### ISSUE TITLE
[bitnami/sonarqube] Difficulties setting up LDAP grep: Unmatched ( or \(

### ISSUE THREAD

**Issue by devent** [bitnami/charts#10005]
### Name and Version

bitnami/sonarqube 1.0.13

### What steps will reproduce the bug?

1. Kubernetes
2. Install helm chart
3. Errors in SonarQube log

### Are you using any custom parameters or values?

```yaml
image:
  debug: true

extraProperties:
  - sonar.security.realm="LDAP"
  - sonar.authenticator.downcase="true"
  - ldap.url="ldap://openldap.kube-ldap.svc.cluster.local:1389"
  - ldap.bindDn="cn=admin,dc=muellerpublic,dc=de"
  - ldap.bindPassword="xxx"
  - ldap.authentication="simple"
  - ldap.user.baseDn="ou=People,dc=muellerpublic,dc=de"
  - ldap.user.request="(&(objectClass=inetOrgPerson)(memberOf=cn=Sonarqube,ou=Group,dc=muellerpublic,dc=de)(|(uid={login})(cn={login})))"
  - ldap.user.realNameAttribute="cn"
  - ldap.user.emailAttribute="mail"
  - ldap.group.baseDn="ou=People,dc=muellerpublic,dc=de"
  - ldap.group.request="(&(objectClass=inetOrgPerson)(memberOf=cn=Sonarqube,ou=Group,dc=muellerpublic,dc=de)(|(uid={login})(cn={login})))"
  - ldap.group.idAttribute="sonarqubeGroups"
```

Tried with and without quotation marks.

### What is the expected behavior?

LDAP is setup.

### What do you see instead?

The attributes are all wrong. Error with grep.

```
sonarqube 14:10:15.36 INFO  ==> Adding properties provided via SONARQUBE_EXTRA_PROPERTIES to sonar.properties
sonarqube 14:10:15.36 DEBUG ==> Setting sonar.security.realm to '"LDAP"' in SonarQube configuration
sonarqube 14:10:15.37 DEBUG ==> Setting sonar.authenticator.downcase to '"true"' in SonarQube configuration
sonarqube 14:10:15.38 DEBUG ==> Setting ldap.url to '"ldap://openldap.kube-ldap.svc.cluster.local:1389"' in SonarQube configuration
sonarqube 14:10:15.39 DEBUG ==> Setting ldap.bindDn="cn to '"cn=admin' in SonarQube configuration
sonarqube 14:10:15.39 DEBUG ==> Setting dc to 'muellerpublic' in SonarQube configuration
sonarqube 14:10:15.40 DEBUG ==> Setting dc to 'de"' in SonarQube configuration
sonarqube 14:10:15.41 DEBUG ==> Setting ldap.bindPassword to '"xxx"' in SonarQube configuration
sonarqube 14:10:15.41 DEBUG ==> Setting ldap.authentication to '"simple"' in SonarQube configuration
sonarqube 14:10:15.42 DEBUG ==> Setting ldap.user.baseDn="ou to '"ou=People' in SonarQube configuration
sonarqube 14:10:15.43 DEBUG ==> Setting dc to 'muellerpublic' in SonarQube configuration
sonarqube 14:10:15.43 DEBUG ==> Setting dc to 'de"' in SonarQube configuration
sonarqube 14:10:15.44 DEBUG ==> Setting ldap.user.request="(&(objectClass=inetOrgPerson)(memberOf=cn to '"(&(objectClass=inetOrgPerson)(memberOf=cn=Sonarqube' in SonarQube configuration
grep: Unmatched ( or \(  
sonarqube 14:10:15.44 DEBUG ==> Setting ou to 'Group' in SonarQube configuration
sonarqube 14:10:15.45 DEBUG ==> Setting dc to 'muellerpublic' in SonarQube configuration
sonarqube 14:10:15.46 DEBUG ==> Setting dc=de)(|(uid={login})(cn to 'de)(|(uid={login})(cn={login})))"' in SonarQube configuration
grep: Unmatched ( or \(  
sonarqube 14:10:15.46 DEBUG ==> Setting ldap.user.realNameAttribute to '"cn"' in SonarQube configuration
sonarqube 14:10:15.47 DEBUG ==> Setting ldap.user.emailAttribute to '"mail"' in SonarQube configuration
sonarqube 14:10:15.47 DEBUG ==> Setting ldap.group.baseDn="ou to '"ou=People' in SonarQube configuration
sonarqube 14:10:15.48 DEBUG ==> Setting dc to 'muellerpublic' in SonarQube configuration
sonarqube 14:10:15.49 DEBUG ==> Setting dc to 'de"' in SonarQube configuration
sonarqube 14:10:15.49 DEBUG ==> Setting ldap.group.request="(&(objectClass=inetOrgPerson)(memberOf=cn to '"(&(objectClass=inetOrgPerson)(memberOf=cn=Sonarqube' in SonarQube configuration
grep: Unmatched ( or \(  
sonarqube 14:10:15.50 DEBUG ==> Setting ou to 'Group' in SonarQube configuration
sonarqube 14:10:15.50 DEBUG ==> Setting dc to 'muellerpublic' in SonarQube configuration
sonarqube 14:10:15.51 DEBUG ==> Setting dc=de)(|(uid={login})(cn to 'de)(|(uid={login})(cn={login})))"' in SonarQube configuration
grep: Unmatched ( or \(
sonarqube 14:10:15.52 DEBUG ==> Setting ldap.group.idAttribute to '"sonarqubeGroups"' in SonarQube configuration
```
