### ISSUE TITLE
[bitnami/airflow] Issue with Git from Dag

### ISSUE THREAD

**Issue by Kydybets** [bitnami/charts#10017]
### Name and Version

bitnamin/airflow 12.2.1

### What steps will reproduce the bug?

This is not actually a bug.
The issue itself is that we are trying to do manipulation with Git inside DAG itself, and we are getting each time permissions are denied, the key itself is working, cause we have mounted the to clone and sync our private repositories.

### Are you using any custom parameters or values?
```yaml
web:
  image:
    pullPolicy: IfNotPresent
  extraVolumeMounts:
    - name: dind-storage
      mountPath: /var/lib/docker
    - name: terraform-credentials
      mountPath: /.aws
    - name: git-clone-secret
      mountPath: /keys
    - name: git-clone-local-keys
      mountPath: /home/bitnami/.ssh
  extraVolumes:
    - name: dind-storage
      emptyDir: {}
    - name: git-clone-local-keys
      emptyDir: {}
    - name: git-clone-secret
      secret:
        secretName: airflow-dwh-bitbucket-ssh-keys
        defaultMode: 256
    - name: terraform-credentials
      secret:
        secretName: airflow-dwh-terraform-aws-credentials
  nodeSelector:
    node_pool: app
  resources:
    limits:
      cpu: 850m
      memory: 2Gi
    requests:
      memory: 1Gi
      cpu: 500m
  containerSecurityContext:
    enabled: false
    runAsUser: 1001
    runAsNonRoot: false
  podSecurityContext:
    enabled: false


scheduler:
  image:
    pullPolicy: IfNotPresent
  extraVolumeMounts:
    - name: dind-storage
      mountPath: /var/lib/docker
    - name: terraform-credentials
      mountPath: /.aws
    - name: git-clone-secret
      mountPath: /keys
    - name: git-clone-local-keys
      mountPath: /home/airflow/.ssh
  extraVolumes:
    - name: dind-storage
      emptyDir: {}
    - name: git-clone-local-keys
      emptyDir: {}
    - name: git-clone-secret
      secret:
        secretName: airflow-dwh-bitbucket-ssh-keys
        defaultMode: 256
    - name: terraform-credentials
      secret:
        secretName: airflow-dwh-terraform-aws-credentials
  nodeSelector:
    node_pool: app
  resources:
    limits:
      cpu: 850m
      memory: 2Gi
    requests:
      memory: 1Gi
      cpu: 500m
  containerSecurityContext:
    enabled: false
    runAsUser: 1001
    runAsNonRoot: false
  podSecurityContext:
    enabled: false

worker:
  image:
    pullPolicy: IfNotPresent
  extraVolumeMounts:
    - name: dind-storage
      mountPath: /var/lib/docker
    - name: terraform-credentials
      mountPath: /.aws
    - name: git-clone-secret
      mountPath: /keys
    - name: git-clone-local-keys
      mountPath: /home/bitnami/.ssh
  extraVolumes:
    - name: dind-storage
      emptyDir: {}
    - name: git-clone-local-keys
      emptyDir: {}
    - name: git-clone-secret
      secret:
        secretName: airflow-dwh-bitbucket-ssh-keys
        defaultMode: 256
    - name: terraform-credentials
      secret:
        secretName: airflow-dwh-terraform-aws-credentials
  initContainers:
  - name: configure-keys
    image: busybox:latest
    command: ["/bin/ash", "-ec"]
    args:
      - >-
        cp -rL /keys/* ~/.ssh/ &&
        chmod 600 ~/.ssh/* &&
        mkdir -p ~/.ssh/airflow &&
        cp -rL /keys/* ~/.ssh/airflow &&
        chown -R 1001:1001 ~/.ssh/airflow/ &&
        chmod 600 ~/.ssh/airflow/*
    volumeMounts:
    - name: git-clone-secret
      mountPath: /keys
    - name: git-clone-local-keys
      mountPath: /root/.ssh
  nodeSelector:
    node_pool: app
  resources:
    limits:
      cpu: 850m
      memory: 2Gi
    requests:
      memory: 1Gi
      cpu: 500m
  containerSecurityContext:
    enabled: false
    runAsUser: root
    runAsNonRoot: false
  podSecurityContext:
    enabled: false


git:
  clone:
    extraVolumeMounts:
    - name: git-clone-secret
      mountPath: /keys
    - name: git-clone-local-keys
      mountPath: /root/.ssh

  sync:
    extraVolumeMounts:
    - name: git-clone-secret
      mountPath: /keys
    - name: git-clone-local-keys
      mountPath: /root/.ssh

externalDatabase:
  database: airflow
  port: 5432

postgresql:
  enabled: false

metrics:
  enabled: true
```

### What is the expected behavior?

We would like to use the git python inside dag because of logic that requires interruption with Git

### What do you see instead?
```
Could not create directory '/home/airflow/.ssh'.
load pubkey "/ssh-keys/id_rsa": Permission denied
Warning: Permanently added '[test.internal]:7999,[10.1.1.1]:7999' (RSA) to the list of known hosts.
Load key "/ssh-keys/id_rsa": Permission denied
git@bitbucket.trustonic.internal: Permission denied (publickey).
fatal: Could not read from remote repository.
```
