### ISSUE TITLE
Mongodb-sharded custom user and db is not creating

### ISSUE THREAD

**Issue by pankaj-dahiya** [bitnami/charts#10018]
### Name and Version

bitnami/mongo-sharded    ---   version: 5.0.0

### What steps will reproduce the bug?

Assign values to these variables :
```yaml
  username: "pankaj"
  password: "randompassword"
  database: "pankaj"
```

### What is the expected behavior?

We can connect mongob via custom user and password.

### What do you see instead?

Connection failed. Checked by connecting via root password and found that custom user and password are not created.
