### ISSUE TITLE
MongoDB - exporter --compatible-mode

### ISSUE THREAD

**Issue by solcik** [bitnami/charts#10026]
### Name and Version

bitnami/mongodb 12.0.0

### What is the problem this feature will solve?

It would be great to be able to define compatible-mode extra parameter for the mongodb-exporter

- https://github.com/bitnami/charts/tree/master/bitnami/mongodb
- https://github.com/percona/mongodb_exporter#enabling-compatibility-mode
- https://www.percona.com/blog/2020/09/22/new-mongodb-exporter-released-with-percona-monitoring-and-management-2-10-0/

### What is the feature you are proposing to solve the problem?

To add new parameter, which is going to enable compatible-mode for the exporter.

**Comment by carrodher** [comment]
Currently, there is an option to pass extra flags to the exporter, not sure if this can work for your use case
```yaml
metrics:
  ## @param metrics.extraFlags String with extra flags to the metrics exporter
  ## ref: https://github.com/percona/mongodb_exporter/blob/master/mongodb_exporter.go
  ##
  extraFlags: ""
```

Apart from that, I just created the attached PR so there is a `metrics.command` and `metrics.args` parameters where you can use any value in order to override the default ones.
