### ISSUE TITLE
redis lifecycleHooks does not work when sentinel enabled

### ISSUE THREAD

**Issue by oppianmatt** [bitnami/charts#10027]
### Name and Version

bitname/redis 16.8.9

### What steps will reproduce the bug?

Readme and values imply we can set lifecycle hooks to run but we can't because of duplicate lifecycle keys in the yaml

https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/sentinel/statefulset.yaml#L99

![image](https://user-images.githubusercontent.com/48596/166828818-e64a666a-9e44-4c0c-9bb7-0e735dff5b5c.png)

is overridden due to a duplicate key later down here

https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/sentinel/statefulset.yaml#L267

![image](https://user-images.githubusercontent.com/48596/166828922-9a3836e6-9b79-4121-aa84-0843082a55ce.png)

note the sentinel image has the same problem

![image](https://user-images.githubusercontent.com/48596/166829018-e1e1a5cc-2d53-4842-b99c-2893db838d15.png)

![image](https://user-images.githubusercontent.com/48596/166829040-64e24e31-9649-4e62-8a07-6c8d2c8f5987.png)

### Are you using any custom parameters or values?

```yaml
  sentinel:
    enabled: true
  replica:
    lifecycleHooks:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo Hello from the postStart handler > $HOME/message"]
```

### What is the expected behavior?

```yaml
...
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo Hello from the postStart handler > $HOME/message"]
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - /opt/bitnami/scripts/start-scripts/prestop-redis.sh
...
```

### What do you see instead?

```yaml
...
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - /opt/bitnami/scripts/start-scripts/prestop-redis.sh
...
```
