### ISSUE TITLE
[bitnami/redis] master.persistence.storageClass not working

### ISSUE THREAD

**Issue by peio-burucoa** [bitnami/charts#10036]
### Name and Version

bitnami/redis/templates 16.4.5

### What steps will reproduce the bug?

I'm using Redis templates and in my `values.yml` I'm using the following values:
```
...
my-store:
  master:
    kind: Deployment
    persistence:
      enabled: true
      storageClass: azurefile
...
```

However, when running the following command: `reckoner plot --log-level=DEBUG --run-all --create-namespace --helm-args=--wait $CI_PROJECT_DIR/deployment/reckoner/course.yml`,
I'm getting the following error message:
```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(PersistentVolumeClaim.spec.resources): unknown field "storageClassName" in io.k8s.api.core.v1.ResourceRequirements
```
And the PersistenceVolumeClaim generated looks like the following:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-my-store-master
  labels:
    app.kubernetes.io/name: my-store
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/component: master
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
    storageClassName: azurefile
```
If I remove the `storageClass` then everything's working properly.

### What do you see instead?

Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(PersistentVolumeClaim.spec.resources): unknown field "storageClassName" in io.k8s.api.core.v1.ResourceRequirements

### Additional information

It seems to me there's an indent issue in the PersistenceVolumeClaim generated, could it be related to this `nindent` value https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/master/pvc.yaml#L25 ?
