### ISSUE TITLE
[bitnami/nginx-ingress-controller] Unable to deploy HorizontalPodAutoscaler on cluster >= 1.23.0

### ISSUE THREAD

**Issue by RenaudDemarneffe** [bitnami/charts#10059]
### Name and Version

bitnami/nginx-ingress-controller 9.1.27

### What steps will reproduce the bug?

1. Enable autoscaling into the values.yaml
```
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 80
  targetMemory: 80
```
2. Deploy `helm install nginx bitnami/nginx-ingress-controller -f values.yaml`

### Are you using any custom parameters or values?

Enable autoscaling into the values.yaml
```
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 80
  targetMemory: 80
```

### What is the expected behavior?

The deployment of the HorizontalPodAutoscaler resource.

### What do you see instead?

The error
```
error: error validating "render/nginx-ingress-controller/templates/controller-hpa.yaml": error validating data: [ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): unknown field "targetAverageUtilization" in io.k8s.api.autoscaling.v2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): missing required field "target" in io.k8s.api.autoscaling.v2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[1].resource): unknown field "targetAverageUtilization" in io.k8s.api.autoscaling.v2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[1].resource): missing required field "target" in io.k8s.api.autoscaling.v2.ResourceMetricSource]; if you choose to ignore these errors, turn validation off with --validate=false
```

### Additional information

It seems that the `HorizontalPodAutoscaler` resource into the version `autoscaling/v2` has the fields `targetAverageUtilization` and `targetAverageUtilization` renamed into the following structure:
```
target:
        type: Utilization
        averageUtilization: 75
```
