### ISSUE TITLE
Sentinel not started

### ISSUE THREAD

**Issue by torbenaa** [bitnami/charts#10055]
### Name and Version

bitnami/redis 16.8.10

### What steps will reproduce the bug?
```
helm install --namespace bitnami-redis --create-namespace --values values.yaml rs1 bitnami/redis
```
### Are you using any custom parameters or values?
```yaml
global:
  redis:
    password: test1234
...
replica:
  replicaCount: 3
...
sentinel:
  enabled: true
```

### What is the expected behavior?

Containers with sentinel running

### What do you see instead?

No sentinel processes anywhere.
