### ISSUE TITLE
harbor keeps generating extra pods for seemingly no reason

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#10052]
### Name and Version

bitnami/harbor:12.3.5

### What steps will reproduce the bug?

```console
$ k version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
```
Install and wait ...

### Are you using any custom parameters or values?

`$ cat base/values.yaml`
```yaml
harbor:
  externalURL: https://harbor.k.home.net
  exposureType: ingress

  ingress:

    core:
      tls: true
      hostname: harbor.k.home.net
      ingressClassName: nginx
      annotations:
        ingress.kubernetes.io/ssl-redirect: 'true'
        ingress.kubernetes.io/proxy-body-size: '0'
        nginx.ingress.kubernetes.io/ssl-redirect: 'true'
        nginx.ingress.kubernetes.io/proxy-body-size: '0'
        cert-manager.io/issuer: "cluster-adcs-issuer"                   #use specific name of issuer
        cert-manager.io/issuer-kind: "ClusterAdcsIssuer"                #or ClusterAdcsIssuer
        cert-manager.io/issuer-group: "adcs.certmanager.csf.nokia.com"

    notary:
      tls: true
      hostname: notary.k.home.net
      ingressClassName: nginx
      annotations:
        ingress.kubernetes.io/ssl-redirect: 'true'
        ingress.kubernetes.io/proxy-body-size: '0'
        nginx.ingress.kubernetes.io/ssl-redirect: 'true'
        nginx.ingress.kubernetes.io/proxy-body-size: '0'
        cert-manager.io/issuer: "cluster-adcs-issuer"                   #use specific name of issuer
        cert-manager.io/issuer-kind: "ClusterAdcsIssuer"                #or ClusterAdcsIssuer
        cert-manager.io/issuer-group: "adcs.certmanager.csf.nokia.com"

  persistence:
    enabled: true

    persistentVolumeClaim:
      registry:
        size: 1000Gi
```

### What is the expected behavior?

Working setup

### What do you see instead?

A setup which never seems fully up, see this listing which shows duplicate pods for some reason:
```console
$ k get all
NAME                                        READY   STATUS              RESTARTS   AGE
pod/harbor-chartmuseum-6946f4cd46-2zzst     1/1     Running             0          4d19h
pod/harbor-chartmuseum-d6857ccb8-9bl74      0/1     ContainerCreating   0          142m
pod/harbor-core-79f8554df6-949sm            1/1     Running             0          142m
pod/harbor-jobservice-9c4cc5698-q4mc7       1/1     Running             0          4d19h
pod/harbor-jobservice-db6d96f74-b8qzn       0/1     ContainerCreating   0          142m
pod/harbor-notary-server-5c84947966-vw8jj   1/1     Running             0          142m
pod/harbor-notary-signer-7574f74b9f-gzrgd   1/1     Running             0          142m
pod/harbor-portal-d474fd6f9-pvx7h           1/1     Running             0          4d19h
pod/harbor-postgresql-0                     1/1     Running             0          11d
pod/harbor-redis-master-0                   1/1     Running             0          11d
pod/harbor-registry-66bfd4dfbc-rmnnp        0/2     ContainerCreating   0          142m
pod/harbor-registry-7f7798b474-jtf4n        2/2     Running             0          4d19h
pod/harbor-trivy-0                          1/1     Running             0          11d

NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/harbor-chartmuseum      ClusterIP   10.110.142.191   <none>        80/TCP              11d
service/harbor-core             ClusterIP   10.96.22.102     <none>        80/TCP              11d
service/harbor-jobservice       ClusterIP   10.98.121.196    <none>        80/TCP              11d
service/harbor-notary-server    ClusterIP   10.107.61.95     <none>        4443/TCP            11d
service/harbor-notary-signer    ClusterIP   10.107.170.206   <none>        7899/TCP            11d
service/harbor-portal           ClusterIP   10.99.198.146    <none>        80/TCP              11d
service/harbor-postgresql       ClusterIP   10.106.45.101    <none>        5432/TCP            11d
service/harbor-postgresql-hl    ClusterIP   None             <none>        5432/TCP            11d
service/harbor-redis-headless   ClusterIP   None             <none>        6379/TCP            11d
service/harbor-redis-master     ClusterIP   10.110.34.255    <none>        6379/TCP            11d
service/harbor-registry         ClusterIP   10.104.55.227    <none>        5000/TCP,8080/TCP   11d
service/harbor-trivy            ClusterIP   10.100.107.16    <none>        8080/TCP            11d

NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/harbor-chartmuseum     1/1     1            1           11d
deployment.apps/harbor-core            1/1     1            1           11d
deployment.apps/harbor-jobservice      1/1     1            1           11d
deployment.apps/harbor-notary-server   1/1     1            1           11d
deployment.apps/harbor-notary-signer   1/1     1            1           11d
deployment.apps/harbor-portal          1/1     1            1           11d
deployment.apps/harbor-registry        1/1     1            1           11d

NAME                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/harbor-chartmuseum-6946f4cd46     1         1         1       4d19h
replicaset.apps/harbor-chartmuseum-69589b9b85     0         0         0       3d20h
replicaset.apps/harbor-chartmuseum-86b96795c5     0         0         0       2d20h
replicaset.apps/harbor-chartmuseum-86d7f96dd5     0         0         0       44h
replicaset.apps/harbor-chartmuseum-945b5f995      0         0         0       26h
replicaset.apps/harbor-chartmuseum-d6857ccb8      1         1         0       142m
replicaset.apps/harbor-core-54679f74f             0         0         0       26h
replicaset.apps/harbor-core-58c6865d5c            0         0         0       3d20h
replicaset.apps/harbor-core-5bbb9d87c7            0         0         0       44h
replicaset.apps/harbor-core-79cf958cf             0         0         0       4d19h
replicaset.apps/harbor-core-79f8554df6            1         1         1       142m
replicaset.apps/harbor-core-86bc87bb9             0         0         0       2d20h
replicaset.apps/harbor-jobservice-67cd9664c7      0         0         0       3d20h
replicaset.apps/harbor-jobservice-6db984fc46      0         0         0       2d20h
replicaset.apps/harbor-jobservice-6f4786f944      0         0         0       26h
replicaset.apps/harbor-jobservice-845b5d96d9      0         0         0       44h
replicaset.apps/harbor-jobservice-9c4cc5698       1         1         1       4d19h
replicaset.apps/harbor-jobservice-db6d96f74       1         1         0       142m
replicaset.apps/harbor-notary-server-5c84947966   1         1         1       142m
replicaset.apps/harbor-notary-server-5f98f5d76f   0         0         0       2d20h
replicaset.apps/harbor-notary-server-6887dcbc94   0         0         0       4d19h
replicaset.apps/harbor-notary-server-68bfd97df    0         0         0       26h
replicaset.apps/harbor-notary-server-6cdf98bcf5   0         0         0       3d20h
replicaset.apps/harbor-notary-server-746d6945cc   0         0         0       44h
replicaset.apps/harbor-notary-signer-647785c8f6   0         0         0       26h
replicaset.apps/harbor-notary-signer-6c67f68989   0         0         0       3d20h
replicaset.apps/harbor-notary-signer-7574f74b9f   1         1         1       142m
replicaset.apps/harbor-notary-signer-79bc6d67f4   0         0         0       44h
replicaset.apps/harbor-notary-signer-b4d7cddf     0         0         0       2d20h
replicaset.apps/harbor-notary-signer-f648997bd    0         0         0       4d19h
replicaset.apps/harbor-portal-d474fd6f9           1         1         1       4d19h
replicaset.apps/harbor-registry-55b489dbf8        0         0         0       44h
replicaset.apps/harbor-registry-5c88745765        0         0         0       26h
replicaset.apps/harbor-registry-5f95854ddf        0         0         0       2d20h
replicaset.apps/harbor-registry-66bfd4dfbc        1         1         0       142m
replicaset.apps/harbor-registry-7b49c896b9        0         0         0       3d20h
replicaset.apps/harbor-registry-7f7798b474        1         1         1       4d19h

NAME                                   READY   AGE
statefulset.apps/harbor-postgresql     1/1     11d
statefulset.apps/harbor-redis-master   1/1     11d
statefulset.apps/harbor-trivy          1/1     11d
```

### Additional information

- If I run `k delete rs --all` I'll end up with a working situation, but within about an hour this pod duplication will start again.
- Am also using argocd, but don't think that matters.
