### ISSUE TITLE
Unable to deploy arbiters in mongodb-sharded

### ISSUE THREAD

**Issue by praemo-admin** [bitnami/charts#10062]
### Name and Version

bitnami/mongodb-sharded 5.0.0

### What steps will reproduce the bug?

In kubernetes on AKS

With config: `values.yaml`:

```configsvr:
  replicaCount: 2
kubeVersion: ""
mongos:
  replicaCount: 2
shards: 5
shardsvr:
  arbiter:
    replicaCount: 1
  dataNode:
    replicaCount: 2
```
    
Execute:
`helm template mongodb bitnami/mongodb-sharded --values values.yaml`

Recieve error:
```
template: mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml:133:155: executing "mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml" at <.Values.clusterDomain>: can't evaluate f
ield Values in type int
```

### Are you using any custom parameters or values?

```
configsvr:
  replicaCount: 2
kubeVersion: ""
mongos:
  replicaCount: 2
shards: 5
shardsvr:
  arbiter:
    replicaCount: 1
  dataNode:
    replicaCount: 2
```

### What is the expected behavior?

mongodb-sharded deployed, including 5 shards @ 2 replicas + 1 arbiter, 2 configsvr, 2 mongos

### What do you see instead?

```
template: mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml:133:155: executing "mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml" at <.Values.clusterDomain>: can't evaluate field Values in type int
```

### Additional information

Removing the arbiter section from values.yaml allows success, without arbiter nodes.
