### ISSUE TITLE
Prometheus: volumePermissions is missing from the chart

### ISSUE THREAD

**Issue by Maelstromeous** [bitnami/charts#10073]
### Name and Version

bitnami/kube-prometheus-6.10.2

### What steps will reproduce the bug?

1. Observe the variables possible for kube-prometheus-6.10.2
2. See volumePermissions is missing

I can confirm that it also does not inject the initContainer that fixes the volume permissions issues, which is present on the Redis chart for instance. I require this as my cluster does not seem to respect the security policy.

### Are you using any custom parameters or values?

volumePermissions.enabled=true

### What is the expected behavior?

volumePermissions should be both available and actually inject the init container required to set the permissions on the volume.

### What do you see instead?

The key is not present and thus my pod won't initalize when a volume is attached due to the error:

```
 msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
panic: Unable to create mmap-ed active query log
```

This is due to a permissions error on the data directory.

### Additional information

Whatever you guys did for the Redis chart, please do here! 🙂

**Comment by Maelstromeous** [comment]
Turns out it was an OVH kubernetes cluster thing. 

https://docs.ovh.com/gb/en/kubernetes/persistentvolumes-permission-errors/

Adding volumePermissions in this case would have done absolutely nothing as the initContainer could not achieve root in the slightest (believe me, I tried adding initContainers to replicate what volumePermissions would do but it completely failed).

However, that being said, there may be still some value to adding it for other use cases.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by FeiYing9** [comment]
can this reopen,, this problem still exist

**Comment by FeiYing9** [comment]
@carrodher   the key problem is that, the storage path is `/prometheus` while this is just a link to the real path `/opt/bitnami/prometheus/data`

```bash
docker run --rm -it bitnami/prometheus:2.34.0-debian-10-r12 bash
$ ls -l /prometheus
lrwxrwxrwx 1 root root 28 Apr 18  2022 /prometheus -> /opt/bitnami/prometheus/data
```

so, it's useless to chown the mount path of `/prometheus`

**Comment by FeiYing9** [comment]
the temporary solution is to add a initcontainer like this:
```yaml
      - command:
        - /bin/bash
        - -ec
        - |
          chown -R {{ .Values.prometheus.podSecurityContext.runAsUser }}:{{ .Values.prometheus.podSecurityContext.fsGroup }} /prometheus /opt/bitnami/prometheus/data
        image: bitnami/prometheus:2.34.0-debian-10-r12
        imagePullPolicy: IfNotPresent
        name: volume-permissions
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /opt/bitnami/prometheus/data
          name: prometheus-prometheus-db
          subPath: prometheus-db
```
why just use `/prometheus` as the storage path?
