### ISSUE TITLE
solr chart with enabled zookeeper tls and auth

### ISSUE THREAD

**Issue by leonidUH** [bitnami/charts#10071]
### Name and Version

bitnami/solr:8.11.1

### What steps will reproduce the bug?

1 enabled zookeeper AUTH or TLS in values.yaml

### Are you using any custom parameters or values?

```
zookeeper:
  auth:
    enabled: true
    clientUser: "zooUser"
    clientPassword: "zooPass"
    serverUsers: "zooUser"
    serverPasswords: "zooPass"
  tls:
    client:
      enabled: true
      autoGenerated: true
    quorum:
      enabled: true
      autoGenerated: true
```

### What is the expected behavior?

expected that zookeeper will be secured with tls and auth

### What do you see instead?

solr pod in crush loop mode

### Additional information

 
 Solr chart  ignore 'tls' because still use zookeeper regular port 2181 and not security  3181. 
 But after manual change to security port it still not working.
Also Solr pod in CrashLoopBackOff if I add zookeeper AUTH values
  
 Just to make sure now Solr doesn't work with zookeeper TLS and AUTH? I'm right?
