### ISSUE TITLE
ES8 unable to authenticate user [kibana_system] for REST request

### ISSUE THREAD

**Issue by mokhos** [bitnami/charts#10076]
### Name and Version

bitnami/elasticsearch 18.0.1

### What steps will reproduce the bug?

Upgrading from bitnami/elasticsearch 17.9.29 caused the error. I intend to install kibana alongside with Elasticsearch. 
Apparently with ES8 comes breaking changes. I have edited my values.yaml to be fit with the new one. But constantly I get this error.

Any idea?

### Are you using any custom parameters or values?
       
```
        Security.elasticPassword: "x"
        Security.tls.autoGenerated: true
        Security.tls.restEncryption: true
        elasticsearch.security.kibanaPassword: "x"
```

### What is the expected behavior?

Kibana to connect to elastic instance.

### What do you see instead?

`
[2022-05-09T10:27:33.799+00:00][ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. security_exception: [security_exception] Reason: unable to authenticate user [kibana_system] for REST request [/_nodes?filter_path=nodes.*.version%2Cnodes.*.http.publish_address%2Cnodes.*.ip]
`

**Comment by FraPazGal** [comment]
Hello @mokhos,

Did you make any `values.yaml` modifications besides the ones for your custom parameters? Could you please share the `helm upgrade` command you are executing?

**Comment by mokhos** [comment]
Hi @FraPazGal 

Thanks for your response.

I'm actuallly getting different errors which caused me to be totally confused. The latest error I get is like below which I don't understand.

`Unable to retrieve version information from Elasticsearch nodes. security_exception: [security_exception] Reason: unable to authenticate user [kibana_system] for REST request`

This is my configuration regarding kibana:
```

kibana:
  elasticsearch:
    hosts:
      - '{{ include "elasticsearch.service.name" . }}'
    port: '{{ include "elasticsearch.service.ports.restAPI" . }}'
    security:
      auth:
        enabled: true
        # default in the elasticsearch chart is elastic
        kibanaUsername: "elastic"
        kibanaPassword: "x"
      tls:
        # Instruct kibana to connect to elastic over https
        enabled: true
        verificationMode: "none"
        # Bit of a catch 22, as you will need to know the name upfront of your release
        existingSecret: elasticsearch-coordinating-only-crt
        # As the certs are auto-generated, they are pemCerts so set to true
        usePemCerts: true
```

Note 1: I tested `kibanaUsername: "kibana_system"` but it didn't work.
Note 2: For some unknown reason, `existingSecret` for kibana must be `elasticsearch-coordinating-only-crt`, otherwise I get this DNS error. The thing is, apprently no `elasticsearch-coordinating-only` pod will be installed anymore and I had to copy the certificate from another installation.

**Comment by FraPazGal** [comment]
Hello @mokhos,

I reproduced your issue but I'm missing some pieces on how the new chart version works compared to the previous one. Let me make some more tests and check with my colleagues before I draw any conclusions. I'll come back with more news as soon as possible.

**Comment by Rhymen** [comment]
Hello,

we got the same issue, but with a fresh install and a somewhat different configuration. We are trying to start 3 master nodes.

```
coordinating:
  replicaCount: 0
data:
  replicaCount: 0
global:
  elasticsearch:
    service:
      name: elasticsearch-master
ingest:
  replicaCount: 0
kibana:
  elasticsearch:
    hosts:
      - '{{ include "elasticsearch.service.name" . }}'
    port: '{{ include "elasticsearch.service.ports.restAPI" . }}'
    security:
      auth:
        enabled: true
        kibanaUsername: 'elastic'
        kibanaPassword: 'x'
      tls:
        enabled: true
        existingSecret: log-elasticsearch-master-crt
        usePemCerts: true
master:
  masterOnly: false
  replicaCount: 3
security:
  elasticPassword: 'x'
  enabled: true
  tls:
    autoGenerated: true
```

```
[2022-05-20T13:32:27.579+00:00][ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. security_exception: [security_exception] Reason: unable to authenticate user [kibana_system] for REST request [/_nodes filter_path=nodes.*.version%2Cnodes.*.http.publish_address%2Cnodes.*.ip]
```

Is this an issue with the chart / es version or is the master only configuration problematic?

**Comment by FraPazGal** [comment]
Hello @Rhymen, @mokhos,

We are currently working on fixing related issues in https://github.com/bitnami/charts/pull/10237 and https://github.com/bitnami/charts/pull/10238 and are aware of these issues. I'll leave this thread open and come back with more news ASAP. Thank you for your patience!

**Comment by mokhos** [comment]
Hi @migruiz4 

Thanks for the info. But the problem still persist, doesn't it?

As a test, I tried to do exactly as you described. I think something goes wrong when setting `createSystemUser: true` as it throw this error:
`
cannot patch "elasticsearch-18-1653317575-kibana" with kind Deployment: Deployment.apps "elasticsearch-18-1653317575-kibana" is invalid: spec.template.spec.containers[0].env[7].valueFrom.secretKeyRef.name: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') 
`

**Comment by migruiz4** [comment]
Hi @mokhos,

Yes, the issue with certificates validation when using autogenerated certs still persists, but this PR should fix it: https://github.com/bitnami/charts/pull/10238/files

**Comment by mooncser** [comment]
Hi @migruiz4 
Did you commit the fix already? It still showed same error as @mokhos mentioned when I tried with plain-text password. Thank you.

**Comment by migruiz4** [comment]
Hi @mooncser,

Yes, the changes have been already released. Are you using the latest version of the chart?

```
$ helm repo update                                  
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
$ helm search repo bitnami/elasticsearch
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
bitnami/elasticsearch   18.2.5          8.2.2           Elasticsearch is a distributed search and analy...
```

**Comment by mooncser** [comment]
Hi @migruiz4,

I have not tried latest chart version yet. It worked when I used with `elasticsearchPasswordSecret` with key 'elasticsearch-password'.  I will try another method. Thanks.

**Comment by mokhos** [comment]
Hi @migruiz4 
I tried the new chart as a fresh installation, but apparently the problem still persist.

1. Enabling `createSystemUser: true` for kibana will end up throwing this:
`Error: INSTALLATION FAILED: Deployment.apps "elasticsearch-kibana" is invalid: spec.template.spec.containers[0].env[7].valueFrom.secretKeyRef.name: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') `

2. Now that there is no `coordinating-only` pod, what should be used instead? [The documentation](https://artifacthub.io/packages/helm/bitnami/elasticsearch#elasticsearch-rest-encryption) is still old. Would it be possible to update it with a working example? 

This is my kibana configuration which does NOT work by the way:
`kibana:
  elasticsearch:
    hosts:
      - '{{ include "elasticsearch.service.name" . }}'
    port: '{{ include "elasticsearch.service.ports.restAPI" . }}'
    security:
      auth:
        enabled: true
        kibanaPassword: "!asUKhuw@9J#hRJfa3"
        createSystemUser: true
      tls:
        # Instruct kibana to connect to elastic over https
        enabled: true
        verificationMode: "none"
        # Bit of a catch 22, as you will need to know the name upfront of your release
        #existingSecret: elasticsearch-coordinating-only-crt
        usePemCerts: true`

**Comment by mokhos** [comment]
@migruiz4 , Would you please give an update about this issue?

**Comment by migruiz4** [comment]
Hi @mokhos,

I'm sorry for the late response.

The followings are working examples of Elasticsearch values with TLS:
```yaml
global:
  kibanaEnabled: true
master:
  replicaCount: 3
  masterOnly: false
data:
  replicaCount: 0
coordinating:
  replicaCount: 0
ingest:
  replicaCount: 0
security:
  enabled: true
  tls:
    autoGenerated: true
kibana:
  elasticsearch:
    hosts:
      - elastic-elasticsearch
    port: 9200
    security:
      auth:
        enabled: true
        createSystemUser: true
        kibanaPassword: secretPass
        elasticsearchPasswordSecret: elastic-elasticsearch      
      tls:
        enabled: true
        existingSecret: elastic-elasticsearch-master-crt
        usePemCerts: true
```

If coordinating-only nodes are enabled:
```yaml
global:
  kibanaEnabled: true
master:
  replicaCount: 3
  masterOnly: false
data:
  replicaCount: 0
coordinating:
  replicaCount: 2
ingest:
  replicaCount: 0
security:
  enabled: true
  tls:
    autoGenerated: true
kibana:
  elasticsearch:
    hosts:
      - elastic-elasticsearch
    port: 9200
    security:
      auth:
        enabled: true
        createSystemUser: true
        kibanaPassword: secretPass
        elasticsearchPasswordSecret: elastic-elasticsearch      
      tls:
        enabled: true
        existingSecret: elastic-elasticsearch-coordinating-crt
        usePemCerts: true
```

> Now that there is no coordinating-only pod, what should be used instead? [The documentation](https://artifacthub.io/packages/helm/bitnami/elasticsearch#elasticsearch-rest-encryption) is still old. Would it be possible to update it with a working example?

Thank you for your feedback, I will update the chart readme to reflect the latest changes.

**Comment by mokhos** [comment]
Hi @migruiz4 

Thank you so much for all your help and support.
I can confirm that the issue is fixed and My Kibana and ES8 are up and running. (Chart version: 18.2.9)

I close the issue then.

**Comment by LinTechSo** [comment]
Hi, any updates ?

**Comment by FraPazGal** [comment]
Hello @LinTechSo,

As last discussed, the reported issue was fixed and thus the thread closed. Have you encountered this problem in our latest chart version? If so, please detail your environment and any relevant info.

If the issue is a different one, please open a new thread so we maintain the forum properly organized.

**Comment by LinTechSo** [comment]
Hi @FraPazGal,
Thanks for the response
The followings are not working for me on version 8.2.0 and the error is the same as above
```
global:
  kibanaEnabled: true
master:
  replicaCount: 1
  masterOnly: true
data:
  replicaCount: 0
coordinating:
  replicaCount: 0
ingest:
  replicaCount: 0
security:
  enabled: true
  tls:
    autoGenerated: true
kibana:
  elasticsearch:
    hosts:
      - elastic-elasticsearch
    port: 9200
    security:
      auth:
        enabled: true
        createSystemUser: true
        kibanaPassword: secretPass
        elasticsearchPasswordSecret: my-elaastic-seacret     
      tls:
        enabled: true
        existingSecret: elastic-elasticsearch-master-crt
        usePemCerts: true
```

**Comment by LinTechSo** [comment]
After if fresh install and update it to the latest version 

```
kibana 08:23:52.30 INFO  ==> ** Starting Kibana setup **
kibana 08:23:52.32 INFO  ==> Configuring/Initializing Kibana...
kibana 08:23:52.35 INFO  ==> Found mounted configuration directory
kibana 08:23:52.43 INFO  ==> Waiting for Elasticsearch to be ready.
kibana 08:23:52.52 INFO  ==> Setting password for user 'kibana_system'
kibana 08:24:52.72 ERROR ==> An error occurred while configuring kibana_system user
```


‍‍‍```
failed to retrieve password hash for reserved user [kibana_system]
org.elasticsearch.action.UnavailableShardsException: at least one primary shard for the index [.security-7] is unavailable
```

**Comment by migruiz4** [comment]
Hi @LinTechSo,

This error means the Elasticsearch cluster is not in green status and the `security` index is not available (red status).
Could you please check the status and logs of your Elasticsearch pods?

If your cluster is responsing, please run the following API call `/cluster/_health`

**Comment by LinTechSo** [comment]
Hi @migruiz4 , thanks for the response. 
i solved my problem by setting masterOnly to false for single set up.

**Comment by Pyttei** [comment]
Hi,
I seem to have the same kind of problem. When restEncryption is set to true I can access Kibana normally, but I can't access Elasticsearch from the browser (502 error, `[elasticsearch-coordinating-0] received plaintext http traffic on an https channel, closing connection Netty4HttpChannel`). When restEncryption is set to false I can access Elasticsearch but I can't access Kibana (503 error, Kibana log says either waiting for Elasticsearch or something like No license). These are my settings, otherwise my cluster uses the default settings in 18.2.15. What settings should I have so I can access them both?
```
kibana:
  elasticsearch:
    hosts:
      - '{{ include "elasticsearch.service.name" . }}'
    port: '{{ include "elasticsearch.service.ports.restAPI" . }}'
    security:
      auth:
        createSystemUser: true
        elasticsearchPasswordSecret: elasticsearch
        enabled: true
        kibanaPassword: specialpassword
      tls:
        enabled: true
        existingSecret: elasticsearch-coordinating-crt
        usePemCerts: true
```
```
security:
  elasticPassword: ''
  enabled: true
  existingSecret: ''
  fipsMode: false
  tls:
    autoGenerated: true
    coordinating:
      existingSecret: ''
    data:
      existingSecret: ''
    ingest:
      existingSecret: ''
    keyPassword: ''
    keystoreFilename: elasticsearch.keystore.jks
    keystorePassword: ''
    master:
      existingSecret: ''
    passwordsSecret: ''
    restEncryption: false
    secretKey: ''
    secretKeystoreKey: ''
    secretTruststoreKey: ''
    truststoreFilename: elasticsearch.truststore.jks
    truststorePassword: ''
    usePemCerts: true
    verificationMode: full
```

**Comment by Pyttei** [comment]
Hey @migruiz4,
Thanks for your help. I disabled tls on both and now I can access both. The reason as to why I couldn't connect when they were on has probably something to do with my Rancher ingresses. I will need to look at my certificate settings in Rancher if I want to use tls at some point.

**Comment by migruiz4** [comment]
Hi @Pyttei,

I'm glad my answer helped you fix the issue!

In case it helps, if you are using `nginx-ingress-controller`, setting the backed protocol annotation may solve the issue when `restEncryption` is enabled: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#backend-protocol

**Comment by CCorrado** [comment]
The documentation 100% needs to be updated to reflect these changes ^ I had set up a fresh cluster using the latest charts (elasticsearch chart with kibana enabled and a fluentd chart) and nothing was working correctly due to the missing notes about `createSystemUser`. Took me a week to find this thread!

```
auth:
        enabled: true
        createSystemUser: true
        kibanaPassword: "secretpw"
        elasticsearchPasswordSecret: elastic-elasticsearch
```
