### ISSUE TITLE
[bitnami/redis] Missing metrics related templating if Sentinel is enabled

### ISSUE THREAD

**Issue by alex1989hu** [bitnami/charts#10082]
### Name and Version

bitnami/redis 16.9.0

### What steps will reproduce the bug?

1. Download bitnami/redis 16.9.0
2. Use custom Helm Chart values file (see below)
3. Run helm template redis ./redis/ -f redis-values.yaml > removeme.yaml
4. Check the removeme.yaml content

### Are you using any custom parameters or values?

```yaml
sentinel:
  enabled: true

metrics:
  enabled: true
  extraEnvVars:
  - name: REDIS_EXPORTER_TLS_SERVER_CERT_FILE
    value: /exporter-certificates/tls.crt
  - name: REDIS_EXPORTER_TLS_SERVER_KEY_FILE
    value: /exporter-certificates/tls.key
  extraVolumes:
  - name: exporter-certificates
    secret:
      secretName: redis-server
  extraVolumeMounts:
  - name: exporter-certificates
    mountPath: /exporter-certificates
    readOnly: true

tls:
  enabled: true
  authClients: true
  existingSecret: redis-server
  certFilename: tls.crt
  certKeyFilename: tls.key
  certCAFilename: ca.crt
```

### What is the expected behavior?

In case of `enabled` Sentinel the metrics side car can not be customized due to missing templating.

### What do you see instead?

None of the seeded value occur for the following keys: `metrics.extraEnvVars`, `metrics.extraVolumes` and `metrics.extraVolumeMounts`
