### ISSUE TITLE
harbor keeps losing oidc client secret

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#10091]
### Name and Version

harbor/12.3.6

### What steps will reproduce the bug?

kubernetes v1.23.6

Install latest harbor.

### Are you using any custom parameters or values?

Configured to use an ingress.  Installed via argocd.

### What is the expected behavior?

Successful harbor installation.

### What do you see instead?

It works for awhile, then after an hour or so I see that additional replicasets have appeared & that pods are restarting.  From the website OIDC configuration stops working.  I can go into the Configuration and copy the correct OIDC Client Secret and things start working again.

When I do this, I use the same client secret value, so the values hasn't changed.  Yet, for some reason, the harbor installation seems to lose this setting.

### Additional information

I've just erased the harbor namespace including the pvcs, and have reinstalled.  Will see if this error occurs again.

**Comment by rafariossaa** [comment]
Hi,
  Please, come back if you get this reproduced, also, indicate the parameters used to deploy it and relevant information you may find in the logs.

**Comment by lknite** [comment]
Eventually became degraded today:
```
$ k get all
NAME                                        READY   STATUS              RESTARTS   AGE
pod/harbor-chartmuseum-7c74fc647c-9k9r7     0/1     ContainerCreating   0          27m
pod/harbor-chartmuseum-868cc75d7d-d5f79     1/1     Running             0          24h
pod/harbor-core-6ff44c4f5b-vlbtp            1/1     Running             0          27m
pod/harbor-jobservice-54746fc465-5hf4m      1/1     Running             0          24h
pod/harbor-jobservice-65b9976b98-82h8h      0/1     Init:0/1            0          27m
pod/harbor-notary-server-555b5c58d5-4g9vq   1/1     Running             0          27m
pod/harbor-notary-signer-79f556d65d-gg8rk   1/1     Running             0          27m
pod/harbor-portal-6d7ff48b6b-lq29m          1/1     Running             0          24h
pod/harbor-postgresql-0                     1/1     Running             0          24h
pod/harbor-redis-master-0                   1/1     Running             0          24h
pod/harbor-registry-5f56d677df-7mcls        2/2     Running             0          24h
pod/harbor-registry-658bf88c8b-k97p4        0/2     Init:0/1            0          27m
pod/harbor-trivy-0                          1/1     Running             0          24h

NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/harbor-chartmuseum      ClusterIP   10.97.195.233    <none>        80/TCP              24h
service/harbor-core             ClusterIP   10.107.162.246   <none>        80/TCP              24h
service/harbor-jobservice       ClusterIP   10.97.205.80     <none>        80/TCP              24h
service/harbor-notary-server    ClusterIP   10.100.108.26    <none>        4443/TCP            24h
service/harbor-notary-signer    ClusterIP   10.108.131.156   <none>        7899/TCP            24h
service/harbor-portal           ClusterIP   10.96.165.229    <none>        80/TCP              24h
service/harbor-postgresql       ClusterIP   10.103.175.205   <none>        5432/TCP            24h
service/harbor-postgresql-hl    ClusterIP   None             <none>        5432/TCP            24h
service/harbor-redis-headless   ClusterIP   None             <none>        6379/TCP            24h
service/harbor-redis-master     ClusterIP   10.98.180.2      <none>        6379/TCP            24h
service/harbor-registry         ClusterIP   10.102.14.77     <none>        5000/TCP,8080/TCP   24h
service/harbor-trivy            ClusterIP   10.98.253.99     <none>        8080/TCP            24h

NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/harbor-chartmuseum     1/1     1            1           24h
deployment.apps/harbor-core            1/1     1            1           24h
deployment.apps/harbor-jobservice      1/1     1            1           24h
deployment.apps/harbor-notary-server   1/1     1            1           24h
deployment.apps/harbor-notary-signer   1/1     1            1           24h
deployment.apps/harbor-portal          1/1     1            1           24h
deployment.apps/harbor-registry        1/1     1            1           24h

NAME                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/harbor-chartmuseum-7c74fc647c     1         1         0       27m
replicaset.apps/harbor-chartmuseum-868cc75d7d     1         1         1       24h
replicaset.apps/harbor-core-57bfc6f85b            0         0         0       24h
replicaset.apps/harbor-core-6ff44c4f5b            1         1         1       27m
replicaset.apps/harbor-jobservice-54746fc465      1         1         1       24h
replicaset.apps/harbor-jobservice-65b9976b98      1         1         0       27m
replicaset.apps/harbor-notary-server-555b5c58d5   1         1         1       27m
replicaset.apps/harbor-notary-server-5dd459f5b4   0         0         0       24h
replicaset.apps/harbor-notary-signer-5f844d598c   0         0         0       24h
replicaset.apps/harbor-notary-signer-79f556d65d   1         1         1       27m
replicaset.apps/harbor-portal-6d7ff48b6b          1         1         1       24h
replicaset.apps/harbor-registry-5f56d677df        1         1         1       24h
replicaset.apps/harbor-registry-658bf88c8b        1         1         0       27m

NAME                                   READY   AGE
statefulset.apps/harbor-postgresql     1/1     24h
statefulset.apps/harbor-redis-master   1/1     24h
statefulset.apps/harbor-trivy          1/1     24h
```

Chart.yaml 

```
apiVersion: v2
name: harbor
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "1.0"

dependencies:
- name: harbor
  repository: https://charts.bitnami.com/bitnami
  version: 12.3.6
```

values.yaml 
```
harbor:

  volumePermissions:
    enabled: true

  externalURL: https://harbor.k.home.net

  exposureType: ingress

  ingress:
    core:
      ingressClassName: nginx
      hostname: harbor.k.home.net
      tls: true
      annotations:
        cert-manager.io/issuer: "cluster-adcs-issuer" #use specific name of issuer
        cert-manager.io/issuer-kind: "ClusterAdcsIssuer" #or AdcsClusterIssuer
        cert-manager.io/issuer-group: "adcs.certmanager.csf.nokia.com"
        nginx.ingress.kubernetes.io/ssl-redirect: 'true'
        nginx.ingress.kubernetes.io/proxy-body-size: '0'

    notary:
      ingressClassName: nginx
      hostname: notary.k.home.net
      tls: true
      annotations:
        cert-manager.io/issuer: "cluster-adcs-issuer" #use specific name of issuer
        cert-manager.io/issuer-kind: "ClusterAdcsIssuer" #or AdcsClusterIssuer
        cert-manager.io/issuer-group: "adcs.certmanager.csf.nokia.com"
        nginx.ingress.kubernetes.io/ssl-redirect: 'true'
        nginx.ingress.kubernetes.io/proxy-body-size: '0'

  persistence:
    enabled: true
    persistentVolumeClaim:
      registry:
        size: 1000Gi
```
