### ISSUE TITLE
Thanos Ruler does not pickup updated changes in service discovery configmap

### ISSUE THREAD

**Issue by gauresh10** [bitnami/charts#10092]
### Name and Version

bitnami/thanos-10.3.7

### What steps will reproduce the bug?

1. Create a Thanos target file based sd configmap.
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-target-sd-cm
data:
  servicediscovery.yml: |-
    - targets:
      - <prom_svc.cluster1>:<port>
      - <prom_svc.cluster2>:<port>
```

2. Deploy Thanos ruler with:
```yaml
query:
  existingSDConfigmap: thanos-target-sd-cm
```  

3. Thanos store on thanos-frontend-UI mentions two targets.
4. Edit the config map thanos-target-sd-cm in run-time to add new targets.
5. New target is not picked up by thanos-query after the default time of 5 mins mentioned here: https://thanos.io/v0.15/thanos/service-discovery.md/

### Are you using any custom parameters or values?
In values.yaml
```yaml
query:
  existingSDConfigmap: thanos-target-sd-cm
```
### What is the expected behavior?

Updated target list from servicediscovery.yml must be picked up by thanos-query:  https://thanos.io/v0.15/thanos/service-discovery.md/

### What do you see instead?

Manually add targets in the config map and do a rollout restart of Thanos-query module.

### Additional information

Is there any way thanos-query picks up changes in the configmap every 5 mins just like https://thanos.io/v0.15/thanos/service-discovery.md/?

Our application has a needs to add new targets using automation and with minimal rollouts as targets are added sequentially.
