### ISSUE TITLE
Zookeeper: Increase /data size

### ISSUE THREAD

**Issue by vando** [bitnami/charts#10090]
### Name and Version

bitnami/zookeeper v3.5.5

### What steps will reproduce the bug?

I want to have a specific size for the `/data` partition and Zookeeper ignores it.

Thanks in advance.

### Are you using any custom parameters or values?

```yaml
zookeeper:
  replicaCount: 1
  persistence:
  enabled: true
  size: 100Gi
```

### What do you see instead?

```console
$ df -h / /logs /data
Filesystem      Size  Used Avail Use% Mounted on
overlay         100G   15G   86G  15% /
/dev/nvme0n1p1  100G   15G   86G  15% /logs
/dev/nvme3n1    4.8G  2.1G  2.8G  43% /data
```
