### ISSUE TITLE
[bitnami/elasticsearch] Ingress: bad indentation for labels

### ISSUE THREAD

**Issue by huguesn** [bitnami/charts#10106]
### Name and Version

bitnami/elasticsearch 18.0.1

### What steps will reproduce the bug?

To reproduce the bug, you just need to enable the ingress:
```yaml
elasticsearch:
  ingress:
    enabled: true
```

### Are you using any custom parameters or values?

Yes, `elasticsearch.ingress.enabled=true`

### What is the expected behavior?

No error, templates can compile.

### What do you see instead?

The error when trying to parse the template:
```
Error: YAML parse error on .../charts/elasticsearch/templates/ingress.yaml: error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context
helm.go:84: [debug] error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context
```

With `helm template --debug`:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch
  namespace: "..."
  labels:
    app.kubernetes.io/name: elasticsearch
    helm.sh/chart: elasticsearch-18.0.1
    app.kubernetes.io/instance: ...
    app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/component: elasticsearch # <--------------------- Wrong indentation
```
