### ISSUE TITLE
[bitnami/elasticsearch] Ingress: http and host reversed in the rules section

### ISSUE THREAD

**Issue by huguesn** [bitnami/charts#10107]
### Name and Version

bitnami/elasticsearch 18.0.1

### What steps will reproduce the bug?

To reproduce the bug, you just need to enable the ingress:
```yaml
elasticsearch:
  ingress:
    enabled: true
```

### Are you using any custom parameters or values?

Yes, `elasticsearch.ingress.enabled=true`

### What is the expected behavior?

No error, templates can compile.

### What do you see instead?

With `helm template --debug`, you can see that something is wrong, the yaml is not valid.
```yaml
spec:
  rules:
    - http:                                # "host:" should be here
      host: elasticsearch.myhost.local     # "http:" should be here
        paths:
          - path: /
            ...
```
