### ISSUE TITLE
SonarQube - postgresql issue deployed via HelmChart

### ISSUE THREAD

**Issue by roman-chub** [bitnami/charts#10103]
### Name and Version

bitnami/sonarqube 1.0.13

### What steps will reproduce the bug?

Applying as Helm Release with described PV for PostgreSQL and autoscaling 

### Are you using any custom parameters or values?

Im using following values

```
    persistence:
      enabled: true
      storageClass: "efs-csi-fs-69762322"
      accessModes:
        - ReadWriteMany
      size: 10Gi

    volumePermissions:
      enabled: false

    sysctl:
      enabled: true

    rbac:
      create: true

    serviceAccount:
      create: true

    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPU: 70
      targetMemory: 70

    postgresql:
      enabled: true
      auth:
        password: "sonar"
        username: sonar
        database: bitnami_sonarqube
      service:
        ports:
          postgresql: 5432
      persistence:
        enabled: true
        accessMode: 
          - ReadWriteMany
        size: 16Gi
```

### What is the expected behavior?

I should see the correct PVC  and HPA

### What do you see instead?

It looks like postgresql persistence values ignored at all since I can see the wrong PVC created after HR apply:

```
% k get pvc
NAME                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
data-sonarqube-postgresql-0   Bound    pvc-94e2051e-5739-44f7-be46-d80883efa081   8Gi        RWO            ebs-gp3-delete        19m
sonarqube                     Bound    pvc-4a95d128-eda7-48a7-bb05-488855571b9b   10Gi       RWX            efs-csi-fs-69762322   19m
```

Sonarqube pvc the same as I described in HR (RWX, 10G) and correct, but postgresql is used default from PostgreSQL Helm Chart. Also, I have tried to describe persistence in global values but see the same

As for HPA - there is no created at all 
```
% k get hpa
No resources found in sonarqube namespace.


% k get all
NAME                             READY   STATUS    RESTARTS   AGE
pod/sonarqube-7b484b84c6-cbqhr   1/1     Running   0          18m
pod/sonarqube-postgresql-0       1/1     Running   0          18m

NAME                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
service/sonarqube                 ClusterIP   172.20.228.56   <none>        80/TCP,9001/TCP   18m
service/sonarqube-postgresql      ClusterIP   172.20.60.228   <none>        5432/TCP          18m
service/sonarqube-postgresql-hl   ClusterIP   None            <none>        5432/TCP          18m

NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/sonarqube   1/1     1            1           18m

NAME                                   DESIRED   CURRENT   READY   AGE
replicaset.apps/sonarqube-7b484b84c6   1         1         1       18m

NAME                                    READY   AGE
statefulset.apps/sonarqube-postgresql   1/1     18m

```
