### ISSUE TITLE
Static loadBalancerIP cannot be configured

### ISSUE THREAD

**Issue by moritzkoch** [bitnami/charts#1016]
**Which chart**:

bitnami/cassandra Version 2.1.2

**Description**

I am trying to configure a static IP through the values.yaml. My starting point is the values template from github:
https://github.com/bitnami/charts/blob/master/bitnami/cassandra/values.yaml
Inside theses values I changed the following values:

```
## Specify a service type
## ref: http://kubernetes.io/docs/user-guide/services/
##
service:
  type: LoadBalancer
  ## CQL Port
  port: 9042
  thriftPort: 9160
  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  nodePort: 30001
  loadBalancerIP: 99.99.99.99
```

If I then start helm to install the chart with theses values I get the following error:
```
$ helm install bitnami/cassandra -f values.yaml
Error: YAML parse error on cassandra/templates/service.yaml: error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context
```

**Steps to reproduce the issue:**

1. Download the values Template from https://github.com/bitnami/charts/blob/master/bitnami/cassandra/values.yaml
2. Change (service) type to LoadBalancer
3. Uncomment the (service) loadBalancerIP and change the value to (service) loadBalancerIP to 99.99.99.99 
3. Run "helm install bitnami/cassandra -f values.yaml" on your shell

**Describe the results you received:**

I get the following error message

> Error: YAML parse error on cassandra/templates/service.yaml: error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context

If I comment the (service) loadBalancerIP helm will install the chart and set the service IP dynamically.

**Describe the results you expected:**

I expected that a Kubernetes service would have been installed with the IP assigned (in this case 99.99.99.99)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-gke.5", GitCommit:"9aba9c1237d9d2347bef28652b93b1cba3aca6d8", GitTreeState:"clean", BuildDate:"2018-12-11T02:36:50Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
