### ISSUE TITLE
mariadb prometheusRule template failed

### ISSUE THREAD

**Issue by lusson-luo** [bitnami/charts#10164]
### Name and Version

bitnami/mariadb 11.0.2

### What steps will reproduce the bug?

1. `helm pull bitnami/mariadb`
2. `tar -xf mariadb-11.0.2.tgz`
3. update values(use code exegesis): 
```yaml
   metrics.prometheusRule.enabled: true
   metrics.enabled: true
   metrics.prometheusRule.rules:
      - alert: MariaDB-Down
      expr: absent(up{job="mariadb"} == 1)
      for: 5m
      labels:
        severity: warning
        service: mariadb
      annotations:
        message: 'MariaDB instance {{ $labels.instance }} is down'
        summary: MariaDB instance is down
```
<img width="225" alt="image" src="https://user-images.githubusercontent.com/19859400/168008469-a99925a8-5d9b-4a56-bfff-39b0f4b7f931.png">
<img width="233" alt="image" src="https://user-images.githubusercontent.com/19859400/168008447-62008118-3216-4d6e-bf91-f5b2093e87b5.png">
<img width="747" alt="image" src="https://user-images.githubusercontent.com/19859400/168008418-b237fe2d-8893-4098-bb7b-f3b2e3c8bdf9.png">

5. helm template and failed
```
helm template mariadb mariadb -n coding --output-dir  target
```
result
```
Error: template: mariadb/templates/prometheusrules.yaml:23:15: executing "mariadb/templates/prometheusrules.yaml" at <include "common.tplvalues.render" (dict "value" .Values.metrics.prometheusRule.rules "context" $)>: error calling include: template: mariadb/charts/common/templates/_tplvalues.tpl:11:12: executing "common.tplvalues.render" at <tpl (.value | toYaml) .context>: error calling tpl: error during tpl function execution for "- alert: MariaDB-Down\n  annotations:\n    message: MariaDB instance {{ $labels.instance }} is down\n    summary: MariaDB instance is down\n  expr: absent(up{job=\"mariadb\"} == 1)\n  for: 5m\n  labels:\n    service: mariadb\n    severity: warning": parse error at (mariadb/templates/prometheusrules.yaml:3): undefined variable "$labels"

Use --debug flag to render out invalid YAML
```
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/19859400/168008543-97be40c7-8a5f-47c4-a97c-96a5e1c824a4.png">

### Are you using any custom parameters or values?
```yaml
metrics:
  enabled: true
  prometheusRule:
    enabled: true
    rules: 
    - alert: MariaDB-Down
      expr: absent(up{job="mariadb"} == 1)
      for: 5m
      labels:
        severity: warning
        service: mariadb
      annotations:
        message: 'MariaDB instance {{ $labels.instance }} is down'
        summary: MariaDB instance is down
```
### What is the expected behavior?

`helm template mariadb mariadb -n coding --output-dir  target` is ok, and have a prometheus rule yaml file

### What do you see instead?
```
Error: template: mariadb/templates/prometheusrules.yaml:23:15: executing "mariadb/templates/prometheusrules.yaml" at <include "common.tplvalues.render" (dict "value" .Values.metrics.prometheusRule.rules "context" $)>: error calling include: template: mariadb/charts/common/templates/_tplvalues.tpl:11:12: executing "common.tplvalues.render" at <tpl (.value | toYaml) .context>: error calling tpl: error during tpl function execution for "- alert: MariaDB-Down\n  annotations:\n    message: MariaDB instance {{ $labels.instance }} is down\n    summary: MariaDB instance is down\n  expr: absent(up{job=\"mariadb\"} == 1)\n  for: 5m\n  labels:\n    service: mariadb\n    severity: warning": parse error at (mariadb/templates/prometheusrules.yaml:3): undefined variable "$labels"
```
