### ISSUE TITLE
[bitnami/keycloak] Error when using existingSecretPerPassword stanza for TLS secret templating 

### ISSUE THREAD

**Issue by gusmann** [bitnami/charts#10182]
### Name and Version

bitnami/keycloak <=8.0.0

### What steps will reproduce the bug?

Attempting to use the [existingSecretPerPassword](https://docs.bitnami.com/kubernetes/apps/keycloak/configuration/manage-passwords/#multiple-existing-secrets-with-all-the-passwords) stanza with Keycloak's TLS keystore and truststore passwords in an existing secret results in an error when rendering the Keycloak statefulset.

I've identified the issue and will open a PR addressing them. There's also a minor misspelling (`tls-truestore` vs `tls-truststore`) that's been propagated across several versions of the chart, will be adjusting that as well.

### Are you using any custom parameters or values?

  ```yaml
auth: 
    tls: 
      enabled: true
    existingSecretPerPassword: 
      keyMapping:
        adminPassword: KEYCLOAK_ADMIN_PASSWORD
        managementPassword: KEYCLOAK_MANAGEMENT_PASSWORD
        databasePassword: postgresql-password
        tlsKeystorePassword: KEYCLOAK_TLS_KEYSTORE_PASSWORD
        tlsTruststorePassword: KEYCLOAK_TLS_TRUSTSTORE_PASSWORD
      adminPassword:
        name: keycloak-administration
      managementPassword:
        name: keycloak-administration
      databasePassword:
        name: keycloak-administration
      tlsKeystorePassword:
        name: keycloak-administration
      tlsTruststorePassword:
        name: keycloak-administration
```

### What do you see instead?

```
Thu, May 12 2022 1:28:14 pm | helm upgrade --history-max=5 --install=true --namespace=keycloak --timeout=10m0s --values=/home/shell/helm/values-keycloak-8.0.0.yaml --version=8.0.0 --wait=true keycloak /home/shell/helm/keycloak-8.0.0.tgz

Thu, May 12 2022 1:28:17 pm | Error: UPGRADE FAILED: template: keycloak/templates/statefulset.yaml:238:27: executing "keycloak/templates/statefulset.yaml" at <tpl>: wrong number of args for tpl: want 2 got 1
```

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/10593140/168167385-90a17bd6-e465-40c3-8261-dd130fd3fccd.png">
