### ISSUE TITLE
[bitnami/mongodb]: auth.database etc is not being respected by the container

### ISSUE THREAD

**Issue by Maelstromeous** [bitnami/charts#10223]
### Name and Version

bitnami/mongodb:12.1.4

### What steps will reproduce the bug?

1. Create a helm chart values with the following properties:

```
auth:
  username: foo
  password: "foobar123"
  database: foodb
```

Also happens with the following values as suggested by https://artifacthub.io/packages/helm/bitnami/mongodb?modal=values&path=auth

```
auth:
  usernames:
    - foo
  passwords:
    - "foobar123"
  databases:
    - foodb
```

3. Apply the chart to the cluster.
4. `kubectl describe pod/<db-pod>`

Describing the pod shows the following:

```
Environment:
      MONGODB_EXTRA_USERNAMES:          foo
      MONGODB_EXTRA_DATABASES:           foodb
      MONGODB_EXTRA_PASSWORDS:          <set to the key 'mongodb-passwords' in secret 'foo-db-mongodb'>  Optional: false
```

However, [according to your documentation](https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#creating-a-user-and-database-on-first-run) `MONGODB_EXTRA_*` is not used anywhere, and I can confirm that no database is created.

### Are you using any custom parameters or values?

```
image:
  tag: 5.0.8

auth:
  rootPassword: foo123
  username: foo
  password: "foobar123"
  database: foodb

persistence:
  size: 20Gi
```

### What is the expected behavior?

A database should be created as supplied by the auth.database etc values. A user and password comination should also have been created.

### What do you see instead?

Database is not created, however `MONGODB_EXTRA_*` values are injected into the environment, but they do nothing. No database is created.

Additonally, the expected user is not created either.

### Additional information

I have also tried injecting the documentation specified values but they too **do not work**.
```
extraEnvVars:
  - name: MONGODB_USERNAME
    value: foo
  - name: MONGODB_PASSWORD
    value: foobar123
  - name: MONGODB_DATABASE
    value: foodb
```

This injects the values the container expects, however no database is actually created.

**Comment by pierreyves-lebrun** [comment]
Thanks god I am not the only one experiencing that issue

**Comment by FraPazGal** [comment]
Hello @Maelstromeous, @pierreyves-lebrun,

I wasn't able to reproduce the issue. I deployed our `bitnami/mongodb v.12.1.5` chart with only the following custom values:

```
  ## @param auth.usernames List of custom users to be created during the initialization
  ## @param auth.passwords List of passwords for the custom users set at `auth.usernames`
  ## @param auth.databases List of custom databases to be created during the initialization
  ##
  usernames:
    - test1
  passwords:
    - passwordtest1
  databases:
    - db_1_test
```

Using an auxiliary MongoDB pod as the mongodb-client, I was able to connect to the defined database using the new user:
```
$ kubectl run --namespace default mongodb-client --rm --tty -i --restart='Never' --env="MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD" --image docker.io/bitnami/mongodb:5.0.8-debian-10-r10 --command -- bash

I have no name!@mongodb-client:/$ mongosh db_1_test --host mongodb -u test1 -p passwordtest1
Current Mongosh Log ID:	62827130736a016091732a83
Connecting to:		mongodb://mongodb:27017/db_1_test?directConnection=true&appName=mongosh+1.3.1
Using MongoDB:		5.0.8
Using Mongosh:		1.3.1

For mongosh info see: https://docs.mongodb.com/mongodb-shell/

db_1_test>
```

Accessing as root, I also checked the new user:
```
I have no name!@mongodb-client:/$ mongosh admin --host "mongodb" --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD

admin> db.system.users.find()
[
  {
    _id: 'admin.root',
    ...
  },
  {
    _id: 'db_1_test.test1',
    userId: UUID("58e5724c-2e5a-4eac-95a8-2a7a0ccc964b"),
    user: 'test1',
    db: 'db_1_test',
    credentials: {
      'SCRAM-SHA-1': {
        iterationCount: 10000,
        salt: '8w0rvjBRnJ+dxokMnO+zvA==',
        storedKey: 'ddQrby/2glGk6vQqSOu2hw/lxKw=',
        serverKey: 'ywRjpeZHiwXbvTsnLmpejegWzoU='
      },
      'SCRAM-SHA-256': {
        iterationCount: 15000,
        salt: 'bmbHI0BJXKHsOASisn5l86nGlPznQsF3MlNSmg==',
        storedKey: 'wmjxEUUap4iQdSYfxxuD0xlMijrJKov2ZOgTiLP3C7U=',
        serverKey: '7ssCwlzbReExkgaUP2beeaSQ0Mfqo9xQa8BoHkZWs3I='
      }
    },
    roles: [ { role: 'readWrite', db: 'db_1_test' } ]
  }
]
```

Could you check if you are still having issues with the latest version? If so, please share the output of the MongoDB commands I used.
