### ISSUE TITLE
CrashLoopBackOff airflow-bitnami-scheduler, airflow-bitnami-web

### ISSUE THREAD

**Issue by pollynesterovich** [bitnami/charts#10224]
### Name and Version

bitnami/airflow 12.2.1

### What steps will reproduce the bug?

Pods airflow-bitnami-scheduler, airflow-bitnami-web start exiting with status CrashLoopBackOff a couple of hours after launch. I see that the clone-repositories container does not start, and I can’t see the logs in any way. 
I am using the following  2.35.1 version of git because it failed not cloning the repo with the  2.36.0-debian-10-r3 version.  (https://github.com/bitnami/charts/issues/9879) . 
Please help me to find out the reason why the clone-repositories container is not stratified and if it is possible for git to set up cloning of the repository without changing the version to a more stray one.
```yaml
web:
  extraVolumes:
  - name: git-sync-ssh-key
      secret:
        secretName: git-ssh-key-secret
        defaultMode: 256
scheduler:
 extraVolumes:
   - name: git-sync-ssh-key
      secret:
        secretName: git-ssh-key-secret
        defaultMode: 256
worker:
  extraVolumes:
    - name: git-sync-ssh-key
      secret:
        secretName: git-ssh-key-secret
        defaultMode: 256
git:
  image:
    registry: docker.io
    repository: bitnami/git
    tag: 2.35.1
  clone:
    extraVolumeMounts:
      - name: git-sync-ssh-key
        mountPath: /.ssh
  sync:
    interval: 60
    extraVolumeMounts:
      - name: git-sync-ssh-key
        mountPath: /.ssh
```

### Are you using any custom parameters or values?

No

### What is the expected behavior?

No CrashLoopBackOff 

### What do you see instead?

CrashLoopBackOff

**Comment by carrodher** [comment]
I am not able to reproduce the described issue, please see below my attempt:

- I used the same values.yaml shared in this post
```yaml
web:
  extraVolumes:
  - name: git-sync-ssh-key
    secret:
      secretName: git-ssh-key-secret
      defaultMode: 256
scheduler:
  extraVolumes:
  - name: git-sync-ssh-key
    secret:
      secretName: git-ssh-key-secret
      defaultMode: 256
worker:
  extraVolumes:
  - name: git-sync-ssh-key
    secret:
      secretName: git-ssh-key-secret
      defaultMode: 256
git:
  image:
    registry: docker.io
    repository: bitnami/git
    tag: 2.35.1
  clone:
    extraVolumeMounts:
    - name: git-sync-ssh-key
      mountPath: /.ssh
  sync:
    interval: 60
    extraVolumeMounts:
    - name: git-sync-ssh-key
      mountPath: /.ssh
```
- Helm chart deployed by running
```console
$ helm install air bitnami/airflow -f values.yaml
```
- Everything is up and running as expected after some hours:
```console
$ kubectl get pods
NAME                                     READY   STATUS    RESTARTS   AGE
air-airflow-scheduler-69b57c49b9-mbc2v   1/1     Running   1          3h48m
air-airflow-web-6f8fc57ffb-pj5r4         1/1     Running   1          3h48m
air-airflow-worker-0                     1/1     Running   0          3h48m
air-postgresql-0                         1/1     Running   0          3h48m
air-redis-master-0                       1/1     Running   0          3h48m
```
