### ISSUE TITLE
bitnami/keycloak 8.0.* / 9.0.* Running Server in Development mode

### ISSUE THREAD

**Issue by jack1902** [bitnami/charts#10236]
### Name and Version

bitnami/keycloak 8.0.1

### What steps will reproduce the bug?

1. Deploy chart with version `7.1.18`
2. Upgrade chart to version `8.0.1`

### Are you using any custom parameters or values?

overrides in a seperate yaml

```yaml
pdb:
  create: true

autoscaling:
  enabled: true
  minReplicas: 2

cache:
  ownersCount: 2
  authOwnersCount: 2

# TLS is terminated by NGINX, NGINX -> keycloak HTTP (wrapped in TLS by service-mesh)
# ref: https://www.keycloak.org/server/reverseproxy
proxy: edge

# no longer a thing (was in older versions)
proxyAddressForwarding: true
replicaCount: 2

# ServiceDiscovery, serviceAccount and rbac required when more than 1 replica exists
serviceDiscovery:
  enabled: true
serviceAccount:
  # required as KUBE_PING is used as the discovery mechanism
  automountServiceAccountToken: true
rbac:
  create: true
  rules:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
        - list

service:
  type: ClusterIP

extraEnvVars:
  # Without needing to force backend request through the frontend
  # Need to look into /auth being removed in keycloak 17
  - name: KEYCLOAK_EXTRA_ARGS
    value: "-Dkeycloak.frontendUrl=https://YOUR_DOMAIN/auth"
```

### What is the expected behavior?

to not see a warning of "DO NOT use in production", this is pretty concerning.

### What do you see instead?

2022-05-16 10:42:47,041 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.

### Additional information

I'm having to read keycloak docs and marry them up with the chart, no docs around upgrades from the current chart version I am on, and the one I desire to be on exist so it is a bit of guess work, but I don't believe my override values cause this issue

**Comment by harishdesetti1206** [comment]
This issue is resolved when upgraded from 7.0.1 to 8.0.2 in my case.

**Comment by jack1902** [comment]
https://github.com/bitnami/bitnami-docker-keycloak/blob/5c67cb51dee7288cc377354cb8b3fcad0ca88df3/17/debian-10/rootfs/opt/bitnami/scripts/libkeycloak.sh#L45

This is too opinionated, as it is possible to run `kc.sh start` without providing `tls` pieces but due to the script linked which wraps `kc.sh` it is impossible to run `kc.sh start` without providing TLS pieces but if a service-mesh is at play with the `proxy` set to `edge` I don't see the need for TLS on keycloak itself.

I'm going to create my own container with this piece commented out and see how far I get, hopefully documentation on upgrading to `8.*` is on the way (if help is needed please say)

**Comment by harishdesetti1206** [comment]
@jack1902 Sorry, it's my bad. Yes, I see the same error **WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.**

Moreover, i see the error of the postgresql password. You face the same error by any chance?
`WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "bn_keycloak"
`

**Comment by harishdesetti1206** [comment]
@jack1902 **FATAL: password authentication failed for user "bn_keycloak"** error is resolved when i uninstalled and installed the keycloak again.

But the former error `2022-05-16 19:03:21,650 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.` pertains.
I tried with 8.0.2 and 8.0.2 aswell. Like you mentioned, the error should be from the kc.sh script.

**Comment by harishdesetti1206** [comment]
@jack1902 I tried adding  **KEYCLOAK_PRODUCTION** as an environmental variable. But I find no luck. The same error remains.
`extraEnvVars:
  - name: KEYCLOAK_PRODUCTION
     value: "true"`

**Comment by jack1902** [comment]
@Mauraza / @carrodher - apologies on @'ing you folks directly, wondering if you have anything to add on this issue? I feel like I'm in a small minority getting keycloak 17 up and running

**Comment by harishdesetti1206** [comment]
@jack1902 see this description in the readme.md about the docker image  keycloak#17-debian-10 https://github.com/bitnami/bitnami-docker-keycloak#17-debian-10

Looks like the tls configuration and the KEYCLOAK_PRODUCTION flag.

**Comment by jack1902** [comment]
the TLS requirement feels like something imposed by bitnami rather than `keycloak` itself. I've been able to get keycloak running in production mode without passing the `tls` flags to point to any known PEM files or Java keystores.

One of the main reasons I use a service-mesh is to avoid having to manage certificates in multiple places, but this upgrade to `17` using the `KEYCLOAK_PRODUCTION` env-var embossed by the scripts forces me to create `tls` certificates for keycloak specifically. I have edge certificates to encrypt traffic from outside to my LB which then strips the cert and onboard traffic into the mesh which wraps things with TLS. Adding additional certs to keycloak to ensure traffic is wrapped before being wrapped again doesn't add much in terms of security, only complexity as all original traffic is encrypted with my edge certificate in the first instance regardless.

I'll keep digging into the upstream keycloak documentation to see if I can find the hard requirement to use tls but so far it feels like it has been imposed by bitnami themselves rather than keycloak as the underlying app

**Comment by jack1902** [comment]
```yaml
ingress:
  hostname: "user-authentication.{{ api_top_level_domain }}"
  enabled: true
  annotations:
    # keycloak auth tokens can be rather large
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    # Ensure we use capture group two always 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  extraPaths:
     # remap /auth/something/something to /something/something
    - path: "/auth(/|$)(.*)"
      pathType: ImplementationSpecific
      backend:
        service:
          name: user-authentication
          port:
            name: HTTP
  # capture anything else into capture group two to ensure the rewrite-target annotation works without needing to create a completely separate ingress object
  path: "/()(.*)"
```

Also, something I found useful for things that required using `/auth` from the outside in without me needing to pass the updated flag to use `/auth` on the build. This means I buy myself time to move things to the new behaviour whilst maintaining a level of backwards compatibility for older URLs

**Comment by tirelibirefe** [comment]
> Actually spawns from https://github.com/bitnami/bitnami-docker-keycloak/blob/399c06a076b1ebea71fc3be3f8cabfdd88ad6fb0/17/debian-10/rootfs/opt/bitnami/scripts/keycloak/run.sh#L22

what if ssl is terminated at LB level?

**Comment by tirelibirefe** [comment]
https://github.com/bitnami/charts/issues/10295
Hello @jack1902 
I tried following parameters with/without JAVA_OPTS, nothing changed:
```
- name: KC_HOSTNAME
  value: "https://keycloakmydomain.com/auth"
- name: KC_HOSTNAME_STRICT
  value: "true"
# - name: JAVA_OPTS
#   value: "-Djgroups.dns.query=keycloak-headless.keycloak"
```

**Comment by tirelibirefe** [comment]
sorry @jack1902 I see, that's ok. I supposed you would prefer here.

**Comment by harishdesetti1206** [comment]
> So i don't see the issue you have present for yourself around the database, but I have made a tonne of progress on getting away from `development` mode.
> 
> There are numerous issues at play, which cause a bunch of confusion. In `start-dev` mode, caching doesn't work as expected which means there is no distributed cache, so if you have two replicas, things won't act as you might of hoped due to load balanced requests hitting different caches result in all sorts of funkiness.
> 
> I've moved passed this by using the following (with two replicas):
> 
> ```yaml
> command:
>   - bash
> 
> args:
>   - -c
>   - "/opt/bitnami/scripts/keycloak/setup.sh && /opt/bitnami/keycloak/bin/kc.sh build --cache=ispn --cache-stack=kubernetes && /opt/bitnami/keycloak/bin/kc.sh -cf /opt/bitnami/keycloak/conf/keycloak.conf start"
> 
> extraEnvVars:
>   # https://www.keycloak.org/server/hostname
>   - name: KC_HOSTNAME
>     value: "<YOUR_EXTERNAL_HOSTNAME_FOR_KEYCLOAK>"
>   - name: KC_HOSTNAME_STRICT
>     value: "true"
>   # https://www.keycloak.org/server/caching
>   # Required if the --cache-stack=kubernetes
>   - name: JAVA_OPTS
>     value: "-Djgroups.dns.query=keycloak-headless.keycloak"
> ```
> 
> It would be good to get some input from Bitnami maintainers who look after keycloak, since I feel the current implementation which forces me to use `tls` causes more issues that it is worth (I can't actually get it working with tls, I tried but this configuration above works for me but uses internal scripts which feel slightly hacky as they could change on me)



> @jack1902 The following configuration resolved the problem "Running server in production mode"

```yaml
auth:
  adminUser: user
  adminPassword: admin
  managementUser: manager
  managementPassword: admin
  tls:
    enabled: true
    autoGenerated: true
    usePem: true
    keystorePassword: <keystoreRandomPassword123>
    truststorePassword: <truststoreRandomPassword123>
extraEnvVars:
  - name: KEYCLOAK_PRODUCTION
    value: "true"
````

Let me know how did it go in your environment.
Moreover, another issue "Enabling cache ispn issue" still pertains (but that is not related to this issue.)

**Comment by jack1902** [comment]
## certificates
in the instance certs are "auto-generated" what is their lifespan? I know I could pass them in but being auto-generated means at some point in the future those certs expire and the environment falls over. I feel like I'm not alone in how people run things with edge certs and then encrypt via their service-mesh on their cluster removing to need for certs on the apps themselves. 

My main bug bear is that you can run `kc.sh start` without passing any TLS flags, and it doesn't blow up asking for TLS to be configured meaning it is optional, but due to the implementation Bitnami have used in the docker images, you are required to pass TLS certs meaning that bitnami have embossed a requirement on the end user that keycloak itself didn't.

## caching
To fix the `ispn` cache piece, the underlying scripts within the container would need to ensure `--cache-stack=kubernetes` is passed when calling `kc.sh build --cache-stack=kubernetes` which can be achieved in this bit here: https://github.com/bitnami/bitnami-docker-keycloak/blob/5ae70b0e96cabceed17b95a48bf3e84c70a3175e/17/debian-10/rootfs/opt/bitnami/scripts/libkeycloak.sh#L121 (when using build you want to ensure all pieces are passed one time, so perhaps breaking the call to build into another function makes sense to enable caching within kubernetes to work)

which then just needs (within the chart by default) to pass the JAVA_OPTS `-Djgroups.dns.query` piece (this has enabled my distributed caching to work like it did before)

**Comment by harishdesetti1206** [comment]
@jack1902 DO you by chance have an idea on how to verify if the certs I created are being used for secured HTTPS communication?
I'm sure the certs are created and picked by keycloak but I don't know how I can actually validate.

**Comment by jack1902** [comment]
Depending on where in your request flow the certificates you are referring to exist, you will need to insert yourself there and check.

If you are referring to the ones on `keycloak` itself, you could create a `pod` and exec into it, then make a request to the service within the cluster to see the public-cert

**Comment by jack1902** [comment]
you can test if it is working as expected by having 2 replicas, login and then terminate one replica and refresh your browser window. If you are forced to login again, then your caching isn't working

**Comment by jack1902** [comment]
For anyone watching this issue, i have managed to get things working, by enhancing the bitnami scripts (which I have PRs open for).

In the meantime, you can clone https://github.com/jack1902/bitnami-docker-keycloak and checkout `all_the_things` which has all my PRs merged in. I've tested this in my own environments and it works using the below values (update tag to something you have created from your own build of that branch)

<details>
  <summary>custom values</summary>
  
  Assumes you are using `edge` as the proxy mode, and kubernetes as the cache stack. You can change this if you want to check the PRs would work for you
  
  ```yaml
  # Assumes https://github.com/jack1902/bitnami-docker-keycloak/blob/all_the_things/17/debian-10/Dockerfile is built and pushed somewhere
  # Upstream PRs exist to get the default image into this state but this allows others to trail it
  tag: "<YOUR_BUILT_IMAGE>"

  pullSecrets:
    - "{{ image_registry_pull_secret_name }}"

  auth:
    adminUser: adminUser
    adminPassword: "adminPassword"
    managementPassword: "managementPassword"

  ingress:
    hostname: "keycloak.<YOURDOMAIN>"
    enabled: true
    annotations:
      nginx.org/hsts-behind-proxy: "True"
      nginx.org/hsts: "True"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "True"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      # Below lines (including path: ) are only required if you want to keep `/auth/something`
      # but it is advisable to remove it once you no longer use `/auth/something` anywhere as future
      # requests to keycloak might change the pathing, which would break this temporary workaround
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    extraPaths:
      - path: "/auth(/|$)(.*)"
        pathType: ImplementationSpecific
        backend:
          service:
            name: keycloak
            port:
              name: http
    path: "/()(.*)"

  pdb:
    create: true

  autoscaling:
    enabled: true
    minReplicas: 2

  # TLS is terminated by edge (NGINX), edge -> keycloak HTTP (wrapped in TLS by service-mesh)
  # ref: https://www.keycloak.org/server/reverseproxy
  proxy: edge

  # ServiceDiscovery, serviceAccount and rbac required when more than 1 replica exists
  serviceDiscovery:
    enabled: true
  serviceAccount:
    # required as kubernetes is used as the cache-stack (KC_CACHE_STACK)
    automountServiceAccountToken: true
  rbac:
    create: true
    rules:
      - apiGroups:
          - ""
        resources:
          - pods
        verbs:
          - get
          - list

  service:
    type: ClusterIP

  postgresql:
    enabled: true

  extraEnvVars:
    # https://www.keycloak.org/server/hostname
    - name: KC_HOSTNAME
      value: "keycloak.<YOUR_DOMAIN>"
    - name: KC_HOSTNAME_STRICT
      value: "true"

    # Required by container scripts to use `start` instead of `start-dev`
    - name: KEYCLOAK_PRODUCTION
      value: "true"

    # https://www.keycloak.org/server/caching - required with --cache-stack=kubernetes
    - name: KC_CACHE_STACK
      value: "kubernetes"
    # keycloak resides in the same namespace, so keycloak-headless suffices
    - name: JAVA_OPTS
      value: "-Djgroups.dns.query=keycloak-headless"

  ```
  
</details>

**Comment by SeWieland** [comment]
Use

```yaml
auth:
  tls:
    enabled: true
    autoGenerated: true
    keystorePassword: xxx
    truststorePassword: xxx
proxy: reencrypt
extraEnvVars:
  - name: KEYCLOAK_PRODUCTION
    value: 'true'
```

This worked for me.

@jack1902 I think the caching cahnged as well.
I simply use 

```yaml
cache:
  enabled: true
``` 

now. The ownersCount and authOwnersCount won't do anything anymore (I guess).

**Comment by javsalgar** [comment]
Hi,

@jack1902 did the PR you created fix the issue commented by @SeWieland  and @kstiehl ?

**Comment by SeWieland** [comment]
🎉 I can confirm that using the image.tag [17.0.1-debian-11-r0](https://github.com/bitnami/bitnami-docker-keycloak/releases/tag/17.0.1-debian-11-r0) together with the chart version 9.x works for me and caching is finally fixed and working!

Im using proxy mode edge + KC_HOSTNAME and KEYCLOAK_PRODUCTION vars set. => Prod mode + caching + old logout mode is working (we still need that), KC v18 with the new logout behavior should work just fine as well.

I think the relevant PR was https://github.com/bitnami/bitnami-docker-keycloak/pull/73 :)

**Comment by jack1902** [comment]
to add, the KC_HOSTNAME piece came from https://github.com/bitnami/bitnami-docker-keycloak/pull/71 

looks like this is solved for others, I will test once I have a spare moment and close this if it works ~"out of the box" (meaning I can pass some settings via the chart and an env-var and walk away without needing to override the `command` and `arg` piece

**Comment by kstiehl** [comment]
Sorry was a little bit busy. But with the latest docker image of 18.0.0 It finally works everything as expected. @jack1902 thank you very much

**Comment by mzurek-teldoc** [comment]
>   tls:
>     enabled: true
>     autoGenerated: true
>     usePem: true
>     keystorePassword: <keystoreRandomPassword123>
>     truststorePassword: <truststoreRandomPassword123>

For me this is causing: `Error: UPGRADE FAILED: YAML parse error on keycloak/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 106: found character that cannot start any token`

**Comment by vijaykumarv7** [comment]
Hello,

Can someone help how did keycloak HA issue resolved  in your environment. What is resolution.  I have installed via bitnami keycloak helm char and Keycloak running on the AKS cluster . I have been stucked for more than a week . Please help me on this.

**Comment by patrickbeam** [comment]
@vijaykumarv7 Happy to help. I think opening another issue might be best.  This will give everyone the relevant information and context they need to help you.

**Comment by harishdesetti1206** [comment]
> Hello,
> 
> Can someone help how did keycloak HA issue resolved in your environment. What is resolution. I have installed via bitnami keycloak helm char and Keycloak running on the AKS cluster . I have been stucked for more than a week . Please help me on this.

Hi Vijay. What's the issue you are facing in AKS?

**Comment by sbile** [comment]
Hey,

I am running Keycloak 20.0.3 with custom kubernetes manifests (not using bitnami operator scripts). I managed to make it work by setting the following environment variables on my deployment yaml. Please note that I am doing the SSL termination in my ingress.

```yaml
...
        env:
          - name: PORT
            value: "8080"
          - name: KEYCLOAK_PRODUCTION
            value: "true"
          - name: KEYCLOAK_PROXY
            value: "edge"
...
```

You can check the actual script enforcing this validation on a running container here `/opt/bitnami/scripts/libkeycloak.sh` at line 43.

```bash
    if is_boolean_yes "$KEYCLOAK_PRODUCTION"; then
        if [[ "$KEYCLOAK_PROXY" == "edge" ]]; then
            # https://www.keycloak.org/server/reverseproxy
            if is_boolean_yes "$KEYCLOAK_ENABLE_HTTPS"; then
                print_validation_error "TLS and proxy=edge are not compatible. Please set the KEYCLOAK_ENABLE_HTTPS variable to false when using KEYCLOAK_PROXY=edge. Review # https://www.keycloak.org/server/reverseproxy for more information about proxy settings."
            fi
        elif ! is_boolean_yes "$KEYCLOAK_ENABLE_HTTPS"; then
            # keycloak proxy passthrough/reencrypt requires tls
            print_validation_error "You need to have TLS enabled. Please set the KEYCLOAK_ENABLE_HTTPS variable to true"
        fi
    fi
```
