### ISSUE TITLE
Kibana subchart is not coming up with default ES host configuration 

### ISSUE THREAD

**Issue by rjindalrohit** [bitnami/charts#10261]
### Name and Version

bitnami/elasticsearch 18.1.0 and 18.0.4

### What steps will reproduce the bug?

1. Using Docker desktop kubernetes setup
2. Config Used
Values.yaml

```
global:
  kibanaEnabled: true

master:
  replicaCount: 1
data: 
  replicaCount: 1
coordinating: 
  replicaCount: 1
ingest: 
  replicaCount: 1
security:
  enabled: true
  # PASSWORD must be the same value passed to elasticsearch to get an "out of the box" experience
  elasticPassword: "rvHsigEI6iVmKfRE"
  tls:
    # AutoGenerate TLS certs for elastic
    autoGenerated: true
    verificationMode: full
    restEncryption: true
kibana:
  extraConfiguration:
    xpack.encryptedSavedObjects.encryptionKey: fd0d21352ecf9d6ce77b758033bafafb
  tls:
    enabled: true
    autoGenerated: true
  elasticsearch:
    #hosts:
    # - "my-elasticsearch-coordinating-hl.elk.svc.cluster.local"
    port: "9200" 
    security:
      auth:
        enabled: true
        kibanaPassword: rvHsigEI6iVmKfRE
        createSystemUser: true
        elasticsearchPasswordSecret: elastic-secret
      tls:
        # Instruct kibana to connect to elastic over https
        enabled: true
        # Bit of a catch 22, as you will need to know the name upfront of your release
        existingSecret: my-elasticsearch-master-crt
        # As the certs are auto-generated, they are pemCerts so set to true
        usePemCerts: true
```
3. Run 
`helm upgrade --install  my-elasticsearch bitnami/elasticsearch --version 18.1.0 --render-subchart-notes -f values.yaml`
4. Error 

> [2022-05-17T08:09:16.577+00:00][ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. Hostname/IP does not match certificate's altnames: Host: my-elasticsearch. is not in the cert's altnames: DNS:*.my-elasticsearch-coordinating-hl.elk.svc.cluster.local, DNS:my-elasticsearch-coordinating-hl.elk.svc.cluster.local, DNS:my-elasticsearch-coordinating, DNS:127.0.0.1, DNS:localhost

### Are you using any custom parameters or values?

Values.yaml
```
global:
  kibanaEnabled: true

master:
  replicaCount: 1
data: 
  replicaCount: 1
coordinating: 
  replicaCount: 1
ingest: 
  replicaCount: 1
security:
  enabled: true
  # PASSWORD must be the same value passed to elasticsearch to get an "out of the box" experience
  elasticPassword: "rvHsigEI6iVmKfRE"
  tls:
    # AutoGenerate TLS certs for elastic
    autoGenerated: true
    verificationMode: full
    restEncryption: true
kibana:
  extraConfiguration:
    xpack.encryptedSavedObjects.encryptionKey: fd0d21352ecf9d6ce77b758033bafafb
#xpack.reporting.encryptionKey: b4aa831be1c4d41eb4b5053ca4cb290d
#xpack.security.encryptionKey: 7a219d2470e57dab8dc91fb0706b812d
  tls:
    enabled: true
    autoGenerated: true
  elasticsearch:
    #hosts:
    # - "my-elasticsearch-coordinating-hl.elk.svc.cluster.local"
    port: "9200" 
    security:
      auth:
        enabled: true
        kibanaPassword: rvHsigEI6iVmKfRE
        createSystemUser: true
        elasticsearchPasswordSecret: elastic-secret
      tls:
        # Instruct kibana to connect to elastic over https
        enabled: true
        # Bit of a catch 22, as you will need to know the name upfront of your release
        existingSecret: my-elasticsearch-master-crt
        # As the certs are auto-generated, they are pemCerts so set to true
        usePemCerts: true
```

### What is the expected behavior?

one should be the expected behaviour out of 2 mentioned below-

1. default **kibana.elasticsearch.hosts** value  **my-elasticsearch** (in my case my release name) should be part of the certificate.
2. default **kibana.elasticsearch.hosts** value  **my-elasticsearch** (in my case my release name) should be change to **my-elasticsearch-coordinating-hl** (in my case name generated from my release name for cordinating svc ) and this also need to be add in certificate as current value added is "my-elasticsearch-coordinating" .

### What do you see instead?

[2022-05-17T08:09:16.577+00:00][ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. Hostname/IP does not match certificate's altnames: Host: my-elasticsearch. is not in the cert's altnames: DNS:*.my-elasticsearch-coordinating-hl.elk.svc.cluster.local, DNS:my-elasticsearch-coordinating-hl.elk.svc.cluster.local, DNS:my-elasticsearch-coordinating, DNS:127.0.0.1, DNS:localhost
