### ISSUE TITLE
No way to dynamically provision non-standard storage class

### ISSUE THREAD

**Issue by derekyle** [bitnami/charts#1026]
**Which chart**:

values.yaml and values-production.yaml most recent version of mariadb chart

**Description**

values.yaml and values-production.yaml seem to imply that you can enter a different storage class in master.persistence.storageClass in order to dynamically provision a non 'default' provisioner. But this doesn't seem to work. If for example, you want to use the pd-ssd storage class with GKE instead of the standard disk.

**Steps to reproduce the issue:**

On a GKE cluster, run helm install with master.persistence.storageClass = 'pd-ssd'

You will get an unbound storage class error unless you add something like this to the charts:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: "{{ .Values.master.persistence.storageClass }}"
provisioner: kubernetes.io/gce-pd
parameters:
  type: "{{ .Values.master.persistence.storageClass }}"
  replication-type: none
reclaimPolicy: Retain
```
