### ISSUE TITLE
[MongoDB] No load balancer despite externalAccess being enabled

### ISSUE THREAD

**Issue by kaykhancheckpoint** [bitnami/charts#10278]
### Name and Version

binami/mongodb latest

### What steps will reproduce the bug?

helm install -f values.yml mongodb-prod bitnami/mongodb -n mongodb --create-namespace

### Are you using any custom parameters or values?

```
global:
  namespaceOverride: mongodb
architecture: replicaset
auth:
  rootPassword: "<redacted>"
  replicaSetKey: "<redacted>"
replicaCount: 1
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: geeiq/node-type
          operator: In
          values:
          - ops
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/component: mongodb
      topologyKey: kubernetes.io/hostname
persistence:
  storageClass: "mongodb"
  size: 250Gi
externalAccess:
  enable: true
```  

- You might have to remove the affinity block.

### What is the expected behavior?

When i set `externalAccess: true` I expect a load balancer to be created in my aws resources.

### What do you see instead?

No load balancer is being created

### Additional information

I have a AWS EKS cluster v1.22
