### ISSUE TITLE
Upgrade chart from `springcloud/spring-cloud-skipper-server` to `bitnami/spring-cloud-skipper` loses the status of the DEPLOYED streams

### ISSUE THREAD

**Issue by dhpizza** [bitnami/charts#10279]
### Name and Version

bitnami/spring-cloud-dataflow 7.0.1

### What steps will reproduce the bug?

1. Having a chart of spring-cloud-data-flow in a cluster with old images 
    ```
       ...
      server:
        image: springcloud/spring-cloud-dataflow-server
        version: 2.5.3.RELEASE
      skipper:
        image: springcloud/spring-cloud-skipper-server
        version: 2.4.1.RELEASE
    ```
installed with a postgresql as RDBMS attached

2. Upgrading the skipper and the server to the bitnami chart i.e now using 
    ```
       ...
      server:
        image: docker.io/bitnami/spring-cloud-dataflow
        version: 2.9.3-debian-10-r4
      skipper:
        image: docker.io/bitnami/spring-cloud-skipper
        version: 2.8.3-debian-10-r4
     ...
    ```
3. results in a perfectly upgraded scdf server but all previously DEPLOYED streams show now status UNDEPLOYED.

### Are you using any custom parameters or values?

Injecting the plain bitnami/spring-cloud-dataflow chart as dependency in the Chart.yaml

```
dependencies:
  - name: spring-cloud-dataflow
    version: 7.0.1
    repository: "https://charts.bitnami.com/bitnami"
```

and additionally custom server-configmap.yaml and skipper-configmap.yaml

### What is the expected behavior?

The skipper should find the correct status of the streams in its DB and server should present status DEPLOYED.

### What do you see instead?

The scdf server shows streams as UNDEPLOYED.

### Additional information

Since this is a very high jump in version and also coming from _springcloud_ to _bitnami_ I failed to find a consistent changelog to find out about any possible breaking changes in the skipper data-structure that might be a reason for the skipper failing to read the DB correctly.
