### ISSUE TITLE
[MongoDB] Prometheus Exporter Metrics Issue

### ISSUE THREAD

**Issue by kaykhancheckpoint** [bitnami/charts#10294]
### Name and Version

`binami/mongodb latest`

### What steps will reproduce the bug?

`helm install -f values.yml mongodb-prod bitnami/mongodb -n mongodb --create-namespace`

### Are you using any custom parameters or values?

```yaml
global:
  namespaceOverride: mongodb
architecture: replicaset
auth:
  rootPassword: "<redacted>"
  replicaSetKey: "<redacted?"
replicaCount: 1
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: geeiq/node-type
          operator: In
          values:
          - ops
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/component: mongodb
      topologyKey: kubernetes.io/hostname

serviceAccount:
  create: true
rbac:
  create: true
persistence:
  storageClass: "mongodb"
  size: 250Gi
externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
 ```

### What is the expected behavior?

I expect MongoDB to export Prometheus metrics

### What do you see instead?

I only see Kubernetes metrics in Prometheus.

### Additional information

I am setting up `mongodb` and `kube-prmetheus-stack` on a new EKS cluster. I noticed that the grafana dashboard we use to monitor MongoDB does not appear to me showing any metrics for MongoDB. However, it does see the instance.

![image](https://user-images.githubusercontent.com/65535942/169015584-7bf37f89-c037-4d19-9d05-90234587501a.png)

I checked the serviceDiscovery of Prometheus and I can see that MongoDB is indeed there. Although this is where I'm unsure and might be where the problem is. I can see the metrics are Kubernetes metrics? and not mongo/mongodb_ specific metrics.

![image](https://user-images.githubusercontent.com/65535942/169015950-cf67b157-3ec7-4ebb-a56b-e596b34bdc39.png)

**kubectl get all -n mongodb**

```
NAME                         READY   STATUS    RESTARTS   AGE
pod/mongodb-prod-0           2/2     Running   0          22m
pod/mongodb-prod-arbiter-0   1/1     Running   0          22m

NAME                                    TYPE           CLUSTER-IP       EXTERNAL-IP                                                              PORT(S)           AGE
service/mongodb-prod-0-external         LoadBalancer   172.20.230.162   <redacted>-<redacted>.eu-west-2.elb.amazonaws.com   27017:31838/TCP   22m
service/mongodb-prod-arbiter-headless   ClusterIP      None             <none>                                                                   27017/TCP         22m
service/mongodb-prod-headless           ClusterIP      None             <none>                                                                   27017/TCP         22m
service/mongodb-prod-metrics            ClusterIP      172.20.169.81    <none>                                                                   9216/TCP          22m

NAME                                    READY   AGE
statefulset.apps/mongodb-prod           1/1     22m
statefulset.apps/mongodb-prod-arbiter   1/1     22m
```

 **kubectl get all -n monitoring**

```
NAME                                                           READY   STATUS    RESTARTS   AGE
pod/alertmanager-kube-prometheus-stack-alertmanager-0          2/2     Running   0          37m
pod/kube-prometheus-stack-grafana-9757f9cb8-vxxz4              3/3     Running   0          37m
pod/kube-prometheus-stack-kube-state-metrics-d699cc95f-4vss4   1/1     Running   0          37m
pod/kube-prometheus-stack-operator-6999f4bcf8-zdqc7            1/1     Running   0          37m
pod/kube-prometheus-stack-prometheus-node-exporter-cdmjg       1/1     Running   0          37m
pod/kube-prometheus-stack-prometheus-node-exporter-jg672       1/1     Running   0          37m
pod/kube-prometheus-stack-prometheus-node-exporter-t54dz       1/1     Running   0          37m
pod/kube-prometheus-stack-prometheus-node-exporter-v8q89       1/1     Running   0          37m
pod/prometheus-kube-prometheus-stack-prometheus-0              2/2     Running   0          37m

NAME                                                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
service/alertmanager-operated                            ClusterIP   None             <none>        9093/TCP,9094/TCP,9094/UDP   37m
service/kube-prometheus-stack-alertmanager               ClusterIP   172.20.223.24    <none>        9093/TCP                     37m
service/kube-prometheus-stack-grafana                    NodePort    172.20.46.200    <none>        80:32534/TCP                 37m
service/kube-prometheus-stack-kube-state-metrics         ClusterIP   172.20.204.178   <none>        8080/TCP                     37m
service/kube-prometheus-stack-operator                   ClusterIP   172.20.65.16     <none>        443/TCP                      37m
service/kube-prometheus-stack-prometheus                 ClusterIP   172.20.106.7     <none>        9090/TCP                     37m
service/kube-prometheus-stack-prometheus-node-exporter   ClusterIP   172.20.74.140    <none>        9100/TCP                     37m
service/prometheus-operated                              ClusterIP   None             <none>        9090/TCP                     37m

NAME                                                            DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/kube-prometheus-stack-prometheus-node-exporter   4         4         4       4            4           <none>          37m

NAME                                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/kube-prometheus-stack-grafana              1/1     1            1           37m
deployment.apps/kube-prometheus-stack-kube-state-metrics   1/1     1            1           37m
deployment.apps/kube-prometheus-stack-operator             1/1     1            1           37m

NAME                                                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/kube-prometheus-stack-grafana-9757f9cb8              1         1         1       37m
replicaset.apps/kube-prometheus-stack-kube-state-metrics-d699cc95f   1         1         1       37m
replicaset.apps/kube-prometheus-stack-operator-6999f4bcf8            1         1         1       37m

NAME                                                               READY   AGE
statefulset.apps/alertmanager-kube-prometheus-stack-alertmanager   1/1     37m
statefulset.apps/prometheus-kube-prometheus-stack-prometheus       1/1     37m
```

![image](https://user-images.githubusercontent.com/65535942/169017173-2444f860-7144-4740-9eb2-d6d6e27ac451.png)

Any ideas on what could be happening here with the dashboard, 

- are the metrics in Prometheus correct? 
- Is this dashboard not compatible anymore?

**Comment by kaykhancheckpoint** [comment]
I thought this may have been the issue https://github.com/bitnami/bitnami-docker-mongodb-exporter/issues/9

```
...
metrics:
  enabled: true
  image:
    tag: 0.11.2-debian-10-r131
  serviceMonitor:
    enabled: true
    namespace: monitoring
```

So i rolled back my metrics image, **but it did not solve the problem**
