### ISSUE TITLE
[bitnami/airflow] Airflow worker command and args not being applied to pod

### ISSUE THREAD

**Issue by junaidnasir-ps** [bitnami/charts#10305]
### Name and Version

bitnami/airflow 12.3.0

### What steps will reproduce the bug?

1. change `worker.command = ['/bin/bash'] ` and `worker.args = ['ls -l']`
2. deploy and trigger an airflow dag
3. describe worker pod using kubectl

### Are you using any custom parameters or values?

```yaml
executor: KubernetesExecutor
worker:
  readinessProbe:
    enabled: true
    initialDelaySeconds: 120
  args:
  - ls
  command:
  - /bin/bash
  image:
    debug: true
    tag: 2.2.5
  livenessProbe:
    enabled: true
    initialDelaySeconds: 180
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 250Mi
```

### What is the expected behavior?

worker.command should replace the default entrypoint/command of airflow-worker

### What do you see instead?

![Screenshot 2022-05-18 at 15 49 05](https://user-images.githubusercontent.com/85359588/169070735-8530a6dd-eea5-4883-a659-90ae7e2bbef4.png)

### Additional information

command and args works for airflow-web and scheduler.
