### ISSUE TITLE
[bitnami/mongodb] Disabling auto-generation of secrets prevents file "generate-certs.sh" from being created that is required for initialization

### ISSUE THREAD

**Issue by jwleon** [bitnami/charts#10300]
### Name and Version

bitnami/mongodb ^11.0.0

### What steps will reproduce the bug?

Having TLS enabled and setting `autoGenerated` to false results in the file `generate-certs.sh` not being created. The file is later on executed and it's absence therefore results in errors preventing pod startup. See [answer in other Issue](https://github.com/bitnami/charts/issues/10264#issuecomment-1129050845)

```
tls:
  enabled: true
  autoGenerated: false
  caCert: "...myCertCode..."
  caKey: "...myKeyCode..."
```

### What do you see instead?

The pod is going into a crash loop because the desired script is not starting.
