### ISSUE TITLE
rabbitmq chart 9.1.1 defines a field not supported by kubernetes in containerSecurityContext

### ISSUE THREAD

**Issue by pduboucher** [bitnami/charts#10310]
### Name and Version

bitnami/rabbitmq 9.1.1

### What steps will reproduce the bug?

**Kubernetes 1.21**
**helm v3.5.3**
**rabbitmq 3.9.13->3.9.16**

https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml#L546

```yaml
containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true
```

### Are you using any custom parameters or values?

no

### What is the expected behavior?

normal upgrade

### What do you see instead?

```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[0].securityContext): unknown field "enabled" in io.k8s.api.core.v1.SecurityContext
```

### Additional information

Line was removed and the upgrade completed.

```yaml
containerSecurityContext:
  runAsUser: 1001
  runAsNonRoot: true
```
