### ISSUE TITLE
Add affinity rules setting ability to bitnami/elasticsearch

### ISSUE THREAD

**Issue by Troyhy** [bitnami/charts#1032]
**bitnami/elasticsearch**:

**Description**

I'm not able to select nodes witch elasticsearch pods are created.

**Comment by rafariossaa** [comment]
Hi @Troyhy,
  Could you provide more information of what are you trying to do and the errors you get?

thanks forehand

**Comment by Troyhy** [comment]
Hi
I have cluster provisioned in Hezner cloud. Elastic needs  sysctl -w vm.max_map_count=262144 in order to start. This is not defined in all of the nodes in cluster.

So I need to do something like this:
``` yaml
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: elasticsearch-shedulable
            operator: Exists

 ```
