### ISSUE TITLE
Harbor portal gives 400 Bad Request when set to use ingress

### ISSUE THREAD

**Issue by johnwc** [bitnami/charts#10355]
### Name and Version

bitnami/harbor 13.1.4

### What steps will reproduce the bug?

1. Deploy bitnami/harbor using `ingress` as `exposureType`, using values.yaml file below....
2. Go to URL set in externalURL
3. Receive 400 error "The plain HTTP request was sent to HTTPS port"

### Are you using any custom parameters or values?

```YAML
adminPassword: 'xxxxx'
chartmuseum:
  absoluteUrl: false
  affinity: {}
  allowOverwrite: true
  anonymousGet: false
  args: []
  automountServiceAccountToken: false
  chartPostFormFieldName: ''
  chartRepoName: chartsRepo
  command: []
  containerPorts:
    http: 9999
    https: 9443
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
  contextPath: ''
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  depth: 1
  disableApi: false
  disableMetrics: false
  disableStatefiles: false
  enabled: true
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  image:
    debug: false
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/chartmuseum
    tag: 0.14.0-debian-10-r106
  indexLimit: ''
  initContainers: []
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  logJson: false
  maxStorageObjects: ''
  maxUploadSize: ''
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  priorityClassName: ''
  provPostFormFieldName: ''
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 1
  resources:
    limits: {}
    requests: {}
  schedulerName: ''
  service:
    ports:
      http: 80
      https: 443
  sidecars: []
  startupProbe:
    enabled: false
    failureThreshold: 15
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  storageTimestampTolerance: 1s
  tls:
    existingSecret: ''
  tolerations: []
  topologySpreadConstraints: {}
  updateStrategy:
    type: RollingUpdate
  useRedisCache: true
clair:
  adapter:
    args: []
    command: []
    containerPorts:
      http: 8080
      https: 8443
    containerSecurityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1001
    customLivenessProbe: {}
    customReadinessProbe: {}
    customStartupProbe: {}
    extraEnvVars: []
    extraEnvVarsCM: ''
    extraEnvVarsSecret: ''
    extraVolumeMounts: []
    image:
      debug: false
      pullPolicy: IfNotPresent
      pullSecrets: []
      registry: docker.io
      repository: bitnami/harbor-adapter-clair
      tag: 2.5.0-debian-10-r38
    lifecycleHooks: {}
    livenessProbe:
      enabled: true
      failureThreshold: 6
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      enabled: true
      failureThreshold: 6
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits: {}
      requests: {}
    service:
      ports:
        http: 8080
        https: 8443
    startupProbe:
      enabled: false
      failureThreshold: 15
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
  affinity: {}
  automountServiceAccountToken: false
  enabled: false
  extraVolumes: []
  hostAliases: []
  httpProxy: ''
  httpsProxy: ''
  initContainers: []
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  priorityClassName: ''
  replicaCount: 1
  schedulerName: ''
  server:
    args: []
    command: []
    containerPorts:
      api: 6060
      health: 6061
    containerSecurityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1001
    customLivenessProbe: {}
    customReadinessProbe: {}
    customStartupProbe: {}
    extraEnvVars: []
    extraEnvVarsCM: ''
    extraEnvVarsSecret: ''
    extraVolumeMounts: []
    image:
      debug: false
      pullPolicy: IfNotPresent
      pullSecrets: []
      registry: docker.io
      repository: bitnami/harbor-clair
      tag: 2.5.0-debian-10-r39
    lifecycleHooks: {}
    livenessProbe:
      enabled: true
      failureThreshold: 6
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      enabled: true
      failureThreshold: 6
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits: {}
      requests: {}
    service:
      ports:
        api: 6060
        health: 6061
    startupProbe:
      enabled: false
      failureThreshold: 15
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
  sidecars: []
  tls:
    existingSecret: ''
  tolerations: []
  topologySpreadConstraints: {}
  updateStrategy:
    type: RollingUpdate
  updatersInterval: 12
clusterDomain: cluster.local
commonAnnotations: {}
commonLabels: {}
core:
  affinity: {}
  args: []
  automountServiceAccountToken: false
  command: []
  configOverwriteJson: ''
  configOverwriteJsonSecret: ''
  containerPorts:
    http: 8080
    https: 8443
    metrics: 8001
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
  csrfKey: ''
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  image:
    debug: false
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/harbor-core
    tag: 2.5.0-debian-10-r41
  initContainers: []
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  priorityClassName: ''
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 1
  resources:
    limits: {}
    requests: {}
  schedulerName: ''
  secret: 'xxxxxxxxxxxxx'
  secretKey: ''
  secretName: 'harbor-core-comm.ourdomain.net-tls'
  service:
    ports:
      http: 80
      https: 443
      metrics: 8001
  sessionLifetime: ''
  sidecars: []
  startupProbe:
    enabled: false
    failureThreshold: 15
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  tls:
    existingSecret: ''
  tolerations: []
  topologySpreadConstraints: {}
  uaaSecret: ''
  updateStrategy:
    type: RollingUpdate
diagnosticMode:
  args:
    - infinity
  command:
    - sleep
  enabled: false
exporter:
  affinity: {}
  args: []
  automountServiceAccountToken: false
  command: []
  containerPorts:
    metrics: 8001
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  image:
    debug: false
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/harbor-exporter
    tag: 2.5.0-debian-10-r39
  initContainers: []
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  priorityClassName: ''
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 1
  resources:
    limits: {}
    requests: {}
  service:
    ports:
      metrics: 8001
  sidecars: []
  startupProbe:
    enabled: false
    failureThreshold: 15
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  tolerations: []
  topologySpreadConstraints: {}
  updateStrategy:
    type: RollingUpdate
exposureType: ingress
externalDatabase:
  clairDatabase: ''
  clairPassword: ''
  clairUsername: ''
  coreDatabase: ''
  host: localhost
  notaryServerDatabase: ''
  notaryServerPassword: ''
  notaryServerUsername: ''
  notarySignerDatabase: ''
  notarySignerPassword: ''
  notarySignerUsername: ''
  password: ''
  port: 5432
  sslmode: disable
  user: bn_harbor
externalRedis:
  chartmuseumDatabaseIndex: '3'
  clairAdapterDatabaseIndex: '4'
  coreDatabaseIndex: '0'
  host: localhost
  jobserviceDatabaseIndex: '1'
  password: ''
  port: 6379
  registryDatabaseIndex: '2'
  sentinel:
    enabled: false
    hosts: ''
    masterSet: mymaster
  trivyAdapterDatabaseIndex: '5'
externalURL: https://core.harbor.ourdomain.net
extraDeploy: []
fullnameOverride: ''
global:
  imagePullSecrets: []
  imageRegistry: ''
  storageClass: ''
ingress:
  core:
    annotations:
      ingress.kubernetes.io/proxy-body-size: '0'
      ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/proxy-body-size: '0'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
      cert-manager.io/cluster-issuer: letsencrypt
    apiVersion: ''
    controller: default
    extraHosts: []
    extraPaths: []
    extraRules: []
    extraTls: []
    hostname: core.harbor.ourdomain.net
    ingressClassName: 'nginx-lb'
    pathType: ImplementationSpecific
    secrets: []
    selfSigned: false
    tls: true
  notary:
    annotations:
      ingress.kubernetes.io/proxy-body-size: '0'
      ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/proxy-body-size: '0'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
      cert-manager.io/cluster-issuer: letsencrypt
    apiVersion: ''
    controller: default
    extraHosts: []
    extraPaths: []
    extraRules: []
    extraTls: []
    hostname: notary.harbor.ourdomain.net
    ingressClassName: 'nginx-lb'
    pathType: ImplementationSpecific
    secrets: []
    selfSigned: false
    tls: true
internalTLS:
  caBundleSecret: ''
  enabled: true
ipFamily:
  ipv4:
    enabled: true
  ipv6:
    enabled: true
jobservice:
  affinity: {}
  args: []
  automountServiceAccountToken: false
  command: []
  containerPorts:
    http: 8080
    https: 8443
    metrics: 8001
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  image:
    debug: false
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/harbor-jobservice
    tag: 2.5.0-debian-10-r31
  initContainers: []
  jobLogger: file
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  maxJobWorkers: 10
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  priorityClassName: ''
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  redisNamespace: harbor_job_service_namespace
  replicaCount: 1
  resources:
    limits: {}
    requests: {}
  schedulerName: ''
  secret: 'xxxxxxxx'
  service:
    ports:
      http: 80
      https: 443
      metrics: 8001
  sidecars: []
  startupProbe:
    enabled: false
    failureThreshold: 15
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  tls:
    existingSecret: ''
  tolerations: []
  topologySpreadConstraints: {}
  updateStrategy:
    type: RollingUpdate
kubeVersion: ''
logLevel: debug
metrics:
  enabled: false
  path: /metrics
  serviceMonitor:
    enabled: false
    honorLabels: false
    interval: ''
    jobLabel: ''
    labels: {}
    metricRelabelings: []
    namespace: ''
    relabelings: []
    scrapeTimeout: ''
    selector: {}
nameOverride: ''
nginx:
  affinity: {}
  args: []
  behindReverseProxy: false
  command: []
  containerPorts:
    http: 8080
    https: 8443
    notary: 4443
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  image:
    debug: false
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/nginx
    tag: 1.21.6-debian-10-r114
  initContainers: []
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  priorityClassName: ''
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 1
  resources:
    limits: {}
    requests: {}
  schedulerName: ''
  sidecars: []
  startupProbe:
    enabled: false
    failureThreshold: 15
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  tls:
    commonName: core.harbor.domain
    enabled: true
    existingSecret: ''
  tolerations: []
  topologySpreadConstraints: {}
  updateStrategy:
    type: RollingUpdate
notary:
  enabled: true
  secretName: ''
  server:
    affinity: {}
    args: []
    automountServiceAccountToken: false
    command: []
    containerPorts:
      server: 4443
    containerSecurityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1001
    customLivenessProbe: {}
    customReadinessProbe: {}
    customStartupProbe: {}
    extraEnvVars: []
    extraEnvVarsCM: ''
    extraEnvVarsSecret: ''
    extraVolumeMounts: []
    extraVolumes: []
    hostAliases: []
    image:
      debug: false
      pullPolicy: IfNotPresent
      pullSecrets: []
      registry: docker.io
      repository: bitnami/harbor-notary-server
      tag: 2.5.0-debian-10-r39
    initContainers: []
    lifecycleHooks: {}
    livenessProbe:
      enabled: true
      failureThreshold: 6
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    nodeAffinityPreset:
      key: ''
      type: ''
      values: []
    nodeSelector: {}
    podAffinityPreset: ''
    podAnnotations: {}
    podAntiAffinityPreset: soft
    podLabels: {}
    podSecurityContext:
      enabled: true
      fsGroup: 1001
    priorityClassName: ''
    readinessProbe:
      enabled: true
      failureThreshold: 6
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    replicaCount: 1
    resources:
      limits: {}
      requests: {}
    schedulerName: ''
    sidecars: []
    startupProbe:
      enabled: false
      failureThreshold: 15
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    tolerations: []
    topologySpreadConstraints: {}
    updateStrategy:
      type: RollingUpdate
  service:
    ports:
      server: 4443
      signer: 7899
  signer:
    affinity: {}
    args: []
    automountServiceAccountToken: false
    command: []
    containerPorts:
      signer: 7899
    containerSecurityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1001
    customLivenessProbe: {}
    customReadinessProbe: {}
    customStartupProbe: {}
    extraEnvVars: []
    extraEnvVarsCM: ''
    extraEnvVarsSecret: ''
    extraVolumeMounts: []
    extraVolumes: []
    hostAliases: []
    image:
      debug: false
      pullPolicy: IfNotPresent
      pullSecrets: []
      registry: docker.io
      repository: bitnami/harbor-notary-signer
      tag: 2.5.0-debian-10-r39
    initContainers: []
    lifecycleHooks: {}
    livenessProbe:
      enabled: true
      failureThreshold: 6
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    nodeAffinityPreset:
      key: ''
      type: ''
      values: []
    nodeSelector: {}
    podAffinityPreset: ''
    podAnnotations: {}
    podAntiAffinityPreset: soft
    podLabels: {}
    podSecurityContext:
      enabled: true
      fsGroup: 1001
    priorityClassName: ''
    readinessProbe:
      enabled: true
      failureThreshold: 6
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    replicaCount: 1
    resources:
      limits: {}
      requests: {}
    schedulerName: ''
    sidecars: []
    startupProbe:
      enabled: false
      failureThreshold: 15
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    tolerations: []
    topologySpreadConstraints: {}
    updateStrategy:
      type: RollingUpdate
persistence:
  enabled: true
  imageChartStorage:
    azure:
      accountkey: base64encodedaccountkey
      accountname: accountname
      container: containername
      realm: ''
      storagePrefix: /azure/harbor/charts
    caBundleSecret: ''
    disableredirect: false
    filesystem:
      maxthreads: ''
      rootdirectory: /storage
    gcs:
      bucket: bucketname
      chunksize: ''
      encodedkey: base64-encoded-json-key-file
      rootdirectory: ''
    oss:
      accesskeyid: ''
      accesskeysecret: ''
      bucket: ''
      chunksize: ''
      encrypt: ''
      endpoint: ''
      internal: ''
      region: ''
      rootdirectory: ''
      secretkey: ''
      secure: ''
    s3:
      accesskey: ''
      bucket: bucketname
      chunksize: ''
      encrypt: ''
      keyid: ''
      region: us-west-1
      regionendpoint: ''
      rootdirectory: ''
      secretkey: ''
      secure: ''
      skipverify: ''
      sse: ''
      storageClass: ''
      v4auth: ''
    swift:
      accesskey: ''
      authurl: https://storage.myprovider.com/v3/auth
      authversion: ''
      chunksize: ''
      container: ''
      domain: ''
      domainid: ''
      endpointtype: ''
      insecureskipverify: ''
      password: ''
      prefix: ''
      region: ''
      secretkey: ''
      tempurlcontainerkey: ''
      tempurlmethods: ''
      tenant: ''
      tenantid: ''
      trustid: ''
      username: ''
    type: filesystem
  persistentVolumeClaim:
    chartmuseum:
      accessModes:
        - ReadWriteOnce
      annotations: {}
      existingClaim: ''
      selector: {}
      size: 5Gi
      storageClass: 'longhorn'
      subPath: ''
    jobservice:
      accessModes:
        - ReadWriteOnce
      annotations: {}
      existingClaim: ''
      selector: {}
      size: 1Gi
      storageClass: 'longhorn'
      subPath: ''
    registry:
      accessModes:
        - ReadWriteOnce
      annotations: {}
      existingClaim: ''
      selector: {}
      size: 5Gi
      storageClass: 'longhorn'
      subPath: ''
    trivy:
      accessModes:
        - ReadWriteOnce
      annotations: {}
      selector: {}
      size: 5Gi
      storageClass: 'longhorn'
  resourcePolicy: keep
portal:
  affinity: {}
  args: []
  automountServiceAccountToken: false
  command: []
  containerPorts:
    http: 8080
    https: 8443
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  image:
    debug: false
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/harbor-portal
    tag: 2.5.0-debian-10-r39
  initContainers: []
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  priorityClassName: ''
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 1
  resources:
    limits: {}
    requests: {}
  schedulerName: ''
  service:
    ports:
      http: 80
      https: 443
  sidecars: []
  startupProbe:
    enabled: false
    failureThreshold: 15
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  tls:
    existingSecret: ''
  tolerations: []
  topologySpreadConstraints: {}
  updateStrategy:
    type: RollingUpdate
postgresql:
  architecture: standalone
  auth:
    enablePostgresUser: true
    existingSecret: ''
    postgresPassword: xxxxx
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 13.7.0-debian-10-r7
  primary:
    extendedConfiguration: |
      max_connections = 1024
    initdb:
      scripts:
        initial-notaryserver.sql: |
          CREATE DATABASE notaryserver;
          CREATE USER server;
          alter user server with encrypted password 'password';
          GRANT ALL PRIVILEGES ON DATABASE notaryserver TO server;
        initial-notarysigner.sql: |
          CREATE DATABASE notarysigner;
          CREATE USER signer;
          alter user signer with encrypted password 'password';
          GRANT ALL PRIVILEGES ON DATABASE notarysigner TO signer;
        initial-registry.sql: >
          CREATE DATABASE registry ENCODING 'UTF8';

          \c registry;

          CREATE TABLE schema_migrations(version bigint not null primary key,
          dirty boolean not null);
proxy:
  components:
    - core
    - jobservice
    - clair
    - trivy
  httpProxy: ''
  httpsProxy: ''
  noProxy: 127.0.0.1,localhost,.local,.internal
redis:
  architecture: standalone
  auth:
    enabled: false
    existingSecret: ''
    password: ''
  enabled: true
registry:
  affinity: {}
  automountServiceAccountToken: false
  controller:
    args: []
    command: []
    containerPorts:
      http: 8080
      https: 8443
    containerSecurityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1001
    customLivenessProbe: {}
    customReadinessProbe: {}
    customStartupProbe: {}
    extraEnvVars: []
    extraEnvVarsCM: ''
    extraEnvVarsSecret: ''
    extraVolumeMounts: []
    image:
      debug: false
      pullPolicy: IfNotPresent
      pullSecrets: []
      registry: docker.io
      repository: bitnami/harbor-registryctl
      tag: 2.5.0-debian-10-r39
    lifecycleHooks: {}
    livenessProbe:
      enabled: true
      failureThreshold: 6
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      enabled: true
      failureThreshold: 6
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits: {}
      requests: {}
    service:
      ports:
        http: 8080
        https: 8443
    startupProbe:
      enabled: false
      failureThreshold: 15
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
  credentials:
    htpasswd: >-
      user:$xxxxxxxxx
    password: xxxxx
    username: user
  extraVolumes: []
  hostAliases: []
  initContainers: []
  middleware:
    cloudFront:
      baseurl: example.cloudfront.net
      duration: 3000s
      ipfilteredby: none
      keypairid: KEYPAIRID
      privateKeySecret: my-secret
    enabled: false
    type: cloudFront
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  priorityClassName: ''
  relativeurls: false
  replicaCount: 1
  schedulerName: ''
  secret: 'xxxxxxxxxx'
  server:
    args: []
    command: []
    containerPorts:
      debug: 5001
      http: 5000
      https: 5443
      metrics: 8001
    containerSecurityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1001
    customLivenessProbe: {}
    customReadinessProbe: {}
    customStartupProbe: {}
    extraEnvVars: []
    extraEnvVarsCM: ''
    extraEnvVarsSecret: ''
    extraVolumeMounts: []
    image:
      debug: false
      pullPolicy: IfNotPresent
      pullSecrets: []
      registry: docker.io
      repository: bitnami/harbor-registry
      tag: 2.5.0-debian-10-r39
    lifecycleHooks: {}
    livenessProbe:
      enabled: true
      failureThreshold: 6
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      enabled: true
      failureThreshold: 6
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits: {}
      requests: {}
    service:
      ports:
        http: 5000
        https: 5443
        metrics: 8001
    startupProbe:
      enabled: false
      failureThreshold: 15
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
  sidecars: []
  tls:
    existingSecret: ''
  tolerations: []
  topologySpreadConstraints: {}
  updateStrategy:
    type: RollingUpdate
service:
  annotations: {}
  clusterIP: ''
  externalTrafficPolicy: Cluster
  extraPorts: []
  loadBalancerIP: ''
  loadBalancerSourceRanges: []
  nodePorts:
    http: ''
    https: ''
    notary: ''
  ports:
    http: 80
    https: 443
    notary: 4443
  sessionAffinity: None
  type: LoadBalancer
trivy:
  affinity: {}
  args: []
  automountServiceAccountToken: false
  cacheDir: /bitnami/harbor-adapter-trivy/.cache
  command: []
  containerPorts:
    http: 8080
    https: 8443
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  debugMode: false
  enabled: true
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraVolumeMounts: []
  extraVolumes: []
  gitHubToken: ''
  hostAliases: []
  ignoreUnfixed: false
  image:
    debug: false
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/harbor-adapter-trivy
    tag: 2.5.0-debian-10-r40
  initContainers: []
  insecure: false
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  priorityClassName: ''
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  schedulerName: ''
  service:
    ports:
      http: 8080
      https: 8443
  severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
  sidecars: []
  skipUpdate: false
  startupProbe:
    enabled: false
    failureThreshold: 15
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  tls:
    existingSecret: ''
  tolerations: []
  topologySpreadConstraints: {}
  updateStrategy:
    type: RollingUpdate
  vulnType: os,library
volumePermissions:
  containerSecurityContext:
    enabled: true
    runAsUser: 0
  enabled: false
  image:
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 10-debian-10-r431
  resources:
    limits: {}
    requests: {}
```

### What is the expected behavior?

Ingress work correctly pointing to portal with either proper configured https, or point to non-secure http and let ingress controller handle SSL termination.

### What do you see instead?

```
400 Bad Request
The plain HTTP request was sent to HTTPS port
nginx/1.21.6
```
