### ISSUE TITLE
[bitnami/etcd] Issue starting the cluster from startFromSnapshot

### ISSUE THREAD

**Issue by CharesLee** [bitnami/charts#10358]
Hi, I am using Bitnami/etcd Version 6.8.2 and I have a problem starting the cluster from startFromSnapshot。

Below is my PVC list
```
NAME          STATUS   VOLUME                   CAPACITY   ACCESS MODES   STORAGECLASS                         AGE
data-etcd-0   Bound    d-2zeecw0l27h5u8fjdmdb   20Gi       RWO            alicloud-disk-efficiency-beijing-d   14m
data-etcd-1   Bound    d-2zeecw0l27h5u8fjdmdc   20Gi       RWO            alicloud-disk-efficiency-beijing-d   14m
data-etcd-2   Bound    d-2zegxsdco1bur9unmxtd   20Gi       RWO            alicloud-disk-efficiency-beijing-d   14m
snapshots     Bound    d-2ze2q97e0772k3662be7   20Gi       RWX            alicloud-disk-efficiency-beijing-d   19m
```

These are my values.yaml configurations
```yaml
image:
    registry: harbor.xxx.com
    repository: etcd/etcd
    tag: 3.5.0-debian-10-r64
 auth:
    rbac:
      rootPassword: xxxx
  
  replicaCount: 3
  
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
  
  volumePermissions:
    enabled: true
    image:
      registry: harbor.xxx.com
      repository: bitnami/bitnami-shell
      tag: "10-debian-10-r172"
      pullPolicy: Always
  
  persistence:
    enabled: true
    size: 20Gi
  
  startFromSnapshot:
    enabled: true
    existingClaim: "snapshots"
    snapshotFilename: "db-2022-05-19_13-00"
```

I uninstalled etcd and re-installed it using the above configuration，But the cluster cannot be recovered
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/23518280/169487748-3039e847-83ad-4844-b2d1-001f9be2f96f.png">

Log in to etcd-1 to view information
```
I have no name!@etcd-1:/opt/bitnami/etcd$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         148G   47G   96G  33% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/vdk         20G  101M   20G   1% /init-snapshot
/dev/vda1       148G   47G   96G  33% /etc/hosts
/dev/vdi         20G  223M   20G   2% /bitnami/etcd
shm              64M     0   64M   0% /dev/shm
tmpfs           7.9G   12K  7.9G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs           7.9G     0  7.9G   0% /proc/acpi
tmpfs           7.9G     0  7.9G   0% /proc/scsi
tmpfs           7.9G     0  7.9G   0% /sys/firmware
I have no name!@etcd-1:/opt/bitnami/etcd$ ls /init-snapshot/
db-2022-05-19_13-00  lost+found
I have no name!@etcd-1:/opt/bitnami/etcd$ ls -al /init-snapshot/
total 58020
drwxr-xr-x 3 root root     4096 May 20 08:04 .
drwxr-xr-x 1 root root     4096 May 20 08:27 ..
-rw------- 1 1001 root 59383840 May 20 08:04 db-2022-05-19_13-00
drwx------ 2 root root    16384 May 20 08:02 lost+found
```
View the logs of etcd-2 and etcd-0
```console
$ kubectl logs -f -n etcd-lhc-test etcd-2
etcd 08:29:11.52
etcd 08:29:11.53 Welcome to the Bitnami etcd container
etcd 08:29:11.53 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-etcd
etcd 08:29:11.53 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-etcd/issues
etcd 08:29:11.53
etcd 08:29:11.53 INFO  ==> ** Starting etcd setup **
etcd 08:29:11.55 INFO  ==> Validating settings in ETCD_* env vars..
etcd 08:29:11.55 ERROR ==> You are trying to initialize etcd from a snapshot, but no snapshot was found. Set the environment variable ETCD_INIT_SNAPSHOT_FILENAME with the snapshot filename and mount it at '/init-snapshot' directory.
```

How can I repair my ETCD cluster， TKS！

_Originally posted by @CharesLee in https://github.com/bitnami/bitnami-docker-etcd/issues/7#issuecomment-1132621869_

**Comment by carrodher** [comment]
According to 
```yaml
    registry: harbor.xxx.com
    repository: etcd/etcd
    tag: 3.5.0-debian-10-r64
```
Are you cloning the `bitnami/etcd` image into a private Harbor instance changing the name to `etcd/etcd` or are you directly using the `etcd/etcd` image?
