### ISSUE TITLE
loadBalancingOnWrite should be disableloadBalancingOnWrite

### ISSUE THREAD

**Issue by David-Angel** [bitnami/charts#10373]
### Name and Version

bitnami/postgresql-ha/master

### What steps will reproduce the bug?

1. In postgresql-ha \ values.yaml
2. master (latest)
3. look for "pgpool.loadBalancingOnWrite"
4. Within the same project search for it being assigned to the container.
5.
```yaml
            - name: PGPOOL_DISABLE_LOAD_BALANCE_ON_WRITE
              value: {{ .Values.pgpool.loadBalancingOnWrite }}
```
Notice the name is opposite of the real name causing confusion when the value is set.
Developers set this to "always" not knowing it was "disable".

### What do you see instead?
```yaml
  ## @param pgpool.loadBalancingOnWrite LoadBalancer on write actions behavior
  ## one of: [off, transaction, trans_transaction, always]
  ##
  loadBalancingOnWrite: transaction
```
And here:
```yaml
            {{- if .Values.pgpool.useLoadBalancing }}
            - name: PGPOOL_**DISABLE**_LOAD_BALANCE_ON_WRITE
              value: {{ .Values.pgpool.loadBalancingOnWrite }}
            {{- end }}
```
