### ISSUE TITLE
[bitnami/harbor] Images manifest is missing

### ISSUE THREAD

**Issue by pascalrimann** [bitnami/charts#10393]
### Name and Version

bitnami/harbor 12.3.6

### What steps will reproduce the bug?

Hi, at our harbor installation we have the problem that some images are not able to be pulled, even when the image is on the web page from harbor.

the images was all pushed when we was at harbor 2.4.x and now on 2.5.0 we have this problem

```bash
rimannp@vls-10-t632-prod-mgt:~> docker pull harbor.infra.k8s.akdb.net/t527/akdb/egov/bsp/base/support-tool:2022.4.27-T154353
Error response from daemon: manifest for harbor.infra.k8s.akdb.net/t527/akdb/egov/bsp/base/support-tool:2022.4.27-T154353 not found: manifest unknown: manifest unknown
rimannp@vls-10-t632-prod-mgt:~>
```

![image](https://user-images.githubusercontent.com/86711849/170195683-c6db3b03-2eae-46a8-94ce-acec16e5b033.png)

### Are you using any custom parameters or values?

```yaml
internalTLS:
  enabled: true
  caBundleSecret: "secret-name"

externalURL: https://harbor.url.net

logLevel: info

proxy:
  httpProxy: http://proxy.url.net:3128
  httpsProxy: http://proxy.url.net:3128
  noProxy: 127.0.0.1,localhost,.local,.internal,.url.net
  components:
    - core
    - jobservice
    - clair
    - trivy

exposureType: ingress

ingress:
  core:
    pathType: ImplementationSpecific
    hostname: harbor.url.net
    annotations:
      ingress.kubernetes.io/ssl-redirect: 'true'
      ingress.kubernetes.io/proxy-body-size: '0'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/proxy-body-size: '0'
  notary:
    pathType: ImplementationSpecific
    hostname: notary.url.net
    annotations:
      ingress.kubernetes.io/ssl-redirect: 'true'
      ingress.kubernetes.io/proxy-body-size: '0'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/proxy-body-size: '0'


persistence:
  enabled: true
  resourcePolicy: 'keep'
  persistentVolumeClaim:
    registry:
      accessMode: ReadWriteOnce
      size: 5Gi
    jobservice:
      accessMode: ReadWriteOnce
      size: 1Gi
    chartmuseum:
      accessMode: ReadWriteOnce
      size: 5Gi
    trivy:
      accessMode: ReadWriteOnce
      size: 5Gi

postgresql:
  enabled: false

externalDatabase:
  host: postgresha-postgresql-ha-pgpool
  user: harbor
  sslmode: disable
  coreDatabase: "core"
  clairDatabase: "clair"
  clairUsername: "clair"
  notaryServerDatabase: "notaryserver"
  notaryServerUsername: "notaryserver"
  notarySignerDatabase: "notarysigner"
  notarySignerUsername: "notarysigner"

redis:
  enabled: false
#   replica:
#     persistence:
#       enabled: true

externalRedis:
  host: redisha
  sentinel:
    enabled: true
    masterSet: harbor-redis-master
    hosts: redisha:26379

nginx:
  replicaCount: 3
  tls:
    enabled: true
    commonName: harbor.url.net

portal:
  replicaCount: 3

core:
  replicaCount: 3

jobservice:
  replicaCount: 3

registry:
  replicaCount: 3

chartmuseum:
  enabled: false

clair:
  replicaCount: 3

notary:
  server:
    replicaCount: 3
  signer:
    replicaCount: 3
  
trivy:
  replicaCount: 3
```

### What is the expected behavior?

image to be downloaded

### What do you see instead?

image not downloaded

### Additional information

here an short output from the registry during an failing docker pull

```log

harbor-registry-78df976c86-k562n registry 10.42.3.227 - - [25/May/2022:06:52:55 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
harbor-registry-78df976c86-k562n registryctl 10.42.3.227 - - [25/May/2022:06:52:55 +0000] "GET /api/health HTTP/1.1" 200 9
harbor-registry-78df976c86-svddt registry time="2022-05-25T06:52:58.256164397Z" level=info msg="authorized request" go.version=go1.15 http.request.host=harbor.infra.k8s.akdb.net http.request.id=67e8cbed-77e5-4841-bca4-b7ff9059c5a0 http.request.method=HEAD http.request.remoteaddr=172.18.3.230 http.request.uri="/v2/t527/akdb/egov/bsp/base/support-tool/manifests/sha256:62ff5982eb8f853192e4795aa16570d0450d347d3f537db0962a0d85c5075933" http.request.useragent="docker/20.10.12-ce go/go1.16.13 git-commit/459d0dfbbb51 kernel/5.3.18-150300.59.63-default os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.12-ce \(linux\))" vars.name="t527/akdb/egov/bsp/base/support-tool" vars.reference="sha256:62ff5982eb8f853192e4795aa16570d0450d347d3f537db0962a0d85c5075933"
harbor-registry-78df976c86-svddt registry time="2022-05-25T06:52:58.258439179Z" level=error msg="error connecting to redis instance redisha:26379/harbor-redis-master:6379: dial tcp: address redisha:26379/harbor-redis-master:6379: too many colons in address" go.version=go1.15 instance.id=1fdd97d8-ab0d-496c-9d87-f6785379c37f service=registry version=v2.8.0
harbor-registry-78df976c86-svddt registry time="2022-05-25T06:52:58.258468621Z" level=error msg="redis: error connecting: dial tcp: address redisha:26379/harbor-redis-master:6379: too many colons in address" go.version=go1.15 instance.id=1fdd97d8-ab0d-496c-9d87-f6785379c37f redis.connect.duration=40.466µs service=registry version=v2.8.0
harbor-registry-78df976c86-svddt registry time="2022-05-25T06:52:58.258786516Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code="manifest unknown" err.detail="unknown manifest name=t527/akdb/egov/bsp/base/support-tool revision=sha256:62ff5982eb8f853192e4795aa16570d0450d347d3f537db0962a0d85c5075933" err.message="manifest unknown" go.version=go1.15 http.request.host=harbor.infra.k8s.akdb.net http.request.id=67e8cbed-77e5-4841-bca4-b7ff9059c5a0 http.request.method=HEAD http.request.remoteaddr=172.18.3.230 http.request.uri="/v2/t527/akdb/egov/bsp/base/support-tool/manifests/sha256:62ff5982eb8f853192e4795aa16570d0450d347d3f537db0962a0d85c5075933" http.request.useragent="docker/20.10.12-ce go/go1.16.13 git-commit/459d0dfbbb51 kernel/5.3.18-150300.59.63-default os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.12-ce \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=78.551556ms http.response.status=404 http.response.written=212 vars.name="t527/akdb/egov/bsp/base/support-tool" vars.reference="sha256:62ff5982eb8f853192e4795aa16570d0450d347d3f537db0962a0d85c5075933"
harbor-registry-78df976c86-svddt registry 10.42.5.59 - - [25/May/2022:06:52:58 +0000] "HEAD /v2/t527/akdb/egov/bsp/base/support-tool/manifests/sha256:62ff5982eb8f853192e4795aa16570d0450d347d3f537db0962a0d85c5075933 HTTP/1.1" 404 212 "" "docker/20.10.12-ce go/go1.16.13 git-commit/459d0dfbbb51 kernel/5.3.18-150300.59.63-default os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.12-ce \\(linux\\))"
harbor-registry-78df976c86-svddt registryctl 10.42.5.172 - - [25/May/2022:06:52:58 +0000] "GET /api/health HTTP/2.0" 200 9
harbor-registry-78df976c86-svddt registryctl 10.42.5.172 - - [25/May/2022:06:52:58 +0000] "GET /api/health HTTP/2.0" 200 9
harbor-registry-78df976c86-svddt registry 10.42.5.172 - - [25/May/2022:06:52:58 +0000] "GET / HTTP/2.0" 200 0 "" "kube-probe/1.22"
harbor-registry-78df976c86-svddt registry 10.42.5.172 - - [25/May/2022:06:52:58 +0000] "GET / HTTP/2.0" 200 0 "" "kube-probe/1.22"
harbor-registry-78df976c86-k562n registry time="2022-05-25T06:52:58.36050804Z" level=info msg="authorized request" go.version=go1.15 http.request.host=harbor.infra.k8s.akdb.net http.request.id=04b38669-795d-4928-87a7-95d7c6ebd07c http.request.method=GET http.request.remoteaddr=172.18.3.230 http.request.uri="/v2/t527/akdb/egov/bsp/base/support-tool/manifests/sha256:62ff5982eb8f853192e4795aa16570d0450d347d3f537db0962a0d85c5075933" http.request.useragent="docker/20.10.12-ce go/go1.16.13 git-commit/459d0dfbbb51 kernel/5.3.18-150300.59.63-default os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.12-ce \(linux\))" vars.name="t527/akdb/egov/bsp/base/support-tool" vars.reference="sha256:62ff5982eb8f853192e4795aa16570d0450d347d3f537db0962a0d85c5075933"
harbor-registry-78df976c86-k562n registry time="2022-05-25T06:52:58.36117565Z" level=error msg="error connecting to redis instance redisha:26379/harbor-redis-master:6379: dial tcp: address redisha:26379/harbor-redis-master:6379: too many colons in address" go.version=go1.15 instance.id=86ed71c2-2d88-4773-80f8-42dce961fbc7 service=registry version=v2.8.0
harbor-registry-78df976c86-k562n registry time="2022-05-25T06:52:58.361347922Z" level=error msg="redis: error connecting: dial tcp: address redisha:26379/harbor-redis-master:6379: too many colons in address" go.version=go1.15 instance.id=86ed71c2-2d88-4773-80f8-42dce961fbc7 redis.connect.duration=180.55µs service=registry version=v2.8.0
harbor-registry-78df976c86-k562n registry time="2022-05-25T06:52:58.362256092Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code="manifest unknown" err.detail="unknown manifest name=t527/akdb/egov/bsp/base/support-tool revision=sha256:62ff5982eb8f853192e4795aa16570d0450d347d3f537db0962a0d85c5075933" err.message="manifest unknown" go.version=go1.15 http.request.host=harbor.infra.k8s.akdb.net http.request.id=04b38669-795d-4928-87a7-95d7c6ebd07c http.request.method=GET http.request.remoteaddr=172.18.3.230 http.request.uri="/v2/t527/akdb/egov/bsp/base/support-tool/manifests/sha256:62ff5982eb8f853192e4795aa16570d0450d347d3f537db0962a0d85c5075933" http.request.useragent="docker/20.10.12-ce go/go1.16.13 git-commit/459d0dfbbb51 kernel/5.3.18-150300.59.63-default os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.12-ce \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=74.025734ms http.response.status=404 http.response.written=212 vars.name="t527/akdb/egov/bsp/base/support-tool" vars.reference="sha256:62ff5982eb8f853192e4795aa16570d0450d347d3f537db0962a0d85c5075933"
harbor-registry-78df976c86-k562n registry 10.42.3.227 - - [25/May/2022:06:52:58 +0000] "GET /v2/t527/akdb/egov/bsp/base/support-tool/manifests/sha256:62ff5982eb8f853192e4795aa16570d0450d347d3f537db0962a0d85c5075933 HTTP/1.1" 404 212 "" "docker/20.10.12-ce go/go1.16.13 git-commit/459d0dfbbb51 kernel/5.3.18-150300.59.63-default os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.12-ce \\(linux\\))"
```
