### ISSUE TITLE
[MongoDB] Created LoadBalancer only showing 1 out of 5 services in use 

### ISSUE THREAD

**Issue by kaykhancheckpoint** [bitnami/charts#10444]
### Name and Version

bitnami/mongodb

### What steps will reproduce the bug?

1. Create a new replicaset using the parameters with external access
2. Check the aws load balancer created in the ui

### Are you using any custom parameters or values?

```
global:
  namespaceOverride: staging
architecture: replicaset
auth:
  rootPassword: "<redacted>"
  replicaSetKey: "<redacted>"
replicaCount: 1
serviceAccount:
  create: true
rbac:
  create: true
persistence:
  storageClass: "mongodb"
  size: 250Gi
externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
```

### What is the expected behavior?

I expect 5 of 5 services to be in use?

### What do you see instead?

I saw only 1 of 5 services in use

### Additional information

![image](https://user-images.githubusercontent.com/65535942/170461881-09634b27-5be3-4330-ab7a-59e974efee9a.png)

You can see only 1 service is in use, the node which the mongodb pod is on. The others are out of services. What is happening here?

![image](https://user-images.githubusercontent.com/65535942/170462005-0fb971be-6608-4772-bdcc-8265c47c9a69.png)
