### ISSUE TITLE
Use Existing PVC Claim

### ISSUE THREAD

**Issue by abhinand5** [bitnami/charts#10473]
### Name and Version

bitnami/redis 16.10.0

### What steps will reproduce the bug?

**Environment:**
minikube version: v1.25.2
commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7

**Command:**
```bash
$ helm install redis-sentinel \
--set auth.enabled=false \
--set replica.replicaCount=3 \
--set sentinel.enabled=true \
--set master.persistence.existingClaim=dcm-redis-sentinel-pvc \
--version 16.10.0 \
bitnami/redis
```

I have created a custom provisoner using `k8s-sigs.io/nfs-subdir-external-provisioner`. I am using an external NFS server for persistence. 

**Deploying nfs-subdir-external-provisioner chart**
```bash
$ helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
    --set nfs.server=11.22.33.44 \
    --set nfs.path=/ \
    --set storageClass.provisionerName=k8s-sigs.io/nfs-subdir-external-provisioner
```

**Custom Storage Class**
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client-storage-class
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  pathPattern: "${.PVC.namespace}/${.PVC.annotations.nfs.io/storage-path}" # waits for nfs.io/storage-path annotation, if not specified will accept as empty string.
  onDelete: delete
```

**Custom PVC:**
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dcm-redis-sentinel-pvc
  annotations:
    nfs.io/storage-path: "redis-sentinel-cluster"
spec:
  storageClassName: nfs-client-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

### Are you using any custom parameters or values?

Only these varaibles are customized
```bash
$ helm install redis-sentinel \
--set auth.enabled=false \
--set replica.replicaCount=3 \
--set sentinel.enabled=true \
--set master.persistence.existingClaim=dcm-redis-sentinel-pvc \
--version 16.10.0 \
bitnami/redis
```

### What is the expected behavior?

In an ideal scenario I should be able to see the contents of `/data` directory in the remote NFS storage. 

But I can see that it is creating the subfolder mentioned in the pvc claim `redis-sentinel-cluster` and the PVC status is 'Bound'. But the contents of `/data` directory is nowhere to be found. But the deployment works well, as it does without the `existingClaim` variable.

### What do you see instead?

Contents of `/data` directory is not found in the remote provisioner. 

### Additional information

Other than this deployment, there are other deployments which I made for different purposes which are working well and storing data in the remote NFS server. I don't think it is a issue with remote storage.
