### ISSUE TITLE
mysql chart includes primary/secondary label in the anti-affinity key

### ISSUE THREAD

**Issue by blushingpenguin** [bitnami/charts#10501]
### Name and Version

bitnami/mysql-9.1.0

### What steps will reproduce the bug?

Use:
```yaml
architecture: replication
```
`kubectl get pod mysql-secondary-0 -o yaml`

```yaml
...
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: secondary
              app.kubernetes.io/instance: mysql
              app.kubernetes.io/name: mysql
          namespaces:
          - wordpress
          topologyKey: kubernetes.io/hostname
        weight: 1
```
The secondary has 'app.kubernetes.io/component: secondary' and the primary has 'app.kubernetes.io/component: primary' which means that primary/secondary can be scheduled on the same node.

### What is the expected behavior?

The pod anti affinity match should not include the primary/secondary label

### What do you see instead?

primary/secondary are labelled separately
