### ISSUE TITLE
[Redis-cluster] helm deployment always creates internet-facing classic load-balancer instead of internal load-balancer

### ISSUE THREAD

**Issue by nixancha** [bitnami/charts#10516]
### Name and Version

bitnami/redis-cluster 7.5.3

### What steps will reproduce the bug?

1. Kubernetes version: v1.19.16-eks-25803e
2. No specific config used. created a new namespace and ran command mentioned in line 3
3. Execute below helm command
```
helm install my-redis-cluster bitnami/redis-cluster --version 7.5.3 --set cluster.externalAccess.enabled=true --set service.metadata.annotations."service\.beta\.kubernetes.io/aws-load-balancer-type"="nlb" --set service.metadata.annotations."service\.beta\.kubernetes.io/aws-load-balancer-internal"="true" --set service.metadata.annotations."service\.beta\.kubernetes.io/aws-load-balancer-scheme"="internal"
```
Also tried below flag as well but
```
--set service.metadata.annotations."service\.beta\.kubernetes.io/aws-load-balancer-scheme"="internal"
```
4. No error observed, chart gets deployed but a internet-facing load balancer is created in AWS instead of internal

### Are you using any custom parameters or values?

Yes,

```
helm install my-redis-cluster bitnami/redis-cluster --version 7.5.3 
--set cluster.externalAccess.enabled=true 
--set service.metadata.annotations."service\.beta\.kubernetes.io/aws-load-balancer-type"="nlb" 
--set service.metadata.annotations."service\.beta\.kubernetes.io/aws-load-balancer-internal"="true"
--set service.metadata.annotations."service\.beta\.kubernetes.io/aws-load-balancer-scheme"="internal"
```

### What is the expected behavior?

Load balancer created after deployment should be internal and not internet-facing.

### What do you see instead?

Internet-facing load balancer where created in AWS

### Additional information

![image](https://user-images.githubusercontent.com/103242759/171362903-0a76d6c6-0091-448a-9799-7d8f9e4f7ab3.png)

**Comment by javsalgar** [comment]
Hi,

Could you check that the annotations are actually created with the service? If not, it seems to me that there's an issue with the EKS cluster and my advice would be to contact the AWS team.

**Comment by nixancha** [comment]
@javsalgar I checked and it seems there was extra period I forgot to escape and thus my annotations were being created as below:
```
USER-SUPPLIED VALUES:
cluster:
  externalAccess:
    enabled: true
service:
  metadata:
    annotations:
      service.beta.kubernetes:
        io/aws-load-balancer-internal: true
        io/aws-load-balancer-scheme: internal
        io/aws-load-balancer-type: nlb
```

I have fixed it by escaping the period between `kubernetes` and `io`
