### ISSUE TITLE
[Redis] Helm deployment  does not set slave hostnames correctly from the master's perspective

### ISSUE THREAD

**Issue by jensenkhem** [bitnami/charts#10533]
### Name and Version

bitnami/redis 16.5.0

### What steps will reproduce the bug?

1. Kubernetes v1.22.8
2. Create TLS secret in the default namespace containing certificates for Redis, called redis-tls-secret-dev via: `kubectl create secret -n default generic redis-tls-secret-dev "--from-file=./redis.pem" "--from-file=./redis-key.pem" "--from-file=root-ca.pem"`
3. Clone out chart at version 16.5.0 and execute the below command: 
`helm install . -f values.yaml --namespace default --name-template redis-scrs`
4. Run `kubectl -n default exec -it redis-scrs-master-0 -- redis-cli --tls --cert /opt/bitnami/redis/certs/redis.pem --key /opt/bitnami/redis/certs/redis-key.pem --cacert /opt/bitnami/redis/certs/root-ca.pem -a <password> role`

### Are you using any custom parameters or values?

Yes. Running with sentinel disabled, and TLS enabled. Additionally, we are using a custom Redis image, but it does not change any of Redis's functionality.
```
global:
  storageClass: nfs

tls:
  enabled: true
  existingSecret: "redis-tls-secret-dev"
  certFilename: "redis.pem"
  certKeyFilename: "redis-key.pem"
  certCAFilename: "root-ca.pem"

replica:
  replicaCount: 2

volumePermissions:
  enabled: true
  image:
    tag: 10-debian-10-r355

auth:
  password:<password>

commonLabels:
  sq: redis-scrs
```

### What is the expected behavior?

The result of the 'role' command should instead be: 
```
1) "master"
2) (integer) 92176
3) 1) 1) "redis-scrs-replicas-0.redis-scrs-headless.default.svc.cluster.local"
      2) "6379"
      3) "92176"
   2) 1) "redis-scrs-replicas-1.redis-scrs-headless.default.svc.cluster.local"
      2) "6379"
      3) "92176"
   3) 1) "redis-scrs-replicas-2.redis-scrs-headless.default.svc.cluster.local"
      2) "6379"
      3) "92176"
```

### What do you see instead?

```
1) "master"
2) (integer) 92176
3) 1) 1) "redis-scrs-replicas-0."
      2) "6379"
      3) "92176"
   2) 1) "redis-scrs-replicas-1."
      2) "6379"
      3) "92176"
   3) 1) "redis-scrs-replicas-2."
      2) "6379"
      3) "92176"
```
As you can see from the above examples, the hostnames of the replicas are cut off after the '.' character. This is causing me issues with running failover commands, since the hostnames specified here do not exist.

### Additional information

When running the same `role` command from one of the slave nodes, the hostname of the master appears correctly:
```
1) "slave"
2) "redis-scrs-master-0.redis-scrs-headless.default.svc.cluster.local"
3) (integer) 6379
4) "connected"
5) (integer) 92316
```
