### ISSUE TITLE
Enabled ghostEnableHttps and traefik config

### ISSUE THREAD

**Issue by Mantany** [bitnami/charts#10534]
### Name and Version

bitnami/ghost

### What steps will reproduce the bug?

Steps:

1. using k3s with traefik 
2. set ghostEnableHttps: true
3. visit the domain

Try the same config without https enabled, works but produces "mixed content" errors

- readinessProbe and startupProbe are good
- The logs on the ghost pod looking fine
- when I try to access the site via domain, I get an internal server error (traefik error site)
- when I try to access the site via the IP address of the pod, firefox says "SSL_ERROR_RX_RECORD_TOO_LONG"

I think it has something to do with the missing header information
"x-forwarded-proto: https"

Following the docs for [traefik](https://doc.traefik.io/traefik/v1.7/configuration/backends/kubernetes/) the additional annotations doesn't seem to do the trick.
```
ingress.kubernetes.io/ssl-proxy-headers: "X-Forwarded-Proto: https"
ingress.kubernetes.io/ssl-redirect: "true"
```

Does anybody has the same issues? 

### Are you using any custom parameters or values?
```
ghostHost: "example.com"
ghostPath: /
ghostEnableHttps: true
ingress:
  enabled: true
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: examle.com
  path: /
  annotations: 
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls: true

```
### What is the expected behavior?

I should see the website, when I visit the domain

### What do you see instead?

internal server error
