### ISSUE TITLE
[mongodb] - arbiter ----- MongoServerError: Authentication failed.

### ISSUE THREAD

**Issue by ashish-kumar-sw** [bitnami/charts#10557]
### Name and Version

bitnami/mongo    ---   version: 12.1.10

### What steps will reproduce the bug?

MongoDB was running properly, and all of a sudden after 8 days of running, the arbiter starts restarting. We just gave root password in values.yaml and nothing else.

Logs :
```console
$ k logs common-mongodb-arbiter-0
mongodb 07:06:31.23 
mongodb 07:06:31.23 Welcome to the Bitnami mongodb container
mongodb 07:06:31.23 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 07:06:31.23 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 07:06:31.23 
mongodb 07:06:31.24 INFO  ==> ** Starting MongoDB setup **
mongodb 07:06:31.25 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 07:06:31.31 INFO  ==> Initializing MongoDB...
mongodb 07:06:31.33 INFO  ==> Deploying MongoDB from scratch...
MongoNetworkError: connect ECONNREFUSED 10.42.3.151:27017
mongodb 07:06:32.48 INFO  ==> Creating users...
mongodb 07:06:32.48 INFO  ==> Users created
mongodb 07:06:32.48 INFO  ==> Writing keyfile for replica set authentication...
mongodb 07:06:32.50 INFO  ==> Configuring MongoDB replica set...
mongodb 07:06:32.50 INFO  ==> Stopping MongoDB...
mongodb 07:06:35.60 INFO  ==> Trying to connect to MongoDB server common-mongodb-0.common-mongodb-headless.benchoneiac.svc.cluster.local...
mongodb 07:06:35.61 INFO  ==> Found MongoDB server listening at common-mongodb-0.common-mongodb-headless.benchoneiac.svc.cluster.local:27017 !
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
```

### What do you see instead?

Arbiter restarting!

### Additional information

checked `/opt/bitnami/mongodb/conf/keyfile` in arbiter as well as common-mongodb-0, both are same

**Comment by fmulero** [comment]
Hi @pankaj-dahiya

With the shared information, the easiest answer is "the password was changed". Have to you tried to log into the mongo nodes? In this [link](https://docs.bitnami.com/aws/infrastructure/mongodb/administration/change-reset-password/) you can find how to reset the password.

**Comment by pankaj-dahiya** [comment]
I have check the mongodb root password env variable in both mongo servers are arbiter -- it is same!! Also, compared it with the mognodb-secret !

**Comment by fmulero** [comment]
Can you log into mongo with that password? If not, then the password was changed, maybe other user had the root password and decided to change it. In that case the password will be different than the one stored in mongodb-secret. As I tried to explain, that's the easiest answer for your problem, but maybe not the unique one. If you have any other clue, or any log about what happened when the problem appeared, please share it.

I'd suggest restoring the root password with a new one, store it in a safe place and don't share it. Any application or client should have its own user with the permission needed. Here you have some links with more information about this topic:
* [Modify The Default MongoDB Root Password](https://docs.bitnami.com/aws/infrastructure/mongodb/administration/change-reset-password/) This documentation is for AWS, so you can have some problems with the restarts. Use the values `*.configuration` of the chart to set the content of `mongodb.conf` file.
* [MongoDB Manage Users and Roles](https://www.mongodb.com/docs/manual/tutorial/manage-users-and-roles/)

**Comment by emre141** [comment]
Hi @fmulero ,

Please could you reopen the issue, because I have been same issue, regarding to applied suggested solution (pvc remove) many times but I have still got same issue, 

I tried different mongodb image tag something 6.x, and 5.x tags  but same result, 
I used latest chart version 13.5.0 but same issue, I just using rootpassword and replicasetkey for auth attirbutes and below configuration for replica set members.

By the way my cluster config 2 replica. 1 primary 1 secondary and 1 arbiter,

```
  # mongod.conf
  # for documentation of all options, see:
  #   http://docs.mongodb.org/manual/reference/configuration-options/

  # where and how to store data.
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
    engine: wiredTiger
    wiredTiger:
      engineConfig:
        cacheSizeGB: 5

  # where to write logging data.
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0

  # network interfaces
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    bindIpAll: true
    #bindIp:

  # replica set options
  replication:
    replSetName: prodrs
    enableMajorityReadConcern: true

  # sharding options
  #sharding:
    #clusterRole:

  # process management options
  processManagement:
     fork: false
     pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid

  # set parameter options
  setParameter:
     enableLocalhostAuthBypass: false

  # security options
  security:
    authorization: enabled
    keyFile: /opt/bitnami/mongodb/conf/keyfile
```
