### ISSUE TITLE
Bitnami mongodb chart initial startup without a proxy defined in extra vars takes 20+ minutes to bindAll

### ISSUE THREAD

**Issue by ozialien** [bitnami/charts#10554]
### Name and Version

bitnami/mongodb:latest

### What steps will reproduce the bug?

# Issue

On a private openshift cluster the intial startup configuration will fail to bind to all  IP addresses for 20 minutes and be inaccessible to other nodes.

```
enabled: true
image:
  registry: repo.botw.io/docker-release
  tag: 5.0.8
  pullPolicy: Always
imagePullSecrets:
  - name: xyz
architecture: standalone
useStatefulSet: true
persistence:
  storageClass: file-gold
auth:
  enabled: true
  rootPassword: ""
  usernames:
    - "abc"
  databases:
    - "def"
  passwords: []
resources:
  limits:
    cpu: "1"
    memory: "4Gi"
  requests:
    cpu: 100m
    memory: 128Mi
podSecurityContext:
  enabled: false
containerSecurityContext:
  enabled: false
readinessProbe:
  enabled: true
livenessProbe:
  enabled: true
```

# Workaround

When allowing a proxy on the pod things work as expected immediately on initialization.

```
extraEnvVars:  
  - name: HTTP_PROXY
    value: 
  - name: HTTPS_PROXY
    value: 
  - name: NO_PROXY
    value: ""
```

### Are you using any custom parameters or values?

Used charts from 11.1.5 to the latest with different mongodb app versions.

```
helm upgrade --install --cleanup-on-fail --wait --timeout 5m client helm-release/mongodb \
     --set auth.rootPassword=$MONGO_ROOT_PW \
     --set auth.passwords={$MONGO_DEV_USER_PW} \
     --version "11.1.5" \
     -f values.yaml
```

### What is the expected behavior?

On startup the pod will immediately bind with the configuration (as happens with proxies defined), and I can use a client to connect on any other pod to the client-mongodb service.

```
oc exec -t client-mongodb-0 cat /opt/bitnami/mongodb/conf/mongodb.conf
....
# network interfaces
net:
  port: 27017
  unixDomainSocket:
    enabled: true
    pathPrefix: /opt/bitnami/mongodb/tmp
  ipv6: false
  bindIpAll: true
  #bindIp:
```

### What do you see instead?

For 20+ minutes I see this, and cannot connect to the mongo pod. 22 minutes was the minimum up to 28 minutes maximum.

```
# network interfaces
net:
  port: 27017
  unixDomainSocket:
    enabled: true
    pathPrefix: /opt/bitnami/mongodb/tmp
  ipv6: false
  bindIpAll: false
  bindIp: 127.0.0.1
```
