### ISSUE TITLE
[Keycloak] Ingress TLS not enabled when providing ingress.secrets

### ISSUE THREAD

**Issue by bh-tt** [bitnami/charts#10567]
### Name and Version

bitnami/keycloak:9.2.2

### What steps will reproduce the bug?

Deploy the chart version on a cluster with an ingress controller installed

### Are you using any custom parameters or values?
```yaml
ingress:
  enabled: true
  hostname: keycloak.local
  tls: true
  secrets:
    - name: keycloak.local-tls
       certificate: <valid wildcard certificate for .local>"
       key: "<valid wildcard key for .local>"
  pathType: Prefix
```
### What is the expected behavior?

There should be a TLS array in the ingress spec with the provided secretName and ingress.hostname in it.

### What do you see instead?

There is no TLS array in the ingress spec at all.

### Additional information

If you look at the [template](https://github.com/bitnami/charts/blob/4d67b975c689b2382e694a39ac592516472d4d86/bitnami/keycloak/templates/ingress.yaml#L52) it seems you need `ingress.tls.enabled` to be true, and either a request for a certificate configured or `ingress.tls.selfSigned` true.

The readme says you can configure your own certificates with `ingress.secrets`, however these are not used by the chart. You have to use a self-signed certificate or configure a certificate manager for the cluster.
