### ISSUE TITLE
ingress secret name mismatch in kube-prometheus 8.0.1

### ISSUE THREAD

**Issue by rahulnaikodi** [bitnami/charts#10576]
### Name and Version

bitnami/kube-prometheus 8.0.1

### What steps will reproduce the bug?

1. Set prometheus.ingress.enabled to 'true'.
2. Set prometheus.ingress.tls to 'true'.
3. Set prometheus.ingress.secrets with below definition -
   ```yaml
    secrets:
    - name: abcd
       key: <some private key>
       certificate: <custom certificate>
   ```
4. Deploy kube-promethues helm chart with above parameters.

### Are you using any custom parameters or values?

1. prometheus.ingress.enabled to 'true'
2. prometheus.ingress.tls to 'true'.
3. prometheus.ingress.secrets with below definition -
   ```yaml 
    secrets:
    - name: abcd
       key: <some private key>
       certificate: <custom certificate>
   ```
### What is the expected behavior?

1. To create ingress resource with secret name - abcd as per the custom parameters passed in values.yaml. i.e. prometheus.ingress.secrets.name

### What do you see instead?

1. It creates ingress resource with secret name as per the syntax mentioned below in templates/prometheus/ingress.yaml.
   ```
   secretName: {{ printf "%s-tls" .Values.prometheus.ingress.hostname }}
   ```
2. Why to limit users to have a secret name same as hostname with a suffix -tls in the end?
3. What is the significance of creating a secret (templates/prometheus/tls-secrets.yaml) with a name populated from helm values in prometheus.ingress.secrets as it is not being used anywhere?
5. Also, why not to give an option to users to create their own secret with TLS certificate and private key and use it as 'secretName' in ingress resource because taking certificate and private key as an input in helm is not a secured way?

**Comment by migruiz4** [comment]
Hi @rahulnaikodi, 

The secret `secretName: {{ printf "%s-tls" .Values.prometheus.ingress.hostname }}` is created only when using `ingress.selfSigned`. 
That secret name is used, either when using selfSigned certs (created by Helm) or when the ingress certManager annotation is included.

If you'd like to use your own certificates using `ingress.secrets`, you need to provide the additional tls configuration using the value `extraTls`, for example:

```yaml
prometheus:
  ingress:
    enabled: true
    tls: true
    secrets:
       - name: test1
         key: foo
         certificate: bar
       - name: test2
         key: foo
         certificate: bar
    extraTls: |-
      - hosts:
          - {{ .Values.prometheus.ingress.hostname | quote }}
        secretName: test1
      - hosts:
          - "another-hostname"
        secretName: test2
```
