### ISSUE TITLE
Additional cname-hostname txt record always created

### ISSUE THREAD

**Issue by devops-cafex** [bitnami/charts#10588]
### Name and Version

bitnami/0.12.0-debian-10-r8 release

### What steps will reproduce the bug?

Deploy helm chart 6.5.2 with values
Create ingress with a new hostname
Hostname Creates records in route53
Additional cname- txt record created in addition to normal txt and A record

### Are you using any custom parameters or values?
```yaml
provider: aws

aws:
  zoneType: public
  preferCNAME: false

policy: sync

rbac:
  create: true

serviceAccount:
  create: false
  name: external-dns
```
### What is the expected behavior?

In chart external-dns-6.4.5 the `txt `and the `a` record are created as expected but in all versions since then without changing any values an additional `cname-` `txt` record is created in route53

### What do you see instead?

Additional cname- txt record created in route53

### Additional information

This causes issues for deleting existing records as they don't have the expected `cname-` `txt` record present only the `txt` and `a` which causes external dns to fail to update records
