### ISSUE TITLE
copy the keystore/truststore method from keycloak to jenkins for same reason (to connect with ldaps)

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#10602]
### Name and Version

bitnami/jenkins : latest

### What is the problem this feature will solve?

In order to connect to LDAPS onprem certificates must be added to the local keystore/truststore.

### What is the feature you are proposing to solve the problem?

The keycloak helm chart has a way to do this, propose duplicating the technique for the jenkins helm chart.
```yaml
  # to specify the ad ca public certificate in order to access ldaps
  auth:
    tls:
      enabled: true
      existingSecret: keycloak-certs
      keystorePassword: changeit
      truststorePassword: changeit
```

### What alternatives have you considered?

If I can find a way to configure OIDC instead of LDAPS that would work as I could then use azure identity server or keycloak.
