### ISSUE TITLE
Redis kind:deployment incorrect REDIS_MASTER_HOST in replicas

### ISSUE THREAD

**Issue by ajromito** [bitnami/charts#10621]
### Name and Version

bitnami/redis latest

### What steps will reproduce the bug?

1) Install chart
```
auth:
  enabled: true
  password: 123
master:
  kind: Deployment
  persistence:
    enabled: false
replica:
  persistence:
    enabled: false
  replicaCount: 2
```

### What is the expected behavior?

Expected behavior is that `REDIS_MASTER_HOST` would be adjusted when kind: Deployment

https://github.com/bitnami/charts/blob/223d9a97749144306895fc49d13b25fcf9f4fce4/bitnami/redis/templates/replicas/statefulset.yaml#L129

### What do you see instead?

`REDIS_MASTER_HOST` includes 'master-0' in the value, which causes replicase to fail to find the master
