### ISSUE TITLE
Elasticsearch ingress: Invalid value: "restAPI"

### ISSUE THREAD

**Issue by vaggeliskls** [bitnami/charts#10657]
### Name and Version

bitnami/elasticsearch 18.2.9

### What steps will reproduce the bug?

1. Using AWS k8s cluster
2. Config Used
Values.yaml

```yaml
global:
  kibanaEnabled: true
sysctlImage:
  enabled: true
ingress:
  enabled: true
master:
  replicaCount: 1
data: 
  replicaCount: 1
coordinating: 
  replicaCount: 1
ingest: 
  replicaCount: 1
security:
  enabled: true
  elasticPassword: "rvHsigEI6iVmKfRE"
  tls:
    autoGenerated: true
    restEncryption: true
kibana:
  extraConfiguration:
    xpack.encryptedSavedObjects.encryptionKey: fd0d21352ecf9d6ce77b758033bafafb
  elasticsearch:
    security:
      auth:
        enabled: true
        kibanaPassword: rvHsigEI6iVmKfRE
        createSystemUser: true
        elasticsearchPasswordSecret: elastic-secret
      tls:
        enabled: true
        existingSecret: elasticsearch-master-crt
        usePemCerts: true
```

3. Run
`helm upgrade --install my-elasticsearch bitnami/elasticsearch --version 18.2.9 -f values.yaml`

4. Error
`Error: UPGRADE FAILED: failed to create resource: Ingress.extensions "elasticsearch" is invalid: spec.rules[0].http.paths[0].backend.service.port.name: Invalid value: "restAPI": must contain only alpha-numeric characters (a-z, 0-9), and hyphens (-)`

### What is the expected behavior?

The creation of elastic search ingress

### What do you see instead?

`Error: UPGRADE FAILED: failed to create resource: Ingress.extensions "elasticsearch" is invalid: spec.rules[0].http.paths[0].backend.service.port.name: Invalid value: "restAPI": must contain only alpha-numeric characters (a-z, 0-9), and hyphens (-)`
