### ISSUE TITLE
[Elasticsearch] Ingress renders wrong name

### ISSUE THREAD

**Issue by Moep90** [bitnami/charts#10650]
### Name and Version

bitnami/elasticsearch 18.2.6

### What steps will reproduce the bug?

1. Render elasticsearch helmchart with ingress
2. kubectl apply -f elasticsearch.yml

### What is the expected behavior?

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
[...]
  labels:
    app.kubernetes.io/component: elasticsearch
    app.kubernetes.io/instance: elasticsearch
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elasticsearch
    helm.sh/chart: elasticsearch-18.2.6
  name: elasticsearch
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
    - host: logz.example.com
      http:
        paths:
          - backend:
              service:
                name: elasticsearch
                port:
                  name: tcp-rest-api <------
            path: /
            pathType: ImplementationSpecific
```

### What do you see instead?

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
[...]
  labels:
    app.kubernetes.io/component: elasticsearch
    app.kubernetes.io/instance: elasticsearch
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elasticsearch
    helm.sh/chart: elasticsearch-18.2.6
  name: elasticsearch
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
    - host: logz.example.com
      http:
        paths:
          - backend:
              service:
                name: elasticsearch
                port:
                  name: restAPI <------ should be "tcp-rest-api"
            path: /
            pathType: ImplementationSpecific
```

### Additional information

https://github.com/bitnami/charts/blob/5b22c6677afa2e3c60eeb4150ff04440dfd1c292/bitnami/elasticsearch/templates/ingress.yaml#L36

https://github.com/bitnami/charts/blob/5b22c6677afa2e3c60eeb4150ff04440dfd1c292/bitnami/elasticsearch/templates/ingress.yaml#L49
