### ISSUE TITLE
[thanos] add configmap-reload to thanos ruler

### ISSUE THREAD

**Issue by davidy718** [bitnami/charts#10744]
### Name and Version

bitnami/thanos 10.5.2

### What is the problem this feature will solve?

when updating the configmap for the rules you need to manually reload the pod

### What is the feature you are proposing to solve the problem?

add a container to reload thanos ruler 
[https://github.com/jimmidyson/configmap-reload](https://github.com/jimmidyson/configmap-reload)

### What alternatives have you considered?

added a value to be able to enable/disable it
something like
```
{{- if .Values.ruler.configmapreload}} 
- name: configmap-reload
  image: jimmidyson/configmap-reload:latest
  args:
    - --volume-dir=/conf/rules/
    - --webhook-url=http://localhost:10902/-/reload
  volumeMounts:
    - name: ruler-config
      mountPath: /conf/rules
```
