### ISSUE TITLE
Thanos HPA is not compatible with k8s 1.22 and autoscaling/v2beta2

### ISSUE THREAD

**Issue by aghassabian** [bitnami/charts#10765]
### Name and Version

bitnami/thanos 10.5.2

### What steps will reproduce the bug?

Merging https://github.com/bitnami/charts/pull/10331/commits/57cba5fb06e2920ed994cdabb26ff1768570120b seems to break the HPA compatibility with k8s 1.22

GKE server version:
```
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8-gke.2200", GitCommit:"81a23326454f32475752ab4ef1ebdd164a6ba96d", GitTreeState:"clean", BuildDate:"2022-04-13T09:37:04Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
```

Enabled autoscaling API versions:
```
$ kubectl api-versions | grep autoscaling
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
internal.autoscaling.gke.io/v1alpha1
```

Deploying thanos chart returns: 
```
W0614 20:49:53.220623     118 warnings.go:70] autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.25+; use autoscaling/v2beta2 HorizontalPodAutoscaler
```

If we manage to deploy with `v2beta2` the following error would raise:
```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): unknown field "targetAverageUtilization" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): missing required field "target" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[1].resource): unknown field "targetAverageUtilization" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[1].resource): missing required field "target" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource]
```

According https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2beta2/, the commit that was mentioned above did not consider the difference between v2beta1 and v2beta2 in `metrics` definition and divide the HPA template to versions before and after 1.23 only: https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/query/hpa.yaml#L28-L46. In fact, supporting custom metrics has been added from v2beta2 and seems the syntax is same as autoscaling/v2

### Are you using any custom parameters or values?

No custom values:
```yaml
autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPU: 60
    targetMemory: 60
```

### What is the expected behavior?

```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
....
```

### What do you see instead?

```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): unknown field "targetAverageUtilization" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): missing required field "target" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[1].resource): unknown field "targetAverageUtilization" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[1].resource): missing required field "target" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource]
```
