### ISSUE TITLE
[bitnami/kafka] Add ability to configure volume for non persisted storage 

### ISSUE THREAD

**Issue by ArtemTrofimushkin** [bitnami/charts#10773]
### Name and Version

bitnami/kafka 17.1.0

### What is the problem this feature will solve?

In the current version, if persistence is disabled, e.g. in values.yaml:

```yaml
persistense:
  enabled: false
```

for data dir will be used volume of type `emptyDir` (in statefulset.yaml):

```yaml
{{- if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
{{- else if .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ printf "%s" (tpl .Values.persistence.existingClaim .) }}
{{- end }}
``` 

However Kubernetes support other types of ephemeral storage: [generic ephemeral volumes](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes), [csi ephemeral volumes](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#csi-ephemeral-volumes). 
It will be useful to add ability to define volume template for non persistent storage.

### What is the feature you are proposing to solve the problem?

Add volume template spec in values.yaml and use it in statefulset.yaml. For example, in values.yaml: 

```yaml
persistence:
  nonPersistentVolumeTemplate: {}
```

In statefulset.yaml:

```yaml
{{- if not .Values.persistence.enabled }}
        - name: data
  {{- if .Values.persistence.nonPersistentVolumeTemplate -}}
          {{- include "common.tplvalues.render" (dict "value" .Values.persistence.nonPersistentVolumeTemplate "context" $) | nindent 10 }}
  {{- else }}
          emptyDir: {}
  {{- end }}
{{- else if .Values.persistence.existingClaim }}
```

With this option, the data volume type can be changed with the following custom values-overrides.yaml:

```yaml
persistense:
  nonPersistentVolumeTemplate:
    ephemeral:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi
          storageClassName: azurefile-csi
```

A similar option can be added for log dir. 
If desired, I can attach a pull request with all changes.

### What alternatives have you considered?

Current workaround is to add extraVolume/extraVolumeMounts and override `KAFKA_VOLUME_DIR` env variable. e.g:

```yaml
extraVolumes:
  - ephemeral:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi
          storageClassName: azurefile-csi
    name: data-ephemeral
extraVolumeMounts:
  - mountPath: "/bitnami/kafka/state"
    name: data-ephemeral
extraEnvVars:
  - name: KAFKA_VOLUME_DIR
    value: "/bitnami/kafka/state"
```

But this can leads to helm upgrade [issue](https://github.com/helm/helm/issues/1065) , because one environment variable sets multiple times

**Comment by ArtemTrofimushkin** [comment]
Hi @javsalgar !
There is already exists field `persistence.mountPath` in values.yaml. 
https://github.com/bitnami/charts/blob/master/bitnami/kafka/values.yaml#L922

This field used for `KAFKA_VOLUME_DIR` env variable value and for `mountPath` of data volumeMount.
https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/statefulset.yaml#L304
https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/statefulset.yaml#L119

But this field will not help in any way in fixing the issue, because data volume of type emptyDir also will be mounted to `persistence.mountPath`.

For example, following values.yaml:

```yaml
persistence:
    enabled: false
    mountPath: "/bitnami/kafka/state"

extraVolumeMounts:
  - mountPath: "/bitnami/kafka/state"
    name: data-ephemeral

extraVolumes:
  - ephemeral:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi
          storageClassName: azurefile-csi
    name: data-ephemeral
```

leads to following statefulset.yaml (some fields omitted for brevity):

```
apiVersion: apps/v1
kind: StatefulSet
spec:
  template:
    spec:
    ...
      containers:
        - image: docker.io/bitnami/kafka:3.2.0-debian-10-r4
          env:
          ...
          - name: KAFKA_VOLUME_DIR
            value: /bitnami/kafka/state
       ...
          volumeMounts:
            - mountPath: /bitnami/kafka/state
              name: data
            - mountPath: /opt/bitnami/kafka/logs
              name: logs
            - mountPath: /bitnami/kafka/state/config/server.properties
              name: kafka-config
              subPath: server.properties
            - mountPath: /scripts/setup.sh
              name: scripts
              subPath: setup.sh
            - mountPath: /bitnami/kafka/state
              name: data-ephemeral
       ...
      volumes:
        - configMap:
            name: kafka-configuration
          name: kafka-config
        - configMap:
            defaultMode: 493
            name: kafka-scripts
          name: scripts
        - configMap:
            name: kafka-jmx-configuration
          name: jmx-config
        - ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 8Gi
                storageClassName: azurefile-csi
          name: data-ephemeral
        - emptyDir: {}
          name: data
        - emptyDir: {}
          name: logs
```

With two volumes (data and data-ephemeral) that mounted to single mountPath and last mount will be ignored, when statefulset.yaml applied to k8s cluster
