### ISSUE TITLE
Wrong customStartupProbe config in all thanos components

### ISSUE THREAD

**Issue by nguyenhoaibao** [bitnami/charts#10778]
### Name and Version

bitnami/thanos

### What steps will reproduce the bug?

Create a values file:
```yaml
bucketweb:
  enabled: true
  startupProbe:
    enabled: false
  customStartupProbe:
    httpGet:
      path: /-/ready
      port: http
      httpHeaders:
      - name: Authorization
        value: Basic <header>

compactor:
  enabled: true
  startupProbe:
    enabled: false
  customStartupProbe:
    httpGet:
      path: /-/ready
      port: http
      httpHeaders:
      - name: Authorization
        value: Basic <header>

query:
  enabled: true
  startupProbe:
    enabled: false
  customStartupProbe:
    httpGet:
      path: /-/ready
      port: http
      httpHeaders:
      - name: Authorization
        value: Basic <header>

queryFrontend:
  enabled: true
  startupProbe:
    enabled: false
  customStartupProbe:
    httpGet:
      path: /-/ready
      port: http
      httpHeaders:
      - name: Authorization
        value: Basic <header>

receive:
  enabled: true
  startupProbe:
    enabled: false
  customStartupProbe:
    httpGet:
      path: /-/ready
      port: http
      httpHeaders:
      - name: Authorization
        value: Basic <header>

storegateway:
  enabled: true
  startupProbe:
    enabled: false
  customStartupProbe:
    httpGet:
      path: /-/ready
      port: http
      httpHeaders:
      - name: Authorization
        value: Basic <header>
```

### Are you using any custom parameters or values?

See values file above.

### What is the expected behavior?

`customStartupProbe` renders successfully.

### What do you see instead?

`customStartupProbe` doesn't render successfully.

### Additional information

This line https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/receive/statefulset.yaml#L205 should be:
```
{{- else if .Values.receive.customStartupProbe }}
```

Same for other components.
