### ISSUE TITLE
prometheus CRD missing subresources.status field

### ISSUE THREAD

**Issue by omriarieli** [bitnami/charts#10776]
### Name and Version

bitnami/kube-prometheus 8.0.6

### What steps will reproduce the bug?

1. install the chart
2. check operator logs

### Are you using any custom parameters or values?

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    meta.helm.sh/release-name: op
    meta.helm.sh/release-namespace: monitoring
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: op
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus
    helm.sh/chart: kube-prometheus-8.0.6
  name: operator-prometheus
  namespace: monitoring
spec:
  additionalScrapeConfigs:
    key: scrape-jobs.yaml
    name: additional-scrape-jobs-operator-prometheus
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: prometheus
              app.kubernetes.io/instance: op
              app.kubernetes.io/name: kube-prometheus
          namespaces:
          - monitoring
          topologyKey: kubernetes.io/hostname
        weight: 1
  alerting:
    alertmanagers:
    - name: operator-alertmanager
      namespace: monitoring
      pathPrefix: /
      port: http
  containers:
  - args:
    - sidecar
    - --prometheus.url=http://localhost:9090
    - --grpc-address=0.0.0.0:10901
    - --http-address=0.0.0.0:10902
    - --tsdb.path=/prometheus/
    - --objstore.config=$(OBJSTORE_CONFIG)
    env:
    - name: OBJSTORE_CONFIG
      valueFrom:
        secretKeyRef:
          key: thanos.yaml
          name: thanos-objstore-config
    image: docker.io/bitnami/thanos:0.26.0-scratch-r4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 120
      httpGet:
        path: /-/healthy
        port: http
        scheme: HTTP
      initialDelaySeconds: 0
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    name: thanos-sidecar
    ports:
    - containerPort: 10901
      name: grpc
      protocol: TCP
    - containerPort: 10902
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 120
      httpGet:
        path: /-/ready
        port: http
        scheme: HTTP
      initialDelaySeconds: 0
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: true
    volumeMounts:
    - mountPath: /prometheus
      name: prometheus-operator-prometheus-db
      subPath: prometheus-db
  - livenessProbe:
      failureThreshold: 10
      httpGet:
        path: /-/healthy
        port: web
        scheme: HTTP
      initialDelaySeconds: 0
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 3
    name: prometheus
    readinessProbe:
      failureThreshold: 10
      httpGet:
        path: /-/ready
        port: web
        scheme: HTTP
      initialDelaySeconds: 0
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 3
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: true
    startupProbe:
      failureThreshold: 60
      httpGet:
        path: /-/ready
        port: web
        scheme: HTTP
      initialDelaySeconds: 0
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 3
  - livenessProbe:
      failureThreshold: 6
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: reloader-web
      timeoutSeconds: 5
    name: config-reloader
    readinessProbe:
      failureThreshold: 6
      initialDelaySeconds: 15
      periodSeconds: 20
      successThreshold: 1
      tcpSocket:
        port: reloader-web
      timeoutSeconds: 5
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: true
  disableCompaction: true
  enableAdminAPI: false
  externalLabels:
    receive_cluster: flow-prod-k8s
    receive_env: prod-flow
    receive_region: europe-west1
    receive_replica: $(SHARD)
  externalUrl: http://operator-prometheus.monitoring:9090/
  image: docker.io/bitnami/prometheus:2.36.1-debian-11-r0
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  nodeSelector:
    prometheus: "true"
  paused: false
  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: op
      app.kubernetes.io/name: kube-prometheus
  portName: web
  replicas: 1
  retention: 7d
  routePrefix: /
  securityContext:
    fsGroup: 1001
    runAsUser: 1001
  serviceAccountName: operator-prometheus
  shards: 2
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 64Gi
        storageClassName: prometheus
  tolerations:
  - effect: NoSchedule
    key: prometheus
    operator: Equal
    value: "true"
  walCompression: true
```

### What do you see instead?

operator logs show
```
level=error ts=2022-06-15T21:45:55.515756804Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"monitoring/operator-prometheus\" failed: failed to update status subresource: prometheuses.monitoring.coreos.com \"operator-prometheus\" not found"
```
every 15 minutes

I don't know if it is related but I can't see the Prometheus pods `container_memory_working_set_bytes`

### Additional information

see https://github.com/prometheus-operator/prometheus-operator/issues/4823
