### ISSUE TITLE
Chart cant be deployed with LoadDefinition Enabeld

### ISSUE THREAD

**Issue by Dragonil** [bitnami/charts#10783]
### Name and Version

> bitnami/rabbitmq:8.31.6

### What steps will reproduce the bug?

I tried to deploy the latest helm chart of Jfrog xray, which depends on the rabbitmq chart 8.31.6 (bitnami/rabbitmq:3.8.14-debian-10-r32).

When I try to deploy rabbitmq with an external Loaddefinition I get in the Container the following error:
```shell
[38;5;6mrabbitmq [38;5;5m08:22:12.97 [0m[38;5;1mERROR[0m ==> The RABBITMQ_LOAD_DEFINITIONS and RABBITMQ_SECURE_PASSWORD environment variables cannot be enabled at once.
```

Since the docker [container documentation](https://hub.docker.com/r/bitnami/rabbitmq) mentioned that it's not possible to use RABBITMQ_SECURE_PASSWORD and RABBITMQ_LOAD_DEFINITIONS at the same time.

But in the mentioned chart, and from the looks of it in the current master, I could not find any option to disable RABBITMQ_SECURE_PASSWORD because it's set to yes within the Template.
```yaml
            - name: RABBITMQ_LOAD_DEFINITIONS
              value: {{ ternary "yes" "no" .Values.loadDefinition.enabled | quote }}
            - name: RABBITMQ_DEFINITIONS_FILE
              value: {{ .Values.loadDefinition.file | quote }}
            - name: RABBITMQ_SECURE_PASSWORD
              value: "yes"
```
https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/templates/statefulset.yaml (208-213)

To reproduce the bug you need to deploy the chart with LoadDefinition enabled.

### Are you using any custom parameters or values?

values from xray chart
```yaml
rabbitmq:
  enabled: true
  replicaCount: 1
  rbac:
    create: true
  image:
    registry: releases-docker.jfrog.io
    repository: bitnami/rabbitmq
    tag: 3.8.14-debian-10-r32
  auth:
    username: guest
    password: ""
    erlangCookie: XRAYRABBITMQCLUSTER
  maxAvailableSchedulers: null
  onlineSchedulers: null
  extraEnvVars:
    - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
      value: "+S 2:2 +sbwt none +sbwtdcpu none +sbwtdio none"
  service:
    port: 5672
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 20Gi
  extraSecretsPrependReleaseName: true
  extraSecrets:
    load-definition:
      load_definition.json: |
        {
          "vhosts": [
            {
              "name": "/"
            }
          ],
          "policies": [
            {
              "name": "ha-all",
              "apply-to": "all",
              "pattern": ".*",
              "vhost": "/",
              "definition": {
                "ha-mode": "all",
                "ha-sync-mode": "automatic",
              }
            }
          ]
        }
  loadDefinition:
    enabled: true
    existingSecret: '{{ .Release.Name }}-load-definition'
  extraConfiguration: |
    management.load_definitions = /app/load_definition.json
```

### What is the expected behavior?

Since it is not possible to use RABBITMQ_SECURE_PASSWORD and RABBITMQ_LOAD_DEFINITIONS at once, I would expect that there is an option to set the parameter to RABBITMQ_SECURE_PASSWORD false with a flag in the values.yaml or when loadDefinition.enabled: true

i.e.
```yaml
            - name: RABBITMQ_LOAD_DEFINITIONS
              value: {{ ternary "yes" "no" .Values.loadDefinition.enabled | quote }}
            - name: RABBITMQ_DEFINITIONS_FILE
              value: {{ .Values.loadDefinition.file | quote }}
            - name: RABBITMQ_SECURE_PASSWORD
              value: {{ ternary "no" "yes" .Values.loadDefinition.enabled | quote }}
```

### What do you see instead?

I haven't found any option in the chart to disable the RABBITMQ_SECURE_PASSWORD so that I can use an external LoadDefinition

### Additional information

When setting any of those parameters in the statefulset to "no", I'm able to deploy rabbitmq.

Before we used the chart version 8.11.4 where the RABBITMQ_SECURE_PASSWORD didn't exist and there were no issues.

I couldn't find any explanation of why those parameters cant be used together and what the purpose of RABBITMQ_SECURE_PASSWORD is.

**Edit:** One workaround I could find was to add an additional env parameter for RABBITMQ_SECURE_PASSWORD in the values.yaml which sets the value to "no"
```yaml
extraEnvVars:
      - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
        value: "+S 2:2 +sbwt none +sbwtdcpu none +sbwtdio none"
      - name: RABBITMQ_SECURE_PASSWORD
        value: "no"
```
