### ISSUE TITLE
Wrong startupProbe config in thanos query-frontend deployment

### ISSUE THREAD

**Issue by nguyenhoaibao** [bitnami/charts#10784]
### Name and Version

bitnami/thanos

### What steps will reproduce the bug?

Create a values file:
```
queryFrontend:
  enabled: true
  startupProbe:
    enabled: false
  customStartupProbe:
    httpGet:
      path: /-/ready
      port: http
      httpHeaders:
      - name: Authorization
        value: Basic <header>
```

### Are you using any custom parameters or values?

See values file above.

### What is the expected behavior?

`customStartupProbe` of query-frontend deployment renders successfully.

### What do you see instead?

`customStartupProbe` doesn't render successfully.

### Additional information

This line https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/query-frontend/deployment.yaml#L149 should be:
```
{{- else if .Values.receive.customStartupProbe }}
```
