### ISSUE TITLE
KeyCloak chart 9.2.11 references old config-cli image which does not contain KeyCloak 18.0.1

### ISSUE THREAD

**Issue by markusheiden** [bitnami/charts#10796]
### Name and Version

bitnami/keycloak:9.2.11

### What steps will reproduce the bug?

1. Use config-cli job

### Are you using any custom parameters or values?

No

### What is the expected behavior?

The config-cli job runs successfully.

### What do you see instead?

`Error: Unable to access jarfile /opt/bitnami/keycloak-config-cli/keycloak-config-cli-18.0.1.jar`

### Additional information

The current chart references a config-cli image that does not contain KeyCloak 18.0.1. Because the chart forces the config-cli job to use the app version of the chart (which is 18.0.1) the config-cli job fails.

**Comment by markusheiden** [comment]
Workaround:
```yaml
keycloakConfigCli:
  command:
    - java
    - -jar
    - /opt/bitnami/keycloak-config-cli/keycloak-config-cli-18.0.0.jar
```
