### ISSUE TITLE
Can't set runAsUser to large int, turns into scientific notation

### ISSUE THREAD

**Issue by JonasJR** [bitnami/charts#10798]
### Name and Version

bitnami/harbor

### What steps will reproduce the bug?

We need to run all containers with a specific UID since only this specific user has access to writing on disk. I'm providing my own values.yaml and set all the runAsUser and fsGroup to the correct user on all places where it is possible. Example:
```
core:
  containerSecurityContext:
    runAsUser: 1234567890
  podSecurityContext:
    fsGroup: 1234567890
```
Since this UID is a long number it gets converted to scientific notation and does not work in the container. I tried also to make it a string:
```
    runAsUser: "1234567890"
```
But i get error that it:
```
got "string", expected "integer"
```

### What is the expected behavior?

I would like the int to not get converted to scientific notation or to be able to pass in the string instead

### What do you see instead?

Errors as explained above
