### ISSUE TITLE
elasticsearch kibana sub chart constantly stuck with the old replicaset 

### ISSUE THREAD

**Issue by kvokka** [bitnami/charts#10791]
### Name and Version

bitnami/elasticsearch:18.2.13

### What steps will reproduce the bug?

It happens in the rollout process

### Are you using any custom parameters or values?

```yaml
elasticsearch:
  kibana:
    image:
      tag: 8.2.2-debian-11-r1
    ingress:
      enabled: true
      ingressClassName: rp-nginx
      hostname: "logs.my-awesome-domain.com"
      tls: true
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-staging
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/auth-type: basic
        # For now we are sharing the same secret with the "old" kibana
        # The chart allows us to use kibana auth but for now we are still use auth from nginx
        nginx.ingress.kubernetes.io/auth-secret: logging-kibana-credentials
        nginx.ingress.kubernetes.io/auth-realm: "Kibana - Authentication Required"
    metrics:
      enabled: true
```

### What is the expected behavior?

no error

### What do you see instead?

the new replicaset was created, but it refuses to replace the old one

### Additional information

to fix it after each chart deployment I have to manually run something like this:

```console
$ k version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:57:43Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11-gke.1100", GitCommit:"20da4c21b3a6b1a56ff6ad5ecb7dee013aaf1b83", GitTreeState:"clean", BuildDate:"2022-04-01T09:40:07Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
$ k get -n logging-system replicasets.apps
NAME                                                   DESIRED   CURRENT   READY   AGE
elastic-kibana-55556fbd89                              1         1         1       8d
elastic-kibana-5977979c7d                              1         1         0       16m
elastic-prometheus-elasticsearch-exporter-6c98996956   2         2         2       13d
$ k delete -n logging-system replicasets.apps elastic-kibana-55556fbd89
replicaset.apps "elastic-kibana-55556fbd89" deleted
```

and then it works as it should. This is happening constantly only with this chart

**Comment by carrodher** [comment]
In order to reproduce the issue on our side, could you share the whole process you're following? From the first installation to how the upgrade is executed

**Comment by kvokka** [comment]
The installation command:

```
$ helm upgrade --create-namespace --namespace $NAMESPACE --install -f $VALUES_FILE $RELEASE_NAME $BASE_PATH
```

will leave a whole values file then (cut only some resources sections for some air):

```yaml
common_elastic_config: &common_elastic_config
  enabled: true
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: soft
    key: soft-dedicated
    values: ["default-namespace"]
  serviceAccount:
    create: true

elasticsearch:
  global:
    storageClass: logging
    kibanaEnabled: true
  image:
    tag: 8.2.2-debian-11-r1

  volumePermissions:
    enabled: true

  extraConfig:

    #X-PACK config
    xpack.license.self_generated.type: basic
    xpack.graph.enabled: false
    xpack.security.enabled: false
    xpack.watcher.enabled: false

  master:
    <<: *common_elastic_config
    priorityClassName: logging-elastic-master
    persistence:
      size: 5Gi
    heapSize: 512m

  data:
    <<: *common_elastic_config
    priorityClassName: logging-elastic-default
    persistence:
      size: 30Gi

  ingest:
    <<: *common_elastic_config
    priorityClassName: logging-elastic-default
    heapSize: 512m

  coordinating:
    priorityClassName: logging-elastic-default

  kibana:
    image:
      tag: 8.2.2-debian-11-r1
    extraConfiguration:
      server.publicBaseUrl: "https://log.my-awesome-domain.com"
      xpack.monitoring.ui.container.elasticsearch.enabled: true
      xpack.reporting.csv.maxSizeBytes: 103809024
    ingress:
      enabled: true
      ingressClassName: rp-nginx
      hostname: "log.my-awesome-domain.com"
      tls: true
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-staging
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: logging-kibana-credentials
        nginx.ingress.kubernetes.io/auth-realm: "Kibana - Authentication Required"
    metrics:
      enabled: true
```
