### ISSUE TITLE
MongoDB commonAnnotations doesn't work with externalAccess

### ISSUE THREAD

**Issue by carstensh** [bitnami/charts#10793]
### Name and Version

bitnami/mongodb:12.1.19

### What steps will reproduce the bug?

Using commonAnnotations in the helm chart doesn't work when externalAccess is enabled.

In my values.yaml file:
```
commonAnnotations:
  some: "annotation"

externalAccess:
  ## @param externalAccess.enabled Enable Kubernetes external cluster access to MongoDB(&reg;) nodes (only for 
  replicaset architecture)
  ##
  enabled: true
```

When I try to helm install I get this error:
```
helm template mongodb -n sophie-mongodb -f values.yaml . > helm.yaml        
Error: template: mongodb/charts/mongodb/templates/replicaset/external-access-svc.yaml:26:64: executing "mongodb/charts/mongodb/templates/replicaset/external-access-svc.yaml" at <.Values.commonAnnotations>: can't evaluate field Values in type int
```

I think this is because in the templates/replicaset/external-access-svc.yaml file on line 26 it is not using $root.Values.commonAnnotations

```
  {{- if or $root.Values.externalAccess.service.annotations $root.Values.commonAnnotations }}
  annotations:
    {{- if $root.Values.externalAccess.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" $root.Values.externalAccess.service.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if $root.Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
```

Many Thanks!

### What do you see instead?

```
helm template mongodb -n sophie-mongodb -f values.yaml . > helm.yaml        
Error: template: mongodb/charts/mongodb/templates/replicaset/external-access-svc.yaml:26:64: executing "mongodb/charts/mongodb/templates/replicaset/external-access-svc.yaml" at <.Values.commonAnnotations>: can't evaluate field Values in type int
```
