### ISSUE TITLE
[Redis] Sentinel cannot use servicetype NodePort

### ISSUE THREAD

**Issue by tomikonio** [bitnami/charts#10808]
### Name and Version

bitnami/redis:16.12.2

### What steps will reproduce the bug?

Install the redis helm chart

### Are you using any custom parameters or values?

```
helm install redis bitnami/redis \
--set sentinel.enabled=true \
--set sentinel.service.type=NodePort
```

### What is the expected behavior?

To have the Redis pods exposed via nodeport (1 for Redis and 1 for Sentinel)

### What do you see instead?

No statefulset is being created

### Additional information

What we ultimately want is to use predefined nodeports - i.e. to have the Redis exposed on **one** nodeport and the sentinel on another.

When used with
```
helm install redis bitnami/redis \
--set sentinel.enabled=true \
--set sentinel.service.type=NodePort \
--set sentinel.service.nodePorts.redis=30007 \
--set sentinel.service.nodePorts.sentinel=30009
```
It fails with:
```
Error: Service "redis-node-2" is invalid: spec.ports[1].nodePort: Invalid value: 30010: provided port is already allocated
```

And indeed it seems that it tries to create a service per each redis node:
```
NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                          AGE
redis-headless   ClusterIP   None            <none>        6379/TCP,26379/TCP                                               19s
redis-node-0     NodePort    10.43.211.241   <none>        30010:30010/TCP,30008:30008/TCP,26379:30832/TCP,6379:31210/TCP   19s
redis-node-1     NodePort    10.43.140.121   <none>        30011:30011/TCP,30009:30009/TCP,26379:32376/TCP,6379:30538/TCP   19s
```

When used with
```
helm install redis bitnami/redis \
--set sentinel.enabled=true \
--set sentinel.service.type=LoadBalancer \
--set sentinel.service.nodePorts.redis=30007 \
--set sentinel.service.nodePorts.sentinel=30009
```
We get this service:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: node
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-16.12.2
  name: redis
  namespace: redis
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: tcp-redis
      nodePort: 30007
      port: 30007
      targetPort: 6379
    - name: tcp-sentinel
      nodePort: 30009
      port: 30009
      targetPort: 26379
  selector:
    app.kubernetes.io/component: node
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
  sessionAffinity: None
  type: LoadBalancer
```
The internal cluster port is set to 30007 and 30009 in addition to the nodeport.

So, to sum it up:
1. When using servicetype Nodeport - no redis pods are being created.
2. When using servicetype Nodeport in combination with specific nodeports for redis and sentinel  - the installation fails due to trying to create a service for each redis node - workaround is to have a bigger margin for the predefined nodeports for redis and sentinal (i.e. 30007 and 30017).
3. When using servicetype LoadBalancer in combination with specific nodeports - installation is successful and a single service is exposed, but its in-cluster port is set to the same value as the nodeport

Update:
When querying the sentinel for the master in either configuration - it returns the in-cluster headless-service DNS name and port instead of the DNS/IP + nodeport of the machine the master is on, so you cannot connect from outside the cluster

**Comment by javsalgar** [comment]
Hi,

It seems that it in the case of nodeports, you need to create one service per node. Would you like to be able to set a list of nodeports for each service created, or would you like to have only one service for the whole redis installation?

**Comment by tomikonio** [comment]
Hi,
Yes a list of nodeports would be good.
It seems that the sentinal returns the internal  address instead of the IP of the node the master is on, so a service outside of the cluster cannot connect.

Using this configuration:
```
master:
  service:
    externalTrafficPolicy: Local

replica:
  service:
    externalTrafficPolicy: Local	

sentinel:
  enabled: true
  service:
    externalTrafficPolicy: Local
    type: "NodePort"
    nodePorts:
      redis: 30027
      sentinel: 30056
```
