### ISSUE TITLE
Grafana loki retention of logs is only 1h

### ISSUE THREAD

**Issue by puppeteer701** [bitnami/charts#10824]
### Name and Version

bitnami/grafana-loki

### What steps will reproduce the bug?

My Config
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana-loki
      version: "2.1.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    tableManager:
      enabled: true
```

### Are you using any custom parameters or values?

Yes, I enabled tableManager.

### What is the expected behavior?

To still be able to query for logs of my app longer than 1h. I used the timerange of 6 hours and I do not see older logs than 1h.

### What do you see instead?

I can only query for logs of my app now-1h, other queries return null result.results
