### ISSUE TITLE
[bitnami/chart-rabbitmq]  about rabbitmq  load_definition.json

### ISSUE THREAD

**Issue by Amazingzzl** [bitnami/charts#10837]
### Name and Version

bitnaimi/rabbitmq 10.1.7

### What steps will reproduce the bug?

The load_definition.json file is configured, but it will not take effect when the pod is started. You need to manually execute rabbitmqctl import_definitions /app/load_definition.json in the pod. Also, how to automatically join the cluster when adding a new node

Thanks for you help

### Are you using any custom parameters or values?

```yaml
clustering:
  enabled: true
  addressType: hostname
  rebalance: true
  forceBoot: true
  partitionHandling: autoheal


loadDefinition:
  enabled: true
  file: "/app/load_definition.json"


extraConfiguration: |-
  existingSecret: load-definition
  load_definitions = /app/load_definition.json


extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "vhosts": [
          {
            "name": "/"
          }
        ],
        "policies": [
          {
            "name": "ha-all",
            "pattern": "^",
            "vhost": "/",
            "definition": {
              "ha-mode": "all",
              "ha-sync-mode": "automatic"
            }
          }
        ]
        "users":[
            {
                "name": "admin",
                "password": "xxxxxx",
                "tags": "administrator"
            }
        ]
      }


extraSecretsPrependReleaseName: false
```

### What is the expected behavior?

2022-06-21 14:56:22.009135+00:00 [warning] <0.685.0> LDAP plugin loaded, but rabbit_auth_backend_ldap is not in the list of auth_backends. LDAP auth will not work.
36
2022-06-21 14:56:22.009904+00:00 [info] <0.691.0> Peer discovery: enabling node cleanup (will only log warnings). Check interval: 10 seconds.
35
2022-06-21 14:56:22.013215+00:00 [info] <0.699.0> Prometheus metrics: HTTP (non-TLS) listener started on port 15692
34
2022-06-21 14:56:22.014181+00:00 [info] <0.577.0> Applying definitions from file at '/app/load_definition.json'
33
2022-06-21 14:56:22.014256+00:00 [info] <0.577.0> Asked to import definitions. Acting user: rmq-internal
32
2022-06-21 14:56:22.014318+00:00 [info] <0.577.0> Ready to start client connection listeners
31
2022-06-21 14:56:22.016784+00:00 [info] <0.743.0> started TCP listener on [::]:5672
