### ISSUE TITLE
[MongoDB]: Does not start on bare-metal Kubernetes cluster: `/opt/bitnami/scripts/libos.sh: line 336:    46 Illegal instruction`

### ISSUE THREAD

**Issue by eugene-marchanka** [bitnami/charts#10839]
### Name and Version

bitnami/mongodb 12.1.20

### What steps will reproduce the bug?

1. `helm template mongodb bitnami/mongodb > manifest.yaml`
2. `kubectl apply manifest.yaml`
3. `kubectl logs mongodb-f8db564fc-mss7l`:
```
mongodb 16:54:19.53
mongodb 16:54:19.53 Welcome to the Bitnami mongodb container
mongodb 16:54:19.53 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 16:54:19.54 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 16:54:19.54
mongodb 16:54:19.55 INFO  ==> ** Starting MongoDB setup **
mongodb 16:54:19.57 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 16:54:19.62 INFO  ==> Initializing MongoDB...
mongodb 16:54:19.66 INFO  ==> Deploying MongoDB from scratch...
/opt/bitnami/scripts/libos.sh: line 336:    46 Illegal instruction     "$@" > /dev/null 2>&1
```

### Are you using any custom parameters or values?

No. All parameters are default and deployed to `default` namespace.
Note1: result is the same even if I deploy to custom namespace.
Node2: the same result I have when deploy `replicaset`

### What is the expected behavior?

MongoDB pod started successfully

### What do you see instead?

```
mongodb 16:54:19.53
mongodb 16:54:19.53 Welcome to the Bitnami mongodb container
mongodb 16:54:19.53 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 16:54:19.54 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 16:54:19.54
mongodb 16:54:19.55 INFO  ==> ** Starting MongoDB setup **
mongodb 16:54:19.57 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 16:54:19.62 INFO  ==> Initializing MongoDB...
mongodb 16:54:19.66 INFO  ==> Deploying MongoDB from scratch...
/opt/bitnami/scripts/libos.sh: line 336:    46 Illegal instruction     "$@" > /dev/null 2>&1
```

### Additional information

```
$ kubectl get nodes -o wide
NAME        STATUS   ROLES                  AGE    VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
200-00   Ready    control-plane,master   111d   v1.21.6   172.16.200.10   <none>        CentOS Linux 7 (Core)   3.10.0-1160.53.1.el7.x86_64   containerd://1.5.8
200-01   Ready    control-plane,master   111d   v1.21.6   172.16.200.11   <none>        CentOS Linux 7 (Core)   3.10.0-1160.53.1.el7.x86_64   containerd://1.5.8
200-02   Ready    control-plane,master   111d   v1.21.6   172.16.200.12   <none>        CentOS Linux 7 (Core)   3.10.0-1160.53.1.el7.x86_64   containerd://1.5.8
200-03   Ready    <none>                 111d   v1.21.6   172.16.200.13   <none>        CentOS Linux 7 (Core)   3.10.0-1160.53.1.el7.x86_64   containerd://1.5.8
200-04   Ready    <none>                 111d   v1.21.6   172.16.200.14   <none>        CentOS Linux 7 (Core)   3.10.0-1160.53.1.el7.x86_64   containerd://1.5.8
200-05   Ready    <none>                 111d   v1.21.6   172.16.200.15   <none>        CentOS Linux 7 (Core)   3.10.0-1160.53.1.el7.x86_64   containerd://1.5.8
200-06   Ready    <none>                 111d   v1.21.6   172.16.200.16   <none>        CentOS Linux 7 (Core)   3.10.0-1160.53.1.el7.x86_64   containerd://1.5.8
200-07   Ready    <none>                 111d   v1.21.6   172.16.200.17   <none>        CentOS Linux 7 (Core)   3.10.0-1160.53.1.el7.x86_64   containerd://1.5.8
```
-----------------
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by snevilleshinn** [comment]
Same here!!
Chart version 11.1.10 works. I tried 3 prior releases in 12.X.X and all the same error.

**Comment by eugene-marchanka** [comment]
I can confirm this issue exists for quiet a while
I'm pretty sure I was running into the same issue in Jan 2022 when was trying `5.x.x-*` tags.
I think this related to images with tag `5.x.x-*`. I don't see this with tags `4.x.x-*` on bare-metal.

**Comment by rafariossaa** [comment]
Could you enable `image.debug` ? Let's see if that gives more information.

**Comment by eugene-marchanka** [comment]
Here is the manifest with `--set image.debug=true`:
```
---
# Source: mongodb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb
  namespace: "default"
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-12.1.20
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
secrets:
  - name: mongodb
automountServiceAccountToken: true
---
# Source: mongodb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: default
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-12.1.20
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  mongodb-root-password: "NmthMWQxYTBTcA=="
---
# Source: mongodb/templates/common-scripts-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-common-scripts
  namespace: "default"
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-12.1.20
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
data:
  startup-probe.sh: |
    #!/bin/bash
    mongosh  $TLS_OPTIONS --port $MONGODB_PORT_NUMBER --eval 'db.hello().isWritablePrimary || db.hello().secondary' | grep -q 'true'
  readiness-probe.sh: |
    #!/bin/bash
    # Run the proper check depending on the version
    [[ $(mongod -version | grep "db version") =~ ([0-9]+\.[0-9]+\.[0-9]+) ]] && VERSION=${BASH_REMATCH[1]}
    . /opt/bitnami/scripts/libversion.sh
    VERSION_MAJOR="$(get_sematic_version "$VERSION" 1)"
    VERSION_MINOR="$(get_sematic_version "$VERSION" 2)"
    VERSION_PATCH="$(get_sematic_version "$VERSION" 3)"
    if [[ "$VERSION_MAJOR" -ge 5 ]] || [[ "$VERSION_MAJOR" -ge 4 ]] && [[ "$VERSION_MINOR" -ge 4 ]] && [[ "$VERSION_PATCH" -ge 2 ]]; then
        mongosh $TLS_OPTIONS --port $MONGODB_PORT_NUMBER --eval 'db.hello().isWritablePrimary || db.hello().secondary' | grep -q 'true'
    else
        mongosh  $TLS_OPTIONS --port $MONGODB_PORT_NUMBER --eval 'db.isMaster().ismaster || db.isMaster().secondary' | grep -q 'true'
    fi
  ping-mongodb.sh: |
    #!/bin/bash
    mongosh  $TLS_OPTIONS --port $MONGODB_PORT_NUMBER --eval "db.adminCommand('ping')"
---
# Source: mongodb/templates/standalone/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb
  namespace: "default"
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-12.1.20
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
---
# Source: mongodb/templates/standalone/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: "default"
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-12.1.20
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: "mongodb"
      port: 27017
      targetPort: mongodb
      nodePort: null
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/component: mongodb
---
# Source: mongodb/templates/standalone/dep-sts.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: "default"
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-12.1.20
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
      app.kubernetes.io/instance: mongodb
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb
        helm.sh/chart: mongodb-12.1.20
        app.kubernetes.io/instance: mongodb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: mongodb
    spec:
      
      serviceAccountName: mongodb
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: mongodb
                    app.kubernetes.io/instance: mongodb
                    app.kubernetes.io/component: mongodb
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
        sysctls: []
      
      containers:
        - name: mongodb
          image: docker.io/bitnami/mongodb:5.0.9-debian-10-r15
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "true"
            - name: MONGODB_ROOT_USER
              value: "root"
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-root-password
            - name: ALLOW_EMPTY_PASSWORD
              value: "no"
            - name: MONGODB_SYSTEM_LOG_VERBOSITY
              value: "0"
            - name: MONGODB_DISABLE_SYSTEM_LOG
              value: "no"
            - name: MONGODB_DISABLE_JAVASCRIPT
              value: "no"
            - name: MONGODB_ENABLE_JOURNAL
              value: "yes"
            - name: MONGODB_PORT_NUMBER
              value: "27017"
            - name: MONGODB_ENABLE_IPV6
              value: "no"
            - name: MONGODB_ENABLE_DIRECTORY_PER_DB
              value: "no"
          ports:
            - name: mongodb
              containerPort: 27017
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 10
            exec:
              command:
                - /bitnami/scripts/ping-mongodb.sh
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - /bitnami/scripts/readiness-probe.sh
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: datadir
              mountPath: /bitnami/mongodb
              subPath: 
            - name: common-scripts
              mountPath: /bitnami/scripts
      volumes:
        - name: common-scripts
          configMap:
            name: mongodb-common-scripts
            defaultMode: 0550
        - name: datadir
          persistentVolumeClaim:
            claimName: mongodb
```

And logs after deploy:
```
$ kubectl logs mongodb-86745cd8b-b9vpw --previous
mongodb 20:17:29.82
mongodb 20:17:29.82 Welcome to the Bitnami mongodb container
mongodb 20:17:29.83 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 20:17:29.83 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 20:17:29.83
mongodb 20:17:29.83 INFO  ==> ** Starting MongoDB setup **
mongodb 20:17:29.86 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 20:17:29.91 INFO  ==> Initializing MongoDB...
mongodb 20:17:29.95 INFO  ==> Deploying MongoDB from scratch...
mongodb 20:17:29.96 DEBUG ==> Starting MongoDB in background...
/opt/bitnami/scripts/libos.sh: line 336:    47 Illegal instruction     "$@"
```
