### ISSUE TITLE
Mongodb no external access

### ISSUE THREAD

**Issue by DreamITJoris** [bitnami/charts#10858]
### Name and Version

bitnami/mongodb 12.1.20

### What steps will reproduce the bug?

1. Create a kind cluster, with config:

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: tcp
  - role: worker
  - role: worker
```
2. Install mongodb chart
3. Try to connect to mongodb from the host system

### Are you using any custom parameters or values?
```
--set 'architecture=replicaset,replicaCount=1'
--set 'auth.rootPassword=changeme'
--set 'externalAccess.enabled=true'
--set 'externalAccess.service.type=NodePort'
--set 'externalAccess.service.nodePorts[0]='30002''
```

### What is the expected behavior?

Mongodb should be accessible from the host system (using mongodb://root:changeme@localhost:30000).

### What do you see instead?

I get a connection timed out when trying to connect to the database

### Additional information

Connecting worked with version 11.2.0
