### ISSUE TITLE
Connection issue of Harbor Registry with external Redis + Sentinel

### ISSUE THREAD

**Issue by schwabix** [bitnami/charts#10869]
### Name and Version

bitnami/harbor 13.2.7

### What steps will reproduce the bug?

1. Provide a Redis HA instance with Sentinel enabled - we do this with the Bitnami Helm chart bitnami/redis:15.6.10 with this custom values.yaml:
```yaml
auth:
  enabled: false
replica:
  replicaCount: 3
rbac:
  create: true
metrics:
  enabled: true
sentinel:
  enabled: true
  masterSet: harbor-redis-master
  quorum: 2
  staticID: false
```

2. Deploy the Helm chart bitnami/harbor:13.2.7 with this custom values.yaml (this is the relevant section for the issue):
```yaml
redis:
  enabled: false
externalRedis:
  host: redisha # hostname of the previously deployed Redis instance
  sentinel:
    enabled: true
    masterSet: harbor-redis-master
    hosts: redisha:26379
```

3. Push and pull an image to the registry and watch the log output for the Pods in the `harbor-registry´ Deployment

### Are you using any custom parameters or values?

This is the relevant section for configuring the Harbor to Redis connection taken from my values.yaml:

```yaml
redis:
  enabled: false

externalRedis:
  host: redisha
  sentinel:
    enabled: true
    masterSet: harbor-redis-master
    hosts: redisha:26379
```

### What is the expected behavior?

I figured this out by looking at the Helm chart provided by the Harbor team - the resulting `harbor-registry` ConfigMap should have Redis config like this:

```yaml
redis:
  addr: "redisha:6379"
  sentinelMasterSet: harbor-redis-master
  db: 2
```

When I manually change the ConfigMap and restart my Harbor registry deployment the Redis connection seems to work just fine:

```
time="2022-06-24T08:25:47.94731321Z" level=info msg="redis: connect redisha:6379" go.version=go1.15 instance.id=95e5b8f2-b389-4195-8869-2f9e054395d9 redis.connect.duration=3.562071ms service=registry version=v2.8.0
```

### What do you see instead?

With my custom Redis configuration I get this result in the `harbor-registry` ConfigMap:

```yaml
redis:
  addr: "redisha:26379/harbor-redis-master:6379"
  db: 2
```

When accessing the Harbor registry to e.g. pull a Docker image i get errors like this in my `harbor-registry` Pods:

```
time="2022-06-24T07:36:39.769241292Z" level=error msg="error connecting to redis instance redisha:26379/harbor-redis-master:6379: dial tcp: address redisha:26379/harbor-redis-master:6379: too many colons in address" go.version=go1.15 instance.id=20384fb3-20e0-4bfd-b41e-0b2867ae436f service=registry version=v2.8.0
time="2022-06-24T07:36:39.769267729Z" level=error msg="redis: error connecting: dial tcp: address redisha:26379/harbor-redis-master:6379: too many colons in address" go.version=go1.15 instance.id=20384fb3-20e0-4bfd-b41e-0b2867ae436f redis.connect.duration=46.465µs service=registry version=v2.8.0
```
