### ISSUE TITLE
[bitnami/mariadb-galera] k8s deployment - Missing NetworkPolicy for gcomm connection 

### ISSUE THREAD

**Issue by ledroide** [bitnami/charts#10861]
### Name

bitnami/mariadb-galera 

### What steps will reproduce the bug?

There is no NetworkPolicy for wsrep between galera nodes, so I manage to create one. The node fails to start because of missing rule (egress or ingress, I can't tell).
Based on [this doc](https://galeracluster.com/library/documentation/firewall-settings.html)

```yaml 
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: galera
  labels:
    app: mariadb
    type: database
    product: myapp
spec:
  podSelector:
    matchExpressions:
      - key: type
        operator: In
        values:
          - database
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: mysql
          protocol: TCP
        - port: galera
          protocol: TCP
        - port: galera
          protocol: UDP
        - port: ist
          protocol: TCP
        - port: sst
          protocol: TCP
      from:
        - podSelector:
            matchExpressions:
              - key: type
                operator: In
                values:
                  - database
  egress:
    - to:
        - podSelector:
            matchExpressions:
              - key: type
                operator: In
                values:
                  - database
      ports:
        - port: mysql
          protocol: TCP
        - port: galera
          protocol: TCP
        - port: galera
          protocol: UDP
        - port: ist
          protocol: TCP
        - port: sst
          protocol: TCP
```
As a reminder, here is the _ports_ section in the StatefulSet : 
```yaml
          ports:
            - name: mysql
              containerPort: 3306
            - name: galera
              containerPort: 4567
            - name: ist
              containerPort: 4568
            - name: sst
              containerPort: 4444
```
Logs : 
```
2022-06-23 14:43:42 0 [Note] WSREP: Start replication
2022-06-23 14:43:42 0 [Note] WSREP: Connecting with bootstrap option: 1
2022-06-23 14:43:42 0 [Note] WSREP: Setting GCS initial position to 00000000-0000-0000-0000-000000000000:-1
2022-06-23 14:43:42 0 [ERROR] WSREP: It may not be safe to bootstrap the cluster from this node. It was not the last one to leave the cluster and may not contain all the updates. To force cluster bootstrap with this node, edit the grastate.dat file manually and set safe_to_bootstrap to 1 .
2022-06-23 14:43:42 0 [ERROR] WSREP: wsrep::connect(gcomm://) failed: 7
2022-06-23 14:43:42 0 [ERROR] Aborting
``` 

Note that the connection is possible when there is no NetworkPolicy, with the following MARIADB_GALERA_CLUSTER_ADDRESS parameter, so this is clearly some rule that is missing in the NetworkPolicy, which is not documented.

```bash
$ kubectl exec -t pod/database-0 -- env | grep MARIADB_GALERA_CLUSTER_ADDRESS
MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://database-0.database-headless.mariadb-sts.svc.poc.kube,database-1.database-headless.mariadb-sts.svc.poc.kube,database-2.database-headless.mariadb-sts.svc.poc.kube
```

As soon as the NetworkPolicy will work, I'll report here the correct manifest in order to help including this option in the Chart.

### Additional info

After deleting the NetworkPolicy : 
```bash
$ kubectl get pod,service --selector type=database
NAME             READY   STATUS    RESTARTS   AGE
pod/database-0   2/2     Running   0          35m
pod/database-1   2/2     Running   0          34m
pod/database-2   2/2     Running   0          33m

NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/database            ClusterIP   10.233.4.185    <none>        3306/TCP,9104/TCP            4d
service/database-headless   ClusterIP   None            <none>        4567/TCP,4568/TCP,4444/TCP   4d
service/database-metrics    ClusterIP   10.233.41.146   <none>        9104/TCP                     4d
```

**Comment by ledroide** [comment]
Edit : the missing policy is an Egress rule.
Because when allowing all Egress traffic, the `wsrep::connect(gcomm://)` succeeds, even with the Ingress rule given above.
```yaml
spec:
  egress:
    - {}
``` 
Any idea ?

**Comment by FraPazGal** [comment]
Hello @ledroide,

I couldn't reproduce your issue. I tried using the following netpol in a default `bitnami/mariadb-galera` installation without encountering any issues:

<details>
<summary>NetworkPolicy definition</summary>

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: galera
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mariadb-galera
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: mysql
          protocol: TCP
        - port: galera
          protocol: TCP
        - port: galera
          protocol: UDP
        - port: ist
          protocol: TCP
        - port: sst
          protocol: TCP
      from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: mariadb-galera
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: mariadb-galera
      ports:
        - port: mysql
          protocol: TCP
        - port: galera
          protocol: TCP
        - port: galera
          protocol: UDP
        - port: ist
          protocol: TCP
        - port: sst
          protocol: TCP
```
</details>

From what I understand, you are using some custom values. Could you share them so I can try reproducing the problem?

**Comment by ledroide** [comment]
Hello @FraPazGal , thanks for your answer.
In the source code for the [statefulset](https://github.com/bitnami/charts/blob/master/bitnami/mariadb-galera/templates/statefulset.yaml#L239), I confirm that port names are the default values.
```yaml
          ports:
            - name: mysql
              containerPort: {{ .Values.containerPorts.mysql }}
            - name: galera
              containerPort: {{ .Values.containerPorts.galera }}
            - name: ist
              containerPort: {{ .Values.containerPorts.ist }}
            - name: sst
              containerPort: {{ .Values.containerPorts.sst }}
``` 
And in [values.yaml](https://github.com/bitnami/charts/blob/master/bitnami/mariadb-galera/values.yaml#L589) : 
```yaml
containerPorts:
  mysql: 3306
  galera: 4567
  ist: 4568
  sst: 4444
``` 
The _Egress_ network policy simply says that the mariadb-galera pods are allowed to query all ports to an other replica of the same mariadb-galera cluster (they all have the same labels). Any other outgoing network call is denied.

The issue is that this Egress rule is not enough for gcomm. Some other destination is required as an Egress rule.
The question is "which pod, or which IP address, on which port, has to be allowed for gcomm ?"
If you can answer this question, then I'll share the NetworkPolicy code for this, it's the easy part.

**Comment by ledroide** [comment]
> Do you have a solution or workaround for this bug

Hello @morei25 . From my point of view, since there is no NetworkPolicy at all in the chart, it cannot be considered as a bug.
It's a lack of documentation, or k8sresource, or security directives, but since you don't try to control the network in your cluster, the helm chart works fine.

If you already have NetworkPolicies, you can allow all egress trafic out of the galera cluster.
```yaml
spec:
  egress:
    - {}
``` 
As soon as we will have an answer, I will post here the correct NetworkPolicy, that you'll have to simply copy and paste.
Hopefully, it will be included as an option in a next version of the chart.
