### ISSUE TITLE
[bitnami/keycloak] Readiness/Livenessprobe fails when Keycloak is served from subpath only

### ISSUE THREAD

**Issue by bobertrublik** [bitnami/charts#10885]
### Name and Version

bitnami/keycloak 9.3.2

### What steps will reproduce the bug?

My infrastructure needs to reach Keycloak at /auth only which was somewhat deprecated with Keycloak Quarkus. Thanks to a recent pull request I can use the following config to access Keycloak just like before:

```yaml
proxy: edge
extraEnvVars:
  - name: KEYCLOAK_HTTP_RELATIVE_PATH
    value: auth
  - name: KC_HOSTNAME
    value: my-domain
## Ingress configuration
##
ingress:
  enabled: true
  ingressClassName: nginx
  hostname: my-domain
  path: /auth
```

### What do you see instead?

The problem is [Keycloak's readiness probe in the statefulset](https://github.com/bitnami/charts/blob/master/bitnami/keycloak/templates/statefulset.yaml#L311) looks at /realms/master, which can't be reached and should be /auth/realms/master. 

> Warning  Unhealthy  30s (x2 over 40s)  kubelet            Readiness probe failed: Get "http://192.168.173.115:8080/realms/master": dial tcp 192.168.173.115:8080: connect: connection refused
>   Warning  Unhealthy  0s (x3 over 20s)   kubelet            Readiness probe failed: HTTP probe failed with statuscode: 404

This was changed with the introduction of Keycloak 17. [The commit](https://github.com/bitnami/charts/pull/10095/files#diff-13d578ae617ed76deafb93a8bdcf0e71e8a279e46a1ea9c99fc7e071ba3e0a00)

### Additional information

When I template the chart to a YAML file and manually set the path of the probes the checks don't fail.

```yaml
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /auth/realms/master
    port: http
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /auth
    port: http
```

Maybe it could be possible to add .`Values.ingress.path` as prefix to the probes?
