### ISSUE TITLE
Cannot get chart to create LoadBalancer service type

### ISSUE THREAD

**Issue by Bezz242** [bitnami/charts#10892]
### Name and Version

bitnami/postgresql 11.1.28

### What steps will reproduce the bug?

1. Create a gitlab deploy using the chart.
2. Add values to values.yml. Specifically
```
primary:
  service:
    type: LoadBalancer
    loadBalancerIP: <permanent ip address>
```
3. Deploy the project.

### Are you using any custom parameters or values?

```
# application name, use lowercase and dash separated strings, no spaces.
name: ${APPLICATION_NAME}
application_environment: ""

# domain name, use a fqdn
domain: ${domain}
imagePullPolicy: Always

# you can specify multiple secrets
imagePullSecrets:
  - name: regcredapi
resources: {}

postgresql:
  auth:
    postgresPassword: test
  rbac:
    create: true
  primary:
    persistence:
      enabled: true
      existingClaim: database-storage
  image:
    pullPolicy: Always

  ## TLS configuration
  ##
  tls:
    ## @param tls.enabled Enable TLS traffic support
    ##
    enabled: true
    ## @param tls.certificatesSecret Name of an existing secret that contains the certificates
    ##
    certificatesSecret: "certificates-tls-secret"
    ## @param tls.certFilename Certificate filename
    ##
    certFilename: "xxx"
    ## @param tls.certKeyFilename Certificate key filename
    ##
    certKeyFilename: "xxx"

primary:
  service:
    type: LoadBalancer
    loadBalancerIP: <permanent ip address>

```

### What is the expected behavior?

The Kubernetes service type would be LoadBalancer, and the loadBalancerIP would be set as specified.

### What do you see instead?

In Lens, looking at the service, we see:

```
spec:
  ports:
    - name: tcp-postgresql
      protocol: TCP
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: <some instance name>
    app.kubernetes.io/name: postgresql
  clusterIP: 10.0.51.35
  type: ClusterIP
  sessionAffinity: None
```

### Additional information

Some sensitive data has been removed from settings examples.
