### ISSUE TITLE
Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex

### ISSUE THREAD

**Issue by adomenech73** [bitnami/charts#10909]
### Name and Version

bitnami/etcd 8.1.3

### What steps will reproduce the bug?

```bash
kubectl rollout restart statefulset/etcd
```

### Are you using any custom parameters or values?

```yaml
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - etcd
            - key: app.kubernetes.io/instance
              operator: In
              values:
                - etcd
        topologyKey: topology.kubernetes.io/zone
auth:
  rbac:
    allowNoneAuthentication: true
    create: false
autoCompactionMode: revision
autoCompactionRetention: "5000000"
image:
  registry: harbor.reviewpro.com/hub-proxy
  repository: bitnami/etcd
metrics:
  enabled: true
  podMonitor:
    enabled: true
persistence:
  size: 8Gi
readinessProbe:
  initialDelaySeconds: 20
replicaCount: 3
```

### What is the expected behavior?

Rolling restart of all replicas

### What do you see instead?

there is always one replica failing with `Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex` error message

### Additional information

k8s: v1.21.12-eks-a64ea69

As workaround we scale instances to 0 and back to 3 which recovers the state of the instances
