### ISSUE TITLE
[bitnami/ghost]  Internal Server Error

### ISSUE THREAD

**Issue by jotcodeofficial** [bitnami/charts#10912]
### Name and Version

bitnami/ghost 19.0.6

### What steps will reproduce the bug?

When I visit my site I get: 'Internal Server Error'

The blog pod is alive and fine with no errors. The https cert for the page is working fine too, the issue is getting the service pointing to right thing, which I think is https port issue. When I check the logs of the pod:
```

ghost 05:56:37.35 INFO  ==> ** Ghost setup finished! **

ghost 05:56:37.56 INFO  ==> ** Starting Ghost **

Love open source? We’re hiring Node.js Engineers to work on Ghost full-time.
https://careers.ghost.org/product-engineer-node-js

- Inspecting operating system
```

Here is the relevant part of my values file:

```yaml
service:
  ## @param service.type Ghost service type
  ##
  type: ClusterIP
  ## @param service.ports.http Ghost service HTTP port
  ## @param service.ports.https Ghost service HTTPS port
  ##
  ports:
    http: 80
    https: 443
  ## Node ports to expose
  ## @param service.nodePorts.http Node port for HTTP
  ## @param service.nodePorts.https Node port for HTTPS
  ## NOTE: choose port between <30000-32767>
  ##
  nodePorts:
    http: ""
    https: ""
  ## @param service.clusterIP Ghost service Cluster IP
  ## e.g.:
  ## clusterIP: None
  ##
  clusterIP: ""
```

  here is my ingress route: 
```yaml
  apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: example
  name: example-ingress-route
annotations:
  kubernetes.io/ingress.class: "traefik"
  cert-manager.io/issuer: example-issuer
  traefik.ingress.kubernetes.io/router.entrypoints: web
  traefik.frontend.redirect.entryPoint: https
tls:
  - hosts:
      - example.com
    secretName: example-com-tls
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`example.com`)
      middlewares:
        - name: https-only,remove-www
      kind: Rule
      services:
        - name: example-blog-ghost
          namespace: example
          port: 80
```
If I change the port in here to 80, I just get a 404 page not found when I visit the site
here is my secure ingress route:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: example
  name: example-secure-ingress-route
annotations:
  kubernetes.io/ingress.class: "traefik"
  cert-manager.io/issuer: example-issuer
  traefik.ingress.kubernetes.io/router.entrypoints: websecure
  traefik.frontend.redirect.entryPoint: https
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`example.com`)
      kind: Rule
      services:
        - name: example-blog-ghost
          namespace: example
          port: 443
  tls:
    domains:
      - main: example.com
    options:
      namespace: example
    secretName: example-com-tls
```

I had this deployed before on version: v13.0.13
It instead had this (and worked for me)

```yaml
ghostProtocol: https
ghostHost: example.com
ghostPort: 443
ghostPath: /


service:
  type: ClusterIP

  ## HTTP Port
  ##
  port: 80
```

my middleware is just:

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-only
  namespace: example
spec:
  redirectScheme:
    scheme: https
    permanent: true
```

Thanks for any assistance!

### What is the expected behavior?

That when the user goes to https://example.com that it shows the ghost blog installation.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/ghost#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by jotcodeofficial** [comment]
I think this is the issue:

 kubectl port-forward --namespace domain svc/domain-blog-ghost 8080:80
error: Service domain-blog-ghost does not have a service port 80


also tried this:

```
kubectl port-forward --namespace domain svc/domain-blog-ghost 8080:443
Forwarding from 127.0.0.1:8080 -> 2368
Forwarding from [::1]:8080 -> 2368
```

which shows this when I visit localhost:

Secure Connection Failed

An error occurred during a connection to localhost:8080. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG



also:

here is what I get when I describe my deployment:
```


  Containers:
   domain-blog-ghost:
    Image:      docker.io/bitnami/ghost:5.2.3-debian-11-r3
    Port:       2368/TCP
    Host Port:  0/TCP
    Liveness:   http-get http://:https/ delay=120s timeout=5s period=10s #success=1 #failure=6
    Readiness:  http-get http://:https/ delay=30s timeout=3s period=5s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:                     false
      ALLOW_EMPTY_PASSWORD:              yes
      GHOST_DATABASE_HOST:               points to database on cluster
      GHOST_DATABASE_PORT_NUMBER:        3306
      GHOST_DATABASE_NAME:               db name
      GHOST_DATABASE_USER:               db user
      GHOST_DATABASE_PASSWORD:           <set to the key 'mysql-password' in secret 'domain-blog-ghost-externaldb'>  Optional: false
      GHOST_HOST:                        domain.com/
      GHOST_PORT_NUMBER:                 2368
      GHOST_USERNAME:                    domain
      GHOST_PASSWORD:                    <set to the key 'ghost-password' in secret 'domain-blog-ghost'>  Optional: false
      GHOST_EMAIL:                       admin@domain.com
      GHOST_BLOG_TITLE:                  domain
      GHOST_ENABLE_HTTPS:                yes
      GHOST_EXTERNAL_HTTP_PORT_NUMBER:   80
      GHOST_EXTERNAL_HTTPS_PORT_NUMBER:  443
      GHOST_SKIP_BOOTSTRAP:              no
      GHOST_SMTP_HOST:                   smtp host
      GHOST_SMTP_PORT:                   465
      GHOST_SMTP_USER:                   smtp user
      GHOST_SMTP_PASSWORD:               <set to the key 'smtp-password' in secret 'domain-blog-ghost'>  Optional: false
      GHOST_SMTP_SERVICE:                SES
      GHOST_SMTP_PROTOCOL:               tls
```

**Comment by nmella** [comment]
I have this error too. 😥

**Comment by wibed** [comment]
i expiriencing this aswell.
set up with the following values.yaml
```
  includeCRDs: false
  releaseName: cluster0
  valuesInline:
    ghostHost: ghost.local
    ghostPassword: test123123
    global:
      storageClass: mayastor
    service:
      type: ClusterIP
    ghostEnableHttps: true
    containerPorts:
      https: 2369
    mysql:
      auth:
        rootPassword: test123
        password: test123   
```

resulted in a 500 error when querying the address

after a portforward, curl closes with a 
```
*   Trying 127.0.0.1:9000...
* Connected to localhost (127.0.0.1) port 9000 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version
* Closing connection 0
curl: (35) error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version
```

openssl on the other hand
```
CONNECTED(00000005)
4376004140:error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number:/AppleInternal/Library/BuildRoots/b6051351-c030-11ec-96e9-3e7866fcf3a1/Library/Caches/com.apple.xbs/Sources/libressl/libressl-2.8/ssl/ssl_pkt.c:386:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 5 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Start Time: 1657779225
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by wibed** [comment]
i tried placing various containerPort configuration, each time https port is already in use.
i could manually set the port with the following command:
```
ghost config server.port.https 2379
ghost restart
```

ghost will fail to start up with an eaddrinuse error, as before

**Comment by wibed** [comment]
@dgomezleon 

could this be related to the latest v5 upgrade?

**Comment by wibed** [comment]
@jotcodeofficial have you found a solution?

**Comment by jawabuu** [comment]
Hey @wibed @jotcodeofficial 
Reposting  solution from https://github.com/bitnami/charts/issues/10534

https://github.com/bitnami/charts/issues/10534#issuecomment-1192649652

**Comment by wibed** [comment]
i am not sure if this solves the problem.
The problem is that there is a "mixed content" issue, because if run without turning on the https option the url within the database is based on http.

**Comment by jawabuu** [comment]
Hey @wibed share your `values.yaml`
You don't need to disable https bit you do need to change the *port name* on the service.

**Comment by wibed** [comment]
@jawabuu 

heres my kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
#  - ./ingressroute-hook.yaml

helmGlobals:
  chartHome: ../../../base/ghost

helmCharts:
- name: ghost
  includeCRDs: false
  releaseName: cluster0
  valuesInline:
    image:
      debug: true
      pullPolicy: Always
    ghostHost: ghost.local
    ghostPassword: test123123
    global:
      storageClass: mayastor
    service:
      type: ClusterIP
    containerPorts:
      tls: 2386
    ingress:
      enabled: true
      apiVersion: "networking.k8s.io/v1"
      hostname: ghost.local
      annotations:
        ingress.kubernetes.io/ssl-proxy-headers: 'X-Forwarded-Proto: https'
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/issuer: selfsigned
      tls: true
      selfSigned: true
    ghostEnableHttps: false
    mysql:
      auth:
        rootPassword: test123
        password: test123
  repo: https://charts.bitnami.com/bitnami
  ```

**Comment by jawabuu** [comment]
Hey @wibed 
I am using traefik
Have you seen this
```
## @param ghostEnableHttps Configure Ghost to build application URLs using https
##
ghostEnableHttps: false
```

**Comment by wibed** [comment]
@jawabuu 

if i enable https i receive the following
![image](https://user-images.githubusercontent.com/69305089/184968762-eb44c595-2145-42fa-95a4-ccb77905ace8.png)

the logs show nothing suspicious neither
![image](https://user-images.githubusercontent.com/69305089/184969151-33788887-52bc-40e8-892f-68a88bc0f545.png)


if you'd enable https, why youd use `ingress.kubernetes.io/ssl-proxy-headers: 'X-Forwarded-Proto: https'`
on your ingress route?

though i am using traefik 2.x and above configuration got dropped after 1.7
atm i think it might be traefik that is misconfigured. but id love to stand corrected

**Comment by jawabuu** [comment]
`ghostEnableHttps: true` ensures urls are created with `https://` so you don't get the mixed content warnings.
`

**Comment by jawabuu** [comment]
You must pass `X-Forwarded-Proto: https` to the ghost pod if `ghostEnableHttps: true` else you'll get a redirect loop.

**Comment by jawabuu** [comment]
Try the values I suggested with this chart
https://github.com/jawabuu/ghost-helm

**Comment by wibed** [comment]
@jawabuu 
could you point it out for me?

`grep -rnw ./ghost -e "X-Forwarded-Proto"
did not show any results. (its your repo btw)

**Comment by jawabuu** [comment]
Hey @wibed 
Take a look at the healthchecks in the deployment when `ghostEnableHttps: true`
This is from the official chart.
Feel free to change the port number to another value.

**Comment by jawabuu** [comment]
https://github.com/bitnami/charts/blob/5c31b475f3cc2b08460cc7f7d46592ed40e10f0e/bitnami/ghost/templates/deployment.yaml#L253-L263

**Comment by jawabuu** [comment]
See working values

```ghost:
  image:
    debug: true

  ## @param ghostHost Ghost host to create application URLs
  ##
  ghostHost: domain.com
  ghostPath: /
  ghostEnableHttps: true

  ingress:
    enabled: true
    hostname: domain.com
    annotations:
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: traefik-cert-manager
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      ingress.kubernetes.io/ssl-proxy-headers: 'X-Forwarded-Proto: https'
      traefik.ingress.kubernetes.io/router.priority: "60"
    tls: true
```

**Comment by wibed** [comment]
https://github.com/bitnami/charts/issues/10912#issuecomment-1217442342

on my end i have adjusted the port to reflect the adjustement.
```
readinessProbe:
  httpGet:
    path: /
    port: {{ ternary "tls" "http" .Values.ghostEnableHttps | quote }}
    scheme: HTTP
    {{- if .Values.ghostEnableHttps }}
      httpHeaders:
      - name: x-forwarded-proto
      value: https
   {{- end }}
   initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
   periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
   timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
   failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
   successThreshold: {{ .Values.readinessProbe.successThreshold }}
```
