### ISSUE TITLE
[bitnami/rabbitmq] undocumented breaking change - all persisted data is ignored value unless overrides added

### ISSUE THREAD

**Issue by blowfishpro** [bitnami/charts#10913]
### Name and Version

bitnami/rabbitmq 10.1.8

### What steps will reproduce the bug?

1. be on an oldish version of the rabbitmq chart (we were on 6.18.2)
2. be using persistence and durable queues
3. Upgrade to a newer version
  - Read [the upgrade notes](https://github.com/bitnami/charts/tree/c35f65410909ebbdda728942b11d1b88ce28cf4c/bitnami/rabbitmq#upgrading) and change all the values that are mentioned, not no mention of mount paths or data directories

### Are you using any custom parameters or values?
```
persistence:
  enabled: true
image:
  tag: 3.10.5-debian-11-r7
replicaCount: 3
pdb:
  create: true
  minAvailable: 2
resources:
  requests:
    cpu: 700m
    memory: 4.5Gi
auth:
  username: guest
  existingPasswordSecret: rabbitmq-secrets
  existingErlangSecret: rabbitmq-secrets
```

### What is the expected behavior?

Either the upgrade works seamlessly and all the old data is used, or instructions on how to deal with the breaking change are included in the readme.

### What do you see instead?

None of the existing data in the persisted volumes is used.  Instead, rabbitmq initializes fresh.  All the existing data files are present within the data volume but rabbitmq does not use them.  It looks for the files at a different location:

Prior to this change, the data volume was expected to contain several directories including `mnesia/` which was used as the data directory.  After the change the data volume itself is mounted at a path that includes `mnesia/` and is expected to only contain that.

This would be fine if it were documented.  The upgrading nodes mention a lot of values that have been added, removed, or moved around, a vague note about "backwards compatibility is not guaranteed", but nothing about the data volume layout being incompatible.

### Additional information

I believe the breaking change was introduced in #2843 (so 7.0.0).  This appears to be where the mount path was changed to include `mnesia`.

I mentioned this above but I'll reiterate it: I don't necessarily object to the change, but the fact that it isn't clearly documented in the upgrade notes (or anywhere I can find) is a problem.  This means that saved data will be effectively lost with no indication.

A few workarounds might be possible:
1. override the `subPath` value so that the old data volume structure can be used
2. Have an init container that moves the files around

**Comment by blowfishpro** [comment]
Here's the init container I've been experimenting with to deal with this (and the rabbitmq clusters that were already upgraded without realizing).  Could probably be cleaned up a bit:
```yaml
initContainers: |-
  - name: migrate-old-data
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command:
      - sh
    args:
      - -ec
      - |-
        if [ ! -d "${MOUNT_PATH}/mnesia" ]; then exit; fi
        if [ ! -d "${RABBITMQ_MNESIA_DIR}" ]; then mv "${MOUNT_PATH}/mnesia"/* "${MOUNT_PATH}"; fi
        rm -rf "${MOUNT_PATH}/mnesia" "${MOUNT_PATH}/config" "${MOUNT_PATH}/schema"
    volumeMounts:
      - name: data
        mountPath: "{{ .Values.persistence.mountPath }}"
        {{- if .Values.persistence.subPath }}
        subPath: {{ .Values.persistence.subPath }}
        {{- end }}
    env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: K8S_SERVICE_NAME
        value: {{ printf "%s-headless" (include "common.names.fullname" .) }}
      - name: MOUNT_PATH
        value: "{{ .Values.persistence.mountPath }}"
      - name: RABBITMQ_NODE_NAME
        value: "rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.{{ .Values.clusterDomain }}"
      - name: RABBITMQ_MNESIA_DIR
        value: "{{ .Values.persistence.mountPath }}/$(RABBITMQ_NODE_NAME)"
```
