### ISSUE TITLE
RabbitMQ on Apple M1 fails with `Segmentation fault` error.

### ISSUE THREAD

**Issue by oleksiivelychko** [bitnami/charts#10915]
### Name and Version

bitnami/rabbitmq 10.1.10

### What steps will reproduce the bug?

MacOS Monterey 12.4
Apple Silicon M1
Chart version 10.1.10
Application version 3.10.5-debian-11-r9

My skaffold.yaml
```
deploy:
  helm:
    releases:
    - name: rabbitmq
      remoteChart: bitnami/rabbitmq
      version: 10.1.9
      valuesFiles:
        - .ops/helm/values/rabbitmq.yaml
```
... where **rabbitmq.yaml** is values from https://artifacthub.io/packages/helm/bitnami/rabbitmq/10.1.10 page

I should notice that works correctly on below versions since 8.x

### Are you using any custom parameters or values?

Only default values from https://artifacthub.io/packages/helm/bitnami/rabbitmq/10.1.10

### What do you see instead?

```
...........................
/opt/bitnami/scripts/libos.sh: line 336:   752 Segmentation fault      "$@" > /dev/null 2>&1                                                                             
/opt/bitnami/scripts/libos.sh: line 336:   807 Segmentation fault      "$@" > /dev/null 2>&1                                                                             
/opt/bitnami/scripts/libos.sh: line 336:   862 Segmentation fault      "$@" > /dev/null 2>&1    
...........................
```
