### ISSUE TITLE
Eks 1.22 Eks Role Service Account Token not mounted

### ISSUE THREAD

**Issue by fbuinosquy1985** [bitnami/charts#10927]
### Name and Version

bitnami/external-dns all versions

### What steps will reproduce the bug?

Eks 1.22, by the default, doesn't mount the Service Account Token it has to be mounted as a Volume

```yaml
        aws:
          region: us-west-2
        serviceAccount:
          create: true
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::793117784422:role/ruby-eks-dev-Ka5mMwv3-external-dns
          name: "external-dns"
        domainFilters: 
          - dev.devops.ruby.com
        extraVolumeMounts:
          - name: aws-iam-token
            readOnly: true          
            mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
        extraVolumes:
          - name: aws-iam-token
            projected:
              defaultMode: 420
              sources:
              - serviceAccountToken:
                audience: sts.amazonaws.com
                expirationSeconds: 86400
                path: token  
```
The error is basically that I don't have permission to use Route53, I wanted to mount the Secret as a Volume but that is not supported on this helm chart.

### What do you see instead?

AccessDenied Route53 or 
```
error validating data: [ValidationError(Deployment.spec.template.spec.volumes[0].projected.sources[0]): unknown field "audience" in io.k8s.api.core.v1.VolumeProjection,
```
