### ISSUE TITLE
[bitnami/postgresql-ha] Unable to start two postgresql-ha in same chart 

### ISSUE THREAD

**Issue by Dracufat** [bitnami/charts#10948]
### Name and Version

bitnami/postgresql-ha 8+

### What steps will reproduce the bug?

1. In a fresh cluster (v1.22.6) on an empty namespace with helm v3.8.0
2. With this config
Chart.yaml
```yaml
apiVersion: v2
name: psql
description: A Helm chart for Kubernetes
type: application
version: 0.3.0
appVersion: 14.0.0

dependencies:
  - repository: https://charts.bitnami.com/bitnami
    name: postgresql-ha
    condition: postgresql-ha.enabled
    version: 8.6.13
  - name: postgresql-ha
    version: 9.1.1
    alias: psql-ha
    condition: psql-ha.enabled
    repository: https://charts.bitnami.com/bitnami
```
3. Run this
``` helm install psql . -f values.yaml```
```bash
helm install psql . -f values.yaml
Error: INSTALLATION FAILED: template: psql/charts/psql-ha/templates/NOTES.txt:83:4: executing "psql/charts/psql-ha/templates/NOTES.txt" at <include "postgresql-ha.checkRollingTags" .>: error calling include: template: psql/charts/postgresql-ha/templates/_helpers.tpl:553:4: executing "postgresql-ha.checkRollingTags" at <include "common.warnings.rollingTag" .Values.postgresqlImage>: error calling include: template: psql/charts/postgresql-ha/charts/common/templates/_warnings.tpl:9:32: executing "common.warnings.rollingTag" at <.repository>: invalid value; expected string
```

### Are you using any custom parameters or values?

Values for both instance are very basic. 

Values.yaml
```yaml

psql-ha:
  enabled: true
  postgresql:
    username: "keycloak"
    database: "keycloak"
    password: dbadminpassword
    repmgrPassword: repmgradmin
    pdb:
      create: true
      maxUnavailable: 1
      minAvailable: ""
  pgpool:
    adminUserName: "keycloak"
    replicaCount: 2
    adminPassword: dbadminpassword
    pdb:
      create: true
      maxUnavailable: 1
      minAvailable: ""

postgresql-ha:
  enabled: true
  postgresql:
    username: "keycloak"
    database: "keycloak"
    password: dbadminpassword
    repmgrPassword: repmgradmin
    pdb:
      create: true
      maxUnavailable: 1
      minAvailable: ""
  pgpool:
    adminUserName: "keycloak"
    replicaCount: 2
    adminPassword: dbadminpassword
    pdb:
      create: true
      maxUnavailable: 1
      minAvailable: ""
```

### What is the expected behavior?

A postgresql-ha 9+ instance alongside the existing postgresql-ha 8+  instance. Both charts are templated correctly independently, but when trying to spawn both helm is unable to template.

### What do you see instead?

helm is unable to template
```
Error: INSTALLATION FAILED: template: psql/charts/psql-ha/templates/NOTES.txt:83:4: executing "psql/charts/psql-ha/templates/NOTES.txt" at <include "postgresql-ha.checkRollingTags" .>: 
error calling include: template: psql/charts/postgresql-ha/templates/_helpers.tpl:553:4: executing "postgresql-ha.checkRollingTags" at <include "common.warnings.rollingTag" .Values.postgresqlImage>: 
error calling include: template: psql/charts/postgresql-ha/charts/common/templates/_warnings.tpl:9:32: executing "common.warnings.rollingTag" at <.repository>: invalid value; expected string
```
### Additional information

The idea is to  migrate from postgresql 11 to 14 without service interruption on a production cluster:
The path of migration I try to implement is:
- spawn a postgresql-ha 9+ alongside existing postgresql-ha 8+ with a different alias
- synchronize the data
- rollout restart the applications that use the database with the new address.
- remove the old postgresql-ha 8+ instance
