### ISSUE TITLE
Installation of system table failed

### ISSUE THREAD

**Issue by fabry00** [bitnami/charts#10980]
### Name and Version

bintami/mariadb-galera:10.8.3-debian-11-r1

### What steps will reproduce the bug?

Deploying the mariadb-galera helm chart using the image `mariadb-galera:10.8.3-debian-11-r1` crashes at pod starts:
![image](https://user-images.githubusercontent.com/11576418/176710581-a6d5eda5-3085-4dde-bf10-a0bb6b970732.png)

If I use the tag 10.6.8-debian-11-r3 everything works perfectly

I had to disabled in the security context because in our Openshift cluster is not enabled. (but  10.6.8-debian-11-r3 it worked anyway)
```yaml
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
```

### Are you using any custom parameters or values?
```yaml
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
```

### What do you see instead?

Check the image
