### ISSUE TITLE
[bitnami/rabbitmq] Helm diff always different when a new chart version release

### ISSUE THREAD

**Issue by Dunge** [bitnami/charts#10985]
### Name and Version

bitnami/rabbitmq

### What steps will reproduce the bug?

I'm still new to this so this is probably a misunderstanding in my comprehension and not a bug, but it's strange.

I'm using the helmfile project with `helmfile apply` to deploy a cluster, which uses the `helm diff` plugin internally to check for modifications before applying them.

This is a snippet of my helmfile:

```yaml
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: jl-rabbitmq
  namespace: default
  chart: bitnami/rabbitmq
  labels:
    name: jl-rabbitmq
  version: ~10.1.8
  values:
    - ./values/rabbitmq.yaml
```

As you can see, I'm using the tilde (~) operator to accept any new "patch version" chart, so if I understand correctly it should update charts to any new release matching 10.1.X

It worked fine at first, but when a new chart release (three times since I selected this version) afterward every run to `helmfile apply` tells me there's a difference en need to update, even if it already done just seconds before:

```
Upgrading release=jl-rabbitmq, chart=bitnami/rabbitmq
Release "jl-rabbitmq" has been upgraded. Happy Helming!

\Kubernetes> helm history jl-rabbitmq

REVISION        UPDATED                         STATUS          CHART                   APP VERSION     DESCRIPTION
1               Wed Jun 29 15:25:59 2022        superseded      rabbitmq-10.1.10        3.10.5          Install complete
2               Thu Jun 30 12:37:01 2022        superseded      rabbitmq-10.1.11        3.10.5          Upgrade complete
3               Thu Jun 30 13:11:21 2022        superseded      rabbitmq-10.1.11        3.10.5          Upgrade complete
4               Thu Jun 30 13:41:32 2022        deployed        rabbitmq-10.1.11        3.10.5          Upgrade complete
```

The difference the "diff" gives is this:

```diff
-         checksum/secret: ecc2e11d3c50f7d5ffbe74056b4477a33f5cd303f36672aa808e8cce04249855
+         checksum/secret: 9b9a7129c10e4a0a5bf5db44184ac39c3c25b9cab2f2431e363bbc4e5eea73b0
```
which is under `rabbitmq/templates/statefulset.yaml` `spec.template.metadata.annotations`

### Are you using any custom parameters or values?

Not sure if it matters, but here's my values file:

```yaml
replicaCount: 3

auth:
  username: jl
  password: jl
  erlangCookie: BAxTTl4hvij3VkivFaBtYtzZLNlO7ttN

clustering:
  partitionHandling: pause_minority
  
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "permissions": [
          {
            "user": "jl",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          }
        ],
        "vhosts": [
          {
            "name": "/"
          }
        ],
        "policies": [
          {
            "name": "ha-all",
            "pattern": ".*",
            "vhost": "/",
            "definition": {
              "ha-mode": "all",
              "ha-sync-mode":	"automatic",
              "max-length-bytes": 50000000,
            }
          }
        ]
      }

loadDefinition:
  enabled: true
  existingSecret: load-definition

extraConfiguration: |-
  default_vhost = /
  default_permissions.configure = .*
  default_permissions.read = .*
  default_permissions.write = .*
  load_definitions = /app/load_definition.json
```

### What is the expected behavior?

No change if I already updated the chart to the latest revision once

### What do you see instead?

Always a new diff, always a new upgrade

**Comment by Dunge** [comment]
Worth nothing that uninstalling the chart, deleting all PVC and reinstalling it works fine... until there's a new release.

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Rabbitmq container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by dostalradim** [comment]
Same problem for me, we have rabbitmq chart in dependencies for our application with following configuration.

```
clusterDomain: "k8s-dev.example.com"
fullnameOverride: "stc-ng-rabbitmq"
clustering:
  enabled: false
metrics:
  enabled: true
service:
  labels:
    metrics: "true"
auth:
  username: "admin"
  password: "Kawasaki2"
  erlangCookie: "Kawasaki2"
```

When we install our application with `helm -i upgrade ....` it makes first installation and everything starts successfully. Then we change something in our application (means new docker image and helm version of our application) we have still dependency to same rabbitmq chart version. Then we call `helm -i upgrade...` again and because it exists helm is going to do application upgrade and during this first upgrade the rabbitmq has been restarted. But during the next upgrades the rabbitmq is not restarted. So I did dump of rabbitmq statefullset before first upgrade and after first upgrade and I saw checksum change between it but the version and configuration is same. Secret file should be same too because it is same rabbitmq chart version. I had no luck with simulation this problem with solo rabbitmq chart.
