### ISSUE TITLE
[nginx] Allow passing custom containerPorts

### ISSUE THREAD

**Issue by agermain** [bitnami/charts#10998]
### Name and Version

bitnami/nginx 12.0.1

### What is the problem this feature will solve?

It's currently not possible to create custom server blocks that will target different ports. It'd be very useful to be able to specify custom ones, e.g.
```
containerPorts:
  http: 8080
  https: ""
extraContainerPorts:
 - name: grpc
   containerPort: 4317
```

### What is the feature you are proposing to solve the problem?

This could work with a given param `extraContainerPorts` in a similar fashion to `extraVolumeMounts`/`extraEnvVars`. I'm happy to submit a PR.
