### ISSUE TITLE
[bitnami/keycloak] Allow to use DB_VENDOR: H2 for e.g. integration tests

### ISSUE THREAD

**Issue by jxsl13** [bitnami/charts#10992]
### Name and Version

bitnami/keycloak 9.3.4

### What is the problem this feature will solve?

Using the chart for integration tests without having to spin up a postgres database, as one does not need to persist the integration test data anyway.

### What is the feature you are proposing to solve the problem?

When disabling the database and not setting any external database parameters I do get an error message.
It would be nice to fallback to the DB_VENDOR: H2 in this case.

### What alternatives have you considered?

the codecentric keycloak chart but that's pretty bad to configure.
One also might try to not use the bitnami keycloak docker image but a different one but that is going to cause the same error when trying to disable the database.

The other alternative is to spin up keycloak with the database and still run the tests.

**Comment by jxsl13** [comment]
another good addition for integration tests would be to allow the modification of the postgresql helm chart to some extent e.g.) disabling persistence.

**Comment by rafariossaa** [comment]
Hi,  
  Would you like to send a PR implementing this ?
  We will be glad to review and merge it.

**Comment by rafariossaa** [comment]
I am sorry, but my previous comment was wrong. 
There is not PR to add this.

**Comment by trevor-vaughan** [comment]
Hi there. I'd like this as well for ease of use in small CI test environments.

**Comment by orendain** [comment]
FYI: Using chart version `15.1.2`, one can work around this limitation by providing values to "trick" the chart into not complaining.

The following config works:

```yaml
keycloak:
  postgresql:
    enabled: false
  externalDatabase:
    host: "none"     # any non-empty value here works
  extraEnvVars:
    - name: KEYCLOAK_DATABASE_VENDOR
      value: "dev-file"
```

Of course, a proper solution would be ideal.
