### ISSUE TITLE
harbor: add liveliness checks to postgres and redis pods

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#11006]
### Name and Version

bitnami/harbor:13.2.7

### What is the problem this feature will solve?

I'm not sure why just yet, maybe my nas went offline, but a few times now I've noticed harbor was down because both the redis and postgres pods were seeing a read-only filesystem.  After restarting these pods they came right back up, as well as the jobservice and core pods which depended on the postgres pod.

### What is the feature you are proposing to solve the problem?

I see the 'pg_isready' liveliness check but this doesn't look for a read-only filesystem, so it is insufficient.

Need to add the ability to add a customLivenessProbe to the pods with postgresql.

### What alternatives have you considered?

I see several customLivenessProbe values at https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml .
I think primary.customLivenessProbe might be the one I need, but I'm not sure how to add that.  Is it possible for me to add this to the harbor helm chart and have it apply to the postgresql pod?
```
  customLivenessProbe:
    exec:
      command:
      - /bin/sh
      - -c
      - $(exit `dmesg | grep "Remounting filesystem read-only" | wc --lines`)
    initialDelaySeconds: 20
    periodSeconds: 20
```

**Comment by migruiz4** [comment]
Hi @lknite,

Postgresql and Redis are subcharts of the Harbor chart and all the values documented in their README can be used by adding `posgresql.*` and `redis.*` in front of the value.

For example, `primary.customLivenessProbe` can be configured using `postgresql.primary.customLivenessProbe`:
```yaml
postgresql:
  enabled: true
  primary:
    customLivenessProbe:
      ...
  readReplicas:
    customLivenessProbe:
      ...
redis:
  enabled: true
  master:
    customLivenessProbe:
      ...
  replicas:
    customLivenessProbe:
      ...
```

**Comment by lknite** [comment]
@migruiz4 I tried before you posted, and again after I saw your posting, but it doesn't seem to be working?  Do you see anything wrong with this yaml which I have added to my values file?
```
harbor:
  ...<snip>...
  persistence:
    enabled: true

    persistentVolumeClaim:
      registry:
        size: 1000Gi

  postgresql:
    primary:
      customLivenessProbe:
        exec:
          command:
          - /bin/sh
          - -c
          - $(exit `dmesg | grep "Remounting filesystem read-only" | wc --lines`)
        initialDelaySeconds: 20
        periodSeconds: 20

```
Applying this values.yaml is not updating the postgresql pod with the additional livenessProbe.

**Comment by migruiz4** [comment]
My bad, it is also necessary to set `livenessProbe.enabled=false` for `customLivenessProbe` to take effect:

```yaml
postgresql:
  enabled: true
  primary:
    livenessProbe:
      enabled: false
    customLivenessProbe:
      ...
  readReplicas:
    livenessProbe:
      enabled: false
    customLivenessProbe:
      ...
redis:
  enabled: true
  master:
    livenessProbe:
      enabled: false
    customLivenessProbe:
      ...
  replicas:
    livenessProbe:
      enabled: false
    customLivenessProbe:
      ...
```



I checked it using `--dry-run` and it should work
```
helm install test ./bitnami/harbor --dry-run -f values.yaml | grep -C 10  Remounting
            - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
              value: "pgaudit"
          ports:
            - name: tcp-postgresql
              containerPort: 5432
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - $(exit `dmesg | grep "Remounting filesystem read-only" | wc --lines`)
            initialDelaySeconds: 20
            periodSeconds: 20
--
            - name: REDIS_PORT
              value: "6379"
          ports:
            - name: redis
              containerPort: 6379
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - $(exit `dmesg | grep "Remounting filesystem read-only" | wc --lines`)
            initialDelaySeconds: 20
            periodSeconds: 20
```
