### ISSUE TITLE
[bitnami/kube-prometheus] Ingress does not use provided secrets

### ISSUE THREAD

**Issue by bh-tt** [bitnami/charts#11016]
### Name and Version

bitnami/kube-prometheus 8.0.9

### What steps will reproduce the bug?

Deploy the chart to any cluster with an ingress controller.

### Are you using any custom parameters or values?

```yaml
prometheus:
  ingress:
    enabled: true
    hostname: prometheus.k8s-intra-rd.local
    ingressClassName: nginx
    pathType: Prefix
    tls: true
    secrets:
      - name: prometheus.k8s-intra-rd.local-tls
         certificate: "<certificate>"
         key: "<key>"
```

### What is the expected behavior?

The ingress should use the provided secret to serve TLS.

### What do you see instead?

The ingress uses the default self-signed certificate, because the Ingress secret is created but not *used*. The problem is similar to https://github.com/bitnami/charts/issues/10567 (in fact, the ingress template appears to be almost identical), the TLS key is only enabled if a self-signed certificate is used or CSR annotations are provided.

The fix should also be similar.

### Additional information

 I'm sure there are more charts in this repository with the same issue, as this is the second time I've run into this problem.

Edit: indentation of values.
