### ISSUE TITLE
[bitnami/thanos] Thanos Query HTTP Ingress stop working when annotating service to use gRPC + Traefik 2.0

### ISSUE THREAD

**Issue by felippe-mendonca** [bitnami/charts#11028]
### Name and Version

bitnami/thanos 9.0.1

### What is the problem this feature will solve?

I've recently moved to Traefik 2.0 and to make gRPC Ingress work properly, I've added the following annotation to `thanos-query` Service:

```yaml
query:
  service:
    annotations:
      traefik.ingress.kubernetes.io/service.serversscheme: h2c
```

Traefik doc: https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/#on-service

However, since the Service object shares both `http` and `grpc` ports, as we can see below, the HTTP Ingress stop working.

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
  labels:
    app.kubernetes.io/component: query
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-9.0.1
  name: thanos-query
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: http
  - name: grpc
    port: 10901
    protocol: TCP
    targetPort: grpc
  selector:
    app.kubernetes.io/component: query
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/name: thanos
  sessionAffinity: None
  type: ClusterIP
```

Any one else facing same problem? Although using an outdated version, I've checked on the latest and still have same behavior. 

### What is the feature you are proposing to solve the problem?

I believe one solution is having separate services on Thanos Query for `http` and `grpc` port. Any other sugestion? I'll be happy to open a PR ;)
