### ISSUE TITLE
Postgres is creating user as "user" even though username is specified in values.yml file.

### ISSUE THREAD

**Issue by NishaSharma14** [bitnami/charts#11033]
### Name and Version

bitnami/postgres 11.6.13

### What steps will reproduce the bug?

1. Add bitnami repo.
2. Install postgres via helm in Kubernetes Cluster.

### Are you using any custom parameters or values?

```
postgresql:
  auth:
    username: "pguser"
    password: "secret"
    database: "testdatabase"
    postgresPassword: "secret"  
  enabled: true
  global:
    storageClass: standard
  host: host-postgresql
  connection: pgsql
  persistence:
    enabled: true
    existingClaim: ''
    size: 50Gi
  port: 5432
  primary:
    service:
      type: LoadBalancer
      port: 5432
  resources:
    limits:
      cpu: 200m
      memory: 150Mi
    requests:
      cpu: 20m
      memory: 100Mi
```

### What is the expected behavior?

It should create user as specified in the values.yml.

### What do you see instead?

Instead, it creates user as "user".

![image](https://user-images.githubusercontent.com/54287612/177281432-24b572a6-d445-4c56-ab19-5871dccc5ae0.png)
