### ISSUE TITLE
Context path is not active with httpRelativePath

### ISSUE THREAD

**Issue by Konstantins-andronovs** [bitnami/charts#11070]
### Name and Version

bitnami/keycloak 9.4.0

### What steps will reproduce the bug?

Encountered issue doing helm install on rke k8s cluster with new provided `httpRelativePath` parameter.

Command: `helm install keycloak -f keycloak-values.yaml -n keycloak bitnami/keycloak`

### Are you using any custom parameters or values?
```
rbac:
    create: true
  rules:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
        - list
serviceAccount:
  automountServiceAccountToken: true

ingress:
  enabled: true
  hostname: "hostName"
  path: /auth
  annotations:
    "nginx.ingress.kubernetes.io/proxy-buffer-size": "128k"

postgresql:
  enabled: false
externalDatabase:
  host: "dbHost"
  port: 5000
  user: keycloak
  password: "password"
  database: keycloak
```
```
httpRelativePath: /auth
proxy: edge
extraStartupArgs: "--auto-build --http-enabled=true --hostname-strict-https=false --hostname-strict=false"
extraEnvVars:
   - name: KEYCLOAK_EXTRA_ARGS
    value: "-Dkeycloak.frontendUrl=https://hostName/auth"
```
```
extraVolumes:
   - name: keycloak-volume
    persistentVolumeClaim:
      claimName: keycloak-volume-claim
  - name: keycloak-deployments-volume
    persistentVolumeClaim:
      claimName: keycloak-volume-claim-deployments
extraVolumeMounts:
   - name: keycloak-volume
    mountPath: /opt/bitnami/keycloak/themes/domain
   - name: keycloak-deployments-volume
    mountPath: /opt/bitnami/keycloak/standalone/deployments/custom
```
### What is the expected behavior?

Keycloak context path to be /auth

### What do you see instead?

- ### Helm response
```
NAME: keycloak
LAST DEPLOYED: Thu Jul  7 00:02:07 2022
NAMESPACE: keycloak
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: keycloak
CHART VERSION: 9.4.0
APP VERSION: 18.0.2

** Please be patient while the chart is being deployed **

Keycloak can be accessed through the following DNS name from within your cluster:

    keycloak.keycloak.svc.cluster.local (port 80)

To access Keycloak from outside the cluster execute the following commands:

1. Get the Keycloak URL and associate its hostname to your cluster external IP:
   export CLUSTER_IP=$(minikube ip) # On Minikube. Use: `kubectl cluster-info` on others K8s clusters
   echo "Keycloak URL: http://_hostName_/"
   echo "$CLUSTER_IP  _hostName_" | sudo tee -a /etc/hosts
2. Access Keycloak using the obtained URL.
3. Access the Administration Console using the following credentials:
  echo Username: user
  echo Password: $(kubectl get secret --namespace keycloak keycloak -o jsonpath="{.data.admin-password}" | base64 -d)
```
-  ### Behaviour
You can access keycloak with direct port forwarding from cluster + adding /auth path, but it does not work as a context path

- Direct k8s service access:
![image](https://user-images.githubusercontent.com/30385884/177644929-c05bee41-6948-4a32-94a2-d7784c39d252.png)

- Manually entered /auth path:
![image](https://user-images.githubusercontent.com/30385884/177645061-ebbb573e-37bd-4011-ad88-5a2f9822d0f5.png)

### Additional information

Previously we were using:
>bitnami/keycloak 
CHART VERSION 7.1.18       
APP VERSION 16.1.1

with the following config:

>auth:
  createAdminUser: true
  adminUser: user
  adminPassword: "password"
serviceDiscovery:
  enabled: true
replicaCount: 1
service:
  type: ClusterIP
rbac:
  create: true
  rules:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
        - list
serviceAccount:
  automountServiceAccountToken: true

>ingress:
  enabled: true
  hostname: "hostName"
  path: /auth
  annotations:
    "nginx.ingress.kubernetes.io/proxy-buffer-size": "128k"

>postgresql:
  enabled: false
externalDatabase:
  host: "dbHost"
  port: 5000
  user: keycloak
  password: "dbPassword"
  database: keycloak

>**proxyAddressForwarding: true
extraEnvVars:
  \- name: KEYCLOAK_LOG_LEVEL
    value: DEBUG
  \- name: KEYCLOAK_EXTRA_ARGS
    value: "-Dkeycloak.frontendUrl=https://hostName/auth"**

>extraVolumes:
  \- name: keycloak-volume
    persistentVolumeClaim:
      claimName: keycloak-volume-claim
  \- name: keycloak-deployments-volume
    persistentVolumeClaim:
      claimName: keycloak-volume-claim-deployments
extraVolumeMounts:
  \- name: keycloak-volume
    mountPath: /opt/bitnami/keycloak/themes/domain
  \- name: keycloak-deployments-volume
    mountPath: /opt/bitnami/keycloak/standalone/deployments/custom
