### ISSUE TITLE
TLS failing in Helm Chart for mariadb-galera

### ISSUE THREAD

**Issue by jhermosobernabeu** [bitnami/charts#11088]
### Name and Version

bitnami/mariadb-galera

### What steps will reproduce the bug?

TLS it is failing all the time.

1.- Create local certs
2.- load secrets + secrets for certs to the namespace, as described in README 
3.- install the release

certificated are validated OK
```
Error:
[ERROR] WSREP: handshake with remote endpoint ssl://10.42.0.128:4567 failed: asio.ssl:337047686: 'certificate verify failed' ( 337047686: 'error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed')
```

### Are you using any custom parameters or values?

Into the values.yaml
```
## Use existing secret (ignores rootUser.password, db.password, and galera.mariabackup.password)
##
  existingSecret: galerasecret --> for root user and backup user
.....
tls:
  ## Enable TLS
 enabled: true
 ## Name of the secret that contains the certificates
 ##
 ##
 certificatesSecret:  "mariadb-certs"
 ## Certificate filename
 ##
 certFilename: "server-cert.pem"
 ## Certificate Key filename
 ##
 certKeyFilename:  "server-key.pem"
 ## CA Certificate filename
 ##
 certCAFilename:  "ca.pem"
...
## SSL
  ## Use extraVolumes and extraVolumeMounts to mount /certs filesystem
  ssl_ca=/certs/ca.pem
  ssl_cert=/certs/server-cert.pem
  ssl_key=/certs/server-key.pem
  #tls_version=TLSv1.2
  #require_secure_transport=1

  [galera]
  wsrep_on=ON
  wsrep_provider=/opt/bitnami/mariadb/lib/libgalera_smm.so
  wsrep_provider_options="gcache.size=2G;socket.ssl_cert=/certs/server-cert.pem;socket.ssl_key=/certs/server-key.pem;socket.ssl_ca=/certs/ca.pem"

....
xtraVolumes:
 - name: backup
# Backup filesystem
 - name: innodb-relay
# relay_log and relay_log_index directory
 - name: innodb-log-group
# innodb_log_group_home_dir directory
 - name: innodb
#  innodb_data_home_dir filesystem
 - name: log-bin
#  log_bin filesystem
 - name: mariadb-log
#   mariadb.err and slow_query_log
 - name: mariadb-tmp
#   mariadb temp directory
 - name: mariadb-certs
   secret:
     defaultMode: 288
     secretName: mariadb-certs
#
extraVolumeMounts:
 - name: backup
   mountPath: /backup
   readOnly: false
 - name: log-bin
   mountPath: /bitnami/mariadb/innodblog
   readOnly: false
 - name: innodb
   mountPath: /bitnami/mariadb/innodb
   readOnly: false
 - name: innodb-relay
   mountPath: /bitnami/mariadb/innodb/binlog
   readOnly: false
 - name: innodb-log-group
   mountPath: /bitnami/mariadb/innodb/log
   readOnly: false
 - name: mariadb-log
   mountPath: /bitnami/mariadb/log
   readOnly: false
 - name: mariadb-tmp
   mountPath: /bitnami/mariadb/tmp
   readOnly: false
 - name: mariadb-certs
   mountPath: /certs
   readOnly: true
```

### What is the expected behavior?

First primary node works fine.
Second is not able to bootstrap due ssl connection error.
ReplicaCount is set to 3, but this is irrelevant since second  pod never works.

All other custom configs without TLS works fine.

### What do you see instead?
```
[ERROR] WSREP: handshake with remote endpoint ssl://10.42.0.128:4567 failed: asio.ssl:337047686: 'certificate verify failed' ( 337047686: 'error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed')
```
### Additional information

I'm not able to find a proper guide to deploy tls for Galera, it should be good to add some documentation.
