### ISSUE TITLE
Grafana loki compactor PVC doesn't match with volume name in deployment.

### ISSUE THREAD

**Issue by jan-lostak** [bitnami/charts#11097]
### Name and Version

bitnami/grafana-loki 2.1.6

### What steps will reproduce the bug?

Install bitnami/grafana-loki 2.1.6 with custom values and release name "my-release"

### Are you using any custom parameters or values?

```
--set compactor.enabled=true
--set compactor.persistence.enabled=true
```

### What is the expected behavior?

The compactor's PVC should have same name as volume used in compactor deployment.

Rendered [grafana-loki](https://github.com/bitnami/charts/tree/master/bitnami/grafana-loki)/[templates](https://github.com/bitnami/charts/tree/master/bitnami/grafana-loki/templates)/[compactor](https://github.com/bitnami/charts/tree/master/bitnami/grafana-loki/templates/compactor)/pvc.yaml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-release-grafana-loki-compactor
  namespace: loki
...
```

Rendered [grafana-loki](https://github.com/bitnami/charts/tree/master/bitnami/grafana-loki)/[templates](https://github.com/bitnami/charts/tree/master/bitnami/grafana-loki/templates)/[compactor](https://github.com/bitnami/charts/tree/master/bitnami/grafana-loki/templates/compactor)/deployment.yaml

```
...
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: my-release-grafana-loki-compactor
...
```

### What do you see instead?

The compactor PVC created by HELM chart has wrong name:

Rendered [grafana-loki](https://github.com/bitnami/charts/tree/master/bitnami/grafana-loki)/[templates](https://github.com/bitnami/charts/tree/master/bitnami/grafana-loki/templates)/[compactor](https://github.com/bitnami/charts/tree/master/bitnami/grafana-loki/templates/compactor)/pvc.yaml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-release-grafana-loki
  namespace: loki
...
```

Rendered [grafana-loki](https://github.com/bitnami/charts/tree/master/bitnami/grafana-loki)/[templates](https://github.com/bitnami/charts/tree/master/bitnami/grafana-loki/templates)/[compactor](https://github.com/bitnami/charts/tree/master/bitnami/grafana-loki/templates/compactor)/deployment.yaml

```
...
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: my-release-grafana-loki-compactor
...
```

### Additional information

I propose to change [grafana-loki](https://github.com/bitnami/charts/tree/master/bitnami/grafana-loki)/[templates](https://github.com/bitnami/charts/tree/master/bitnami/grafana-loki/templates)/[compactor](https://github.com/bitnami/charts/tree/master/bitnami/grafana-loki/templates/compactor)/pvc.yaml object name from `{{ include "common.names.fullname" . }}` to `{{ include "grafana-loki.compactor.fullname" . }}`.
