### ISSUE TITLE
Enable metrics with auth on solr chart based on the new prometheus-exporter feature

### ISSUE THREAD

**Issue by xrow** [bitnami/charts#11125]
### Name and Version

bitnami/solr latest

### What is the problem this feature will solve?

The chart currently doesn`t support metrics when there is auth enabled. https://github.com/bitnami/charts/blob/master/bitnami/solr/templates/metrics-deployment.yaml#L1

Due a the feature in the prometheus-exporter https://issues.apache.org/jira/browse/SOLR-12584 it is possible now to have that functionality, but the chart doesn`t reflect this change.

I would like to see this as a feature of the solr chart. 

### What is the feature you are proposing to solve the problem?

Have metrics on a secure solr

### What alternatives have you considered?

None

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. If it is adding a flag in the metrics deployment, would you like to submit a PR with the feature?

**Comment by rafariossaa** [comment]
Hi @xrow , 
  Would this work for you ?

**Comment by xrow** [comment]
@rafariossaa I can confirm it is wokring.

I do not know it is smart to have scrape enabled by default? Currently it isn`t.

```
  metrics:
    enabled: true
    # @TODO Remove with solr 9
    configFile: "/opt/bitnami/solr/contrib/prometheus-exporter/conf/solr-exporter-config.xml"
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    podAnnotations:
      prometheus.io/scrape: 'true'
```
