### ISSUE TITLE
 unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend

### ISSUE THREAD

**Issue by rezuma** [bitnami/charts#11120]
### Name and Version

bitnami/keycloak

### What steps will reproduce the bug?

Trying to install Keycloak latest chart on AWS EKS
When adding extrapaths like this
```
  extraPaths:
  - path: /*
    backend:
      serviceName: ssl-redirect
      servicePort: use-annotation
```

I get the following error

### What do you see instead?

```
upgrade.go:139: [debug] preparing upgrade for keycloak
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]
helm.go:88: [debug] error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]
helm.sh/helm/v3/pkg/kube.scrubValidationError
	helm.sh/helm/v3/pkg/kube/client.go:631
helm.sh/helm/v3/pkg/kube.(*Client).Build
	helm.sh/helm/v3/pkg/kube/client.go:204
helm.sh/helm/v3/pkg/action.validateManifest
	helm.sh/helm/v3/pkg/action/upgrade.go:527
helm.sh/helm/v3/pkg/action.(*Upgrade).prepareUpgrade
	helm.sh/helm/v3/pkg/action/upgrade.go:256
helm.sh/helm/v3/pkg/action.(*Upgrade).RunWithContext
	helm.sh/helm/v3/pkg/action/upgrade.go:140
main.newUpgradeCmd.func2
	helm.sh/helm/v3/cmd/helm/upgrade.go:200
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
	runtime/proc.go:225
runtime.goexit
	runtime/asm_amd64.s:1371
UPGRADE FAILED
main.newUpgradeCmd.func2
	helm.sh/helm/v3/cmd/helm/upgrade.go:202
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
	runtime/proc.go:225
runtime.goexit
	runtime/asm_amd64.s:1371
```

**Comment by javsalgar** [comment]
Hi,

Could you share the kubernetes version that you are using? Could you show the rendered YAML as well for the ingress rule?

**Comment by rezuma** [comment]
Hi Javier,

The K8s version is v1.21.12
`# Source: keycloak/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-9.3.4
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: keycloak
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:xxxxxxxxxxx:certificate/ba77ba13-625f-45a1-97b9-4ff16ebbdbff
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: "alb"
  rules:
    - host: "auth.domain.com"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: keycloak
                port:
                  name: http
`

I have remove the domain and account number.
Por cierto, paisano de Sevilla aqui tambien, aunque ya llevo 20 anios en EEUU

**Comment by rezuma** [comment]
I forgot to share the new ingress rule.
I have the deployment on EKS behind an AWS ALB with an ACM cert.
The tls termination is on the ALB, the pod is exposing port 8080 and 8443 but the app only working on 8080.
I am trying to see if using redirect rule will fix the 502 that I am getting when trying to access keycloak through the https ALB

````
spec:
  ingressClassName: "alb"
  rules:
    - host: "auth.domain.com"
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: keycloak
                port:
                  name: httpspec:

```

**Comment by javsalgar** [comment]
Hi,

I believe that the validation issue is because you were using a deprecated syntax for the ingress rule

```
  extraPaths:
    - path: /*
      pathType: ImplementationSpecific
      backend:
        service:
          name: ssl-redirect
          port:
            name: use-annotation
```

This should avoid the validation issue.

PS: Un gusto saludarte paisano!
