### ISSUE TITLE
Initial Admin user not created because auth.adminUser creates the wrong env name for keycloak

### ISSUE THREAD

**Issue by rezuma** [bitnami/charts#11193]
### Name and Version

CHART NAME: keycloak CHART VERSION: 9.4.0 APP VERSION: 18.0.2

### What steps will reproduce the bug?

auth.adminUser creates the env var in the container KEYCLOAK_ADMIN_USER but the env name that Keycloak is expecting is KEYCLOAK_ADMIN, as a result the chart doesnt add the initial admin user.
A way around this is not use auth values from the chart and use instead extraEnvs
```

extraEnvVars:
  - name: KEYCLOAK_ADMIN
    value: "admin"
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: whateverpasswordyoulike


```

### Are you using any custom parameters or values?

```
 auth:
   adminUser: user
   adminPassword: "dsadasdas"
   managementUser: manager
   managementPassword: "asdasdasdasd"
```

```
extraEnvVars:
  - name: KEYCLOAK_ADMIN
    value: "admin"
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: ds,jfsdkjfsd
```

### What do you see instead?

It creates the wrong Env Var in the container
