### ISSUE TITLE
Minio incorrect totalDrives validator 

### ISSUE THREAD

**Issue by R-omk** [bitnami/charts#11202]
### Name and Version

bitnami/minio 11.7.10

### What steps will reproduce the bug?

Specify the number of replicas not a multiple of 4 and greater than 4 when installing in distributed mode.

### Are you using any custom parameters or values?

```yaml
mode: distributed
statefulset:
  replicaCount: 6
  zones: 1
  drivesPerNode: 1
```

### What is the expected behavior?

The minio cluster will start without problems with size of erasure set is 3. (See how it is calculated from the links in the additional information sections.)  

Or the size of erasure set could be 2 if I specify it explicitly

```yaml
  extraEnvVars:
    - name: MINIO_STORAGE_CLASS_STANDARD
      value: 'EC:2'
```

### What do you see instead?

Validation error which contains text accessible by link:
https://github.com/bitnami/charts/blame/fc8ecc/bitnami/minio/templates/_helpers.tpl#L211

### Additional information

https://docs.min.io/minio/baremetal/concepts/erasure-coding.html
https://min.io/product/erasure-code-calculator?ref=docs
