### ISSUE TITLE
[bitnami/mongodb] MongoDB CrashLoopBackOff on EKS while upgrade helm from 12.0.0 to latest version 12.1.26

### ISSUE THREAD

**Issue by chary1112004** [bitnami/charts#11213]
### Name and Version

bitnami/mongodb 12.1.26

### What steps will reproduce the bug?

1. Install mongodb helm chart **12.0.0**, mongodb version **5.0.8** -> In this version, there is no metric prometheus mongodb then we would like to try to upgrade helm chart & mongodb to latest version
2. Upgrade mongodb helm latest version **12.1.26**, mongodb version **5.0.9-debian-11-r3** -> Upgrade fail as below log
```
{"t":{"$date":"2022-07-18T03:37:08.964+00:00"},"s":"I",  "c":"REPL_HB",  "id":23974,   "ctx":"ReplCoord-1","msg":"Heartbeat failed after max retries","attr":{"target":"mongodb-arbiter-0.mongodb-arbiter-headless.dev-mongodb-5.svc.cluster.local:27017","maxHeartbeatRetries":2,"error":{"code":94,"codeName":"NotYetInitialized","errmsg":"Received heartbeat while still initializing replication system"}}}
{"t":{"$date":"2022-07-18T03:37:08.970+00:00"},"s":"I",  "c":"REPL_HB",  "id":23974,   "ctx":"ReplCoord-5","msg":"Heartbeat failed after max retries","attr":{"target":"mongodb-arbiter-0.mongodb-arbiter-headless.dev-mongodb-5.svc.cluster.local:27017","maxHeartbeatRetries":2,"error":{"code":94,"codeName":"NotYetInitialized","errmsg":"Received heartbeat while still initializing replication system"}}}
{"t":{"$date":"2022-07-18T03:37:10.972+00:00"},"s":"I",  "c":"REPL_HB",  "id":23974,   "ctx":"ReplCoord-3","msg":"Heartbeat failed after max retries","attr":{"target":"mongodb-arbiter-0.mongodb-arbiter-headless.dev-mongodb-5.svc.cluster.local:27017","maxHeartbeatRetries":2,"error":{"code":94,"codeName":"NotYetInitialized","errmsg":"Received heartbeat while still initializing replication system"}}}
{"t":{"$date":"2022-07-18T03:37:12.974+00:00"},"s":"I",  "c":"REPL_HB",  "id":23974,   "ctx":"ReplCoord-0","msg":"Heartbeat failed after max retries","attr":{"target":"mongodb-arbiter-0.mongodb-arbiter-headless.dev-mongodb-5.svc.cluster.local:27017","maxHeartbeatRetries":2,"error":{"code":94,"codeName":"NotYetInitialized","errmsg":"Received heartbeat while still initializing replication system"}}}
{"t":{"$date":"2022-07-18T03:37:14.976+00:00"},"s":"I",  "c":"REPL_HB",  "id":23974,   "ctx":"ReplCoord-2","msg":"Heartbeat failed after max retries","attr":{"target":"mongodb-arbiter-0.mongodb-arbiter-headless.dev-mongodb-5.svc.cluster.local:27017","maxHeartbeatRetries":2,"error":{"code":94,"codeName":"NotYetInitialized","errmsg":"Received heartbeat while still initializing replication system"}}}
{"t":{"$date":"2022-07-18T03:37:20.110+00:00"},"s":"W",  "c":"NETWORK",  "id":4615610, "ctx":"conn23","msg":"Failed to check socket connectivity","attr":{"error":{"code":6,"codeName":"HostUnreachable","errmsg":"Connection closed by peer"}}}
{"t":{"$date":"2022-07-18T03:37:20.110+00:00"},"s":"W",  "c":"QUERY",    "id":20478,   "ctx":"conn23","msg":"getMore command executor error","attr":{"error":{"code":279,"codeName":"ClientDisconnect","errmsg":"operation was interrupted because a client disconnected"},"stats":{"stage":"COLLSCAN","nReturned":3,"works":33,"advanced":3,"needTime":15,"needYield":0,"saveState":15,"restoreState":14,"isEOF":0,"direction":"forward","minRecord":7121551433173827585,"docsExamined":3},"cmd":{"getMore":379020024493429892,"collection":"oplog.rs","batchSize":13981010,"maxTimeMS":5000,"term":3,"lastKnownCommittedOpTime":{"ts":{"$timestamp":{"t":1658115394,"i":1}},"t":2}}}}
```

### What is the expected behavior?

I expect it is upgraded successfully

### What do you see instead?

Replica mongo-1 is crashed
![image](https://user-images.githubusercontent.com/76929085/179443701-cbfdfa26-4599-4ecf-970d-6ab7b415367d.png)

### Additional information

I have tested additional cases
- helm chart **12.1.24**, mongodb **5.0.9-debian-11-r1**: It is upgraded successfully
- helm chart **12.1.25**, mongodb **5.0.9-debian-11-r3**: It is upgraded fail -> So I suppose version fail start from this one

**Comment by chary1112004** [comment]
Thanks @fmulero then I keep this issue opens as it is reproduced.

**Comment by cschockaert** [comment]
Hello, got exactly the same problem here, so we reverted to the 12.1.24.
Thanks :)

**Comment by WilliamJauffret** [comment]
Hello, got the same issue here. I had to revert to the 12.1.24 version. 

Thanks :)

**Comment by fmulero** [comment]
New [version of mongodb-exporter](https://github.com/percona/mongodb_exporter/compare/v0.32.3...v0.33.0#diff-c722ac09a12b0798d4b56729c7f9c7236651f195ea1d3ee985db75543d5ce219R328) is only handling `/metrics` path.

We are going to release a new version fixing this issue. In the meantime you can workaround this issue disabling  `metrics.livenessProbe.enabled` and setting  `metrics.customLivenessProbe`

**Comment by jmvizcainoio** [comment]
Added to values.yaml

```
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false
    customLivenessProbe:
      failureThreshold: 3
      httpGet:
        path: /metrics
        port: metrics
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    customReadinessProbe:
      failureThreshold: 3
      httpGet:
        path: /metrics
        port: metrics
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
```


and it works!!!!
