### ISSUE TITLE
[bitnami/mongodb] MongoDB CrashLoopBackOff on OpenShift

### ISSUE THREAD

**Issue by braghettos** [bitnami/charts#11223]
### Name and Version

bitnami/mongodb 12.1.26

### What steps will reproduce the bug?

In OpenShift 4.8, install MongoDB via helm chart.

### Are you using any custom parameters or values?

Thesere are values used for the Helm chart:

```
              auth:
                databases:
                - test
                usernames:
                - test
              volumePermissions:
                securityContext:
                  runAsUser: "auto"
              podSecurityContext:
                enabled: false
              containerSecurityContext:
                enabled: false
              shmVolume:
                chmod:
                  enabled: false
```

### What is the expected behavior?

Pod running.

### What do you see instead?

Pod in CrashLoopBackOff.

### Additional information

Probably a probe fails to be validated: an error that I see in the pod logs is:

`SignalHandler - Received signal - signal:15, error: terminated`
