### ISSUE TITLE
Keycloak 18.0.2 - dreaded too many redirects

### ISSUE THREAD

**Issue by wenslauw** [bitnami/charts#11231]
### Name and Version

bitnami/keycloak

### What steps will reproduce the bug?

I run the chart with a replicaCount of 2. SSL is terminated at the ingress.

### Are you using any custom parameters or values?
```
replicaCount: 2
proxy: edge
auth:
  adminUser: admin
  adminPassword: "password"
  createAdminUser: true
  managementUser: manager
  managementPassword: "password"
serviceDiscovery:
  enabled: true
proxyAddressForwarding: true
ingress:
  enabled: true
  hostname: auth.bla.com
  ingressClassName: "ingress-name"
  tls: true
  annotations: {
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  }
tls:
  enabled: true
  autoGenerated: true
service:
  type: ClusterIP
rbac:
  create: true
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - keycloak
        topologyKey: "kubernetes.io/hostname"
extraEnvVars:
  - name: KEYCLOAK_PRODUCTION
    value: "true"
  - name: KC_HOSTNAME
    value: "auth.bla.com"
  - name: KEYCLOAK_EXTRA_ARGS
    value: "--auto-build"
```

### What is the expected behavior?

I expect to be logged in....

### What do you see instead?

I get it to run, get the login page, but when I submit the login form, I get a lot of redirects and then Firefox ends with a page saying:"The page isn't redirecting properly"

**Comment by wenslauw** [comment]
Well, that fixed it for one login...

**Comment by rafariossaa** [comment]
Hi @wenslauw ,
  Not sure after changing the annotation which is the status of this issue. Is it solved ?

**Comment by wenslauw** [comment]
No, I could login once for some reason, but after that kept getting the too many redirects error. It works when my replicaCount is 1, but I would like to have two pods.

**Comment by wenslauw** [comment]
It seems proxyAddressForwarding is no longer used in the helm chart, so I added that setting to the extraEnvVars, but that didn't do the trick either.

  - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
    value: "true"

**Comment by rafariossaa** [comment]
Hi, in that case, I would suggest you to ask in keycloak forums. I think they could provide better hints for this.

**Comment by duhow** [comment]
https://github.com/bitnami/charts/tree/master/bitnami/keycloak#use-with-ingress-offloading-ssl
> If your ingress controller has the SSL Termination, you should set `proxy` to `edge`.

**Comment by rafariossaa** [comment]
Thanks @duhow . 
@wenslauw could you try that ?

**Comment by Woudan** [comment]
@rafariossaa @duhow Looks like he already set the param to edge.
```
replicaCount: 2
proxy: edge
```

I'm also running into the same issue with the param set. I will investigate it a bit further.

**Comment by rafariossaa** [comment]
Thanks Woudan, don't hesitate to come back and share your findings.

**Comment by jack1902** [comment]
You most likely need to use:
```yaml
  # https://www.keycloak.org/server/caching
  # Required if the --cache-stack=kubernetes
  - name: JAVA_OPTS
    value: "-Djgroups.dns.query=keycloak-headless.keycloak"
```

Note: The `value` above is the headless k8s service address and namespace within the cluster

I had similar issues previously when upgrading to kc17 as documented here: https://github.com/bitnami/charts/issues/10236#issuecomment-1128858062

**Comment by rafariossaa** [comment]
Thanks for sharing.

**Comment by patrickbeam** [comment]
I ran into this issue very recently as well. Thanks for all of this information @jack1902 .  In my case, none of the above solved my issue.  I have the following configuration.
AWS ELB --> Nginx Ingress --> Kubernetes Service --> Keycloak Pods.
For some reason, I had set the ELB to listen on TCP and not HTTP.  This was my issue as the proper headers don't get passed to Nginx.  The following AWS doc talks about the different listener configurations. https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/using-elb-listenerconfig-quickref.html

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/1314271/187083298-d0f82420-6627-4c65-b4ef-a8396ae57dcd.png">

**Comment by kfern** [comment]
@f4z3r How do you enabled the cache? Do you have a complete example?

**Comment by f4z3r** [comment]
@kfern you can just set the `cache.enabled` value to `true`. This seems to be an issue with round-robin LB when using a setup with several instances, i.e `replicaCount` not `1` (it will create a new cookie when going on a new pod and then redirect - this is an infinite loop if you do not accidentally end up going onto the same pod twice in a row). I _think_ setting `cache.enabled` will cache session cookies across the Keycloak instances, so that they are aware of each others sessions (solving the infinite loop).

**Comment by patrickbeam** [comment]
> @f4z3r How did you enable the cache? Do you have a complete example?

Assuming you are using the helm chart, you need the following values to enable caching. 

```
extraEnvVars:
   - name: KC_CACHE_STACK
     value: "kubernetes"
   - name: JAVA_OPTS
     value: "-Djgroups.dns.query=release-name-keycloa-headless"
   - name: KC_HOSTNAME
     value: "keycloak.example.com"
   - name: KC_HOSTNAME_STRICT
     value: "true"
   - name: KC_HOSTNAME_STRICT_HTTPS
     value: "false"
   - name: KEYCLOAK_PRODUCTION
     value: "true"
   - name: KEYCLOAK_EXTRA_ARGS
     value: --auto-build
```

**Comment by kfern** [comment]
@f4z3r @patrickbeam Thank you!!

cache.enabled: true solves this problem, but we need to add what @patrickbeam comments to make keycloak work in production mode.  I'll try it later

```yaml
# ha-config-values.yaml
service:
  type: ClusterIP
ingress:
  enabled: true
  hostname: auth.localtest.me
replicaCount: 2
cache:
  enabled: true
```

``` bash
k3d cluster create --api-port 6550 -p "80:80@loadbalancer" --agents 2

helm install my-release bitnami/keycloak -f ha-config-values.yaml 

...wait a few minutes...

echo Keycloak URL: http://auth.localtest.me/
echo Username: user
echo Password: $(kubectl get secret my-release-keycloak -o jsonpath="{.data.admin-password}" | base64 -d)
```

**Comment by kfern** [comment]
Hi @patrickbeam. Keycloak doesn't start with this env values. Any idea? 

> extraEnvVars:
>    - name: KC_CACHE_STACK
>      value: "kubernetes"
>    - name: JAVA_OPTS
>      value: "-Djgroups.dns.query=release-name-keycloa-headless"
>    - name: KC_HOSTNAME
>      value: "keycloak.example.com"
>    - name: KC_HOSTNAME_STRICT
>      value: "true"
>    - name: KC_HOSTNAME_STRICT_HTTPS
>      value: "false"
>    - name: KEYCLOAK_PRODUCTION
>      value: "true"
>    - name: KEYCLOAK_EXTRA_ARGS
>      value: --auto-build
> 

```bash
kubectl logs -n default my-release-keycloak-0 

keycloak 18:17:38.15 
keycloak 18:17:38.15 Welcome to the Bitnami keycloak container
keycloak 18:17:38.15 Subscribe to project updates by watching https://github.com/bitnami/containers
keycloak 18:17:38.15 Submit issues and feature requests at https://github.com/bitnami/containers/issues
keycloak 18:17:38.15 
keycloak 18:17:38.15 INFO  ==> ** Starting keycloak setup **
keycloak 18:17:38.16 INFO  ==> Validating settings in KEYCLOAK_* env vars...
keycloak 18:17:38.16 ERROR ==> You need to have TLS enabled. Please set the KEYCLOAK_ENABLE_TLS variable to true
```

**Comment by patrickbeam** [comment]
What version of Keycloak are you running?  

One thing to check in the values.yaml file.  Ensure that TLS is not enabled.

```  
tls:
    ## @param auth.tls.enabled Enable TLS encryption. Required for HTTPs traffic.
    ##
    enabled: false
```

In the rendered YAML that will look like this. 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-env-vars
data:
  KEYCLOAK_ENABLE_TLS: "false"
```

**Comment by patrickbeam** [comment]
What version of Keycloak are you running?  

One thing to check in the values.yaml file.  Ensure that TLS is not enabled.

```  
tls:
    ## @param auth.tls.enabled Enable TLS encryption. Required for HTTPs traffic.
    ##
    enabled: false
```

In the rendered YAML that will look like this. 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-env-vars
data:
  KEYCLOAK_ENABLE_TLS: "false"
```
