### ISSUE TITLE
additional labels are not getting created for serviceMonitor resource

### ISSUE THREAD

**Issue by rhollins** [bitnami/charts#11234]
### Name and Version

bitnami/nginx-ingress-controller:9.1.25

### What steps will reproduce the bug?

install helm chart with custom values file

### Are you using any custom parameters or values?

```yaml
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus
```

### What is the expected behavior?

Servicemonitor resource called "ingress-nginx-nginx-ingress-controller" should have extra label: `release: prometheus`

### What do you see instead?

no label 

### Additional information

Currently, I manually patch resource:
```
kubectl label servicemonitors.monitoring.coreos.com ingress-nginx-nginx-ingress-controller release=prometheus --overwrite
```

**Comment by carrodher** [comment]
I'm not able to reproduce the issue, please see below the steps I followed:

1. Use this `values.yaml` file
```yaml
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus
```
2. Use the latest Helm chart available
```console
$ helm repo update bitnami
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈

$ helm search repo bitnami/nginx-ingress
NAME                            	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/nginx-ingress-controller	9.2.20       	1.3.0      	NGINX Ingress Controller is an Ingress controll...
```
3. Render the k8s manifests by using `helm template`
```console
$ helm template bitnami/nginx-ingress-controller -f myvalues.yaml --generate-name
```
4. Check how the `release: prometheus` label is present in the `kind: ServiceMonitor` manifest
```yaml
# Source: nginx-ingress-controller/templates/controller-servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: release-name-nginx-ingress-controller
  namespace: "default"
  labels:
    app.kubernetes.io/name: nginx-ingress-controller
    helm.sh/chart: nginx-ingress-controller-9.2.20
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    release: prometheus
  annotations:
spec:
  jobLabel: ""
  endpoints:
    - port: metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-ingress-controller
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: metrics
```
