### ISSUE TITLE
Argo CronWorkflow unknown time zone

### ISSUE THREAD

**Issue by leonidas-o** [bitnami/charts#11241]
### Name and Version

bitnami/argo-workflows 2.3.4 and 2.3.5

### What steps will reproduce the bug?

Issue was opened in argo-workflows repo:
https://github.com/argoproj/argo-workflows/issues/9091

Using argo-workflows 3.3.8 with a timezone setup was working for others. Assumption that something may be broken on bitnamis side.

As soon as I add timezone e.g: "Europe/Zurich" the workflow is not generated out of the cron workflow. When I remove it, all works fine, then I add back the timezone, it shows and also counts (countdown) correctly inside the UI, but it is not creating a workflow.

```
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep error
time="2022-07-01T13:43:18.420Z" level=error msg="could not schedule CronWorkflow" cronWorkflow=MYNAMESPACE/MY-cron-workflow error="provided bad location Europe/Zurich: unknown time zone Europe/Zurich"
```

### Are you using any custom parameters or values?

adapted values in `values.yaml`:
```yaml
global:
  imageRegistry: "harbor.my-domain/proxy"
baseHref: /argoworkflows/
workflows:
  serviceAccount:
    create: true
postgresql:
  enabled: false
externalDatabase:
  enabled: true
  type: "postgresql"
  host: my-hostname-postgresql
  port: 5432
  username: argoworkflows
  password: ""
  database: argoworkflows
  existingSecret: "argo-workflows"
```

### What is the expected behavior?

If timezone is set, that it creates the workflow out of the cron workflow like it already does when not using a timezone.

### What do you see instead?

Countdown is using the correct time, but the workflow is not created. Nothing happens.
