### ISSUE TITLE
[bitnami/postgresql] readiness probe succeeds before initdb.scripts are done

### ISSUE THREAD

**Issue by teleivo** [bitnami/charts#11263]
### Name and Version

bitnami/postgresql 11.0.4

### What steps will reproduce the bug?

1. Create a DB pod using bitnami/postgresql 11.0.4
2. With a primary.initdb.scripts. Note that the script will need to take a while, otherwise it will be hard for you to see/test the readiness probe as you'll not have enough time 😅 
3. kubectl describe pod <yourpod>

```
    Readiness:  exec [/bin/sh -c -e exec pg_isready -U <youruser> -d "dbname=<yourdbname>" -h 127.0.0.1 -p 5432
[ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
] delay=5s timeout=5s period=10s #success=1 #failure=6
```

4. Execute the following in the pod

You will need to have enough time to execute the `pg_isready` and the file tests separately and see `pg_isready` succeeding

```sh
/bin/sh -c -e exec pg_isready -U <youruser> -d "dbname=<yourdbname>" -h 127.0.0.1 -p 5432
echo $?
```

while the files that are created after the initdb.scripts are done are not yet present

```sh
ls -l /opt/bitnami/postgresql/tmp/.initialized
ls -l /bitnami/postgresql/.initialized
```

### Are you using any custom parameters or values?

https://github.com/dhis2-sre/im-manager/blob/3136e4f0ce0398ef1b9d2a86ff0bf3e6e658b336/stacks/dhis2/helmfile.yaml#L54-L87

### What is the expected behavior?

I assume the readiness probe should only report success when the DB is ready to accept connections and the initdb.scripts finished successfully.

### What do you see instead?

The readiness probe reports success as soon as the `pg_isready` portion of the readiness probe is executed successfully. Meanwhile I can see my `initdb.scripts` still creating tables, indexes, ...

### Additional information

Thanks a lot for these great charts 😄 

## Potential fix

I think the readiness probe is missing an `&&` between `pg_isready` and the file tests. If I reuse the readiness probe from the chart and add the `&&` in a `customReadinessProbe`

```yaml
          readinessProbe:
            enabled: false
          customReadinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - |
                  exec pg_isready -U {{ env "DATABASE_USERNAME" }} -d "dbname={{ env "DATABASE_NAME" }}" -h 127.0.0.1
                  && [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
```

the DB pod is only ready when the initdb.scripts are done. I assume if what I experience is indeed a bug and the suggestion makes sense it could be added in https://github.com/bitnami/charts/blob/7e4a21b0efb68ca2f1c0996970155efc87e6e4d0/bitnami/postgresql/templates/_helpers.tpl#L280

## pg_isready

Adding this here since its related to the readiness probe command in the chart. I am unsure if its a bug of the chart itself. It might be useful for others to know at least 😄 

`pg_isready` exits with 0 if it can connect to postgres but the DB does not exist. So `pg_isready -d postgres://127.0.0.1/foo` exits with 0 while `psql postgres://127.0.0.1/foo` would not if DB foo does not exist. See https://dba.stackexchange.com/questions/298643/monitoring-a-specific-database-with-pg-isready

So maybe something like `psql --no-password --quiet --username user postgres://127.0.0.1/dbname -p 5432 --command "SELECT 'ok'" > /dev/null` would be more truthful. The password would then need to be present in `PGPASSWORD` or in a pgpass file.

## user_scripts_initialized file

File `/bitnami/postgresql/.user_scripts_initialized` is also created after the initdb.scripts are done. Not sure if that one should be part of the probes.
