### ISSUE TITLE
Keycloak and my own SSL certificates. Ingress doesn't have block tls: after install.

### ISSUE THREAD

**Issue by tanatonaut** [bitnami/charts#11316]
### Name and Version

bitnami/keycloak 7.1.10

### What steps will reproduce the bug?

1. Environment  - 
Kubernetes V1.23
CHART NAME: keycloak
CHART VERSION: 7.1.10
APP VERSION: 16.1.1

2. Default values.yaml config except few parameters below.
3. 
```
helm pull bitnami/keycloak --untar
helm install -f values.yaml keycloak ./keycloak --dry-run
```
4. Don't see "tls" block in ingress manifest.

### Are you using any custom parameters or values?

**VARIANT 1**
```
ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: keycloak.mydomain.com
  path: /auth/realms/.*/protocol
  servicePort: https
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: https
    nginx.ingress.kubernetes.io/use-regex: "true"
  tls: true
  secrets:
  - name: keycloak.mydomain.com-tls
    certificate: -----BEGIN CERTIFICATE-----MIIGKj<omitted>
    key: -----BEGIN PRIVATE KEY-----MIIE<omitted>
```
In this case secret was created correct but it didn't matter because ingress didn't have a tls block after install.
    
**VARIANT 2**
```
ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: keycloak.mydomain.com
  path: /auth/realms/.*/protocol
  servicePort: https
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: https
    nginx.ingress.kubernetes.io/use-regex: "true"
  tls: true
```
At this moment i already have secret "keycloak.mydomain.com-tls" in my namespace. tls block was not created in ingress afrer install.

### What is the expected behavior?

According to 
https://docs.bitnami.com/kubernetes/apps/keycloak/administration/enable-tls-ingress/

i want to enable HTTPS through my own wildcard certificate.
i have two ways:

**- Generate certificate secrets based on chart parameters.**
If using Helm to manage the certificates based on the parameters, copy these values into the certificate and key values for a given *.ingress.secrets entry.

**- Enable externally generated certificates.**
If managing TLS secrets separately, it is necessary to create a TLS secret with name INGRESS_HOSTNAME-tls (where INGRESS_HOSTNAME is a placeholder to be replaced with the hostname you set using the *.ingress.hostname parameter).

**What is the expected behavior?**
Ingress resource with **tls** block with link on secret in it.
```
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname }}

```

### What do you see instead?

I was tried both variants but no one of them doesn't work for me. 
My ingresses are being created without "tls:" block.

### Additional information

i look at this code in /templates/ingress.yaml
```
  {{- if or (and .Values.ingress.tls (or (include "common.ingress.certManagerRequest" ( dict "annotations" .Values.ingress.annotations )) .Values.ingress.selfSigned)) .Values.ingress.extraTls }}
  tls:
    {{- if and .Values.ingress.tls (or (include "common.ingress.certManagerRequest" ( dict "annotations" .Values.ingress.annotations )) .Values.ingress.selfSigned) }}
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
    {{- end }}
    {{- if .Values.ingress.extraTls }}
    {{- include "common.tplvalues.render" (dict "value" .Values.ingress.extraTls "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}

```
and I don't see the triggering of this block of code by condition:
**Variant 1**
- Values.ingress.tls = true
and
- Values.ingress.secrets non empty

**Variant 2**
- Values.ingress.tls = true

**Comment by rafariossaa** [comment]
Hi,
  I can see that it is being generated.
  I put your configuration in `user.yaml` and run:
```
$ helm template mykey -f values.yaml -f user.yaml . > rendered.yaml
```
in `rendered.yaml` I can see:
```
apiVersion: networking.k8s.io/v1
kind: Ingress

...

  rules:
    - host: "keycloak.mydomain.com"
      http:
        paths:
          - path: /auth/realms/.*/protocol
            pathType: ImplementationSpecific
            backend:
              service:
                name: mykey-keycloak
                port:
                  name: https
  tls:
    - hosts:
        - "keycloak.mydomain.com"
      secretName: keycloak.mydomain.com-tls
```
and there is a secret named: `keycloak.mydomain.com-tls` that contains the following
```
...
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tTUlJR0tqPG9taXR0ZWQ+
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tTUlJRTxvbWl0dGVkPg==
```
If you decode those strings, they are the given certificate and key:
```
$ echo LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tTUlJR0tqPG9taXR0ZWQ+ | base64 -d
-----BEGIN CERTIFICATE-----MIIGKj<omitted>

$ echo  LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tTUlJRTxvbWl0dGVkPg== | base64 -d
-----BEGIN PRIVATE KEY-----MIIE<omitted>
```

```
