### ISSUE TITLE
Bash script timeout when connecting to Sentinel svc with network policy enabled

### ISSUE THREAD

**Issue by helldweller** [bitnami/charts#11368]
### Name and Version

bitnami/redis 17.0.3

### What steps will reproduce the bug?

Bash script should exit with the error `Could not connect to Redis at redis.redis.svc.cluster.local:26379: Network is unreachable` while first starting pod redis-0
But instead it waits for a connection

### Are you using any custom parameters or values?

Chart.yaml:
```
---
apiVersion: v2
name: redis
description: redis
type: application
version: "17.0.3"
appVersion: "0.0.0"

dependencies:
  - name: redis
    condition: redis.enabled
    version: 17.0.3
    repository: "https://charts.bitnami.com/bitnami"
```
values:
```
---
redis:
  enabled: true
  architecture: replication
  commonConfiguration: |-
    appendonly no
    save ""
    maxmemory 251658240
    maxmemory-policy volatile-ttl
    maxmemory-samples 30
  networkPolicy:
    enabled: true
  auth:
    enabled: false
    sentinel: false
  sentinel:
    enabled: true
    automateClusterRecovery: true
    downAfterMilliseconds: 1500
    failoverTimeout: 3000
    resources:
      requests:
        cpu: "10m"
        memory: "16Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"
    readinessProbe:
      timeoutSeconds: 2
  master:
    # getMasterTimeout: 10
    persistence:
      enabled: false
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "100m"
        memory: "256Mi" # see maxmemory
    readinessProbe:
      timeoutSeconds: 2
  replica:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "100m"
        memory: "256Mi" # see maxmemory
    readinessProbe:
      timeoutSeconds: 2
  metrics:
    enabled: true
    resources:
      requests:
        cpu: "10m"
        memory: "16Mi"
      limits:
        cpu: "50m"
        memory: "32Mi"
    serviceMonitor:
      enabled: false
      namespace: "monitoring"
```

### What do you see instead?

it waiting at that log
` 08:54:24.03 INFO  ==> about to run the command: redis-cli -h redis.redis.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster `

**Comment by migruiz4** [comment]
Hi @helldweller,

I think that issue has been already resolved in version `17.0.4` in this PR https://github.com/bitnami/charts/pull/11298

Could you please update your Redis version and let me know if the issue persists?

**Comment by helldweller** [comment]
This seems to have partially solved the problem. Now it works. But the problem of a long first launch remained. Waiting 220 seconds for the first pod to start is too critical. For myself, I solved this problem like this:
```
sentinel:
  getMasterTimeout: 10
  startupProbe:
    failureThreshold: 2
```
