### ISSUE TITLE
Cert-manager 1.9.0 has regression, and bitnami/cert-manager 0.7.3 still uses 1.9.0 containers

### ISSUE THREAD

**Issue by hosh** [bitnami/charts#11396]
### Name and Version

bitnami/cert-manager 0.7.3

### What steps will reproduce the bug?

1. Install bitnami/cert-manager 0.7.3
2. Apply this issuer:

```yaml
apiVersion: cert-manager.io/v1
 kind: ClusterIssuer
 metadata:
   name: letsencrypt-issuer
 spec:
   acme:
     server: https://acme-staging-v02.api.letsencrypt.org/directory
     email: ops@example.com

     # Name of a secret used to store the ACME account private key
     privateKeySecretRef:
       name: letsencrypt-account-secret
     # ACME DNS-01 provider configurations
     solvers:
     - selector:
         dnsZones:
             - "example.com"
       dns01:
         cnameStrategy: Follow
         route53:
           region: us-east-1           
 ```

### What is the expected behavior?

```
clusterissuer.cert-manager.io/letsencypt-issuer created
```

### What do you see instead?

 
 ```
 Error from server (NotAcceptable): error when creating "letsencypt-issuer.yml": admission webhook "webhook.cert-manager.io" denied the request: spec.acme.solvers[0].dns01.route53: Required value: accessKeyID or accessKeyIDSecretRef is required
 ```

### Additional information

This is because of a regression in 1.9.0 of the admissions webhook: https://github.com/cert-manager/cert-manager/issues/5334
 
 When I override: `controller.acmesolver.image.tag`, `webhook.image.tag`, and `cainjector.image.tag` to the 1.9.1 version, I was able to add the issuer. The 0.7.3 release did not update all of the version tags for the other components of cert-manager.
