### ISSUE TITLE
The Redis-Cluster POD is not created

### ISSUE THREAD

**Issue by isfong** [bitnami/charts#11402]
### Name and Version

bitnami/redis-cluster 8.1.2

### What steps will reproduce the bug?

helmfile.yaml
```yaml
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - namespace: redis
    name: redis-cluster
    chart: bitnami/redis-cluster
    version: 8.1.2
    wait: false
    values:
      - password: redispw
      - redis:
          extraEnvVars:
            - name: TZ
              value: Asia/Shanghai
          startupProbe:
            enabled: true
      - persistence:
          storageClass: redis-cluster.redis.storage.class
      - cluster:
          nodes: 6
          externalAccess:
            enabled: true
            service:
              type: ClusterIP
```
```shell
$ helmfile apply
```

### What do you see instead?

```shell
$ kubectl -n redis get po 
No resources found in redis namespace.

$ kubectl -n redis get svc
NAME                               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)              AGE
redis-cluster                      ClusterIP   10.103.204.35    <none>        6379/TCP             32m
redis-cluster-0-svc                ClusterIP   10.105.165.72    <none>        6379/TCP,16379/TCP   32m
redis-cluster-1-svc                ClusterIP   10.98.156.26     <none>        6379/TCP,16379/TCP   32m
redis-cluster-2-svc                ClusterIP   10.101.159.215   <none>        6379/TCP,16379/TCP   32m
redis-cluster-3-svc                ClusterIP   10.101.4.97      <none>        6379/TCP,16379/TCP   32m
redis-cluster-4-svc                ClusterIP   10.101.45.69     <none>        6379/TCP,16379/TCP   32m
redis-cluster-5-svc                ClusterIP   10.105.100.162   <none>        6379/TCP,16379/TCP   32m
redis-cluster-headless             ClusterIP   None             <none>        6379/TCP,16379/TCP   32m
```
