### ISSUE TITLE
elasticsearch chart don't create ingest pod 

### ISSUE THREAD

**Issue by AlexByNex** [bitnami/charts#11409]
### Name and Version

bitnami/elasticsearch:19.1.2

### What steps will reproduce the bug?

`helm install --namespace esn elasticsearch bitnami/elasticsearch -f values.yaml`

### Are you using any custom parameters or values?

```yaml
global:
  storageClass: "local-storage"
  kibanaEnabled: true

ingest:
  replicaCount: 1

security:
  enabled: true
experience
  elasticPassword: "esadmin"
  tls:
    autoGenerated: true

network:
  publish_host: ${HOSTNAME}
http:
  publish_host: ${HOSTNAME}
transport:
  publish_host: ${HOSTNAME}

extraEnvVars:
  - name: ES_JAVA_OPTS
    value: "-Des.http.cname_in_publish_address=true"
master:
  heapSize: 512m
data:
  heapSize: 3072m
kibana:
  elasticsearch:
    ssl:
      verificationMode: none
    security:
      auth:
        enabled: true
        kibanaUsername: "elastic"
        kibanaPassword: "esadmin"
      tls:
        enabled: true
        existingSecret: elasticsearch-coordinating-only-crt
        usePemCerts: true
```
### What is the expected behavior?

We need to resolve this problem with CSV file import, but ingest pod is not created:
```
[2022-07-27T08:04:16,434][WARN ][r.suppressed             ] [elasticsearch-coordinating-only-1] path: /tst22/_bulk, params: {pipeline=tst22-pipeline, index=tst22}
java.lang.IllegalStateException: There are no ingest nodes in this cluster, unable to forward request to an ingest node.
```
### What do you see instead?
```
root@k8s-mstr-01:/home/efk_config_bitnami# kubectl get po -n esn -o wide
NAME                                    READY   STATUS    RESTARTS   AGE   IP              NODE         NOMINATED NODE   READINESS GATES
elasticsearch-coordinating-only-0       1/1     Running   0          23m   10.233.71.50    k8s-wrk-08   <none>           <none>
elasticsearch-coordinating-only-1       1/1     Running   0          23m   10.233.73.98    k8s-wrk-06   <none>           <none>
elasticsearch-data-0                    1/1     Running   0          23m   10.233.72.108   k8s-wrk-05   <none>           <none>
elasticsearch-data-1                    1/1     Running   0          23m   10.233.74.192   k8s-wrk-07   <none>           <none>
elasticsearch-kibana-6f56bf4859-pk4hx   1/1     Running   0          23m   10.233.67.235   k8s-wrk-03   <none>           <none>
elasticsearch-master-0                  1/1     Running   0          23m   10.233.71.205   k8s-wrk-08   <none>           <none>
elasticsearch-master-1                  1/1     Running   0          23m   10.233.73.153   k8s-wrk-06   <none>           <none>
elasticsearch-master-2                  1/1     Running   0          23m   10.233.71.6     k8s-wrk-08   <none>           <none>
```

### Additional information

Is the ingest pod must run by default?

Thanks a lot for any help.
