### ISSUE TITLE
Elasticsearch rejoining issue

### ISSUE THREAD

**Issue by PrabhuSukumar** [bitnami/charts#11417]
### Name and Version

bitnami/elasticsearch 8.3.2

### What steps will reproduce the bug?

We have deployed Elasticsearch, Kibana & Data nodes with Version 8.3.2 via helm on our EKS Cluster with replica count as 1. Initially the cluster is up & running, and we are able to upload some sample data. To ensure data is getting persist we are trying to recreate the cluster and we are getting below error. Note: We have created dedicated EFS only for data-node as our Persistent Volume. Master & Kibana are using default storage type(EBS)

Error 

This node previously joined a cluster with UUID [fhD_******] and is now trying to join a different cluster with UUID [412****]. This is forbidden and usually indicates an incorrect discovery or cluster bootstrapping configuration. Note that the cluster UUID persists across restarts and can only be changed by deleting the contents of the node's data path [/bitnami/elasticsearch/data] which will also remove any data held by this node.

When we check the documents, They are saying to cleanup /bitnami/elasticsearch/data directory to join the cluster. This works but the sample data which we added is deleted. Could you please let us know how we can fix this issue without deleting the data directory. 

### Are you using any custom parameters or values?
```yaml
global:
  kibanaEnabled: true
  
volumePermissions:
  enabled: true

master: 
  replicaCount: 1
  persistence:
    existingClaim: "elasticsearch-dev-master-data-claim"
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-name1
data: 
  replicaCount: 1
  persistence:
    existingClaim: "elasticsearch-dev-datanode-claim"
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-name1
coordinating: 
  replicaCount: 1
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-name1
ingest: 
  replicaCount: 1
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-name1
security:
  enabled: true
  elasticPassword: "*****"
  tls: 
    autoGenerated: true
kibana:
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-name1
  persistence:
    existingClaim: "elasticsearch-dev-kibana-claim"
  elasticsearch:
    security:
      auth:
        enabled: true
        # default user in the elasticsearch chart is elastic
        kibanaUsername: "kibana_system"
        kibanaPassword: "*****"
        createSystemUser: true
        elasticsearchPasswordSecret: es-elasticsearch
      tls:
        enabled: true
        usePemCerts: true
        existingSecret: es-elasticsearch-coordinating-crt
  ingress: 
    enabled: true 
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      kubernetes.io/ingress.class: nginx
    # pathType: ImplementationSpecific
    pathType: Prefix 
    hostname: "*"
```

### What do you see instead?

Error 

This node previously joined a cluster with UUID [fhD_******] and is now trying to join a different cluster with UUID [412****]. This is forbidden and usually indicates an incorrect discovery or cluster bootstrapping configuration. Note that the cluster UUID persists across restarts and can only be changed by deleting the contents of the node's data path [/bitnami/elasticsearch/data] which will also remove any data held by this node.

**Comment by fmulero** [comment]
Hi @PrabhuSukumar 

Could you edit the custom values and set the right indentation? A `yaml` [block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) could help you

**Comment by migruiz4** [comment]
Hi @PrabhuSukumar,

The cluster is bootstrapped by the master-eligible nodes, is during that process that the cluster UUID is generated.

If you don't persist your master node, each time its data is flushed a new cluster UUID will be generated which means a brand new cluster, so I would highly recommend persisting the information of your master nodes.

I haven't tried, but it would be hypothetically possible to restore the cluster data from a single data node, but the process would be very tedious, manual, and not something you want to perform recurrently, more kind of a disaster recovery method.

> When we check the documents, They are saying to cleanup /bitnami/elasticsearch/data directory to join the cluster. This works but the sample data which we added is deleted. Could you please let us know how we can fix this issue without deleting the data directory.

If you don't have sensitive data stored in the cluster yet, I would recommend removing the volumes and inserting the sample 
data again, but this time persisting the master nodes too.

P.S.: If you are planning to deploy a 1 master, 1 data, 1 coordinating, and 1 ingest deployment, I would suggest trying out the value `master.masterOnly=false`. This way the master-eligible will act as a multi-role node instead of master-only, allowing you to deploy smaller architectures.
E.g.: Single node, 3 multi-role master-elegible nodes, etc.

The bigger your cluster both in number of nodes and data I/O demand, the more you would like to deploy dedicated nodes for better performance.

**Comment by PrabhuSukumar** [comment]
@migruiz4 Thanks for your response. We tried creating dedicated persistent volume for Master & Data nodes. We are getting below error. Could you please assist on this

Please note: We have provided full permission(777) to /data path

org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [/bitnami/elasticsearch/data]; maybe these locations are not writable or multiple nodes were started on the same data path?
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:228) [elasticsearch-8.3.2.jar:?]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67) [elasticsearch-8.3.2.jar:?]
**Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [/bitnami/elasticsearch/data]; maybe these locations are not writable or multiple nodes were started on the same data path?**
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:285) ~[elasticsearch-8.3.2.jar:?]
	at org.elasticsearch.node.Node.<init>(Node.java:438) ~[elasticsearch-8.3.2.jar:?]
	at org.elasticsearch.node.Node.<init>(Node.java:300) ~[elasticsearch-8.3.2.jar:?]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:230) ~[elasticsearch-8.3.2.jar:?]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:230) ~[elasticsearch-8.3.2.jar:?]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-8.3.2.jar:?]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:224) ~[elasticsearch-8.3.2.jar:?]

**Comment by migruiz4** [comment]
Hi @PrabhuSukumar,

Are you using a different `values.yaml` that the one you previously shared?
Could you have configured more than one replica using the same volume? For example:
```
master: 
  replicaCount: 3
  persistence:
    existingClaim: "elasticsearch-dev-master-data-claim"
```

That would cause several Elasticsearch nodes to share the same data path, causing the error you shared.

This could be solved with the following workaround, setting each node to use a subpath of `/bitnami/elasticsearch/data` as its data dir:
```
extraEnvVars:
 - name: ELASTICSEARCH_DATA_DIR_LIST
   value: "/bitnami/elasticsearch/data/$(MY_POD_NAME)"
```

But please be aware that having multiple nodes sharing a single volume would have other implications, affecting high availability, I/O performance, and recovery in case of failure.

**Comment by PrabhuSukumar** [comment]
@migruiz4 We are using single replica's when we use same persistent volume for data & master we are getting below error. 

org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [/bitnami/elasticsearch/data]; maybe these locations are not writable or multiple nodes were started on the same data path?
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:228) [elasticsearch-8.3.2.jar:?]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67) [elasticsearch-8.3.2.jar:?]
**Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [/bitnami/elasticsearch/data]; maybe these locations are not writable or multiple nodes were started on the same data path?**
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:285) ~[elasticsearch-8.3.2.jar:?]
	at org.elasticsearch.node.Node.<init>(Node.java:438) ~[elasticsearch-8.3.2.jar:?]
	at org.elasticsearch.node.Node.<init>(Node.java:300) ~[elasticsearch-8.3.2.jar:?]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:230) ~[elasticsearch-8.3.2.jar:?]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:230) ~[elasticsearch-8.3.2.jar:?]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-8.3.2.jar:?]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:224) ~[elasticsearch-8.3.2.jar:?]

Below is the values.yaml file which we are using

global:
  kibanaEnabled: true

volumePermissions:
  enabled: true

master:
  replicaCount: 1
  persistence:
    existingClaim: "data-volume-cliam"
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-machine
data:
  replicaCount: 1
  persistence:
    existingClaim: "data-volume-cliam"
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-machine
coordinating: 
  replicaCount: 1
  # persistence:
  #   existingClaim: "data-volume-cliam"
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-machine
ingest:
  replicaCount: 1
  # persistence:
  #   existingClaim: "data-volume-cliam"
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-machine
security:
  enabled: true
  elasticPassword: "*****"
  tls: 
    autoGenerated: true
kibana:
  volumePermissions:
    enabled: true
  # persistence:
  #   existingClaim: "data-volume-cliam"
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-machine
  elasticsearch:
    security:
      auth:
        enabled: true
        # default user in the elasticsearch chart is elastic
        kibanaUsername: "****"
        kibanaPassword: "****"
        createSystemUser: true
        elasticsearchPasswordSecret: es-elasticsearch
      tls:
        enabled: true
        usePemCerts: true
        existingSecret: es-elasticsearch-coordinating-crt
  ingress: 
    enabled: true 
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      kubernetes.io/ingress.class: nginx
    # pathType: ImplementationSpecific
    pathType: Prefix 
    hostname: "dev.elasticsearch.analyticalwizards.com"

**Comment by migruiz4** [comment]
The same applies if you use the same volume claim in two different pods with different roles:
```
master:
  persistence:
    existingClaim: "data-volume-cliam"
data:
  persistence:
    existingClaim: "data-volume-cliam"
```

**Comment by PrabhuSukumar** [comment]
@migruiz4 Could you please assist how to fix this ? We need to create two different claim with subpath ?

**Comment by migruiz4** [comment]
Hi @PrabhuSukumar,

I provided the workaround to this issue in my previous response:
```
extraEnvVars:
 - name: ELASTICSEARCH_DATA_DIR_LIST
   value: "/bitnami/elasticsearch/data/$(MY_POD_NAME)"
```

Using that, each elasticsearch node will use `/bitnami/elasticsearch/data/$(MY_POD_NAME)` as its data path, creating a subfolder inside the volume. Otherwise every node mounting the volume will share the same data path, causing the error you are currently seeing.

Adding that to your values should fix the issue and elasticsearch should be able to initialize, but as I previously mentioned please be aware that having multiple nodes sharing a single volume would have other implications, affecting high availability, I/O performance, and recovery in case of failure or accidental removal.

**Comment by PrabhuSukumar** [comment]
@migruiz4 We updated our values.yml as below. Still same error

global:
  kibanaEnabled: true

volumePermissions:
  enabled: true

master:
  replicaCount: 1
  persistence:
    existingClaim: "data-volume-cliam"
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-machine
data:
  replicaCount: 1
  persistence:
    existingClaim: "data-volume-cliam"
  extraEnvVars:
    - name: elasticsearch-data-dir-list
      value: "reportpath"
  extraVolumeMounts:
       - mountPath: /bitnami/elasticsearch/data/data_dir
         name: data
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-machine
coordinating: 
  replicaCount: 1
  # persistence:
  #   existingClaim: "data-volume-cliam"
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-machine
ingest:
  replicaCount: 1
  # persistence:
  #   existingClaim: "data-volume-cliam"
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-machine
security:
  enabled: true
  elasticPassword: "****"
  tls: 
    autoGenerated: true
kibana:
  volumePermissions:
    enabled: true
  # persistence:
  #   existingClaim: "data-volume-cliam"
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-machine
  elasticsearch:
    security:
      auth:
        enabled: true
        # default user in the elasticsearch chart is elastic
        kibanaUsername: "****"
        kibanaPassword: "****"
        createSystemUser: true
        elasticsearchPasswordSecret: es-elasticsearch
      tls:
        enabled: true
        usePemCerts: true
        existingSecret: es-elasticsearch-coordinating-crt
  ingress: 
    enabled: true 
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      kubernetes.io/ingress.class: nginx
    # pathType: ImplementationSpecific
    pathType: Prefix 
    hostname: "dev.elasticsearch.analyticalwizards.com"


Configmap Name: elasticsearch-data-dir-list
Name:         elasticsearch-data-dir-list
Namespace:    elasticsearch-dev
Labels:       <none>
Annotations:  <none>

Data
====
**reportpath:
----
/bitnami/elasticsearch/data/data_dir**

**Comment by migruiz4** [comment]
@PrabhuSukumar Please try the following:
```yaml
global:
  kibanaEnabled: true

volumePermissions:
  enabled: true

extraEnvVars:
 - name: ELASTICSEARCH_DATA_DIR_LIST
   value: "/bitnami/elasticsearch/data/$(MY_POD_NAME)"

master:
  replicaCount: 1
  persistence:
    existingClaim: "data-volume-cliam"
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-machine
data:
  replicaCount: 1
  persistence:
    existingClaim: "data-volume-cliam"
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-machine
coordinating: 
  replicaCount: 1
  # persistence:
  #   existingClaim: "data-volume-cliam"
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-machine
ingest:
  replicaCount: 1
  # persistence:
  #   existingClaim: "data-volume-cliam"
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-machine
security:
  enabled: true
  elasticPassword: "*****"
  tls: 
    autoGenerated: true
kibana:
  volumePermissions:
    enabled: true
  # persistence:
  #   existingClaim: "data-volume-cliam"
  nodeSelector:
    eks.amazonaws.com/nodegroup: dhc-machine
  elasticsearch:
    security:
      auth:
        enabled: true
        # default user in the elasticsearch chart is elastic
        kibanaUsername: "****"
        kibanaPassword: "****"
        createSystemUser: true
        elasticsearchPasswordSecret: es-elasticsearch
      tls:
        enabled: true
        usePemCerts: true
        existingSecret: es-elasticsearch-coordinating-crt
  ingress: 
    enabled: true 
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      kubernetes.io/ingress.class: nginx
    # pathType: ImplementationSpecific
    pathType: Prefix 
    hostname: "dev.elasticsearch.analyticalwizards.com"
```
