### ISSUE TITLE
[thanos] Horizontal Pod Autoscaler doesn't work when sharding StoreGateway

### ISSUE THREAD

**Issue by kmai** [bitnami/charts#11413]
### Name and Version

bitnami/thanos 10.5.3

### What steps will reproduce the bug?

Given a sharded store gateway configuration, only one HorizontalPodAutoscaler is created. This will yield an invalid configuration, because a HPA should be created for each StatefulSet:

```
k get statefulset -n thanos
NAME                    READY   AGE
thanos-storegateway-0   0/1     28d
thanos-storegateway-1   1/1     28d
thanos-storegateway-2   1/1     28d
```

### Are you using any custom parameters or values?

```yaml
storegateway:
  livenessProbe:
    initialDelaySeconds: 600
  readinessProbe:
    initialDelaySeconds: 600
  enabled: true
  serviceAccount:
    existingServiceAccount: thanos-sa
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
  persistence:
    enabled: true
    size: 256Gi
  sharded:
    enabled: true
    timePartitioning:
    # One store for data older than 6 weeks
    - min: ""
      max: -6w
    # One store for data newer than 6 weeks and older than 2 weeks
    - min: -6w
      max: -2w
    # One store for data newer than 2 weeks
    - min: -2w
      max: ""
```

### What is the expected behavior?

The template should contemplate if the `storegateway.sharded.enabled` value is set to `true` and, if so, iterate over the sharding definition to know how many HPAs to create and pointing towards which StatefulSets.

### What do you see instead?

This is the created HPA that doesn't target any StatefulSet on a sharded deployment.

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"False","lastTransitionTime":"2022-06-30T16:16:45Z","reason":"FailedGetScale","message":"the
      HPA controller was unable to get the target''s current scale: statefulsets.apps
      \"thanos-storegateway\" not found"}]'
    meta.helm.sh/release-name: thanos
    meta.helm.sh/release-namespace: thanos
  labels:
    app.kubernetes.io/component: storegateway
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-10.5.3
  name: thanos-storegateway
  namespace: thanos
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: thanos-storegateway
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 0
  desiredReplicas: 0
```

### Additional information

It might be worth adding a map to configure the HPA on each Statefulset because in most use cases, sharding will cause Statefulset sizes to be different, depending on the time periods chosen for the shards.
