### ISSUE TITLE
[bitnami/etcd] auth disabled with auth.rbac.create = true and auth.rbac.rootPassword is set

### ISSUE THREAD

**Issue by blaisewang** [bitnami/charts#11429]
### Name and Version

bitnami/etcd 8.3.4

### What steps will reproduce the bug?

Use bitnami/etcd as a subchart with the following `value.yaml`. 

Sometimes etcd started with authentication disabled. Every time this happened, I found `etcd-0` pods with restart count 1.

I use standalone k3s as the Kubernetes distribution with `rancher.io/local-path` as the default storage-class.

### Are you using any custom parameters or values?

```yaml
etcd:
  enabled: true
  auth:
    rbac:
      create: true
      rootPassword: "n0qy0xFSQ7D5fN8Y"
    token:
      type: simple
  replicaCount: 3
  removeMemberOnContainerTermination: false
```

### What is the expected behavior?

etcd started with auth enabled.

### What do you see instead?

etcd started with auth disabled, and empty user list
