### ISSUE TITLE
[bitnami/rabbitmq] prometheus enabled issue

### ISSUE THREAD

**Issue by muslimcodeid** [bitnami/charts#11448]
### Name and Version

bitnami/rabbitmq-10.1.15

### What steps will reproduce the bug?

1. Enable prometheus using default values
2. Run helm upgrade

### Are you using any custom parameters or values?
```
metrics:
  enabled: true
  plugins: "rabbitmq_prometheus"
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.ports.metrics }}"
  serviceMonitor:
    enabled: true
    namespace: "tools"
    interval: 30s
    labels:
      monitoring-platform: core-prometheus
  prometheusRule:
    enabled: true
    additionalLabels:
      monitoring-platform: core-prometheus 
    namespace: "tools"
    rules:
      - alert: RabbitmqTooManyMessagesInQueue
        expr: rabbitmq_queue_messages_ready{queue="adapter.position.store.queue"} > 1000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Rabbitmq too many messages in queue (instance {{ `{{` }} $labels.instance }}  )
          description: "Queue is filling up (> 1000 msgs)\n  VALUE = {{ `{{` }} $value }}  \n  LABELS = {{ `{{` }} $labels }}"
```

### What is the expected behavior?

Helm Successfully upgraded

### What do you see instead?

Error: UPGRADE FAILED: [unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]
