### ISSUE TITLE
Concourse worker fails to boot ("iptables not found")

### ISSUE THREAD

**Issue by Kitanotori** [bitnami/charts#11516]
### Name and Version

bitnami/concourse 1.3.9

### What steps will reproduce the bug?

`helm install concourse-bitnami . -f myvalues.yaml`

### Are you using any custom parameters or values?

myvalues.yaml:
```
global:
  storageClass: local-path
  web:
    externalUrl: "my.domain"
    logLevel: info
    tsa:
      logLevel: info
    enableAcrossStep: true
    enablePipelineInstances: true
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi
  worker:
    mode: statefulset
    logLevel: info
    baggageclaim:
      driver: overlay
    extraEnvVars:
      - name: CONCOURSE_RUNTIME
        value: containerd
    pdb:
      create: false
    replicaCount: 1
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi
  service:
    web:
      type: ClusterIP
  postgresql:
    auth:
      enablePostgresUser: true
      username: concourse
      password: concourse
      database: concourse
    primary:
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 256Mi
```

### What is the expected behavior?

Concourse worker boots normally

### What do you see instead?

`$ kubectl logs concourse-bitnami-worker-0` :
```
error: containerd garden server runner: failed to create CNI network opts: failed to initialize iptables: exec: "iptables": executable file not found in $PATH
```
