### ISSUE TITLE
Should we reconsider the  * default * resource value in helm charts?

### ISSUE THREAD

**Issue by panpan0000** [bitnami/charts#11555]
### Name and Version

bitnami/mysql

### What steps will reproduce the bug?

Actually,  this issue is a question indeed, hope somebody can help.

In every bitnami chart values.yaml, `resource` blocks are left blank as  a conscious.
( below example is [mysql](https://github.com/bitnami/charts/blob/master/bitnami/mysql/values.yaml) )

```
  ## We usually recommend not to specify default resources and to leave this as a conscious
  ## choice for the user. This also increases chances charts run on environments with little
  ## resources, such as Minikube. If you do want to specify resources, uncomment the following
  ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  ## @param primary.resources.limits The resources limits for MySQL primary containers
  ## @param primary.resources.requests The requested resources for MySQL primary containers
  ##
  resources:
    ## Example:
    ## limits:
    ##    cpu: 250m
    ##    memory: 256Mi
    limits: {}
    ## Examples:
    ## requests:
    ##    cpu: 250m
    ##    memory: 256Mi
    requests: {}
```

But as we know, Kubernetes **doesn't** recommend pods without resource limit/request in production best practice ,otherwise it will make the system unstable .(refer to https://www.youtube.com/watch?v=xjpHggHKm78&t=18s) ( Is this "rule" changed nowadays ?)

I can understand that : to enable pod running on some demo/dev environments like kind/miniKube, "leaving no resource value in values.yaml" does help.
But mostly, people in this community would like to install app in production environment, those people will struggle with a lot of `helm install --set xxx.resources.limit.cpu=250m --set xxx.resources.limit.memory=256Mi  --set xxx.resources.limit.request=250m --set xxx.resources.request.memory=256Mi `.... which is very annoyed and troublesome. "helm install -f " with a yaml file filled with those parameters is neither a connivence way.

If it's true that resource should be specified in production, why don't we uncomment those code block to make production user happy ? For those minukube/kind user, they can uncomment those block by themselves .
Is it a better idea ? 

More over, maybe the chart user in production should worry about the scale size and the resource level (especially for those app cannot be scale-out easily (which means increasing the replica of pod can not solve the problem), example : mySQL in master-slave mode.)

Single default value for resource limit will not suit for every scale and performance.
The tradeoff is something like :
 (1) `default values` as a common scale/performance( for mysql, maybe below 250m can fulfill  average TPS/QPS )
 (2) `comments` to recommend other scale/performance

Below is an illustration. 

```
  # for very high TPS mysql: limit will be up to 2C,1Gi
  # for high TPS mysql: limit will be up 1C, 500Mi

 #
  resources:
     limits:
        cpu: 250m
        memory: 256Mi
    requests:
        cpu: 250m
        memory: 256Mi

```

NOTE:
I didn't suggest to change it for now which request big efforts and incompatible changes.
But I think a lot of bitnami user will be confused with this common question.
So the answers are greatly appreciated.

### What do you see instead?

As state above ,In every bitnami chart values.yaml, `resource` blocks are left blank as  a conscious.
