### ISSUE TITLE
initdbScripts not works

### ISSUE THREAD

**Issue by rerime** [bitnami/charts#11571]
### Name and Version

bitnami/postgres-ha 9.2.5

### What steps will reproduce the bug?

Set values.yaml
```yaml
postgresql:
  image:
    tag: 12.11.0-debian-11-r23
  initdbScripts:
    my_init_script.sh: |
      #!/bin/sh
      echo "Do something."
    users.sql: |
      CREATE USER user06 WITH ENCRYPTED PASSWORD 'pass06';
    init-db.sh: |
      #!/usr/bin/env sh
      psql -U postgres -d postgres -c 'CREATE USER user06 WITH ENCRYPTED PASSWORD $$'pass06'$$;'
      echo blah
      exit
 ```
 
 After boot new instance
` \du` doesn't show new user.  Also no `echo` in logs.

### Are you using any custom parameters or values?

```yaml
postgresql:
  image:
    tag: 12.11.0-debian-11-r23
  initdbScripts:
    my_init_script.sh: |
      #!/bin/sh
      echo "Do something."
    users.sql: |
      CREATE USER user06 WITH ENCRYPTED PASSWORD 'pass06';
    init-db.sh: |
      #!/usr/bin/env sh
      psql -U postgres -d postgres -c 'CREATE USER user06 WITH ENCRYPTED PASSWORD $$'pass06'$$;'
      echo blah
      exit
 ```

### What is the expected behavior?

Run my init-db script

### What do you see instead?

No users
