### ISSUE TITLE
Sonarqube: It's not possible to select the Developer Edition

### ISSUE THREAD

**Issue by rowi1de** [bitnami/charts#11595]
### Name and Version

sonarqube/1.3.0 

### What steps will reproduce the bug?

I use argocd:

```yaml
project: infrastructure
source:
  repoURL: 'https://charts.bitnami.com/bitnami'
  targetRevision: 1.3.0
  helm:
    releaseName: sonarqube
    values: |-
      replicaCount: 1
      service:
        type: ClusterIP
      ingress:
        enabled: false
      extraEnvVarsCM: sonar-config
  chart: sonarqube
destination:
  server: 'https://kubernetes.default.svc'
  namespace: sonarqube
syncPolicy:
  syncOptions:
    - CreateNamespace=true
```

### Are you using any custom parameters or values?

```yaml
replicaCount: 1
resources:
  requests:
    cpu: 200m
    memory: 4Gi
  limits:
    cpu: 500m
    memory: 6Gi
service:
  type: ClusterIP
extraEnvVarsCM: sonar-config
```

```yaml
apiVersion: v1
kind: ConfigMap
data:
  EDITION: developer
metadata:
  creationTimestamp: "2022-08-04T16:19:35Z"
  name: sonar-config
  namespace: sonarqube
```

or overriding
`extraEnvVars["EDITION=developer"]`
will create an invalid Deployment Manifest

### What is the expected behavior?
- The helm chart should have a simple "edition" config flag
- The deployment should pull `sonarqube-<version>-<edition>`

### What do you see instead?

It's always the community edition that is pulled.

### Additional information
- Is it a valid approach to use the chart with a custom image?
```yaml
image:
  repository: sonarqube
  tag: 9.5.0-developer
```
