### ISSUE TITLE
[bitnami/minio] Can't run docker image on Mac with M1 chip

### ISSUE THREAD

**Issue by Mr-Bam** [bitnami/charts#11606]
### Name and Version

bitnami/minio:latest

### Run on
Apple M1 Pro Monterey version 12.3, 2021.

### What steps will reproduce the bug?

1. Added image to docker-compose.yml:
```
minio:
        image: "bitnami/minio:latest"
        environment:
            MINIO_ROOT_USER: "access-key"
            MINIO_ROOT_PASSWORD: "access-secret"
            MINIO_DEFAULT_BUCKETS: "bucket"
```
2. Run docker-compose up.

### What is the expected behavior?

Starting MinIO without failing.

### What do you see instead?

```
minio_1                  | minio 07:11:37.65 INFO  ==> Creating default buckets...
minio_1                  | Bucket created successfully `local/bucket`.
minio_1                  | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
minio_1                  | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
minio_1                  | /opt/bitnami/scripts/libminioclient.sh: line 48:   143 Segmentation fault      [ ${#bucket_info[@]} -eq 2 ]
minio_1                  | minio 07:11:38.92 INFO  ==> MinIO is already stopped...
minio_1                  |  07:11:38.98 INFO  ==> ** MinIO setup finished! **
minio_1                  | 
minio_1                  | minio 07:11:39.10 INFO  ==> ** Starting MinIO **
minio_1                  | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

### Additional information

I tried it on Ubuntu 20.04 with an Intel chip and it works well. My colleagues had a successful result with Mac on Intel chip too.
