### ISSUE TITLE
Unable to run mongodb pods with non-root-group

### ISSUE THREAD

**Issue by HauklandJ** [bitnami/charts#11638]
### Name and Version

bitnami/mongodb/12.1.31

### What steps will reproduce the bug?

Add the chart to a cluster.
Change the values file to the one given below, where runAsGroup is set to 1001.
See that the pods are now stuck in crashloopbackoff.

replica-0 error: 
**/opt/bitnami/scripts/libmongodb.sh: line 758: /opt/bitnami/mongodb/conf/keyfile: Permission denied**

arbiter error:
**mkdir: cannot create directory '/bitnami/mongodb/data/db/': Permission denied**

### Are you using any custom parameters or values?

values.yaml,
**Notice the runAsGroup is not set to default (0=root)**
```
mongodb:
  namespace: namespace
  serviceAccount:
    name: \<name>
  architecture: replicaset
  auth:
    enabled: true
    rootUser: \<user>
    rootPassword: \<password>
    usernames: 
      - \<user>
    passwords: 
      - \<password>
    databases: 
      - Audit
    replicaSetKey: \<rskey>
  containerSecurityContext: 
    capabilities:
      drop:
      - ALL
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    runAsGroup: 1001
    runAsUser: 1001
  arbiter:
    containerSecurityContext:
      enabled: true
      capabilities:
        drop:
        - ALL
      allowPrivilegeEscalation: false
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true
      seccompProfile:
        type: "RuntimeDefault"    
```

### What is the expected behavior?

That the pod is running succesfully

### What do you see instead?

See that the pods are now stuck in crashloopbackoff.

replica-0 error: 
**/opt/bitnami/scripts/libmongodb.sh: line 758: /opt/bitnami/mongodb/conf/keyfile: Permission denied**

arbiter error:
**mkdir: cannot create directory '/bitnami/mongodb/data/db/': Permission denied**

### Additional information

The reason nonRootGroup is important is that the production environment uses kyverno policies which state that no pod is allowed to run with root privileges
