### ISSUE TITLE
[bitnami/jasperreports] Make database type configurable

### ISSUE THREAD

**Issue by Adriien-M** [bitnami/charts#11688]
### Name and Version

bitnami/jasperreports

### What is the problem this feature will solve?

It's not possible to change database type, currently, only MariaDB is available

### What is the feature you are proposing to solve the problem?

In fact, rather than use `MARIADB_HOST` and `MARIADB_PORT_NUMBER` we should use `JASPERREPORTS_DATABASE_HOST` and `JASPERREPORTS_DATABASE_PORT_NUMBER` variables

In this way, we could add a parameter `externalDatabase.type` to specify `JASPERREPORTS_DATABASE_TYPE` and use another database easily

By default, it would remain MariaDB of course!

### What alternatives have you considered?

Currently, I added these variables in `extraEnvVars` and it works, but it's a bit dirty... 
```yaml
externalDatabase:
  host: "postgres-host"
  port: 5432
  user: ""
  password: ""
  database: ""
extraEnvVars: 
  - name: JASPERREPORTS_DATABASE_TYPE
    value: "postgresql"
  - name: JASPERREPORTS_DATABASE_HOST
    value: "$(MARIADB_HOST)"
  - name: JASPERREPORTS_DATABASE_PORT
    value: "$(MARIADB_PORT)"
```
JasperReports support multiple database types so the chart should too...
