### ISSUE TITLE
startFromSnapshot.enabled=true seems to restore only one replica

### ISSUE THREAD

**Issue by pchambre** [bitnami/charts#11697]
### Name and Version

bitnami/etcd 8.3.7

### What steps will reproduce the bug?

Running in a GKE Autopilot cluster
```
Installing with these values in YAML:
replicaCount: 3
auth:
  rbac:
    enabled: true
    rootPassword: mypassword
startFromSnapshot:
  enabled: true
  existingClaim: nfs-pvc-etcdbackup
  snapshotFilename: etcdback.dat
```
I get a StatefulSet with 3 Pods, but, if I connect to the bitnami etcd client Pod and run:
`etcdctl endpoint status  -w table --user="root" --password="mypassword"`

I get:
```
{"level":"warn","ts":"2022-08-09T23:05:53.766Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0002f0700/my-release-etcd.default.svc.cluster.local:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: authentication is not enabled"}
{"level":"warn","ts":"2022-08-09T23:05:53.768Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0002f0700/my-release-etcd.default.svc.cluster.local:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: authentication is not enabled"}
+------------------------------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|                    ENDPOINT                    |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+------------------------------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| my-release-etcd.default.svc.cluster.local:2379 | 2a20d9beebf101c4 |   3.5.4 |   20 kB |      true |      false |         7 |       1700 |               1700 |        |
+------------------------------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
```
If I then connect to each of the etcd Pods and check status, I find one with the restored DB and auth enabled, and the other two with an empty raft and auth not enabled.

Please advise what I'm missing here to have the chart deploy a 3-node etcd cluster and restore all three nodes from the backup and enable auth for all three nodes.

Thanks!

### Are you using any custom parameters or values?
```
replicaCount: 3
auth:
  rbac:
    enabled: true
    rootPassword: mypassword
startFromSnapshot:
  enabled: true
  existingClaim: nfs-pvc-etcdbackup
  snapshotFilename: etcdback.dat
```
### What is the expected behavior?

An etcd cluster with replicaCount nodes all using the same DB and with the same RBAC settings.

### What do you see instead?

Three one-node etcd instances, one of which has the restored DB and RBAC enabled; the other two having RBAC disabled and empty DBs.
