### ISSUE TITLE
mongodb 13.0.0 with replicaset in CrashLoopBackOff

### ISSUE THREAD

**Issue by joscabmar** [bitnami/charts#11726]
### Name and Version

bitnami/mongodb 13.0.0

### What steps will reproduce the bug?

1. When the first pod (`mongodb-0`) starts, I get the following logs:
```
mongodb 10:13:24.34 INFO  ==> Advertised Hostname: mongodb-0.mongodb-headless.test.svc.cluster.local
mongodb 10:13:24.35 INFO  ==> Advertised Port: 27017
realpath: /bitnami/mongodb/data/db: No such file or directory
mongodb 10:13:24.35 INFO  ==> Data dir empty, checking if the replica set already exists
MongoNetworkError: connect ECONNREFUSED 10.1.150.11:27017
mongodb 10:13:25.49 INFO  ==> Pod name matches initial primary pod name, configuring node as a primary
mongodb 10:13:25.51
mongodb 10:13:25.51 Welcome to the Bitnami mongodb container
mongodb 10:13:25.51 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 10:13:25.51 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 10:13:25.52
mongodb 10:13:25.52 INFO  ==> ** Starting MongoDB setup **
mongodb 10:13:25.53 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 10:13:25.61 INFO  ==> Initializing MongoDB...
mongodb 10:13:25.64 INFO  ==> Deploying MongoDB from scratch...
mongodb 10:13:25.64 DEBUG ==> Starting MongoDB in background...
{"t":{"$date":"2022-08-11T10:13:25.683Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"enableLocalhostAuthBypass":{"default":true,"value":true}}}}
about to fork child process, waiting until server is ready for connections.
forked process: 81
child process started successfully, parent exiting
MongoNetworkError: connect ECONNREFUSED 10.1.150.11:27017
mongodb 10:13:27.86 INFO  ==> Creating users...
mongodb 10:13:27.86 INFO  ==> Creating admin user...
Current Mongosh Log ID:	62f4d6484311ade8b7be0cc4
Connecting to:		mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.5.4
Using MongoDB:		6.0.0
Using Mongosh:		1.5.4

For mongosh info see: https://docs.mongodb.com/mongodb-shell/


To help improve our products, anonymous usage data is collected and sent to MongoDB periodically (https://www.mongodb.com/legal/privacy-policy).
You can opt-out by running the disableTelemetry() command.

------
   The server generated these startup warnings when booting
   2022-08-11T10:13:25.693+00:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
   2022-08-11T10:13:26.287+00:00: vm.max_map_count is too low
------

------
   Enable MongoDB's free cloud-based monitoring service, which will then receive and display
   metrics about your deployment (disk utilization, CPU, operation statistics, etc).

   The monitoring data will be available on a MongoDB website with a unique URL accessible to you
   and anyone you share the URL with. MongoDB may use this information to make product
   improvements and to suggest MongoDB products and deployment options to you.

   To enable free monitoring, run the following command: db.enableFreeMonitoring()
   To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
------

test> { ok: 1 }
mongodb 10:13:29.95 INFO  ==> Creating user 'test'...
test> Current Mongosh Log ID:	62f4d64bdf021d29ccd61a3d
Connecting to:		mongodb://<credentials>@127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.5.4
Using MongoDB:		6.0.0
Using Mongosh:		1.5.4

For mongosh info see: https://docs.mongodb.com/mongodb-shell/

------
   The server generated these startup warnings when booting
   2022-08-11T10:13:25.693+00:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
   2022-08-11T10:13:26.287+00:00: vm.max_map_count is too low
------

------
   Enable MongoDB's free cloud-based monitoring service, which will then receive and display
   metrics about your deployment (disk utilization, CPU, operation statistics, etc).

   The monitoring data will be available on a MongoDB website with a unique URL accessible to you
   and anyone you share the URL with. MongoDB may use this information to make product
   improvements and to suggest MongoDB products and deployment options to you.

   To enable free monitoring, run the following command: db.enableFreeMonitoring()
   To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
------

test> { ok: 1 }
mongodb 10:13:32.17 INFO  ==> Users created
mongodb 10:13:32.18 INFO  ==> Writing keyfile for replica set authentication...
mongodb 10:13:32.20 INFO  ==> Configuring MongoDB replica set...
mongodb 10:13:32.21 INFO  ==> Stopping MongoDB...
mongodb 10:13:33.22 DEBUG ==> Starting MongoDB in background...
test> {"t":{"$date":"2022-08-11T10:13:33.272Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"enableLocalhostAuthBypass":{"default":true,"value":true}}}}
about to fork child process, waiting until server is ready for connections.
forked process: 236
ERROR: child process failed, exited with 1
To see additional information in this output, start without the "--fork" option.
```
2. The following startup times I get:
```
mongodb 10:38:10.11 INFO  ==> Advertised Hostname: mongodb-0.mongodb-headless.test.svc.cluster.local
mongodb 10:38:10.11 INFO  ==> Advertised Port: 27017
mongodb 10:38:10.11 INFO  ==> Pod name matches initial primary pod name, configuring node as a primary
mongodb 10:38:10.13
mongodb 10:38:10.13 Welcome to the Bitnami mongodb container
mongodb 10:38:10.13 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 10:38:10.13 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 10:38:10.14
mongodb 10:38:10.14 INFO  ==> ** Starting MongoDB setup **
mongodb 10:38:10.15 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 10:38:10.21 INFO  ==> Initializing MongoDB...
mongodb 10:38:10.24 INFO  ==> Enabling authentication...
mongodb 10:38:10.25 INFO  ==> Deploying MongoDB with persisted data...
mongodb 10:38:10.25 INFO  ==> Writing keyfile for replica set authentication...
mongodb 10:38:10.28 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
mongodb 10:38:10.29 DEBUG ==> Starting MongoDB in background...
{"t":{"$date":"2022-08-11T10:38:10.316Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"enableLocalhostAuthBypass":{"default":true,"value":false}}}}
about to fork child process, waiting until server is ready for connections.
forked process: 97
ERROR: child process failed, exited with 1
To see additional information in this output, start without the "--fork" option.
```

### Are you using any custom parameters or values?

```yaml
mongodb:
  fullnameOverride: mongodb
  image:
    debug: true
  architecture: replicaset
  useStatefulSet: true
  replicaCount: 3
  arbiter:
    enabled: false
  auth:
    rootUser: admin
    rootPassword: "admintest"
    usernames: ["test"]
    passwords: ["test"]
    databases: ["test"]
    replicaSetKey: "replicasetkeytest"
  initdbScripts:
    init-userdb.js: |
      db = db.getSiblingDB("user_local");
      db.createUser({ user: "user-local", pwd: "test", roles: [ { role: "readWrite", db: "user_local" } ]});
  metrics:
    enabled: true
    prometheusRule:
      enabled: true
      rules:
      - alert: HighRequestLatency
        annotations:
          summary: High request latency
        expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
        for: 10m
        labels:
          severity: page
    serviceMonitor:
      enabled: true
```

### What is the expected behavior?

Mongodb statefulset should start and the pods should be healthy.

### What do you see instead?

A CrashLoopBackOff in mongodb-0 pod

### Additional information

I started by removing all previous mongodb persistent data before deploying the new release:
```
kubectl delete statefulset/mongodb persistentvolumeclaim/datadir-mongodb-0 persistentvolumeclaim/datadir-mongodb-1 persistentvolumeclaim/datadir-mongodb-2
```
