### ISSUE TITLE
[bitnami/grafana] missing functionality to download dashboards 

### ISSUE THREAD

**Issue by rptaylor** [bitnami/charts#11736]
### Name and Version

chart bitnami/grafana 8.0.4   , app version 9.0.5

### What is the problem this feature will solve?

The upstream grafana chart can download dashboards by URL or an ID on grafana.com:
https://github.com/grafana/helm-charts/tree/main/charts/grafana#import-dashboards

There is a dashboard downloader script/container that does it:
https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/configmap.yaml#L67

That is much more convenient than downloading/updating/managing multi-thousand-line JSON files and importing them into configmaps.
Why was that functionality removed in the bitnami grafana chart?

### What is the feature you are proposing to solve the problem?

Include the upstream functionality for downloading dashboards.

### What alternatives have you considered?

Switching to the grafana/grafana chart instead of using bitnami/grafana, although we generally prefer the extra engineering that goes into bitnami charts.

**Comment by fmulero** [comment]
Thanks @rptaylor  for opening this issue.

In the `bitnami/grafana` chart we've never had that feature as it is implemented in the upstream project, but you can add an initContainer to download the dashboards as you need.  For instance, the following `values.yaml` creates an initContainer to  download a dashboard for ingress-nginx:

```yaml
dashboardsProvider:
  enabled: true
grafana:
  extraVolumes:
    - name: dashboards
      emptyDir: {}
  extraVolumeMounts:
    - name: dashboards
      mountPath: /opt/bitnami/grafana/dashboards
  initContainers:
    - name: dashboard-provisioner
      image: bitnami/bitnami-shell:latest
      command:
        - /bin/bash
        - -ec
        - curl -kSsLfo /tmp/dashboards/request-handling-performance.json https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/grafana/dashboards/request-handling-performance.json
      volumeMounts:
        - name: dashboards
          mountPath: /tmp/dashboards
```

I hope it helps
