### ISSUE TITLE
pinniped sets incorrect backend.service.name for service/pinniped-service

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#11734]
### Name and Version

bitnami/pinniped:0.1.5

### What steps will reproduce the bug?

1. deploy helm chart with a few custom parameters including an ingress

### Are you using any custom parameters or values?

```yaml
          parameters:
          - name: pinniped.concierge.enabled
            value: "'false'"
          - name: pinniped.supervisor.service.type
            value: "ClusterIP"
          - name: pinniped.supervisor.ingress.enabled
            value: "'true'"
          - name: pinniped.supervisor.ingress.ingressClassName
            value: "nginx"
          - name: pinniped.supervisor.ingress.hostname
            value: "pinniped.k.home.net"
          - name: pinniped.supervisor.ingress.tls
            value: "'true'"
          - name: pinniped.supervisor.ingress.annotations.cert-manager\.io\/issuer
            value: "cluster-adcs-issuer"
          - name: pinniped.supervisor.ingress.annotations.cert-manager\.io\/issuer-kind
            value: "ClusterAdcsIssuer"
          - name: pinniped.supervisor.ingress.annotations.cert-manager\.io\/issuer-group
            value: "adcs.certmanager.csf.nokia.com"
```

### What is the expected behavior?

expected pinniped supervisor to come up, accessible via ingress

### What do you see instead?

503, because the ingress has a service name of `pinniped` instead of `pinniped-supervisor`

```yaml
spec:
  ingressClassName: nginx
  rules:
  - host: pinniped.k.home.net
    http:
      paths:
      - backend:
          service:
            name: pinniped
            port:
              name: https
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - pinniped.k.idaho.gov
    secretName: pinniped.k.home.net-tls
```

```console
$ k get service
NAME                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
pinniped-concierge       ClusterIP   10.102.172.226   <none>        443/TCP   15m
pinniped-concierge-api   ClusterIP   10.111.181.170   <none>        443/TCP   15m
pinniped-supervisor      ClusterIP   10.104.85.218    <none>        443/TCP   15m
```

### Additional information

I looked over the ingress template but I'm not sure how it's getting the service name it is using or what I can do to get this to work.  If I just need to specify the name somewhere please let me know where.
