### ISSUE TITLE
[bitnami/keycloak] Import of keycloak custom themes is failing

### ISSUE THREAD

**Issue by suchitsancheti** [bitnami/charts#11759]
### Name and Version

bitnami/keycloak 9.6.8

### What steps will reproduce the bug?

1. Create a tar of themes file.
2. Create a configmap consisting of the themes.tar
3. Deploy the helm chart
4. Getting the following error:
`Error: create: failed to create: Request entity too large: limit is 3145728
helm.go:84: [debug] Request entity too large: limit is 3145728
create: failed to create`

5. Then I added an init-container to download the themes.tar from S3 bucket and copy it to /opt/bitnami/keycloak/themes. For copying the themes, mounted an emptyDir in initContainer at location /opt/bitnami/keycloak/themes. In keycloak, this volume is also mounted at the location /opt/bitnami/keycloak/themes
6. When I am logging into the keycloak using admin user, the screen is showing up as blank after the user is logged in.

What is the way of importing the custom themes using the bitnami charts?

### What is the expected behavior?

Custom themes are imported and keycloak is able to load them

### What do you see instead?

`Error: create: failed to create: Request entity too large: limit is 3145728
helm.go:84: [debug] Request entity too large: limit is 3145728
create: failed to create`

A blank screen after the user is logged in.

**Comment by fmulero** [comment]
Hi @suchitsancheti 

That error about `Request entity too large` seems to be happening in helm side, probably because the release with the theme is too large. Please keep in mind that [configmaps](https://kubernetes.io/docs/concepts/configuration/configmap/#motivation) are not designed to store big files 

Could you share more information about the solution with the `initContainer`? Do you have a `values.yaml` file?

**Comment by suchitsancheti** [comment]
Hi @fmulero, 

Here is the values.yaml that I have used to get the themes imported.

```
  extraVolumes:
    - name: my-themes
      emptyDir: {}         

  extraVolumeMounts:
    - mountPath: /opt/bitnami/keycloak/themes
      name: my-themes

  initContainers:
    - name: my-themes
      image: xxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/my-image:0.1.0
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash","-c"]
      args:
      - "aws s3 cp s3://my-keycloak-themes/themes.tar.gz my-themes.tar.gz && \
         tar -xvf my-themes.tar.gz && rm -rf my-themes.tar.gz && ls -ltra && \
         cp -rf my-theme base /opt/bitnami/keycloak/themes && \
         ls -ltra /opt/bitnami/keycloak/themes"
      volumeMounts:
      - mountPath: /opt/bitnami/keycloak/themes
        name: my-themes
```
Also, can you please suggest the recommended way to import the custom themes?

**Comment by fmulero** [comment]
About the way you imported themes, just only one comment, take care about the file permissions, please try something like this:

```yaml
  extraVolumes:
    - name: my-themes
      emptyDir: {}         

  extraVolumeMounts:
    - mountPath: /opt/bitnami/keycloak/themes
      name: my-themes
      subPath: themes

  initContainers:
    - name: my-themes
      image: xxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/my-image:0.1.0
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 1001
      command: ["/bin/bash","-c"]
      args:
      - "mkdir /opt/bitnami/keycloak/themes && \
         aws s3 cp s3://my-keycloak-themes/themes.tar.gz my-themes.tar.gz && \
         tar -xvf my-themes.tar.gz && rm -rf my-themes.tar.gz && ls -ltra && \
         cp -rf my-theme base /opt/bitnami/keycloak/themes && \
         ls -ltra /opt/bitnami/keycloak/themes"
      volumeMounts:
      - mountPath: /opt/bitnami/keycloak
         name: my-themes
```

About the 204 error, to be perfectly blunt, I have no idea. Maybe you can find more information about that in keycloak forums
