### ISSUE TITLE
commonAnnotations are missing if no service.annotation is not filled

### ISSUE THREAD

**Issue by lynchmaniac** [bitnami/charts#11791]
### Name and Version

bitnami/grafana:8.1.0

### What steps will reproduce the bug?

Simple launch with:

```sh
helm install grafana -n monitoring --create-namespace -f values.yaml bitnami/grafana
```

Values.yaml :

```yaml
global:
  imageRegistry: "XXXXXXX:XXXX" 
commonAnnotations: {
  service.citrix.com/class: citrix-ingress,
  service.citrix.com/ipam-range: vips,
  service.citrix.com/service-type-0: HTTP,
  external-dns.alpha.kubernetes.io/hostname: grafana-test.all
}
admin:
  password: AAAAAAAAA
service:
  type: LoadBalancer
persistence:
  storageClass: csi
  size: 10Gi
  accessModes: ["ReadWriteOnce"]
```

### What is the expected behavior?

I expected to find my annotations in the description of the service. Instead they are absent which leads to a side effect.

With other Bitnami charts (drupal or WordPress), the problem don't exist.

### What do you see instead?

I'll see no annotation inside my object.

If I'll put my annotation inside `service.annotation`, it works.

### Additional information

The problem is in the template service.

Actual version:

```yaml
{{- if or (and .Values.metrics.enabled .Values.metrics.service.annotations) .Values.service.annotations }}
  annotations:
  {{- if and .Values.metrics.enabled .Values.metrics.service.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.metrics.service.annotations "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.service.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.service.annotations "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  {{- end }}
```

`.Values.commonAnnotations` is inside the condition `{{- if or (and .Values.metrics.enabled .Values.metrics.service.annotations) .Values.service.annotations }}` so if there is no service annotation, commonAnnotation can be applied. I don't know if it's voluntary or not but maybe it's just the doc out of date.

for me the code should be like this: 

```yaml
{{- if or (and .Values.metrics.enabled .Values.metrics.service.annotations) .Values.service.annotations .Values.commonAnnotations }}
  annotations:
  {{- if and .Values.metrics.enabled .Values.metrics.service.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.metrics.service.annotations "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.service.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.service.annotations "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  {{- end }}
```

Any advice or comments?

Thanks for the work on this chart, other than that issue it works like a charm 😃
