### ISSUE TITLE
[bitnami/kube-prometheus] unable to install kube-prometheus twice

### ISSUE THREAD

**Issue by FeiYing9** [bitnami/charts#11792]
### Name and Version

bitnami/kube-prometheus 6.9.4

### What steps will reproduce the bug?

install kube-prometheus in two namespace:

```bash
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "operator" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "namespace1": current value is "namespace2"
```

### What do you see instead?

```yaml
# k get clusterrole operator -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prometheus
    meta.helm.sh/release-namespace: infra              # this cause the problem
```
