### ISSUE TITLE
[bitnami/postgresql-ha] pgpool syntax error in configuration file

### ISSUE THREAD

**Issue by alexanderursu99** [bitnami/charts#11817]
### Name and Version

bitnami/postgresql-ha 9.3.3

### What steps will reproduce the bug?

Deploying Helm chart on EKS 1.21

### Are you using any custom parameters or values?

Currently have these values set for pgpool section in the Helm chart:
```yml
pgpool:
  image:
    registry: docker.io
    repository: bitnami/pgpool
    tag: 4.3.2-debian-11-r26
    debug: true
  ## @param pgpool.customUsersSecret Name of a secret containing the usernames and passwords of accounts that will be added to pgpool_passwd
  ## The secret must contain the keys "usernames" and "passwords" respectively.
  ##
  customUsersSecret: ""
  existingSecret: postgresql-ha-pgpool-creds
  ## @param pgpool.srCheckDatabase Name of the database to perform streaming replication checks
  ##
  srCheckDatabase: postgres
  replicaCount: 1
  topologySpreadConstraints: []
  podAntiAffinityPreset: soft
  nodeSelector: {}
  resources:
    limits: {}
    requests: {}
  pdb:
    create: false
    minAvailable: 1
    maxUnavailable: ""
  updateStrategy: {}
  ## @param pgpool.minReadySeconds How many seconds a pod needs to be ready before killing the next, during update
  ##
  minReadySeconds: ""
  adminUsername: admin
  usePasswordFile: true
  authenticationMethod: scram-sha-256
  logConnections: false
  logHostname: true
  logPerNodeStatement: false
  logLinePrefix: ""
  clientMinMessages: error
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/pgpool#configuration
  numInitChildren: "32"
  reservedConnections: 1
  maxPool: "15"
  childMaxConnections: "0"
  childLifeTime: "300"
  clientIdleLimit: "0"
  connectionLifeTime: "0"
  useLoadBalancing: true
  ## @param pgpool.loadBalancingOnWrite LoadBalancer on write actions behavior
  ## one of: [off, transaction, trans_transaction, always]
  ##
  loadBalancingOnWrite: transaction
  ## @param pgpool.configuration Pgpool configuration
  ## You can use this parameter to specify the content for pgpool.conf
  ## Otherwise, a repmgr.conf will be generated based on the environment variables
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/pgpool#configuration
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/pgpool#configuration-file
  ## Example:
  ## configuration: |-
  ##   listen_addresses = '*'
  ##   port = '5432'
  ##   ...
  ##
  configuration: ""
```

### What is the expected behavior?

Expecting pgpool to start up successfully.

### What do you see instead?

pgpool begins setup and exits after stating a warning of a syntax error in pgpool.conf without any indication of what is causing it.
```
pgpool 21:35:13.41 Welcome to the Bitnami pgpool container
pgpool 21:35:13.41 Subscribe to project updates by watching https://github.com/bitnami/containers
pgpool 21:35:13.41 Submit issues and feature requests at https://github.com/bitnami/containers/issues
pgpool 21:35:13.41
pgpool 21:35:13.41 INFO ==> ** Starting Pgpool-II setup **
pgpool 21:35:13.44 INFO ==> Validating settings in PGPOOL_* env vars...
pgpool 21:35:13.46 INFO ==> Initializing Pgpool-II...
pgpool 21:35:13.47 INFO ==> Generating pg_hba.conf file...
pgpool 21:35:13.47 INFO ==> Generating pgpool.conf file...
pgpool 21:35:13.62 DEBUG ==> Adding 'postgresql-postgresql-ha-postgresql-0.postgresql-postgresql-ha-postgresql-headless' information to the configuration...
pgpool 21:35:13.63 DEBUG ==> Adding 'postgresql-postgresql-ha-postgresql-1.postgresql-postgresql-ha-postgresql-headless' information to the configuration...
pgpool 21:35:13.64 DEBUG ==> Adding 'postgresql-postgresql-ha-postgresql-2.postgresql-postgresql-ha-postgresql-headless' information to the configuration...
pgpool 21:35:13.65 INFO ==> Generating password file for local authentication...
trying to read key from file /opt/bitnami/pgpool/conf/.pgpoolkey
WARNING: pid 122: syntax error in configuration file "/opt/bitnami/pgpool/conf/pgpool.conf"
Unable to get configuration. Exiting...
```
