### ISSUE TITLE
Unable to login to harbor registry when using ingress as alb ingress controller

### ISSUE THREAD

**Issue by Nadeem93** [bitnami/charts#11824]
### Name and Version

bitnami/harbor:15.0.4

### What steps will reproduce the bug?

Creates an alb ingress controller and changes the values in vaules.yaml for ingress , but i am not able to login to the page.

### Are you using any custom parameters or values?
```
postgresql:
  enabled: false
externalDatabase:
  host:xxxxxxxx
  port: 5432
  user: postgres
  password: "xxxxx"
  #sslmode: disable
  coreDatabase: "registry"
  #notaryServerDatabase: "notaryserver"
  #  notaryServerUsername: "postgres"
  #  notaryServerPassword: "password"
  #notarySignerDatabase: "notarysigner"
  #  notarySignerUsername: "postgres"
  #  notarySignerPassword: "password"
redis:
  enabled: false
externalRedis:
  host: xxxxxxxx
  port: 6379
  password: ""
  coreDatabaseIndex: '0'
  jobserviceDatabaseIndex: '1'
  registryDatabaseIndex: '2'
  chartmuseumDatabaseIndex: '3'
  trivyAdapterDatabaseIndex: '5'
notary:
  ## @param notary.enabled Enable Notary
  ##
  enabled: false


persistence:
  imageChartStorage:
    disableredirect: false
    type: s3
    s3:
      region: us-west-2
      bucket: xxxxxx
        
        
jobservice:
  jobLogger: database

externalURL: https:/xxxxxxx

#Ingress Configurations

exposureType: ingress
ingress:
  core:
    ingressClassName: "alb"
    hostname: xxxxxxx
    annotations:
      alb.ingress.kubernetes.io/subnets: subnet-xxxxxx, subnet-xxxxxx
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/success-codes: "200"
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/certificate-arn: xxxxxx
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'



--set adminPassword=password
```
### What is the expected behavior?

Login should work properly

### What do you see instead?

Getting invalid user and password failed
