### ISSUE TITLE
[bitnami/postgresql] metrics not work if tls.enabled=true  and tls.certCAFilename not empty

### ISSUE THREAD

**Issue by snailxr** [bitnami/charts#11822]
### Name and Version

bitnami/postgres:11.7.1

### What steps will reproduce the bug?

values set:
``` yaml
auth:
    username: xxx
    password: xxx
    database: postgres

tls:
    enabled: true
    certificatesSecret: db-certificates-tls-secret
    certFilename: serverxxx.crt
    certKeyFilename: serverxxx.key
    certCAFilename: caxxx.crt
```
After installing and getting metrics will get the following error:
```
ts=2022-08-18T05:19:59.443Z caller=postgres_exporter.go:731 level=error err="Error opening connection to database (host=127.0.0.1%20port=5432%20user=xxx%20sslmode=require%20sslcert=/opt/bitnami/postgresql/certs/server.crt%20sslkey=/opt/bitnami/postgresql/certs/server.key): pq: database \"xxx\" does not exist"
```
Seems caused by no database name same as the custom username, and we can not specify the database for env `DATA_SOURCE_NAME`

### What do you see instead?

error logs:
```
ts=2022-08-18T05:19:59.443Z caller=postgres_exporter.go:731 level=error err="Error opening connection to database (host=127.0.0.1%20port=5432%20user=xxx%20sslmode=require%20sslcert=/opt/bitnami/postgresql/certs/server.crt%20sslkey=/opt/bitnami/postgresql/certs/server.key): pq: database \"xxx\" does not exist"
```
### Additional information

If can specifies the database for env `DATA_SOURCE_NAME` in values, this issue can be resolved
