### ISSUE TITLE
[bitnami/kube-prometheus] Additional annotations for CRDs

### ISSUE THREAD

**Issue by Johannes-** [bitnami/charts#11831]
### Name and Version

bitnami/kube-prometheus 8.0.16

### What is the problem this feature will solve?

The prometheuses.monitoring.coreos.com CRD is too large to be applied with kubectl apply. This results in following error:
```
metadata.annotations: Too long: must have at most 262144 bytes (retried 5 times)
```

This is a problem when using ArgoCD to deploy the bitnami/kube-prometheus helm chart as it uses `kubectl apply`. ArgoCD provides a solution for this by providing an option to use `kubectl replace`. This option can be either used for the complete app or by annotating resources with `argocd.argoproj.io/sync-options: Replace=true`.

Hence it would be nice to be able to add optional additional annotations via `values.yaml` to all CRDs as I don't want to use `kubectl replace` for all manifests in the helm chart.

### What is the feature you are proposing to solve the problem?

Adding optional additional annotations via `values.yaml` to all CRDs.

### What alternatives have you considered?

Have the CRDs in a second helm chart and add them before with the `kubectl replace` option.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by Johannes-** [comment]
Just noticed that my proposed solution won't work as it is not possible to use go templating in the crds folder.

I can only think of two solutions wich both have some drawbacks:

1. Add ``argocd.argoproj.io/sync-options: Replace=true`` as default annotation to all crds (or just the one that is to large for kube ctl apply``). 
2. Move the crds to templates folder.

As solution 1 is much to specific and solution 2 would change the behaviour, I can't think of an appropriate solution other the one proposed in the issue. If there is no other idea of how to solve this, this issue can be closed.

**Comment by Johannes-** [comment]
Maybe I got you wrong but it is not possible to add a code block to a CRD as long as the file stays in the /crds folder. So adding for example ``{{- .Values.foo.bar }}`` to /crds/crd-alermanger-confog.yaml:

```yaml
# https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.57.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
    {{- .Values.foo.bar }}
...
```

With ```helm template --include-crds . > out.yaml ``` we will see that the templating is not applied to it and it stays the same. Further by trying to install it we get an error as it is not a valid json: ```Error: INSTALLATION FAILED: failed to install CRD crds/crd-alertmanager-config.yaml: error parsing : error converting YAML to JSON: yaml: line 8: could not find expected ':'```
