### ISSUE TITLE
Nginx - Service Type Defaulting to LoadBalancer - should be ClusterIP + How to Auto Use Existing LB of NGINX-INGRESS Type

### ISSUE THREAD

**Issue by noelashford** [bitnami/charts#11846]
### Name and Version

nginx/latest

### What steps will reproduce the bug?

setting ingress.enabled=false or not setting it (defualt is false) spins up a load balancer - it should not. I understand the type needs to be set to ClusterIP but the way i read this / desired behavior should be to make or not make an ingress depending on the type of service you choose. ClusterIP should ask about an existing one and how to ingress it & setting this to disabled should do nothing vs something

" helm template demo bitnami/nginx --namespace demo --set ingress.enabled=false" can confirm this

### Are you using any custom parameters or values?

same happens with or without the ingress.enabled shown above

### What is the expected behavior?

No load balancer should be created (I have an existing one i wish to use - also, please advise how to reference another ingress controller of ingress-nginx

### What do you see instead?

I see this being generated:

```
# Source: nginx/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: demo-nginx
  namespace: "demo"
  labels:
    app.kubernetes.io/name: nginx
    helm.sh/chart: nginx-13.1.7
    app.kubernetes.io/instance: demo
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: "Cluster"
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: demo

```

### Additional information

The annotations for ingress should be able to also reference another ingress controller - this also does not work
