### ISSUE TITLE
[bitnami/discourse] Postgres password is stored in configMap and not respecting existing secret

### ISSUE THREAD

**Issue by ariksidney** [bitnami/charts#11859]
### Name and Version

bitnami/discourse 8.0.9

### What steps will reproduce the bug?

1. Start postgresql via the bitnami postgresql chart (or use another fresh postgres installation)
2. Create a secret which contains the postgres admin user password
3. Disable postgres and configure the external postgres instance like described below
4. Deploy discourse with the values from above

### Are you using any custom parameters or values?

```yaml
postgresql:
  enabled: false
externalDatabase:
  host: <todo>
  port: 5432
  user: bn_discourse
  database: bitnami_application
  # password: ""
  create: true
  postgresUser: "postgres"
  # postgresPassword: ""
  existingSecret: "<name from secret created before>"
  existingSecretPasswordKey: "<secret key for application postgres user>"
  existingSecretPostgresPasswordKey: "<secret key for postgres root user>"
```

### What is the expected behavior?

Discourse should start normally and getting the db passwords from the secret.

### What do you see instead?

The following error is preventing the successful start of Discourse:

`The POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development`

If a password is provided in the values, it is stored inside a configMap but in my opinion passwords should always be stored in secrets.

### Additional information

I can provide a PR in the next days for that
