### ISSUE TITLE
[bitnami/redis] Chart template render failed due to TLS options

### ISSUE THREAD

**Issue by masteryyh** [bitnami/charts#11863]
### Name and Version

bitnami/redis 17.0.11

### What steps will reproduce the bug?

1. Setup an ubuntu server 22.04 environment with K3s 1.24.3+k3s1 and helm installed
2. Run `helm install redis bitnami/redis -n redis -f values.yaml`
3. Helm will then prompt the error message:
```
Error: INSTALLATION FAILED: template: redis/templates/sentinel/statefulset.yaml:343:33: executing "redis/templates/sentinel/statefulset.yaml" at <{{template "redis.tls.dhParamsFilename" .}}>: template "redis.tls.dhParamsFilename" not defined
```

### Are you using any custom parameters or values?

Reduced due to length limit in GitHub
```yaml
## TLS configuration
##
tls:
  ## @param tls.enabled Enable TLS traffic
  ##
  enabled: true
  ## @param tls.authClients Require clients to authenticate
  ##
  authClients: false
  ## @param tls.autoGenerated Enable autogenerated certificates
  ##
  autoGenerated: false
  ## @param tls.existingSecret The name of the existing secret that contains the TLS certificates
  ##
  existingSecret: tls-redis
  ## @param tls.certificatesSecret DEPRECATED. Use existingSecret instead.
  ##
  certificatesSecret: ""
  ## @param tls.certFilename Certificate filename
  ##
  certFilename: redis.crt
  ## @param tls.certKeyFilename Certificate Key filename
  ##
  certKeyFilename: redis.key
  ## @param tls.certCAFilename CA Certificate filename
  ##
  certCAFilename: ca.crt
  ## @param tls.dhParamsFilename File containing DH params (in order to support DH based ciphers)
  ##
  dhParamsFilename: redis.dh
```

### What is the expected behavior?

Redis installed successfully without any issue.

### What do you see instead?

```
Error: INSTALLATION FAILED: template: redis/templates/sentinel/statefulset.yaml:343:33: executing "redis/templates/sentinel/statefulset.yaml" at <{{template "redis.tls.dhParamsFilename" .}}>: template "redis.tls.dhParamsFilename" not defined
```
