### ISSUE TITLE
[zookeeper]: auth not possible

### ISSUE THREAD

**Issue by Morriz** [bitnami/charts#1192]
The chart values are clear about auth server vars format and that they are plural:
```
auth:
  clientUser: ''
  clientPass: ''
  serverUsers: []
  serverPasswords: []
```
In the chart however they are treated as singular (see `secrets.yaml`) and so when auth is enabled we get an error saying:
```
Error executing 'postInstallation': zookeeperServerUsers and zookeeperServerPasswords lists should have the same length
```
