### ISSUE TITLE
Enabling TLS w/ autogeneration fails deployment of chart

### ISSUE THREAD

**Issue by RossComputerGuy** [bitnami/charts#11967]
### Name and Version

bitnami/keycloak 9.6.9

### What steps will reproduce the bug?

1. Deploy keycloak with the values

### Are you using any custom parameters or values?

```
auth:
  tls:
    enabled: true
    autoGenerated: true
    usePem: true
    keystorePassword: [generated by terraform, redacted]
    truststorePassword: [generated by terraform, redacted]
```

### What is the expected behavior?

The Helm chart should deploy

### What do you see instead?

```
│ Error: execution error at (keycloak/templates/statefulset.yaml:31:29):
│ PASSWORDS ERROR: The secret "keycloak" does not contain the key "tls-keystore-password"
```

**Comment by migruiz4** [comment]
Hi @RossComputerGuy,

Is there any additional value you used to deploy the chart? For example, values `auth.existingSecret` or `auth.existingSecretPerPassword`?

I couldn't reproduce the issue in a freshly installed deployment using the values you provided.

The error message `The secret "keycloak" does not contain the key "tls-keystore-password"` points out that the keycloak secret does not contain the key, but a dry-run shows that the secret will be generated and includes the key:
```console
$ helm install keycloak bitnami/keycloak -f values.yaml --dry-run
...
# Source: keycloak/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: "default"
  labels:
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-9.6.9
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: keycloak
type: Opaque
data:
  admin-password: "QXBkdXJ5TnRZZg=="
  tls-keystore-password: "cGFzc3dvcmQy"
  tls-truststore-password: "cGFzc3dvcmQx"
...
```

**Comment by RossComputerGuy** [comment]
> Hi @RossComputerGuy,
> 
> Is there any additional value you used to deploy the chart? For example, values `auth.existingSecret` or `auth.existingSecretPerPassword`?
> 
> I couldn't reproduce the issue in a freshly installed deployment using the values you provided.
> 
> The error message `The secret "keycloak" does not contain the key "tls-keystore-password"` points out that the keycloak secret does not contain the key, but a dry-run shows that the secret will be generated and includes the key:
> ```console
> $ helm install keycloak bitnami/keycloak -f values.yaml --dry-run
> ...
> # Source: keycloak/templates/secrets.yaml
> apiVersion: v1
> kind: Secret
> metadata:
>   name: keycloak
>   namespace: "default"
>   labels:
>     app.kubernetes.io/name: keycloak
>     helm.sh/chart: keycloak-9.6.9
>     app.kubernetes.io/instance: keycloak
>     app.kubernetes.io/managed-by: Helm
>     app.kubernetes.io/component: keycloak
> type: Opaque
> data:
>   admin-password: "QXBkdXJ5TnRZZg=="
>   tls-keystore-password: "cGFzc3dvcmQy"
>   tls-truststore-password: "cGFzc3dvcmQx"
> ...
> ```
> 

All of my values are defined [here](https://github.com/RossComputerGuy/kluster/blob/3c21b7605752444ce6e431ed54676c99be21b5de/main.tf#L160-L229). I wasn't sure which ones were relevant besides auth.

**Comment by migruiz4** [comment]
I'm sorry I haven't used Helm provider for terraform, but I don't see any reference to `auth.tls.enabled=true` or `auth.tls.autoGenerated=true` in the file you provided.

> Error: execution error at (keycloak/templates/statefulset.yaml:31:29):
> PASSWORDS ERROR: The secret "keycloak" does not contain the key "tls-keystore-password"

Is this error triggered by that same file?

**Comment by RossComputerGuy** [comment]
That's because I removed the reference when I got the error, `main.tf` is what does the work of deployment but the error seems to be coming from the Helm.

**Comment by migruiz4** [comment]
In that case, could you please share the exact version of the file that triggers the error?

**Comment by RossComputerGuy** [comment]
The password was generated via the `random_password` resource in Terraform which I've used many times and never had issues. And these values don't replicate it?
```yaml
auth:
  tls:
    enabled: true
    autoGenerated: true
    usePem: true
    keystorePassword: [generated by terraform, redacted]
    truststorePassword: [generated by terraform, redacted]
ingress:
  enabled: true
```

**Comment by migruiz4** [comment]
I can't get to replicate it using those values:
```
auth:
  tls:
    enabled: true
    autoGenerated: true
    usePem: true
    keystorePassword: [generated by terraform, redacted]
    truststorePassword: [generated by terraform, redacted]
ingress:
  enabled: true
```

Output:
```
$ helm install test bitnami/keycloak -f values.yaml 
NAME: test
LAST DEPLOYED: Wed Aug 31 16:21:51 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: keycloak
CHART VERSION: 9.7.2
APP VERSION: 18.0.2

** Please be patient while the chart is being deployed **

Keycloak can be accessed through the following DNS name from within your cluster:

    test-keycloak.default.svc.cluster.local (port 80)

To access Keycloak from outside the cluster execute the following commands:

1. Get the Keycloak URL and associate its hostname to your cluster external IP:

   export CLUSTER_IP=$(minikube ip) # On Minikube. Use: `kubectl cluster-info` on others K8s clusters
   echo "Keycloak URL: http://keycloak.local/"
   echo "$CLUSTER_IP  keycloak.local" | sudo tee -a /etc/hosts

2. Access Keycloak using the obtained URL.
```

**Comment by migruiz4** [comment]
Although, I have been able to reproduce the error by doing the following:

- I created a secret containing the Keycloak admin password but missing the Keystore and Trustore passwords, using the same name the chart would use (in my case, `test-keycloak`):
```
$ cat secret.yaml 
apiVersion: v1
kind: Secret
metadata:
  name: test-keycloak
  namespace: "default"
type: Opaque
data:
  admin-password: "VXNEblp4RmN0Yw=="
$ kubectl apply -f secret.yaml
secret/test-keycloak created
```
- Provide the values, I will be using the same that previously worked:
```
auth:
  tls:
    enabled: true
    autoGenerated: true
    usePem: true
    keystorePassword: jZ333#RjW3yW
    truststorePassword: 5L3xo0%Sj*^5&5hC
ingress:
  enabled: true
```
- Try to install the chart and see error:
```
$ helm install test bitnami/keycloak -f values.yaml          
Error: INSTALLATION FAILED: execution error at (keycloak/templates/statefulset.yaml:31:29): 
PASSWORDS ERROR: The secret "test-keycloak" does not contain the key "tls-keystore-password"
```

Is it possible you are creating a secret named `keycloak` in the same kubernetes cluster and namespace?
Maybe you could try using a different RELEASE_NAME for the keycloak helm chart, or use a different secret name if you find it.

The chart has a mechanism that uses the `lookup` function trying to find the secret from an existing deployment when upgrading, but in this case it may be picking a different secret and failing because of it.
