### ISSUE TITLE
Upgrading to version 11.9.x of the minio chart breaks other Bitnami dependencies

### ISSUE THREAD

**Issue by JD-Robertson** [bitnami/charts#12026]
### Name and Version

bitnami/minio 11.9.x

### What steps will reproduce the bug?

1. Using this simple reproducing chart:

```yaml
apiVersion: v2
name: reproduce
description: Reproducing Case
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: rabbitmq
    version: 10.1.19
    repository: '@bitnami'
  - name: minio
    repository: "@bitnami"
    version: 11.7.19
    # version: 11.9.1
```

2. Run `helm dependency update`
3. Run `helm template` and examine the output. The `image` value for the "rabbitmq" container should be "docker.io/bitnami/rabbitmq:3.10.7-debian-11-r4".
4. Comment out "version: 11.7.19" above and then uncomment "version: 11.9.1". Save the chart.
5. Run `helm dependency update`
6. Run `helm template` and examine the output. The "rabbitmq" container image is now "docker.io/bitnami/rabbitmq@<nil>". 

This is an invalid docker reference and will result in a container that is unable to run on the cluster. 

### Are you using any custom parameters or values?

This is seen as part of a much larger deployment and affects multiple dependencies, but the above case is sufficient to reproduce the issue.

### What is the expected behavior?

I do not expect updating a dependency to change the rendering of other dependencies at all. At a minimum, updating the dependency needs to not break other, older dependencies. 

### What do you see instead?

Updating the minio dependency to 11.9.0 or later (when support for [Docker image digests was added](https://github.com/bitnami/charts/commit/775737435e1bdd0c2c2238e882a632ad4a3ad8ed)) breaks other Bitnami chart dependencies.

**Comment by JD-Robertson** [comment]
With a bit of additional experimentation, it looks like if I update all dependencies to a version that supports Docker image digests then I do not see this issue. This only happens with a mix of older and newer charts. That would be a workaround for the simple reproducing case above, but in the much more complicated deployment where i encountered this issue we are using MongoDB 12.3.1 and updating to 13.x means updating MongoDB from version 5.x to 6.x which is not free for us. That could maybe be worked around by overriding image tags but I'd rather avoid if possible.

**Comment by carrodher** [comment]
Thanks for letting us know, we are adding backward compatibility in the bitnami/common library chart as part of the above PR. Then the different charts will receive a new patch version updating the bundled bitnami/common, that should fix the issue

**Comment by carrodher** [comment]
I just tested the same `Chart.yaml` shared above but using the latest bitnami/minio (`11.9.2` instead of `11.9.1`):
```yaml
apiVersion: v2
name: reproduce
description: Reproducing Case
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: rabbitmq
    version: 10.1.19
    repository: '@bitnami'
  - name: minio
    repository: "@bitnami"
    version: 11.7.19
    # version: 11.9.2
```

- Using the previous version (`11.7.19`) ✅:
```console
$ ls charts          
minio-11.7.19.tgz  rabbitmq-10.1.19.tgz
$ helm template . | grep 'image:'
          image: docker.io/bitnami/minio:2022.8.8-debian-11-r0
          image: docker.io/bitnami/rabbitmq:3.10.7-debian-11-r4
```
- Using the version with the issue (`11.9.1`) 🔴:
```console
$ ls charts          
minio-11.9.1.tgz  rabbitmq-10.1.19.tgz

$ helm template . | grep 'image:' 
          image: docker.io/bitnami/minio:2022.8.22-debian-11-r0
          image: docker.io/bitnami/rabbitmq@<nil>
```
- Changing the comment to use `11.9.2` ✅:
```console
$ ls charts          
minio-11.9.2.tgz  rabbitmq-10.1.19.tgz

$ helm template . | grep 'image:'
          image: docker.io/bitnami/minio:2022.8.22-debian-11-r0
          image: docker.io/bitnami/rabbitmq:3.10.7-debian-11-r4
```

Everything works as expected using the latest version. Thanks again for reporting the issue. Feel free to reopen it if something doesn't work as expected
