### ISSUE TITLE
[nginx-ingress-controller] Upgrading to version 9.3.1  breaks cert-manager SSL certificates

### ISSUE THREAD

**Issue by vudzero** [bitnami/charts#12028]
### Name and Version

bitnami/nginx-ingress-controller

### What steps will reproduce the bug?

Upgrade to version 9.3.1 of the helm chart

### What is the expected behavior?

SSL certificates generated from cert-manager to still works

### What do you see instead?

SSL certificates from cert-manager does not work anymore

### Additional information

I'm getting this error in the nginx controller pod
`2022/08/23 20:19:25 [error] 296#296: *7952 [lua] certificate.lua:259: call(): failed to set DER private key: d2i_PrivateKey_bio() failed, context: ssl_certificate_by_lua*`

And this error in the browser
![image](https://user-images.githubusercontent.com/2973549/186260200-ef5dfb1b-5f58-4dec-bc3f-ce5779177d58.png)

**Comment by vudzero** [comment]
Reverting to 9.3.0 fixes the issue

**Comment by javsalgar** [comment]
Hi!

Thank you for reporting. Could you provide the full steps to reproduce the issue? Including the installation of cert-manager and the certificate creation.

**Comment by steache** [comment]
Hello!
I hope you don't mind if I provide values to reproduce this issue?

We have running `cert-manager` from `jetstack` with this definition: (default chart values used, only overrides in `spec.values`

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  interval: 1h0m0s
  chart:
    spec:
      chart: cert-manager
      version: "^1.6.1"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: true
    prometheus:
      enabled: false

```

and `nginx-ingress-controller` with this values: (default chart values used, only overrides in `spec.values`)

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  releaseName: nginx
  interval: 1h0m0s
  chart:
    spec:
      chart: nginx-ingress-controller
      version: "9.3.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    service:
      externalTrafficPolicy: "Local"
    pdb:
      create: true

```

during auto-update to `bitnami/nginx-ingress-controller` version `9.3.2` an error from the issue.description on top crashed the nginx multiple times :) 

Certificate definition:

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: star-example-com
  namespace: cert-manager
spec:
  secretName: star-example-com
  issuerRef:
    kind: ClusterIssuer
    name: digitalocean-issuer # the problem is also with zerossl-issuer
  commonName: "*.reservio.com"
  dnsNames:
    - "*.example.com"
    - "example.com"
```

[(2022/08/23 20:19:25 [error] 296#296: *7952 [lua] certificate.lua:259: call(): failed to set DER private key: d2i_PrivateKey_bio() failed, context: ssl_certificate_by_lua*)](https://github.com/bitnami/charts/issues/12028#issue-1348514234)

Hope this helps somehow! :)
