### ISSUE TITLE
RabbitMQ HELM chart not listening on management port 15672

### ISSUE THREAD

**Issue by craigb-zencore** [bitnami/charts#12143]
### Name and Version

bitnami/rabbitmq 10.2.1

### What steps will reproduce the bug?

The default management port 15672 is not listening on my RabbitMQ deployment. I have no overrides for this service/port, so I'm unsure why the port is not listening.

### Are you using any custom parameters or values?

Not for this configuration, but here is my values.yaml file

```
image:
  registry: docker.io
  repository: rabbitmq
  tag: 3.10.7-alpine
replicaCount: 3
auth:
  username: guest
  existingPasswordSecret: rabbitmq-ha
  existingErlangSecret: rabbitmq-ha
#memoryHighWatermark:
#  enabled: true
#  type: absolute
#  value: 8GB
extraConfiguration: |
      ## All configurations above this line are from the baseline HELM chart. No way to update
      ##
      ## BEGIN CUSTOM CONFIGURATIONS
      ## RabbitMQ configuration
      ## Ref: https://github.com/rabbitmq/rabbitmq-server/blob/master/docs/rabbitmq.conf.example

      ## Memory-based Flow Control threshold
      vm_memory_high_watermark.absolute = 8GB

      ## END CUSTOM CONFIGURATIONS
containerPorts:
  metrics: 15692
extraPlugins: "rabbitmq_shovel rabbitmq_shovel_management rabbitmq_federation rabbitmq_federation_management rabbitmq_consistent_hash_exchange"
extraEnvVars:
  - name: RABBITMQ_NODENAME
    value: rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.cluster.local
  - name: RABBITMQ_ERLANG_COOKIE
    valueFrom:
      secretKeyRef:
        key: rabbitmq-erlang-cookie
        name: rabbitmq-ha
  - name: RABBIT_MANAGEMENT_USER
    valueFrom:
      secretKeyRef:
        key: rabbitmq-management-username
        name: rabbitmq-ha
  - name: RABBIT_MANAGEMENT_PASSWORD
    valueFrom:
      secretKeyRef:
        key: rabbitmq-management-password
        name: rabbitmq-ha
extraVolumeMounts:
  - mountPath: /etc/definitions
    name: definitions
    readOnly: true
extraVolumes:
  - name: definitions
    secret:
      defaultMode: 420
      items:
        - key: definitions.json
          path: definitions.json
      secretName: rabbitmq-ha
persistence:
  mountPath: /var/lib/rabbitmq
loadDefinition:
  enabled: true
  file: /etc/definitions/definitions.json
  existingSecret: rabbitmq-ha
metrics:
  enabled: true
podSecurityContext:
  fsGroup: 101
  runAsGroup: 101
  runAsNonRoot: true
  runAsUser: 100
containerSecurityContext:
  runAsUser: 100
dnsPolicy: ClusterFirst
schedulerName: default-scheduler
podManagementPolicy: Parallel
podLabels:
  app: rabbitmq-ha
  release: rabbitmq-ha
updateStrategy:
  type: OnDelete
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app: rabbitmq-ha
          topologyKey: kubernetes.io/hostname
        weight: 1
resources:
  limits:
    cpu: "3"
    memory: 16Gi
  requests:
    cpu: 2500m
    memory: 8Gi
livenessProbe:
  failureThreshold: 2
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
readinessProbe:
  failureThreshold: 6
  initialDelaySeconds: 20
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 3
serviceAccount:
  name: rabbitmq-ha
persistence:
  storageClass: ssd
  mountPath: /var/lib/rabbitmq
initContainers:
- args:
    - -c
    - |
      set -ex
      echo "${RABBITMQ_ERLANG_COOKIE}" > /var/lib/rabbitmq/.erlang.cookie
      chown -R 100:101 /var/lib/rabbitmq/
      chmod 400 /var/lib/rabbitmq/.erlang.cookie
  command:
    - sh
  env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: RABBITMQ_MNESIA_DIR
      value: /var/lib/rabbitmq/mnesia/rabbit@$(POD_NAME).rabbitmq-ha-discovery.rabbit.svc.cluster.local
    - name: RABBITMQ_ERLANG_COOKIE
      valueFrom:
        secretKeyRef:
          key: rabbitmq-erlang-cookie
          name: rabbitmq-ha
  image: busybox:1.30.1
  imagePullPolicy: IfNotPresent
  name: bootstrap
  resources: {}
  securityContext:
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  terminationMessagePath: /dev/termination-log
  terminationMessagePolicy: File
  volumeMounts:
    - mountPath: /bitnami/rabbitmq/conf
      name: configuration
    - mountPath: /var/lib/rabbitmq
      name: data
service:
  portNames:
    manager: http
```

### What is the expected behavior?

I expect RabbitMQ to listen on port 15672 as a default configuration.

### What do you see instead?

Nothing listening on port 15672

### Additional information

Output of netstat showing which ports are actively listening

```
netstat -nlp | grep -v unix
netstat: showing only processes with your user ID
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:15006           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:15006           0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:15463         0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      11/beam.smp
tcp        0      0 0.0.0.0:15692           0.0.0.0:*               LISTEN      11/beam.smp
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      72/epmd
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:15001           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:15001           0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:15004         0.0.0.0:*               LISTEN      -
tcp        0      0 :::5672                 :::*                    LISTEN      11/beam.smp
tcp        0      0 :::15020                :::*                    LISTEN      -
tcp        0      0 :::4369                 :::*                    LISTEN      72/epmd
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node PID/Program name    Path
```
