### ISSUE TITLE
Automatically generate Zookeeper tls certs

### ISSUE THREAD

**Issue by denissabramovs** [bitnami/charts#12162]
### Name and Version

bitnami/kafka

### What is the problem this feature will solve?

It will not require to manually generate tls certs and mount/refer them for Zookeeper.
This way, specifying that we want `auth.zookeeper.tls.enabled=true` and `auth.zookeeper.tls.type=pem`, we won't need to generate certs on our own and they will be automatically generated and placed/referred where it's required.

### What is the feature you are proposing to solve the problem?

Automatically generate certs for Zookeper auth.

**Comment by marcosbc** [comment]
Hi @denissabramovs, are you looking for the [`tls.client.autoGenerated` option](https://github.com/bitnami/charts/tree/master/bitnami/zookeeper#tlsssl-parameters)? If not, what are you referring to?

**Comment by Somebi** [comment]
Yes, Zookeeper is a part of kafka helm chart and I haven't found that option there. Possibly I have missed it, will re-check.

**Comment by denissabramovs** [comment]
I have added it and it is not working as it seems:
```
kafka 09:48:06.56 ERROR ==> In order to configure the TLS encryption for Zookeeper with JKS certs you must mount your zookeeper.truststore.jks cert to the /bitnami/kafka/config/certs directory.
kafka 09:48:06.57 WARN  ==> In order to configure the mTLS for Zookeeper with JKS certs you must mount your zookeeper.keystore.jks cert to the /bitnami/kafka/config/certs directory.
```

**Comment by denissabramovs** [comment]
and with `type: pem`:
```
kafka 09:49:06.99 ERROR ==> In order to configure the TLS encryption for Zookeeper with PEM certs you must mount your zookeeper.truststore.pem cert to the /bitnami/kafka/config/certs directory.
kafka 09:49:06.99 WARN  ==> In order to configure the mTLS for Zookeeper with PEM certs you must mount your zookeeper.keystore.pem cert and zookeeper.keystore.key key to the /bitnami/kafka/config/certs directory.
```

**Comment by denissabramovs** [comment]
```
zookeeper:
  ## @param zookeeper.enabled Switch to enable or disable the ZooKeeper helm chart
  ##
  enabled: true
  ## @param zookeeper.replicaCount Number of ZooKeeper nodes
  ##
  replicaCount: 1
  tls:
    client:
      enabled: true
      autoGenerated: true
  ## ZooKeeper authenticaiton
  ##
  auth:
    client:
      ## @param zookeeper.auth.client.enabled Enable ZooKeeper auth
      ##
      enabled: true
```

**Comment by denissabramovs** [comment]
Don't have time for this right now, but i have tried to mount secret into
```
extraVolumes:
  - name: zookeeper-tls-crt
    secret:
      secretName: kafka-zookeeper-client-crt
      items:
        - key: tls.crt
          path: config/certs/tls.crt
        - key: tls.key
          path: config/certs/tls.key
        - key: ca.crt
          path: config/certs/ca.crt
```

And it doesn't work, kafka doesn't see certs. Possibly they should be placed like error is telling, but zookeeper.keystore.pem can't be assembled on the fly, `zookeeper.keystore.pem` is a chain cert I assume.
Joining tls.crt and ca.crt when mounting is kind of problematic.

**Comment by alyvusal** [comment]
Hi, I've also tried to authenticate sasl_tls with separate installed zk chart. Same issue occurs for me.
Seems  `setup.sh` script only consider using JKS stores only. I didn't see and PEM related commands on script. See [this](https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/scripts-configmap.yaml#L182-L193)

I tried to add extra `existingSecretKeystoreKeyKey` to chart default values.yml and for `.key` and on [deploy.sh](https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/scripts-configmap.yaml#L182-L193) script edited like this

```sh
    JKS_TRUSTSTORE={{ printf "/kafka-zookeeper-cert/%s" (.Values.auth.zookeeper.tls.existingSecretTruststoreKey) | quote }}
    JKS_KEYSTORE={{ printf "/kafka-zookeeper-cert/%s" (.Values.auth.zookeeper.tls.existingSecretKeystoreKey) | quote }}
    JKS_KEYSTORE_KEY={{ printf "/kafka-zookeeper-cert/%s" (.Values.auth.zookeeper.tls.existingSecretKeystoreKeyKey) | quote }}
    if [[ -f "$JKS_TRUSTSTORE" ]] && [[ -f "$JKS_KEYSTORE" ]]; then
      CERT_DIR="/opt/bitnami/kafka/config/certs"
      TRUSTSTORE_LOCATION="${CERT_DIR}/zookeeper.truststore.pem"
      cp "$JKS_TRUSTSTORE" "$TRUSTSTORE_LOCATION"
      cp "$JKS_KEYSTORE" "${CERT_DIR}/zookeeper.keystore.pem"
      cp "$JKS_KEYSTORE_KEY" "${CERT_DIR}/zookeeper.keystore.key"
      export KAFKA_ZOOKEEPER_TLS_TRUSTSTORE_FILE="${TRUSTSTORE_LOCATION}"
    fi
```

on deploy values file added:
```yaml
auth:
  zookeeper:
      tls:
        existingSecret: "zk-zookeeper-client-crt"
        existingSecretKeystoreKey: tls.crt
        existingSecretKeystoreKeyKey: tls.key
        existingSecretTruststoreKey: ca.crt
        passwordsSecret: "zk-zookeeper-client-tls-pass"
```
and deployed. 

Still failed with error:
```sh
...
kafka 20:12:02.23 INFO  ==> Creating users in Zookeeper
/opt/bitnami/scripts/libkafka.sh: line 661: /opt/bitnami/kafka/config/certs/zookeeper.keystore.pem: Permission denied
