### ISSUE TITLE
[bitnami/rabbitmq] RabbitMQ initScriptsSecret buggy?

### ISSUE THREAD

**Issue by michalpenka** [bitnami/charts#12161]
### Name and Version

bitnami/rabbitmq:10.2.1

### What steps will reproduce the bug?

1. create a secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-init-scripts
type: Opaque
stringData:
  set-cluster-name.sh: |-
    rabbitmqctl set_cluster_name rabbit@whatever
```
2. set values
`  initScriptsSecret: "rabbitmq-init-scripts"
`
3. helm template
`executing "rabbitmq/charts/rabbitmq/templates/statefulset.yaml" at <{{template ".Values.initScriptsSecret" .}}>: template ".Values.initScriptsSecret" not defined`

### Are you using any custom parameters or values?

` initScriptsSecret: "rabbitmq-init-scripts"`

### What is the expected behavior?

Script is executed on init and cluster is renamed

### What do you see instead?

```
Error: template: rabbitmq/charts/rabbitmq/templates/statefulset.yaml:390:36: executing "rabbitmq/charts/rabbitmq/templates/statefulset.yaml" at <{{template ".Values.initScriptsSecret" .}}>: template ".Values.initScriptsSecret" not defined
helm.go:88: [debug] template: rabbitmq/charts/rabbitmq/templates/statefulset.yaml:390:36: executing "rabbitmq/charts/rabbitmq/templates/statefulset.yaml" at <{{template ".Values.initScriptsSecret" .}}>: template ".Values.initScriptsSecret" not defined
```
