### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] Unable to use persistence due to incorrect mount path

### ISSUE THREAD

**Issue by sarahhenkens** [bitnami/charts#12179]
### Name and Version

bitnami:rabbitmq-cluster-operator:2.7.0

### What steps will reproduce the bug?

Deploy a rabbitmq cluster with persistence enabled:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  persistence:
    storage: 5Gi
  replicas: 1
```

Bitnami's own rabbitmq image stores the data in `/bitnami/rabbitmq/mnesia` while the upstream official image is using `/var/lib/rabbitmq/mnesia`

The operator itself hardcodes this the `/var/lib/rabbitmq/mnesia` mount path in its code: https://github.com/rabbitmq/cluster-operator/blob/e186a81c177043d5f4a764248bbe6bd991027fba/internal/resource/statefulset.go#L447

### What is the expected behavior?

To expect persistence to work

### What do you see instead?

The operator hard-code mounts the PVC on `/var/lib/rabbitmq/mnesia` while the bitnami image defaults its rabbitmq data directory to `/bitnami/rabbitmq/mnesia`, this results any state being lost upon restart of the cluster.

**Comment by sarahhenkens** [comment]
The current work-around is to configure the cluster operator to use the official image instead:

```yaml
  rabbitmqImage:
    registry: docker.io
    repository: rabbitmq
    tag: 3.10.7
```
