### ISSUE TITLE
[bitnami/logstash] Logstash connect to elsaticsearch with ssl

### ISSUE THREAD

**Issue by kuberlive** [bitnami/charts#12178]
### Name and Version

bitnami/logstash 5.0.17

### What steps will reproduce the bug?

1. enable x-pack and security on elasticsearch.
2. 

### Are you using any custom parameters or values?

I can't find any value tp set SSL for logstash on value.yaml file, I have only set elasticsearch address and port:
```
extraEnvVars:
  - name: ELASTICSEARCH_HOST
    value: "http://elastic-elasticsearch"
  - name: ELASTICSEARCH_PORT
    value: "9200"
```

### What is the expected behavior?

connect to elasticsearch and insert my log to index.

### What do you see instead?

Logstash logs:
```
[2022-08-28T19:24:13,410][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http://elastic-elasticsearch:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :message=>"Elasticsearch Unreachable: [http://elastic-elasticsearch:9200/][Manticore::ClientProtocolException] elastic-elasticsearch:9200 failed to respond"}
```
