### ISSUE TITLE
[bitnami/argo-cd] externalRedis doesn't work, missing secret in wait-for-redis container

### ISSUE THREAD

**Issue by jasonhao518** [bitnami/charts#12180]
### Name and Version

bitnami/argo-cd 4.0.6

### What steps will reproduce the bug?

1. install argocd using helm command
   helm upgrade --install -n argocd argocd bitnami/argo-cd --values argocd-bitnami.yaml
2. kubectl get pods to check state

### Are you using any custom parameters or values?
```
redis:
  enabled: false
externalRedis:
   host: data-redis.data.svc.cluster.local
   password: xxxxx
```
### What is the expected behavior?

pod start correctly
```
argocd-argo-cd-app-controller-67b89469b-jfhjz   1/1     Running                           6 (44h ago)   8d
argocd-argo-cd-repo-server-65655484cb-2htwt     1/1     Running                           0             8d
argocd-argo-cd-server-7f7c66745f-jkvpq          1/1     Running                           0             5h6m
```
### What do you see instead?

pods are  in Init:CreateContainerConfigError
```
   argocd-argo-cd-app-controller-8d9bdcf79-48t6l   0/1     Init:CreateContainerConfigError   0             86m
   argocd-argo-cd-repo-server-b4dcb44b5-n6qhw      0/1     Init:CreateContainerConfigError   0             86m
   argocd-argo-cd-server-7f6f69668-bs8zm           0/1     Init:CreateContainerConfigError   0             86m
```
### Additional information

this is because the wait-for-redis container relies on secret {{Release.Name}}-redis-redis which will not be created when using external redis
```
        env:
        - name: REDISCLI_AUTH
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: argocd-redis-redis
```
