### ISSUE TITLE
[bitnami/grafana-loki] gateway.ingress backend is pointing to wrong serviceName and servicePort

### ISSUE THREAD

**Issue by sandeeprohokale** [bitnami/charts#12195]
### Name and Version

bitnami/grafana-loki 2.6.1

### What steps will reproduce the bug?

1. create aws eks cluster and have alb-controller running in cluster
2. deploy bitnami/grafana-loki helm-chart of version 2.6.1 with following overridden values
```
    gateway:
      ingress:`
	   enabled: true`
		pathType: ImplementationSpecific
		hostname: <domain_name>.com
		path: /*
		annotations:
			kubernetes.io/ingress.class: alb
			alb.ingress.kubernetes.io/load-balancer-name: your-load-balancer-name
			alb.ingress.kubernetes.io/scheme: internal
			alb.ingress.kubernetes.io/target-type: ip
			alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:<region>:<account_number>:certificate/<id_string>"
			external-dns.alpha.kubernetes.io/hostname: "<domain_name>.com"
```

3. check gateway-ingress object created in eks cluster. you will notice it is not pointing to gateway service.. for example, if deployed helm-chart name is grafana-loki. then gateway-ingress object backend service name is 'grafana-loki' and port is 'http'.  correct backend service name should be 'grafana-loki-gateway' and service port should be '80' (default)

### Are you using any custom parameters or values?

```
gateway:
	ingress:
	   enabled: true
		pathType: ImplementationSpecific
		hostname: <domain_name>.com
		path: /*
		annotations:
			kubernetes.io/ingress.class: alb
			alb.ingress.kubernetes.io/load-balancer-name: your-load-balancer-name
			alb.ingress.kubernetes.io/scheme: internal
			alb.ingress.kubernetes.io/target-type: ip
			alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:<region>:<account_number>:certificate/<id_string>"
			external-dns.alpha.kubernetes.io/hostname: "<domain_name>.com"


```
### What is the expected behavior?

deployed gateway.ingress  object should have backend service name as 'grafana-loki-gateway' and service port should be '80' (default value).
and when we try to access loki using http/https url, we should not get error message 'backend service is not available'

### What do you see instead?

deployed gateway.ingress  object should have backend service name as 'grafana-loki-gateway' and service port should be '80' (default value).

**Comment by fmulero** [comment]
Hi @sandeeprohokale,

Could you edit the yaml code in the description? Please use [GitHub markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax), the yaml pasted in the description is not correct and we can not use it to reproduce your issue.

**Comment by sandeeprohokale** [comment]
Hi Fran,
I updated yaml with correct formatting. note this yaml is just small
snippet of values.yaml from bitnami/grafana-loki chart

Thanks,
Sandeep

**Comment by sandeeprohokale** [comment]
Hi Fran,I updated yaml with correct formatting. note this yaml is just small snippet of values.yaml from bitnami/grafana-loki chart

**Comment by fmulero** [comment]
Thanks @sandeeprohokale  for opening this issue.

Yes it seems you are right about the backend service. The `ingress` object created for the gateway component should use as `backend`, the `service` created for that component. About using the 80 instead of `http`, I am not sure what you mean because we are using the named port and it should work.  Could you create a PR with your suggested changes? That would be great and we could see better your point

**Comment by sandeeprohokale** [comment]
I already created PR (Pull Request) with suggested changes.. please let me know if you mean meaning something by PR

**Comment by fmulero** [comment]
Please @sandeeprohokale  have look to your PR, you have little things to improve but I think is worth it to include your changes in the main branch

**Comment by erSitzt** [comment]
Are you sure the PR is a fix for this problem ?

only enabling the ingress for the gateway and setting a hostname i end up with this 👍 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: loki2
    meta.helm.sh/release-namespace: loki
  labels:
    app.kubernetes.io/instance: loki2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana-loki
    helm.sh/chart: grafana-loki-2.4.0
    manager: helm
  name: loki2-grafana-loki-gateway
  namespace: loki
spec:
  ingressClassName: kong
  rules:
  - host: loki2.rke2-zentrale-monitoring.kong.mydomain.com
    http:
      paths:
      - backend:
          service:
            name: loki2-grafana-loki
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
```

Which refers to a service which does not exist.

And this is the list of services available after deploying
<img width="309" alt="image" src="https://user-images.githubusercontent.com/1625376/191279606-b1c83401-4c55-49ca-b13d-a73931efe6bb.png">

Using `loki2-grafana-loki-query-frontend` as the target service works, but thats not the change i can see in the PR, or is it ?
