### ISSUE TITLE
[bitnami/rabbitmq] Unable to use existing PVCs in values.yaml

### ISSUE THREAD

**Issue by zohebs341** [bitnami/charts#12228]
### Name and Version

bitname/rabbitmq 3.10.7

### What steps will reproduce the bug?

I've deployed rabbitmq using bitnami charts in Azure AKS 1.22.11. (https://bitnami.com/stack/rabbitmq/helm)

I am having existing PVC, which I want to use as a part of the installation. Like in any statefulset, we can use existing PVCs like below.
```yaml
volumeClaimTemplates:
    - metadata:
        name: persistent-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: managed-csi
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
```
In a similar manner, I want to define existing PVC so that i can get 3 PVCs - If replicas set is 3. Basically I want my existing PVC to be used as a part of installation. 

When I used the below config in values.yaml, all the pods are trying to use the same PVC and it's failing. Dynamic provisioning is not happening with existing PVCs.

Run this: using rabbitmq values.yaml
```yaml
persistence:
  enabled: true
  storageClass: ""
  selector: {}
  ## @param persistence.accessModes PVC Access Modes for RabbitMQ data volume
  ##
  accessModes:
    - ReadWriteOnce
  existingClaim: pvc-rabbitmq-0
  mountPath: /bitnami/rabbitmq/mnesia
  subPath: ""
  size: 8Gi
```
Error:
```
Events:
  Type     Reason              Age                 From                     Message
  ----     ------              ----                ----                     -------
  Normal   Scheduled           19m                 default-scheduler        Successfully assigned rabbitmq/rabbitmq-1 to aks-agentpool-10440409-vmss000005
  Warning  FailedAttachVolume  19m                 attachdetach-controller  Multi-Attach error for volume "pv-rabbimtq-0" Volume is already used by pod(s) rabbitmq-0
```
### Are you using any custom parameters or values?

Yes, I am using existing PVCs in values.yaml
```yaml
persistence:
  enabled: true
  storageClass: ""
  selector: {}
  ## @param persistence.accessModes PVC Access Modes for RabbitMQ data volume
  ##
  accessModes:
    - ReadWriteOnce
  existingClaim: pvc-rabbitmq-0
  mountPath: /bitnami/rabbitmq/mnesia
  subPath: ""
  size: 8Gi
```
### What is the expected behavior?

Pods should be up/running with 3 PVCs.

### What do you see instead?
```
Events:
  Type     Reason              Age                 From                     Message
  ----     ------              ----                ----                     -------
  Normal   Scheduled           19m                 default-scheduler        Successfully assigned rabbitmq/rabbitmq-1 to aks-agentpool-10440409-vmss000005
  Warning  FailedAttachVolume  19m                 attachdetach-controller  Multi-Attach error for volume "pv-rabbimtq-0" Volume is already used by pod(s) rabbitmq-0

shaik [ ~ ]$ kubectl get pods -n rabbitmq
NAME         READY   STATUS              RESTARTS   AGE
rabbitmq-0   1/1     Running             0          20m
rabbitmq-1   0/1     ContainerCreating   0          19m
```

**Comment by fmulero** [comment]
Hi @zohebs341

Have you taken a look #3219 ? Are you facing the same problem?

Also, Could you use [GitHub markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to apply a readable format in the description? Is very difficult to read the code you pasted.

**Comment by zohebs341** [comment]
@fmulero Yes, I'm trying to achieve the same.

Basically existing PVC, I'm trying to use it via values.yaml file. But it's not working.

Is it a limitation? In statefulsets, I'm able to use it. But not using helm/values

**Comment by zohebs341** [comment]
The same applies to MongoDB as well.

bitnami/mongodb-sharded

Basically, if we have 2-3 persistent volume claims then it's not working from values.yaml file.

The same is working for a statefulset.yaml file(For both RabbitMQ & MongoDB), where we can define PVC details for reusing.

It's not possible to use it from values.yaml?

**Comment by marcosbc** [comment]
Currently it is only possible to specify `volumeClaimTemplates` in the following way:

```
  ## Fine tuning for volumeClaimTemplates
  ##
  volumeClaimTemplates:
    ## @param persistence.volumeClaimTemplates.selector A label query over volumes to consider for binding (e.g. when using local volumes)
    ## A label query over volumes to consider for binding (e.g. when using local volumes)
    ## See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#labelselector-v1-meta for more details
    ##
    selector: {}
    ## @param persistence.volumeClaimTemplates.requests Custom PVC requests attributes
    ## Sometime cloud providers use additional requests attributes to provision custom storage instance
    ## See https://cloud.ibm.com/docs/containers?topic=containers-file_storage#file_dynamic_statefulset
    ##
    requests: {}
    ## @param persistence.volumeClaimTemplates.dataSource Add dataSource to the VolumeClaimTemplate
    ##
    dataSource: {}
```

If you would like to improve the way it works, feel free to send a PR! We would be happy to review it and help with the merge and release of the changes.
