### ISSUE TITLE
[bitnami/oauth2-proxy] secret key gets `redis-` prefix

### ISSUE THREAD

**Issue by jasperjonker** [bitnami/charts#12236]
### Name and Version

bitnami/oauth2-proxy 3.3.0

### What steps will reproduce the bug?

With the folling values.yaml config:
```yaml
  redis:
    enabled: true
    auth:
      enabled: true
      existingSecret: redis-oauth-password
      existingSecretPasswordkKey: password
```

It is looking for the key `redis-password`, not `password` in the secret `redis-oauth-password`:

```yaml
containers:
    - args:
        - '--http-address=0.0.0.0:4180'
        - '--config=/bitnami/oauth2-proxy/conf/oauth2_proxy.cfg'
      env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client-id
              name: oauth2-proxy
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client-secret
              name: oauth2-proxy
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: cookie-secret
              name: oauth2-proxy
        - name: OAUTH2_PROXY_SESSION_STORE_TYPE
          value: redis
        - name: OAUTH2_PROXY_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: redis-oauth-password
        - name: OAUTH2_PROXY_REDIS_CONNECTION_URL
          value: 'redis://oauth2-proxy-redis-master:6379'
```

and therefore gives the error:
`Error: couldn't find key redis-password in Secret kibana/redis-oauth-password`

### What is the expected behavior?

When specifying `existingSecretPasswordkKey` in the values.yaml, actually use that value and not have `redis-` as a prefix.

### What do you see instead?

`Error: couldn't find key redis-password in Secret kibana/redis-oauth-password`
