### ISSUE TITLE
[bitnami/solr] Long user and group ids leads to unusable charts

### ISSUE THREAD

**Issue by PascalTurbo** [bitnami/charts#12232]
### Name and Version

bitnami/solr:6.1.3

### What steps will reproduce the bug?

1. enable the volume permissions init-container by setting
```YAML
  volumePermissions:
    enabled: true
```
2. Set a long fsgroup 
```YAML
   podSecurityContext:
    enabled: true
    fsGroup: 1000860000
  containerSecurityContext:
    enabled: true
    runAsUser: 1000860000
    runAsNonRoot: true

### Are you using any custom parameters or values?

See Steps to reproduce

### What is the expected behavior?

The init-container should set the correct permissions like
`chown -R 1000860000:1000860000`

### What do you see instead?

The ids gets converted to scientific notation and the init-container will crash
`chown -R 1.00086e+09:1.00086e+09`

### Additional information

See helm documentation: https://helm.sh/docs/chart_best_practices/values/#make-types-clear

They recommend not to use integer and use strings instead and convert them to int when needed.

**Comment by fmulero** [comment]
Hi @PascalTurbo, thanks for opening this issue

Have you tried quoting the `fsGroup` ?
```
   podSecurityContext:
    enabled: true
    fsGroup: "1000860000"
  containerSecurityContext:
    enabled: true
    runAsUser: "1000860000"
    runAsNonRoot: true
```
