### ISSUE TITLE
[bitnami/keycloak] Configure scraping of realm metrics and add rules and a dashboard

### ISSUE THREAD

**Issue by maxnitze** [bitnami/charts#12250]
### Name and Version

bitnami/keycloak 9.7.2

### What is the problem this feature will solve?

Keycloak exposes realm metrics on `/realms/master/metrics` (actually they are available at `/realms/<ANY REALM NAME HERE>/metrics`). But the service monitor only configures an endpoint for the server statistics at `/metrics`.

Besides that there are no default Prometheus rules in the chart. And no Grafana dashboard.

### What is the feature you are proposing to solve the problem?

Add scraping of the realm metrics, add the [Prometheus rules from the Keycloak Operator](https://github.com/keycloak/keycloak-operator/blob/master/pkg/model/prometheus_rule.go) and add a dashboard based on [this](https://grafana.com/grafana/dashboards/10441) dashboard from Grafana Labs.

I would like to provide the PR for this, but I'm not entirely sure on how to do it. I would like to make it all optional and deactivate it by default, so that updating will not change anything in the release.

My idea is adding keys like this:

```yaml
metrics:
  serviceMonitor:
    enabledRealmMetrics: false

  prometheusRules:
    group1:
      rule1: # add the rules from the operator here
        alert: KeycloakJavaNonHeapThresholdExceeded
        ...

  grafanaDashboards:
    enabled: false
    namespace: monitoring
    labels: {}
    prometheusInstance: default
```

And the respective templates of course.

My open questions are:
* Does it make sense to just add a toggle for the realm metrics? Or should I just enable them when the service monitor is enabled? Or should it get a whole group, so one can configure everything (like relabellings, ...) for it as well?
* Is it ok to add the rules from the operator? Or should it just be empty and the user adds his or her own rules?
* Is it ok to add a dashboard from Grafana Labs? Or should this also be done by the user?

### What alternatives have you considered?

I added the features to my own chart, that depends on this one. But I think it is a valuable addition to the chart. So I'd like to add it here as well.

**Comment by erickaby** [comment]
@maxnitze did you end up creating a Grafana dashboard for these metrics?

**Comment by maxnitze** [comment]
@erickaby no, I decided against providing a default dashboard. From my experience the dashboards are highly _personalized_. So providing a default one is probably not the best idea, when you cannot manipulate it. And changing or overwriting it is not that easy, when the template is in the base chart.

My setup now looks like this: I have my own Keycloak chart, that has this one as a dependency. I configure all my values there, per instance. And inside I have a folder `files/grafana-dashboards` with a json file with my dashboard (a copy from https://grafana.com/grafana/dashboards/14607 with some changes) and a template `configmap-grafana-dashboards.yaml` with the following content:

```yaml
{{- if .Values.keycloak.metrics.serviceMonitor.enabled }}
{{- $files := .Files.Glob "files/grafana-dashboards/*.json" }}
{{- if $files }}
{{- if .Values.grafanaDashboards.enabled }}
apiVersion: v1
kind: ConfigMapList
items:
{{- range $path, $fileContents := $files }}
{{- $dashboardName := regexReplaceAll "(^.*/)(.*)\\.json$" $path "${2}" }}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: {{ printf "%s-dashboard-%s" $.Release.Name $dashboardName | trunc 63 | trimSuffix "-" }}
    namespace: {{ default $.Release.Namespace $.Values.grafanaDashboards.namespace }}
    labels:
      {{- include "common.labels.standard" $.Subcharts.keycloak | nindent 6 }}
      prometheus: {{ $.Values.grafanaDashboards.prometheusInstance }}
      grafana_dashboard: "1"
      {{- if $.Values.grafanaDashboards.labels }}
      {{ toYaml $.Values.grafanaDashboards.labels | nindent 4}}
      {{- end }}
  data:
    {{ $dashboardName }}.json: {{ $.Files.Get $path | toJson }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}
```

The config block in my `values.yaml` looks like this:

```yaml
grafanaDashboards:
  enabled: true
  namespace: monitoring
  labels: {}
  prometheusInstance: default
```

Hope this helps you :)
