### ISSUE TITLE
[bitnami/mediawiki] certManager always creates certificate without deprecated value

### ISSUE THREAD

**Issue by fernferret** [bitnami/charts#12266]
### Name and Version

bitnami/mediawiki 14.3.1

### What steps will reproduce the bug?

1. Setup mediawiki with CertManager
2. Follow the advice not to use `ingress.certManager`, instead add `cert-manager.io/cluster-issuer: my-issuer`
3. A self-signed certificate is created, because ingress.certManager was not set
4. ~~`Certificate` is created, but cert-manager cannot create the `Secret` because it's already owned by helm and contains a self-signed certificate.~~

#### UPDATE

This is not as critical than I had originally thought. I actually had an error in my cert-manager config (missing a `commonName` annotation which was required for my issuer) which was causing me to think that `cert-manager` couldn't update the `Secret`, however, I don't think it should be created regardless, as this will cause pain for anyone using something like ArgoCD or helm diff:

```console
$ helm diff upgrade -n wiki -f mediawiki-lts.yaml mediawiki-lts ../oss/mediawiki
wiki, wiki.example.com-tls, Secret (v1) has changed:
  # Source: mediawiki/templates/tls-secrets.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app.kubernetes.io/instance: mediawiki-lts
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: mediawiki
      helm.sh/chart: mediawiki-14.3.1
    name: wiki.example.com-tls
    namespace: wiki
  data:
-   ca.crt: '-------- # (1135 bytes)'
-   tls.crt: '-------- # (1180 bytes)'
-   tls.key: '-------- # (1679 bytes)'
+   ca.crt: '++++++++ # (1135 bytes)'
+   tls.crt: '++++++++ # (1180 bytes)'
+   tls.key: '++++++++ # (1675 bytes)'
```

### Are you using any custom parameters or values?

Corrected `values.yaml`:

```yaml
# helm diff upgrade -n wiki -f mediawiki-lts.yaml mediawiki-lts ../oss/mediawiki

global:
  storageClass: "local-path"

service:
  type: ClusterIP

nodeSelector:
  kubernetes.io/hostname: myhostname

ingress:
  enabled: true
  hostname: wiki.example.com
  annotations:
    cert-manager.io/cluster-issuer: my-issuer
    cert-manager.io/common-name: wiki.example.com
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  tls: true
  # NOTE: This is marked as deprecated, but we need it to not create secrets
  # certManager: true

mediawikiHost: "wiki.example.com"

mariadb:
  auth:
    # example authentication for a demo
    rootPassword: "rootymcrootface"
    password: "mywikikdatabasepassword"

# example authentication for a demo
mediawikiPassword: "mywikipass"

image:
  tag: 1.35.2-debian-10-r42 # I like being on the LTS release
  debug: true
```

Issue originally posted with:

```yaml
# helm diff upgrade -n wiki -f mediawiki-lts.yaml mediawiki-lts ../oss/mediawiki

global:
  storageClass: "local-path"

service:
  type: ClusterIP

nodeSelector:
  kubernetes.io/hostname: myhostname

ingress:
  enabled: true
  hostname: wiki.example.com
  annotations:
    cert-manager.io/cluster-issuer: my-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  tls: true
  # NOTE: This is marked as deprecated, but we need it to not create secrets
  # certManager: true

mediawikiHost: "wiki.example.com"

mariadb:
  auth:
    # example authentication for a demo
    rootPassword: "rootymcrootface"
    password: "mywikikdatabasepassword"

# example authentication for a demo
mediawikiPassword: "mywikipass"

image:
  tag: 1.35.2-debian-10-r42 # I like being on the LTS release
  debug: true
```

### What is the expected behavior?

If `cert-manager` annotations are detected, the self-signed certificate `Secret` should not be created. This should be put in place before the deprecation removal to give folks time to migrate to annotations.

#### UPDATE

I'll leave the details below because it was still a bit strange/fun to follow, but cert-manager had a cert-manager issue, so cert-manager will "take ownership" of this `Secret` but it will cause deltas in helm-diff and ArgoCD (and other reconciliation based tools).

#### Original

```console
$ kubectl get secret -n wiki wiki.example.com-tls -o yaml
apiVersion: v1
data:
  ca.crt: ...
  tls.crt: ...
  tls.key: ...
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: mediawiki-lts
    meta.helm.sh/release-namespace: wiki
  creationTimestamp: "..."
  labels:
    app.kubernetes.io/instance: mediawiki-lts
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mediawiki
    helm.sh/chart: mediawiki-14.3.1
  name: wiki.example.com-tls
  namespace: wiki
  resourceVersion: "..."
  uid: ...
type: kubernetes.io/tls
```

A secret is created, if a user visits the mediawiki page, it has the wrong certificate.
