### ISSUE TITLE
Cannot connect from a vnet to the Redis Cluster installed  in AKS on another vnet

### ISSUE THREAD

**Issue by mchen999** [bitnami/charts#12262]
### Name and Version

bitnami/redis-cluster, latest

### What steps will reproduce the bug?

Install the redis cluster via helm after changing the following two settings on AKS (azure k8s)
`--service.beta.kubernetes.io/azure-load-balancer-internal: "true"`
`--type: LoadBalancer`

Now we will have a cluster/svc like below
```
NAME                                                          TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)                      AGE
test-dev-redis-cluster                                         LoadBalancer   10.0.16.157   10.10.1.34    6379:30340/TCP               32d
```

Now from anywhere in the vnet where the aks is installed, we can connect, and all are fine.  Using the external IP. the external IP is actually just a private IP in the vnet. 

### What is the expected behavior?

Now the problem is: we need to access this Redis Cluster from another Azure vnet. There we have problems due to re-direct.  Of course, in order to connect from another vnet, we need to expose this cluster via Private link service and add a private endpoint from the connecting vnet. Your helm chart handles configuring all necessary in the AKS internal load balancer :-)

Connecting using redis-cli using the private endpoint (10.2.3.41 is the IP of the private endpoint)
```
>>redis-cli  -h 10.2.3.41 -a LcMFNNdlAnIM -c
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
10.2.3.41:6379> get one
"111111"
10.2.3.41:6379> get two
-> Redirected to slot [2127] located at 10.10.1.28:6379
Could not connect to Redis at 10.10.1.28:6379: Connection timed out
```

### What do you see instead?

You see, the first key returns fine. but the 2nd key, it hangs. 
This is because the redis cli is connected to the cluster, if the data is in the same node it is connected to, it gets the data and just returns. But if the data is on another redis pod/node, it has to redirect to 10.10.1.28, which is on another vnet. The redis cli on another vnet has no idea of the IP. It only knows the IP of the private endpoint.

We validated this using networking tracing, when redirected, the redis-cli client is re-establishing a connection between itself and wherever it is re-directed. And it cannot because there are on different vnets.

I see there are options like `hostNetwork` in the chart. Tried to change it to true. But the cluster won't even start this way.
```yaml
    hostNetwork: true
```
So is this expected? Is there a way to make it work across vnets (not via vnet peering)? If so, please advise. 

### Additional information

So this thread, but we cannot figure out what to change in your chart to make it work.
https://github.com/Grokzen/docker-redis-cluster/issues/30

Feel there is something we can do here. 
This is very important to us. Thank you so much for looking into this.

Martin C.

**Comment by marcosbc** [comment]
Hi @mchen999, this looks like a networking issue on Azure, have you considered asking their support about this? My understanding is that it is not possible to access private IP addresses from a different VNet without peering them, but I could be wrong, and they might be able to help you with this particular issue.

**Comment by xtianus79** [comment]
@mchen999 How would you be on a different vnet?

**Comment by xtianus79** [comment]
@javsalgar So for me I got the same error in Azure but it is a different thing and it is fixable. Also, the link you posted about the cluster topology is great. Here is my 1 question:

Do you do both? meaning you do you assign the service load balancer? 

For the service, I do have a LB and corresponding IP; but this is very different than the `externalAccess` setting you mention regarding the chart.  The setting below makes it seem as if I could load balance my way into the connection and thus connect to a load balanced redis-cluster configuration. <<< Just reading that I feel it's wrong. Yet, the option is available so maybe it's not. 

So going to `externalAccess` and setting `cluster.externalAccess.service.loadbalancerIP: [...,...,...]` this it seems as if those 2 things don't connect/go together. Or do they? 

What is the difference of this 
`cluster.externalAccess.service.loadbalancerIP`
or this
`service.loadBalancerIP`

If I do one setting do I have to worry about the other setting. 

Lastly, if this `cluster.externalAccess.service.loadbalancerIP` doesn't depend on this `service.loadBalancerIP` . What is `service.loadBlancerIP` for?

``` yaml
  type: LoadBalancer
  ## @param service.clusterIP Service Cluster IP
  ## e.g.:
  ## clusterIP: None
  ##
  clusterIP: ""
  ## @param service.loadBalancerIP Load balancer IP if `service.type` is `LoadBalancer`
  ## If service.type is LoadBalancer, request a specific static IP address if supported by the cloud provider, otherwise leave blank
  ##
  ## Altered 4
  loadBalancerIP: "77.myip.here.0"
  ## @param service.loadBalancerSourceRanges Service Load Balancer sources
  ## ref: https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
  ## e.g:
  ## loadBalancerSourceRanges:
  ##   - 10.10.10.0/24
  ##
  loadBalancerSourceRanges: []
```
