### ISSUE TITLE
VisualEditor not working in sub-pages in MediaWiki 1.35

### ISSUE THREAD

**Issue by fernferret** [bitnami/charts#12278]
### Name and Version

bitnami/mediawiki 1.35

### What is the problem this feature will solve?

VisualEditor is great and included in MediaWiki 1.35+

### What is the feature you are proposing to solve the problem?

Allow native configuration of the VisualEditor to work with the bitnami MediaWiki helm chart.

### What alternatives have you considered?

I actually came here after finding old issue: https://github.com/bitnami/bitnami-docker-mediawiki/issues/84

@kachkaev has a lot of great information and I've come up with a workaround based on his work
that does not require any modifications to the stock bitnami chart and will persist with 
restarts (via the `extraDeploy` directive).

The one difference I experienced was that I had to enable some of the custom "docker" settings
for VisualEditor [per the VisualEditor "Linking with Parsoid"](https://www.mediawiki.org/wiki/Extension:VisualEditor#Linking_with_Parsoid) section. These are called out specifically below.

This is a reasonably standard feature so it'd be really great if it didn't require
modification (overwrite mounting) of files to get it working after applying settings in the LocalSettings.php.

It'd also be nice to include the snippet below at least in the readme to describe how to enable VisualEditor (maybe this belongs in the helm chart?) as this took me a little while to figure out, especially with the bitnami portions.

It should be noted that I am running the LTS release so maybe some of these items are no longer required.

### Full example Helm chart values file (with certmanager)

```yaml
# Chart version at time of writing: 14.3.1
# helm diff upgrade -n wiki -f mediawiki-lts.yaml mediawiki-lts ../oss/mediawiki

global:
  storageClass: "local-path"

service:
  type: ClusterIP

nodeSelector:
  kubernetes.io/hostname: myhostname

ingress:
  enabled: true

  hostname: mywiki.example.com
  annotations:
    cert-manager.io/cluster-issuer: mycluster-issuer
    cert-manager.io/common-name: mywiki.example.com
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  tls: true

mediawikiHost: "mywiki.example.com"

# Example credentials for a demo
mariadb:
  auth:
    rootPassword: "rootymcrootface"
    password: "mywikikdatabasepassword"

# Example credentials for a demo
mediawikiPassword: "mywikipass"

# I'm currently using the LTS release, but this should work fine with 1.38+
image:
  tag: 1.35.2-debian-10-r42 # LTS
  # debug: true

extraDeploy:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: '{{ template "common.names.fullname" $ }}-custom-vhost'
    data:
      # This is identical to the stock `vhost.conf` file, but this adds the
      # `AllowEncodedSlashes NoDecode` argument in the <VirtualHost> block
      vhost.conf: |-
        <VirtualHost 127.0.0.1:8080 _default_:8080>
          ServerAlias *
          DocumentRoot /opt/bitnami/mediawiki
          AllowEncodedSlashes NoDecode
          <Directory "/opt/bitnami/mediawiki">
            Options -Indexes +FollowSymLinks -MultiViews
            AllowOverride None
            Require all granted
            RewriteEngine On
            RewriteRule ^/?wiki(/.*)?$ %{DOCUMENT_ROOT}/index.php [L]
          </Directory>
          Include "/opt/bitnami/apache/conf/vhosts/htaccess/mediawiki-htaccess.conf"
        </VirtualHost>

extraVolumes:
  - name: custom-vhost
    configMap:
      name: '{{ template "common.names.fullname" $ }}-custom-vhost'

extraVolumeMounts:
  - name: custom-vhost
    mountPath: /opt/bitnami/apache/conf/vhosts/mediawiki-vhost.conf
    subPath: vhost.conf
```

Here are the important settings to get `VisualEditor` working:

```php
# NOTE: The MediaWiki manual states that if the `wgVirtualRestConfig` is set, this needs to be 
# set as well. This was my experience, but if the full path is not uses, the bitnmai container 
# crashes on startup stating it couldn't find the extension.json file.
#
# wfLoadExtension( 'Parsoid', 'vendor/wikimedia/parsoid/extension.json' );
#
# Here is the full correct form:
wfLoadExtension( 'Parsoid', '/opt/bitnami/mediawiki/vendor/wikimedia/parsoid/extension.json' );

# With the Bitnami helm chart, the apache is configured to serve on port :8080.
# this can also be seen above in the overridden `vhost.conf` file.
$wgVirtualRestConfig['modules']['parsoid'] = array(
    // The apache container serves up rest.php on :8080 in the helm chart.
    'url' => "http://localhost:8080/rest.php",

    // Default:
    // 'url' => $wgServer . $wgScriptPath . '/rest.php',

    // Do NOT set the domain, it will be pulled automatically from wgServer above
    // Parsoid "domain", see below (optional, rarely needed)
    // 'domain' => 'localhost',
);
```

Finally, here's an example of a fully working demo `LocalSettings.php` for anyone looking for a reference.

```php
<?php
# This file was automatically generated by the MediaWiki 1.35.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "MyWiki";
$wgMetaNamespace = "MyWiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = '';

## The protocol and server name to use in fully-qualified URLs
$wgServer = '//mywiki.example.com';

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/wiki.png" ];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = 'admin@example.com';
$wgPasswordSender = 'wiki@example.com';

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "mediawiki-lts-mariadb";
$wgDBname = "bitnami_mediawiki";
$wgDBuser = "bn_mediawiki";
$wgDBpassword = "mywikikdatabasepassword";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale. This should ideally be set to an English
## language locale so that the behaviour of C library functions will
## be consistent with typical installations. Use $wgLanguageCode to
## localise the wiki.
$wgShellLocale = "C.UTF-8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "xxx";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "xxx";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

# End of automatically generated settings.
# Add more configuration options below.
$wgArticlePath = "/wiki/$1";
$wgUsePathInfo = true;

# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtensions('ExtensionName');
# to LocalSettings.php. Check specific extension documentation for more details.

wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'WikiEditor' );

wfLoadExtension( 'Cite' );
wfLoadExtension( 'Poem' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'Renameuser' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'Interwiki' );

# Enable VisualEditor and TemplateData
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'TemplateData' );

# To grant sysops permissions to edit interwiki data
$wgGroupPermissions['sysop']['interwiki'] = true;

# Disable anonymous editing
$wgGroupPermissions['*']['edit'] = false;

# We use external images for status and stuff.
$wgAllowExternalImages = true;

# wfLoadExtension( 'Parsoid', 'vendor/wikimedia/parsoid/extension.json' );
wfLoadExtension( 'Parsoid', '/opt/bitnami/mediawiki/vendor/wikimedia/parsoid/extension.json' );

$wgVirtualRestConfig['modules']['parsoid'] = array(
    // The apache container serves up rest.php on :8080 in the helm chart.
    'url' => "http://localhost:8080/rest.php",

    // Default:
    // 'url' => $wgServer . $wgScriptPath . '/rest.php',

    // Do NOT set the domain, it will be pulled automatically from wgServer above
    // Parsoid "domain", see below (optional, rarely needed)
    // 'domain' => 'localhost',
);

### Enable Syntax Highlighter
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
```
