### ISSUE TITLE
[wordpress] hpa resource order

### ISSUE THREAD

**Issue by Atoms** [bitnami/charts#12277]
### Name and Version

bitnami/wordpress-15.1.5

### What steps will reproduce the bug?

When using Argocd to sync resources desired and live manifest differs

### Are you using any custom parameters or values?

no custom values, just enable autoscaling

### What is the expected behavior?

Resource is in sync, live manifest matches desired manifest

### What do you see instead?

![image](https://user-images.githubusercontent.com/9615/188374980-b5938520-76bc-424d-9cf0-91552e0e03e8.png)

### Additional information

Manifest generated from Helm chart:
```YAML
---
# Source: wordpress/templates/hpa.yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: release-name-wordpress
  namespace: "default"
  labels:
    app.kubernetes.io/name: wordpress
    helm.sh/chart: wordpress-15.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: release-name-wordpress
  minReplicas: 1
  maxReplicas: 11
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 70
```

**Comment by carrodher** [comment]
I'm not sure what should be modified in the bitnami/wordpress Helm chart. In the hpa template everything is defined as expected, see
```yaml
  metrics:
    {{- if .Values.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.autoscaling.targetCPU }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPU }}
        {{- end }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.autoscaling.targetMemory }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemory }}
        {{- end }}
    {{- end }}
```
This order is fixed there and it is not modified. It seems an issue about how ArgoCD renders, could you please fill an issue in the ArgoCD project? We can't help with this issue
