### ISSUE TITLE
[ExternalDNS] RBAC missing CRD configuration

### ISSUE THREAD

**Issue by darkn3rd** [bitnami/charts#12276]
### Name and Version

bitnami/external-dns 6.8.1

### What steps will reproduce the bug?

1. Install external-dns helm chart as per instructions https://artifacthub.io/packages/helm/bitnami/external-dns
2. In particular, attention to this area:
   ```yaml
   crd:
     create: true
     apiversion: externaldns.nginx.org/v1
     kind: DNSEndpoint
   rbac:
     create: true
     apiVersion: v1
   ```
3. Check Logs

### Are you using any custom parameters or values?

```yaml
provider: google
google:
  zoneVisibility: public
  project: {{ env "DNS_PROJECT_ID" }}
sources:
  - crd
  - service
  - ingress
# use with NGINX VirtualServer CRD
crd:
  create: true
  apiversion: externaldns.nginx.org/v1
  kind: DNSEndpoint
serviceAccount:
  annotations:
    # google workgroup identity annotation
    iam.gke.io/gcp-service-account: {{ requiredEnv "DNS_SA_EMAIL" }}
nodeSelector:
  # deploy on nodes that support workgroup identity
  iam.gke.io/gke-metadata-server-enabled: "true"
logLevel: {{ env "EXTERNALDNS_LOG_LEVEL" | default "debug" }}
domainFilters:
  - {{ requiredEnv "DNS_DOMAIN" }}
txtOwnerId: external-dns
rbac:
  create: true
  apiVersion: v1
policy: upsert-only
```

### What is the expected behavior?

There would not be errors.  I expected that the configuration for the CRD would have been added to the RBAC.

These rules would be included in additional to other rules:

```yaml
rules:
- apiGroups: ["externaldns.nginx.org"]
  resources: ["dnsendpoints"]
  verbs: ["get","watch","list"]
- apiGroups: ["externaldns.nginx.org"]
  resources: ["dnsendpoints/status"]
```

### What do you see instead?

I got this error:

```
time="2022-09-05T03:57:27Z" level=error msg="dnsendpoints.externaldns.nginx.org is forbidden: User \"system:serviceaccount:kube-addons:external-dns\" cannot list resource \"dnsendpoints\" in API group \"externaldns.nginx.org\" at the cluster scope"
```

The `ClusterRole`  had the following rules:

```yaml
  rules:
  - apiGroups: [""]
    resources: ["services", "pods", "nodes","endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "networking.k8s.io", "getambassador.io"]
    resources: ["ingresses", "hosts"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.istio.io"]
    resources:  ["gateways", "virtualservices"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["zalando.org"]
    resources: ["routegroups"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["zalando.org"]
    resources: ["routegroups/status"]
    verbs: ["patch", "update"]
  - apiGroups: ["projectcontour.io"]
    resources: ["httpproxies"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["gloo.solo.io", "gateway.solo.io"]
    resources: "proxies", "virtualservices"
    verbs: ["get", "list", "watch"]
  - apiGroups: ["configuration.konghq.com"]
    resources: ["tcpingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["externaldns.k8s.io"]
    resources: ["dnsendpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["externaldns.k8s.io"]
    resources: ["dnsendpoints/status"]
    verbs: ["update"]
```

**Comment by carrodher** [comment]
Please note the `crd.create` parameter will install and use the integrated DNSEndpoint CRD invalidating any other custom CRD.
If you would like to use `externaldns.nginx.org/v1`, `crd.create` should be set to false (the default value).

Please, see below an example using the following `values.yaml` file:
```yaml
 ## Options for the source type "crd"
 ##
 crd:
   ## @param crd.create Install and use the integrated DNSEndpoint CRD
   ##
   create: false
   ## @param crd.apiversion Sets the API version for the CRD to watch
   ##
   apiversion: "externaldns.nginx.org/v1"
   ## @param crd.kind Sets the kind for the CRD to watch
   ##
   kind: "DNSEndpoint"
```
We can see how at the end of the rendered template there are a couple of rules for `externaldns.nginx.org/v1`:
```console
$ helm template bitnami/external-dns -s templates/clusterrole.yaml -f values.yaml
---
# Source: external-dns/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-external-dns-default
  namespace: "default"
  labels:
    app.kubernetes.io/name: external-dns
    helm.sh/chart: external-dns-6.8.1
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - nodes
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - "networking.k8s.io"
      - getambassador.io
    resources:
      - ingresses
      - hosts
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.istio.io
    resources:
      - gateways
      - virtualservices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - zalando.org
    resources:
      - routegroups
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - zalando.org
    resources:
      - routegroups/status
    verbs:
      - patch
      - update
  - apiGroups:
      - projectcontour.io
    resources:
      - httpproxies
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - gloo.solo.io
      - gateway.solo.io
    resources:
      - proxies
      - virtualservices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - configuration.konghq.com
    resources:
      - tcpingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - externaldns.nginx.org
    resources:
      - dnsendpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - externaldns.nginx.org
    resources:
      - dnsendpoints/status
    verbs:
      - update
```
