### ISSUE TITLE
[bitnami/rabbitmq] Failed to lock with peer discovery backend rabbit_peer_discovery_k8s

### ISSUE THREAD

**Issue by Aadarsh-Verma** [bitnami/charts#12283]
### Name and Version

bitnami/rabbitmq 9.1.0

### What steps will reproduce the bug?

helm install with custom-values.
I do not face this issue with minikube and gcp k8s cluster.
Only face this with out local k8s setup.

### Are you using any custom parameters or values?
```
replicaCount: 3

podManagementPolicy: Parallel
extraPlugins: "rabbitmq_auth_backend_ldap rabbitmq_federation"
auth:
  username: eYeContact
  password: hello
volumePermissions:
  enabled: true

extraEnvVars:
  - name: LOG_LEVEL
    value: debug
```

### What do you see instead?

Rabbitmq Error logs on 

https://paste.sh/U_XhY_mY#b2iXK9AShDKTYfyxoaguLey4

### Additional information

The helm chart runs fine on minikube and digital ocean k8s cluster only on my custom k8s cluster it is creating this problem.
