### ISSUE TITLE
[bitnami/mongodb-sharded] - Unable to use existing PVCs in values.yaml

### ISSUE THREAD

**Issue by zohebs341** [bitnami/charts#12290]
### Name and Version

bitnami/mongodb-sharded 4.4.9-debian-10-r20

### What is the problem this feature will solve?

I want to use my existing PVCs(2-3 PVCs) by defining them in mongodb-sharded values.yaml. If it is one PVC, then we can use it this:
```yaml
persistence:
  enabled: true
  storageClass: ""
  selector: {}
  ## @param persistence.accessModes PVC Access Modes for RabbitMQ data volume
  ##
  accessModes:
    - ReadWriteOnce
  existingClaim: pvc-rabbitmq-0
  mountPath: /bitnami/rabbitmq/mnesia
  subPath: ""
  size: 8G
```
But in my use case, I am having 2-3 PVCs. Is it a limitation like we cannot use it in values.yaml?

The same use case applies to RabbitMQ as well, I've raised an issue for it as well.
https://github.com/bitnami/charts/issues/12228

### What is the feature you are proposing to solve the problem?

We should be able to use multiple PVCs in values.yaml.

### What alternatives have you considered?

For now, the alternative option for me is to use statefulset.yaml file and use existing PVCs.
