### ISSUE TITLE
[bitnami/redis] Redis Sentinel won't startup when `networkPolicy.allowExternal: false` is set

### ISSUE THREAD

**Issue by jgkirschbaum** [bitnami/charts#12337]
### Name and Version

bitnami/redis 17.1.4

### What steps will reproduce the bug?

1. `helm upgrade --install dos-redis redis --values redis.yaml`
2. Watch the result

```
kubectl get pod
NAME               READY   STATUS    RESTARTS        AGE
dos-redis-node-0   1/3     Running   8 (2m58s ago)   21m
```

### Are you using any custom parameters or values?

redis.yaml
```yaml
networkPolicy:
    enabled: true
    allowExternal: false

auth:
    password: "secret"
  
replica:
  podLabels:
    app: "redis"
  resources:
    limits:
      memory: "256Mi"
    requests:
      cpu: "0.2"
      memory: "256Mi"
  podSecurityContext:
    enabled: true
    fsGroup: 10101
  containerSecurityContext:
    enabled: true
    runAsUser: 10101
    runAsGroup: 10101
    allowPrivilegeEscalation: false
    runAsNonRoot: true
  persistence:
    enabled: false

sentinel:
  enabled: true
  image:
    pullPolicy: "Always"
  getMasterTimeout: 15
  downAfterMilliseconds: 10000
  failoverTimeout: 60000
  resources:
    limits:
      memory: "64Mi"
    requests:
      cpu: "0.1"
      memory: "64Mi"
  containerSecurityContext:
    enabled: true
    runAsUser: 10101
    runAsGroup: 10101
    allowPrivilegeEscalation: false
    runAsNonRoot: true

metrics:
  enabled: true
  image:
    pullPolicy: "Always"
  containerSecurityContext:
    enabled: true
    runAsUser: 10101
    runAsGroup: 10101
    allowPrivilegeEscalation: false
    runAsNonRoot: true
  resources:
    limits:
      memory: "64Mi"
    requests:
      cpu: "0.1"
      memory: "64Mi"
  serviceMonitor:
    enabled: true
  ```

### What is the expected behavior?

Redis should form a 3-node HA-configuration.

### What do you see instead?

First pod will never start and hang forever. It's the sentinel container.

```
kubectl get pod
NAME               READY   STATUS    RESTARTS      AGE
dos-redis-node-0   1/3     Running   6 (45s ago)   15m
```

### Additional information

When changing the `networkPolicy` part of `redis.yaml` file to

```yaml
networkPolicy:
    enabled: true
    allowExternal: true
```

everything works fine.

**Comment by javsalgar** [comment]
Hi,

Could you provide the logs of the pods as well? If you could launch it with image.debug=true it would be helpful

**Comment by jgkirschbaum** [comment]
Containers are now started with `image.debug=true`

`redis.log`
```
 05:26:37.74 INFO  ==> about to run the command: REDISCLI_AUTH=$REDIS_PASSWORD timeout 15 redis-cli -h dos-redis.dos-ig1.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster
 05:26:52.74 INFO  ==> Configuring the node as master
1:C 12 Sep 2022 05:26:52.749 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 12 Sep 2022 05:26:52.749 # Redis version=7.0.4, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 12 Sep 2022 05:26:52.749 # Configuration loaded
1:M 12 Sep 2022 05:26:52.750 * monotonic clock: POSIX clock_gettime
1:M 12 Sep 2022 05:26:52.751 # Warning: Could not create server TCP listening socket ::*:6379: unable to bind socket, errno: 97
1:M 12 Sep 2022 05:26:52.751 * Running mode=standalone, port=6379.
1:M 12 Sep 2022 05:26:52.751 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 12 Sep 2022 05:26:52.751 # Server initialized
1:M 12 Sep 2022 05:26:52.754 * Creating AOF base file appendonly.aof.1.base.rdb on server start
1:M 12 Sep 2022 05:26:52.768 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
1:M 12 Sep 2022 05:26:52.768 * Ready to accept connections
1:signal-handler (1662960651) Received SIGTERM scheduling shutdown...
1:M 12 Sep 2022 05:30:51.167 # User requested shutdown...
1:M 12 Sep 2022 05:30:51.167 * Calling fsync() on the AOF file.
1:M 12 Sep 2022 05:30:51.167 # Redis is now ready to exit, bye bye...
```

`sentinel.log`

```
 05:26:38.04 INFO  ==> about to run the command: REDISCLI_AUTH=$REDIS_PASSWORD timeout 15 redis-cli -h dos-redis.dos-ig1.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster
1:X 12 Sep 2022 05:26:53.071 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:X 12 Sep 2022 05:26:53.071 # Redis version=7.0.4, bits=64, commit=00000000, modified=0, pid=1, just started
1:X 12 Sep 2022 05:26:53.071 # Configuration loaded
1:X 12 Sep 2022 05:26:53.071 * monotonic clock: POSIX clock_gettime
1:X 12 Sep 2022 05:26:53.072 # Warning: Could not create server TCP listening socket ::*:26379: unable to bind socket, errno: 97
1:X 12 Sep 2022 05:26:53.073 * Running mode=sentinel, port=26379.
1:X 12 Sep 2022 05:26:53.073 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:X 12 Sep 2022 05:26:53.073 # Sentinel ID is fdc7c0cc7f493c5102debdadc69243a114b56565
1:X 12 Sep 2022 05:26:53.073 # +monitor master mymaster dos-redis-node-0.dos-redis-headless.dos-ig1.svc.cluster.local 6379 quorum 2
1:X 12 Sep 2022 05:31:01.284 # +sdown master mymaster dos-redis-node-0.dos-redis-headless.dos-ig1.svc.cluster.local 6379
1:signal-handler (1662960681) Received SIGTERM scheduling shutdown...
1:X 12 Sep 2022 05:31:21.337 # User requested shutdown...
1:X 12 Sep 2022 05:31:21.337 # Sentinel is now ready to exit, bye bye...
```

`metrics.log`

```
time="2022-09-12T05:26:38Z" level=info msg="Redis Metrics Exporter v1.43.1    build date: 2022-08-13-05:09:29    sha1: 78f04312879f5585f307c8bec9354de8250e47e9    Go: go1.19    GOOS: linux    GOARCH: amd64"
time="2022-09-12T05:26:38Z" level=info msg="Providing metrics at :9121/metrics"
time="2022-09-12T05:26:51Z" level=error msg="Couldn't connect to redis instance (redis://localhost:6379)"
time="2022-09-12T05:30:51Z" level=error msg="Couldn't connect to redis instance (redis://localhost:6379)"
time="2022-09-12T05:30:51Z" level=error msg="Couldn't connect to redis instance (redis://localhost:6379)"
time="2022-09-12T05:31:02Z" level=error msg="Couldn't connect to redis instance (redis://localhost:6379)"
time="2022-09-12T05:31:21Z" level=error msg="Couldn't connect to redis instance (redis://localhost:6379)"
time="2022-09-12T05:31:21Z" level=error msg="Couldn't connect to redis instance (redis://localhost:6379)"
time="2022-09-12T05:31:32Z" level=error msg="Couldn't connect to redis instance (redis://localhost:6379)"
```

**Comment by migruiz4** [comment]
Hi @jgkirschbaum,

Could you please provide more information about your environment? What CNI are you using? Have you omitted any additional value from the `values.yaml` provided?

I tried to reproduce the issue using Calico on a fresh install but I wasn't able to get the same behavior.

**Comment by jgkirschbaum** [comment]
We are running the VMware TKGI distribution with k8s v1.23.7 on premises. TKGI uses NSX-T CNI from VMware. Tested it also on k8s v1.21.9 with no success.

Omitted is (was) only the following part:

```yaml
global:
  imageRegistry: "our-private-registry"
  imagePullSecrets: ["pullsecret"]

image:
  pullPolicy: "Always"
  debug: true
```

**Comment by jgkirschbaum** [comment]
What I figured out is, that the only difference in the deployment is the `ingress:` part in the generated network-policy, but this seems not to be suspicious.

**Comment by migruiz4** [comment]
It is very hard to determine what could be the root cause of the issue, so in case it helps with troubleshooting, I would like to share here my thoughts about what could be the cause:
- Using `networkPolicy.allowExternal: true` the Redis chart is installed successfully, but with `networkPolicy.allowExternal: false`. As you mentioned, the only difference caused by this value is the `ingress` section of the networkPolicy.
- StartupProbes are failing with the following error, which would mean either the TCP socket is not open or it is not reachable.
```
  Warning  Unhealthy          8m19s (x4442 over 23h)  kubelet  Startup probe failed: dial tcp 10.226.180.2:26379: i/o timeout
  Warning  Unhealthy          3m19s (x4466 over 23h)  kubelet  Startup probe failed: dial tcp 10.226.180.2:6379: i/o timeout
```

It would be super odd, but I'm thinking that maybe with the networkPolicy ingress restricted, Kubernetes is not being able to properly execute the probes.

To discard this hypothesis, could you please try to install the chart with all probes disabled? 
Once installed, it would be helpful to know:
- If Redis gets into the CrashLoopback status too without Probes enabled
- If the Redis container did not crash, is port 6379 open?
- If the port is open, can a client pod (with the proper label) reach and/or connect to Redis?

That troubleshooting may give us some additional info on what could be the cause of the problem.

**Comment by migruiz4** [comment]
Hi @jgkirschbaum,

Thank you very much for the detailed response.

It is very weird that enable/disable is causing the issue, in addition to the `i/o timeout` on the TcpSocket probe from the previous pod describe output.
>  Warning  Unhealthy          8m19s (x4442 over 23h)  kubelet  Startup probe failed: dial tcp 10.226.180.2:26379: i/o timeout
>  Warning  Unhealthy          3m19s (x4466 over 23h)  kubelet  Startup probe failed: dial tcp 10.226.180.2:6379: i/o timeout

I'm not sure if this could be caused by the chart itself or an issue with the CNI plugin, as the probes requests shouldn't be blocked. 
I suggest trying `redis/sentinel.customStartupProbe` to set a different Probe condition. Meanwhile, I will discuss this issue internally.

**Comment by jgkirschbaum** [comment]
@migruiz4 thank you for your effort, your feedback and your thoughts regarding debugging the startup issue.

Meanwhile I did a little further investigation and I'd like to share my results. As you mentioned I tried it with `redis|sentinel.customStartupProbe` and the following quick hack as configuration:

```yaml
replica:
  startupProbe:
    enabled: false
  customStartupProbe:
    failureThreshold: 22
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
    exec:
      command:
        - "bash"
        - "-c"
        - "REDISCLI_AUTH=secret timeout 1 redis-cli -h 127.0.0.1 -p 6379 ping"

sentinel:
  startupProbe:
    enabled: false
  customStartupProbe:
    failureThreshold: 22
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
    exec:
      command:
        - "bash"
        - "-c"
        - "REDISCLI_AUTH=secret timeout 1 redis-cli -h 127.0.0.1 -p 26379 ping"
```

Everything works like a charme, all pods start up and form a Redis Sentinel environment.

Replacing the `exec` part in the startup probe like the helm chart does with

```yaml
tcpSocket:
  port: 6379|26379
```

the pods won't startup.

In the [k8s documention](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#tcp-probes) I found

> For a TCP probe, the kubelet makes the probe connection at the node, not in the pod, which means that you can not use a service name in the host parameter since the kubelet is unable to resolve it.

It's a bit unclear to me, but could it be, that the network policy generated by the helm chart with `networkPolicy.allowExternal: false` doesn't allow the kubelet to connect to the pod, i.e. containers?
