### ISSUE TITLE
[bitnami/thanos] Add support for creating custom certificate objects to Thanos Helm chart

### ISSUE THREAD

**Issue by njegosrailic** [bitnami/charts#12335]
### Name and Version

bitnami/thanos

### What is the problem this feature will solve?

First of all thanks for the great Helm chart. I'd like to check does it make sense to add support for custom `cert-manager` certificate templates. As I user 

Example: 
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: thanos-query-grpc-certificate
  namespace: monitoring
spec:
  dnsNames:
  - kube-thanos-query-grpc-c2.service.consul.internal.mydomain.com
  - thanos-query-grpc.monitoring.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: vault-issuer
  secretName: thanos-query-grpc-certificate
```
I know that cert-manager supports TLS automation for the `Ingress` type of service, but configuring Thanos GCP service over TLS using ingress can be challenging.

I think this would make sense but wanted to ask before creating a PR.

### What is the feature you are proposing to solve the problem?

This feature would allow using `cert-manager` to issue custom TLS certificates, which could simplify the process for users that would like to use GRPC over TLS. 

### What alternatives have you considered?

A custom Helm chart to manage certificates then use the Bitnami Thanos Helm chart as a dependency.
