### ISSUE TITLE
Mediawiki unable to connect to db

### ISSUE THREAD

**Issue by YonatanRubin** [bitnami/charts#12364]
### Name and Version

bitnami/mediawiki 13.0.4

### What steps will reproduce the bug?

Running on openshift, when changing the custom mariadb port to 13306 the 'install.php' script fails even though running 'mysql' from the same container with the same configuration succeed. 

### Are you using any custom parameters or values?

```yaml
mariadb:
  primary:
    configuration: |
      [mysqld]
      port = 13306
      [client]
      port = 13306
      [manager]
      port = 13306
    service:
      ports:
        mysql: 13306

service:
  type: NodePort
  ports:
    http: 13080
extraEnvVars:
  - name: MEDIAWIKI_EXTERNAL_HTTP_PORT_NUMBER
    value: 13080
  - name: MARIADB_PORT_NUMBER
    value: 13306
```

### What is the expected behavior?

The mediawiki chart should connect to the db and install successfully 

### What do you see instead?

setup.sh showing
```
/opt/bitnami/mediawiki/maintenance/install.php  'My Wiki' REAL_USER --pass REAL_PASS --dbserver Release-mariadb --dbport 13306 --dbuser bn_mediawiki --dbpass REAL_DB_PASS --installdbuser bn_mediawiki --installdbpass REAL_DB_PASS --dbname bitnami_mediawiki 

Cannot access the database: :real_connect(): (HY000/2002) Connection timed out
```
running
```bash
mysql -u bn_mediawiki -pREAL_DB_PASS -h Release-mariadb -P 13306 -D bitnami_mediawiki
```
Does connect successfully
