### ISSUE TITLE
External MariaDB secret name is wrong

### ISSUE THREAD

**Issue by LedAlex** [bitnami/charts#12384]
### Name and Version

bitnami/redmine 20.3.3

### What steps will reproduce the bug?

Make deploy with external MariaDB/MySQL using:
```
databaseType: mariadb
mariadb:
  enabled: false
postgresql:
  enabled: false
externalDatabase:
  host: "XXX.XXX.XXX.XXX"
  port: 3306
  user: not_a_root
  database: Redmine
  password: "XXXX"
  existingSecret: ""
  existingSecretPasswordKey: ""
```

### What do you see instead?

Since bug in helpers it tries to use secret for PostgreSQL to MariaDB.
```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  74s                default-scheduler  Successfully assigned redmine/redmine-595849d98c-vq2nf to ubuntu-22-04-server-08
  Normal   Pulled     10s (x7 over 74s)  kubelet            Container image "docker.io/bitnami/redmine:5.0.2-debian-11-r23" already present on machine
  Warning  Failed     10s (x7 over 74s)  kubelet            Error: couldn't find key password in Secret redmine/redmine-externaldb
```
