### ISSUE TITLE
elasticsearch not working while enabling security

### ISSUE THREAD

**Issue by Sahalats** [bitnami/charts#12398]
### Name and Version

bitnami/elasticsearch

### What steps will reproduce the bug?

while deploying elastic search with security enabled, It is not working properly. It shows page cannot be reached after giving the type as loadbalancer and checking even though the log and description on k9s show no error

### Are you using any custom parameters or values?
```yaml
security.enabled: true
toleration added - tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
tls autogenerate: true
```
### What is the expected behavior?

![e1](https://user-images.githubusercontent.com/71964320/189836270-8231f3a6-71e7-487c-a6b9-0ecc566e9205.PNG)

### What do you see instead?

![e2](https://user-images.githubusercontent.com/71964320/189836316-c9cbe117-a59e-49f5-9d9a-526c575bb2ac.PNG)
