### ISSUE TITLE
[bitnami/grafana-loki] Better customization of Loki's configuration

### ISSUE THREAD

**Issue by k-jingyang** [bitnami/charts#12400]
### Name and Version

bitnami/grafana-loki

### What is the problem this feature will solve?

Better customization of Loki's configuration

The current Helm chart does not allow users to override specific configuration values without replacing the entire `loki.configuration`, where the current `loki.configuration` has provided sane defaults for many components.

### What is the feature you are proposing to solve the problem?

Is there a way that we can inspiration from https://github.com/grafana/loki/blob/main/production/helm/loki/templates/configmap.yaml and have something similar to

```yaml
data:
  config.yaml: |
    {{- tpl (mergeOverwrite (tpl .Values.loki.config . | fromYaml) .Values.loki.structuredConfig | toYaml) . | nindent 4 }}
{{- end -}}
```

where individual keys can be inserted from `.Values.loki.structuredConfig` into `.Values.loki.config` (`.Values.loki.configuration` in our bitnami helm chart)

### What alternatives have you considered?

Have thought of segregating the individual sections from the configuration into separate keys (e.g. splitting out the `compactor` configuration into a `.Values.compactor.configuration`).

This will take some effort and may not be as flexible as the proposed approach, which allows individual key overrides.
