### ISSUE TITLE
minio defaultBuckets setting results in error while starting

### ISSUE THREAD

**Issue by Loosetooth** [bitnami/charts#12426]
### Name and Version

bitnami/minio 11.10.2

#### In short:
Running the minio helm chart with a `values.yml` file containing a non-empty `defaultBuckets` setting results in the container not starting. It throws the following error: 

```
mc: <ERROR> Unable to make bucket `local/myCustomBucketName`. Bucket name contains invalid characters
```

#### To reproduce:
Start with the default [values.yml](https://github.com/bitnami/charts/blob/master/bitnami/minio/values.yaml) file.
Change the `defaultBuckets` setting:
```
defaultBuckets: "myCustomBucketName"
```

Now start the chart:
```
$ helm install -f values.yml minio bitnami/minio
```

Check the running pods:
```
kubectl get pods
```
Which shows that the pod had an error:
```
NAME                                      READY   STATUS    RESTARTS      AGE
minio-57964db74b-kwmr9                    0/1     Error     1 (10s ago)   28s
```

Then check the logs of the pod:
```
kubectl logs minio-57964db74b-kwmr9
```

Shows the following output:
```
 13:07:56.23 
 13:07:56.23 Welcome to the Bitnami minio container
 13:07:56.23 Subscribe to project updates by watching https://github.com/bitnami/containers
 13:07:56.23 Submit issues and feature requests at https://github.com/bitnami/containers/issues
 13:07:56.24 
 13:07:56.24 INFO  ==> ** Starting MinIO setup **
minio 13:07:56.25 INFO  ==> Starting MinIO in background...
minio 13:08:01.27 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 13:08:01.30 INFO  ==> Creating default buckets...
mc: <ERROR> Unable to make bucket `local/myCustomBucketName`. Bucket name contains invalid characters
minio 13:08:01.42 INFO  ==> Stopping MinIO...
```
The bucket name seems to contain invalid characters.
I tried with a few different bucket names, had the same error every time. It almost seems to me like the `local/` prefix is causing the error.

### What do you see instead?

Container fails to start with following output:

```
 13:07:56.23 
 13:07:56.23 Welcome to the Bitnami minio container
 13:07:56.23 Subscribe to project updates by watching https://github.com/bitnami/containers
 13:07:56.23 Submit issues and feature requests at https://github.com/bitnami/containers/issues
 13:07:56.24 
 13:07:56.24 INFO  ==> ** Starting MinIO setup **
minio 13:07:56.25 INFO  ==> Starting MinIO in background...
minio 13:08:01.27 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 13:08:01.30 INFO  ==> Creating default buckets...
mc: <ERROR> Unable to make bucket `local/myCustomBucketName`. Bucket name contains invalid characters
minio 13:08:01.42 INFO  ==> Stopping MinIO...
```

**Comment by yywing** [comment]
It is not name problem. My chart not work，too.
And I found docker compose can also repeat this bug.
```
version: '2'

services:
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
      - MINIO_DEFAULT_BUCKETS=my-first-bucket:private,my-second-bucket
  minio2:
    image: docker.io/bitnami/minio:2022
    volumes:
      - 'minio_2_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
      - MINIO_DEFAULT_BUCKETS=my-first-bucket:private,my-second-bucket
  minio3:
    image: docker.io/bitnami/minio:2022
    volumes:
      - 'minio_3_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
      - MINIO_DEFAULT_BUCKETS=my-first-bucket:private,my-second-bucket
  minio4:
    image: docker.io/bitnami/minio:2022
    volumes:
      - 'minio_4_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
      - MINIO_DEFAULT_BUCKETS=my-first-bucket:private,my-second-bucket

volumes:
  minio_data:
    driver: local
  minio_2_data:
    driver: local
  minio_3_data:
    driver: local
  minio_4_data:
    driver: local
```

```
docker compose up

minio-minio4-1  |  09:21:09.34
minio-minio4-1  |  09:21:09.34 Welcome to the Bitnami minio container
minio-minio4-1  |  09:21:09.35 Subscribe to project updates by watching https://github.com/bitnami/containers
minio-minio4-1  |  09:21:09.35 Submit issues and feature requests at https://github.com/bitnami/containers/issues
minio-minio4-1  |  09:21:09.35
minio-minio4-1  |  09:21:09.35 INFO  ==> ** Starting MinIO setup **
minio-minio4-1  | minio 09:21:09.36 INFO  ==> Starting MinIO in background...
minio-minio2-1  |  09:21:09.55
minio-minio2-1  |  09:21:09.55 Welcome to the Bitnami minio container
minio-minio2-1  |  09:21:09.55 Subscribe to project updates by watching https://github.com/bitnami/containers
minio-minio2-1  |  09:21:09.55 Submit issues and feature requests at https://github.com/bitnami/containers/issues
minio-minio2-1  |  09:21:09.55
minio-minio2-1  |  09:21:09.55 INFO  ==> ** Starting MinIO setup **
minio-minio2-1  | minio 09:21:09.56 INFO  ==> Starting MinIO in background...
minio-minio3-1  |  09:21:09.72
minio-minio3-1  |  09:21:09.72 Welcome to the Bitnami minio container
minio-minio3-1  |  09:21:09.72 Subscribe to project updates by watching https://github.com/bitnami/containers
minio-minio3-1  |  09:21:09.72 Submit issues and feature requests at https://github.com/bitnami/containers/issues
minio-minio-1   |  09:21:09.72
minio-minio3-1  |  09:21:09.72
minio-minio-1   |  09:21:09.72 Welcome to the Bitnami minio container
minio-minio3-1  |  09:21:09.72 INFO  ==> ** Starting MinIO setup **
minio-minio-1   |  09:21:09.72 Subscribe to project updates by watching https://github.com/bitnami/containers
minio-minio-1   |  09:21:09.72 Submit issues and feature requests at https://github.com/bitnami/containers/issues
minio-minio-1   |  09:21:09.72
minio-minio-1   |  09:21:09.72 INFO  ==> ** Starting MinIO setup **
minio-minio3-1  | minio 09:21:09.73 INFO  ==> Starting MinIO in background...
minio-minio-1   | minio 09:21:09.73 INFO  ==> Starting MinIO in background...
minio-minio4-1  | minio 09:21:14.37 INFO  ==> Adding local Minio host to 'mc' configuration...
minio-minio2-1  | minio 09:21:14.57 INFO  ==> Adding local Minio host to 'mc' configuration...
minio-minio3-1  | minio 09:21:14.74 INFO  ==> Adding local Minio host to 'mc' configuration...
minio-minio-1   | minio 09:21:14.74 INFO  ==> Adding local Minio host to 'mc' configuration...
minio-minio4-1  | minio 09:21:19.40 INFO  ==> Creating default buckets...
minio-minio4-1  | minio 09:21:19.44 INFO  ==> Bucket local/my-first-bucket already exists, skipping creation.
minio-minio4-1  | minio 09:21:19.47 INFO  ==> Bucket local/my-second-bucket already exists, skipping creation.
minio-minio4-1  | minio 09:21:19.51 INFO  ==> Stopping MinIO...
minio-minio2-1  | minio 09:21:19.60 INFO  ==> Creating default buckets...
minio-minio3-1  | minio 09:21:19.78 INFO  ==> Creating default buckets...
minio-minio-1   | minio 09:21:19.78 INFO  ==> Creating default buckets...
minio-minio4-1  |
minio-minio4-1  |  09:21:20.58 INFO  ==> ** MinIO setup finished! **
minio-minio4-1  | minio 09:21:20.58 INFO  ==> ** Starting MinIO **
minio-minio-1   | mc: <ERROR> Unable to make bucket `local/my-first-bucket`. Put "http://localhost:9000/my-first-bucket/": dial tcp 127.0.0.1:9000: connect: connection refused
minio-minio-1   | minio 09:21:22.04 INFO  ==> MinIO is already stopped...
minio-minio-1 exited with code 1
minio-minio3-1  | mc: <ERROR> Unable to make bucket `local/my-first-bucket`. Put "http://localhost:9000/my-first-bucket/": dial tcp 127.0.0.1:9000: connect: connection refused
minio-minio3-1  | minio 09:21:23.35 INFO  ==> MinIO is already stopped...
minio-minio3-1 exited with code 1
minio-minio2-1  | mc: <ERROR> Unable to make bucket `local/my-first-bucket`. Put "http://localhost:9000/my-first-bucket/": dial tcp 127.0.0.1:9000: connect: connection refused
minio-minio2-1  | minio 09:21:24.73 INFO  ==> MinIO is already stopped...
minio-minio2-1 exited with code 1
```
