### ISSUE TITLE
[bitnami/spark] Setting service.type=LoadBalancer in the Spark chart has no effect on provisions a ClusterIp regardless

### ISSUE THREAD

**Issue by theelderbeever** [bitnami/charts#12451]
### Name and Version

bitnami/spark 6.3.1

### What steps will reproduce the bug?

Environment: AWS EKS 1.23
In the helm chart
```yaml
service:
  ## @param service.type Kubernetes Service type
  ##
  type: LoadBalancer
```
Doesn't provision a LoadBalancer. Manually editing the generated service to be a LoadBalancer will provision one.

### Are you using any custom parameters or values?

```yaml
...
service:
  ## @param service.type Kubernetes Service type
  ##
  type: LoadBalancer
...
```

### What is the expected behavior?

The resultant service type should match the requested one in the chart. Namely, a load balancer should be provisioned.

### What do you see instead?

The service remains a `ClusterIp` regardless of setting. Manually updating the service will provision the load balancer.

EDIT: The manually provisioned LoadBalancer eventually worked. It was just very slow to provision on the AWS side of things. Removed those comments from the issue.

**Comment by javsalgar** [comment]
Hi,

According to the YAML, the master service would take these settings

```
spec:
  type: {{ .Values.service.type }}
```

Could you double check that the service type of the master service is expected?

**Comment by theelderbeever** [comment]
When the master service is created it ends up with `ClusterIp` as the type regardless of what I set it as in the `values.yaml`.

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the delay.
  If I change the service type changed to `hello_world` I got it rendered in the template.
```
helm template myspark bitnami/spark --set service.type=hello_world | grep -B 12 hello
kind: Service
metadata:
  name: myspark-master-svc
  namespace: "default"
  labels:
    app.kubernetes.io/name: spark
    helm.sh/chart: spark-6.3.4
    app.kubernetes.io/instance: myspark
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: master
  annotations:
spec:
  type: hello_world
```
  Could you try that ?
