### ISSUE TITLE
Owncloud creates wrong PV if hostPath and storageClass are specified

### ISSUE THREAD

**Issue by edemen** [bitnami/charts#12452]
### Name and Version

bitnami/owncloud 12.2.2

### What steps will reproduce the bug?

I'm trying to install owncloud such that it will write files to a particular path on my hard drive. However, it creates two PVs and binds PVC to the wrong one.

### Are you using any custom parameters or values?

In my values.yaml:
```yaml
persistence:
  enabled: true
  hostPath: /storage/ssd1/owncloud
  size: 100Gi
  accessMode: ReadWriteOnce
  storageClass: microk8s-hostpath-retain
```
### What is the expected behavior?

I expect that it would:

1. Create PV owncloud-owncloud with the desired hostPath
2. Create PVC and bind it to the PV

### What do you see instead?

It creates PV owncloud-owncloud with correct hostPath
Then it creates another PV, which ignores my hostPath
And binds the PVC to the second, wrong PV

```
owncloud-owncloud                          100Gi      RWO            Retain           Available                                                                     5s
pvc-024aca65-85e2-459d-b6ff-01bdb0216680   100Gi      RWO            Delete           Bound       owncloud/owncloud-owncloud           microk8s-hostpath            5s
```
The effect is that it ignores my hostPath entirely.

### Additional information

And if I don't specify storageClass it fails as soon as it runs the install script without any errors, just exits with code 1.
