### ISSUE TITLE
[bitnami/minio] port change error

### ISSUE THREAD

**Issue by juyunsang** [bitnami/charts#12469]
### Name and Version

bitnami/minio 11.2.12

### What steps will reproduce the bug?

In order to change the api and console port of miniio, the values are set as below

```yaml
  containerPorts:
    api: 10900
    console: 10901
  service:
    ports:
      api: 10900
      console: 10901
  extraEnvVars:
    - name: MINIO_CONSOLE_PORT_NUMBER
      value: "10901"
    - name: MINIO_SERVER_PORT_NUMBER
      value: "10900"
    - name: MINIO_API_PORT_NUMBER
      value: "10900"
```

If i update the existing minio, the following error occurs and becomes CrashLoopBackOff status
```
API: SYSTEM()
Time: 12:55:30 UTC 09/16/2022
Error: Marking http://minio-2.minio-headless.test-db.svc.cluster.local:10900/minio/storage/data/v44 temporary offline; caused by Post "http://minio-2.minio-headless.test-db.svc.cluster.local:10900/minio/storage/data/v44/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 10.108.212.225:10900: connect: connection refused (*fmt.wrapError)
       6: internal/rest/client.go:151:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:153:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:523:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:387:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:326:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
```
If i deploy a new minio, it will run without any problems
- Delete only existing minio helm, do not delete pvc --> crashloopbackoff error
- Delete both existing minio helm and pvc and deploy minio --> No problem

Is there an issue with the values I set?
Or is it impossible to change the port for the existing minio because I saved the port-related settings on the pvc?

### What do you see instead?

```
API: SYSTEM()
Time: 12:55:30 UTC 09/16/2022
Error: Marking http://minio-2.minio-headless.test-db.svc.cluster.local:10900/minio/storage/data/v44 temporary offline; caused by Post "http://minio-2.minio-headless.test-db.svc.cluster.local:10900/minio/storage/data/v44/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 10.108.212.225:10900: connect: connection refused (*fmt.wrapError)
       6: internal/rest/client.go:151:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:153:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:523:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:387:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:326:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
```
