### ISSUE TITLE
[bitnami/airflow] Change timezone Airflow

### ISSUE THREAD

**Issue by emerchalegre** [bitnami/charts#12468]
### Name and Version

bitnami/airflow

### What steps will reproduce the bug?

I add in the values.yaml file the property extraEnvVars with defautl timezone, but don't had effect on UI.

Below my config:

```
auth:
  username: user
  password: ""
  fernetKey: ""
  secretKey: ""
  existingSecret: ""
executor: KubernetesExecutor
loadExamples: false
defaultTimezone: Brazil/East
configuration: ""
existingConfigmap: ""
dags:
  existingConfigmap: ""
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 11-debian-11-r34
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
extraEnvVars:
  - name: AIRFLOW_DEFAULT_TIMEZONE
    value: Brazil/East
```

### What is the expected behavior?

In the image below the timezone is UTC, but I put Brazil/East in the config file.
![image](https://user-images.githubusercontent.com/1181145/190837202-941fb22a-21e1-4cfb-b83a-a110b8b77fc9.png)

### What do you see instead?

I need that show Brazil/East in Timezone on the Airflow UI

**Comment by fmulero** [comment]
Hi @emerchalegre 

AFAIK we are not supporting any `defaultTimezone` [value in airflow chart](https://github.com/bitnami/charts/tree/master/bitnami/airflow#parameters) According to [airflow configuration](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#default-timezone) you can set the default timezone with the variable `AIRFLOW__CORE__DEFAULT_TIMEZONE `. 

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

**Comment by emerchalegre** [comment]
Hi @fmulero. I try set variable AIRFLOW__CORE__DEFAULT_TIMEZONE, but don't work.
I saw in https://github.com/bitnami/containers/blob/main/bitnami/airflow/2/debian-11/rootfs/opt/bitnami/scripts/airflow-env.sh that it doesn't have the default_timezone variable, for that won't work.

**Comment by fmulero** [comment]
After setting `AIRFLOW__CORE__DEFAULT_TIMEZONE` you are able to see something like this (Please read the documentation about [web ui and server configuration](https://airflow.apache.org/docs/apache-airflow/stable/timezone.html#web-ui)):
![image](https://user-images.githubusercontent.com/23502572/191464196-0ede37f2-015a-4af1-93d5-439367877244.png)

Previous example was generated with following docker-compose:
```yaml
version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:10
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: docker.io/bitnami/redis:7.0
    volumes:
      - 'redis_data:/bitnami'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Brazil/East
  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Brazil/East
  airflow:
    image: docker.io/bitnami/airflow:2
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Brazil/East
    ports:
      - '8080:8080'
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local

```
