### ISSUE TITLE
[bitnami/redis-cluster] What is the YAML interface syntax. Error while decoding JSON: json: cannot unmarshal string into Go value of type map[string]interface {} Redis-cluster

### ISSUE THREAD

**Issue by xtianus79** [bitnami/charts#12476]
### Name and Version

bitnami/redis-cluster

### What steps will reproduce the bug?

When I run the helm command to process the values.yaml file. I get an error and I am a little confused as what I should be putting in the yaml file pertaining to the correct value(s)

`helm upgrade --install -f .\redis-cluster-values.yml redis-mqtt-stream bitnami/redis-cluster --create-namespace -n $NAMESPACE_REDIS_EMQX`

 I am getting this error

`Error: failed to parse .\redis-cluster-values.yml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type map[string]interface {}`

The values below Are what I changed the value.yaml file to. I am not understanding the proper way to right the values in the values.yaml file.

      networkPolicy:
        ## Altered 1
        enabled: true
        ## When set to false, only pods with the correct
        ## client label will have network access to the port Redis&reg; is listening
        ## on. When true, Redis&reg; will accept connections from any source
        ## (with the correct destination port).
        ##
        allowExternal: true
        ingressNSMatchLabels: {
          "kubernetes.io/metadata.name": "some-value",
          "name": "some-value"
        }

Am I doing something wrong or does this just not work correctly. 

Also, I am confused on what should go there exactly in the first place. 

While there is an example it doesn't make sense to me. Could be just me. 

> With networkPolicy.ingressNSMatchLabels pods from other namespaces can connect to redis. Set networkPolicy.ingressNSPodMatchLabels to match pod labels in matched namespace. For example, for a namespace labeled redis=external and pods in that namespace labeled redis-client=true the fields should be set:

Do you want the labels or the metadata name? 

for example this is my namespace file. 

      kind: Namespace
        apiVersion: v1
        metadata:
          name: some-value
          uid: some-value
          resourceVersion: '33033'
          creationTimestamp: '2022-09-08T04:39:34Z'
          labels:
            kubernetes.io/metadata.name: some-value
            name: some-value

### Are you using any custom parameters or values?

Yes. values.yaml

 ``` Yaml
networkPolicy:
  ## Altered 1
  enabled: true
  ## When set to false, only pods with the correct
  ## client label will have network access to the port Redis&reg; is listening
  ## on. When true, Redis&reg; will accept connections from any source
  ## (with the correct destination port).
  ##
  allowExternal: true
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
```

### What is the expected behavior?

For it to work

### What do you see instead?

Get an error

### Additional information

I would like to know what I am missing regarding this yaml syntax. Any help to clear that up would be appreciated.

**Comment by javsalgar** [comment]
Hi,

Could you try this format? 

```
  networkPolicy:
    ## Altered 1
    enabled: true
    ## When set to false, only pods with the correct
    ## client label will have network access to the port Redis&reg; is listening
    ## on. When true, Redis&reg; will accept connections from any source
    ## (with the correct destination port).
    ##
    allowExternal: true
    ingressNSMatchLabels:
       kubernetes.io/metadata.name: some-value
       name: some-value
   

```
