### ISSUE TITLE
Matomo cron error

### ISSUE THREAD

**Issue by kajla** [bitnami/charts#12580]
### Name and Version

bitnami/matomo 0.2.5

### What steps will reproduce the bug?

Hello,

I installed the Helm chart and since the container is not running as root, cron does not start.

```
matomo 14:55:31.43
matomo 14:55:31.43 Welcome to the Bitnami matomo container
matomo 14:55:31.43 Subscribe to project updates by watching https://github.com/bitnami/containers
matomo 14:55:31.43 Submit issues and feature requests at https://github.com/bitnami/containers/issues
matomo 14:55:31.43
matomo 14:55:31.44 INFO  ==> ** Starting Matomo setup **
realpath: /bitnami/apache/conf: No such file or directory
matomo 14:55:31.60 INFO  ==> Configuring the HTTP port
matomo 14:55:31.68 INFO  ==> Configuring the HTTPS port
matomo 14:55:31.69 INFO  ==> Configuring Apache ServerTokens directive
matomo 14:55:31.73 INFO  ==> Configuring PHP options
matomo 14:55:31.73 INFO  ==> Setting PHP expose_php option
matomo 14:55:31.87 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
matomo 14:55:32.09 INFO  ==> Persisted Matomo installation detected
matomo 14:55:32.09 INFO  ==> Updating default plugins in persisted data
matomo 14:55:37.26 INFO  ==> Updating default js scripts in persisted data
matomo 14:55:37.33 INFO  ==> Restoring Matomo installation
matomo 14:55:38.05 INFO  ==> Trying to connect to the database server
matomo 14:55:38.22 INFO  ==> Launching schema update

Everything is already up to date.

Done. To check if this worked please open the system report or run `./console diagnostics:run` and look out for the private directories check. If it doesn't work you may need to execute this command using a user that has write permissions or maybe you are not using Apache or IIS web server. Please note you may need to execut this command every time you update Matomo to a newer version.
matomo 14:55:44.39 WARN  ==> Skipping cron configuration for Matomo because of running as a non-root user
matomo 14:55:44.40 INFO  ==> ** Matomo setup finished! **

matomo 14:55:44.41 WARN  ==> Cron will not be started because of running as a non-root user
matomo 14:55:44.43 INFO  ==> ** Starting Apache **

```

### What do you see instead?

On the UI, shows 1 error:
![image](https://user-images.githubusercontent.com/5457824/191048850-8c0e0b78-b8b2-43ef-8d9d-1324b3a93726.png)

### Additional information

The documentation recommends using cron.
https://matomo.org/faq/on-premise/how-to-set-up-auto-archiving-of-your-reports/

Thank you in advance.

**Comment by renepardon** [comment]
Using Helm chart version 0.2.6, there seems absolutely no cron job to start at all. Is there an example available on how to do this with a sidecar container inside the same pod?

**Comment by renepardon** [comment]
Update:

I had to get this working so my hacky solution for now is to configure a sidecar container with security context "root". I have to execute the entrypoint explicitly but after that a simple while loop and sleep combination works between every core:archive command. Maybe something like this could be implemented into the helm chart directly, so one does not to copy all env vars and additional configuration again which also increases maintenance. Variables defined inside ${} is my setup, because I use terraform with templatefile() helper to deploy. I mostly reuse the same container spec but removed health checks. If entrypoint/loop/console command fails the container should restart with the same loop again. Didn't test that yet.

```yaml
sidecars:
    - name: matomo-core-archive
      image: docker.io/bitnami/matomo:${imageTag}
      imagePullPolicy: "IfNotPresent"
      command: ["/bin/sh"]
      args:
          - -c
          - /entrypoint.sh ; while true ; do /opt/bitnami/php/bin/php /opt/bitnami/matomo/console core:archive --url=https://matomo.example.net ; sleep 3600; done
      securityContext:
        runAsUser: 1001
        runAsNonRoot: true
      env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: APACHE_HTTP_PORT_NUMBER
          value: "8080"
        - name: APACHE_HTTPS_PORT_NUMBER
          value: "8443"
        - name: MATOMO_DATABASE_HOST
          value: "matomo-mariadb"
        - name: MATOMO_DATABASE_PORT_NUMBER
          value: "3306"
        - name: MATOMO_DATABASE_NAME
          value: "bitnami_matomo"
        - name: MATOMO_DATABASE_USER
          value: "matomo"
        - name: MATOMO_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "matomo-mariadb"
              key: "mariadb-password"
        - name: MATOMO_SKIP_BOOTSTRAP
          value: "no"
        - name: MATOMO_USERNAME
          value: "${matomoUsername}"
        - name: MATOMO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "matomo"
              key: matomo-password
        - name: MATOMO_EMAIL
          value: "sag@ich.net"
        - name: MATOMO_WEBSITE_NAME
          value: "Matomo Stats"
        - name: MATOMO_WEBSITE_HOST
          value: "https://matomo.example.com"
        - name: MATOMO_SMTP_HOST
          value: "${smtpHost}"
        - name: MATOMO_SMTP_PORT
          value: "25"
        - name: MATOMO_SMTP_USER
          value: "${smtpUser}"
        - name: MATOMO_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "matomo"
              key: smtp-password
        - name: MATOMO_SMTP_PROTOCOL
          value: "tls"
      resources:
        requests:
          memory: 512Mi
          cpu: 300m
        limits: {}
      volumeMounts:
        - name: matomo-data
          mountPath: /bitnami/matomo
```
