### ISSUE TITLE
bitmani/keycloak 10.1.1 not available

### ISSUE THREAD

**Issue by AokigaharaX** [bitnami/charts#12590]
### Name and Version

bitnami/keycloak 10.1.1

### What steps will reproduce the bug?

In https://bitnami.com/stack/keycloak/helm it says keycloak latest version is 19.0.2 (bitnami/keycloak 10.1.1)
However I'm unable to find it, it's still 10.1.0 as the latest:
```console
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "codecentric" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
$ helm search repo keycloak
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
bitnami/keycloak        10.1.0          19.0.1          Keycloak is a high performance Java-based ident...

```

### What do you see instead?

In https://charts.bitnami.com/bitnami:
```yaml
 keycloak:
  - annotations:
      category: DeveloperTools
    apiVersion: v2
    appVersion: 19.0.1
    created: "2022-09-14T11:28:28.767421148Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 11.x.x
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 2.x.x
    description: Keycloak is a high performance Java-based identity and access management
      solution. It lets developers add an authentication layer to their applications
      with minimum effort.
    digest: 720bb576111c62b6f98ef5de5e91f6ca9796405b09f9d7ece3eba3cfe413cbe0
    home: https://www.keycloak.org
    icon: https://bitnami.com/assets/stacks/keycloak/img/keycloak-stack-220x234.png
    keywords:
    - keycloak
    - access-management
    maintainers:
    - name: Bitnami
      url: https://github.com/bitnami/charts
    name: keycloak
    sources:
    - https://github.com/bitnami/containers/tree/main/bitnami/keycloak
    - https://github.com/keycloak/keycloak
    urls:
    - https://charts.bitnami.com/bitnami/keycloak-10.1.0.tgz
    version: 10.1.0
```
