### ISSUE TITLE
[bitnami/redis] Unable to use common labels for Redis chart: servicemonitor does not scrape Metrics

### ISSUE THREAD

**Issue by Ghilteras** [bitnami/charts#12621]
### Name and Version

bitnami/redis 17.1.7

### What steps will reproduce the bug?

1. Enable Prom Metrics in the values yaml
2. Enable Servicemonitor
3. Add podsAnnotation per https://docs.bitnami.com/kubernetes/infrastructure/redis/administration/enable-metrics/
4. apply a common label to match the selector
```
  commonLabels:
    app.kubernetes.io/instance: metadata-api
```

### Are you using any custom parameters or values?

no

### What is the expected behavior?

Expected behavior is that the servicemonitor scrapes the metrics on the Metrics service

### What do you see instead?

metrics are not available on Prometheus

### Additional information

it seems that the servicemonitor selector uses a selector on the instance using the app name, but the Metrics svc uses an instance name which is the FQDN and I do not have any way of customizing the labels. I tried using commonLabels (see point 4 above) which should cascade from General to all deployed objects, but the label is not applied and I have no other way to change the selector.

What can I do to change the selector on the servicemonitor and/or the metrics svc? or how do I change the labels so they match?

**Comment by Ghilteras** [comment]
Looks like the selector should default to `metrics` only if `common.labels.matchLabels` are not defined according to the servicemonitor code

https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/servicemonitor.yaml#L39-L40

```
selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
```

I tried taking away the common labels because matching only on `metrics` would work, but the rendered template is still showing the instance

```
selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: metadata-api
      app.kubernetes.io/name: redis
```
why?

**Comment by jotamartos** [comment]
Hi @Ghilteras,

Sorry for the delay here. We are going to take a look at the issue and will update it as soon as we have more information.

**Comment by jotamartos** [comment]
Hi @Ghilteras,

I edited the `templates/servicemonitor.yaml` file and removed the "common.labels.matchLabels" parameter

```
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
{{- end }}
```

and the template command showed the correct information when rendering the file 

```
$ helm template -s templates/servicemonitor.yaml .
---
# Source: redis/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: release-name-redis
  namespace: "default"
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-17.3.1
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: metadata-api
spec:
  endpoints:
    - port: http-metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
```

How are you rendering the template files?

**Comment by webdz9r** [comment]
@Ghilteras you asked why?
`selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics`

because that isn't a condition, it always includes those. This chart needs to have the option to NOT include this, I'm stuck with the same issue with the elastic search chart. because the selector is using 3 conditions to match the metrics it fails to load targets. 

Need a nice way of NOT including your common.labels.matchLabels values that are set in the base bitnami chart.

**Comment by jotamartos** [comment]
Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by webdz9r** [comment]
My solution was based on a kustomize patch. I could work on a PR to remove this but I believe this would affect all base charts and most likely cause issues. I don’t believe fundamental the current code is wrong. But having 3 required conditions seems a bit overkill IMO. 

Let me know if you’d like me to share my kustomize patch. In our case we have a post-processing pipeline that renames the application name so the application name condition was always going to fail in our case.

**Comment by jotamartos** [comment]
Hi @webdz9r,

You do not need to edit all charts but this one. You can create a PR with the changes you think we need to implement and the team will review them. If those changes are applied you (and the entire community) will benefit from them

**Comment by webdz9r** [comment]
Seems all charts use the Labels Template from the [charts/bitnami/common](https://github.com/bitnami/charts/blob/63b3d0b2a7363776b52e6dd68d985b20c3f6c456/bitnami/common/templates/_labels.tpl#L15)

In my case elastic search alerts and rules wouldn't match because it requires 3 matching statements for the selector, this is a bit overkill but again works in most cases. For us we modify our instance name before we deploy so any bitnami chart fails. 

There is no method for overriding this value from target chart (elastic search) (at least that I'm aware of) so enabling
```
#Values.yaml 
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```


gives me these selectors
```  
# rendered output from helm template
selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: elasticsearch
      app.kubernetes.io/name: elasticsearch
```

 **there is no way to modify the above values or remove the inclusion of instance or name** 

using Kustomize I applied a simple patch to remove it from the rendered manifest from `helm template`

```
#kustomize patch
patches:
  - target:
      kind: ServiceMonitor
      name: elasticsearch-metrics
    patch: |-
      - path: /spec/selector/matchLabels/app.kubernetes.io~1component
        op: remove
      - path: /spec/selector/matchLabels/app.kubernetes.io~1instance
        op: remove
      - path: /spec/jobLabel
        op: remove
```
