### ISSUE TITLE
Redmine doesn`t work on openshift

### ISSUE THREAD

**Issue by xrow** [bitnami/charts#1263]
**Which chart**:

redmine latest

**Description**

the redmine pod suffers permission issue due to the to the additional uid security in openshift. While the mysql container work . redmine crashes.

  
**Steps to reproduce the issue:**

```
helm init --client-only
helm repo update
helm install --replace --namespace $KUBERNETES_NAMESPACE_OVERWRITE --name redmine -f redmine/values.yaml stable/redmine
```

**Describe the results you received:**

```
  |  
-- | --
  | Welcome to the Bitnami redmine container
  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
  |  
  | INFO  ==> Starting redmine...
  | mkdir: cannot create directory '/opt/bitnami/redmine/tmp/pids': Permission denied
```

**Describe the results you expected:**

Please make the chart compatible to openshift.

**Additional information you deem important (e.g. issue happens only occasionally):**

```
rootUser:
  password: xxx
  forcePassword: true
db:
  user: redmine
  password: xxx
  name: remine
  forcePassword: true
master:
  persistence:
    enabled: true

securityContext:
  enabled: false

mariadb:
  securityContext:
    enabled: false
```

**Version of Helm and Kubernetes**:

```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://server010.dc03.xrow.net:8443
openshift v3.11.0+e88d6e9-205
kubernetes v1.11.0+d4cacc0
```
