### ISSUE TITLE
[bitnami/postgresql] auth. existingSecret not working

### ISSUE THREAD

**Issue by xarbit** [bitnami/charts#12667]
### Name and Version

bitnami/postgresql 14.5.0

### What steps will reproduce the bug?

1. set values to: 
```yaml
auth:
  enablePostgresUser: true
  existingSecret: db-master
  secretKeys:
    adminPasswordKey: postgres-password
```
2. try to login with Postgres user and set password key `'postgres-password'` in secrets 

### Are you using any custom parameters or values?

```yaml
auth:
  enablePostgresUser: true
  existingSecret: db-master
  secretKeys:
    adminPasswordKey: postgres-password
```

### What is the expected behavior?

this still works in chart version 11.6.6, it is expected to work in future versions as well.

### What do you see instead?

login fails with own password.

**Comment by fmulero** [comment]
Hi @xarbit I tried to reproduce your issue with latest postgresql chart, 11.9.1, without success. These are the steps I followed, please correct me if I am wrong or I missed any step (`postgresql.yaml` contains the values you shared in the description):

```console
$ kubectl create secret generic db-master --from-literal=postgres-password=321password
secret/db-master created
$ helm install psql bitnami/postgresql --version 11.9.1 -f postgresql.yaml
....
$ kubectl run psql-postgresql-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql:14.5.0-debian-11-r14 --command -- bash
I have no name!@psql-postgresql-client:/$ export PGPASSWORD=321password
I have no name!@psql-postgresql-client:/$ psql --host psql-postgresql -U postgres -d postgres -p 5432
psql (14.5)
Type "help" for help.

postgres=#
```

**Comment by xarbit** [comment]
Hi @fmulero 

this is what I do .. its from automation script but its basically the same. 
I see you call export PGPASSWORD=321password, I did not do that as it should do that for me if I use auth.existingSecret=db-master

1. create own, separate values.yaml and only add: 

```yaml
auth:
  enablePostgresUser: true
  existingSecret: db-master
  secretKeys:
    adminPasswordKey: postgres-password
```

3. create file named 'env-postgres' and add the key with password:

`postgres-password=321password`

4. create and apply secret from the env-postgres file

```bash
kubectl create secret generic db-master
            --save-config --dry-run=client --from-env-file=env-postgres -o yaml | kubectl apply -f -
```

5. Install Chart using the above values.yaml
`envsubst <values.yaml | helm upgrade --debug --install --wait -f - postgresql bitnami/postgresql`


7. enter the postgresql container Command-line and run:
`psql -U postgres`

8. enter password 321password.


As a note, I was able to see that the POSTGRES_PASSWORD was set correct, but I couldn't log in using it. 
Had to go back to chart version: 11.6.6 which works perfectly.
