### ISSUE TITLE
Grafana operator fails when zapLevel is set to debug

### ISSUE THREAD

**Issue by mtrin** [bitnami/charts#12666]
### Name and Version

grafana-operator:2.7.4

### What steps will reproduce the bug?

```yaml
operator:
    enabled: true
    scanAllNamespaces: true
    watchNamespace: "my-namespace" 
    zapDevel: true # 
    zapEncoder: "console"
    zapLevel: "debug"
```

### What is the expected behavior?

Operator would accept the flag as debug, accordingly to documentation

```
<html>
<body>
<!--StartFragment-->

operator.zapLevel | Zap log level (one of 'debug', 'info', 'error' or any integer value > 0) (default info) | string | ""
-- | -- | -- | --


<!--EndFragment-->
</body>
</html>
```

### What do you see instead?

The operator pod fails to start with:
`flag provided but not defined: -zap-level`

### Additional information

This seems to be related to the following lines:

https://github.com/bitnami/charts/blob/9e15346368a58970bfe079d242e8ea78bc2618ef/bitnami/grafana-operator/templates/deployment.yaml#L109-L111
