### ISSUE TITLE
[bitnami/mariadb] 10.5.11 is not showing metrics

### ISSUE THREAD

**Issue by stuartm21** [bitnami/charts#12674]
### Name and Version

bitnami/mariadb:10.5.11

### What steps will reproduce the bug?

I am using kube-prometheus-stack for monitor our kubernetes cluster. I tried to enable the metrics, but it is not working. 

### Are you using any custom parameters or values?

No, Nothing extra values using

### What is the expected behavior?

No errors

### What do you see instead?

Like your other apps, if I enabled the metrics I can see the two containers in the pod. But coming to Mariadb, I am seeing only single container in the pod

### Additional information

Pasting my code here. Added this code block under both primary and secondary side:
`metrics:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/mysqld-exporter
        tag: 0.13.0-debian-10-r19
      podAnnotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9104'
      serviceMonitor:
        enabled: true
        interval: 30s
        selector:
          release: prometheus`

**Comment by stuartm21** [comment]
@javsalgar Is this your bug or did I missed something ?

**Comment by javsalgar** [comment]
Hi,

How did you try enabling the metrics in the chart? I can see that `metrics.enabled=true` should enable the metrics.

**Comment by stuartm21** [comment]
Hi @javsalgar Yeah. I know that. I am installing mariadb via helm chart, so I tried to enable the metrics via helm chart. I am pasting my code block here: 
**Mariadb version: 10.5.11**
```
  metrics:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/mysqld-exporter
        tag: 0.14.0-debian-11-r37
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9104'
      serviceMonitor:
        enabled: true
        interval: 30s
        selector:
          release: prometheus
```
Using the "release: prometheus" label our bitnami apps(redis,mongo,rabbitmq) are working. But I don't know why this this not working here.
