### ISSUE TITLE
[bitnami/kafka] Let the JRE "determine Xmx and Xms flags automatically"

### ISSUE THREAD

**Issue by petr-cada** [bitnami/charts#12678]
### Name and Version

bitnami/kafka 18.1.3

### What is the problem this feature will solve?

Problem is that I need to adapt Xmx and Xms JVM flags manually when I set "resources" parameter ("requests.memory" and "limits.memory") in values.yaml. As far as I know current JREs support determining the container limits and they are able to use that information to "determine Xmx and Xms automatically".

It would be nice to have a possibility to unset Xmx and Xms flags of JVM in which Kafka is running.
Currently there is a possibility to set these flags via "heapOpts" paremeter (see values.yaml of Kafka helm chart). The problem is that you can not unset them (as far as I know). E.g. Via setting value of "heapOpts" parameter to "".

When I set the value of "heapOpts" parameter to "" the JVM was started with "-Xmx1024m -Xms1024m" anyway.

### What is the feature you are proposing to solve the problem?

E.g. From the user point of view to support setting of heapOpts parameter to "" and let the JRE "determine Xmx and Xms automatically".

Instead of current entries in values.yaml
------------------

```
heapOpts: "-Xmx512m -Xms512m"
resources:
  requests:
    memory: 704Mi
  limits:
    memory: 1024Mi
```

It can look like this
---------------------

```
heapOpts: ""
resources:
  requests:
    memory: 704Mi
  limits:
    memory: 1024Mi
```

So there will be no need to update "heapOpts" parameter when you decide to change memory limit for Kafka.
