### ISSUE TITLE
Used latest Spark Image to create a Standalone cluster - error of Initial Job didn't accept any resources

### ISSUE THREAD

**Issue by kiran-jayaram** [bitnami/charts#12687]
### Name and Version

bitnami/Spark:3.2.1 (but happens on 3.3 as well

### What steps will reproduce the bug?

Created a network with a single worker and but everytime I start it up, I am able to submit a job but I can't get it to execute as it's not able to find resources.

### What is the expected behavior?

On my local Spark, I am logging in with the --master spark://localhost:7077 and then trying to run a basic job

### What do you see instead?

![image](https://user-images.githubusercontent.com/95016070/192393172-7687e671-6fb6-4336-91fd-897125b35179.png)

### Additional information

The below is the compose_file

```
version: '2'

networks:
  netw:

services:
  spark-master:
    image: docker.io/bitnami/spark:3.2.1

    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080      

    ports:
      - '8080:8080'
      - '7077:7077'
      - '4040:4040'
      - '6066:6066'
    networks:
      - netw

  spark-worker:
    image: docker.io/bitnami/spark:3.2.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077      
      - SPARK_WORKER_MEMORY=8G
      - SPARK_WORKER_CORES=24      
      - SPARK_WORKER_PORT=40001
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

    ports:
      - '40001:40001'
      - '8081:8081'

    networks:
      - netw

    depends_on:
      - spark-master
```
