### ISSUE TITLE
[bitnami/external-dns] Issue with recent changes to chart

### ISSUE THREAD

**Issue by ranferimeza** [bitnami/charts#12680]
### Name and Version

bitnami/external-dns 6.8.2

### What steps will reproduce the bug?

Run: `helm upgrade --reuse-values -f "${BASEDIR}"/eks-infra/external-dns/values-aws-sync.yaml external-dns bitnami/external-dns -n add-ons`

### Are you using any custom parameters or values?
```yaml
aws:
  batchChangeSize: 4000
  apiRetries: 6
  zonesCacheDuration: "4h"
extraArgs:
  aws-batch-change-interval: "30s"
triggerLoopOnEvent: true
interval: "120m"

initContainers:
  - name: init-jitter
    image: public.ecr.aws/docker/library/busybox:stable-musl
    command:
    - /bin/sh
    - -c
    - 'FOR=$$((RANDOM % 30))s;echo "Sleeping for $$FOR";sleep $$FOR'
```
### What is the expected behavior?

upgrade works without issue

### What do you see instead?
```
Error: UPGRADE FAILED: template: external-dns/templates/secret.yaml:1:8: executing "external-dns/templates/secret.yaml" at <include "external-dns.createSecret" .>: error calling include: template: external-dns/templates/_helpers.tpl:117:49: executing "external-dns.createSecret" at <.Values.akamai.clientSecret>: nil pointer evaluating interface {}.clientSecret
deployment.apps/external-dns restarted
```
### Additional information

The same command works with external-dns 6.5.1 without issues. It seems recent changes introduced for the Akamai provider are causing this problem.
