### ISSUE TITLE
[bitnami/mongodb] mongodb-exporter keeps crashing with context canceled

### ISSUE THREAD

**Issue by oz117** [bitnami/charts#12717]
### Name and Version

bitnami/mongodb 13.1.5

### What steps will reproduce the bug?

I am running this chart inside aws eks on version 1.23 and having an issue with mongodb-exporter.
I am not really certain of the origin of the problem.

First here is my config:
```
global:
  storageClass: gp2-mongo

image:
  repository: public.ecr.aws/bitnami/mongodb
  tag: 6.0.1
  pullPolicy: IfNotPresent

auth:
  rootUser: [username]
  rootPassword: [password]
  replicaSetKey: [key]

architecture: "replicaset"

commonLabels:
  app: "mongodb"

annotations:
  app: "mongodb"

labels:
  app: "mongodb"

podLabels:
  app: "mongodb"

arbiter:
  enabled: false

metrics:
  enabled: true
  image:
    registry: public.ecr.aws
    repository: bitnami/mongodb-exporter
    tag: 0.34.0-debian-11-r17

replicaCount: 3

rbac:
  create: true

resources:
  requests:
    cpu: 0.75
    memory: 2G
  limits:
    cpu: 1
    memory: 4G
```

Whenever I enable the metrics the container running `mongodb-exporter` keeps on crashing, telling me that it cannot connect to mongodb. I can confirm that the `mongodb` container is running just fine.

I already tried to create a new user dedicated to the metrics, but it kept on giving me the same errors.

A small screenshot of the errors I am seeing:

![image](https://user-images.githubusercontent.com/6696897/192807338-0e2468ea-41ff-455c-ae7a-70d2849df35c.png)

I don't really understand what is happening here :confused:, what am I missing ?

### Are you using any custom parameters or values?

```
global:
  storageClass: gp2-mongo

image:
  repository: public.ecr.aws/bitnami/mongodb
  tag: 6.0.1
  pullPolicy: IfNotPresent

auth:
  rootUser: [username]
  rootPassword: [password]
  replicaSetKey: [key]

architecture: "replicaset"

commonLabels:
  app: "mongodb"

annotations:
  app: "mongodb"

labels:
  app: "mongodb"

podLabels:
  app: "mongodb"

arbiter:
  enabled: false

metrics:
  enabled: true
  image:
    registry: public.ecr.aws
    repository: bitnami/mongodb-exporter
    tag: 0.34.0-debian-11-r17

replicaCount: 3

rbac:
  create: true

resources:
  requests:
    cpu: 0.75
    memory: 2G
  limits:
    cpu: 1
    memory: 4G
```

### What is the expected behavior?

mongodb-exporter should connect to mongodb and not be in a crash-loop cycle

### What do you see instead?
```
level=info ts=2022-09-28T15:14:17.201Z caller=tls_config.go:195 msg="TLS is disabled." http2=false
time="2022-09-28T15:14:38Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-21]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:14:47Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-33]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:15:00Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-48]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:15:07Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-60]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:15:20Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-71]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:15:27Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-83]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:15:40Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-93]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:15:47Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-107]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:16:00Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-122]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:16:07Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-134]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:16:20Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-147]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:16:20Z" level=error msg="Failed to get $dbstats for database admin: connection(localhost:27017[-145]) incomplete read of message header: context canceled"
time="2022-09-28T15:16:20Z" level=error msg="Failed to get $dbstats for database config: timed out while checking out a connection from connection pool: context canceled; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other operations: 0"
time="2022-09-28T15:16:20Z" level=error msg="Failed to get $dbstats for database local: timed out while checking out a connection from connection pool: context canceled; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other operations: 0"
time="2022-09-28T15:16:20Z" level=error msg="Failed to get $dbstats for database tourop: timed out while checking out a connection from connection pool: context canceled; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other operations: 0"
time="2022-09-28T15:16:26Z" level=error msg="Registry - Cannot get node type to check if this is a mongos : timed out while checking out a connection from connection pool: context canceled; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other operations: 0"
time="2022-09-28T15:16:40Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-171]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:16:47Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-182]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:17:00Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-198]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:17:00Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-197]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:17:07Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-207]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:17:20Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-222]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:17:20Z" level=error msg="Failed to get $dbstats for database admin: connection(localhost:27017[-221]) failed to write: context canceled"
time="2022-09-28T15:17:20Z" level=error msg="Failed to get $dbstats for database config: connection(localhost:27017[-221]) failed to write: context canceled"
time="2022-09-28T15:17:20Z" level=error msg="Failed to get $dbstats for database local: connection(localhost:27017[-221]) failed to write: context canceled"
time="2022-09-28T15:17:20Z" level=error msg="Failed to get $dbstats for database tourop: connection(localhost:27017[-221]) failed to write: context canceled"
time="2022-09-28T15:17:27Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-233]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:17:40Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-245]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:17:47Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-258]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:17:57Z" level=error msg="Registry - Cannot get node type to check if this is a mongos : timed out while checking out a connection from connection pool: context canceled; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other operations: 0"
time="2022-09-28T15:18:07Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-285]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:18:17Z" level=error msg="Cannot connect to MongoDB: cannot connect to MongoDB: connection(localhost:27017[-297]) unable to write wire message to network: context canceled"
2022/09/28 15:18:18 http: panic serving 192.168.45.177:34846: runtime error: invalid memory address or nil pointer dereference
goroutine 8098 [running]:
net/http.(*conn).serve.func1()
	/opt/hostedtoolcache/go/1.17.12/x64/src/net/http/server.go:1802 +0xb9
panic({0xb36820, 0x1264f80})
	/opt/hostedtoolcache/go/1.17.12/x64/src/runtime/panic.go:1047 +0x266
go.mongodb.org/mongo-driver/mongo.newDatabase(0x0, {0xbf9cca, 0x5}, {0x0, 0x30, 0xc000054400})
	/home/runner/go/pkg/mod/go.mongodb.org/mongo-driver@v1.9.1/mongo/database.go:47 +0x5c
go.mongodb.org/mongo-driver/mongo.(*Client).Database(...)
	/home/runner/go/pkg/mod/go.mongodb.org/mongo-driver@v1.9.1/mongo/client.go:837
github.com/percona/mongodb_exporter/exporter.getClusterRole({0xd97ce0, 0xc000d0c1e0}, 0x40d1f4)
	/home/runner/work/mongodb_exporter/mongodb_exporter/exporter/topology_info.go:172 +0x8b
github.com/percona/mongodb_exporter/exporter.(*topologyInfo).loadLabels(0xc000772300, {0xd97ce0, 0xc000d0c1e0})
	/home/runner/work/mongodb_exporter/mongodb_exporter/exporter/topology_info.go:105 +0xeb
github.com/percona/mongodb_exporter/exporter.newTopologyInfo({0xd97ce0, 0xc000d0c1e0}, 0x0, 0xc000328d90)
	/home/runner/work/mongodb_exporter/mongodb_exporter/exporter/topology_info.go:75 +0xb0
github.com/percona/mongodb_exporter/exporter.(*Exporter).Handler.func1({0xd94f80, 0xc000cd00e0}, 0xc000ad1200)
	/home/runner/work/mongodb_exporter/mongodb_exporter/exporter/exporter.go:304 +0x3ab
net/http.HandlerFunc.ServeHTTP(0x0, {0xd94f80, 0xc000cd00e0}, 0x0)
	/opt/hostedtoolcache/go/1.17.12/x64/src/net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0, {0xd94f80, 0xc000cd00e0}, 0xc000ad1200)
	/opt/hostedtoolcache/go/1.17.12/x64/src/net/http/server.go:2425 +0x149
net/http.serverHandler.ServeHTTP({0xc000c3c2d0}, {0xd94f80, 0xc000cd00e0}, 0xc000ad1200)
	/opt/hostedtoolcache/go/1.17.12/x64/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0001b0dc0, {0xd97d18, 0xc0001a9d70})
	/opt/hostedtoolcache/go/1.17.12/x64/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.17.12/x64/src/net/http/server.go:3034 +0x4e8
time="2022-09-28T15:18:27Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-309]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:18:38Z" level=error msg="Registry - Cannot get node type to check if this is a mongos : connection(localhost:27017[-320]) incomplete read of full message: context canceled"
time="2022-09-28T15:18:47Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-332]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:19:00Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-348]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:19:07Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-359]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:19:20Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-371]) failed to write: context canceled" component=diagnosticDataCollector
time="2022-09-28T15:19:27Z" level=error msg="Cannot get node type to check if this is a mongos: connection(localhost:27017[-383]) failed to write: context canceled" component=diagnosticDataCollector
```
