### ISSUE TITLE
Argocd giving error while deploying the cert-manager

### ISSUE THREAD

**Issue by suchitsancheti** [bitnami/charts#12775]
### Name and Version

bitnami/cert-manager 0.8.4

### What steps will reproduce the bug?

1. Create an umbrella chart of cert-manager
```yaml
annotations:
  category: CertificateAuthority
apiVersion: v2
appVersion: 1.9.1
dependencies:
  - name: cert-maanger
    repository: https://charts.bitnami.com/bitnami
    tags:
      - cert-manager
    version: 0.8.4

description: Cert Manager is a Kubernetes add-on to automate the management and issuance of TLS certificates from various issuing sources.
engine: gotpl
home: https://github.com/jetstack/cert-manager
icon: https://bitnami.com/assets/stacks/cert-manager/img/cert-manager-stack-220x234.png
keywords:
  - go
  - security
  - tls
  - certificate
maintainers:
name: cert-manager
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/cert-manager
  - https://github.com/bitnami/containers/tree/main/bitnami/cert-manager-webhook
  - https://github.com/bitnami/containers/tree/main/bitnami/cainjector
  - https://github.com/jetstack/cert-manager
version: 0.8.4
```
2. Commit the change to git repo
3. Sync the application in argocd

### Are you using any custom parameters or values?

No

### What is the expected behavior?

ArgoCD should be able to pull the helm chart from the repo using the helm dependency build and cert-manager should be deployed in the cluster

### What do you see instead?

ArgoCD is failing to run the helm add repo command with the following error:
```
rpc error: code = Unknown desc = Manifest generation error (cached): `helm repo add https:--charts.bitnami.com-bitnami`` https://charts.bitnami.com/bitnami ``failed signal: killed`
```
This is causing the error in deploying the cert-manager using the argo cd

### Additional information

Tried setting the `controller.repo.server.timeout.seconds` to `1000` and `ARGOCD_EXEC_TIMEOUT` to `10m` still getting the same error. Other charts are getting downloaded and deployed using argocd in the cluster
