### ISSUE TITLE
[bitnami/redmine] certificates.customCA not working properly

### ISSUE THREAD

**Issue by NainzguL** [bitnami/charts#12787]
### Name and Version

bitnami/redmine 20.3.4

### What steps will reproduce the bug?

I have a kubernetes (minikube) environment with helm installed.
I just want to install redmine with custom CA, using the provided values.
To do so, I run 
`helm install redmine bitnami/redmine -f custom/values.yaml`

### Are you using any custom parameters or values?

I use this values.yaml file :
```yaml
image:
  repository: custom/redmine
  tag: "1.0"

redmineUsername: redAdmin
existingSecret: redmine-keys
mariadb:
  auth:
    existingSecret: redmine-keys

certificates:
  customCAs:
    - secret: redmine-ca

ingress:
  enabled: true
  hostname: redmine.local

postgresql:
  enabled: false
```

### What is the expected behavior?

The chart should be installed properly.

### What do you see instead?

the initContainer "certificates" never ends properly. The logs I can get are the following :
```sh
$ kubectl logs redmine-redmine-84d46cd84c-tmf55 -c certificates
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
apt failed, retrying
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
apt failed, retrying
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
```

### Additional information

From my understanding, the initContainer (bitnami/bitnami-shell) failed because it try to install some packages as non-root user :
Here is the container's command
```sh
install_packages ca-certificates openssl && openssl req -new -x509 -days 3650 -nodes -sha256 -subj "/CN=$(hostname)" -addext "subjectAltName = DNS:$(hostname)" -out  /etc/ssl/certs/ssl-cert-snakeoil.pem -keyout /etc/ssl/private/ssl-cert-snakeoil.key -extensions v3_req
```

But the last line in the DockerFile is `USER 1001` [see Here](https://github.com/bitnami/containers/blob/main/bitnami/bitnami-shell/11/debian-11/Dockerfile)
