### ISSUE TITLE
[bitnami/elasticsearch] Deployment getting error

### ISSUE THREAD

**Issue by bhaskarja1** [bitnami/charts#12789]
### Name and Version

bitnami/elasticsearch:8.14.1

### What steps will reproduce the bug?

1. kubernetes deplyment getting error

### What is the expected behavior?

Would you please let me know how to fix this error and I am not using GeoIP database, so how to remove this component from the deplyment yaml sample below

Deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipp-elastic
spec:
  selector:
    matchLabels:
      app: ipp-elastic
  replicas: 1
  template:
    metadata:
      labels:
        app: ipp-elastic
    spec:
      containers:
      - name: ipp-elastic
        image: docker.repo1.uhc.com/bitnami/elasticsearch:
          
        # env:
        # # - name: INGEST_GEOIP_DOWNLOADER_ENABLED
        # #   value: 'false'
        # livenessProbe:
        #     exec:
        #       command:
        #         - /bin/true
        # readinessProbe:
        #     exec:
        #       command:
        #         - /bin/true
        #     volumeMounts:
        #     - name: es-data
        #     mountPath: /data
        livenessProbe:
            exec:
              command:
                - /bin/true
        readinessProbe:
            exec:
              command:
                - /bin/true        
        imagePullPolicy: Always
        resources:
          limits:
            memory: 4Gi
            cpu: 500m
          requests:
            memory: 100Mi
            cpu: 10m
        volumeMounts:
        - name: storage
          mountPath: /bitnami
        securityContext:
          runAsUser: 1001
          privileged: false
          capabilities:
            drop:
              - KILL
              - MKNOD
              - SYS_CHROOT
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: ipp-storage
```
Error I am getting:

```
[2022-10-01T22:37:12,585][ERROR][o.e.i.g.GeoIpDownloader  ] [ipp-elastic-6dbc6486b-w5bx9] exception during geoip databases update java.net.SocketTimeoutException: Connect timed ou │
│     at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)                                                                                                │
│     at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)                                                                                                           │
│     at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)                                                                                                         │
│     at java.base/java.net.Socket.connect(Socket.java:633)                                                                                                                           │
│     at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)                                                                                                     │
│     at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)                                                                                                            │
│     at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532)                                                                                                        │
│     at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637)                                                                                                        │
│     at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)                                                                                                │
│     at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)                                                                                                   │
│     at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)                                        │
│     at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)      
```
### What do you see instead?

I need to fix the error or bypass the Geoip download
