### ISSUE TITLE
[bitnami/mysql] initdbScriptsConfigMap fails in replicaset with sql.gz file

### ISSUE THREAD

**Issue by sreepathy-tl** [bitnami/charts#12781]
### Name and Version

bitnami/mysql 8.0.30

### What steps will reproduce the bug?

- Download bitnami/mysql chart
- Change the following values in values.yaml

```
image.tag: 5.7.33-debian-10-r85
auth.rootPassword: "root"
architecture: replication
debug: true
auth.createDatabase: false
auth.database: ""
auth.username: ""
auth.password:""
initdbScriptsConfigMap: "init-db-scripts"
primary.containerSecurityContext:
    enabled: true
    runAsUser: 0
    runAsNonRoot: false
secondary.containerSecurityContext:
    enabled: true
    runAsUser: 0
    runAsNonRoot: false

```

- Compress an sql file  using gz to create your sql_file.sql.gz file
- Create a new directory `files` inside `mysql` directory and copy the `sql_file.sql.gz` file there
- create a `configmap-1.yaml` file with below contents inside the `mysql/templates` directory

```
{{ if .Files.Glob "files/*.sql.gz" }}
apiVersion: v1
kind: ConfigMap
metadata:
    name: init-db-scripts
    namespace: {{ .Release.Namespace | quote }}
data:
{{ (.Files.Glob "files/*.sql.gz").AsConfig | indent 2 }}
{{ end }}
```

- install the chart using command `helm install -n nmspc mysql mysql`
- Wait for the pod to get created
- Login to the pod's shell and check `ls docker-entrypoint-initdb.d/`
- The expected  `sql_file.sql.gz` or its inflated sql file is missing there
- Check the database to see if the initialization scripts were executed
- You will find that the sql files in gz file were NOT executed

### Are you using any custom parameters or values?

Yes. In values.yaml
```
image.tag: 5.7.33-debian-10-r85
auth.rootPassword: "root"
architecture: replication
debug: true
auth.createDatabase: false
auth.database: ""
auth.username: ""
auth.password:""
initdbScriptsConfigMap: "init-db-scripts"
primary.containerSecurityContext:
    enabled: true
    runAsUser: 0
    runAsNonRoot: false
secondary.containerSecurityContext:
    enabled: true
    runAsUser: 0
    runAsNonRoot: false
```

Custom configmap-1.yaml in templates/ directory
```
{{ if .Files.Glob "files/*.sql.gz" }}
apiVersion: v1
kind: ConfigMap
metadata:
    name: init-db-scripts
    namespace: {{ .Release.Namespace | quote }}
data:
{{ (.Files.Glob "files/*.sql.gz").AsConfig | indent 2 }}
{{ end }}
```

### What is the expected behavior?

The custom  **sql_file.sql.gz** kept in /files directory should be mounted to  **/docker-entrypoint-initdb.d** directory in the container and the deflated sql file should get executed in the first run in the primary node.

### What do you see instead?

The custom  **sql_file.sql.gz** kept in **/files** directory is not mounted to  **/docker-entrypoint-initdb.d** directory in the container and the deflated sql file  did not get executed in the first run.

### Additional information

- This option - **initdbScriptsConfigMap** - works correctly if deflated .sql files were kept in files directory. So basically it is only when we use sql.gz files in initdbScriptsConfigMap. 
- In my case, I have to load 5MB SQL file which when compressed to gz reduces to 700kb that can be used in a configmap

**Comment by fmulero** [comment]
Hi @sreepathy-tl thanks a lot for opening such detailed issue.

Currently we don't have implemented this feature, we only support `.sql` files in as valid files to initialize the database and there is no plan to support it in short term.

In your case you could workaround this issue, using an `initContainer` to uncompress the files. Please note, the following code is not tested and was created to share this idea, you may need to customize it:

```yaml
initContainers:
  - name: extractSQL
    image: bitnami/bitnami-shell:11-debian-11-r37
    command:
      - /bin/bash
      - -ec
      - |
        mkdir -p /tmp/empty-dir/init
        cp /tmp/scripts/*.gz /tmp/empty-dir/init
        tar -xvzf /tmp/empty-dir/init/*.gz 
    volumeMounts:
      - name: initDbVolume
        mountPath: /tmp/empty-dir
      - name: initScripts
        mountPath: /tmp/scripts
extraVolumeMounts:
  - name: initDbVolume
    mountPath: /docker-entrypoint-initdb.d
    subPath: init
extraVolumes:
  - name: initDbVolume
    emptyDir: {}
  - name: initScripts
    configMap:
      name: <Your configMap here >
```
