### ISSUE TITLE
Keycloak external database

### ISSUE THREAD

**Issue by Kvistian** [bitnami/charts#12809]
### Name and Version

bitnami/keycloak

### What steps will reproduce the bug?

Environment: Managed AWS EKS cluster

Config (`values.yaml`):
```
auth:
  adminUser: {user}
  adminPassword: {password}

proxy: edge
replicaCount: 2
resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"

postgresql:
  enabled: false

externalDatabase:
  database: keycloak
  host: jdbc:postgresql://{aws-instance-id}.{aws-region}.rds.amazonaws.com
  user: {user}
  password: {password}

cache:
  enabled: true

ingress:
  enabled: true
  hostname: {mydomain}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: {myCertificateArn}
    alb.ingress.kubernetes.io/ssl-redirect: '443'

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
```

Run:
`$ helm install keycloak --values values.yaml bitnami/keycloak`

Error:
```
$ kubectl logs keycloak-0
keycloak 06:57:59.71
keycloak 06:57:59.72 Welcome to the Bitnami keycloak container
keycloak 06:57:59.72 Subscribe to project updates by watching https://github.com/bitnami/containers
keycloak 06:57:59.72 Submit issues and feature requests at https://github.com/bitnami/containers/issues
keycloak 06:57:59.72
keycloak 06:57:59.72 INFO  ==> ** Starting keycloak setup **
keycloak 06:57:59.73 INFO  ==> Validating settings in KEYCLOAK_* env vars...
keycloak 06:57:59.74 INFO  ==> Trying to connect to PostgreSQL server jdbc:postgresql://{aws-instance-id}.{aws-region}.rds.amazonaws.com...
cannot resolve host "jdbc:postgresql://{aws-instance-id}.{aws-region}.rds.amazonaws.com": lookup jdbc:postgresql://{aws-instance-id}.{aws-region}.rds.amazonaws.com: no such host
cannot resolve host "jdbc:postgresql://{aws-instance-id}.{aws-region}.rds.amazonaws.com": lookup jdbc:postgresql://{aws-instance-id}.{aws-region}.rds.amazonaws.com: no such host
cannot resolve host "jdbc:postgresql://{aws-instance-id}.{aws-region}.rds.amazonaws.com": lookup jdbc:postgresql://{aws-instance-id}.{aws-region}.rds.amazonaws.com: no such host
```

### Are you using any custom parameters or values?

Only the values file specified above

### What is the expected behavior?

Keycloak connecting to my RDS instance

### What do you see instead?

```
cannot resolve host "jdbc:postgresql://{aws-instance-id}.{aws-region}.rds.amazonaws.com": lookup jdbc:postgresql://{aws-instance-id}.{aws-region}.rds.amazonaws.com: no such host
```

### Additional information

I have read through the documentation on [github](https://github.com/bitnami/charts/tree/master/bitnami/keycloak/#installing-the-chart) which says:

```
Sometimes, you may want to have Keycloak connect to an external PostgreSQL database rather than a database 
within your cluster - for example, when using a managed database service, or when running a single database 
server for all your applications. To do this, set the postgresql.enabled parameter to false and specify the 
credentials for the external database using the externalDatabase.* parameters.

Refer to the [chart documentation on using an external database](https://docs.bitnami.com/kubernetes/apps/keycloak/configuration/use-external-database) for more details and an example.
```

But the [chart documentation on using an external database](https://docs.bitnami.com/kubernetes/apps/keycloak/configuration/use-external-database) is empty.

The only thing I found on google was an answer on stackoverflow that suggested using a sidecar container for connecting to the database and pointed to a broken link.
Is the documentation on github incorrect, do I really need a sidecar container?
