### ISSUE TITLE
[bitnami/rabbitmq] Pod crashing on startup without errors

### ISSUE THREAD

**Issue by netthier** [bitnami/charts#12806]
### Name and Version

bitnami/rabbitmq 10.3.6

### What steps will reproduce the bug?

I deployed rabbitmq with the values listed below in my cluster.

### Are you using any custom parameters or values?

```yaml
  values:
    global:
      imageRegistry: hub.docker.com # See notes below
      storageClass: kubernetes-dev-storage-policy # Edited for privacy reasons
    communityPlugins: "rabbitmq_federation rabbitmq_federation_management"
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: rmq.example.com # Edited for privacy reasons
```

### What is the expected behavior?

I'd expect everything to start and work

### What do you see instead?

The volumes and other resources are created correctly.
Then the pod is created, successfully pulls the image, starts it, and enters into a CrashLoopBackoff status.
The logs are inconclusive:
```
$ kubectl logs --all-containers -n rabbitmq rabbitmq-0
rabbitmq 15:55:17.15
rabbitmq 15:55:17.16 Welcome to the Bitnami rabbitmq container
rabbitmq 15:55:17.16 Subscribe to project updates by watching https://github.com/bitnami/containers
rabbitmq 15:55:17.16 Submit issues and feature requests at https://github.com/bitnami/containers/issues
rabbitmq 15:55:17.17
rabbitmq 15:55:17.17 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 15:55:17.19 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 15:55:17.21 INFO  ==> Initializing RabbitMQ...
```
The logs stop at this point and the container restarts.

### Additional information

The Kubernetes cluster is deployed using VMWare Tanzu, with the cluster's version being `1.21.6+vmware.1-tkg.1.b3d708a`
`global.imageRegistry` is actually a Harbor instance where the images get pulled through.
