### ISSUE TITLE
Error when enabling clientEncryption

### ISSUE THREAD

**Issue by sillva** [bitnami/charts#1281]
**Which chart**:

bitnami/cassandra:2.3.10

**Description**

When setting `clientEncryption: true` the cluster doesn't go up properly

**Steps to reproduce the issue:**

1. Using the following config.yaml

```
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName

## Bitnami Cassandra image version
## ref: https://hub.docker.com/r/bitnami/cassandra/tags/
##
image:
  registry: docker.io
  repository: bitnami/cassandra
  ## Bitnami Cassandra image tag
  ## ref: https://github.com/bitnami/bitnami-docker-cassandra#supported-tags-and-respective-dockerfile-links
  ##
  tag: 3.11.4-debian-9-r98
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

## Specify a service type
## ref: http://kubernetes.io/docs/user-guide/services/
##
service:
  type: ClusterIP
  ## CQL Port
  port: 9042
  thriftPort: 9160
  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  # nodePort: 30001
  # loadBalancerIP:

  ## Provide any additional annotations which may be required. This can be used to
  ## set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  annotations: {}

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  ## If true, use a Persistent Volume Claim, If false, use emptyDir
  ##
  enabled: true
  ## Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  ## Persistent Volume Claim annotations
  ##
  annotations:
  ## Persistent Volume Access Mode
  ##
  accessModes:
  - ReadWriteOnce
  ## Persistent Volume size
  ##
  size: 8Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
## Minimum memory for development is 4GB and 2 CPU cores
## Minimum memory for production is 8GB and 4 CPU cores
## ref: http://docs.datastax.com/en/archived/cassandra/2.0/cassandra/architecture/architecturePlanningHardware_c.html
##
resources: {}
  # requests:
  #   memory: 4Gi
  #   cpu: 2
  # limits:
  #   memory: 4Gi
  #   cpu: 2

## Secret with keystore, keystore password, truststore, truststore password
# tlsEncryptionSecretName:
tlsEncryptionSecretName: cassandra-keystore
## ConfigMap with custom cassandra configuration files. This overrides any other Cassandra configuration set in the chart
# existingConfiguration:

## Cluster parameters
##
cluster:
  name: cassandra
  replicaCount: 3
  seedCount: 2
  numTokens: 256
  datacenter: ap-southeast-2
  rack: apse2-az1
  enableRPC: true
  endpointSnitch: SimpleSnitch
  minimumAvailable: 2
  ## Encryption values. NOTE: They require tlsEncryptionSecretName
  internodeEncryption: all
  clientEncryption: true

jvm:
  ## Extra JVM Settings
  ##
  extraOpts:

  ## Memory settings: These are calculated automatically
  ## unless specified otherwise
  ##
  # maxHeapSize: 4G
  # newHeapSize: 800M

## Database credentials
##
dbUser:
  user: cassandra
  forcePassword: true
  password: *********
  # existingSecret:

## ConfigMap with cql scripts. Useful for creating a keyspace
## and pre-populating data
##
#initDBConfigMap: default-keyspace
## Liveness and Readiness probe values.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
##
livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
readinessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

## Additional pod annotations
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

## Additional pod labels
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
podLabels: {}

## StatefulSet settings
##
statefulset:
  updateStrategy: RollingUpdate
  # rollingUpdatePartition:

## Pod Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001

## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Network policies
## Ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/
##
networkPolicy:
  ## Specifies whether a NetworkPolicy should be created
  ##
  enabled: true

  ## The Policy model to apply. When set to false, only pods with the correct
  ## client label will have network access to the port Redis is listening
  ## on. When true, Redis will accept connections from any source
  ## (with the correct destination port).
  ##
  # allowExternal: true

## Cassandra exporter configuration
## Ref: https://github.com/criteo/cassandra_exporter
##
metrics:
  enabled: true
  image:
    registry: docker.io
    pullPolicy: IfNotPresent
    repository: criteord/cassandra_exporter
    tag: 2.0.4
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName
  resources: {}
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
```

2. Then install it:
`helm install --name prod bitnami/cassandra -f cassandra-config.yaml --namespace production`

**Describe the results you received:**

Nonstop exception on logs:

`INFO  [epollEventLoopGroup-2-2] 2019-07-10 00:54:04,199 Message.java:687 - Unexpected exception during request; channel = [id: 0x47ff95a3, L:/10.2.2.218:9042 ! R:/10.2.2.218:59202]
io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 0400000001000000160001000b43514c5f56455253494f4e0005332e302e30`

Cluster to go up without exceptions.

The `internodeEncryption: all` works as it's been tested when `clientEncryption: false` so that I ruled out any issues with keystore/truststore.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-07T20:43:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
As you can see in the [README.md](https://github.com/bitnami/charts/blob/master/bitnami/cassandra/README.md):

cluster.clientEncryption | Set client-server encryption. NOTE: A value different from 'false' requires setting tlsEncryptionSecretName | false
-- | -- | --

I can see in your **values.yaml**:

```yaml
tlsEncryptionSecretName: cassandra-keystore
```

In order to reproduce the issue, could you share the "cassandra-keystore" secret or share the command you used to generate it? Thanks in advance.

**Comment by sillva** [comment]
```kubectl create secret generic --namespace=monitoring cassandra-keystore --from-file=keystore --from-file=truststore --from-literal=keystore-password=***** --from-literal=truststore-password=*****"```

Both the keystore and truststore are in JKS format. Also, I used keytool to list the keys inside and it worked.

To generate the stores I followed this post: [https://dzone.com/articles/setting-up-a-cassandra-cluster-with-ssl](https://dzone.com/articles/setting-up-a-cassandra-cluster-with-ssl)

**Comment by juan131** [comment]
Hi! 

Sorry for the late response but I was finally able to reproduce the issue, finding the errors below in the logs (**/opt/bitnami/cassandra/logs/cassandra.log**):

```
ERROR [main] 2019-07-12 14:28:43,581 CassandraDaemon.java:749 - Fatal configuration error
org.apache.cassandra.exceptions.ConfigurationException: Unable to create ssl socket
	at org.apache.cassandra.net.MessagingService.getServerSockets(MessagingService.java:701) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.net.MessagingService.listen(MessagingService.java:681) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.net.MessagingService.listen(MessagingService.java:665) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:796) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:683) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:632) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:388) [apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:620) [apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:732) [apache-cassandra-3.11.4.jar:3.11.4]
Caused by: java.io.IOException: Error creating the initializing the SSL Context
	at org.apache.cassandra.security.SSLFactory.createSSLContext(SSLFactory.java:201) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.security.SSLFactory.getServerSocket(SSLFactory.java:61) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.net.MessagingService.getServerSockets(MessagingService.java:697) ~[apache-cassandra-3.11.4.jar:3.11.4]
	... 8 common frames omitted
Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:785) ~[na:1.8.0_212-ojdkbuild]
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56) ~[na:1.8.0_212-ojdkbuild]
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224) ~[na:1.8.0_212-ojdkbuild]
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70) ~[na:1.8.0_212-ojdkbuild]
	at java.security.KeyStore.load(KeyStore.java:1445) ~[na:1.8.0_212-ojdkbuild]
	at org.apache.cassandra.security.SSLFactory.createSSLContext(SSLFactory.java:171) ~[apache-cassandra-3.11.4.jar:3.11.4]
	... 10 common frames omitted
Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:783) ~[na:1.8.0_212-ojdkbuild]
	... 15 common frames omitted
```

I'm going to create an internal task to investigate what's going on. Thanks so much for reporting it!

**Comment by Maraket** [comment]
@juan131 is there any movement on this? similar issue

**Comment by juan131** [comment]
Hi @Maraket 

This issue has been in our backlog for quite a long time. I'll try to raise the priority! Thanks for your consideration and patience.

**Comment by blindenvy** [comment]
We have also observed this issue, We're trying to use this chart via IBM Cloud Service but without being able to enable encryption its pretty useless. Please prioritize this!

**Comment by mmpetarpeshev** [comment]
Any update on this ?

**Comment by juan131** [comment]
I am afraid the task is still in our backlog. I'll try (again) to raise its priority and include it in the plan for next weeks. Thanks for your consideration and patience.

**Comment by mmpetarpeshev** [comment]
In my case was wrong password for the certs.

**Comment by simo222** [comment]
In my can it was different java version that solved issue. 
openjdk version "11.0.13"  did not work. 

openjdk version "1.8.0_252" worked for me.

**Comment by fmulero** [comment]
Hi @simo222 

Thanks a lot for your comment. The reason behind that is the format of the keystore. openjdk version 11.0.13 uses PKCS12 by default, in the other side, openjdk version 1.8 uses JKS. You can create a valid keystore for `bitnami/cassandra` containers with openjdk 11 setting JKS as your store type (the concrete parameter depends on your `keytool` command)

Please have look to the latest chart, it can create the keystore and truststore dynamically with your certificate. The following lines shows how you can configure it in your `values.yaml` file:

```
tls:
  internodeEncryption: all
  autoGenerated: true
  certificatesSecret: cassandra-cert
  passwordsSecret: cassandra-keypass
```
`cassandra-cert` should be a tls secret with your certificate (including the certificate authority). The following lines assume you've got the files `tls.crt`, `tls.key` and `ca.crt` in pem format :
```
kubectl create secret tls cassandra-cert --cert tls.crt --key tls.key
kubectl patch secret cassandra-cert -p="{\"data\":{\"ca.crt\": \"$(cat ca.crt | base64 )\"}}"
```
`passwordsSecret` contains the password for the generated keystores
```
kubectl create secret generic --namespace=default cassandra-keypass --from-literal=keystore-password=keypass --from-literal=truststore-password=trustpass
```
NOTE: At the moment it doesn't allow self signed certificates
