### ISSUE TITLE
[bitnami/etcd] Etcd option disasterRecovery requires persistence as a ReadWriteMulti - Question

### ISSUE THREAD

**Issue by bizonek27** [bitnami/charts#12859]
### Name and Version

bitnami/etcd - 8.5.5

### What steps will reproduce the bug?

Hi, more like a question.
After configuring persistence and disasterRecovery pods fails just after running snapshot pod. 
```yaml
        persistence:
          enabled: true
          size: 8Gi
          accessModes:
            - ReadWriteOnce
        disasterRecovery:
          enabled: true
          cronjob:
            schedule: '*/15 * * * *'
            snapshotHistoryLimit: 5
          pvc:
            existingClaim: "etcd-snapshot-claim"
            size: 2Gi
            storageClassName: gp2-etcd-a
```

### What is the expected behavior?

Create a snapshot

### What do you see instead?

Cannot mount data-etcd-0 is already mounted by pod etcd-0
