### ISSUE TITLE
[bitnami/wordpress] cannot change wp-config.php file

### ISSUE THREAD

**Issue by Braineanear** [bitnami/charts#12878]
### Name and Version

bitnami/wordpress 6.0.2

### What steps will reproduce the bug?

I'm trying to update the wp-config.php so i used the wordpressConfiguration parameter to put the content of the wp-config.php data inside it.
Which is not actually working.

### Are you using any custom parameters or values?
```yaml
wordpressUsername: "secret"
wordpressPassword: "secret"
wordpressEmail: "secret"
wordpressFirstName: "secret"
wordpressLastName: "secret"
wordpressSkipInstall: true
wordpressBlogName: "secret"
wordpressConfiguration: "@ini_set( 'upload_max_filesize' , '1024M' );@ini_set( 'upload_max_filesize' , '1024M' );@ini_set( 'post_max_size', '1024M');@ini_set( 'memory_limit', '1024M' );@ini_set( 'max_execution_time', '0' );@ini_set( 'max_input_time', '300' );"
overrideDatabaseSettings: true

persistence:
  size: 50Gi
mariadb:
  auth:
    username: "secret"
    password: "secret"
  primary:
    persistence:
      size: 50Gi
```

### What is the expected behavior?

Update the wp-config.php file and pod runs normally

### What do you see instead?

error message contains: "The WordPress configuration file '/opt/bitnami/wordpress/wp-config.php' is not writable. Configurations based on environment variables will not be applied for this file." in the pod shell and pod restarts everytime.
