### ISSUE TITLE
[bitnami/elasticsearch] Unable to retrieve version information from Elasticsearch nodes. socket hang up

### ISSUE THREAD

**Issue by tianjindaxue1202** [bitnami/charts#12882]
### Name and Version

bitnami/elasticsearch 18.2.16

### What steps will reproduce the bug?

my config:
```yaml
kibana:
  elasticsearch:
    hosts:
      - '{{ include "elasticsearch.service.name" . }}'
    port: '{{ include "elasticsearch.service.ports.restAPI" . }}'
    security:
      auth:
        createSystemUser: true
        elasticsearchPasswordSecret: elastic
        enable: true
        kibanaPassword: kibana
      tls:
        enable: true
        existingSecret: elastic-elasticsearch-coordinating-crt
        usePemCerts: true
```

I checked the relevant results of this question. The Elasticsearch.host configuration of Kibana should be https, but after installation, the configuration in elsaticsearch.hosts is http

### What do you see instead?

[ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. socket hang up
