### ISSUE TITLE
[bitnami/grafana-loki] Is filesystem storage supported?

### ISSUE THREAD

**Issue by k-jingyang** [bitnami/charts#12916]
### Name and Version

bitnami/grafana-loki: 2.4.2

### What steps will reproduce the bug?

I've been trying to get Loki working without an object storage backend. I'm not sure if the chart supports this. The current behaviour I'm experiencing is that I'm unable to query any logs that's older than 1hr.

I can't locate anything in the README on this as well.

For what it's worth, here's the Loki configuration.

```yaml
auth_enabled: true
chunk_store_config:
  chunk_cache_config:
    memcached:
      batch_size: 100
      parallelism: 100
    memcached_client:
      addresses: dns+observability-stack-memcachedchunks:11211
      consistent_hash: true
  max_look_back_period: 0s
compactor:
  shared_store: filesystem
distributor:
  ring:
    kvstore:
      store: memberlist
frontend:
  compress_responses: true
  log_queries_longer_than: 5s
  tail_proxy_url: http://observability-stack-loki-querier:3100
frontend_worker:
  frontend_address: observability-stack-loki-query-frontend:9095
ingester:
  chunk_block_size: 262144
  chunk_encoding: snappy
  chunk_idle_period: 30m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  max_transfer_retries: 0
  wal:
    dir: /bitnami/grafana-loki/wal
limits_config:
  enforce_metric_name: false
  max_cache_freshness_per_query: 10m
  per_tenant_override_config: /etc/tenants/overrides.yaml
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 744h
  split_queries_by_interval: 15m
memberlist:
  join_members:
  - observability-stack-loki-gossip-ring
query_range:
  align_queries_with_step: true
  cache_results: true
  max_retries: 5
  results_cache:
    cache:
      memcached_client:
        addresses: dns+observability-stack-memcachedfrontend:11211
        consistent_hash: true
        max_idle_conns: 16
        timeout: 500ms
        update_interval: 1m
ruler:
  alertmanager_url: https://alertmanager.xx
  external_url: https://alertmanager.xx
  ring:
    kvstore:
      store: memberlist
  rule_path: /tmp/loki/scratch
  storage:
    local:
      directory: /bitnami/grafana-loki/conf/rules
    type: local
schema_config:
  configs:
  - from: "2020-10-24"
    index:
      period: 24h
      prefix: index_
    object_store: filesystem
    schema: v11
    store: boltdb-shipper
server:
  http_listen_port: 3100
storage_config:
  boltdb_shipper:
    active_index_directory: /bitnami/grafana-loki/loki/index
    cache_location: /bitnami/grafana-loki/loki/cache
    cache_ttl: 168h
    shared_store: filesystem
  filesystem:
    directory: /bitnami/grafana-loki/chunks
  index_queries_cache_config:
    memcached:
      batch_size: 100
      parallelism: 100
    memcached_client:
      addresses: dns+observability-stack-memcachedindexqueries:11211
      consistent_hash: true
      service: http
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
```

### What is the expected behavior?

Show logs that are older than 1hr

### What do you see instead?

Only show logs within the hour
