### ISSUE TITLE
[bitnami/airflow] Cannot set Airflow connections in the chart

### ISSUE THREAD

**Issue by eclipsetalk** [bitnami/charts#12923]
### Name and Version

bitnami/airflow 2.3.4

### What steps will reproduce the bug?

Hello,
I cannot set Airflow connections in the current version of bitnami charts 2.3.4.
```yaml
connections:
        - id: ckd_gcp_2
          type: google_cloud_platform
          description: GCP connection
          extra: |
            {
              "extra__google_cloud_platform__key_path": "/opt/bitnami/airflow/keys/key.json",
              "extra__google_cloud_platform__num_retries: "5"
            }
```
Is it missing? Do you have any guidance on how this can be configured when deploying the chart?
Thank you in advance

### What do you see instead?

No connection are created if *connections* is added to the chart values
