### ISSUE TITLE
[cassandra] packaged cqlsh driver does not support protocol version 21

### ISSUE THREAD

**Issue by jgrabenstein** [bitnami/charts#12931]
### Name and Version

bitnami/cassandra 9.7.2

### What steps will reproduce the bug?

I have installed the latest chart (9.7.2) to our kubernetes cluster. Pods are stable & running. When I attempt to test the connection with `cqlsh`, I receive the error:

>`Connection error: ('Unable to connect to any servers', {'10.73.65.136:9042': ProtocolError('This version of the driver does not support protocol version 21')})`

Steps to reproduce:

1. Install bitnami/kafka chart with the values file i've provided
2. Fetch generated password from the `cassandra` secret and export as `CASSANDRA_PASSWORD`
3. Wait for the 3 cassandra replicas to start
4. Start a client container in the same namespace, like the guide suggests after install:
```
kubectl run --namespace cassandra cassandra-client --rm --tty -i --restart='Never' \
   --env CASSANDRA_PASSWORD=$CASSANDRA_PASSWORD \
    \
   --image bitnami/cassandra:4.0.6-debian-11-r11 -- bash
```
5. Attempt to connect with `cqlsh`:
```
cqlsh -u cassandra -p $CASSANDRA_PASSWORD cassandra
```

### Are you using any custom parameters or values?

```
cluster:
  name: cassandra-gusc1-dev
  datacenter: gusc1
  clientEncryption: true

replicaCount: 3
nodeSelector: 
  use: cassandra

tolerations:
  - key: "use"
    operator: "Equal"
    value: "cassandra"
    effect: "NoSchedule"

resources:
  limits:
    cpu: 2
    memory: 8Gi
  requests:
    cpu: 2
    memory: 8Gi

pdb:
  create: true
  minAvailable: ""
  maxUnavailable: 1

persistence:
  storageClass: premium-rwo
  commitStorageClass: premium-rwo
  size: 200Gi
  commitLogsize: 12Gi
  commitLogMountPath: "/bitnami/cassandra/commitlog"

tls:
  internodeEncryption: "all"
  autoGenerated: true
```

### What is the expected behavior?

I expect that cqlsh should be able to establish a connection. Since the images (client and server are the same) should have the correct version of cqlsh driver installed for the version of cassandra.

### What do you see instead?

`Connection error: ('Unable to connect to any servers', {'10.73.65.136:9042': ProtocolError('This version of the driver does not support protocol version 21')})`

### Additional information

I tried several 9.* versions of the chart and all result in the same error from cqlsh.
