### ISSUE TITLE
[bitnami/pinniped] Pinniped Supervisor missing service for aggregated API service

### ISSUE THREAD

**Issue by jessedearing** [bitnami/charts#12950]
### Name and Version

bitnami/pinniped 0.4.1

### What steps will reproduce the bug?

1. Install pinniped supervisor only.
2. Run `kubectl get apiservices.apiregistration.k8s.io v1alpha1.clientsecret.supervisor.pinniped.dev`

### Are you using any custom parameters or values?

```yaml
concierge:
  enabled: false
  rbac:
    create: false
supervisor:
  service:
    type: ClusterIP
    annotations:
      projectcontour.io/upstream-protocol.h2: "443,https"
  ingress:
    enabled: true
    ingressClassName: contour-external
    hostname: pinniped-supervisor.${LOCAL_CLUSTER_NAME}.${CELL_CONFIG_CELLREGION}.${CELL_CONFIG_CELLNAME}.${CELL_CONFIG_CELLZONE}
    tls: true
    extraTls:
      - hosts:
          - pinniped-supervisor.${LOCAL_CLUSTER_NAME}.${CELL_CONFIG_CELLREGION}.${CELL_CONFIG_CELLNAME}.${CELL_CONFIG_CELLZONE}
        secretName: pinniped-supervisor-server-tls

  configuration: |
    apiGroupSuffix: pinniped.dev
    names:
      defaultTLSCertificateSecret: pinniped-supervisor-server-tls
      apiService: pinniped-supervisor
```

### What is the expected behavior?

See `True` in the "AVAILABLE column.

### What do you see instead?

See in the "AVAILABLE" column `False (FailedDiscoveryCheck)`

```
❯ kubectl get apiservices.apiregistration.k8s.io v1alpha1.clientsecret.supervisor.pinniped.dev
NAME                                            SERVICE                                   AVAILABLE                      AGE
v1alpha1.clientsecret.supervisor.pinniped.dev   unstable/pinniped-supervisor   False (FailedDiscoveryCheck)   22h
```

### Additional information

It seems that pinniped supervisor is deployed but missing [the service to back the aggregated API endpoint](https://github.com/vmware-tanzu/pinniped/blob/eb62f04f217e0a280a3eb4181c9c57e8388d91f2/deploy/supervisor/deployment.yaml#L204-L220) and the apiservice created by the chart is referencing the supervisor endpoint itself.
