### ISSUE TITLE
[bitnami/thanos] Existing service account not used properly with new values schema

### ISSUE THREAD

**Issue by mbrancato** [bitnami/charts#12954]
### Name and Version

bitnami/thanos 11.5.5

### What steps will reproduce the bug?

1. Deploy the chart with a new `serviceAccount.name` described [here](https://github.com/bitnami/charts/blob/03778adc52921a4c83ce1be9aabb05a41a239e69/bitnami/thanos/values.yaml#L136-L151).
2. Observe the wrong service account name on the `compactor` (and I believe `storegateway`).

### Are you using any custom parameters or values?

```
  values:
    serviceAccount:
      create: false
      name: svc-monitoring
```

### What is the expected behavior?

Expect the assigned service account in the `thanos-compactor` Deployment to be `svc-monitoring`.

### What do you see instead?

```
      serviceAccount: thanos-compactor
      serviceAccountName: thanos-compactor
```

### Additional information

Reverting back to the deprecated `existingServiceAccount` fixes the issue, the correct service account is assigned to `compactor` and the `storegateway`.

```
      serviceAccount: svc-monitoring
      serviceAccountName: svc-monitoring
```

**Comment by mbrancato** [comment]
I too see it correct with `helm template`. I do know I've reported issues before where `helm template` does not exactly reproduce the same values as the install command.

From `helm list` on an affected cluster:
```
NAME                       	NAMESPACE    	REVISION	UPDATED                                	STATUS  	CHART                       	APP VERSION
...
kube-prometheus-stack      	monitoring   	2       	2022-10-13 20:40:49.189064008 +0000 UTC	deployed	kube-prometheus-stack-41.4.0	0.60.1     
thanos                     	monitoring   	2       	2022-10-13 21:45:11.196848458 +0000 UTC	deployed	thanos-11.5.5               	0.28.1     
```

**Comment by mbrancato** [comment]
FYI I was able to reproduce this with both `helm template` and `helm install --dry-run`.

using a values.yaml:

```yaml
serviceAccount:
  create: false
  name: svc-monitoring
objstoreConfig: |-
  type: GCS
  config:
    bucket: my-bucket
compactor:
  enabled: true
storegateway:
  enabled: true
queryFrontend:
  enabled: true
query:
  enabled: true
```

The resulting `serviceAccount` should be set to `svc-monitoring` but it does not happen:
```
% helm install thanos-test bitnami/thanos --version 11.5.5 --dry-run -f values.yaml | grep serviceAccount
      serviceAccount: thanos-test-compactor
      serviceAccount: thanos-test-query-frontend
      serviceAccount: thanos-test-query
      serviceAccount: thanos-test-storegateway
```

```
% helm template thanos-test bitnami/thanos --version 11.5.5 -f values.yaml | grep serviceAccount 
      serviceAccount: thanos-test-compactor
      serviceAccount: thanos-test-query-frontend
      serviceAccount: thanos-test-query
      serviceAccount: thanos-test-storegateway
```
```
