### ISSUE TITLE
Pod metrics in elasticsearch failed when deploy elasticsearch

### ISSUE THREAD

**Issue by patsevanton** [bitnami/charts#12957]
### Name and Version

bitnami/elasticsearch 19.4.2

### What steps will reproduce the bug?
```
helm install --wait -n elasticsearch my-elasticsearch bitnami/elasticsearch -f value.yaml
```

### Are you using any custom parameters or values?
```
master:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 256Mi

data:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 256Mi

coordinating:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 256Mi

metrics:
  enabled: true
```

### What is the expected behavior?

install elasticsearch without error

### What do you see instead?

https://gist.github.com/patsevanton/91ff1d968f708e3731fa36330a2c8b13

### Additional information
```
kubectl get pod -n elasticsearch
NAME                                       READY   STATUS    RESTARTS   AGE
my-elasticsearch-coordinating-0            1/1     Running   0          22m
my-elasticsearch-data-0                    1/1     Running   0          22m
my-elasticsearch-ingest-0                  1/1     Running   0          22m
my-elasticsearch-ingest-1                  1/1     Running   0          22m
my-elasticsearch-master-0                  1/1     Running   0          22m
my-elasticsearch-metrics-944c9685b-bpwr5   1/1     Running   1          22m
```
