### ISSUE TITLE
[bitnami/redis] Redis external master replicas not working as expected

### ISSUE THREAD

**Issue by amrragab95** [bitnami/charts#12985]
### Name and Version

bitnami/redis latest

### What steps will reproduce the bug?

1.EKS version 1.21

```
  externalMaster:
    enabled: true
    host: "redis-poc-master.redis-replica-poc.svc.cluster.local"
    port: 6379
```
3.
<img width="978" alt="image" src="https://user-images.githubusercontent.com/93654678/196159758-436d78e3-d1f5-4145-9d93-d48d844c45f4.png">
here it shows that it's using service from the namespace of the replica redis which is using the master node of the first namespace

### What do you see instead?

<img width="978" alt="image" src="https://user-images.githubusercontent.com/93654678/196159959-3589d2ad-291a-45db-9e88-a4c307c4cd18.png">
here it shows that it's using service from the namespace of the replica redis which is using the master node of the first namespace
