### ISSUE TITLE
Rabbitmq using Keycloak OIDC Provider, keycloak login page is not shown

### ISSUE THREAD

**Issue by andreapulvirenti** [bitnami/charts#12982]
### Name and Version

bitnami/rabbitmq 11.0.0

### What steps will reproduce the bug?

accordingly with documentations page 
[https://blog.rabbitmq.com/posts/2022/07/oidc-integration/](url)
we're struggling with configuration of keycloak as OIDC provider for RabbitMQ. 

In test environment using the configuration: 

```
{
          "enable_uaa" : true,
          "oauth_enabled" : true,
          "oauth_client_id" : "rabbitmq",
          "oauth_client_secret": "<secret>",
          "oauth_provider_url": "<URL>",
          "vhosts": [
            {
              "name": "/"
            }
          ],
          "parameters": [{
            "value": {
              "pattern": ".*",
              "definition": {
                "delivery-limit": {{ .Values.rabbitmqConfiguration.messagePoisonPolicy.deliveryLimit }}
              },
              "priority": 0,
              "apply-to": "queues"
            },
            "vhost": "/",
            "component": "operator_policy",
            "name": "<poisoning>"
          }]
        }
```

- install rabbitmq chart and install keycloak chart.

- Create confidential client named rabbitmq on keycloak and set the following parameters:
![image](https://user-images.githubusercontent.com/14847376/196140699-7b03335e-00db-45b0-bd88-90db21861b6e.png)
- Create the Guest user in keycloak setting password "guest", user enabled and Email verified. 
![image](https://user-images.githubusercontent.com/14847376/196142907-3a920117-6e68-470c-a206-2755a09ad6d9.png)

- Get the client secret generated on Credential Tab and the Keycloak URL in order to fulfill the configuration json above. 
- On Admin tab in Rabbitmq Management page set the guest permission for vhost "/"

![image](https://user-images.githubusercontent.com/14847376/196141923-1f224fea-63d1-4ad5-87a2-7d2407458559.png)

- After that you should see in rabbimtq-0 pod some logs like:
_"user 'guest' authenticated and granted access to vhost '/'"_

### Are you using any custom parameters or values?

```yaml
rabbitmq: 
  global:
  replicaCount: 1
  service: 
    type: ClusterIP
  fullnameOverride: "rabbitmq"
  labels: {}
  clustering: 
    rebalance: true
    forceBoot: true
  auth:
    username: "guest"
    password: "guest"
    erlangCookie: "<ERLANGCOOKIE>"
  loadDefinition: 
    enabled: true
    existingSecret: "<DEFINITION SECRET>"
  extraConfiguration: |-
    raft.wal_max_size_bytes = 64000000
    management.load_definitions = /app/load_definition.json
    disk_free_limit.relative = 2.0
  resources:
    requests:
      cpu: "150m"
      memory: "256Mi"
    limits:
      cpu: "800m"
      memory: "2Gi"
```

### What is the expected behavior?

Connections seem to work but if you access on rabbitmq management page, the classic page is shown instead of keycloak one. 
![image](https://user-images.githubusercontent.com/14847376/196143546-5256dcb4-ea57-4506-9ea8-8fde3b02ed3a.png)

### What do you see instead?

Classic Rabbitmq login page

### Additional information

Let me know if you need any additional information
