### ISSUE TITLE
Not able to set the MongoDB Cluster variables - `connPoolMaxConnsPerHost`

### ISSUE THREAD

**Issue by anjanitsip** [bitnami/charts#13002]
### Name and Version

bitnami/mongodb:12.1.31

### What steps will reproduce the bug?

We are creating MongoDB cluster with 1 primary and 2 secondary nodes.  But we are not able to set cluster configuration values like - **connPoolMaxConnsPerHost** 

As per documentation, We are using updating Configuration to setup primary and secondary node 

```
## @param configuration MongoDB(&reg;) configuration file to be used for Primary and Secondary nodes
## For documentation of all options, see: http://docs.mongodb.org/manual/reference/configuration-options/
## Example:
configuration: |-
  # where and how to store data.
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
  # where to write logging data
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
     path: /opt/bitnami/mongodb/logs/mongodb.log
     verbosity: 0
   # network interfaces
   net:
     port: 27017
     unixDomainSocket:
       enabled: true
       pathPrefix: /opt/bitnami/mongodb/tmp
     ipv6: false
     bindIpAll: true
   # replica set options
   replication:
     replSetName: replicaset
     enableMajorityReadConcern: true
   # process management options
   processManagement:
      fork: false
      pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
   # set parameter options
   setParameter:
      enableLocalhostAuthBypass: true
      connPoolMaxConnsPerHost: 5000 
   # security options
   security:
     authorization: disabled
     keyFile: /opt/bitnami/mongodb/conf/keyfile

```

But we are getting below error, and cluster is not created  -   
```
[ec2-user@ip-10-0-101-50 ~]$ kubectl -n persistence -c mongodb logs -f mongodb-0
mongodb 01:03:14.04 INFO  ==> Advertised Hostname: mongodb-0.mongodb-headless.persistence.svc.cluster.local
mongodb 01:03:14.04 INFO  ==> Advertised Port: 27017
mongodb 01:03:14.05 INFO  ==> Data dir empty, checking if the replica set already exists
MongoNetworkError: connect ECONNREFUSED 10.62.18.128:27017
mongodb 01:03:15.03 INFO  ==> Pod name matches initial primary pod name, configuring node as a primary
mongodb 01:03:15.04
mongodb 01:03:15.05 Welcome to the Bitnami mongodb container
mongodb 01:03:15.05 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 01:03:15.05 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 01:03:15.05
mongodb 01:03:15.05 INFO  ==> ** Starting MongoDB setup **
mongodb 01:03:15.06 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 01:03:15.12 INFO  ==> Initializing MongoDB...
mongodb 01:03:15.13 INFO  ==> Deploying MongoDB from scratch...
```

```
[ec2-user@ip-10-0-101-50 ~]$ kubectl -n persistence get pods
NAME                READY   STATUS             RESTARTS         AGE
mongodb-0           0/2     CrashLoopBackOff   23 (2m46s ago)   30m
mongodb-arbiter-0   1/1     Running            3 (4m5s ago)     30m
```

### What do you see instead?

MongoNetworkError: connect ECONNREFUSED 10.62.18.128:27017
