### ISSUE TITLE
[Spark] Affinity dosent work

### ISSUE THREAD

**Issue by samuel-begin** [bitnami/charts#1300]
**Which chart**:
bitnami/spark
apiVersion: v1
appVersion: 2.4.3

**Description**
affinity configurations dont work

**Steps to reproduce the issue:**
use something like this in the values you use for deployment
```
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: "app.kubernetes.io/name"
            operator: In
            values:
            - spark
        topologyKey: "kubernetes.io/hostname"
```

**Describe the results you received:**
affinity is appended in `metadata`
no effects in pod affinity

**Describe the results you expected:**
affinity should be appended in `spec`
https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity

**Additional information you deem important (e.g. issue happens only occasionally):**
here's the git diff that fixes the problem. tested on both satefulspecs for master and workers
```
@@ -23,6 +23,7 @@ spec:
         app.kubernetes.io/instance: {{ .Release.Name }}
         helm.sh/chart: {{ include "spark.chart" . }}
         app.kubernetes.io/component: master
+    spec:
    {{- if .Values.master.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.master.nodeSelector | nindent 8 }}
    {{- end }}
    {{- with .Values.master.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.master.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
-    spec:
       {{- include "spark.imagePullSecrets" . | nindent 6 }}
       {{- if .Values.master.securityContext.enabled }}
       securityContext:
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
