### ISSUE TITLE
Unable to apply transitionToAuth

### ISSUE THREAD

**Issue by nivimorbgp** [bitnami/charts#13036]
### Name and Version

bitnami/mongodb 10.12.2

### What steps will reproduce the bug?

1. Configure mongo rs with a configuration parameter in values.yaml:
```yaml   
    # where and how to store data.
    storage:
      dbPath: /bitnami/mongodb/data/db
      journal:
        enabled: true
      directoryPerDB: false
    # where to write logging data
    systemLog:
      destination: file
      quiet: false
      logAppend: true
      logRotate: reopen
      path: /opt/bitnami/mongodb/logs/mongodb.log
      verbosity: 0
    # network interfaces
    net:
      port: 27017
      unixDomainSocket:
        enabled: true
        pathPrefix: /opt/bitnami/mongodb/tmp
      ipv6: false
      bindIpAll: true
    # replica set options
    #replication:
      #replSetName: replicaset
      #enableMajorityReadConcern: true
    # process management options
    processManagement:
        fork: false
        pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
    # set parameter options
    setParameter:
        enableLocalhostAuthBypass: true
    # security options
    security:
      authorization: enabled
      transitionToAuth: true
      keyFile: /opt/bitnami/mongodb/conf/keyfile
```

2. Mongo tries to init but keeps crashing. 
3. There are no apparent error messages, just the following:
```Pod name matches initial primary pod name, configuring node as a primary
mongodb 07:28:31.86 
mongodb 07:28:31.86 Welcome to the Bitnami mongodb container
mongodb 07:28:31.87 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 07:28:31.87 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 07:28:31.87 
mongodb 07:28:31.88 INFO  ==> ** Starting MongoDB setup **
mongodb 07:28:31.93 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 07:28:31.97 INFO  ==> Initializing MongoDB...
mongodb 07:28:31.98 INFO  ==> Deploying MongoDB from scratch...

```

### Are you using any custom parameters or values?

Using the configuration parameter in values.yaml.
Also using 

```yaml
  auth:
    replicaSetKey: "*******"

```

### What is the expected behavior?

Mongo should start and allow for both authenticated and non-authenticated access.

### What do you see instead?

Mongo just gets into a `back-off restarting failed` container loop.

### Additional information

[transitionToAuth](https://www.mongodb.com/docs/manual/tutorial/enforce-keyfile-access-control-in-existing-replica-set-without-downtime/#overview) is a parameter in mongo conf that allows for both authenticated and non-authenticated access to mongo.

**Comment by nivimorbgp** [comment]
Ran with 

`BITNAMI_DEBUG: true`

but I'm only getting this:

```about to fork child process, waiting until server is ready for connections.
forked process: 40
ERROR: child process failed, exited with 1
To see additional information in this output, start without the "--fork" option.```

**Comment by nivimorbgp** [comment]
Another thing I realized, it's probably not possible to have both auth.enabled=true and transitionToAuth at the same time.

However, transitionToAuth requires the keyfile, and the chart only creates the keyfile if auth.enabled=true.

**Comment by nivimorbgp** [comment]
Another update:

I tried to bypass the obstacle mentioned above by doing the following:

1. I created a configmap that contains the contents of the keyfile
2. I created a volume and volume mount:

```
extraVolumes:
  - name: keyfile
    configMap:
        name: keyfile

extraVolumeMounts:
  - name: keyfile
    mountPath: /opt/bitnami/mongodb/conf/keyfile
    subPath: keyfile
```

3. I passed the `transitionToAuth` and `keyFile` flags through `extraFlags`:

```
extraFlags:
  - "--transitionToAuth"
  - "--keyFile=/opt/bitnami/mongodb/conf/keyfile"
```

The container keeps crashing:


```
mongodb 09:52:50.20 
mongodb 09:52:50.21 Welcome to the Bitnami mongodb container
mongodb 09:52:50.21 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 09:52:50.21 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 09:52:50.22 
mongodb 09:52:50.22 INFO  ==> ** Starting MongoDB setup **
mongodb 09:52:50.24 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 09:52:50.24 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mongodb 09:52:50.27 INFO  ==> Initializing MongoDB...
mongodb 09:52:50.30 INFO  ==> Deploying MongoDB from scratch...
mongodb 09:52:50.30 DEBUG ==> Starting MongoDB in background...
about to fork child process, waiting until server is ready for connections.
forked process: 45
ERROR: child process failed, exited with 1
To see additional information in this output, start without the "--fork" option.
```
