### ISSUE TITLE
[bitnami/redis] password is not taking from secrets it creates its own

### ISSUE THREAD

**Issue by resulraveendran** [bitnami/charts#13049]
### Name and Version

bitnami/redis redis-17.3.5

### What steps will reproduce the bug?

I tried deploying redis using helm and I could also notice that the redis nodes are taking the default secrets of its own from the chart-configuration and not from secrets even though âexistingSecret: redis-config' parameter is added in the yaml file.

### Are you using any custom parameters or values?
```
helm install nq-redis-${ENV} bitnami/redis  --values values-production.yaml -n nq-stage
```
```yaml
usePassword: true
usePasswordFile: true   
existingSecret: redis-config
cluster:
  enabled: false
persistence:
  enabled: false
```

### What do you see instead?

'redis.exceptions.ResponseError: WRONGPASS invalid username-password pair or user is disabled.'
