### ISSUE TITLE
[bitnami/elasticearch] Unable to retrieve version information from Elasticsearch nodes. unable to verify the first certificate

### ISSUE THREAD

**Issue by tianjindaxue1202** [bitnami/charts#13093]
### Name and Version

bitnami/elasticearch 19.4.4

### What steps will reproduce the bug?

my config
```yaml
clusterDomain: cluster.local
clusterName: elastic
commonAnnotations: {}
commonLabels: {}
config: {}
containerPorts:
  restAPI: 9200
  transport: 9300
coordinating:
  affinity: {}
  annotations: {}
  args: []
  autoscaling:
    enabled: false
    maxReplicas: 11
    minReplicas: 3
    targetCPU: ''
    targetMemory: ''
  command: []
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraVolumeMounts: []
  extraVolumes: []
  fullnameOverride: ''
  heapSize: 128m
  hostAliases: []
  initContainers: []
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 90
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  nameOverride: ''
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: ''
  podLabels: {}
  podManagementPolicy: Parallel
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  priorityClassName: ''
  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 90
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 2
  resources:
    limits: {}
    requests:
      cpu: 25m
      memory: 256Mi
  schedulerName: ''
  serviceAccount:
    annotations: {}
    automountServiceAccountToken: true
    create: false
    name: ''
  servicenameOverride: ''
  sidecars: []
  startupProbe:
    enabled: false
    failureThreshold: 5
    initialDelaySeconds: 90
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  terminationGracePeriodSeconds: ''
  tolerations: []
  topologySpreadConstraints: []
  updateStrategy:
    type: RollingUpdate
data:
  affinity: {}
  annotations: {}
  args: []
  autoscaling:
    enabled: false
    maxReplicas: 11
    minReplicas: 3
    targetCPU: ''
    targetMemory: ''
  command: []
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraVolumeMounts: []
  extraVolumes: []
  fullnameOverride: ''
  heapSize: 1024m
  hostAliases: []
  initContainers: []
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 90
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  nameOverride: ''
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  persistence:
    accessModes:
      - ReadWriteOnce
    annotations: {}
    enabled: true
    existingClaim: ''
    existingVolume: ''
    selector: {}
    size: 8Gi
    storageClass: ''
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: ''
  podLabels: {}
  podManagementPolicy: Parallel
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  priorityClassName: ''
  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 90
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 2
  resources:
    limits: {}
    requests:
      cpu: 25m
      memory: 2048Mi
  schedulerName: ''
  serviceAccount:
    annotations: {}
    automountServiceAccountToken: true
    create: false
    name: ''
  servicenameOverride: ''
  sidecars: []
  startupProbe:
    enabled: false
    failureThreshold: 5
    initialDelaySeconds: 90
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  terminationGracePeriodSeconds: ''
  tolerations: []
  topologySpreadConstraints: []
  updateStrategy:
    type: RollingUpdate
diagnosticMode:
  args:
    - infinity
  command:
    - sleep
  enabled: false
extraConfig: {}
extraDeploy: []
extraEnvVars: []
extraEnvVarsCM: ''
extraEnvVarsSecret: ''
extraHosts: []
extraVolumeMounts: []
extraVolumes: []
fullnameOverride: ''
global:
  elasticsearch:
    service:
      name: elasticsearch
      ports:
        restAPI: 9200
  imagePullSecrets: []
  imageRegistry: ''
  kibanaEnabled: true
  storageClass: local-path
image:
  debug: false
  digest: ''
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: docker.io
  repository: bitnami/elasticsearch
  tag: 8.4.3-debian-11-r2
ingest:
  affinity: {}
  annotations: {}
  args: []
  autoscaling:
    enabled: false
    maxReplicas: 11
    minReplicas: 3
    targetCPU: ''
    targetMemory: ''
  command: []
  containerPorts:
    restAPI: 9200
    transport: 9300
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  enabled: true
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraVolumeMounts: []
  extraVolumes: []
  fullnameOverride: ''
  heapSize: 128m
  hostAliases: []
  ingress:
    annotations: {}
    apiVersion: ''
    enabled: false
    extraHosts: []
    extraPaths: []
    extraRules: []
    extraTls: []
    hostname: elasticsearch-ingest.local
    ingressClassName: ''
    path: /
    pathType: ImplementationSpecific
    secrets: []
    selfSigned: false
    tls: false
  initContainers: []
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 90
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  nameOverride: ''
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: ''
  podLabels: {}
  podManagementPolicy: Parallel
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  priorityClassName: ''
  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 90
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 2
  resources:
    limits: {}
    requests:
      cpu: 25m
      memory: 256Mi
  schedulerName: ''
  service:
    annotations: {}
    clusterIP: ''
    enabled: false
    externalTrafficPolicy: Cluster
    extraPorts: []
    loadBalancerIP: ''
    loadBalancerSourceRanges: []
    nodePorts:
      restAPI: ''
      transport: ''
    ports:
      restAPI: 9200
      transport: 9300
    sessionAffinity: None
    sessionAffinityConfig: {}
    type: ClusterIP
  serviceAccount:
    annotations: {}
    automountServiceAccountToken: true
    create: false
    name: ''
  servicenameOverride: ''
  sidecars: []
  startupProbe:
    enabled: false
    failureThreshold: 5
    initialDelaySeconds: 90
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  terminationGracePeriodSeconds: ''
  tolerations: []
  topologySpreadConstraints: []
  updateStrategy:
    type: RollingUpdate
ingress:
  annotations: {}
  apiVersion: ''
  enabled: false
  extraHosts: []
  extraPaths: []
  extraRules: []
  extraTls: []
  hostname: elasticsearch.local
  ingressClassName: ''
  path: /
  pathType: ImplementationSpecific
  secrets: []
  selfSigned: false
  tls: false
initContainers: []
initScripts: {}
initScriptsCM: ''
initScriptsSecret: ''
kibana:
  elasticsearch:
    hosts:
      - '{{ include "elasticsearch.service.name" . }}'
    port: '{{ include "elasticsearch.service.ports.restAPI" . }}'
    security:
      auth:
        createSystemUser: true
        enable: true
        kibanaPassword: kibana
      tls:
        enable: true
        existingSecret: elkt-elasticsearch-coordinating-crt
        usePemCerts: true
  extraConfiguration:
    elasticsearch:
      hosts:
        - 'https://{{ include "elasticsearch.service.name" . }}:9200'
    i18n:
      locale: zh-CN
    server:
      host: 0.0.0.0
  service:
    nodePorts:
      http: 30602
    ports:
      http: 5601
    type: NodePort
  tls:
    autoGenerated: true
    enabled: true
kubeVersion: ''
master:
  affinity: {}
  annotations: {}
  args: []
  autoscaling:
    enabled: false
    maxReplicas: 11
    minReplicas: 3
    targetCPU: ''
    targetMemory: ''
  command: []
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraVolumeMounts: []
  extraVolumes: []
  fullnameOverride: ''
  heapSize: 128m
  hostAliases: []
  initContainers: []
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 90
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  masterOnly: true
  nameOverride: ''
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  persistence:
    accessModes:
      - ReadWriteOnce
    annotations: {}
    enabled: true
    existingClaim: ''
    existingVolume: ''
    selector: {}
    size: 8Gi
    storageClass: ''
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: ''
  podLabels: {}
  podManagementPolicy: Parallel
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  priorityClassName: ''
  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 90
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 2
  resources:
    limits: {}
    requests:
      cpu: 25m
      memory: 256Mi
  schedulerName: ''
  serviceAccount:
    annotations: {}
    automountServiceAccountToken: true
    create: false
    name: ''
  servicenameOverride: ''
  sidecars: []
  startupProbe:
    enabled: false
    failureThreshold: 5
    initialDelaySeconds: 90
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  terminationGracePeriodSeconds: ''
  tolerations: []
  topologySpreadConstraints: []
  updateStrategy:
    type: RollingUpdate
metrics:
  affinity: {}
  args: []
  command: []
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  enabled: false
  extraArgs: []
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraVolumeMounts: []
  extraVolumes: []
  fullnameOverride: ''
  hostAliases: []
  image:
    digest: ''
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/elasticsearch-exporter
    tag: 1.5.0-debian-11-r27
  initContainers: []
  livenessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  nameOverride: ''
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  podAffinityPreset: ''
  podAnnotations:
    prometheus.io/port: '9114'
    prometheus.io/scrape: 'true'
  podAntiAffinityPreset: ''
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  priorityClassName: ''
  prometheusRule:
    additionalLabels: {}
    enabled: false
    namespace: ''
    rules: []
  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  resources:
    limits: {}
    requests: {}
  schedulerName: ''
  service:
    annotations:
      prometheus.io/port: '9114'
      prometheus.io/scrape: 'true'
    port: 9114
    type: ClusterIP
  serviceMonitor:
    enabled: false
    honorLabels: false
    interval: ''
    jobLabel: ''
    labels: {}
    metricRelabelings: []
    namespace: ''
    relabelings: []
    scrapeTimeout: ''
    selector: {}
  sidecars: []
  startupProbe:
    enabled: false
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  tolerations: []
  topologySpreadConstraints: []
nameOverride: ''
namespaceOverride: ''
plugins: ''
security:
  elasticPassword: elastic
  enabled: true
  existingSecret: ''
  fipsMode: false
  tls:
    autoGenerated: true
    coordinating:
      existingSecret: ''
    data:
      existingSecret: ''
    ingest:
      existingSecret: ''
    keyPassword: ''
    keystoreFilename: elasticsearch.keystore.jks
    keystorePassword: ''
    master:
      existingSecret: ''
    passwordsSecret: ''
    restEncryption: true
    secretKey: ''
    secretKeystoreKey: ''
    secretTruststoreKey: ''
    truststoreFilename: elasticsearch.truststore.jks
    truststorePassword: ''
    usePemCerts: false
    verificationMode: full
service:
  annotations: {}
  clusterIP: ''
  externalTrafficPolicy: Cluster
  extraPorts: []
  loadBalancerIP: ''
  loadBalancerSourceRanges: []
  nodePorts:
    restAPI: '30201'
    transport: '30301'
  ports:
    restAPI: 9200
    transport: 9300
  sessionAffinity: None
  sessionAffinityConfig: {}
  type: NodePort
sidecars: []
snapshotRepoPath: ''
sysctlImage:
  digest: ''
  enabled: true
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: docker.io
  repository: bitnami/bitnami-shell
  resources:
    limits: {}
    requests: {}
  tag: 11-debian-11-r41
volumePermissions:
  enabled: false
  image:
    digest: ''
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 11-debian-11-r41
  resources:
    limits: {}
    requests: {}

```

### What do you see instead?

```
[2022-10-23T09:29:44.892+00:00][INFO ][plugins.taskManager] TaskManager is identified by the Kibana UUID: 31e951bb-8008-40cc-ae4c-828f6ccf92d4
[2022-10-23T09:29:45.023+00:00][WARN ][plugins.security.config] Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-10-23T09:29:45.064+00:00][WARN ][plugins.security.config] Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-10-23T09:29:45.077+00:00][WARN ][plugins.encryptedSavedObjects] Saved objects encryption key is not set. This will severely limit Kibana functionality. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-10-23T09:29:45.103+00:00][WARN ][plugins.actions] APIs are disabled because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-10-23T09:29:45.247+00:00][WARN ][plugins.reporting.config] Generating a random key for xpack.reporting.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.reporting.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-10-23T09:29:45.248+00:00][WARN ][plugins.reporting.config] Found 'server.host: "0.0.0.0"' in Kibana configuration. Reporting is not able to use this as the Kibana server hostname. To enable PNG/PDF Reporting to work, 'xpack.reporting.kibanaServer.hostname: localhost' is automatically set in the configuration. You can prevent this message by adding 'xpack.reporting.kibanaServer.hostname: localhost' in kibana.yml.
[2022-10-23T09:29:45.256+00:00][WARN ][plugins.alerting] APIs are disabled because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-10-23T09:29:45.322+00:00][INFO ][plugins.ruleRegistry] Installing common resources shared between all indices
[2022-10-23T09:29:45.388+00:00][INFO ][plugins.cloudSecurityPosture] Registered task successfully [Task: cloud_security_posture-stats_task]
[2022-10-23T09:29:46.322+00:00][WARN ][plugins.screenshotting.config] Chromium sandbox provides an additional layer of protection, but is not supported for Linux Debian 11.5 OS. Automatically setting 'xpack.screenshotting.browser.chromium.disableSandbox: true'.
[2022-10-23T09:29:46.437+00:00][ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. unable to verify the first 
```

**Comment by carrodher** [comment]
I'm not able to reproduce the issue using the default values, could you please share the specific parameters that were modified instead of the whole values file?

**Comment by tianjindaxue1202** [comment]
```
global:
  kibanaEnabled: true

security:
  elasticPassword: elastic
  enabled: true
  tls:
    autoGenerated: true

kibana:
  elasticsearch:
    hosts:
      - '{{ include "elasticsearch.service.name" . }}'
    port: '{{ include "elasticsearch.service.ports.restAPI" . }}'
    security:
      auth:
        createSystemUser: true
        enable: true
        kibanaPassword: kibana
      tls:
        # this option not work，so i use the extraConfiguration
        enable: true
        existingSecret: elkt-elasticsearch-coordinating-crt
        usePemCerts: true
  extraConfiguration:
    elasticsearch:
      hosts:
        - 'https://{{ include "elasticsearch.service.name" . }}:9200'
    i18n:
      locale: zh-CN
    server:
      host: 0.0.0.0
  service:
    nodePorts:
      http: 30602
    ports:
      http: 5601
    type: NodePort
  tls:
    autoGenerated: true
    enabled: true
```

this is my Changed configuration。
[https://github.com/bitnami/charts/issues/7928](url) this proble exist for a long time.Others have the same problem
