### ISSUE TITLE
[keycloak] can not export realm

### ISSUE THREAD

**Issue by artarik** [bitnami/charts#13105]
### Name and Version

bitnami/keycloak:10.1.2

### What steps will reproduce the bug?

1. install helm chart via custom values (described below)
2. created and configured realm *oidc* via GUI
3. goto keycloak pod `kubectl exec -it kk-0 -- bash`
4. run export command `keycloak@kk-0: /opt/bitnami/keycloak/bin/kc.sh export --file oidc.json --realm oidc --users skip`

### Are you using any custom parameters or values?

```yaml
nameOverride: kk
fullnameOverride: kk
image:
  pullPolicy: Always

auth:
  adminUser: kk-admin
  existingSecret:
    name: keycloak
    keyMapping:
      admin-password: kk_admin_pass
      databasePassword: postgres_pass

replicaCount: 3

resources:
  limits:
    memory: "3072Mi"
    cpu: "1"
  requests:
    cpu: "100m"
    memory: "1024Mi"

service:
  type: ClusterIP
  ports:
    http: 80
    https: 443

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: kk.cluster.local

networkPolicy:
  enabled: false

serviceAccount:
  create: true
  name: ""
  automountServiceAccountToken: true
  annotations: {}

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPU: "55"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    endpoints:
    - path: /metrics
    - path: /realms/oidc/metrics
    selector: {}
  prometheusRule:
    enabled: true

postgresql:
  enabled: true
  auth:
    database: keycloak
    existingSecret: keycloak-db
    secretKeys:
      adminPasswordKey: "username"
      userPasswordKey: "password"
  architecture: standalone

cache:
  enabled: true

logging:
  output: json
```

### What do you see instead?

```
Appending additional Java properties to JAVA_OPTS: -Djgroups.dns.query=kk-headless.oidc-provider.svc.cluster.local
{"timestamp":"2022-10-24T11:25:05.384Z","sequence":50,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider","level":"INFO","message":"Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"kk-0","processName":"QuarkusEntryPoint","processId":30228}
{"timestamp":"2022-10-24T11:25:10.643Z","sequence":8205,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.common.crypto.CryptoIntegration","level":"INFO","message":"Detected crypto provider: org.keycloak.crypto.def.DefaultCryptoProvider","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"kk-0","processName":"QuarkusEntryPoint","processId":30228}
{"timestamp":"2022-10-24T11:25:18.278Z","sequence":8439,"loggerClassName":"org.infinispan.util.logging.Log_$logger","loggerName":"org.infinispan.PERSISTENCE","level":"WARN","message":"ISPN000554: jboss-marshalling is deprecated and planned for removal","threadName":"keycloak-cache-init","threadId":18,"mdc":{},"ndc":"","hostName":"kk-0","processName":"QuarkusEntryPoint","processId":30228}
{"timestamp":"2022-10-24T11:25:18.642Z","sequence":8440,"loggerClassName":"org.infinispan.util.logging.Log_$logger","loggerName":"org.infinispan.CONFIG","level":"WARN","message":"ISPN000569: Unable to persist Infinispan internal caches as no global state enabled","threadName":"keycloak-cache-init","threadId":18,"mdc":{},"ndc":"","hostName":"kk-0","processName":"QuarkusEntryPoint","processId":30228}
{"timestamp":"2022-10-24T11:25:18.84Z","sequence":8441,"loggerClassName":"org.infinispan.util.logging.Log_$logger","loggerName":"org.infinispan.CONTAINER","level":"INFO","message":"ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'","threadName":"keycloak-cache-init","threadId":18,"mdc":{},"ndc":"","hostName":"kk-0","processName":"QuarkusEntryPoint","processId":30228}
{"timestamp":"2022-10-24T11:25:20.441Z","sequence":8442,"loggerClassName":"org.infinispan.util.logging.Log_$logger","loggerName":"org.infinispan.CONTAINER","level":"INFO","message":"ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final","threadName":"keycloak-cache-init","threadId":18,"mdc":{},"ndc":"","hostName":"kk-0","processName":"QuarkusEntryPoint","processId":30228}
{"timestamp":"2022-10-24T11:25:20.952Z","sequence":8443,"loggerClassName":"org.infinispan.util.logging.Log_$logger","loggerName":"org.infinispan.CLUSTER","level":"INFO","message":"ISPN000078: Starting JGroups channel `ISPN`","threadName":"keycloak-cache-init","threadId":18,"mdc":{},"ndc":"","hostName":"kk-0","processName":"QuarkusEntryPoint","processId":30228}
{"timestamp":"2022-10-24T11:25:21.678Z","sequence":8445,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler","level":"ERROR","message":"ERROR: Failed to start server in (import_export) mode","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"kk-0","processName":"QuarkusEntryPoint","processId":30228}
{"timestamp":"2022-10-24T11:25:21.68Z","sequence":8446,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler","level":"ERROR","message":"ERROR: Failed to start caches","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"kk-0","processName":"QuarkusEntryPoint","processId":30228}
{"timestamp":"2022-10-24T11:25:21.68Z","sequence":8447,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler","level":"ERROR","message":"ERROR: org.infinispan.manager.EmbeddedCacheManagerStartupException: org.infinispan.commons.CacheException: Unable to start JGroups Channel","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"kk-0","processName":"QuarkusEntryPoint","processId":30228}
{"timestamp":"2022-10-24T11:25:21.68Z","sequence":8448,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler","level":"ERROR","message":"ERROR: org.infinispan.commons.CacheException: Unable to start JGroups Channel","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"kk-0","processName":"QuarkusEntryPoint","processId":30228}
{"timestamp":"2022-10-24T11:25:21.681Z","sequence":8449,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler","level":"ERROR","message":"ERROR: Unable to start JGroups Channel","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"kk-0","processName":"QuarkusEntryPoint","processId":30228}
{"timestamp":"2022-10-24T11:25:21.681Z","sequence":8450,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler","level":"ERROR","message":"ERROR: no port available in range [7800 .. 7800] (bind_addr=/10.233.232.59)","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"kk-0","processName":"QuarkusEntryPoint","processId":30228}
{"timestamp":"2022-10-24T11:25:21.682Z","sequence":8451,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler","level":"ERROR","message":"For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"kk-0","processName":"QuarkusEntryPoint","processId":30228}
```
