### ISSUE TITLE
[bitnami/redis] failed to unmarshal manifest

### ISSUE THREAD

**Issue by nichcuta** [bitnami/charts#13140]
### Name and Version

bitnami/redis 17.3.7

### What steps will reproduce the bug?

ArgoCD server running v2.4.X with Helm version v3.8.1 and using the config provided below, ArgoCD application Fails with 'converting YAML to JSON: yaml: line 6: mapping values are not allowed in this context''

### Are you using any custom parameters or values?

ArgoCD plugin configmap config:
```
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
    - name: argocd-helm-vault-plugin
      generate:
        command: ["sh", "-c"]
        args: ["helm dependency build && helm template ${ARGOCD_ENV_helm_args} . > all.yaml && argocd-vault-plugin generate all.yaml"]
```

ArgoCD Application plugin section:
```
plugin:
          name: argocd-helm-vault-plugin
          env:
            - name: helm_args
               value: -n default -f "values/test-redis-password.yaml" test
```

values.yaml file:
```
redis:
  architecture: replication
  replica:
    replicaCount: 3
    resources:
      limits:
        memory: "2Gi"
  auth:
    enabled: true
    sentinel: true
    existingSecret: test-redis-password
    existingSecretPasswordKey: redis-password
  sentinel:
    enabled: true
    masterSet: test_cache_cluster
    resources:
      limits:
        memory: "1Gi"
    configuration: |-
      loglevel notice
  commonConfiguration: |-
    # User-supplied common configuration:
    loglevel notice
    maxclients 10000
    maxmemory 1024mb
    maxmemory-policy allkeys-lfu
    appendonly no
    # Disable RDB persistence, AOF persistence already enabled.
    save ""
    # End of common configuration
```

### What is the expected behavior?

For it to deploy a redis-sentinel cluster

### What do you see instead?

```
status:
  conditions:
  - lastTransitionTime: "2022-10-25T14:08:17Z"
    message: 'rpc error: code = Unknown desc = failed to unmarshal manifest: error
      converting YAML to JSON: yaml: line 6: mapping values are not allowed in this
      context'
    type: ComparisonError
```

### Additional information

This chart seems to be incompatible with ArgoCD version 2.4X and future releases which is a problem. One should note that the chart works fine with prior ArgoCD versions.

**Comment by javsalgar** [comment]
Hi,

It seems that the chart is being used as a subchart. Could you add more details on this?

**Comment by nichcuta** [comment]
Sure, only a chart.yaml and values file provided above are used.

Chart.yaml
```
---
apiVersion: v2
name: redis-subchart
type: application
version : 1.0.3
appVersion: "1.0.0"
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.3.7
```

**Comment by nichcuta** [comment]
Any updates regarding this issue?

**Comment by corico44** [comment]
Hello @nichcuta,
I can't reproduce the error. Could you tell me exactly what files you are modifying and the added or modified content of those files?
Also, I've been looking into the error itself and at first glance, it seems to be something related to indentation. Could you check that the indentation of everything added is correct?
Here are some examples of your error:

- https://stackoverflow.com/questions/68178304/helm-error-converting-yaml-to-json-yaml-line-29-mapping-values-are-not-allo
- https://github.com/helm/helm/issues/6251
- https://stackoverflow.com/questions/62201210/error-converting-yaml-to-json-yaml-line-10-mapping-values-are-not-allowed-in
- https://stackoverflow.com/questions/60367255/how-to-fix-the-error-in-yaml-file-converting-yaml-to-json-mapping-values-are-no

**Comment by nichcuta** [comment]
So let me recap. These are the files I'm using:

Chart.yaml
```
---
apiVersion: v2
name: redis-subchart
type: application
version : 1.0.3
appVersion: "1.0.0"
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.3.7
```

values.yaml
```
redis:
  architecture: replication
  replica:
    replicaCount: 3
    resources:
      limits:
        memory: "2Gi"
  auth:
    enabled: true
    sentinel: true
  sentinel:
    enabled: true
    masterSet: test_cache_cluster
```

argocd-application-set.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis-application-set
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: "aws/stg/test-cluster/eks00"
        redisname: test
        namespace: default
        repoTag: HEAD
  template:
    metadata:
      name: "{{redisname}}-redis"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - ServerSideApply=true
        - Validate=false
      source:
        repoURL: https://github.company.com/repos/redis_k8s.git
        targetRevision: "{{repoTag}}"
        path: test-gitops/helm
        plugin:
          name: argocd-helm-vault-plugin
          env:
            - name: helm_args
              value: -n {{namespace}} -f "values/values.yaml" {{redisname}}
      destination:
        server: 'https://kubernetes.default.svc'
        namespace:  "{{namespace}}"
```

configured argocd plugins
```
apiVersion: v1
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  configManagementPlugins: |
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
    - name: argocd-helm-vault-plugin
      generate:
        command: ["sh", "-c"]
        args: ["helm dependency build && helm template ${ARGOCD_ENV_helm_args} . > all.yaml && argocd-vault-plugin generate all.yaml"]
  exec.enabled: "false"
```

helm, argocd, vault plugin versions:
```
HELM: version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}
ArgoCD: argocd v2.4.15+05acf7a
Vault-plugin: argocd-vault-plugin v1.13.0 (6866b7206719e9b5b2ea4d7cb870e18f76534637) BuildDate: 2022-09-19T15:06:23Z
```

Note that I'm not manipulating any files but simply relying on helm and argocd to apply the generated manifest. The error is misleading and I cannot seem to narrow it down to a specific portion of the generated YAML file.

This works just fine with the below helm, argocd & vault plugin versions:
```
HELM: version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}
ArgoCD: argocd v2.3.1+b65c169
Vault-plugin: argocd-vault-plugin v1.4.0 (60fed6f08b363f92d61760f48ac80da704f5c1c5) BuildDate: 2021-09-28T16:35:48Z
```

Seems like the generated manifest is no longer compatible with the new argoCD version

**Comment by corico44** [comment]
Hello @nichcuta,

I can't reproduce the error. Using only the configuration that you provided for redis and performing helm install using that values.yaml with the changes, there doesn't seem to be any errors. The error as such comes from the argo itself?

**Comment by nichcuta** [comment]
Hi @corico44,

managed to fix the issue by replacing the argocd-helm-vault-plugin definition to the below:
```
FOR ARGOCD < 2.4:
- name: argocd-helm-vault-plugin
      init:
        command: ["sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: ["sh", "-c"]
        args: ["helm template ${helm_args} . > all.yaml && argocd-vault-plugin generate all.yaml"]

FOR ARGOCD > 2.4:
- name: argocd-helm-vault-plugin
      init:
        command: ["sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: ["sh", "-c"]
        args: ["helm template ${ARGOCD_ENV_helm_args} . > all.yaml && argocd-vault-plugin generate all.yaml"]
```
Although the previous plugin definition seems to do the same, it was causing the issue..

Thanks for your help
