### ISSUE TITLE
Add common oauth2-proxy args as chart values

### ISSUE THREAD

**Issue by cmbaatz** [bitnami/charts#13195]
### Name and Version

bitnami/oauth2-proxy 3.3.3

### What is the problem this feature will solve?

A typical oauth2-proxy configuration may include a few arguments that point to environment specific hosts.  These could include the `--oidc-issuer-url`,  `--redirect-url`, and the `--whitelist-domain` oauth2-proxy command line arguments.  Currently the only way to provide these values is to add them to the extraArgs chart variable.  When trying to reuse the chart in multiple environments this means that all extraArgs chart variables need to be redefined in environment specific values files, which makes the management of non-host based extraArgs more difficult.

## Current Setup
values.yaml
```yaml
oauth2-proxy:
  extraArgs:
    - --provider=keycloak-oidc
    - --show-debug-on-error=true
    - --silence-ping-logging=true
    - --upstream=static://200
    - --skip-provider-button=true
    - --reverse-proxy=true
    - --set-xauthrequest=true
    - --pass-access-token=true
    - --set-authorization-header=true
    - --pass-authorization-header=true
    - --pass-user-headers=true
    - --pass-host-header=true
    - --cookie-name=session  
    - --redirect-url: https://dev.test.com/oauth2/callback
    - --oidc-issuer-url: https://dev.test.com/auth/realms/test
    - --white-list: dev.test.com,auth.dev.test.com
```
qa-values.yaml
```yaml
oauth2-proxy:
  extraArgs:
    - --provider=keycloak-oidc
    - --show-debug-on-error=true
    - --silence-ping-logging=true
    - --upstream=static://200
    - --skip-provider-button=true
    - --reverse-proxy=true
    - --set-xauthrequest=true
    - --pass-access-token=true
    - --set-authorization-header=true
    - --pass-authorization-header=true
    - --pass-user-headers=true
    - --pass-host-header=true
    - --cookie-name=session  
    - --redirect-url: https://qa.test.com/oauth2/callback
    - --oidc-issuer-url: https://qa.test.com/auth/realms/test
    - --white-list: qa.test.com,auth.qa.test.com
```

## Suggested Setup
> Helm will load the Chart values from values.yaml and then add then overwrite values from the qa-values.yaml file.
values.yaml
```yaml
oauth2-proxy:
  extraArgs:
    - --provider=keycloak-oidc
    - --show-debug-on-error=true
    - --silence-ping-logging=true
    - --upstream=static://200
    - --skip-provider-button=true
    - --reverse-proxy=true
    - --set-xauthrequest=true
    - --pass-access-token=true
    - --set-authorization-header=true
    - --pass-authorization-header=true
    - --pass-user-headers=true
    - --pass-host-header=true
    - --cookie-name=session  
  configuration:
    redirectUrl: https://dev.test.com/oauth2/callback
    oidcIssuerUrl: https://dev.test.com/auth/realms/test
    whiteList: dev.test.com,auth.dev.test.com
```
qa-values.yaml
```yaml
oauth2-proxy:
  configuration:
    redirectUrl: https://dev.test.com/oauth2/callback
    oidcIssuerUrl: https://dev.test.com/auth/realms/test
    whiteList: dev.test.com,auth.dev.test.com
```

#### Dev
```shell
helm install oauth2-proxy .
``` 
#### QA
```shell
helm install -f qa-values.yaml oauth2-proxy .
``` 

### What is the feature you are proposing to solve the problem?

Use the new configuration chart values to populate specific args in the oath2-proxy deployment template.

PR will be submitted with the change.

### What alternatives have you considered?

The alternative is to redefine the entire extraArgs chart variable for each environment which makes it harder to keep the non-environment specific value in sync.
