### ISSUE TITLE
Keycloak fail on deployment

### ISSUE THREAD

**Issue by j0nathan33** [bitnami/charts#13206]
### Name and Version

keycloak/11.0.0

### What steps will reproduce the bug?

I'm trying to deploy to kubernetes with this command:
```console
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm upgrade --install keycloak-dev2 bitnami/keycloak --values values2.yaml
```

When I remove the `passwordsSecret`, deployment to kubernites is working well

### Are you using any custom parameters or values?

```yaml
spi:
  existingSecret: "keycloak-crt"
  truststoreFilename: "keycloak-spi.truststore.jks"
  passwordsSecret: "keycloak-dev"
  hostnameVerificationPolicy: "WILDCARD"
```

### What is the expected behavior?

Deployment to Kubernetes is working

### What do you see instead?
```
Release "keycloak-dev2" does not exist. Installing it now.
Error: YAML parse error on keycloak/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 81: mapping values are not allowed in this context
```
