### ISSUE TITLE
Default path to keycloak config cli jar is wrong

### ISSUE THREAD

**Issue by taliesins** [bitnami/charts#13200]
### Name and Version

bitnami/keycloak/templates/keycloak-config-cli-job.yaml

### What steps will reproduce the bug?

Create a new keycloak instance using the helm chart that also sets up the realm using configuration as code via the keycloak cli job.

The error message received is:
```
Error: Unable to access jarfile /opt/bitnami/keycloak-config-cli/keycloak-config-cli-19.0.3.jar
```

Code that probably needs to be fixed is at: https://github.com/bitnami/charts/blob/main/bitnami/keycloak/templates/keycloak-config-cli-job.yaml#L60

If you look at the docker image for the path:
https://github.com/bitnami/containers/blob/main/bitnami/keycloak-config-cli/5/debian-11/Dockerfile#L40

```
RUN ln -sf /opt/bitnami/keycloak-config-cli/keycloak-config-cli.jar /opt/keycloak-config-cli.jar
```

To be honest I think the fix is not to update the path but rather to really on the container instance provided default command.

Container default command:
https://github.com/bitnami/containers/blob/main/bitnami/keycloak-config-cli/5/debian-11/Dockerfile#L46
```Dockerfile
WORKDIR /opt/bitnami/keycloak-config-cli
USER 1001
ENTRYPOINT [ "java", "-jar", "./keycloak-config-cli.jar" ]
``` 

### Are you using any custom parameters or values?

Helm value.yaml
```yaml
keycloak:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostname: keycloak.localhost
  keycloakConfigCli:
    enabled: true
    config:
      default:
        file: files/default-realm.json
    #config:    
    # <realm name>:
    #   inline:
    #     realm: <realm name>
    #     clients: []
    # <realm name>:
    #   file: <path>
```

files/default-realm.json
```
{
    "enabled": true,
    "realm": "default",
    "smtpServer": {
      "from": "keycloak-config-cli@default.com",
      "fromDisplayName": "keycloak-config-cli",
      "host": "mailing.default.com",
      "auth": true,
      "envelopeFrom": "keycloak-config-cli@default.com",
      "user": "username",
      "password": "password"
    },
    "clients": [
      {
        "name": "whoami-client",
        "enabled": true,
        "clientAuthenticatorType": "client-secret",
        "secret": "my-special-client-secret",
        "redirectUris": [
          "*"
        ],
        "webOrigins": [
          "*"
        ]
      }
    ]
  }
```

### What is the expected behavior?

Should not have to configure the command for the container job but it works by default.

### What do you see instead?

The container command points to a path that does not exist, so the container job fails.
