### ISSUE TITLE
[bitnami/keycloak] chart ignores tls parameters

### ISSUE THREAD

**Issue by ht-vo** [bitnami/charts#13211]
### Name and Version

bitnami/keycloak 11.0.0

### What steps will reproduce the bug?

```sh
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install app-auth bitnami/keycloak -f keycloak_values.yaml --version=11.0.0
```

### Are you using any custom parameters or values?

```yaml
tls:
  enabled: true
  usePem: true
  existingSecret: app-auth-keycloak-tls
  keystorePassword: examplepassword
  truststorePassword: examplepassword
```

### What is the expected behavior?

Keycloak is listening on `https://0.0.0.0:8443` when TLS is enabled. 

There is no issue with the version `10.1.8` of the chart.

### What do you see instead?

```
2022-10-28 07:41:24,045 INFO [io.quarkus] (main) Keycloak 18.0.2 on JVM (powered by Quarkus 2.7.5.Final) started in 16.698s. Listening on: http://0.0.0.0:8080
```
