### ISSUE TITLE
[bitnami/keycloak] Ingress TLS secret is not created and TLS parameters not added

### ISSUE THREAD

**Issue by guerzon** [bitnami/charts#13239]
### Name and Version

bitnami/keycloak 10.1.6

### What steps will reproduce the bug?

Hi there,

I can't seem to get a simple Helm chart deployment to recognize an SSL certificate and use it for Ingress.

```bash
helm repo add bitnami https://charts.bitnami.com/bitnami
export NAMESPACE=newapp-test
helm template -n $NAMESPACE keycloak bitnami/keycloak -f values-keycloak-testing.yaml
```

### Are you using any custom parameters or values?

`values-keycloak-testing.yaml`:

```yaml
image:
  registry: docker.company.com
  repository: bitnami/keycloak
service:
  type: ClusterIP
  ports:
    http: 80
    https: 443
auth:
  adminUser: adminuser
  adminPassword: adminpassword
ingress:
  enabled: true
  ingressClassName: nginx
  hostname: "{{ .Release.Namespace }}-keycloak.company.com"
  tls: true
  secret:
    - name: "{{ .Release.Namespace }}-keycloak.company.com-tls"
      certificate: -----BEGIN CERTIFICATE-----
        <valid x509 cert>
        -----END CERTIFICATE-----
      key: -----BEGIN RSA PRIVATE KEY-----
        <valid private key>
        -----END RSA PRIVATE KEY-----
```

### What is the expected behavior?

Accoding to the [annotations](https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml#L576), this should create the secret and add the secret to the TLS ingress.

### What do you see instead?

No secret is created and `tls` is not added to the ingress:

```yaml
...
---
# Source: keycloak/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: "auditor-test"
  labels:
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-12.0.0
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: keycloak
  annotations:
spec:
  ingressClassName: "nginx"
  rules:
    - host: "newapp-test-keycloak.company.com"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: keycloak
                port:
                  name: http
```

### Additional information

Side question: Is there an easier way to add TLS certs to Ingress, for example if there is already an existing `tls` secret?
