### ISSUE TITLE
[bitnami/minio] How to use own custom secret defined under secretName in CertManager, in the ingress spec section in values.yaml

### ISSUE THREAD

**Issue by vyom-soft** [bitnami/charts#13272]
### Name and Version

bitnami/minio 11.10.13

### What steps will reproduce the bug?
One can have a running cert-manager with cluster-issuer configured to see this behaviour. 

Under the ingress section of  [minio-values.yaml](https://github.com/bitnami/charts/blob/main/bitnami/minio/values.yaml#L643)
 TLS certificates will be retrieved from a TLS secret with name: `{{- printf "%s-tls" .Values.ingress.hostname }}`   
This statement is not clear for secret defined under **secretName** in CertManager

I am not sure where to put the _secretName: secret-vomsoft-ca-tech_ in the values file for ingress where tls is true.

Below is my Cert-Manager resource definition.
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kvib-prod-ca-tech # the certificate & key pair is stored
  namespace: cert-manager
spec:
  isCA: true
  secretName: **kvib-prod-ca-tech** 
  dnsNames:
      - minio.kvinfosys.tech
```

### Are you using any custom parameters or values?

```yaml
ingress:
  enabled: true
  apiVersion: ""
  ingressClassName: "nginx"
  hostname: minio.kvinfosys.tech
  path: /
  pathType: ImplementationSpecific
  servicePort: minio-console

  annotations: {
    cert-manager.io/cluster-issuer: kvib-prod-ca-issuer,
    nginx.ingress.kubernetes.io/use-regex: "true"
  }
  ## @param ingress.tls Enable TLS configuration for the hostname defined at `ingress.hostname` parameter
  ## TLS certificates will be retrieved from a TLS secret with name: `{{- printf "%s-tls" .Values.ingress.hostname }}`
  ## You can:
  ##   - Use the `ingress.secrets` parameter to create this TLS secret
  ##   - Rely on cert-manager to create it by setting the corresponding annotations
  ##   - Rely on Helm to create self-signed certificates by setting `ingress.selfSigned=true`
  ##
  tls: true

  ## @param ingress.selfSigned Create a TLS secret for this ingress record using self-signed certificates generated by Helm
  ##
  selfSigned: false
  ## @param ingress.extraHosts The list of additional hostnames to be covered with this ingress record.
  ## Most likely the hostname above will be enough, but in the event more hosts are needed, this is an array
  ## e.g:
  ## extraHosts:
  ##   - name: minio.local
  ##     path: /
  ##
  extraHosts: []
  ## @param ingress.extraPaths Any additional paths that may need to be added to the ingress under the main host
  ## For example: The ALB ingress controller requires a special rule for handling SSL redirection.
  ## extraPaths:
  ## - path: /*
  ##   backend:
  ##     serviceName: ssl-redirect
  ##     servicePort: use-annotation
  ##
  extraPaths: []
  ## @param ingress.extraTls The tls configuration for additional hostnames to be covered with this ingress record.
  ## see: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
  ## e.g:
  ## extraTls:
  ## - hosts:
  ##     - minio.local
  ##   secretName: minio.local-tls
  ##
  extraTls: []
  ## @param ingress.secrets If you're providing your own certificates, please use this to add the certificates as secrets
  ## key and certificate are expected in PEM format
  ## name should line up with a secretName set further up
  ##
  ## If it is not set and you're using cert-manager, this is unneeded, as it will create a secret for you with valid certificates
  ## If it is not set and you're NOT using cert-manager either, self-signed certificates will be created valid for 365 days
  ## It is also possible to create and manage the certificates outside of this helm chart
  ## Please see README.md for more information
  ##
  ## Example
  ## secrets:
  ##   - name: minio.local-tls
  ##     key: ""
  ##     certificate: ""
  ##
  secrets: []
  ## @param ingress.extraRules Additional rules to be covered with this ingress record
  ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules
  ## e.g:
  ## extraRules:
  ## - host: example.local
  ##     http:
  ##       path: /
  ##       backend:
  ##         service:
  ##           name: example-svc
  ##           port:
  ##             name: http
  ##
  extraRules: []
```

### What is the expected behaviour?

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: "minio"
  labels:
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-11.10.13
    app.kubernetes.io/instance: minio
    app.kubernetes.io/managed-by: Helm
  annotations:
    cert-manager.io/cluster-issuer: kvib-prod-ca-issuer
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: "nginx"
  rules:
    - host: minio.kvinfosys.tech
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: minio
                port:
                  name: minio-console
  tls:
    - hosts:
        - minio.vyomsoft.tech
      secretName: kvib-prod-ca-tech
```

### What do you see instead?

```yaml
# Source: minio/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: "minio"
  labels:
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-11.10.13
    app.kubernetes.io/instance: minio
    app.kubernetes.io/managed-by: Helm
  annotations:
    cert-manager.io/cluster-issuer: kvib-prod-ca-issuer
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: "nginx"
  rules:
    - host: minio.kvinfosys.tech
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: minio
                port:
                  name: minio-console
  tls:
    - hosts:
        - minio.vyomsoft.tech
      secretName: minio.kvinfosys.tech-tls. # This is wrong generation after after helm install, 
                                           #I was expecting is secretName defined under certificate manager.
```

**Comment by rafariossaa** [comment]
Hi,
  I am not very sure of the issue, most probably I am missing something.
  
  When you use cert-manager, the cert manager's issuer (indicated in the annotations) will generate a certificate with the needed name.
  
  I used minikube and this is what I did:
  - Deployed ingress: `helm install myingress bitnami/nginx-ingress-controller`
  - Deployed cert-manager: `helm install mycerman bitnami/cert-manager --set installCRDs=true`
  - Create a selfsigned issuer:
```yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mycerts-issuer
spec:
  selfSigned: {}
```
  - Deploy minio using the default values.yaml and this user.yaml: (`helm install myminio -f values.yaml -f user.yaml .`)
```yaml
ingress:
  enabled: true
  apiVersion: ""
  ingressClassName: ""
  hostname: minio.local
  path: /
  pathType: ImplementationSpecific
  servicePort: minio-console
  annotations:
    cert-manager.io/issuer: "mycerts-issuer"
    nginx.ingress.kubernetes.io/use-regex: "true"
  tls: true
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraTls: []
  extraRules: []
 ```
   - Check the ingress creation, you could see it triggered a certification creation.
```bash
$ kubectl describe ingress myminio 
Name:             myminio
...
Events:
  Type    Reason             Age   From                       Message
  ----    ------             ----  ----                       -------
  Normal  CreateCertificate  106s  cert-manager-ingress-shim  Successfully created Certificate "minio.local-tls"

```
   - Check there is a certificate created:
   ```bash
$ kubectl get certificate
NAME              READY   SECRET            AGE
minio.local-tls   True    minio.local-tls   23s
```
   - If you edit the ingress object you could see it is using the certificate:
```
$ kubectl edit ingress myminio
...
spec:
  rules:
  - host: minio.local
    http:
      paths:
      - backend:
          service:
            name: myminio
            port:
              name: minio-console
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - minio.local
    secretName: minio.local-tls
```

**Comment by vyom-soft** [comment]
Many thanks for your insight. 

The case I am chasing is that under Certificate there is secretName. I have been using this secret name for other resources too, when defining the ingress with tls.
So I was thinking to use here also. Am I wrong in my understanding ?

Here is the actual snippet. I hope am able to present my case

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/18686082/199977784-4c422db6-7500-4691-8636-c1607f90dc19.png">

After installing Minio 

 $ kubectl get certificate does not show the generated 
<img width="954" alt="image" src="https://user-images.githubusercontent.com/18686082/199976993-4edbd0a6-21bd-486d-999e-797b9f7b6f2e.png">

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, I am not sure what should happen when using a secret. My guess is that it should behave the same way. 
  Maybe you can rise this question to cert-manager forums, I think you could get a better answer there.

**Comment by vyom-soft** [comment]
Hello, Thank you for your insight. 
That is what I am not able to figure out. Where to provide the specific  secretName in given [values.yaml](https://github.com/bitnami/charts/blob/main/bitnami/minio/values.yaml#L643). 
 In a way I think the bitnami chart is forcing to use generated `<somesecret>-tls` ?. 

Here is one more view https://docs.giantswarm.io/advanced/tls-certificates/

**Comment by rafariossaa** [comment]
> In a way I think the bitnami chart is forcing to use generated <somesecret>-tls ?.
The secretname is indicated [here](https://github.com/bitnami/charts/blob/71f87af27adf8a009dd6b4ca565db8ad90460ac9/bitnami/minio/templates/ingress.yaml#L54), but you could use:
```
ingress:
  enabled: true
  apiVersion: ""
  ingressClassName: ""
  hostname: minio.local
  path: /
  pathType: ImplementationSpecific
  servicePort: minio-console
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  tls: true
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraTls:
   - hosts:
       - minio.local
     secretName: minio.local-tl
  extraRules: []
```
 and indicate the name of the cert you want for that host. However, take into account that this way the cert is not autogenerated by certmanager when deploying minio.
