### ISSUE TITLE
[bitnami/kafka] not able to provide additional labels on deployed resources kafka bitnami helm charts 

### ISSUE THREAD

**Issue by Deepanshu6dec** [bitnami/charts#13304]
### Name and Version

bitnami/kafka

### What steps will reproduce the bug?

I'm trying to provide additional labels on all deployed resources by using a Common parameter in Kafka helm charts
This is what I mention in my values.yaml 
```yaml
#Common parameters
clusterDomain: cluster.local

commonLabels:
   application: test
```
While deploying using the below command 

```
helm install kafka -f values.yaml bitnami/kafka
``` 

Resources deployed but checking the pods labels new label not added 

```console
$ kubectl get pod kafka-1 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: d9845295a183c5a8f79d386705e13b47af272600f564bdc9e04dedb053b04a4a
    cni.projectcalico.org/podIP: 10.244.135.99/32
    cni.projectcalico.org/podIPs: 10.244.135.99/32
  creationTimestamp: "2022-11-02T07:05:38Z"
  generateName: kafka-
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    controller-revision-hash: kafka-6c95b7dfb4
    helm.sh/chart: kafka-19.0.1
    statefulset.kubernetes.io/pod-name: kafka-1
```

New label also should available

### Are you using any custom parameters or values?
```yaml
#Common parameters
clusterDomain: cluster.local

commonLabels:
   application: test
```
### What is the expected behavior?

New labels not added 

### What do you see instead?
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: d9845295a183c5a8f79d386705e13b47af272600f564bdc9e04dedb053b04a4a
    cni.projectcalico.org/podIP: 10.244.135.99/32
    cni.projectcalico.org/podIPs: 10.244.135.99/32
  creationTimestamp: "2022-11-02T07:05:38Z"
  generateName: kafka-
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    controller-revision-hash: kafka-6c95b7dfb4
    helm.sh/chart: kafka-19.0.1
    statefulset.kubernetes.io/pod-name: kafka-1
```
