### ISSUE TITLE
Slow Startup time and no logs while trying to add imports during startup

### ISSUE THREAD

**Issue by dishi-github** [bitnami/charts#13328]
### Name and Version

bitnami/keycloak-config-cli

### What steps will reproduce the bug?

1. Create a helm install deployment with this URL `helm install my-release -f values-keycloak.yml bitnami/keycloak`
2. Add custom DB configurations (external DB - able to connect)
3. Default admin as user name and password (admin)
4. Use initContainer (custom docker image) to add providers at startup (Works fine most times, but the logs move very slowly, at times I have to restart and then the logs appear that a new Custom Provider is added) - This is an issue no 1 regarding the performance
5. The second issue is that I cannot import the realm at the startup. I am sharing my configuration below. I have tried several approaches from other blogs posts such as different environmental variables `KEYCLOAK_IMPORT` / `KEYCLOAK_EXTRA_ARGS` / `KEYCLOAK_CONFIGURATION` but none of it works because I do not see any logs with any of these variables.

```yaml
image:
    registry: docker.io
    repository: bitnami/keycloak-config-cli
    tag: 5.3.1-debian-11-r10

extraEnvVars:
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: admin
  - name: KEYCLOAK_EXTRA_ARGS
    value: "-Dkeycloak.import=/config/realm.json -Dkeycloak.profile.feature.upload_scripts=enabled"
  - name: KEYCLOAK_IMPORT
    value: "/config/realm.json"
    
  initContainers:
  - name: user-storage-spi
    image: gcr.io/firm-repo-project-id/XXX-user-provider:latest
    command: [ 'cp', 'XXX-user-provider.jar', '/jar/XXX-user-provider.jar' ] #
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: user-storage-spi
        mountPath: /jar
### @param extraVolumes Optionally specify extra list of additional volumes for Keycloak pods
###
extraVolumes: |
  - name: user-storage-spi
    emptyDir: {}
  - name: config
    configMap:
      name: keycloak-realm
      items:
       - key: "realm.json"
         path: "realm.json"
## @param extraVolumeMounts Optionally specify extra list of additional volumeMounts for Keycloak container(s)
##
extraVolumeMounts: |
  - name: user-storage-spi
    mountPath: /opt/bitnami/keycloak/providers/
  - name: config
    mountPath: "/config"
    readOnly: true  
    
 postgresql:
  enabled: false
  auth:
    username: bn_keycloak
    password: ""
    database: bitnami_keycloak
    existingSecret: ""
  architecture: standalone

externalDatabase:
  host: "host.minikube.internal"
  port: 5432
  user: bn_keycloak
  database: bitnami_keycloak
  password: ""
  existingSecret: ""
  existingSecretPasswordKey: ""
```

### What is the expected behavior?

1. The logs should move forward. 
2. The logs should give me an error if any of those configurations are invalid. 
3. If any environment variables are picked/ignored should be clearly shown in the logs, at least in the dev environment.

There is no way to figure out what's happening in the backend with the stalled logs.

### What do you see instead?

```
keycloak 05:28:50.37 DEBUG ==> Setting proxy to 'passthrough' in Keycloak configuration
keycloak 05:28:50.52 INFO  ==> ** keycloak setup finished! **

keycloak 05:28:50.63 INFO  ==> ** Starting keycloak **
Updating the configuration and installing your custom providers, if any. Please wait.
```

Logs are stalled here. Sometimes after the restart, it will show custom user storage provider is created but that's all. Anything regarding import?

### Additional information
```
kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.24.3

image.tag: 5.3.1-debian-11-r10

https://artifacthub.io/packages/helm/bitnami/keycloak/9.8.1

APPLICATION VERSION
18.0.2
```

**Comment by dishi-github** [comment]
Hi All, any updates on this one please?

**Comment by dishi-github** [comment]
I was able to fix this after several trials and errors. Stating the solution here for anyone coming by. I would like to add a note on logging though that if there is any error in your realm.json file, like some config, is missing like Provider, the logs just stall. So I had to start with a vanilla realm.json file and then slowly I added other components. It would be nice if logs were more vocal. 

```
extraEnvVars:
  - name: KEYCLOAK_EXTRA_ARGS
    value: "--import-realm"

extraVolumes: |
  - name: config
    configMap:
      name: keycloak-realm
      items:
        - key: "realm.json"
          path: "realm.json"


extraVolumeMounts: |
  - name: config
    mountPath: "/opt/bitnami/keycloak/data/import/"
    readOnly: true
```

PS - Speed fix: It was a cluster issue. Deleted minikube and started again.
