### ISSUE TITLE
Unable to configure Spark master as Reverse Proxy

### ISSUE THREAD

**Issue by sanchi2019** [bitnami/charts#13340]
### Name and Version

bitnami/spark CHART NAME: spark CHART VERSION: 6.3.8 APP VERSION: 3.3.0

### What steps will reproduce the bug?

Unable to configure Spark master as Reverse Proxy using the following config yml. Please advice.

```yaml
master:
  configOptions:
    -Dspark.ui.reverseProxy=true
    -Dspark.ui.reverseProxyUrl=http://spark.poc.com
worker:
  configOptions:
    -Dspark.ui.reverseProxy=true
    -Dspark.ui.reverseProxyUrl=http://spark.poc.com
ingress:
  enabled: true
  hostname: spark.poc.com
```
Additional config parameters set while installing the helm chart are:
- `service.type=LoadBalancer`

`SUBMIT_IP` was obtained using the following
```
export SUBMIT_IP=$(kubectl get --namespace <namespace> svc <service name>-o jsonpath="{.status.loadBalancer.ingress[0]['ip', 'hostname'] }")
```
Here is the output of 

```console
$ kubectl get services
NAME                            TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                       AGE
<name>-spark-master-svc   LoadBalancer   <cluster-ip>   <external-ip>   7077:31032/TCP,80:32181/TCP   117m
```
I tried to access the Spark UI using the URL http://<external-ip>:80. The URL is accessible, however, all the links to worker nodes as well as application logs seem to be private links. Is any additional config needed here?

### Are you using any custom parameters or values?

Additional config parameters set while installing the helm chart are:
- service.type=LoadBalancer

values.yml

```yaml
master:
  configOptions:
    -Dspark.ui.reverseProxy=true
    -Dspark.ui.reverseProxyUrl=http://spark.poc.com
worker:
  configOptions:
    -Dspark.ui.reverseProxy=true
    -Dspark.ui.reverseProxyUrl=http://spark.poc.com
ingress:
  enabled: true
  hostname: spark.poc.com
```

### What is the expected behavior?

Private application links as well as the links to the logs on the worker are accessible through the UI

### What do you see instead?

I tried to access the Spark UI using the URL http://<external-ip>:80. The URL is accessible, however, all the links to worker nodes as well as application logs seem to be private links. Is any additional config needed here?
