### ISSUE TITLE
[bitnami/solr] unable to mount /opt/bitnami/solr folder on local disk

### ISSUE THREAD

**Issue by abhishekgupta2205** [bitnami/charts#13347]
### Name and Version

bitnami/solr , latest

### What steps will reproduce the bug?

2) helm install solr bitnami/solr

### Are you using any custom parameters or values?

1) configured parameters for extra volume and volume mounts .
```
extraVolumes:
- name: opt-data-autocomplete
  hostPath:
    path: /data/opt-data/autocomplete

extraVolumeMounts:
- name: opt-data-autocomplete
  mountPath: /opt/bitnami/solr
```
2) pod securtiy and container security context has been changed to root .

### What is the expected behavior?

above container volume should be mounted to local disk and should be persisting.

### What do you see instead?

pod is not started . gives crashloopbackoff.

### Additional information

![Screenshot from 2022-11-04 12-50-24](https://user-images.githubusercontent.com/68244292/199917194-8edf4eab-a544-4229-8c89-730464cea387.png)
these are the logs obtained
