### ISSUE TITLE
[bitnami/redmine] Add tls parameter to SMTP configuration

### ISSUE THREAD

**Issue by NainzguL** [bitnami/charts#13357]
### Name and Version

bitnami/redmine 21.0.0

### What is the problem this feature will solve?

I would like to be able to write a configuration for SMTP with the tls parameter :

```
default:
  # Outgoing emails configuration
  # See the examples below and the Rails guide for more configuration options:
  # http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: <mail.server>
      port: "465"
      authentication: login
      user_name: <user@email>
      password: <password>
      domain: <domain>
      enable_starttls_auto: true
      tls: true
```

In the current version, I cannot to it

### What is the feature you are proposing to solve the problem?

Add this paramter to the env variables, like the others.

It also might be usefull to line up the configuration for SMTP to the documentation (or line up the doc to the code), because it's necessary to dig into the chart to understand how parameters works.

### What alternatives have you considered?

The only alternative I found was to edit manually the file, which is not a good idea for maintenability.
