### ISSUE TITLE
[bitnami/mongodb] Zombie mongosh processes after startup

### ISSUE THREAD

**Issue by simon-jouet** [bitnami/charts#13365]
### Name and Version

bitnami/mongodb 13.4.1

### What steps will reproduce the bug?

I deployed a single node (for the time being) mongodb replicaset. After a reboot of the server I SSH into the machine and get notified of zombie processes.

The zombie processes are only timestamped when the machine is starting and after that, I can see `mongosh` being executed by the mongodb container without problems.

### Are you using any custom parameters or values?

Very bare bone configuration 

```yaml
image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 6.0.2-debian-11-r11
  pullPolicy: IfNotPresent
  debug: false

architecture: replicaset

volumePermissions:
  enabled: false

persistence:
  enabled: true

replicaCount: 1

arbiter:
  enabled: false

auth:
  enabled: true
  existingSecret: mongodb
```

### What is the expected behavior?

No zombie processes

### What do you see instead?

When connecting over SSH in the banner message

```
  => There are 2 zombie processes.
```

Checking the processes

```console
$ sudo ps aux | grep 'Z'

USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
abc         8389  2.2  0.0      0     0 ?        Z    11:43   0:01 [mongosh mongodb] <defunct>
abc         8390  0.0  0.0      0     0 ?        Z    11:43   0:00 [grep] <defunct>
```

Checking the start time of the machine

```console
$ uptime -s
2022-11-05 11:42:29
```

### Additional information

Using `pstree -p` I can see that the zombie process is from the mongodb pod

```
           ├─containerd-shim(5888)─┬─mongod(5976)─┬─grep(8390)
           │                       │              ├─mongosh mongodb(8389)
           │                       │              ├─{mongod}(6228)
   [truncated]
```

**Comment by javsalgar** [comment]
Hi,

Could you add more details of the resources of the cluster? We are aware that mongosh has a significant performance impact (reported upstream).

**Comment by simon-jouet** [comment]
Hi @javsalgar,

Do you mean the compute/process resources of the nodes? If that's the case the load is extremely minimal as this is a brand new deployment (I have other clusters with older versions and much higher load without issues).

Anyway, the CPU usage is a few percent (2.7% right now) and the RAM usage is at 12%, the single node has 16GB of RAM and a 4 core E3-1230 v6 (OVH).

There are very few pods booting up with kubernetes, at the moment it's only calico for the network, cert-manager, ingress-nginx and harbor as well as obviously mongodb.

Best regards,
Simon

**Comment by aoterolorenzo** [comment]
After some research I found [this issue](https://jira.mongodb.org/browse/SERVER-43363) which seems a pretty close behaviour, reported in Mongodb's issue tracker:

```
"another user was running a dockerized instance of mongod on start-up and was prohibiting the service'd mongod from starting at boot-time"
```

Could this be related to your issue?

**Comment by ey3ball** [comment]
I'm seeing this too, it looks we get these defunct process because the liveness probe is so slow to respond that it ultimately gets killed.

The upstream issue mentioned by @javsalgar seems to be this one maybe ? https://jira.mongodb.org/browse/MONGOSH-1240

**Comment by ey3ball** [comment]
It seems that mongosh has been here a while and that anything remotely recent is affected (I tried going back to the 10.x series of this chart and mongodb 4.4.x)

For now the only "solution" (considering I don't plan on upgrading my hardware) is simply to disable the probes : 
```
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
```
This is obviously far from ideal, but after this change performance gets back to normal and there are no more defunct / zombie process created
