### ISSUE TITLE
[bitnami/redis-cluster]When cluster externalAccess enabled, no workload is created.

### ISSUE THREAD

**Issue by sniperking1234** [bitnami/charts#13375]
### Name and Version

bitnami/redis-cluster 8.2.5

### What steps will reproduce the bug?

helm install redis-cluster redis-cluster -f values.yaml -ncommon

### Are you using any custom parameters or values?

```
global:
  imageRegistry: ""
  storageClass: juicefs-sc
  redis:
    password: EP9qAkZ3sJ

image:
  repository: bitnami/redis-cluster
  tag: 7.0.5-debian-11-r9

persistence:
  size: 8Gi

service:
  nodePorts:
    redis: "31300"
  type: NodePort

cluster:
  externalAccess:
    enabled: true
```

### What is the expected behavior?

Create 6 loadbalancer services and redis workload.

### What do you see instead?

Only 6 loadbalancer services.
