### ISSUE TITLE
[bitnami/postgresql] Inconsistency in password and username environment variables

### ISSUE THREAD

**Issue by rharink** [bitnami/charts#13387]
### Name and Version

bitnami/postgresql 12.1.0

### What steps will reproduce the bug?

Install a helm-chart with bitnami/postgresql 12.1.0 as a dependency and connect to the database with a given password.

1. Install chart
2. Port forward to local machine
3. Try to log in: `psql --username postgres`

### Are you using any custom parameters or values?

```yaml
postgresql:
  auth:
    enablePostgresUser: true
    postgresPassword: MySuperSecretPassword
```

### What is the expected behavior?

That i'm able to log-in to the database

### What do you see instead?

 error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

### Additional information

I think the problem lies in the environment variables that are set:

```yaml
# In the Pod definition
...
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgres-password
          name: local-test-postgresql
...
```

In the documentation of the docker container (https://hub.docker.com/r/bitnami/postgresql)

```yaml
...
    environment:
      - POSTGRESQL_PASSWORD=password123
  ...
```

Shouldn't the variable be set as `POSTGRESQL_PASSWORD` not `POSTGRES_PASSWORD`?

**Comment by rharink** [comment]
Ok, so I tried to remove everything and stumbled upon the persistent volumes. These keep the password once it has been set. So I can indeed log in. The difference in environment variable names still remains but seems to work just fine.

**Comment by javsalgar** [comment]
Hi!

I'm afraid that the password settings are only configured on first boot, after that, we don't have logic in place to reconcile any change in the environment variable. We've evaluated this is in the past and saw that it would be very difficult to implement with innumerable corner cases.

**Comment by rharink** [comment]
Ok thanks for the information 👍

**Comment by ollyde** [comment]
When rebooting the the pool (shifting resources) it's now stuck with the error

```ERROR ==> The POSTGRESQL_PASSWORD environment variable is empty or not set.``` whatever we do.

Can't start the main Postgres instance 🙈

**Comment by ollyde** [comment]
The temp fix for anyone else is to use ```extraEnv```

```
extraEnv:
  - name: POSTGRESQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-postgresql
        key: password
```

But after setting this I get

`AttachVolume.Attach failed for volume "pvc-29382437-43f9-ad9a-ac62c08956dc" : rpc error: code = Internal desc = scaleway-sdk-go: http error 400 Bad Request: volumes not available: [756875b6-6e52-4234-45701b23a6cb]`
