### ISSUE TITLE
[bitnami/postgresql]: postgres password is not being set when applying pg_hba.conf from a configmap

### ISSUE THREAD

**Issue by fozcode** [bitnami/charts#13386]
### Name and Version

bitnami/postgresql 11.9.1

### What steps will reproduce the bug?

With this configmap the `postgres` user password is set correctly (from `postgres-password` in existing secret):

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
data:
#  pg_hba.conf: |-
#    # Allowed local connections
#    local  all        all                     scram-sha-256
#    host   all        all       127.0.0.1/32  scram-sha-256
#    host   all        all       ::1/128       scram-sha-256
```

With this configmap the `postgres` user password is not set. Postgres reports `User "postgres" has no password assigned.`.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
data:
  pg_hba.conf: |-
    # Allowed local connections
    local  all        all                     scram-sha-256
    host   all        all       127.0.0.1/32  scram-sha-256
    host   all        all       ::1/128       scram-sha-256
```

I also have a `postgresql.conf` in the configmap but I've omitted that as it's huge.

### Are you using any custom parameters or values?

Values.yaml has:

```
postgresql:
  primary:
    existingConfigmap: "postgresql-configmap"
```

### What is the expected behavior?

This is the setup output when there is no custom pg_hba.conf:

```
postgresql 16:19:37.59 INFO  ==> ** Starting PostgreSQL setup **
postgresql 16:19:37.61 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 16:19:37.62 INFO  ==> Loading custom pre-init scripts...
postgresql 16:19:37.62 INFO  ==> Initializing PostgreSQL database...
postgresql 16:19:37.63 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql 16:19:37.64 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 16:19:37.64 INFO  ==> Generating local authentication configuration
postgresql 16:19:38.60 INFO  ==> Starting PostgreSQL in background...
postgresql 16:19:38.72 INFO  ==> Changing password of postgres
postgresql 16:19:38.74 INFO  ==> Configuring synchronous_replication
postgresql 16:19:38.74 INFO  ==> Loading custom scripts...
postgresql 16:19:38.75 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql 16:19:38.85 INFO  ==> ** PostgreSQL setup finished! **
```

### What do you see instead?

After deleting the Stateful Set and the PVC, this is the setup output when the custom pg_hba.conf is enabled:

```
postgresql 16:24:39.00 INFO  ==> ** Starting PostgreSQL setup **
postgresql 16:24:39.02 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 16:24:39.03 INFO  ==> Loading custom pre-init scripts...
postgresql 16:24:39.03 INFO  ==> Initializing PostgreSQL database...
postgresql 16:24:39.04 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql 16:24:39.04 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql 16:24:39.06 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 16:24:39.07 INFO  ==> Loading custom scripts...
postgresql 16:24:39.07 INFO  ==> ** PostgreSQL setup finished! **
```

It is missing the steps for:

* Generating local authentication configuration
* Starting PostgreSQL in background...
* Changing password of postgres
* Stopping PostgreSQL...

which I would still expect to happen. Perhaps a clue here is that it says `Deploying PostgreSQL with persisted data...` which I would not expect on first launch after the previous PVC has been deleted.

**Comment by waschk** [comment]
I had a similar issue. It's normal that the postgres user is created without a password first. If there is no custom pg_hba.conf the setup script will create one with `trust` for each connection. After setting the passwords the pg_hba.conf is modified to replace `trust` with `md5`.

You can try
```
data:
  pg_hba.conf: |
    local  all        postgres                trust
    local  all        all                     scram-sha-256
    host   all        all       127.0.0.1/32  scram-sha-256
    host   all        all       ::1/128       scram-sha-256
```

That one should work because postgres can login without password to set the password. I don't think it's currently possible to specify a pg_hba.conf through a configmap without a `trust` entry to allow the setup to run. You should be able to modify the configmap afterwards to remove the `trust` entry and reload the config.

I was able to work around it in my setup by replacing
```
postgresql:
  primary:
    pgHbaConfiguration: |
      # ----------------------
      # |   My pg_hba.conf   |
      # ----------------------
```
with
```
postgresql:
  primary:
    initdb:
      scripts:
        pgHbaConfiguration.sh: |
          #/bin/bash
          cat << EOF > "$POSTGRESQL_PGHBA_FILE"
          # ----------------------
          # |   My pg_hba.conf   |
          # ----------------------
          EOF
          pg_ctl reload
```

This looks to me like a bug in the container and not in the helm chart though.
