### ISSUE TITLE
[bitnami/spring-cloud-data-flow] Unable to set SPRING_APPLICATION_JSON env var

### ISSUE THREAD

**Issue by juanpablo-santos** [bitnami/charts#13383]
### Name and Version

bitnami/spring-cloud-data-flow 2.9.6

### What steps will reproduce the bug?

As per [Using SPRING_APPLICATION_JSON](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_using_code_spring_application_json_code), you can use a `SPRING_APPLICATION_JSON` environment variable to set Data Flow server properties.

However when setting on a values.yaml file something like:
```
server:
[...]
  extraEnvVars:
    - name: SPRING_APPLICATION_JSON
      value: { "maven": { "remote-repositories":...
```

the resulting template yields something like:
```
[...]
            - name: SPRING_APPLICATION_JSON
              value: "map[maven:map[remote-repositories:map[...
[...]
```

### Are you using any custom parameters or values?

on a `values.yaml` file:
```
server:
[...]
  extraEnvVars:
    - name: SPRING_APPLICATION_JSON
      value: { "maven": { "remote-repositories":...
```
(would be nice to pass this var through an exisiting env variable, like `--set server.extraVars[0].SPRING_APPLICATION_JSON=$MY_ENV_VAR` but haven't found a way to do so)

### What is the expected behavior?

```
[...]
            - name: SPRING_APPLICATION_JSON
              value: {"maven":{"remote-repositories":{...
```

### What do you see instead?

```
[...]
            - name: SPRING_APPLICATION_JSON
              value: "map[maven:map[remote-repositories:map[...
[...]
```

### Additional information

changing range on line 172 on `deployment.yaml` to 

```
            {{- range $key, $value := .Values.server.extraEnvVars }}
            - name: {{ $value.name }}
              {{- if eq $value.name "SPRING_APPLICATION_JSON" }}
              value: {{ $value.value | toJson | quote }}
              {{- else }}
              value: "{{ $value.value }}"
              {{- end }}
            {{- end }}
```

seems enough to fix this. Another workaorund to manually patch the file is to extend bitnami's SCDF Docker image and add the aforementioned variable
