### ISSUE TITLE
[bitnami/minio] Why are helm charts (minio) not versioned properly?

### ISSUE THREAD

**Issue by Quasarman** [bitnami/charts#13399]
### Name and Version

11.6.7

### What steps will reproduce the bug?

I was using version 11.6.7 for quite some time now and suddenly from one day to the other my config is no longer valid. It gives an error regarding the `ingress.tls` and `apiIngress.tls` not being a container but a boolean value. Until now this config worked without any problems:

(I am using devspace to build the deployments)
```yaml
name: minio
    helm:
      chart:
        name: minio
        version: 11.6.7
        repo: https://charts.bitnami.com/bitnami
      wait: true
      values:
        defaultBuckets: <name>
        podLabels:
          app: cdn
        auth:
          rootUser: <user>
          rootPassword: <password>
        apiIngress:
          enabled: true
          hostname: ${DOMAIN_SUB_CDN}.${DOMAIN}
          tls:
            enabled: true
            existingSecret: dev-secret
        ingress:
          enabled: true
          hostname: ui.${DOMAIN_SUB_CDN}.${DOMAIN}
          tls:
            enabled: true
            existingSecret: dev-secret
        provisioning:
          enabled: true
          users:
            - username: ${S3_KEY_ID}
              password: ${S3_ACCESS_KEY}
              policies:
                - readwrite
        persistence:
          enabled: false
```

I did not change the version or anything else. It just stopped working with the existing config that worked just fine yesterday. So my question is if there are config changes why am I forced to upgrade a versioned config to a newer schema?

### What is the expected behavior?

My config to be valid if i dont change anything and if it was valid before for the same version.

### What do you see instead?

An invalid config for some reason? Is there something broken with the version handling?

**Comment by javsalgar** [comment]
Hi,

Could you share the exact error helm returns?

**Comment by Quasarman** [comment]
Sure thing:

![edited](https://user-images.githubusercontent.com/30523269/200552847-84f60381-12d0-4010-b80c-13c178834a99.jpeg)


when I adapt the config to this.
```yaml
...
apiIngress:
  enabled: true
  hostname: ${DOMAIN_SUB_CDN}.${DOMAIN}
  tls: true
ingress:
  enabled: true
  hostname: ui.${DOMAIN_SUB_CDN}.${DOMAIN}
  tls: true
tls:
  enabled: true
  existingSecret: dev-secret
...
```

It fixes this issue but I get another one regarding the certificate that also did not occur before. Thats why I raised this issue since IMHO leaving the version and everything else unchanged should not just break my builds.

I would very much like to leave the config as is and to not have to change the version or anything.
