### ISSUE TITLE
[bitnami/argo-cd]: "Unable to load data: configmap "argocd-tls-certs-cm" not found"

### ISSUE THREAD

**Issue by aurelioacn** [bitnami/charts#13400]
### Name and Version

bitnami/argocd

### What steps will reproduce the bug?

Deploy bitnami/argocd helm chart without set .Values.config.tlsCerts.
Application is deployed successfully.
From ArgoCD interface navigate to Settings -> Certificates.

### Are you using any custom parameters or values?
```yaml
controller:
    podSecurityContext:
        enabled: false
    containerSecurityContext:
        enabled: false
        
server:
    insecure: true
    podSecurityContext:
        enabled: false
    containerSecurityContext:
        enabled: false

repoServer:
    podSecurityContext:
        enabled: false
    containerSecurityContext:
        enabled: false

config:
    secret:
        argocdServerAdminPassword: "1234ABCD"
    extraKnownHosts: |  
           github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=        

redis:
    master:
        podSecurityContext:
            enabled: false
        containerSecurityContext:
            enabled: false
```
### What is the expected behavior?

Since config.tlsCerts parameter is not mandatory the deployed ArgoCD should not complain about configmap "argocd-tls-certs-cm" not begin created and users should be able to add certificates from the interface.

### What do you see instead?

Pop up "Unable to load data: configmap "argocd-tls-certs-cm" not found" and user cannot add manually any certificates because this ConfigMap is not created.

### Additional information

the argocd-tls-certs-cm is not created because of this condition: 
https://github.com/bitnami/charts/blob/main/bitnami/argo-cd/templates/tls-certs-cm.yaml#L1

If I add the parameter config.tlsCerts a dummy certificate, the argocd-tls-certs-cm is created as expected and there are no issues and the users can add certificates from interface with no problem.
