### ISSUE TITLE
Issue setting inpress on google cloud kubernetes Mongodb

### ISSUE THREAD

**Issue by phuc-but** [bitnami/charts#1342]
Try to set inpress for install mongodb via Helm.

I'm no idea with the default setting why I just reuse this:

```
ingress:
  enabled: true

  certManager: false

  annotations:
    kubernetes.io/ingress.class: nginx

  hosts:
  - name: mongodb.local
    path: /
```

Error return:

```
Error: release db-stg-release failed: Ingress.extensions "db-stg-release-mongodb" is invalid: spec.rules[0].host: Invalid value: "map[name:mongodb.local path:/]": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric ch
aracter (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

If you have any else example to make it more clear. Please send it to me.
Thanks.

**Comment by tompizmor** [comment]
Hello @phuc-but,

Can you let me know which version of the MongoDB chart are you deploying? I tried with the latest one but I don't get that error.

**Comment by phuc-but** [comment]
Hi @tompizmor,

I 'm using this chart:
https://github.com/bitnami/charts/tree/master/upstreamed/mongodb

Thank you very much.
Best regards.

**Comment by alemorcuq** [comment]
Hi, @phuc-but.

This works for me too. I'm using this Ingress configuration in my `values.yaml`:

```yaml
ingress:
  ## Set to true to enable ingress record generation
  enabled: true

  ## Set this to true in order to add the corresponding annotations for cert-manager
  certManager: false

  ## Ingress annotations done as key:value pairs
  ## For a full list of possible ingress annotations, please see
  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
  ##
  ## If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
  ## If certManager is set to true, annotation kubernetes.io/tls-acme: "true" will automatically be set
  annotations:
    kubernetes.io/ingress.class: nginx

  ## The list of hostnames to be covered with this ingress record.
  ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
  hosts:
  - name: mongodb.local
    path: /

  ## The tls configuration for the ingress
  ## see: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
  tls:
  - hosts:
      - mongodb.local
    secretName: mongodb.local-tls

  secrets:
```

```console
$ helm install .
[...]
$ kubectl get ingress mean-lizard-mongodb -o yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  creationTimestamp: 2019-08-13T11:14:25Z
  generation: 1
  labels:
    app: mongodb
    chart: mongodb-7.1.1
    heritage: Tiller
    release: mean-lizard
  name: mean-lizard-mongodb
  namespace: default
  resourceVersion: "159215160"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/mean-lizard-mongodb
  uid: 82408938-bdbb-11e9-9cd9-42010a9600d6
spec:
  rules:
  - host: mongodb.local
    http:
      paths:
      - backend:
          serviceName: mean-lizard-mongodb
          servicePort: mongodb
        path: /
  tls:
  - hosts:
    - mongodb.local
    secretName: mongodb.local-tls
status:
  loadBalancer: {}
```

How are you deploying it? Can you share your `values.yaml` (with any sensible data stripped)?

Regards,
Alejandro
