### ISSUE TITLE
node-exporter: wrong use of extraArgs templating

### ISSUE THREAD

**Issue by s0uky** [bitnami/charts#13479]
### Name and Version

bitnami/node-exporter:3.2.3

### What steps will reproduce the bug?

extraArgs values are templated as key:value, but should be templated by toYaml function

### Are you using any custom parameters or values?

In values.yaml I have defined:

```yaml
node-exporter:
   extraArgs:
   - --collector.ntp
   - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+)($|/)
   - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|cgroup|cgroup2|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs|tmpfs|nsfs|shm)$
 ```

### What is the expected behavior?

In daemonset template should be: 

```yaml
{{- if .Values.extraArgs }}
{{ toYaml .Values.extraArgs | indent 12 }}
{{- end }}
```

intead of
```yaml
{{- range $key, $value := .Values.extraArgs }}
{{- if $value }}
- --{{ $key }}={{ $value }}
{{- else }}
- --{{ $key }}
{{- end }}
```

### What do you see instead?

Templating as key:values looks like this and that is not valid: 

```yaml
containers:
      - name: node-exporter
        args:
        - --0=--collector.ntp
        - --1=--collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+)($|/)
        - --2=--collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|cgroup|cgroup2|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs|tmpfs|nsfs|shm)$
```
