### ISSUE TITLE
[bitnami/redis] auth.existingSecret cannot be templated

### ISSUE THREAD

**Issue by OvervCW** [bitnami/charts#13503]
### Name and Version

bitnami/redis 17.3.9

### What is the problem this feature will solve?

I would like to create a secret with a password for Redis that is named after my Helm release like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-chart.fullname" . }}-redis-auth
```

So, I would like to reference the secret like this in `values.yaml`:

```yaml
redis:
  auth:
    existingSecret: '{{ include "my-chart.fullname" . }}-auth'
```

However, the chart currently doesn't allow this value to be templated, so it'll raise an error about the secret name being invalid.

### What is the feature you are proposing to solve the problem?

Allow `existingSecret` to be templated using `tpl`.

### What alternatives have you considered?

I currently work around this by specifying the `existingSecret` value on the Helm commandline using `--set`, but I really want to be able to do it in `values.yaml` instead.
