### ISSUE TITLE
[bitnami/mongodb] tls.extraDnsNames cannot include variable

### ISSUE THREAD

**Issue by tbnguyen1407** [bitnami/charts#13519]
### Name and Version

bitnami/mongodb 13.4.2

### What steps will reproduce the bug?

1. Deploy with TLS and extra DNS names containing variable

### Are you using any custom parameters or values?

```
tls:
  enabled: true
  existingSecret: mongodb-tls-secret
  extraDnsNames:
    - mongodb.$MY_POD_NAMESPACE  ## not working
    - mongodb.ns-db              ## working
```

### What is the expected behavior?

Successful cert generated with proper SANs.

### What do you see instead?

```
generate-tls-certs Generating RSA private key, 2048 bit long modulus (2 primes)
generate-tls-certs ........+++++
generate-tls-certs ..................+++++
generate-tls-certs e is 65537 (0x010001)
generate-tls-certs req: Error on line 16 of config file "/certs/openssl.cnf"
generate-tls-certs 139822151427392:error:0E065068:configuration file routines:str_copy:variable has no value:../crypto/conf/conf_def.c:638:line 16
generate-tls-certs x509: Error on line 16 of config file "/certs/openssl.cnf"
generate-tls-certs rm: cannot remove '/certs/mongo.csr': No such file or directory
generate-tls-certs cat: /certs/mongo.crt: No such file or directory
```
