### ISSUE TITLE
Disable keycloak headless service http port

### ISSUE THREAD

**Issue by afhtan** [bitnami/charts#13523]
### Name and Version

bitnami/keycloak 10.1.4

### What steps will reproduce the bug?

Deploy keycloak using the custom values below

### Are you using any custom parameters or values?
```
service.http.enabled=false
```
### What is the expected behavior?

The headless keycloak service does not expose http port like the keycloak service

### What do you see instead?

port http is still enabled on keycloak headless service

### Additional information

The headless-service.yaml file should look like the following at line 18:

```yaml
   {{- if .Values.service.http.enabled }}
   - name: http
      port: {{ coalesce .Values.service.ports.http .Values.service.port }}
      protocol: TCP
      targetPort: http
  {{- end }}
```
