### ISSUE TITLE
[bitnami/mongodb]: External Access + TLS does not work.

### ISSUE THREAD

**Issue by pryhodkin** [bitnami/charts#13522]
### Name and Version

bitnami/mongodb 13.4.2

### What steps will reproduce the bug?

Install chart with customized values for and monitor the bahavior.

### Are you using any custom parameters or values?

```
global:
  imageRegistry: docker.io

serviceAccount:
  create: true
auth:
  enabled: true
pdb:
  create: true
metrics: 
  enabled: true
rbac:
  create: true
arbiter:
  enabled: false


nodeSelector:
  env: dev
  app: mongodb
resources:
  requests:
    cpu: 1.5
    memory: 4.5Gi
  limits:
    cpu: 1.5
    memory: 4.5Gi
persistence:
  enabled: true
  size: 20Gi

architecture: replicaset
replicaCount: 3

externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true           
  service:
    type: LoadBalancer 

tls:
  enabled: true
  existingSecret: "custom-certs"
  extraDnsNames:
    - "*.my-namespace"
```
### What is the expected behavior?

3 mongodb replicas is up and I am able to connect via forwarding mongodb-headless service.

### What do you see instead?

One replica is up, but it has a bunch of errors in logs and I am not able to connect to it.

MongoServerSelectionError: Hostname/IP does not match certificate's altnames: IP: <external IP of 1st replica> is not in the cert's list: 10.240.0.6, 127.0.0.1

MongoServerError: No host described in new configuration with {version: 1, term: 0} for replica set rs0 maps to this node

The second replica can not rise, because of metrics container failes due to connectivity problems to mongodb.
```
level=error msg="Cannot connect to MongoDB: cannot connect to MongoDB: connection() error occured during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism \"SCRAM-SHA-1\": (AuthenticationFailed) Authentication failed."
```
