### ISSUE TITLE
[bitnami/argo-cd] ArgoCD login with Google Workspace users: Connect using Dex unstable

### ISSUE THREAD

**Issue by nxhuy-github** [bitnami/charts#13549]
### Name and Version

argo-cd-5.13.8

### What steps will reproduce the bug?

1. I follow step-by-step in this [article](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/google/#openid-connect-using-dex) to setup the login with Google accounts
2. Everything is fine, I can see the button 
![image](https://user-images.githubusercontent.com/23189942/202223752-b19952a9-1704-4cdc-99d0-29f1ed3833e7.png)
3. Then when I click in the button LOG IN VIA GOOGLE, I get an error
![image](https://user-images.githubusercontent.com/23189942/202224147-fc2d9daf-2287-4106-b51b-37843f1a0912.png)
4. But if I **wait like 7 or 10min, everything get back to normal**, I could login with my Google accounts. I DO NOT DO ANYTHING except waiting and
![image](https://user-images.githubusercontent.com/23189942/202227460-aef3e932-d825-4d9f-b09b-f8d6d61514f2.png)

### Are you using any custom parameters or values?

My settting

```
# ./argocd/Chart.yaml
apiVersion: v2
name: argo-cd
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 5.13.8
    repository: https://argoproj.github.io/argo-helm
```
```
# ./argocd/values.yaml
argo-cd:
  dex:
    enabled: true
  server:
    extraArgs:
      - --insecure
  configs:
    cm:
      url: https://argocd.kube-cicd.xxxxxxxxxxxxx.com
      dex.config: |
        connectors:
        - config:
            redirectURI: https://argocd.kube-cicd.xxxxxxxxxxxxx.com/api/dex/callback
            issuer: https://accounts.google.com
            clientID: AAAAAAAABBBBBBBCCCCCC.apps.googleusercontent.com
            clientSecret: AAAAAAAABBBBBBBCCCCCC
          type: oidc
          id: google
          name: Google
    repositories:
      argo-helm:
        type: helm
        name: argo-cd
        url: https://argoproj.github.io/argo-helm
```

Command I used to install ArgoCD 
```
helm upgrade --install argocd ./argocd --namespace=my-namespace -f ./argocd/values.yaml
```

For OAuth consent screen and OAuth Client ID, I did exactly what is in this [article](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/google/#openid-connect-using-dex)

### What do you see instead?

This is what I get when I click in the login button:

![image](https://user-images.githubusercontent.com/23189942/202224147-fc2d9daf-2287-4106-b51b-37843f1a0912.png)

### Additional information

I don't understand why there is a double slash (see my picture please) `//api/dex`, I don't know if this is a good sign ?!?

![image](https://user-images.githubusercontent.com/23189942/202224147-fc2d9daf-2287-4106-b51b-37843f1a0912.png)
