### ISSUE TITLE
Moodle file pod restore on AKS failing with : Error: Database connection failed

### ISSUE THREAD

**Issue by ojordano** [bitnami/charts#13556]
### Name and Version

Bitnami/moodle+mariadb v4.0.1, Package 14.1.9

### What steps will reproduce the bug?

I am running a **Bitnami/moodle+mariadb v4.0.1, Package 14.1.9** on **Azure AKS** in a specific production namespace.

I now want to test a restore in case something happens and i need to do a new clean install

I backed up the attached disk, did a restore and gave them another name. I now created a test namespace and attached disks to it through pv & pvc for the pods, which went well.

When I now try to deploy the app in the test namespace with the prod values, the mariadb pod is up & running well with no error, but the moodle pod fails with the below error:
```
**!!! <p>Error: Database connection failed</p>**
<p>It is possible that the database is overloaded or otherwise not running properly.</p>

**<p>The site administrator should also check that the database details have been correctly specified in config.php</p> !!!**
```
I have checked the secrets deployed, and database host from environment variables and they are all good.

Can you please advise and help on this please??

### Are you using any custom parameters or values?

**Values used**
```yaml
allowEmptyPassword: false
containerSecurityContext:
  enabled: false
extraEnvVars:
  - name: PHP_MAX_INPUT_VARS
    value: '5000'
  - name: PHP_POST_MAX_SIZE
    value: 500m
  - name: PHP_UPLOAD_MAX_FILESIZE
    value: 500m
image:
  debug: true
ingress:
  annotations:
    acme.cert-manager.io/http01-edit-in-place: 'true'
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.org/client-max-body-size: 500m
  enabled: true
  hostname: <em>_host_url_</em>
  ingressClassName: <em>_class_name</em>
  tls: true
livenessProbe:
  enabled: false
mariadb:
  auth:
    password: ************************
    rootPassword: *********************
  primary:
    persistence:
      existingClaim: <em>_pvc_claim_name</em>
moodlePassword: ********************
moodleSkipInstall: true
persistence:
  existingClaim: <em>_pvc_claim_name</em>
podSecurityContext:
  enabled: false
readinessProbe:
  enabled: false
service:
  type: ClusterIP
```

### What is the expected behavior?

Moodle pod running and url accessible.
A describe on the pod show that right database information are well acknowledged

### What do you see instead?

The moodle pod failing with below error

```
←[38;5;6mmoodle ←[38;5;5m08:41:51.83 ←[0m←[38;5;2mINFO ←[0m ==> Restoring persisted Moodle installation
←[38;5;6mmoodle ←[38;5;5m08:41:54.09 ←[0m←[38;5;2mINFO ←[0m ==> Trying to connect to the database server
←[38;5;6mmoodle ←[38;5;5m08:41:54.10 ←[0m←[38;5;5mDEBUG←[0m ==> Getting $CFG->dbtype from Moodle configuration
←[38;5;6mmoodle ←[38;5;5m08:41:54.11 ←[0m←[38;5;5mDEBUG←[0m ==> Getting $CFG->dbhost from Moodle configuration
←[38;5;6mmoodle ←[38;5;5m08:41:54.12 ←[0m←[38;5;5mDEBUG←[0m ==> Getting 'dbport' from Moodle configuration
←[38;5;6mmoodle ←[38;5;5m08:41:54.13 ←[0m←[38;5;5mDEBUG←[0m ==> Getting $CFG->dbname from Moodle configuration
←[38;5;6mmoodle ←[38;5;5m08:41:54.14 ←[0m←[38;5;5mDEBUG←[0m ==> Getting $CFG->dbuser from Moodle configuration
←[38;5;6mmoodle ←[38;5;5m08:41:54.15 ←[0m←[38;5;5mDEBUG←[0m ==> Getting $CFG->dbpass from Moodle configuration
←[38;5;6mmoodle ←[38;5;5m08:41:54.16 ←[0m←[38;5;2mINFO ←[0m ==> Running database upgrade

<p>!!!Error: Database connection failed</p>
<p>It is possible that the database is overloaded or otherwise not running properly.</p>
<p>The site administrator should also check that the database details have been correctly specified in config.php !!!</p> 
```
