### ISSUE TITLE
[bitnami/redis] Remove warning when override nodeSelector value

### ISSUE THREAD

**Issue by Yhasmina** [bitnami/charts#13567]
### Name and Version

bitnami/redis-cluster:8.2.7

### What steps will reproduce the bug?

Appear a warning when override the nodeSelector value.

1. Download bitnami/redis 8.2.7
2. Use custom Helm Chart values file
3. Run 
```bash
helm template redis ./redis/ -f redis-values.yaml > redis-manifest.yaml
```
4. See Helm warning

### Are you using any custom parameters or values?

```yaml
global:
  nodeSelector:
    label: value
redis-cluster:
  redis:
    nodeSelector: "{{ (.Values.global.nodeSelector | toYaml) | default dict }}"
```

### What is the expected behavior?

The warning shouldn't appear

### What do you see instead?

```bash
coalesce.go:220: warning: cannot overwrite table with non table for redis-cluster.redis.nodeSelector (map[])
```

### Additional information

Helm Version

```bash
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}
```
