### ISSUE TITLE
[bitnami/thanos] PrometheusRules not valid denied by admissionwebhook

### ISSUE THREAD

**Issue by Moep90** [bitnami/charts#13578]
### Name and Version

bitnami/thanos 11.6.0

### What steps will reproduce the bug?

1. install latest kube-prometheus-stack with thanos sidecar
2. install thanos latest version
3. enabled the flags `metric.prometheusRule.enabled` etc.
4. kubectl apply --recursive -f thanos.yml
5. See error below

### Are you using any custom parameters or values?

```yaml
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
  prometheusRule:
    enabled: true
    default:
      create: true
```

### What is the expected behavior?

The PrometheusRules should be applied with no issues.

### What do you see instead?

For every Rule I get something similar
```yaml
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"monitoring.coreos.com/v1\",\"kind\":\"PrometheusRule\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/instance\":\"thanos\",\"app.kubernetes.io/managed-by\":\"Helm\",\"app.kubernetes.io/name\":\"thanos\",\"helm.sh/chart\":\"thanos-11.6.0\"},\"name\":\"thanos\",\"namespace\":\"monitoring\"},\"spec\":{\"groups\":[{\"name\":\"thanos-compact\",\"rules\":[{\"alert\":\"ThanosCompactMultipleRunning\",\"annotations\":{\"description\":\"No more than one Thanos Compact instance should be running at once. There are {{ \\\\$value }} instances running.\",\"runbook_url\":\"https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompactmultiplerunning\",\"summary\":\"Thanos Compact has multiple instances running.\"},\"expr\":\"sum by (job) (up{job=~\\\".*thanos-compact.*\\\"}) \\u003e 1\",\"for\":\"5m\",\"labels\":{\"severity\":\"warning\"}},{\"alert\":\"ThanosCompactHalted\",\"annotations\":{\"description\":\"Thanos Compact {{ \\\\$labels.job }} has failed to run and now is halted.\",\"runbook_url\":\"https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompacthalted\",\"summary\":\"Thanos Compact has failed to run and is now halted.\"},\"expr\":\"thanos_compact_halted{job=~\\\".*thanos-compact.*\\\"} == 1\",\"for\":\"5m\",\"labels\":{\"severity\":\"warning\"}},{\"alert\":\"ThanosCompactHighCompactionFailures\",\"annotations\":{\"description\":\"Thanos Compact {{ \\\\$labels.job }} is failing to execute {{ $value | humanize }}% of compactions.\",\"runbook_url\":\"https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompacthighcompactionfailures\",\"summary\":\"Thanos Compact is failing to execute compactions.\"},\"expr\":\"(\\n  sum by (job) (rate(thanos_compact_group_compactions_failures_total{job=~\\\".*thanos-compact.*\\\"}[5m]))\\n/\\n  sum by (job) (rate(thanos_compact_group_compactions_total{job=~\\\".*thanos-compact.*\\\"}[5m]))\\n* 100 \\u003e 5\\n)\\n\",\"for\":\"15m\",\"labels\":{\"severity\":\"warning\"}},{\"alert\":\"ThanosCompactBucketHighOperationFailures\",\"annotations\":{\"description\":\"Thanos Compact {{ \\\\$labels.job }} Bucket is failing to execute {{ \\\\$value | humanize }}% of operations.\",\"runbook_url\":\"https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompactbuckethighoperationfailures\",\"summary\":\"Thanos Compact Bucket is having a high number of operation failures.\"},\"expr\":\"(\\n  sum by (job) (rate(thanos_objstore_bucket_operation_failures_total{job=~\\\".*thanos-compact.*\\\"}[5m]))\\n/\\n  sum by (job) (rate(thanos_objstore_bucket_operations_total{job=~\\\".*thanos-compact.*\\\"}[5m]))\\n* 100 \\u003e 5\\n)\\n\",\"for\":\"15m\",\"labels\":{\"severity\":\"warning\"}},{\"alert\":\"ThanosCompactHasNotRun\",\"annotations\":{\"description\":\"Thanos Compact {{ \\\\$labels.job }} has not uploaded anything for 24 hours.\",\"runbook_url\":\"https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompacthasnotrun\",\"summary\":\"Thanos Compact has not uploaded anything for last 24 hours.\"},\"expr\":\"(time() - max by (job) (max_over_time(thanos_objstore_bucket_last_successful_upload_time{job=~\\\".*thanos-compact.*\\\"}[24h]))) / 60 / 60 \\u003e 24\",\"labels\":{\"severity\":\"warning\"}}]}]}}\n"}},"spec":{"groups":[{"name":"thanos-compact","rules":[{"alert":"ThanosCompactMultipleRunning","annotations":{"description":"No more than one Thanos Compact instance should be running at once. There are {{ \\$value }} instances running.","runbook_url":"https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompactmultiplerunning","summary":"Thanos Compact has multiple instances running."},"expr":"sum by (job) (up{job=~\".*thanos-compact.*\"}) \u003e 1","for":"5m","labels":{"severity":"warning"}},{"alert":"ThanosCompactHalted","annotations":{"description":"Thanos Compact {{ \\$labels.job }} has failed to run and now is halted.","runbook_url":"https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompacthalted","summary":"Thanos Compact has failed to run and is now halted."},"expr":"thanos_compact_halted{job=~\".*thanos-compact.*\"} == 1","for":"5m","labels":{"severity":"warning"}},{"alert":"ThanosCompactHighCompactionFailures","annotations":{"description":"Thanos Compact {{ \\$labels.job }} is failing to execute {{ $value | humanize }}% of compactions.","runbook_url":"https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompacthighcompactionfailures","summary":"Thanos Compact is failing to execute compactions."},"expr":"(\n  sum by (job) (rate(thanos_compact_group_compactions_failures_total{job=~\".*thanos-compact.*\"}[5m]))\n/\n  sum by (job) (rate(thanos_compact_group_compactions_total{job=~\".*thanos-compact.*\"}[5m]))\n* 100 \u003e 5\n)\n","for":"15m","labels":{"severity":"warning"}},{"alert":"ThanosCompactBucketHighOperationFailures","annotations":{"description":"Thanos Compact {{ \\$labels.job }} Bucket is failing to execute {{ \\$value | humanize }}% of operations.","runbook_url":"https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompactbuckethighoperationfailures","summary":"Thanos Compact Bucket is having a high number of operation failures."},"expr":"(\n  sum by (job) (rate(thanos_objstore_bucket_operation_failures_total{job=~\".*thanos-compact.*\"}[5m]))\n/\n  sum by (job) (rate(thanos_objstore_bucket_operations_total{job=~\".*thanos-compact.*\"}[5m]))\n* 100 \u003e 5\n)\n","for":"15m","labels":{"severity":"warning"}},{"alert":"ThanosCompactHasNotRun","annotations":{"description":"Thanos Compact {{ \\$labels.job }} has not uploaded anything for 24 hours.","runbook_url":"https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompacthasnotrun","summary":"Thanos Compact has not uploaded anything for last 24 hours."},"expr":"(time() - max by (job) (max_over_time(thanos_objstore_bucket_last_successful_upload_time{job=~\".*thanos-compact.*\"}[24h]))) / 60 / 60 \u003e 24","labels":{"severity":"warning"}}]}]}}
to:
Resource: "monitoring.coreos.com/v1, Resource=prometheusrules", GroupVersionKind: "monitoring.coreos.com/v1, Kind=PrometheusRule"
Name: "thanos", Namespace: "monitoring"
for: "path/to/file/thanos.yml": error when patching "path/to/file/thanos.yml": admission webhook "prometheusrulemutate.monitoring.coreos.com" denied the request: Rules are not valid
```

### Additional information

I was able to fix some of the rules by prefixing all occurences of `$` with a backslash like so `\$` and was able to apply at least some rules after reading this https://github.com/prometheus-community/helm-charts/issues/1573#issuecomment-988858943.

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know. If it's an issue of not escaping characters, would you like to submit a PR with the fix?

**Comment by Moep90** [comment]
> Hi,
> 
> Thanks for letting us know. If it's an issue of not escaping characters, would you like to submit a PR with the fix?

Hey @javsalgar thx for your reply, I dont see that I can get to root of that issue.

**Comment by javsalgar** [comment]
Hi,

What do you exactly mean? That the issue does not have to do with applying `\$`?

**Comment by Moep90** [comment]
> Hi,
> 
> What do you exactly mean? That the issue does not have to do with applying `\$`?

@javsalgar I'm sorry. I meant that I cant research and provide a fix for this. 
I dont know what really te cause is, as I dont know a mechanism how to validate these rules propperly (like linting).
From the YAML perspective it looks fine.

Adding the backslash `\$`, enabled to at least deploy a few PromRules. But for the other apply errors, as I said, I dont have the time to investigate.

**Comment by CeliaGMqrz** [comment]
Hi @Moep90 

Sorry, I have not been able to reproduce the error. It works for me by adding those parameters from the values.yaml of each chart in the same namespace.

Are you using additional parameters in thanos chart values.yaml before executing the apply? 

Could you please provide the steps including more details?

Thanks for your report.

**Comment by Moep90** [comment]
> Hi @Moep90
> 
> Sorry, I have not been able to reproduce the error. It works for me by adding those parameters from the values.yaml of each chart in the same namespace.
> 
> Are you using additional parameters in thanos chart values.yaml before executing the apply?
> 
> Could you please provide the steps including more details?
> 
> Thanks for your report.

Sorry for the late reply....
This are all my `helm_values.yml`
```yaml
bucketweb:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    enabled: true
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1001
  enabled: false
  logFormat: json
  logLevel: info
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  refresh: 30m
  resources:
    limits: {}
    requests: {}
  timeout: 5m
compactor:
  args:
    - compact
    - --log.level=info
    - --log.format=json
    - --http-address=0.0.0.0:10902
    - --data-dir=/data
    - --retention.resolution-raw=7d
    - --retention.resolution-5m=14d
    - --retention.resolution-1h=60y
    - --compact.concurrency=2
    - --downsample.concurrency=2
    - --block-files-concurrency=2
    - --hash-func=SHA256
    - --debug.accept-malformed-index
    - --consistency-delay=30m
    - --min-time=0000-01-01T00:00:00Z
    - --max-time=9999-12-31T23:59:59Z
    - --objstore.config-file=/conf/objstore.yml
    - --wait
  consistencyDelay: 30m
  containerSecurityContext:
    allowPrivilegeEscalation: false
    enabled: true
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1001
  enabled: true
  logFormat: json
  logLevel: info
  persistence:
    enabled: true
    size: 300Gi
    storageClass: {}
    storageclass: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  resources:
    limits:
      cpu: '2'
      memory: 10Gi
    requests:
      cpu: '1'
      memory: 8Gi
  retentionResolution1h: 60y
  retentionResolution5m: 14d
  retentionResolutionRaw: 7d
existingObjstoreSecret: thanos-objstore
global:
  storageClass: {}
metrics:
  enabled: true
  prometheusRule:
    default:
      create: true
    enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
query:
  affinity: {}
  containerSecurityContext:
    allowPrivilegeEscalation: false
    enabled: true
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1001
  dnsDiscovery:
    enabled: false
  enabled: true
  extraFlags:
    - --grpc-client-tls-skip-verify
  grpc:
    client:
      tls:
        autoGenerated: false
        enabled: true
        existingSecret:
          keyMapping:
            ca-cert: ca.crt
            tls-cert: tls.crt
            tls-key: tls.key
          name: thanos-tls
    server:
      tls:
        autoGenerated: false
        enabled: true
        existingSecret:
          keyMapping:
            ca-cert: ca.crt
            tls-cert: tls.crt
            tls-key: tls.key
          name: thanos-tls
  logFormat: json
  logLevel: info
  pspEnabled: true
  rbac:
    create: true
  resources:
    limits: {}
    requests: {}
  stores:
    - thanos-storegateway:10901
    - kube-prometheus-stack-thanos-discovery:10901
    - thanos-receive:10901
    - thanos-k8s-nx-product-a.example.com:443
    - thanos-k8s-otc-product-b.example.com:443
    - thanos-k8s-otc-product-c.example.com:443
    - thanos-k8s-otc-product-d.example.com:443
queryFrontend:
  affinity: {}
  containerSecurityContext:
    allowPrivilegeEscalation: false
    enabled: true
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1001
  enabled: true
  grpc:
    client:
      tls:
        autoGenerated: false
        enabled: true
        existingSecret:
          keyMapping:
            ca-cert: ca.crt
            tls-cert: tls.crt
            tls-key: tls.key
          name: thanos-tls
    server:
      tls:
        autoGenerated: false
        enabled: true
        existingSecret:
          keyMapping:
            ca-cert: ca.crt
            tls-cert: tls.crt
            tls-key: tls.key
          name: thanos-tls
  logFormat: json
  logLevel: info
  pspEnabled: true
  rbac:
    create: true
  resources:
    limits: {}
    requests: {}
receive:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    enabled: true
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1001
  enabled: true
  grpc:
    server:
      tls:
        autoGenerated: false
        enabled: true
        existingSecret:
          keyMapping:
            ca-cert: ca.crt
            tls-cert: tls.crt
            tls-key: tls.key
          name: thanos-tls
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: vault
      cert-manager.io/common-name: thanos-reveive.apps.example.com
    enabled: true
    hostname: thanos-reveive.apps.example.com
    ingressClassName: nginx
    path: /
    pathType: Prefix
    tls: true
  logFormat: json
  logLevel: info
  mode: standalone
  persistence:
    accessModes:
      - ReadWriteOnce
    enabled: true
    size: 8Gi
    storageClass: ''
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  replicationFactor: 1
  resources:
    limits: {}
    requests: {}
  tsdbRetention: 15d
receiveDistributor:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    enabled: true
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1001
  enabled: false
  logFormat: json
  logLevel: info
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  resources:
    limits: {}
    requests: {}
ruler:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    enabled: true
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1001
  enabled: false
  logFormat: json
  logLevel: info
  persistence:
    accessModes:
      - ReadWriteOnce
    enabled: true
    size: 8Gi
    storageClass: ''
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  replicaLabel: replica
  resources:
    limits: {}
    requests: {}
serviceAccount:
  create: true
storegateway:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    enabled: true
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1001
  enabled: true
  existingSecret: {}
  extraFlags:
    - --min-time=0000-01-01T00:00:00Z
    - --max-time=9999-12-31T23:59:59Z
  grpc:
    server:
      tls:
        autoGenerated: false
        enabled: true
        existingSecret:
          keyMapping:
            ca-cert: ca.crt
            tls-cert: tls.crt
            tls-key: tls.key
          name: thanos-tls
  logFormat: json
  logLevel: info
  persistence:
    accessModes:
      - ReadWriteOnce
    annotations: {}
    enabled: true
    size: 120Gi
    storageClass: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  resources:
    limits: {}
    requests: {}
  sharded:
    enabled: false
    timePartitioning:
      - max: '9999-12-31T23:59:59Z'
        min: '0000-01-01T00:00:00Z'
```
