### ISSUE TITLE
[bitnami/postgresql] Support volumeDevices instead of volumeMounts - Raw Block devices instead of Filesystem

### ISSUE THREAD

**Issue by abdennour** [bitnami/charts#13587]
### Name and Version

bitnami/postgresql 12.1.2

### What is the problem this feature will solve?

Applications with DBMS functionalities must bypass filesystem overhead to achieve improved I/O performance

### What is the feature you are proposing to solve the problem?

1. [pvc] Using volumeMode: Block instead of FileSystem
2. [po] Using volumeDevices instead of volumeMounts
3. [po] Using devicePath instead of mountPath

i.e.
```yaml
spec:
  containers:
    - name: db
      image: bitnami/postgresql
...output omitted...
      volumeDevices:
        - name: data
          devicePath: /dev/xvda
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: block-pvc
```

### What alternatives have you considered?

N/A
