### ISSUE TITLE
[bitnami/oauth2-proxy] externalRedis.password  ignored in secret.yaml and connection to redis failed

### ISSUE THREAD

**Issue by mnsaybi** [bitnami/charts#13597]
### Name and Version

bitnami/oauth2-proxy 7.4

### What steps will reproduce the bug?

I want to use an existing redis cluster with oauth2 proxy instead of a standalone cluster (sub-chart to be installed with oauth2 proxy)
 
`externalRedis.password` is defined but ignored in deployment because not added in secret.yaml like (client-secret, client-id and cookie-secret)
```
==> connection to redis failed 
```

### Are you using any custom parameters or values?
```yaml
- name: OAUTH2_PROXY_SESSION_STORE_TYPE
              value: redis
- name: OAUTH2_PROXY_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: external-redis-secret
```
### What is the expected behavior?

connection to external redis should be established with the configured password (`externalRedis.password`)

As a fix I suggest adding another key for redis password in **[secret.yaml](https://github.com/bitnami/charts/blob/main/bitnami/oauth2-proxy/templates/secret.yaml)** file 

```yaml
data:
  cookie-secret: {{ .Values.configuration.cookieSecret | b64enc | quote }}
  client-secret: {{ .Values.configuration.clientSecret | b64enc | quote }}
  client-id: {{ .Values.configuration.clientID | b64enc | quote }}
  redis-password: {{ .Values.externalRedis.password | b64enc | quote }}
```
