### ISSUE TITLE
[bitnami/thanos] k8s service conflict with receive and receive-distributor

### ISSUE THREAD

**Issue by logamanig** [bitnami/charts#13607]
### Name and Version

bitnamei/thanos 11.6.1

### What steps will reproduce the bug?

when enable receive with dual mode, the receive service point to the receive-distributor. But, service for both receive and receive-distributor are required. receive-distributor service for remote_write and receive service for exposing storeapi from receive service so that querier can fetch metrics from receive component. Since, receive-distributor doesn't have store api, we cannot use the same receive-distributor to integrate with querier.

The k8s service create also not matching this thanos design with receive-distributor (receive in dual-mode)
https://thanos.io/tip/proposals-accepted/202012-receive-split.md/

everytime I run a query from thanos, receive-distributor throws this error as it cannot fetch the metrics from receive, because it's querying the wrong component

```
caller=proxy.go:282 component=receive component=proxy request="min_time:1668883920000 max_time:1668884520000 matchers:<name:\"__name__\" value:\"otelcol_exporter_queue_capacity\" > aggregates:COUNT aggregates:SUM " err="No StoreAPIs matched for this query" stores=
```

### What is the expected behavior?

successful storeapi response from receive not receive-distributor

### What do you see instead?

everytime I run a query from thanos, receive-distributor throws this error as it cannot fetch the metrics from receive, because it's querying the wrong component
```
caller=proxy.go:282 component=receive component=proxy request="min_time:1668883920000 max_time:1668884520000 matchers:<name:\"__name__\" value:\"otelcol_exporter_queue_capacity\" > aggregates:COUNT aggregates:SUM " err="No StoreAPIs matched for this query" stores=
```

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the ticket. Just to properly understand, is there any missing deployment in the thanos installation for dual mode? Is it that services selectors are incorrect for this mode?

**Comment by logamanig** [comment]
Hi, the deployments are looks fine. but when enabling dual-mode, instead of creating separate service and ingress for receive-distributor, it's just transfers the receive's service and ingress to distributor. 

I faced another issue after creating separate service and ingress for distributor in my local. when I use the distributor endpoint as remote_write, I'm getting 500 internal server error with context deadline exceeded error

**Comment by logamanig** [comment]
I would like to also mention that each component have support to enable http and grpc ingress except receive and receive-distributor (both http and grpc ingress are missing). Could you also please add a grpc ingress for receive components?

**Comment by logamanig** [comment]
Hi @aoterolorenzo , I enabled both receive and receive distributor component. Configured the receive distributor endpoint as remote write for my metrics and it's keep failing with error code 500

> Hi @logamanig, sorry for the delay
> 
> 
> 
> Could you provide the exact set of values you are using to faithfully try to reproduce the issue?

**Comment by aoterolorenzo** [comment]
Hi @logamanig,

I will raise an internal task for our team to investigate this. We will be in touch over this conversation when it gets to an outcome. Meanwhile, I will mark it as on hold to prevent the `bitnami-bot` from closing it.

**Comment by ahmedbani** [comment]
is there any update on this issue cause I'm having the same problem ?

**Comment by carrodher** [comment]
Due to other priorities in the team, our internal task is still on our backlog.

If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by Nashluffy** [comment]
Just FYI this is still an issue. When dual mode is enabled, the service that's created for `receive` will then point to `receive-distributor`. So if your thanos-query was pointing to that service, it will now no longer work. On the flip side, this means if your ingress resource was pointing at the service, traffic will naturally shift to the new receive-distributor pods.

This is rather tricky to fix in the chart since it's likely a breaking change. If we were starting from scratch, a second service should be spun up that clearly delineates which part of the dual-mode it points to, ie. one for receive-distributor and one for receive-ingestor


```
# Source: thanos/templates/receive/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: longterm-thanos-receive
  namespace: "monitoring"
  labels:
    app: receive
    app.kubernetes.io/instance: longterm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: thanos
    app.kubernetes.io/version: 0.32.4
    helm.sh/chart: thanos-12.13.9
    project: longterm-metrics
    thanos-discovery: "true"
    app.kubernetes.io/component: receive
spec:
  type: ClusterIP
  ports:
    - port: 10902
      targetPort: http
      protocol: TCP
      name: http
      nodePort: null
  selector:
    app.kubernetes.io/instance: longterm
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: receive-distributor
```
