### ISSUE TITLE
Kafka Kraft Mode Helm Charts

### ISSUE THREAD

**Issue by ganilmca** [bitnami/charts#13624]
### Name and Version

bitnami/kafka

### What is the problem this feature will solve?

Hi Team,

1. We could see the latest update from the "apache Kafka" official site as we can use "Kafka's latest version 3.3.1 Kraft mode is Production Ready."

2. From Bitnami Kafka charts we can not able to deploy the Kubernetes cluster without zookeeper mode, could you please let us know when will be the supported helm charts will be available? 

Thanks,

**Comment by bharathreddy901** [comment]
Hi @carrodher - In Bitnami Kafka helm charts in which file we need to update Kraft environment variables. I could not find below options in any of the file. Can you please help here.

![image](https://user-images.githubusercontent.com/96808632/203351464-1ee699d6-a7e8-4da0-a7af-36fa05aba1fc.png)

Thanks,

**Comment by bharathreddy901** [comment]
Hi @carrodher - I think you are referring to bitnami docker-compose.yml from below link. We are looking for  what are the configurations to be changed for Bitnami Kafka helm charts to make it for Kraft mode.

Docker compose           -   https://github.com/bitnami/bitnami-docker-kafka/blob/master/docker-compose.yml
Bitnami Helm Charts     -  https://github.com/bitnami/charts/tree/main/bitnami/kafka

Thanks in advance.

**Comment by OneCricketeer** [comment]
> We are looking for what are the configurations to be changed for Bitnami Kafka helm charts

@bharathreddy901 You can use a literal [config](https://github.com/bitnami/charts/blob/main/bitnami/kafka/values.yaml#L95-L124)

Or `extraEnvVars`. Just look at the templates for values you can set to add env-vars shown in the Docker Compose - https://github.com/bitnami/charts/blob/main/bitnami/kafka/templates/statefulset.yaml#L359-L372

**Comment by bharathreddy901** [comment]
Thank you @OneCricketeer,I will check on it.

**Comment by zhangwei900808** [comment]
Good job!

**Comment by jcpunk** [comment]
I'll confess some interest in this as well.

**Comment by jcpunk** [comment]
I'd still love to have this feature

**Comment by AntonOfTheWoods** [comment]
It would definitely be great to have anyone who has had success with a literal config post it here. I tried doing as much and it didn't work, and unfortunately I couldn't work out why.

Zookeeper as the backing for kafka is going to be marked as obsolete in the (already overdue, ie Dec 2022) next version of kafka (3.4), and removed shortly after that, so it would be good to have a workaround while official support is worked on.

**Comment by nxthuong** [comment]
I'm able to install the chart with Kraft mode. Here is my values.yaml file:
`
extraDeploy:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: kafka-custom-scripts
      namespace: "kafka"
      labels: {{- include "common.labels.standard" . | nindent 4 }}
    data:
      kraft-setup.sh: |-
        #!/bin/bash

        ## Set value for `KAFKA_CFG_BROKER_ID`
        if [[ -f "/bitnami/kafka/data/meta.properties" ]]; then
          # Sub-sequences deployment AND Persistence enabled
          BROKER_ID=$(grep "node.id" /bitnami/kafka/data/meta.properties | awk -F '=' '{print $2}')
          BROKER_ID=$(echo $BROKER_ID | tr -d '"')
          export KAFKA_CFG_BROKER_ID=$(echo $BROKER_ID)
        else
          # First deployment OR Persistence disabled
          POD_NAME=$(grep "statefulset.kubernetes.io/pod-name" /etc/podinfo/labels | awk -F '=' '{print $2}')
          POD_NAME=$(echo $POD_NAME | tr -d '"')
          export KAFKA_CFG_BROKER_ID=$(echo $POD_NAME | rev | cut -d'-' -f 1 | rev)
        fi

        ## Set value for `KAFKA_CFG_CONTROLLER_QUORUM_VOTERS`
        REPLICAS={{ .Values.replicaCount }}
        CONTROLLER_QUORUM_VOTERS=""
        for i in $( seq 0 $REPLICAS); do
          if [[ $i != $REPLICAS ]]; then
            BROKER_ID="$((i + 0))"
            BROKER_URL="{{ include "common.names.fullname" . }}-$BROKER_ID.{{ include "common.names.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.service.ports.internal }}"
            CONTROLLER_QUORUM_VOTERS="$CONTROLLER_QUORUM_VOTERS$BROKER_ID@$BROKER_URL,"
          else
            CONTROLLER_QUORUM_VOTERS=${CONTROLLER_QUORUM_VOTERS::-1}
          fi
        done
        export KAFKA_CFG_CONTROLLER_QUORUM_VOTERS="${CONTROLLER_QUORUM_VOTERS}"

        ## Continue with default execution
        exec /entrypoint.sh /run.sh

listeners:
  - PLAINTEXT://:9092
  - CONTROLLER://:9093
advertisedListeners:
  - PLAINTEXT://:9092
listenerSecurityProtocolMap: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT"
interBrokerListenerName: PLAINTEXT
extraEnvVars:
  - name: KAFKA_ENABLE_KRAFT
    value: "yes"
  - name: KAFKA_KRAFT_CLUSTER_ID
    value: "s_vb8yLzRnyOVW3Ko2mUbg"
  - name: KAFKA_CFG_PROCESS_ROLES
    value: "broker,controller"
  - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
    value: "CONTROLLER"
extraVolumes:
  - name: myscripts
    configMap:
      name: kafka-custom-scripts
      defaultMode: 0755
  - name: podinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
extraVolumeMounts:
  - name: myscripts
    mountPath: /scripts/kraft-setup.sh
    subPath: kraft-setup.sh
  - name: podinfo
    mountPath: /etc/podinfo
command:
  - "/scripts/kraft-setup.sh"

zookeeper:
  enabled: false
`

**Comment by bharathreddy901** [comment]
Hi @nxthuong : Thanks for sharing Kraft mode details. Can you please share your complete values.yaml file.

**Comment by nxthuong** [comment]
Hi @bharathreddy901 , I think that is all Kraft related values. Btw, I install the chart on a three-nodes cluster (using minikube), so I set `replicaCount: 3`.
Did you got any issue using my values above?

**Comment by bharathreddy901** [comment]
Hi @nxthuong - I have deployed adding above Kraft values in bitnami Kafka values.yaml file. I have disabled the zookeeper.
But still i am unable to deploy Kafka in Kraft mode.I am attaching values.yaml and find error below.

I am using bitnami helm charts : https://github.com/bitnami/charts/tree/main/bitnami/kafka

**Comment by bharathreddy901** [comment]
![image](https://user-images.githubusercontent.com/96808632/210996527-05c3e5cc-859e-4ce5-b6c4-9d1141c11c90.png)

i am getting above error.

**Comment by nxthuong** [comment]
It's must be something wrong with your values because the error come from ZooKeeper. Can you provide the whole values.yaml file so I can have a look?

**Comment by bharathreddy901** [comment]
Hi @nxthuong - Sorry I missed that, Please find the attached my values.yaml files.I renamed as values.txt since yaml file are unable to attach.
[values.txt](https://github.com/bitnami/charts/files/10367517/values.txt)

![image](https://user-images.githubusercontent.com/96808632/211176685-d5d8aa47-1176-408d-b924-90cc58023d3a.png)

**Comment by nxthuong** [comment]
Is that the first time you use helm chart? The values.yaml file should only contains configuration needed to change, the rest will get from chart default values.

**Comment by bharathreddy901** [comment]
Hi @nxthuong - configs are resides on values.yaml file. I have added kraft configs in extra deploy(values.yaml) and disabled the zookeeper.
Please find the attached completed helm charts.
[charts-master_Plaintext_bitnami.zip](https://github.com/bitnami/charts/files/10367673/charts-master_Plaintext_bitnami.zip)

If I need to change anything Please  let me know.

**Comment by AntonOfTheWoods** [comment]
Thanks for your help @nxthuong . Unfortunately, I appear to be getting similar behaviour to what I had with my attempts. It looks like I am getting different results depending on what server the clients are connecting to. It *looks* like they are simply not properly forming a cluster, or at least are not communicating properly. The startup logs make it look like they *are* getting set up properly with kraft though - the helm chart installs and all the instances (3) start with no errors. Then when I try and produce or consume items, things go wrong. Initially I was getting lots of "topic doesn't exist" errors, which is funny because auto-create is on (and if memory serves I should only get an error maybe the first time). Then I started getting different behaviour/errors each time I connected. After more testing, I am getting 3 distinct behaviours. E.g., for the consumer (I am using what the helm chart spits out at the end of the installation), in one case I get a warning:

```
[2023-01-10 00:08:06,908] WARN [Consumer clientId=console-consumer, groupId=console-consumer-83135] Error while fetching metadata with correlation id 2 : {test=UNKNOWN_TOPIC_OR_PARTITION} (org.apache.kafka.clients.NetworkClient)
```

But I do get the messages that were produced, another is it just hangs (not even a warning), and the last one I get:

```
[2023-01-10 00:09:27,880] WARN [Consumer clientId=console-consumer, groupId=console-consumer-97546] Error while fetching metadata with correlation id 2 : {test=UNKNOWN_TOPIC_OR_PARTITION} (org.apache.kafka.clients.NetworkClient) 
[2023-01-10 00:09:27,988] WARN [Consumer clientId=console-consumer, groupId=console-consumer-97546] Error while fetching metadata with correlation id 4 : {test=UNKNOWN_TOPIC_OR_PARTITION} (org.apache.kafka.clients.NetworkClient)
...

But it never stops (it just keeps increasing even numbers of the correlation id) and I never get the messages.

With the normal install with zookeeper and also 3 replicas, everything works as expected with zero errors.

Any ideas?

**Comment by nxthuong** [comment]
Hi @AntonOfTheWoods , here is my values.yaml and script that install the chart:
```
## Common parameters
extraDeploy:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: kafka-custom-scripts
      namespace: {{ .Release.Namespace }}
      labels: {{- include "common.labels.standard" . | nindent 4 }}
    data:
      kraft-setup.sh: |-
        #!/bin/bash

        ## Set value for `KAFKA_CFG_BROKER_ID`
        if [[ -f "/bitnami/kafka/data/meta.properties" ]]; then
          # Sub-sequences deployment AND Persistence enabled
          BROKER_ID=$(grep "node.id" /bitnami/kafka/data/meta.properties | awk -F '=' '{print $2}')
          BROKER_ID=$(echo $BROKER_ID | tr -d '"')
          export KAFKA_CFG_BROKER_ID=$(echo $BROKER_ID)
        else
          # First deployment OR Persistence disabled
          POD_NAME=$(grep "statefulset.kubernetes.io/pod-name" /etc/podinfo/labels | awk -F '=' '{print $2}')
          POD_NAME=$(echo $POD_NAME | tr -d '"')
          export KAFKA_CFG_BROKER_ID=$(echo $POD_NAME | rev | cut -d'-' -f 1 | rev)
        fi
        echo "KAFKA_CFG_BROKER_ID: ${KAFKA_CFG_BROKER_ID}"

        ## Set value for `KAFKA_CFG_CONTROLLER_QUORUM_VOTERS`
        REPLICAS={{ .Values.replicaCount }}
        CONTROLLER_QUORUM_VOTERS=""
        for i in $( seq 0 $REPLICAS); do
          if [[ $i != $REPLICAS ]]; then
            BROKER_ID="$((i + 0))"
            BROKER_URL="{{ include "common.names.fullname" . }}-$BROKER_ID.{{ include "common.names.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.service.ports.internal }}"
            CONTROLLER_QUORUM_VOTERS="$CONTROLLER_QUORUM_VOTERS$BROKER_ID@$BROKER_URL,"
          else
            CONTROLLER_QUORUM_VOTERS=${CONTROLLER_QUORUM_VOTERS::-1}
          fi
        done
        export KAFKA_CFG_CONTROLLER_QUORUM_VOTERS="${CONTROLLER_QUORUM_VOTERS}"
        echo "KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}"

        ## Continue with default execution
        exec /entrypoint.sh /run.sh

## Kafka parameters
image:
  tag: 3.3.1-debian-11-r25
  debug: true
autoCreateTopicsEnable: true
listeners:
  - PLAINTEXT://:9092
  - CONTROLLER://:9093
advertisedListeners:
  - PLAINTEXT://:9092
listenerSecurityProtocolMap: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT"
interBrokerListenerName: PLAINTEXT
extraEnvVars:
  - name: KAFKA_ENABLE_KRAFT
    value: "yes"
  - name: KAFKA_KRAFT_CLUSTER_ID
    value: "s_vb8yLzRnyOVW3Ko2mUbg"
  - name: KAFKA_CFG_PROCESS_ROLES
    value: "broker,controller"
  - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
    value: "CONTROLLER"
extraVolumes:
  - name: myscripts
    configMap:
      name: kafka-custom-scripts
      defaultMode: 0755
  - name: podinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
extraVolumeMounts:
  - name: myscripts
    mountPath: /scripts/kraft-setup.sh
    subPath: kraft-setup.sh
  - name: podinfo
    mountPath: /etc/podinfo
command:
  - "/scripts/kraft-setup.sh"

## Statefulset parameters
replicaCount: 3

## Volume Permissions parameters
volumePermissions:
  enabled: true

## ZooKeeper chart parameters
zookeeper:
  enabled: false
```


```
#! /usr/bin/env sh

# Exit in case of error
set -e

## Set variables
export NAMESPACE=test \
  RELEASE_NAME=test-2002 \
  CHART_VERSION=20.0.2

## Add repository
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update

## Create namespace
kubectl create namespace $NAMESPACE

## Install chart
helm install $RELEASE_NAME \
  --values values.yaml \
  --namespace $NAMESPACE \
  bitnami/kafka --version $CHART_VERSION
```

I install the chart on a complete new namespace and it works fine. First, I run `kafka-console-producer.sh` script to create new topic and produce messages, then I run `kafka-console-consumer.sh` script and got all messages without any error or warning.

Also, please check the value of `KAFKA_CFG_BROKER_ID` and `KAFKA_CFG_CONTROLLER_QUORUM_VOTERS` envs (printed from `kraft-setup.sh` script) on each brokers.

**Comment by bharathreddy901** [comment]
Hi @nxthuong - Can you please share complete values.yaml and change the format to txt file. Since it will not allow to attach yaml here. It will clear all the confusions.

**Comment by AntonOfTheWoods** [comment]
Actually having the kubernetes version and distro might be relevant also

**Comment by nxthuong** [comment]
@bharathreddy901 The code block above is actually the **COMPLETE** values.yaml file. Did you try it?

@AntonOfTheWoods I use Docker Desktop running on Windows 10 with Docker Engine v20.10.21, Kubernetes v1.25.2, Minikube v1.27.0.

**Comment by AntonOfTheWoods** [comment]
@nxthuong , I have a sneaking suspicion @bharathreddy901 has downloaded the entire chart and is modifying the chart values, rather than just using the repo and adding his overrides. @bharathreddy901 , if that is the case, this is a *second* config file - you should just leave the first one and add what @nxthuong has provided (with some modifications maybe). To do that check out https://stackoverflow.com/questions/51097553/can-i-have-multiple-values-yaml-files-for-helm

**Comment by johnpptz** [comment]
Do you have any estimation when bitnami Kafka + Kraft will be production ready?

**Comment by carrodher** [comment]
No ETA for now, we have an internal task in our roadmap, but due to the capacity of the team and other priorities I can't provide an estimation, we will update this thread once there is some news. Thanks for your patience.

**Comment by NeverBehave** [comment]
If you are upgrading from older version. Be sure to regenerate metadata or kafka will refuse to start up due to `version=0`. 

You can simply delete it and delete the pod so the new metadata will be set in place.

Only tested in dev environment yet, k3s in k3d, the config above is working properly.

**Comment by AntonOfTheWoods** [comment]
> If you are upgrading from older version. Be sure to regenerate metadata or kafka will refuse to start up due to `version=0`.
> 
> You can simply delete it and delete the pod so the new metadata will be set in place.
> 
> Only tested in dev environment yet, k3s in k3d, the config above is working properly.

By dev env, do you mean on a single physical node (multiple VMs)? Just one node?

**Comment by NeverBehave** [comment]
@AntonOfTheWoods One physical node, no VMs, directly spin up cluster from k3d with 5 agents(containers), and run the chart against the cluster

**Comment by koraven** [comment]
Here is my PR implementing Kraft mode https://github.com/bitnami/charts/pull/14850
If somebody can help with testing that would be great. Remember that Kafka does not support migrations from Zookeeper to Kraft mode

**Comment by mitter91** [comment]
@koraven tried to use in minikube, but receiving continuously 
`[2023-02-12 20:45:36,525] WARN [RaftManager nodeId=0] Error connecting to node kafka-1.kafka-headless.default.svc.cluster.local:9095 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)`
changed only:
`
replicaCount: 3
kraft:
  enabled: true
zookeeper:
  enabled: false
`

**Comment by koraven** [comment]
@mitter91 That's ok. It happens because Kafka expects that all domain names exist, but k8s does not create them (with headless-svc) until Kafka is in "Ready" state. 
I could not find anything like "wait N seconds before trying to connect to other controllers" in Kafka configuration.

**Comment by fzyzcjy** [comment]
Kafka Kraft mode is a must in the future, so looking forward to seeing bitnami charts repo be updated for that, and thanks for people sharing the working config above!

**Comment by AntonOfTheWoods** [comment]
@koraven , I tried creating a cluster with the following overrides file (from commit https://github.com/bitnami/charts/pull/14850/commits/1f9f336166dd2c8a2525448be369cb4aba03df49):

```
clusterDomain: am-cluster.local
replicaCount: 3
image:
  tag: 3.3.2-debian-11-r0
kraft:
  enabled: true
  clusterId: "amclusterlocal"
headless:
  publishNotReadyAddresses: true
zookeeper:
  enabled: false
```
The cluster is a 3-node `k3s` cluster on VMs (on a budget VPS provider, using the `flannel+wireguard-native` network driver), and the system allocates one kafka node on each VM.
With or without `publishNotReadyAddresses`, it fails to start. If I simply exchange with `kraft.enabled: false` and `zookeeper.enabled: true` then the cluster comes up as expected. I also tried with the latest bitnami `3.4` image but there was no change.

I get 
```
anton@zub:~$ rkubectl logs testkraft-kafka-0 -n testk
kafka 14:22:53.69 
kafka 14:22:53.69 Welcome to the Bitnami kafka container
kafka 14:22:53.70 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 14:22:53.70 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 14:22:53.70 
kafka 14:22:53.70 INFO  ==> ** Starting Kafka setup **
kafka 14:22:53.81 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka 14:22:53.83 INFO  ==> Initializing Kafka...
kafka 14:22:53.83 INFO  ==> No injected configuration files found, creating default config files
kafka 14:22:54.46 INFO  ==> Configuring Kafka for inter-broker communications with PLAINTEXT authentication.
kafka 14:22:54.46 WARN  ==> Inter-broker communications are configured as PLAINTEXT. This is not safe for production environments.
kafka 14:22:54.47 INFO  ==> Configuring Kafka for client communications with PLAINTEXT authentication.
kafka 14:22:54.47 WARN  ==> Client communications are configured using PLAINTEXT listeners. For safety reasons, do not use this in a production environment.
kafka 14:22:54.49 INFO  ==> Initializing KRaft...
kafka 14:22:54.49 INFO  ==> Formatting storage directories to add metadata...
```
For the logs, and:
```
testkraft-kafka-0        0/1     Running            6 (2m43s ago)   6m14s
testkraft-kafka-1        0/1     Running            6 (2m46s ago)   6m16s
testkraft-kafka-2        0/1     Running            6 (2m45s ago)   6m18s
testkraft-kafka-0        0/1     Error              6 (2m48s ago)   6m19s
testkraft-kafka-1        0/1     Error              6 (2m50s ago)   6m20s
testkraft-kafka-2        0/1     Error              6 (2m49s ago)   6m22s
testkraft-kafka-1        0/1     CrashLoopBackOff   6 (5s ago)      6m24s
testkraft-kafka-0        0/1     CrashLoopBackOff   6 (7s ago)      6m25s
testkraft-kafka-2        0/1     CrashLoopBackOff   6 (4s ago)      6m25s
```

Anything else I can try?

**Comment by SandeepRatnani** [comment]
@nxthuong Thanks for the info shared [here]([nxthuong](https://github.com/nxthuong)) . But I am facing issue while adding load balancer to access the kafka broker externally. Were you able to add external IP to access the brokers running in kraft mode.

**Comment by sinkaravel07** [comment]
@AntonOfTheWoods  Thanks for the info, you shared here. SASL_PLainText is not working for me in kraft mode enabled. Could you please help me on this

**Comment by koraven** [comment]
@sinkaravel07 it is not supported yet because kafka image does not support it. There is an issue about it https://github.com/bitnami/charts/issues/15111 I think there should be a condition [here](https://github.com/bitnami/containers/blob/main/bitnami/kafka/3.4/debian-11/rootfs/opt/bitnami/scripts/libkafka.sh#L865) to not try to create zookeeper users when kraft is enabled.

**Comment by sinkaravel07** [comment]
@koraven , below is my values.yaml file. I need to use SASL_Plaintext mechanism to connect to broker with kraft mode enabled . Could you help me on that?



## Common parameters
extraDeploy:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: kafka-custom-scripts
      namespace: {{ .Release.Namespace }}
      labels: {{- include "common.labels.standard" . | nindent 4 }}
    data:
      kraft-setup.sh: |-
        #!/bin/bash

        ## Set value for `KAFKA_CFG_BROKER_ID`
        if [[ -f "/bitnami/kafka/data/meta.properties" ]]; then
          # Sub-sequences deployment AND Persistence enabled
          BROKER_ID=$(grep "node.id" /bitnami/kafka/data/meta.properties | awk -F '=' '{print $2}')
          BROKER_ID=$(echo $BROKER_ID | tr -d '"')
          export KAFKA_CFG_BROKER_ID=$(echo $BROKER_ID)
        else
          # First deployment OR Persistence disabled
          POD_NAME=$(grep "statefulset.kubernetes.io/pod-name" /etc/podinfo/labels | awk -F '=' '{print $2}')
          POD_NAME=$(echo $POD_NAME | tr -d '"')
          export KAFKA_CFG_BROKER_ID=$(echo $POD_NAME | rev | cut -d'-' -f 1 | rev)
        fi
        echo "KAFKA_CFG_BROKER_ID: ${KAFKA_CFG_BROKER_ID}"

        ## Set value for `KAFKA_CFG_CONTROLLER_QUORUM_VOTERS`
        REPLICAS={{ .Values.replicaCount }}
        CONTROLLER_QUORUM_VOTERS=""
        for i in $( seq 0 $REPLICAS); do
          if [[ $i != $REPLICAS ]]; then
            BROKER_ID="$((i + 0))"
            BROKER_URL="{{ include "common.names.fullname" . }}-$BROKER_ID.{{ include "common.names.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.service.ports.internal }}"
            CONTROLLER_QUORUM_VOTERS="$CONTROLLER_QUORUM_VOTERS$BROKER_ID@$BROKER_URL,"
          else
            CONTROLLER_QUORUM_VOTERS=${CONTROLLER_QUORUM_VOTERS::-1}
          fi
        done
        export KAFKA_CFG_CONTROLLER_QUORUM_VOTERS="${CONTROLLER_QUORUM_VOTERS}"
        echo "KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}"

        ## Continue with default execution
        exec /entrypoint.sh /run.sh

## Kafka parameters
image:
  tag: 3.3.1-debian-11-r25
  debug: true
autoCreateTopicsEnable: false
deleteTopicEnable: true
heapOpts: -Xmx1024m -Xms1024m
logRetentionHours: 72
maxMessageBytes: _10000012
auth:
  clientProtocol: sasl
  externalClientProtocol: ""
  interBrokerProtocol: plaintext
  sasl:
    interBrokerMechanism: plain
    jaas:
      clientUsers:
        - <username>
      clientPasswords: 
        - <password>
listeners:
  - PLAINTEXT://:9092
  - CONTROLLER://:9093
advertisedListeners:
  - PLAINTEXT://:9092
listenerSecurityProtocolMap: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT"
interBrokerListenerName: PLAINTEXT
extraEnvVars:
  - name: KAFKA_ENABLE_KRAFT
    value: "yes"
  - name: KAFKA_KRAFT_CLUSTER_ID
    value: "s_vb8yLzRnyOVW3Ao2mUbg"
  - name: KAFKA_CFG_PROCESS_ROLES
    value: "broker,controller"
  - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
    value: "CONTROLLER"
extraVolumes:
  - name: myscripts
    configMap:
      name: kafka-custom-scripts
      defaultMode: 0755
  - name: podinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
extraVolumeMounts:
  - name: myscripts
    mountPath: /scripts/kraft-setup.sh
    subPath: kraft-setup.sh
  - name: podinfo
    mountPath: /etc/podinfo
command:
  - "/scripts/kraft-setup.sh"

## Statefulset parameters
replicaCount: 3
nodeSelector:
   agentpool: nodepool
resources:
  requests:
    memory: 2Gi

externalAccess:
  enabled: true
  service:
    type: ClusterIP
    domain: "" ##Ingress loadbalancer ip

persistence:
  storageClass: kafka-storage
  size: 30Gi
logPersistence:
  enabled: false

## Volume Permissions parameters
# volumePermissions:
#   enabled: true

## ZooKeeper chart parameters
zookeeper:
  enabled: false

**Comment by fzyzcjy** [comment]
Hi, I am trying to use the latest master (after #14850 by @koraven ) has been merged, with the following config:

```yaml
replicaCount: 1
image:
  tag: 3.4.0-debian-11-r8
kraft:
  enabled: true
  clusterId: "hello_cluster_id"
headless:
  publishNotReadyAddresses: true
zookeeper:
  enabled: false
```

However, it does not work: It keeps crashing and crashing. The exit code is 1:

```
terminated
Reason:Reason: Error - exit code: 1
```

Weirdly, it does not have any error log:

```
kafka 12:13:48.51 
kafka 12:13:48.51 Welcome to the Bitnami kafka container
kafka 12:13:48.51 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 12:13:48.51 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 12:13:48.52 
kafka 12:13:48.52 INFO  ==> ** Starting Kafka setup **
kafka 12:13:48.57 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka 12:13:48.58 INFO  ==> Initializing Kafka...
kafka 12:13:48.59 INFO  ==> No injected configuration files found, creating default config files
kafka 12:13:49.17 INFO  ==> Configuring Kafka for inter-broker communications with PLAINTEXT authentication.
kafka 12:13:49.17 WARN  ==> Inter-broker communications are configured as PLAINTEXT. This is not safe for production environments.
kafka 12:13:49.17 INFO  ==> Configuring Kafka for client communications with PLAINTEXT authentication.
kafka 12:13:49.18 WARN  ==> Client communications are configured using PLAINTEXT listeners. For safety reasons, do not use this in a production environment.
kafka 12:13:49.19 INFO  ==> Initializing KRaft...
kafka 12:13:49.19 INFO  ==> Formatting storage directories to add metadata...
```

![image](https://user-images.githubusercontent.com/5236035/223419208-09ad0867-e191-4a6c-a4f3-402dee2d3c32.png)

**Comment by AntonOfTheWoods** [comment]
@fzyzcjy , I have an almost identical config on a single-node k3s cluster on a cloud VPS and it is working fine. I installed from their chart repo rather than git but it should be the same. Did you do a fresh install? I definitely had to delete the previous kafka pvc for it to work (which was known, there are no upgrades supported yet), so if you didn't do that, then that might be the reason.

**Comment by koraven** [comment]
@fzyzcjy If you don't see other errors when you run the chart and kafka in debug mode, it can be that you just use M1/M2 based Mac. I had similar issue on Mac when it just hangs until liveness check fails and container is terminated.
Maybe if you choose the image for ARM it helps but I didn't try.

**Comment by fzyzcjy** [comment]
@AntonOfTheWoods @koraven Thanks for the replies!

* I deleted the PVC and PV. (will double check and do experiment again later)
* on linux, not mac

I will do more experiments and report progress here.

(Btw it is so weird for it to exit code 1 without even printing a single warning message...)

**Comment by luisloros** [comment]
Don't know if this might help, I was able to deploy a 3 node Kafka cluster by creating a values.yaml with content as follows:
```
extraDeploy:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: kafka-custom-scripts
      namespace: {{ .Release.Namespace }}
      labels: {{- include "common.labels.standard" . | nindent 4 }}
    data:
      kraft-setup.sh: |-
        #!/bin/bash

        ## Set value for `KAFKA_CFG_BROKER_ID`
        if [[ -f "/bitnami/kafka/data/meta.properties" ]]; then
          # Sub-sequences deployment AND Persistence enabled
          BROKER_ID=$(grep "node.id" /bitnami/kafka/data/meta.properties | awk -F '=' '{print $2}')
          BROKER_ID=$(echo $BROKER_ID | tr -d '"')
          export KAFKA_CFG_BROKER_ID=$(echo $BROKER_ID)
        else
          # First deployment OR Persistence disabled
          POD_NAME=$(grep "statefulset.kubernetes.io/pod-name" /etc/podinfo/labels | awk -F '=' '{print $2}')
          POD_NAME=$(echo $POD_NAME | tr -d '"')
          export KAFKA_CFG_BROKER_ID=$(echo $POD_NAME | rev | cut -d'-' -f 1 | rev)
        fi
        echo "KAFKA_CFG_BROKER_ID: ${KAFKA_CFG_BROKER_ID}"

        ## Set value for `KAFKA_CFG_CONTROLLER_QUORUM_VOTERS`
        REPLICAS={{ .Values.replicaCount }}
        CONTROLLER_QUORUM_VOTERS=""
        for i in $( seq 0 $REPLICAS); do
          if [[ $i != $REPLICAS ]]; then
            BROKER_ID="$((i + 0))"
            BROKER_URL="{{ include "common.names.fullname" . }}-$BROKER_ID.{{ include "common.names.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.service.ports.internal }}"
            CONTROLLER_QUORUM_VOTERS="$CONTROLLER_QUORUM_VOTERS$BROKER_ID@$BROKER_URL,"
          else
            CONTROLLER_QUORUM_VOTERS=${CONTROLLER_QUORUM_VOTERS::-1}
          fi
        done
        export KAFKA_CFG_CONTROLLER_QUORUM_VOTERS="${CONTROLLER_QUORUM_VOTERS}"
        echo "KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}"

        ## Continue with default execution
        exec /entrypoint.sh /run.sh

autoCreateTopicsEnable: true
listeners:
  - PLAINTEXT://:9092
  - CONTROLLER://:9093
advertisedListeners:
  - PLAINTEXT://:9092
listenerSecurityProtocolMap: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT"
interBrokerListenerName: PLAINTEXT
extraEnvVars:
  - name: KAFKA_ENABLE_KRAFT
    value: "yes"
  - name: KAFKA_KRAFT_CLUSTER_ID
    value: "s_vb8yLzRnyOVW3Ko2mUbg"
  - name: KAFKA_CFG_PROCESS_ROLES
    value: "broker,controller"
  - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
    value: "CONTROLLER"
extraVolumes:
  - name: kafka-custom-scripts
    configMap:
      name: kafka-custom-scripts
      defaultMode: 0755
  - name: podinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
extraVolumeMounts:
  - name: kafka-custom-scripts
    mountPath: /scripts/kraft-setup.sh
    subPath: kraft-setup.sh
  - name: podinfo
    mountPath: /etc/podinfo
command:
  - "/scripts/kraft-setup.sh"

replicaCount: 3

zookeeper:
  enabled: false

kraft:
  enabled: true
```

And then running
`helm upgrade my-kafka bitnami/kafka --install -n kafka --create-namespace --values values.yaml`

Source: https://msazure.club/deploy-kafka-without-zookeeper/
