### ISSUE TITLE
[postgresql-ha] serviceAccount.name is ignored

### ISSUE THREAD

**Issue by giuliocalzolari** [bitnami/charts#13629]
### Name and Version

bitnami/postgresql-ha: 10.0.3

### What steps will reproduce the bug?

based on the [values.yaml ](https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha/values.yaml#L1072) is possible to setup the service account name, but in `serviceaccount.yaml`  such kind of parameter is ignored

### Are you using any custom parameters or values?

--set fullnameOverride=test --set serviceAccount.name=test-sa

### What is the expected behavior?

```
# Source: demo/charts/postgresql-ha/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
  namespace: "demo"
  labels:
    app.kubernetes.io/name: demo
    helm.sh/chart: postgresql-ha-10.0.3
    app.kubernetes.io/instance: pcs
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true

```

### What do you see instead?

```
# Source: demo/charts/postgresql-ha/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test # my fullnameOverride
  namespace: "demo"
  labels:
    app.kubernetes.io/name: demo
    helm.sh/chart: postgresql-ha-10.0.3
    app.kubernetes.io/instance: pcs
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true

```
