### ISSUE TITLE
[bitnami/postgresql-ha] Findings from OpenShift deployment

### ISSUE THREAD

**Issue by yemkay** [bitnami/charts#13675]
### Name and Version

bitnami/postgresql-ha 9.4.11

### What is the problem this feature will solve?

I found many errors while deploying postgresql-ha chart to OpenShift. 
```
Server Version: 4.10.12
Kubernetes Version: v1.23.5+70fb84c
```
All those errors were of kind "Permission denied", as the container filesystem is Readonly in OpenShift. 

### What is the feature you are proposing to solve the problem?

To overcome these errors, I had to define volumes for writable paths, to allow the postgres process to write to them. 
Following are samples or reference:

**pg-values.yaml:** 
```
postgresql:
  ## Fix to allow non-root container users (RHOCP environments),
  extraVolumes:
  - name: pg-conf
    emptyDir: {}
  - name: pg-tmp
    emptyDir: {}
  - name: repmgr-conf
    emptyDir: {}
  - name: tmp-dir
    emptyDir: {}
  - name: wal-archives-mnt-nfs
    emptyDir: {}

  extraVolumeMounts:
    #Path used for auto generation of conf
  - name: pg-conf
    mountPath: /opt/bitnami/postgresql/conf/
    #Temp path used for creating temp files
  - name: pg-tmp
    mountPath: /opt/bitnami/postgresql/tmp/
    #Path used for auto generation of conf
  - name: repmgr-conf
    mountPath: /opt/bitnami/repmgr/conf/
    #Temp path
  - name: tmp-dir
    mountPath: /tmp
    # Mount the extraVolumes from the outside (hostPath, NFS, AWS S3, EBS, etc)
  - name: wal-archives-mnt-nfs
    mountPath: /mnt/nfs/wal_archives
  
  extraInitContainers:
  - name: init-conf-dir
    image: busybox
    imagePullPolicy: IfNotPresent
    ##Main container expects the /conf directory to be present, 
    ##otherwise first time it fails to generate the postgresql.conf under it
    command: ['sh', '-c', 'mkdir -p /bitnami/postgresql/conf/conf.d']
    volumeMounts:
    - name: data
      mountPath: /bitnami/postgresql
pgpool:
  ## Fix to allow non-root container users (RHOCP environments),
  extraVolumes:
  - name: pgpool-conf
    emptyDir: {}
  - name: pgpool-tmp
    emptyDir: {}
  - name: pgpool-pcp
    emptyDir: {}

  extraVolumeMounts:
  - name: pgpool-conf
    mountPath: /opt/bitnami/pgpool/conf/
  - name: pgpool-tmp
    mountPath: /opt/bitnami/pgpool/tmp/
    ##This file should be writable for writing admin credentials
  - name: pgpool-pcp
    mountPath: /opt/bitnami/pgpool/etc/pcp.conf
    subPath: pcp.conf

  initContainers:
  - name: init-conf
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'touch /init/pcp.conf']
    volumeMounts:
    - name: pgpool-pcp
      mountPath: /init
```

**pg-security-context.yaml:**

```
##Define uid, gid, fsgroupid in the range allowed by your namespace/project. Find it by command: oc get project <project-name> 
##For some reason, 64 bit integers are not converted properly. So I edited my namespace to a range of 32-bit integers to avoid this issue: https://github.com/bitnami/charts/issues/12232

postgresql:
  image:
    debug: true
  podSecurityContext:
    enabled: true
    fsGroup: 31010
  containerSecurityContext:
    enabled: true
    runAsUser: 31010
    runAsGroup: 31010
    runAsNonRoot: true
    readOnlyRootFilesystem: true
pgpool:
  image:
    debug: true
  podSecurityContext:
    enabled: true
    fsGroup: 31010
  containerSecurityContext:
    enabled: true
    runAsUser: 31010
    runAsGroup: 31010
    runAsNonRoot: true
    readOnlyRootFilesystem: true
volumePermissions:
  enabled: false
  podSecurityContext:
    runAsUser: 31010
metrics:
  podSecurityContext:
    enabled: true
    runAsUser: 31010
```
