### ISSUE TITLE
Wordpress Memcached Connection error

### ISSUE THREAD

**Issue by pomland-94** [bitnami/charts#13674]
### Name and Version

bitnami/wordpress:latest

### What steps will reproduce the bug?

Hey,
I installed the WordPress Chart with Helm in my Kubernetes Cluster, I also enabled Memcached and created a Secret for the memcache admin user. But W3total Cache can't connect to the local memcache instance under `wordpress-memcached.wordpress.svc.cluster.local:11211` the Namespace I used is `Wordpress`

This is my Values.yaml
```yaml
image:
  pullPolicy: Always
podSecurityContext:
  enabled: true
containerSecurityContext:
  enabled: true
replicaCount: 2
persistence:
  enabled: true
  size: 6Gi
  accessModes:
    - ReadWriteMany
mariadb:
  primary:
    persistence:
      size: 3Gi
      storageClass: rook-ceph-block
    podSecurityContext:
      enabled: true
    containerSecurityContext:
      enabled: true
memcached:
  enabled: true
  auth:
    enabled: true
    username: admin
    existingPasswordSecret: memcache-secret
  persistence:
    enabled: true
    size: 6Gi
ingress:
  ingressClassName: nginx
  hostname: contentways.org
  extraHosts:
    - name: www.contentways.org
      path: /
  enabled: true
  annotations:
    cert-manager.io/issuer: wordpress-acme
  tls: true
  extraTls:
  - hosts:
    - www.contentways.org
    secretName: www-contentways.org-tls
wordpressUsername: XXX
wordpressEmail: XXX
wordpressBlogName: XXX
wordpressFirstName: XXX
wordpressLastName: XXX
wordpressScheme: https
allowEmptyPassword: false
wordpressConfigureCache: true
```

What I am doing wrong?

### What do you see instead?

![Bildschirm­foto 2022-11-23 um 23 25 41](https://user-images.githubusercontent.com/96850116/203656270-c2c0ee9c-0cec-42f1-9abd-6acbbcd05568.png)
