### ISSUE TITLE
[binami/kafka] Reversed CA and client cert in provisioning job

### ISSUE THREAD

**Issue by tbnguyen1407** [bitnami/charts#13688]
### Name and Version

bitnami/kafka 19.1.3

### What steps will reproduce the bug?

1. Deploy chart with TLS and provisioning

### Are you using any custom parameters or values?

```yaml
auth:
  clientProtocol: tls
  tls:
    type: pem
    existingSecrets: [kafka-tls-secret, kafka-tls-secret, kafka-tls-secret]
    endpointIdentificationAlgorithm: https

provisioning:
  enabled: true
  topics:
    - name: mytopic
  auth:
    tls:
      type: pem
      certificatesSecret: kafka-client-tls-secret
```

### What is the expected behavior?

Topics successfully provisioned

### What do you see instead?

Provisioning job cert validation failed with:
```
Unable to find valid certification path to requested target
```
### Additional information

Keystore and truststore seem to be reversed
- Client cert should be in keystore
- CA cert should be in truststore

https://github.com/bitnami/charts/blob/7b63fd6576b11e45860773a665f0ec0da2583bfe/bitnami/kafka/templates/kafka-provisioning.yaml#L115-L116

The provisioning script should be fixed.

**Workaround**: switch 2 keys in the secret

```yaml
provisioning:
  auth:
    tls:
      caCert: tls.crt
      cert: ca.crt
```
