### ISSUE TITLE
[bitnami/mysql] How secondary replication works?

### ISSUE THREAD

**Issue by elwood218** [bitnami/charts#13681]
### Name and Version

bitnami/mysql 9.4.4

### What is the problem this feature will solve?

I thought and hoped that mysql secondary is also automatically synced when there is a primary which had already data. So that there is automatically a dump pulled and then the replication started.
But it seems that the setup only works if there is an empty database. This would also prevent an raising of "replicaCount" later which would automatically set up the secondary.

### What is the feature you are proposing to solve the problem?

Maybe this could be documented anywhere at least.
Also a documentation would be nice how to bring it in sync - because at the moment I cannot even connect to the secondary to put a restore a recent dump from the primary.

But best would be that the secondary automatically gets synced. Maybe doing a mysqldump from the primary automatically if the server is out of sync?

Maybe I am missing something? But maybe also other got that problem because it's not documented well enough?!

**Comment by elwood218** [comment]
```
The MYSQL_MASTER_HOST, MYSQL_MASTER_ROOT_USER and MYSQL_MASTER_ROOT_PASSWORD parameters are used by the slave to connect to the master. It also takes a dump of the existing data in the master server.
```

This is what the docker image says. https://github.com/bitnami/containers/tree/main/bitnami/mysql#setting-up-a-replication-cluster

But I cannot see that in the scripts of the Docker image and also not that this is happening.

**Comment by javsalgar** [comment]
Hi.

Do you have an example docker-compose that triggers the issue? In principle, the replication should take place so we would like to reproduce the issue.

**Comment by elwood218** [comment]
Hi @javsalgar thank you for the quick response :)
What do you mean by example docker-compose? We use your helm chart and I thought at least that the link I posed is the docker image you also use in the helm chart?!

We use helmfile to deploy the chart:

```
  - name: mysql-{{.Values.environment}}
    namespace: services-{{.Values.environment}}
    chart: bitnami/mysql
    version: 9.4.4
    labels:
      app: mysql
    values:
      - mysql.gotmpl
```

```
architecture: replication

auth:
  database: magento
  username: magento
  existingSecret: mysql-magento-credentials

primary:
  persistence:
    enabled: true
    size: 80Gi
    storageClass: ssd-rpd

  configuration: |
    {{- readFile "magento.cnf" | nindent 4 }}

  pdb:
    create: false

  resources:
    requests:
      memory: 18G
      cpu: 600m

secondary:

  replicaCount: 1

  persistence:
    enabled: true
    size: 80Gi
    storageClass: ssd-rpd


  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: false

  pdb:
    create: false

  resources:
    requests:
      memory: 18G
      cpu: 600m
```

The probes on the secondary are disabled because we tried to manually dump from primary to secondary.
I would think that the dump is happen automatically. 

Further facts:
As I mentioned we had an "standalone" setup (so a setup which already had data) but which I destroyed and re-used the PV for the primary - but now I thought the secondary would automatically dump the data from the primary. As when increase the replicaCount this should also be take place automatically - otherwise when adding secondaries someone needs to take manually a dump everytime.
