### ISSUE TITLE
[bitnami/mediawiki] Deployment fails: externalDatabase host is not honored in image 

### ISSUE THREAD

**Issue by ololdach** [bitnami/charts#13714]
### Name and Version

bitnami/mediawiki 14.3.8

### What steps will reproduce the bug?

k3s 1.24.7
deploy mediawiki in namespace mediawiki using externalDatabase pointing to the db in another namespace

values:
```yaml
externalDatabase:
  host: mariadb.mariadb-prod.svc.cluster.local
  port: 3306
```
translates to deployment:
```yaml
      - env:
        - name: BITNAMI_DEBUG
          value: "true"
        - name: ALLOW_EMPTY_PASSWORD
          value: "no"
        - name: MARIADB_HOST
          value: mariadb.mariadb-prod.svc.cluster.local
        - name: MARIADB_PORT_NUMBER
          value: "3306"
```
which leads up to the error in the log of the pod:
```
ERROR 2005 (HY000): Unknown server host 'maraidb-production-mariadb.mariadb.svc.cluster.local' (-2) 
```
Since the env var has the right host, either the name of the environment variable is wrong, so that the container tries to get the host from another place, or the container fails to honor the value of the env. Either way, it's likely a bug to be fixed in the container image

### Are you using any custom parameters or values?

no

### What is the expected behavior?

I'd expect the container to respect the db host parameter passed with the MARIADB_HOST env var, connect to the database and start correctly

### What do you see instead?

The pod fails to start. Without debugging enabled the error reads: Failed to connect to database

### Additional information

Since this bug has been in and out of production, I assume that there are some places where the container "generates" his default host name for the db (sensible behavior whenever the chart configures the embedded mariadb). Please make sure to switch off any tampering with the hostname, as soon aas the externalDatabase is enabled.
