### ISSUE TITLE
[bitnami/mongodb] MongoServerError: Authentication failed

### ISSUE THREAD

**Issue by emre141** [bitnami/charts#13744]
### Name and Version

bitname/mongodb:13.5.0

### What steps will reproduce the bug?

Bitnami Helm Chart : mongodb 
Chart Version: 13.5.0
MongoDB Image Version: 6.0.3-debian-11-r4
Helm Version: v3.7.2
Kubernetes Engine Version: 1.21
Cloud Provider: AWS
Storage Provisioner: kubernetes.io/aws-ebs

### Are you using any custom parameters or values?

I am using default values.yaml only except below parameter 

Cluster Configuration

```yaml
auth:
  enabled: true
  rootUser: root
  rootPassword: root123
  replicaSetKey: mongoprod
  replicaSetName: prodrs

persistence:
  enabled: true
  medium: ""
  existingClaim: ""
  resourcePolicy: ""
  storageClass: "gp2-new"
  accessModes:
    - ReadWriteOnce
  size: 10Gi

configuration: |  
  # mongod.conf
  # for documentation of all options, see:
  #   http://docs.mongodb.org/manual/reference/configuration-options/

  # where and how to store data.
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
    engine: wiredTiger
    wiredTiger:
      engineConfig:
        cacheSizeGB: 5

  # where to write logging data.
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0

  # network interfaces
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    bindIpAll: true
    #bindIp:

  # replica set options
  replication:
    replSetName: prodrs
    enableMajorityReadConcern: true

  # sharding options
  #sharding:
    #clusterRole:

  # process management options
  processManagement:
     fork: false
     pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid

  # set parameter options
  setParameter:
     enableLocalhostAuthBypass: false

  # security options
  security:
    authorization: enabled
    keyFile: /opt/bitnami/mongodb/conf/keyfile
```
`--set auth.rootPassword and --set auth.replicaSetKey`

### What do you see instead?

I followed up the outputed steps after helm chart installed, I execute a mongo client pod tried to connect to the mongo primary pod but I have got below error output,

```console
$ kubectl run --namespace infra mongo-prod-rs-client --rm --tty -i --restart='Never' --env="MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD" --image docker.io/bitnami/mongodb:6.0 --command -- bash

If you don't see a command prompt, try pressing enter.

I have no name!@mongo-prod-rs-client:/$ mongosh admin --host "mongo-prod-rs-0.mongo-prod-rs-headless.infra.svc.cluster.local:27017" --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD
Current Mongosh Log ID:	638630884c7035049ee6394d
Connecting to:		mongodb://<credentials>@mongo-prod-rs-0.mongo-prod-rs-headless.infra.svc.cluster.local:27017/admin?directConnection=true&authSource=admin&appName=mongosh+1.6.0
MongoServerError: Authentication failed.
```

As well I have got authentication failed error from arbiter pod due to that the arbiter pods consistently restarting

```
NAME                                                    READY   STATUS    RESTARTS   AGE
mongo-prod-rs-0                                         1/1     Running   0          24m
mongo-prod-rs-1                                         1/1     Running   0          25m
mongo-prod-rs-arbiter-0                                 1/1     Running   **5**       24m
```

Arbiter Pod Logs
```
mongodb 16:42:56.01 
mongodb 16:42:56.02 Welcome to the Bitnami mongodb container
mongodb 16:42:56.02 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 16:42:56.03 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 16:42:56.03 
mongodb 16:42:56.03 INFO  ==> ** Starting MongoDB setup **
mongodb 16:42:56.05 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 16:42:56.11 INFO  ==> Initializing MongoDB...
mongodb 16:42:56.13 INFO  ==> Deploying MongoDB from scratch...
MongoNetworkError: connect ECONNREFUSED 172.16.6.17:27017
mongodb 16:42:58.17 INFO  ==> Creating users...
mongodb 16:42:58.18 INFO  ==> Users created
mongodb 16:42:58.18 INFO  ==> Writing keyfile for replica set authentication...
mongodb 16:42:58.20 INFO  ==> Configuring MongoDB replica set...
mongodb 16:42:58.21 INFO  ==> Stopping MongoDB...
mongodb 16:43:02.81 INFO  ==> Trying to connect to MongoDB server mongo-prod-rs-0.mongo-prod-rs-headless.infra.svc.cluster.local...
mongodb 16:43:02.83 INFO  ==> Found MongoDB server listening at mongo-prod-rs-0.mongo-prod-rs-headless.infra.svc.cluster.local:27017 !
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
```

**Comment by javsalgar** [comment]
Hi,

Could you share the logs of the other pods? Could you re-try the experiment with `image.debug=true`. Also, could you ensure that there are no leftover PVCs from previous installations?

**Comment by emre141** [comment]
@javsalgar ,
I have completely uninstall mongodb helm release and clean all pvc, pv and ebs volume, afterward I used below command to install,
`helm upgrade --install mongprod-test my-repo/mongodb --version=13.5.0 -f values.prod-rs.yaml --set auth.rootPassword=root123,auth.replicaSetKey=mongoprod --set image.debug=true --debug --atomic --wait --timeout 5m`

**POD Status**
```
emre@MACFVFF76H8Q05P:/tmp|⇒  kubectl get pods
NAME                                                    READY   STATUS    RESTARTS   AGE
mongo-prod-rs-0                                         1/1     Running   0          15m
mongo-prod-rs-1                                         1/1     Running   0          14m
mongo-prod-rs-arbiter-0                                 0/1     Error     3          15m
```
**PVC Status**
```
NAME                             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
datadir-mongo-prod-rs-0          Bound    pvc-daf9587b-44f4-4dd6-a2c6-bea073b2e7f4   10Gi       RWO            gp2-new        15m
datadir-mongo-prod-rs-1          Bound    pvc-6477a3c2-af1f-4638-a316-38557c6df77b   10Gi       RWO
```

**mongo arbiter pod logs**
```
mongodb 19:55:19.97 
mongodb 19:55:19.97 Welcome to the Bitnami mongodb container
mongodb 19:55:19.97 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 19:55:19.97 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 19:55:19.97 
mongodb 19:55:19.98 INFO  ==> ** Starting MongoDB setup **
mongodb 19:55:19.99 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 19:55:20.02 INFO  ==> Initializing MongoDB...
mongodb 19:55:20.03 INFO  ==> Deploying MongoDB from scratch...
mongodb 19:55:20.03 DEBUG ==> Starting MongoDB in background...
{"t":{"$date":"2022-11-30T19:55:20.050Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"enableLocalhostAuthBypass":{"default":true,"value":true}}}}
about to fork child process, waiting until server is ready for connections.
forked process: 45
child process started successfully, parent exiting
MongoNetworkError: connect ECONNREFUSED 172.16.4.164:27017
mongodb 19:55:21.54 INFO  ==> Creating users...
mongodb 19:55:21.54 INFO  ==> Users created
mongodb 19:55:21.54 INFO  ==> Writing keyfile for replica set authentication...
mongodb 19:55:21.56 INFO  ==> Configuring MongoDB replica set...
mongodb 19:55:21.56 INFO  ==> Stopping MongoDB...
mongodb 19:55:22.57 DEBUG ==> Starting MongoDB in background...
{"t":{"$date":"2022-11-30T19:55:22.606Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"enableLocalhostAuthBypass":{"default":true,"value":true}}}}
about to fork child process, waiting until server is ready for connections.
forked process: 138
child process started successfully, parent exiting
mongodb 19:55:25.35 DEBUG ==> Waiting for primary node...
mongodb 19:55:25.36 DEBUG ==> Waiting for primary node...
mongodb 19:55:25.36 INFO  ==> Trying to connect to MongoDB server mongo-prod-rs-0.mongo-prod-rs-headless.infra.svc.cluster.local...
cannot resolve host "mongo-prod-rs-0.mongo-prod-rs-headless.infra.svc.cluster.local": lookup mongo-prod-rs-0.mongo-prod-rs-headless.infra.svc.cluster.local: no such host
cannot resolve host "mongo-prod-rs-0.mongo-prod-rs-headless.infra.svc.cluster.local": lookup mongo-prod-rs-0.mongo-prod-rs-headless.infra.svc.cluster.local: no such host
mongodb 19:55:35.39 INFO  ==> Found MongoDB server listening at mongo-prod-rs-0.mongo-prod-rs-headless.infra.svc.cluster.local:27017 !
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.

```

mongodb primary pod log
```
{"t":{"$date":"2022-11-30T19:55:31.521Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"enableLocalhostAuthBypass":{"default":true,"value":false}}}}

{"t":{"$date":"2022-11-30T19:55:31.521+00:00"},"s":"I",  "c":"CONTROL",  "id":20698,   "ctx":"-","msg":"***** SERVER RESTARTED *****"}
{"t":{"$date":"2022-11-30T19:55:31.521+00:00"},"s":"I",  "c":"NETWORK",  "id":4915701, "ctx":"-","msg":"Initialized wire specification","attr":{"spec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":17},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":17},"outgoing":{"minWireVersion":6,"maxWireVersion":17},"isInternalClient":true}}}
{"t":{"$date":"2022-11-30T19:55:31.521+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"-","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
{"t":{"$date":"2022-11-30T19:55:31.522+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
{"t":{"$date":"2022-11-30T19:55:31.535+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"main","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"TenantMigrationDonorService","namespace":"config.tenantMigrationDonors"}}
[primary-pod.log](https://github.com/bitnami/charts/files/10126903/primary-pod.log)
[primary-pod.log](https://github.com/bitnami/charts/f
[secondary-pod.log](https://github.com/bitnami/charts/files/10126914/secondary-pod.log)
iles/10126912/primary-pod.log)

```

**Comment by emre141** [comment]
I do not know but I guess the root user did not create or does not create due to following log lines getting from primary but not  secondary pod, so i could not see ACCESS facility based on secondary but I saw the logs on only primary pod ?

```
{"t":{"$date":"2022-11-30T19:55:36.227+00:00"},"s":"I",  "c":"ACCESS",   "id":20251,   "ctx":"conn3","msg":"Supported SASL mechanisms requested for unknown user","attr":{"user":{"user":"root","db":"admin"}}}
{"t":{"$date":"2022-11-30T19:55:36.227+00:00"},"s":"I",  "c":"ACCESS",   "id":20249,   "ctx":"conn3","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-256","speculative":true,"principalName":"root","authenticationDatabase":"admin","remote":"172.16.4.164:48328","extraInfo":{},"error":"UserNotFound: Could not find user \"root\" for db \"admin\""}}
{"t":{"$date":"2022-11-30T19:55:36.228+00:00"},"s":"I",  "c":"ACCESS",   "id":20249,   "ctx":"conn3","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-1","speculative":false,"principalName":"root","authenticationDatabase":"admin","remote":"172.16.4.164:48328","extraInfo":{},"error":"UserNotFound: Could not find user \"root\" for db \"admin\""}}
{"t":{"$date":"2022-11-30T19:55:36.230+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn2","msg":"Connection ended","attr":{"remote":"172.16.4.164:48312","uuid":"da1f76fa-0f6f-411d-a023-00737764d250","connectionId":2,"connectionCount":1}}
```

**Comment by emre141** [comment]
Hi @CeliaGMqrz 

Did you have change to look at the issue ? Do you have any update ?

**Comment by CeliaGMqrz** [comment]
Hi @emre141 

Thanks for reporting this but sorry, I need more time to reproduce this particular case. 
I have created an internal task to investigate the issue. We’ll leave this issue on hold until we have updates.

**Comment by emre141** [comment]
> Hi @emre141
> 
> Thanks for reporting this but sorry, I need more time to reproduce this particular case. I have created an internal task to investigate the issue. We’ll leave this issue on hold until we have updates.

Hi Celina, 
Have you ever chance  to test the case on your environment

**Comment by fmulero** [comment]
Hi Emre.

I think you missed something in the values.yaml or in the instructions to reproduce the issue, for example `architecture` is set standalone by default (which enforces the number of replicas to 1) and I don't see where did you set it. Could you review if you share correctly the values?

Other points you have to check are:
* `replicaSetName` value should be at root level, not under `auth`
*  In the configuration file `enableLocalhostAuthBypass` should be set to `true` at least during first installation to create the default users, after that you can upgrade your deployment and set it to `false`

**Comment by emre141** [comment]
I tried a couple of different way to install mongodb replicaset let me share the way which was successed and failed 

Success Scenari-1
```
helm install my-release \             
    --set auth.rootPassword=secretpassword,auth.username=my-user,auth.password=my-password,auth.database=my-database,architecture=replicaset,replicaCount=2,persistence.storageClass=gp2-new  my-repo/mongodb
```
```
⚡ ⇒  kubectl get pods -l app.kubernetes.io/instance=my-release
NAME                           READY   STATUS    RESTARTS   AGE
my-release-mongodb-0           1/1     Running   0          4m26s
my-release-mongodb-1           1/1     Running   0          3m48s
my-release-mongodb-arbiter-0   1/1     Running   0          4m26s
```

**Primary Pod Log Output**

mongodb 19:34:52.07 INFO  ==> Advertised Hostname: my-release-mongodb-0.my-release-mongodb-headless.infra.svc.cluster.local
mongodb 19:34:52.08 INFO  ==> Advertised Port: 27017
realpath: /bitnami/mongodb/data/db: No such file or directory
mongodb 19:34:52.08 INFO  ==> Data dir empty, checking if the replica set already exists
MongoNetworkError: connect ECONNREFUSED 172.16.6.17:27017
mongodb 19:34:53.98 INFO  ==> Pod name matches initial primary pod name, configuring node as a primary
mongodb 19:34:53.99 
mongodb 19:34:53.99 Welcome to the Bitnami mongodb container
mongodb 19:34:53.99 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 19:34:53.99 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 19:34:54.00 
mongodb 19:34:54.00 INFO  ==> ** Starting MongoDB setup **
mongodb 19:34:54.01 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 19:34:54.35 INFO  ==> Initializing MongoDB...
mongodb 19:34:54.37 INFO  ==> Deploying MongoDB from scratch...
MongoNetworkError: connect ECONNREFUSED 172.16.6.17:27017
**mongodb 19:34:56.37 INFO  ==> Creating users...
mongodb 19:34:56.38 INFO  ==> Creating root user...**
Current Mongosh Log ID: 6390eae129d528632842af04
Connecting to:          mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.6.0
Using MongoDB:          6.0.3
Using Mongosh:          1.6.0

For mongosh info see: https://docs.mongodb.com/mongodb-shell/

**Clean Release and Persistent Volumes**
`helm uninstall my-release`
`kubectl delete pvc datadir-my-release-mongodb-0 datadir-my-release-mongodb-1`
`kubectl delete pv pvc-cd8d9e1b-3d63-4cdb-a83d-d738c2787f23 pvc-df853eb1-dddb-4586-95ef-d32e72146f53`
Delete volume from EBS console (permentantly cleaned)

Success Scenario-2
Just use latest chart version and without custom user and custom database

```
helm install my-release \          
    --set auth.rootPassword=secretpassword,architecture=replicaset,replicaCount=2,persistence.storageClass=gp2-new  my-repo/mongodb
```

```
⚡ ⇒  kubectl get pods -l app.kubernetes.io/instance=my-release
NAME                           READY   STATUS    RESTARTS   AGE
my-release-mongodb-0           1/1     Running   0          4m26s
my-release-mongodb-1           1/1     Running   0          3m48s
my-release-mongodb-arbiter-0   1/1     Running   0          4m26s
```

**Mongodb Primary Pod Log**

mongodb 19:45:47.79 INFO  ==> Advertised Hostname: my-release-mongodb-0.my-release-mongodb-headless.infra.svc.cluster.local
mongodb 19:45:47.79 INFO  ==> Advertised Port: 27017
realpath: /bitnami/mongodb/data/db: No such file or directory
mongodb 19:45:47.80 INFO  ==> Data dir empty, checking if the replica set already exists
MongoNetworkError: getaddrinfo ENOTFOUND my-release-mongodb-1.my-release-mongodb-headless.infra.svc.cluster.local
mongodb 19:45:49.08 INFO  ==> Pod name matches initial primary pod name, configuring node as a primary
mongodb 19:45:49.09 
mongodb 19:45:49.09 Welcome to the Bitnami mongodb container
mongodb 19:45:49.09 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 19:45:49.09 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 19:45:49.10 
mongodb 19:45:49.10 INFO  ==> ** Starting MongoDB setup **
mongodb 19:45:49.11 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 19:45:49.18 INFO  ==> Initializing MongoDB...
mongodb 19:45:49.20 INFO  ==> Deploying MongoDB from scratch...
MongoNetworkError: connect ECONNREFUSED 172.16.6.17:27017
mongodb 19:45:51.10 INFO  ==> Creating users...
mongodb 19:45:51.10 INFO  ==> Creating root user...
Current Mongosh Log ID: 6390ed70b1dfe0a264ad4cd6
Connecting to:          mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.6.0
Using MongoDB:          6.0.3
Using Mongosh:          1.6.0

**Clean Release and Persistent Volumes**

Failed Scenario 

```
helm install my-release --set auth.rootPassword=secretpassword -f values.prod-rs-deneme.yaml my-repo/mongodb
```
```
mongodbprodrepldeployment⚡ ⇒  kubectl get pods -l app.kubernetes.io/instance=my-release
NAME                   READY   STATUS    RESTARTS   AGE
my-release-0           1/1     Running   0          4m55s
my-release-1           1/1     Running   0          4m28s
**my-release-arbiter-0   1/1     Running   1          4m55s**
```

**Mongodb Primary POD Initial Logs**

mongodb 20:00:52.96 INFO  ==> Advertised Hostname: my-release-0.my-release-headless.infra.svc.cluster.local
mongodb 20:00:52.96 INFO  ==> Advertised Port: 27017
mongodb 20:00:52.96 INFO  ==> Pod name matches initial primary pod name, configuring node as a primary
mongodb 20:00:52.97 
mongodb 20:00:52.97 Welcome to the Bitnami mongodb container
mongodb 20:00:52.97 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 20:00:52.97 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 20:00:52.97 
mongodb 20:00:52.97 INFO  ==> ** Starting MongoDB setup **
mongodb 20:00:52.98 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 20:00:53.01 INFO  ==> Initializing MongoDB...
mongodb 20:00:53.01 INFO  ==> Deploying MongoDB with persisted data...
mongodb 20:00:53.01 INFO  ==> Writing keyfile for replica set authentication...
mongodb 20:00:53.02 INFO  ==> ** MongoDB setup finished! **

mongodb 20:00:53.03 INFO  ==> ** Starting MongoDB **
{"t":{"$date":"2022-12-07T20:00:53.049Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"enableLocalhostAuthBypass":{"default":true,"value":true}}}}


Also I added the values yaml file to the attachment by zip format, 

[values-yaml.zip](https://github.com/bitnami/charts/files/10179647/values-yaml.zip)

**Comment by emre141** [comment]
By the way I clean the release (release- pvc - pv - ebs volume ) afterthat just comment the configration block from values yaml then reuse same helm install command,

**commented lines**
```
#configuration: |
#  # mongod.conf
#  # for documentation of all options, see:
#  #   http://docs.mongodb.org/manual/reference/configuration-options/
#
#  # where and how to store data.
#  storage:
#    dbPath: /bitnami/mongodb/data/db
#    journal:
#      enabled: true
#    directoryPerDB: false
#    engine: wiredTiger
#    wiredTiger:
#      engineConfig:
#        cacheSizeGB: 2
#
#  # where to write logging data.
#  systemLog:
#    destination: file
#    quiet: false
#    logAppend: true
#    logRotate: reopen
#    path: /opt/bitnami/mongodb/logs/mongodb.log
#    verbosity: 0
#
#  # network interfaces
#  net:
#    port: 27017
#    unixDomainSocket:
#      enabled: true
#      pathPrefix: /opt/bitnami/mongodb/tmp
#    ipv6: false
#    bindIpAll: true
#    #bindIp:
#
#  # replica set options
#  replication:
#    replSetName: prodrs
#    enableMajorityReadConcern: true
#
#  # sharding options
#  #sharding:
#    #clusterRole:
#
#  # process management options
#  processManagement:
#     fork: false
#     pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
#
#  # set parameter options
#  setParameter:
#     enableLocalhostAuthBypass: true
#
#  # security options
#  security:
#    authorization: enabled
#    keyFile: /opt/bitnami/mongodb/conf/keyfile
# configuration: ""
## @section replicaSetConfigurationSettings settings applied during runtime (not via configuration file)
## If enabled, these are applied by a script which is called within setup.sh
## for documentation see https://docs.mongodb.com/manual/reference/replica-configuration/#replica-set-configuration-fields
## @param replicaSetConfigurationSettings.enabled Enable MongoDB(&reg;) Switch to enable/disable configuring MongoDB(&reg;) run time rs.conf settings
## @param replicaSetConfigurationSettings.configuration run-time rs.conf settings
##
```

```
helm install my-release --set auth.rootPassword=secretpassword -f values.prod-rs-deneme.yaml my-repo/mongodb
```
The result same
```
mongodbprodrepldeployment⚡ ⇒  kubectl get pods -l app.kubernetes.io/instance=my-release
NAME                   READY   STATUS    RESTARTS   AGE
my-release-0           1/1     Running   0          5m47s
my-release-1           1/1     Running   0          5m20s
my-release-arbiter-0   1/1     Running   1          5m47s
```
**Primary POD Log Output**

mongodb 20:11:35.02 INFO  ==> Advertised Hostname: my-release-0.my-release-headless.infra.svc.cluster.local
mongodb 20:11:35.02 INFO  ==> Advertised Port: 27017
mongodb 20:11:35.02 INFO  ==> Pod name matches initial primary pod name, configuring node as a primary
mongodb 20:11:35.03 
mongodb 20:11:35.03 Welcome to the Bitnami mongodb container
mongodb 20:11:35.03 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 20:11:35.03 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 20:11:35.03 
mongodb 20:11:35.03 INFO  ==> ** Starting MongoDB setup **
mongodb 20:11:35.04 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 20:11:35.07 INFO  ==> Initializing MongoDB...
mongodb 20:11:35.09 INFO  ==> Enabling authentication...
mongodb 20:11:35.09 INFO  ==> Deploying MongoDB with persisted data...
mongodb 20:11:35.10 INFO  ==> Writing keyfile for replica set authentication...
mongodb 20:11:35.12 INFO  ==> ** MongoDB setup finished! **

mongodb 20:11:35.13 INFO  ==> ** Starting MongoDB **
{"t":{"$date":"2022-12-07T20:11:35.149Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"enableLocalhostAuthBypass":{"default":true,"value":false}}}}

**Arbiter POD Log Output**

mongodbprodrepldeployment⚡ ⇒  k logs my-release-arbiter-0
mongodb 20:15:04.35 
mongodb 20:15:04.36 Welcome to the Bitnami mongodb container
mongodb 20:15:04.36 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 20:15:04.36 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 20:15:04.36 
mongodb 20:15:04.36 INFO  ==> ** Starting MongoDB setup **
mongodb 20:15:04.37 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 20:15:04.39 INFO  ==> Initializing MongoDB...
mongodb 20:15:04.41 INFO  ==> Deploying MongoDB from scratch...
MongoNetworkError: connect ECONNREFUSED 172.16.0.37:27017
mongodb 20:15:05.78 INFO  ==> Creating users...
mongodb 20:15:05.79 INFO  ==> Users created
mongodb 20:15:05.79 INFO  ==> Writing keyfile for replica set authentication...
mongodb 20:15:05.80 INFO  ==> Configuring MongoDB replica set...
mongodb 20:15:05.80 INFO  ==> Stopping MongoDB...
mongodb 20:15:09.28 INFO  ==> Trying to connect to MongoDB server my-release-0.my-release-headless.infra.svc.cluster.local...
mongodb 20:15:09.28 INFO  ==> Found MongoDB server listening at my-release-0.my-release-headless.infra.svc.cluster.local:27017 !
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.

I mean there are something broken the mongo installation while initial setup within values.yaml file but unfortunately I did not found it yet

**Comment by emre141** [comment]
Hi @CeliaGMqrz @fmulero 

Did you have a chance to had good time to test the case on your environment ?

**Comment by fmulero** [comment]
Sorry I haven't got the chance to revisit it yet. Could you compare your values files with the [default one](https://github.com/bitnami/charts/blob/main/bitnami/mongodb/values.yaml) and set only the values you are interested in?

**Comment by emre141** [comment]
Hi @fmulero 
No problem, I mean I have already shared the values file which I tried to install but failed, Let me share only difference part of the values

`fullnameOverride`
`namespaceOverride`
`commonLabels`
`bitnami/mongodb` tag `6.0.3-debian-11-r4`
`architecture`  = `replicaset`
`replicaSetKey` = `mongoprod`
`replicaSetName` = `prodrs`
`configuration`
```
configuration: |
  # mongod.conf
  # for documentation of all options, see:
  #   http://docs.mongodb.org/manual/reference/configuration-options/

  # where and how to store data.
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
    engine: wiredTiger
    wiredTiger:
      engineConfig:
        cacheSizeGB: 2

  # where to write logging data.
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0

  # network interfaces
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    bindIpAll: true
    #bindIp:

  # replica set options
  replication:
    replSetName: prodrs
    enableMajorityReadConcern: true

  # sharding options
  #sharding:
    #clusterRole:

  # process management options
  processManagement:
     fork: false
     pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid

  # set parameter options
  setParameter:
     enableLocalhostAuthBypass: true

  # security options
  security:
    authorization: enabled
    keyFile: /opt/bitnami/mongodb/conf/keyfile
```

`affinity`

```
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: name
            operator: NotIn
            values:
              - kube-system
          - key: currentness
            operator: NotIn
            values:
              - old
          - key: workload-type
            operator: In
            values:
              - mongo
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: product
                operator: In
                values:
                  - mongodbtest
          topologyKey: kubernetes.io/hostname

```

`tolerations`
```
  - key: "workload"
    operator: "Equal"
    value: "mongodb"
    effect: "NoSchedule"
  - key: "workload"
    operator: "Equal"
    value: "mongodb"
    effect: "NoExecute"
```
`request` and `limit`

```
  limits:
    cpu: 3
    memory: 30Gi
  ## Examples:
  ## requests:
  ##    cpu: 100m
  ##    memory: 128Mi
  ##
  requests:
    cpu: 100m
    memory: 1Gi
```
`storageClass` = `gp2-new`
`mountPath` = `/bitnami/mongodb/data/db`
`size` = `8Gi`

Rest of the defination same.
