### ISSUE TITLE
[bitnami/spark] Application Submission Instructions not clear

### ISSUE THREAD

**Issue by mxcolin** [bitnami/charts#13771]
### Name and Version

bitnami/spark

### What steps will reproduce the bug?

On installing this chart the instructions are displayed for submitting applications, however, this would only work for example applications, you need to get your own content onto the client pod, you are kinda left to your own devices unless you want to just use examples. So this requires you to customize the command that's given away from:

```
  kubectl run --namespace apache-spark apache-spark-client --rm --tty -i --restart='Never' \
    --image docker.io/bitnami/spark:3.3.1-debian-11-r5 \
    -- spark-submit --master spark://$SUBMIT_IP:$SUBMIT_PORT \
    --class org.apache.spark.examples.SparkPi \
    --deploy-mode cluster \
    $EXAMPLE_JAR 1000
```
You need to somehow get a mount or a PVC onto the client pod. Without it, it will never find anything other than the examples.

This for example:

```
kubectl run --namespace apache-spark apache-spark-client --rm --tty -i --restart='Never' --image docker.io/bitnami/spark:3.3.1-debian-11-r5 -- spark-submit --master spark://10.120.112.210:30077 /sparkdata/test.py
```

Won't work even if you configure the chart to mount a PVC with the test.py file available to the workers. There's no way to mount it to the client pod that gets created. So now you have to figure that out. The solution seems to be using overrides in your kubectl run command. This gets you a little further as now you can mount your own content but any combination of command and args flags to the spark-submit command just prints the usage information for spark-submit. This particular combination of command and args produces the error message: "Error: Unrecognized option: --master spark://10.105.180.230:7077"

```
kubectl run --namespace apache-spark apache-spark-client --rm --tty -i --restart='Never' \
--image docker.io/bitnami/spark:3.3.1-debian-11-r5 \
--overrides='
{
    "kind": "Pod",
    "apiVersion": "v1",
    "spec": {
        "containers": [
            {          
                "name": "apache-spark-client",
                "image": "docker.io/bitnami/spark:3.3.1-debian-11-r5",    
                "command": [ "spark-submit" ],
                "args": [ "--master spark://10.105.180.230:7077", "/sparkdata/test.py" ],            
                "volumeMounts": [ 
                    {
                        "mountPath": "/sparkdata",
                        "name": "spark-data"
                    }
                ]
            }
        ],
        "volumes": [
            {
                "name": "spark-data",
                "persistentVolumeClaim": {
                    "claimName": "spark-data"
                }
            }
        ]                  
    }               
}'
```

So as it stands I can run the examples and nothing more, obviously the intention is to be able to run your own content but it's not clear from any documentation how that would be possible.

### Are you using any custom parameters or values?

values-spark.yaml

```
service:
  type: NodePort
  nodePorts:
    cluster: 30077
    http: 30080
global:
  storageClass: sas
master:
  extraVolumes:
    - name: spark-data
      persistentVolumeClaim:
        claimName: spark-data
  extraVolumeMounts:
    - name: spark-data
      mountPath: '/sparkdata'
  resources:
    limits:
      memory: "2Gi"
      cpu: "1000m"
    requests:
      memory: "2Gi"
      cpu: "1000m"
worker:
  replicaCount: 3
  coreLimit: 2
  resources:
    limits:
      memory: "8Gi"
      cpu: "4000m"
    requests:
      memory: "2Gi"
      cpu: "1000m"
  extraVolumes:
    - name: spark-data
      persistentVolumeClaim:
        claimName: spark-data
  extraVolumeMounts:
    - name: spark-data
      mountPath: '/sparkdata'
```

### What is the expected behavior?

I'd expect some way to get your own content onto the driver pod and some documentation that show a Hello World example of getting the most basic of your own .py file launched in spark.

### What do you see instead?

Can only run the examples, no way to use your own content.
