### ISSUE TITLE
[bitnami/mongodb]When mongodb is in replicaset mode and external access is enabled, the member's ip configuration is incorrect.

### ISSUE THREAD

**Issue by sniperking1234** [bitnami/charts#13775]
### Name and Version

bitnami/mongodb 13.3.0

### What steps will reproduce the bug?

`helm install mongodb mongodb -ncommon -f values-test.yaml`

### Are you using any custom parameters or values?

values.yaml
```
global:
  imageRegistry: ""
  storageClass: juicefs-sc
image:
  repository: bitnami/mongodb
  tag: 6.0.2-debian-11-r1
architecture: replicaset
auth:
  enabled: true
  rootUser: root
  rootPassword: 1234qwer
replicaCount: 3
persistence:
  enabled: true
  size: 8Gi

externalAccess:
  enabled: true
  service:
    type: NodePort
    nodePorts:
    - 30100
    - 30101
    - 30102
```

### What is the expected behavior?

When executing the rs.conf() command，`member`config should be 
```
[
    {
      "_id": new NumberInt("0"),
      "host": "mongodb-0.mongodb-headless.common.svc.cluster.local:27017"
    },
    {
      "_id": new NumberInt("1"),
      "host": "mongodb-arbiter-0.mongodb-arbiter-headless.common.svc.cluster.local:27017"
    },
    {
      "_id": new NumberInt("2"),
      "host": "mongodb-0.mongodb-headless.common.svc.cluster.local:27017"
    },
    {
      "_id": new NumberInt("3"),
      "host": "mongodb-0.mongodb-headless.common.svc.cluster.local:27017"
    }
]
```

### What do you see instead?

But the actual `member` configuration is:
```
[
    {
      "_id": new NumberInt("0"),
      "host": "192.168.1.247:30100"
    },
    {
      "_id": new NumberInt("1"),
      "host": "mongodb-arbiter-0.mongodb-arbiter-headless.common.svc.cluster.local:27017"
    },
    {
      "_id": new NumberInt("2"),
      "host": "192.168.1.246:30101"
    },
    {
      "_id": new NumberInt("3"),
      "host": "192.168.1.245:30102"
    }
]
```
192.168.1.245, 192.168.1.246, 192.168.1.247, these three ip addresses are the ip of the k8s node.
