### ISSUE TITLE
[bitnami/minio] "The Access Key Id you provided does not exist in our records" after Docker image upgrade.

### ISSUE THREAD

**Issue by ldvy** [bitnami/charts#13788]
### Name and Version

bitnami/minio not.sure

### What steps will reproduce the bug?

1. Deployed MinIO using the helm chart to my k8s cluster around five months ago, and everything worked fine
2. Changed the Docker image in the deployment from `docker.io/bitnami/minio:2021.6.17-debian-10-r57 ` to `docker.io/bitnami/minio:2022.9.25-debian-11-r1` 
This specific version was chosen due to [this](https://github.com/bitnami/charts/issues/13245) bug I've encountered with newer versions.
3. After the MinIO service came to life, I noticed that my applications started throwing the following error upon attempting to connect to MinIO: "The Access Key Id you provided does not exist in our records"
4. Attempted to log in to the MinIO web console using the access and secret keys specified in the deployment but got the same error.

### Are you using any custom parameters or values?

In my deployment, I supplied environment variables "MINIO_ACCESS_KEY" and "MINIO_SECRET_KEY" containing the actual keys.
```yaml
- name: MINIO_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      key: access-key
      name: minio
- name: MINIO_SECRET_KEY
  valueFrom:
    secretKeyRef:
      key: secret-key
      name: minio
```

I checked the "minio" secret in k8s, and it does have values for both keys.

### What is the expected behavior?

Application to be able to use the MinIO service,
MinIO web console to allow me to log in using the configured credentials.

### What do you see instead?

"The Access Key Id you provided does not exist in our records" error is thrown.

### Additional information

I am pretty unfamiliar with how MinIO itself works, so might've missed something.
I would appreciate any help with this issue!
