### ISSUE TITLE
[bitnami/redis] Set sysctls via pod security context

### ISSUE THREAD

**Issue by rjasper-frohraum** [bitnami/charts#1379]
**Which chart**:

chart: redis 
version: 9.1.3

**Description**

It would be nice to have an option to set the sysctls in the `securityContext` of the master and slave pods. This way it would not be necessary to create a privileged init container to set sysctls. Would it be possible to implement a value parameter like `securityContext.sysctls`? In `values.yml` you could then write something like:

```yaml
securityContext:
  sysctls:
    - name: net.core.somaxconn
      value: "10000"
```

I could also provide a PR.
