### ISSUE TITLE
Solr xProbes have duplicated values

### ISSUE THREAD

**Issue by jam01-lb** [bitnami/charts#13793]
### Name and Version

bitnami/solr 6.3.2

### What steps will reproduce the bug?

1. Using with the given values.yaml below
2. `helm install solr bitnami/solr --dry-run --debug -f values.yaml`
3. All probes in StatefulSet have the entries duplicated as shown below

### Are you using any custom parameters or values?

```yaml
    auth:
      enabled: true
      existingSecret: solr
    collection: 'example'
    coreNames: ['example']
    volumePermissions:
      enabled: true
    persistence:
      enabled: true
      existingClaim: solr-data
    cloudEnabled: false
    zookeeper:
      enabled: false
```

### What is the expected behavior?

No duplicated values

### What do you see instead?

```yaml
            failureThreshold: 6
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
            initialDelaySeconds: 60
            timeoutSeconds: 15
            failureThreshold: 6
            periodSeconds: 10
            successThreshold: 1
```

### Additional information

Attempting a release with the specified values results in an error because of the duplicated entries.
