### ISSUE TITLE
[mariadb-galera] Upscaling a cluster fails if data cannot be synced within readiness probe window

### ISSUE THREAD

**Issue by jbrinksmeier** [bitnami/charts#13801]
### Name and Version

bitnami/mariadb-galera

### What steps will reproduce the bug?

Create a cluster with 3 nodes. Add data (we have ~20GB). Scale up the stateful set to 5 nodes. Before getting ready, wsrep starts syncing, which takes longer than 60 seconds to complete. Because of this the readiness probe never succeeds and the new pods keep restarting. 

### Are you using any custom parameters or values?

values.yml:

```yaml
existingSecret: mariadb-secrets
replicaCount: 3
nodeSelector:
  role: mariadb
global:
  storageClass: block-storage
galera:
  name: galera
  mariabackup:
    forcePassword: true

rootUser:
  forcePassword: true

db:
  user: my-user
  forcePassword: true
  name: my-database

persistence:
  size: 50Gi
```

### What is the expected behavior?

The readiness probe cannot be edited in a stateful set, hence this cluster is unable to scale up without first recreating the statefulset (which is downtime) with readinessprobe disabled.
Is there any way you know of to scale up without having to delete the statefulset first?

### What do you see instead?

The new node starts syncing and is killed in the process
