### ISSUE TITLE
[bitnami/redis] No change in size pv

### ISSUE THREAD

**Issue by MrKribel** [bitnami/charts#13813]
### Name and Version

redis:latest

### What steps will reproduce the bug?

I am trying to change the default pv 8gb to 2gb.

`helm install  redis-cluster bitnami/redis -f redis/values.yaml  -n redis`

My values:

```
global:
  redis:
    password: "myredispassword"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: "prometheus"

master:
  persistence:
    enabled: false

slave:
  persistence:
    enabled: false

sentinel:
  enabled: true
  downAfterMilliseconds: 600

cluster:
  enabled: true
  slaveCount: 3  

persistence:
    size: 2Gb
```

But it doesn't work. I still have a pv of 8 gb...

How do I resize? And how enable data overwrite mode if the pv is completely full?

### What do you see instead?

I don't know how to do it.
