### ISSUE TITLE
[bitnami/external-dns] Add Vault Secret injection (at least for AWS)

### ISSUE THREAD

**Issue by vitali-federau-fivestars** [bitnami/charts#13837]
### Name and Version

bitnami/external-dns 6.12.0

### What is the problem this feature will solve?

Currently I am not able anyhow inject access_key and secret_key to the external-dns from Vault. According to the templates code, credentials section being pushed directly by mounting data from values to the credentials file, avoiding appearing in ConfigMap that doesn't allow to parse values with Vault, example of helm how ideally it could/should work:
```
podAnnotations:
          vault.security.banzaicloud.io/vault-addr: addr
          vault.security.banzaicloud.io/vault-path: kubernetes
          vault.security.banzaicloud.io/vault-role: role
          vault.security.banzaicloud.io/vault-tls-secret: vault-tls
        serviceAccount:
          create: true
          name: role
        aws:
          credentials:
            accessKey: vault:secret/data/secret#access_key#1
            secretKey: vault:secret/data/secret#secret_key#1
          preferCNAME: true
```

### What is the feature you are proposing to solve the problem?

To add aws access_key and secret_key to configMap and to get values to deployment from ConfigMap

### What alternatives have you considered?

Tried to use injection with env variables like:
```
aws:
          credentials:
            accessKey: $AWS_ACCESS_KEY_ID
            secretKey: $AWS_SECRET_ACCESS_KEY
          preferCNAME: true
        extraEnvVars:
          - name: AWS_ACCESS_KEY_ID
            value: vault:secret/data/secret#access_key#1
          - name: AWS_SECRET_ACCESS_KEY
            value: vault:secret/data/secret#secret_key#1
```

Didn't work
