### ISSUE TITLE
[bitnami/external-dns] CNAME records are not being created while preferCNAME: true

### ISSUE THREAD

**Issue by vitali-federau-fivestars** [bitnami/charts#13850]
### Name and Version

bitnami/external-dns 6.12.0

### What steps will reproduce the bug?

Have next config:
```
       sources:
          - service
        zoneIdFilters: [
          123123123
        ]
        txtPrefix: "external-dns-"
        aws:
          preferCNAME: true
        policy: upsert-only
```
Should create CNAME records in Route53, but no matter what value I pass to preferCNAME (true or false) I always have A record: 
```
time="2022-12-06T23:23:15Z" level=info msg="Desired change: CREATE record.vitali.dev.company.com A [Id: /hostedzone/123123123]"
time="2022-12-06T23:23:15Z" level=info msg="Desired change: CREATE external-dns-a-record.vitali.dev.company.com TXT [Id: /hostedzone/1231231231]"
time="2022-12-06T23:23:15Z" level=info msg="Desired change: CREATE external-dns-record.vitali.dev.company.com TXT [Id: /hostedzone/12312312123]"
```

### Are you using any custom parameters or values?

Only these 
```
       sources:
          - service
        zoneIdFilters: [
          123123123
        ]
        txtPrefix: "external-dns-"
        aws:
          preferCNAME: true
        policy: upsert-only
```

### What is the expected behavior?

CNAME record should be created instead of A record

### What do you see instead?

A record is created for all the applications
