### ISSUE TITLE
[bitnami/ghost] Error when deploying Ghost on subpath

### ISSUE THREAD

**Issue by AliMirlou** [bitnami/charts#13867]
### Name and Version

bitnami/ghost 19.1.44

### What steps will reproduce the bug?

I installed the bitnami/ghost helm chart on a subpath of a domain in a Kubernetes with Nginx Ingress and cert-manager. My values and configurations are added below.

### Are you using any custom parameters or values?

```yaml
global:
  storageClass: openebs-hostpath-retain
ghostUsername: admin
existingSecret: ghost-secret
ghostEmail: admin@domain.com
ghostBlogTitle: My Blog
ghostHost: domain.com
ghostPath: /blog
ghostEnableHttps: true
allowEmptyPassword: false
service:
  type: ClusterIP
mysql:
  auth:
    existingSecret: ghost-mysql
```

### What is the expected behavior?

The expected behavior is that the Ghost pod to go into `Ready` state with a similar log to this:

```
ghost 15:00:36.94
ghost 15:00:36.94 Welcome to the Bitnami ghost container
ghost 15:00:36.94 Subscribe to project updates by watching https://github.com/bitnami/containers
ghost 15:00:36.94 Submit issues and feature requests at https://github.com/bitnami/containers/issues
ghost 15:00:36.95
ghost 15:00:36.95 INFO  ==> Configuring libnss_wrapper
ghost 15:00:36.97 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
ghost 15:00:37.00 INFO  ==> Ensuring Ghost directories exist
ghost 15:00:37.00 INFO  ==> Trying to connect to the database server
ghost 15:00:57.04 INFO  ==> Configuring database
ghost 15:00:57.08 INFO  ==> Setting up Ghost
ghost 15:00:57.93 INFO  ==> Configuring Ghost URL to https://domain.com/blog
ghost 15:00:57.97 INFO  ==> Passing admin user creation wizard
ghost 15:00:57.97 INFO  ==> Starting Ghost in background
ghost 15:07:07.40 INFO  ==> Stopping Ghost
ghost 15:07:08.13 INFO  ==> Persisting Ghost installation

ghost 15:07:08.22 INFO  ==> ** Ghost setup finished! **
ghost 15:07:08.24 INFO  ==> ** Starting Ghost **

Love open source? We’re hiring JavaScript Engineers to work on Ghost full-time.
https://careers.ghost.org

- Inspecting operating system
```

### What do you see instead?

The pod crashes with the following error:

```
ghost 15:00:36.94
ghost 15:00:36.94 Welcome to the Bitnami ghost container
ghost 15:00:36.94 Subscribe to project updates by watching https://github.com/bitnami/containers
ghost 15:00:36.94 Submit issues and feature requests at https://github.com/bitnami/containers/issues
ghost 15:00:36.95
ghost 15:00:36.95 INFO  ==> Configuring libnss_wrapper
ghost 15:00:36.97 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
ghost 15:00:37.00 INFO  ==> Ensuring Ghost directories exist
ghost 15:00:37.00 INFO  ==> Trying to connect to the database server
ghost 15:00:57.04 INFO  ==> Configuring database
ghost 15:00:57.08 INFO  ==> Setting up Ghost
ghost 15:00:57.93 INFO  ==> Configuring Ghost URL to https://domain.com/blog
ghost 15:00:57.97 INFO  ==> Passing admin user creation wizard
ghost 15:00:57.97 INFO  ==> Starting Ghost in background
ghost 15:01:10.26 ERROR ==> An error occurred while installing Ghost
```

### Additional information

My Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
```

I'm using Nginx Ingress Controller and configured the Ingress object myself:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: site
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: domain.com
    http:
      paths:
      - backend:
          service:
            name: frontend-service
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
      - backend:
          service:
            name: ghost
            port:
              name: https
        path: /blog
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - domain.com
    secretName: site-tls
```
