### ISSUE TITLE
[bitnami/kafka] Listener not created correctly when using an empty array

### ISSUE THREAD

**Issue by jseparovic** [bitnami/charts#13868]
### Name and Version

bitnami/kafka:3.3.1-debian-11-r1

### What steps will reproduce the bug?

Swap the client and the external ports around like so:
```
  ports:
    client: 9094
    internal: 9093
    external: 9092
```
The listener should also swap these ports but it doesn't. It remains default.
Advertised listener is fine.

### What is the expected behavior?

listeners:
  - INTERNAL://:9093
  - CLIENT://:9094
  - EXTERNAL://:9092

### What do you see instead?

listeners:
  - INTERNAL://:9093
  - CLIENT://:9092
  - EXTERNAL://:9094

**Comment by fmulero** [comment]
Hi @jseparovic, Thanks for sharing your concerns but I am not sure what do you mean.

In the `values.yml` file we have different  values to set the listener ports:
```yaml
## @param containerPorts.client Kafka client container port
## @param containerPorts.internal Kafka inter-broker container port
## @param containerPorts.external Kafka external container port
##
containerPorts:
  client: 9092
  internal: 9093
  external: 9094
...
## Service parameters
##
service:
  ## @param service.ports.client Kafka svc port for client connections
  ## @param service.ports.internal Kafka svc port for inter-broker connections
  ## @param service.ports.external Kafka svc port for external connections
  ##
  ports:
    client: 9092
    internal: 9093
    external: 9094
...
```

`service.ports` set the ports in the exposed service, if you want change the listeners in the container side you have to set the `containerPorts` value.

**Comment by jseparovic** [comment]
Yes, so I have swapped client and external ports like so:
```
## @param containerPorts.client Kafka client container port
## @param containerPorts.internal Kafka inter-broker container port
## @param containerPorts.external Kafka external container port
##
containerPorts:
  client: 9094
  internal: 9093
  external: 9092
service:
  ## @param service.ports.client Kafka svc port for client connections
  ## @param service.ports.internal Kafka svc port for inter-broker connections
  ## @param service.ports.external Kafka svc port for external connections
  ##
  ports:
    client: 9094
    internal: 9093
    external: 9092
```

With this configuration, the advertisedListeners are correct, however the listeners are not. The listeners remain the same as the original configuration. Seems to be some issue with the listener auto-calculation.

To get my setup to work properly I had to add the following:
```
## @param listeners The address(es) the socket server listens on. Auto-calculated it's set to an empty array
## When it's set to an empty array, the listeners will be configured
## based on the authentication protocols (auth.clientProtocol, auth.externalClientProtocol and auth.interBrokerProtocol parameters)
##
listeners:
  - INTERNAL://:9093
  - CLIENT://:9094
  - EXTERNAL://:9092
```

However from the listener comment, I should not have to do this, it should be auto-calculated with an empty array.
