### ISSUE TITLE
[bitnami/keycloak] Adding a custom theme to Keycloak is not working

### ISSUE THREAD

**Issue by Abhiram-RK** [bitnami/charts#13864]
### Name and Version

bitnami/keycloak:19.0.3

### What steps will reproduce the bug?

```
initContainers: |
  - name: theme-provider
    image: image/keycloaktheme:latest
    imagePullPolicy: Always
    command:
      - sh
    args:
      - -c
      - |
        echo "Copying theme..."
        cp -R /themes/default/* /theme
    volumeMounts:
      - name: theme
        mountPath: /theme

extraVolumeMounts: |
  - name: theme
    mountPath: /opt/jboss/keycloak/themes/theme

extraVolumes: |
  - name: theme
    emptyDir: {}
```

After updating values.yaml like this we didn't get a custom theme from Keyclock

### Are you using any custom parameters or values?

using `values.yaml`

### What do you see instead?

Please provide us with the correct values.yaml configuration to add a custom theme to Keycloak
