### ISSUE TITLE
[bitnami/thanos] helm chart do not have auto-downsampling section under query

### ISSUE THREAD

**Issue by sreekanthm** [bitnami/charts#13872]
### Name and Version

bitnami/thanos 9.0.0

### What is the problem this feature will solve?

I use bitnami thanos helm chart for grafana dashboard, and I want to enable "auto-downsampling" to see 1 year data in grafana. I had already configured 
```yaml
retentionResolutionRaw: 90d
retentionResolution5m: 90d
retentionResolution1h: 365d
```
To enable auto-downsampling, I had added code like this helm chart value.yaml

```yaml
query:
  extraFlags:
    - auto-downsampling:1hr      
  dnsDiscovery:
    enabled: false
  replicaLabel:
    - replica 
    - prometheus_replica  
```
in the default helm chart do not have "auto-downsampling" section so I have added under extraFlags but it is not working, Can you please guide me here

### What is the feature you are proposing to solve the problem?

Is it possible to add "auto-downsampling" under query like "replica-label", If not possible, how to enable auto-downsampling in thanos helm chart
