### ISSUE TITLE
[bitnami/pinniped] Reused nodePorts for two services

### ISSUE THREAD

**Issue by ecklm** [bitnami/charts#13875]
### Name and Version

bitnami/pinniped 0.4.6

### What steps will reproduce the bug?

1. In a kubeadm setup kubernetes cluster
2. I have the nodePort range set to 49000-49100
3. With the values yaml provided below
4. I run `helm upgrade --install --values helm-values.yml --version=0.4.6 pinniped-authenticator bitnami/pinniped`

### Are you using any custom parameters or values?
```yaml
concierge:
  enabled: true
  replicaCount: 2
  # TODO
  resources:
    limits: {}
    requests: {}

supervisor:
  enabled: true
  replicaCount: 2

  # TODO
  resources:
    limits: {}
    requests: {}

  service:
    type: NodePort
    nodePorts:
      https: "49000"
```

### What is the expected behavior?

I expect the installation to succeed with a defined nodePort for the supervisor service.

### What do you see instead?

The installation fails because nodePort 49000 is already in use.
```console
$ helm upgrade --install --values helm-values.yml --version=0.4.6 pinniped-authenticator bitnami/pinniped 
Release "pinniped-authenticator" does not exist. Installing it now.
Error: Service "pinniped-authenticator-supervisor-api" is invalid: spec.ports[0].nodePort: Invalid value: 49000: provided port is already allocated
```

```console
$ kubectl get svc
NAME                                                          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
pinniped-authenticator-concierge                              ClusterIP   10.103.36.71     <none>        443/TCP         70s
pinniped-authenticator-concierge-pinniped-authenticator-api   ClusterIP   10.103.213.9     <none>        443/TCP         70s
pinniped-authenticator-supervisor                             NodePort    10.104.181.158   <none>        443:49000/TCP   70s
```

### Additional information

I have investigated the problem, and I think it is that two service definitions use the same configuration from the values file.
* https://github.com/bitnami/charts/blob/main/bitnami/pinniped/templates/supervisor/service-api.yaml#L51
* https://github.com/bitnami/charts/blob/main/bitnami/pinniped/templates/supervisor/service.yaml#L51

In fact, based on the services included in the deployment based on pinnipads own documentation (see below), I think the `.Values.supervisor.service` should be broken up into two, because separate parameters of it correspond to two different services.

---

The original service definition looks like this:
```yaml
# Included in the manifest at https://get.pinniped.dev/v0.20.0/install-pinniped-supervisor.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: pinniped-supervisor-api
  namespace: pinniped-supervisor
  labels:
    app: pinniped-supervisor
  annotations:
    kapp.k14s.io/disable-default-label-scoping-rules: ""
spec:
  type: ClusterIP
  selector:
    deployment.pinniped.dev: supervisor
  ports:
  - protocol: TCP
    port: 443
    targetPort: 10250

# Suggested by the documentation, done by me
---
apiVersion: v1
kind: Service
metadata:
  name: pinniped-supervisor-loadbalancer
  # Assuming that this is the namespace where the Supervisor was installed.
  # This is the default.
  namespace: pinniped-supervisor
spec:
  type: NodePort
  selector:
    # Assuming that this is how the Supervisor Pods are labeled.
    # This is the default.
    app: pinniped-supervisor
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443  # 8443 is the TLS port.
    nodePort: 49000
```

**Comment by ecklm** [comment]
By running `helm template --values helm-values.yml --version=0.4.6 pinniped-authenticator bitnami/pinniped` with the same helm-values file, I get the following services.

```yaml
---
# Source: pinniped/templates/supervisor/service-api.yaml
apiVersion: v1
kind: Service
metadata:
  name: pinniped-authenticator-supervisor-api
  namespace: "pinniped-authenticator"
  labels:
    app.kubernetes.io/name: pinniped
    helm.sh/chart: pinniped-0.4.6
    app.kubernetes.io/instance: pinniped-authenticator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: pinniped
    app.kubernetes.io/component: supervisor
spec:
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: "Cluster"
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 10250
      nodePort: 49000
  selector:
    app.kubernetes.io/name: pinniped
    app.kubernetes.io/instance: pinniped-authenticator
    app.kubernetes.io/component: supervisor

---
# Source: pinniped/templates/supervisor/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pinniped-authenticator-supervisor
  namespace: "pinniped-authenticator"
  labels:
    app.kubernetes.io/name: pinniped
    helm.sh/chart: pinniped-0.4.6
    app.kubernetes.io/instance: pinniped-authenticator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: pinniped
    app.kubernetes.io/component: supervisor
spec:
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: "Cluster"
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      nodePort: 49000
  selector:
    app.kubernetes.io/name: pinniped
    app.kubernetes.io/instance: pinniped-authenticator
    app.kubernetes.io/component: supervisor

```
