### ISSUE TITLE
[kube-prometheus] Error loading config/ parsing YAML file/ empty duration string

### ISSUE THREAD

**Issue by viceice** [bitnami/charts#13874]
### Name and Version

bitnami/kube-prometheus 8.2.1

### What steps will reproduce the bug?

1. deploy chart v8.2.1+
2. see error and restarting prometheus pod

### Are you using any custom parameters or values?

```yml
#PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
rbac:
  pspEnabled: false

node-exporter:
  rbac:
    pspEnabled: false

  serviceMonitor:
    relabelings:
      - action: replace
        regex: (.*)
        replacement: $1
        sourceLabels:
          - __meta_kubernetes_pod_node_name
        targetLabel: kubernetes_node
      - action: replace
        regex: (.*)
        sourceLabels:
          - __meta_kubernetes_endpoint_node_name
        targetLabel: node

kubelet:
  serviceMonitor:
    metricRelabelings:
      - action: replace
        sourceLabels:
          - node
        targetLabel: instance

kube-state-metrics:
  rbac:
    pspEnabled: false

  serviceMonitor:
    honorLabels: true
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

operator:
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

prometheus:
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

alertmanager:
  enabled: false # currently unused
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

grafana:
  enabled: false
```

### What is the expected behavior?

pod starts

### What do you see instead?

constantly restarting pod with error
```
ts=2022-12-08T15:57:10.586Z caller=main.go:468 level=error msg="Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)" file=/etc/prometheus/config_out/prometheus.env.yaml err="parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: empty duration string"
```

### Additional information

- #13621

It seems the prometheus update from `v2.39.1` to `v.40.2`  broke something

**Comment by viceice** [comment]
it seems setting these values fixes the issue:
```yml
prometheus:
  scrapeInterval: 1m
  evaluationInterval: 1m
```
