### ISSUE TITLE
Add more options to securityContext override for nginx containers

### ISSUE THREAD

**Issue by omarkalloush** [bitnami/charts#13881]
### Name and Version

bitnami/nginx 13.2.14

### What is the problem this feature will solve?

For highly regulated environments using security policies it is useful that containers allow overrides for securityContext, for example if I wanna add capabilities and privileged options.

### What is the feature you are proposing to solve the problem?

Maybe adding something like this would help:
```
containerSecurityContext:
  enabled: true
  runAsUser: 0
  runAsNonRoot: false
  privileged: true
  capabilities:
    add: ["SYS_ADMIN"]
```
