### ISSUE TITLE
[rabbitmq] Can not access cluster from Job

### ISSUE THREAD

**Issue by kvokka** [bitnami/charts#13919]
### Name and Version

bitnami/rabbitmq:11.2.0

### What steps will reproduce the bug?

The goal is to create extra users (besides the default one) with chart installation, to make it I'm running `batch.Job` as an extra resource in the `templates` folder, which can not access the cluster. There is no problem accessing the cluster from the StatefulSet pod, but the way to create extra resources in there is to use `lifeHooks.postStart` and wait, which is dirty.

I'm definitely missing something but after spending a while with different attempts, I just do not know where else I can ask.

### Are you using any custom parameters or values?

```yaml
rabbitmq:
  auth:
    username: admin
    existingPasswordSecret: rabbitmq-admin
    existingErlangSecret:   rabbitmq-admin

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  extraContainerPorts: |
    {{- range $port := untilStep 35672 35683 1 }}
    - name: port-{{ $port }}
      containerPort: {{ $port }}
    {{- end }}
```

### What do you see instead?

In the job pod logs I see:

```
Most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

In addition to the diagnostics info below:

 * See the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more
 * Consult server logs on node rabbit@rabbitmq
 * If target node is configured to use long node names, don't forget to use --longnames with CLI tools

DIAGNOSTICS
===========

attempted to contact: [rabbit@rabbitmq]

rabbit@rabbitmq:
  * connected to epmd (port 4369) on rabbitmq
  * epmd reports node 'rabbit' uses port 25672 for inter-node and CLI tool traffic
  * TCP connection succeeded but Erlang distribution failed
  * suggestion: check if the Erlang cookie is identical for all server nodes and CLI tools
  * suggestion: check if all server nodes and CLI tools use consistent hostnames when addressing each other
  * suggestion: check if inter-node connections may be configured to use TLS. If so, all nodes and CLI tools must do that
   * suggestion: see the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more


Current node details:
 * node name: 'rabbitmqcli-685-rabbit@my-shell'
 * effective user's home directory: /var/lib/rabbitmq
 * Erlang cookie hash: YxabQGjXopvxkIq3W8Sncg==
```

At the same time cluster operates normally.

### Additional information

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ list .Chart.Name "create-users" ( date "20060102150405" .Release.Time ) | join "-" }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    component: {{ .Chart.Name }}
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 1800
  template:
    spec:
      # granted extra possible rights to chart SA, no luck
      serviceAccountName: {{ template "rabbitmq.serviceAccountName" . }}
      containers:
      - name: main
        image: {{ template "rabbitmq.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: [ "/bin/bash", "-c", "--" ]
        args:
          - |
            # also tried to access some node directly with `rabbitctl -n rabbit@rabbitmq-0 ...`
            # and `rabbitmqctl n rabbit@rabbitmq-0  await_startup` and tons of other combinations 
            rabbitmqctl -n rabbit@rabbitmq await_online_nodes {{ .Values.rabbitmq.replicaCount }}
        # This is the part of a desperate try, it should be unnecessary 
        ports:
          - name: amqp
            containerPort: {{ .Values.rabbitmq.containerPorts.amqp }}
          - name: dist
            containerPort: {{ .Values.rabbitmq.containerPorts.dist }}
          - name: stats
            containerPort: {{ .Values.rabbitmq.containerPorts.manager }}
          - name: epmd
            containerPort: {{ .Values.rabbitmq.containerPorts.epmd }}
          {{- range $port := untilStep 35672 35683 1 }}
          - name: port-{{ $port }}
            containerPort: {{ $port }}
          {{- end }}
        env:
          - name: RABBITMQ_ERL_COOKIE
            valueFrom:
              secretKeyRef:
                name: {{ template "rabbitmq.secretErlangName" . }}
                key: rabbitmq-erlang-cookie
        volumeMounts:
        - name: configuration
          mountPath: /bitnami/rabbitmq/conf
      volumes:
      - name: configuration
        secret:
          secretName: {{ printf "%s-config" (include "common.names.fullname" .) }}
          items:
            - key: rabbitmq.conf
              path: rabbitmq.conf
            {{- if .Values.advancedConfiguration }}
            - key: advanced.config
              path: advanced.config
            {{- end }}
```

**Comment by tbnguyen1407** [comment]
I think for user provisioning you should mount a json definitions file containing the users and configure RabbitMQ to load the definitions instead.

```
~ values.yaml ~

extraConfiguration: |-
  ## load definitions
  load_definitions = /mydefinitions/..data

extraVolumes:
  - name: mydefinitions
    secret:
      secretName: rabbitmq-definitions-secret

extraVolumeMounts:
  - name: mydefinitions
    mountPath: /mydefinitions
```
