### ISSUE TITLE
how to resize the PVC with helm

### ISSUE THREAD

**Issue by user2893** [bitnami/charts#13927]
### Name and Version

bitnami/redis

### What steps will reproduce the bug?

Please help me understand how to change the pvc value in redis HA cluster...

after command: `helm install redis-sentinel bitnami/redis --values values.yaml `
I get a disk size of 8GB:

```
NAME                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
redis-data-redis-sentinel-node-0   Bound    pvc-933f75c2-3290-4921-949d-5c2c3894b6a9   8Gi        RWO            standard       5m16s
redis-data-redis-sentinel-node-1   Bound    pvc-96d1ca03-aa6d-445b-bab9-f8ea1bef53a2   8Gi        RWO            standard       4m52s
redis-data-redis-sentinel-node-2   Bound    pvc-192063f2-e20e-4acd-82ef-3215610a19d1   8Gi        RWO            standard       4m25s
```

### Are you using any custom parameters or values?

my value.yaml:

```
auth:
  enabled: false

metrics:
  enabled: true

master:
  persistence:
    enabled: false
    size: 1Gi

slave:
  persistence:
    enabled: false
    size: 1Gi

sentinel:
  enabled: true
  downAfterMilliseconds: 600
  automateClusterRecovery: true
```

### What do you see instead?

What am I doing wrong?
