### ISSUE TITLE
[bitnami/mariadb] Can't create/write to /opt/bitnami/mariadb/tmp whithout privilege escalation

### ISSUE THREAD

**Issue by bauerjs1** [bitnami/charts#13942]
### Name and Version

bitnami/mariadb 11.4.1

### What steps will reproduce the bug?

Launch a mariadb instance without privilege escalation allowed (I suppose that is the reason for the crashing, since that is what I've changed from the defaults)

### Are you using any custom parameters or values?

```yaml
auth:
  ...

primary:
  resources:
    ...
  persistence:
    ...

  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    privileged: false
    allowPrivilegeEscalation: false
```

### What is the expected behavior?

Mariadb should be running fine without privilege escalation. It would be nice to have this set by default in all of the `containerSecurityContext`s

### What do you see instead?

The instance starts successfully in the first place (iirc), but fails as soon as it attempts to write to /opt/bitnami/mariadb/tmp and continues crash-looping from there

### Additional information

Since `primary.podSecurityContext.fsGroup` already defaults to `1001`, a possible solution is adding an `emtyDir` volume for this tmp directory to make it user-writable.

My current workaround:
```yaml
primary:
  # this tmp directory must be user-writable
  extraVolumes:
    - name: tmp
      emptyDir: {}
  extraVolumeMounts:
    - name: tmp
      mountPath: /opt/bitnami/mariadb/tmp
```
