### ISSUE TITLE
[bitnami/redis] in redis sentinel Headless service makes no distinction between write and read traffic

### ISSUE THREAD

**Issue by farhadkh000** [bitnami/charts#13952]
### Name and Version

Bitnami/redis 17.3.8

### What steps will reproduce the bug?

1) I have a Kuber cluster version 1.25.3 in that I implemented a three-node cluster in Kuber by Helm Chart and using the `sentinel.enabled=true` feature.
2) Both Redis and Sentinel applications were launched in one pod, one pod has the role of master and the other two have the role of slave.
Normal service and headless service have been launched for both ports.
3) I published both services on their own ports by ingress.
4) No separation is done for Read/Write traffic at the service layer or ...

### Are you using any custom parameters or values?

I change this parameter in file values.yaml:
```yaml
  resources:
    limits:
      cpu: 500m
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 1000Mi
    ## @param master.persistence.storageClass Persistent Volume storage class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner
    ##
    storageClass: "rook-ceph-block-ext"
    ## @param master.persistence.size Persistent Volume size
    ##
    size: 1Gi
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 500m
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 1000Mi
    ## @param replica.persistence.storageClass Persistent Volume storage class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner
    ##
    storageClass: "rook-ceph-block-ext"
    ##
    accessModes:
      - ReadWriteOnce
    size: 1Gi
sentinel:
  ##
  enabled: true
  ##sentinel.masterSet Master set name
  ##
  masterSet: master
```
this my config for ingress :
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: redis
  namespace: redis-sentinel-true
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  entryPoints:
    - "redis"
  routes:
  - match: HostSNI(`*`)
    services:
      - name: redis-sentinel-true-headless
        namespace: redis-sentinel-true
        port: 6379
---------------
kind: IngressRouteTCP
metadata:
  name: sentinel
  namespace: redis-sentinel-true
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  entryPoints:
    - "sentinel"
  routes:
  - match: HostSNI(`*`)
    services:
      - name: redis-sentinel-true-headless
        namespace: redis-sentinel-true
        port: 26379
```

### What is the expected behavior?

I expect that there is a way to separate the write traffic from the read traffic so that when I write from outside the Kubernetes cluster, the request goes to the pod that has the role of master.
I can do this by defining the selector in the headless service for podmaster but with it gone and the role of the master is transferred to another pod, there is a problem again.

### What do you see instead?

When I connect to Redis from outside the cluster Kubernetes, write requests are sent to all pods, and it is successful only if sent to the pod that has the master role. 
I use one IP address for ingress and I have opened both ports 6379 and 26379.
When I try to cache data with Python, it is only successful if the traffic goes to the pod with the master role
Of course, I didn't manage to get the master address with Python code, although I'm sure its address in the Kubernetes cluster is "redis-sentinel-true-node-2.redis-sentinel-true-headless.redis-sentinel-true.svc.cluster.local" it is.
And it cannot be used in the code outside the cluster Kubernetes.
```
					  10.56.149.131:6379 
					  10.56.149.131:26379
                                     ---------------------------
				        traefik ingress
			             ---------------------------
				    			|
							|
							|
				  ---------------------------------
				  service headless port 6379,26379
				  ---------------------------------
						|		|
						|		|
			       	  POD-1   |   POD-3  |  POD-3 
	 				        |		|
```
### Additional information
```console
$ k get all -n redis-sentinel-true  -o wide
NAME                             READY   STATUS    RESTARTS   AGE   IP              NODE           NOMINATED NODE   READINESS GATES
pod/redis-sentinel-true-node-0   2/2     Running   0          13h   20.20.152.14    kubeworker02   <none>           <none>
pod/redis-sentinel-true-node-1   2/2     Running   0          26h   20.20.26.245    kubeworker03   <none>           <none>
pod/redis-sentinel-true-node-2   2/2     Running   0          26h   20.20.251.141   kubeworker01   <none>           <none>

NAME                                   TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)              AGE   SELECTOR
service/redis-sentinel-true            ClusterIP   10.110.138.1   <none>        6379/TCP,26379/TCP   26h   app.kubernetes.io/component=node,app.kubernetes.io/instance=redis-sentinel-true,app.kubernetes.io/name=redis
service/redis-sentinel-true-headless   ClusterIP   None           <none>        6379/TCP,26379/TCP   26h   app.kubernetes.io/instance=redis-sentinel-true,app.kubernetes.io/name=redis

NAME                                        READY   AGE   CONTAINERS       IMAGES
statefulset.apps/redis-sentinel-true-node   3/3     26h   redis,sentinel   docker.io/bitnami/redis:7.0.5-debian-11-r15,docker.io/bitnami/redis-sentinel:7.0.5-debian-11-r14
```
```
[root@master-01 ~]# python3 test.py
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    r.set('hello4', 'dad4')
  File "/usr/local/lib/python3.6/site-packages/redis/commands/core.py", line 2220, in set
    return self.execute_command("SET", *pieces, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 1242, in execute_command
    lambda error: self._disconnect_raise(conn, error),
  File "/usr/local/lib/python3.6/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 1240, in <lambda>
    conn, command_name, *args, **options
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 1215, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 1254, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 839, in read_response
    raise response
redis.exceptions.ReadOnlyError: You can't write against a read only replica.
[root@master-01 ~]# python3 test.py
b'dad4'
log for traefik ingress: 
10.56.149.47 - - [14/Dec/2022:10:52:50 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 9775 "ping@internal" "-" 0ms
10.56.149.47 - - [14/Dec/2022:10:52:50 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 9776 "ping@internal" "-" 0ms
time="2022-12-14T10:52:54Z" level=debug msg="Handling connection from 10.56.149.47:55440 to 20.20.251.141:6379"
10.56.149.47 - - [14/Dec/2022:10:53:00 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 9777 "ping@internal" "-" 0ms
10.56.149.47 - - [14/Dec/2022:10:53:00 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 9778 "ping@internal" "-" 0ms
```
