### ISSUE TITLE
[bitnami/mongodb] Prometheus exporter does not use correct port

### ISSUE THREAD

**Issue by barisaksan** [bitnami/charts#13951]
### Name and Version

bitnami/mongodb 13.6.0

### What steps will reproduce the bug?

1- Configure mongodb to use a different port than the default 27017
2- Enable metrics and service monitor to enable using a sidecar Prometheus exporter
3- Deploy mongodb
4- The Prometheus exporter running in the sidecar cannot connect to the mongodb database

### Are you using any custom parameters or values?
```yaml
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
containerPorts:
  mongodb: 27018
service:
  ports:
    mongodb: 27018
```
### What is the expected behavior?

The Prometheus exporter can connect to the mongodb database and can export metrics

### What do you see instead?

The Prometheus exporter tries to connect to Mongodb using 27017 port and fails to connect

### Additional information

The mongodb url used by the /bin/mongodb_exporter uses the 27017 port which is the default mongodb port.
https://github.com/bitnami/charts/blob/main/bitnami/mongodb/templates/_helpers.tpl#L418-L427
If mongodb is configured to use another port, the mongodb_exporter cannot connect
