### ISSUE TITLE
[Bitnami/Discourse]: Production.Log file is not created with the correct write permissions

### ISSUE THREAD

**Issue by stevejr** [bitnami/charts#13970]
### Name and Version

bitnami/discourse 8.1.8

### What steps will reproduce the bug?

Have deployed Discourse using custom values.yaml (see below) and am seeing an error that the production.log file is not writable. My custom config should not affect this.

### Are you using any custom parameters or values?

```yaml
image:
  tag: 2.8.9
auth:
  email: <email address>
  user: <email user>
discourse:
  lifecycleHooks:
    postStart:
      exec:
        command:
          [
            "/bin/sh",
            "-c",
            "cd /opt/bitnami/discourse; RAILS_ENV=production bundle exec rake s3:upload_assets",
          ]
  extraEnvVars:
  # This env var is needed as we have encryption in transport enabled in elasticache
  - name: DISCOURSE_REDIS_USE_SSL
    value: "true"
  # This env var is needed so that we read S3 config from site settings
  - name: USE_DB_S3_CONFIG
    value: "true"
  # S3 settings used for serving ALL public files
  # be sure to configure a CDN as well per cdn_url
  - name: DISCOURSE_EXTRA_CONF_CONTENT
    value: |
      backup_frequency = 1
      backup_location = s3
      enable_s3_uploads = true
      s3_bucket = <bucket>
      s3_backup_bucket = <backup bucket>
      s3_upload_bucket = <upload bucket>
      s3_region = <s3 region>
      s3_use_iam_profile = true
      s3_cdn_url = <cdn url>
      use_db_s3_config = true
      force_https = false
externalDatabase:
  port: 5432
  database: discourse
  create: false
  host: <host>
  user: <user>
  existingSecret: <secret name>
  existingSecretPasswordKey: <password key>
externalRedis:
  host: <host>
  port: 6379
host: <host name>
image:
  debug: false
  tag: 2.8.11
sidekiq:
  extraEnvVars:
  # This env var is needed as we have encryption in transport enabled in elasticache
  - name: DISCOURSE_REDIS_USE_SSL
    value: "true"
siteName: <site name>
smtp:
  auth: login
  enabled: true
  existingSecret: <secret name>
  host: <host>
  port: 587
  protocol: tls
  user: <user id>
```

### What is the expected behavior?

The production.log file should be writable.

### What do you see instead?

```
App 32622 output: Rails Error: Unable to access log file. Please ensure that /opt/bitnami/discourse/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /opt/bitnami/discourse/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
```

The file is owned by root and is set to only be r/w for the root user.
