### ISSUE TITLE
bitnami/postgresql requries a root user

### ISSUE THREAD

**Issue by splix** [bitnami/charts#13985]
### Name and Version

bitnami/postgresql 10.0.5

### What steps will reproduce the bug?

Deploying to a kubernetes v1.24.6 + containerd + security disallowing non-root users.

### What do you see instead?

Fails with:
```
postgresql 04:01:45.07 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 04:01:45.07 INFO  ==> Generating local authentication configuration
/opt/bitnami/scripts/libpostgresql.sh: line 222: /opt/bitnami/postgresql/conf/pg_hba.conf: Permission denied
/opt/bitnami/scripts/libfile.sh: line 39: /opt/bitnami/postgresql/conf/postgresql.conf: Permission denied
```
Because it cannot write to the internal container filesystem, which is owned by a root user.

A root user is not allowed so a chown of those dirs is not possible during the deployment.

### Additional information

Mounting those directories as volumes with write access can fix the issue:
```yaml
primary:
  extraVolumes:
    - name: conf
      emptyDir:
        sizeLimit: 10Mi
    - name: tmp
      emptyDir:
        sizeLimit: 10Mi
  extraVolumeMounts:
    - name: conf
      mountPath: /opt/bitnami/postgresql/conf
    - name: tmp
      mountPath: /opt/bitnami/postgresql/tmp
```

But I believe that a real fix would be a chmod or chown during the docker building phase.

**Comment by carrodher** [comment]
Can you try using the "volumePermissions" init container? See https://github.com/bitnami/charts/tree/main/bitnami/postgresql#volume-permissions-parameters

**Comment by splix** [comment]
@carrodher tried actually, but it didn't work too because of the same reasons

**Comment by migruiz4** [comment]
Hi @splix,

The `bitnami/postgresql` chart version 10.0.5 does not exist, the closer versions are 10.0.2 and 10.1.0, which were released 2 years ago on November 2020. 

Have you been able to reproduce this issue using the latest version of the chart (12.1.3)? Although we investigate and found the root cause of the issue, fixes can only be applied to the latest versions.

Additionally, it would be helpful if you could provide the `values.yaml` used to deploy the chart, so we can try to reproduce the issue in the exact same conditions.

**Comment by splix** [comment]
Hi @migruiz4

I'm not sure where I've got the `10.0.5`, I think took it from another chart. Because the actual version that I'm using is `12.1.2`

My config is simple:
```
auth:
  enablePostgresUser: true
  postgresPassword: 123456

primary:
  persistence:
    existingClaim: pv-postgres-claim
  nodeSelector:
    role: storage
  podSecurityContext:
    fsGroup: 1001  # <- I think I was running it without that option, but have it now in the final config
 [... here goes the empty dir mounts as above to fix the issue ...]
```

**Comment by migruiz4** [comment]
Thank you for the additional information and sorry for the late response.

The value `primary.podSecurityContext.fsGroup` is set to 1001 by default.

In the issue description you mention you have disallowed non-root users.
Could you please let us know what user are you running the `bitnami/postgresql` container as?

**Comment by splix** [comment]
I tried with (and without):

```
securityContext:
  runAsUser: 1001
```

But it didn't have any effect, b/c to my understanding it's the default option. So I'm **running it without specifying any user**.

**Comment by migruiz4** [comment]
I think I know what may be happening, is it possible your container is running with a `runAsGroup` other than `0`/`root`?
The user and group the container runs as may vary depending on the Kubernetes cluster policies, so it may be possible you haven't explicitly set this configuration.

You can verify which user by running the `id` command inside the pod:
```
$ k exec -it test-postgresql-0 -- bash   
...
I have no name!@test-postgresql-0:/$ id
uid=1001 gid=0(root) groups=0(root),1001
``` 

The Bitnami containers are configured to run as any non-root user (any arbitrary UUID, not only 1001). For this to work, it is necessary that the user running the container is also part of the `root` group id.

You can find more information about Bitnami's non-root container in the following link: https://docs.bitnami.com/tutorials/bitnami-best-practices-hardening-containers/

If the user is running with a group different than root, that would explain the `permission denied` on paths like `/opt/bitnami/postgresql/conf` or `/opt/bitnami/postgresql/tmp`, which are part of the container filesystem.

**Comment by splix** [comment]
@migruiz4 yes, the user does not belong to the `root` group. It's a cluster-wide policy because of the security reasons.

**Comment by migruiz4** [comment]
Hi @splix,

Unfortunately, our container images do not support running as a non-root group for the moment.

As I previously mentioned, it is a required feature for supporting non-root containers using an arbitrary UID (i.e. where the UID is not any known user of the system), as those users belong to the root group, allowing us to grant write access files (via group write privileges).

Also, I'd like to point out that the container image does not have any file writable by the root group, other than those that are world-writable or in the Postgresql installation directory.

If you need to restrict write privileges to the root group, then unfortunately the only way is to run the container as the root user, as that will make PostgreSQL run as a daemon user with non-root writable group permissions.

**Comment by splix** [comment]
Ok, I see. 

btw, to my understanding Kubernetes is going to restrict the root privileges including root group with the following releases? or at least it's a best practice. Any plans to avoid using a root group? Is it really required? since I see it works fine without a root group

**Comment by migruiz4** [comment]
I'm sorry @splix, but at the moment it is not possible to run our containers with non-root GID as it is required to run users with random UID, which is a requirement in some security-hardened kubernetes clusters.

> btw, to my understanding Kubernetes is going to restrict the root privileges including root group with the following releases? 

Could you please share a link? We are not aware of such changes in the upcoming releases.

As I previously mentioned, our container images do not have any file writable by the root group other than those that are required by the running application.

**Comment by 100tomer** [comment]
Any updates? For me, I run the container with:
```
  securityContext:
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true
      privileged: false
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
```
              
and it does not work, but for other Bitnami releases like Minio, it works fine.
