### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by hdavila146** [bitnami/charts#13993]
### Name and Version

[bitnami/thanos] release 11.6.4

### What steps will reproduce the bug?

1. env: minikube and Digital Ocean.
2.  The configuration of Thanos example 
3. Error
```
bucket: The Access Key Id you provided does not exist in our records."
```
### Are you using any custom parameters or values?

no only the ones recommended in the readme.md file.
```yaml
objstoreConfig: |-
  type: s3
  config:
    bucket: thanos
    endpoint: {{ include "thanos.minio.fullname" . }}.monitoring.svc.cluster.local:9000
    access_key: minio
    secret_key: minio123
    insecure: true
query:
  dnsDiscovery:
    sidecarsService: kube-prometheus-prometheus-thanos
    sidecarsNamespace: monitoring
bucketweb:
  enabled: true
compactor:
  enabled: true
storegateway:
  enabled: true
ruler:
  enabled: true
  alertmanagers:
    - http://kube-prometheus-alertmanager.monitoring.svc.cluster.local:9093
  config: |-
    groups:
      - name: "metamonitoring"
        rules:
          - alert: "PrometheusDown"
            expr: absent(up{prometheus="monitoring/kube-prometheus"})
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
minio:
  enabled: true
  auth:
    rootUser: "admin"
    rootPassword: "minio123"
  defaultBuckets: "thanos"
```
### What is the expected behavior?

pods of thanos-compact and thanos storegateway run without any problems.

### What do you see instead?

make the pods thanos-compact and thanos storegateway change the status to crashloopbackoff.

### Additional information

this change of the chart minio have been done in this PR https://github.com/bitnami/charts/issues/6726 already create a PR of the changes that can be done. [bitnami/thanos] release 11.6.4
