### ISSUE TITLE
ServiceMonitor Endpoint Path is not configurable

### ISSUE THREAD

**Issue by Loucool111** [bitnami/charts#13995]
### Name and Version

bitnami/nginx 13.2.18

### What is the problem this feature will solve?

Currently the servicemonitor endpoint path is not configurable.
This is a problem if the nginx `stub_status` info is not available under /status.

### What is the feature you are proposing to solve the problem?

Make the ServiceMonitor endpoint path configurable via helm values.

for example these changes in `servicemonitor.yaml` would fix this:
```yaml
...
spec:
  ...
  endpoints:
    - port: metrics
      path: {{ .Values.metrics.serviceMonitor.path | default "/metrics" }}
      ...
...
```

This would make my job a bit better ;)

### What alternatives have you considered?

None.
