### ISSUE TITLE
bitnami/keycloak We are sorry... Page not found through nginx

### ISSUE THREAD

**Issue by Gowlar** [bitnami/charts#14004]
### Name and Version

bitnami/keycloak 12.2.0

### What steps will reproduce the bug?

When I navigate to the url of keycloak i get the following page

![image](https://user-images.githubusercontent.com/5189666/208242213-b94e6646-1d04-4de1-8a9a-12c7e9066d0e.png)

In addition, each time I restart the pod I get `ERROR [org.keycloak.services] (main) KC-SERVICES0010: Failed to add user 'user' to realm 'master': user with username exists. `

Deployed helm chart with nginx ingreess

![image](https://user-images.githubusercontent.com/5189666/208242132-e3fafc53-dfa8-44da-b380-4e574aea699f.png)

### Are you using any custom parameters or values?

helm:
```yaml
    parameters:
      - name: externalDatabase.existingSecret
        value: xxx-db
      - name: externalDatabase.host
        value: xxxx.postgres.database.azure.com
      - name: externalDatabase.user
        value: synectics
      - name: postgresql.enabled
        value: 'false'
      - name: externalDatabase.database
        value: keycloak
      - name: autoscaling.enabled
        value: 'true'
      - name: autoscaling.maxReplicas
        value: '5'
      - name: pdb.create
        value: 'true'
      - name: replicaCount
        value: '2'
      - name: service.type
        value: ClusterIP
      - name: production
        value: 'true'
      - name: proxy
        value: edge
      - name: ingress.hostname
        value: dev-xxxxx.com
    values: |
      extraEnv: |
        - name: KEYCLOAK_LOGLEVEL
          value: DEBUG
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
```
### What is the expected behavior?

Show keycloak landing page 

### What do you see instead?

![image](https://user-images.githubusercontent.com/5189666/208242257-e1096644-8d10-4322-942e-23fdbb972299.png)
