### ISSUE TITLE
[rabbitmq chart] Add an option to override advancedConfiguration with a pre existing secret

### ISSUE THREAD

**Issue by FranAguiar** [bitnami/charts#14017]
### Name and Version

bitnami/rabbitmq

### What is the problem this feature will solve?

The "advancedConfiguration" field could have sensitive data (Azure active directory configuration in my case) or be different between environments.

### What is the feature you are proposing to solve the problem?

My proposal is that it would be nice to have a way to load that configuration from a secret. Then we can address both issues, not expose sensitive data and have configurations per environment easily.

If needed I am willing to help, but I don't know where to start so I appreciate any help.

### What alternatives have you considered?

I think the helm post render option could solve this, but doesn't fit my needs because argocd isn't compatible with that helm's feature. And I think a native solution would be better to not add that complexity to the deploy

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by FranAguiar** [comment]
Hi @carrodher, glad to help if I can.
Can someone from the team suggest the best approach to solve it? I'm not very confident with helm and I don't want to mesh it up.

**Comment by FranAguiar** [comment]
I was checking the statefulset.yaml template and I think this could work:

```
        - name: configuration
          secret:
            secretName: {{ printf "%s-config" (include "common.names.fullname" .) }}
            items:
              - key: rabbitmq.conf
                path: rabbitmq.conf
              {{- if .Values.advancedConfiguration }}
              - key: advanced.config
                path: advanced.config
              {{- end }}
        {{ - if .Values.advancedConfigurationExistingSecret }}
        - name: advanced-configuration
          secret:
            secretName: {{ tpl .Values.advancedConfigurationExistingSecret . | quote }}
            items:
              - key: advanced.config
                path: advanced.config
        {{- end }}
```
