### ISSUE TITLE
not able to create seperate pod for sentinels

### ISSUE THREAD

**Issue by abhishekgupta2205** [bitnami/charts#14019]
### Name and Version

bitnami/redis , latest

### What steps will reproduce the bug?

helm install redis
sentinel enabled

### What is the expected behavior?

it should create different pods for redis server and sentinel

### What do you see instead?

one pod consisting of redis server and sentinel is created

**Comment by carrodher** [comment]
Could you please share the changes you did in the values.yaml or the parameters used as part of the `helm install` command? That will help us to reproduce the issue on our side

**Comment by abhishekgupta2205** [comment]
i could not find any parameter in values.yaml to spwan another pod containing sentinel container .

**Comment by carrodher** [comment]
There is a `sentinel.enabled` parameter, but this doesn't deploy a different pod for sentinel, but configure sentinel in the same pod as Redis, see the description:
```yaml
sentinel:
  ## @param sentinel.enabled Use Redis Sentinel on Redis pods.
  ## IMPORTANT: this will disable the master and replicas services and
  ## create a single Redis service exposing both the Redis and Sentinel ports
  ##
  enabled: false
```
