### ISSUE TITLE
Cannot use custom certificates in matomo https

### ISSUE THREAD

**Issue by shaikmuzakkir** [bitnami/charts#14020]
### Name and Version

matomo-0.2.13

### What steps will reproduce the bug?

I see a default certificate example.com on loading the matomo site deployed by the helm chart and I tried to use my custom certs with the below configs. I had added the cert and key to a TLS secret in Kubernetes and created a secret called matomo-ssl and used it in the config.

```yaml
## Add custom certificates and certificate authorities to matomo container
##
certificates:
  ## @param certificates.customCertificate.certificateSecret Secret containing the certificate and key to add
  ## @param certificates.customCertificate.chainSecret.name Name of the secret containing the certificate chain
  ## @param certificates.customCertificate.chainSecret.key Key of the certificate chain file inside the secret
  ## @param certificates.customCertificate.certificateLocation Location in the container to store the certificate
  ## @param certificates.customCertificate.keyLocation Location in the container to store the private key
  ## @param certificates.customCertificate.chainLocation Location in the container to store the certificate chain
  ##
  customCertificate:
    certificateSecret: "matomo-ssl"
    certificateLocation: /etc/ssl/certs/ssl-cert-snakeoil.pem
    keyLocation: /etc/ssl/private/ssl-cert-snakeoil.key
```
Even after using the custom certs, I still see example.com in the ssl cert.

### What is the expected behavior?

The matomo HTTPS site should have the certs we provide in the config.

### What do you see instead?

The matomo HTTPS site has a default cert example.com.

**Comment by migruiz4** [comment]
Hi @shaikmuzakkir,

Could you please try using the following values and let me know if it works for you?
```
certificates:
  customCertificate:
    certificateSecret: "matomo-ssl"
    chainSecret: {}
      # name: secret-name
      # key: secret-key
    certificateLocation: /opt/bitnami/apache/conf/bitnami/certs/server.crt
    keyLocation: /opt/bitnami/apache/conf/bitnami/certs/server.key
```

The above should mount the SSL certificate and key overriding the default certificate included in the container.
