### ISSUE TITLE
Cannot fetch postgresql-ha chart from https://charts.bitnami.com/bitnami

### ISSUE THREAD

**Issue by dmitry-midokura** [bitnami/charts#14040]
### Name and Version

bitnami/postgresql-ha:8.6.13

### What steps will reproduce the bug?

Chart.yaml:

```
apiVersion: v1
description: A Helm chart
name: test
type: application
version: 1.0.0
dependencies:
  - name: postgresql-ha
    version: 8.6.13
    repository: https://charts.bitnami.com/bitnami
 ```

```bash
helm dependency build
```

Error: can't get a valid version for repositories postgresql-ha. Try changing the version constraint in Chart.yaml

It used to work till yesterday. I also tried versions: 9.0.2 and 10.16.2, same error.

### What is the expected behavior?

Chart should be downloaded

### What do you see instead?

Error: can't get a valid version for repositories postgresql-ha. Try changing the version constraint in Chart.yaml

### Additional information

It used to work till yesterday. I also tried versions: 9.0.2 and 10.16.2, same error.
