### ISSUE TITLE
Problems with /tmp in Fluentd chart with latest default image

### ISSUE THREAD

**Issue by a13xbr0** [bitnami/charts#14053]
### Name and Version

bitnami/fluentd 5.5.11

### What steps will reproduce the bug?

In values.yaml enable extraVolumes/extraVolumeMounts for aggregator StatefulSet as described in the comments.

### Are you using any custom parameters or values?

```yaml
aggregator:
  containerSecurityContext:
    readOnlyRootFilesystem: true
  extraVolumes:
    - name: temporary
      emptyDir: {}
  extraVolumeMounts:
    - name: temporary
      mountPath: /tmp
```

### What is the expected behavior?

Working StatefulSet/pod

### What do you see instead?

The container fails with these messages in log:
```
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
. is not writable: /opt/bitnami/fluentd
Unexpected error could not find a temporary directory
  /opt/bitnami/ruby/lib/ruby/3.1.0/tmpdir.rb:39:in `tmpdir'
  /opt/bitnami/ruby/lib/ruby/3.1.0/tmpdir.rb:115:in `tmpdir'
  /opt/bitnami/ruby/lib/ruby/3.1.0/tmpdir.rb:130:in `create'
  /opt/bitnami/ruby/lib/ruby/3.1.0/tmpdir.rb:90:in `mktmpdir'
  /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/supervisor.rb:47:in `before_run'
  /opt/bitnami/fluentd/gems/serverengine-2.3.0/lib/serverengine/server.rb:125:in `main'
  /opt/bitnami/fluentd/gems/serverengine-2.3.0/lib/serverengine/daemon.rb:119:in `main'
  /opt/bitnami/fluentd/gems/serverengine-2.3.0/lib/serverengine/daemon.rb:68:in `run'
  /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/supervisor.rb:902:in `supervise'
  /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/supervisor.rb:742:in `run_supervisor'
  /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/command/fluentd.rb:350:in `<top (required)>'
  <internal:/opt/bitnami/ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
  <internal:/opt/bitnami/ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
  /opt/bitnami/fluentd/gems/fluentd-1.15.3/bin/fluentd:15:in `<top (required)>'
  /opt/bitnami/fluentd/bin/fluentd:25:in `load'
  /opt/bitnami/fluentd/bin/fluentd:25:in `<main>'
```

**Comment by carrodher** [comment]
Fluentd container is non root by default, which means the user running the container is 1001 (or any other random UID) **but it should belong to the root group** in order to be able to have the proper permissions. Then, any directory used by the container should have the proper permissions for the root group.
Could you check if the `/tmp` folder is writable by the root group?

[Here](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/) you can find more info about this topic.

**Comment by cagdasoezguer** [comment]
I have the same Problem.
By just updating the image tag from `1.14.4-debian-10-r32` to `1.15.3-debian-11-r40`

I receive the same error:
```
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
. is not writable: /opt/bitnami/fluentd
Unexpected error could not find a temporary directory
```

In the part of the security-context nothing is changed:

````yaml
 podSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
````

````yaml
  containerSecurityContext:
    enabled: true
    privileged: false
    allowPrivilegeEscalation: false
    ## Requires mounting an `extraVolume` of type `emptyDir` into /tmp
    ##
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
````
Also nothing in the tmpdir configuration is changed
````yaml
  extraVolumes:
     - name: tmpdir
       emptyDir: {}
  ## @param aggregator.extraVolumeMounts Mount extra volume(s)
  ##   - name: tmpDir
  ##     mountPath: /tmp
  ##
  extraVolumeMounts:
     - name: tmpdir
       mountPath: /tmp
````
