### ISSUE TITLE
Helm upgrade failed after upgrading to 12.x.x

### ISSUE THREAD

**Issue by falyoun** [bitnami/charts#14058]
### Name and Version

bitnami/postgres

### What steps will reproduce the bug?

After upgrading bitnami/postgres to version 12.1.6 running into the following issue:

```
Error: helm upgrade have failed: UPGRADE FAILED: execution error at (ship-api/charts/postgresql/templates/secrets.yaml:20:15):
PASSWORDS ERROR: The secret "..." does not contain the key "password"
Error: The process '/runner/_work/_temp/werf-tools/werf' failed with exit code 1
```

Chart.yaml

```yaml
apiVersion: v2
name: '{{ .Chart.Name }}'
version: 1.0.0
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.1.6
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.3.17
    condition: redis.enabled
```

### What do you see instead?

Building chart dependencies
```
│ Using chart dependencies directory:                                                                                            ↵
│ /home/runner/.werf/local_cache/helm_chart_dependencies/1/bb938eb99fb09ce4812fef7a9eb14[97](https://github.com/..../...-api/actions/runs/3749487253/jobs/6368090593#step:19:98)4be912a172f7a3e827dcd329dc2615755
│ Hang tight while we grab the latest from your chart repositories...
│ ...Successfully got an update from the "bitnami" chart repository
│ Update Complete. ⎈Happy Helming!⎈
│ Saving 2 charts
│ Downloading postgresql from repo https://charts.bitnami.com/bitnami
│ Downloading redis from repo https://charts.bitnami.com/bitnami
│ Deleting outdated charts
└ Building chart dependencies (1.86 seconds)

Running time 5.08 seconds
Error: helm upgrade have failed: UPGRADE FAILED: execution error at (ship-api/charts/postgresql/templates/secrets.yaml:20:15): 
PASSWORDS ERROR: The secret "....-api-review-472" does not contain the key "password"
Error: The process '/runner/_work/_temp/werf-tools/werf' failed with exit code 1
```

**Comment by carrodher** [comment]
You need to export the password when upgrading, see https://docs.bitnami.com/kubernetes/infrastructure/postgresql/administration/upgrade/#upgrading-instructions

**Comment by falyoun** [comment]
@carrodher Can I export it via `.yaml` files?

**Comment by carrodher** [comment]
Yes, you only need to obtain the password from the already running deployment and use it when upgrading the release as `auth.postgresPassword`

**Comment by falyoun** [comment]
@carrodher 

I already tried that but still not working

```
postgresql:
  enabled: false
  auth:
    database: ...
    username: ...
    postgresPassword: ...
  fullnameOverride: ...
  primary:
    nodeSelector:
      lifecycle: 'Ec2Spot'
```
