### ISSUE TITLE
Wordpress wp_mail relies on non-existing sendmail

### ISSUE THREAD

**Issue by dploeger** [bitnami/charts#14068]
### Name and Version

bitnami/wordpress 15.2.21

### What steps will reproduce the bug?

When deploying the chart with the smtp-parameters, Wordpress still can't send mails because the wp_mail function (or PHPMailer in turn) relies on an installed sendmail binary, which is missing from the container.

### Are you using any custom parameters or values?

```yaml
    smtpHost: ...
    smtpPort: 587
    smtpUsername: ...
    smtpPassword: ...
    smtpProtocol: tls
```

### What is the expected behavior?

Wordpress can directly send out mails without any more configuration

### What do you see instead?

When using the [wp-test-email](https://de.wordpress.org/plugins/wp-test-email/) plugin to send out a test mail I get the following error in the log:

sh: 1: /usr/sbin/sendmail: not found

**Comment by fmulero** [comment]
Sorry @dploeger  but I am not able to reproduce exactly the issue you reported. How did you get that message in the log? Are you setting any additional value?

**Comment by dploeger** [comment]
I don't think so. These are my complete values:

```yaml
    wordpressUsername: <redacted>
    wordpressEmail: <redacted>
    wordpressFirstName: <redacted>
    wordpressLastName: <redacted>
    wordpressBlogName: <redacted>
    # Settings here don't work. See https://github.com/bitnami/charts/issues/14068
    # In the meantime, we're using wpmailSMTP plugin
    smtpHost: <redacted>
    smtpPort: 587
    smtpUsername: <redacted>
    smtpPassword: <redacted>
    smtpProtocol: tls
    ## @param wordpressSkipInstall Skip wizard installation
    ## NOTE: useful if you use an external database that already contains WordPress data
    ## ref: https://github.com/bitnami/containers/tree/main/bitnami/wordpress#connect-wordpress-docker-container-to-an-existing-database
    ##
    wordpressSkipInstall: false
    ## @param wordpressExtraConfigContent Add extra content to the default wp-config.php file
    ## e.g:
    ## wordpressExtraConfigContent: |
    ##   @ini_set( 'post_max_size', '128M');
    ##   @ini_set( 'memory_limit', '256M' );
    ##
    wordpressExtraConfigContent: ""
    ## @param wordpressConfiguration The content for your custom wp-config.php file (advanced feature)
    ## NOTE: This will override configuring WordPress based on environment variables (including those set by the chart)
    ## NOTE: Currently only supported when `wordpressSkipInstall=true`
    ##
    wordpressConfiguration: ""
    ## @param existingWordPressConfigurationSecret The name of an existing secret with your custom wp-config.php file (advanced feature)
    ## NOTE: When it's set the `wordpressConfiguration` parameter is ignored
    ##
    existingWordPressConfigurationSecret: ""
    ## @param wordpressConfigureCache Enable W3 Total Cache plugin and configure cache settings
    ## NOTE: useful if you deploy Memcached for caching database queries or you use an external cache server
    ##
    wordpressConfigureCache: false
    ## @param wordpressPlugins Array of plugins to install and activate. Can be specified as `all` or `none`.
    ## NOTE: If set to all, only plugins that are already installed will be activated, and if set to none, no plugins will be activated
    ##
    wordpressPlugins: none
    service:
      type: ClusterIP
    resources:
      limits: {}
      requests:
        memory: 512Mi
        cpu: 300m
    persistence:
      storageClass: default
      size: 10Gi
    mariadb:
      primary:
        persistence:
          storageClass: default
          size: 8Gi
```

Could it be that it doesn't work because I added the SMTP values after the release was installed?
