### ISSUE TITLE
[bitnami/kube-prometheus] Ingress with wildcard (*) hostname not working

### ISSUE THREAD

**Issue by haje01** [bitnami/charts#14070]
### Name and Version

bitnami/kube-prometheus 8.3.0 

### What steps will reproduce the bug?

Enable Ingress with `hostname` as `*` :

```yaml
  prometheus:
    enabled: true
    ingress:
      enabled: true
      hostname: "*"
```

### Are you using any custom parameters or values?

No.

### What is the expected behavior?

Install Ingress without error.

### What do you see instead?

Installation failed with following messages :

```
YAML parse error on alpaka/charts/prometheus/templates/prometheus/ingress.yaml: error converting YAML to JSON: yaml: line 20: did not find expected alphabetic or numeric character
```

`helm template` result: 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eks-prometheus-prometheus
  namespace: "default"
  labels:
    app.kubernetes.io/name: prometheus
    helm.sh/chart: prometheus-8.2.2
    app.kubernetes.io/instance: eks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: prometheus
spec:
  rules:
    - host: *      # <----------- THIS IS WRONG.
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: eks-prometheus-prometheus
                port:
                  name: http
```

### Additional information

Ingress with wildcard hostname should not produce `host` element.
Following is [bitnami/grafana] implementation:

```yaml
  rules:
    {{- if .Values.ingress.hostname }}                                                                                           
    - http:
        paths:
          {{- if .Values.ingress.extraPaths }}
          {{- toYaml .Values.ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ .Values.ingress.path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
            pathType: {{ .Values.ingress.pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" .) "servicePort" "http" "context" $)  | nindent 14 }}
      {{- if ne .Values.ingress.hostname "*" }}   # <----------- THIS IS RIGHT
      host: {{ include "common.tplvalues.render" (dict "value" .Values.ingress.hostname "context" $) }}
      {{- end }}
    {{- end }}
```
