### ISSUE TITLE
Fails to deploy MySQL with customPasswordFiles in K8s

### ISSUE THREAD

**Issue by tochrisme** [bitnami/charts#14083]
### Name and Version

bitnami/mysql:8.0.31-debian-11-r20

### What steps will reproduce the bug?

Hello, I am working on a POC to integrate HashiCorp Vault secret management with Helm Charts:

I use the following auth configs in the values.yaml to enable a custom password file:
```yaml
auth:
  ## @param auth.rootPassword Password for the `root` user. Ignored if existing secret is provided
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/mysql#setting-the-root-password-on-first-run
  ##
  rootPassword: ""
  ## @param auth.createDatabase Wheter to create the .Values.auth.database or not
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/mysql#creating-a-database-on-first-run
  ##
  createDatabase: true
  ## @param auth.database Name for a custom database to create
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/mysql#creating-a-database-on-first-run
  ##
  database: "my_database"
  ## @param auth.username Name for a custom user to create
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/mysql#creating-a-database-user-on-first-run
  ##
  username: "db_user"
  ## @param auth.password Password for the new user. Ignored if existing secret is provided
  ##
  password: ""
  ## @param auth.replicationUser MySQL replication user
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/mysql#setting-up-a-replication-cluster
  ##
  replicationUser: replicator
  ## @param auth.replicationPassword MySQL replication user password. Ignored if existing secret is provided
  ##
  replicationPassword: ""
  ## @param auth.existingSecret Use existing secret for password details. The secret has to contain the keys `mysql-root-password`, `mysql-replication-password` and `mysql-password`
  ## NOTE: When it's set the auth.rootPassword, auth.password, auth.replicationPassword are ignored.
  ##
  existingSecret: ""
  ## @param auth.usePasswordFiles Mount credentials as files instead of using an environment variable
  ##
  usePasswordFiles: true
  ## @param auth.customPasswordFiles Use custom password files when `auth.usePasswordFiles` is set to `true`. Define path for keys `root` and `user`, also define `replicator` if `architecture` is set to `replication`
  ## Example:
  ## customPasswordFiles:
  ##   root: /vault/secrets/mysql-root
  ##   user: /vault/secrets/mysql-user
  ##   replicator: /vault/secrets/mysql-replicator
  ##
  customPasswordFiles: 
    root: /vault/secrets/database-root-config
```

### Are you using any custom parameters or values?

vault secrets are injected into the pod by adding podAnnotations in the values.yaml
```yaml
  ## @param primary.podAnnotations Additional pod annotations for MySQL primary pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  podAnnotations: 
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/agent-inject-status: 'update'
    vault.hashicorp.com/role: 'k8s-kv-role'
    vault.hashicorp.com/agent-inject-secret-database-root-config: 'kv/k8s/poc/database/mysql'
    vault.hashicorp.com/agent-inject-template-database-root-config: |
      {{`{{ with secret "kv/k8s/poc/database/mysql" }}{{ .Data.data.mysql_root_password }}
      {{ end }}`}}
```

### What is the expected behavior?

It is expected that Helm would deploy MySQL and use the password from the custom password file, "database-root-config" as the root password

### What do you see instead?

The MySQL pod gets stuck in the Back-off restarting failed container state with the following error
```
mysql 09:27:15.13 INFO  ==> ** Starting MySQL setup **
mysql 09:27:15.17 WARN  ==> Skipping export of 'MYSQL_PASSWORD'. '/opt/bitnami/mysql/secrets/mysql-password' is not readable.
mysql 09:27:15.18 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 09:27:15.19 ERROR ==> The MYSQL_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development
```

### Additional information

The file is successfully injected into the MySQL pod:
```
sh: bash: not found
/ $ cat /vault/secrets/database-root-config
MyRootPwd
```
