### ISSUE TITLE
[bitnami/grafana-operator] SecurityContext applied to initContainers into Grafana deployment 

### ISSUE THREAD

**Issue by robmonct** [bitnami/charts#14104]
### Name and Version

bitnami/grafana-operator:4.8.0

### What is the problem this feature will solve?

The problem is that there is no way to add SecurityContext to initContainers (grafana-plugins-init) for Grafana pods. There is a way to add containerSecurityContext and podSecurityContext but that is not applied to initContainers. 

### What is the feature you are proposing to solve the problem?

With this feature, we should be able to add securityContext also to initContainers.

### What alternatives have you considered?

The easiest way in my honest opinion is add the option to overwrite the initContainers for Grafana pods like it is possible to do it for Grafana operator pods. 

PR proposed: https://github.com/bitnami/charts/pull/14103

**Comment by carrodher** [comment]
Thanks for creating this issue and the associated PR, the team will review it and provide feedback as soon as possible (it will take longer than usual due to the holidays). This issue will be automatically closed once merge the PR.

**Comment by robmonct** [comment]
After testing the new version of the chart, this values.yaml is not overriding the deployment properly: 
```
  grafana:
    containerSecurityContext:
      enabled: true
      allowPrivilegeEscalation: false
    initContainers:
     - name: grafana-plugins-init
       image: docker.io/bitnami/grafana:9.3.2-debian-11-r4
       imagePullPolicy: IfNotPresent
       resources:
         limits:
           cpu: "1"
           memory: 512Mi
         requests:
           cpu: 250m
           memory: 128Mi
       securityContext:
         allowPrivilegeEscalation: false
         capabilities:
           drop:
           - ALL
         privileged: false
         readOnlyRootFilesystem: true
       env:
       - name: GRAFANA_PLUGINS
       volumeMounts:
       - mountPath: /opt/plugins
         name: grafana-plugins
``` 
The deployment that I can see is this: 
```
  initContainers:
  - env:
    - name: GRAFANA_PLUGINS
    image: docker.io/bitnami/grafana:9.3.2-debian-11-r4
    imagePullPolicy: IfNotPresent
    name: grafana-plugins-init
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/plugins
      name: grafana-plugins
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-d7vwl
      readOnly: true
```
Maybe should great to be able to disable the grafana-plugin-init initContainer if there is no Grafana plugins to install.
