### ISSUE TITLE
[MONGODB] - no replset config has been received 

### ISSUE THREAD

**Issue by lenglet-k** [bitnami/charts#14110]
### Name and Version

bitnami/mongodb 12.1.6

### What steps will reproduce the bug?

1. Environment

Environment is kubernetes 1.22.16

Helm chart values.yaml:

3. config

Standard config for mongodb replicaset

5. run

```shell
helm install mongodb -f values.yaml
```
7. Error 

The replicat is not configured, only mongodb-0 is on primary and no secondary is configured

### Are you using any custom parameters or values?

My values.yaml:
```yaml
 mongodb:
    # -- Override name chart
    fullnameOverride: mongodb
    service:
      ports:
        mongodb: "27017"
    # -- Standalone / replicaset
    architecture: replicaset
    replicaCount: 3
    labels:
      app: "mongodb"
    # -- Use pvc storage
    persistence:
      # -- mongodb enabled persistent volume
      enabled: true
      size: 5Gi
      storageClass: csi-cinder-high-speed
    # -- enable or disable mongodb auth
    auth:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        labels:
          prometheus.io/monitor: "true"
    arbiter:
      enabled: false
```

### What is the expected behavior?

I want that replicaSet mongo to be up after the helm deploy

### What do you see instead?

I see on

mongodb-0 with `rs.status()`:

```shell
{
  set: 'rs0',
  date: ISODate("2022-12-27T10:38:42.403Z"),
  myState: 1,
  term: Long("4"),
  syncSourceHost: '',
  syncSourceId: -1,
  heartbeatIntervalMillis: Long("2000"),
  majorityVoteCount: 1,
  writeMajorityCount: 1,
  votingMembersCount: 1,
  writableVotingMembersCount: 1,
  optimes: {
    lastCommittedOpTime: { ts: Timestamp({ t: 1672137516, i: 1 }), t: Long("4") },
    lastCommittedWallTime: ISODate("2022-12-27T10:38:36.405Z"),
    readConcernMajorityOpTime: { ts: Timestamp({ t: 1672137516, i: 1 }), t: Long("4") },
    appliedOpTime: { ts: Timestamp({ t: 1672137516, i: 1 }), t: Long("4") },
    durableOpTime: { ts: Timestamp({ t: 1672137516, i: 1 }), t: Long("4") },
    lastAppliedWallTime: ISODate("2022-12-27T10:38:36.405Z"),
    lastDurableWallTime: ISODate("2022-12-27T10:38:36.405Z")
  },
  lastStableRecoveryTimestamp: Timestamp({ t: 1672137506, i: 1 }),
  electionCandidateMetrics: {
    lastElectionReason: 'electionTimeout',
    lastElectionDate: ISODate("2022-12-27T10:37:36.379Z"),
    electionTerm: Long("4"),
    lastCommittedOpTimeAtElection: { ts: Timestamp({ t: 0, i: 0 }), t: Long("-1") },
    lastSeenOpTimeAtElection: { ts: Timestamp({ t: 1672137441, i: 1 }), t: Long("3") },
    numVotesNeeded: 1,
    priorityAtElection: 5,
    electionTimeoutMillis: Long("10000"),
    newTermStartDate: ISODate("2022-12-27T10:37:36.386Z"),
    wMajorityWriteAvailabilityDate: ISODate("2022-12-27T10:37:36.494Z")
  },
  members: [
    {
      _id: 0,
      name: 'mongodb-0.mongodb-headless.namespace.svc.cluster.local:27017',
      health: 1,
      state: 1,
      stateStr: 'PRIMARY',
      uptime: 67,
      optime: { ts: Timestamp({ t: 1672137516, i: 1 }), t: Long("4") },
      optimeDate: ISODate("2022-12-27T10:38:36.000Z"),
      lastAppliedWallTime: ISODate("2022-12-27T10:38:36.405Z"),
      lastDurableWallTime: ISODate("2022-12-27T10:38:36.405Z"),
      syncSourceHost: '',
      syncSourceId: -1,
      infoMessage: 'Could not find member to sync from',
      electionTime: Timestamp({ t: 1672137456, i: 1 }),
      electionDate: ISODate("2022-12-27T10:37:36.000Z"),
      configVersion: 1,
      configTerm: 4,
      self: true,
      lastHeartbeatMessage: ''
    }
  ],
```

On mongodb-1 and mongodb-2 with rs.status() command:

```shell
MongoError:  no replset config has been received 
```

on kubectl logs:

```shell
{"error":"NotYetInitialized: no replset config has been received","file":"src/mongo/db/repl/repl_set_get_status_cmd.cpp","line":56}
```

### Additional information

To fix that I have do:

```shell
rs.add(mongodb-1)
rs.add(mongodb-2)
```
