### ISSUE TITLE
[bitnami/nats] persistence forbidden on mkdir /data/jetstream

### ISSUE THREAD

**Issue by darzanebor** [bitnami/charts#14111]
### Name and Version

bitnami/nats 2.9.9

### What steps will reproduce the bug?

To reproduce:
1. Enable persistence
```yaml
persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 32Gi
  annotations: {}
  selector: {}
```
2. Deploy
3. Get an error

```console
$ kubectl -n infra logs -f nats-0
nats 11:14:39.24 
nats 11:14:39.25 Welcome to the Bitnami nats container
nats 11:14:39.25 Subscribe to project updates by watching https://github.com/bitnami/containers
nats 11:14:39.25 Submit issues and feature requests at https://github.com/bitnami/containers/issues
nats 11:14:39.25 
nats 11:14:39.26 INFO  ==> ** Starting NATS setup **
nats 11:14:39.30 WARN  ==> A custom configuration file "nats-server.conf" was found or the file is not writable. Configurations based on environment variables will not be applied for this file.
nats 11:14:39.31 INFO  ==> Initializing NATS
nats 11:14:39.33 INFO  ==> Custom configuration files detected, using them

nats 11:14:39.36 INFO  ==> ** NATS setup finished! **
nats 11:14:39.39 INFO  ==> ** Starting NATS **
[37] [INF] Starting nats-server
[37] [INF]   Version:  2.9.9
[37] [INF]   Git:      [825949b]
[37] [INF]   Cluster:  nats
[37] [INF]   Name:     nats-0
[37] [INF]   Node:     S1Nunr6R
[37] [INF]   ID:       NCYNWRNPQ4TGDWCOKIXKT2FUMAQKBK56ZE6SWNA5DCBDK4EOKI3X6VJ2
[37] [WRN] Plaintext passwords detected, use nkeys or bcrypt
[37] [INF] Using configuration file: /opt/bitnami/nats/conf/nats-server.conf
[37] [INF] Starting http monitor on 0.0.0.0:8222
[37] [INF] Starting JetStream
[37] [FTL] Can't start JetStream: could not create storage directory - mkdir /data/jetstream: permission denied
```
### Are you using any custom parameters or values?

no custom parameters, enabling persistence out of the box

### What is the expected behavior?

no permission issues, helm chart should be properly configured for uid and gid out of the box if there are specific user

### What do you see instead?

```
[37] [WRN] Plaintext passwords detected, use nkeys or bcrypt
[37] [INF] Using configuration file: /opt/bitnami/nats/conf/nats-server.conf
[37] [INF] Starting http monitor on 0.0.0.0:8222
[37] [INF] Starting JetStream
[37] [FTL] Can't start JetStream: could not create storage directory - mkdir /data/jetstream: permission denied
```

### Additional information

pvc exists and bonded
```yaml
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-nats-0
    ReadOnly:   false
```
