### ISSUE TITLE
Helm upgrade failed after upgrading postgres to 12.1.6

### ISSUE THREAD

**Issue by Baha-mumzwolrd** [bitnami/charts#14122]
### Name and Version

bitnami/postgres 12.1.6

### What steps will reproduce the bug?

After upgrading bitnami/postgres from 10.16.2 to 12.1.6, helm upgrade start failing, and we are getting this issue:

```
Error: helm upgrade have failed: UPGRADE FAILED: execution error at (headless-cms/charts/postgresql/templates/secrets.yaml:17:24): 
PASSWORDS ERROR: The secret "headless-cms-postgres-staging" does not contain the key "postgres-password"has
```

### Are you using any custom parameters or values?

values.yaml

```yaml
postgresql:
  enabled: true
  auth:
    database: xxx
    username: xxx
    postgresPassword: xxx
  fullnameOverride: xxx
  primary:
    nodeSelector:
      lifecycle: 'Ec2Spot'
```

### What do you see instead?

```
┌ Building chart dependencies
│ Using chart dependencies directory:                                                                                            ↵
│ /home/runner/.werf/local_cache/helm_chart_dependencies/1/8797afb8465531288f8bb9d94fdedd5d99af9338c5bb29346c40310b6cbf9dec
│ Hang tight while we grab the latest from your chart repositories...
│ ...Successfully got an update from the "bitnami" chart repository
│ Update Complete. ⎈Happy Helming!⎈
│ Saving 1 charts
│ Downloading postgresql from repo https://charts.bitnami.com/bitnami
│ Deleting outdated charts
└ Building chart dependencies (1.30 seconds)

Running time 160.32 seconds
Error: helm upgrade have failed: UPGRADE FAILED: execution error at (headless-cms/charts/postgresql/templates/secrets.yaml:17:24): 
PASSWORDS ERROR: The secret "headless-cms-postgres-staging" does not contain the key "postgres-password"
Error: The process '/runner/_work/_temp/werf-tools/werf' failed with exit code 1
```
