### ISSUE TITLE
Custom Mapper jar not getting picked up for token creation

### ISSUE THREAD

**Issue by happy0088** [bitnami/charts#14149]
### Name and Version

bitnami/keycloak appVersion: 20.0.1

### What steps will reproduce the bug?

**Upgrading from keycloak V14 to V20 using bitnami helms .**

I'm trying to implement a custom token mapper for adding additional info in the JWT generated.
I have created the jar and placed it under the folder "deployment" as an extravolume mount:
```yaml
extraVolumeMounts:
  - name: deployments
    mountPath: /opt/bitnami/keycloak/standalone/deployment
```
```yaml
initContainers: 
  - name: aws-cli
    image: amazon/aws-cli
    imagePullPolicy: IfNotPresent
    command:
      - sh
    args:
      - -c
      - |
        echo "Copying .jar from S3..."
        aws s3 cp s3://keycloak-configs/Tenant/custom-mapper-1.0-SNAPSHOT.jar /deployments
        aws s3 cp s3://keycloak-configs/Tenant/custom-happy-mapper-1.0-SNAPSHOT.jar /deployments
    volumeMounts:
      - name: deployments
        mountPath: /deployments
```

Jars:
custom-happy-mapper-1.0-SNAPSHOT.jar
custom-mapper-1.0-SNAPSHOT.jar 

Observation:
I can see the custom jar present in the location when I do ssh in the pod created.

Issue:
The JWT generated does not carry the additional info being added from the jar.

I don't know if it's even picking the jar from this location.

### What is the expected behavior?

The custom mapper jar should be picked up and used to generate the new JWTs

### What do you see instead?

The JWTs were created to carry the basic attributes and are missing the custom roles added in the custom mapper roles. 

### Additional information

Just wanted to mention that the same jar was working earlier with V14 of keycloak using bitnami helms, so I was wondering if there is any change in config or path with higher versions.
