### ISSUE TITLE
postgresql.postgresqlSharedPreloadLibraries doesn't add pg_stat_statements

### ISSUE THREAD

**Issue by gredwhite** [bitnami/charts#14142]
### Name and Version

bitnami/postgres 11.6.7

### What steps will reproduce the bug?

I use the following values.yaml but when I run it  - there are no pg_stat_statements extension in postgres but I expected it:
```yaml
postgresql:
  postgresqlSharedPreloadLibraries: "pgaudit,pg_stat_statements"   # <---- THIS LINE
  readReplicas:
    resources:
    limits:
      memory: 512Mi
      cpu: 512m
  volumePermissions:
    resources:
      requests:
        memory: 256Mi
        cpu: 256m
      limits:
        memory: 512Mi
        cpu: 512m
  auth:
    database: ***
    password: ***
    postgresPassword: ***
  metrics:
    customMetrics:
      pg_database:
        query: "SELECT pg_database.datname, pg_database_size(pg_database.datname) as size FROM pg_database"
        ...
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        ***
    resources:
      requests:
        memory: 256Mi
        cpu: 256m
      limits:
        memory: 512Mi
        cpu: 512m
  enabled: true
  nameOverride: *dbHost
  fullnameOverride: *dbHost
  primary:
    persistence:
        storageClass: nfs-dbp
        size: 1Gi
    initdb:
        user: ***
        password: ***
        scriptsConfigMap: ***
    extendedConfiguration: |
      shared_preload_libraries = 'pg_stat_statements' # (change requires restart)
      pg_stat_statements.max = 10000
      pg_stat_statements.track = all

    initdb:
      scriptsConfigMap: ***
    persistence:
      size: 1Gi
    resources:
      limits:
        memory: &postgresMemory 512Mi
        cpu: &postgresCpu 500m
      requests:
        memory: &postgresMemory 128Mi
        cpu: &postgresCpu 100m
```

### Are you using any custom parameters or values?

All mentioned in the previous section

### What is the expected behavior?

Run postgesql server instance and pg_stat_statements extension is enabled

### What do you see instead?

absence of pg_stat_statements extension
