### ISSUE TITLE
mkdir: cannot create directory '/bitnami/mariadb': Permission denied

### ISSUE THREAD

**Issue by crackers8199** [bitnami/charts#14147]
### Name and Version

bitnami/wordpress 15.2.22

### What steps will reproduce the bug?

mac os ventura 13.1
minikube: stable 1.28.0 (bottled), HEAD (installed via homebrew)
docker for mac version 4.15.0 (93002)
* Engine: 20.10.21
* Compose: v2.13.0
* Credential Helper: v0.7.0
* Kubernetes: v1.25.2
* Snyk: v1.1054.0

### Are you using any custom parameters or values?

this is similar to all of the many bugs referring to the issues with permissions on `/bitnami/mariadb/data`

https://github.com/bitnami/charts/issues/8565

8565 in particular references the mariadb chart, but my specific issue is with wordpress. I can resolve this on the mariadb chart by using initContainers as follows (as suggested elsewhere on the web):

```yaml
primary:
  initContainers:
    - name: mariadb-create-directory-structure
      image: busybox
      command:
        [
          "sh",
          "-c",
          "/bin/mkdir -p /bitnami/mariadb/data && /bin/chmod -R 777 /bitnami/mariadb",
        ]
      volumeMounts:
        - name: data
          mountPath: /bitnami/mariadb/data
```

when trying to install mariadb as part of the wordpress chart though, this isn't an option as there's no way that i've seen to run initContainers on the mariadb containers as a part of that install... ly WP

### What is the expected behavior?

mariadb should be installed and should work since you need it for wordpress.

### What do you see instead?

mariadb does not work. the container never starts because it can't access `/bitnami/mariadb/data`.

```
mbp2021 helm % k logs wordpress-mariadb-0
mariadb 01:52:03.03 
mariadb 01:52:03.06 Welcome to the Bitnami mariadb container
mariadb 01:52:03.08 Subscribe to project updates by watching https://github.com/bitnami/containers
mariadb 01:52:03.11 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mariadb 01:52:03.13 
mariadb 01:52:03.15 INFO  ==> ** Starting MariaDB setup **
mariadb 01:52:03.32 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 01:52:03.38 INFO  ==> Initializing mariadb database
mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied
```
