### ISSUE TITLE
Problem using wordpressSkipInstall as true using a wordpress multisite installation

### ISSUE THREAD

**Issue by Daivdson** [bitnami/charts#14156]
### Name and Version

bitnami/15.2.22 - wordpress-6.1.1

### What steps will reproduce the bug?

**1 in this environment**
A wordpress installation is made using an external bank with a wordpress multiste installation. When trying to upload wordpress with an existing bank with a wordpress multisite installation, he manages to establish the pod and finish the installation with the settings, however the wordpress multisite mode is not activated, considered only the main site of the bank.

**2 With this config**
```yaml
wordpress:
  image:
    tag: 6.1.1-debian-11-r19
  wordpressBlogName: Camara
  wordpressScheme: http
  wordpressSkipInstall: true
  wordpressConfigureCache: false
  wordpressUsername: admin
  existingSecret: credenciais-wordpress
  mariadb:
    enabled: false
  service:
    type: ClusterIP
  externalDatabase:
    host: host
    existingSecret: credenciais-wordpress
    database: portal-wordpress-v2-tes
    user: sepor
    port: 3306
  persistence:
    enabled: true
    storageClass: nfs-sepor
    size: 4Gi
  ingress:
    enabled: true
    apiVersion: networking.k8s.io/v1beta1
    hostname: portal-wordpress-v2-tes.leg.br
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: '0'
  multisite:
    enable: true
    host: portal-wordpress-v2-tes.leg.br
    networkType: subdirectory
```
    
**3 run**
Wordpress can be installed using chart by disabling the `wordpressSkipInstall` parameter to false. Then try to make a new installation but with `wordpressSkipInstall` as true and using the same external database, now with a multiste wordpress installation.

**4 See the error**
The installation will be finished ignoring the multisite settings due to the `wordpressSkipInstall` parameter, accessing the installation page the multisite mode has not been activated.

### What is the expected behavior?

When `wordpressSkipInstall` is set to true, the multisite configuration, if any, must not be ignored and the wordpress installation must be restored according to data from the external database.

### What do you see instead?

Multisite installation is ignored when using an external database with a wordpress multisite installation.

### Additional information

No
