### ISSUE TITLE
[bitnami/grafana-loki] "mkdir /loki: file exists"

### ISSUE THREAD

**Issue by ercansayici** [bitnami/charts#14173]
### Name and Version

2.5.2

### What steps will reproduce the bug?

Started Loki (image: bitnami/grafana-loki) (Storage-aws S3)
Started Fluent-bit to tail
Manually scaled up the querier replica.

### What is the expected behavior?

add a new querier  without any error.

### What do you see instead?

When I want to scale up the querier, a new querier instance is up but it gives the error "mkdir /loki: file exists".

### Additional information

to test it, I added ['sh', "-c", "rm -rf /loki"] as an argument into the values.yml file, and upgraded the helm chart, the error was gone. but I think It won't work with the autoscaling.

**Comment by aoterolorenzo** [comment]
Hi @ercansayici,

Could you provide the exact values you are using and a little more info deep into the steps to reproduce the issue?

**Comment by giosdas** [comment]
Hello,
Today I have encountered the same issue. I've resolved it with the change of these two settings in values.yaml:
```
loki:
  overrideConfiguration:
    storage_config:
      boltdb_shipper:
        active_index_directory: /tmp/loki_index
        cache_location: /tmp/loki_index_cache
```
Thanks
Regards
