### ISSUE TITLE
keycloakConfigCli in values.yaml don't create users

### ISSUE THREAD

**Issue by mamu-reply** [bitnami/charts#14184]
### Name and Version

bitnami/keycloak 12.1.5

### What steps will reproduce the bug?

If in values.yaml I configure users they don't appear on keycloak.
I've created a new realm with a new client and an IdP, and for users I've used this YAML form:
```yaml
users:
- username: test@test.com
  email: test@test.com
  emailVerified: true
  enabled: true
  federatedIdentities:
    - identityProvider: test_idp
      userId: test@test.com
      userName: test@test.com
```

it wasn't created, but if I will use the import from keycloak console it works, so the yaml form is correct.

### Are you using any custom parameters or values?

```yaml
ingress:
  enabled: 'true'
  annotations:
    cert-manager.io/cluster-issuer: 'cert-manager-letsencrypt-...'
    ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  path: /
  hostname: '...'
  tls: true
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraTls: []
  secrets: []
  extraRules: []
auth:
  adminUser: admin
  adminPassword: '...'
postgresql:
  enabled: true
  auth:
    postgresPassword: "..."  
    username: bn_keycloak
    password: "..."
    database: bitnami_keycloak
    existingSecret: ""
  architecture: standalone
keycloakConfigCli:
  enabled: true
  configuration:
    realm-configuration.yaml:
      realm: test
      enabled: true
      users:
      - username: service-account-...
        enabled: true
      - username: test@test.com
        email: test@test.com
        emailVerified: true
        enabled: true
        federatedIdentities:
          - identityProvider: test_idp
            userId: test@test.com
            userName: test@test.com
      clients:
         ...
```

I hid some pieces with **...** because they are private, but all the configuration works except for the users part

### What is the expected behavior?

See the user in the Keycloak user tab

### What do you see instead?

nothing

### Additional information

I'm trying to automatize the creation of an entire keycloak setup, with a realm, a client, some users and an IdP, and everything will be created correctly, but only the users don't appear, I've tried to import the users from the keycloak console manually, with the Partial Import button, and in this way work, but I need that the user creation will be done together with the rest.

**Comment by aoterolorenzo** [comment]
Hi @mamu-reply,

Seems like you are declaring the content of `the realm-configuration.yaml` in form of yaml object. Could you try to declare it as text using the `|`?

`realm-configuration.yaml: |`

```
    realm-configuration.yaml: |
      realm: test
      enabled: true
      users:
        - username: service-account-...
          enabled: true
        - username: test@test.com
          email: test@test.com
          emailVerified: true
          enabled: true
          federatedIdentities:
            - identityProvider: test_idp
              userId: test@test.com
              userName: test@test.com
      clients:
```

**Comment by jtele2** [comment]
I am also having issues running this.

```
helm upgrade keycloak bitnami/keycloak --version 13.0.3 -f ~/***/keycloak-override.yaml --namespace pathfinder --debug --install
history.go:56: [debug] getting history for release keycloak
Release "keycloak" does not exist. Installing it now.
install.go:178: [debug] Original chart version: "13.0.3"
install.go:195: [debug] CHART PATH: /home/ubuntu/.cache/helm/repository/keycloak-13.0.3.tgz

client.go:128: [debug] creating 11 resource(s)
client.go:299: [debug] Starting delete for "keycloak-keycloak-config-cli" Job
client.go:128: [debug] creating 1 resource(s)
client.go:529: [debug] Watching for changes to Job keycloak-keycloak-config-cli with timeout of 5m0s
client.go:557: [debug] Add/Modify event for keycloak-keycloak-config-cli: ADDED
client.go:596: [debug] keycloak-keycloak-config-cli: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:557: [debug] Add/Modify event for keycloak-keycloak-config-cli: MODIFIED
client.go:596: [debug] keycloak-keycloak-config-cli: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:557: [debug] Add/Modify event for keycloak-keycloak-config-cli: MODIFIED
client.go:596: [debug] keycloak-keycloak-config-cli: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:557: [debug] Add/Modify event for keycloak-keycloak-config-cli: MODIFIED
client.go:596: [debug] keycloak-keycloak-config-cli: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:557: [debug] Add/Modify event for keycloak-keycloak-config-cli: MODIFIED
client.go:596: [debug] keycloak-keycloak-config-cli: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
client.go:557: [debug] Add/Modify event for keycloak-keycloak-config-cli: MODIFIED
client.go:596: [debug] keycloak-keycloak-config-cli: Jobs active: 0, jobs failed: 1, jobs succeeded: 0
client.go:557: [debug] Add/Modify event for keycloak-keycloak-config-cli: MODIFIED
Error: failed post-install: job failed: BackoffLimitExceeded
helm.go:84: [debug] failed post-install: job failed: BackoffLimitExceeded
```

keycloak-override.yaml:
```
keycloakConfigCli:
  enabled: true
  configuration:
    realm1.yaml: |
      realm: test
      clients: []
```
