### ISSUE TITLE
[bitnami/grafana-operator] Validation error for "initContainers" into org.integreatly.v1alpha1.Grafana.spec

### ISSUE THREAD

**Issue by robmonct** [bitnami/charts#14180]
### Name and Version

bitnami/grafana-operator 2.7.13

### What steps will reproduce the bug?

Error: 

`error validating data: ValidationError(Grafana.spec): unknown field "initContainers" in org.integreatly.v1alpha1.Grafana.spec`

### Are you using any custom parameters or values?

```yaml
 grafana:
    initContainers:
     - name: grafana-plugins-init
       image: docker.io/bitnami/grafana:9.3.0-debian-11-r0
       imagePullPolicy: IfNotPresent
```

### What do you see instead?

Error to update the chart. 

### Additional information

It seems it's needed the new field into `org.integreatly.v1alpha1.Grafana.spec` after this PR: https://github.com/bitnami/charts/pull/14103
