### ISSUE TITLE
[bitnami/kafka] Cannot specify externalAccess.service.type=ClusterIP despite described in the documentation.

### ISSUE THREAD

**Issue by bigqi0812** [bitnami/charts#14195]
### Name and Version

bitnami/kafka Release 20.0.2 

### What steps will reproduce the bug?

Try to expose the kafka service via externalAccess.service.type of ClusterIP and with a TCP Ingress in place.
This is the section in my value.yaml
```yaml
externalAccess:
  enabled: true
  service:
    type: ClusterIP
```
This is my command
```
helm install si-kafka -f values.yaml bitnami/kafka -n kafka
```
This is the error message
```
Error: INSTALLATION FAILED: execution error at (kafka/templates/NOTES.txt:304:4):
VALUES VALIDATION:
kafka: externalAccess.service.type
    Available service type for external access are NodePort or LoadBalancer.
```
However, the documentation indicated that ClusterIP is a choice if one wants to connect kafka via a TCP Ingress
https://github.com/bitnami/charts/tree/main/bitnami/kafka/ (See "Using Cluster IP Service" section)

### Are you using any custom parameters or values?

Yes
```yaml
externalAccess:
  enabled: true
  service:
    type: ClusterIP
```
### What is the expected behavior?

It should allow using ClusterIP as externalAccess service type

### What do you see instead?
```
Validation error
Error: INSTALLATION FAILED: execution error at (kafka/templates/NOTES.txt:304:4):
VALUES VALIDATION:
kafka: externalAccess.service.type
    Available service type for external access are NodePort or LoadBalancer.
```

**Comment by Mauraza** [comment]
Hi @bigqi0812,

Did you specify the domain? please check this https://github.com/bitnami/charts/tree/main/bitnami/kafka#using-clusterip-services

**Comment by bigqi0812** [comment]
I just tried with a domain of non empty string, I still got the same error.
```
externalAccess:
   service:
     type: ClusterIP
     domain: ingress-ip
```
