### ISSUE TITLE
Port 9419 for prometheus metrics is hard coded in RabbitMQ Configuration file content specified in values.yaml

### ISSUE THREAD

**Issue by s-srakshe** [bitnami/charts#14212]
### Name and Version

bitnami/rabbitmq 11.3.0

### What steps will reproduce the bug?

In the chart values.yaml file. The 'configuration' object that specifies RabbitMQ Configuration file content, has the prometheus port harded coded to 9419. 
`prometheus.tcp.port = 9419`

Instead can be set as below. 
prometheus.tcp.port = {{ .Values.containerPorts.metrics }}

This is preventing the use of custom port no for metrics.

### Are you using any custom parameters or values?
```yaml
  containerPorts:
    metrics: 9090
  metrics:
    enabled: true
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9090"
      prometheus.io/path: "/metrics"
  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9090"
    ports:
      metrics: 9090
```
### What is the expected behavior?

Should be able to set custom port for prometheus metrics.

### What do you see instead?

Unable to use the custom port no 9090 for metrics. 
Due to hardcoding of port no 9419 through `prometheus.tcp.port = 9419`. Rabbitmq server is starting the prometheus listener on port 9419.
