### ISSUE TITLE
When enabling memcached, only the w3 plugin is installed, memcached itself is not deployed

### ISSUE THREAD

**Issue by conall88** [bitnami/charts#14229]
### Name and Version

bitnami/wordpress 15.2.22

### What steps will reproduce the bug?

Deploy via helm, passing in the following values.yaml.

helm get values output for the deployment:
 
```
externalCache:
memcached:
    memcached: 11211
    repository: bitnami/memcached
      repository: bitnami/memcached-exporter
      memcached: ""
      memcached: 11211
memcached.auth.enabled: true
memcached.auth.password: <removed>
memcached.auth.username: <removed>
memcached.enabled: true
wordpressConfigureCache: true
```

 

### Are you using any custom parameters or values?

#enable caching via w3

wordpressConfigureCache: true

#enable memcacheD

memcached.enabled: true
memcached.auth.enabled: true
memcached.auth.username: username
memcached.auth.password: password

### What is the expected behavior?

a Memcached instance should also be deployed.

### What do you see instead?

only the w3 total cache plugin is installed.
