### ISSUE TITLE
[bitnami/thanos] Thanos receive replication hashring configuration wrong

### ISSUE THREAD

**Issue by samox73** [bitnami/charts#14248]
### Name and Version

bitnami/thanos 11.6.8

### What steps will reproduce the bug?

1. Deploy with receive enabled and set to 3 replicas and replication factor 3
2. inspect the created hashring config

### Are you using any custom parameters or values?

```yaml
fullnameOverride: thanos
global:
  storageClass: "ebs-retain"
serviceAccount:
  create: false
  name: redacted
compactor:
  enabled: true
  serviceAccount:
    create: false
    name: redacted
  retentionResolutionRaw: 14d
  retentionResolution5m: 30d
  retentionResolution1h: 365d
storegateway:
  enabled: true
  serviceAccount:
    create: false
    name: redacted
  serviceAccountName: redacted
receive:
  enabled: true
  replicaCount: 3
  replicationFactor: 3
  serviceAccount:
    create: false
    name: redacted
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      memory: 4Gi
  tsdbRetention: 4h
  persistence:
    size: redacted
  ingress:
    enabled: true
    hostname: redacted
    annotations: redacted
    extraHosts:
      - name: redacted
      - name: redacted
    pathType: Prefix
query:
  enabled: true
  serviceAccount:
    create: false
    name: redacted
objstoreConfig: redacted
```

### What is the expected behavior?

That the helm chart manages the replicas itself and creates a valid hashring json.

### What do you see instead?

Replicas do not know about each other since the hashring config contains only the local thanos component.

### Additional information

Is the chart expected to handle multiple replicas by itself? As I see it, the hashring config would have to contain N service names that point to the N respective replicas. For that to work there would have to be N different `StatefulSet`s, since the "service-per-replica" approach of `StatefulSet`s is not how kubernetes envisions `StatefulSet`s being used. I also think that the documentation of the respective values of the chart should go into a little more detail. Obviously just setting `replicas: 3` and `replicationFactor: 3` does not work out of the box.
