### ISSUE TITLE
[bitnami/postgresql] there are not all metrics from charts

### ISSUE THREAD

**Issue by GorSarg** [bitnami/charts#14250]
### Name and Version

bitnami/postgresql 10.16.2; bitnami/mongodb 11.1.10

### What steps will reproduce the bug?

I could not find all metrics from mongodb and postgres. my values yaml files are

postgres

```
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

    
mongodb

```
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

The instances are operational, but there aren't many metrics available. Is it possible to investigate problems? Perhaps there are some other flags I should include.

### Are you using any custom parameters or values?

postgres
```
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```
    
mongodb
```
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

### What is the expected behavior?

see all metrics

### What do you see instead?

a couple of them
