### ISSUE TITLE
[bitnami/keycloak] keycloakConfigCli unable to access jarfile

### ISSUE THREAD

**Issue by chri4774** [bitnami/charts#14279]
### Name and Version

bitnami/keycloak 13.0.0

### What steps will reproduce the bug?

- Enable keycloakConfigCli in helm values
- install the keycloak helm chart
- The keycloak-keycloak-config-cli job fails with error `Error: Unable to access jarfile /opt/bitnami/keycloak-config-cli/keycloak-config-cli-20.0.2.jar`

When you inspect the docker image of the keycloakConfigCli pod you can see that there is no keycloak-config-cli-20.0.2.jar inside the docker image docker.io/bitnami/keycloak-config-cli:5.5.0-debian-11-r12
This is also the case for the latest keycloak-config-cli image from docker hub with tag 5.5.0-debian-11-r19
```console
$ sudo docker run --entrypoint bash --rm -it docker.io/bitnami/keycloak-config-cli:5.5.0-debian-11-r12
Unable to find image 'docker.io/bitnami/keycloak-config-cli:5.5.0-debian-11-r12' locally
Trying to pull repository docker.io/bitnami/keycloak-config-cli ...
5.5.0-debian-11-r12: Pulling from docker.io/bitnami/keycloak-config-cli
f8c1c832ce65: Already exists
eff619273fd6: Already exists
Digest: sha256:dacd3e51eac29923ef84addb40c945ac5e16f7d7a172193609569f569db549e2
Status: Downloaded newer image for docker.io/bitnami/keycloak-config-cli:5.5.0-debian-11-r12

I have no name!@d19e0f14182b:/opt/bitnami/keycloak-config-cli$ ls -l
total 77152
-rw-r--r--. 1 root root 19744842 Nov 12 12:20 keycloak-config-cli-17.0.1.jar
-rw-r--r--. 1 root root 19746655 Nov 12 12:20 keycloak-config-cli-18.0.2.jar
-rw-r--r--. 1 root root 19749083 Nov 12 12:21 keycloak-config-cli-19.0.3.jar
-rw-r--r--. 1 root root 19758510 Nov 12 12:21 keycloak-config-cli-20.0.1.jar
lrwxrwxrwx. 1 root root       63 Nov 12 12:21 keycloak-config-cli.jar -> /opt/bitnami/keycloak-config-cli/keycloak-config-cli-20.0.1.jar
drwxr-xr-x. 2 root root       43 Nov 12 12:41 licenses
```

### Are you using any custom parameters or values?
```yaml
keycloakConfigCli:
  enabled: true
  existingConfigmap: "keycloak-realm"
  extraEnvVars:
  - name: IMPORT_BEHAVIORS_SYNC_USER_FEDERATION
    value: "true"
  - name: KEYCLOAK_AVAILABILITYCHECK_TIMEOUT
    value: "300s"
```
### What is the expected behavior?

The keycloakConfigCli job should work without any command overrides in the helm values.yaml

### What do you see instead?

The keycloak-keycloak-config-cli job fails. The error message of the pod is
`Error: Unable to access jarfile /opt/bitnami/keycloak-config-cli/keycloak-config-cli-20.0.2.jar`

### Additional information

My workaround is to override the command in the helm values.yaml
```yaml
keycloakConfigCli:
  command:
  - java
  - -jar
  - /opt/bitnami/keycloak-config-cli/keycloak-config-cli.jar
```
