### ISSUE TITLE
bitnami/airflow Support webserver_config.py

### ISSUE THREAD

**Issue by calvinlu3** [bitnami/charts#14297]
### Name and Version

bitnami/airflow:latest

### What is the problem this feature will solve?

I would like to modify some variables in webserver_config.py to enable user registration as described here https://airflow.apache.org/docs/apache-airflow/stable/security/webserver.html#other-methods. I can't find a way to pass in the variables through helm chart.

### What is the feature you are proposing to solve the problem?

Allow me to configure webserver_config.py

### What alternatives have you considered?

I have tried creating a configmap like below:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: airflow-webserver-config
data:
  webserver_config.py: |
    - AUTH_USER_REGISTRATION: true
    - AUTH_USER_REGISTRATION_ROLE: Public
    - MAIL_SERVER: smtp.gmail.com
    - MAIL_USE_TLS: true
    - MAIL_USERNAME: 
    - MAIL_PASSWORD: 
    - MAIL_SENDER: 
 ```

and passing it `web.extraEnvVarsCM` like such:
```
web:
  extraEnvVarsCM: airflow-webserver-config
```
When I installed the chart, the `webserver_config.py` file contains the following:
```
# Config for Flask-Mail necessary for user self registration
# MAIL_SERVER = 'smtp.gmail.com'
# MAIL_USE_TLS = True
# MAIL_USERNAME = 'yourappemail@gmail.com'
# MAIL_PASSWORD = 'passwordformail'
# MAIL_DEFAULT_SENDER = 'sender@gmail.com'

# The default user self registration role
```

There used to `airflow.auth.webserverConfigMap`, but that has been removed.
