### ISSUE TITLE
[bitnami/postgresql-ha] In fail-our scenario when master failed next standby is not becoming master

### ISSUE THREAD

**Issue by Deepanshu6dec** [bitnami/charts#14311]
### Name and Version

bitnami/postgresql-ha

### What steps will reproduce the bug?

Helm Install: 

```helm install postgresql-ha -f custom-10.0.5-values.yaml bitnami/postgresql-ha --version 10.0.5 -n default```

```
# Pods status
CMD: kgp

NAME                                   READY   STATUS    RESTARTS      AGE   IP             NODE           NOMINATED NODE   READINESS GATES
postgresql-ha-pgpool-695c5677d-rs4ps   1/1     Running   0             80m   10.244.4.123   k8swn4   <none>           <none>
postgresql-ha-postgresql-0             1/1     Running   0             80m   10.244.3.128   k8swn5   <none>           <none>
postgresql-ha-postgresql-1             1/1     Running   1 (79m ago)   80m   10.244.1.166   k8swn3   <none>           <none>
postgresql-ha-postgresql-2             1/1     Running   1 (79m ago)   80m   10.244.5.195   k8swn1   <none>           <none>

```

```
# terminating the Master Pod

CMD: k delete po postgresql-ha-postgresql-0

pod "postgresql-ha-postgresql-0" deleted

```

```
# exec into the pod

k exec -it postgresql-ha-postgresql-0 -- bash

# Checking logs 

I have no name!@postgresql-ha-postgresql-0:/$ . /opt/bitnami/scripts/postgresql-env.sh
I have no name!@postgresql-ha-postgresql-0:/$ . /opt/bitnami/scripts/libpostgresql.sh
I have no name!@postgresql-ha-postgresql-0:/$ postgresql_enable_nss_wrapper
postgresql 12:27:46.14 DEBUG ==> Configuring libnss_wrapper...
I have no name!@postgresql-ha-postgresql-0:/$ repmgr service status -f /opt/bitnami/repmgr/conf/repmgr.conf
 ID | Name                       | Role    | Status               | Upstream                     | repmgrd | PID | Paused? | Upstream last seen
----+----------------------------+---------+----------------------+------------------------------+---------+-----+---------+--------------------
1000 | postgresql-ha-postgresql-0 | primary | * running            |                              | running | 1   | no      | n/a                
 1001 | postgresql-ha-postgresql-1 | standby | ! running as primary |                              | running | 1   | no      | n/a                
 1002 | postgresql-ha-postgresql-2 | standby |   running            | ! postgresql-ha-postgresql-1 | running | 1   | no      | 1 second(s) ago  

WARNING: following issues were detected
  - node "postgresql-ha-postgresql-1" (ID: 1001) is registered as standby but running as primary
  - node "postgresql-ha-postgresql-2" (ID: 1002) reports a different upstream (reported: "postgresql-ha-postgresql-1", expected "postgresql-ha-postgresql-0")

```

1000 - Postgresql-0  - Still running as Master 
1001 - postgresql-1 -  showing standby 

Postgresql-1 pod should be running as Master (primary)

``` 
# Cluster events

I have no name!@postgresql-ha-postgresql-0:/$ repmgr cluster event -f /opt/bitnami/repmgr/conf/repmgr.conf
 Node ID | Name                       | Event                  | OK | Timestamp           | Details                                                                                                                                                       
---------+----------------------------+------------------------+----+---------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000    | postgresql-ha-postgresql-0 | repmgrd_start          | t  | 2023-01-12 12:25:14 | monitoring cluster primary "postgresql-ha-postgresql-0" (ID: 1000)                                                                                            
 1002    | postgresql-ha-postgresql-2 | repmgrd_start          | t  | 2023-01-12 11:05:35 | monitoring connection to upstream node "postgresql-ha-postgresql-0" (ID: 1000)                                                                                
 1002    | postgresql-ha-postgresql-2 | standby_follow         | t  | 2023-01-12 11:05:32 | standby attached to upstream node "postgresql-ha-postgresql-0" (ID: 1000)                                                                                     
 1000    | postgresql-ha-postgresql-0 | child_node_new_connect | t  | 2023-01-12 11:05:32 | new standby "postgresql-ha-postgresql-2" (ID: 1002) has connected                                                                                             
 1002    | postgresql-ha-postgresql-2 | standby_register       | t  | 2023-01-12 11:05:30 | standby registration succeeded; upstream node ID is 1000 (-F/--force option was used)                                                                         
 1000    | postgresql-ha-postgresql-0 | child_node_new_connect | t  | 2023-01-12 11:05:26 | new standby "postgresql-ha-postgresql-1" (ID: 1001) has connected                                                                                             
 1002    | postgresql-ha-postgresql-2 | standby_clone          | t  | 2023-01-12 11:05:24 | cloned from host "postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local", port 5432; backup method: pg_basebackup; --force: Y
 1001    | postgresql-ha-postgresql-1 | repmgrd_start          | t  | 2023-01-12 11:05:24 | monitoring connection to upstream node "postgresql-ha-postgresql-0" (ID: 1000)                                                                                
 1001    | postgresql-ha-postgresql-1 | standby_follow         | t  | 2023-01-12 11:05:21 | standby attached to upstream node "postgresql-ha-postgresql-0" (ID: 1000)                                                                                     
 1000    | postgresql-ha-postgresql-0 | child_node_new_connect | t  | 2023-01-12 11:05:20 | new standby "postgresql-ha-postgresql-1" (ID: 1001) has connected                                                                                             
 1001    | postgresql-ha-postgresql-1 | standby_register       | t  | 2023-01-12 11:05:18 | standby registration succeeded; upstream node ID is 1000 (-F/--force option was used)                                                                         
 1001    | postgresql-ha-postgresql-1 | standby_clone          | t  | 2023-01-12 11:05:13 | cloned from host "postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local", port 5432; backup method: pg_basebackup; --force: Y
 1000    | postgresql-ha-postgresql-0 | repmgrd_start          | t  | 2023-01-12 11:04:25 | monitoring cluster primary "postgresql-ha-postgresql-0" (ID: 1000)                                                                                            
 1000    | postgresql-ha-postgresql-0 | primary_register       | t  | 2023-01-12 11:04:17 |                                                                                                                                                               
 1000    | postgresql-ha-postgresql-0 | cluster_created        | t  | 2023-01-12 11:04:17 | 

```

### Are you using any custom parameters or values?

Providing custom password and initdconfigMaps

```yaml
USER-SUPPLIED VALUES:
clusterDomain: cluster.local
commonAnnotations: {}
commonLabels: null
diagnosticMode:
  args:
  - infinity
  command:
  - sleep
  enabled: false
extraDeploy: []
fullnameOverride: ""
global:
  imagePullSecrets: []
  imageRegistry: ""
  ldap:
    bindpw: ""
    existingSecret: ""
  pgpool:
    adminPassword: ""
    adminUsername: ""
    existingSecret: ""
  postgresql:
    database: ""
    existingSecret: ""
    password: ""
    repmgrDatabase: ""
    repmgrPassword: ""
    repmgrUsername: ""
    username: ""
  storageClass: nfs-provisioner
kubeVersion: ""
ldap:
  basedn: ""
  binddn: ""
  bindpw: ""
  bslookup: ""
  enabled: false
  existingSecret: ""
  nssInitgroupsIgnoreusers: root,nslcd
  scope: ""
  tlsReqcert: ""
  uri: ""
metrics:
  annotations:
    prometheus.io/port: "9187"
    prometheus.io/scrape: "true"
  containerPorts:
    http: 9187
  customLivenessProbe: {}
  customMetrics: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  enabled: false
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  image:
    debug: false
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/postgres-exporter
    tag: 0.11.1-debian-11-r27
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  podSecurityContext:
    enabled: true
    runAsUser: 1001
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  resources:
    limits: {}
    requests: {}
  service:
    clusterIP: ""
    externalTrafficPolicy: Cluster
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    nodePorts:
      metrics: ""
    ports:
      metrics: 9187
    type: ClusterIP
  serviceMonitor:
    annotations: {}
    enabled: false
    honorLabels: false
    interval: ""
    jobLabel: ""
    labels: {}
    metricRelabelings: []
    namespace: ""
    relabelings: []
    scrapeTimeout: ""
    selector:
      prometheus: kube-prometheus
  startupProbe:
    enabled: false
    failureThreshold: 10
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
nameOverride: ""
namespaceOverride: ""
networkPolicy:
  allowExternal: true
  egressRules:
    customRules: []
    denyConnectionsToExternal: false
  enabled: false
persistence:
  accessModes:
  - ReadWriteMany
  annotations: {}
  enabled: true
  existingClaim: ""
  labels: {}
  mountPath: /bitnami/postgresql
  selector: {}
  size: 5Gi
  storageClass: null
pgpool:
  adminPassword: ""
  adminUsername: admin
  affinity: {}
  args: []
  authenticationMethod: scram-sha-256
  childLifeTime: ""
  childMaxConnections: ""
  clientIdleLimit: ""
  clientMinMessages: error
  command: []
  configuration: ""
  configurationCM: ""
  connectionLifeTime: ""
  containerPorts:
    postgresql: 5432
  containerSecurityContext:
    enabled: true
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1001
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  customUsers: {}
  customUsersSecret: ""
  existingSecret: ""
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  image:
    debug: false
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: registry.csmsc.net:5000
    repository: pgpool
    tag: 4.3.3
  initContainers: []
  initdbScripts: {}
  initdbScriptsCM: null
  initdbScriptsSecret: ""
  labels: {}
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  loadBalancingOnWrite: transaction
  logConnections: false
  logHostname: true
  logLinePrefix: ""
  logPerNodeStatement: false
  maxPool: ""
  minReadySeconds: ""
  nodeAffinityPreset:
    key: ""
    type: ""
    values: []
  nodeSelector: {}
  numInitChildren: ""
  passwords: smsc1234
  pdb:
    create: false
    maxUnavailable: ""
    minAvailable: 1
  podAffinityPreset: ""
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  priorityClassName: ""
  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 1
  reservedConnections: 1
  resources:
    limits: {}
    requests: {}
  schedulerName: ""
  serviceLabels: {}
  sidecars: []
  srCheckDatabase: postgres
  startupProbe:
    enabled: false
    failureThreshold: 10
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  terminationGracePeriodSeconds: ""
  tls:
    autoGenerated: false
    certCAFilename: ""
    certFilename: ""
    certKeyFilename: ""
    certificatesSecret: ""
    enabled: false
    preferServerCiphers: true
  tolerations: []
  topologySpreadConstraints: []
  updateStrategy: {}
  useLoadBalancing: true
  usePasswordFile: ""
  usernames: smsc
postgresql:
  affinity: {}
  args: []
  audit:
    clientMinMessages: error
    logConnections: false
    logDisconnections: false
    logHostname: true
    logLinePrefix: ""
    logTimezone: ""
    pgAuditLog: ""
    pgAuditLogCatalog: "off"
  command: []
  configuration: ""
  configurationCM: ""
  containerPorts:
    postgresql: 5432
  containerSecurityContext:
    enabled: true
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1001
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  database: csmsc
  dbUserConnectionLimit: ""
  existingSecret: ""
  extendedConf: ""
  extendedConfCM: null
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraInitContainers: []
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  hostIPC: false
  hostNetwork: false
  image:
    debug: true
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: registry.csmsc.net:5000
    repository: postgresql-repmgr
    tag: 9.6.24
  initContainers: []
  initdbScriptsCM: psql-tabletest
  initdbScriptsSecret: ""
  labels: {}
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  maxConnections: ""
  nodeAffinityPreset:
    key: ""
    type: ""
    values: []
  nodeSelector: {}
  password: smsc1234
  pdb:
    create: false
    maxUnavailable: ""
    minAvailable: 1
  pgHbaConfiguration: ""
  pgHbaTrustAll: false
  pghbaRemoveFilters: ""
  podAffinityPreset: ""
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  postgresConnectionLimit: ""
  postgresPassword: smsc1234
  priorityClassName: ""
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 3
  repmgrChildNodesCheckInterval: 5
  repmgrChildNodesConnectedMinCount: 1
  repmgrChildNodesDisconnectTimeout: 30
  repmgrConfiguration: ""
  repmgrConnectTimeout: 10
  repmgrDatabase: repmgr
  repmgrFenceOldPrimary: false
  repmgrLogLevel: NOTICE
  repmgrPassfilePath: ""
  repmgrPassword: smsc1234
  repmgrReconnectAttempts: 8
  repmgrReconnectInterval: 5
  repmgrUsePassfile: ""
  repmgrUsername: repmgr
  resources:
    limits: {}
    requests: {}
  schedulerName: ""
  sharedPreloadLibraries: pgaudit, repmgr
  sidecars: []
  startupProbe:
    enabled: false
    failureThreshold: 10
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  statementTimeout: ""
  syncReplication: false
  tcpKeepalivesCount: ""
  tcpKeepalivesIdle: ""
  tcpKeepalivesInterval: ""
  terminationGracePeriodSeconds: ""
  tls:
    certFilename: ""
    certKeyFilename: ""
    certificatesSecret: ""
    enabled: false
    preferServerCiphers: true
  tolerations: []
  topologySpreadConstraints: []
  updateStrategy:
    type: RollingUpdate
  upgradeRepmgrExtension: false
  usePasswordFile: ""
  usePgRewind: false
  username: smsc
psp:
  create: false
rbac:
  create: false
  rules: []
service:
  annotations: {}
  clusterIP: ""
  externalTrafficPolicy: Cluster
  extraPorts: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  nodePorts:
    postgresql: ""
  portName: postgresql
  ports:
    postgresql: 5432
  serviceLabels: {}
  sessionAffinity: None
  sessionAffinityConfig: {}
  type: ClusterIP
serviceAccount:
  annotations: {}
  automountServiceAccountToken: true
  create: false
  name: ""
volumePermissions:
  enabled: false
  image:
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 11-debian-11-r50
  podSecurityContext:
    runAsUser: 0
  resources:
    limits: {}
    requests: {}
```

### What is the expected behavior?

When master failed next standby replica will became primary and work flawless 

### What do you see instead?

It is showing fail our master is still showing as primary
