### ISSUE TITLE
rough new-line is added to the provisioning job in minio 11.10.25

### ISSUE THREAD

**Issue by cedi** [bitnami/charts#14351]
### Name and Version

bitnami/minio 11.10.25

### What steps will reproduce the bug?

Deploying minio with `provisioning.enabled` set to `true`.
The job will fail with the following error message: 

```plaintext
Waiting for Minio
the required argument `port` was not provided
```

### Are you using any custom parameters or values?

```yaml
provisioning:
  enabled: true

  usersExistingSecrets:
    - minio-users

  buckets:
    - name: mimir-tsdb
      versioning: false
      withLock: false
      tags:
        app: mimir
    - name: mimir-ruler
      versioning: false
      withLock: false
      tags:
        app: mimir
    - name: mimir-alert
      versioning: false
      withLock: false
      tags:
        app: mimir
```

### What is the expected behavior?

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-provisioning
  namespace: minio
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: minio-provisioning
        job-name: minio-provisioning
    spec:
      initContainers:
        - command:
            - /bin/bash
            - '-c'
            - |-
              set -e;
              echo "Waiting for Minio";
              wait-for-port \
                --host=minio \
                --state=inuse \
                --timeout=120 \
                9000;
              echo "Minio is available";
          image: 'docker.io/bitnami/minio:2022.12.12-debian-11-r9'
          imagePullPolicy: IfNotPresent
          name: wait-for-available-minio
```

### What do you see instead?

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-provisioning
  namespace: minio
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: minio-provisioning
        job-name: minio-provisioning
    spec:
      initContainers:
        - command:
            - /bin/bash
            - '-c'
            - |-
              set -e; echo "Waiting for Minio"; wait-for-port \

                --host=minio \
                --state=inuse \
                --timeout=120 \
                9000;
              echo "Minio is available";
          image: 'docker.io/bitnami/minio:2022.12.12-debian-11-r9'
          imagePullPolicy: IfNotPresent
          name: wait-for-available-minio
```

### Additional information

The Bug is in `bitnami/minio/templates/provisioning-job.yaml` where in the `initContainer.command` the `>-` expression is used, where `|-` should be used.
