### ISSUE TITLE
[bitnami/mastodon] init never finishes

### ISSUE THREAD

**Issue by digitalbuddha** [bitnami/charts#14366]
### Name and Version

bitnami/mastodon

### What steps will reproduce the bug?

deploying into k3s on hetzner after terraforming using https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/kube.tf.example

 ```
helm install mastodon -f values.yaml my-repo/mastodon --debug --kubeconfig k3s_kubeconfig.yaml --timeout 20m
```
### Are you using any custom parameters or values?
```yaml
//I removed all keys from below otherwise this is my values.yaml
global:
  storageClass: "longhorn"
## Mastodon Bitnami chart values
## @section Mastodon common parameters
##
## Enable diagnostic mode in the deployment
##
diagnosticMode:
  ## @param diagnosticMode.enabled Enable diagnostic mode (all probes will be disabled and the command will be overridden)
  ##
  enabled: false
  ## @param diagnosticMode.command Command to override all containers in the deployment
  ##
  command:
    - sleep
  ## @param diagnosticMode.args Args to override all containers in the deployment
  ##
  args:
    - infinity

## @param adminUser Mastodon admin username
## [REQUIRED]
adminUser: "****"
## @param adminEmail Mastodon admin email
## [REQUIRED]
adminEmail: "****"
## @param adminPassword Mastodon admin password
## [REQUIRED]
adminPassword: "password"

## @param enableSearches Enable the search engine (uses Elasticsearch under the hood)
##
enableSearches: false

## @param enableS3 Enable the S3 storage engine
##
enableS3: true

## @param webDomain Web domain for Mastodon
## [REQUIRED]
webDomain: "***"

persistence:
  enabled: true
  storageClass: "longhorn"



## @section Mastodon Web Parameters
##
web:
  ## @param web.replicaCount Number of Mastodon web replicas to deploy
  ##
  replicaCount: 2

## @section Mastodon Sidekiq Parameters
##
sidekiq:
  ## @param sidekiq.replicaCount Number of Mastodon sidekiq replicas to deploy
  ##
  replicaCount: 4

## @section Mastodon Streaming Parameters
##
streaming:
  ## @param streaming.replicaCount Number of Mastodon streaming replicas to deploy
  ##
  replicaCount: 1

## @section External PostgreSQL configuration
##
## All of these values are only used when postgresql.enabled is set to false
## @param externalDatabase.host Database host
## @param externalDatabase.port Database port number
## @param externalDatabase.user Non-root username for JupyterHub
## @param externalDatabase.password Password for the non-root username for JupyterHub
## @param externalDatabase.database JupyterHub database name
## @param externalDatabase.existingSecret Name of an existing secret resource containing the database credentials
## @param externalDatabase.existingSecretPasswordKey Name of an existing secret key containing the database credentials
##

## @section External S3 parameters
## All of these values are only used when redis.enabled is set to false
## @param externalS3.host External S3 host
## @param externalS3.port External S3 port number
## @param externalS3.accessKeyID External S3 access key ID
## @param externalS3.accessKeySecret External S3 access key secret
## @param externalS3.existingSecret Name of an existing secret resource containing the S3 credentials
## @param externalS3.existingSecretAccessKeyIDKey Name of an existing secret key containing the S3 access key ID
## @param externalS3.existingSecretKeySecretKey Name of an existing secret key containing the S3 access key secret
## @param externalS3.protocol External S3 protocol
## @param externalS3.bucket External S3 bucket
## @param externalS3.region External S3 region
##
externalS3:
  # S3 endpoint
  host: "s3.us-west-004.backblazeb2.com"
  port: 443
  accessKeyID: "***"
  accessKeySecret: "***"
  protocol: "https"
  bucket: "***"

## @section Redis sub-chart parameters
##
redis:
  ## @param redis.enabled Deploy Redis subchart
  ##
  enabled: true


## @section PostgreSQL chart configuration
## ref: https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
## @param postgresql.enabled Switch to enable or disable the PostgreSQL helm chart
postgresql:
  enabled: true

## @section Elasticsearch chart configuration
## https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/values.yaml
##
elasticsearch:
  ## @param elasticsearch.enabled Whether to deploy a elasticsearch server to use as Mastodon's search engine
  ## To use an external server set this to false and configure the externalElasticsearch parameters
  ##
  enabled: false

## MinIO chart parameters
## For full list of MinIO values configurations please refer to https://github.com/bitnami/charts/tree/main/bitnami/minio
##
minio:
  ## Enable/disable MinIO chart installation
  ## to be used as an objstore for Mastodon
  ##
  enabled: false  

## Apache chart configuration
##
apache:
  ## Enable Apache chart
  ##
  enabled: true  
```
### What is the expected behavior?

create a mastodon deployment

### What do you see instead?

```
m2-mastodon-init-xl7mv                   1/2     NotReady    3 (31s ago)     14m
```

```
Containers:
  migrate-and-create-admin:
    Container ID:  containerd://30416a74602fcf25ea9504852c3bfd24ff27b0cd92d25cda244f952908b53156
    Image:         docker.io/bitnami/mastodon:4.0.2-debian-11-r7
    Image ID:      docker.io/bitnami/mastodon@sha256:5ea7462cd2ff48796ccb3883cba563757b1f64aa976a72a1cb68ea1b0467a43d
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
      -ec
    Args:
      /scripts/migrate-and-create-admin.sh
    State:          Running
      Started:      Sun, 15 Jan 2023 12:53:44 -0500
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sun, 15 Jan 2023 12:49:42 -0500
      Finished:     Sun, 15 Jan 2023 12:53:43 -0500
    Ready:          True
    Restart Count:  1
    Environment Variables from:
      m1-mastodon-default  ConfigMap  Optional: false
      m1-mastodon-default  Secret     Optional: false
    Environment:
      BITNAMI_DEBUG:               false
      MASTODON_DATABASE_PASSWORD:  <set to the key 'password' in secret 'm1-postgresql'>   Optional: false
      MASTODON_REDIS_PASSWORD:     <set to the key 'redis-password' in secret 'm1-redis'>  Optional: false
    Mounts:
      /scripts from scripts (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-rmkwd (ro)
```

### Additional information

All other steps succeed but the init script seems to just hang and retry over and over again. `/scripts/migrate-and-create-admin.sh` is the script in question.

Is there something I need to do for this to work?
