### ISSUE TITLE
[bitnami/thanos] how to add index-cache.yml to the thanos values.yaml

### ISSUE THREAD

**Issue by Hello-Linux** [bitnami/charts#14362]
### Name and Version

bitnami/thanos11.6.8

### What steps will reproduce the bug?

1. I create a configmap that includes the _index-cache.yml_, his name is thanos-store-gateway-index-cache, and I config this name in the chart _values.yml_, but the thanos-store-gateway can't start, and shows 
```
level=error ts=2023-01-15T05:07:37.198869106Z caller=main.go:135 err="open /conf/index-cache.yml: no such file or directory\nloading file /conf/index-cache.yml for index-cache.config-file\ngithub.com/efficientgo/tools/extkingpin.(*PathOrContent).Content\n\t/go/pkg/mod/github.com/efficientgo/tools/extkingpin@v0.0.0-20220817170617-6c25e3b627dd/pathorcontent.go:79\nmain.runStore\n\t/app/cmd/thanos/store.go:283\nmain.registerStore.func1\n\t/app/cmd/thanos/store.go:198\nmain.main\n\t/app/cmd/thanos/main.go:133\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594\nget content of index cache configuration\nmain.runStore\n\t/app/cmd/thanos/store.go:285\nmain.registerStore.func1\n\t/app/cmd/thanos/store.go:198\nmain.main\n\t/app/cmd/thanos/main.go:133\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594\npreparing store command failed\nmain.main\n\t/app/cmd/thanos/main.go:135\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594"
```
my configmap content is
```
apiVersion: v1
data:
  index-cache.yml: |
    type: IN-MEMORY
    config:
      max_size: 512MB
      max_item_size: 125MB
kind: ConfigMap
metadata:
  creationTimestamp: "2023-01-14T13:57:55Z"
  name: thanos-store-gateway-index-cache
  namespace: monitoring
```
and the chart values.yml file is
```yaml
indexCacheConfig: "thanos-store-gateway-index-cache"
## @param bucketCacheConfig The [bucket cache configuration](https://thanos.io/tip/components/store.md/)
## Specify content for bucket-cache.yml
##
```
How can I customize the index memory cache in the values.yml file?

**Comment by Hello-Linux** [comment]
@carrodher @rafariossaa

**Comment by CeliaGMqrz** [comment]
Hi @Hello-Linux, 

Thanks for your comments. Sorry, I can't reproduce the problem. 

I have tested this scenario with your config map like this:

I create a thanos.yaml with your content

```yaml
extraDeploy:
  - apiVersion: v1
    data:
      index-cache.yml: |
        type: IN-MEMORY
        config:
          max_size: 512MB
          max_item_size: 125MB
    kind: ConfigMap
    metadata:
      creationTimestamp: "2023-01-14T13:57:55Z"
      name: thanos-store-gateway-index-cache
      namespace: monitoring

indexCacheConfig: "thanos-store-gateway-index-cache"
```
I have created the namespace and installed the chart

```shell
$ kubectl create namespace monitoring
$ helm install thanos bitnami/thanos  -f thanos.yaml -n monitoring
```

Output:
```yaml
$ kubectl get configmaps -n monitoring 
NAME                               DATA   AGE
kube-root-ca.crt                   1      15m
thanos-store-gateway-index-cache   1      15m

$ kubectl describe configmaps/thanos-store-gateway-index-cache -n monitoring
Name:         thanos-store-gateway-index-cache
Namespace:    monitoring
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: thanos
              meta.helm.sh/release-namespace: monitoring

Data
====
index-cache.yml:
----
type: IN-MEMORY
config:
  max_size: 512MB
  max_item_size: 125MB


BinaryData
====

Events:  <none>
```

The chart is deployed correctly.
Can you check if the config map has been created correctly? To make sure, you can run:

```shell
$ kubectl get configmaps -n yournamespace
$ kubectl describe configmaps/thanos-store-gateway-index-cache -n monitoring
```
However, you can set indexCacheConfig like this, in values.yaml

```yaml
## @param indexCacheConfig The [index cache configuration](https://thanos.io/tip/components/store.md/)
## Specify content for index-cache.yml
##
indexCacheConfig: |
      - type: IN-MEMORY
        config:
          max_size: 512MB
          max_item_size: 125MB
```

**Comment by Hello-Linux** [comment]
@CeliaGMqrz I still have problems according to your configuration
<img width="899" alt="截屏2023-02-11 下午12 44 17" src="https://user-images.githubusercontent.com/17851645/218240492-a7fe3009-3fd6-49b1-87de-f84737bf2fe7.png">
and the error is below
<img width="1166" alt="截屏2023-02-11 下午12 45 19" src="https://user-images.githubusercontent.com/17851645/218240537-034e8233-4242-4cf2-822c-47900ec62924.png">

**Comment by CeliaGMqrz** [comment]
Hi @Hello-Linux, 

I'm sorry, I didn't activate the store-gateway option. However, I have now added the index-cache config to values.yaml. The issue is that the indexCacheConfig param is not set with a configmap instead the configuration is injected directly. Can you try this config in values.yaml?

```.yaml
## @param indexCacheConfig The [index cache configuration](https://thanos.io/tip/components/store.md/)
## Specify content for index-cache.yml
##
indexCacheConfig: |-
  type: IN-MEMORY
  config:
    max_size: 512MB
    max_item_size: 125MB
```
Storegateway is enabled and it works correctly.
```
NAME                                         READY   STATUS    RESTARTS   AGE
pod/thanos-query-685b797b8-tkvkh             1/1     Running   0          9m33s
pod/thanos-query-frontend-58c764fdf6-cv4kk   1/1     Running   0          9m33s
pod/thanos-storegateway-0                    1/1     Running   0          9m33s

NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)              AGE
service/thanos-query            ClusterIP   10.101.137.143   <none>        9090/TCP             9m33s
service/thanos-query-frontend   ClusterIP   10.111.173.172   <none>        9090/TCP             9m33s
service/thanos-query-grpc       ClusterIP   10.104.60.91     <none>        10901/TCP            9m33s
service/thanos-storegateway     ClusterIP   10.99.237.163    <none>        9090/TCP,10901/TCP   9m33s
NAME                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/thanos-query            1/1     1            1           9m33s
deployment.apps/thanos-query-frontend   1/1     1            1           9m33s

NAME                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/thanos-query-685b797b8             1         1         1       9m33s
replicaset.apps/thanos-query-frontend-58c764fdf6   1         1         1       9m33s

NAME                                   READY   AGE
statefulset.apps/thanos-storegateway   1/1     9m33s
```

```
$ k logs service/thanos-storegateway -n monitoring 
level=info ts=2023-02-16T09:42:56.089017086Z caller=factory.go:52 msg="loading bucket configuration"
level=info ts=2023-02-16T09:42:56.103373919Z caller=factory.go:35 msg="loading index cache configuration"
level=info ts=2023-02-16T09:42:56.105654878Z caller=inmemory.go:174 msg="created in-memory index cache" maxItemSizeBytes=131072000 maxSizeBytes=536870912 maxItems=maxInt
level=info ts=2023-02-16T09:42:56.110349836Z caller=options.go:26 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2023-02-16T09:42:56.121147544Z caller=store.go:469 msg="starting store node"
level=info ts=2023-02-16T09:42:56.121823503Z caller=store.go:382 msg="initializing bucket store"
level=info ts=2023-02-16T09:42:56.123541961Z caller=intrumentation.go:75 msg="changing probe status" status=healthy
level=info ts=2023-02-16T09:42:56.123938586Z caller=http.go:73 service=http/server component=store msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2023-02-16T09:42:56.134037003Z caller=tls_config.go:232 service=http/server component=store msg="Listening on" address=[::]:10902
level=info ts=2023-02-16T09:42:56.134358169Z caller=tls_config.go:235 service=http/server component=store msg="TLS is disabled." http2=false address=[::]:10902
level=info ts=2023-02-16T09:42:56.135395169Z caller=fetcher.go:478 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=11.847167ms duration_ms=12 cached=0 returned=0 partial=0
level=info ts=2023-02-16T09:42:56.137279669Z caller=store.go:388 msg="bucket store ready" init_duration=15.24225ms
level=info ts=2023-02-16T09:42:56.137760628Z caller=intrumentation.go:56 msg="changing probe status" status=ready
level=info ts=2023-02-16T09:42:56.138000794Z caller=grpc.go:131 service=gRPC/server component=store msg="listening for serving gRPC" address=0.0.0.0:10901
level=info ts=2023-02-16T09:42:56.138414044Z caller=fetcher.go:478 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=895.417µs duration_ms=1 cached=0 returned=0 partial=0
level=info ts=2023-02-16T09:45:56.145149419Z caller=fetcher.go:478 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=5.1185ms duration_ms=5 cached=0 returned=0 partial=0
level=info ts=2023-02-16T09:48:56.152935794Z caller=fetcher.go:478 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=7.02625ms duration_ms=7 cached=0 returned=0 partial=0
level=info ts=2023-02-16T09:51:56.145796086Z caller=fetcher.go:478 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=4.969791ms duration_ms=4 cached=0 returned=0 partial=0
```

**Comment by nswamy** [comment]
unfortunately this still does not work
* Config:
```
indexCacheConfig: |-
  type: IN-MEMORY
  config:
    max_size: 512MB
    max_item_size: 125MB
```
* Output
```
level=info ts=2023-05-01T22:06:50.33255412Z caller=factory.go:52 msg="loading bucket configuration"
level=error ts=2023-05-01T22:06:50.3338239Z caller=main.go:135 err="open /conf/index-cache.yml: no such file or directory\nloading file /conf/index-cache.yml for index-cache.config-file\ngithub.com/efficientgo/tools/extkingpin.(*PathOrContent).Content\n\t/go/pkg/mod/github.com/efficientgo/tools/extkingpin@v0.0.0-20220817170617-6c25e3b627dd/pathorcontent.go:79\nmain.runStore\n\t/app/cmd/thanos/store.go:304\nmain.registerStore.func1\n\t/app/cmd/thanos/store.go:214\nmain.main\n\t/app/cmd/thanos/main.go:133\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594\nget content of index cache configuration\nmain.runStore\n\t/app/cmd/thanos/store.go:306\nmain.registerStore.func1\n\t/app/cmd/thanos/store.go:214\nmain.main\n\t/app/cmd/thanos/main.go:133\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594\npreparing store command failed\nmain.main\n\t/app/cmd/thanos/main.go:135\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594"
```
