### ISSUE TITLE
Spark applications not completing when submitted from pod running jupyter as driver in client mode

### ISSUE THREAD

**Issue by RuizChristianJ** [bitnami/charts#14391]
### Name and Version

bitnami/spark 6.3.11

### What steps will reproduce the bug?

Followed instructions to install the helm chart via:

```
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm install spark-test bitnami/spark
```
This installs fine and I can do `kubectl get pods` and `kubectl get svc` to see if it was successful. After doing this, I create a pod with jupyter, spark, and python via `kubectl apply -f pod.yaml` where pod.yaml is: 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: spark-test
  namespace: my-namespace
spec:
  serviceAccountName: default-editor
  containers:
  - name: spark-test
    image: kubeflow-jupyter-spark:dev
    imagePullPolicy: Always
    ports:
      - containerPort: 7077
    resources:
      requests:
        memory: "2Gi"
        cpu: "2"
      limits:
        memory: "2Gi"
        cpu: "2"
```
Next, I port forward into my pod running jupyter via `kubectl port-forward spark-test 8888:8888` and setup my spark session via the following:
```
import sys, os, re, pprint, subprocess
from pyspark.conf import SparkConf
from pyspark.sql import SparkSession, Catalog
from pyspark.sql.types import Row
import pyspark

ETH0_IP = subprocess.check_output(["hostname", "-i"]).decode(encoding='utf-8').strip()
ETH0_IP = re.sub(fr'\s*127.0.0.1\s*', '', ETH0_IP) # Remove alias to 127.0.0.1, if present.
SPARK_DRIVER_HOST = ETH0_IP
os.environ["SPARK_LOCAL_IP"] = ETH0_IP

spark_conf = SparkConf()
spark_conf.setAll([
    ('spark.master', 'spark://spark-test-master-svc:7777'),
    ('spark.driver.bindAddress', '0.0.0.0'),
    ('spark.driver.host', SPARK_DRIVER_HOST),
    ('spark.driver.port', '7077'),
    ('spark.app.name', 'myApp'),
    ('spark.submit.deployMode', 'client'),
    ('spark.ui.showConsoleProgress', 'true'),
    ('spark.eventLog.enabled', 'false'),
    ('spark.logConf', 'false'),
    ('spark.executor.instances', '1'),
    ('spark.task.cpus', '1'),
])

spark = (SparkSession.builder.config(conf=spark_conf).getOrCreate())

myDF  = spark.createDataFrame([Row(col0=0, col1=1, col2=2),
                               Row(col0=3, col1=1, col2=5),
                               Row(col0=6, col1=2, col2=8)])

myGDF = myDF.select('*').groupBy('col1')
myDF.createOrReplaceTempView('mydf_as_sqltable')
print(myDF.collect())
myGDF.sum().show()
```
I can see that the app was registered, executors were launched on the workers, but the python command hangs and I can see `java.lang.AssertionError: assertion failed: CPUs per task should be > 0` when I exec into the worker pod and look at the stdout. I verified that the install works as intended by running the test command given by the helm install: 
```
export EXAMPLE_JAR=$(kubectl exec -ti --namespace my-namespace spark-test-worker-0 -- find examples/jars/ -name 'spark-example*\.jar' | tr -d '\r')

  kubectl exec -ti --namespace my-namespace spark-test-worker-0 -- spark-submit --master spark://spark-test-master-svc:7077 \
    --class org.apache.spark.examples.SparkPi \
    $EXAMPLE_JAR 5
```

### Are you using any custom parameters or values?

Custom values.yaml for bitnami spark helm install:

```yaml
image:
  tag: 3.3.1-debian-11-r25
master:
  resources:
    limits:
      cpu: 2
      memory: 5Gi
    requests:
      cpu: 2
      memory: 5Gi
worker:
  resources:
    limits:
      cpu: 2
      memory: 5Gi
    requests:
      cpu: 2
      memory: 5Gi
security:
  resources:
    limits:
      cpu: 2
      memory: 5Gi
    requests:
      cpu: 2
      memory: 5Gi
serviceAccount:
  create: false
  name: default-editor
```

### What do you see instead?

```
23/01/16 19:31:10 ERROR Inbox: Ignoring error
java.lang.AssertionError: assertion failed: CPUs per task should be > 0
	at scala.Predef$.assert(Predef.scala:223)
	at org.apache.spark.scheduler.TaskDescription.<init>(TaskDescription.scala:64)
	at org.apache.spark.scheduler.TaskDescription$.decode(TaskDescription.scala:204)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$$anonfun$receive$1.applyOrElse(CoarseGrainedExecutorBackend.scala:182)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:115)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
23/01/16 19:35:54 INFO CoarseGrainedExecutorBackend: Driver commanded a shutdown
```

### Additional information

I have also tried creating a headless service for my driver pod running jupyter, however this yielded the same results.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: spark-driver-test
spec:
  type: ClusterIP
  ports:
  - name: spark-driver-test
    port: 7077
  selector:
    app: spark-runner-test
```
