### ISSUE TITLE
Airflow support postgres password via externalsecrets kind

### ISSUE THREAD

**Issue by Cr0n1c** [bitnami/charts#14409]
### Name and Version

bitnami/airflow

### What is the problem this feature will solve?

Currently, there is no clean way to store a database password in a Declarative Ops way. I would like to be able to use something like AWS Secrets Manager to store the password to my postgres (RDS) instance. 

By doing it this way, it would allow me to drop a ExternalSecret manifest in my template that will allow it to sync to my AWS Secrets Manager. Another option would be to allow me to specify the OS Environmental Variable for the containers to use.

### What is the feature you are proposing to solve the problem?

Allowing the support for AWS secretsmanage, for allowing the values file to determine the Kind of secret to use, or allowing us to pass the environment variable via any means.

Example:
```
  externalDatabase:
    host: "airflow-rds.xxxxxxxxxx.us-east-1.rds.amazonaws.com"
    port: "5432"
    user: "user"
    database: "airflow-db"
    existingSecret: "airflow-db-secrets"
    existingSecretType: "externalsecret" # This would be the Kind
    existingSecretPasswordKey: "airflow-db-password"
 ```
