### ISSUE TITLE
[bitnami/keycloak]  Service monitor match labels selector contains not expected hardcoded label

### ISSUE THREAD

**Issue by ikatlinsky** [bitnami/charts#14422]
### Name and Version

bitnami/keycloak 

### What steps will reproduce the bug?

Install keycloak with service monitor enabled and configure it to connect to the Prometheus. 

### Are you using any custom parameters or values?

```yaml
metrics:
  enabled: true
  service:
    ports:
      http: 8080
  serviceMonitor:
    enabled: true
    port: http
    endpoints:
      - path: /metrics
      - path: /realms/master/metrics
      - path: /realms/prototype/metrics
```

### What is the expected behavior?

Metrics are correctly scraped by Prometheus

### What do you see instead?

Metrics are not collected properly

### Additional information

Service monitor match label selector contains an invalid label `app.kubernetes.io/component: metrics` which is not assigned to the keycloak service resource, which makes it impossible to link them and properly configure metrics scrapping. Also, it seems that the label was left accidentally after some refactor process.
