### ISSUE TITLE
[bitnami/nginx-ingress-controller] loadBalancerSourceRanges list rendering is broken in latest chart

### ISSUE THREAD

**Issue by samling** [bitnami/charts#14439]
### Name and Version

bitnami/nginx-ingress-controller 9.3.25

### What steps will reproduce the bug?

I have a list of source IPs defined in my `values.yaml`, shown below as an example of the format.

Previously this list was rendered via `toYaml` and appeared in the rendered manifest the same as it appears in the values file. However, at some point between versions 9.1.5 and at least 9.3.18, the template for `loadBalancerSourceRanges` changed from:

```yaml
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
```

to

```yaml
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.service.loadBalancerSourceRanges }}
  {{- end }}
```

This causes the list to render as:

```yaml
  loadBalancerSourceRanges: [1.2.3.4/30 2.3.4.5/30]
```

which is invalid and breaks the deployment. The workaround at the moment is to define a single list item with a string of comma-separated values:

```yaml
nginx-ingress-controller:
  service:
    loadBalancerSourceRanges:
    - "1.2.3.4/30, 2.3.4.5/30"
```

This renders properly.

### Are you using any custom parameters or values?

```yaml
nginx-ingress-controller:
  service:
    loadBalancerSourceRanges:
    - "1.2.3.4/30"
    - "2.3.4.5/30"
```

### What is the expected behavior?

Final `service` resource is rendered with the correct list format:

```yaml
nginx-ingress-controller:
  service:
    loadBalancerSourceRanges:
    - "1.2.3.4/30"
    - "2.3.4.5/30"
 ```

### What do you see instead?

An invalid format of list items is rendered instead:

```yaml
  loadBalancerSourceRanges: [1.2.3.4/30 2.3.4.5/30]
```
