### ISSUE TITLE
[bitnami/discourse] Generated ordered list resulting in an un-patchable change to discourse deployment

### ISSUE THREAD

**Issue by angelicax** [bitnami/charts#14443]
### Name and Version

bitnami/discourse-8.1.8

### What steps will reproduce the bug?

1. Create _chart.yaml_ and add 
```yaml
apiVersion: v2
name: chart
description: A Helm chart for deploying all SASS tools
type: application
version: 0.1.0
appVersion: 2.8.9

dependencies:
  - name: discourse
    repository: https://charts.bitnami.com/bitnami
    version: ~8.1.8
```
2. Create helm chart yaml and add containerSecurityContext and set it for non-root
3. Add additional environment variables _extraEnvVars_
```
- name: DISCOURSE_PASSWORD
- name: DISCOURSE_DATABASE_PASSWORD
- name: POSTGRESQL_CLIENT_POSTGRES_PASSWORD
- name: DISCOURSE_REDIS_PASSWORD
```
4. Run the helm chart

### Are you using any custom parameters or values?

```
helm upgrade --install --namespace=discourse $flags \
    --set "smtp_password=${base64_pw}" \
    --set "discourse_password=${base64_pw}" \
    --set "postgresql_password=${base64_pw}" \
    --set "azuread_client_id=${AZURE_CLIENT_ID}" \
    --set "azuread_client_secret=${AZURE_CLIENT_SECRET}"  \
    --set service.loadBalancerIP=${LOAD_BALANCER_IP}  \
    -f values.yaml \
    -f ./env/${env}.yaml \
    $name ./
```

### What is the expected behavior?

Successfully deployed the helm chart without any issues.

### What do you see instead?

```
Error: UPGRADE FAILED: cannot patch "discourse" with kind Deployment: The order in patch list:
[map[name:BITNAMI_DEBUG value:false] map[name:DISCOURSE_PASSWORD valueFrom:map[secretKeyRef:map[key:discourse-password name:discourse]]] map[name:DISCOURSE_PORT_NUMBER value:8080] map[name:DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER value:80] map[name:DISCOURSE_DATABASE_PASSWORD valueFrom:map[secretKeyRef:map[key:password name:postgres-password]]] map[name:DISCOURSE_DATABASE_PASSWORD valueFrom:map[secretKeyRef:map[key:password name:postgres-password]]] map[name:POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD valueFrom:map[secretKeyRef:map[key:password]]] map[name:POSTGRESQL_CLIENT_POSTGRES_PASSWORD valueFrom:map[secretKeyRef:map[key:password name:postgres-password]]] map[name:DISCOURSE_REDIS_PASSWORD valueFrom:map[secretKeyRef:map[key:redis name:discourse-redis]]]]
 doesn't match $setElementOrder list:
[map[name:BITNAMI_DEBUG] map[name:DISCOURSE_PASSWORD] map[name:DISCOURSE_PORT_NUMBER] map[name:DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER] map[name:DISCOURSE_DATABASE_PASSWORD] map[name:POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD] map[name:POSTGRESQL_CLIENT_POSTGRES_PASSWORD] map[name:DISCOURSE_REDIS_PASSWORD] map[name:BITNAMI_DEBUG] map[name:BITNAMI_DEBUG] map[name:DISCOURSE_PASSWORD] map[name:DISCOURSE_PORT_NUMBER] map[name:DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER] map[name:DISCOURSE_DATABASE_PASSWORD] map[name:POSTGRESQL_CLIENT_POSTGRES_PASSWORD] map[name:DISCOURSE_REDIS_PASSWORD] map[name:SMTP_HOST] map[name:SMTP_PORT] map[name:SMTP_USER] map[name:SMTP_TLS] map[name:DISCOURSE_DEVELOPER_EMAILS] map[name:DISCOURSE_SKIP_BOOTSTRAP] map[name:DISCOURSE_SKIP_INSTALL] map[name:DISCOURSE_PRECOMPILE_ASSETS]]
```

### Additional information

Have tried different ways to re-arrange the element order of environment variables but still encounter this un-patchable change to the discourse deployment.

**Comment by javsalgar** [comment]
Hi,

Could you provide the full values.yaml? We would like to reproduce the issue.

**Comment by angelicax** [comment]
Hello this is the content of values.yaml

```
name: sbx
hostname: sbx-discourse.bb.com
volumeIp: 10.29.9.154 #filestore IP
discourseStorage: 2660G
discourse:
  image:
    tag: "2.8.9-debian-11-r3"
  volumePermissions:
    enabled: true
    image:
      pullPolicy: IfNotPresent
  replicaCount: 20
  persistence:
    storageClass: sbx-discourse-sc
    existingClaim: sbx-discourse-pvc
    accessMode: ReadWriteMany
  podSecurityContext:
    enabled: true
    fsGroup: 999
  discourse:
    livenessProbe:
      initialDelaySeconds: 500
      periodSeconds: 20
      timeoutSeconds: 10
      failureThreshold: 6
      successThreshold: 1
    readinessProbe:
      initialDelaySeconds: 300
      periodSeconds: 20
      timeoutSeconds: 10
      failureThreshold: 6
      successThreshold: 1
    resources:
      limits:
        memory: 5Gi
      requests:
        cpu: 500m
        memory: 1Gi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 999
      runAsNonRoot: true
      runAsUser: 999
    host: sbx-discourse.bb.com
    email: test@email.com
    existingSecret: discourse-password
    extraEnvVars:
      - name: BITNAMI_DEBUG
        value: "false"
      - name: BITNAMI_DEBUG
        value: "true"
      - name: DISCOURSE_PASSWORD
        valueFrom:
          secretKeyRef:
            key: discourse-password
            name: sbx-discourse-discourse
      - name: DISCOURSE_PORT_NUMBER
        value: "8080"
      - name: DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER
        value: "80"
      - name: DISCOURSE_DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            key: postgresql-password
            name: postgres-password
      - name: POSTGRESQL_CLIENT_POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            key: postgresql-password
            name: postgres-password
      - name: DISCOURSE_REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            key: redis-password
            name: sbx-discourse-redis
      - name: SMTP_HOST
        value: "smtp.sendgrid.net"
      - name: SMTP_PORT
        value: "587"
      - name: SMTP_USER
        value: "apikey"
      - name: SMTP_TLS
        value: "no"
      - name: DISCOURSE_DEVELOPER_EMAILS
        value: "test@email.com"
      - name: DISCOURSE_SKIP_BOOTSTRAP
        value: "yes"
      - name: DISCOURSE_SKIP_INSTALL
        value: "yes"
      - name: DISCOURSE_PRECOMPILE_ASSETS
        value: "yes"
    extraEnvVarsSecret: discourse-smtp-password
  sidekiq:
    readinessProbe:
      initialDelaySeconds: 200
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 30
    livenessProbe:
      initialDelaySeconds: 300
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 15
    resources:
      limits:
        memory: 5Gi
      requests:
        cpu: 500m
        memory: 1Gi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 999
      runAsNonRoot: true
      runAsUser: 999
    extraEnvVars:
      - name: BITNAMI_DEBUG
        value: "false"
      - name: BITNAMI_DEBUG
        value: "true"
      - name: DISCOURSE_PASSWORD
        valueFrom:
          secretKeyRef:
            key: discourse-password
            name: sbx-discourse-discourse
      - name: DISCOURSE_PORT_NUMBER
        value: "8080"
      - name: DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER
        value: "80"
      - name: DISCOURSE_DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            key: postgresql-password
            name: postgres-password
      - name: POSTGRESQL_CLIENT_POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            key: postgresql-password
            name: postgres-password
      - name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            key: redis-password
            name: sbx-discourse-redis
      - name: SMTP_HOST
        value: "smtp.sendgrid.net"
      - name: SMTP_PORT
        value: "587"
      - name: SMTP_USER
        value: "apikey"
      - name: SMTP_TLS
        value: "no"
      - name: DISCOURSE_SKIP_BOOTSTRAP
        value: "yes"
      - name: DISCOURSE_SKIP_INSTALL
        value: "yes"
      - name: DISCOURSE_PRECOMPILE_ASSETS
        value: "yes"
    extraEnvVarsSecret: discourse-smtp-password
  postgresql:
    enabled: false
  externalDatabase:
    host: 10.85.0.5 # cloudsql IP
    user: postgres
    postgresqlPostgresUser: postgres
    existingSecret: postgres-password
    database: discourse
  service:
    port: 80
    type: NodePort
    loadBalancerIP: "10.101.0.240"
    externalTrafficPolicy: Local
    annotations:
      cloud.google.com/backend-config: '{"default": "backend-config"}'
      beta.cloud.google.com/backend-config: '{"default": "backend-config"}'
```

We also have a file called _install.sh_ and we run it in gcp cloud shell by running the `ENV=sbx ./install.sh`. This is the contents, but I think the last line will do and no need to create the install file.

```
#!/bin/bash
# Requires bash 5

# Be sure to log in to the correct cluster and project with kubectl before running this
# for int:
#  gcloud container clusters get-credentials int-gke --region us-central1 --project furlong-platform-int-a31cdf
#  gcloud config set project furlong-platform-int-a31cdf 

# The secret discourse-smtp-pw is created manually

set -ex # Exit on error, output commands

env=${ENV:-int}
name=${env}-discourse
flags=$FLAGS
pw=$(gcloud secrets versions access latest --secret=discourse_pg_pw)
smtp_pw=$(gcloud secrets versions access latest --secret=discourse-smtp-pw)
base64_pw=$(echo ${pw} | base64) #No longer used, rework this
IFS=":" read -ra AZUREAD_CREDS \
    <<< "$(gcloud secrets versions access latest --secret="${env}-discourse-azuread-creds")"
AZURE_TENANT_ID=$(echo "${AZUREAD_CREDS[0]}" | base64) #No longer used, rework this
AZURE_CLIENT_ID=$(echo "${AZUREAD_CREDS[1]}" | base64) #No longer used, rework this
AZURE_CLIENT_SECRET=$(echo "${AZUREAD_CREDS[2]}" | base64) #No longer used, rework this
LOAD_BALANCER_IP=$(cat ./env/${env}.yaml | grep -i loadBalancerIP | awk -F\" '{print $2}')

discourse_pods_running=`kubectl get pods --all-namespaces | grep Running | grep -c $env-discourse || echo`

if (( $discourse_pods_running > 0 )); then
    echo "Found Running pods, skipping discourse install"
     # Do not run the Discourse installation wizard
    flags="$flags --set discourse.skipInstall=true --set discourse.discourse.skipInstall=true"
fi

# Update dependencies
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm dependency update

# Create the namespaces
kubectl create namespace discourse --dry-run=client -o yaml | kubectl apply -f -
kubectl create namespace cert-manager --dry-run=client -o yaml | kubectl apply -f -

# Install cert-manager
helm upgrade -i \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v1.5.3 \
  --create-namespace \
  --set installCRDs=true

# Set the DB password for the postgres user
gcloud sql users set-password postgres -i "${env}-discourse" --password="${pw}"

# Postgres
kubectl create secret generic postgres-password \
    --namespace discourse \
    --from-literal=postgresql-postgres-password="${pw}" \
    --from-literal=postgresql-password="${pw}" \
    --dry-run=client -o yaml | kubectl apply -f -

# Discourse
kubectl create secret generic discourse-password \
    --namespace discourse \
    --from-literal=discourse-password="${pw}" \
    --dry-run=client -o yaml | kubectl apply -f -

# Discourse SMTP
kubectl create secret generic discourse-smtp-password \
    --namespace discourse \
    --from-literal=SMTP_PASSWORD="${smtp_pw}" \
    --from-literal=DISCOURSE_AZURE_TENANT_ID="${AZUREAD_CREDS[0]}" \
    --from-literal=DISCOURSE_AZURE_CLIENT_ID="${AZUREAD_CREDS[1]}" \
    --from-literal=DISCOURSE_AZURE_CLIENT_SECRET="${AZUREAD_CREDS[2]}" \
    --from-literal=POSTGRESQL_CLIENT_CREATE_DATABASE_USER="${env}-discourse" \
    --from-literal=POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD="${pw}" \
    --from-literal=DISCOURSE_SKIP_BOOTSTRAP=yes \
    --from-literal=DISCOURSE_SKIP_INSTALL=yes \
    --dry-run=client -o yaml | kubectl apply -f -


# Wait for cert-manager to be ready
kubectl -n cert-manager wait --for=condition=Ready pod -l app=webhook --timeout 60s
kubectl -n cert-manager wait --for=condition=Ready pod -l app=cainjector --timeout 60s
kubectl -n cert-manager wait --for=condition=Ready pod -l app=cert-manager --timeout 60s

# Install Discourse
# These --sets are no longer necessary, this needs to be reworked
helm upgrade --install --namespace=discourse $flags \
    --set "smtp_password=${base64_pw}" \
    --set "discourse_password=${base64_pw}" \
    --set "postgresql_password=${base64_pw}" \
    --set "azuread_client_id=${AZURE_CLIENT_ID}" \
    --set "azuread_client_secret=${AZURE_CLIENT_SECRET}"  \
    --set service.loadBalancerIP=${LOAD_BALANCER_IP}  \
    -f values.yaml \
    -f ./env/${env}.yaml \
    $name ./

# Watch the status with: 'kubectl get svc --namespace discourse -w $name-discourse'. Update discourse.discourse.host with the domain after updating the DNS and rerun this script
```

**Comment by marcosbc** [comment]
Hi @angelicax, I believe this is happening because `DISCOURSE_PASSWORD` has already been set by default within `deployment.yaml`. If you instead set `auth.password`, it should work. It is possible that something similar may happen with `DISCOURSE_DATABASE_PASSWORD` and similar envvars.

**Comment by angelicax** [comment]
Hello @marcosbc. I'm not sure if I'm doing it right but I still encounter the error. I even tried to remove those environment variables. This is the deployment yaml.

```
name: sbx
hostname: sbx-discourse.bb.com
volumeIp: 10.29.9.154 #filestore IP
discourseStorage: 2660G
discourse:
  image:
    tag: "2.8.9-debian-11-r3"
  volumePermissions:
    enabled: true
    image:
      pullPolicy: IfNotPresent
  replicaCount: 20
  persistence:
    storageClass: sbx-discourse-sc
    existingClaim: sbx-discourse-pvc
    accessMode: ReadWriteMany
  podSecurityContext:
    enabled: true
    fsGroup: 999
  discourse:
    livenessProbe:
      initialDelaySeconds: 500
      periodSeconds: 20
      timeoutSeconds: 10
      failureThreshold: 6
      successThreshold: 1
    readinessProbe:
      initialDelaySeconds: 300
      periodSeconds: 20
      timeoutSeconds: 10
      failureThreshold: 6
      successThreshold: 1
    resources:
      limits:
        memory: 5Gi
      requests:
        cpu: 500m
        memory: 1Gi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 999
      runAsNonRoot: true
      runAsUser: 999
    host: sbx-discourse.bb.com
    email: test@gm.com
    existingSecret: discourse-password
    extraEnvVars:
      - name: BITNAMI_DEBUG
        value: "true"
      - name: SMTP_HOST
        value: "smtp.sendgrid.net"
      - name: SMTP_PORT
        value: "587"
      - name: SMTP_USER
        value: "apikey"
      - name: SMTP_TLS
        value: "no"
      - name: DISCOURSE_DEVELOPER_EMAILS
        value: "test@gm.com"
      - name: DISCOURSE_SKIP_BOOTSTRAP
        value: "yes"
      - name: DISCOURSE_SKIP_INSTALL
        value: "yes"
      - name: DISCOURSE_PRECOMPILE_ASSETS
        value: "yes"
    extraEnvVarsSecret: discourse-smtp-password
  sidekiq:
    readinessProbe:
      initialDelaySeconds: 200
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 30
    livenessProbe:
      initialDelaySeconds: 300
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 15
    resources:
      limits:
        memory: 5Gi
      requests:
        cpu: 500m
        memory: 1Gi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 999
      runAsNonRoot: true
      runAsUser: 999
    extraEnvVars:
      - name: BITNAMI_DEBUG
        value: "true"
      - name: SMTP_HOST
        value: "smtp.sendgrid.net"
      - name: SMTP_PORT
        value: "587"
      - name: SMTP_USER
        value: "apikey"
      - name: SMTP_TLS
        value: "no"
      - name: DISCOURSE_SKIP_BOOTSTRAP
        value: "yes"
      - name: DISCOURSE_SKIP_INSTALL
        value: "yes"
      - name: DISCOURSE_PRECOMPILE_ASSETS
        value: "yes"
    extraEnvVarsSecret: discourse-smtp-password
  postgresql:
    enabled: false
  externalDatabase:
    host: 10.85.0.5 # cloudsql IP
    user: postgres
    postgresqlPostgresUser: postgres
    existingSecret: postgres-password
    database: discourse
  service:
    port: 80
    type: NodePort
    loadBalancerIP: "10.101.0.240"
    externalTrafficPolicy: Local
    annotations:
      cloud.google.com/backend-config: '{"default": "backend-config"}'
      beta.cloud.google.com/backend-config: '{"default": "backend-config"}'
```

but I still got this error:
```
Error: UPGRADE FAILED: cannot patch "sbx-discourse" with kind Deployment: The order in patch list:
[map[name:BITNAMI_DEBUG value:true] map[name:BITNAMI_DEBUG value:false] map[name:DISCOURSE_PASSWORD valueFrom:map[secretKeyRef:map[key:discourse-password name:sbx-discourse-discourse]]] map[name:DISCOURSE_PORT_NUMBER value:8080] map[name:DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER value:80] map[name:POSTGRESQL_CLIENT_POSTGRES_PASSWORD valueFrom:map[secretKeyRef:map[key:postgres-password name:postgres-password]]] map[name:DISCOURSE_REDIS_PASSWORD valueFrom:map[secretKeyRef:map[key:redis-password name:sbx-discourse-redis]]]]
 doesn't match $setElementOrder list:
[map[name:BITNAMI_DEBUG] map[name:DISCOURSE_PASSWORD] map[name:DISCOURSE_PORT_NUMBER] map[name:DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER] map[name:DISCOURSE_DATABASE_PASSWORD] map[name:POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD] map[name:POSTGRESQL_CLIENT_POSTGRES_PASSWORD] map[name:DISCOURSE_REDIS_PASSWORD] map[name:BITNAMI_DEBUG] map[name:SMTP_HOST] map[name:SMTP_PORT] map[name:SMTP_USER] map[name:SMTP_TLS] map[name:DISCOURSE_DEVELOPER_EMAILS] map[name:DISCOURSE_SKIP_BOOTSTRAP] map[name:DISCOURSE_SKIP_INSTALL] map[name:DISCOURSE_PRECOMPILE_ASSETS]]
```

This is the install file that we run whenever we have changes in the deployment yaml using `ENV=sbx ./install.sh` command. I added your suggestion of setting a helm parameter with those passwords at the lowest part of this file. Am I doing it right? Thank you so much!
```
#!/bin/bash
# Requires bash 5

# Be sure to log in to the correct cluster and project with kubectl before running this
# for int:
#  gcloud container clusters get-credentials int-gke --region us-central1 --project furlong-platform-int-a31cdf
#  gcloud config set project furlong-platform-int-a31cdf 

# The secret discourse-smtp-pw is created manually

set -ex # Exit on error, output commands

env=${ENV:-int}
name=${env}-discourse
flags=$FLAGS
pw=$(gcloud secrets versions access latest --secret=discourse_pg_pw)
smtp_pw=$(gcloud secrets versions access latest --secret=discourse-smtp-pw)
base64_pw=$(echo ${pw} | base64) #No longer used, rework this
IFS=":" read -ra AZUREAD_CREDS \
    <<< "$(gcloud secrets versions access latest --secret="${env}-discourse-azuread-creds")"
AZURE_TENANT_ID=$(echo "${AZUREAD_CREDS[0]}" | base64) #No longer used, rework this
AZURE_CLIENT_ID=$(echo "${AZUREAD_CREDS[1]}" | base64) #No longer used, rework this
AZURE_CLIENT_SECRET=$(echo "${AZUREAD_CREDS[2]}" | base64) #No longer used, rework this
LOAD_BALANCER_IP=$(cat ./env/${env}.yaml | grep -i loadBalancerIP | awk -F\" '{print $2}')

discourse_pods_running=`kubectl get pods --all-namespaces | grep Running | grep -c $env-discourse || echo`

if (( $discourse_pods_running > 0 )); then
    echo "Found Running pods, skipping discourse install"
     # Do not run the Discourse installation wizard
    flags="$flags --set discourse.skipInstall=true --set discourse.discourse.skipInstall=true"
fi

# Update dependencies
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm dependency update

# Create the namespaces
kubectl create namespace discourse --dry-run=client -o yaml | kubectl apply -f -
kubectl create namespace cert-manager --dry-run=client -o yaml | kubectl apply -f -

# Install cert-manager
helm upgrade -i \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v1.5.3 \
  --create-namespace \
  --set installCRDs=true

# Set the DB password for the postgres user
gcloud sql users set-password postgres -i "${env}-discourse" --password="${pw}"

# Postgres
kubectl create secret generic postgres-password \
    --namespace discourse \
    --from-literal=postgresql-postgres-password="${pw}" \
    --from-literal=postgresql-password="${pw}" \
    --dry-run=client -o yaml | kubectl apply -f -

# Discourse
kubectl create secret generic discourse-password \
    --namespace discourse \
    --from-literal=discourse-password="${pw}" \
    --dry-run=client -o yaml | kubectl apply -f -

# Discourse SMTP
kubectl create secret generic discourse-smtp-password \
    --namespace discourse \
    --from-literal=SMTP_PASSWORD="${smtp_pw}" \
    --from-literal=DISCOURSE_AZURE_TENANT_ID="${AZUREAD_CREDS[0]}" \
    --from-literal=DISCOURSE_AZURE_CLIENT_ID="${AZUREAD_CREDS[1]}" \
    --from-literal=DISCOURSE_AZURE_CLIENT_SECRET="${AZUREAD_CREDS[2]}" \
    --from-literal=POSTGRESQL_CLIENT_CREATE_DATABASE_USER="${env}-discourse" \
    --from-literal=POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD="${pw}" \
    --from-literal=DISCOURSE_SKIP_BOOTSTRAP=yes \
    --from-literal=DISCOURSE_SKIP_INSTALL=yes \
    --dry-run=client -o yaml | kubectl apply -f -


# Wait for cert-manager to be ready
kubectl -n cert-manager wait --for=condition=Ready pod -l app=webhook --timeout 60s
kubectl -n cert-manager wait --for=condition=Ready pod -l app=cainjector --timeout 60s
kubectl -n cert-manager wait --for=condition=Ready pod -l app=cert-manager --timeout 60s

# Install Discourse
# These --sets are no longer necessary, this needs to be reworked
helm upgrade --install --namespace=discourse $flags \
    --set "smtp_password=${base64_pw}" \
    --set "discourse_password=${base64_pw}" \
    --set "postgresql_password=${base64_pw}" \
    --set "azuread_client_id=${AZURE_CLIENT_ID}" \
    --set "azuread_client_secret=${AZURE_CLIENT_SECRET}"  \
    --set service.loadBalancerIP=${LOAD_BALANCER_IP}  \
    --set "auth.password=${DISCOURSE_PASSWORD}" \
    --set "auth.password=${DISCOURSE_POSTGRESQL_PASSWORD}" \
    --set "auth.password=${REDIS_PASSWORD}" \
    -f values.yaml \
    -f ./env/${env}.yaml \
    $name ./

# Watch the status with: 'kubectl get svc --namespace discourse -w $name-discourse'. Update discourse.discourse.host with the domain after updating the DNS and rerun this script
```
