### ISSUE TITLE
[bitnami/spark] Incorrectly mounted `existingConfigmap` ?

### ISSUE THREAD

**Issue by BMalaichik** [bitnami/charts#14468]
### Name and Version

bitnami/spark:6.3.12

### What steps will reproduce the bug?

1. Create a config map with `spark-defaults.conf` value
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-dev
  namespace: spark
data:
  spark-defaults.conf: |-
    # For more details visit official docs:
    # This is my default config ...

```
2. Define in helm chart `master. existingConfigmap` or `worker. existingConfigmap` value
3. Install chart
4. Inspect `$SPARK_HOME/conf` directory

### What is the expected behavior?

I expected the config map to be mounted under the default spark configuration path `$SPARK_HOME/conf`, which is by default `/opt/bitnami/spark`, not `bitnami/spark`

### What do you see instead?

Debugging the helm chart I see that the actual config map content is mounted under the `bitnami/spark/conf` path
, the value is hardcoded in [chart-template](https://github.com/bitnami/charts/blob/main/bitnami/spark/templates/statefulset-worker.yaml#L185)

```
            {{- if .Values.worker.existingConfigmap }}
            - name: config
              mountPath: '/bitnami/spark/conf/'
            {{- end }}
```

### Additional information

What might be a temporary solution for that?
I've tried to create an init script and copy the config to the target `$SPARK_HOME/conf` path however it doesn't work.

Looking forward for any suggestions.
Thanks

**Comment by javsalgar** [comment]
Hi,

Even though the configuration is mounted in that folder, the container scripts should copy the content to the proper folder. You mentioned that you even tried an init script but it didn't work. Could you detail the error?

**Comment by BMalaichik** [comment]
> Hi,
> 
> Even though the configuration is mounted in that folder, the container scripts should copy the content to the proper folder. You mentioned that you even tried an init script but it didn't work. Could you detail the error?

No errors, defining an `initScript` just didn't work, no content was copied
1. define `existingConfigMap`
2. Define init copy script
```
initScripts:
  my_init_script.sh: |
      #!/bin/sh
      yes | cp -f /bitnami/spark/conf/* /opt/bitnami/spark/conf
```
3. check the actual file content
```
kubectl exec -it POD_NAME -n spark -- cat /opt/bitnami/spark/conf/spark-defaults.conf
```

Show default config file, not the one supplied in the `existingConfigMap`

**Comment by aoterolorenzo** [comment]
Hi @BMalaichik,

As you may notice, the current implementation of the chart hardcodes the "spark home": the chart template is using the path `/bitnami/spark/conf` to mount the config map, while you would expect it to be mounted to the location defined by the environment variable `$SPARK_HOME/conf`, which is not working for that exact reason. Could you try to mount the config file directly to `/bitnami/spark/conf`?

**Comment by BMalaichik** [comment]
> Hi @BMalaichik,
> 
> As you may notice, the current implementation of the chart hardcodes the "spark home": the chart template is using the path `/bitnami/spark/conf` to mount the config map, while you would expect it to be mounted to the location defined by the environment variable `$SPARK_HOME/conf`, which is not working for that exact reason. Could you try to mount the config file directly to `/bitnami/spark/conf`?


> Could you try to mount the config file directly to `/bitnami/spark/conf`
You mean `/opt/bitnami/spark/conf` ?

Yes, it doesn't work either, ConfigMaps volume mounts are read-only, spark container can't be launched, container can't be launched, fails with file is read-only error.

**Comment by aoterolorenzo** [comment]
Does mounting directly to `/opt/bitnami/spark/conf` work? You could use also the $SPARK_BASEDIR env var (always defined).

The thing is, the Bitnami scripts in many containers execute a binding between the folders in the volume directory (`SPARK_VOLUMEDIR`) and the base application directory (`SPARK_BASEDIR`). This only includes necessary required folders to recover persistence from the volume in case of a previous existing installation.

Could you trying mounting the configmap directly to `$SPARK_BASEDIR/conf`?

**Comment by alexeckert** [comment]
Stumbled upon the same issue, what's the point of `master. existingConfigmap` when the configmap is mounted to a location which doesn't pick up the configs?

**Comment by BMalaichik** [comment]
@alexeckert that's the exact concern of mine, eventually ended up with parametrization with  `-Dspark.*` in `configOptions`

**Comment by javsalgar** [comment]
As mentioned before, the container logic should copy the configmaps to the proper folder. If not, there is a bug in the container logic.

**Comment by alexeckert** [comment]
According to the container doc, mounting to `/opt/bitnami/spark/...` is recommended. https://github.com/bitnami/containers/tree/main/bitnami/spark#mount-a-custom-configuration-file
Entrypoint script also has hardcoded link to `/opt/bitnami/spark/...`: https://github.com/bitnami/containers/blob/main/bitnami/spark/3.2/debian-11/rootfs/opt/bitnami/scripts/spark/entrypoint.sh#L15
A `BITNAMI_VOLUME_DIR` env var is defined but not used in spark-env.sh: https://github.com/bitnami/containers/blob/main/bitnami/spark/3.2/debian-11/rootfs/opt/bitnami/scripts/spark-env.sh

**Comment by Mauraza** [comment]
I just create an RP updating the path of the config file.

**Comment by alexeckert** [comment]
Hello, thanks for the quick reaction and the fix. However, I think the current concept of mounting the configmaps doesn't really work due to permission issues.
```
/opt/bitnami/scripts/spark/entrypoint.sh: line 22: /opt/bitnami/spark/conf/spark-env.sh: Permission denied
```
This seems to be an issue from the past: https://github.com/bitnami/charts/pull/9536 and probably reintroduces https://github.com/bitnami/charts/issues/9505 again. While I'm not familiar with the code, I think the mechanism which is mentioned in https://github.com/bitnami/charts/pull/9536 where config files are picked up from `/bitnami/...` is probably missing.

**Comment by Mauraza** [comment]
Hi @alexeckert,

Sorry for the delay. The problem was that `SPARK_CONF_FILE` is not initialized. 
I just create a PR to revert the change, after merging the PR, you only need to add this 🔽  in the values for the master and the worker:
```yaml
  extraEnvVars: 
    - name: SPARK_CONF_FILE
      value: /bitnami/conf/spark-defaults.conf
```
And that should be working.

**Comment by deep1pradee** [comment]
the issue persists... it's not resolved yet.

**Comment by yurymkomarov** [comment]
@deep1pradee there is only one workaround (in my case it was core-site.xml)

```
...
  master:
    extraVolumes:
      - name: spark-extra-configmap
        configMap:
          name: spark-extra-configmap
    extraVolumeMounts:
      - name: spark-core-config
        mountPath: /opt/bitnami/spark/conf/core-site.xml
        subPath: core-site.xml
...
  worker:
    extraVolumes:
      - name: spark-extra-configmap
        configMap:
          name: spark-extra-configmap
    extraVolumeMounts:
      - name: spark-core-config
        mountPath: /opt/bitnami/spark/conf/core-site.xml
        subPath: core-site.xml
...
```
