### ISSUE TITLE
[bitnami/postgresql] The POSTGRESQL_PASSWORD environment variable is empty or not set.

### ISSUE THREAD

**Issue by shkmaaz11** [bitnami/charts#14469]
### Name and Version

bitnami/postgresql12.1.9

### What steps will reproduce the bug?

I was trying to upgrade the postgresql chart from 11.9.13 to 12.1.9.
1. I enabled the diagnostic mode and and updated the chart version
2. The postgress pod gives me the following error. "The POSTGRESQL_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development."
3. I've checked that I already have the secrets in place.

Can anyone point out what I am doing wrong?

 

### Are you using any custom parameters or values?
```
  global:
    imageRegistry: myRegistry
    imagePullSecrets:
      - pullSecrets
    postgresql:
      auth:
        database: my_db
        existingSecret: my-db-secret
        secretKeys:
          adminPasswordKey: "postgresql-password"
          userPasswordKey: "postgresql-password"
```
### What is the expected behavior?

I want to be able to successfully upgrade from chart version 11.9.13 to 12.1.9

### What do you see instead?
```
postgresql 11:56:44.10 ERROR ==> The POSTGRESQL_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.
```

**Comment by shkmaaz11** [comment]
I checked it. It doesn't get assigned

**Comment by javsalgar** [comment]
Could you explain the reason of using the global section? Is it part of a subchart?

**Comment by shkmaaz11** [comment]
Not a part of subchart.. The bitnami chart specifies that we can specify the credentials in the global section. It was a personal choice to specify there.

**Comment by javsalgar** [comment]
Could you try using the non-global section? This way we can check whether the issue is in the global section.

**Comment by shkmaaz11** [comment]
Yes, I did try but the same result

**Comment by migruiz4** [comment]
Hi @shkmaaz11,

I tried to reproduce your issue using the following command, but the POSTGRESQL_PASSWORD got assigned correctly when using the values you provided:
```yaml
$ helm upgrade test bitnami/postgresql -f values.yaml --dry-run
...
      containers:
        - name: postgresql
          image: myRegistry/bitnami/postgresql:15.1.0-debian-11-r30
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: POSTGRESQL_PORT_NUMBER
              value: "5432"
            - name: POSTGRESQL_VOLUME_DIR
              value: "/bitnami/postgresql"
            - name: PGDATA
              value: "/bitnami/postgresql/data"
            # Authentication
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-db-secret
                  key: postgresql-password
            - name: POSTGRES_DB
              value: "my_db"
...
```

Could you please share the output of  the following commands?
```
# Description of your postgresql pod
$ kubectl describe pod <your_postgresql_pod>
# Your helm upgrade command, using the flag `--dry-run` to display the templates
$ helm upgrade ... --dry-run
```

Additionally, it would be helpful if you could provide more details about how are you starting postgresql inside the container.
