### ISSUE TITLE
[bitnami/redis-cluster] externalaccess bugs

### ISSUE THREAD

**Issue by busyboy77** [bitnami/charts#14480]
### Name and Version

bitnami/redis-cluster-8.3.3

### What steps will reproduce the bug?

1. Running on K3s with 5 nodes running RHEL-8.4
2. helm redis-cluster-8.3.3     
3. APP version 7.0.7
4. Helm install Command 
```
helm upgrade --install=true --timeout=10m0s --debug --namespace=ef-external --values=redis-cluster/values-external-access.yaml  nikka redis-cluster
```
5. with values file
6. Then waited for the cluster to come up 
```
# k get svc  -n ef-external
NAME                                              TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                                                                                          AGE
nikka-redis-cluster                               ClusterIP      10.43.141.115   <none>          6379/TCP                                                                                         3h3m
nikka-redis-cluster-0-svc                         LoadBalancer   10.43.15.230    10.192.168.76   6379:31716/TCP,16379:32562/TCP                                                                   3h3m
nikka-redis-cluster-1-svc                         LoadBalancer   10.43.235.134   10.192.168.73   6379:30814/TCP,16379:31712/TCP                                                                   3h3m
nikka-redis-cluster-2-svc                         LoadBalancer   10.43.128.115   10.192.168.72   6379:30903/TCP,16379:31728/TCP                                                                   3h3m
nikka-redis-cluster-3-svc                         LoadBalancer   10.43.174.178   10.192.168.74   6379:31985/TCP,16379:31754/TCP                                                                   3h3m
nikka-redis-cluster-4-svc                         LoadBalancer   10.43.15.137    10.192.168.77   6379:30299/TCP,16379:32637/TCP                                                                   3h3m
nikka-redis-cluster-5-svc                         LoadBalancer   10.43.142.114   10.192.168.75   6379:32333/TCP,16379:31168/TCP                                                                   3h3m

```
7. and then ran helm upgrade as suggested 
```
helm upgrade --namespace ef-external nikka --set "cluster.externalAccess.enabled=true,cluster.externalAccess.service.type=LoadBalancer,cluster.externalAccess.service.loadBalancerIP[0]=10.192.168.76,cluster.externalAccess.service.loadBalancerIP[1]=10.192.168.73,cluster.externalAccess.service.loadBalancerIP[2]=10.192.168.72,cluster.externalAccess.service.loadBalancerIP[3]=10.192.168.74,cluster.externalAccess.service.loadBalancerIP[4]=10.192.168.77,cluster.externalAccess.service.loadBalancerIP[5]=10.192.168.75" redis-cluster
```

8. This shows me this message.

```
# helm status nikka -n ef-external
NAME: nikka
LAST DEPLOYED: Fri Jan 20 17:09:57 2023
NAMESPACE: ef-external
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
CHART NAME: redis-cluster
CHART VERSION: 8.3.3
APP VERSION: 7.0.7** Please be patient while the chart is being deployed **


To get your password run:
    export REDIS_PASSWORD=$(kubectl get secret --namespace "ef-external" nikka-redis-cluster -o jsonpath="{.data.redis-password}" | base64 -d)

To connect to your Redis&reg; server from outside the cluster check the following information:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace ef-external -w nikka-redis-cluster'

    You will have a different external IP for each Redis&reg; node. Get the external ip from `-external` suffixed services: `kubectl get svc`.
    Redis&reg; port: 6379INFO: The Job to create the cluster will be created.To connect to your database from outside the cluster execute the following commands:

    export SERVICE_IP=$(kubectl get svc --namespace ef-external nikka-redis-cluster --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
    redis-cli -c -h $SERVICE_IP -p 6379 -a $REDIS_PASSWORD
```

9. Running the commands separately.

For REDIS_PASSWORD:
```
export REDIS_PASSWORD=$(kubectl get secret --namespace "ef-external" nikka-redis-cluster -o jsonpath="{.data.redis-password}" | base64 -d)
echo $REDIS_PASSWORD```
```
gives

```Password123```

9.b Status of the svc
```
# kubectl get svc --namespace ef-external -w nikka-redis-cluster
NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
nikka-redis-cluster   ClusterIP   10.43.141.115   <none>        6379/TCP   3h8m
```

9.c
Running the IP range list for redis-cluster
```
export SERVICE_IP=$(kubectl get svc --namespace ef-external nikka-redis-cluster --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
```
output.

error: error executing template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}": template: output:1:10: executing "output" at <index .status.loadBalancer.ingress 0>: error calling index: index of untyped nil

running the command separately gives

```
# kubectl get svc --namespace ef-external nikka-redis-cluster --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}"
Error executing template: template: output:1:10: executing "output" at <index .status.loadBalancer.ingress 0>: error calling index: index of untyped nil. Printing more information for debugging the template:
        template was:
                {{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}
        raw data was:
                {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"meta.helm.sh/release-name":"nikka","meta.helm.sh/release-namespace":"ef-external"},"creationTimestamp":"2023-01-20T11:56:02Z","labels":{"app.kubernetes.io/instance":"nikka","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"redis-cluster","helm.sh/chart":"redis-cluster-8.3.3"},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:meta.helm.sh/release-name":{},"f:meta.helm.sh/release-namespace":{}},"f:labels":{".":{},"f:app.kubernetes.io/instance":{},"f:app.kubernetes.io/managed-by":{},"f:app.kubernetes.io/name":{},"f:helm.sh/chart":{}}},"f:spec":{"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":6379,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}},"manager":"helm","operation":"Update","time":"2023-01-20T11:56:02Z"}],"name":"nikka-redis-cluster","namespace":"ef-external","resourceVersion":"13154","uid":"0c9f3c18-532d-4c4a-ac60-9f119bdfa807"},"spec":{"clusterIP":"10.43.141.115","clusterIPs":["10.43.141.115"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"tcp-redis","port":6379,"protocol":"TCP","targetPort":"tcp-redis"}],"selector":{"app.kubernetes.io/instance":"nikka","app.kubernetes.io/name":"redis-cluster"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
        object given to template engine was:
                map[apiVersion:v1 kind:Service metadata:map[annotations:map[meta.helm.sh/release-name:nikka meta.helm.sh/release-namespace:ef-external] creationTimestamp:2023-01-20T11:56:02Z labels:map[app.kubernetes.io/instance:nikka app.kubernetes.io/managed-by:Helm app.kubernetes.io/name:redis-cluster helm.sh/chart:redis-cluster-8.3.3] managedFields:[map[apiVersion:v1 fieldsType:FieldsV1 fieldsV1:map[f:metadata:map[f:annotations:map[.:map[] f:meta.helm.sh/release-name:map[] f:meta.helm.sh/release-namespace:map[]] f:labels:map[.:map[] f:app.kubernetes.io/instance:map[] f:app.kubernetes.io/managed-by:map[] f:app.kubernetes.io/name:map[] f:helm.sh/chart:map[]]] f:spec:map[f:internalTrafficPolicy:map[] f:ports:map[.:map[] k:{"port":6379,"protocol":"TCP"}:map[.:map[] f:name:map[] f:port:map[] f:protocol:map[] f:targetPort:map[]]] f:selector:map[] f:sessionAffinity:map[] f:type:map[]]] manager:helm operation:Update time:2023-01-20T11:56:02Z]] name:nikka-redis-cluster namespace:ef-external resourceVersion:13154 uid:0c9f3c18-532d-4c4a-ac60-9f119bdfa807] spec:map[clusterIP:10.43.141.115 clusterIPs:[10.43.141.115] internalTrafficPolicy:Cluster ipFamilies:[IPv4] ipFamilyPolicy:SingleStack ports:[map[name:tcp-redis port:6379 protocol:TCP targetPort:tcp-redis]] selector:map[app.kubernetes.io/instance:nikka app.kubernetes.io/name:redis-cluster] sessionAffinity:None type:ClusterIP] status:map[loadBalancer:map[]]]

error: error executing template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}": template: output:1:10: executing "output" at <index .status.loadBalancer.ingress 0>: error calling index: index of untyped nil

```

9.d A beuatified version of the above output is 

```
# kubectl get svc --namespace ef-external nikka-redis-cluster -o json
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "annotations": {
            "meta.helm.sh/release-name": "nikka",
            "meta.helm.sh/release-namespace": "ef-external"
        },
        "creationTimestamp": "2023-01-20T11:56:02Z",
        "labels": {
            "app.kubernetes.io/instance": "nikka",
            "app.kubernetes.io/managed-by": "Helm",
            "app.kubernetes.io/name": "redis-cluster",
            "helm.sh/chart": "redis-cluster-8.3.3"
        },
        "name": "nikka-redis-cluster",
        "namespace": "ef-external",
        "resourceVersion": "13154",
        "uid": "0c9f3c18-532d-4c4a-ac60-9f119bdfa807"
    },
    "spec": {
        "clusterIP": "10.43.141.115",
        "clusterIPs": [
            "10.43.141.115"
        ],
        "internalTrafficPolicy": "Cluster",
        "ipFamilies": [
            "IPv4"
        ],
        "ipFamilyPolicy": "SingleStack",
        "ports": [
            {
                "name": "tcp-redis",
                "port": 6379,
                "protocol": "TCP",
                "targetPort": "tcp-redis"
            }
        ],
        "selector": {
            "app.kubernetes.io/instance": "nikka",
            "app.kubernetes.io/name": "redis-cluster"
        },
        "sessionAffinity": "None",
        "type": "ClusterIP"
    },
    "status": {
        "loadBalancer": {}
    }
}
```

There are no IPS assigned to the LoadBalancer, however, the `kubectl get svc ` shows the really assigned IPS

10. Trying to connecto the  redis cluster

Set the password:
`export REDIS_PASSWORD=$(kubectl get secret --namespace "ef-external" nikka-redis-cluster -o jsonpath="{.data.redis-password}" | base64 -d)`

Run the redis client 

`run --namespace ef-external redis-client --restart='Never'  --env REDIS_PASSWORD=$REDIS_PASSWORD  --image gitimages.exsample.com/general/redis-cluster/redis-cluster-json-search:7.0.7-debian-11-r0 --command -- sleep infinity`

get the client running 
```
# k get pods -n ef-external 
redis-client                                          1/1     Running   0               8s'
```

Actions inside the redis-client

```
# kubectl exec --tty -i redis-client     --namespace ef-external -- bash

kubectl exec --tty -i redis-client    --namespace ef-external -- bash
I have no name!@redis-client:/$  redis-cli -c -h $SERVICE_IP -p 6379 -a $REDIS_PASSWORD
Could not connect to Redis at -p:6379: Name or service not known
I have no name!@redis-client:/$
```
However, giving one of the external IPs gives access to it
```
I have no name!@redis-client:/$ redis-cli -c -h 10.192.168.76  -p 6379 -a $REDIS_PASSWORD
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
10.192.168.76:6379> exit
I have no name!@redis-client:/$
```

### Are you using any custom parameters or values?

```YAML
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: "openebs-hostpath"
  redis:
    password: ""
nameOverride: ""
fullnameOverride: ""
clusterDomain: cluster.local
commonAnnotations: {}
commonLabels: {}
extraDeploy: []
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity
image:
  registry: gitimages.exsample.com
  repository: general/redis-cluster/redis-cluster-json-search
  tag: 7.0.7-debian-11-r0
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
networkPolicy:
  enabled: false
  allowExternal: true
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
serviceAccount:
  create: false
  name: ""
  annotations: {}
  automountServiceAccountToken: false
rbac:
  create: false
  role:
    rules: []
podSecurityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
  sysctls: []
podDisruptionBudget: {}
minAvailable: ""
maxUnavailable: ""
containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true
usePassword: true
password: ""
existingSecret: ""
existingSecretPasswordKey: ""
usePasswordFile: false
tls:
  enabled: false
  authClients: true
  autoGenerated: false
  existingSecret: ""
  certificatesSecret: ""
  certFilename: ""
  certKeyFilename: ""
  certCAFilename: ""
  dhParamsFilename: ""
service:
  ports:
    redis: 6379
  nodePorts:
    redis: ""
  extraPorts: []
  annotations: {}
  labels: {}
  type: ClusterIP
  clusterIP: ""
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  sessionAffinityConfig: {}
persistence:
  enabled: true
  path: /bitnami/redis/data
  subPath: ""
  storageClass: ""
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: 15Gi
  matchLabels: {}
  matchExpressions: {}
volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 11-debian-11-r63
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  containerSecurityContext:
    enabled: true
    runAsUser: 0
    privileged: false
  resources:
    limits: {}
    requests: {}
podSecurityPolicy:
  create: false
redis:
  command: []
  args: []
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  podManagementPolicy: Parallel
  hostAliases: []
  hostNetwork: false
  useAOFPersistence: "yes"
  containerPorts:
    redis: 6379
    bus: 16379
  lifecycleHooks: {}
  extraVolumes: []
  extraVolumeMounts: []
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  initContainers: []
  sidecars: []
  podLabels: {}
  priorityClassName: ""
  defaultConfigOverride: ""
  configmap: ""
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  podAnnotations: {}
  resources:
    limits: {}
    requests: {}
  schedulerName: ""
  shareProcessNamespace: false
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
  startupProbe:
    enabled: false
    path: /
    initialDelaySeconds: 300
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
updateJob:
  activeDeadlineSeconds: 600
  command: []
  args: []
  hostAliases: []
  annotations: {}
  podAnnotations: {}
  podLabels: {}
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraVolumes: []
  extraVolumeMounts: []
  initContainers: []
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  priorityClassName: ""
  resources:
    limits: {}
    requests: {}
cluster:
  init: true
  nodes: 6
  replicas: 1
  externalAccess:
    enabled: true
    service:
      type: LoadBalancer
      port: 6379
      loadBalancerIP: []
      loadBalancerSourceRanges: []
      annotations: {}
  update:
    addNodes: true
    currentNumberOfNodes: 6
    currentNumberOfReplicas: 1
    newExternalIPs: []
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/redis-exporter
    tag: 1.45.0-debian-11-r17
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources: {}
  extraArgs: {}
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
  podLabels: {}
  containerSecurityContext:
    enabled: false
    allowPrivilegeEscalation: false
  serviceMonitor:
    enabled: false
    namespace: ""
    interval: ""
    scrapeTimeout: ""
    selector: {}
    labels: {}
    annotations: {}
    jobLabel: ""
    relabelings: []
    metricRelabelings: []
  prometheusRule:
    enabled: false
    additionalLabels: {}
    namespace: ""
    rules: []
  priorityClassName: ""
  service:
    type: ClusterIP
    clusterIP: ""
    loadBalancerIP: ""
    annotations: {}
    labels: {}
sysctlImage:
  enabled: true
  command:
    - /bin/sh
    - -c
    - |-
      install_packages systemd
      sysctl -w net.core.somaxconn=10000
      echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
  registry: docker.io
  repository: bitnami/bitnami-shell
  tag: 11-debian-11-r63
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  mountHostSys: true
  containerSecurityContext:
    enabled: true
    runAsUser: 0
    privileged: true
  resources:
    limits: {}
    requests: {}
```

### What is the expected behavior?

I'm not sure if this okay

### What do you see instead?

the problem in the output

### Additional information

already provisioned.
