### ISSUE TITLE
[bitnami/mastodon] problems deploying chart mastodon-init never finished when initJob.createAdmin is true

### ISSUE THREAD

**Issue by showxu** [bitnami/charts#14485]
### Name and Version

mastodon-1.0.0  4.0.2

### What steps will reproduce the bug?

1. mastodon-1.0.0  4.0.2  deployed on both TKG and docker-desktop
2. values.yaml 
   ```
   initJob.createAdmin: true
   adminUser: "user"
   adminEmail: "user@google.com"
   adminPassword: "abc1234567890"
   ```
3. `$ kubectl logs mastodon-init-5l8sb`,  console output:

   ```
   ERROR ==> Error creating admin user
   ```

### Are you using any custom parameters or values?

NO

### What is the expected behavior?

state of `mastodon-web-xxxx` shows Completed instead of NetReady

### What do you see instead?

```
ERROR ==> Error creating admin user
```

### Additional information

I have to turn off the ` initJob.createAdmin: false`, and create admin manually with `tootctl`.

**Comment by carrodher** [comment]
Please note in the _values.yaml_ file the `initJob.createAdmin: true` format is not valid, you need to expand it as follows
```yaml
initJob:
  createAdmin: true
```

**Comment by showxu** [comment]
> Please note in the _values.yaml_ file the `initJob.createAdmin: true` format is not valid, you need to expand it as follows
> 
> ```yaml
> initJob:
>   createAdmin: true
> ```

Yes, yaml format is valid which is copied from  charts/mastodon/value.yaml.

Only the following config works.

```
initJob:
  createAdmin: false
```

**Comment by migruiz4** [comment]
Hi @showxu,

Thank you for reporting this issue.

Could you please share the values `MASTODON_ADMIN_EMAIL` and `MASTODON_ADMIN_USERNAME: user` in the Mastodon configmap?

```console
$ k get cm <your-release-name>-mastodon-default -o yaml
apiVersion: v1
data:
  DB_HOST: test-postgresql
  DB_NAME: bitnami_mastodon
  DB_PORT: "5432"
  DB_USER: bn_mastodon
  ES_ENABLED: "true"
  ES_HOST: test-elasticsearch
  ES_PORT: "9200"
  MASTODON_ADMIN_EMAIL: user@changeme.com
  MASTODON_ADMIN_USERNAME: user
  ...
```

There was an issue with the Mastodon default values, that forced us to change the default email `user@example.com` (https://github.com/bitnami/containers/pull/19154/files). 
By default, Mastodon will block the email domain `example.com` unless it is explicitly set in the environment variable `MASTODON_EMAIL_DOMAIN_ALLOWLIST`. 
Setting this variable by default had other major drawbacks, so we had to remove it and change the default admin email.

Version 1.0.0 of the chart still uses `user@example.com` as default value, causing the error described in your PR, but shouldn't happen if a different value for `adminEmail` is provided. Thus why I'm asking for the running configuration.

**Comment by migruiz4** [comment]
Also, I would like to mention that failed pods from previous deployment jobs won't be deleted automatically, so it is possible that the mastodon-init pod corresponds to a previously failed deployment using the default `adminEmail` value.

**Comment by showxu** [comment]
> Additionally, I would like to mention that failed pods from previous deployment jobs won't be deleted automatically, so it is possible that the mastodon-init pod corresponds to a previously failed deployment using the default `adminEmail` value.

Since I always use `helm delete` mastodon deployment and use `kubectl pvc delete` before each `helm install`, this scene may never happened?

My failed deployment values.yaml as follows:

```yaml
adminUser: "admin"
## @param adminEmail Mastodon admin email
##
adminEmail: "admin@google.com"
## @param adminPassword Mastodon admin password
##
adminPassword: "abc1234567890"
```
It failed and I think this user name "admin" is preserved, so I changed to:

```yaml
adminUser: "admin2"
## @param adminEmail Mastodon admin email
##
adminEmail: "admin2@google.com"
## @param adminPassword Mastodon admin password
##
adminPassword: "abc1234567890"
```

also failed, and then I use my real one:

```yaml
adminUser: "showxu"
## @param adminEmail Mastodon admin email
##
adminEmail: "show.xdxu@icloud.com"
## @param adminPassword Mastodon admin password
##
adminPassword: "abc1234567890"
```

and it fails again. 

Both 'admin2' and 'showxu' can be created by tootctl.
