### ISSUE TITLE
[bitnami/zookeeper] volumePermissions.containerSecurityContext.runAsUser is missing from the zookeeper statefulset.yaml

### ISSUE THREAD

**Issue by abhayycs** [bitnami/charts#14494]
### Name and Version

bitnami/zookeeper

### What steps will reproduce the bug?
```
helm upgrade --install --namespace test --create-namespace myzookeeper bitnami/zookeeper --set replicaCount=3  --set persistence.enabled=true --set volumePermissions.enabled=true --set volumePermissions.containerSecurityContext.runAsUser=true
```

### What is the expected behavior?

```
initContainer:
    volumePermissions:
      containerSecurityContext:
        runAsUser: 0
```

### What do you see instead?

initContainer is unable to perform chown command:
```
tester@bln-k8s-71 ➜  test-helm-charts git:(persistence_issue_zookeeper) ✗ k logs -f test-kafka-zookeeper-2 -c volume-permissions
chown: changing ownership of '/bitnami/zookeeper': Operation not permitted
```

### Additional information

I think volumePermissions.containerSecurityContext.runAsUser is missing from the zookeeper statefulset.yaml

**Comment by javsalgar** [comment]
Hi,

Could you try removing the `initContainer` part so it looks like this?

```
    volumePermissions:
      containerSecurityContext:
        runAsUser: 0
```

**Comment by abhayycs** [comment]
My concern is "--set volumePermissions.containerSecurityContext.runAsUser=true" parameter is not working with helm

when we enable persistence (--set persistence.enabled=true --set volumePermissions.enabled=true), it add initContainer section, where it does some chown operations, which is failing.

I'm only using the helm command, not editing the 'initContainer' separately.

**Comment by abhayycs** [comment]
Hi Javsalgar,

I'm only using the helm command, not editing the 'initContainer' separately.

My concern is "--set volumePermissions.containerSecurityContext.runAsUser=true" parameter is not working with helm.
when we enable persistence (--set persistence.enabled=true --set volumePermissions.enabled=true), it add initContainer section, where it does some chown operations, which is failing.

when I am using kubectl edit pod myzookeeper-0 -n test
I am not able to see: runAsUser: 0 for the initContainer.
I want to enable it for this initContainer by using "--set volumePermissions.containerSecurityContext.runAsUser=true", but it is not working.
I hope it explains the issue.

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue.

I ran this

```
helm install zookeeper bitnami/zookeeper --set volumePermissions.containerSecurityContext.runAsUser=0 --set volumePermissions.enabled=true --debug --dry-run
```

and got this

```
      initContainers:
        - name: volume-permissions
          image: docker.io/bitnami/bitnami-shell:11-debian-11-r69
          imagePullPolicy: "IfNotPresent"
          command:
            - /bin/bash
          args:
            - -ec
            - |
              mkdir -p /bitnami/zookeeper
              chown -R 1001:1001 /bitnami/zookeeper
              find /bitnami/zookeeper -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | xargs -r chown -R 1001:1001
          securityContext:
            runAsUser: 0
```

As you can see the `runAsUser` is there.
