### ISSUE TITLE
Unable to run keycloak at /http path

### ISSUE THREAD

**Issue by happy0088** [bitnami/charts#14507]
### Name and Version

bitnami/keycloak appVersion: 20.0.1

### What steps will reproduce the bug?

update the below params :
```yaml
  ## @param ingress.path Default path for the ingress record
  ##
  path: /auth

httpRelativePath: "/auth"
```
**Readiness probe**
```yaml
readinessProbe:
  enabled: true
  httpGet:
    path: /auth/realms/master
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1
```

and try to bring the pod using helm 

`helm upgrade --install keycloak-release . -f values.yaml -n keycloak-test`

pod fails to initialize.

Error 
```
Warning  Unhealthy  21m (x8 over 22m)     kubelet            Readiness probe failed: HTTP probe failed with statuscode: 500
Warning  Unhealthy  3m6s (x125 over 21m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 404
``` 

saw the below in the documentation
> By default, the new Quarkus distribution removes /auth from the context-path. To re-introduce the /auth use the http-relative-path build option. For example: `bin/kc.[sh|bat] start-dev --http-relative-path /auth`

But couldn't figure out how to pass this parameter while running from a helm.

### Are you using any custom parameters or values?

httprelative path set to /http

### What is the expected behavior?

keycloak should run on /auth path

### What do you see instead?

fails to start

### Additional information

I am migrating from V14 to V20 and trying to retain the /auth path for application backward compatibility.

we are using a custom mapper for adding authorization headers in the token which is passed externally.

Thanks.

**Comment by fmulero** [comment]
Sorry @happy0088 for my very late response.

I am not sure but I think `httpRelativePath` must start and end with `/`.  Please note that if you want to change the default `readinessProbe` you have to set value `customReadinessProbe` in this way:

```yaml
customReadinessProbe:
  httpGet:
    path: /auth/realms/master
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1
```

You can find the `http-relative-path` parameter in the `keycloack.conf` file of your container:
```console
$ kubectl exec -it <your container here> -- tail /opt/bitnami/keycloak/conf/keycloak.conf
#hostname=myhostname
http-enabled = true
http-relative-path = /auth/
http-port = 8080
https-port = 8443
hostname-strict = false
cache-stack = kubernetes
cache = ispn
log-level = info
log-console-output = default
```
