### ISSUE TITLE
[bitnami/harbor] Chart Since Version 16.1.0: TLS handshake error from XXX remote error: tls: bad certificate

### ISSUE THREAD

**Issue by torsten-online** [bitnami/charts#14514]
### Name and Version

bitnami/harbor 16.3.1

### What steps will reproduce the bug?

Hi Bitnami Harbor Chart Users, 

I run into the issue since Chart Version 16.1.0 that the auto-setup of self-signed internalTLS is not working fine, 
so we run into the "bad certificate" issue.

Deployments are tested by clear-setup. The Harbor Chart Version 16.0.4 is Running fine with my Setup!

1. Environment

RKE2 latest Cluster with 3 Master and 3 Worker nodes deployed over Rancher.

Harbor Chart Version affected: 16.3.0 since 16.1.0
Harbor Chart Version running all fine: 16.0.4

2. Config

`````yaml
harbor:
  global:
    imageRegistry: "docker.registry.hub"
    imagePullSecrets:
      - pullsecret
    storageClass: "csi-cinderstorage"
  
  adminPassword: "XXX"
  
  
  nginx:
    tls:
      enabled: true
  service: 
    type: ClusterIP

  proxy:
    httpProxy: "http://myproxy:1234"
    httpsProxy: "http://myproxy:1234"
    noProxy: "127.0.0.1,localhost,.local,.internal,.mydomain.test,.mydomain.dev"
    components:
      - core
      - jobservice
      - trivy

  logLevel: debug

  internalTLS:
    enabled: true
    caBundleSecret: "squid-proxy-ca"
  
  ipFamily:
    ipv6:
      enabled: false

`````
3. Run
After the Deployment - harbor instance is running - and all pod's status are ok.

Trivy is not running with internal TLS and have the status "Error" at container logfile.

4. See Error

`````
TLS handshake error from XXX remote error: tls: bad certificate
`````

### Are you using any custom parameters or values?

look environment configuration

### What is the expected behavior?

Trivy and Harbor out of service

### What do you see instead?

Deployment with Chart Version 16.0.4, which is running fine 

### Additional information

Is there a difference by deployment of secrets for internalTLS? 

There seems to be a change of existingEnvVarsSecret to be a secret.
