### ISSUE TITLE
service.type=LoadBalancer can't be securely used with aws-load-balancer-controller

### ISSUE THREAD

**Issue by mouchar** [bitnami/charts#14523]
### Name and Version

bitnami/postgresql-ha:11.0.0

### What steps will reproduce the bug?

1. **Environment:** AWS EKS with aws-load-balancer-controller-1.4.6 installed. Installing `bitnami/postgresql-ha:11.0.0` chart.
2. **Config:** see below, file `/tmp/example.yaml`
3. **Run:** `helm install postgresql-ha bitnami/postgresql-ha -f /tmp/example.yaml`
4. **Error**: No error, but dangerous Service configurations are generated

### Are you using any custom parameters or values?

```
service:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 1.2.3.4/32
    - 5.6.7.8/32
  externalTrafficPolicy: Local
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-name: pgpool
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
    service.beta.kubernetes.io/aws-load-balancer-type: external
```

### What is the expected behavior?

I expect the possibility to control annotations per service. The reason is that only LoadBalancer service must have annotations that control the creation of cloud resources like Target Groups or updating Security Groups.

### What do you see instead?

There's just one common variable `service.annotations` that is shared between pgpool and postgresql services, so both services will have the same set of annotations.

# Why it is wrong/dangerous:
1. pgpool creates target group and updates security group with a list of IPs, allowing access to the **pgpool port 5432**. A new Load Balancer is created and target group is attached to its listener. So far so good, this is desired configuration. 
2. postgresql service has hard-coded ClusterIP type, but `service.beta.kubernetes.io/aws-load-balancer-*` annotations cause ingress controller to create another target group for this service. This service doesn't have `loadBalancerSourceRanges` specified, so default value 0.0.0.0/0 will be used in security group rule allowing access from anywhere to **postgresql port 5432**. No LoadBalacer will be created.

The outcome of this configuration is that security group will allow access to port 5432 from anywhere regardless of the contents of loadBalancerSourceRanges. This is because port 5432 is the same for pgpool and postgresql.

### Additional information

Remedy?

Allow configuring pgpool service annotations separately from potgresql service annotations. The same pattern is already used for metrics. It might be problematic to make it backward compatible.

Or at least describe this behavior in documentation to let people know that they can't rely on `loadBalancerSourceRanges` when using aws-load-balancer-controller. I don't know how much are other controllers affected.
