### ISSUE TITLE
Ghost instance recreate fails

### ISSUE THREAD

**Issue by murarustefaan** [bitnami/charts#14527]
### Name and Version

CHART: bitnami/ghost-19.1.60  |  APP: 5.31.0

### Environment: 
Rancher Kubernetes 1.25.3 cluster provisioned.

### Config: 
Added another MySQL Secondary instance, provided all passwords & co and modified Service Type to ClusterIP.

I also dived the Docker image and noticed those paths have an ownership of 0:0, yet the image is run as user 1001.

### Are you using any custom parameters or values?

```yaml
ghostEnableHttps: false
service:
  type: ClusterIP
persistence:
  enabled: true
  storageClass: "wdata"
  accessModes:
    - ReadWriteMany
volumePermissions:
  enabled: true
mysql:
  enabled: true
  architecture: replication
  auth:
    rootPassword: "redacted"
    database: ghost
    username: ghost
    password: "redacted"
    existingSecret: ""
    replicationPassword: "redacted"
  primary:
    persistence:
      enabled: true
      storageClass: "wdata"
      accessModes:
        - ReadWriteOnce
      size: 20Gi
  secondary:
    persistence:
      enabled: true
      replicas: 1
      storageClass: "wdata"
      accessModes:
        - ReadWriteOnce
      size: 20Gi
```

### What is the expected behavior?

Ghost should start and run correctly.

### What do you see instead?

```
➜  k logs website-v2-ghost-d6f6446cb-4lpk4 -f
Defaulted container "website-v2-ghost" out of: website-v2-ghost, volume-permissions (init)
ghost 20:38:24.62
ghost 20:38:24.62 Welcome to the Bitnami ghost container
ghost 20:38:24.63 Subscribe to project updates by watching https://github.com/bitnami/containers
ghost 20:38:24.63 Submit issues and feature requests at https://github.com/bitnami/containers/issues
ghost 20:38:24.63
ghost 20:38:24.63 INFO  ==> Configuring libnss_wrapper
ghost 20:38:24.65 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
ghost 20:38:24.67 DEBUG ==> Validating settings in GHOST_* environment variables...
ghost 20:38:24.73 INFO  ==> Ensuring Ghost directories exist
ghost 20:38:24.74 INFO  ==> Trying to connect to the database server
ghost 20:38:24.74 DEBUG ==> Executing SQL command:
SELECT 1
1
ghost 20:38:24.75 INFO  ==> Configuring database
ghost 20:38:24.93 INFO  ==> An already initialized Ghost database was provided, configuration will be skipped
ghost 20:38:24.93 INFO  ==> Persisting Ghost installation
ghost 20:38:25.15 INFO  ==> ** Ghost setup finished! **

ghost 20:38:25.24 INFO  ==> ** Starting Ghost **

Love open source? We’re hiring JavaScript Engineers to work on Ghost full-time.
https://careers.ghost.org

- Inspecting operating system
[2023-01-24 20:38:28] INFO Ghost is running in production...
[2023-01-24 20:38:28] INFO Your site is now available on http://localhost:2368/
[2023-01-24 20:38:28] INFO Ctrl+C to shut down
[2023-01-24 20:38:28] INFO Ghost server started in 1.491s
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/opt/bitnami/ghost/versions/5.31.0/content/logs/http___localhost_2368_production.error.log'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:335:14
    at FSReqCallback.oncomplete (fs.js:180:23) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/opt/bitnami/ghost/versions/5.31.0/content/logs/http___localhost_2368_production.error.log'
}
```
