### ISSUE TITLE
[bitnami/keycloak] External Secrets Documentation Unclear

### ISSUE THREAD

**Issue by jinja2ninja** [bitnami/charts#14531]
### Name and Version

bitnami/keycloak 13.02

### What is the problem this feature will solve?

I am unable to figure out how to use an existing secret with this chart. I have attempted various things, but nothing seems to actually set the postgresql password. If someone can help point me in the correct direction, I'd be more than happy to submit a PR to make the documentation more clear.

I found a similar issue that went stale with someone having a similar complaint. https://github.com/bitnami/charts/issues/10544

This is what my current values.yaml looks like (I have stripped this down to be as basic as possible to try and narrow down the issue) 
```
existingSecret:
  name: keycloak-secret
  secretKeys:
    admin-password: admin-password
```

I have an existing secret in the same namespace named `keycloak-secret` that has a key `admin-password`, however when installing the chart using this values.yaml, the password doesn't work. It seems that helm is creating another secret in the same namespace alongside the existing one.
```
Name:         keycloak
Namespace:    keycloak
Labels:       app.kubernetes.io/component=keycloak
              app.kubernetes.io/instance=keycloak
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=keycloak
              helm.sh/chart=keycloak-13.0.2
Annotations:  meta.helm.sh/release-name: keycloak
              meta.helm.sh/release-namespace: keycloak

Type:  Opaque

Data
====
admin-password:  10 bytes
```

### What is the feature you are proposing to solve the problem?

Like I said, I'd be more than happy to update the documentation if someone can help me get this sorted out. I think ideally the documentation should provide a more clear explaination of what the values need to be, and pehaps some more examples. Using a very vanilla values file with the example from the documentation doesn't seem to work as expected for me.

### What alternatives have you considered?

I could just install the chart without the values, and then get the secret value, but I would like to be able to use the chart as intended.

**Comment by migruiz4** [comment]
Hi @jinja2ninja,

Thank you very much for reporting this issue, and I'm sorry that the documentation is outdated.

In version `11.x.x` we refactored Keycloak secrets configuration along with other changes: https://github.com/bitnami/charts/pull/13103

I wrote this summary with all the new values used to provide each secret, I hope it helps clarify this:
```yaml
# Keycloak password secret
auth:
  # Secret containing the admin password (default key 'admin-password')
  existingSecret: ""
  # Set a different key if needed
  passwordSecretKey: ""
# Keycloak HTTPS secret
tls:
  # Secret containing the Keystore and Truststore
  existingSecret: ""
  # Secret containing the Keystore and Truststore passwords (keys 'tls-keystore-password' and 'tls-truststore-password')
  passwordsSecret: ""
# Keycloak SPI TLS secret
spi:
  # Secret containing the truststore for SPI verification
  existingSecret: ""
  # Secret containing the truststore password (keys 'spi-truststore-password')
  passwordsSecret: ""
# Postgresql subchart credentials secret
postgresql:
  auth:
    # Existing secret containing the keys 'password' and 'postgres-password'
    existingSecret: ""
# External database secret
externalDatabase:
  # Existing secret containing the external database password, default key 'db-password'
  existingSecret: ""
  # Set a different key if needed
  existingSecretPasswordKey: ""
```

Please don't hesitate to let me know if you have any further questions.

**Comment by jinja2ninja** [comment]
Awesome thank you for the the clarification, this worked for me. I will for the repo and create a PR to update the documentation. Just for posterity, here is what my values.yaml looks like now

```
auth:
  existingSecret: keycloak-secret
  passwordSecretKey: admin-password
  adminUser: admin

postgresql:
  enabled: true
  existingSecret: keycloak-secret
  secretKeys:
    adminPasswordKey: postgres_admin_password
    userPasswordKey: postgres_user_password
    replicationPasswordKey: postgres_replication_password
```
