### ISSUE TITLE
Can't login to rabbitmq management with ingress/metallb on microk8s deployment

### ISSUE THREAD

**Issue by DaveDevalore** [bitnami/charts#14533]
### Name and Version

bitnami/rabbitmq 11.5.0

### What steps will reproduce the bug?

1. install microk8s and enable ingress
2. deploy rabbitmq

### Are you using any custom parameters or values?
```yaml
 namespaceOverride: deployment
 release:
  namespace: deployment
service:
   type: LoadBalancer
   annotations:
     metallb.universe.tf/loadBalancerIPs: 192.168.0.106
     metallb.universe.tf/address-pool: services-pool

 auth:
   username: "admin"
   password: "rmq-password"
   tls:
     enabled: true
     autoGenerated: false
     failIfNoPeerCert: false
     existingSecret: "rmq-master-certs"
     sslOptionsVerify: "verify_none"

 ingress:
   enabled: true
   annotations:
     cert-manager.io/cluster-issuer: vault-super-issuer
     cert-manager.io/common-name: rmq.kube.local
     nginx.ingress.kubernetes.io/use-regex: 'true'
   hostname: rmq.kube.local
   path: /(.*)
   pathType: Prefix
   ingressClassName: nginx
   tls: true
```
### What is the expected behavior?

login to work and let me through

### What do you see instead?

I repeatedly get a popup asking me to enter credentials, 
on the logs I see "HTTP access denied: user 'admin' - invalid credentials"
This fails when I try to use the ingress connection, metallb and port-forward to the service.

![image](https://user-images.githubusercontent.com/106315695/214534937-bdfec437-8b55-4e00-bbbf-4cfc37e1747a.png)
![image](https://user-images.githubusercontent.com/106315695/214534989-2087e86e-55ad-49d1-a845-6e4dec58eb07.png)
