### ISSUE TITLE
External-dns doesn't work with dyn provider

### ISSUE THREAD

**Issue by oksanakalyuzhenko** [bitnami/charts#14537]
### Name and Version

bitnami/external-dns:6.13.1

### What steps will reproduce the bug?

Install chart: bitnami/external-dns:6.13.1 for dyn provider.

### Are you using any custom parameters or values?

```yaml
policy: "sync"
provider: dyn
zoneIdFilters: ["example.com"]
rbac:
  create: true
extraEnvVars:
  - name: EXTERNAL_DNS_DYN_CUSTOMER_NAME
    value: example
  - name: EXTERNAL_DNS_DYN_USERNAME
    value: user-name
  - name: EXTERNAL_DNS_DYN_PASSWORD
    value: 'password'
txtOwnerId:  test
txtPrefix:  test
```

### What is the expected behavior?

'Running' status for external-dns pods and listening changes for the specified zone

### What do you see instead?

external-dns pod logs:
```
time="2023-01-25T11:26:42Z" level=info msg="Instantiating new Kubernetes client"
time="2023-01-25T11:26:42Z" level=info msg="Using inCluster-config based on serviceaccount-token"
time="2023-01-25T11:26:42Z" level=info msg="Created Kubernetes client https://X.X.X.X:443"
time="2023-01-25T11:26:43Z" level=info msg="Configured zones: [example.com]"
panic: interface conversion: interface {} is nil, not *dynsoap.GetAllRecordsResponseType

goroutine 1 [running]:
sigs.k8s.io/external-dns/provider/dyn.(*dynProviderState).fetchAllRecordsInZone(0xc000e485b0, {0x7ffeac658d51, 0xb})
        /bitnami/blacksmith-sandox/external-dns-0.13.2/src/github.com/kubernetes-incubator/external-dns/provider/dyn/dyn.go:403 +0x7e5
sigs.k8s.io/external-dns/provider/dyn.(*dynProviderState).Records(0xc000e485b0, {0xc000cbaa40?, 0x43bc20?})
        /bitnami/blacksmith-sandox/external-dns-0.13.2/src/github.com/kubernetes-incubator/external-dns/provider/dyn/dyn.go:622 +0x5df
sigs.k8s.io/external-dns/registry.(*TXTRegistry).Records(0xc0006d8160, {0x3799688?, 0xc000631d80?})
        /bitnami/blacksmith-sandox/external-dns-0.13.2/src/github.com/kubernetes-incubator/external-dns/registry/txt.go:98 +0xac
sigs.k8s.io/external-dns/controller.(*Controller).RunOnce(0xc000778ea0, {0x3799688, 0xc000631d80})
        /bitnami/blacksmith-sandox/external-dns-0.13.2/src/github.com/kubernetes-incubator/external-dns/controller/controller.go:164 +0x52
sigs.k8s.io/external-dns/controller.(*Controller).Run(0xc000778ea0?, {0x3799688, 0xc000631d80})
        /bitnami/blacksmith-sandox/external-dns-0.13.2/src/github.com/kubernetes-incubator/external-dns/controller/controller.go:294 +0xc5
main.main()
        /bitnami/blacksmith-sandox/external-dns-0.13.2/src/github.com/kubernetes-incubator/external-dns/main.go:412 +0x3b85
```
