### ISSUE TITLE
Can't access etcd when installing with default values

### ISSUE THREAD

**Issue by dardanos** [bitnami/charts#1454]
**Which chart**:
```yml
- name: etcd
  repository: https://charts.bitnami.com/bitnami
  version: 4.3.5
```
**Description**
When I try to run `etcdctl` against the deployed chart I get

```
Error: etcdserver: user name is empty
```

**Steps to reproduce the issue:**

1. Install the chart with the following values
    ```yml
     nameOverride: 'etcd'  
     image:
       tag: 3.4.0-debian-9-r0
   ```
2. Forward the port to work connect to etcd locally
    ```
    kubectl port-forward <pod-name> 2379
    ```
3. Run `etcdctl get /`

**Describe the results you received:**

```
Error: etcdserver: user name is empty
```

**Describe the results you expected:**

A valid response with an empty etcd 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
