### ISSUE TITLE
[bitnami/kube-prometheus] Ingress for thanos with empty address

### ISSUE THREAD

**Issue by pedrovalido** [bitnami/charts#14569]
### Name and Version

bitnami/kube-prometheus

### What steps will reproduce the bug?

Deploying kube-prometheus chart using thanos sidecar for prometheus and ingress for thanos. The ingress does not have and attributed address.

### Are you using any custom parameters or values?

```yaml
prometheus:
  enabled: true
  thanos:
    create: true
    service:
      type: LoadBalancer
    ingress:
      enabled: true
      hostname: thanos.example.org
  service:
    type: ClusterIP
  externalLabels:
    cluster: "external-label"

operator:
  service:
    type: ClusterIP

alertmanager:
  service:
    type: ClusterIP
```

### What is the expected behavior?

The expected behavior is having a load balancer service "thanos" with external IP and ingress that would get the same IP as the load balancer. 

### What do you see instead?

The ingress has an empty address, not getting the same external IP as the Load Balancer service.
