### ISSUE TITLE
thanos: prometheusRules and additionalLabel failure

### ISSUE THREAD

**Issue by bdols** [bitnami/charts#14595]
### Name and Version

bitnami/thanos 12.0.0

### What steps will reproduce the bug?

Providing `additiionalLabel` for prometheusRule fails to render PrometheusRules:

```yaml
metrics:
  enabled: true
  prometheusRule:
    additionalLabels:
      my-alert: enabled
```

example rendering:
```yaml
# Source: thanos/templates/alert-rule/absent_rules.yml

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: release-name-thanos-component-absent
  namespace: "monitoring"
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-12.0.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    my-alert: enabled
spec:
  groups:
  - name: thanos-component-absent
    rules:
    - alert: ThanosCompactIsDown
      annotations:
        description: ThanosCompact has disappeared. Prometheus target for the component cannot be discovered.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompactisdown
        summary: Thanos component has disappeared.
      expr: |
        absent(up{job=~".*thanos-compact.*"} == 1)
      for: 5m
      labels:
        severity: critical
                my-alert: enabled
```

note the failed indentation in the last line, whereas the label is indented correctly in the metadata

### What is the expected behavior?

Nice to see some sample rules provided in this chart!
I have prometheus-operator configured to pick up rules based on a configurable label so I expect that I can use the `additionalLabel` setting to enable these.

### What do you see instead?

```
Error: YAML parse error on thanos/templates/alert-rule/absent_rules.yml: error converting YAML to JSON: yaml: line 26: mapping values are not allowed in this context
helm.go:84: [debug] error converting YAML to JSON: yaml: line 26: mapping values are not allowed in this context
YAML parse error on thanos/templates/alert-rule/absent_rules.yml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
        helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
        helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
        helm.sh/helm/v3/pkg/action/action.go:165
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
        helm.sh/helm/v3/pkg/action/install.go:259
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:264
```
