### ISSUE TITLE
Deploy wordpress at subpath rather than / and rewrite with ingress

### ISSUE THREAD

**Issue by Msarnaot** [bitnami/charts#1461]
**Which chart**:
Wordpress
**Description**
I am looking to deploy wordpress on Kubernetes google cloud and I'm using this chart, however we are looking to run wordpress from the /blog path on our domain. So in our ingress we set rule that /blog requests are served by the wordpress service generated from the helm chart. However we ran into problems with that, and realized that we need wordpress to know that its running at /blog for relative files to work. To that end we added the following setting as per the description of the chart ```ingress.hosts[0].path: /blog```.  That unfortunately didn't work either.
We also added to the wp_config.php file in bitnami/wordpress/wp_config.php the following:
define( 'WP_HOME', 'http://example.com' );
define( 'WP_SITEURL', 'http://example.com' );
However it still didn't work. Mainly the problem that persists is that wordpress loads at mydomain.com/blog however non of the css or js files load. 

**Version of Helm and Kubernetes**:
We are using GKE. And helm client and remote version v2.14.3
- Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.25", GitCommit:"d4c79083ab6dea5d26ef4ed8d50b145268349bc3", GitTreeState:"clean", BuildDate:"2019-06-22T16:10:31Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by rafariossaa** [comment]
Hi @Msarnaot ,
  That option is not supported by default.
  Could  you try what is indicated by wordpress for path change? https://wordpress.org/support/article/changing-the-site-url/

**Comment by Msarnaot** [comment]
Hey @rafariossaa,
That make sense,  I actually had already follow the instruction on that link. It works in some ways but not completely.  We updated the wp_config.php to http//ourdomain.com/blog, and it loads but without any styling or js loading. I noticed in the network tab in dev tools its not able to find those files. Can you please advice?

**Comment by rafariossaa** [comment]
Did you made changes in the database ?
https://wordpress.org/support/article/changing-the-site-url/#changing-the-url-directly-in-the-database

**Comment by Msarnaot** [comment]
Hi raferiossaa, making those changes worked, thank you for. your replies. However,  after testing  it seemed like one thing isn't working which is installing new themes and plugins. I searched around and tried changing the Wordpress plugin install path however nothing seems to work. Please let me know if you have any potential steps for this.

**Comment by juan131** [comment]
Hi everyone,

This same topic is being discussed in the issue below:

https://github.com/helm/charts/issues/17196

**Comment by Msarnaot** [comment]
@juan131 thanks for referencing, @rafariossaa thanks for helping out. I was able to get it to work, although in a pretty round about way, that I'm not sure how it will scale.
I deploy wordpress via bitnami helm chart. 
I then SSHed into running pod and and navigated to opt/bitnami/wordpress. Over there I changed wp-config as per those instructions https://wordpress.org/support/article/changing-the-site-url/

After that I changed the site url and home records in wp_options table in mysql db as per those instructions https://wordpress.org/support/article/changing-the-site-url/#changing-the-url-directly-in-the-database

Finally, I had to create a new folder inside that folder called /blog, and copied all my folders inside it, make sure the user that has access to the files/folders inside blog is the same as in the original folder, and that resolved the 404 issue for me.

**Comment by Msarnaot** [comment]
@juan131 Agreed! 
I wanted to follow up and ask if the redirections configurations you mentioned above are part of the road map for bitnami?

**Comment by juan131** [comment]
Hi @Msarnaot 

We're not planning to implement an "easy (or direct)" way to configure these redirections in the short team. At this point, we're just offering a chart as flexible as possible, so users can add any redirection they desire.

**Comment by Msarnaot** [comment]
@juan131 can you recommend how we can potentially add this redirection? If there any docs or instructions you can share.

**Comment by juan131** [comment]
Hi @Msarnaot 

We discussed some of the alternatives on this thread:

https://github.com/helm/charts/issues/17196

The might be helpful for you.

**Comment by rafariossaa** [comment]
Hi, @PavelYarysh 
  Could you open a new issue ? This way we can take care properly of the details of your issue.

Thanks forehand

**Comment by mhoskiso** [comment]
Hi @PavelYarysh ,

I had the same problem. Here are the steps I took which appear to be working.

**Update these wp-config.php for the /blog path**
define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] . '/blog/');
define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST'] . '/blog/');
define('WP_CONTENT_URL', 'http://' . $_SERVER['HTTP_HOST'] . '/blog/wp-content/');

**In the helm chart's deployment.yaml, add this to the wordpress container**
lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "ln -s /opt/bitnami/wordpress /opt/bitnami/wordpress/blog"]

**Update wordpress ingress path**
- path: /blog

**Comment by juan131** [comment]
Thanks for sharing your workaround @mhoskiso !

**Comment by appunni-dishq** [comment]
> Hi @PavelYarysh ,
> 
> I had the same problem. Here are the steps I took which appear to be working.
> 
> **Update these wp-config.php for the /blog path**
> 
> ```
> define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] . '/blog/');
> define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST'] . '/blog/');
> define('WP_CONTENT_URL', 'http://' . $_SERVER['HTTP_HOST'] . '/blog/wp-content/');
> ```
> 
> **In the helm chart's deployment.yaml, add this to the wordpress container**
> 
> ```
> lifecycle:
>   postStart:
>     exec:
>       command: ["/bin/sh", "-c", "ln -s /opt/bitnami/wordpress /opt/bitnami/wordpress/blog"]
> ```
> 
> **Update wordpress ingress path**
> `- path: /blog`

I believe  wp-config.php accepts environment variables for those in wordpress docker, So passing env vars should do or a configMap

**Comment by rafariossaa** [comment]
Hi, 
 Thanks for sharing.

**Comment by appunni-dishq** [comment]
```
FROM bitnami/wordpress


RUN echo 'define("WP_SITEURL", "http://" . $_SERVER['HTTP_HOST'] . "/blog/");' >> /opt/bitnami/wordpress/wp-config.php
RUN echo 'define("WP_HOME", "http://" . $_SERVER['HTTP_HOST'] . "/blog/");' >> /opt/bitnami/wordpress/wp-config.php
RUN echo 'define("WP_CONTENT_URL", "http://" . $_SERVER['HTTP_HOST'] . "/blog/wp-content/");' >> /opt/bitnami/wordpress/wp-config.php

RUN ln -s /opt/bitnami/wordpress /opt/bitnami/wordpress/blog
```
I wrote it in form of a docker file like this

**Comment by mhoskiso** [comment]
I ended up doing some more modifications since I didn't want to commit the wp-config.php. I added a script that runs sed on the wp-config.php and updated the entrypoint script to run it after wp-config.php is added to /bitnami/wordpress on start up.


**Dockerfile**
```Dockerfile
FROM bitnami/wordpress:5.4.2

COPY scripts/change_blog_path.sh /
COPY scripts/app-entrypoint.sh /

COPY --chown=1001:1001 blog/wp-content /bitnami/wordpress/wp-content
COPY --chown=1001:1001 blog/.htaccess /bitnami/wordpress/
```
**app-entrypoint.sh**
```bash
#!/bin/bash -e

. /opt/bitnami/base/functions
. /opt/bitnami/base/helpers

print_welcome_page

if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "httpd" ]]; then
    . /apache-init.sh
    . /wordpress-init.sh
    nami_initialize apache mysql-client wordpress
    info "Starting gosu... "
    . /post-init.sh
    info "Changing Blog path... "
    . /change_blog_path.sh
fi

exec tini -- "$@"
```
**change_blog_path.sh**
```bash
#!/bin/bash
#

set -o errexit
set -o nounset
set -o pipefail

sed -i "s|. '/');|. '/blog/');|g" /bitnami/wordpress/wp-config.php
```

**Comment by juan131** [comment]
Hi @mhoskiso 

Thanks for sharing your workaround.

Please note that you can also clone the Bitnami WP repo, and include your "sed" modifying the original "post-init.sh" script. This way you don't need to add extra scripts to the image.

**Comment by diogomurta** [comment]
> 
> 
> Hi @PavelYarysh ,
> 
> I had the same problem. Here are the steps I took which appear to be working.
> 
> **Update these wp-config.php for the /blog path**
> 
> ```
> define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] . '/blog/');
> define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST'] . '/blog/');
> define('WP_CONTENT_URL', 'http://' . $_SERVER['HTTP_HOST'] . '/blog/wp-content/');
> ```
> 
> **In the helm chart's deployment.yaml, add this to the wordpress container**
> 
> ```yaml
> lifecycle:
>   postStart:
>     exec:
>       command: ["/bin/sh", "-c", "ln -s /opt/bitnami/wordpress /opt/bitnami/wordpress/blog"]
> ```
> 
> **Update wordpress ingress path**
> `- path: /blog`

 Hi  @appunni-dishq ,
 
Thanks for this workaround, perfect works for me.

Att
@diogomurta

**Comment by PJEstrada** [comment]
Hey guys, 

For anybody struggling with this after like 12 hours of figuring this out, I managed to do it following these steps.

I'm assuming also that you have cloned the bitnami repo to modify some files

## Install Steps

1. Run: `helm dependency update `
2. Add: 
```yaml
lifecycle:
  postStart:
    exec:
      command: ["/bin/sh", "-c", "ln -s /opt/bitnami/wordpress /opt/bitnami/wordpress/blog"]
 ```
To the `deployment.yaml` of the wordpress helmchart, inside the wordpress container section.
2. Open `values.yaml` and replace `wordpressPassword` with the Default login password.
3. Open `values.yaml` and replace `mariadb.auth.password` with the Default MariaDB password.
4. Open `values.yaml` and modify The following: `ingress.enabled` set to `true` , `ingress.ingressClassName` is `nginx`,  `ingress.hostname` is `<your_domain.com>`, `ingress.path` is `/blog`
4. Make sure `kubectl ` is installed and connected to the cluster to deploy Wordpress in.
5. Go inside `wordpress` dir and run: `helm install my-blog . -f values.yaml -n <<YOUR_NAMESPACE>>`
6. After a few minutes you should be able to see the pods, services and ingress for the Wordpress blog.

Note: At this point the blog would only be accessible via The IP on the ingress and not via the
domain name.
## Part 2: Modifying Ingress and Configs So blog is on `/blog` subpath:

1. Install PHP My Admin to Connect to DB:
`helm install phpmyadmin bitnami/phpmyadmin -n <<YOUR_NAMESPACE>>`
2. Connect to MariaDB using:
` kubectl port-forward --namespace <<YOUR_NAMESPACE>> svc/phpmyadmin 8001:80`
3. Login to PhpMyAdmin on `localhost:8001` and enter the credentials provided in the `mariadb.auth` section
inside `values.yaml`
4. Go to the wordpress database and to the `wp_options` table and modify the values of the
`site` and `home` rows to be `https://yourdomain.com/blog`
5. Modify The Ingress (Called: `my-blog-wordpress`). Erase the current rules section
and replace it with the following:
```yaml
      http: <YOUR_DOMAIN>
        paths:
          - path: /(wp.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: my-blog-wordpress
                port:
                  name: http
          - path: /blog
            pathType: ImplementationSpecific
            backend:
              service:
                name: my-blog-wordpress
                port:
                  name: http
```

* Make sure that the service name `my-blog-wordpress` exists, if it has another
name make sure to change it.
* Save the Ingress

At this point you should be able to at least see the login page on 
`<your_domain>/blog/wp-login.php` and be able to login to wp-admin

## Part 3: Changing WP Configurations
In this part we will modify some configuration variables from Wordpress so that the home page of the blog is on
`/blog` subpath.

1. Login to Wordpress in `<your_domain>/blog/wp-login.php` use the credentials in `values.yaml`
2. Install the Plugin `WP File Manager`
3. Go to the Plugin and Edit the file `wp-config.php` so that it has the following definitions:

```
define( 'WP_AUTO_UPDATE_CORE', false );
define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] . '/blog/'); 
define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST'] . '/blog/'); 
define('WP_CONTENT_URL', 'http://' . $_SERVER['HTTP_HOST'] . '/blog/wp-content/'); 
define('WP_ADMIN_URL', 'http://' . $_SERVER['HTTP_HOST'] . '/blog/wp-admin/'); 
```
Any other definitions for the above variables should be removed as the may conflict with the installation.

Close your browser tab and wait a few moments. Hard refresh the URL of your browser, sometimes cache can leave previous redirections active.

* If the update does not work. Make sure you copy the `/opt/bitnami/wordpress/wp-config.php`
file into `/bitnami/wordpress/` folder.

You should now be able to enter the blog and navigate on `/blog` subpath on the domain.

We are done!

**Comment by cangel111** [comment]
Hi guys,

I spent another 24 hours on this and found a simpler and more persistent solution.

1. Add this to the wordpress section in `deployment.yaml` of the helm chart:
```yaml
lifecycle:
  postStart:
    exec:
      command: ["/bin/sh", "-c", "ln -s /opt/bitnami/wordpress /opt/bitnami/wordpress/blog"]
```

2. Add this script in `customPostInitScripts` in `values.yaml`:
```yaml
customPostInitScripts:
  change-wordpress-url.sh: |
    #!/bin/bash
    chmod +w /bitnami/wordpress/wp-config.php
    sed -i -r "s|_SERVER\['HTTP_HOST'\] \. '/'|_SERVER\['HTTP_HOST'\] \. '/blog/'|g" /bitnami/wordpress/wp-config.php
    chmod -w /bitnami/wordpress/wp-config.php
```

This replaces the paths for the Wordpress URLs using `sed` initial in wp-config.php, which is why the database is also initialized with the correct URLs on startup. Furthermore, it is possible to keep the correct URLs even when creating a new pod/container.

**Comment by rafariossaa** [comment]
Hi @cangel111 ,
  Thanks for sharing this new approach.

**Comment by zzvara** [comment]
> Hi @PavelYarysh ,
> 
> I had the same problem. Here are the steps I took which appear to be working.
> 
> **Update these wp-config.php for the /blog path**
> 
> ```
> define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] . '/blog/');
> define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST'] . '/blog/');
> define('WP_CONTENT_URL', 'http://' . $_SERVER['HTTP_HOST'] . '/blog/wp-content/');
> ```
> 
> **In the helm chart's deployment.yaml, add this to the wordpress container**
> 
> ```yaml
> lifecycle:
>   postStart:
>     exec:
>       command: ["/bin/sh", "-c", "ln -s /opt/bitnami/wordpress /opt/bitnami/wordpress/blog"]
> ```
> 
> **Update wordpress ingress path** `- path: /blog`

How can I give you money?

**Comment by mhoskiso** [comment]
> How can I give you money?

@zzvara thanks , https://www.venmo.com/u/Michael-Hoskison

**Comment by pahla1** [comment]
@cangel111 No need to add the lifecycle hook to `deployment.yml`. Just add these sections to `values.yml` and everything works now:

```yaml
lifecycle hooks:
  postStart:
    exec:
      command: ["/bin/sh", "-c", "ln -s /opt/bitnami/wordpress /opt/bitnami/wordpress/blog"]
customPostInitScripts:
  change-wordpress-url.sh: |
    #!/bin/bash
    chmod +w /bitnami/wordpress/wp-config.php
    sed -i -r "s|_SERVER\['HTTP_HOST'\] \. '/'|_SERVER\['HTTP_HOST'\] \. '/blog/'|g" /bitnami/wordpress/wp-config.php
    chmod -w /bitnami/wordpress/wp-config.php



```

**Comment by Saigut** [comment]
```yaml
lifecycleHooks:
  postStart:
    exec:
      command: ["/bin/sh", "-c", "ln -s /opt/bitnami/wordpress /opt/bitnami/wordpress/blog"]

customPostInitScripts:
  change-wordpress-url.sh: |
    #!/bin/bash
    chmod +w /bitnami/wordpress/wp-config.php
    sed -i -r "s|_SERVER\['HTTP_HOST'\] \. '/'|_SERVER\['HTTP_HOST'\] \. '/blog/'|g" /bitnami/wordpress/wp-config.php
    chmod -w /bitnami/wordpress/wp-config.php
```
@pahla1 no effect
