### ISSUE TITLE
[bitnami/mongodb] Issues at deployment

### ISSUE THREAD

**Issue by islet5** [bitnami/charts#14686]
### Name and Version

bitnami/mongodb:10.12.5

### What steps will reproduce the bug?

1. deploy mongodb by using the helm chart:
`helm upgrade --install mongodb  -f values-eu.yaml ./mongodb/  -n mongo-system`
working as expect
<img width="828" alt="image" src="https://user-images.githubusercontent.com/9824473/215814164-b0dc128a-9c8b-461b-9172-891f732d4ccc.png">

2. EKS cluster node updated, then I found mongodb cluster is down
<img width="655" alt="image" src="https://user-images.githubusercontent.com/9824473/215814372-b6138eed-dda0-4af3-bc50-8e175af233b0.png">

3. tried to do helm uninstall and reinstall, pod is keeping crash and restart:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/9824473/215814692-1bdfd6ba-ca40-4a38-8770-1fb2f2b31eab.png">

**mongodb-0 log as below**:
```console
$ eks-eu-k8s -n mongo-system logs -f mongodb-0 -c mongodb
Advertised Hostname: mongodb-0.mongodb-headless.mongo-system.svc.cluster.local
Pod name matches initial primary pod name, configuring node as a primary
mongodb 16:04:55.94 
mongodb 16:04:55.94 Welcome to the Bitnami mongodb container
mongodb 16:04:55.94 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 16:04:55.94 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 16:04:55.94 
mongodb 16:04:55.94 INFO  ==> ** Starting MongoDB setup **
mongodb 16:04:55.95 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 16:04:55.96 INFO  ==> Initializing MongoDB...
mongodb 16:04:55.98 INFO  ==> Enabling authentication...
mongodb 16:04:55.98 INFO  ==> Deploying MongoDB with persisted data...
mongodb 16:04:55.98 INFO  ==> Writing keyfile for replica set authentication...
mongodb 16:04:56.00 INFO  ==> ** MongoDB setup finished! **

mongodb 16:04:56.01 INFO  ==> ** Starting MongoDB **

{"t":{"$date":"2023-01-31T16:04:56.026+00:00"},"s":"I",  "c":"CONTROL",  "id":20698,   "ctx":"main","msg":"***** SERVER RESTARTED *****"}
{"t":{"$date":"2023-01-31T16:04:56.028+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
{"t":{"$date":"2023-01-31T16:04:56.029+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2023-01-31T16:04:56.029+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
{"t":{"$date":"2023-01-31T16:04:56.029+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2023-01-31T16:04:56.046+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/bitnami/mongodb/data/db","architecture":"64-bit","host":"mongodb-0"}}
{"t":{"$date":"2023-01-31T16:04:56.046+00:00"},"s":"W",  "c":"CONTROL",  "id":20720,   "ctx":"initandlisten","msg":"Available memory is less than system memory","attr":{"availableMemSizeMB":1907,"systemMemSizeMB":15656}}
{"t":{"$date":"2023-01-31T16:04:56.046+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.5","gitVersion":"ff5cb77101b052fa02da43b8538093486cf9b3f7","openSSLVersion":"OpenSSL 1.1.1d  10 Sep 2019","modules":[],"allocator":"tcmalloc","environment":{"distmod":"debian10","distarch":"x86_64","target_arch":"x86_64"}}}}
{"t":{"$date":"2023-01-31T16:04:56.046+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"PRETTY_NAME=\"Debian GNU/Linux 10 (buster)\"","version":"Kernel 5.4.219-126.411.amzn2.x86_64"}}}
{"t":{"$date":"2023-01-31T16:04:56.046+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"config":"/opt/bitnami/mongodb/conf/mongodb.conf","net":{"bindIp":"*","ipv6":false,"port":27017,"unixDomainSocket":{"enabled":true,"pathPrefix":"/opt/bitnami/mongodb/tmp"}},"processManagement":{"fork":false,"pidFilePath":"/opt/bitnami/mongodb/tmp/mongodb.pid"},"replication":{"enableMajorityReadConcern":true,"replSetName":"rs0"},"security":{"authorization":"enabled","keyFile":"/opt/bitnami/mongodb/conf/keyfile"},"setParameter":{"enableLocalhostAuthBypass":"false"},"storage":{"dbPath":"/bitnami/mongodb/data/db","directoryPerDB":false,"journal":{"enabled":true}},"systemLog":{"destination":"file","logAppend":true,"logRotate":"reopen","path":"/opt/bitnami/mongodb/logs/mongodb.log","quiet":false,"verbosity":0}}}}
{"t":{"$date":"2023-01-31T16:04:56.054+00:00"},"s":"I",  "c":"STORAGE",  "id":22270,   "ctx":"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/bitnami/mongodb/data/db","storageEngine":"wiredTiger"}}
{"t":{"$date":"2023-01-31T16:04:56.059+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=441M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"CONTROL",  "id":23377,   "ctx":"SignalHandler","msg":"Received signal","attr":{"signal":15,"error":"Terminated"}}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"CONTROL",  "id":23378,   "ctx":"SignalHandler","msg":"Signal was sent by kill(2)","attr":{"pid":0,"uid":0}}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"CONTROL",  "id":23381,   "ctx":"SignalHandler","msg":"will terminate after current cmd ends"}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"REPL",     "id":4784900, "ctx":"SignalHandler","msg":"Stepping down the ReplicationCoordinator for shutdown","attr":{"waitTimeMillis":10000}}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"COMMAND",  "id":4784901, "ctx":"SignalHandler","msg":"Shutting down the MirrorMaestro"}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"SHARDING", "id":4784902, "ctx":"SignalHandler","msg":"Shutting down the WaitForMajorityService"}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"NETWORK",  "id":20562,   "ctx":"SignalHandler","msg":"Shutdown: going to close listening sockets"}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"NETWORK",  "id":4784905, "ctx":"SignalHandler","msg":"Shutting down the global connection pool"}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"STORAGE",  "id":4784906, "ctx":"SignalHandler","msg":"Shutting down the FlowControlTicketholder"}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"-",        "id":20520,   "ctx":"SignalHandler","msg":"Stopping further Flow Control ticket acquisitions."}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"REPL",     "id":4784907, "ctx":"SignalHandler","msg":"Shutting down the replica set node executor"}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"NETWORK",  "id":4784918, "ctx":"SignalHandler","msg":"Shutting down the ReplicaSetMonitor"}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"SHARDING", "id":4784921, "ctx":"SignalHandler","msg":"Shutting down the MigrationUtilExecutor"}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"CONTROL",  "id":4784925, "ctx":"SignalHandler","msg":"Shutting down free monitoring"}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"STORAGE",  "id":4784927, "ctx":"SignalHandler","msg":"Shutting down the HealthLog"}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"STORAGE",  "id":4784929, "ctx":"SignalHandler","msg":"Acquiring the global lock for shutdown"}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"-",        "id":4784931, "ctx":"SignalHandler","msg":"Dropping the scope cache for shutdown"}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"FTDC",     "id":4784926, "ctx":"SignalHandler","msg":"Shutting down full-time data capture"}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"CONTROL",  "id":20565,   "ctx":"SignalHandler","msg":"Now exiting"}
{"t":{"$date":"2023-01-31T16:06:16.309+00:00"},"s":"I",  "c":"CONTROL",  "id":23138,   "ctx":"SignalHandler","msg":"Shutting down","attr":{"exitCode":0}}`
```

**events**:
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/9824473/215815867-5db24aae-6255-4c7f-901e-82c211d9f1a1.png">

### Are you using any custom parameters or values?

[xiaowei_zhou@azure-k8s ~]$ cat  /opt/sensor-dashboard/eks-eu/dashboard/helm/mongodb/values-eu.yaml | grep -v "#"
```yaml
image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 4.4.5-debian-10-r0
  pullPolicy: IfNotPresent
  debug: false

clusterDomain: cluster.local
architecture: replicaset

useStatefulSet: true

auth:
  enabled: true
  rootPassword: "Vk8yNiBWrsDpj42T"
  replicaSetKey: ""

tls:
  enabled: false

  image:
    registry: docker.io
    repository: bitnami/nginx
    tag: 1.19.9-debian-10-r6
    pullPolicy: IfNotPresent

hostAliases: []

replicaSetName: rs0

replicaSetHostnames: true

enableIPv6: false

directoryPerDB: false

systemLogVerbosity: 0
disableSystemLog: false

disableJavascript: false

configuration: ""

initdbScripts: {}

extraFlags: []

extraEnvVars: []

annotations: {}

labels: {}

replicaCount: 2

strategyType: RollingUpdate

podManagementPolicy: OrderedReady

podAffinityPreset: ""

podAntiAffinityPreset: soft

nodeAffinityPreset:
  type: ""
  key: ""
  values: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: project
          operator: In
          values:
          - ods

nodeSelector: {}

tolerations:
- effect: NoSchedule
  key: project
  operator: Equal
  value: ods

podLabels: {}

podAnnotations: {}
podSecurityContext:
  enabled: true
  fsGroup: 1001
  sysctls: []

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true

resources:
  limits:
    cpu: 1
    memory: 2G
  requests: {}

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
startupProbe:
  enabled: false
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 30

customLivenessProbe: {}

customReadinessProbe: {}

customStartupProbe: {}

initContainers: {}

sidecars: {}

extraVolumeMounts: []
extraVolumes: []

pdb:
  create: false
  minAvailable: 1

persistence:
  enabled: true
  storageClass: "sensor-operator-1"
  accessModes:
    - ReadWriteOnce
  size: 100Gi
  annotations: {}
  mountPath: /bitnami/mongodb
  subPath: ""
  volumeClaimTemplates:
    selector:
    requests:

service:
  nameOverride: ""
  type: ClusterIP
  port: 27017
  portName: mongodb
  nodePort: ""
  externalIPs: []
  loadBalancerSourceRanges: []
  annotations: {}

externalAccess:
  enabled: false
  autoDiscovery:
    enabled: false
    image:
      registry: docker.io
      repository: bitnami/kubectl
      tag: 1.18.17-debian-10-r18
      pullPolicy: IfNotPresent
      pullSecrets: []
    resources:
      limits: {}
      requests: {}
  service:
    type: LoadBalancer
    port: 27017
    loadBalancerIPs: []
    loadBalancerSourceRanges: []
    nodePorts: []
    annotations: {}
  hidden:
    enabled: false
    service:
      type: LoadBalancer
      port: 27017
      loadBalancerIPs: []
      loadBalancerSourceRanges: []
      nodePorts: []
      annotations: {}

arbiter:
  enabled: true

  configuration: ""

  hostAliases: []

  extraFlags: []

  extraEnvVars: []

  annotations: {}

  labels: {}

  podAffinityPreset: ""

  podAntiAffinityPreset: soft

  nodeAffinityPreset:
    type: ""
    key: ""
    values: []

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: project
            operator: In
            values:
            - ods
  nodeSelector: {}

  tolerations:
  - effect: NoSchedule
    key: project
    operator: Equal
    value: ods

  podLabels: {}

  podAnnotations: {}

  podSecurityContext:
    enabled: true
    fsGroup: 1001
    sysctls: []

  containerSecurityContext:
    enabled: true
    runAsUser: 1001

  resources:
    limits: {}
    requests: {}

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

  customLivenessProbe: {}

  customReadinessProbe: {}

  initContainers: {}

  sidecars: {}

  extraVolumeMounts: []
  extraVolumes: []

  pdb:
    create: false
    minAvailable: 1

  service:
    nameOverride: ""

serviceAccount:
  create: true
  annotations: {}

rbac:
  create: false

podSecurityPolicy:
  create: false
  allowPrivilegeEscalation: false
  privileged: false
  spec: {}

volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: "10"
    pullPolicy: Always
    pullSecrets: []
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests: {}
  securityContext:
    runAsUser: 0

metrics:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/mongodb-exporter
    tag: 0.11.2-debian-10-r131
    pullPolicy: IfNotPresent

  extraFlags: ""

  extraUri: ""

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests: {}

  containerPort: 9216

  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "{{ .Values.metrics.service.port }}"
      prometheus.io/path: "/metrics"
    type: ClusterIP
    port: 9216

  livenessProbe:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  serviceMonitor:
    enabled: false

    interval: 30s
    additionalLabels: {}

  prometheusRule:
    enabled: false
    additionalLabels: {}

    rules: {}

hidden:
  enabled: false

  configuration: ""

  extraFlags: []

  extraEnvVars: []

  annotations: {}

  labels: {}

  replicaCount: 1

  strategyType: RollingUpdate

  podManagementPolicy: OrderedReady

  podAffinityPreset: ""

  podAntiAffinityPreset: soft

  nodeAffinityPreset:
    type: ""
    key: ""
    values: []

  affinity: {}

  nodeSelector: {}

  tolerations: []

  podLabels: {}

  podAnnotations: {}


  resources:
    limits: {}
    requests: {}

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

  customLivenessProbe: {}

  customReadinessProbe: {}

  initContainers: {}

  sidecars: {}

  extraVolumeMounts: []
  extraVolumes: []

  pdb:
    create: false
    minAvailable: 1

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: {}
    mountPath: /bitnami/mongodb
    subPath: ""
    volumeClaimTemplates:
      selector:
```
### What is the expected behavior?

mongodb pods in running state

### What do you see instead?

pods keeping restart and crash
