### ISSUE TITLE
[bitnami/external-dns] not working with istio 1.13.5 on aws EKS

### ISSUE THREAD

**Issue by ashuec90** [bitnami/charts#14680]
### Name and Version

bitnami/external-dns 6.12.2

### What steps will reproduce the bug?

1. Use AWS eks 1.21/1.22.
2. Use istio 1.13.5 version.
3. Use external-dns v0.13.1 (chart version v6.12.2)

All the services running properly. External dns is not updating the data in aws route53 an nothing is printing in external dns logs as below

```
{"level":"info","msg":"Instantiating new Kubernetes client","time":"2023-01-30T16:33:59Z"}
{"level":"info","msg":"Using inCluster-config based on serviceaccount-token","time":"2023-01-30T16:33:59Z"}
{"level":"info","msg":"Created Kubernetes client https://172.20.0.1:443","time":"2023-01-30T16:33:59Z"}
{"level":"info","msg":"Assuming role: arn:aws:iam::<account-id>:role/route-53-external-dns-role","time":"2023-01-30T16:34:01Z"}
````
previously we were using external dns v0.5.18 and this is working fine with this istio version.

### Are you using any custom parameters or values?

below are the container args we are passing

```yaml
      containers:
      - args:
        - --metrics-address=:7979
        - --log-level=debug
        - --log-format=json
        - --domain-filter=example.com
        - --policy=upsert-only
        - --provider=aws
        - --registry=txt
        - --txt-owner-id=ashuec90
        - --interval=30m
        - --source=service
        - --source=ingress
        - --source=istio-gateway
        - --source=istio-virtualservice
        - --aws-api-retries=5
        - --aws-zone-type=public
        - --aws-batch-change-size=1000
        - --aws-assume-role=arn:aws:iam::<account-id>:role/route-53-external-dns-role
```

### What is the expected behavior?

External dns should go ahead and create the route53 records in aws and the same should be printed in the external-dns logs.

### What do you see instead?

It is stuck and nothing is getting printed after the below logs given and records are not getting created as well.
```
{"level":"info","msg":"Instantiating new Kubernetes client","time":"2023-01-30T16:33:59Z"}
{"level":"info","msg":"Using inCluster-config based on serviceaccount-token","time":"2023-01-30T16:33:59Z"}
{"level":"info","msg":"Created Kubernetes client https://172.20.0.1:443","time":"2023-01-30T16:33:59Z"}
{"level":"info","msg":"Assuming role: arn:aws:iam::<account-id>:role/route-53-external-dns-role","time":"2023-01-30T16:34:01Z"}
```

### Additional information

We are using banzaicloud istio operator https://github.com/banzaicloud/istio-operator/
