### ISSUE TITLE
[bitnami/thanos] Use `tpl` in ingress templates

### ISSUE THREAD

**Issue by hauks96** [bitnami/charts#14703]
### Name and Version

bitnami/thanos 12.0.3

### What is the problem this feature will solve?

Where ingresses are defined, often the same domain is used for various deployments, only varying in the subdomain. For this, charts such as [kube-prometheus-stack](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack?modal=template&template=prometheus/ingress.yaml) and [grafana](https://artifacthub.io/packages/helm/grafana/grafana?modal=template&template=ingress.yaml) enable the use of the `tpl` function, so that users can nest `.Values` in the values.yaml file, such as the following in grafana:

```
# values.yaml
domain: "example.com"

# Modifying values of grafana subchart dependency
grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.{{ .Values.domain }}
```

This is not really a problem, but rather an improvement for the use of this helm chart as a dependency .

### What is the feature you are proposing to solve the problem?

It would be great if this was possible for ingress templates such as [query-frontend/ingress.yaml](https://artifacthub.io/packages/helm/bitnami/thanos?modal=template&template=query-frontend/ingress.yaml).
