### ISSUE TITLE
[bitnami/grafana-operator] grafana oidc, does it work?

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#14768]
### Name and Version

bitnami/grafana-operator:2.7.17

### What steps will reproduce the bug?

It doesn't seem like the oidc config is making it through to the installation.  Notes in values.yaml show how to configure oidc but using those doesn't seem to do anything. 

Not sure where the config should go but I suspect  grafana-config... don't see it there.

### Are you using any custom parameters or values?

I've used the oidc values provided in the commented out section in the values.yaml here at github, but updated of course with the actual values in my oidc keycloak configuration.

### What is the expected behavior?

Oidc configured

### What do you see instead?

As if the oidc values are not being used

```
[grafana-deployment-6b5bb4695b-tfdp7 grafana] logger=context userId=0 orgId=0 uname= t=2023-02-07T16:22:13.751380528Z level=error msg="Invalid username or password" error="user not found" remote_addr=192.168.1.1 traceID=
[grafana-deployment-6b5bb4695b-tfdp7 grafana] logger=context userId=0 orgId=0 uname= t=2023-02-07T16:22:13.751443021Z level=info msg="Request Completed" method=POST path=/login status=401 remote_addr=192.168.1.1 time_ms=1 duration=1.041239ms size=55 referer=https://grafana.k.home.net/login handler=/login
[grafana-deployment-6b5bb4695b-tfdp7 grafana] logger=ngalert.state.manager t=2023-02-07T16:22:15.359644644Z level=debug msg="Recording state cache metrics" now=2023-02-07T16:22:15.359634967Z
```

### Additional information

Is there another option that needs to be enabled maybe, before the oidc values are recognized and put to use?

**Comment by javsalgar** [comment]
Hi,

Could you share some example oidc values that trigger the issue? Did you check the rendered yaml?

**Comment by lknite** [comment]
if you look at the values.yaml here at bitnami github for the chart you will see a section with example oidc values you can test with.  They are commented out by default, just uncomment them.  I can copy my values here in a few hours, but really the sample should be enough for you to test with I would think.  Can search for "oidc" in the values.yaml to find the section.

It would help if you could tell me where in the rendered yaml I should look.  I mentioned before a config file where I thought the values should end up, and they were not there.

**Comment by lknite** [comment]
here's my values.yaml
```
grafana-operator:

  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: grafana.k.home.net
      tls: true
      annotations:
        cert-manager.io/issuer: "cluster-adcs-issuer"                   #use specific name of issuer
        cert-manager.io/issuer-kind: "ClusterAdcsIssuer"                #or ClusterAdcsIssuer
        cert-manager.io/issuer-group: "adcs.certmanager.csf.nokia.com"

    extraVolumeMounts:
    - mountPath: "/etc/ssl/certs"
      name: ca-bundle
    extraVolumes:
    - name: ca-bundle
      secret:
        secretName: ca-bundle

    config:
      log:
        level: "debug"
      security:
        auth:
          generic_oauth:
            enabled: true
            client_id: defaultwithtoken
            client_secret: <hidden>
            scopes: profile email openid offline_access
            auth_url: https://keycloak.k.home.net/auth/realms/home.net/protocol/openid-connect/auth
            token_url: https://keycloak.k.home.net/auth/realms/home.net/protocol/openid-connect/token
            api_url: https://keycloak.k.home.net/auth/realms/home.net/protocol/openid-connect/userinfo
            tls_skip_verify_insecure: true
            ## Automatic role handling with OIDC
            ##
            role_attribute_path: contains(groups[*], 'platform-readonly') && 'Viewer' || contains(groups[*], 'platform-admin') && 'Admin' || contains(groups[*], platform-emergency') && 'Admin' || contains(groups[*], 'customer-poweruser') && 'Admin' || contains(groups[*], 'customer-collaborator') && 'Editor' || contains(groups[*], 'customer-readonly') && 'Viewer'
            allowed_domains: home.net k.home.net
            allow_sign_up: true
```

**Comment by lknite** [comment]
I tried:
```
security:
  auth.generic_oauth:
```
before trying the incarnation you see in the yaml now

**Comment by lknite** [comment]
![image](https://user-images.githubusercontent.com/92187614/217312865-4258d5aa-0ef6-4197-b766-41bc74c9c30f.png)

**Comment by marcosbc** [comment]
Hi @lknite, it seems like the example is wrong. According to the [official documentation](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#auth), the `auth` section should be outside of `security`. [Here](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/#role-mapping) seems to be another guide for configuring generic OAuth2.

Unfortunately this is not something that we are able to test. However, if grafana-operator supports the feature, it should work with the chart if configured properly, since it is basically running the binary.

**Comment by lknite** [comment]
I tried out the helm chart provided by grafana, which worked, so am abandoning this one for now in favor of that one.  Closing as I won't be retesting this one any time soon, maybe next year.

**Comment by pat-s** [comment]
@lknite I suspect that because of the dot the config was not parsed correctly. The following works for `grafana-operator`:

```yml
grafana:
  config:
    "auth.generic_oauth":
      enabled: "true"
```
