### ISSUE TITLE
[bitnami/rabbitmq] memoryHighWatermark not working

### ISSUE THREAD

**Issue by younessof2m** [bitnami/charts#14793]
### Name and Version

bitnami/rabbitmq:11.9.0

### What steps will reproduce the bug?

Set memoryHighWatermark.enabled to true and upgrade chart. This is my chart
```
rabbitmq:
  enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx-01
    hostname: xxxx.xxxxx
    path: /
    pathType: Prefix

  auth:
    password: xxxxx
  memoryHighWatermark:
    enabled: true
    type: relative
    value: 0.9
  resources:
    limits:
      memory: 1Gi
  persistence:
    size: 2Gi
```

### What is the expected behavior?

Pod work

### What do you see instead?

The pod don't start and i get this error:
`Readiness probe failed: Error: unable to perform an operation on node 'rabbit@ofa-rabbitmq-0.ofa-rabbitmq-headless.rabbitmq.svc.cluster.local'. Please see diagnostics information and suggestions below. Most common reasons for this are: * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues) * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server) * Target node is not running In addition to the diagnostics info below: * See the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more * Consult server logs on node rabbit@ofa-rabbitmq-0.ofa-rabbitmq-headless.rabbitmq.svc.cluster.local * If target node is configured to use long node names, don't forget to use --longnames with CLI tools DIAGNOSTICS =========== attempted to contact: ['rabbit@ofa-rabbitmq-0.ofa-rabbitmq-headless.rabbitmq.svc.cluster.local'] rabbit@ofa-rabbitmq-0.ofa-rabbitmq-headless.rabbitmq.svc.cluster.local: * connected to epmd (port 4369) on ofa-rabbitmq-0.ofa-rabbitmq-headless.rabbitmq.svc.cluster.local * epmd reports: node 'rabbit' not running at all no other nodes on ofa-rabbitmq-0.ofa-rabbitmq-headless.rabbitmq.svc.cluster.local * suggestion: start the node Current node details: * node name: 'rabbitmqcli-241-rabbit@ofa-rabbitmq-0.ofa-rabbitmq-headless.rabbitmq.svc.cluster.local' * effective user's home directory: /opt/bitnami/rabbitmq/.rabbitmq *`

### Additional information

I use multiple value for watermak like absolute type with value but the only way to make the pod start is set the parameter memoryHighWatermark.enabled to false.
