### ISSUE TITLE
[bitnami/argo-workflows] helm chart containers are not staying on the same version

### ISSUE THREAD

**Issue by hnougher** [bitnami/charts#14805]
### Name and Version

bitnami/argo-workflows

### What steps will reproduce the bug?

1. Install the Helm chart

### What is the expected behavior?

All container components are of the same release version.
(argo-workflows-server, argo-workflows-controller, argo-workflows-exec)

### What do you see instead?

The Helm chart releases with the different containers being different versions.

eg: Helm chart 5.1.5 contains some parts in version 3.4.4 and others with 3.4.5
```yaml
    repository: bitnami/argo-workflow-controller
    tag: 3.4.4-scratch-r2
    repository: bitnami/argo-workflow-exec
    tag: 3.4.4-debian-11-r23
    repository: bitnami/argo-workflow-cli
    tag: 3.4.5-scratch-r0
```

### Additional information

Having different parts on different versions causes odd bugs that waste the time of everybody involved.
