### ISSUE TITLE
[bitnami/zookeeper] fails to start when readOnlyRootFilesystem: true

### ISSUE THREAD

**Issue by oren1zo** [bitnami/charts#14855]
### Name and Version

bitnami/zookeeper 8.1.2

### What steps will reproduce the bug?

enabling the security context and readOnlyRootFilesystem:true in the values.yaml 
installing the chart
zookeeper is not starting - fails to generate the zoo.cfg file

### Are you using any custom parameters or values?

in values.yaml
```
containerSecurityContext:
  enabled: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsUser: 1001
```

### What do you see instead?

The pod is not starting and the message in the log:
```
zookeeper 13:06:54.38 INFO  ==> No injected configuration file found, creating default config files...
cp: cannot create regular file '/opt/bitnami/zookeeper/conf/zoo.cfg': Read-only file system
Stream closed EOF for data/platform-nap-zookeeper-0 (zookeeper)  
```
### Additional information

In addition to setting the readOnlyRootFilesystem to true are other configurations needed in order to change the location of the zoo.cfg file?
