### ISSUE TITLE
Joomla! + MariaDB Galera - not working

### ISSUE THREAD

**Issue by clickersmudge** [bitnami/charts#14856]
### Name and Version

bitnami/joomla 13.3.14

### What steps will reproduce the bug?

Hi,
We have installed  MariaDB Galera on the cluster.

![Zrzut ekranu z 2023-02-13 14-30-01](https://user-images.githubusercontent.com/113194014/218482540-ae35416f-acca-43b3-aac6-9a92e7c0586d.png)

Joomla! helm charts and used an external database.

Helm
```yaml
mariadb:
  ## @param mariadb.enabled Whether to deploy a mariadb server to satisfy the applications database requirements. To use an external database set this to false and configure the externalDatabase parameters
  ##
  enabled: false

externalDatabase:
  ## @param externalDatabase.existingSecret Name of the database existing Secret Object
  ## NOTE: When it's set, the `externalDatabase.password` parameter is ignored
  ##
  existingSecret: ""
  ## @param externalDatabase.host Host of the existing database
  ##
  host: "mariadb-galera.mariadb-galera.svc.cluster.local"
  ## @param externalDatabase.port Port of the existing database
  ##
  port: 3306
  ## @param externalDatabase.user Existing username in the external db
  ##
  user: user
  ## @param externalDatabase.password Password for the above username
  ##
  password: "password"
  ## @param externalDatabase.database Name of the existing database
  ##
  database: my_database
```

It appears that tables in the database are being created.
![Zrzut ekranu z 2023-02-13 14-29-24](https://user-images.githubusercontent.com/113194014/218483645-c5004077-4a52-4f6e-8086-e4240b0cc8a6.png)

Unfortunately, the container does not start.
Logs:
![Zrzut ekranu z 2023-02-13 14-29-39](https://user-images.githubusercontent.com/113194014/218483953-1106f462-c02e-401f-bb97-fa0f55776cd3.png)

### What do you see instead?

```console
$ kubectl logs -n joomla11               joomla11-7d89c8c7bd-cxqft 
Defaulted container "joomla" out of: joomla, k8tz (init)
joomla 15:23:52.19 
joomla 15:23:52.19 Welcome to the Bitnami joomla container
joomla 15:23:52.19 Subscribe to project updates by watching https://github.com/bitnami/containers
joomla 15:23:52.19 Submit issues and feature requests at https://github.com/bitnami/containers/issues
joomla 15:23:52.19 
joomla 15:23:52.20 INFO  ==> ** Starting Joomla! setup **
realpath: /bitnami/apache/conf: No such file or directory
joomla 15:23:52.23 INFO  ==> Configuring the HTTP port
joomla 15:23:52.24 INFO  ==> Configuring the HTTPS port
joomla 15:23:52.25 INFO  ==> Configuring Apache ServerTokens directive
joomla 15:23:52.27 INFO  ==> Configuring PHP options
joomla 15:23:52.27 INFO  ==> Setting PHP expose_php option
joomla 15:23:52.30 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
joomla 15:23:52.38 INFO  ==> Configuring file permissions for Joomla!
joomla 15:23:52.39 INFO  ==> Configuring Joomla! with settings provided via environment variables
joomla 15:23:52.39 INFO  ==> Setting site name
joomla 15:23:52.41 INFO  ==> Setting database host
joomla 15:23:52.42 INFO  ==> Setting database name
joomla 15:23:52.43 INFO  ==> Setting database user
joomla 15:23:52.44 INFO  ==> Setting database password
joomla 15:23:52.45 INFO  ==> Setting salt
joomla 15:23:52.46 INFO  ==> Trying to connect to the database server
joomla 15:23:52.50 INFO  ==> Executing initialization SQL commands
```
