### ISSUE TITLE
sonarqube/logs/sonar.log: no such file or directory

### ISSUE THREAD

**Issue by satya1302** [bitnami/charts#14892]
### Name and Version

bitnami/sonarqube:2.1.0

### What steps will reproduce the bug?

Previously I am using sonarqube helm chart 2.0.1 which is running fine. I would like to increase max http post size to 32 MB. with the following values
```yaml
jvmOpts:
  SONARQUBE_WEB_JVM_OPTS: "-Xmx512m -XX:MaxMetaspaceSize=256m -Dsonar.web.port=9000 -Dsonar.web.javaAdditionalOpts=-Dserver.max-http-post-size=33554432"
```
but I got some error with unable to restart the elasticsearch container but I browsed the web and found that I need to upgrade the helm chart to the latest version 2.1.0 which solved that issue but a new issue has come up 
![Screenshot 2023-02-15 at 14 33 11](https://user-images.githubusercontent.com/87824006/219041574-ed255313-3fa2-4797-bbe8-200cb445dbb1.png)

but I have that file(sonar.log) in my container, I have also checked the ReadWrite permissions 
![Screenshot 2023-02-15 at 14 28 32](https://user-images.githubusercontent.com/87824006/219042761-9fd8db6c-700d-4135-9e2a-da27d75fbe47.png)
. I have also checked the memory requests which are given as 2GiB with cpu 100MiB. 
I found this issue which is very similar to my issue [https://github.com/bitnami/charts/issues/8030](https://github.com/bitnami/charts/issues/8030) 

can someone please help resolve this issue?

### What do you see instead?

I should see the sonarqube running successfully instead sonarqube container running in crashloopbackoff status

**Comment by carrodher** [comment]
It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by diegoluisi** [comment]
Same problem.

`
sonarqube 11:32:07.26
sonarqube 11:32:07.26 Welcome to the Bitnami sonarqube container
sonarqube 11:32:07.26 Subscribe to project updates by watching https://github.com/bitnami/containers
sonarqube 11:32:07.26 Submit issues and feature requests at https://github.com/bitnami/containers/issues
sonarqube 11:32:07.27
sonarqube 11:32:07.29 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
sonarqube 11:32:07.41 INFO  ==> Creating SonarQube configuration
sonarqube 11:32:07.61 INFO  ==> Trying to connect to the database server
sonarqube 11:32:07.69 INFO  ==> Ensuring SonarQube directories exist
sonarqube 11:32:07.76 INFO  ==> Starting SonarQube in background
sonarqube 11:32:07.91 INFO  ==> Waiting for SonarQube to start...
grep: /opt/bitnami/sonarqube/logs/sonar.log: No such file or directory
grep: /opt/bitnami/sonarqube/logs/sonar.log: No such file or directory
grep: /opt/bitnami/sonarqube/logs/sonar.log: No such file or directory
`

**Comment by danscarf** [comment]
Same problem for me:
<img width="1059" alt="image" src="https://github.com/bitnami/charts/assets/8267608/bfc34b17-fd69-4eaa-aff5-a19bba6ab15c">

**Comment by maytan-cogo** [comment]
I'm facing the same issue. Have tried multiple chart versions(recent) and both packaged postgres and external. The log file exists in all cases.

```
sonarqube 05:24:36.40 
sonarqube 05:24:36.40 Welcome to the Bitnami sonarqube container
sonarqube 05:24:36.40 Subscribe to project updates by watching https://github.com/bitnami/containers
sonarqube 05:24:36.40 Submit issues and feature requests at https://github.com/bitnami/containers/issues
sonarqube 05:24:36.40 
sonarqube 05:24:36.41 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
sonarqube 05:24:36.44 INFO  ==> Creating SonarQube configuration
sonarqube 05:24:36.47 INFO  ==> Trying to connect to the database server
sonarqube 05:24:36.50 INFO  ==> Ensuring SonarQube directories exist
sonarqube 05:24:36.56 INFO  ==> Starting SonarQube in background
sonarqube 05:24:36.59 INFO  ==> Waiting for SonarQube to start...
grep: /opt/bitnami/sonarqube/logs/sonar.log: No such file or directory
grep: /opt/bitnami/sonarqube/logs/sonar.log: No such file or directory
```

Here's my postgres and sonarqube chart values:

*bitnami/postgres (version: 12.5.7)*
```
global:
  imageRegistry: public.ecr.aws
architecture: standalone
auth:
  database: sonarqube
  username: sonarqube
  existingSecret: some-credentials
  secretKeys:
    adminPasswordKey: password
    userPasswordKey: password
primary:
  resources:
    limits:
      memory: 256Mi
      cpu: 250m
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

*bitnami/sonarqube (version: 3.2.3)*
```
global:
  imageRegistry: public.ecr.aws
existingSecret: some-credentials
sonarqubeUsername: sonarqube
replicaCount: 1
minHeapSize: 1024m
maxHeapSize: 2048m
resources:
  limits:
    memory: 2.5Gi
    cpu: 500m
podAntiAffinityPreset: hard
service:
  type: NodePort
persistence:
  enabled: true
metrics:
  jmx:
    enabled: true
  serviceMonitor:
    enabled: true
postgresql:
  enabled: false
externalDatabase:
  host: postgresql
  user: sonarqube
  existingSecret: some-credentials
```
