### ISSUE TITLE
[bitnami/external-dns] Allow env variables to authenticate in AWS.

### ISSUE THREAD

**Issue by EnriqueLop** [bitnami/charts#14916]
### Name and Version

bitnami/external-dns 6.13.2

### What is the problem this feature will solve?

When using AWS provider there are two options: 
- Hardcode credentials on the helm chart definition
- Use a secret that holds .aws/credentials in aws credentials file format.

```
aws:
  credentials:
   ## Hardcoded credentials
    secretKey: ""
    accessKey: ""
    ## Secret that houlds credentials file.
    secretName: ""
```

I you use secretName the secret needs to use the following format:
```
[default]
aws_access_key_id = 
aws_secret_access_key = 
```

I find this two methods too static. I think chart should provide a method to define AWS credentials thought a secret that holds credentials in the key-value format.
 
bitnami/etcd example:
```
auth:
  ## Role-based access control parameters
  ## ref: https://etcd.io/docs/current/op-guide/authentication/
  ##
  rbac:
    ## Secret that holds the credentials
    existingSecret: ""
    ## Key that holds the secret
    existingSecretPasswordKey: ""
```

Cert-manager issuer example:
```
accessKeyIDSecretRef:
  name: iam-cert-manager-dns
  key: AWS_ACCESS_KEY_ID
```

---------------------

You can bypass this problem by adding `extraEnvVarsSecret` and adding any value to secretKey and accessKay fields (to skip aws credentials validations in helm templating):
```
extraEnvVarsSecret: iam-credentials
aws:
  credentials:
    secretKey: "foo"
    accessKey: "bar"
    secretName: ""
```
Obviously this solution is really bad.

### What is the feature you are proposing to solve the problem?

My proposal is to add a new field that manages AWS credentials using secrets that holds credentials in a key-value format. By doing that credentials are provided the same way as env variables in a deployment when using [valueFrom](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data) field. 

### What alternatives have you considered?

Example:

```
aws:
  credentials:
    ##
    ##All fields
    ##

    ##
    ##New fields
    accessKeyIDSecretRef:
      name: ${NAME OF THE SECRET}
      key: ${KEY}
    secretAccessKeySecretRef:
      name: ${NAME OF THE SECRET}
      key: ${KEY}
    ##

```

Changes to be done on the chart: 
- Modify values.yaml with new configuration.
- Do not create aws-credentials volume when secretRefs are defined.
- Define AWS_ACCESS_KEY_ID and AWS_SECRET_KEY env variables when secretRefs are defined.
