### ISSUE TITLE
PASSWORDS ERROR: The secret "postgresql-creds" does not contain the key "postgres-password"

### ISSUE THREAD

**Issue by jimsnab** [bitnami/charts#14923]
### Name and Version

bitnami/postgresql 12.2.0

### What steps will reproduce the bug?

1. Start with a `values.yaml` that has a section like:

```yaml
auth:
  username: ${postgresql_user_name}
  existingSecret: ${postgresql_creds_name}
  secretKeys:
    adminPasswordKey: admin-password
    userPasswordKey: user-password
```

2. Deploy

### What is the expected behavior?

Auth secret with non-default key names used successfully

### What do you see instead?

`PASSWORDS ERROR: The secret "postgresql-creds" does not contain the key "postgres-password"`

### Additional information

`postgres-password` is a `values.yaml` default.
