### ISSUE TITLE
[bitnami/redis-cluster] example from node affinity

### ISSUE THREAD

**Issue by justknife** [bitnami/charts#14942]
### Name and Version

bitmani/redis-cluster

### What steps will reproduce the bug?

Good afternoon. I'm setting your chart in a closed loop, and I ran into a misunderstanding of how to correctly specify the label for the node so that the nodes would fall on it if I use the standard cluster configuration. i.e. by your variables, it is podAffiniityPreset .../etc

### What do you see instead?

pod in non pending status

**Comment by justknife** [comment]
version charts current lts

**Comment by justknife** [comment]
i trying :
kubectl label mynode redis.affinity=soft, but status pods:pending

**Comment by justknife** [comment]
how to try: 
i disable in values.yaml PVS

**Comment by justknife** [comment]
installing failed on step "setting redis config file" script /opt/bitnami/scripts/redis-cluster/setup.sh

**Comment by javsalgar** [comment]
Hi,

Could you add more details on your setup and what you want to achieve? This should be more helpful to understand the issue.

**Comment by justknife** [comment]
i trying install yours chart without internet connection.
My os: centos-7
My Kubernetes version: 1.21.5
Helm chart version: 8.3.7
My config: 
change it:
```
global:
  imageRegistry: "10.10.10.10/24"
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: "local-storage"
  redis:
    password: "my-password"
```
    
i add label from node :
 redis.affinity=soft
 
 but redis not run
