### ISSUE TITLE
[bitnami/postgresql] Update to 12.2.0 breaks when auth.existingSecret is set

### ISSUE THREAD

**Issue by ekeih** [bitnami/charts#14961]
### Name and Version

bitnami/postgresql 12.2.0

### What steps will reproduce the bug?

1. Create secret `postgresql-auth` with `password` and `postgres-password` values.
2. Install chart version 12.1.15 with the values below.
3. Try upgrading to chart version 12.2.0

### Are you using any custom parameters or values?

```
serviceAccount:
  create: true
rbac:
  create: true
auth:
  existingSecret: postgresql-auth
  username: metrics-dummy
  database: metrics-dummy
primary:
  persistence:
    size: 10Gi
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

### What is the expected behavior?

Chart upgrade from `12.1.15` to `12.2.0` should work.

### What do you see instead?

```
  PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                   Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                   Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases
      'global.postgresql.auth.postgresPassword' must not be empty, please add '--set global.postgresql.auth.postgresPassword=$POSTGRES_PASSWORD' to the command. To get the current value:
          export POSTGRES_PASSWORD=$(kubectl get secret --namespace "postgresql" postgresql-auth -o jsonpath="{.data.postgres-password}" | base64 -d)
```

### Additional information

The `postgresql-auth` secret contains two keys: `password` and `postgres-password`.

This has worked during previous updates without any issues. As far as I can see in the git history this breaking change is not intentional.

As a test I even set `global.postgresql.auth.postgresPassword` in the values, but that also failed.

Thanks for providing all the charts and thanks for looking into this! Let me know if you need any further information or if I can help testing something.
