### ISSUE TITLE
[bitnami/keycloak] Liquibase Error while DB migration from keycloak V14 to V20

### ISSUE THREAD

**Issue by happy0088** [bitnami/charts#15052]
### Name and Version

bitnami/keycloak appVersion: 20.0.3

### What steps will reproduce the bug?

Hi , i am upgrading from V14 to V20 .

while running the database migration liquibase throws error :

`ERROR: relation \"user_role\" already exists`
I am using external postgres as a database connection with teh below config

```
externalDatabase:
  host: "apostgresHost"
  port: 5432
  user: postgres
  database: myDB
  password: "myPassword"
  existingSecret: ""
  existingSecretPasswordKey: ""
```
i have tried deleting the pod , restarting container but it still fails with same error .

Do we need to set any flag in db config to upsert if relation already exists ?

### Are you using any custom parameters or values?

yes , i am using custom external postgres database.

### What is the expected behavior?

Should complete the migration without errors 

### What do you see instead?

{"timestamp":"2023-02-18T08:56:51.55Z","sequence":8437,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler","level":"ERROR","message":"ERROR: Migration failed for change set META-INF/jpa-changelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOAK-5461::sthorger@redhat.com:\n     Reason: liquibase.exception.DatabaseException: ERROR: relation \"user_role_\" already exists [Failed SQL: (0) CREATE TABLE public.USER_ROLE (ROLE_ID VARCHAR(255) NOT NULL, USER_ID VARCHAR(36) NOT NULL)]","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"keycloak-release-0","processName":"QuarkusEntryPoint","processId":1}
