### ISSUE TITLE
[bitnami/mastodon] TLS security for Elasticsearch is not functional via the Mastodon chart

### ISSUE THREAD

**Issue by ajguyot** [bitnami/charts#15087]
### Name and Version

bitnami/mastodon 1.0.3

### What steps will reproduce the bug?

- Enable security settings for Elasticsearch either via the built-in deployment or an external Elasticsearch deployment.
- Deploy the Mastodon Helm chart. The init script will fail on the "Waiting for Elasticsearch to be ready" step.

### Are you using any custom parameters or values?

I tried with both the built-in and an external Elasticsearch configuration (in separate deploys, of course).

External using the recommended approach of including `https://` in the hostname (see my additional info section below):
```
externalElasticsearch:
  host: https://elasticsearch
  port: 9200
  existingSecret: elasticsearch-secret
  existingSecretPasswordKey: elasticsearch-password
```

External with no protocol specified in the hostname:
```
externalElasticsearch:
  host: elasticsearch
  port: 9200
  existingSecret: elasticsearch-secret
  existingSecretPasswordKey: elasticsearch-password
```

Or built-in:
```
elasticsearch:
  enabled: true

  sysctlImage:
    enabled: true

  security:
    enabled: true
    tls:
      restEncryption: true
      autoGenerated: true

  master:
    replicaCount: 1

  coordinating:
    replicaCount: 1

  data:
    replicaCount: 1

  ingest:
    replicaCount: 1

  service:
    ports:
      restAPI: 9200
```

### What is the expected behavior?

The init script should be able to connect to the Elasticsearch instance over TLS using password authentication.

### What do you see instead?

The init script is unable to connect to the Elasticsearch instance.

### Additional information

I believe the exact cause of this issue is that the Bitnami Mastodon init script is hard-coded to connect to Elasticsearch using `http://`. Instead, it should connect using `https://` whenever a password is utilized.

Elasticsearch cannot be deployed (anymore? it's possible that this was not always the case) with password authentication unless TLS is enabled, so it should be safe to assume that `https://` is being used. However, a better alternative would probably be to not specify a protocol at all and just let the user optionally include one in their Elasticsearch `host` config value. Using the `ES_HOST` environment variable is the current recommended way to enable TLS support for Mastodon instances connecting to Elasticsearch, as described in this issue: https://github.com/mastodon/mastodon/issues/19402

I have a PR out for this chart (#15076) which adds features and fixes a number of other minor issues, but I was not able to fix this Elasticsearch problem because I believe it will require changes to both the chart _and_ the actual Mastodon image to tweak the init script itself.
