### ISSUE TITLE
[bitnami/postgresql] global.postgres.auth assumed to exist

### ISSUE THREAD

**Issue by tshirtman** [bitnami/charts#15084]
### Name and Version

bitnami/postgresql/12.1.13

### What steps will reproduce the bug?

When trying to deploy postgresql as a dependency of a chart, with another dependency *also* having a *different* postgres dependency, i do not want to use `global.postgres.auth`, but set `auth:{...}` in each specific values, definition for the subchart, but currently, the chart forces me to define global.postgres.auth, only to leave it empty (`{}`), because the logic at https://github.com/bitnami/charts/blob/main/bitnami/postgresql/templates/_helpers.tpl#L71 assumes the object to exist.

### What is the expected behavior?

if `global.postgres` or `global.postgres.auth` is undefined, it should be ignored and look for `.Values.auth`.

### What do you see instead?

deployment fails
```
Error: UPGRADE FAILED: template: xxx/charts/postgresql/templates/statefulset.yaml:205:24: executing "xxx/charts/postgresql/templates/statefulset.yaml" at <include "postgresql.username" .>: error calling include: template: xxx/charts/postgresql/templates/_helpers.tpl:71:14: executing "postgresql.username" at <.Values.global.postgresql.auth.username>: nil pointer evaluating interface {}.username
```

unless i add
```
globals:
    postgresql:
        auth: {}
```
to my values.yaml.

**Comment by rafariossaa** [comment]
Hi,
 Could you put an example of how you are setting the usernames in both subcharts ?
 You could set something like the following in your `Chart.yaml`:
```
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.x.x
    alias: pg1

  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.x.x
    alias: pg2
```
and then set the passwords to each of the postgresql in  your `values.yaml`:
```
pg1:
  auth:
    username: test1
    password: test1pwd

pg2:
  auth:
    username: test2
    password: test2pwd
```
I am not sure if that would work for your use case.
