### ISSUE TITLE
[bitnami/argo-workflows] server.auth.sso.scopes and server.auth.sso.rbac should be under server.auth.sso.config

### ISSUE THREAD

**Issue by bh-tt** [bitnami/charts#15085]
### Name and Version

bitnami/argo-workflows:5.1.9

### What steps will reproduce the bug?

According to the readme one should set the properties `server.auth.sso.scopes` and `server.auth.sso.rbac.enabled` in order to use SSO RBAC. The chart however only renders `server.auth.sso.config` into the `argo-workflows-controller` configmap, so in order to use them these values should be under `server.auth.sso.config`.

See https://github.com/bitnami/charts/blob/6bc7961f5027bb17a949c69c0e16bdd686a13745/bitnami/argo-workflows/values.yaml#L678.

### Are you using any custom parameters or values?

``` 
     server:
        auth:
          mode: sso
          sso:
            enabled: true
            config:
              issuer: <issuer>
              clientId:
                name: argowf-sso
                key: clientid
              clientSecret:
                name: argowf-sso
                key: clientsecret
              redirectUrl: "https://{{ externalhost }}/oauth2/callback"
            scopes:
              - openid
              - groups
            rbac:
              enabled: true
```

### What is the expected behavior?

I expected the scopes and rbac configuration to be used by argo-workflows-server.

### What do you see instead?

The values were not added to the configmap.

### Additional information

I recommend updating the README instead of changing the chart rendering, as that will not create a breaking change.
