### ISSUE TITLE
[bitnami/mongodb] RSM received failed isMaster, Host failed in replica set

### ISSUE THREAD

**Issue by USB-05** [bitnami/charts#15116]
### Name and Version

bitnami/mongodb:4.4.15-debian-10-r8

### What steps will reproduce the bug?

1. helm repo add sorry-cypress https://sorry-cypress.github.io/charts
2. helm install sorry-cypress sorry-cypress/sorry-cypress --namespace sorry-cypress
3. Delete the pods created by mongodb statefulset.

### Are you using any custom parameters or values?

I am using following values provided by sorry-cypress values.yaml
```
mongodb:
  # You need to ensure that director.environmentVariables.executionDriver is set to "../execution/mongo/driver" if you want the director to use mongodb.
  mongoConnectionString: ""

  # One of the following two options must be enabled in order to securely use connection strings
  # that may contain sensitive information. Use either enableSecret or enableCustomSecret, not both.
  mongoSecretConnectionString:
    enableSecret: false
    enableCustomSecret: false

  # One of the following two options must be enabled in order for the Sorry Cypress API to work.
  # Set this to "true" if you wish to use your own external mongodb.
  external_db:
    enabled: false
    mongoServer: ""

  # Set this to "true" if you want this chart to deploy mongodb for you.
  internal_db:
    enabled: true

  mongoDatabase: "sorry-cypress"

  certificate:
    enabled: false
    name: "db-cert"
    configMapName: "sorry-cypress-db-cert"

  # If enabled, you can use any values from the mongodb helm chart: https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml
  # Below are the bare minimim to get you started.
  architecture: replicaset
  auth:
    enabled: false

  resources:
    limits:
      cpu: 600m
      memory: 2Gi
    requests:
      cpu: 600m
      memory: 2Gi

  persistence:
    enabled: true
    size: 30Gi

  externalAccess:
    enabled: true
    service:
      type: ClusterIP
```

### What is the expected behavior?

After crashing/deletion of mongo pods, the pods should come up again successfully.

### What do you see instead?

"ctx":"ReplicaSetMonitor-TaskExecutor","msg":"RSM received failed isMaster","attr":{"host":"10.40.2.2:27017","error":"NetworkInterfaceExceededTimeLimit: Couldn't get a connection within the time limit of 500ms","replicaSet":"rs0","isMasterReply":"{}"}}

Here it is trying to connect to host "10.40.2.2:27017", which no longer exists in the cluster as that pod got crashed.

### Additional information

Here it is trying to connect to host "10.40.2.2:27017", which no longer exists in the cluster as that pod got crashed. Scripts are not looking for the new pod IP instead it is looking for old IP which no longer exists.
I have checked my "rs.conf()" and it contains IPs in the members host name and not cluster service names.
i had to reconfigure the replicatset config manually to point host to DNS instead of IP of PODS to solve this error.
