### ISSUE TITLE
[bitnami/kube-prometheus] validate Prometheus flags: found that TSDB Max time is 1d and Min time is 2h. Compaction needs to be disabled

### ISSUE THREAD

**Issue by SrinivReddy** [bitnami/charts#15129]
### Name and Version

bitnami/kube-prometheus

### What steps will reproduce the bug?

I tried to configure the kube-promethues  with thanos sidecar, But  I am getting  
`validate Prometheus flags: found that TSDB Max time is 1d and Min time is 2h. Compaction needs to be disabled` error

I believe we need to pass below arguments to thanos but unable to find related filed in values.yaml file. Can any one idea on this issue, I am using latest chart.

```
--storage.tsdb.min-block-duration=2h
--storage.tsdb.max-block-duration=2h
```

### Are you using any custom parameters or values?
```
prometheus:
  thanos:
    disableCompaction: true
    create: true
    objectStorageConfig:
      secretKey: thanos.yaml
      secretName: thanos-objstore-config
```

### What do you see instead?

```
level=info ts=2023-02-23T10:15:12.328093336Z caller=options.go:26 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2023-02-23T10:15:12.328686218Z caller=factory.go:52 msg="loading bucket configuration"
level=info ts=2023-02-23T10:15:12.330136323Z caller=sidecar.go:362 msg="starting sidecar"
level=info ts=2023-02-23T10:15:12.330339871Z caller=intrumentation.go:75 msg="changing probe status" status=healthy
level=info ts=2023-02-23T10:15:12.330499765Z caller=http.go:73 service=http/server component=sidecar msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2023-02-23T10:15:12.331661159Z caller=tls_config.go:232 service=http/server component=sidecar msg="Listening on" address=[::]:10902
level=info ts=2023-02-23T10:15:12.331863348Z caller=tls_config.go:235 service=http/server component=sidecar msg="TLS is disabled." http2=false address=[::]:10902
level=info ts=2023-02-23T10:15:12.33204169Z caller=intrumentation.go:56 msg="changing probe status" status=ready
level=info ts=2023-02-23T10:15:12.332127669Z caller=grpc.go:131 service=gRPC/server component=sidecar msg="listening for serving gRPC" address=0.0.0.0:10901
level=info ts=2023-02-23T10:15:12.332221513Z caller=reloader.go:199 component=reloader msg="nothing to be watched"
level=warn ts=2023-02-23T10:15:12.334070784Z caller=intrumentation.go:67 msg="changing probe status" status=not-ready reason="validate Prometheus flags: found that TSDB Max time is 1d and Min time is 2h. Compaction needs to be disabled (storage.tsdb.min-block-duration = storage.tsdb.max-block-duration)"
level=info ts=2023-02-23T10:15:12.334212661Z caller=http.go:91 service=http/server component=sidecar msg="internal server is shutting down" err="validate Prometheus flags: found that TSDB Max time is 1d and Min time is 2h. Compaction needs to be disabled (storage.tsdb.min-block-duration = storage.tsdb.max-block-duration)"
level=info ts=2023-02-23T10:15:12.334351094Z caller=http.go:110 service=http/server component=sidecar msg="internal server is shutdown gracefully" err="validate Prometheus flags: found that TSDB Max time is 1d and Min time is 2h. Compaction needs to be disabled (storage.tsdb.min-block-duration = storage.tsdb.max-block-duration)"
level=info ts=2023-02-23T10:15:12.33441791Z caller=intrumentation.go:81 msg="changing probe status" status=not-healthy reason="validate Prometheus flags: found that TSDB Max time is 1d and Min time is 2h. Compaction needs to be disabled (storage.tsdb.min-block-duration = storage.tsdb.max-block-duration)"
level=info ts=2023-02-23T10:15:12.334544295Z caller=grpc.go:138 service=gRPC/server component=sidecar msg="internal server is shutting down" err="validate Prometheus flags: found that TSDB Max time is 1d and Min time is 2h. Compaction needs to be disabled (storage.tsdb.min-block-duration = storage.tsdb.max-block-duration)"
level=info ts=2023-02-23T10:15:12.334581509Z caller=grpc.go:151 service=gRPC/server component=sidecar msg="gracefully stopping internal server"
level=info ts=2023-02-23T10:15:12.334624748Z caller=grpc.go:164 service=gRPC/server component=sidecar msg="internal server is shutdown gracefully" err="validate Prometheus flags: found that TSDB Max time is 1d and Min time is 2h. Compaction needs to be disabled (storage.tsdb.min-block-duration = storage.tsdb.max-block-duration)"
level=error ts=2023-02-23T10:15:12.334829716Z caller=main.go:161 err="found that TSDB Max time is 1d and Min time is 2h. Compaction needs to be disabled (storage.tsdb.min-block-duration = storage.tsdb.max-block-duration)\nmain.validatePrometheus\n\t/app/cmd/thanos/sidecar.go:390\nmain.runSidecar.func3\n\t/app/cmd/thanos/sidecar.go:164\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594\nvalidate Prometheus flags\nmain.runSidecar.func3\n\t/app/cmd/thanos/sidecar.go:165\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594\nsidecar command failed\nmain.main\n\t/app/cmd/thanos/main.go:161\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594"
```

**Comment by nitramrc** [comment]
just set disableCompaction: true (line 943)

**Comment by SrinivReddy** [comment]
Thanks for suggestion, I was misplaced disableCompaction variable in my values.yaml file, I just corrected it and I don't see that error, But after that I am seeing below error.

`level=warn ts=2023-02-24T07:47:50.996287654Z caller=shipper.go:239 msg="reading meta file failed, will override it" err="failed to read /prometheus/thanos.shipper.json: open /prometheus/thanos.shipper.json: no such file or directory"
`

**Comment by javsalgar** [comment]
Hi,

Could you share the thanos,yaml configuration for us to reproduce the issue?

**Comment by SrinivReddy** [comment]
Hi @javsalgar 
Thanks for responding on this, I am using below configuration to deploy  kube-prometheus stack with thanos-sidecar enable

`prometheus:
  disableCompaction: true
  thanos:
    create: true
    objectStorageConfig:
      secretKey: thanos.yaml
      secretName: thanos-objstore-config
`

**Comment by hoanbc** [comment]
> Thanks for suggestion, I was misplaced disableCompaction variable in my values.yaml file, I just corrected it and I don't see that error, But after that I am seeing below error.
> 
> `level=warn ts=2023-02-24T07:47:50.996287654Z caller=shipper.go:239 msg="reading meta file failed, will override it" err="failed to read /prometheus/thanos.shipper.json: open /prometheus/thanos.shipper.json: no such file or directory" `

same warning, my helm file working on-premise but today i do it in aws, it show me as below.
![image](https://user-images.githubusercontent.com/26288807/221251449-c1808f65-c3ee-4e52-a805-01c5cdd54c90.png)

**Comment by javsalgar** [comment]
Hi,

My question is, did you create a thanos.yaml file or it was created automatically?

**Comment by nitramrc** [comment]
> > Thanks for suggestion, I was misplaced disableCompaction variable in my values.yaml file, I just corrected it and I don't see that error, But after that I am seeing below error.
> > `level=warn ts=2023-02-24T07:47:50.996287654Z caller=shipper.go:239 msg="reading meta file failed, will override it" err="failed to read /prometheus/thanos.shipper.json: open /prometheus/thanos.shipper.json: no such file or directory" `
> 
> same warning, my helm file working on-premise but today i deploy it in aws, it show me as below. ![image](https://user-images.githubusercontent.com/26288807/221251449-c1808f65-c3ee-4e52-a805-01c5cdd54c90.png)

This is a permission issue, I use another image

```
  thanos:
    image:
      registry: quay.io
      repository: thanos/thanos
      tag: v0.24.0
  ```

**Comment by nitramrc** [comment]
> Hi,
> 
> My question is, did you create a thanos.yaml file or it was created automatically?

I had to manually create the secret for sidecar

`kubectl -n monitoring create secret generic thanos-objstore-config --from-file=thanos.yaml=</path/to>/s3.yaml`

**Comment by nitramrc** [comment]
btw my function setup ... I got the solution up and running in a few days ... 

kube-prometheus_values.yaml:
```
prometheus:
  disableCompaction: true
  replicaCount: 3
  shards: 1
  thanos:
    create: true
    image:
      registry: quay.io
      repository: thanos/thanos
      tag: v0.24.0
    objectStorageConfig:
      secretName: thanos-objstore-config
      secretKey: thanos.yaml

alertmanager:
  replicaCount: 3

kube-state-metrics:
  replicaCount: 3
```

thanos_values.yaml:
```
objstoreConfig: |-
  type: s3
  config:
    bucket: "rb-thanos-metrics4"
    endpoint: "s3.eu-central-1.amazonaws.com"
    region: "eu-central-1"
    access_key: "XXXXXXXXXXXXXXXXXXXXXXXXXX"
    secret_key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    signature_version2: false
query:
  dnsDiscovery:
    sidecarsService: kube-prometheus-prometheus-thanos
    sidecarsNamespace: monitoring
  replicaCount: 3
queryFrontend:
  replicaCount: 3
bucketweb:
  enabled: true
  replicaCount: 3
compactor:
  enabled: true
storegateway:
  enabled: true
  replicaCount: 3
ruler:
  enabled: true
  alertmanagers:
    - http://kube-prometheus-alertmanager.monitoring.svc.cluster.local:9093
  config: |-
      groups:
        - name: "metamonitoring"
          rules:
            - alert: "PrometheusDown"
              expr: absent(up{prometheus="monitoring/kube-prometheus-prometheus"})
  replicaCount: 3
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

**Comment by SrinivReddy** [comment]
for some reason I could see below message at container start up, But after waiting for 3 hours and had verified the thanos sidecar logs, I could see blocks are uploading to S3 bucket. So if anyone see below error lets wait for 3 hours and check the sidecar logs.

`level=warn ts=2023-02-24T07:47:50.996287654Z caller=shipper.go:239 msg="reading meta file failed, will override it" err="failed to read /prometheus/thanos.shipper.json: open /prometheus/thanos.shipper.json: no such file or directory" `

**Comment by nitramrc** [comment]
> for some reason I could see below message at container start up, But after waiting for 3 hours and had verified the thanos sidecar logs, I could see blocks are uploading to S3 bucket. So if anyone see below error lets wait for 3 hours and check the sidecar logs.
> 
> `level=warn ts=2023-02-24T07:47:50.996287654Z caller=shipper.go:239 msg="reading meta file failed, will override it" err="failed to read /prometheus/thanos.shipper.json: open /prometheus/thanos.shipper.json: no such file or directory" `

probably old log ? as I already wrote, I solved this by changing the sidecar image

**Comment by fmulero** [comment]
Hi all

We have several questions/doubts here. I'll try to answer the best I can.

> I believe we need to pass below arguments to thanos but unable to find related filed in values.yaml file. Can any one idea on this issue, I am using latest chart.
> --storage.tsdb.min-block-duration=2h
> --storage.tsdb.max-block-duration=2h

This is related to this [issue](https://github.com/prometheus-operator/prometheus-operator/issues/4414#issuecomment-1235591360) in kube-promethues side. It seems fixed but our CRDs are not updated to that version. We should update them and include that option in our chart.

As @nitramrc said, you can disable the compaction feature setting the value `prometheus.disableCompaction`.

About the warning: 
```
level=warn ts=2023-02-24T07:47:50.996287654Z caller=shipper.go:239 msg="reading meta file failed, will override it" err="failed to read /prometheus/thanos.shipper.json: open /prometheus/thanos.shipper.json: no such file or directory" 
```

I've reproduced it but I think is a "cosmetic error", the thanos sidecar starts faster than prometheus and the file is shared between both containers. If we force a restar of the container the error won't appear. Did you face any issue due to that?

**Comment by kcasas** [comment]
@nitramrc Experienced the same issue with `/prometheus/thanos.shipper.json`.
It happens cause the thanos-sidecar wants to read the file but prometheus is not done making it yet.
Enabling persistence will fix it. First pod will still fail though while the file does not exist yet, a restart will finally make this work.

```
prometheus:
  disableCompaction: true
  persistence:
    enabled: true
```
