### ISSUE TITLE
[bitnami/mongodb] logs a lot of authorization failed

### ISSUE THREAD

**Issue by maulal** [bitnami/charts#15131]
### Name and Version

bitnami/mongodb:6.0.4

### What steps will reproduce the bug?

Just deploy the pod with a metrics user.

### What is the expected behavior?

metrics user should have all the rights needed to work on mongodb.

### What do you see instead?

We can see a lot of error of authentication in the mongodb logs about the metrics user.

```
{"t":{"$date":"2023-02-16T10:58:34.590+00:00"},"s":"I", "c":"ACCESS", "id":20436, "ctx":"conn6163","msg":"Checking authorization failed","attr":{"error":{"code":13,"codeName":"Unauthorized","errmsg":"not authorized on admin to execute command { find: \"system.version\", filter: { _id: \"shardIdentity\" }, limit: 1, singleBatch: true, lsid: { id: UUID(\"237060c9-3a71-49fb-bf05-432739da0f4b\") }, $clusterTime: { clusterTime: Timestamp(1676545109, 120), signature: { hash: BinData(0, D555E0CDA6BDBE5B5749E4AD025BA01F55208F4A), keyId: 7200691780470177797 } }, $db: \"admin\", $readPreference: { mode: \"primaryPreferred\" } }"}}}
{"t":{"$date":"2023-02-16T10:58:34.590+00:00"},"s":"I", "c":"ACCESS", "id":20436, "ctx":"conn6162","msg":"Checking authorization failed","attr":{"error":{"code":13,"codeName":"Unauthorized","errmsg":"not authorized on admin to execute command { find: \"system.version\", filter: { _id: \"shardIdentity\" }, limit: 1, singleBatch: true, lsid: { id: UUID(\"78775c4b-77d1-463a-a953-b4cf8962a58d\") }, $clusterTime: { clusterTime: Timestamp(1676545109, 120), signature: { hash: BinData(0, D555E0CDA6BDBE5B5749E4AD025BA01F55208F4A), keyId: 7200691780470177797 } }, $db: \"admin\", $readPreference: { mode: \"primaryPreferred\" } }"}}}
```

### Additional information

Since some times (I do not know which version of the mongodb percona exporter, but it's more or less `>0.30`), even if it's not documented, we have to add a dedicated role to the metrics user.

```
db.createRole({role: 'explainRole', privileges: [
            { resource: {db: '', collection: ''}, actions: [ 'collStats', 'dbHash', 'dbStats', 'find', 'listIndexes', 'listCollections' ] },
            { resource: {db: '', collection: 'system.version'}, actions: [ 'find' ] }
], roles: [] });
db.createUser({user: username, pwd: password, roles: [{ role: 'clusterMonitor', db: 'admin' }, { role: 'read', db: 'local' }, { role: 'explainRole', db: 'admin' }] });
```

This bug is due to the collection stats gathering.

Can you add this to avoid failed authentications in the logs ?

Best regards,

**Comment by javsalgar** [comment]
Could you share the exact values.yaml changes that you used to deploy the chart?

**Comment by maulal** [comment]
Yes, for sure:

```
nameOverride: "mongodb"
replicaSetName: "rs0"
architecture: replicaset

auth:
  enabled: true
  rootUser: "root"
  rootPassword: "root"
  replicaSetKey: "changepassword"

metrics:
  enabled: true
  username: "monitor"
  password: "monitor"
  resources:
    limits:
      cpu: 400m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 64Mi

podSecurityContext:
  enabled: true
  fsGroup: 1001

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true

persistence:
  size: 4Gi
```
My bad, I explained that to see the trouble, you could directly make a curl inside the metrics pod, but curl is not installed in it... so here another way to reproduce the error with a port-forward on the metrics port.

**First ssh session (port-forward), just keep this session open until the end:**

```
kubectl port-forward pod/mongo-mongodb-0 9216:9216
```

**Second ssh session (mongodb logs - failed authentication), just keep this session open until the end:**

```
kubectl logs -f  mongo-mongodb-0 | grep -i failed
```

**Third ssh session (curl the /metrics endpoint), with this command you should see the error on the second ssh window:**

```
curl http://127.0.0.1:9216/metrics
```

On the second ssh window:

```
{"t":{"$date":"2023-02-24T10:03:44.141+00:00"},"s":"I",  "c":"ACCESS",   "id":20436,   "ctx":"conn313","msg":"Checking authorization failed","attr":{"error":{"code":13,"codeName":"Unauthorized","errmsg":"not authorized on admin to execute command { find: \"system.version\", filter: { _id: \"shardIdentity\" }, limit: 1, singleBatch: true, lsid: { id: UUID(\"1001fc85-8e78-4c5f-ba51-d2e7e1e55144\") }, $clusterTime: { clusterTime: Timestamp(1677233019, 1), signature: { hash: BinData(0, 35B84FA5AB76774A4CD5796D1AF5AAD5A00E8F94), keyId: 7203659104655507462 } }, $db: \"admin\", $readPreference: { mode: \"primaryPreferred\" } }"}}}
```

Best regards,
