### ISSUE TITLE
[bitnami/external-dns]  -  us-gov-cloud

### ISSUE THREAD

**Issue by SridharSambu** [bitnami/charts#15142]
### Name and Version

bitnami/external-dns 6.7.5

### What architecture are you using?

None

### What steps will reproduce the bug?

**aws-gov-cloud.**

getting this error
```
time="2023-02-24T14:34:03Z" level=error msg="records retrieval failed: failed to list hosted zones: RequestError: send request failed\ncaused by: Get \"https://route53.us-gov.amazonaws.com/2013-04-01/hostedzone\": dial tcp 52.46.228.39:443: i/o timeout"
```
**policy attached to service account.**
```
 statement {
    effect = "Allow"
    resources = ["arn:aws-us-gov:route53:::hostedzone/*"]
    actions = [
      "route53:ChangeResourceRecordSets",
       "route53:ListResourceRecordSets"
       ]
  }

  statement {
    effect    = "Allow"
    resources = ["*"]
    actions = [
      "route53:ListHostedZones",
     
    ]
  }

  statement {
    effect = "Allow"
    resources = [
      "arn:aws-us-gov:route53:::change/*"
    ]
    actions = [
      "route53:GetChange"
    ]
  }
}
```
image : bitnami/external-dns:0.13.2

### Are you using any custom parameters or values?
```yaml
provider: aws
sources:
  - service
  - ingress
aws:
  region: ${aws_region}
  zoneType: private
image:
  registry: ${registry}
  repository:bitnami/external-dns
  tag: 0.13.2
logLevel: debug
zoneIdFilters: 
    AAAAAAAAAAAAAAAA
txtOwnerId: eks-deployment
crd:
  create: true
```
### What is the expected behavior?

records should be retrieved

### What do you see instead?
```
time="2023-02-24T14:34:03Z" level=error msg="records retrieval failed: failed to list hosted zones: RequestError: send request failed\ncaused by: Get \"https://route53.us-gov.amazonaws.com/2013-04-01/hostedzone\": dial tcp 52.46.228.39:443: i/o timeout"
time="2023-02-24T14:34:03Z" level=debug msg="Refreshing zones list cache"
```
