### ISSUE TITLE
[bitnami/mongodb] Custom databases not getting created

### ISSUE THREAD

**Issue by desgith** [bitnami/charts#15151]
### Name and Version

mongodb-13.6.7

### What architecture are you using?

None

### What steps will reproduce the bug?

```helm.exe install mongodb .  -n mongo``` 

### Are you using any custom parameters or values?

```
  usernames: [mycontext]
  passwords: [context]
  databases: [mynewdb]
```

### What is the expected behavior?

```
mongosh admin --host "mongodb-0.mongodb-headless.m.svc.cluster.local:27017,mongodb-1.mongodb-headless.m.svc.cluster.local:27017" --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD
```
The above command should login and 
```
show dbs
```
should show me `mynewdb`

### What do you see instead?

```
rs0 [primary] admin> show dbs
admin   140.00 KiB
config  184.00 KiB
local   620.00 KiB
```
`mynewdb` is missing

### Additional information

Am i doing anything wrong in this command or my understanding is wrong?  `.Values.auth.databases` create new DBs or should i do something else to make it work

**Comment by javsalgar** [comment]
Hi!

Could you share the logs of the containers to see if there's an any error?

**Comment by desgith** [comment]
Hi,
 I dont see any errors, i am seeing no restarts in the containers as well
 ```
 NAME                            READY   STATUS             RESTARTS          AGE
mongodb-0                       1/1     Running            0                 45h
mongodb-1                       1/1     Running            0                 45h
mongodb-arbiter-0               1/1     Running            0                 45h
 ```
 The log is very big, with errors related to missing `username` as well, which i tried creating using `custom usernames` let me know if you need it

**Comment by desgith** [comment]
Any update on this request?

**Comment by benhosmereop** [comment]
@aoterolorenzo I've got a a similar issue:

```
rs0 [primary] admin> show dbs
admin   172.00 KiB
config  216.00 KiB
local   444.00 KiB
```
`$ helm upgrade --install rc-mongo mongodb/mongodb -f mongodb-dev-values.yaml -n rc`

`mongodb-dev-values.yaml`

```
auth:
  usernames:
    - rocketchat
  databases:
    - rocketchat
  passwords:
    - rocketchat
  rootPassword: rocketchat
architecture: replicaset
useStatefuleSet: false
replicaCount: 3
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "node-role.kubernetes.io/control-plane"
          operator: DoesNotExist
        - key: "node-role.kubernetes.io/etcd"
          operator: DoesNotExist
        - key: "node-role.kubernetes.io/master"
          operator: DoesNotExist
arbiter:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "node-role.kubernetes.io/control-plane"
            operator: DoesNotExist
          - key: "node-role.kubernetes.io/etcd"
            operator: DoesNotExist
          - key: "node-role.kubernetes.io/master"
            operator: DoesNotExist
```
