### ISSUE TITLE
[bitnami/keycloak]  Service "keycloak-pre" is invalid: spec.ports[1].name: Duplicate value: "http"

### ISSUE THREAD

**Issue by aboubeta** [bitnami/charts#15158]
### Name and Version

bitnami/keycloak 13.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

* On a EKS cluster: 

### Are you using any custom parameters or values?

```
image:
  pullPolicy: Always
  debug: true 

service:
  type: ClusterIP
  http:
    enabled: true 

ingress:
  enabled: true
  ingressClassName: alb  
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /auth/
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/group.name: keycloak
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip


postgresql:
  enabled: false


production: true
proxy: edge 
httpRelativePath: /auth/

logging:
  level: DEBUG

auth:
  adminUser: XXXXXXXXXXXX
  adminPassword : XXXXXXXXX

externalDatabase:
  host: XXXXXXXXXX
  port: XXXXXXXXXX
  user: XXXXXXXXXX
  password: XXXXXXXXX
  database: XXXXXXXXX
```

### What is the expected behavior?

```
helm upgrade --install --create-namespace -f deployment/config-pre.yaml keycloak-pre bitnami/keycloak
11:56:26  Release "keycloak-pre" has been upgraded. Happy Helming!
11:56:26  NAME: keycloak-pre
11:56:26  LAST DEPLOYED: Wed Jan 11 10:56:25 2023
11:56:26  NAMESPACE: keycloak-pre
11:56:26  STATUS: deployed
11:56:26  REVISION: 5
11:56:26  TEST SUITE: None
11:56:26  NOTES:
11:56:26  CHART NAME: keycloak
11:56:26  CHART VERSION: 13.1.1
11:56:26  APP VERSION: 20.0.2
```

### What do you see instead?

```
helm upgrade --install --create-namespace -f deployment/config-pre.yaml keycloak-pre bitnami/keycloak

Error: UPGRADE FAILED: cannot patch "keycloak-pre-headless" with kind Service: Service "keycloak-pre-headless" is invalid: spec.ports[1].name: Duplicate value: "http" && cannot patch "keycloak-pre" with kind Service: Service "keycloak-pre" is invalid: spec.ports[1].name: Duplicate value: "http"
```

**Comment by javsalgar** [comment]
Hi,

Could you add a more descriptive title to the issue?

**Comment by aboubeta** [comment]
Sorry, Monday morning :P

**Comment by jotamartos** [comment]
Hi, 

If I run the helm template command with the parameters you posted in your first message, I can see that there is not a duplicated http entry in the headless service file 

```
# Source: keycloak/templates/headless-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-keycloak-headless
  namespace: "jotamartos"
  labels:
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-13.1.3
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: keycloak
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/component: keycloak
```

Can you check if you get the same result? I'm generating this template using the latest version of the chart, please ensure you are using it too. 

Thanks.
