### ISSUE TITLE
chart "keycloak" matching 7.1.18 not found in bitnami index

### ISSUE THREAD

**Issue by MageshAnand** [bitnami/charts#15154]
### Name and Version

bitnami/keycloak 7.1.18

### What architecture are you using?

None

### What steps will reproduce the bug?

I'm using keycloak version 7.1.18 for my application. recently it's not been working and getting the below error. Is the mentioned version removed?
```
Error: INSTALLATION FAILED: chart "keycloak" matching 7.1.18 not found in bitnami index. (try 'helm repo update'): no chart version found for keycloak-7.1.18
```

Install command:
`helm install keycloak -f keycloak_values.yml bitnami/keycloak  --version 7.1.18`

keycloak_values.yml:
```yaml
service:
  ports:
    http: 9080
    https: 9443
auth:
  adminPassword: admin
extraEnvVars:
  - name: KEYCLOAK_LOGLEVEL
    value: ALL
  - name: ROOT_LOGLEVEL
    value: ALL
```

Thanks in advance.

### What do you see instead?
```
Error: INSTALLATION FAILED: chart "keycloak" matching 7.1.18 not found in bitnami index. (try 'helm repo update'): no chart version found for keycloak-7.1.18
```
