### ISSUE TITLE
[bitnami/thanos] Service account name won't change after initial release

### ISSUE THREAD

**Issue by antoinedeschenes** [bitnami/charts#15181]
### Name and Version

bitnami/thanos 11.6.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Create an initial `thanos` release, then attempt to change the service account name. One will find out that the deployment spec hasn't changed and fails with the following error, because the chart is provisioning the deprecated PodSpec `serviceAccount` field. 

```
Error creating: pods "thanos-compactor-decafdecaf-" is forbidden: error looking up service account thanos/thanos-compactor-2: serviceaccount "thanos-compactor-2" not found
```

### Are you using any custom parameters or values?

After an initial deployment, change the service account name:

```yaml
compactor:
  serviceAccount:
    name: thanos-compactor-2
```

### What is the expected behavior?

```yaml
spec:
  template:
    spec:
      serviceAccount: thanos-compactor-2
      serviceAccountName: thanos-compactor-2
```

### What do you see instead?

```yaml
spec:
  template:
    spec:
      serviceAccount: thanos-compactor
      serviceAccountName: thanos-compactor
```

### Additional information

Quick testing shows it's impossible to patch the `serviceAccount` field after a resource's initial creation:

```
# Create test resources
% kubectl create sa one
serviceaccount/one created

% kubectl create sa two
serviceaccount/two created

% kubectl create deploy test --image=nginx:alpine
deployment.apps/test created

% kubectl get deploy test -o yaml | yq .spec.template.spec | grep serviceAccount

# Add initial serviceAccount to deployment
% kubectl patch deploy test -p '{"spec":{"template":{"spec":{"serviceAccount":"one"}}}}'
deployment.apps/test patched

% kubectl get deploy test -o yaml | yq .spec.template.spec | grep serviceAccount
serviceAccount: one
serviceAccountName: one

# Failed attempt to patch serviceAccount using the 'serviceAccount' field
% kubectl patch deploy test -p '{"spec":{"template":{"spec":{"serviceAccount":"two"}}}}'
deployment.apps/test patched (no change)

% kubectl get deploy test -o yaml | yq .spec.template.spec | grep serviceAccount
serviceAccount: one
serviceAccountName: one

# Successful patch to serviceAccount using the 'serviceAccountName' field
% kubectl patch deploy test -p '{"spec":{"template":{"spec":{"serviceAccountName":"two"}}}}'
deployment.apps/test patched

% kubectl get deploy test -o yaml | yq .spec.template.spec | grep serviceAccount
serviceAccount: two
serviceAccountName: two
```
