### ISSUE TITLE
rabbitmq-cluster-[msgTopologyOperator]

### ISSUE THREAD

**Issue by sb185296** [bitnami/charts#15288]
### Name and Version

rabbitmq-cluster-operator/latest

### What architecture are you using?

None

### What steps will reproduce the bug?

1. I install rabbitmq-cluster-operator
2. I see that I have rabbit + msgTopolog
3. I add to the rabbit TLS CERT
4. everything is working with the rabbit 

when I try to use msgTopolog I get error there are 2 ways

```yaml
- name: MESSAGING_DOMAIN_NAME
value: "my.cluster.domain"
```

1. without `MESSAGING_DOMAIN_NAME` its goes to the local SVC and get a fail on TLS
![image](https://user-images.githubusercontent.com/66299621/222154565-9cb335e9-15d6-4216-a5ae-5b2105e94845.png)

2. with `MESSAGING_DOMAIN_NAME`, it try to reach out the world and then I add this 2 vale also that didn't work
```yaml
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
```
![image](https://user-images.githubusercontent.com/66299621/222154500-eb9e1fc7-a409-46ee-bd7b-08d495153578.png)

```
error: "Put "https://rabbithq.r10.svc.test.*.com:15671/api/users/test": dial tcp 13.65.174.163:15671: connect: connection timed out"
```

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: shay-user-credentials
  namespace: test
type: Opaque
stringData:
  username: "test"
  password: "Qwe12345"
  uri: httpS://rabbithq:15671
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: shay-user
  namespace: test
spec:
  rabbitmqClusterReference:
    name: rabbithq
  importCredentialsSecret:
    name: shay-user-credentials
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: shay-user-permission
  namespace: test
spec:
  vhost: "/"
  user: "shay-user" # name corresponds to the username we provided in "shay-user-credentials" secret
  permissions:
    write: ".*"
    configure: ""
    read: ".*"
  rabbitmqClusterReference:
    name: rabbithq
```

### Are you using any custom parameters or values?

I try to add also
```yaml
  values:
    msgTopologyOperator:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
```
and didn't work same errors

### What is the expected behavior?

that its work

### What do you see instead?

error

**Comment by carrodher** [comment]
It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by sb185296** [comment]
hi thanks for repsoe 

i think that its very basic one , just to install RabbitMQ operator + Topology
and then install rabbit server with TLS cert
and then try to use the Topology to perfrom somting

i try this : https://rabbitmq.com/kubernetes/operator/install-topology-operator.html#non-default-k8s-domain
but didnt work

this not exsite :(
https://github.com/rabbitmq/messaging-topology-operator/blob/f43013b44936be1b1b1ef279be583fa3d54292bf/docs/proposals/20220105-start-certificate-support.md?plain=1#L100

how can i make it work ?

**Comment by dgomezleon** [comment]
Just for clarifying it. I have some questions about your scenario:

* Are you using a Kubernetes internal domain name different than `.cluster.local.`
* Can you see the service is created as expected? Can you access them?
* Have tried adding the annotation as proposed [here](https://github.com/rabbitmq/messaging-topology-operator/blob/f43013b44936be1b1b1ef279be583fa3d54292bf/docs/proposals/20220105-start-certificate-support.md?plain=1#L100)?

**Comment by sb185296** [comment]
hi ,

1. no i not cahnge it
2. yes
3.  this not existe / not working
```
`messaging.rabbitmq.com/override-url` with value `"https://myrabbit.example.com"`.
```

**Comment by dgomezleon** [comment]
Hi @sb185296 ,

I double-checked it. 

> 2\. with `MESSAGING_DOMAIN_NAME`, it try to reach out the world and then I add this 2 vale also that didn't work
> 
> ```yaml
>       hostNetwork: true
>       dnsPolicy: ClusterFirstWithHostNet
> ```

It seemed that using `MESSAGING_DOMAIN_NAME` changed the issue with the certificate. Did you try it without editing `hostNetwork` and `dnsPolicy`? What result did you get?

About the anotation, they say:

> In certain scenarios, the above solution won't be sufficient. For example, RabbitMQ can be exposed via
TCP Ingress to applications external to Kubernetes. In this scenario, RabbitMQ is provisioned with a
certificate to match the FQDN used to connect to the Ingress, for example `rabbitmq-example.my-domain.com`.
In this scenario, it is not possible to determine the URL from the pieces of information described above.
In order to satisfy this scenario, the Topology Operator needs the URL as input, per RabbitMQ instance.
The proposed solution is to use an annotation in `RabbitmqCluster`, with the URL to connect to as value.
For example, the annotation `messaging.rabbitmq.com/override-url` with value `"https://myrabbit.example.com"`.

I understand that you are not using an Ingres, so it should not be necessary. Isn't it?

**Comment by sb185296** [comment]
hi ,

yes i try without the ``` hostNetwork: true dnsPolicy: ClusterFirstWithHostNet```
without it still try to reach out to the world

i try this one : messaging.rabbitmq.com/override-url
but when i serach in them source code there is no point to somting like that ,so i think they didnt devolve it yet

in your installtion is that can be work ? with CERT and costume domain ?

**Comment by dgomezleon** [comment]
Hi @sb185296 ,

Note that we don't try all the possible combinations with the available CRDs.

Could you share all your CRDs definitions (apart from `User` and `Permission`) so we could try to reproduce it? You could use a common placeholder for sensitive information like DOMAIN, NAMESPACE, etc.

**Comment by sb185296** [comment]
i dont use any CRD just the bitnami helm with FLUX to install the helm chart

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq-cluster-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: rabbitmq-cluster-operator
  targetNamespace: rabbitmq-system
```


Chart : 

```values.yaml
# replicas -- Number of rabbit nodes. 
replicas: 1

mirroring:
  enabled: false
tls:
  secretName: rabbit-tls
  caSecretName: rabbit-tls

persistence: {}
image: "rabbitmq:3.10.7-management"
service:
  type: ClusterIP # set this to LoadBalancer when using rabbit tls termination
resources: {}
nodeSelector: {}

```


```rabbitmq.yaml

apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ .Release.Name }}

spec:
  {{- if .Values.image }}
  image: {{ .Values.image }}
  {{- end }}

  {{- if .Values.imagePullSecret }}
  imagePullSecret: {{ .Values.imagePullSecret }}
  {{- end }}

  replicas: {{ .Values.replicas }}
  
  {{- if .Values.tls }}
  tls:
{{ toYaml .Values.tls | indent 4 }}    
  {{- end }}

  {{- if .Values.service }}
  service:
    type: {{ .Values.service.type }}
    {{- if .Values.service.annotations }}
    annotations:
{{ toYaml .Values.service.annotations | indent 6 }}
    {{- end }}
  {{- end }}

  {{- if .Values.persistence }}
  persistence:
    storageClassName: {{ required ".Values.persistence.storageClassName entry required! GKE: premium-rwo ,AKS: managed-premium, K3S: local-path" .Values.persistence.storageClassName }}
    storage: {{ required ".Values.persistence.storage entry required!" .Values.persistence.storage }}
  {{- end }}

  {{- if .Values.tolerations }}
  tolerations:
{{ toYaml .Values.tolerations | indent 2 }}
  {{- end }}

  {{- if .Values.affinity }}
  affinity:
{{ toYaml .Values.affinity | indent 4 }}
  {{- end }}

  resources: {{- toYaml .Values.resources | nindent 4 }}

  rabbitmq:
    additionalPlugins:
    - rabbitmq_shovel
    - rabbitmq_shovel_management
    additionalConfig: |
      load_definitions = /etc/definitions/def.json
    advancedConfig: |
      [
      {rabbit,
        [
        {queue_index_embed_msgs_below ,0},
        {tcp_listen_options, 
                                                  [
                                                                  {backlog,       128},
                                                                  {nodelay,       true},
                                                                  {linger,        {true,0}},
                                                                  {exit_on_close, false},
                                                                  {sndbuf,        196608},
                                                                  {recbuf,        196608},
                                                                  {send_timeout,        900000}]
                                                                                                                                                                                                                                      },
        {log_levels, [{connection, error}, {channel, error}]},
        {vm_memory_high_watermark, 0.8},
        {vm_memory_high_watermark_paging_ratio, 9.0},
        {collect_statistics, none},
        {collect_statistics_interval, 60000}   
        ]
        },
        {mnesia, 
        [
        {dump_log_write_threshold, 2000}, 
        {dc_dump_limit, 40}
        ]
        }
      ].

  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              volumeMounts:
              - mountPath: /etc/definitions
                name: definitions
            volumes:
            - name: definitions
              configMap:
                name: "{{ .Release.Name }}-definitions"
            {{- with .Values.nodeSelector }}
            nodeSelector:
            {{- toYaml . | nindent 14 }}
            {{- end }}
    {{- if .Values.service.loadBalancerIP }}
    service:
      spec:
        loadBalancerIP: {{ .Values.service.loadBalancerIP }}
    {{- end }}
```

**Comment by dgomezleon** [comment]
Hi @sb185296,

The operator is responsible for executing all the logic here. Additionally, we noticed that you are currently using the Rabbitmq official image instead of the Bitnami image. Therefore, to address your scenario, it may be helpful to open an upstream case and seek guidance from Rabbitmq developers.

**Comment by sb185296** [comment]
ok let me switch to the Bitnami image and i will recheck it with your configations

i will update

**Comment by sb185296** [comment]
hi ,

now i install like you say with bitnami image only
and take all default parms

now i get different error :\

```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm upgrade rabbit bitnami/rabbitmq-cluster-operator --set msgTopologyOperator.existingWebhookCertSecret=tls-secret
```

create TLS secret

```
# Source: r10/charts/hq-rabbitmq/templates/rabbitmq.yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbit
spec:
  tls:
    secretName: tls-secret
  replicas: 1
  persistence:
    storageClassName: managed-premium
    storage: "100Gi"
  service:
    type: LoadBalancer
    #annotations:
    #  service.beta.kubernetes.io/azure-load-balancer-internal: "true"

  rabbitmq:
    additionalPlugins:
    - rabbitmq_shovel
    - rabbitmq_shovel_management
```

i also add this to try bypass it
    additionalConfig: |
      ssl_options.fail_if_no_peer_cert = false
      ssl_options.verify = verify_none

![image](https://user-images.githubusercontent.com/66299621/229366362-8d2e561c-6af0-4570-8604-23276a24813e.png)

![image](https://user-images.githubusercontent.com/66299621/229366297-4d024fad-a0a5-4ac3-916c-883af4e8b15d.png)
