### ISSUE TITLE
[bitnami/postgresql-ha] Creating new user credentials post deployment in postgresql-ha 

### ISSUE THREAD

**Issue by ranjeetranjan** [bitnami/charts#15292]
### Name and Version

bitnami/postgresql-ha 11.1.3 

### What architecture are you using?

arm64

### What steps will reproduce the bug?

We wanted to **create new user credentials post-deployment** of the postgresql-ha on the **Kubernetes**. Did not find relevant documentation on how I can create a new user once we deploy or in an existing postgresql-ha cluster. 

### What do you see instead?

N/A

**Comment by ranjeetranjan** [comment]
Would you mind sharing one example for creating a user and their credentials and database? This will give a clear idea.

**Comment by javsalgar** [comment]
I did not have much time but this is an example of a skeleton

```
extraDeploy:
 - |
   apiVersion: batch/v1
   kind: Job
   metadata:
     name: {{ include "common.names.fullname" . }}-init
     namespace: {{ .Release.Namespace }}
   spec:
     backoffLimit: 20
     template:
       spec:
         restartPolicy: OnFailure
         containers:
           - name: populate-database
             image: {{ include "postgresql.image" . }}
             command:
               - /bin/bash
               - -ec
             args:
               - | 
                  #!/bin/bash
                  # YOUR PSQL COMMANDS HERE
                 
             env:
               - name: PGPASSWORD
                 valueFrom:
                   secretKeyRef:
                     name: {{ template "postgresql.secretName" . }}
                     key: postgres-password
```
