### ISSUE TITLE
[bitnami/minio] .Values.networkPolicy.extraFromClauses wrong default type

### ISSUE THREAD

**Issue by G-Tarik** [bitnami/charts#15314]
### Name and Version

bitnami/minio 12.1.10

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Create sample Helm Chart with `helm create sample`
2. Include Bitnami/Minio in dependencies of `sample`
    ```yaml
    dependencies:
      - name: minio
        repository: https://charts.bitnami.com/bitnami
        version: "12.x.x"
    ```
4. Put in values.yaml of `sample` chart this:
    ```yaml
    minio:
      networkPolicy:
        enabled: true
        extraFromClauses:
          - podSelector: {}
    ```
5.  Execute `helm lint sample/`. Any of `helm template` or `helm install` also produce the same bug.

### What is the expected behavior?

I expect to see successful lint without warnings:
```console
==> Linting .
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
```

 The fix is to set in default values.yaml of Bitnami/Minio `list` instead of `map` in `networkPolicy.extraFromClauses` as below:
```yaml
networkPolicy:
  extraFromClauses: []
```
It must be a `list`, even the example shows it at line 869:
```yaml
  ## Example
  ## extraFromClauses:
  ## - podSelector:
  ##     matchLabels:
  ##       a: b
```

### What do you see instead?

```console
coalesce.go:220: warning: cannot overwrite table with non table for sample.minio.networkPolicy.extraFromClauses (map[])
coalesce.go:220: warning: cannot overwrite table with non table for sample.minio.networkPolicy.extraFromClauses (map[])
coalesce.go:220: warning: cannot overwrite table with non table for sample.minio.networkPolicy.extraFromClauses (map[])
coalesce.go:220: warning: cannot overwrite table with non table for sample.minio.networkPolicy.extraFromClauses (map[])
```
