### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] Chart v3.2.4 - Incorrect Service name

### ISSUE THREAD

**Issue by tlb1galaxy** [bitnami/charts#15324]
### Name and Version

bitnami/rabbitmq-cluster-operator 3.2.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. helm install rabbitmq-cluster-operator bitnami/rabbitmq-cluster-operator --version 3.2.4 -n global-rabbitmq-operator -f bitnami_rabbitmq-operator-override-values-v3.2.4.yaml
2. kubectl apply -f 50-rabbitmq-cluster.yaml

### bitnami_rabbitmq-operator-override-values-v3.2.4.yaml
``` yaml
# Override-values for Bitnami RabbitMQ Operator
#
msgTopologyOperator:
  replicaCount: 2
useCertManager: true
```

### 50-rabbitmq-cluster.yaml
``` yaml
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: compass-staging
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "*"
spec:
  replicas: 2
  resources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 3
      memory: 6Gi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
  persistence:
    storageClassName: rook-ceph-block-ssd
    storage: "50Gi"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - pod-anti-affinity
          topologyKey: kubernetes.io/hostname
...
```

### What is the expected behavior?

So seems chart v3.2.4 creates a service named ```rabbitmq-cluster-rabbitmq-messaging-topology-operator``` and not ```rabbitmq-cluster-rabbitmq-messaging-topology-operator-webhook```

### What do you see instead?

chart v3.2.4 creates a service named ```rabbitmq-cluster-rabbitmq-messaging-topology-operator```

**Comment by tlb1galaxy** [comment]
Can validate chart v3.2.3 works ok.

**Comment by tlb1galaxy** [comment]
Opened issue with rabbitmq-operator but they said it is a chart issue and not an operator issue.
https://github.com/rabbitmq/cluster-operator/issues/1280

**Comment by javsalgar** [comment]
Hi,

Could you explain the issue that this is causing? It has to do with the character limit but the ValidatingWebhookConfiguration should point to the proper service name.

**Comment by tlb1galaxy** [comment]
When I deploy via the above manifest, I receive the following error:
```
Error from server (InternalError): error when creating "95-secret-user-permission.yaml": Internal error occurred: failed calling webhook "vuser.kb.io": failed to call webhook: Post "https://rabbitmq-cluster-rabbitmq-messaging-topology-operator-webhook.compass-staging.svc:443/validate-rabbitmq-com-v1beta1-user?timeout=10s": service "rabbitmq-cluster-rabbitmq-messaging-topology-operator-webhook" not found
Error from server (InternalError): error when creating "95-secret-user-permission.yaml": Internal error occurred: failed calling webhook "vpermission.kb.io": failed to call webhook: Post "https://rabbitmq-cluster-rabbitmq-messaging-topology-operator-webhook.compass-staging.svc:443/validate-rabbitmq-com-v1beta1-permission?timeout=10s": service "rabbitmq-cluster-rabbitmq-messaging-topology-operator-webhook" not found
```

**Comment by tlb1galaxy** [comment]
Forgot to mention.
- The operators are deployed in a global (different from the deployment) namespace
- Enabled the cross-namespace option

Whenever you try to deploy a RabbitMQ object within the non-global namespace, you receive the above error message.

## 95-secret-user-permission.yaml
``` yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: svc-rabbitmq-ra
  namespace: compass-staging
  labels:
    app.kubernetes.io/name: secret
    app.kubernetes.io/instance: compass-staging
    app.kubernetes.io/version: "3.2.4"
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: rabbitmq-cluster
    app.kubernetes.io/managed-by: manifests
    lastupdate: "202303031104" # yyyymmddhhmm - Should match 'User' labels
type: Opaque
stringData:
  username: "user1"
  password: "XXXXXXXX"
...
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: user1
  namespace: compass-staging
  labels:
    app.kubernetes.io/name: user
    app.kubernetes.io/instance: compass-staging
    app.kubernetes.io/version: "3.2.4"
    app.kubernetes.io/component: permissions
    app.kubernetes.io/part-of: rabbitmq-cluster
    app.kubernetes.io/managed-by: manifests
    lastupdate: "202303031104" # yyyymmddhhmm - update field for any changes to secret are populated to RabbitMQ
spec:
  tags:
    - administrator
  rabbitmqClusterReference:
    name: rabbitmq-cluster
  importCredentialsSecret:
    name: user1
...
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: user1
  namespace: compass-staging
  labels:
    app.kubernetes.io/name: permission
    app.kubernetes.io/instance: compass-staging
    app.kubernetes.io/version: "3.2.4"
    app.kubernetes.io/component: permissions
    app.kubernetes.io/part-of: rabbitmq-cluster
    app.kubernetes.io/managed-by: manifests
    lastupdate: "202303031104" # yyyymmddhhmm - update field for any changes to secret are populated to RabbitMQ
spec:
  vhost: "/"
  user: "user1" # name corresponds to the username we provided in secret
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq-cluster
...
```
