### ISSUE TITLE
Minio-Chart 'metrics' missing 'enabled' property

### ISSUE THREAD

**Issue by haojingma** [bitnami/charts#15332]
### Name and Version

bitnami/minio 12.1.10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. environment
   - linux: centos7
   - kernel: 3.10.0-1062.el7.x86_64
   - K8s: 1.19.15
2. config(ChartValue)
minio-values.yaml(detail see blow)
3. run shell
`helm install my-minio -f minio-values.yaml my-repo/minio --version 12.1.10`
4. error
PrometheusRule no generate& no apply.

### Are you using any custom parameters or values?

```yaml
global:
  storageClass: "localstorage-class"
persistence:
  mountPath: "/data-minio"
ingress:
  enabled: true
auth:
  rootUser: "admin"
  rootPassword: "xxxxx"
mode: distributed
statefulset:
  zones: 2
  replicaCount: 4
  drivesPerNode: 2
metrics:
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true
    rules:
    - alert: NodesOffline
      expr: avg_over_time(minio_cluster_nodes_offline_total{job="minio-job"}[5m]) > 0
      for: 10m
      labels:
        severity: warn
      annotations:
        summary: "Node down in MinIO deployment"
        description: "Node(s) in cluster {{ $labels.instance }} offline for more than 5 minutes"
    - alert: DisksOffline
      expr: avg_over_time(minio_cluster_disk_offline_total{job="minio-job"}[5m]) > 0
      for: 10m
      labels:
        severity: warn
      annotations:
        summary: "Disks down in MinIO deployment"
        description: "Disks(s) in cluster {{ $labels.instance }} offline for more than 5 minutes"
```

### What do you see instead?

No PromethuesRules in THAT NAMESPACE!

**Comment by haojingma** [comment]
values looks not good.
for this maybe better.
```
---
global:
  storageClass: "localstorage-class"
persistence:
  mountPath: "/data-minio"
ingress:
  enabled: true
auth:
  rootUser: "admin"
  rootPassword: "xxxx"
mode: distributed
statefulset:
  zones: 2
  replicaCount: 4
  drivesPerNode: 2
metrics:
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true
    rules:
    - alert: NodesOffline
      expr: avg_over_time(minio_cluster_nodes_offline_total{job="minio-job"}[5m]) > 0
      for: 10m
      labels:
        severity: warn
      annotations:
        summary: "Node down in MinIO deployment"
        description: "Node(s) in cluster {{ $labels.instance }} offline for more than 5 minutes"
    - alert: DisksOffline
      expr: avg_over_time(minio_cluster_disk_offline_total{job="minio-job"}[5m]) > 0
      for: 10m
      labels:
        severity: warn
      annotations:
        summary: "Disks down in MinIO deployment"
        description: "Disks(s) in cluster {{ $labels.instance }} offline for more than 5 minutes"
```
