### ISSUE TITLE
[bitnami/mongodb] Migrating from standalone to replicaset

### ISSUE THREAD

**Issue by bwmills** [bitnami/charts#15345]
### Name and Version

bitnami/mongodb

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Please details below.

### What do you see instead?

Please details below.

### Additional information

Greetings,

The issue is related to migrating from an existing `standalone` to a `replicaset` architecture.

Is this possible?

In EKS running Kubernetes 1.22 using chart version `10.31.5` with this Helm release manifest:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: analytics
  namespace: mongo
spec:
  interval: 5m
  chart:
    spec:
      chart: mongodb
      version: '10.31.5'
      sourceRef:
        kind: HelmRepository
        name: mongo
        namespace: mongo
      interval: 1m
  values:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - analytics
          topologyKey: "kubernetes.io/hostname"
    architecture: standalone
    auth:
      enabled: true
      database: <redacted>
      storage:
        journal:
          enabled: true
      net:
        bindIp: "0.0.0.0"
        port: 27017
    image:
      tag: 4.4.11-debian-10-r12
      pullPolicy: IfNotPresent
      repository: bitnami/mongodb
    metrics:
      enabled: true
      serviceMonitor:
        namespace: monitoring
        enabled: true
        additionalLabels:
          release: prometheus
    nodeSelector:
      nodeGroup: <redacted>
    replicaCount: 1
    tolerations:
      - key: "<redacted>"
        operator: "Exists"
        effect: "NoSchedule"
    useStatefulSet: true
  valuesFrom:
  ...
  ...
```

had MongoDB working well with a standalone config. Then changed only these fields in the manifest:

```yaml
replicaCount: 2
architecture: replicaset
```

everything else is the same.

_Note: we have MongoDB deployed as a replicaset using the same chart and application versions in other environments, where it's working well (i.e. we are familiar with the PSA setup)._

In the environment where we have an issue, the expected behavior is that recreating this Helm release would:

[1] Deploy an arbiter pod (understood that it has its own StatefulSet)
[2] Deploy a -0 ordinal pod and use default Kubernetes liveness and readiness probes to go healthy
[3] Deploy a -1 ordinal pod and use default Kubernetes liveness and readiness probes to go healthy - this step implies the creation of a new persistent volume for this data-bearing node/pod
[4] Allow authentication from embedded mongo clients in a set of microservices that depend on these database collections

What we see instead is:

[1] Arbiter pod does get deployed and initially logs:

```
INFO  ==> Found MongoDB server listening at analytics-mongodb-0.analytics-mongodb-headless.mongo.svc.cluster.local:27017 !
``` 

[2] analytics-mongodb-0 pod starts up without complaint, but:

* never goes healthy
* logs these messages repeatedly

```
mongodb {"t":{"$date":"2023-03-06T17:00:24.237+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn765","msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-256","speculative":true,"principalName":"<redacted>","authenticationDatabase":"admin","remote":"<pod ip of arbiter>:58398","extraInfo":{}}}
mongodb {"t":{"$date":"2023-03-06T17:00:24.250+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn765","msg":"Connection ended","attr":{"remote":"<pod ip of arbiter>:58398","connectionId":765,"connectionCount":30}}
```

[3] A -1 ordinal pod is never deployed

[4] Client applications complaining about:

```
Caused by: com.mongodb.MongoQueryException: Query failed with error code 13436 with name 'NotPrimaryOrSecondary' and error message 'node is not in primary or recovering state' on server analytics-mongodb-0.analytics-mongodb-headless.mongo.svc.cluster.local:27017 
```

[5] Arbiter pod eventually crashloops

Any help is much appreciated, thank you.
