### ISSUE TITLE
[bitnami/kafka] no template "kafka.fullname" associated with template "gotpl"

### ISSUE THREAD

**Issue by Mihai-CMM** [bitnami/charts#15340]
### Name and Version

bitnami/kafka

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. helm chart doesn't seems to work when i  add: 
```
extraDeploy:
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: {{ include "kafka.fullname" . }}-connect
      labels: {{- include "common.labels.standard" . | nindent 4 }}
        app.kubernetes.io/component: connector
    spec:
      replicas: 1
      selector:
        matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
          app.kubernetes.io/component: connector
      template:
        metadata:
          labels: {{- include "common.labels.standard" . | nindent 8 }}
            app.kubernetes.io/component: connector
        spec:
          containers:
            - name: connect
              image: costache2mihai/kafkamongo
              imagePullPolicy: Never
              command: [ "/bin/bash", "-c", "/opt/bitnami/kafka/bin/connect-standalone.sh /config/connect-standalone.properties /config/mongodb-sink.properties"]
              ports:
                - name: connector
                  containerPort: 8083
              volumeMounts:
                - name: configuration
                  mountPath: /config
          volumes:
            - name: configuration
              configMap:
                name: {{ include "kafka.fullname" . }}-connect
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ include "kafka.fullname" . }}-connect
      labels: {{- include "common.labels.standard" . | nindent 4 }}
        app.kubernetes.io/component: connector
    data:
      connect-standalone.properties: |-
        bootstrap.servers={{ include "kafka.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.service.port }}
        key.converter=org.apache.kafka.connect.json.JsonConverter
        value.converter=org.apache.kafka.connect.json.JsonConverter
        key.converter.schemas.enable=true
        value.converter.schemas.enable=true
        offset.storage.file.filename=/tmp/connect.offsets
        offset.flush.interval.ms=20000
        plugin.path=/opt/bitnami/kafka/plugins
      mongodb-sink.properties: |-
        connection.uri=mongodb://user:pass@mongos-mongodb-sharded.mongos.svc.datalake/?authSource=datalake
        name=mongo-sink-connector
        topics=dns
        connector.class=com.mongodb.kafka.connect.MongoSinkConnector
        tasks.max=1
        key.converter=org.apache.kafka.connect.json.JsonConverter
        value.converter=org.apache.kafka.connect.json.JsonConverter
        key.converter.schemas.enable=false
        value.converter.schemas.enable=false
        database=datalake
        collection=kafka-sink
  - |
    apiVersion: v1
    kind: Service    
    metadata:
      name: {{ include "kafka.fullname" . }}-connect
      labels: {{- include "common.labels.standard" . | nindent 4 }}
        app.kubernetes.io/component: connector
    spec:
      ports:
        - protocol: TCP
          port: 8083
          targetPort: connector
      selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
        app.kubernetes.io/component: connector
```

### Are you using any custom parameters or values?

per above

### What do you see instead?
```
Error: template: kafka/templates/extra-list.yaml:3:3: executing "kafka/templates/extra-list.yaml" at <include "common.tplvalues.render" (dict "value" . "context" $)>: error calling include: template: kafka/charts/common/templates/_tplvalues.tpl:9:12: executing "common.tplvalues.render" at <tpl .value .context>: error calling tpl: error during tpl function execution for "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {{ include \"kafka.fullname\" . }}-connect\n  labels: {{- include \"common.labels.standard\" . | nindent 4 }}\n    app.kubernetes.io/component: connector\nspec:\n  replicas: 1\n  selector:\n    matchLabels: {{- include \"common.labels.matchLabels\" . | nindent 6 }}\n      app.kubernetes.io/component: connector\n  template:\n    metadata:\n      labels: {{- include \"common.labels.standard\" . | nindent 8 }}\n        app.kubernetes.io/component: connector\n    spec:\n      containers:\n        - name: connect\n          image: costache2mihai/kafkamongo\n          imagePullPolicy: IfNotPresent\n          ports:\n            - name: connector\n              containerPort: 8083\n          volumeMounts:\n            - name: configuration\n              mountPath: /bitnami/kafka/config\n      volumes:\n        - name: configuration\n          configMap:\n            name: {{ include \"kafka.fullname\" . }}-connect\n": template: kafka/templates/extra-list.yaml:4:11: executing "kafka/templates/extra-list.yaml" at <include "kafka.fullname" .>: error calling include: template: no template "kafka.fullname" associated with template "gotpl"
helm.go:84: [debug] template: kafka/templates/extra-list.yaml:3:3: executing "kafka/templates/extra-list.yaml" at <include "common.tplvalues.render" (dict "value" . "context" $)>: error calling include: template: kafka/charts/common/templates/_tplvalues.tpl:9:12: executing "common.tplvalues.render" at <tpl .value .context>: error calling tpl: error during tpl function execution for "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {{ include \"kafka.fullname\" . }}-connect\n  labels: {{- include \"common.labels.standard\" . | nindent 4 }}\n    app.kubernetes.io/component: connector\nspec:\n  replicas: 1\n  selector:\n    matchLabels: {{- include \"common.labels.matchLabels\" . | nindent 6 }}\n      app.kubernetes.io/component: connector\n  template:\n    metadata:\n      labels: {{- include \"common.labels.standard\" . | nindent 8 }}\n        app.kubernetes.io/component: connector\n    spec:\n      containers:\n        - name: connect\n          image: costache2mihai/kafkamongo\n          imagePullPolicy: IfNotPresent\n          ports:\n            - name: connector\n              containerPort: 8083\n          volumeMounts:\n            - name: configuration\n              mountPath: /bitnami/kafka/config\n      volumes:\n        - name: configuration\n          configMap:\n            name: {{ include \"kafka.fullname\" . }}-connect\n": template: kafka/templates/extra-list.yaml:4:11: executing "kafka/templates/extra-list.yaml" at <include "kafka.fullname" .>: error calling include: template: no template "kafka.fullname" associated with template "gotpl"
```
