### ISSUE TITLE
[bitnami/mysql] `MYSQL_EXTRA_FLAGS` with `--lower-case-table-names=1` can not start

### ISSUE THREAD

**Issue by icefery** [bitnami/charts#15360]
### Name and Version

bitnami/mysql:8.0.31-debian-11-r15

### What architecture are you using?

amd64

### What steps will reproduce the bug?

docker-compose: 
```yaml
services:
  mysql:
    image: docker.io/bitnami/mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/bitnami/mysql/data
    environment:
      MYSQL_EXTRA_FLAGS: '--lower-case-table-names=1'
      MYSQL_ROOT_PASSWORD: root
volumes:
  mysql-data:
```

### What do you see instead?
```
mysql 09:51:49.40
mysql 09:51:49.40 Welcome to the Bitnami mysql container
mysql 09:51:49.40 Subscribe to project updates by watching https://github.com/bitnami/containers
mysql 09:51:49.40 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mysql 09:51:49.41
mysql 09:51:49.41 INFO  ==> ** Starting MySQL setup **
mysql 09:51:49.43 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 09:51:49.44 INFO  ==> Initializing mysql database
mysql 09:51:49.46 INFO  ==> Updating 'my.cnf' with custom configuration
mysql 09:51:49.47 INFO  ==> Setting slow_query_log option
mysql 09:51:49.48 INFO  ==> Setting long_query_time option
mysql 09:51:49.48 INFO  ==> Installing database
mysql 09:51:54.36 INFO  ==> Starting mysql in background
mysql 10:01:55.18 ERROR ==> MySQL failed to start
```

### Additional information

I have opened an issue at [https://github.com/bitnami/containers/issues/16211](https://github.com/bitnami/containers/issues/16211), but the solution did'nt help all. I'm sorry unable to find out the reason, could anyone help?
