### ISSUE TITLE
Error with Postgres custom user

### ISSUE THREAD

**Issue by ktw1016** [bitnami/charts#15378]
### Name and Version

bitnami/postgresql:12.1.6

### What architecture are you using?

None

### What steps will reproduce the bug?

Deployed bitnami/postgresql:12.1.6 with this config for auth:
```yaml
auth:
  enablePostgresUser: true
  username: antimatter_users
  existingSecret: antimatter-iceberg-catalog-db
  secretKeys:
    adminPasswordKey: postgresql-password
    userPasswordKey: postgresql-unprivileged-password
primary:
  extraEnvVars:
    - name: POSTGRES_MAX_CONNECTIONS
      value: "500"
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          key: postgresql-password
          name: antimatter-iceberg-catalog-db
```
_Needed `PGPASSWORD` environment variable as I'm running a init sql script using postStart lifecycle hook_ 

I can access postgres fine and do all of my operations as expected. Problem is that, in the logs, I'm getting errors:
```
2023-03-07 20:03:10.162 GMT [452] FATAL:  password authentication failed for user "antimatter_users"
2023-03-07 20:03:10.162 GMT [452] DETAIL:  Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
```

### What is the expected behavior?

Log from Postgresql does not contain any errors

### What do you see instead?
```
2023-03-07 20:03:10.162 GMT [452] FATAL:  password authentication failed for user "antimatter_users"
2023-03-07 20:03:10.162 GMT [452] DETAIL:  Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
```
