### ISSUE TITLE
[thanos] ServiceMonitors do not support HTTPS, while the rest of the chart does

### ISSUE THREAD

**Issue by lorenzo-biava** [bitnami/charts#15395]
### Name and Version

bitnami/thanos latest

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Enable https (with the `https.enabled` value or manually, adding config to httpConfig)
2. Scraping of the components fail, because the ServiceMonitor doesn't use scheme: https, and doesn't allow to override of those fields either.

### What is the expected behavior?

The ServiceMonitors:
A) contain "scheme: https"
B) allow to specify additional properties like
```yaml
    tlsConfig: 
      serverName: ${tls_scrape_server_name}
      caFile: ${tls_scrape_ca_file}
```
See https://github.com/bitnami/charts/blob/6c40169ffa706bcc414784818eed99beb425a7f3/bitnami/thanos/templates/query/servicemonitor.yaml#L22

### What do you see instead?

Prometheus scraping fails, because it connects via HTTP, and gets "server returned HTTP status 400 Bad Request"
