### ISSUE TITLE
[bitnami/logstash] Can't create NodePort through logstash helm chart

### ISSUE THREAD

**Issue by joshua-heidrich** [bitnami/charts#15393]
### Name and Version

bitnami/logstash 5.1.15

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Installing Logstash through Helm-Chart with service.type=NodePort

### Are you using any custom parameters or values?

```
service:
  type: NodePort
  ports:
    - name: gelf
      port: 1234
      targetPort: 1234
      nodePort: 30345
      protocol: UDP
```

### What is the expected behavior?

The install works.

### What do you see instead?

`Error: UPGRADE FAILED: failed to create resource: Service "logstash-headless" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'`

### Additional information

I think I already have the source of the problem. There is this section in headless-svc.yaml:
```
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    {{- include "common.tplvalues.render" (dict "value" .Values.service.ports "context" $) | nindent 4 }}
  selector: {{ include "common.labels.matchLabels" . | nindent 4 }}
```
It uses  `.Values.service.ports` which I have defined as follows:
```
    - name: gelf
      port: 1234
      targetPort: 1234
      nodePort: 30345
      protocol: UDP
```
I need the "nodePort"-part because I want to create a Nodeport. But this uses the NodePort port to create a ClusterIP which obviously does not work.
