### ISSUE TITLE
[Contour] Envoy not exposing all SecurityContext fields breaks security policies

### ISSUE THREAD

**Issue by UXabre** [bitnami/charts#15392]
### Name and Version

bitnami/contour:11.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Using the values:
```yaml
contour:
    containerSecurityContext:
      runAsGroup: 1000
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: "RuntimeDefault"
      allowPrivilegeEscalation: false
  envoy:
    containerSecurityContext:
      runAsGroup: 1000
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: "RuntimeDefault"
      allowPrivilegeEscalation: false
```
It seems not all securitycontext fields are exposed (some make more sense for a pod than others, depending on what the use case is). I've set a quite hard policy on my AKS cluster which needs a seccompProfile to be set.
2. In envoy at least, I saw that not all fields are integrally copied. For contour, it seems that a nice trace-off was found, because I can either specify enabled and some fields or directly set my securityContext.
3. Not setting it prevents it from being deployed

### Are you using any custom parameters or values?

See my values above

### What is the expected behavior?

That I can set all securitycontext fields

### What do you see instead?

Not all securitycontext fields are copied verbatim
