### ISSUE TITLE
KONG hostNetwork/hostPort

### ISSUE THREAD

**Issue by busyboy77** [bitnami/charts#15412]
### Name and Version

bitnami/kong:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I wanted to deploy the KONG IC without using any external/internal load-balancer, but I couldn't find any option to deploy using hostPorts/hostNetwork options

like below:

```yaml
  ## Use host ports 80 and 443
  ## Disabled by default
  hostPort:
    # -- Enable 'hostPort' or not
    enabled: true
    ports:
      # -- 'hostPort' http port
      http: 80
      # -- 'hostPort' https port
      https: 443
```
This allows us to deploy the KONG without any load-balancer added in the cluster to assign an IP address.

Regards,
