### ISSUE TITLE
[bitnami/etcd] Can't configure a cluster to use HTTPS/TLS for Server/Client communications/advertisements

### ISSUE THREAD

**Issue by pchambre** [bitnami/charts#15418]
### Name and Version

bitnami/etcd-8.7.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

- Deployed to GKE
- Values
```
replicaCount: 3
initialClusterState: new
logLevel: debug
service:
  type: LoadBalancer
auth:
  rbac:
    enabled: true
    rootPassword: password
  client:
    secureTransport: true
    existingSecret: etcd-ssl-wildcard
    certFilename: tls.crt
    certKeyFilename: tls.key
  peer:
    secureTransport: true
    useAutoTLS: true
```
- Cluster nodes go into crash loops - no details about what about the certificate they don't like

The certificate, in this case, is an internal PKI pem with key with SAN for 0.0.0.0 (as the AutoTLS does), plus *.<namespace>.svc.cluster.local and *.my-release-etcd-headless.<namespace>.svc.cluster.local. The certificate also includes TLS Server Auth, digital Signature, and key encipherment. 
```
The logs show: {"level":"info","ts":"2023-03-10T00:40:52.385Z","caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_KEY_FILE","variable-
value":"/opt/bitnami/etcd/certs/client/tls.key"}
```
as the last event where they hang for a while before restarting.

### Are you using any custom parameters or values?

Yes, see above. Attempting to set a custom certificate for server to client TLS.

### What is the expected behavior?

Cluster should start, or should at least log some details about why it can't start. 

Documentation on how to enable TLS would be nice.

### What do you see instead?

Cluster crash loop. Nodes restart ever 200 seconds or so.
