### ISSUE TITLE
[bitnami/memcached] metrics containerSecurityContext missing from STS

### ISSUE THREAD

**Issue by dszakallas** [bitnami/charts#15449]
### Name and Version

bitnami/memcached 6.3.11

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The `metrics.containerSecurityContext` configuration is missing from the stateful set template.

### Are you using any custom parameters or values?

```yaml
metrics:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
```

### What is the expected behavior?

Security context applied to `metrics` container

### What do you see instead?

Security context missing from `metrics` container
