### ISSUE TITLE
[bitnami/rabbitmq] Failed readiness does not result in replaced pod

### ISSUE THREAD

**Issue by zenbones** [bitnami/charts#15459]
### Name and Version

bitnami/rabitmq 11.1.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Not sure how to reproduce because in general the chart has been very stable for us. However, we had a failure where one of the rabbitmq pods (we have a cluster of 2) showed 0/1 readiness with a simple kubectl get pods -n <namespace>. This could have been due to the underlying node, or some other failure in any number of systems. What I find curious is that the pod was not replaced by k8s automatically, and I assume that's due to the configuration given to k8s by the helm chart?

### Are you using any custom parameters or values?

```
rabbitmq:
  nodeSelector:
    kubernetes.io/os: linux
    silo: production-gxl
  podAntiAffinityPreset: soft
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "topology.kubernetes.io/zone"
      whenUnsatisfiable:  "ScheduleAnyway"
      labelSelector:
        matchLabels:
          app.kubernetes.io/instance: "{{ .Release.Name }}"
          app.kubernetes.io/name: "rabbitmq"
  podDisruptionBudget:
    enabled: true
    maxUnavailable: "1"
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-name: "{{ .Release.Name }}-epicenter-eks-rabbitmq"
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
      external-dns.alpha.kubernetes.io/hostname: "{{ .Release.Name }}-epicenter-eks-rabbitmq.forio.internal"
      external-dns.alpha.kubernetes.io/ttl: "3600"
  replicaCount: 2
  podAnnotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    ad.datadoghq.com/rabbitmq.check_names: '["rabbitmq"]'
    ad.datadoghq.com/rabbitmq.init_configs: '[{}]'
    ad.datadoghq.com/rabbitmq.instances: |
      [
        {
          "rabbitmq_api_url": "http://%%host%%:15672/api/",
          "username": "epicenter",
          "password": "{{ .Ansible.vault_epicenter_rabbitmq_password }}"
        }
      ]
  auth:
    username: "epicenter"
    password: "{{ .Ansible.vault_epicenter_rabbitmq_password }}"
  persistence:
    enabled: true
    storageClass: gp2
    accessMode: ReadWriteOnce
    size: 2Gi
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenDeleted: Delete
    whenScaled: Delete
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
```

### What is the expected behavior?

I assumed that a pod failing readiness would be replaced. If there was an underlying condition it might be replaced repeatedly in a loop of failing pod, but t was not replaced at all.

### What do you see instead?

Pod just sits there unready.
