### ISSUE TITLE
There is a gap on the Grafana Logs Volume chart when run a query

### ISSUE THREAD

**Issue by ercansayici** [bitnami/charts#15466]
### Name and Version

bitnami/grafana-loki 2.5.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Grafana version: 9.4.0
Data source type & version: Loki 2.7.1 Distributed deployment (use Memcached)
OS Grafana is installed on: Linux
User OS & Browser: Windows, Mac

### Are you using any custom parameters or values?
```yaml
 configuration: |
    auth_enabled: false

    server:
      http_listen_port: {{ .Values.loki.containerPorts.http }}

    common:
      compactor_address: http://{{ include "grafana-loki.compactor.fullname" . }}:{{ .Values.compactor.service.ports.http }}

    distributor:
      ring:
        kvstore:
          store: memberlist

    memberlist:
      join_members:
        - {{ include "grafana-loki.gossip-ring.fullname" . }}

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 30m
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_retain_period: 1m
      max_transfer_retries: 0
      wal:
        dir: {{ .Values.loki.dataDir }}/wal

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m


    schema_config:
      configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: aws
        schema: v11
        index:
          prefix: index_
          period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/boltdb-shipper-active
        cache_location: /loki/boltdb-shipper-cache
        cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: s3
      aws:
        bucketnames: xxxxxxxxxxxxxxxxxxxxxxx
        region: xxxxxxxxxxxxxxxxx
        access_key_id: xxxxxxxxxxxxxxxxxxx
        secret_access_key: xxxxxxxxxxxxxxx
        s3forcepathstyle: true

      # boltdb_shipper:
      #   shared_store: filesystem
      #   active_index_directory: {{ .Values.loki.dataDir }}/loki/index
      #   cache_location: {{ .Values.loki.dataDir }}/loki/cache
      #   cache_ttl: 168h
      #   {{- if .Values.indexGateway.enabled }}
      #   index_gateway_client:
      #     server_address: {{ (printf "dns:///%s:9095" (include "grafana-loki.index-gateway.fullname" .)) }}
      #   {{- end }}
      # filesystem:
      #   directory: {{ .Values.loki.dataDir }}/chunks

      index_queries_cache_config:
        {{- if .Values.memcachedindexqueries.enabled }}
        memcached:
          batch_size: 200
          parallelism: 200
        memcached_client:
          consistent_hash: true
          addresses: dns+{{ include "grafana-loki.memcached-index-queries.host" . }}
          service: http
        {{- end }}

    chunk_store_config:
      max_look_back_period: 0s
      {{- if .Values.memcachedchunks.enabled }}
      chunk_cache_config:
        memcached:
          batch_size: 200
          parallelism: 200
        memcached_client:
          consistent_hash: true
          addresses: dns+{{ include "grafana-loki.memcached-chunks.host" . }}
      {{- end }}
      {{- if .Values.memcachedindexwrites.enabled }}
      write_dedupe_cache_config:
        memcached:
          batch_size: 200
          parallelism: 200
        memcached_client:
          consistent_hash: true
          addresses: dns+{{ include "grafana-loki.memcached-index-writes.host" . }}
      {{- end }}

    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s

    query_range:
      align_queries_with_step: true
      max_retries: 5
      cache_results: true
      results_cache:
        cache:
          {{- if .Values.memcachedfrontend.enabled }}
          memcached_client:
            consistent_hash: true
            addresses: dns+{{ include "grafana-loki.memcached-frontend.host" . }}
            max_idle_conns: 16
            timeout: 500ms
            update_interval: 1m
          {{- else }}
          embedded-cache:
            enabled: true
            max_size_items: 1024
            validity: 24h
          {{- end }}
    {{- if not .Values.queryScheduler.enabled }}
    frontend_worker:
      frontend_address: {{ include "grafana-loki.query-frontend.fullname" . }}:{{ .Values.queryFrontend.service.ports.grpc }}
    {{- end }}

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
      tail_proxy_url: http://{{ include "grafana-loki.querier.fullname" . }}:{{ .Values.querier.service.ports.http }}

    compactor:
      shared_store: s3


    ruler:
      storage:
        type: local
        local:
          directory: {{ .Values.loki.dataDir }}/conf/rules
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      external_url: xxxxxxxxxxxxxxxxxxxxxx
      alertmanager_url: xxxxxxxxxxxxxxxxxxxxx
      enable_alertmanager_v2: true
      enable_api: true
```
### What is the expected behavior?

see the all logs volume on Grafana chart.

### What do you see instead?

When I run a query on Grafana to see some logs from my app, even though the logs are gathered from Loki and can be seen in the logs section, some of the logs are not present on the Logs Volume Chart (there is a gap). and after some time passed this gap disappears. (please see the screenshots below, I took screenshots at 1-hour intervals)

### Additional information

![8-15](https://user-images.githubusercontent.com/51846261/224237898-dcbd1737-08da-4104-9e61-32d9851a8c1d.png)
![9-15](https://user-images.githubusercontent.com/51846261/224237915-097c7d1c-80ec-4c58-b647-88f388a067c8.png)
![10-15](https://user-images.githubusercontent.com/51846261/224237923-a1653be7-47dc-40ad-817b-7dd93fc01f95.png)
![1-15](https://user-images.githubusercontent.com/51846261/224237985-08fbeca1-c889-4891-9554-0c80f636e0d3.png)

Notes:
- Actually, logs are still in there.
- The gap always appears near the query time.
- The gap only appears when the number of logs is huge ( > 5000 logs per second).
- if the size of the logs is small, the gap does not appear.
