### ISSUE TITLE
Keycloak not working behind AWS aws load balancer controller

### ISSUE THREAD

**Issue by zibuyule** [bitnami/charts#15462]
### Name and Version

bitnami/keycloak --version 20.0.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. helm upgrade --install keycloak ./  -n default
2. The internal access address of k8s is https://keycloak.default.svc.cluster.local.  It is available.
3. The internet access address of k8s is https://keycloak.sredevops.me. If http, It is available; if https, it is not available.

![pod-https](https://user-images.githubusercontent.com/5792519/224480986-cbdd95cf-525d-4f52-a366-7658f864ac85.png)
![internet-access-http](https://user-images.githubusercontent.com/5792519/224481055-0e65204f-fe5a-48f2-9aba-75e9c32d099e.png)
![502-error](https://user-images.githubusercontent.com/5792519/224481134-14101b04-455a-4f9c-b629-b246f3a80c7d.png)

### Are you using any custom parameters or values?

Ingress in values.com is not enabled.
I created an ingress resource on AWS.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  #namespace: istio-system
  namespace: default
  name: istio-ingressgateway-alb-for-keycloak
  labels:
    app: ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-1:494021538801:certificate/03571561-dc82-4f6f-a5b1-33fa67cf3f28
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
spec:
  rules:
    - host: "keycloak.sredevops.me"
      http:
        paths:
        - backend:
            service:
              #name: istio-ingressgateway
              name: "keycloak"
              port:
                number: 443
          path: /
          pathType: Prefix
```

### What is the expected behavior?

I expect https://keycloak.sredevops.com Is accessible.

### What do you see instead?

Nothing.
