### ISSUE TITLE
[bitnami/postgresql-ha] PgPool-II missing 'backend_application_name' setting in pgpool.conf results in replication issues

### ISSUE THREAD

**Issue by dminca** [bitnami/charts#15469]
### Name and Version

bitnami/postgresql-ha 11.1.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. deploy chart with provided values
2. create a test DB
3. fill in some data in test DB
4. fire multiple `pg_dump` commands at irregular time intervals and connect to `pg-pool` (this is your `PGHOST`)
5. see error `FATAL:  failed to read kind from backend`

### Are you using any custom parameters or values?

```yaml
fullnameOverride: pg
global:
  imageRegistry: registry-proxy.example.com
  postgresql:
    existingSecret: postgresql
  pgpool:
    existingSecret: postgresql-pgpool
postgresql:
  extendedConf: |-
    max_locks_per_transaction = 1024
  maxConnections: "500"
  image:
    tag: 14.5.0-debian-11-r14
pgpool:
  image:
    tag: 4.3.3-debian-11-r9
  replicaCount: 3
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - postgresql-ha
          topologyKey: "kubernetes.io/hostname"
metrics:
  image:
    tag: 0.11.1-debian-11-r8
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
persistence:
  enabled: true
  size: 200Gi
volumePermissions:
  enabled: true
```

### What is the expected behavior?

```
Type "help" for help.

postgres=# show pool_nodes;
 node_id |                hostname                | port | status | pg_status | lb_weight |  role   | pg_role | select_cnt | load_balance_node | replication_delay | replication_state | replication_sync_state | last_status_change
---------+----------------------------------------+------+--------+-----------+-----------+---------+---------+------------+-------------------+-------------------+-------------------+------------------------+---------------------
 0       | pg-postgresql-0.pg-postgresql-headless | 5432 | up     | up        | 0.333333  | primary | primary | 93         | false             | 0                 |  0                | 0                      | 2023-02-14 13:02:35
 1       | pg-postgresql-1.pg-postgresql-headless | 5432 | up     | up        | 0.333333  | standby | standby | 62         | false             | 0                 |  0                | 0                      | 2023-02-14 13:03:15
 2       | pg-postgresql-2.pg-postgresql-headless | 5432 | up     | up        | 0.333333  | standby | standby | 86         | true              | 0                 |  0                | 0                      | 2023-02-14 13:03:15
(3 rows)
```

In **streaming replication mode** it's mandatory that PgPool-II reports replication state in columns `replication_state` and `replication_sync_state` as per [their docu](https://www.pgpool.net/docs/42/en/html/runtime-config-backend-settings.html)

### What do you see instead?

Encountering problems with streaming replication during a `pg_dump` operation. As seen below, the columns `replication_state` and `replication_sync_state` are not populated which is not compliant with PgPool-II configuration recommendations, as per [this support document](https://www.pgpool.net/docs/42/en/html/runtime-config-backend-settings.html) which clearly states _in other than streaming replication mode, this parameter does not need to be set_. Setting `backend_application_name(string)` mitigates this PgPool-II issue.

```
psql (14.5)
Type "help" for help.

postgres=# show pool_nodes;
 node_id |                hostname                | port | status | pg_status | lb_weight |  role   | pg_role | select_cnt | load_balance_node | replication_delay | replication_state | replication_sync_state | last_status_change
---------+----------------------------------------+------+--------+-----------+-----------+---------+---------+------------+-------------------+-------------------+-------------------+------------------------+---------------------
 0       | pg-postgresql-0.pg-postgresql-headless | 5432 | up     | up        | 0.333333  | primary | primary | 93         | false             | 0                 |                   |                        | 2023-02-14 13:02:35
 1       | pg-postgresql-1.pg-postgresql-headless | 5432 | up     | up        | 0.333333  | standby | standby | 62         | false             | 0                 |                   |                        | 2023-02-14 13:03:15
 2       | pg-postgresql-2.pg-postgresql-headless | 5432 | up     | up        | 0.333333  | standby | standby | 86         | true              | 0                 |                   |                        | 2023-02-14 13:03:15
(3 rows)
```

### Additional information

This issue was raised with PgPool-II community which provided 3 solutions to mitigate, you can [see the question](https://www.pgpool.net/pipermail/pgpool-general/2023-March/008694.html) in the mailing list archive and [these are their mitigation proposals](https://www.pgpool.net/pipermail/pgpool-general/2023-March/008696.html).

In this particular case, the error is present while issuing a `pg_dump` through the `pg-pool` `Service`. PgPool-II docs recommend setting `backend_application_name (string)` in `pgpool.conf`, unfortunately I couldn't find a way to set this in the Helm chart, perhaps you can guide me?

**Comment by aoterolorenzo** [comment]
Hi @dminca, I will create an internal task to address the issue you found and apply one of the proposed solutions upstream. We will reach you back once one of my teammates address the task.

**Comment by aoterolorenzo** [comment]
Hi @dminca,

Seems you can set the environment variable `PGPOOL_BACKEND_APPLICATION_NAMES` as an extra env var:

```
pgpool.extraEnvVars: 
    - name: PGPOOL_BACKEND_APPLICATION_NAMES
       value: name1,name2
```

You can see more about the different configuration options here https://github.com/bitnami/containers/tree/main/bitnami/pgpool#configuration

Also, you could specify an entire `pgpool.conf` file through the `pgpool.configuration` chart value.

```
  ## @param pgpool.configuration Pgpool configuration
  ## You can use this parameter to specify the content for pgpool.conf
  ## Otherwise, a repmgr.conf will be generated based on the environment variables
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/pgpool#configuration
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/pgpool#configuration-file
  ## Example:
  ## configuration: |-
  ##   listen_addresses = '*'
  ##   port = '5432'
  ##   ...
  ##
```

**Comment by dminca** [comment]
I've tried updating the 

```yml
pgpool:
  extraEnvVars:
  - name: PGPOOL_BACKEND_APPLICATION_NAMES
    value: server0,server1,server2
```

with no results on the replication fields whatsoever

```
postgres=# show pool_nodes;
 node_id |                hostname                | port | status | pg_status | lb_weight |  role   | pg_role | select_cnt | load_balance_node | replication_delay | replication_state | replication_sync_state | last_status_change
---------+----------------------------------------+------+--------+-----------+-----------+---------+---------+------------+-------------------+-------------------+-------------------+------------------------+---------------------
 0       | pg-postgresql-0.pg-postgresql-headless | 5432 | up     | up        | 0.333333  | standby | standby | 2689       | false             | 0                 |                   |                        | 2023-03-20 12:27:11
 1       | pg-postgresql-1.pg-postgresql-headless | 5432 | up     | up        | 0.333333  | primary | primary | 5987       | true              | 0                 |                   |                        | 2023-03-20 12:27:11
 2       | pg-postgresql-2.pg-postgresql-headless | 5432 | up     | up        | 0.333333  | standby | standby | 3757       | false             | 0                 |                   |                        | 2023-03-20 12:27:11
(3 rows)
```
