### ISSUE TITLE
[bitnami/clickhouse] loadBalancerSourceRanges list rendering is broken

### ISSUE THREAD

**Issue by alexandrujieanu** [bitnami/charts#15477]
### Name and Version

bitnami/clickhouse 3.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

This is similar to https://github.com/bitnami/charts/issues/14834 in the nginx chart and https://github.com/bitnami/charts/issues/14439 in the nginx-ingress-controller chart.

### What is the expected behavior?

```yaml
spec:
  loadBalancerSourceRanges:
    - 1.2.3.4/32
    - 5.6.7.8/32
```

### What do you see instead?

```
Service "clickhouse" is invalid: spec.LoadBalancerSourceRanges: Invalid value: "[1.2.3.4/32 5.6.7.8/32]": must be a list of IP ranges. For example, 10.240.0.0/24,10.250.0.0/24
```
