### ISSUE TITLE
[bitnami/postgresql] Login to Postgresql db not possible when setting credentials via auth.existingSecret

### ISSUE THREAD

**Issue by mhanci92** [bitnami/charts#15493]
### Name and Version

bitnami/postgresql 11.9.13

### What architecture are you using?

None

### What steps will reproduce the bug?

I have a parent chart that includes the bitnami/postgresql chart as a subchart, like so:

```yaml
apiVersion: v2
name: postgres
description: A wrapper Helm chart for Postgres for Kubernetes
type: application
version: 1.0.0
dependencies:
- name: postgresql
  version: "11.9.13"
  repository: "https://charts.bitnami.com/bitnami"
```

The only reason for the parent-chart is to actually be able to use helm's templating mechanism for a dynamic ConfigMap that I handover to the postgresql chart as well as the management of secrets that I pass to the postgresql chart. To simplify the reproducable example, I leave the configmap out, which I would normally specify via `--set posgresql.primary.initdb.scriptsConfigMap=myConfigMap`.

When I install a release for this chart with the following command, it works fine:

```
cd <PARENT_CHART_PATH>

helm secrets install postgres-db . \
  -f values.yaml \
  -f secrets.yaml \
  -n my-test-ns --create-namespace \
  --set serviceName=my-service-name \
  --set dbUsername=myUsername \
  --set postgresql.auth.password=mysecretpassword \
  --set postgresql.auth.postgresPassword=postgres \
  --set postgresql.auth.database=my-db\
  --set postgresql.auth.username=myUsername
```
The uppermost two values being set are related to the parent chart. The secret file being passed via `-f secrets.yaml` is a helm-secrets file that I created with the help of the [helm-secrets plugin](https://github.com/jkroepke/helm-secrets) to be able to encrypt and decrypt k8s secrets on the fly when executing CLI commands. A k8s secret can of course also be created without the helm-secrets plugin via `kubectl create secret ...` and published to the given namespace beforehand.

Now what I mean by it works fine is that when I jump into the container within my pod, and enter

`psql -U postgres`

and subsequently enter the password into the password dialog:

`postgres`

 then, I'm able to successfully login to the db.

**Sidenote**: As it can be seen from the CLI wrapper command "secrets" provided by the helm-secrets plugin.

Though, I'm not able to login anymore when I specify a secret that contains credentials `auth.password` and `auth. postgresPassword` according to the [documentation](https://artifacthub.io/packages/helm/bitnami/postgresql/11.9.13#postgresql-common-parameters)

The command I make in order to install a release:

```bash
cd <PARENT_CHART_PATH>

helm secrets install postgres-db . \
  -f values.yaml \
  -f secrets.yaml \
  -n my-test-ns --create-namespace \
  --set serviceName=my-service-name \
  --set dbUsername=myUsername \
  --set postgresql.auth.existingSecret=postgres-secrets-my-service-name \
  --set postgresql.auth.database=my-db \
  --set postgresql.auth.username=myUsername
```

**IMPORTANT**: I always make sure that I remove existing PVC's, as I'm aware that the `helm uninstall` command won't remove those. Hence, that should not be the issue in my case.

To verify that the secret actually has the expected values for the passwords:

(I use [kubectx & kubens](https://github.com/ahmetb/kubectx). Hence I don't explicitly have to pass the namespace, as I'm locally already switched to my 'my-test-ns' via kubens)

```bash 
export POSTGRES_PASSWORD=$(kubectl get secrets postgres-secrets-my-service-name -o jsonpath="{.data.postgres-password}" | base64 --decode)

echo $POSTGRES_PASSWORD # returns: postgres

export POSTGRES_PASSWORD_2=$(kubectl get secrets postgres-secrets-my-service-name -o jsonpath="{.data.password}" | base64 --decode)

echo $POSTGRES_PASSWORD_2 # returns: mysecretpassword
```

Hence, the secret seems to have the intended content. I can also verify this when I jump into the container in the pod and print the env variables and their corresponding values via:

`env`

the k8s secret that I'm specifying, looks as follows:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets-{{ .Values.serviceName }}
type: Opaque
data:
  postgres-password: {{ .Values.secrets.auth.postgresPassword }}
  password: {{ .Values.secrets.auth.password }}
```

### Are you using any custom parameters or values?

```yaml
# Values for the parent chart
serviceName: "my-service-name"
dbUsername: "myDbUserName"

# Values for the postgres subchart
postgresql:

  image:
    debug: true
    pullPolicy: Always

  auth:
    database: "myDbName"
    username: "myDbUserName"

  primary:
    initdb:
      user: "postgres" # user to execute the sql script(s) within the specified configMap
```

### What is the expected behavior?

Successful login with the the superuser as well as the custom user.

### What do you see instead?

The following error when trying to login as the postgres superuser:

`psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  password authentication failed for user "postgres"`

as well as the following logs:

```
2023-03-14 13:20:01.972 GMT [10863] FATAL:  password authentication failed for user "postgres"
2023-03-14 13:20:01.972 GMT [10863] DETAIL:  Connection matched pg_hba.conf line 3: "local    all             all                                     md5"
```
