### ISSUE TITLE
[bitnami/grafana-operator] Failed to start grafana. error: migration failed (id = create migration_log table): database is locked

### ISSUE THREAD

**Issue by slawekww** [bitnami/charts#15494]
### Name and Version

bitnami/grafana-operator:2.7.22

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy helm chart with values - it uses persistent volume on AKS 1.24.6 using StorageClass=azurefile-csi.

2. Investigate `grafana-deployment` pod CrashLoopBackOff

### Are you using any custom parameters or values?

```yaml
commonLabels:
  app: grafana-operator
operator:
  image:
    tag: 4.9.0-debian-11-r6
  enabled: true
  replicaCount: 1
  podLabels:
    app: grafana-operator
  startupProbe:
    periodSeconds: 30
    timeoutSeconds: 10
  podSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    fsGroup: 1001
    supplementalGroups: []
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
  rbac:
    enabled: false
  serviceAccount:
    enabled: false
  scanAllNamespaces: false
  scanNamespaces:
    - management
    - standard
    - standard-test
    - win-standard-workload
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
grafana:
  image:
    tag: 9.3.6-debian-11-r10
  enabled: true
  podSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 0
    runAsNonRoot: true
    fsGroup: 1001
    supplementalGroups: []
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 0
    privileged: false
    runAsNonRoot: true
    allowPrivilegeEscalation: false
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  replicaCount: 1
  ingress:
    enabled: false
  config:
    server:
      root_url: https://grafana-global.mydomain.com/
    auth:
      disable_login_form: true
    auth.generic_oauth:
      enabled: true
      allow_sign_up: true
      client_id: '$__file{/etc/secrets/auth_generic_oauth/client_id}'
      client_secret: '$__file{/etc/secrets/auth_generic_oauth/client_secret}'
      scopes: openid email profile
      auth_url: https://login.microsoftonline.com/id/oauth2/authorize
      token_url: https://login.microsoftonline.com/id/oauth2/token
      role_attribute_path: contains(groups[*], 'id') && 'Admin' || contains(groups[*], 'id2') && 'Admin' || contains(groups[*], id') && 'Editor' || ''
      role_attribute_strict: true
  dashboardLabelSelectors:
    - matchLabels:
        app.kubernetes.io/instance: grafana-dashboard
  extraVolumes:
    - name: grafana-sso-client-secret
      secret:
        secretName: grafana-sso-client-secret
        defaultMode: 0440
        items:
          - key: client_id
            path: client_id
          - key: client_secret
            path: client_secret
  extraVolumeMounts:
    - name: grafana-sso-client-secret
      mountPath: /etc/secrets/auth_generic_oauth
      readOnly: true
  persistence:
    enabled: true
    storageClass: azurefile-csi
    accessModes:
      - ReadWriteMany
    size: 5Gi
    annotations:
      backup.velero.io/backup-volumes: grafana-data
```

### What is the expected behavior?

Grafana deployment pod to start successfully.

### What do you see instead?

Error is seen:

```
Defaulted container "grafana" out of: grafana, grafana-plugins-init (init)
grafana 14:27:55.90
grafana 14:27:55.90 Welcome to the Bitnami grafana container
grafana 14:27:55.90 Subscribe to project updates by watching https://github.com/bitnami/containers
grafana 14:27:55.90 Submit issues and feature requests at https://github.com/bitnami/containers/issues
grafana 14:27:55.91
grafana 14:27:55.92 INFO  ==> Ensuring /etc/grafana/grafana.ini points to /opt/bitnami/grafana/conf/grafana.ini
grafana 14:27:55.92 INFO  ==> Ensuring /var/lib/grafana points to /opt/bitnami/grafana/data
grafana 14:27:55.93 INFO  ==> Ensuring /var/log/grafana points to /opt/bitnami/grafana/logs
grafana 14:27:55.93 INFO  ==> Ensuring /etc/grafana/provisioning points to /opt/bitnami/grafana/conf/provisioning
grafana 14:27:55.94 INFO  ==> ** Grafana setup finished! **

grafana 14:27:55.94 INFO  ==> ** Starting Grafana **
Error checking server process execution privilege. error: could not get current OS user to detect process privileges
logger=sqlstore t=2023-03-14T14:27:56.404306889Z level=warn msg="SQLite database file has broader permissions than it should" path=/opt/bitnami/grafana/data/grafana.db mode=-rwxrwxrwx expected=-rw-r-----
Failed to start grafana. error: migration failed (id = create migration_log table): database is locked
migration failed (id = create migration_log table): database is locked
```

### Additional information

It is only one replica of grafana-deployment and pvc is created by grafana-operator.

PVC contains labels like helm.sh/chart which would cause re-creation of pvc in case of upgrade helm chart.

```yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      backup.velero.io/backup-volumes: grafana-data
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: file.csi.azure.com
      volume.kubernetes.io/storage-provisioner: file.csi.azure.com
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: grafana-operator
      app.kubernetes.io/instance: grafana-operator-global
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana-operator
      helm.sh/chart: grafana-operator-2.7.22
```

It may be good to allow providing existing persistent volume claim to CR grafana instead of persistent volume only.
