### ISSUE TITLE
PR 14912 introduces breaking changes for helm-operator during reconciling of resources

### ISSUE THREAD

**Issue by aneagoe** [bitnami/charts#15501]
### Name and Version

bitnami/postgresql 12.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

It looks like PR: https://github.com/bitnami/charts/pull/14893 introduces a breaking change for `helm-operator`. Note that helm itself appears to behave just fine (tested with helm 3.7.0). This breaks on `helm-operator` version `1.4.4` (which is based off helm 3.7.0).
This happens across all charts that include this change (so far tested on `postgresql` and `mysql`).

Steps to reproduce:

1. Create namespace and secret
```
kubectl create ns test-postgresql
kubectl create secret generic test-postgresql --from-literal=postgres-password=test -n test-postgresql
```
2. Deploy helm release with following content:
```yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: test-postgresql
  namespace: test-postgresql
spec:
  releaseName: test-postgresql
  targetNamespace: test-postgresql
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: postgresql
    version: 12.2.0 # or any version above 12.2.0
  values:
    auth:
      existingSecret: test-postgresql
      database: test
    primary:
      persistence:
        size: 8Gi
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
      extendedConfiguration: |
        shared_buffers = 1GB
        max_connections = 1000
        log_min_duration_statement = 100
        log_checkpoints = on
        log_lock_waits = on
        log_temp_files = 0
        log_autovacuum_min_duration = 0
        log_error_verbosity = default
    volumePermissions:
      enabled: false
    shmVolume:
      enabled: false
    resources:
      limits:
        memory: "4Gi"
        cpu: "2"
      requests:
        memory: "4Gi"
        cpu: "2"
    metrics:
      enabled: true
      containerSecurityContext:
        enabled: false
```
3. Observe behavior after the `helm-operator` attempts to reconcile the resource. 

### Are you using any custom parameters or values?

```yaml
auth:
  existingSecret: test-postgresql
  database: test
primary:
  persistence:
    size: 8Gi 
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  extendedConfiguration: |
    shared_buffers = 1GB 
    max_connections = 1000
    log_min_duration_statement = 100 
    log_checkpoints = on
    log_lock_waits = on
    log_temp_files = 0 
    log_autovacuum_min_duration = 0 
    log_error_verbosity = default
volumePermissions:
  enabled: false
shmVolume:
  enabled: false
resources:
  limits:
    memory: "4Gi"
    cpu: "2" 
  requests:
    memory: "4Gi"
    cpu: "2" 
metrics:
  enabled: true
  containerSecurityContext:
    enabled: false
```

### What is the expected behavior?

Reconciling the resources by `helm-operator` should succeed with no changes.

### What do you see instead?

Initial `kubectl get hr -n test-postgresql` shows:
```
NAME              RELEASE           PHASE       STATUS     MESSAGE                                                                           AGE
test-postgresql   test-postgresql   Succeeded   deployed   Release was successful for Helm release 'test-postgresql' in 'test-postgresql'.   82s
```
After a reconcile cycle of `helm-operator`:
```
NAME              RELEASE           PHASE    STATUS     MESSAGE                                                                   AGE
test-postgresql   test-postgresql   Failed   deployed   Release failed for Helm release 'test-postgresql' in 'test-postgresql'.   3m6s
```

After the failure, `kubectl describe hr test-postgresql -n test-postgresql` shows the following:
```yaml
Name:         test-postgresql
Namespace:    test-postgresql
Labels:       <none>
Annotations:  <none>
API Version:  helm.fluxcd.io/v1
Kind:         HelmRelease
Metadata:
  Creation Timestamp:  2023-03-14T16:38:29Z
  Generation:          1
  Managed Fields:
    API Version:  helm.fluxcd.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:chart:
          .:
          f:name:
          f:repository:
          f:version:
        f:releaseName:
        f:targetNamespace:
        f:values:
          .:
          f:auth:
            .:
            f:database:
            f:existingSecret:
          f:metrics:
            .:
            f:containerSecurityContext:
              .:
              f:enabled:
            f:enabled:
          f:primary:
            .:
            f:containerSecurityContext:
              .:
              f:enabled:
            f:extendedConfiguration:
            f:persistence:
              .:
              f:size:
            f:podSecurityContext:
              .:
              f:enabled:
          f:resources:
            .:
            f:limits:
              .:
              f:cpu:
              f:memory:
            f:requests:
              .:
              f:cpu:
              f:memory:
          f:shmVolume:
            .:
            f:enabled:
          f:volumePermissions:
            .:
            f:enabled:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2023-03-14T16:38:29Z
    API Version:  helm.fluxcd.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:lastAttemptedRevision:
        f:observedGeneration:
        f:phase:
        f:releaseName:
        f:releaseStatus:
        f:revision:
    Manager:         helm-operator
    Operation:       Update
    Subresource:     status
    Time:            2023-03-14T16:38:52Z
  Resource Version:  1466713088
  UID:               859ab19b-b62d-4cbb-9705-9437f0de1803
Spec:
  Chart:
    Name:            postgresql
    Repository:      https://charts.bitnami.com/bitnami
    Version:         12.2.0
  Release Name:      test-postgresql
  Target Namespace:  test-postgresql
  Values:
    Auth:
      Database:         test
      Existing Secret:  test-postgresql
    Metrics:
      Container Security Context:
        Enabled:  false
      Enabled:    true
    Primary:
      Container Security Context:
        Enabled:               false
      Extended Configuration:  shared_buffers = 1GB
max_connections = 1000
log_min_duration_statement = 100
log_checkpoints = on
log_lock_waits = on
log_temp_files = 0
log_autovacuum_min_duration = 0
log_error_verbosity = default

      Persistence:
        Size:  8Gi
      Pod Security Context:
        Enabled:  false
    Resources:
      Limits:
        Cpu:     2
        Memory:  4Gi
      Requests:
        Cpu:     2
        Memory:  4Gi
    Shm Volume:
      Enabled:  false
    Volume Permissions:
      Enabled:  false
Status:
  Conditions:
    Last Transition Time:   2023-03-14T16:38:36Z
    Last Update Time:       2023-03-14T16:38:36Z
    Message:                Chart fetch was successful for Helm release 'test-postgresql' in 'test-postgresql'.
    Reason:                 ChartFetched
    Status:                 True
    Type:                   ChartFetched
    Last Transition Time:   2023-03-14T16:38:37Z
    Last Update Time:       2023-03-14T16:38:37Z
    Message:                Installation or upgrade succeeded for Helm release 'test-postgresql' in 'test-postgresql'.
    Reason:                 Deployed
    Status:                 True
    Type:                   Deployed
    Last Transition Time:   2023-03-14T16:41:24Z
    Last Update Time:       2023-03-14T16:41:24Z
    Message:                Release failed for Helm release 'test-postgresql' in 'test-postgresql'.
    Reason:                 Failed
    Status:                 False
    Type:                   Released
  Last Attempted Revision:  12.2.0
  Observed Generation:      1
  Phase:                    Failed
  Release Name:             test-postgresql
  Release Status:           deployed
  Revision:                 12.2.0
Events:
  Type     Reason             Age    From           Message
  ----     ------             ----   ----           -------
  Normal   ReleaseSynced      3m39s  helm-operator  managed release 'test-postgresql' in namespace 'test-postgresql' synchronized
  Warning  FailedReleaseSync  52s    helm-operator  synchronization of release 'test-postgresql' in namespace 'test-postgresql' failed: dry-run upgrade failed: dry-run upgrade for comparison failed: execution error at (postgresql/templates/secrets.yaml:5:24): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'global.postgresql.auth.postgresPassword' must not be empty, please add '--set global.postgresql.auth.postgresPassword=$POSTGRES_PASSWORD' to the command. To get the current value:

        export POSTGRES_PASSWORD=$(kubectl get secret --namespace "test-postgresql" test-postgresql -o jsonpath="{.data.postgres-password}" | base64 -d)
```

### Additional information

Updating the HR with an older version (ie 12.1.15) resolves the issue. The breaking change is tracked to this PR: https://github.com/bitnami/charts/pull/14893
