### ISSUE TITLE
[bitnami/mastodon] websocket served unencrypted over TLS ingress

### ISSUE THREAD

**Issue by daimoniac** [bitnami/charts#15507]
### Name and Version

bitnami/mastodon 1.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

On a cluster running cert-manager (bitnami chart) that issues certificates using letsencrypt:

Using the following command and values.yaml, mastodon starts up correctly, but the website fails to create a websocket connection to streaming because of `mixed content`.

```
helm upgrade --install pascal-mastodon --create-namespace --namespace pascal-mastodon bitnami/mastodon -f mastodon/values.yaml
```

![image](https://user-images.githubusercontent.com/7752824/225238875-60eed557-df8b-4a48-9709-25843716e670.png)

### Are you using any custom parameters or values?

values.yaml:
```
local_https: true
localDomain: mastodon.development.socialhub.dev

adminUser: admin
adminPassword: admin

smtp:
  server: mailcatcher
  port: 25
  from_address: mastodon@mastodon.local

apache:
  ingress:
    enabled: true
    hostname: mastodon.development.socialhub.dev
    ingressClassName: nginx
    certManager: true
    tls:
    - hosts:
        - mastodon.development.socialhub.dev
      secretName: mastodon.development.socialhub.dev-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

initJob:
  createAdmin: false
```

### What is the expected behavior?

full functionality, service of websocket via `wss:` URLs rather than `ws:` URLs

### What do you see instead?

mastodon is trying to serve websockets in an unencrypted way via `ws:` URLs
