### ISSUE TITLE
[bitnami/external-dns] Istio Gateways not populating

### ISSUE THREAD

**Issue by chruzcruz** [bitnami/charts#15515]
### Name and Version

1.12.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Good Afternoon,

I am trying to use external-dns to autopopulate GCP Cloud DNS, but noticed the entries are not being populated. 
If I add in the annotations, the DNS upsert works accordingly, but would like to avoid having to hard-code load balancer/IP Values within the deployment manifests.

```yaml
kind: Gateway
metadata:
  name: sample-gateway
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/target: x.x.x.x
    external-dns.alpha.kubernetes.io/hostname: sample.dev.mydomain.com
```

### Are you using any custom parameters or values?
```yaml
logFormat: json
policy: upsert-only
sources:
  - istio-gateway
provider: google
serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: "xxxxxxxx"
domainFilters: ["xxxxx"]
txtOwnerId: "xxxx-owner"
policy: "upsert-only"
logLevel: debug
extraArgs:
  - "--google-project=xxxx-dns-project"
```

### What do you see instead?
```
level=debug msg="No endpoints could be generated from Gateway default/sample-gateway"
```
### Additional information

https://github.com/kubernetes-sigs/external-dns/issues/1718
https://github.com/bitnami/charts/issues/3275
