### ISSUE TITLE
[bitnami/mysql] Needs to expose   podSecurityContext/containerSecurityContext for metrics

### ISSUE THREAD

**Issue by udf2457** [bitnami/charts#15552]
### Name and Version

bitnami/mysql 9.6.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Run helm install with restricted PSS enabled.

Note the following warning:

```
W0318 12:58:17.528714    8052 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "metrics" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "metrics" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "metrics" must set securityContext.runAsNonRoot=true)
W0318 12:58:17.528714    8052 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "metrics" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "metrics" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "metrics" must set securityContext.runAsNonRoot=true)
```

Adding:

```yaml
metrics:
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
```

It does not resolve the issue because the variables are not passed down to metrics.

Please note that I am still a newbie in Helm charts, so please do not ask me to submit a PR!

### Are you using any custom parameters or values?

```yaml
global:
  storageClass: "longhorn"
architecture: "replication"
auth:
  existingSecret: "mysql"
primary:
  extraFlags: "--authentication-policy=mysql_native_password"
  startupProbe:
    initialDelaySeconds: 60
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
secondary:
  extraFlags: "--authentication-policy=mysql_native_password"
  startupProbe:
    initialDelaySeconds: 60
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
metrics:
  enabled: true
```

### What is the expected behavior?

No warning.
