### ISSUE TITLE
[bitnami/influxdb] duplicate targets discovered by Prometheus

### ISSUE THREAD

**Issue by mateuszdrab** [bitnami/charts#15630]
### Name and Version

bitnami/influxdb 5.4.18

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy InfluxDB with below values
2. Check Prometheus

### Are you using any custom parameters or values?
```yaml
influxdb:
  service:
    type: LoadBalancer
  updateStrategy:
    type: Recreate
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```
### What is the expected behavior?

Single target per deployment of influxdb

### What do you see instead?

Two targets as two services are matched by the selectors of the `servicemonitor`. There is no label to uniquely identify the metrics service from the main one.
