### ISSUE TITLE
[bitnami/kube-prometheus] Unknown field "enableRemoteWriteReceiver" in com.coreos.monitoring.v1.Prometheus.spec

### ISSUE THREAD

**Issue by Placidina** [bitnami/charts#15636]
### Name and Version

bitnami/kube-prometheus 8.3.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Upgrade from `8.3.2` for any new versions:
```
helm upgrade --install --namespace monitoring --version 8.3.5 --wait --timeout 1800s -f custom.yaml kube-prometheus bitnami/kube-prometheus
```
### Are you using any custom parameters or values?

```yaml
fullnameOverride: kube-prometheus
operator:
  serviceMonitor:
    enabled: false
  priorityClassName: default-high
  tolerations:
    - effect: NoSchedule
      key: monitoring
      operator: Exists
  nodeSelector:
    environment: monitoring
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 250m
      memory: 512Mi
  configReloaderResources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 100m
      memory: 256Mi
prometheus:
  scrapeInterval: 10s
  evaluationInterval: 10s
  serviceMonitor:
    enabled: false
  externalLabels:
    cluster: production
  priorityClassName: default-high
  tolerations:
    - effect: NoSchedule
      key: monitoring
      operator: Exists
  nodeSelector:
    environment: monitoring
  resources:
    requests:
      cpu: 2000m
      memory: 4Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  persistence:
    enabled: true
    size: 50Gi
    storageClass: gp2-us-east-1a
  retention: 15d
  additionalPrometheusRules:
    - name: kubernetes-alerts
      groups:
        - name: kubernetes-node.alerts
          rules:
            - alert: KubernetesNodeReady
              expr: kube_node_status_condition{condition="Ready", status="true"} == 0
              for: 5m
              labels:
                severity: critical
              annotations:
                summary: Kubernetes Node Ready
                description: Node {{ $labels.node }} has been unready for a long time
            - alert: KubernetesMemoryPressure
              expr: kube_node_status_condition{condition="MemoryPressure", status="true"} == 1
              for: 2m
              labels:
                severity: critical
              annotations:
                summary: Kubernetes memory pressure
                description: Node {{ $labels.node }} has MemoryPressure condition
            - alert: KubernetesDiskPressure
              expr: kube_node_status_condition{condition="DiskPressure", status="true"} == 1
              for: 2m
              labels:
                severity: critical
              annotations:
                summary: Kubernetes disk pressure
                description: Node {{ $labels.node }} has DiskPressure condition
            - alert: KubernetesOutOfCapacity
              expr: sum(kube_pod_info) by (node) / sum(kube_node_status_allocatable_pods) by (node) * 100 > 90
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: Kubernetes out of capacity
                description: Node {{ $labels.node }} is out of capacity
        - name: kubernetes-api.alerts
          rules:
            - alert: KubernetesApiServerErrors
              expr: sum(rate(apiserver_request_total{job="apiserver", code=~"^(?:5..)$"}[1m])) / sum(rate(apiserver_request_total{job="apiserver"}[1m])) * 100 > 3
              for: 1m
              labels:
                severity: critical
              annotations:
                summary: Kubernetes API server errors
                description: Kubernetes API server is experiencing high error rate
            - alert: KubernetesApiClientErrors
              expr: (sum(rate(rest_client_requests_total{code=~"(4|5).."}[1m])) by (instance, job) / sum(rate(rest_client_requests_total[1m])) by (instance, job)) * 100 > 1
              for: 2m
              labels:
                severity: critical
              annotations:
                summary: Kubernetes API client errors
                description: Kubernetes API client is experiencing high error rate
            - alert: KubernetesApiClientErrors
              expr: (sum(rate(rest_client_requests_total{code=~"(4|5).."}[1m])) by (instance, job) / sum(rate(rest_client_requests_total[1m])) by (instance, job)) * 100 > 1
              for: 1m
              labels:
                severity: critical
              annotations:
                summary: Kubernetes API client errors
                description: Kubernetes API client is experiencing high error rate
    - name: node-alerts
      groups:
        - name: node-memory.alerts
          rules:
            - alert: NodeOutOfMemory
              expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: Node out of memory
                description: The memory available is less than 10%
            - alert: NodeMemoryUnderMemoryPressure
              expr: rate(node_vmstat_pgmajfault[1m]) > 1000
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: Node memory under memory pressure
                description: The node is under heavy memory pressure. High rate of major page faults
        - name: node-network.alerts
          rules:
            - alert: NodeUnusualNetworkThroughputIn
              expr: sum by (instance) (rate(node_network_receive_bytes_total[2m])) / 1024 / 1024 > 100
              for: 5m
              labels:
                severity: warning
              annotations:
                summary: Node unusual network throughput in
                description: Node network interfaces are probably receiving too much data
            - alert: NodeUnusualNetworkThroughputOut
              expr: sum by (instance) (rate(node_network_transmit_bytes_total[2m])) / 1024 / 1024 > 100
              for: 5m
              labels:
                severity: warning
              annotations:
                summary: Node unusual network throughput out
                description: Node network interfaces are probably sending too much data
            - alert: NodeNetworkReceiveErrors
              expr: rate(node_network_receive_errs_total[2m]) / rate(node_network_receive_packets_total[2m]) > 0.01
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: Node Network Receive Errors
                description: Interface {{ $labels.device }} has encountered {{ printf "%.0f" $value }} receive errors
            - alert: NodeNetworkTransmitErrors
              expr: rate(node_network_transmit_errs_total[2m]) / rate(node_network_transmit_packets_total[2m]) > 0.01
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: Node Network Transmit Errors
                description: Interface {{ $labels.device }} has encountered {{ printf "%.0f" $value }} transmit errors
            - alert: NodeNetworkInterfaceSaturated
              expr: (rate(node_network_receive_bytes_total{device!~"^tap.*"}[1m]) + rate(node_network_transmit_bytes_total{device!~"^tap.*"}[1m])) / node_network_speed_bytes{device!~"^tap.*"} > 0.8
              for: 1m
              labels:
                severity: warning
              annotations:
                summary: Node Network Interface Saturated
                description: The network interface "{{ $labels.interface }}" is getting overloaded
        - name: node-disk.alerts
          rules:
            - alert: NodeUnusualDiskReadRate
              expr: sum by (instance) (rate(node_disk_read_bytes_total[2m])) / 1024 / 1024 > 50
              for: 1m
              labels:
                severity: warning
              annotations:
                summary: Node unusual disk read rate
                description: Disk is probably reading too much data
            - alert: NodeUnusualDiskWriteRate
              expr: sum by (instance) (rate(node_disk_written_bytes_total[2m])) / 1024 / 1024 > 50
              for: 1m
              labels:
                severity: warning
              annotations:
                summary: Node unusual disk write rate
                description: Disk is probably writing too much data
            - alert: NodeOutOfInodes
              expr: node_filesystem_files_free{device ="rootfs"} / node_filesystem_files{device="rootfs"} * 100 < 10 and ON (instance, device, mountpoint) node_filesystem_readonly{device="rootfs"} == 0
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: Node out of inodes
                description: The available disk inodes is less 10%
            - alert: NodeInodsWillFillIn24Hours
              expr: node_filesystem_files_free{device="rootfs"} / node_filesystem_files{device="rootfs"} * 100 < 10 and predict_linear(node_filesystem_files_free{device="rootfs"}[1h], 24 * 3600) < 0 and ON (instance, device, mountpoint) node_filesystem_readonly{device="rootfs"} == 0
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: Node inodes will fill in 24 hours
                description: Filesystem is predicted to run out of inodes within the next 24 hours at current write rate
            - alert: NodeUnusualDiskReadLatency
              expr: rate(node_disk_read_time_seconds_total[1m]) / rate(node_disk_reads_completed_total[1m]) > 0.1 and rate(node_disk_reads_completed_total[1m]) > 0
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: Node unusual disk read latency
                description: Disk latency is growing
            - alert: NodeOutOfDiskSpace
              expr: (node_filesystem_avail_bytes{mountpoint!~"^/(sys|proc|dev|run)($|/)"} * 100) / node_filesystem_size_bytes{mountpoint!~"^/(sys|proc|dev|run)($|/)"} < 10 and ON (instance, device, mountpoint) node_filesystem_readonly{mountpoint!~"^/(sys|proc|dev|run)($|/)"} == 0
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: Node out of disk space
                description: Disk available space is less 10%
            - alert: NodeDiskWillFillIn24Hours
              expr: (node_filesystem_avail_bytes{mountpoint!~"^/(sys|proc|dev|run)($|/)"} * 100) / node_filesystem_size_bytes{mountpoint!~"^/(sys|proc|dev|run)($|/)"} < 10 and ON (instance, device, mountpoint) predict_linear(node_filesystem_avail_bytes{mountpoint!~"^/(sys|proc|dev|run)($|/)", fstype!~"tmpfs"}[1h], 24 * 3600) < 0 and ON (instance, device, mountpoint) node_filesystem_readonly{mountpoint!~"^/(sys|proc|dev|run)($|/)"} == 0
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: Node disk will fill in 24 hours
                description: Filesystem is predicted to run out of space within the next 24 hours at current write rate
        - name: node-cpu.alerts
          rules:
            - alert: NodeHighCpuLoad
              expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
              for: 1m
              labels:
                severity: warning
              annotations:
                summary: Node high CPU load
                description: CPU load is bigger than 80%
            - alert: NodeCpuStealNoisyNeighbor
              expr: avg by(instance) (rate(node_cpu_seconds_total{mode="steal"}[5m])) * 100 > 10
              for: 0m
              labels:
                severity: warning
              annotations:
                summary: Node CPU steal noisy neighbor
                description: CPU steal is bigger than 10%. A noisy neighbor is killing VM performances or a spot instance may be out of credit
        - name: node-misc.alerts
          rules:
            - alert: HostConntrackLimit
              expr: node_nf_conntrack_entries / node_nf_conntrack_entries_limit > 0.8
              for: 5m
              labels:
                severity: warning
              annotations:
                summary: Host conntrack limit
                description: The number of conntrack is approching limit
    - name: prometheus-alerts
      groups:
        - name: prometheus-jobs.alerts
          rules:
            - alert: PrometheusJobMissing
              expr: absent(up{job="prometheus"})
              for: 0m
              labels:
                severity: critical
              annotations:
                summary: Prometheus job missing
                description: A Prometheus job has disappeared
            - alert: PrometheusTooManyRestarts
              expr: changes(process_start_time_seconds{job=~"kube-prometheus-.*"}[15m]) > 2
              for: 0m
              labels:
                severity: warning
              annotations:
                summary: Prometheus too many restarts
                description: Prometheus has restarted more than twice in the last 15 minutes
        - name: prometheus-configurations.alerts
          rules:
            - alert: PrometheusConfigurationReloadFailure
              expr: prometheus_config_last_reload_successful != 1
              for: 0m
              labels:
                severity: warning
              annotations:
                summary: Prometheus configuration reload failure
                description: Prometheus configuration reload error
            - alert: PrometheusAlertmanagerConfigurationReloadFailure
              expr: alertmanager_config_last_reload_successful != 1
              for: 0m
              labels:
                severity: warning
              annotations:
                summary: Prometheus AlertManager configuration reload failure
                description: AlertManager configuration reload error
            - alert: PrometheusAlertmanagerConfigNotSynced
              expr: count(count_values("config_hash", alertmanager_config_hash)) > 1
              for: 0m
              labels:
                severity: warning
              annotations:
                summary: Prometheus AlertManager config not synced
                description: Configurations of AlertManager cluster instances are out of sync
        - name: prometheus-tsdb.alerts
          rules:
            - alert: PrometheusTsdbCheckpointCreationFailures
              expr: increase(prometheus_tsdb_checkpoint_creations_failed_total[1m]) > 0
              for: 0m
              labels:
                severity: critical
              annotations:
                summary: Prometheus TSDB checkpoint creation failures
                description: Prometheus encountered checkpoint creation failures
            - alert: PrometheusTsdbCheckpointDeletionFailures
              expr: increase(prometheus_tsdb_checkpoint_deletions_failed_total[1m]) > 0
              for: 0m
              labels:
                severity: critical
              annotations:
                summary: Prometheus TSDB checkpoint deletion failures
                description: Prometheus encountered checkpoint deletion failures
            - alert: PrometheusTsdbCompactionsFailed
              expr: increase(prometheus_tsdb_compactions_failed_total[1m]) > 0
              for: 0m
              labels:
                severity: critical
              annotations:
                summary: Prometheus TSDB compactions failed
                description: Prometheus encountered TSDB compactions failures
            - alert: PrometheusTsdbHeadTruncationsFailed
              expr: increase(prometheus_tsdb_head_truncations_failed_total[1m]) > 0
              for: 0m
              labels:
                severity: critical
              annotations:
                summary: Prometheus TSDB head truncations failed
                description: Prometheus encountered TSDB head truncation failures
            - alert: PrometheusTsdbReloadFailures
              expr: increase(prometheus_tsdb_reloads_failures_total[1m]) > 0
              for: 0m
              labels:
                severity: critical
              annotations:
                summary: Prometheus TSDB reload failures
                description: Prometheus encountered TSDB reload failures
            - alert: PrometheusTsdbWalCorruptions
              expr: increase(prometheus_tsdb_wal_corruptions_total[1m]) > 0
              for: 0m
              labels:
                severity: critical
              annotations:
                summary: Prometheus TSDB WAL corruptions
                description: Prometheus encountered TSDB WAL corruptions
            - alert: PrometheusTsdbWalTruncationsFailed
              expr: increase(prometheus_tsdb_wal_truncations_failed_total[1m]) > 0
              for: 0m
              labels:
                severity: critical
              annotations:
                summary: Prometheus TSDB WAL truncations failed
                description: Prometheus encountered TSDB WAL truncation failures
        - name: prometheus-data-volume.alerts
          rules:
            - alert: PrometheusDataVolumeOutOfDiskSpace
              expr: kubelet_volume_stats_available_bytes{job="kubernetes-nodes", environment="prometheus"} / kubelet_volume_stats_capacity_bytes{job="kubernetes-nodes", environment="prometheus"} * 100 < 10
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: Prometheus Data Volume Out Of Disk Space
                description: Volume is almost full ({{ $value }}% left)
        - name: prometheus-misc.alerts
          rules:
            - alert: PrometheusNotConnectedToAlertmanager
              expr: prometheus_notifications_alertmanagers_discovered < 1
              for: 0m
              labels:
                severity: critical
              annotations:
                summary: Prometheus not connected to alertmanager
                description: Prometheus cannot connect the alertmanager
            - alert: PrometheusRuleEvaluationFailures
              expr: increase(prometheus_rule_evaluation_failures_total[3m]) > 0
              for: 0m
              labels:
                severity: critical
              annotations:
                summary: Prometheus rule evaluation failures
                description: Prometheus encountered rule evaluation failures, leading to potentially ignored alerts
            - alert: PrometheusTemplateTextExpansionFailures
              expr: increase(prometheus_template_text_expansion_failures_total[3m]) > 0
              for: 0m
              labels:
                severity: critical
              annotations:
                summary: Prometheus template text expansion failures
                description: Prometheus encountered template text expansion failures
            - alert: PrometheusRuleEvaluationSlow
              expr: prometheus_rule_group_last_duration_seconds > prometheus_rule_group_interval_seconds
              for: 5m
              labels:
                severity: warning
              annotations:
                summary: Prometheus rule evaluation slow
                description: Prometheus rule evaluation took more time than the scheduled interval. It indicates a slower storage backend access or too complex query
            - alert: PrometheusNotificationsBacklog
              expr: min_over_time(prometheus_notifications_queue_length[10m]) > 0
              for: 0m
              labels:
                severity: warning
              annotations:
                summary: Prometheus notifications backlog
                description: The Prometheus notification queue has not been empty for 10 minutes
            - alert: PrometheusAlertmanagerNotificationFailing
              expr: rate(alertmanager_notifications_failed_total[1m]) > 0
              for: 0m
              labels:
                severity: critical
              annotations:
                summary: Prometheus AlertManager notification failing
                description: Alertmanager is failing sending notifications
            - alert: PrometheusTargetEmpty
              expr: prometheus_sd_discovered_targets == 0
              for: 0m
              labels:
                severity: critical
              annotations:
                summary: Prometheus target empty
                description: Prometheus has no target in service discovery
            - alert: PrometheusTargetScrapingSlow
              expr: prometheus_target_interval_length_seconds{quantile="0.9"} > 60
              for: 5m
              labels:
                severity: warning
              annotations:
                summary: Prometheus target scraping slow
                description: Prometheus is scraping exporters slowly
            - alert: PrometheusLargeScrape
              expr: increase(prometheus_target_scrapes_exceeded_sample_limit_total[10m]) > 10
              for: 5m
              labels:
                severity: warning
              annotations:
                summary: Prometheus large scrape
                description: Prometheus has many scrapes that exceed the sample limit
            - alert: PrometheusTargetScrapeDuplicate
              expr: increase(prometheus_target_scrapes_sample_duplicate_timestamp_total[5m]) > 0
              for: 0m
              labels:
                severity: warning
              annotations:
                summary: Prometheus target scrape duplicate
                description: Prometheus has many samples rejected due to duplicate timestamps but different values
  additionalScrapeConfigs:
    enabled: true
    type: internal
    internal:
      jobList:
        - job_name: prometheus
          static_configs:
            - targets:
                - localhost:9090
        - job_name: kubernetes-apiservers
          kubernetes_sd_configs:
            - role: endpoints
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          relabel_configs:
            - source_labels:
                - __meta_kubernetes_namespace
                - __meta_kubernetes_service_name
                - __meta_kubernetes_endpoint_port_name
              action: keep
              regex: default;kubernetes;https
        - job_name: kubernetes-nodes
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels:
                - __meta_kubernetes_node_name
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/$1/proxy/metrics
        - job_name: kubernetes-nodes-cadvisor
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels:
                - __meta_kubernetes_node_name
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
        - job_name: kubernetes-service-endpoints
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - source_labels:
                - __meta_kubernetes_service_annotation_prometheus_io_scrape
              action: keep
              regex: true
            - source_labels:
                - __meta_kubernetes_service_annotation_prometheus_io_scrape_slow
              action: drop
              regex: true
            - source_labels:
                - __meta_kubernetes_service_annotation_prometheus_io_scheme
              action: replace
              target_label: __scheme__
              regex: (https?)
            - source_labels:
                - __meta_kubernetes_service_annotation_prometheus_io_path
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels:
                - __address__
                - __meta_kubernetes_service_annotation_prometheus_io_port
              action: replace
              target_label: __address__
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
            - action: labelmap
              regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
              replacement: __param_$1
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - source_labels:
                - __meta_kubernetes_namespace
              action: replace
              target_label: kubernetes_namespace
            - source_labels:
                - __meta_kubernetes_service_name
              action: replace
              target_label: kubernetes_name
            - source_labels:
                - __meta_kubernetes_pod_node_name
              action: replace
              target_label: kubernetes_node
        - job_name: kubernetes-service-endpoints-slow
          scrape_interval: 5m
          scrape_timeout: 30s
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - source_labels:
                - __meta_kubernetes_service_annotation_prometheus_io_scrape_slow
              action: keep
              regex: true
            - source_labels:
                - __meta_kubernetes_service_annotation_prometheus_io_scheme
              action: replace
              target_label: __scheme__
              regex: (https?)
            - source_labels:
                - __meta_kubernetes_service_annotation_prometheus_io_path
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels:
                - __address__
                - __meta_kubernetes_service_annotation_prometheus_io_port
              action: replace
              target_label: __address__
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
            - action: labelmap
              regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
              replacement: __param_$1
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - source_labels:
                - __meta_kubernetes_namespace
              action: replace
              target_label: kubernetes_namespace
            - source_labels:
                - __meta_kubernetes_service_name
              action: replace
              target_label: kubernetes_name
            - source_labels:
                - __meta_kubernetes_pod_node_name
              action: replace
              target_label: kubernetes_node
        - job_name: prometheus-pushgateway
          honor_labels: true
          kubernetes_sd_configs:
            - role: service
          relabel_configs:
            - source_labels:
                - __meta_kubernetes_service_annotation_prometheus_io_probe
              action: keep
              regex: pushgateway
        - job_name: kubernetes-services
          metrics_path: /probe
          params:
            module:
              - http_2xx
          kubernetes_sd_configs:
            - role: service
          relabel_configs:
            - source_labels:
                - __meta_kubernetes_service_annotation_prometheus_io_probe
              action: keep
              regex: true
            - source_labels:
                - __address__
              target_label: __param_target
            - target_label: __address__
              replacement: blackbox
            - source_labels:
                - __param_target
              target_label: instance
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - source_labels:
                - __meta_kubernetes_namespace
              target_label: kubernetes_namespace
            - source_labels:
                - __meta_kubernetes_service_name
              target_label: kubernetes_name
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels:
                - __meta_kubernetes_pod_annotation_prometheus_io_scrape
              action: keep
              regex: true
            - source_labels:
                - __meta_kubernetes_pod_annotation_prometheus_io_scrape_slow
              action: drop
              regex: true
            - source_labels:
                - __meta_kubernetes_pod_annotation_prometheus_io_scheme
              action: replace
              regex: (https?)
              target_label: __scheme__
            - source_labels:
                - __meta_kubernetes_pod_annotation_prometheus_io_path
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels:
                - __address__
                - __meta_kubernetes_pod_annotation_prometheus_io_port
              action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
              replacement: __param_$1
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - source_labels:
                - __meta_kubernetes_namespace
              action: replace
              target_label: kubernetes_namespace
            - source_labels:
                - __meta_kubernetes_pod_name
              action: replace
              target_label: kubernetes_pod_name
            - source_labels:
                - __meta_kubernetes_pod_phase
              regex: Pending|Succeeded|Failed|Completed
              action: drop
        - job_name: kubernetes-pods-slow
          scrape_interval: 5m
          scrape_timeout: 30s
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels:
                - __meta_kubernetes_pod_annotation_prometheus_io_scrape_slow
              action: keep
              regex: true
            - source_labels:
                - __meta_kubernetes_pod_annotation_prometheus_io_scheme
              action: replace
              regex: (https?)
              target_label: __scheme__
            - source_labels:
                - __meta_kubernetes_pod_annotation_prometheus_io_path
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels:
                - __address__
                - __meta_kubernetes_pod_annotation_prometheus_io_port
              action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
              replacement: __param_$1
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - source_labels:
                - __meta_kubernetes_namespace
              action: replace
              target_label: kubernetes_namespace
            - source_labels:
                - __meta_kubernetes_pod_name
              action: replace
              target_label: kubernetes_pod_name
            - source_labels:
                - __meta_kubernetes_pod_phase
              regex: Pending|Succeeded|Failed|Completed
              action: drop
alertmanager:
  serviceMonitor:
    enabled: false
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 20m
      memory: 32Mi
  tolerations:
    - key: operation
      operator: Exists
      effect: NoSchedule
  nodeSelector:
    environment: operation
  priorityClassName: default-high
  config:
    global: {}
    route:
      receiver: gchat
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 1h
      routes:
        - receiver: gchat
          group_wait: 30s
          continue: true
          match_re:
            severity: critical|warning|info
    receivers:
      - name: gchat
        webhook_configs:
          - send_resolved: true
            url: http://integration.infra.svc.cluster.local:6000/api/v1/alertmanager/alert
node-exporter:
  serviceMonitor:
    enabled: false
  service:
    annotations:
      prometheus.io/scrape: "true"
  priorityClassName: default-high
  tolerations:
    - operator: Exists
  resources:
    requests:
      cpu: 10m
      memory: 24Mi
    limits:
      cpu: 10m
      memory: 24Mi
  extraArgs:
    no-collector.wifi: ""
    no-collector.hwmon: ""
    collector.filesystem.ignored-mount-points: "^/(dev|proc|run|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)"
    collector.filesystem.ignored-fs-types: "^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$"
kube-state-metrics:
  enabled: true
  serviceMonitor:
    enabled: false
  tolerations:
    - key: operation
      operator: Exists
      effect: NoSchedule
  nodeSelector:
    environment: operation
  priorityClassName: default-high
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 128Mi
kubeProxy:
  enabled: false
kubeApiServer:
  enabled: false
kubeScheduler:
  enabled: false
coreDns:
  enabled: false
kubeControllerManager:
  enabled: false
kubelet:
  enabled: false
```

### What is the expected behavior?

No error for the field `enableRemoteWriteReceiver`

### What do you see instead?

```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Prometheus.spec): unknown field "enableRemoteWriteReceiver" in com.coreos.monitoring.v1.Prometheus.spec
```
