### ISSUE TITLE
[bitnami/mongodb] Could not find user "root" for db "admin"

### ISSUE THREAD

**Issue by StevenCyb** [bitnami/charts#15634]
### Name and Version

bitnami/mongodb 13.9.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Clone the `main` branch 
2. Use `values.yaml` (defined below)
3. Deploy it on AWS EKS `v1.24.8`
4. Try to ping or connect (e.g. go mongo driver or MongoDB Compass)
I use `mongodb://svc.ns:27017/?replicaSet=rs0&ssl=false&authSource=admin` with the correct credentials.

### Are you using any custom parameters or values?

```yaml
architecture: replicaset
replicaCount: 2
disableSystemLog: true

auth:
  rootUser: root
  rootPassword: some_password
  replicaSetKey: some_rs_key

persistence:
  size: 10Gi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  livenessProbe:
    timeoutSeconds: 10
  readinessProbe:
    timeoutSeconds: 10
```

### What is the expected behavior?

To get authenticated by using the defined root.

### What do you see instead?

Error log in my go service:
```bash
panic: pinging MongoDB failed: failed to ping mongo (PrimaryPreferred): connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using me chanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.
```
Error log in MongoDB:
```bash
mongodb {"t":{"$date":"2023-03-20T09:51:11.511+00:00"},"s":"I",  "c":"ACCESS",   "id":20249,   "ctx":"conn285","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-256","speculative":true,"  principalName":"root","authenticationDatabase":"admin","remote":"10.10.1.126:38828","extraInfo":{},"error":"UserNotFound: Could not find user \"root\" for db \"admin\""}}   
```

### Additional information

I tried to delete pvc's and all resources but without any effect.
