### ISSUE TITLE
[bitnami/kafka] kraft mode enabled but connected to zookeeper

### ISSUE THREAD

**Issue by zigbang-yeezy** [bitnami/charts#15648]
### Name and Version

bitnami/kafka:3.4.0-debian-11-r6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I connected kraft to helm chart and removed zookeeper. However, the configuration did not work, and only the error that the main keeper cannot be connected in kafka pad appears. Is there any part in Helm Chart that needs to be revised further?

### Are you using any custom parameters or values?

```
kraft:
  enabled: true
  processRoles: broker,controller
  controllerListenerNames: CONTROLLER
  clusterId: "some_uuid"
  controllerQuorumVoters: "1@127.0.0.1:9093"
zookeeper:
  enabled: false
```

### What do you see instead?

```
ERROR Exiting Kafka due to fatal exception during startup. (kafka.Kafka$)
kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
	at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:254)
	at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:250)
	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:108)
	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:2262)
	at kafka.zk.KafkaZkClient$.createZkClient(KafkaZkClient.scala:2354)
	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:593)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:213)
	at kafka.Kafka$.main(Kafka.scala:115)
	at kafka.Kafka.main(Kafka.scala)
```

**Comment by marcosbc** [comment]
Hi @zigbang-yeezy, there are some cases where using Kafka as a sub-chart might cause issues if it is not properly configured.

Could you try and see if KRAFT envvars appear with `helm template` using those values? E.g.:

```
$ helm template . -f values-custom.yaml | grep -A 2 -B 2 KRAFT
            - name: KAFKA_CFG_SUPER_USERS
              value: "User:admin"
            - name: KAFKA_KRAFT_CLUSTER_ID
              value: "kafka_cluster_id_test1"
            - name: KAFKA_CFG_PROCESS_ROLES
--
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_ENABLE_KRAFT
              value: "true"
          ports:
```

**Comment by zigbang-yeezy** [comment]
I entered the following command.
`helm template kafka bitnami/kafka -f ./values.yaml | grep -A 2 -B 2 KRAFT`
And no value could be returned.

**Comment by marcosbc** [comment]
Hi @zigbang-yeezy, unfortunately I could not reproduce the following command from the directory `/path/to/charts/bitnami/kafka`:

```
$ helm template bitnami/kafka -f my-values.yaml | grep -A 2 -B 2 ZOOKEEPER
```

I am using the following `my-values.yaml`:

```
kraft:
  enabled: true
  processRoles: broker,controller
  controllerListenerNames: CONTROLLER
  clusterId: "some_uuid"
  controllerQuorumVoters: "1@127.0.0.1:9093"
zookeeper:
  enabled: false
```

Make sure that your Helm repo is updated (e.g. `helm repo update`) and that you are not using Kafka as a sub-chart.
