### ISSUE TITLE
[bitnami/minio] Policy provisioning error in 12.1.14

### ISSUE THREAD

**Issue by justusbunsi** [bitnami/charts#15675]
### Name and Version

bitnami/minio 12.1.14

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Configure values.yaml to enable `provisioning` and specify policies to be added/updated
2. Deploy the Helm Chart to a cluster
3. Wait for the provisioning job to start
4. Inspect logs of provisioning job pod

### Are you using any custom parameters or values?

```yaml
provisioning:
  enabled: true
  policies:
    - name: backup
      statements:
        - resources:
            - "arn:aws:s3:::backup"
          effect: "Allow"
          actions:
            - "s3:GetBucketLocation"
            - "s3:ListBucket"
            - "s3:ListBucketMultipartUploads"
        - resources:
            - "arn:aws:s3:::backup/*"
          effect: "Allow"
          actions:
            - "s3:AbortMultipartUpload"
            - "s3:DeleteObject"
            - "s3:GetObject"
            - "s3:ListMultipartUploadParts"
            - "s3:PutObject"

  # for completeness only, as the bucket is referenced in the policy
  buckets:
    - name: backup
      region: eu-west-1
      versioning: false
      withLock: false
      lifecycle:
        - id: backupRotation7d
          prefix: ""
          disabled: false
          expiry:
            days: 7
            nonconcurrentDays: 0
      quota: {}
      tags: {}
  config:
    - name: region
      options:
        name: eu-west-1
```

### What is the expected behavior?

No errors during provisioning job processing.

### What do you see instead?

MinIO itself will start successful. The provisioning job after MinIO is up and running fails with that error message:

```
Start Minio provisioning
Added `provisioning` successfully.
Successfully applied new settings.
Please restart your server 'mc admin service restart provisioning'.
Restart command successfully sent to `provisioning`. Type Ctrl-C to quit or wait to follow the status of the restart process.

Restarted `provisioning` successfully in 1 seconds
mc: <ERROR> Incorrect command. Please use 'mc admin policy create'.
```

### Additional information

The error appears since MinIO is bumped to https://github.com/minio/minio/releases/tag/RELEASE.2023-03-20T20-16-18Z with 4b3257186c17dff14081377c8fcac32f76ea5b27. The mentioned release contains commit https://github.com/minio/minio/commit/3fdd574f5418a69b394f0367f5d89763cafa8f3e which bumps the `mc` command line tool to https://github.com/minio/mc/releases/tag/RELEASE.2023-03-20T17-17-53Z. That release contains a breaking change in managing policies.
