### ISSUE TITLE
[bitnami/kafka] provision of topics fails

### ISSUE THREAD

**Issue by burkempers** [bitnami/charts#15686]
### Name and Version

bitnami/kafka:21.3.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. deploy kafka kraft cluster of 3
2. run provisioning job with a topic that needs 3 replicas

### Are you using any custom parameters or values?

Yes, but can reproduce with just using standard kraft and replica counts.

### What is the expected behavior?

A topic to be created with the correct settings.

### What do you see instead?

There is a race condition between all of the pods starting and the brokers are actually registered with kraft, so the topic creation fails with and error of 
```
Unable to replicate the partition 3 times(s): The target replication factor of 3 cannot be reached becuase only 2 brokers(s) are registered.
```
You dont get the error everytime, but it does happen enough.

### Additional information

Please add some logic to mitigate this race condition.  Probably in the init container after checking if port is active also add a check for if all the brokers are active.  Could just catch the topic creation error and add retry logic.

**Comment by javsalgar** [comment]
Hi,

Could you share the exact values you changed to reproduce the issue?

**Comment by burkempers** [comment]
```
zookeeper:
  enabled: false
kraft:
  enabled: true
replicaCount: 3
persistence:
  enabled: true
  size: 5Gi
provisioning:
  enabled: true
  topics:
    - name: mytopic
      numPartitions: 20
      replicationFactor: 3
startupProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timoutSeconds: 1
  failureThreshold: 15
  successThreshold: 1
```

**Comment by dgomezleon** [comment]
Hello @burkempers ,

Have you checked [this documentation](https://github.com/bitnami/containers/tree/main/bitnami/kafka#kafka-without-zookeeper-kraft) about how to use Kraft mode?

FYI, we are currently working on releasing a new version of the chart that uses Kraft by default. We will notify you here with any updates.

**Comment by burkempers** [comment]
Yes, I have read up on Kraft documentation.  My problem is not using Kraft mode, but just the race condition with this helm chart between when all of the brokers are available and the topic provisioning.

**Comment by dgomezleon** [comment]
Hi @burkempers ,

Sorry for the misunderstanding. 

We were not able to reproduce the issue after 10 retries. Could you please share the whole log? Did you get those logs from the pods?

**Comment by burkempers** [comment]
logs with error:
```
Configuring environment
Running pre-provisioning
Error while executing topic command : Unable to replicate the partition 3 time(s): The target replication factor of 3 cannont be reached because only 2 brokers(s) are register
[2023-04-06 12:06:03,748] ERROR org.apache.kafka.common.errors.InvalidReplicationFactorException: Unable to replicate the partition 3 times(s): The target replication factor
  (kafka.admin.TopicCommand$)
Running post-provisioning script if any given
Provisioning succeeded
```

I was having issue recreating this issue as well with the provided values.  Here is a slight modification to the values that i made to get this error to show:
```
zookeeper:
  enabled: false
kraft:
  enabled: true
replicaCount: 3
persistence:
  enabled: true
  size: 5Gi
externalAccess:
  enabled: true
provisioning:
  enabled: true
  topics:
    - name: mytopic
      numPartitions: 20
      replicationFactor: 3
startupProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timoutSeconds: 1
  failureThreshold: 15
  successThreshold: 1
  ```

**Comment by dgomezleon** [comment]
Hi @burkempers ,

The only change I can see with the previous parameters is that `externalAccess` is enabled, right? With those values, you should receive this warning:

```
Error: template: kafka/templates/NOTES.txt:314:4: executing "kafka/templates/NOTES.txt" at <include "kafka.validateValues" .>: error calling include: template: kafka/templates/_helpers.tpl:394:51: executing "kafka.validateValues" at <fail>: error calling fail:
VALUES VALIDATION:

kafka: externalAccess.service.loadBalancerNames or externalAccess.service.loadBalancerIPs
    By specifying "externalAccess.enabled=true", "externalAccess.autoDiscovery.enabled=false" and
    "externalAccess.service.type=LoadBalancer" at least one of externalAccess.service.loadBalancerNames
    or externalAccess.service.loadBalancerIPs  must be set and the length of those arrays must be equal
    to the number of replicas.
```

Regarding the logs you mentioned, could you please let us know where you obtained them? Did you deploy the application and execute kubectl logs POD? The steps I followed to deploy the application were:

1. Replace the values above in `values.yaml`
2. Execute `helm install kafka .`
3. Use  `kubectl logs kafka-{0,1,2}` to view the logs.

If you followed a different procedure, could you please provide us with more details or a recording?

**Comment by burkempers** [comment]
Sorry I was not fully filling in details since I work on an air gapped system and was guessing the things I was skipping would have been obvious.

1. pull the chart and extract
```
helm pull bitnami/kafka --version 21.3.0
tar zxvf kafka-21.3.0.tgz
```

2. update the provisioning job to remove delete hook to get to the errors in the logs
```
cd kafka/
sed -i 's/,hook-succeeded//g' templates/kafka-provisioning.yaml
```

3. create a good values overrides
```
cat<<EOF > tmp-values.yml
zookeeper:
  enabled: false
kraft:
  enabled: true
replicaCount: 3
persistence:
  enabled: true
  size: 5Gi
externalAccess:
  enabled: true
  service:
    type: ClusterIP
    domain: "my.some.domain"
provisioning:
  enabled: true
  topics:
    - name: mytopic
      numPartitions: 20
      replicationFactor: 3
startupProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timoutSeconds: 1
  failureThreshold: 15
  successThreshold: 1
EOF
```

4. install with helm
```
helm upgrade --install myKafka . -f tmp-values.yml
```

5. look at the logs from the provisioning job pod
```
kubectl logs -l app.kubernetes.io/component=kafka-provisioning
```
