### ISSUE TITLE
[bitnami/redis-cluster] After shutdown 2 of the 3 masters, restarting only 1 master will result in a failed status.

### ISSUE THREAD

**Issue by sdYoo** [bitnami/charts#15698]
### Name and Version

bitnami/redis-cluster 7.1.1

### What architecture are you using?

None

### What steps will reproduce the bug?

1. I currently have a redis-cluster consisting of 3 masters and 3 replica.
I configured the pods to float on static nodes with hostnetwork
```
master1-pod(node1) running - replica1-pod(node4)
master2-pod(node2) running - replica2-pod(node5)
master3-pod(node3) running - replica3-pod(node6)
```
2. I forcibly shut down the 2 master servers for availability testing.
```
master2-pod(node2) -> shutdown 
master3-pod(node3) -> shutdown
```
4. I confirmed that the "cluster state chaged" failed and I run [master2-pod(node2)]
master2-pod(node2) -> restart

5. But still the "cluster state chaged" failed.
6. After restarting up to [master3-pod(node3)], the "cluster state chaged" became ok.
master3-pod(node3) -> restart

7. I want to know why the "cluster state chaged" is failed when only one is restart.
```
master1-pod(node1) running     - replica1-pod(node4)
master2-pod(node2) restart      - replica2-pod(node5)
master3-pod(node3) shutdown - replica3-pod(node6)
```
### Are you using any custom parameters or values?

The helm value.yaml config I modified is as follows.
```
customConfig:
  maxmemory: 3gb
  maxclients: 10000
  clusterNodeTimeout: 4000
  daemonize: no
  appendonly: yes
  stopWritesOnBgsaveError: no
  clusterRequireFullCoverage: no
  logfile: "/tmp/redis-server.log"
  redisname: test-redis-cluster
  nodeips: 10.0.0.1 10.0.0.2 10.0.0.3 10.0.0.4
  renameCommands:
    - FLUSHDB "custome-flushdb"
    - FLUSHALL "custome-flushall"
```
### What is the expected behavior?

Out of the 3 masters, if I shut down 2 masters and restart one, the cluster state should return to ok.

1) cluster state chaged : fail
```
master1-pod(node1) running         - replica1-pod(node4)
master2-pod(node2) shutdown  - replica2-pod(node5)
master3-pod(node3) shutdown  - replica3-pod(node6)
```
2) cluster state chaged : Expected to be ok, but failed.
```
master1-pod(node1) running          - replica1-pod(node4)
master2-pod(node2) restart        - replica2-pod(node5)
master3-pod(node3) shutdown   - replica3-pod(node6)
```
3) cluster state chaged : ok
```
master1-pod(node1) running      - replica1-pod(node4)
master2-pod(node2) restart    - replica2-pod(node5)
master3-pod(node3) restart   - replica3-pod(node6)
```
### What do you see instead?

After shutting down 2 of the 3 masters, restarting only 1 master will result in a failed status.
Both need to be restarted to be ok.
