### ISSUE TITLE
Spark chart does not respect the worker.replicaCount=(number)

### ISSUE THREAD

**Issue by RafaelAybar** [bitnami/charts#15691]
### Name and Version

bitnami/spark  6.4.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Edit the values .yaml
2. Run helm template -n test .  > test.yaml

### Are you using any custom parameters or values?

I tried to use both: With the `helm template spark --set worker.replicaCount=4 . > template.yaml -n demo` and I set  also in the values.yaml:
```yaml
master:
  containerPorts:
    http: 8080 # Specify the port where the web interface will listen on the worker over HTTP
    https: 8480 #Specify the port where the web interface will listen on the worker over HTTPS
    cluster: 7077 # Specify the port where the master listens to communicate with workers
  configOptions: "" # Use a string to set the config options for in the form "-Dx=y"
  extraEnvVars: []
  updateStrategy:
    type: RollingUpdate

worker:
  replicaCount: 4
  containerPorts:
    http: 8080
    https: 8480
    cluster: 7077
  updateStrategy:
    type: RollingUpdate
  configOptions: ""
  extraEnvVars: []
```

### What is the expected behavior?

It must return the proper number of replicas:
```yaml
# Source: spark/charts/spark/templates/statefulset-worker.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-worker
  namespace: "demo"
  labels:
    app.kubernetes.io/name: spark
    helm.sh/chart: spark-6.4.1
    app.kubernetes.io/instance: spark
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: worker
spec:
  serviceName: spark-headless
  replicas: 4
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: spark
      app.kubernetes.io/instance: spark
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spark
        helm.sh/chart: spark-6.4.1
        app.kubernetes.io/instance: spark
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: worker
    spec:
      
      serviceAccountName: spark
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: spark
                    app.kubernetes.io/instance: spark
                    app.kubernetes.io/component: worker
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
        runAsGroup: 0
        runAsUser: 1001
        seLinuxOptions: {}
      containers:
        - name: spark-worker
          image: docker.io/bitnami/spark:3.3.2-debian-11-r9
          imagePullPolicy: "IfNotPresent"
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
          env:
            - name: SPARK_MODE
              value: "worker"
            - name: BITNAMI_DEBUG
              value: "false"
            - name: SPARK_DAEMON_MEMORY
              value: ""
            ## There are some environment variables whose existence needs
            ## to be checked because Spark checks if they are null instead of an
            ## empty string
            - name: SPARK_WORKER_WEBUI_PORT
              value: "8080"
            - name: SPARK_DAEMON_JAVA_OPTS
              value: ""
            - name: SPARK_MASTER_URL
              value: spark://spark-master-svc:7077
            # If you use a custom properties file, it must be loaded using a ConfigMap
            - name: SPARK_WORKER_OPTS
              value: 
          envFrom:
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 180
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /
              port: 8080
          startupProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /
              port: 8080
          resources:
            limits: {}
            requests: {}
      volumes:
```

### What do you see instead?

```yaml
# Source: spark/charts/spark/templates/statefulset-worker.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-worker
  namespace: "demo"
  labels:
    app.kubernetes.io/name: spark
    helm.sh/chart: spark-6.4.1
    app.kubernetes.io/instance: spark
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: worker
spec:
  serviceName: spark-headless
  replicas: 2
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: spark
      app.kubernetes.io/instance: spark
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spark
        helm.sh/chart: spark-6.4.1
        app.kubernetes.io/instance: spark
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: worker
    spec:
      
      serviceAccountName: spark
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: spark
                    app.kubernetes.io/instance: spark
                    app.kubernetes.io/component: worker
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
        runAsGroup: 0
        runAsUser: 1001
        seLinuxOptions: {}
      containers:
        - name: spark-worker
          image: docker.io/bitnami/spark:3.3.2-debian-11-r9
          imagePullPolicy: "IfNotPresent"
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
          env:
            - name: SPARK_MODE
              value: "worker"
            - name: BITNAMI_DEBUG
              value: "false"
            - name: SPARK_DAEMON_MEMORY
              value: ""
            ## There are some environment variables whose existence needs
            ## to be checked because Spark checks if they are null instead of an
            ## empty string
            - name: SPARK_WORKER_WEBUI_PORT
              value: "8080"
            - name: SPARK_DAEMON_JAVA_OPTS
              value: ""
            - name: SPARK_MASTER_URL
              value: spark://spark-master-svc:7077
            # If you use a custom properties file, it must be loaded using a ConfigMap
            - name: SPARK_WORKER_OPTS
              value: 
          envFrom:
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 180
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /
              port: 8080
          startupProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /
              port: 8080
          resources:
            limits: {}
            requests: {}
      volumes:
```
