### ISSUE TITLE
Postgres client fails with FATAL error : password authentication failed for user 

### ISSUE THREAD

**Issue by shahamit** [bitnami/charts#15706]
### Name and Version

bitnami/postgres 11.7.0

### What architecture are you using?

None

### What steps will reproduce the bug?

I am trying to add postgresql as a dependency into an open source [java spring boot app](https://github.com/camunda-community-hub/zeeqs/files/8068312/zeeqs-charts.zip) helm chart. I need postgres app version 14.4 hence I am using bitnami/postgres chart version 11.7.0. 

I added the dependency as below
```yaml
dependencies:
- name: postgresql
  version: 11.7.0
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
```
The values.yaml file config for postgres is as below

```yaml
postgres:
  enabled: true
  global:
    postgresql:
      auth:
        database: "zeeqsdb"
        password: "zeebe"
        username: "zeebeuser"
        postgresPassword: "zeebe"
```
The java application configures its postgres connection as below. Here `zeeqs-postgresql` is the kubernetes service name. The username and password match in the postgres and the client configuration though we see the error `Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "zeebeuser"`

```yaml
env:
   - name: spring.datasource.url
      value: jdbc:postgresql://zeeqs-postgresql:5432/zeeqsdb
   - name: spring.datasource.password
      value: "zeebe"
   - name: spring.datasource.username
      value: "zeebeuser"
   - name: spring.datasource.driverClassName
      value: "org.postgresql.Driver"
   - name: spring.jpa.properties.hibernate.dialect
     value: "org.hibernate.dialect.PostgreSQLDialect"
   - name: spring.jpa.hibernate.ddl-auto
     value: "create"
```

On viewing the secret create by postgres through `kubectl get secrets/zeeqs-postgresql -o jsonpath="{.data.postgres-password}"` I see a randomly generated base64 encoded password `SEk1Q0diU0M3Tg==`. Decoding it shows `HI5CGbSC7N`

Is my configuration correct?

### What is the expected behavior?

The java application should connect with the postgres database successfully.

### What do you see instead?

An exception on the java postgres client
`Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "zeebeuser"`

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami postgresql container image or Helm chart but about how the application or environment is being used/configured.

It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by shahamit** [comment]
@carrodher - thanks for the reply. 

Can you please confirm if the postgres helm values file config is accurate? I am re-pasting it below for easy read. From the secret created by postgres helm chart it seemed that on every deployment a new password was getting generated for the `zeebeuser` which indicated that the config wasn't right or is incomplete. Kindly confirm.

Thanks.

```yaml
postgres:
  enabled: true
  global:
    postgresql:
      auth:
        database: "zeeqsdb"
        password: "zeebe"
        username: "zeebeuser"
        postgresPassword: "zeebe"
```
