### ISSUE TITLE
[bitnami/mariadb] Liveness/Readiness checks failing resulting in root password not set

### ISSUE THREAD

**Issue by iomarcovalente** [bitnami/charts#1570]
**Which chart**: 

name: mariadb-galera
appVersion: 10.3.18
version: 0.5.0

**Description**

Installing chart manually from helm template should work but does not.
The problem, it seems, is that the first pod is stuck at the starting phase when starting the mariadb-galera on a fresh environment:
 ```
17:02:43.15 
 17:02:43.15 Welcome to the Bitnami mariadb-galera container
 17:02:43.15 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
 17:02:43.15 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
 17:02:43.15 Send us your feedback at containers@bitnami.com
 17:02:43.15 
 17:02:43.15 INFO  ==> ** Starting MariaDB setup **
 17:02:43.19 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
 17:02:43.24 INFO  ==> Initializing mariadb database...
 17:03:58.84 INFO  ==> Starting mariadb in background
```

Based on my findings, after disabling readiness and liveness checks, it looks like the pods wait for all to be up and running before continuing and starting the mysql socket. 
Without a socket, the pod would not responde to the checks and restart. 
Restarting results in the database to start with empty root password and not setting other users - failing as a result on every attempt of performing checks.
 
**Steps to reproduce the issue:**

1. Install the chart with non empty root password

**Describe the results you received:**

Chart fails deployment

**Describe the results you expected:**

Chart to deploy pods without issues

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
```

**Comment by iomarcovalente** [comment]
Here is manifests that I am applying:

```
---
# Source: mariadb-galera/templates/pdb.yaml

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: test-release-mariadb-galera
  labels:
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-0.5.0
    app.kubernetes.io/instance: test-release
    
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb-galera
      app.kubernetes.io/instance: test-release

---
# Source: mariadb-galera/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-release-mariadb-galera
  labels:
    app.kubernetes.io/name: mariadb-galera
    app.kubernetes.io/instance: test-release
type: Opaque
data:
  mariadb-root-password: {{ root_user_password }}
  mariadb-password: {{ dbadmin_user_password }}
  mariadb-galera-mariabackup-password: {{ mariadb_backup_password }}

---
# Source: mariadb-galera/templates/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: test-release-mariadb-galera-configuration
  labels:
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-0.5.0
    app.kubernetes.io/instance: test-release
    
data:
  my.cnf: |
    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    plugin_dir=/opt/bitnami/mariadb/plugin
    
    [mysqld]
    default-storage-engine=InnoDB
    basedir=/opt/bitnami/mariadb
    datadir=/bitnami/mariadb/data
    plugin_dir=/opt/bitnami/mariadb/plugin
    tmpdir=/opt/bitnami/mariadb/tmp
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    bind-address=0.0.0.0
    
    ## Character set
    collation-server=utf8_unicode_ci
    init-connect='SET NAMES utf8'
    character-set-server=utf8
    
    ## MyISAM
    key-buffer-size=32M
    myisam-recover-options=FORCE,BACKUP
    
    ## safety
    skip-host-cache
    skip-name-resolve
    max-allowed-packet=16M
    max-connect-errors=1000000
    sql-mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY
    sysdate-is-now=1
    innodb=FORCE
    innodb-strict-mode=1
    innodb_file_per_table=1
    # Mandatory per https://github.com/codership/documentation/issues/25
    innodb-autoinc-lock-mode=2
    # Per https://www.percona.com/blog/2006/08/04/innodb-double-write/
    innodb-doublewrite=1
    # Not fully ACID compliant, up to 1sec transaction loss in the event of total cluster failure (across both regions)
    # Enabled for performance per https://mariadb.com/kb/en/mariadb/getting-started-with-mariadb-galera-cluster/
    innodb_flush_log_at_trx_commit=0
    
    ## binary logging
    log-bin=mysql-bin
    expire-logs-days=14
    # Disabling for performance per http://severalnines.com/blog/9-tips-going-production-galera-cluster-mysql
    sync-binlog=0
    # Required for Galera
    binlog-format=row
    ## Caches and limits
    tmp-table-size=32M
    max-heap-table-size=32M
    # Re-enabling as now works with Maria 10.1.2
    query-cache-type=1
    query-cache-limit=4M
    query-cache-size=256M
    max-connections=500
    thread-cache-size=50
    open-files-limit=65535
    table-definition-cache=4096
    table-open-cache=4096
    ## innodb
    innodb-flush-method=O_DIRECT
    innodb-log-files-in-group=2
    innodb-log-file-size=128M
    innodb-flush-log-at-trx-commit=1
    innodb-file-per-table=1
    # 80% Memory is default reco.
    # Need to re-evaluate when DB size grows
    innodb-buffer-pool-size=2G
    innodb_file_format=Barracuda
    
    ## logging
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    slow-query-log-file=/opt/bitnami/mariadb/logs/mysqld.log
    log-queries-not-using-indexes=1
    slow-query-log=1
    
    [galera]
    wsrep_on=ON
    wsrep_provider=/opt/bitnami/mariadb/lib/libgalera_smm.so
    wsrep_sst_method=mariabackup
    wsrep_slave_threads=4
    wsrep_cluster_address=gcomm://
    wsrep_cluster_name=galera
    wsrep_sst_auth="root:"
    innodb-flush-log-at-trx-commit=2
    # MYISAM REPLICATION SUPPORT #
    wsrep_replicate_myisam=ON
    
    [mariadb]
    plugin_load_add=auth_pam


---
# Source: mariadb-galera/templates/tests.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-release-mariadb-galera-tests
data:
  run.sh: |-
    @test "Testing MariaDB is accessible" {
      mysql -h test-release-mariadb-galera -uroot -p$MARIADB_ROOT_PASSWORD -e 'show databases;'
    }

---
# Source: mariadb-galera/templates/headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-release-mariadb-galera-headless
  labels:
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-0.5.0
    app.kubernetes.io/instance: test-release
    
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: galera
    port: 4567
    targetPort: galera
  - name: ist
    port: 4568
    targetPort: ist
  - name: sst
    port: 4444
    targetPort: sst
  selector:
    app.kubernetes.io/name: mariadb-galera
    app.kubernetes.io/instance: test-release

---
# Source: mariadb-galera/templates/metrics-svc.yaml

apiVersion: v1
kind: Service
metadata:
  name: test-release-mariadb-galera-metrics
  labels:
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-0.5.0
    app.kubernetes.io/instance: test-release
    
  annotations: 
    prometheus.io/port: "9104"
    prometheus.io/scrape: "true"
    
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9104
    targetPort: metrics
  selector:
    app.kubernetes.io/name: mariadb-galera
    app.kubernetes.io/instance: test-release

---
# Source: mariadb-galera/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-release-mariadb-galera
  labels:
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-0.5.0
    app.kubernetes.io/instance: test-release
    
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app.kubernetes.io/name: mariadb-galera
    app.kubernetes.io/instance: test-release

---
# Source: mariadb-galera/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-release-mariadb-galera
  labels:
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-0.5.0
    app.kubernetes.io/instance: test-release
    
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-release
      app.kubernetes.io/name: mariadb-galera
  serviceName: test-release-mariadb-galera
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mariadb-galera
        app.kubernetes.io/instance: test-release
        helm.sh/chart: mariadb-galera-0.5.0
    spec:
      serviceAccountName: default
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: mariadb-galera
                  app.kubernetes.io/instance: test-release      
      containers:
      - name: "mariadb-galera"
        image: docker.io/bitnami/mariadb-galera:10.3.18-debian-9-r32
        imagePullPolicy: "IfNotPresent"
        env:
        - name: BITNAMI_DEBUG
          value: "true"
        - name: MARIADB_GALERA_CLUSTER_NAME
          value: "galera"
        - name: MARIADB_GALERA_CLUSTER_ADDRESS
          value: "gcomm://test-release-mariadb-galera-headless.kube-system.svc.cluster.local"
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-release-mariadb-galera
              key: mariadb-root-password
        - name: MARIADB_USER
          value: "dbAdmin"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-release-mariadb-galera
              key: mariadb-password
        - name: MARIADB_DATABASE
          value: "default_db"
        - name: MARIADB_GALERA_MARIABACKUP_USER
          value: mariabackup
        - name: MARIADB_GALERA_MARIABACKUP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-release-mariadb-galera
              key: mariadb-galera-mariabackup-password
        ports:
        - name: mysql
          containerPort: 3306
        - name: galera
          containerPort: 4567
        - name: ist
          containerPort: 4568
        - name: sst
          containerPort: 4444
        livenessProbe:
          exec:
            command: ["sh", "-c", "exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD"]
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["sh", "-c", "exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 2000m
            memory: 1Gi
          
        volumeMounts:
        - name: data
          mountPath: /bitnami/mariadb
        - name: mariadb-galera-config
          mountPath: /opt/bitnami/mariadb/conf/my.cnf
          subPath: my.cnf
      - name: metrics
        image: docker.io/bitnami/mysqld-exporter:0.12.1-debian-9-r74
        imagePullPolicy: "IfNotPresent"
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-release-mariadb-galera
              key: mariadb-root-password
        command: [ 'sh', '-c', 'DATA_SOURCE_NAME="root:$MARIADB_ROOT_PASSWORD@(localhost:3306)/" /bin/mysqld_exporter' ]
        ports:
        - name: metrics
          containerPort: 9104
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
          
      volumes:
        - name: mariadb-galera-config
          configMap:
            name: test-release-mariadb-galera-configuration
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/name: mariadb-galera
          app.kubernetes.io/instance: test-release
          
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "{{ mariadb_storage_size }}"
        storageClassName: {{ mariadb_storage_class }}
```
