### ISSUE TITLE
[elasticsearch] unable to deploy in single node

### ISSUE THREAD

**Issue by davgia** [bitnami/charts#15710]
### Name and Version

elasticsearch (19.6.0)

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Just deploy the chart in a separate empty namespace, like:

`helm upgrade --install elasticsearch bitnami/elasticsearch -n elasticsearch -f es_values.yaml --create-namespace`

### Are you using any custom parameters or values?

```yaml
global:
  kibanaEnabled: true

nameOverride: "elasticsearch"
fullnameOverride: "elasticsearch"

config:
  discovery:
    type: single-node
  network:
    host: 0.0.0.0

master:
  replicaCount: 1

data:
  replicaCount: 0

coordinating:
  replicaCount: 0

ingest:
  enabled: false
```

### What is the expected behavior?

I should be able to have the single elasticsearch pod healthy and running.

### What do you see instead?

The elasticsearch pod goes into crashloopbackoff due to the following error:

```
elasticsearch 17:00:31.96 
elasticsearch 17:00:31.97 Welcome to the Bitnami elasticsearch container
elasticsearch 17:00:31.98 Subscribe to project updates by watching https://github.com/bitnami/containers
elasticsearch 17:00:31.98 Submit issues and feature requests at https://github.com/bitnami/containers/issues
elasticsearch 17:00:32.00 
elasticsearch 17:00:32.02 INFO  ==> ** Starting Elasticsearch setup **
warning: ignoring JAVA_HOME=/opt/bitnami/java; using ES_JAVA_HOME
elasticsearch 17:00:39.72 INFO  ==> Configuring/Initializing Elasticsearch...
elasticsearch 17:00:39.84 INFO  ==> Custom configuration file detected, using it...
elasticsearch 17:00:40.22 INFO  ==> ** Elasticsearch setup finished! **

elasticsearch 17:00:40.29 INFO  ==> ** Starting Elasticsearch **
warning: ignoring JAVA_HOME=/opt/bitnami/java; using ES_JAVA_HOME
Exception in thread "main" java.nio.file.FileSystemException: /opt/bitnami/elasticsearch/config/elasticsearch.yml.EyoRKb_4RlCf6oEGM8wy_g.tmp -> /opt/bitnami/elasticsearch/config/elasticsearch.yml: Device or resource busy
    at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
    at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:416)
    at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:266)
    at java.base/java.nio.file.Files.move(Files.java:1432)
    at org.elasticsearch.xpack.security.cli.AutoConfigureNode.fullyWriteFile(AutoConfigureNode.java:1127)
    at org.elasticsearch.xpack.security.cli.AutoConfigureNode.fullyWriteFile(AutoConfigureNode.java:1139)
    at org.elasticsearch.xpack.security.cli.AutoConfigureNode.execute(AutoConfigureNode.java:687)
    at org.elasticsearch.server.cli.ServerCli.autoConfigureSecurity(ServerCli.java:160)
    at org.elasticsearch.server.cli.ServerCli.execute(ServerCli.java:81)
    at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
    at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
    at org.elasticsearch.cli.Command.main(Command.java:50)
    at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)
```

**Comment by aoterolorenzo** [comment]
Hi @davgia,

This could be related to the Elasticsearch's autoconfiguration of security settings.

Could you try disabling this feature by adding the following environment variable to your values.yaml file?:

```
master:
  extraEnvVars:
    - name: ELASTICSEARCH_AUTOCONFIGURE_SECURITY
      value: "no"
```

So the file would remain:

```
global:
  kibanaEnabled: true

nameOverride: "elasticsearch"
fullnameOverride: "elasticsearch"

config:
  discovery:
    type: single-node
  network:
    host: 0.0.0.0

master:
  replicaCount: 1
  extraEnvVars:
      - name: ELASTICSEARCH_AUTOCONFIGURE_SECURITY
        value: "no"

data:
  replicaCount: 0

coordinating:
  replicaCount: 0

ingest:
  enabled: false
```

**Comment by davgia** [comment]
> Hi @davgia,
> 
> This could be related to the Elasticsearch's autoconfiguration of security settings.
> 
> Could you try disabling this feature by adding the following environment variable to your values.yaml file?:
> 
> ```
> master:
>   extraEnvVars:
>     - name: ELASTICSEARCH_AUTOCONFIGURE_SECURITY
>       value: "no"
> ```
> 
> So the file would remain:
> 
> ```
> global:
>   kibanaEnabled: true
> 
> nameOverride: "elasticsearch"
> fullnameOverride: "elasticsearch"
> 
> config:
>   discovery:
>     type: single-node
>   network:
>     host: 0.0.0.0
> 
> master:
>   replicaCount: 1
>   extraEnvVars:
>       - name: ELASTICSEARCH_AUTOCONFIGURE_SECURITY
>         value: "no"
> 
> data:
>   replicaCount: 0
> 
> coordinating:
>   replicaCount: 0
> 
> ingest:
>   enabled: false
> ```

Hi @aoterolorenzo,

thank you for the support but the problem persists. I double checked and the environment variable is present in the deployment resource.

**Comment by janosmiko** [comment]
Hi @davgia 

I was messing around this issue too during the last days. I found this config is working:

```
elasticsearch:
  image:
    registry: docker.io
    repository: bitnami/elasticsearch
    tag: 7.16.3
  antiAffinity: "soft"
  sysctlImage:
    enabled: true
    resources:
      limits:
        cpu: 25m
        memory: 16Mi
      requests:
        cpu: 25m
        memory: 16Mi
  extraConfig:
    xpack.ml.enabled: false
    bootstrap.system_call_filter: false
  extraEnvs:
    - name: discovery.type
      value: single-node
    - name: cluster.initial_master_nodes
      value: ""
    - name: network.host
      value: 0.0.0.0
    - name: transport.host
      value: 127.0.0.1
  master:
    masterOnly: false
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 512Mi
  coordinating:
    replicaCount: 0
  data:
    replicaCount: 0
  ingest:
    replicaCount: 0
```

I hope this helps to you too

**Comment by davgia** [comment]
Hi @janosmiko,

Thanks for the tip. I ended up with the following working configuration:

``` yaml
global:
  kibanaEnabled: true

nameOverride: "elasticsearch"
fullnameOverride: "elasticsearch"

extraConfig:
  discovery:
    type: single-node
  network:
    host: 0.0.0.0
  transport:
    host: 127.0.0.1
  cluster:
    initial_master_nodes: ""

master:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1024Mi

data:
  replicaCount: 0

coordinating:
  replicaCount: 0

ingest:
  enabled: false
```

**Comment by aoterolorenzo** [comment]
@janosmiko @davgia thank you both. 

My thoughts now are about the `config` parameter. `extraConfig` appends config to the chart-native elasticsearch one, while `config` overwrites it completely so the thing is: maybe there is kind of a config parameter that is overwritten when used `config`, that remains when using `extraConfig`, and that's why maybe we had this working?

I think that at least is coherent to deeper investigate this and see if it is really a bug or a misconfiguration or a tricky configuration need. I will create a task for the team to take a look, leaving this as on-hold. We will reach you back here with the outcome.

**Comment by aoterolorenzo** [comment]
Hey @janosmiko 

Yes, what I've understood is that passing the values with through the `config` value resulted in a misconfiguration, that's why I asked if that was happening or @davgia just tried to use the `config` value to put the specific values without realising that the rest of the parameters in the `elasticsearch.yaml` would be overwritting.

So, as I understand now from your comment, is that using the `config` value properly (setting not only the specific use case parameters but all the necessary to compose a functional `elasticsearch.yaml`) works as expected and there's no bug, is it?

**Comment by aoterolorenzo** [comment]
It seem so. Closing this then, thank you for your help!

**Comment by davgia** [comment]
Hi @janosmiko @aoterolorenzo,

I understand the reasoning behind the last comments but I still don't get the error I got.

**Comment by aoterolorenzo** [comment]
Hi [davgia](https://github.com/davgia),

Sorry I haven't been pretty understandable there. As the `config` value overwrites the entire config file, using:

```
config:
  discovery:
    type: single-node
  network:
    host: 0.0.0.0
```
 
Will result in an elasticsearch config with just those parameters:

elasticsearch.yml
```
  discovery:
    type: single-node
  network:
    host: 0.0.0.0
```

What we would need to check, is to put a functional set of elasticsearch configuration parameters in that `config` value, since I assume that there are several configuration parameters needed to run elasticsearch more than those.

So maybe your problem resided in you were overwriting parameters in the original config file. That's why using the `extraConfig` value instead of the `config` value, would work.

**Comment by davgia** [comment]
> Hi [davgia](https://github.com/davgia),
> 
> Sorry I haven't been pretty understandable there. As the `config` value overwrites the entire config file, using:
> 
> ```
> config:
>   discovery:
>     type: single-node
>   network:
>     host: 0.0.0.0
> ```
> 
> Will result in an elasticsearch config with just those parameters:
> 
> elasticsearch.yml
> 
> ```
>   discovery:
>     type: single-node
>   network:
>     host: 0.0.0.0
> ```
> 
> What we would need to check, is to put a functional set of elasticsearch configuration parameters in that `config` value, since I assume that there are several configuration parameters needed to run elasticsearch more than those.
> 
> So maybe your problem resided in you were overwriting parameters in the original config file. That's why using the `extraConfig` value instead of the `config` value, would work.

Ok got it now. The problem is that providing working parameters in the `config` value would not change the error I'm seeing that it's not related to elasticsearch (/opt/bitnami/elasticsearch/config/elasticsearch.yml: Device or resource busy). I'm afraid that any change to `config` value will result in the same outcome. I hope I've been more clear this time. In any case this issue caused by a misconfiguration on my side. We all agree that `extraConfig` needs to be used when you want to extend the configuration without overriding it.

**Comment by migruiz4** [comment]
Hi @davgia,

Wouldn't the following values work for you? This way, you won't need to override or add extra configuration to your deployment:

```
master:
  masterOnly: false
  replicaCount: 1
data:
  replicaCount: 0
ingest:
  replicaCount: 0
coordinating:
  replicaCount: 0
```

This won't configure `discovery.type: single-node` exactly, but it is the easiest and straightest way to deploy a single node.
In my case, the resulting `elasticsearch.yaml` would be:
```
http:
  port: "9200"
path:
  data: /bitnami/elasticsearch/data
transport:
  port: "9300"
network:
  host: test-elasticsearch-master-0.test-elasticsearch-master-hl.default.svc.cluster.local
  publish_host: test-elasticsearch-master-0.test-elasticsearch-master-hl.default.svc.cluster.local
  bind_host: 0.0.0.0
cluster:
  name: elastic
  initial_master_nodes: test-elasticsearch-master-0
node:
  name: test-elasticsearch-master-0
discovery:
  seed_hosts: test-elasticsearch-master-hl.default.svc.cluster.local
  initial_state_timeout: 10m
xpack:
  security:
    enabled: "false"
  ml:
    enabled: "false"
```

One of the main differences between setting `discovery.seed_hosts` and `discovery.type: single-node` would be that later you could add additional nodes to build a cluster if desired.

**Comment by davgia** [comment]
Using @migruiz4 suggestion I was able to deploy it without any error. Thanks.

``` yaml
master:
  masterOnly: false
  replicaCount: 1
data:
  replicaCount: 0
ingest:
  replicaCount: 0
coordinating:
  replicaCount: 0
```
