### ISSUE TITLE
Postgres chart with replication

### ISSUE THREAD

**Issue by pausanchezv** [bitnami/charts#15714]
### Name and Version

bitnami/postgresql

### What architecture are you using?

None

### What steps will reproduce the bug?

What's the advantage of using replication if I am not given a headless read/write service as your MySQL chart does? It only gives me a writing service and a read service separately. Which means I need to have 2 connections to the database. And then if I need a PGBouncer between the clients and Postgres I need to obviously point it to the write svc and then the read slaves are never hit. Am I missing something here?

### Are you using any custom parameters or values?
```yaml
global:
  storageClass: premium-rwo

  postgresql:
    auth:
      username: xxx
      postgresPassword: xxx
      password: xxx
      database: xxx

image:
  tag: 15.2.0-debian-11-r14

architecture: replication

readReplicas:
  replicaCount: 2
```
### What is the expected behavior?

Having a headless read/write service that load balances all queries and that I can put a bouncer in front, just like your MySQL chart.

### What do you see instead?

Separated read/write services.
