### ISSUE TITLE
[bitnami/kube-prometheus] Prometheus.monitoring.coreos.com "pr-kube-prometheus-prometheus" is invalid: spec.storage.volumeClaimTemplate.metadata: Invalid value: "null": spec.storage.volumeClaimTemplate.metadata in body must be of type object: "null"

### ISSUE THREAD

**Issue by oktayalizada** [bitnami/charts#15722]
### Name and Version

bitnami/kube-prometheus 8.3.1

### What architecture are you using?

None

### What steps will reproduce the bug?

`helm install pr -f prometheus.yaml bitnami/kube-prometheus --version 8.3.1
`
### Are you using any custom parameters or values?

```
prometheus:
  replicaCount: 3
  service:
    type: NodePort
    clusterIP: None
    nodePort: 32702
  thanos:
    service:
      type: NodePort
      nodePort: 32701
  image:
      tag: 2.43.0-debian-11-r0
  persistence:
      enabled: true
      size: 8Gi
  additionalScrapeConfigs:
    enabled: true
    type: external
    external:
      name: prometheus-scrape-config
      key: additional-scrape-configs.yaml
alertmanager:
  enabled: false
  service:
    type: NodePort
    clusterIP: None
    nodePort: 32703
operator:
  image:
    tag: 0.63.0-debian-11-r13
  service:
    type: NodePort
    nodePort: 32704
    clusterIP: None

```
### What is the expected behavior?

Installation succeeds

### What do you see instead?

`Error: INSTALLATION FAILED: Prometheus.monitoring.coreos.com "pr-kube-prometheus-prometheus" is invalid: spec.storage.volumeClaimTemplate.metadata: Invalid value: "null": spec.storage.volumeClaimTemplate.metadata in body must be of type object: "null"`
