### ISSUE TITLE
[bitnami/thanos] do not create default prometheus rules if component is disabled

### ISSUE THREAD

**Issue by antonincms** [bitnami/charts#15721]
### Name and Version

bitnami/thanos 12.3.2

### What is the problem this feature will solve?

When explicitely disabling optional elements of thanos (receive, replicate, ruler comes to mind), if the user use the defaults rules (`metrics.prometheusRule.default.create`) it will create all rules, without taking into account which components are enabled.

We should not enable the IsDown and the group related to disabled elements, and optionally i think if the user still want to enable a rule without enabling the component he could do it by enabling the corresponding `metrics.prometheusRule.default.<component>` instead.

### What is the feature you are proposing to solve the problem?

Instead of checking 
```
{{- if and .Values.metrics.enabled (or .Values.metrics.prometheusRule.default.create .Values.metrics.prometheusRule.default.receive ) }}
```

We could check 
```
{{- if and .Values.metrics.enabled (or (and .Values.metrics.prometheusRule.default.create .Values.receive.enabled) .Values.metrics.prometheusRule.default.receive ) }}
```

For the IsDown, we should maybe add a way to force enable them if that's something wanted. 

### What alternatives have you considered?

Currently we cannot enable "create" and instead do something like so 
```yaml
metrics:
  enabled: true
  prometheusRule:
    enabled: true
    default:
      absent_rules: true
      compaction: true
      query: true
      receive: false # Disabled because receive component is disabled
      replicate: false # Disabled because replicate component is disabled
      ruler: false # Disabled because ruler component is disabled
      sidecar: true
      store_gateway: true
      disabled:
        ThanosReceiveIsDown: true
        # There is no ThanosReplicateIsDown
        ThanosRuleIsDown: true
```
