### ISSUE TITLE
ExternalDNS fails to update Route53 in a Dual Stacked environment

### ISSUE THREAD

**Issue by jamesharr** [bitnami/charts#15741]
### Name and Version

bitnami/external-dns:0.13.3-debian-11-r3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Start with a dual-stack Kubernetes environment (K3S in my case)
2. Deploy an Ingress Controller (ingress-nginx in my case) with RequireDualStack enabled
3. Deploy external-dns using the `aws` provider with appropriate credentials
4. Deploy an example service with an Intgress
5. Observe that the Ingress has been assigned both an IPv4 and IPv6 address
6. Observe that the ExternalDNS logs and see that the AWS provider is attempting to create an A record with an IPv6 address in it.

### What is the expected behavior?

I expect both the A and AAAA record to be created in ExternalDNS

### What do you see instead?

Neither an IPv4 nor an IPv6 DNS record is created and the following appears in the logs for external-dns

```
time="2023-03-24T19:18:40Z" level=info msg="Applying provider record filter for domains: [REDACTED.]"
time="2023-03-24T19:18:40Z" level=info msg="Desired change: CREATE a-echo1.testing.REDACTED TXT [Id: /hostedzone/Z02739221C9PML4J93YDL]"
time="2023-03-24T19:18:40Z" level=info msg="Desired change: CREATE echo1.testing.REDACTED A [Id: /hostedzone/Z02739221C9PML4J93YDL]"
time="2023-03-24T19:18:40Z" level=info msg="Desired change: CREATE echo1.testing.REDACTED TXT [Id: /hostedzone/Z02739221C9PML4J93YDL]"
time="2023-03-24T19:18:40Z" level=error msg="Failure in zone REDACTED. [Id: /hostedzone/Z02739221C9PML4J93YDL] when submitting change batch: InvalidChangeBatch: [Invalid Resource Record: 'FATAL problem: ARRDATAIllegalIPv4Address (Value is not a valid IPv4 address) encountered with '2001:REDACTED::31'']\n\tstatus code: 400, request id: 07fd77f1-d239-458b-9b9d-ca12c425e649"
time="2023-03-24T19:18:41Z" level=error msg="failed to submit all changes for the following zones: [/hostedzone/Z02739221C9PML4J93YDL]"
```

### Additional information

Note that this cluster is not inside AWS and does not make use of EC2 roles or anything like that.

Helm Values used for ExternalDNS:
```yaml
aws:
  credentials:
    accessKey: REDACTED
    secretKey: REDACTED
domainFilters:
- REDACTED
policy: upsert-only
provider: aws
triggerLoopOnEvent: true
txtOwnerId: salt-kprd2.REDACTED
```

The following is the helm version deployed
```sh
% helm list -n external-dns-system
NAME        	NAMESPACE          	REVISION	UPDATED                                	STATUS  	CHART              	APP VERSION
external-dns	external-dns-system	44      	2023-03-23 21:34:50.320270437 +0000 UTC	deployed	external-dns-6.14.4	0.13.3
```

The following pod manifests are used for testing
```yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echo1
spec:
  secretName: echo-tls
  subject:
    organizationalUnits:
      - "My Org Unit"
  dnsNames:
    - echo1.testing.REDACTED
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cert-manager-ecc
---
apiVersion: v1
kind: Service
metadata:
  name: echo1
spec:
  ports:
    - port: 80
      targetPort: 5678
  selector:
    app: echo1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo1
spec:
  selector:
    matchLabels:
      app: echo1
  replicas: 2
  template:
    metadata:
      labels:
        app: echo1
    spec:
      containers:
        - name: echo1
          image: hashicorp/http-echo
          args:
            - "-text=echo1"
          ports:
            - containerPort: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:
spec:
  ingressClassName: public-web
  tls:
    - hosts:
        - echo1.testing.REDACTED
      secretName: echo-tls
  rules:
    - host: echo1.testing.REDACTED
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: echo1
                port:
                  number: 80

```
