### ISSUE TITLE
[mongodb-sharded] Selector label for shard number in data nodes is missing.

### ISSUE THREAD

**Issue by fortra-cloudops-platform** [bitnami/charts#15812]
### Name and Version

bitnami/mongodb-sharded:6.3.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Run Mongo cluster with more than 1 shard. 

### Are you using any custom parameters or values?

```yaml
shardsvr:
  dataNode:
    replicaCount: 2
    resources:
      requests:
        cpu: 500m
        memory: 500M
      limits:
        cpu: 1000m
        memory: 1G
    readinessProbe:
      enabled: false
    customReadinessProbe:
      exec:
        command:
          - /bin/sh
          - -c
          - mongosh --tlsCertificateKeyFile=/certs/tls-combined.pem --tlsCAFile=/certs/ca.crt --tls --port $MONGODB_PORT_NUMBER --eval "db.adminCommand('ping')"
      failureThreshold: 6
      initialDelaySeconds: 10
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 20
    mongodbExtraFlags:
      - "--wiredTigerCacheSizeGB=0.5"
      - "--enableFreeMonitoring=off"
      - "--tlsMode=requireTLS"
      - "--tlsCertificateKeyFile=/certs/tls-combined.pem"
      - "--tlsCAFile=/certs/ca.crt"
    extraEnvVars:
      - name: MONGODB_SHELL_EXTRA_FLAGS
        value: "--tls --tlsCertificateKeyFile=/certs/tls-combined.pem --tlsCAFile=/certs/ca.crt"
    pdb:
      create: true
      maxUnavailable: 1
  persistence:
    enabled: true
    size: 100Gi
    resourcePolicy: keep
```

### What is the expected behavior?

Each StatefulSet has the appropriate `selectorLabels`

### What do you see instead?

Every Shard StatefulSet has the same `selectorLabels`

```yaml
  selector:
    matchLabels:
      app.kubernetes.io/component: shardsvr
      app.kubernetes.io/instance: mongodb
      app.kubernetes.io/name: mongodb-sharded
```
