### ISSUE TITLE
[bitnami/argo-cd]  Helm chart argocd v4.5.3  wrong

### ISSUE THREAD

**Issue by dellnoantechnp** [bitnami/charts#15820]
### Name and Version

bitnami/argocd 4.5.3

### What architecture are you using?

None

## Environment
1. Kubernetes 1.23
2. Helm 3.10
3. Chart bitnami/argocd v4.5.3  (appVersion: 2.6.7)

## Bug 1:
1. enable Notification `serviceMonitor: true` 
2. install this chart return miss `notifications/servicemonitor.yaml`
```log
argo-cd/templates/notifications/servicemonitor.yaml:5:11: executing "argo-cd/templates/notifications/servicemonitor.yaml" at <include "argo-cd.notifications" .>: error calling include: template: no template "argo-cd.notifications" associated with template "gotpl"
```

## Bug 2:
1. On install complete, webUI version number is wrong
![image](https://user-images.githubusercontent.com/11703403/229046568-fefe1c7a-4a09-46e0-a6b0-a22276d7a781.png)
v99.99.99-unknown 🤣

### What do you see instead?

normal settings.

**Comment by dellnoantechnp** [comment]
Hi @aoterolorenzo 
Maybe I didn't describe it.

yes, I set values like this
```yaml
notifications:
    enabled: true
    metrics:
        enabled: true
        serviceMonitor:
            enabled: true
```
helm return log:
```log
Error: UPGRADE FAILED: template: argo-cd/templates/notifications/servicemonitor.yaml:5:11: executing "argo-cd/templates/notifications/servicemonitor.yaml" at <include "argo-cd.notifications" .>: error calling include: template: no template "argo-cd.notifications" associated with template "gotpl"
```


I have found the cause of this problem.
in file `templates/notifications/servicemonitor.yaml`, line 5 `{{ include "argo-cd.notifications" . }}`, variable name was wrong.
```yaml
{{- if and .Values.notifications.enabled .Values.notifications.metrics.enabled .Values.notifications.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "argo-cd.notifications" . }}
  {{- if .Values.notifications.metrics.serviceMonitor.namespace }}
```
The name should be `{{ include "argocd.notifications" . }}`  not `{{ include "argo-cd.notifications" . }}`.

Modify this file `templates/notifications/servicemonitor.yaml` to change variable name, to be success.
