### ISSUE TITLE
[bitnami/postgresql] password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by gredwhite** [bitnami/charts#15824]
### Name and Version

bitnami/postgres 11.6.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Just install the chart

### Are you using any custom parameters or values?

Values.yaml
```
  postgresql:
    auth:
      database: *dbName
      username: "postgres"
      password: "postgres"
      postgresPassword: "postgres"
    nameOverride: *dbHost
    fullnameOverride: *dbHost
    primary:
      persistence:
        size: 1Gi
      initdb:
        user: "postgres"
        password: "postgres"
        scriptsConfigMap: my-config
```
And template:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  labels:
    ....
data:
{{- with .Files.Glob "files/init-db.sh" }}
{{ .AsConfig | indent 2 }}
{{- end }}
```

### What is the expected behavior?

Sql script is always executed successfully

### What do you see instead?

Sometimes (probability is 10-20%  ) I experience error:

```
Start exec init script for db '***' username=postgres
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  password authentication failed for user "postgres"
```
