### ISSUE TITLE
[bitnami/keycloak] When setting database vendor to dev-mem or dev-file container still tries to reach postgres

### ISSUE THREAD

**Issue by valerii15298** [bitnami/charts#15927]
### Name and Version

**bitnami/keycloak latest**

### What architecture are you using?

**`amd64`**

### What steps will reproduce the bug?

Create file `docker-compose.yml` with the following content:
```yaml
version: "3.8"
services:
  keycloak:
    image: docker.io/bitnami/keycloak:latest
    environment:
      - KEYCLOAK_DATABASE_VENDOR=dev-mem
```
And in the same directory run command `docker compose up`
You will see the output:
```
Trying to connect to PostgreSQL server postgresql...
app-keycloak-1  | cannot resolve host "postgresql": lookup postgresql on 127.0.0.11:53: read udp 127.0.0.1:56799->127.0.0.11:53: i/o timeout
```

### Are you using any custom parameters or values?

no

### What is the expected behavior?

I expect keycloak to use in memory store and successfully start

### What do you see instead?

I see that keycloak server tries to connect to postgres database while it shouldn't do so according to `KEYCLOAK_DATABASE_VENDOR` env variable

### Additional information

What interesting is that for `docker.io/bitnami/keycloak:21` everything works fine without any bugs
