### ISSUE TITLE
[bitnami/keycloak] How do I add my custom provider?

### ISSUE THREAD

**Issue by drunkcattt** [bitnami/charts#15930]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

I see that [bitnami/keycloak](https://github.com/bitnami/containers/tree/main/bitnami/keycloak/) uses bitnami's keycloak, which already has a provider `keycloak-metrics-spi-3.0.0.jar`.

If I want to add my custom provider to this chart, I should mount a volume at `/opt/bitnami/keycloak/providers` and load it in `initContainers`.

But `/opt/bitnami/keycloak/providers` already has `keycloak-metrics-spi-3.0.0.jar` and I have mounted an emptyDir.

```yaml
initContainers:
  - name: download-all-providers
    image: curlimages/curl:8.00.1
    securityContext:
      runAsUser: 1001
    command:
      - "/bin/sh"
      - "-c"
    args:
         curl https://xxx/my_custom_provider.jar \
         -o /opt/bitnami/keycloak/providers/my_custom_provider.jar
    volumeMounts:
      - name: keycloak-providers-volume
        mountPath: /opt/bitnami/keycloak/providers

extraVolumes:
  - name: keycloak-providers-volume
    emptyDir: {}

extraVolumeMounts:
  - name: keycloak-providers-volume
    mountPath: /opt/bitnami/keycloak/providers

```

### What is the feature you are proposing to solve the problem?

Maybe we can put keycloak-metrics-spi-3.0.0.jar into initContainers.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for opening the ticket. Are you proposing to add `keycloak-metrics-spi-3.0.0.jar` into the Keycloak container?

**Comment by Tuxzx** [comment]
> Hi,
> 
> Thank you so much for opening the ticket. Are you proposing to add `keycloak-metrics-spi-3.0.0.jar` into the Keycloak container?

@javsalgar Thanks for your reply.

I need this feature.
 
In the current case, I have to mount the entire `/opt/bitnami/keycloak/providers` directory, then download the bitnami packaged keycloak with `keylcoak-metric-spi.jar`(from here   https://github.com/bitnami/containers/blob/8dfdfe3a64f358cb3ee9eb6f4f8586e03dec7d00/bitnami/keycloak/21/debian-11/Dockerfile#L33 ), copy the jar and mount it with my custom provider.

**Comment by javsalgar** [comment]
Hi,

The container has support for custom init scripts

```
########################
# Run custom initialization scripts
# Globals:
#   KEYCLOAK_*
# Arguments:
#   None
# Returns:
#   None
#########################
keycloak_custom_init_scripts() {
    if [[ -n $(find "${KEYCLOAK_INITSCRIPTS_DIR}/" -type f -regex ".*\.sh") ]] && [[ ! -f "${KEYCLOAK_INITSCRIPTS_DIR}/.user_scripts_initialized" ]]; then
        info "Loading user's custom files from ${KEYCLOAK_INITSCRIPTS_DIR} ..."
        local -r tmp_file="/tmp/filelist"
        find "${KEYCLOAK_INITSCRIPTS_DIR}/" -type f -regex ".*\.sh" | sort >"$tmp_file"
        while read -r f; do
            case "$f" in
            *.sh)
                if [[ -x "$f" ]]; then
                    debug "Executing $f"
                    "$f"
                else
                    debug "Sourcing $f"
                    . "$f"
                fi
                ;;
            *) debug "Ignoring $f" ;;
            esac
        done <$tmp_file
        rm -f "$tmp_file"
        touch "$KEYCLOAK_VOLUME_DIR"/.user_scripts_initialized
    fi
}

```

Therefore, if instead of mounting the folder at the providers dirs you mount it somewhere else and then use a init script to copy your provider, I believe it should work without issues. Could you give that a try?

**Comment by Tuxzx** [comment]
> Hi,
> 
> The container has support for custom init scripts
> 
> ```
> ########################
> # Run custom initialization scripts
> # Globals:
> #   KEYCLOAK_*
> # Arguments:
> #   None
> # Returns:
> #   None
> #########################
> keycloak_custom_init_scripts() {
>     if [[ -n $(find "${KEYCLOAK_INITSCRIPTS_DIR}/" -type f -regex ".*\.sh") ]] && [[ ! -f "${KEYCLOAK_INITSCRIPTS_DIR}/.user_scripts_initialized" ]]; then
>         info "Loading user's custom files from ${KEYCLOAK_INITSCRIPTS_DIR} ..."
>         local -r tmp_file="/tmp/filelist"
>         find "${KEYCLOAK_INITSCRIPTS_DIR}/" -type f -regex ".*\.sh" | sort >"$tmp_file"
>         while read -r f; do
>             case "$f" in
>             *.sh)
>                 if [[ -x "$f" ]]; then
>                     debug "Executing $f"
>                     "$f"
>                 else
>                     debug "Sourcing $f"
>                     . "$f"
>                 fi
>                 ;;
>             *) debug "Ignoring $f" ;;
>             esac
>         done <$tmp_file
>         rm -f "$tmp_file"
>         touch "$KEYCLOAK_VOLUME_DIR"/.user_scripts_initialized
>     fi
> }
> ```
> 
> Therefore, if instead of mounting the folder at the providers dirs you mount it somewhere else and then use a init script to copy your provider, I believe it should work without issues. Could you give that a try?

In my case, just override this param.

```
initdbScripts:
  load_custom_provider_script.sh: |
    #!/bin/bash
    echo "load_custom_provider_script.sh"
    curl -sS https://xxx/my_custom_provider.jar -o /opt/bitnami/keycloak/providers/my_custom_provider.jar
```

Thank you.

**Comment by chominnn** [comment]
> > 안녕,
> > 컨테이너는 사용자 정의 init 스크립트를 지원합니다.
> > ```
> > ########################
> > # Run custom initialization scripts
> > # Globals:
> > #   KEYCLOAK_*
> > # Arguments:
> > #   None
> > # Returns:
> > #   None
> > #########################
> > keycloak_custom_init_scripts() {
> >     if [[ -n $(find "${KEYCLOAK_INITSCRIPTS_DIR}/" -type f -regex ".*\.sh") ]] && [[ ! -f "${KEYCLOAK_INITSCRIPTS_DIR}/.user_scripts_initialized" ]]; then
> >         info "Loading user's custom files from ${KEYCLOAK_INITSCRIPTS_DIR} ..."
> >         local -r tmp_file="/tmp/filelist"
> >         find "${KEYCLOAK_INITSCRIPTS_DIR}/" -type f -regex ".*\.sh" | sort >"$tmp_file"
> >         while read -r f; do
> >             case "$f" in
> >             *.sh)
> >                 if [[ -x "$f" ]]; then
> >                     debug "Executing $f"
> >                     "$f"
> >                 else
> >                     debug "Sourcing $f"
> >                     . "$f"
> >                 fi
> >                 ;;
> >             *) debug "Ignoring $f" ;;
> >             esac
> >         done <$tmp_file
> >         rm -f "$tmp_file"
> >         touch "$KEYCLOAK_VOLUME_DIR"/.user_scripts_initialized
> >     fi
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 따라서 제공자 디렉토리에 폴더를 마운트하는 대신 다른 곳에 마운트한 다음 init 스크립트를 사용하여 제공자를 복사하면 문제 없이 작동할 것으로 생각합니다. 시도해 볼 수 있나요?
> 
> 제 경우에는 이 매개변수를 재정의하면 됩니다.
> 
> ```
> initdbScripts:
>   load_custom_provider_script.sh: |
>     #!/bin/bash
>     echo "load_custom_provider_script.sh"
>     curl -sS https://xxx/my_custom_provider.jar -o /opt/bitnami/keycloak/providers/my_custom_provider.jar
> ```
> 
> 감사합니다.

i love u from korea

**Comment by eraserx99** [comment]
Hi,

  I got a question here. The default configuration sets the root file system of Keycloak container to read-only. It means, touch "$KEYCLOAK_VOLUME_DIR"/.user_scripts_initialized, of keycloak_custom_init_scripts would fail. I can set the root file system read-only to false to make it work. However, is it the only/right way?

**Comment by danvy** [comment]
Copying files using init scripts is not longer allowed.
I had to create my own docker image to copy files.
I did not try to set containerSecurityContext.readOnlyRootFilesystem to false.

**Comment by eraserx99** [comment]
hi @danvy 

  Yes, I was thinking about creating my own image too. Instead, I set the containerSecurityContext.readOnlyRootFilesystem to false to play around first. It does work, but it might not be a good idea. I posted it here to remind the potential issue with keycloak_custom_init_scripts when someone runs into it...

**Comment by javsalgar** [comment]
Hi,

It seems like a regression to me, as having readOnlyRootFilesystem=true should not break the init scripts. The statefulset volumes section should look like this:

```
            - name: empty-dir
              mountPath: /bitnami
              subPath: app-volume-dir
```

As you discovered the issue, would you like to submit a PR adding this to the `volumes` section?

**Comment by eraserx99** [comment]
Hi @javsalgar Sorry that I'm getting stuck with other projects in hand now. Can you help submit the PR? Thanks!

**Comment by bork91** [comment]
This commit https://github.com/bitnami/charts/commit/9de041c92e2788a108631052aa5401a9469e3592 have made it posible to add own providers with at initContainer.

```
initContainers: |
    - name: keycloak-plugin
      image: my-plugin
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying module..."
          cp -r /module/* /emptydir/app-providers-dir
      volumeMounts:
        - name: empty-dir
          mountPath: /emptydir
```
