### ISSUE TITLE
[bitnami/postgresql] existingSecret fails on latest chart release

### ISSUE THREAD

**Issue by jseiser** [bitnami/charts#15957]
### Name and Version

12.2.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Create a secret, reference existing secret.

### Are you using any custom parameters or values?

```
auth:
  enablePostgresUser: true
  username: "name"
  database: "database"
  existingSecret: "pql-secret"
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password
    replicationPasswordKey: replication-password
```

secret

```
kubectl create secret generic pql-secret -n namespace \
--from-literal=password=RandomPassword123 \
--from-literal=postgres-password=RandomPassword1234 \
--from-literal=replicationPasswordKey=RandomPassword12345
```

### What is the expected behavior?

Password auth should work.

### What do you see instead?

```
❯ export POSTGRES_PASSWORD=$(kubectl get secret --namespace namespace pql-secret -o jsonpath="{.data.password}" | base64 -d)
❯ PGPASSWORD="$POSTGRES_PASSWORD" psql --host 127.0.0.1 -U name -d database -p 5432
psql: error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "name"
```

```
2023-04-04 13:51:02.430 GMT [293] LOG:  connection received: host=localhost port=41290
2023-04-04 13:51:02.431 GMT [293] FATAL:  password authentication failed for user "name"
2023-04-04 13:51:02.431 GMT [293] DETAIL:  Role "name" does not exist.
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
```

### Additional information

Note, i swapped the real name and database for `name` and `database` in case something randomly doesnt match up.

If you re-use this same setup, for an older release, like `11.9.13` it works as intended.
