### ISSUE TITLE
[bitnami/elasticsearch] Unable to verify the first certificate error

### ISSUE THREAD

**Issue by saintshini** [bitnami/charts#15969]
### Name and Version

bitnami/elasticsearch:19.4.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. I deploy the elasticsearch service on GCP.
2. Kibana has HTTPS and Elasticsearch the autogenerated tls.
3. It deploys correctly but after a while it throws the following error

```
[2023-04-05T12:16:11.272+00:00][WARN ][plugins.licensing] License information could not be obtained from Elasticsearch due to ConnectionError: unable to verify the first certificate error
[2023-04-05T12:16:11.542+00:00][ERROR][plugins.security.authentication] License is not available, authentication is not possible.
```
```
GKE version :  1.24.9-gke.3200
Helm version: version.BuildInfo{Version:"v3.10.1", GoVersion:"go1.18.7"}
Helmfile version: v0.144.0
```

### Are you using any custom parameters or values?

```
security:
  enabled: true
  elasticPassword: "xxxxx"
  fipsMode: false
  tls:
    restEncryption: true
    autoGenerated: true
    verificationMode: "certificate"

kibana:
  elasticsearch:
    security:
      auth:
        enabled: true
        createSystemUser: true
        kibanaUsername: "xxxx" 
        kibanaPassword: "xxxxxx"
      tls:
        enabled: true
        usePemCerts: true
        existingSecret: "xxxx-xxx-xxxx-crt"
    hosts:
      - '{{ include "elasticsearch.service.name" . }}'
    port: '{{ include "elasticsearch.service.ports.restAPI" . }}'
  extraConfiguration:
    elasticsearch:
      hosts:
        - 'https://{{ include "elasticsearch.service.name" . }}:9200'
  tls:
    autoGenerated: true
    enabled: true
  service:
    type: NodePort
    annotations:
      cloud.google.com/app-protocols: '{"https":"HTTPS","http2":"HTTP"}'
      cloud.google.com/backend-config: '{"default": "kibana-backend-healthcheck"}'
```

### What do you see instead?

```
[2023-04-05T12:20:41.287+00:00][WARN ][plugins.licensing] License information could not be obtained from Elasticsearch due to ConnectionError: unable to verify the first certificate error
[2023-04-05T12:20:41.569+00:00][ERROR][plugins.security.authentication] License is not available, authentication is not possible.
[2023-04-05T12:20:49.056+00:00][ERROR][plugins.security.authentication] License is not available, authentication is not possible.
[2023-04-05T12:20:49.060+00:00][ERROR][plugins.security.authentication] License is not available, authentication is not possible.
```

**Comment by rafariossaa** [comment]
Hi, 
I have tried to reproduce your issue by using the following command, and these changes in `values.yaml`:
 
```
$ helm install es bitnami/elasticsearch -f values.yaml
``` 

```
global:
  kibanaEnabled: true
security:
  enabled: true
  elasticPassword: "Testing"
  tls:
    restEncryption: true
    autoGenerated: true
    verificationMode: "certificate"
kibana:
  elasticsearch:
    security:
      auth:
        enabled: true
        createSystemUser: true
        kibanaUsername: "kibanauser" 
        kibanaPassword: "testing"
        elasticsearchPasswordSecret: "es-elasticsearch"
      tls:
        enabled: true
        usePemCerts: true
        existingSecret: "es-elasticsearch-coordinating-crt"
  tls:
    autoGenerated: true
    enabled: true
 ```
 Notice that: 
- `kibana.elasticsearch.security.auth.elasticsearchPasswordSecret` is required when using `createSystemUser`. 
- `kibana.elasticsearch.security.tls.existingSecret` is set to the secret name autogenerated for the nodes used to connect (coordinating).

I am not very sure about why you set the `hosts` parameters in your deployment.

Could you give a try to these changes ?
