### ISSUE TITLE
[bitnami/thanos] Query unable to connect with grpc.server.tls.autoGenerated=true

### ISSUE THREAD

**Issue by pduchnovsky** [bitnami/charts#15974]
### Name and Version

bitnami/thanos 12.1.2

### What architecture are you using?

None

### What steps will reproduce the bug?

Deploy chart with following custom config:
  ```
  # Custom values for thanos.
  query:
    enabled: true
    grpc:
      client:
        tls:
          enabled: true
          autoGenerated: true
  storegateway:
    enabled: true
    grpc:
      server:
        tls:
          enabled: true
          autoGenerated: true
  ```

### What is the expected behavior?

Expected behavior is communication between query/storegateway with TLS enabled, so query could also connect to other stores behind nginx reverse proxy with TLS enabled.

Note that it doesn't work even if extra flag is added to stop validating certs on query:
```
  extraFlags:
  - --grpc-client-tls-skip-verify
```

### What do you see instead?
```
level=warn ts=2023-04-06T07:03:11.196180131Z caller=endpointset.go:446 component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from 10.0.85.117:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.0.85.117:10901
```
