### ISSUE TITLE
[bitnami/postgresql-ha]: with initdbScriptsCM, GRANT ALL ON SCHEMA public TO newuser; not works

### ISSUE THREAD

**Issue by exfly** [bitnami/charts#15977]
### Name and Version

bitnami/postgresql-ha 11.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sharedx-postgresql-ha-postgresql-init-scripts
data:
  init_script.sh: |
    #!/bin/bash
    env
    export PGPASSWORD=$POSTGRES_PASSWORD
    psql -U $POSTGRES_USER -tc "CREATE USER newuser with password 'TODO';" || true
    psql -U $POSTGRES_USER -tc "CREATE DATABASE newuser;" || true
    psql -U $POSTGRES_USER -tc "GRANT CREATE ON SCHEMA public TO PUBLIC;" || true
```

helm upgrade

then exec in postgres-0, psql postgres://newuser:TODO@localhost:5432/newuser?sslmode=disable

```
CREATE TABLE mytable2( t text );
ERROR:  permission denied for schema public
LINE 1: CREATE TABLE mytable2( t text );
```

### Are you using any custom parameters or values?

```yaml
postgresql:
  image:
    tag: 15.2.0-debian-11-r13
    debug: true
  replicaCount: 3
  initdbScriptsCM: sharedx-postgresql-ha-postgresql-init-scripts
```

### What is the expected behavior?
```
CREATE TABLE mytable2( t text ); -- ok
```
### What do you see instead?
```
ERROR:  permission denied for schema public
```
