### ISSUE TITLE
[bitnami/nginx] Deployment parameter 'readinessProbe.enabled' doesn't update

### ISSUE THREAD

**Issue by fernandino143** [bitnami/charts#15989]
### Name and Version

bitnami/nginx

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. `helm install ng bitnami/nginx`
2. `cat values.yaml`
```yaml
image:
  registry: "docker.io"
  repository: "nginx"
  tag: "latest"

livenessProbe:
  enabled: "false"

readinessProbe:
  enabled: "false" 
```
3. `helm upgrade ng bitnami/nginx --values values.yaml`

After the upgrade, the livenessProbe is disabled, but the pod is never healthy with the following log:
```
Warning  Unhealthy  5s (x2 over 10s)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 500
```

A describe of the pod shows
```yaml
Containers:
  nginx:
    Container ID:   docker://0ca7af61da1735f7d13b20ba982ae550b761f286719e1b7a050cdd14bcc63895
    Image:          docker.io/nginx:latest
    Image ID:       docker-pullable://nginx@sha256:2ab30d6ac53580a6db8b657abf0f68d75360ff5cc1670a85acb5bd85ba1b19c0
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 07 Apr 2023 12:57:34 +0100
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 07 Apr 2023 12:56:14 +0100
      Finished:     Fri, 07 Apr 2023 12:57:34 +0100
    Ready:          False
    Restart Count:  3
    Liveness:       http-get http://:15020/app-health/nginx/livez delay=30s timeout=5s period=10s #success=1 #failure=6
    Readiness:      http-get http://:15020/app-health/nginx/readyz delay=5s timeout=3s period=5s #success=1 #failure=3
    Environment:
      BITNAMI_DEBUG:           false
      NGINX_HTTP_PORT_NUMBER:  8080
    Mounts:                    <none>
```

### Are you using any custom parameters or values?
```yaml
image:
  registry: "docker.io"
  repository: "nginx"
  tag: "latest"

livenessProbe:
  enabled: "false"

readinessProbe:
  enabled: "false" 
```
### What is the expected behavior?

Disable liveness and readiness probes. 

### What do you see instead?

Liveness and readiness are still in action

### Additional information

If I understand this correctly: https://github.com/bitnami/charts/blob/main/bitnami/nginx/templates/deployment.yaml#L206
This should be disabled when "False" is passed. The code suggests it should, but I'm confused
