### ISSUE TITLE
[bitnami/mongodb] labeler sidecar fails with error: Forbidden: pod updates may not change fields other than...

### ISSUE THREAD

**Issue by dmitry-mightydevops** [bitnami/charts#15994]
### Name and Version

bitnami/mongodb

### What architecture are you using?

amd64

### What steps will reproduce the bug?

setup the replicaset architecture, 3 nodes in the rs0.

helm chart has the following values:

```yaml
sidecars:
  - name: mongo-labeler
    image: korenlev/k8s-mongo-labeler-sidecar
    imagePullPolicy: Always
    env:
      - name: LABEL_SELECTOR
        value: "app.kubernetes.io/component=mongodb"
      - name: NAMESPACE
        value: "mongodb"
      - name: DEBUG
        value: "true"

# this is needed for mongodb-labeler sidecar to auto determine primary node
extraDeploy:
  - apiVersion: v1
    kind: Service
    metadata:
      name: mongodb-primary
      namespace: mongodb
      labels:
        app.kubernetes.io/component: mongodb
        app.kubernetes.io/instance: mongodb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mongodb
    spec:
      type: ClusterIP
      ports:
        - name: mongodb
          port: 30001
          protocol: TCP
          targetPort: mongodb
      selector:
        app.kubernetes.io/component: mongodb
        app.kubernetes.io/instance: mongodb
        app.kubernetes.io/name: mongodb
        primary: "true"
```

### Are you using any custom parameters or values?

<details>
<summary>Entire values.yaml</summary>

```yaml
replicaCount: 3
architecture: replicaset
priorityClassName: high-priority
useStatefulSet: false
systemLogVerbosity: 0
disableSystemLog: true

service:
  nameOverride: mongodb-svc
  type: ClusterIP
  portName: mongodb
  ports:
    mongodb: 27017

global:
  storageClass: mongodb-sc

image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 6.0.5-debian-11-r0
  debug: true

auth:
  enabled: true
  rootUser: root
  usernames: [mongouser]
  databases: [mongostaging]
  existingSecret: mongodb-auth

persistence:
  enabled: true
  size: 100Gi
  storageClass: mongodb-sc

updateStrategy:
  type: RollingUpdate

rbac:
  create: true
  rules:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
        - list
        - watch
        - update

readinessProbe:
  enabled: true
  failureThreshold: 5
  initialDelaySeconds: 30
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10

livenessProbe:
  enabled: true
  failureThreshold: 10
  initialDelaySeconds: 30
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10

startupProbe:
  enabled: true
  failureThreshold: 30
  initialDelaySeconds: 30
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 10

metrics:
  enabled: true
  extraFlags: |
    --collector.replicasetstatus --collector.dbstats --collector.topmetrics --collector.indexstats --collector.collstats
  image:
    tag: 0.37.0-debian-11-r15
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 20
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 10
  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 20
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 10
  service:
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: "9216"
      prometheus.io/scrape: "true"
  startupProbe:
    enabled: false
    failureThreshold: 5
    initialDelaySeconds: 10
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 10

nodeSelector:
  mongodb: "true"

arbiter:
  nodeSelector:
    mongodb: "true"

resources:
  limits:
    cpu: 2000m
    memory: 8Gi
  requests:
    cpu: 2000m
    memory: 8Gi
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: workload
          operator: In
          values:
          - mongodb

sidecars:
  - name: mongo-labeler
    image: korenlev/k8s-mongo-labeler-sidecar
    imagePullPolicy: Always
    env:
      - name: LABEL_SELECTOR
        value: "app.kubernetes.io/component=mongodb"
      - name: NAMESPACE
        value: "mongodb"
      - name: DEBUG
        value: "true"

# this is needed for mongodb-labeler sidecar to auto determine primary node
extraDeploy:
  - apiVersion: v1
    kind: Service
    metadata:
      name: mongodb-primary
      namespace: mongodb
      labels:
        app.kubernetes.io/component: mongodb
        app.kubernetes.io/instance: mongodb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mongodb
    spec:
      type: ClusterIP
      ports:
        - name: mongodb
          port: 30001
          protocol: TCP
          targetPort: mongodb
      selector:
        app.kubernetes.io/component: mongodb
        app.kubernetes.io/instance: mongodb
        app.kubernetes.io/name: mongodb
        primary: "true"
```
</details>

### What is the expected behavior?

pods to receive the label "primary=true"

### What do you see instead?

error

```sh
kail -p mongodb-0 -c mongo-labeler
mongodb/mongodb-0[mongo-labeler]: time="2023-04-09T21:30:46Z" level=debug msg="Hosts bson.Array[mongodb-0.mongodb-svc.mongodb.svc.cluster.local:27017, mongodb-1.mongodb-svc.mongodb.svc.cluster.local:27017, mongodb-2.mongodb-svc.mongodb.svc.cluster.local:27017]"
mongodb/mongodb-0[mongo-labeler]: time="2023-04-09T21:30:46Z" level=debug msg="Found 3 pods"
mongodb/mongodb-0[mongo-labeler]: time="2023-04-09T21:30:46Z" level=info msg="Setting primary to true for pod mongodb-0"
mongodb/mongodb-0[mongo-labeler]: time="2023-04-09T21:30:46Z" level=debug msg="Setting labels map[app.kubernetes.io/component:mongodb app.kubernetes.io/instance:mongodb app.kubernetes.io/managed-by:Helm app.kubernetes.io/name:mongodb controller-revision-hash:mongodb-6d8ddbfcc4 helm.sh/chart:mongodb-13.9.4 primary:true statefulset.kubernetes.io/pod-name:mongodb-0]"
mongodb/mongodb-0[mongo-labeler]: time="2023-04-09T21:30:46Z" level=error msg="Pod \"mongodb-0\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds`, `spec.tolerations` (only additions to existing tolerations) or `spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)\n\u00a0\u00a0core.PodSpec{\n\u00a0\u00a0\tVolumes:        {{Name: \"datadir\", VolumeSource: {PersistentVolumeClaim: &{ClaimName: \"datadir-mongodb-0\"}}}, {Name: \"common-scripts\", VolumeSource: {ConfigMap: &{LocalObjectReference: {Name: \"mongodb-common-scripts\"}, DefaultMode: &360}}}, {Name: \"scripts\", VolumeSource: {ConfigMap: &{LocalObjectReference: {Name: \"mongodb-scripts\"}, DefaultMode: &493}}}, {Name: \"kube-api-access-9s8k7\", VolumeSource: {Projected: &{Sources: {{ServiceAccountToken: &{ExpirationSeconds: 3607, Path: \"token\"}}, {ConfigMap: &{LocalObjectReference: {Name: \"kube-root-ca.crt\"}, Items: {{Key: \"ca.crt\", Path: \"ca.crt\"}}}}, {DownwardAPI: &{Items: {{Path: \"namespace\", FieldRef: &{APIVersion: \"v1\", FieldPath: \"metadata.namespace\"}}}}}}, DefaultMode: &420}}}},\n\u00a0\u00a0\tInitContainers: nil,\n\u00a0\u00a0\tContainers: []core.Container{\n\u00a0\u00a0\t\t{\n\u00a0\u00a0\t\t\t... // 11 identical fields\n\u00a0\u00a0\t\t\tLivenessProbe:  &{ProbeHandler: {Exec: &{Command: {\"/bitnami/scripts/ping-mongodb.sh\"}}}, InitialDelaySeconds: 30, TimeoutSeconds: 10, PeriodSeconds: 30, ...},\n\u00a0\u00a0\t\t\tReadinessProbe: &{ProbeHandler: {Exec: &{Command: {\"/bitnami/scripts/readiness-probe.sh\"}}}, InitialDelaySeconds: 30, TimeoutSeconds: 10, PeriodSeconds: 30, ...},\n-\u00a0\t\t\tStartupProbe: &core.Probe{\n-\u00a0\t\t\t\tProbeHandler:        core.ProbeHandler{Exec: &core.ExecAction{Command: []string{...}}},\n-\u00a0\t\t\t\tInitialDelaySeconds: 30,\n-\u00a0\t\t\t\tTimeoutSeconds:      10,\n-\u00a0\t\t\t\tPeriodSeconds:       20,\n-\u00a0\t\t\t\tSuccessThreshold:    1,\n-\u00a0\t\t\t\tFailureThreshold:    30,\n-\u00a0\t\t\t},\n+\u00a0\t\t\tStartupProbe:           nil,\n\u00a0\u00a0\t\t\tLifecycle:              nil,\n\u00a0\u00a0\t\t\tTerminationMessagePath: \"/dev/termination-log\",\n\u00a0\u00a0\t\t\t... // 6 identical fields\n\u00a0\u00a0\t\t},\n\u00a0\u00a0\t\t{Name: \"metrics\", Image: \"docker.io/bitnami/mongodb-exporter:0.37.0-debian-11-r15\", Command: {\"/bin/bash\", \"-ec\"}, Args: {\"/bin/mongodb_exporter --collect-all --compatible-mode --web.list\"...}, ...},\n\u00a0\u00a0\t\t{Name: \"mongo-labeler\", Image: \"korenlev/k8s-mongo-labeler-sidecar\", Env: {{Name: \"LABEL_SELECTOR\", Value: \"app.kubernetes.io/component=mongodb\"}, {Name: \"NAMESPACE\", Value: \"mongodb\"}, {Name: \"DEBUG\", Value: \"true\"}}, VolumeMounts: {{Name: \"kube-api-access-9s8k7\", ReadOnly: true, MountPath: \"/var/run/secrets/kubernetes.io/serviceaccount\"}}, ...},\n\u00a0\u00a0\t},\n\u00a0\u00a0\tEphemeralContainers: nil,\n\u00a0\u00a0\tRestartPolicy:       \"Always\",\n\u00a0\u00a0\t... // 26 identical fields\n\u00a0\u00a0}\n"
```

### Additional information

```
k version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.13", GitCommit:"592eca05be27f7d927d0b25cbb4241d75a9574bf", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:16Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.10-eks-48e63af", GitCommit:"9176fb99b52f8d5ff73d67fea27f3a638f679f8a", GitTreeState:"clean", BuildDate:"2023-01-24T19:17:48Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

kgpo     
NAME                READY   STATUS    RESTARTS      AGE
mongodb-0           3/3     Running   0             14m
mongodb-1           3/3     Running   0             15m
mongodb-2           3/3     Running   0             16m
mongodb-arbiter-0   1/1     Running   0             71m

kgsvc            
NAME                       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
mongodb-arbiter-headless   ClusterIP   None            <none>        27017/TCP   234d
mongodb-metrics            ClusterIP   172.20.16.39    <none>        9216/TCP    234d
mongodb-primary            ClusterIP   172.20.133.29   <none>        30001/TCP   234d
mongodb-svc                ClusterIP   None            <none>        27017/TCP   234d
```

mogodb app is managed by the argocd.

@korenlev any ideas?
