### ISSUE TITLE
[bitnami/*] Allow setting Sealed secret values

### ISSUE THREAD

**Issue by abdennour** [bitnami/charts#15992]
### Name and Version

bitnami/*

### What is the problem this feature will solve?

Whenever I need to use helm chart, I need to seal the password/token/...etc, then create extra resource (SealedSecret), then added alongside the helm chart.

### What is the feature you are proposing to solve the problem?

I am proposing to allow setting sealed secret values.

### What alternatives have you considered?

helm chart wrapper

**Comment by abdennour** [comment]
## Values Design

```
global:
  sealedSecret:
    enabled: true
    scope: namespace-wide

auth:
    # @param auth.password - it must be sealed if global.sealedSecret.enabled is true
    password:

```
