### ISSUE TITLE
[bitnami/postgres] Password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by cdprete** [bitnami/charts#16012]
### Name and Version

bitnami/postgres 14

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hello.
I'm trying to run postgres in k3s installed on a RHEL 8 VM, but I always get the following error:
> psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  password authentication failed for user "postgres"

and that's the full log I get from the container:
> postgresql 07:44:41.52 
> postgresql 07:44:41.52 Welcome to the Bitnami postgresql container
> postgresql 07:44:41.53 Subscribe to project updates by watching https://github.com/bitnami/containers
> postgresql 07:44:41.53 Submit issues and feature requests at https://github.com/bitnami/containers/issues
> postgresql 07:44:41.53 
> postgresql 07:44:41.56 INFO  ==> ** Starting PostgreSQL setup **
> postgresql 07:44:41.58 INFO  ==> Validating settings in POSTGRESQL_* env vars..
> postgresql 07:44:41.58 INFO  ==> Loading custom pre-init scripts...
> postgresql 07:44:41.59 INFO  ==> Initializing PostgreSQL database...
> postgresql 07:44:41.62 INFO  ==> pg_hba.conf file not detected. Generating it...
> postgresql 07:44:41.63 INFO  ==> Generating local authentication configuration
> postgresql 07:44:42.36 INFO  ==> Starting PostgreSQL in background...
> postgresql 07:44:42.62 INFO  ==> Creating user phone-book-user
> postgresql 07:44:42.64 INFO  ==> Granting access to "phone-book-user" to the database "phone-book-db"
> postgresql 07:44:42.67 INFO  ==> Setting ownership for the 'public' schema database "phone-book-db" to "phone-book-user"
> postgresql 07:44:42.70 INFO  ==> Configuring replication parameters
> postgresql 07:44:42.74 INFO  ==> Configuring synchronous_replication
> postgresql 07:44:42.74 INFO  ==> Configuring fsync
> postgresql 07:44:42.77 INFO  ==> Stopping PostgreSQL...
> waiting for server to shut down.... done
> server stopped
> postgresql 07:44:42.87 INFO  ==> Loading custom scripts...
> postgresql 07:44:42.88 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
> postgresql 07:44:42.88 INFO  ==> Starting PostgreSQL in background...
> Password for user postgres: 
> psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  password authentication failed for user "postgres"
> postgresql 07:44:43.03 INFO  ==> Stopping PostgreSQL...
> waiting for server to shut down.... done

and I've tried already multiple time to delete the PV and PVC, but with no luck.

Below you can find all my definitions in order to reproduce the issue:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: phone-book-database
  labels:
    app.kubernetes.io/name: phone-book-database
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: phone-book-database-config-map
  namespace: phone-book-database
  labels:
    app.kubernetes.io/name: phone-book-database
immutable: true
data:
  # Data for the phone-book main database
  POSTGRESQL_DATABASE: phone-book-db
  POSTGRESQL_USERNAME: phone-book-user
  # Data for the database used by the IdP
  PHONE_BOOK_IDP_DATABASE: phone-book-idp-db
  PHONE_BOOK_IDP_USERNAME: phone-book-idp-user

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phone-book-idp-db-config-map
  namespace: phone-book-database
  labels:
    app.kubernetes.io/name: phone-book-database
immutable: true
data:
  init-idp-db.sh: |-
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
      CREATE USER "$PHONE_BOOK_IDP_USERNAME" WITH PASSWORD '$PHONE_BOOK_IDP_PASSWORD';
      CREATE DATABASE "$PHONE_BOOK_IDP_DATABASE";
      GRANT ALL PRIVILEGES ON DATABASE "$PHONE_BOOK_IDP_DATABASE" TO "$PHONE_BOOK_IDP_USERNAME";
    EOSQL
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: phone-book-database-secret
  namespace: phone-book-database
  labels:
    app.kubernetes.io/name: phone-book-database
type: Opaque
immutable: true
data:
  # In production environments these won't be stored unencrypted like this, but something like
  # https://github.com/bitnami-labs/sealed-secrets would instead be used.
  POSTGRESQL_PASSWORD: 'bko2TiM4aFQyUHgyakQqeQ=='

  PHONE_BOOK_IDP_PASSWORD: 'WDlqJUc/cCM1U0hXNnBjLQ=='
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: phone-book-database-service
  namespace: phone-book-database
  labels:
    app.kubernetes.io/name: phone-book-database
spec:
  selector:
    app.kubernetes.io/name: phone-book-database-deployment
  ports:
    - port: 5432
```

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: phone-book-database-persistent-volume
  namespace: phone-book-database
  labels:
    app.kubernetes.io/name: phone-book-database
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  # local-path is a storage class provided by Rancher k3s that mounts the volume as an hostPath, where the path is under
  # the WSL installation of the k3s cluster. This is accessible from the Windows explorer at \\wsl$
  storageClassName: local-path
  hostPath:
    path: /phone-book-db
  claimRef:
    name: phone-book-database-persistent-volume-claim
    namespace: phone-book-database
```

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phone-book-database-persistent-volume-claim
  namespace: phone-book-database
  labels:
    app.kubernetes.io/name: phone-book-database
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 10Mi
    limits:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phone-book-database-deployment
  namespace: phone-book-database
  labels:
    app.kubernetes.io/name: phone-book-database
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: phone-book-database-deployment
  template:
    metadata:
      name: phone-book-database-pod
      namespace: phone-book-database
      labels:
        app.kubernetes.io/name: phone-book-database-deployment
    spec:
      containers:
        - name: postgres
          image: artifactory.six-group.net/bitnami/postgresql:14
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: phone-book-database-config-map
            - secretRef:
                name: phone-book-database-secret
          volumeMounts:
            - name: postgres-data
              # Use /bitnami instead of /bitnami/postgresql as specified in the docs of the Docker image.
              # See: https://github.com/bitnami/charts/issues/1210#issuecomment-678759936
              mountPath: /bitnami
            - name: idp-db-init
              mountPath: /docker-entrypoint-initdb.d/init-idp-db.sh
              subPath: init-idp-db.sh
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 5432
          readinessProbe:
            initialDelaySeconds: 15
            tcpSocket:
              port: 5432
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: phone-book-database-persistent-volume-claim
        - name: idp-db-init
          configMap:
            name: phone-book-idp-db-config-map
            defaultMode: 0744
```

The files are also available at https://github.com/cdprete/phone-book/tree/main/phone-book-deployment

Kind regards and thanks in advance for the help.

### What do you see instead?

psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  password authentication failed for user "postgres"
