### ISSUE TITLE
Rename ReplicaSet members host when external access is enabled using NodePorts

### ISSUE THREAD

**Issue by fhperuchi** [bitnami/charts#16020]
### Name and Version

bitnami/mongodb 13.9.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Is it possible to change replicaset `members[*].host` to an FQDN and not set it to k8s DNS internal name?

It is causing me problems when I try to connect to it. I have tried to setup that with many types of configurations, but I could not.

I am using theis Chart version:
```
chart = "mongodb"
repository = "https://charts.bitnami.com/bitnami"
chart version = "13.9.4"
```

Error:
```console
$ mongosh 'mongodb://user:pass@my.domain.com:31000,my.domain.com:31001,my.domain.com:31002/test?authSource=admin&ssl=false&tls=false'
Current Mongosh Log ID:	64357eb40d000ca7875be467
Connecting to:		mongodb://<credentials>@my.domain.com:31000,my.domain.com:31001,my.domain.com:31002/test?authSource=admin&ssl=false&tls=false&appName=mongosh+1.8.0
MongoNetworkError: getaddrinfo ENOTFOUND mongodb-staging-0.mongodb-staging-headless.mongodb-staging.svc.cluster.local
```

### Are you using any custom parameters or values?

values.yaml:
```yaml
externalAccess:
  enabled: true
  autoDiscovery:
    enabled: false
    image:
      registry: docker.io
      repository: bitnami/kubectl
      tag: 1.26.3-debian-11-r4
      digest: ""
      pullPolicy: IfNotPresent
      pullSecrets: []
    resources:
      limits: {}
      requests: {}
  service:
    type: NodePort
    portName: "mongodb"
    ports:
      mongodb: 27017
    loadBalancerIPs: []
    loadBalancerClass: ""
    loadBalancerSourceRanges: []
    allocateLoadBalancerNodePorts: true
    externalTrafficPolicy: Local
    nodePorts:
      - 31000
      - 31001
      - 31002
    domain: my.domain.com
    extraPorts: []
    annotations: {}
    sessionAffinity: ClientIP
    sessionAffinityConfig: {}
```

### What is the expected behavior?

```
replicaset [direct: primary] test> rs.conf()
{
  _id: 'replicaset',
  version: 7,
  term: 27,
  members: [
    {
      _id: 0,
      host: 'my.domain.com:31000',
      arbiterOnly: false,
      buildIndexes: true,
      hidden: false,
      priority: 5,
      tags: {},
      secondaryDelaySecs: Long("0"),
      votes: 1
    },
    {
      _id: 1,
      host: 'my.domain.com:31001',
      arbiterOnly: false,
      buildIndexes: true,
      hidden: false,
      priority: 1,
      tags: {},
      secondaryDelaySecs: Long("0"),
      votes: 1
    },
    {
      _id: 2,
      host: 'my.domain.com:31002',
      arbiterOnly: false,
      buildIndexes: true,
      hidden: false,
      priority: 1,
      tags: {},
      secondaryDelaySecs: Long("0"),
      votes: 1
    }
  ],
  protocolVersion: Long("1"),
  writeConcernMajorityJournalDefault: true,
  settings: {
    chainingAllowed: true,
    heartbeatIntervalMillis: 2000,
    heartbeatTimeoutSecs: 10,
    electionTimeoutMillis: 10000,
    catchUpTimeoutMillis: -1,
    catchUpTakeoverDelayMillis: 30000,
    getLastErrorModes: {},
    getLastErrorDefaults: { w: 1, wtimeout: 0 },
    replicaSetId: ObjectId("64340452538eeadbe7fdbb68")
  }
}
```

### What do you see instead?

```
replicaset [direct: primary] test> rs.conf()
{
  _id: 'replicaset',
  version: 7,
  term: 27,
  members: [
    {
      _id: 0,
      host: 'mongodb-staging-0.mongodb-staging-headless.mongodb-staging.svc.cluster.local:27017',
      arbiterOnly: false,
      buildIndexes: true,
      hidden: false,
      priority: 5,
      tags: {},
      secondaryDelaySecs: Long("0"),
      votes: 1
    },
    {
      _id: 1,
      host: 'mongodb-staging-1.mongodb-staging-headless.mongodb-staging.svc.cluster.local:27017',
      arbiterOnly: false,
      buildIndexes: true,
      hidden: false,
      priority: 1,
      tags: {},
      secondaryDelaySecs: Long("0"),
      votes: 1
    },
    {
      _id: 2,
      host: 'mongodb-staging-2.mongodb-staging-headless.mongodb-staging.svc.cluster.local:27017',
      arbiterOnly: false,
      buildIndexes: true,
      hidden: false,
      priority: 1,
      tags: {},
      secondaryDelaySecs: Long("0"),
      votes: 1
    }
  ],
  protocolVersion: Long("1"),
  writeConcernMajorityJournalDefault: true,
  settings: {
    chainingAllowed: true,
    heartbeatIntervalMillis: 2000,
    heartbeatTimeoutSecs: 10,
    electionTimeoutMillis: 10000,
    catchUpTimeoutMillis: -1,
    catchUpTakeoverDelayMillis: 30000,
    getLastErrorModes: {},
    getLastErrorDefaults: { w: 1, wtimeout: 0 },
    replicaSetId: ObjectId("64340452538eeadbe7fdbb68")
  }
}
```
