### ISSUE TITLE
[bitnami/zookeeper] OOM restart issue 

### ISSUE THREAD

**Issue by abhayycs** [bitnami/charts#16027]
### Name and Version

bitnami/zookeeper-3.8.0

### What architecture are you using?

None

### What steps will reproduce the bug?

I am running around 7 microservices watchers for kafka and sideways zookeeper is also running. (I'm not sure if it helps)
and set some memory-limits in zookeeper.
```yaml
    resources:
      limits:
        memory: 420Mi
        cpu: 150m
      requests:
        memory: 210Mi
        cpu: 75m
```
Even in the Idle state over the long run, the memory usage by zookeeper memory keeps on increasing and after some point, it is getting restarted.
It started with Memory:
```
kafka-zookeeper-0                                          9m           148Mi
kafka-zookeeper-1                                          10m          148Mi
kafka-zookeeper-2                                          7m           138Mi
```

After a long run:
```
kafka-zookeeper-0                                          13m          353Mi
kafka-zookeeper-1                                          11m          384Mi
kafka-zookeeper-2                                          11m          408Mi 
```

![image](https://user-images.githubusercontent.com/30349166/231397891-97f0c816-f21e-46e2-9fba-874e3106733b.png)

### Are you using any custom parameters or values?
```yaml
    podAntiAffinityPreset: "soft"
    replicaCount: 3
    persistence:
      enabled: true
    volumePermissions:
      containerSecurityContext:
        enabled: true
```
### What is the expected behavior?

It is supposed to keep releasing memory in between during the long run.

**Comment by abhayycs** [comment]
Hi @javsalgar,

I have not modified any setting of Java variables.
```
zookeeper:
  podAntiAffinityPreset: "soft"
  replicaCount: 3
  persistence:
    storageClass: "manual"
    enabled: true
  volumePermissions:
    containerSercurityContext:
      enabled: true
resources:
  limits:
    memory: 420Mi
    cpu: 150m
  requests:
    memory: 210Mi
    cpu: 75m
```

Could you please tell, how can I take memory dump trace for zookeeper?

PS: Please let me know, if you need any further details.
