### ISSUE TITLE
[bitnami/redis] redis v7 deploy fail

### ISSUE THREAD

**Issue by ddh-open** [bitnami/charts#16040]
### Name and Version

bitnami/redis

### What architecture are you using?

None

### What steps will reproduce the bug?

failed to render values files
```
"../values/redis-v7.yaml.gotmpl": failed to render [../values/redis-v7.yaml.gotmpl], because of template: stringTemplate:1587:47: executing "stringTemplate" at <{{template "common.names.fullname" .}}>: template "common.names.fullname" not defined
```

**Comment by carrodher** [comment]
Could you provide more info about how are you installing the Helm chart?

**Comment by ddh-open** [comment]
Ok, i`m installing the helm chart by use helmfile

```
releases:
  - name: "redis-cluster"
    namespace: "redis"
    chart: "bitnami/redis"
    labels:
      app: "redis"
    version: 17.9.3
    installed: true
    wait: true
    values:
      - ../values/redis-v7.yaml.gotmpl
```
