### ISSUE TITLE
[bitnami/keycloak] Getting --features=declarative-user-profile into the Container

### ISSUE THREAD

**Issue by milufranz08** [bitnami/charts#16051]
### Name and Version

bitnami/keycloak 14.2.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Following Keycloak's documentation to [enable a user profile](https://www.keycloak.org/docs/latest/server_admin/#user-profile).

Looked into the readme and value.yaml file in the repo and added this to our helm:
```yaml
extraEnvVars:
            - name: KEYCLOAK_EXTRA_ARGS
              value: "-Dkeycloak.profile.feature.declarative_user_profile=enabled"
```
It deployed with no issues, however, we are not seeing the `User Profile Enabled` switch option under `Realm Settings` as indicated in the KC documentation.

Please advice if we are missing a step. Any help or guidance will be appreciated

### Are you using any custom parameters or values?

Yes, we are trying to pass the declarative user profile features parameter as a values.yaml customization.

The KC documentation shows this flag:
`--features=declarative-user-profile`

### What is the expected behavior?

Expect to see the `User Profile Enabled` switch option under `Realm Settings` as indicated in the KC documentation.

### What do you see instead?

`User Profile Enabled` switch option is NOT visible under `Realm Settings` as indicated in the KC documentation.

**Comment by javsalgar** [comment]
Hi,

Could you check the container logs and ensure that the flag is correctly set? You can also enter the container and check the running processes to see that the flag is indeed set.

**Comment by javsalgar** [comment]
Hi,

I'd say that entering the container and executing `ps -xufa | cat`  is an option. But if you checked the logs and saw the flag, then Keycloak is consuming the flag. In this sense, it seems that the issue is not in the Bitnami packaging of Keycloak but in Keycloak itself, so my advice would be to check with the upstream Keycloak developers.

**Comment by milufranz08** [comment]
Thank again for the suggestion. We executed the suggested command and got these results:
```
$ kubectl -n keycloak exec -it keycloak-0 -- ps -xufa | cat
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
keycloak                                                               Rs+  17:33   0:00 ps -xufa
keycloak                                                               Ssl  Apr14  26:58 /opt/bitnami/
```

Should these results show the corresponding `declarative-user-profile` feature flag?

We also ran a kubernetes logs command with `grep` on `declarative` and did not find any match. So we are assuming that the feature flag is not getting enabled correctly.

We are using the following command on the values.yaml to set up the feature. Are we missing a step?
```
extraEnvVars:
     - name: KEYCLOAK_EXTRA_ARGS
        value: "-Dkeycloak.profile.feature.declarative_user_profile=enabled"
```

Thank you so much again for your help!

**Comment by javsalgar** [comment]
Could you try with 

```
$ kubectl -n keycloak exec -it keycloak-0 -- bash
$ ps -xufa | cat
```

This should show the whole output of the keycloak command

**Comment by milufranz08** [comment]
Thank you for sharing that command @javsalgar! It was really helpful.
We ran it on our deployed helm and saw the flag was present on the output of the keycloak command.

I ran the bitnami keycloak chart locally to see if I would have the same issue. And just as our deployed environment, the flag was present on the command output but the Keycloak UI did not show the additional features.

Finally, I wanted to test that the issue was coming from Keycloak. So I also ran a local docker Keycloak instance passing the `--features=declarative-user-profile` flag. However, this time it worked as expected... the local Keycloak UI instantiated with docker displays the extra features I need.

Is there any chance you could take a look at what might be causing this behavior on the bitnami Keycloak chart? 

Thank you so much again for all the help to get to this point! I understand if this issue might not be a priority.

**Comment by Mauraza** [comment]
Hi @milufranz08,

The docker you trying was the container of bitnami o the official image?

**Comment by milufranz08** [comment]
Hi @Mauraza,

Not sure if I understand the question but I'm going to try to answer it anyways. Let me know if this is not what you were looking for:

1) Deployed env - uses bitnami helm chart -> flags set correctly, feature not showing on UI
2) K8s local test - uses bitnami helm chart -> same issue as above
3) Docker local test - uses official docker image 
      command used:
      `docker run --name mykeycloak -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:latest start-dev --features=declarative-user-profile`

**Comment by Mauraza** [comment]
Hi @milufranz08,

Could you tell me if this docker-compose.yaml is working as you expected?
```yaml
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  keycloak:
    image: docker.io/bitnami/keycloak:21
    environment:
      - KEYCLOAK_EXTRA_ARGS="-Dkeycloak.profile.feature.declarative_user_profile=enabled"
    depends_on:
      - postgresql
    ports:
      - "80:8080"

volumes:
  postgresql_data:
    driver: local
```

If the answer is yes is something related to the chart, in that case, could you share the values are you using?
