### ISSUE TITLE
[bitnami/thanos] Allow personalizing some PrometheusRules' labels

### ISSUE THREAD

**Issue by achetronic** [bitnami/charts#16065]
### Name and Version

bitnami/thanos 12.4.2

### What is the problem this feature will solve?

When setting this configuration on the chart:
```
  # What to do with the metrics for Thanos components
  metrics:
    enabled: true

    # Create a PrometheusRule to monitor critical stuff for Thanos
    prometheusRule:
      enabled: true
      default:
        create: true
```

Basically, the templating hardcode some labels on the metrics that changes. For example most collectors like OTEL change the name of the jobs, so these PrometheusRules become completely useless. An example can be seen [here](https://github.com/bitnami/charts/blob/main/bitnami/thanos/templates/alert-rule/query.yml#L57)

### What is the feature you are proposing to solve the problem?

Two things, delete not meaningful labels, and give the possibility to add some extra as follows:

```
  # What to do with the metrics for Thanos components
  metrics:
    enabled: true

    # Create a PrometheusRule to monitor critical stuff for Thanos
    prometheusRule:
      enabled: true

      # SOMETHING LIKE THIS FIELD
      extraLabels:
        job: foo
        another: bar

      default:
        create: true
```

this way we could provide some meaningful labels to filter the cluster and this kind of stuff, and at the same time personalize those ones like the job, which is hardcoded by the collector most times 
![Screenshot 2023-04-14 at 16 37 44](https://user-images.githubusercontent.com/61636487/232090099-683de6e3-fdb3-4b81-baea-aad9c98a2b1c.png)

### What alternatives have you considered?

We don't have alternatives yet
