### ISSUE TITLE
[bitnami/redis] Redis HA with Sentinel, pods restart repeatedly by receiving SIGTERM signal

### ISSUE THREAD

**Issue by amirhj** [bitnami/charts#16067]
### Name and Version

bitnami/redis 17.9.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Installing the chart by `helm upgrade --install redis-ha bitnami/redis --version 17.9.4 -f values.production.yaml --post-renderer ./modify.sh` the following is contents of `modify.sh` script:

```sh
cat <&0 \
  | yq e "del(select(di == 8).spec.template.spec.securityContext.fsGroup)" - \
  | yq e "del(select(di == 8).spec.template.spec.affinity)" - \
  | yq e "del(select(di == 8).spec.template.spec.containers[1].securityContext)" - \
  | yq e "del(select(di == 8).spec.template.spec.containers[2].securityContext)" -
```

3. After some amount of time, first some slave node restarting repeatedly in 10 or 5 or 2 minutes periods by receiving SIGTERM signal
4. After some restarting of the slave nodes, the master node restarts and the master changes to one of the slave nodes repeatedly.

### Are you using any custom parameters or values?

```yaml
image:
  registry: docker.io 
  repository: bitnami/redis
  tag: 7.0.10-debian-11-r8

commonConfiguration: |-
  appendonly no
  maxmemory 1024mb
  maxmemory-policy allkeys-lru
  io-threads 2
  io-threads-do-reads yes 
  client-output-buffer-limit normal 0 0 0
  client-output-buffer-limit slave 512mb 512mb 120
  client-output-buffer-limit pubsub 32mb 8mb 60
  cluster-replica-validity-factor 10
  daemonize no
  save ""

architecture: replication

auth:
  enabled: false
  sentinel: false

master:
  count: 1
  resources:
    limits:
      memory: 5Gi
      cpu: 3
    requests:
      memory: 5Gi
  podSecurityContext:
    enabled: true
    sysctls:
      - name: "net.core.somaxconn"
        value: "65535"
      - name: "net.ipv4.ip_local_port_range"
        value: "15000 60999"
    fsGroup: ""
  containerSecurityContext:
    enabled: false
  persistence:
    enabled: false

replica:
  replicaCount: 3
  resources:
    limits:
      memory: 5Gi
      cpu: 3
    requests:
      memory: 5Gi
  podSecurityContext:
    enabled: true
    sysctls:
      - name: "net.core.somaxconn"
        value: "65535"
      - name: "net.ipv4.ip_local_port_range"
        value: "15000 60999"
    fsGroup: ""
  containerSecurityContext:
    enabled: false
  persistence:
    enabled: false
  affinity: {}

sentinel:
  enabled: true
  image:
    registry: docker.io 
    repository: bitnami/redis-sentinel
    tag: 7.0.10-debian-11-r2
  persistence:
    enabled: false
  resources:
    limits:
      memory: 200Mi
      cpu: 800m
    requests:
      memory: 100Mi

metrics:
  enabled: true
  image:
    registry: docker.io 
    repository: bitnami/redis-exporter
    tag: 1.48.0-debian-11-r7  
  resources:
    limits:
      memory: 300Mi
      cpu: 400m
    requests:
      memory: 200Mi

rbac:
  create: false

volumePermissions:
  enabled: false

pdb:
  create: true
  minAvailable: 2
```

### What is the expected behavior?

Nodes work properly without restarting repeatedly

### What do you see instead?

Here is logs of redis container of one of the slave nodes:

```
1:C 14 Apr 2023 15:57:41.759 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 14 Apr 2023 15:57:41.759 # Redis version=7.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 14 Apr 2023 15:57:41.759 # Configuration loaded
1:S 14 Apr 2023 15:57:41.759 * monotonic clock: POSIX clock_gettime
1:S 14 Apr 2023 15:57:41.760 * Running mode=standalone, port=6379.
1:S 14 Apr 2023 15:57:41.760 # Server initialized
1:S 14 Apr 2023 15:57:41.761 * Loading RDB produced by version 7.0.10
1:S 14 Apr 2023 15:57:41.761 * RDB age 2362 seconds
1:S 14 Apr 2023 15:57:41.761 * RDB memory usage when created 6.94 Mb
1:S 14 Apr 2023 15:57:41.790 * Done loading RDB, keys loaded: 5721, keys expired: 0.
1:S 14 Apr 2023 15:57:41.790 * DB loaded from disk: 0.029 seconds
1:S 14 Apr 2023 15:57:41.790 * Before turning into a replica, using my own master parameters to synthesize a cached master: I may be able to synchronize with the new master with just a partial transfer.
1:S 14 Apr 2023 15:57:41.790 * Ready to accept connections
1:S 14 Apr 2023 15:57:42.695 * Connecting to MASTER redis-ha-node-0.redis-ha-headless.xxx-production.svc.cluster.local:6379
1:S 14 Apr 2023 15:57:42.696 * MASTER <-> REPLICA sync started
1:S 14 Apr 2023 15:57:42.696 * Non blocking connect for SYNC fired the event.
1:S 14 Apr 2023 15:57:43.147 * Master replied to PING, replication can continue...
1:S 14 Apr 2023 15:57:43.149 * Trying a partial resynchronization (request 47223c4cd76e82b33fe180b22dc004c2d9954714:396350).
1:S 14 Apr 2023 15:57:49.760 * Full resync from master: 47223c4cd76e82b33fe180b22dc004c2d9954714:164735790
1:S 14 Apr 2023 15:57:49.774 * MASTER <-> REPLICA sync: receiving streamed RDB from master with EOF to disk
1:S 14 Apr 2023 15:57:51.328 * Discarding previously cached master state.
1:S 14 Apr 2023 15:57:51.328 * MASTER <-> REPLICA sync: Flushing old data
1:S 14 Apr 2023 15:57:51.332 * MASTER <-> REPLICA sync: Loading DB in memory
1:S 14 Apr 2023 15:57:51.394 * Loading RDB produced by version 7.0.10
1:S 14 Apr 2023 15:57:51.394 * RDB age 2 seconds
1:S 14 Apr 2023 15:57:51.394 * RDB memory usage when created 60.25 Mb
1:S 14 Apr 2023 15:57:51.690 * Done loading RDB, keys loaded: 54445, keys expired: 0.
1:S 14 Apr 2023 15:57:51.691 * MASTER <-> REPLICA sync: Finished with success
1:signal-handler (1681488097) Received SIGTERM scheduling shutdown...
1:S 14 Apr 2023 16:01:42.943 # User requested shutdown...
1:S 14 Apr 2023 16:01:42.943 # Redis is now ready to exit, bye bye...
```
