### ISSUE TITLE
[discourse] Back-off restarting failed container

### ISSUE THREAD

**Issue by obeyler** [bitnami/charts#16073]
### Name and Version

bitnami/discourse 10.0.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I update from 10.0.3 to 10.0.5 chart.
It always crashes with Back-off restarting the failed container

### Are you using any custom parameters or values?
```yaml
    livenessProbe:
      timeoutSeconds: 60
      failureThreshold: 10
    readynessProbe:
      failureThreshold: 10
    startupProbe:
      enabled: true
      periodSeconds: 30
      timeoutSeconds: 60
      failureThreshold: 30
```

### What do you see instead?
```
discourse 00:50:04.03 Welcome to the Bitnami discourse container
discourse 00:50:04.03 Subscribe to project updates by watching https://github.com/bitnami/containers
discourse 00:50:04.03 Submit issues and feature requests at https://github.com/bitnami/containers/issues
discourse 00:50:04.03 
discourse 00:50:04.04 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse 00:50:04.04 INFO  ==> Trying to connect to the database server
discourse 00:50:04.05 INFO  ==> Creating database bitnami_application
discourse 00:50:04.10 INFO  ==> Creating Discourse configuration file
discourse 00:50:04.13 INFO  ==> Enabling SMTP
discourse 00:50:04.14 INFO  ==> Restoring persisted Discourse installation
discourse 00:50:04.22 INFO  ==> Trying to connect to the database server
discourse 00:50:04.23 INFO  ==> Running database migrations
```
After that no more log, It always crash with Back-off restarting failed container
