### ISSUE TITLE
[bitnami/etcd] member can't join cluster

### ISSUE THREAD

**Issue by roy-work** [bitnami/charts#16071]
### Name and Version

bitnami/etcd 8.8.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We appear to have run into [this issue](https://github.com/bitnami/charts/issues/6251).

There's not much in the way of good information in that bug, so in an attempt to work around the issue, I deleted the node & wiped its PVC/PV; I figured a clean slate should do it, and it could replicate from the other two.

Now, it cannot start with:

```
etcd-0 etcd etcd 18:06:20.81 INFO  ==> Member ID wasn't properly stored, the member will try to join the cluster by it's own
[… later …]
etcd-0 etcd {"level":"warn","ts":"2023-04-14T18:06:23.387Z","caller":"etcdserver/server.go:1127","msg":"server error","error":"the member has been permanently removed from the cluster"}
```

This mirrors [this issue](https://github.com/bitnami/charts/issues/8055). (Also supposedly fixed.)

How can I get this `etcd` member to rejoin the cluster?

### What is the expected behavior?

Brand new Sts replicas should just join the existing cluster.

### What do you see instead?

They cannot, as they were "permanently removed".

**Comment by javsalgar** [comment]
Hi,

Did you change any of the default values? Which is the Kubernetes platform you are using to deploy the solution?

**Comment by roy-work** [comment]
A few:

```yaml
replicaCount: 3
metrics:
  enabled: true
persistence:
  enabled: true
  size: 1Gi
auth:
  rbac:
    allowNoneAuthentication: false
    existingSecret: "etcd-password"
    existingSecretPasswordKey: "etcd-password"
  token:
    type: simple
```

This is deployed on GKE.
