### ISSUE TITLE
[bitnami/mysql] Mysql not load balanced

### ISSUE THREAD

**Issue by pausanchezv** [bitnami/charts#16074]
### Name and Version

bitnami/mysql 9.7.1

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Deploy mysql with this configuration

```
global:
  storageClass: premium-rwo # standard-rwo

image:
  tag: 8.0.32-debian-11-r21

primary:
  startupProbe:
    enabled: false

auth:
  database: XXX
  rootPassword: XXX

architecture: replication

secondary:
  replicaCount: 2
```

2. Note that you can either connect to the primary service (read/write) or to the secondary (read), but not to a service that load balances the requests to all the pods, which is what is interesting about replication.

### Are you using any custom parameters or values?

```
global:
  storageClass: premium-rwo # standard-rwo

image:
  tag: 8.0.32-debian-11-r21

primary:
  startupProbe:
    enabled: false

auth:
  database: XXX
  rootPassword: XXX

architecture: replication

secondary:
  replicaCount: 2
```

### What is the expected behavior?

The expected behaviour is something like your **postresql-ha** has, or your **redis**. I need a service that uses all the available pods so as not to saturate one.
Why would I wanna have replicas otherwise? The way the chart suggests, I'd need to have two connections to two different dbs is my code for read and write, which is messy.
Can you help in this matter, please?

### What do you see instead?

I see different services to connect to, I need a general one that load balances the requests and uses all the replicas and the master.
