### ISSUE TITLE
Ports are hardcoded and no support for graphite port (2003)

### ISSUE THREAD

**Issue by marekmrowca** [bitnami/charts#1608]
**Chart version**

influxdb 0.2.0

**Description**

In standalone-dpl.yaml containers are hardcoded - the ones with 8086 and 8088.

```yaml
          ports:
            - name: http
              containerPort: 8086
              protocol: TCP
            - name: rcp
              containerPort: 8088
              protocol: TCP
```

In service.yaml these ports are configurable, but they are hardcoded in deployment description, so the endpoints will always be 8086 and 8088.

It would be great to have them configurable and possible to add at least one additional port for graphite.
