### ISSUE TITLE
[bitnami/redis] CrashLoopBackOff  mkdir: cannot create directory '/opt/bitnami/redis/tmp': Permission denied

### ISSUE THREAD

**Issue by ram-yadav** [bitnami/charts#16102]
### Name and Version

bitnami/redis 6.2.7

### What architecture are you using?

None

### What steps will reproduce the bug?

`helm install bitnami/redis 6.2.7` within namespace of Kubernetes

### Are you using any custom parameters or values?
```yaml
# Default values for redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: bitnami/redis
  # Pinning redis to a default version
  tag: 6.2.7
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: <some port>

internalContainerPorts:
  redis:
    port: <some port>
    protocol: TCP

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # Default is cpu: 100m and memory: 128Mi. For redis, reserving 256Mi memory.
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

lifecycle:
  postStart:
    exec:
      command: ["/bin/sh", "-c", "(redis-cli ping && redis-cli set db redis && redis-cli get db && redis-cli del db) > /tmp/test-ping.log"]

# For High Availability, scale redis deployment to a maximum of 2 pods. Set enabled to true.
# Along with autoscaling, consider using sentinel or master/worker type of configuration.
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
```
### What is the expected behavior?

bitnami/redis should get deployed successfully

### What do you see instead?
```
redis 23:52:57.68 
redis 23:52:57.68 Welcome to the Bitnami redis container
redis 23:52:57.68 Subscribe to project updates by watching https://github.com/bitnami/containers
redis 23:52:57.68 Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis 23:52:57.68 
redis 23:52:57.78 INFO  ==> ** Starting Redis setup **
redis 23:52:57.88 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis 23:52:57.88 INFO  ==> Initializing Redis
mkdir: cannot create directory '/opt/bitnami/redis/tmp': Permission denied
```
