### ISSUE TITLE
[minio] Provisionning hook failed if quota is defined

### ISSUE THREAD

**Issue by sereinity** [bitnami/charts#16111]
### Name and Version

bitnami/minio 12.2.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy minio with provided values:

```shell
helm upgrade --install -n temp -f local-values.yaml --version 12.2.6 bitnami/minio minio
```

### Are you using any custom parameters or values?

```yaml
auth:
  rootPassword: mysupersecret
  rootUser: bar
mode: distributed
pdb:
  create: true
provisioning:
  buckets:
  - lifecycle:
    - disabled: false
      expiry:
        days: 14
        nonconcurrentDays: 3
      id: retention
    name: baz
    quota:
      size: 24GiB
      type: hard
  enabled: true
```

### What do you see instead?

The deployment fail with this error:

```shell
$ kubectl -n temp logs -f jobs/minio-provisioning
Defaulted container "minio" out of: minio, wait-for-available-minio (init)
Start Minio provisioning
Added `provisioning` successfully.
Restart command successfully sent to `provisioning`. Type Ctrl-C to quit or wait to follow the status of the restart process.

Restarted `provisioning` successfully in 1 seconds
Bucket created successfully `provisioning/baz`.
Lifecycle configuration imported successfully to `provisioning/baz`.
mc: <ERROR> Deprecated command. Please use 'mc quota' instead.
```

### Additional information

The cause is that `mc` changed, [new way to set quota](https://min.io/docs/minio/linux/reference/minio-mc/mc-quota-set.html#command-mc.quota.set)

I tested a patch that works:

```patch
diff --git a/bitnami/minio/templates/provisioning-job.yaml b/bitnami/minio/templates/provisioning-job.yaml
index 60d7baee2..8d9d3c316 100755
--- a/bitnami/minio/templates/provisioning-job.yaml
+++ b/bitnami/minio/templates/provisioning-job.yaml
@@ -177,7 +177,11 @@ spec:
               {{- end }}

               {{- with $bucket.quota }}
-              mc admin bucket quota {{ $minioAlias }}/{{ $bucket.name }} --{{ .type }} {{ .size }};
+              {{- if eq .type "hard" }}
+              mc quota set {{ $minioAlias }}/{{ $bucket.name }} {{ if .size }}--size {{ .size }}{{ end }};
+              {{- else }}
+              mc quota {{ .type }} {{ $minioAlias }}/{{ $bucket.name }} {{ if .size }}--size {{ .size }}{{ end }};
+              {{- end }}
               {{- end }}

               {{- if $isDistributedMode }}
```

Which allow to still use types `hard`/`clear` but it may be useful to switch to `set`/`clear` or whatever. Will probably open a PR later.
