### ISSUE TITLE
clean keycloak deployment redirects to /auth and gives 404

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#16119]
### Name and Version

bitnami/keycloak: 14.2.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Using values.yaml from a previous installation but with the latest chart 14.2.0

Deleted namespace & pvcs, allowing for a clean deployment.

### Are you using any custom parameters or values?

```yaml
keycloak:

  # use to increase logging
  image:
    debug: false

  global:
    storageClass: cephfs

  production: true

  proxy: edge

  # to specify the ad ca public certificate in order to access ldaps
  spi:
    existingSecret: keycloak-certs
    truststorePassword: changeit
    truststoreFilename: "keycloak.truststore.jks"

  ingress:
    enabled: true
    hostname: keycloak.k.home.net
    ingressClassName: nginx
    pathType: Prefix
    tls: true
    annotations:
      cert-manager.io/issuer: "cluster-adcs-issuer"                   #use specific name of issuer
      cert-manager.io/issuer-kind: "ClusterAdcsIssuer"                #or ClusterAdcsIssuer
      cert-manager.io/issuer-group: "adcs.certmanager.csf.nokia.com"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/proxy-body-size: 1000m
      nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"


  postgresql:
    enabled: true
    auth:
      password: <snip>
```

### What is the expected behavior?

working application

### What do you see instead?

https://keycloak.k.home.net redirects to https://keycloak.k.home.net/auth and returns a 404
