### ISSUE TITLE
Wordpress warning about memcached not running on localhost

### ISSUE THREAD

**Issue by bellini666** [bitnami/charts#16118]
### Name and Version

bitnami/wordpress:15.3.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy the chart without any memcached option set (so it uses the default)
2. Update it with `memcached.enabled: true`

### What is the expected behavior?

That only the external deployed memcached instance would be used and the installation would not warn me about memcached not running

### What do you see instead?

```
The following memcached servers are not responding or not running:

Database Cache: localhost:11211.
This message will automatically disappear once the issue is resolved.
```

### Additional information

I have set `externalCache.host: ''` but I still see that issue

**Comment by bellini666** [comment]
@mdhont I'm deploying the chart using kustomize using the `helmCharts` generator. This is my current config (I replaces specifics with `...`)

```
helmCharts:
  - name: wordpress
    releaseName: wordpress
    repo: https://charts.bitnami.com/bitnami
    version: 15.3.5
    namespace: wordpress
    valuesInline:
      wordpressUsername: veroo
      existingSecret: secrets
      wordpressEmail: ...
      wordpressFirstName: ...
      wordpressLastName: ...
      wordpressBlogName: ...
      wordpressScheme: https
      wordpressConfigureCache: true
      smtpHost: ...
      smtpPort: ...
      smtpUser: ...
      smtpExistingSecret: secrets
      updateStrategy:
        type: Recreate
      persistence:
        storageClass: do-block-storage
      memcached:
        enabled: true
      externalCache:
        host: ''
        port: 0
      mariadb:
        primary:
          persistence:
            enabled: true
            storageClass: do-block-storage
      service:
        type: NodePort
      ingress:
        enabled: true
        annotations:
          cert-manager.io/issuer: cert-issuer
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/proxy-body-size: 100m
          nginx.ingress.kubernetes.io/proxy-send-timeout: 120
          nginx.ingress.kubernetes.io/proxy-read-timeout: 120
        hostname: ...
        tls: true
```

I had this issue when I first deployed something similar but without the `memcached.enabled: true` and changed it to `memcached.enabled: true`.

I ended up having to redeploy from scratch, and doing so with `memcached.enabled: true` did not produce the issue anymore.
