### ISSUE TITLE
AKS Bitnami Wordpress and Azurefiles PVC - Could not create directory

### ISSUE THREAD

**Issue by mmillard0** [bitnami/charts#16128]
### Name and Version

bitnami/wordpres 6.2.0

### What architecture are you using?

None

### What steps will reproduce the bug?

`helm upgrade -i wordpress -n mynamespace bitnami/wordpress -f wp-values.yaml`

wp-values.yaml:
```yaml
multisite:
  enable: true
  host: "myurl.com"
  networkType: "subdomain"
  enableNipIoRedirect: false
service:
  type: "ClusterIP"
ingress:
  enabled: false
persistence:
  enabled: true
  storageClass: myfilecsi-sc
  accessModes:
    -  ReadWriteMany
volumePermissions:
  enabled: true
```

### What is the expected behavior?

See the wordpress main page and the wp-content folder in the PVC (Azure File)

### What do you see instead?

When I am using persistence, when I try to access the blog I get this error:
![image](https://user-images.githubusercontent.com/77118562/233102633-2cd35f16-e446-489b-a221-89f7198679e6.png)

And when I try to install a plugin or theme manually I get an error related to permissions:

### Additional information

Accessing the File Shares (PVC) I can see just one file wp-config.php
There is no wp-content folder.

Nothing special in the wordpress pod's log. 

The Helm install without storageclass is working fine. It takes the default storageclass (disk.csi.azure.com) but I want to use a file.csi.azure (Standard_LRS and SMB protocol).
