### ISSUE TITLE
Unable to add locale (translation) into jasperreports:8.1.0 container

### ISSUE THREAD

**Issue by wh1test** [bitnami/charts#16132]
### Name and Version

bitnami/jasperreports:8.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I use JasperReports + Postgres in docker. Everything is working fine, but now I'm trying to add new locale (translation) according the [guide](https://community.jaspersoft.com/documentation/tibco-jasperreports-server-administrator-guide/v60/configuring-jasperreports-server-0).
As you can see there I have to adjust some files in folder jasperreports/WEB-INF including **applicationContext-security.xml** and restart Jasper.

So I tried to stop docker container, replace files and start it without luck (container jasperreports unable start: can't read **/opt/bitnami/tomcat/webapps/ROOT/index.jsp: No such file or directory**). 
BTW I see the error even with default jasper files when I try stop (`docker compose stop jasperreports`) and start (`docker compose start jasperreports`) the container.

In order to fix it I have to make `docker compose down` and `docker compose up -d` commands.
But in this case file **applicationContext-security.xml** replaced by default one during startup.

It seems JASPERREPORTS_SKIP_BOOTSTRAP=yes is not working properly.

My **docker-compose.yml**:
```
version: '3'
services:
  jasperreports:
    image: docker.io/bitnami/jasperreports:8.1.0
    container_name: jasperreports
    hostname: jasperreports
    ports:
      - '8888:8080'
    volumes:
      - 'jasperreports_data:/bitnami/jasperreports'
      - 'bitnami_dir:/opt/bitnami'
    depends_on:
      - postgres
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - JASPERREPORTS_SKIP_BOOTSTRAP=yes
      - JASPERREPORTS_USE_ROOT_URL=true
      - JASPERREPORTS_USERNAME=jasperadmin
      - JASPERREPORTS_PASSWORD=YYYYYYYYYYY
      - JASPERREPORTS_DATABASE_TYPE=postgresql
      - JASPERREPORTS_DATABASE_HOST=postgres
      - JASPERREPORTS_DATABASE_PORT_NUMBER=5432
      - JASPERREPORTS_DATABASE_USER=jasperserver
      - JASPERREPORTS_DATABASE_NAME=jasperserver
      - JASPERREPORTS_DATABASE_PASSWORD=XXXXXXXXXXXXXX
      - TZ=Europe/Riga
    networks:
      - jasperreportsnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 120s    

  postgres:
    image: postgres:14
    container_name: postgres
    hostname: postgres
    ports:
      - '5433:5432'    
    volumes:
      - 'postgres_jasper_data:/var/lib/postgresql/data'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRES_USER=jasperserver
      - POSTGRES_PASSWORD=XXXXXXXXXXXX
      - POSTGRES_DB=jasperserver
      - TZ=Europe/Riga
    networks:
      - jasperreportsnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jasperserver -d jasperserver -h 127.0.0.1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s

volumes:
  jasperreports_data:
    external: false
  bitnami_dir:
    external: false
  postgres_jasper_data:
    external: false

networks:
  jasperreportsnet:
    driver: bridge
```

### What is the expected behavior?

Jasperreports container should not replace config file applicationContext-security.xml when JASPERREPORTS_SKIP_BOOTSTRAP=yes 

### What do you see instead?

applicationContext-security.xml replaced during statup.
