### ISSUE TITLE
[influxdb helm chart] wrong nindent

### ISSUE THREAD

**Issue by carlosmkb** [bitnami/charts#1614]
nindent for `matchLables` in `requiredDuringSchedulingIgnoredDuringExecution` must be 18, if not the generated yaml will be:

```
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchLabels:
              app.kubernetes.io/name: influxdb
              app.kubernetes.io/instance: influxdb
            app.kubernetes.io/component: influxdb
```

and it will cause an error parsing the yaml
