### ISSUE TITLE
[bitnami/airflow] worker.lifecycleHooks does not work

### ISSUE THREAD

**Issue by acobaugh** [bitnami/charts#16153]
### Name and Version

bitnami/airflow 14.0.14

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Set `worker.lifecycleHooks` to anything.
Install airflow.
pod_template.yaml does not contain lifecycleHooks.

### Are you using any custom parameters or values?

```yaml
executor: KubernetesExecutor
worker:
  lifecycleHooks:
    preStop:
      exec:
        command: ["curl", "-X", "POST", "http://localhost:15020/quitquitquit"]
```

### What is the expected behavior?

lifecycle hooks should be rendered in pod_template.yaml

### What do you see instead?

They are not rendered.
