### ISSUE TITLE
Kafka and zookeeper cannot be successfully started through docker-compose

### ISSUE THREAD

**Issue by joelzzhang** [bitnami/charts#16188]
### Name and Version

bitnami/zookeeper:3.8 and bitnami/kafka:3.2

### What architecture are you using?

None

### docker-compose.yml
```yaml
version: "2"

services:
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.8
    network_mode: bridge
    ports:
      - "2181:2181"
    volumes:
      - "/data/bitnami/zookeeper:/bitnami/zookeeper"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3.2
    network_mode: bridge
    ports:
      - "9092:9092"
    volumes:
      - "/data/bitnami/kafka:/bitnami/kafka"
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    links:
      - zookeeper
```
### Start with the following command

`docker-compose up -d`

#### zookerper
```
zookeeper 08:23:29.16 
zookeeper 08:23:29.16 Welcome to the Bitnami zookeeper container
zookeeper 08:23:29.16 Subscribe to project updates by watching https://github.com/bitnami/containers
zookeeper 08:23:29.16 Submit issues and feature requests at https://github.com/bitnami/containers/issues
zookeeper 08:23:29.16 
zookeeper 08:23:29.16 INFO  ==> ** Starting ZooKeeper setup **
zookeeper 08:23:29.19 WARN  ==> You have set the environment variable ALLOW_ANONYMOUS_LOGIN=yes. For safety reasons, do not use this flag in a production environment.
zookeeper 08:23:29.19 INFO  ==> Initializing ZooKeeper...
zookeeper 08:23:29.19 INFO  ==> No injected configuration file found, creating default config files...
cp: cannot create regular file '/opt/bitnami/zookeeper/conf/zoo.cfg': Permission denied
```

#### kafka
```
kafka 08:23:29.48 
kafka 08:23:29.48 Welcome to the Bitnami kafka container
kafka 08:23:29.48 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 08:23:29.48 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 08:23:29.48 
kafka 08:23:29.48 INFO  ==> ** Starting Kafka setup **
kafka 08:23:29.54 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka 08:23:29.55 INFO  ==> Initializing Kafka...
kafka 08:23:29.55 INFO  ==> No injected configuration files found, creating default config files
/opt/bitnami/scripts/libfile.sh: line 39: /opt/bitnami/kafka/config/server.properties: Permission denied
```
**All commands are executed as root user**

#### zookerper
```
zookeeper 08:23:29.16 
zookeeper 08:23:29.16 Welcome to the Bitnami zookeeper container
zookeeper 08:23:29.16 Subscribe to project updates by watching https://github.com/bitnami/containers
zookeeper 08:23:29.16 Submit issues and feature requests at https://github.com/bitnami/containers/issues
zookeeper 08:23:29.16 
zookeeper 08:23:29.16 INFO  ==> ** Starting ZooKeeper setup **
zookeeper 08:23:29.19 WARN  ==> You have set the environment variable ALLOW_ANONYMOUS_LOGIN=yes. For safety reasons, do not use this flag in a production environment.
zookeeper 08:23:29.19 INFO  ==> Initializing ZooKeeper...
zookeeper 08:23:29.19 INFO  ==> No injected configuration file found, creating default config files...
cp: cannot create regular file '/opt/bitnami/zookeeper/conf/zoo.cfg': Permission denied
```

#### kafka
```
kafka 08:23:29.48 
kafka 08:23:29.48 Welcome to the Bitnami kafka container
kafka 08:23:29.48 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 08:23:29.48 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 08:23:29.48 
kafka 08:23:29.48 INFO  ==> ** Starting Kafka setup **
kafka 08:23:29.54 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka 08:23:29.55 INFO  ==> Initializing Kafka...
kafka 08:23:29.55 INFO  ==> No injected configuration files found, creating default config files
/opt/bitnami/scripts/libfile.sh: line 39: /opt/bitnami/kafka/config/server.properties: Permission denied
```
