### ISSUE TITLE
[bitnami/nginx-ingress-controller] Ingress annotation nginx.org/rewrites doesn't work

### ISSUE THREAD

**Issue by dumitrucatan** [bitnami/charts#16189]
### Name and Version

bitnami/nginx-ingress-controller:9.5.1

### What architecture are you using?

amd64

### 2. Create ingress resource as follows:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ui-admin
  namespace: myapp
  annotations:
    nginx.org/client-body-buffer-size: 1024m
    nginx.org/client-max-body-size: 1024m
    nginx.org/mergeable-ingress-type: minion
    nginx.org/proxy-connect-timeout: 5m
    nginx.org/proxy-ignore-client-abort: 'on'
    nginx.org/proxy-read-timeout: 5m
    nginx.org/proxy-send-timeout: 5m
    nginx.org/rewrites: |
      serviceName=myapp-ui-svc rewrite=/;
    nginx.org/websocket-services: myapp-ui-svc

spec:
  ingressClassName: nginx
  rules:
    - host: admin.app.mydomain.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myapp-ui-svc
                port:
                  number: 80
          - path: /myapp
            pathType: Prefix
            backend:
              service:
                name: myapp-ui-svc
                port:
                  number: 80
```

When accessing `admin.app.mydomain.net` we expect to have all the UI scripts loaded, instead we're getting the error of mime type. `The stylesheet https://admin.app.mydomain.net/myapp/assets/vendor.8eb5451c.css was not loaded because its MIME type, text/html, is not text/css”`. And a blank page is showed, the app is not loading.

 I know this is rewrite rule issue, because we have another UI app whose container path for resources is the same as ingress path, we don't apply rewrite there. That means all the routing is working perfectly, but for some reason rewrite  rule is not being picked up. Am I missing some additional config for this ingress controller ?

### Are you using any custom parameters or values?
```yaml
image:
  registry: docker.io
  repository: bitnami/nginx-ingress-controller
  tag: 1.7.0-debian-11-r2
watchIngressWithoutClass: true
ingressClassResource:
  name: nginx
  enabled: true
  default: true
  controllerClass: "k8s.io/ingress-nginx"
  parameters: {}

kind: DaemonSet
daemonset:
  useHostPort: true
  hostPorts:
    http: 80
    https: 443

containerPorts:
  http: 80
  https: 443
  metrics: 10254

service:
  type: NodePort
  ports:
    http: 80
    https: 443
  targetPorts:
    http: http
    https: https
```

### What is the expected behavior?

The page is loaded properly.

### What do you see instead?

A blank page
