### ISSUE TITLE
[bitnami/mariadb]  'auth.rootPassword' must not be empty when using Ansible to deploy or --dry-run with existingSecret set

### ISSUE THREAD

**Issue by rstoermer** [bitnami/charts#16194]
### Name and Version

bitnami/mariadb:12.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install mariadb with auth.existingSecret set
2. Do a --dry-run of mariadb with auth.existingSecret set and without changing any values

### Are you using any custom parameters or values?

```yaml
commonLabels:
  tier: data-layer

image:
  tag: 10.6.12-debian-11-r16

architecture: replication

auth:
  existingSecret: mariadb-creds

primary:
  persistence:
    size: 30G
    storageClass: ssd-low-retain

secondary:
  replicaCount: 2
  persistence:
    size: 30G
    storageClass: ssd-low-retain

metrics:
  enabled: true
```

### What is the expected behavior?

--dry-run runs without any problems on first upgrade.

### What do you see instead?

upgrade works, --dry-run does not. So this is probably why I can't use Ansible to upgrade the chart, as Ansible will probably check changes beforehand

```
command: helm upgrade -i mariadb oci://registry-1.docker.io/bitnamicharts/mariadb --values ./roles/cluster-deps/templates/helm-values-mariadb.yaml --dry-run

Pulled: registry-1.docker.io/bitnamicharts/mariadb:12.0.0
Digest: sha256:0c1457eb6ea094e415719bbcef260f58b13fde24f86b952d85ae5a14d445adcf
Error: UPGRADE FAILED: execution error at (mariadb/templates/secrets.yaml:3:21): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$MARIADB_ROOT_PASSWORD' to the command. To get the current value:

        export MARIADB_ROOT_PASSWORD=$(kubectl get secret --namespace "data-layer" mariadb-creds -o jsonpath="{.data.mariadb-root-password}" | base64 -d)
```
### Additional information

I am deploying with Ansible using kubernetes.core 2.4.0
