### ISSUE TITLE
[bitnami/matomo] Wrong include paths due to symlinks

### ISSUE THREAD

**Issue by tmechsner** [bitnami/charts#16233]
### Name and Version

bitnami/matomo 0.2.26

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We are running this chart with the (anonymized) values given below. 
On the volume we inserted a backup containing the folders `config`, `js`, `misc` and `plugins` into the directory `/bitnami/matomo/`.
Then nothing works, tracking, plugins, auto archiving etc., because in all these scripts relative imports of matomo core files are used.
However, relative imports don't work here, because the actual base directory is `/opt/bitnami/matomo/` which contains symlinks to the directories listed above. 
So, we fixed the files on the pv with relative imports and changed them to absolute paths.
Then everything worked as expected.
However, after a matomo restart all these scripts on the pv get overwritten and contain the non-functioning relative imports again.
Changing the imports manually fixes the problem until the next restart.

### Are you using any custom parameters or values?

```
namespaceOverride: tracking
image:
  tag: 4.14.1-debian-11-r0

matomoEmail: webadmin@xyz.com
matomoWebsiteName: Website Tracking
matomoWebsiteHost: tracking.website.com

smtpHost: "smtp-relay.mail-service.com"
smtpPort: 587
smtpUser: "user@website.com"
smtpPassword: "12345"

replicaCount: 1

updateStrategy:
  type: Recreate

persistence:
  enabled: true
  existingClaim: matomo-matomo-new

volumePermissions:
  enabled: true

resources:
  requests:
    cpu: 400m
    memory: 800Mi
  limits:
    cpu: 600m
    memory: 1Gi

service:
  type: NodePort

readinessProbe:
  enabled: true
  path: /matomo.php

livenessProbe:
  enabled: true
  path: /matomo.php

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: tracking.website.com
  tls: true
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
```

### What is the expected behavior?

We expect the symlinked folders on the pv to work like in every other non-cloud matomo installation without the need to manually modify the files.
If this is not possible, we at least expect our modifications on the persistent volume to persist and not get overwritten on matomo restart, which breaks the tracking.

### What do you see instead?

Lots of "File not found" errors, because relative imports from the symlinked directories in `/bitnami/matomo/` don't work, as the base application files are in `/opt/bitnami/matomo/`
