### ISSUE TITLE
[bitnami/kube-prometheus] enable compatibility with AWS managed service for prometheus

### ISSUE THREAD

**Issue by ripro-patrick** [bitnami/charts#16248]
### Name and Version

bitnami/kube-prometheus

### What is the problem this feature will solve?

configure aws managed service for prometheus ingestion:
https://eu-central-1.console.aws.amazon.com/prometheus/home

The following definitions are required as per aws prometheus configuration screen:
```
serviceAccounts:
    server:
        name: "amp-iamproxy-ingest-service-account"
        annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::046690449381:role/amp-iamproxy-ingest-role"
server:
    remoteWrite:
        - url: https://aps-workspaces.eu-central-1.amazonaws.com/workspaces/ws-9f2d668b-1fd6-473d-892f-9c442d346cf8/api/v1/remote_write
          sigv4:
            region: eu-central-1
          queue_config:
            max_samples_per_send: 1000
            max_shards: 200
            capacity: 2500
```

With the bitnami kube-prometheus chart, this would look something like this:
```
serviceAccount:
  create: true
  name: "amp-iamproxy-ingest-service-account"
  annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::046690449381:role/amp-iamproxy-ingest-role"
prometheus:
  remoteWrite:
      - url: https://aps-workspaces.eu-central-1.amazonaws.com/workspaces/ws-9f2d668b-1fd6-473d-892f-9c442d346cf8/api/v1/remote_write
        # sigv4: # does not work with kube-prometheus
        #   region: eu-central-1
        # queue_config: # does not work with kube-prometheus
        #   max_samples_per_send: 1000
        #   max_shards: 200
        #   capacity: 2500
```
sadly, the parameters "sigv4" and "queue_config" are not available in kube-prometheus.

can you please add the missing parameters to enable compatibility with AWS managed service for prometheus?

### What is the feature you are proposing to solve the problem?

enable compatibility with AWS managed service for prometheus

### What alternatives have you considered?

use the "prometheus-community" chart instead
