### ISSUE TITLE
[bitnami/matomo] behind reverse proxy Setup

### ISSUE THREAD

**Issue by slamer59** [bitnami/charts#16258]
### Name and Version

bitnami/matomo:0.2.30

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy the chart
2. Enable Ingress (Nginx) Reverse proxy
As stated here, one need to had some configurations. 

https://matomo.org/faq/how-to-install/faq_98/

I am seeing the same Internal IP 10.X.X.X (I guess form my k8s) instead of external IP.

Then I don't see php.ini or config as a config map. 
https://github.com/bitnami/charts/tree/main/bitnami/matomo/templates

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Tracking external IP

### What do you see instead?

Internal IP in 10.x.x.x

### Additional information

Implementing https://matomo.org/faq/how-to-install/faq_98/
could solve the problem

**Comment by jotamartos** [comment]
The Bitnami container for Matomo, allows you to configure those parameters to work behind a proxy setup. Please take a look at this section of the README

https://github.com/bitnami/containers/tree/main/bitnami/matomo#reverse-proxy-configuration-options

You can configure them in the extraEnvVars parameter of your values file to configure the application properly. 

Let us know if that works for you.

**Comment by slamer59** [comment]
Hello,
I just add this to value.yaml

```
matomo:
  ...
  extraEnvVars:
    - name: MATOMO_PROXY_CLIENT_HEADER
      value: HTTP_X_FORWARDED_FOR
    - name: MATOMO_ENABLE_FORCE_SSL
      value: "yes"
    - name: MATOMO_ENABLE_ASSUME_SECURE_PROTOCOL
      value: "yes"
```
Which is propageted to the pod : 
![image](https://user-images.githubusercontent.com/25283272/236435284-e60d7d03-a6f8-463b-868f-57f48d465225.png)

But I don't see improvement. Still identified has 10.2.XXX instead of 81.XXX

I probably don't understand the logic to debug. :(

![image](https://user-images.githubusercontent.com/25283272/236433936-e73fe06e-67dd-4eb3-a755-cf2647b42edc.png)
