### ISSUE TITLE
Drop secret mounts from keycloak

### ISSUE THREAD

**Issue by nevlkv** [bitnami/charts#16256]
### Name and Version

bitnami/keycloak 14.2.0

### What architecture are you using?

None

### What steps will reproduce the bug?

You drop [secrets mount](
https://github.com/bitnami/charts/commit/dc83778c2e40c9f7f011a2b747407e3f12aa2b54)

but in values [keys exists](https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml#L1021)

and its needed feature, ex i start spilo with keycloak and uses created operator secret

ex

```yaml
externalDatabase:
  host: io-keycloak
  port: 5432
  user: io_keycloak
  database: io_keycloak
  password: ""
  existingSecret: io-keycloak.io-keycloak.credentials.spilo
  existingSecretPasswordKey: password
```

### What do you see instead?

revert changes in[ commit](https://github.com/bitnami/charts/commit/dc83778c2e40c9f7f011a2b747407e3f12aa2b54)

@dalbani :question:

**Comment by dalbani** [comment]
(As I have been mentioned: I won’t be able to look at this issue before end of next week.)

**Comment by aoterolorenzo** [comment]
I just created a revert PR at #16617

**Comment by dalbani** [comment]
It's not clear to me what the problem exactly is, to be honest.
With the values provided above:
```
postgresql:
  enabled: false

externalDatabase:
  host: io-keycloak
  port: 5432
  user: io_keycloak
  database: io_keycloak
  password: ""
  existingSecret: io-keycloak.io-keycloak.credentials.spilo
  existingSecretPasswordKey: password
```
Here's the before/after difference to the YAML produced due to commit https://github.com/bitnami/charts/commit/dc83778c2e40c9f7f011a2b747407e3f12aa2b54:
```
# Source: keycloak/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
...
            - name: KEYCLOAK_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: io-keycloak.io-keycloak.credentials.spilo
                  key: password
            - name: KEYCLOAK_HTTP_RELATIVE_PATH
              value: "/"
          envFrom:
            - configMapRef:
                name: my-keycloak-env-vars
           envFrom:
             - configMapRef:
                 name: my-keycloak-env-vars
-            - secretRef:
-                name: io-keycloak.io-keycloak.credentials.spilo
           resources:
             limits: {}
             requests: {}
```
So given that Keycloak expects the environment variable `KEYCLOAK_DATABASE_PASSWORD` to be filled with the database password, I don't see why the removal of 2 lines in question in the YAML has any effect.

And what does this secret generated by Spilo contain by the way?
