### ISSUE TITLE
[bitnami/kube-prometheus] prometheus chart 1 node(s) didn't have free ports for the requested pod ports

### ISSUE THREAD

**Issue by eliassal** [bitnami/charts#16266]
### Name and Version

bitnami/kube-prometheus

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1 - I created a yaml file with the following
```yaml
alertmanager:
     persistentVolume:
           enabled: false
server:
      persistentVolume:
            enabled: false
```

2 - I ran the following command
`helm install prometheus -f prometheus-values.yml bitnami/kube-prometheus --namespace prometheus`
3. when I run to see the pods created , with
`kubectl get pods --namespace prometheus`
I see 3 in pending state
![image](https://user-images.githubusercontent.com/8447864/235185607-3655eefd-52f1-40c0-abad-2791888dfb30.png)

4.  I do a describe for 
 `kubectl describe pod prometheus-prometheus-kube-prometheus-prometheus-0 -n prometheus`

I see in the events

> 0/2 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 1 node(s) had untolerated taint {node.kubernetes.io/disk-pressure: }. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.

5. describe for the other pod  prometheus-node-exporter-q4s99

I see in the events 

>  0/2 nodes are available: 1 node(s) didn't have free ports for the requested pod ports. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod..

In spite of the fact that port 9100 is free, I checked so many times
 
So what might be wrong or what parameter should be used to avoid this? Thanks

### Are you using any custom parameters or values?
```yaml
alertmanager:
     persistentVolume:
           enabled: false
server:
      persistentVolume:
            enabled: false
```

### What is the expected behavior?

to have prometheus pods up and running

### What do you see instead?

3 pods in pending state and cant proceed
