### ISSUE TITLE
KRaft Controller Quorum Voters value always overwritten by setup.sh

### ISSUE THREAD

**Issue by jdfoster** [bitnami/charts#16261]
### Name and Version

bitnami/kafka 22.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Create a Kafka cluster with a custom voters values;  `helm install dc-2 bitnami/kafka --value vals.yaml`.

### Are you using any custom parameters or values?

```yaml
minId: 2
kraft:
  controllerQuorumVoters: >-
    0@dc-1-kafka-0.dc-1-kafka-headless.default.svc.cluster.local:9093,1@dc-1-kafka-1.dc-1-kafka-headless.default.svc.cluster.local:9093,2@dc-2-kafka-0.dc-2-kafka-headless.default.svc.cluster.local:9093
```

### What is the expected behavior?

We expect the user defined value `kraft.controllerQuorumVoters`  to be used to populate the `controller.quorum.voters` property in the file `/opt/bitnami/kafka/config/kraft/server.properties`.

### What do you see instead?

```sh
❯ kubectl exec -it dc-2-kafka-0 -- cat /opt/bitnami/kafka/config/kraft/server.properties | grep controller.quorum.voters
controller.quorum.voters=2@dc-2-kafka-0.dc-2-kafka-headless.default.svc.cluster.local:9093
```

### Additional information

The environmental variable `KAFKA_CFG_CONTROLLER_QUORUM_VOTERS` is always overwritten when `KAFKA_CFG_PROCESS_ROLES` includes `controller`; see [line](https://github.com/bitnami/charts/blob/483fcc8527b6005f31b16a963e28ebd837d09cbb/bitnami/kafka/templates/scripts-configmap.yaml#L110). This should only be overwritten when `KAFKA_CFG_CONTROLLER_QUORUM_VOTERS` is not set. This could be prevent by include a `-z "${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}"` to the logic on this [line](https://github.com/bitnami/charts/blob/483fcc8527b6005f31b16a963e28ebd837d09cbb/bitnami/kafka/templates/scripts-configmap.yaml#L96).
