### ISSUE TITLE
Can't install schema-registry with plaintext externalKafka

### ISSUE THREAD

**Issue by emeraldhieu** [bitnami/charts#16288]
### Name and Version

bitnami/schema-registry:10.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1) Install Kafka chart

```
helm install kafka42 oci://registry-1.docker.io/bitnamicharts/kafka
```

2) Install schema-registry chart 

```
helm install schema-registry42 -f k8s/schema-registry/values.yaml oci://registry-1.docker.io/bitnamicharts/schema-registry
```

with this "k8s/schema-registry/values.yaml"
```yaml
kafka:
  enabled: false
externalKafka:
  brokers:
    - PLAINTEXT://kafka42-0.kafka42-headless.default.svc.cluster.local:9092
```

Logs
```
Pulled: registry-1.docker.io/bitnamicharts/schema-registry:10.0.0
Digest: sha256:c92821475eddb9963e437965e7da7a894819a0a8039fe060657570a8a5fb248a
Error: INSTALLATION FAILED: template: schema-registry/templates/statefulset.yaml:4:95: executing "schema-registry/templates/statefulset.yaml" at <.Values.kafka.auth.clientProtocol>: nil pointer evaluating interface {}.clientProtocol
```

---
The line fails in `statefulset.yaml`
```
{{- $kafkaProtocol := include "schema-registry.listenerType" ( dict "protocol" (ternary .Values.kafka.auth.clientProtocol .Values.externalKafka.auth.protocol .Values.kafka.enabled) ) -}}
```

`kafka.enabled` is false but why would the ternary return the first argument?

### What is the expected behavior?

The helm chart is installed successfully.

**Comment by Hongbo-Miao** [comment]
Hi @emeraldhieu I got same error, and Attempt 3 is my workaround way. Hopefully it helps !

Worth fixing though, Bitnami team. 😃

## Attempt 1 (Failed)

```shell
helm upgrade \
  confluent-schema-registry \
  oci://registry-1.docker.io/bitnamicharts/schema-registry \
  --install \
  --namespace=hm-confluent-schema-registry \
  --create-namespace \
  --values=my-values.yaml
```

**my-values.yaml**

```
kafka:
  enabled: false
externalKafka:
  brokers:
    - PLAINTEXT://hm-kafka-kafka-bootstrap.hm-kafka.svc:9092
```

gives me error


```shell
Error: template: schema-registry/templates/statefulset.yaml:4:95: executing "schema-registry/templates/statefulset.yaml" at <.Values.kafka.auth.clientProtocol>: nil pointer evaluating interface {}.clientProtocol
```

## Attempt 2 (Failed)

**my-values.yaml**

```
kafka:
  enabled: false
externalKafka:
  brokers:
    - PLAINTEXT://hm-kafka-kafka-bootstrap.hm-kafka.svc:9092
```

gives me error


```shell
Error: template: schema-registry/templates/statefulset.yaml:7:29: executing "schema-registry/templates/statefulset.yaml" at <.Values.kafka.service.ports.client>: nil pointer evaluating interface {}.ports
```

## Attempt 3 (Succeed)

```yaml
kafka:
  enabled: false
  auth:
    protocol: plaintext
  service:
    ports:
      client: 9092
externalKafka:
  brokers:
    - PLAINTEXT://hm-kafka-kafka-bootstrap.hm-kafka.svc:9092
```

However, these two paramters

```
kafka:
  auth:
    protocol: plaintext
  service:
    ports:
      client: 9092
```

do not exist in [schema-registry/values.yaml](https://github.com/bitnami/charts/blob/c693dd78f26da6c495a9566c6a5b49ba15c6587c/bitnami/schema-registry/values.yaml) right now.
