### ISSUE TITLE
[bitnami/etcd] `service.clusterIP` only works when `service.type` is `ClusterIP`

### ISSUE THREAD

**Issue by icefery** [bitnami/charts#16325]
### Name and Version

bitnami/etcd 8.10.1

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Assuming that `service-cidr` is `10.16.0.0/16`.

2. Deploy bitnami/etcd charts with custom `values.yaml`.

   ```yaml
   auth:
     rbac:
       create: false
   service:
     type: NodePort
     clusterIP: 10.16.23.79
     nodePorts:
       client: 32379
       peer: 32380
   ```

3. When `service.type` is `NodePort` the configuarion is ignored.

   ```
   NAME              READY   STATUS    RESTARTS   AGE
   pod/etcd-client   1/1     Running   0          60m
   pod/etcd-0        1/1     Running   0          80s

   NAME                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                         AGE
   service/etcd-headless   ClusterIP   None            <none>        2379/TCP,2380/TCP               80s
   service/etcd            NodePort    10.16.215.129   <none>        2379:32379/TCP,2380:32380/TCP   80s

   NAME                    READY   AGE
   statefulset.apps/etcd   1/1     80s
   ```

4. When `service.type` is `ClusterIP` the configuration does work.

   ```
   NAME              READY   STATUS    RESTARTS   AGE
   pod/etcd-client   1/1     Running   0          56m
   pod/etcd-0        1/1     Running   0          12m

   NAME                    TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)             AGE
   service/etcd-headless   ClusterIP   None          <none>        2379/TCP,2380/TCP   12m
   service/etcd            ClusterIP   10.16.23.79   <none>        2379/TCP,2380/TCP   12m

   NAME                    READY   AGE
   statefulset.apps/etcd   1/1     12m
   ```

5. See templates from https://github.com/bitnami/charts/blob/main/bitnami/etcd/templates/svc.yaml at line 21, `service.clusterIP` only works when `service.type` is `ClusterIP`.

   ```yaml
   spec:
     type: {{ .Values.service.type }}
     {{- if and .Values.service.clusterIP (eq .Values.service.type "ClusterIP") }}
     clusterIP: {{ .Values.service.clusterIP }}
     {{- end }}
   ```

### Are you using any custom parameters or values?

Yes, see reproducing steps.

### What is the expected behavior?

`clusterIP` would work no matter which method I use to expose serivce.

For example, I reference a fixed etcd service clusterIP at coredns etcd-plugin while I want to access etcd outside together.

```
etcd {
    path /skydns
    endpoint http://10.16.23.79:2379
    fallthrough
}
```

### What do you see instead?

1. Manually set clusterIP to a fixed value.
2. Reference etcd endpoint with a fixed host + nodePort rather than a fixed clusterIP.

### Additional information

I wanted to open a PR but I found that other charts are configed with similar way.

I wonder if this is a feature, but I used it with a wrong way.
