### ISSUE TITLE
[bitnami/mongodb] Chart cannot deploy if Value 'configuration' file is provided with a 'security.keyFile'

### ISSUE THREAD

**Issue by rrileyca** [bitnami/charts#16386]
### Name and Version

bitnami/mongodb 13.9.4

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Deploy the chart with a MongoDB configuration file (see values section).

### Are you using any custom parameters or values?

```yaml
storage:
  dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
systemLog:
  destination: file
  quiet: false
  logAppend: true
  logRotate: reopen
  path: /opt/bitnami/mongodb/logs/mongodb.log
  verbosity: 0
net:
  port: 27017
  unixDomainSocket:
    enabled: true
    pathPrefix: /opt/bitnami/mongodb/tmp
  ipv6: false
  bindIpAll: true
  tls:
    allowConnectionsWithoutCertificates: true
replication:
  replSetName: rs0
  enableMajorityReadConcern: true
processManagement:
  fork: false
  pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
setParameter:
  enableLocalhostAuthBypass: false
security:
  authorization: enabled
  keyFile: /opt/bitnami/mongodb/conf/keyfile
```

### What is the expected behavior?

It seems that the ReplicaSet keyfile is created after MongoDB is started, but it's not clear why that happens to me. I believe the ReplicaSet keyfile should be created early in the initialization process.

### What do you see instead?

The pod would not start and instead threw the error below. Apologies, I had to write this error out by hand (it is not a copy+paste), so there may be a typo.
```
about to fork child process, waiting until server is ready for connections.
forked process: 78
ERROR: child process failed, exited with 1
to see additional information in this output, start without the "--fork" option.
```

### Additional information

Potentially related to https://github.com/bitnami/charts/issues/16385, my goal was to set the MongoDB setting of `net.tls.allowConnectionsWithoutCertificates`. In an attempt to do this:
1. I coped the contents of `/opt/bitnami/mongodb/conf/mongodb.conf` from within the container
2. I added these contents to the Chart `values.yaml`, under the `configuration` field.

In trying to get this working, I deleted the namespace to test a fresh deployment with `values.yaml` that were working.

To troubleshoot this (long story short) I put a `sleep 1000000` in the `setup.sh` before launching Mongo, entered the pod, and manually ran `mongod` until I found it complaining that the file `/opt/bitnami/mongodb/conf/keyfile` does not exist. This file was set in the `values.yaml` under the `configuration` field, in the MongoDB configuration file: `security.keyFile`.
