### ISSUE TITLE
[bitnami/thanos] Allow templating jobName for default PrometheusRules

### ISSUE THREAD

**Issue by dragoangel** [bitnami/charts#16403]
### Name and Version

bitnamicharts/thanos 12.5.1

### What is the problem this feature will solve?

Allow configuring `jobName` in `prometheusRule` for `default` resources separately per `resource`.
Example of `.Values`:
```yaml
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    ## @param metrics.serviceMonitor.relabelings [array] Specify general relabeling
    ##
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        targetLabel: instance
  ## PrometheusRule CRD configuration
  ##
  prometheusRule:
    ## @param metrics.prometheusRule.enabled If `true`, creates a Prometheus Operator PrometheusRule (also requires `metrics.enabled` to be `true`)
    ##
    enabled: true
    jobNames:
      query: thanos-query
      sidecar: monitoring-thanos-discovery
      ruler: monitoring-thanos-ruler
```

### What is the feature you are proposing to solve the problem?

It will allow to create alerts for resources managed outside of current Helm chart. It's common to have `kube-prometheus-stack` to have deploy `thanos-ruler` and `thanos-sidecar` while all other resources (`query`, `queryFrontend`, `store`, `compactor`, etc) with `bitnamicharts/thanos`.
