### ISSUE TITLE
ERROR: backend authentication failed, backend response with kind 'E' when expecting 'R'

### ISSUE THREAD

**Issue by leonidas-o** [bitnami/charts#16408]
### Name and Version

bitnami/postgresql-ha 11.5.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. On kubernetes deployed postgresql-ha via ArgoCD with `1. initial parameters` listed below.
2. Created port-forward to `postgresql-ha-pgpool`, connected with a postgresql client and user `postgres`, created new role and database
3. As connecting wit newly created role was not possible (`SCRAM authentication failed DETAIL: pool_passwd file does not contain an entry for ...`), added the secret to the kubernetes cluster and the parameters `2. updated parameters` listed below to the ArgoCD app file.
4. postgresql-ha-pgpool pod gets re-created but is not able to boot up (`postgresql-ha DETAIL: backend response with kind 'E' when expecting 'R'`) anymore.

### Are you using any custom parameters or values?

1. initial parameters
```yaml
      parameters:
        - name: global.imageRegistry
          value: my-registry
        - name: global.storageClass
          value: nfs-client
        - name: persistence.size
          value: 2Gi
```

2. updated parameters
```yaml
        - name: pgpool.customUsersSecret
          value: my-project-pgpool
```
where the secret itself contains the following entries:
```yaml
data:
  usernames: BASE64ENCODEDUSERNAME
  passwords: BASE64ENCODEDPASSWORD
```

### What is the expected behavior?

Unfortunately there is not enough documentation about how to do that. I would like to create a new Role and Database and let my service use this new Role and DB to connect and work with postgresql. I would expect adding this new Role and Password via `pgpool.customUsersSecret` would leave everything intact and just allow that specific Role to authenticate.

### What do you see instead?

`postgresql-ha-pgpool-84fd496687-ckcl4       0/1       CrashLoopBackOff `
```bash
│ 2023-05-05 14:17:47.616: main pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 2                                                                                                                                                                       │
│ 2023-05-05 14:17:48.171: child pid 161: ERROR:  backend authentication failed                                                                                                                                                                                                              │
│ 2023-05-05 14:17:48.172: child pid 161: DETAIL:  backend response with kind 'E' when expecting 'R'  
```

### Additional information

Either a bug or simply lack of knowledge using the `values.yaml` as this part is not fully documented.
