### ISSUE TITLE
[bitnami/thanos] Support generation of Bucket Groupcache config file in Helm 

### ISSUE THREAD

**Issue by dragoangel** [bitnami/charts#16400]
### Name and Version

bitnamicharts/thanos 12.5.1

### What is the problem this feature will solve?

Thanos Store has a new in-memory shared cache between multiple replicas of Store and other types but bitnami helm chart for Thanos has a bit tricky configuration for it which should be handled fully by user, while it can be simplified I think.

https://thanos.io/tip/components/store.md/#experimental-groupcache-caching-bucket-provider:~:text=dns%2Bhttp%3A//store.thanos.consul.svc%3A8080

This option could be passed as an environment variable from generated secret
There is an option to use `${POD_IP}` for `self_link`.

For `peers` we need to use DNS discovery. Thanos documentation does not mention clearly if `dnssrv+` is possible in that place, but after checking source code https://github.com/thanos-io/thanos/blob/v0.31.0/pkg/cache/groupcache.go#L45-L46 it clearly supported, so:
`dnsrv+http://_http._tcp.{{ include "common.names.fullname" . }}-storegateway-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}` to generate link

I also checked that `${POD_IP}` or other variables will be processed by Thanos properly while passing them in `--store.caching-bucket.config=<yaml content>`

Also if we enable `groupcache` we need to enable headless service as a dependency even if it doesn't explicitly enabled.

Another thing to care about is Store ingress. We need prohibit access to `/_groupcache` from ingress, as it can be exposed to public. This path should be only available locally between Thanos Stores. More details: https://thanos.io/tip/components/store.md/#experimental-groupcache-caching-bucket-provider
I see it as a commented-out examples:
1. 
```yaml
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* "^/_groupcache" {
          deny all;
          return 403;
        }
```
server-snippets is the best option but some ingresses administrators disable them cluster-wide, so the second option requires to have some `thanos-storegateway-groupcache-blackhole` that will look to actually not used port
2. 
```yaml
  - path: /_groupcache
    pathType: ImplementationSpecific
    backend:
      service:
        name: thanos-storegateway-groupcache-blackhole
        port:
          number: 50000
```

I think this `thanos-storegateway-groupcache-blackhole` should be created if `.Values.store.bucketGroupCache.enabled .Values.store.ingress.enabled` are met. 

### What is the feature you are proposing to solve the problem?

It will allow to use Groupcache Caching Bucket Provider in Thanos Store which should improve the performance of this component

**Comment by dragoangel** [comment]
I get things working without changing helm chart, I think it was a bit tricky to do, maybe there plans to provide some general settings to configure it more easier? Or add some samples to docs? If no - then issue can be closed.

For a reference for other people how to configure this:
```
storegateway:
  enabled: true
  extraEnvVars:
    # https://thanos.io/tip/components/store.md/#index-cache
    - name: INDEX_CACHE_CONFIG
      value: |-
        type: IN-MEMORY
        config:
          max_size: 250MB
          max_item_size: 125MB
    # https://thanos.io/tip/components/store.md/#caching-bucket
    - name: STORE_CACHING_BUCKET_CONFIG
      value: |-
        type: GROUPCACHE
        config:
          self_url: http://$(POD_IP):10902
          peers:
            - dnssrv+http://_http._tcp.{{ include "common.names.fullname" . }}-storegateway-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
          groupcache_group: {{ include "common.names.fullname" . }}
          dns_interval: 3s
          timeout: 5s
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  extraFlags:
    # https://thanos.io/tip/components/store.md/#index-cache
    - --index-cache.config=$(INDEX_CACHE_CONFIG)
    # https://thanos.io/tip/components/store.md/#caching-bucket
    - --store.caching-bucket.config=$(STORE_CACHING_BUCKET_CONFIG)
  replicaCount: 2
  resources:
    limits: {}
    requests: {}
  service:
    ## @param storegateway.service.additionalHeadless Additional Headless service
    ## used to configure peers via dnssrv record in STORE_CACHING_BUCKET_CONFIG
    additionalHeadless: true
  ingress:
    enabled: true
    hostname: thanos-store.example.org
    ingressClassName: nginx
    annotations:
      # disable access to /_groupcache as it contains sensetive data that should be only available locally
      # https://thanos.io/tip/components/store.md/#store:~:text=disable%20access%20to%20/_groupcache/
      nginx.ingress.kubernetes.io/server-snippet: |-
        location ~* "^/_groupcache/.+" {
            deny all;
            return 403;
          }
      nginx.ingress.kubernetes.io/auth-type: basic
      # name of the secret that contains the user/password definitions
      # created by kube-prometheus-stack
      nginx.ingress.kubernetes.io/auth-secret: thanos-monitoring-ingress-auth-basic
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    extraTls:
      - hosts:
          - thanos-store.example.org
        secretName: ingress-default-cert
    path: /
    pathType: ImplementationSpecific
  persistence:
    enabled: true
    size: 5Gi
```
