### ISSUE TITLE
could not download chart: failed to authorize: failed to fetch anonymous token: unexpected status: 400 Bad Request

### ISSUE THREAD

**Issue by xyfleet** [bitnami/charts#16434]
### Name and Version

bitnamicharts/wordpress 16.0.4

### What architecture are you using?

None

### What steps will reproduce the bug?

1: install wordpress helm chart with terraform code below:
```
resource "helm_release" "wordpress" {
    repository = "oci://registry-1.docker.io/bitnamicharts/wordpress"
    name       = "wordpress"
    chart      = "wordpress"
    version    = "16.0.4" 
    namespace = "wordpress"
}
```

2: Got the error below:
`
Error: could not download chart: failed to authorize: failed to fetch anonymous token: unexpected status: 400 Bad Request
`

### What is the expected behavior?

Expected to download and install this chart correctly. 

### What do you see instead?

See the error:

`Error: could not download chart: failed to authorize: failed to fetch anonymous token: unexpected status: 400 Bad Request
`

**Comment by xyfleet** [comment]
I noticed that previous repo link is `https://charts.bitnami.com/bitnami
`
Not sure if this still OK to use?

**Comment by javsalgar** [comment]
Hi,

Do you see if the 400 error appears when using the helm client directly? Not sure if it's something with the Terraform integration

**Comment by poligraph** [comment]
I have got the same error while used `chart-syncer` https://github.com/bitnami-labs/charts-syncer


```
charts-syncer sync -v 6
I0509 14:14:13.494981   13810 sync.go:49] Looking for the default config charts-syncer.yaml
I0509 14:14:13.495829   13810 config.go:37] 'source.repo.chartsIndex' property is empty. Using "registry-1.docker.io//bitnamicharts/memcached/charts-index:latest" default value
I0509 14:14:13.495908   13810 syncer.go:124] Using workdir: "/Users/user/.charts-syncer"
I0509 14:14:13.495959   13810 cachedisk.go:39] Allocating cache dir: "/Users/user/.charts-syncer/c46f5a2d31c0ed5dd9a137737482f4674c8257b3"
I0509 14:14:13.495998   13810 oci.go:428] Attempting to retrieve remote index...
INFO[0001] trying next host                              error="failed to authorize: failed to fetch anonymous token: unexpected status: 400 Bad Request" host=registry-1.docker.io
Error: unable to download index: failed to authorize: failed to fetch anonymous token: unexpected status: 400 Bad Request
```
on other side I could pull it with helm with no issues
`helm pull oci://registry-1.docker.io/bitnamicharts/memcached`

**Comment by dsukhoroslov** [comment]
I have the same issue installing keycloak dependency from `oci://registry-1.docker.io/bitnamicharts/keycloak` repo with `helm dependency build` command. But `helm pull` command works properly.

**Comment by xyfleet** [comment]
@javsalgar I managed to install wordpress correctly by using `https://charts.bitnami.com/bitnami` not `(oci://registry-1.docker.io/bitnamicharts/wordpress)`
I tried to use client directly and got same error. Should not be related to Terraform.

**Comment by fmulero** [comment]
The 400 Bad Request error suggest me that the client is sending something wrong. 

@xyfleet could you share the version of Helm Provider for Terraform (terraform-provider-helm)? Please note several issues about  token refresh or authentication in OCI repositories where fixed in version 2.5.1 or higher.
What do you mean with?: 
> I tried to use client directly and got same error
Did you try it with helm? Could you share also the version? Are you running the commands behind a proxy or any other network device that might be causing the issue?

Hi @dsukhoroslov, about dependencies we have faced a similar issue with other OCI repositories. In our case the issue was solved setting the dependencies in alphabetically  reversed  order. I know it seems tricky, but it works and the seems related to how containerd pulls the images.

**Comment by batalist23** [comment]
According to helm [docs](https://helm.sh/docs/topics/registries/#specifying-dependencies) you should specify repository without a chart name.
 `repository = "oci://registry-1.docker.io/bitnamicharts"` not  `repository = "oci://registry-1.docker.io/bitnamicharts/wordpress"`

**Comment by batalist23** [comment]
According to helm [docs](https://helm.sh/docs/topics/registries/#specifying-dependencies) you should specify registry name without a chart name.
So ` repository = "oci://registry-1.docker.io/bitnamicharts"`  and not ` repository = "oci://registry-1.docker.io/bitnamicharts/wordpress"`

**Comment by dsukhoroslov** [comment]
Thanks @batalist23, without a chart name it works properly!

**Comment by xyfleet** [comment]
@batalist23 Thank you so much. It works without a chart name.

**Comment by xyfleet** [comment]
@javsalgar @fmulero One more question here, thanks in advance. I tried to update my blog address and failed. 
my blog address should be "http://www.example.com/blog". 


tried to add this in the value file, 
```
wordpressExtraConfigContent:
  define('WP_HOME',      'http://www.example.com/blog');
  define('WP_SITEURL',   'http://www.example.com/blog');
```
However, after the deployment, the wp-config.php did not get updated. How can I update the url and home?

**Comment by fmulero** [comment]
Thanks a lot @batalist23! I didn't realize on that.

@xyfleet If you are using the nginx ingress controller you can try with a values file like this one (more information [here](https://kubernetes.github.io/ingress-nginx/examples/rewrite/)):

```yaml
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  path: /blog(/|$)(.*)
  pathType: Prefix
customPostInitScripts:
  wp-home-blog.sh: |
    #!/bin/bash
    chmod +w /bitnami/wordpress/wp-config.php
    sed -i "s|define( 'WP_HOME', 'http://' \. \$_SERVER\['HTTP_HOST'\] \. '/' );|define( 'WP_HOME', 'http://' \. \$_SERVER\['HTTP_HOST'\] . '/blog' );|g" /bitnami/wordpress/wp-config.php
    sed -i "s|define( 'WP_SITEURL', 'http://' \. \$_SERVER\['HTTP_HOST'\] \. '/' );|define( 'WP_SITEURL', 'http://' \. \$_SERVER\['HTTP_HOST'\] . '/blog' );|g" /bitnami/wordpress/wp-config.php
    wp cli cache clear
    chmod -w /bitnami/wordpress/wp-config.php
````

Please follow these steps:
1. Force running the initialization scripts: `kubectl exec -it deploy/wordpress -- rm /bitnami/wordpress/.user_scripts_initialized`
2. Upgrade your deployment (`helm upgrade ....`)
3. Force a deployment rollout restart: `kubectl rollout restart deploy/wordpress`

If you still having problems, please open a new issue.
