### ISSUE TITLE
unable to create solr in kubernetes v1.22.12

### ISSUE THREAD

**Issue by ivanmissu** [bitnami/charts#16439]
### Name and Version

bitnami/solr 7.4.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

i used bitnami/solr 7.4.1[9.2.1], but i modify the version to repository: bitnami/solr
  tag: 8.3.1-r24.

### Are you using any custom parameters or values?
```yaml
global:
  imageRegistry: ''
  imagePullSecrets: []
  storageClass: ''
kubeVersion: ''
nameOverride: ''
fullnameOverride: ''
clusterDomain: cluster.local
commonLabels: {}
commonAnnotations: {}
extraDeploy: []
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity
image:
  registry: docker.io
  repository: bitnami/solr
  tag: 8.3.1-r24
  digest: ''
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
auth:
  enabled: false
  adminUsername: admin
  adminPassword: ''
  existingSecret: ''
  existingSecretPasswordKey: solr-password
coreNames:
  - yzqwhy
  - heritage
cloudEnabled: false
cloudBootstrap: false
collection: my-collection
collectionShards: 1
collectionReplicas: 2
serverDirectory: server
javaMem: ''
heap: ''
command:
  - /scripts/setup.sh
args: []
extraEnvVars: []
extraEnvVarsCM: ''
extraEnvVarsSecret: ''
replicaCount: 1
containerPorts:
  http: 8983
livenessProbe:
  enabled: true
  initialDelaySeconds: 40
  periodSeconds: 10
  timeoutSeconds: 15
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 15
  failureThreshold: 6
  successThreshold: 1
startupProbe:
  enabled: false
  initialDelaySeconds: 40
  periodSeconds: 10
  timeoutSeconds: 15
  failureThreshold: 15
  successThreshold: 1
customLivenessProbe: {}
customReadinessProbe: {}
customStartupProbe: {}
lifecycleHooks: {}
resources:
  limits: {}
  requests: {}
podSecurityContext:
  enabled: true
  fsGroup: 1001
containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true
hostAliases: []
podLabels: {}
podAnnotations: {}
podAffinityPreset: ''
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ''
  key: ''
  values: []
affinity: {}
nodeSelector: {}
tolerations: []
topologySpreadConstraints: []
podManagementPolicy: Parallel
priorityClassName: ''
schedulerName: ''
updateStrategy:
  type: RollingUpdate
  rollingUpdate: {}
pdb:
  create: false
  minAvailable: 1
  maxUnavailable: ''
extraVolumes: []
extraVolumeMounts: []
initContainers: []
sidecars: []
service:
  type: ClusterIP
  ports:
    http: 8983
  nodePorts:
    http: ''
  sessionAffinity: None
  sessionAffinityConfig: {}
  clusterIP: ''
  loadBalancerIP: ''
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster
  annotations: {}
  extraPorts: []
  headless:
    annotations: {}
ingress:
  enabled: false
  ingressClassName: ''
  pathType: ImplementationSpecific
  apiVersion: ''
  hostname: solr.local
  path: /
  annotations: {}
  tls: false
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraTls: []
  secrets: []
  extraRules: []
persistence:
  enabled: true
  existingClaim: ''
  storageClass: ''
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  annotations: {}
  mountPath: /bitnami/solr
  subPath: ''
  subPathExpr: ''
  selector: {}
volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 11-debian-11-r111
    digest: ''
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits: {}
    requests: {}
  containerSecurityContext:
    runAsUser: 0
serviceAccount:
  create: false
  name: ''
  automountServiceAccountToken: true
  annotations: {}
tls:
  enabled: false
  autoGenerated: false
  certificatesSecretName: ''
  passwordsSecretName: ''
  keystorePassword: ''
  truststorePassword: ''
  resources:
    limits: {}
    requests: {}
metrics:
  enabled: false
  configFile: /opt/bitnami/solr/prometheus-exporter/conf/solr-exporter-config.xml
  threads: 7
  command: []
  args: []
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  containerPorts:
    http: 9231
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 15
    failureThreshold: 15
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 15
    failureThreshold: 15
    successThreshold: 15
  startupProbe:
    enabled: false
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 15
    successThreshold: 1
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  resources:
    limits: {}
    requests: {}
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  podLabels: {}
  podAnnotations: {}
  podAffinityPreset: ''
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ''
    key: ''
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
  priorityClassName: ''
  schedulerName: ''
  hostAliases: []
  updateStrategy:
    type: RollingUpdate
    rollingUpdate: {}
  extraVolumes: []
  extraVolumeMounts: []
  initContainers: []
  sidecars: []
  service:
    type: ClusterIP
    ports:
      http: 9231
    sessionAffinity: None
    clusterIP: ''
    annotations: {}
    labels: {}
  serviceMonitor:
    enabled: false
    namespace: ''
    interval: ''
    scrapeTimeout: ''
    additionalLabels: {}
    selector: {}
    relabelings: []
    metricRelabelings: []
    honorLabels: false
    jobLabel: ''
  prometheusRule:
    enabled: false
    namespace: ''
    additionalLabels: {}
    rules: []
zookeeper:
  enabled: false
  fourlwCommandsWhitelist: 'srvr,mntr,conf,ruok'
  containerPorts:
    client: 2181
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: ''
    accessModes:
      - ReadWriteOnce
    size: 8Gi
externalZookeeper:
  servers: []
```

### What is the expected behavior?

how to deploy it 

### What do you see instead?
```
Error: error while running post render on files: error while running command /tmp/helm-operator/prod_solr-ihuxnm_qympplmmm8jp07/helm-post-render.sh. error output: Error: map[string]interface {}(nil): yaml: unmarshal errors: line 104: mapping key "failureThreshold" already defined at line 97 line 102: mapping key "initialDelaySeconds" already defined at line 98 line 105: mapping key "periodSeconds" already defined at line 99 line 106: mapping key "successThreshold" already defined at line 100 line
```
