### ISSUE TITLE
[bitnami/kafka] could not start in cluster mode

### ISSUE THREAD

**Issue by alita1991** [bitnami/charts#16530]
### Name and Version

bitnami/kafka:19.0.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Deploy kafka + zookeeper in cluster mode (it does not reproduce all the time, just from time to time)

### Are you using any custom parameters or values?

```
defaultReplicationFactor: 3
metrics:
  jmx:
    enabled: true
  kafka:
    enabled: true
offsetsTopicReplicationFactor: 3
persistence:
  enabled: true
  size: 8Gi
  storageClass: ""
replicaCount: 3
transactionStateLogReplicationFactor: 3
zookeeper:
  enabled: true
  metrics:
    enabled: true
  persistence:
    enabled: true
    size: 8Gi
    storageClass: ""
  replicaCount: 3
```

### What is the expected behavior?

```
[zk: localhost:2181(CONNECTED) 0] ls /brokers/ids
[0, 1, 2]
```

### What do you see instead?

```
[zk: localhost:2181(CONNECTED) 0] ls /brokers/ids
[0, 1]

```
OR

```
[zk: localhost:2181(CONNECTED) 0] ls /brokers/ids
[0]
```

### Additional information

EKS 1.22 (6 nodes of type m5.xlarge)
Applications are installed in parallel via ArgoCD (Kafka + other microservices)
No issue was found when installing sequentially

Resource consumption of nodes
```
NAME                                          CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
ip-10-195-68-109.us-west-2.compute.internal   442m         11%    5021Mi          34%       
ip-10-195-68-114.us-west-2.compute.internal   239m         6%     2957Mi          20%       
ip-10-195-68-190.us-west-2.compute.internal   324m         8%     6866Mi          46%       
ip-10-195-68-225.us-west-2.compute.internal   263m         6%     4190Mi          28%       
ip-10-195-68-33.us-west-2.compute.internal    556m         14%    4694Mi          31%       
ip-10-195-68-4.us-west-2.compute.internal     228m         5%     3661Mi          24%  
```
