### ISSUE TITLE
Attach existing volume as persistence storage

### ISSUE THREAD

**Issue by yywing** [bitnami/charts#16559]
### Name and Version

all chart

### What is the problem this feature will solve?

Can I disable pvc and use exist volume in all bitnami chart?

postgrest-ha as example:

value.yaml
```yaml
    extraVolumes:
      - name: data
        nfs:
          server: "1"
  persistence:
    enabled: false
```

gen k8s config:
```yaml
        - name: data
          nfs:
            server: "1"
         ...
        - name: data
          emptyDir: {}
```

### What is the feature you are proposing to solve the problem?

some thing like:
```
        - name: data
          nfs:
            server: "1"
```
