### ISSUE TITLE
[bitnami/mongodb-sharded] auth.existingSecret cannot be templated

### ISSUE THREAD

**Issue by soniqua** [bitnami/charts#16563]
### Name and Version

bitnami/mongodb-sharded 6.4.2

### What is the problem this feature will solve?

I would like to consume an external secret with a templated name, similar to:

```YAML
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "other-chart.fullname" . }}-mongodb-auth
```

And then reference this in the `values.yaml` file as:

```YAML
mongodb-sharded:
  auth:
    existingSecret: '{{ include "other-chart.fullname" . }-mongodb-auth'
```

As the chart evaluates this value as a literal, I cannot do so.

### What is the feature you are proposing to solve the problem?

Allow `existingSecret` to be templated using `tpl`.
