### ISSUE TITLE
[bitnami/keycloak] Service Monitor template is ignoring httpRelativePath setting

### ISSUE THREAD

**Issue by maxnitze** [bitnami/charts#16572]
### Name and Version

bitnami/keycloak 15.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. set `httpRelativePath` to something else than `/` (e.g. `/auth/` for backwards compatability with older Keycloak setups)
* https://github.com/bitnami/charts/blob/55aa23dc703ae88971d5c2fb3583e0b3f06c9787/bitnami/keycloak/values.yaml#L203
2. enable `metrics` and `metrics.serviceMonitor`
* https://github.com/bitnami/charts/blob/55aa23dc703ae88971d5c2fb3583e0b3f06c9787/bitnami/keycloak/values.yaml#L743-L765

### What is the expected behavior?

I actually don't know. I assumed, that the service monitor chart would use the relative path and prefix its configured endpoints with it. Instead it used the plain endpoint configs. Therefore it could not scrape the metrics and our alerts fired.

### What do you see instead?

Scraping the metrics of the Keycloak instance failed and our alerts fired, because no Keycloak pod was up and running.

### Additional information

We fixed this now by overwriting the `metrics.servicemonitor.endpoints`:

```yaml
httpRelativePath: /auth/
...
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    endpoints:
      - path: /auth/metrics
      - path: /auth/realms/master/metrics
```

I'm not entirely sure if this is by design, or if the service monitor template should automatically use the `httpRelativePath`, when it is set.

In case you see this as a bug in the chart I'm happy to provide a PR to fix it.
