### ISSUE TITLE
[bitnami/contour] ask to define shutdown , readiness, metric and liveness ports in values.yaml

### ISSUE THREAD

**Issue by Sinamcp** [bitnami/charts#16586]
### Name and Version

11.3.1

### What is the problem this feature will solve?

Hi, We deploy 3 contour (because we have 3 ingressclasses) with hostnetwork:true on one node, we faced issue for  envoy pods because shutdown port, liveness, metric and readiness probe ports are hardcode, it would be great to define these ports in valuse.yaml.
we use helm proxy chart for contour, thats why we can not change deployment directly.

it is the proxy chart configuration,

```
apiVersion: v2
name: contour-ingress-controller
description: A Helm chart for Kubernetes
type: application
version: 1.24.4
sources:
- https://artifacthub.io/packages/helm/bitnami/contour
dependencies:
  - name: contour
    version: 11.3.1
    repository: https://charts.bitnami.com/bitnami
    alias: private
  - name: contour
    version: 11.3.1
    repository: https://charts.bitnami.com/bitnami
    alias: public
  - name: contour
    version: 11.3.1
    repository: https://charts.bitnami.com/bitnami
    alias: inter-dc
```

### What is the feature you are proposing to solve the problem?

Add shutdown, liveness, metric and readiness ports to values.yaml
