### ISSUE TITLE
[bitnami/mysql] metrics setup is incompatible with customPasswordFiles

### ISSUE THREAD

**Issue by Yaytay** [bitnami/charts#16604]
### Name and Version

bitnami/mysql 9.7.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Using docker-desktop and argocd (though any helm should have the same issue).
2. With the values below, specifying a customPasswordFile and a secret that is mounted as an extraVolumeMount
3. There is no way to get the secret mounted in the metrics container.
Note that the MYSQL_ROOT_PASSWORD_FILE is set correctly:
```bash
MYSQL_ROOT_PASSWORD_FILE=/etc/mysql/credentials/root/password
```
there is just no way to create that file.

The statefulset template just has:
```yaml
          {{- if and .Values.auth.usePasswordFiles (not .Values.auth.customPasswordFiles) }}
          volumeMounts:
            - name: mysql-credentials
              mountPath: /opt/bitnami/mysqld-exporter/secrets/
          {{- end }}
```

### Are you using any custom parameters or values?

```yaml
        auth:
          usePasswordFiles: true
          customPasswordFiles:
            root: /etc/mysql/credentials/root/password
        metrics:
          enabled: true
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
        primary:
          resources:
            limits:
              memory: 4Gi
            requests:
              memory: 3Gi
          extraVolumes:
          - name: root-secret
            secret:
              secretName: mysql-root-credentials
          extraVolumeMounts:
          - name: root-secret
            mountPath: /etc/mysql/credentials/root
            readOnly: true
```

### What is the expected behavior?

There should be a way to get a custom volume mounted in the metrics container.

### What do you see instead?

No way to get a custom volume mounted in the metrics container.

### Additional information

I think the metrics block should support an extraVolumeMounts, just like the primary/secondary containers do.
I'll create a PR that does that.
