### ISSUE TITLE
Ignoring changes to 'blog.example.com' because a suitable Azure DNS zone was not found.

### ISSUE THREAD

**Issue by travisforte** [bitnami/charts#16631]
### Name and Version

bitnami/external-dns ^6.13.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

AKS Server Version: v1.24.3

Using bitnami/external-dns version `6.13.1` or greater with it's default `image.tag: 0.13.2-debian-11-r0` or greater will fail to take any action on Azure DNS records with the following error message...
`Ignoring changes to 'blog.example.com' because a suitable Azure DNS zone was not found.`

I am able to successfully use versions greater than `6.13.1` by pinning the `image.tag: 0.13.1-debian-11-r19`, so I believe the issue has to do with the image version.

`image.tag: 0.13.1-debian-11-r19` or lower works
`image.tag: 0.13.2-debian-11-r0` or greater errors

### Are you using any custom parameters or values?

```
  replicaCount: 3
  provider: azure
  azure:
    tenantId: xxxxx
    subscriptionId: xxxxxx
    resourceGroup: xxxx
    useManagedIdentityExtension: true
    userAssignedIdentityID: xxxxx
  policy: sync
  domainFilters: [qa.example.com, dev.example.com]
  service:
    enabled: false
  logFormat: json
```

### What is the expected behavior?

For Azure DNS records to be updated, like below...

`Updating TXT record named 'blog.example.com' to '"heritage=external-dns,external-dns/owner=default,external-dns/resource=ingress/blog-dev/user-service"' for Azure DNS zone 'example.com'.`

### What do you see instead?

`Ignoring changes to 'blog.example.com' because a suitable Azure DNS zone was not found.`
