### ISSUE TITLE
[bitnami/postgresql-ha] Dynamic provisioning with ReadWriteMany and multiple replicas on AWS EKS 

### ISSUE THREAD

**Issue by redaER7** [bitnami/charts#16645]
### Name and Version

bitnami/postgresql-ha 15.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am trying to attach `ReadWriteMany` persistence volume claims to postgresql-ha helm chart with following values on AWS EKS

```yaml
postgresql:
  replicaCount: 3
image:
  debug: true
persistence:
  ## @param primary.persistence.enabled Enable PostgreSQL Primary data persistence using PVC
  ##
  enabled: true
  ## @param primary.persistence.existingClaim Name of an existing PVC to use
  ##
  existingClaim: ""
  ## @param primary.persistence.mountPath The path the volume will be mounted at
  ## Note: useful when using custom PostgreSQL images
  ##
  mountPath: /bitnami/postgresql
  ## @param primary.persistence.subPath The subdirectory of the volume to mount to
  ## Useful in dev environments and one PV for multiple services
  ##
  #subPath: ""
  ### @param primary.persistence.storageClass PVC Storage Class for PostgreSQL Primary data volume
  ### If defined, storageClassName: <storageClass>
  ### If set to "-", storageClassName: "", which disables dynamic provisioning
  ### If undefined (the default) or set to null, no storageClassName spec is
  ###   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ###   GKE, AWS & OpenStack)
  ###
  storageClass: "efs-sc"
  ### @param primary.persistence.accessModes PVC Access Mode for PostgreSQL volume
  ###
  accessModes:
    - ReadWriteMany
  ### @param primary.persistence.size PVC Storage Request for PostgreSQL volume
  ###
  size: 25Gi
```

`efs-sc` is a storage class where I'm attaching multi ReadWrite pvc with aws efs storage

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-XXXX
  directoryPerms: "700"
  gidRangeStart: "1000" # optional
  gidRangeEnd: "2000" # optional
  basePath: "/dynamic_provisioning" # optional
```

Dynamic proivsionning with this storage class is working well with other deployments, but when I'm using it with `bitnami/postgresql-ha` , it's not working

Bitnami claims are well created for the 3 replicas:

```bash
NAME                                       STATUS   VOLUME                                     CAPACITY
 ACCESS MODES   STORAGECLASS   AGE
data-postgres-postgresql-ha-postgresql-0   Bound    pvc-edb527bc-e38e-4ff1-ac3c-4dc7ab7984d3   25Gi
 RWX            efs-sc         6m3s
data-postgres-postgresql-ha-postgresql-1   Bound    pvc-8bab8e74-309c-48ae-8282-42a8cc2e46e2   25Gi
 RWX            efs-sc         6m3s
data-postgres-postgresql-ha-postgresql-2   Bound    pvc-1f3a862e-1d94-4357-bf72-7a7e772edd41   25Gi
```

Master node fails to start
```bash
postgres-postgresql-ha-pgpool-866fcddc58-g5c4q   0/1     Running            6 (51s ago)     8m52s
postgres-postgresql-ha-postgresql-0              0/1     CrashLoopBackOff   6 (3m1s ago)    8m52s
postgres-postgresql-ha-postgresql-1              0/1     Running            5 (2m22s ago)   8m52s
postgres-postgresql-ha-postgresql-2              0/1     Running            5 (81s ago)     8m51s
```

with following logs

```bash
kubectl -n dev describe pod postgres-postgresql-ha-postgresql-0
>>
Events:
  Type     Reason            Age                     From               Message
  ----     ------            ----                    ----               -------
  Warning  FailedScheduling  8m53s                   default-scheduler  0/4 nodes are available: 4 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled         8m51s                   default-scheduler  Successfully assigned dev/postgres-postgresql-ha-postgresql-0 to ip-XXX.XXX.compute.internal
  Normal   Pulled            7m23s (x5 over 8m50s)   kubelet            Container image "docker.io/bitnami/postgresql-repmgr:15.2.0-debian-11-r0" already present on machine
  Normal   Created           7m23s (x5 over 8m50s)   kubelet            Created container postgresql
  Normal   Started           7m23s (x5 over 8m50s)   kubelet            Started container postgresql
  Warning  BackOff           3m43s (x30 over 8m46s)  kubelet            Back-off restarting failed container
```

```bash
kubectl -n dev logs postgres-postgresql-ha-postgresql-0
>>
postgresql-repmgr 11:49:28.55
postgresql-repmgr 11:49:28.55 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 11:49:28.55 Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql-repmgr 11:49:28.55 Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql-repmgr 11:49:28.56
postgresql-repmgr 11:49:28.57 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 11:49:28.61 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 11:49:28.61 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 11:49:28.62 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 11:49:28.68 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 11:49:28.69 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 11:49:28.69 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 11:49:28.86 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 11:49:28.88 INFO  ==> Initializing Repmgr...
postgresql-repmgr 11:49:28.89 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 11:49:28.91 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 11:49:28.91 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
```

Logs are not very helpful here,

Anyone face same issue please ?
Thanks,

### Are you using any custom parameters or values?

please see values

### What do you see instead?

```bash
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  11m                 default-scheduler  0/4 nodes are available: 4 pod has unbound immediate PersistentVolumeClaims.
```

### Additional information

jjjj

**Comment by javsalgar** [comment]
Hi,

Could you try setting image.debug=true in both images so we get more debug information?

**Comment by redaER7** [comment]
Adding Debug on the pool
```yaml
...
pgpool:
  imgage:
    debug: true
```

Then,  Logs from the master node

```bash
postgresql-repmgr 17:08:09.56 DEBUG ==> Ensuring expected directories/files exist...
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /bitnami/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
2023-05-16 17:08:10.400 UTC [188] FATAL:  data directory "/bitnami/postgresql/data" has wrong ownership
2023-05-16 17:08:10.400 UTC [188] HINT:  The server must be started by the user that owns the data directory.
child process exited with exit code 1
initdb: removing contents of data directory "/bitnami/postgresql/data"
running bootstrap script ... %
```bash

and logs from the pool

```bash
...
2023-05-16 17:10:24.501: main pid 1: WARNING:  failed to connect to PostgreSQL server, getaddrinfo() failed with error "Name or service not known"
2023-05-16 17:10:24.501: main pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 1
2023-05-16 17:10:24.502: main pid 1: WARNING:  failed to connect to PostgreSQL server, getaddrinfo() failed with error "Name or service not known"
2023-05-16 17:10:24.502: main pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 2
```

**Comment by migruiz4** [comment]
Hi @redaER7,

Could you please add the flag `-p` to your `kubectl logs` command? 
```
kubectl -n dev logs -p postgres-postgresql-ha-postgresql-0
```

This flag will display the logs from the previously running container (the one that is failing) instead of the currently running one, which should give us some more useful information about the cause of the error.

**Comment by aki263** [comment]
Facing exactly same issue, init container says 

`chown: changing ownership of '/bitnami/postgresql': Operation not permitte`

Dynamically provisioned EFS
![image](https://github.com/bitnami/charts/assets/5713674/819377ac-8696-4b5c-9b18-2f9a17d268ac)

**Comment by migruiz4** [comment]
Hi @aki263,

Some users have reported issues when running EFS dynamic provisioning and charts that include **non-root containers**.

This appears to be an issue with how EFS works and not our charts/images, as it appears to happen if any other image is deployed with a non-root user.

I'm sorry but it would be out of my scope to help configure EFS to run with non-root containers, but in case it helps, some users reported that configuring EFS AccessPoint worked for them.

**Comment by GiovanniPaoloGibilisco** [comment]
Hi, 
I incurred in the same issue with a EKS cluster v 1.30 and EFS using dynamic provisioning. 
We are using chart v.15.2.13 and postgres image 14.12.0-debian-12-r4

Mi first idea was to disable the security context as we do when running on openshift but that didn't help 
```
#Tried but not working
primary:
  containerSecurityContext:
    enabled: false

  podSecurityContext:
    enabled: false
```

So i falled back in changing the efs storage class to  not use dynamic uid and gids but assign the same gid to all the folders. It worked as now all folders have 1001 as gid and postgres is happy. 
Luckly no other container was picky on the gid and everything started. 

Here is my storageclass for reference.

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-my-efs-id
  directoryPerms: "700"
  uid: "1001"
  gid: "1001"
    #  gidRangeStart: "1000" # this (and the next one) was casuing the issue
    #  gidRangeEnd: "2000" # this (and the previous one) was causing the issue
    #  basePath: "/dynamic_provisioning" # optional
  subPathPattern: "${.PVC.namespace}/${.PV.name}" # optional
  ensureUniqueDirectory: "true" # optional
  reuseAccessPoint: "false" # optional
```

Clearly a better solution would be to configure postgres to run as non root and cope with the gid, maybe also using an init container to change the folder permissions so that the issue scope is limited to the init container which might be run as root or with another gid.
