### ISSUE TITLE
Seccomp Profiles

### ISSUE THREAD

**Issue by pomland-94** [bitnami/charts#16679]
### Name and Version

bitnami/*

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Hey,
I have to use special sec comp Profiles, is it possible to add these to any Helm Deployment? I can't find any value for this.

I also have to set this value to false `containerSecurityContext.allowPrivilegeEscalation` which is no problem, but how can I set sec comp Profiles?

**Comment by fmulero** [comment]
Hi @pomland-94, thanks for using Bitnami charts.

You can set `seccompProfile` in the `podSecurityContext` value already present in most of our charts. I have to recognize that it is not documented but podSecurityContext is an object and it is rendered in the `Deployments` or `Statefulsets` as it is filled by the user, only removing the `enabled` field. https://github.com/bitnami/charts/blob/c199dd402c39db14cc3631276964a100cbce6221/bitnami/wordpress/templates/deployment.yaml#L67-L69

NOTE: I am not sure if I understood clearly your question because I've seen [you are already using it](https://github.com/bitnami/charts/issues/12690). Please correct me if I am wrong.

**Comment by pomland-94** [comment]
When I try to setup for example cert-manager with the following values:
`
helm install certificate-manager oci://registry-1.docker.io/bitnamicharts/cert-manager \
--namespace certificate-manager --create-namespace \
--set installCRDs=true \
--set replicaCount=2 \
--set controller.replicaCount=2 \
--set controller.podSecurityContext.enabled=true \
--set controller.containerSecurityContext.enabled=true \
--set webhook.replicaCount=2 \
--set webhook.podSecurityContext.enabled=true \
--set webhook.containerSecurityContext.enabled=true \
--set webhook.securityContext.allowPrivilegeEscalation=false \
--set webhook.securityContext.capabilities.drop="{ALL}" \
--set webhook.securityContext.seccompProfile.type="RuntimeDefault" \
--set cainjector.podSecurityContext.enabled=true \
--set cainjector.containerSecurityContext.enabled=true \
--set cainjector.securityContext.allowPrivilegeEscalation=false \
--set cainjector.securityContext.capabilities.drop="{ALL}" \
--set cainjector.securityContext.seccompProfile.type="RuntimeDefault" \
--set metrics.enabled=true \
--set rbac.create=true
`

I get the following error:
`
E0517 22:57:20.943031   16889 memcache.go:121] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0517 22:57:20.963913   16889 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request
E0517 22:57:21.038029   16889 memcache.go:287] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0517 22:57:21.048496   16889 memcache.go:287] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request
E0517 22:57:21.068323   16889 memcache.go:121] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0517 22:57:21.089424   16889 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request
E0517 22:57:21.160222   16889 memcache.go:287] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0517 22:57:21.177626   16889 memcache.go:287] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request
E0517 22:57:21.197235   16889 memcache.go:121] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0517 22:57:21.218133   16889 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request
W0517 22:57:24.900463   16889 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "cainjector" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "cainjector" must set securityContext.capabilities.drop=["ALL"]), seccompProfile (pod or container "cainjector" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0517 22:57:24.981046   16889 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "cert-manager" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "cert-manager" must set securityContext.capabilities.drop=["ALL"]), seccompProfile (pod or container "cert-manager" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0517 22:57:25.074086   16889 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "cert-manager-webhook" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "cert-manager-webhook" must set securityContext.capabilities.drop=["ALL"]), seccompProfile (pod or container "cert-manager-webhook" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
`

I have install my Kubernetes Cluster with Kubespray and use extra Values for Hardening my Cluster, see this link here:
https://kubespray.io/#/docs/hardening

**Comment by pomland-94** [comment]
I get the following error:

```
[root@bastion-20 ingress-controller]# helm install ingress-controller oci://registry-1.docker.io/bitnamicharts/nginx-ingress-controller --namespace ingress-controller --create-namespace -f values.yaml
Pulled: registry-1.docker.io/bitnamicharts/nginx-ingress-controller:9.6.3
Digest: sha256:cdbaf7f467a6f9a57cb17fe54dea7e475a3032eda06bea741cd2ec82ff3823ed
Error: INSTALLATION FAILED: 2 errors occurred:
	* Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal string into Go struct field SecurityContext.spec.template.spec.containers.securityContext.seccompProfile of type v1.SeccompProfile
	* Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal string into Go struct field SecurityContext.spec.template.spec.containers.securityContext.seccompProfile of type v1.SeccompProfile
```

My Values File looks like:

```
clusterDomain: elastic-cloud.io
dhParam: "LS0tLS1CRUdJTiBESCBQQVJBTUVURVJTLS0tLS0KTUlJQ0NBS0NBZ0VBNHRsY2x2VjRhU29qaENNYjFqRTJJNmVHd0UrRmsvMXZCbmNNUVRKSFBpRzM3U1RFRUZDVwppeENyYjlJYlZLWUpVSkpSY1RPS0NRZUdHeGZydC9yZFladWVXS3JOQ1VjQlNRajYxVm0wd25RcDk4VllvbTJhCm5Jbkl1UUhqZGxhWXJ1QjYvTlZES3AzMnE1c0RhQlQrMXZnRU9ielo5bzVVdmRGdXV6c2hkOWdMdXdQaFJSOFgKU2RRVGd6eDR2aENubGdsY1hIMGgwY2dEYkVSYWVlTWVxaDVnOUQ5MkFITEoyYUZPbzV0NWQ4UXlWZUxVWVNMaQp0RHdGT0xoSlFMb0EwR25JQzc0Tmc1NG9zQjArNUUwOG4vQkphYVNTbVVxYmtsMFNNdjNkWHlwT2I3L1FLczdRCnhSMUMvYWJORkRSaCswcUM1aTQxdkJlOFFmUUpKb3Fqd1pTaVJQb21manYrU0l3MTFSdFpFNTdqUVlleXlpWnUKOWNXT0NUcUEzZGhUMmdXOS9kMTh5dENJWTNZT2g4K0Yrb3FvZjlnWkNiTkZXN0tQYjlwOHRVbktpRVRxWS9QSwo5ZStWdXFlTnpTN01pUm1hUVBBVGtBbkNIMVhjYlJWOFZxeDYzTlpvb21WcGo4OURraHZoZHUwdS9Zc0Q3NFhSCitOa2pwNDk1VWpRUEhDYVVHbnJKMlUzaHJ0VmxpS0FPeTRZWjFYZmVpUnJsd2dnUUcrZmlFejlIcVloOUFxRisKOElGRU9tei9JZ3NZcEpyRDBsWkVIa0dWV0g2QitzdVlHd2FHTDdDMmo0VE5pNjlaWGZtZ3ExMDA4ZDh3MUJLRwozK1pNY20xendvUm9laDI4Yk54Y3RsOEpkR3lMNWJxalZ4a1RWeTJFZXhGVHBzQlI4RWMyR2tzQ0FRST0KLS0tLS1FTkQgREggUEFSQU1FVEVSUy0tLS0tCg=="
replicaCount: 3

podSecurityContext:
  enabled: true
  fsGroup: 1001

containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false
  runAsUser: 1001
  capabilities:
    drop: ["ALL"]
    add: ["NET_BIND_SERVICE"]
  seccompProfile: "RuntimeDefault"
  runAsNonRoot: true

startupProbe:
  enabled: true
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

defaultBackend:
  enabled: true
  replicaCount: 3

  podSecurityContext:
    enabled: true
    fsGroup: 1001

  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    seccompProfile: "RuntimeDefault"

  startupProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 0
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5

service:
  type: NodePort

rbac:
  create: true

pdb:
  create: false
  minAvailable: 1

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5

metrics:
  enabled: true
  serviceMonitor:
    enabled: false

  prometheusRule:
    enabled: false
```

**Comment by pomland-94** [comment]
Found my Error:

```
containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    runAsUser: 1001
    capabilities:
      drop: ["ALL"]
      add: ["NET_BIND_SERVICE"]
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
```
This is correct so
