### ISSUE TITLE
[bitnami/supabase] Existing jwt secret is overwritten, although it should not be.

### ISSUE THREAD

**Issue by jsmueller7** [bitnami/charts#16706]
### Name and Version

bitnami/supabase 0.3.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create a secret, anon-key, and service-key according to the Docker Swarm installation instructions (follow steps 1-4) https://www.linode.com/docs/guides/installing-supabase/#generating-api-keys-and-secrets
2. Encode the values in base64 and transfer the values into a secret with the following structure:
```
apiVersion: v1
kind: Secret
metadata:
  name: <jwt-secret-name>
  namespace: <your-namespace-name>
type: Opaque
data:
  secret: <secret-string, base64>
  anon-key: <anon-key, base64>
  service-key: <service-key, base64>
```
3. Apply the secret to your cluster and check, if the secret reflects the correct values.
4. Set the folowing value in your values.yaml
```
global:
  jwt:
    existingSecret: <jwt-secret-name>
```
5. Install the helm chart and repeat 3. - now the secret string is still in place, but you'll find a different anon-key and service-key. This will lead to errors when using studio, for example when you create a new table.

### Are you using any custom parameters or values?

```
global:
  jwt:
    existingSecret: <jwt-secret-name>
rbac:
  create: false
serviceAccount:
  create: false
  name: <service-account-name>
  annotations: {}
postgresql:
  auth:
    existingSecret: <porstgres-secret-name>
studio:
  ingress:
    enabled: true
    hostname: <my-supabase-hostname>
    annotations:
    ingressClassName: <my-ingress-controller>
kong:
  ingress:
    enabled: true
    className:  <my-ingress-controller>
    hostname: <my-kong-hostname>
  service:
    type: ClusterIP
```

### What is the expected behavior?

Step 3 and 5 should give the same results. Instead, the secret is overwritten and after installing the Helm Chart, the secret contains different values.

### What do you see instead?

As mentioned in 5.

### Additional information

A cumbersome way to fix the problem is to install the self-created secret again after step 5 and restart the studio pod. At least in the studio GUI, this will allow studio to communicate with the database again.

**Comment by jsmueller7** [comment]
I've found a way to make it work. Obviously the problem is with the jwt-init-iob, that should not be executed, if a jwt is provided. The workaround is to add the folowing lines to the custom-values.yaml
```
jwt:
  secret: "secret"
  anonKey: "anon-key"
  serviceKey: "service-key"
```
- in conjunction with the specification of an existing jwt-secret:
```
global:
  jwt:
    existingSecret: <jwt-secret-name>
```
There could be different approaches to fix this. I found out that line 265 in `templates/_helpers.tpl` says
```
{{- if or .Values.jwt.autoGenerate.forceRun (and (not (and .Values.jwt.secret .Values.jwt.anonKey .Values.jwt.serviceKey)) .Release.IsInstall) -}}
```
- and since there are no defaults for `.Values.jwt.secret` `.Values.jwt.anonKey` `.Values.jwt.serviceKey` the problem went away by setting some.
