### ISSUE TITLE
[bitnami/kafka] Zookeeper user creation attempted while using KRaft

### ISSUE THREAD

**Issue by exaucae** [bitnami/charts#16727]
### Name and Version

bitnami/kafka 22.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy chart with values.yaml below

### Are you using any custom parameters or values?

````yaml
image:
 debug: true  
kraft:
  clusterId: "xxxxxxxx"
  controllerQuorumVoters: "0@kafka-0.kafka-headless.kafka.svc.cluster.local"
superUsers: User:alice;User:bob
auth:
  clientProtocol: sasl_tls
  externalClientProtocol: sasl_tls
  interBrokerProtocol: sasl_tls
  controllerProtocol: sasl_tls
  tls:
    type: pem
    autoGenerated: true
  sasl:
    mechanisms: scram-sha-256,scram-sha-512
    interBrokerMechanism: scram-sha-512
    jaas:
      clientUsers:
        - alice
      existingSecret: kafka-jaas-secret
````

### What is the expected behavior?

Zookeeper is never invoked. Since it's disabled by default.

### What do you see instead?

Zookeeper user creation is initiated. See last line of ogs below

````sh

18
kafka 02:50:59.05 
17
kafka 02:50:59.05 Welcome to the Bitnami kafka container
16
kafka 02:50:59.05 Subscribe to project updates by watching https://github.com/bitnami/containers
15
kafka 02:50:59.05 Submit issues and feature requests at https://github.com/bitnami/containers/issues
14
kafka 02:50:59.05 
13
kafka 02:50:59.06 INFO  ==> ** Starting Kafka setup **
12
kafka 02:50:59.13 DEBUG ==> Validating settings in KAFKA_* env vars...
11
kafka 02:50:59.16 INFO  ==> Initializing Kafka...
10
kafka 02:50:59.17 INFO  ==> No injected configuration files found, creating default config files
9
kafka 02:50:59.84 INFO  ==> Configuring Kafka for inter-broker communications with SASL_SSL authentication.
8
kafka 02:50:59.88 INFO  ==> Configuring Kafka for client communications with SASL_SSL authentication.
7
kafka 02:50:59.89 INFO  ==> Configuring Kafka for external client communications with SASL_SSL authentication.
6
kafka 02:50:59.90 INFO  ==> Generating JAAS authentication file
5
kafka 02:50:59.91 INFO  ==> Creating users in Zookeeper
4
kafka 02:50:59.91 DEBUG ==> Creating user alice in zookeeper
3
Warning: --zookeeper is deprecated and will be removed in a future version of Kafka.
2
Use --bootstrap-server instead to specify a broker to connect to.
1
A HostProvider may not be empty!

````

### Additional information

Helm 3.8
K8s 1.23

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the inconvenience. Kraft support was added recently and there is several issues reported on this regarding.
  We are reviewing it and we will come back as soon as we have news.

**Comment by exaucae** [comment]
One important update regarding this is that the issue disappear when:
-  changing all auth protocols in the initial values.yml from `sasl_tls `to `plaintext` mode.
-  removing sasl config, specially `sasl.jaas.clientUsers`

That's a workaround to have kafka up and running. It introduces security risks, since communications aren't secured anymore.

Consequently, looking into ties between zookeeper and `sasl.jaas.clientUsers` could be a good start. Something might still be on even with kRaft is enable

**Comment by 98sean98** [comment]
I'm seeing the same error as well. 

```
Helm: 3.12
K8: 1.24.9
bitnami/kafka chart: 22.1.3
```

Chart values (abbreviated):

```
replicaCount: 2
image:
    tag: 3.4.0
    debug: true
superUsers: User:admin
auth:
    clientProtocol: sasl
    externalClientProtocol: sasl_tls
    interBrokerProtocol: plaintext
    controllerProtocol: plaintext
sasl:
    mechanisms: plain,scram-sha-256,scram-sha-512
    jaas:
        clientUsers:
            - user
        existingSecret: kafka-sasl
tls:
    autogenerated: false
    existingSecrets:
        - kafka-cert-0
        - kafka-cert-1
```

The necessary k8 secrets like `kafka-sasl`, `kafka-cert-0` and `kafka-cert-1` have been created before running `helm install` of the kafka chart.

For now, I've switched back to using zookeeper, and disabled kraft. And things work as expected. Hopefully, it's possible to use kraft reliably soon.

**Comment by fanzeming-st** [comment]
```
bitnami/kafka: 22.1.6
```
I manage to run kafka in kraft mode with sals enabled.
This is part of my values.yaml.
```
auth:
    # client may not support self signed certs. not to use tls by default
    clientProtocol: sasl
    interBrokerProtocol: sasl_tls
    controllerProtocol: sasl_tls
    sasl:
      # fix: if scram-* are enabled, the initialized scripts will call zookeeper, which will failed in kraft mode.
      mechanisms: plain
  extraEnvVars:
    # fix: this environment variable is needed if sasl and kraft mode are enabled.
    - name: KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL
      value: "plain"
```
I hope this could help you.
