### ISSUE TITLE
[bitnami/kafka] Failed KRaft Initialization

### ISSUE THREAD

**Issue by exaucae** [bitnami/charts#16722]
### Name and Version

bitnami/kafka 22.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. override values.yaml with samle below
2. Install chart in a cluster

### Are you using any custom parameters or values?

````yaml
kafka:
  kubeVersion: "1.23"
  kraft:
    enabled: true
    processRoles: broker,controller
    controllerListenerNames: CONTROLLER
    clusterId: "xxxxxxxx"
    controllerQuorumVoters: "0@kafka-0.kafka-headless.kafka.svc.cluster.local"

  networkPolicy:
    enabled: true

  externalAccess:
    enabled: true
    autoDiscovery:
      enabled: true
    service:
      type: ClusterIP
      ports:
        external: 9095
      domain: kafka.foo.com

  persistence:
    size: 2Gi

  rbac:
    create: true


````

### What is the expected behavior?

KRaft is properly initialized

### What do you see instead?

_CrashLoop Back-off_ events. Pod keeps restarting due to failed container initialization.

**The logs are stuck at KRaft initialization**:

````sh

kafka 18:57:19.92 
16
kafka 18:57:19.93 Welcome to the Bitnami kafka container
15
kafka 18:57:19.93 Subscribe to project updates by watching https://github.com/bitnami/containers
14
kafka 18:57:19.93 Submit issues and feature requests at https://github.com/bitnami/containers/issues
13
kafka 18:57:19.93 
12
kafka 18:57:19.93 INFO  ==> ** Starting Kafka setup **
11
kafka 18:57:19.98 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
10
kafka 18:57:19.99 INFO  ==> Initializing Kafka...
9
kafka 18:57:19.99 INFO  ==> No injected configuration files found, creating default config files
8
kafka 18:57:20.47 INFO  ==> Configuring Kafka for inter-broker communications with PLAINTEXT authentication.
7
kafka 18:57:20.48 WARN  ==> Inter-broker communications are configured as PLAINTEXT. This is not safe for production environments.
6
kafka 18:57:20.48 INFO  ==> Configuring Kafka for client communications with PLAINTEXT authentication.
5
kafka 18:57:20.49 WARN  ==> Client communications are configured using PLAINTEXT listeners. For safety reasons, do not use this in a production environment.
4
kafka 18:57:20.49 INFO  ==> Configuring Kafka for external client communications with PLAINTEXT authentication.
3
kafka 18:57:20.49 WARN  ==> External client communications are configured using PLAINTEXT listeners. For safety reasons, do not use this in a production environment.
2
kafka 18:57:20.49 INFO  ==> Initializing KRaft...
1
kafka 18:57:20.49 INFO  ==> Formatting storage directories to add metadata...

````

It doesn't go further than `Formatting storage directories to add metadata...`. [That line](https://github.com/bitnami/containers/blob/f6bcdf046219e6193bea76985d271f0e333c0cbf/bitnami/kafka/3.4/debian-11/rootfs/opt/bitnami/scripts/libkafka.sh#L800) originates from [kRaft initialization](https://github.com/bitnami/containers/blob/36b8f3a81d8f70629f364ca5617b4335ee5480dc/bitnami/kafka/3.4/debian-11/rootfs/opt/bitnami/scripts/kafka/setup.sh#L52).

My values must be doing something that prevents the script from [moving on](https://github.com/bitnami/containers/blob/f6bcdf046219e6193bea76985d271f0e333c0cbf/bitnami/kafka/3.4/debian-11/rootfs/opt/bitnami/scripts/libkafka.sh#L801).

That's why the issue is openned in the chart repo, and not the container one. If proven it has noting to do with the chart, I'll gladl y move it.

My guess is that there's an issue with finding the persitence volume. If that's likely the case, I'll expand on my theory.

### Additional information

Version:
 - Helm 3.8
 - K8s 1.23

**Comment by exaucae** [comment]
this comment is to keep the issue open since it was labelled `in progress`

**Comment by zacheryph** [comment]
I am running into this as well. Values below:

```yaml
persistence:
  enabled: true
replicaCount: 3
metrics:
  kafka:
    enabled: true
  serviceMonitor:
    enabled: true
    namespace: system-monitor
kraft:
  clusterId: "xxxxxxxx"
```
