### ISSUE TITLE
Allow Spring Cloud Config Server Usage With spring-cloud-dataflow Chart

### ISSUE THREAD

**Issue by meditations180** [bitnami/charts#16723]
### Name and Version

bitnami/spring-cloud-dataflow 18.1.1

### What is the problem this feature will solve?

[Spring Cloud Config Server](https://docs.spring.io/spring-cloud-config/docs/current/reference/html/) cannot be used with the `spring-cloud-dataflow` chart.

The `SPRING_CLOUD_CONFIG_ENABLED` env variable is hardcoded to `false` and there is no way to override it.

This applies to both the `server` component and the `skipper` component.

### Proposal
1. Add a new Dataflow Server parameter:
    - Name: `server.cloudConfigEnabled`
    - Description: `Enable Spring Cloud Config`
    - Value: `false`
2. Use value of above parameter as value for  `SPRING_CLOUD_CONFIG_ENABLED` env variable.

### Current implementation:
```yaml
          env:
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
```

### Proposed implementation:
```yaml
          env:
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: {{ ternary "true" "false" .Values.server.cloudConfigEnabled | quote }}
```
NOTE: For the `skipper` component above value would be `.Values.skipper.cloudConfigEnabled`, instead.

Above changes would apply to `server` and `skipper` component files, i.e.:
  - `spring-cloud-dataflow/templates/server/deployment.yaml` 
  - `spring-cloud-dataflow/templates/skipper/deployment.yaml`

### What alternatives have you considered?

The following workaround uses the `extraEnvVars` parameter to install `spring-cloud-dataflow` with Spring Cloud Config Server enabled, but has the following side-effects:
  1. Two env variables named `SPRING_CLOUD_CONFIG_ENABLED` will have been set on the Pods.
  2. The following warning will be shown during install:
    ```
    W0511 19:00:19.451874     401 warnings.go:70] spec.template.spec.containers[0].env[14].name: duplicate name "SPRING_CLOUD_CONFIG_ENABLED"
    ```

This workaround may not work with certain tools such as Helmfile, etc. which may handle the warning message in various ways.

1. Create values.yaml file with the following contents:
```yaml
 server:
   extraEnvVars:
     - name: SPRING_CLOUD_CONFIG_ENABLED
       value: true
 skipper:
   extraEnvVars:
     - name: SPRING_CLOUD_CONFIG_ENABLED
       value: true
 mariadb:
   enabled: false
 rabbitmq:
   enabled: false
```
2. Run the following command to install `spring-cloud-dataflow`:
```
helm install dataflow bitnami/spring-cloud-dataflow -f values.yaml
```
