### ISSUE TITLE
elasticsearch ingress tls problem

### ISSUE THREAD

**Issue by baturorkun** [bitnami/charts#16743]
### Name and Version

bitnami/elasticsearch:19.5.11

### What is the problem this feature will solve?

I want to create an ingress with TLS for Elasticsearch. I checked the values file and I could not find an existing secret variable. It is weird but it forces to me about adding certs to the values file. am I wrong?

### What is the feature you are proposing to solve the problem?

I have exiting secret file for cert.

**Comment by baturorkun** [comment]
hi @carrodher 
which parameter you are talking about?  I could not find a parameter for existing secret in ingress block

**Comment by carrodher** [comment]
Sorry, I was talking about `ingress.secrets` but this is for defining the secret:
```yaml
  ## @param ingress.secrets Custom TLS certificates as secrets
  ## NOTE: 'key' and 'certificate' are expected in PEM format
  ## NOTE: 'name' should line up with a 'secretName' set further up
  ## If it is not set and you're using cert-manager, this is unneeded, as it will create a secret for you with valid certificates
  ## If it is not set and you're NOT using cert-manager either, self-signed certificates will be created valid for 365 days
  ## It is also possible to create and manage the certificates outside of this helm chart
  ## Please see README.md for more information
  ## e.g:
  ## secrets:
  ##   - name: elasticsearch.local-tls
  ##     key: |-
  ##       -----BEGIN RSA PRIVATE KEY-----
  ##       ...
  ##       -----END RSA PRIVATE KEY-----
  ##     certificate: |-
  ##       -----BEGIN CERTIFICATE-----
  ##       ...
  ##       -----END CERTIFICATE-----
  ##
  secrets: []
```

It should be needed to implement the `ingress.existingSecret` one as
```
  security:
    ## @param security.tls.master.existingSecret Existing secret containing the certificates for the master nodes
    ## @param security.tls.data.existingSecret Existing secret containing the certificates for the data nodes
    ## @param security.tls.ingest.existingSecret Existing secret containing the certificates for the ingest nodes
    ## @param security.tls.coordinating.existingSecret Existing secret containing the certificates for the coordinating nodes
    ##
    master:
      existingSecret: ""
    data:
      existingSecret: ""
    ingest:
      existingSecret: ""
    coordinating:
      existingSecret: ""
```
Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by oksnfjan** [comment]
@baturorkun Looks like you can use the extraTls property to define your own TLS secret
``` yaml
extraTls:
    - hosts:
      - dummy.local
      secretName: keyvault-elasticsearch-dummy
```

Resulting Ingress yaml
``` yaml
spec:
  tls:
  - hosts:
    - dummy.local
    secretName: keyvault-elasticsearch-dummy
```
