### ISSUE TITLE
[bitnami/memcached] HorizontalPodAutoscaler api version incorrect on Kubernetes 1.26

### ISSUE THREAD

**Issue by Routhinator** [bitnami/charts#16749]
### Name and Version

bitnami/memcached 6.5.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy memcached 6.5.1 on Kubernetes 1.26

### Are you using any custom parameters or values?

```yaml
memcached:
  architecture: "high-availability"
  autoscaling:
    enabled: true
  persistence:
    enabled: true
    size: 10Gi
  metrics:
    enabled: true
  volumePermissions:
    enabled: true
```

### What is the expected behavior?

Chart deploys

### What do you see instead?

```
Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
```

### Additional information

Kubernetes 1.26 has moved from api version `autoscaling/v2beta1`  to api version `autoscaling/v2`

**Comment by javsalgar** [comment]
Hi,

We have the following function in the bitnami/common chart (which memcached uses)

```
{{/*
Return the appropriate apiVersion for Horizontal Pod Autoscaler.
*/}}
{{- define "common.capabilities.hpa.apiVersion" -}}
{{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .context) -}}
{{- if .beta2 -}}
{{- print "autoscaling/v2beta2" -}}
{{- else -}}
{{- print "autoscaling/v2beta1" -}}
{{- end -}}
{{- else -}}
{{- print "autoscaling/v2" -}}
{{- end -}}
{{- end -}}
```

In principle, it should render the correct API version.  How did you deploy/upgrade the chart?

**Comment by Routhinator** [comment]
Sorry for delays here. 

Deployment is as a child chart, pretty standard inclusions:

`Chart.yaml`

```yaml
dependencies:
  - name: memcached
    version: 6.5.1
    repository: https://charts.bitnami.com/bitnami
```

`values.yaml`
```yaml
memcached:
  architecture: "high-availability"
  autoscaling:
    enabled: true
  persistence:
    enabled: true
    size: 10Gi
  metrics:
    enabled: true
  volumePermissions:
    enabled: true
```

Nothing special here, however while this works fine on <=1.25 - on 1.26 it's not hiting the else for "autoscaling/v2" and is attempting to use `autoscaling/v2beta2`

```
Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
```


This is a very standard helm deploy:

```
        helm upgrade --install \
          --atomic \
          --timeout 900s \
          --namespace ${KUBE_NAMESPACE} \
          --set dovecot.image.tag=${CI_COMMIT_TAG} \
          --set postfix.image.tag=${CI_COMMIT_TAG} \
          --set rspamd.image.tag=${CI_COMMIT_TAG} \
          --set postfixadmin.image.tag=${CI_COMMIT_TAG} \
          --set roundcube.image.tag=${CI_COMMIT_TAG} \
          -f prod/values.yaml \
          routhio-mail-server mail-server/
```
