### ISSUE TITLE
[bitnami/wordpress] serviceTarget port is not able to be aligned with containerPort in ClusterIP service case

### ISSUE THREAD

**Issue by jmdots** [bitnami/charts#16751]
### Name and Version

     docker.io/bitnami/wordpress:6.2.1-debian-11-r1 

### What is the problem this feature will solve?

Without aligning targetPort to containerPort, ClusterIP cannot work.

I'm releasing the helm chart using terraform on GKE using GCP ingress. It should be possible to set service targetPort to 8080, 8443 to match containerPort when using ClusterIP type service. The reason people don't normally see an issue is the chart is biased toward NodePort, which is not my scenario. I'm on GKE with ingress, and NodePort isn't the way to go there to my knowledge. 

Configurable targetPort value by numerical port for both http and https.

Values:

```
allowEmptyPassword: false
allowOverrideNone: false

htaccessPersistenceEnabled: true

wordpressBlogName: "${var.wordpress_blog_name}"
wordpressScheme: "${var.wordpress_scheme}"
wordpressTablePrefix: "${var.wordpress_table_prefix}"

wordpressUsername: "${var.wordpress_username}"
wordpressPassword: "${var.wordpress_password}"

wordpressFirstName: "${var.wordpress_first_name}"
wordpressLastName: "${var.wordpress_last_name}"

service:
  type: ClusterIP

ingress:
  enabled: true
  hostname: "${var.wordpress_ingress_hostname}"
  pathType: Prefix
  tls: true
  tlsWwwPrefix: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "gce"
    bump: "0"
persistence:
  size: 100Gi
```

### What is the feature you are proposing to solve the problem?

Without aligning targetPort to containerPort, ClusterIP cannot work.

I'm releasing the helm chart using terraform on GKE using GCP ingress. It should be possible to set service targetPort to 8080, 8443 to match containerPort when using ClusterIP type service. The reason people don't normally see an issue is the chart is biased toward NodePort, which is not my scenario. I'm on GKE with ingress, and NodePort isn't the way to go there to my knowledge. 

Configurable targetPort value by numerical port for both http and https.

Values:

```
allowEmptyPassword: false
allowOverrideNone: false

htaccessPersistenceEnabled: true

wordpressBlogName: "${var.wordpress_blog_name}"
wordpressScheme: "${var.wordpress_scheme}"
wordpressTablePrefix: "${var.wordpress_table_prefix}"

wordpressUsername: "${var.wordpress_username}"
wordpressPassword: "${var.wordpress_password}"

wordpressFirstName: "${var.wordpress_first_name}"
wordpressLastName: "${var.wordpress_last_name}"

service:
  type: ClusterIP

ingress:
  enabled: true
  hostname: "${var.wordpress_ingress_hostname}"
  pathType: Prefix
  tls: true
  tlsWwwPrefix: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "gce"
    bump: "0"
persistence:
  size: 100Gi
```
