### ISSUE TITLE
add repmgr -> witness details in poregresql-HA chart

### ISSUE THREAD

**Issue by busyboy77** [bitnami/charts#16750]
### Name and Version

bitnami/postgresql-ha-11.7.1

### What is the problem this feature will solve?

in bitnami/postgresql-ha chart, the `witness` component has been added but there is there no much details provided. even the provided link is not relevant like below:

```YAML
witness:
  ## ref: https://hub.docker.com/r/bitnami/postgresql/tags/
  ## @param witness.create Create PostgreSQL witness nodes
  ##
  create: false
```

However, there is a proper link to the repmgr -> witness with a lot of details on it.

### What is the feature you are proposing to solve the problem?

Add the below given link into the documentation in the helm chart at line number `611` for postgresql-ha

https://repmgr.org/docs/4.3/repmgrd-witness-server.html

```
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
bitnami/postgresql-ha   11.7.1          15.3.0          This PostgreSQL cluster solution includes the P...

```
