### ISSUE TITLE
[bitnami/wordpress] chart: existingSecret value 

### ISSUE THREAD

**Issue by aliaksandrbychkoues** [bitnami/charts#16864]
### Name and Version

bitnami/wordpress 16.1.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When you define `externalDatabase.existingSecret` with the name of existing secret with mariadb-password wordpress can't log in with this password to the database
But If you define `externalDatabase.password` with the same password from your secret wordpress easily connect to your external db

### What is the expected behavior?

```
wordpress 16:11:14.77 INFO  ==> Configuring the HTTP port
wordpress 16:11:14.78 INFO  ==> Configuring the HTTPS port
wordpress 16:11:14.78 INFO  ==> Configuring Apache ServerTokens directive
wordpress 16:11:14.80 INFO  ==> Configuring PHP options
wordpress 16:11:14.80 INFO  ==> Setting PHP expose_php option
wordpress 16:11:14.81 INFO  ==> Setting PHP output_buffering option
wordpress 16:11:14.82 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
wordpress 16:11:14.95 INFO  ==> Ensuring WordPress directories exist
wordpress 16:11:14.96 INFO  ==> Trying to connect to the database server
wordpress 16:12:15.10 ERROR ==> Could not connect to the database
```

In database logs, I also see errors with authentication:

`19:15:39 1923 [Warning] Aborted connection 1923 to db: 'unconnected' user: 'unauthenticated' host: 'my-ip'`

### What do you see instead?

I can easily define `externalDatabase.password` and my WordPress will work without any problems
But I use GitOps with Argocd and don't want to commit my pass to the repo

### Additional information

My secret looks correct:

```yaml
apiVersion: v1
kind: Secret
metadata:
  annotations:
  name: wordpress-externaldb
  namespace: default
data:
  mariadb-password: my-password in base64
type: Opaque
```

My wordpress config:

```yaml
helm:
      values: |
        allowEmptyPassword: false
        mariadb:
          enabled: false
        externalDatabase:
          host: db-ip
          port: dbport
          user: username
          database: dbname
          existingSecret: wordpress-externaldb
        ingress:
          secrets: cert
        persistence:
          enabled: false
```
