### ISSUE TITLE
[bitnami/postgresql] Extra env vars are not being quoted

### ISSUE THREAD

**Issue by mrabe142** [bitnami/charts#16866]
### Name and Version

bitnami/postgres 12.5.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create a custom values file with a test primary.extraEnvVars set
2. Run '`helm template postres postgresql-12.5.2.tgz -n demo -f custom-values/postgres-values.yml > postgres1252.yml`
3. Inspect the yaml file for expected values

### Are you using any custom parameters or values?

Set a test env var in a custom values file:
```yaml
primary:
  extraEnvVars:
    - name: TEST_VAR
      value: "test"
```

### What is the expected behavior?

I expected this to be set in the env vars section of the postgres container:
```yaml
            - name: TEST_VAR
              value: "test"
```

### What do you see instead?

This is what was set, the value was not properly quoted anymore:
```yaml
            - name: TEST_VAR
              value: test
```

### Additional information

I noticed in the helm templates, it uses include `common.tplvalues.render` for the extra env vars. Looking at the common templates, there is also a `common.tplvalues.renderEnv` which seems more appropriate for this block in the template. Some guidance on the expected format for that template would be helpful too if it is changed.

**Comment by migruiz4** [comment]
Hi @mrabe142,

I'm sorry but we don't have any `common.tplvalues.renderEnv` function in our 'common' functions chart: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_tplvalues.tpl

The function `common.tplvalues.render` makes use of the Helm `tpl` function, appears to be removing the quotes when not strictly necessary to interpret the `extraEnvVars` yaml:

Example where value "test" is interpreted as a String, the quotes are removed:
```
primary:
  extraEnvVars:
    - name: TEST_VAR
      value: "test"
============= Rendered ===========
            - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
              value: "pgaudit"
            - name: TEST_VAR
              value: test
```
But, if you use 123, which would be interpreted as an Integer (causing Kubernetes to fail), the quotes remain:
```
primary:
  extraEnvVars:
    - name: TEST_VAR
      value: "123"
============= Rendered ===========
            - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
              value: "pgaudit"
            - name: TEST_VAR
              value: "123"
```

In any case, did you find any issues when installing the chart or using the templates because of this?

If you'd like the quotes to be rendered, you could use the following format:
```
primary:
  extraEnvVars: |-
    - name: TEST_VAR
      value: "test"
============= Rendered ===========
            - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
              value: "pgaudit"
            - name: TEST_VAR
              value: "test"
```
