### ISSUE TITLE
Enabling resources definition in values.yml breaks templating

### ISSUE THREAD

**Issue by ddvogt** [bitnami/charts#1686]
**Which chart**:

airflow/latest

**Description**

Enabling resources in `values.yml` breaks the templating

**Steps to reproduce the issue:**

1. Uncomment the resources setting in `values.yml`, i.e.: 
```
resources:
  limits:
    cpu: 200m
    memory: 1Gi
  requests:
    memory: 256Mi
    cpu: 250m
```
2. Run `helm template -f values.yaml .`

**Describe the results you received:**

A YAML parse error is presented:
`Error: YAML parse error on airflow/templates/statefulset-worker.yaml: error converting YAML to JSON: yaml: line 35: mapping values are not allowed in this context`

**Describe the results you expected:**

The expectation is that the generated jsons/yamls feature resource definitions as presented in the values file. Instead, a parsing error is presented. 

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue happens on the latest master commit.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by alemorcuq** [comment]
Hi, @ddvogt.

I'm not able to reproduce your issue. I modify the `values.yaml` to use the `resources` parameter:

```diff
diff --git a/bitnami/airflow/values.yaml b/bitnami/airflow/values.yaml
index 92a16b4f..9f560bd4 100644
--- a/bitnami/airflow/values.yaml
+++ b/bitnami/airflow/values.yaml
@@ -271,12 +271,12 @@ affinity: {}
 ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
 ##
 resources:
-#  limits:
-#    cpu: 200m
-#    memory: 1Gi
-#  requests:
-#    memory: 256Mi
-#    cpu: 250m
+  limits:
+    cpu: 200m
+    memory: 1Gi
+  requests:
+    memory: 256Mi
+    cpu: 250m
```

And then run `helm template -f values.yaml .`:

```
❯ helm3 template -f values.yaml .
---
# Source: airflow/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
```

Can you diff the `values.yaml`?

Regards,
Alejandro

**Comment by ddvogt** [comment]
The diff looks the same as yours:
```
diff --git a/bitnami/airflow/values.yaml b/bitnami/airflow/values.yaml
index 92a16b4f..9f560bd4 100644
--- a/bitnami/airflow/values.yaml
+++ b/bitnami/airflow/values.yaml
@@ -271,12 +271,12 @@ affinity: {}
 ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
 ##
 resources:
-#  limits:
-#    cpu: 200m
-#    memory: 1Gi
-#  requests:
-#    memory: 256Mi
-#    cpu: 250m
+  limits:
+    cpu: 200m
+    memory: 1Gi
+  requests:
+    memory: 256Mi
+    cpu: 250m

 ## Configure extra options for liveness and readiness probes
 ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
```

Yet, the generated json cannot be applied to the cluster:
```
secret/dev-postgresql created
secret/dev-redis created
secret/dev-airflow created
configmap/dev-redis created
configmap/dev-redis-health created
configmap/dev-airflow-dag-files created
service/dev-postgresql-headless created
service/dev-postgresql created
service/dev-redis-headless created
service/dev-redis-master created
service/dev-redis-slave created
service/dev-airflow-headless created
service/dev-airflow created
statefulset.apps/dev-postgresql created
statefulset.apps/dev-redis-master created
statefulset.apps/dev-redis-slave created
Error from server (Invalid): error when creating "STDIN": Deployment.apps "dev-airflow-scheduler" is invalid: spec.template.spec.containers[0].resources.requests: Invalid value: "250m": must be less than or equal to cpu limit
Error from server (Invalid): error when creating "STDIN": Deployment.apps "dev-airflow-web" is invalid: spec.template.spec.containers[0].resources.requests: Invalid value: "250m": must be less than or equal to cpu limit
error validating "STDIN": error validating data: [ValidationError(StatefulSet.spec.template.spec.containers[0]): unknown field "requests" in io.k8s.api.core.v1.Container, ValidationError(StatefulSet.spec.template.spec.containers[0].resources): unknown field "cpu" in io.k8s.api.core.v1.ResourceRequirements, ValidationError(StatefulSet.spec.template.spec.containers[0].resources): unknown field "memory" in io.k8s.api.core.v1.ResourceRequirements]; if you choose to ignore these errors, turn validation off with --validate=false
```

I believe the reason is the indentation in the generated configs.
When I run the template, output to files and view the statefulset, then the indentation of the resource definition is indeed wrong:
```
---
# Source: airflow/templates/statefulset-worker.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dev-airflow-worker
  labels:
    app.kubernetes.io/name: airflow
    helm.sh/chart: airflow-4.0.16
    app.kubernetes.io/instance: dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: worker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: airflow
      app.kubernetes.io/instance: dev
      app.kubernetes.io/component: worker
  serviceName: dev-airflow-headless
  replicas: 1
  updateStrategy:
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: airflow
        app.kubernetes.io/instance: dev
        app.kubernetes.io/component: worker
    spec:      
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      containers:
        - name: airflow-worker
          image: "docker.io/bitnami/airflow-worker:1.10.6-debian-9-r1"
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
          env:
            - name: AIRFLOW_DATABASE_NAME
              value: bitnami_airflow
            - name: AIRFLOW_DATABASE_USERNAME
              value: bn_airflow
            - name: AIRFLOW_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-postgresql
                  key: postgresql-password
            - name: AIRFLOW_DATABASE_HOST
              value: dev-postgresql
            - name: AIRFLOW_DATABASE_PORT_NUMBER
              value: "5432"
            - name: REDIS_HOST
              value: dev-redis-master
            - name: REDIS_PORT_NUMBER
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-redis
                  key: redis-password
            - name: AIRFLOW_EXECUTOR
              value: "CeleryExecutor"
            - name: AIRFLOW_FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: dev-airflow
                  key: airflow-fernetKey
            - name: AIRFLOW_WEBSERVER_HOST
              value: dev-airflow
          ports:
            - name: worker
              containerPort: 8793
          livenessProbe:
            tcpSocket:
              port: worker
            initialDelaySeconds: 180
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: worker
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - name: local-dag-files
              mountPath: /opt/bitnami/airflow/dags/local
      volumes:
      - name: local-dag-files
        configMap:
          name: dev-airflow-dag-files
```
