### ISSUE TITLE
[bitnami/grafana-loki] Add `extraArgs` to the helm chart

### ISSUE THREAD

**Issue by sarahhenkens** [bitnami/charts#16890]
### Name and Version

bitnami/grafana-loki

### What is the problem this feature will solve?

When using environment variable expansion in the configuration file of Loki, you must enable it first via the "-config.expand-env=true" CLI argument. Documentation: https://grafana.com/docs/loki/latest/configuration/#use-environment-variables-in-the-configuration

Currently, the helm chart hard-codes the container args for all components of Loki making it impossible to add this CLI argument without overwriting all of them.

### What is the feature you are proposing to solve the problem?

I suggest we add an `extraArgs` option for each component to allow us to add additional args to the container:

```yaml
  compactor:
    extraEnvVarsSecret: loki-minio-credentials

    extraArgs:
      - -config.expand-env
```

### What alternatives have you considered?

Manually overwriting all the args requires me to also overwrite the essential default args that are needed for configuration:

```yaml
  compactor:
    extraEnvVarsSecret: loki-minio-credentials

    args:
      # Copied from the deployment, there is corrently no way to add additional args
      - -target=compactor
      - -config.file=/bitnami/grafana-loki/conf/loki.yaml
      - -boltdb.shipper.compactor.working-directory=/bitnami/grafana-loki/loki/compactor

      # The rest
      - -config.expand-env
```
