### ISSUE TITLE
[bitnami/redis] Failed to connect replica when disabling external redis/sentinel access.

### ISSUE THREAD

**Issue by AlehYarmalovich** [bitnami/charts#16946]
### Name and Version

bitnami/redis 17.11.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install helm chart with exposing redis/sentinel outside the cluster and then disable external access.

For a correct migration from external access to internal access, for some time I can’t delete external services with the NodePort type, so that the already recreated internal replica can connect to it, but at the same time, inside the startup scripts in the get_port function, the port is being installed from ENV variable (example: REDIS_MASTER_NODE_0_SERVICE_PORT_REDIS=30311) because external service exist.

### Are you using any custom parameters or values?

Enable external access:
```yaml
architecture: replication
useHostnames: false
sentinel:
  enabled: true
  quorum: 2
  masterSet: master
  downAfterMilliseconds: 2000
  failoverTimeout: 1000
  service:
    type: NodePort
    nodePorts:
      redis: 30310
      sentinel: 30420
useExternalDNS:
  enabled: true
  suffix: example.com
  additionalAnnotations:
    dns-type: external-dns
    endpoints-type: HostIP
```

Disable external access:
```yaml
architecture: replication
useHostnames: false
sentinel:
  enabled: true
  quorum: 2
  masterSet: master
  downAfterMilliseconds: 2000
  failoverTimeout: 1000
```

### What is the expected behavior?

After disable external access
Logs:
```
1:S 26 May 2023 19:11:13.754 * MASTER <-> REPLICA sync started
1:S 26 May 2023 19:11:13.756 # Error condition on socket for SYNC: Connection refused
1:S 26 May 2023 19:11:14.127 * Connecting to MASTER xxx.xxx.xxx.xxx:30311
```

Conf file:
```
dir /data
# User-supplied replica configuration:
rename-command FLUSHDB ""
rename-command FLUSHALL ""
# End of replica configuration
replica-announce-port 30311 <externalPort>
replica-announce-ip xxx.xxx.xxx.xxx <nternalIP>
```

### What do you see instead?

**instead of:**
```yaml
get_port() {
    hostname="$1"
    type="$2"

    port_var=$(echo "${hostname^^}_SERVICE_PORT_$type" | sed "s/-/_/g")
    port=${!port_var}

    if [[ -z "$port" ]]; then
        case $type in
            "SENTINEL")
                echo {{ .Values.sentinel.containerPorts.sentinel }}
                ;;
            "REDIS")
                echo {{ .Values.master.containerPorts.redis }}
                ;;
        esac
    else
        echo $port
    fi
}
```

**use:**
```yaml
get_port() {
    hostname="$1"
    type="$2"

    port_var=$(echo "${hostname^^}_SERVICE_PORT_$type" | sed "s/-/_/g")
    port=${!port_var}

    if [[ -z "$port" ]] || [[ {{ .Values.sentinel.service.type | quote }} == "ClusterIP" ]]
    then
        case $type in
            "SENTINEL")
                echo {{ .Values.sentinel.containerPorts.sentinel }}
                ;;
            "REDIS")
                echo {{ .Values.master.containerPorts.redis }}
                ;;
        esac
    else
        echo $port
    fi
}
```

I'll do a PR
