### ISSUE TITLE
[bitnami/airlfow] KubernetesExecutor: MountVolume.SetUp failed for volume "kube-api-access-lw6n6"

### ISSUE THREAD

**Issue by alekseyolg** [bitnami/charts#16965]
### Name and Version

bitnami/airflow:14.2.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

version images - 2.6.1-debian-11-r3
Kubernetes as a Service - Sbercloud
kubectl version --short
  Client Version: v1.23.3
  Server Version: v1.23.3-r0-CCE22.5.1

### Are you using any custom parameters or values?

set into values.yaml:
```yaml
executor: KubernetesExecutor
serviceAccount:
  create: true
  name: "airflow"
rbac:
  create: true
  rules:
    - apiGroups:
        - '*'
      resources:
        - '*'
      verbs:
        - '*'
serviceAccount:
  create: false
rbac:
  create: true
git:
  dags:
    enabled: true
ldap:
  enabled: true
redis:
  enabled: false
```
### What is the expected behavior?

Correct operation of the pod

### What do you see instead?
```
event:
MountVolume.SetUp failed for volume "kube-api-access-lw6n6" : object "airflow"/"kube-root-ca.crt" not registered
```
