### ISSUE TITLE
schema-registry helm chart requires .Values.kafka.auth.clientProtocol when kakfa.enabled: false

### ISSUE THREAD

**Issue by ssontaclaus** [bitnami/charts#16963]
### Name and Version

bitnamicharts/schema-registry

### What architecture are you using?

None

### What steps will reproduce the bug?

1. `helm upgrade --install schema-registr-test oci://registry-1.docker.io/bitnamicharts/schema-registry -f values.yaml -n test`

### Are you using any custom parameters or values?

```yaml
# values.yaml
kafka:
  enabled: false
externalKafka:
  brokers:
    - PLAINTEXT://my.kafka.domain:9092
    auth:
      protocol: plaintext
```

### What is the expected behavior?

I think it should require a `.Values.externalKafka.auth.protocol` value.
https://github.com/bitnami/charts/blob/main/bitnami/schema-registry/templates/statefulset.yaml#L4

### What do you see instead?
```
Error: UPGRADE FAILED: template: schema-registry/templates/statefulset.yaml:4:95: executing "schema-registry/templates/statefulset.yaml" at <.Values.kafka.auth.clientProtocol>: nil pointer evaluating interface {}.clientProtocol
```
