### ISSUE TITLE
[bitnami/thanos] service.additionalHeadless can't be excluded from servicemonitor

### ISSUE THREAD

**Issue by dragoangel** [bitnami/charts#16967]
### Name and Version

bitnami/charts - any

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Deploy any chart with `.Values.SomePackage.service.additionalHeadless` and `.Values.SomePackage.serviceMonitor.enabled`
2. Check Prometheus Targets, if try adjust relebel or other options in serviceMonitor it doesn't help

### What is the expected behavior?

If a service is deployed with an additional service only one of the services will match serviceMonitor selectors 

### What do you see instead?

Prometheus collect metrics 2 times same metrics for each service

**Comment by dragoangel** [comment]
Need to use something like:
1. ServiceMonitor:
```
  selector:
    matchExpressions:
      - key: prometheus.io/service-monitor
        operator: NotIn
        values:
          - "false"
```
2. additionalHeadless service:
```
  labels:
    prometheus.io/service-monitor: "false"
```

**Comment by dragoangel** [comment]
For now in Thanos I added:
```
    metricRelabelings:
      - action: drop
        regex: ^thanos-.+-headless$
        sourceLabels: [job]
```

But this is not a solution as Prometheus still scrapes metrics
