### ISSUE TITLE
Kafka - How to enable multi-broker with SASL_SSL?

### ISSUE THREAD

**Issue by joshho** [bitnami/charts#1699]
**Which chart**:

Latest

**Description**

How do we encrypt the inter-broker communication via SSL?
According to the README, we're to create a keystore for each broker with an alias of `localhost`. 
Originally I tried creating a single keystore with `CN=` the value of the `<helmName>-kafka` (service), but I ran into 
```
Failed authentication with \
<helmName>-kafka-<brokerNumber>.<helmName>-kafka-headless.<namespace>.svc.cluster.local/10.130.0.189 SSL handshake failed
```

My thought process is that in order to create a keystore for EACH broker, each broker must mount in a separate keystore. Since the broker is scaled via statefulset.yaml how do we pass in each individual keystore for each broker?

**Steps to reproduce the issue:**

1. Create a kafka.keystore.jks and kafka.truststore.jks with password `somevalue` insert it into `kafka-keystores` Secret.
2. Create the `bitnami-zk-kafka-authsecret` secret with the appropriate passwords for the various usernames.
3. Helm install with:
```
allowPlaintextListener: true
auth:
    brokerUser: kafka-broker-user
    enabled: true
    existingSecret: bitnami-zk-kafka-authsecret
    interBrokerUser: kafka-interbroker-user
    zookeeperUser: zkuser
    certificatesSecret: kafka-keystores
    certificatesPassword: somevalue
    defaultReplicationFactor: 3
    externalZookeeper:
    servers: bitnami-zookeeper
listenerSecurityProtocolMap: SASL_SSL:SASL_SSL
listeners: SASL_SSL://:9092
advertisedListeners: SASL_SSL://:9092
```

**Describe the results you received:**

```
Failed authentication with \
<helmName>-kafka-<brokerNumber>.<helmName>-kafka-headless.<namespace>.svc.cluster.local/10.130.0.189 SSL handshake failed
```

**Describe the results you expected:**

Kafka brokers are able to communicate through SSL.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z",GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
```
