### ISSUE TITLE
[bitnami/kafka] default logRetentionHours is set wrong

### ISSUE THREAD

**Issue by yavorivanov-cw** [bitnami/charts#16996]
### Name and Version

bitnami/kafka 19.1.4

### What architecture are you using?

None

### What steps will reproduce the bug?

1. k8s cluster

### Are you using any custom parameters or values?

```
kafka:
  auth:
    clientProtocol: sasl
    externalClientProtocol: sasl
    interBrokerProtocol: plaintext
    controllerProtocol: plaintext
    sasl:
      mechanisms: plain
      # interBrokerMechanism: sasl
      jaas:
        clientUsers:
          - user
        existingSecret: kafka-client-secret

  externalAccess:
    enabled: true
    service:
      type: ClusterIP
      domain: ***

  readinessProbe:
    initialDelaySeconds: 5
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 20
    tcpSocket:
      port: kafka-client

  livenessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 10

  podSecurityContext:
    fsGroup: 1000
  containerSecurityContext:
    runAsUser: 1000

  zookeeper:
    podSecurityContext:
      fsGroup: 1000
    containerSecurityContext:
    runAsUser: 1000

  persistence:
    size: 16Gi

  resources:
    requests:
      memory: 512Mi

  # log files per topic are rotated at 1Gi and old files deleted after 1 h
  logRetentionHours: 1

  global:
    storageClass: ceph-filesystem # use managed-csi for AKS
```

### What is the expected behavior?

log.retention.hours = 168

### What do you see instead?

log.retention.hours = 1

### Additional information

Adding `logRetentionHours` to the values.yaml does not change anything.
