### ISSUE TITLE
[bitnami/supabase] targetPort is defined multiple times in chart version 0.3.6 - failed to install through fluxCD

### ISSUE THREAD

**Issue by jsmueller7** [bitnami/charts#16997]
### Name and Version

bitnami/supabase 0.3.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install the chart 0.3.6 using fluxCD
2. Retreive these error logs:

```
Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 25: mapping key "targetPort" already defined at line 22 Last Helm logs: CRD kongconsumers.configuration.konghq.com is already present. Skipping. CRD kongingresses.configuration.konghq.com is already present. Skipping. CRD kongplugins.configuration.konghq.com is already present. Skipping. CRD tcpingresses.configuration.konghq.com is already present. Skipping. CRD udpingresses.configuration.konghq.com is already present. Skipping.

reconciliation failed: Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 25: mapping key "targetPort" already defined at line 22
```
### Are you using any custom parameters or values?

The installation runs through when you install it directly with `helm install my-supabase bitnami/supabase --version 0.3.6 -n <namespace> -f custom-values.yml`

### What is the expected behavior?

The installation of the chart version 0.3.5 runs through with fluxCD. 0.3.6 fails. I'd expect 0.3.6 to work as well. 

### What do you see instead?

Nothing, besides the mentioned error.

### Additional information

This might be helpful to debug: https://github.com/fluxcd/helm-controller/issues/283#issuecomment-1277624223

The error message indicates that `targetPort` has been defined more than once.

**Comment by fevisera** [comment]
Hi @jsmueller7, sorry for the delay.

Can you give more details about the content of custom-values.yml? 
Is the issue present in the latest version of bitnami/supabase?

Thanks.

**Comment by jsmueller7** [comment]
Hi @fevisera,
my customizations are as described earlier [here](https://github.com/bitnami/charts/issues/16706#issue-1713311775). The problem still persists with chart version `0.3.8`; the break occured with the update from `0.3.5` to `0.3.6`. The main problem is: The chart can't be installed anymore through a CI pipeline. Flux2 is our tool of choice. These errors still occur - while a installation through `helm install` with the exact same configurations runs through:

> Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 25: mapping key "targetPort" already defined at line 22 Last Helm logs: CRD kongconsumers.configuration.konghq.com is already present. Skipping. CRD kongingresses.configuration.konghq.com is already present. Skipping. CRD kongplugins.configuration.konghq.com is already present. Skipping. CRD tcpingresses.configuration.konghq.com is already present. Skipping. CRD udpingresses.configuration.konghq.com is already present. Skipping.

and

> reconciliation failed: Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 25: mapping key "targetPort" already defined at line 22

Im my opinion here https://github.com/fluxcd/helm-controller/issues/283 a similar issue is described. What I can do locally is to run `helm template test .` with the different chart versions. The problem seems to be with the services for

* auth
* meta
* realtime
* rest
* storage
*studio

When you take a look at the output for auth you'll see that `targetPort` has been defined twice (line 21 and 24). The line numbers don't exactly match those in my error message, but the differnce in the line count does exacly match - plus: This second definition of `targetPort` does neither make sence to me, nor is it presece in the output of `helm template test` for chart version `0.3.5`.

```
---
# Source: supabase/templates/auth/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-supabase-auth
  namespace: "default"
  labels:
    app.kubernetes.io/name: supabase
    helm.sh/chart: supabase-0.3.8
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: supabase
    app.kubernetes.io/component: auth
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      nodePort: null
      targetPort: 9999
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: test
    app.kubernetes.io/component: auth
```
