### ISSUE TITLE
[influxdb] The value relay.replicaCount is ingored

### ISSUE THREAD

**Issue by carlosmkb** [bitnami/charts#1700]
The value `relay.replicaCount` is ignored because the related value in templates is not an Helm object:

_bitnami/influxdb/templates/relay/deployment.yaml_
```
{{- if eq .Values.architecture "high-availability" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "influxdb.fullname" . }}-relay
  labels: {{- include "influxdb.labels" . | nindent 4 }}
    app.kubernetes.io/component: relay
spec:
  replicas: 1  <-----------
...
```
