### ISSUE TITLE
[bitnami/redis] Use `tpl` to parse `existingSecretPasswordKey` in Redis

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [bitnami/charts#17016]
### Name and Version

bitnami/redis:17.11.3

### What is the problem this feature will solve?

In my `values.yaml` I want to be able to set the `existingSecretPasswordKey` as a templatable value. For eg. I wan the following yaml to work:
```yaml
...
redis:
  auth:
    existingSecret: '{{ include "chart.fullname" . | trimSuffix "-redis" }}'
    existingSecretPasswordKey: '{{ include "chart.fullname" . }}-pass'
```
> Note
I am using `redis` as a subchart.

### What is the feature you are proposing to solve the problem?

I want the `existingSecretPasswordKey` to be templatable like the `existingSecret` is. Relevant codebase https://github.com/bitnami/charts/blob/52454ca4f01eadd8d073054258ea0bc619584edf/bitnami/redis/templates/_helpers.tpl#L192-L211
