### ISSUE TITLE
[bitnami/rabbitmq] Not_Authorized when using existingClaim

### ISSUE THREAD

**Issue by default-doe** [bitnami/charts#17022]
### Name and Version

bitnami/rabbitmq 11.15.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`$ helm upgrade --install rabbitmq bitnami/rabbitmq --version 11.15.5 --namespace rabbitmq-qa --set persistence.enabled=true --set persistence.existingClaim=$MY_EXISTING_CLAIM --set auth.username=csmqadmin --set auth.password=test1234`

### What is the expected behavior?

I should authenticate with the custom credentials passed as values.

### What do you see instead?

Getting invalid credentials when using the `existingClaim`.
`2023-06-05 10:11:07.035675+00:00 [warning] <0.1133.0> HTTP access denied: user 'csmqadmin' - invalid credentials`

### Additional information

I have double checked that `$RABBITMQ_PASSWORD` is the one as expected.

**Comment by Mauraza** [comment]
Hi @default-doe,

Could you add more information about the persistence are you using? Where are you deploying the chart?

**Comment by default-doe** [comment]
Hola @Mauraza,

These are the PV & PVC that I'm manually creating.

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: application-pv-development-rabbitmq
  annotations:
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10G
  csi:
    driver: cephfs.manila.csi.openstack.org
    volumeHandle: volume-development-rabbitmq
    nodeStageSecretRef:
      name:  os-trustee
      namespace: kube-system
    nodePublishSecretRef:
      name:  os-trustee
      namespace: kube-system
    volumeAttributes:
      shareID: $MY_SHARE_ID
      shareAccessID: $MY_SHARE_ACCESS_ID
```

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: application-pvc-rabbitmq
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
  storageClassName: ""
```

The chart is being deployed in a K8s cluster with version v1.25.3, deployed in the OpenStack cloud.
