### ISSUE TITLE
[redis] How can we add Redis modules to our bitnami image

### ISSUE THREAD

**Issue by xtianus79** [bitnami/charts#17036]
### Name and Version

bitnami/redis 

### What is the problem this feature will solve?

Using other open source capabilities from Redis

### What is the feature you are proposing to solve the problem?

For kubernetes installation how can we add modules to the bitnami image?

### What alternatives have you considered?

I've asked this question in another thread that was closed. 

https://github.com/bitnami/charts/issues/12572

**Comment by carrodher** [comment]
Thanks for reporting this issue. At this moment it is not something supported nor in the roadmap for the short term. Unfortunately, we are a small team with limited capacity to handle all the requests for the different apps in the catalog.

Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by carrodher** [comment]
Yes, Helm charts are totally customizable in terms of images. You can use your own image by configuring the following section in the values.yaml:
```yaml
## Bitnami Redis&reg; image
## ref: https://hub.docker.com/r/bitnami/redis/tags/
## @param image.registry Redis&reg; image registry
## @param image.repository Redis&reg; image repository
## @param image.tag Redis&reg; image tag (immutable tags are recommended)
## @param image.digest Redis&reg; image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag
## @param image.pullPolicy Redis&reg; image pull policy
## @param image.pullSecrets Redis&reg; image pull secrets
##
image:
  registry: docker.io
  repository: bitnami/redis
  tag: 7.0.11-debian-11-r12
  digest: ""
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  ##
  pullSecrets: []
```

**Comment by stssathishr** [comment]
can i get the loadmodule command please

**Comment by bamaas** [comment]
I tried this 
`  configmap: |
    loadmodule /redismodules/redistimeseries.so`

But getting:
`Module /redismodules/redistimeseries.so failed to load: libssl.so.3: cannot open shared object file: No such file or directory`

Im 100% sure the module is present, I checked the content of /redismodules/.

**Comment by dilipk8** [comment]
I get this error:

### Module /redismodules/libredisgears_v8_plugin.so failed to load: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /redismodules/libredisgears_v8_plugin.so)
Can't load module from /redismodules/libredisgears_v8_plugin.so: server aborting

I have an EKS cluster.
I'm neither able to upgrade or install any package from within the pod directly ( no apt,apt-get,sudo, wget etc.)

**Comment by bamaas** [comment]
In the end I've easily fixed it by building the module during image build time and thus baking the module into the image itself. Then override the default image and set the load module command in the values file.

Dockerfile:
`# https://github.com/bitnami/containers/blob/main/bitnami/redis-cluster/7.2/debian-11/Dockerfile
FROM bitnami/redis-cluster:7.2.3-debian-11-r1

USER root

RUN mkdir /redismodules

WORKDIR /redismodules

# https://github.com/RedisTimeSeries/RedisTimeSeries
RUN apt-get update -y && \
    apt-get install -y git make && \
    git clone --recursive https://github.com/RedisTimeSeries/RedisTimeSeries.git ./RedisTimeSeries && \
    cd RedisTimeSeries && \
    ./sbin/setup && \
    bash -l && \
    make && \
    mv ./bin/linux-x64-release/redistimeseries.so /redismodules/redistimeseries.so && \
    cd /redismodules/ && \
    rm -rf /redismodules/RedisTimeSeries

USER 1001
`

values.yaml
`image:
  repository: mymodifiedimage
  tag: mytag

redis:
  configmap: |
    loadmodule /redismodules/redistimeseries.so`

**Comment by krebznet** [comment]
@bamaas - thank you, i think this will help me getting a cluster setup using the redis-cluster helm chart, based on what you describe it sounds like creating a custom docker image that will clone, build and put int the redistmodules directory and then in your values.yaml update the image with the customized one and add a line to the config map to load the time series module, this might actually work!

**Comment by xtianus79** [comment]
@bamaas did you use this as your still your core image? 

```
FROM docker.io/bitnami/minideb:bookworm

ARG TARGETARCH
```

**Comment by xtianus79** [comment]
@bamaas I got it. doing a new post.

**Comment by xtianus79** [comment]
Thanks @bamaas  and @jnissan1 I finally did it. I will post a code update on the other blog.

**Comment by tonywangcn** [comment]
Thanks @bamaas  and @jnissan1 here is the working code for redis chart (not redis cluster)

```
image:
  repository: redis/redis-stack-server
  tag: 7.2.0-v10
commonConfiguration: |-
  loadmodule /redismodules/redisbloom.so
master:
  extraVolumes:
    - name: redismodules
      emptyDir: {}
  extraVolumeMounts:
    - name: redismodules
      mountPath: /redismodules/
  initContainers:
    - name: redis-module-preload
      image: redis/redis-stack:latest
      command: ['/bin/sh', '-c', 'cp /opt/redis-stack/lib/* /redismodules/']
      volumeMounts:
        - name: redismodules
          mountPath: /redismodules/

replica:
  extraVolumes:
    - name: redismodules
      emptyDir: {}
  extraVolumeMounts:
    - name: redismodules
      mountPath: /redismodules/
  initContainers:
    - name: redis-module-preload
      image: redis/redis-stack:latest
      command: ['/bin/sh', '-c', 'cp /opt/redis-stack/lib/* /redismodules/']
      volumeMounts:
        - name: redismodules
          mountPath: /redismodules/
```
