### ISSUE TITLE
[bitnami/redis-cluster] `User requested shutdown` master nodes restarts

### ISSUE THREAD

**Issue by staboss** [bitnami/charts#17040]
### Name and Version

bitnami/redis-cluster 8.6.2

### What architecture are you using?

None

### What steps will reproduce the bug?

We deploy a `redis-cluster` in a separate `ns` and run each pod on one instance.

Instance config is `t4g.small` with `2CPU` / `2Gb`.

The `K8s` cluster is managed by `AWS`.

The `K8s` cluster version is `1.24`.

### Are you using any custom parameters or values?

Helm Chart configuration:

```yaml
cluster:
  nodes: 6
  replicas: 1

image:
  repository: bitnami/redis-cluster
  tag: 7.0.11-debian-11-r12

persistence:
  enabled: true
  size: 20Gi

redis:
  nodeSelector:
    kube/nodetype: redis-cluster

  tolerations:
    - key: dedicated
      operator: Equal
      value: redis-cluster
      effect: NoSchedule

  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi

usePassword: true
```

***

Terraform code snippet to deploy:

```hcl
resource "helm_release" "redis_cluster" {
  count            = var.redis_cluster_enabled ? 1 : 0
  chart            = "redis-cluster"
  create_namespace = true
  name             = "redis-cluster"
  namespace        = "redis-cluster"
  repository       = "https://charts.bitnami.com/bitnami"
  version          = "8.6.2"

  values = [
    file("./templates/redis-cluster/values-${var.environment}.yaml")
  ]

  set {
    name  = "clusterDomain"
    value = "redis-cluster.${var.domain}"
  }

  set_sensitive {
    name  = "password"
    value = data.vault_generic_secret.redis_cluster_credentials[0].data["password"]
  }
}
```

### What is the expected behavior?

Pods are not restarted.

### What do you see instead?

After some random time, some of the Pods restarted with the following log output:

```bash
1:M 06 Jun 2023 10:53:57.935 # Server initialized
1:M 06 Jun 2023 10:53:57.937 * Reading RDB base file on AOF loading...
1:M 06 Jun 2023 10:53:57.937 * Loading RDB produced by version 7.0.11
1:M 06 Jun 2023 10:53:57.937 * RDB age 439533 seconds
1:M 06 Jun 2023 10:53:57.937 * RDB memory usage when created 1.62 Mb
1:M 06 Jun 2023 10:53:57.937 * RDB is base AOF
1:M 06 Jun 2023 10:53:57.937 * Done loading RDB, keys loaded: 3, keys expired: 0.
1:M 06 Jun 2023 10:53:57.937 * DB loaded from base file appendonly.aof.121.base.rdb: 0.000 seconds
```

or similar log.

Moreover, we did not notice any patterns in the restarts, so for us these are completely random restarts.

***

We also noticed that only master nodes are restarted, and when a master node becomes non-master, it stops restarting until it becomes master again.

### Additional information

Tried on both architectures (AMD / ARM), the result is the same.
