### ISSUE TITLE
Plugin ldap-server not working

### ISSUE THREAD

**Issue by mathiasrettich** [bitnami/charts#17050]
### Name and Version

bitnami/moodle:4.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create the /srv/docker/moodle directory on a Linux machine with the latest docker-version.
2. In /srv/docker/moodle create the file docker-compose.yml with the content from [here](https://github.com/bitnami/containers/blob/main/bitnami/moodle/docker-compose.yml).
3.  In the /srv/docker/moodle directory, issue the docker compose up -d command.
4. Try to connect with the ldap-server plugin to an ldap-server (in my case: ldaps://10.16.1.1).
 I get: Object of class LDAP/Connection could not be converted to string

### Are you using any custom parameters or values?

Here is a snippet of my docker-compose.yml file.:
```yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.io/bitnami/moodle:4.2
    restart: always
...
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './moodle_data:/bitnami/moodle'
      - './moodledata_data:/bitnami/moodledata'
 ...
```
### What is the expected behavior?

Moodle should connect to the server (10.16.1.1)

### What do you see instead?

The error: Object of class LDAP/Connection could not be converted to string

### Additional information

The ldap-connection works with Apache-Directory-Studio and nextcloud.
