### ISSUE TITLE
[bitnami/postgresql] primary.initdb.scripts not getting executed

### ISSUE THREAD

**Issue by agapebondservant** [bitnami/charts#17063]
### Name and Version

bitnami/postgresql 12.5.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Run `helm install pg5 -f postgres-ml-values.yaml -n postgresml oci://registry-1.docker.io/bitnamicharts/postgresql`
2. Run `kubectl run pg5-postgresql-client --rm --tty -i --restart='Never' --namespace postgresml --image docker.io/bitnami/postgresql:15.3.0-debian-11-r7 --env="PGPASSWORD=docker" --command -- psql --host pg5-postgresql -U docker -d postgresml -p 5432`
3. Hit Enter
4. Run `create extension pgml`

### Are you using any custom parameters or values?
```yaml
### postgres-ml-values.yaml
global:
  postgresql:
    nameOverride: postgresml
    storageClass: generic
    auth:
      postgresPassword: "docker"
      username: "docker"
      password: "docker"
      database: "postgresml"

image:
  debug: true

primary:
  extraVolumes:
    - name: postgres-seed
      persistentVolumeClaim:
        claimName: postgres-seed-pvc

  extraVolumeMounts:
    - mountPath: /docker-entrypoint-initdb.d
      name: postgres-seed

  service:
    type: LoadBalancer

  initdb:
    user: "docker"
    password: "docker"
    scripts:
      00_init_extensions.sh: |-
        #/bin/bash
        echo 'here'
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -y
        apt-get install -y --no-install-recommends software-properties-common gpg-agent lsb-core
        echo "deb [trusted=yes] https://apt.postgresml.org $(lsb_release -cs) main" >> /etc/apt/sources.list
        add-apt-repository ppa:deadsnakes/ppa
        apt-get install -y --no-install-recommends python3.10 python3-pip g++ gcc git default-libmysqlclient-dev curl lsb-release tzdata sudo make cmake libpq-dev libclang-dev wget git postgresql-pgml-14
        apt-get clean
        rm -rf /var/lib/apt/lists/*
```
### What is the expected behavior?

The extension should be created successfully.

### What do you see instead?
```
ERROR:  extension "pgml" is not available
DETAIL:  Could not open extension control file "/opt/bitnami/postgresql/share/extension/pgml.control": No such file or directory.
HINT:  The extension must first be installed on the system where PostgreSQL is running.
```
### Additional information
```
### debug logs
postgresql 12:06:46.26 
postgresql 12:06:46.26 Welcome to the Bitnami postgresql container
postgresql 12:06:46.26 Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 12:06:46.26 Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql 12:06:46.27 
postgresql 12:06:46.27 DEBUG ==> Configuring libnss_wrapper...
postgresql 12:06:46.28 INFO  ==> ** Starting PostgreSQL setup **
postgresql 12:06:46.31 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 12:06:46.32 INFO  ==> Loading custom pre-init scripts...
postgresql 12:06:46.33 INFO  ==> Initializing PostgreSQL database...
postgresql 12:06:46.33 DEBUG ==> Ensuring expected directories/files exist...
postgresql 12:06:46.36 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 12:06:46.36 INFO  ==> Generating local authentication configuration
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /bitnami/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
initdb: warning: enabling "trust" authentication for local connections
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
syncing data to disk ... ok


Success. You can now start the database server using:

    /opt/bitnami/postgresql/bin/pg_ctl -D /bitnami/postgresql/data -l logfile start

postgresql 12:06:47.23 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2023-06-07 12:06:47.283 GMT [69] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-06-07 12:06:47.284 GMT [69] LOG:  listening on IPv6 address "::1", port 5432
2023-06-07 12:06:47.284 GMT [69] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-06-07 12:06:47.289 GMT [69] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-06-07 12:06:47.296 GMT [72] LOG:  database system was shut down at 2023-06-07 12:06:47 GMT
2023-06-07 12:06:47.303 GMT [69] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE
postgresql 12:06:47.43 INFO  ==> Changing password of postgres
ALTER ROLE
postgresql 12:06:47.46 INFO  ==> Creating user docker
CREATE ROLE
postgresql 12:06:47.49 INFO  ==> Granting access to "docker" to the database "postgresml"
GRANT
ALTER DATABASE
postgresql 12:06:47.52 INFO  ==> Setting ownership for the 'public' schema database "postgresml" to "docker"
ALTER SCHEMA
postgresql 12:06:47.56 INFO  ==> Configuring replication parameters
postgresql 12:06:47.59 INFO  ==> Configuring synchronous_replication
postgresql 12:06:47.60 INFO  ==> Configuring fsync
postgresql 12:06:47.65 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down....2023-06-07 12:06:47.658 GMT [69] LOG:  received fast shutdown request
2023-06-07 12:06:47.661 GMT [69] LOG:  aborting any active transactions
2023-06-07 12:06:47.663 GMT [69] LOG:  background worker "logical replication launcher" (PID 75) exited with exit code 1
2023-06-07 12:06:47.664 GMT [70] LOG:  shutting down
2023-06-07 12:06:47.667 GMT [70] LOG:  checkpoint starting: shutdown immediate
2023-06-07 12:06:47.729 GMT [70] LOG:  checkpoint complete: wrote 927 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.048 s, sync=0.006 s, total=0.065 s; sync files=257, longest=0.003 s, average=0.001 s; distance=4222 kB, estimate=4222 kB
2023-06-07 12:06:47.735 GMT [69] LOG:  database system is shut down
 done
server stopped
postgresql 12:06:47.76 INFO  ==> Loading custom scripts...
postgresql 12:06:47.77 INFO  ==> Enabling remote connections
postgresql 12:06:47.78 INFO  ==> ** PostgreSQL setup finished! **

postgresql 12:06:47.80 INFO  ==> ** Starting PostgreSQL **
2023-06-07 12:06:47.818 GMT [1] LOG:  pgaudit extension initialized
2023-06-07 12:06:47.830 GMT [1] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-06-07 12:06:47.831 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-06-07 12:06:47.831 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2023-06-07 12:06:47.836 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-06-07 12:06:47.842 GMT [156] LOG:  database system was shut down at 2023-06-07 12:06:47 GMT
2023-06-07 12:06:47.849 GMT [1] LOG:  database system is ready to accept connections
```
