### ISSUE TITLE
[bitnami/kafka 22.1.3] Custom server.properties is mounted incorrectly in Kraft mode

### ISSUE THREAD

**Issue by ThomasRutger** [bitnami/charts#17062]
### Name and Version

bitnami/kafka 22.1.3

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Deploy chart in Kraft mode
2. Use custom config, using the `config` key.
3. Custom config is mounted in `/opt/bitnami/kafka/config/server.properties` instead of `/opt/bitnami/kafka/config/kraft/server.properties`.

### Are you using any custom parameters or values?

```yaml
config: |-
  # Custom config here

image:
  debug: false

serviceAccount:
  create: true
rbac:
  create: true
externalAccess:
  autoDiscovery:
    enabled: true
  enabled: true
  service:
    type: LoadBalancer
```

### What is the expected behavior?

config mounted at `/opt/bitnami/kafka/config/kraft/server.properties`

### What do you see instead?

Custom config is mounted in `/opt/bitnami/kafka/config/server.properties`
