### ISSUE TITLE
POSTGRESQL_PGAUDIT_LOG="READ,WRITE" in bitnami/postgresql:12.9.0 seems to have no effect.

### ISSUE THREAD

**Issue by kopax-polyconseil** [bitnami/charts#17094]
### Name and Version

bitnami/postgresql:12.9.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```yml
version: '2'

services:
  postgresql:
    image: bitnami/postgresql:12.9.0
    ports:
      - '5434:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=testabc
      - POSTGRESQL_DATABASE=testabc
      - POSTGRESQL_PGAUDIT_LOG="READ,WRITE"
volumes:
  postgresql_data:
    driver: local
```

### What is the expected behavior?

I expect to have something when running `pgaudit.log`

### What do you see instead?

```bash
I have no name!@e104dd9f5fb8:/$ psql -U postgres
Password for user postgres: 
psql (12.9)
Type "help" for help.

postgres=# show pgaudit.log;
 pgaudit.log 
-------------
 none
(1 row)

postgres=# select 1+1;
 ?column? 
----------
        2
(1 row)

postgres=# show pgaudit.log;
 pgaudit.log 
-------------
 none
(1 row)

postgres=# show pgaudit.log;
 pgaudit.log 
-------------
 none
(1 row)

postgres=# show pgaudit.log;
 pgaudit.log 
-------------
 none
(1 row)

postgres=# ALTER SYSTEM SET pgaudit.log TO 'read, write';
ALTER SYSTEM
postgres=# show pgaudit.log;
 pgaudit.log 
-------------
 none
(1 row)

```

### Additional information

pgAudit doesn't seems to be working, I tried to edit a few things in our db, no results at all
