### ISSUE TITLE
Unable to mount volume on Tasks

### ISSUE THREAD

**Issue by ardesai** [bitnami/charts#17117]
### Name and Version

bitnami/spring-cloud-dataflow 15.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install this chart and mount a PVC to the SCDF server at `/tmp/mount/in/` and I have copied a file at this location.
2. When I try to execute a task, it creates a new a new Pod for this Task execution however this file is not available on the Task pod and it fails with a FileNotFound error.
3. I am expecting this file this mount to be available on the Server and Task Pods as this truststore file is needed to connect to a remote Database for TLS.

### Are you using any custom parameters or values?

Install this chart with below configuration for server
```yaml
server:
  containerRegistries:
    default:
       registry-host: artifactory.platform.dat.ns1s.corp.hmrc.gov.uk/hmrc-dps-ems-docker-virtual/
  image:
    registry: artifactory.platform.dat.ns1s.corp.hmrc.gov.uk
    repository: registry-1-docker-docker/bitnami/spring-cloud-dataflow
  resources:
    limits:
      cpu: 1000m
      memory: 5Gi
      ephemeral-storage: 10Gi
  requests:
    cpu: 1000m
    memory: 5Gi
    ephemeral-storage: 10Gi
  configuration:
    batchEnabled: true
    streaming:
      enabled: true
  extraVolumes:
    - name: scdf-volume
      persistentVolumeClaim:
        claimName: scdf-pvc
  extraVolumeMounts:
    - name: scdf-volume
      mountPath: /tmp/mount/in/

deployer:
  volumes:
    name: scdf-volume
    persistentVolumeClaim:
      claimName: scdf-pvc
  volumeMounts:
    name: scdf-volume
    mountPath: /tmp/mount/in/

```

### What is the expected behavior?

Mount available on Task pods.

### What do you see instead?

Task pod fails with mount not available.

### Additional information

How can I make this file available on all the Task pods (including ComposedTask and individual Task)?
