### ISSUE TITLE
[bitnami/schema-registry] nil pointer evaluating interface {}.clientProtocol

### ISSUE THREAD

**Issue by Hongbo-Miao** [bitnami/charts#17126]
### Name and Version

bitnami/schema-registry 7.4.0

### What architecture are you using?

None

### What steps will reproduce the bug?

I have a Kafka created by Strimzi at `hm-kafka-kafka-bootstrap.hm-kafka.svc:9092`.

I am trying to install Confluent Schema Registry using Bitnami helm at https://github.com/bitnami/charts/tree/main/bitnami/schema-registry

Here are my steps:

```shell
helm upgrade \
  confluent-schema-registry \
  oci://registry-1.docker.io/bitnamicharts/schema-registry \
  --install \
  --namespace=hm-confluent-schema-registry \
  --create-namespace \
  --values=my-values.yaml
```

**my-values.yaml**:

```yaml
kafka:
  enabled: false
externalKafka:
  brokers:
    - PLAINTEXT://hm-kafka-kafka-bootstrap.hm-kafka.svc:9092
```

### What is the expected behavior?

I expect it has no error when install by helm chart.

### What do you see instead?

It gives me error

```shell
Error: template: schema-registry/templates/statefulset.yaml:4:95: executing "schema-registry/templates/statefulset.yaml" at <.Values.kafka.auth.clientProtocol>: nil pointer evaluating interface {}.clientProtocol
```

### Additional information

Originally posted at https://stackoverflow.com/questions/76157961/how-to-install-confluent-schema-registry-using-bitnami-helm-chart-for-external-k

Here is my workaround solution

```yaml
kafka:
  enabled: false
  auth:
    protocol: {}
  service:
    ports:
      client: {}
externalKafka:
  brokers:
    - PLAINTEXT://hm-kafka-kafka-bootstrap.hm-kafka.svc:9092
```

Currently, helm install expects these two parameters which do not exist in [schema-registry/values.yaml](https://github.com/bitnami/charts/blob/c693dd78f26da6c495a9566c6a5b49ba15c6587c/bitnami/schema-registry/values.yaml) and also not expected to:

```yaml
kafka:
  auth:
    protocol: {}
  service:
    ports:
      client: {}
```

It would be great to fix, thanks! 😃
