### ISSUE TITLE
[bitnami/mariadb-galera] update mariadb-galera from 7.5.5 to 8.2.5

### ISSUE THREAD

**Issue by tasches** [bitnami/charts#17139]
### Name and Version

bitnami/mariadb-galera 8.25

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am using the galera chart in the version 7.5.5 and tried upgrading to 8.25. The chart gets updated as expected but there are some changes which are not applied automaticaly. After the Container Image update from 10.6.12 to 10.11.4 there are errors in the log similar to the following
```
ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
```
I have to run mariadb_upgrade manualy. It was not mentioned in the docs of the chart. Did I make mistake during the update or is it intended to upgrade the schema myself?

You can reproduce the bug if you create a release with 7.5.5 and upgrade to 8.2.5

### Are you using any custom parameters or values?
```yaml
replicaCount: 3
rootUser:
  forcePassword: true
  password: <>
db:
  forcePassword: true
  password: <>
galera:
  mariabackup:
    forcePassword: true
    password: <>
priorityClassName: normal
podAntiAffinityPreset: hard
extraEnvVars:
  - name: MARIADB_EXTRA_FLAGS
    value: --skip-log-bin
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  resources:
    requests:
      memory: 32Mi
      cpu: 10m
    limits:
      memory: 64Mi
      cpu: 250m
persistence:
  enabled: true
  storageClass: rbd
  size: 8Gi
resources:
  requests:
    memory: 1Gi
  limits:
    memory: 4Gi
    cpu: 2
podSecurityContext:
  enabled: true
containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  runAsNonRoot: true
serviceAccount:
  create: false
rbac:
  create: false
```
### What is the expected behavior?

mariadb_upgrade run automaticly in the upgrade from version 10.6 to 10.11 like its done in the [libmariadbgalera.sh](https://github.com/bitnami/containers/blob/75c314b8e8f80f173ea7ddaf89fb3a453211fa52/bitnami/mariadb-galera/10.11/debian-11/rootfs/opt/bitnami/scripts/libmariadbgalera.sh#L1138) under different circumstances.

or it should be mentioned in the documentation of the chart

### What do you see instead?

Errors in the log after the upgrade

![Screenshot_183](https://github.com/bitnami/charts/assets/12058592/c2f2b223-67e7-4223-bea1-c698ea6ce663)

### Additional information

I haven't seen an issue like this before, so maybe its my mistake or it does not belong here because the issues is related to the container instead.
