### ISSUE TITLE
[bitnami/kube-prometheus] Upgrade from 8.9.1 to 8.13.1 broken

### ISSUE THREAD

**Issue by Balsir** [bitnami/charts#17143]
### Name and Version

bitnami/kube-prometheus 8.13.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am deploying kube-prometheus via ArgoCD (version 2.6.7) with server side apply.

When upgrading from 8.9.1 to 8.13.1, the sync fails with these errors:

```
error calculating structured merge diff: error building typed value from config resource: .spec.scrapeConfigSelector: field not declared in schema

error calculating structured merge diff: error building typed value from config resource: .spec.scrapeConfigNamespaceSelector: field not declared in schema
```

Tearing down 8.9.1 and installing 8.13.1 from scratch succeeds without any issues.

### Are you using any custom parameters or values?

My values:
````yaml
alertmanager:
  enabled: false
blackboxExporter:
  enabled: false
commonLabels:
  monitoring/scope: system
coreDns:
  service:
    labels:
      jobLabel: coredns
  serviceMonitor:
    jobLabel: jobLabel
exporters:
  kube-state-metrics:
    enabled: true
  node-exporter:
    enabled: true
kube-state-metrics:
  commonLabels:
    monitoring/scope: system
  extraArgs:
    metric-labels-allowlist: nodes=[*],daemonsets=[*],deployments=[*],pods=[*],cronjobs=[*],jobs=[*],ingresses=[*],persistentvolumeclaims=[*],persistentvolumes=[*]
  selfMonitor:
    enabled: true
  service:
    labels:
      jobLabel: kube-state-metrics
  serviceMonitor:
    jobLabel: jobLabel
kubeControllerManager:
  enabled: false
kubeProxy:
  service:
    labels:
      jobLabel: kube-proxy
  serviceMonitor:
    jobLabel: jobLabel
kubeScheduler:
  enabled: false
kubelet:
  serviceMonitor:
    relabelings:
    - action: replace
      sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
node-exporter:
  commonLabels:
    monitoring/scope: system
  podAnnotations:
    cluster-autoscaler.kubernetes.io/enable-ds-eviction: "false"
  priorityClassName: system-cluster-critical
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  serviceMonitor:
    relabelings:
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance_name
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 15%
    type: RollingUpdate
prometheus:
  disableCompaction: true
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: default
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    enabled: true
    hostname: prometheus.domain.com
    ingressClassName: nginx-internal
    path: /
    tls: true
  persistence:
    enabled: true
    size: 100Gi
    storageClass: ebs-csi-gp3
  priorityClassName: system-cluster-critical
  replicaCount: 2
  retention: 4h
  service:
    labels:
      jobLabel: prometheus-k8s
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::123456780912:role/role-arn
    create: true
    name: prometheus
  serviceMonitor:
    jobLabel: jobLabel
rbac:
  create: true
````

### What is the expected behavior?

Seamless upgrade of kube-prometheus from 8.9.1 to 8.13.1 or higher.

### What do you see instead?

```
error calculating structured merge diff: error building typed value from config resource: .spec.scrapeConfigSelector: field not declared in schema

error calculating structured merge diff: error building typed value from config resource: .spec.scrapeConfigNamespaceSelector: field not declared in schema
```

### Additional information

Error appears when upgrading from 8.10.2 to 8.12.1. Probably caused by these changes:
https://github.com/bitnami/charts/pull/16736
https://github.com/bitnami/charts/pull/16895
