### ISSUE TITLE
[bitnami/keycloak] Can't import themes because initContainer doesn't work

### ISSUE THREAD

**Issue by oburd** [bitnami/charts#17183]
### Name and Version

bitnami/keycloak:21.1.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Hello!
I have tried to do next:

```yaml
initContainers:
  - name: keycloak-theme-provider
    image: AWS.dkr.ecr.REGION.amazonaws.com/ecr-name:latest
    imagePullSecrets: ecrcred
    imagePullPolicy: Always
    command: 
      - sh
    args:
      - -c
      - |
        echo "Copying theme..."
        cp -R /my-theme/* /customize-themes
    volumeMounts:
      - name: customize-themes
        mountPath: /customize-themes

extraVolumeMounts:
  - name: customize-themes
    mountPath: /opt/bitnami/keycloak/themes/customize-themes

extraVolumes:
  - name: customize-themes
    emptyDir: {}
```

### What do you see instead?

when I came to logs in initcontainer
I see the next error:
```
exec /bin/sh: exec format error
```
