### ISSUE TITLE
[bitnami/rabbitmq] livenessProbe failure after adding curl option in version 11.15.7

### ISSUE THREAD

**Issue by kbakk23** [bitnami/charts#17199]
### Name and Version

bitnami/rabbitmq:11.15.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Update to rabbitmq chart to 11.15.7 or later version using helm
2. Helm update is applied and started creating the new pod
3. Rabbitmq pod will start but it fails the livenessProbe and will not be ready to accept connections

### Are you using any custom parameters or values?

```yaml
livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  timeoutSeconds: 20
  periodSeconds: 30
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 20
  periodSeconds: 30
  failureThreshold: 3
  successThreshold: 1

startupProbe:
  enabled: false
  initialDelaySeconds: 10
  timeoutSeconds: 20
  periodSeconds: 30
  failureThreshold: 3
  successThreshold: 1

customLivenessProbe: {}

customReadinessProbe: {}

customStartupProbe: {}

initContainers: []

sidecars: []
```
### What is the expected behavior?

rabbitmq pod will be running and ready

### What do you see instead?

Rabbitmq pod is running but not ready.
```console
$ k get po 
NAME         READY   STATUS    RESTARTS        AGE
rabbitmq-0   0/1     Running   1 (4m54s ago)   10m

  Normal   Started    8m19s                   kubelet            Started container rabbitmq
  Warning  Unhealthy  3m20s (x14 over 7m50s)  kubelet            Readiness probe failed:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (1) Received HTTP/0.9 when not allowed
  Warning  Unhealthy  3m20s (x6 over 5m50s)  kubelet  Liveness probe failed:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (1) Received HTTP/0.9 when not allowed
  Normal  Killing  3m20s                  kubelet  Container rabbitmq failed liveness probe, will be restarted
```

### Additional information

The liveness probe has not been changed. On version 11.15.7, curl was added in the liveness part and it is causing this problem. 
[https://github.com/bitnami/charts/commit/94da8bb6df32884071ecb298bee5a3b58ec8fd47](https://github.com/bitnami/charts/commit/94da8bb6df32884071ecb298bee5a3b58ec8fd47)

I tried to add --http0.9 manually to the curl in livenessprobe and it works. The pod becomes ready.
The new curl command will be:
``` 
 curl -f --user {{ .Values.auth.username }}:$RABBITMQ_PASSWORD  --http0.9 127.0.0.1:{{ .Values.containerPorts.manager }}/api/health/checks/virtual-hosts
```
