### ISSUE TITLE
[binami/elasticsearch] Allow topology with master and master eligible nodes at the same time

### ISSUE THREAD

**Issue by fabio-s-franco** [bitnami/charts#17285]
### Name and Version

binami/elasticsearch 19.10.2

### What is the problem this feature will solve?

Having a more constrained resource setup requires a bit more flexibility on the roles nodes can assume in an ELK cluster.
master configuration allows only all in, or all out when it comes to master nodes.

Either all of them are dedicated master nodes or all master eligible ("master.masterOnly" setting.).
A more sensible option would be to get rid of the boolean completely and just have:
`master.dedicatedReplicaCount` and `master.eligibleReplicaCount`. 

This would give a lot of freedom already to some unorthodox setups. Then `master.extraRoles` would be applicable only to nodes deployed as master eligible.

Similarly to data nodes, the same applies. I wish I could have 2 dedicated data nodes and 1 master eligible data node for availability and be the 3rd node necessary for the consensus algorithm. This would allow me not to over-provision 3 master nodes which would be overkill for me, but I still prefer to have dedicated nodes so that resource utilization is more efficient.

A master eligible data node alongside two dedicated data noes would give that third leg for both master and data nodes, which in my view for my current setup, would be ideal and at this moment, it doesn't seem to be possible with this helm chart.

### What is the feature you are proposing to solve the problem?

I would love to PR this one, but I have way too little knowledge of the whole stack and the chart to do something like this at a sensible time. I wish I had more time to put on this, which would make use of the following parameters to achieve this feature set:
```
 master.dedicatedReplicaCount
 master.eligibleReplicaCount
 master.extraRoles
 
 data.dedicatedReplicaCount
data.masterEligibleReplicaCount
data.masterEligibleExtraRoles (in addition to the inferred master and data roles)
```
### What alternatives have you considered?

Not a lot of choice here other than making all data nodes master eligible, which to me is a bit of a risk of having a suboptimal resource allocation and load distribution.

**Comment by migruiz4** [comment]
Hi @fabio-s-franco,

There is a big problem with your proposed feature, which is that ALL the nodes of the same kind ('master', 'data', 'ingest', 'coordinating') share the same Statefulset file with the same inputs.

This means that the only difference between `master-0`, `master-1` and `master-2` is the replica number and the PVC attached to each node.

With a single statefulset, it is not possible to configure the deployment of a replica with different roles, which is what I understand from your proposal: `master-0`, `master-1`, `master-2 (master+data)`, `data-0`, `data-1` OR `master-0`, `master-1`, `data-0 (master+data)`, `data-1`, `data-2`.

As I mentioned, all the replicas from a statefulset will always be, as its name implies, exact copies from another.

For your use case, I would like to propose two solutions:

- My personal recommendation, if you would like to deploy a small cluster and optimise resources, it is not necessary to configure a cluster with dedicated nodes at all. A 3 multi-role nodes cluster should be the most optimal: 
  ```yaml
  master:
    replicaCount: 3
    masterOnly: false
  data:
    replicaCount: 0
  ingest:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ```
  From that point, you can grow your cluster naturally over-time depending on your requirements: 
    - Add dedicated data nodes for more storage.
    - Deploy dedicated coordinating-only nodes to perform the gathering stage if your detect intensive read operations. 
    - Once your cluster grows significantly enough for your cluster metadata to be big enough (many nodes with many shards distributed on them), disable allocation on masters and set them as dedicated master nodes.

- My other suggestion would be a solution for your use case using the current features available in the chart. Using the values `extraDeploy`, you could deploy an additional stateful set of your own called 'master-data', which fulfilled that requirements you describe.
  ```yaml
    master:
      replicaCount: 3
      masterOnly: false
  data:
    replicaCount: 0
  extraDeploy:
    - |
      kind: Statefulset
      name: {{ printf "%s-master-data" (include "common.names.fullname" .)}}
      ...
    - |
       kind: Service
       name: {{ printf "%s-master-data" (include "common.names.fullname" .)}}
       ...
  ```
  This will bootstrap your cluster with 2 master nodes, but then your third master-data node will join the cluster and start working normally as master-eligible node.
  The value `extraDeploy` is rendered as a template, so you can access values from the `values.yaml` and call helper functions.

I hope this helps you with your use case.
