### ISSUE TITLE
Spark - 3.3.2 - Volume for worker

### ISSUE THREAD

**Issue by ognjen-it** [bitnami/charts#17283]
### Name and Version

bitnami/spark:3.3.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Short explanation:
We cannot mount PVC to workers since there is not volumeClaimTemplates in worker statefulset.
So here is a test with extra volumes:

First case:
1. Create values file:
```yaml
worker:
  extraVolumes:
    - name: spark-data
      persistentVolumeClaim:
        claimName: spark-data
  extraVolumeMounts:
    - name: spark-data
      mountPath: '/opt/bitnami/spark/work'
```
2. Install with helm:
`helm -n spark upgrade --install spark-cluster bitnami/spark --version 6.6.3 -f values.yaml`

Error: spark-data PVC doesn't exist

Second case:
1. Create PVC
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-data
  namespace: spark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: managed-csi
  volumeMode: Filesystem
```
2. Create values file:
```yaml
worker:
  extraVolumes:
    - name: spark-data
      persistentVolumeClaim:
        claimName: spark-data
  extraVolumeMounts:
    - name: spark-data
      mountPath: '/opt/bitnami/spark/work'
```
3. Install with helm:
`helm -n spark upgrade --install spark-cluster bitnami/spark --version 6.6.3 -f values.yaml`

First worker will start successfully but the second will fail because of multi-attach error.

### Are you using any custom parameters or values?

```yaml
worker:
  extraVolumes:
    - name: spark-data
      persistentVolumeClaim:
        claimName: spark-data
  extraVolumeMounts:
    - name: spark-data
      mountPath: '/opt/bitnami/spark/work'
```

### What is the expected behavior?

I want to have running 2 workers and each one should have its own volume.

### What do you see instead?

We can set the configuration for worker to have volumeClaimTemplates in statefullset.

### Additional information

With the current helm, we cannot create spark cluster with volumes.
The main problem is if we are using HDD for k8s nodes, we cannot mount SSD to spark workers.
