### ISSUE TITLE
Cassandra could not start when TLS enabled

### ISSUE THREAD

**Issue by mingtwan** [bitnami/charts#1729]
**Which chart**:

bitnami/cassandra version: 4.1.11 appVersion: 3.11.5

**Description**

Cassandra could not start when TLS enabled

**Steps to reproduce the issue:**

1. create keystore and truststore
2. use keystore and truststore to create secret 
3. helm install 

logs of cassandra pod:
 ```
Setting node as password seeder
cassandra 15:12:19.39
cassandra 15:12:19.39 Welcome to the Bitnami cassandra container
cassandra 15:12:19.39 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-cassandra
cassandra 15:12:19.40 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-cassandra/issues
cassandra 15:12:19.40 Send us your feedback at containers@bitnami.com
cassandra 15:12:19.40
cassandra 15:12:19.40 INFO  ==> ** Starting Cassandra setup **
cassandra 15:12:19.43 INFO  ==> Validating settings in CASSANDRA_* env vars..
cassandra 15:12:19.53 WARN  ==> Hostname tls-cassandra-1.tls-cassandra-headless.test-cassandra.svc.cluster.local could not be resolved. This could lead to connection issues
cassandra 15:12:19.55 WARN  ==> Hostname tls-cassandra-1.tls-cassandra-headless.test-cassandra.svc.cluster.local could not be resolved. This could lead to connection issues
cassandra 15:12:19.56 INFO  ==> Initializing Cassandra database...
cassandra 15:12:19.58 DEBUG ==> No injected jvm.options file found. Creating default jvm.options file
cassandra 15:12:19.59 DEBUG ==> No injected hotspot_compiler file found. Creating default hotspot_compiler file
cassandra 15:12:19.60 DEBUG ==> No injected cqlshrc.sample file found. Creating default cqlshrc.sample file
cassandra 15:12:19.61 DEBUG ==> No injected commitlog_archiving.properties file found. Creating default commitlog_archiving.properties file
cassandra 15:12:19.62 DEBUG ==> No injected metrics-reporter-config-sample.yaml file found. Creating default metrics-reporter-config-sample.yaml file
cassandra 15:12:19.64 DEBUG ==> No injected cassandra.yaml file found. Creating default cassandra.yaml file
cassandra 15:12:19.65 DEBUG ==> No injected triggers/README.txt file found. Creating default triggers/README.txt file
cassandra 15:12:19.66 DEBUG ==> No injected README.txt file found. Creating default README.txt file
cassandra 15:12:19.68 DEBUG ==> No injected cassandra-jaas.config file found. Creating default cassandra-jaas.config file
cassandra 15:12:19.69 DEBUG ==> No injected logback-tools.xml file found. Creating default logback-tools.xml file
cassandra 15:12:19.71 DEBUG ==> No injected cassandra-topology.properties file found. Creating default cassandra-topology.properties file
cassandra 15:12:19.73 DEBUG ==> No injected logback.xml file found. Creating default logback.xml file
cassandra 15:12:19.74 DEBUG ==> No injected cassandra-env.sh file found. Creating default cassandra-env.sh file
cassandra 15:12:19.75 DEBUG ==> No injected cassandra-rackdc.properties file found. Creating default cassandra-rackdc.properties file
cassandra 15:12:19.76 DEBUG ==> No injected cassandra-env.ps1 file found. Creating default cassandra-env.ps1 file
cassandra 15:12:19.96 DEBUG ==> Ensuring expected directories/files exist...
cassandra 15:12:19.97 INFO  ==> Deploying Cassandra from scratch
cassandra 15:12:19.98 INFO  ==> Starting Cassandra
cassandra 15:12:19.98 INFO  ==> Checking that it started up correctly
cassandra 15:12:19.99 DEBUG ==> Checking that log /opt/bitnami/cassandra/logs/cassandra_first_boot.log contains entry "Starting listening for CQL clients"
INFO  [main] 2019-12-11 15:12:38,305 Server.java:159 - Starting listening for CQL clients on /0.0.0.0:9042 (encrypted)...
cassandra 15:12:40.07 INFO  ==> Found CQL startup log line
cassandra 15:12:40.08 DEBUG ==> Checking status with nodetool
UN  172.21.242.152  103.69 KiB  256          100.0%            f05ec7c7-ecd4-46b1-a427-a532d2fc3cf0  rack1
cassandra 15:12:41.76 INFO  ==> Nodetool reported the successful startup of Cassandra
cassandra 15:12:41.76 INFO  ==> Password seeder node
cassandra 15:12:41.76 INFO  ==> Trying to access CQL server @ tls-cassandra-0.tls-cassandra-headless.test-cassandra.svc.cluster.local
cassandra 15:12:41.77 DEBUG ==> Executing CQL "DESCRIBE KEYSPACES"
Connection error: ('Unable to connect to any servers', {'172.21.242.152': ConnectionShutdown('Connection to 172.21.242.152 was closed',)})
cassandra 15:12:52.30 DEBUG ==> Executing CQL "DESCRIBE KEYSPACES"
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

my values.yaml:
```
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName
#   storageClass: myStorageClass

## Bitnami Cassandra image version
## ref: https://hub.docker.com/r/bitnami/cassandra/tags/
##
image:
  registry: docker.io
  repository: bitnami/cassandra
  ## Bitnami Cassandra image tag
  ## ref: https://github.com/bitnami/bitnami-docker-cassandra#supported-tags-and-respective-dockerfile-links
  ##
  tag: 3.11.5-debian-9-r21
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName
  ## Set to true if you would like to see extra information on logs
  ## It turns BASH debugging in minideb-extras-base
  ##
  debug: true

## String to partially override cassandra.fullname template (will maintain the release name)
##
# nameOverride:

## String to fully override cassandra.fullname template
##
# fullnameOverride:

## Init containers parameters:
## volumePermissions: Change the owner and group of the persistent volume mountpoint to runAsUser:fsGroup values from the securityContext section.
##
volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/minideb
    tag: stretch
    pullPolicy: Always
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName
  ## Init container' resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits: {}
    #   cpu: 100m
    #   memory: 128Mi
    requests: {}
    #   cpu: 100m
    #   memory: 128Mi

## Service parameters
##
service:
  ## Service type
  ##
  type: ClusterIP
  ## CQL port
  ##
  port: 9042
  ## Thrift Client API port
  ##
  thriftPort: 9160
  ## Specify the nodePort(s) value(s) for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  nodePorts:
    cql: ""
    thriftPort: ""
  ## Set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  # loadBalancerIP:
  ## Provide any additional annotations which may be required. This can be used to
  ## set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  annotations: {}

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  ## If true, use a Persistent Volume Claim, If false, use emptyDir
  ##
  enabled: true
  ## Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: "managedssd-rwcache"
  ## Persistent Volume Claim annotations
  ##
  #annotations:
  ## Persistent Volume Access Mode
  ##
  accessModes:
    - ReadWriteOnce
  ## Persistent Volume size
  ##
  size: 256Gi

## Cassandra pods' resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
## Minimum memory for development is 4GB and 2 CPU cores
## Minimum memory for production is 8GB and 4 CPU cores
## ref: http://docs.datastax.com/en/archived/cassandra/2.0/cassandra/architecture/architecturePlanningHardware_c.html
##
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits: {}
  #   cpu: 2
  #   memory: 4Gi
  requests: {}
  #   cpu: 2
  #   memory: 4Gi

## Secret with keystore, keystore password, truststore, truststore password
##
tlsEncryptionSecretName: cassandra-tls
## ConfigMap with custom cassandra configuration files. This overrides any other Cassandra configuration set in the chart
##
# existingConfiguration:

## Cluster parameters
##
cluster:
  name: cassandra
  replicaCount: 3
  seedCount: 2
  numTokens: 256
  datacenter: dc1
  rack: rack1
  enableRPC: true
  endpointSnitch: SimpleSnitch
  minimumAvailable: 2
  ## Encryption values. NOTE: They require tlsEncryptionSecretName
  ##
  internodeEncryption: all
  clientEncryption: true
  domain: cluster.local

## JVM Settings
##
jvm:
  ## Extra JVM options
  ##
  extraOpts:

  ## Memory settings: These are calculated automatically
  ## unless specified otherwise
  ##
  maxHeapSize: 4G
  newHeapSize: 800M

## Database credentials
##
dbUser:
  user: cassandra
  forcePassword: false
  # password:
  # existingSecret:

## ConfigMap with cql scripts. Useful for creating a keyspace
## and pre-populating data
##
# initDBConfigMap:

## Cassandra container's liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
##
livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
readinessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

## Additional pod annotations
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

## Additional pod labels
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
podLabels: {}

## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Node labels for pod assignment. Evaluated as a template.
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## StatefulSet settings
##
statefulset:
  updateStrategy: OnDelete
  # rollingUpdatePartition:

## Pod Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001

## Container entrypoint and cmd (useful for using different images)
##
entrypoint: "/entrypoint.sh"
cmd: "/run.sh"

## Network policies
## Ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/
##
networkPolicy:
  ## Specifies whether a NetworkPolicy should be created
  ##
  enabled: true

  ## The Policy model to apply. When set to false, only pods with the correct
  ## client label will have network access to the port Redis is listening
  ## on. When true, Redis will accept connections from any source
  ## (with the correct destination port).
  ##
  allowExternal: true

## Cassandra Prometheus exporter configuration
## ref: https://hub.docker.com/r/bitnami/cassandra-exporter/tags/
##
metrics:
  enabled: false
  image:
    registry: docker.io
    pullPolicy: IfNotPresent
    repository: bitnami/cassandra-exporter
    tag: 2.3.0-debian-9-r102
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName
  ## Cassandra Prometheus exporter resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits: {}
    #   cpu: 100m
    #   memory: 128Mi
    requests: {}
    #   cpu: 100m
    #   memory: 128Mi
  ## Metrics exporter pod Annotation and Labels
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
```

the secret content:
```
apiVersion: v1
data:
  keystore: /u3+7QAAAAIAAAACAAAAAgAGY2Fyb290AAABbvViyOsABVguNTA5AAADZzCCA2MwggJLoAMCAQICFCitEmnEk5SgVhGweY5t8yDJ3odkMA0GCSqGSIb3DQEBCwUAMEExCzAJBgNVBAYTAk5OMQswCQYDVQQIDAJOTjELMAkGA1UEBwwCTk4xCzAJBgNVBAoMAk5OMQswCQYDVQQLDAJOTjAeFw0xOTEyMTExNDM1MjBaFw00NzA0MjgxNDM1MjBaMEExCzAJBgNVBAYTAk5OMQswCQYDVQQIDAJOTjELMAkGA1UEBwwCTk4xCzAJBgNVBAoMAk5OMQswCQYDVQQLDAJOTjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAO3hzFAUTe34RI0NC+dj17YONYk7rz+8ObKPaRgrKbW6spJAa7oL8oITxhPIf43G5Nv2HZBhRhrvbX//i5RJOY8zvi3UXP2g9PDXfioEfk3BabycYhu4kt7knCt+Rw1jTLcZ1E7nI8+b7KoAW6il7mg2tTdnGzgfg2xjiO/n3yfM90dJXT7lBlCP6pP+4j08DM0EKQuS05yggtp1zjfa9jTzNu2LL6w/AaoeQtbzKrT7jB+JTzuVIJ5rn9UEsGA/7tiel6znuCQB8RBU/oM3ZX9/DleB3+PnEkD87jmSm0DZF27c+68Mlo3WQuWKmlP4v8jlXoTsozPp9pz/JfkmvYMCAwEAAaNTMFEwHQYDVR0OBBYEFFGw6zjtTKQOIVB3dUHi45ez9F/sMB8GA1UdIwQYMBaAFFGw6zjtTKQOIVB3dUHi45ez9F/sMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAC4AUTPSVXmCkDt/OoPw08TzblIDZTzqn7K/Zg4J0Sr7bBlJt7XrcNfbmX5ZPgCLVBRyaa/cEIqEVD5Gm2s3vGw2nRCnI0mGd13UFXxWYpMkoBMQE6NSNWdsDf6BIWrc4oSB/5L6r/UvuX/skd1gOQelea5MqxLopIO3RyYiT02lra8mEAPShDVhsETDb5o9llaPFLq3XR2E2eXnk17PlkOdNug1wV8VIv9aLUIYIEOuyPJZeAmzsukV229+vKI0RWY9aOf49BUulSKXcU4aKKPqLoqQveIZXsOPFq3Sv67sbXFC3DCAUP+KzwR2a17PwCGXwvRZ371Law2dHJNQnHgAAAABAAlsb2NhbGhvc3QAAAFu9WLJlwAABQEwggT9MA4GCisGAQQBKgIRAQEFAASCBOnfnPlcWzWEipTWspIkRyhbwOo/LTFEcKYeSt1j2VHpEtoaoB5ipxm+9a8AYFWYIJKKfZj8gSM+cUwj+259NB1q9h1ekb89cgtTo7yDCC+JI8zYuuPt7fyi85xYDr+iKnM8tWW6EGKcT28BK4NRMhL9FQOOfQUyrJPvUB4iwvSpp2sZuD3OYVW+XVHOVbIEXC6tf/6eFTofL+SA5XT1bAFP5Px2mRjrhJkzA8EituxhWVmS7jNB6EJbchWcgHFkNL48w6kZwaUw2B9PihqPcAKcoz8uLjZBWy/qycxgf1VQXUVsCWjkVAfuy5nhU+7LK2M+xyXXTQwCgQC8IuFY3rBH0eBtBPutVu7P58kJV2a3wGxS4IPcoLofLN18fUayPd/oaKQz7kwWkZ9WWJM1+fmmmOJyDe7WlnmoQijjuaNP/Gjjuy3vXvvGnfSeZ+3YKxMFLwCmB6zMlnm/x0bjW4IT3r6jFiYfqNramkg464vs9g/FoxiTDlz3uqcENcgJNhEr4ZeeUcLg4CnLycC7Ng/VzVf5ylGbT9ultrT+e306Pbm45CHm3eALCsMzTYObJIhQVd2SdquMk5UodVI3PWeMi9SZdGKSvFs9rYJvRNUXO6YyLGwoMKE7OZ2DGcz7NFHKJiR5BjdNBjQ3YZho1Gn0yfcAhYqq988Xh4C0XQ4+g5qFNg67nNRPaw+elFau+4oBM8/mR3i+kf0qSubk95TGN5UZc9cpsd/Yy7vCeyAKICNwz8xc3DfqW/F5UgqcHqF7PrT4r4xxRJJjRaYVq26LA6Rf/0cPER3KhEibOAJPgeFORWNbUSnAamb9FEYjUkwjhIyYe6grZPGod1Oc7NNbjPUa13vNqWteMLQcgrcpQ07+66QrGGJTou2RpkqDQ9QwwgyrD8aPcLGRMaxv9VAqlmHZHLRpfuC+8MX4OaOFze5kRykORe/kNygkqaDkzV4YHMWMZurPcLq8RV+mtCQFs+ul793noej+LmqS0O5YZK7rFuiNa+FG66NumuSa6LYTXxZ/uwJEd7fc9bKnqCKssZGdiBpRpKtFtedLQsTRY8YBINKe88yHp1TF+AQh20976K9vcRiTARc+b01Tqb9BgXDhDR/9s84qpI5plp9+zUQkuSwawkhQlXFK1dSrL2ZyW6Eh9nOGPyxtaOFwmIPLZ650bbP5aEMhyH/ILpe8kAFhFuOQym7oCkYDQN7HePyFAdu4vDqb/b1mg9g6m6lHDAWWXA40nOjsivafUXYrlO+QozJ9MYumwKOqzznvYu6YmAJ8NQL2Uyc0WsT/huuMPo1UYgpd+M16DiRhq6OvwpF1k23T0eVGAGyEaqfNR4CbQLMw31TuHdgh3PB4YpotQULJuf6THrBN2JNbAMNVcpXPHHzTT9g4GroJO0vCSOUlxPiEhubzSQPTJt/KqK6sfBlYeB4KAQh6MGX7x2Wyo0s3CZ+6z+2+hZo+Ep5cbPBQTnso4YTfcbu8BG62jAcVGnbKWxO/vX8H+z553hYRKCYFveuHPioQaFLG7hTghLatyCtJ0NC84jSghRILa38xLNnnSsjPx/ju4Mt1Wztzmqxcpi6IKeJKsB7m+52fvxsU6Y+fyiCwXet5lUw7z44OprzJja752LqJwUu4z/oqQdevQ5xq+Q/u1EhA3Ui+WJmFhDB6iYhyYQUAAAACAAVYLjUwOQAABFgwggRUMIIDPKADAgECAhRulojbEAtSKNrIEAn+5/eWl9gLbTANBgkqhkiG9w0BAQsFADBBMQswCQYDVQQGEwJOTjELMAkGA1UECAwCTk4xCzAJBgNVBAcMAk5OMQswCQYDVQQKDAJOTjELMAkGA1UECwwCTk4wHhcNMTkxMjExMTQzNTIyWhcNNDcwNDI4MTQzNTIyWjCBlDELMAkGA1UEBhMCTk4xCzAJBgNVBAgTAk5OMQswCQYDVQQHEwJOTjELMAkGA1UEChMCTk4xCzAJBgNVBAsTAk5OMVEwTwYDVQQDE0h0ZXN0LWNhc3NhbmRyYS0wLnRlc3QtY2Fzc2FuZHJhLWhlYWRsZXNzLmtlbnNobzItaW5mcmEuc3ZjLmNsdXN0ZXIubG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCTcVywnKARAbdpI2nq+gAXlDQ3doBse9UoRsxVA2eEd/nlxrg31Wm56cdm27uTksiQtrSzgKJ293MB7G8NJdOMPynlxVTrz6VyH8qUCX6NzLoHsunnrvdlm8p7Yt394QUkjfmuRSdXYbG7k7EgORcpWPvfdMS3tTcnJKKNqTQ02ar+qZCf7R3BYjwrA5/ugMeRLrvegpm1x/eXz02zYMzBRsFKHrIVipDl3q7fo7sJNhI0utPdkpqqGzChz5xqSBJL7tvp7CGVVXRfpU8iS6roRxc4FCDHOAu7R/QFyOcwX1RjNecfFo86/fwNSNcEaVbl9iiSphgS//QU8NHpaac9AgMBAAGjge8wgewwgekGA1UdEQSB4TCB3oJIdGVzdC1jYXNzYW5kcmEtMC50ZXN0LWNhc3NhbmRyYS1oZWFkbGVzcy5rZW5zaG8yLWluZnJhLnN2Yy5jbHVzdGVyLmxvY2Fsgkh0ZXN0LWNhc3NhbmRyYS0xLnRlc3QtY2Fzc2FuZHJhLWhlYWRsZXNzLmtlbnNobzItaW5mcmEuc3ZjLmNsdXN0ZXIubG9jYWyCSHRlc3QtY2Fzc2FuZHJhLTIudGVzdC1jYXNzYW5kcmEtaGVhZGxlc3Mua2Vuc2hvMi1pbmZyYS5zdmMuY2x1c3Rlci5sb2NhbDANBgkqhkiG9w0BAQsFAAOCAQEAnEv78vCWD6Ii95HuD4/3cDznbVmNsjA21lgPcuyRSwYHrQz8r1uJs2fU5ii53Wq69eckKUHzSGcNL5PmUPMPM27BcihMKnxQe5q1XQ0BTIlQ9OXyiKhCEvcSUl5vdL13+W9zQ5huz4aOuPkufIBQrvyQknK2IkHTk9LqmPoHfzx2ylSTQqzveYsgzoBw/IUg/5QJ+GHngzY4QDWmKjiEZ31H7Dx4P9FH39mesju9JI2zuKDot6MMxcjDSvlp4jVYqnSR+b96v6U6ZzdEnIXt65gHn/Eiobi+B6sMQe2Ui/Ekg6Tulk6dLUdVqqRl/PHn6HRgG3ShUBgH6s7kkaWZjwAFWC41MDkAAANnMIIDYzCCAkugAwIBAgIUKK0SacSTlKBWEbB5jm3zIMneh2QwDQYJKoZIhvcNAQELBQAwQTELMAkGA1UEBhMCTk4xCzAJBgNVBAgMAk5OMQswCQYDVQQHDAJOTjELMAkGA1UECgwCTk4xCzAJBgNVBAsMAk5OMB4XDTE5MTIxMTE0MzUyMFoXDTQ3MDQyODE0MzUyMFowQTELMAkGA1UEBhMCTk4xCzAJBgNVBAgMAk5OMQswCQYDVQQHDAJOTjELMAkGA1UECgwCTk4xCzAJBgNVBAsMAk5OMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7eHMUBRN7fhEjQ0L52PXtg41iTuvP7w5so9pGCsptbqykkBrugvyghPGE8h/jcbk2/YdkGFGGu9tf/+LlEk5jzO+LdRc/aD08Nd+KgR+TcFpvJxiG7iS3uScK35HDWNMtxnUTucjz5vsqgBbqKXuaDa1N2cbOB+DbGOI7+ffJ8z3R0ldPuUGUI/qk/7iPTwMzQQpC5LTnKCC2nXON9r2NPM27YsvrD8Bqh5C1vMqtPuMH4lPO5Ugnmuf1QSwYD/u2J6XrOe4JAHxEFT+gzdlf38OV4Hf4+cSQPzuOZKbQNkXbtz7rwyWjdZC5YqaU/i/yOVehOyjM+n2nP8l+Sa9gwIDAQABo1MwUTAdBgNVHQ4EFgQUUbDrOO1MpA4hUHd1QeLjl7P0X+wwHwYDVR0jBBgwFoAUUbDrOO1MpA4hUHd1QeLjl7P0X+wwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEALgBRM9JVeYKQO386g/DTxPNuUgNlPOqfsr9mDgnRKvtsGUm3tetw19uZflk+AItUFHJpr9wQioRUPkabaze8bDadEKcjSYZ3XdQVfFZikySgExATo1I1Z2wN/oEhatzihIH/kvqv9S+5f+yR3WA5B6V5rkyrEuikg7dHJiJPTaWtryYQA9KENWGwRMNvmj2WVo8UurddHYTZ5eeTXs+WQ5026DXBXxUi/1otQhggQ67I8ll4CbOy6RXbb368ojRFZj1o5/j0FS6VIpdxThooo+ouipC94hlew48WrdK/ruxtcULcMIBQ/4rPBHZrXs/AIZfC9FnfvUtrDZ0ck1CceDqr+IygqOC4BOwVy1t8Nh6lVwlO
  keystore-password: b3kydGlGVTFGZjY3a1VLTA==
  truststore: /u3+7QAAAAIAAAABAAAAAgAGY2Fyb290AAABbvVix0QABVguNTA5AAADZzCCA2MwggJLoAMCAQICFCitEmnEk5SgVhGweY5t8yDJ3odkMA0GCSqGSIb3DQEBCwUAMEExCzAJBgNVBAYTAk5OMQswCQYDVQQIDAJOTjELMAkGA1UEBwwCTk4xCzAJBgNVBAoMAk5OMQswCQYDVQQLDAJOTjAeFw0xOTEyMTExNDM1MjBaFw00NzA0MjgxNDM1MjBaMEExCzAJBgNVBAYTAk5OMQswCQYDVQQIDAJOTjELMAkGA1UEBwwCTk4xCzAJBgNVBAoMAk5OMQswCQYDVQQLDAJOTjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAO3hzFAUTe34RI0NC+dj17YONYk7rz+8ObKPaRgrKbW6spJAa7oL8oITxhPIf43G5Nv2HZBhRhrvbX//i5RJOY8zvi3UXP2g9PDXfioEfk3BabycYhu4kt7knCt+Rw1jTLcZ1E7nI8+b7KoAW6il7mg2tTdnGzgfg2xjiO/n3yfM90dJXT7lBlCP6pP+4j08DM0EKQuS05yggtp1zjfa9jTzNu2LL6w/AaoeQtbzKrT7jB+JTzuVIJ5rn9UEsGA/7tiel6znuCQB8RBU/oM3ZX9/DleB3+PnEkD87jmSm0DZF27c+68Mlo3WQuWKmlP4v8jlXoTsozPp9pz/JfkmvYMCAwEAAaNTMFEwHQYDVR0OBBYEFFGw6zjtTKQOIVB3dUHi45ez9F/sMB8GA1UdIwQYMBaAFFGw6zjtTKQOIVB3dUHi45ez9F/sMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAC4AUTPSVXmCkDt/OoPw08TzblIDZTzqn7K/Zg4J0Sr7bBlJt7XrcNfbmX5ZPgCLVBRyaa/cEIqEVD5Gm2s3vGw2nRCnI0mGd13UFXxWYpMkoBMQE6NSNWdsDf6BIWrc4oSB/5L6r/UvuX/skd1gOQelea5MqxLopIO3RyYiT02lra8mEAPShDVhsETDb5o9llaPFLq3XR2E2eXnk17PlkOdNug1wV8VIv9aLUIYIEOuyPJZeAmzsukV229+vKI0RWY9aOf49BUulSKXcU4aKKPqLoqQveIZXsOPFq3Sv67sbXFC3DCAUP+KzwR2a17PwCGXwvRZ371Law2dHJNQnHiGZ1zbg2xDD+UHP7AQpsg8rYOOlg==
  truststore-password: b3kydGlGVTFGZjY3a1VLTA==
kind: Secret
metadata:
  name: cassandra-tls
  namespace: test-cassandra
type: Opaque
```
