### ISSUE TITLE
[bitnami/kafka] Cannot update the  KAFKA_CFG_*  values with Helm Deployments

### ISSUE THREAD

**Issue by deep1pradee** [bitnami/charts#17303]
### Name and Version

bitnami/kafka:3.4.1-debian-11-r0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

i Cannot update the values for KAFKA_CFG_* in the second time deployment.

### Are you using any custom parameters or values?
```yaml
  - name: KAFKA_CFG_LOG_CLEANER_DELETE_RETENTION_MS
    value: "300000"
  - name: KAFKA_CFG_LOG_RETENTION_HOURS
    value: "2"
  - name: KAFKA_CFG_LOG_ROLL_HOURS
    value: "3"
  - name: KAFKA_CFG_LOG_MESSAGE_TIMESTAMP_DIFFERENCE_MAX_MS
    value: "14400000"
  - name: KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS
    value: "180000"
  - name: KAFKA_CFG_LOG_MESSAGE_TIMESTAMP_TYPE
    value: "CreateTime"
  - name: KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES
    value: "16777216"
  - name: KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES
    value: "16777216"
  - name: KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES
    value: "104857600"
  - name: KAFKA_CFG_RESERVED_BROKER_MAX_ID
    value: "2147483647"
  - name: KAFKA_CFG_REPLICA_FETCH_MAX_BYTES
    value: "67108864"
  - name: KAFKA_CFG_NUM_PARTITIONS
    value: "3"
  - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
    value: "true"
  - name: KAFKA_CFG_ALLOW_AUTO_CREATE_TOPICS
    value: "false"
  - name: KAFKA_CFG_DEFAULT_REPLICATION_FACTOR
    value: "1"
  - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
    value: "1"
```
### What is the expected behavior?

When i update the value for KAFKA_CFG_LOG_RETENTION_HOURS to` 2 to 3.` it should update in the container..

### What do you see instead?

The helm deployment fails with below error
```
Error: UPGRADE FAILED: cannot patch "kafka-test" with kind StatefulSet: The order in patch list:
[map[name:KAFKA_CFG_ZOOKEEPER_CONNECT value:<nil>] map[name:KAFKA_CFG_LOG_RETENTION_HOURS value:168] map[name:KAFKA_CFG_LOG_RETENTION_HOURS value:2] map[name:KAFKA_CFG_NUM_PARTITIONS value:1] map[name:KAFKA_CFG_NUM_PARTITIONS value:3] map[name:KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES value:16777216] map[name:KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES value:102400] map[name:KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES value:102400] map[name:KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES value:16777216] map[name:KAFKA_CFG_AUTHORIZER_CLASS_NAME value:]]
```
 doesn't match $setElementOrder list:
 ```
[map[name:BITNAMI_DEBUG] map[name:MY_POD_IP] map[name:MY_POD_NAME] map[name:KAFKA_CFG_ZOOKEEPER_CONNECT] map[name:KAFKA_INTER_BROKER_LISTENER_NAME] map[name:KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP] map[name:KAFKA_CFG_LISTENERS] map[name:KAFKA_CFG_ADVERTISED_LISTENERS] map[name:ALLOW_PLAINTEXT_LISTENER] map[name:KAFKA_ZOOKEEPER_PROTOCOL] map[name:KAFKA_VOLUME_DIR] map[name:KAFKA_LOG_DIR] map[name:KAFKA_CFG_DELETE_TOPIC_ENABLE] map[name:KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE] map[name:KAFKA_HEAP_OPTS] map[name:KAFKA_CFG_LOG_FLUSH_INTERVAL_MESSAGES] map[name:KAFKA_CFG_LOG_FLUSH_INTERVAL_MS] map[name:KAFKA_CFG_LOG_RETENTION_BYTES] map[name:KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS] map[name:KAFKA_CFG_LOG_RETENTION_HOURS] map[name:KAFKA_CFG_MESSAGE_MAX_BYTES] map[name:KAFKA_CFG_LOG_SEGMENT_BYTES] map[name:KAFKA_CFG_LOG_DIRS] map[name:KAFKA_CFG_DEFAULT_REPLICATION_FACTOR] map[name:KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR] map[name:KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR] map[name:KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR] map[name:KAFKA_CFG_NUM_IO_THREADS] map[name:KAFKA_CFG_NUM_NETWORK_THREADS] map[name:KAFKA_CFG_NUM_PARTITIONS] map[name:KAFKA_CFG_NUM_RECOVERY_THREADS_PER_DATA_DIR] map[name:KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES] map[name:KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES] map[name:KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES] map[name:KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS] map[name:KAFKA_CFG_AUTHORIZER_CLASS_NAME] map[name:KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND] map[name:KAFKA_CFG_SUPER_USERS] map[name:KAFKA_ENABLE_KRAFT] map[name:KAFKA_KRAFT_CLUSTER_ID] map[name:KAFKA_CFG_PROCESS_ROLES] map[name:KAFKA_CFG_CONTROLLER_LISTENER_NAMES] map[name:KAFKA_CFG_LOG_CLEANER_DELETE_RETENTION_MS] map[name:KAFKA_CFG_LOG_RETENTION_HOURS] map[name:KAFKA_CFG_LOG_ROLL_HOURS] map[name:KAFKA_CFG_LOG_MESSAGE_TIMESTAMP_DIFFERENCE_MAX_MS] map[name:KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS] map[name:KAFKA_CFG_LOG_MESSAGE_TIMESTAMP_TYPE] map[name:KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES] map[name:KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES] map[name:KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES] map[name:KAFKA_CFG_RESERVED_BROKER_MAX_ID] map[name:KAFKA_CFG_REPLICA_FETCH_MAX_BYTES] map[name:KAFKA_CFG_NUM_PARTITIONS] map[name:KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE] map[name:KAFKA_CFG_ALLOW_AUTO_CREATE_TOPICS] map[name:KAFKA_CFG_DEFAULT_REPLICATION_FACTOR] map[name:KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR]]`
```
