### ISSUE TITLE
[bitnami/redis-cluster] no password issue

### ISSUE THREAD

**Issue by mojixcoder** [bitnami/charts#17338]
### Name and Version

bitnami/redis-cluster

### What architecture are you using?

None

### What steps will reproduce the bug?

Here is my manifest:
```
nameOverride: "redis-cluster"
fullnameOverride: "redis-cluster"

commonLabels:
  app: redis-cluster

usePassword: false

image:
  tag: 6.2-debian-11

podSecurityContext:
  enabled: true
  sysctls:
    - name: "net.core.somaxconn"
      value: "65535"
    - name: "net.ipv4.ip_local_port_range"
      value: "15000 60999"

containerSecurityContext:
  enabled: true

persistence:
  enabled: true
  path: /redis/data
  size: 500Mi

service:
  type: ClusterIP

volumePermissions:
  enabled: true
  image:
    tag: 11-debian-11-r118

redis:
  resources:
    limits:
      memory: 500Mi
      cpu: 200m
  defaultConfigOverride: |
    dir /redis/data
    appendonly yes
    save 60 500
    maxmemory 450mb
    maxmemory-policy allkeys-lru
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 15000
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit slave 800mb 800mb 180
    client-output-buffer-limit pubsub 32mb 8mb 60
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 9
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 9
    successThreshold: 1
    failureThreshold: 5

cluster:
  nodes: 6
  replicas: 1
  update:
    currentNumberOfNodes: 6
    currentNumberOfReplicas: 1

metrics:
  enabled: true
  tag: 1.50.0-debian-11-r13
  resources:
    limits:
      memory: 150Mi
      cpu: 100m
  containerSecurityContext:
    enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s
```

The cluster is deployed and there is no error at the first sight.
But when I look at the logs of `redis-cluster-0` pod I see lots of this error log:
```
AUTH failed: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
2321
Node redis-cluster-0.redis-cluster-headless not ready, waiting for all the nodes to be ready... 
```

Therefore, in the client-side when I do redis commands some of them are failed because of this error:
```
dial tcp ip:6379: connect: no route to host
```

And the IP changes over time.

Has anyone had this issue before?

### What is the expected behavior?

There should be no AUTH error since it's disabled.

### What do you see instead?

I see AUTH error.
