### ISSUE TITLE
[bitnami/kafka] Enabling the mTLS with Custom certs the deployment fails with cp error

### ISSUE THREAD

**Issue by deep1pradee** [bitnami/charts#17348]
### Name and Version

bitnami/kafka:3.4.1-debian-11-r0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy the secrets
```
kubectl -n bit-kafka create secret generic kafka-test-cluster-0-tls --from-file=ca.crt=./ca.cert --from-file=tls.crt=./tls.crt --from-file=tls.key=./tls.key
```

Deploy the Kafka with 1 `replicaCount`
```
auth:
  clientProtocol: plaintext
  externalClientProtocol: plaintext
  interBrokerProtocol: tls
  sasl:
    mechanisms: plain,scram-sha-256,scram-sha-512
    interBrokerMechanism: plain
    jaas:
      clientUsers:
        - user
      clientPasswords: []
      interBrokerUser: admin
      interBrokerPassword: ""
      zookeeperUser: ""
      zookeeperPassword: ""
      existingSecret: ""
  tls:
    type: pem
    pemChainIncluded: true
    existingSecrets: 
       - kafka-test-cluster-0-tls
    autoGenerated: false
    password: "test123"
    existingSecret: ""
    jksTruststoreSecret: ""
    jksKeystoreSAN: ""
    jksTruststore: ""
    endpointIdentificationAlgorithm: ""
  zookeeper:
    tls:
      enabled: true
      type: jks
      verifyHostname: false
      existingSecret: "zookeeper"
      existingSecretKeystoreKey: zookeeper.keystore.jks
      existingSecretTruststoreKey: zookeeper.truststore.jks
      passwordsSecret: "secret-key"
      passwordsSecretKeystoreKey: "secret-key"
      passwordsSecretTruststoreKey: "secret-key"
```      
      
Im using the external Zookeeper setup and configure the JKS Client Authentication with Plaintext protocol.
      
When i enable the mtls for `interBrokerProtocol` the deployment complains about 
```
cp: cannot create regular file '/opt/bitnami/kafka/config/certs/zookeeper.keystore.jks': Permission denied 2023-06-26T14:46:14.196632686Z cp: cannot create regular file '/opt/bitnami/kafka/config/certs/zookeeper.truststore.jks': Permission denied
```
      
Any clue if i have done any mistake with my deployment. 

### Are you using any custom parameters or values?

I have created the Customer Certs and Deployed 

### What is the expected behavior?

The cluster kafka broker should come up as expected

### What do you see instead?

The error is 

```
cp: cannot create regular file '/opt/bitnami/kafka/config/certs/zookeeper.keystore.jks': Permission denied 2023-06-26T14:46:14.196632686Z cp: cannot create regular file '/opt/bitnami/kafka/config/certs/zookeeper.truststore.jks': Permission denied
```

### Additional information

Could someone tell me how to use the  jksSecret jksPassword with the deployment.

_No response_
