### ISSUE TITLE
[bitnami/redis-cluster] Error condition on socket for SYNC: No route to host Redis Cluster

### ISSUE THREAD

**Issue by mojixcoder** [bitnami/charts#17340]
### Name and Version

bitnami/redis-cluster

### What architecture are you using?

None

### What steps will reproduce the bug?

Whenever I deploy a redis-cluster all the master pods are okay and running.

But I get the following logs in the slave nodes:
```
1:S 24 Jun 2023 12:07:55.084 # Error condition on socket for SYNC: No route to host
714
1:S 24 Jun 2023 12:07:55.479 * Connecting to MASTER 10.131.187.165:6379
715
1:S 24 Jun 2023 12:07:55.479 * MASTER <-> REPLICA sync started
```

Here is my deployment:
```
nameOverride: "redis-cluster"
fullnameOverride: "redis-cluster"

usePassword: false

image:
  tag: 6.2-debian-11

podSecurityContext:
  enabled: true
  sysctls:
    - name: "net.core.somaxconn"
      value: "65535"
    - name: "net.ipv4.ip_local_port_range"
      value: "15000 60999"

containerSecurityContext:
  enabled: true

persistence:
  enabled: true
  path: /redis/data
  size: 500Mi

service:
  type: ClusterIP

volumePermissions:
  enabled: true
  image:
    tag: 11-debian-11-r118

redis:
  resources:
    limits:
      memory: 500Mi
      cpu: 200m
  defaultConfigOverride: |
    dir /redis/data
    appendonly yes
    save 60 500
    maxmemory 450mb
    maxmemory-policy allkeys-lru
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 15000
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit slave 800mb 800mb 180
    client-output-buffer-limit pubsub 32mb 8mb 60
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 9
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 9
    successThreshold: 1
    failureThreshold: 5

cluster:
  nodes: 6
  replicas: 1
  # externalAccess:
  #   enabled: true
  #   type: ClusterIP
  update:
    currentNumberOfNodes: 6
    currentNumberOfReplicas: 1

metrics:
  enabled: true
  tag: 1.50.0-debian-11-r13
  resources:
    limits:
      memory: 150Mi
      cpu: 100m
  containerSecurityContext:
    enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s
```

### What is the expected behavior?

Slaves should be able to sync with master nodes.

### What do you see instead?

slaves node can't sync.
