### ISSUE TITLE
[bitnami/kafka] max.request.size configuration not working (socketRequestMaxBytes)

### ISSUE THREAD

**Issue by TotallyTroll** [bitnami/charts#17347]
### Name and Version

chart=kafka-22.1.6

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Fire up kafka with:
helm install my-release oci://registry-1.docker.io/bitnamicharts/kafka -n kafka \
-f ./values.yaml
2. Start kafka-connect from kafka.strimzi.io/v1beta2 on top of started kafka.
3. Setup MySQL-debezium connector to a desired server/database.
4. I'm using some database dump restored to a couple of databases that deployed to an Azure MySQL flexible server. 
5. When connectors starting (1 connector to 1 database) their status is ok, until some of them can drop with next error:
```
java.base/java.lang.Thread.run(Thread.java:829)\nCaused by: org.apache.kafka.common.errors.RecordTooLargeException:
        **The message is 1906815 bytes when serialized which is larger than 1048576,**
        which is the value of the max.request.size configuration.\n"
```
### Are you using any custom parameters or values?

I've tried to increase max.request.size via any similar or related parameter that I could find in parameters section.
Also added extraEnvVars to my values file.

So here is my values.yaml:
```
socketRequestMaxBytes: "_209715200"
socketReceiveBufferBytes: "204800"
socketSendBufferBytes: "204800"
maxMessageBytes: "_209715200"
deleteTopicEnable: true
externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
rbac:
  create: true
extraEnvVars:
  - name: KAFKA_CFG_MAX_REQUEST_SIZE
    value: "2097152"
  - name: KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES
    value: "2097152"
  - name: KAFKA_CFG_FETCH_MESSAGE_MAX_BYTES
    value: "2097152"
  - name: KAFKA_CFG_CONNECT_PRODUCER_MAX_REQUEST_SIZE
    value: "2097152"
  - name: KAFKA_CFG_PRODUCER_MAX_REQUEST_SIZE
    value: "2097152"
```
### What is the expected behavior?

max.request.size should be increased and error doesn't occur.

### What do you see instead?
```
java.base/java.lang.Thread.run(Thread.java:829)\nCaused by: org.apache.kafka.common.errors.RecordTooLargeException:
        **The message is 1906815 bytes when serialized which is larger than 1048576,**
        which is the value of the max.request.size configuration.\n"
```   
 Also in the server.properties file, on kafka pod I can see that:
 socket.request.max.bytes=104857600
