### ISSUE TITLE
[bitnami/rabbitmq] Readiness probe and liveness probe fails after each deployment update for rabbitmq

### ISSUE THREAD

**Issue by dhruvbardolia** [bitnami/charts#17359]
### Name and Version

bitnami/rabbitmq 3.12.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. I installed the helm chart with the required custom-values. 
2. After updating the fields like resource, limits, or anything. When I upgrade the helm chart it throws an error message of readiness probe and liveness probe failed.

The output of kubectl describe pod :
```
Events:
  Type     Reason     Age               From     Message
  ----     ------     ----              ----     -------
  Warning  Unhealthy  40m (x6 over 8h)  kubelet  Liveness probe failed:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 15672: Connection refused
  Warning  Unhealthy  13m (x745 over 14h)  kubelet  Liveness probe failed:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 15672: Connection refused
  Warning  Unhealthy  5m14s (x1648 over 14h)  kubelet  Readiness probe failed:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 15672: Connection refused
```

The output of kubectl logs : 
```
rabbitmq 05:50:23.08 
rabbitmq 05:50:23.38 Welcome to the Bitnami rabbitmq container
rabbitmq 05:50:23.68 Subscribe to project updates by watching https://github.com/bitnami/containers
rabbitmq 05:50:23.98 Submit issues and feature requests at https://github.com/bitnami/containers/issues
rabbitmq 05:50:24.18 
rabbitmq 05:50:24.38 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 05:50:26.68 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 05:50:29.78 INFO  ==> Initializing RabbitMQ...
rabbitmq 05:50:35.48 INFO  ==> Starting RabbitMQ in background...
```

The pod is getting restarted everytime.
3. I also tried to increase the initial delay seconds of readiness probe to 120, But the error remains the same.

### Are you using any custom parameters or values?

```
global:
  
  storageClass: "sc"

auth:
  username: ""
  erlangCookie: ""
  existingPasswordSecret: ""
persistence:

  enabled: true
  storageClass: "sc"
  accessModes:
    - ReadWriteOnce
  size: 2Gi

replicaCount: 3

updateStrategy:
  ## StrategyType
  ## Can be set to RollingUpdate or OnDelete
  ##
  type: OnDelete

nodeSelector:
  Name: rabbitmq-node

plugins: "rabbitmq_management rabbitmq_peer_discovery_k8s rabbitmq_federation rabbitmq_prometheus"

service:
  type: "LoadBalancer"
  annotations:
    cloud.google.com/load-balancer-type: internal
    # networking.gke.io/internal-load-balancer-allow-global-access: "true"
clustering:
  forceBoot: true
  
resources:
  limits:
    cpu: 4000m
    memory: 12Gi
  requests:
    cpu: 2000m
    memory: 8Gi

metrics:
  enabled: true
```

### What is the expected behavior?

It should be in a ready state after every upgrade or at least I should get an error in the logs.

### What do you see instead?

I am not getting any errors in the logs. When I described the pod I got the error message of readinessProbe and livenessProbe failed.
