### ISSUE TITLE
Wordpress helm chart ultimatively slow

### ISSUE THREAD

**Issue by Tjerk-Haaye-Henricus** [bitnami/charts#17363]
### Name and Version

bitnami/wordpress latest

### What architecture are you using?

None

### What steps will reproduce the bug?

Hey There, 

we're running the newest Wordpress Chart. An unfortunetly it so slow that installing Woocommerce needs about 10 Minutes. 

We're really wondering why that happens because we don't do anything special. Spinning up the Database needs 3 Minutes and activating WooCommerce needs more then 10 Minutes. In earlier releases it was a lot faster. Can you guys tell us how to speed things up here ? 

```yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: wordpress
  namespace: kube-system
spec:
  chart: wordpress
  repo: https://charts.bitnami.com/bitnami
  targetNamespace: xxxx
  valuesContent: |-
    image:
      debug: false
    podLabels:
      app: xxxx-wordpress
    service:
      type: ClusterIP

    # podSecurityContext:
    #   enabled: false
    #   fsGroup: 0
    # containerSecurityContext:
    #   enabled: false
    #   runAsUser: 0
    #   runAsNonRoot: false

    resources:
      requests:
        memory: 2Gi
        cpu: "1.5"
      limits:
        memory: 3Gi
        cpu: "2.5"
    persistence:
      existingClaim: xxxx-pvc-wordpress-production
    mariadb:
      primary:
        persistence:
          existingClaim: xxxx-pvc-mariadb-wordpress-production
      auth:
        database: xxx
        username: xxxx
        password: xxxx
        rootPassword: xxxx

    wordpressConfigureCache: true
    memcached:
      enabled: true

    wordpressUsername: xxxx
    wordpressPassword: xxxx
    wordpressTablePrefix: wp_
    wordpressEmail: developer+xxxx@xxxx.io

    extraVolumeMounts:
      - name: php-ini
        mountPath: /opt/bitnami/php/etc/conf.d
    extraVolumes:
      - name: php-ini
        configMap:
          name: xxxx-php-ini-wordpress-production
```

We also gave it 10GB Memory and 5 cores but without any better perfomance results. 
This is our php-ini

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-ini-wordpress
  namespace: xxxx
  labels:
    app.kubernetes.io/name: wordpress
data:
  php-custom.ini: |
    upload_max_filesize = 256M
    post_max_size = 256M
    max_execution_time = 3600
    max_input_time = 3600
    memory_limit = 3072M

```

### Are you using any custom parameters or values?

We're using kustomize but that shouldnt make any difference :) 

### What is the expected behavior?

It should be super fast

### What do you see instead?

it is extremely slow
