### ISSUE TITLE
[bitnami/wordpress] cannot install theme

### ISSUE THREAD

**Issue by Tjerk-Haaye-Henricus** [bitnami/charts#17364]
### Name and Version

bitnami/wordpress latest

### What architecture are you using?

None

### What steps will reproduce the bug?

Hey There, 

If i'm spinning up a default environment without anything else - just this wordpress helmchart with the following configuration: 

```yaml 
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: wordpress
  namespace: kube-system
spec:
  chart: wordpress
  repo: https://charts.bitnami.com/bitnami
  targetNamespace: xxxx
  valuesContent: |-
    image:
      debug: false
    podLabels:
      app: xxxx-wordpress
    service:
      type: ClusterIP

    # podSecurityContext:
    #   enabled: false
    #   fsGroup: 0
    # containerSecurityContext:
    #   enabled: false
    #   runAsUser: 0
    #   runAsNonRoot: false

    resources:
      requests:
        memory: 5Gi
        cpu: "2.5"
      limits:
        memory: 8Gi
        cpu: "3.5"
    persistence:
      existingClaim: xxxx-pvc-wordpress-production
    mariadb:
      primary:
        persistence:
          existingClaim: xxxx-pvc-mariadb-wordpress-production
      auth:
        database: xxxx
        username: xxxx
        password: xxxx
        rootPassword: xxxx

    wordpressConfigureCache: true
    memcached:
      enabled: true

    wordpressUsername: xxxx
    wordpressPassword: xxxx
    wordpressTablePrefix: wp_
    wordpressEmail: developer+xxxx@xxxx.io

    extraVolumeMounts:
      - name: php-ini
        mountPath: /opt/bitnami/php/etc/conf.d
    extraVolumes:
      - name: php-ini
        configMap:
          name: xxxx-php-ini-wordpress-production

```

I cannot install any theme. It's telling me that it isn't allowed to create directories. 

### What is the expected behavior?

It should be able to install themes

### What do you see instead?

It's not able to install themes
