### ISSUE TITLE
[bitnami/postgresql-ha] PG Pool unable to find valid pool key

### ISSUE THREAD

**Issue by gerethd** [bitnami/charts#17367]
### Name and Version

postgresql-ha-11.7.2/15.3.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. `helm fetch --untar oci://registry-1.docker.io/bitnamicharts/postgresql-ha`

2. update global configs to 

```
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: "csi-rbd-sc"
  postgresql:
    username: "zevrant"
    password: ""
    database: ""
    repmgrUsername: ""
    repmgrPassword: ""
    repmgrDatabase: ""
    existingSecret: "backup-service-postgres-credentials"
  ldap:
    bindpw: ""
    existingSecret: ""
  pgpool:
    adminUsername: "postgres"
    adminPassword: "?.Jdv0BL~DJ4ZhUbgSl7[MNv*%5Hp<b8xyVvsqJ?4zzqVAD(NFKQDXq.<AfgWi7DKCH1fzxv~E6.^8mX"
    existingSecret: ""
```

3. helm install release-name postgresql-ha 

### Are you using any custom parameters or values?
```
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: "csi-rbd-sc"
  postgresql:
    username: "zevrant"
    password: ""
    database: ""
    repmgrUsername: ""
    repmgrPassword: ""
    repmgrDatabase: ""
    existingSecret: "backup-service-postgres-credentials"
  ldap:
    bindpw: ""
    existingSecret: ""
  pgpool:
    adminUsername: "postgres"
    adminPassword: "?.Jdv0BL~DJ4ZhUbgSl7[MNv*%5Hp<b8xyVvsqJ?4zzqVAD(NFKQDXq.<AfgWi7DKCH1fzxv~E6.^8mX"
    existingSecret: ""
```
### What is the expected behavior?

PG Pool is able to connect to database instances

### What do you see instead?
```
2023-06-27 14:05:02.711: child pid 137: ERROR:  SCRAM authentication failed
2023-06-27 14:05:02.711: child pid 137: DETAIL:  unable to decrypt password from pool_passwd
2023-06-27 14:05:02.711: child pid 137: HINT:  verify the valid pool_key exists
```

### Additional information

I've tried both explicit and passing in secret names. I'm able to see the configs in the PGPool container as it tried to start up. Not sure what i'm missing here. This may end up being a feature request for better documentation on required field updates to get this to run.

for each attempt for clarity i am uninstalling and deleting PVCs

```
helm uninstall release-name && kubectl delete pvc `kubectl get pvc | grep release-name | awk '{ print $1 }'` && helm install release-name .
```
