### ISSUE TITLE
[bitnami/keycloak] Can't import themes because initContainer doesn't work with private registries

### ISSUE THREAD

**Issue by spoilerdo** [bitnami/charts#17376]
### Name and Version

bitnami/keycloak 15.1.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

This is my .gotmpl file where I use a docker image from a private registry

```
service:
    type: NodePort

  ingress:
    enabled: true
    ingressClassName: "alb"
    hostname: {{ .Values.host }}
    path: /*
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: instance
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/certificate-arn: {{ requiredEnv "AWS_CRT_ARN" }}
      alb.ingress.kubernetes.io/group.name: "test-01-external"
      alb.ingress.kubernetes.io/backend-protocol: "HTTP"
      alb.ingress.kubernetes.io/wafv2-acl-arn: {{ requiredEnv "AWS_WAF_ARN" }}
      alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-path: /
      elbv2.k8s.aws/targetGroupBinding: shared

  extraVolumes:
    - name: theme
      emptyDir: {}

  extraVolumeMounts:
    - name: theme
      mountPath: /opt/jboss/keycloak/themes/xen

  initContainers:
    - name: theme-template
      image: "{{ requiredEnv "CI_REGISTRY" }}/{{ requiredEnv "IMAGE_NAME" }}:{{ requiredEnv "IMAGE_TAG" }}"
      imagePullSecrets: nexuscreds-keycloak
      imagePullPolicy: Always
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying theme ..."
          cp -R /xen/* /theme
      volumeMounts:
        - name: theme
          mountPath: /theme
```

### What is the expected behavior?

That the initContainer can authenticate successfully with the private registry and pull the image from it.

### What do you see instead?

I get the following errors when I try to do this with a private Docker registry

![image](https://github.com/bitnami/charts/assets/21689486/7d3a193e-7417-45e3-81fa-09eb77e76fff)

So first an unauthorized and then a ImagePullBackOff error.

**Comment by javsalgar** [comment]
Hi,

Could you confirm that the rendered YAML file has the proper `imagePullSecrets` section?

**Comment by spoilerdo** [comment]
So I am relativly new to Kubernetes so please keep that in mind. I think you are refering to the following:
![image](https://github.com/bitnami/charts/assets/21689486/331cb88e-fccf-42c3-a760-5bbd0faa3fc9)

This is the secret and I also already tried naming the imagePullSecrets to nexuscreds-keycloak-xential-keycloak, but it has the same result. The secret contains a .dockerconfigjson using the following yaml config to make the secret:

```
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}-{{ .Chart.Name }}
data:
  .dockerconfigjson: {{ .Values.secret.dockerConfigJson }}
type: kubernetes.io/dockerconfigjson
```

**Comment by spoilerdo** [comment]
![image](https://github.com/bitnami/charts/assets/21689486/8db1f42a-b0bc-451b-8cb9-8e847df6ce9a)

Also when I check on AWS in the raw view of the deployed keycloak pod. I do not see any imagePullSecrets section

**Comment by spoilerdo** [comment]
Do I perhaps need to use the global.imagePullSecrets instead of putting the secret value in initContainers.imagePullSecrets?

**Comment by spoilerdo** [comment]
Alright I fixed it myself by using a custom Docker image instead of the basic bitnami/keycloak one. I just extend that image with a COPY to copy my theme to the themes folder inside keycloak. Then I push the image to the private registry and use the following config:

```
  image:
    registry: {{ requiredEnv "CI_REGISTRY" }}
    repository: {{ requiredEnv "IMAGE_NAME" }}
    tag: {{ requiredEnv "IMAGE_TAG" }}
    pullPolicy: Always
    pullSecrets:
      - MY_SECRET
```

The secret I made with this:

```
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}-{{ .Chart.Name }}
data:
  .dockerconfigjson: {{ .Values.secret.dockerConfigJson }}
type: kubernetes.io/dockerconfigjson
```
