### ISSUE TITLE
[bitnami/redis-cluster] New node not joining cluster when scaling up

### ISSUE THREAD

**Issue by LukeRH** [bitnami/charts#17381]
### Name and Version

bitnami/redis-cluster 8.3.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi,
We are finding that when following the guide for scaling up the redis cluster that the new nodes are created but they do not join the cluster. In the example below we are scaling from 9 to 10 nodes.

Logs of new node:
```
redis-cluster 11:02:03.40 
redis-cluster 11:02:03.40 Welcome to the Bitnami redis-cluster container
redis-cluster 11:02:03.40 Subscribe to project updates by watching https://github.com/bitnami/containers
redis-cluster 11:02:03.40 Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis-cluster 11:02:03.40 
redis-cluster 11:02:03.40 INFO  ==> ** Starting Redis setup **
redis-cluster 11:02:03.42 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis-cluster 11:02:03.43 INFO  ==> Initializing Redis
redis-cluster 11:02:03.44 INFO  ==> Setting Redis config file
Storing map with hostnames and IPs
redis-cluster 11:02:08.63 INFO  ==> ** Redis setup finished! **

1:C 28 Jun 2023 11:02:08.667 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 28 Jun 2023 11:02:08.667 # Redis version=7.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 28 Jun 2023 11:02:08.667 # Configuration loaded
1:M 28 Jun 2023 11:02:08.667 * monotonic clock: POSIX clock_gettime
1:M 28 Jun 2023 11:02:08.668 * No cluster configuration found, I'm e91ad3361baeec5e0c871b36e7e12163c6d2dac2
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 7.0.8 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                  
 (    '      ,       .-`  | `,    )     Running in cluster mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           https://redis.io       
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

1:M 28 Jun 2023 11:02:08.679 # Server initialized
1:M 28 Jun 2023 11:02:08.683 * Creating AOF base file appendonly.aof.1.base.rdb on server start
1:M 28 Jun 2023 11:02:08.690 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
1:M 28 Jun 2023 11:02:08.690 * Ready to accept connections
```

### Are you using any custom parameters or values?
```yaml
usePassword: false
fullnameOverride: redis-cluster
cluster:
  init: false
  nodes: 10
  replicas: 1
  update:
    addNodes: true
    currentNumberOfNodes: 9
redis: 
  configmap: |- # This lines add extra configuration to the default config already present. (need to investigate if it overrides if same parameters are added)
    maxmemory 9500mb
    maxmemory-policy volatile-lru
  resources:
    limits:
      memory: 11G
    requests:
      cpu: 400m
      memory: 10G

persistence:
  size: 127Gi
```
### What is the expected behavior?

New nodes added when scaling up will join the cluster

### What do you see instead?

The nodes are not able to join the existing cluster

### Additional information

We are using FluxCD to install the Helm charts
