### ISSUE TITLE
[bitnami/keycloak] Azure AGW HTTPS is configured incorrectly

### ISSUE THREAD

**Issue by engineertdog** [bitnami/charts#17391]
### Name and Version

bitnami/keycloak 15.1.6

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Install the latest version of the Bitnami KeyCloak helm chart.
2. Install the Azure Application Gateway controller (there seems to be issues in the Microsoft documentation, so the simplest way to do this is through enabling it on the AKS cluster from within the portal).
3. Deploy an HTTPS version of KeyCloak to the AKS cluster.

### Are you using any custom parameters or values?

```yml
enabled: true
namespaceOverride: keycloak

global:
  imagePullSecrets:
    - name: regcred

postgresql:
  enabled: false

externalDatabase: 
  host: my-postgres-host
  port: 5432
  user: keycloak
  database: KeyCloak
  existingSecret: keycloak-externaldb
  existingSecretPasswordKey: db-password

auth:
  adminUser: admin
  existingSecret: keycloak-admin
  passwordSecretKey: admin-password

tls:
  enabled: true
  autoGenerated: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
  hostname: keycloak.mydomain.com
  tls: true
  servicePort: https
```

### What do you see instead?

With the above configuration, the Azure Application Gateway should produce an HTTPS listener to KeyCloak, that is then publicly accessible over HTTPS. Instead, this is what I see:

KeyCloak service:
```
keycloak            ClusterIP   10.0.167.186   <none>        80/TCP,443/TCP   13m   app.kubernetes.io/component=keycloak,app.kubernetes.io/instance=keycloak,app.kubernetes.io/name=keycloak
keycloak-headless   ClusterIP   None           <none>        80/TCP,443/TCP   13m   app.kubernetes.io/component=keycloak,app.kubernetes.io/instance=keycloak,app.kubernetes.io/name=keycloak
```

KeyCloak ingress:
```
keycloak   <none>   keycloak.mydomain.com   <public-AGW-IP>   80      17m
```

I added the certificate & private key with the following command:
```bash
kubectl create secret tls keycloak.mydomain.com-tls --key .\cert-key.key --cert .\cert-cert.crt -n keycloak 
```

I did notice before that the secret name was definied explicitly via hostname, and I was receiving an error before. But that error no longer exists. If I describe the ingress, I do have the following error message (which did not occur the other day):
```
 Warning  PortResolutionError  20m (x2 over 21m)  azure/application-gateway  Code="ErrorServiceResolvedToInvalidPort" Message="service keycloak/keycloak and service port https was resolved to an invalid service-backend port 65536, defaulting to port 80"
```

As for host the KeyCloak ingress is being written into the Application Gateway, it's using the HTTP protocol, but the HTTPS port for KeyCloak. And it's not binding the SSL certificate to the listener.

If I deploy KeyCloak with `tls: false` and `servicePort: http`, then everything works fine, but KeyCloak is only accessible over port 80 through the Application Gateway, and that's not desired.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by engineertdog** [comment]
Determined the full configuration necessary for anyone that may need it in the future.

```yaml
enabled: true
production: true
namespaceOverride: keycloak

global:
  imagePullSecrets:
    - name: regcred

postgresql:
  enabled: false

externalDatabase: 
  host: mypostgres
  port: 5432
  user: keycloak
  database: KeyCloak
  existingSecret: keycloak-externaldb
  existingSecretPasswordKey: db-password

auth:
  adminUser: admin
  existingSecret: keycloak-admin
  passwordSecretKey: admin-password

tls:
  enabled: true
  usePem: true
  existingSecret: keycloak.mydomain

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-hostname: "keycloak.mydomain"
    appgw.ingress.kubernetes.io/backend-protocol: "https"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "cert-keycloak-keycloak.mydomain-tls"
    appgw.ingress.kubernetes.io/health-probe-port: "8443"
  hostname: keycloak.mydomain
  tls: true
  servicePort: https
```

**Comment by engineertdog** [comment]
Determined the full configuration necessary for anyone that may need it in the future.

```yaml
enabled: true
production: true
namespaceOverride: keycloak

global:
  imagePullSecrets:
    - name: regcred

postgresql:
  enabled: false

externalDatabase: 
  host: mypostgres
  port: 5432
  user: keycloak
  database: KeyCloak
  existingSecret: keycloak-externaldb
  existingSecretPasswordKey: db-password

auth:
  adminUser: admin
  existingSecret: keycloak-admin
  passwordSecretKey: admin-password

tls:
  enabled: true
  usePem: true
  existingSecret: keycloak.mydomain

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-hostname: "keycloak.mydomain"
    appgw.ingress.kubernetes.io/backend-protocol: "https"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "cert-keycloak-keycloak.mydomain-tls"
    appgw.ingress.kubernetes.io/health-probe-port: "8443"
  hostname: keycloak.mydomain
  tls: true
  servicePort: https
```
