### ISSUE TITLE
[bitnami/elasticsearch] Cannot login or recognize credentials after enabling EKS secrets encryption

### ISSUE THREAD

**Issue by fkamaliada** [bitnami/charts#17399]
### Name and Version

bitnami/elasticsearch 19.10.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Installed in AWS EKS cluster and was working fine until secrets encryption enabled in cluster.

`helm install es-bi --values es-dev-secure.yaml --render-subchart-notes bitnami/elasticsearch --namespace koko`

### Are you using any custom parameters or values?

es-dev-secure-yaml:

```yaml
global:
  kibanaEnabled: true

clusterName: srate-bi

master:
  replicaCount: 1
  masterOnly: true

data:
  replicaCount: 1

coordinating:
  replicaCount: 0

ingest:
 enabled: false

security:
  enabled: true
  elasticPassword: "test-pass"
  tls:
    autoGenerated: true
    restEncryption: true

kibana:
  elasticsearch:
    hosts:
    - "es-bi-elasticsearch"
    port: 9200
    security:
      auth:
        enabled: true
        createSystemUser: true
        kibanaPassword: "test-pass"
        elasticsearchPasswordSecret: es-bi-elasticsearch
      tls:
        # Instruct kibana to connect to elastic over https
        enabled: true
        existingSecret: es-bi-elasticsearch-master-crt 
        usePemCerts: true
        # verificationMode: none
```

### What is the expected behavior?

In logs all seems normal and I can login to kibana with username: elastic and pass: test-pass for example

### What do you see instead?

Pods are restarting and cannot login to kibana. Also elasticsearch keeps giving error:

`[INFO ][o.e.x.s.a.RealmsAuthenticator] [es-bi-elasticsearch-master-0] Authentication of [kibana_system] was terminated by realm [reserved] - failed to authenticate user [kibana_system]`

[elasticsearch.log](https://github.com/bitnami/charts/files/11904965/elasticsearch.log)
[elasticsearch2.log](https://github.com/bitnami/charts/files/11904966/elasticsearch2.log)

**Comment by fkamaliada** [comment]
If I disable credentials it works normally again. I've tried many things, but with no luck.

**Comment by javsalgar** [comment]
Hi,

Could you launch it with `diagnosticMode.enabled=true`, enter the containers and check the environment variables of the password to see if they make sense?

**Comment by corico44** [comment]
I can't reproduce the error @fkamaliada. What values are you using exactly?

**Comment by fkamaliada** [comment]
Thank you @corico44 for your answer.

All deployments and testing are done in a working EKS cluster (kubernetes v.1.27) with secrets enabled.

**Case1:**

values:
```
global:
  kibanaEnabled: true

diagnosticMode:
  enabled: true

clusterName: srate-test

master:
  replicaCount: 1
  masterOnly: true

data:
  replicaCount: 1

coordinating:
  replicaCount: 0

ingest:
 enabled: false

security:
  enabled: true
  elasticPassword: "test4321"
  tls:
    autoGenerated: true
    restEncryption: false

kibana:
  elasticsearch:
    security:
      auth:
        enabled: true
        createSystemUser: true
        kibanaPassword: "test4321"
        elasticsearchPasswordSecret: es-bi-elasticsearch
      tls:
       # Instruct kibana to connect to elastic over https
        enabled: true
        existingSecret: es-bi-elasticsearch-master-crt
        autoGenerated: true
```
Install with:

`helm install es-bi --values es-dev-secure.yaml --render-subchart-notes bitnami/elasticsearch --namespace bebe`

Results:

Master and Data nodes seems to work, but they do not produce any logs. Kibana fails with:

`Back-off restarting failed container kibana in pod es-bi-kibana-64f69848d8-wx5px_bebe(d86db641-64b8-42e1-9101-c0efc065d102)`

And logs: 
```
kibana 08:06:07.03 
kibana 08:06:07.04 Welcome to the Bitnami kibana container
kibana 08:06:07.04 Subscribe to project updates by watching https://github.com/bitnami/containers
kibana 08:06:07.04 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kibana 08:06:07.04 
kibana 08:06:07.04 INFO  ==> ** Starting Kibana setup **
kibana 08:06:07.05 ERROR ==> In order to connect to Elasticsearch via HTTPS, a valid PKCS12 truststore is required.
```

**Comment by fkamaliada** [comment]
Case 2:

```
global:
  kibanaEnabled: true

clusterName: srate-bi

master:
  replicaCount: 1
  masterOnly: true

data:
  replicaCount: 1

coordinating:
  replicaCount: 0

ingest:
 enabled: false

security:
  enabled: true
  elasticPassword: "test4321"
  tls:
    autoGenerated: true
    restEncryption: true

kibana:
  elasticsearch:
    hosts:
    - "es-bi-elasticsearch"
    port: 9200
    security:
      auth:
        enabled: true
        createSystemUser: true
        kibanaPassword: "test4321"
        elasticsearchPasswordSecret: es-bi-elasticsearch
      tls:
        # Instruct kibana to connect to elastic over https
        enabled: true
        existingSecret: es-bi-elasticsearch-master-crt 
        usePemCerts: true
```

It's strange because that worked!!! It's the same values.yaml with that in my first post but then, It didn't working.

The only thing is changed is an AMI update and some AWS plugins update...

So, I think there's no problem anymore.
