### ISSUE TITLE
[bitnami/mongodb] serviceBindings not created for custom users

### ISSUE THREAD

**Issue by jcpunk** [bitnami/charts#17411]
### Name and Version

bitnami/mongodb 13.15.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Helm install with the attached values file

### Are you using any custom parameters or values?

```yaml
architecture: standalone

directoryPerDB: true

useStatefulSet: true

auth:
  rootUser: root
  rootPassword: password
  databases: ["daqconfigdb", "thisone", "and_this"]
  usernames: ["daqconfigdb", "thisone", "and_this"]
  passwords: ["daqconfigdb", "thisone", "and_this"]

serviceBindings:
  enabled: true

persistence:
  enabled: true

metrics:
  enabled: true
  compatibleMode: false # skip old metrics
  username: metrics
  # password:
  collector:
    all: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
  serviceMonitor:
    enabled: true
    labels:
      "prometheus.io/servicemonitor": "dune-metrics"
  prometheusRule: # setup alerting rules here and then enable it
    enabled: false
    rules: []
    additionalLabels:
      "prometheus.io/rule": "dune-metrics"
```

### What is the expected behavior?

Secrets for the service binding should be created:

```shell
kubectl -n mongodb get secret mongodb-svcbind-daqconfigdb
```

### What do you see instead?

```shell
$ kubectl -n mongodb get secrets
NAME                   TYPE                        DATA   AGE
mongodb                Opaque                      3      19m
mongodb-svcbind-root   servicebinding.io/mongodb   8      19m
```

### Additional information

The Secret `mongodb` doesn't appear to have the correct password for the users.
