### ISSUE TITLE
[bitnami/redis-cluster] follower number changed per master != cluster.replicas value

### ISSUE THREAD

**Issue by azhurbilo** [bitnami/charts#17420]
### Name and Version

bitnami/redis-cluster 7.2.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

we got a strange situation when 2 masters restarted at the same time, new masters receives a different number of replicas (3 and 1). expected: 2

<img width="892" alt="image" src="https://github.com/bitnami/charts/assets/6387460/3bf6a2fe-b3ed-4852-a15a-a9133e013ec2">

can not reproduce it. happens from time to time

### Are you using any custom parameters or values?

```yaml
redis-cluster:
  enabled: true
  persistence:
    storageClass: premium-rwo
    size: 10Gi

  service:
    type: NodePort

  cluster:
    nodes: 12 ## (4 master + 8 replicas)
    replicas: 2 ## (each master have 2 replicas )
```

### What is the expected behavior?

as we use "replicas: 2" we expect that the master always has 2 replicas

### What do you see instead?

new master receives different number of replicas (3 and 1)
