### ISSUE TITLE
[bitnami/rabbitmq] feature flag is failing

### ISSUE THREAD

**Issue by Jojoooo1** [bitnami/charts#17433]
### Name and Version

bitnami/rabbitmq 11.16.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When pod is starting it showing the following warn message:

```
[warning] <0.234.0> Feature flags: the previous instance of this node must have failed to write the `feature_flags` file at `/bitnami/rabbitmq/mnesia/rabbit@rabbitmq-0.rabbitmq-headless.messaging.svc.cluster.local-feature_flags`:
[warning] <0.234.0> Feature flags:   - list of previously disabled feature flags now marked as such: [empty_basic_get_metric]
```
![Screenshot from 2023-07-01 11-56-48](https://github.com/bitnami/charts/assets/17641873/c5318e89-1f08-45d8-9aef-4cc532fd7ed6)

### Are you using any custom parameters or values?

```
        - name: clustering.rebalance
          value: "true"

        - name: persistence.storageClass
          value: "standard-rwo"

        - name: auth.existingPasswordSecret
          value: "rabbitmq-secrets"
        - name: auth.existingErlangSecret
          value: "rabbitmq-secrets"

        - name: communityPlugins
          value: "https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.11.1/rabbitmq_delayed_message_exchange-3.11.1.ez"
        - name: extraPlugins
          value: "rabbitmq_management rabbitmq_shovel rabbitmq_shovel_management rabbitmq_delayed_message_exchange"
        - name: loadDefinition.enabled
          value: "true"
        - name: loadDefinition.existingSecret
          value: "intelipoint-rabbitmq-load-definition"

        - name: extraConfiguration
          value: |
            raft.wal_max_size_bytes = 64000000 
            load_definitions = /app/load_definition.json
```

### What is the expected behavior?

It should show the enabled feature flag.

### What do you see instead?

It shows failed message at boot.

**Comment by javsalgar** [comment]
Hi,

Could you share how you deployed the helm chart? Looking at the values it is not clear to me if you are using helm or an operator like flux

**Comment by Jojoooo1** [comment]
Hi, 

Yes that is right, I am using argocd. Here the full yaml:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-messaging
  namespace: argocd

spec:
  project: default
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=background
      - CreateNamespace=true

  source:
    chart: rabbitmq
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: 11.16.2
    helm:
      parameters:

        - name: fullnameOverride
          value: "rabbitmq"

        - name: resources.requests.memory
          value: "1Gi"
        - name: resources.limits.memory
          value: "1Gi"
        - name: resources.requests.cpu
          value: "650m"
        - name: resources.limits.cpu
          value: "1"

        - name: replicaCount
          value: "3"
        - name: pdb.create
          value: "true"
        - name: pdb.minAvailable
          value: "3"

        - name: clustering.rebalance
          value: "true"

        - name: persistence.storageClass
          value: "standard-rwo"
        - name: persistence.size
          value: "10Gi"

        - name: auth.existingPasswordSecret
          value: "rabbitmq-secrets"
        - name: auth.existingErlangSecret
          value: "rabbitmq-secrets"

        - name: communityPlugins
          value: "https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.11.1/rabbitmq_delayed_message_exchange-3.11.1.ez"
        - name: extraPlugins
          value: "rabbitmq_management rabbitmq_shovel rabbitmq_shovel_management rabbitmq_delayed_message_exchange"
        - name: loadDefinition.enabled
          value: "true"
        - name: loadDefinition.existingSecret
          value: "intelipoint-rabbitmq-load-definition"

        - name: extraConfiguration
          value: |
            # Flush current WAL file to a segment file on disk once it reaches 64 MiB in size
            raft.wal_max_size_bytes = 64000000 
            load_definitions = /app/load_definition.json

        - name: metrics.enabled
          value: "true"

        - name: metrics.serviceMonitor.enabled
          value: "true"
        - name: metrics.serviceMonitor.namespace
          value: "messaging"
        - name: metrics.serviceMonitor.labels.release
          value: "observability-kube-prometheus"

        - name: metrics.prometheusRule.enabled
          value: "true"
        - name: metrics.prometheusRule.namespace
          value: "messaging"
        - name: metrics.prometheusRule.additionalLabels.release
          value: "observability-kube-prometheus"

        - name: extraDeploy[0]
          value: |
            apiVersion: v1
            kind: Secret
            metadata:
              name: intelipoint-rabbitmq-load-definition
              namespace: messaging
            data:
              load_definition.json: xxxxxxx

        - name: extraDeploy[1]
          value: |
            apiVersion: v1
            kind: Secret
            metadata:
              name: rabbitmq-secrets
              namespace: messaging
            data:
              rabbitmq-password: xxxxxx
              rabbitmq-erlang-cookie: xxxxxxxx

      values: |
        customLivenessProbe:
          exec:
            command:
              - sh
              - -ec
              - curl -f --user user:$RABBITMQ_PASSWORD 127.0.0.1:15672/api/health/checks/virtual-hosts
          failureThreshold: 6
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 20
        customReadinessProbe:
          exec:
            command:
              - sh
              - -ec
              - curl -f --user user:$RABBITMQ_PASSWORD 127.0.0.1:15672/api/health/checks/local-alarms
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 20
```
