### ISSUE TITLE
[bitnami/postgresql] primary.service.loadBalancerSourceRanges can't handle multi-element arrays

### ISSUE THREAD

**Issue by hashbou** [bitnami/charts#17450]
### Name and Version

bitnami/postgresql

### What architecture are you using?

None

### What steps will reproduce the bug?

The main issue is that given more than one element in the array for primary.service.loadBalancerSourceRanges the outputted template is falsy and can't be deployed. If you use only one element it works perfectly fine.

The affected LOC is https://github.com/bitnami/charts/blob/main/bitnami/postgresql/templates/primary/svc.yaml#L31 and while using helm-playground I could also reproduce it there: 
https://helm-playground.com/#t=LQhQFMA8EMFsAcA24BcACA3htA6AatIgK7gDOOAlgC7iyloC%2BDooQA&v=LQhQEsBcFMFsGcBcACA2gIgGbgE70ugDTLrzQDGA9gHYAm6AuqEA

A possible fix is to use 
https://helm-playground.com/#t=LQhQFMA8EMFsAcA24BcACA3htA6AatIgK7gDOOAlgC7iyloA%2BaVA9gFKksB2aAvr6FBA&v=LQhQEsBcFMFsGcBcACA2gIgGbgE70ugDTLrzQDGA9gHYAm6AuqEA

```
loadBalancerSourceRanges: {{ .Values.primary.service.loadBalancerSourceRanges | toJson }}
```

instead of 

```
loadBalancerSourceRanges: {{ .Values.primary.service.loadBalancerSourceRanges }}
```

Reproduce with: 

With the given values below just run the `helm template` command for the `bitnami/postgresql` chart and see the output with the given error.

### Are you using any custom parameters or values?

```yaml
primary:
    service:
        loadBalancerSourceRanges: 
            - 10.240.0.0/24
            - 10.250.0.0/24
        type: LoadBalancer
```

also tested 

```yaml
primary:
    service:
        loadBalancerSourceRanges: ["10.240.0.0/24", "10.250.0.0/24"]
        type: LoadBalancer
```

### What is the expected behavior?

The helm template should output the following array: 

[10.240.0.0/24, 10.250.0.0/24] 

or:

- 10.240.0.0/24
- 10.250.0.0/24

### What do you see instead?

The output for the LoadBalancerSourceRanges array is the following (notice the missing comma here): 

[10.240.0.0/24 10.250.0.0/24]

### Additional information

While providing only one source range it works perfectly fine. As soon as I provide more than one entries it seems to break.
