### ISSUE TITLE
[bitnami/cassandra] metrics.resources is unused in values.yaml

### ISSUE THREAD

**Issue by Akhalaka** [bitnami/charts#1745]
**Which chart**:

cassandra-4.1.11

**Description**

While the values.yaml file suggests that it is possible to configure the resource requests of the metrics sidecar, it appears that these values go unused leading to an unexpected result.

**Steps to reproduce the issue:**

1. Run: `helm template --set metrics.enabled=true --set metrics.resources.requests.cpu=100m -x templates/statefulset.yaml cassandra-4.1.11.tgz`
Note: this can also be run with additional config or with `helm install` but this seems to be the simplest way to describe the problem

**Describe the results you received:**

Got (pulled out just the metrics container):
```
- name: metrics
  image: docker.io/bitnami/cassandra-exporter:2.3.0-debian-9-r102
  imagePullPolicy: "IfNotPresent"
  ports:
    - name: metrics
      containerPort: 8080
      protocol: TCP
    - name: jmx
      containerPort: 5555
  livenessProbe:
    tcpSocket:
      port: metrics
  readinessProbe:
    httpGet:
      path: /metrics
      port: metrics
    initialDelaySeconds: 20
    timeoutSeconds: 45
```
**Describe the results you expected:**

Expected:
Same as above but with the additional resource section:
```
  resources:
    requests:
      cpu: 100m
```

**Additional information you deem important (e.g. issue happens only occasionally):**

None...appears to need the extra configuration here: https://github.com/bitnami/charts/blob/35f6e7fac28de7969079fc34495fe335391510dc/bitnami/cassandra/templates/statefulset.yaml#L207-L226

I would be happy to make the necessary changes to add the resources configuration assuming this is the expected behavior.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
```
