### ISSUE TITLE
Helm fails when gateway.auth.existingSecret is set

### ISSUE THREAD

**Issue by zstevenson-payments** [bitnami/charts#17468]
### Name and Version

bitnami/grafana-mimir 0.5.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. With `myvals.yaml` as below
2. Run `helm template . -f myvals.yaml`

### Are you using any custom parameters or values?

```
# myvals.yaml
extraDeploy:
- apiVersion: v1
  data:
    htpasswd: dXNlcjokMnkkMTAkVTl1cW5RSDdaVzdaV2JyNzdvV3hDLnh5Qm5Bak40RGJhLjlVdnpFL3ZKOEt1S05qUXJDYnk=
    password: cGFzc3dvcmQ=
  kind: Secret
  metadata:
    name: gateway-secret
gateway:
  auth:
    enabled: true
    existingSecret: gateway-secret
```

### What is the expected behavior?

The `htpasswd` volume in the `grafana-mimir-gateway` deployment should have `secretName: gateway-secret`.

### What do you see instead?

```
Error: template: grafana-mimir/templates/gateway/deployment.yaml:175:27: executing "grafana-mimir/templates/gateway/deployment.yaml" at <include "grafana-mimir.gateway.secretName" .>: error calling include: template: grafana-mimir/templates/_helpers.tpl:27:6: executing "grafana-mimir.gateway.secretName" at <include "" .Values.gateway.auth.existingSecret>: error calling include: template: no template "" associated with template "gotpl"
```
