### ISSUE TITLE
[bitnami/postgresql] : Upgrade Postgres password while using existing secret for password(Randomly generated)

### ISSUE THREAD

**Issue by Hareshraman** [bitnami/charts#17462]
### Name and Version

bitnami/postgresql:12.2.7

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Create an umbrella chart for postgresql with a secret manifest file under the templates folder , the secret file will have the existing keys for adminPasswordKey and userPasswordKey
2. Both these passwords are generated randomly using randomalpha `$password := b64enc ((randAlphaNum 8 | nospace))`
3. The values.yaml of the chart looks something similar to this 

```
global:
    postgresql:
      auth: 
        existingSecret: "postgres-secrets"
        secretKeys:
          adminPasswordKey: "postgres_password"
          userPasswordKey: "postgres_password" 
```

4. Let's say the password generated during my initial installation was `cmFuZG9t` ,now we've made some changes to chart and released another version of the chart calling it v2, now helm template would generate another random password as we are using randalpha, let's say the password generated would be `cMxQZH9t` . This would make changes to the secret on kubernetes result in authentication failure between services and postgres as postgres still expects  `cmFuZG9t` .
5. How do i let postgres know that my password has changed from `cmFuZG9t` to  `cMxQZH9t` for default user postgres.

### Are you using any custom parameters or values?

1. Tried using lifecyclehooks within postgres by running a psql command to alter postgres user password.

### What do you see instead?

1. Authentication failure from services to postgres
2. Postgres still expecting old password although chart has been upgraded.

I might be missing out on a few things .

### Additional information

1. Is there a way that i can let postgres know that password has been changed for a particular user in the form of extra volume Mounts ? such as using volumes which are loaded from a secret value in our case postgres_password and then consuming these volumes as volumeMounts , and whenever kubelet decided to notify postgres that these values have changed postgres automatically changes the password to the updated value.

**Comment by javsalgar** [comment]
Hi,

Please note that the password is set and configured on first run, but the initialization scripts do not change the password on subsequent updates. In our case, we use the `fetch` function to get the previous random value of the secret.

**Comment by Hareshraman** [comment]
Let's consider this scenario where i would like to change the password , after installing postgres . for example , my password has been compromised or There is a need to change it for unknown reasons , does postgres allow this without reinstalling/ redeploying the chart ? 

Can I also change the password of "Postgrespassword" to a value that would be overriden if i were to create an umbrella chart of bitnami postgres ? 

And another thing that i mentioned earlier "In Additional information" , What i noticed was if you were to just create template of the bitnami postgres chart 12.2.7 ,`helm template templates . ` , under the Env in the statefulset.yaml , you would notice a Key named as POSTGRES_PASSWORD_FILE , this is enabled if i were to set `usePasswordFiles: true` in my values.yaml of the chart.

```
 # Authentication
            - name: POSTGRES_PASSWORD_FILE
              value: /opt/bitnami/postgresql/secrets/postgres-password
```
The usePasswordFiles: true is under the auth section 
```
 auth:
    postgresPassword: "postgrespasshere"
    database: dbname
    usePasswordFiles: true
```

And POSTGRES_PASSWORD_FILE is available under volume Mounts and the volume is generated using a secret which is automatically created by postgres if i were to supply a value to postgresPassword 

```
container:
  volumeMounts:
             - name: postgresql-password
              mountPath: /opt/bitnami/postgresql/secrets/
volumes:
        - name: postgresql-password
          secret:
            secretName: mychart-postgres
```

Here the container is mounted with the Volume at this path . so any change to the container will be reflected directly to the pod , and the volume that is loaded is a secret and in turn i am creating the secret as a part of the chart if i put in any value into 

```
auth:
  postgresPassword : "anypassword"

#This is the secret that has been created as mychart-postgres , as i specify the postgresPassword , refer tpl 
```

I hope this helps explaining my scenario ! feel free to comment if you would like more information

**Comment by javsalgar** [comment]
Hi!

In a scenario where this has occured, my advice would be to upgrade the chart in `diagnosticMode.enabled`, there you can perform changes using the `psql` client and then execute helm upgrade again.

At the moment we do not have a feature for automatically updating the password because of the risks associated. Another option could be deploying a sidecar that checks the value of the secret and perform an update using `psql`. However, we do not have anything like that at the moment. It would be greate to hear from the community possible solutions for this.

**Comment by bgalvao** [comment]
I am way late to the party, but I am trying this out

https://itnext.io/manage-auto-generated-secrets-in-your-helm-charts-5aee48ba6918

it's a different answer to this problem

**Comment by vorandrew** [comment]
Why do you change contents of secret at all? After each upgrade I get new password in secret.

If secret does not exists - make it. If it exists - don't touch it. Isn't it obvious?

**Comment by Hareshraman** [comment]
@javsalgar I have a few more questions regarding this issue , I am setting the context for anyone reading this thread again, And as we're almost 9 months ahead , i would like to know if bitnami has any solution to this problem statement. 

1. We have a secret named postgres-chart-secrets 
```  global:
    postgresql:
      auth: 
        existingSecret: "postgres-chart-secrets"
        secretKeys:
          adminPasswordKey: "postgres_password"
          userPasswordKey: "postgres_password"  
```
2. Let's deploy postgres standalone chart , in a kubernetes cluster using my umbrella chart 
3. value of key `postgres_password` in my secret `postgres-chart-secrets` has been rotated to some other value , and has been updated in my branch. Argocd will update the secret values. We are no longer using Randalpha
4. How do i let postgres know hey use my new password ? or is it still the same approach that @javsalgar suggested , by using diagnostic mode. ? 


@vorandrew : We are using a predefined secret in my environment to set it as the password of postgres. Let's say we are using a vault to update the values of our secret/ and create them if they didn't exist. The postgres chart secrets are created during cluster creation as a part of the chart. 
The values are populated using a vault. Now let's imagine we would like to rotate the values due to a breach/compromise of the contents of the secret(which is highly impossible) , But let's just say it happens .. Is there a way that i can just the change the contents of my secret to expect postgres to now start using the latest password for authentication ?

**Comment by javsalgar** [comment]
Hi,

I'm afrad that at the moment, this step is to be done manually or by launhcing an Job that performs the password update.

**Comment by Hareshraman** [comment]
Hey @javsalgar can you elaborate on the job strategy that you've mentioned above ?

**Comment by javsalgar** [comment]
It would be to launch something like this (note that this is a non-tested example), it's just to give you an idea

```
kind: Job
metadata:
  name: postgresql-rotate
  namespace: "default"
  labels:
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: rotate
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: postgresql
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/component: rotate
    spec:      
      serviceAccountName: postgresql
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      affinity:
        podAffinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: mlflow
                    app.kubernetes.io/name: mlflow
                    app.kubernetes.io/component: run
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      containers:
        - name: postgresql
          image: docker.io/bitnami/postgresql
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          command:
            - bash
          args:
            - -ec
            - |
              #!/bin/bash
              PGPASSWORD=$POSTGRES_PASSWORD psql -u postgres --host postgresql -e "ALTER USER postgres with password=$POSTGRES_NEW_PASSWORD'
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
            - name: POSTGRES_NEW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-new-password
                  key: postgres-password
```

If we use helm pre-upgrade hooks, this would be executed prior to updating the release, so the secret `postgresql` would not be updated until the job finishes, and then the upgrade would occur. You would need to create a secret called postgresql-new-password as part of this upgrade (using helm hooks it would be also pre-upgrade and could be deleted automatically after finished). 

In the `extraDeploy` array you could try adding a similar definition, and if this is validated by the community, it could be officially added as a feature to the chart.
