### ISSUE TITLE
 Cannot invoke "kafka.raft.KafkaRaftManager.apiVersions()" because the return value of "kafka.server.SharedServer.raftManager()" is null

### ISSUE THREAD

**Issue by shameoff** [bitnami/charts#17479]
### Name and Version

bitnami/kafka 23.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Using this docker-compose.yml(delete .txt) start first container.
[docker-compose.yml.txt](https://github.com/bitnami/charts/files/11952647/docker-compose.yml.txt)
Or with same credentials run helm chart

### What is the expected behavior?

Sucessful start of Kafka container

### What do you see instead?

`"Cannot invoke "kafka.raft.KafkaRaftManager.apiVersions()" because the return value of "kafka.server.SharedServer.raftManager()" is null"`

### Additional information
```
 [2023-07-04 23:06:35,575] INFO Initialized snapshots with IDs Set() from /bitnami/kafka/data/__cluster_metadata-0 (kafka.raft.KafkaMetadataLog$)
ejudge-infrastructure-kafka-1  | [2023-07-04 23:06:35,579] ERROR [SharedServer id=1] Got exception while starting SharedServer (kafka.server.SharedServer)
ejudge-infrastructure-kafka-1  | org.apache.kafka.common.KafkaException: java.lang.IllegalArgumentException: No serviceName defined in either JAAS or Kafka config
ejudge-infrastructure-kafka-1  |        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184)
ejudge-infrastructure-kafka-1  |        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
ejudge-infrastructure-kafka-1  |        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
ejudge-infrastructure-kafka-1  |        at kafka.raft.KafkaRaftManager.buildNetworkClient(RaftManager.scala:285)
ejudge-infrastructure-kafka-1  |        at kafka.raft.KafkaRaftManager.buildNetworkChannel(RaftManager.scala:253)
ejudge-infrastructure-kafka-1  |        at kafka.raft.KafkaRaftManager.<init>(RaftManager.scala:171)
ejudge-infrastructure-kafka-1  |        at kafka.server.SharedServer.start(SharedServer.scala:247)
ejudge-infrastructure-kafka-1  |        at kafka.server.SharedServer.startForController(SharedServer.scala:129)
ejudge-infrastructure-kafka-1  |        at kafka.server.ControllerServer.startup(ControllerServer.scala:197)
ejudge-infrastructure-kafka-1  |        at kafka.server.KafkaRaftServer.$anonfun$startup$1(KafkaRaftServer.scala:95)
ejudge-infrastructure-kafka-1  |        at kafka.server.KafkaRaftServer.$anonfun$startup$1$adapted(KafkaRaftServer.scala:95)
ejudge-infrastructure-kafka-1  |        at scala.Option.foreach(Option.scala:407)
ejudge-infrastructure-kafka-1  |        at kafka.server.KafkaRaftServer.startup(KafkaRaftServer.scala:95)
ejudge-infrastructure-kafka-1  |        at kafka.Kafka$.main(Kafka.scala:113)
ejudge-infrastructure-kafka-1  |        at kafka.Kafka.main(Kafka.scala)
ejudge-infrastructure-kafka-1  | Caused by: java.lang.IllegalArgumentException: No serviceName defined in either JAAS or Kafka config
ejudge-infrastructure-kafka-1  |        at org.apache.kafka.common.security.kerberos.KerberosLogin.getServiceName(KerberosLogin.java:303)
ejudge-infrastructure-kafka-1  |        at org.apache.kafka.common.security.kerberos.KerberosLogin.configure(KerberosLogin.java:92)
ejudge-infrastructure-kafka-1  |        at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:61)
ejudge-infrastructure-kafka-1  |        at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:112)
ejudge-infrastructure-kafka-1  |        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:170)
ejudge-infrastructure-kafka-1  |        ... 14 more
ejudge-infrastructure-kafka-1  | [2023-07-04 23:06:35,582] INFO [ControllerServer id=1] Waiting for controller quorum voters future (kafka.server.ControllerServer)
ejudge-infrastructure-kafka-1  | [2023-07-04 23:06:35,582] INFO [ControllerServer id=1] Finished waiting for controller quorum voters future (kafka.server.ControllerServer)
ejudge-infrastructure-kafka-1  | [2023-07-04 23:06:35,583] ERROR Encountered fatal fault: caught exception (org.apache.kafka.server.fault.ProcessTerminatingFaultHandler)
ejudge-infrastructure-kafka-1  | java.lang.NullPointerException: Cannot invoke "kafka.raft.KafkaRaftManager.apiVersions()" because the return value of "kafka.server.SharedServer.raftManager()" is null
ejudge-infrastructure-kafka-1  |        at kafka.server.ControllerServer.startup(ControllerServer.scala:210)
ejudge-infrastructure-kafka-1  |        at kafka.server.KafkaRaftServer.$anonfun$startup$1(KafkaRaftServer.scala:95)
ejudge-infrastructure-kafka-1  |        at kafka.server.KafkaRaftServer.$anonfun$startup$1$adapted(KafkaRaftServer.scala:95)
ejudge-infrastructure-kafka-1  |        at scala.Option.foreach(Option.scala:407)
ejudge-infrastructure-kafka-1  |        at kafka.server.KafkaRaftServer.startup(KafkaRaftServer.scala:95)
ejudge-infrastructure-kafka-1  |        at kafka.Kafka$.main(Kafka.scala:113)
ejudge-infrastructure-kafka-1  |        at kafka.Kafka.main(Kafka.scala)
```

**Comment by shameoff** [comment]
I think it's may be more understandable with values.yaml from my chart. The error is same
```yaml
kafka:
  image:
    debug: true
  replicaCount: 1
  autoCreateTopicsEnable: true
  deleteTopicEnable: true
  listeners: INTERNAL://:9092,CLIENT://:9093,CONTROLLER://:9094
  interBrokerListenerName: INTERNAL
  listenerSecurityProtocolMap: INTERNAL:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT
  advertisedListeners: INTERNAL://kafka:9092,CLIENT://kafka:9093
  config:
  auth:
    clientProtocol: sasl
    controllerProtocol: sasl
    sasl:
      mechanisms: plain,
      interBrokerMechanism: plain
      jaas:
        clientUsers: ["ejudge"]
        clientPasswords: ["ejudge123"]
  service:
    ports:
      client: 9093
      internal: 9092
      controller: 9094
  kraft:
    enabled: true
    controllerListenerNames: CONTROLLER
    processRoles: controller,broker
```
