### ISSUE TITLE
[bitnami/postgresql] parse error at (postgresql/templates/_helpers.tpl:164): unclosed action

### ISSUE THREAD

**Issue by GaryGlobality** [bitnami/charts#17488]
### Name and Version

bitnami/postgresql

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Using Skaffold to deploy with helm:

```
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: infra
build:
  local: {}
deploy:
  helm:
    releases:
    - name: postgres
      remoteChart: postgresql
      repo: https://charts.bitnami.com/bitnami
      namespace: "{{ .NAMESPACE_NAME }}"
      createNamespace: true
      valuesFiles:
        - skaffold/postgres_values.yaml
```

`skaffold run -f skaffold/infra.yaml`

### Are you using any custom parameters or values?

Values:

```
image:
  tag: 11
primary:
  pgHbaConfiguration: |-
    host     all             all             0.0.0.0/0               trust
    host     all             all             ::/0                    trust
    local    all             all                                     trust
    host     all             all        127.0.0.1/32                 trust
    host     all             all        ::1/128                      trust
  persistence:
    size: 500Mi
```

### What is the expected behavior?

There should not be a parse error.

### What do you see instead?

`Error: parse error at (postgresql/templates/_helpers.tpl:164): unclosed action`

### Additional information

Possibly related to https://github.com/bitnami/charts/issues/17472
