### ISSUE TITLE
[bitnami/postgresql]: 'common.secrets.lookup': Argument 'defaultValue' missing or empty

### ISSUE THREAD

**Issue by kr4sv** [bitnami/charts#17503]
### Name and Version

bitnami/postgresql 12.6.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We're using postgresql as part of an umbrella chart with a postgres admin password passed as existing secret value.

Up until 12.5.8, the values below have been working fine.
Version 12.6.2 however fails to render with the following message: `execution error at (<umbrella-chart>/charts/my-postgresql/charts/postgresql/templates/secrets.yaml:9:25): 'common.secrets.lookup': Argument 'defaultValue' missing or empty`

Possibly related to `https://github.com/bitnami/charts/commit/262f4f1d2906226cee8cabb49c8fedf97ecc30e4#diff-00f2e1e3c249371477aae086aa0c058d3e8e34d7045398f5d558d34840cef2e1` ?

### Are you using any custom parameters or values?

Here are my values:
```yaml
postgresql:
  enabled: true
  fullnameOverride: my-postgresql
  auth:
    enablePostgresUser: true
    existingSecret: "my-secret-name"
    secretKeys:
      adminPasswordKey: postgresPassword
```
### What is the expected behavior?

postgresql being deployed without rendering issues.

### What do you see instead?

Helm error rendering the secrets.yaml:
```
execution error at (<umbrella-chart>/charts/my-postgresql/charts/postgresql/templates/secrets.yaml:9:25): 'common.secrets.lookup': Argument 'defaultValue' missing or empty
```
