### ISSUE TITLE
Alertmanager not triggering email alerts

### ISSUE THREAD

**Issue by RomainCruciani** [bitnami/charts#17521]
### Name and Version

bitnami/kube-prometheus 8.13.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

After running : 
`helm install my-release oci://registry-1.docker.io/bitnamicharts/kube-prometheus`

And creating a `PrometheusRule` resource : 
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-example-rules
  namespace: prometheus
spec:
  groups:
    - name: ./example.rules
      rules:
        - alert: ExampleAlert
          expr: vector(1)
```

And creating an `AlertmanagerConfig` resource : 
```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-example
  namespace: prometheus
spec:
  route:
    receiver: 'gmail-notifications'
  receivers:
    - name: 'gmail-notifications'
      emailConfigs:
        - to: xxx@gmail.com
          from: xxx@gmail.com
          smarthost: smtp.gmail.com:587
          authUsername: xxx@gmail.com
          authIdentity: xxx@gmail.com
          authPassword:
            name: alertmanager-email-secret
            key: authPassword
          sendResolved: true
```

### What is the expected behavior?

I expect to receive email notifications when an alert triggers.

### What do you see instead?

Alerts seems to be triggered in Prometheus, but no email is sent : 
![Screenshot from 2023-07-07 15-04-57](https://github.com/bitnami/charts/assets/93149313/b1fbb85e-6c71-4b5f-8447-a19e45126a4d)
![Screenshot from 2023-07-07 15-05-11](https://github.com/bitnami/charts/assets/93149313/d3adf953-785a-4888-bfa0-21b6803c2d40)
![Screenshot from 2023-07-07 15-05-33](https://github.com/bitnami/charts/assets/93149313/02b9516e-7c9f-4266-ad0f-f9e7b8aa57b9)

**Comment by RomainCruciani** [comment]
It seems the `AlertmanagerConfig` resource is not picked up by the system. It does not trigger configuration reloads in any component.

When configuring alertmanager using a configMap, then it works fine (with the exact same alert definition and alertmanager config).

**Comment by andresbono** [comment]
Hi @RomainCruciani, you need to connect your Alertmanager instance with the AlertmanagerConfig resources. It can be done with the `.alertmanager.configSelector` Helm chart value. You can pass it when installing the chart:

```yaml
alertmanager:
  configSelector:
    matchLabels:
      alertmanagerConfig: my-release-extra-config
```

And then when you create your AlertManagerConfig, you set that label:

```diff
@@ -3,6 +3,8 @@ kind: AlertmanagerConfig
 metadata:
   name: config-example
   namespace: prometheus
+  labels:
+    alertmanagerConfig: my-release-extra-config
 spec:
   route:
     receiver: 'gmail-notifications'
```

Steps to test it:

```shell
helm install --create-namespace --namespace prometheus my-release oci://registry-1.docker.io/bitnamicharts/kube-prometheus --version 8.13.0 --set alertmanager.configSelector.matchLabels.alertmanagerConfig=my-release-extra-config

# Create your CRDs
cat <<EOF | kubectl create -f -
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-example-rules
  namespace: prometheus
spec:
  groups:
    - name: ./example.rules
      rules:
        - alert: ExampleAlert
          expr: vector(1)
EOF
cat <<EOF | kubectl create -f -
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-example
  namespace: prometheus
  labels:
    alertmanagerConfig: my-release-extra-config
spec:
  route:
    receiver: 'gmail-notifications'
  receivers:
    - name: 'gmail-notifications'
      emailConfigs:
        - to: xxx@gmail.com
          from: xxx@gmail.com
          smarthost: smtp.gmail.com:587
          authUsername: xxx@gmail.com
          authIdentity: xxx@gmail.com
          authPassword:
            name: alertmanager-email-secret
            key: authPassword
          sendResolved: true
EOF
kubectl --namespace prometheus create secret generic alertmanager-email-secret --from-literal=authPassword=xxx

# Expose the service and check the logs to notice config reloading
kubectl --namespace prometheus port-forward svc/alertmanager-operated 9093:9093
kubectl --namespace prometheus logs -f deploy/my-release-kube-prometheus-operator
# Go to http://127.0.0.1:9093/#/status
```

![image](https://github.com/bitnami/charts/assets/1057973/d053e0f4-b212-4cfc-b4ef-440be749af48)
