### ISSUE TITLE
[bitnami/mongodb] Unable to start with architecture as replicaset and service as LoadBalancer

### ISSUE THREAD

**Issue by IrfanSyed-PSC** [bitnami/charts#17531]
### Name and Version

bitnami/mongodb 6.0.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When I run the helm chart with architecture as replicaset and service type as LoadBalancer, it does not show headless svc in LoadBalancer mode. Instead it shows both arbiter and headless service in ClusterIP mode. Here is the config used
```
mongodb:
  architecture: replicaset

service:
  type: LoadBalancer
  headless:
    enabled: true

replicaSet:
  enabled: true
  replicas: 3
```

### Are you using any custom parameters or values?
```
mongodb:
  architecture: replicaset

service:
  type: LoadBalancer
  headless:
    enabled: true

replicaSet:
  enabled: true
  replicas: 3
```

### What is the expected behavior?

services to be started in LoadBalancer mode

### What do you see instead?

services are started in clusterip mode
