### ISSUE TITLE
airflow cannot perform initial repositories clone

### ISSUE THREAD

**Issue by kiela** [bitnami/charts#17543]
### Name and Version

bitnami/airflow:14.3.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create chart directory and enter into the directory:
```
mkdir airflow
cd airflow
```
2. Create chart YAML file:
```console
$ cat <<EOF> Chart.yaml
apiVersion: v2
name: airflow
version: 0.0.1
dependencies:
  - name: airflow
    version: 14.3.0
    repository: "@bitnami"
EOF
```
3. Create custom `values.yaml`:
```console
$ cat <<EOF> values.yaml
airflow:
  nameOverride: airflow
  fullnameOverride: airflow

  git:
    dags:
      enabled: true
      repositories:
        - repository: https://github.com/apache/airflow.git
          name: example_dags
          branch: main
          paths: /airflow/example_dags
EOF
```
4. Build chart dependency:
```
helm dependency build
```
5. Install chart:
```
helm install airflow . --namespace airflow --create-namespace -f values.yaml
```

### Are you using any custom parameters or values?

```yaml
airflow:
  nameOverride: airflow
  fullnameOverride: airflow

  git:
    dags:
      enabled: true
      repositories:
        - repository: https://github.com/apache/airflow.git
          name: example_dags
          branch: main
          paths: /airflow/example_dags
```

### What is the expected behavior?

`clone-repositories` init container of `airflow-scheduler` pod clones  `/airflow/example_dags` from `main` branch of `https://github.com/apache/airflow.git` repository into `/dags/example_dags` directory.

### What do you see instead?

`clone-repositories` init container crashes with `CrashLoopBackOff` message causing `airflow-scheduler` pod to crash with `Init:CrashLoopBackOff` message.

### Additional information

After initial investigation, I was able to find the cause of this bug. Unfortunately, the `clone-repositories` init container uses the same `securityContext` as other containers from the `airflow-scheduler` pod effectively setting UID as 1001. Changes from https://github.com/bitnami/containers/commit/73f36339d9fbad1e3757b6920695018ca9cf2f5c are run as UID 1001 and try to generate SSH keys by default. UID 1001 does not exist in `clone-repositories` container causing `ssh-keygen` from `/opt/bitnami/scripts/git/entrypoint.sh` script to fail silently due to `>/dev/null 2>&1` inside the script.
