### ISSUE TITLE
[grafana-operator]: ingress configuration in Grafana instance is incorrect

### ISSUE THREAD

**Issue by portswigger-tim** [bitnami/charts#17554]
### Name and Version

bitnami/grafana-operator:3.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. attempt to template, diff or install the chart with `grafana.ingress.enabled`

### What is the expected behavior?

Expected to create a template with:
```yaml
  ingress:
    spec:
      ingressClassName: nginx
      rules:
        - host: test.io
          http:
            paths:
              - backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
 ```
 
 See: https://github.com/grafana-operator/grafana-operator/blob/master/examples/ingress_http/resources.yaml

### What do you see instead?

Creates a template with:
```yaml
    ingress:
      spec:
        ingressClassName: nginx
        tlsEnabled: false
        tlsSecretName: grafana.local-tls
        rules:
          host: test.io
          - http:
            paths:
              - path: /
              - pathType: ImplementationSpecific
```
