### ISSUE TITLE
[bitnami/external-dns] do not set pod annotation to null

### ISSUE THREAD

**Issue by FlorisFeddema** [bitnami/charts#17562]
### Name and Version

bitnami/external-dns

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We deploy External-dns with ArgoCD and have autosync enabled.
When doing a restart of the external-dns deployment kubectl add the `kubectl.kubernetes.io/restartedAt` annotation to the pod spec. When the pod has pod spec has no other annotations this field should not be included.

The chart currently sets the pod spec annotation to null when there is no addition annotation given while it should leave the field empty.

1. Deploy external-dns via Argocd with autosync enabled
2. Kubectl rolllout restart deployement external-dns
3. New replicaset and pods will be remove instantly

### What is the expected behavior?
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: externaldns-external-dns
  namespace: externaldns
spec:
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: ""
```
### What do you see instead?
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: externaldns-external-dns
  namespace: externaldns
spec:
  template:
    metadata:
      annotations: null
```
