### ISSUE TITLE
[bitnami/mongodb] Unable to pass vault credentials in mongodb

### ISSUE THREAD

**Issue by ahsan-n** [bitnami/charts#17561]
### Name and Version

bitnami/mongodb

### What architecture are you using?

None

### What steps will reproduce the bug?

trying to add root username and password from vault using the config:

```yaml
podAnnotations:
  vault.hashicorp.com/agent-inject: 'true'
  vault.hashicorp.com/role: 'mongo'
  vault.hashicorp.com/agent-inject-secret-mongo-config: 'internal/data/mongo/config'
  vault.hashicorp.com/agent-inject-status: 'update'

  vault.hashicorp.com/agent-inject-template-mongo-config: |
    {{`{{- with secret "internal/data/mongo/config" -}}
      export MONGODB_ROOT_PASSWORD={{ .Data.data.password }}
      export MONGODB_ROOT_USER={{ .Data.data.user }}
    {{- end }}`}}

command: ['/bin/bash', '-c', ]
## @param args Override default container args (useful when using custom images)
args: ['source /vault/secrets/mongo-config && /opt/bitnami/scripts/mongodb/entrypoint.sh /opt/bitnami/scripts/mongodb/run.sh']
```

I can see in init container that credentials are being injected but when I do env in container I see no effect in env variables. Wondering what I am doing wrong and what is the right wayt to inject variables

### What is the expected behavior?

MONGODB_ROOT_USER=myadmin

env should be this 👆 

### What do you see instead?

```env
I have no name!@mongo-mongodb-6d698ccf9c-9rmt5:/$ env
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_PORT=443
HOSTNAME=mongo-mongodb-6d698ccf9c-9rmt5
PWD=/
OS_FLAVOUR=debian-11
MONGODB_DISABLE_SYSTEM_LOG=no
MONGO_MONGODB_PORT_27017_TCP=tcp://10.100.217.59:27017
HOME=/
MONGODB_ROOT_USER=root
KUBERNETES_PORT_443_TCP=tcp://10.100.0.1:443
MONGO_MONGODB_PORT=tcp://10.100.217.59:27017
MONGODB_ENABLE_IPV6=no
BITNAMI_DEBUG=false
MONGODB_PORT_NUMBER=27017
MONGO_MONGODB_SERVICE_HOST=10.100.217.59
TERM=xterm
MONGO_MONGODB_SERVICE_PORT_MONGODB=27017
SHLVL=1
KUBERNETES_PORT_443_TCP_PROTO=tcp
BITNAMI_APP_NAME=mongodb
KUBERNETES_PORT_443_TCP_ADDR=10.100.0.1
MONGODB_ENABLE_JOURNAL=yes
MONGO_MONGODB_PORT_27017_TCP_PORT=27017
MONGO_MONGODB_SERVICE_PORT=27017
MONGODB_ROOT_PASSWORD=cOPiQiLIdc
MONGODB_ENABLE_DIRECTORY_PER_DB=no
APP_VERSION=6.0.7
MONGODB_SYSTEM_LOG_VERBOSITY=0
MONGODB_DISABLE_JAVASCRIPT=no
ALLOW_EMPTY_PASSWORD=no
KUBERNETES_SERVICE_HOST=10.100.0.1
KUBERNETES_PORT=tcp://10.100.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
OS_NAME=linux
PATH=/opt/bitnami/mongodb/bin:/opt/bitnami/common/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MONGO_MONGODB_PORT_27017_TCP_PROTO=tcp
MONGO_MONGODB_PORT_27017_TCP_ADDR=10.100.217.59
OS_ARCH=amd64
_=/usr/bin/env
```

### Additional information
I refered this #https://github.com/hashicorp/vault-helm/issues/816#issuecomment-1344672808 but no help

**Comment by javsalgar** [comment]
Hi,

Could you confirm that the file is created? In principle the commands seem correct to me.

**Comment by ahsan-n** [comment]
yes file is created, but whenever i log in i get the automated credentials in env

**Comment by javsalgar** [comment]
Could you also confirm that it is not using leftover credentials from a previous installation?

**Comment by tripod70** [comment]
Any updates?

**Comment by javsalgar** [comment]
Do you have a similar bug? Could you confirm there are no leftovers from previous installations?

**Comment by tripod70** [comment]
Hi. Thank you for fast response!
I'm not installing fresh instance. Like a topicstarter I've added vault annotations to inject secrets and defined non default "command" section in values

```
values:
    command: ["/bin/sh", "-c", "/vault/secrets/config && /scripts/setup.sh"]
...
    arbiter:
      command: ["/bin/sh", "-c", "/vault/secrets/config && /opt/bitnami/scripts/mongodb/entrypoint.sh"] 
```

mongodb-arbiter container logs:
```
mongodb 10:57:47.19 INFO  ==>
mongodb 10:57:47.19 INFO  ==> Welcome to the Bitnami mongodb container
mongodb 10:57:47.19 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 10:57:47.19 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 10:57:47.20 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packag
mongodb 10:57:47.20 INFO  ==>
/opt/bitnami/scripts/mongodb/entrypoint.sh: line 27: $1: unbound variable
Stream closed EOF for fraudaverse/mongodb-arbiter-0 (mongodb-arbiter)
```
