### ISSUE TITLE
podAntiAffinityPreset does not work

### ISSUE THREAD

**Issue by Jean-PhilippeD** [bitnami/charts#17588]
### Name and Version

bitnami/rabbitmq7.6.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

With a cluster Kubenetes v1.25.6 with 8 nodes.
With the chart rabbitmq 7.6.8

**values.yaml**:
```yaml
rabbitmq:
  fullnameOverride: rabbitmq
  replicaCount: 3
  global:
    imagePullSecrets:
    - regcred
    storageClass: nfs-client
  podAntiAffinityPreset: soft
  image:
    registry: ....
    repository: myrepo/rabbitmq
    tag: 3.8.9
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    storageClass: nfs-client
  ...etc
```

### Are you using any custom parameters or values?

podAntiAffinityPreset: soft

### What is the expected behavior?

The doc says the policy is already **soft** by default but even with the specific values, I would expect the pods deploys on different node if possible.

### What do you see instead?

In my production cluster my 3 pods are on the same node.
With the value set in values.yaml I don't see anything about the podAntiAffinity parameters in my pod description when I do a kubectl describe on my pod, even when I trie to edit the configuration in yaml.
