### ISSUE TITLE
[bitnami/keycloak] Nginx ingress connection refused to Keycloak instance

### ISSUE THREAD

**Issue by topeawolwo** [bitnami/charts#17584]
### Name and Version

keycloak-15.1.6, keycloak- App version is : 21.1.2

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I had set up Nginix ingress

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloaka-ingress
  annotations:
    kubernetes.io/ingress.class: "bitnami-internal"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-url: "http://127.0.0.1:8085/realms/argocd/protocol/openid-connect/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://127.0.0.1:8085/realms/argocd/protocol/openid-connect/auth"
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization"
spec:
  rules:
  - host: keycloak.local
    http:
      paths:
      - path: /account(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: oxygena-test-keycloak
            port:
              number: 8085


```
```
➜  ~ kubectl get ing               
NAME               CLASS    HOSTS            ADDRESS     PORTS   AGE
keycloak-ingress   <none>   keycloak.local   localhost   80      58s

My macos  nano /etc/hosts has 127.0.0.1       keycloak.local
```
```
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
127.0.0.1       keycloak.local
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section

```

my Keycloak is running on http://127.0.0.1:8085

### Are you using any custom parameters or values?

no

### What is the expected behavior?

successful keycloak redirect with ArgoCD

### What do you see instead?
```
Failed to query provider "http://localhost:8085/admin/master/": Get "http://localhost:8085/admin/master/.well-known/openid-configuration": dial tcp 127.0.0.1:8085: connect: connection refused
```
