### ISSUE TITLE
[bitnami/jupyterhub] add profileList as input option to singleuser

### ISSUE THREAD

**Issue by wakafa** [bitnami/charts#17590]
### Name and Version

bitnami/jupyterhub-4.1.4

### What is the problem this feature will solve?

Currently, there is no support for profileList input to singleuser instance at values - profileList input will have no effect 

```yaml
singleuser:
  profileList:
    - display_name: "minimal-notebook (Python 3)"
      description: "Limit: CPU 1, Memory 2G"
    - display_name: "scipy-notebook (Python 3, pandas, scikit-learn)"
      description: "Limit: CPU 1, Memory 2G"
      kubespawner_override:
        image: jupyter/tensorflow-notebook:83ed2c63671f
        cpu_limit: 1
        mem_limit: '2G'
  image:
    registry: docker.io
    repository: bitnami/jupyter-base-notebook
    tag: 4.0.0-debian-11-r5
    digest: ""
```

### What is the feature you are proposing to solve the problem?

Allow the chart to parse 'profileList' attribute alongside others that already exist (like extravolumes, sidecars etc)

### What alternatives have you considered?

Currently, I have found no way of using jupyterhub via bitnami if I want to support profileList to my users.
