### ISSUE TITLE
[bitnami/minio] add https schema support for ServiceMonitor endpoint

### ISSUE THREAD

**Issue by zagr0** [bitnami/charts#17708]
### Name and Version

bitnami/minio 12.6.6

### What is the problem this feature will solve?

When TLS is enabled for minio with values:
```yaml
tls:
  enabled: true
  autoGenerated: true
metrics:
  serviceMonitor:
    enabled: true
```
ServiceMonitor resource does not set `schema: https` for the endpoint and there are no values to provide such schema config in to the spec. As a result prometheus targets are down with 400 error, http is used by default.

### What is the feature you are proposing to solve the problem?

Could you please add either ServiceMonitor spec `schema: https` in case of TLS is enabled or add corresponding `metrics.serviceMonitor.schema` config in values
Also would be great to have ability to customize `tlsConfig`.
