### ISSUE TITLE
[bitnami/redis-cluster] taints/affinity for redis master and replicas pods

### ISSUE THREAD

**Issue by vladsf** [bitnami/charts#17712]
### Name and Version

bitnami/redis-cluster 8.6.7

### What is the problem this feature will solve?

Redis cluster in default configuration might place master and replics on the same k8s node.
E.g. if I have 6 k8s nodes how do I place pods on different nodes so master and replicas do not reside on the same node?

### What is the feature you are proposing to solve the problem?

Cluster reliability

### What alternatives have you considered?

Otherwise it is just Sentinel in a nutshell.

**Comment by fmulero** [comment]
Hi @vladsf 

Default configuration uses this affinity term to avoid scheduling several redis pods in the same node, but the weight is very low it is only a "best effort":
```yaml
  affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: redis-cluster
                app.kubernetes.io/name: redis-cluster
            topologyKey: kubernetes.io/hostname
          weight: 1
```

To enforce this rule, you can set the value `redis.podAntiAffinityPreset=hard` and every pod will be scheduled in a different node.

Also you can set your own affinity rules according to your needs in the `redis-cluster` statefulset, but unfortunately, at kubernetes level, there is no way at the moment to distinguish between a master and its replica pods, so you can not set a concrete rule to avoid scheduling them on the same node.
