### ISSUE TITLE
postgresql: Error during `helm diff` but not `helm upgrade`

### ISSUE THREAD

**Issue by NfNitLoop** [bitnami/charts#17717]
### Name and Version

bitnami/postgresql 12.6.5 (and 12.2.2)

### What architecture are you using?

arm64

### What steps will reproduce the bug?

In any environment (I assume?) 

With a config like:
```yaml
postgresql:
  primary:
    persistence:
      enabled: true
  auth:
    existingSecret: postgres-creds
    username: foo
 ```

run `helm install` to install the chart, then `helm upgrade` to upgrade it.  Both should work.

However, if I run `helm diff`, I get this error:
```
  Error: Failed to render chart: exit status 1: Error: execution error at (user/charts/postgresql/templates/secrets.yaml:18:16):
  PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                   Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                   Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases
```

But I *have* specified the secrets to use. The `existingSecret`, which has both the password for `foo` (with key `password`) and the postgresql user (key: `postgres-password`)

### What is the expected behavior?

`helm diff` shouldn't give an error.

Unfortunately my helm knowledge isn't enough to know whether this is a bug with `helm diff` or with the `postgresql` chart, but only the postgresql chart (among several others) is having this problem, so it seems like the likely candidate here.

### What do you see instead?

The error message above. 😊 

### Additional information

Just for some context: My team recently moved to using `helmfile`, and it does a `helm diff` before an upgrade, which is when we started running into this issue. ~~I don't see a way in `helmfile` to skip that step, so this means we can't `bitnami/postgresql` with `helmfile` reliably.~~ (Update:)  `helmfile sync` will apply the update without doing a `helm diff`, so that's a workaround for us for now. But it would be nice if `helm diff` would work so we can use `helmfile apply`.

**Comment by NfNitLoop** [comment]
> Are you providing the values when upgrading?

The values are in a larger chart that includes the postgresql chart like so:
```yaml
# Chart.yaml
# [...]

dependencies:
  - name: postgresql
    version: 12.2.2
    repository: https://charts.bitnami.com/bitnami
```

We specify the values for the postgresql chart like so in values.yaml:

```yaml
postgresql:
  primary:
    persistence:
      enabled: true
  auth:
    existingSecret: postgres-creds
    username: foo
```

They seem to be getting passed correctly on `upgrade`, because that's been working for us.  It's `helm diff` that's failing.
