### ISSUE TITLE
[bitnami/elasticsearch] missing env var `DB_ENABLE_FIPS_MODE`

### ISSUE THREAD

**Issue by NKID00** [bitnami/charts#17755]
### Name and Version

bitnami/elasticsearch:8.8.2-debian-11-r16

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install `bitnami/elasticsearch` Helm Chart version 19.10.4.

### Are you using any custom parameters or values?

The chart is installed with the following values:

```yaml
image:
  tag: 8.8.2-debian-11-r16
security:
  enabled: true
  elasticPassword: <PASSWORD>
  tls:
    autoGenerated: true
master:
  masterOnly: false
  replicaCount: 1
  persistence:
    enabled: false
data:
  replicaCount: 1
coordinating:
  replicaCount: 1
ingest:
  replicaCount: 1
metrics:
  enabled: false
```

### What do you see instead?

All pods goes into CrashLoopBackOff state with the following error:

```
/opt/bitnami/scripts/libelasticsearch.sh: line 730: DB_ENABLE_FIPS_MODE: unbound variable
```

### Additional information

Providing the env var manually solves the problem:

```diff
 image:
   tag: 8.8.2-debian-11-r16
 security:
   enabled: true
   elasticPassword: 5fQ6uo2dy81Cl1DU
   tls:
     autoGenerated: true
+extraEnvVars:
+  - name: DB_ENABLE_FIPS_MODE
+    value: "false"
 master:
   masterOnly: false
   replicaCount: 1
   persistence:
     enabled: false
 data:
   replicaCount: 1
 coordinating:
   replicaCount: 1
 ingest:
   replicaCount: 1
 metrics:
   enabled: false

```

It seems that the script `elasticsearch-env.sh` did not export the `DB_ENABLE_FIPS_MODE` env var properly.
