### ISSUE TITLE
usePasswordFiles does not work as expected

### ISSUE THREAD

**Issue by renexu** [bitnami/charts#17762]
### Name and Version

bitnami/postgresql 12.6.5

### What architecture are you using?

None

### What steps will reproduce the bug?

```yaml
auth:
  postgresPassword: foobar
  usePasswordFiles: true
```

### What is the expected behavior?

the postgresql should up and running

### What do you see instead?

```
postgresql 22:14:27.98 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 22:14:27.98 ERROR ==> The POSTGRESQL_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.
postgresql 22:14:27.98 ERROR ==> The POSTGRESQL_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.
```

### Additional information

the way to make it work is by adding below to values.yaml

```yaml
  extraEnvVars:
    - name: POSTGRESQL_PASSWORD_FILE
      value: /opt/bitnami/postgresql/secrets/postgres-password
```
