### ISSUE TITLE
[bitnami/grafana-operator]: templating error when setting ingress

### ISSUE THREAD

**Issue by MShekow** [bitnami/charts#17800]
### Name and Version

bitnami/grafana-operator 3.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When running `helm template my-release oci://registry-1.docker.io/bitnamicharts/grafana-operator --version=3.0.3 -f values.yaml`

### Are you using any custom parameters or values?

```yaml
grafana:
  ingress:
    enabled: true
```

### What is the expected behavior?

Templating generates YAML files without throwing an error.

### What do you see instead?

I get the following error:

```
Error: YAML parse error on grafana-operator/templates/grafana.yaml: error converting YAML to JSON: yaml: line 44: did not find expected key
```

### Additional information

We are using Helm 3.10.0.

Note that the error changes, depending on the used values.yaml. For a `values.yaml` such as this:

```yaml
grafana:
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 80Mi

  replicaCount: 1

  envFrom:
    - secretRef:
        name: grafana-secrets

  ingress:
    enabled: true
```

the error becomes `Error: YAML parse error on grafana-operator/templates/grafana.yaml: error converting YAML to JSON: yaml: line 47: did not find expected key` (different line number).

And for this `values.yaml`:

```yaml
grafana:
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 80Mi

  replicaCount: 1

  envFrom:
    - secretRef:
        name: grafana-secrets

  ingress:
    enabled: true
    ingressClassName: 'nginx'
    hostname: foo
    tls: true

  persistence:
    enabled: true
    storageClass: 'managed-csi-premium'
    size: 100Gi
```
the error becomes `Error: YAML parse error on grafana-operator/templates/grafana.yaml: error converting YAML to JSON: yaml: line 58: did not find expected key` (again another line number)
