### ISSUE TITLE
No version of minio starts (Kubernetes + glasterfs)

### ISSUE THREAD

**Issue by a1xs** [bitnami/charts#17813]
### Name and Version

bitnami/minio --version 11.10.18

### What architecture are you using?

amd64

### What steps will reproduce the bug?

value.yaml
```yaml
image:
  debug: true
global:
  storageClass: "glusterfs-client"
auth:
  rootUser: h52mz4PJMxE
  rootPassword: TGGlFuX0cCTBW
ingress:
  enabled: true
  hostname: minio.dev
persistence:
  size: 5Gi
volumePermissions:
  enabled: true
```

### What do you see instead?
```
Error: invalid argument (syscall.Errno)
6: internal/logger/logger.go:258:logger.LogIf()
5: cmd/storage-errors.go:165:cmd.osErrToFileErr()
4: cmd/xl-storage.go:2432:cmd.(*xlStorage).RenameData()
3: cmd/xl-storage-disk-id-check.go:418:cmd.(*xlStorageDiskIDCheck).RenameData()
2: cmd/erasure-object.go:815:cmd.renameData.func1()
1: github.com/minio/pkg@v1.7.5/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to initialize config system: Storage resources are insufficient for the write operation .minio.sys/config/config.json)
```
### Additional information

If I change `mountPath: /data/` to `/data_minio/` it starts up and works, but the data will not be saved when the pod is restarted.
