### ISSUE TITLE
[bitnami/postgresql-ha] Postgresql standby server in a restart loop while trying to replicate huge database

### ISSUE THREAD

**Issue by regmish** [bitnami/charts#17838]
### Name and Version

bitnami/postgresql-ha@11.7.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Chart Version: 11.7.6
Install the chart with the following values.yaml
`helm install postgresql-ha oci://registry-1.docker.io/bitnamicharts/postgresql-ha`

After that I did inserted millions of records in bunch of tables, which took around `~59GB`

**Main Issue**
When the standy nodes restarts, they always start replicating records from the beginning and by the time they finish the replication, it's already killed by Kubernetes with exit `code 137`

I managed to fix the replication by disabling the `livenessProbe` and `readinessProbe`.

Is there a way to tell postgresql to only replay the recent logs, not the entire WAL from the beginning?

### Are you using any custom parameters or values?

```yaml
 global:
    storageClass: "postgresql"
   postgresql:
     database: "my_database"
     username: "my_user"
     password: "my_password"
     postgresPassword: "my_password"
     repmgrPassword: "my_password"
     replicaCount: 3
     resources:
       requests:
         memory: "2Gi"
         cpu: "1"
       limits:
         memory: "5Gi"
         cpu: "2"      

    persistence:
      enabled: true
    pgpool:
      replicaCount: 3
   metrics:
     enabled: true
     serviceMonitor: 
       enabled: fasle
```

### What is the expected behavior?

I was expecting, that the standby server will immediately come up, reply only the missing records and come healthy

### What do you see instead?

Standby nodes are in this loop and has multiple restarts
```
postgresql-repmgr 08:54:19.05 
postgresql-repmgr 08:54:19.05 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 08:54:19.05 Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql-repmgr 08:54:19.05 Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql-repmgr 08:54:19.05 
postgresql-repmgr 08:54:19.07 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 08:54:19.09 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 08:54:19.09 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 08:54:19.10 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 08:54:19.18 INFO  ==> Auto-detected primary node: 'postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.cognigy-ai.svc.cluster.local:5432'
postgresql-repmgr 08:54:19.18 INFO  ==> Node configured as standby
postgresql-repmgr 08:54:19.19 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 08:54:19.19 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 08:54:19.28 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 08:54:19.29 INFO  ==> Initializing Repmgr...
postgresql-repmgr 08:54:19.29 INFO  ==> Waiting for primary node...
postgresql-repmgr 08:54:19.32 INFO  ==> Rejoining node...
postgresql-repmgr 08:54:19.32 INFO  ==> Cloning data from primary node...

```

### Additional information

If I inspect the size of disk used by primary it is around ~59GB

While the standby node is replicating, I was also inspecting it's disk usage using `df-h`
```
/dev/nvme1n1     99G   1G   40G  60% /bitnami/postgresql
```
this start from 0 and increase to a bit (around 10G) and K8S kills the pod and it start all over again.

**Comment by javsalgar** [comment]
Hi,

We have an experimental feature that uses `pg_rewind`. 

```
  ## @param postgresql.usePgRewind Use pg_rewind for standby failover (experimental)
  ##
  usePgRewind: false
```

Could you try it?

**Comment by regmish** [comment]
Hi @javsalgar, 
I tried to enable pg_rewind with existing installation and it failed with the warning
`warn pg_rewind failed, resorting to data cloning`

Do I need to setup a fresh installation?

**Comment by Savid** [comment]
Just had the same issue. Looked like liveness probes were failing so i disabled them;

```
postgresql:
  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false
```

Gave them enough time to restore data. Re-enabled probes and now replicas are fine
