### ISSUE TITLE
[bitnami/mongodb] Upgrade failed with auth.existingSecret set and Rancher Fleet

### ISSUE THREAD

**Issue by matteogazzadi** [bitnami/charts#17839]
### Name and Version

bitnami/mongodb 13.16.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create an Helm chart with MongoDB 13.16.0 as dependency.
In values.yaml set:
```yaml
mongodb:
   auth:
      existingSecret: mine-super-secret
```

The secret is defined in the templates folder, with annotation: `"helm.sh/resource-policy": "keep"` to avoid loosing it in case of uninstall.

2. Deploy the chart with Rancher Fleet (v0.7.X)
3. Modify the chart, by changing any values (eg. increase replicaCount)
4. Fleet does report the  error: `PASSWORDS ERROR: You must provide your current passwords when upgrading the release. Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims. Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases 'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$MONGODB_ROOT_PASSWORD' to the command`

If chart is upgrade using `helm upgrade` it does work correctly.

So far we found as workaround, to set the `auth.rootPassword:  dummyPassword` in the values.yaml.  This does in someway bypass the validation.

### Are you using any custom parameters or values?

mongodb:
    auth:
        existingSecret: mine-super-secret

### What is the expected behavior?

Upgrade working without error when performed using Rancher Fleet

### What do you see instead?

We got: PASSWORDS ERROR: You must provide your current passwords when upgrading the release. Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims. Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases 'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$MONGODB_ROOT_PASSWORD' to the command

**Comment by jotamartos** [comment]
Hi @matteogazzadi,

I just tried to reproduce the error but couldn't do so. The secret I created was this one 

```
apiVersion: v1
data:
  mongodb-passwords: cGFzc3dvcmQy
  mongodb-replica-set-key: MTIzNDU2Nzg5YXNkZmdoamts
  mongodb-root-password: cGFzc3dvcmQx
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  creationTimestamp: null
  name: mine-super-secret
```

Then, edited the values.yaml file with these changes 

```
diff --git a/bitnami/mongodb/values.yaml b/bitnami/mongodb/values.yaml
index 077fd3676..1c6998bff 100644
--- a/bitnami/mongodb/values.yaml
+++ b/bitnami/mongodb/values.yaml
@@ -144,7 +144,7 @@ image:
 schedulerName: ""
 ## @param architecture MongoDB(&reg;) architecture (`standalone` or `replicaset`)
 ##
-architecture: standalone
+architecture: replicaset
 ## @param useStatefulSet Set to true to use a StatefulSet instead of a Deployment (only when `architecture=standalone`)
 ##
 useStatefulSet: false
@@ -168,9 +168,11 @@ auth:
   ## @param auth.passwords List of passwords for the custom users set at `auth.usernames`
   ## @param auth.databases List of custom databases to be created during the initialization
   ##
-  usernames: []
+  usernames:
+    - user1
   passwords: []
-  databases: []
+  databases:
+    - test1
   ## @param auth.username DEPRECATED: use `auth.usernames` instead
   ## @param auth.password DEPRECATED: use `auth.passwords` instead
   ## @param auth.database DEPRECATED: use `auth.databases` instead
@@ -184,7 +186,7 @@ auth:
   ## @param auth.existingSecret Existing secret with MongoDB(&reg;) credentials (keys: `mongodb-passwords`, `mongodb-root-password`, `mongodb-metrics-password`, `mongodb-replica-set-key`)
   ## NOTE: When it's set the previous parameters are ignored.
   ##
-  existingSecret: ""
+  existingSecret: mine-super-secret
 tls:
   ## @param tls.enabled Enable MongoDB(&reg;) TLS support between nodes in the cluster as well as between mongo clients and nodes
   ##
```

and launched the deployment. Everything succeeded and could access the database using the root user and the password. After that, I edited the statefulset to increase the number of replicas and the new pod ran without problems 

```
$ k get pods
NAME                     READY   STATUS    RESTARTS   AGE
jota-mongodb-0           1/1     Running   0          12m
jota-mongodb-1           1/1     Running   0          12m
jota-mongodb-2           1/1     Running   0          7m9s
jota-mongodb-arbiter-0   1/1     Running   0          12m
```

I deployed this in GKE, can you confirm the issue only happens when using Rancher? Can you try to reproduce the issue when using the changes I just posted? 

Thanks

**Comment by matteogazzadi** [comment]
The issue is not about using an external secret or making changes later in Kubernetes. 
Is about upgrading the chart later (like change chart version) and do it using Rancher Fleet.

With previous release of MongoDb 10.X it was working, while with the current one it does fail.

Rancher fleet version it’s kept the same.

**Comment by matteogazzadi** [comment]
Dear, 
We think it's pretty clear that a breaking change has been introduced in the common bitnami part handling existing secret, given that maintaining the same version of rancher, MongoDB 10 does perform correctly while version 13 got this error.

Moreover, we just found a workaround that is basically set the auth.rootPassword to a dummy one.

In this way the validation is passed but the chart will actually use the existing secret.

**Comment by jotamartos** [comment]
Hi @matteogazzadi,

Could you please provide the exact steps (commands) you follow to get the error? As I mentioned, everything worked correctly in our GKE environment using the latest version of the chart. I used `kubectl edit` to modify the statefulSet (to set a new replicaCount value) and didn't get errors.

**Comment by matteogazzadi** [comment]
Hi @jotamartos,  sure:
1. Create an Helm Chart with MongoDB 13.9.2 as chart dependency
2. In Values.yaml set:
```yaml
mongodb:
  replicaCount: 1
  architecture: replicaset
  replicaSetName: rs0
  podAntiAffinityPreset: hard
  enabled: true
  nameOverride: "db"
  useStatefulSet: true
  auth:
    # Use Existing Secret
    existingSecret: my-app-db
    # database is the MongoDB custom database
    database: myapp
    # username is the MongoDB custom user (mandatory if auth.database is set)
    username: myappuser
```

3. in templates folder add the code for the secret:
```yaml
# retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace .Values.mongodb.auth.existingSecret).data | default dict }}
# Retrieve database credentials from the Secret. If not present, the credential is randomly generated.
{{- $mongodbPassword:= (get $secretData "mongodb-passwords") | default (randAlphaNum 32 | b64enc) }}
{{- $mongodbRootPassword:= (get $secretData "mongodb-root-password") | default (randAlphaNum 32 | b64enc) }}
{{- $mongodbReplicaSetKey:= (get $secretData "mongodb-replica-set-key") | default (randAlphaNum 32 | b64enc) }} 

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.auth.existingSecret }}
  annotations:
    # With this annotation the secret IS NOT deleted if helm uninstall command is run.
    "helm.sh/resource-policy": "keep"
type: Opaque
# Mark the secret immutable so it cannot be modified by mistake
immutable: true
data:
  mongodb-passwords: {{ $mongodbPassword | quote }}
  mongodb-root-password: {{ $mongodbRootPassword | quote }}
  mongodb-replica-set-key: {{ $mongodbReplicaSetKey | quote }}
```

4. Deploy it using Rancher Fleet.
5. Change in the chart.yaml the MongoDB dependency, and set MongoDb: 13.16.2.
6. Rancher Fleet automatically detects the error and perform upgrade, but it fails on the initial validation about existing secret, that is btw present in the cluster given the (helm.sh/resource-policy: keep annotation).

To make it work is enough to adda dummy rootPassword in the Values.yaml: 
 ```yaml
 mongodb:
   auth:
      rootPassword: dummyPasswordIgnoredByExistSecret
```

**Comment by jotamartos** [comment]
Hi again, 

I'm sorry but I'm afraid this is something that the Rancher developers should check. I tried to reproduce the issue again in the GKE environment and everything worked as expected. This is what I tried, all these scenarios included the changes to use the `mine-super-secret` secret I posted above

- Install the latest version and use `kubectl edit` to change the replicaCount parameter
- Install MongoDB version 13.9.2 using the same values.yaml file I posted above and then upgrade the deployment to the latest version using `kubectl upgrade`
- Edit the values.yaml file again and change the replicaCount parameter again and run the `helm upgrade` command to update the number of replicas

None of the above scenarios returned errors and I deleted the deployments before launching a new one. You can still use the workaround you found to upgrade the solution but if you find a fix after talking to the Rancher developers, we will be more than happy to [review it](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md). 

Thanks

**Comment by aDisplayName** [comment]
@matteogazzadi , I believe it is the limitation of 
1. how bitnami charts were written, and 
2. how "helm template" was used by rancher fleet.

In [`common.secrets.passwords.manage`](https://github.com/bitnami/charts/blob/ec87ba608d945b1735f8b65e828cd9dc61ae425f/bitnami/common/templates/_secrets.tpl#L92C1-L92C49), `lookup` was used to check the existing object. If such object does not exist, and if the current helm operation `.Release.IsUpgrade` is `true`, the `fail` function will be invoked to fail the upgrade.

Note the 'lookup' will not get anything during when `--dryrun` was specified. I highly suspect the reason almost every bitnami charts fails at upgrade when fleet was used, is because `--dryrun` was used by fleet somehow:
https://github.com/search?q=repo%3Arancher%2Ffleet%20dryrun&type=code

I'm more interested on how you get around this problem? How does the dummy password get around the problem? I'm deploying postgresql and needs a workaround.

Here is the code example I'm using
```yaml
kind: ConfigMap
metadata:
  name: kc-data
apiVersion: v1
data:
  {{- $secret := (lookup "v1" "Secret" "default" "external-data") }}
  {{- if $secret }}
  key: value
  {{- else }}
  {{- if .Release.IsUpgrade -}}
  {{  printf "local data not found during upgrade " | fail  -}}
  mode: upgrade
  {{- else }}
  mode: install
  {{- end }}
  {{- end }}
```

**Comment by und-miller** [comment]
@matteogazzadi the dummy password workaround solved our deployment issues. 

```yaml
mongodb:
  auth:
     rootPassword: dummyPasswordIgnoredByExistSecret
```
