### ISSUE TITLE
[bitnami/solr] Unable to mount volumes from initContainers

### ISSUE THREAD

**Issue by GridexX** [bitnami/charts#17841]
### Name and Version

bitnami/solr 7.5.5

### What architecture are you using?

amd64

## 1. Environment

Here is my Linux OS:
```command
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.1.38-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × 11th Gen Intel® Core™ i7-1165G7 @ 2.80GHz
Memory: 30.9 GiB of RAM
Graphics Processor: Mesa Intel® Xe Graphics
Manufacturer: Dell Inc.
Product Name: Latitude 5420
```

I'm running this chart with the following tools:

```
minikube version: v1.30.1
```

```command
$ kubectl version
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.26.3
```

```command
$ helm version
version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}

```

--- 

## 2. Run

Run a Helm Chart with bitnami/solr 7.5.5 installed and the following values.

### Are you using any custom parameters or values?

```yaml
solr:
  enabled: true
  auth:
    enabled: false
  service:
    ports:
      http: 8983
  coreNames:
    - xwiki
    - xwiki_events
    - xwiki_extension_index
    - xwiki_ratings
  extraVolumes:
    - name: solr-cores
      emptyDir: {}
  # diagnosticMode:
  #   enabled: true
  extraVolumesMount:
    - name: solr-cores
      mountPath: /tmp

  initContainers:
  - name: download-cores
    image: curlimages/curl:8.2.0
    volumeMounts:
      - name: solr-cores
        mountPath: /home/curl_user/cores
    command: ['/bin/sh', '-c']
    args:
    - |
      SOLR_CORE_URL="https://maven.xwiki.org/releases/org/xwiki/platform/xwiki-platform-search-solr-server-core/15.5/xwiki-platform-search-solr-server-core-15.5.jar"
      SOLR_MINIMAL_CORE_URL="https://maven.xwiki.org/releases/org/xwiki/platform/xwiki-platform-search-solr-server-core-minimal/15.5/xwiki-platform-search-solr-server-core-minimal-15.5.zip"
      cd /home/curl_user
      curl $SOLR_CORE_URL -o ./xwiki-server-core.zip && \
      curl $SOLR_MINIMAL_CORE_URL -o ./xwiki-minimal-core.zip
      mkdir -p /home/curl_user/cores/xwiki
      mkdir -p /home/curl_user/cores/xwiki_events
      mkdir -p /home/curl_user/cores/xwiki_extension_index
      mkdir -p /home/curl_user/cores/xwiki_ratings
      unzip -qq ./xwiki-server-core.zip  -d /home/curl_user/cores/xwiki
      unzip -qq ./xwiki-minimal-core.zip -d /home/curl_user/cores/xwiki_events
      unzip -qq ./xwiki-minimal-core.zip -d /home/curl_user/cores/xwiki_extension_index
      unzip -qq ./xwiki-minimal-core.zip -d /home/curl_user/cores/xwiki_ratings

```

### What is the expected behavior?

The initContainers Download cores ZIP Archive and decompress them. They should be connected to the container using a volumeMount.
The directory `cores` should be mounted inside the `/tmp` folder. Instead, this folder doesn't contain it.

Core should be created and viewable from the Solr Admin Page.

## The directory is empty of the cores directory
![image](https://github.com/bitnami/charts/assets/50552672/6bd7791f-8cbc-4c97-9517-0e7c37b532a8)

## Core are not created 
![image](https://github.com/bitnami/charts/assets/50552672/e9aa7e77-3cc4-48b6-8364-7414f2bdcd4c)

### Additional information

I'm using this Chart into a custom Helm Chart, it might impact the behavior. Here is the URL of it: [xwiki-contrib/xwiki-helm](https://github.com/xwiki-contrib/xwiki-helm)
