### ISSUE TITLE
thanos chart's PrometheusRules reference incorrect job names

### ISSUE THREAD

**Issue by rfox-codecov** [bitnami/charts#17968]
### Name and Version

bitnami/thanos 12.8.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

instantiate a new Helm release of bitnami/thanos with a custom release name (ours was `thanos-codecov-production`, but it could be anything that's not `thanos`)

set metrics.prometheusRule.enabled to true

observe the PrometheusRules in your cluster targetting `job=` targets which do not exist -- `thanos-query`, etc

### Are you using any custom parameters or values?

Custom Helm release name -- common use case: deploying multiple instances of Thanos

metrics.prometheusRule.enabled must be true to deploy the rules

### What is the expected behavior?

PrometheusRule resources alerts should be templated such that they don't assume the job names will be `thanos-{component}` but instead be `{release name}-component` 

### What do you see instead?

PrometheusRule resources created reference `job=` selectors which aren't correct:

```yaml
    - alert: ThanosCompactHighCompactionFailures
      annotations:
        description: Thanos Compact {{ $labels.job }} is failing to execute {{ $value
          | humanize }}% of compactions.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompacthighcompactionfailures
        summary: Thanos Compact is failing to execute compactions.
      expr: |
        (
          sum by (job) (rate(thanos_compact_group_compactions_failures_total{job=~".*thanos-compact.*"}[5m]))
        /
          sum by (job) (rate(thanos_compact_group_compactions_total{job=~".*thanos-compact.*"}[5m]))
        * 100 > 5
        )
      for: 15m
      labels:
        default_rule: "true"
        severity: warning
```

but the deployed jobs are entitled `thanos-codecov-production-compact` for example, so the selector 

### Additional information

Rules are in https://github.com/bitnami/charts/tree/main/bitnami/thanos/templates/alert-rule
