### ISSUE TITLE
auth.usernames, passwords, database not working?

### ISSUE THREAD

**Issue by nickpapadonis** [bitnami/charts#17998]
### Name and Version

bitnami/mongodb

### What architecture are you using?

None

### What steps will reproduce the bug?

```yaml
 auth:
    rootPassword: "XXX"
    usernames:
      - mern-0
    passwords:
      - test
    databases:
      - mern-0
```

### Are you using any custom parameters or values?

I'm trying to automatically add a database, user role for it and password.  I use above Yaml, however, I find this user is not created.

### What is the expected behavior?

Database user and password created

### What do you see instead?

Nothing
