### ISSUE TITLE
[bitnami/postgresql-ha] support secrets for pgpool.customUsers

### ISSUE THREAD

**Issue by kzombro-pfl** [bitnami/charts#18001]
### Name and Version

bitnami/postgresql-ha 11.7.11 (latest)

### What is the problem this feature will solve?

I have a need to mask the `pgpool.customUsers` fields out of plaintext and into a kubernetes secret.

Here is the current spec from values.yaml:
```
pgpool:
...
  ## @param pgpool.customUsers.usernames Comma or semicolon separated list of additional users that will be performing connections to the database using pgpool.
  ## @param pgpool.customUsers.passwords Comma or semicolon separated list of the associated passwords for the users above. Must have the same number of elements as the usernames list.
  ## Use this property in order to create new user/password entries that will be appended to the "pgpool_passwd" file.
  ## e.g:
  ##    customUsers:
  ##      usernames: "user01;user02"
  ##      passwords: "pass01;pass02"
  customUsers:
    usernames: ""
    passwords: ""
```

What I would like to see is a configuration option for storing the `pgpool.customUsers.usernames` and `pgpool.customUsers.passwords` as a kubernetes secret.

something like this:
```
pgpool:
  customUsers:
    secretName: pgpool-custom-users
```
wherein the opaque k8s secret has fields `usernames` and `passwords`.

Please let me know if I need to elaborate further

### What is the feature you are proposing to solve the problem?

extend bitnami/postgresql-ha  `pgpool.customUsers` to support a kubernetes secret instead of plaintext username/password declaration.

### What alternatives have you considered?

none
