### ISSUE TITLE
[bitnami/grafana-operator] ingress 

### ISSUE THREAD

**Issue by aagutu** [bitnami/charts#18003]
### Name and Version

version: 3.1.3

### What architecture are you using?

None

### What steps will reproduce the bug?

deploying the grafana-operator chart using helm install but before it finished i get the below error 

`error validating data: [ValidationError(Grafana.spec.ingress.spec): unknown field "tlsEnabled" in org.integreatly.grafana.v1beta1.Grafana.spec.ingress.spec, ValidationError(Grafana.spec.ingress.spec): unknown field "tlsSecretName" in org.integreatly.grafana.v1beta1.Grafana.spec.ingress.spec]`

### Are you using any custom parameters or values?

using values.yaml file to do my deployment 
A snippet of the values.yaml file 

```yaml
  ingress:
      enabled: true
      ingressClassName: ""
      host: "grafana{{.Values.global.componentSubdomainSeparator}}{{.Values.global.clusterName}}.{{.Values.global.domain}}"
      tls: true
      tlsSecret: selfsigned-tls-certificate
      issuerName: selfsigned-tls-issuer
```
### What is the expected behavior?

the expected thing that i should see is that the deployment should finish and create for me an ingress llink

### What do you see instead?

deployment is not completed and there is no ingress link created
