### ISSUE TITLE
k8s pods ImagePullBackOff issue bitnami rabbitmq-exporter

### ISSUE THREAD

**Issue by santoshbaruah** [bitnami/charts#18012]
### Name and Version

bitnami/rabbitmq-exporter:0.29.0-debian-9-r104

### What is the problem this feature will solve?

`kubectl get statefulset rabbitmq -o yaml`
```yaml
 name: rabbitmq
        - name: RABBIT_URL
          value: http://localhost:15672
        - name: RABBIT_USER
          value: user
        - name: PUBLISH_PORT
          value: "9419"
        - name: RABBIT_CAPABILITIES
          value: bert,no_sort
        image: docker.io/bitnami/rabbitmq-exporter:0.29.0-debian-9-r104
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /metrics
            port: metrics

 name: RABBITMQ_ERL_COOKIE
          valueFrom:
            secretKeyRef:
              key: rabbitmq-erlang-cookie
              name: rabbitmq
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rabbitmq-password
              name: rabbitmq
        image: docker.io/bitnami/rabbitmq:3.8.2-debian-9-r0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
```   
but we have an issue with the RabbitMQ matrics.
```console
$ kubectl get pods --selector app=rabbitmq

NAME         READY   STATUS             RESTARTS   AGE
rabbitmq-0   1/2     ImagePullBackOff   0          5d15h
                                                                                                                                                                                                                                                                                                     
pod status 

rabbitmq-0                                             1/2     ImagePullBackOff             0                 5d15h
redis-master-0                                         2/2     Running                      0                 5d15h
```
It's not available in Docker Hub.
```
docker pull bitnami/rabbitmq-exporter:0.29.0-debian-9-r104
```

### What is the feature you are proposing to solve the problem?

Error response from daemon: pull access denied for bitnami/rabbitmq-exporter, the repository does not exist or may require 'docker login': denied: requested access to the resource is denied

So, we are unable to download the bitnami/rabbitmq-exporter specific version as it is not available in the Docker Hub.

### What alternatives have you considered?

As rabbitmq-exporter:0.29.0-debian-9-r104 is not available, what is the alternative to be used for? compatible with bitnami/rabbitmq:3.8.2-debian-9-r0?

**Comment by carrodher** [comment]
The bitnami/rabbitmq-exporter was deprecated and removed a long time ago, we recommend using a recent version of the bitnami/rabbitmq Helm chart

**Comment by santoshbaruah** [comment]
Which version of RabbitMQ is required to access /bitnami/rabbitmq-exporter? Presently, we are utilizing /bitnami/rabbitmq-exporter. Has the exporter been replaced with harbor-exporter in their Helm charts? If we upgrade to the recent version of the bitnami/rabbitmq Helm chart , which version of exporter is avibale to use ?

**Comment by carrodher** [comment]
The bitnami/rabbitmq-exporter container image is not present in the registry anymore, there is not any replacement for it.

You can use a sidecar or init container setting any external exporter container image, see
```yaml
## @param initContainers Add init containers to the RabbitMQ pod
## Example:
## initContainers:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
initContainers: []
## @param sidecars Add sidecar containers to the RabbitMQ pod
## Example:
## sidecars:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
sidecars: []
```
This is a way of extending the capabilities of the Helm chart, but please note there is not any exporter feature built-in into the Helm chart.

**Comment by carrodher** [comment]
No, there is not any exporter bundled in the RabbitMQ Helm chart

**Comment by santoshbaruah** [comment]
ok , you are suggesting this right ? 
spec:
  ```
    terminationGracePeriodSeconds: 30
      containers:
      - name: rabbitmq
        image: docker.io/bitnami/rabbitmq:3.8.2-debian-9-r0
        ports:
        - name: amqp
          containerPort: 5672
        - name: dist
          containerPort: 25672
        - name: stats
          containerPort: 15672        
        env:
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq-password
        readinessProbe:
          exec: 
            command: 
            - sh
            - -c
            - rabbitmq-health-check
        livenessProbe:
          exec:
            command:
            - sh
            - -c     
            - rabbitmq-api-check
      sidecars:
      - name: rabbitmq-exporter
        image: prom/rabbitmq-exporter:latest
        ports:
        - name: http
          containerPort: 9419
      volumes:
      - name: config-volume
        configMap:
          name: rabbitmq-config
      - name: healthchecks        
        configMap:
          name: rabbitmq-healthchecks
    
      # Service
      ports:
      - name: http
        port: 9419
```
