### ISSUE TITLE
[bitnami/keycloak] existingSecret

### ISSUE THREAD

**Issue by pescador691** [bitnami/charts#18014]
### Name and Version

bitnami/keycloak 16.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Trying to deploy keycloak with the postgres in ArgoCD. I need to use the secrets stored on an existing secret. 

However, the keycloak and postgres pod won't get the values of my `keycloak-secret`.

### Are you using any custom parameters or values?

My values.yaml if as follows:

```yaml
auth:
  existingSecret: keycloak-secret
  passwordSecretKey: admin-password
  adminUser: admin

postgresql:
  enabled: true
  existingSecret: keycloak-secret
  secretKeys:
    adminPasswordKey: postgres_admin_password
    userPasswordKey: postgres_user_password
    replicationPasswordKey: postgres_replication_password
```
My secrets.yaml is the following:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: app-k8s-keycloak-ns
stringData:
  admin-password: generated
  postgres_admin_password: admin-postgres-generated
  postgres_user_password: postgres-generated
```

### What is the expected behavior?

The keycloak and postgres pod would get the secrets from the existing secret defined.

### What do you see instead?

The keycloak and postgres pod keep using the default secret that is created in the deployment when the `existingSecret` is empty.

I am using openlens and I can see that the pods will get the default secret and not the existing secret

### Additional information

I tried to create a secret file to override the default secrets and now the keycloak and postgres pods have the correct secret but needed to delete the pvc because the old keys persisted.

secret.yaml used to override defaulta secrets:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-k8s-keycloak
  namespace: app-k8s-keycloak-ns
stringData:
  admin-password: generated
---
apiVersion: v1
kind: Secret
metadata:
  name: app-k8s-keycloak-postgresql
  namespace: app-k8s-keycloak-ns
stringData:
  postgres-password: admin-postgres-generated
  password: postgres-generated
---
```

**Comment by dgomezleon** [comment]
Hi @pescador691 ,

I reproduce another issue using your values (using `helm template` command):

```
...
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: postgres_user_password
            - name: POSTGRES_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: postgres_admin_password

...

            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: admin-password
            - name: KEYCLOAK_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: password
```

This would fail since the key `password` is not present in the secret and can be added as a workaround. This is due to how  `databaseSecretPasswordKey` is defined in `templates/_helpers.tpl`

```
{{/*
Add environment variables to configure database values
*/}}
{{- define "keycloak.databaseSecretPasswordKey" -}}
{{- if .Values.postgresql.enabled -}}
    {{- print "password" -}}
{{- else -}}
    {{- if .Values.externalDatabase.existingSecret -}}
        {{- if .Values.externalDatabase.existingSecretPasswordKey -}}
            {{- printf "%s" .Values.externalDatabase.existingSecretPasswordKey -}}
        {{- else -}}
            {{- print "db-password" -}}
        {{- end -}}
    {{- else -}}
        {{- print "db-password" -}}
    {{- end -}}
{{- end -}}
{{- end -}}
```

Could you please confirm?

**Comment by dgomezleon** [comment]
Hi @pescador691 ,

I'm not familiar with OpenLens, but let's clarify if we are trying the same.

I created this secret (I used `keycloak-custom-secret` to double-check it was using my secret, and added `password` key as mentioned previously):

```
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-custom-secret
stringData:
  password: postgres-generated
  admin-password: generated
  postgres_admin_password: admin-postgres-generated
  postgres_user_password: postgres-generated
```

I tried these values:

```
auth:
  existingSecret: keycloak-custom-secret
  passwordSecretKey: admin-password
  adminUser: admin

postgresql:
  existingSecret: keycloak-custom-secret
  secretKeys:
    adminPasswordKey: postgres_admin_password
    userPasswordKey: postgres_user_password
    replicationPasswordKey: postgres_replication_password
```

This is the output from  `helm template .`:

```
...
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-custom-secret
                  key: postgres_user_password
            - name: POSTGRES_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-custom-secret
                  key: postgres_admin_password
...

            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-custom-secret
                  key: admin-password
            - name: KEYCLOAK_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-custom-secret
                  key: password
...
```

And also using `kubectl describe pod POD`:

```
...
    Environment:
      KUBERNETES_NAMESPACE:         dgomezleon (v1:metadata.namespace)
      BITNAMI_DEBUG:                false
      KEYCLOAK_ADMIN_PASSWORD:      <set to the key 'admin-password' in secret 'keycloak-custom-secret'>  Optional: false
      KEYCLOAK_DATABASE_PASSWORD:   <set to the key 'password' in secret 'keycloak-custom-secret'>        Optional: false
      KEYCLOAK_HTTP_RELATIVE_PATH:  /
```

I was able to access the pod and log in with those credentials. 

Could you please try it on your side?

**Comment by pescador691** [comment]
OpenLens is an opensource IDE for kubernetes that helps with the troubleshoot.

We tried the same - Add a secret with all those key/values and parse the reference of the secrets in the `values.yaml`.

The screenshots I took from openlens have the same result as using kubectl.

To clarify better, the first screenshot is showing that the pod is grabbing the secrets from the `secret app-k8s-keycloak`.

The second screenshot shows the values parsed to the pod.

The last screenshot shows the values of the secret `app-keys-keycloak`..


To sum up:

Even though I create a secret with all key/values like described above, and parse the secretKeyRef in the `values.yaml`, keycloak pod won't get the secrets from the `keycloak-custom-secret`.

Secret used:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-custom-secret
stringData:
  password: postgres-generated
  admin-password: generated
  postgres_admin_password: admin-postgres-generated
  postgres_user_password: postgres-generated
```

Values used:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-custom-secret
stringData:
  password: postgres-generated
  admin-password: generated
  postgres_admin_password: admin-postgres-generated
  postgres_user_password: postgres-generated
```
