### ISSUE TITLE
[bitnami/mongodb] Set advertised hostnames

### ISSUE THREAD

**Issue by Ray-Barker** [bitnami/charts#18020]
### Name and Version

bitnami/mongodb latest

### What is the problem this feature will solve?

Currently when setting up external access using LoadBalancer you can only use IP address as advertised hostname.
We have our own cloud provider which uses named load balancer IPs to create LoadBalancer service, for example:
`loadBalancerIP: some-random-name`
instead of IP address itself. 
Since the chart overrides the MONGODB_ADVERTISED_HOSTNAME variable with the value of LoadBalancer service's field 'loadBalancerIP' when using externalAccess.enabled.true with hardcoding it into startup script, we can't use the chart as it is without modifying it.

### What is the feature you are proposing to solve the problem?

Add another parameter to `externalAccess.service` values block where you can set advertised hostnames instead of IPs, for example, something like this:
```yaml
externalAccess:
  enabled: true
  service:
    hostnames:
    - host1
    - host2
```
Or use existing parameter `externalAccess.service.domain` not only for NodePort service, but for LoadBalancer service too.

### What alternatives have you considered?

My workaround, for now, is a combination of `extraVars` and `extraDeploy`:
```yaml
extraEnvVars:
  - name: MONGODB_ADVERTISED_HOSTNAME
    value: "$(MY_POD_NAME).<custom-domain>"
extraDeploy:
- apiVersion: v1
  kind: Service
  metadata:
    name: mongodb-external
    labels:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/name: mongodb
  spec:
    type: LoadBalancer
    ports:
      - name: mongodb
        port: 27017
        protocol: TCP
        targetPort: mongodb
    selector:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/name: mongodb
    loadBalancerIP: cloud-provider-lb-ip-name
    publishNotReadyAddresses: true
```
This is ok for one-node cluster, but when there are several nodes the values file becomes quite large due to several extra LB service manifests
