### ISSUE TITLE
[bitnami/matomo] Do not create Secret when an external DB Secret is provided

### ISSUE THREAD

**Issue by gw0** [bitnami/charts#18027]
### Name and Version

bitnami/matomo 1.1.9

### What is the problem this feature will solve?

The `matomo-externaldb` Secret is being created even if you specify that an existing Secret contains the DB password. (This happens if do not use the built-in Mariadb (`mariadb.enabled=false`) and provide `externalDatabase.existingSecret="matomo-my-secret"`).

```yaml
mariadb:
  enabled: false

externalDatabase:
  host: ${dbHost}
  port: ${dbPort}
  user: ${dbUser}
  existingSecret: ${dbExistingSecret}
```

### What is the feature you are proposing to solve the problem?

The condition for creating the `templates/externaldb-secrets.yaml` (https://github.com/bitnami/charts/blob/main/bitnami/matomo/templates/externaldb-secrets.yaml#L6) should match the "else" condition when selecting the Secret name in `matomo.databaseSecretName` (https://github.com/bitnami/charts/blob/main/bitnami/matomo/templates/_helpers.tpl#L131).

With other words, in `templates/externaldb-secrets.yaml` it should state:

```
{{- if and (not .Values.mariadb.enabled) (not .Values.externalDatabase.existingSecret) }}
```
