### ISSUE TITLE
[bitnami/mongodb] Error 'unable to get issuer certificate' when using TLs from cert-manager+let's encrypt

### ISSUE THREAD

**Issue by edson-morais-os** [bitnami/charts#18035]
### Name and Version

bitnami/mongodb 13.16.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1 - I'm deploying the cluster cert-manager issuers by using the Terraform below:
```
resource "kubectl_manifest" "cluster_cert_manager_cluster_self_issuer" {
  yaml_body = <<YAML

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigning
spec:
  selfSigned: {}

YAML
}

resource "kubectl_manifest" "cluster_cert_manager_cluster_issuer" {
  yaml_body = <<YAML

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: myteam@mycompnay.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          route53:
            region: ${var.region}

YAML
}
```

2 - Now, I'm deploying the mongodb TLS certificate:
```
resource "kubectl_manifest" "mongodb-client-tls" {
  yaml_body = <<YAML

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-client-tls
  namespace: mongodb
spec:
  secretName: mongodb-client-tls
  duration: 8736h # 1 year
  renewBefore: 240h # 10 days
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
  commonName: mongodb.dev.mycompnay.net
  dnsNames:
    - mongodb.dev.mycompnay.net
    - 
YAML
}
```

With these steps, I'm able to create a secret called "mongodb-client-tls" with the cert-manager & let's encrypt TLS data ( tls.crt , tls.key)

### Are you using any custom parameters or values?

I am using this value.yaml inputs:
```
---
architecture: standalone

global:
  storageClass: aws-ebs-gp2

auth:
  enabled: true
  rootUser: my-awesome-root-user
  rootPassword: my-awesome-root-user-password
  usernames:
    - my-awesome-root-user
    - my-awesome-root-user
  passwords:
    - my-awesome-root-user-password
    - my-awesome-root-user-password
  databases:
    - db-one
    - db-two

tls:
  enabled: true
  mode: requireTLS
  autoGenerated: false
  pemChainIncluded: true
  standalone:
    existingSecret: mongodb-client-tls

persistence:
  enabled: true
  storageClass: aws-ebs-gp2
  size: 20Gi

ingress:
  hosts:
    - name: ${dns_name}
      path: /
...
```
### What is the expected behavior?

Having the pod [cluster-mongodb] containers [mongodb and generate-tls-certs] up and running.

Also, being able to connect to my mongodb instance by using the Compass and my DNS [mongodb.dev.mycompnay.net].

### What do you see instead?

When starting the chart deployment, the pod [cluster-mongodb] container [mongodb] shows the log & message:

Pod logs:  [mongodb - existing certs.log](https://github.com/bitnami/charts/files/12213687/mongodb.-.existing.certs.log)

Pod event: 
```
Liveness probe failed: 
Current Mongosh Log ID: 64c77ca49921046d59d7c4c6 
Connecting to: mongodb://127.0.0.1:27017/?directConnection=true&
                                          serverSelectionTimeoutMS=2000&
										  tls=true&
										  tlsCertificateKeyFile=/certs/mongodb.pem&
										  tlsCAFile=/certs/mongodb-ca-cert&
										  tlsAllowInvalidHostnames=true&
										  appName=mongosh+1.10.1
MongoServerSelectionError: unable to get issuer certificate
```
### Additional information

Sorry to bother you guys :(

But, please, is expected to have mongodb working with this TLS strategy? I mean, using cert-manager, and let's encrypt?

Should I change something in my values.yaml?

I appreciate any orientation.
And count on me to try different approaches, do more tests, and give more details.

Thank you so much.
