### ISSUE TITLE
[bitnami/discourse] - Premature Termination [K8]

### ISSUE THREAD

**Issue by sonic-sw** [bitnami/charts#18033]
### Name and Version

-bitnami/discourse:10.3.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Dear Team,

I am trying to deploy in GCP the discourse.
The setup from DB and Redis is starting, however the min deployment fails and gets early terminated when compiling the asses

```
discourse 14:12:58.46 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse 14:12:58.67 INFO  ==> Trying to connect to the database server
discourse 14:12:59.91 INFO  ==> Creating database bitnami_application
discourse 14:13:03.21 INFO  ==> Creating Discourse configuration file
discourse 14:13:03.44 INFO  ==> Enabling SMTP
discourse 14:13:03.61 INFO  ==> Restoring persisted Discourse installation
discourse 14:13:04.41 INFO  ==> Trying to connect to the database server
discourse 14:13:04.44 INFO  ==> Running database migrations
discourse   4:14:23.65 INFO  ==> Precompiling assets, this may take some time...
```

### What is the expected behavior?

Complete the initial setup and start

### What do you see instead?

early termination due to time exceed the default probles

Readiness probe failed: Get "http://10.80.2.184:8080/srv/status": dial tcp 10.80.2.184:8080: connect: connection refused

**Comment by sonic-sw** [comment]
Dear Javsalgar,

my nodes are of GKE e2-medium (2c/4r) and are to slow for building the assets before been terminated by the probes.
I have disabled all (6) probes, example given

```
  livenessProbe:
    enabled: **true**
    initialDelaySeconds: 500
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
```

```
  livenessProbe:
    enabled: **false**
    initialDelaySeconds: 500
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
```

The total startup time for me was:
**10:46:53.33** ==> Precompiling assets, this may take some time...
**10:58:56.81** ==> ** Starting Discourse **
