### ISSUE TITLE
Kafka ServiceMonitor not being discovered by Prometheus Operator

### ISSUE THREAD

**Issue by amtux** [bitnami/charts#1804]
**Which chart**: bitnami/kafka

**Description**

Prometheus operator does not use annotations for service discovery so kafka-exporter and zookeeper-exporter cannot be used to send metrics over to Prometheus.

Enabling ServiceMonitor with the following values configuration creates the service monitor itself but the targets fail to show up in Prometheus and Kafka is missing in service discovery.

```yaml
# values-override.yaml
metrics:
  kafka:
    enabled: false
  jmx:
    enabled: true
  serviceMonitor:
    enabled: true
    namespace: logmet
    selector:
      prometheus: mon-prometheus-operator-prometheus
zookeeper:
  metrics:
    enabled: false
```

**Steps to reproduce the issue:**

1. `helm repo add bitnami https://charts.bitnami.com/bitnami`
2. `helm install kafka --atomic --namespace storage bitnami/kafka --values values-production.yaml --values values-override.yaml`

**Describe the results you received:**

Servicemonitors get created under correct namespace:

```bash
$ kubectl -n logmet get servicemonitor | grep kafka
kafka-jmx-metrics                                 2d
kafka-metrics                                     2d
$ kubectl -n logmet describe servicemonitor/kafka-metrics
Name:         kafka-metrics
Namespace:    logmet
Labels:       app.kubernetes.io/component=metrics
              app.kubernetes.io/instance=kafka
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=kafka
              helm.sh/chart=kafka-7.1.1
              prometheus=mon-prometheus-operator-prometheus
Annotations:  <none>
API Version:  monitoring.coreos.com/v1
Kind:         ServiceMonitor
Metadata:
  Creation Timestamp:  2020-01-03T20:34:09Z
  Generation:          1
  Resource Version:    8978956
  Self Link:           /apis/monitoring.coreos.com/v1/namespaces/logmet/servicemonitors/kafka-metrics
  UID:                 64ced74e-2e68-11ea-b277-42010a800030
Spec:
  Endpoints:
    Path:  /metrics
    Port:  metrics
  Namespace Selector:
    Match Names:
      storage
  Selector:
    Match Labels:
      App . Kubernetes . Io / Component:  metrics
      App . Kubernetes . Io / Instance:   kafka
      App . Kubernetes . Io / Name:       kafka
Events:                                   <none>
```

However, kafka is not showing up under Service Discovery of Prometheus

<img width="707" alt="image" src="https://user-images.githubusercontent.com/6476125/71825249-758b8a80-3069-11ea-898c-56d96e689f67.png">

**Describe the results you expected:**

Expected Kafka to show up in service discovery in Prometheus

**Additional information you deem important (e.g. issue happens only occasionally):**

Prometheus operator was installed with `helm install mon --namespace logmet stable/prometheus-operator` from [stable helm/charts](https://github.com/helm/charts/tree/master/stable/prometheus-operator)

```
kubectl -n logmet get pods
NAME                                                  READY   STATUS    RESTARTS   AGE
alertmanager-mon-prometheus-operator-alertmanager-0   2/2     Running   0          21d
alertmanager-mon-prometheus-operator-alertmanager-1   2/2     Running   0          21d
mon-grafana-f6d5b475c-v9xb7                           2/2     Running   0          21d
mon-kube-state-metrics-7d758d8c94-2v7tf               1/1     Running   0          21d
mon-prometheus-node-exporter-6jdzn                    1/1     Running   0          21d
mon-prometheus-node-exporter-96hwp                    1/1     Running   0          21d
mon-prometheus-node-exporter-9p777                    1/1     Running   0          14m
mon-prometheus-node-exporter-dwks8                    1/1     Running   0          21d
mon-prometheus-node-exporter-gkb4b                    1/1     Running   0          9d
mon-prometheus-node-exporter-jhct9                    1/1     Running   0          14m
mon-prometheus-node-exporter-p4p5g                    1/1     Running   0          21d
mon-prometheus-node-exporter-t8hwq                    1/1     Running   0          9d
mon-prometheus-operator-operator-55f97f5c55-57lpv     2/2     Running   0          21d
prometheus-mon-prometheus-operator-prometheus-0       3/3     Running   0          21d
prometheus-mon-prometheus-operator-prometheus-1       3/3     Running   0          21d
```

```
$ kubectl -n logmet describe deployment/mon-prometheus-operator-operator
Name:                   mon-prometheus-operator-operator
Namespace:              logmet
CreationTimestamp:      Mon, 16 Dec 2019 12:13:38 -0500
Labels:                 app=prometheus-operator-operator
                        chart=prometheus-operator-8.2.4
                        heritage=Helm
                        release=mon
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=prometheus-operator-operator,release=mon
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=prometheus-operator-operator
                    chart=prometheus-operator-8.2.4
                    heritage=Helm
                    release=mon
  Service Account:  mon-prometheus-operator-operator
  Containers:
   prometheus-operator:
    Image:      quay.io/coreos/prometheus-operator:v0.34.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/mon-prometheus-operator-kubelet
      --logtostderr=true
      --localhost=127.0.0.1
      --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.34.0
      --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
      --config-reloader-cpu=100m
      --config-reloader-memory=25Mi
    Environment:  <none>
    Mounts:       <none>
   tls-proxy:
    Image:      squareup/ghostunnel:v1.4.1
    Port:       8443/TCP
    Host Port:  0/TCP
    Args:
      server
      --listen=:8443
      --target=127.0.0.1:8080
      --key=cert/key
      --cert=cert/cert
      --disable-authentication
    Environment:  <none>
    Mounts:
      /cert from tls-proxy-secret (ro)
  Volumes:
   tls-proxy-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mon-prometheus-operator-admission
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   mon-prometheus-operator-operator-55f97f5c55 (1/1 replicas created)
Events:          <none>
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by amtux** [comment]
Unrelated but I am using NGINX ingress controller and wrote the following ServiceMonitor config which got picked up by Prometheus.
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-controller-metrics
  namespace: logmet
  labels:
    app: nginx-ingress
    release: mon
spec:
  endpoints:
  - interval: 30s
    port: metrics
  selector:
    matchLabels:
      app: nginx-ingress
      release: nginx-ingress
  namespaceSelector:
    matchNames:
      - nginx-ingress
```

 I'm wondering if the servicemonitor selector labels are messed up somehow with the random spaces:
```
    Match Labels:
      App . Kubernetes . Io / Component:  metrics
      App . Kubernetes . Io / Instance:   kafka
      App . Kubernetes . Io / Name:       kafka
```

**Comment by juan131** [comment]
Hi @amtux 

It could be related with the labels you're using.

I was able to retrieve Kafka metrics on Prometheus Operator using the commands below:

```console
$ helm install bitnami/prometheus-operator --name prometheus-operator --namespace monitoring
$ helm install --namespace kafka --name kafka --values values.yaml bitnami/kafka
$ kubectl get servicemonitor -n monitoring
NAME                                     AGE
kafka-jmx-metrics                        3m
prometheus-operator-alertmanager         8m
prometheus-operator-kube-state-metrics   8m
prometheus-operator-node-exporter        8m
prometheus-operator-operator             8m
prometheus-operator-prometheus           8m
$ kubectl port-forward --namespace monitoring svc/prometheus-operator-prometheus 9090:9090
```

When I access to Prometheus:

![Screenshot 2020-01-07 at 15 32 23](https://user-images.githubusercontent.com/6740773/71902844-2de92980-3163-11ea-8b39-dd30f5453e16.png)


Using the values.yaml below:

```yaml
metrics:
  kafka:
    enabled: false
  jmx:
    enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
zookeeper:
  metrics:
    enabled: false
```

**Comment by amtux** [comment]
Thanks for the response @juan131 - is there something in specific with the labels that looks weird to you?
One of the differences I see is that I'm using helm stable version prometheus-operator (which comes with node exporter, grafana, prometheus, alertmanager) vs your test with  `bitnami/prometheus-operator`

In the docs for `metrics.servicemonitor.interval` - it suggests to change the selector to the one we use so I matched it to the one in service definition of prometheus-operator's prometheus (i.e. mon-prometheus-operator-prometheus).

metrics.serviceMonitor.selector | Default to kube-prometheus install (CoreOS recommended), but should be set according to Prometheus install | { prometheus: kube-prometheus }
-- | -- | --

```
$ kubectl -n logmet describe svc/mon-prometheus-operator-prometheus
Name:              mon-prometheus-operator-prometheus
Namespace:         logmet
Labels:            app=prometheus-operator-prometheus
                   chart=prometheus-operator-8.2.4
                   heritage=Helm
                   release=mon
                   self-monitor=true
Annotations:       <none>
Selector:          app=prometheus,prometheus=mon-prometheus-operator-prometheus
Type:              ClusterIP
IP:                10.0.26.99
Port:              web  9090/TCP
TargetPort:        9090/TCP
Endpoints:         10.52.0.37:9090,10.52.1.18:9090
Session Affinity:  None
Events:            <none>
```

The servicemonitor description:
```
kubectl -n logmet describe servicemonitor/kafka-jmx-metrics
Name:         kafka-jmx-metrics
Namespace:    logmet
Labels:       app.kubernetes.io/component=kafka
              app.kubernetes.io/instance=kafka
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=kafka
              helm.sh/chart=kafka-7.1.1
              prometheus=mon-prometheus-operator-prometheus
Annotations:  <none>
API Version:  monitoring.coreos.com/v1
Kind:         ServiceMonitor
Metadata:
  Creation Timestamp:  2020-01-03T20:34:09Z
  Generation:          1
  Resource Version:    8978959
  Self Link:           /apis/monitoring.coreos.com/v1/namespaces/logmet/servicemonitors/kafka-jmx-metrics
  UID:                 64d32216-2e68-11ea-b277-42010a800030
Spec:
  Endpoints:
    Path:  /
    Port:  metrics
  Namespace Selector:
    Match Names:
      storage
  Selector:
    Match Labels:
      App . Kubernetes . Io / Component:  kafka
      App . Kubernetes . Io / Instance:   kafka
      App . Kubernetes . Io / Name:       kafka
Events:                                   <none>
```

**Comment by amtux** [comment]
Kafka jmx service looks pretty simple so I tried to write a servicemonitor myself but still no luck.

```yaml
# jmx servicemonitor yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-jmx-metrics
  namespace: logmet
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/name: kafka
spec:
  endpoints:
  - path: /
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: kafka
      app.kubernetes.io/instance: kafka
      app.kubernetes.io/name: kafka
      release: kafka
  namespaceSelector:
    matchNames:
      - storage
```

What the JMX service definition itself:
```yaml
$ kubectl -n storage get svc/kafka-jmx-metrics -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /
    prometheus.io/port: "5556"
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-01-07T16:26:19Z"
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-7.1.1
  name: kafka-jmx-metrics
  namespace: storage
  resourceVersion: "10581719"
  selfLink: /api/v1/namespaces/storage/services/kafka-jmx-metrics
  uid: 6fa1ff31-316a-11ea-b277-42010a800030
spec:
  clusterIP: 10.0.26.205
  ports:
  - name: metrics
    port: 5556
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/name: kafka
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by juan131** [comment]
Hi @amtux 

According to your servicemonitor description:

```console
Spec:
  Endpoints:
    Path:  /
    Port:  metrics
  Namespace Selector:
    Match Names:
      storage
  Selector:
    Match Labels:
      App . Kubernetes . Io / Component:  kafka
      App . Kubernetes . Io / Instance:   kafka
      App . Kubernetes . Io / Name:       kafka
```

It's looking for the services with the labels below in the namespace `storage`:

```yaml
app.kubernetes.io/component: kafka
app.kubernetes.io/instance: kafka
app.kubernetes.io/name: kafka
```

That should match your `kafka-jmx-metrics` service. I guess you can access the kafka endpoints though that service, anyway you can check it running the command below:

```console
$ kubectl get endpoints kafka-jmx-metrics -n storage
```

Could you check all the solutions suggested in the article below? 

- https://support.coreos.com/hc/en-us/articles/360000155514-Prometheus-ServiceMonitor-troubleshooting

**Comment by amtux** [comment]
Ok so I enabled jmx metrics and disabled everything else:
```
metrics:
  kafka:
    enabled: false
  jmx:
    enabled: true
  serviceMonitor:
    enabled: false
    namespace: logmet
    selector:
      app.kubernetes.io/component: kafka
      app.kubernetes.io/instance: kafka
      app.kubernetes.io/name: kafka
zookeeper:
  metrics:
    enabled: false
```

Then I wrote a servicemonitor for jmx metrics, added a `release: mon` to refer to one of the prometheus-operator helm deployment labels and JMX metrics are now being discovered in Prometheus and metrics are showing up:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-jmx-metrics
  namespace: logmet
  labels:
    release: mon
spec:
  endpoints:
  - path: /
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: kafka
      app.kubernetes.io/instance: kafka
      app.kubernetes.io/name: kafka
  namespaceSelector:
    matchNames:
      - storage
```

Thank you for your help!

**Comment by juan131** [comment]
Great @amtux !!! I'm glad you were able to solve the issue

**Comment by Dunj3nMast3r** [comment]
Hi @amtux could you please share your prometheus.yaml. I am also facing the same issue. able to see the metrics but they are not getting in prometheus.

**Comment by amtux** [comment]
@Dunj3nMast3r - sure. I am using prometheus-operator provided by [helm/charts repo](https://github.com/helm/charts/tree/master/stable/prometheus-operator) so I will link you my values override and install command.
If you are using a standalone prometheus deployment or [coreos version](https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html) instead - you may have to use annotations instead of service monitor.  
```
# values-override.yaml
prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    replicas: 2
    retention: 120d
    retentionSize: 95GiB
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: standard
          resources:
            requests:
              storage: 100Gi

# Define persistent storage for Grafana (PVC)
grafana:
  persistence:
    enabled: true
    storageClassName: standard
    accessModes: ["ReadWriteOnce"]
    size: 2Gi


# Define persistent storage for Alertmanager (PVC)
alertmanager:
  alertmanagerSpec:
    replicas: 2
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: standard
          resources:
            requests:
              storage: 5Gi

# Disable Etcd metrics
kubeEtcd:
  enabled: false
```

Deploy with: `helm install mon --version 8.9.0 --namespace logmet --values values-override.yaml --set grafana.adminPassword=mypassword stable/prometheus-operator`
Prometheus operator is in `mon` namespace and kafka is in `storage` namespace.
