### ISSUE TITLE
[bitnami/minio] TLS config and indentation issues in ServiceMonitor

### ISSUE THREAD

**Issue by zagr0** [bitnami/charts#18057]
### Name and Version

bitnami/minio 12.6.11

### What architecture are you using?

None

### What steps will reproduce the bug?

Install chart with values provided above

### Are you using any custom parameters or values?
```yaml
tls:
  enabled: true
  autoGenerated: true

metrics:
  serviceMonitor:
    enabled: true
    tlsConfig: 
      insecureSkipVerify: true
```
### What is the expected behavior?

ServiceMonitor to be created

### What do you see instead?

Helm install fails

### Additional information

related to https://github.com/bitnami/charts/pull/17798 and https://github.com/bitnami/charts/issues/17708
