### ISSUE TITLE
[bitnami/discourse] - Automated Backups not being sent to S3

### ISSUE THREAD

**Issue by stevejr** [bitnami/charts#18065]
### Name and Version

bitnami/discourse 10.3.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Using Discourse in EKS with CloudFront as the CDN. S3 is in use for Assets and that appears to work ok but automated backups are not being sent to the configured backup bucket.

Various environment vars have been set to configure the S3 settings but for some reason, the backup does not get sent to S3. Looking at the code it appears to return [here](https://github.com/discourse/discourse/blob/8a0d00b8663c950ac961e6acf282d5b83295ad8a/lib/backup_restore/backuper.rb#L339C21-L339C33)

Is there anyway to check if usage of the remote store is set? 

Do settings conflict and override each other?

### Are you using any custom parameters or values?

Related settings for S3:

```yaml
discourse:
  extraEnvVars:
  - name: DISCOURSE_BACKUP_LOCATION
    value: "s3"
  - name: DISCOURSE_S3_BUCKET
    value: "my-bucket"
  - name: DISCOURSE_S3_BACKUP_BUCKET
    value: "my-backup-bucket"
  - name: DISCOURSE_S3_CDN_URL
    value: "my-cdn-url"
  - name: DISCOURSE_S3_REGION
    value: "eu-west-1"
  - name: DISCOURSE_S3_UPLOAD_BUCKET
    value: "my-bucket"
  - name: DISCOURSE_S3_USE_IAM_PROFILE
    value: "true"
  - name: DISCOURSE_USE_S3
    value: "true"
  # This env var is needed so that we read S3 config from site settings
  - name: USE_DB_S3_CONFIG
    value: "true"
  - name: DISCOURSE_EXTRA_CONF_CONTENT
    value: |
      automatic_backups_enabled = true
      backup_gzip_compression_level_for_uploads = 1
      backup_location = s3
      backup_with_uploads = true
      enable_backups = true
      enable_s3_backups = true
      enable_s3_uploads = true
      maximum_backups = 30
      s3_bucket = my-bucket
      s3_backup_bucket = my-backup-bucket
      s3_upload_bucket = my-bucket
      s3_region = eu-west-1
      s3_use_iam_profile = true
      s3_cdn_url = my-cdn-url
      use_db_s3_config = true
      use_s3 = true
```

### What is the expected behavior?

Backups should be sent to S3

### What do you see instead?

The backup runs and but does not get sent to S3. It looks like the check to see if remote store is enabled is always returning false.
