### ISSUE TITLE
[rabbitmq] Trying to upgrade chart gives null pointer for Values.networkPolicy.enabled

### ISSUE THREAD

**Issue by mltsy** [bitnami/charts#1808]
**Which chart**:

stable/rabbitmq v6.13.1

(Also tried upgrading to 6.16.0, which didn't help)
(Downgrading to 6.8.4 worked fine)

**Description**

I was trying to run `helm upgrade --recreate-pods --reuse-values -f rabbitmq-values.yaml rabbitmq-server stable/rabbitmq` and got the following error message:
```
UPGRADE FAILED: render error in "rabbitmq/templates/networkpolicy.yaml": template: rabbitmq/templates/networkpolicy.yaml:1:14: executing "rabbitmq/templates/networkpolicy.yaml" at <.Values.networkPolicy.enabled>: nil pointer evaluating interface {}.enabled
```

The values file is pretty simple:
```yaml
rabbitmq:
  loadDefinition:
    enabled: true
    secretName: rabbitmq-load-definition
  extraConfiguration: |
    management.load_definitions = /app/load_definition.json
    vm_memory_high_watermark.relative = 0.6
    vm_memory_high_watermark_paging_ratio = 0.75
    total_memory_available_override_value = 5000MiB
    disk_free_limit.absolute = 4GiB
podManagementPolicy: Parallel
persistence:
  size: 50Gi
resources:
  requests:
    memory: 5000Mi
    cpu: 400m
  limits:
    memory: 5000Mi
    cpu: 600m
```

It contains nothing about `networkPolicy`, so I assume this is a bug with the chart.

**Steps to reproduce the issue:**

I would assume it can be reproduced by installing version 6.13.1 of the chart on a cluster, and then running:
`helm upgrade --recreate-pods --reuse-values -f rabbitmq-values.yaml rabbitmq-server stable/rabbitmq`

(with at least one value to update  in rabbitmq-values.yaml)

Doing this on my cluster, I got the error message above, while I would expect the release to be upgraded with the provided values without an exception.

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.17", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-11-13T20:47:11Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
)
```

**Comment by carrodher** [comment]
I was able to reproduce your issue. I think it is not a fault in the chart but collateral damage in the way Helm tries to upgrade.

I installed rabbitmq 6.13.1:
```
▶ helm2 install stable/rabbitmq --version 6.13.1
```

After that, I tried to upgrade it to the latest version with and without new values (using `--set`):
```
▶ helm2 upgrade --recreate-pods --reuse-values --set resources.requests.memory=5000Mi belligerent-mole stable/rabbitmq
UPGRADE FAILED
Error: UPGRADE FAILED: render error in "rabbitmq/templates/networkpolicy.yaml": template: rabbitmq/templates/networkpolicy.yaml:1:14: executing "rabbitmq/templates/networkpolicy.yaml" at <.Values.networkPolicy.enabled>: nil pointer evaluating interface {}.enabled

▶ helm2 upgrade --recreate-pods --reuse-values belligerent-mole stable/rabbitmq
UPGRADE FAILED
Error: UPGRADE FAILED: render error in "rabbitmq/templates/networkpolicy.yaml": template: rabbitmq/templates/networkpolicy.yaml:1:14: executing "rabbitmq/templates/networkpolicy.yaml" at <.Values.networkPolicy.enabled>: nil pointer evaluating interface {}.enabled
```
both cases the issue is the same, so it doesn't matter if you use new values or not (`--set` has the same effect that `-f`).

In the latest chart version (>6.14.0) there is a template (`templates/networkpolicy.yaml`) starting with the following sentence:
```yaml
{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
```

The `networkPolicy` object was added in the 6.14.0 version (https://github.com/helm/charts/pull/19304). We are trying to upgrade from a version that doesn't contain this object to a version that uses it *reusing the old values where `networkPolicy` object doesn't exist*.

`helm upgrade` without `--reuse-values` works fine, the problem is that using `--reuse-values` will fail if you don't specify the new values. In your case, you can solve the issue setting the `networkPolicy` to false in the `helm upgrade` command or adding it to your `rabbitmq-values.yaml`:

- `helm upgrade --recreate-pods --reuse-values --set networkPolicy.enabled=false -f rabbitmq-values.yaml rabbitmq-server stable/rabbitmq`

- ```yaml
rabbitmq:
  loadDefinition:
    enabled: true
    secretName: rabbitmq-load-definition
  extraConfiguration: |
    management.load_definitions = /app/load_definition.json
    vm_memory_high_watermark.relative = 0.6
    vm_memory_high_watermark_paging_ratio = 0.75
    total_memory_available_override_value = 5000MiB
    disk_free_limit.absolute = 4GiB
podManagementPolicy: Parallel
persistence:
  size: 50Gi
resources:
  requests:
    memory: 5000Mi
    cpu: 400m
  limits:
    memory: 5000Mi
    cpu: 600m
networkPolicy
    enabled: false
```

Both methods add the parameter missing in the old version.
