### ISSUE TITLE
[bitnami/jupyterhub] auxiliaryImage cannot configure more than 1 image for pre-pull

### ISSUE THREAD

**Issue by rajan123456** [bitnami/charts#18097]
### Name and Version

bitnami/jupyterhub

### What is the problem this feature will solve?

I would like to pull multiple images through the imagePuller so that my notebooks spawn fast and I do not need to wait for image pull to complete.

Currently the auxiliaryImage section allows only setting 1 image. I would like the ability to set multiple. The upstream project provides the option to provide a list of images to be pulled.

https://z2jh.jupyter.org/en/latest/administrator/optimization.html#relevant-image-sources

```yaml
auxiliaryImage:
  registry: docker.io
  repository: bitnami/os-shell
  tag: 11-debian-11-r2
  digest: ""
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  ##
  pullSecrets: []
```

### What is the feature you are proposing to solve the problem?

The auxiliaryImage section should be an array or list of images that can support multiple images to be configured.
