### ISSUE TITLE
[bitnami/thanos] chart | thanos-receive throws error with when replication.factor > 1 

### ISSUE THREAD

**Issue by gcosta-lively** [bitnami/charts#18141]
### Name and Version

bitnami/thanos 12.8.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Setup your thanos-receiver helm chat with the custom values provided
2. wait for everything to start
3. Check the logs for the thanos-receiver pods: After some minutes, the following errors appear: 
`evel=error ts=2023-07-31T13:41:41.325412906Z caller=handler.go:559 component=receive component=receive-handler tenant=default-tenant err="insufficient nodes; have 1, want 2" msg="internal server error"`

It looks like something is odd with the hashring.

Can you please help?

### Are you using any custom parameters or values?

```
metrics:
  enabled: true
  serviceMonitor:
    enabled: true

commonAnnotations: |-
  prometheus.io/scrape: 'true'
  prometheus.io/path: '/metrics'
  prometheus.io/port: '10902'

objstoreConfig: |-
  type: s3
  config:
    bucket: monitoring-data-example
    endpoint:   <URL_GOES_HERE>

query:
  autoscaling:
    enabled: true
    minReplicas: "1"
    maxReplicas: "5"
    targetCPU: "60"
    targetMemory: "70"
  resources:
    requests:
      memory: "1000Mi"
      cpu: "1"
    limits:
      memory: "1000Mi"
      cpu: "1"

queryFrontend:
  autoscaling:
    enabled: true
    minReplicas: "1"
    maxReplicas: "5"
    targetCPU: "60"
    targetMemory: "70"
  resources:
    requests:
      memory: "1000Mi"
      cpu: "1"
    limits:
      memory: "1000Mi"
      cpu: "1"

receive:
  enabled: true
  tsdbRetention: 2h
  replicationFactor: 2
  persistence: 
    size: 30Gi
  autoscaling:
    enabled: true
    minReplicas: "2"
    maxReplicas: "5"
    targetCPU: "60"
    targetMemory: "70"
  podAntiAffinityPreset: hard
  resources:
    requests:
      memory: "5000Mi"
      cpu: "1"
    limits:
      memory: "14000Mi"
      cpu: "3"

storegateway:
  enabled: true
  persistence:
    enabled: false
  autoscaling:
    enabled: true
    minReplicas: "1"
    maxReplicas: "5"
    targetCPU: "60"
    targetMemory: "70"
  resources:
    requests:
      memory: "1000Mi"
      cpu: "1"
    limits:
      memory: "1000Mi"
      cpu: "1"
```

### What do you see instead?

`evel=error ts=2023-07-31T13:41:41.325412906Z caller=handler.go:559 component=receive component=receive-handler tenant=default-tenant err="insufficient nodes; have 1, want 2" msg="internal server error"`

### Additional information

I am running this setup with ArgoCD, but it should not influence the outcome.

**Comment by andresbono** [comment]
> Have you created a setup with two thanos-receivers as mentioned above?

Exactly, but I cannot see any error logs in the pods. Do you observe the error messaged after certain time or under certain specific circumstances?

**Comment by iagosrodrigues** [comment]
I've got the same problem trying to deploy the receiver component with two replicas. Do I have to manually create a service for each pod and use the 'receive.config'?

**Comment by gcosta-lively** [comment]
> Exactly, but I cannot see any error logs in the pods. Do you observe the error messaged after certain time or under certain specific circumstances?

I see the error on the 1st pod once the 2nd pod joins. The error is super consistent

**Comment by andresbono** [comment]
Still unable to reproduce the issue, at least in a simple [kind](https://kind.sigs.k8s.io/) cluster. I'm installing the Helm chart with these equivalent values:

```yaml
receive:
  enabled: true
  replicationFactor: 2
  replicaCount: 2
```

```shell
$ kind create cluster
$ helm install thanos oci://docker.io/bitnamicharts/thanos --version 12.8.0 --set receive.enabled=true --set receive.replicationFactor=2 --set receive.replicaCount=2

# Wait for pods to be ready and check for logs with "level=error"
$ kubectl wait --for=condition=Ready pod --selector='app.kubernetes.io/component=receive'
pod/thanos-receive-0 condition met
pod/thanos-receive-1 condition met
$ kubectl logs thanos-receive-0 | grep 'level=error'
$ kubectl logs thanos-receive-1 | grep 'level=error'

# Check for logs "server is ready"
$ kubectl logs thanos-receive-0 | grep 'server is ready'
level=info ts=2023-09-01T13:48:55.545650737Z caller=receive.go:618 component=receive msg="storage started, and server is ready to receive requests"
$ kubectl logs thanos-receive-1 | grep 'server is ready'
level=info ts=2023-09-01T13:49:37.572206115Z caller=receive.go:618 component=receive msg="storage started, and server is ready to receive requests"
```

Please, share any findings. Any suggestion on how to reproduce on my side is also welcome.
