### ISSUE TITLE
[bitnami/apisix] can't disable tls mode

### ISSUE THREAD

**Issue by markeee-e** [bitnami/charts#18153]
### Name and Version

bitnami/apisix 2.0.7

### What architecture are you using?

None

### What steps will reproduce the bug?

each dep-ds.yaml files in templates
I expect the cause of this problem
hard coded volumeMounts
```yaml
          volumeMounts:
            - name: apisix-dir
              mountPath: /usr/local/apisix
            - name: tmp
              mountPath: /tmp
            - name: certs
              mountPath: /bitnami/certs`
```

### Are you using any custom parameters or values?
```
  --set dataPlane.tls.enabled=false \
  --set dataPlane.tls.autoGenerated=false \
  --set controlPlane.tls.enabled=false \
  --set controlPlane.tls.autoGenerated=false \
  --set dashboard.tls.enabled=false \
  --set dashboard.tls.autoGenerated=false \
```

### What do you see instead?

```
Error: UPGRADE FAILED: cannot patch "mk-apisix-bitnami-control-plane-tls" with kind Secret: Secret "mk-apisix-bitnami-control-plane-tls" is invalid: [data[tls.crt]: Required value, data[tls.key]: Required value] && cannot patch "mk-apisix-bitnami-control-plane" with kind Deployment: Deployment.apps "mk-apisix-bitnami-control-plane" is invalid: spec.template.spec.containers[0].volumeMounts[2].name: Not found: "certs" && cannot patch "mk-apisix-bitnami-dashboard" with kind Deployment: Deployment.apps "mk-apisix-bitnami-dashboard" is invalid: spec.template.spec.containers[0].volumeMounts[2].name: Not found: "certs" && cannot patch "mk-apisix-bitnami-data-plane" with kind Deployment: Deployment.apps "mk-apisix-bitnami-data-plane" is invalid: spec.template.spec.containers[0].volumeMounts[2].name: Not found: "certs"
```
