### ISSUE TITLE
[bitnami/gitea] Unable to mount a volume

### ISSUE THREAD

**Issue by Lexian-droid** [bitnami/charts#18177]
### Name and Version

docker.io/bitnami/gitea:1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I followed the instructions in the https://hub.docker.com/r/bitnami/gitea
I added this: ``/var/www/vhosts/lexian.dev/docker/gitea/override.ini:/bitnami/gitea/custom/conf/app.ini:ro``
However for an unknown reason, it seems to not work as expected.
It'll give an error message saying that it can't access app.ini because permission is denied.

### Are you using any custom parameters or values?

I am only using the following:
```
      - GITEA_DATABASE_HOST=postgresql
      - GITEA_DATABASE_NAME=XXX
      - GITEA_DATABASE_USERNAME=XXX
      - GITEA_DATABASE_PASSWORD=XXX
```

### What is the expected behavior?

It was expected that it would be able to read my override.ini as per the instructions, however it is unable to do so.

### What do you see instead?

 open /opt/bitnami/gitea/custom/conf/app.ini: permission denied

### Additional information

I tried adding
```
      - USER_ID=0
      - USER_GID=0
```
too but that also didn't work, I've tried making it mount to a directory instead of a file, but that didn't work either. I don't know why this is happening, as I have a mediawiki server that is also set up in a similar way to this.

Also, because some people may want to see this, I will give you my docker-compose.yml file:
```
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - USER_ID=0
      - USER_GID=0
      - POSTGRESQL_DATABASE=bitnami_gitea
      - POSTGRESQL_USERNAME=bn_gitea
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  gitea:
    image: docker.io/bitnami/gitea:1
    volumes:
      - /var/www/vhosts/lexian.dev/docker/gitea/override.ini:/bitnami/gitea/custom/conf/app.ini:ro
      - 'gitea_data:/bitnami/gitea'
    environment:
      - USER_ID=0
      - USER_GID=0
      - GITEA_DATABASE_HOST=postgresql
      - GITEA_DATABASE_NAME=bitnami_gitea
      - GITEA_DATABASE_USERNAME=bn_gitea
      - GITEA_DATABASE_PASSWORD=bitnami1
    ports:
      - '3000:3000'
      - '2222:2222'
volumes:
  postgresql_data:
    driver: local
  gitea_data:
    driver: local
```
