### ISSUE TITLE
[bitnami/airflow] ELK logging not working

### ISSUE THREAD

**Issue by alekseyolg** [bitnami/charts#18175]
### Name and Version

bitnami/airflow:14.2.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

install helm chart Airflow for Kubernetes Executor

### Are you using any custom parameters or values?

```
executor: KubernetesExecutor
extraEnvVars:
  - name: AIRFLOW_CONN_KUBERNETES_DEFAULT_BAK
    value: "kubernetes://?extra__kubernetes__in_cluster=True&extra__kubernetes__namespace='{{ .Release.Namespace }}'"
  - name: AIRFLOW_CONN_KUBERNETES_DEFAULT
    value: "kubernetes://?in_cluster=True&namespace={{ .Release.Namespace }}"
  - name: AIRFLOW__LOGGING__REMOTE_LOGGING
    value: "True"
  - name: AIRFLOW__ELASTICSEARCH_HOST
    value: "my-elk-host"
  - name: AIRFLOW__ELASTICSEARCH_PORT
    value: "9200"
  - name: AIRFLOW__ELASTICSEARCH_LOG_INDEX_PREFIX
    value: "airflow"
  - name: AIRFLOW__ELASTICSEARCH_LOG_TAGS
    value: "my-pod-operator"
  - name: AIRFLOW__ELASTICSEARCH_LOG_TO_STDOUT
    value: "True"
  - name: AIRFLOW__ELASTICSEARCH_WRITE_JSON
    value: "True"

```

### What is the expected behavior?

Saving all logs, including the airflow itself in the Christmas ELK

### What do you see instead?

All Airflow pods endlessly restart without showing any logs

### Additional information

Images version - 2.6.1-debian-11-r3

**Comment by migruiz4** [comment]
Hi @alekseyolg,

Several things to keep in mind regarding Elasticsearch logging in Airflow.

- Your env variables missing an additional underscore (`_`) after `ELASTICSEARCH_`
- The settings you have used don't seem to be correct. See [Airflow configuration reference](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#config-elasticsearch-host) and [Airflow elasticsearch logging guide](https://airflow.apache.org/docs/apache-airflow-providers-elasticsearch/stable/logging/index.html).
  Allowed settings would look similar to this:

    ```yaml
    executor: KubernetesExecutor
    extraEnvVars:
      - name: AIRFLOW__LOGGING__REMOTE_LOGGING
        value: "True"
      - name: AIRFLOW__ELASTICSEARCH__HOST
        value: "elasticsearch:9200"
      - name: AIRFLOW__ELASTICSEARCH__WRITE_STDOUT
        value: "True"
      - name: AIRFLOW__ELASTICSEARCH__JSON_FORMAT
        value: "True"
    ```

- According to [Airflow documentation](https://airflow.apache.org/docs/apache-airflow/1.10.9/howto/write-logs.html#writing-logs-to-elasticsearch), logs can be collected from Elasticsearch, but additional components are required to send those logs to Elasticsearch, such as Logstash, Fluentd, Filebeat, etc.
    > Airflow can be configured to **read** task logs from Elasticsearch and **optionally write logs to stdout** in standard or json format. These logs can later be collected and forwarded to the Elasticsearch cluster using tools like fluentd, logstash or others.
