### ISSUE TITLE
[bitnami/supabase] Implement Logflare and Edge Function

### ISSUE THREAD

**Issue by stevefan1999-personal** [bitnami/charts#18179]
### Name and Version

bitnami/supabase:0.3.14

### What is the problem this feature will solve?

These two are also open sourced in late April.

### What is the feature you are proposing to solve the problem?

Add it in the charts

**Comment by stevefan1999-personal** [comment]
Kong will need to have the following config added, reference:

```
  ## Edge Functions routes
  - name: functions-v1
    _comment: 'Edge Functions: /functions/v1/* -> http://functions:9000/*'
    url: http://functions:9000/
    routes:
      - name: functions-v1-all
        strip_path: true
        paths:
          - /functions/v1/
    plugins:
      - name: cors

  ## Analytics routes
  - name: analytics-v1
    _comment: 'Analytics: /analytics/v1/* -> http://logflare:4000/*'
    url: http://analytics:4000/
    routes:
      - name: analytics-v1-all
        strip_path: true
        paths:
          - /analytics/v1/
```

https://github.com/supabase/supabase/blob/82021367d0fc7a0386d4a5218ba5c4cb75b67d51/docker/volumes/api/kong.yml#L157-L177

**Comment by stevefan1999-personal** [comment]
And this is how the Analytics (Logflare) is done. However, this also depends on a Datadog Vector service which collects the Supabase container syslog into a digestable format. This will get a little bit tricky:

```yaml
  analytics:
    container_name: supabase-analytics
    image: supabase/logflare:1.3.17
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:4000/health" ]
      timeout: 5s
      interval: 5s
      retries: 10
    restart: unless-stopped
    depends_on:
      db:
        # Disable this if you are using an external Postgres database
        condition: service_healthy
    ports:
      - ${LOGFLARE_HTTP_PORT}:4000/tcp
    volumes:
      - type: bind
        source: ${PWD}/gcloud.json
        target: /opt/app/rel/logflare/bin/gcloud.json
        read_only: true
    environment:
      MY_POD_IP: 127.0.0.1
      DB_USERNAME: supabase_admin
      DB_DATABASE: ${POSTGRES_DB}
      DB_HOSTNAME: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SCHEMA: _analytics
      LOGFLARE_API_KEY: ${LOGFLARE_API_KEY}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      GOOGLE_PROJECT_NUMBER: ${GOOGLE_PROJECT_NUMBER}
      LOGFLARE_SINGLE_TENANT: true
      LOGFLARE_SUPABASE_MODE: true
      LOGFLARE_MIN_CLUSTER_SIZE: 1
  vector:
    container_name: supabase-vector
    image: timberio/vector:0.28.1-alpine
    healthcheck:
      test:
        [

          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:${VECTOR_API_PORT}/health"
        ]
      timeout: 5s
      interval: 5s
      retries: 3
    ports:
      - ${VECTOR_PORT}:${VECTOR_PORT}
      - ${VECTOR_API_PORT}:${VECTOR_API_PORT}
    volumes:
      - ./volumes/logs/vector.yml:/etc/vector/vector.yml:ro
    command: [ "--config", "etc/vector/vector.yml" ]
```

https://github.com/supabase/supabase/blob/daa67dd0ef7681c8e041392682e8f0ab8a51a128/docker/docker-compose-logging.yml#L94-L150
