### ISSUE TITLE
[bitnami/supabase] pg_graphql is missing

### ISSUE THREAD

**Issue by stevefan1999-personal** [bitnami/charts#18182]
### Name and Version

bitnami/supabase:0.3.14

### What is the problem this feature will solve?

#18181

### What is the feature you are proposing to solve the problem?

Add the extension, but this may need cross issue to https://github.com/bitnami/containers

### What alternatives have you considered?

Don't use GraphQL despite it is cool

**Comment by stevefan1999-personal** [comment]
Also, Kong config needs to be updated to add the GraphQL routes back, for example:

```yaml
  ## Secure GraphQL routes
  - name: graphql-v1
    _comment: 'PostgREST: /graphql/v1/* -> http://supbase-rest:80/rpc/graphql'
    url: http://supbase-rest:80/rpc/graphql
    routes:
      - name: graphql-v1-all
        strip_path: true
        paths:
          - /graphql/v1
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: true
      - name: request-transformer
        config:
          add:
            headers:
              - Content-Profile:graphql_public
      - name: acl
        config:
          hide_groups_header: true
          allow:
            - admin
            - anon
```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for opening the ticket. I will forward this to the team.

**Comment by jsmueller7** [comment]
@stevefan1999-personal  You can make this work, if you're switching to the postgres image from supabase.
That image has a hardcoded data-dir though that you can't persist without loosing the `extension` folder. So you need to mout a customized `postgresql.conf` file where you change the default data dir (you could also write a startup command that does that). Here is how the values would look alike, if you chose to mout a config map:

```
postgresql:
  image:
    registry: docker.io
    repository: supabase/postgres
    tag: 15.1.0.123
  postgresqlDataDir: /var/lib/postgresql/data/pgdata
  primary:
    extraVolumeMounts:
      - name: postgresql-default-conf
        mountPath: /etc/postgresql/postgresql.conf
        subPath: postgresql.conf
    extraVolumes:
      - name: postgresql-default-conf
        configMap:
          name: postgresql-default-conf
          items:
            - key: postgresql.conf
              path: postgresql.conf
    persistence:
      enabled: true
      mountPath: /var/lib/postgresql/data
    podSecurityContext:
      fsGroup: 102
    containerSecurityContext:
      runAsUser: 101
```
