### ISSUE TITLE
[bitnami/kafka] Provisioning not working

### ISSUE THREAD

**Issue by aabed-aa** [bitnami/charts#18191]
### Name and Version

bitnami/kafka 24.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy kafka helm chart with provisioning enabled does not work

### Are you using any custom parameters or values?

Tried:

```yaml
  provisioning:
    enabled: true
    topics:
      - name: ***
```

and:

```yaml
  provisioning:
    enabled: true
    replicationFactor: 3
    topics:
      - name: ***
```

and:

```yaml
  provisioning:
    enabled: true
    topics:
      - name: ****
        replicationFactor: 3
```

### What is the expected behavior?

Provisioning job to exectue

### What do you see instead?

Helm error:

`helm.go:84: [debug] template: ***/charts/kafka/templates/provisioning/job.yaml:156:87: executing "***/charts/kafka/templates/provisioning/job.yaml" at <.context.Values.provisioning.replicationFactor>: nil pointer evaluating interface {}.Values`

**Comment by aabed-asml** [comment]
@carrodher can this issue please be removed, I posted it using the wrong (work) account

**Comment by tbnguyen1407** [comment]
@dgomezleon Hello, even after the fix provisioning job still fails with file permission error when trying to `touch /opt/bitnami/kafka/config/client.properties`. This is due to default `readOnlyRootFilesystem` in `securityContext`.

I think the job needs to be updated to use a tmp emptyDir for `client.properties` instead of trying to generate/override `client.properties` in `kafka/config/` folder.

**Comment by tbnguyen1407** [comment]
Current workaround, which uses `emptyDir`

```
~ values.yaml ~
provisioning:
  enabled: true
  topics:
    - name: mytopic
  extraEnvVars:
    - name: CLIENT_CONF
      value: "/tmp/client.properties"
  extraVolumes:
    - name: tmp
      emptyDir: {}
  extraVolumeMounts:
    - name: tmp
      mountPath: /tmp
```
