### ISSUE TITLE
[bitnami/keycloak] Can't access admin console after install

### ISSUE THREAD

**Issue by WestFarmer** [bitnami/charts#18198]
### Name and Version

bitnami/keycloak 16.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

installed with:
```
global:
  storageClass: rook-ceph-block
```

exposed with istio `gateway`
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: security-gateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:  # match the istio-ingressgateway's service port
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: lecerts
    hosts:
    - keycloak.xxx.com
    
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak-vs
spec:
  hosts:
  - "keycloak.xxx.com"
  gateways:
  - security-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: keycloak-1691131094 #
```

### Are you using any custom parameters or values?

```
global:
  storageClass: rook-ceph-block
```

### What is the expected behavior?

 can access keycloak admin console

### What do you see instead?

 can access the landing page, but when click "Administration Console", "Loading Admin UI" spinning forever.

from browser's console:

it's loading `http://keycloak.xxx.com/realms/master/protocol/openid-connect/3p-cookies/step1.html`

`http` used instead of `https`

while using port-forwading, it works.

**Comment by javsalgar** [comment]
Hi!

Note that we do not test our charts directly with Istio, so we cannot guarantee its support. Did you try accessing without Istio, just to confirm is the issue lies there?

**Comment by WestFarmer** [comment]
> Hi!
> 
> Note that we do not test our charts directly with Istio, so we cannot guarantee its support. Did you try accessing without Istio, just to confirm is the issue lies there?

I tried port-forwading, it works.

**Comment by WestFarmer** [comment]
tried to append extra environment variable: 
```
global:
  storageClass: rook-ceph-block
  imageRegistry: "172.25.128.67:9002"
  
metrics:
  enabled: true
  serviceMonitor:
    enabled: false
    
keycloak:
  extraEnvVars:
    - name: KC_HOSTNAME_URL
      value: "https://keycloak.bgzchina.com"
```

bug why pod still don't have KC_HOSTNAME_URL:

![图片](https://github.com/bitnami/charts/assets/14016562/f1537790-8399-4aaf-adff-82664dcdddf9)

**Comment by WestFarmer** [comment]
I will go to following this issue: https://github.com/keycloak/keycloak/issues/14666

**Comment by WestFarmer** [comment]
for anyone face the same issue:
if you are using ingress or istio gateway to expose keycloak under `https`, while keycloak is running in pure `http`

you should config extra envs for keycloak container:

```
extraEnvVars:
- name: KC_HOSTNAME_URL
  value: https://keycloak.bgzchina.com
- name: KC_HOSTNAME_ADMIN_URL
  value: https://keycloak.bgzchina.com
```

**Comment by deba10106** [comment]
I'm facing the same issue! Found any solution?

**Comment by deba10106** [comment]
sorry, Yes it's fixed now following your comments! Thanks.


*Thanks and Regards,*
Debasis Mondal

**Comment by h4tt3n** [comment]
> for anyone face the same issue: if you are using ingress or istio gateway to expose keycloak under `https`, while keycloak is running in pure `http`
> 
> you should config extra envs for keycloak container:
> 
> ```yaml
> extraEnvVars:
> - name: KC_HOSTNAME_URL
>   value: https://keycloak.xxx.com
> - name: KC_HOSTNAME_ADMIN_URL
>   value: https://keycloak.xxx.com
> ```

This solved it for me. Running Bitnami Keycloak Helm chart on Azure kubernetes cluster.

**Comment by daniel-be-sw** [comment]
this solution unfortunately breaks my client auth inside my k8s cluster...
for example using curl command to one of the realms under my SVC name, for eg:
`curl keycloak.keycloak.svc.cluster.local](http://keycloak-headless.keycloak.svc.cluster.local:8080/realms/XXXX)`
I get response from the KC_HOSTNAME_URL but I dont want to get response from the URL, I need response from the SVC with the correct port -> 8080.

If not my application return:
`Caused by: java.lang.IllegalStateException: The Issuer "http://keycloak-headless.keycloak.svc.cluster.local/realms/XXX" provided in the configuration metadata did not match the requested issuer "http://keycloak-headless.keycloak.svc.cluster.local:8080/realms/XXX"`

using the same setup with istio gateway + istio virtual service + istio injection in keycloak + application namespaces

**Comment by dominicbinarly** [comment]
> this solution unfortunately breaks my client auth inside my k8s cluster... for example using curl command to one of the realms under my SVC name, for eg: `curl http://keycloak-headless.keycloak.svc.cluster.local:8080/realms/XXXX` I get response from the KC_HOSTNAME_URL but I dont want to get response from the URL, I need response from the SVC with the correct port -> 8080.
> 
> If not my application return: `Caused by: java.lang.IllegalStateException: The Issuer "http://keycloak-headless.keycloak.svc.cluster.local/realms/XXX" provided in the configuration metadata did not match the requested issuer "http://keycloak-headless.keycloak.svc.cluster.local:8080/realms/XXX"`
> 
> using the same setup with istio gateway + istio virtual service + istio injection in keycloak + application namespaces

More than a year after your question, but I thought I'd add here in case anyone stumbles on this issue. For me this was down to the network policy deployed by the chart. I added:

```
spec:
  egress:
    - {}
  ingress:
    - ports:
        - port: 7800
          protocol: TCP
        - port: 8080
          protocol: TCP
        - port: 15008 # This entry is required or the netpol will block mesh traffic
          protocol: TCP
```

I ended up turning the netpol off and adding my own
