### ISSUE TITLE
[bitnami/kafka] kafka.config requires to be supplied with an array

### ISSUE THREAD

**Issue by edebosz-inka** [bitnami/charts#18204]
### Name and Version

bitnami/kafka 24.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy kafka with default values.yaml file.

### Are you using any custom parameters or values?

```yaml
...
global:
  imageRegistry: proxy.repo
...
resources:
  nodeSelector: 
    foo: bar
...
broker:
  nodeSelector: 
    foo: bar
...
metrics:
    nodeSelector: 
      foo: bar
...
provisioning:
  nodeSelector: 
    foo: bar
...
```

### What is the expected behavior?

No warning during deployment.

### What do you see instead?

```
coalesce.go:223: warning: destination for kafka.broker.config is a table. Ignoring non-table value ()
coalesce.go:175: warning: skipped value for kafka.config: Not a table.
coalesce.go:175: warning: skipped value for kafka.config: Not a table.
coalesce.go:223: warning: destination for kafka.broker.config is a table. Ignoring non-table value ()
```

### Additional information

Solution:
change values.yaml value
L109 
from: `config: ""`
to: `config: []`
and update README.md

Please verify that value under values.yaml:
```yaml
controller:
  config: ""
```
is set correctly in values.yaml and documentation.

Please verify that value under values.yaml:
```yaml
broker:
  config: ""
```
is set correctly in values.yaml and documentation.
