### ISSUE TITLE
[bitnami/kafka] nodeSelector is not assigned properly for kafka-controller

### ISSUE THREAD

**Issue by edebosz-inka** [bitnami/charts#18203]
### Name and Version

bitnami/kafka 24.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Set up Kubernetes policy to require nodeSelector, set node selector as eg.:
```yaml
  nodeSelector: 
    foo: bar
```
I set up all 4 available nodeSelectors just in case.
Deploy:
`helm install--kubeconfig=${KUBECONFIG} -f values.yaml kafka oci://registry-1.docker.io/bitnamicharts/kafka --namespace ${NAMESPACE} --version 24.0.1`

### Are you using any custom parameters or values?

I'm using provided value file with changes in:
```yaml
...
global:
  imageRegistry: proxy.repo
...
resources:
  nodeSelector: 
    foo: bar
...
broker:
  nodeSelector: 
    foo: bar
...
metrics:
    nodeSelector: 
      foo: bar
...
provisioning:
  nodeSelector: 
    foo: bar
...
```

### What is the expected behavior?

The node selector is supplied for deployment.

### What do you see instead?

```
require-node-selector:
  autogen-require-node-selector: 'validation error: Missing required nodeSelector
    "foo: bar/eventmesh/gh-runners". rule autogen-require-node-selector failed
    at path /spec/template/spec/nodeSelector/'
```

**Comment by migruiz4** [comment]
Hi @edebosz-inka,

I tried to reproduce your issue using the following values.yaml but I haven't been able to:
```yaml
resources:
  nodeSelector: 
    foo: bar
controller:
  nodeSelector:
    foo: bar
broker:
  nodeSelector: 
    foo: bar
metrics:
    nodeSelector: 
      foo: bar
provisioning:
  nodeSelector: 
    foo: bar
```

Is it possible you may have missed `controller.nodeSelector`?

You could try debugging this issue by executing the `helm install` command using the flag `--dry-run`. That may shed some light on what manifest is missing the nodeSelector section.
