### ISSUE TITLE
seccompProfile definition cannot be unset

### ISSUE THREAD

**Issue by seggcsont** [bitnami/charts#18230]
### Name and Version

registry-1.docker.io/bitnamicharts/redis:17.14.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Generate helm template and set `redis.master.containerSecurityContext.seccompProfile=null`

### Are you using any custom parameters or values?
```
--set redis.master.containerSecurityContext.seccompProfile=null
```
### What is the expected behavior?

seccompProfile is not set in the master StatefulSet

### What do you see instead?

It is set with the default RuntimeDefault value.

### Additional information
Redis used as a dependency:
```yaml
apiVersion: v2
appVersion: 0.1.0
description: A Helm chart for Kubernetes
name: myapp
type: application
version: 0.1.55
dependencies:
  - name: redis
    version: 17.14.5
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
```

Creating helm template for only redis works as expected, seccompProfile is not there. But it "fails" as dependency. 
I can update the seccompProfile.type without any issue.

Our cluster rejects the deployment with this error:
```
statefulset-controller  create Pod ps-redis-master-0 in StatefulSet ps-redis-master failed ││  error: pods "ps-redis-master-0" is forbidden: PodSecurityPolicy: unable to admit pod: [pod.metadata.annotations[container.seccomp.security.al ││ pha.kubernetes.io/redis]: Forbidden: seccomp may not be set]
```

**Comment by bondbenbond** [comment]
Seeing this same issue for the Kafka chart when using kafka as a dependency:

`Chart.yaml`
```
apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: myapp
type: application
version: 0.1.0
dependencies:
  - name: kafka
    version: 24.0.5
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: kafka.enabled
```

`values.yaml`
```
kafka:
  enabled: true

  controller:
    podSecurityContext:
      seccompProfile: null
```

`statefulset.yaml`
```
# Source: kafka/templates/controller-eligible/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-kafka-controller
.
.
.
spec:
.
.         
      securityContext:
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
```

Thanks!
