### ISSUE TITLE
[bitnami/keycloak] StartTLS is not working with LDAP even with a truststore configured (however LDAPS works)

### ISSUE THREAD

**Issue by MohammedNoureldin** [bitnami/charts#18290]
### Name and Version

https://artifacthub.io/packages/helm/bitnami/keycloak
16.0.3
(4 Aug, 2023)

### Issue description

Does StartTLS with LDAP work for anybody? For me, when I try to connect to an LDAP server over LDAPS, both connection and authentication work properly, and removing the certificate causes LDAPS to fail, which proves that the CA in my truststore works well.

However, when I use StartTLS (ldap://..) the connection fails with the following error:

> Error when connecting to LDAP: Could not negotiate TLS: javax.naming.AuthenticationException: Could not negotiate TLS [Root exception is javax.naming.CommunicationException: Connection reset [Root exception is java.net.SocketException: Connection reset]]

I am not sure what is wrong here, because as shown above, the certificate seems to be trusted by my truststore.

### Are you using any custom parameters or values?

The interesting part is (here I am creating the truststore on the fly, and it is created successfully, I check that, and used it with LDAPS):

```
      extraEnvVars:
        # SPI: Trusts the certificate of LDAP provider.
        # The SPI variables provided by the Helm chart were not used, to be able to generate the truststore in the container directly using `keytool`.
        - name: KEYCLOAK_SPI_TRUSTSTORE_FILE_HOSTNAME_VERIFICATION_POLICY
          value: "WILDCARD"
        - name: KEYCLOAK_SPI_TRUSTSTORE_FILE
          value: "/opt/bitnami/keycloak/spi-certs/truststore.jks"
        - name: KEYCLOAK_SPI_TRUSTSTORE_PASSWORD
          value: "nopass" # Password is not needed because the truststore includes no private keys.
      initdbScripts:
        truststore-init.sh: |
          echo "Creating a trust store (JKS) from ca.crt"
          mkdir /opt/bitnami/keycloak/spi-certs
          keytool -importcert -file /tmp/certs/ca.crt -keystore /opt/bitnami/keycloak/spi-certs/truststore.jks -storepass "nopass" -noprompt
```

### What is the expected behavior?

StartTLS should work also.

### What do you see instead?

StartTLS is not working.

> Error when connecting to LDAP: Could not negotiate TLS: javax.naming.AuthenticationException: Could not negotiate TLS [Root exception is javax.naming.CommunicationException: Connection reset [Root exception is java.net.SocketException: Connection reset]]

### Additional information

Can this be related to the need of adding ldap.conf somewhere? I wanted to try that, but the pod runs as a non-privileged user, thus it was not possible to try creating a ldap.conf file.

What can we do here to get StartTLS working for LDAP?
