### ISSUE TITLE
Envoy initContainer resources are mapped to contour resources

### ISSUE THREAD

**Issue by denraf** [bitnami/charts#18365]
### Name and Version

bitnami/contour 11.3.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Helm chart with the below values

### Are you using any custom parameters or values?
```yaml
contour:
  resources:
    requests:
      cpu: 0.2
      memory: 5G

envoy:
  resources:
    requests:
      cpu: 0.1
      memory: 350m
```
### What is the expected behavior?

Contour resources used by contour
Envoy resources used by envoy

### What do you see instead?

The init container from envoy is using contour resources

### Additional information

In our setup, contour has a much higher memory consumption (5G), and thus resources, then envoy (350M)
Since the initContainer is using the contour resources, the node with reserve the resource request of contour for envoy, leaving a lot of memory unused.
