### ISSUE TITLE
bitnami/fluentd 5.8.2 can't set aggregator.initScriptsCM

### ISSUE THREAD

**Issue by sturmf** [bitnami/charts#18377]
### Name and Version

bitnami/fluentd 5.8.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Add a config map for a custom init script. E.g.:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-initscripts
data:
  fluentd-plugins.sh: |
    #! /bin/sh
    fluent-gem install fluent-plugin-influxdb-v2 -v 1.10.0

```

Now reference this config map in the kutomization.yaml file 

```
bases:
  - ../../../../base
resources:
  - fluentd-configmap.yaml
  - fluentd-initscripts-configmap.yaml
helmCharts:
  - name: fluentd
    repo: https://charts.bitnami.com/bitnami
    version: 5.8.2
    valuesInline:
      aggregator:
        configMap: fluentd-configuration
        initScriptsCM: fluentd-initscripts

```

On rendering this template I get:

```
oc kustomize  --enable-helm
error: Error: template: fluentd/templates/aggregator-statefulset.yaml:236:30: executing "fluentd/templates/aggregator-statefulset.yaml" at <{{template ".Values.initScriptsCM" .}}>: template ".Values.initScriptsCM" not defined
```

### What is the expected behavior?

I would expect the template to render without any errors

### What do you see instead?

error: Error: template: fluentd/templates/aggregator-statefulset.yaml:236:30: executing "fluentd/templates/aggregator-statefulset.yaml" at <{{template ".Values.initScriptsCM" .}}>: template ".Values.initScriptsCM" not defined

### Additional information

I maybe got the idea wrong how to add custom init scripts?
