### ISSUE TITLE
bitnami/kong specifying database name in postgresql.external values does not take effect

### ISSUE THREAD

**Issue by digitalray** [bitnami/charts#18381]
### Name and Version

bitnamicharts/kong 9.4.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy kong using the custom values file
2. Create an external postgresql database with the name: `kongapigateway` and kong user that has privilege on that db.

### Are you using any custom parameters or values?

```yaml    
ingress:
  enabled: true
  ingressClassName: kong
ingressController:
  enabled: false
postgresql:
  enabled: false
  external:
    host: "redacted"
    port: "5432"
    user: redacted
    password: redacted
    database: "kongapigateway"
image:
  debug: true
```

### What is the expected behavior?

The postgresql.external.database value specified in the values yaml file should cause creation of environment variable `KONG_PG_DATABASE` which then should be used by kong to connect to the database specified.

### What do you see instead?

We are getting the following error insted:
```shell
Run with --v (verbose) or --vv (debug) for more details
kong 18:11:05.43 DEBUG ==> Database is still not ready, will retry
kong 18:11:06.63 DEBUG ==> Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: FATAL: database "kong" does not exist
```

### Additional information

Here are the environment variables inside the migration pod:
```shell
KONG_PG_PORT=5432
KONG_PG_USER=redacted
KONG_DATABASE=postgres
KONG_PG_PASSWORD=redacted
KONG_PG_HOST=redacted
```
As you can see, there is no `KONG_PG_DATABASE`
