### ISSUE TITLE
Prometheus

### ISSUE THREAD

**Issue by pomland-94** [bitnami/charts#18385]
### Name and Version

bitnami/prometehus:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?
```
helm install prometheus bitnami/prometheus --namespace prometheus --create-namespace -f values.yaml
```
```yaml
alertmanager:
  configuration: |
    receivers:
      - name: default-receiver
    route:
      group_wait: 10s
      group_interval: 5m
      receiver: default-receiver
      repeat_interval: 3h
  replicaCount: 2
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    runAsUser: 1001
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  service:
    type: ClusterIP
  persistence:
    enabled: true
    mountPath: /bitnami/alertmanager/data
    storageClass: "rook-cephfs"
    accessModes:
      - ReadWriteOnce
    size: 50Gi
server:
  configuration: |
    global:
      {{- if .Values.server.scrapeInterval }}
      scrape_interval: {{ .Values.server.scrapeInterval }}
      {{- end }}
      {{- if .Values.server.scrapeTimeout }}
      scrape_timeout: {{ .Values.server.scrapeTimeout }}
      {{- end }}
      {{- if .Values.server.evaluationInterval }}
      evaluation_interval: {{ .Values.server.evaluationInterval }}
      {{- end }}
      external_labels:
        monitor: {{ template "common.names.fullname" . }}
        {{- if .Values.server.externalLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.server.externalLabels "context" $) | nindent 4 }}
        {{- end }}
    {{- if .Values.server.remoteWrite }}
    remote_write: {{- include "common.tplvalues.render" (dict "value" .Values.server.remoteWrite "context" $) | nindent 4 }}
    {{- end }}
    scrape_configs:
      - job_name: prometheus
      {{- include "prometheus.scrape_config" (dict "component" "server" "context" $) | nindent 4 }}
    {{- if .Values.alertmanager.enabled }}
      - job_name: alertmanager
        {{- include "prometheus.scrape_config" (dict "component" "alertmanager" "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.server.extraScrapeConfigs}}
    {{- include "common.tplvalues.render" (dict "value" .Values.server.extraScrapeConfigs "context" $) | nindent 2 }}
    {{- end }}
    {{- if or .Values.alertmanager.enabled .Values.server.alertingEndpoints}}
    alerting:
      alertmanagers:
        {{- if .Values.server.alertingEndpoints }}
        {{- include "common.tplvalues.render" (dict "value" .Values.server.alertingEndpoints "context" $) | nindent 4 }}
        {{- end }}
        - scheme: HTTP
          static_configs:
            - targets: [ "{{ printf "%s.%s.svc.%s:%d" (include "prometheus.alertmanager.fullname" .) (include "common.names.namespace" .) .Values.clusterDomain (int .Values.alertmanager.service.ports.http) }}" ]
    rule_files:
      - rules.yaml
    {{- end }}
  replicaCount: 1
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    runAsUser: 1001
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  service:
    type: ClusterIP
  persistence:
    enabled: true
    storageClass: "rook-cephfs"
    accessModes:
      - ReadWriteOnce
    size: 50Gi
```

### What is the expected behavior?

In the new Chart, there is no Prometheus Operator anymore. When i install with the following values above and try to install another chart with serviceMonitor enabled true I'll get the following error:

`Error: UPGRADE FAILED: resource mapping not found for name: "node-exporter" namespace: "node-exporter" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first`

This means that Prometheus does not install the CRDs anymore. This should be fixed or I'm wrong?
