### ISSUE TITLE
kube-prometheus init-container ContainerSecurityContext not confugureable

### ISSUE THREAD

**Issue by pomland-94** [bitnami/charts#18392]
### Name and Version

bitnami/kube-prometheus:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

When I try to set up kube-prometheus I'll get the following error in my stateful sets:

### Are you using any custom parameters or values?

```yaml
operator:
  enabled: true
  podSecurityContext:
    enabled: true
    runAsUser: 1001
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    capabilities:
      drop:
      - ALL
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    seccompProfile:
      type: RuntimeDefault
  service:
    type: ClusterIP
    ports:
      http: 8080
  serviceMonitor:
    enabled: true
  kubeletService:
    enabled: true
    namespace: kube-system
prometheus:
  enabled: true
  podSecurityContext:
    enabled: true
    runAsUser: 1001
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
    capabilities:
      drop:
        - ALL
  serviceMonitor:
    enabled: true
  enableAdminAPI: false
  enableFeatures: []
  retention: 90d
  replicaCount: 3
  shards: 3
  persistence:
    enabled: true
    storageClass: "rook-cephfs"
    accessModes:
      - ReadWriteOnce
    size: 75Gi
  thanos:
    create: false
    containerSecurityContext:
      enabled: true
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
    ## @param prometheus.thanos.objectStorageConfig.secretName Support mounting a Secret for the objectStorageConfig of the sideCar container.
    ## @param prometheus.thanos.objectStorageConfig.secretKey Secret key with the configuration file.
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/thanos.md
    ## objectStorageConfig:
    ##    secretName: thanos-objstore-config
    ##    secretKey: thanos.yaml
    ##
    objectStorageConfig:
      secretName: ""
      secretKey: thanos.yaml
  configReloader:
    service:
      enabled: false
    serviceMonitor:
      enabled: false
alertmanager:
  enabled: true
  podSecurityContext:
    enabled: true
    runAsUser: 1001
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
    capabilities:
      drop:
        - ALL
  initContainers:
    containerSecurityContext:
      enabled: true
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      runAsNonRoot: true
      capabilities:
        drop: ["ALL"]
  pdb:
    create: false
    minAvailable: 1
    maxUnavailable: ""
  service:
    ports:
      http: 9093
  serviceMonitor:
    enabled: true
  ## Alertmanager configuration
  ## ref: https://prometheus.io/docs/alerting/configuration/#configuration-file
  ## @param alertmanager.config [object] Alertmanager configuration directive
  ## @skip alertmanager.config.route.group_by
  ## @skip alertmanager.config.route.routes
  ## @skip alertmanager.config.receivers
  ##
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
        - match:
            alertname: Watchdog
          receiver: 'null'
    receivers:
      - name: 'null'
  ## @param alertmanager.templateFiles Extra files to be added inside the `alertmanager-{{ template "kube-prometheus.alertmanager.fullname" . }}` secret.
  ##
  templateFiles: {}
  ## @param alertmanager.externalConfig Alertmanager configuration is created externally. If true, `alertmanager.config` is ignored, and a secret will not be created.
  ## Alertmanager requires a secret named `alertmanager-{{ template "kube-prometheus.alertmanager.fullname" . }}`
  ## It must contain:
  ##     alertmanager.yaml: <config>
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/alerting.md#alerting
  ##
  externalConfig: false
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: "rook-cephfs"
    accessModes:
      - ReadWriteOnce
    size: 25Gi
exporters:
  node-exporter:
    enabled: false
  kube-state-metrics:
    enabled: false
kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    https: true
blackboxExporter:
  enabled: true
  replicaCount: 1
  ## @param blackboxExporter.configuration [object] Blackbox Exporter configuration
  ##
  configuration:  |
    "modules":
      "http_2xx":
        "http":
          "preferred_ip_protocol": "ip4"
        "prober": "http"
      "http_post_2xx":
        "http":
          "method": "POST"
          "preferred_ip_protocol": "ip4"
        "prober": "http"
      "irc_banner":
        "prober": "tcp"
        "tcp":
          "preferred_ip_protocol": "ip4"
          "query_response":
          - "send": "NICK prober"
          - "send": "USER prober prober prober :prober"
          - "expect": "PING :([^ ]+)"
            "send": "PONG ${1}"
          - "expect": "^:[^ ]+ 001"
      "pop3s_banner":
        "prober": "tcp"
        "tcp":
          "preferred_ip_protocol": "ip4"
          "query_response":
          - "expect": "^+OK"
          "tls": true
          "tls_config":
            "insecure_skip_verify": false
      "ssh_banner":
        "prober": "tcp"
        "tcp":
          "preferred_ip_protocol": "ip4"
          "query_response":
          - "expect": "^SSH-2.0-"
      "tcp_connect":
        "prober": "tcp"
        "tcp":
          "preferred_ip_protocol": "ip4"

  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    runAsUser: 1001
    capabilities:
      drop: ["ALL"]
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
kubeApiServer:
  enabled: true
kubeControllerManager:
  enabled: true
  service:
    enabled: true
    ports:
      http: 10257
    targetPorts:
      http: 10257
  serviceMonitor:
    https: true
    insecureSkipVerify: true
kubeScheduler:
  enabled: true
  service:
    enabled: true
    ports:
      http: 10257
    targetPorts:
      http: 10257
  serviceMonitor:
    https: true
    insecureSkipVerify: true
coreDns:
  enabled: true
  namespace: kube-system
  service:
    enabled: true
    ports:
      http: 9153
    targetPorts:
      http: 9153
kubeProxy:
  enabled: true
  namespace: kube-system
  service:
    enabled: true
    ports:
      http: 10249
    targetPorts:
      http: 10249
  serviceMonitor:
    https: true
rbac:
  create: true
  pspEnabled: true
```

### What do you see instead?

```
Events:
  Type     Reason            Age                From                    Message
  ----     ------            ----               ----                    -------
  Normal   SuccessfulCreate  24s                statefulset-controller  create Claim alertmanager-monitor-kube-prometheus-alertmanager-db-alertmanager-monitor-kube-prometheus-alertmanager-0 Pod alertmanager-monitor-kube-prometheus-alertmanager-0 in StatefulSet alertmanager-monitor-kube-prometheus-alertmanager success
  Warning  FailedCreate      3s (x13 over 24s)  statefulset-controller  create Pod alertmanager-monitor-kube-prometheus-alertmanager-0 in StatefulSet alertmanager-monitor-kube-prometheus-alertmanager failed error: pods "alertmanager-monitor-kube-prometheus-alertmanager-0" is forbidden: violates PodSecurity "restricted:latest": runAsNonRoot != true (pod or container "init-config-reloader" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "init-config-reloader" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
root@admingw-01:~# kubectl -n prometehus edit statefulset.apps/alertmanager-monitor-kube-prometheus-alertmanager
```

### Additional information

Make init containers more configurable with ContainerSecurityContext
