### ISSUE TITLE
loadBalancerSourceRanges in Cassandra helm chart not taking list of IP ranges

### ISSUE THREAD

**Issue by prince129** [bitnami/charts#18395]
### Name and Version

bitnami/cassandra version 10.4.4

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Applying Cassandra helm release with below defined values for service is not applying or helm release says upgrade retries exhausted. We want to apply loadBalancerSourceRanges for loadbalancer service. While applying below values to helm release the error is thrown out.
Only providing single IP in list works like: 
```yaml
values:
    dbUser:
      password: "support" #default cassandra user is "cassandra"
    service:
      allocateLoadBalancerNodePorts: false
      annotations:
          service.beta.kubernetes.io/azure-load-balancer-resource-group: *****kube-****-***-******
          service.beta.kubernetes.io/azure-load-balancer-ipv4: ***.***.***.***
      type: "LoadBalancer"
      ports:
        cql: 9042
      externalTrafficPolicy: "Local"
      loadBalancerIP: ***.***.***.***
      **loadBalancerSourceRanges: [155.***.***.**5/32]**
    persistence:
      storageClass: "hdd"
      accessModes:
        - "ReadWriteOnce"
      size: "8Gi"
```
But while applying below configuration it fails:
```yaml
values:
    dbUser:
      password: "support" #default cassandra user is "cassandra"
    service:
      allocateLoadBalancerNodePorts: false
      annotations:
          service.beta.kubernetes.io/azure-load-balancer-resource-group: *****kube-****-***-******
          service.beta.kubernetes.io/azure-load-balancer-ipv4: ***.***.***.***
      type: "LoadBalancer"
      ports:
        cql: 9042
      externalTrafficPolicy: "Local"
      loadBalancerIP: ***.***.***.***
      **loadBalancerSourceRanges: ["155.***.***.215/32", "155.***.***.19/32"]
    persistence:
      storageClass: "hdd"
      accessModes:
        - "ReadWriteOnce"
      size: "8Gi"
```
Failure Message:
Helm upgrade failed: cannot patch "cassandra-release" with kind Service: Service "cassandra-release" is invalid: spec.LoadBalancerSourceRanges: Invalid value: "[155.***.***.215/32 155.***.***.19/32]": must be a list of IP ranges. For example, 10.240.0.0/24,10.250.0.0/24 Last Helm logs: preparing upgrade for cassandra-release resetting values to the chart's original version performing update for cassandra-release creating upgraded release for cassandra-release warning: Upgrade "cassandra-release" failed: cannot patch "cassandra-release" with kind Service: Service "cassandra-release" is invalid: spec.LoadBalancerSourceRanges: Invalid value: "[155.***.***.215/32 155.***.***.19/32]": must be a list of IP ranges. For example, 10.240.0.0/24,10.250.0.0/24

### Are you using any custom parameters or values?

```yaml
values:
    dbUser:
      password: "support" #default cassandra user is "cassandra"
    service:
      allocateLoadBalancerNodePorts: false
      annotations:
          service.beta.kubernetes.io/azure-load-balancer-resource-group: *****kube-****-***-******
          service.beta.kubernetes.io/azure-load-balancer-ipv4: ***.***.***.***
      type: "LoadBalancer"
      ports:
        cql: 9042
      externalTrafficPolicy: "Local"
      loadBalancerIP: ***.***.***.***
      **loadBalancerSourceRanges: ["155.***.***.215/32", "155.***.***.19/32"]
    persistence:
      storageClass: "hdd"
      accessModes:
        - "ReadWriteOnce"
      size: "8Gi"
```

### What is the expected behavior?

Should add the loadBalancerSourceRanges as list to service.yml

### What do you see instead?
```
Helm upgrade failed: cannot patch "cassandra-release" with kind Service: Service "cassandra-release" is invalid: spec.LoadBalancerSourceRanges: Invalid value: "[155.***.***.215/32 155.***.***.19/32]": must be a list of IP ranges. For example, 10.240.0.0/24,10.250.0.0/24 Last Helm logs: preparing upgrade for cassandra-release resetting values to the chart's original version performing update for cassandra-release creating upgraded release for cassandra-release warning: Upgrade "cassandra-release" failed: cannot patch "cassandra-release" with kind Service: Service "cassandra-release" is invalid: spec.LoadBalancerSourceRanges: Invalid value: "[155.***.***.215/32 155.***.***.19/32]": must be a list of IP ranges. For example, 10.240.0.0/24,10.250.0.0/24
```
