### ISSUE TITLE
[bitnami/spark] unable to start cluster in  with SSL

### ISSUE THREAD

**Issue by ETisREAL** [bitnami/charts#18427]
### Name and Version

bitnami/spark 7.1.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Trying to install the chart with security.ssl.autoGenerated = true will fail (init cert)
2. The same if I try to import my own .pem files (as from the script tls.key, tls.crt, ca.crt) in a secret specified as security.ssl.existingSecret = spark-secret

### Are you using any custom parameters or values?

No

Here is my values.yaml security section file if it can be useful:
```yaml
security:
  ## @param security.passwordsSecretName Name of the secret that contains all the passwords
  ## This is optional, by default random passwords are generated
  ##
  passwordsSecretName: spark-secret

  rpc:
    authenticationEnabled: false
    encryptionEnabled: false

  storageEncryptionEnabled: false
  
  ssl:
    enabled: false
    needClientAuth: false
    protocol: TLSv1.2
  
    ## @param security.ssl.existingSecret Name of the existing secret containing the TLS certificates
    ## It should contains two keys called "spark-keystore.jks" and "spark-truststore.jks" with the files in JKS format.
    ##
    # existingSecret: spark-secret
    ## @param security.ssl.autoGenerated Create self-signed TLS certificates. Currently only supports PEM certificates
    ## The Spark container will generate a JKS keystore and trustore using the PEM certificates.
    ##
    autoGenerated: true
    
    keystorePassword: ""
    truststorePassword: "strong-pwd"
    
    resources:
      ## Example:
      ## limits:
      ##    cpu: 100m
      ##    memory: 128Mi
      ##
      limits: {}
      ## Examples:
      ## requests:
      ##    cpu: 100m
      ##    memory: 128Mi
      ##
      requests: {}
```

### What is the expected behavior?

It should start the cluster with SSL mode enabled

### What do you see instead?

Error startup (init cert), but it doesn't specify any of the error messages that are specified in the init script

**Comment by ETisREAL** [comment]
@rafariossaa The pod won't even start, and it returns this message: 'Defaulted container "spark-master" out of: spark-master, init-certs (init)'

This is the security configuration: 
```
security:
  ## @param security.passwordsSecretName Name of the secret that contains all the passwords
  ## This is optional, by default random passwords are generated
  ##
  passwordsSecretName: spark-secret

  rpc:
    authenticationEnabled: false
    encryptionEnabled: false

  storageEncryptionEnabled: false
  
  ssl:
    enabled: true
    needClientAuth: false
    protocol: TLSv1.2
  
    ## @param security.ssl.existingSecret Name of the existing secret containing the TLS certificates
    ## It should contains two keys called "spark-keystore.jks" and "spark-truststore.jks" with the files in JKS format.
    ##
    # existingSecret: spark-secret
    ## @param security.ssl.autoGenerated Create self-signed TLS certificates. Currently only supports PEM certificates
    ## The Spark container will generate a JKS keystore and trustore using the PEM certificates.
    ##
    autoGenerated: true
    
    keystorePassword: ""
    truststorePassword: "strong-pwd"
    
    resources:
      ## Example:
      ## limits:
      ##    cpu: 100m
      ##    memory: 128Mi
      ##
      limits: {}
      ## Examples:
      ## requests:
      ##    cpu: 100m
      ##    memory: 128Mi
      ##
      requests: {}
```
 In the secret I have specified the tls.key, tls.crt, ca.crt and password
