### ISSUE TITLE
[bitnami/cert-manager] CRDs are outdated

### ISSUE THREAD

**Issue by krakowski** [bitnami/charts#18558]
### Name and Version

bitnami/cert-manager 0.11.13

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install the `bitnami/cert-manager` chart with `installCRDs` set to `true`.
2. Try to create a `Issuer` according to [cert-manager documentation](https://cert-manager.io/docs/configuration/acme/http01/#configuring-the-http01-ingress-solver)
    ```yaml
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: example-issuer
    spec:
      acme:
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
          name: example-issuer-account-key
        solvers:
        - http01:
            ingress:
              ingressClassName: nginx
    ```

### Are you using any custom parameters or values?

`--set installCRDs=true`

### What is the expected behavior?

The `Issuer` resource should be created.

### What do you see instead?

```
strict decoding error: unknown field "spec.acme.solvers[0].http01.ingress.ingressClassName"
```

### Additional information

According to the [README](https://github.com/bitnami/charts/tree/main/bitnami/cert-manager#to-050), the templates were synchronized with version `1.8` (March 2022) of `cert-manager`. This version's CRDs don't contain the `ingressClassName` field.

Using the `kubernetes.io/ingress.class` annotation results in the following deprecation warning during runtime:

```
1 warnings.go:70] annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
```
