### ISSUE TITLE
[bitnami/mariadb-galera] Readiness probe failed

### ISSUE THREAD

**Issue by obeyler** [bitnami/charts#18642]
### Name and Version

bitnami/mariadb-galera:9.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

just install it

### Are you using any custom parameters or values?

```
db:
  name: "strapi"
  user: "strapi"
  forcePassword: true
persistence:
  storageClass: longhorn
podAnnotations:
  backup.velero.io/backup-volumes: data
service:
  type: NodePort
  nodePorts:
    mysql:  31473
```

### What do you see instead?
```
Readiness probe failed: mysqladmin: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mariadb/bin/mariadb-admin' instead 
mysqladmin: connect to server at 'localhost' failed error: 'Can't connect to local server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)' Check that mariadbd is running and that the socket: '/opt/bitnami/mariadb/tmp/mysql.sock' exists! 
```
### Additional information
The pod restart as the probe failed 
_No response_
