### ISSUE TITLE
[bitnami/redis-cluster] network policy problem

### ISSUE THREAD

**Issue by mak241265** [bitnami/charts#18671]
### Name and Version

bitnami/redis-cluster-8.6.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

install redis cluster with network policy enable

### Are you using any custom parameters or values?
```
networkPolicy:
  enabled: true
  allowExternal: true
  ingressNSMatchLabels:
     redis: external
  ingressNSPodMatchLabels:
    redis-client: true
```

What is the expected behavior?
As i red the document of bitnami i found something which can be wrong.it is said by doc:With networkPolicy.ingressNSMatchLabels pods from other namespaces can connect to redis. Set networkPolicy.ingressNSPodMatchLabels to match pod labels in matched namespace. For example, for a namespace labeled redis=external and pods in that namespace labeled redis-client=true the fields should be set:
```
networkPolicy:
  enabled: true
  ingressNSMatchLabels:
    redis: external
  ingressNSPodMatchLabels:
    redis-client: true
```
But this is not AND this is OR as i describe the create network policy:
```
Spec:
  PodSelector: app.kubernetes.io/instance=mdata,app.kubernetes.io/name=redis-cluster
  Allowing ingress traffic:
    To Port: 6379/TCP
    To Port: 16379/TCP
    From:
      NamespaceSelector: redis=external
    From:
      PodSelector: redis-client=true
--
```
my problem is my redisinsight which is in another namespace with labeld redis=external can not connect to redis cluster.i also brought up a pod with redis-cli and tried to connect to redis cluster but not successfull. and when i delete the network policy everything goes well with out problem.

### What do you see instead?

Connection time out to redis
