### ISSUE TITLE
[bitnami/grafana] Cannot get HTTPS working on EKS cluster with grafana Helm chart

### ISSUE THREAD

**Issue by IBDO** [bitnami/charts#1871]
**Which chart**:
bitnami/grafana v 1.2.5

**Description**
So I have been trying to get Grafana Helm working on an EKS cluster. I can connect to the internal-reallylongloadbalancerurl.amazonaws.com load balancer on port 3000 with http, but trying to get TLS/HTTPS working has caused me to reach a dead end.

**Steps to reproduce the issue:**

1. Create TLS secret
```
kubectl create secret tls my-grafana-tls-secret --key my-tls.key --cert my-tls.crt -n grafana-namespace
```
2. Use following values.yaml with the following ingress/service code:
```
ingress:
  enabled: true
  certManager: true
  hosts:
    - tls: true
      name: mygrafana
      tlsHosts:
        - mygrafana.mydomain.com
      tlsSecret: my-grafana-tls-secret

service:
  annotations:
    "service.beta.kubernetes.io/aws-load-balancer-internal": myc.i.d.r/block
  type: LoadBalancer 
```
3. Install and wait for load balancer
```
helm install --name grafana-release bitnami/grafana --version 1.2.5 -f templates/values.yaml
```

**Describe the results you received:**
Connect to https://internal-reallylongloadbalancerurl.amazonaws.com:3000 and get an ERR_SSL_PROTOCOL_ERROR error

**Describe the results you expected:**
Connect to https://internal-reallylongloadbalancerurl.amazonaws.com:3000 and get a webpage with HTTPS

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
