### ISSUE TITLE
[bitnami/sonarqube] setup endpoint not available at version upgrades

### ISSUE THREAD

**Issue by chrira** [bitnami/charts#18789]
### Name and Version

bitnami/sonarqube 3.2.10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. deploy the sonarqube chart with the sonarqube image: 'docker.io/bitnami/sonarqube:9.9.0-debian-11-r23'
2. change the image to: 'docker.io/bitnami/sonarqube:9.9.1-debian-11-r96'
3. deploy it with the new version
4. the pod will never become ready and therefore no access to the UI is possible

### Are you using any custom parameters or values?

yes, the image and tag as described above

### What is the expected behavior?

There are two problems:
1. The relevant logs are not visible in std-out
2. The startup-, readiness and liveness probes do not respect the db upgrade state of SonarQube.

### Solution for problem 1
Write the content of this file to std-out: `/opt/bitnami/sonarqube/logs/sonar.log` 

Then you would see something like this:
```bash
2023.08.22 15:46:50 WARN  app[][startup] ################################################################################
2023.08.22 15:46:50 WARN  app[][startup] The database must be manually upgraded. Please backup the database and browse /setup. For more information: https://docs.sonarqube.org/latest/setup/upgrading
2023.08.22 15:46:50 WARN  app[][startup] ################################################################################
```

### Solution for problem 2

Adapt the solution of the official SonarQube Helm Chart of Sonarsource for the probes.

```yaml
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - |
                #!/bin/bash
                # A Sonarqube container is considered ready if the status is UP, DB_MIGRATION_NEEDED or DB_MIGRATION_RUNNING
                # status about migration are added to prevent the node to be kill while sonarqube is upgrading the database.
                host="$(hostname -i || echo '127.0.0.1')"
                if wget --no-proxy -qO- http://${host}:{{ .Values.service.internalPort }}{{ .Values.readinessProbe.sonarWebContext }}api/system/status | grep -q -e '"status":"UP"' -e '"status":"DB_MIGRATION_NEEDED"' -e '"status":"DB_MIGRATION_RUNNING"'; then
                	exit 0
                fi
                exit 1
```

Link to the chart: https://artifacthub.io/packages/helm/sonarqube/sonarqube

### What do you see instead?

SonarQube pod does not start and ends in a CrashLoopBackOff.
