### ISSUE TITLE
[bitnami/postgresql] username / password login failed

### ISSUE THREAD

**Issue by 51yu** [bitnami/charts#18787]
### Name and Version

bitnami/postgresql 12.8.3

### What architecture are you using?

None

### What steps will reproduce the bug?

install
```sh
helm install postgresql bitnami/postgresql --values helm/postgresql-values.yaml
```
values
```yaml
auth:
  postgresPassword: admin
  username: dev
  password: dev
  database: test
```
ssh in
```sh
 kubectl exec -it postgresql-0 -- /bin/sh
```
print env
```
I have no name!@postgresql-0:/$ echo $POSTGRES_USER
dev
I have no name!@postgresql-0:/$ echo $POSTGRES_PASSWORD
dev
I have no name!@postgresql-0:/$ echo $POSTGRES_POSTGRES_PASSWORD
admin
```
try login
```
I have no name!@postgresql-0:/$ psql -h postgresql -d test -U dev
Password for user dev:
psql: error: connection to server at "postgresql" (10.111.33.87), port 5432 failed: FATAL:  password authentication failed for user "dev"
```
^^ same for user `postgres` with password `admin`

### Are you using any custom parameters or values?

```yaml
auth:
  postgresPassword: admin
  username: dev
  password: dev
  database: test
```

### What is the expected behavior?

login succeed

### What do you see instead?

login fail
```
I have no name!@postgresql-0:/$ psql -h postgresql -U postgres -p 5432
Password for user postgres:
psql: error: connection to server at "postgresql" (10.111.33.87), port 5432 failed: FATAL:  password authentication failed for user "postgres"
```
and
```
I have no name!@postgresql-0:/$ psql -h postgresql -d test -U dev
Password for user dev:
psql: error: connection to server at "postgresql" (10.111.33.87), port 5432 failed: FATAL:  password authentication failed for user "dev"
```
