### ISSUE TITLE
[bitnami/kafka] PodAntiAffinity Not working for Kafka Cluster

### ISSUE THREAD

**Issue by sushil-clearsense** [bitnami/charts#18794]
### Name and Version

bitnami/kafka 24.0.10

### What architecture are you using?

None

### What steps will reproduce the bug?

1. I am running the Kafka chart to create a kafka cluster. I have set the broker.podAffinityPreset to hard. But, multiple kafka-broker pods are still scheduled on the same node

### Are you using any custom parameters or values?
```
image:
  tag: 3.5.1-debian-11-r16
  pullPolicy: Always

existingLog4jConfigMap: "kafka-log4j-config"

kraft:
  enabled: false

auth:
  interBrokerProtocol: tls

broker:
  replicaCount: 3
  podAntiAffinityPreset: hard

controller:
  replicaCount: 0

zookeeper:
  enabled: true
  replicaCount: 3

listeners:
  client:
    protocol: SSL

  interbroker:
    protocol: SSL

  external:
    protocol: SSL

tls:
  type: jks
  existingSecret: kafka-tls
  keystorePassword: ############
  truststorePassword: #############

externalAccess:
  enabled: true
  broker:
    service:
      type: NodePort
      nodePorts:
        - 31095
        - 31096
        - 31097
      externalIPs:
        - ###########
        - ############
        - ################

  controller:
    service:
      type: ClusterIP
      domain: ############ # not being used currently
```

### What is the expected behavior?

3 Kafka broker pods should be deployed and the all the pods should be on different worker nodes

### What do you see instead?

3 kafka broker pods are deployed, but two of them are on the same node

### Additional information

I checked the final YAML of the pods and i see that ant-affinity specs are applied properly. However, I see that the matchLabels section in the podAntiAffinity mentions a label - `app.kubernetes.io/component: kafka`. However, the pod does not have that lablel, as can be seen from the below YAML. The helm chart adds a different label to the pod - ` app.kubernetes.io/component: broker`

Could this be causing the issue?

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cattle.io/timestamp: "2023-08-22T19:40:54Z"
    checksum/configuration: c3defcc69b183f2633be4f668a9ee0fd9f676b41e4d7dbc236b069ff227e522d
    cni.projectcalico.org/containerID: f26f10de498622d46197e0ebe217a97c19651cf68563f9f57a8f2b92514b80fa
    cni.projectcalico.org/podIP: 10.42.2.126/32
    cni.projectcalico.org/podIPs: 10.42.2.126/32
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2023-08-22T19:50:36Z"
  generateName: kafka-broker-
  labels:
    app.kubernetes.io/component: broker
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: kafka
    controller-revision-hash: kafka-broker-858f89b75c
    helm.sh/chart: kafka-24.0.10
    statefulset.kubernetes.io/pod-name: kafka-broker-0
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/component: kafka
            app.kubernetes.io/instance: kafka
            app.kubernetes.io/name: kafka
        topologyKey: kubernetes.io/hostname
```
