### ISSUE TITLE
[bitnami/keycloak] failed to umount, device or resource busy

### ISSUE THREAD

**Issue by coffreo-lcabello** [bitnami/charts#18840]
### Name and Version

bitnami/keycloak 16.0.5

### What architecture are you using?

amd64

## Environment

OVH, on managed k8s, 1.25.9-0.
Works on 1.26.4-1.

### Are you using any custom parameters or values?

```
image:
  registry: registry.gitlab.com/coffreo
  repository: keycloak/keycloak-default
  tag: latest
  pullSecrets: [ gitlab-coffreo-registry ]

extraEnvVars:
  - name: KEYCLOAK_PRODUCTION
    value: "true"

replicaCount: 2

auth:
  createAdminUser: true
  adminUser: admin
  existingSecret: "keycloak-auth-secret"
  tls:
    enabled: true
    autoGenerated: true

containerPorts:
  http: 8080
  https: 8443
  management: 9990

service:
  type: ClusterIP
  ports:
    https: 443

tls:
  enabled: true
  autoGenerated: true

ingress:
  enabled: true
  certManager: false
  hostname: xxx
  path: /
  servicePort: https
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  tls: true
  selfSigned: true

proxy: passthrough

keycloakConfigCli:
  enabled: false

postgresql:
  enabled: false

externalDatabase:
  host: "xxx"
  port: xxx
  user: keycloak
  database: keycloak
  existingSecret: keycloak-db-secret
  existingSecretPasswordKey: "password"

cache:
  enabled: true
```

### What is the expected behavior?

```
Pulling image "registry.gitlab.com/coffreo/keycloak/keycloak-default:latest"
Successfully pulled image "registry.gitlab.com/coffreo/keycloak/keycloak-default:latest" in 10.673956972s (10.673963605s including waiting)
Created container keycloak
Started container keycloak
```

### What do you see instead?

```
Failed to pull image "registry.gitlab.com/coffreo/keycloak/keycloak-default:latest": rpc error: code = Unknown desc = failed to pull and unpack image "registry.gitlab.com/coffreo/keycloak/keycloak-default:latest": failed to extract layer sha256:dd5cf8dbecf9709a18ef987e391e28d71cf01b984ada703a30e0a54ace6e3548: failed to unmount /var/lib/containerd/tmpmounts/containerd-mount2801332412: failed to unmount target /var/lib/containerd/tmpmounts/containerd-mount2801332412: device or resource busy: unknown
Back-off pulling image "registry.gitlab.com/coffreo/keycloak/keycloak-default:latest"
Error: ImagePullBackOff
```

### Additional information

A similar problem was detected with McAfee, where a race condition in the application was found.
See https://github.com/ansible/awx-operator/issues/987

What makes us think of a race condition is that sometimes deployment is successful. The conditions are apparently random.

The problem also occurs when replicaCount is set to 1.
