### ISSUE TITLE
make topologySpreadConstraints smoother to use

### ISSUE THREAD

**Issue by davidkarlsen** [bitnami/charts#18882]
### Name and Version

commons chart

### What is the problem this feature will solve?

Having to define the full section like this:
```yaml
 topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: etcd
              app.kubernetes.io/instance: db2u-ftm-hadr-etcd
```

is cumbersome - especially the labels as they are tied to the given release.
I think commons should be extended with this out of the box - similar to how podAntiAffinity works.

### What is the feature you are proposing to solve the problem?

More easy use of topologySpreadConstraints across charts (for instance the etcd chart).

### What alternatives have you considered?

The alternative today is to spell it out yourself - due to missing templating support.

**Comment by jouve** [comment]
in the meantime, you can use templating in topologySpreadConstraints :

```yaml
topologySpreadConstraints: |
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
```
