### ISSUE TITLE
Using Mongo and RabbitMq as chart dependencies results in "error calling include" error

### ISSUE THREAD

**Issue by scott-david-walker** [bitnami/charts#18890]
### Name and Version

mongo:12.1.31 - rabbitmq:12.1.2

### What architecture are you using?

None

### What steps will reproduce the bug?

Create a Helm chart that has dependencies on both Mongo and RabbitMQ

```yaml
dependencies:
  - name: mongodb
    condition: mongodb.enabled
    version: 12.1.31
    repository: https://charts.bitnami.com/bitnami
  - name: rabbitmq
    condition: rabbitmq.enabled
    version: 12.1.2
    repository: https://charts.bitnami.com/bitnami

```

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Expect that no error is provided when running a helm template command

### What do you see instead?

Error: template: my-app/charts/rabbitmq/templates/svc.yaml:12:14: executing "swift-convert/charts/rabbitmq/templates/svc.yaml" at <include "common.labels.standard" (dict "customLabels" $labels "context" $)>: error calling include: template: my-app/charts/mongodb/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: my-app/charts/mongodb/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name

### Additional information

If I only use one of the dependencies then they both work without issue. It is possibly a similar issue to #18339
