### ISSUE TITLE
ApiREST login

### ISSUE THREAD

**Issue by Jose3212** [bitnami/charts#1889]
**Which chart**:
azure-marketplace/airflow 

**Description**

I change the values.yml to deploy the chart with an already created user and password, also added the extravar to add password auth to the apiREST. I can access the web interface but when I try to access the ApiREST with the already created user and password I receive forbidden

**Steps to reproduce the issue:**

1. I add the values to the yml:
```
auth:
    forcePassword: true
    username: user
    password: example
```
2. Add the extra_var to authenticate the API:
airflow:
```
  extraEnvVars:
    - name: AIRFLOW__API__AUTH_BACKEND
      value: "airflow.contrib.auth.backends.password_auth"
```
3. I wait until is deployed, and then via Web can access airflow.

4.Tryin this to launch my DAG

`curl -X POST -u user:example https://airflow.example.com/api/experimental/dags/test_send_recv/dag_runs -H 'Cache-Control: no-cache' -H 'Content-Type: application/json' -d '{}'`
or
`curl -X POST https://user:example@airflow.example.com/api/experimental/dags/test_send_recv/dag_runs -H 'Cache-Control: no-cache' -H 'Content-Type: application/json' -d '{}'`

**Describe the results you received:**

I received Forbidden

**Describe the results you expected:**

I expected a 200 and the dag to run

**Additional information you deem important (e.g. issue happens only occasionally):**

None

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by dani8art** [comment]
Hi @Jose3212 

Thank you for opening this issue, I will try to reproduce it.

- have you changed any other values in the values.yaml or `--set` option?

Regards.

**Comment by Jose3212** [comment]
Yes I added this in airflow also
```
airflow:
  cloneDagFilesFromGit:
    enabled: true
    repository: https://user:password@gitlab.example.com/project/airflow-dags
    branch: master
    interval: 60
    path: dags
  baseUrl: http://airflow.example.com
  worker:
    port: 8793
    replicas: 3
ingress:
  enabled: true

  certManager: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod

  hosts:
    - name: airflow.example.com
      path: /
      tls: true

      tlsSecret: airflow-tls-secret
```
But i do not know if it is relevant, the urls are different since we are in a production environment also the users and password

Thanks to you for your reply!

**Comment by dani8art** [comment]
Hi, I've reproduced the issue and I'm trying to identify the problem so that I can give you a solution. It looks like a misconfiguration issue. I'll come back to you soon. 

Thank you, for your patient.

**Comment by dani8art** [comment]
Hi @Jose3212 

After trying different approaches, we can not identify the issue in the configuration. As you can see in `opt/bitnami/airflow/airflow.cfg` we are adding all required parameters to enable auth in the API REST.  

As the doc says [here](https://airflow.apache.org/docs/stable/security.html#rbac-ui-security) we are adding RBAC feature.
```
[webserver]
rbac=True
```

Also, following [this](https://airflow.apache.org/docs/stable/api.html#authentication) we are adding API configuration using `extraEnvVars`

```
extraEnvVars:
  - name: AIRFLOW__API__AUTH_BACKEND
     value: airflow.contrib.auth.backends.password_auth
```

In addition, I've try to set [this](https://airflow.apache.org/docs/stable/security.html#web-authentication) too but it wouldn't be needed 
```
extraEnvVars:
  - name: AIRFLOW__WEBSERVER__AUTH_BACKEND
     value: airflow.contrib.auth.backends.password_auth
  - name: AIRFLOW__WEBSERVER__AUTHENTICATE
     value: True
```

Unfortunately, It always returns `403 Forbidden`. 

We are going to open an internal task in order to evaluate and decide what to do with this issue. As we cannot consider this issue as critical we cannot give you an ETA, as some as we have any new will be reported to this ticket. 

Thank you for your patience and sorry for the inconvenience.
Regards.
