### ISSUE TITLE
Keyclok behaviour when using ENV Vars as CM or as array inside the Helm chart.

### ISSUE THREAD

**Issue by busyboy77** [bitnami/charts#18935]
### Name and Version

bitnami/keycloak:16.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

when deployed using below given configuration, the keycloak doesn't respond of pick up the variables as they should be 

All ENV Vars embedded inside the HELM chart under `extraEnvVars` as array

```YAML
extraEnvVars: 
   - name: KC_LOG_LEVEL
     value: "DEBUG"
   - name: KEYCLOAK_LOGLEVEL
     value: "DEBUG"
   - name: ROOT_LOGLEVEL
     value: "DEBUG"
   - name:  KEYCLOAK_ADMIN_URL
     value: https://devops.ef.com/auth/
   - name:  KEYCLOAK_EXTRA_ARGS
     value: -Dkeycloak.frontendUrl=https://devops.ef.com/auth/  -Dkeycloak.profile.feature.upload_scripts=enabled
   - name:  KEYCLOAK_FRONTEND_URL
     value: https://devops.ef.com/auth/
   - name:  KEYCLOAK_LOGLEVEL
     value: DEBUG
   - name:  KEYCLOAK_PASSWORD
     value: admin
   - name:  KEYCLOAK_PROXY_ADDRESS_FORWARDING
     value: "true"
   - name:  KEYCLOAK_USER
     value: admin
   - name:  NODE_ENV
     value: development

## @param extraEnvVarsCM Name of existing ConfigMap containing extra env vars
##
extraEnvVarsCM: ""
## @param extraEnvVarsSecret Name of existing Secret containing extra env vars
##
```

The keycloak does not pick up all the said vairables.

Now, I left the above paragraph as it is and used a configmap like below:

```YAML
extraEnvVars: 
   - name: KC_LOG_LEVEL
     value: "DEBUG"
   - name: KEYCLOAK_LOGLEVEL
     value: "DEBUG"
   - name: ROOT_LOGLEVEL
     value: "DEBUG"
## @param extraEnvVarsCM Name of existing ConfigMap containing extra env vars
##
extraEnvVarsCM: "ef-keycloak-config"
## @param extraEnvVarsSecret Name of existing Secret containing extra env vars
##
```

ef-keycloak-config contents:

```yaml
apiVersion: v1
data:
  KEYCLOAK_ADMIN_URL: https://devops.ef.com/auth/
  KEYCLOAK_EXTRA_ARGS: -Dkeycloak.frontendUrl=https://devops.ef.com/auth/  -Dkeycloak.profile.feature.upload_scripts=enabled
  KEYCLOAK_FRONTEND_URL: https://devops.ef.com/auth/
  KEYCLOAK_LOGLEVEL: DEBUG
  KEYCLOAK_PASSWORD: admin
  KEYCLOAK_PROXY_ADDRESS_FORWARDING: "true"
  KEYCLOAK_USER: admin
  NODE_ENV: development
kind: ConfigMap
metadata:
  name: ef-keycloak-config
  namespace: some-ns
```

The keycloak works and picks up all the environment variables from the said configmap and displays the information correctly.

any idea, what is the different between importing ENV Vars using `extraEnvVars` or `extraEnvVarsCM`

### Are you using any custom parameters or values?

Yes Shared all the values above

### What is the expected behavior?

Same info

### What do you see instead?

problem described well above

**Comment by dgomezleon** [comment]
Hi @busyboy77 ,

Could you try with this?:

```
extraEnvVars: 
   - name: KC_LOG_LEVEL
     value: "DEBUG"
   - name: KEYCLOAK_LOGLEVEL
     value: "DEBUG"
   - name: ROOT_LOGLEVEL
     value: "DEBUG"
   - name:  KEYCLOAK_ADMIN_URL
     value: https://devops.ef.com/auth/
   - name:  KEYCLOAK_EXTRA_ARGS
     value: "-Dkeycloak.frontendUrl=https://devops.ef.com/auth/  -Dkeycloak.profile.feature.upload_scripts=enabled"
   - name:  KEYCLOAK_FRONTEND_URL
     value: https://devops.ef.com/auth/
   - name:  KEYCLOAK_PASSWORD
     value: admin
   - name:  KEYCLOAK_PROXY_ADDRESS_FORWARDING
     value: "true"
   - name:  KEYCLOAK_USER
     value: admin
   - name:  NODE_ENV
     value: development
```

The error is probably due to not putting KEYCLOAK_EXTRA_ARGS in quotes. Also, KEYCLOAK_LOGLEVEL was repeated.
