### ISSUE TITLE
[bitnami/elasticsearch] Issue related to health check scripts

### ISSUE THREAD

**Issue by vanpt1114** [bitnami/charts#18934]
### Name and Version

bitnami/elasticsearch 19.10.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Use bitnami/elasticsearch with version `19.10.4` and above
2. Set `security.tls.restEncryption.enabled = false`
3. Set `image.tag = 8.9.1-debian-11-r2`

### Are you using any custom parameters or values?

```yaml
master:
  masterOnly: false
  replicaCount: 3

data:
  replicaCount: 0

coordinating:
  replicaCount: 0

ingest:
  enabled: false

image:
  tag: 8.9.1-debian-11-r2

security:
  enabled: true
  elasticPassword: xxx
  tls:
    restEncryption: false          ## <= disable HTTPS
    autoGenerated: true
    usePemCerts: true
```

### What is the expected behavior?

Pods pass liveness/readiness check

### What do you see instead?

Pods did not pass liveness/readiness check, so it cannot rollout
<img width="1503" alt="image" src="https://github.com/bitnami/charts/assets/48898401/4ee67735-f1ae-4719-a964-8d6f5ff2a755">

### Additional information
- User image tag version `8.8.2-debian-11-r4` for Chart 19.10.5 and above is oke
- If I set `security.tls.restEncrytion = true` , liveness/readiness is ok

=> So I think there is some issue that is related to container image larger than `8.8.2-debian-11-r4`, especially in health check script.
_No response_

**Comment by fevisera** [comment]
Hi @vanpt1114,

Sorry for the delay, thank you very much for submitting the issue. It appears to https://github.com/bitnami/containers/pull/47319. So, let's wait for the release of a new chart version that incorporates that container change to ensure that it addresses your issue.

Thanks for your patience.

**Comment by overholts** [comment]
I'm not sure the above PR fixes the issue - it seems like `$DB_ENABLE_REST_TLS` in those container scripts still [defaults to true](https://github.com/bitnami/containers/blob/d78ea4fb43a663f10da00bfdfe6fb97bbf032b37/bitnami/elasticsearch/8/debian-11/rootfs/opt/bitnami/scripts/elasticsearch-env.sh#L229) if `ELASTICSEARCH_ENABLE_REST_TLS` is not set on the container environment, which is the behavior of this chart if `security.enabled = false` ([[1]](https://github.com/bitnami/charts/blob/7d4bfbd87bb6f6ed2210510c1bbc7ccde13abed4/bitnami/elasticsearch/templates/data/statefulset.yaml#L194-L195), [[2]](https://github.com/bitnami/charts/blob/7d4bfbd87bb6f6ed2210510c1bbc7ccde13abed4/bitnami/elasticsearch/templates/_helpers.tpl#L453-L454))

I had to work around this with:

```
  extraEnvVars:
    - name: ELASTICSEARCH_ENABLE_REST_TLS
      value: "false"
```

I haven't tried, but it looks like it would be reproducible with entirely default values.

**Comment by fevisera** [comment]
Hi @vanpt1114 and @overholts,

It still happens with the latest container version. I will create an internal task to review this use case. I cannot provide an ETA, but we will come back as soon as we have news.

Thanks!

**Comment by juan131** [comment]
Hi everyone!

I'm unable to reproduce the issue with the latest chart version (**19.13.14**) which ships the image version **8.11.3-debian-11-r0** using the values below:

```yaml
master:
  masterOnly: false
  replicaCount: 3
data:
  replicaCount: 0
coordinating:
  replicaCount: 0
ingest:
  enabled: false
security:
  enabled: true
  elasticPassword: some-password
  tls:
    restEncryption: false
    autoGenerated: true
    usePemCerts: true
```

This issue should be solved thanks to [this contribution](https://github.com/bitnami/containers/pull/47319) that was included in (version **8.10.2-debian-11-r6**), see commit below:

- https://github.com/bitnami/containers/commit/c78a11460f391c08fd365d93d6ba228f0ea4b036

Could you please confirm it?
