### ISSUE TITLE
[bitnami/memcached] Service annotations are not being applied

### ISSUE THREAD

**Issue by alexmg** [bitnami/charts#1894]
**Which chart**:

memcached

**Description**

Service annotations are not applied.

**Steps to reproduce the issue:**

Create a `values.yaml` file that includes service annotations.

```
service:
  annotations:
    something: "true"
```

Test the Helm chart with `--debug` and `--dry-run`.

**Describe the results you received:**

The annotations are not added to the service.

**Describe the results you expected:**

The annotations to be present on the service.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"c52f59bbba5fbf21fbb18e9a06f96e563fe4c20a", GitTreeState:"clean", BuildDate:"2020-01-31T20:00:26Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rafariossaa** [comment]
Hi @alexmg ,
  Could you confirm that the issue is fixed ?

**Comment by alexmg** [comment]
Yes it is working nicely with the values file. It was just a simple typo with the missing "s" character. What syntax (if actually possible) would be needed to have it work as a `--set` parameter?

**Comment by rafariossaa** [comment]
This in particular will be `--set service.annotations=value` .

**Comment by alexmg** [comment]
@rafariossaa What would the content of `value` look like in this case?

I have seen the format below in other charts but that does not work.

```
--set service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal=true"
```

**Comment by rafariossaa** [comment]
Hi @alexmg ,
  I have been testing this and the annotations are not working. I am opening an internal task to fix this.
  We will come back as soon as we have news.

**Comment by Mauraza** [comment]
Hi @alexmg 
Cloud you try this:

```
--set service.annotations="'service.beta.kubernetes.io/azure-load-balancer-internal': 'true'"
```
For more that one will be:

```
helm install my-release  bitnami/memcached --set service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal"="'true'" --set service.annotations."service\.beta\.kubernetes\.io/azure-load-2"="'true'"
```

Meaby it's easier to do with a file of values.

In the file (my-values.yaml)

```
service:
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
    service.beta.kubernetes.io/azure-load-2: 'true'
```

And then run 

```
helm install my-release -f my-values.yaml  bitnami/memcached
```

**Comment by alexmg** [comment]
When using the provided `--set` syntax the annotation key is quoted.

```
--set service.annotations="'service.beta.kubernetes.io/azure-load-balancer-internal': 'true'"
```
```
metadata:
  name: memcached
  labels:
    app.kubernetes.io/name: memcached
    helm.sh/chart: memcached-4.2.5
    app.kubernetes.io/instance: memcached
    app.kubernetes.io/managed-by: Helm
  annotations:
    'service.beta.kubernetes.io/azure-load-balancer-internal': 'true'
```
Removing the single quotes around the key also works.

```
--set service.annotations="service.beta.kubernetes.io/azure-load-balancer-internal: 'true'"
```
```
metadata:
  name: memcached
  labels:
    app.kubernetes.io/name: memcached
    helm.sh/chart: memcached-4.2.5
    app.kubernetes.io/instance: memcached
    app.kubernetes.io/managed-by: Helm
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
```

In both cases a warning is displayed but the annotations are stilled applied.

```
USER-SUPPLIED VALUES:
service:
  annotations: 'service.beta.kubernetes.io/azure-load-balancer-internal: ''true'''

coalesce.go:196: warning: cannot overwrite table with non table for annotations (map[])
```

When two values are provided using `--set` the warning is not shown but the single quotes do not appear correctly on the annotations.

```
metadata:
  name: memcached
  labels:
    app.kubernetes.io/name: memcached
    helm.sh/chart: memcached-4.2.5
    app.kubernetes.io/instance: memcached
    app.kubernetes.io/managed-by: Helm
  annotations:
    service.beta.kubernetes.io/azure-load-2: '''true'''
    service.beta.kubernetes.io/azure-load-balancer-internal: '''true'''
```
