### ISSUE TITLE
[bitnami/mariadb-galera] possible misprint in the helm chart template: .Values.metrics.prometheusRule

### ISSUE THREAD

**Issue by ErmakovDmitriy** [bitnami/charts#18945]
### Name and Version

mariadb-galera/9.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Get mariadb-galera 9.1.1 helm chart
2. Install with values:

```yaml
metrics:
  enabled: true
  prometheusRules:
    enabled: true
    additionalLabels:
      app: prometheus-operator
      release: prometheus
    # The rules below do not matter.
    rules:
      - alert: MariaDB-Down
        annotations:
          message: "MariaDB instance {{ $labels.instance }} is down"
          summary: MariaDB instance is down
        expr: absent(up{job="mariadb-galera"} == 1)
        labels:
          severity: warning
          service: mariadb-galera
        for: 5m

```

3. Get an error:

```
Error: template: mariadb-galera/templates/prometheusrules.yaml:13:18: executing "mariadb-galera/templates/prometheusrules.yaml" at <.Values.metrics.prometheusRule.additionalLabels>: nil pointer evaluating interface {}.additionalLabels
```

### What is the expected behavior?

Chart should be installed.

### What do you see instead?

```
Error: template: mariadb-galera/templates/prometheusrules.yaml:13:18: executing "mariadb-galera/templates/prometheusrules.yaml" at <.Values.metrics.prometheusRule.additionalLabels>: nil pointer evaluating interface {}.additionalLabels
```

### Additional information

I think that the issue is within line https://github.com/bitnami/charts/blob/c78083c946876f94b4ff66000ac9b503bb20f70a/bitnami/mariadb-galera/templates/prometheusrules.yaml#L13 in the template.

If I change the line to:

```patch
13c13
<     {{- if .Values.metrics.prometheusRule.additionalLabels }}
---
>     {{- if .Values.metrics.prometheusRules.additionalLabels }}
```

the issue is fixed.
