### ISSUE TITLE
thanos chart's PrometheusRules reference incorrect job names (with quick & dirty fix)

### ISSUE THREAD

**Issue by cschockaert** [bitnami/charts#18943]
### Name and Version

bitnami/thanos:12.12.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install thanos chart with a different release name than thanos: ex thanos-stack

ServiceMonitor job will get name like :

- thanos-stack-compactor
- thanos-stack-...

Prometheus rules will not work as they relies on job name "thanos-compactor" ; "thanos-xxx"

### What is the expected behavior?

Prometheus rule must be working as expected

### What do you see instead?

Prometheus rules wont work reporting false positives errors. 

### Additional information

I found a way to fix it but it's a quick & dirty fix:

in values.yaml added theses line to relabel the job name:

```yaml
thanos:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      # quick fix to replace from (for example) job=thanos-stack-compactor to job=thanos-compactor and get rules working
      relabelings:
        - action: replace
          sourceLabels: [__meta_kubernetes_service_name]
          regex: thanos-stack-(.*)
          targetLabel: job
          replacement: thanos-$1
```
