### ISSUE TITLE
HTTP2 in kong

### ISSUE THREAD

**Issue by thanhtai9606** [bitnami/charts#18956]
### Name and Version

bitnami/kong 3.4.0

### What architecture are you using?

None

### What steps will reproduce the bug?

 I cannot enable http2 in bitnami kong??
I have options in kong/kong with parameters 
```yaml

 http:
     # Enable plaintext HTTP listen for the proxy
     enabled: true
     servicePort: 80
     containerPort: 8000
     # Set a nodePort which is available if service type is NodePort
     # nodePort: 32080
     # Additional listen parameters, e.g. "reuseport", "backlog=16384"
     parameters: 
     **- http2**
 
   tls:
     # Enable HTTPS listen for the proxy
     enabled: true
     servicePort: 443
     containerPort: 8443
     # Set a target port for the TLS port in proxy service
     # overrideServiceTargetPort: 8000
     # Set a nodePort which is available if service type is NodePort
     # nodePort: 32443
     # Additional listen parameters, e.g. "reuseport", "backlog=16384"
     parameters:
     **- http2**
```

### What do you see instead?

I need a configuration option to enable http2

**Comment by aoterolorenzo** [comment]
Could you try...?:

```
http:
  enabled: true
  servicePort: 80
  containerPort: 8000
  parameters:
    - http2

tls:
  enabled: true
  servicePort: 443
  containerPort: 8443
  parameters:
    - http2

```
