### ISSUE TITLE
[bitnami/redis-cluster] Cannot resize cluster in multimaster mode (no replicas)

### ISSUE THREAD

**Issue by ritmas** [bitnami/charts#18960]
### Name and Version

bitnami/redis-cluster 9.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Setup cluster with 3 master nodes, no replicas:
```yaml
# helm upgrade --install redis-cluster bitnami/redis-cluster --version=9.0.0 -f values.yml
usePassword: false
persistence:
  size: 1Gi
redis:
  configmap: |
    maxmemory 128mb
    maxmemory-policy allkeys-lfu
    appendonly no
    save ""
  resources:
    requests:
      cpu: 500m
      memory: 150Mi
    limits:
      memory: 150Mi
  useAOFPersistence: "no"
metrics:
  enabled: true
cluster:
  replicas: 0
  nodes: 3
```
2. Try resize it by adding new node
```bash
helm upgrade --install redis-cluster bitnami/redis-cluster \
  --set "cluster.nodes=4,cluster.update.addNodes=true,cluster.update.currentNumberOfNodes=3,cluster.update.currentNumberOfReplicas=0"
```

### What is the expected behavior?

Cluster is successfully resized

### What do you see instead?

Due to [inaccurate chart template check](https://github.com/bitnami/charts/blob/main/bitnami/redis-cluster/templates/_helpers.tpl#L221-L224), it's impossible to set 0 replicas upon cluster resize:
```bash
Error: UPGRADE FAILED: execution error at (redis-cluster/templates/NOTES.txt:105:4): 
VALUES VALIDATION:
redis-cluster: currentNumberOfReplicas
    You must provide the currentNumberOfReplicas to perform an upgrade when not using external access.
```

It should look something similar to:
```diff
--    {{- if not .Values.cluster.update.currentNumberOfReplicas -}}
++    {{- if kindIs "invalid" .Values.cluster.update.currentNumberOfReplicas -}}
redis-cluster: currentNumberOfReplicas
    You must provide the currentNumberOfReplicas to perform an upgrade when not using external access.
    {{- end -}}
```
