### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference on helm template

### ISSUE THREAD

**Issue by Maannniii** [bitnami/charts#18994]
### Name and Version

bitnami/nginx 1.25.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm trying to package the helm chart to create the YAML files which can be applied via `kubectl apply`.
1. cloned bitnami repo
2. cd bitnami
3. ran `helm template bitnami-nginx ./nginx --dependency-update --namespace default -f nginx/values.yaml` with default values.yaml

### Are you using any custom parameters or values?

No. Using default values.yaml provided with the chart.

### What is the expected behavior?

This is supposed to output the following Yaml

```yaml
---
# Source: nginx/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: bitnami-nginx
  namespace: "default"
  labels:
    app.kubernetes.io/name: nginx
    helm.sh/chart: nginx-15.1.0
    app.kubernetes.io/instance: bitnami-nginx
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: "Cluster"
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: bitnami-nginx
---
# Source: nginx/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitnami-nginx
  namespace: "default"
  labels:
    app.kubernetes.io/name: nginx
    helm.sh/chart: nginx-15.1.0
    app.kubernetes.io/instance: bitnami-nginx
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate: {}
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/instance: bitnami-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        helm.sh/chart: nginx-15.1.0
        app.kubernetes.io/instance: bitnami-nginx
        app.kubernetes.io/managed-by: Helm
      annotations:
    spec:

      automountServiceAccountToken: false
      shareProcessNamespace: false
      serviceAccountName: default
      affinity:
        podAffinity:

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: nginx
                    app.kubernetes.io/instance: bitnami-nginx
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:

      hostNetwork: false
      hostIPC: false
      initContainers:
      containers:
        - name: nginx
          image: docker.io/bitnami/nginx:<+artifacts.primary.tag>
          imagePullPolicy: "IfNotPresent"
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: NGINX_HTTP_PORT_NUMBER
              value: "8080"
          envFrom:
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            tcpSocket:
              port: http
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
            tcpSocket:
              port: http
          resources:
            limits: {}
            requests: {}
          volumeMounts:
      volumes:
```

### What do you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x38 pc=0x101ffed70]

goroutine 1 [running]:
helm.sh/helm/v3/pkg/registry.(*Client).Tags(0x0, {0x14000594930?, 0x14000c0f598?})
	helm.sh/helm/v3/pkg/registry/client.go:628 +0xb0
helm.sh/helm/v3/internal/resolver.(*Resolver).Resolve(0x14000c0f7e0, {0x140007174c0, 0x1, 0x4}, 0x1?)
	helm.sh/helm/v3/internal/resolver/resolver.go:153 +0x4dc
helm.sh/helm/v3/pkg/downloader.(*Manager).resolve(0x14000140a20?, {0x140007174c0?, 0x140007174c0?, 0x1?}, 0x14000140a20?)
	helm.sh/helm/v3/pkg/downloader/manager.go:235 +0x58
helm.sh/helm/v3/pkg/downloader.(*Manager).Update(0x14000140a20)
	helm.sh/helm/v3/pkg/downloader/manager.go:194 +0xac
main.runInstall({0x1400060ee00?, 0x2, 0x7}, 0x1400059e6e0, 0x0?, {0x102ad4b20?, 0x1400000e018})
	helm.sh/helm/v3/cmd/helm/install.go:256 +0x5f4
main.newTemplateCmd.func2(0x14000c20f00?, {0x1400060ee00, 0x2, 0x7})
	helm.sh/helm/v3/cmd/helm/template.go:88 +0x1d0
github.com/spf13/cobra.(*Command).execute(0x14000c20f00, {0x1400060ed90, 0x7, 0x7})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x14000b7e000)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	helm.sh/helm/v3/cmd/helm/helm.go:83 +0x248
```

### Additional information

However, I copied `bitnami/common` into the `bitnami/nginx/charts/common` post which upon `helm template bitnami-nginx ./nginx --dependency-update --namespace default -f nginx/values.yaml` the yaml gets generated.

helm version used to test: v3.12.0 and v3.12.1
kubectl version installed: v1.27.4
