### ISSUE TITLE
Multi-chart dependencies

### ISSUE THREAD

**Issue by r65535** [bitnami/charts#19003]
### Name and Version

redis/18.0.1

### What architecture are you using?

None

### What steps will reproduce the bug?

I'm adding 2 bitnami charts (postgresql and redis) as dependencies in my helm chart:
```yaml
  - name: postgresql
    version: "12.8.0"
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: "18.0.1"
    repository: https://charts.bitnami.com/bitnami
```

When I do this, I'm getting an error with the templating:
```
Error: template: myapp/charts/redis/templates/replicas/statefulset.yaml:12:14: executing "myapp/charts/redis/templates/replicas/statefulset.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: myapp/charts/postgresql/charts/common/templates/_labels.tpl:11:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: myapp/charts/postgresql/charts/common/templates/_names.tpl:11:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```

Is this caused because I'm importing two bitnami charts, or have I broken something on my side? 😢 

### What do you see instead?

Logs above
