### ISSUE TITLE
[bitnami/keycloak] X-Frame-Option denied

### ISSUE THREAD

**Issue by CaptainKrby** [bitnami/charts#19001]
### Name and Version

bitnami/keycloak 16.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

This is a fresh install.
In my installation, I have a Haproxy that does SSL offload.

### Are you using any custom parameters or values?
```yaml
    tls:
      enabled: false

    replicaCount: 2
    production: true
    proxy: edge
    httpRelativePath: "/auth/"

    extraEnvVars:
    - name: KC_HOSTNAME_URL
      value: https://my_keycloak_instance/auth
    - name: KC_HOSTNAME_ADMIN_URL
      value: https://my_keycloak_instance/auth

    ingress:
      ingressClassName: "nginx"
      hostname: my_keycloak_instance
      tls: true
      selfSigned: false
      extraTls:
        - hosts:
            - my_keycloak_instance

    postgresql:
      enabled: true
      auth:
        postgresPassword: ""
        username: keycloak
        password: ""
        database: keycloakdb
        existingSecret: "keycloak-postgresql"
      architecture: replication
      podAntiAffinityPreset: hard

    cache:
      enabled: true
      stackName: kubernetes
      stackFile: ""
```
### What is the expected behavior?

I'm supposed to access the administration interface.

### What do you see instead?

After clicking on Administration Console, I get a page called "Loading the Admin UI" which remains blocked.

On inspecting the page I see a blocked resource:
```
    Refused to display : https://my_keycloak_instance/auth/realms/master/protocol/openid-connect/3p-cookies/step1.html' in a frame because it set 'X-Frame-Options' to 'DENY’.
```
![image](https://github.com/bitnami/charts/assets/22073496/0e67628e-b62c-4df8-9f55-c0309b5b2424)

### Additional information

I'm quite annoyed because I'm not able to allow the X-Frame-Options :

- By my ingress allowing the nginx.ingress.kubernetes.io/configuration-snippet annotation is a security risk.
- By haproxy it's overkill to have to create a vip in passthrough just to overload a header.
