### ISSUE TITLE
[bitnami/fluentd] Unreadable log mounts

### ISSUE THREAD

**Issue by austince** [bitnami/charts#1905]
**Which chart**:

Fluentd 0.4.10

**Description**

Mounted logs are unreadable. It seems similar to this issue: https://stackoverflow.com/questions/51671212/fluentd-log-unreadable-it-is-excluded-and-would-be-examined-next-time

I have already set the FLUENT_UID to '0'. What other information do you need to find out what else I could be doing wrong?

**Steps to reproduce the issue:**

1. Deploy the chart on EKS
2. Tail the logs of the daemonset
3. See error

**Describe the results you received:**

```
2020-02-11 00:28:26 +0000 [warn]: #0 /var/log/containers/prometheus-prometheus-operator-prometheus-1_monitoring_prometheus-config-reloader-5de238447ab71c5f5e77c3890822c9fe5e0caefb212003488747ba73d4a0e603.log unreadable. It is excluded and would be examined next time.
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-21T22:17:28Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by austince** [comment]
I have another Fluentd daemonset running as well - could they be interfering with one another?

**Comment by javsalgar** [comment]
Hi,

Did you deploy it with the security group as root? 

```
      {{- if .Values.forwarder.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.forwarder.securityContext.runAsUser }}
        fsGroup: {{ .Values.forwarder.securityContext.fsGroup }}
```

**Comment by austince** [comment]
Hey @javsalgar, yeah here's my current config:

```yaml
forwarder:
    ## Enable forwarder daemonset
    ##
    enabled: true

    ## K8s Security Context for forwarder pods
    ## https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
    ##
    securityContext:
      enabled: true
      runAsUser: 0
      fsGroup: 0
```

**Comment by austince** [comment]
Looks like it's being mounted as `rw`, if I'm reading this describe output correctly: 

```
    Mounts:
      /opt/bitnami/fluentd/conf from fluentd-config (rw)
      /opt/bitnami/fluentd/logs/buffers from buffer (rw)
      /var/lib/docker/containers from varlibdockercontainers (rw)
      /var/log from varlog (rw)
```

**Comment by austince** [comment]
I've also verified that `whoami` prints `root`

**Comment by jixuju** [comment]
I have the same problem.

## Error log in forwarder
```
# kubectl logs -f fluentd-t7vpt -n logging
2020-02-15 07:46:26 +0000 [warn]: #0 /var/log/containers/es-elasticsearch-data-0_logging_elasticsearch-b788c87b88ca72f6e6b4a9853d3d7236bed636d07c939011e21ddcc63118b84e.log unreadable. It is excluded and would be examined next time.
2020-02-15 07:46:26 +0000 [warn]: #0 /var/log/containers/es-elasticsearch-metrics-6845b86646-kbs57_logging_metrics-d5aa13ceadda11388cbc7b6e4a1995bb127cafa8a829386214f91d7bc3de01c1.log unreadable. It is excluded and would be examined next time.
```

## Forwarder container current user
```
root@fluentd-t7vpt:/var/lib/docker/containers# whoami
root
```

## Part configuration of daemonset fluent
```
spec:
    volumes:
    - name: fluentd-config
        configMap:
        name: fluentd-forwarder-cm
        defaultMode: 420
    - name: buffer
        emptyDir: {}
    - name: varlog
        hostPath:
        path: /var/log
        type: ''
    - name: varlibdockercontainers
        hostPath:
        path: /var/lib/docker/containers
        type: ''
    containers:
    - name: fluentd
        image: 'docker.io/bitnami/fluentd:1.9.2-debian-10-r1'
        ports:
        - name: http
            containerPort: 9880
            protocol: TCP
        env:
        - name: FLUENTD_CONF
            value: fluentd.conf
        - name: FLUENTD_OPT
        resources: {}
        volumeMounts:
        - name: fluentd-config
            mountPath: /opt/bitnami/fluentd/conf
        - name: buffer
            mountPath: /opt/bitnami/fluentd/logs/buffers
        - name: varlog
            mountPath: /var/log
        - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
```

## Part of the configuration of forwarder in values.yaml
```
forwarder:
  ## Enable forwarder daemonset
  ##
  enabled: true

  ## K8s Security Context for forwarder pods
  ## https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  ##
  securityContext:
    enabled: true
    runAsUser: 0
    fsGroup: 0

  ## Name of the config file that will be used by Fluentd at launch
  ## Fluentd will look for it under the /opt/bitnami/fluentd/conf directory
  ##
  configFile: fluentd.conf
```

## Log path relationship
```
lrwxrwxrwx 1 root root 102 Feb 15 10:57 es-elasticsearch-data-0_logging_elasticsearch-b788c87b88ca72f6e6b4a9853d3d7236bed636d07c939011e21ddcc63118b84e.log -> /var/log/pods/logging_es-elasticsearch-data-0_1d1096fe-c372-4ce6-8232-fbae77d0d9e1/elasticsearch/0.log

# cd /var/log/pods/logging_es-elasticsearch-data-0_1d1096fe-c372-4ce6-8232-fbae77d0d9e1/elasticsearch
# ls -lrt
total 0
lrwxrwxrwx 1 root root 165 Feb 15 10:57 0.log -> /var/lib/docker/containers/b788c87b88ca72f6e6b4a9853d3d7236bed636d07c939011e21ddcc63118b84e/b788c87b88ca72f6e6b4a9853d3d7236bed636d07c939011e21ddcc63118b84e-json.log
```
