### ISSUE TITLE
[bitnami/nginx-ingress-controller] ServiceMonitor broken in 9.8.0

### ISSUE THREAD

**Issue by wvengen** [bitnami/charts#19129]
### Name and Version

bitnami/ingress-nginx 9.8.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Version 9.8.0 had a refactor of how labels and annotations are included in the templates. Somehow this broke our setup. Looking at the helm output of just the metrics and serviceMonitor enabled, confirms this issue (as to my understanding).

#### version 9.7.9

```
helm template nginx-ingress-controller-9.7.9.tgz --set metrics.enabled=true --set metrics.serviceMonitor.enabled=true
```

includes resources

```yaml
# Source: nginx-ingress-controller/templates/controller-metrics-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-nginx-ingress-controller-metrics
  namespace: "default"
  labels:
    app.kubernetes.io/name: nginx-ingress-controller
    helm.sh/chart: nginx-ingress-controller-9.7.9
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
  annotations:
    prometheus.io/port: '9913'
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9913
      targetPort: metrics
  selector:
    app.kubernetes.io/name: nginx-ingress-controller
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: controller
---
# Source: nginx-ingress-controller/templates/controller-servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: release-name-nginx-ingress-controller
  namespace: "default"
  labels:
    app.kubernetes.io/name: nginx-ingress-controller
    helm.sh/chart: nginx-ingress-controller-9.7.9
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
  annotations:
spec:
  jobLabel: ""
  endpoints:
    - port: metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-ingress-controller
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: metrics
```

#### version 9.8.0

```
helm template nginx-ingress-controller-9.8.0.tgz --set metrics.enabled=true --set metrics.serviceMonitor.enabled=true
```

includes resources

```yaml
# Source: nginx-ingress-controller/templates/controller-metrics-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-nginx-ingress-controller-metrics
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx-ingress-controller
    helm.sh/chart: nginx-ingress-controller-9.8.0
    app.kubernetes.io/component: controller
  annotations:
    prometheus.io/port: '9913'
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9913
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/name: nginx-ingress-controller
    app.kubernetes.io/component: controller
---
# Source: nginx-ingress-controller/templates/controller-servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: release-name-nginx-ingress-controller
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx-ingress-controller
    helm.sh/chart: nginx-ingress-controller-9.8.0
    app.kubernetes.io/component: metrics
spec:
  jobLabel: ""
  endpoints:
    - port: metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: nginx-ingress-controller
      app.kubernetes.io/component: metrics
```

As you can see, the label `app.kubernetes.io/component` of the metrics service has changed from `metrics` to `controller`, making the `ServiceMonitor` not match a service anymore.
