### ISSUE TITLE
[bitnami/postgresql] Cannot set `tcp_keepalives_idle ` via. `extraEnvVars`

### ISSUE THREAD

**Issue by mreiche** [bitnami/charts#19132]
### Name and Version

bitnami/postgresql:12.5.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Setting
```yaml
primary:
  extraEnvVars:
  - name: POSTGRESQL_TCP_KEEPALIVES_IDLE
    value: "7222"
```
Will add `POSTGRESQL_TCP_KEEPALIVES_IDLE` to the env of the PostgreSQL primary pod.

```shell
export | grep KEEPALIVE
export POSTGRESQL_TCP_KEEPALIVES_IDLE='7222'
```
But PostgreSQL doesn't accept it.

```sql
select * from pg_settings where name like '%keepalive%';
```
```
tcp_keepalives_idle     | 0       | s    |
```

It's supposed to work like the `bitnami/postgresql` docker image environment variables described here: https://github.com/bitnami/containers/tree/main/bitnami/postgresql#configuration

I already tried:

```yaml
primary:
  extraEnvVars:
  - name: PGOPTIONS
    value: "-c tcp_keepalives_idle=7200"
```
which only changes the `reset_value`of `tcp_keepalives_idle` and not its actual value, which remains zero (`0`).

### What do you see instead?

value of `POSTGRESQL_TCP_KEEPALIVES_IDLE` gets ignored in the primary.
