### ISSUE TITLE
[bitnami/elasticsearch 17.9.7] CertPathValidatorException: validity check failed

### ISSUE THREAD

**Issue by rysinal** [bitnami/charts#19154]
### Name and Version

bitnami/elasticsearch  17.9.7

### What architecture are you using?

None

### What steps will reproduce the bug?

My values is as follows:

```yaml
security:
  ## @param security.enabled Enable X-Pack Security settings
  ##
  enabled: true
  ## @param security.elasticPassword Password for 'elastic' user
  ## Ref: https://github.com/bitnami/bitnami-docker-elasticsearch#security
  ##
  elasticPassword: "fooxxxx"
  ## @param security.existingSecret Name of the existing secret containing the Elasticsearch password
  ##
  existingSecret: ""
  ## FIPS mode
  ## @param security.fipsMode Configure elasticsearch with FIPS 140 compliant mode
  ## Ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/fips-140-compliance.html
  ##
  fipsMode: false
  ## TLS configuration
  ##
  tls:
    ## @param security.tls.restEncryption Enable SSL/TLS encryption for Elasticsearch REST API.
    ##
    restEncryption: false
    ## @param security.tls.autoGenerated Create self-signed TLS certificates.
    ## Note: Currently only supports PEM certificates.
    ##
    autoGenerated: true
    ## @param security.tls.verificationMode Verification mode for SSL communications.
    ## Supported values: full, certificate, none.
    ## Ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
    ##
    verificationMode: "full"
    ## @param security.tls.master.existingSecret Existing secret containing the certificates for the master nodes
    ## @param security.tls.data.existingSecret Existing secret containing the certificates for the data nodes
    ## @param security.tls.ingest.existingSecret Existing secret containing the certificates for the ingest nodes
    ## @param security.tls.coordinating.existingSecret Existing secret containing the certificates for the coordinating nodes
    ##
    master:
      existingSecret: ""
    data:
      existingSecret: ""
    ingest:
      existingSecret: ""
    coordinating:
      existingSecret: ""
```

The certificate was generated automatically, but now it has expired. How can I automatically refresh the new certificate?
