### ISSUE TITLE
[bitnami/kube-prometheus] invalid yaml when activating thanos

### ISSUE THREAD

**Issue by Flou21** [bitnami/charts#19159]
### Name and Version

bitnami/kube-prometheus 8.18.0, 8.18.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

just templating shows the invalid yaml

`helm template bitnami/kube-prometheus --version 8.18.1 --set prometheus.thanos.create=true`

output of the `thanos-service.yaml` is:

```yaml
# Source: kube-prometheus/templates/prometheus/thanos-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-kube-promethe-prometheus-thanos
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus
    helm.sh/chart: kube-prometheus-8.18.1
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/subcomponent: thanos
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None
  ports:
    - name: grpc
      port: 10901
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: prometheus
    prometheus: release-name-kube-promethe-prometheus
    prometheus: release-name-kube-promethe-prometheus

```

### Are you using any custom parameters or values?

--set prometheus.thanos.create=true

### What is the expected behavior?

no duplicate keys

### What do you see instead?

duplicate key in `spec.selector`:

```yaml
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: prometheus
    prometheus: release-name-kube-promethe-prometheus
    prometheus: release-name-kube-promethe-prometheus
```

### Additional information

bug was introduced in this commit: https://github.com/bitnami/charts/commit/2f7fbef0d681c26a3be4a94c857c23c114b0108a

here is the first (old) occurrence of the `prometheus` key: https://github.com/bitnami/charts/blob/main/bitnami/kube-prometheus/templates/prometheus/thanos-service.yaml#L53C10-L53C10

and here is the second (new) one: https://github.com/bitnami/charts/blob/main/bitnami/kube-prometheus/templates/_helpers.tpl#L147
