### ISSUE TITLE
[bitnami/mastodon] Use of go templating inside of values.yaml for mastodon chart breaks Argo CD ApplicationSets

### ISSUE THREAD

**Issue by jessebot** [bitnami/charts#19173]
### Name and Version

bitnami/mastodon 2.1.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

On k3s using Argo CD 2.8.3, if you try to deploy an ApplicationSet for mastodon which uses a generator (which also using [go templates](https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/GoTemplate/)), using a values.yaml like the one listed below for instance, it will try to pull that from the external [generator](https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Generators/).

Example ApplicationSet that uses a custom defaultConfig via values.yaml:
https://github.com/small-hack/argocd-apps/blob/main/mastodon/mastodon_argocd_appset.yaml

### Are you using any custom parameters or values?

```yaml
            ## [string] Default config for Mastodon in the form of environment variables
            defaultConfig: |
              DB_HOST: {{ include "mastodon.database.host" . | quote }}
              DB_PORT: {{ include "mastodon.database.port" . | quote }}
              DB_NAME: {{ include "mastodon.database.name" . | quote }}
              DB_USER: {{ include "mastodon.database.user" . | quote }}
              ES_ENABLED: {{ .Values.enableSearches | quote }}
              ES_HOST: {{ include "mastodon.elasticsearch.host" . | quote }}
              ES_PORT: {{ include "mastodon.elasticsearch.port" . | quote }}
              WEB_DOMAIN: {{ include "mastodon.web.domain" . | quote }}
              LOCAL_DOMAIN: {{ .Values.localDomain | quote }}
              LOCAL_HTTPS: {{ .Values.local_https | quote }}
              DEFAULT_LOCALE: {{ .Values.defaultLocale | quote }}
              STREAMING_API_BASE_URL: {{ include "mastodon.streaming.url" . | quote }}
              REDIS_HOST: {{ include "mastodon.redis.host" . | quote }}
              REDIS_PORT: {{ include "mastodon.redis.port" . | quote }}
              SMTP_PORT: {{ .Values.smtp.port | quote }}
              SMTP_FROM_ADDRESS: {{ .Values.smtp.from_address | quote }}
              SMTP_DOMAIN: {{ .Values.smtp.domain | quote }}
              SMTP_REPLY_TO: {{ .Values.smtp.reply_to | quote }}
              SMTP_DELIVERY_METHOD: {{ .Values.smtp.delivery_method | quote }}
              SMTP_CA_FILE: {{ .Values.smtp.ca_file | quote }}
              SMTP_OPENSSL_VERIFY_MODE: {{ .Values.smtp.openssl_verify_mode | quote }}
              SMTP_ENABLE_STARTTLS_AUTO: {{ .Values.smtp.enable_starttls_auto | quote }}
              SMTP_TLS: {{ .Values.smtp.tls | quote }}
              SMTP_AUTH_METHOD: {{ .Values.smtp.auth_method | quote }}
              RAILS_ENV: {{ .Values.environment | quote }}
              NODE_ENV: {{ .Values.environment | quote }}
              {{- if .Values.enableS3 }}
              S3_ENABLED: "true"
              S3_BUCKET: {{ include "mastodon.s3.bucket" . | quote }}
              S3_ENDPOINT: {{ include "mastodon.s3.endpoint" . | quote }}
              S3_HOSTNAME: {{ include "mastodon.s3.host" . | quote }}
              S3_REGION: {{ include "mastodon.s3.region" . | quote }}
              S3_ALIAS_HOST: {{ include "mastodon.s3.aliasHost" . | quote }}
              S3_PROTOCOL: {{ include "mastodon.s3.protocol.setting" . | quote }}
              {{- end }}
```

### What is the expected behavior?

Typically you try to keep all go templating directly in files under the `templates/` dir for that helm chart. I'd like to see the `defaultConfig` here:
https://github.com/bitnami/charts/blob/c9716b7089e6213692e6c319c3b7c7bb39d00620/bitnami/mastodon/values.yaml#L117-L155

 moved to [`templates/default-configmap.yaml`](https://github.com/bitnami/charts/blob/main/bitnami/mastodon/templates/default-configmap.yaml) for instance.
 
 And the same goes for `defaultSecretConfig`:
 
 https://github.com/bitnami/charts/blob/c9716b7089e6213692e6c319c3b7c7bb39d00620/bitnami/mastodon/values.yaml#L159-L162
 
 which should go to [`templates/default-secret.yaml`](https://github.com/bitnami/charts/blob/main/bitnami/mastodon/templates/default-secret.yaml)
 
 I'm not sure what can be done about `apache.vhostsConfigMap` though:
 
 https://github.com/bitnami/charts/blob/c9716b7089e6213692e6c319c3b7c7bb39d00620/bitnami/mastodon/values.yaml#L1548

### What do you see instead?

My applicationSet that uses a [generator](https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Generators-Plugin/) shows:

```yaml
  conditions:
    - lastTransitionTime: '2023-09-07T12:12:22Z'
      message: >-
        error listing params: error get api 'mastodon-app-set': Post
        "http://argocd-appset-secret-plugin.argocd.svc.cluster.local/api/v1/getparams.execute":
        EOF
      reason: ApplicationGenerationFromParamsError
      status: 'True'
      type: ErrorOccurred
    - lastTransitionTime: '2023-09-07T12:12:22Z'
      message: >-
        error listing params: error get api 'mastodon-app-set': Post
        "http://argocd-appset-secret-plugin.argocd.svc.cluster.local/api/v1/getparams.execute":
        EOF
      reason: ErrorOccurred
      status: 'False'
      type: ParametersGenerated
    - lastTransitionTime: '2023-09-07T12:12:22Z'
      message: >-
        error listing params: error get api 'mastodon-app-set': Post
        "http://argocd-appset-secret-plugin.argocd.svc.cluster.local/api/v1/getparams.execute":
        EOF
      reason: ApplicationGenerationFromParamsError
      status: 'False'
      type: ResourcesUpToDate
```

### Additional information

I tried getting rid of most of the `defaultConfig` and `defaultSecretConfig` [here](https://github.com/small-hack/argocd-apps/blob/38b3397ce662e8aa47a62129e42ab0c89e42f2e1/mastodon/mastodon_argocd_appset.yaml#L48-L52) and also `apache.vhostsConfigMap` [here](https://github.com/small-hack/argocd-apps/blob/38b3397ce662e8aa47a62129e42ab0c89e42f2e1/mastodon/mastodon_argocd_appset.yaml#L404), but it still fails. The other issue here is that if I create env vars for all of these values manually, I can't use any of the existing parameters in the values.yaml such as the smtp section.
