### ISSUE TITLE
[bitnami/kafka] Can not set custom parameters(numPartitions,defaultReplicationFactor) for bitnami/kafka

### ISSUE THREAD

**Issue by liyuuKitchen** [bitnami/charts#19185]
### Name and Version

bitnami/kafka 3.5.1

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Deploy Azure K8s cluster
2. Install bitnami kafka: ` helm install kafka bitnami/kafka --set replicaCount=3,provisioning.enabled=true,provisioning.replicationFactor=3,provisioning.numPartitions=3,extraConfig="logRetentionHours=-1,logRetentionBytes=2199023985135,offsetsTopicReplicationFactor=3"`

### Are you using any custom parameters or values?

Yes.`--set replicaCount=3,provisioning.enabled=true,provisioning.replicationFactor=3,provisioning.numPartitions=3,extraConfig="logRetentionHours=-1,logRetentionBytes=2199023985135,offsetsTopicReplicationFactor=3"`

### What is the expected behavior?

If I deploy the Kafdrop UI, I should see 3 partitions and 3 Replica Nodes for each partition.

### What do you see instead?

I see 1 partition and 1 Replica node for this partition. That means the custom parameters are not in effect.

**Comment by liyuuKitchen** [comment]
"logRetentionHours=-1,logRetentionBytes=2199023985135,offsetsTopicReplicationFactor=3" is also not in effect

**Comment by migruiz4** [comment]
Hi @liyuuKitchen,

Version `24.x.x`  of the `bitnami/kafka` chart introduced several major changes, including the removal of those variables: https://github.com/bitnami/charts/tree/main/bitnami/kafka#to-2400

In order to extend Kafka configuration, you should now use the value `extraConfig`:
```
# extraConfig needs to be provided as valid Kafka properties: https://kafka.apache.org/documentation/#brokerconfigs
# This setting will be rendered as a template and appended directly to server.properties
extraConfig: |
  log.retention.hours=-1,
  log.retention.bytes=2199023985135
  offsets.topic.replication.factor=3
# Number of controller+broker nodes. If you'd like to deploy controller-only nodes, set controller.controllerOnly=true
controller:
  replicaCount: 3
  #controllerOnly: false
# Number of brokerOnly nodes
broker:
  replicaCount: 0
# Provisioning values remain untouched
provisioning:
    enabled: true
    replicationFactor: 3
    numPartitions: 3
```
