### ISSUE TITLE
[bitnami/rabbitmq] ingress writing changes

### ISSUE THREAD

**Issue by Aurorxa** [bitnami/charts#19186]
### Name and Version

bitnami/rabbitmq v12.1.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. k8s version is v1.21.14，helm version is v3.11.3 
2. now ingress demo is 
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /path
            pathType: Prefix
            backend:
              service:
                name: your-service-name
                port:
                  number: 80
```
3 but, the chart value in bitnami/rabbitmq is below 
```yaml
  extraHosts: []
  ## @param ingress.extraPaths An array with additional arbitrary paths that may need to be added to the ingress under the main host
  ## e.g:
  ## extraPaths:
  ## - path: /*
  ##   backend:
  ##     serviceName: ssl-redirect
  ##     servicePort: use-annotation
```
### What do you see instead?

![image](https://github.com/bitnami/charts/assets/25677587/51f47d66-b566-4f95-90e0-225058abec50)

**Comment by fevisera** [comment]
Hi @Aurorxa,

Sorry for the delay. I'm trying to gain a better understanding of the issue you reported. I noticed that in the screenshot, you are executing the command `helm install rabbitmq rabbitmq-12.1.3.tgz -n robot -f override.yaml`. Would you kindly shre the content of that `override.yaml` file? This will allow me to attempt to reproduce the error on my side.

Thanks.

**Comment by Aurorxa** [comment]
What I mean is that Ingress 'yaml writing has changed, so the comments need to be updated。
In the early days, ingress was written as follows
```yaml
  extraHosts: []
  ## @param ingress.extraPaths An array with additional arbitrary paths that may need to be added to the ingress under the main host
  ## e.g:
  ## extraPaths:
  ## - path: /*
  ##   backend:
  ##     serviceName: ssl-redirect
  ##     servicePort: use-annotation
```
However, ingress is now written as follows

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /path
            pathType: Prefix
            backend:
              service:
                name: your-service-name
                port:
                  number: 80
```
In other words, the comments should read as follows
```yaml
  extraHosts: []
  ## @param ingress.extraPaths An array with additional arbitrary paths that may need to be added to the ingress under the main host
  ## e.g:
  ## extraPaths:
  ## - path: /*
  ##   backend:
  ##     service: 
  ##        name: ssl-redirect  # edit
  ##        port: use-annotation # edit
```
