### ISSUE TITLE
[bitnami/rabbitmq] Values yaml doesn't contain MQTT plugin w/ tls functionality

### ISSUE THREAD

**Issue by RyanMannix** [bitnami/charts#19207]
### Name and Version

bitnami/rabbitmq

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Enable tls for the main broker.
Uncomment the lines in the MQTT plugin section to enable the mqtt.ssl.listener.default value

### What is the expected behavior?

mqtt plugin listens on 8883 for tls encrypted messages

### What do you see instead?

There were no apparent changes.

Service did not have port 8883 and pod didn't have any ports opened for 8883.
Rabbitmq logs didn't not output a line for starting a tls listener on 8883

### Additional information

tls is enabled in the rabbitmq instance for the main broker, and everything stands up correctly. 

After uncommenting the lines didn't bring the desired functionality, I hoped that opening/exposing the correct ports would work.

I manually created the service entries in the yaml file for the service port
 ```yaml
ports:
    amqp: 5672
    amqpTls: 5671
    dist: 25672
    manager: 15672
    metrics: 9419
    epmd: 4369
    mqtt: 1883
    mqttTls: 8883
  ## Service ports name
  ## @param service.portNames.amqp Amqp service port name
  ## @param service.portNames.amqpTls Amqp TLS service port name
  ## @param service.portNames.dist Erlang distribution service port name
  ## @param service.portNames.manager RabbitMQ Manager service port name
  ## @param service.portNames.metrics RabbitMQ Prometheues metrics service port name
  ## @param service.portNames.epmd EPMD Discovery service port name
  ## @param service.portNames.mqtt MQTT service port name
  ##
  portNames:
    amqp: "amqp"
    amqpTls: "amqp-tls"
    dist: "dist"
    manager: "http-stats"
    metrics: "metrics"
    epmd: "epmd"
    mqtt: "mqtt"
    mqttTls: "mqtt-tls"
  ## Node ports to expose
  ## @param service.nodePorts.amqp Node port for Ampq
  ## @param service.nodePorts.amqpTls Node port for Ampq TLS
  ## @param service.nodePorts.dist Node port for Erlang distribution
  ## @param service.nodePorts.manager Node port for RabbitMQ Manager
  ## @param service.nodePorts.epmd Node port for EPMD Discovery
  ## @param service.nodePorts.metrics Node port for RabbitMQ Prometheues metrics
  ## @param service.nodePorts.mqtt Node port for MQTT
  ##
  nodePorts:
    amqp: ""
    amqpTls: ""
    dist: ""
    manager: ""
    epmd: ""
    metrics: ""
    mqtt: ""
    mqttTls: ""
  ## @param service.extraPorts Extra ports to expose in the service
  ## E.g.:
  ## extraPorts:
  ## - name: new_svc_name
  ##   port: 1234
  ##   targetPort: 1234
  ##
  extraPorts:
    - name: "mqtt"
      port: 1883
      targetPort: 1883
    - name: "mqtt-tls"
      port: 8883
      targetPort: 8883
```

And manually added the container port:
```yaml
extraContainerPorts:
  - name: mqtt
    containerPort: 1883
  - name: mqtt-tls
    containerPort: 8883
```

The MQTT section:
```yaml
## @section  MQTT plugin configuration
# see https://www.rabbitmq.com/mqtt.html

mqtt.listeners.tcp.default: 1883
## Default MQTT with TLS port is 8883
mqtt.listeners.ssl.default: 8883
ssl_cert_login: false  ###### tried this with both true and false

# anonymous connections, if allowed, will use the default
# credentials specified here
mqtt.allow_anonymous: true ## tried with true and false, just to check
mqtt.default_user: <username>
mqtt.default_pass: <password>

mqtt.vhost: /
mqtt.exchange: amq.topic
# 24 hours by default
mqtt.subscription_ttl: 86400000
mqtt.prefetch: 10

# Use ETS-based storage for retaining MQTT messages
mqtt.retained_message_store: rabbit_mqtt_retained_msg_store_dets

# configure lower max WAL segment since quorum queues aren't used
raft.wal_max_size_bytes: 67108864
```

But even after creating the service ports and container ports, there's no indication that rabbitmq is receiving any communications on 8883
