### ISSUE TITLE
[bitnami/postgresql] global.postgresql.auth.secretKeys doesn't fully override auth.secretKeys if the username is not "postgres"

### ISSUE THREAD

**Issue by archer-321** [bitnami/charts#19202]
### Name and Version

bitnami/postgresql 12.11.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Start with a fresh Kubernetes cluster. When using minikube, `minikube start -p postgresql` should be enough.\
   I used a minikube cluster to reproduce this problem throughout this issue. However, I'm also experiencing the same on a production cluster maintained with `kubeadm`.
2. Create a `postgresql` namespace:\
   `kubectl create namespace postgresql`
3. Create a secret containing PostgreSQL's various passwords:\
   `kubectl create secret -n postgresql generic postgres-creds --from-literal=user=foo --from-literal=admin=bar --from-literal=replication=baz`
4. Create the `values.yml` file listed in the section below:
   ```sh
   $ cat << EOF > values.yml
   global:
     postgresql:
       auth:
         username: customuser
         existingSecret: postgres-creds
         secretKeys:
           adminPasswordKey: admin
           userPasswordKey: user
           replicationPasswordKey: replication
   EOF
   ```
5. Try to install `bitnami/postgresql` version `12.11.1`:
   ```sh
   $ helm install -n postgresql -f values.yml arrow bitnami/postgresql --version 12.11.1
   Error: INSTALLATION FAILED: execution error at (postgresql/templates/secrets.yaml:23:16):
   PASSWORDS ERROR: The secret "postgres-creds" does not contain the key "password"
   ```

### Are you using any custom parameters or values?

I'm using the following `values.yml` file:

```yaml
global:
  postgresql:
    auth:
      username: customuser
      existingSecret: postgres-creds
      secretKeys:
        adminPasswordKey: admin
        userPasswordKey: user
        replicationPasswordKey: replication
```

### What is the expected behavior?

The documentation of `global.postgresql.auth.secretKeys`'s various sub-keys states the following:

> Name of key in existing secret to use for PostgreSQL credentials (overrides auth.secretKeys.userPasswordKey). [...]

Based on this, `global.postgresql.auth.secretKeys` should fully override `auth.secretKeys.*`, and users shouldn't have to re-specify values in that section.

### What do you see instead?

Setting a custom username with `global.postgresql.auth.username` makes [this block][error-source] ignore the value in `global.postgresql.auth.secretKeys.userPasswordKey`. Instead, the chart uses the value in `auth.secretKeys.userPasswordKey` which defaults to `"password"`.

[error-source]: https://github.com/bitnami/charts/blob/36b616986bdb3b62aba434f63f99c4fd70b060b7/bitnami/postgresql/templates/secrets.yaml#L22-L24

If the user has set a different key in `global.postgresql.auth.secretKeys.userPasswordKey`, installing the chart fails with the following error message: 

```sh
Error: INSTALLATION FAILED: execution error at (postgresql/templates/secrets.yaml:23:16):
PASSWORDS ERROR: The secret "postgres-creds" does not contain the key "password"
```

### Additional information

I first experienced this with a Nextcloud deployment (nextcloud/helm#445). All other deployments of `bitnami/postgresql` in my cluster were using the key `password`, so I didn't run into this issue.

## Temporary workaround

As a temporary workaround, users can set `auth.secretKeys.userPasswordKey` accordingly:

`values.yml`:

```yaml
# === New block ===
auth:
  secretKeys:
    userPasswordKey: user
# === End of new block ===
global:
  postgresql:
    auth:
      username: customuser
      existingSecret: postgres-creds
      secretKeys:
        adminPasswordKey: admin
        userPasswordKey: user
        replicationPasswordKey: replication
```

While this fixes the problem, it defeats the purpose of having a `global.postgresql.auth.secretKeys` section.
