### ISSUE TITLE
[bitnami/redis] NOPERM this  user has no permissions to access subscribe channel in redis sentinel

### ISSUE THREAD

**Issue by farhadkh000** [bitnami/charts#19244]
### Name and Version

bitnami/redis  17.3.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

in kubernetes cluster i deploy sentinel cluster with helm chart , when i want  subscribe a channel i get this error 
`Reading messages... (press Ctrl-C to quit)
(error) NOPERM this user has no permissions to access one of the channels used as arguments
`

### Are you using any custom parameters or values?

i use extraVolumes to mount users.acl file 
```
 extraVolumes:
    - name: aclfile
      configMap:
        name: aclfile
  ## @param master.extraVolumeMounts Optionally specify extra list of additional volumeMounts for the Redis&reg; master container(s)
  ##

  extraVolumeMounts:
    - name: aclfile
      mountPath: /opt/bitnami/redis/users.acl
      subPath: users.acl

commonConfiguration: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""
  aclfile /opt/bitnami/redis/users.acl
  #loglevel debug
## @param extraDeploy Array of extra objects to deploy with the release
##
extraDeploy:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: aclfile
      labels: {{- include "common.labels.standard" . | nindent 6 }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 6 }}
        {{- end }}
      {{- if .Values.commonAnnotations }}
      annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 6 }}
      {{- end }}
    data:
      users.acl: |-
        user admin  on  ~* +@all >Fo6R9^!
        user notif on ~* +@all -@dangerous +info +role +dbsize >Dc17^mu!b
        user default on ~* +@all >Fo6R9^!

## Enable diagnostic mode in the deployment
```

### What is the expected behavior?

I didn't find any specific config for this, I expected it to be easy to configure

### What do you see instead?
```
192.168.114.123:6384> role
1) "master"
2) (integer) 1221371
3) 1) 1) "redis-notif01-node-1.redis-notif01-headless.technical-bigdata-redissen-notif01.svc.cluster.local"
      2) "6379"
      3) "1221357"
   2) 1) "redis-notif01-node-2.redis-notif01-headless.technical-bigdata-redissen-notif01.svc.cluster.local"
      2) "6379"
      3) "1221357"
192.168.114.123:6384> SUBSCRIBE a a
Reading messages... (press Ctrl-C to quit)
(error) NOPERM this user has no permissions to access one of the channels used as arguments
```
