### ISSUE TITLE
[bitnami/kube-prometheus] Prometheus podAntiAffinity does not match podLabels

### ISSUE THREAD

**Issue by TwoStone** [bitnami/charts#19246]
### Name and Version

bitnami/kube-prometheus 8.18.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy the helm chart with enabled prometheus instance

### Are you using any custom parameters or values?

`releaseName: prometheus-app`

```
prometheus:
  podAntiAffinityPreset: hard
```

### What is the expected behavior?

Prometheus pods do have configured podAntiAffinity that prevents two instances on the same node

### What do you see instead?

Prometheus pods get configured with wrong podAntiAffinity. The labelSelector for the podAntiAffinity does not match the labels of the created prometheus pods.

Here is an example from one of our prometheuses:
```
metadata:
  labels:                                                                                                                                                                           
     app.kubernetes.io/component: prometheus                                                                                                                                         
     app.kubernetes.io/instance: app-prometheus                                                                                                                                      
     app.kubernetes.io/managed-by: prometheus-operator                                                                                                                               
     app.kubernetes.io/name: prometheus
```

```
spec:
  affinity:
    podAntiAffinity:                                                                                                                                                                
      requiredDuringSchedulingIgnoredDuringExecution:                                                                                                                               
       - labelSelector:                                                                                                                                                              
           matchLabels:                                                                                                                                                              
             app.kubernetes.io/component: prometheus                                                                                                                                 
             app.kubernetes.io/instance: prometheus-app                                                                                                                              
             app.kubernetes.io/name: kube-prometheus
```

As you can see, the `app.kubernetes.io/name` and `app.kubernetes.io/instance` do not match, so the antiAffinity has not effect at all.
