### ISSUE TITLE
[bitnami/thanos] Setting ServiceMonitor selector results in invalid YAML

### ISSUE THREAD

**Issue by cablespaghetti** [bitnami/charts#19285]
### Name and Version

bitnami/thanos 12.13.3

### What architecture are you using?

None

### What steps will reproduce the bug?

Enabling metrics and the serviceMonitor with a custom `selector` value.

### Are you using any custom parameters or values?

```yaml
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    selector:
      prometheus: primary
```

### What is the expected behavior?

Making a serviceMonitor with the extra label for my prometheus operator to pick it up.

### What do you see instead?

```yaml
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos
      app.kubernetes.io/instance: thanos
      app.kubernetes.io/component: storegateway
      prometheus-operator/monitor: 'true'prometheus: primary
```

YAML missing a line break which causes Helm to fail.
