### ISSUE TITLE
[bitnami/postgresql-ha] Unable to upgrade the postgresql-ha release

### ISSUE THREAD

**Issue by vipcxj** [bitnami/charts#19292]
### Name and Version

bitnami/postgresql-ha

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. install a chart with
```yaml
global:
  postgresql:
    password: "XXXXX"
    repmgrPassword: "XXXXX"
  pgpool:
    adminUsername: "admin"
    adminPassword: "XXXXX"
  ldap:
    bindpw: "XXXXX"
```
2. upgrade the release

### Are you using any custom parameters or values?

yes, just see reproduce steps 2

### What is the expected behavior?

no error

### What do you see instead?
```
Pulled: registry-1.docker.io/bitnamicharts/postgresql-ha:11.9.4
Digest: sha256:4e207dc24b754d00a93f43baf11f40c6d17d5c3ac808314bce42ce5ccff42b56
Error: UPGRADE FAILED: execution error at (postgresql-ha/templates/NOTES.txt:101:4): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'postgresql.password' must not be empty, please add '--set postgresql.password=$PASSWORD' to the command. To get the current value:

        export PASSWORD=$(kubectl get secret --namespace "default" postgresql-ha-postgresql -o jsonpath="{.data.password}" | base64 -d)

    'postgresql.repmgrPassword' must not be empty, please add '--set postgresql.repmgrPassword=$REPMGR_PASSWORD' to the command. To get the current value:

        export REPMGR_PASSWORD=$(kubectl get secret --namespace "default" postgresql-ha-postgresql -o jsonpath="{.data.repmgr-password}" | base64 -d)

    'pgpool.adminPassword' must not be empty, please add '--set pgpool.adminPassword=$ADMIN_PASSWORD' to the command. To get the current value:

        export ADMIN_PASSWORD=$(kubectl get secret --namespace "default" postgresql-ha-pgpool -o jsonpath="{.data.admin-password}" | base64 -d)
```
### Additional information

I have provided postgresql.password, postgresql.repmgrPassword and pgpool.adminPassword through global.postgresql.password, global.postgresql.repmgrPassword and global.pgpool.adminPassword, but it seems that the helm not recognized them.

**Comment by damoun** [comment]
Can you set your values outside of `global` ? Like

```
postgresql:
  password: "XXXXX"
  repmgrPassword: "XXXXX"
pgpool:
  adminUsername: "admin"
  adminPassword: "XXXXX"
ldap:
  bindpw: "XXXXX"
```
