### ISSUE TITLE
Flink deployment template missing imagePullSecrets

### ISSUE THREAD

**Issue by rituraj-AU** [bitnami/charts#19302]
### Name and Version

bitnami/flink 0.4.1

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Create a chart with dependency on bitnami/flink:

`Chart.yaml`
```yaml
apiVersion: v2
name: flink
description: A Helm chart for Flink
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: flink
    version: 0.4.1
    repository: https://charts.bitnami.com/bitnami
```

Then either add `global.imagePullSecrets` or `image.pullSecrets`:

`values.yaml`
```yaml
flink:
  global:
    imagePullSecrets:
      - my-secret
  image:
    registry: "my.private.registry"
    repository: "my.repo"
    tag: "1.0"
    pullPolicy: "Always"
    pullSecrets:
      - my-secret
```

Expected rendered chart
```yaml
containers:
        - name: flink-taskmanager
          image: my.private.registry/my.repo:1.0
          imagePullPolicy: "Always"
          imagePullSecrets:
            - my-secret
```

Actual:
`imagePullSecrets` is missing.

Cause:
`deployment.yaml` in job manager and task manager are missing any reference to `imagePullSecrets`
https://github.com/bitnami/charts/blob/main/bitnami/flink/templates/jobmanager/deployment.yaml
https://github.com/bitnami/charts/blob/main/bitnami/flink/templates/taskmanager/deployment.yaml

This is preventing me from pulling flink from a private repo

### What is the expected behavior?

Expected rendered chart
```yaml
containers:
        - name: flink-taskmanager
          image: my.private.registry/my.repo:1.0
          imagePullPolicy: "Always"
          imagePullSecrets:
            - my-secret
```

### What do you see instead?

Actual:
`imagePullSecrets` is missing.
