### ISSUE TITLE
Helm install of influxdb - influxdb dont start automaticly

### ISSUE THREAD

**Issue by GhostTalker** [bitnami/charts#19312]
### Name and Version

bitnami/influxdb 5.9.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install influxdb with config.yaml
`helm upgrade --namespace database --install influxdb bitnami/influxdb -f ./values.yaml`
2. Use of PersistentVolumeClaim

### Are you using any custom parameters or values?
```yaml
image:
  registry: docker.io
  repository: bitnami/influxdb
  tag: latest
  digest: ""
  pullPolicy: Always
  debug: true

auth:
  enabled: true
  usePasswordFiles: false

  service:
    sessionAffinity: ClientIP
    sessionAffinityConfig:
      clientIP:
        timeoutSeconds: 300

ingress:
  enabled: true
  tls: false
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: influxdb.mynetwork.lan
  path: /

metrics:
  enabled: true

persistence:
  enabled: true
  existingClaim: "influxdb-pv-claim"

volumePermissions:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/os-shell
    tag: 11-debian-11-r60
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []

securityContext:
    runAsUser: 0
```
### What is the expected behavior?

1. Auto setup and autostart of influxdb
2. UI reachable via browser

### What do you see instead?

Influxdb is not starting and also not set at the first time.

I have to log in to the container and execute there:

1. for setup
    /opt/bitnami/scripts/influxdb/entrypoint.sh /opt/bitnami/scripts/influxdb/run.sh
   
2. for startup
  /opt/bitnami/scripts/influxdb/run.sh &
