### ISSUE TITLE
[bitnami/rabbitmq] Unexpected restart behavior when using load definition

### ISSUE THREAD

**Issue by WFA-hhsieh** [bitnami/charts#19318]
### Name and Version

bitnami/rabbitmq 12.1.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Enable load definition
2. Not set auth.password
3. Deploy helm

### Are you using any custom parameters or values?

```yaml
auth:
  existingErlangSecret: xxx

loadDefinition:
  enabled: true
  existingSecret: xxx

extraConfiguration: |-
  loopback_users.guest = false
  listeners.tcp.default = 5672
  management.tcp.port = 15672
```

### What is the expected behavior?

RabbitMQ should not regenerate the user password in rabbitmq secret and restart the server when load definition is enabled and without setting `auth.password`.

### What do you see instead?

RabbitMQ always restarted unexpectedly every hour
