### ISSUE TITLE
[bitnami/logstash] headless-svc doesn't respect service.type

### ISSUE THREAD

**Issue by ahmadidev** [bitnami/charts#19313]
### Name and Version

5.5.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1- logstash-values.yaml
Set service.type: NodePort and set ports template as below custom values.

2- Install chart
```bash
helm upgrade --install --namespace elk --create-namespace logstash bitnami/logstash --values=logstash-values.yaml
```

### Are you using any custom parameters or values?

```yaml
service:
  type: NodePort
  ports:
  - name: http
    nodePort: 30202
    port: 8080
    protocol: TCP
    targetPort: http
```

### What is the expected behavior?

`logstash-headless` service should be created with `type: NodePort`

### What do you see instead?

```yaml
# Source: logstash/templates/headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: logstash-headless
  namespace: "elk"
  labels:
    app.kubernetes.io/name: logstash
    helm.sh/chart: logstash-5.4.10
    app.kubernetes.io/instance: logstash
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      nodePort: 30202
      port: 8080
      protocol: TCP
      targetPort: http
```

### Additional information

The logstash service respects `type: NodePort` but the type of logstash-headless service is [statically ](https://github.com/bitnami/charts/blob/8b6ee5a92648d921b09faf3e9087ee64840d2cf0/bitnami/logstash/templates/headless-svc.yaml#L17)set to ClusterIP and installing the chart with the above custom config results in the below error:
```
Error: UPGRADE FAILED: cannot patch "logstash-headless" with kind Service: Service "logstash-headless" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```
