### ISSUE TITLE
Struggling to install mongodb replicaset with TLS

### ISSUE THREAD

**Issue by igor-pinchuk** [bitnami/charts#19360]
### Name and Version

bitnami/mongodb/13.18.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

What I am going to do looks very straight forward and something that I have done many times before without using K8S or Helm just on dedicated instances.
I just need to install replica-set with 3 nodes and with TLS enabled (preferably with autoGenerated=true).
If this installation is something non-trivial - please provide configuration examples or at least show some meaningful logs.

Running on EKS 1.27

### Are you using any custom parameters or values?

```yaml
arbiter:
  enabled: false
architecture: replicaset
auth:
  databases:
  - mydb
  enabled: true
  passwords:
  - cgadmin
  replicaSetKey: rskey
  rootPassword: root
  rootUser: root
  usernames:
  - cgadmin
directoryPerDB: true
externalAccess:
  enabled: false
persistence:
  enabled: true
  existingClaim: keep
  size: 10Gi
replicaCount: 3
replicaSetName: rs0
systemLogVerbosity: 5
tls:
  autoGenerated: true
  enabled: true
```

### What is the expected behavior?

The expected behaviour is to have running replicaset or some meaningful logs that can be used for debuging.

### What do you see instead?

The first pod is failing without any logs that can help in troubleshooting.

### Additional information

**logs:**
```
kubectl logs -n db mongodb-0
Defaulted container "mongodb" out of: mongodb, generate-tls-certs (init)
mongodb 16:04:43.93 INFO  ==> Advertised Hostname: mongodb-0.mongodb-headless.db.svc.cluster.local
mongodb 16:04:43.93 INFO  ==> Advertised Port: 27017
mongodb 16:04:43.94 INFO  ==> Data dir empty, checking if the replica set already exists
MongoNetworkError: getaddrinfo ENOTFOUND mongodb-2.mongodb-headless.db.svc.cluster.local
mongodb 16:04:44.46 INFO  ==> Pod name matches initial primary pod name, configuring node as a primary
mongodb 16:04:44.47
mongodb 16:04:44.48 Welcome to the Bitnami mongodb container
mongodb 16:04:44.48 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 16:04:44.48 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 16:04:44.48
mongodb 16:04:44.48 INFO  ==> ** Starting MongoDB setup **
mongodb 16:04:44.50 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 16:04:44.56 INFO  ==> Initializing MongoDB...
mongodb 16:04:44.59 INFO  ==> Writing keyfile for replica set authentication...
mongodb 16:04:44.61 INFO  ==> Deploying MongoDB from scratch...
```

**pod events**
```
Events:
  Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
  Normal   Scheduled               2m15s                default-scheduler        Successfully assigned db/mongodb-0 to ip-10-110-22-69.eu-west-1.compute.internal
  Normal   SuccessfulAttachVolume  2m13s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-381ea963-dfaf-412d-b5e3-5289b8ec6d2f"
  Normal   Pulled                  2m10s                kubelet                  Container image "docker.io/bitnami/nginx:1.25.2-debian-11-r25" already present on machine
  Normal   Created                 2m10s                kubelet                  Created container generate-tls-certs
  Normal   Started                 2m10s                kubelet                  Started container generate-tls-certs
  Normal   Pulled                  77s (x4 over 2m10s)  kubelet                  Container image "docker.io/bitnami/mongodb:6.0.10-debian-11-r0" already present on machine
  Normal   Created                 77s (x4 over 2m10s)  kubelet                  Created container mongodb
  Normal   Started                 77s (x4 over 2m10s)  kubelet                  Started container mongodb
  Warning  BackOff                 56s (x10 over 2m6s)  kubelet                  Back-off restarting failed container mongodb in pod mongodb-0_db(c2656b46-f18d-4c42-9d21-d36ace3c77f6)
```
