### ISSUE TITLE
[bitnami/wordpress] Failure to create new pod during upgrade.

### ISSUE THREAD

**Issue by ZandercraftGames** [bitnami/charts#19367]
### Name and Version

bitnami/wordpress 17.1.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Using Rancher with k3s, a traefik ingress, and Longhorn storage engine.
2. Install "Wordpress" application from the Apps menu
3. Use the given configuration below.
4. Update/Upgrade the system or delete the application and re-install it with the same configuration under the same namespace. Or even redeploy the deployment/pod.

### Are you using any custom parameters or values?

```YAML
affinity: {}
allowEmptyPassword: false
allowOverrideNone: false
apacheConfiguration: ''
args: []
autoscaling:
  enabled: false
  maxReplicas: 11
  minReplicas: 1
  targetCPU: 50
  targetMemory: 50
clusterDomain: cluster.local
command: []
commonAnnotations: {}
commonLabels: {}
containerPorts:
  http: 8080
  https: 8443
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  enabled: true
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001
customHTAccessCM: ''
customLivenessProbe: {}
customPostInitScripts: {}
customReadinessProbe: {}
customStartupProbe: {}
diagnosticMode:
  args:
    - infinity
  command:
    - sleep
  enabled: false
existingApacheConfigurationConfigMap: ''
existingSecret: ''
existingWordPressConfigurationSecret: ''
externalCache:
  host: localhost
  port: 11211
externalDatabase:
  database: <REDACTED>
  existingSecret: ''
  host: localhost
  password: <REDACTED>
  port: 3306
  user: <REDACTED>
extraContainerPorts: []
extraDeploy: []
extraEnvVars: []
extraEnvVarsCM: ''
extraEnvVarsSecret: ''
extraVolumeMounts: []
extraVolumes: []
fullnameOverride: ''
global:
  imagePullSecrets: []
  imageRegistry: ''
  storageClass: longhorn
  cattle:
    systemProjectId: p-rdlrp
hostAliases:
  - hostnames:
      - status.localhost
      - <REDACTED>
      - www.<REDACTED>
    ip: 127.0.0.1
htaccessPersistenceEnabled: true
image:
  debug: false
  digest: ''
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: docker.io
  repository: bitnami/wordpress
  tag: 6.3.0-debian-11-r9
ingress:
  annotations:
    cert-manager.io/issuer: <REDACTED>
  apiVersion: ''
  enabled: true
  extraHosts:
    - name: www.<REDACTED>
      path: /
  extraPaths: []
  extraRules: []
  extraTls: []
  hostname: <REDACTED>
  ingressClassName: traefik
  path: /
  pathType: ImplementationSpecific
  secrets: []
  selfSigned: false
  tls: true
  tlsWwwPrefix: true
initContainers: []
kubeVersion: ''
lifecycleHooks: {}
livenessProbe:
  enabled: true
  failureThreshold: 6
  httpGet:
    httpHeaders: []
    path: /wp-admin/install.php
    port: '{{ .Values.wordpressScheme }}'
    scheme: '{{ .Values.wordpressScheme | upper }}'
  initialDelaySeconds: 120
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
mariadb:
  architecture: standalone
  auth:
    database: <REDACTED>
    password: <REDACTED>
    rootPassword: <REDACTED>
    username: <REDACTED>
  enabled: true
  primary:
    persistence:
      accessModes:
        - ReadWriteOnce
      enabled: true
      size: 6Gi
      storageClass: ''
memcached:
  auth:
    enabled: false
    password: ''
    username: ''
  enabled: true
  service:
    port: 11211
metrics:
  containerPorts:
    metrics: 9117
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  enabled: false
  image:
    digest: ''
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/apache-exporter
    tag: 1.0.1-debian-11-r21
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 15
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 3
  resources:
    limits: {}
    requests: {}
  service:
    annotations:
      prometheus.io/port: '{{ .Values.metrics.containerPorts.metrics }}'
      prometheus.io/scrape: 'true'
    ports:
      metrics: 9150
  serviceMonitor:
    enabled: true
    honorLabels: false
    interval: ''
    jobLabel: ''
    labels: {}
    metricRelabelings: []
    namespace: ''
    relabelings: []
    scrapeTimeout: ''
    selector: {}
  startupProbe:
    enabled: false
    failureThreshold: 15
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
multisite:
  enable: false
  enableNipIoRedirect: false
  host: ''
  networkType: subdomain
nameOverride: ''
networkPolicy:
  egressRules:
    customRules: {}
    denyConnectionsToExternal: false
  enabled: false
  ingress:
    enabled: false
    namespaceSelector: {}
    podSelector: {}
  ingressRules:
    accessOnlyFrom:
      enabled: false
      namespaceSelector: {}
      podSelector: {}
    backendOnlyAccessibleByFrontend: false
    customBackendSelector: {}
    customRules: {}
  metrics:
    enabled: false
    namespaceSelector: {}
    podSelector: {}
nodeAffinityPreset:
  key: ''
  type: ''
  values: []
nodeSelector: {}
overrideDatabaseSettings: false
pdb:
  create: false
  maxUnavailable: ''
  minAvailable: 1
persistence:
  accessMode: ReadWriteOnce
  accessModes:
    - ReadWriteOnce
  annotations: {}
  dataSource: {}
  enabled: true
  existingClaim: ''
  selector: {}
  size: 10Gi
  storageClass: ''
podAffinityPreset: ''
podAnnotations: {}
podAntiAffinityPreset: soft
podLabels: {}
podSecurityContext:
  enabled: true
  fsGroup: 1001
  seccompProfile:
    type: RuntimeDefault
priorityClassName: ''
readinessProbe:
  enabled: true
  failureThreshold: 6
  httpGet:
    httpHeaders: []
    path: /wp-login.php
    port: '{{ .Values.wordpressScheme }}'
    scheme: '{{ .Values.wordpressScheme | upper }}'
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
replicaCount: 1
resources:
  limits: {}
  requests:
    cpu: 300m
    memory: 512Mi
schedulerName: ''
service:
  annotations: {}
  clusterIP: ''
  externalTrafficPolicy: Cluster
  extraPorts: []
  httpsTargetPort: https
  loadBalancerIP: ''
  loadBalancerSourceRanges: []
  nodePorts:
    http: ''
    https: ''
  ports:
    http: 80
    https: 443
  sessionAffinity: None
  sessionAffinityConfig: {}
  type: ClusterIP
serviceAccount:
  annotations: {}
  automountServiceAccountToken: true
  create: false
  name: ''
sidecars: []
smtpExistingSecret: ''
smtpHost: <REDACTED>
smtpPassword: <REDACTED>
smtpPort: '587'
smtpProtocol: ssl
smtpUser: <REDACTED>
startupProbe:
  enabled: false
  failureThreshold: 6
  httpGet:
    httpHeaders: []
    path: /wp-login.php
    port: '{{ .Values.wordpressScheme }}'
    scheme: '{{ .Values.wordpressScheme | upper }}'
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
terminationGracePeriodSeconds: ''
tolerations: []
topologySpreadConstraints: []
updateStrategy:
  type: RollingUpdate
volumePermissions:
  containerSecurityContext:
    runAsUser: 0
  enabled: false
  image:
    digest: ''
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/os-shell
    tag: 11-debian-11-r43
  resources:
    limits: {}
    requests: {}
wordpressBlogName: <REDACTED>
wordpressConfiguration: ''
wordpressConfigureCache: false
wordpressEmail: <REDACTED>
wordpressExtraConfigContent: ''
wordpressFirstName: <REDACTED>
wordpressLastName: <REDACTED>
wordpressPassword: <REDACTED>
wordpressPlugins: none
wordpressScheme: http
wordpressSkipInstall: false
wordpressTablePrefix: wp_
wordpressUsername: <REDACTED>
```

### What is the expected behavior?

The wp-content (images, plugins, etc.) should be persisted as the db and wordpress container reconnects to the same Longhorn volume with the existing data.

### What do you see instead?

The database data is persisted, but the wp-content data is not resulting in pages still existing, warnings about plugin files missing, and blank images showing in the Wordpress Media tab (because the files themselves are missing).

### Additional information

I've tried quite a bit to persist the data from it, but nothing seems to work.

**Comment by juan131** [comment]
Hi @ZandercraftGames 

Could you please share the WordPress container logs after you upgrade your release? Could you also please confirm that the PVC(s) that's created during the 1st installation isn't removed during upgrades?

Please note that the created PVC(s) will be removed if you uninstall the chart release, therefore it's expected you lose the data on this case.

**Comment by ZandercraftGames** [comment]
Thanks for reaching out @juan131! Just wanted to make sure you know I've seen your reply. Please give me a little bit to figure this out as I'm a little busy this weekend. I'll get back to you as soon as I can.

**Comment by ZandercraftGames** [comment]
So a few issues. After an update, it seems the persistence fails and plugin files are missing, so I end up with it giving an error 500. This results in the readiness probe failing and attempting to restart. Eventually it ends up stopping because it has failed repeatedly.
```
wordpress 21:34:00.17 INFO ==> ** Starting WordPress setup **
wordpress 21:34:00.19 INFO ==> Generating sample certificates
Generating RSA private key, 4096 bit long modulus (2 primes)
<>
Signature ok
subject=CN = example.com
Getting Private key
realpath: /bitnami/apache/conf: No such file or directory
wordpress 21:34:01.53 INFO ==> Configuring the HTTP port
wordpress 21:34:01.54 INFO ==> Configuring the HTTPS port
wordpress 21:34:01.55 INFO ==> Configuring Apache ServerTokens directive
wordpress 21:34:01.57 INFO ==> Configuring PHP options
wordpress 21:34:01.57 INFO ==> Setting PHP expose_php option
wordpress 21:34:01.58 INFO ==> Setting PHP output_buffering option
wordpress 21:34:01.60 INFO ==> Validating settings in MYSQL_CLIENT_* env vars
wordpress 21:34:01.78 INFO ==> Restoring persisted WordPress installation
wordpress 21:34:02.35 INFO ==> Trying to connect to the database server
wordpress 21:34:03.25 INFO ==> ** WordPress setup finished! **
 
wordpress 21:34:03.28 INFO ==> ** Starting Apache **
[Mon Sep 25 21:34:03.395962 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.57 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Mon Sep 25 21:34:03.396006 2023] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
[25-Sep-2023 21:34:39 UTC] PHP Warning: Unknown: Failed to open stream: No such file or directory in Unknown on line 0
[25-Sep-2023 21:34:39 UTC] PHP Fatal error: Failed opening required '/opt/bitnami/wordpress/wordfence-waf.php' (include_path='.:/opt/bitnami/php/lib/php') in Unknown on line 0
10.42.1.1 - - [25/Sep/2023:21:34:39 +0000] "GET /wp-login.php HTTP/1.1" 500 -
[25-Sep-2023 21:34:49 UTC] PHP Warning: Unknown: Failed to open stream: No such file or directory in Unknown on line 0
[25-Sep-2023 21:34:49 UTC] PHP Fatal error: Failed opening required '/opt/bitnami/wordpress/wordfence-waf.php' (include_path='.:/opt/bitnami/php/lib/php') in Unknown on line 0
0.42.1.1 - - [25/Sep/2023:21:34:49 +0000] "GET /wp-login.php HTTP/1.1" 500 -
[25-Sep-2023 21:34:59 UTC] PHP Warning: Unknown: Failed to open stream: No such file or directory in Unknown on line 0
[25-Sep-2023 21:34:59 UTC] PHP Fatal error: Failed opening required '/opt/bitnami/wordpress/wordfence-waf.php' (include_path='.:/opt/bitnami/php/lib/php') in Unknown on line 0
```

Alerts
![image](https://github.com/bitnami/charts/assets/28664144/fc5bc7b8-0f87-420a-946e-c488c15b8e32)

Related Resources (after update)
![image](https://github.com/bitnami/charts/assets/28664144/93a9b8d0-4cc7-49a5-a220-1f589e0d64c5)

**Comment by juan131** [comment]
Hi @ZandercraftGames 

> After an update, it seems the persistence fails and plugin files are missing, so I end up with it giving an error 500

What do you mean by "an update"? Do you mean updating WordPress through the Admin panel or updating the container image version?

```console
[25-Sep-2023 21:34:39 UTC] PHP Warning: Unknown: Failed to open stream: No such file or directory in Unknown on line 0
[25-Sep-2023 21:34:39 UTC] PHP Fatal error: Failed opening required '/opt/bitnami/wordpress/wordfence-waf.php' (include_path='.:/opt/bitnami/php/lib/php') in Unknown on line 0
```

I guess you installed the [Wordfence plugin](https://wordpress.org/plugins/wordfence/) and now its files are missing, right? Could you please share the exact steps you followed to install it?

**Comment by ZandercraftGames** [comment]
> Hi @ZandercraftGames
> 
> > After an update, it seems the persistence fails and plugin files are missing, so I end up with it giving an error 500
> 
> What do you mean by "an update"? Do you mean updating WordPress through the Admin panel or updating the container image version?
> 
> ```
> [25-Sep-2023 21:34:39 UTC] PHP Warning: Unknown: Failed to open stream: No such file or directory in Unknown on line 0
> [25-Sep-2023 21:34:39 UTC] PHP Fatal error: Failed opening required '/opt/bitnami/wordpress/wordfence-waf.php' (include_path='.:/opt/bitnami/php/lib/php') in Unknown on line 0
> ```
> 
> I guess you installed the [Wordfence plugin](https://wordpress.org/plugins/wordfence/) and now its files are missing, right? Could you please share the exact steps you followed to install it?

Hey there. I installed Wordfence by going to Plugins -> Add New -> (search for Wordfence) -> Install -> Activate. This particular part of my issue may actually be caused by #19452 when Wordfence exits learning mode and activates.

I know this issue is a bit of a mess because of my misunderstanding/mixup here, but one issue I've been having is that when theres a new update and I go to Upgrade via the Apps -> Installed Apps page, I end up with a new pod being spun up, the old one being stuck in Terminating, and no IP being able to be assigned to the new one with the install process eventually timing out and failing.

**Comment by ZandercraftGames** [comment]
So a quick update. It seems that it is indeed #19452 causing the container to start crashing, relating in the Crashloopbackoff. So that's good to figure out.
Relating to the upgrade process, it still ends up with a container being stuck in Containercreating with the following status causing upgrades to fail:
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-09-28T01:09:18Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-09-28T01:09:18Z"
    message: 'containers with unready status: [wordpress]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-09-28T01:09:18Z"
    message: 'containers with unready status: [wordpress]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-09-28T01:09:18Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: docker.io/bitnami/wordpress:6.3.0-debian-11-r9
    imageID: ""
    lastState: {}
    name: wordpress
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: ContainerCreating
  hostIP: <host IP>
  phase: Pending
  qosClass: Burstable
  startTime: "2023-09-28T01:09:18Z"
```
![image](https://github.com/bitnami/charts/assets/28664144/dfedc412-7218-4b95-a9ad-d8f40d41389a)

It seems to be unable to get an IP assignment (maybe the other pod is occupying the port or volume?) in this case and just kinda sits there in Containercreating forever, never actually upgrading. It seems that the persistence issue I was having was that the PVs were being deleted when I attempted to resolve this by re-installing the app (initial deployment works, subsequent upgrades not so much).

**Comment by juan131** [comment]
Hi @ZandercraftGames 

> One issue I've been having is that when theres a new update and I go to Upgrade via the Apps -> Installed Apps page, I end up with a new pod being spun up, the old one being stuck in Terminating, and no IP being able to be assigned to the new one with the install process eventually timing out and failing and the container sitting in a ContainerCreating status.

Readiness / liveness probes are intended to be run periodically to ensure the application is reachable. Therefore, if you upgrade WordPress via the admin panel and, during that process, the app's not responding (since it's running on maintenance mode for a few minutes) and the probes will fail restarting the WordPress container in the middle of the process and resulting on the issue you're experiencing.

You have two options to avoid that:

- Disable readiness / liveness probes while upgrading WordPress.
- Upgrade WordPress by updating the container image once Bitnami releases the new version instead of using Admin Panel.

> I installed Wordfence by going to Plugins -> Add New -> (search for Wordfence) -> Install -> Activate

I'll try to reproduce it tomorrow if I find the time but it's likely that Wordfence plugins is adding new files outside the persisted directories causing WordPress to fail if the container is recreated (since these files are gone).

**Comment by fmiqbal** [comment]
@ZandercraftGames wordfence indeed create new file 

you can add this to your helm chart values

```
...
extraEnvVars:
  - name: WORDPRESS_DATA_TO_PERSIST
    value: "wp-config.php wp-content wordfence-waf.php"
```

refer to https://github.com/bitnami/containers/tree/main/bitnami/wordpress

> WORDPRESS_DATA_TO_PERSIST: Space separated list of files and directories to persist. Use a space to persist no data: " ". Default: "wp-config.php wp-content"

but if you happen to already install wordfence and restarted (causing the `wordfence-waf.php` file to be missing), you can try disabling readiness check, and uninstall wordfence waf using wp-cli, or you can try adding file manually, here's a copy of mine:

```
<?php
// Before removing this file, please verify the PHP ini setting `auto_prepend_file` does not point to this.

if (file_exists(__DIR__.'/wp-content/plugins/wordfence/waf/bootstrap.php')) {
	define("WFWAF_LOG_PATH", __DIR__.'/wp-content/wflogs/');
	include_once __DIR__.'/wp-content/plugins/wordfence/waf/bootstrap.php';
}
```

**Comment by ZandercraftGames** [comment]
Would the liveness/readiness probe be what's causing the following behaviour?
```
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-09-28T01:15:31Z"
    lastUpdateTime: "2023-09-28T01:15:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-09-28T01:25:32Z"
    lastUpdateTime: "2023-09-28T01:25:32Z"
    message: ReplicaSet "wordpress-5c75c48b6" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
  ```
  
  
![image](https://github.com/bitnami/charts/assets/28664144/71c3cc9c-36ed-4b25-a195-194d5f602a85)
