### ISSUE TITLE
redis cluster init failed when namespace managed  by istio

### ISSUE THREAD

**Issue by mainy** [bitnami/charts#19386]
### Name and Version

bitnami/redis-cluster 

### What architecture are you using?

None

### What steps will reproduce the bug?

1.Install istio for k8s and  label the namespace with "istio-injection=enabled"
2.Install helm charts  with values:
![image](https://github.com/bitnami/charts/assets/12928781/e1602b11-ac6d-4e48-9985-34e905aa4f11)

3.Then we can see the cluster create pod logs:
![企业微信截图_16951111012045](https://github.com/bitnami/charts/assets/12928781/0c774b9b-029f-4a37-b8b9-66866d9bb34c)
It is waiting for the cluster to join . 
4.follow is cluster node logs:
![企业微信截图_16951111426324](https://github.com/bitnami/charts/assets/12928781/b9ca22be-6061-4fc0-a19b-70a472741d58)
![企业微信截图_16951111717575](https://github.com/bitnami/charts/assets/12928781/97b4f817-3122-4c03-92dc-8a2656644500)
![企业微信截图_1695111199342](https://github.com/bitnami/charts/assets/12928781/79502b01-4e29-4657-828a-2b615aa09688)
Only one of the nodes successfully joined the cluster, no matter how long they wait

Furthermore, if my namespace does not label  with "istio-injection=enabled" , everything is ok

### Are you using any custom parameters or values?

**the values :**
```yaml
redis-cluster:
  cluster:
    init: true
    nodes: 3
    replicas: 0
    update:
      addNodes: false
  fullnameOverride: wxx-redis-cluster-5x-istio
  metrics:
    enabled: false
  password: hzero
  persistence:
    enabled: true
    size: 8Gi
    storageClass: nfs
  service:
    port: 6379
  usePassword: true
```

### What do you see instead?

I don't know what caused the cluster initialization to fail. So I came here to seek help
