### ISSUE TITLE
Irritating security scanner results

### ISSUE THREAD

**Issue by wollud1969** [bitnami/charts#19389]
### Name and Version

bitnami/keycloak:16.1.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Use trivy scanner via trivy-operator in k3s environment

### Are you using any custom parameters or values?

```
postgresql:
  enabled: false

externalDatabase:
  host: timescaledb.database.svc.cluster.local
  port: 5432
  database: keycloak
  existingSecret: keycloak-db-cred
  existingSecretUserKey: username
  existingSecretPasswordKey: password

global:
  storageClass: nfs-client

auth:
  adminUser: admin
  existingSecret: keycloak-admin-password
  passwordSecretKey: password

production: true

replicaCount: 2

proxy: edge

tls:
  enabled: false

service:
  ports:
    http: 8080

ingress:
  enabled: false

commonAnnotations:
  secret.reloader.stakater.com/reload: "keycloak-db-cred"

```

### What is the expected behavior?

Scanner finds no vulnerabilities or at least no vuln. with high or critical severity.

### What do you see instead?

```
NAMESPACE↑   NAME                                                             REPOSITORY                                               TAG                  SCANNER CRITICAL HIGH MEDIUM LOW UNKNOWN 
idp          statefulset-keycloak-keycloak                                    bitnami/keycloak                                         22.0.3-debian-11-r0  Trivy   3        24   39     85  0       
```

### Additional information

This is not actually a bug report nor a report concerning vulnerabilities I found but more a question concerning findings of a security scanner. If you have a forum or slack to discuss those topics I would be glad I've you could let me know.
You see above that the trivy scanner from Aqua finds 3 issues with critical severity and 24 issues with high severity.
Critically severe issues are about curl, libcurl4, libdb5.3 and
highly severe issues are about bash, bind9-host, bind9-libs, again curl, libcom-err2, again libcurl4, libgcrypt20, libldap, libncurses, libss2, libssh, libtinfo, libxml2, libzstd1, ncurses-base, perl-base
Seems to me, that none of these findings are directly related to keycloak, however, they are related to stuff in the container image and I'm wondering whether you have evaluated all these findings and considered them as irrelevant or whether it might be an option to down strip the image to remove these components with findings.
Or is there a misunderstanding on my side or a to strict configuration of trivy bringing up too much false positives?
Thank you so far!
