### ISSUE TITLE
Helm Chart RabbitMQ-Operator PodSecurity Violation

### ISSUE THREAD

**Issue by nihaldivyam** [bitnami/charts#19394]
### Name and Version

bitnami/rabbitmq-cluster-operator 3.8.0
kubernetes v1.26.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install RabbitMQ-Operator using the Helm chart version 3.8.0.
2. Observe the error message mentioned above when trying to create pods.

### Are you using any custom parameters or values?

```yaml
rabbitmq-cluster-operator:
  useCertManager: "true"
  clusterOperator:
    resources:
      limits: null
      requests:
        cpu: 100m
        memory: 250Mi
  msgTopologyOperator:
    resources:
      limits: null
      requests:
        cpu: 100m
        memory: 250Mi
```

### What is the expected behavior?

```text
The expected behavior for the Helm Chart RabbitMQ-Operator, version 3.8.0, is that it should create pods that adhere to the specified PodSecurity policies. Specifically:

The pods created by the chart should have allowPrivilegeEscalation set to false within their securityContext. This means that containers within the pods should not be allowed to escalate their privileges.

The pods should not have unrestricted capabilities. The chart should configure the containers' securityContext.capabilities.drop to include ["ALL"], indicating that all Linux capabilities should be dropped for security purposes.

The seccompProfile for the pods or containers should be set to either "RuntimeDefault" or "Localhost" as per the PodSecurity requirements.
```

### What do you see instead?

```text
I see that when deploying the RabbitMQ-Operator using Helm chart version 3.8.0, it's generating pods that violate the specified PodSecurity policies. The error message displays as follows:
```

```bash
Warning   FailedCreate        replicaset/rabbitmq-operator   Error creating: pods "rabbitmq-operator-rabbitmq-operator-578snxfl" is forbidden: violates PodSecurity "restricted:v1.24":
- allowPrivilegeEscalation != false (container "rabbitmq-cluster-operator" must set securityContext.allowPrivilegeEscalation=false).
- unrestricted capabilities (container "rabbitmq-cluster-operator" must set securityContext.capabilities.drop=["ALL"]).
- seccompProfile (pod or container "rabbitmq-cluster-operator" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")

```

### Additional information

I fixed the issue using these values

```yaml
rabbitmq-cluster-operator:
  useCertManager: "true"
  clusterOperator:
    podSecurityContext:
      enabled: true
      fsGroup: 1001
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      capabilities:
          drop:
          - ALL
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
    resources:
      limits: null
      requests:
        cpu: 100m
        memory: 250Mi
  msgTopologyOperator:
    podSecurityContext:
      enabled: true
      fsGroup: 1001
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      capabilities:
          drop:
          - ALL
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
    resources:
      limits: null
      requests:
        cpu: 100m
        memory: 250Mi

```
