### ISSUE TITLE
[bitnami/minio] chart 12.8.5 upgrade with TLS fails

### ISSUE THREAD

**Issue by bobbeeke** [bitnami/charts#19392]
### Name and Version

charts/bitnami/minio 12.8.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy Minio chart version 12.8.5 with TLS values

### Are you using any custom parameters or values?

```yaml
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      enabled: true
      hostname: <hostname>
      ingressClassName: nginx
      tls: true
```

### What is the expected behavior?

The chart will deploy with ingress and without errors

### What do you see instead?

`Helm upgrade failed: template: minio/templates/ingress.yaml:48:42: executing "minio/templates/ingress.yaml" at <include "common.ingress.certManagerRequest" (dict "annotations" $annotations)>: error calling include: template: minio/charts/common/templates/_ingress.tpl:70:17: executing "common.ingress.certManagerRequest" at <.annotations>: wrong type for value; expected map[string]interface {}; got string`

### Additional information

Chart version 12.8.4 works fine with the same values set.
