### ISSUE TITLE
kubernetes-event-exporter stops posting new events

### ISSUE THREAD

**Issue by dmitry-mightydevops** [bitnami/charts#19406]
### Name and Version

bitnami/kubernetes-event-exporter:2.6.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. aws eks 1.27
2. image
```console
$ k ice image                                                                                                                                
PODNAME                                    CONTAINER       PULL          IMAGE                                        TAG
kubernetes-event-exporter-c75986578-9ld8c  event-exporter  IfNotPresent  docker.io/bitnami/kubernetes-event-exporter  1.4.0-debian-11-r14
```
3. installed via HELM chart

```yaml
source:
  repoURL: 'https://charts.bitnami.com/bitnami'
  targetRevision: 2.6.0
```

**values:**

```yaml
tolerations:
  null

affinity:
  null

nodeSelector:
  ops: "true"

resources:
  limits:
    cpu: 500m
    memory: 250Mi
  requests:
    cpu: 100m
    memory: 100Mi

commonLabels:
  app: "kubernetes-event-exporter"

# ? if you get throttling errors
# ? https://github.com/resmoio/kubernetes-event-exporter/issues/27
config:
  logLevel: error
  logFormat: json
  kubeQPS: 60
  kubeBurst: 60
  receivers:
    - name: "dump"
      file:
        path: "/dev/stdout"
        layout:
          message: "{{ .Message }}"
          reason: "{{ .Reason }}"
          type: "{{ .Type }}"
          count: "{{ .Count }}"
          kind: "{{ .InvolvedObject.Kind }}"
          name: "{{ .InvolvedObject.Name }}"
          namespace: "{{ .Namespace }}"
          component: "{{ .Source.Component }}"
          host: "{{ .Source.Host }}"
```

4. Eventually it stops posting new  events

```console
$ klo -l app.kubernetes.io/component=kubernetes-event-exporter
{"component":"kubelet","count":"1","host":"ip-xx-yyy-ww-zz.us-west-2.compute.internal","kind":"Pod","message":"Container image \"11111111111.dkr.ecr.us-west-2.amazonaws.com/project/backend/backend-legacy/dev:dev-aaba723\" already present on machine","name":"project-legacy-portal-schedule-v1-28246989-vf5h2","namespace":"project","reason":"Pulled","type":"Normal"}
{"component":"kubelet","count":"1","host":"ip-xx-yyy-ww-zz.us-west-2.compute.internal","kind":"Pod","message":"Started container backend","name":"project-portal-schedule-v1-28246989-smfcp","namespace":"project","reason":"Started","type":"Normal"}
{"component":"kubelet","count":"1","host":"ip-xx-yyy-ww-zz.us-west-2.compute.internal","kind":"Pod","message":"Created container backend","name":"project-legacy-portal-schedule-v1-28246989-vf5h2","namespace":"project","reason":"Created","type":"Normal"}
{"component":"kubelet","count":"1","host":"ip-xx-yyy-ww-zz.us-west-2.compute.internal","kind":"Pod","message":"Container image \"11111111111.dkr.ecr.us-west-2.amazonaws.com/project/backend:dev-665b31e\" already present on machine","name":"project-backend-schedule-v1-28246989-glrf6","namespace":"project","reason":"Pulled","type":"Normal"}
{"component":"kubelet","count":"1","host":"ip-xx-yyy-ww-zz.us-west-2.compute.internal","kind":"Pod","message":"Started container backend","name":"project-legacy-portal-schedule-v1-28246989-vf5h2","namespace":"project","reason":"Started","type":"Normal"}
{"component":"kubelet","count":"1","host":"ip-xx-yyy-ww-zz.us-west-2.compute.internal","kind":"Pod","message":"Created container backend","name":"project-backend-schedule-v1-28246989-glrf6","namespace":"project","reason":"Created","type":"Normal"}
{"component":"kubelet","count":"1","host":"ip-xx-yyy-ww-zz.us-west-2.compute.internal","kind":"Pod","message":"Started container backend","name":"project-backend-schedule-v1-28246989-glrf6","namespace":"project","reason":"Started","type":"Normal"}
{"component":"job-controller","count":"1","host":"","kind":"Job","message":"Job completed","name":"project-legacy-portal-schedule-v1-28246989","namespace":"project","reason":"Completed","type":"Normal"}
{"component":"job-controller","count":"1","host":"","kind":"Job","message":"Job completed","name":"project-schedule-min-v1-28246989","namespace":"project","reason":"Completed","type":"Normal"}
{"component":"job-controller","count":"1","host":"","kind":"Job","message":"Job completed","name":"project-portal-schedule-v1-28246989","namespace":"project","reason":"Completed","type":"Normal"}
```

starting new Pod:

```console
$ k run --image nixery.dev/shell/bash/curl utils --overrides='{"apiVersion": "v1", "spec": {"nodeSelector": { "ops": "true"}}}' -- sleep 3000
pod/utils created

```

### and see no new events in the console output.

When I restart the deployment - I start getting new events again.

Any ideas?

### What is the expected behavior?

events continue to be posted in the console output of the pod

### What do you see instead?

events are not being posted after some time. Around several days.

**Comment by aoterolorenzo** [comment]
Hi @dmitry-mightydevops ,

Could you check the output log once set `.Values.image.debug=true`?

**Comment by dmitry-mightydevops** [comment]
We have added the configuration and are waiting for the POD to stop posting events. Pls reopen the ticket.

**Comment by dmitry-mightydevops** [comment]
@Mauraza
- the logs show no errors or anything that is suspicious. It just stops adding new data to stdout and that's it. 
- we collect logs with loki/promtail and have alarm setup when no new events happen over 24h, which is not possible in our clusters - as they're heavily used. 
- we have to restart pods and events are getting logged again

We don't have any probes:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  labels:
    app: kubernetes-event-exporter
    app.kubernetes.io/component: kubernetes-event-exporter
    app.kubernetes.io/instance: kubernetes-event-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-event-exporter
    argocd.argoproj.io/instance: kubernetes-event-exporter
    helm.sh/chart: kubernetes-event-exporter-2.6.0
  name: kubernetes-event-exporter
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: kubernetes-event-exporter
      app.kubernetes.io/name: kubernetes-event-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: a93357f8d683502990c3fb3b5f115eaaa8a9f0bdd51bac54047926b182c4c470
      creationTimestamp: null
      labels:
        app: kubernetes-event-exporter
        app.kubernetes.io/component: kubernetes-event-exporter
        app.kubernetes.io/instance: kubernetes-event-exporter
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kubernetes-event-exporter
        helm.sh/chart: kubernetes-event-exporter-2.6.0
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: kubernetes-event-exporter
                  app.kubernetes.io/instance: kubernetes-event-exporter
                  app.kubernetes.io/name: kubernetes-event-exporter
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - args:
        - -conf=/data/config.yaml
        image: docker.io/bitnami/kubernetes-event-exporter:1.4.0-debian-11-r14
        imagePullPolicy: IfNotPresent
        name: event-exporter
        ports:
        - containerPort: 2112
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: cfg
      dnsPolicy: ClusterFirst
      nodeSelector:
        ops: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      serviceAccount: kubernetes-event-exporter
      serviceAccountName: kubernetes-event-exporter
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: kubernetes-event-exporter
        name: cfg

```
