### ISSUE TITLE
helm template fails for umbrella chart having different sub-chart common dependencies

### ISSUE THREAD

**Issue by msadiq058** [bitnami/charts#19417]
### Name and Version

bitnami/mongodb 10.6.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create Chart.yaml with this config
```yaml
apiVersion: v2
appVersion: 1.0.0
dependencies:
- name: mongodb
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  version: 10.6.0
- name: redis
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  version: 18.0.4
description: A Helm Chart for Akridata Data Explorer
name: test-umbrella
type: application
version: 1.0.0
```
2. Run `helm dep build .`
3. Run `helm template .`

### What do you see instead?
```
Error: template: test-umbrella/charts/redis/templates/replicas/statefulset.yaml:12:14: executing "test-umbrella/charts/redis/templates/replicas/statefulset.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: test-umbrella/charts/mongodb/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: test-umbrella/charts/mongodb/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```
### Additional information

Redis chart have dependency on
```yaml 
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
 ```
 And rabbitmq has dependency
```yaml
 dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 1.3.7
```
Is there a way to make it working?

**Comment by kingjan1999** [comment]
I can reproduce this with Redis + MariaDB:

```
[ERROR] templates/: template: kiv/charts/redis/templates/replicas/statefulset.yaml:12:14: executing "kiv/charts/redis/templates/replicas/statefulset.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: kiv/charts/mariadb/charts/common/templates/_labels.tpl:11:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: kiv/charts/mariadb/charts/common/templates/_names.tpl:11:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```

This only affects the redis chart from version 17.16.0. Using redis 17.15.6 works fine. So apparently https://github.com/bitnami/charts/commit/e3c23350ca2a96918c40265674cb53e58ff42183 introduced a regression of some kind

**Comment by andresbono** [comment]
Hi, it seems to be some sort of incompatibility due to having 2 charts depending on different common subcharts...

For example, in the shared `Chart.yaml` file:

- mongodb@10.6.0 depends on common@1.3.7
- redis@18.0.4 depends on common@2.10.0

If you bump the mongodb version to, for instance, mongodb@13.17.0. The issue is gone, right?

- mongodb@13.17.0 depends on common@2.9.0

Is there any reason to not use more recent versions of the charts?

**Comment by sbor23** [comment]
Same issue here, in my case upgrading `postgresql` from `12.8` to `12.9` from 23 Aug, 2023 increases `common 2.8.0 -> 2.9.0` https://github.com/bitnami/charts/pull/18408

while having `mongodb 13.15.5` from 15 Jul, 2023 with `common 2.6.0`.

```yaml
dependencies:
- name: dagster
  repository: https://dagster-io.github.io/helm
  version: 1.3.14
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 13.0.0
- name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 13.15.5
digest: sha256:9d10fb0bad5375f5d1044ed7a5158768aef96155746b4eb950503c4b2b258219
generated: "2023-09-29T09:31:00.2900535+02:00"
```

```
$ helm lint -f values-lab.yaml 
coalesce.go:223: warning: destination for dagster.postgresql.ldap.tls is a table. Ignoring non-table value (false)
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: synertia-spc/charts/postgresql/templates/primary/svc.yaml:11:14: executing "synertia-spc/charts/postgresql/templates/primary/svc.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: synertia-spc/charts/mongodb/charts/common/templates/_labels.tpl:11:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: synertia-spc/charts/mongodb/charts/common/templates/_names.tpl:11:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name

Error: 1 chart(s) linted, 1 chart(s) failed
```

I wouldn't call one month difference an "old" version of a chart...

Could we maybe get mayor version bumps in `common` if there are breaking changes? And could that cause a mayor bump in the main chart as well?
Are there generally any rules one should follow for upgrading when multiple bitnami charts are used? I had no idea they influence each other, it feels a bit like a minefield to be honest...

**Comment by andresbono** [comment]
Hi, @msadiq058, @kingjan1999, @sbor23, this is in fact a duplicate of #19003.

This simple scenario illustrates the issue:

![image](https://github.com/bitnami/charts/assets/1057973/0516a368-ff94-4424-9f3e-919c3c31319f)

`$ ./helm-v3.13.0 template .`
```yaml
---
# Source: base/charts/a/templates/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "common-1-0.1.0"
spec:
  containers:
    - name: c
      image: bitnami/minideb
---
# Source: base/charts/b/templates/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "common-1-0.1.0"
spec:
  containers:
    - name: c
      image: bitnami/minideb
```

All the templates are rendered into a global namespace, this is how the Helm tool works. When the same template is declared multiple times, only one will be used. So please, update the dependencies in your "umbrella" chart so they are compatible.

Please, check these references for a better understanding of the issue:
- https://github.com/helm/helm/issues/8804#issuecomment-700733687
- https://github.com/helm/helm/issues/11561#issuecomment-1325411773
