### ISSUE TITLE
[bitnami/kafka] External advertised listeners nor as expected

### ISSUE THREAD

**Issue by luispabon** [bitnami/charts#19429]
### Name and Version

bitnami/kafka 25.1.10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Kube 1.27
2. Helm 3.11.2
3. Install the `bitnami/kafka` chart with the provided values

### Are you using any custom parameters or values?

Helm values:

(`dummy.domain` is resolvable from outside the cluster)

```yaml
  controller:
    replicaCount: 3
  listeners:
    client:
      protocol: PLAINTEXT
    external:
      protocol: PLAINTEXT
  externalAccess:
    enabled: true
    autoDiscovery:
      enabled: false
    controller:
      service:
        type: ClusterIP
        domain: dummy.domain
    broker:
      service:
        type: ClusterIP
        domain: dummy.domain
```

This generates:

```console
$ kubectl get all

NAME                     READY   STATUS    RESTARTS      AGE
pod/kafka-controller-0   2/2     Running   0             9m13s
pod/kafka-controller-1   2/2     Running   0             9m12s
pod/kafka-controller-2   2/2     Running   0             9m12s
pod/shell                1/1     Running   1 (16h ago)   16h

NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/kafka                         ClusterIP   172.17.80.192   <none>        9092/TCP,9095/TCP            9m13s
service/kafka-controller-0-external   ClusterIP   172.19.103.56   <none>        9094/TCP                     9m13s
service/kafka-controller-1-external   ClusterIP   172.18.42.143   <none>        9094/TCP                     9m13s
service/kafka-controller-2-external   ClusterIP   172.17.185.16   <none>        9094/TCP                     9m13s
service/kafka-controller-headless     ClusterIP   None            <none>        9094/TCP,9092/TCP,9093/TCP   9m13s

NAME                                READY   AGE
statefulset.apps/kafka-controller   3/3     9m13s
```

### What is the expected behavior?

I expect the advertised external listener to conform to `EXTERNAL_SVC_NAME.domain` and also use the service's port, like so:
```console
$ kcat -v -L -b kafka-controller-0-external.dummy.domain:9094
Metadata for all topics (from broker -1: kafka-controller-0-external.dummy.domain:9094/bootstrap):
 3 brokers:
  broker 0 at kafka-controller-0-external.dummy.domain:9094
  broker 1 at kafka-controller-1-external.dummy.domain:9094
  broker 2 at kafka-controller-2-external.dummy.domain:9094 (controller)
```

### What do you see instead?

Instead each broker is advertising just the domain name we provided and the wrong port:

```console
$ kcat -v -L -b kafka-controller-0-external.dummy.domain:9094
Metadata for all topics (from broker -1: kafka-controller-0-external.dummy.domain:9094/bootstrap):
 3 brokers:
  broker 0 at dummy.domain:9094
  broker 1 at dummy.domain:9095
  broker 2 at dummy.domain:9096 (controller)
```

### Additional information

For cost-saving we also have a single AWS ALB wired into an nginx reverse proxy using a`LoadBalancer` service, instead of letting the helm chart create `LoadBalancer` services as they are expensive. On the reverse proxy, we simply use a stream block to wire up the external hostname with the external service. This shouldn't have any bearing though to the advertised brokers.
