### ISSUE TITLE
[bitnami/harbor] trivy: failed to ping scanner

### ISSUE THREAD

**Issue by lusu007** [bitnami/charts#19439]
### Name and Version

bitnami/harbor  18.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy the Harbor Helm chart

### Are you using any custom parameters or values?

```yaml
harbor:
  adminPassword: redacted
  externalURL: redacted
  exposureType: ingress
  global:
    storageClass: redacted
  persistence:
    imageChartStorage:
      type: s3
      s3:
        region: "redacted"
        bucket: "redacted"
        accesskey: redacted
        secretkey: redacted
        regionendpoint: "redacted"
        secure: true
        v4auth: true
  core:
    secretKey: redacted
    secret: redacted
    csrfKey: redacted
    tokenCert: redacted
    tokenKey: redacted
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      capabilities:
        drop: ["NET_RAW"]
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      runAsUser: 10001
  ingress:
    core:
      ingressClassName: nginx
      hostname: redacted
  portal:
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      capabilities:
        drop: ["NET_RAW"]
      allowPrivilegeEscalation: false
      runAsUser: 10001
    extraEnvVars:
      - name: NGINX_SKIP_SAMPLE_CERTS
        value: "true"
  jobservice:
    secret: redacted
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 25m
        memory: 50Mi
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      capabilities:
        drop: ["NET_RAW"]
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsUser: 10001
  registry:
    secret: redacted
    credentials:
      username: redacted
      password: redacted
      htpasswd: redacted
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
    server:
      containerSecurityContext:
        capabilities:
          drop: ["NET_RAW"]
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsUser: 10001
    controller:
      containerSecurityContext:
        capabilities:
          drop: ["NET_RAW"]
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsUser: 10001
  trivy:
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      capabilities:
        drop: ["NET_RAW"]
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      runAsUser: 10001
  postgresql:
    primary:
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        capabilities:
          drop: ["NET_RAW"]
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 10001
  redis:
    master:
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        capabilities:
          drop: ["NET_RAW"]
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 10001

```

### What is the expected behavior?

Harbor should connect to Trivy and the connection should be healthy.

### What do you see instead?

Harbor shows Trivy as unhealthy in the Web  UI. After some debugging I found that the `/probe/healthy`  endpoint responds as expected but the `/api/v1/metadata` endpoint of Trivy times out.

**Comment by javsalgar** [comment]
Hi!

Does the issue happen when using the default values?

**Comment by lusu007** [comment]
No, it does not. I tried removing `podSecurityContext`  and `containerSecurityContext` but that didn't change anything. 

I also have two network policies in my Harbor namespace. Are they maybe the problem?
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: harbor
  namespace: {{ .Release.Namespace }}
spec:
  # match all pods in the namespace
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # allow ingress from all pods in the namespace
    - from:
        - podSelector: {}
  egress:
    # allow egress to all pods in the namespace
    - to:
        - podSelector: {}
    # allow DNS traffic
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name:
                kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
    # allow egress to the public internet (for OIDC login, proxy cache, CVE scan, etc.)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            # https://en.wikipedia.org/wiki/Private_network#Private_IPv4_addresses
            except:
              - 10.0.0.0/8
              - 192.168.0.0/16
              - 172.16.0.0/12
              
---              

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: harbor-ingress
  namespace: {{ .Release.Namespace }}
spec:
  # match the "core" and "portal" components to expose their HTTP ports to the ingress controller
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values: ["core", "portal"]
  policyTypes:
    - Ingress
  ingress:
    # allow ingress from the ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080         
```

I still think it's an issue with the Trivy container since the Trivy endpoint is not responding.
