### ISSUE TITLE
git-sync sidecar container not work

### ISSUE THREAD

**Issue by jackchuong** [bitnami/charts#19445]
### Name and Version

bitnami/spark-7.2.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi all,
I want to create a git-sync sidecar container in spark master pod , it will sync data from my private git repo periodical (60s) using SSH.
Here my chart values:
```yaml
master:
  extraVolumes:
    - name: sparks-job-pv
      emptyDir: {}
    - name: ssh-key
      secret:
        defaultMode: 256
        secretName: spark-ssh-git-secret
  extraVolumeMounts:
    - name: sparks-job-pv
      mountPath: /opt/sparks-job
  sidecars:
    - name: git-sync-sparks-job
      image: k8s.gcr.io/git-sync:v3.1.5
      env:
        - name: GIT_SYNC_REPO
          value: "git@gitlab.mydomain.com:ebis1/sparks-job.git" ##repo-path-you-want-to-clone
        - name: GIT_SYNC_BRANCH
          value: "main" ##repo-branch
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_SYNC_ROOT
          value: /data
        - name: GIT_SYNC_DEST
          value: "sparks-job" ##path-where-you-want-to-clone
        - name: GIT_SYNC_ONE_TIME
          value: "false"
        - name: GIT_SYNC_PERIOD
          value: "60"
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: ssh-key
          mountPath: "/etc/git-secret"
        - name: sparks-job-pv
          mountPath: /data
```
I created a secret contain ssh key
```console
$ kubectl -n ebis describe secret/spark-ssh-git-secret
Name:         spark-ssh-git-secret
Namespace:    ebis
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
known_hosts:  674 bytes
ssh:          2622 bytes
```
User can use this ssh key to push/pull git repo already.

### What is the expected behavior?

Pod Spark master ready 2/2 and running

### What do you see instead?

Pod Spark master not ready 1/2 and CrashLoopBackOff
```console
$ kubectl -n ebis get pod
pod/spark-master-0                          1/2     CrashLoopBackOff   2 (18s ago)   43s

$ kubectl -n ebis describe pod spark-master-0
Name:             spark-master-0
Namespace:        ebis
Priority:         0
Service Account:  spark
Node:             k3s-dc-worker1/192.168.0.201
Start Time:       Thu, 21 Sep 2023 13:29:45 +0700
Labels:           app.kubernetes.io/component=master
                  app.kubernetes.io/instance=spark
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=spark
                  controller-revision-hash=spark-master-686777bc98
                  helm.sh/chart=spark-7.2.1
                  statefulset.kubernetes.io/pod-name=spark-master-0
Annotations:      <none>
Status:           Running
IP:               10.42.1.23
IPs:
  IP:           10.42.1.23
Controlled By:  StatefulSet/spark-master
Containers:
  spark-master:
    Container ID:   containerd://29c9d50665a8422ac8343721fabc25c328c7391c20d5595c49fc256407d84daf
    Image:          docker.io/bitnami/spark:3.4.1-debian-11-r0
    Image ID:       docker.io/bitnami/spark@sha256:b09846b988dba82090b53455b33d557ef21923b13cab54e6029d87f604898b26
    Ports:          8080/TCP, 7077/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Thu, 21 Sep 2023 13:29:46 +0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  4Gi
    Requests:
      cpu:      2
      memory:   4Gi
    Liveness:   http-get http://:8080/ delay=180s timeout=5s period=20s #success=1 #failure=6
    Readiness:  http-get http://:8080/ delay=30s timeout=5s period=10s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:            false
      SPARK_MODE:               master
      SPARK_DAEMON_MEMORY:
      SPARK_MASTER_PORT:        7077
      SPARK_MASTER_WEBUI_PORT:  8080
    Mounts:
      /mnt/certs from cert (ro)
      /opt/jars from ebis-pv (rw)
      /opt/sparks-job from sparks-job-pv (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9g7d5 (ro)
  git-sync-sparks-job:
    Container ID:   containerd://08473509b094b0a4dffaed2e2266b57ae1b6dfff9e664c69104ed2269f064b48
    Image:          k8s.gcr.io/git-sync:v3.1.5
    Image ID:       k8s.gcr.io/git-sync@sha256:f38673f25b8e6a27b3518a34c304c9c3b10b9fc18b917c9e2b5f8f63c4da7cc6
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 21 Sep 2023 13:30:31 +0700
      Finished:     Thu, 21 Sep 2023 13:30:31 +0700
    Ready:          False
    Restart Count:  3
    Environment:
      GIT_SYNC_REPO:      git@gitlab.mydomain.com:ebis1/sparks-job.git
      GIT_SYNC_BRANCH:    main
      GIT_SYNC_SSH:       true
      GIT_SYNC_ROOT:      /data
      GIT_SYNC_DEST:      sparks-job
      GIT_SYNC_ONE_TIME:  false
      GIT_SYNC_PERIOD:    60
    Mounts:
      /data from sparks-job-pv (rw)
      /etc/git-secret from ssh-key (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9g7d5 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  ebis-pv:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  ebis-pvc
    ReadOnly:   false
  cert:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            secrets-store.csi.k8s.io
    FSType:
    ReadOnly:          true
    VolumeAttributes:      secretProviderClass=cert-spc
  sparks-job-pv:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  ssh-key:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  spark-ssh-git-secret
    Optional:    false
  kube-api-access-9g7d5:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  66s                default-scheduler  Successfully assigned ebis/spark-master-0 to k3s-dc-worker1
  Normal   Pulled     66s                kubelet            Container image "docker.io/bitnami/spark:3.4.1-debian-11-r0" already present on machine
  Normal   Created    66s                kubelet            Created container spark-master
  Normal   Started    66s                kubelet            Started container spark-master
  Normal   Pulled     21s (x4 over 66s)  kubelet            Container image "k8s.gcr.io/git-sync:v3.1.5" already present on machine
  Normal   Created    21s (x4 over 65s)  kubelet            Created container git-sync-sparks-job
  Normal   Started    21s (x4 over 65s)  kubelet            Started container git-sync-sparks-job
  Warning  BackOff    5s (x6 over 63s)   kubelet            Back-off restarting failed container git-sync-sparks-job in pod spark-master-0_ebis(7f2a2716-a357-4045-9bb0-3c5c1a693631)

$ kubectl -n ebis logs -f -c git-sync-sparks-job spark-master-0
INFO: detected pid 1, running init handler
I0921 06:36:51.378406      13 main.go:322]  "level"=0 "msg"="starting up"  "args"=["/git-sync"]
I0921 06:36:51.378519      13 main.go:575]  "level"=0 "msg"="cloning repo"  "origin"="git@gitlab.mydomain.com:ebis1/sparks-job.git" "path"="/data"
E0921 06:36:51.504122      13 main.go:348]  "msg"="failed to sync repo, aborting" "error"="error running command: exit status 128: \"Cloning into '/data'...\\nfatal: Could not read from remote repository.\\n\\nPlease make sure you have the correct access rights\\nand the repository exists.\\n\""
```

### Additional information
Meanwhile, this test.yaml works fine
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ebis
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-helloworld
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: www-data
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.1.5
        volumeMounts:
        - name: www-data
          mountPath: /data
        - name: git-secret
          mountPath: "/etc/git-secret"
        env:
        - name: GIT_SYNC_REPO
          value: "git@gitlab.mydomain.com:ebis1/sparks-job.git" ##repo-path-you-want-to-clone
        - name: GIT_SYNC_BRANCH
          value: "main" ##repo-branch
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_SYNC_ROOT
          value: /data
        - name: GIT_SYNC_DEST
          value:  "sparks-job" ##path-where-you-want-to-clone
        - name: GIT_SYNC_ONE_TIME
          value: "false"
        - name: GIT_SYNC_PERIOD
          value: "60"
        securityContext:
          runAsUser: 0
      volumes:
      - name: www-data
        emptyDir: {}
      - name: git-secret
        secret:
          defaultMode: 256
          secretName: spark-ssh-git-secret # your-ssh-key
```
container `git-sync` can sync data from git repo each 60s and I can see data in container `nginx-helloworld` at /usr/share/nginx/html , pod `nginx-deployment` running without error
```console
$ kubectl -n ebis get pod
nginx-deployment-7f8ccf868b-8dvbm       2/2     Running       0          94s
```
