### ISSUE TITLE
[bitnami/appsmith] clobbering of helm chart values for external mongodb/redis

### ISSUE THREAD

**Issue by jliedy** [bitnami/charts#19474]
### Name and Version

bitnami/appsmith 1.0.4

### What architecture are you using?

AMD64

### What steps will reproduce the bug?

The hosting platform is Red Hat OpenShift for AWS (ROSA) v4.12.30.  Due to default uid/gid constraints in ROSA and a bug in Helm that prevents "nulling" values in subcharts (I've even tried with the latest dev build of Helm), I've deployed unique MongoDB and Redis apps to the ROSA cluster instead of using the built-in subchart deploys in Appsmith.  As such, I've configured the deployment values to utilize the external apps to the following:

```yaml
mongodb:
  enabled: false
externalDatabase:
  hosts:
  - "appsmith-mongodb-0.appsmith-mongodb-headless"
  - "appsmith-mongodb-1.appsmith-mongodb-headless"
  username: placeholder
  existingSecret: "appsmith-mongodb"
  existingSecretPasswordKey: "mongodb-passwords"
redis:
  enabled: false
externalRedis:
  host: "appsmith-redis-headless"
  existingSecret: "appsmith-redis"
  existingSecretPasswordKey: "redis-password"
```

Upon installing/upgrading the helm chart, the backend deployment piece of the app fails to start due to the deployed yaml for appsmith-backend showing as: `spec.template.spec.containers.env` having the following config:
```yaml
            - name: APPSMITH_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: appsmith-mongodb
                  key: redis-password
```
So it looks like `externalRedis.existingSecret` is not being properly processed in the install/upgrade.

### Are you using any custom parameters or values?

```yaml
global:
  storageClass: "gp3-csi"
client:
  podSecurityContext:
    fsGroup: null
  containerSecurityContext:
    runAsUser: null
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostname: placeholder.com
    tls: true
    extraTls:
    - hosts:
        - placeholder.com
      secretName: placeholder
backend:
  adminUser: placeholder@placeholder.com
  adminEmail: placeholder@placeholder.com
  podSecurityContext:
    fsGroup: null
  containerSecurityContext:
    runAsUser: null
  persistence:
    storageClass: "gp3-csi"
    size: 10Gi
  extraEnvVars:
    - name: APPSMITH_OAUTH2_GOOGLE_CLIENT_ID
      value: "placeholder"
    - name: APPSMITH_OAUTH2_GOOGLE_CLIENT_SECRET
      value: "placeholder"
    - name: APPSMITH_SIGNUP_ALLOWED_DOMAINS
      value: "placeholder.com"
    - name: APPSMITH_GIT_ROOT
      value: "/bitnami/appsmith/git-data"
rts:
  podSecurityContext:
    fsGroup: null
  containerSecurityContext:
    runAsUser: null
mongodb:
  enabled: false
externalDatabase:
  hosts:
  - "appsmith-mongodb-0.appsmith-mongodb-headless"
  - "appsmith-mongodb-1.appsmith-mongodb-headless"
  username: placeholder
  existingSecret: "appsmith-mongodb"
  existingSecretPasswordKey: "mongodb-passwords"
redis:
  enabled: false
externalRedis:
  host: "appsmith-redis-headless"
  existingSecret: "appsmith-redis"
  existingSecretPasswordKey: "redis-password"
```

### What is the expected behavior?

The deployment at: `spec.template.spec.containers.env` should output the following config:
```yaml
            - name: APPSMITH_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: appsmith-redis
                  key: redis-password
```

**Comment by jliedy** [comment]
If you wanna do a quickie MongoDB and Redis deployment to test this against, here's my value files for each:

MongoDB chart at bitnami/mongodb:
```yaml
global:
  storageClass: "gp3-csi"
architecture: "replicaset"
auth:
  rootUser: rootPlaceholder
  usernames:
  - "placeholder"
  databases:
  - "appsmith"
podSecurityContext:
  fsGroup: null
containerSecurityContext:
  runAsUser: null
  runAsGroup: null
service:
  portName: appsmith-mongodb
persistence:
  storageClass: "gp3-csi"
arbiter:
  enabled: false
```

Redis chart at bitnami/redis:
```yaml
architecture: standalone
master:
  podSecurityContext:
    fsGroup: null
  containerSecurityContext:
    runAsUser: null
    runAsGroup: null
  persistence:
    storageClass: "gp3-csi"
```

Nulled values are to support the default "randomized" uid/gid requirements when running as nonroot in ROSA.
