### ISSUE TITLE
Apache pod / prometheus metrics side car does not honor namespace setting in chart

### ISSUE THREAD

**Issue by ctc-longr** [bitnami/charts#19483]
### Name and Version

bitnami/apache *

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Enable metrics side-car
2. Enable serviceMonitor
3. set "namespace:" on the serviceMonitor to 'monitoring'
4. Attempt to deploy objects to kubernetes
5. Prometheus operator on the cluster does not pickup this object (administered by another department).
6. Notice that the namespace on the 'serviceMonitor' object created is actually still in the default release namespace and not in "monitoring" where assigned. 

### Are you using any custom parameters or values?
```yaml
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
        interval: 10s
```
### What is the expected behavior?
```yaml
name:
  web-proxy-apache
namespace:
  monitoring
```
### What do you see instead?
```yaml
name:
  web-proxy-apache
namespace:
  web-proxy-dev
```
### Additional information

The namespace portion of the template is here: https://github.com/bitnami/charts/blob/main/bitnami/apache/templates/servicemonitor.yaml#L11

does not contain any "if user provided a value in Values.metrics.serviceMonitor.namespace then use that, otherwise use this default" logic. It just sets the release. 

Meanwhile, the documentation exposes this as a setting and suggests it should be configurable: 
https://github.com/bitnami/charts/blob/main/bitnami/apache/values.yaml#L656
https://github.com/bitnami/charts/tree/main/bitnami/apache/#installing-the-chart
