### ISSUE TITLE
I just want to use mils between producer client and schema-registry, and use external kafka.but i can only find out mtls about kafka brokers, no mtls about message producer client and schema-registry document was found using clientAuthentication

### ISSUE THREAD

**Issue by mingmingshiliyu** [bitnami/charts#19493]
### Name and Version

bitnami/schema-registry

### What architecture are you using?

None

### What steps will reproduce the bug?

using `clientAuthentication` with REQUIRED and secret with jks certs.there is no workable solution to make mtls between schema-registry and producer client

### What is the expected behavior?

``` yaml
auth:
  ## TLS parameters to be used when a listener uses HTTPS
  ##
  tls:
    ## @param auth.tls.enabled Enable TLS configuration to provide to be used when a listener uses HTTPS
    ##
    enabled: true
    ## @param auth.tls.jksSecret Existing secret containing the truststore and one keystore per Schema Registry replica
    ##
    ## Create this secret following the steps below:
    ## 1) Generate your trustore and keystore files. Helpful script: https://raw.githubusercontent.com/confluentinc/confluent-platform-security-tools/master/kafka-generate-ssl.sh
    ## 2) Rename your truststore to `schema-registry.truststore.jks`.
    ## 3) Rename your keystores to `schema-registry-X.keystore.jks` where X is the ID of each Schema Registry replica
    ## 4) Run the command below where SECRET_NAME is the name of the secret you want to create:
    ##       kubectl create secret generic SECRET_NAME --from-file=./schema-registry.truststore.jks --from-file=./schema-registry-0.keystore.jks --from-file=./schema-registry-1.keystore.jks ...
    ##
    jksSecret: "schema-registry-test"
    ## @param auth.tls.keystorePassword Password to access the keystore when it's password-protected
    ##
    keystorePassword: "password"
    ## @param auth.tls.truststorePassword Password to access the truststore when it's password-protected
    ##
    truststorePassword: "password"
    ## @param auth.tls.clientAuthentication Client authentication configuration.
    ## Valid options: NONE, REQUESTED, over REQUIRED
    ##
    clientAuthentication: REQUESTED
  ## Parameters to configure authentication with kafka brokers
  ##
  kafka:
    ## @param auth.kafka.jksSecret Existing secret containing the truststore and one keystore per Schema Registry replica
    ##
    ## Create this secret following the steps below:
    ## 1) Generate your trustore and keystore files. Helpful script: https://raw.githubusercontent.com/confluentinc/confluent-platform-security-tools/master/kafka-generate-ssl.sh
    ## 2) Rename your truststore to `kafka.truststore.jks`.
    ## 3) Rename your keystores to `kafka-X.keystore.jks` where X is the ID of each Schema Registry replica
    ## 4) Run the command below where SECRET_NAME is the name of the secret you want to create:
    ##       kubectl create secret generic SECRET_NAME --from-file=./kafka.truststore.jks --from-file=./kafka-0.keystore.jks --from-file=./kafka-1.keystore.jks ...
    ##
    jksSecret: ""
    ## @param auth.kafka.tlsEndpointIdentificationAlgorithm The endpoint identification algorithm used validate brokers hostnames
    ## Disable server hostname verification by setting it to an empty string
    ## See: https://docs.confluent.io/current/kafka/authentication_ssl.html#optional-settings
    ##
    tlsEndpointIdentificationAlgorithm: https
    ## @param auth.kafka.keystorePassword Password to access the keystore when it's password-protected
    ##
    keystorePassword: ""
    ## @param auth.kafka.truststorePassword Password to access the truststore when it's password-protected
    ##
    truststorePassword: ""
    ## @param auth.kafka.saslMechanism Mechanism that schema registry will use to connect to kafka. Allowed: PLAIN, SCRAM-SHA-256, SCRAM-SHA-512
    ##
    saslMechanism: SCRAM-SHA-256


## @section Schema Registry statefulset parameters
## @param replicaCount Number of Schema Registry replicas to deploy.
##
replicaCount: 3
kafka:
  listeners:
    client:
      protocol: "SSL"

##
## External Kafka Configuration
## All of these values are only used when kafka.enabled is set to false
##
externalKafka:
  ## @param externalKafka.brokers Array of Kafka brokers to connect to. Format: protocol://broker_hostname:port
  ##
  brokers:
    - PLAINTEXT://kafka3:9093
    - PLAINTEXT://kafka2:9093
    - PLAINTEXT://kafka1:9093
  ## @param externalKafka.listener.protocol Kafka listener protocol. Allowed protocols: PLAINTEXT, SASL_PLAINTEXT, SASL_SSL and SSL
  ##
  listener:
    protocol: SSL
  ## Authentication parameters
  ## @param externalKafka.sasl.user User for SASL authentication
  ## @param externalKafka.sasl.password Password for SASL authentication
  ## @param externalKafka.sasl.existingSecret Name of the existing secret containing a password for SASL authentication (under the key named "client-passwords")
  ##
  sasl:
    user: "test"
    password: "test"
    existingSecret: "schema-registry-test"

```

### What do you see instead?

the configuration about tis certs location is empty
