### ISSUE TITLE
Schema-Registry in empty

### ISSUE THREAD

**Issue by vyom-soft** [bitnami/charts#19579]
### Name and Version

bitnami/schema-registry 14.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I installed the helm chart schema-registry version 14-0.0 appVersion 7.4.1,
The schema is empty, nothing is shown.

- I see this issue https://stackoverflow.com/questions/76157961/how-to-install-confluent-schema-registry-using-bitnami-helm-chart-for-external-k

What else should be configured so that the schema show some data. The kafka cluster connection is there message are also send.

Thank you, 

### Are you using any custom parameters or values?

```yaml
kafka:
  ## @param kafka.enabled Enable/disable Kafka chart installation
  ##
  enabled: false
  ## @param kafka.controller.replicaCount Number of Kafka controller-eligible (controller+broker) nodes
  ##
  broker:
    replicaCount: 0
  kraft:
    enabled: false
  controller:
    replicaCount: 1
  ## @param kafka.listeners.client.protocol Authentication protocol for communications with clients. Allowed protocols: `PLAINTEXT`, `SASL_PLAINTEXT`, `SASL_SSL`, `SSL`
  ##
  listeners:
    client:
      protocol: "PLAINTEXT"
  ## @param kafka.service.ports.client Kafka svc port for client connections
  ##
  service:
    ports:
      client: 9092
  ## @param kafka.extraConfig Additional configuration to be appended at the end of the generated Kafka configuration file.
  ##
  extraConfig: |-
    offsets.topic.replication.factor=1
  ## @param kafka.sasl.client.users Comma-separated list of usernames for Kafka client listener when SASL is enabled
  ## @param kafka.sasl.client.passwords Comma-separated list of passwords for client listener when SASL is enabled, must match the number of client.users
  ##
  sasl:
    client:
      users:
        - user
      passwords: ""
##
## External Kafka Configuration
## All of these values are only used when kafka.enabled is set to false
##
externalKafka:
  ## @param externalKafka.brokers Array of Kafka brokers to connect to. Format: protocol://broker_hostname:port
  ##
  brokers:
    - PLAINTEXT://kvib-kafka-cluster-kafka-bootstrap.kvib-dev:9092

  ## @param externalKafka.listener.protocol Kafka listener protocol. Allowed protocols: PLAINTEXT, SASL_PLAINTEXT, SASL_SSL and SSL
  ##
  listener:
    protocol: PLAINTEXT
```

### What do you see instead?

nothing

### Additional information

I am using strimzi-kafka 
logs: 
[schema-registry.txt](https://github.com/bitnami/charts/files/12740900/schema-registry.txt)
