### ISSUE TITLE
[bitnami/rabbitmq] expose metrics/detailed endpoint to prometheus for scraping

### ISSUE THREAD

**Issue by basit9958** [bitnami/charts#19592]
### Name and Version

bitnami/rabbitmq-cluster-operator 3.8.0

### What is the problem this feature will solve?

Exposing the `detailed` metric endpoint to prometheus for scraping.

### What is the feature you are proposing to solve the problem?

It would be great to enable not just /metrics as exposed metric and scraped via ServiceMonitor but to also add `detailed` scraping to that option.
More about this here; https://www.rabbitmq.com/prometheus.html#detailed-endpoint

**Comment by basit9958** [comment]
we could enable this by adding this in servicemonitor for rabbitmq-operator
```
    - port: metrics
    - interval: {{ .Values.clusterOperator.metrics.serviceMonitor.interval }}
      params:
          family: {{- range $family := .Values.clusterOperator.metrics.serviceMonitor.params.family}}
            - {{ $family }}
          {{- end }}
      path: /metrics/detailed
  ```
  
  and values could be changed to 
  ```
        ## @param clusterOperator.metrics.serviceMonitor.params.family specify family parameter to scrape metrics
      ## E.g.
      ## family:
      ##   - queue_coarse_metrics
      ##   - queue_consumer_count
      ##
      params:
        family:
 ```
