### ISSUE TITLE
[bitnami/kube-prometheus] spec.storage.volumeClaimTemplate.metadata: Invalid value: "null"

### ISSUE THREAD

**Issue by lusu007** [bitnami/charts#19693]
### Name and Version

bitnami/kube-prometheus 8.23.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install `kube-prometheus` with the given `values.yaml` below

### Are you using any custom parameters or values?

```yaml
prometheus:
  persistence:
    enabled: true
    storageClass: csi-cinder-classic-retain
    size: 4Gi
alertmanager:
  persistence:
    enabled: true
    storageClass: csi-cinder-classic-retain
    size: 4Gi
```

### What is the expected behavior?

`kube-prometheus` should be deployed as expected.

### What do you see instead?

The Helm chart installation fails the following error displayed in ArgoCD:

```
Alertmanager.monitoring.coreos.com "prometheus-operator-kube-p-alertmanager" is invalid: spec.storage.volumeClaimTemplate.metadata: Invalid value: "null": spec.storage.volumeClaimTemplate.metadata in body must be of type object: "null"
```
```
Prometheus.monitoring.coreos.com "prometheus-operator-kube-p-prometheus" is invalid: spec.storage.volumeClaimTemplate.metadata: Invalid value: "null": spec.storage.volumeClaimTemplate.metadata in body must be of type object: "null"
```

### Additional information

This problem arises specifically when both `.Values.prometheus.persistence.annotations` and `.Values.commonAnnotations` are not configured. To resolve this issue, a potential solution would involve implementing a validation step to check for the presence of annotations. The `metadata` should be applied only if these annotations are properly configured.
