### ISSUE TITLE
[bitnami/metallb] Remote state is encrypted and encryption is not configured

### ISSUE THREAD

**Issue by nabilbendafi** [bitnami/charts#19737]
### Name and Version

bitnami/metallb 4.7.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. `helm pull bitnami/metallb --version 4.7.3`
2. `tar xzvf metallb-4.7.3.tgz`
3. `cd metallb`
4. `helm template --release-name metallb --namespace metallb . | kubectl create -f -`
5. `stern -n metallb metallb-speaker`

### What is the expected behavior?

```yaml
        - name: METALLB_ML_SECRET_KEY_PATH
          value: "/etc/ml_secret_key"
...
        volumeMounts:
        - mountPath: /etc/ml_secret_key
          name: memberlist
          readOnly: true
...
      volumes:
      - name: memberlist 
        secret: 
          secretName: memberlist
```

### What do you see instead?

```yaml
        - name: METALLB_ML_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: metallb-memberlist
```

### Additional information

Since https://github.com/metallb/metallb/pull/1692, MetalLB 0.13.11 memberlist secret key relies on file volume mount and not env variable
