### ISSUE TITLE
Metrics-Server Chart Version: 6.5.3 not rendered properly

### ISSUE THREAD

**Issue by lmad4832** [bitnami/charts#19741]
### Name and Version

bitnami/metrics-server:6.5.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`helm install support . --dry-run` 

Chart yaml: 
``` yaml
apiVersion: v2
name: support
description: A Helm chart for supporting components

type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: metrics-server
  version: "6.5.3"
  repository: "https://charts.bitnami.com/bitnami"
- name: kubernetes-dashboard
  version: "^5.0.0"
  repository: "https://kubernetes.github.io/dashboard"
```

### What do you see instead?

This chart's helper function `common.tplvalues.render` is now interfering with Kubernetes Dashboard chart's `common.tplvalues.render` function. I see a new helper function is added with the new release to merge list of values with rendering called `common.tplvalues.merge` ([code](https://github.com/bitnami/charts/blame/c586293de255112ee434f353ce0b6f744100e6f8/bitnami/common/templates/_tplvalues.tpl#L30)) and that function is calling above mentioned render function (Specially to render metadata labels). 
As of my understanding this could be avoided by having unique like helper function signatures.
