### ISSUE TITLE
[bitnami/schema-registry] Schema Registry HPA not working properly

### ISSUE THREAD

**Issue by morkalfon** [bitnami/charts#19761]
### Name and Version

bitnami/schema-registry 14.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy Schema Registry via helm chart using the following values:
```
...
autoscaling:
   enabled: true
   minReplicas: 2
   maxReplicas: 4
   targetCPU: 85
   targetMemory: 90
kafka:
  # using pre-installed Kafka
  enabled: false
# connect to existing Kafka
externalKafka:
  brokers:
    - <BORKER>
...
```

### What is the expected behavior?

HPA should be created successfully.

### What do you see instead?

Getting the following error message on the HPA resource:
```
Warning  FailedGetScale  4s    horizontal-pod-autoscaler  deployments/scale.apps "confluent-schema-registry" not found
```

### Additional information

Looking at the code in: https://github.com/bitnami/charts/blob/754566b3508f66cc307e1439f48cda273ec33a42/bitnami/schema-registry/templates/hpa.yaml#L19
The scaleTargetRef is of type Deployment, but the the component being deployed as StatefulSet.
