### ISSUE TITLE
[bitnami/thanos] storegateway ingres grpc gets configured with wrong service name when sharding is enabled  

### ISSUE THREAD

**Issue by simisimis** [bitnami/charts#19769]
### Name and Version

bitnami/thanos 12.3.1, 12.13.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

using helmfile.yaml 
```yaml
  - name: thanos
    namespace: thanos
    chart: bitnami/thanos
    version: 10.13.7
      - storegateway:
          enabled: true
          sharded:
            enabled: true
          ingress:
            enabled: false
            grpc:
              enabled: true
              hostname: example.com
              ingressClassName: "alb"
              path: '/*'
              annotations:

```
This creates an ingress resource that is pointing to the wrong service. 

### Are you using any custom parameters or values?

Pasted above in the snippet.

### What is the expected behavior?

This snippet above works when I don't enable `sharded`.
When `sharded` is enabled ingress cannot reach the service anymore.

### What do you see instead?

When I enable sharded, it creates a service `thanos-storegateway-0` but it generates ingress grpc that points to `thanos-storegateway`. Manually editing ingres resource appending `-0` solves it until redeploy.
This is how the `spec` of ingress grpc looks when generated.
```yaml
spec:
  ingressClassName: alb
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          service:
            name: thanos-storegateway
            port:
              name: grpc
        path: /*
        pathType: ImplementationSpecific
```
service `thanos-storegateway` is not created. Instead, it's `thanos-storegateway-0`
