### ISSUE TITLE
[bitnami/keycloak] keycloakConfigCli won't run

### ISSUE THREAD

**Issue by macmenco** [bitnami/charts#19826]
### Name and Version

bitnami/keycloak 17.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Creating a kyecloak with the following values gives an error in the keycloakConfigCli

```
2023-10-06 15:07:12.702 ERROR 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : Could not connect to keycloak in 120 seconds: jakarta.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "features" (class org.keycloak.representations.info.ServerInfoRepresentation), not marked as ignorable (15 known properties: "protocolMapperTypes", "providers", "identityProviders", "themes", "passwordPolicies", "clientInstallations", "memoryInfo", "enums", "socialProviders", "clientImporters", "profileInfo", "componentTypes", "systemInfo", "cryptoInfo", "builtinProtocolMappers"])
 at [Source: (org.jboss.resteasy.specimpl.AbstractBuiltResponse$InputStreamWrapper); line: 1, column: 1200] (through reference chain: org.keycloak.representations.info.ServerInfoRepresentation["features"])
```

```
auth:
  adminUser: admin

proxy: edge

production: true 

replicaCount: 1

ingress:
  enabled: true
  ingressClassName: traefik
  hostname: sso.blabla.internal
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: internalsecure
    kubernetes.io/ingress.provider: traefik
  tls: true

resources:
  limits: 
    cpu: 1
    memory: 512Mi

postgresql:
  primary:
    containerSecurityContext:
      enabled: false
    resources:
      limits: 
        cpu: 1
        memory: 256Mi

tls:
  enabled: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

logging:
  level: WARN

keycloakConfigCli:
  enabled: true
  existingConfigmap: keycloak-config
  cleanupAfterFinished:
    enabled: true
    seconds: 600
```

### Are you using any custom parameters or values?

See values

### What is the expected behavior?

A running keycloak, configred according to the config in configmap

### What do you see instead?

The error
