### ISSUE TITLE
[bitnami/external-dns] unable to disable validation on external-dns

### ISSUE THREAD

**Issue by jwhitcraft** [bitnami/charts#19942]
### Name and Version

bitnami/external-dns:6.23.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Using ArgoCD with the ArgoCD Vault Plugin, i'm unable to bypass the validation of the external-dns chart.

My use case is that we pass in the path to the secret location inside of Hashicorp Vault and then argocd-vault-plugin does a `helm template --values values.yaml | argocd-vault-plugin generate -` to substitute the path out of the yaml files into the correct values.

Which then ARGO will apply to the cluster.

https://github.com/argoproj-labs/argocd-vault-plugin

### Are you using any custom parameters or values?

```yaml
aws:
  region: <path:omnibus/data/cluster123/external-dns#awsRegion>
  assumeRoleArn: <path:omnibus/data/cluster123/external-dns#assumeRoleArn>
serviceAccount:
  name: <path:omnibus/data/cluster123/external-dns#serviceAccountName>
  annotations:
    eks.amazonaws.com/role-arn:  <path:omnibus/data/cluster123/external-dns#serviceAccountArn>
txtOwnerId: <path:omnibus/data/cluster123/external-dns#txtOwnerId>
domainFilters: [<path:omnibus/data/cluster123/external-dns#domainFilters>]
sources: [<path:omnibus/data/cluster123/external-dns#sources>]
```

### What is the expected behavior?

Outputs the yaml with what was passed in, that way the argocd-vault-plugin can substitute out the values correctly. 

### What do you see instead?

Error: execution error at (external-dns/charts/external-dns/templates/NOTES.txt:11:3): 
VALUES VALIDATION:\nexternal-dns: aws.assumeRoleArn
    The AWS Role to assume must follow ARN format: `arn:aws:iam::123455567:role/external-dns`
    Ref: https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html
    Please set a valid ARN (--set aws.assumeRoleARN="xxxx")

Use --debug flag to render out invalid YAML

### Additional information

It would be nice to have a flag that could be set to disable the validation, so more advance tools like this could be used.

Thanks,
