### ISSUE TITLE
[bitnami/kafka] provision of topics fails due to race condition

### ISSUE THREAD

**Issue by sebastianlutter** [bitnami/charts#20019]
### Name and Version

bitnami/kafka 25.1.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Taken from https://github.com/bitnami/charts/issues/15686#issuecomment-1502055124, updated to my current version
1. Pull the chart and extract
```
helm pull bitnami/kafka --version 25.1.8
tar zxvf kafka-25.1.8.tgz
```
2. values.yaml
```
cat<<EOF > tmp-values.yml
zookeeper:
  enabled: false
kraft:
  enabled: true
replicaCount: 3
persistence:
  enabled: true
  size: 5Gi
externalAccess:
  enabled: true
  service:
    type: ClusterIP
    domain: "my.some.domain"
provisioning:
  enabled: true
  topics:
    - name: mytopic
      numPartitions: 20
      replicationFactor: 3
startupProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timoutSeconds: 1
  failureThreshold: 15
  successThreshold: 1
EOF
```
3.  install with helm
```
helm upgrade --install myKafka . -f tmp-values.yml
```
4. Inspect logs
```
kubectl logs -l app.kubernetes.io/component=kafka-provisioning
```
5. Find in logs the error that topic has not been created
```
[2023-10-10 15:05:26,557] ERROR org.apache.kafka.common.errors.InvalidReplicationFactorException: Unable to replicate the partition 3 time(s): The target replication factor of 3 cannot be reached because only 2 broker(s) are registered.
 (kafka.admin.TopicCommand$)
```

### Are you using any custom parameters or values?

```
zookeeper:
  enabled: false
kraft:
  enabled: true
replicaCount: 3
persistence:
  enabled: true
  size: 5Gi
externalAccess:
  enabled: true
  service:
    type: ClusterIP
    domain: "my.some.domain"
provisioning:
  enabled: true
  topics:
    - name: mytopic
      numPartitions: 20
      replicationFactor: 3
startupProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timoutSeconds: 1
  failureThreshold: 15
  successThreshold: 1
```

### What is the expected behavior?

Topic should be created, but sometimes fails due to race condition because not all kafka replicas are ready

### What do you see instead?

This error in provisioning pod:
```
Error while executing topic command : Unable to replicate the partition 3 time(s): The target replication factor of 3 cannot be reached because only 2 broker(s) are registered.
[2023-10-10 15:05:26,557] ERROR org.apache.kafka.common.errors.InvalidReplicationFactorException: Unable to replicate the partition 3 time(s): The target replication factor of 3 cannot be reached because only 2 broker(s) are registered.
```

### Additional information

As a workaround I added a sleep in `kafka/templates/provisioning/job.yaml` (at https://github.com/bitnami/charts/blob/9fbaaea4de7ac062477988400c7552cda7bd454f/bitnami/kafka/templates/provisioning/job.yaml#L169)
```
              echo "Starting provisioning"
              echo "BUT: we wait 60 seconds before doing so"
              sleep 60
```

It should start the provisioning job when all broker are ready:
 - Maybe using a init container that checks if kafka replica count are equal to the up-and-running kafka instances
 - Or the Job should fail if provisioning of one or more topic fails and be retried at a later time

Using the sleep as workaround is a really bad solution!
