### ISSUE TITLE
Unable to mount hostpath to bitname/kafka pods

### ISSUE THREAD

**Issue by ranjiniganeshan** [bitnami/charts#20077]
### Name and Version

bitnami/kafka version 25.1.12 

### What architecture are you using?

None

### What steps will reproduce the bug?
```
 helm upgrade --install kafkalog1 bitnami/kafka -n example --set persistence.size=250Gi -f kafka-rest/kafka.yaml -f kafka-rest/metrics.yaml
```
### Are you using any custom parameters or values?
```
 helm upgrade --install kafkalog1 bitnami/kafka -n example --set persistence.size=250Gi -f kafka-rest/kafka.yaml -f kafka-rest/metrics.yaml
```

### What is the expected behavior?

I'm adding this content to kafka.yaml but I see the hostpath configuration is ignored.
```yaml
volumeMounts:
  - mountPath: "/log"
    name: temporal

volumes:
- name: temporal
  hostPath:
    path: "/log"
    type: DirectoryOrCreate
```
### What do you see instead?

The hostpath is not mounted.

### Additional information

The hostpath is not mounted.

I have tried these things 
```
helm3 upgrade --install clusterkafkalog1 bitnami-full-index/kafka -n example --set volumes.temporal.hostPath.path=/logs --set persistence.size=10Gi,volumePermissions.enabled=true,persistence.enabled=true -f kafka-rest-log-1a/kafka.yaml -f kafka-rest-log-1a/metrics.yaml --version 25.1.12 
```

**Comment by ranjiniganeshan** [comment]
Any Update @carrodher

**Comment by juan131** [comment]
Hi @ranjiniganeshan 

There are no parameters named `volumes` or `volumeMounts` in Bitnami Kafka chart. I guess you meant using  `extraVolumeMounts` and `extraVolumes` that allow you defining extra volumes to add to Kafka pods:

```yaml
extraVolumeMounts:
  - mountPath: "/log"
    name: temporal
extraVolumes:
- name: temporal
  hostPath:
    path: "/log"
    type: DirectoryOrCreate
```

See:

- https://github.com/bitnami/charts/tree/main/bitnami/kafka#parameters

**Comment by ranjiniganeshan** [comment]
Thank you @juan131. Will try this and update.

**Comment by ranjiniganeshan** [comment]
@juan131 This works fine. Thank you again. But if you could suggest me further that would be great. 
I would like kafka logs to write to /shared/logs/kafka as of now /shared is mounted and I could see logs directory. I need a directory called kafka created when the hostpath mounts. Could you please suggest?

**Comment by juan131** [comment]
Hi @ranjiniganeshan 

Please note this charts offer you a series of parameters to manage storing Kafka logs on volumes. See:

- https://github.com/bitnami/charts/tree/main/bitnami/kafka#controller-eligible-statefulset-parameters

![Screenshot 2023-10-19 at 15 54 49](https://github.com/bitnami/charts/assets/6740773/f5471234-0010-4908-9d54-94054e0e29ad)

You can use `extraVolumes` in combination with `controller.logPersistence.existingClaim` parameter to store them on an hostPath volume.

**Comment by ranjiniganeshan** [comment]
@juan131 Thanks for helping. controller.logPersistence.existingClaim this paramater may not be much helpful.
Requirement : Hostpath /logs/data is common for all app running in eks. When never the app runs (pod runs) it will create a directory in the same name.
example: If the app name is kafka. It will create a directory /logs/data/kafka. Later the logs are written here. Kafka directory is created only if it is not available.
logstash container will read the logs from /logs/data/kafka.
with the below I m able to achieve. The volume /log are mounted. But I need kafka directory to be created.

Later I will modify the property logsDirs: /log/data/kafka. So that the logs are written.
extraVolumeMounts:
  - mountPath: "/log"
    name: temporal
extraVolumes:
- name: temporal
  hostPath:
    path: "/log"
    type: DirectoryOrCreate

Please advise. Appreciate your help in advance.

**Comment by juan131** [comment]
Hi @ranjiniganeshan 

I think you can achieve your goal using the values below:

```yaml
controller:
  logPersistence:
    enabled: true
    existingClaim: temporal
    mountPath: /logs/data/kafka
extraVolumes:
- name: temporal
  hostPath:
    path: /logs/data
    type: DirectoryOrCreate
```

That said, it's necessary to have the patch below in the chart to use this approach. I just created and it's waiting for review:

- https://github.com/bitnami/charts/pull/20476
