### ISSUE TITLE
[question] MongoDB replicaset servicemonitor

### ISSUE THREAD

**Issue by mdarii** [bitnami/charts#2008]
**Which chart**:

name: mongodb
version: 7.8.4

**Description**

Prometheus service monitor is configured to scrape metrics only from Primary instance. In case of failure of primary instance we will loss all metrics, metrics from secondary instance aren't collected.
What is reason to don't configure service monitor to scape secondary instance also?

**Comment by javsalgar** [comment]
Hi,

In the definition I see this

```
  selector:
    matchLabels:
      app: {{ template "mongodb.name" . }}
      chart: {{ template "mongodb.chart" . }}
      release: "{{ .Release.Name }}"
      heritage: "{{ .Release.Service }}"
```

In principle, this should apply to all pods, unless I'm missing anything.
