### ISSUE TITLE
Cassandra metrics exporter datacenter error

### ISSUE THREAD

**Issue by BrianGreenhill** [bitnami/charts#2011]
**Which chart**:
cassandra:3.11

**Description**
cassandra instance enters crashloop on k8s after adding the exporter to the statefulset spec.
```
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot retrieve the datacenter name information for the node
```

**Steps to reproduce the issue:**

1. Create cassandra statefulset manifest with exporter as container
```
      - image: bitnami/cassandra-exporter:2.3.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: metrics
          timeoutSeconds: 1
        name: metrics
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 5555
          name: jmx
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 45
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi
```
2. Delete pod from stateful set to restart with patched manifest
3. Pod enters crash loop and logs an error:
```
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot retrieve the datacenter name information for the node
```

**Describe the results you received:**

error in logs, crash looping cassandra instance

**Describe the results you expected:**

metrics were expected to be exported from the metrics container

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"archive", BuildDate:"2019-08-29T18:43:18Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

Could you share the full set of values you changed? I want to find out if there's an specific set of values that are triggering the issue.

**Comment by BrianGreenhill** [comment]
> Hi,
> 
> Could you share the full set of values you changed? I want to find out if there's an specific set of values that are triggering the issue.

Hello, @javsalgar,
here is the full manifest that I've used for cassandra. Please let me know if I can provide any more information.

Thanks for your support!

```
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: cassandra
    namespace: observability
    labels:
      app: cassandra
      app.kubernetes.io/name: cassandra
      app.kubernetes.io/component: storage-backend
      app.kubernetes.io/part-of: jaeger
  spec:
    ports:
    - port: 7000
      name: intra-node
    - port: 7001
      name: tls-intra-node
    - port: 7199
      name: jmx
    - port: 9042
      name: cql
    - port: 9160
      name: thrift
    clusterIP: None
    selector:
      app.kubernetes.io/name: cassandra
      app.kubernetes.io/component: storage-backend
      app.kubernetes.io/part-of: jaeger
- apiVersion: "apps/v1beta1"
  kind: StatefulSet
  metadata:
    name: cassandra
    namespace: observability
    labels:
      app: cassandra
      app.kubernetes.io/name: cassandra
      app.kubernetes.io/component: storage-backend
      app.kubernetes.io/part-of: jaeger
  spec:
    serviceName: cassandra
    replicas: 3
    template:
      metadata:
        namespace: observability
        labels:
          app: cassandra
          app.kubernetes.io/name: cassandra
          app.kubernetes.io/component: storage-backend
          app.kubernetes.io/part-of: jaeger
      spec:
        terminationGracePeriodSeconds: 1800
        containers:
        - name: cassandra
          image: cassandra:3.11
          command:
          - /docker-entrypoint.sh
          - "-R"
          ports:
          - containerPort: 7000
            name: intra-node
          - containerPort: 7001
            name: tls-intra-node
          - containerPort: 7199
            name: jmx
          - containerPort: 9042
            name: cql
          - containerPort: 9160
            name: thrift
          resources:
            requests:
              cpu: "100m"
              memory: "1Gi"
            limits:
              cpu: "100m"
              memory: "1Gi"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "nodetool drain"]
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_LISTEN_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CASSANDRA_CLUSTER_NAME
              value: "jaeger"
            - name: CASSANDRA_DC
              value: "dc1"
            - name: CASSANDRA_RACK
              value: "rack1"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: "GossipingPropertyFileSnitch"
            - name: CASSANDRA_SEEDS
              value: cassandra-0.cassandra
          volumeMounts:
          - name: cassandra-data
            mountPath: /var/lib/cassandra
          - name: cassandra-logs
            mountPath: /var/log/cassandra
        volumes:
        - name: cassandra-data
          emptyDir: {}
        - name: cassandra-logs
          emptyDir: {}
- apiVersion: batch/v1
  kind: Job
  metadata:
    namespace: observability
    name: jaeger-cassandra-schema-job
    labels:
      app: cassandra-schema
      app.kubernetes.io/name: cassandra-schema
      app.kubernetes.io/component: storage-backend
      app.kubernetes.io/part-of: jaeger
  spec:
    activeDeadlineSeconds: 86400
    template:
      metadata:
        name: cassandra-schema
      spec:
        activeDeadlineSeconds: 320
        containers:
        - name: jaeger-cassandra-schema
          image: jaegertracing/jaeger-cassandra-schema:1.6.0
          env:
            - name: MODE
              value: "prod"
            - name: DATACENTER
              value: "dc1"
        restartPolicy: OnFailure
```
