### ISSUE TITLE
[bitnami/mariadb] create more then one databases with list variable like MongoDB chart 

### ISSUE THREAD

**Issue by Syntax3rror404** [bitnami/charts#20224]
### Name and Version

Bitnami/mariadb:14.0.1

### What is the problem this feature will solve?

Currently, MariaDB can only be used with basic tools provided by this chart for purposes where only one database and only one user is required. Only one user and one database can be provided during creation.

The issue has already been resolved in the MongoDB Chart (example below).

### What is the feature you are proposing to solve the problem?

Like in MongoDB chart: (https://artifacthub.io/packages/helm/bitnami/mongodb?modal=values&path=auth.databases)

```
auth:
  ## @param auth.enabled Enable authentication
  ## ref: https://docs.mongodb.com/manual/tutorial/enable-authentication/
  ##
  enabled: true
  ## @param auth.rootUser MongoDB(&reg;) root user
  ##
  rootUser: root
  ## @param auth.rootPassword MongoDB(&reg;) root password
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/mongodb#setting-the-root-user-and-password-on-first-run
  ##
  rootPassword: ""
  ## MongoDB(&reg;) custom users and databases
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/mongodb#creating-a-user-and-database-on-first-run
  ## @param auth.usernames List of custom users to be created during the initialization
  ## @param auth.passwords List of passwords for the custom users set at `auth.usernames`
  ## @param auth.databases List of custom databases to be created during the initialization
  ##
  usernames: []
  passwords: []
  databases: []
```
