### ISSUE TITLE
stable/rabbitmq extra ports not working

### ISSUE THREAD

**Issue by embcla** [bitnami/charts#2023]
Uncommenting the "extraports" and "extracontainerports" in the values.yaml results in intepretation errors at various points of templates/svc.yaml

**Version of Helm and Kubernetes**:
Helm 3.0.2
Kube 1.17.3+k3s1

**Which chart**:
rabbitmq

**What happened**:
I tried to add port 1883 which is necessary for plugin mqtt 

**What you expected to happen**:
an additional port made available

**How to reproduce it** (as minimally and precisely as possible):
enter this

```
  ## Extra ports to expose 
  extraPorts: 
    1883 
 
  ## Extra ports to be included in container spec, primarily informational 
  extraContainerPorts: 
    1883 
```
or this
```
  ## Extra ports to expose 
  extraPorts: 1883 
 
  ## Extra ports to be included in container spec, primarily informational 
  extraContainerPorts: 1883 
```
and helm will quit with a yaml parse error

**Comment by rafariossaa** [comment]
Hi @embcla ,
extraPorts and extraContainerPorts should be a block like this:
```
  ## Extra ports to expose
  extraPorts:
   - name: extraPort
     port: 1883
     targetPort: 1883

  ## Extra ports to be included in container spec, primarily informational
  extraContainerPorts:
   - name: extraPort2
     port: 1884
     targetPort: 1884
```
