### ISSUE TITLE
[Bug] Can't deploy Grafana pod with custom nodeAffinityPreset preset

### ISSUE THREAD

**Issue by ak-aghost** [bitnami/charts#20237]
### Name and Version

bitnami/grafana-operator-3.4.10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

**Describe the bug**

Hello!

I have deploy latest Grafana-operator with my k8s cluster and got error: 
```
Error: template: grafana-operator/templates/grafana.yaml:87:190: executing "grafana-operator/templates/grafana.yaml" at <14>: wrong type for value; expected string; got map[string]interface {}
```
I'm using custom values for nodeAffinityPreset of Grafana pod:

```yaml
grafana:
  ## @param grafana.enabled Enabled the deployment of the Grafana CRD object into the cluster
  ##
  enabled: true

...

  nodeAffinityPreset:
    ## @param grafana.nodeAffinityPreset.type Set nodeAffinity preset type
    ## Allowed values: soft, hard
    ##
    type: "hard"
    ## @param grafana.nodeAffinityPreset.key Set nodeAffinity preset key
    ## E.g.
    ## key: "kubernetes.io/e2e-az-name"
    ##
    key: "kubernetes.io/hostname"
    ## @param grafana.nodeAffinityPreset.values Set nodeAffinity preset values
    ## E.g.
    ## values:
    ##   - e2e-az1
    ##   - e2e-az2
    ##
    values:
      - kuber-1.local
```

After investigation found that you missed `"include "common.affinities.nodes"` at line 87 file templates/grafana.yaml

So fixed version must look like this:

`nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.grafana.nodeAffinityPreset.type "key".Values.grafana.nodeAffinityPreset.key "values" .Values.grafana.nodeAffinityPreset.values) | nindent 14 }}`

patch file:

```diff
--- grafana.yaml	2023-10-13 09:50:13.421053391 -0400
+++ grafana.yaml.fixed	2023-10-13 09:50:32.669014190 -0400
@@ -84,7 +84,7 @@
             podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.grafana.podAntiAffinityPreset "component" "grafana" "customLabels" .Values.commonLabels "context" $) | nindent 14 }}
             {{- end }}
             {{- if not (empty .Values.grafana.nodeAffinityPreset.type) }}
-            nodeAffinity: {{- (dict "type" .Values.grafana.nodeAffinityPreset.type "key" .Values.grafana.nodeAffinityPreset.key "values" .Values.grafana.nodeAffinityPreset.values) | nindent 14 }}
+            nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.grafana.nodeAffinityPreset.type "key" .Values.grafana.nodeAffinityPreset.key "values" .Values.grafana.nodeAffinityPreset.values) | nindent 14 }}
             {{- end }}
           {{- end }}
           {{- if .Values.grafana.podSecurityContext.enabled }}
```

### What do you see instead?

error message:
```
Error: template: grafana-operator/templates/grafana.yaml:87:190: executing "grafana-operator/templates/grafana.yaml" at <14>: wrong type for value; expected string; got map[string]interface {}
```
