### ISSUE TITLE
[bitnami/keycloak] keycloakConfigCli uses incorrect port

### ISSUE THREAD

**Issue by jseiser** [bitnami/charts#20266]
### Name and Version

bitnami/keycloak 17.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Note how Keycloak Service's are configure by default, `-headless` is listening on port 80.

```
❯ kubectl get svc -n keycloak
NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
keycloak-headless        ClusterIP   None            <none>        80/TCP     36m
keycloak-postgresql-hl   ClusterIP   None            <none>        5432/TCP   36m
keycloak-postgresql      ClusterIP   10.43.253.101   <none>        5432/TCP   36m
keycloak                 ClusterIP   10.43.85.112    <none>        80/TCP     36m
```

yet, the CLI job comes up with keycloak url, with a completely different port

https://github.com/bitnami/charts/blob/main/bitnami/keycloak/templates/keycloak-config-cli-job.yaml#L75

```
    Environment:
      KEYCLOAK_URL:                        http://keycloak-headless:8080/
```

### Are you using any custom parameters or values?

```
auth:
  adminUser: randomuser
  adminPassword: "RandomPassword123"

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: keycloak.localdev.me


keycloakConfigCli:
  enabled: true
  configuration:
    config.json: {}
```

### What is the expected behavior?

CLI should be configured to use the port for the service its attemptign to reach

### What do you see instead?

Its trying to use the port from the container, not the service

```
  keycloak:
    Container ID:   containerd://268d3b9041467ded50d0b34871d281077953f0e390a7bdef54a79fb4ac9c88d2
    Image:          docker.io/bitnami/keycloak:22.0.4-debian-11-r3
    Image ID:       docker.io/bitnami/keycloak@sha256:a794ae4c8d1ef9750f43003ef49e7524a4a09ab94feaa68d3a6fa219326c8f4d
    Ports:          8080/TCP, 7800/TCP
```

### Additional information

This used to work, and somewhere in upgrading to the latest releases we noticed it fails.
