### ISSUE TITLE
[bitnami/mongodb] StatefulSet PVC template does not set common labels

### ISSUE THREAD

**Issue by silvamb** [bitnami/charts#20264]
### Name and Version

bitnami/mongodb 14.0.10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. With config
```yaml
architecture: replicaset
useStatefulSet: true
persistence:
  enabled: true
commonLabels:
  mylabel: "mylabelvalue"
```
2. Run the `helm template mongodb`
3. Statefulset Persistence Volume Claims template does dot include the common labels

### What is the expected behavior?

The stateful set should have rendered the common labels for the PVC template:
```yaml
spec:
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: datadir
        labels:
          app.kubernetes.io/component: mongodb
          mylabel: mylabelvalue
```

### What do you see instead?

```yaml
spec:
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: datadir
```
