### ISSUE TITLE
Dependency charts installed from oci:// URI fail

### ISSUE THREAD

**Issue by pentago** [bitnami/charts#20303]
### Name and Version

bitnami/rabbitmq

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Create an umbrella helm chart containing rabbitmq as one of the dependencies and run `helm dependency build --debug`

`Chart.yaml` for my umbrella chart:

```
apiVersion: v2
name: core-helm-charts
description: An umbrella Helm chart for core 3rd party applications
type: application
version: '1.0.0'
appVersion: '1.0.0'

dependencies:

  - name: cert-manager
    alias: cert-manager
    version: 'v1.13.1'
    repository: 'https://charts.jetstack.io'
    condition: cert-manager.enabled

  - name: argo-cd
    alias: argo-cd
    version: '5.46.8'
    repository: 'https://argoproj.github.io/argo-helm'
    condition: argocd.enabled

  - name: traefik
    alias: traefik
    version: 'v24.0.0'
    repository: 'https://traefik.github.io/charts'
    condition: traefik.enabled

  - name: rabbitmq
    alias: rabbitmq
    version: '12.2.5'
    repository: 'oci://registry-1.docker.io/bitnamicharts/rabbitmq'
    condition: rabbitmq.enabled

  - name: grafana
    alias: grafana
    version: '6.61.0'
    repository: 'https://grafana.github.io/helm-charts'
    condition: grafana.enabled

  - name: jaeger
    alias: jaeger
    version: '0.71.17'
    repository: 'https://jaegertracing.github.io/helm-charts'
    condition: jaeger.enabled

  - name: loki-stack
    alias: loki
    version: '2.9.11'
    repository: 'https://grafana.github.io/helm-charts'
    condition: loki.enabled

  - name: prometheus
    alias: prometheus
    version: '25.1.0'
    repository: 'https://prometheus-community.github.io/helm-charts'
    condition: prometheus.enabled

  - name: connect
    alias: 1password-connect
    version: '1.14.0'
    repository: 'https://1password.github.io/connect-helm-charts'
    condition: 1password.enabled

  - name: sealed-secrets
    alias: sealed-secrets
    version: 'v2.13.1'
    repository: 'oci://registry-1.docker.io/bitnamicharts/sealed-secrets'
    condition: sealed-secrets.enabled

  - name: ingress-nginx
    alias: ingress-nginx
    version: '4.8.2'
    repository: 'https://kubernetes.github.io/ingress-nginx'
    condition: ingress-nginx.enabled

```

### Are you using any custom parameters or values?

No.

### What is the expected behavior?

Successful installation.

### What do you see instead?

```
Downloading rabbitmq from repo oci://registry-1.docker.io/bitnamicharts/rabbitmq
DEBU[0022] resolving                                     host=registry-1.docker.io
DEBU[0022] do request                                    host=registry-1.docker.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=Helm/3.13.1 request.method=HEAD url="https://registry-1.docker.io/v2/bitnamicharts/rabbitmq/rabbitmq/manifests/12.2.3"
DEBU[0023] fetch response received                       host=registry-1.docker.io response.header.content-length=174 response.header.content-type=application/json response.header.date="Wed, 18 Oct 2023 12:05:16 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.strict-transport-security="max-age=31536000" response.header.www-authenticate="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:bitnamicharts/rabbitmq/rabbitmq:pull\"" response.status="401 Unauthorized" url="https://registry-1.docker.io/v2/bitnamicharts/rabbitmq/rabbitmq/manifests/12.2.3"
DEBU[0023] Unauthorized                                  header="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:bitnamicharts/rabbitmq/rabbitmq:pull\"" host=registry-1.docker.io
DEBU[0023] do request                                    host=registry-1.docker.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=Helm/3.13.1 request.method=HEAD url="https://registry-1.docker.io/v2/bitnamicharts/rabbitmq/rabbitmq/manifests/12.2.3"
DEBU[0024] fetch response received                       host=registry-1.docker.io response.header.content-length=174 response.header.content-type=application/json response.header.date="Wed, 18 Oct 2023 12:05:17 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.strict-transport-security="max-age=31536000" response.header.www-authenticate="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:bitnamicharts/rabbitmq/rabbitmq:pull\",error=\"insufficient_scope\"" response.status="401 Unauthorized" url="https://registry-1.docker.io/v2/bitnamicharts/rabbitmq/rabbitmq/manifests/12.2.3"
DEBU[0024] Unauthorized                                  header="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:bitnamicharts/rabbitmq/rabbitmq:pull\",error=\"insufficient_scope\"" host=registry-1.docker.io
INFO[0024] trying next host                              error="pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed" host=registry-1.docker.io
Save error occurred:  could not download oci://registry-1.docker.io/bitnamicharts/rabbitmq/rabbitmq: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
Error: could not download oci://registry-1.docker.io/bitnamicharts/rabbitmq/rabbitmq: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
helm.go:84: [debug] pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
could not download oci://registry-1.docker.io/bitnamicharts/rabbitmq/rabbitmq
helm.sh/helm/v3/pkg/downloader.(*Manager).downloadAll
        helm.sh/helm/v3/pkg/downloader/manager.go:356
helm.sh/helm/v3/pkg/downloader.(*Manager).Update
        helm.sh/helm/v3/pkg/downloader/manager.go:200
helm.sh/helm/v3/pkg/downloader.(*Manager).Build
        helm.sh/helm/v3/pkg/downloader/manager.go:95
main.newDependencyBuildCmd.func1
        helm.sh/helm/v3/cmd/helm/dependency_build.go:71
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.7.0/command.go:940
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.7.0/command.go:992
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:267
runtime.goexit
        runtime/asm_arm64.s:1197
```

### Additional information

Installing charts via `helm install` and `oci://` URI works fine, doesn't work when `oci://`  URI is used for dependency charts.

**Comment by devthejo** [comment]
I have this error just now, here is my Chart.yaml
```yaml
apiVersion: v2
name: minio
version: 0.0.0
dependencies:
  - repository: oci://registry-1.docker.io/bitnamicharts/minio
    name: minio
    version: "12.10.3"
```
when I run `helm dependency update`, I get this:
```
Downloading minio from repo oci://registry-1.docker.io/bitnamicharts/minio
Save error occurred:  could not download oci://registry-1.docker.io/bitnamicharts/minio/minio: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
Error: could not download oci://registry-1.docker.io/bitnamicharts/minio/minio: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```
