### ISSUE TITLE
[bitmani/Redis] Not be able to pull from market place last version ( https://marketplace.azurecr.io/helm/v1/repo )

### ISSUE THREAD

**Issue by Tirius667** [bitnami/charts#20302]
### Name and Version

bitnami/redis

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Run `helm dependency update` with the following configuration in my Chart.yml. ( working fine on my project several days ago )

```yaml
    - name: redis
      alias: redis
      version: 17.3.12
      repository: https://marketplace.azurecr.io/helm/v1/repo
```
2. However, now it's impossible to find this version ( 17.3.12 ) in the Azure public registry at https://marketplace.azurecr.io/helm/v1/repo when I launch a `helm dependency update`.

### What is the expected behavior?

- Downloading the Redis chart. 

### What do you see instead?

Error message: `Error: can't get a valid version for repositories redis. Try changing the version constraint in Chart.yaml`

### Additional information

I know this may be not the right place to ask for this, but since https://github.com/bitnami/azure-marketplace-charts is on read-only mode, I'm asking here. 

Thanks for your help.
