### ISSUE TITLE
[bitnami/postgresql] Incorrect rendering of the initContainer command in postgres helm chart (user formatting)

### ISSUE THREAD

**Issue by tonxxd** [bitnami/charts#20300]
### Name and Version

bitnami/postgresql 13.0.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Incorrect rendering of the initContainer command (user formatting)

Use these values to deploy the chart

```yaml
primary:
  podSecurityContext:
    enabled: true
    runAsUser: 1003080000
    fsGroup: 1003080000
  containerSecurityContext:
    runAsUser: 1003080000
    runAsGroup: 1003080000
    allowPrivilegeEscalation: false

  persistence:
    size: 50Gi

volumePermissions:
  containerSecurityContext:
    runAsUser: 1003080000
    runAsGroup: 1003080000
    runAsNonRoot: true
  enabled: true
```

This will render the statefulset initContainers as 

```yaml
initContainers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: init-chmod-data
          command:
            - /bin/sh
            - '-ec'
            - >
              chown 1.00308e+09:1.00308e+09 /bitnami/postgresql

              mkdir -p /bitnami/postgresql/data

              chmod 700 /bitnami/postgresql/data

              find /bitnami/postgresql -mindepth 1 -maxdepth 1 -not -name "conf"
              -not -name ".snapshot" -not -name "lost+found" | \
                xargs -r chown -R 1.00308e+09:1.00308e+09
              chmod -R 777 /dev/shm
          securityContext:
            runAsUser: 1003080000
            runAsGroup: 1003080000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /bitnami/postgresql
            - name: dshm
              mountPath: /dev/shm
          terminationMessagePolicy: File
          image: 'docker.io/bitnami/os-shell:11-debian-11-r77'
```
Which leads to this error in the `init-chmod-data` container
`chown: invalid user: '1.00308e+09:1.00308e+09'`

### Are you using any custom parameters or values?

```yaml
primary:
  podSecurityContext:
    enabled: true
    runAsUser: 1003080000
    fsGroup: 1003080000
  containerSecurityContext:
    runAsUser: 1003080000
    runAsGroup: 1003080000
    allowPrivilegeEscalation: false

  persistence:
    size: 50Gi

volumePermissions:
  containerSecurityContext:
    runAsUser: 1003080000
    runAsGroup: 1003080000
    runAsNonRoot: true
  enabled: true
```

### What is the expected behavior?

Render `1003080000` instead of `1.00308e+09:1.00308e+09`

### What do you see instead?

```yaml
initContainers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: init-chmod-data
          command:
            - /bin/sh
            - '-ec'
            - >
              chown 1.00308e+09:1.00308e+09 /bitnami/postgresql

              mkdir -p /bitnami/postgresql/data

              chmod 700 /bitnami/postgresql/data

              find /bitnami/postgresql -mindepth 1 -maxdepth 1 -not -name "conf"
              -not -name ".snapshot" -not -name "lost+found" | \
                xargs -r chown -R 1.00308e+09:1.00308e+09
              chmod -R 777 /dev/shm
          securityContext:
            runAsUser: 1003080000
            runAsGroup: 1003080000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /bitnami/postgresql
            - name: dshm
              mountPath: /dev/shm
          terminationMessagePolicy: File
          image: 'docker.io/bitnami/os-shell:11-debian-11-r77'
```
