### ISSUE TITLE
[bitnami/jaeger] deployment missing imagePullSecrets

### ISSUE THREAD

**Issue by avl-team-pandas** [bitnami/charts#20318]
### Name and Version

bitnami/jaeger 1.3.5

### What architecture are you using?

None

### What steps will reproduce the bug?

Using Jaeger chart with values that contain either `global.imagePullSecrets` or `image.pullSecrets`:

```
global:
  imageRegistry: "my.registry.com"
  imagePullSecrets:
    - my-docker-secret

image:
  pullSecrets:
    - my-docker-secret
```

and deploying it or simply using `helm template` will show that
there are no rendered imagePullSecrets for Jaeger agent, collector or query. Only place with imagePullSecrets is the cassandra subchart.

In the deployment.yaml's of agent, collector and query there is no property imagePullSecrets defined.

### What is the expected behavior?

It is expected that Jaeger agent, collector and query deployments have imagePullSecrets if specified in values

### What do you see instead?

imagePullSecrets is not rendered even though it is present in values
