### ISSUE TITLE
[bitnami/keycloak] Storage Class not passed to KeyCloak PVC

### ISSUE THREAD

**Issue by AhmadHasan** [bitnami/charts#20354]
### Name and Version

bitnami/keycloak 17.0.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Install bitnami chart for KeyCloak with the paramter
`global.storageClass = myStorageClass`

The PVC data-keycloak-postgresql-0 is not satisfied and two pods are failing to start. Checking the deployed state, the StorageClassName is not set. When I set the StorageClassName manually, everything works!

### Are you using any custom parameters or values?

global.storageClass

### What is the expected behavior?

PVC can be satisfied.

### What do you see instead?

PVC keeps trying to load, but a message saying "No persistence volume is available...." is logged under events

**Comment by MartinWallgren** [comment]
I encountered this and was surprised that it was closed without a comment. I don't know if it is the expected way, but I managed to get this working by passing the storage class directly to postresql via the values.

```
postgresql:
  primary:
    persistence:
      storageClass: "SomeStorageClass"
```

**Comment by javsalgar** [comment]
Hi!

It seems that it was the OP the one that closed it. In principle, global should work, so if it doesn't there's a bug in the chart.

**Comment by danim55** [comment]
I think this issue is interesting. At least in the docs some mention should appear to explain how to configure the pvc and pv of the default postgresql used in this chart. For reference i add what worked for me:

```yaml
 - name: keycloak
    namespace: {{ $keycloakNamespace | quote }}
    createNamespace: true
    chart: {{ printf "oci://%s/bitnamicharts/keycloak" $dockerHubRegistryProxy }} 
    version: 24.7.7
    values:
      - global:  
          security: 
            allowInsecureImages: true # Needed because of https://github.com/bitnami/charts/issues/30850
          imageRegistry: {{ $dockerHubRegistryProxy | quote }}
        image:
          pullPolicy: IfNotPresent

        # PostgreSQL Specific Configuration
        postgresql:
          enabled: true
          primary:
            persistence:
              enabled: true
              storageClass: custom-storage-class
              size: 2Gi
```

Notice how the persistence configuration needs to be under `primary` section.
