### ISSUE TITLE
[bitnami/kafka] SASL client users list not being updated on chart upgrade

### ISSUE THREAD

**Issue by dfgrosso** [bitnami/charts#20357]
### Name and Version

bitnami/kafka 25.1.6

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Install the chart with a given list of users configured in sasl.client.users
2. Add a user to the list or change an existing one
3. Upgrade the chart
4. Authentication fails for the new/edited users

### Are you using any custom parameters or values?

```yaml
## @section Kafka SASL parameters
## Kafka SASL settings for authentication, required if SASL_PLAINTEXT or SASL_SSL listeners are configured
##
sasl:
  ## @param sasl.enabledMechanisms Comma-separated list of allowed SASL mechanisms when SASL listeners are configured. Allowed types: `PLAIN`, `SCRAM-SHA-256`, `SCRAM-SHA-512`
  ## NOTE: At the moment, Kafka Raft mode does not support SCRAM, that is why only PLAIN is configured.
  ##
  enabledMechanisms: PLAIN
  ## @param sasl.interBrokerMechanism SASL mechanism for inter broker communication.
  ##
  interBrokerMechanism: PLAIN
  ## @param sasl.controllerMechanism SASL mechanism for controller communications.
  ##
  controllerMechanism: PLAIN
  ## Credentials for inter-broker communications.
  ## @param sasl.interbroker.user Username for inter-broker communications when SASL is enabled
  ## @param sasl.interbroker.password Password for inter-broker communications when SASL is enabled. If not set and SASL is enabled for the controller listener, a random password will be generated.
  ##
  interbroker:
    user: inter_broker_user
    password: ""
  ## Credentials for controller communications.
  ## @param sasl.controller.user Username for controller communications when SASL is enabled
  ## @param sasl.controller.password Password for controller communications when SASL is enabled. If not set and SASL is enabled for the inter-broker listener, a random password will be generated.
  ##
  controller:
    user: controller_user
    password: ""
  ## Credentials for client communications.
  ## @param sasl.client.users Comma-separated list of usernames for client communications when SASL is enabled
  ## @param sasl.client.passwords Comma-separated list of passwords for client communications when SASL is enabled, must match the number of client.users
  ##
  ## The provisioning job uses the first user of the list and its password must also be in a key named "system-user-password" in the given secret
  client:
    users:
      - system-user
      - api-admin-kafka
      - api-audit-kafka
      - api-auth-kafka
      - api-crm-kafka
      - api-game-kafka
      - api-game-trx-kafka
      - api-ext-com-kafka
      - api-ext-int-kafka
      - clickhouse-kafka
      - opm-event-notifications-manager-kafka
      - opm-external-message-request-manager-kafka

  ## @param sasl.existingSecret Name of the existing secret containing credentials for clientUsers, interBrokerUser, controllerUser and zookeeperUser
  ## Create this secret running the command below where SECRET_NAME is the name of the secret you want to create:
  ##       kubectl create secret generic SECRET_NAME --from-literal=client-passwords=CLIENT_PASSWORD1,CLIENT_PASSWORD2 --from-literal=inter-broker-password=INTER_BROKER_PASSWORD --from-literal=controller-password=CONTROLLER_PASSWORD --from-literal=zookeeper-password=ZOOKEEPER_PASSWORD
  ##
  existingSecret: "api-kafka-secret"
```

### What is the expected behavior?

The new/edited users should work

### What do you see instead?
```
org.apache.kafka.common.errors.SaslAuthenticationException: Authentication failed: Invalid username or password
```
### Additional information

I'm using KRAFT mode
