### ISSUE TITLE
[bitnami/kafka ] - Can only set one k8s secret with certs for controller nodes following Kafka Chart Refactor in 24.0.0

### ISSUE THREAD

**Issue by fouadsemaan** [bitnami/charts#20369]
### Name and Version

bitnami/kafka 26.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In AKS 1.26.* 

With these overrides (default kraft mode with controller + broker mode with 3 replicas):
```yaml
kraft:
  enabled: true
listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    external:
      protocol: TLS
tls:
    externalClientProtocol: tls
    password: mydirtylittlesecret
    existingSecret: "" # previously an array --> ["my-kafka-0-pem","my-kafka-1-pem","my-kafka-2-pem"]
    jksTruststore: truststore.jks
    jksKeystoreSAN: keystore.jks
```

### What is the expected behavior?

In the past `existingSecret` was an array of the secrets holding the JKS store of each broker. Each broker got a copy of all the stores and the secret to use was driven by the ID. Now it's just one string. My secrets are generated by Cert Manager. Is bitnami now expecting them to be packaged in one chart?

The CertManager workflow is broken as it can't bundle different certs into one Kubernetes secret.

### What do you see instead?

I expect the secretName input/output to remain the same.
