### ISSUE TITLE
[bitnami/redis] StatefulSet PVC template does not set common labels

### ISSUE THREAD

**Issue by asafsgit** [bitnami/charts#20373]
### Name and Version

bitnami/redis 18.1.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. With config 

```
commonLabels:
  foo: bar
``` 
      
2. helm install oci://registry-1.docker.io/bitnamicharts/redis -f C:\GitHub\QM_Apollo\hydra\Redis\redis-values-test.yaml --dry-run --generate-name
3. Statefulset Persistence Volume Claims template does not include the common labels

### What is the expected behavior?

The stateful set should have rendered the common labels for the PVC template:

```
 volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: redis-data
        labels:
          foo: bar
          app.kubernetes.io/name: redis
          ....
      spec:
``` 

### What do you see instead?

```
volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: redis-data
        labels:
          app.kubernetes.io/instance: redis-1698119788
          app.kubernetes.io/name: redis
          app.kubernetes.io/component: master
``` 

### Additional information

seems related to this issue: #20264

If I change in the statefulset template from 

```
{{- $claimLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.master.persistence.labels .Values.commonLabels ) "context" . ) }}
        labels: {{- include "common.labels.matchLabels" ( dict "customLabels" $claimLabels "context" $ ) | nindent 10 }}
```

to 

```
{{- $claimLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.master.persistence.labels .Values.commonLabels ) "context" . ) }}
        labels: {{- include "common.labels.standard" ( dict "customLabels" $claimLabels "context" $ ) | nindent 10 }}
```

I can see my label

**Comment by javsalgar** [comment]
Hi,

I believe that this has to do with breaking changes. If we add commonLabels to the PVCs, then we need to bump the major version because there would be installations using commonLabels that will break after updates. Therefore, I think we were waiting for a major bump to add that section.

**Comment by asafsgit** [comment]
Thanks @javsalgar! 

Please mind that it is not only commonLabels. This config also doesn't work:
```
master:
  persistence:
    labels:
      foo: bar
``` 
Will wait for your next major release

**Comment by italoiz** [comment]
It seems this is happening with the RabbitMQ chart too. I tried to set `commonLabels` and also `persistence.labels`, and it didn't take any effect on created PVCs.

Below is what my `values.yaml` looks like right now.

<details>
  <summary>values.yaml</summary>

```yaml
# ... rest of file above

## @param commonLabels Labels to add to all deployed objects
##
commonLabels:
  recurring-job.longhorn.io/source: enabled
  recurring-job-group.longhorn.io/three-times-day-backup: enabled

# ...
## @section Persistence parameters
##
persistence:
  ## @param persistence.enabled Enable RabbitMQ data persistence using PVC
  ##
  enabled: true
  
  ## @param persistence.storageClass PVC Storage Class for RabbitMQ data volume
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: longhorn
  
  ## @param persistence.selector Selector to match an existing Persistent Volume
  ## selector:
  ##   matchLabels:
  ##     app: my-app
  ##
  # selector: {}
  
  ## @param persistence.accessModes PVC Access Modes for RabbitMQ data volume
  ##
  accessModes:
    - ReadWriteOnce
  
  ## @param persistence.existingClaim Provide an existing PersistentVolumeClaims
  ## The value is evaluated as a template
  ## So, for example, the name can depend on .Release or .Chart
  ##
  # existingClaim: rabbitmq-pvc

  ## @param persistence.mountPath The path the volume will be mounted at
  ## Note: useful when using custom RabbitMQ images
  ##
  # mountPath: /bitnami/rabbitmq/mnesia
  ## @param persistence.subPath The subdirectory of the volume to mount to
  ## Useful in dev environments and one PV for multiple services
  ##
  # subPath: ""

  ## @param persistence.size PVC Storage Request for RabbitMQ data volume
  ## If you change this value, you might have to adjust `rabbitmq.diskFreeLimit` as well
  ##
  size: 3Gi
  
  ## @param persistence.annotations Persistence annotations. Evaluated as a template
  ## Example:
  ## annotations:
  ##   example.io/disk-volume-type: SSD
  ##
  # annotations: {}

  ## @param persistence.labels Persistence labels. Evaluated as a template
  ## Example:
  ## labels:
  ##   app: my-app
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/three-times-day-backup: enabled
```
</details>

Am I doing something wrong?
