### ISSUE TITLE
[bitnami/minio] Minio provisioning job not executed at the right time when is part of an umbrella chart

### ISSUE THREAD

**Issue by alita1991** [bitnami/charts#20386]
### Name and Version

bitnami/minio:12.8.15

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create an umbrella chart and add as dependency minio subchart and mimir/loki/tempo from grafana
2. Update values.yaml of the umbrella chart for minio and enable the provisioning job to create the required bucket
3. Deploy the umbrella chart via ArgoCD / Helm

### Are you using any custom parameters or values?

```yaml
provisioning:
  enabled: true
  buckets:
    - name: mimir-ruler
    - name: mimir-blocks
    - name: mimir-alertmanager
    - name: loki-blocks
    - name: tempo-traces
```

### What is the expected behavior?

The provisioning job should be executed after minio is deployed

### What do you see instead?

The provisioning job is executed at the end of the umbrella chart deployment, which results in deployment failure. One idea to solve this problem is to allow the provisioning job to run in parallel with the deployment of minio and wait for the minio to be accessible for a configurable amount of time.
