### ISSUE TITLE
postgres helm chart install failed if set extraEnvVars for metrics

### ISSUE THREAD

**Issue by snailxr** [bitnami/charts#20394]
### Name and Version

bitnami/postgresql:11.9.13

### What architecture are you using?

amd64

### What steps will reproduce the bug?

in value.yaml
```yaml
architecture: replication
metrics:
    enabled: true
    extraEnvVars:
      - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
        value: "true"
```
then install

### What do you see instead?
```
Error: INSTALLATION FAILED: YAML parse error on xxx/templates/read/statefulset.yaml: error converting YAML to JSON: yaml: line 241: did not find expected key
```

### Additional information

```yaml
              {{- if .Values.metrics.extraEnvVars }}
              {{- include "common.tplvalues.render" (dict "value" .Values.metrics.extraEnvVars "context" $) | nindent 12 }}
              {{- end }}``
```
Seems the nindent is not correct in `templates/read/statefulset.yaml`
