### ISSUE TITLE
[bitnami/postgresql-ha] configure an internal Loadbalancer for pgpool

### ISSUE THREAD

**Issue by ton3r** [bitnami/charts#20402]
### Name and Version

bitnami/postgres-ha

### What is the problem this feature will solve?

Currently I can configure ClusterIP, NodePort or external Loadbalancer.

But we wanna have a dedicated GKE cluster for postgres-ha. 

To get other VMs or microservices access over pgpool, I want to configure a load-balancer-type "internal"

```
apiVersion: v1
kind: Service
metadata:
  name: postgres-ha
  labels:
    app: postgres-ha
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.165.77.100
  selector:
    app: postgres-ha
  ports:
  - name: postgress
    port: 5432
    protocol: TCP
```

### What is the feature you are proposing to solve the problem?

to have a setting like

```
service.type=InternalLoadBalancer
service.loadBalancerIP=10.165.77.100
```

### What alternatives have you considered?

used `service.type=NodePort`, but IP can change if cluster reconfigure.
