### ISSUE TITLE
[mariadb-galera] Passwords seemingly get changed after some time, access denied for user 'root'@'localhost' puts pods in CrashLoop

### ISSUE THREAD

**Issue by jakuzure** [bitnami/charts#20416]
### Name and Version

bitnami/mariadb-galera 9.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

This issue is probably hard to reproduce, but here's how it's been happening for us on multiple clusters (RKE2 clusters on vSphere):

- deploy 3 node cluster
- everything works fine for days or even weeks
- one or multiple pods can't connect to root on localhost anymore, which results in probes failing and the pods being stuck in a CrashLoop
- connecting to another pod's DB with the credentials mounted in the secret works
- when a previously still working pod gets restarted, it starts having the same error

### Are you using any custom parameters or values?

```
image:
  tag: 10.7.7-debian-11-r30

serviceAccount:
  create: true
  automountServiceAccountToken: true

rbac:
  create: true

podManagementPolicy: Parallel

replicaCount: 3

db:
  user: technical
  name: ""

persistence:
  size: 20Gi

existingSecret: mariadb-credentials
```

### What do you see instead?

The user passwords of the DB seemingly get changed after a while, even though we declared them all in a secret and the cluster works fine for a while.

I got a failing cluster working again like this:

- Scaled down to one node, with diagnosticMode enabled
- Followed this guide to set the root password to the one we use in the existingSecret: https://docs.bitnami.com/aws/infrastructure/lamp/administration/change-reset-password-mariadb/
- Initiated bootstrap from Node 0 and the pod started running again
- Scaled back up to 3 nodes, but the other pods couldn't sync up
  - Set the password of the mariabackup user directly on the working pod. Then the remaining pods became ready again

It seems like not only the root user, but also mariabackup get their passwords changed to something else.

I don't know what could be causing this after the cluster has been working fine for quite a while.

Did this mayb happen to anybody else as well?
