### ISSUE TITLE
postgresql readiness probe exec - second command is never run

### ISSUE THREAD

**Issue by okgolove** [bitnami/charts#20434]
### Name and Version

bitnami/postgresql 13.1.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Minikube
2. default values
3. `helm install postgresql --version 13.1.5 bitnami/postgresql`

### What is the expected behavior?

Readiness check which contains two commands check pg_isready and for file as well

```yaml
exec:
  command:
    - /bin/sh
    - -c
    - -e
    - |
      exec pg_isready -U "test" -d "dbname=boom" -h 127.0.0.1 -p 5432
      [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
```

### What do you see instead?

Second command `[ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]` is never be run.

### Additional information

To reproduce it a large sql dump can be put to /docker-entrypoint-initdb.d directory. During the restoring process check the pod readiness status. It will be ready. This shouldn't happen if the second command is used in readinessProbe.

By the way, this [if statement](https://github.com/bitnami/charts/blob/d6092dc781b59106e434fa591c94e26494fa2f07/bitnami/postgresql/templates/_helpers.tpl#L303) could be put under values logic, not just contains check. As an example, I built my own image based on the bitnami postgresql image and put it into my private docker registry and as a result, I don't have this initialization readiness check.
