### ISSUE TITLE
[bitnami/postgresql-ha]: 

### ISSUE THREAD

**Issue by mike-pisman** [bitnami/charts#20437]
### Name and Version

bitnami/postgresql-ha-11.9.8

### What architecture are you using?

microk8s HA (3 nodes) - Kubernetes 1.28

### What steps will reproduce the bug?

Installed the database with helm chart.

Tried creating new database
```bash
$ PGPASSWORD="$POSTGRES_PASSWORD" psql -h 10.0.2.168 -p 5432 -U postgres
``` 

```sql
postgres=# CREATE DATABASE test;
CREATE DATABASE
```
```sql
postgres=# GRANT ALL ON DATABASE test TO postgres;
GRANT
```

```sql
postgres=# \l
                                                 List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    | ICU Locale | Locale Provider |   Access privileges
-----------+----------+----------+-------------+-------------+------------+-----------------+-----------------------
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            |
 repmgr    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            |
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | =c/postgres          +
           |          |          |             |             |            |                 | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | =c/postgres          +
           |          |          |             |             |            |                 | postgres=CTc/postgres
 test      | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | =Tc/postgres         +
           |          |          |             |             |            |                 | postgres=CTc/postgres
```

### Are you using any custom parameters or values?

```yaml
postgresql:
  password: LZZTcUu9M9
  repmgrPassword: LeBrJzJM9Y
  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false
  startupProbe:
    enabled: false
service:
  type: LoadBalancer
pgpool:
  adminPassword: IQgLSmaWZG
  customUsers:
    usernames: "user01"
    passwords: "pass01"
metrics:
  enabled: false
  readinessPro:
    enabled: false
  livenessProbe:
    enabled: false
```

### What is the expected behavior?

To be able to connect to and use(query) the new database.

### What do you see instead?

```console
$ PGPASSWORD="$POSTGRES_PASSWORD" psql -h 10.0.2.168 -p 5432 -U postgres -d test

psql: error: connection to server at "10.0.2.168", port 5432 failed: ERROR:  unable to read message kind
DETAIL:  kind does not match between main(45) slot[2] (53)
```

In log of pg-poll pod
```console
...
2023-10-26 01:37:22.064: psql pid 169: LOG:  pool_read_kind: error message from main backend:database "test" does not exist
2023-10-26 01:37:22.064: psql pid 169: ERROR:  unable to read message kind
2023-10-26 01:37:22.064: psql pid 169: DETAIL:  kind does not match between main(45) slot[2] (53)
```

### Additional information

Seems like my installation is broken, becaues when I try to create a new user and connect with credentials "user01" "pass01", I get an error

```
psql: error: connection to server at "10.0.2.168", port 5432 failed: ERROR:  backend authentication failed
DETAIL:  backend response with kind 'E' when expecting 'R'
```

The regular postgresql (not HA) seems to work fine though.
