### ISSUE TITLE
[bitnami/kube-prometheus] Prometheus.monitoring.coreos.com "prometheus-kube-prometheus-prometheus" is invalid

### ISSUE THREAD

**Issue by mohitmaheshwari31** [bitnami/charts#20445]
### Name and Version

bitnami/kube-prometheus

### What architecture are you using?

None

### What steps will reproduce the bug?
```
Prometheus.monitoring.coreos.com "prometheus-kube-prometheus-prometheus" is invalid: spec.storage.volumeClaimTemplate.metadata: Invalid value: "null": spec.storage.volumeClaimTemplate.metadata in body must be of type object: "null"
```
### Are you using any custom parameters or values?
```yaml
  remoteWrite: 
  - url: http://thanos-receive:19291/api/v1/receive
  ## @param prometheus.enableRemoteWriteReceiver Enable Prometheus to be used as a receiver for the Prometheus remote write protocol.
  ##
  enableRemoteWriteReceiver: true
  ## @param prometheus.storageSpec Prometheus StorageSpec for persistent data
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/storage.md
  ##
  storageSpec: {}
  ## Prometheus persistence parameters
  ##
  persistence:
    ## @param prometheus.persistence.enabled Use PVCs to persist data. If the storageSpec is provided this will not take effect.
    ##
    enabled: true
    ## @param prometheus.persistence.storageClass Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ## set, choosing the default provisioner.
    ##
    storageClass: ""
    ## @param prometheus.persistence.accessModes Persistent Volume Access Modes
    ##
    accessModes:
      - ReadWriteOnce
    ## @param prometheus.persistence.size Persistent Volume Size
    ##
    size: 20Gi
    ## @param prometheus.persistence.annotations Persistent Volume Claim annotations
    ##
    annotations: {}
  ## @param prometheus.priorityClassName Priority class assigned to the Pods
  ##
  priorityClassName: ""
  ## @param prometheus.containers Containers allows injecting additional containers
  ##
  containers: []
```
