### ISSUE TITLE
[wordpress] Can not create /bitnami/wordpress/wp-content

### ISSUE THREAD

**Issue by polRk** [bitnami/charts#2046]
```
mysql-c INFO  MySQL server listening and working at mariadb:3306
wordpre INFO  Preparing WordPress environment
wordpre INFO  You provided an already initialized WordPress database.
wordpre INFO  The installation wizard will be skipped and parameters for configuring the user account will be ignored.
wordpre INFO  Upgrading WordPress Database ...
php     TRACE [runProgram] Executing: /opt/bitnami/php/bin/php /tmp/15840908800950.4420257811142374
wordpre TRACE [prepareDataToPersist] Preparing /opt/bitnami/wordpress/wp-content to persist in /bitnami/wordpress/wp-content
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/wordpress/wp-content'
```

values.yaml
```
persistence:
  enabled: true
  storageClass: "csi-s3"
  accessMode: ReadWriteMany
  size: 10Gi
```

**Comment by javsalgar** [comment]
Hi,

Could you provide more information about your Kubernetes platform and the storage you are using?

**Comment by polRk** [comment]
yes, i'm used csi-s3 storage https://github.com/ctrox/csi-s3

Kubernetes provider is DigitalOcean
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

It seems that the volume you are using is not compatible with the `fsGroup` setting in the `securityContext` section. This is the one that should adapt the volume permissions so you don't get permission denied errors. In order to fix this we could add the `volumePermissions` init container that we have in other charts.

https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml#L575

I'm not entirely sure that this would cover your use case, but it is worth trying :) Could you try doing helm template, add this `volumePermissions` init container and check if it works after that? If so, I will create a PR.

**Comment by polRk** [comment]
I have opened the PR for initContainers #2058

**Comment by javsalgar** [comment]
Awesome, thanks for contributing! :)

**Comment by emreberber** [comment]
This issue still continues.

Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/wordpress/wp-content'

**Comment by javsalgar** [comment]
Hi,

Probably it has to do with the specific platform you are using. Could you provide more information about your Kubernetes platform and the storage you are using?

**Comment by emreberber** [comment]
Rancher version v2.4.3 and Ceph RBD

Thanks,

**Comment by javsalgar** [comment]
Hi,

I believe

**Comment by javsalgar** [comment]
This PR should fix the issue https://github.com/bitnami/charts/pull/3850

**Comment by dani8art** [comment]
no stale

**Comment by miguelaeh** [comment]
Addin on-hold until the above PR is meged

**Comment by maximmai** [comment]
The issue is reproduced on Kubernetes running on Bare Metal, with NFS as storageClass.

**Comment by dani8art** [comment]
Hi @maximmai did you enable the `volumePermissions` container in this chart in order to avoid issues?

**Comment by floek** [comment]
Same issue here on bare metal with glusterfs. How do I enable this volumePermissions container with  initContainers?

**Comment by floek** [comment]
Okay, setting these values worked in my case:
```yaml
        initContainers:
          - name: volume-permissions
            image: bitnami/minideb
            imagePullPolicy: Always
            command: ['sh', '-c', 'chown -R 1001:1001 /bitnami/wordpress']
            volumeMounts:
            - mountPath: /bitnami/wordpress
              name: wordpress-data
              subPath: wordpress
```
