### ISSUE TITLE
Thanos

### ISSUE THREAD

**Issue by gipyeong-lee** [bitnami/charts#20475]
### Name and Version

bitnami/thanos 12.13.13

### What architecture are you using?

None

### What steps will reproduce the bug?

1. implement override value.yaml
```yaml
enabled: true
query:
  enabled: true
  dnsDiscovery:
    enabled: true
    sidecarsService: prometheus-thanos-discovery
    sidecarsNamespace: prometheus-operator
queryFrontend:
  enabled: false
bucketweb:
  enabled: true
compactor:
  enabled: true
storegateway:
  enabled: true
ruler:
  enabled: true
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  config: |-
    groups:
    - name: example
      rules:
      - record: job:http_inprogress_requests:sum
        expr: sum(http_inprogress_requests) by (job)
receive:
  enabled: false
```
2. Deploy 
3. Checking arguments

### Are you using any custom parameters or values?

```yaml
enabled: true
query:
  enabled: true
  dnsDiscovery:
    enabled: true
    sidecarsService: prometheus-thanos-discovery
    sidecarsNamespace: prometheus-operator

```

### What is the expected behavior?

```yaml
        - args:
            - query
            - '--log.level=info'
            - '--log.format=logfmt'
            - '--grpc-address=0.0.0.0:10901'
            - '--http-address=0.0.0.0:10902'
            - '--query.replica-label=replica'
            - '--endpoint=dnssrv+_grpc._tcp.prometheus-thanos-discovery.prometheus-operator.svc.cluster.local
```

### What do you see instead?

```yaml
        - args:
            - query
            - '--log.level=info'
            - '--log.format=logfmt'
            - '--grpc-address=0.0.0.0:10901'
            - '--http-address=0.0.0.0:10902'
            - '--query.replica-label=replica'
```

### Additional information
```
  {{- if and .Values.query.dnsDiscovery.enabled .Values.query.dnsDiscovery.sidecarsService .Values.query.dnsDiscovery.sidecarsNamespace }}
            - --endpoint=dnssrv+_grpc._tcp.{{- include "common.tplvalues.render" ( dict "value" .Values.query.dnsDiscovery.sidecarsService "context" $) -}}.{{- include "common.tplvalues.render"  ( dict "value" .Values.query.dnsDiscovery.sidecarsNamespace "context" $) -}}.svc.{{ .Values.clusterDomain }}
  {{- end }}
```
