### ISSUE TITLE
[bitnami/kafka] jmx or kafka exporter is not exporting kafka_server_raft-metrics

### ISSUE THREAD

**Issue by acharbha** [bitnami/charts#20491]
### Name and Version

bitnami/kafka 25.1.10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```yaml
  jmx:
    enabled: true	
    kafkaJmxPort: 5555	
    image:	
      registry: docker.io	
      repository: bitnami/jmx-exporter	
      tag: 0.19.0-debian-11-r66	
      digest: ""	
      pullPolicy: IfNotPresent	
      pullSecrets: []	
    containerSecurityContext: {}	
    containerPorts:	
      metrics: 5556	
    resources:	
      limits: {}	
      requests: {}	
    service:	
      ports:	
        metrics: 5556	
      clusterIP: ""	
      sessionAffinity: None	
      annotations:	
        prometheus.io/scrape: "true"	
        prometheus.io/port: "{{ .Values.metrics.jmx.service.ports.metrics }}"	
        prometheus.io/path: "/"	
    whitelistObjectNames:	
      - kafka.controller:*	
      - kafka.server:*	
      - java.lang:*	
      - kafka.network:*	
      - kafka.log:*	
    config: |-	
      jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:{{ .Values.metrics.jmx.kafkaJmxPort }}/jmxrmi	
      lowercaseOutputName: true	
      lowercaseOutputLabelNames: true	
      ssl: false	
      {{- if .Values.metrics.jmx.whitelistObjectNames }}	
      whitelistObjectNames: ["{{ join "\"	\"" .Values.metrics.jmx.whitelistObjectNames }}"]
      {{- end }}	
    existingConfigmap: ""	
    extraRules: ""	
  serviceMonitor:	
    namespace: "default"	
    interval: "1m"	
    scrapeTimeout: ""	
    labels: {}	
    selector: {}	
    relabelings: []	
    metricRelabelings: []	
    honorLabels: false	
    jobLabel: ""	
  prometheusRule:	
    groups: []	
```

### Are you using any custom parameters or values?

I've added required rules in `jmx-configmap.yaml` as below -

```yaml
      - pattern: kafka.server<type=(raft-metrics), name=(.+)><>(Value)
        name: kafka_server_$1_$2_$3 
``` 
Even though adding the above explicitly, its missing kafka_server_raft-metrics in Prometheus.

### What is the expected behavior?

I expect to see following metrics -
```
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/acharbha/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/acharbha/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.75in .7in .75in .7in;
	mso-header-margin:.3in;
	mso-footer-margin:.3in;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl65
	{font-weight:700;}
-->
</style>
</head>

<body link="#0563C1" vlink="#954F72">



MBEAN   NAME
--
kafka.server:type=raft-metrics,name=current-state
kafka.server:type=raft-metrics,name=current-leader
kafka.server:type=raft-metrics,name=current-vote
kafka.server:type=raft-metrics,name=current-epoch
kafka.server:type=raft-metrics,name=high-watermark
kafka.server:type=raft-metrics,name=log-end-offset
kafka.server:type=raft-metrics,name=number-unknown-voter-connections
kafka.server:type=raft-metrics,name=commit-latency-avg
kafka.server:type=raft-metrics,name=commit-latency-max
kafka.server:type=raft-metrics,name=election-latency-avg
kafka.server:type=raft-metrics,name=election-latency-max
kafka.server:type=raft-metrics,name=fetch-records-rate
kafka.server:type=raft-metrics,name=append-records-rate
kafka.server:type=raft-metrics,name=poll-idle-ratio-avg
kafka.server:type=MetadataLoader,name=CurrentMetadataVersion
kafka.server:type=MetadataLoader,name=HandleLoadSnapshotCount
kafka.server:type=SnapshotEmitter,name=LatestSnapshotGeneratedBytes
kafka.server:type=SnapshotEmitter,name=LatestSnapshotGeneratedAgeMs



</body>

</html>
```

### What do you see instead?

I'm seeing all other metrics except raft-metrics

```
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/acharbha/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/acharbha/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.75in .7in .75in .7in;
	mso-header-margin:.3in;
	mso-footer-margin:.3in;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl65
	{background:#C6E0B4;
	mso-pattern:black none;}
-->
</style>
</head>

<body link="#0563C1" vlink="#954F72">



Metric Name
--
java_lang_classloading_loadedclasscount
java_lang_classloading_totalloadedclasscount
java_lang_classloading_unloadedclasscount
java_lang_classloading_verbose
java_lang_compilation_compilationtimemonitoringsupported
java_lang_compilation_totalcompilationtime
java_lang_memory_heapmemoryusage_committed
java_lang_memory_heapmemoryusage_init
java_lang_memory_heapmemoryusage_max
java_lang_memory_heapmemoryusage_used
java_lang_memory_nonheapmemoryusage_committed
java_lang_memory_nonheapmemoryusage_init
java_lang_memory_nonheapmemoryusage_max
java_lang_memory_nonheapmemoryusage_used
java_lang_memory_objectpendingfinalizationcount
java_lang_memory_verbose
java_lang_operatingsystem_availableprocessors
java_lang_operatingsystem_committedvirtualmemorysize
java_lang_operatingsystem_cpuload
java_lang_operatingsystem_freememorysize
java_lang_operatingsystem_freephysicalmemorysize
java_lang_operatingsystem_freeswapspacesize
java_lang_operatingsystem_maxfiledescriptorcount
java_lang_operatingsystem_openfiledescriptorcount
java_lang_operatingsystem_processcpuload
java_lang_operatingsystem_processcputime
java_lang_operatingsystem_systemcpuload
java_lang_operatingsystem_systemloadaverage
java_lang_operatingsystem_totalmemorysize
java_lang_operatingsystem_totalphysicalmemorysize
java_lang_operatingsystem_totalswapspacesize
java_lang_runtime_bootclasspathsupported
java_lang_runtime_pid
java_lang_runtime_starttime
java_lang_runtime_uptime
java_lang_threading_currentthreadallocatedbytes
java_lang_threading_currentthreadcputime
java_lang_threading_currentthreadcputimesupported
java_lang_threading_currentthreadusertime
java_lang_threading_daemonthreadcount
java_lang_threading_objectmonitorusagesupported
java_lang_threading_peakthreadcount
java_lang_threading_synchronizerusagesupported
java_lang_threading_threadallocatedmemoryenabled
java_lang_threading_threadallocatedmemorysupported
java_lang_threading_threadcontentionmonitoringenabled
java_lang_threading_threadcontentionmonitoringsupported
java_lang_threading_threadcount
java_lang_threading_threadcputimeenabled
java_lang_threading_threadcputimesupported
java_lang_threading_totalstartedthreadcount
jmx_config_reload_failure_created
jmx_config_reload_failure_total
jmx_config_reload_success_created
jmx_config_reload_success_total
jmx_exporter_build_info
jmx_scrape_cached_beans
jmx_scrape_duration_seconds
jmx_scrape_error
kafka_broker_info
kafka_brokers
kafka_controller_kafkacontroller_activebrokercount_value
kafka_controller_kafkacontroller_activecontrollercount_value
kafka_controller_kafkacontroller_fencedbrokercount_value
kafka_controller_kafkacontroller_globalpartitioncount_value
kafka_controller_kafkacontroller_globaltopiccount_value
kafka_controller_kafkacontroller_lastappliedrecordlagms_value
kafka_controller_kafkacontroller_lastappliedrecordoffset_value
kafka_controller_kafkacontroller_lastappliedrecordtimestamp_value
kafka_controller_kafkacontroller_lastcommittedrecordoffset_value
kafka_controller_kafkacontroller_metadataerrorcount_value
kafka_controller_kafkacontroller_offlinepartitionscount_value
kafka_controller_kafkacontroller_preferredreplicaimbalancecount_value
kafka_controller_kafkacontroller_zkmigrationstate_value
kafka_exporter_build_info
kafka_log_log_logendoffset
kafka_log_log_logstartoffset
kafka_log_log_numlogsegments
kafka_log_log_size
kafka_network_processor_idlepercent_value
kafka_network_requestchannel_requestqueuesize_value
kafka_network_requestchannel_responsequeuesize_processor_0_value
kafka_network_requestchannel_responsequeuesize_processor_1_value
kafka_network_requestchannel_responsequeuesize_processor_2_value
kafka_network_requestchannel_responsequeuesize_processor_3_value
kafka_network_requestchannel_responsequeuesize_processor_4_value
kafka_network_requestchannel_responsequeuesize_processor_5_value
kafka_network_requestchannel_responsequeuesize_processor_6_value
kafka_network_requestchannel_responsequeuesize_processor_7_value
kafka_network_requestchannel_responsequeuesize_processor_8_value
kafka_network_requestchannel_responsequeuesize_value
kafka_network_requestmetrics_errorspersec_count
kafka_network_requestmetrics_localtimems_count
kafka_network_requestmetrics_messageconversionstimems_count
kafka_network_requestmetrics_remotetimems_count
kafka_network_requestmetrics_requestbytes_count
kafka_network_requestmetrics_requestqueuetimems_count
kafka_network_requestmetrics_requestspersec_count
kafka_network_requestmetrics_responsequeuetimems_count
kafka_network_requestmetrics_responsesendtimems_count
kafka_network_requestmetrics_temporarymemorybytes_count
kafka_network_requestmetrics_throttletimems_count
kafka_network_requestmetrics_totaltimems_count
kafka_network_socketserver_expiredconnectionskilledcount_value
kafka_network_socketserver_memorypoolavailable_value
kafka_network_socketserver_memorypoolused_value
kafka_network_socketserver_networkprocessoravgidlepercent_value
kafka_server_brokermetadatalistener_total_metadatabatchprocessingtimeus_count
kafka_server_brokermetadatalistener_total_metadatabatchsizes_count
kafka_server_brokertopicmetrics_bytesinpersec_count
kafka_server_brokertopicmetrics_bytesinpersec_oneminuterate
kafka_server_brokertopicmetrics_messagesinpersec_count
kafka_server_brokertopicmetrics_messagesinpersec_oneminuterate
kafka_server_brokertopicmetrics_total_bytesinpersec_count
kafka_server_brokertopicmetrics_total_bytesinpersec_oneminuterate
kafka_server_brokertopicmetrics_total_bytesoutpersec_count
kafka_server_brokertopicmetrics_total_bytesoutpersec_oneminuterate
kafka_server_brokertopicmetrics_total_bytesrejectedpersec_count
kafka_server_brokertopicmetrics_total_bytesrejectedpersec_oneminuterate
kafka_server_brokertopicmetrics_total_failedfetchrequestspersec_count
kafka_server_brokertopicmetrics_total_failedfetchrequestspersec_oneminuterate
kafka_server_brokertopicmetrics_total_failedproducerequestspersec_count
kafka_server_brokertopicmetrics_total_failedproducerequestspersec_oneminuterate
kafka_server_brokertopicmetrics_total_fetchmessageconversionspersec_count
kafka_server_brokertopicmetrics_total_fetchmessageconversionspersec_oneminuterate
kafka_server_brokertopicmetrics_total_invalidmagicnumberrecordspersec_count
kafka_server_brokertopicmetrics_total_invalidmagicnumberrecordspersec_oneminuterate
kafka_server_brokertopicmetrics_total_invalidmessagecrcrecordspersec_count
kafka_server_brokertopicmetrics_total_invalidmessagecrcrecordspersec_oneminuterate
kafka_server_brokertopicmetrics_total_invalidoffsetorsequencerecordspersec_count
kafka_server_brokertopicmetrics_total_invalidoffsetorsequencerecordspersec_oneminuterate
kafka_server_brokertopicmetrics_total_messagesinpersec_count
kafka_server_brokertopicmetrics_total_messagesinpersec_oneminuterate
kafka_server_brokertopicmetrics_total_nokeycompactedtopicrecordspersec_count
kafka_server_brokertopicmetrics_total_nokeycompactedtopicrecordspersec_oneminuterate
kafka_server_brokertopicmetrics_total_producemessageconversionspersec_count
kafka_server_brokertopicmetrics_total_producemessageconversionspersec_oneminuterate
kafka_server_brokertopicmetrics_total_reassignmentbytesinpersec_count
kafka_server_brokertopicmetrics_total_reassignmentbytesinpersec_oneminuterate
kafka_server_brokertopicmetrics_total_reassignmentbytesoutpersec_count
kafka_server_brokertopicmetrics_total_reassignmentbytesoutpersec_oneminuterate
kafka_server_brokertopicmetrics_total_replicationbytesinpersec_count
kafka_server_brokertopicmetrics_total_replicationbytesinpersec_oneminuterate
kafka_server_brokertopicmetrics_total_replicationbytesoutpersec_count
kafka_server_brokertopicmetrics_total_replicationbytesoutpersec_oneminuterate
kafka_server_brokertopicmetrics_total_totalfetchrequestspersec_count
kafka_server_brokertopicmetrics_total_totalfetchrequestspersec_oneminuterate
kafka_server_brokertopicmetrics_total_totalproducerequestspersec_count
kafka_server_brokertopicmetrics_total_totalproducerequestspersec_oneminuterate
kafka_server_brokertopicmetrics_totalproducerequestspersec_count
kafka_server_brokertopicmetrics_totalproducerequestspersec_oneminuterate
kafka_server_controllermutation_queue_size
kafka_server_controllerserver_total_linux_disk_read_bytes_value
kafka_server_controllerserver_total_linux_disk_write_bytes_value
kafka_server_controllerserver_total_yammer_metrics_count_value
kafka_server_delayedoperationpurgatory_numdelayedoperations_alteracls_value
kafka_server_delayedoperationpurgatory_numdelayedoperations_deleterecords_value
kafka_server_delayedoperationpurgatory_numdelayedoperations_electleader_value
kafka_server_delayedoperationpurgatory_numdelayedoperations_fetch_value
kafka_server_delayedoperationpurgatory_numdelayedoperations_heartbeat_value
kafka_server_delayedoperationpurgatory_numdelayedoperations_produce_value
kafka_server_delayedoperationpurgatory_numdelayedoperations_rebalance_value
kafka_server_delayedoperationpurgatory_purgatorysize_alteracls_value
kafka_server_delayedoperationpurgatory_purgatorysize_deleterecords_value
kafka_server_delayedoperationpurgatory_purgatorysize_electleader_value
kafka_server_delayedoperationpurgatory_purgatorysize_fetch_value
kafka_server_delayedoperationpurgatory_purgatorysize_heartbeat_value
kafka_server_delayedoperationpurgatory_purgatorysize_produce_value
kafka_server_delayedoperationpurgatory_purgatorysize_rebalance_value
kafka_server_fetch_queue_size
kafka_server_fetcherstats_total_bytespersec_clientid_replicafetcherthread_0_0_brokerhost_my_kafka_controller_0_my_kafka_controller_headless_kafka_svc_cluster_local_brokerport_9094_count
kafka_server_fetcherstats_total_bytespersec_clientid_replicafetcherthread_0_0_brokerhost_my_kafka_controller_0_my_kafka_controller_headless_kafka_svc_cluster_local_brokerport_9094_oneminuterate
kafka_server_fetcherstats_total_bytespersec_clientid_replicafetcherthread_0_1_brokerhost_my_kafka_controller_1_my_kafka_controller_headless_kafka_svc_cluster_local_brokerport_9094_count
kafka_server_fetcherstats_total_bytespersec_clientid_replicafetcherthread_0_1_brokerhost_my_kafka_controller_1_my_kafka_controller_headless_kafka_svc_cluster_local_brokerport_9094_oneminuterate
kafka_server_fetcherstats_total_bytespersec_clientid_replicafetcherthread_0_2_brokerhost_my_kafka_controller_2_my_kafka_controller_headless_kafka_svc_cluster_local_brokerport_9094_count
kafka_server_fetcherstats_total_bytespersec_clientid_replicafetcherthread_0_2_brokerhost_my_kafka_controller_2_my_kafka_controller_headless_kafka_svc_cluster_local_brokerport_9094_oneminuterate
kafka_server_fetcherstats_total_requestspersec_clientid_replicafetcherthread_0_0_brokerhost_my_kafka_controller_0_my_kafka_controller_headless_kafka_svc_cluster_local_brokerport_9094_count
kafka_server_fetcherstats_total_requestspersec_clientid_replicafetcherthread_0_0_brokerhost_my_kafka_controller_0_my_kafka_controller_headless_kafka_svc_cluster_local_brokerport_9094_oneminuterate
kafka_server_fetcherstats_total_requestspersec_clientid_replicafetcherthread_0_1_brokerhost_my_kafka_controller_1_my_kafka_controller_headless_kafka_svc_cluster_local_brokerport_9094_count
kafka_server_fetcherstats_total_requestspersec_clientid_replicafetcherthread_0_1_brokerhost_my_kafka_controller_1_my_kafka_controller_headless_kafka_svc_cluster_local_brokerport_9094_oneminuterate
kafka_server_fetcherstats_total_requestspersec_clientid_replicafetcherthread_0_2_brokerhost_my_kafka_controller_2_my_kafka_controller_headless_kafka_svc_cluster_local_brokerport_9094_count
kafka_server_fetcherstats_total_requestspersec_clientid_replicafetcherthread_0_2_brokerhost_my_kafka_controller_2_my_kafka_controller_headless_kafka_svc_cluster_local_brokerport_9094_oneminuterate
kafka_server_fetchsessioncache_total_incrementalfetchsessionevictionspersec_count
kafka_server_fetchsessioncache_total_incrementalfetchsessionevictionspersec_oneminuterate
kafka_server_fetchsessioncache_total_numincrementalfetchpartitionscached_value
kafka_server_fetchsessioncache_total_numincrementalfetchsessions_value
kafka_server_kafkarequesthandlerpool_total_requesthandleravgidlepercent_count
kafka_server_kafkarequesthandlerpool_total_requesthandleravgidlepercent_oneminuterate
kafka_server_kafkaserver_total_brokerstate_value
kafka_server_kafkaserver_total_linux_disk_read_bytes_value
kafka_server_kafkaserver_total_linux_disk_write_bytes_value
kafka_server_kafkaserver_total_yammer_metrics_count_value
kafka_server_produce_queue_size
kafka_server_replicaalterlogdirsmanager_total_deadthreadcount_clientid_replicaalterlogdirs_value
kafka_server_replicaalterlogdirsmanager_total_failedpartitionscount_clientid_replicaalterlogdirs_value
kafka_server_replicaalterlogdirsmanager_total_maxlag_clientid_replicaalterlogdirs_value
kafka_server_replicaalterlogdirsmanager_total_minfetchrate_clientid_replicaalterlogdirs_value
kafka_server_replicafetchermanager_deadthreadcount_value
kafka_server_replicafetchermanager_failedpartitionscount_value
kafka_server_replicafetchermanager_maxlag_value
kafka_server_replicafetchermanager_minfetchrate_value
kafka_server_replicamanager_total_atminisrpartitioncount_value
kafka_server_replicamanager_total_failedisrupdatespersec_count
kafka_server_replicamanager_total_failedisrupdatespersec_oneminuterate
kafka_server_replicamanager_total_isrexpandspersec_count
kafka_server_replicamanager_total_isrexpandspersec_oneminuterate
kafka_server_replicamanager_total_isrshrinkspersec_count
kafka_server_replicamanager_total_isrshrinkspersec_oneminuterate
kafka_server_replicamanager_total_leadercount_value
kafka_server_replicamanager_total_offlinereplicacount_value
kafka_server_replicamanager_total_partitioncount_value
kafka_server_replicamanager_total_partitionswithlatetransactionscount_value
kafka_server_replicamanager_total_produceridcount_value
kafka_server_replicamanager_total_reassigningpartitions_value
kafka_server_replicamanager_total_underminisrpartitioncount_value
kafka_server_replicamanager_total_underreplicatedpartitions_value
kafka_server_request_queue_size
kafka_topic_partition_current_offset
kafka_topic_partition_in_sync_replica
kafka_topic_partition_leader
kafka_topic_partition_leader_is_preferred
kafka_topic_partition_oldest_offset
kafka_topic_partition_replicas
kafka_topic_partition_under_replicated_partition
kafka_topic_partitions



</body>

</html>
```

### Additional information

```yaml
  images: |
    - name: jmx-exporter
      image: docker.io/bitnami/jmx-exporter:0.19.0-debian-11-r66
    - name: kafka-exporter
      image: docker.io/bitnami/kafka-exporter:1.7.0-debian-11-r102
    - name: kafka
      image: docker.io/bitnami/kafka:3.5.1-debian-11-r44
    - name: kubectl
      image: docker.io/bitnami/kubectl:1.25.13-debian-11-r11
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r60
  licenses: Apache-2.0
apiVersion: v2
appVersion: 3.5.1
```

**Comment by joancafom** [comment]
Hi @acharbha 

I can definitely export KRaft-related metrics using the following `extraRules`:

```yaml
metrics:
  jmx:
    extraRules:
      - pattern: "kafka.server<type=raft-metrics><>(current-state): (.+)"
        name: kafka_server_raft_metrics
        labels:
          name: $1
          state: $2
        value: 1
      - pattern: "kafka.server<type=raft-metrics><>(.+): (.+)"
        name: kafka_server_raft_metrics
        labels:
          name: $1
```

```
...
# HELP kafka_server_raft_metrics The average number of records appended per sec as the leader of the raft quorum. kafka.server:name=null,type=raft-metrics,attribute=append-records-rate
# TYPE kafka_server_raft_metrics untyped
kafka_server_raft_metrics{name="append-records-rate",} 0.0
kafka_server_raft_metrics{name="commit-latency-avg",} NaN
kafka_server_raft_metrics{name="number-unknown-voter-connections",} 0.0
kafka_server_raft_metrics{name="election-latency-max",} NaN
kafka_server_raft_metrics{name="election-latency-avg",} NaN
kafka_server_raft_metrics{name="poll-idle-ratio-avg",} 0.9861080963750813
kafka_server_raft_metrics{name="current-state",state="follower",} 1.0
kafka_server_raft_metrics{name="current-vote",} -1.0
kafka_server_raft_metrics{name="commit-latency-max",} NaN
kafka_server_raft_metrics{name="high-watermark",} 219.0
kafka_server_raft_metrics{name="log-end-epoch",} 4.0
kafka_server_raft_metrics{name="current-leader",} 1.0
kafka_server_raft_metrics{name="log-end-offset",} 220.0
kafka_server_raft_metrics{name="fetch-records-rate",} 2.0195065978198508
kafka_server_raft_metrics{name="current-epoch",} 4.0
```

I guess the error should be in your pattern itself.

**Comment by acharbha** [comment]
> joancafom

thanks a lot, I'm getting the raft metrics now.
by any chance do you how can I scrape producer and consumer metrics from Kafka cluster? is this is possible from kafka cluster or those metrics only available on Kafka client machines?
if possible, can you give me the rules and pattern for producer and consumer metrics?

**Comment by joancafom** [comment]
>thanks a lot, I'm getting the raft metrics now.

That's nice!

>by any chance do you how can I scrape producer and consumer metrics from Kafka cluster? is this is possible from kafka cluster or those metrics only available on Kafka client machines?
if possible, can you give me the rules and pattern for producer and consumer metrics?

I'm sorry but my knowledge about specific metrics and rules is limited. I recommend you reach out to the JMX exporter community for further info instead :) 

As this seems solved, I will proceed to close the thread now.

**Comment by yujinchoi-94** [comment]
### Name and Version: kafka, 24.0.3
@joancafom  
Hi! I am also trying to collect kraft metrics using `extraRules`.

I tried adding [this configuration](https://github.com/bitnami/charts/issues/20491#issuecomment-1791074759) to my helm values file, but it didn't work.

Here's my values.yaml.
```
kafka:
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    external:
      protocol: PLAINTEXT

  controller:
    replicaCount: 3

  externalAccess:
    enabled: true
    autoDiscovery:
      enabled: true
    controller:
      service:
        loadBalancerAnnotations:
          - service.beta.kubernetes.io/aws-load-balancer-type: external
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
            service.beta.kubernetes.io/aws-load-balancer-scheme: internal
          - service.beta.kubernetes.io/aws-load-balancer-type: external
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
            service.beta.kubernetes.io/aws-load-balancer-scheme: internal
          - service.beta.kubernetes.io/aws-load-balancer-type: external
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
            service.beta.kubernetes.io/aws-load-balancer-scheme: internal

  rbac:
    create: true

  metrics:
    jmx:
      enabled: true
    extraRules:
      - pattern: "kafka.server<type=raft-metrics><>(current-state): (.+)"
        name: kafka_server_raft_metrics
        labels:
          name: $1
          state: $2
        value: 1
      - pattern: "kafka.server<type=raft-metrics><>(.+): (.+)"
        name: kafka_server_raft_metrics
        labels:
          name: $1
    kafka:
      enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
  kraft:
    clusterId: lYuVBmG446na6oWDz6ulxQ

```


I found out that the extraRules are being removed when i rendered helm chart locally.
```
helm template . --debug -f values.yaml
# Source: kafka-poc/charts/kafka/templates/metrics/jmx-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-kafka-jmx-configuration
  namespace: "argo-events"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    app.kubernetes.io/version: 3.6.1
    helm.sh/chart: kafka-26.4.4
    app.kubernetes.io/component: metrics
data:
  jmx-kafka-prometheus.yml: |-
    jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:5555/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    whitelistObjectNames: ["kafka.controller:*","kafka.server:*","java.lang:*","kafka.network:*","kafka.log:*"]
    rules:
      - pattern: kafka.controller<type=(ControllerChannelManager), name=(QueueSize), broker-id=(\d+)><>(Value)
        name: kafka_controller_$1_$2_$4
        labels:
          broker_id: "$3"
      - pattern: kafka.controller<type=(ControllerChannelManager), name=(TotalQueueSize)><>(Value)
        name: kafka_controller_$1_$2_$3
      - pattern: kafka.controller<type=(KafkaController), name=(.+)><>(Value)
        name: kafka_controller_$1_$2_$3
      - pattern: kafka.controller<type=(ControllerStats), name=(.+)><>(Count)
        name: kafka_controller_$1_$2_$3
      - pattern : kafka.network<type=(Processor), name=(IdlePercent), networkProcessor=(.+)><>(Value)
        name: kafka_network_$1_$2_$4
        labels:
          network_processor: $3
      - pattern : kafka.network<type=(RequestMetrics), name=(.+), request=(.+)><>(Count|Value)
        name: kafka_network_$1_$2_$4
        labels:
          request: $3
      - pattern : kafka.network<type=(SocketServer), name=(.+)><>(Count|Value)
        name: kafka_network_$1_$2_$3
      - pattern : kafka.network<type=(RequestChannel), name=(.+)><>(Count|Value)
        name: kafka_network_$1_$2_$3
      - pattern: kafka.server<type=(.+), name=(.+), topic=(.+)><>(Count|OneMinuteRate)
        name: kafka_server_$1_$2_$4
        labels:
          topic: $3
      - pattern: kafka.server<type=(ReplicaFetcherManager), name=(.+), clientId=(.+)><>(Value)
        name: kafka_server_$1_$2_$4
        labels:
          client_id: "$3"
      - pattern: kafka.server<type=(DelayedOperationPurgatory), name=(.+), delayedOperation=(.+)><>(Value)
        name: kafka_server_$1_$2_$3_$4
      - pattern: kafka.server<type=(.+), name=(.+)><>(Count|Value|OneMinuteRate)
        name: kafka_server_$1_total_$2_$3
      - pattern: kafka.server<type=(.+)><>(queue-size)
        name: kafka_server_$1_$2
      - pattern: java.lang<type=(.+), name=(.+)><(.+)>(\w+)
        name: java_lang_$1_$4_$3_$2
      - pattern: java.lang<type=(.+), name=(.+)><>(\w+)
        name: java_lang_$1_$3_$2
      - pattern : java.lang<type=(.*)>
      - pattern: kafka.log<type=(.+), name=(.+), topic=(.+), partition=(.+)><>Value
        name: kafka_log_$1_$2
        labels:
          topic: $3
          partition: $4
---
```

When i add [this configuration](https://github.com/bitnami/charts/issues/20491#issuecomment-1791074759) directly to a configmap, i can get the metrics.

Is there anything wrong with my configurations?
