### ISSUE TITLE
[wildfly] add possibility to enable debug port 

### ISSUE THREAD

**Issue by Xnyle** [bitnami/charts#2049]
The Wildfly chart is missing the option to enable debugging / the debugging port

I modified the chart as follows:

svcdebug:

```
{{- if and (.Values.debugMode) (eq .Values.debugMode true) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s-debug" .Release.Name .Chart.Name | quote}}
spec:
  type: LoadBalancer
  ports:
    - name: debug
      port: 8787
      targetPort: 8787
  selector: {{- include "wildfly.matchLabels" . | nindent 4 }}
{{- end }}
```

deployment:

```
          env:
            - name: DEBUG_PORT
              value: {{ default "*:8787" .Values.debugPort | quote }}
            - name: DEBUG
              value: {{ default "false" .Values.debugMode | quote }}
            - name: WILDFLY_USERNAME
              value: {{ default "" .Values.wildflyUsername | quote }}
            - name: WILDFLY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "wildfly.fullname" . }}
                  key: wildfly-password
          ports:
            - name: http
              containerPort: 8080
            - name: mgmt
              containerPort: 9990
            {{- if and (.Values.debugMode) (eq .Values.debugMode true) }}
            - name: debug
              containerPort: 8787
            {{- end }}
```
