### ISSUE TITLE
[bitnami/redis] Redis trying to use values from postgres

### ISSUE THREAD

**Issue by jankovicgd** [bitnami/charts#20504]
### Name and Version

bitnami/redis:17.17.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Using postgresql-12.5.6 & redis:17.17.1 (also tried 18.2.x & 18.1.x)
2. Values and chart below

`values.yaml`

```yml
global: ...

database:
  auth:
    username: dbuser
    password: dbpw
    database: dbname
    postgresPassword: dbpgpw
  primary:
    persistence:
      enabled: false
      existingClaim: data-access-db
    initdb:
      scripts:
        enablePostgis.sh: |
          echo "Enabling postgis"
          PGPASSWORD="${POSTGRES_POSTGRES_PASSWORD}" psql -U postgres -d "${POSTGRES_DB}" -c "CREATE EXTENSION postgis;"
  replicaCount: 1
  resources:
    limits:
      cpu: "1.5"
      memory: 6Gi
    requests:
      cpu: "0.1"
      memory: 0.5Gi
  affinity: {}

redis:
  auth:
    password: ""
  master:
    persistence:
      existingClaim: data-access-redis
      enabled: true
      storageClass: managed-nfs-storage
  architecture: standalone

... other values
```

Chart.yaml

```yaml
apiVersion: v2
name: vs
description: A Helm chart for a Kubernetes deployment of the View Server (VS)
type: application
version: "4.3.0"
appVersion: "4.3.0"
maintainers:
  - name: EOX IT Services GmbH
    url: https://eox.at
dependencies:
  - name: "postgresql"
    version: "12.5.6"
    repository: "https://charts.bitnami.com/bitnami"
    alias: database
  - name: "redis"
    version: "17.17.1"
    repository: "https://charts.bitnami.com/bitnami"
    alias: redis

```

3. run
```
helm template default path/to/chart
```

### What is the expected behavior?

Rendered templates

### What do you see instead?

```
Error: template: vs/charts/redis/templates/master/service.yaml:12:14: 
executing "vs/charts/redis/templates/master/service.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: 
error calling include: template: vs/charts/database/charts/common/templates/_labels.tpl:6:27: 
executing "common.labels.standard" at <include "common.names.name" .>: 
error calling include: template: vs/charts/database/charts/common/templates/_names.tpl:6:18: 
executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```

### Additional information

The chart was working prior but I wanted to update redis to a newer version (old was 10.9). Seems like the redis service.yaml is trying to use .tpl files from postgres.

Any help would be greatly appreciated. I am unsure if  this is a bug or something on my side.
