### ISSUE TITLE
No way to disable confirmation email?

### ISSUE THREAD

**Issue by jgreywolf** [bitnami/charts#20516]
### Name and Version

unknown

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm not sure that this is the right place to even post this - but I'm not sure where else to at this point.

How do you disable the email confirmation step for new users? 

If I were to use the base docker container from supabase. I could just set the following variables:

In docker-compose.yml => `GOTRUE_MAILER_AUTOCONFIRM: ${ENABLE_EMAIL_AUTOCONFIRM}`
in .env => `ENABLE_EMAIL_AUTOCONFIRM=true`

### What do you see instead?

But I have not been able to find any setting within the helm chart for supabase that seems to match these at all. What am I missing?

**Comment by migruiz4** [comment]
Hi @jgreywolf,

I'm sorry but reading your post it is unclear to me if you are using the `bitnami/supabase` helm chart.

If that is the case, you could modify the chart `values.yaml`:

```yaml
auth:
  defaultConfig: |
    GOTRUE_API_HOST: "0.0.0.0"
    GOTRUE_API_PORT: {{ .Values.auth.containerPorts.http | quote }}
    GOTRUE_SITE_URL: {{ include "supabase.studio.publicURL" . | quote }}
    GOTRUE_URI_ALLOW_LIST: "*"
    GOTRUE_DISABLE_SIGNUP: "false"
    GOTRUE_DB_DRIVER: "postgres"
    GOTRUE_JWT_DEFAULT_GROUP_NAME: "authenticated"
    GOTRUE_JWT_ADMIN_ROLES: "service_role"
    GOTRUE_JWT_AUD: "authenticated"
    GOTRUE_JWT_EXP: "3600"
    GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
    GOTRUE_MAILER_AUTOCONFIRM: "false" <--
    GOTRUE_SMTP_ADMIN_EMAIL: "your-mail@example.com"
    GOTRUE_SMTP_HOST: "smtp.example.com"
    GOTRUE_SMTP_PORT: "587"
    GOTRUE_SMTP_SENDER_NAME: "your-mail@example.com"
    GOTRUE_EXTERNAL_PHONE_ENABLED: "false"
    GOTRUE_SMS_AUTOCONFIRM: "false"
    GOTRUE_MAILER_URLPATHS_INVITE: "{{ include "supabase.studio.publicURL" . }}/auth/v1/verify"
    GOTRUE_MAILER_URLPATHS_CONFIRMATION: "{{ include "supabase.studio.publicURL" . }}/auth/v1/verify"
    GOTRUE_MAILER_URLPATHS_RECOVERY: "{{ include "supabase.studio.publicURL" . }}/auth/v1/verify"
    GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: "{{ include "supabase.studio.publicURL" . }}/auth/v1/verify"
```

Because `auth.defaultConfig` is a text value, you need to copy it entirely to override a single value.
