### ISSUE TITLE
[bitnami/mlflow] Invalid reference to containerSecurityContext in upgradeDBInitContainer template

### ISSUE THREAD

**Issue by mafs12** [bitnami/charts#20524]
### Name and Version

bitnami/mlflow 0.1.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I had previously installed chart version 0.1.2 (mlflow 2.7.1) with the custom values pasted in this issue, but with `runUpgradeDB: false`. Installed with  `helm upgrade --install mlflow mlflow  --repo https://charts.bitnami.com/bitnami  --version 0.1.2 --values mlflow-values.yaml --namespace mlflow  --create-namespace`

When upgrading to chart version 0.1.4 (mlflow 2.8.0) with the custom values pasted in this issue (`runUpgradeDB: true`) got the described error. Upgrade command:  `helm upgrade --install mlflow mlflow  --repo https://charts.bitnami.com/bitnami  --version 0.1.4 --values mlflow-values.yaml --namespace mlflow  --create-namespace`

### Are you using any custom parameters or values?

```yaml
## Global Docker image registry
global:
  imageRegistry: "" # OMMITED private image registry

## Bitnami MLflow image
## ref: https://hub.docker.com/r/bitnami/mlflow/tags/
image:
  ## Enable debug mode
  debug: false

## MLflow Tracking parameters
tracking:
  ## Enable Tracking server
  enabled: true
  ## Number of MLflow replicas to deploy
  replicaCount: 1
  ## MLflow resource requests and limits
  resources:
    limits: {}
    requests: {}
  ## Basic authentication
  auth:
    enabled: true
    username: ""
    password: ""
    existingSecret: "mlflow-admin-password"
    existingSecretUserKey: ""
    existingSecretPasswordKey: ""
    extraOverrides: {}
    overridesConfigMap: ""
  ## TLS configuration
  tls:
    ## Enable TLS traffic support
    enabled: false
  ## Add an init container to run `mlflow db upgrade`
  runUpgradeDB: true
  enableDefaultInitContainers: true
  ## MLflow service parameters
  service:
    ## MLflow service type
    type: ClusterIP
  ## MLflow ingress parameters
  ingress:
    ## Enable ingress record generation for MLflow
    enabled: false
  ## Enable persistence using Persistent Volume Claims
  persistence:
    ## Enable persistence using Persistent Volume Claims
    enabled: true
    accessModes:
      - ReadWriteOnce
    ## Size of data volume
    size: 8Gi
  ## MLflow Tracking Metrics Parameters
  metrics:
    ## Enable the export of Prometheus metrics
    enabled: false

## MLflow Run Parameters
run:
  ## Enable Run deployment
  enabled: false

## PostgreSQL chart configuration
## ref: https://github.com/bitnami/charts/blob/main/bitnami/postgresql
postgresql:
  enabled: true
  auth:
    username: "mlflow"
    database: mlflow
    existingSecret: "mlflow-postgresql-secret"
  architecture: standalone
  primary:
    service:
      type: ClusterIP
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 8Gi
    initdb:
      scripts:
        # For authentication, MLflow requires a different database in order to work
        create_auth_db.sh: |
          #!/bin/bash
          PGPASSWORD=$POSTGRES_POSTGRES_PASSWORD psql -U postgres <<< "CREATE DATABASE {{ include "mlflow.v0.database-auth.name" . }}"
          PGPASSWORD=$POSTGRES_POSTGRES_PASSWORD psql -U postgres <<< "GRANT ALL PRIVILEGES ON DATABASE {{ include "mlflow.v0.database-auth.name" . }} to {{ .Values.auth.username }}"
          PGPASSWORD=$POSTGRES_POSTGRES_PASSWORD psql -U postgres <<< "ALTER DATABASE {{ include "mlflow.v0.database-auth.name" . }} OWNER TO {{ .Values.auth.username }}"
  backup:
    enabled: false
  # serviceAccount:
    # create: true
  # rbac:
    # create: true
  metrics:
    enabled: false

## MinIO chart parameters
## ref: https://github.com/bitnami/charts/tree/main/bitnami/minio
minio:
  enabled: false

## External S3 parameters
externalS3:
  host: "minio.minio.svc.cluster.local"
  port: 9000
  accessKeyID: ""
  accessKeySecret: ""
  existingSecret: "mlflow-minio-secret"
  existingSecretAccessKeyIDKey: "root-user"
  existingSecretKeySecretKey: "root-password"
  protocol: "http"
  bucket: "mlruns"
```

### What is the expected behavior?

Helm installation succeeds.

### What do you see instead?

Error: UPGRADE FAILED: template: mlflow/templates/tracking/deployment.yaml:89:12: executing "mlflow/templates/tracking/deployment.yaml" at <include "mlflow.v0.tracking.upgradeDBInitContainer" .>: error calling include: template: mlflow/templates/_helpers.tpl:229:16: executing "mlflow.v0.tracking.upgradeDBInitContainer" at <.Values.containerSecurityContext.enabled>: nil pointer evaluating interface {}.enabled
