### ISSUE TITLE
Readiness and liveness probes randomly fail without cause

### ISSUE THREAD

**Issue by bramk** [bitnami/charts#20564]
### Name and Version

bitnami/zookeeper 12.1.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

On EKS with a statefulset with 3 replicas the liveness and readiness probes fail ever now and then.

This blog details the issue/solution: https://wolverineav.blog/tech/zookeeper-4-letter-word-netcat-no-response/

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Under normal operation, every `ruok` call should receive an `imok` response causing the probes to report healthy.

### What do you see instead?

Every now and then there is no response which results in the probes to reported as unhealthy.

### Additional information

Adding `-q 1` to the nc command resolves the issue.

```yaml
      customLivenessProbe: |
        failureThreshold: 6
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
        exec:
          command: ['/bin/bash', '-c', 'echo "ruok" | timeout 2 nc -w 2 -q 1 localhost 2181 | grep imok']
      customReadinessProbe: |
        failureThreshold: 6
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
        exec:
          command: ['/bin/bash', '-c', 'echo "ruok" | timeout 2 nc -w 2 -q 1 localhost 2181 | grep imok']
```
