### ISSUE TITLE
[bitnami/etcd] Scale from 0 or 1 for replica lost data

### ISSUE THREAD

**Issue by alisre** [bitnami/charts#20579]
### Name and Version

bitnami/etcd 9.6.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Start new  etcd node
`helm install etcd-test bitnami/etcd --set auth.rbac.create=false --set replicaCount=1 --set persistence.enabled=true --set global.storageClass=disk `
2. Wait the etcd installation is finished
3. write the data to etcd
`etcdctl put foo "hello world";
etcdctl  get foo 
hello world`
4. Scale down to 0
5. Scale up again to 1
6. etcd running and get foo but nothing
`
etcdctl  get foo 
`

### Are you using any custom parameters or values?
```yaml
auth:
  rbac:
    create: true
    allowNoneAuthentication: true
    rootPassword: "abc_@%yRGxGV0Y_%@ABC"
  token:
    enabled: false
    type: simple
autoCompactionMode: "periodic"
autoCompactionRetention: "24"
initialClusterState: "new"
initialClusterToken: "etcd-cluster-k8s"
removeMemberOnContainerTermination: true
extraEnvVars:
  - name: ETCD_MAX_REQUEST_BYTES
    value: "10485760"
  - name: ETCD_QUOTA_BACKEND_BYTES
    value: "8589934592"
  - name: ETCD_HEARTBEAT_INTERVAL
    value: "150"
  - name: ETCD_EXPERIMENTAL_BACKEND_BBOLT_FREELIST_TYPE
    value: map
replicaCount: 1
podManagementPolicy: Parallel
```
### What is the expected behavior?

etcd will not lost data

### What do you see instead?

etcd lost data
