### ISSUE TITLE
`render-auth-conf` container of `tracking` POD fails to start with "Error: secret "<release_name>-externaldb" not found"

### ISSUE THREAD

**Issue by ogusak** [bitnami/charts#20581]
### Name and Version

bitnami/mlflow 0.1.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Our deployment consists of AWS EKS cluster external DB (Postgres RDS) and S3 bucket.
The values file is configured to use external RDS, with the internal to the chart Postgres DB deployment disabled.

### Are you using any custom parameters or values?

Yes:
```yaml
postgresql:
  enabled: false

# ...

externalDatabase:
  host: "<hostname>"
  port: 5432
  user: "user"
  database: mlflow
  authDatabase: mlflow_auth
  password: "password"
  existingSecret: ""
  existingSecretPasswordKey: "db-password"
```

### What is the expected behavior?

deployment of tracking pod should succeed

### What do you see instead?

Deployment of `tracking` pod fails at the init container `render-auth-conf` cannot start.

### Additional information

The reason this happens is due to incorrect [name](https://github.com/bitnami/charts/blob/main/bitnami/mlflow/templates/tracking/externaldb-secret.yaml#L10) of the `secret` template defined in the `tracking` chart:
```yaml
metadata:
  name: {{ printf "%s-externaldb" (include "mlflow.v0.tracking.fullname" .) | trunc 63 | trimSuffix "-" }}
```

Instead, the name's value should be taken from the value defined in the [helper template](https://github.com/bitnami/charts/blob/main/bitnami/mlflow/templates/_helpers.tpl#L459C1-L459C1): 
```
{{- define "mlflow.v0.database.secretName" -}}
```
which is also used in the definition of the init containers of the `tracking` pod. Hence the error.
