### ISSUE TITLE
Unknown field "enabled" in io.k8s.api.core.v1.SecurityContext

### ISSUE THREAD

**Issue by JakobHtz** [bitnami/charts#20594]
### Name and Version

bitnami/mongodb

### What architecture are you using?

None

### What steps will reproduce the bug?

1. run:
`helm upgrade -i mongodb-backup-test -f values.yaml bitnami/mongodb`
2. get error:  
`Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(CronJob.spec.jobTemplate.spec.template.spec.containers[0].securityContext): unknown field "enabled" in io.k8s.api.core.v1.SecurityContext`

### Are you using any custom parameters or values?

Used values:
```YAML
auth:
  enabled: false
  
persistence: 
  enabled: true
  resourcePolicy: "keep"
  storageClass: "block"

architecture: "replicaset"

replicaCount: 3

containerSecurityContext:
  enabled: false

podSecurityContext:
  enabled: false

backup: 
  enabled: true
  cronjob: 
    storage:
      storageClass: "block"
      size: 50Gi
    containerSecurityContext:
      enabled: false

externalAccess: 
  enabled: false 
```

### What is the expected behavior?

I expected it to install the chart without validation error.

### What do you see instead?

`Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(CronJob.spec.jobTemplate.spec.template.spec.containers[0].securityContext): unknown field "enabled" in io.k8s.api.core.v1.SecurityContext`

### Additional information

Validation failed for me independent of enabled being set to false or true. 
I fixed it for me locally by adding a conditional around the Security Policy and remove the enable field afterwards:
```YAML
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - ...
            {{- if .Values.backup.cronjob.containerSecurityContext.enabled }}
            {{ $securityContext := .Values.backup.cronjob.containerSecurityContext }}
            {{ unset $securityContext "enabled" }}
            securityContext:
              {{- include "common.tplvalues.render" ( dict "value" $securityContext "context" $) | nindent 14 }}
            {{- end }}
```

Here's some info about the versions I'm running.
```JSON
{
  "clientVersion": {
    "major": "1",
    "minor": "26",
    "gitVersion": "v1.26.0",
    "gitCommit": "b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d",
    "gitTreeState": "clean",
    "buildDate": "2022-12-08T19:58:30Z",
    "goVersion": "go1.19.4",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v4.5.7",
  "serverVersion": {
    "major": "1",
    "minor": "24",
    "gitVersion": "v1.24.6",
    "gitCommit": "b39bf148cd654599a52e867485c02c4f9d28b312",
    "gitTreeState": "clean",
    "buildDate": "2022-09-21T13:12:04Z",
    "goVersion": "go1.18.6",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```
