### ISSUE TITLE
Fresh installation of kube-prometheus 8.22.0 + bitnami/thanos 12.13.13 yields minio permission denied error 

### ISSUE THREAD

**Issue by lony** [bitnami/charts#20598]
### Name and Version

bitnami/thanos 12.13.13

### What architecture are you using?

amd64

#### I Setup bitnami/kube-prometheus 8.22.0

1. Create new folder and add Chart.yaml

```yaml
apiVersion: v2
name: thanos-chart
version: 1.0.0

dependencies:
  - name: kube-prometheus
    version: 8.22.0
    repository: https://charts.bitnami.com/bitnami
```
2. Add values.yaml file

```yaml
kube-prometheus:
  prometheus:
    thanos:
      create: true
```
3. Create namespace thanos
4. Run `helm install --namespace thanos thanos-inst .`

#### II Setup bitnami/thanos 12.13.13 (inside same meta chart)

1. Create a new folder and add Chart.yaml

```yaml
apiVersion: v2
name: thanos-chart
version: 1.0.0

dependencies:
  - name: kube-prometheus
    version: 8.22.0
    repository: https://charts.bitnami.com/bitnami
  - name: thanos
    version: 12.13.13
    repository: https://charts.bitnami.com/bitnami
```
2. Add values.yaml file

```yaml
thanos:
  objstoreConfig: |-
    type: s3
    config:
      bucket: thanos
      endpoint: {{ include "thanos.minio.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:9000
      access_key: minio
      secret_key: minio123
      insecure: true
  query:
    dnsDiscovery:
      sidecarsService: kube-prometheus-prometheus-thanos
      sidecarsNamespace: thanos
  bucketweb:
    enabled: true
  compactor:
    enabled: true
  storegateway:
    enabled: true
  ruler:
    enabled: true
    alertmanagers:
      - http://kube-prometheus-alertmanager.thanos.svc.cluster.local:9093
    config: |-
      groups:
        - name: "metamonitoring"
          rules:
            - alert: "PrometheusDown"
              expr: absent(up{prometheus="thanos/kube-prometheus"})
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  minio:
    enabled: true
    auth:
      rootPassword: minio123
      rootUser: minio
    monitoringBuckets: thanos
    accessKey:
      password: minio
    secretKey:
      password: minio123
  volumePermissions:
    enabled: true
```
3. Create namespace thanos
4. Run `helm install --namespace thanos thanos-inst .`

### Are you using any custom parameters or values?

```yaml
kube-prometheus:
  prometheus:
    thanos:
      create: true

thanos:
  objstoreConfig: |-
    type: s3
    config:
      bucket: thanos
      endpoint: {{ include "thanos.minio.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:9000
      access_key: minio
      secret_key: minio123
      insecure: true
  query:
    dnsDiscovery:
      sidecarsService: kube-prometheus-prometheus-thanos
      sidecarsNamespace: thanos
  bucketweb:
    enabled: true
  compactor:
    enabled: true
  storegateway:
    enabled: true
  ruler:
    enabled: true
    alertmanagers:
      - http://kube-prometheus-alertmanager.thanos.svc.cluster.local:9093
    config: |-
      groups:
        - name: "metamonitoring"
          rules:
            - alert: "PrometheusDown"
              expr: absent(up{prometheus="thanos/kube-prometheus"})
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  minio:
    enabled: true
    auth:
      rootPassword: minio123
      rootUser: minio
    monitoringBuckets: thanos
    accessKey:
      password: minio
    secretKey:
      password: minio123
  volumePermissions:
    enabled: true
```

### What is the expected behavior?

Everything is running and has the Running status

### What do you see instead?

minio and storegateway pod are stuck in CrashLoopBackOff state

minio log

```
 20:53:03.97 
 20:53:03.97 Welcome to the Bitnami minio container
 20:53:03.97 Subscribe to project updates by watching https://github.com/bitnami/containers
 20:53:03.98 Submit issues and feature requests at https://github.com/bitnami/containers/issues
 20:53:03.98 
 20:53:03.98 INFO  ==> ** Starting MinIO setup **
/opt/bitnami/scripts/libminio.sh: line 364: /bitnami/minio/data/.root_user: Permission denied
Stream closed EOF for thanos/thanos-inst-minio-59785f96cd-4p8nv (minio)
```              

storegateway log

```
ts=2023-11-02T20:52:36.99920273Z caller=factory.go:53 level=info msg="loading bucket configuration"
ts=2023-11-02T20:52:36.99961213Z caller=inmemory.go:179 level=info msg="created in-memory index cache" maxItemSizeBytes=131072000 maxSizeBytes=262144000 maxItems=maxInt
ts=2023-11-02T20:52:36.999994116Z caller=options.go:26 level=info protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
ts=2023-11-02T20:52:37.001122643Z caller=store.go:520 level=info msg="starting store node"
ts=2023-11-02T20:52:37.001223879Z caller=store.go:418 level=info msg="initializing bucket store"
ts=2023-11-02T20:52:37.001344528Z caller=intrumentation.go:75 level=info msg="changing probe status" status=healthy
ts=2023-11-02T20:52:37.001397229Z caller=http.go:73 level=info service=http/server component=store msg="listening for requests and metrics" address=0.0.0.0:10902
ts=2023-11-02T20:52:37.001640506Z caller=tls_config.go:274 level=info service=http/server component=store msg="Listening on" address=:10902
ts=2023-11-02T20:52:37.001701496Z caller=tls_config.go:277 level=info service=http/server component=store msg="TLS is disabled." http2=false address=:10902
ts=2023-11-02T20:53:07.007659115Z caller=intrumentation.go:67 level=warn msg="changing probe status" status=not-ready reason="bucket store initial sync: sync block: BaseFetcher: iter bucket: Get \"http://thanos-inst-minio.thanos.svc.cluster.local:9000/thanos/?location=\": dial tcp 10.254.56.164:9000: connect: connection refused"
ts=2023-11-02T20:53:07.007717509Z caller=http.go:91 level=info service=http/server component=store msg="internal server is shutting down" err="bucket store initial sync: sync block: BaseFetcher: iter bucket: Get \"http://thanos-inst-minio.thanos.svc.cluster.local:9000/thanos/?location=\": dial tcp 10.254.56.164:9000: connect: connection refused"
ts=2023-11-02T20:53:07.007806312Z caller=intrumentation.go:56 level=info msg="changing probe status" status=ready
ts=2023-11-02T20:53:07.007845938Z caller=grpc.go:131 level=info service=gRPC/server component=store msg="listening for serving gRPC" address=0.0.0.0:10901
ts=2023-11-02T20:53:07.007933997Z caller=http.go:110 level=info service=http/server component=store msg="internal server is shutdown gracefully" err="bucket store initial sync: sync block: BaseFetcher: iter bucket: Get \"http://thanos-inst-minio.thanos.svc.cluster.local:9000/thanos/?location=\": dial tcp 10.254.56.164:9000: connect: connection refused"
ts=2023-11-02T20:53:07.007964385Z caller=intrumentation.go:81 level=info msg="changing probe status" status=not-healthy reason="bucket store initial sync: sync block: BaseFetcher: iter bucket: Get \"http://thanos-inst-minio.thanos.svc.cluster.local:9000/thanos/?location=\": dial tcp 10.254.56.164:9000: connect: connection refused"
ts=2023-11-02T20:53:07.008012055Z caller=intrumentation.go:67 level=warn msg="changing probe status" status=not-ready reason="bucket store initial sync: sync block: BaseFetcher: iter bucket: Get \"http://thanos-inst-minio.thanos.svc.cluster.local:9000/thanos/?location=\": dial tcp 10.254.56.164:9000: connect: connection refused"
ts=2023-11-02T20:53:07.008031272Z caller=grpc.go:138 level=info service=gRPC/server component=store msg="internal server is shutting down" err="bucket store initial sync: sync block: BaseFetcher: iter bucket: Get \"http://thanos-inst-minio.thanos.svc.cluster.local:9000/thanos/?location=\": dial tcp 10.254.56.164:9000: connect: connection refused"
ts=2023-11-02T20:53:07.00805076Z caller=grpc.go:151 level=info service=gRPC/server component=store msg="gracefully stopping internal server"
ts=2023-11-02T20:53:07.00808318Z caller=grpc.go:164 level=info service=gRPC/server component=store msg="internal server is shutdown gracefully" err="bucket store initial sync: sync block: BaseFetcher: iter bucket: Get \"http://thanos-inst-minio.thanos.svc.cluster.local:9000/thanos/?location=\": dial tcp 10.254.56.164:9000: connect: connection refused"
ts=2023-11-02T20:53:07.008216672Z caller=main.go:161 level=error err="Get \"http://thanos-inst-minio.thanos.svc.cluster.local:9000/thanos/?location=\": dial tcp 10.254.56.164:9000: connect: connection refused\nBaseFetcher: iter bucket\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetchMetadata\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:383\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch.func2\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:456\ngithub.com/golang/groupcache/singleflight.(*Group).Do\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/pkg/mod/github.com/golang/groupcache@v0.0.0-20210331224755-41bb18bfe9da/singleflight/singleflight.go:56\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:454\ngithub.com/thanos-io/thanos/pkg/block.(*MetaFetcher).Fetch\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:514\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).SyncBlocks\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/src/github.com/thanos-io/thanos/pkg/store/bucket.go:556\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).InitialSync\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/src/github.com/thanos-io/thanos/pkg/store/bucket.go:625\nmain.runStore.func5.1\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/src/github.com/thanos-io/thanos/cmd/thanos/store.go:427\ngithub.com/thanos-io/thanos/pkg/runutil.RetryWithLog\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/src/github.com/thanos-io/thanos/pkg/runutil/runutil.go:97\ngithub.com/thanos-io/thanos/pkg/runutil.Retry\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/src/github.com/thanos-io/thanos/pkg/runutil/runutil.go:87\nmain.runStore.func5\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/src/github.com/thanos-io/thanos/cmd/thanos/store.go:426\ngithub.com/oklog/run.(*Group).Run.func1\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/opt/bitnami/go/src/runtime/asm_amd64.s:1598\nsync block\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).InitialSync\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/src/github.com/thanos-io/thanos/pkg/store/bucket.go:626\nmain.runStore.func5.1\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/src/github.com/thanos-io/thanos/cmd/thanos/store.go:427\ngithub.com/thanos-io/thanos/pkg/runutil.RetryWithLog\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/src/github.com/thanos-io/thanos/pkg/runutil/runutil.go:97\ngithub.com/thanos-io/thanos/pkg/runutil.Retry\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/src/github.com/thanos-io/thanos/pkg/runutil/runutil.go:87\nmain.runStore.func5\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/src/github.com/thanos-io/thanos/cmd/thanos/store.go:426\ngithub.com/oklog/run.(*Group).Run.func1\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/opt/bitnami/go/src/runtime/asm_amd64.s:1598\nbucket store initial sync\nmain.runStore.func5\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/src/github.com/thanos-io/thanos/cmd/thanos/store.go:432\ngithub.com/oklog/run.(*Group).Run.func1\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/opt/bitnami/go/src/runtime/asm_amd64.s:1598\nstore command failed\nmain.main\n\t/bitnami/blacksmith-sandox/thanos-0.32.5/src/github.com/thanos-io/thanos/cmd/thanos/main.go:161\nruntime.main\n\t/opt/bitnami/go/src/runtime/proc.go:250\nruntime.goexit\n\t/opt/bitnami/go/src/runtime/asm_amd64.s:1598"
Stream closed EOF for thanos/thanos-inst-storegateway-0 (storegateway)
```

### Additional information

I run on a Kubernetes 1.28.3 based on OpenStack.
My standard storage provisioner is cinder.csi.openstack.org
