### ISSUE TITLE
Error in SCHEMA_REGISTRY_KAFKA_BROKERS value generation

### ISSUE THREAD

**Issue by MarcTerrasson** [bitnami/charts#20603]
### Name and Version

bitnamicharts/schema-registry:16.2.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. `helm template kafka oci://registry-1.docker.io/bitnamicharts/schema-registry --namespace my-kafka > template.yaml`
2. open template.yaml, l.677 : 
```yaml
            - name: SCHEMA_REGISTRY_KAFKA_BROKERS
              value: "PLAINTEXT://kafka-kafka-controller-0.kafka-kafka-controller-headless.my-kafka.svc.cluster.local:9092"
```
3. See the service and the pod name
```yaml
kind: Service
metadata:
  name: kafka-controller-headless
  namespace: "my-kafka"
---
kind: StatefulSet
metadata:
  name: kafka-controller
```

### Are you using any custom parameters or values?

N/A

### What is the expected behavior?

The value of `SCHEMA_REGISTRY_KAFKA_BROKERS` is correct

### What do you see instead?

```yaml
            - name: SCHEMA_REGISTRY_KAFKA_BROKERS
              value: "PLAINTEXT://kafka-kafka-controller-0.kafka-kafka-controller-headless.my-kafka.svc.cluster.local:9092"
```
