### ISSUE TITLE
[bitnami/grafana] Grafana Chart will ALWAYS fail if replicaCount is greater then one due to faulty validation.

### ISSUE THREAD

**Issue by ruifung** [bitnami/charts#20629]
### Name and Version

bitnami/grafana:9.5.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy grafana helm chart with replicaSet > 1.
2. Watch as deployment fails due to faulty validation.

### Are you using any custom parameters or values?

```yaml
    persistence:
      accessMode: ReadWriteMany
      storageClass: cephfs
    grafana:
      replicaCount: 2
      nodeSelector:
        kubernetes.io/os: linux
        location: homelab
      updateStrategy:
        type: Recreate
      extraEnvVarsSecret: "grafana-config"
      extraVolumes:
        - name: db-config
          secret:
            secretName: postgres-ha-pguser-grafana
            optional: false
      extraVolumeMounts:
        - name: db-config
          mountPath: /db-config
          readOnly: true
    config:
      useGrafanaIniFile: true
      grafanaIniConfigMap: "grafana-config"
    ingress:
      enabled: true
      pathType: Prefix
      hostname: grafana.example.com
      tls: false
      extraTls:
      - hosts:
        - grafana.example.com
        secretName: grafana-cert
      ingressClassName: traefik
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
      prometheusRule:
        enabled: false
        namespace: monitoring
        rules:
          - alert: Grafana-Down
            annotations:
              message: "Grafana instance is down"
              summary: Grafana instance is down
            expr: absent(up{job="grafana"} == 1)
            labels:
              severity: warning
              service: grafana
            for: 5m
```

### What is the expected behavior?

For it to successfully deploy.

### What do you see instead?

execution error at (grafana/templates/NOTES.txt:32:3): VALUES VALIDATION: grafana: replicaCount Using more than one replica requires using an external database to share data between Grafana instances. By default Grafana uses an internal sqlite3 per instance but you can configure an external MySQL or PostgreSQL. Please, ensure you provide a configuration file configuring the external database to share data between replicas.

### Additional information

I'm pretty sure that's supposed to be a warning, but due to the checks at https://github.com/bitnami/charts/blob/e748cd1b3eda066812df1b8dccaec36e755438ec/bitnami/grafana/templates/_helpers.tpl#L176-L190 and https://github.com/bitnami/charts/blob/e748cd1b3eda066812df1b8dccaec36e755438ec/bitnami/grafana/templates/_helpers.tpl#L228-L236
It will ALWAYS fail if replicaCount is greater than 1.

Commit history shows that this was previously fixed around 1 year ago, and reintroduced in commit https://github.com/bitnami/charts/commit/1ceda9c8b7a85312c666844e47ddc23c2713bb0b
