### ISSUE TITLE
[postgresql] NodePort + Relication fails

### ISSUE THREAD

**Issue by kav** [bitnami/charts#2063]
**Which chart**:
postgresql 8.6.4

**Description**
Running install with the following values fails:
```yaml
service:
  type: NodePort
  nodePort: 30042
replication:
  enabled: true
  slaveReplicas: 2
```
due to a collision in the nodePort for the master and slave services.

I'd propose a master.nodePort and slave.nodePort _but_ it occurs to me one might want master and slaves running different service types. We've also got that use case as master gets fed outside the cluster and the slaves serve internal workloads so given that I'd propose service entries under master and slave that override the top level service entry if present.

If that sounds reasonable I'll get to work on a PR.

Example proposed:
```yaml
service:
  type: NodePort
  nodePort: 30042
replication:
  enabled: true
  slaveReplicas: 2
slave:
  service:
    nodePort: 30043
```
alternatively expressible as:
```yaml
service:
  type: NodePort
replication:
  enabled: true
  slaveReplicas: 2
master:
  service:
    nodePort: 30042
slave:
  service:
    nodePort: 30043
```
More complex example:
```yaml
replication:
  enabled: true
  slaveReplicas: 2
master:
  service:
    type: NodePort
    nodePort: 30042
slave:
  service:
    type: ClusterIP
```

**Comment by miguelaeh** [comment]
Hi @kav ,
Thank you very much for reporting this and for offering you to create a PR!!!,
It would be great if you can open the PR. I would say to use the lat example you posted. I.e. having:
```
master:
  service:
    type: NodePort
    nodePort: 30042
slave:
  service:
    type: ClusterIP
    nodePort: 30043
```

In order to do that you will need to separated the service in two service one for the master and another one for the slaves, and replicate the following structure into the aster and into the slave:
```
## PostgreSQL service configuration
service:
  ## PosgresSQL service type
  type: ClusterIP
  # clusterIP: None
  port: 5432

  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  # nodePort:

  ## Provide any additional annotations which may be required.
  ## The value is evaluated as a template, so, for example, the value can depend on .Release or .Chart
  annotations: {}
  ## Set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  # loadBalancerIP:

  ## Load Balancer sources
  ## https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
  ##
  # loadBalancerSourceRanges:
  # - 10.10.10.0/24
```
