### ISSUE TITLE
[Redis] Unable to connect to MASTER: Resource temporarily unavailable

### ISSUE THREAD

**Issue by arianf** [bitnami/charts#2064]
**Which chart**: `redis` and `appVersion: 5.0.7`

**Description**

When deploying with NetworkPolicy turned on, I get the following in the `redis-slave-0` logs:

```
$ kubectl logs redis-slave-0 

 02:08:21.90 INFO  ==> ** Starting Redis **
1:C 17 Mar 2020 02:08:21.914 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 17 Mar 2020 02:08:21.914 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 17 Mar 2020 02:08:21.914 # Configuration loaded
1:S 17 Mar 2020 02:08:21.915 * Running mode=standalone, port=6379.
1:S 17 Mar 2020 02:08:21.915 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:S 17 Mar 2020 02:08:21.915 # Server initialized
1:S 17 Mar 2020 02:08:21.915 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:S 17 Mar 2020 02:08:21.916 * Ready to accept connections
1:S 17 Mar 2020 02:08:21.917 * Connecting to MASTER redis-master-0.redis-headless.sentry-production.svc.cluster.local:6379
1:S 17 Mar 2020 02:08:22.322 # Unable to connect to MASTER: Resource temporarily unavailable
1:S 17 Mar 2020 02:08:23.326 * Connecting to MASTER redis-master-0.redis-headless.sentry-production.svc.cluster.local:6379
1:S 17 Mar 2020 02:08:23.451 # Unable to connect to MASTER: Resource temporarily unavailable
1:S 17 Mar 2020 02:08:24.454 * Connecting to MASTER redis-master-0.redis-headless.sentry-production.svc.cluster.local:6379
1:S 17 Mar 2020 02:08:24.461 # Unable to connect to MASTER: Resource temporarily unavailable
1:S 17 Mar 2020 02:08:25.465 * Connecting to MASTER redis-master-0.redis-headless.sentry-production.svc.cluster.local:6379
1:S 17 Mar 2020 02:08:25.471 # Unable to connect to MASTER: Resource temporarily unavailable
1:S 17 Mar 2020 02:08:26.474 * Connecting to MASTER redis-master-0.redis-headless.sentry-production.svc.cluster.local:6379
1:S 17 Mar 2020 02:08:26.479 # Unable to connect to MASTER: Resource temporarily unavailable
1:S 17 Mar 2020 02:08:27.481 * Connecting to MASTER redis-master-0.redis-headless.sentry-production.svc.cluster.local:6379
1:S 17 Mar 2020 02:08:27.491 # Unable to connect to MASTER: Resource temporarily unavailable
```

**Steps to reproduce the issue:**

1. `helm install .`
2. that's it

**Describe the results you received:**

```
NAME                 READY  STATUS   RESTARTS  AGE   IP             NODE 
pod/redis-master-0   1/1    Running  0         31m   172.20.87.38   node090.some.url.com
pod/redis-slave-0    0/1    Running  0         31m   172.20.87.30   node090.some.url.com


NAME                     TYPE        CLUSTER-IP        EXTERNAL-IP   PORT(S)   AGE   SELECTOR
service/redis-headless   ClusterIP   None              <none>        6379/TCP  31m   app=redis,release=sentry-db
service/redis-master     ClusterIP   192.168.108.128   <none>        6379/TCP  31m   app=redis,release=sentry-db,role=master
service/redis-slave      ClusterIP   192.168.246.14    <none>        6379/TCP  31m   app=redis,release=sentry-db,role=slave
```

**Describe the results you expected:**

I expected the slave to connect to master

**Additional information you deem important (e.g. issue happens only occasionally):**

It happens every time. My clusters ingress and egress is set to deny all by default

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by miguelaeh** [comment]
Hi @arianf
Could you check if the NetworkPolicy was correctly created?
```
kubectl get networkpolicy
```

**Comment by arianf** [comment]
```
$ kubectl get networkpolicy
redis                          app=redis,release=sentry-db                 2m
```


```
$ kubectl get networkpolicy/redis -o yaml 

apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2020-03-17T19:54:51Z"
  generation: 1
  labels:
    app: redis
    chart: redis-10.3.3
    heritage: Helm
    release: sentry-db
  name: redis
  namespace: sentry-production
  resourceVersion: "1616610230"
  selfLink: /apis/extensions/v1beta1/namespaces/sentry-production/networkpolicies/redis
  uid: 29f12a65-6889-11ea-9fbb-040973d6aa84
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
  - ports:
    - port: 6379
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: redis
          release: sentry-db
  ingress:
  - from:
    - podSelector:
        matchLabels:
          redis-client: "true"
    - podSelector:
        matchLabels:
          app: redis
          release: sentry-db
    ports:
    - port: 6379
      protocol: TCP
  podSelector:
    matchLabels:
      app: redis
      release: sentry-db
  policyTypes:
  - Ingress
  - Egress
```

**Comment by miguelaeh** [comment]
Hi @arianf ,
I was checking the issue and I found in the network policy that the `-client` label should be set to be able to access to Redis. Also, after installing the chart you will see some comments that come from the NOTES.txt that says something like this:
```
Note: Since NetworkPolicy is enabled, only pods with label
redis-client=true"
will be able to connect to redis.
```

It can change depending on your release name.

Could you try to label your pods with the specified label that appear when you install the chart?

**Comment by arianf** [comment]
@miguelaeh does the `redis-slave-0` pod not come with the `redis-client=true` label by default?

**Comment by arianf** [comment]
I've ran:

```
kubectl label pods redis-slave-0 redis-client=true
```

`kubectl get pods/redis-slave-0 -o yaml`
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/configmap: 9e999a38483e23dbb8fab75156655b06153a5175bd3b7eba42d33e1d249a9942
    checksum/health: f5b81bccc9b8e192ea23a1dd6434be14bafe0f4d21161cfdeb10b26f28d94a0c
    checksum/secret: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    cni.projectcalico.org/podIP: 172.20.123.38/32
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, ephemeral-storage, memory
      request for container redis; cpu, ephemeral-storage, memory limit for container
      redis'
  creationTimestamp: "2020-03-17T19:54:52Z"
  generateName: redis-slave-
  labels:
    app: redis
    chart: redis-10.3.3
    controller-revision-hash: redis-slave-5445547d68
    redis-client: "true"
    release: sentry-db
    role: slave
    statefulset.kubernetes.io/pod-name: redis-slave-0
  name: redis-slave-0
  namespace: sentry-production
```

Nothing changed:

```
1:S 19 Mar 2020 03:17:34.812 * Ready to accept connections
1:S 19 Mar 2020 03:17:34.813 * Connecting to MASTER redis-master-0.redis-headless.sentry-production.svc.cluster.local:6379
1:S 19 Mar 2020 03:17:34.818 # Unable to connect to MASTER: Resource temporarily unavailable
1:S 19 Mar 2020 03:17:35.820 * Connecting to MASTER redis-master-0.redis-headless.sentry-production.svc.cluster.local:6379
1:S 19 Mar 2020 03:17:35.825 # Unable to connect to MASTER: Resource temporarily unavailable
```
