### ISSUE TITLE
[bitnami/kafka] Can't set resources on init container with chart 24.0.0

### ISSUE THREAD

**Issue by fouadsemaan** [bitnami/charts#20641]
### Name and Version

bitnami/kafka 24.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I can't deploy Kafka in the presence of a namespace resource quota since the cart won't allow me to set resources for the Kafka init containers. This specifically happens when I turn on TLS for external access.

The function doesn't allow to set resources: https://github.com/bitnami/charts/blob/main/bitnami/kafka/templates/_helpers.tpl#L736

I may have missed it but don't see a way to set them.

### Are you using any custom parameters or values?
```
kraft:
  enabled: true
listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    external:
      protocol: TLS
tls:
    externalClientProtocol: tls
    password: mydirtylittlesecret
    existingSecret: "" # previously an array --> ["my-kafka-0-pem","my-kafka-1-pem","my-kafka-2-pem"]
    jksTruststore: truststore.jks
    jksKeystoreSAN: keystore.jks
```
### What is the expected behavior?

I expect to be given the option to set resources on the init container.

### What do you see instead?

I get an error that the pods cannot deployed because of requirement to set resources on the kafka init container.

**Comment by opencmit2** [comment]
Hi @javsalgar 
please assign to me.

I set up a kafkaInitContainerResources in the broker and controller respectively. Is it reasonable?
Examples are as follows：
```yaml
broker:
  kafkaInitContainerResources:
    requests:
      memory: "128Mi" 
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
```
