### ISSUE TITLE
[bitnami/mlflow] Error while setting selector on ServiceMonitor

### ISSUE THREAD

**Issue by fcecagno** [bitnami/charts#20668]
### Name and Version

bitnami/mlflow 0.2.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Regular setup with `tracking.metrics.serviceMonitor.selector` set.

### Are you using any custom parameters or values?

```yaml
tracking:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      selector:
        monitoring: prometheus
```

### What do you see instead?

```
Helm upgrade failed: failed to create resource: ServiceMonitor.monitoring.coreos.com "mlflow-tracking" is invalid: spec.endpoints[0].port: Invalid value: "integer": spec.endpoints[0].port in body must be of type string: "integer"
```

### Additional information

This is the default value that should be used as `spec.endpoints[0].port`: https://github.com/bitnami/charts/blob/main/bitnami/mlflow/values.yaml#L473
It seems like the calculated value is the string "integer".
