### ISSUE TITLE
[bitnami/mlflow] Error while creating ingress with annotations

### ISSUE THREAD

**Issue by fcecagno** [bitnami/charts#20660]
### Name and Version

bitnami/mlflow 0.2.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Regular setup with `tracking.ingress.annotations` set.

### Are you using any custom parameters or values?

```
tracking:
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
```

### What is the expected behavior?

Ingress with the above annotations.

### What do you see instead?

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    Error: 'error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string
      into Go value of type map[string]interface {}'
```
