### ISSUE TITLE
[Bitnami/Kafka] v24.0.0 advertised listeners override no longer interpolated at runtime

### ISSUE THREAD

**Issue by fouadsemaan** [bitnami/charts#20677]
### Name and Version

bitnami/kafka 24.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```yaml
kraft:
  enabled: true
listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    external:
      protocol: TLS
tls:
    externalClientProtocol: tls
    password: mydirtylittlesecret
    existingSecret: "" # previously an array --> ["my-kafka-0-pem","my-kafka-1-pem","my-kafka-2-pem"]
    jksTruststore: truststore.jks
    jksKeystoreSAN: keystore.jks
```
### Are you using any custom parameters or values?

Prior to chart version 24.0.0 we had taken advantage of the advertisedListeners override to be able to resolve DNS names outside of the kafka chart, i.e. consul/istio ingress level. To do that we needed to specify individual domain names for each broker with an ordinal index solved at runtime. Unfortunately, while the override is still available, it is no longer interpolated and is taken as ie, values such as ${MY_POD_NAME} are copied as such in the server properties.

In the prior version, the override was interpolated at runtime in a script called `setup.sh` from the main container. 

I saw there was a way to specify a list of load balancer names but only if you use LoadBalancer type for your service which we don't want to do as the load balancing aspect of Kafka is delegated to an ingress (consul/istio).

### What is the expected behavior?

Restore the ability to interpolate the advertisedListeners value at runtime.

### What do you see instead?

Unable to correctly override advertisedListeners.
