### ISSUE TITLE
[bitnami/nginx] 15.4.0 breaks cloneStaticSiteFromGit (dubious ownership in repository at '/app')

### ISSUE THREAD

**Issue by Cogitri** [bitnami/charts#20682]
### Name and Version

bitnami/nginx 15.4.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Setup nginx with the values.yml below (and version >=15.4.0). The same config works with 15.3.0

### Are you using any custom parameters or values?

```yaml
cloneStaticSiteFromGit:
  enabled: true
  repository: <repo>
  branch: master
  interval: 15
```

### What is the expected behavior?

Synching should work

### What do you see instead?

Starting with 15.4.0, the following error is logged by the git-repo-syncher:

```
fatal: detected dubious ownership in repository at '/app'
```
