### ISSUE TITLE
Cannot disable persistence with official postgres image

### ISSUE THREAD

**Issue by hammady** [bitnami/charts#20814]
### Name and Version

bitnami/postgresql 13.2.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Try installing using this command:
```bash
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install my-volatile-pg bitnami/postgresql -f bitnami-bug-values.yaml
```
Where `bitnami-bug-values.yaml` is:
```yaml
primary:
  persistence:
    enabled: false
image:
  registry:
  repository: docker.io/postgres
  tag: 16.0-bullseye
```
The pod crashes with the below error:
```
mkdir: cannot create directory ‘/bitnami’: Permission denied
```
Inspect the pod and observe `volumeMounts` does not include the data dir even though there is an EmptyDir volume created, albeit not used.
Now add the mount manually as in:
```yaml
primary:
  persistence:
    enabled: false
  extraVolumeMounts:
    - name: data
      mountPath: /bitnami/postgresql
image:
  registry:
  repository: docker.io/postgres
  tag: 16.0-bullseye
```
And install again. Everything now works fine and inspecting the pod shows the created mount.

This does not happen in the bitnami image probably because permissions inside the container are configured correctly for this case, but the bigger issue is that the EmptyDir is not used while it should.

### Are you using any custom parameters or values?

```yaml
primary:
  persistence:
    enabled: false
image:
  registry:
  repository: docker.io/postgres
  tag: 16.0-bullseye
```

### What is the expected behavior?

The pod to start.

### What do you see instead?

The pod crashes due to permission errors.

**Comment by carrodher** [comment]
Using different images in the Helm chart is not something supported out of the box, it is something that could work or not, but has not been tested on our end.

**Comment by hammady** [comment]
@carrodher thanks for the context behind this. I can rephrase the issue description to make it more relevant. Forget about the different image for a moment; if we use the official bitnami image and disable persistence, an `EmptyDir` is defined in the pod but it is never used (no `volumeMount` for it). It has no side effects, but the template is inconsistent in this case. Now recall the different image issue, this is when side effects start to appear. Are there other side effects in other scenarios? There could be hidden bugs, so I suggest fixing it as long as we know there is an inconsistency.
Thanks for your time considering this.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by aneurinprice** [comment]
Seeing a similar thing today.

Using bitnami postgresql as a subchart:

values:
```
postgresql:
  fullNameOverride: "pxls-database"
  auth:
    username: "pxls"
    password: "randomstring"
    database: "pxls"
  primary:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false
  volumePermissions:
    enabled: true
```

logs:
```
Defaulted container "postgresql" out of: postgresql, init-chmod-data (init)
postgresql 16:16:31.09 INFO  ==> 
postgresql 16:16:31.09 INFO  ==> Welcome to the Bitnami postgresql container
postgresql 16:16:31.09 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 16:16:31.16 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql 16:16:31.16 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
postgresql 16:16:31.16 INFO  ==> 
postgresql 16:16:31.17 INFO  ==> ** Starting PostgreSQL setup **
postgresql 16:16:31.27 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 16:16:31.27 INFO  ==> Loading custom pre-init scripts...
postgresql 16:16:31.27 INFO  ==> Initializing PostgreSQL database...
mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied
```

The pod is accepting the disablement of the persisnt volume as you can see here:

```
  containers:
  - env:
    - name: BITNAMI_DEBUG
      value: "false"
    - name: POSTGRESQL_PORT_NUMBER
      value: "5432"
    - name: POSTGRESQL_VOLUME_DIR
      value: /bitnami/postgresql
    - name: PGDATA
      value: /bitnami/postgresql/data
    - name: POSTGRES_USER
      value: pxls
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: chart-1711556188-postgresql
    - name: POSTGRES_POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgres-password
          name: chart-1711556188-postgresql
    - name: POSTGRES_DATABASE
      value: pxls
    - name: POSTGRESQL_ENABLE_LDAP
      value: "no"
    - name: POSTGRESQL_ENABLE_TLS
      value: "no"
    - name: POSTGRESQL_LOG_HOSTNAME
      value: "false"
    - name: POSTGRESQL_LOG_CONNECTIONS
      value: "false"
    - name: POSTGRESQL_LOG_DISCONNECTIONS
      value: "false"
    - name: POSTGRESQL_PGAUDIT_LOG_CATALOG
      value: "off"
    - name: POSTGRESQL_CLIENT_MIN_MESSAGES
      value: error
    - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
      value: pgaudit
    image: docker.io/bitnami/postgresql:16.2.0-debian-12-r10
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - exec pg_isready -U "pxls" -d "dbname=pxls" -h 127.0.0.1 -p 5432
      failureThreshold: 6
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: postgresql
    ports:
    - containerPort: 5432
      name: tcp-postgresql
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - -e
        - |
          exec pg_isready -U "pxls" -d "dbname=pxls" -h 127.0.0.1 -p 5432
          [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
      failureThreshold: 6
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: 150m
        ephemeral-storage: 1Gi
        memory: 192Mi
      requests:
        cpu: 100m
        ephemeral-storage: 50Mi
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1001
      runAsNonRoot: true
      runAsUser: 1001
      seLinuxOptions: {}
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp
      name: empty-dir
      subPath: tmp-dir
    - mountPath: /opt/bitnami/postgresql/conf
      name: empty-dir
      subPath: app-conf-dir
    - mountPath: /opt/bitnami/postgresql/tmp
      name: empty-dir
      subPath: app-tmp-dir
    - mountPath: /opt/bitnami/postgresql/logs
      name: empty-dir
      subPath: app-logs-dir
    - mountPath: /dev/shm
      name: dshm
```
