### ISSUE TITLE
[bitnami/kafka] How to disable SASL on Kafka with Kraft

### ISSUE THREAD

**Issue by wrl-cc** [bitnami/charts#20857]
### Name and Version

bitnami/kafka 26.3.2

### What architecture are you using?

None

### What steps will reproduce the bug?

I just try to deploy kafka using bitnami helm chart, using default configuration the kafka have SASL enabled.
I can't disable it at all. 

How to achive kafka without authentication using bitnami kafka helm chart?

Thank You.

### Are you using any custom parameters or values?

```yaml
kafka:
  auth:
    enabled: false
    sasl:
      enabled: false
      mechanisms: plain
  enabledMechanisms: PLAIN
  saslEnabled: false
  metrics:
    kafka:
      enabled: true
```

### What is the expected behavior?

SASL Disabled

### What do you see instead?

The SASL still enabled

**Update**
After digging deep into the Chart Templates, I found how to disable the SASL authentication using this values
```yaml
  listeners:
    client:
      name: CLIENT
      containerPort: 9092
      protocol: PLAINTEXT
      sslClientAuth: ""
  
    interbroker:
      name: INTERNAL
      containerPort: 9094
      protocol: PLAINTEXT
      sslClientAuth: ""
  
    external:
      name: EXTERNAL
      containerPort: 9095
      protocol: PLAINTEXT
      sslClientAuth: ""  
```
