### ISSUE TITLE
Wordpress chart use wp-config from secret doesn't work

### ISSUE THREAD

**Issue by sixgunnar** [bitnami/charts#20880]
### Name and Version

bitnami/wordpress 6.3.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Create a secret using: 

`kubectl create secret generic <secret-name> --from-file=wp-config.php`

Reference this secret in the YAML file for the WordPress chart:

```yaml
wordpressSkipInstall: true

## @param existingWordPressConfigurationSecret The name of an existing secret with your custom wp-config.php file (advanced feature)
## NOTE: When it's set the `wordpressConfiguration` parameter is ignored
##
existingWordPressConfigurationSecret: wp-config
```

Upgrade to use the wp-config from the secret instead of the file in /bitnami/wordpress/wp-config.php:

`helm upgrade -f .\wpWithWpconfigAsSecret.yaml wordpress bitnami/wordpress`

### Are you using any custom parameters or values?

```yaml
diagnosticMode:
  ## @param diagnosticMode.enabled Enable diagnostic mode (all probes will be disabled and the command will be overridden)
  ##
  enabled: false

## @section WordPress Configuration parameters
## WordPress settings based on environment variables
## ref: https://github.com/bitnami/containers/tree/main/bitnami/wordpress#environment-variables
##

## @param wordpressConfigureCache Enable W3 Total Cache plugin and configure cache settings
## NOTE: useful if you deploy Memcached for caching database queries or you use an external cache server
## Changed below to false since we don't use W3 Total Cache at the moment
wordpressConfigureCache: false

##wordpressPassword: <hidden>

## @param wordpressSkipInstall Skip wizard installation
## NOTE: useful if you use an external database that already contains WordPress data
## ref: https://github.com/bitnami/containers/tree/main/bitnami/wordpress#connect-wordpress-docker-container-to-an-existing-database
##
wordpressSkipInstall: true

## @param wordpressScheme Scheme to use to generate WordPress URLs
##
wordpressScheme: https

## @param existingWordPressConfigurationSecret The name of an existing secret with your custom wp-config.php file (advanced feature)
## NOTE: When it's set the `wordpressConfiguration` parameter is ignored
##
existingWordPressConfigurationSecret: wp-config

## @param apacheConfiguration The content for your custom httpd.conf file (advanced feature)
##
apacheConfiguration: |
  ServerRoot "/opt/bitnami/apache"
  Listen 8080
  #LoadModule mpm_event_module modules/mod_mpm_event.so
  LoadModule mpm_prefork_module modules/mod_mpm_prefork.so
  #LoadModule mpm_worker_module modules/mod_mpm_worker.so
  LoadModule authn_file_module modules/mod_authn_file.so
  #LoadModule authn_dbm_module modules/mod_authn_dbm.so
  #LoadModule authn_anon_module modules/mod_authn_anon.so
  #LoadModule authn_dbd_module modules/mod_authn_dbd.so
  #LoadModule authn_socache_module modules/mod_authn_socache.so
  LoadModule authn_core_module modules/mod_authn_core.so
  LoadModule authz_host_module modules/mod_authz_host.so
  LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
  LoadModule authz_user_module modules/mod_authz_user.so
  #LoadModule authz_dbm_module modules/mod_authz_dbm.so
  #LoadModule authz_owner_module modules/mod_authz_owner.so
  #LoadModule authz_dbd_module modules/mod_authz_dbd.so
  LoadModule authz_core_module modules/mod_authz_core.so
  #LoadModule authnz_ldap_module modules/mod_authnz_ldap.so
  LoadModule access_compat_module modules/mod_access_compat.so
  LoadModule auth_basic_module modules/mod_auth_basic.so
  #LoadModule auth_form_module modules/mod_auth_form.so
  #LoadModule auth_digest_module modules/mod_auth_digest.so
  #LoadModule allowmethods_module modules/mod_allowmethods.so
  #LoadModule file_cache_module modules/mod_file_cache.so
  #LoadModule cache_module modules/mod_cache.so
  #LoadModule cache_disk_module modules/mod_cache_disk.so
  #LoadModule cache_socache_module modules/mod_cache_socache.so
  LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
  #LoadModule socache_dbm_module modules/mod_socache_dbm.so
  #LoadModule socache_memcache_module modules/mod_socache_memcache.so
  #LoadModule socache_redis_module modules/mod_socache_redis.so
  #LoadModule watchdog_module modules/mod_watchdog.so
  #LoadModule macro_module modules/mod_macro.so
  #LoadModule dbd_module modules/mod_dbd.so
  #LoadModule dumpio_module modules/mod_dumpio.so
  #LoadModule buffer_module modules/mod_buffer.so
  #LoadModule ratelimit_module modules/mod_ratelimit.so
  LoadModule reqtimeout_module modules/mod_reqtimeout.so
  #LoadModule ext_filter_module modules/mod_ext_filter.so
  #LoadModule request_module modules/mod_request.so
  #LoadModule include_module modules/mod_include.so
  LoadModule filter_module modules/mod_filter.so
  #LoadModule substitute_module modules/mod_substitute.so
  #LoadModule sed_module modules/mod_sed.so
  LoadModule deflate_module modules/mod_deflate.so
  LoadModule mime_module modules/mod_mime.so
  #LoadModule ldap_module modules/mod_ldap.so
  LoadModule log_config_module modules/mod_log_config.so
  #LoadModule log_debug_module modules/mod_log_debug.so
  #LoadModule logio_module modules/mod_logio.so
  LoadModule env_module modules/mod_env.so
  LoadModule expires_module modules/mod_expires.so
  LoadModule headers_module modules/mod_headers.so
  #LoadModule unique_id_module modules/mod_unique_id.so
  LoadModule setenvif_module modules/mod_setenvif.so
  LoadModule version_module modules/mod_version.so
  #LoadModule remoteip_module modules/mod_remoteip.so
  LoadModule proxy_module modules/mod_proxy.so
  LoadModule proxy_connect_module modules/mod_proxy_connect.so
  LoadModule proxy_ftp_module modules/mod_proxy_ftp.so
  LoadModule proxy_http_module modules/mod_proxy_http.so
  LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so
  #LoadModule proxy_scgi_module modules/mod_proxy_scgi.so
  #LoadModule proxy_uwsgi_module modules/mod_proxy_uwsgi.so
  #LoadModule proxy_fdpass_module modules/mod_proxy_fdpass.so
  #LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
  LoadModule proxy_ajp_module modules/mod_proxy_ajp.so
  LoadModule proxy_balancer_module modules/mod_proxy_balancer.so
  #LoadModule proxy_express_module modules/mod_proxy_express.so
  #LoadModule proxy_hcheck_module modules/mod_proxy_hcheck.so
  #LoadModule session_module modules/mod_session.so
  #LoadModule session_cookie_module modules/mod_session_cookie.so
  #LoadModule session_dbd_module modules/mod_session_dbd.so
  LoadModule slotmem_shm_module modules/mod_slotmem_shm.so
  LoadModule ssl_module modules/mod_ssl.so
  #LoadModule http2_module modules/mod_http2.so
  #LoadModule lbmethod_byrequests_module modules/mod_lbmethod_byrequests.so
  #LoadModule lbmethod_bytraffic_module modules/mod_lbmethod_bytraffic.so
  #LoadModule lbmethod_bybusyness_module modules/mod_lbmethod_bybusyness.so
  #LoadModule lbmethod_heartbeat_module modules/mod_lbmethod_heartbeat.so
  LoadModule unixd_module modules/mod_unixd.so
  #LoadModule dav_module modules/mod_dav.so
  LoadModule status_module modules/mod_status.so
  LoadModule autoindex_module modules/mod_autoindex.so
  #LoadModule info_module modules/mod_info.so
  #LoadModule cgid_module modules/mod_cgid.so
  #LoadModule dav_fs_module modules/mod_dav_fs.so
  #LoadModule vhost_alias_module modules/mod_vhost_alias.so
  LoadModule negotiation_module modules/mod_negotiation.so
  LoadModule dir_module modules/mod_dir.so
  #LoadModule actions_module modules/mod_actions.so
  #LoadModule speling_module modules/mod_speling.so
  #LoadModule userdir_module modules/mod_userdir.so
  LoadModule alias_module modules/mod_alias.so
  LoadModule rewrite_module modules/mod_rewrite.so
  #LoadModule security3_module modules/mod_security3.so
  LoadModule php_module modules/libphp.so
  
  <IfModule unixd_module>
  User daemon
  Group daemon
  </IfModule>
  
  ServerAdmin you@example.com
  ServerName www.example.com:8080
  
  <Directory />
  AllowOverride None
  Require all denied
  </Directory>
  DocumentRoot "/opt/bitnami/apache/htdocs"
  <Directory "/opt/bitnami/apache/htdocs">
  Options Indexes FollowSymLinks
  AllowOverride None
  Require all granted
  </Directory>
  
  <IfModule dir_module>
  DirectoryIndex index.html
  </IfModule>
  
  <Files ".ht*">
  Require all denied
  </Files>
  
  ErrorLog "logs/error_log"
  LogLevel warn
  
  <IfModule log_config_module>
  LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
  LogFormat "%h %l %u %t \"%r\" %>s %b" common
  
  <IfModule logio_module>
  LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
  </IfModule>
  
  CustomLog "logs/access_log" common
  </IfModule>
  
  <IfModule alias_module>
  ScriptAlias /cgi-bin/ "/opt/bitnami/apache/cgi-bin/"
  
  </IfModule>
  
  <IfModule cgid_module>
  
  </IfModule>
  
  <Directory "/opt/bitnami/apache/cgi-bin">
  AllowOverride None
  Options None
  Require all granted
  </Directory>
  
  <IfModule headers_module>
  RequestHeader unset Proxy early
  </IfModule>
  
  <IfModule mime_module>
  TypesConfig conf/mime.types
  
  AddType application/x-compress .Z
  AddType application/x-gzip .gz .tgz
  
  </IfModule>
  
  <IfModule proxy_html_module>
  Include conf/extra/proxy-html.conf
  </IfModule>
  
  <IfModule ssl_module>
  SSLRandomSeed startup builtin
  SSLRandomSeed connect builtin
  </IfModule>
  Include "/opt/bitnami/apache/conf/extra/httpd-default.conf"
  PidFile "/opt/bitnami/apache/var/run/httpd.pid"
  TraceEnable Off
  ServerTokens Prod
  Include "/opt/bitnami/apache/conf/deflate.conf"
  IncludeOptional "/opt/bitnami/apache/conf/vhosts/*.conf"
  Include "/opt/bitnami/apache/conf/bitnami/bitnami.conf"
  Include "/opt/bitnami/apache/conf/bitnami/php.conf"


## @section WordPress Multisite Configuration parameters
## ref: https://github.com/bitnami/containers/tree/main/bitnami/wordpress#multisite-configuration
##

## @param multisite.enable Whether to enable WordPress Multisite configuration.
## @param multisite.host WordPress Multisite hostname/address. This value is mandatory when enabling Multisite mode.
## @param multisite.networkType WordPress Multisite network type to enable. Allowed values: `subfolder`, `subdirectory` or `subdomain`.
## @param multisite.enableNipIoRedirect Whether to enable IP address redirection to nip.io wildcard DNS. Useful when running on an IP address with subdomain network type.
##
multisite:
  enable: true
  host: "<hidden>"
  networkType: subdirectory
  enableNipIoRedirect: false


## @param extraEnvVars Array with extra environment variables to add to the WordPress container
## e.g:
## extraEnvVars:
##   - name: FOO
##     value: "bar"
##
extraEnvVars: 
  - name: MYSQL_CLIENT_ENABLE_SSL
    value: "true"
  - name: WORDPRESS_ENABLE_DATABASE_SSL
    value: "true"

mariadb:
  ## @param mariadb.enabled Deploy a MariaDB server to satisfy the applications database requirements
  ## To use an external database set this to false and configure the `externalDatabase.*` parameters
  ##
  enabled: false

externalDatabase:
  ## @param externalDatabase.host External Database server host
  ##
  host: <hidden>
  ## @param externalDatabase.port External Database server port
  ##
  port: <hidden>
  ## @param externalDatabase.user External Database username
  ##
  user: <hidden>
  ## @param externalDatabase.password External Database user password
  ##
  password: <hidden>
  ## @param externalDatabase.database External Database database name
  ##
  database: <hidden>
  ## @param externalDatabase.existingSecret The name of an existing secret with database credentials. Evaluated as a template
  ## NOTE: Must contain key `mariadb-password`
  ## NOTE: When it's set, the `externalDatabase.password` parameter is ignored
  ##
  ##existingSecret: ""

resources:
  limits: 
    memory: 2048Mi
    cpu: 500m
  requests:
    memory: 512Mi
    cpu: 300m

## Configure extra options for WordPress containers' liveness, readiness and startup probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
## @param livenessProbe.enabled Enable livenessProbe on WordPress containers
## @skip livenessProbe.httpGet
## @param livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
## @param livenessProbe.periodSeconds Period seconds for livenessProbe
## @param livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
## @param livenessProbe.failureThreshold Failure threshold for livenessProbe
## @param livenessProbe.successThreshold Success threshold for livenessProbe
##
livenessProbe:
  enabled: true
  httpGet:
    path: /wp-admin/install.php
    port: '{{ .Values.wordpressScheme }}'
    scheme: '{{ .Values.wordpressScheme | upper }}'
    ## If using an HTTPS-terminating load-balancer, the probes may need to behave
    ## like the balancer to prevent HTTP 302 responses. According to the Kubernetes
    ## docs, 302 should be considered "successful", but this issue on GitHub
    ## (https://github.com/kubernetes/kubernetes/issues/47893) shows that it isn't.
    ## E.g.
    ## httpHeaders:
    ## - name: X-Forwarded-Proto
    ##   value: https
    ##
    httpHeaders:
    - name: X-Forwarded-Proto
      value: https
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
## @param readinessProbe.enabled Enable readinessProbe on WordPress containers
## @skip readinessProbe.httpGet
## @param readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
## @param readinessProbe.periodSeconds Period seconds for readinessProbe
## @param readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
## @param readinessProbe.failureThreshold Failure threshold for readinessProbe
## @param readinessProbe.successThreshold Success threshold for readinessProbe
##
readinessProbe:
  enabled: true
  httpGet:
    path: /wp-login.php
    port: '{{ .Values.wordpressScheme }}'
    scheme: '{{ .Values.wordpressScheme | upper }}'
    ## If using an HTTPS-terminating load-balancer, the probes may need to behave
    ## like the balancer to prevent HTTP 302 responses. According to the Kubernetes
    ## docs, 302 should be considered "successful", but this issue on GitHub
    ## (https://github.com/kubernetes/kubernetes/issues/47893) shows that it isn't.
    ## E.g.
    ## httpHeaders:
    ## - name: X-Forwarded-Proto
    ##   value: https
    ##
    httpHeaders:
    - name: X-Forwarded-Proto
      value: https
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
## @param startupProbe.enabled Enable startupProbe on WordPress containers
## @skip startupProbe.httpGet
## @param startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
## @param startupProbe.periodSeconds Period seconds for startupProbe
## @param startupProbe.timeoutSeconds Timeout seconds for startupProbe
## @param startupProbe.failureThreshold Failure threshold for startupProbe
## @param startupProbe.successThreshold Success threshold for startupProbe
##
startupProbe:
  enabled: false
  httpGet:
    path: /wp-login.php
    port: '{{ .Values.wordpressScheme }}'
    scheme: '{{ .Values.wordpressScheme | upper }}'
    ## If using an HTTPS-terminating load-balancer, the probes may need to behave
    ## like the balancer to prevent HTTP 302 responses. According to the Kubernetes
    ## docs, 302 should be considered "successful", but this issue on GitHub
    ## (https://github.com/kubernetes/kubernetes/issues/47893) shows that it isn't.
    ## E.g.
    ## httpHeaders:
    ## - name: X-Forwarded-Proto
    ##   value: https
    ##
    httpHeaders:
    - name: X-Forwarded-Proto
      value: https
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

## Memcached chart configuration
## ref: https://github.com/bitnami/charts/blob/master/bitnami/memcached/values.yaml
##
memcached:
  ## @param memcached.enabled Deploy a Memcached server for caching database queries
  ##
  enabled: false
  
## WordPress service parameters
##
service:
  ## @param service.type WordPress service type
  ##
  type: ClusterIP
  ## @param service.ports.http WordPress service HTTP port
  ## @param service.ports.https WordPress service HTTPS port
  ##
  ports:
    http: 80
    https: 443
  ## @param service.httpsTargetPort Target port for HTTPS
  ##
  httpsTargetPort: https
  ## Node ports to expose
  ## @param service.nodePorts.http Node port for HTTP
  ## @param service.nodePorts.https Node port for HTTPS
  ## NOTE: choose port between <30000-32767>
  ##
  nodePorts:
    http: ""
    https: ""
  ## @param service.sessionAffinity Control where client requests go, to the same pod or round-robin
  ## Values: ClientIP or None
  ## ref: https://kubernetes.io/docs/user-guide/services/
  ##
  sessionAffinity: None
  ## @param service.sessionAffinityConfig Additional settings for the sessionAffinity
  ## sessionAffinityConfig:
  ##   clientIP:
  ##     timeoutSeconds: 300
  ##
  sessionAffinityConfig: {}
  ## @param service.clusterIP WordPress service Cluster IP
  ## e.g.:
  ## clusterIP: None
  ##
  ##clusterIP: ""
  ## @param service.loadBalancerIP WordPress service Load Balancer IP
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer
  ##
  
persistence:
  enabled: true
  existingClaim: wordpress
```

### What is the expected behavior?

Pod starting as usual after upgrade.

### What do you see instead?

The pod crashes with this in the logs:

```
wordpress 09:11:59.60 
wordpress 09:11:59.60 Welcome to the Bitnami wordpress container
wordpress 09:11:59.60 Subscribe to project updates by watching https://github.com/bitnami/containers
wordpress 09:11:59.60 Submit issues and feature requests at https://github.com/bitnami/containers/issues
wordpress 09:11:59.60 
wordpress 09:11:59.61 INFO  ==> ** Starting WordPress setup **
wordpress 09:11:59.62 WARN  ==> The Apache configuration file '/opt/bitnami/apache/conf/httpd.conf' is not writable. Configurations based on environment variables will not be applied.
wordpress 09:11:59.63 INFO  ==> Generating sample certificates
Generating RSA private key, 4096 bit long modulus (2 primes)
...++++
.......................................++++
e is 65537 (0x010001)
Signature ok
subject=CN = example.com
Getting Private key
realpath: /bitnami/apache/conf: No such file or directory
wordpress 09:12:00.11 INFO  ==> Configuring the HTTP port
wordpress 09:12:00.11 INFO  ==> Configuring the HTTPS port
wordpress 09:12:00.12 INFO  ==> Configuring Apache ServerTokens directive
wordpress 09:12:00.13 INFO  ==> Configuring PHP options
wordpress 09:12:00.13 INFO  ==> Setting PHP expose_php option
wordpress 09:12:00.14 INFO  ==> Setting PHP output_buffering option
wordpress 09:12:00.19 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
wordpress 09:12:00.22 WARN  ==> The WordPress configuration file '/opt/bitnami/wordpress/wp-config.php' is not writable. Configurations based on environment variables will not be applied for this file.
wordpress 09:12:00.34 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
wordpress 09:12:00.50 INFO  ==> Restoring persisted WordPress installation
rm: cannot remove '/opt/bitnami/wordpress/wp-config.php': Device or resource busy
```

### Additional information

A similar issue is seen here: https://github.com/bitnami/charts/issues/13018#issuecomment-1296118443
