### ISSUE TITLE
[bitnami/mongodb] Can't connect to replicaset

### ISSUE THREAD

**Issue by mike-pisman** [bitnami/charts#20898]
### Name and Version

bitnami/mongodb:14.2.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install helm chart with values.yaml
2. Try to connect using
```bash
mongosh admin --host "10.0.2.181:27017,10.0.2.182:27017,10.0.2.183:27017" --authenticationDatabase admin -u root -p <password>
```

### Are you using any custom parameters or values?

**values.yaml**
```yaml
architecture: replicaset
replicaCount: 3
externalAccess:
  enabled: true
  service:
    loadBalancerIPs:
      - 10.0.2.181
      - 10.0.2.182
      - 10.0.2.183
auth:
  existingSecret: mongodb-credentials
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      monitoring-platform: core-prometheus
  service:
    type: LoadBalancer
```

### What is the expected behavior?

The client should select primary replica and connect to it

### What do you see instead?

```
MongoServerSelectionError: Server selection timed out after 30000 ms
```

### Additional information

I can connect to all three pods individually, i.e.
```bash
mongosh admin --host "10.0.2.181:27017" --authenticationDatabase admin -u root -p <password>
```

Sorry, if I made an error in the configuration, the replicaset could be documented more extensively though.

Also, I get this error repeated over and over again in arbiter log:
```
{"t":{"$date":"2023-11-11T04:05:52.001+00:00"},"s":"W",  "c":"QUERY",    "id":23799,   "ctx":"ftdc","msg":"Aggregate command executor error","attr":{"error":{"code":26,"codeName":"NamespaceNotFound","errmsg":"Unable to retrieve storageStats in $collStats stage :: caused by :: Collection [local.oplog.rs] not found."},"stats":{},"cmd":{"aggregate":"oplog.rs","cursor":{},"pipeline":[{"$collStats":{"storageStats":{"waitForLock":false,"numericOnly":true}}}],"$db":"local"}}}
```
