### ISSUE TITLE
[bitnami/memcached] unable to pass `--extended` options

### ISSUE THREAD

**Issue by dmitry-mightydevops** [bitnami/charts#20906]
### Name and Version

bitnami/memcached 6.7.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```yaml
architecture: standalone
auth:
  enabled: false
replicaCount: 1
containerPorts:
memcached: 11211
args:
  - /run.sh
  - -m 256 
  - -I 10m
  - -o "ext_wbuf_size=32,ext_threads=10,ext_max_sleep=10000,slab_automove_freeratio=0.10,ext_recache_rate=0"
resources:
  limits: {}
  requests:
    memory: 256Mi
    cpu: 250m
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    labels:
      release: prometheus
```

pods:

```sh
➜ k ice command | grep memcached
loki-memcached-5f86bc6576-gcnfw              memcached               -        /run.sh -m 256 -I 10m -o ext_wbuf_size=32,ext_threads=10,ext_max_sleep=10000,slab_automove_freeratio=0.10,ext_recache_rate=0
loki-memcached-5f86bc6576-gcnfw              metrics                 -        -
loki-memcached-754b64b8b-j68j2               memcached               -        /run.sh -m 256 -I 10m -o "ext_wbuf_size=32,ext_threads=10,ext_max_sleep=10000,slab_automove_freeratio=0.10,ext_recache_rate=0"
loki-memcached-754b64b8b-j68j2               metrics                 -        -
```

both containers are failing

```sh
➜ kgpo | grep memcached                  
loki-memcached-5f86bc6576-gcnfw               1/2     CrashLoopBackOff   5 (2m19s ago)   5m20s
loki-memcached-754b64b8b-j68j2                1/2     CrashLoopBackOff   5 (10s ago)     3m32s

➜  klo loki-memcached-5f86bc6576-gcnfw                             
Defaulted container "memcached" out of: memcached, metrics
memcached 23:16:03.00 
memcached 23:16:03.00 Welcome to the Bitnami memcached container
memcached 23:16:03.01 Subscribe to project updates by watching https://github.com/bitnami/containers
memcached 23:16:03.01 Submit issues and feature requests at https://github.com/bitnami/containers/issues
memcached 23:16:03.01 
memcached 23:16:03.01 INFO  ==> ** Starting Memcached setup **
memcached 23:16:03.04 INFO  ==> Initializing Memcached
memcached 23:16:03.05 INFO  ==> ** Memcached setup finished! **

memcached 23:16:03.06 INFO  ==> ** Starting Memcached **
Illegal suboption " ext_wbuf_size=32"

➜ klo loki-memcached-754b64b8b-j68j2                              
Defaulted container "memcached" out of: memcached, metrics
memcached 23:18:12.02 
memcached 23:18:12.02 Welcome to the Bitnami memcached container
memcached 23:18:12.02 Subscribe to project updates by watching https://github.com/bitnami/containers
memcached 23:18:12.02 Submit issues and feature requests at https://github.com/bitnami/containers/issues
memcached 23:18:12.03 
memcached 23:18:12.03 INFO  ==> ** Starting Memcached setup **
memcached 23:18:12.06 INFO  ==> Initializing Memcached
memcached 23:18:12.07 INFO  ==> ** Memcached setup finished! **

memcached 23:18:12.09 INFO  ==> ** Starting Memcached **
Illegal suboption " "ext_wbuf_size=32"
```

### Are you using any custom parameters or values?

so I'm trying to pass args
```
- -o "ext_wbuf_size=32,ext_threads=10,ext_max_sleep=10000,slab_automove_freeratio=0.10,ext_recache_rate=0"
```

### What is the expected behavior?

The arguments to be passed in the run.sh and memcached instance to be started.

### What do you see instead?

```sh
➜ klo loki-memcached-754b64b8b-j68j2                              
Defaulted container "memcached" out of: memcached, metrics
memcached 23:18:12.02 
memcached 23:18:12.02 Welcome to the Bitnami memcached container
memcached 23:18:12.02 Subscribe to project updates by watching https://github.com/bitnami/containers
memcached 23:18:12.02 Submit issues and feature requests at https://github.com/bitnami/containers/issues
memcached 23:18:12.03 
memcached 23:18:12.03 INFO  ==> ** Starting Memcached setup **
memcached 23:18:12.06 INFO  ==> Initializing Memcached
memcached 23:18:12.07 INFO  ==> ** Memcached setup finished! **

memcached 23:18:12.09 INFO  ==> ** Starting Memcached **
Illegal suboption " "ext_wbuf_size=32"

```
