### ISSUE TITLE
[bitnami/mastodon] missing support for redis sub-chart's `redis.auth.existingSecret`

### ISSUE THREAD

**Issue by jessebot** [bitnami/charts#20903]
### Name and Version

bitnami/mastodon

### What architecture are you using?

amd64

### What steps will reproduce the bug?

On the latest version of k3s using Argo CD, attempt to deploy the latest mastodon chart using the redis subchart with the below values set.

### Are you using any custom parameters or values?

relevant values:
```yaml
## ref: https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml
redis:
  enabled: true
  fullnameOverride: mastodon-redis
  ## Set Redis architecture
  architecture: standalone
  auth:
    ## Name of a secret containing redis credentials
    existingSecret: "mastodon-redis-credentials"
    existingSecretPasswordKey: "redis-pasword"
```

which I've based on the docs here:
https://github.com/bitnami/charts/tree/8c7bc70727aa6096895cf3f3a5d5b55e88470cf1/bitnami/redis#redis-common-configuration-parameters

### What is the expected behavior?

This section of the _helpers.tpl below should include checking the following values for existing Secret names and secret key names:
- `.Values.redis.auth.existingSecret` 
- `.Values.redis.auth.existingSecretPasswordKey`

https://github.com/bitnami/charts/blob/8c7bc70727aa6096895cf3f3a5d5b55e88470cf1/bitnami/mastodon/templates/_helpers.tpl#L400-L430

Based on the docs here:
https://github.com/bitnami/charts/tree/8c7bc70727aa6096895cf3f3a5d5b55e88470cf1/bitnami/redis#redis-common-configuration-parameters

### What do you see instead?

The init-job fails with:
```
Error: secret "mastodon-redis" not found
```

### Additional information

The values section showing existingSecret for redis:
https://github.com/bitnami/charts/blob/8c7bc70727aa6096895cf3f3a5d5b55e88470cf1/bitnami/mastodon/values.yaml#L1357-L1381

which are documented here:
https://github.com/bitnami/charts/tree/main/bitnami/mastodon#redis-sub-chart-parameters
