### ISSUE TITLE
[bitnami/mongodb-sharded] {Feature Request / Question} shard db node anti affinities

### ISSUE THREAD

**Issue by oldluke92** [bitnami/charts#2090]
Feature Request:

Adding a Label to the shard data node and arbiter pods which has the shard number in it, e.g.:

`shard: 0`
or
`shardname: shard2`

And node antiaffinities based on releasename and that label so there can never be more than one node of the same shard on one kubernetes node.
This is especially useful in smaller setups.

Alternatively: 
Please Tell me how to access $i from the loop creating the shards in custom labels and node affinities, so I can add this without changing the chart.

**Comment by dani8art** [comment]
Hi @oldluke92 thank you for opening this issue. 

> Please Tell me how to access $i from the loop creating the shards in custom labels and node affinities, so I can add this without changing the chart.

I think this is not possible since $i is managing for k8s after helm deploys the charts. 

Maybe you can play with `affinity` trying to say to not deploy a node where other of the same component exists yet. using `app.kubernetes.io/component`.

**Comment by javsalgar** [comment]
Hi,

The value `affinity` is templatized, so you could try adding a templatized value that uses the variable `$i` if that's what you require. I would need to understand the use case or what you would like to have in more detail but maybe that helps you.

**Comment by oldluke92** [comment]
@dani8art Thank you for your answer. I already did that like the following:

shardsvr and arbiter:
```yml
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: shardsvr
              app.kubernetes.io/instance: {{ mongodb.releaseName }}
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: shardsvr-arbiter
              app.kubernetes.io/instance: {{ mongodb.releaseName }}
```

configsvr:
```yml
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: configsvr
            app.kubernetes.io/instance: {{ mongodb.releaseName }}
```

Which works as expected.

Use-Case:

We got an on-prem bare-metal cluster with 3 master and 4 worker nodes. The settings above work fine when using only one shard. A sharded mongodb is used (instead of a replicaset) so clients don't have to know they are dealing with a cluster.
If a second shard is added, with the above settings 2 of 3 pods of that shard are unschedulable.

The Goal is to define that of a single shard, only one pod at a time can be running on the same k8s node. e.G.

```
Node1                  Node2                  Node3                  Node4
config-0               config-1               config-2
                       shard0-0               shard0-1               shard0-arbiter
shard1-0               shard1-1               shard1-arbiter
                       shard2-0               shard2-1               shard2-arbiter
```
( Ofc this would be mixed a little bit more, but this is an example ...)

Or in case a node fails:
```
Node1                  Node2                  Node3                  N̶o̶d̶e̶4
config-0               config-1               config-2
shard0-0               shard0-1               shard0-arbiter
shard1-0               shard1-1               shard1-arbiter
shard2-0               shard2-1               shard2-arbiter
```
But never like this:

```
Node1                  Node2                  Node3                  N̶o̶d̶e̶4
config-0               config-1               config-2
shard0-0               shard2-0               shard0-arbiter
shard0-1               shard1-1               shard1-arbiter
shard2-arbiter         shard2-1               shard1-0
```
To ensure availability if a node fails.

And yes, I am aware that adding more shards on these nodes does not increase performance nor availability at all.

**Comment by dani8art** [comment]
I see, so if I understood well, your proposal is to have
-  `shard` and `data-node` have a new label like `shard: $i`
-  Then you can do anti-affinity in pods and they won't be scheduled in the same node for the same shard. do we have to add sth more for the anti-affinity?

**Comment by oldluke92** [comment]
@dani8art 
I guess you wanted to write

- `arbiter` and `data-node` have a new label like `shard: $i`

Having the label (though that might be useful in other ways too) is not sufficient though, as $i can also not be accessed through the affinities value templating (at least I was not able to. If it is possible, please explain how.
I tried

```yaml
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                shard: {{ $i }}"
```
and 
`shard: {{ .i }}"`
`shard: "{% raw %}{{ $i }}{% endraw %}"`

but none of those worked (same problem as in Label ..)

Elseways it needs to be there already (and maybe disabled by default with a variable to activate it)
or templating needs to be done in a way that $i can be accessed.
