### ISSUE TITLE
[matomo] CronJob.batch "matomo-archive" is invalid: spec.jobTemplate.spec.template.spec.containers[1].image: Required value

### ISSUE THREAD

**Issue by viceice** [bitnami/charts#20922]
### Name and Version

bitnami/matomo 3.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. k3s 1.27.7+k3s2
2. flux 2.1.2
3. deploy with diabled cronjob
4. upgrade with enabled cronjobs

### Are you using any custom parameters or values?

```yaml
matomoUsername: root
matomoEmail: admin@some.test
existingSecret: matomo

allowEmptyPassword: false

smtpHost: mail.some.test
smtpPort: 25
noreplyName: Matomo
noreplyAddress: noreply@some.test

externalDatabase:
  existingSecret: matomo
  host: mariadb
  database: matomo
  user: matomo

extraEnvVars:
  - name: MATOMO_ENABLE_ASSUME_SECURE_PROTOCOL
    value: 'yes'
  - name: MATOMO_ENABLE_FORCE_SSL
    value: 'yes'
  - name: MATOMO_PROXY_CLIENT_HEADER
    value: HTTP_X_FORWARDED_FOR
  - name: MATOMO_PROXY_HOST_HEADER
    value: HTTP_X_FORWARDED_HOST
  - name: MATOMO_ENABLE_PROXY_URI_HEADER
    value: 'yes'

extraVolumes:
  - name: matomo-files
    configMap:
      name: matomo-files

extraVolumeMounts:
  - name: matomo-files
    mountPath: /opt/bitnami/apache/conf/vhosts/000_matomo.conf
    readOnly: true
    subPath: matomo.conf

persistence:
  existingClaim: matomo-data

startupProbe:
  enabled: true
  initialDelaySeconds: 30
  failureThreshold: 70

livenessProbe:
  initialDelaySeconds: 0
  failureThreshold: 10

readinessProbe:
  enabled: false

service:
  type: ClusterIP

ingress:
  enabled: true
  path: /_m
  pathType: Prefix
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.middlewares: matomo-matomo-strip-prefix@kubernetescrd,matomo-matomo-replace-js@kubernetescrd,matomo-matomo-replace-php@kubernetescrd,matomo-matomo-headers@kubernetescrd

resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 1000m

mariadb:
  enabled: false

cronjobs:
  enabled: true
```

### What is the expected behavior?

Upgrade should work

### What do you see instead?

A failed upgrade
```
reconciliation failed: Helm upgrade failed: failed to create resource: CronJob.batch "matomo-archive" is invalid: spec.jobTemplate.spec.template.spec.containers[1].image: Required value
```

### Additional information

When manually run it via `helm template` then it prints the jobs normally. 🤔
