### ISSUE TITLE
[bitnami/postgresql] FATAL:  certificate authentication failed for user "postgresql-db"

### ISSUE THREAD

**Issue by ericklife28** [bitnami/charts#20932]
### Name and Version

bitnami/postgresql 13.2.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create Values.yml
2. Execute helm
3. Check logs on postgresql pod(kubectl logs) 

The postgresql  install and start up processes are successful. I can connect to the server. However, I get this log entries recurrently: 
```
postgresql 2023-11-14 00:00:44.747 GMT [3780] DETAIL:  Connection matched file "/opt/bitnami/postgresql/conf/pg_hba.conf" line 1: "hostssl │
│ postgresql 2023-11-14 00:00:54.696 GMT [3788] LOG:  provided user name (postgresql-db) and authenticated user name (int.spectra-ops.nabanc │
│ postgresql 2023-11-14 00:00:54.696 GMT [3788] FATAL:  certificate authentication failed for user "postgresql-db"                           │
│ postgresql 2023-11-14 00:00:54.696 GMT [3788] DETAIL:  Connection matched file "/opt/bitnami/postgresql/conf/pg_hba.conf" line 1: "hostssl │
│ postgresql 2023-11-14 00:00:54.758 GMT [3796] LOG:  provided user name (postgresql-db) and authenticated user name (int.spectra-ops.nabanc │
│ postgresql 2023-11-14 00:00:54.758 GMT [3796] FATAL:  certificate authentication failed for user "postgresql-db"                           │
│ postgresql 2023-11-14 00:00:54.758 GMT [3796] DETAIL:  Connection matched file "/opt/bitnami/postgresql/conf/pg_hba.conf" line 1: "hostssl │
│
```
### Are you using any custom parameters or values?

USER-SUPPLIED VALUES:
```
auth:
  database: postgresql-db
  existingSecret: postgresql-creds
  secretKeys:
    adminPasswordKey: admin-password
    userPasswordKey: user-password
  username: postgresql-db
nameOverride: postgresql
primary:
  name: primary
  persistence:
    accessModes:
    - ReadWriteOnce
    enabled: true
    size: 20Gi
    storageClass: premium-rwo
tls:
  certCAFilename: root.pem
  certFilename: tls.crt
  certKeyFilename: tls.key
  certificatesSecret: postgresql-tls
  enabled: true
volumePermissions:
  enabled: true
```
### What is the expected behavior?

I would expect that after the start up process none log error should be present 

### What do you see instead?

The log entries above.

### Additional information

I have generated some tls certificates for the postgresql-db user and it can connect successfully to the server. However, the log entries are still there.   The issue started when I turned on tls on the server

This is a more complete start up log entry 
[init.log](https://github.com/bitnami/charts/files/13343187/init.log)
