### ISSUE TITLE
[bitnami/wordpress] wordpress Error establishing a database connection

### ISSUE THREAD

**Issue by xyfleet** [bitnami/charts#20933]
### Name and Version

bitnami/wordpress 16.1.2 (helm chart)
In the wordpress site, I upgrade the application to 18.1.14

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1: deployed the wordpress in EKS
2: build an external mysql DB for wordpress
3: probably you can see this error when you click the blog link.

### Are you using any custom parameters or values?

```
externalDatabase:
    host: "${var.external_mysql_wordpress_db_host}"
    user: my_wordpress
    password: "${var.external_mysql_wordpress_password}"
    database: wordpress
```

### What do you see instead?

Sometimes, visitors clicked the link of our blog and saw an error similar like this one **"Error establishing a database connection"**. If you refresh the page, the error is gone, you can read the blog without problem. It happens a lot but always. So annoyed, since customers may not click refresh button and then just leave our blog site. 

After checking all possible reasons, I found that the external mysql has a high ConnectionAttempts, around 2K on average. I don't know why wordpress sends so many connection attempts to MySql DB. Do you have any idea? 

Thanks,

### Additional information

btw, my DB only has 2CPU and 2G memory.
