### ISSUE TITLE
[bitnami/kafka] Cannot configure topic provisioning

### ISSUE THREAD

**Issue by RomainWilbert** [bitnami/charts#20961]
### Name and Version

bitnami/kafka 26.4.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Try to provision the topic with a custom configuration

### Are you using any custom parameters or values?
```yaml
     provisioning:
       enabled: true
       topics:
         - name: my_topic_name
           partitions: 9
           replicationFactor: 3
           config:
             max.message.bytes: 10000000
```
or 
```yaml
     provisioning:
       enabled: true
       replicationFactor: 3
       numPartitions: 9
       topics:
         - name: my_topic_name
```
### What is the expected behavior?

The provision job finishes with no errors, topics are created with custom values for partitions, replicationFactor and maxMessageBytes

### What do you see instead?

The provision job finishes with no errors, topic are created with default values for partitions, replicationFactor and maxMessageBytes

### Additional information

The only way to configure topics was to use extraConfig and global configuration variables : 
```yaml
     provisioning:
       enabled: true
       topics:
         - name: my_topic_name
           
     extraConfig: |
       message.max.bytes=10000000
       num.partitions=9
       default.replication.factor=3
```
