### ISSUE TITLE
[bitnami/spring-cloud-dataflow] SCDF upgrade to 2.11.1 corrupts skipper tables in DB and streams not accessible via UI

### ISSUE THREAD

**Issue by dhpizza** [bitnami/charts#21037]
### Name and Version

bitnami/spring-cloud-dataflow

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Have   spring-cloud-dataflow bitnami Chart deployed with images:

```yaml
appVersion: 2.9.3
dependencies:
- name: spring-cloud-dataflow
  version: 16.0.2
```

2. Upgrade to 
```yaml
appVersion: 2.11.1
dependencies:
- name: spring-cloud-dataflow
  version: 25.0.0
```

3. Access spring-cloud-dataflow UI
4. Go to streams and ERROR pop- up will show up `logref:SkipperException message:No release manager available for 'null'`

### What is the expected behavior?

The list of previously registered and deployed streams should be visible.
The upgrade should not change the existing data or make it un-accessible.

### What do you see instead?

![image](https://github.com/bitnami/charts/assets/4428361/4c43c4fe-5d25-41d2-8995-dddbde3ee651)

### Additional information

I found that after the upgrade the `skipper_release` table in the in the skipper postgreSQL DB has values of `pkg_json_string` changed from 7-digit integers like `7076817`  to `{ "metadata":{"apiVersion":"skipper.spring.io/v1", ...`
