### ISSUE TITLE
mariadb upgrade fails via flux and helm

### ISSUE THREAD

**Issue by djtecha** [bitnami/charts#21045]
### Name and Version

bitnami/mariadb:14.1.2

### What architecture are you using?

None

### What steps will reproduce the bug?

Install mariadb using flux and the helm chart:

```yaml
---
# https://github.com/bitnami/charts/blob/main/bitnami/mariadb/values.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: mariadb
      #Upgrading requires manual methods - be careful
      version: "14.1.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: cluster-config
  values:
    architecture: standalone
    primary:
      persistence:
        existingClaim: "mariadb-pvc"
        size: "2Gi"
    volumePermissions:
      enabled: true
```
### What is the expected behavior?

Upgrading helm chart in code should allow kustomize to run the helm upgrade on the chart.

### What do you see instead?

Helm upgrade is blocked do to missing rootPassword. Even attempting to add the following fails since the secret was created on the initial mariadb creation.

```yaml
  values:
    auth:
      rootPassword: "XXXXX"

```

Last Helm logs:
```
preparing upgrade for mariadb
resetting values to the chart's original version
  Warning  error  9m58s (x597 over 6d)  helm-controller  reconciliation failed: Helm upgrade failed: execution error at (mariadb/templates/NOTES.txt:73:6): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$MARIADB_ROOT_PASSWORD' to the command. To get the current value:

        export MARIADB_ROOT_PASSWORD=$(kubectl get secret --namespace "default" mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 -d)
  Normal  info  5m15s (x598 over 6d)  helm-controller  Helm upgrade has started
```
