### ISSUE TITLE
[bitnami/harbor] There is no option for the externalDatabase.password parameter to come from a Secret.

### ISSUE THREAD

**Issue by vargaadam** [bitnami/charts#21051]
### Name and Version

bitnami/harbor 19.1.2

### What is the problem this feature will solve?

Currently, there is an issue with the `externalDatabase.password` parameter, as it does not provide an option to retrieve the password from a secret. This constraint raises security issues since storing sensitive information in plaintext within configuration files is discouraged.

### What is the feature you are proposing to solve the problem?

Just like in your other charts, such as the one for Keycloak, it should specify an external secret to store the necessary information, like so:

```yaml
externalDatabase:
  existingSecret: ""
  existingSecretUserKey: ""
  existingSecretPasswordKey: ""
```

### What alternatives have you considered?

Given that `externalDatabase.password` is a mandatory field, no alternative options were considered.
