### ISSUE TITLE
[bitnami/opensearch] opensearch missing settings

### ISSUE THREAD

**Issue by pmiriyev** [bitnami/charts#21050]
### Name and Version

bitnami/opensearch

### What is the problem this feature will solve?

hi, I have tried to add these settings under `extraconfig` and `extraenvvars` but no luck, pods crashing, any idea how can I apply these settings? thanks in advance
```yaml
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]

plugins.security.authc:
        openid_auth_domain:
          http_enabled: true
          transport_enabled: true
          order: 0
          http_authenticator:
            type: openid
            challenge: false
            config:
              subject_key: preferred_username
              roles_key: roles
              openid_connect_url: "https://PROVIDER/.well-known/openid-configuration"
          authentication_backend:
            type: noop
```
for dashboard:
```yaml
opensearchDashboards:
  config:
    opensearch_dashboards.yml: |
      opensearch_security.auth.type: "openid"
      opensearch_security.openid.connect_url: "https://PROVIDER/.well-known/openid-configuration"
      opensearch_security.openid.client_id: "CLIENT_ID"
      opensearch_security.openid.client_secret: "CLIENT_SECRET"
      opensearch_security.openid.base_redirect_url: "_URL"
```

### What is the feature you are proposing to solve the problem?

settings for opensearch.yml and opensearch_dashboards.yml
