### ISSUE TITLE
[bitnami/mastodon] Unable to template chart locally with bitnami/common errors

### ISSUE THREAD

**Issue by joelparker** [bitnami/charts#21060]
### Name and Version

bitnnami/mastodon 3.2.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

* Check out most current bitnami/charts (6ec633ba1 at the time of this issue)
* cd bitnami/mastodon
* helm template . --debug

The following error occurs:

```
Error: template: mastodon/templates/web/service.yaml:11:14: executing "mastodon/templates/web/service.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: mastodon/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: mastodon/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
helm.go:84: [debug] template: mastodon/templates/web/service.yaml:11:14: executing "mastodon/templates/web/service.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: mastodon/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: mastodon/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```

### Are you using any custom parameters or values?

None.  I'm trying to render the default template with no changes in the git repo

### What is the expected behavior?

A render of yaml files 

### What do you see instead?

An error with getting bitnami/common includes in mastodon/templates/web/service.yaml

```
Error: template: mastodon/templates/web/service.yaml:11:14: executing "mastodon/templates/web/service.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: mastodon/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: mastodon/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
helm.go:84: [debug] template: mastodon/templates/web/service.yaml:11:14: executing "mastodon/templates/web/service.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: mastodon/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: mastodon/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```

### Additional information

This is a clean checkout of bitnami/charts:

```
git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

Perhaps I'm doing something wrong?  My intent was test template renders for a PR I was working on that I found in mastodon 3.2.3. Is there a trick to running helm template for local  file renders for bitnami charts?

 Chart.lock is also default:

https://github.com/bitnami/charts/blob/main/bitnami/mastodon/Chart.lock
```
dependencies:
- name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 18.3.3
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.2.9
- name: elasticsearch
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 19.13.10
- name: minio
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.10.0
- name: apache
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 9.6.5
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.13.3
digest: sha256:37743c67ef81fea043de7568b2f816312b1b6027dc6693469d3372218d28100e
generated: "2023-11-16T02:29:56.400648442Z"
```
