### ISSUE TITLE
[bitnami/solr] health check probes not working

### ISSUE THREAD

**Issue by Sierra1011** [bitnami/charts#21201]
### Name and Version

bitnami/solr 8.3.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploying a HelmRelease with FluxCD
2. Use default values
3. Flux reconciler reports a rendering error:
4. Still using otherwise default values, set `enabled: false` for `livenessProbe`, `readinessProbe`, and `startupProbe`.
5. Flux now reconciles with no issue... but also no probes.
6. Using the default values, perform a manual installation using `helm install solr bitnami/solr`, which works.

When doing a `helm template bitnami/solr` with default values, we see the relevant values are duplicated:
```
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 40
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
            initialDelaySeconds: 40
            timeoutSeconds: 15
            failureThreshold: 6
            periodSeconds: 10
            successThreshold: 1
```
This is ignored in Helm because in the case of duplicate values, the lattermost is used and any previous values ignored. Flux is more stringent and does not allow this.

### Are you using any custom parameters or values?

blank/default values with manual Helm: :ballot_box_with_check: 
blank/default values with FluxCD: :negative_squared_cross_mark: 
these values with FluxCD: :ballot_box_with_check: 
```
livenessProbe:
  enabled: false
startupProbe:
  enabled: false
readinessProbe:
  enabled: false
```

### What is the expected behavior?

The YAML is rendered correctly and installs.

### What do you see instead?

The YAML is duplicated and will not install:
```
Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 138: mapping key "failureThreshold" already defined at line 131
  line 136: mapping key "initialDelaySeconds" already defined at line 132
  line 139: mapping key "periodSeconds" already defined at line 133
  line 140: mapping key "successThreshold" already defined at line 134
  line 137: mapping key "timeoutSeconds" already defined at line 135
  line 155: mapping key "failureThreshold" already defined at line 148
  line 153: mapping key "initialDelaySeconds" already defined at line 149
  line 156: mapping key "periodSeconds" already defined at line 150
  line 157: mapping key "successThreshold" already defined at line 151
  line 154: mapping key "timeoutSeconds" already defined at line 152
```

### Additional information

This is probably because the template is both setting a default value for subvalues of `*nessProbes` and then including default values:
```
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.livenessProbe "enabled") "context" $) | nindent 12 }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
```

Issue opened as requested in https://github.com/bitnami/charts/issues/16439
