### ISSUE TITLE
[bitnami/mongodb] MongoDB crashloop when provided custom configuration

### ISSUE THREAD

**Issue by tadasgedgaudas** [bitnami/charts#21210]
### Name and Version

bitnami/mongodb:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

Deploying on kubernetes with simply:

```
helm install mongodb oci://registry-1.docker.io/bitnamicharts/mongodb -n mongodb-main -f mongodb_values.yaml -n mongodb-main
```

Cannot see what's the error:

It's restarting after 

`Deploying MongoDB from scratch`

```
mongodb 14:35:15.43 INFO  ==> 
mongodb 14:35:15.43 INFO  ==> Welcome to the Bitnami mongodb container
mongodb 14:35:15.43 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 14:35:15.43 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 14:35:15.43 INFO  ==> 
mongodb 14:35:15.44 INFO  ==> ** Starting MongoDB setup **
mongodb 14:35:15.45 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 14:35:15.53 INFO  ==> Initializing MongoDB...
mongodb 14:35:15.54 INFO  ==> Deploying MongoDB from scratch...
```

### Are you using any custom parameters or values?

```
persistence:
  mountPath: /bitnami/mongodb/data/db

configuration: |-
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
  systemLog:
    destination: file
    quiet: true
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    bindIp: 0.0.0.0
    #bindIpAll: true
  replication:
    replSetName: rs0
    enableMajorityReadConcern: true
  processManagement:
        fork: false
        pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
  setParameter:
       enableLocalhostAuthBypass: true
  security:
    authorization: enabled
    keyFile: /opt/bitnami/mongodb/conf/keyfile
```

### What is the expected behavior?

Successfuly deployed MongoDB

### What do you see instead?

Container restarting

### Additional information

If I don't provide the custom configuration the deployment is successful
