### ISSUE TITLE
Bitnami/minio: the generated admin password is changing each time - in loop

### ISSUE THREAD

**Issue by cdtzabra** [bitnami/charts#21223]
### Name and Version

Bitnami/minio 12.10.2

### What architecture are you using?

Argocd > Bitnami/minio in distributed mode

### What steps will reproduce the bug?

I deployed the bitnami/minio chart yesterday 
And today, I noticed that the generated admin password is not working anymore
I got this error displayed in the browser **The request signature we calculated does not match the signature you provided. Check your key and signing method.**

Then I use `kubectl get secret --namespace minio minio -o jsonpath="{.data.root-password}" | base64 -d` to get the new password.

Some minutes later, I noticed the same issue. The password is not working anymore.

A new password has been generated again

The chart is deployed through ArgoCD

Nothing has been modified after the deployment except the ing url

### Are you using any custom parameters or values?

```yaml
minio:
  extraEnvVarsSecret: minio-kms-key

  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: s3-console.xxxxxx.com
    path: /
    pathType: ImplementationSpecific
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls: true
    
  apiIngress:
    enabled: true
    ingressClassName: "nginx"
    hostname: s3.xxxxxx.com
    path: /
    pathType: ImplementationSpecific
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls: true

  persistence:
    enabled: true
    storageClass: "thin-csi"
    size: 250Gi 
    existingClaim: ""
    
  auth:
    rootUser: admin
    rootPassword: ""
    existingSecret: ""
    forcePassword: false

  ## defaultBuckets: "my-bucket, my-second-bucket"
  defaultBuckets: ""

  statefulset:
    # There are two valid pod management policies: OrderedReady and Parallel
    podManagementPolicy: Parallel
    replicaCount: 2
    ## @param statefulset.drivesPerNode Number of drives attached to every node (only for MinIO&reg; distributed mode)
    drivesPerNode: 4
```

### What is the expected behavior?

admin password must be generated only once and persisted

### What do you see instead?

admin password regenerated over and over for no good reason

**Comment by fevisera** [comment]
Hi @cdtzabra,

Could you set `image.debug` to `true` and share the logs? That may help us investigate what is going on.

Thanks!

**Comment by cdtzabra** [comment]
I set the debug option

```
k get sts minio -o yaml | grep -i debug -A 2
        - name: BITNAMI_DEBUG
          value: "false"
        - name: MINIO_DISTRIBUTED_MODE_ENABLED
k get sts minio -o yaml | grep -i debug -A 2
        - name: BITNAMI_DEBUG
          value: "true"
        - name: MINIO_DISTRIBUTED_MODE_ENABLED
 ```


I'll add a log if I see anything interesting.

**Comment by cdtzabra** [comment]
Hello @fevisera 

There are no additional logs despite `debug=true`.

```
  containers:
  - env:
    - name: BITNAMI_DEBUG
      value: "true"
```

And even when the error `The request signature we calculated does not match the signature you provided. Check your key and signing method.` is displayed on the browser, there is no special log in the pods.


```
$ k logs minio-0
 12:58:44.88 INFO  ==> 
 12:58:44.88 INFO  ==> Welcome to the Bitnami minio container
 12:58:44.88 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
 12:58:44.88 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
 12:58:44.88 INFO  ==> 
 12:58:44.88 INFO  ==> ** Starting MinIO setup **
minio 12:58:44.90 DEBUG ==> Validating settings in MINIO_* env vars..
minio 12:58:44.91 DEBUG ==> Skipping MinIO client configuration...
 12:58:44.92 INFO  ==> ** MinIO setup finished! **

minio 12:58:44.93 INFO  ==> ** Starting MinIO **
Waiting for all MinIO sub-systems to be initialize...
Automatically configured API requests per node based on available memory on the system: 153
All MinIO sub-systems initialized successfully in 5.119223ms
MinIO Object Storage Server
Copyright: 2015-2023 MinIO, Inc.
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Version: DEVELOPMENT.2023-11-20T22-40-07Z (go1.20.11 linux/amd64)

Status:         8 Online, 0 Offline. 
S3-API: http://localhost:9000 
Console: http://172.23.76.24:9001 http://127.0.0.1:9001 

Documentation: https://min.io/docs/minio/linux/index.html

 You are running an older version of MinIO released 3 weeks before the latest release 
 Update: Run `mc admin update` 
 ```
 
 
 ```
  12:58:26.91 INFO  ==> 
 12:58:26.91 INFO  ==> Welcome to the Bitnami minio container
 12:58:26.91 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
 12:58:26.91 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
 12:58:26.91 INFO  ==> 
 12:58:26.91 INFO  ==> ** Starting MinIO setup **
minio 12:58:26.93 DEBUG ==> Validating settings in MINIO_* env vars..
minio 12:58:26.94 DEBUG ==> Skipping MinIO client configuration...
 12:58:26.94 INFO  ==> ** MinIO setup finished! **

minio 12:58:26.95 INFO  ==> ** Starting MinIO **
Waiting for all MinIO sub-systems to be initialize...
Automatically configured API requests per node based on available memory on the system: 152
All MinIO sub-systems initialized successfully in 3.796497ms

 You are running an older version of MinIO released 3 weeks before the latest release 
 Update: Run `mc admin update` 



API: SYSTEM()
Time: 12:58:28 UTC 12/18/2023
DeploymentID: 0aaab06f-b3d5-4d9b-b4a5-9674d5a4f5ce
Error: Drive: http://minio-0.minio-headless.infra-minio.svc.cluster.local:9000/bitnami/minio/data-2 returned Authentication failed, check your access credentials (*fmt.wrapError)
       endpoint="http://minio-0.minio-headless.infra-minio.svc.cluster.local:9000/bitnami/minio/data-2"
       3: internal/logger/logger.go:248:logger.LogAlwaysIf()
       2: cmd/prepare-storage.go:51:cmd.glob..func9.1()
       1: cmd/erasure-sets.go:233:cmd.(*erasureSets).connectDisks.func2()

API: SYSTEM()
Time: 12:58:28 UTC 12/18/2023
DeploymentID: 0aaab06f-b3d5-4d9b-b4a5-9674d5a4f5ce
Error: Drive: http://minio-0.minio-headless.infra-minio.svc.cluster.local:9000/bitnami/minio/data-3 returned Authentication failed, check your access credentials (*fmt.wrapError)
       endpoint="http://minio-0.minio-headless.infra-minio.svc.cluster.local:9000/bitnami/minio/data-3"
       3: internal/logger/logger.go:248:logger.LogAlwaysIf()
       2: cmd/prepare-storage.go:51:cmd.glob..func9.1()
       1: cmd/erasure-sets.go:233:cmd.(*erasureSets).connectDisks.func2()

API: SYSTEM()
Time: 12:58:28 UTC 12/18/2023
DeploymentID: 0aaab06f-b3d5-4d9b-b4a5-9674d5a4f5ce
Error: Drive: http://minio-0.minio-headless.infra-minio.svc.cluster.local:9000/bitnami/minio/data-0 returned Authentication failed, check your access credentials (*fmt.wrapError)
       endpoint="http://minio-0.minio-headless.infra-minio.svc.cluster.local:9000/bitnami/minio/data-0"
       3: internal/logger/logger.go:248:logger.LogAlwaysIf()
       2: cmd/prepare-storage.go:51:cmd.glob..func9.1()
       1: cmd/erasure-sets.go:233:cmd.(*erasureSets).connectDisks.func2()

API: SYSTEM()
Time: 12:58:28 UTC 12/18/2023
DeploymentID: 0aaab06f-b3d5-4d9b-b4a5-9674d5a4f5ce
Error: Drive: http://minio-0.minio-headless.infra-minio.svc.cluster.local:9000/bitnami/minio/data-1 returned Authentication failed, check your access credentials (*fmt.wrapError)
       endpoint="http://minio-0.minio-headless.infra-minio.svc.cluster.local:9000/bitnami/minio/data-1"
       3: internal/logger/logger.go:248:logger.LogAlwaysIf()
       2: cmd/prepare-storage.go:51:cmd.glob..func9.1()
       1: cmd/erasure-sets.go:233:cmd.(*erasureSets).connectDisks.func2()

API: SYSTEM()
Time: 12:58:32 UTC 12/18/2023
DeploymentID: 0aaab06f-b3d5-4d9b-b4a5-9674d5a4f5ce
Error: Marking minio-0.minio-headless.infra-minio.svc.cluster.local:9000 offline temporarily; caused by Post "http://minio-0.minio-headless.infra-minio.svc.cluster.local:9000/minio/lock/v7/lock": lookup minio-0.minio-headless.infra-minio.svc.cluster.local on 172.23.0.2:53: no such host (*fmt.wrapError)
       7: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
       6: internal/logger/logonce.go:149:logger.LogOnceIf()
       5: internal/rest/client.go:319:rest.(*Client).Call()
       4: cmd/lock-rest-client.go:64:cmd.(*lockRESTClient).callWithContext()
       3: cmd/lock-rest-client.go:96:cmd.(*lockRESTClient).restCall()
       2: cmd/lock-rest-client.go:115:cmd.(*lockRESTClient).Lock()
       1: internal/dsync/drwmutex.go:470:dsync.lock.func1()
Client 'http://minio-0.minio-headless.infra-minio.svc.cluster.local:9000/minio/lock/v7' re-connected in 18.56585447s
MinIO Object Storage Server
Copyright: 2015-2023 MinIO, Inc.
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Version: DEVELOPMENT.2023-11-20T22-40-07Z (go1.20.11 linux/amd64)

Status:         8 Online, 0 Offline. 
S3-API: http://localhost:9000 
Console: http://172.23.7.162:9001 http://127.0.0.1:9001 

Documentation: https://min.io/docs/minio/linux/index.html
```
