### ISSUE TITLE
appVersion in charts not matching image tag

### ISSUE THREAD

**Issue by fvogl** [bitnami/charts#21230]
### Name and Version

grafana

### What architecture are you using?

None

### What steps will reproduce the bug?

This time with Grafana and last week with RabbitMQ you publish a new helm chart with an appVersion x but in the values, you use an older image tag.

e.g. now grafana
```yaml
appVersion: 10.2.2
version: 9.6.2
```
but in the values
```yaml
image:
  registry: docker.io
  repository: bitnami/grafana
  tag: 10.2.0-debian-11-r3
```

### What do you see instead?

Please make sure `appVersion` matches the image tag you're using.
