### ISSUE TITLE
Not valid Secret generated when enabled the authentication into the gateway

### ISSUE THREAD

**Issue by borrown** [bitnami/charts#21282]
### Name and Version

bitnami/grafana-loki 2.11.16

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In a machine where is installed helm, configured the bitnami repository and having the values.yaml file with next content:

```yaml
gateway:
  auth:
    enabled: true
    username: myuser 
    password: tobechanged
```

Run next command in a shell:

```cmd
helm install loki-instance grafana-loki -f l.yaml --dry-run
```

We can find into the generated Secret with name loki-instance-grafana-loki-gateway the next wrong .data:

```yaml
data:
  password: "\"dG9iZWNoYW5nZWQ=\""
```

### Are you using any custom parameters or values?

gateway:
  auth:
    enabled: true
    username: myuser 
    password: tobechanged

### What is the expected behavior?

A valid Secret generated:

```yaml
# Source: grafana-loki/templates/gateway/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: loki-instance-grafana-loki-gateway
  namespace: "argocd"
  labels:
    app.kubernetes.io/instance: loki-instance
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana-loki
    app.kubernetes.io/version: 1.25.2
    helm.sh/chart: grafana-loki-2.11.11
    app.kubernetes.io/part-of: grafana-loki
    app.kubernetes.io/component: gateway
type: Opaque
data:
  password: "dG9iZWNoYW5nZWQK"
  htpasswd: "bXl1c2VyOiQyYSQxMCRuYXNzQzBJSXVFa091dXZlcmkxNGhPYXBUTXRxdHJJNXB4LnAzUmEzYU1DVzl5eDgwV1ZTRw=="
```

### What do you see instead?

Next secret is generated:

```yaml
# Source: grafana-loki/templates/gateway/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: loki-instance-grafana-loki-gateway
  namespace: "argocd"
  labels:
    app.kubernetes.io/instance: loki-instance
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana-loki
    app.kubernetes.io/version: 1.25.2
    helm.sh/chart: grafana-loki-2.11.11
    app.kubernetes.io/part-of: grafana-loki
    app.kubernetes.io/component: gateway
type: Opaque
data:
  password: "\"dG9iZWNoYW5nZWQ=\""
  htpasswd: "bXl1c2VyOiQyYSQxMCRuYXNzQzBJSXVFa091dXZlcmkxNGhPYXBUTXRxdHJJNXB4LnAzUmEzYU1DVzl5eDgwV1ZTRw=="
```

With a not valid value for .data.password ( "\"dG9iZWNoYW5nZWQ=\"")
