### ISSUE TITLE
[bitnami/mongodb] Setting Replica Set Member Priority

### ISSUE THREAD

**Issue by emahdij** [bitnami/charts#21291]
### Name and Version

bitnami/mongodb:14.2.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hello Bitnami Charts Team,

I am currently using the Bitnami MongoDB Helm chart to deploy a MongoDB replica set on my Kubernetes cluster. I am attempting to set different priorities for the replica set members to control the election of the primary node.

Here is how I have configured the priorities in my `values.yaml` file:
```yaml
  configurationSettings:
    enabled: true
    configuration: |
      members[0].priority: 3
      members[1].priority: 2
      members[2].priority: 1
  ```

However, after deploying the chart with these settings, it does not appear that the priorities are being applied to the replica set members as expected. The members do not reflect the priority settings from the configuration.

Could you provide some guidance on how to correctly set the priorities for replica set members using the Bitnami MongoDB Helm chart? If this configuration is not supported, could this be considered for future addition to the chart features?

I appreciate any help or information you can provide, and thank you for maintaining this useful chart.

Best regards,
Mehdi Jafarpour
