### ISSUE TITLE
[bitnami/discourse] Integrated postgresql version is to new, discourse fails to connect

### ISSUE THREAD

**Issue by psych0d0g** [bitnami/charts#21294]
### Name and Version

bitnami/discourse 12.0.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

deploy fresh discourse with postgresql subchart enabled

### What is the expected behavior?

discourse should connect to the postgresql db

### What do you see instead?

authentication fails for the main postgresql and the discourse postgresql user

### Additional information

it does work when i specify the image version for the postgresql subchart manually:

```yaml
      image:
        registry: docker.io
        repository: bitnami/postgresql
        tag: 13.13.0-debian-11-r14
```

see the official discourse docker templates (where the latest postgresql version officially supported is version 13):
https://github.com/discourse/discourse_docker/tree/master/templates
