### ISSUE TITLE
[bitnami/mariadb-galera] Charts > 9.0.5 are not populating labels of volumeClaimTemplates passed via values.yaml

### ISSUE THREAD

**Issue by babasaikiran** [bitnami/charts#21307]
### Name and Version

bitnami/mariadb-galera 9.1.0 and Above

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`helm template mariadb ./mariadb-galera/  --set persistence.labels.foo=bar,persistence.labels.baz=qux`

### What is the expected behavior?

**Chart version 9.0.5**:

```yaml
# Source: mariadb-galera/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
...
...
volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/name: mariadb-galera
          app.kubernetes.io/instance: mariadb
          app.kubernetes.io/managed-by: Helm
          foo: bar
          baz: qux
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
```

### What do you see instead?

**Chart version 9.1.0 and Above**:

```yaml
# Source: mariadb-galera/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
...
...
volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/name: mariadb-galera
          app.kubernetes.io/instance: mariadb
          app.kubernetes.io/managed-by: Helm
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
```

### Additional information

This is failing the upgrade of MariaDB to latest where 9.0.5 or earlier chart is used to deploy.
