### ISSUE TITLE
[bitnami/grafana-loki] Attempting to use update strategy other than RollingUpdate causes error

### ISSUE THREAD

**Issue by bpfoster** [bitnami/charts#21311]
### Name and Version

bitnami/grafana-loki 2.11.16

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set an updateStrategy to some other type, e.g. `compactor.updateStrategy.type = Recreate`
2. Attempt to install

### Are you using any custom parameters or values?

```yaml
compactor:
  updateStrategy:
    type: Recreate
```

### What is the expected behavior?

Chart deploys with the deployment having appropriate update strategy

### What do you see instead?

Deployment of chart fails:

```
Error: UPGRADE FAILED: cannot patch "test-loki-compactor" with kind Deployment: Deployment.apps "test-loki-compactor" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
```

**Comment by bpfoster** [comment]
Values specify a default empty object for `rollingUpdate`
https://github.com/bitnami/charts/blob/main/bitnami/grafana-loki/values.yaml#L450-L452

This cannot be overridden with `null`
```
compactor:
  updateStrategy:
    type: Recreate
    rollingUpdate: null
```

results in 
```
coalesce.go:286: warning: cannot overwrite table with non table for loki.compactor.updateStrategy.rollingUpdate (map[])
```
