### ISSUE TITLE
Pods doesn't connect to new redis master if the old master keeps crashing

### ISSUE THREAD

**Issue by MohamadTahir** [bitnami/charts#21330]
### Name and Version

bitnamicharts/redis 18.1.2

### What architecture are you using?

None

### What steps will reproduce the bug?

1. I am installing Redis using the attached values.yaml. 

1. I have an ASP .net core 7 webapi project that is connecting to Redis using those Nuget packages 
```
<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="7.0.5" />
<PackageReference Include="AspNetCore.HealthChecks.Redis" Version="7.0.1" />
<PackageReference Include="ZiggyCreatures.FusionCache.Backplane.StackExchangeRedis" Version="0.19.0" />
<PackageReference Include="ZiggyCreatures.FusionCache.Serialization.SystemTextJson" Version="0.19.0" />
```
the client works without any issues in normal cases, even in the case of graceful failover nothing goes wrong, the client switches over to the new Redis master.

the issue occurs when the current master starts crashing for any reason (to produce this issue purposefully update the master image to an image that doesn't exist)

the pod will start crashing because it keeps trying to connect to the old master even though there is a new master elected, the health checks will fail.

### Are you using any custom parameters or values?
```yaml
global:
  imageRegistry: reg.dev.krd

image:
  tag: 7.2.1-debian-11-r19

auth:
  existingSecret: redis
  existingSecretPasswordKey: password

architecture: replication

master:
  persistence: { enabled: false }
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 20m

replica:
  persistence: { enabled: false }
  replicaCount: 3
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 20m

sentinel:
  enabled: true
  masterSet: myset
  image: { tag: 7.2.1-debian-11-r19 }
  getMasterTimeout: 120
  resources:
    limits:
      memory: 16Mi
    requests:
      cpu: 5m
```
### What is the expected behavior?

I am expecting my client to switch to the new master.

### What do you see instead?

the client keeps trying to connect to the old master
