### ISSUE TITLE
[bitnami/elasticsearch] Can't reference to Secret

### ISSUE THREAD

**Issue by pomland-94** [bitnami/charts#21385]
### Name and Version

bitnami/elasticsearch:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

Hey,
I try to deploy Elastisearch with Kibana, I let Helm autogenerate the elastic-password Values so I let the following Value empty:

```yaml
global:
  security:
  enabled: false
  elasticPassword: ""

```

Now at the end of the values.yaml where I can configure Kibana, I wan't to reference to this secret which get's deployed at the Helm install Stage, I try to use the following Snippet to do this:

```yaml
kibana:
  elasticsearch:
    security:
      auth:
        enabled: true
        ...
        elasticsearchPasswordSecret: '{{ include "elasticsearch.secretName" . }}'
```

But this does not work, I get the following error:

### What do you see instead?

```console
[root::admingw-01]
~/yaml/elasticsearch: helm install --namespace elastic-search --generate-name bitnami/elasticsearch -f values.yaml
Error: INSTALLATION FAILED: template: elasticsearch/charts/kibana/templates/deployment.yaml:160:27: executing "elasticsearch/charts/kibana/templates/deployment.yaml" at <tpl .Values.elasticsearch.security.auth.elasticsearchPasswordSecret .>: error calling tpl: error during tpl function execution for "{{ include \"elasticsearch.secretName\" . }}": template: elasticsearch/charts/kibana/templates/deployment.yaml:1:3: executing "elasticsearch/charts/kibana/templates/deployment.yaml" at <include "elasticsearch.secretName" .>: error calling include: template: elasticsearch/templates/_helpers.tpl:394:55: executing "elasticsearch.secretName" at <.Values.security.existingSecret>: nil pointer evaluating interface {}.existingSecret
[root::admingw-01]
~/yaml/elasticsearch:
```

### Additional information

Maybe this is a Bug??
