### ISSUE TITLE
[bitnami/mongodb] cronjob includes `.securityContext.enabled`

### ISSUE THREAD

**Issue by jcpunk** [bitnami/charts#21469]
### Name and Version

bitnami/mongodb 14.4.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install helm chart with backup cronjob enabled on kubernetes 1.27

### Are you using any custom parameters or values?

```yaml
---
architecture: standalone

directoryPerDB: true

useStatefulSet: true

auth: {"databases": ["daqconfigdb"], "passwords": ["password"], "rootPassword": "password", "rootUser": "root", "usernames": ["daqconfig"]}

serviceBindings:
  enabled: true

persistence:
  enabled: true
  storageClass: local-path


backup:
  enabled: true
  successfulJobsHistoryLimit: 1


affinity:
 nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: node-role.kubernetes.io/worker
         operator: Exists
```

### What is the expected behavior?

Cronjob installs

### What do you see instead?

```
  daqconfig/CronJob/daqconfig-mongodb-mongodump: failed to patch daqconfig/CronJob/daqconfig-mongodb-mongodump: failed to create typed patch object (daqconfig/daqconfig-mongodb-mongodump; batch/v1, Kind=CronJob): errors:
  .spec.jobTemplate.spec.template.spec.containers[name="daqconfig-mongodb-mongodump"].securityContext.enabled: field not declared in schema
  .spec.jobTemplate.spec.securityContext: field not declared in schema
```

### Additional information

This worked in a previous release (13.x series)
