### ISSUE TITLE
Cassandra chart should not generate ConfigMap for empty directories

### ISSUE THREAD

**Issue by matthewadams** [bitnami/charts#2146]
**Which chart**:
bitnami/cassandra:5.1.4

**Describe the bug**
The glob pattern `files/conf/*` in `templates/configuration-cm` and the glob pattern `files/docker-entrypoint-initdb.d/*` in `templates/initdb-configmap.yaml` match the `README.md` files in those directories, respectively.  This causes the chart to create a `ConfigMap` for each template whose contents are the `README.md`.  If there are no files besides `README.md`, the template should _not_ generate a `ConfigMap`.

**To Reproduce**
1. `helm template bitnami/cassandra`
2. Inspect output, notice that the two templates render the following `ConfigMap`s, when they should _not_ be rendering anything:
```
---
# Source: cassandra/templates/configuration-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-cassandra-configuration
  labels:
    app: cassandra
    chart: cassandra-5.1.4
    release: RELEASE-NAME
    heritage: Helm
data:
  README.md: |
    Place your Cassandra configuration files here. This will override the values set in any configuration environment variable. This will not be used in case the value *existingConfiguration* is used.
  
    More information [here](https://github.com/bitnami/bitnami-docker-cassandra#configuration)
---
# Source: cassandra/templates/initdb-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-cassandra-init-scripts
  labels:
    app: cassandra
    chart: cassandra-5.1.4
    release: RELEASE-NAME
    heritage: Helm
data:
  README.md: |
    You can copy here your custom `.sh` or `.cql` file so they are executed during the first boot of the image.
  
    More info in the [bitnami-docker-cassandra](https://github.com/bitnami/bitnami-docker-cassandra#initializing-a-new-instance) repository.
```

**Expected behavior**
No `ConfigMap`s should be generated by default.

**Version of Helm and Kubernetes**:
- Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.22", GitCommit:"9bae7fcacb520dfee658b26cc1a9643bf787dfc3", GitTreeState:"clean", BuildDate:"2020-02-27T18:43:37Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
It appears as though this functionality doesn't work anyway with Helm 3, because a chart is disallowed, AFAICT, from accessing files outside of the chart itself.  This requires the user to create a parent chart that depends on this chart, create his own `ConfigMap`s, and set `initDBConfigMap` and `existingConfiguration` himself.  This chart, really, should _only_ support `initDBConfigMap` and `existingConfiguration` and the templates `templates/configuration-cm` & `templates/initdb-configmap.yaml` ought to be removed.  If I'm wrong, please correct.  I got my info from https://github.com/helm/helm/issues/4026 & https://github.com/helm/helm/issues/3276.
