### ISSUE TITLE
[bitnami/wordpress] Wordpress Database (RDS) Too Many Connections

### ISSUE THREAD

**Issue by mdeppe68ob** [bitnami/charts#21481]
### Name and Version

bitnami/wordpress-18.1.23

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When using RDS @5.7-mysql-aurora-2-12.0 modifications or changes to plugins/themes cause database connection saturation.
![mysql_wp](https://github.com/bitnami/charts/assets/86248959/66458eb3-c305-4e08-871f-1b2f2a7ae4e8)

### Are you using any custom parameters or values?
```yaml
project: development
source:
  repoURL: 'https://charts.bitnami.com/bitnami'
  targetRevision: 18.1.23
  helm:
    parameters:
      - name: allowEmptyPassword
        value: 'false'
      - name: autoscaling.enabled
        value: 'true'
      - name: externalCache.host
        value: xxxx
      - name: externalDatabase.database
        value: wp
      - name: externalDatabase.host
        value: xxxx
      - name: externalDatabase.user
        value: xxx
      - name: global.storageClass
        value: xxx
      - name: mariadb.enabled
        value: 'false'
      - name: externalDatabase.password
        value: xxxx 
      - name: externalDatabase.host
        value: wordpress-xxxx.cluster-xxxx.rds.amazonaws.com
      - name: externalDatabase.user
        value: xxx
      - name: global.storageClass
        value: xxx
      - name: mariadb.enabled
        value: 'false'
      - name: externalDatabase.password
        value: xxx
      - name: metrics.enabled
        value: 'true'
      - name: metrics.serviceMonitor.enabled
        value: 'false'
      - name: metrics.serviceMonitor.interval
        value: '30'
      - name: persistence.accessMode
        value: ReadWriteMany
      - name: 'persistence.accessModes[0]'
        value: ReadWriteMany
      - name: persistence.storageClass
        value: xxx
      - name: persistence.size
        value: 100Gi
      - name: replicaCount
        value: '1'
      - name: resources.requests.cpu
        value: 1300m
      - name: service.type
        value: NodePort
      - name: resources.requests.memory
        value: 1512Mi
      - name: startupProbe.enabled
        value: 'true'
      - name: wordpressBlogName
        value: xxx
      - name: volumePermissions.enabled
        value: 'false'
      - name: wordpressConfigureCache
        value: 'true'
      - name: wordpressEmail
        value: xxx
      - name: wordpressPassword
        value: oxxx
     - name: wordpressConfigureCache
        value: 'true'
      - name: autoscaling.minReplicas
        value: '1'
  chart: wordpress
destination:
  server: 'xxxx'
  namespace: wordpress
```
### What is the expected behavior?

Normal operation through either filesystem copies of plugin/themes or dashboard based additions/removals of the same.

### What do you see instead?

Database connections peak to > max connection values * number nodes in replicaset.
This behavior fails the application.
