### ISSUE TITLE
Not able to fetch the EXTERNAL_ACCESS_HOST_USE_PUBLIC_IP in Kafka Chart

### ISSUE THREAD

**Issue by junaid18183** [bitnami/charts#21498]
### Name and Version

bitnami/kafka 26.4.3

### What architecture are you using?

None

### What steps will reproduce the bug?

Using below inp

### Are you using any custom parameters or values?

```yaml
controller:
  replicaCount: 1
listeners:
  client:
    protocol: "PLAINTEXT"
externalAccess:
  enabled: true
  controller:
    service:
      type: NodePort
      nodePorts:
        - 30991
serviceAccount:
  create: true
rbac:
  create: true
```

### What is the expected behavior?

I am expecting the 
EXTERNAL://<my_external_ip>:30991 in the /opt/bitnami/kafka/config/server.properties file 

### What do you see instead?

I am getting  the 
EXTERNAL://:30991    in the /opt/bitnami/kafka/config/server.properties file 

### Additional information

The https://github.com/bitnami/charts/blob/main/bitnami/kafka/templates/scripts-configmap.yaml#L160 

```
curl -s https://ipinfo.io/ip
```
Does not report anything.  Either we have to use 

`curl -s https://ipinfo.io/` and  parse the ipinfor using `jq` or use the 

`curl -s https://ifconfig.me/`

I have sent a PR -  https://github.com/bitnami/charts/pull/21499
