### ISSUE TITLE
[bitnami/keycloak] unable to use secrets to set credentials (probable decoding issue)

### ISSUE THREAD

**Issue by ETisREAL** [bitnami/charts#21491]
### Name and Version

bitnami/keycloak:17.3.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am trying to set the admin password using a secret. Here is the values.yaml section
```yaml
auth:
  adminUser: admin
  # adminPassword: "password"
  existingSecret: "keycloak-admin-secret"
  passwordSecretKey: "admin-password"
  annotations: {}
```

Here is the output 
```
password
```
of the kubectl command: 
```
kubectl get secret keycloak-admin-secret-o jsonpath='{.data.admin-password}' | base64 -d
```

### Are you using any custom parameters or values?

Yes, these ones are the relative ones:
```yaml
auth:
  adminUser: admin
  # adminPassword: "password"
  existingSecret: "keycloak-admin-secret"
  passwordSecretKey: "admin-password"
  annotations: {}
```

### What is the expected behavior?

Since the secret exists and is in the same ns, and also the secret key is referred to correctly in the values.yaml, it should pick up the password form the secret

### What do you see instead?
```
Warning  Failed     2s    kubelet            Error: failed to create containerd task: failed to create shim task:  │
│ OCI runtime create failed: runc create failed: unable to start container process: error during container init: envir │
│ onment variable value can't contain null(\x00): "KEYCLOAK_ADMIN_PASSWORD=p\x00a\x00s\x00s\x00w\x00o\x00r\x00d\x00":  │
│ unknown
```

**Comment by javsalgar** [comment]
Hi,

Could you let us know how you created the secret? We would like to reproduce the issue in our side

**Comment by ETisREAL** [comment]
Sure, sorry I forgot to add it. Here is the secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
type: Opaque
data:
  admin-password: cGFzc3dvcmQK

```

and the command I used
```

kubectl apply -f keycloak-admin-secret.yaml

```
