### ISSUE TITLE
[bitnami/redis-cluster] When trying to add new nodes to a redis cluster, nodes start but are not added into cluster

### ISSUE THREAD

**Issue by pilot513** [bitnami/charts#21571]
### Name and Version

bitnami/redis-cluster 9.1.3

### What architecture are you using?

None

### What steps will reproduce the bug?

```
helm  install  redis-cl -n redis -f ./values-redisCluster.yaml ./redis

helm  upgrade --install --atomic --wait --timeout=5m redis-cl -n redis --set "password=$REDIS_PASSWORD,cluster.nodes=8,cluster.update.addNodes=true,cluster.update.currentNumberOfNodes=6,cluster.init=false" -f ./values-redisCluster.yaml ./redis
```

### Are you using any custom parameters or values?

./values-redisCluster.yaml
```
persistence:
  enabled: true
  size: 512Mi

redis:
  resources:
    limits:
      cpu: 500m
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 256Mi
  useAOFPersistence: "no"
  configmap: |-
    save ""
    appendonly no
    maxmemory 512mb
    maxmemory-policy volatile-lru
    cluster-require-full-coverage no

metrics:
  enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
```

### What is the expected behavior?

From new node (new pod):

![image](https://github.com/bitnami/charts/assets/28645933/7f4e3451-698d-48ba-95a9-c320d4b2170c)

From "0" node:
![image](https://github.com/bitnami/charts/assets/28645933/d1610161-dd03-48b3-b6d8-1fc948b8628e)

### What do you see instead?

The new pods do not go into ready status, although they are running. Nodes are not joining the cluster.

### Additional information

Before try this, I read https://github.com/bitnami/charts/issues/3743

**Comment by pilot513** [comment]
So, if don't use custom config-values (set as is) scale work fine:
```
helm upgrade --timeout 600s redis-cluster -n redis-cluster --set "password=$REDIS_PASSWORD,cluster.nodes=8,cluster.update.addNodes=true,cluster.update.currentNumberOfNodes=6,cluster.init=false" .
```

**Comment by juan131** [comment]
Hi @pilot513 

I wasn't able to reproduce the issue using a simplified version of your values:

```yaml
redis:
  useAOFPersistence: "no"
  configmap: |-
    save ""
    appendonly no
    maxmemory 512mb
    maxmemory-policy volatile-lru
    cluster-require-full-coverage no
```

Steps followed:

```console
$ kubectl create ns redis
$ helm install redis-cl --namespace redis \
  --values values-redis-cluster.yaml \
  --version 9.1.3 \
  oci://registry-1.docker.io/bitnamicharts/redis-cluster
$ export REDIS_PASSWORD=$(kubectl get secret --namespace "redis" redis-cl-redis-cluster -o jsonpath="{.data.redis-password}" | base64 -d)
$ helm upgrade redis-cl --namespace redis \
  --values values-redis-cluster.yaml \
  --set "password=$REDIS_PASSWORD" \
  --set cluster.nodes=8 \
  --set cluster.update.addNodes=true \
  --set cluster.update.currentNumberOfNodes=6
  --set cluster.init=false \
  --version 9.1.3 \
   oci://registry-1.docker.io/bitnamicharts/redis-cluster
```

Result:

```console
$ kubectl get pods -n redis
NAME                                          READY   STATUS      RESTARTS       AGE
redis-cl-redis-cluster-0                      1/1     Running     1 (18s ago)    24s
redis-cl-redis-cluster-1                      1/1     Running     0              60s
redis-cl-redis-cluster-2                      1/1     Running     0              66s
redis-cl-redis-cluster-3                      1/1     Running     0              72s
redis-cl-redis-cluster-4                      1/1     Running     0              78s
redis-cl-redis-cluster-5                      1/1     Running     1 (73s ago)    2m8s
redis-cl-redis-cluster-6                      1/1     Running     1 (119s ago)   2m58s
redis-cl-redis-cluster-7                      1/1     Running     3 (103s ago)   2m58s
redis-cl-redis-cluster-cluster-update-6lftv   0/1     Completed   0              2m58s
$ kubectl exec redis-cl-redis-cluster-0 -n redis -- bash
I have no name!@redis-cl-redis-cluster-0:/$ redis-cli
127.0.0.1:6379> CLUSTER NODES
f0c5ee1736721bc02bf7621a7ca28e0c96d1f209 10.244.0.22:6379@16379 slave 4d921c0144eff29d86ed79f8ba3bbf6177f01ac5 0 1702886991364 2 connected
a1337723d63b46ec23169aec61cc4954ddcbf5ec 10.244.0.20:6379@16379 master - 0 1702886992375 7 connected 0-1364 5461-6826 10923-12287
7124f3e82b63d12f6794e9cacd344da24ca893c9 10.244.0.25:6379@16379 master - 0 1702886991000 3 connected 12288-16383
2f1b434bb1b9b16cef528cbf68bc6d85cf657d10 10.244.0.27:6379@16379 myself,master - 0 1702886993000 1 connected 1365-5460
4d921c0144eff29d86ed79f8ba3bbf6177f01ac5 10.244.0.26:6379@16379 master - 0 1702886989000 2 connected 6827-10922
7ec6a1b340610f012da1719e1561af951611f901 10.244.0.24:6379@16379 slave 7124f3e82b63d12f6794e9cacd344da24ca893c9 0 1702886990000 3 connected
56f4c4b956d64af0d72fd003b4508397d95fe4dc 10.244.0.23:6379@16379 slave a1337723d63b46ec23169aec61cc4954ddcbf5ec 0 1702886993390 7 connected
69d9de88200057ce208d47600bdcae5307c45394 10.244.0.21:6379@16379 slave 2f1b434bb1b9b16cef528cbf68bc6d85cf657d10 0 1702886991000 1 connected
```console

**Comment by pilot513** [comment]
Thanks Juan.
I'm try again reinstall it.
Now, for upgrade I'm used separater '--set' options ( as you)
After update, some pods restarted twice. After that, cluster stabilized to state:
```

**Comment by juan131** [comment]
Hi @pilot513 

Then, you can confirm the cluster could be stabilized, right? Should we consider this solved?

**Comment by pilot513** [comment]
Yes. I tried again, just to check.
After expanding the cluster to 8 nodes, I tried changing the limits and the amount of data memory. In addition,  I added a section:
```
cluster:
  init: false
  nodes: 8
  replicas: 1
```
so that the cluster does not “break” (_without adding the current number of nodes_ (8), the cluster breaks)
The update was successful
