### ISSUE TITLE
Kong does not bootstrap database

### ISSUE THREAD

**Issue by jr-dimedis** [bitnami/charts#21570]
### Name and Version

bitnami/kong 10.1.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy the helm chart with the values and secrets I provided below.

I am doing this with a K8s cluster on the Hetzner (www.hetzner.de) platform.

### Are you using any custom parameters or values?

`values.yaml`:

```yaml
image:
  debug: true

service:
  type: LoadBalancer
  annotations:
    load-balancer.hetzner.cloud/name: kong
    load-balancer.hetzner.cloud/hostname: ***.***.**
    load-balancer.hetzner.cloud/location: fsn1
    load-balancer.hetzner.cloud/type: lb11
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/disable-private-ingress: "true"
    load-balancer.hetzner.cloud/uses-proxyprotocol: "true"

kong:
  extraEnvVars:
    - name: KONG_PROXY_LISTEN
      value: "0.0.0.0:8000 proxy_protocol, 0.0.0.0:8443 ssl proxy_protocol"
    - name: KONG_REAL_IP_HEADER
      value: "proxy_protocol"
    - name: KONG_TRUSTED_IPS
      value: "0.0.0.0/0,::/0"

postgresql:
  auth:
    existingSecret: kong-postgresql-password

  persistence:
    enabled: true
    storageClass: hcloud-volumes
    size: 10Gi
```

Secret created with Terraform:

```terraform
resource "kubernetes_namespace" "kong" {
  metadata {
    name = "kong"
  }

  lifecycle {
    ignore_changes = [ metadata[0].annotations ]
  }
}

resource "random_password" "kong-postgresql-password" {
  length = 16
  special = false
}

resource "kubernetes_secret" "kong-postgresql-secret" {
  depends_on = [kubernetes_namespace.kong]

  metadata {
    name      = "kong-postgresql-password"
    namespace = "kong"
  }

  data = {
    # I have to specify the password twice? (looks like a bug to me)

    # Helm complains without this field
    password = random_password.kong-postgresql-password.result

    # The pod couldn't start without this field
    postgres-password = random_password.kong-postgresql-password.result
  }
}
```

### What is the expected behavior?

Automatic deployment with a bootstrapped PostgreSQL database.

### What do you see instead?

Kong pods do not start and are stuck with this message:

`Waiting for database connection to succeed`

### Additional information

I could bootstrap the database on my own by starting a shell in a kong pod and executing this:

```bash
kong migrations bootstrap
```

Then the pods do start. As well I could see that a migration job was started, which probably did nothing on this fresh database. Unfortunately I do not have any logs from it, but it succeeded.

Kong Ingress Controller pods do start as well and it's working with a simple Hello World app + corresponding Ingress configuration.

But the controller pods go into a crash restart loop with this error message:

```
Error: failed to wait for KongV1beta1KongUpstreamPolicy caches to sync: timed out waiting for cache to be synced for Kind *v1beta1.KongUpstreamPolicy
```

I don't know whether this is related to the bootstrapping problem or another issue.
