### ISSUE TITLE
[bitnami/postgresql] Prevent generating a new password for Secret if the old one is set

### ISSUE THREAD

**Issue by MurzNN** [bitnami/charts#21613]
### Name and Version

bitnami/mariadb 14.1.4

### What is the problem this feature will solve?

When checking the changes before deploying an updated version of the Helm Chart, I always see changes in the Secrets manifests like this:
```diff
my-deployment, my-deployment-mariadb, Secret (v1) has changed:
  apiVersion: v1
  data:
-   mariadb-root-password: XXXXU29tbkFYTw==
+   mariadb-root-password: YYYYOXJuSVVvMw==
  kind: Secret
  metadata:
    labels:
      app.kubernetes.io/managed-by: Helm
...
```
But on the chart deployment, the secret with the password does not change and still has the old value.

### What is the feature you are proposing to solve the problem?

Is there any way to prevent producing the change of the Secret manifest, if the password actually will not change?

Maybe the Helm chart can check and generate the new password only if the existing Secret is missing?

### What alternatives have you considered?

Alternatively, I can use a specific option in the `helm diff` plugin to not show the Secret changes, but this will lead me to miss the change when the password will actually changed.

**Comment by jotamartos** [comment]
Hi @MurzNN,

I just tried to reproduce this but I'm unable to do so. I created a secret 

```
k create secret generic mariadb-secret --from-literal=mariadb-root-password=bitnami --from-literal=mariadb-replication-password=bitnami --from-literal=mariadb-password=bitnami
```

and used it when installing the chart 

```
diff --git a/bitnami/mariadb/values.yaml b/bitnami/mariadb/values.yaml
index 6556fe1bf0..592bd69888 100644
--- a/bitnami/mariadb/values.yaml
+++ b/bitnami/mariadb/values.yaml
@@ -139,7 +139,7 @@ auth:
   replicationPassword: ""
   ## @param auth.existingSecret Use existing secret for password details (`auth.rootPassword`, `auth.password`, `auth.replicationPassword` will be ignored and picked up from this secret). The secret has to contain the keys `mariadb-root-password`, `mariadb-replication-password` and `mariadb-password`
   ##
-  existingSecret: ""
+  existingSecret: "mariadb-secret"
   ## @param auth.forcePassword Force users to specify required passwords
   ##
   forcePassword: false
```

```
helm install mariadb bitnami/mariadb -f values.yaml --version 14.1.4
```

After that, I upgraded and confirmed that the password didn't change 

```
$ k get secret mariadb-secret -o yaml
apiVersion: v1
data:
  mariadb-password: Yml0bmFtaQ==
  mariadb-replication-password: Yml0bmFtaQ==
  mariadb-root-password: Yml0bmFtaQ==
kind: Secret
metadata:
  creationTimestamp: "2023-12-26T16:41:01Z"
  name: mariadb-secret
  namespace: test
  resourceVersion: "66369"
  uid: e395665d-72b7-4c2f-ae09-7bb6c40afbc1
type: Opaque

$ helm upgrade mariadb bitnami/mariadb -f values.yaml --set auth.rootPassword=$MARIADB_ROOT_PASSWORD
...
Release "mariadb" has been upgraded. Happy Helming!
...

$ k get secret mariadb-secret -o yaml
apiVersion: v1
data:
  mariadb-password: Yml0bmFtaQ==
  mariadb-replication-password: Yml0bmFtaQ==
  mariadb-root-password: Yml0bmFtaQ==
kind: Secret
metadata:
  creationTimestamp: "2023-12-26T16:41:01Z"
  name: mariadb-secret
  namespace: test
  resourceVersion: "66369"
  uid: e395665d-72b7-4c2f-ae09-7bb6c40afbc1
type: Opaque
```

**Comment by MurzNN** [comment]
Sorry, I reported the wrong chart name, it's about `postgresql`, steps to reproduce:
1. `helm install my-release oci://registry-1.docker.io/bitnamicharts/postgresql`
2. `helm diff upgrade my-release oci://registry-1.docker.io/bitnamicharts/postgresql`
3. See the changes in diff:
```diff
$ helm diff upgrade my-release oci://registry-1.docker.io/bitnamicharts/postgresql
test-namespace, my-release-postgresql, Secret (v1) has changed:
  # Source: postgresql/templates/secrets.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app.kubernetes.io/instance: my-release
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/version: 16.1.0
      helm.sh/chart: postgresql-13.2.25
    name: my-release-postgresql
    namespace: test-namespace
  data:
-   postgres-password: '-------- # (10 bytes)'
+   postgres-password: '++++++++ # (10 bytes)'
  type: Opaque
```
Please check, and if this can't be fixed by technical reasons, we can close this issue.

**Comment by jotamartos** [comment]
I created the secret again 

```
apiVersion: v1
data:
  password: Yml0bmFtaQ==
  postgres-password: Yml0bmFtaQ==
  replication-password: Yml0bmFtaQ==
kind: Secret
metadata:
  creationTimestamp: "2023-12-27T08:32:38Z"
  name: postgresql-secret
  namespace: test
  resourceVersion: "10808"
  uid: 5bc43ec5-198a-4dbe-802a-32e48eb2a4e2
type: Opaque
```

and installed version 13.2.4 of the chart using that secret: `helm install ... --set auth.existingSecret=postgresql-secret`

The `helm diff upgrade postgresql bitnami/postgresql --set auth.existingSecret=postgresql-secret` command doesn't show any changes in the password parameter

```
test, postgresql, Service (v1) has changed:
  # Source: postgresql/templates/primary/svc.yaml
  apiVersion: v1
  kind: Service
  metadata:
    name: postgresql
    namespace: "test"
    labels:
      app.kubernetes.io/instance: postgresql
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: postgresql
-     app.kubernetes.io/version: 16.0.0
-     helm.sh/chart: postgresql-13.2.4
+     app.kubernetes.io/version: 16.1.0
+     helm.sh/chart: postgresql-13.2.25
      app.kubernetes.io/component: primary
  spec:
    type: ClusterIP
    sessionAffinity: None
    ports:
      - name: tcp-postgresql
        port: 5432
        targetPort: tcp-postgresql
        nodePort: null
    selector:
      app.kubernetes.io/instance: postgresql
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: primary
test, postgresql, StatefulSet (apps) has changed:
  # Source: postgresql/templates/primary/statefulset.yaml
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: postgresql
    namespace: "test"
    labels:
      app.kubernetes.io/instance: postgresql
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: postgresql
-     app.kubernetes.io/version: 16.0.0
-     helm.sh/chart: postgresql-13.2.4
+     app.kubernetes.io/version: 16.1.0
+     helm.sh/chart: postgresql-13.2.25
      app.kubernetes.io/component: primary
  spec:
    replicas: 1
    serviceName: postgresql-hl
    updateStrategy:
      rollingUpdate: {}
      type: RollingUpdate
    selector:
      matchLabels:
        app.kubernetes.io/instance: postgresql
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/component: primary
    template:
      metadata:
        name: postgresql
        labels:
          app.kubernetes.io/instance: postgresql
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: postgresql
-         app.kubernetes.io/version: 16.0.0
-         helm.sh/chart: postgresql-13.2.4
+         app.kubernetes.io/version: 16.1.0
+         helm.sh/chart: postgresql-13.2.25
          app.kubernetes.io/component: primary
      spec:
        serviceAccountName: default
        
        affinity:
          podAffinity:
            
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app.kubernetes.io/instance: postgresql
                      app.kubernetes.io/name: postgresql
                      app.kubernetes.io/component: primary
                  topologyKey: kubernetes.io/hostname
                weight: 1
          nodeAffinity:
            
        securityContext:
          fsGroup: 1001
        hostNetwork: false
        hostIPC: false
        containers:
          - name: postgresql
-           image: docker.io/bitnami/postgresql:16.0.0-debian-11-r16
+           image: docker.io/bitnami/postgresql:16.1.0-debian-11-r16
            imagePullPolicy: "IfNotPresent"
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              privileged: false
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              runAsUser: 1001
              seccompProfile:
                type: RuntimeDefault
            env:
              - name: BITNAMI_DEBUG
                value: "false"
              - name: POSTGRESQL_PORT_NUMBER
                value: "5432"
              - name: POSTGRESQL_VOLUME_DIR
                value: "/bitnami/postgresql"
              - name: PGDATA
                value: "/bitnami/postgresql/data"
              # Authentication
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql-secret
                    key: postgres-password
              # Replication
              # Initdb
              # Standby
              # LDAP
              - name: POSTGRESQL_ENABLE_LDAP
                value: "no"
              # TLS
              - name: POSTGRESQL_ENABLE_TLS
                value: "no"
              # Audit
              - name: POSTGRESQL_LOG_HOSTNAME
                value: "false"
              - name: POSTGRESQL_LOG_CONNECTIONS
                value: "false"
              - name: POSTGRESQL_LOG_DISCONNECTIONS
                value: "false"
              - name: POSTGRESQL_PGAUDIT_LOG_CATALOG
                value: "off"
              # Others
              - name: POSTGRESQL_CLIENT_MIN_MESSAGES
                value: "error"
              - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
                value: "pgaudit"
            ports:
              - name: tcp-postgresql
                containerPort: 5432
            livenessProbe:
              failureThreshold: 6
              initialDelaySeconds: 30
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
              exec:
                command:
                  - /bin/sh
                  - -c
                  - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
            readinessProbe:
              failureThreshold: 6
              initialDelaySeconds: 5
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
              exec:
                command:
                  - /bin/sh
                  - -c
                  - -e
                  - |
                    exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
                    [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
            resources:
              limits: {}
              requests:
                cpu: 250m
                memory: 256Mi
            volumeMounts:
              - name: dshm
                mountPath: /dev/shm
              - name: data
                mountPath: /bitnami/postgresql
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
    volumeClaimTemplates:
      - apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: data
        spec:
          accessModes:
            - "ReadWriteOnce"
          resources:
            requests:
              storage: "8Gi"
test, postgresql-hl, Service (v1) has changed:
  # Source: postgresql/templates/primary/svc-headless.yaml
  apiVersion: v1
  kind: Service
  metadata:
    name: postgresql-hl
    namespace: "test"
    labels:
      app.kubernetes.io/instance: postgresql
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: postgresql
-     app.kubernetes.io/version: 16.0.0
-     helm.sh/chart: postgresql-13.2.4
+     app.kubernetes.io/version: 16.1.0
+     helm.sh/chart: postgresql-13.2.25
      app.kubernetes.io/component: primary
    annotations:
      # Use this annotation in addition to the actual publishNotReadyAddresses
      # field below because the annotation will stop being respected soon but the
      # field is broken in some versions of Kubernetes:
      # https://github.com/kubernetes/kubernetes/issues/58662
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  spec:
    type: ClusterIP
    clusterIP: None
    # We want all pods in the StatefulSet to have their addresses published for
    # the sake of the other Postgresql pods even before they're ready, since they
    # have to be able to talk to each other in order to become ready.
    publishNotReadyAddresses: true
    ports:
      - name: tcp-postgresql
        port: 5432
        targetPort: tcp-postgresql
    selector:
      app.kubernetes.io/instance: postgresql
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: primary
```
