### ISSUE TITLE
[bitnami/redmine] redmine pod aborts when using an external database

### ISSUE THREAD

**Issue by johanneskastl** [bitnami/charts#21615]
### Name and Version

bitnami/redmine redmine-25.0.7 (appVersion 5.1.1)

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Setup an external postgreSQL database
2. add the database details to the `values.yaml` (see below)
3. install the chart using `helm install redmine oci://registry-1.docker.io/bitnamicharts/redmine -n redmine -f Redmine/values.yaml`
4. The pod comes up, tries to do the database migrations and aborts. (Error see below)

Using the `diagnosticMode.enabled` setting I can get a pod that does not abort, and can then successfully connect to the postgreSQL database using the host/user/password/databasename from the `values.yaml`.

The only thing I can think of is that the external database is still on PostgreSQL 15, while the chart already uses a PostgreSQL 16 when enabling the builtin postgresql chart dependency.

### Are you using any custom parameters or values?

The relevant parts of the `valies.yaml` are:

```yaml
databaseType: postgresql
mariadb:
  enabled: false
postgresql:
  enabled: false
externalDatabase:                                                                                                                                                                            
  host: "external-database-hostname"
  port: 5432
  user: "redmine"
  database: "redmine"
  existingSecret: "existing-kubernetes-secret-containing-the-password"
  existingSecretPasswordKey: "password"
```

### What is the expected behavior?

Either an error message that is helpful. Or documentation on how to get this working?

### What do you see instead?

```
redmine 10:59:30.45 INFO  ==> 
redmine 10:59:30.46 INFO  ==> Welcome to the Bitnami redmine container
redmine 10:59:30.46 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
redmine 10:59:30.46 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
redmine 10:59:30.46 INFO  ==> 
redmine 10:59:30.47 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
redmine 10:59:30.49 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
redmine 10:59:30.59 WARN  ==> The REDMINE_SMTP_PASSWORD environment variable is empty or not set.
redmine 10:59:30.62 INFO  ==> Ensuring Redmine directories exist
redmine 10:59:30.63 INFO  ==> Trying to connect to the database server
redmine 10:59:30.74 INFO  ==> Configuring Redmine database connections
redmine 10:59:30.93 INFO  ==> Configuring Redmine application with settings provided via environment variables
redmine 10:59:31.02 INFO  ==> Configuring SMTP credentials
redmine 10:59:31.39 INFO  ==> Executing database migrations
```
And after this the pod exists and restarts until it reaches `CrashLoopBackOff`

**Comment by carrodher** [comment]
Are you able to reproduce the issue by using the bundled Postgresql?

**Comment by johanneskastl** [comment]
> Are you able to reproduce the issue by using the bundled Postgresql?

Sorry for the late reply. Due to holiday season I had no chance to debug this and try with a bundled PostgreSQL. But as I was running this with a bundled PostgreSQL in another cluster last year I daresay it should work.

**Comment by aswath-betaflux** [comment]
I'm also facing the same issue with External Postgres. 

My Pod logs :- 
```
redmine 06:45:29.90 INFO  ==> 
redmine 06:45:29.90 INFO  ==> Welcome to the Bitnami redmine container
redmine 06:45:29.90 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
redmine 06:45:29.90 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
redmine 06:45:29.90 INFO  ==> 
redmine 06:45:29.91 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
redmine 06:45:29.92 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
redmine 06:45:29.95 INFO  ==> Ensuring Redmine directories exist
redmine 06:45:29.96 INFO  ==> Trying to connect to the database server
redmine 06:45:29.98 INFO  ==> Configuring Redmine database connections
redmine 06:45:30.04 INFO  ==> Configuring Redmine application with settings provided via environment variables
redmine 06:45:30.06 INFO  ==> Executing database migrations
```

My HELM conf :-
```
## @param databaseType Redmine database type. Allowed values: `mariadb` and `postgresql`
## ref: https://github.com/bitnami/containers/tree/main/bitnami/redmine/#environment-variables
##
databaseType: postgresql
## MariaDB chart configuration
## ref: https://github.com/bitnami/charts/blob/main/bitnami/mariadb/values.yaml
## @param mariadb.enabled Switch to enable or disable the MariaDB helm chart
## @param mariadb.auth.rootPassword MariaDB root password
## @param mariadb.auth.username MariaDB username
## @param mariadb.auth.password MariaDB password
## @param mariadb.auth.existingSecret Name of existing secret to use for MariaDB credentials
## @param mariadb.architecture MariaDB architecture. Allowed values: `standalone` or `replication`
##
mariadb:
  enabled: false
  auth:
    rootPassword: ""
    username: bn_redmine
    password: ""
    existingSecret: ""
  architecture: standalone
## PostgreSQL chart configuration
## ref: https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
## @param postgresql.enabled Switch to enable or disable the PostgreSQL helm chart
## @param postgresql.auth.username Name for a custom user to create
## @param postgresql.auth.password Password for the custom user to create
## @param postgresql.auth.database Name for a custom database to create
## @param postgresql.auth.existingSecret Name of existing secret to use for PostgreSQL credentials
## @param postgresql.architecture PostgreSQL architecture (`standalone` or `replication`)
##
postgresql:
  enabled: false
  auth:
    username: bn_redmine
    password: ""
    database: bitnami_redmine
    existingSecret: ""
  architecture: standalone
## External PostgreSQL configuration
## All of these values are only used when postgresql.enabled is set to false
## @param externalDatabase.host Database host
## @param externalDatabase.port Database port number
## @param externalDatabase.user Non-root username for Redmine
## @param externalDatabase.password Password for the non-root username for Redmine
## @param externalDatabase.database Redmine database name
## @param externalDatabase.existingSecret Name of an existing secret resource containing the database credentials
## @param externalDatabase.existingSecretPasswordKey Name of an existing secret key containing the database credentials
##
externalDatabase:
  host: "xxxxxxxxxxxxxx"
  port: 5432
  user: xxxxx
  database: redmine
  password: "xxxx"
  existingSecret: ""
  existingSecretPasswordKey: ""
```
