### ISSUE TITLE
Redis chart with NodePorts in sentinel mode can't be installed

### ISSUE THREAD

**Issue by lasfromhell** [bitnami/charts#21619]
### Name and Version

bitnami/redis 18.5.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Helm v3.7.2 (MacOS)
2. Install helmchart with the following configuration:
```yaml
redis:
  architecture: "replication"
  replica:
    replicaCount: 3
  sentinel:
    enabled: true
    service:
      type: NodePort
      nodePorts:
        redis: "56379"
        sentinel: "57379"
```

### Are you using any custom parameters or values?

No

### What is the expected behavior?

No errors during installation

### What do you see instead?

```
Error: INSTALLATION FAILED: template: redis/charts/redis/templates/sentinel/node-services.yaml:10:42: executing "redis-test/charts/redis/templates/sentinel/node-services.yaml" at <include "common.names.namespace" .>: error calling include: template: redis-test/charts/redis/charts/common/templates/_names.tpl:63:20: executing "common.names.namespace" at <.Release.Namespace>: can't evaluate field Release in type int
```

### Additional information

The problem is in this part of the `templates/sentinel/node-services.yaml` template:
```yaml
{{- range $i := until (int .Values.replica.replicaCount) }}

{{ $portsmap := (lookup "v1" "ConfigMap" (include "common.names.namespace" .) (printf "%s-%s" ( include "common.names.fullname" $ ) "ports-configmap")).data }}
```

It's trying to evaluate `(include "common.names.namespace" .)`, but `.` is having value equal to `$i` in `range` loop
