### ISSUE TITLE
[bitnami/postgresql] Missing initdb scripts ConfigMap

### ISSUE THREAD

**Issue by mikart143** [bitnami/charts#21627]
### Name and Version

bitnami/postgresql:13.2.24

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Create Helm Chart where Postgresql is as local subchart to the parent.
2. Execute the build and install
3. No ConfigMap was created 

### Are you using any custom parameters or values?
```
image:
  debug: true
auth:
  username: garager
  password: mysecretpassword
  postgresPassword: mysecretpassword
primary:
  persistence:
    enabled: true
  initdb:
    user: postgres
    password: mysecretpassword
    scripts:
      00_test_echo.sh: |
         #!/bin/sh
         echo "Test script execution. START!"
      01_auth_database_setup.sql: |
         CREATE DATABASE "auth" WITH OWNER garager;
      02_scheduler_database_setup.sql: |
         CREATE DATABASE "scheduler" WITH OWNER garager;
      03_test_echo.sh: |
         #!/bin/sh
         echo "Test script execution."
```

### What is the expected behavior?

InitDB scripts would create two databases: auth and scheduler

### What do you see instead?

Instead of information of executing the file I can see: 

> postgresql 21:31:51.41 INFO  ==> 
postgresql 21:31:51.41 INFO  ==> Welcome to the Bitnami postgresql container
postgresql 21:31:51.41 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 21:31:51.41 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql 21:31:51.41 INFO  ==> 
postgresql 21:31:51.42 INFO  ==> ** Starting PostgreSQL setup **
postgresql 21:31:51.43 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 21:31:51.43 INFO  ==> Loading custom pre-init scripts...
postgresql 21:31:51.44 INFO  ==> Initializing PostgreSQL database...
postgresql 21:31:51.44 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 21:31:51.44 INFO  ==> Generating local authentication configuration
postgresql 21:31:51.45 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 21:31:51.46 INFO  ==> Configuring replication parameters
postgresql 21:31:51.48 INFO  ==> Configuring fsync
postgresql 21:31:51.48 INFO  ==> Configuring synchronous_replication
postgresql 21:31:51.50 INFO  ==> Loading custom scripts...
postgresql 21:31:51.50 INFO  ==> Enabling remote connections
postgresql 21:31:51.51 INFO  ==> ** PostgreSQL setup finished! **
postgresql 21:31:51.52 INFO  ==> ** Starting PostgreSQL **
2023-12-18 21:31:51.530 GMT [1] LOG:  pgaudit extension initialized
2023-12-18 21:31:51.535 GMT [1] LOG:  starting PostgreSQL 16.1 on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-12-18 21:31:51.535 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-12-18 21:31:51.535 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2023-12-18 21:31:51.536 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-12-18 21:31:51.538 GMT [91] LOG:  database system was shut down at 2023-12-18 21:25:35 GMT
2023-12-18 21:31:51.540 GMT [1] LOG:  database system is ready to accept connections

### Additional information

Result of helm template command:

```
---
# Source: helm-charts/charts/database/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.1.0
    helm.sh/chart: postgresql-13.2.24
type: Opaque
data:
  postgres-password: "bWtkQWI2WXU2eA=="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
---
# Source: helm-charts/charts/database/charts/postgresql/templates/primary/svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-postgresql-hl
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.1.0
    helm.sh/chart: postgresql-13.2.24
    app.kubernetes.io/component: primary
  annotations:
    # Use this annotation in addition to the actual publishNotReadyAddresses
    # field below because the annotation will stop being respected soon but the
    # field is broken in some versions of Kubernetes:
    # https://github.com/kubernetes/kubernetes/issues/58662
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  # We want all pods in the StatefulSet to have their addresses published for
  # the sake of the other Postgresql pods even before they're ready, since they
  # have to be able to talk to each other in order to become ready.
  publishNotReadyAddresses: true
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: primary
---
# Source: helm-charts/charts/database/charts/postgresql/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.1.0
    helm.sh/chart: postgresql-13.2.24
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
      nodePort: null
  selector:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: primary
---
# Source: helm-charts/charts/database/charts/postgresql/templates/primary/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.1.0
    helm.sh/chart: postgresql-13.2.24
    app.kubernetes.io/component: primary
spec:
  replicas: 1
  serviceName: release-name-postgresql-hl
  updateStrategy:
    rollingUpdate: {}
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: primary
  template:
    metadata:
      name: release-name-postgresql
      labels:
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/version: 16.1.0
        helm.sh/chart: postgresql-13.2.24
        app.kubernetes.io/component: primary
    spec:
      serviceAccountName: default
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: release-name
                    app.kubernetes.io/name: postgresql
                    app.kubernetes.io/component: primary
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
      hostNetwork: false
      hostIPC: false
      containers:
        - name: postgresql
          image: docker.io/bitnami/postgresql:16.1.0-debian-11-r15
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: POSTGRESQL_PORT_NUMBER
              value: "5432"
            - name: POSTGRESQL_VOLUME_DIR
              value: "/bitnami/postgresql"
            - name: PGDATA
              value: "/bitnami/postgresql/data"
            # Authentication
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-name-postgresql
                  key: postgres-password
            # Replication
            # Initdb
            # Standby
            # LDAP
            - name: POSTGRESQL_ENABLE_LDAP
              value: "no"
            # TLS
            - name: POSTGRESQL_ENABLE_TLS
              value: "no"
            # Audit
            - name: POSTGRESQL_LOG_HOSTNAME
              value: "false"
            - name: POSTGRESQL_LOG_CONNECTIONS
              value: "false"
            - name: POSTGRESQL_LOG_DISCONNECTIONS
              value: "false"
            - name: POSTGRESQL_PGAUDIT_LOG_CATALOG
              value: "off"
            # Others
            - name: POSTGRESQL_CLIENT_MIN_MESSAGES
              value: "error"
            - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
              value: "pgaudit"
          ports:
            - name: tcp-postgresql
              containerPort: 5432
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - |
                  exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
                  [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
          resources:
            limits: {}
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: data
              mountPath: /bitnami/postgresql
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
```
