### ISSUE TITLE
[bitnami/mongodb] resources did not find expected key

### ISSUE THREAD

**Issue by alex1989hu** [bitnami/charts#2163]
**Which chart**:
mongodb/7.10.5

**Describe the bug**
Error: YAML parse error on mongodb/templates/deployment-standalone.yaml: error converting YAML to JSON: yaml: line 81: did not find expected key

If you only put either `limits`, or `requests` you will not see the error message. Only the invalid generated content:
```yaml
          resources:
              limits:
              cpu: 900m
              memory: 900Mi
```

**Example values.yaml**:
```yaml
resources:
  limits:
    cpu: 900m
    memory: 900Mi
  requests:
    cpu: 800m
    memory: 800Mi
```

**To Reproduce**
1. Create **values.yml**, see above
3. Execute `helm template mongodb --namespace mongodb -f values.yaml mongodb/`

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Previous fix did not fix it, see there: #2137
