### ISSUE TITLE
[bitnami/wordpress] adjust container resource issue

### ISSUE THREAD

**Issue by xyfleet** [bitnami/charts#21636]
### Name and Version

bitnami/wordpress 18.1.14

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1: install by bitnami/wordpress helm chart
2: adjust the resource of container

### Are you using any custom parameters or values?

```yaml
resources:
  limits:
    memory: 6Gi
    cpu: 3000m
  requests:
    memory: 4Gi
    cpu: 2000m

```

### What is the expected behavior?

I adjusted the resource from original 
```yaml
resources:
  limits: {}
  requests:
    memory: 512Mi
    cpu: 300m
```

to 

```yaml
resources:
  limits:
    memory: 6Gi
    cpu: 3000m
  requests:
    memory: 4Gi
    cpu: 2000m

```

### What do you see instead?

I think it works. But from the query monitor plugin, you can see it still shows the Peak memory if 512M. 
![Screenshot2023_12_18_213830](https://github.com/bitnami/charts/assets/113627389/e707da50-3d03-4a92-81e6-1242207c4a4b)

Why is it showing only 512M? I think I have at least 4G memory available.
