### ISSUE TITLE
[bitnami/redis] Redis Sentinel on OCP fails to connect with Network Policy enabled

### ISSUE THREAD

**Issue by hkailantzis** [bitnami/charts#21657]
### Name and Version

bitnami/redis 18.4.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Deployed Redis Helm chart 18.4.0 to OCP cluster running Kubernetes 1.24.16, with mode Sentinel, Architecture: Replication, and replicas 3.  Network policy Enabled and allowExternal: true

### Are you using any custom parameters or values?

The part of interest is Network Policy related:
```yaml
networkPolicy:
    ## @param networkPolicy.enabled Enable creation of NetworkPolicy resources
    ##
    enabled: true
    ## @param networkPolicy.allowExternal Don't require client label for connections
    ## When set to false, only pods with the correct client label will have network access to the ports
    ## Redis&reg; is listening on. When true, Redis&reg; will accept connections from any source
    ## (with the correct destination port).
    ##
    allowExternal: true
   ```

### What is the expected behavior?

all redis pods should be up and running (3/3). Replicas set is 3.

### What do you see instead?

redis pods keep crashlooping.

### Additional information

OCP DNS forwarding seems to be running on port 5353.
With Network policy enabled, the Helm chart assumes this running on 53, which was not true in my case, thus blocking pod communication on DNS level...
Adding the ExtraEgress Block fixed the issue for me. Hope it helps others also. 
```yaml
extraEgress:
  - ports:
    - port: 5353
      protocol: UDP
```
It could be, if legit, to add it also in the Helm chart maybe?
That's the only resource I could find on this: https://docs.openshift.com/container-platform/4.14/networking/dns-operator.html
