### ISSUE TITLE
[bitnami/keycloak] Getting a redirect loop on the admin panel url

### ISSUE THREAD

**Issue by MurzNN** [bitnami/charts#21661]
### Name and Version

bitnami/keycloak 17.3.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy a bitnami/keycloak helm chart with enabled Ingress using these values:
```yaml
ingress:
  enabled: true
  hostname: keycloak.mydomain.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  tls: true
```

2. Open the web UI URL: https://keycloak.mydomain.com/ - it will open correctly.
3. Click on the "Administration Console" link - it will lead from the https to the http URL (`http://keycloak.mydomain.com/admin/master/console/`) 
4. Get the redirect loop error to http and back to https in the browser.
5. Try to open it manually with https by url `https://keycloak.mydomain.com/admin/master/console/`
See the infinite spinner in the webpage "Loading the Admin UI" and errors in the Console:
```
Content-Security-Policy: The page’s settings blocked the loading of a resource at http://keycloak.mydomain.com/realms/master/protocol/openid-connect/3p-cookies/step1.html (“frame-src”).
```

### Are you using any custom parameters or values?

```yaml
ingress:
  enabled: true
  hostname: keycloak.mydomain.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  tls: true
```

### What is the expected behavior?

All should work well by default.

### What do you see instead?

A redirect loop or an Content-Security-Policy error.

**Comment by MurzNN** [comment]
I already tried to workaround this issue via these values:
```yaml
extraEnvVars:
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_EXTRA_ARGS
      value: "-Dkeycloak.frontendUrl=https://keycloak.mydomain.com/"
```
But this doesn't help.

**Comment by Guite** [comment]
@MurzNN did you find any workaround?

**Comment by MurzNN** [comment]
My workaround is to run it in production mode and enable https explicitly via
```yaml
production: true
extraEnvVars:
  - name: PROXY_ADDRESS_FORWARDING
    value: 'true'
  - name: KEYCLOAK_ENABLE_HTTPS
    value: 'true'
```
But it's better to make the chart works well with non-production mode too.

**Comment by Guite** [comment]
Thanks, this brought me on the right track. Due to [this change](https://www.keycloak.org/docs/latest/upgrading/index.html#passthrough-proxy-mode-changes) I had to define the `proxy` configuration setting.

**Comment by fevisera** [comment]
Hi @MurzNN,

I attempted to replicate the error you encountered, but was unsuccessful. Could you please provide the complete set of parameters you are using?

Thank you.

**Comment by danielloader** [comment]
Can confirm just trying to deploy chart with tls via the ingress yields the same issue as the original issue post.

**Comment by fevisera** [comment]
Are you using the latest [chart version](https://github.com/bitnami/charts/blob/main/bitnami/keycloak/Chart.yaml#L36C10-L36C16)? 

I ran the current version (`18.3.4`) locally and the "Administration Console" links to a "https" link and no error is found in the logs:
```
$ kubectl logs keycloak-0 | grep "Content-Security-Policy"
$ 
```

**Comment by Vinss26** [comment]
Hi @fevisera 

I have the same issue.  I re-tested with your last chart version `18.3.4`
And the issue still present.

My values to reproduce : 
```yaml
auth:
  adminPassword: password
ingress:
  enabled: true
  hostname: xyz-keycloak.local.xyz.internal
  tls: true
  selfSigned: true
tls:
  enabled: true
  autoGenerated: true

logging:
  level: INFO
postgresql:
  primary:
    persistence:
      enabled: false
```

1. after deploy, go to https://xyz-keycloak.local.xyz.internal/
2. (Accept certificate exception)
3. Click on `Administration Console` link
4. ... in Network console tab, you can found an infinite redirect loop between http and https

The workaround proposed by https://github.com/bitnami/charts/issues/21661#issuecomment-1875077358 works fine.
Only `proxy: reencrypt` is necessary : 
```yaml
auth:
  adminPassword: password
ingress:
  enabled: true
  hostname: xyz-keycloak.local.xyz.internal
  tls: true
  selfSigned: true
tls:
  enabled: true
  autoGenerated: true

logging:
  level: INFO
postgresql:
  primary:
    persistence:
      enabled: false

proxy: reencrypt
```

**Comment by fevisera** [comment]
Hi @Vinss26,

Sorry, but I'm still unable to reproduce the error. Here's the configuration I'm using:
```
auth:
  adminPassword: password
ingress:
  enabled: true
  hostname: keycloak.local
  tls: true
  selfSigned: true
tls:
  enabled: true
  autoGenerated: true

logging:
  level: INFO
postgresql:
  primary:
    persistence:
      enabled: false
```
When accessing the hostname, I notice the "https" link for the "Administration Console" in the lower-left corner:
![image](https://github.com/bitnami/charts/assets/43246350/3bc6e2f6-ea1e-454d-90b1-c12e1e715fa2)

Which K8s cluster are you using? Does the issue persist if you execute the following:
```
export HTTP_SERVICE_PORT=$(kubectl get --namespace keycloak -o jsonpath="{.spec.ports[?(@.name=='https')].port}" services keycloak)
kubectl port-forward --namespace keycloak svc/keycloak ${HTTP_SERVICE_PORT}:${HTTP_SERVICE_PORT}
```
And then access through https://localhost?

Please, let me know if there is anything I might be overlooking.

Thank you.
