### ISSUE TITLE
[bitnami/postgresql]: Impossible to add third party extensions with non-root container

### ISSUE THREAD

**Issue by logicbomb421** [bitnami/charts#2168]
**Which chart**:
bitnami/postgresql

**Describe the bug**
I am attempting to install the PostGIS extensions, which require a few outside packages to be installed (`postgresql-contrib`, `postgresql-9.6-postgis-scripts`), however I cannot `apt install` them as the command required root access, which I cannot seem to achieve in this image.

Here is my init script map:
```yaml
  initdbScripts:
    extensions.sh: |
      #! /usr/bin/env bash
      sudo apt update -y
      sudo apt install -y postgres-contrib
      sudo apt install -y postgresql-9.6-postgis-scripts
```

I have attempted to disable all the `securityContext` settings, as well as setting their `runAsUser` values to 0, to no avail. I also attempted to set the `chmod` feature on the `shmVolume`, which did not appear to work either:

```yaml
  volumePermissions:
    enabled: true
  shmVolume:
    chmod:
      enabled: true
```

**To Reproduce**
Install bitnami/postgresql with an initdbScript that needs root access.

**Expected behavior**
There should be a way to either re-enable root access to allow these operations to proceed, or there should be a specific feature of this chart that allows one to install any extension necessary in whatever way is deemed most safe.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

---

It feels as if I'm missing something here, as I doubt I'm the first one to need to install third party postgresql extensions. Any help is greatly appreciated!
