### ISSUE TITLE
[bitnami/mongodb] Unable to carry out safe backups with current CronJob template

### ISSUE THREAD

**Issue by MaciekLeks** [bitnami/charts#21736]
### Name and Version

bitnami/mongodb 14.3.2

### What architecture are you using?

None

### What steps will reproduce the bug?

1. To ensure securityContext works in the cj pod, set `backup.enabled: true` and `backup.cronjob.containerSecurityContext: true` (see https://github.com/bitnami/charts/blob/19880ab4add49512a75059ded4ed1f82d5a1d91b/bitnami/mongodb/templates/backup/cronjob.yaml#L149).
2. Use the default settings from the `values.yml`: 
```yaml
    containerSecurityContext:
      runAsUser: 1001
      runAsGroup: 0
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
```
3. Mount your backup PVC, for example.
```yaml
volumeMounts: 
  - mountPath: /backup/mongodb
    name: datadir
```
4. Then install the helm chart.

### Are you using any custom parameters or values?

As shown above.

### What is the expected behavior?

The CronJob's POD should run without any permission issues.

### What do you see instead?

Permission errors occurred in the mounted volume, and no backup was performed.

### Additional information

While reviewing the CronJob template, it appears that there is no option to add a securityContext at the pod level. It is necessary to include at least `fsGroup: 1001` to ensure everything functions without permission failures.
