### ISSUE TITLE
[bitnami/keycloak] keycloak-config-cli: Allow for multiple extraEnvVarsSecret

### ISSUE THREAD

**Issue by antikalk** [bitnami/charts#21742]
### Name and Version

bitnami/keycloak 17.3.6

### What is the problem this feature will solve?

For keycloak-config-cli at the moment it is only possible to mount one secret as extraEnvVarsSecret. This means that all the additional environment variables you want to mount from a secret have to be in this secret. It would be nice to have the possibility to source the environement variables from multiple secrets. This might also be a nice to have for keycloak itself.

### What is the feature you are proposing to solve the problem?

Add support for `extraEnvVarsSecrets`, allowing you to provide additional multiple secrets: 
```yaml
extraEnvVarsSecrets: 
    - secretRef:
        name: "foo"
    - secretRef:
        name: "bar"
```
