### ISSUE TITLE
Helm uninstall is not destroying rabbitmq cluster CRD mentioned in extraDeploy

### ISSUE THREAD

**Issue by Sadhvik-Modak** [bitnami/charts#21754]
### Name and Version

bitnami/rabbitmq-cluster-operator

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. export mq_namespace=mq-prod
2. helm repo add bitnami https://charts.bitnami.com/bitnami
3. helm install yeedu-rabbitmq3 bitnami/rabbitmq-cluster-operator -n $mq_namespace --create-namespace  -f values.yaml
4. kubectl get secret yeedu-rabbitmq3-default-user -o jsonpath='{.data.username}'  -n $mq_namespace | base64 --decode
5. kubectl get secret yeedu-rabbitmq3-default-user -o jsonpath='{.data.password}'  -n $mq_namespace | base64 --decode
6. helm uninstall yeedu-rabbitmq3 -n $mq_namespace

Values.yaml is provided below.

```yaml
global:
  storageClass:	yeedu-storage-class

clusterOperator:
  requests:
    cpu: 900m
    memory: 2000Mi
  limits:
    cpu: 1000m
    memory: 2048Mi

msgTopologyOperator:
  requests:
    cpu: 900m
    memory: 2000Mi
  limits:
    cpu: 1000m
    memory: 2048Mi


extraDeploy:
  - apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    metadata:
      name: yeedu-rabbitmq3
    spec:
      terminationGracePeriodSeconds: 60
      persistence:
        storageClassName: yeedu-storage-class
        storage: 20Gi
      replicas: 3
      resources:
        requests:
          cpu: 900m
          memory: 2000Mi
        limits:
          cpu: 1000m
          memory: 2048Mi
      rabbitmq:
        additionalConfig: |
          log.console.level = info
          channel_max = 1700
          # default_user_tags.administrator = true
          cluster_partition_handling = pause_minority
          vm_memory_high_watermark_paging_ratio = 0.99
          disk_free_limit.relative = 1.0
          collect_statistics_interval = 10000
          default_user = guest
          default_pass = guest
          loopback_users = none
      service:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
```

### Are you using any custom parameters or values?

Below is the values.yaml I am passing

```yaml
global:
  storageClass:	yeedu-storage-class

clusterOperator:
  requests:
    cpu: 900m
    memory: 2000Mi
  limits:
    cpu: 1000m
    memory: 2048Mi

msgTopologyOperator:
  requests:
    cpu: 900m
    memory: 2000Mi
  limits:
    cpu: 1000m
    memory: 2048Mi


extraDeploy:
  - apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    metadata:
      name: yeedu-rabbitmq3
    spec:
      terminationGracePeriodSeconds: 60
      persistence:
        storageClassName: yeedu-storage-class
        storage: 20Gi
      replicas: 3
      resources:
        requests:
          cpu: 900m
          memory: 2000Mi
        limits:
          cpu: 1000m
          memory: 2048Mi
      rabbitmq:
        additionalConfig: |
          log.console.level = info
          channel_max = 1700
          # default_user_tags.administrator = true
          cluster_partition_handling = pause_minority
          vm_memory_high_watermark_paging_ratio = 0.99
          disk_free_limit.relative = 1.0
          collect_statistics_interval = 10000
          default_user = guest
          default_pass = guest
          loopback_users = none
      service:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
```

### What is the expected behavior?

The RabbitmQ CRD should get deleted on `helm uninstall`

### What do you see instead?

When I run helm uninstall, it is not destroying the rabbitmq CRD (Statefuleset, pod and loadbalancer)
```bash
sc2302@sadhviks-notebook:~$ kgp -n yeedu
NAME                       READY   STATUS    RESTARTS      AGE
rabbitmq3-server-0   1/1     Running   1 (23h ago)   23h
rabbitmq3-server-1   1/1     Running   0             23h
rabbitmq3-server-2   1/1     Running   0             23h
```

### Additional information

-NA-

**Comment by jotamartos** [comment]
Hi @Sadhvik-Modak,

Thank you for using Bitnami. I just verified that a simple pod is properly destroyed when uninstalling the chart

```
extraDeploy:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:latest
        # Just spin & wait forever
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
```

```
$ helm install rabbitmq bitnami/rabbitmq -f values.yaml
...
$ kubectl get all 
NAME             READY   STATUS    RESTARTS   AGE
pod/rabbitmq-0   1/1     Running   0          2m21s
pod/ubuntu       1/1     Running   0          2m21s

NAME                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                 AGE
service/kubernetes          ClusterIP   10.96.0.1        <none>        443/TCP                                 69d
service/rabbitmq            ClusterIP   10.102.248.193   <none>        5672/TCP,4369/TCP,25672/TCP,15672/TCP   2m21s
service/rabbitmq-headless   ClusterIP   None             <none>        4369/TCP,5672/TCP,25672/TCP,15672/TCP   2m21s

NAME                        READY   AGE
statefulset.apps/rabbitmq   1/1     2m21s

$ helm uninstall rabbitmq

$ kubectl get all 
NAME             READY   STATUS        RESTARTS   AGE
pod/rabbitmq-0   1/1     Terminating   0          2m37s
pod/ubuntu       1/1     Terminating   0          2m37s

NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   69d
```

This issue should be related to the object you are deploying. I suggest you check with the RabbitMQ team to get more information about why the object is not destroyed when you uninstall the chart. 

Thanks
