### ISSUE TITLE
postgresql chart + tls enabled seems to break `cronjob.yaml`

### ISSUE THREAD

**Issue by tbscode** [bitnami/charts#21750]
### Name and Version

bitnami/postgresql 13.2.25

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Setting in values.yaml

```yaml
global:
  postgresql:
    auth:
      username: "testUser"
      password: "testPass"
      database: "testDB"
clusterDomain: "my-domain.server.com"
tls:
  enabled: true
  autoGenerated: true
backup:
  enabled: true
  cronjob:
    schedule: '0 */6 * * *'
    storage:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 50Gi
      mountPath: "/backups"
```

Causes a syntax error in `cronjob.yaml`:
If I use `helm template ...` I can see the generated broken line:

```yaml
              - name:  PGSSLROOTCERTvalue: /tmp/certs/ca.crt
```

I've tried multiple configurations I believe this is a bug in the chart.

The issue should be here in `charts/bitnami/postgresql/templates/backup/cronjob.yaml`:

```yaml
              {{- if .Values.tls.enabled }}
              - name:  PGSSLROOTCERT
                {{- if .Values.tls.autoGenerated -}}
                value: /tmp/certs/ca.crt
                {{- else }}
                value: {{- printf "/tmp/certs/%s" .Values.tls.certCAFilename -}}
                {{- end }}
              {{- end }}
```

I believe updating `value: {{ printf "/tmp/certs/%s" .Values.tls.certCAFilename | quote }}` could resolve the issue of a missing newline after `PGSSLROOTCERT`

### Are you using any custom parameters or values?

See steps to reproduce

### What is the expected behavior?

No syntax error with `tls.enabled: true`

### What do you see instead?

I saw a yaml syntax error on helm install so I investigated it using `helm template --debug`

### Additional information

Can Imagine making a pull for this, let me know.

**Comment by tbscode** [comment]
Bash online reproduce ( or exposing my miss configuration ):

```yaml
global:
  postgresql:
    auth:
      username: "dbUser"
      password: "dbPass"
      database: "Database"
tls:
  enabled: true
  autoGenerated: true
backup:
  enabled: true
  cronjob:
    schedule: '0 */6 * * *'
    storage:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 50Gi
EOM
helm install my-release oci://registry-1.docker.io/bitnamicharts/postgresql \
    -n test \
    -f- <<< "$VALUES"
```

Gives me:

```bash
Error: INSTALLATION FAILED: YAML parse error on postgresql/templates/backup/cronjob.yaml: error converting YAML to JSON: yaml: line 53: mapping values are not allowed in this context
```
