### ISSUE TITLE
[bitnami/elasticsearch] Include fluentd as subchart

### ISSUE THREAD

**Issue by irizzant** [bitnami/charts#2176]
**Which chart**:
bitnami/elasticsearch elasticsearch-11.0.13

**Is your feature request related to a problem? Please describe.**
Fluentd is the "de facto" standard for log forwarding to Elasticsearch, but it's not included as subchart as Kibana is instead.

**Describe the solution you'd like**
I'd like to have bitnami/fluentd as subchart.

**Describe alternatives you've considered**
The only alternative is manual installation of Fluentd chart.

**Additional context**

**Comment by juan131** [comment]
Hi @irizzant 

> Fluentd is the "de facto" standard for log forwarding to Elasticsearch

I agree that Fluentd is one of the most common logging solutions and it's frequently used along with Elasticsearch & Kibana to manage logging on Kubernetes. However, a very popular stack is also ELK, which includes Logstash instead of Fluetnd.

I would suggest instead creating EFK or ELK charts which use ElasticSearch, Kibana and Fluetnd/Logstash as subcharts to manage these stacks as a whole.

What do you think about that?

**Comment by irizzant** [comment]
Hi @juan131 
as long as both EFK and ELK are provided as subcharts of the existing ElasticSearch I don't see any problem.

**Comment by juan131** [comment]
@javsalgar @carrodher what do you think about this suggestion?

**Comment by irizzant** [comment]
@juan131 If possible, it would be great if you could change the `Service` port name on the elasticsearch chart to respect [Istio standards](https://istio.io/docs/ops/deployment/requirements/).
I noticed that:
* https://github.com/bitnami/charts/blob/cefffdb35eb9c41959c2bb0497460c856e08a6d9/bitnami/elasticsearch/templates/discovery-svc.yaml#L13
* https://github.com/bitnami/charts/blob/cefffdb35eb9c41959c2bb0497460c856e08a6d9/bitnami/elasticsearch/templates/ingest-svc.yaml#L15
* https://github.com/bitnami/charts/blob/cefffdb35eb9c41959c2bb0497460c856e08a6d9/bitnami/elasticsearch/templates/master-svc.yaml#L14
* https://github.com/bitnami/charts/blob/cefffdb35eb9c41959c2bb0497460c856e08a6d9/bitnami/elasticsearch/templates/metrics-svc.yaml#L12

do not respect Istio standards and there is no way in the chart to change the port names
Thanks

**Comment by juan131** [comment]
Hi @irizzant 

Yes, that would be possible. Could you please create a separate issue for that? We should try to discuss about just one topic per issue to avoid confusion. Thanks in advance.

**Comment by irizzant** [comment]
Hi @juan131 ok no problem, see https://github.com/bitnami/charts/issues/2199

**Comment by juan131** [comment]
Thanks @irizzant !! 
Ping @carrodher @javsalgar ! Please review this suggestion to use Fluentd/Logstash as subhcarts

**Comment by carrodher** [comment]
I think is a good idea to have a solution including Elastic, Fluentd/Logstash and Kibana.
About what is the best option, I am not sure, we can add different subcharts disabled by default to ES (the same approach we are currently using for Kibana) or create a new EFLK chart with ES as main application and then Fluentd, Logstash and Kibana as subcharts, on this way we maintain the current ES chart as it is (ES+Kibana) and then a different solution with the logging apps.

**Option 1: Everything in the current ES chart**
```yaml
dependencies:
  - name: kibana
    version: 5.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: global.kibanaEnabled
  - name: logstash
    version: Y.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: global.logstashEnabled
  - name: fluentd
    version: Y.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: global.fluentdEnabled
```
**Option 2: ELFK with ES as main chart**
```yaml
dependencies:
  - name: kibana
    version: 5.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: logstash
    version: Y.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: global.logstashEnabled
  - name: fluentd
    version: Y.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: global.fluentdEnabled
```
In this case, Kibana is always enabled by default (no condition) and then users can select Fluentd or Logstash to create EFK or ELK respectively.
