### ISSUE TITLE
auth.existingSecret does not work for PostgreSQL chart

### ISSUE THREAD

**Issue by skillpoint-dev** [bitnami/charts#21763]
### Name and Version

bitnami/postgresql 13.2.25

### What architecture are you using?

amd64

### What steps will reproduce the bug?

k8s v1.28.3

```bash
kubectl create ns postgres-test
kubectl apply -f secret.yaml
helm upgrade -i postgres-test -n postgres-test oci://registry-1.docker.io/bitnamicharts/postgresql -f values.yaml
```

secret.yaml

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: postgres-test
type: Opaque
data:
  postgres-password: ANY-GENERATED-BASE64-TEST-VALUE
```

### Are you using any custom parameters or values?

values.yaml
```yaml
auth:
  existingSecret: postgresql-secret
primary:
  persistence:
    enabled: false
```

### What is the expected behavior?

Passwords of the secret should be used.

### What do you see instead?

The right value is shown in den ENV "POSTGRES_PASSWORD" of the pod but I can't login with it.

```bash
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  password authentication failed for user "postgres"
```

If I do the same thing without setting the secret in the values and use the generated value in the pod for login it works...
