### ISSUE TITLE
Kafka controller: cannot increase persistence volume size

### ISSUE THREAD

**Issue by cinimins** [bitnami/charts#21787]
### Name and Version

bitnami/kafka 26.4.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When increasing the value `controller.persistence.size` and triggering an `helm upgrade` I get the following error:

> Error: UPGRADE FAILED: cannot patch "kafka-controller" with kind StatefulSet: StatefulSet.apps "kafka-controller" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden

This used to work before when I used brokers and zookeeper, and doesn't seem to work with controllers anymore.

### Are you using any custom parameters or values?

```yaml
fullnameOverride: "kafka"

controller:
  pdb:
    create: true
    maxUnavailable: 1
  replicaCount: 3
  persistence:
    size: 2Gi

sasl:
  enabledMechanisms: PLAIN,SCRAM-SHA-512
  interBrokerMechanism: SCRAM-SHA-512
  controllerMechanism: PLAIN
  client:
    users:
      - "admin"
    passwords:
      - "admin"

extraConfig: |-
  authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer
  super.users=User:controller_user;User:admin

externalAccess:
  enabled: true

kraft:
  enabled: true
```

### What do you see instead?

> Error: UPGRADE FAILED: cannot patch "kafka-controller" with kind StatefulSet: StatefulSet.apps "kafka-controller" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
