### ISSUE TITLE
Allow CA to come from different secret

### ISSUE THREAD

**Issue by FireDrunk** [bitnami/charts#21796]
### Name and Version

bitnami/postgresql 13.2.26

### What is the problem this feature will solve?

Better integration with `cert-manager`.

### What is the feature you are proposing to solve the problem?

Allow the file `certCAFilename` to come from a different `Secret`.
Currently it's pulled from the `certificatesSecret` value, but when using `cert-manager` this CA is not the correct one if you have an internal `Issuer` that provides the certificate.
That CA is stored in a different `Secret`.

Perhaps something like adding a value: `caSecret` would be nice.

### What alternatives have you considered?

The alternative is to manually construct a secret containing the correct files, which negates any automation from cert-manager.

### Example Cert-Manager setup ###

```yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: database-issuer
spec:
  selfSigned: {}
```

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: database-ca
spec:
  isCA: true
  commonName: database-ca
  secretName: database-ca-tls

  privateKey:
    algorithm: ECDSA
    size: 256
  
  issuerRef:
    name: database-issuer
    kind: Issuer
```

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: database-certificate
spec:
  # Certificate Info
  commonName: postgres
  isCA: false
  
  # Renewal
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  
  # Secret
  secretName: database-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  
  usages:
    - server auth
    - client auth
  
  dnsNames:
  - database
  - database.default.svc
  - database.default.svc.cluster.local
  
  issuerRef:
    name: database-issuer
    kind: Issuer
```

This will create 2 secrets `database-tls` and `database-ca-tls` which contain the TLS Key + Cert and CA Cert respectively.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by FireDrunk** [comment]
After a bit of digging around, I found out that my cert-manager setup was all wrong, which caused the Certificate to not be properly generated with the parent as it's CA, which caused the CA being incorrect in the same secret.

After fixing the cert-manager setup, the CA is correct in the secret, so this is no longer required.

The correct cert-manager setup for reference:
```yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: database-ca-root-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: database-ca
spec:
  isCA: true
  commonName: database-ca
  secretName: database-ca-tls
  
  subject:
    organizations:
    - myOrg

  privateKey:
    algorithm: ECDSA
    size: 256
  
  issuerRef:
    name: database-ca-root-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: database-ca-issuer
spec:
  ca:
    secretName: database-ca-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: database-certificate
spec:
  # Certificate Info
  commonName: postgres
  isCA: true
  subject:
    organizations:
    - myOrg
  
  # Renewal
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  
  # Secret
  secretName: database-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  
  usages:
    - server auth
    - client auth
  
  dnsNames:
  - database
  - database.default.svc
  - database.default.svc.cluster.local
  
  issuerRef:
    name: database-ca-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: database-issuer
spec:
  ca:
    secretName: database-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: database-client-certificate
spec:
  # Certificate Info
  commonName: database-client
  isCA: false
  subject:
    organizations:
    - myOrg

  # Renewal
  duration: 2160h # 90d
  renewBefore: 360h # 15d

  # Secret
  secretName: database-client-tls
  privateKey:
    algorithm: ECDSA
    size: 256

  usages:
    - server auth
    - client auth

  dnsNames:
  - database-client
  
  issuerRef:
    name: database-issuer
    kind: Issuer
```
