### ISSUE TITLE
[bitnami/external-dns] Facing issue when using EKS pod identity for external-dns

### ISSUE THREAD

**Issue by suchsatdevops** [bitnami/charts#21847]
### Name and Version

bitnami/external-dns 6.28.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm using Amazon EKS Pod Identity Agent in one of my EKS cluster and created pod identity association to associate my IAM role to external-dns pod. 

Below is the IAM policy attached to my IAM role.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "DNSAccess",
            "Effect": "Allow",
            "Action": "route53:ChangeResourceRecordSets",
            "Resource": [
                "arn:aws:route53:::hostedzone/XXXXXXXXXXX"
            ]
        },
        {
            "Sid": "DNSAccess1",
            "Effect": "Allow",
            "Action": [
                "route53:Get*",
                "route53:List*"
            ],
            "Resource": "*"
        },
}
```

Below is my external-dns service-account yaml

```yaml
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: external-dns
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: 0.14.0
    helm.sh/chart: external-dns-6.28.5
    helm.toolkit.fluxcd.io/name: external-dns
    helm.toolkit.fluxcd.io/namespace: kube-system
  name: external-dns
  namespace: kube-system
```

External-dns pod is going to error state and I'm seeing below error in external-dns pod logs.

`level=fatal msg="records retrieval failed: failed to list hosted zones: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"`

Note: We are seeing this issue when eks pod identity association is created for my IAM role and the external-dns serviceaccount. Please help me with the issue. 

### Are you using any custom parameters or values?
```yaml
 values:
    # image repo details
    image:
      registry: docker.io
      repository: bitnami/external-dns
      tag: 0.14.0-debian-11-r1
      pullPolicy: IfNotPresent
      pullSecrets:
      - xxxxxxxxx
    
    provider: aws
    logLevel: debug
    
    aws:
      zoneType: public
    rbac:
      create: true
    interval: 4h
    triggerLoopOnEvent: true
    domainFilters: ["xxxxxxxx"]
    txtOwnerId: <cluster-name>
    policy: sync
    
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 60s
        selector:
          release: monitoringaddon

    podSecurityContext:
      fsGroup: 65534   
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 200Mi
```

### What do you see instead?
```
level=fatal msg="records retrieval failed: failed to list hosted zones: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
```
