### ISSUE TITLE
Postgresql charts: Bad environment variable name for POSTGRES_POSTGRES_PASSWORD

### ISSUE THREAD

**Issue by Kaylleur** [bitnami/charts#21852]
### Name and Version

bitnami\postgresql 13.2.27

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi,

There is an error in the bitnami charts postgresql. When we set the postgres-password values, and templating it with helm the env vars has not the same name as in the docker description.

On the docker hub the env var is named : POSTGRESQL_POSTGRES_PASSWORD  ([link](https://hub.docker.com/r/bitnami/postgresql))

If we run: `docker run --name postgresql -e POSTGRESQL_USERNAME=my_user -e POSTGRESQL_PASSWORD=password123 -e POSTGRESQL_DATABASE=my_database -p 5432:5432 -e POSTGRESQL_POSTGRES_PASSWORD=toto bitnami/postgresql:13.11.0-debian-11-r22`

Then we can connect to it with credentials postgres / toto

If we install the postgresql helm chart with values: 
```yaml
global:
  postgresql:
    auth:
      postgresPassword: "titi"
      username: "tata"
      password: "toto"
```
and then template them:
`helm template -f values.yml --output-dir dist oci://registry-1.docker.io/bitnamicharts/postgresql`

The file generated has the wrong env vars key:
```yaml
  - name: POSTGRES_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-name-postgresql
                  key: postgres-password
```

If we check the template file:
```yaml
            - name: POSTGRES_POSTGRES_PASSWORD_FILE
              value: {{ printf "/opt/bitnami/postgresql/secrets/%s" (include "postgresql.v1.adminPasswordKey" .) }}
            {{- else }}
            - name: POSTGRES_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.v1.secretName" . }}
                  key: {{ include "postgresql.v1.adminPasswordKey" . }}
```
These keys are not the same as the docker hub documentation which mentions:
_Note! When POSTGRESQL_USERNAME is specified, the postgres user is not assigned a password and as a result you cannot login remotely to the PostgreSQL server as the postgres user. If you still want to have access with the user postgres, please set the POSTGRESQL_POSTGRES_PASSWORD environment variable (or the content of the file specified in POSTGRESQL_POSTGRES_PASSWORD_FILE)._

### What is the expected behavior?

The env vars generated by the helm charts should be as same as the container documentation on the docker hub.
The postgres password should be set as the container do.

### What do you see instead?

POSTGRES_POSTGRES_PASSWORD should be POSTGRESQL_POSTGRES_PASSWORD
POSTGRES_POSTGRES_PASSWORD_FILE should be POSTGRESQL_POSTGRES_PASSWORD_FILE
