### ISSUE TITLE
[bitnami/redis] searches for master in a different namespace

### ISSUE THREAD

**Issue by MrKribel** [bitnami/charts#21855]
### Name and Version

bitnami/redis-18.6.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

 helm install redis-sentinel bitnami/redis --values values.yaml --namespace authorization

### Are you using any custom parameters or values?

```
global:
  storageClass: "fast"

auth:
  enabled: false

metrics:
  enabled: true

sentinel:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi
  downAfterMilliseconds: 10000 
  failoverTimeout: 20000
```

### What do you see instead?

```
>>> kubectl get all --namespace authorization

pod/redis-sentinel-node-0                         3/3     Running   0              3m8s
pod/redis-sentinel-node-1                         3/3     Running   0               54s
pod/redis-sentinel-node-2                         3/3     Running   0               17s

statefulset.apps/redis-sentinel-node   3/3     3m9s


>>> kubectl exec -it redis-sentinel-node-0  /bin/bash -n authorization -- redis-cli role

1) "slave"
2) "redis-sentinel-node-2.redis-sentinel-headless.interaction.svc.cluster.local"
3) (integer) 6379
4) "connected"
5) (integer) 4943370033
```
