### ISSUE TITLE
[bitnami/drupal] - Add tlsWwwPrefix mechanism to handle 301 redirects when nginx.ingress.kubernetes.io/from-to-www-redirect i set

### ISSUE THREAD

**Issue by g0blin79** [bitnami/charts#21864]
### Name and Version

bitnami/drupal:17.0.0

### What is the problem this feature will solve?

At this stage does not seem that the bitnami/drupal chart can create an ingress that supports correctly the `nginx.ingress.kubernetes.io/from-to-www-redirect : true` annotations when also `tls: true`

Basically, I want to manage an ingress manifest like this:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: my-example-app
  namespace: my-example-namespace
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          service:
            name: my-example-app
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - example.com
    - www.example.com
    secretName: example.com-tls
[...]
``` 

### What is the feature you are proposing to solve the problem?

A viable solution to this is just implemented in the `bitnami/wordpress` helm chart, here:

- https://github.com/bitnami/charts/blob/main/bitnami/wordpress/values.yaml#L641C1-L644C22 
- https://github.com/bitnami/charts/blob/main/bitnami/wordpress/templates/ingress.yaml#L53C1-L55C19

And the same solution can be used also for the `bitnami/drupal` chart.
