### ISSUE TITLE
[bitnami/apisix] Error ssl protocol in apisix

### ISSUE THREAD

**Issue by 223311** [bitnami/charts#21861]
### Name and Version

bitnami/apisix:2.2.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

i am trying to install the through helm.
```
resource "helm_release" "apisix-deployment" {
  name       = "apisix"
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "apisix"
  namespace  = var.apisix_namespace
  version    = "2.2.7"

  values = [
    templatefile("${path.module}/templates/values.yaml", {
      CLUSTER_NAME = "apisix"
    })
  ]
}
```

### Are you using any custom parameters or values?

values.yaml
```yaml
dashboard:
  service:
    type: ClusterIP
    ingress:
      enabled: true
dataPlane:
  service:
    type: NodePort
    nodePorts:
      http: "32655"
  metrics:
    enabled: true
  autoscaling:
    hpa:
      enabled: true
      minReplicas: "1"
      maxReplicas: "2"
      targetCPU: "80"
      targetMemory: "80"

controlPlane:
  metrics:
    enabled: true
  autoscaling:
    hpa:
      enabled: true
      minReplicas: "1"
      maxReplicas: "1"
      targetCPU: "80"
      targetMemory: "80"
```
### What is the expected behavior?

while deploying it opens the HTTP port, HTTPS port and metric port. When I am trying to port forward for the HTTP port of the data plane pod it is working fine i.e. I am getting the message like {"error_msg":"404 Route Not Found"} . which I am expecting. but when I try to forward the HTTPS port of dataplane it shows `Error: SSL connect error`

![image](https://github.com/bitnami/charts/assets/29684497/c109c875-16a2-41be-a412-8985acabbae2)

FYI:  in the values.yaml I see the `dataplane.tls.enabled` is set to `true` and `dataplane.tls.autoGenerated` is set `true`.
is there anything config is missing?

Here my flow will like from elb(443)(first ssl termination will happened by aws)->dataplane tls(9443)(lb will forward to the dataplane ssl cert)->service->pod 

Thanks for the help.

### What do you see instead?
```
{"error_msg":"404 Route Not Found"}
```
and it should serve the self-signed ssl certificate
