### ISSUE TITLE
[bitnami/redis-cluster]  redis-cluster did not start successfully, but has been stuck in the step of 【Setting Redis config file】.

### ISSUE THREAD

**Issue by xiaoxuanyo** [bitnami/charts#21874]
### Name and Version

bitnami/redis-cluster 7.2.3-debian-11-r2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. A k8s cluster using cilium, with one master node, two worker nodes and is in the ready state
2. `helm install bitnami/redis-cluster`, version is 7.2.3-debian-11-r2
3. Observe whether the redis cluster starts successfully
4. Failed

### Are you using any custom parameters or values?

```yaml
global:
  storageClass: "redis-storage"
  redis:
    password: "XXXXX"

password: "XXXXX"

persistence:
  storageClass: "redis-storage"
  size: 1Gi

 livenessProbe:
    initialDelaySeconds: 300
    periodSeconds: 10

readinessProbe:
    initialDelaySeconds: 300
    periodSeconds: 10
````

### What is the expected behavior?

 redis cluster starts successfully

### What do you see instead?

redis-cluster-X is in the running state, but the redis service of the internal container did not start successfully, but has been stuck in the step of Setting Redis config file.

### Additional information

1. redis-cluster-x status
![image](https://github.com/bitnami/charts/assets/65661595/6bbacc02-0ead-493c-838a-86443458895c)
2. StorageClass status
![image](https://github.com/bitnami/charts/assets/65661595/bc5ab59f-148a-42d6-b50c-c6da463efee5)
3. PVC status
![image](https://github.com/bitnami/charts/assets/65661595/72f63be4-fa85-4907-b319-06db46f0b127)
4. PV status
![image](https://github.com/bitnami/charts/assets/65661595/a4016ddd-8c75-4cd2-a85b-d0eff263f406)
5. pod-x describe
![image](https://github.com/bitnami/charts/assets/65661595/33421b5b-72b9-4d91-b9d5-dc84be395dc6)
6. pod-x logs
![image](https://github.com/bitnami/charts/assets/65661595/43c697a3-f2e8-4682-82d4-c8e5ef0bde30)
7. pod's inside container logs
![image](https://github.com/bitnami/charts/assets/65661595/d573aeab-b150-4b35-884d-eb16411753aa)
