### ISSUE TITLE
[bitnami/mongodb] Custom mongodb.conf crashes arbiter pods

### ISSUE THREAD

**Issue by gorzek** [bitnami/charts#2191]
**Which chart**:
bitnami/mongodb: 7.10.6

**Describe the bug**
I need a custom mongodb.conf to set a larger oplog size. I understand that applying it to an existing deployment must be done manually, but I want the correct values in our deployment files, too. I pasted the default mongodb.conf into the `configmap` section of our values file, while adding `oplogSizeMB: 10240` to the `replication` subsection. This works for primary and secondary pods, but causes arbiter pods to crash without any error messages:

```
> File /opt/bitnami/mongodb/conf/mongodb.conf was mounted in /opt/bitnami/mongodb/conf
> Custom configuration /opt/bitnami/mongodb/conf/mongodb.conf detected!                                                                                                                   
> Deploying MongoDB from scratch...
```

**To Reproduce**
1. Take the stock chart.
2. Create a custom values file like so:
```
replicaSet:
  enabled: true
  replicas:
    secondary: 4
    arbiter: 2
```
3. Deploy the chart.
4. Update the values file and add:
```
configmap:
  # mongod.conf
  # for documentation of all options, see:
  #   http://docs.mongodb.org/manual/reference/configuration-options/

  # where and how to store data.
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false

  # where to write logging data.
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0

  # network interfaces
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    bindIpAll: true
    #bindIp:

  # replica set options
  replication:
    replSetName: rs0
    enableMajorityReadConcern: true
    oplogSizeMB: 10240

  # process management options
  processManagement:
     fork: false
     pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid

  # set parameter options
  setParameter:
     enableLocalhostAuthBypass: false

  # security options
  security:
    authorization: enabled
    keyFile: /opt/bitnami/mongodb/conf/keyfile
```
5. Deploy again. The arbiter pods should get stuck in a crash loop.

**Expected behavior**
I expect the arbiter pods to start up without issue using this new configuration, especially since it is not supposed to change the actual functioning of mongodb without manual setting changes within the containers.

**Version of Helm and Kubernetes**:
Helm 2.14.3, Kubernetes 1.15.9

- Output of `helm version`:

```
 version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Note that we use Tillerless helm via our CD system so I don't have the output handy for the server version, however I know it's 2.14.3.

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-12T13:43:46Z", GoVersion:"go1.13.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.22", GitCommit:"9bae7fcacb520dfee658b26cc1a9643bf787dfc3", GitTreeState:"clean", BuildDate:"2020-02-27T18:43:37Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by Mauraza** [comment]
Hi @gorzek,

Could you try to start the chart with all the values of `mongod.conf`? 
You can modify values.yml and run `helm install my-release -f values.yaml bitnami/mongodb`.

**Comment by gorzek** [comment]
So initially I do start it with all values that the containers have by default. That is, I deploy without any changes to the default config, and then cat out the contents of mongodb.conf from the individual pods. I just checked, and for arbiter, primary, and secondary, it's exactly the same:

```
# mongod.conf
# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# where and how to store data.
storage:
  dbPath: /bitnami/mongodb/data/db
  journal:
    enabled: true
  directoryPerDB: false

# where to write logging data.
systemLog:
  destination: file
  quiet: false
  logAppend: true
  logRotate: reopen
  path: /opt/bitnami/mongodb/logs/mongodb.log
  verbosity: 0

# network interfaces
net:
  port: 27017
  unixDomainSocket:
    enabled: true
    pathPrefix: /opt/bitnami/mongodb/tmp
  ipv6: false
  bindIpAll: true
  #bindIp:

# replica set options
replication:
  replSetName: rs0
  enableMajorityReadConcern: true

# process management options
processManagement:
   fork: false
   pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid

# set parameter options
setParameter:
   enableLocalhostAuthBypass: false

# security options
security:
  authorization: enabled
  keyFile: /opt/bitnami/mongodb/conf/keyfile
```

But adding `oplogSizeMB: 10240` to the `replication` section (via helm values) reliably causes the arbiter pods to crash (while primary and secondary are fine).

**Comment by gorzek** [comment]
As far as I can tell, the above is identical to what's in the default chart values.

**Comment by Mauraza** [comment]
The pod are ephemeral, so it's a good idea to deploy the chart with the values you want because if the pod die, you lose the changes. 

You can follow these steps to deploy the char with changes in the `mongodb.conf`
 
- get the file `values.yaml` https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml
- edit the file with your changes 
for example for mongodb.conf(start in line 402):
```
configmap:
  # where and how to store data.
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
  # where to write logging data.
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0
  # network interfaces
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    bindIpAll: true
   # replica set options
  replication:
    replSetName: rs0
    enableMajorityReadConcern: true
    oplogSizeMB: 10240
  # process management options
  processManagement:
     fork: false
     pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
  # set parameter options
  setParameter:
     enableLocalhostAuthBypass: true
  # security options
  security:
    authorization: disabled
    #keyFile: /opt/bitnami/mongodb/conf/keyfile
```
- save the file with your specification (add to the changes of replicaSet line 163) 
- run : `helm install my-release -f values.yaml bitnami/mongodb`

**Comment by gorzek** [comment]
That is exactly what I have done. I am saying that applying the oplogSizeMG parameter via the helm values causes arbiter pods to crash on startup. Primary and secondary pods start up without an issue.

**Comment by Mauraza** [comment]
Hi @gorzek,

could you copy the command are you used?

**Comment by gorzek** [comment]
Which command are you looking for? Just to be clear.

**Comment by Mauraza** [comment]
Your command for deploy mongodb with helm. I think will be similar to: `helm install your-relase bitnami/mongodb --set replicas.enable=true...`

**Comment by gorzek** [comment]
We use helmfile to render our combination of helm files and values files, which invokes helm internally.

I can provide any of the rendered manifests, if that helps.

**Comment by Mauraza** [comment]
Yes, please give us the rendered manifests and the values you are using.

**Comment by gorzek** [comment]
```
---
# Source: mongodb/templates/poddisruptionbudget-arbiter-rs.yaml

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: mongodb
    chart: mongodb-7.10.6
    heritage: Tiller
    release: dev-inf-acme-mongodb
  name: dev-inf-acme-mongodb-arbiter
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mongodb
      release: dev-inf-acme-mongodb
      component: arbiter
---
# Source: mongodb/templates/poddisruptionbudget-secondary-rs.yaml

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: mongodb
    chart: mongodb-7.10.6
    heritage: Tiller
    release: dev-inf-acme-mongodb
  name: dev-inf-acme-mongodb-secondary
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mongodb
      release: dev-inf-acme-mongodb
      component: secondary

---
# Source: mongodb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: dev-inf-acme-mongodb
  labels:
    app: mongodb
    chart: mongodb-7.10.6
    release: "dev-inf-acme-mongodb"
    heritage: "Tiller"
type: Opaque
data:
  mongodb-root-password:  "xxxxx"
  mongodb-replica-set-key: "xxxxx"

---
# Source: mongodb/templates/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: mongodb
    chart: mongodb-7.10.6
    heritage: Tiller
    release: dev-inf-acme-mongodb
  name: dev-inf-acme-mongodb
data:
  mongodb.conf: |-
    net:
      bindIpAll: true
      ipv6: false
      port: 27017
      unixDomainSocket:
        enabled: true
        pathPrefix: /opt/bitnami/mongodb/tmp
    processManagement:
      fork: false
      pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
    replication:
      enableMajorityReadConcern: true
      oplogSizeMB: 10240
      replSetName: rs0
    security:
      authorization: enabled
      keyFile: /opt/bitnami/mongodb/conf/keyfile
    setParameter:
      enableLocalhostAuthBypass: false
    storage:
      dbPath: /bitnami/mongodb/data/db
      directoryPerDB: false
      journal:
        enabled: true
    systemLog:
      destination: file
      logAppend: true
      logRotate: reopen
      path: /opt/bitnami/mongodb/logs/mongodb.log
      quiet: false
      verbosity: 0

---
# Source: mongodb/templates/serviceaccount.yml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-inf-acme-mongodb
  labels:
    app: mongodb
    chart: mongodb-7.10.6
    release: "dev-inf-acme-mongodb"
    heritage: "Tiller"
secrets:
  - name: dev-inf-acme-mongodb

---
# Source: mongodb/templates/svc-headless-rs.yaml

apiVersion: v1
kind: Service
metadata:
  name: dev-inf-acme-mongodb-headless
  labels:
    app: mongodb
    chart: mongodb-7.10.6
    release: "dev-inf-acme-mongodb"
    heritage: "Tiller"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
  selector:
    app: mongodb
    release: dev-inf-acme-mongodb

---
# Source: mongodb/templates/svc-primary-rs.yaml

apiVersion: v1
kind: Service
metadata:
  name: dev-inf-acme-mongodb
  labels:
    app: mongodb
    chart: mongodb-7.10.6
    release: "dev-inf-acme-mongodb"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  - name: metrics
    port: 9216
    targetPort: metrics
  selector:
    app: mongodb
    release: "dev-inf-acme-mongodb"
    component: primary

---
# Source: mongodb/templates/statefulset-arbiter-rs.yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dev-inf-acme-mongodb-arbiter
  labels:
    app: mongodb
    chart: mongodb-7.10.6
    heritage: Tiller
    release: dev-inf-acme-mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
      release: dev-inf-acme-mongodb
      component: arbiter
  serviceName: dev-inf-acme-mongodb-headless
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongodb
        chart: mongodb-7.10.6
        release: dev-inf-acme-mongodb
        component: arbiter
    spec:
      serviceAccountName: dev-inf-acme-mongodb
      priorityClassName: critical-inf-priority
      securityContext:
        fsGroup: 1001
      containers:
        - name: mongodb-arbiter
          image: docker.io/bitnami/mongodb:4.2.5-debian-10-r35
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          ports:
          - containerPort: 27017
            name: mongodb
          env:
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
          - name: MONGODB_DISABLE_SYSTEM_LOG
            value: "no"
          - name: MONGODB_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MONGODB_REPLICA_SET_MODE
            value: "arbiter"
          - name: MONGODB_PRIMARY_HOST
            value: dev-inf-acme-mongodb
          - name: MONGODB_REPLICA_SET_NAME
            value: "rs0"
          - name: MONGODB_ADVERTISED_HOSTNAME
            value: "$(MONGODB_POD_NAME).dev-inf-acme-mongodb-headless.dev-inf-acme.svc.cluster.local"
          - name: MONGODB_PRIMARY_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dev-inf-acme-mongodb
                key: mongodb-root-password
          - name: MONGODB_REPLICA_SET_KEY
            valueFrom:
              secretKeyRef:
                name: dev-inf-acme-mongodb
                key: mongodb-replica-set-key
          - name: MONGODB_ENABLE_IPV6
            value: "no"
          - name: MONGODB_ENABLE_DIRECTORY_PER_DB
            value: "no"
          livenessProbe:
            tcpSocket:
              port: mongodb
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: mongodb
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - name: config
              mountPath: /opt/bitnami/mongodb/conf/mongodb.conf
              subPath: mongodb.conf
          resources:
            {}

      volumes:
        - name: config
          configMap:
            name: dev-inf-acme-mongodb

---
# Source: mongodb/templates/statefulset-primary-rs.yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dev-inf-acme-mongodb-primary
  labels:
    app: mongodb
    chart: mongodb-7.10.6
    heritage: Tiller
    release: dev-inf-acme-mongodb
spec:
  serviceName: dev-inf-acme-mongodb-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mongodb
      release: dev-inf-acme-mongodb
      component: primary
  template:
    metadata:
      labels:
        app: mongodb
        chart: mongodb-7.10.6
        release: dev-inf-acme-mongodb
        component: primary
      annotations:
        prometheus.io/port: "9216"
        prometheus.io/scrape: "true"

    spec:
      serviceAccountName: dev-inf-acme-mongodb
      priorityClassName: critical-inf-priority
      securityContext:
        fsGroup: 1001
      initContainers:
      containers:
        - name: mongodb-primary
          image: docker.io/bitnami/mongodb:4.2.5-debian-10-r35
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          ports:
          - containerPort: 27017
            name: mongodb
          env:
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
          - name: MONGODB_DISABLE_SYSTEM_LOG
            value: "no"
          - name: MONGODB_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MONGODB_REPLICA_SET_MODE
            value: "primary"
          - name: MONGODB_REPLICA_SET_NAME
            value: "rs0"
          - name: MONGODB_ADVERTISED_HOSTNAME
            value: "$(MONGODB_POD_NAME).dev-inf-acme-mongodb-headless.dev-inf-acme.svc.cluster.local"
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dev-inf-acme-mongodb
                key: mongodb-root-password
          - name: MONGODB_REPLICA_SET_KEY
            valueFrom:
              secretKeyRef:
                name: dev-inf-acme-mongodb
                key: mongodb-replica-set-key
          - name: MONGODB_ENABLE_IPV6
            value: "no"
          - name: MONGODB_ENABLE_DIRECTORY_PER_DB
            value: "no"
          livenessProbe:
            exec:
              command:
                - pgrep
                - mongod
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - name: datadir
              mountPath: /bitnami/mongodb
              subPath:
            - name: config
              mountPath: /opt/bitnami/mongodb/conf/mongodb.conf
              subPath: mongodb.conf
          resources:
            limits:
              cpu: 1000m
              memory: 4096Mi
            requests:
              cpu: 200m
              memory: 1536Mi

        - name: metrics
          image: docker.io/bitnami/mongodb-exporter:0.10.0-debian-10-r63
          imagePullPolicy: "Always"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dev-inf-acme-mongodb
                key: mongodb-root-password
          command: [ 'sh', '-c', '/bin/mongodb_exporter --mongodb.uri mongodb://root:`echo $MONGODB_ROOT_PASSWORD | sed -r "s/@/%40/g;s/:/%3A/g"`@localhost:27017/admin ' ]
          ports:
          - name: metrics
            containerPort: 9216
          resources:
            limits:
              cpu: 50m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 128Mi

      volumes:
        - name: config
          configMap:
            name: dev-inf-acme-mongodb
  volumeClaimTemplates:
    - metadata:
        name: datadir
        annotations:
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "10Gi"
        storageClassName: ssd-zonal

---
# Source: mongodb/templates/statefulset-secondary-rs.yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dev-inf-acme-mongodb-secondary
  labels:
    app: mongodb
    chart: mongodb-7.10.6
    heritage: Tiller
    release: dev-inf-acme-mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
      release: dev-inf-acme-mongodb
      component: secondary
  podManagementPolicy: "Parallel"
  serviceName: dev-inf-acme-mongodb-headless
  replicas: 4
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongodb
        chart: mongodb-7.10.6
        release: dev-inf-acme-mongodb
        component: secondary
      annotations:
        prometheus.io/port: "9216"
        prometheus.io/scrape: "true"

    spec:
      serviceAccountName: dev-inf-acme-mongodb
      priorityClassName: critical-inf-priority
      securityContext:
        fsGroup: 1001
      initContainers:
      containers:
        - name: mongodb-secondary
          image: docker.io/bitnami/mongodb:4.2.5-debian-10-r35
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          ports:
          - containerPort: 27017
            name: mongodb
          env:
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
          - name: MONGODB_DISABLE_SYSTEM_LOG
            value: "no"
          - name: MONGODB_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MONGODB_REPLICA_SET_MODE
            value: "secondary"
          - name: MONGODB_PRIMARY_HOST
            value: dev-inf-acme-mongodb
          - name: MONGODB_REPLICA_SET_NAME
            value: "rs0"
          - name: MONGODB_ADVERTISED_HOSTNAME
            value: "$(MONGODB_POD_NAME).dev-inf-acme-mongodb-headless.dev-inf-acme.svc.cluster.local"
          - name: MONGODB_PRIMARY_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dev-inf-acme-mongodb
                key: mongodb-root-password
          - name: MONGODB_REPLICA_SET_KEY
            valueFrom:
              secretKeyRef:
                name: dev-inf-acme-mongodb
                key: mongodb-replica-set-key
          - name: MONGODB_ENABLE_IPV6
            value: "no"
          - name: MONGODB_ENABLE_DIRECTORY_PER_DB
            value: "no"
          livenessProbe:
            exec:
              command:
                - pgrep
                - mongod
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - name: datadir
              mountPath: /bitnami/mongodb
              subPath:
            - name: config
              mountPath: /opt/bitnami/mongodb/conf/mongodb.conf
              subPath: mongodb.conf
          resources:
            limits:
              cpu: 1000m
              memory: 4096Mi
            requests:
              cpu: 200m
              memory: 1536Mi

        - name: metrics
          image: docker.io/bitnami/mongodb-exporter:0.10.0-debian-10-r63
          imagePullPolicy: "Always"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dev-inf-acme-mongodb
                key: mongodb-root-password
          command: [ 'sh', '-c', '/bin/mongodb_exporter --mongodb.uri mongodb://root:`echo $MONGODB_ROOT_PASSWORD | sed -r "s/@/%40/g;s/:/%3A/g"`@localhost:27017/admin ' ]
          ports:
          - name: metrics
            containerPort: 9216
          resources:
            limits:
              cpu: 50m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 128Mi

      volumes:
        - name: config
          configMap:
            name: dev-inf-acme-mongodb
  volumeClaimTemplates:
    - metadata:
        name: datadir
        annotations:
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "10Gi"
        storageClassName: ssd-zonal

---
# Source: mongodb/templates/deployment-standalone.yaml

---
# Source: mongodb/templates/ingress.yaml


---
# Source: mongodb/templates/initialization-configmap.yaml


---
# Source: mongodb/templates/prometheus-alerting-rule.yaml


---
# Source: mongodb/templates/prometheus-service-monitor.yaml


---
# Source: mongodb/templates/pvc-standalone.yaml


---
# Source: mongodb/templates/svc-standalone.yaml

```
