### ISSUE TITLE
[bitnami/kube-prometheus] Renaming the instance to node

### ISSUE THREAD

**Issue by maggie44** [bitnami/charts#22002]
### Name and Version

bitnami/kube-prometheus

### What is the problem this feature will solve?

In Prometheus stack the output of this: `node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100` is this:

```
{container="node-exporter", endpoint="metrics", instance="10.253.0.101:9100", job="node-exporter", namespace="monitoring", pod="prometheus-node-exporter-dfl64", service="prometheus-node-exporter"}
```

In the  community Grafana stack Prometheus the `instance` is the name of the node not the IP. 

I have tried replacing it with this:

```
          serviceMonitor:
            enabled: true
            jobLabel: "nodename"
            relabelings:
              - action: replace
                sourceLabels: [__meta_kubernetes_pod_node_name]
                targetLabel: instance
```

And gone through these: https://stackoverflow.com/questions/49896956/relabel-instance-to-hostname-in-prometheus/64623786#64623786

Still no joy. I have looked through the different options in the [docs](https://github.com/bitnami/charts/tree/main/bitnami/kube-prometheus) but running out of ideas of how to customise the stack.

**Comment by javsalgar** [comment]
Hi,

It seems to me that this is more related to the configuration of node-exporter rather than the Bitnami packaging. Did you try checking with the node-exporter devs? 

https://github.com/prometheus/node_exporter

**Comment by maggie44** [comment]
Managed to resolve it with the following in the values.yaml:

```
node-exporter:
  serviceMonitor:
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        targetLabel: instance
```
