### ISSUE TITLE
[bitnami/influxdb] Helm : wrong configuration inside cronjob-backup.yaml file (Error: template: influxdb/charts/influxdb/templates/cronjob-backup.yaml)

### ISSUE THREAD

**Issue by trickytibo** [bitnami/charts#22068]
### Name and Version

bitnami/influxdb 5.11.2

### What architecture are you using?

None

### What steps will reproduce the bug?

```
$ helm template influxdb/ -f influxdb/myvalues.yaml 
Error: template: influxdb/charts/influxdb/templates/cronjob-backup.yaml:30:24: executing "influxdb/charts/influxdb/templates/cronjob-backup.yaml" at <.Values.backup.cronjob.securityContext.enabled>: nil pointer evaluating interface {}.enabled
```

Content of myvalues.yaml file :
 
``` 
backup:
      enabled: true
  
      cronjob:
  
          containerSecurityContext:
              enabled: true
              runAsUser: 1001
              runAsNonRoot: true
              privileged: false
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                  drop: ["ALL"]
              seccompProfile:
                  type: "RuntimeDefault"
```

### What do you see instead?

When trying to activate backup using helm, I got this error : 
_Error: template: influxdb/charts/influxdb/templates/cronjob-backup.yaml:30:24: executing "influxdb/charts/influxdb/templates/cronjob-backup.yaml" at <.Values.backup.cronjob.securityContext.enabled>: nil pointer evaluating interface {}.enabled_

Instead of looking for the **.Values.backup.cronjob.containerSecurityContext.enabled** (the one in the values.yaml file), it looks for **.Values.backup.cronjob.securityContext.enabled**. 
For making it to work, I had to add a new variable called securityContext in the cronjob section of the values.yaml file. 

```
backup:
    enabled: true

    cronjob:

        securityContext:
            enabled: true

        containerSecurityContext:
            enabled: true
            runAsUser: 1001
            runAsNonRoot: true
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
                drop: ["ALL"]
            seccompProfile:
                type: "RuntimeDefault"
```
