### ISSUE TITLE
[bitnami/rabbitmq] add extra tls configuration and ports

### ISSUE THREAD

**Issue by razvanphp** [bitnami/charts#22086]
### Name and Version

bitnami/rabbitmq 12.6.3

### What is the problem this feature will solve?

When enabling tls, configuration will be easier and no custom rules will be needed.

### What is the feature you are proposing to solve the problem?

Currently, when one enables tls, given that management plugin is also enabled by default, extraConfiguration needs to be added to set the certificate and port for this. Also the same for `web_mqtt` plugin.

It would be easier to add those as separate values so users can enable them easier.

My current (working values):
```yaml
  values:
    extraPlugins: rabbitmq_mqtt rabbitmq_web_mqtt
    auth:
      tls:
        enabled: true
        existingSecret: rabbitmq-tls-secret
        existingSecretFullChain: true
    ingress:
      enabled: true
      hostname: <my-hostname>.domain.com
      tls: true
      existingSecret: rabbitmq-tls-secret
      # annotations:
    extraConfiguration: |
      web_mqtt.ssl.port       = 15676
      web_mqtt.ssl.backlog    = 1024
      web_mqtt.ssl.cacertfile = /opt/bitnami/rabbitmq/certs/ca_certificate.pem
      web_mqtt.ssl.certfile   = /opt/bitnami/rabbitmq/certs/server_certificate.pem
      web_mqtt.ssl.keyfile    = /opt/bitnami/rabbitmq/certs/server_key.pem

      management.tcp.port      = 15672
      management.ssl.port       = 15671
      management.ssl.cacertfile = /opt/bitnami/rabbitmq/certs/ca_certificate.pem
      management.ssl.certfile   = /opt/bitnami/rabbitmq/certs/server_certificate.pem
      management.ssl.keyfile    = /opt/bitnami/rabbitmq/certs/server_key.pem
    service:
      nodePorts:
        manager: 15672
        amqpTls: 5671
      extraPorts:
      - name: manager-tls
        port: 15671
        targetPort: 15671
      - name: web-mqtt-tls
        port: 15676
        targetPort: 15676
```

### What alternatives have you considered?

Adding those ports in values as:

- `service.ports.managerTls` and `service.nodePorts.managerTls`
- `service.ports.mqtt` and `service.nodePorts.mqtt`
- `service.ports.mqttTls` and `service.nodePorts.mqttrTls`

... and having the certificates automatically included in the confguration.

Thank you!
