### ISSUE TITLE
[bitnami/grafana] unable to set SMTP

### ISSUE THREAD

**Issue by masterkain** [bitnami/charts#2213]
I'm using the latest 1.4.1 chart, these are the related helm values:

```
    extraEnvVars:
      - name: GF_SMTP_HOST
        value: email-smtp.eu-west-1.amazonaws.com:587
      - name: GF_SMTP_FROM_NAME
        value: 'my Charts'
      - name: GF_SMTP_FROM_ADDRESS
        value: 'developer@mydomain.com'

    smtp:
      enabled: true
      user: xxxxxx
      password: 'xxxx'
```

I verified that the chart installed successfully and env vars are present, however when trying to invite someone:

```
grafana t=2020-04-03T07:37:16+0000 lvl=eror msg="SMTP not configured, check your grafana.ini config file's [smtp] section" logger=context userId=1 orgId=1 uname=admin error="SMTP not configured, check your grafana.ini config file's [smtp] section"
```
