### ISSUE TITLE
[wildfly] Disable standalone.log file as it wastes space on the node

### ISSUE THREAD

**Issue by Xnyle** [bitnami/charts#2218]
Widlfly logs to stdout which is then handled by k8s but also to file inside of the container. This is a waste of resources and those file can grow quite large.

I Added the following to disable file logging:

```
      containers:
        - name: wildfly
          lifecycle:
            postStart:
              exec:
                command: 
                  - "/bin/sh"
                  - "-c"
                  - >
                    sleep 30;
                    /opt/bitnami/wildfly/bin/jboss-cli.sh -c --command='/subsystem=logging/root-logger=ROOT:remove-handler(name=FILE)' > /tmp/poststart.hook.stdout
```
