### ISSUE TITLE
[bitnami/redis] Can't open the append-only file: No such file or directory

### ISSUE THREAD

**Issue by Efp95** [bitnami/charts#2220]
**Describe the bug**
There's been a persistent volume I was using for Redis and it's been working as expected.
Recently, I got several restarts from my Redis pod due to the liveness probe.

According to what I saw in the container logs the restarts occur when the "Can't open the append-only file: No such file or directory"
There were 2 times that the pod kept restarting over and over.
A "workaround" was to delete my PersistentVolumeClaim and the Pod so the StatefulSet create others.

And one last thing, we have around 6 Redis pods deployed separately with the same configuration.
This issue occurred only for one of them (pod kept restarting).
There were also restarts for the other instances of Redis but they got up & running after a couple of restarts

**Version of Helm and Kubernetes**:
**_kubernetes_**
 version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**_helm_**
 &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

**Which chart**:
stable/redis v8.0.10

**What happened**:
Redis pod keeps restarting due to LivenessProbe (as first error description, then it shows up as _CrashLoopBackOff_).

**What you expected to happen**:
Pod gets up & running (after a restart maybe)

**How to reproduce it** (as minimally and precisely as possible):
I haven't identified repro steps. It has happened in our NONPROD and PROD clusters.

**Anything else we need to know**:
This is the config I've been using:

```
  usePassword: true
  password: "*********"
  nameOverride: appredis
  cluster:
    enabled: false
  master:
    statefulset:
      updateStrategy: RollingUpdate
    persistence:
      size: 1Gi
      storageClass: azurefile
```

And here you have and attachment from the log producing the error

![image](https://user-images.githubusercontent.com/12222605/78313703-4fb53b00-751d-11ea-9121-c6e8ba8a87e6.png)
