### ISSUE TITLE
[bitnami/kube-prometheus] Add Telegram support to kube-prometheus AlertManager

### ISSUE THREAD

**Issue by maggie44** [bitnami/charts#22234]
### Name and Version

bitnami/kube-prometheus

### What is the problem this feature will solve?

Alert Manager has native support for Telegram notifications, but the field is not available in the values of kube-prometheus.

A post [here](https://github.com/bitnami/charts/issues/10474#issuecomment-1141869220) suggests using `configuration`, but on deployment, it says it's not supported: `.spec.alertmanagerConfiguration.receivers: field not declared in schema`

```yaml
        alertmanager:
          configuration:
            receivers:
              - name: telegram-receiver
                telegram_configs:
                  - bot_token_file: token
                  - chat_id: -1234
```

And this:
```yaml
        alertmanager:
          configuration:
            - receivers:
              - name: telegram-receiver
                telegram_configs:
                  - bot_token_file: token
                  - chat_id: -1234
```

`expected map, got &{[map[receivers:[map[name:telegram-receiver telegram_configs:[map[bot_token_file:token chat_id:1234]]]]]]}`

### What is the feature you are proposing to solve the problem?

Inclusion of the receiver fields in the values that can be passed.

**Comment by javsalgar** [comment]
Hi,

If the operator throws that error, then it may be an issue with the CRD that currently does not support Telegram. Then this may not be an issue with the Bitnami packaging of Kube Prometheus but with upstream Kube Prometheus itself. Did you check with the prometheus-operator devs?

https://github.com/prometheus-operator/prometheus-operator

**Comment by maggie44** [comment]
Is this not it in your repo? https://github.com/bitnami/charts/blob/f208194cc57391fff8288f3466edb43f9aab4ddb/bitnami/kube-prometheus/crds/crd-alertmanagerconfigs.yaml#L3173

It’s an officially supported AlertManager feature and receivers is required for the email alerts too which is a longer standing feature.

**Comment by joancafom** [comment]
Hi @maggie44 

The file you referenced is related to `AlertmanagerConfig` resources:

https://github.com/bitnami/charts/blob/f208194cc57391fff8288f3466edb43f9aab4ddb/bitnami/kube-prometheus/crds/crd-alertmanagerconfigs.yaml#L3173

That means that you should create an `AlertmanagerConfig` resource in your cluster and then reference it using the `.Values.alertmanager.configuration` property.

**Comment by maggie44** [comment]
Not sure I follow. Isn't alertmanager.configuration a key/value pair?

https://github.com/bitnami/charts/blob/main/bitnami/kube-prometheus/README.md

| Name                                               | Description                                                                                            | Value                        |
| -------------------------------------------------- | ------------------------------------------------------------------------------------------------------ | ---------------------------- |
| `alertmanager.configuration`                                     | EXPERIMENTAL: alertmanagerConfiguration specifies the global Alertmanager configuration. If defined, it takes precedence over the `configSecret` field. This field may change in future releases. The specified global alertmanager config will not force add a namespace label in routes and inhibitRules | `{}`                           |

**Comment by joancafom** [comment]
> Not sure I follow. Isn't alertmanager.configuration a key/value pair?

I think I might understand your confusion now, @maggie44. `kube-prometheus`'s AlertManager can **ALTERNATIVELY** be configured using an `AlertmanagerConfig` CRD as I mentioned (it must be defined in the same namespace as the Alertmanager object). So, if you are using this option, you should reference the created object back in the values using this syntax (as far as I can tell from the CRD definition):

```
alertmanager:
  configuration:
    name: nameOfTheAlertmanagerConfigurationCrdInYourCluster
```

Nevertheless, you can also provide your configuration file contents **directly** (I think this is what you are intending to do) using the `alertmanager.config` param in values:

https://github.com/bitnami/charts/blob/1c9cbd5c06353a96ab690ab4d79afd55cd57e26e/bitnami/kube-prometheus/values.yaml#L1989-L2003

**Comment by maggie44** [comment]
I have no idea how I managed to miss the `config` option. I think I must have seen `configuration` and got tunnel visioned. 

Ended up getting it to work with 

```
        alertmanager:
          config:
            route:
              group_by: ["instance"]
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 30m
              receiver: telegram-receiver
              routes:
                - receiver: null
            receivers:
              - name: telegram-receiver
                telegram_configs:
                  - bot_token_file: /etc/alertmanager/secrets/telegram-secret/token
                    chat_id: -1234
```
