### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] RabbitMQ cluster operator roles are overridden by custom rules

### ISSUE THREAD

**Issue by Zerpet** [bitnami/charts#22248]
### Name and Version

bitnami/rabbitmq-cluster-operator 3.10.10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create custom rules for the RBAC in `values.yaml`
    ```
    clusterOperator:
      rbac:
        create: true
        clusterRole:
          customRules:
            - apiGroups:
                - policy
              resourceNames:
                - example
              resources:
                - podsecuritypolicies
              verbs:
                - use
    ```
2. Pull the template: `helm pull bitnami/rabbitmq-cluster-operator`
3. Render the template
    ```
    helm template rabbitmq-operator ./rabbitmq-cluster-operator-3.10.10.tgz --values ./repro.yaml --show-only "templates/cluster-operator/clusterrole.yaml"
    ```
4. Observe the cluster role only have the RBAC rules in the `customRules` section

### Are you using any custom parameters or values?

```yaml
clusterOperator:
  rbac:
    create: true
    clusterRole:
      customRules:
        - apiGroups:
            - policy
          resourceNames:
            - example
          resources:
            - podsecuritypolicies
          verbs:
            - use
```

### What is the expected behavior?

The rules in `customRules` section should be appended and/or merged with the rules in cluster role template.

### What do you see instead?

The custom rules are set as cluster role rules. Cluster role rules in the template are not rendered.

### Additional information

I'm not sure if this is a bug, or intended behaviour. In its current state, I think it's not particularly useful, because the users of this chart don't know the RBAC needed to run the operator; but they do know the RBAC needed to run in _their_ environment. In my particular case, I need to append a rule to use Pod Security Policies in my environment, and I'd like to declare those in the values YAML, without having to carry over all the RBAC rules from upstream rabbitmq operator.
