### ISSUE TITLE
[bitnami/logstash] plugin install behind a proxy

### ISSUE THREAD

**Issue by mayac-philips** [bitnami/charts#22255]
### Name and Version

bitnami/logstash 8.10.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. k3s on-prem server behind a proxy (agent is configured with the proy inside service agent)
2. logstash with ELK stack of kibana and elasticsearch
3. Trying to install opensearch plugin - added as env values in values.yaml

logs:
```
logstash 15:15:44.06
logstash 15:15:44.07 Welcome to the Bitnami logstash container
logstash 15:15:44.07 Subscribe to project updates by watching https://github.com/bitnami/containers
logstash 15:15:44.07 Submit issues and feature requests at https://github.com/bitnami/containers/issues
logstash 15:15:44.07
logstash 15:15:44.08 INFO  ==> ** Starting Logstash setup **
logstash 15:15:44.10 INFO  ==> Initializing Logstash
logstash 15:15:44.14 INFO  ==> Mounted setting files detected
logstash 15:15:44.15 INFO  ==> Enabling Logstash API endpoint
logstash 15:15:44.21 INFO  ==> Creating pipelines.yml file for multiple pipelines
logstash 15:15:44.25 WARN  ==> Detected mounted '/bitnami/logstash/config/logstash.conf' pipeline configuration file in legacy directory.
logstash 15:15:44.25 WARN  ==> Support for this configuration may be deprecated in a future version of this image. Please mount the pipeline files to '/bitnami/logstash/pipeline' instead.
logstash 15:15:44.26 INFO  ==> Installing plugins: logstash-output-opensearch
```
It just stuck on installing without indication of the issue, but my guess is it's the proxy. How I define a proxy to logstash?

### Are you using any custom parameters or values?

I tried this, but with no effect in values.yaml:
```
extraEnvVars:
  - name: HTTPS_PROXY
    value: "http://x.x.x.x:443"
  - name: Dhttps.proxyHost
    value: "http://x.x.x.x"
  - name: Dhttps.proxyPort
    value: "443"
```
### What is the expected behavior?

Logstash understanding it's using proxy, and download the plugin through the proxy.

### What do you see instead?
```
logstash 15:15:44.25 WARN  ==> Support for this configuration may be deprecated in a future version of this image. Please mount the pipeline files to '/bitnami/logstash/pipeline' instead.
logstash 15:15:44.26 INFO  ==> Installing plugins: logstash-output-opensearch
```
Logstash stuck on trying install the plugin

**Comment by fmulero** [comment]
Hi @mayac-philips, sorry about my very late response.

Under the hood we are using [logstash-plugin](https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html) and it seems the tool is expecting the HTTP proxy env vars in lower case. Have you tried anything like this?
```yaml
extraEnvVars:
  - name: HTTPS_PROXY
    value: "http://x.x.x.x:443"
  - name: https_proxy
    value: "http://x.x.x.x:443"
```

**Comment by mayac-philips** [comment]
@fmulero I've tried with lower case as you suggested. Still same result. 

```
logstash 10:21:07.01
logstash 10:21:07.01 Welcome to the Bitnami logstash container
logstash 10:21:07.01 Subscribe to project updates by watching https://github.com/bitnami/containers
logstash 10:21:07.01 Submit issues and feature requests at https://github.com/bitnami/containers/issues
logstash 10:21:07.02
logstash 10:21:07.02 INFO  ==> ** Starting Logstash setup **
logstash 10:21:07.04 INFO  ==> Initializing Logstash
logstash 10:21:07.07 INFO  ==> Mounted setting files detected
logstash 10:21:07.08 INFO  ==> Enabling Logstash API endpoint
logstash 10:21:07.11 INFO  ==> Detected mounted 'pipelines.yml' configuration file for multiple pipelines
logstash 10:21:07.12 INFO  ==> Creating sample config file
logstash 10:21:07.14 INFO  ==> Installing plugins: logstash-output-opensearch
```

**Comment by mayac-philips** [comment]
@fmulero 
I ran the helm chart with debug as true and got this error.

```
Using system java: /opt/bitnami/java/bin/java
Errno::EACCES: Permission denied - /.m2
            mkdir at org/jruby/RubyDir.java:660
         fu_mkdir at /opt/bitnami/logstash/vendor/jruby/lib/ruby/stdlib/fileutils.rb:243
          mkdir_p at /opt/bitnami/logstash/vendor/jruby/lib/ruby/stdlib/fileutils.rb:221
     reverse_each at org/jruby/RubyArray.java:2071
          mkdir_p at /opt/bitnami/logstash/vendor/jruby/lib/ruby/stdlib/fileutils.rb:219
             each at org/jruby/RubyArray.java:1989
          mkdir_p at /opt/bitnami/logstash/vendor/jruby/lib/ruby/stdlib/fileutils.rb:211
  configure_proxy at /opt/bitnami/logstash/lib/pluginmanager/proxy_support.rb:112
           <main> at /opt/bitnami/logstash/lib/pluginmanager/main.rb:42
```

**Comment by fmulero** [comment]
Hi @mayac-philips 

I am trying to reproduce your issue but I couldn't do it. Could you share the following information?:
* Chart version. The version reported above is the logstash version, not the chart one.
* Values or configuration. Are you using persistence? Are you using any pod or container security context?
* You are using a HTTPS proxy. Does it modify the certificates exposed? Did you need to install CAs in the container?
* Do you have any extension or admision controller in your k3d cluster that could change the behaviour of the chart?

**Comment by mayac-philips** [comment]
@fmulero 
1. chart version -  8.12.0 (i upgraded to latest when saw the error)
2. Valus yaml - 
```
mounts 
extraVolumes:
  - name: data-logs
    hostPath:
      path: /data/Elastic/
      type: Directory
## @param extraVolumeMounts Array to add extra mounts (normally used with extraVolumes, evaluated as a template)
extraVolumeMounts:
  - mountPath: /data
    name: data-logs
    readOnly: false
   
 podSecurityContext:
      enabled: true
     fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
    fsGroup: 1001
   
 containerSecurityContext:
    enabled: true
    seLinuxOptions: null
    runAsUser: 1001
    runAsNonRoot: true
   privileged: false
   readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"

persistence:
  enabled: true
  existingClaim: ""
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 2Gi
  annotations: {}
  selector: {}
```
   3. I didn't instal certifiacte to logstash, only for kibana
   4. I didn't add any extenstion. I used default config. I've installed on a server k3s

Thanks,

**Comment by fmulero** [comment]
I've just reproduced your issue. I span up a `tinyproxy` web proxy and changed the configuration above to point to my http proxy:

```console
$ docker run -d --name="tinyproxy" --rm -p 4444:8888 -e "LOG_LEVEL=Notice" francisbesset/tinyproxy "192.168.
0.0/16"
$ k3d cluster create --volume /Users/fmulero/workspace/support/charts/22255/Elastic/:/data/Elastic
$ helm install logstash bitnami/logstash -f  /Users/fmulero/workspace/support/charts/22255/logstash.yaml 
NAME: logstash
LAST DEPLOYED: Tue Mar  5 11:59:36 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: logstash
CHART VERSION: 5.11.3
APP VERSION: 8.12.2

** Please be patient while the chart is being deployed **

Logstash can be accessed through following DNS names from within your cluster:

    Logstash: logstash.default.svc.cluster.local

To access Logstash from outside the cluster execute the following commands:

    export SERVICE_PORT=$(kubectl get --namespace default -o jsonpath="{.spec.ports[0].port}" services logstash)
    kubectl --namespace default port-forward svc/logstash ${SERVICE_PORT}:${SERVICE_PORT} &
    echo "http://127.0.0.1:${SERVICE_PORT}"

WARNING: There are "resources" sections in the chart not set. Using "resourcesPreset" is not recommended for production. For production installations, please set the following values according to your workload needs:
  - resources
+info https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
$ k logs -f logstash-0
logstash 10:46:36.00 INFO  ==> 
logstash 10:46:36.00 INFO  ==> Welcome to the Bitnami logstash container
logstash 10:46:36.00 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
logstash 10:46:36.00 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
logstash 10:46:36.01 INFO  ==> 
logstash 10:46:36.01 INFO  ==> ** Starting Logstash setup **
logstash 10:46:36.02 DEBUG ==> Validating settings in LOGSTASH_* environment variables
logstash 10:46:36.03 INFO  ==> Initializing Logstash
logstash 10:46:36.03 DEBUG ==> Using specified values for Xmx and Xms heap options
logstash 10:46:36.03 DEBUG ==> Setting '-Xmx1024m -Xms1024m' heap options
logstash 10:46:36.04 INFO  ==> Mounted setting files detected
logstash 10:46:36.04 INFO  ==> Enabling Logstash API endpoint
logstash 10:46:36.06 WARN  ==> Detected mounted '/bitnami/logstash/config/logstash.conf' pipeline configuration file in legacy directory.
logstash 10:46:36.06 WARN  ==> Support for this configuration may be deprecated in a future version of this image. Please mount the pipeline files to '/bitnami/logstash/pipeline' instead.
logstash 10:46:36.07 INFO  ==> Installing plugins: logstash-output-opensearch
logstash 10:46:36.07 DEBUG ==> Installing plugin: logstash-output-opensearch
Using system java: /opt/bitnami/java/bin/java
Errno::EACCES: Permission denied - /.m2
            mkdir at org/jruby/RubyDir.java:660
         fu_mkdir at /opt/bitnami/logstash/vendor/jruby/lib/ruby/stdlib/fileutils.rb:243
          mkdir_p at /opt/bitnami/logstash/vendor/jruby/lib/ruby/stdlib/fileutils.rb:221
     reverse_each at org/jruby/RubyArray.java:2071
          mkdir_p at /opt/bitnami/logstash/vendor/jruby/lib/ruby/stdlib/fileutils.rb:219
             each at org/jruby/RubyArray.java:1989
          mkdir_p at /opt/bitnami/logstash/vendor/jruby/lib/ruby/stdlib/fileutils.rb:211
  configure_proxy at /opt/bitnami/logstash/lib/pluginmanager/proxy_support.rb:112
           <main> at /opt/bitnami/logstash/lib/pluginmanager/main.rb:42
```

It seems the library `lib/pluginmanager/proxy_support.rb` is trying to create the '/.m2' folder to store the proxy configuration before downloading the plugins. As workaround you can set the `HOME` env var pointing to folder with write permissions. With this configuration I could spin up the containers:
```yaml
image:
  debug: true
extraEnvVars:
  - name: HOME
    value: /bitnami/logstash/data
  - name: HTTP_PROXY
    value: "http://192.168.0.234:4444"
  - name: http_proxy
    value: "http://192.168.0.234:4444"
  - name: LOGSTASH_PLUGINS
    value: logstash-output-opensearch
extraVolumes:
  - name: data-logs
    hostPath:
      path: /data/Elastic/
      type: Directory
## @param extraVolumeMounts Array to add extra mounts (normally used with extraVolumes, evaluated as a template)
extraVolumeMounts:
  - mountPath: /data
    name: data-logs
    readOnly: false
   
podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
  fsGroup: 1001
   
containerSecurityContext:
  enabled: true
  seLinuxOptions: null
  runAsUser: 1001
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"
networkPolicy:
  allowExternalEgress: true
persistence:
  enabled: true
  existingClaim: ""
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 2Gi
  annotations: {}
  selector: {}
```
