### ISSUE TITLE
Specify buckets with policies

### ISSUE THREAD

**Issue by zatselyapin** [bitnami/charts#2233]
**Which chart**:
bitnami/minio
**Is your feature request related to a problem? Please describe.**
I am trying to set up a structure of buckets with various policies
via chart values 

**Describe the solution you'd like**
I want to be able to add something like this into values
and get a structure of buckets with policies.

```
buckets:
    - name: private 
      policy: none
      purge: true
    - name: static
      policy: download
      purge: true

```	  
	  
**Describe alternatives you've considered**

The only alterantive solution i can see here is to use command line tools
The alternative to use command lines tools after installations is not acceptables
unless i will be able to do it via values
