### ISSUE TITLE
[bitnami/rabbitmq] StatefulSet PVC template does not set common labels

### ISSUE THREAD

**Issue by javsalgar** [bitnami/charts#22364]
It seems this is happening with the RabbitMQ chart too. I tried to set `commonLabels` and also `persistence.labels`, and it didn't take any effect on created PVCs.

Below is what my `values.yaml` looks like right now.

<details>
  <summary>values.yaml</summary>

```yaml
# ... rest of file above

## @param commonLabels Labels to add to all deployed objects
##
commonLabels:
  recurring-job.longhorn.io/source: enabled
  recurring-job-group.longhorn.io/three-times-day-backup: enabled

# ...
## @section Persistence parameters
##
persistence:
  ## @param persistence.enabled Enable RabbitMQ data persistence using PVC
  ##
  enabled: true
  
  ## @param persistence.storageClass PVC Storage Class for RabbitMQ data volume
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: longhorn
  
  ## @param persistence.selector Selector to match an existing Persistent Volume
  ## selector:
  ##   matchLabels:
  ##     app: my-app
  ##
  # selector: {}
  
  ## @param persistence.accessModes PVC Access Modes for RabbitMQ data volume
  ##
  accessModes:
    - ReadWriteOnce
  
  ## @param persistence.existingClaim Provide an existing PersistentVolumeClaims
  ## The value is evaluated as a template
  ## So, for example, the name can depend on .Release or .Chart
  ##
  # existingClaim: rabbitmq-pvc

  ## @param persistence.mountPath The path the volume will be mounted at
  ## Note: useful when using custom RabbitMQ images
  ##
  # mountPath: /bitnami/rabbitmq/mnesia
  ## @param persistence.subPath The subdirectory of the volume to mount to
  ## Useful in dev environments and one PV for multiple services
  ##
  # subPath: ""

  ## @param persistence.size PVC Storage Request for RabbitMQ data volume
  ## If you change this value, you might have to adjust `rabbitmq.diskFreeLimit` as well
  ##
  size: 3Gi
  
  ## @param persistence.annotations Persistence annotations. Evaluated as a template
  ## Example:
  ## annotations:
  ##   example.io/disk-volume-type: SSD
  ##
  # annotations: {}

  ## @param persistence.labels Persistence labels. Evaluated as a template
  ## Example:
  ## labels:
  ##   app: my-app
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/three-times-day-backup: enabled
```
</details>

Am I doing something wrong?

_Originally posted by @italoiz in https://github.com/bitnami/charts/issues/20373#issuecomment-1893907025_
