### ISSUE TITLE
[Cassandra Chart]  Passwordless and userless feature toggle for development purposes

### ISSUE THREAD

**Issue by cfontes** [bitnami/charts#2240]
**Which chart**:
Cassandra Chart 5.2.0

**Is your feature request related to a problem? Please describe.**
In dev having security on can sometimes be not ideal

**Describe the solution you'd like**
Would be nice to have a feature to completely disable it, by setting `authenticator: AllowAllAuthenticator` and `authorizer: AllowAllAuthorizer`, so one can use the cassandra cluster without any password or authentication.

**Describe alternatives you've considered**
I am working around it now by completelly replacing the whole configuration by fecthing the chart and adding a cassandra.yaml without security to the /files/conf folder and deploying this locally modified chart, which is very manual and error prone.

That is it!

Thanks for the chart, it is great!

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the feedback. Question, wouldn't using init scripts cover your use case? You could create a script that overrides the authentication mechanism prior to launching the Cassandra daemon.

https://github.com/bitnami/charts/blob/master/bitnami/cassandra/values.yaml#L198

It supports cql scripts and bash scripts.

**Comment by cfontes** [comment]
Hello, thanks for the answer, that is a good idea.

My point for opening this ticket is even though this has a couple possible fixes, none of the ones I could find were user friendly like I see with the other configurations in the chart.

**Comment by a1kemist** [comment]
@javsalgar I tried your recommendation of using an initdb script to set the `authenticator` from `PasswordAuthenticator` to `AllowAllAuthenticator` and `authorizer` from `CassandraAuthorizer` to `AllowAllAuthorizer`, but the install scripts are applied _after_ cassandra is already started and the updated configuration doesn't take effect as seen here:

```
[38;5;6mcassandra [38;5;5m03:45:31.85 [0m[38;5;2mINFO [0m ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
Disabling auth in cassandra.yaml
Auth disabled in cassandra.yaml
[38;5;6mcassandra [38;5;5m03:45:31.88 [0m[38;5;2mINFO [0m ==> ** Cassandra setup finished! **

[38;5;6mcassandra [38;5;5m03:45:31.90 [0m[38;5;2mINFO [0m ==> ** Starting Cassandra **
[38;5;6mcassandra [38;5;5m03:45:31.91 [0m[38;5;2mINFO [0m ==> Cassandra already running with PID 183 because of the intial cluster setup
```

If I exec into the pod I can confirm that the script was applied and that the cassandra.yaml file contains the expected entries, but due to the fact that the database is not restarted after the initdb scripts, the old configuration seems to still be in memory.

If I restart the pod, then the initdb script is not run and the configuration is reset to the `PasswordAuthenticator` and `CassandraAuthorizer`. Is there another way to disable auth for local development as @cfontes proposes? If not, would you accept a pull request to add the ability to specify the `authenticator` and `authorizer` sections of the config?

For reference, this is the config map that I used:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db
data:
  disable-auth.sh: |
    #!/bin/bash
    
    set -euo pipefail
    
    echo "Disabling auth in cassandra.yaml"
    
    sed -i \
      -e s"/authenticator: 'PasswordAuthenticator'/authenticator: 'AllowAllAuthenticator'/" \
      -e s"/authorizer: 'CassandraAuthorizer'/authorizer: 'AllowAllAuthorizer'/" \
      /opt/bitnami/cassandra/conf/cassandra.yaml

    echo "Auth disabled in cassandra.yaml"
```

**Comment by javsalgar** [comment]
Hi,

Because Cassandra is hard to deal when restarting, especially when building the cluster, the init scripts don't stop Cassandra. In this sense, maybe it makes sense for you to also make Cassandra stop in your user scripts. You could load the `libcassandra.sh` that we have in the container and make use of the cassandra_stop function.

https://github.com/bitnami/bitnami-docker-cassandra/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh#L972

**Comment by a1kemist** [comment]
I believe that would work for the first start, but it wouldn't handle the case of a pod/container restart as far as I understand because the conf gets reverted back to its original state and the initdb scripts aren't executed on pod/container restart. (see #1277)

IMO having a first class way to do this is preferable.

**Comment by cfontes** [comment]
@a1kemist I am also struggling to make it work properly.

Indeed some sort of configuration version of it, would be better.

**Comment by javsalgar** [comment]
Hi,

Yes, I see two things:

    - We should allow init scripts to be re-executed on container restarts, because as you said the configuration would revert.
    - Regarding adding explicit support in the container, that's something we can evaluate.

I will create tasks for evaluation. Thanks for the feedback!

**Comment by cfontes** [comment]
As a work around for now, use the `existingConfiguration` feature and override the whole config file.

That works for me.

**Comment by javsalgar** [comment]
Thanks for confirming that with that you can make it work :)

**Comment by dmilcevski** [comment]
> As a work around for now, use the `existingConfiguration` feature and override the whole config file, in case you want security off.
> 
> That works for me.

How do you setup the _listen_address_, _broadcast_rpc_address_ in case of a cluster? They are the names of the pods and cannot be the same in a cluster.

**Comment by scottgrasley** [comment]
Leveraging the `extraEnvVars` feature seems to do the trick for a development environment.
```
  extraEnvVars:
    - name: CASSANDRA_AUTHENTICATOR
      value: AllowAllAuthenticator
    - name: CASSANDRA_AUTHORIZER
      value: AllowAllAuthorizer
```
