### ISSUE TITLE
Cloudflare DNS continuously deleted/created

### ISSUE THREAD

**Issue by jaygorrell** [bitnami/charts#2247]
**Which chart**:
`external-dns` version 2.20.10

**Describe the bug**
Using the latest (2.20.10) with Cloudflare and the following settings.

```
        policy: sync
        provider: cloudflare
        txtOwnerId: {{ .Environment.Values.externalDnsTxtOwnerId }}
        extraEnv:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare
                key: api_token
```

The `external-dns` system is continuously deleting and recreating records once per minute (logged as `msg="Changing record." action=UPDATE`) for all Ingress records. After some searching, this came up in the past and the fix was to revert to the 0.5.17 image (https://github.com/kubernetes-sigs/external-dns/issues/992#issuecomment-575823459). 

I was skeptical since things have advanced since then, but decided to try this I tried this and confirmed it worked. This is from `0.7.0-debian-10-r21`, which is the most recent at the time of this issue.

There are a handful of other closed issues describing this behavior that was apparently fixed in the past, but I'm creating a new issue as requested at the end of https://github.com/kubernetes-sigs/external-dns/issues/992.

**To Reproduce**
1. Deploy chart 2.20.10 with the above settings.
2. Create a basic ingress with no external-dns annotations (especially TTL)
3. Observe `external-dns` logs or Cloudflare audit logs

**Expected behavior**
DNS should only be updated when Ingress changes, and logs should be relatively quiet.

**Version of Helm and Kubernetes**:
helm2 / k8s 1.15.10 (eks)

**Additional context**
In the past this was related to proxied DNS records and TTL issues, however it is occurring when no TTL is specified in annotations.
