### ISSUE TITLE
[bitnami/memcached] Autoscaling ends in ContainerCreation/Termination loop for replicas

### ISSUE THREAD

**Issue by mscdit** [bitnami/charts#22502]
### Name and Version

bitnami/memcached 6.8.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Using a managed Kubernetes cluster at OVH and deployed memcached (via argoCD) by using:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memcached
  namespace: argocd
spec:
  project: production
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: memcached
    targetRevision: 6.8.1
    helm:
      values: |
        storageClass: "csi-cinder-high-speed"
        architecture: "high-availability"
        persistence:
          enabled: true
          size: 10Gi
        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 6
          targetCPU: 50
          targetMemory: 50
        metrics:
          enabled: true
          podAnnotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "9150"
          service:
            annotations: {
              "prometheus.io/scrape": "true",
              "prometheus.io/port": "9150"
            }
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: memcached
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=false
    - CreateNamespace=true
```

### What is the expected behavior?

I expect two running/working memcached pods memcached-0 and memcached-1.

### What do you see instead?

Problem is that pod memcached-0 gets created normally (and works) but pod memcached-1 quits recurring immediately after ContainerCreation - see logs:
```
~ % kubectl -n memcached logs -f pod/memcached-1 -c memcached
memcached 20:39:34.34 INFO  ==> 
memcached 20:39:34.34 INFO  ==> Welcome to the Bitnami memcached container
memcached 20:39:34.34 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
memcached 20:39:34.34 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
memcached 20:39:34.34 INFO  ==> 
memcached 20:39:34.35 INFO  ==> ** Starting Memcached setup **
memcached 20:39:34.36 INFO  ==> Initializing Memcached
memcached 20:39:34.37 INFO  ==> ** Memcached setup finished! **

memcached 20:39:34.37 INFO  ==> ** Starting Memcached **
Exiting normally
```

<img width="1194" alt="Bildschirmfoto 2024-01-18 um 22 11 13" src="https://github.com/bitnami/charts/assets/105646066/5f56e6b2-093d-40a3-8770-2c5af50888a5">
