### ISSUE TITLE
[bitnami/milvus] panic: parse bool useIAM:strconv.ParseBool: parsing "<nil>": invalid syntax

### ISSUE THREAD

**Issue by christian-nickerson-faculty** [bitnami/charts#22519]
### Name and Version

bitnami/milvus:5.3.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create an EKS Cluster, with private subnets with EBS CSI Drivers
2. Create an S3 bucket (to be used in place of MinIO)
3. Create an IAM User, keys with a `s3:*`  policy on all resources, deploy as a k8 secret (for development purposes)
4. Helm install the chart 

### Are you using any custom parameters or values?

```yaml
attu:
  enabled: false

minio:
  enabled: false

externalS3:
  host: "https://BUCKET_NAME.s3.REGION.amazonaws.com"
  existingSecret: SECRET_NAME
  cloudProvider: "aws"
```

### What is the expected behavior?

Service should deploy successfully

### What do you see instead?

All init containers pass and the milvus containers start, however, they error and backoff. Running `kubectl -n NAME_SPACE -f POD_NAME` shows the `useIAM` doesnt parse properly:

```txt
Defaulted container "milvus" out of: milvus, wait-for-etcd (init), wait-for-kafka (init), wait-for-s3 (init), prepare-milvus (init)
panic: parse bool useIAM:strconv.ParseBool: parsing "<nil>": invalid syntax

goroutine 1 [running]:
github.com/milvus-io/milvus/internal/util/paramtable.(*MinioConfig).initUseIAM(0x5eba128)
        /bitnami/blacksmith-sandox/milvus-2.2.14/src/github.com/milvus-io/milvus/internal/util/paramtable/service_param.go:579 +0x1ea
github.com/milvus-io/milvus/internal/util/paramtable.(*MinioConfig).init(0x5eba128, 0x4685dc0?)
        /bitnami/blacksmith-sandox/milvus-2.2.14/src/github.com/milvus-io/milvus/internal/util/paramtable/service_param.go:512 +0x79
github.com/milvus-io/milvus/internal/util/paramtable.(*ServiceParam).Init(0x5eb9e00)
        /bitnami/blacksmith-sandox/milvus-2.2.14/src/github.com/milvus-io/milvus/internal/util/paramtable/service_param.go:70 +0x1a5
github.com/milvus-io/milvus/internal/util/paramtable.(*ComponentParam).Init(0x5eb9e00)
        /bitnami/blacksmith-sandox/milvus-2.2.14/src/github.com/milvus-io/milvus/internal/util/paramtable/component_param.go:86 +0x25
github.com/milvus-io/milvus/internal/util/interceptor.init.0()
        /bitnami/blacksmith-sandox/milvus-2.2.14/src/github.com/milvus-io/milvus/internal/util/interceptor/interceptor.go:26 +0x25
```

### Additional information

looking at the `values.yaml`, there is no supported value that overrides this:

```yaml
    # S3 configuration
    minio:
      address: {{ include "milvus.s3.host" . }}
      port: {{ include "milvus.s3.port" . }}
      accessKeyID: {{ print "{{ MILVUS_S3_ACCESS_ID }}" | quote }}
      secretAccessKey: {{ print "{{ MILVUS_S3_SECRET_ACCESS_KEY }}" | quote }}
      useSSL: {{ include "milvus.s3.useSSL" . }}
      bucketName: {{ include "milvus.s3.bucket" . }}
      rootPath: {{ include "milvus.s3.rootPath" . }}
      useIAM: {{ include "milvus.s3.useIAM" . }}
      {{- if not .Values.minio.enabled }}
      cloudProvider: {{ .Values.externalS3.cloudProvider }}
      iamEndpoint: {{ .Values.externalS3.iamEndpoint }}
      {{- end }}
```
