### ISSUE TITLE
[bitnami/wordpress] Injecting extra config into wp-config.php

### ISSUE THREAD

**Issue by v1nc3nt27** [bitnami/charts#22513]
### Name and Version

bitnami/wordpress 19.1.2 helm chart

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I use the latest helm chart 19.1.2 and I want to inject extra config via wordpressExtraConfigContent

```yaml
wordpressExtraConfigContent: |
  define('WP_ALLOW_REPAIR', true);
```

I saw https://github.com/bitnami/charts/pull/21616 and I was wondering if there is any setup that allows wordpressExtraConfigContent to work or is it buggy at the moment?

### Are you using any custom parameters or values?

```yaml
wordpressSkipInstall: true 
wordpressExtraConfigContent: |
  define('WP_ALLOW_REPAIR', true);
```

### What is the expected behavior?

I expect that the additional config is added to wp-config.php

### What do you see instead?

Nothing is added.
