### ISSUE TITLE
[bitnami/prometheus-operator] Prometheus data volume is not mounted into the thanos sidecar

### ISSUE THREAD

**Issue by ni-ajardan** [bitnami/charts#2251]
**Which chart**:
bitnami/prometheus-operator

**Describe the bug**
To be able to sync Prometheus data to a Cloud Object Storage, the thanos sidecar container should also mount the data volume where Prometheus is saving its data. This doesn't happen:

```
- args:
        - sidecar
        - --prometheus.url=http://localhost:9090
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --tsdb.path=/opt/bitnami/prometheus/data/
        env:
        - name: OBJSTORE_CONFIG
          valueFrom:
            secretKeyRef:
              key: thanos.yaml
              name: thanos-objstore-config
        image: docker.io/bitnami/thanos:0.11.0-scratch-r9
        imagePullPolicy: IfNotPresent
        name: thanos-sidecar
        ports:
        - containerPort: 10901
          name: grpc
          protocol: TCP
        - containerPort: 10902
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      serviceAccount: prometheus-prometheus-oper-prometheus
      serviceAccountName: prometheus-prometheus-oper-prometheus
      terminationGracePeriodSeconds: 600
      volumes:
      - name: config
        secret:
          defaultMode: 420
          secretName: prometheus-prometheus-prometheus-oper-prometheus
      - name: tls-assets
        secret:
          defaultMode: 420
          secretName: prometheus-prometheus-prometheus-oper-prometheus-tls-assets
      - emptyDir: {}
        name: config-out
      - configMap:
          defaultMode: 420
          name: prometheus-prometheus-prometheus-oper-prometheus-rulefiles-0
        name: prometheus-prometheus-prometheus-oper-prometheus-rulefiles-0
```
Which results in these errors:

```
level=warn ts=2020-04-07T10:38:37.598380229Z caller=sidecar.go:339 err="iter local block metas: read dir: open /opt/bitnami/prometheus/data/: no such file or directory" uploaded=0
level=warn ts=2020-04-07T10:38:37.598464718Z caller=sidecar.go:344 msg="reading timestamps failed" err="read shipper meta file: open /opt/bitnami/prometheus/data/thanos.shipper.json: no such file or directory"
```

**To Reproduce**
1. Deploy this chart with this configuration:
```
prometheus:
  disableCompaction: true
  thanos:
    create: true
    extraArgs:
      - "--objstore.config={type: GCS, config: {bucket: prometheus-bucket-name}}"
      - "--tsdb.path=/opt/bitnami/prometheus/data/"  
  storageSpec:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
```
2. Check bucket for Prometheus data
3. See it empty
4. Check the Prometheus POD logs
5. Find the errors mentioned above

**Expected behavior**
As I can see from the Prometheus Operator code, when the thanos sidecar spec is generated, VolumeMounts are also added (from Prometheus config): https://github.com/coreos/prometheus-operator/blob/5bf25f7abc446a912fc2bb99152463a2323a90a1/pkg/prometheus/statefulset.go#L792

So I would expect the volume prometheus-prometheus-prometheus-oper-prometheus-db to be mounted into thanos sidecar container as well, and the object storage sync to work properly.

**Version of Helm and Kubernetes**:
Helm 3.1.2 

Kubernetes v1.15.11-gke.3

- Output of `helm version`:

```
$ helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
$ k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.3", GitCommit:"71631703d37fb1b4b333abd427deae839aeb2032", GitTreeState:"clean", BuildDate:"2020-03-24T18:54:48Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Mauraza** [comment]
Hi @ni-ajardan,

could you post `kubectl describe pvc prometheus-prometheus-prometheus-oper-prometheus-db-prometheus-prometheus-prometheus-oper-prometheus-0` ?

**Comment by ni-ajardan** [comment]
@Mauraza sure, here you go:

```
k -n mon describe pvc prometheus-prometheus-prometheus-oper-prometheus-db-prometheus-prometheus-prometheus-oper-prometheus-0
Name:          prometheus-prometheus-prometheus-oper-prometheus-db-prometheus-prometheus-prometheus-oper-prometheus-0
Namespace:     mon
StorageClass:  standard
Status:        Bound
Volume:        pvc-9ba60dad-6011-4322-90e5-3be7fd2d2059
Labels:        app=prometheus
               prometheus=prometheus-prometheus-oper-prometheus
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      50Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    prometheus-prometheus-prometheus-oper-prometheus-0
Events:        <none>
```

**Comment by Mauraza** [comment]
I haven't been able to reproduce the problem, so maybe it has to do with `--objstore.config={type: GCS, config: {bucket: prometheus-bucket-name}}` which is what we have different. Could you check that everything is correct?

**Comment by ni-ajardan** [comment]
@Mauraza Sure, I will try today and come back with details. Thank you !

**Comment by ni-ajardan** [comment]
I reconfigured it with the recommended objectStorageConfig, but the problem still persists:

```
- args:
        - sidecar
        - --prometheus.url=http://localhost:9090
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --objstore.config=$(OBJSTORE_CONFIG)
        env:
        - name: OBJSTORE_CONFIG
          valueFrom:
            secretKeyRef:
              key: thanos.yaml
              name: thanos-objstore-config
        image: docker.io/bitnami/thanos:0.11.0-scratch-r9
        imagePullPolicy: IfNotPresent
        name: thanos-sidecar
        ports:
        - containerPort: 10901
          name: grpc
          protocol: TCP
        - containerPort: 10902
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      serviceAccount: prometheus-prometheus-oper-prometheus
      serviceAccountName: prometheus-prometheus-oper-prometheus
      terminationGracePeriodSeconds: 600
      volumes:
      - name: config
        secret:
          defaultMode: 420
          secretName: prometheus-prometheus-prometheus-oper-prometheus
      - name: tls-assets
        secret:
          defaultMode: 420
          secretName: prometheus-prometheus-prometheus-oper-prometheus-tls-assets
      - emptyDir: {}
        name: config-out
      - configMap:
          defaultMode: 420
          name: prometheus-prometheus-prometheus-oper-prometheus-rulefiles-0
        name: prometheus-prometheus-prometheus-oper-prometheus-rulefiles-0
```

And logs:

```
level=warn ts=2020-04-09T09:39:30.451315652Z caller=sidecar.go:339 err="iter local block metas: read dir: open ./data: no such file or directory" uploaded=0
level=warn ts=2020-04-09T09:39:30.451405172Z caller=sidecar.go:344 msg="reading timestamps failed" err="read shipper meta file: open data/thanos.shipper.json: no such file or directory"
```
