### ISSUE TITLE
Postgres fails upgrade --dry-run but not regular upgrade when auth.existingSecret set and architecture is "replication"

### ISSUE THREAD

**Issue by dkinzer** [bitnami/charts#22554]
### Name and Version

bitnami/postgresql 13.3.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install the postgresql helm chart using the architecture set to "replication" and an existing secret. Try running an upgrade `--dry-run`.

I get the following error:
```
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'auth.replicationPassword' must not be empty, please add '--set auth.replicationPassword=$REPLICATION_PASSWORD' to the command. To get the current value:

        export REPLICATION_PASSWORD=$(kubectl get secret --namespace "padigital-qa" padigital-db -o jsonpath="{.data.replication-password}" | base64 -d)

helm.go:84: [debug] execution error at (padigital/charts/postgresql/templates/secrets.yaml:15:27): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'auth.replicationPassword' must not be empty, please add '--set auth.replicationPassword=$REPLICATION_PASSWORD' to the command. To get the current value:

        export REPLICATION_PASSWORD=$(kubectl get secret --namespace "padigital-qa" padigital-db -o jsonpath="{.data.replication-password}" | base64 -d)
```

### Are you using any custom parameters or values?

values.yaml config 

```yaml
postgresql:
  diagnosticMode:
    enabled: false
  architecture: replication
  auth:
    existingSecret: padigital-db
    database: padigital
    username: padigital
  fullnameOverride: padigital-db
  persistence:
    size: 1Gi
  primary:
    podAnnotations:
      backup.velero.io/backup-volumes: data
    containerSecurityContext:
      readOnlyRootFilesystem: true
    resources:
      limits:
        cpu: 400m
        memory: 512Mi
    extraVolumes:
      - name: tmp
        emptyDir: {}
      - name: conf
        emptyDir: {}
      - name: tmp2
        emptyDir: {}
    extraVolumeMounts:
      - name: tmp
        mountPath: /tmp
      - name: conf
        mountPath: /opt/bitnami/postgresql/conf
      - name: tmp2
        mountPath: /opt/bitnami/postgresql/tmp/
  image:
    pullPolicy: Always
    registry: harbor.k8s.temple.edu
    repository: utilities/bitnami-postgresql
    tag: 16.1.0-debian-11-r19 
  replication:
    applicationName: padigital    
  service:
    type: ClusterIP
    port: 5432
  readReplicas:
    replicaCount: 2
    resources:
      limits:
        cpu: 400m
        memory: 512Mi
    containerSecurityContext:
      readOnlyRootFilesystem: true
    extraVolumes:
      - name: tmp
        emptyDir: {}
      - name: conf
        emptyDir: {}
      - name: tmp2
        emptyDir: {}
    extraVolumeMounts:
      - name: tmp
        mountPath: /tmp
      - name: conf
        mountPath: /opt/bitnami/postgresql/conf
      - name: tmp2
        mountPath: /opt/bitnami/postgresql/tmp/
```

### What is the expected behavior?

I expect the dry-run to not fail.

### What do you see instead?

I see the following error:
```
upgrade.go:155: [debug] preparing upgrade for padigital
Error: UPGRADE FAILED: execution error at (padigital/charts/postgresql/templates/secrets.yaml:15:27): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'auth.replicationPassword' must not be empty, please add '--set auth.replicationPassword=$REPLICATION_PASSWORD' to the command. To get the current value:

        export REPLICATION_PASSWORD=$(kubectl get secret --namespace "padigital-qa" padigital-db -o jsonpath="{.data.replication-password}" | base64 -d)

helm.go:84: [debug] execution error at (padigital/charts/postgresql/templates/secrets.yaml:15:27): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'auth.replicationPassword' must not be empty, please add '--set auth.replicationPassword=$REPLICATION_PASSWORD' to the command. To get the current value:

        export REPLICATION_PASSWORD=$(kubectl get secret --namespace "padigital-qa" padigital-db -o jsonpath="{.data.replication-password}" | base64 -d)
```
