### ISSUE TITLE
Setting ingress.enabled to true in an umbrella chart with multiple Bitnami sub-charts fails

### ISSUE THREAD

**Issue by tglaeser** [bitnami/charts#22555]
### Name and Version

bitnami/kibana 10.6.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When using an umbrella chart with multiple Bitnami sub-charts I don't see a way to properly configure Ingress.

Particularly I'm configuring
```
kibana:
  ingress:
    enabled: true
    pathType: Prefix
    ingressClassName: nginx
```
in my umbrella chart.

This produces an ingress template of
```
# Source: elk/charts/kibana/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elk-kibana
  namespace: "elk-test"
  labels:
    app.kubernetes.io/instance: elk
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kibana
    app.kubernetes.io/version: 8.11.3
    helm.sh/chart: kibana-10.6.7
spec:
  ingressClassName: "nginx"
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: elk-kibana
                port:
                  name: http
      host: kibana.local
```

### Are you using any custom parameters or values?

I'm using an umbrella chart to describe the overall system, representing the EFK-Stack:
```
---
fluentd:
  aggregator:
    configMap: elk-fluentd-aggregator-cm
  forwarder:
    configMap: elk-fluentd-forwarder-cm
kibana:
  elasticsearch:
    hosts:
      - elk-elasticsearch.elk-test.svc.cluster.local
    port: 9200
  ingress:
    enabled: true
    pathType: Prefix
    ingressClassName: nginx
...
```

### What is the expected behavior?

Well, that's a good question. With an umbrella chart describing the EFK-Stack I find 4 services with named port `http`:
```
elk-fluentd-aggregator
elk-fluentd-forwarder
elk-fluentd-headless
elk-kibana
```
They are all in different pods, so there is no name conflict here.

The port that should be used with the Ingress template is the one from the last service which is defined in the umbrella chart values as `kibana.service.ports.http: 5601`

File `ingress.yaml` from the Kibana chart references the `backend.service.port` by name `http`; how could it possibly resolve to a port value of `5601`?

### What do you see instead?

The Ingress pod logs warning
```
W0122 22:42:09.053673       7 controller.go:1214] Service "elk-test/elk-kibana" does not have any active Endpoint.
```
and the Kibana front-end is not reachable.

**Comment by tglaeser** [comment]
BTW: I see the same behavior when trying to install `bitnami/kibana` alone with `ingress.enabled` set to `true` and `ingress.ingressClassName` equals `nginx`. I don't quite understand how `kibana/templates/ingress.yaml` could possibly work. In the past, when setting up NGINX Ingress controller, I would always define some spec like
```
spec:
  ingressClassName: "nginx"
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: elk-kibana
                port:
                  number: 5601
      host: kibana.local
```
, that is a `port.number` instead of a `port.name`. What am I missing?

**Comment by dgomezleon** [comment]
> BTW: I see the same behavior when trying to install `bitnami/kibana` alone with `ingress.enabled` set to `true` and `ingress.ingressClassName` equals `nginx`. I don't quite understand how `kibana/templates/ingress.yaml` could possibly work. In the past, when setting up NGINX Ingress controller, I would always define some spec like

Hi @tglaeser ,

I'm sorry for not getting back to you sooner.

Let's reduce the scope of this. If I understand correctly, you only set `ingress.enabled=true` and `ingress.ingressClassName=nginx` (apart from ES host and port that are mandatory). Is that correct? Could you let me know what error you are having with this scenario?

**Comment by tglaeser** [comment]
What I described in the the _What do you see instead?_ section above.

**Comment by dgomezleon** [comment]
Hi @tglaeser ,

I guess you should have an ingress like this: 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: kibana
    meta.helm.sh/release-namespace: test
  creationTimestamp: "2024-01-26T15:39:01Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: kibana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kibana
    app.kubernetes.io/version: 8.12.0
    helm.sh/chart: kibana-10.8.1
  name: kibana
  namespace: test
  resourceVersion: "5191"
  uid: a7f3400f-2cb3-4119-847e-f3b94d4d4d3a
spec:
  ingressClassName: nginx
  rules:
  - host: kibana.local
    http:
      paths:
      - backend:
          service:
            name: kibana
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: XX.XX.XX.XX
```

Note that service `kibana` names port 5601 as `http`, so you can reference it by name:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
...
  - name: http
    port: 5601
    protocol: TCP
    targetPort: http
  selector:
...
```

I hope it clarifies things.

**Comment by tglaeser** [comment]
And you are able to access the Kibana front-end at `http://xx.xx.xx.xx/`? I have the same configuration as you except that the `status` section is missing in my `kibana/templates/ingress.yaml`.

Here is what I did:
```
$ kubectl create namespace ingress-nginx
$ helm --namespace=ingress-nginx install nginx-ingress-controller oci://registry-1.docker.io/bitnamicharts/nginx-ingress-controller
$ kubectl create namespace test
$  helm --namespace test install kibana ./charts/kibana-10.6.7.tgz --values ./values.yaml
Error: INSTALLATION FAILED: 1 error occurred:
        * Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s": service "ingress-nginx-controller-admission" not found
```
with `values.yaml` containing
```
elasticsearch:
  hosts:
    - elasticsearch.test.svc.cluster.local
  port: 9200
ingress:
  enabled: true
  ingressClassName: nginx
```
I'm getting the above listed error but the pods seem to be running just fine:
```
$ kubectl --namespace test get pods
NAME                      READY   STATUS    RESTARTS   AGE
kibana-7d848d986f-bj4zb   1/1     Running   0          42s
$ kubectl --namespace ingress-nginx get pods
NAME                                                       READY   STATUS    RESTARTS   AGE
nginx-ingress-controller-default-backend-8855f6dd8-v9pbl   1/1     Running   0          7m9s
nginx-ingress-controller-75f7897d9d-4zwkm                  1/1     Running   0          7m9s
$ kubectl --namespace ingress-nginx get svc
NAME                                       TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                      AGE
nginx-ingress-controller-default-backend   ClusterIP      10.43.3.66      <none>          80/TCP                       8m24s
nginx-ingress-controller                   LoadBalancer   10.43.154.126   xx.xx.xx.xx     80:31428/TCP,443:31032/TCP   8m24s
$ kubectl --namespace test get svc
NAME     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
kibana   ClusterIP   10.43.106.117   <none>        5601/TCP   2m31s
```
Still, `curl -v http://xx.xx.xx.xx` returns
```
*   Trying xx.xx.xx.xx:80...
* Connected to xx.xx.xx.xx (xx.xx.xx.xx) port 80
> GET / HTTP/1.1
> Host: xx.xx.xx.xx
> User-Agent: curl/8.5.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Fri, 26 Jan 2024 17:04:14 GMT
< Content-Type: text/html
< Content-Length: 146
< Connection: keep-alive
<
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host xx.xx.xx.xx left intact
```

**Comment by tglaeser** [comment]
OK, so I ignored notes
```
1. Get the application URL by running these commands:
  Get the Kibana URL and associate Kibana hostname to your cluster external IP:

   export CLUSTER_IP=$(minikube ip) # On Minikube. Use: `kubectl cluster-info` on others K8s clusters
   echo "Kibana URL: http://kibana.local/"
   echo "$CLUSTER_IP  kibana.local" | sudo tee -a /etc/hosts
```
from the Kibana chart thinking I should be able to access the dashboard via the IP address forgetting that that's not how things work. After following those notes I was able to access the dashboard via `http://kibana.local/`.

**Comment by tglaeser** [comment]
Now back to what I originally tried to achieve, accessing several ports named `http` via NGINX ingress, I specified values
```
---
fluentd:
  aggregator:
    configMap: webm-log-fluentd-aggregator-cm
    ingress:
      enabled: true
      ingressClassName: nginx
  forwarder:
    configMap: webm-log-fluentd-forwarder-cm
kibana:
  elasticsearch:
    hosts:
      - webm-log-elasticsearch.webm-log-test.svc.cluster.local
    port: 9200
  ingress:
    enabled: true
    ingressClassName: nginx
...
```
and installed my EFK-Stack system and verified the ingress resources:
```
$ kubectl --namespace elk-test get ingress
NAME                          CLASS   HOSTS           ADDRESS         PORTS   AGE
elk-kibana               nginx   kibana.local      xx.xx.xx.xx   80      31m
elk-fluentd-aggregator   nginx   fluentd.local     xx.xx.xx.xx   80      31m
```
So things work as expected and I can access both endpoints via their hostname as long as I added lines
```
xx.xx.xx.xx  			kibana.local
xx.xx.xx.xx  			fluentd.local
```
to my `/etc/hosts`.

Bottom line, there is no naming conflict with the umbrella EFK-Stack. Warning `Service "elk-test/elk-kibana" does not have any active Endpoint` from the ingress controller logs have put me on the wrong track, sorry @dgomezleon for taking up some of your time, feel free to close the ticket with resolution set to "user error".
