### ISSUE TITLE
[bitnami/kube-prometheus] Prometheus Operator pod does cant mount service account token

### ISSUE THREAD

**Issue by lusu007** [bitnami/charts#22560]
### Name and Version

bitnami/kube-prometheus 8.25.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install the chart
2. Look into the pod logs

### Are you using any custom parameters or values?

```
kube-prometheus:
  alertmanager:
    enabled: false
  prometheus:
    replicaCount: 1
    retention: 1d
    retentionSize: 5GiB
    # Needs to be disabled for Thanos to work correctly. See: https://github.com/bitnami/charts/issues/15129
    disableCompaction: true
    persistence:
      enabled: true
      # TODO: Remove this annotation when the bitnami chart is fixed
      # see: https://github.com/bitnami/charts/pull/21881
      annotations:
        bugmitigation: I'm here to mitigate an issue in the bitnami annotation validation
      storageClass: redacted
      size: 5Gi
    thanos:
      create: true
      objectStorageConfig:
        secretName: thanos-object-storage-secret
```

### What do you see instead?

The pod does not start and throws the following error message:

```
level=info ts=2024-01-23T09:23:45.146901527Z caller=main.go:181 msg="Starting Prometheus Operator" version="(version=0.71.0, branch=, revision=unknown)"
level=info ts=2024-01-23T09:23:45.147042632Z caller=main.go:182 build_context="(go=go1.21.6, platform=linux/amd64, user=, date=20240112-12:10:45, tags=unknown)"
level=info ts=2024-01-23T09:23:45.147082979Z caller=main.go:193 msg="namespaces filtering configuration " config="{allow_list=\"\",deny_list=\"\",prometheus_allow_list=\"\",alertmanager_allow_list=\"\",alertmanagerconfig_allow_list=\"\",thanosruler_allow_list=\"\"}"
level=error ts=2024-01-23T09:23:45.147501889Z caller=main.go:203 msg="failed to create Kubernetes client configuration" err="open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory"
```
