### ISSUE TITLE
Cannot see airflow logs helm chart

### ISSUE THREAD

**Issue by kerolossalib** [bitnami/charts#22563]
### Name and Version

bitnamicharts/airflow 16.4.0

### What architecture are you using?

None

### What steps will reproduce the bug?

I've installed Airflow helm on AKS cluster, and DAGs logs find this error.
```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnamiairflow
spec:
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
spec:
  interval: 1m
  releaseName: airflow
  chart:
    spec:
      chart: airflow
      version: "16.2.0"
      sourceRef:
        kind: HelmRepository
        name: bitnamiairflow
  values:
    auth:
      username: user
      password: user
    replicaCount: 2
    web:
      baseUrl: "airflow.example.eu"
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: airflow.example.eu
      tls: true
      selfSigned: false
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
```

### Are you using any custom parameters or values?

yes
```yaml
auth:
      username: user
      password: user
    replicaCount: 2
    web:
      baseUrl: "airflow.example.eu"
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: airflow.example.eu
      tls: true
      selfSigned: false
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
```

### What is the expected behavior?

I'm expecting to see the logs of the DAG

### What do you see instead?

it shows `*** Could not read served logs: Request URL is missing an 'http://' or 'https://' protocol.`

<img width="1769" alt="image" src="https://github.com/bitnami/charts/assets/17772218/e94b449d-f25e-45c6-8707-544aa8b27bae">
