### ISSUE TITLE
[bitnami/kafka] The Kafka chart does not generate proper JAAS config 

### ISSUE THREAD

**Issue by Dwijad** [bitnami/charts#22696]
### Name and Version

bitnami/kafka 26.6.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?
Generated secret for SASL authentication:

`# k create secret generic kafka-client-secret --from-literal=client-passwords=password --from-literal=inter-broker-password=password --from-literal=inter-broker-client-secret=password --from-literal=controller-password=password --from-literal=controller-client-secret=password`

Configured SASL authentication using following config
```
...
...
sasl:
  enabledMechanisms: PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
  interBrokerMechanism: PLAIN
  controllerMechanism: PLAIN
  interbroker:
    user: broker
    
  controller:
    user: controller
    
  client:
    users: 
      - user1

  existingSecret: "kafka-client-secret"
...
...
```
### Are you using any custom parameters or values?

No

### What is the expected behavior?

I should see the following line in the kafka server properties file in the client SASL JAAS configuration section.
```
...
...
listener.name.client.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="user1" password="password";
...
...
```

### What do you see instead?

```
...
...
listener.name.client.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required user_user1="password";
...
...
```
