### ISSUE TITLE
[bitnami/elasticsearch] cannot read configured [PKCS12] keystore

### ISSUE THREAD

**Issue by tka4roman** [bitnami/charts#22702]
### Name and Version

bitnami/elasticsearch:19.13.14

### What architecture are you using?

None

### What steps will reproduce the bug?

Generated certificates as in this [article](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-basic-setup.html#encrypt-internode-communication).

### Are you using any custom parameters or values?

```
    security:
      enabled: true
      elasticPassword: ${ELASTIC_PASSWORD}
      tls:
        verificationMode: certificate
        passwordsSecret: <secret-with-passwords-for-certs>
        master:
          existingSecret: <secret-with-p12-file>
        data:
          existingSecret:  <secret-with-p12-file>
        coordinating:
          existingSecret:  <secret-with-p12-file>
        ingest:
          existingSecret: <secret-with-p12-file>
        keystoreFilename: elasticsearch-certificates.p12
        truststoreFilename: elasticsearch-certificates.p12
```

### What is the expected behavior?

Cluster with TLS/SSL

### What do you see instead?

![image](https://github.com/bitnami/charts/assets/22062755/f2418160-52a1-4587-a7b8-3e572f753831)

### Additional information

```
$ keytool -v -list -keystore elastic-certificates.p12 
Enter keystore password:  
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 2 entries

Alias name: ca
Creation date: Jan 24, 2024
Entry type: trustedCertEntry

Owner: CN=Elastic Certificate Tool Autogenerated CA
Issuer: CN=Elastic Certificate Tool Autogenerated CA
Serial number: db904e2a1e1ca7e166e9498b38fa9054d84c4b6
Valid from: Wed Jan 24 21:07:04 EET 2024 until: Sat Jan 21 21:07:04 EET 2034
Certificate fingerprints:
	 SHA1: 77:C4:69:F9:9E:19:EE:93:A1:30:67:3D:8C:4F:0C:9E:6B:40:B3:08
	 SHA256: B7:13:E2:3D:9B:78:1E:4C:9E:1D:2A:4A:04:3C:BE:96:E4:61:1C:32:1D:B1:66:27:A1:C7:9B:6E:8A:1E:61:A9
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions: 
...
*******************************************
*******************************************


Alias name: instance
Creation date: Jan 24, 2024
Entry type: PrivateKeyEntry
Certificate chain length: 2
Certificate[1]:
Owner: CN=instance
Issuer: CN=Elastic Certificate Tool Autogenerated CA
Serial number: 2d2b292f645ed97488b794eaa8b5bd48c96b5f9d
Valid from: Wed Jan 24 21:08:04 EET 2024 until: Sat Jan 23 21:08:04 EET 2027
Certificate fingerprints:
	 SHA1: C0:2F:7F:63:0F:5F:40:25:F6:27:16:CD:2A:CB:FA:E8:3C:49:DB:71
	 SHA256: 5A:1C:58:72:A1:16:15:E1:A6:9B:8F:FD:B3:21:2F:2A:B1:90:91:36:DE:E4:A6:92:9F:26:C0:10:BC:97:EC:0A
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions: 
...

```
