### ISSUE TITLE
[bitnami/postgresql-ha] Pods are always restarting , when Failover occurs

### ISSUE THREAD

**Issue by Sardonyxtechsupport** [bitnami/charts#22713]
### Name and Version

bitnami/postgresql-ha 12.2.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am using the bitnami PostgreSQL HA with Kubernetes as helm chart. I have the 3 master nodes and 2 worker nodes, the primary database is running on worker node1 and the secondary database is running on worker node2. If the worker node1 goes down, the secondary database has become as primary database. still that it is working fine. and then now failure node becomes active, the database data are fully removed, and then data syncing data from the primary database from the beginning. 
why did the data sync from the beginning?  In that stage, the only updated data only to be synced. 
what is the reason behind this?

 the pods are always restarting after the failed pc gets up when we have a high volume of data.
 the total data sync takes more time and then the readiness probe will fail, and then pods are always restarting.
How to fix this Issue?

**Hint:**   When we have exactly more than 10 lakhs records, this problem comes. 

**Deploy Postgres on Kubernetes **

1. `helm repo add bitnami https://charts.bitnami.com/bitnami`
2. `helm repo update`
3. `helm install postgresql-dev -f values.yaml bitnami/postgresql-ha`

### Are you using any custom parameters or values?

**Create a new configuration file (values.yaml)**
```yaml
postgresql:
  postgresPassword: admin@123
  password: admin@123
  database: kubeapp
  repmgrPassword: admin@123
  repmgrConnectTimeout: 2
  repmgrReconnectAttempts: 1
  repmgrReconnectInterval: 2
  repmgrChildNodesCheckInterval: 2
  repmgrChildNodesDisconnectTimeout: 5
  replicaCount: 3
  image:
    debug: true

service:
  type: NodePort

volumePermissions:
  enabled: true

pgpool:
  adminPassword: admin@123
  replicaCount: 2
  customUsers:
     usernames: postgres
     passwords: admin@123

persistence:
  storageClass: "nfs-client"
  size: 50Gi
```

### What is the expected behavior?

PostgreSQL Pods don't need restarts always. It needs to be working fine, When we have a large amount of data.

### What do you see instead?

PostgreSQL Pods restarts always When we have a large amount of data.

### Additional information

```console
$ kubectl get nodes
NAME      STATUS   ROLES              AGE   VERSION
master1   Ready      control-plane   22h   v1.28.6
master2   Ready      control-plane   22h   v1.28.6
master3   Ready      control-plane   22h   v1.28.6
worker1   Ready      worker         15h   v1.28.6
worker2   Ready      worker          22h   v1.28.6

$ kubectl get po -n postgres-dev -o wide
NAME                                                 READY   STATUS             RESTARTS         AGE    IP            NODE      NOMINATED NODE   READINESS GATES
postgres-dev-postgresql-ha-pgpool-5fb79d45d6-dg24b   1/1     Running            11 (5h55m ago)   47h    10.244.1.85   worker1   <none>           <none>
postgres-dev-postgresql-ha-pgpool-5fb79d45d6-t9nt8   1/1     Running            0                165m   10.244.1.88   worker2   <none>           <none>
postgres-dev-postgresql-ha-postgresql-0              1/1     Running            5 (30s ago)      10m    10.244.2.80   worker1   <none>           <none>
postgres-dev-postgresql-ha-postgresql-1              0/1     CrashLoopBackOff   94 (71s ago)     47h    10.244.1.83   worker2   <none>           <none>
```
