### ISSUE TITLE
[nginx] permit resources limits and requests on git-clone-repository initcontainer 

### ISSUE THREAD

**Issue by louisgls** [bitnami/charts#22726]
### Name and Version

bitnami/nginx 15.9.2

### What is the problem this feature will solve?

This chart does not permit to have resource limits and requests on initcontainers.

We have resource quotas that prevent the deployment of any containers that do not have resource specifications.

### What is the feature you are proposing to solve the problem?

Permit chart users to add resources on initContainers in templates/deployment.yaml:

```yaml
{{- if .Values.cloneStaticSiteFromGit.gitClone.resources }}
resources: {{- toYaml .Values.cloneStaticSiteFromGit.gitClone.resources | nindent 12 }}
{{- end }}
```

and in values.yaml

```yaml
  gitClone:
    ## @param cloneStaticSiteFromGit.gitClone.command Override default container command for git-clone-repository
    ##
    command: []
    ## @param cloneStaticSiteFromGit.gitClone.args Override default container args for git-clone-repository
    ##
    args: []
    resources:
      limits: {}
      requests: {}
```

### What alternatives have you considered?

Removing quota for the specific deployment but not ideal.
