### ISSUE TITLE
Custom config file pgpool.conf causes pgpool to overwrite conf.d directory

### ISSUE THREAD

**Issue by JudewinVJ** [bitnami/charts#2272]
**Which chart**:
postgresql-ha 2.2.0

**Describe the bug**
When I use pgpool.configuration in values.yaml to specify custom configuration for pgpool.conf, it overrides entire directory and causes pgpool service to fail. 

**To Reproduce**
gpool 16:33:07.16 INFO  ==> ** Starting Pgpool-II setup **
pgpool 16:33:07.18 INFO  ==> Validating settings in PGPOOL_* env vars...
pgpool 16:33:07.20 INFO  ==> Initializing Pgpool-II...
pgpool 16:33:07.20 INFO  ==> Custom configuration /opt/bitnami/pgpool/conf/pgpool.conf detected!
pgpool 16:33:07.21 INFO  ==> ** Pgpool-II setup finished! **

pgpool 16:33:07.24 INFO  ==> ** Starting Pgpool-II **
2020-04-08 16:33:07: pid 1: LOG:  could not open configuration file "/opt/bitnami/pgpool/conf/pool_hba.conf": No such file or directory
2020-04-08 16:33:07: pid 1: LOG:  Backend status file /opt/bitnami/pgpool/logs/pgpool_status does not exist

**Expected behavior**
it should only override pgpool.conf and rest should be intact. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by rafariossaa** [comment]
Hi @JudewinVJ ,
  Are you setting the directives in `postgresql.pgHbaConfiguration` or are you providing a file mounting it ?
  Could your provide an example of what you are doing ?
Thanks forehand

**Comment by judewin-alef** [comment]
Hi @rafariossaa 

I am providing a file named pgpool.conf, I also tried to set the directive pgpool.configuration like this 

## Pgpool configuration
    ## Specify content for pgpool.conf
    ## Alternatively, you can put your pgpool.conf under the files/ directory
    ## ref: https://github.com/bitnami/bitnami-docker-pgpool#configuration-file
    ##
    configuration: |
      failover_on_backend_error = 'on'

**Comment by rafariossaa** [comment]
Hi,
 I am creating an internal task to address this issue.
 We will come back as soon as we have news.

**Comment by rafariossaa** [comment]
You could also take a look to the generated pgpool.conf file, because there are other parameters that need to be set, as the backend nodes.

**Comment by abrahamgv** [comment]
I do some workaround with this problem.

I edit the `deployment.yaml` for the pgpool in this part, so the `pgpool.conf` is not mounted to the original directory. You can mount to any available directory, mine is `/home`

Before:
```
          volumeMounts:
            {{- if or (.Files.Glob "files/pgpool.conf") .Values.pgpool.configuration }}
            - name: pgpool-config
              mountPath: /opt/bitnami/pgpool/conf/
```

After:
```
          volumeMounts:
            {{- if or (.Files.Glob "files/pgpool.conf") .Values.pgpool.configuration }}
            - name: pgpool-config
              mountPath: /home/
```

And after that, i put init scripts in the helm chart for pgpool `pgpool-entrypoint-initdb.d` to copy the mounted `pgpool.conf` to the right directory.
```
#!/bin/bash

cp /home/pgpool.conf /opt/bitnami/pgpool/conf/pgpool.conf
```
And it worked.

But still, it is a messy workaround. Hope this issue is fixed soon.
