### ISSUE TITLE
[bitnami/supabase] kong containers don't log errors to stderr in supabase helm chart

### ISSUE THREAD

**Issue by a-schild** [bitnami/charts#22755]
### Name and Version

bitnamicharts/supabase 0.23.11

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Activate the keycloak SSO module in supbabase with the GOTRUE_EXTERNAL_KEYCLOAK_ENABLED: "true"
When the auth redirect from keycloak to supabase-api (kong) returns, then KONG modules logs errors to /opt/bitnami/kong/server/logs/error.log in the container
But there errors are never seen outside of the container/pod

### Are you using any custom parameters or values?
```
kong:
  ## @param kong.enabled Enable Kong
  ##
  enabled: true
  ## @param kong.database Database to use
  # We will use declarative configuration so we don't need the database
  database: "off"

    GOTRUE_EXTERNAL_KEYCLOAK_ENABLED: "true"
    GOTRUE_EXTERNAL_KEYCLOAK_CLIENT_ID: "Supabase"
    GOTRUE_EXTERNAL_KEYCLOAK_SECRET: "xxxxxxxxxxx"
    GOTRUE_EXTERNAL_KEYCLOAK_REDIRECT_URI: "https://supabase-api.staging.xxxxxxxxx.com/auth/v1/callback"
    GOTRUE_EXTERNAL_KEYCLOAK_URL: "https://sso.xxxxx.com/auth/realms/XXXX"
```

### What is the expected behavior?

Having the errors visible outside of the pod in stderrr or similar
```
2024/01/26 15:12:13 [error] 89#0: *300 upstream sent too big header while reading response header from upstream, client: 10.1.5.33, server: kong, request: "GET /auth/v1/callback?state=eyxxxxxxxxxxxxxxxxxf7ad4b HTTP/1.1", upstream: "http://10.2.5.126:80/callback?state=eyJhxxxxxxxxxxxxxxd4b", host: "supabase-api.staging.xxxxxx.com"
```
### What do you see instead?

In the /opt/bitnami/kong/server/logs/error.log
```
2024/01/26 15:12:13 [error] 89#0: *300 upstream sent too big header while reading response header from upstream, client: 10.1.5.33, server: kong, request: "GET /auth/v1/callback?state=eyxxxxxxxxxxxxxxxxxf7ad4b HTTP/1.1", upstream: "http://10.2.5.126:80/callback?state=eyJhxxxxxxxxxxxxxxd4b", host: "supabase-api.staging.xxxxxx.com"
```
