### ISSUE TITLE
[bitnami/redis-cluster] chart ver 9.4.0 is broken with metrics.enabled=true

### ISSUE THREAD

**Issue by solarvm** [bitnami/charts#22784]
### Name and Version

bitnami/redis-cluster 9.4.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

run install of the redis cluster with metrics enabled. 
Helm fails with:
```
Error: INSTALLATION FAILED: template: redis-cluster/templates/redis-statefulset.yaml:345:44: executing "redis-cluster/templates/redis-statefulset.yaml" at <.Values.metrics.contanierPorts.http>: nil pointer evaluating interface {}.http
```

### Are you using any custom parameters or values?
```yaml
# Values for PROD Redis cluster
usePassword: false
persistence:
  enabled: true
  size: 32G
cluster:
  init: true
  nodes: 15
  replicas: 0
podDisruptionBudget:
  minAvailable: 2
redis:
  configmap: |-
    maxmemory 16000mb
    maxmemory-policy allkeys-lru
    maxclients 50000
    cluster-require-full-coverage no
    cluster-allow-reads-when-down yes

sysctlImage:
  enabled: true
  mountHostSys: true
  command:
    - /bin/sh
    - -c
    - |-
      insta
      sysctl -w net.core.somaxconn=10000
      echo never > /host-sys/kernel/mm/transparent_hugepage/enabled

metrics:
  enabled: true
```
### What is the expected behavior?

I'd expect it to get installed

### What do you see instead?

error msg: 
```
Error: INSTALLATION FAILED: template: redis-cluster/templates/redis-statefulset.yaml:345:44: executing "redis-cluster/templates/redis-statefulset.yaml" at <.Values.metrics.contanierPorts.http>: nil pointer evaluating interface {}.http
```

### Additional information

There is an obvious typo at https://github.com/bitnami/charts/blob/3dc3ee1e71a4e62545bf5a1b679320f6478afbc6/bitnami/redis-cluster/templates/redis-statefulset.yaml#L345

cont**anier**Ports <- should be containerPorts. 
However fixing it is not enough (it installs, but then the metric container crash loops with `unknown port tcp/9121` in the log
