### ISSUE TITLE
Unable to use Ingress TLS with an empty Secret name (use case: ingress controller provides a default certificate for all connections)

### ISSUE THREAD

**Issue by juliohm1978** [bitnami/charts#22810]
### Name and Version

bitnami/phpmyadmin:14.2.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Current chart template is unable to render the Ingress object without a TLS secret:

```
helm install --dry-run myrelease oci://registry-1.docker.io/bitnamicharts/phpmyadmin --version 14.2.1 --set ingress.enabled=true --se
t ingress.tls=true > output.yaml
```

Inspecting `output.yaml`, the Ingress will be:

```yaml
# Source: phpmyadmin/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myrelease-phpmyadmin
  namespace: "default"
  labels:
    app.kubernetes.io/instance: myrelease
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: phpmyadmin
    app.kubernetes.io/version: 5.2.1
    helm.sh/chart: phpmyadmin-14.2.1
spec:
  rules:
    - host: phpmyadmin.local
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: myrelease-phpmyadmin
                port:
                  name: http
  tls:
    - hosts:
        - phpmyadmin.local
      secretName: phpmyadmin.local-tls
```

The value for `tls[].secretName` defaults to `phpmyadmin.local-tls`.

### What is the expected behavior?

Under particular scenarios, I expect the chart to be table to render an Ingress with a `tls` array as follows:

```yaml
  tls:
    - hosts:
        - phpmyadmin.local
```

The use case for this might not be very common, but very possible. Ingress Nginx controller, for example, allows for a [default SSL certificate](https://kubernetes.github.io/ingress-nginx/user-guide/tls/#default-ssl-certificate) which can be served for all Ingresses that do not define a TLS secret.

The only workaround I found is to deploy a release with `ingress.enabled=false` and kubectl apply my own custom Ingress without a TLS secret defined.

**Comment by juliohm1978** [comment]
Follow up: another workaround is to use `ingress.extraTls` to define your own TLS list.

```yaml
ingress:
      tls: false
      extraTls:
      - hosts:
        - my.domain.com
```

That's as intuitive, since we need to use `ingress.tls: false` while defining a custom `extraTls` list. Perhaps a simple note in the README for this chart can instruct chart users on that.
