### ISSUE TITLE
[bitnami/etcd] can't enable authentication automatically when authentication with TLS is enabled

### ISSUE THREAD

**Issue by bitnik** [bitnami/charts#22824]
### Name and Version

bitnami/etcd 9.10.3

### What architecture are you using?

arm64

### What steps will reproduce the bug?

We are trying to deploy an etcd cluster with RBAC, token and TLS authentication enabled. TLS auth is enabled both for server-to-server and client-to-server communications.

When we deploy it with the following configuration and certificates, all pods get into Running state, but the `etcd-0` stuck in "Enabling etcd authentication" part and we see "tls: first record does not look like a TLS handshake" logs in `etcd-1` and `etcd-2` pods (requests coming from `etcd-0`). It looks like etcd-0 doesn't use TLS while connecting to other etcd pods, but we don't understand what is configured wrongly.

### Are you using any custom parameters or values?

Values:

```yaml
initialClusterState: "new"
replicaCount: 3

auth:
  rbac:
    enabled: true
    create: true
    allowNoneAuthentication: false
    rootPassword: "secret"
  token:
    enabled: true
    type: jwt
  peer:
    secureTransport: true
    useAutoTLS: false
    existingSecret: etcd-peer-tls
    enableAuthentication: true
    certFilename: tls.crt
    certKeyFilename: tls.key
    caFilename: ca.crt
  client:
    secureTransport: true
    useAutoTLS: false
    existingSecret: etcd-client-tls
    enableAuthentication: true
    certFilename: tls.crt
    certKeyFilename: tls.key
    caFilename: ca.crt
```

Certificate manifests:

```yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-client
spec:
  secretName: etcd-client-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: <name>
  usages:
  - server auth
  - client auth
  dnsNames:
  - '*.etcd.etcd.svc.cluster.local'
  - '*.etcd-headless.etcd.svc.cluster.local'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-peer
spec:
  secretName: etcd-peer-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: <name>
  usages:
  - server auth
  - client auth
  dnsNames:
  - '*.etcd.etcd.svc.cluster.local'
  - '*.etcd-headless.etcd.svc.cluster.local'
```

### What is the expected behavior?

The authentication is enabled and the root user is created.

### What do you see instead?

 `etcd-0` logs:

```
etcd 10:11:30.14 INFO  ==> 
etcd 10:11:30.14 INFO  ==> Welcome to the Bitnami etcd container
etcd 10:11:30.14 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
etcd 10:11:30.14 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
etcd 10:11:30.15 INFO  ==> 
etcd 10:11:30.15 INFO  ==> ** Starting etcd setup **
etcd 10:11:30.16 INFO  ==> Validating settings in ETCD_* env vars..
etcd 10:11:30.17 INFO  ==> Initializing etcd
etcd 10:11:30.17 INFO  ==> Generating etcd config file using env variables
etcd 10:11:30.18 INFO  ==> There is no data from previous deployments
etcd 10:11:30.18 INFO  ==> Bootstrapping a new cluster
etcd 10:12:05.23 INFO  ==> Obtaining cluster member ID
etcd 10:12:05.23 INFO  ==> Starting etcd in background
{"level":"warn","ts":"2024-01-29T10:12:08.307548Z","logger":"etcd-client","caller":"v3@v3.5.11/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004001c0/etcd-0.etcd-headless.sensu-dev.svc.cluster.local:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: authentication is not enabled"}
etcd 10:12:08.32 INFO  ==> Stored member ID: 5d0485e7a4a7b0e6
etcd 10:12:08.32 INFO  ==> Stopping etcd
Terminated
etcd 10:12:10.33 INFO  ==> Starting etcd in background
{"level":"warn","ts":"2024-01-29T10:12:13.431613Z","logger":"etcd-client","caller":"v3@v3.5.11/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0003c0380/etcd-0.etcd-headless.sensu-dev.svc.cluster.local:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: authentication is not enabled"}
etcd 10:12:13.43 INFO  ==> Enabling etcd authentication

```

`etcd-1/2` logs:

```
...
{"level":"warn","ts":"2024-01-29T10:12:19.259767Z","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"<etcd-0-pod-ip>:37220","server-name":"","error":"tls: first record does not look like a TLS handshake"}
{"level":"warn","ts":"2024-01-29T10:12:22.715213Z","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"<etcd-0-pod-ip>:37234","server-name":"","error":"tls: first record does not look like a TLS handshake"}
{"level":"warn","ts":"2024-01-29T10:12:29.335173Z","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"<etcd-0-pod-ip>:35644","server-name":"","error":"tls: first record does not look like a TLS handshake"}
{"level":"warn","ts":"2024-01-29T10:12:40.840435Z","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"<etcd-0-pod-ip>:40414","server-name":"","error":"tls: first record does not look like a TLS handshake"}
{"level":"warn","ts":"2024-01-29T10:12:59.942145Z","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"<etcd-0-pod-ip>:58514","server-name":"","error":"tls: first record does not look like a TLS handshake"}
{"level":"warn","ts":"2024-01-29T10:13:26.163582Z","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"<etcd-0-pod-ip>:57972","server-name":"","error":"tls: first record does not look like a TLS handshake"}
{"level":"warn","ts":"2024-01-29T10:14:13.277526Z","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"<etcd-0-pod-ip>:48492","server-name":"","error":"tls: first record does not look like a TLS handshake"}
{"level":"warn","ts":"2024-01-29T10:15:33.008714Z","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"<etcd-0-pod-ip>:34372","server-name":"","error":"tls: first record does not look like a TLS handshake"}
{"level":"warn","ts":"2024-01-29T10:17:21.199029Z","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"<etcd-0-pod-ip>:43468","server-name":"","error":"tls: first record does not look like a TLS handshake"}
{"level":"warn","ts":"2024-01-29T10:19:36.978455Z","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"<etcd-0-pod-ip>:38170","server-name":"","error":"tls: first record does not look like a TLS handshake"}
{"level":"warn","ts":"2024-01-29T10:21:46.338497Z","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"<etcd-0-pod-ip>:46650","server-name":"","error":"tls: first record does not look like a TLS handshake"}
{"level":"warn","ts":"2024-01-29T10:24:08.066138Z","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"<etcd-0-pod-ip>:57676","server-name":"","error":"tls: first record does not look like a TLS handshake"}
```

When we connect to one of the pods and check the health with etcdctl, it says that endpoints are healthy. We also see that auth is not enabled and root user is not created as the logs indicate.

### Additional information

If we enable the auth and create the root user manually, and  then restart the pods, everything seems to be okay.

**Comment by rafariossaa** [comment]
Hi,
  Have you tried it doing it by steps ? 
  I mean, for example using TLS, using RBAC, and then using TLS + RBAC .

**Comment by brickpattern** [comment]
I faced the exact same issue  but in my case it was just 1  replica count. ( copying only the first page of helm chart values). 



```
affinity: {}
args: []
auth:
  client:
    caFilename: ""
    certFilename: cert.pem
    certKeyFilename: key.pem
    enableAuthentication: false
    existingSecret: ""
    secureTransport: false
    useAutoTLS: false
  peer:
    caFilename: ""
    certFilename: cert.pem
    certKeyFilename: key.pem
    enableAuthentication: false
    existingSecret: ""
    secureTransport: false
    useAutoTLS: false
  rbac:
    allowNoneAuthentication: true
    create: true
    existingSecret: ""
    existingSecretPasswordKey: ""
    rootPassword: ""
  token:
    enabled: true
    privateKey:
      existingSecret: ""
      filename: jwt-token.pem
    signMethod: RS256
    ttl: 10m
    type: jwt
autoCompactionMode: ""
autoCompactionRetention: ""
automountServiceAccountToken: false
clusterDomain: cluster.local
command: []
```

when the etcd-0 pod started it failed as 


```
etcd 17:32:47.98 INFO  ==> Starting etcd in background
{"level":"warn","ts":"2024-02-09T17:33:28.693691Z","logger":"etcd-client","caller":"v3@v3.5.12/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000ba700/etcd-0.etcd-headless.etcd.svc.cluster.local:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: authentication is not enabled"}
etcd 17:33:28.69 INFO  ==> Enabling etcd authentication
{"level":"warn","ts":"2024-02-09T17:33:28.816342Z","logger":"etcd-client","caller":"v3@v3.5.12/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00032c1c0/etcd-0.etcd-headless.etcd.svc.cluster.local:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: user name already exists"}
Error: etcdserver: user name already exists
etcd 17:33:28.82 INFO  ==> Stopping etcd
```

my only inference was  it started with Persistent Volume PV where the PVC already was bound to previously running  etcd chart  ( inspite of complete helm uninstall of the bitnami/etcd) .  After deleting the PVC manually, and reinstalling the chart the POD came up successful.  So my inference, this failure could possible be related to previous existing data on the PVs on the same cluster+namespace. 

let me know otherwise.
