### ISSUE TITLE
[bitnami/mongodb] seccomp error on OpenShift

### ISSUE THREAD

**Issue by romanziske** [bitnami/charts#22872]
### Name and Version

bitnami/mongodb

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I try to start MongoDB with following values:
```yaml
auth:
  enabled: true
  rootUser: *****
  rootPassword: *****
  usernames:
    - *****
  passwords:
    - *****
  databases:
    - *****

architecture: replicaset
replicaCount: 3
replicaSetName: rs01

podSecurityContext:
  enabled: false

containerSecurityContext:
  enabled: false

shmVolume:
  chmod:
    enabled: false

volumePermissions:
  securityContext:
    runAsUser: "auto"

arbiter:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
```

### What is the expected behavior?

The expected behavior is a running MongoDB replicaset.

### What do you see instead?

error msg="runc create failed: unable to start container process: unable to init seccomp: error loading seccomp filter into kernel: error loading seccomp filter: errno 524"
