### ISSUE TITLE
bitnami/mediawiki Error executing 'postInstallation': EPERM: operation not permitted, chown '/bitnami/mediawiki'

### ISSUE THREAD

**Issue by phinaliumz** [bitnami/charts#2288]
**Which chart**:
mediawiki, 9.1.12

**Describe the bug**
If I have set persistence to enabled when running the helm chart, I get an error "Error executing 'postInstallation': EPERM: operation not permitted, chown '/bitnami/mediawiki'" on installation. This happens after few minutes, after MySQL database has been found.

I'm using NFS as persistent volume provider. 

**To Reproduce**
1. Use NFS as volume provider, see chart https://hub.helm.sh/charts/stable/nfs-client-provisioner
2. Run mediawiki helm chart, helm install mediawiki -f .\values.yaml --namespace mediawiki-ns bitnami/mediawiki
3. Wait until logs show MySQL server listening and working at :3306
4. You should see the error in the title

values.yaml is as follows
```
mediawikiUser: admin
mediawikiName: <name>
mediawikiHost: <host>
mediawikiEmail: <email>
mariadb:
  enabled: false
service:
  type: NodePort
persistence:
  enabled: true
  accessMode: ReadWriteOnce
livenessProbe:
  initialDelaySeconds: 3600
readinessProbe:
  initialDelaySeconds: 3600
externalDatabase:
  host: <host>
  password: <password>
```
Database is also running in the cluster, as a separate pod. 

**Expected behavior**
I excepted that running the helm chart would offer a working Mediawiki instances

**Version of Helm and Kubernetes**:
Helm 3.1.2
Kubernetes 1.17

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compi
ler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compi
ler:"gc", Platform:"linux/amd64"}
```

**Additional context**

Persistent volume is created succesfully
```
Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"mediawiki-ns", Name:"mediawiki-me
diawiki", UID:"c0075485-add4-43cf-a6c2-638ec0d6c382", APIVersion:"v1", ResourceVersion:"1417638", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume pvc-c0075485-add4-
43cf-a6c2-638ec0d6c382
```
If I run the chart with persistence false, the installation runs through.

I'm still starting to learn with Kubernetes. This cluster is my home lab. I'm creating this issue in hope of getting advices how to debug this.
