### ISSUE TITLE
[bitnami/external-dns] extraArgs array index bug Istio

### ISSUE THREAD

**Issue by tomas-stary-work** [bitnami/charts#22913]
### Name and Version

bitnami/external-dns 6.31.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Using extraArgs in the values field in the helm chart

### Are you using any custom parameters or values?

```
extraArgs:
  source: istio-gateway
  source: istio-virtualservice
```

### What is the expected behavior?

It cannot be done this way because the key is not unique, but the key does not have to be unique in the arguments, so it cannot be solved using a map, but an array must be used.
```
extraArgs:
  - --source=istio-gateway
  - --source=istio-virtualservice
```

### What do you see instead?

Only the last item of the map is added to the arguments, because the key is not unique, so the first item is not added and only the last item from the map is in the resulting manifest.
```
args:
            ......
             # Extra arguments
            - --sourcea=istio-virtualservice

```
### Additional information

It cannot be done this way because the key is not unique, but the key does not have to be unique in the arguments, so it cannot be solved using a map, but an array must be used.

The whole problem is in the dep-ds.yaml template
```
  # Extra arguments
               {{- if $value }}
             - --{{ $key }}={{ $value }}
               {{- else }}
             - --{{ $key }}
               {{- end }}
```

**Comment by jotamartos** [comment]
As you can see [here](https://github.com/bitnami/charts/blob/main/bitnami/external-dns/templates/dep-ds.yaml#L179), you can define the sources to use using the sources parameter. If you add your 2 sources there, the container is run with the expected arguments 

```
      containers:
        - name: external-dns
          image: docker.io/bitnami/external-dns:0.14.0-debian-11-r8
          imagePullPolicy: "IfNotPresent"
          args:
            # Generic arguments
            - --metrics-address=:7979
            - --log-level=info
            - --log-format=text
            - --policy=upsert-only
            - --provider=aws
            - --registry=txt
            - --interval=1m
            - --source=istio-gateway
            - --source=istio-virtualservice
            # AWS arguments
            - --aws-api-retries=3
            - --aws-zone-type=
            - --aws-batch-change-size=1000
```
