### ISSUE TITLE
[bitnami/redis] REDIS_EXPORTER_WEB_LISTEN_ADDRESS incorrectly set causing metrics pod to crashloop

### ISSUE THREAD

**Issue by mars64** [bitnami/charts#22922]
### Name and Version

bitnami/redis 18.11.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. depoly redis-master via `HEAD`, enable `metrics`, but don't change any readinessProbe related values
2. observe `metrics` fails to perform readiness probe

### Are you using any custom parameters or values?

I am, but I believe the default values (with `metrics.enabled = true`) will also trigger this condition. Here are the relevant values that I am setting: 
```yaml
auth:
  enabled: true
  password: "superUltraMegaSecret"
master:
  resources:
    limits:
      cpu: 4000m
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 128Mi
metrics:
  enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi
namespace: monitoring
networkPolicy:
  enabled: false
prometheusRule:
  enabled: true
  # https://github.com/bitnami/charts/blob/dfbf28240eca7b8732d83d07f10d7a3ca0788e3a/bitnami/redis/values.yaml
  rules: []
replica:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPU: "75"
  resources:
    limits:
      cpu: 1500m
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 128Mi
serviceMonitor:
  enabled: true
```

### What is the expected behavior?

The `metrics` pod should not crash.

### What do you see instead?

The `metrics` pod crashes, rendering the `master` unavailable.

### Additional information

I believe this change is the culprit: https://github.com/bitnami/charts/commit/f1c7b0d6c691bccf60c3294e1e607184ee462e1e#r138079079
