### ISSUE TITLE
Postgresql container stuck on ContainerCreating with no info in describe

### ISSUE THREAD

**Issue by 0x4d6165** [bitnami/charts#22925]
### Name and Version

bitnami/postgresql 13.2.29

### What architecture are you using?

None

### What steps will reproduce the bug?

I'm trying to run the Postgresql container as part of an iceshrimp installation and no matter what value options I try, the Postgresql deployment gets stuck in the container creating

### Are you using any custom parameters or values?
```yaml
  primary:
    persistence:
      size: 70Gi
      accessModes: [ "ReadWriteMany" ]
```
### What is the expected behavior?

The container creates and starts.

### What do you see instead?

The container gets stuck in the "creating" phase.
