### ISSUE TITLE
[bitnami/kafka] kafka_jaas.conf is not generated(chart version 26.6.2)

### ISSUE THREAD

**Issue by sdYoo** [bitnami/charts#22938]
### Name and Version

bitnami/kafka 26.6.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

kafka_jaas.conf file cannot be created in bitnami/kafka 26.6.2 version.
In chart version 23.0.0, the kafka_jaas.conf file was created through auth.sasl.jaas.clientUsers.
In chart version 26.6.2, kafka_jaas.conf is not created even if users are set to sasl.client.users in the same way.

### Are you using any custom parameters or values?
```
sasl:
  client:
    users:
      - admin1
      - admin2
      - admin3
    passwords:
      - test1
      - test2
      - test3
```
### What is the expected behavior?

The kafka_jaas.conf file is created under /opt/bitnami/kafka/config.

### What do you see instead?

The kafka_jaas.conf file is not generated under /opt/bitnami/kafka/config.

### Additional information

In the existing 23.0.0 version, the kafka_jaas.conf file is created.
