### ISSUE TITLE
MongoDB metrics auth authentication not working with prometheus scrape_config jobs

### ISSUE THREAD

**Issue by mayur2281** [bitnami/charts#22954]
### Name and Version

bitnami/mongodb

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```yaml
metrics:
  enabled: true
  compatibleMode: false
  username: user
  password: password
  serviceMonitor:
    enabled: true
  collector:
    all: true
```
  This is my metrics configuration
```yaml
  scrape_configs:
            - job_name: "mongodb-metrics"
              scrape_interval: 30s
              static_configs:
                - targets: ['mongodb.example.com:9216']
              tls_config:
                insecure_skip_verify: true
              basic_auth:
                username: user
                password: password
```             
Ans this is my prometheus scrape_config

### What is the expected behavior?

Expected prometheus to scrape metrics from the metrics container of mongodb

### What do you see instead?

Error:
```
time="2024-01-31T08:16:57Z" level=error msg="Cannot connect to MongoDB: cannot connect to MongoDB: connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism \"SCRAM-SHA-1\": (AuthenticationFailed) Authentication failed." 
```
This error occurs in the metrics container
