### ISSUE TITLE
[bitnami/spring-cloud-dataflow] unable to configure helm chart to use existing TLS certificate

### ISSUE THREAD

**Issue by moss2k13** [bitnami/charts#22973]
### Name and Version

bitnami/spring-cloud-dataflow 26.5.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. helm template below values:
```yaml
      ingress:
        annotations:
        enabled: true
        hostname: spring-cloud-data-flow.example.com
        tls: true
```

### Are you using any custom parameters or values?

nothing except above values:
`helm template dataflow -n dataflow bitnami/spring-cloud-dataflow --version 26.5.0 --values values.yaml > helmtemplate`

### What is the expected behavior?

helm chart does not generate secret resource `spring-cloud-data-flow.example.com-tls` 

### What do you see instead?

helm chart generates secret resource `spring-cloud-data-flow.example.com-tls`
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: spring-cloud-data-flow.example.com-tls
  namespace: "dataflow"
  labels:
    app.kubernetes.io/instance: dataflow
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: spring-cloud-dataflow
    app.kubernetes.io/version: 2.11.2
    helm.sh/chart: spring-cloud-dataflow-26.5.0
type: kubernetes.io/tls
data:
  tls.crt: {omitted}
  tls.key: {omitted}
  ca.crt: {omitted}
---
# Source: spring-cloud-dataflow/templates/server/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dataflow-spring-cloud-dataflow-server
  labels:
    app.kubernetes.io/instance: dataflow
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: spring-cloud-dataflow
    app.kubernetes.io/version: 2.11.2
    helm.sh/chart: spring-cloud-dataflow-26.5.0
    app.kubernetes.io/component: server
  namespace: "dataflow"
spec:
  rules:
    - host: spring-cloud-data-flow.example.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: dataflow-spring-cloud-dataflow-server
                port:
                  name: http
  tls:
    - hosts:
        - spring-cloud-data-flow.example.com
      secretName: spring-cloud-data-flow.example.com-tls
```

### Additional information

I have my own certificate already prepared in existing secret called `spring-cloud-data-flow.example.com-tls` but I can't configure the helm chart values to use it and not generate its own secret.

I'm trying to achieve this scenario described in the docs:
https://github.com/bitnami/charts/blob/main/bitnami/spring-cloud-dataflow/README.md?plain=1#L733

I'm preparing the related fix.
