### ISSUE TITLE
Kafka user is not created.

### ISSUE THREAD

**Issue by sdYoo** [bitnami/charts#22997]
### Name and Version

bitnami/kafka 26.6.2

### What architecture are you using?

None

### What steps will reproduce the bug?

Kafka user is not created.
In chart version 23.0.0, A kafka user was created with the settings as follows.
```yaml
auth:
  clientProtocol: sasl
  sasl:
    jaas:
      clientUsers:
        - test1
        - test2
        - test3
      clientPasswords:
        - password1
        - password2
        - password3
```
In chart version 26.6.2, Even if you set it as below, the kafka user is not created.
```yaml
sasl:
  client:
    users:
      - test1
      - test2
      - test3
    passwords:
      - password1
      - password2
      - password3
```     
How do I automatically create the kafka user entered in values.yaml?

### What is the expected behavior?

test1,test2,test3 uses are searched.
```yaml
sasl:
  client:
    users:
      - test1
      - test2
      - test3
    passwords:
      - password1
      - password2
      - password3
```
### What do you see instead?

Since the kafka user is not created, I must create kafka user manually.
