### ISSUE TITLE
[bitnami/schema-registry] externalKafka value is broken if networkPolicy is enabled

### ISSUE THREAD

**Issue by marsou77** [bitnami/charts#23015]
### Name and Version

bitnami/schema-registry:16.5.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Deploy Schema Registry with values as following:
```yaml
externalKafka:
  brokers:
    - PLAINTEXT://my-kafka-broker-1:9092
    - PLAINTEXT://my-kafka-broker-2:9092
    - PLAINTEXT://my-kafka-broker-3:9092
networkPolicy:
  enabled: true
```

### What is the expected behavior?

Deploy successful 

### What do you see instead?

```
Error: template: schema-registry/templates/networkpolicy.yaml:38:19: executing "schema-registry/templates/networkpolicy.yaml" at <include "schema-registry.kafka.port" .>: error calling include: template: schema-registry/templates/_helpers.tpl:116:35: executing "schema-registry.kafka.port" at <.Values.externalKafka.brokers>: wrong type for value; expected string; got []interface {}
  Use --debug flag to render out invalid YAML
```

### Additional information

To workaround this issue I passed my list of brokers as comma separated value.
