### ISSUE TITLE
[bitnami/clickhouse] Clickhouse Pod DNS Resolution Issue

### ISSUE THREAD

**Issue by nevotheless** [bitnami/charts#23017]
### Name and Version

bitnami/clickhouse 4.5.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

This is a pretty standard EKS Cluster

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: some-cluster
  region: eu-central-1

managedNodeGroups:
  - name: compute-group-1
    instanceType: c6a.2xlarge
    desiredCapacity: 2
    privateNetworking: true
    amiFamily: AmazonLinux2
    volumeSize: 100
    volumeType: gp3
    securityGroups:
      attachIDs:
        - sg-asdf12345
    availabilityZones:
      - eu-central-1a
      - eu-central-1b
      - eu-central-1c
    iam:
      withAddonPolicies:
        ebs: true
        efs: true
    tags:
      nodegroup-type: worker
      nodegroup-environment: testing

vpc:
  id: vpc-asdf1234
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
  securityGroup: sg-0asdf1234
  subnets:
    private:
      pone:
        id: subnet-asdfa
      ptwo:
        id: subnet-asdfb
      pthree:
        id: subnet-asdf

iam:
  withOIDC: true
  # The Service Account Setup creates the IAM Roles for the Service Accounts
  serviceAccounts:
    - metadata:
        name: efs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        efsCSIController: true
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        ebsCSIController: true

  - account: "someAccount" # AWS Account ID without additional Keys is needed here according to the eksctl docs

addons:
  - name: aws-efs-csi-driver
  - name: aws-ebs-csi-driver
 ```

Additionally `aws-loadbalancer-controller` and `ingress-nginx` are installed as well.

I deployed the bitnami clickhouse chart with the parameters below. Without much change but the clickhouse pods aren't able to resolve the hostnames.

### Are you using any custom parameters or values?

The values file didn't get touched much. 

 ```yaml
 auth:
    username: default
    password: ""
    existingSecret: "clickhouse-admin-creds"
    existingSecretKey: "password"
```

```yaml
ingress:
    enabled: true
    hostname: somehostname.our.company.intern
    ingressClassName: "nginx"
    tls: true
    extraTls: 
      - hosts:
          - somehostname.our.company.intern
        secretName: some-tls-secret
```

```yaml
storageClass: "some-gp3-storageClass"
```

### What is the expected behavior?

Clickhouse being able to resolve the hostnames of the shard pods.

### What do you see instead?

```
2024.01.29 14:11:42.900433 [ 78 ] {} <Warning> DNSResolver: Cannot resolve host (clickhouse-shard0-0.clickhouse-headless.apps.svc.cluster.local), error 0: Host not found.
2024.01.29 14:11:42.901533 [ 78 ] {} <Warning> DNSResolver: Cannot resolve host (clickhouse-shard0-2.clickhouse-headless.apps.svc.cluster.local), error 0: Host not found.
2024.01.29 14:11:42.902724 [ 78 ] {} <Warning> DNSResolver: Cannot resolve host (clickhouse-shard1-0.clickhouse-headless.apps.svc.cluster.local), error 0: Host not found.
2024.01.29 14:11:42.903902 [ 78 ] {} <Warning> DNSResolver: Cannot resolve host (clickhouse-shard1-2.clickhouse-headless.apps.svc.cluster.local), error 0: Host not found.
2024.01.29 14:11:42.903970 [ 78 ] {} <Information> DNSResolver: Cached hosts not found: clickhouse-shard0-0.clickhouse-headless.apps.svc.cluster.local, clickhouse-shard0-2.clickhouse-headless.apps.svc.cluster.local, clickhouse-shard1-0.clickhouse-headless.apps.svc.cluster.local, clickhouse-shard1-2.clickhouse-headless.apps.svc.cluster.local

```

### Additional information

Debugging this is quite hard, since i can't install anything into the containers but i tried the best i can.

Pods have the proper kubernetes dns entry in `/etc/resolv.conf`

```
I have no name!@clickhouse-shard0-0:/$ cat /etc/resolv.conf 
search apps.svc.cluster.local svc.cluster.local cluster.local eu-central-1.compute.internal
nameserver 10.100.0.10
options ndots:5
```

Other pods in the same namespace can resolve the headless service and the pods specifically just fine.

```
/ # dig +short clickhouse-headless.apps.svc.cluster.local
172.30.12.160
172.30.11.133
172.30.11.213
172.30.11.111
172.30.12.148
172.30.12.44
/ # dig +short clickhouse-shard0-2.clickhouse-headless.apps.svc.cluster.local
172.30.12.160
```

I suspect that the pod networking works as expected and the clickhouse pods themselves would resolve everything fine but that clickhouse maybe doing some internal dns resolving? Just assuming here, i have no clue.
