### ISSUE TITLE
[bitnami/matomo] Error after Upgrade to 5.0.1

### ISSUE THREAD

**Issue by tmechsner** [bitnami/charts#23014]
### Name and Version

bitnami/matomo 5.1.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We updated to matomo 5.0.1 from 4.16.0 with the most recent chart version.

### Are you using any custom parameters or values?

```yaml
namespaceOverride: xxx-tracking
global:
  storageClass: ssd
image:
  tag: 5.0.1-debian-11-r2
  pullSecrets:
    - ghcr

sidecars:
  - name: backup
    image: ghcr.io/sustago/matomo-backup:0.0.6
    imagePullSecrets:
      - name: ghcr
    volumeMounts:
      - mountPath: /bitnami/matomo
        name: matomo-data

matomoEmail: webadmin@sustago.de
matomoWebsiteName: xxx Tracking
matomoWebsiteHost: xxx.com

smtpHost: "smtp-relay.sendinblue.com"
smtpPort: "587"
smtpUser: "user@xxx.com"
smtpPassword: "xsmtpsib-asdf"

replicaCount: 1

priorityClassName: "prod-priority"

updateStrategy:
  type: Recreate

persistence:
  enabled: true
  existingClaim: matomo-matomo-new

volumePermissions:
  enabled: true

resources:
  requests:
    cpu: 800m
    memory: 1500Mi
  limits:
    cpu: 1500m
    memory: 2Gi

service:
  type: NodePort

readinessProbe:
  enabled: true
  path: /matomo.php

livenessProbe:
  enabled: true
  path: /matomo.php

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: false

mariadb:
  image:
    registry: docker.io
    repository: bitnami/mariadb
    tag: 10.6.12-debian-11-r16
    digest: ""
  
  diagnosticMode:
    enabled: false
  
  primary:
    resources:
      requests:
        cpu: 100m
        memory: 400Mi
      limits:
        cpu: 150m
        memory: 600Mi
    extraVolumes:
      - name: matomo-mariadb-backup
        persistentVolumeClaim:
          claimName: matomo-mariadb-backup
      - name: mariadb-secret
        secret:
          secretName: matomo-mariadb
    
    sidecars:
      # https://wolfgang.gassler.org/docker-image-mysql-mariadb-backups/
      # https://mariadb.com/kb/en/full-backup-and-restore-with-mariabackup/
      - name: backup
        image: woolfg/mysql-backup-sidecar:0.3-mariadb-10.5
        volumeMounts:
          - mountPath: /bitnami/mariadb
            name: data
          - mountPath: /backup
            name: matomo-mariadb-backup
          - mountPath: /secrets
            name: mariadb-secret
        env:
          - name: CRON_SCHEDULE
            value: "5 3 * * *"
          - name: INCREMENTAL
            value: "true"
          - name: COMPRESS_THREADS
            value: "0"
          - name: BACKUP_DIR
            value: /backup
          - name: DIR_DATE_PATTERN
            value: "%Y-%m-%d"
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD_FILE
            value: /secrets/mariadb-root-password
          - name: MYSQL_HOST
            value: matomo-mariadb
          
          # Full Backups every Sunday
          - name: FULL_BACKUP_DATE_FORMAT
            value: "%a"
          - name: FULL_BACKUP_DATE_RESULT
            value: "Sun"
          
          # Every backup directory that is older than 6 days: Keep only the full backups from Sundays
          - name: ROTATION1_DAYS
            value: "4"
          - name: ROTATION1_DATE_FORMAT
            value: "%a"
          - name: ROTATION1_DATE_RESULT
            value: "Sun"
          
          # Every backup directory that is older than 31 days: delete (condition not satisfyable)
          - name: ROTATION2_DAYS
            value: "31"
          - name: ROTATION2_DATE_FORMAT
            value: "%d"
          - name: ROTATION2_DATE_RESULT
            value: ">31"
          
          # Every backup directory that is older than 93 days: delete (condition not satisfyable)
          - name: ROTATION3_DAYS
            value: "93"
          - name: ROTATION3_DATE_FORMAT
            value: "%d"
          - name: ROTATION3_DATE_RESULT
            value: ">31"
  auth:
    username: "foo"
    password: "foo"
    replicationPassword: "foo"
    rootPassword: "foo"
  
  configuration: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    plugin_dir=/opt/bitnami/mariadb/plugin
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=512M
    bind-address=*
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    slow_query_log=0
    slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log
    long_query_time=10.0
    
    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mariadb/plugin
    
    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid



ingress:
  enabled: true
  ingressClassName: nginx
  hostname: xxx.com
  tls: true
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
```

### What is the expected behavior?

I expect the update to just work, as there was a bitnami chart and container release and no special update notes.

### What do you see instead?

After changing the image version, `matomo` pod and `matomo-scheduled-tasks` pod don't not start anymore due to `Multi-Attach error for volume` and the `matomo-archive` pod does not start with error `PHP Fatal error:  Cannot override final method Piwik\Plugin\ConsoleCommand::execute() in /bitnami/matomo/plugins/CoreConsole/Comman │
│ ds/GenerateAngularComponent.php on line 27` (same as mentioned here: https://forum.matomo.org/t/update-matomo-4-16-0-5-0-0-error/54668 and here https://github.com/bitnami/containers/issues/53962).
