### ISSUE TITLE
Mongodb backup cronjob doesn't respect global.imagePullSecrets or image.pullPolicy

### ISSUE THREAD

**Issue by kdward** [bitnami/charts#23021]
### Name and Version

bitnami/mongodb 14.8.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The backupCronJob job container is not respecting `global.imagePullSecrets` nor is it including the setting for `image.pullPolicy` which results in the default of `Always` and thus fails when attempting to pull the image from a private repository that requires auth.

`imagePullSecrets` issue:

`helm template my-release oci://registry-1.docker.io/bitnamicharts/mongodb --set backup.enabled=true --set global.imagePullSecrets={expectedSecret} -s templates/backup/cronjob.yaml | grep -B 1 expectedSecret`

Expect the template spec to have imagePullSecrets defined with the given array set in the global:

```
imagePullSecrets:
  - expectedSecret
```

Additionally the primary container for the job which launches the mongo image does not respect the `image.pullPolicy` setting.  It does not set an `imagePullPolicy` at all for the container which results in the kubernetes default of `Always`.

### Are you using any custom parameters or values?

`--set backup.enabled=true --set global.imagePullSecrets={expectedSecret}`

### What is the expected behavior?

backup cronjob respects `global.imagePullSecrets`
backup cronjob mongo container respects `image.imagePullPolicy`

expected snippet from from `helm template my-release oci://registry-1.docker.io/bitnamicharts/mongodb --set backup.enabled=true --set global.imagePullSecrets={expectedSecret} -s templates/backup/cronjob.yaml`

```
        spec:
          imagePullSecrets:
            - name: expectedSecret
          securityContext:
            fsGroup: 1001
            fsGroupChangePolicy: Always
            supplementalGroups: []
            sysctls: []
          enableServiceLinks: true
          containers:
          - name: my-release-mongodb-mongodump
            image: docker.io/bitnami/mongodb:7.0.5-debian-11-r5
            imagePullPolicy: "IfNotPresent"
```
### What do you see instead?

`imagePullPolicy` is not present, resulting in kubernetes defualt of `Always`
`imagePullSecrets` is not present
