### ISSUE TITLE
Helm upgrade failed: template: rabbitmq/templates/networkpolicy.yaml:47:64: executing "rabbitmq/templates/networkpolicy.yaml" at <.Values.rts.networkPolicy.extraEgress>: nil pointer evaluating interface {}.networkPolicy

### ISSUE THREAD

**Issue by tufberg** [bitnami/charts#23032]
### Name and Version

bitnami/rabbitmq 12.9.1

### What architecture are you using?

None

### What steps will reproduce the bug?

I've enabled networkpolicy and extraEgress in my HelmRelease using Flux

```yaml
    networkPolicy:
      enabled: true
      allowExternal: true
      extraIngress:
        - ports:
            - port: 1883
            - port: 8883
      extraEgress:
        - ports:
            - port: 6379
              protocol: TCP
            - port: 1883
              protocol: TCP
            - port: 8883
              protocol: TCP
          to:
            - podSelector:
                - matchLabels:
                    - app.kubernetes.io/instance: redis
```

Doing this I'll receive an error deploying this HelmRelease.
```
Helm upgrade failed: template: rabbitmq/templates/networkpolicy.yaml:47:64: executing "rabbitmq/templates/networkpolicy.yaml" at <.Values.rts.networkPolicy.extraEgress>: nil pointer evaluating interface {}.networkPolicy
```

### What is the expected behavior?

It should enable the egress Network policy.

### What do you see instead?

I checked the template code for **[networkPolicy](bitnami/rabbitmq/templates/networkpolicy.yaml)** and I see this line which seems wrong

`{{- include "common.tplvalues.render" ( dict "value" .Values.rts.networkPolicy.extraEgress "context" $ ) | nindent 4 }}`

Shouldn´t it be?

`{{- include "common.tplvalues.render" ( dict "value" .Values.networkPolicy.extraEgress "context" $ ) | nindent 4 }}`
