### ISSUE TITLE
[bitnami/nginx] Default value for https port networkPolicy is not conditional

### ISSUE THREAD

**Issue by olibenni** [bitnami/charts#23058]
### Name and Version

bitnami/nginx 15.10.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Default of `containerPorts.https` is an empty string but isn't conditionally added.
Kubernetes requires ports to be non empty string in order to render

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
spec:
  podSelector:
    matchLabels:
      app: some-app
  policyTypes:
    - Ingress
    - Egress
  egress:
    - ports:
        - port: ""
  ingress:
    - ports:
        - port: ""
```

Will fail on apply with error

### Are you using any custom parameters or values?

None

### What is the expected behavior?

Not requiring to override a value with a an arbitrary value for the network policy to work

### What do you see instead?

> NetworkPolicy.extensions "test-network-policy" is invalid: [spec.ingress[0].ports[0].port: Invalid value: "": must contain only alpha-numeric characters (a-z, 0-9), and hyphens (-), spec.ingress[0].ports[0].port: Invalid value: "": must contain at least one letter (a-z), spec.egress[0].ports[0].port: Invalid value: "": must contain only alpha-numeric characters (a-z, 0-9), and hyphens (-), spec.egress[0].ports[0].port: Invalid value: "": must contain at least one letter (a-z)] (retried 1 times).

See also
https://github.com/bitnami/charts/pull/22875/files#r1475095122
