### ISSUE TITLE
[bitnami/flink] How to add a custom flink-conf.yaml with Flink

### ISSUE THREAD

**Issue by spaily** [bitnami/charts#23090]
### Name and Version

bitnami/flink:1.18.1-debian-11-r1

### What is the problem this feature will solve?

To have a custom flink-conf.yaml file rather than fixed default one

### What is the feature you are proposing to solve the problem?

A configMap that can replace the default flink-conf.yaml file

### What alternatives have you considered?

Writing own Helm chart for deploying the Flink cluster

**Comment by javsalgar** [comment]
Hi,

You can use the `extraVolumes` and `extraVolumeMounts` section of the chart. There you can mount your own configmap with the file.

**Comment by daroga0002** [comment]
Also single parameters in config can be changes as below:

```sh
jobmanager:
  extraEnvVars: 
    - name: FLINK_PROPERTIES
      value: |
        jobmanager.memory.process.size: 4g
        jobmanager.memory.jvm-metaspace.size: 750m
        jobmanager.bind-host: 0.0.0.0
        jobmanager.retrieve-taskmanager-hostname: true
        rest.bind-address: 0.0.0.0
        rest.address: 0.0.0.0
		
taskmanager:
  extraEnvVars: 
    - name: FLINK_PROPERTIES
      value: |
        taskmanager.memory.process.size: 4g
        taskmanager.memory.jvm-metaspace.size: 750m
        rest.bind-address: 0.0.0.0
        rest.address: 0.0.0.0
```

**Comment by littlejiancc** [comment]
> Hi,
> 
> You can use the `extraVolumes` and `extraVolumeMounts` section of the chart. There you can mount your own configmap with the file.

@javsalgar Hi, I'm use `extraVolumes` and `extraVolumeMounts` to update config.yaml

```
extraVolumes:
  - name: flink-config
    configMap:
      name: flink-config
extraVolumeMounts:
  - name: flink-config
    mountPath: /opt/bitnami/flink/conf/config.yaml
    subPath: config.yaml
```
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: flink-config
data:
  config.yaml: |-
    jobmanager.rpc.address: flink-jobmanager
    taskmanager.numberOfTaskSlots: 8
    blob.server.port: 6124
    jobmanager.rpc.port: 6123
    taskmanager.rpc.port: 6122
    jobmanager.memory.process.size: 1600m
    taskmanager.memory.process.size: 1728m
    parallelism.default: 2
    classloader.resolve-order: parent-first
    env.java.opts: -Duser.timezone=Asia/Shanghai
```
And Startup Error

```
flink 10:26:48.23 INFO  ==> 

 flink 10:26:48.23 INFO  ==> Welcome to the Bitnami flink container

 flink 10:26:48.24 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers

 flink 10:26:48.24 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues

 flink 10:26:48.24 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise

 flink 10:26:48.24 INFO  ==> 

 flink 10:26:48.25 INFO  ==> ** Starting Apache Flink jobmanager setup **

 /opt/bitnami/scripts/libfile.sh: line 41: /opt/bitnami/flink/conf/config.yaml: Read-only file system
```
