### ISSUE TITLE
[bitnami/postgresql] Do not set postgre user password when you set global.postgresql.postgresqlUsername value

### ISSUE THREAD

**Issue by vsavostyanov** [bitnami/charts#2309]
**Which chart**:
bitnami/postgresql 
8.7.3

**Describe the bug**
When you set global.postgresql.postgresqlUsername value the template statefulset.yaml do not set POSTGRES_POSTGRES_PASSWORD variable

**To Reproduce**
Add values to values.yaml file

```yaml
global:
  postgresql:
    postgresqlDatabase: "my-databese"
    postgresqlUsername: "myusser"
    existingSecret: mysecret
```

**Expected behavior**
In pod describe:

```yaml
 - env:
    - name: BITNAMI_DEBUG
      value: "false"
    - name: POSTGRESQL_PORT_NUMBER
      value: "5432"
    - name: POSTGRESQL_VOLUME_DIR
      value: /bitnami/postgresql
    - name: PGDATA
      value: /bitnami/postgresql/data
    - name: POSTGRES_USER
      value: myusser
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgresql-password
          name: mysecret
    - name: POSTGRES_DB
      value: my-databese
    - name: POSTGRESQL_ENABLE_LDAP
      value: "no"
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
