### ISSUE TITLE
[bitnami/kafka] Issue with sasl.client.passwords

### ISSUE THREAD

**Issue by DavidS-B** [bitnami/charts#23180]
### Name and Version

bitnami/kafka 26.8.5

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I have this yaml config:

```
sasl:
  client:
      users:
          - "usr"
      passwords: "blah;blah"
```

### Are you using any custom parameters or values?

```
controller:
  replicaCount: 1

sasl:
  client:
      users:
          - "usr"
      passwords: "blah;blah"

provisioning:
  enabled: true
  topics:
    - name "topic"
      partitions: 2
      replicaPartition: 1
      config:
        retention.ms: 2000
```

### What is the expected behavior?

The documentation about sasl.client.passwords says: "Comma-separated list of passwords...".
So a password with semicolon should be valid.

### What do you see instead?

I have an error saying:
```
{:sasl_auth_error, "Authentification failed: Invalid username or password"}
```

### Additional information

Everything is working fine when the password doesn't contain any semicolon, but I need semicolon in my sasl client password.
