### ISSUE TITLE
[bitnami/moodle] existing secrets not working

### ISSUE THREAD

**Issue by DrummyFloyd** [bitnami/charts#23214]
### Name and Version

bitnami/moodle:20.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```
  podAnnotations: {}
  allowEmptyPassword: false
  # -- Skip Moodle™ installation wizard. Useful for migrations and restoring from SQL dump
  moodleSkipInstall: false
  moodleUsername: admin
  existingSecret: "moodle-secrets"
  ingress:
    enabled: false

  mariadb:
    enabled: false
  externalDatabase:
    user: usermoodle
    # password: uCUCeyc783ew6W3xQZmB873
    database: moodle
    type: mariadb
    port: 3306
    existingSecret: "moodle-secrets"

```
### Are you using any custom parameters or values?

all the existingSecret sequence won't work , because they include `common.names.fullname`
instead of something similar to this https://github.com/bitnami/charts/blob/67681dcb1608db89da63d6797547f0bbd98d467a/bitnami/wordpress/templates/deployment.yaml#L153

### What is the expected behavior?

can map correctly the existing secret upon declaration 

### What do you see instead?

instead i see `.Release.Name-moodle`
