### ISSUE TITLE
[bitnami/matomo] Missing custom certificate volumeMounts on CronJob

### ISSUE THREAD

**Issue by redzioch** [bitnami/charts#23211]
### Name and Version

bitnami/matomo 5.1.4

### What architecture are you using?

None

### What steps will reproduce the bug?

I tried to use custom certificates. Secret is correctly mount on application container, but not on `CronJob` ones.

Problem lies in missing `volumeMounts` in `CronJob` manifest.

Present [code](https://github.com/bitnami/charts/blob/90f6e7f3e6c341fd11cd04874be33e606e56fa48/bitnami/matomo/templates/cronjob.yaml#L86C1-L95C27):
```yaml
              volumeMounts:
                - name: matomo-data
                  mountPath: /bitnami/matomo
                {{- if .Values.customPostInitScripts }}
                - mountPath: /docker-entrypoint-init.d
                  name: custom-postinit
                {{- end }}
                {{- if .Values.extraVolumeMounts }}
                {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" $) | nindent 16 }}
                {{- end }}
```

Should be (just copied a sample from `Deployment` - needs to be reviewed):
```yaml
          volumeMounts:
            - name: matomo-data
              mountPath: /bitnami/matomo
            {{- if .Values.certificates.customCertificate.certificateSecret }}
            - name: custom-certificate
              mountPath: {{ .Values.certificates.customCertificate.certificateLocation }}
              subPath: tls.crt
              readOnly: true
            - name: custom-certificate
              mountPath: {{ .Values.certificates.customCertificate.keyLocation }}
              subPath: tls.key
              readOnly: true
            {{- if .Values.certificates.customCertificate.chainSecret }}
            - name: custom-certificate-chain
              mountPath: {{ .Values.certificates.customCertificate.chainLocation }}
              subPath: {{ .Values.certificates.customCertificate.chainSecret.key }}
              readOnly: true
            {{- end }}
            {{- end }}
            {{- if .Values.customPostInitScripts }}
            - mountPath: /docker-entrypoint-init.d
              name: custom-postinit
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
```

I will contribute fix when I have a moment.

### Are you using any custom parameters or values?

```yaml
certificates:
- customCertificate:
  - certificateLocation: /path/server.crt
    certificateSecret: secret-name
    chainSecret: false
    keyLocation: /path/server.key
```

### What is the expected behavior?

Attach volume with certificates to all Matomo containers.

### What do you see instead?

Missing `volumeMounts`.
