### ISSUE TITLE
[bitnami/wordpress] Adding initContainers cause parse error

### ISSUE THREAD

**Issue by v-six** [bitnami/charts#2325]
**Which chart**:
`bitnami/wordpress` `9.1.4`

**Describe the bug**
Adding an `initContainers:` in values is causing a yaml parse error : 
```yaml
...
sidecars: {}

## Add init containers to the pod.
## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
## Example:
## initContainers:
##  - name: your-image-name
##    image: your-image
##    imagePullPolicy: Always
##    command: ['sh', '-c', 'copy themes and plugins from git and push to /bitnami/wordpress/wp-conntent. Should work with extraVolumeMounts and extraVolumes']
##
initContainers:
  - name: init-htaccess
    image: busybox:1.28
    command: ['sh', '-c', 'echo true']
```

=> `Error: YAML parse error on wordpress/templates/deployment.yaml: error converting YAML to JSON: yaml: line 44: did not find expected key`

**To Reproduce**
1. Create a value file with `initContainers` (as shown above)
2. Install it `helm install bitnami/wordpress --name="test" -f values.yml`
3. Error : `Error: YAML parse error on wordpress/templates/deployment.yaml: error converting YAML to JSON: yaml: line 44: did not find expected key`

**Expected behavior**
No parse error.

**Version of Helm and Kubernetes**:
- `helm version`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}
```

- `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I think `initContainers:` key is missing here : https://github.com/bitnami/charts/blob/master/bitnami/wordpress/templates/deployment.yaml#L48
