### ISSUE TITLE
Add port 5432 / 6379 to networkPolicy when external db / redis is enabled

### ISSUE THREAD

**Issue by fzhan** [bitnami/charts#23301]
### Name and Version

bitnami/airflow-16.5.3

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Change `postgresql.enabled` to false, `externalDatabase` setup with correct service
2. Deploy but pod stuck at 'trying to connect to db'
3. DNS resolution gets through but Python test to db fails

### Are you using any custom parameters or values?
```yaml
postgresql:
  enabled: false

redis:
  enabled: false
```
### What is the expected behavior?

Network Policy should have been added 
```yaml
- ports:
    - protocol: TCP
      port: 5432
    - protocol: TCP
      port: 6379
```

### What do you see instead?

Only ports for 53 & 8080 were enabled
```yaml
- ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
- ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8080
```
