### ISSUE TITLE
[bitnami/mongodb] secret name conflict

### ISSUE THREAD

**Issue by m4dm4rtig4n** [bitnami/charts#23339]
### Name and Version

bitnami/mongodb:14.8.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hello,

When I try to deploy MongoDB with a secret file, I can't create a secret with "-" in the key.
But it's mandatory by the chart :

Helm release deploys by flux : 
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ${name}-mongodb
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: ${name}-mongodb
  timeout: 1m
  interval: 10m
  chart:
    spec:
      chart: mongodb
      version: 14.8.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-infra
      interval: 10m
  values:
    image:
      tag: 7.0.5 # {"$imagepolicy": "unifi:unifi-mongodb:tag"}
    auth:
      existingSecret: ${name}-mongodb
    podSecurityContext:
      enabled: false
    architecture: replicaset
```

My secret file: 
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: ${name}-mongodb
type: Opaque
stringData:
  mongodb-passwords: XXXXXXXXXXXXXXXXXXXXX
  mongodb-root-password: XXXXXXXXXXXXXXXXXXXXX
  mongodb-metrics-password: XXXXXXXXXXXXXXXXXXXXX
  mongodb-replica-set-key: XXXXXXXXXXXXXXXXXXXXX
```

Error when fluxcd try to deploy kustomize : 
```
var substitution failed for '${name}': YAMLToJSON: 'mongodb-root-password' var name is invalid, must match '^[_[:alpha:]][_[:alpha:][:digit:]]*$'
var substitution failed for '${name}': YAMLToJSON: 'mongodb-metrics-password' var name is invalid, must match '^[_[:alpha:]][_[:alpha:][:digit:]]*$
...
```

### What do you see instead?

Just want to deploy MongoDB with my secret :D

### Additional information

If I replace "-" by "_" in secret, deploy works, but MongoDB fails to start because need a key with "-" :/

**Comment by javsalgar** [comment]
Hi,

Do you find this problem when trying to deploy the chart with your secret only with helm? Initially, it seems more of an issue with flux, am I correct?

**Comment by m4dm4rtig4n** [comment]
I don't try without flux, i have remove bitnami chart and use bjw's template to deploy it :
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ${name}-mongodb
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: ${name}-mongodb
  timeout: 1m
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-infra
      interval: 1m
  values:
    #
    #    DEFAULT VALUE YAML
    #    https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
    #
    service:
      main:
        ports:
          http:
            port: 27017
            protocol: TCP
            targetPort: 27017
    ingress:
      main:
        enabled: false
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/arch: amd64        
    controllers:
      main:
        enabled: true
        type: statefulset
        replicas: 1
        strategy: RollingUpdate
        rollingUpdate:
          unavailable: 1
          surge: 1
        revisionHistoryLimit: 3
        containers:
          main:
            image:
              repository: mongo
              tag: 7.0.5 # {"$imagepolicy": "unifi:unifi-mongodb:tag"}
              pullPolicy: Always
            resources:
              limits:
                memory: 1024Mi
              requests:
                memory: 512Mi
            env:
              - name: MONGO_INITDB_ROOT_USERNAME
                valueFrom:
                secretKeyRef:
                  name: ${name}-mongodb
                  key: mongodb_root_username
              - name: MONGO_INITDB_ROOT_PASSWORD
                valueFrom:
                secretKeyRef:
                  name: ${name}-mongodb
                  key: mongodb_root_password
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /data/db
```
