### ISSUE TITLE
kubernetes-event-exporter PrometheusRule `KubernetesEventExporterTooManyWatchErrors` example always triggered

### ISSUE THREAD

**Issue by alexfouche** [bitnami/charts#23368]
### Name and Version

bitnami/kubernetes-event-exporter

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1) in Helm values, uncomment or use the PrometheusRule example provided to create the alert named `KubernetesEventExporterTooManyWatchErrors`
2) This alert is always triggered

### What is the expected behavior?

No alert if the PrometheusRule expression `sum(watch_errors{namespace="{{ include "common.names.namespace" . }}"})` equals 0

### What do you see instead?

i see the expression `sum(watch_errors{namespace="{{ include "common.names.namespace" . }}"})` equalling 0 ,
but a Prometheus alert is triggered anyway

### Additional information

From what i understood from [alerting_rules](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/), an alert is triggered as soon as the expression returns a vector. The current expression given as example in the `values.html` returns a vector with value 0

I suppose the expression should be 
```yaml
    groups:
      - name: EventExporter
        rules:
          - alert: KubernetesEventExporterTooManyWatchErrors
(...)
            expr: |
              sum(watch_errors{namespace="{{ include "common.names.namespace" . }}"}) >= 1
(...)
```

I will provide a merge request for it
