### ISSUE TITLE
Airflow git sync on running dag

### ISSUE THREAD

**Issue by marcocharlie** [bitnami/charts#23377]
### Name and Version

bitnami/airflow 16.5.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install helm chart on EKS cluster with default values.

### Are you using any custom parameters or values?

Customizing helm values only with:

```yaml
git:
  dags:
    enabled: true
    repositories:
      - repository: <https://USERNAME:PERSONAL_ACCESS_TOKEN@github.com/USERNAME/REPOSITORY>
        name: <REPOSITORY>
        branch: main
        path: "dags"

```
### What is the expected behavior?

By defining a dag of 2 tasks, if while the first task is running and before the second starts, the git sync updates the dag definition (due to a new commit on the target branch), the second task should run using the previous dag definition.

What we expect is that dag tasks should run entirely with the same definition. If git sync happens due to new commits, this should have effects on the next dag schedule and not on the running dag.

### What do you see instead?

The second dag task runs using the new dag definition.

### Additional information

In this situation, we can have a concurrency issue due to job tasks running on different definitions between dag tasks.
