### ISSUE TITLE
[bitnami/minio] Enabling provisioning for policies results in unexpected errors

### ISSUE THREAD

**Issue by Mo0rBy** [bitnami/charts#23378]
### Name and Version

minio 12.8.18

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. In the Helm chart values, enable `provisioning` > https://github.com/bitnami/charts/blob/main/bitnami/minio/values.yaml#L222
2. Add the following policy to the `policies` array > https://github.com/bitnami/charts/blob/main/bitnami/minio/values.yaml#L294
```yaml
        - name: admin-policy
          statements:
            - effect: Allow
              actions:
                - "admin:*"
                - "s3:*"
                - "kms:*"
              resources:
                - "arn:aws:s3:::*"
```
3. Install the helm chart and see the logs of the provisioning container
`mc: <ERROR> Unable to create new policy: unsupported admin action 's3:*'.`
OR
`mc: <ERROR> Unable to create new policy: unsupported admin action 'kms:*'.`
I think it depends on which one you have first within the array.

### Are you using any custom parameters or values?

There parameters are outlined above

### What is the expected behavior?

Expected behaviour is that the provisioning pod is able to successfully create the `admin-policy`

### What do you see instead?

Errors stating that `s3:*` or `kms:*` are not supported admin actions.

### Additional information

I have gone through the PBAC docs [here](https://min.io/docs/minio/linux/administration/identity-access-management/policy-based-access-control.html) and these clearly state an `s3:*` and `admin:*` as supported actions. I don't see `kms:*` so I'm guessing that is a mistake, but when I log in as the admin user and go to policies, the default `consoleAdmin` policy is:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "admin:*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "kms:*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```
and this contains `kms:*`.

I am basically just trying to recreate this group with a different name so that it works with an openId auth provider.
