### ISSUE TITLE
[bitnami/spark] Spark-UI stages and other tabs not accessible when reverse-proxy is enabled

### ISSUE THREAD

**Issue by imsharadmishra** [bitnami/charts#23384]
### Name and Version

bitnami/spark - 6.0.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Kubernetes Version: 1.25
Spark: 3.4.2
Helm chart: 6.0.0

When enabled reverse proxy in master and worker configOptions. We're not able to access different tabs available in spark UI e.g.(stages, environment, storage etc.)

Steps to reproduce:
After installing the chart Spark Cluster(Master and worker) UI is available at:
https://spark.staging.abc.com/
<img width="1509" alt="Screenshot 2024-02-09 at 5 04 49 PM" src="https://github.com/bitnami/charts/assets/75194603/c6ac9a52-0b2b-4abf-8c3d-0b002b5202bc">

We are able to access running application by click on applicationID under Running Applications link:
<img width="1512" alt="Screenshot 2024-02-09 at 5 05 48 PM" src="https://github.com/bitnami/charts/assets/75194603/80ed9389-e82a-4458-b625-8fe97270c116">

We can access spark UI by clicking Application Detail UI:
<img width="1504" alt="Screenshot 2024-02-09 at 5 06 59 PM" src="https://github.com/bitnami/charts/assets/75194603/bb75e7dc-a39f-4386-8e24-84f35ced9689">

We are taken to jobs tab when we click on Application Detail UI
URL looks like: https://spark.staging.abc.com/proxy/app-20240208103209-0030/stages/
<img width="1511" alt="Screenshot 2024-02-09 at 5 09 28 PM" src="https://github.com/bitnami/charts/assets/75194603/0a1f0b20-7bab-4d5c-8e28-1c1479ea0eda">

When we click any of the tab from spark UI e.g. stages or environment etc, it takes us back to spark cluster UI page
<img width="1508" alt="Screenshot 2024-02-09 at 5 13 01 PM" src="https://github.com/bitnami/charts/assets/75194603/d73bd701-d4e5-457a-a427-41d7fb9abe8b">

We noticed that endpoint changes to 
https://spark.staging.abc.com/stages/ 
instead of 
https://spark.staging.abc.com/proxy/app-20240208103209-0030/stages/

### Are you using any custom parameters or values?

Configurations set in values.yaml
```
master:
  configOptions:
    -Dspark.ui.reverseProxy=true
    -Dspark.ui.reverseProxyUrl=https://spark.staging.abc.com

worker:
  configOptions:
    -Dspark.ui.reverseProxy=true
    -Dspark.ui.reverseProxyUrl=https://spark.staging.abc.com

service:
  type: ClusterIP
  ports:
    http: 8080
    https: 443
    cluster: 7077

ingress:

  enabled: true
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: spark.staging.abc.com
  ingressClassName: "staging"
  path: /
```

### What is the expected behavior?

Expected behaviour is that when I click on stages tab, instead of taking me to 
https://spark.staging.abc.com/stages/ 
it should take me to following URL:
https://spark.staging.abc.com/proxy/app-20240208103209-0030/stages/

### What do you see instead?

current behaviour is it takes me to URL: https://spark.staging.abc.com/stages/ , which shows spark cluster UI with master and worker details
<img width="1508" alt="Screenshot 2024-02-09 at 5 13 01 PM" src="https://github.com/bitnami/charts/assets/75194603/3cff7dcb-c11b-449f-b745-ab4d4935dd83">
