### ISSUE TITLE
[bitnami/redis-cluster] Metrics exporter is not getting deployed with metrics.enabled=true

### ISSUE THREAD

**Issue by solarvm** [bitnami/charts#23393]
### Name and Version

bitnami/redis-cluster 9.5.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Just try to deploy redis-cluster with metrics enabled. 

### Are you using any custom parameters or values?

```
usePassword: false
persistence:
  enabled: true
  size: 32G
cluster:
  init: true
  nodes: 15
  replicas: 0
podDisruptionBudget:
  minAvailable: 2
redis:
  configmap: |-
    maxmemory 16000mb
    maxmemory-policy allkeys-lru
    maxclients 50000
    cluster-require-full-coverage no
    cluster-allow-reads-when-down yes

sysctlImage:
  enabled: true
  mountHostSys: true
  command:
    - /bin/sh
    - -c
    - |-
      sysctl -w net.core.somaxconn=10000
      echo never > /host-sys/kernel/mm/transparent_hugepage/enabled

metrics:
  enabled: true
```

### What is the expected behavior?

expect to have redis-exporter container + service 

### What do you see instead?

only the redis container is up, metrics exporter is not deployed
