### ISSUE TITLE
Cannot pass `extraIngress` to networkPolicy

### ISSUE THREAD

**Issue by aledegano** [bitnami/charts#23424]
### Name and Version

bitnami/solr:8.7.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. With the values file (basically the same of what is reported in the values.yaml of this chart):
```yaml
---
networkPolicy:
  extraIngress:
    - ports:
        - port: 8983
      from:
        - podSelector:
            - matchLabels:
                - app: foo-bar
```
2. Helm install: `helm -n solr install solr bitnami-archive/solr --create-namespac
e -f solr-values.yaml`

### Are you using any custom parameters or values?

```yaml
---
networkPolicy:
  extraIngress:
    - ports:
        - port: 8983
      from:
        - podSelector:
            - matchLabels:
                - app: foo-bar
```

### What is the expected behavior?

The Helm chart deploys and the networkPolicy allows ingress from the pod whose label is `app= foo-bar`

### What do you see instead?

An error:
```
Error: INSTALLATION FAILED: 1 error occurred:
        * NetworkPolicy in version "v1" cannot be handled as a NetworkPolicy: json: cannot unmarshal array into Go struct field NetworkPolicyPeer.spec.ingress.from.podSelector of type v1.LabelSelector
```

**Comment by fmulero** [comment]
Hi @aledegano, thanks for using `bitnami/charts`.

Your values seems not correct, `matchLabels` should contain a map, please try with these values:
```yaml
networkPolicy:
  extraIngress:
    - ports:
        - port: 8983
      from:
        - podSelector:
            matchLabels:
              app: foo-bar

```
