### ISSUE TITLE
[bitname/mongodb] `uri` in `daqconfig-mongodb-svcbind-0` password base64 encoded

### ISSUE THREAD

**Issue by jcpunk** [bitnami/charts#23541]
### Name and Version

bitnami/mongodb 14.8.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. install chart
2. decode the `uri` from the `daqconfig-mongodb-svcbind-0` secret
3. note the password in the `uri` is base64 encoded in the decoded string

### Are you using any custom parameters or values?

```yaml
---
architecture: standalone

directoryPerDB: true

useStatefulSet: true

auth: {"databases": ["daqconfigdb"], "passwords": ["userpassword"], "rootPassword": "adminpassword", "rootUser": "root", "usernames": ["daqconfig"]}

serviceBindings:
  enabled: true

persistence:
  enabled: true
  storageClass: local-path

affinity:
 nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: node-role.kubernetes.io/worker
         operator: Exists

metrics: # TODO https://github.com/percona/grafana-dashboards/tree/main/dashboards/MongoDB
  enabled: true
  compatibleMode: false # skip old metrics
  username: metrics
  collector:
    all: true
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: 300m
      memory: 512Mi
  serviceMonitor:
    enabled: true
    labels:
      "prometheus.io/servicemonitor": "mongodb-metrics"
  prometheusRule: # setup alerting rules here and then enable it
    enabled: false
    rules: []
    additionalLabels:
      "prometheus.io/rule": "mongodb-metrics"
```

### What is the expected behavior?

The password should only be base64 encoded one time

### What do you see instead?

The password is double base64 encoded
