### ISSUE TITLE
Helm Database Charts Not Loading Due To Permissions

### ISSUE THREAD

**Issue by davidphudo** [bitnami/charts#2356]
Please note, this is not a bug, I just can't seem to get these databases up and working through helm.  I'm not using kubeapps to deploy but deploying manually through each chart helm.

**Charts:**  MongoDb, MySQL, PostGreSQL

**Objective: ** Install all database types in our production environment, we are currently moving away from virtual machines and docker-compose.

**Environment:** All Ubuntu 18.04 machines with 2 CPU and 2 GB of memory for Kubernetes masters.  Worker nodes run the same OS but have significantly more resources, 40 cores 128 GB of memory.  We are running in a multi-master setup with 3 kubernetes masters, 1 kubernetes proxy running HAProxy, and currently 2 worker nodes.

**Error:** I get CrashLoopBackOff, when looking at the logs, it appears it can't write to the /bitnami directory.  I have manually created pv and pvc sets but it appears it doesn't have permissions to write.  On the worker nodes, I had tried making the /bitnami/mongodb, /bitnami/mysql, and /bitnami/postgresql folders but I still get permission issues.  I also tried command "chmod a+rwx /bitnami/X" for each X folder and sub folders but it didn't work.  This appears to be a write permission issue to the worker node drives, anybody have any idea why I can't get this to work on 3 different helm charts?

- mkdir: cannot create directory '/bitnami/mongodb/data': Permission denied
- mkdir: cannot create directory '/bitnami/mysql/data': Permission denied
- Interestingly enough, the postgresql-ha doesn't not have any permission denied logs.

**Note:** N0TSecur3 is a random password, I'm not using that in my environment.

How to reproduce:
PV:
**Install via "kubectl apply -f pv.yaml"**
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-sharded-configsvr-0-volume
  labels:
    type: local
spec:
  storageClassName: mongodb-sharded-configsvr-0
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/bitnami/mongodb/configsvr-0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-sharded-shard0-volume
  labels:
    type: local
spec:
  storageClassName: mongodb-sharded-shard0
  capacity:
    storage: 256Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/bitnami/mongodb/shard0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-sharded-shard1-volume
  labels:
    type: local
spec:
  storageClassName: mongodb-sharded-shard1
  capacity:
    storage: 256Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/bitnami/mongodb/shard1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-sharded-shard2-volume
  labels:
    type: local
spec:
  storageClassName: mongodb-sharded-shard2
  capacity:
    storage: 256Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/bitnami/mongodb/shard2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    type: local
spec:
  storageClassName: mysql
  capacity:
    storage: 256Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/bitnami/mysql/"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-volume
  labels:
    type: local
spec:
  storageClassName: postgresql
  capacity:
    storage: 256Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/bitnami/postgresql/"
```

PVC:
**Install via "kubectl apply -f pvc.yaml"**
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mongodb-mongodb-sharded-configsvr-0
spec:
  storageClassName: mongodb-sharded-configsvr-0
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mongodb-mongodb-sharded-shard0-data-0
spec:
  storageClassName: mongodb-sharded-shard0
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mongodb-mongodb-sharded-shard1-data-0
spec:
  storageClassName: mongodb-sharded-shard1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mongodb-mongodb-sharded-shard2-data-0
spec:
  storageClassName: mongodb-sharded-shard2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
spec:
  storageClassName: mysql
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-postgresql-postgresql-ha-postgresql-0
spec:
  storageClassName: postgresql
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
```

Install via helm:
**helm install -f values.yaml Bitnami/mongodb-sharded**

```
global: {}
image:
    registry: docker.io
    repository: bitnami/mongodb-sharded
    tag: 4.2.5-debian-10-r31
    pullPolicy: IfNotPresent
    pullSecrets: null
    debug: false
nameOverride: null
fullnameOverride: null
mongodbRootPassword: N0TSecur3
mongodbUsername: app
mongodbPassword: N0TSecur3
mongodbDatabase: admin
replicaSetKey: N0TSecur3
existingSecret: null
usePasswordFile: true
shards: 3
shardsvr:
    dataNode:
        replicas: 2
        resources: {}
        mongodbExtraFlags: []
        priorityClassName: null
        nodeSelector: {}
        affinity: {}
        tolerations: []
        updateStrategy:
            type: RollingUpdate
        config: null
        configCM: null
        extraEnvVars: null
        extraEnvVarsCM: null
        extraEnvVarsSecret: null
        sidecars: null
        initContainers: null
        podAnnotations: null
        podLabels: null
        extraVolumes: null
        extraVolumeMounts: null
        schedulerName: null
    arbiter:
        replicas: 1
        resources: {}
        mongodbExtraFlags: []
        priorityClassName: null
        nodeSelector: {}
        affinity: {}
        tolerations: []
        updateStrategy:
            type: RollingUpdate
        config: null
        configCM: null
        extraEnvVars: null
        extraEnvVarsCM: null
        extraEnvVarsSecret: null
        sidecars: null
        initContainers: null
        podAnnotations: null
        podLabels: null
        extraVolumes: null
        extraVolumeMounts: null
        schedulerName: null
    persistence:
        enabled: true
        mountPath: /bitnami/mongodb
        subPath: ""
        storageClass: mongodb
        accessModes:
            - ReadWriteMany
        size: 256Gi
        annotations: {}
configsvr:
    replicas: 3
    resources: {}
    mongodbExtraFlags: []
    priorityClassName: null
    nodeSelector: {}
    affinity: {}
    tolerations: []
    updateStrategy:
        type: RollingUpdate
    config: null
    configCM: null
    extraEnvVars: null
    extraEnvVarsCM: null
    extraEnvVarsSecret: null
    sidecars: null
    initContainers: null
    podAnnotations: null
    podLabels: null
    extraVolumes: null
    extraVolumeMounts: null
    schedulerName: null
    persistence:
        enabled: true
        mountPath: /bitnami/mongodb
        subPath: ""
        storageClass: mongodb
        accessModes:
            - ReadWriteMany
        size: 8Gi
        annotations: {}
mongos:
    replicas: 3
    resources: {}
    mongodbExtraFlags: []
    priorityClassName: null
    nodeSelector: {}
    affinity: {}
    tolerations: []
    updateStrategy:
        type: RollingUpdate
    config: null
    configCM: null
    extraEnvVars: null
    extraEnvVarsCM: null
    extraEnvVarsSecret: null
    sidecars: null
    initContainers: null
    podAnnotations: null
    podLabels: null
    extraVolumes: null
    extraVolumeMounts: null
    schedulerName: null
common:
    useHostnames: true
    mongodbEnableIPv6: false
    mongodbDirectoryPerDB: false
    mongodbSystemLogVerbosity: 0
    mongodbDisableSystemLog: false
    mongodbMaxWaitTimeout: 120
    initScriptsCM: null
    initScriptsSecret: null
    extraEnvVars: null
    extraEnvVarsCM: null
    extraEnvVarsSecret: null
    sidecars: null
    initContainers: null
    podAnnotations: null
    podLabels: null
    extraVolumes: null
    extraVolumeMounts: null
volumePermissions:
    enabled: false
    image:
        registry: docker.io
        repository: bitnami/minideb
        tag: buster
        pullPolicy: Always
    resources: {}
securityContext:
    enabled: false
    fsGroup: 1101
    runAsUser: 1101
    runAsNonRoot: true
clusterDomain: cluster.local
service:
    name: null
    annotations: {}
    type: NodePort
    externalTrafficPolicy: Cluster
    port: 27017
    clusterIP: null
    nodePort: 31000
    externalIPs: []
    loadBalancerIP: null
    loadBalancerSourceRanges: []
    extraPorts: null
livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
metrics:
    enabled: false
    image:
        registry: docker.io
        repository: bitnami/mongodb-exporter
        tag: 0.10.0-debian-10-r79
        pullPolicy: Always
    extraArgs: ""
    livenessProbe:
        enabled: false
        initialDelaySeconds: 15
        periodSeconds: 5
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
    readinessProbe:
        enabled: false
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 1
        failureThreshold: 3
        successThreshold: 1
    podAnnotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9216'
    serviceMonitor:
        enabled: false
        namespace: monitoring
        selector:
            prometheus: kube-prometheus

```

**helm install -f values.yaml Bitnami/mysql**

```
image:
    registry: docker.io
    repository: bitnami/mysql
    tag: 8.0.19-debian-10-r86
    pullPolicy: IfNotPresent
clusterDomain: cluster.local
volumePermissions:
    enabled: false
    image:
        registry: docker.io
        repository: bitnami/minideb
        tag: buster
        pullPolicy: Always
    resources:
        limits: {}
        requests: {}
root:
    password: N0TSecur3
    forcePassword: true
    injectSecretsAsVolume: true
db:
    user: app
    password: N0TSecur3
    name: my_database
    forcePassword: true
    injectSecretsAsVolume: true
replication:
    enabled: true
    user: replicator
    password: N0TSecur3
    forcePassword: true
    injectSecretsAsVolume: true
serviceAccount:
    create: true
master:
    config: "[mysqld]\ndefault_authentication_plugin=mysql_native_password\nskip-name-resolve\nexplicit_defaults_for_timestamp\nbasedir=/opt/bitnami/mysql\nplugin_dir=/opt/bitnami/mysql/plugin\nport=3306\nsocket=/opt/bitnami/mysql/tmp/mysql.sock\ndatadir=/bitnami/mysql\ntmpdir=/opt/bitnami/mysql/tmp\nmax_allowed_packet=16M\nbind-address=0.0.0.0\npid-file=/opt/bitnami/mysql/tmp/mysqld.pid\nlog-error=/opt/bitnami/mysql/logs/mysqld.log\ncharacter-set-server=UTF8\ncollation-server=utf8_general_ci\n\n[client]\nport=3306\nsocket=/opt/bitnami/mysql/tmp/mysql.sock\ndefault-character-set=UTF8\nplugin_dir=/opt/bitnami/mysql/plugin\n\n[manager]\nport=3306\nsocket=/opt/bitnami/mysql/tmp/mysql.sock\npid-file=/opt/bitnami/mysql/tmp/mysqld.pid"
    updateStrategy:
        type: RollingUpdate
    podAnnotations: {}
    affinity: {}
    nodeSelector: {}
    tolerations: []
    securityContext:
        enabled: true
        fsGroup: 1101
        runAsUser: 1101
    containerSecurityContext: {}
    resources:
        limits: {}
        requests: {}
    livenessProbe:
        enabled: true
        initialDelaySeconds: 120
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
    readinessProbe:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
    persistence:
        enabled: true
        mountPath: /bitnami/mysql
        storageClass: mysql
        annotations: {}
        accessModes:
            - ReadWriteMany
        size: 256Gi
        existingClaim: mysql-claim
slave:
    replicas: 2
    config: "[mysqld]\ndefault_authentication_plugin=mysql_native_password\nskip-name-resolve\nexplicit_defaults_for_timestamp\nbasedir=/opt/bitnami/mysql\nport=3306\nsocket=/opt/bitnami/mysql/tmp/mysql.sock\ndatadir=/bitnami/mysql/data\ntmpdir=/opt/bitnami/mysql/tmp\nmax_allowed_packet=16M\nbind-address=0.0.0.0\npid-file=/opt/bitnami/mysql/tmp/mysqld.pid\nlog-error=/opt/bitnami/mysql/logs/mysqld.log\ncharacter-set-server=UTF8\ncollation-server=utf8_general_ci\n\n[client]\nport=3306\nsocket=/opt/bitnami/mysql/tmp/mysql.sock\ndefault-character-set=UTF8\n\n[manager]\nport=3306\nsocket=/opt/bitnami/mysql/tmp/mysql.sock\npid-file=/opt/bitnami/mysql/tmp/mysqld.pid"
    updateStrategy:
        type: RollingUpdate
    podAnnotations: {}
    affinity: {}
    nodeSelector: {}
    tolerations: []
    securityContext:
        enabled: false
        fsGroup: 1001
        runAsUser: 1001
    containerSecurityContext: {}
    resources:
        limits: {}
        requests: {}
    livenessProbe:
        enabled: true
        initialDelaySeconds: 120
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
    readinessProbe:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
    persistence:
        enabled: true
        mountPath: /bitnami/mysql
        storageClass: mysql
        annotations: {}
        accessModes:
            - ReadWriteMany
        size: 256Gi
        existingClaim: mysql-claim
service:
    type: ClusterIP
    port: 3306
    annotations: {}
metrics:
    enabled: false
    image:
        registry: docker.io
        repository: bitnami/mysqld-exporter
        tag: 0.12.1-debian-10-r78
        pullPolicy: IfNotPresent
    resources:
        limits: {}
        requests: {}
    service:
        type: ClusterIP
        port: 9104
        annotations:
            prometheus.io/scrape: 'true'
            prometheus.io/port: '{{ .Values.metrics.service.port }}'
    serviceMonitor:
        enabled: false
```

**helm install -f values.yaml Bitnami/postgresql-ha**

```
postgresqlImage:
    registry: docker.io
    repository: bitnami/postgresql-repmgr
    tag: 11.7.0-debian-10-r76
    pullPolicy: IfNotPresent
    debug: false
pgpoolImage:
    registry: docker.io
    repository: bitnami/pgpool
    tag: 4.1.1-debian-10-r50
    pullPolicy: IfNotPresent
    debug: false
volumePermissionsImage:
    registry: docker.io
    repository: bitnami/minideb
    tag: buster
    pullPolicy: Always
metricsImage:
    registry: docker.io
    repository: bitnami/postgres-exporter
    tag: 0.8.0-debian-10-r72
    pullPolicy: IfNotPresent
    debug: false
clusterDomain: cluster.local
postgresql:
    labels: {}
    podLabels: {}
    replicaCount: 2
    updateStrategyType: RollingUpdate
    podAnnotations: {}
    affinity: {}
    nodeSelector: {}
    priorityClassName: ""
    tolerations: {}
    securityContext:
        enabled: false
        fsGroup: 1001
        runAsUser: 1001
    resources:
        limits: {}
        requests: {}
    livenessProbe:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 6
    readinessProbe:
        enabled: true
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 6
    pdb:
        create: false
        minAvailable: 1
    username: postgres
    password: N0TSecur3
    upgradeRepmgrExtension: false
    pgHbaTrustAll: false
    repmgrUsername: repmgr
    repmgrDatabase: repmgr
    repmgrLogLevel: NOTICE
    repmgrConnectTimeout: 5
    repmgrReconnectAttempts: 3
    repmgrReconnectInterval: 5
pgpool:
    labels: {}
    podLabels: {}
    replicaCount: 1
    podAnnotations: {}
    affinity: {}
    nodeSelector: {}
    priorityClassName: ""
    tolerations: {}
    securityContext:
        enabled: false
        fsGroup: 1001
        runAsUser: 1001
    resources:
        limits: {}
        requests: {}
    livenessProbe:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 5
    readinessProbe:
        enabled: true
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 5
    pdb:
        create: false
        minAvailable: 1
    adminUsername: admin
    useLoadBalancing: true
ldap:
    enabled: false
    uri: null
    base: null
    binddn: null
    bindpw: null
    bslookup: null
    scope: null
    tlsReqcert: null
    nssInitgroupsIgnoreusers: 'root,nslcd'
volumePermissions:
    enabled: false
    securityContext:
        runAsUser: 0
    resources:
        limits: {}
        requests: {}
metrics:
    enabled: false
    securityContext:
        enabled: true
        runAsUser: 1001
    resources:
        limits: {}
        requests: {}
    livenessProbe:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 6
    readinessProbe:
        enabled: true
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 6
    annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9187'
    serviceMonitor:
        enabled: false
        selector:
            prometheus: kube-prometheus
persistence:
    enabled: true
    storageClass: postgresql
    mountPath: /bitnami/postgresql
    accessModes:
        - ReadWriteMany
    size: 256Gi
    annotations: {}
service:
    type: ClusterIP
    port: 5432
    annotations: {}
ingress:
    enabled: false
    certManager: false
    annotations: {}
    hosts:
        -
            name: postgresql.local
            path: /
    tls:
        -
            hosts: [postgresql.local]
            secretName: postgresql.local-tls
    secrets: null
networkPolicy:
    enabled: true
    allowExternal: false
```
