### ISSUE TITLE
[bitnami/elasticsearch] Extra Roles on Master+Data throws error

### ISSUE THREAD

**Issue by ArkShocer** [bitnami/charts#23562]
### Name and Version

bitnami/elasticsearch 19.18.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Setup ArgoCD
2. Setup ArgoCD Appsets
3. Deploy Elasticsearch with the provided values config.

### Are you using any custom parameters or values?

```yaml
fullnameOverride: "elasticsearch"
extraConfig:
    "cluster.remote":
        testing:
            seeds:
                - elasticsearch.testing-2.svc.cluster.local:9300
            skip_unavailable: true
master:
    extraRoles:
        - "remote_cluster_client"
    replicaCount: 2
    persistence:
        storageClass: "managed-csi"
data:
    replicaCount: 2
    persistence:
        storageClass: "managed-csi"
coordinating:
    replicaCount: 2
    extraRoles:
        - "remote_cluster_client"
    resources:
        requests:
            cpu: 25m
            memory: 512Mi
    heapSize: 256m
ingest:
    replicaCount: 2
security:
    enabled: true
    elasticPassword: "admin@12345"
    tls:
        restEncryption: true
        autoGenerated: true
```

### What is the expected behavior?

Not getting Invalid node role since the exact same role is displayed in the error log I provided as "working".

### What do you see instead?

```txt
elasticsearch 12:28:32.56 INFO  ==>
elasticsearch 12:28:32.61 INFO  ==> Welcome to the Bitnami elasticsearch container
elasticsearch 12:28:32.64 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
elasticsearch 12:28:32.65 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
elasticsearch 12:28:32.66 INFO  ==>
elasticsearch 12:28:32.66 INFO  ==> ** Starting Elasticsearch setup **
elasticsearch 12:28:32.91 ERROR ==> Invalid node role '[remote_cluster_client]'. Supported roles are 'master,data,data_content,data_hot,data_warm,data_cold,data_frozen,ingest,ml,remote_cluster_client,transform'
```
