### ISSUE TITLE
[bitnami/nginx] - Add tlsWwwPrefix mechanism to handle 301 redirects

### ISSUE THREAD

**Issue by g0blin79** [bitnami/charts#23570]
### Name and Version

bitnami/nginx

### What is the problem this feature will solve?

This issue is strictly related to this https://github.com/bitnami/charts/issues/21864, previously solved for bitnami/drupal.

At this stage does not seem that the `bitnami/nginx` chart can create an ingress that supports correctly the `nginx.ingress.kubernetes.io/from-to-www-redirect : true` annotations when also `tls: true`

Basically, I want to manage an ingress manifest like this:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: my-example-app
  namespace: my-example-namespace
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          service:
            name: my-example-app
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - example.com
    - www.example.com
    secretName: example.com-tls
[...]
```

### What is the feature you are proposing to solve the problem?

A viable solution to this is just implemented in the `bitnami/wordpress` and `bitnami/drupal` helm charts here:

- https://github.com/bitnami/charts/blob/main/bitnami/wordpress/values.yaml#L641C1-L644C22
- https://github.com/bitnami/charts/blob/main/bitnami/wordpress/templates/ingress.yaml#L53C1-L55C19
- https://github.com/bitnami/charts/blob/main/bitnami/drupal/values.yaml#L531
- https://github.com/bitnami/charts/blob/main/bitnami/drupal/templates/ingress.yaml#L56C1-L61C15
