### ISSUE TITLE
Problem with bus connection between redis clusters in k8s

### ISSUE THREAD

**Issue by ku9nov** [bitnami/charts#23593]
### Name and Version

bitnami/redis latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hey everyone,

I am currently working on deploying a Redis Cluster across different regions and VPCs, utilizing Istio to establish connections between the clusters using service names. Istio can't share PodIP between clusters for example.

I acknowledge that I am using my manifests, which are slightly modified versions of your Helm Chart. I hope it's appropriate to bring up a question here; my apologies if it's not.

**Important Note: All my configurations work seamlessly when the Redis Cluster is contained within a single Kubernetes cluster.**

Here are my configurations for two clusters in different VPCs (regions sfo3 and fra1):
**SFO3**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-sfo3-0
  namespace: redis
spec:
  selector:
    app.kubernetes.io/instance: redis-sfo3
    app.kubernetes.io/name: redis-cluster
    statefulset.kubernetes.io/pod-name: redis-sfo3-redis-cluster-0
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: tcp-redis
      protocol: TCP
      nodePort: null
    - name: tcp-redis-bus
      protocol: TCP
      port: 16379
      targetPort: tcp-redis-bus 
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-sfo3-1
  namespace: redis
spec:
  selector:
    app.kubernetes.io/instance: redis-sfo3
    app.kubernetes.io/name: redis-cluster
    statefulset.kubernetes.io/pod-name: redis-sfo3-redis-cluster-1
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: tcp-redis
      protocol: TCP
      nodePort: null
    - name: tcp-redis-bus
      protocol: TCP
      port: 16379
      targetPort: tcp-redis-bus 


---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-sfo3-2
  namespace: redis
spec:
  selector:
    app.kubernetes.io/instance: redis-sfo3
    app.kubernetes.io/name: redis-cluster
    statefulset.kubernetes.io/pod-name: redis-sfo3-redis-cluster-2
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: tcp-redis
      protocol: TCP
      nodePort: null
    - name: tcp-redis-bus
      protocol: TCP
      port: 16379
      targetPort: tcp-redis-bus 


---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-sfo3-3
  namespace: redis
spec:
  selector:
    app.kubernetes.io/instance: redis-sfo3
    app.kubernetes.io/name: redis-cluster
    statefulset.kubernetes.io/pod-name: redis-sfo3-redis-cluster-3
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: tcp-redis
      protocol: TCP
      nodePort: null
    - name: tcp-redis-bus
      protocol: TCP
      port: 16379
      targetPort: tcp-redis-bus 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sfo3-redis-cluster
  namespace: redis
  labels:
    app.kubernetes.io/instance: redis-sfo3
    
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/version: 7.2.4
    
spec:
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: redis-sfo3
      app.kubernetes.io/name: redis-cluster
  replicas: 4
  serviceName: redis-sfo3-redis-cluster-headless
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: redis-sfo3
        
        app.kubernetes.io/name: redis-cluster
        app.kubernetes.io/version: 7.2.4
        
      annotations:
        checksum/scripts: 5db89f6535037d96cd347a0abdc50bb49d1de6bd7c8411d25a92371cab53360c
        checksum/secret: b2cbb282d16ec4419e9aa6a71ed750e3f5654d84ccca57c8b3d362e7a0ef5632
        checksum/config: 2e89562d0d7a828b5b34a641f8fe2fcfdb59155cacd13f3e7ef83dbcbb77753e
    spec:
      hostNetwork: false
      enableServiceLinks: false

      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      serviceAccountName: redis-sfo3-redis-cluster
      automountServiceAccountToken: false
      affinity:
        podAffinity:

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: redis-sfo3
                    app.kubernetes.io/name: redis-cluster
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
      initContainers:
      - name: initialize-redis-pod-name-label
        image: busybox
        command: ['sh', '-c', 'echo "pod-name=$(hostname)" >> /mnt/labels/pod-name']
        volumeMounts:
        - name: label-volume
          mountPath: /mnt/labels
      containers:
        - name: redis-sfo3-redis-cluster
          image: registry-1.docker.io/bitnami/redis-cluster:7.2.4-debian-11-r19
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: null
            seccompProfile:
              type: RuntimeDefault
          command: ['/bin/bash', '-c']
          args:
            - |
              # Backwards compatibility change
              if ! [[ -f /opt/bitnami/redis/etc/redis.conf ]]; then
                  echo COPYING FILE
                  cp  /opt/bitnami/redis/etc/redis-default.conf /opt/bitnami/redis/etc/redis.conf
              fi
              pod_index=($(echo "$POD_NAME" | tr "-" "\n"))
              pod_index="${pod_index[-1]}"
              if [[ "$pod_index" == "0" ]]; then
                export REDIS_CLUSTER_CREATOR="yes"
                export REDIS_CLUSTER_REPLICAS="1"
              fi
              /opt/bitnami/scripts/redis-cluster/entrypoint.sh /opt/bitnami/scripts/redis-cluster/run.sh
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_NODES
              value: "redis-cluster-sfo3-0.redis redis-cluster-sfo3-1.redis redis-cluster-sfo3-2.redis redis-cluster-sfo3-3.redis redis-cluster-fra1-0.redis redis-cluster-fra1-1.redis"
            - name: REDISCLI_AUTH
              valueFrom:
                secretKeyRef:
                  name: redis-sfo3-redis-cluster
                  key: redis-password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-sfo3-redis-cluster
                  key: redis-password
            - name: REDIS_AOF_ENABLED
              value: "yes"
            - name: REDIS_TLS_ENABLED
              value: "no"
            - name: REDIS_PORT_NUMBER
              value: "6379"
          ports:
            - name: tcp-redis
              containerPort: 6379
            - name: tcp-redis-bus
              containerPort: 16379
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            # One second longer than command timeout should prevent generation of zombie processes.
            timeoutSeconds: 6
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - /scripts/ping_liveness_local.sh 5
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            # One second longer than command timeout should prevent generation of zombie processes.
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - /scripts/ping_readiness_local.sh 1
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: redis-data
              mountPath: /bitnami/redis/data
              subPath:
            - name: default-config
              mountPath: /opt/bitnami/redis/etc/redis-default.conf
              subPath: redis-default.conf
            - name: redis-tmp-conf
              mountPath: /opt/bitnami/redis/etc/
      volumes:
        - name: scripts
          configMap:
            name: redis-sfo3-redis-cluster-scripts
            defaultMode: 0755
        - name: default-config
          configMap:
            name: redis-sfo3-redis-cluster-default
        - name: redis-tmp-conf
          emptyDir: {}
        - name: label-volume
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        labels:
          app.kubernetes.io/instance: redis-sfo3
          app.kubernetes.io/name: redis-cluster
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
```
**FRA1**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-fra1-0
  namespace: redis
spec:
  selector:
    app.kubernetes.io/instance: redis-fra1
    app.kubernetes.io/name: redis-cluster
    statefulset.kubernetes.io/pod-name: redis-fra1-redis-cluster-0
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: tcp-redis
      protocol: TCP
      nodePort: null
    - name: tcp-redis-bus
      protocol: TCP
      port: 16379
      targetPort: tcp-redis-bus 
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-fra1-1
  namespace: redis
spec:
  selector:
    app.kubernetes.io/instance: redis-fra1
    app.kubernetes.io/name: redis-cluster
    statefulset.kubernetes.io/pod-name: redis-fra1-redis-cluster-1
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: tcp-redis
      protocol: TCP
      nodePort: null
    - name: tcp-redis-bus
      protocol: TCP
      port: 16379
      targetPort: tcp-redis-bus 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-fra1-redis-cluster
  namespace: redis
  labels:
    app.kubernetes.io/instance: redis-fra1
    
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/version: 7.2.4
    
spec:
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: redis-fra1
      app.kubernetes.io/name: redis-cluster
  replicas: 2
  serviceName: redis-fra1-redis-cluster-headless
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: redis-fra1
        
        app.kubernetes.io/name: redis-cluster
        app.kubernetes.io/version: 7.2.4
        
      annotations:
        checksum/scripts: 5db89f6535037d96cd347a0abdc50bb49d1de6bd7c8411d25a92371cab53360c
        checksum/secret: b2cbb282d16ec4419e9aa6a71ed750e3f5654d84ccca57c8b3d362e7a0ef5632
        checksum/config: 2e89562d0d7a828b5b34a641f8fe2fcfdb59155cacd13f3e7ef83dbcbb77753e
    spec:
      hostNetwork: false
      enableServiceLinks: false

      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      serviceAccountName: redis-fra1-redis-cluster
      automountServiceAccountToken: false
      affinity:
        podAffinity:

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: redis-fra1
                    app.kubernetes.io/name: redis-cluster
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
      initContainers:
      - name: initialize-redis-pod-name-label
        image: busybox
        command: ['sh', '-c', 'echo "pod-name=$(hostname)" >> /mnt/labels/pod-name']
        volumeMounts:
        - name: label-volume
          mountPath: /mnt/labels
      containers:
        - name: redis-fra1-redis-cluster
          image: registry-1.docker.io/bitnami/redis-cluster:7.2.4-debian-11-r19
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: null
            seccompProfile:
              type: RuntimeDefault
          command: ['/bin/bash', '-c']
          args:
            - |
              # Backwards compatibility change
              if ! [[ -f /opt/bitnami/redis/etc/redis.conf ]]; then
                  echo COPYING FILE
                  cp  /opt/bitnami/redis/etc/redis-default.conf /opt/bitnami/redis/etc/redis.conf
              fi
              pod_index=($(echo "$POD_NAME" | tr "-" "\n"))
              pod_index="${pod_index[-1]}"
              # if [[ "$pod_index" == "0" ]]; then
              #   export REDIS_CLUSTER_CREATOR="yes"
              #   export REDIS_CLUSTER_REPLICAS="1"
              # fi
              /opt/bitnami/scripts/redis-cluster/entrypoint.sh /opt/bitnami/scripts/redis-cluster/run.sh
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_NODES
              value: "redis-cluster-sfo3-0.redis redis-cluster-sfo3-1.redis redis-cluster-sfo3-2.redis redis-cluster-sfo3-3.redis redis-cluster-fra1-0.redis redis-cluster-fra1-1.redis"
            - name: REDISCLI_AUTH
              valueFrom:
                secretKeyRef:
                  name: redis-fra1-redis-cluster
                  key: redis-password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-fra1-redis-cluster
                  key: redis-password
            - name: REDIS_AOF_ENABLED
              value: "yes"
            - name: REDIS_TLS_ENABLED
              value: "no"
            - name: REDIS_PORT_NUMBER
              value: "6379"
          ports:
            - name: tcp-redis
              containerPort: 6379
            - name: tcp-redis-bus
              containerPort: 16379
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            # One second longer than command timeout should prevent generation of zombie processes.
            timeoutSeconds: 6
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - /scripts/ping_liveness_local.sh 5
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            # One second longer than command timeout should prevent generation of zombie processes.
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - /scripts/ping_readiness_local.sh 1
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: redis-data
              mountPath: /bitnami/redis/data
              subPath:
            - name: default-config
              mountPath: /opt/bitnami/redis/etc/redis-default.conf
              subPath: redis-default.conf
            - name: redis-tmp-conf
              mountPath: /opt/bitnami/redis/etc/
      volumes:
        - name: scripts
          configMap:
            name: redis-fra1-redis-cluster-scripts
            defaultMode: 0755
        - name: default-config
          configMap:
            name: redis-fra1-redis-cluster-default
        - name: redis-tmp-conf
          emptyDir: {}
        - name: label-volume
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        labels:
          app.kubernetes.io/instance: redis-fra1
          app.kubernetes.io/name: redis-cluster
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
```
This manifests should deploy 2 master\2 slave in SFO3, 1 master\1 replica in FRA1

Logs from sfo3 cluster (which contains the created cluster node):

```
>>> Performing hash slots allocation on 6 nodes...
Master[0] -> Slots 0 - 5460
Master[1] -> Slots 5461 - 10922
Master[2] -> Slots 10923 - 16383
Adding replica 10.245.75.149:6379 to 10.245.56.225:6379
Adding replica 10.245.42.112:6379 to 10.245.213.126:6379
Adding replica 10.245.74.234:6379 to 10.245.232.46:6379
M: 84dddd1bfa0ccfb426af00538eb7f97a183c069e 10.245.56.225:6379
   slots:[0-5460] (5461 slots) master
M: 1245a85a46075cfe33e4ae9686d1054069336214 10.245.213.126:6379
   slots:[5461-10922] (5462 slots) master
M: 0f99cccb1439a65bc8d13479adf1cecf3e260652 10.245.232.46:6379
   slots:[10923-16383] (5461 slots) master
S: 64e7a6d9c9e2bde92dd740e1151c83c502a40e04 10.245.74.234:6379
   replicates 0f99cccb1439a65bc8d13479adf1cecf3e260652
S: 286af877b61780767707ca877d47ceaa854e378d 10.245.75.149:6379
   replicates 84dddd1bfa0ccfb426af00538eb7f97a183c069e
S: 469bb8e739fff87d53188a6ce4ad312f4c175718 10.245.42.112:6379
   replicates 1245a85a46075cfe33e4ae9686d1054069336214
>>> Nodes configuration updated
>>> Assign a different config epoch to each node
>>> Sending CLUSTER MEET messages to join the cluster
Waiting for the cluster to join
...122:M 19 Feb 2024 15:11:50.580 * Cluster state changed: ok
.........
Warning: 1 node(s) may be unreachable
 - The port 16379 of node 10.244.0.131 may be unreachable from:
   10.245.42.112:6379
Cluster bus ports must be reachable by every node.
Remember that cluster bus ports are different from standard instance ports.
..............................................................................................................................
Warning: 1 node(s) may be unreachable
 - The port 16379 of node 10.244.1.161 may be unreachable from:
   10.245.42.112:6379
Cluster bus ports must be reachable by every node.
Remember that cluster bus ports are different from standard instance ports.
.....................
Warning: 1 node(s) may be unreachable
 - The port 16379 of node 10.244.0.111 may be unreachable from:
   10.245.42.112:6379
Cluster bus ports must be reachable by every node.
Remember that cluster bus ports are different from standard instance ports.
..............................................................................................................................
Warning: 1 node(s) may be unreachable
 - The port 16379 of node 10.244.0.111 may be unreachable from:
   10.245.42.112:6379
Cluster bus ports must be reachable by every node.
Remember that cluster bus ports are different from standard instance ports.
...............................................................
Warning: 1 node(s) may be unreachable
 - The port 16379 of node 10.244.0.111 may be unreachable from:
   10.245.75.149:6379
Cluster bus ports must be reachable by every node.
Remember that cluster bus ports are different from standard instance ports.
```

Resources info from fra1 region:

```console
$ kubectl get pods -n redis -o wide
NAME                         READY   STATUS    RESTARTS   AGE   IP             NODE                     NOMINATED NODE   READINESS GATES
redis-fra1-redis-cluster-0   1/2     Running   0          51m   10.244.1.130   indexer-dev-fra1-obum0   <none>           <none>
redis-fra1-redis-cluster-1   1/2     Running   0          51m   10.244.0.152   indexer-dev-fra1-om4m4   <none>           <none>

$ kubectl get svc -n redis
NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)              AGE
redis-cluster-fra1-0                ClusterIP   10.245.75.149    <none>        6379/TCP,16379/TCP   51m
redis-cluster-fra1-1                ClusterIP   10.245.42.112    <none>        6379/TCP,16379/TCP   51m
redis-fra1-redis-cluster            ClusterIP   10.245.173.108   <none>        6379/TCP             2d23h
redis-fra1-redis-cluster-headless   ClusterIP   None             <none>        6379/TCP,16379/TCP   2d23h
```

Resources info from sfo3 region:

```console
$ kubectl get  pods -o wide -n redis
NAME                         READY   STATUS    RESTARTS   AGE   IP             NODE                     NOMINATED NODE   READINESS GATES
redis-sfo3-redis-cluster-0   2/2     Running   0          52m   10.244.0.7     indexer-dev-sfo3-o7anp   <none>           <none>
redis-sfo3-redis-cluster-1   2/2     Running   0          52m   10.244.1.161   indexer-dev-sfo3-ox0pq   <none>           <none>
redis-sfo3-redis-cluster-2   2/2     Running   0          52m   10.244.0.111   indexer-dev-sfo3-o7anp   <none>           <none>
redis-sfo3-redis-cluster-3   2/2     Running   0          52m   10.244.0.131   indexer-dev-sfo3-o7an2   <none>           <none>

$ kubectl get svc -n redis
NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)              AGE
redis-cluster-sfo3-0                ClusterIP   10.245.56.225    <none>        6379/TCP,16379/TCP   52m
redis-cluster-sfo3-1                ClusterIP   10.245.213.126   <none>        6379/TCP,16379/TCP   52m
redis-cluster-sfo3-2                ClusterIP   10.245.232.46    <none>        6379/TCP,16379/TCP   52m
redis-cluster-sfo3-3                ClusterIP   10.245.74.234    <none>        6379/TCP,16379/TCP   52m
redis-sfo3-redis-cluster            ClusterIP   10.245.106.49    <none>        6379/TCP             2d23h
redis-sfo3-redis-cluster-headless   ClusterIP   None             <none>        6379/TCP,16379/TCP   2d23h
```

### What do you see instead?

While the clusters can communicate and discover each other using port 6379, it appears that they are facing difficulties communicating via the bus port. It seems like the bus port wants to communicate with other pods using PodIP. Is this correct?

Unfortunately, Istio also seems to have issues working with headless services between clusters. Is it possible to reconfigure the bus port for different communication? Any advice would be greatly appreciated.

Thank you.
