### ISSUE TITLE
[bitnami/jupyterhub] chart externalDatabase Error: UPGRADE FAILED: template

### ISSUE THREAD

**Issue by alekseytivonchik** [bitnami/charts#23600]
### Name and Version

bitnami/jupyterhub 4.0.2 (appVersion)

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Open values.yaml
2. Set:
```yaml
postgresql:
  enabled: false
...
externalDatabase:
  host: "postgresql.postgresql.svc.cluster.local"
```
3. Run:
`helm upgrade --install jupyterhub -n jupyter -f values.yaml .`
4. Get error:
```
Error: UPGRADE FAILED: template: jupyterhub/templates/hub/deployment.yaml:82:20: executing "jupyterhub/templates/hub/deployment.yaml" at <include "common.images.image" (dict "imageRoot" .Values.postgresql.image "global" .Values.global)>: error calling include: template: jupyterhub/charts/common/templates/_images.tpl:12:31: executing "common.images.image" at <.imageRoot.registry>: nil pointer evaluating interface {}.registry
```

### Are you using any custom parameters or values?

values.yaml customization

### What is the expected behavior?

Success upgrade/install application
