### ISSUE TITLE
dns-controller-manager reports invalid DNS entry for 5-10 mins after upgrade

### ISSUE THREAD

**Issue by krimeshshah** [bitnami/charts#23612]
### Name and Version

bitnami/nginx-ingress-controller 10.1.0 and 10.3.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Install nginx-ingress-controller on 10.1.0
2. Deploy ingress resources on other ns
3. Now perform nginx-ingress-controller upgrade from 10.1.0 to 10.3.0 
4. In the other terminal tab also execute `kubectl get ingress -w -n <ns-of-ingress-resource>` --> You will see the address files empty after some time for a short duration and then it will itself restore the address field with DNS entry
5. Open one more tab in the terminal and execute `kubectl describe ingress <ingress-resource-name> -n <ns of ingress resource>` --> You should see  Normal  dns-annotation  dns-controller-manager    <ingress URl>: dns entry invalid: no target or text specified error
This error only stays for a short time say 5-10 mins and itself fixes but this 5-10 mins causes downtime.

### Are you using any custom parameters or values?
```yaml
watchIngressWithoutClass: true
  ingressClassResource:
    default: true
  replicaCount: 2
  pdb:
    create: true
    minAvailable: 1
  service:
    externalTrafficPolicy: Cluster
    annotations:
      dns.gardener.cloud/class: garden
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3000"
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      service.beta.kubernetes.io/aws-load-balancer-target-node-labels: "ingress"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      dns.gardener.cloud/dnsnames: "*.ingress.CLUSTERNAME.PROJECTNAME.shoot.LANDSCAPE.k8s-hana.ondemand.com"
    ports:
      http: false
  publishService:
    enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
  resources:
    requests:
      memory: 300Mi
      cpu: 250m
    limits:
      memory: 512Mi
  config:
    use-proxy-protocol: "true"
    keep-alive: "305"
    allow-snippet-annotations: "true"
  podAntiAffinityPreset: hard
  defaultBackend:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 256Mi
    podAntiAffinityPreset: hard 
```
### What is the expected behavior?

After or during the upgrade, the DNS controller manager should not report the invalid DNS entry for ingress resources and must not cause downtime.

### What do you see instead?

Event logs in ingress resource -  Normal  dns-annotation  dns-controller-manager    <ingress URl>: dns entry invalid: no target or text specified error

2. `kubectl get ingress -w -n <ns>` will show the Address field empty for a short duration.
