### ISSUE TITLE
[bitnami/opensearch] helm install with security enabled fails

### ISSUE THREAD

**Issue by fgleixner** [bitnami/charts#23610]
### Name and Version

bitnami/opensearch 0.10.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Did a helm install with these values:
```
clusterDomain: mycluster.local
clusterName: os-bitnami
security:
  enabled: true
 adminPassword: "********"
 tls:
   autoGenerated: true
```
And all pods complain about:
`opensearch 14:07:44.27 ERROR ==> Opensearch does not support plaintext conections (HTTP) when Security is enabled.`

### Are you using any custom parameters or values?

see above

### What is the expected behavior?

Helm chart should configure services with https

### What do you see instead?

the error above

### Additional information

-

**Comment by rafariossaa** [comment]
Hi,
  Could you try by addind `security.tls.restEncryption=true` too ?
```
clusterDomain: mycluster.local
clusterName: os-bitnami
security:
  enabled: true
 adminPassword: "********"
 tls:
   autoGenerated: true
   restEncryption: true
```
