### ISSUE TITLE
[bitnami/elasticsearch] Configure alerts - Need bitnami chart to configure alerts in Kibana

### ISSUE THREAD

**Issue by jeffersonjerome19** [bitnami/charts#23620]
### Name and Version

elasticsearch:19.18.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. we are trying to configure alerts from alerts and insights from kibana management
2. while trying to configure rules, additional setup required you must configure an encryption key to use alerting
3. we need to how to configure an encryption key in the bitnami chart
4. Could see a chart to setup Elasticsearch Rest Encryption, however could not find to configure encryption key to use alerting feature
5. Kindly advise on this
```
security:
  enabled: true
  # PASSWORD must be the same value passed to elasticsearch to get an "out of the box" experience
  elasticPassword: "<PASSWORD>"
  tls:
    # AutoGenerate TLS certs for elastic
    autoGenerated: true

kibana:
  elasticsearch:
    security:
      auth:
        enabled: true
        # default in the elasticsearch chart is elastic
        kibanaUsername: "<USERNAME>"
        kibanaPassword: "<PASSWORD>"
      tls:
        # Instruct kibana to connect to elastic over https
        enabled: true
        # Bit of a catch 22, as you will need to know the name upfront of your release
        existingSecret: RELEASENAME-elasticsearch-coordinating-crt # or just 'elasticsearch-coordinating-crt' if the release name happens to be 'elasticsearch'
        # As the certs are auto-generated, they are pemCerts so set to true
        usePemCerts: true
```

### What do you see instead?

Could not find any parameters to enable encryption key
