### ISSUE TITLE
[bitnami/postgresql] Seems I'm unable to add a custom pg_hba.conf file when installing the PostgreSQL helm chart

### ISSUE THREAD

**Issue by kometen** [bitnami/charts#23621]
### Name and Version

bitnami/postgresql

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I am installing the bitnami PostgreSQL helm chart on a single microk8s node on ubuntu 22.04 LTS. I have tried to create a custom `pg_hba.conf` file but it seems I am not issuing the correct syntax.

Chart.yaml:

```yaml
dependencies:
  - name: postgresql
    appVersion: "16.2.0"
    version: "14.0.5"
    repository: "oci://registry-1.docker.io/bitnamicharts"
```

### Are you using any custom parameters or values?

values.yaml:

```yaml
global:
  postgresql:
    auth:
      username: "write_user"
      database: "marketing"

primary:
  pgHbaConfiguration: |-
    # TYPE  DATABASE        USER             ADDRESS                METHOD

    # "local" is for Unix domain socket connections only
    local   all             all                                     trust
    # IPv4 local connections:
    #host    all             all              127.0.0.1/32           trust
    # IPv6 local connections:
    #host    all             all              ::1/128                trust
    # Allow replication connections from localhost, by a user with the
    # replication privilege.
    local   replication     all                                     trust
    host    replication     all              127.0.0.1/32           trust
    host    replication     all              ::1/128                trust

    host    {{ .Values.global.postgresql.auth.database }}            {{ .Values.custom.read_only_user }} ::0/0                  trust
    host    {{ .Values.global.postgresql.auth.database }}            {{ .Values.custom.read_only_user }} 0.0.0.0/0              trust
    host    {{ .Values.global.postgresql.auth.database }}            {{ .Values.global.postgresql.auth.username }}        ::0/0                  scram-sha-256
    host    {{ .Values.global.postgresql.auth.database }}            {{ .Values.global.postgresql.auth.username }}        0.0.0.0/0              scram-sha-256

    host    all             all              0.0.0.0/0              reject
    host    all             all              ::0/0                  reject

    # IPv4 local connections:
    # IPv6 local connections:
    # Unix socket connections:
    local   all             postgres                                trust
    # Enable streaming replication with wal2json:
    host    replication     all             127.0.0.1/32            trust

  initdb:
    scripts:
      local_init_script.sql: |
        create role {{ .Values.custom.read_only_user }} login;

custom:
  read_only_user: "readonly_user"
```

### What is the expected behavior?

Install and log into the database. As you can see `global.postgresql.auth.database`- and `username` in `values.yaml` is used to specify user and database during installation.

```console
$ microk8s helm install postgresql . --namespace foo 

$ microk8s kubectl get pods --namespace foo
NAME           READY   STATUS    RESTARTS   AGE
postgresql-0   1/1     Running   0          4m6s

$ microk8s kubectl exec --namespace foo postgresql-0 -it -- /bin/bash
I have no name!@postgresql-0:/$

$ env | grep -i pass
POSTGRES_PASSWORD=wd1Vfbsz7h
POSTGRES_POSTGRES_PASSWORD=wn4iviJE1P

$ psql postgres://postgres@localhost/marketing
Password for user postgres:
psql (16.2)
Type "help" for help.

marketing=# \du
                              List of roles
 Role name  |                         Attributes
------------+------------------------------------------------------------
 postgres   | Superuser, Create role, Create DB, Replication, Bypass RLS
 write_user | Create DB
```

### What do you see instead?

Apparently `pg_hba.conf` is not read from `values.yaml` but created from scratch.

```
marketing=# table pg_hba_file_rules;
 rule_number |                file_name                 | line_number | type  | database | user_name |  address  |                 netmask                 | auth_method | options | error
-------------+------------------------------------------+-------------+-------+----------+-----------+-----------+-----------------------------------------+-------------+---------+-------
           1 | /opt/bitnami/postgresql/conf/pg_hba.conf |           1 | host  | {all}    | {all}     | 0.0.0.0   | 0.0.0.0                                 | md5         |         |
           2 | /opt/bitnami/postgresql/conf/pg_hba.conf |           2 | host  | {all}    | {all}     | ::        | ::                                      | md5         |         |
           3 | /opt/bitnami/postgresql/conf/pg_hba.conf |           3 | local | {all}    | {all}     |           |                                         | md5         |         |
           4 | /opt/bitnami/postgresql/conf/pg_hba.conf |           4 | host  | {all}    | {all}     | 127.0.0.1 | 255.255.255.255                         | md5         |         |
           5 | /opt/bitnami/postgresql/conf/pg_hba.conf |           5 | host  | {all}    | {all}     | ::1       | ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff | md5         |         |
(5 rows)

```

### Additional information

I have also tried to apply the custom `pg_hba.conf` using `ConfigMap` as suggested by [this thread][1] on Stackoverflow but it did not work eiither for me.

[1]: https://stackoverflow.com/a/74345705/319826

**Comment by kometen** [comment]
If I move the settings to the file conf/pg_config.yaml:

```
primary:
  pgHbaConfiguration: |-
    # TYPE  DATABASE        USER             ADDRESS                METHOD

    # "local" is for Unix domain socket connections only
    local   all             all                                     trust
    # IPv4 local connections:
    #host    all             all              127.0.0.1/32           trust
    # IPv6 local connections:
    #host    all             all              ::1/128                trust
    # Allow replication connections from localhost, by a user with the
    # replication privilege.
    local   replication     all                                     trust
    host    replication     all              127.0.0.1/32           trust
    host    replication     all              ::1/128                trust

    host    {{ .Values.global.postgresql.auth.database }}            read_only_user ::0/0                  trust
    host    {{ .Values.global.postgresql.auth.database }}            read_only_user 0.0.0.0/0              trust
    host    {{ .Values.global.postgresql.auth.database }}            {{ .Values.global.postgresql.auth.username }}        ::0/0                  scram-sha-256
    host    {{ .Values.global.postgresql.auth.database }}            {{ .Values.global.postgresql.auth.username }}        0.0.0.0/0              scram-sha-256

    host    all             all              0.0.0.0/0              reject
    host    all             all              ::0/0                  reject

    # IPv4 local connections:
    # IPv6 local connections:
    # Unix socket connections:
    local   all             postgres                                trust
    # Enable streaming replication with wal2json:
    host    replication     all             127.0.0.1/32            trust

  initdb:
    scripts:
      local_init_script.sql: |
        create role read_only_user login;
```

And change `helm install` from `.` to `bitnami/postgresql`

```
microk8s helm install postgresql bitnami/postgresql --namespace foo -f values.yaml -f conf/pg_config.yaml
```
it installs the custom pg_hba.conf.

**Comment by kometen** [comment]
I believe I can close this. Being fairly new to helm some implicit "mechanics" takes place beyond my knowledge. I initally created a `helm create project` when diving into helm and I modified Chart.yaml, values.yaml etc. for this helm chart. Using `bitnami/postgresql` later makes it work as expected.

```
microk8s helm install postgresql . --namespace foo
microk8s helm install postgresql bitnami/postgresql --namespace foo -f values.yaml -f conf/pg_conf.yaml
```

What confused me was that I could change default database and user with

```
global:
  postgresql:
    auth:
      username: "write_user"
      database: "marketing"
```

So I assumed it also would work with a custom pg_hba.conf.
