### ISSUE TITLE
[bitnami/postgres-ha] Allow additional Volume mounts

### ISSUE THREAD

**Issue by killerzwelch** [bitnami/charts#2363]
**Which chart**:
[bitnami/postgres-ha]

**Is your feature request related to a problem? Please describe.**
We want to internally host a Kubernetes environment for different departments. Various applications belong to the standard set. Postgresql is part of it. As we do not have control over data and data amount we cannot forsee how much space is needed for now and the future. My aim would be to ask the new user for space requirement so that we can create a VMDK, PV, PVC for them and create a new tablespace so that they have a separated storage.

**Describe the solution you'd like**
define a list of pvcs and mount points so that we can add storage for every application separatly

**Describe alternatives you've considered**
define ridiculous high amount of storage so that all applications share the same space, which would lead somewhen to problems

**Additional context**

**Comment by dani8art** [comment]
Hi @killerzwelch the idea would be to have something like:

```yaml
postgresql:
  ## Array to add extra volumes
  ##
  extraVolumes: []

  ## Array to add extra mounts (normally used with extraVolumes)
  ##
  extraVolumeMounts: []
```
