### ISSUE TITLE
[bitnami/redis] Enable the PVC label configuration

### ISSUE THREAD

**Issue by MauroSoli** [bitnami/charts#23732]
### Name and Version

bitnami/redis 7.2.4

### What is the problem this feature will solve?

It's not possible to manage the PVC labels using the bitnami/redis Helm Chart.
This could be a problem in some cases, e.g.: PVC labels are used to manage snapshot scheduling by many software.

### What is the feature you are proposing to solve the problem?

This feature allows to add one or more labels on the created PVC.

**Comment by im-jinxinwang** [comment]
@MauroSoli 
```yaml
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
``

**Comment by javsalgar** [comment]
Hi!

Did you try master.persistence.labels and replica.persistence.labels?

**Comment by MauroSoli** [comment]
Hi all, thanks for the help.
 
I will give you some context: I use the Redis Sentinel setup, here is the replica.persistence and sentinel sections of my `values.yaml`:

```yaml
replica:
  replicaCount: 3
  persistence:
    storageClass: "gp3-retain"
    ## @param replica.persistence.accessModes Persistent Volume access modes
    ##
    accessModes:
      - ReadWriteOnce
    ## @param replica.persistence.size Persistent Volume size
    ##
    size: 8Gi
    ## @param replica.persistence.labels Additional custom labels for the PVC
    ##
    labels:
      snapshotScheduler: enabled
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 100Mi


sentinel:
  enabled: true
  image:
    repository: bitnami/redis-sentinel
    tag: 7.2.4-debian-11-r3
    ## Enable debug mode
    ##
    debug: false
  downAfterMilliseconds: 30000
  failoverTimeout: 120000
  ## @param sentinel.masterSet Master set name
  ##
  masterSet: master
  resources:
    limits:
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
```
 
 
I attempted to utilize the `commonLabels` but it did not function as expected: the labels were not successfully added to the PVC. Furthermore, this approach does not appear to be an optimal or clean solution.

**Comment by javsalgar** [comment]
Hi!

I see the issue. In sentinel/statefulset.yaml I see that the labels section is not set

```
      kind: PersistentVolumeClaim
      metadata:
        name: redis-data
        labels: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 10 }}
          app.kubernetes.io/component: node

```

It should be 

```
      kind: PersistentVolumeClaim
      metadata:
        name: redis-data
        {{- $claimLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.replica.persistence.labels .Values.commonLabels ) "context" . ) }}
        labels: {{- include "common.labels.matchLabels" ( dict "customLabels" $claimLabels "context" $ ) | nindent 10 }}
          app.kubernetes.io/component: node
```

Would you like to submit a PR updating the file?
