### ISSUE TITLE
[Bitnami/MongoDB] Cannot create root user on inital startup: Command createUser requires authentication

### ISSUE THREAD

**Issue by mmkonrad** [bitnami/charts#23744]
### Name and Version

bitnami/mongodb 14.9.4

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Install chart with:
```
helm install mongodb-test-release \
mongodb \
--values mongodb/values.yaml \
--values mongodb/my_values.yaml \
--set auth.rootPassword=secretpassword
```

1.1 chart is locally extracted to analyze it -> BUT NO CHANGES HAVE BEEN MADE!

2. Watch the logs until I see the log output as listed below

3. Cannot log in locally (from within the pod) to mongodb using `mongosh` due to users not being created at initial start

### Are you using any custom parameters or values?

```yaml
---
# Global parameters
global:
  imagePullSecrets:
    - <SECRET_PLACEHOLDER>


# Common parameters
nameOverride: employee-info-subscriber-mail-mongodb


# MongoDB Architecture (Standalone (Deployment vs StatefulSet) vs ReplicaSet)
architecture: standalone
useStatefulSet: true

# MongoDB parameters
image.registry: <MY_REGISTRY>
image.repository: bitnami/mongodb
image.tag: 7.0.5

auth:
  usernames:
    - mongodb_user
  passwords:
    - tbd
  databases:
    - consumers

image.debug: true

# MongoDB configuration file
configuration: |-2
  # mongod.conf
  # for documentation of all options, see:
  #   http://docs.mongodb.org/manual/reference/configuration-options/

  # where and how to store data.
  storage:
    dbPath: /bitnami/mongodb/data/db
    directoryPerDB: false

  # where to write logging data.
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
    path: /bitnami/mongodb/logs/mongodb.log
    verbosity: 0
    traceAllExceptions: true

  # network interfaces
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /bitnami/mongodb/tmp
    ipv6: false
    bindIpAll: true
    #bindIp:

  # replica set options
  #replication:
    #replSetName: replicaset
    #enableMajorityReadConcern: true

  # sharding options
  #sharding:
    #clusterRole:

  # process management options
  processManagement:
     fork: false
     pidFilePath: /bitnami/mongodb/tmp/mongodb.pid

  # set parameter options
  setParameter:
     enableLocalhostAuthBypass: false

  # security options
  security:
    authorization: enabled
    #keyFile: replace_me



# MongoDB StatefulSet parameters
replicaCount: 1
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 2Gi
readinessProbe:
  enabled: true
  timeoutSeconds: 20

livenessProbe:
  enabled: true
  timeoutSeconds: 20
  periodSeconds: 60

pdb.create: true
pdb.minAvailable: 1

# Security / Compliance parameters
podSecurityContext:
  fsGroup: null
containerSecurityContext:
  runAsUser: 1003210001
  readOnlyRootFilesystem: true


# Persistence parameters
persistence:
  storageClass: ebs-gp2-any-az
  size: 4Gi
  mountPath: /bitnami/mongodb/data
  subPath: data

extraVolumeMounts:
  - name: datadir
    mountPath: /.mongodb/mongosh
    subPath: mongosh
  - name: datadir
    mountPath: /bitnami/mongodb/logs
    subPath: logs
  - name: datadir
    mountPath: /bitnami/mongodb/tmp
    subPath: tmp

# RBAC parameters
serviceAccount.create: true
```

### What is the expected behavior?

I expect the users root and mongodb_user to be created.

After the creation and restart of mongodb I expect to be able to log in locally (from within the pod) using mongosh.

### What do you see instead?

```
[38;5;6mmongodb [38;5;5m15:26:30.13 [0m[38;5;2mINFO [0m ==> 
[38;5;6mmongodb [38;5;5m15:26:30.13 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami mongodb container[0m
[38;5;6mmongodb [38;5;5m15:26:30.13 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[38;5;6mmongodb [38;5;5m15:26:30.13 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[38;5;6mmongodb [38;5;5m15:26:30.13 [0m[38;5;2mINFO [0m ==> 
[38;5;6mmongodb [38;5;5m15:26:30.13 [0m[38;5;2mINFO [0m ==> ** Starting MongoDB setup **
[38;5;6mmongodb [38;5;5m15:26:30.15 [0m[38;5;2mINFO [0m ==> Validating settings in MONGODB_* env vars...
[38;5;6mmongodb [38;5;5m15:26:30.22 [0m[38;5;2mINFO [0m ==> Initializing MongoDB...
[38;5;6mmongodb [38;5;5m15:26:30.22 [0m[38;5;2mINFO [0m ==> Deploying MongoDB from scratch...
[38;5;6mmongodb [38;5;5m15:26:33.40 [0m[38;5;2mINFO [0m ==> Creating users...
[38;5;6mmongodb [38;5;5m15:26:33.40 [0m[38;5;2mINFO [0m ==> Creating root user...
Current Mongosh Log ID:	65d6162af723e3394119db0b
Connecting to:		mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.1.4
Using MongoDB:		7.0.5
Using Mongosh:		2.1.4

For mongosh info see: https://docs.mongodb.com/mongodb-shell/

test> Uncaught 
MongoServerError[Unauthorized]: Command createUser requires authentication
test> [38;5;6mmongodb [38;5;5m15:26:35.60 [0m[38;5;2mINFO [0m ==> Creating user 'mongodb_user'...
Current Mongosh Log ID:	65d6162c1285ece70435646f
Connecting to:		mongodb://<credentials>@127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.1.4
MongoServerError: Authentication failed.
```

### Additional information

When I comment the `security.authorization` field in the config, the users get created and I can log in locally (from within the pod).

But I want to have the authorization feature enabled.
