### ISSUE TITLE
[bitnami/supabase] All services are up and running, but many API calls result into HTTP 404 and HTTP 400

### ISSUE THREAD

**Issue by bartcode** [bitnami/charts#23778]
### Name and Version

bitnami/supabase 2.8.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I've deployed the Helm chart with at few options as possible. It must be said that I can't use port 80 for Kong, because another service is running on that port on the host.

### Are you using any custom parameters or values?

The only options I currently use are as follows:

```yaml
publicURL: "http://xx.xx.xx.xx:3000" 
jwt:
  existingSecret: jwt-secret
studio:
  publicURL: "http://xx.xx.xx.xx:3000"
  service:
    ports:
      http: 3000
    type: LoadBalancer
kong:
  service:
    ports:
      proxyHttp: 7007
      proxyHttps: 7008
```

I've also desperately configured the /auth/v1 on my ingress controller to go to the supabase-auth service, /rest/v1 to supabase-rest, etc. (with and without rewrites to `/`)

### What is the expected behavior?

HTTP 200 on API calls.

### What do you see instead?

The Supabase studio UI seems to work just fine. It's only when API calls are made in the background that I can see many HTTP 404s and 400s. Oddly enough, I did manage to get _some_ API calls to work.

I'm getting 404s for:
- `/project/default/auth/undefined/projects/default/upgrade/eligibility`. Also don't know why it says `undefined` here.
- `/api/projects/default/billing/addons`
- `/api/integrations/default-org-slug?expand=true`
- `/auth/v1/admin/users`
- `/storage/v1/object/test/test/config`

But I _am_ getting HTTP 200s for:
- `/api/auth/default/users?limit=10&offset=0&keywords=`
- `/api/projects`
- `/api/props/project/default/api`
- `/api/storage/default/buckets`

I expect there to be something off with Kong as it doesn't seem to connect to the underlying APIs. But I've found it quite hard to debug, because I can't use `curl` in any of the Kong pods.

### Additional information

If I use `curl` from the Postgres pod, I can make successful API calls to all the separate services. So, again, it seems like Kong is the bottleneck here.
