### ISSUE TITLE
[bitnami/clickhouse] extraOverrides not applied

### ISSUE THREAD

**Issue by platzhersh** [bitnami/charts#23781]
### Name and Version

bitnami/clickhouse 3.1.5

### What architecture are you using?

None

### What steps will reproduce the bug?

I am using `extraOverrides` in my bitnami/clickhouse values.yaml to disable some logs (for my disk spaces sake):

fleet.yaml
```yaml
helm:
  repo: https://charts.bitnami.com/bitnami
  chart: clickhouse
  version: 3.1.5
  releaseName: clickhouse
  valuesFiles:
    - values.yaml
```

values.yaml
```yaml
extraOverrides: |
  <clickhouse>
    <!-- disable greedy logs -->
    <asynchronous_metric_log remove="1"/>
    <trace_log remove="1"/>
  </clickhouse>
```

I deployed the changes, but I am not seeing an effect. Where should this config be found inside the pod?

https://artifacthub.io/packages/helm/bitnami/clickhouse?modal=values&path=extraOverrides

### Are you using any custom parameters or values?

values.yaml
```yaml
extraOverrides: |
  <clickhouse>
    <!-- disable greedy logs -->
    <asynchronous_metric_log remove="1"/>
    <trace_log remove="1"/>
  </clickhouse>
```

### What is the expected behavior?

I would expect the config to be applied, and therefore no `trace_log` or `asynchronous_metric_log` data to be collected.

### What do you see instead?

`trace_log` or `asynchronous_metric_log` data is still being collected
