### ISSUE TITLE
bitnami/elasticsearch chart required for snapshot operations - to use azure storage to store backups

### ISSUE THREAD

**Issue by jeffersonjerome19** [bitnami/charts#23782]
### Name and Version

elasticsearch:19.19.2

### What architecture are you using?

None

### What steps will reproduce the bug?

1. we have below chart for file system snapshot repository
```yaml
extraVolumes:
  - name: snapshot-repository
    nfs:
      server: nfs.example.com # Please change this to your NFS server
      path: /share1
extraVolumeMounts:
  - name: snapshot-repository
    mountPath: /snapshots
snapshotRepoPath: "/snapshots"
```
2. we require chart to use azure storage for snapshot repository
3. Please assist on this

### What do you see instead?

we have chart only for file system repository
```yaml
extraVolumes:
  - name: snapshot-repository
    nfs:
      server: nfs.example.com # Please change this to your NFS server
      path: /share1
extraVolumeMounts:
  - name: snapshot-repository
    mountPath: /snapshots
snapshotRepoPath: "/snapshots"
```
