### ISSUE TITLE
[bitnami/prometheus-operator] Define recording and alerting rules (PrometheusRule) for a Prometheus instance

### ISSUE THREAD

**Issue by evgmoskalenko** [bitnami/charts#2381]
**Which chart**:

* [bitnami/prometheus-operator]

Hello, how to define alerting rules (PrometheusRule) for a Prometheus instance?

* https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusrule
* https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusrulespec

I did not find anything like this in the chart templates.

It will be better using something like this:

```
additionalPrometheusRules:
  - name: custom-rules-file
    groups:
      - name: prometheus-config
        rules:
          - alert: PrometheusConfigurationReload
            expr: prometheus_config_last_reload_successful != 1
            for: 5m
            labels:
              severity: error
            annotations:
              summary: "Prometheus configuration reload (instance {{ $labels.instance }})"
              description: "Prometheus configuration reload error\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - name: custom-node-exporter-rules
        rules:
          - alert: PhysicalComponentTooHot
            expr: node_hwmon_temp_celsius > 75
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Physical component too hot (instance {{ $labels.instance }})"
              description: "Physical hardware component too hot\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          - alert: NodeOvertemperatureAlarm
            expr: node_hwmon_temp_alarm == 1
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Node overtemperature alarm (instance {{ $labels.instance }})"
              description: "Physical node temperature alarm triggered\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```
