### ISSUE TITLE
[bitnami/oauth2-proxy] Why is there no helm chart?

### ISSUE THREAD

**Issue by Cellebyte** [bitnami/charts#2384]
**Describe the solution you'd like**
Create A Simple Helm chart which enables oauth2-proxy deployments.

The image is already built by bitnami.
Is their a reason why that proxy is not available as a helm chart?

[https://bitnami.com/stack/oauth2-proxy/containers](https://bitnami.com/stack/oauth2-proxy/containers)

**Additional context**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oauth2-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=github
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        # Register a new application
        # https://github.com/settings/applications/new
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: <Client ID>
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: <Client Secret>
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: SECRET
        image: docker.io/bitnami/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: oauth2-proxy
  name: oauth2-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app.kubernetes.io/name: oauth2-proxy
```
