### ISSUE TITLE
[bitnami/influxdb] mapping key "mountPath" already defined

### ISSUE THREAD

**Issue by sveinpj** [bitnami/charts#23861]
### Name and Version

bitnami/influxdb 5.17.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Volumemount "empty-dir" seems funky in chart
```yaml
volumeMounts:
  - name: empty-dir
    mountPath: /tmp
    subPath: tmp-dir
  - name: empty-dir
    mountPath: /opt/bitnami/influxdb/etc 
    mountPath: app-conf-dir
  - name: data
    mountPath: /bitnami/influxdb
```

### What is the expected behavior?

Release reconciliation succeeded

### What do you see instead?
```
Helm upgrade failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:...
line 150: mapping key "mountPath" already defined at line 149
```
### Additional information
```
Last Applied Revision:           5.16.3 (working)
Last Attempted Revision:         5.17.0 (not working)

flux: v2.0.0
helm-controller: v0.35.0
image-automation-controller: v0.35.0
image-reflector-controller: v0.29.0
kustomize-controller: v1.0.0
notification-controller: v1.0.0
source-controller: v1.0.0
```
