### ISSUE TITLE
[bitnami/minio] after setting the ingress.path to /minio-path/ , the static resource cannot be reached

### ISSUE THREAD

**Issue by LiDaiyan** [bitnami/charts#23872]
### Name and Version

bitnami/minio:13.6.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

this is the values 

```
ingress:
  enabled: true
  apiVersion: ""
  ingressClassName: "my-traefik"
  hostname: localhost
  path: /minio-console
  pathType: ImplementationSpecific
```

and  the status of
http://localhost/minio-console/ is 200

but it will request the static resource from root path, and it can not be loaded because no ingress for the static resources.

### Are you using any custom parameters or values?

no

### What is the expected behavior?

I want the static resource can be loaded.

### What do you see instead?

because the static resource can not be loaded, there is nothing on the page.
