### ISSUE TITLE
[bitnami/kube-prometheus] Prometheus Shard Statefulset not comes up

### ISSUE THREAD

**Issue by pomland-94** [bitnami/charts#23896]
### Name and Version

bitnami/kube-prometheus:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Hey,
when I try to setup kube-prometheus on a clean Kubernetes Cluster the Shards don't come up, I get the following error:

```console
$ kubectl --namespace prometheus describe statefulset.apps/prometheus-prometheus-kube-prometheus-prometheus-shard-1
Name:               prometheus-prometheus-kube-prometheus-prometheus-shard-1
Namespace:          prometheus
CreationTimestamp:  Sat, 24 Feb 2024 14:29:05 +0100
Selector:           app.kubernetes.io/instance=prometheus-kube-prometheus-prometheus,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,operator.prometheus.io/name=prometheus-kube-prometheus-prometheus,operator.prometheus.io/shard=1,prometheus=prometheus-kube-prometheus-prometheus
Labels:             app.kubernetes.io/component=prometheus
                    app.kubernetes.io/instance=prometheus
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=kube-prometheus
                    app.kubernetes.io/version=0.71.2
                    helm.sh/chart=kube-prometheus-8.28.2
                    managed-by=prometheus-operator
                    operator.prometheus.io/mode=server
                    operator.prometheus.io/name=prometheus-kube-prometheus-prometheus
                    operator.prometheus.io/shard=1
Annotations:        meta.helm.sh/release-name: prometheus
                    meta.helm.sh/release-namespace: prometheus
                    prometheus-operator-input-hash: 4956232721795248389
Replicas:           3 desired | 0 total
Update Strategy:    RollingUpdate
Pods Status:        0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app.kubernetes.io/component=prometheus
                    app.kubernetes.io/instance=prometheus-kube-prometheus-prometheus
                    app.kubernetes.io/managed-by=prometheus-operator
                    app.kubernetes.io/name=prometheus
                    app.kubernetes.io/version=2.48.1
                    operator.prometheus.io/name=prometheus-kube-prometheus-prometheus
                    operator.prometheus.io/shard=1
                    prometheus=prometheus-kube-prometheus-prometheus
  Annotations:      kubectl.kubernetes.io/default-container: prometheus
  Service Account:  prometheus-kube-prometheus-prometheus
  Init Containers:
   init-config-reloader:
    Image:      docker.io/bitnami/prometheus-operator:0.71.2-debian-12-r7
    Port:       8080/TCP
    Host Port:  0/TCP
    Command:
      /bin/prometheus-config-reloader
    Args:
      --watch-interval=0
      --listen-address=:8080
      --config-file=/etc/prometheus/config/prometheus.yaml.gz
      --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
      --watched-dir=/etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0
    Limits:
      cpu:     10m
      memory:  50Mi
    Requests:
      cpu:     10m
      memory:  50Mi
    Environment:
      POD_NAME:   (v1:metadata.name)
      SHARD:     1
    Mounts:
      /etc/prometheus/config from config (rw)
      /etc/prometheus/config_out from config-out (rw)
      /etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0 from prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0 (rw)
  Containers:
   prometheus:
    Image:           docker.io/bitnami/prometheus:2.49.1-debian-12-r9
    Port:            9090/TCP
    Host Port:       0/TCP
    SeccompProfile:  RuntimeDefault
    Args:
      --web.console.templates=/etc/prometheus/consoles
      --web.console.libraries=/etc/prometheus/console_libraries
      --config.file=/etc/prometheus/config_out/prometheus.env.yaml
      --web.enable-lifecycle
      --web.external-url=http://prometheus-kube-prometheus-prometheus.prometheus:9090/
      --web.route-prefix=/
      --storage.tsdb.retention.time=90d
      --storage.tsdb.path=/prometheus
      --web.config.file=/etc/prometheus/web_config/web-config.yaml
    Liveness:     http-get http://:web/-/healthy delay=0s timeout=3s period=10s #success=1 #failure=10
    Readiness:    http-get http://:web/-/ready delay=0s timeout=3s period=10s #success=1 #failure=10
    Startup:      http-get http://:web/-/ready delay=0s timeout=3s period=15s #success=1 #failure=60
    Environment:  <none>
    Mounts:
      /etc/prometheus/certs from tls-assets (ro)
      /etc/prometheus/config_out from config-out (ro)
      /etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0 from prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0 (rw)
      /etc/prometheus/web_config/web-config.yaml from web-config (ro,path="web-config.yaml")
      /prometheus from prometheus-prometheus-kube-prometheus-prometheus-db (rw,path="prometheus-db")
   config-reloader:
    Image:           docker.io/bitnami/prometheus-operator:0.71.2-debian-12-r7
    Port:            8080/TCP
    Host Port:       0/TCP
    SeccompProfile:  RuntimeDefault
    Command:
      /bin/prometheus-config-reloader
    Args:
      --listen-address=:8080
      --reload-url=http://127.0.0.1:9090/-/reload
      --config-file=/etc/prometheus/config/prometheus.yaml.gz
      --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
      --watched-dir=/etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0
    Limits:
      cpu:     10m
      memory:  50Mi
    Requests:
      cpu:      10m
      memory:   50Mi
    Liveness:   tcp-socket :reloader-web delay=10s timeout=5s period=10s #success=1 #failure=6
    Readiness:  tcp-socket :reloader-web delay=15s timeout=5s period=20s #success=1 #failure=6
    Environment:
      POD_NAME:   (v1:metadata.name)
      SHARD:     1
    Mounts:
      /etc/prometheus/config from config (rw)
      /etc/prometheus/config_out from config-out (rw)
      /etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0 from prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0 (rw)
  Volumes:
   config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-prometheus-kube-prometheus-prometheus
    Optional:    false
   tls-assets:
    Type:                Projected (a volume that contains injected data from multiple sources)
    SecretName:          prometheus-prometheus-kube-prometheus-prometheus-tls-assets-0
    SecretOptionalName:  <nil>
   config-out:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
   prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0
    Optional:  false
   web-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-prometheus-kube-prometheus-prometheus-web-config
    Optional:    false
Volume Claims:
  Name:          prometheus-prometheus-kube-prometheus-prometheus-db
  StorageClass:  rook-cephfs
  Labels:        <none>
  Annotations:   <none>
  Capacity:      25Gi
  Access Modes:  [ReadWriteMany]
Events:
  Type     Reason            Age                   From                    Message
  ----     ------            ----                  ----                    -------
  Normal   SuccessfulCreate  2m36s                 statefulset-controller  create Claim prometheus-prometheus-kube-prometheus-prometheus-db-prometheus-prometheus-kube-prometheus-prometheus-shard-1-0 Pod prometheus-prometheus-kube-prometheus-prometheus-shard-1-0 in StatefulSet prometheus-prometheus-kube-prometheus-prometheus-shard-1 success
  Warning  FailedCreate      74s (x15 over 2m36s)  statefulset-controller  create Pod prometheus-prometheus-kube-prometheus-prometheus-shard-1-0 in StatefulSet prometheus-prometheus-kube-prometheus-prometheus-shard-1 failed error: Pod "prometheus-prometheus-kube-prometheus-prometheus-shard-1-0" is invalid: metadata.labels: Invalid value: "prometheus-prometheus-kube-prometheus-prometheus-shard-1-76c9dc7c9b": must be no more than 63 characters
[root::admingw-01]
~/yaml/prometheus-operator:
```

### Are you using any custom parameters or values?

```yaml
operator:
  enabled: true
  containerSecurityContext:
    enabled: true
    seLinuxOptions: null
    runAsUser: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
  serviceMonitor:
    enabled: true
  kubeletService:
    enabled: true
    namespace: kube-system
  prometheusConfigReloader:
    containerSecurityContext:
      enabled: true
      seLinuxOptions: null
      runAsUser: 1001
      runAsNonRoot: true
      privileged: false
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: "RuntimeDefault"
prometheus:
  enabled: true
  serviceAccount:
    create: true
    automountServiceAccountToken: false
  containerSecurityContext:
    enabled: true
    seLinuxOptions: null
    runAsUser: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
  serviceMonitor:
    enabled: true
  ingress:
    enabled: false
    hostname: prometheus.local
    annotations: {}
    ingressClassName: ""
    tls: false
    selfSigned: false
  externalUrl: ""
  enableAdminAPI: false
  ## @param prometheus.enableFeatures Enable access to Prometheus disabled features.
  ## ref: https://prometheus.io/docs/prometheus/latest/disabled_features/
  ##
  enableFeatures: []
  ## @param prometheus.alertingEndpoints Alertmanagers to which alerts will be sent
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#alertmanagerendpoints
  ##
  alertingEndpoints: []
  retention: 90d
  ## @param prometheus.retentionSize Maximum size of metrics
  ##
  disableCompaction: false
  walCompression: false
  replicaCount: 3
  shards: 5
  persistence:
    enabled: true
    storageClass: "rook-cephfs"
    accessModes:
      - ReadWriteMany
    size: 25Gi
  ## @param prometheus.additionalPrometheusRules PrometheusRule defines recording and alerting rules for a Prometheus instance.
  ## - name: custom-recording-rules
  ##   groups:
  ##     - name: sum_node_by_job
  ##       rules:
  ##         - record: job:kube_node_labels:sum
  ##           expr: sum(kube_node_labels) by (job)
  ##     - name: sum_prometheus_config_reload_by_pod
  ##       rules:
  ##         - record: job:prometheus_config_last_reload_successful:sum
  ##           expr: sum(prometheus_config_last_reload_successful) by (pod)
  ## - name: custom-alerting-rules
  ##   groups:
  ##     - name: prometheus-config
  ##       rules:
  ##         - alert: PrometheusConfigurationReload
  ##           expr: prometheus_config_last_reload_successful > 0
  ##           for: 1m
  ##           labels:
  ##             severity: error
  ##           annotations:
  ##             summary: "Prometheus configuration reload (instance {{ $labels.instance }})"
  ##             description: "Prometheus configuration reload error\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  ##     - name: custom-node-exporter-alerting-rules
  ##       rules:
  ##         - alert: PhysicalComponentTooHot
  ##           expr: node_hwmon_temp_celsius > 75
  ##           for: 5m
  ##           labels:
  ##             severity: warning
  ##           annotations:
  ##             summary: "Physical component too hot (instance {{ $labels.instance }})"
  ##             description: "Physical hardware component too hot\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  ##         - alert: NodeOvertemperatureAlarm
  ##           expr: node_hwmon_temp_alarm == 1
  ##           for: 5m
  ##           labels:
  ##             severity: critical
  ##           annotations:
  ##             summary: "Node overtemperature alarm (instance {{ $labels.instance }})"
  ##             description: "Physical node temperature alarm triggered\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  ##
  ## @param prometheus.additionalArgs Allows setting additional arguments for the Prometheus container
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.Prometheus
  ##
  additionalArgs: []
  additionalPrometheusRules: []
  ## Note that the prometheus will fail to provision if the correct secret does not exist.
  ## @param prometheus.additionalScrapeConfigs.enabled Enable additional scrape configs
  ## @param prometheus.additionalScrapeConfigs.type Indicates if the cart should use external additional scrape configs or internal configs
  ## @param prometheus.additionalScrapeConfigs.external.name Name of the secret that Prometheus should use for the additional external scrape configuration
  ## @param prometheus.additionalScrapeConfigs.external.key Name of the key inside the secret to be used for the additional external scrape configuration
  ## @param prometheus.additionalScrapeConfigs.internal.jobList A list of Prometheus scrape jobs
  ##
  additionalScrapeConfigs:
    enabled: false
    type: external
    external:
      ## Name of the secret that Prometheus should use for the additional scrape configuration
      ##
      name: ""
      ## Name of the key inside the secret to be used for the additional scrape configuration.
      ##
      key: ""
    internal:
      jobList: []
  ## @param prometheus.additionalScrapeConfigsExternal.enabled Deprecated: Enable additional scrape configs that are managed externally to this chart
  ## @param prometheus.additionalScrapeConfigsExternal.name Deprecated: Name of the secret that Prometheus should use for the additional scrape configuration
  ## @param prometheus.additionalScrapeConfigsExternal.key Deprecated: Name of the key inside the secret to be used for the additional scrape configuration
  ##
  additionalScrapeConfigsExternal:
    enabled: false
    name: ""
    key: ""
  thanos:
    create: false
    containerSecurityContext:
      enabled: true
      seLinuxOptions: null
      runAsUser: 1001
      runAsNonRoot: true
      privileged: false
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: "RuntimeDefault"
    ingress:
      enabled: false
      hostname: thanos.prometheus.local
      annotations: {}
      ingressClassName: ""
      tls: false
      selfSigned: false
  configReloader:
    service:
      enabled: false
    serviceMonitor:
      enabled: false
alertmanager:
  enabled: true
  serviceAccount:
    create: true
  containerSecurityContext:
    enabled: true
    seLinuxOptions: null
    runAsUser: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
  serviceMonitor:
    enabled: true
  ingress:
    enabled: false
    hostname: alertmanager.local
    annotations: {}
    ingressClassName: ""
    tls: false
    selfSigned: false
  externalUrl: ""
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
        - match:
            alertname: Watchdog
          receiver: 'null'
    receivers:
      - name: 'null'
  ## @param alertmanager.templateFiles Extra files to be added inside the `alertmanager-{{ template "kube-prometheus.alertmanager.fullname" . }}` secret.
  ##
  templateFiles: {}
  externalConfig: false
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: "rook-cephfs"
    accessModes:
      - ReadWriteMany
    size: 25Gi
exporters:
  node-exporter:
    enabled: true
  kube-state-metrics:
    enabled: true
node-exporter:
  service:
    labels:
      jobLabel: node-exporter
  serviceMonitor:
    enabled: true
    jobLabel: jobLabel
  extraArgs:
    collector.filesystem.ignored-mount-points: "^/(dev|proc|sys|var/lib/docker/.+)($|/)"
    collector.filesystem.ignored-fs-types: "^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$"
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      value: ""
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Equal"
      value: ""
      effect: "NoSchedule"
kube-state-metrics:
  serviceMonitor:
    enabled: true
    honorLabels: true
kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    https: true
blackboxExporter:
  enabled: true
  replicaCount: 1
  configuration: |
    "modules":
      "http_2xx":
        "http":
          "preferred_ip_protocol": "ip4"
        "prober": "http"
      "http_post_2xx":
        "http":
          "method": "POST"
          "preferred_ip_protocol": "ip4"
        "prober": "http"
      "irc_banner":
        "prober": "tcp"
        "tcp":
          "preferred_ip_protocol": "ip4"
          "query_response":
          - "send": "NICK prober"
          - "send": "USER prober prober prober :prober"
          - "expect": "PING :([^ ]+)"
            "send": "PONG ${1}"
          - "expect": "^:[^ ]+ 001"
      "pop3s_banner":
        "prober": "tcp"
        "tcp":
          "preferred_ip_protocol": "ip4"
          "query_response":
          - "expect": "^+OK"
          "tls": true
          "tls_config":
            "insecure_skip_verify": false
      "ssh_banner":
        "prober": "tcp"
        "tcp":
          "preferred_ip_protocol": "ip4"
          "query_response":
          - "expect": "^SSH-2.0-"
      "tcp_connect":
        "prober": "tcp"
        "tcp":
          "preferred_ip_protocol": "ip4"
  serviceAccount:
    create: true
    automountServiceAccountToken: false
  containerSecurityContext:
    enabled: true
    seLinuxOptions: null
    runAsUser: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
kubeApiServer:
  enabled: true
kubeControllerManager:
  enabled: true
  namespace: kube-system
  service:
    enabled: true
    ports:
      http: 10252
    targetPorts:
      http: 10252
  serviceMonitor:
    https: false
kubeScheduler:
  enabled: true
  namespace: kube-system
  service:
    enabled: true
    ports:
      http: 10251
    targetPorts:
      http: 10251
  serviceMonitor:
    https: false
coreDns:
  enabled: true
  namespace: kube-system
  service:
    enabled: true
    ports:
      http: 9153
    targetPorts:
      http: 9153
kubeProxy:
  enabled: true
  namespace: kube-system
  service:
    enabled: true
    ports:
      http: 10249
    targetPorts:
      http: 10249
  serviceMonitor:
    https: false
rbac:
  create: true
  pspEnabled: true
```

### What do you see instead?

```bash
Events:
  Type     Reason            Age                   From                    Message
  ----     ------            ----                  ----                    -------
  Normal   SuccessfulCreate  2m36s                 statefulset-controller  create Claim prometheus-prometheus-kube-prometheus-prometheus-db-prometheus-prometheus-kube-prometheus-prometheus-shard-1-0 Pod prometheus-prometheus-kube-prometheus-prometheus-shard-1-0 in StatefulSet prometheus-prometheus-kube-prometheus-prometheus-shard-1 success
  Warning  FailedCreate      74s (x15 over 2m36s)  statefulset-controller  create Pod prometheus-prometheus-kube-prometheus-prometheus-shard-1-0 in StatefulSet prometheus-prometheus-kube-prometheus-prometheus-shard-1 failed error: Pod "prometheus-prometheus-kube-prometheus-prometheus-shard-1-0" is invalid: metadata.labels: Invalid value: "prometheus-prometheus-kube-prometheus-prometheus-shard-1-76c9dc7c9b": must be no more than 63 characters
```
