### ISSUE TITLE
[bitnami/airflow] Install additionals python modules

### ISSUE THREAD

**Issue by alekseytivonchik** [bitnami/charts#23902]
### Name and Version

bitnami/airflow-16.7.0

### What is the problem this feature will solve?

There is a need to install additional python modules to run some DAGs, in particular the mlflow module, something like:
`pip install mlflow`

### What is the feature you are proposing to solve the problem?

Is it possible to perform the installation by specifying the list of modules in the chart or using some other method?

**Comment by alekseytivonchik** [comment]
Hi! Workaround that work for me, add volumes to the airflow helm chart:
```
## @param extraVolumeMounts Optionally specify extra list of additional volumeMounts for all the Airflow pods
##
extraVolumeMounts:
  - name: apache-airflow-requirements
    mountPath: /bitnami/python/requirements.txt
    subPath: requirements.txt
## @param extraVolumes Optionally specify extra list of additional volumes for the all the Airflow pods
##
extraVolumes:
  - name: apache-airflow-requirements
    configMap:
      name: apache-airflow-requirements
```
ConfigMap - create manualy:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-airflow-requirements
  namespace: airflow
data:
  requirements.txt: |
    mlflow==2.10.2
```
