### ISSUE TITLE
[bitnami/jenkins] nil pointer evaluating interface {}.cpu

### ISSUE THREAD

**Issue by busyboy77** [bitnami/charts#23945]
### Name and Version

bitnami/jenkins:12.9.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

this version is somewhat broken with default values, the error that we receive is like below:

```console
$ helm upgrade  --install --namespace jenkins --create-namespace --values values.yaml jenkins oci://registry-1.docker.io/bitnamicharts/jenkins
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/rke2/rke2.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/rancher/rke2/rke2.yaml
Release "jenkins" does not exist. Installing it now.
Pulled: registry-1.docker.io/bitnamicharts/jenkins:12.9.2
Digest: sha256:2b6fed1df09d8f9b4bddf925acdbff4170451dd340ac88b56c813e897651d000
Error: template: jenkins/templates/casc-cm.yaml:74:34: executing "jenkins/templates/casc-cm.yaml" at <.Values.agent.resources.limits.cpu>: nil pointer evaluating interface {}.cpu
```

### Are you using any custom parameters or values?

```YAML
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""
kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
commonLabels: {}
commonAnnotations: {}
clusterDomain: cluster.local
extraDeploy: []
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity
image:
  registry: docker.io
  repository: bitnami/jenkins
  tag: 2.440.1-debian-12-r0
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
jenkinsUser: user
jenkinsPassword: ""
jenkinsHost: ""
jenkinsHome: /bitnami/jenkins/home
javaOpts: []
disableInitialization: "no"
command: []
args: []
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
plugins:
   - kubernetes:3852.v41ea_166a_ed1b_
   - workflow-aggregator:590.v6a_d052e5a_a_b_5
   - git:4.13.0
   - configuration-as-code:1569.vb_72405b_80249
extraPlugins: []
latestPlugins: true
latestSpecifiedPlugins: false
skipImagePlugins: false
overridePlugins: false
overridePaths: ""
initScripts: {}
initScriptsCM: ""
initScriptsSecret: ""
initHookScripts: {}
initHookScriptsCM: ""
initHookScriptsSecret: ""
tls:
  autoGenerated: true
  usePemCerts: false
  existingSecret: ""
  password: ""
  passwordsSecret: ""
  resourcesPreset: "none"
  resources: {}
configAsCode:
  enabled: true
  extraConfigFiles: {}
  securityRealm: {}
  authorizationStrategy: {}
  security: {}
  extraJenkins: {}
  extraConfig: {}
  extraKubernetes: {}
  extraClouds: []
  existingConfigmap: ""
  autoReload:
    enabled: true
    initialDelay: 360
    reqRetries: 12
    interval: 10
    command: []
    args: []
    extraEnvVars: []
    extraEnvVarsSecret: ""
    extraEnvVarsCM: ""
    extraVolumeMounts: []
    containerSecurityContext:
      enabled: true
      seLinuxOptions: null
      runAsUser: 1001
      runAsNonRoot: true
      privileged: false
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: "RuntimeDefault"
agent:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/jenkins-agent
    tag: 0.3206.0-debian-12-r9
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
    debug: false
  templateLabel: "kubernetes-agent"
  podLabels: {}
  annotations: {}
  sidecars: []
  command: ""
  args: ""
  containerExtraEnvVars: []
  podExtraEnvVars: []
  extraAgentTemplate: {}
  extraTemplates: []
  resourcesPreset: "none"
  resources: {}
  containerSecurityContext:
    enabled: false
    seLinuxOptions: null
    runAsUser: ""
    runAsGroup: ""
    privileged: false
updateStrategy:
  type: RollingUpdate
priorityClassName: ""
schedulerName: ""
topologySpreadConstraints: []
automountServiceAccountToken: true
hostAliases: []
extraVolumes: []
extraVolumeMounts: []
sidecars: []
initContainers: []
lifecycleHooks: {}
podLabels: {}
podAnnotations: {}
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ""
  key: ""
  values: []
affinity: {}
nodeSelector: {}
tolerations: []
resourcesPreset: "none"
resources: {}
containerPorts:
  http: 8080
  https: 8443
  agentListener: 50000
podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
  fsGroup: 1001
containerSecurityContext:
  enabled: true
  seLinuxOptions: null
  runAsUser: 1001
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"
startupProbe:
  enabled: false
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 6
livenessProbe:
  enabled: true
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 6
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
customStartupProbe: {}
customLivenessProbe: {}
customReadinessProbe: {}
service:
  type: ClusterIP
  ports:
    http: 80
    https: 443
  nodePorts:
    http: ""
    https: ""
  clusterIP: ""
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster
  annotations: {}
  extraPorts: []
  sessionAffinity: None
  sessionAffinityConfig: {}
networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: true
  kubeAPIServerPorts: [443, 6443, 8443]
  extraIngress: []
  extraEgress: []
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
agentListenerService:
  enabled: true
  type: ClusterIP
  ports:
    agentListener: 50000
  nodePorts:
    agentListener: ""
  clusterIP: ""
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster
  annotations: {}
  extraPorts: []
  sessionAffinity: None
  sessionAffinityConfig: {}
ingress:
  enabled: false
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: jenkins.local
  path: /
  annotations: {}
  tls: false
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraTls: []
  secrets: []
  ingressClassName: ""
  extraRules: []
persistence:
  enabled: true
  storageClass: ""
  existingClaim: ""
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  selector: {}
volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/os-shell
    tag: 12-debian-12-r16
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  resourcesPreset: "none"
  resources: {}
  securityContext:
    seLinuxOptions: null
    runAsUser: 0
rbac:
  create: true
  rules: []
serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: false
```

### What is the expected behavior?

Ideally, the helm chart should be able to be deployed without customizing the agent CPU specs. however, this works when below given snippet is added to the `agent`

agent:

```YAML
resource:
   requests:
     cpu: 2
     memory: 512Mi
   limits:
     cpu: 3
     memory: 1024Mi
```

### What do you see instead?

All info provided

### Additional information

info provided
