### ISSUE TITLE
[bitnami/jenkins] plugins are not enabled during chart bootstrapping

### ISSUE THREAD

**Issue by busyboy77** [bitnami/charts#23964]
### Name and Version

bitnami/jenkins:12.10.0

### What architecture are you using?

None

### What steps will reproduce the bug?

RKE

`
helm upgrade --install --namespace jenkins --create-namespace --values ./values.yaml  jenkins oci://registry-1.docker.io/bitnamicharts/jenkins
`

### Are you using any custom parameters or values?

with values given below:

```YAML
root@jenkins:~/jenkins# egrep  -v "^[ ]*#|^$" values.yaml
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""
kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
commonLabels: {}
commonAnnotations: {}
clusterDomain: cluster.local
extraDeploy: []
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity
image:
  registry: docker.io
  repository: bitnami/jenkins
  tag: 2.440.1-debian-12-r0
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
jenkinsUser: user
jenkinsPassword: ""
jenkinsHost: ""
jenkinsHome: /bitnami/jenkins/home
javaOpts: []
disableInitialization: "no"
command: []
args: []
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
plugins:
  - kubernetes:3852.v41ea_166a_ed1b_
  - workflow-aggregator:590.v6a_d052e5a_a_b_5
  - git:4.13.0
  - configuration-as-code:1569.vb_72405b_80249
extraPlugins: []
latestPlugins: true
latestSpecifiedPlugins: false
skipImagePlugins: false
overridePlugins: false
overridePaths: ""
initScripts: {}
initScriptsCM: ""
initScriptsSecret: ""
initHookScripts: {}
initHookScriptsCM: ""
initHookScriptsSecret: ""
tls:
  autoGenerated: true
  usePemCerts: false
  existingSecret: ""
  password: ""
  passwordsSecret: ""
  resourcesPreset: "none"
  resources:
   requests:
     cpu: 2
     memory: 512Mi
   limits:
     cpu: 3
     memory: 1024Mi
configAsCode:
  enabled: true
  extraConfigFiles: {}
  securityRealm: {}
  authorizationStrategy: {}
  security: {}
  extraJenkins: {}
  extraConfig: {}
  extraKubernetes: {}
  extraClouds: []
  existingConfigmap: ""
  autoReload:
    enabled: true
    initialDelay: 360
    reqRetries: 12
    interval: 10
    command: []
    args: []
    extraEnvVars: []
    extraEnvVarsSecret: ""
    extraEnvVarsCM: ""
    extraVolumeMounts: []
    containerSecurityContext:
      enabled: true
      seLinuxOptions: null
      runAsUser: 1001
      runAsGroup: 0
      runAsNonRoot: true
      privileged: false
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: "RuntimeDefault"
agent:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/jenkins-agent
    tag: 0.3206.0-debian-12-r9
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
    debug: false
  templateLabel: "kubernetes-agent"
  podLabels: {}
  annotations: {}
  sidecars: []
  command: ""
  args: ""
  containerExtraEnvVars: []
  podExtraEnvVars: []
  extraAgentTemplate: {}
  extraTemplates: []
  resourcesPreset: "2xlarge"
  resources:
   requests:
     cpu: 2
     memory: 1024Mi
   limits:
     cpu: 3
     memory: 4096Mi
  containerSecurityContext:
    enabled: false
    seLinuxOptions: null
    runAsUser: ""
    runAsGroup: ""
    privileged: false
updateStrategy:
  type: RollingUpdate
priorityClassName: ""
schedulerName: ""
topologySpreadConstraints: []
automountServiceAccountToken: true
hostAliases: []
extraVolumes: []
extraVolumeMounts: []
sidecars: []
initContainers: []
lifecycleHooks: {}
podLabels: {}
podAnnotations: {}
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ""
  key: ""
  values: []
affinity: {}
nodeSelector: {}
tolerations: []
resourcesPreset: "none"
resources:
  requests:
    cpu: "2"
    memory: 1024Mi
  limits:
    cpu: "4"
    memory: 8192Mi
containerPorts:
  http: 8080
  https: 8443
  agentListener: 50000
podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
  fsGroup: 1001
containerSecurityContext:
  enabled: true
  seLinuxOptions: null
  runAsUser: 1001
  runAsGroup: 0
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"
startupProbe:
  enabled: false
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 6
livenessProbe:
  enabled: true
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 6
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
customStartupProbe: {}
customLivenessProbe: {}
customReadinessProbe: {}
service:
  type: ClusterIP
  ports:
    http: 80
    https: 443
  nodePorts:
    http: ""
    https: ""
  clusterIP: ""
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster
  annotations: {}
  extraPorts: []
  sessionAffinity: None
  sessionAffinityConfig: {}
networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: true
  kubeAPIServerPorts: [443, 6443, 8443]
  extraIngress: []
  extraEgress: []
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
agentListenerService:
  enabled: true
  type: ClusterIP
  ports:
    agentListener: 50000
  nodePorts:
    agentListener: ""
  clusterIP: ""
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster
  annotations: {}
  extraPorts: []
  sessionAffinity: None
  sessionAffinityConfig: {}
ingress:
  enabled: false
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: jenkins.local
  path: /
  annotations: {}
  tls: false
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraTls: []
  secrets: []
  ingressClassName: ""
  extraRules: []
persistence:
  enabled: true
  storageClass: ""
  existingClaim: ""
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  selector: {}
volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/os-shell
    tag: 12-debian-12-r16
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  resourcesPreset: "none"
  resources: {}
  securityContext:
    seLinuxOptions: null
    runAsUser: 0
rbac:
  create: true
  rules: []
serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: false

```

### What is the expected behavior?

When Plugins is enabled with below given configuration, it should automatically add/install the requested plugins, however, this is not happening

```YAML
plugins:
  - kubernetes:3852.v41ea_166a_ed1b_
  - workflow-aggregator:590.v6a_d052e5a_a_b_5
  - git:4.13.0
  - configuration-as-code:1569.vb_72405b_80249
extraPlugins: []
latestPlugins: true
latestSpecifiedPlugins: false
skipImagePlugins: false
overridePlugins: false

```

### What do you see instead?

Selected plugins are not installed and are to be manually deployed after installation

**Comment by javsalgar** [comment]
Hi!

Could you share the startup logs in case there is some error?

**Comment by busyboy77** [comment]
I have deleted the deployment now and moved to a standard OS based deployment. I you want me to do this again, I will do it and share details

**Comment by busyboy77** [comment]
Using this Values.yaml

```YAML
image:
  debug: true
javaOpts:
#  - "-Dfile.encoding=UTF-8"
#  - "-Dsun.jnu.encoding=UTF-8"
#  - "-Dhudson.slaves.NodeProvisioner.initialDelay=5"
#  - "-Dhudson.slaves.NodeProvisioner.MARGIN=50"
#  - "-Dhudson.slaves.NodeProvisioner.MARGIN0=0.85"
#  - "-Duser.timezone=Asia/Shanghai"
  - "-Xmx8192m"
  - "-XshowSettings:vm"
#jenkinsUser: admin
#jenkinsPassword: "admin123$"
plugins:
  - kubernetes:3852.v41ea_166a_ed1b_
  - workflow-aggregator:590.v6a_d052e5a_a_b_5
  - git:4.13.0
  - configuration-as-code:1569.vb_72405b_80249
latestSpecifiedPlugins: true
latestPlugins: true
disableInitialization: "no"
resources:
  requests:
    cpu: "2"
    memory: 1024Mi
  limits:
    cpu: "4"
    memory: 16384Mi
tls:
  autoGenerated: false
configAsCode:
  enabled:  true
agent:
  enabled: true
  debug: true
  resources:
     requests:
       cpu: "2"
       memory: 1024Mi
     limits:
       cpu: "2"
       memory: 8192Mi


service:
  type: ClusterIP

agentListenerService:
  enabled: true
  type: NodePort
  ports:
    agentListener: 50000
  nodePorts:
    agentListener: "30050"


```

with debug enabled, logs are attached ( too big to paste here )

[jenkins-logs-debug.txt](https://github.com/bitnami/charts/files/14460160/jenkins-logs-debug.txt)
