### ISSUE TITLE
[bitnami/jenkins] Jenkins Cloud config not created

### ISSUE THREAD

**Issue by busyboy77** [bitnami/charts#23963]
### Name and Version

bitnami/jenkins:12.10.0

### What architecture are you using?

None

### What steps will reproduce the bug?

RKE2
using 
` helm upgrade --install --namespace jenkins --create-namespace --values ./values.yaml  jenkins oci://registry-1.docker.io/bitnamicharts/jenkins --version 12.10.0
`

### Are you using any custom parameters or values?

Using Helm chart values 

```YAML
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""
kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
commonLabels: {}
commonAnnotations: {}
clusterDomain: cluster.local
extraDeploy: []
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity
image:
  registry: docker.io
  repository: bitnami/jenkins
  tag: 2.440.1-debian-12-r0
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
jenkinsUser: user
jenkinsPassword: ""
jenkinsHost: ""
jenkinsHome: /bitnami/jenkins/home
javaOpts: []
disableInitialization: "no"
command: []
args: []
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
plugins: []
extraPlugins: []
latestPlugins: true
latestSpecifiedPlugins: false
skipImagePlugins: false
overridePlugins: false
overridePaths: ""
initScripts: {}
initScriptsCM: ""
initScriptsSecret: ""
initHookScripts: {}
initHookScriptsCM: ""
initHookScriptsSecret: ""
tls:
  autoGenerated: true
  usePemCerts: false
  existingSecret: ""
  password: ""
  passwordsSecret: ""
  resourcesPreset: "none"
  resources:
   requests:
     cpu: 2
     memory: 512Mi
   limits:
     cpu: 3
     memory: 1024Mi
configAsCode:
  enabled: true
  extraConfigFiles: {}
  securityRealm: {}
  authorizationStrategy: {}
  security: {}
  extraJenkins: {}
  extraConfig: {}
  extraKubernetes: {}
  extraClouds: []
  existingConfigmap: ""
  autoReload:
    enabled: true
    initialDelay: 360
    reqRetries: 12
    interval: 10
    command: []
    args: []
    extraEnvVars: []
    extraEnvVarsSecret: ""
    extraEnvVarsCM: ""
    extraVolumeMounts: []
    containerSecurityContext:
      enabled: true
      seLinuxOptions: null
      runAsUser: 1001
      runAsGroup: 0
      runAsNonRoot: true
      privileged: false
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: "RuntimeDefault"
agent:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/jenkins-agent
    tag: 0.3206.0-debian-12-r9
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
    debug: false
  templateLabel: "kubernetes-agent"
  podLabels: {}
  annotations: {}
  sidecars: []
  command: ""
  args: ""
  containerExtraEnvVars: []
  podExtraEnvVars: []
  extraAgentTemplate: {}
  extraTemplates: []
  resourcesPreset: "2xlarge"
  resources:
   requests:
     cpu: 2
     memory: 1024Mi
   limits:
     cpu: 3
     memory: 4096Mi
  containerSecurityContext:
    enabled: false
    seLinuxOptions: null
    runAsUser: ""
    runAsGroup: ""
    privileged: false
updateStrategy:
  type: RollingUpdate
priorityClassName: ""
schedulerName: ""
topologySpreadConstraints: []
automountServiceAccountToken: true
hostAliases: []
extraVolumes: []
extraVolumeMounts: []
sidecars: []
initContainers: []
lifecycleHooks: {}
podLabels: {}
podAnnotations: {}
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ""
  key: ""
  values: []
affinity: {}
nodeSelector: {}
tolerations: []
resourcesPreset: "none"
resources:
  requests:
    cpu: "2"
    memory: 1024Mi
  limits:
    cpu: "4"
    memory: 8192Mi
containerPorts:
  http: 8080
  https: 8443
  agentListener: 50000
podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
  fsGroup: 1001
containerSecurityContext:
  enabled: true
  seLinuxOptions: null
  runAsUser: 1001
  runAsGroup: 0
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"
startupProbe:
  enabled: false
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 6
livenessProbe:
  enabled: true
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 6
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
customStartupProbe: {}
customLivenessProbe: {}
customReadinessProbe: {}
service:
  type: ClusterIP
  ports:
    http: 80
    https: 443
  nodePorts:
    http: ""
    https: ""
  clusterIP: ""
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster
  annotations: {}
  extraPorts: []
  sessionAffinity: None
  sessionAffinityConfig: {}
networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: true
  kubeAPIServerPorts: [443, 6443, 8443]
  extraIngress: []
  extraEgress: []
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
agentListenerService:
  enabled: true
  type: ClusterIP
  ports:
    agentListener: 50000
  nodePorts:
    agentListener: ""
  clusterIP: ""
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster
  annotations: {}
  extraPorts: []
  sessionAffinity: None
  sessionAffinityConfig: {}
ingress:
  enabled: false
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: jenkins.local
  path: /
  annotations: {}
  tls: false
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraTls: []
  secrets: []
  ingressClassName: ""
  extraRules: []
persistence:
  enabled: true
  storageClass: ""
  existingClaim: ""
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  selector: {}
volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/os-shell
    tag: 12-debian-12-r16
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  resourcesPreset: "none"
  resources: {}
  securityContext:
    seLinuxOptions: null
    runAsUser: 0
rbac:
  create: true
  rules: []
serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: false
```

### What is the expected behavior?

In previous versions, Cloud config was automatically added with one Agent available, however, in latest releases, the agent and the cloud Nodes have to be manually added.

### What do you see instead?

There is no default Cloud Added
![image](https://github.com/bitnami/charts/assets/19593617/de103d7d-85c9-4d82-af5a-4a2e91bde094)
![image](https://github.com/bitnami/charts/assets/19593617/71e681f0-9e57-4961-a353-88b1e3453204)
