### ISSUE TITLE
[bitnami/mlflow] AWS S3 Bucket access using service account

### ISSUE THREAD

**Issue by aliabbasjaffri** [bitnami/charts#24000]
### Name and Version

bitnami/mlflow

### What is the problem this feature will solve?

Currently there has to be a user created in AWS, which allows ACCESSKEY and SECRETKEY to be generated and hence used to [access the mlflow external S3 bucket](https://github.com/bitnami/charts/blob/dd929f1fa2e6453f9fdede3c78117be91f7d3996/bitnami/mlflow/values.yaml#L1446-L1447). This can be an additional step in case the users are synced in from an external LDAP service.

### What is the feature you are proposing to solve the problem?

 A more safer way to [access S3 would be via IRSA](https://repost.aws/knowledge-center/eks-restrict-s3-bucket). This would allow access to AWS S3 only via permission based policy instead of generating secrets, which are an endless mess to manage, rotate, and update.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by act-mreeves** [comment]
@aliabbasjaffri I believe this is possible as of https://github.com/bitnami/charts/commit/50c0de916e9caf185c5da93c51055d2640877d00.

It's not very intuitive but the way I did this was with these settings (assume aws account id of 123456789 and a bucket named my-cool-bucket in us-east-1):
```
externalS3:
  useCredentialsInSecret: false
  protocol: "https"
  host: "my-cool-bucket.s3.us-east-1.amazonaws.com"
  bucket: "my-cool-bucket"
  serveArtifacts: true
tracking:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::123456789:role/mlflow
```

I am having a different issue `botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the ListObjectsV2 operation: The specified key does not exist.` where it can't find a given key perhaps because I am wrestling with an import from another mlflow mysql db to postgres but I solved the original error of `botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity`.

I am using helm chart 0.7.7 for context.
