### ISSUE TITLE
Allow elasticsearch to run in a single node configuration

### ISSUE THREAD

**Issue by AdallomRoy** [bitnami/charts#2402]
**Which chart**:
elasticsearch

**Is your feature request related to a problem? Please describe.**
Currently, it's impossible to run elasticsearch in single node configuration (which is very relevant and helpful for local dev environments, which do not need 3 or more pods running).
You can easily set configuration like this:
```
config:
  discovery:
    type: single-node
  network:
    host: 0.0.0.0
```
and set other replica counts to 0, but none of the current templates fit the requirements:
Master nodes does not externalize port 9200, so it can't be the single node.
Data nodes do not have a service template at all
Coordinate only nodes do not have persistency

**Describe the solution you'd like**
I was thinking about adding port 9200 as a flag to master nodes - then it will be easy to run the current chart in a single node mode

**Describe alternatives you've considered**
You can add persistency to coordination only nodes or add a service to data nodes but that is far more work and will significantly change the chart.

**Additional context**
Thanks!

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. If you already explored the possible solution, could you try adding PR to cover that use case? This is not a critical feature for the chart so we wouldn't be able to guarantee an ETA otherwise.

**Comment by graste** [comment]
Using the above example as a reference with helm chart v13.1.3 this 'works':

```yaml
elasticsearch:
  fullnameOverride: slightly-weird-elasticsearch
  image:
    registry: docker.io
    repository: bitnami/elasticsearch
    tag: 7.10.2-debian-10-r0
    pullPolicy: IfNotPresent
  plugins: "analysis-icu"
  master:
    replicas: 1
    heapSize: 1024m
  config:
    discovery:
      type: single-node
    network:
      host: 0.0.0.0
  coordinating:
    replicas: 0
  data:
    replicas: 0
  sysctlImage:
    enabled: true
  persistence:
    enabled: true
    size: 4Gi
  volumePermissions:
    enabled: true
```

This creates a single pod `master` stateful set w/ service. The `data` stateful set is still defined, but has no running pods. The `coordinating-only` deployment is also defined, but running with 0 pods. So still a bit more than necessary for dev-only tests, but at least has a somewhat usable elasticsearch node.

**Comment by javsalgar** [comment]
Hi,

Thank you for the input! At least for the time being, it should be enough for dev testing with a single-node ES.

**Comment by GeorgeTsilias** [comment]
To be able to use persistence, you need to also add the path.data in the config section of the helm chart.
The path.data default is /opt/bitnami/elasticsearch/data whereas the volumePermissions initContainer chowns /bitnami/elasticsearch/data, causing errors such as this:
`java.lang.IllegalStateException: Unable to access 'path.data' (/opt/bitnami/elasticsearch/data)
`
This is on chart version 15.9.1

**Comment by thenotsoft** [comment]
> To be able to use persistence, you need to also add the path.data in the config section of the helm chart.
> The path.data default is /opt/bitnami/elasticsearch/data whereas the volumePermissions initContainer chowns /bitnami/elasticsearch/data, causing errors such as this:
> `java.lang.IllegalStateException: Unable to access 'path.data' (/opt/bitnami/elasticsearch/data) `
> This is on chart version 15.9.1

have same problem

**Comment by littleboss** [comment]
> To be able to use persistence, you need to also add the path.data in the config section of the helm chart. The path.data default is /opt/bitnami/elasticsearch/data whereas the volumePermissions initContainer chowns /bitnami/elasticsearch/data, causing errors such as this: `java.lang.IllegalStateException: Unable to access 'path.data' (/opt/bitnami/elasticsearch/data) ` This is on chart version 15.9.1

how to fix this issues?

**Comment by GeorgeTsilias** [comment]
@littleboss since the initContainer chowns /bitnami/elasticsearch/data, I went ahead and put something like this in the values.yaml ( I use Elasticsearch as a subchart, so I added this on the parent chart values.yaml file)

```
elasticsearch:
   config:
      discovery:
        type: single-node
      network:
        host: 0.0.0.0
      path:
        data: /bitnami/elasticsearch/data
```
This essentially populates the configuration file that ElasticSearch reads when it boots up and changes the default path under which data is gonna be saved.
