### ISSUE TITLE
[bitnami/mongodb] suboptimal deployment setting

### ISSUE THREAD

**Issue by gecube** [bitnami/charts#24174]
### Name and Version

bitnami/mongodb

### What architecture are you using?

None

### What steps will reproduce the bug?

Just to install mongodb with helmrelease:

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: mongo
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: mongo
spec:
  interval: 5m0s
  timeout: 1m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongo
  namespace: mongo
spec:
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: '*'
  interval: 5m0s
  values:
    architecture: standalone
    auth:
      enabled: true
      rootUser: root
      rootPassword: "e8L85239yHVZ2jwFVzaS"
```

The mongo is installed and running. But then I see the next:

```console
$ kubectl get pods -n mongo
NAME                             READY   STATUS             RESTARTS           AGE
mongo-mongodb-5dc8c88457-4l4kb   1/1     Running            0                  15d
mongo-mongodb-c686c8bf8-dg7qj    0/1     CrashLoopBackOff   2598 (3m17s ago)   9d
```

The issue is `useStatefulSet: false` default value. It simply does not work well. No documentation was found with a warning.
I am asking to change the default value to `useStatefulSet: true` which solves the issue with multiple pods of mongodb sharing the same volume.

### What do you see instead?

n/a
