### ISSUE TITLE
[bitnami/ghost] MySQL statefulset never becomes ready, enters CrashLoopBackoff

### ISSUE THREAD

**Issue by djjudas21** [bitnami/charts#24175]
### Name and Version

bitnami/ghost 19.10.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy Ghost with lightly-customised values file (below)
2. MySQL statefulset never becomes ready

### Are you using any custom parameters or values?

This values file is derived from the bitnami/ghost `values.yaml` with minor modifications. Most settings are left at default.

```yaml
ghostBlogTitle: User's Blog
ghostUsername: ghost
ghostPassword: ghost
ghostEmail: mail@example.com
ghostHost: ghost.example.com
ghostPath: /
ghostEnableHttps: true

## SMTP mail delivery configuration
smtpHost: "smtp-relay.smtp.svc.cluster.local"
smtpPort: "25"
smtpService: ""
smtpProtocol: ""
  
allowEmptyPassword: false
ghostSkipInstall: false

## @section Ghost deployment parameters
replicaCount: 1

## @param updateStrategy.type Ghost deployment strategy type
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
## NOTE: Set it to `Recreate` if you use a PV that cannot be mounted on multiple pods
updateStrategy:
  type: Recreate
## @param priorityClassName Ghost pod priority class name
##
priorityClassName: ""

podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
  fsGroup: 1001

containerSecurityContext:
  enabled: true
  seLinuxOptions: null
  runAsUser: 1001
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"
startupProbe:
  enabled: false
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6
  successThreshold: 1
## @section Traffic Exposure Parameters

## Ghost service parameters
##
service:
  ## @param service.type Ghost service type
  ##
  type: ClusterIP
  ## @param service.ports.http Ghost service HTTP port
  ## @param service.ports.https Ghost service HTTPS port
  ##
  ports:
    http: 80
    https: 443
  ## @param service.externalTrafficPolicy Ghost service external traffic policy
  ## ref https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  ##
  externalTrafficPolicy: Cluster
  ## @param service.annotations Additional custom annotations for Ghost service
  ##
  annotations: {}
  ## @param service.sessionAffinityConfig Additional settings for the sessionAffinity
  ## sessionAffinityConfig:
  ##   clientIP:
  ##     timeoutSeconds: 300
  sessionAffinityConfig: {}
## Configure the ingress resource that allows you to access the Ghost installation
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  ## @param ingress.enabled Enable ingress record generation for Ghost
  ##
  enabled: true
  ## @param ingress.pathType Ingress path type
  ##
  pathType: ImplementationSpecific
  ## @param ingress.hostname Default host for the ingress record
  ##
  hostname: ghost.example.com
  ## @param ingress.path Default path for the ingress record
  ## NOTE: You may need to set this to '/*' in order to use this with ALB ingress controllers
  ##
  path: /
  ## @param ingress.annotations Additional annotations for the Ingress resource. To enable certificate autogeneration, place here your cert-manager annotations.
  ## For a full list of possible ingress annotations, please see
  ## ref: https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md
  ## Use this parameter to set the required annotations for cert-manager, see
  ## ref: https://cert-manager.io/docs/usage/ingress/#supported-annotations
  ##
  ## e.g:
  ## annotations:
  ##   kubernetes.io/ingress.class: nginx
  ##   cert-manager.io/cluster-issuer: cluster-issuer-name
  ##
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls: true

persistence:
  enabled: true
  storageClass: ceph-block
  size: 8Gi

volumePermissions:
  ## @param volumePermissions.enabled Enable init container that changes the owner/group of the PV mount point to `runAsUser:fsGroup`
  ##
  enabled: false

## @section Database Parameters

## MySQL chart configuration
## ref: https://github.com/bitnami/charts/blob/main/bitnami/mysql/values.yaml
##
mysql:
  enabled: true
  image:
    debug: true
  architecture: standalone
  auth:
    rootPassword: ghostroot
    database: ghost
    username: ghost
    password: ghost
  primary:
    persistence:
      enabled: true
      storageClass: ceph-block
      accessModes:
        - ReadWriteOnce
      size: 4Gi
```

### What is the expected behavior?

I expect the MySQL statefulset to become ready after a short time

### What do you see instead?

MySQL statefulset never becomes ready. It looks like the MySQL daemon never starts up.

```console
$ kubectl get sts
NAME          READY   AGE
ghost-mysql   0/1     8m56s
```

```console
$ kubectl get pvc
NAME                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
ghost                Bound    pvc-1b6b358a-55a0-4cd4-857b-886fb4fe8140   8Gi        RWO            ceph-block     18m
data-ghost-mysql-0   Bound    pvc-b5bf2fd5-91cc-4f3b-afe0-bfe7af0cc8c2   4Gi        RWO            ceph-block     18m
```

```console
$ kubectl get po
NAME            READY   STATUS    RESTARTS       AGE
ghost-mysql-0   0/1     Running   3 (116s ago)   9m1s
```

```console
$ kubectl logs -f ghost-mysql-0
mysql 22:30:27.35 INFO  ==> 
mysql 22:30:27.37 INFO  ==> Welcome to the Bitnami mysql container
mysql 22:30:27.39 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
mysql 22:30:27.39 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
mysql 22:30:27.39 INFO  ==> 
mysql 22:30:27.40 DEBUG ==> Copying files from /opt/bitnami/mysql/conf.default to /opt/bitnami/mysql/conf
mysql 22:30:27.40 INFO  ==> ** Starting MySQL setup **
mysql 22:30:27.42 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 22:30:27.43 INFO  ==> Initializing mysql database
mysql 22:30:27.43 DEBUG ==> Ensuring expected directories/files exist
mysql 22:30:27.44 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 22:30:27.45 DEBUG ==> Cleaning data directory to ensure successfully initialization
mysql 22:30:27.45 INFO  ==> Installing database
mysql 22:31:15.67 INFO  ==> Starting mysql in background
mysql 22:31:19.68 DEBUG ==> Executing SQL command:
select 1
1
mysql 22:31:19.69 INFO  ==> Configuring authentication
mysql 22:31:19.69 DEBUG ==> Executing SQL command:
DELETE FROM mysql.user WHERE user not in ('mysql.sys','mariadb.sys');
mysql 22:31:19.79 DEBUG ==> Configuring root user credentials
mysql 22:31:19.79 DEBUG ==> Executing SQL command:
-- create admin user
create user 'root'@'%' identified by "ghostroot";
grant all on *.* to 'root'@'%' with grant option;
flush privileges;
mysql 22:31:20.04 DEBUG ==> removing the unknown user
mysql 22:31:20.04 DEBUG ==> Executing SQL command:
select Host from user where User='';
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql 22:31:20.05 DEBUG ==> creating database user \'ghost\'
mysql 22:31:20.06 DEBUG ==> Executing SQL command:
create user if not exists 'ghost'@'%' identified by 'ghost';
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql 22:31:20.15 DEBUG ==> Removing all other hosts for the user
mysql 22:31:20.15 DEBUG ==> Executing SQL command:
select Host from user where User='ghost' and Host!='%';
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql 22:31:20.16 DEBUG ==> Creating database ghost
mysql 22:31:20.17 DEBUG ==> Executing SQL command:
create database if not exists `ghost` ;
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql 22:31:20.30 DEBUG ==> Providing privileges to username ghost on database ghost
mysql 22:31:20.30 DEBUG ==> Executing SQL command:
grant all on `ghost`.* to 'ghost'@'%';
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql 22:31:20.40 INFO  ==> Running mysql_upgrade
mysql 22:31:20.40 INFO  ==> Stopping mysql
mysql 22:31:22.41 DEBUG ==> Waiting for mysql to unlock db files
mysql 22:31:22.43 INFO  ==> Starting mysql in background
find: '/docker-entrypoint-startdb.d/': No such file or directory
mysql 22:32:34.53 INFO  ==> Stopping mysql
mysql 22:32:44.55 DEBUG ==> Waiting for mysql to unlock db files
/bitnami/mysql/data/ibdata1:
   221
```
^^ container restarts here, continue tailing log below

```console
$ kubectl logs -f ghost-mysql-0
mysql 22:32:47.13 INFO  ==> 
mysql 22:32:47.13 INFO  ==> Welcome to the Bitnami mysql container
mysql 22:32:47.14 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
mysql 22:32:47.14 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
mysql 22:32:47.14 INFO  ==> 
mysql 22:32:47.14 DEBUG ==> Copying files from /opt/bitnami/mysql/conf.default to /opt/bitnami/mysql/conf
mysql 22:32:47.14 INFO  ==> ** Starting MySQL setup **
mysql 22:32:47.16 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 22:32:47.17 INFO  ==> Initializing mysql database
mysql 22:32:47.17 DEBUG ==> Ensuring expected directories/files exist
mysql 22:32:47.18 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 22:32:47.18 INFO  ==> Using persisted data
mysql 22:32:47.20 INFO  ==> Running mysql_upgrade
mysql 22:32:47.20 INFO  ==> Starting mysql in background
```
^^ container hangs, gets killed by kubernetes here, and loops forever like this

```console
$ kubectl exec -it ghost-mysql-0 -- bash
I have no name!@ghost-mysql-0:/$ mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (2)
```

**Comment by carrodher** [comment]
What is the command you're using to deploy ghost? Are you able to reproduce the issue installing the chart in a brand new namespace or only reusing an existing one?

**Comment by djjudas21** [comment]
Hey, thanks for the response. I am deploying with:

```sh
helm upgrade -i --create-namespace \
    -n ghost ghost \
    -f values.yaml \
    bitnami/ghost
```

Each attempt, I am tearing down the `ghost` namespace (including all volumes) and redeploy a clean installation.

**Comment by djjudas21** [comment]
Also worth noting that I'm using several other Bitnami charts on this cluster without problems, although most of those are using MariaDB rather than MySQL.

**Comment by charlesg99** [comment]
+1, same issue. Reverting to v9.19 makes it work again.

**Comment by dgomezleon** [comment]
Hi @djjudas21 and @charlesg99 
> ```
> Can't connect to local MySQL server through socket
> ```

To better understand the issue. What version do you mean? Have you detected what may have changed since then? Does it work for you with the default values?

**Comment by djjudas21** [comment]
I'm using bitnami/ghost v19.11.1 and this is the first time I have attempted to install Ghost.

I just attempted to install with 100% default values and the problem is the same. I install like this:

```sh
helm upgrade -i --create-namespace \
    -n ghost ghost \
    bitnami/ghost
```

MySQL still loops

```
[jonathan@poseidon ghost]$ kubectl get po
NAME            READY   STATUS    RESTARTS        AGE
ghost-mysql-0   0/1     Running   2 (2m17s ago)   7m6s
```

```
[jonathan@poseidon ghost]$ kubectl logs -f ghost-mysql-0
mysql 14:29:18.48 INFO  ==> 
mysql 14:29:18.48 INFO  ==> Welcome to the Bitnami mysql container
mysql 14:29:18.48 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
mysql 14:29:18.48 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
mysql 14:29:18.48 INFO  ==> 
mysql 14:29:18.49 INFO  ==> ** Starting MySQL setup **
mysql 14:29:18.51 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 14:29:18.52 INFO  ==> Initializing mysql database
mysql 14:29:18.52 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 14:29:18.53 INFO  ==> Using persisted data
mysql 14:29:18.55 INFO  ==> Running mysql_upgrade
mysql 14:29:18.55 INFO  ==> Starting mysql in background
```

**Comment by charlesg99** [comment]
On my end the issue started going from mysql chart v9.19 to v9.21. Nothing changed in my project, just updated the chart. I haven't tried with default values, here are mine:

```
mysql:
  architecture: standalone
  primary:
    persistence:
      storageClass: dev-data
  volumePermissions:
    enabled: true
  auth:
    rootPassword: *dbap
    username: *dbu
    password: *dbp
    database: *dbn
  initdbScripts:
    init.sql: | 'little init script'
```

**Comment by dgomezleon** [comment]
> On my end the issue started going from mysql chart v9.19 to v9.21. Nothing changed in my project, just updated the chart

In case it helps, the main changes between those versions were:

* [Enable networkPolicy](https://github.com/bitnami/charts/pull/23019)
* [Add resource preset support](Add resource preset support)
* [Use Debian 12 images](https://github.com/bitnami/charts/pull/23672)

> I haven't tried with default values, here are mine:

It is possible that the storageClass is too slow for the current liveness/readiness probes timers, and you may need to increase the `initialDelaySeconds` even more.


> just attempted to install with 100% default values and the problem is the same

From the first logs you sent, I can see that the installation took more than 2 minutes. Could you try it by increasing `initialDelaySeconds` too?

**Comment by djjudas21** [comment]
I would be surprised if it's slow storage, since my storageClass is Ceph RBD, backed by an array of NVMe.

But, I tried deploying again with the `startupProbe` enabled, as this is what it is for :slightly_smiling_face:

```yaml
mysql:
  primary:
    startupProbe:
      enabled: true
```

The MySQL container shows the same behaviour. The readiness probe never marks it "ready", but it takes a bit longer to be restarted because it is being protected by the startup probe.

```
NAME            READY   STATUS    RESTARTS      AGE
ghost-mysql-0   0/1     Running   2 (31s ago)   5m17s
```

I looked at the readiness probe in the `bitnami/mysql` chart. I did wonder if is having trouble figuring out what `localhost` is in this context, and whether that could be related to the change of base distro image. Something weird to do with IPv6 being enabled, or port number, or something like that?

```yaml
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.primary.readinessProbe "enabled") "context" $) | nindent 12 }}
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  password_aux="${MYSQL_ROOT_PASSWORD:-}"
                  if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
                  fi
                  mysqladmin status -uroot -p"${password_aux}"
```

**Comment by djjudas21** [comment]
I disabled the probes so the container wouldn't get restarted from underneath me all the time, and ran the probes by hand:

```sh
[jonathan@poseidon ghost]$ kubectl exec -it ghost-mysql-0 -- bash

# First I ran the command to populate an env var with the root password
I have no name!@ghost-mysql-0:/$ password_aux="${MYSQL_ROOT_PASSWORD:-}"
              if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                  password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
              fi

# I checked that the value is correct, and it is
I have no name!@ghost-mysql-0:/$ echo $password_aux
ghostroot

# Finally I ran the probe command, and it returns valid output
I have no name!@ghost-mysql-0:/$ mysqladmin status -uroot -p"${password_aux}"
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
Uptime: 40  Threads: 2  Questions: 4  Slow queries: 0  Opens: 119  Flush tables: 3  Open tables: 39  Queries per second avg: 0.100
```

So the probe looks fine...

**Comment by dgomezleon** [comment]
Hi @djjudas21 ,

It seems like the default timing for the probes is not enough for your use case, so you will need to fine-tune them for your environment. Have you tried increasing it significantly to check it? E.g:

```
livenessProbe:
  enabled: true
  initialDelaySeconds: 360
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 360
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6
  successThreshold: 1
```


> But, I tried deploying again with the `startupProbe` enabled, as this is what it is for

If you want to wait before executing a readiness probe, you can use `initialDelaySeconds` or a `startupProbe`.



> I did wonder if is having trouble figuring out what `localhost` is in this context, and whether that could be related to the change of base distro image.

I don't think it is related, but to confirm it you could also try it by changing `debian-11` to `debian-12` in your values.yaml.
