### ISSUE TITLE
[bitnami/rabbitmq] Enabling of networkPolicy in rabbitmq Chart should be mentioned in Update part of docs

### ISSUE THREAD

**Issue by taladar** [bitnami/charts#24181]
### Name and Version

bitnami/rabbitmq after Pull-Request #22741 got merged

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When using RabbitMQ for e.g. MQTT or anything else that uses extra ports the network policy blocks ingress to those ports.
Upgrading the helm dependency beyond this point silently adds the networkPolicy.
It would be useful if that was mentioned in the Upgrade section of the docs.

### What do you see instead?

Potentially breaking changes should be discoverable in the upgrade section and potentially even use a new chart major version.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. I agree that the upgrade section should have included some notes on this. We apologize for any inconvenience caused. Having said that, how are you setting these extra ports? Maybe the network policy should take into account these extra ports automatically when creating the `ingress` rule.

**Comment by taladar** [comment]
Originally we only used

```
  extraConfiguration: "mqtt.listeners.ssl.default = 8883"
  service:
    extraPorts:
      - appProtocol: "secure-mqtt"
        name: "mqtts"
        protocol: "TCP"
        port: 8883
        targetPort: 8883
```

which was working before the upgrade and now we also added

```
  extraContainerPorts:
    - name: "mqtts"
      protocol: "TCP"
      containerPort: 8883
  networkPolicy:
    extraIngress:
      - ports:
          - protocol: "TCP"
            containerPort: 8883
            port: 8883
```
