### ISSUE TITLE
[bitnami/keycloak] keycloak-config-cli pod affected by anti-affinity

### ISSUE THREAD

**Issue by taladar** [bitnami/charts#24183]
### Name and Version

bitnami/keycloak 18.7.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We have an environment with 3 nodes and set
```yaml
  replicaCount: 3
  podAntiAffinityPreset: "hard"
  keycloakConfigCli:
    enabled: true
    ...
```
Apparently, this also prevents the keycloak-config-cli job from running on any node where a keycloak pod is already running.

### Are you using any custom parameters or values?

The image is just the upstream image with an added theme
```yaml
  image:
    registry: ...
    repository: ...
    pullSecrets:
      - ...
  extraEnvVars:
  - name: KC_FEATURES
    value: 'account-api,account2,admin-api,admin2,admin-fine-grained-authz,authorization,ciba,client-policies,impersonation,js-adapter,kerberos,par,step-up-authentication,token-exchange,web-authn'
  production: true
  proxy: "edge"
  replicaCount: 3
  podAntiAffinityPreset: "hard"
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "200m"
      memory: "2Gi"
  startupProbe:
    enabled: true
    # increased from 60 because one of the three pods will not start within the time allotted
    failureThreshold: 90
  postgresql:
    enabled: true
    user: "keycloak"
    existingSecret: "keycloak-db-credentials"
    database: "keycloak"
  keycloakConfigCli:
    enabled: true
    existingConfigmap: keycloak-config-cli-configmap
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        cpu: "200m"
        memory: "1Gi"
  auth:
    adminUser: admin
    existingSecret: "keycloak-admin-credentials"
```
### What is the expected behavior?

I would expect the job pod to ignore the configured anti-affinity rules for the actual keycloak pods.

### What do you see instead?
```
Warning   FailedScheduling   Pod/keycloak-keycloak-config-cli-l2z48   0/4 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 3 node(s) didn't satisfy existing pods anti-affinity rules. preemption: 0/4 nodes are available: 1 Preemption is not helpful for scheduling, 3 No preemption victims found for incoming pod.
```
