### ISSUE TITLE
[bitnami/keycloak] `app-quarkus-dir` is empty

### ISSUE THREAD

**Issue by delvh** [bitnami/charts#24192]
### Name and Version

bitnami/keycloak 14.2.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

There seems to be a seemingly random chance that `/opt/bitnami/keycloak/lib/quarkus/` is empty, due to which https://github.com/bitnami/charts/blob/b9201f64c174a9e0cee184e02e48e31624695568/bitnami/keycloak/templates/statefulset.yaml#L90-L99 fails.

I have no idea how this is possible, it worked the last few days, and now it doesn't work anymore.
Even a downgrade didn't help.

### Are you using any custom parameters or values?

Output of `helm get --namespace $NAMESPACE values keycloak`
```yaml
USER-SUPPLIED VALUES:
args:
- start-dev
- --import-realm
auth:
  adminPassword: <redacted>
  adminUser: <redacted>
command:
- /opt/keycloak/bin/kc.sh
extraEnvVars:
- name: KC_HOSTNAME_STRICT
  value: "false"
extraVolumeMounts:
- mountPath: /opt/keycloak/data/import
  name: keycloak-realm
- mountPath: /opt/keycloak/providers
  name: keycloak-plugins
extraVolumes:
- configMap:
    name: keycloak-realm-config
  name: keycloak-realm
- name: keycloak-plugins
  persistentVolumeClaim:
    claimName: keycloak-plugin-volume
image:
  registry: quay.io
  repository: keycloak/keycloak
  tag: 24.0
ingress:
  hostname: <redacted>
initContainers:
- image: <redacted>
  imagePullPolicy: Always
  name: keycloak-plugin-initializer
  volumeMounts:
  - mountPath: /opt/keycloak/providers
    name: keycloak-plugins
metrics:
  enabled: true
podAnnotations:
  dapr.io/app-id: keycloak
  dapr.io/app-port: "80"
  dapr.io/config: tracing
  dapr.io/enabled: "true"
postgresql:
  auth:
    database: <redacted>
    postgresPassword: <redacted>
    username: <redacted>
production: true
proxy: edge
readinessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 10
```

### What is the expected behavior?

The chart starts.

### What do you see instead?

```sh
kubectl logs --namespace $NAMESPACE keycloak-0 --container init-quarkus-directory
cp: cannot stat '/opt/bitnami/keycloak/lib/quarkus/*': No such file or directory
```

### Additional information

I think the easiest solution would be to continue even if the directory is empty.
However, I don't know how and why this directory is empty, and/or what it means
