### ISSUE TITLE
[bitnami/schema-registry] schema-registry `headless-service.yaml` doesn't include `namespace`:

### ISSUE THREAD

**Issue by Kellen275** [bitnami/charts#24263]
### Name and Version

bitnami/schema-registry 17.1.0

### What steps will reproduce the bug?

I detected this when I noticed my ArgoCD failed to sync because the namespace was missing
![Screenshot from 2024-03-07 17-12-55](https://github.com/bitnami/charts/assets/59538148/4ce87b9b-9006-420d-89fd-ba33ea104b90)

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Other templates follow the common config ([example](https://github.com/bitnami/charts/blob/main/bitnami/schema-registry/templates/hpa.yaml))
```yaml
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
```

### What do you see instead?

The `headless-service.yaml` doesn't specify a namespace (https://github.com/bitnami/charts/blob/main/bitnami/schema-registry/templates/headless-service.yaml#L9)
```yaml
metadata:
  name: {{ include "common.names.fullname" . }}
```
