### ISSUE TITLE
[bitnami/discourse] Parts of this page are not secure (such as images)

### ISSUE THREAD

**Issue by oleksiidn** [bitnami/charts#24270]
### Name and Version

bitnami/discourse

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am hosting my app in Hetzner cloud.

I did next:

## Install NGiNX-ingress

```helm
helm upgrade --install \
ingress-nginx ingress-nginx/ingress-nginx \
-f ingress-value.yaml \
--namespace ingress-nginx \
--create-namespace
```

## ingress-value.yaml

```yaml
controller:
  kind: DaemonSet
  
  service:
    annotations:
      load-balancer.hetzner.cloud/location: hel1
      load-balancer.hetzner.cloud/name: lb
      load-balancer.hetzner.cloud/use-private-ip: "true"
      load-balancer.hetzner.cloud/hostname: "sub.domain.com"
      load-balancer.hetzner.cloud/uses-proxyprotocol: 'true'
  replicaCount: 2
  config:
    use-proxy-protocol: "true"
```

### Install cert manager
```
helm upgrade --install \
--namespace cert-manager \
--create-namespace \
--set installCRDs=true \
cert-manager jetstack/cert-manager
```

## ClusterIssuer
I added cluster issuer to the discourse helm charts
```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
   name: letsencrypt-prod
   labels:
      name: letsencrypt-prod
spec:
   acme:
      email: my@email.com
      privateKeySecretRef:
         name: letsencrypt-prod
      server: https://acme-v02.api.letsencrypt.org/directory
      solvers:
         - http01:
              ingress:
                 class: nginx
```

## Discourse helm value file changes

```yaml
ingress:
   enabled: true
   hostname: sub.domain.com
   annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: "nginx"
   tls: true
```

## Discourse helm value changes

```yaml
ingress:
   enabled: true
   hostname: sub.domain.com
   annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: "nginx"
   tls: true
```

### What is the expected behavior?

I expect to have https connection

### What do you see instead?

Only Fire Fox browser complains about connection:
`Parts of this page are not secure (such as images)`

## ssllabs.com says

Certificate #2: RSA 2048 bits (SHA256withRSA) **No SNI**

**Alternative names:** 	ingress.local   MISMATCH

**Trusted:**  	No   NOT TRUSTED Mozilla  Apple  Android  Java  Windows  

![image](https://github.com/bitnami/charts/assets/98417392/a0f9c516-adb6-4a67-bbc9-e399390a8b44)
