### ISSUE TITLE
[bitnami/airflow] nil pointer evaluating interface {}.global

### ISSUE THREAD

**Issue by romanziske** [bitnami/charts#24283]
### Name and Version

bitnami/airflow  2.8.2

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Run helm install with follwing config:
```yaml
global:
  imageRegistry:  REGISTRY
  storageClass: "directpv-min-io"

ingress:
  enabled: true
  hostname: HOSTNAME
  path: /airflow

git:
  dags:
    enabled: true
    repositories:
      - repository: URL_TO_REPO
        branch: develop
        name: INDENTIFIER
        path: airflow/dags
```

### What is the expected behavior?

Airflow installed on kubernetes 

### What do you see instead?
```
Error: UPGRADE FAILED: template: airflow/templates/worker/statefulset.yaml:78:12: executing "airflow/templates/worker/statefulset.yaml" at <include "airflow.git.containers.clone" (dict "securityContext" .Values.worker.containerSecurityContext "context" $)>: error calling include: template: airflow/templates/_git_helpers.tpl:83:23: executing "airflow.git.containers.clone" at <include "common.compatibility.renderSecurityContext" (dict "secContext" .securityContext "context" $)>: error calling include: template: airflow/charts/common/templates/_compatibility.tpl:26:15: executing "common.compatibility.renderSecurityContext" at <.context.Values.global.compatibility>: nil pointer evaluating interface {}.global
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by giosdas** [comment]
Hello,

I've found the same issue with helm chart version 17.2.1.

In a test environment a quick workaround is to disable container security context for web, scheduler and worker
```yaml
web:
  containerSecurityContext:
    enabled: false

scheduler:
  containerSecurityContext:
    enabled: false

worker:
  containerSecurityContext:
    enabled: false
```

I make some investigation and the issue seems to be related to the wrong call made by the helpers function that call "renderSecurityContext" with $, but $ is null in the helper function. Instead of $ it should be pass ".context".

_git_helpers.tpl at line 71 and 139 call:
```
  securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .securityContext "context" $) | nindent 4 }}
```

but with this fix it's working:
```
  securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .securityContext "context" .context) | nindent 4 }}
```
