### ISSUE TITLE
Bitnami/Keycloak Custom Themes

### ISSUE THREAD

**Issue by ITS1988** [bitnami/charts#24302]
### Name and Version

bitnami/keycloak 19.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi,
 
We deploy Keycloak via the Helm charts bitnami/keycloak.
 
We would like to upload and use a custom theme for the login page, as well as for the different realms. 
What we have done so far is to create a pv.yaml file and a pvc.yaml and include it via extraVolumes and extraVolumeMounts with the folder /opt/bitnami/keycloak/themes. 
 
<include code sample about what you mention above here>

We can see the custom themes folder in the container from the filesystem, but unfortunately, we cannot see the themes under "Themes" in the web interface.
 
Are we doing something wrong? Is it possible to use custom themes with the bitnami/keycloak chart?
 
Thank you in advance!
 
Regards, 
Ilias

### Are you using any custom parameters or values?
```yaml
extraVolumes:
  - name: keycloak-themes-volume
    persistentVolumeClaim:
      claimName: keycloak-themes-pvc
## @param extraVolumeMounts Optionally specify extra list of additional volumeMounts for Keycloak container(s)
##
extraVolumeMounts:
  - name: keycloak-themes-volume
    mountPath: /opt/bitnami/keycloak/themes/
```

### What do you see instead?

I didn't get an error but I can not see the themes under "Themes"

**Comment by ITS1988** [comment]
Hi,

any news for this?

**Comment by andresbono** [comment]
Hi, it looks like your approach is correct, according to https://github.com/bitnami/containers/tree/main/bitnami/keycloak#adding-custom-themes, right? Did you check the [Keycloak docs regarding themes](https://www.keycloak.org/docs/23.0.7/server_development/#_themes)? Are you missing any steps?

**Comment by casix** [comment]
I have the same problem, how did you solve it?

We have a theme that is working with the chart version 18.5.0.
We copy the jar file into the /opt/bitnami/keycloak/providers with an init container and a initdbScripts:

```
extraVolumes: 
  - name: theme
    emptyDir: {}
extraVolumeMounts: 
  - name: theme
    mountPath: /opt/themes_temp    
initContainers:
  - name: theme-provider
    image: XXXXXXXXXXXXXXXXXXXXX/keycloak/theme:v0.x.x
    imagePullPolicy: Always
    volumeMounts:
      - name: theme
        mountPath: /deployments

initdbScripts:
  my_init_script.sh: |
    #!/bin/bash
    cp /opt/themes_temp/newtheme.jar /opt/bitnami/keycloak/providers/
```
After upgrading to chart version 24.0.0, it fails because we get an error due to the filesystem being read-only.

We tried to mount it in the /opt/bitnami/keycloak/themes/newtheme folder (as the docs suggest):

```
extraVolumes:
  - name: theme
    emptyDir: {}

extraVolumeMounts: 
  - name: theme
    mountPath: /opt/bitnami/keycloak/providers/myautomatictv/

initContainers:
  - name: theme-provider
    image: XXXXXXXXXXXXXXXXXXXXXXXXXXXX/keycloak/theme:0.X.X
    imagePullPolicy: Always
    volumeMounts:
      - name: theme
        mountPath: /deployments
```

The folder and the jar theme file are present:
```
keycloak@keycloak-1:/opt/bitnami/keycloak/themes$ find 
.
./README.md
./newtheme
./newtheme/newtheme.jar
```

but the theme does not appear in the realm setting -> theme tab.

At keycloak startup there are no line logs entries indicating anything about the theme.

Any idea how can I fix this?

Thank you!!

**Comment by MugenTwo** [comment]
Hi! I was able to make this work by putting the followin in the values.yaml file:

I have the following directory in my physical node: /root/keycloak/themes/custom-theme

```
extraVolumes: |
  - name: realm-import
    configMap:
      name: keycloak-realm-config
  - name: keycloak-theme-host-volume
    hostPath:
      path: /root/keycloak/themes
      type: Directory

extraVolumeMounts: |
  - name: realm-import
    mountPath: /opt/bitnami/keycloak/data/import
  - name: keycloak-theme-host-volume
    mountPath: /opt/bitnami/keycloak/themes
```


The realm's config.json had the realm in the client:

<img width="246" alt="Image" src="https://github.com/user-attachments/assets/b739e513-147b-4e9f-b30b-2b71fd268fba" />

**Comment by briceruzand** [comment]
I found the following solution : copy the theme in an init container by mounting existing `empty-dir` volume.

```yaml
initContainers:
  - name: theme-provider
    image: mytheme-provider-image
    imagePullPolicy: Always
    command:
      - /bin/bash
    args:
      - -ec
      - |
        SOURCE_THEME="/keycloak-theme/mytheme.jar"
        TARGET_THEME_DIR="/mnt/app-providers-dir/"
        cp -a "${SOURCE_THEME}" "${TARGET_THEME_DIR}"
        echo "Theme files copied successfully from ${SOURCE_THEME} to ${TARGET_THEME_DIR}"
    volumeMounts:
      - name: empty-dir
        mountPath: /mnt
```
