### ISSUE TITLE
[bitnami/nginx] Mounting custom HTTPs certificate causes pod CrashLoopBackOff

### ISSUE THREAD

**Issue by DonaldKellett** [bitnami/charts#24312]
### Name and Version

bitnami/nginx 15.14.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install version 15.14.0 of the Helm chart with the following values:

```yaml
containerPorts:
  https: 8443
extraVolumeMounts:
- name: nginx-tls
  mountPath: /opt/bitnami/nginx/conf/bitnami/certs
extraVolumes:
- name: nginx-tls
  secret:
    secretName: nginx-tls
```

Assume the secret `nginx-tls` already exists with a valid TLS certificate-key pair named `server.crt` and `server.key` respectively.

### Are you using any custom parameters or values?

```yaml
containerPorts:
  https: 8443
extraVolumeMounts:
- name: nginx-tls
  mountPath: /opt/bitnami/nginx/conf/bitnami/certs
extraVolumes:
- name: nginx-tls
  secret:
    secretName: nginx-tls
```

### What is the expected behavior?

NGINX pod starts correctly, enters a Ready state within a few seconds

### What do you see instead?

NGINX pod stuck in CrashLoopBackOff

Pod logs indicate this error is related to filesystem permissions:

```text
cp: cannot create regular file '/opt/bitnami/nginx/conf/./bitnami/protect-hidden-files.conf': Permission denied
```

### Additional information

This issue appears to be introduced in chart version 15.14.0 via https://github.com/bitnami/charts/pull/24041 most likely due to a combination of mounting `/opt/bitnami/nginx/conf` as an emptyDir volume and `runAsUser` / `runAsGroup` / `fsGroup`. Version 15.13.0 of the chart installs correctly with the Helm chart values provided above. Furthermore, the issue does not appear when the chart is deployed with the default Helm chart values.

Please find below the related Asciinema screencasts demonstrating the issue in action. A fresh kind Kubernetes cluster was initialized for each screencast for reproducibility and providing a standardized environment:

- kubectl version (client): `v1.29.2`
- kubectl version (server): `v1.29.2`
- kind version: `v0.22.0`
- Helm version: `v3.14.2`

### [bitnami/nginx] 15.14.0, custom HTTPs certificate

[![asciicast](https://asciinema.org/a/646042.svg)](https://asciinema.org/a/646042)

### [bitnami/nginx] 15.13.0, custom HTTPs certificate

[![asciicast](https://asciinema.org/a/646041.svg)](https://asciinema.org/a/646041)

### [bitnami/nginx] 15.14.0, default Helm chart values

[![asciicast](https://asciinema.org/a/646044.svg)](https://asciinema.org/a/646044)

**Comment by javsalgar** [comment]
Hi,

The issue is that mounting the bitnami folder as a secret makes the folder read-only. Could you try this alternative?

```
extraVolumeMounts:
- name: nginx-tls
  mountPath: /opt/bitnami/nginx/conf/bitnami/certs/server.crt
  subPath: server.crt
- name: nginx-tls
  mountPath: /opt/bitnami/nginx/conf/bitnami/certs/server.key
  subPath: server.key
- name: empty-dir
  mountPath: /opt/bitnami/nginx/conf/bitnami
  subPath: app-conf-bitnami-dir
```

However, this is a workaround. The chart should provide a way to add TLS secrets without using `extraVolumes` and `extraVolumeMounts`

**Comment by DonaldKellett** [comment]
> Hi,
> 
> The issue is that mounting the bitnami folder as a secret makes the folder read-only. Could you try this alternative?
> 
> ```
> extraVolumeMounts:
> - name: nginx-tls
>   mountPath: /opt/bitnami/nginx/conf/bitnami/certs/server.crt
>   subPath: server.crt
> - name: nginx-tls
>   mountPath: /opt/bitnami/nginx/conf/bitnami/certs/server.key
>   subPath: server.key
> - name: empty-dir
>   mountPath: /opt/bitnami/nginx/conf/bitnami
>   subPath: app-conf-bitnami-dir
> ```
> 
> However, this is a workaround. The chart should provide a way to add TLS secrets without using `extraVolumes` and `extraVolumeMounts`

Thanks, I used the following modified values as per your suggestion and the pod was able to start correctly:

```yaml
containerPorts:
  https: 8443
extraVolumeMounts:
- name: nginx-tls
  mountPath: /opt/bitnami/nginx/conf/bitnami/certs/server.crt
  subPath: server.crt
- name: nginx-tls
  mountPath: /opt/bitnami/nginx/conf/bitnami/certs/server.key
  subPath: server.key
- name: empty-dir
  mountPath: /opt/bitnami/nginx/conf/bitnami
  subPath: app-conf-bitnami-dir
extraVolumes:
- name: nginx-tls
  secret:
    secretName: nginx-tls
```

However, like you mentioned, supporting TLS secrets directly without `extraVolumes` and `extraVolumeMounts` would be better UX.

I'll leave it up to you to decide whether to keep this issue open or close it \(and perhaps track the TLS secrets feature in a separate issue\).
