### ISSUE TITLE
[bitnami/discourse]  Jobs::DownloadBackupEmail and CriticalUserEmail fail

### ISSUE THREAD

**Issue by oleksiidn** [bitnami/charts#24317]
### Name and Version

bitnami/discourse

### What architecture are you using?

None

### What steps will reproduce the bug?

I am trying to connect my app to mailjet API.

### Are you using any custom parameters or values?

```yaml
auth:
   email: my@email.com
   username: superAdmin
   password: "password"
smtp:
   enabled: true
   host: "mailjet"
   port: "587"
   user: "user"
   password: "password"
   protocol: ""
   auth: ""
   existingSecret: ""
```

### What is the expected behavior?

The application has to call the email API

### What do you see instead?

I got `class=Jobs::DownloadBackupEmail INFO: fail` error when I tried to download the backup from the admin UI.

I got `class=Jobs::CriticalUserEmail INFO: fail` error when I tried to reset my password through the forgot button.
