### ISSUE TITLE
bitnami/keycloak same FQDN for both ingresses

### ISSUE THREAD

**Issue by busyboy77** [bitnami/charts#24320]
### Name and Version

bitnami/keycloak:19.3.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm trying to configure and setup keycloak using bitnami/keycloak:19.3.0 helm chart with below given command

```
helm upgrade --install=true --namespace ef-external --values ./values.yaml --debug --render-subchart-notes  keycloak .

```
and trying to setup ingresses for both normal `ingress` and `adminIngress` using same FQDN. However, it seems to loop forever or does not work completely. 

Background:

We use bitnami/keycloak for on-prem based deployments where using 2 different FQDNs is completely NOT an option and routing using same FQDN is mandatory requirement. 

### Are you using any custom parameters or values?

```YAML
auth:
  adminUser: admin
  adminPassword: "admin"
httpRelativePath: "/auth/"
extraEnvVars:
     - name: KC_LOG_LEVEL
       value: "DEBUG"
     - name: KEYCLOAK_LOGLEVEL
       value: "DEBUG"
     - name: ROOT_LOGLEVEL
       value: "DEBUG"
     - name:  KEYCLOAK_ADMIN_URL
       value: https://devops218.ef.com/keyadmin
     - name: KEYCLOAK_EXTRA_ARGS
       value:  "-Dkeycloak.frontendUrl=https://devops218.ef.com/keyadmin  -Dkeycloak.profile.feature.upload_scripts=enabled"
     - name:  KEYCLOAK_FRONTEND_URL
       value: https://devpos218.ef.com/keyadmin
     - name: KEYCLOAK_LOGLEVEL
       value:  DEBUG
     - name: KEYCLOAK_PASSWORD
       value: admin
     - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
       value: "true"
     - name: KEYCLOAK_USER
       value: admin
     - name: NODE_ENV
       value: development
ingress:
  enabled: true
  ingressClassName: "nginx"
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: devops218.ef.com
  path: "{{ .Values.httpRelativePath }}"
  servicePort: http
  annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.org/server-snippets: |
         location / {
            proxy_set_header X-Forwarded-For $host;
            proxy_set_header X-Forwarded-Proto $scheme;
           }
  labels: {}
  tls: true
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraTls:
    - hosts:
       - devops218.ef.com
      secretName: ef-ingress-tls-secret
  secrets: []
  extraRules: []
adminIngress:
  enabled: true
  ingressClassName: "nginx"
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: devops218.ef.com
  path: "/keyadmin"
  servicePort: http
  annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.org/server-snippets: |
         location / {
            proxy_set_header X-Forwarded-For $host;
            proxy_set_header X-Forwarded-Proto $scheme;
           }
  labels: {}
  tls: true
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraTls:
    - hosts:
        - devops218.ef.com
      secretName: ef-ingress-tls-secret
  secrets: []
  extraRules: []
```

### What is the expected behavior?

the `adminIngress `  never works.

### What do you see instead?

Ideally, the requirement of separate FQDN should not block using same FQDN but with different ingress routes.
