### ISSUE TITLE
coalesce.go:175: warning: skipped value for zookeeper.automountServiceAccountToken: Not a table.

### ISSUE THREAD

**Issue by ThomasKroghMortensen** [bitnami/charts#24328]
### Name and Version

Kafka 27.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I deploy the /kafka-27.1.0.tgz as a subchart of another chart.

With these values:
The kafka values get set from the master helm chart like this for kafka and zookeeper

Chart dependencies:

```yaml
apiVersion: v2
appVersion: "1.0.0"
description: Kafka test
name: master-chart
version: 1.0.0
dependencies:
  - name: kafka
    version: "27.1.0"
```

Values for kafka and zookeeper in master values.yaml
```yaml
kafka:
  fullnameOverride: "kafka-service"
  image:
    pullPolicy: Always
  metrics:
    kafka:
      enabled: false
    jmx:
      enabled: false
  kraft:
    enabled: false
  controller:
    replicaCount: 0
  broker:
    replicaCount: 1
    startupProbe:
      enabled: true
    persistence:
      enabled: false
    resources:
      limits:
        cpu: 400m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
    podSecurityContext:
      enabled: false
      fsGroup: 1001
    containerSecurityContext:
      enabled: false
      runAsUser: 1001
    podLabels:
      test/space: tkm
  zookeeper:
    enabled: true
    fullnameOverride: "zookeeper-service"
    automountServiceAccountToken: false
    image:
      pullPolicy: Always
    metrics:
      enabled: false
    persistence:
      enabled: false
    podSecurityContext:
      enabled: false
      fsGroup: 1001
    containerSecurityContext:
      enabled: false
      runAsUser: 1001
    resources:
      limits:
        cpu: 400m
        memory: 512Mi
      requests:
        cpu: 250m
    podLabels:
      test/space: tkm
   ```   

When installing the master helm chart (including kafka) 
`helm install ./master-1.0.0.tgz -f values.yaml`

Causes this warning:

`coalesce.go:175: warning: skipped value for zookeeper.automountServiceAccountToken: Not a table.`

Note. Is this only an issue when Kafka is used as a dependency chart in another master/umbrella helm chart?

### What is the expected behavior?

No warnings

### What do you see instead?
```
coalesce.go:175: warning: skipped value for zookeeper.automountServiceAccountToken: Not a table.
```

Note: If I try to provide the `zookeeper.automountServiceAccountToken`as a table in the values, I get this:
```
coalesce.go:175: warning: skipped value for sd-helm-chart.kafka.zookeeper.automountServiceAccountToken: Not a table.
coalesce.go:175: warning: skipped value for zookeeper.automountServiceAccountToken: Not a table.
coalesce.go:223: warning: destination for sd-helm-chart.kafka.zookeeper.automountServiceAccountToken is a table. Ignoring non-table value (false)
coalesce.go:175: warning: skipped value for sd-helm-chart.kafka.zookeeper.automountServiceAccountToken: Not a table.
coalesce.go:223: warning: destination for sd-helm-chart.kafka.zookeeper.automountServiceAccountToken is a table. Ignoring non-table value (false)
coalesce.go:175: warning: skipped value for sd-helm-chart.kafka.zookeeper.automountServiceAccountToken: Not a table.
```
