### ISSUE TITLE
[bitnami/harbor] issue in redis string with external redis

### ISSUE THREAD

**Issue by fandz1979** [bitnami/charts#24362]
### Name and Version

bitnami/harbor 

### What architecture are you using?

amd64

### What steps will reproduce the bug?

define an external redis in default value

### Are you using any custom parameters or values?

value set in values.yaml
```yaml
redis:
  enabled: false
externalRedis:
  host: redis
  sentinel:
    enabled: true
    hosts: redis:26379
```

### What is the expected behavior?

The string sentinel should be something like that `redis+sentinel://redis:26379/...`

### What do you see instead?

we have instead `redis+sentinel://redis:26379:6379/...`

### Additional information

the issue seems to be in _helpers.tpl in the definition of redis string (`harbor.redisForJobservice` `harbor.redisForGC harbor.redisForTrivyAdapter` and `harbor.redisForCore`)
