### ISSUE TITLE
[bitnami/logstash] Plugin installation via env var suddenly stopped working

### ISSUE THREAD

**Issue by natimellino** [bitnami/charts#24403]
### Name and Version

bitnami/logstash 5.13.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Set `values.yaml` to:

```yaml
image:
  debug: true
extraEnvVars:
  - name: LOGSTASH_PLUGINS
    value: logstash-filter-json_encode, logstash-output-exec, logstash-output-statsd
enableMultiplePipelines: true
service:
  type: NodePort
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: beats
    - name: metrics
      port: 9198
      protocol: TCP
      targetPort: metrics
containerPorts:
  - name: http
    containerPort: 8080
    protocol: TCP
  - name: monitoring
    containerPort: 9600
    protocol: TCP
  - name: beats
    containerPort: 5044
    protocol: TCP
  - name: metrics
    containerPort: 9198
    protocol: TCP
extraVolumes:
  ## Patterns
  ...
  - name: beat-pipeline-vol
    configMap:
      name: beat-pipeline
      items:
      - key: beat
        path: beat_pipeline.conf
extraVolumeMounts:
  ## Patterns
  ...
  ## Logstash config
  - mountPath: /bitnami/logstash/pipelines/beat_pipeline.conf
    name: beat-pipeline-vol
    subPath: beat_pipeline.conf
# # Add metrics exporter container
sidecars:
  - name: logstash-exporter
    image: sequra/logstash_exporter:7.3.0.0
    imagePullPolicy: IfNotPresent
    ports:
      - name: metrics
        containerPort: 9198
    command:
      - ./logstash_exporter
      - --logstash.endpoint=http://localhost:9600
livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 10
readinessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 10
persistence:
  enabled: true
diagnosticMode:
  enabled: true
extraConfigurationFiles:
  logstash.yml: |
    pipeline.batch.size: 125
    pipeline.batch.delay: 50
    queue.type: persisted
    path.data: {{ .Values.persistence.mountPath }}
    api.http.host: 0.0.0.0
    api.http.port: {{ .Values.monitoringAPIPort | quote }}
    path.queue: /bitnami/logstash/data/queue
    queue.max_bytes: 1gb
    config.reload.automatic: true
    config.reload.interval: '15s'
    log.level: debug
  pipelines.yml: |
    - pipeline.id: beat_pipeline
      path.config: "/bitnami/logstash/pipelines/beat_pipeline.conf"
      pipeline.workers: 1
configFileName: logstash.yml
fullnameOverride: "logstash"
ingress:
  enabled: true
  selfSigned: true
  hostname: logstash.local
  annotations:
    kubernetes.io/ingress.class: nginx
  extraPaths:
    - backend:
        service:
          name: logstash
          port:
            name: beats
      path: /beats
      pathType: ImplementationSpecific
```

Install chart with custom values

### What is the expected behavior?

Logstash succesfully installed with all plugins specified in 

```yaml
extraEnvVars:
    - name: LOGSTASH_PLUGINS
      value: logstash-filter-json_encode, logstash-output-exec, logstash-output-statsd
```

### What do you see instead?

Setting `diagnosticMode` to `enabled` and manually performing the plugin installation shows the following output:

```bash
I have no name!@logstash-0:/opt/bitnami/logstash$ ./bin/logstash-plugin install logstash-filter-json_encode
Using system java: /opt/bitnami/java/bin/java
Warning: no jvm.options file found.
Validating logstash-filter-json_encode
Resolving mixin dependencies
Installing logstash-filter-json_encode
`/` is not writable.
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
. is not writable: /opt/bitnami/logstash
Error ArgumentError, retrying 1/10
could not find a temporary directory
`/` is not writable.
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
. is not writable: /opt/bitnami/logstash
Error ArgumentError, retrying 2/10
could not find a temporary directory
`/` is not writable.
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
. is not writable: /opt/bitnami/logstash
Error ArgumentError, retrying 3/10
could not find a temporary directory
`/` is not writable.
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
. is not writable: /opt/bitnami/logstash
Error ArgumentError, retrying 4/10
could not find a temporary directory
`/` is not writable.
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
. is not writable: /opt/bitnami/logstash
Error ArgumentError, retrying 5/10
could not find a temporary directory
`/` is not writable.
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
. is not writable: /opt/bitnami/logstash
Error ArgumentError, retrying 6/10
could not find a temporary directory
`/` is not writable.
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
. is not writable: /opt/bitnami/logstash
Error ArgumentError, retrying 7/10
could not find a temporary directory
`/` is not writable.
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
. is not writable: /opt/bitnami/logstash
Error ArgumentError, retrying 8/10
could not find a temporary directory
`/` is not writable.
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
. is not writable: /opt/bitnami/logstash
Error ArgumentError, retrying 9/10
could not find a temporary directory
`/` is not writable.
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
. is not writable: /opt/bitnami/logstash
Error ArgumentError, retrying 10/10
could not find a temporary directory
`/` is not writable.
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
. is not writable: /opt/bitnami/logstash
Too many retries, aborting, caused by ArgumentError
ERROR: Installation Aborted, message: could not find a temporary directory
```

### Additional information

I have it  deployed locally, everything was working fine until yesterday. I did not change anything, I was just testing some configs in the `beat` pipeline and the problem started out of nowhere. This same `values.yaml` was working just fine, but now the plugins cannot be installed due to this error and Logstash fails to start.

**Comment by natimellino** [comment]
Ok I just downgraded to `5.12.0` and the plugin installation part seems to work now. I did not have a version fixed so it picked up the new version that was released yesterday.

```bash
I have no name!@logstash-0:/opt/bitnami/logstash$ ./bin/logstash-plugin install logstash-filter-json_encode
Using system java: /opt/bitnami/java/bin/java
Validating logstash-filter-json_encode
Resolving mixin dependencies
Installing logstash-filter-json_encode
`/` is not writable.
Bundler will use `/tmp/bundler20240313-11-qem0hw11' as your home directory temporarily.
Installation successful
```
Could it be a problem with the new version? I just saw it was released yesterday, I tried changing some of the options in the new `containerSecurityContext` section, but it did not seem to fix the issue. If you could help me to configure the new chart version correctly I'd be really grateful.

**Comment by rafariossaa** [comment]
Hi, 
  Could you try version 6.0.0 ? 
  Did you tried disabling the `securityContext` ?

**Comment by miglocatiq** [comment]
> Hi, sorry for the delay and thanks for your response. I just tried upgrading to `6.0.0` and set
> 
> ```yaml
> containerSecurityContext:
>   enabled: false
> ```
> 
> The error is still showing. Am I missing another config? The only solution I can think of is to write a custom Docker image to install the plugins, but it is not a solution to the real problem.

Im running into exectly the same problem, when going from v5.12 to a higher version

**Comment by andresbono** [comment]
Hi, installing plugins that way is not recommended, instead, it would be nicer to customize the container image to ship all the required artifacts for your use case.

If you want to fix those permissions issues you could use the following workaround in your `values.yaml`:

```yaml
extraEnvVars:
  - name: LOGSTASH_PLUGINS
    value: logstash-filter-json_encode
initContainers:
  - name: prepare-tmp-plugins
    image: '{{ include "logstash.image" . }}'
    command:
      - bash
      - -c
      - |
        mkdir /emptydir/tmp-dir
        chmod o-w /emptydir/tmp-dir
    volumeMounts:
      - mountPath: /emptydir
        name: empty-dir
containerSecurityContext:
  readOnlyRootFilesystem: false
  runAsGroup: 0
```

As you can see, the workaround is deactivating the recently added security best practices, so again, our recommendation would be to create a custom container image bundling all the plugins and required artifacts. I hope this helps.
