### ISSUE TITLE
[bitnami/mongodb] TLS without specifying a chain of trust is no longer supported

### ISSUE THREAD

**Issue by m4rc3l-h3** [bitnami/charts#24442]
### Name and Version

bitnami/mongodb 14.13.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Environment: k8s (v1.28.4), crio (v1.28.2), helm (v3.14.2)
2. Create server certificate `secret` via certmanager ( v1.13.1) / hashicorp vault (0.25.0) installed via Helm in cluster. Created certficates worked with mongodb deployed with previous version of bitnami helm chart.
3. Deploying mongodb standalone via helm chart with `tls.enabled: true` results in error message as specified below. This issue is occurring if an existing `secret` is referenced in `tls.standalone.existingSecret` and also if instead `tls.autoGenerated: true` is set. Those two attempts are represented in the below custom parameters by the options separated by `|`. Disabling `tls` results in a starting pod.

### Are you using any custom parameters or values?

``` yaml

clusterDomain: {{ create_db_cluster_suffix }}

commonLabels:
  app.kubernetes.io/part-of: {{ create_db_app_label_part_of }}
  app.kubernetes.io/version: {{ create_db_app_label_version }}
  environment: {{ create_db_app_label_environment }}
  instance: {{ create_db_app_name }}

enableServiceLinks: false

image:
    debug: true

auth:
  rootPassword: {{ create_db_root_pwd }}
  usernames:
    - {{ create_db_user_name }}
  passwords:
    - {{ create_db_user_pwd }}
  databases:
    - {{ create_db_db_name }}

tls:
  enabled: true
  mTLS:
    enabled: false
  autoGenerated: true | false
  existingSecret: ""
  caCert: "{{ local_ca_crt_base64 }}" | ""
  caKey: "{{ local_ca_key_base64 }}" | ""
  pemChainIncluded: false
  standalone:
    existingSecret: "" | {{ create_db_app_name }}-server-tls
  mode: preferTLS

nodeSelector:
  kubernetes.io/arch: amd64

service:
  type: LoadBalancer
  loadBalancerIP: {{ create_db_ip }}

persistence:
  existingClaim: {{ create_db_app_name }}-nfs

serviceAccount:
  automountServiceAccountToken: true

volumePermissions:
  enabled: true

metrics:
  enabled: true
  collector:
    replicasetstatus: false
  serviceMonitor:
    enabled: true
```

### What is the expected behavior?

MongoDB pod starts 

### What do you see instead?

CrashLoopBackOff of Pod with the following entries in logs:
```console
$ kubectl logs -nproduction mongodb-c6bb84948-qnppr
...
mongodb 05:31:20.39 DEBUG ==> Starting MongoDB in background...
{"t":{"$date":"2024-03-14T05:31:20.438Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"main","msg":"Applied --setParameter options","attr":{"serverParameters":{"enableLocalhostAuthBypass":{"default":true,"value":true}}}}
{"t":{"$date":"2024-03-14T05:31:20.438Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"main","msg":"Error during global initialization","attr":{"error":{"code":72,"codeName":"InvalidOptions","errmsg":"The use of TLS without specifying a chain of trust is no longer supported. See https://jira.mongodb.org/browse/SERVER-72839 for details."}}}

$ kubectl logs -nproduction mongodb-c6bb84948-qnppr -cgenerate-tls-certs
Certificate request self-signature ok
subject=C = US, O = My Organisations, OU = IT, CN = wekan-db-mongodb-c6bb84948-qnppr
```

### Additional information

It has probably something to do with [SERVER-72839](https://jira.mongodb.org/browse/SERVER-72839), however, I could not find any configuration option in the helm chart to accommodate for this requirement.

If you need further information, please let me know.

Thank you for looking into this and providing guidance for correct configuration.
