### ISSUE TITLE
The keycloak-init container is missing the compatilbility-fix for openshift

### ISSUE THREAD

**Issue by JoostVanDerSluis** [bitnami/charts#24457]
### Name and Version

bitnami/keycloak 19.3.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. On an openshift/okd cluster with default security settings
2. Using a values file including this:
```yaml
    keycloak:
      global:
        compatibility:
          openshift:
            adaptSecurityContext: force
```
3. The statefulset will contain:
```yaml
    spec:
       initContainers:
         - resources: {}
           securityContext:
             privileged: false
             runAsUser: 1001
```

### What is the expected behavior?

Since the feature in https://github.com/bitnami/charts/pull/24101 runAsUser should be empty. This is done for the regular pods, but not the init pod.

### What do you see instead?

This is the event that is generated for the statefulset, and no pod is deployed

```
create Pod refurb-battery-keycloak-0 in StatefulSet refurb-battery-keycloak failed error: pods "refurb-battery-keycloak-0" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, spec.initContainers[0].securityContext.runAsUser: Invalid value: 1001: must be in the ranges: [1000710000, 1000719999], provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
```
