### ISSUE TITLE
[bitnami/jupyterhub] Wrong extraVolumes templating

### ISSUE THREAD

**Issue by adrienyhuel** [bitnami/charts#24458]
### Name and Version

bitnami/jupyterhub 6.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When you use singleuser.extraVolumes and singleuser.extraVolumeMounts the template use wrong indentation.

Lines :

https://github.com/bitnami/charts/blob/5d6a4ad00dfd69066d7c92be1eba3f176f1aaa4e/bitnami/jupyterhub/values.yaml#L226

https://github.com/bitnami/charts/blob/5d6a4ad00dfd69066d7c92be1eba3f176f1aaa4e/bitnami/jupyterhub/values.yaml#L233C83-L233C101

It should use "nindent 6" instead of "nindent 4"

### Are you using any custom parameters or values?

```yaml
singleuser:
  extraVolumes:
      - name: ca-bundle
        configMap:
          name: jupyterhub-ca-bundle
    extraVolumeMounts:
      - name: ca-bundle
        mountPath: /ca-bundle
```

### What is the expected behavior?

Values.hub.configuration template should produce :
```yaml
    extraVolumes:
      - name: empty-dir
        emptyDir: {}
      - configMap:
          name: jupyterhub-ca-bundle
        name: ca-bundle
    extraVolumeMounts:
```

### What do you see instead?

```yaml
    extraVolumes:
      - name: empty-dir
        emptyDir: {}
    - configMap:
        name: jupyterhub-ca-bundle
      name: ca-bundle
    extraVolumeMounts:
```
