### ISSUE TITLE
mastodon-sidekiq has errors when pulling posts/media due to missing temporary folder

### ISSUE THREAD

**Issue by dankar** [bitnami/charts#24469]
### Name and Version

bitnami/mastodon 4.7.2

### What architecture are you using?

None

### What steps will reproduce the bug?

Not sure how to reproduce this, but it seems to be a general issue. I have had bitnamis mastodon chart installed for a while and gone through several updates, so not sure when this appeared.

### What is the expected behavior?

Sidekiq container seems to require a tmp folder for something. In the log there are many errors like this:

```
2024-03-15T10:07:49.881660361+01:00 2024-03-15T09:07:49.881Z pid=1 tid=93e69 WARN: ArgumentError: could not find a temporary directory
2024-03-15T10:07:49.881672128+01:00 2024-03-15T09:07:49.881Z pid=1 tid=93e69 WARN: /opt/bitnami/ruby/lib/ruby/3.2.0/tmpdir.rb:38:in `tmpdir'
2024-03-15T10:07:49.881680781+01:00 /opt/bitnami/ruby/lib/ruby/3.2.0/tmpdir.rb:114:in `tmpdir'
2024-03-15T10:07:49.881688928+01:00 /opt/bitnami/ruby/lib/ruby/3.2.0/tmpdir.rb:136:in `create'
```

And a lot of posts ends up missing.

From a quick internet search, this seems to be an issue when the filesystem does not have the stick bit (+t) set for /tmp. Unfortunately I don't know 

### What do you see instead?

Sidekiq processes should be able to pull posts without issues.

**Comment by Mauraza** [comment]
Hi @dankar,

You are right it is a warning related to the creation of a temporal folder. Could you share your values?

**Comment by dankar** [comment]
Note that while this says warning in the logs, it is causing many failed sidekiq jobs. ~half of all the jobs are failing due to this.

Below are the values. The "extraConfigExistingConfigmap" is basically only OIDC settings and enabling statsd.
```
USER-SUPPLIED VALUES:
adminEmail: xxxx@xxxx.xxx
adminUser: xxxx
apache:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.middlewares: default-hsts-header@kubernetescrd
    apiVersion: ""
    enabled: true
    extraHosts: null
    extraPaths: null
    extraRules: null
    extraTls: null
    hostname: xxxx.xxxxx.xxx
    ingressClassName: traefik-external
    path: /
    pathType: ImplementationSpecific
    secrets: null
    selfSigned: false
    tls: true
  service:
    loadBalancerIP: null
    type: ClusterIP
elasticsearch:
  data:
    replicaCount: 2
  master:
    replicaCount: 2
  metrics:
    enabled: true
    extraArgs:
    prometheusRule:
      enabled: true
    serviceMonitor:
      enabled: true
  persistence:
    storageClass: longhorn-fast
externalDatabase:
  existingSecret: mastodon-cnpg-app-static
  existingSecretPasswordKey: password
  host: mastodon-cnpg-rw
  password: null
  user: mastodon
externalS3:
  accessKeyID: null
  accessKeySecret: null
  bucket: xxxxxxxx
  existingSecret: mastodon-s3-keys
  existingSecretAccessKeyIDKey: username
  existingSecretKeySecretKey: password
  host: xxx.xxxx.xxx
  region: home
extraConfigExistingConfigmap: mastodon-config
forceHttpsS3Protocol: true
global:
  cattle:
    clusterId: local
    clusterName: local
    rkePathPrefix: ""
    rkeWindowsPathPrefix: ""
    systemProjectId: p-szbjn
    url: https://xxxx.xxx.xxx
  storageClass: longhorn-fast
initJob:
  createAdmin: false
  migrateElasticsearch: false
localDomain: xxxxx.xxx
minio:
  enabled: false
postgresql:
  enabled: false
redis:
  master:
    persistence:
      size: 1Gi
      storageClass: longhorn-fast
  persistence:
    size: 1Gi
    storageClass: longhorn-fast
  replica:
    persistence:
      size: 1Gi
      storageClass: longhorn-fast
s3AliasHost: xxxx.xxxx.xxx/xxxxxxxxx
secretKeyBase: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
sidekiq:
  extraEnvVars:
  - name: SIDEKIQ_CONCURRENCY
    value: "10"
  - name: MASTODON_DATABASE_POOL
    value: "10"
smtp:
  auth_method: login
  domain: localhost
  from_address: xxxx@xxxxx.xxx
  login: xxxxxx@xxxxx.xxx
  password: xxxxxxxxxxxxxxx
  port: 25
  reply_to: xxxxxx@xxxx.xxx
  server: xxx.xxx
useSecureWebSocket: true
vapidPrivateKey: xxxxxxxxxxxxx
vapidPublicKey: xxxxxxxxxxxxx
webDomain: xxxxx.xxxxxx.xxx
```
