### ISSUE TITLE
[bitnami/etcd] Deployment Eliminating ReadWriteMany Storage Class Dependency

### ISSUE THREAD

**Issue by hadizamani021** [bitnami/charts#24485]
### Name and Version

bitnami/etcd 9.15.2

### What is the problem this feature will solve?

When aiming to restore an etcd cluster with three nodes from a snapshot, the method of setting `startFromSnapshot.enabled` to true and linking `startFromSnapshot.existingClaim` to a PVC containing the backup snapshot is suitable for deploying a single-node etcd cluster. However, using a ReadWriteOnce storage class for multiple nodes restrict all etcd nodes to the same Kubernetes node, which is not recommended. Given your current setup with ReadWriteOnce PVCS, enhancing the capability to configure startFromSnapshot.existingClaim individually for each node would offer greater flexibility and efficiency in managing the deployment of the etcd cluster.
It's worth mentioning that we are restricted and unable to configure a PVC with the ReadWriteMany storage class.

### What is the feature you are proposing to solve the problem?

Introducing a 'snapshots' array field and individual 'existingClaim' settings for each node would be a beneficial enhancement to the configuration.

```
startFromSnapshot:
  enabled: true
  snapshots:
  - existingClaim: "pvc for node 1"
    snapshotFilename: "snapshot.db"
  - existingClaim: "pvc for node 2"
    snapshotFilename: "snapshot.db"
  - existingClaim: "pvc for node 3"
    snapshotFilename: "snapshot.db"

```
