### ISSUE TITLE
[bitnami/consul] New Consul Chart readonly file system breaks consul without persistence

### ISSUE THREAD

**Issue by EStork09** [bitnami/charts#24483]
### Name and Version

bitnami/consul 11.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy Chart with:
 ```yaml
 persistence:
    enabled: false
 ```

### What is the expected behavior?

Consul Runs.

### What do you see instead?

`/bitnami/consul readonly file-system`

### Additional information

The solution is to add
```yaml
extraVolumeMounts:
    - name: empty-dir
      mountPath: /bitnami/consul
```
But most likely it would be good to add an else statement [here](https://github.com/bitnami/charts/blob/f871cafdd2337d0ea90b3e9bea7235fa47bc28d8/bitnami/consul/templates/statefulset.yaml#L275C13-L278C23)

```yaml
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /bitnami/consul
            {{- end }}
            {{- else }}
           - name: empty-dir
             mountPath: /bitnami/consul
           {{- end }}
 ```
