### ISSUE TITLE
[bitnami/elasticsearch] Unable to open ingress access（TLS）

### ISSUE THREAD

**Issue by Awsmsniper** [bitnami/charts#24492]
My goal is to deploy an elastic cluster in a production environment, and I need to enable TLS to ensure security as much as possible. However, when I enable ingress, I still cannot complete the deployment. How can I solve this problem? Or, do you have a complete deployment guide (which requires opening ingress and tls) that you can refer to?

### Name and Version

bitnami/elasticsearch 20.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. kubernetes 1.28.7 and cephfs
2. `kubectl create ns elastic`
3. `helm install elastic --namespace elastic .`

### Are you using any custom parameters or values?

values.yaml
```yaml
security:
  enabled: true
  elasticPassword: "******"
  existingSecret: ""
  fipsMode: false
  tls:
    restEncryption: true
    autoGenerated: true
    verificationMode: "full"
   usePemCerts: false
#####
service:
  type: ClusterIP
  annotations: {}
#####
ingress:
  enabled: true
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: elastic.testhost
  path: /
  annotations: {}
  tls: true
  selfSigned: true
  ingressClassName: "nginx"
```

charts/kibana/values.yaml
```yaml
service:
  ports:
    http: 5601
  type: ClusterIP
  annotations: {}
#####
ingress:
  enabled: true
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: kibana.testhost
  path: / 
  annotations: {}
  tls: true
  selfSigned: true
  ingressClassName: "nginx"
#####
tls:
  enabled: true
  autoGenerated: true
  existingSecret: ""
  usePemCerts: true
elasticsearch:
  hosts: []
  port: ""
  security:
    auth:
      enabled: true
      kibanaPassword: "*****
      existingSecret: ""
      createSystemUser: tru
      elasticsearchPasswordSecret: "elastic-elasticsearch"
    tls:
      enabled: true
      verificationMode: "full"
      existingSecret: "elastic-elasticsearch-coordinating-crt"
      usePemCerts: true
```

### What is the expected behavior?

It can be achieved through` https://elastic.testhost/ `accessingElasticsearch 
and  through` https://kibana.testhost/ `accessing Kibana

### What do you see instead?

I encountered an error while accessing Elasticsearch。
```console
$ curl -k https://elastic.testhost/
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

When I checked the ingress controller logs, I found that
 
```console
$ kubectl logs -f ingress-nginx-controller-42zj2 -n ingress-nginx
W0318 08:05:23.996850       6 controller.go:1214] Service "elastic/elastic-kibana" does not have any active Endpoint.
W0318 08:05:23.996883       6 controller.go:1214] Service "elastic/elastic-elasticsearch-ingest" does not have any active Endpoint.
W0318 08:05:23.996903       6 controller.go:1214] Service "elastic/elastic-elasticsearch" does not have any active Endpoint.
W0318 08:05:
..........
2024/03/18 08:24:22 [error] 176006#176006: *53039203 upstream prematurely closed connection while reading response header from upstream, client: 192.168.xx.xx, server: elastic.testhost, request: "GET / HTTP/2.0", upstream: "http://172.20.251.184:9200/", host: "elastic.testhost"
2024/03/18 08:24:22 [error] 176006#176006: *53039203 upstream prematurely closed connection while reading response header from upstream, client: 192.168.xx.xx, server: elastic.testhost, request: "GET / HTTP/2.0", upstream: "http://172.20.254.49:9200/", host: "elastic.testhost"
2024/03/18 08:24:22 [error] 176006#176006: *53039203 upstream prematurely closed connection while reading response header from upstream, client: 192.168.xx.xx, server: elastic.testhost, request: "GET / HTTP/2.0", upstream: "http://172.20.202.8:9200/", host: "elastic.testhost"
192.168.xx.xx- - [18/Mar/2024:08:24:22 +0000] "GET / HTTP/2.0" 502 150 "-" "curl/7.88.1" 34 0.005 [elastic-elastic-elasticsearch-tcp-rest-api] [] 172.20.251.184:9200, 172.20.254.49:9200, 172.20.202.8:9200 0, 0, 0 0.002, 0.001, 0.001 502, 502, 502 7d75e119e8ca583186b3f1d5f778a7ef
```

When I checked the elasticsearch logs, I found that

```console
$ kubectl logs -f service/elastic-elasticsearch -n elastic
[2024-03-18T08:25:41,855][WARN ][o.e.h.n.Netty4HttpServerTransport] [elastic-elasticsearch-coordinating-0] received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/172.20.251.184:9200, remoteAddress=/192.168.xx.xx:52008}
```

```console
$ kubectl get all -n elastic
NAME                                                READY   STATUS    RESTARTS      AGE
pod/elastic-elasticsearch-coordinating-0            1/1     Running   0             56m
pod/elastic-elasticsearch-coordinating-1            1/1     Running   0             56m
pod/elastic-elasticsearch-coordinating-2            1/1     Running   0             56m
pod/elastic-elasticsearch-data-0                    1/1     Running   0             56m
pod/elastic-elasticsearch-data-1                    1/1     Running   0             56m
pod/elastic-elasticsearch-data-2                    1/1     Running   0             56m
pod/elastic-elasticsearch-ingest-0                  1/1     Running   0             56m
pod/elastic-elasticsearch-ingest-1                  1/1     Running   0             56m
pod/elastic-elasticsearch-ingest-2                  1/1     Running   0             56m
pod/elastic-elasticsearch-master-0                  1/1     Running   0             56m
pod/elastic-elasticsearch-master-1                  1/1     Running   0             56m
pod/elastic-elasticsearch-master-2                  1/1     Running   0             56m
pod/elastic-elasticsearch-metrics-8f9f564fb-6nhfh   0/1     Running   1 (54m ago)   56m
pod/elastic-kibana-696c47848d-ffk6l                 1/1     Running   0             56m

NAME                                            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/elastic-elasticsearch                   ClusterIP   10.88.160.32    <none>        9200/TCP,9300/TCP   56m
service/elastic-elasticsearch-coordinating-hl   ClusterIP   None            <none>        9200/TCP,9300/TCP   56m
service/elastic-elasticsearch-data-hl           ClusterIP   None            <none>        9200/TCP,9300/TCP   56m
service/elastic-elasticsearch-ingest            ClusterIP   10.88.100.226   <none>        9200/TCP,9300/TCP   56m
service/elastic-elasticsearch-ingest-hl         ClusterIP   None            <none>        9200/TCP,9300/TCP   56m
service/elastic-elasticsearch-master-hl         ClusterIP   None            <none>        9200/TCP,9300/TCP   56m
service/elastic-elasticsearch-metrics           ClusterIP   10.88.51.162    <none>        9114/TCP            56m
service/elastic-kibana                          ClusterIP   10.88.103.53    <none>        5601/TCP            56m

NAME                                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/elastic-elasticsearch-metrics   0/1     1            0           56m
deployment.apps/elastic-kibana                  1/1     1            1           56m

NAME                                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/elastic-elasticsearch-metrics-8f9f564fb   1         1         0       56m
replicaset.apps/elastic-kibana-696c47848d                 1         1         1       56m

NAME                                                  READY   AGE
statefulset.apps/elastic-elasticsearch-coordinating   3/3     56m
statefulset.apps/elastic-elasticsearch-data           3/3     56m
statefulset.apps/elastic-elasticsearch-ingest         3/3     56m
statefulset.apps/elastic-elasticsearch-master         3/3     56m
```
