### ISSUE TITLE
[bitnami/postgresql] existingExtendedConfigmap and extendedConfiguration broken since chart v14.2.1

### ISSUE THREAD

**Issue by titou10titou10** [bitnami/charts#24528]
### Name and Version

bitnami/postgresql] v14.2.1+

### What steps will reproduce the bug?

When using a value file with the`"existingExtendedConfigmap"` tag pointing to a configmap, the postgresql configuration params are not applied when deploying the chart
It works up to v14.1.3, broken since c14.2.1

The problem is the same when`extendedConfiguration`, ie the content of the file is discard/not used

values.yaml:
```yaml
    primary:
      existingExtendedConfigmap: budget2-db-dev-postgresql-config 
```
budget2-db-dev-postgresql-config  ConfigMap:
```yaml
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: budget2-db-dev-postgresql-config
    data:
      override.conf: |+
        shared_buffers=256MB
        work_mem=128MB
        maintenance_work_mem=128MB
        temp_buffers=64MB
        ...
 ```

### What is the expected behavior?

The chart deploys without problem with the postgresql parameters overridden from the config map

### What do you see instead?

The chart deploys without overriding the postgresql config parameters

### Additional information

This is caused by this code addition in `"template/primary/statefulset.yaml"` in v14.2.1:
```yaml
     volumeMounts:
        - name: empty-dir
          mountPath: /tmp
          subPath: tmp-dir
        - name: empty-dir
          mountPath: /opt/bitnami/postgresql/conf
          subPath: app-conf-dir
        - name: empty-dir
          mountPath: /opt/bitnami/postgresql/tmp
          subPath: app-tmp-dir
        - name: empty-dir
          mountPath: /opt/bitnami/postgresql/logs
          subPath: app-logs-dir
```
Removing the added lines related to `"/opt/bitnami/postgresql/conf"` from `template/primary/statefulset.yaml` in any version >v14.2.1+ makes the chart work again
```yaml
        - name: empty-dir
          mountPath: /opt/bitnami/postgresql/conf
          subPath: app-conf-dir
```
Q:
Why has this been added to the chart, and in what use case it is useful?

It may be related to issue #16623
