### ISSUE TITLE
[bitnami/external-dns] pihole.tlsSkipVerify: true gives an error

### ISSUE THREAD

**Issue by ThijsBorst** [bitnami/charts#24529]
### Name and Version

bitnami/external-dns 7.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I deployed the external-dns chart to my cluster with pihole configuration:

```yaml
provider: pihole
pihole:
  secretName: pihole
  server: x.x.x.x
  tlsSkipVerify: true
````

### What is the expected behavior?

Starting up and connect to my pihole instance and create dns records.

### What do you see instead?

When the pod starts up it gives an error: 

```
time="2024-03-18T22:43:57Z" level=fatal msg="flag parsing error: unexpected true"
```
