### ISSUE TITLE
Schema Registry with external Confluent Kafka

### ISSUE THREAD

**Issue by piyu5h** [bitnami/charts#24533]
### Name and Version

bitnami/schema-registry 7.6.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am trying to set up a standalone schema registry with external Kafka in the confluent cloud. 
However, I am getting the below exception. 
```
kafka: auth.kafka.jksSecret
    A secret containing the Schema Registry JKS files is required when TLS encryption in enabled
```
However, I have disabled the kafka. 
Did anyone else have a similar issue and Does this chart support Confluent Kafka for Kafka Store ??

### Are you using any custom parameters or values?
```yaml
externalKafka:
  ## @param externalKafka.brokers Array of Kafka brokers to connect to. Format: protocol://broker_hostname:port
  ##
  brokers:
    - SASL_SSL://******.confluent.cloud:9092
  ## @param externalKafka.listener.protocol Kafka listener protocol. Allowed protocols: PLAINTEXT, SASL_PLAINTEXT, SASL_SSL and SSL
  ##
  listener:
    protocol: SASL_SSL
  ## Authentication parameters
  ## @param externalKafka.sasl.user User for SASL authentication
  ## @param externalKafka.sasl.password Password for SASL authentication
  ## @param externalKafka.sasl.existingSecret Name of the existing secret containing a password for SASL authentication (under the key named "client-passwords")
  ##
  sasl:
    user: ******
    password: "***************"
    existingSecret: ""
```
### What is the expected behavior?

It should be able to connect to confluent kafka

### What do you see instead?

<img width="947" alt="Screenshot 2024-03-19 at 1 48 00 PM" src="https://github.com/bitnami/charts/assets/4945457/c31ae8b0-cbbf-4e0b-8a80-b69d6ed63b17">
