### ISSUE TITLE
[bitnami/kibana] helm chart [5.0.16] fails to install with extraVolumeMounts and extraVolumes set

### ISSUE THREAD

**Issue by optimus-kart** [bitnami/charts#2454]
**Which chart**:
kibana
**Describe the bug**
Unable to set extraVolumes / extraVolumeMounts using configmap

**To Reproduce**
Use a values.yaml with following content
```
plugins:
  - "https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.6.2-0.1.31.zip"


extraVolumeMounts:
  - name: logtrailconfig
    mountPath: /usr/share/kibana/plugins/logtrail/logtrail.json
    subPath: logtrail.json

extraVolumes:
  - name: logtrailconfig
    configMap:
      name: logtrail

```
And try to install the helm with 
helm install  kibana-svc bitnami/kibana --namespace logging --values .values.yaml --version "5.0.16"

**Output**
Error: YAML parse error on kibana/templates/deployment.yaml: error converting YAML to JSON: yaml: line 71: did not find expected key

**Expected behavior**
Helm should get installed successfully

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}```
````

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}`

```

**Comment by optimus-kart** [comment]
Below is the complete yaml file that is being used
```
## List of plugins to install
##
plugins:
  - "https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.6.2-0.1.31.zip"


extraVolumeMounts:
  - name: logtrailconfig
    mountPath: /usr/share/kibana/plugins/logtrail/logtrail.json
    subPath: logtrail.json

extraVolumes:
  - name: logtrailconfig
    configMap:
      name: logtrail

service:
  port: 80
  type: LoadBalancer
  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  nodePort: 5601

  ## Enable client source IP preservation
  ## ref http://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  ##
  externalTrafficPolicy: Cluster
  ## Provide any additional annotations which may be required. This can be used to
  ## set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  hosts:
    - name: kibana.local
      path: /

      ## Set this to true in order to enable TLS on the ingress record
      tls: false

      ## Optionally specify the TLS hosts for the ingress record
      ## Useful when the Ingress controller supports www-redirection
      ## If not specified, the above host name will be used
      # tlsHosts:
      #   - www.kibana.local
      #   - kibana.local

      ## If TLS is set to true, you must declare what secret will store the key/certificate for TLS
      tlsSecret: kibana.local-tls

elasticsearch:
  hosts:
    - elasticsearch-master
  port: 9200
```
