### ISSUE TITLE
[bitnami/grafana-operator] Alert rule group failed to be applied - context deadline exceeded

### ISSUE THREAD

**Issue by ErikRosic** [bitnami/charts#24550]
### Name and Version

bitnami/grafana-operator 3.12.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy the following CRs:

```yaml
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: erik-folder
spec:
  instanceSelector:
    matchLabels:
      app: grafana-operator-grafana
  permissions: |
    {
      "items": [
        {
          "role": "Admin",
          "permission": 4
        }
      ]
    }
```
```yaml
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaAlertRuleGroup
metadata:
  name: zookeeper-elastic
spec:
  folderRef: erik-folder
  instanceSelector:
    matchLabels:
      app: grafana-operator-grafana
  interval: 1m
  rules:
    - uid: a55303dc-81ba-4d92-8d71-82de4dd6541f
      title: zookeeper-elastic
      condition: A
      data:
        - refId: A
          relativeTimeRange:
            from: 600
            to: 0
          datasourceUid: 51226607-32f3-4822-b9e4-d81ce739e094
          model:
            alias: ""
            bucketAggs:
              - field: '@timestamp'
                id: "2"
                settings:
                  interval: auto
                type: date_histogram
            datasource:
              type: elasticsearch
              uid: 51226607-32f3-4822-b9e4-d81ce739e094
            hide: false
            intervalMs: 1000
            maxDataPoints: 43200
            metrics:
              - id: "1"
                type: count
            query: 'kubernetes.labels.app_kubernetes_io/name: zookeeper'
            refId: A
            timeField: '@timestamp'
      noDataState: NoData
      execErrState: Error
      for: 1m
      annotations: { }
      labels: { }
      isPaused: false
```

### What is the expected behavior?

Deployed alert in grafana-operator-grafana-deployment

### What do you see instead?

After deploying grafana-operator-grafana-deployment with CR alertrulegroup i'm getting following error:

```
Alert Rule Group failed to be applied for 1 out of 1 instances. Errors:                                                                                                                                                                                                                                            │
│       - grafana-operator/grafana-operator-grafana: fetching folder: Get "http://grafana-operator-grafana-service.grafana-operator:3000/api/folders/670f1565-8f76-49f6-b78a-51469d413791": context deadline exceeded
```

### Additional information

I am using k8s version v1.26.10+rke2r2
