### ISSUE TITLE
[bitnami/ejbca] Storage Changes Required for Replication

### ISSUE THREAD

**Issue by seancallaway** [bitnami/charts#24579]
### Name and Version

bitnami/ejbca 12.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Setup working EJBCA installation on EKS cluster.
2. Follow instructions [found here](https://github.com/bitnami/charts/tree/main/bitnami/ejbca/#set-up-replication) on how to setup replication.

### Are you using any custom parameters or values?

```yaml
global:
  imageRegistry: "public.ecr.aws"

##
## REPLICATION CONFIG
##
replicaCount: 2

##
## DATABASE CONFIG
##
mariadb:
  enabled: false
externalDatabase:
  host: [FQDN REDACTED]
  database: [DB NAME REDACTED]
  user: [USER NAME REDACTED]
  existingSecret: ejbca-creds

##
## UPDATE STRATEGY
##
updateStrategy:
  type: Recreate

##
## ADMIN LOGIN CONFIG
##
ejbcaAdminUsername: [USERNAME REDACTED]
existingSecret: ejbca-creds

##
## SERVICE CONFIG
##
service:
  type: NodePort

##
## INGRESS CONFIG (INCLUDING DNS AND SSL)
##
ingress:
  enabled: true
  pathType: Prefix
  hostname: [FQDN REDACTED]
  ingressClassName: "alb"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/success-codes: 200-399
    alb.ingress.kubernetes.io/healthcheck-path: /ejbca/doc  # Same as livenessProbe
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/certificate-arn: [ARN REDACTED]
    external-dns.alpha.kubernetes.io/hostname: [FQDN REDACTED]
```

### What is the expected behavior?

Two pods spin up and start successfully.

### What do you see instead?

Additional pods fail to start due to "Multi-Attach error" for PV.

```
Warning  FailedAttachVolume  71s   attachdetach-controller  Multi-Attach error for volume "pvc-fc1d8036-a1a9-489f-b4d9-6ecb138e6bc3" Volume is already used by pod(s) pki-ejbca-65f86bc74d-lg96n
```

### Additional information

The [defaults for storage](https://github.com/bitnami/charts/blob/main/bitnami/ejbca/values.yaml#L205) are as follows:

```yaml
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 2Gi
```

Obviously, `ReadWriteOnce` won't work across multiple pods, so the [documentation](https://github.com/bitnami/charts/tree/main/bitnami/ejbca/#set-up-replication) should be edited to reflect the additional changes required. These options are, as far as I can tell, one of the following:

1. Disable persistence (e.g. `persistence.enabled: false`)
  a. What will this do regarding functionality? Are pod startup times increased?
2. Utilize a storageClass that supports multiattach (like something EFS-backed) and adjust the accessModes to `ReadWriteMany`.
  a. How does this work with multiple pods writing to the same volume? Do they detect each other and utilize locks?

Is there a better suggestion?
