### ISSUE TITLE
[bitnami/discourse] Running database migrations failed

### ISSUE THREAD

**Issue by crazyfree** [bitnami/charts#24596]
### Name and Version

bitnami/discourse:3.2.1-debian-12-r0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. take the image from docker hub
2. Provision with `values.yaml` below
```yaml
# Default values for test-forum-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  debug: true
  repository: "bitnami/discourse"
  tag: "3.2.1-debian-12-r0"
  pullPolicy: IfNotPresent
ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: discourse.local.domain.com
  tls: []
resources: {}
discourse:
  plugins: []
redis:
  enabled: true
  auth:
    enabled: false

# auth for Discourse
auth:
  email: dev@test.com
  username: dev
  ## @param auth.existingSecret Name of an existing secret to use for Discourse credentials
  ## `auth.password` will be ignored and picked up from this secret
  ## The secret must contain the key `discourse-password`
  ## The value is evaluated as a template
  ##
  existingSecret: test-secrets

siteName: "Test Forum"
smtp:
  enabled: true
  host: "smtp.gmail.com"
  port: 587
  user: "test@gmail.com"
  existingSecret: test-secrets
  protocol: tls

# this configuratin is for postgresql 
postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: "test"
    username: "test"
    password: "test"
    database: test
```

### What is the expected behavior?

Pod runs properly 

### What do you see instead?

```
discourse 07:45:15.56 DEBUG ==> Setting smtp_enable_start_tls to 'true' in Discourse configuration
discourse 07:45:15.57 DEBUG ==> Setting smtp_authentication to 'login' in Discourse configuration
discourse 07:45:15.58 INFO  ==> Restoring persisted Discourse installation
discourse 07:45:15.75 INFO  ==> Trying to connect to the database server
 ?column? 
----------
        1
(1 row)

discourse 07:45:15.78 INFO  ==> Running database migrations
oxipng worker: `oxipng` not found; please provide proper binary or disable this worker (--no-oxipng argument or `:oxipng => false` through options)
rake aborted!
Errno::EEXIST: File exists @ dir_s_mkdir - /opt/bitnami/discourse/public/uploads (Errno::EEXIST)
/opt/bitnami/discourse/lib/file_store/local_store.rb:82:in `copy_file'
/opt/bitnami/discourse/lib/file_store/local_store.rb:8:in `store_file'
/opt/bitnami/discourse/lib/file_store/base_store.rb:21:in `store_optimized_image'
/opt/bitnami/discourse/app/models/optimized_image.rb:120:in `block (2 levels) in create_for'
/opt/bitnami/discourse/app/models/optimized_image.rb:119:in `open'
/opt/bitnami/discourse/app/models/optimized_image.rb:119:in `block in create_for'
/opt/bitnami/discourse/app/models/optimized_image.rb:19:in `block (2 levels) in lock'
/opt/bitnami/discourse/lib/distributed_mutex.rb:53:in `block in synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:34:in `synchronize'
/opt/bitnami/discourse/app/models/optimized_image.rb:19:in `block in lock'
/opt/bitnami/discourse/lib/distributed_mutex.rb:53:in `block in synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:34:in `synchronize'
/opt/bitnami/discourse/app/models/optimized_image.rb:18:in `lock'
/opt/bitnami/discourse/app/models/optimized_image.rb:73:in `create_for'
/opt/bitnami/discourse/lib/site_icon_manager.rb:74:in `block in ensure_optimized!'
/opt/bitnami/discourse/lib/site_icon_manager.rb:70:in `each'
/opt/bitnami/discourse/lib/site_icon_manager.rb:70:in `ensure_optimized!'
/opt/bitnami/discourse/lib/tasks/db.rake:264:in `block (2 levels) in <main>'
/opt/bitnami/discourse/lib/distributed_mutex.rb:53:in `block in synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:34:in `synchronize'
/opt/bitnami/discourse/lib/tasks/db.rake:231:in `block in <main>'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
/opt/bitnami/ruby/bin/bundle:25:in `load'
/opt/bitnami/ruby/bin/bundle:25:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

### Additional information
- I've tried to delete both postgres and redis pvc on docker desktop but the error is still remain 
- I've tried to reset cluster on docker desktop but the error is still remain
