### ISSUE TITLE
Arbiter crashloop on chart 8.0.0+

### ISSUE THREAD

**Issue by lzoeckle** [bitnami/charts#24597]
### Name and Version

bitnami/mongodb-sharded:8.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I believe I'm running into the same bug as this previous issue, but with the sharded chart. See https://github.com/bitnami/containers/issues/63885

My values.yaml look like:

```yaml
image:
  tag: 7.0.7-debian-12-r0
  pullPolicy: IfNotPresent
  debug: true
shards: 4
defaults: &defaults
  resources:
    requests:
      cpu: 20m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
mongos:
  replicaCount: 1
  <<: *defaults
configsvr:
  replicaCount: 3
  <<: *defaults
shardsvr:
  dataNode:
    replicaCount: 2
    <<: *defaults
  arbiter:
    replicaCount: 1
    <<: *defaults
```

### What is the expected behavior?

The arbiter should start successfully.

### What do you see instead?

Crashloop with the error `mkdir: cannot create directory '/bitnami/mongodb/data/db': Read-only file system`

If I update the arbiter to include 
```yaml
containerSecurityContext:
    readOnlyRootFilesystem: false
```
I see `mkdir: cannot create directory '/bitnami/mongodb/data/db': Permission denied` instead.

### Additional information

It looks like the same `volumeMounts` entry may be missing from the arbiter's `statefulset.yaml`, as in the other bug.

**Comment by lzoeckle** [comment]
Adding here, I was able to get things running by including
```
extraVolumes:
      - mountPath: /bitnami/mongodb
        name: empty-dir
        subPath: app-volume-dir
```
in `shardsvr.arbiter`.
