### ISSUE TITLE
SASL authentication failures using kafka helm chart

### ISSUE THREAD

**Issue by DavidH-SG** [bitnami/charts#24598]
### Name and Version

bitnami/charts/kafka

### What architecture are you using?

amd64

### What steps will reproduce the bug?

running k8s on kind
install helm chart and follow your instructions to create a kafka client within the cluster and run a producer

### Are you using any custom parameters or values?
```yaml
externalAccess:
  enabled: true
  controller:
    service:
      domain: "localhost"
      type: NodePort
      nodePorts:
        - 31000
        - 31001
        - 31002
```
### What is the expected behavior?

producing messages

### What do you see instead?

I get the following error:
```
Failed operation - SASL SCRAM SHA256 authentication failed: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256
```
