### ISSUE TITLE
memcached php extension broken in wordpress 21.0.0 to 21.0.3

### ISSUE THREAD

**Issue by fabio-peptone** [bitnami/charts#24605]
### Name and Version

bitnami/wordpress 21.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install chart 21.0.3 with
```yaml
wordpressConfigureCache: true

memcached:
  enabled: true
```

The memcached plugin is not enabled in php.

Execing into the wordpress container
```console
$ $ grep memcache /opt/bitnami/php/etc/php.ini
;extension = memcached
```

The extension is correctly enabled in chart 20.1.3

### What is the expected behavior?

memcached php extension should be enabled

### What do you see instead?

memcached php extension is not enabled

### Additional information

I believe this was broken in 38bf03c4c13a580baeb856db99a3bee4c081ad90. As far as I understand, php extensions are enabled during container build. Replacing `php/etc` with an emptydir removes all the build-time configuration

**Comment by Multiply** [comment]
Noticing the same problem here.

**Comment by yourcelf** [comment]
A workaround that worked for me is to define a post-init script which uncomments the extension in php.ini:

```yaml
# Enable memcached plugin in php.ini
# https://github.com/bitnami/charts/issues/24605
customPostInitScripts:
  enable_php_ini_memcached.sh: |
    #!/bin/bash
    sed -i 's/^;extension = memcached$/extension = memcached/' /opt/bitnami/php/etc/php.ini  
```
