### ISSUE TITLE
MinIO Headless Service causes ServiceMonitor metrics to be scraped twice

### ISSUE THREAD

**Issue by Skaronator** [bitnami/charts#24619]
### Name and Version

bitnami/minio 13.7.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy MinIO in distributed mode with serviceMonitor enabled and you'll see that every metric has been scraped twice.

### Are you using any custom parameters or values?

```yaml
mode: distributed

metrics:
  serviceMonitor:
    enabled: true
```

### What is the expected behavior?

ServiceMonitor should only point to Service "minio".

### What do you see instead?

ServiceMonitor currently points to Service "minio" and "minio-headless".

Query: `minio_node_process_resident_memory_bytes{pod="minio-0", server="minio-0.minio-headless.storage.svc.cluster.local:9000"}`

![image](https://github.com/bitnami/charts/assets/2886913/aab911ce-e46d-4254-860c-6f6022d75ded)

### Additional information

The matchLabels in ServiceMonitor matches both, minio and minio-headless service: https://github.com/bitnami/charts/blob/97a9db57b510c8bf5442c393e072c6f2fc5dcea5/bitnami/minio/templates/servicemonitor.yaml#L62

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by Skaronator** [comment]
I'll take a look in the near future. Is there any recommendation which label should be used to differentiate the service selector?

**Comment by Aegdesil** [comment]
Hi @Skaronator, I am having the same issue, do you still have time to work on it ?
I think `service.kubernetes.io/headless` could be a good label to differenciate the headless service, seems to be pretty standard even though it is supposed to be used on Endpoints rather than Services: https://kubernetes.io/docs/reference/labels-annotations-taints/#servicekubernetesioheadless

**Comment by aryanbaghi** [comment]
After some investigation, I've found this workaround.

## The Problems

**Duplicate Scrape Targets:** When MinIO is deployed, the Prometheus ServiceMonitor often discovers both the standard Kubernetes Service and the headless Service, leading to two identical scrape jobs and duplicated data.
**Redundant Node Metrics:** Each MinIO node in a distributed cluster exposes metrics for all other nodes in the cluster. Scraping every node results in N sets of identical cluster-wide metrics, where N is the number of nodes.

## The Solution

This solution uses relabelings to solve the first problem at the target discovery level and metric_relabelings to solve the second problem after the scrape occurs.

Here is the ServiceMonitor configuration:
```yaml
serviceMonitor:
  enabled: true
  # Solves Problem 1: Drops scrape targets for the headless service.
  relabelings:
    - action: drop
      regex: true
      sourceLabels:
        - __meta_kubernetes_service_label_service_kubernetes_io_headless
  # Solves Problem 2: Keeps only self-reported metrics from each node.
  metricRelabelings:
    - action: replace
      regex: ([^\.]+)\..*
      sourceLabels:
        - server
      targetLabel: __temp_server
    - action: keepequal
      sourceLabels:
        - pod
      targetLabel: __temp_server
    - action: labeldrop
      regex: __temp_server
```
