### ISSUE TITLE
[bitnami/matomo] Cronjobs fail to run because of a missing certificate file

### ISSUE THREAD

**Issue by JaZo** [bitnami/charts#24618]
### Name and Version

bitnami/matomo 6.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set up a Matomo instance
2. Wait for the cronjobs to start or trigger them
3. See they fail to run (see logs below)

### Are you using any custom parameters or values?

```yaml
matomoWebsiteHost: XXX

service:
  type: ClusterIP

ingress:
  enabled: true
  hostname: XXX

mariadb:
  enabled: false

externalDatabase:
  # Properly configured

volumePermissions:
  enabled: true
```

### What is the expected behavior?

I'd expect both cronjobs to run successfully.

### What do you see instead?

```
matomo 10:51:42.08 INFO  ==> Configuring PHP options
matomo 10:51:42.09 INFO  ==> Setting PHP opcache.enable option
matomo 10:51:42.10 INFO  ==> Setting PHP expose_php option
matomo 10:51:42.10 INFO  ==> Setting PHP output_buffering option
matomo 10:51:42.12 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
matomo 10:51:42.14 DEBUG ==> Validating settings in MATOMO_* environment variables...
matomo 10:51:42.15 WARN  ==> The MATOMO_SMTP_USER environment variable is empty or not set.
matomo 10:51:42.15 WARN  ==> The MATOMO_SMTP_PASSWORD environment variable is empty or not set.
matomo 10:51:42.20 INFO  ==> Ensuring Matomo directories exist
matomo 10:51:42.21 INFO  ==> Trying to connect to the database server
matomo 10:51:42.21 DEBUG ==> Executing SQL command:
SELECT 1
1
matomo 10:51:42.27 INFO  ==> Starting apache in background
AH00526: Syntax error on line 5 of /opt/bitnami/apache/conf/vhosts/matomo-https-vhost.conf:
SSLCertificateFile: file '/opt/bitnami/apache/conf/bitnami/certs/server.crt' does not exist or is empty
```

### Additional information

It works just fine with version 5.5.1.
