### ISSUE TITLE
[bitnami/etcd] rpc error: code = PermissionDenied desc = etcdserver: permission denied

### ISSUE THREAD

**Issue by ujala-singh** [bitnami/charts#24622]
### Name and Version

bitnami/etcd 10.0.0

### What architecture are you using?

None

### What steps will reproduce the bug?

```console
$ helm install mycertm bitnami/cert-manager --set installCRDs=true

$ cat <<EOF> user.yaml
initialClusterState: "new"
replicaCount: 3

image:
  debug: true

persistence:
  accessModes:
    - ReadWriteMany
  size: 2Gi

volumePermissions:
  enabled: true

auth:
  rbac:
    enabled: true
    create: true
    allowNoneAuthentication: false
    rootPassword: "secret"
  token:
    enabled: true
    type: jwt
  peer:
    secureTransport: true
    useAutoTLS: false
    existingSecret: etcd-peer-tls
    enableAuthentication: true
    certFilename: tls.crt
    certKeyFilename: tls.key
    caFilename: ca.crt
  client:
    secureTransport: true
    useAutoTLS: false
    existingSecret: etcd-client-tls
    enableAuthentication: true
    certFilename: tls.crt
    certKeyFilename: tls.key
    caFilename: ca.crt
EOF

$ helm install myetcd bitnami/etcd -f user.yaml 
$ sleep 60
$ cat <<EOF>certs.yaml 
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-client
spec:
  secretName: etcd-client-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
  usages:
  - server auth
  - client auth
  dnsNames:
  - 'myetcd.default.svc.cluster.local'
  - '*.myetcd.default.svc.cluster.local'
  - 'myetcd-headless.default.svc.cluster.local'
  - '*.myetcd-headless.default.svc.cluster.local'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-peer
spec:
  secretName: etcd-peer-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
  usages:
  - server auth
  - client auth
  dnsNames:
  - 'myetcd.default.svc.cluster.local'
  - '*.myetcd.default.svc.cluster.local'
  - 'myetcd-headless.default.svc.cluster.local'
  - '*.myetcd-headless.default.svc.cluster.local'
EOF

$ kubectl apply -f certs.yaml
$ cat <<EOF>issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
EOF

$ kubectl apply -f issuer.yaml
```

### Are you using any custom parameters or values?

Yes.
```yaml
initialClusterState: "new"
replicaCount: 3

image:
  debug: true

persistence:
  accessModes:
    - ReadWriteMany
  size: 2Gi

volumePermissions:
  enabled: true

auth:
  rbac:
    enabled: true
    create: true
    allowNoneAuthentication: false
    rootPassword: "secret"
  token:
    enabled: true
    type: jwt
  peer:
    secureTransport: true
    useAutoTLS: false
    existingSecret: etcd-peer-tls
    enableAuthentication: true
    certFilename: tls.crt
    certKeyFilename: tls.key
    caFilename: ca.crt
  client:
    secureTransport: true
    useAutoTLS: false
    existingSecret: etcd-client-tls
    enableAuthentication: true
    certFilename: tls.crt
    certKeyFilename: tls.key
    caFilename: ca.crt
```

### What is the expected behavior?

```
I have no name!@myetcd-0:/opt/bitnami/etcd$ export ETCDCTL_ENDPOINTS=https://myetcd.default.svc.cluster.local:2379
I have no name!@myetcd-0:/opt/bitnami/etcd$ etcdctl --cert $ETCD_CERT_FILE --key $ETCD_KEY_FILE --cacert $ETCD_TRUSTED_CA_FILE endpoint status -w table
+-----------------------------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|                   ENDPOINT                    |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+-----------------------------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| https://myetcd.default.svc.cluster.local:2379 | 94ed28b1cb999b71 |  3.5.12 |   20 kB |      true |      false |         5 |        303 |                303 |        |
+-----------------------------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
I have no name!@myetcd-0:/opt/bitnami/etcd$ etcdctl --cert $ETCD_CERT_FILE --key $ETCD_KEY_FILE --cacert $ETCD_TRUSTED_CA_FILE endpoint status -w table
+-----------------------------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|                   ENDPOINT                    |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+-----------------------------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| https://myetcd.default.svc.cluster.local:2379 | 94ed28b1cb999b71 |  3.5.12 |   20 kB |      true |      false |         5 |        309 |                309 |        |
+-----------------------------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
I have no name!@myetcd-0:/opt/bitnami/etcd$ etcdctl --cert $ETCD_CERT_FILE --key $ETCD_KEY_FILE --cacert $ETCD_TRUSTED_CA_FILE get / --prefix --keys-only
{"level":"warn","ts":"2024-03-22T13:13:13.767205Z","logger":"etcd-client","caller":"v3@v3.5.12/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0x40002b0c40/myetcd.default.svc.cluster.local:2379","attempt":0,"error":"rpc error: code = PermissionDenied desc = etcdserver: permission denied"}
Error: etcdserver: permission denied
```

I am not able to understand why it's giving me permission denied while I try to get the keys.

### What do you see instead?

```
I have no name!@myetcd-0:/opt/bitnami/etcd$ etcdctl --cert $ETCD_CERT_FILE --key $ETCD_KEY_FILE --cacert $ETCD_TRUSTED_CA_FILE get / --prefix --keys-only
{"level":"warn","ts":"2024-03-22T13:13:13.767205Z","logger":"etcd-client","caller":"v3@v3.5.12/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0x40002b0c40/myetcd.default.svc.cluster.local:2379","attempt":0,"error":"rpc error: code = PermissionDenied desc = etcdserver: permission denied"}
Error: etcdserver: permission denied
```
