### ISSUE TITLE
etcd config file extension should be yaml instead of yml

### ISSUE THREAD

**Issue by romanhirsh-guardicore** [bitnami/charts#24629]
### Name and Version

bitnami/etcd 9.5.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set custom configuration value
2. Deploy

### Are you using any custom parameters or values?
```yaml
  configuration: |
    quota-backend-bytes: 8589934592
    max-txn-ops: 2048
    max-wals: 0
```
### What is the expected behavior?

Etcd pod expects the configuration file at /opt/bitnami/etcd/conf/etcd.yaml

See: https://github.com/bitnami/containers/blob/main/bitnami/etcd/3.5/debian-12/rootfs/opt/bitnami/scripts/etcd-env.sh#L77

### What do you see instead?

Config map is mounted at  /opt/bitnami/etcd/conf/etcd.yml

### Additional information

The config map in this chart is mounted to /opt/bitnami/etcd/conf/etcd.yml, whereas the bitnami script look for the default config at /opt/bitnami/etcd/conf/etcd.yaml
