### ISSUE TITLE
could not download oci://registry-1.docker.io/bitnamicharts/postgresql: failed to authorize: failed to fetch anonymous token: unexpected status from GET request 

### ISSUE THREAD

**Issue by rcbandit111** [bitnami/charts#24623]
### Name and Version

bitnami/keycloak

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I downloaded keycloak helm chart from https://github.com/bitnami/charts/tree/main/bitnami/keycloak

I edited it this way:

```yaml
## PostgreSQL chart configuration
## ref: https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
## @param postgresql.enabled Switch to enable or disable the PostgreSQL helm chart
## @param postgresql.auth.postgresPassword Password for the "postgres" admin user. Ignored if `auth.existingSecret` with key `postgres-password` is provided
## @param postgresql.auth.username Name for a custom user to create
## @param postgresql.auth.password Password for the custom user to create
## @param postgresql.auth.database Name for a custom database to create
## @param postgresql.auth.existingSecret Name of existing secret to use for PostgreSQL credentials
## @param postgresql.architecture PostgreSQL architecture (`standalone` or `replication`)
##
postgresql:
  enabled: false
  auth:
    postgresPassword: ""
    username: bn_keycloak
    password: ""
    database: bitnami_keycloak
    existingSecret: ""
  architecture: standalone
## External PostgreSQL configuration
## All of these values are only used when postgresql.enabled is set to false
## @param externalDatabase.host Database host
## @param externalDatabase.port Database port number
## @param externalDatabase.user Non-root username for Keycloak
## @param externalDatabase.password Password for the non-root username for Keycloak
## @param externalDatabase.database Keycloak database name
## @param externalDatabase.existingSecret Name of an existing secret resource containing the database credentials
## @param externalDatabase.existingSecretHostKey Name of an existing secret key containing the database host name
## @param externalDatabase.existingSecretPortKey Name of an existing secret key containing the database port
## @param externalDatabase.existingSecretUserKey Name of an existing secret key containing the database user
## @param externalDatabase.existingSecretDatabaseKey Name of an existing secret key containing the database name
## @param externalDatabase.existingSecretPasswordKey Name of an existing secret key containing the database credentials
## @param externalDatabase.annotations Additional custom annotations for external database secret object
##
externalDatabase:
  host: jdbc:postgresql://11.1.1.1:5432/prod?currentSchema=keycloak
  port: 5432
  user: admin
  database: keycloak
  password: keycloak
  existingSecret: ""
  existingSecretHostKey: ""
  existingSecretPortKey: ""
  existingSecretUserKey: ""
  existingSecretDatabaseKey: ""
  existingSecretPasswordKey: ""
  annotations: {}
```

Basically, I disabled the default postgre and I added credentials for the external PostgreSQL database.

Then I run from Jenkins job:
```
      script {
                    withKubeConfig([credentialsId: 'kubernetes_credentials']) {
                        sh '''
                            cd keycloak
                            helm list
                            helm dependency build
                            helm upgrade --install keycloak --set image.tag=$IMAGE_TAG .
                        '''
                    }
                }         

```

But I get error:

```
Saving 2 charts
Downloading postgresql from repo oci://registry-1.docker.io/bitnamicharts
Save error occurred:  could not download oci://registry-1.docker.io/bitnamicharts/postgresql: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3Abitnamicharts%2Fpostgresql%3Apull&service=registry.docker.io: 401 Unauthorized
Error: could not download oci://registry-1.docker.io/bitnamicharts/postgresql: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3Abitnamicharts%2Fpostgresql%3Apull&service=registry.docker.io: 401 Unauthorized
[Pipeline] }
[kubernetes-cli] kubectl configuration cleaned up
```
What should be the proper way to install the helm chart manually?
