### ISSUE TITLE
need chart to configure elasticsearch backups to use azure blob storage to store snapshots

### ISSUE THREAD

**Issue by jeffersonjerome19** [bitnami/charts#24642]
### Name and Version

20.0.0

### What architecture are you using?

None

### What steps will reproduce the bug?

below is the existing chart to use filesystems
```yaml
extraVolumes:
  - name: snapshot-repository
    nfs:
      server: nfs.example.com # Please change this to your NFS server
      path: /share1
extraVolumeMounts:
  - name: snapshot-repository
    mountPath: /snapshots
snapshotRepoPath: "/snapshots"
```

### What do you see instead?

need chart to use azure blog storage
```yaml
extraVolumes:
  - name: snapshot-repository
    nfs:
      server: nfs.example.com # Please change this to your NFS server
      path: /share1
extraVolumeMounts:
  - name: snapshot-repository
    mountPath: /snapshots
snapshotRepoPath: "/snapshots"
```
