### ISSUE TITLE
Random values regenerating

### ISSUE THREAD

**Issue by gcezaralmeida** [bitnami/charts#24658]
### Name and Version

bitnami/harbor 20.1.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. I'm using Harbor 20.1.3 Chart from Bitnami with ArgoCD, some secrets keep regenerating and forcing ArgoCD to deploy a new replica set. I saw that this issue was solved in the original Harbor Repo. Is it possible to replicate here? 

https://github.com/goharbor/harbor-helm/pull/1612

### Are you using any custom parameters or values?
```yaml
      global:
        imagePullSecrets:
          - docker-registry
      service:
        type: Ingress
      ipFamily:
        ipv6:
          enabled: false
      exposureType: ingress
      nginx:
        replicaCount: 3
      portal:
        replicaCount: 3
      core:
        replicaCount: 3
      jobservice:
        jobLogger: database
        replicaCount: 3
        updateStrategy:
          type: Recreate
      registry:
        replicaCount: 3
      notary:
        replicaCount: 3
      signer:
        replicaCount: 3
      trivy:
        replicaCount: 3
      exporter:
        replicaCount: 3
      ingress:
        core:
          ingressClassName: nginx
          hostname: fortistack-harbor.corp.fortinet.com
          tls: false
          selfSigned: false
          extraTls:
            - hosts:
              - fortistack-harbor.corp.fortinet.com
              secretName: core-harbor-fortinet-tls
      adminPassword: "Harbor12345"
      externalURL: https://fortistack-harbor.corp.fortinet.com
      persistence:
        enabled: true
        imageChartStorage:
          disableredirect: true
          caBundleSecretName: s3-ca
          type: s3
          s3:
            region: us-west-1
            bucket: harbor
            accesskey: admin
            secretkey: 8rt&XuNY414e
            regionendpoint: http://minio.minio.svc:9000
            #encrypt: false
            secure: false
            skipverify: true
            v4auth: true
      postgresql:
        architecture: replication
        readReplicas:
          extendedConfiguration: |
            max_connections = 1024
      redis:
        architecture: replication
```

### What do you see instead?

![image](https://github.com/bitnami/charts/assets/25770754/a44e6de8-98a6-478d-9142-5b74f69db22c)
