### ISSUE TITLE
[bitnami/thanos] Thanos alerting rules expression  are statically set

### ISSUE THREAD

**Issue by pierreblais** [bitnami/charts#24651]
### Name and Version

bitnami/thanos

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Edit the `values.yaml` file for `bitnami/thanos` Helm charts
2. Deployed the helm chart with release name different from `thanos`

### Are you using any custom parameters or values?

The following values should be set to enable prometheus alerts:

```yaml
## @section Metrics parameters
metrics:
  ## @param metrics.enabled Enable the export of Prometheus metrics
  ##
  enabled: true
  ## Prometheus Operator ServiceMonitor configuration
  ##
  serviceMonitor:
    ## @param metrics.serviceMonitor.enabled Specify if a ServiceMonitor will be deployed for Prometheus Operator
    ##
    enabled: true
## PrometheusRule CRD configuration
  ##
  prometheusRule:
    ## @param metrics.prometheusRule.enabled If `true`, creates a Prometheus Operator PrometheusRule (also requires `metrics.enabled` to be `true`)
    ##
    enabled: true
    ## Configure prometheus rules
    ##
    default:
      ## @param metrics.prometheusRule.default.create would create all default prometheus alerts
      ##
      create: true
```

### What is the expected behavior?

The deployed prometheus rules should adapted to the deployment name and so should not be firing.

### What do you see instead?

The rule's regex expression are settled statically at `thanos` like if the helm release name was too. So all alerts are firing because any objects are founds

### Additional information

Here is an example of expression:
https://github.com/bitnami/charts/blob/916e47866cd0b509b361bf569f20c5b543703cea/bitnami/thanos/templates/alert-rule/absent_rules.yml#L36C9-L36C15
