### ISSUE TITLE
[bitnami/keycloak] Fail to create realm with keycloak-config-cli

### ISSUE THREAD

**Issue by dimara** [bitnami/charts#24668]
### Name and Version

bitnami/keycloak 19.3.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create a bare minimum realm JSON (I have created a new realm from the dashboard and exported it)
[test.json](https://github.com/bitnami/charts/files/14755884/test.json)

2. Create a configmap holding this realm.
   ```
   $ kubectl create configmap keycloak-realm -n test --from-file=test.json
   ```
4. Enable keycloak-config-cli in values with:
   ```yaml
   keycloakConfigCli:
     enabled: true
     existingConfigmap: "keycloak-realm"
   ```
5. Deploy keycloak:
   ```console
   $ helm upgrade --install  keycloak -n test -f values.yaml keycloak/
   Release "keycloak" does not exist. Installing it now.
   Error: failed post-install: 1 error occurred:
	* job keycloak-keycloak-config-cli failed: BackoffLimitExceeded
   ```

### Are you using any custom parameters or values?
```yaml
auth:
  adminUser: admin
  adminPassword: admin

keycloakConfigCli:
  enabled: true
  extraEnvVars:
  - name: KEYCLOAK_AVAILABILITYCHECK_TIMEOUT
    value: "900s"
  existingConfigmap: "keycloak-realm"

logging:
  level: INFO
```
### What is the expected behavior?

Helm install should succeed.

### What do you see instead?

keycloak-config-cli job failed:
```console
$ kubectl get pods -n test
NAME                                 READY   STATUS    RESTARTS   AGE
keycloak-0                           1/1     Running   0          64s
keycloak-keycloak-config-cli-lwp5c   0/1     Error     0          6s
keycloak-keycloak-config-cli-zf7qc   0/1     Error     0          63s
keycloak-postgresql-0                1/1     Running   0          64s
```

keycloak-config-cli job logs
```
2024-03-26 08:24:02.946 ERROR 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : Cannot create realm 'test': HTTP 500 Internal Server Error{"error":"unknown_error"}
```

keycloak logs:
```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "maxTemporaryLockouts" (class org.keycloak.representations.idm.RealmRepresentation), not marked as ignorable 
```

### Additional information

I think this is related with https://github.com/adorsys/keycloak-config-cli/issues/996.
maxTemporaryLockouts is only supported in 24.0.1. I understand that the latest keycloak-config-cli image supports both 23.0.7 and 24.0.1 but the default entry point is for 24.0.1.
```
docker inspect bitnami/keycloak-config-cli:5.11.1-debian-12-r0
...
            "Entrypoint": [
                "java",
                "-jar",
                "./keycloak-config-cli.jar"
            ],
```
```console
$ docker run --rm --entrypoint "/bin/sh" bitnami/keycloak-config-cli:5.11.1-debian-12-r0  -c "ls -la"
total 40396
drwxr-xr-x 3 root root     4096 Mar 12 12:47 .
drwxrwxr-x 5 root root     4096 Mar 12 12:54 ..
-rw-r--r-- 1 root root   118267 Mar 12 12:47 .spdx-keycloak-config-cli.spdx
-rw-r--r-- 1 root root 20568402 Mar 12 12:21 keycloak-config-cli-23.0.7.jar
-rw-r--r-- 1 root root 20659256 Mar 12 12:21 keycloak-config-cli-24.0.1.jar
lrwxrwxrwx 1 root root       63 Mar 12 12:21 keycloak-config-cli.jar -> /opt/bitnami/keycloak-config-cli/keycloak-config-cli-24.0.1.jar
drwxr-xr-x 2 root root     4096 Mar 12 12:31 licenses
```

I had to explicitly set:
```yaml
keycloakConfigCli:
  command:
  - java
  - -jar
  - /opt/bitnami/keycloak-config-cli/keycloak-config-cli-23.0.7.jar
```
to make this work. Maybe this should be the default since AppVersion is 23.0.7.
