### ISSUE TITLE
[thanos] index-cache config parameter set, but no configmap created and/or mounted, but is referenced via parameter

### ISSUE THREAD

**Issue by sfhl** [bitnami/charts#24678]
### Name and Version

bitnami/thanos 14.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

render chart templates and apply

### Are you using any custom parameters or values?

```yaml
...
storegateway:
  enabled: true
  logLevel: "{{ k8s_vars['ops']['thanos']['loglvl'] }}"
  persistence: {storageClass: "csi-disk"}
  extraFlags: [--index-cache-size=500MB, --chunk-pool-size=500MB, --max-time=-12h]
...
indexCacheConfig:
  type: MEMCACHED
  config:
    addresses: [memcached:11211]
    timeout: 0s
    max_idle_connections: 500
    max_async_concurrency: 200
    max_async_buffer_size: 10000
    max_get_multi_concurrency: 200
    max_item_size: 0
    max_get_multi_batch_size: 0
    dns_provider_update_interval: 10s
    auto_discovery: false
  enabled_items: []
  ttl: 1h
...
```

### What is the expected behavior?

An index-cache ConfigMap object is created, a corresponding volume & volumemount is created within the storegateway statefulset object and is used by in-container binary (parameter)

### What do you see instead?

The parameter `--index-cache.config-file=/conf/index-cache.yml` is set, the config block is given, but no configmap is created, no volume is created, no config file mounted and so the pod/container fails to satrt, because of the missing, but referenced `/conf/index-cache.yml`
