### ISSUE TITLE
[bitnami/milvus] use of serviceAccount for external S3 authentication fails on prepare-milvus init contianer

### ISSUE THREAD

**Issue by christian-nickerson-faculty** [bitnami/charts#24691]
### Name and Version

bitnami/milvus:5.6.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create an EKS Cluster, with private subnets with EBS CSI Drivers
2. Create an S3 bucket (to be used in place of MinIO)
3. Create an IAM role and service account with relevant access to an s3 bucket
4. Helm install the chart

### Are you using any custom parameters or values?

```yaml
  attu:
    enabled: false

  minio:
    enabled: false

  externalS3:
    enabled: true
    host: "https://BUCKET_NAME.s3.REGION.amazonaws.com"
    bucket: "BUCKET_NAME"
    port: 443
    cloudProvider: "aws"
    iamEndpoint: "iam.amazonaws.com"
    useSSL: true
    useIAM: true

  dataCoord:
    serviceAccount:
      create: false
      name: "SERVICE_ACCOUNT_NAME"

  dataNode:
    serviceAccount:
      create: false
      name: "SERVICE_ACCOUNT_NAME"

  queryCoord:
    serviceAccount:
      create: false
      name: "SERVICE_ACCOUNT_NAME"

  queryNode:
    serviceAccount:
      create: false
      name: "SERVICE_ACCOUNT_NAME"

  indexCoord:
    serviceAccount:
      create: false
      name: "SERVICE_ACCOUNT_NAME"

  indexNode:
    serviceAccount:
      create: false
      name: "SERVICE_ACCOUNT_NAME"

  rootCoord:
    serviceAccount:
      create: false
      name: "SERVICE_ACCOUNT_NAME"

  proxy:
    serviceAccount:
      create: false
      name: "SERVICE_ACCOUNT_NAME"
```

### What is the expected behavior?

when deploying the chart, all containers should not try to use s3 access keys from env vars, and instead natively access the s3 api via is service account privileges

### What do you see instead?

when deploying the chart, all init containers successfully terminate, except for `prepare-milvus`.

The init container, looks for the access key `MILVUS_S3_ACCESS_ID` and `MILVUS_S3_SECRET_ACCESS_KEY`, which are not created when `existingSecret` is empty (see below from [`externals3-secret.yaml`](https://github.com/bitnami/charts/blob/main/bitnami/milvus/templates/externals3-secret.yaml#L6))

```yaml
{{- if and (not .Values.minio.enabled) (not .Values.externalS3.existingSecret) .Values.enableS3 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-externals3" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: mivus
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ .Values.externalS3.existingSecretAccessKeyIDKey }}: {{ .Values.externalS3.accessKeyID | b64enc | quote }}
  {{ .Values.externalS3.existingSecretKeySecretKey }}: {{ .Values.externalS3.accessKeySecret | b64enc | quote }}
{{- end }}
```

However, the `prepare-milvus` init container, is expecting there to be an `existingSecret` when minio.enabled=false (see below from [`_helpers.tpl`](https://github.com/bitnami/charts/blob/main/bitnami/milvus/templates/_helpers.tpl#L996)

```yaml
{{- if and (include "milvus.s3.deployed" .context) }}
- name: MILVUS_S3_ACCESS_ID
  valueFrom:
    secretKeyRef:
      name: {{ include "milvus.s3.secretName" .context }}
      key: {{ include "milvus.s3.accessKeyIDKey" .context }}
- name: MILVUS_S3_SECRET_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: {{ include "milvus.s3.secretName" .context }}
      key: {{ include "milvus.s3.secretAccessKeyKey" .context }}
```

I suspect that amending the above with the below would remove the referenced secrets and allow the init container to access s3 via its service account permissions (as I assume is intended?) and reflect the control flow logic in `externals3-secret.yaml`

```yaml
{{- if and (include "milvus.s3.deployed" .context) (not .Values.externalS3.existingSecret) }}
- name: MILVUS_S3_ACCESS_ID
  valueFrom:
    secretKeyRef:
      name: {{ include "milvus.s3.secretName" .context }}
      key: {{ include "milvus.s3.accessKeyIDKey" .context }}
- name: MILVUS_S3_SECRET_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: {{ include "milvus.s3.secretName" .context }}
      key: {{ include "milvus.s3.secretAccessKeyKey" .context }}
```
