### ISSUE TITLE
[bitnami/grafana] Using existing secret results in ServiceAccount with broken secret link

### ISSUE THREAD

**Issue by bpfoster** [bitnami/charts#24736]
### Name and Version

bitnami/grafana 10.0.3

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Configure grafana with `admin.existingSecret`, with a name that doesn't match the default convention
2. Observe that the ServiceAccount lists a secret with the name that would have been created if the chart created the admin secret

### Are you using any custom parameters or values?

```yaml
admin:
  existingSecret: foo
```

### What is the expected behavior?

The service account lists the configured secret, not the default (non-existent in this case) secret.

### What do you see instead?

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zzz-grafana
  namespace: "default"
  labels:
    app.kubernetes.io/instance: zzz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 10.4.1
    helm.sh/chart: grafana-10.0.3
secrets:
  - name: zzz-grafana-admin
  - name: zzz-grafana-datasources
automountServiceAccountToken: false
```

### Additional information

I have been running like this, and only noticed when I ran a misconfiguration scanner against the cluster.  So I'm not sure if the ServiceAccount really even needs access to the admin secret.
