### ISSUE TITLE
[bitnami/kafka] How to implement auto-scaling with multiple broker with Kubernetes?

### ISSUE THREAD

**Issue by DharmiVekariya** [bitnami/charts#24731]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am creating micro-services and implementing Kafka for event streaming. For Kafka, using 'bitnami/kafka' image along with persistent volume (PV) and persistent volume claim (PVC) configurations. It functions well for a single Kafka broker. However, now I require auto-scaling functionality for multiple brokers, with the PVs managed dynamically. Please check .yaml configuration for the current implementation.

What changes are required to fulfill the requirement of auto-scaling, multiple brokers with Manage PV?

### Are you using any custom parameters or values?

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  replicas: 1
  serviceName: zookeeper
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:3.6.3
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: peer
            - containerPort: 3888
              name: leader-election
          volumeMounts:
            - name: zookeeper-data
              mountPath: /data
      volumes:
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: zookeeper-pvc

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          env:
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"
            - name: KAFKA_CFG_NODE_ID
              value: "0"
          ports:
            - containerPort: 9092
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - port: 2181
      targetPort: 2181
  clusterIP: None
  selector:
    app: zookeeper

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/zookeeper
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeName: zookeeper-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /bitnami/kafka/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeName: kafka-pv

```

### What is the expected behavior?

Able to auto-scaling with maintaining PV and PVC for multiple brokerbrokers.

### What do you see instead?

- Above .ymal file changing replicas to 2. When I increase replica it gives an error that PV is not allocated to more than one broker.

![image](https://github.com/bitnami/charts/assets/109334059/de26cb88-7cf4-4227-bbff-cf2164dbb12c)

![image](https://github.com/bitnami/charts/assets/109334059/d82766d9-a482-49ae-812c-bc44275cb871)

![image](https://github.com/bitnami/charts/assets/109334059/47a3b880-eec2-4ee2-bf9b-e8eec6f7a94a)

![image](https://github.com/bitnami/charts/assets/109334059/a3b97c37-2e44-459c-a083-7ea87f41ae88)
