### ISSUE TITLE
[bitnami/rabbitmq] Using existing password secret results in ServiceAccount with broken secret link

### ISSUE THREAD

**Issue by bpfoster** [bitnami/charts#24738]
### Name and Version

bitnami/rabbitmq 13.0.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Configure rabbitmq with `auth.existingPasswordSecret`, with a name that doesn't match the default convention
2. Observe that the ServiceAccount lists a secret with the name that would have been created if the chart created the admin secret

### Are you using any custom parameters or values?

```yaml
auth:
  existingPasswordSecret: foo
```

### What is the expected behavior?

The service account lists the configured secret, not the default (non-existent in this case) secret.

### What do you see instead?

```yaml
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: zzz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/version: 3.12.13
    argocd.argoproj.io/instance: zzz
    helm.sh/chart: rabbitmq-13.0.0
  name: zzz-rabbitmq
  namespace: default
secrets:
- name: zzz-rabbitmq
- name: zzz-rabbitmq-token-lgkwr
```

### Additional information

I have been running like this for quite a while, and only noticed when I ran a misconfiguration scanner against the cluster. So I'm not sure if the ServiceAccount really even needs access to the admin secret.
