### ISSUE TITLE
[bitnami/mongodb] Using existing auth secret results in ServiceAccount with broken secret link

### ISSUE THREAD

**Issue by bpfoster** [bitnami/charts#24740]
### Name and Version

bitnami/mongodb 15.1.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Configure mongodb with `auth.existingSecret`, with a name that doesn't match the default convention
2. Observe that the ServiceAccount lists a secret with the name that would have been created if the chart created the admin secret

### Are you using any custom parameters or values?

```yaml
auth:
  existingSecret: foo
```

### What is the expected behavior?

The service account lists the configured secret, not the default (non-existent in this case) secret.

### What do you see instead?

```yaml
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: zzz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/version: 7.0.7
    argocd.argoproj.io/instance: zzz
    helm.sh/chart: mongodb-15.1.0
  name: zzz-mongodb
  namespace: default
secrets:
- name: zzz-mongodb
- name: zzz-mongodb-token-nh5dt
```

### Additional information

I have been running like this for quite a while, and only noticed when I ran a misconfiguration scanner against the cluster. So I'm not sure if the ServiceAccount really even needs access to the admin secret.
