### ISSUE TITLE
Kibana fails to open secret content on OpenShift

### ISSUE THREAD

**Issue by ygalblum** [bitnami/charts#24762]
### Name and Version

bitnami/kibana 11.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Relevant only for OpenShift

### Are you using any custom parameters or values?

```yaml
elasticsearch:
  security:
    tls:
      enabled: true
      existingSecret: < SecretName >
      usePemCerts: true
```

### What is the expected behavior?

Kibana should be able to access the certificates in the secret

### What do you see instead?

Kibana returns a permissions error

### Additional information

The root cause if the `securityContext` of the `initContainer` not being templated for OpenShift
