### ISSUE TITLE
The nameOverride for mysql breaks startup probe

### ISSUE THREAD

**Issue by elct9620** [bitnami/charts#24776]
### Name and Version

bitnami/mysql:10.1.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. create a Helm chart
2. add `bitnami/mysql` as dependency
3. set values with `nameOverride`
```yaml
mysql:
  enabled: true
  nameOverride: app-mysql
  auth:
    username: example
    password: example
    database: example
```
4. install the chart
5. the MySQL server is unable to pass the startup probe due to `rootPassword` is incorrect

```
Startup probe failed: mysqladmin: [Warning] Using a password on the command line interface can be insecure. mysqladmin: connect to server at 'localhost' failed error: 'Access denied for user 'root'@'localhost' (using password: YES)'
```

### Are you using any custom parameters or values?

```yaml
mysql:
  enabled: true
  nameOverride: app-mysql
  auth:
    username: example
    password: example
    database: example
```

### What is the expected behavior?

The MySQL server is running correctly.

### What do you see instead?

1. If remove `nameOverride` the startup probe works correctly.
2. If install `bitnami/mysql` directly the startup probe works correctly.
  * Without `nameOverride` work correctly
  * With `nameOverride` work correctly
3. Add `rootPassword` to `values.yaml` not help
4. Forward the pod using `mysql -h {IP} -u root -p` to connect the root password generated or manual config both incorrect

### Additional information

1. ~~If `nameOverride` is configured I get 2 same services same `example-app-mysql`~~
2. ~~If `nameOverride` is not configured I get 2 different service `example-app-mysql` and `example-app-mysql-headless`~~
