### ISSUE TITLE
[bitnami/schema-registry] cannot overwrite table with non table for schema-registry.kafka.listeners

### ISSUE THREAD

**Issue by kozdincer** [bitnami/charts#24770]
### Name and Version

bitnami/schema-registry 18.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. In kubernetes environment version: v1.28.5
2. Install helm package
3. With values.yaml below

reference issue: https://github.com/bitnami/charts/issues/17126

### Are you using any custom parameters or values?

```yaml
kafka:
  enabled: false
  auth:
    protocol: {}
  service:
    ports:
      client: {}
externalKafka:
  brokers:
    - PLAINTEXT://hm-kafka-kafka-bootstrap.hm-kafka.svc:9092
```

### What is the expected behavior?

Installed successfully

### What do you see instead?
```
coalesce.go:286: warning: cannot overwrite table with non table for schema-registry.kafka.listeners (map[client:map[protocol:PLAINTEXT]])
Error: UPGRADE FAILED: template: schema-registry/templates/statefulset.yaml:17:14: executing "schema-registry/templates/statefulset.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: /kafka/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: /kafka/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```
### Additional information

What is wrong with the configuration? Is there an example configuration?
