### ISSUE TITLE
[bitnami/flink] Flink network policies causing issue

### ISSUE THREAD

**Issue by daroga0002** [bitnami/charts#24784]
### Name and Version

bitnami/flink:1.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Just execute:
`helm template flink bitnami/flink`

and look into manifests for network policices:

```
---
# Source: flink/templates/jobmanager/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: flink-jobmanager
  namespace: "default"
  labels:
    app.kubernetes.io/instance: flink
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: flink
    app.kubernetes.io/version: 1.19.0
    helm.sh/chart: flink-1.0.1
    app.kubernetes.io/part-of: flink
    app.kubernetes.io/component: jobmanager
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: flink
      app.kubernetes.io/name: flink
      app.kubernetes.io/part-of: flink
      app.kubernetes.io/component: jobmanager
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - ports:
        - port: 6124
        - port: 6123
        - port: 8081
---
# Source: flink/templates/taskmanager/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: flink-taskmanager
  namespace: "default"
  labels:
    app.kubernetes.io/instance: flink
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: flink
    app.kubernetes.io/version: 1.19.0
    helm.sh/chart: flink-1.0.1
    app.kubernetes.io/part-of: flink
    app.kubernetes.io/component: taskmanager
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: flink
      app.kubernetes.io/name: flink
      app.kubernetes.io/part-of: flink
      app.kubernetes.io/component: taskmanager
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - ports:
        - port: 6121
        - port: 6122
```

### What is the expected behavior?

Network policies should allow to work software in correct way

### What do you see instead?

there is issue between flink jobmanager <> taskmanager communication what is causing it is not working correctly

### Additional information

Due nature of flink which rely on multiple ports to communicate existing network policies are not enough. Taskmanager uses ranges of ports which by default are allocated dynamiclly:

**metrics.internal.query-service.port**
The port range used for Flink's internal metric query service. Accepts a list of ports (“50100,50101”), ranges(“50100-50200”) or a combination of both. It is recommended to set a range of ports to avoid collisions when multiple Flink components are running on the same machine. Per default Flink will pick a random port.

**taskmanager.data.bind-port**
The task manager's bind port used for data exchange operations. Also accepts a list of ports (“50100,50101”), ranges (“50100-50200”) or a combination of both. If not configured, 'taskmanager.data.port' will be used.

**taskmanager.rpc.port**
The external RPC port where the TaskManager is exposed. Accepts a list of ports (“50100,50101”), ranges (“50100-50200”) or a combination of both. It is recommended to set a range of ports to avoid collisions when multiple TaskManagers are running on the same machine.

I dont know does those are all becuase we disabled network policices to get this working.
