### ISSUE TITLE
[bitnami/postgresql] Adding Hashicorp Vault to Postgresql helm chart the pod remains in status init

### ISSUE THREAD

**Issue by kometen** [bitnami/charts#24849]
### Name and Version

bitnami/postgresql

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When I add Hashicorp Vault to the PostgreSQL helm chart the pod will be in status init indefinitely. The pod is deployed fine when Vault is not added. I have a spring boot app that is configured the same way and this mounts the `/vault/secrets` folder.

### Are you using any custom parameters or values?

values.yaml:

```yaml
postgresql:
  serviceAccount:
    name: database-sa
  tls:
    enabled: true
    autoGenerated: true
  primary:
    automountServiceAccountToken: 'true'
    podAnnotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/role: 'database'
      vault.hashicorp.com/agent-inject-secret-database-config.txt: 'secret/data/database/faktura'
    persistence:
      storageClass: "nfs-csi"
      accessModes: ["ReadWriteOnce"]
      size: 1Gi
```

### What is the expected behavior?

That the pod mounts `/vault/secrets` folder.

### What do you see instead?

I get this error from vault-agent-init:

```
2024-04-03T13:40:05.929Z [INFO]  agent.auth.handler: authenticating
2024-04-03T13:40:35.929Z [ERROR] agent.auth.handler: error authenticating: error="Put \"http://vault.vault.svc:8200/v1/auth/kubernetes/login\": dial tcp 10.152.183.147:8200: i/o timeout" backoff=1.99s
```

### Additional information

When I comment out (disable) the line `vault.hashicorp.com/role: 'database'` I get a message from Vault that `role` is missing.

**Comment by kometen** [comment]
I think the reason is the postgresql helm chart is readonly. From the vault-init-agent:

```
agent.sink.file: file sink configured: path=/home/vault/.vault-token mode=-rw-r-----
```

So I probably need to change the vault-home-folder to a rw-fs. I added

```
postgresql:
  primary:
    extraVolumeMounts:
      - name: vault-volume
        mountPath: /home/vault
    extraVolumes:
      - name: vault-volume
        emptyDir: {}
    automountServiceAccountToken: 'true'
    podAnnotations:
      vault.hashicorp.com/agent-run-as-user: '1001'
      vault.hashicorp.com/agent-run-as-group: '1001'
```

and specified uid and guid 1001 for the vault-user. I may mount the vault-volume incorrectly though.
