### ISSUE TITLE
jupyterhub: proxy.service annotations are not being applied to `public-proxy` service

### ISSUE THREAD

**Issue by edu-gi** [bitnami/charts#24856]
### Name and Version

bitnami/jupyterhub 6.1.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. In an AWS EKS cluster with an external DNS using the `aws-ia/terraform-aws-eks-blueprints` [add on](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/7755fb6ec97139d34b7d01467ce7f20164cbd24a/main.tf#L2240)) configured to use AWS Route 53.
2. Deploy the Jupyterhub helm chart to the cluster (I'm using Flux CD) by updating a manifest with the Bitnami Jupyterhub Helm release, where some values have been filled in. Deployed to a `jupyterhub` namespace. One of these is an annotation in `proxy.service.annotations`, with the value `external-dns.alpha.kubernetes.io/hostname: jupyterhub.example.com`. This is so the external DNS can automatically add the specified desired domain to Route 53 and the hub can be accessed via this domain.
3. Run `kubectl describe helmrelease -n jupyterhub` and confirm the values specified in the manifest are present (they are).
4. Once the service is up and running , run `kubectl describe svc jupyterhub-proxy-public -n jupyterhub`. I notice the `external-dns.alpha.kubernetes.io/hostname` annotation is missing.
5. logs for external-dns and load balancer controller pods show no errors. jupyterhub-proxy pod logs show no errors. Events for the jupyterhub namespace shows no errors.

### Are you using any custom parameters or values?

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  interval: 2m
  install:
    remediation:
      retries: -1
  values:
    hub:
      password: XXXXXX
    proxy:
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: jupyterhub.example.com
    postgresql:
      enabled: true
  chart:
    spec:
      chart: jupyterhub
      version: "6.1.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: bitnami
      interval: 1m
```

### What is the expected behavior?

I would expect the `external-dns.alpha.kubernetes.io/hostname` annotation to be added to the `proxy-public` service, which would be picked up by the external DNS and a record would be added to AWS Route 53 and enable use of `jupyterhub.example.com` to access the hub.

### What do you see instead?

The annotation is missing from the proxy-public service. 
`kubectl describe svc jupyterhub-proxy-public -n jupyterhub`:

```
Name:                     jupyterhub-proxy-public
Namespace:                jupyterhub
Labels:                   app.kubernetes.io/component=proxy
                          app.kubernetes.io/instance=jupyterhub
                          app.kubernetes.io/managed-by=Helm
                          app.kubernetes.io/name=jupyterhub
                          app.kubernetes.io/version=4.6.1
                          helm.sh/chart=jupyterhub-6.1.4
                          helm.toolkit.fluxcd.io/name=jupyterhub
                          helm.toolkit.fluxcd.io/namespace=jupyterhub
Annotations:              meta.helm.sh/release-name: jupyterhub
                          meta.helm.sh/release-namespace: jupyterhub
Selector:                 app.kubernetes.io/component=proxy,app.kubernetes.io/instance=jupyterhub,app.kubernetes.io/name=jupyterhub
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       XXXXXXX
IPs:                      XXXXXXX
LoadBalancer Ingress:     k8s-jupyterh-jupyterh-XXXXXXXXXXXXXXXX.elb.us-east-1.amazonaws.com
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  XXXXX/TCP
Endpoints:                XXXXXXX
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

### Additional information

I can access the hub through the EXTERNAL IP given for the `proxy-public` service. Other than the annotation, everything seems to be working as expected.
I know the external DNS works because I've deployed the bitnami mlflow chart using the `external-dns.alpha.kubernetes.io/hostname` annotation and have had success there (a record is created in AWS Route 53, I am able to access the service via the domain I specify). If I run `kubectl describe` on the mlflow service being deployed by the chart, I see the `external-dns.alpha.kubernetes.io/hostname` annotation.
