### ISSUE TITLE
[bitnami/contour] envoy custom readiness checks are applied to shutdown manager for deployment and missing from daemonset

### ISSUE THREAD

**Issue by seth-epps** [bitnami/charts#24859]
### Name and Version

bitnami/contour 17.0.1

### What architecture are you using?

arm64

## DaemonSet
Run helm template with the chart values.yaml defined below and observe the daemonset pod container spec still uses the default readiness probe
```yaml
❯ helm template contour-envoy PATH/TO/CHART/REPO/bitnami/contour -f values.yaml | yq 'select(.kind == "DaemonSet" and .metadata.name == "contour-envoy-envoy") | .spec.template.spec.containers[] | select(.name == "envoy") | .readinessProbe'
```

and the shutdown manager is unchanged
```yaml
❯ helm template contour-envoy PATH/TO/CHART/REPO/bitnami/contour -f values.yaml| yq 'select(.kind == "DaemonSet" and .metadata.name == "contour-envoy-envoy") | .spec.template.spec.containers[] | select(.name == "shutdown-manager") | .readinessProbe'
```

## Deployment
Running the same helm template with deployment-values.yaml defined below (ie adding `envoy.kind: deployment`) and observe the container spec uses the default readiness probe
```yaml
❯ helm template contour-envoy PATH/TO/CHART/REPO/bitnami/contour -f deployment-values.yaml | yq 'select(.kind == "Deployment" and .metadata.name == "contour-envoy-envoy") | .spec.template.spec.containers[] | select(.name == "envoy") | .readinessProbe'
```

and the shutdown manager is overridden
```yaml
❯ helm template contour-envoy PATH/TO/CHART/REPO/bitnami/contour -f deployment-values.yaml | yq 'select(.kind == "Deployment" and .metadata.name == "contour-envoy-envoy") | .spec.template.spec.containers[] | select(.name == "shutdown-manager") | .readinessProbe'
```

## values.yaml
```yaml
# values.yaml
envoy:
  # custom envoy readiness check to hit a different port
  customReadinessProbe:
    failureThreshold: 3
    httpGet:
      path: /ready
      port: 8003
      scheme: HTTP
```

## deployment-values.yaml
```yaml
# deployment-values.yaml
envoy:
  kind: deployment
  # custom envoy readiness check to hit a different port
  customReadinessProbe:
    failureThreshold: 3
    httpGet:
      path: /ready
      port: 8003
      scheme: HTTP

```

### What is the expected behavior?

In both cases specifying a custom readiness probe should override the envoy container readiness probe

## DaemonSet
```yaml
❯ helm template contour-envoy PATH/TO/CHART/REPO/bitnami/contour -f values.yaml | yq 'select(.kind == "DaemonSet" and .metadata.name == "contour-envoy-envoy") | .spec.template.spec.containers[] | select(.name == "envoy") | .readinessProbe'
httpGet:
  path: /ready
  port: 8002
initialDelaySeconds: 10
periodSeconds: 3
timeoutSeconds: 1
successThreshold: 1
failureThreshold: 3
```

shutdown manager
```yaml
❯ helm template contour-envoy PATH/TO/CHART/REPO/bitnami/contour -f values.yaml| yq 'select(.kind == "DaemonSet" and .metadata.name == "contour-envoy-envoy") | .spec.template.spec.containers[] | select(.name == "shutdown-manager") | .readinessProbe'
exec:
  command:
    - pgrep
    - contour
initialDelaySeconds: 10
periodSeconds: 3
timeoutSeconds: 1
successThreshold: 1
failureThreshold: 3
```

## Deployment

```yaml
❯ helm template contour-envoy PATH/TO/CHART/REPO/bitnami/contour -f deployment-values.yaml | yq 'select(.kind == "Deployment" and .metadata.name == "contour-envoy-envoy") | .spec.template.spec.containers[] | select(.name == "envoy") | .readinessProbe'
httpGet:
  path: /ready
  port: 8002
initialDelaySeconds: 10
periodSeconds: 3
timeoutSeconds: 1
successThreshold: 1
failureThreshold: 3
```

shutdown manager
```yaml
❯ helm template contour-envoy PATH/TO/CHART/REPO/bitnami/contour -f deployment-values.yaml | yq 'select(.kind == "Deployment" and .metadata.name == "contour-envoy-envoy") | .spec.template.spec.containers[] | select(.name == "shutdown-manager") | .readinessProbe'
failureThreshold: 3
httpGet:
  path: /ready
  port: 8003
  scheme: HTTP
```
