### ISSUE TITLE
[bitnami/thanos]  Unable to configure tls for thanos query frontend

### ISSUE THREAD

**Issue by sakeebshaikh74** [bitnami/charts#24893]
### Name and Version

thanos /13.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In values.yaml i made the following entry
```
https:
  ## @param https.enabled Set to true to enable HTTPS. Requires a secret containing the certificate and key.
  ##
  **enabled: true**
  ## @param https.autoGenerated Create self-signed TLS certificates.
  ##
  autoGenerated: true
  ## @param https.existingSecret Existing secret containing your own server key and certificate
  ##
  existingSecret: ""
  #existingSecret: "thanos-qf.acmp-thanos-eks-53"
  ## @param https.certFilename
  ##
  certFilename: "tls.crt"
  #certFilename: "thanos-qf.acmp-thanos-eks-53.crt"
  ## @param https.keyFilename
  ##
  keyFilename: "tls.key"
  #keyFilename: "thanos-qf.acmp-thanos-eks-53.key"
  ## @param https.caFilename
  ##
  caFilename: "ca.crt"
```
ingress is off for all the components

i have opened the following componetns svc as nodeport 
compactor, queryFrontend , storegateway

out of which compactor and storegateway UI is working fine with https but queryFrontend  fails with error

![image](https://github.com/bitnami/charts/assets/163878399/325153ba-5639-47dd-82c9-14bd6c8ad89a)

### Are you using any custom parameters or values?

no

### What is the expected behavior?

UI should open in https mode

### What do you see instead?

![image](https://github.com/bitnami/charts/assets/163878399/47cd4c4e-8c27-43b4-9fe8-31c36eb0a465)
