### ISSUE TITLE
[kibana-chart] plugins are not getting installed with version 5.0.17

### ISSUE THREAD

**Issue by optimus-kart** [bitnami/charts#2490]
**Which chart**:
kibana 5.0.17

**Describe the bug**
plugins are not getting installed

**To Reproduce**
install the helm with following command
`helm install kibana-svc bitnami/kibana --namespace efk --values values.yaml --version "5.0.17"`

the content of values.yaml being

```
#
plugins:
  - https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.6.2-0.1.31.zip

extraVolumes:
  - name: logtrail-config
    configMap:
      name: logtrail

## Array to add extra mounts (normally used with extraVolumes)
##
extraVolumeMounts:
  - name: logtrail-config
    mountPath: /usr/share/kibana/plugins/logtrail/logtrail.json
    subPath: logtrail.json

```
**Expected behavior**
Plugins should be installled sucessfully

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

```
