### ISSUE TITLE
[bitnami/elasticsearch] fullnameOverride has no effect

### ISSUE THREAD

**Issue by d3bt3ch** [bitnami/charts#2492]
Please fix the chart. `fullnameOverride` has no effect. `Fix line 38 in _helpers.tpl`

**Comment by carrodher** [comment]
I am not able to see any error related to that, in order to be able to reproduce your issue, can you provide more information? When creating a new issue a template appears asking for specific information, this is really useful to reproduce the issue on our side.

I am trying with the latest elasticsearch version and this is the result:
- I used the[ `master-statefulset.yaml` template](https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/templates/master-statefulset.yaml#L151) as example, specifically the `volumes` section:
```yaml
      volumes:
        {{- if .Values.sysctlImage.enabled }}
        - name: initcontainer-script
          configMap:
            name: {{ include "elasticsearch.fullname" . }}-initcontainer
            defaultMode: 0755
        {{- end }}
```
- In the above template, the `configMap` name depends on the `fullname` helper.
- Rendering this template without set the fullnameOverride I have the following output:
```console
$ helm template MYRELEASE bitnami/elasticsearch --set sysctlImage.enabled=true
```
```yaml
      volumes:
        - name: initcontainer-script
          configMap:
            name: MYRELEASE-elasticsearch-initcontainer
            defaultMode: 0755
```
- As you can see, the `name` was rendered with the release name (MYRELEASE).
- Now, if I maintain the same release name but also set the `fullnameOverride` parameter the `configMap` name uses the `fullnameOverride` parameter (MYFULLNAME in this case) instead of the release name:
```console
$ helm template MYRELEASE bitnami/elasticsearch --set sysctlImage.enabled=true --set fullnameOverride=MYFULLNAME
```
```yaml
      volumes:
        - name: initcontainer-script
          configMap:
            name: MYFULLNAME-initcontainer
            defaultMode: 0755
```
