### ISSUE TITLE
[kafka] Unable to set correct advertised listeners for external access behind TCP Ingress

### ISSUE THREAD

**Issue by dergyitheron** [bitnami/charts#25030]
### Name and Version

bitnami/kafka 28.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have a K3s cluster with 3 worker nodes, which have built-in LB (klipper) and Ingress controller (traefik). I have successfully deployed bitnami/kafka helm chart with some custom values listed below. I can connect from within the K3s cluster and produce and consume messages.

Now I'm trying to set up external access including IngressRouteTCP and have some issues with advertised listeners. The consumer connects to the bootstrap server but gets advertised listeners with Kafka ports, not the ingress entrypoint ports.

The traefik entrypoint is on port 443 so I need for the consumer to receive the advertised listener with the external URL set in IngressRouteTCP and port 443.

I've also tried ClusterIP type for external access but that allows only one domain for the service to be specified, so advertised listeners values are even more incorrect (same for every kafka node). 

I've also noticed that external access service of type ClusterIP and LoadBalancer creates separate services for each pod, so since I have Ingress on top with the domain for each pod it doesn't really matter which one I use as it ends up in the correct pod every time.

What is the best way to approach this and set up correctly?

### Are you using any custom parameters or values?

Values
```yaml
global:
  storageClass: "local-path"
commonLabels:
  {
    app.kubernetes.io/name: kafka,
    app.kubernetes.io/instance: kafka,
    app.kubernetes.io/component: kafka,
    app.kubernetes.io/part-of: kafka,
  }
diagnosticMode:
  enabled: false
image:
  pullPolicy: IfNotPresent
listeners:
  client:
    containerPort: 9092
    protocol: SASL_PLAINTEXT
    name: CLIENT
  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: PLAINTEXT
    sslClientAuth: ""
  interbroker:
    containerPort: 9094
    protocol: PLAINTEXT
    name: INTERNAL
    sslClientAuth: ""
  external:
    containerPort: 9095
    protocol: SASL_PLAINTEXT
    name: EXTERNAL
    sslClientAuth: ""
sasl:
  enabledMechanisms: PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
  client:
    users:
      - adminuser
    passwords: "adminpassword"
controller:
  replicaCount: 3
  resourcesPreset: "none"
  resources:
    limits:
      memory: 2Gi
  nodeSelector:
    node-role.kubernetes.io/storage-worker: "true"
  persistence:
    enabled: true
    storageClass: "local-path"
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    mountPath: /bitnami/kafka
externalAccess:
  enabled: true
  controller:
    service:
      type: LoadBalancer
      ports:
        external: 9095
      loadBalancerNames:
        - "kafka-0.my-domain.org"
        - "kafka-1.my-domain.org"
        - "kafka-2.my-domain.org"
  broker:
    service:
      type: LoadBalancer
      ports:
        external: 9095
      loadBalancerNames: 
        - "kafka-0.my-domain.org"
        - "kafka-1.my-domain.org"
        - "kafka-2.my-domain.org"
kraft:
  enabled: true
  clusterId: 1
zookeeper:
  enabled: false
```

IngressRouteTCP
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: kafka-tls-ingress
  namespace: kafka
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`kafka-0.my-domain.org`)
      services:
        - name: kafka-controller-0-external
          port: 9095
    - match: HostSNI(`kafka-1.my-domain.org`)
      services:
        - name: kafka-controller-1-external
          port: 9095
    - match: HostSNI(`kafka-2.my-domain.org`)
      services:
        - name: kafka-controller-2-external
          port: 9095
  tls:
    secretName: kafka-tls-secret
```

### What is the expected behavior?

It is unclear to me how I can modify the advertised listeners to return the external listener with the correct domain and correct port for the kafka node.

I expect to see this (for first kafka node, notice the port for EXTERNAL):
```
advertised.listeners = CLIENT://kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092,INTERNAL://kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9094,EXTERNAL://kafka-0.my-domain.org:443
```

I only expect to connect to kafka from inside of the cluster or outside via ingress route but I don't want to expose any additional ports outside.

### What do you see instead?

```
advertised.listeners = CLIENT://kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092,INTERNAL://kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9094,EXTERNAL://kafka-0.my-domain.org:9095
```

The external listener advertises on port 9095. I cannot set up LoadBalancer type for port 443 because it's already taken by the traefik ingress controller on each K3s node.

`extraPorts` value doesn't help as it tries to allocate the 443 port.

### Additional information

I can also see this behavior with consumers written in the .NET package [Confluent.Kafka](https://github.com/confluentinc/confluent-kafka-dotnet).

```
BootstrapServers = "kafka-0.my-domain.org:443"
```

Connects to the bootstrap server and tries to establish connection on advertised listener found in properties of the kafka node.

Log:
```
`%3|1712562181.395|ERROR|rdkafka#consumer-1| [thrd:app]: rdkafka#consumer-1: GroupCoordinator: kafka-1.my-domain.org:9095: Connection setup timed out in state CONNECT (after 30034ms in state CONNECT)
```

I know I might have some redundant values for the helmchart, I'll take care of that once this is solved. TLS termination is handled by traefik ingress controller and I'm not concerned about plaintext communication within the K3s cluster (nodes are in an isolated network).
