### ISSUE TITLE
Probes failing in Redis Chart 19.0.1 and above (is working with 18.19.4)

### ISSUE THREAD

**Issue by kjq** [bitnami/charts#25056]
### Name and Version

bitnami/redis 19.01 or above

### What architecture are you using?

None

### What steps will reproduce the bug?

Did something change in Redis between 18.19.4 (working) and 19.0.1+?  

The liveliness and readiness probes are failing but I can see in the logs that everything is working ok (i.e. synchronization between master and replica).

This happens in local Minikube as well as on EKS.

### Are you using any custom parameters or values?

Nothing really custom, here the the overrides...

```yaml
architecture: replication

master:
  persistence:
    enabled: true

replica:
  replicaCount: 1
```

### What is the expected behavior?

Redis master and replica start up fine.

### What do you see instead?

Replica keeps failing the liveliness and readiness probe (disabling one leads into the other) and eventually dies.

**Comment by kjq** [comment]
Just checking in on this as I see it in progress and a new helm chart was released...

**Comment by jotamartos** [comment]
Hi @kjq,

I tried to reproduce the issue but couldn't do so. I just launched the Bitnami Redis Chart with this change (the only one in your values.yaml that is not the default one)

```
diff --git a/bitnami/redis/values.yaml b/bitnami/redis/values.yaml
index 6081dfa0f4..c8d07603a3 100644
--- a/bitnami/redis/values.yaml
+++ b/bitnami/redis/values.yaml
@@ -623,7 +623,7 @@ replica:
   kind: StatefulSet
   ## @param replica.replicaCount Number of Redis&reg; replicas to deploy
   ##
-  replicaCount: 3
+  replicaCount: 1
   ## @param replica.configuration Configuration for Redis&reg; replicas nodes
   ## ref: https://redis.io/topics/config
   ##
```

And the deployment worked as expected 

```
$ k get pods
Warning: Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
NAME               READY   STATUS    RESTARTS   AGE
redis-master-0     1/1     Running   0          109s
redis-replicas-0   1/1     Running   0          109s

$ k logs redis-master-0
1:C 18 Apr 2024 13:37:54.010 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 18 Apr 2024 13:37:54.010 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 18 Apr 2024 13:37:54.010 * Configuration loaded
1:M 18 Apr 2024 13:37:54.010 * monotonic clock: POSIX clock_gettime
1:M 18 Apr 2024 13:37:54.011 * Running mode=standalone, port=6379.
1:M 18 Apr 2024 13:37:54.012 * Server initialized
1:M 18 Apr 2024 13:37:54.015 * Creating AOF base file appendonly.aof.1.base.rdb on server start
1:M 18 Apr 2024 13:37:54.019 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
1:M 18 Apr 2024 13:37:54.019 * Ready to accept connections tcp
1:M 18 Apr 2024 13:38:17.817 * Replica redis-replicas-0.redis-headless.test.svc.cluster.local:6379 asks for synchronization
1:M 18 Apr 2024 13:38:17.817 * Full resync requested by replica redis-replicas-0.redis-headless.test.svc.cluster.local:6379
1:M 18 Apr 2024 13:38:17.817 * Replication backlog created, my new replication IDs are '63bbc9743f88d045203a83d4f891f2774c6c6f6c' and '0000000000000000000000000000000000000000'
1:M 18 Apr 2024 13:38:17.817 * Delay next BGSAVE for diskless SYNC
1:M 18 Apr 2024 13:38:22.205 * Starting BGSAVE for SYNC with target: replicas sockets
1:M 18 Apr 2024 13:38:22.206 * Background RDB transfer started by pid 49
49:C 18 Apr 2024 13:38:22.304 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
1:M 18 Apr 2024 13:38:22.304 * Diskless rdb transfer, done reading from pipe, 1 replicas still up.
1:M 18 Apr 2024 13:38:22.307 * Background RDB transfer terminated with success
1:M 18 Apr 2024 13:38:22.307 * Streamed RDB transfer with replica redis-replicas-0.redis-headless.test.svc.cluster.local:6379 succeeded (socket). Waiting for REPLCONF ACK from replica to enable streaming
1:M 18 Apr 2024 13:38:22.307 * Synchronization with replica redis-replicas-0.redis-headless.test.svc.cluster.local:6379 succeeded
```

Could you please ensure you are using the latest version and there is no a previous PV/PVC that may be affecting the deployment? 

Thanks

**Comment by kjq** [comment]
Ill try it again in Minikube.  My logs look just like yours and are correct (it does sync).  Where mine fail are the probes.

**Comment by kjq** [comment]
Using the latest Helm chart (19.1.1) on a fresh Minikube (nothing installed yet) I get the same errors.  This is the same when we deploy to EKS.

This is the main template I am filling in:

```yaml
architecture: {{ .Values.architecture }}

globals:
  storageClass: {{ .Values.aws.storageClass }}
  
auth:
  enabled: {{ .Values.auth.enabled }}
  
master:
  persistence:
    enabled: {{ .Values.master.persistence.enabled }}
    size: {{ .Values.storageSize }}
    
metrics:
  enabled: true
  serviceMonitor: 
    enabled: true
    interval: 60s
    jobLabel: redis
    scrapeInterval: 60s
    
replica:
  replicaCount: {{ .Values.replica.replicaCount }}
  persistence:
    enabled: {{ .Values.replica.persistence.enabled }}
    size: {{ .Values.storageSize }}
```

with this...

```yaml
architecture: replication
storageSize: 5Gi

auth:
  enabled: false

master:
  persistence:
    enabled: true

replica:
  replicaCount: 1
  persistence:
    enabled: false
```

**Initial Install (as soon as pods are ready):**

![Screenshot 2024-04-18 122400](https://github.com/bitnami/charts/assets/533810/5bfc10d6-b651-42be-9f36-d6364c8e1f10)
[replicas.log](https://github.com/bitnami/charts/files/15027636/replicas.log)
[master.log](https://github.com/bitnami/charts/files/15027637/master.log)

**After about 5m:**

![Screenshot 2024-04-18 122442](https://github.com/bitnami/charts/assets/533810/f0762543-4574-45db-8c61-ccc48ff18a8d)
![Screenshot 2024-04-18 122538](https://github.com/bitnami/charts/assets/533810/43ff54f3-c9d6-4bda-9b52-51e30c6492c1)
[redis-master-down.log](https://github.com/bitnami/charts/files/15027698/redis-master-down.log)
[replicas-down.log](https://github.com/bitnami/charts/files/15027677/replicas-down.log)

> The 2 pods were because of the service monitor being enabled but even with that off it still has the same problem.

This exact same configuration (without changes) works fine with Helm chart `18.19.4`.

**Comment by jotamartos** [comment]
Hi @kjq,

I see some errors in your values.yaml file. For example, globals.storageClass and metrics.serviceMonitor.scrapeInterval parameters do not exist in the bitnami/redis chart

https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml

I suggest you launch Redis with the changes I [posted above](https://github.com/bitnami/charts/issues/25056#issuecomment-2063899888) and check if that works for you. If that's the case, continue adding other changes until you find the parameters that cause the issue.

**Comment by kjq** [comment]
I cleaned up the values.yaml and updated to 19.1.2 and it seems to work so far in both MiniKube and AWS.

Still seeing an issue in the replica set but I disabled the livenessProbe and readinessProbe on the replica for now.

This is now the values I am using:

```
architecture: {{ .Values.architecture }}

global:
  storageClass: {{ .Values.aws.storageClass }}
  
auth:
  enabled: {{ .Values.auth.enabled }}
  
master:
  persistence:
    enabled: {{ .Values.master.persistence.enabled }}
    size: {{ .Values.storageSize }}
    
metrics:
  enabled: true
  serviceMonitor: 
    enabled: true
    interval: 60s
    
replica:
  replicaCount: {{ .Values.replica.replicaCount }}
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  persistence:
    enabled: {{ .Values.replica.persistence.enabled }}
    size: {{ .Values.storageSize }}
```
