### ISSUE TITLE
[bitnami/elasticsearch] No configmap/secret or volume found for elasticsearch.yml 

### ISSUE THREAD

**Issue by gzOne2Free** [bitnami/charts#25088]
### Name and Version

bitnami/elasticsearch 19.5.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install by helm with the below values overrides. 

### Are you using any custom parameters or values?
```yaml
global:
  elasticsearch:
    service:
      name: elasticsearch
      ports:
        restAPI: 9200
  kibanaEnabled: true

clusterName: logstore
containerPorts:
  restAPI: 9200
  transport: 9300
useIstioLabels: true

ingress:
  enabled: true

master:
  masterOnly: true
  replicaCount: 3

data:
  replicaCount: 3

coordinating:
  replicaCount: 0

ingest:
  enabled: true
  replicaCount: 2

metrics:
  enabled: true

volumePermissions:
  enabled: false

sysctlImage:
  enabled: true
```

### What is the expected behavior?

elasticsearch.yml config file should be stored in ConfigMap or Secret and mounted to elasticsearch pods. Thus we can update elasticsearch configuration by modifying the related Configmap or Secret.

### What do you see instead?

Neither Configmap nor Secret is found in the installed release, nor is volume mount in the pod's definition. Kibana configmap exist.

### Additional information

My real requirement is how can I update Elasticsearch configuration to enable some features such as LDAP authentication and so on. As common sense, a dynamic config file should be stored in configmap or secret, rather than modify config file in pods directly (usually it's a read-only file if mounted from configmap or secret, or a temp filesystem which will lost when pod restart).
