### ISSUE TITLE
Self-Hosted Supabase in Kubernetes with external DB not working

### ISSUE THREAD

**Issue by lautaro79** [bitnami/charts#25104]
### Name and Version

bitnami/supabase 3.0.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Execute this command:

`helm upgrade --install supabase bitnami/supabase --version 3.0.0 -n supabase --values=./values.example.yaml`

### Are you using any custom parameters or values?

Where the file _values.example.yaml_ contains:

```
studio:
  ingress:
    path: /
    enabled: true
    hostname: 'localhost'
    ingressClassName: nginx

postgresql:
  enabled: false
externalDatabase:
  host: 'my.external.db.host'
  port: '5432'
  user: 'supabase_admin'
  database: 'supabase'
  password: 'mysecretpassword'
  existingSecret: 'supabase-externaldb'
  existingSecretPasswordKey: db-password
```

### What is the expected behavior?

All pods running correctly and connected to the configured External DB

### What do you see instead?

supabase-realtime POD is down, it shows the following error:

`[error] Postgrex.Protocol (#PID<0.137.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"`

### Additional information

It looks like the migration script in Realtime is not using the configured External DB, but default built in database configuration
