### ISSUE TITLE
[bitnami/aspnet-core] NetworkPolicy.yaml parses ingress ports incorrectly when extraContainerPorts is used

### ISSUE THREAD

**Issue by axiedoble** [bitnami/charts#25114]
### Name and Version

bitnami/aspnet-core 6.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install by helm with the below values overrides.

### Are you using any custom parameters or values?

```yaml
aspnet-core:
  image:
    registry: someregistry
    repository: some/image
    tag: latest
    pullPolicy: Always
     
  args: 
    - SomeDll.dll
    
  bindURLs: http://+:5000;https://+:5001

  service:
    type: ClusterIP
    ports:
      http: 5000
    extraPorts:
      - name: https
        port: 5001
        targetPort: https
  
  containerPorts:
    http: 5010

  extraContainerPorts:
    - name: https
      containerPort: 5001
```

### What is the expected behavior?

`helm template chart`
```yaml
# Source: aspnet-core/templates/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: someservice
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aspnet-core
    app.kubernetes.io/version: 8.0.3
    helm.sh/chart: aspnet-core-6.0.1
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: aspnet-core
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - ports:
        - port: 5000
        - port: 5001
 ```

### What do you see instead?
`helm template chart`
```yaml
# Source: aspnet-core/templates/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: someservice
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aspnet-core
    app.kubernetes.io/version: 8.0.3
    helm.sh/chart: aspnet-core-6.0.1
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: aspnet-core
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - ports:
        - port: 5000
        - port: map[containerPort:5001 name:https] # Should just be the port number
 ```

### Additional information

The workaround is setting `networkPolicy.enabled` to false, which isn't ideal.
