### ISSUE TITLE
[bitnami/mongodb] Standalone: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name

### ISSUE THREAD

**Issue by maon-fp** [bitnami/charts#25127]
### Name and Version

bitnami/mongodb 13.17.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Upgrading mongodb from <13.17.0 to >=13.17.0

### Are you using any custom parameters or values?

```yaml
mongo:
  architecture: standalone
  auth:
    enabled: false
  podAnnotations:
    fluentbit.io/parser: mongodb
  persistence:
    # Will be overwritten by production pipeline with adequate size for production
    size: 8Gi

  metrics:
    enabled: true
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /
    prometheus.io/port: '9216'
```

### What do you see instead?
```
Error: UPGRADE FAILED: template: charts/mongo/templates/standalone/svc.yaml:12:14: executing "charts/mongo/templates/standalone/svc.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: charts/minio/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: charts/minio/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```
### Additional information

From <13.17.0 to >=13.17.0 the `bitnami-common` was changed from 1.x.x to 2.x.x.

I see the same behaviour when using `replicaset` instead of `standalone`.

**Comment by javsalgar** [comment]
Hi!

Could you provide more details on the chart structure you are using? It seems that you are using mongodb as a subchart.

**Comment by maon-fp** [comment]
Thanks for looking into this.

I'm not so much into helm. The chart looks like:

```
apiVersion: v2
name: ...
version: 0.1.0
appVersion: master
description: ...
dependencies:
  - name: mongodb
    version: 13.6.7
    repository: https://charts.bitnami.com/bitnami
    alias: mongo
  - name: minio
    version: 11.10.23
    repository: https://charts.bitnami.com/bitnami
```

Are there more details you need?

**Comment by javsalgar** [comment]
Probably the issue lies in the minio subchart version you are using. Would it be possible to upgrade the minio subchart to one that contains the same common versioning?

**Comment by maon-fp** [comment]
Thank you for the insight. This involves a migration on minio. It'll take some time but I'll give it a try.

**Comment by maon-fp** [comment]
It worked on my dev. So I'm optimistic that'll work out in prod as well. Thanks a lot!

**Comment by Chaho12** [comment]
@maon-fp Hey, i am similiar issue, but am using postgresql. Can you elaborate more on how you matched common versioning when you changed version of minio?
[Postgresql 12.1.0](https://github.com/bitnami/charts/blob/postgresql/12.1.0/bitnami/postgresql/Chart.yaml) has bitnami common of version: 2.x.x... so ddo i need to match this in [Marquez common](https://github.com/MarquezProject/marquez/blob/main/chart/Chart.yaml)?

**Comment by maon-fp** [comment]
> @maon-fp Hey, i am similiar issue, but am using postgresql. Can you elaborate more on how you matched common versioning when you changed version of minio?

I just took the latest versions of all charts I was using. That worked out.

**Comment by davgia** [comment]
Hi, I encounter the same error but I cannot work out why. It seems that all my subcharts are using the common version 2.x.x, so I don't understand.

Here is my chart:

``` yaml
apiVersion: v2
name: test
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: nginx
    version: "13.2.34"
    repository: "oci://internal-harbor.com/docker-hub/bitnamicharts"
    alias: frontend
    condition: frontend.enabled
  - name: redis
    version: "17.17.1"
    repository: "oci://internal-harbor.com/docker-hub/bitnamicharts"
    condition: redis.enabled
  - name: rabbitmq
    version: "11.16.2"
    repository: "oci://internal-harbor.com/docker-hub/bitnamicharts"
    condition: rabbitmq.enabled
  - name: keycloak
    version: "13.4.1"
    repository: "oci://internal-harbor.com/docker-hub/bitnamicharts"
    condition: keycloak.enabled
```

and here are my values:

``` yaml
# Global

global:
  imageRegistry: internal-harbor.com

nodeAffinityPreset: &nodeAffinityPreset
  type: "hard"
  key: "environment"
  values: 
  - "testing"

redis:
  enabled: true
  nameOverride: "redis"
  fullnameOverride: "redis"
  architecture: standalone
  auth:
    existingSecret: "redis"
  master:
    disableCommands: []
    nodeAffinityPreset: *nodeAffinityPreset
    resources:
      requests:
        memory: "256Mi"
        cpu: "50m"
      limits:
        memory: "2Gi"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

rabbitmq:
  enabled: true
  nameOverride: "rabbitmq"
  fullnameOverride: "rabbitmq"
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
  nodeAffinityPreset: *nodeAffinityPreset
  extraPlugins: rabbitmq_stomp
  extraConfiguration: |-
    stomp.hide_server_info = true
  extraContainerPorts:
  - name: stomp
    containerPort: 61613
  service:
    extraPorts:
    - name: stomp
      port: 61613
      targetPort: stomp
  auth:
    username: admin
    existingPasswordSecret: "rabbitmq"
    existingErlangSecret: "rabbitmq"
  ingress:
    enabled: true
    hostname: rabbitmq.management.testing.omniaplace.net
    path: /
    pathType: Prefix
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-route53-dns01
      nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
      nginx.ingress.kubernetes.io/auth-url: "https://internal-oauth2-proxy.com/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://internal-oauth2-proxy.com/oauth2/start?rd=$scheme://$host$request_uri"
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

keycloak:
  enabled: true
  nameOverride: keycloak
  fullnameOverride: keycloak
  resources:
    requests:
      memory: "512Mi"
      cpu: "10m"
    limits:
      memory: "1536Mi"
  nodeAffinityPreset: *nodeAffinityPreset
  auth:
    createAdminUser: true
    adminUser: admin
    managementUser: manager
    existingSecret: "keycloak"
  service:
    type: ClusterIP
  cache:
    enabled: true
  logging:
    output: json
  ingress:
    enabled: true
    hostname: internal-keycloak.com
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-route53-dns01
      nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
  initdbScripts:
    change-web-context.sh: |
      debug_execute kc.sh build --http-relative-path=keycloak
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      path: /realms/master/metrics
  postgresql:
    enabled: true
    nameOverride: "keycloak-postgresql"
    fullnameOverride: "keycloak-postgresql"
    auth:
      username: admin
      database: testing
      existingSecret: "keycloak-postgresql"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    primary:
      resources:
        requests:
          memory: "64Mi"
          cpu: "10m"
        limits:
          memory: "128Mi"
      nodeAffinityPreset: *nodeAffinityPreset
```

as an additional information, I receive the error `error calling include: template: demo/charts/keycloak/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name` when both redis and keycloak are enabled together, not when they are enabled one at a time.

**Comment by zffocussss** [comment]
> **EDIT:** **I solved by updating keycloak chart to `16.1.7`**
> 
> Hi, I encounter the same error but I cannot work out why. It seems that all my subcharts are using the common version 2.x.x, so I don't understand.
> 
> Here is my chart:
> 
> apiVersion: v2
> name: test
> type: application
> version: 1.0.0
> appVersion: 1.0.0
> 
> dependencies:
>   - name: nginx
>     version: "13.2.34"
>     repository: "oci://internal-harbor.com/docker-hub/bitnamicharts"
>     alias: frontend
>     condition: frontend.enabled
>   - name: redis
>     version: "17.17.1"
>     repository: "oci://internal-harbor.com/docker-hub/bitnamicharts"
>     condition: redis.enabled
>   - name: rabbitmq
>     version: "11.16.2"
>     repository: "oci://internal-harbor.com/docker-hub/bitnamicharts"
>     condition: rabbitmq.enabled
>   - name: keycloak
>     version: "13.4.1"
>     repository: "oci://internal-harbor.com/docker-hub/bitnamicharts"
>     condition: keycloak.enabled
> and here are my values:
> 
> # Global
> 
> global:
>   imageRegistry: internal-harbor.com
> 
> nodeAffinityPreset: &nodeAffinityPreset
>   type: "hard"
>   key: "environment"
>   values: 
>   - "testing"
> 
> redis:
>   enabled: true
>   nameOverride: "redis"
>   fullnameOverride: "redis"
>   architecture: standalone
>   auth:
>     existingSecret: "redis"
>   master:
>     disableCommands: []
>     nodeAffinityPreset: *nodeAffinityPreset
>     resources:
>       requests:
>         memory: "256Mi"
>         cpu: "50m"
>       limits:
>         memory: "2Gi"
>   metrics:
>     enabled: true
>     serviceMonitor:
>       enabled: true
> 
> rabbitmq:
>   enabled: true
>   nameOverride: "rabbitmq"
>   fullnameOverride: "rabbitmq"
>   resources:
>     requests:
>       memory: "512Mi"
>       cpu: "100m"
>     limits:
>       memory: "1Gi"
>   nodeAffinityPreset: *nodeAffinityPreset
>   extraPlugins: rabbitmq_stomp
>   extraConfiguration: |-
>     stomp.hide_server_info = true
>   extraContainerPorts:
>   - name: stomp
>     containerPort: 61613
>   service:
>     extraPorts:
>     - name: stomp
>       port: 61613
>       targetPort: stomp
>   auth:
>     username: admin
>     existingPasswordSecret: "rabbitmq"
>     existingErlangSecret: "rabbitmq"
>   ingress:
>     enabled: true
>     hostname: rabbitmq.management.testing.omniaplace.net
>     path: /
>     pathType: Prefix
>     tls: true
>     annotations:
>       cert-manager.io/cluster-issuer: letsencrypt-route53-dns01
>       nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
>       nginx.ingress.kubernetes.io/auth-url: "https://internal-oauth2-proxy.com/oauth2/auth"
>       nginx.ingress.kubernetes.io/auth-signin: "https://internal-oauth2-proxy.com/oauth2/start?rd=$scheme://$host$request_uri"
>       nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email"
>   metrics:
>     enabled: true
>     serviceMonitor:
>       enabled: true
> 
> keycloak:
>   enabled: true
>   nameOverride: keycloak
>   fullnameOverride: keycloak
>   resources:
>     requests:
>       memory: "512Mi"
>       cpu: "10m"
>     limits:
>       memory: "1536Mi"
>   nodeAffinityPreset: *nodeAffinityPreset
>   auth:
>     createAdminUser: true
>     adminUser: admin
>     managementUser: manager
>     existingSecret: "keycloak"
>   service:
>     type: ClusterIP
>   cache:
>     enabled: true
>   logging:
>     output: json
>   ingress:
>     enabled: true
>     hostname: internal-keycloak.com
>     tls: true
>     annotations:
>       cert-manager.io/cluster-issuer: letsencrypt-route53-dns01
>       nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
>   initdbScripts:
>     change-web-context.sh: |
>       debug_execute kc.sh build --http-relative-path=keycloak
>   metrics:
>     enabled: true
>     serviceMonitor:
>       enabled: true
>       path: /realms/master/metrics
>   postgresql:
>     enabled: true
>     nameOverride: "keycloak-postgresql"
>     fullnameOverride: "keycloak-postgresql"
>     auth:
>       username: admin
>       database: testing
>       existingSecret: "keycloak-postgresql"
>     metrics:
>       enabled: true
>       serviceMonitor:
>         enabled: true
>     primary:
>       resources:
>         requests:
>           memory: "64Mi"
>           cpu: "10m"
>         limits:
>           memory: "128Mi"
>       nodeAffinityPreset: *nodeAffinityPreset
> as an additional information, I receive the error `error calling include: template: demo/charts/keycloak/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name` when both redis and keycloak are enabled together, not when they are enabled one at a time.

similar issues when install subchart PostgreSQL

```
annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 2.0.4
description: A Library Helm Chart for grouping common logic between bitnami charts.
  This chart is not deployable by itself.
home: https://github.com/bitnami/charts/tree/main/bitnami/common
icon: https://bitnami.com/downloads/logos/bitnami-mark.png
keywords:
- common
- helper
- template
- function
- bitnami
maintainers:
- name: Bitnami
  url: https://github.com/bitnami/charts
name: common
sources:
- https://github.com/bitnami/charts
- https://www.bitnami.com/
type: library
version: 2.0.4
```
