### ISSUE TITLE
[bitnami/redis] Redis-sentinel auto-discovering wrong hosts for masters and slaves

### ISSUE THREAD

**Issue by AsoTora** [bitnami/charts#25136]
### Name and Version

bitnami/redis 19.1.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Have multiple bitnami/redis helm charts deployed in 1 namespace
2. Each of them uses almost all default values
3. For some reason sentinel auto-discovers and adds new nodes to its config, for example:
```
I have no name!@instruments-redis-node-2:/$ cat /opt/bitnami/redis-sentinel/etc/sentinel.conf 
dir "/tmp"
port 26379
sentinel monitor mymaster tradersroom-sso-redis-node-0.sso-redis-headless.tradersroom-sso.svc.cluster.local 6379 2
sentinel down-after-milliseconds mymaster 60000

# User-supplied sentinel configuration:
# End of sentinel configuration
sentinel myid 28d492393e1f1939c1acec90e5ed59b2b31fdbd2

sentinel known-sentinel mymaster instruments-redis-node-0.instruments-redis-headless.native-trading-middleware.svc.cluster.local 26379 9c8a6f0438f19422dd4d63f6534d1fdbe6cf7902

sentinel known-replica mymaster instruments-redis-node-1.instruments-redis-headless.native-trading-middleware.svc.cluster.local 6379

sentinel known-sentinel mymaster instruments-redis-node-1.instruments-redis-headless.native-trading-middleware.svc.cluster.local 26379 86746251f86902d8476c8cb038739c05d001f37f

sentinel known-replica mymaster instruments-redis-node-0.instruments-redis-headless.native-trading-middleware.svc.cluster.local 6379

sentinel known-replica mymaster sso-redis-node-2.sso-redis-headless.sso.svc.cluster.local 6379

sentinel announce-hostnames yes
sentinel resolve-hostnames yes
sentinel announce-port 26379
sentinel announce-ip "instruments-redis-node-2.instruments-redis-headless.native-trading-middleware.svc.cluster.local"

# Generated by CONFIG REWRITE
protected-mode no
latency-tracking-info-percentiles 50 99 99.9
user default on nopass sanitize-payload ~* &* +@all
sentinel config-epoch mymaster 84
sentinel leader-epoch mymaster 0
sentinel known-replica mymaster instruments-redis-node-2.instruments-redis-headless.native-trading-middleware.svc.cluster.local 6379
sentinel current-epoch 84

sentinel known-replica mymaster sso-redis-node-1.sso-redis-headless.sso.svc.cluster.local 6379

sentinel known-sentinel mymaster sso-redis-node-0.sso-redis-headless.sso.svc.cluster.local 26379 85f92b127c60c601af4298b6a6f6195dcdd148db

sentinel known-sentinel mymaster sso-redis-node-1.sso-redis-headless.sso.svc.cluster.local 26379 fe4882504b2d61fa014e19aa74077a7b4f48883f

sentinel known-sentinel mymaster sso-redis-node-2.sso-redis-headless.sso.svc.cluster.local 26379 f90e3459599f4e41124bd5e7478ce450f937f2f0
```

![image](https://github.com/bitnami/charts/assets/36507055/5fe2a6d3-b6a8-492f-b308-1a0e576929ab)

I've tried to mitigate this using network policy, but for some reason the discovery still continues. Probably because the 'sso' redis doesn't have it yet. However, this still doesn't answer why in the world this happens. 

### Are you using any custom parameters or values?
```yaml
nameOverride: "instruments-redis"
fullnameOverride: "instruments-redis"
architecture: replication
useHostnames: true
auth:
  enabled: false
  sentinel: false
master:
  persistence:
    enabled: false
replica:
  persistence:
    enabled: false
sentinel:
  enabled: true
  downAfterMilliseconds: 60000
  failoverTimeout: 180000
  image:
    debug: true
  persistence:
    enabled: false
metrics:
  enabled: true
  service:
    annotations:
      prometheus.io/scrape: "true"

networkPolicy:
  enabled: true
  allowExternal: false
  ingressNSPodMatchLabels:
    redis-client: "true"
  # allow metrics to be exposed without net policy
  metrics:
    allowExternal: true
```

### What is the expected behavior?

Redis sentinel started with 1 master 2 slaves

### What do you see instead?

Sentinel auto-discovers multple wrong slaves and masters.

### Additional information

A similar issue is addressed here: https://github.com/bitnami/charts/issues/10016 but i see no resolution and have a similar case.

environment:
- on-premise k8s v1.27.7
- net-plugin: calico
