### ISSUE TITLE
[bitnami/kube-state-metrics] Chart does not support CustomResourceDefitinitions

### ISSUE THREAD

**Issue by rrileyca** [bitnami/charts#25145]
### Name and Version

bitnami/kube-state-metrics

### What is the problem this feature will solve?

kube-state-metrics supports monitoring custom resources in Kubernetes following their [CustomResourceState documentation](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/extend/customresourcestate-metrics.md). Using the chart, I can successfully add this configuration by mounting a ConfigMap.

Values.yaml:
```yaml
extraArgs:
  custom-resource-state-only: true
  custom-resource-state-config-file: /kube-state-metrics-config/kube-state-config.yaml
extraVolumes:
  - name: kube-state-metrics-config
    configMap:
      name: kube-state-metrics-config
extraVolumeMounts:
  - mountPath: /kube-state-metrics-config
    name: kube-state-metrics-config
    readOnly: true
```

However, as described in the RBAC-enabled Clusters section of the kube-state-metrics docs, the `list` and `watch` permissions are required at the Cluster level to be able to scan these.

### What is the feature you are proposing to solve the problem?

Add a template like `extraClusterRoleRules` which allows adding additional role rules like:
```yaml
extraClusterRoleRules:
- apiGroups:
  - "foor.bar"
  resources:
  - mycustomresource
  verbs:
  - list
  - watch
```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the input! In other charts we have an `rbac.rules` value does exactly what you are looking for

https://github.com/bitnami/charts/blob/49b06417cd66361b9ad2baad90b0507799c2d3b0/bitnami/airflow/templates/rbac/role.yaml#L41

Would you like to submit a PR replicating this behavior?

**Comment by rrileyca** [comment]
In the meantime as a workaround I used a postRenderer in the HelmRelease:
```yaml
spec:
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op: add
                path: /rules/-
                value:
                  apiGroups:
                    - apiextensions.k8s.io
                  resources:
                    - customresourcedefinitions
                  verbs:
                    - list
                    - watch
            target:
              kind: ClusterRole
              group: rbac.authorization.k8s.io
              version: v1
              name: kube-state-metrics-kube-state-metrics
          - patch: |
              - op: add
                path: /rules/-
                value:
                  apiGroups:
                    - my.api.group.io
                  resources:
                    - mycustomresource
                  verbs:
                    - list
                    - watch
            target:
              kind: ClusterRole
              group: rbac.authorization.k8s.io
              version: v1
              name: kube-state-metrics-kube-state-metrics
```
