### ISSUE TITLE
[bitnami/grafana-operator] Grafana operator network policy not honoring `allowExternalEgress` option

### ISSUE THREAD

**Issue by miqm** [bitnami/charts#25150]
### Name and Version

bitnami/grafana-operator 4.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy grafana using grafana-operator with default values (allowExternalEgress is set to true)
2. Add a datasource (i.e. prometheus) on port 9090
3. grafana cannot access datasource
4. 

### Are you using any custom parameters or values?

no

### What is the expected behavior?

with `allowExternalEgress` set to true all egress ports should be allowed.

### What do you see instead?

on grafana network policy, despite allowExternalEgress is set to true and all external traffic should be enabled, only dns ports (53) and kubeApiServer ports and grafana 3000 ports are enabled.

### Additional information

grafana chart networpolicy.yaml template has an if for `allowExternalEgress`. grafana-operator - don't have it.

**Comment by javsalgar** [comment]
Hi! Thank you so much for reporting. I created the PR below to fix the issue :arrow_down:

**Comment by miqm** [comment]
@javsalgar Awesome! also - not sure if this is related - can you give an example how to use `extraEgress`? When providing as value:
```yaml
  networkPolicy:
    extraEgress:
      - ports:
        - protocol: TCP
          port: 9090
```
the output networkpolicy was:
```
  egress:
    - ports:
        # Allow dns resolution
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
        # Allow access to kube-apiserver
        - port: 443
        - port: 6443
        - port: 8443
        # Allow access to Grafana. As it does not have a label to identify its created grafana instances, we will use the standard grafana port (currently hardcoded in the operator)
        - port: 3000
    - ports:
      - port: 9090
        protocol: TCP
```
but it didn't work.
