### ISSUE TITLE
[bitnami/mariadb] Impossible to use MariaDB's own NodePort in its initdb script

### ISSUE THREAD

**Issue by arches-richard** [bitnami/charts#25180]
### Name and Version

bitnami/mariadb 18.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Run: 

```bash
helm install -n mariadb --create-namespace -f values.yaml db oci://registry-1.docker.io/bitnamicharts/mariadb
```

Then watch the logs.

### Are you using any custom parameters or values?

```yaml
auth:
  rootPassword: 'rootpass'

image:
  debug: true

initdb:
  init.sh: 'mysql -h <node> -P 30306 -u root -prootpass'

primary:
  service:
    type: 'NodePort'
    nodePorts:
      mysql: 30306

secondary:
  replicaCount: 0
```

### What is the expected behavior?

The `mysql` call in the initdb script succeeds

### What do you see instead?

It fails with:

```bash
2024-04-15T15:36:36.568771722-04:00 ERROR 2002 (HY000): Can't connect to server on '<node>' (115)
```

### Additional information

In my actual initdb (not this simplified example), I pass in my host, port, etc. to the initdb via environment variables loaded from a configmap. This way the initdb script is not hardcoding the default mariadb port and failing once someone changes that.
