### ISSUE TITLE
[bitnami/grafana-operator] missing option to add labels in the Grafana deployment template

### ISSUE THREAD

**Issue by kopendrex** [bitnami/charts#25199]
### Name and Version

bitnami/grafana-operator 4.0.3

### What is the problem this feature will solve?

There is no option to set custom labels in the Grafana deployment template. Right now, there is an option to use only `commonLabels` or `common.labels.standard` labels:
```
      template:
        metadata:
          labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 12 }}
            app.kubernetes.io/component: grafana
```
Source: [(.../bitnami/grafana-operator/templates/grafana.yaml#L78)](https://github.com/bitnami/charts/blob/ca970d7f4888fc51c529358f5f685283fe092672/bitnami/grafana-operator/templates/grafana.yaml#L78)

In a situation where I want to use a workload identity label which should be only in a template section, if I use a `commonLables` this label is added in many other places.

### What is the feature you are proposing to solve the problem?

Maybe we can add additional settings for this option `.values.grafana.template.lables`?

### What alternatives have you considered?

Any alternative for this option will be good.
