### ISSUE TITLE
[bitnami/grafana] helm chart does not load my grafana.ini

### ISSUE THREAD

**Issue by raphaelcervantes** [bitnami/charts#2519]
**Which chart**:
grafana 1.5.2

**Describe the bug**
The helm chart won't load my grafana.ini file.

**To Reproduce**
1. Make config map that includes customized grafana.ini. Then create the ConfigMap. I did `kubectl apply -f grafana-ini-configmap.yaml`. 

The first 70 lines of my configmap are pasted below. They contain mostly defaults of the grafana.ini. The one change from default is     `root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/`

```
[non-helm-details] head -70 grafana-ini-configmap.yaml                                                                                                                                   feature/postgres-container
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini-config
data:
  grafana.ini: |-
    ##################### Grafana  Configuration Example #####################
    #
    # Everything has defaults so you only need to uncomment things you want to
    # change

    # possible values : production, development
    ;app_mode = production

    # instance name, defaults to HOSTNAME environment variable value or hostname if HOSTNAME var is empty
    ;instance_name = ${HOSTNAME}

    #################################### Paths ####################################
    [paths]
    # Path to where grafana can store temp files, sessions, and the sqlite3 db (if that is used)
    ;data = /var/lib/grafana

    # Temporary files in `data` directory older than given duration will be removed
    ;temp_data_lifetime = 24h

    # Directory where grafana can store logs
    ;logs = /var/log/grafana

    # Directory where grafana will automatically scan and look for plugins
    ;plugins = /var/lib/grafana/plugins

    # folder that contains provisioning config files that grafana will apply on startup and while running.
    ;provisioning = conf/provisioning

    #################################### Server ####################################
    [server]
    # Protocol (http, https, socket)
    ;protocol = http

    # The ip address to bind to, empty will bind to all interfaces
    ;http_addr =

    # The http port  to use
    ;http_port = 3000

    # The public facing domain name used to access grafana from a browser
    ;domain = localhost

    # Redirect to correct domain if host header does not match domain
    # Prevents DNS rebinding attacks
    ;enforce_domain = false

    # The full public facing url you use in browser, used for redirects and emails
    # If you use reverse proxy and sub path specify full url (with sub path)
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/

    # Serve Grafana from subpath specified in `root_url` setting. By default it is set to `false` for compatibility reasons.
    ;serve_from_sub_path = false

    # Log web requests
    ;router_logging = false

    # the path relative working path
    ;static_root_path = public

    # enable gzip
    ;enable_gzip = false

    # https certs & key file
    ;cert_file =
```

2. Adjust values file to load custom grafana.ini from config map.

```
[external_charts] cat grafana-values.yaml                                                                                                                                                feature/postgres-container
ingress:
  enabled: True
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - name: nlwymmd.orpheus
      paths: ["/grafana(/|$)(.*)"]
metrics:
  enabled: true
config:
  useGrafanaInifile: true
  grafanaIniConfigMap: grafana-ini-config
persistence:
  enabled: false
```

3. Install helm chart with values file.
`helm install grafana bitnami/grafana -f grafana-values.yaml`
The output of `helm upgrade grafana bitnami/grafana -f releases/external_charts/grafana-values.yaml --dry-run --debug > grafana_debug.txt` is pasted below.

```
Release "grafana" has been upgraded. Happy Helming!
NAME: grafana
LAST DEPLOYED: Tue May  5 09:24:23 2020
NAMESPACE: default
STATUS: pending-upgrade
REVISION: 2
TEST SUITE: None
USER-SUPPLIED VALUES:
config:
  grafanaIniConfigMap: grafana-ini-config
  useGrafanaInifile: true
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  enabled: true
  hosts:
  - name: nlwymmd.orpheus
    paths:
    - /grafana(/|$)(.*)
metrics:
  enabled: true
persistence:
  enabled: false

COMPUTED VALUES:
admin:
  existingSecretPasswordKey: password
  user: admin
affinity: {}
config:
  customIniConfigMap: null
  customIniSecret: null
  grafanaIniConfigMap: grafana-ini-config
  grafanaIniSecret: null
  useCustomIniFile: false
  useGrafanaIniFile: false
  useGrafanaInifile: true
dashboardsConfigMaps: []
dashboardsProvider:
  configMapName: null
  enabled: false
datasources:
  secretName: null
extraConfigmaps: {}
extraEnvVars: {}
image:
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: bitnami/grafana
  tag: 6.7.3-debian-10-r0
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  certManager: false
  enabled: true
  hosts:
  - name: nlwymmd.orpheus
    paths:
    - /grafana(/|$)(.*)
ldap:
  allowSignUp: false
  enabled: false
livenessProbe:
  enabled: true
  failureThreshold: 6
  initialDelaySeconds: 120
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
metrics:
  enabled: true
  service:
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: "3000"
      prometheus.io/scrape: "true"
  serviceMonitor:
    enabled: false
nodeSelector: {}
persistence:
  accessMode: ReadWriteOnce
  enabled: false
  size: 10Gi
podAnnotations: {}
readinessProbe:
  enabled: true
  failureThreshold: 6
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
replicaCount: 1
resources:
  limits: {}
  requests: {}
securityContext:
  enabled: true
  fsGroup: 1001
  runAsNonRoot: true
  runAsUser: 1001
service:
  annotations: {}
  port: 3000
  type: ClusterIP
serviceAccount:
  create: true
  name: null
smtp:
  enabled: false
  existingSecretPasswordKey: password
  existingSecretUserKey: user
  password: password
  user: user
tolerations: []
updateStrategy:
  type: RollingUpdate

HOOKS:
MANIFEST:
---
# Source: grafana/templates/serviceaccount.yml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
    helm.sh/chart: grafana-1.5.2
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
secrets:
  - name: grafana-admin
---
# Source: grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  labels:
    app.kubernetes.io/name: grafana
    helm.sh/chart: grafana-1.5.2
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  GF_SECURITY_ADMIN_PASSWORD: "M2U4cFVOYTFhVA=="
---
# Source: grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-envvars
  labels:
    app.kubernetes.io/name: grafana
    helm.sh/chart: grafana-1.5.2
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
data:
  GF_SECURITY_ADMIN_USER: "admin"
  GF_PATHS_PLUGINS: "/opt/bitnami/grafana/data/plugins"
  GF_AUTH_LDAP_ENABLED: "false"
  GF_AUTH_LDAP_CONFIG_FILE: "/opt/bitnami/grafana/conf/ldap.toml"
  GF_AUTH_LDAP_ALLOW_SIGN_UP: "false"
  GF_PATHS_PROVISIONING: "/opt/bitnami/grafana/conf/provisioning"
  GF_PATHS_CONFIG: "/opt/bitnami/grafana/conf/grafana.ini"
  GF_PATHS_DATA: "/opt/bitnami/grafana/data"
  GF_PATHS_LOGS: "/opt/bitnami/grafana/logs"
---
# Source: grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
    helm.sh/chart: grafana-1.5.2
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "3000"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: dashboard
      protocol: TCP
      name: http
      nodePort: null
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
---
# Source: grafana/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
    helm.sh/chart: grafana-1.5.2
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: grafana
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        helm.sh/chart: grafana-1.5.2
        app.kubernetes.io/instance: grafana
        app.kubernetes.io/managed-by: Helm
      annotations:
        checksum/secret: 74a2ae181939e3f8555e11fba09f14b633c1a92fec3da778ad4203d27e325fcc
        checksum/config: 99c0d5ea65ed8615f436ab01c34ca6ea1e6018c6d4b5a7530ccf4c4ac82b3b15
        checksum/dashboard-provider: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
    spec:
      serviceAccountName: grafana

      securityContext:
        runAsUser: 1001
        fsGroup: 1001
        runAsNonRoot: true
      containers:
        - name: grafana
          image: docker.io/bitnami/grafana:6.7.3-debian-10-r0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: grafana-envvars
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: GF_SECURITY_ADMIN_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /opt/bitnami/grafana/data
          ports:
            - name: dashboard
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: dashboard
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: dashboard
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
           successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: dashboard
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          resources:
            limits: {}
            requests: {}
      volumes:
        - name: data
---
# Source: grafana/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
    helm.sh/chart: grafana-1.5.2
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: "nlwymmd.orpheus"
      http:
        paths:
          - path: /grafana(/|$)(.*)
            backend:
              serviceName: grafana
              servicePort: http
  tls:

NOTES:
** Please be patient while the chart is being deployed **

1. Get the application URL by running these commands:
  http://nlwymmd.orpheus/grafana(/|$)(.*)

2. Get the admin credentials:

    echo "User: admin"
    echo "Password: $(kubectl get secret grafana-admin --namespace default -o jsonpath="{.data.GF_SECURITY_ADMIN_PASSWORD}" | base64 --decode)"
```

4. Check if docker container loaded grafana.ini.

First, get a bash instance working inside of the container.
`kubectl exec -it grafana-85df46fbdc-hczn5 -- bash`

The print out the grafana.ini inside of the container.
`I have no name!@grafana-85df46fbdc-hczn5:/opt/bitnami/grafana$ cat conf/grafana.ini`

I see that grafana.ini inside of the pod uses all of the default settings. It ignored the changes in my configmap.

**Expected behavior**
If I go into the pod image, I expect grafana.ini to use my grafana.ini and not just the default.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
In the larger scheme of things, I am trying to get grafana to talk to my nginx-ingress setup, so that I can access grafana through a URL.
