### ISSUE TITLE
[bitnami/argo-cd] Named Port of argocd application-controller deployment is missing after chart version upgrade

### ISSUE THREAD

**Issue by nevotheless** [bitnami/charts#25201]
### Name and Version

bitnami/argo-cd 6.0.10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

- I've upgraded an argocd deployment from char version `5.4.4` to `6.0.10`. 

- The deployment is missing the `spec.template.spec.containers.ports` key
- Pod reference named ports which isn't found hence they have their probes failing

### Are you using any custom parameters or values?

Unfortunately I've just deployed it via the helm integration inside lens and have no separate value.yaml but i've made minimal changes and try to get them together:

```
global.storageClass: someValue
```

```
server
   ingress:
    ingressClassName: nginx
    hostname: somehostname
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
```

and i previously had to change the `seccomProfile` of `dex` but since i've moved to aws this isn't changed anymore. 

Otherwise nothing is changed. But I've saw that the image tag didn't get updated either, even though the `appVersion` Field shows `2.10.7`, image tag is still on `2.9.4-debian-11-r0` don't know if this is relevant.

### What is the expected behavior?

No issues with the `application-controller` pods. 😄 

### What do you see instead?

On the `application-controller` pods:
```
Liveness probe errored: strconv.Atoi: parsing "metrics": invalid syntax
```

```
Readiness probe errored: strconv.Atoi: parsing "metrics": invalid syntax
```

---

The only interesting observation i've found so far was when i diffed the new revision with the previous via 
```
helm diff -n argocd revision {deploymentName} {deploymentNr}
```

it doesn't show the metrics port as newly added, only that the controller port is getting removed
```
            ports:
-             - name: controller
-               containerPort: 8082
-               protocol: TCP
              - name: metrics
                containerPort: 8082
                protocol: TCP
```

After the deployment the `ports` section is non-existent. 

When i add it manually the error went away.

**Comment by davgia** [comment]
Hi, I have the same error. I upgrade from 5.1.13 to 7.1.4. The controller container is not healthy due to the following error in both liveness and readiness probes:

``` sh
Liveness probe errored: strconv.Atoi: parsing "metrics": invalid syntax
Readiness probe errored: strconv.Atoi: parsing "metrics": invalid syntax
```

**Comment by javsalgar** [comment]
Hi!

Let me reopen it so you can share any extra findings

**Comment by davgia** [comment]
Hi @javsalgar,

I have created a new Kubernetes cluster (1.31.4) and I have deployed the argo-cd bitnami chart 7.1.4 in it with the same values as my other argocd existing installation (in another cluster). I cannot reproduce the error. It seems to me that the error is triggered when trying to upgrade a previously installed chart. Please note that I am managing helm charts with Terraform 1.9.8 (provider helm version: 2.17.0) but I don't think it matters.

here are my values (I have redacted some values):

``` yaml
nameOverride: argocd
fullnameOverride: argocd
# common configuration
config:
  rbac:
    policy.default: "role:admin"
  secret:
    create: false
# controller configuration
controller:
  logFormat: json
  extraArgs:
  - "--repo-server-timeout-seconds"
  - "600"
  - "--app-resync"
  - "300"
  # affinity configuration
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "ephemeral"
              operator: In
              values:
                - "false"
  # resource configuration
  resources:
    limits:
      memory: 1280Mi
    requests:
      cpu: 100m
      memory: 512Mi     
# server configuration
server:
  logFormat: json
  # server url
  url: [REDACTED]
  # ingress configuration
  ingress:
    enabled: true
    hostname: [REDACTED]
    ingressClassName: "nginx"
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-dns01"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  # server configuration
  config:
    admin.enabled: 'false'
    oidc.config: |
      name: Keycloak
      issuer: [REDACTED]
      clientID: $oidc.keycloak.clientId
      clientSecret: $oidc.keycloak.clientSecret
      requestedScopes: ["openid", "profile", "email"]
  # affinity configuration
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "ephemeral"
              operator: In
              values:
                - "false"
  # resource configuration
  resources:
    limits:
      memory: 384Mi
    requests:
      cpu: 10m
      memory: 256Mi
# repository server configuration
repoServer:
  logFormat: json
  extraEnvVars:
    - name: "ARGOCD_EXEC_TIMEOUT"
      value: "10m"
  # affinity configuration
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "ephemeral"
              operator: In
              values:
                - "false"
  # resource configuration
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 256Mi
# redis configuration
redis:
  auth:
    existingSecret: "argocd-redis"
  master:
    # affinity configuration
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "ephemeral"
                operator: In
                values:
                  - "false"
    # resource configuration
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
    # persistence
    persistence:
      enabled: true
      size: 256Mi
```

**Comment by davgia** [comment]
I've done many tests and I can say for sure that if a chart with version `< 6.0.8` is installed the upgrade process will fail with the error described in this issue. If the chart version is `>= 6.0.8` the upgrade process will succeed. Maybe it should be documented or a fix should be made in the chart so that it does not break compatibility.

**Comment by javsalgar** [comment]
Hi,

As a possible workaround, could you try upgrading from the problematic version to 6.0.8 disabling the probes?

**Comment by davgia** [comment]
Hi @javsalgar,

sorry for the late reply but I was indisposed. I have done the following:

0. install argo-cd chart version 6.0.7
1. prepare alternative values.yaml with the following addition:
   ``` yaml
   controller:
      livenessProbe:
        enabled: false
      readinessProbe:
        enabled: false
   ```
2. upgrade the argo-cd release to version 7.1.5
3. check that app-controller is running

As expected all went smoothly and the app controller pod is up and running.
