### ISSUE TITLE
[bitnami/keycloak] Keycloak chart is incorrectly setting the database existing password key in `KEYCLOAK_DATABASE_PASSWORD` env var.

### ISSUE THREAD

**Issue by hamza-m-masood** [bitnami/charts#25232]
### Name and Version

bitnami/keycloak 21.0.2

### What architecture are you using?

GKE

### What steps will reproduce the bug?

3. Run: `helm install keycloak oci://registry-1.docker.io/bitnamicharts/keycloak -n keycloak -f ./keycloak.yaml`  The `./keycloak.yaml` is the values.yaml. It's contents are pasted below.
4. Error:
```yaml
COMMAND:
kubectl events keycloak -n keycloak

OUTPUT:
...
2m51s (x11 over 4m45s)   Warning   Failed      Pod/keycloak-0     Error: couldn't find key password in Secret keycloak/camunda-secrets

```

### Are you using any custom parameters or values?

Here is my values.yaml:
```yaml
auth:
  existingSecret: camunda-secrets
  passwordSecretKey: keycloak-secret
postgresql:
  auth:
    existingSecret: camunda-secrets
    secretKeys:
      userPasswordKey: postgresql-secret
      adminPasswordKey: postgresql-secret
      replicationPasswordKey: postgresql-secret
```

### What is the expected behavior?

The chart should correctly reference the `auth.passwordSecretKey` and start up the keycloak pod in a healthy state.

### What do you see instead?

Currently, the `KEYCLOAK_DATABASE_PASSWORD` sets the incorrect secret key. It uses `password` instead of referencing the secret key from `auth.passwordSecretKey`
Here is the full environment variable:
```yaml
    - name: KEYCLOAK_DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: camunda-secrets
```

The `key` should have this value: `keycloak-secret`

### Additional information

This is probably because of the `templates/_helpers.tpl` file. Here is a snippet:
```yaml
{{/*
Add environment variables to configure database values
*/}}
{{- define "keycloak.databaseSecretPasswordKey" -}}
{{- if .Values.postgresql.enabled -}}
    {{- print "password" -}}
{{- else -}}
    {{- if .Values.externalDatabase.existingSecret -}}
        {{- if .Values.externalDatabase.existingSecretPasswordKey -}}
            {{- printf "%s" .Values.externalDatabase.existingSecretPasswordKey -}}
        {{- else -}}
            {{- print "db-password" -}}
        {{- end -}}
    {{- else -}}
        {{- print "db-password" -}}
    {{- end -}}
{{- end -}}
{{- end -}}
```
The value `password` is hardcoded instead of first checking and referencing the `auth.passwordSecretKey` value.
