### ISSUE TITLE
[bitnami/grafana-operator] spec.config.security.auth in body must be of type string: "object"

### ISSUE THREAD

**Issue by fabio-s-franco** [bitnami/charts#25235]
### Name and Version

bitnami/grafana-operator 4.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install the chart using the [values.yaml](https://github.com/bitnami/charts/blob/main/bitnami/grafana-operator/values.yaml) file and uncomment the [auth](https://github.com/bitnami/charts/blob/2c7666225b6d2d9d709ec6c873a2d69a1a039cc2/bitnami/grafana-operator/values.yaml#L782) section:

```yaml
    security:
      # ## Grafana Admin credentials, if omitted they will be admin:<random_pass>
      # admin_user:
      # admin_password:
      #
      # ## OIDC configuration
      # ##
      # auth:
      #   disable_login_form: "false"
      #   disable_signout_menu: "false"
      # auth.generic_oauth:
      #   enabled: "true"
      #   client_id: grafana
      #   client_secret: a391df94-dd1f-46d6-b3ab-60e90f23e8a2
      #   scopes: profile email
      #   auth_url: https://keycloak.example.com/auth/realms/master/protocol/openid-connect/auth
      #   token_url: https://keycloak.example.com/auth/realms/master/protocol/openid-connect/token
      #   api_url: https://keycloak.example.com/auth/realms/master/protocol/openid-connect/userinfo
```

```
cannot patch "grafana-operator-grafana" with kind Grafana: Grafana.grafana.integreatly.org "grafana-operator-grafana" is invalid: [spec.config.security.auth.anonymous: Invalid value: "object": spec.config.security.auth.anonymous in body must be of type string: "object"]
```
On a side note, the links [here](https://github.com/bitnami/charts/blob/2c7666225b6d2d9d709ec6c873a2d69a1a039cc2/bitnami/grafana-operator/values.yaml#L59) are broken.

### Are you using any custom parameters or values?

Just as described on the reproduction, uncommenting any of the auth sections will trigger the error. ie:

```yaml
    security:
      # ## Grafana Admin credentials, if omitted they will be admin:<random_pass>
      # admin_user:
      # admin_password:
      #
      # ## OIDC configuration
      # ##
      auth:
        disable_login_form: "false"
        disable_signout_menu: "false"
      # auth.generic_oauth:
      #   enabled: "true"
      #   client_id: grafana
      #   client_secret: a391df94-dd1f-46d6-b3ab-60e90f23e8a2
      #   scopes: profile email
      #   auth_url: https://keycloak.example.com/auth/realms/master/protocol/openid-connect/auth
      #   token_url: https://keycloak.example.com/auth/realms/master/protocol/openid-connect/token
      #   api_url: https://keycloak.example.com/auth/realms/master/protocol/openid-connect/userinfo
```

### What is the expected behavior?

Chart installs / updates without errors

### What do you see instead?
```
cannot patch "grafana-operator-grafana" with kind Grafana: Grafana.grafana.integreatly.org "grafana-operator-grafana" is invalid: [spec.config.security.auth.anonymous: Invalid value: "object": spec.config.security.auth.anonymous in body must be of type string: "object"]
```
