### ISSUE TITLE
[bitnami/grafana] grafana won't provision my datasource

### ISSUE THREAD

**Issue by raphaelcervantes** [bitnami/charts#2525]
**Which chart**:
 grafana 1.5.2

**Describe the bug**
grafana helm chart ignores the datasource I try to privision from the secret.

**To Reproduce**

1. Create and apply secret containing data source. 

```
raphaelc@nlwymmd:~$ cat grafana-postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: orpheusdb-grafana
  namespace: default
type: Opaque
stringData:
  other_datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: sensor_db
        type: postgres
        url: postgres-kvstore-postgresql.default.svc.cluster.local
        database: sensor_data
        user: madeupname
        secureJsonData:
          password: "password"
        jsonData:
          sslmode: "disable" # disable/require/verify-ca/verify-full
          maxOpenConns: 0         # Grafana v5.4+
          maxIdleConns: 2         # Grafana v5.4+
          connMaxLifetime: 14400  # Grafana v5.4+
          postgresVersion: 1000 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
          timescaledb: false
```

2. Adjust values file to point to secret.

```
admin:
  user: user
  password: <redacted>
datasource:
  secretName: orpheusdb-grafana
persistence:
  enabled: false
```

3. Install helm chart.
`helm install grafana bitnami/grafana -f grafana-values.yaml`

4. Look at grafana through a web browser and notice that there is no database provisioned.

5. Check that you can manually set the database source int he GUI with the same credentials.

**Expected behavior**
I expect that my provisioned datasource would show up in the grafana UI.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
This is probably related to the same problem I'm having here: https://github.com/bitnami/charts/issues/2519

**Comment by javsalgar** [comment]
Hi,

It seems that the value name is datasources, not datasource. Could you check that this is not the issue? You can do kubectl get pods -o yaml in the grafana pod to see if the secret is being mounted or not.

**Comment by raphaelcervantes** [comment]
That appeared to be the issue. I needed to change my values file so that it was datasources instead of datasource.
```

admin:
  user: user
  password: <redacted>
datasources:
  secretName: orpheusdb-grafana
persistence:
  enabled: false
```
