### ISSUE TITLE
Elastic search installation issue - /opt/bitnami/scripts/libfs.sh: line 59: 1: missing directory

### ISSUE THREAD

**Issue by bharani-dasari** [bitnami/charts#25279]
### Name and Version

bitnami/elasticsearch 8.3.2-debian-11-r0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am currently trying upgrade/install elasticsearch in cluster mode version 8.3.3-debian-11-r10/8.3.2-debian-11-r0 from bitnami helm charts via cloud-deploy. But I am running below error

```
elasticsearch-v1-ingest-1 copy-default-plugins] /opt/bitnami/scripts/libfs.sh: line 59: 1: missing directory
elasticsearch-v1-coordinating-0 copy-default-plugins] /opt/bitnami/scripts/libfs.sh: line 59: 1: missing directory
```

### What is the expected behavior?

Pods should be up and running 

### What do you see instead?
```
elasticsearch-v1-coordinating-0             0/1     Init:CrashLoopBackOff   6 (2m8s ago)    8m1s
elasticsearch-v1-coordinating-1             0/1     Init:CrashLoopBackOff   6 (2m14s ago)   8m
elasticsearch-v1-data-0                     0/1     Init:CrashLoopBackOff   6 (111s ago)    8m1s
elasticsearch-v1-data-1                     0/1     Init:CrashLoopBackOff
```

**Comment by Jancis** [comment]
I have the same issue with 21.0.1.
> copy-default-plugins /opt/bitnami/scripts/libfs.sh: line 61: 1: missing directory

**Comment by dgomezleon** [comment]
Hi @Jancis ,

Did it happen on a fresh installation or during an upgrade? Are you using any custom values?

**Comment by dgomezleon** [comment]
I see,

It works fine for the latest version (debian-12). For debian-11 I would recommend using the latest released tag `8.12.1-debian-11-r20`, to create a custom image with all the changes applied (using it directly you will find this error:

```
/opt/bitnami/scripts/elasticsearch/entrypoint.sh: line 24: DB_DEFAULT_CONF_DIR: unbound variable
```

Note that we only release Debian-12 since February.

I hope it helps.

**Comment by adiii717** [comment]
broken for me using latest helm chart, here is how to reproduce
```
clusterName: "mycluster"


master:
  replicaCount: 1
  persistence:
    size: 30Gi
data:
  replicaCount: 1
coordinating:
  replicaCount: 0
ingest:
  replicaCount: 0

image:
  tag: 6.8.23


global:
  kibanaEnabled: true




security:
  enabled: false
  restEncryption: false

kibana:
  elasticsearch:
    security:
      auth:
        enabled: false
      tls:
        enabled: false
        usePemCerts: false
      
plugins: ""
```
