### ISSUE TITLE
[bitnami/grafana] Request for more documentation on how to implement admin.existingSecret

### ISSUE THREAD

**Issue by raphaelcervantes** [bitnami/charts#2528]
**Which chart**:
 grafana 1.5.2

**Is your feature request related to a problem? Please describe.**

It took me a long time to figure out how to set up the secret so that it can be interpreted properly by admin.existingSecret. After a lot of trial and error and guessing, I found a configuration file that works for setting up the secret.

```
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
type: Opaque
data:
  password: redacted
```
It took a long time for me to figure out that metadata.name = grafana-admin, and that I should configure data.password (as opposed to anything else like data.grafana-password or data.GF_SECURITY_ADMIN_PASSWORD). This is really not obvious because rabbitmq requires you to set data.rabbitmq-password, and postgresql requires you to set data.postgresql-password.

**Describe the solution you'd like**

I'd like more documentation about how to setup the secret for the grafana admin password. It's sensitive to the secret name. You also need to set data.password.

**Comment by carrodher** [comment]
Hi, thanks for the suggestion, I am not sure if this topic needs more documentation (or I can't see what is the real issue).

Using the default configuration, that means installing the chart without any extra parameters, a secret with a random password is created:
```
$ helm template myrelease bitnami/grafana
```
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: myrelease-grafana-admin
  labels:
    app.kubernetes.io/name: grafana
    helm.sh/chart: grafana-1.5.2
    app.kubernetes.io/instance: myrelease
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  GF_SECURITY_ADMIN_PASSWORD: "bjlVb0E4TGd5MA=="
```

If you want to use an already existing secret, you should install the chart with `--set admin.existingSecret=whatever-name`, but this name is not restricted to "grafana-admin", is the name of the secret already created. About the key, you should use the `--set admin.existingSecretPasswordKey=whatever-key` so you are not restricted to `password`. Those variables are documented in the [Parameters section of the `README.md`](https://github.com/bitnami/charts/tree/master/bitnami/grafana#parameters).

Apart from that, we are happy to receive contributions from users to improve our charts and documentation, feel free to create a PR with a new section in the README if you think this explanation can be improved.
