### ISSUE TITLE
[bitnami/grafana-mimir] Basic deployment failing; querier cannot contact query-frontend

### ISSUE THREAD

**Issue by SeanKilleen** [bitnami/charts#25338]
### Name and Version

bitnami/grafana-mimir 1.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

* Have an existing MinIO instance (does not seem to be the source of the issue)

The following terraform:

```hcl
# Showing how I achieved the config values
locals {
  mimir_template = templatefile("helm_chart_values/mimir.tftpl", {
    S3_ACCESS_KEY_ID     = kubernetes_secret.minio_creds.data["root-user"]
    S3_SECRET_ACCESS_KEY = var.minio_root_password
    S3_BUCKET_NAME       = "mimir"
    S3_ENDPOINT          = "${helm_release.minio_mimir[0].name}.${helm_release.minio_mimir[0].namespace}.svc.cluster.local:9000"
  })
}

resource "helm_release" "mimir" {
  #  count = var.uses_mimir ? 1 : 0 # Commented to show how I'm using it

  depends_on = [kubernetes_namespace.o11y, helm_release.minio_mimir]
  name       = "mimir"
  namespace  = kubernetes_namespace.o11y.metadata[0].name
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "grafana-mimir"
  version    = "1.0.2"

  values = ["${local.mimir_template}"]
  # values = ["${file("helm_chart_values/mimir.yaml")}"]

  set {
    name  = "minio.enabled"
    value = "false"
  }
}
```

And a `mimir.tftpl` as below (note: these data sources are added because our PV, which I can't control, forces WaitForFirstConsumer, which otherwise causes the Helm release to hang, so I'm controlling the PVCs myself since I can't do it through the chart).

```yaml
ingester:
  persistence:
    datasource: |
      name: data-mimir-grafana-mimir-ingester-0
      kind: PersistentVolumeClaim

compactor:
  persistence:
    datasource: |
      name: data-mimir-grafana-mimir-compactor-0
      kind: PersistentVolumeClaim

storeGateway:
  persistence:
    datasource: |
      name: data-mimir-grafana-mimir-store-gateway-0
      kind: PersistentVolumeClaim
  extraEnvVars:
     # Setting directly instead of from secret since this is a POC
    - name: S3_ACCESS_KEY_ID
      value: ${S3_ACCESS_KEY_ID}
    - name: S3_SECRET_ACCESS_KEY
      value: ${S3_SECRET_ACCESS_KEY}

mimir:
  blockStorage:
    backend: s3
    config: |
      access_key_id: ${S3_ACCESS_KEY_ID}
      secret_access_key: ${S3_SECRET_ACCESS_KEY}
      bucket_name: ${S3_BUCKET_NAME}
      endpoint: ${S3_ENDPOINT}
      insecure: true
```

### What is the expected behavior?

Mimir is deployed successfully and able to be connected to

### What do you see instead?

The Helm release fails after a timeout. Upon further inspection, the issue seems that the querier cannot contact the query-frontend.

The querier, based on its logs, has the correct IP address for the query front-end. But the querier is failing with `connection terminated` and the query-frontend pod restarts because it detects no querier connections.

Sample from the querier's logs -- 

```
ts=2024-04-23T18:03:17.693470735Z caller=frontend_processor.go:91 level=error msg="error processing requests" address=100.64.3.196:9095 err="rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection termination"
ts=2024-04-23T18:03:18.071927164Z caller=frontend_processor.go:91 level=error msg="error processing requests" address=100.64.3.196:9095 err="rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection termination"
ts=2024-04-23T18:03:18.253604285Z caller=frontend_processor.go:91 level=error msg="error processing requests" address=100.64.3.196:9095 err="rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection termination"
ts=2024-04-23T18:03:18.359267982Z caller=frontend_processor.go:91 level=error msg="error processing requests" address=100.64.3.196:9095 err="rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection termination"
ts=2024-04-23T18:03:18.403495138Z caller=frontend_processor.go:91 level=error msg="error processing requests" address=100.64.3.196:9095 err="rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection termination"
```

and from the query-frontend:

```
 ts=2024-04-23T18:04:01.135792002Z caller=frontend.go:358 level=info msg="not ready: number of queriers connected to query-frontend is 0"
ts=2024-04-23T18:04:01.135902602Z caller=frontend.go:358 level=info msg="not ready: number of queriers connected to query-frontend is 0"
```

### Additional information

I've noticed that the querier network policy does not seem to have an egress policy that allows a match for query-frontend; only a policy that matches `querier`. I'm wondering if this could be the issue, but I don't know nearly enough to say so with confidence.
