### ISSUE TITLE
All ETCD nodes intermittently shut down when Disaster Recovery CronJob failed.

### ISSUE THREAD

**Issue by kworkbee** [bitnami/charts#25346]
### Name and Version

etcd 9.7.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Enable `disasterRecovery`.

### Are you using any custom parameters or values?

```yaml
disasterRecovery:
  enabled: true
  pvc:
    storageClassName: efs
```

### What is the expected behavior?

`CronJob` must be successfully completed.

### What do you see instead?

It seems to be intermittent failures.

Event shows : `Job reached backoff limit`

As a result, errors occur when ETCD retrieves Broken data from Snapshot.
