### ISSUE TITLE
Allow templating NetworkPolicy ingressNSMatchLabels values?

### ISSUE THREAD

**Issue by bpfoster** [bitnami/charts#25340]
### Name and Version

bitnami/mongodb 15.1.5

### What is the problem this feature will solve?

I'm looking to lock down NetworkPolicies to only allow ingress traffic from the same namespace as the deployment.

### What is the feature you are proposing to solve the problem?

Conceptually, I was thinking I could configure the chart like so:
```yaml
networkPolicy:
  allowExternal: false
  ingressNSMatchLabels:
    kubernetes.io/metadata.name: "{{ .Release.Namespace }}"
```

However the chart [takes the raw](https://github.com/bitnami/charts/blob/288a544c640bd8850b6e2b40c254d246952524a9/bitnami/mongodb/templates/networkpolicy.yaml#L82) `ingressNSMatchLabels` values, so I cannot use `{{ .Release.Namespace }}` here.

Is it possible to render these values to accommodate this use case?  Is there another way already possible in the chart to do this that I'm not seeing?

The verbiage in the README is a little confusing I also think. `allowExternal` is a value, but if I understand correctly it's not really about external so much as requiring the pod to have a specific label, regardless of the namespace.  Similarly on the description for `ingressNSMatchLabels`:  `Labels to match to allow traffic from other namespaces` but it doesn't look like the namespace restriction is in place to begin with.

This issue is specific to the MongoDB chart but it looks like most NetworkPolicies in this repository follow the same template, so for consistency sake, it may be scoped to more charts than just this.

**Comment by bpfoster** [comment]
Ok, after more in depth testing, I do see that when the `podSelector` is added by `allowExternal: false`, it implies from that namespace.  My mistake there!

Is there a way to accomplish this without having to add the `mongodb-client` label to all my pods?

**Comment by fmulero** [comment]
Hi @bpfoster, sorry for my late response.

As you mentioned If `allowExternal: false` only pods with the label `mongodb-client: true´ will be allowed. You can add an `extraIngress rule` to allow traffic from your namespace, something like this should be enough:
```yaml
```

**Comment by fmulero** [comment]
Hi @bpfoster, sorry for my late response.

As you mentioned If `allowExternal: false` only pods with the label `mongodb-client: true` will be allowed. You can add an `extraIngress rule` to allow traffic from your namespace, something like this should be enough:
```yaml
networkPolicy:
  allowExternal: false
  extraIngress: |
    - ports:
      - port: {{ .Values.containerPorts.mongodb }}
    {{- if .Values.metrics.enabled }}
      - port: {{ .Values.metrics.containerPort }}
    {{- end }}
      from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ include "common.names.namespace" . | quote }}
```

Could you give it a try?

**Comment by fmulero** [comment]
Giving it a glance, I think this feature should be more flexible. Your use case makes sense and probably other users have that kind of restrictions. With our current configuration we are forcing to use the `mongodb-client: true` label if you want to restrict the traffic and that looks like a back door. Do you have any proposal in mind?

**Comment by bpfoster** [comment]
I'm not sure if it's a backdoor or not.  I guess someone with access could simply create a pod in the same namespace and give it that label to get access, but not sure any way to prevent that here.

I can see the use case of the `mongodb-client: true` label, if you want to restrict only certain pods in your namespace to connect.  Theoretically this could work for me.  Basically I'd want all pods in my app to have this connectivity though, so I'd rather not have to add the label to every pod.

What I was looking for was a way to simply say "all pods in this namespace can connect", or "all pods in my application can connect".

First attempt at doing that was
```
networkPolicy:
  allowExternal: false
  ingressNSMatchLabels:
    kubernetes.io/metadata.name: "{{ .Release.Namespace }}"
```
but the generated selector took the ` "{{ .Release.Namespace }}"` as a literal.

Considering maybe narrowing down on labels as well:
```
networkPolicy:
  allowExternal: false
  ingressNSMatchLabels:
    kubernetes.io/metadata.name: "{{ .Release.Namespace }}"
  ingressNSPodMatchLabels:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
```
but again the generated selector takes the ` "{{ .Release.Names }}"` as a literal.

These rules would get added to the NetworkPolicy alongside the already-defined MongoDB ports so that I don't have to copy-paste them out of the Bitnami chart (and hope they never change!).

My naive proposal would therefore be to simply change the matchLabels from
```
{{ $key | quote }}: {{ $value | quote }}
```

to something like 
```
{{ $key | quote }}: {{ (tpl $value $) | quote }}
```


Maybe another (or additional) proposal would be to allow configuring the podSelector.  Move
```
matchLabels:
    {{ template "common.names.fullname" . }}-client: "true"
```
into the values.yaml, call `common.tplvalues.render` on it.  This would allow users to override the value with `{}` (all pods in the namespace) or some other labeling scheme they decide on.
e.g:
```
from:
    - podSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.networkPolicy.ingressPodSelector "context" $ ) | nindent 12 }}
````
