### ISSUE TITLE
[bitnami/grafana-loki] Read S3 credentials from secret

### ISSUE THREAD

**Issue by seb-835** [bitnami/charts#25362]
### Name and Version

bitnami/grafana-loki 4.0.0

### What is the problem this feature will solve?

Hi,
I want to avoid my S3 credentials being put as text in the Values File in the storage_config block
I do not find the way, but I may be wrong.   
```yaml
       overrideConfiguration:
          auth_enabled: true

          storage_config:
            aws:
              s3: s3://USER:PASSWORD@ENDPOINT
```

In docs,  ExtraEnvVars can be added to the subsections: distributor, compactor, ingester, querier, queryFrontend and vulture.  but NOT storage_config.

If I am wrong can you give me an example how-to do it?
Best

### What is the feature you are proposing to solve the problem?

use   extraEnvVars in  storage_config like this : 

```yaml
          storage_config:
             extraEnvVars:
                - name: MINIO-USER
                  valueFrom:
                     secretKeyRef:
                         name:  minio-creds
                         key: root-user
                 - name: MINIO-PASSWORD
                   valueFrom:
                      secretKeyRef:
                         name:  minio-creds
                         key: root-password
              aws:
                s3: s3://$MINIO-USER:$MINIO-PASSWORD@minio.svc
```
