### ISSUE TITLE
[bitnami/mediawiki] Upgrade mediawiki helm package 20.0.2 and having a file permission denied issue

### ISSUE THREAD

**Issue by iain-ilearner** [bitnami/charts#25374]
### Name and Version

bitnami/mediawiki 20.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

There seems to be an equivalent issue for mediawiki that affected wordpress in issue #24590 

```bash
helm upgrade wiki oci://registry-1.docker.io/bitnamicharts/mediawiki 
```

### Are you using any custom parameters or values?

values.yaml:
```yaml
    extraVolumes:
      - name: custom-htaccess
        configMap:
          name: wiki-htaccess-configmap
          items:
            - key: mediawiki-htaccess.conf
              path: mediawiki-htaccess.conf
```

### What do you see instead?

```
cp: cannot create regular file '/opt/bitnami/apache/conf/./vhosts/00_status-vhost.conf': Permission denied
cp: cannot create regular file '/opt/bitnami/apache/conf/./vhosts/mediawiki-https-vhost.conf': Permission denied
cp: cannot create regular file '/opt/bitnami/apache/conf/./vhosts/mediawiki-vhost.conf': Permission denied
```
