### ISSUE TITLE
[bitnami/kafka] Issue with kafka sasl.client.passwords

### ISSUE THREAD

**Issue by Skull0ne** [bitnami/charts#25377]
### Name and Version

bitnami/kafka

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Command to install :
```
kubectl -n kafka create secret generic kafka-ssl --from-file=kafka-ca.crt=./kafka-ca.crt --from-file=kafka.crt=./kafka.crt --from-file=kafka.key=./kafka.key
helm install --atomic kafka oci://registry-1.docker.io/bitnamicharts/kafka -n kafka -f values.yml
```

The first time I deployed kafka, I saved the passwords and added them to my values.yml (also to avoid errors during helm upgrade).

I tried to update them to something more complicated, for "interbroker" and "controller" it's ok (I had issues with some special characters like '&').
However for the "client" password, nothing works... The Kafka Exporter keeps failing to start.

I thought it was due to some special charaters so I removed them. So I tried a password with the same length, no repetitive characters, uppercase/lowercase/number, but still KO. The only working password is the one automatically generated the 1st time.

Also between each test I uninstall the chart : 
`helm -n kafka uninstall kafka`

sasl.client:
    passwords: 's5tEH3Ub9v'   ## WORK, Generated automatically
    passwords: 'aeg02efaQu'   ## FAIL
    passwords: 'aivng3jouSRaing2eemoR41oPh4To2ei'  ## FAIL

### Are you using any custom parameters or values?

Values.yml : 
```
listeners:
  client:
    protocol: "SASL_SSL"
  controller:
    protocol: "SASL_SSL"

tls:
  type: "PEM"
  existingSecret: 'kafka-ssl'

metrics:
  kafka:
    enabled: true
    extraFlags: {tls.insecure-skip-tls-verify: ""}

sasl:
  interbroker:
    password: 'cae1eipoo@k6mo!6IJ1eiHie7eigh_ie'
    #password: '4FKkMbGOEe'   ## Generated automatically
  controller:
    password: 'kool2sha_0eG+aech0utah6ahj!ejoox'
    #password: 'Vl0LDaJsJ3'   ## Generated automatically
  client:
    passwords: 's5tEH3Ub9v'   ## WORK, Generated automatically
    passwords: 'aeg02efaQu'   ## FAIL
    passwords: 'aivng3jouSRaing2eemoR41oPh4To2ei'  ## FAIL

kraft:
  clusterId: 'mwa1PozAqnjiuIaRKeZKdy'
```

### What is the expected behavior?

Kafka Exporter should start

### What do you see instead?

```
Error Init Kafka Client: kafka: client has run out of available brokers to talk to: 3 errors occurred:
	* EOF
	* EOF
	* EOF
```
