### ISSUE TITLE
[bitnami/elasticsearch] Helm template renders incorrectly when affinities or pod annotations are not set in values

### ISSUE THREAD

**Issue by mihirsamdarshi** [bitnami/charts#25398]
### Name and Version

bitnami/elasticsearch 21.0.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Simply render the chart using the default values

```bash
helm template --version 21.0.1 elasticsearch bitnami/elasticsearch
```

### What is the expected behavior?

I think the default `values.yaml` should provide the correct values for those parameters

### What do you see instead?

All of the StatefulSets have YAML that looks incorrect. See below for an example of how the YAML looks.
 
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-master
...
        ## Istio Labels: https://istio.io/docs/ops/deployment/requirements/
        app: master
      annotations:
    spec:
      serviceAccountName: elasticsearch-master
      
      automountServiceAccountToken: false
      affinity:
        podAffinity:
          
        podAntiAffinity:
          
        nodeAffinity:
          
      securityContext:
```
