### ISSUE TITLE
Use sealed secret resource for bitnami kube-prometheus-stack and thanos chart

### ISSUE THREAD

**Issue by suxiaoxiaomm** [bitnami/charts#25422]
### Name and Version

kube-prometheus-stack:57.1.1, 

### What architecture are you using?

None

### What steps will reproduce the bug?

Dear experts,
I am trying to use ArgoCD to deploy my observability stack, which requires to use Sealed Secret to manage my secrets.
For kube-prometheus-stack, there are secrets such as email account info used by alertmanager to send email alerts, the storage account for Thanos to connect to object storage, etc.

Previously, I only put the Env variable name as a placeholder in my values.yaml file, and **envsubst them during the deployment pipeline** as below:

```yaml
kube-prometheus-stack:
  alertmanager:
    enabled: true
    config:
      global:
        resolve_timeout: 5m
        smtp_auth_identity: "alert@xxx.com"
        **smtp_auth_password: "$SEC_ALERT_EMAIL_AUTH_PASSWORD"**
```
Now as the practice for Gitops, I need to put my secrets inside the repo and I decided to create a SealedSecret resource and get it deployed to the cluster.

**I am wondering how I integrate Sealed Secret with the current kube-prometheus-stack chart.  How can the chart refer to my SealedSecret resource automatically and get the correct values(or the Secret which is converted from this SealedSecret resource)?**

### What do you see instead?

The secret value cannot be correctly referred to by other resources.

**Comment by rouke-broersma** [comment]
The thanos chart has:

```
thanos:
  existingObjstoreSecret: thanos-secret
  existingObjstoreSecretItems:
    - key: config-file.yaml
      path: objstore.yml
```

Alertmanager has:

```
  ## @param alertmanager.externalConfig Alertmanager configuration is created externally. If true, `alertmanager.config` is ignored, and a secret will not be created.
  ## Alertmanager requires a secret named `alertmanager-{{ template "kube-prometheus.alertmanager.fullname" . }}`
  ## It must contain:
  ##     alertmanager.yaml: <config>
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/alerting.md#alerting
  ##
  externalConfig: false
```
