### ISSUE TITLE
Policies do not support conditions

### ISSUE THREAD

**Issue by ammirator-administrator** [bitnami/charts#25434]
### Name and Version

bitnami/minio 14.3.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Create a policy in helm values file using the provisioner, and add a `conditions` field to that (Below I attached an example)
After installing the chart with these values, go to the policies tab in UI and check the policy and the Conditions field is missing
And it is missing because in the Provisioning job Config map such field is not present at all 

### Are you using any custom parameters or values?

```yaml
provisioning:
  enabled: true
  policies:
    - name: my-bucket-policy
      statements:
        - resources:
            - "arn:aws:s3:::my-bucket/*"
          effect: "Allow"
          actions:
            - "s3:GetObject"
          conditions:
            - StringLike: |
                "aws:Referer": [
                  "https://localhost:3000/*",
                  "http://localhost:3000/*"
                ]
 ```

### What is the expected behavior?

The expected behaviour is that the conditions should be present in policy, and work as intended per documentation

### What do you see instead?

No conditions field in the bucket policy
