### ISSUE TITLE
[bitnami/postgresql] Included networkpolicy blocks backup job from using dns

### ISSUE THREAD

**Issue by pixil98** [bitnami/charts#25438]
### Name and Version

bitnami/postgresql 15.2.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

After enabling the backup cronjob in the helm chart, the backup jobs always fail because they are unable to resolve the IP for the postgresql service name. This appears to be because the provided networkpolicy for the backup job only allows egress on port 5432/TCP. After deleting the network policy, the job is able to query dns again.

### Are you using any custom parameters or values?
```yaml
auth:
  database: authentik
  username: authentik
  existingSecret: authentik-secrets
  secretKeys:
    adminPasswordKey: postgresql-admin-password
    userPasswordKey: postgresql-user-password
  usePasswordFiles: true
backup:
  enabled: true
```
### What is the expected behavior?

I would expect it to be able to query DNS as it is needed for performing the backup.

### What do you see instead?

It fails after timing out.
