### ISSUE TITLE
[bitnami/kube-prometheus]: support tsdb runtime configuration

### ISSUE THREAD

**Issue by rfc2119** [bitnami/charts#25444]
### Name and Version

bitnami/kube-prometheus 9.0.5

### What is the problem this feature will solve?

The TSDB enables support for configuring the time window out-of-order samples. It was implemented here https://github.com/prometheus/prometheus/pull/11075 in Prometheus v2.39.0, and the Prometheus operator supports [configuring it](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.TSDBSpec). However, the generated `prometheus.env.yaml` file does not include that option, and also the documentation for the helm chart does not mention it. Here's an example "values.yaml" file:
```yaml
prometheus:
  retention: 30d
  tsdb:
    outOfOrderTimeWindow: 5m
```

And in the Prometheus config file itself: [Configuration | Prometheus](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tsdb)

### What is the feature you are proposing to solve the problem?

Support configuring TSDB's runtime options, including out-of-order samples. The latter option is still considered experimental, but it's widely used in production and is effective in large clusters.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by rfc2119** [comment]
Thanks @carrodher . Before submitting a PR, I was trying to test this out on a live version bitnami/kube-prometheus chart (9.0.7). I have edited the CRD "monitoring.coreos.com/v1/prometheus" on-the-fly to include the relevant stanza, like this:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/version: 0.73.2
    helm.sh/chart: kube-prometheus-9.0.7
spec:
  additionalScrapeConfigs:
    key: scrape-jobs.yaml
    name: additional-scrape-jobs-prometheus-prometheus
  tsdb:    # <-------------------
    outOfOrderTimeWindow: 2m
```
However, I am getting 
> strict decoding error: unknown field "spec.tsdb"

The operator clearly supports TSDBSpec inside PrometheusSpec. I have no mutating or validating webhooks. Any idea why this errors ?
