### ISSUE TITLE
configmap keycloak.conf no newline

### ISSUE THREAD

**Issue by asvataa** [bitnami/charts#25455]
### Name and Version

bitnami/keycloak 21.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

To reproduce the bug, you must set configuration block and add something
```yaml
configuration: |
  foo=bar
```

### What is the expected behavior?

Correct keycloak.conf

### What do you see instead?

When I try to add a line to the config file it merges with the current one
In the keyclock.conf I see the next configuration

```
foo=bardb = postgres
db-username = example
db-password = example
db-url = jdbc:postgresql://keycloak-postgresql:5432/bitnami_keycloak?currentSchema=public
metrics-enabled = false
health-enabled = false
http-enabled = true
http-relative-path = /
http-port = 8080
https-port = 8443
hostname-strict = false
cache-stack = kubernetes
cache = ispn
log-level = INFO
log-console-output = default
proxy = edge
```

### Additional information

I think if you remove the symbol - in configmap it will fix the problem

```yaml
data:
  keycloak.conf: |
    {{- .Values.configuration | nindent 4 }}
```

instead of this

```yaml
data:
  keycloak.conf: |-
    {{- .Values.configuration | nindent 4 }}
```
