### ISSUE TITLE
[bitnami/supabase] Auth pod failing in self-hosted Supabase in Kubernetes with external DB 

### ISSUE THREAD

**Issue by lautaro79** [bitnami/charts#25452]
### Name and Version

bitnami/supabase 4.0.3

### What architecture are you using?

None

### What steps will reproduce the bug?

Execute this command:

`helm upgrade --install supabase bitnami/supabase --version 4.0.3 -n supabase --values=./values.example.yaml`

### Are you using any custom parameters or values?

Where the file values.example.yaml contains:

```yaml
studio:
  ingress:
    path: /
    enabled: true
    hostname: 'localhost'
    ingressClassName: nginx

postgresql:
  enabled: false
externalDatabase:
  host: 'my.external.db.host'
  port: '5432'
  user: 'supabase_admin'
  database: 'supabase'
  password: 'mysecretpassword'
  existingSecret: 'supabase-externaldb'
  existingSecretPasswordKey: db-password
```

### What is the expected behavior?

All pods running correctly and connected to the configured External DB

### What do you see instead?

Auth pod fails to start with the following error log:

```
{"level":"info","msg":"Go runtime metrics collection started","time":"2024-04-29T13:17:17Z"}
{"args":[".spdx-gotrue.spdx"],"component":"pop","level":"warning","msg":"ignoring file %s because it does not match the migration file pattern","time":"2024-04-29T13:17:17Z"}
{"args":["auth"],"component":"pop","level":"warning","msg":"ignoring file %s because it does not match the migration file pattern","time":"2024-04-29T13:17:17Z"}
{"args":["gotrue"],"component":"pop","level":"warning","msg":"ignoring file %s because it does not match the migration file pattern","time":"2024-04-29T13:17:17Z"}
{"args":["gotrue-2.149.0.txt"],"component":"pop","level":"warning","msg":"ignoring file %s because it does not match the migration file pattern","time":"2024-04-29T13:17:17Z"}
{"args":[0.018388729],"component":"pop","level":"info","msg":"%.4f seconds","time":"2024-04-29T13:17:17Z"}
{"level":"fatal","msg":"running db migrations: Migrator: problem creating schema migrations: could not execute CREATE TABLE \"schema_migrations\" (\n\"version\" VARCHAR (14) NOT NULL,\nPRIMARY KEY(\"version\")\n);\nCREATE UNIQUE INDEX \"schema_migrations_version_idx\" ON \"schema_migrations\" (version);: ERROR: no schema has been selected to create in (SQLSTATE 3F000)","time":"2024-04-29T13:17:17Z"}
```

### Additional information

`problem creating schema migrations: could not execute CREATE TABLE \"schema_migrations\" `

`no schema has been selected to create in (SQLSTATE 3F000)`
