### ISSUE TITLE
Defining networkpolicy.extraEgress causes nil pointer error upon deployment

### ISSUE THREAD

**Issue by musdotdigital** [bitnami/charts#25451]
### Name and Version

bitnami/mysql:10.1.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Create custom values config with `networkpolicy.extraEgress` defined
2. Run `helm install mysql oci://registry-1.docker.io/bitnamicharts/mysql -f values.yaml`
3. See the `INSTALLATION FAILED` error 
4. Tested on GKE Cluster and locally on k3d (Mac M1)

### Are you using any custom parameters or values?

```yaml
# values.yaml
networkPolicy:
  enabled: true
  allowExternal: false
  allowExternalEgress: false
  extraEgress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ns-1
        podSelector:
          matchLabels:
            component: "server"
```

### What is the expected behavior?

Deployment should be successful with a network policy defined containing the egress outlined in `values.yaml`.

### What do you see instead?

```
Error: INSTALLATION FAILED: template: mysql/templates/networkpolicy.yaml:43:64: executing "mysql/templates/networkpolicy.yaml" at <.Values.rts.networkPolicy.extraEgress>: nil pointer evaluating interface {}.networkPolicy
```

### Additional information

The deployment template for the `networkpolicy` contains the following:
```
{{- if .Values.networkPolicy.extraEgress }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.rts.networkPolicy.extraEgress "context" $ ) | nindent 4 }}
{{- end }}
```

It is depending on `rts.networkpolicy.extraEgress` which is undefined. The only way to fix this problem currently is to pass `extraEgress` as `true` and then define the egress under `rts.networkpolicy.extraEgress`.

```yaml
networkPolicy:
  ...
  extraEgress: true
rts:
  networkPolicy:
    extraEgress:
      - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ns-1
          podSelector:
            matchLabels:
              component: "server"
```

This is an unexpected behavior considering that `extraIngress` does not rely on such value:
```
{{- if .Values.networkPolicy.extraIngress }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.networkPolicy.extraIngress "context" $ ) | nindent 4 }}
{{- end }}
```

Hence I expect that the `networkpolicy` deployment should be the following for `extraEgress`:
```
{{- if .Values.networkPolicy.extraEgress }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.networkPolicy.extraEgress "context" $ ) | nindent 4 }}
{{- end }}
```
