### ISSUE TITLE
[bitnami/airflow] DAG sync error: unable to access

### ISSUE THREAD

**Issue by zygias** [bitnami/charts#25463]
### Name and Version

bitnami/airflow 18.0.6

### What architecture are you using?

None

### What steps will reproduce the bug?

Hello, I faced an issue with dags sync and I need help. 
Error message in airflow scheduler pod:

```
clone-repositories - Cloning into '/dags/dags'...
clone-repositories - fatal: unable to access 'https://gitlab.com/xxxx/xxx/xxx/dags.git/': Failed to connect to gitlab.com port 443 after 14 ms: Couldn't connect to server
```
Values:
```yaml
git:
  dags:
    enabled: true
    repositories:
      - repository: "https://{USERNAME}:{PASSWORD}@gitlab.com/xxx/xxx/xxx/dags.git"
        branch: "main"
        name: "dags"
        path: "etl/dags"
  sync:
    interval: 30
```
i have tried to clone locally with same repo url -> `https://{USERNAME}:{PASSWORD}@gitlab.com/xxx/xxx/xxx/dags.git`
and it works, but not in the scheduler pod. 

Anyone could help? :) 

### What do you see instead?
```
clone-repositories - Cloning into '/dags/dags'...
clone-repositories - fatal: unable to access 'https://gitlab.com/xxxx/xxx/xxx/dags.git/': Failed to connect to gitlab.com port 443 after 14 ms: Couldn't connect to server
```
