### ISSUE TITLE
[bitnami/postgresql] "postgres" user password does not seem to be set properly

### ISSUE THREAD

**Issue by SeanKilleen** [bitnami/charts#25472]
### Name and Version

bitnami/postgresql 15.2.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Use a helm template file of:

```yaml
auth:
  enablePostgresUser: false
  username: "myCustomUser"
  password: "myCustomPassword"
  database: "akka"
```

### What is the expected behavior?

* A custom user, `myCustomUser` is created with the password `myCustomPassword`
* A database is created called `akka`
* A `postgres` user is not created.

### What do you see instead?

Error: execution error at (postgresql/templates/secrets.yaml:23:16): 
│ PASSWORDS ERROR: The secret "postgres-postgresql" does not contain the key "password"
