### ISSUE TITLE
argocd: Failed to query provider "https://argocd.mydomain.com/api/dex"

### ISSUE THREAD

**Issue by ktzsolt** [bitnami/charts#25476]
### Name and Version

bitnami/argo-cd 6.0.14

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Trying to set up oidc with self hosted gitlab, I created application registration in gitlab with the following scopes:

    api (Access the authenticated user's API)
    read_user (Read the authenticated user's personal information)
    read_repository (Allows read-only access to the repository)
    openid (Authenticate using OpenID Connect)

for callback url: https://argocd.mydomain.com/api/dex/callback

I am using the following values.yaml to deploy the chart:

```yaml
dex:
  enabled: true
server:
  url: https://argocd.mydomain.com
  config:
    admin.enabled: "true"
    dex.config: |
      connectors:
      - type: gitlab
        id: gitlab
        name: Gitlab
        config:
          baseURL: "https://gitlab.mydomain.com"
          clientID: gitlab-client-id
          clientSecret: gitlab-client-secret
          url: https://argocd.mydomain.com
          users.anonymous.enabled: "false" 
  ingress:
    enabled: true
    hostname: argocd.mydomain.com
    ingressClassName: "nginx"
    pathType: "Prefix"
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    tls: true
    path: "/"
```

When I click on log in with gitlab on the argocd login page I get the following in the browser:

    Failed to query provider "https://argocd.mydomain.com/api/dex": Get "https://argocd-dex-server:5556/api/dex/.well-known/openid-configuration": dial tcp: lookup argocd-dex-server on 10.43.0.10:53: server misbehaving

In argocd-argo-cd-server pod log I see only this: 

    time="2024-04-30T19:28:42Z" level=info msg="Initializing OIDC provider (issuer: https://argocd.mydomain.com/api/dex)"    

In argocd-argo-cd-dex pod there is no log, only that it started up and listening on 5556,5557,5558 ports:

    Defaulted container "dex" out of: dex, copyutil (init)
    time="2024-04-30T18:01:31Z" level=info msg="ArgoCD Dex Server is starting" built="2024-04-26T15:20:05Z" commit=37b1cf5306f9c245f188c4c0566c23a0f80cdc65 namespace=argocd version=v2.10.8+37b1cf5
    time="2024-04-30T18:01:31Z" level=info msg="Generating self-signed TLS certificate for this session"
    time="2024-04-30T18:01:32Z" level=info msg="Starting configmap/secret informers"
    time="2024-04-30T18:01:33Z" level=info msg="Configmap/secret informer synced"
    time="2024-04-30T18:01:33Z" level=info msg="0xc000f283c0 subscribed to settings updates"
    time="2024-04-30T18:01:33Z" level=info msg="Dex Version: v2.39.1, Go Version: go1.21.9, Go OS/ARCH: linux amd64"
    time="2024-04-30T18:01:33Z" level=info msg="config issuer: https://argocd.fms-dev.ps.cloudapp.azs.tsmcloud.hu/api/dex"
    time="2024-04-30T18:01:33Z" level=info msg="config storage: memory"
    time="2024-04-30T18:01:33Z" level=info msg="config static client: Argo CD"
    time="2024-04-30T18:01:33Z" level=info msg="config static client: Argo CD CLI"
    time="2024-04-30T18:01:33Z" level=info msg="config static client: Argo CD PKCE"
    time="2024-04-30T18:01:33Z" level=info msg="config connector: gitlab"
    time="2024-04-30T18:01:33Z" level=info msg="config skipping approval screen"
    time="2024-04-30T18:01:33Z" level=info msg="config refresh tokens rotation enabled: true"
    time="2024-04-30T18:01:33Z" level=info msg="keys expired, rotating"
    time="2024-04-30T18:01:34Z" level=info msg="keys rotated, next rotation: 2024-05-01 00:01:34.072310084 +0000 UTC"
    time="2024-04-30T18:01:34Z" level=info msg="listening (telemetry) on 0.0.0.0:5558"
    time="2024-04-30T18:01:34Z" level=info msg="listening (https) on 0.0.0.0:5556"
    time="2024-04-30T18:01:34Z" level=info msg="listening (grpc) on 0.0.0.0:5557"

looks like a dns/adressing issue, I don't have `argocd-dex-server` in the cluster, I have the following services:

| NAME|TYPE | CLUSTER-IP| EXTERNAL-IP|  PORT(S)| 
|--------|--------|--------|--------|--------|
argocd-argo-cd-app-controller  | ClusterIP|   10.43.8.237  |   <none>      |  8082/TCP
**argocd-argo-cd-dex**              |ClusterIP   |10.43.89.232   | <none>        |5556/TCP,5557/TCP
argocd-argo-cd-repo-server   |   ClusterIP|   10.43.212.183   |<none>   |     8081/TCP
argocd-argo-cd-server           |ClusterIP  | 10.43.16.232 |   <none>       | 80/TCP,443/TCP
argocd-redis-headless           |ClusterIP  | None            |<none>        |6379/TCP
argocd-redis-master             |ClusterIP   |10.43.19.188    |<none>        |6379/TCP

How can I tell the chart that my argocd dex service is listening on `http://argocd-argo-cd-dex` instead of `https://argocd-dex-server` ? Or what else should I do to make it work?

### Are you using any custom parameters or values?

```yaml
dex:
  enabled: true
server:
  url: https://argocd.mydomain.com
  config:
    admin.enabled: "true"
    dex.config: |
      connectors:
      - type: gitlab
        id: gitlab
        name: Gitlab
        config:
          baseURL: "https://gitlab.mydomain.com"
          clientID: gitlab-client-id
          clientSecret: gitlab-client-secret
          url: https://argocd.mydomain.com
          users.anonymous.enabled: "false" 
  ingress:
    enabled: true
    hostname: argocd.mydomain.com
    ingressClassName: "nginx"
    pathType: "Prefix"
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    tls: true
    path: "/"
```

### What is the expected behavior?

Log in with gitlab account

### What do you see instead?

Failed to query provider "https://argocd.mydomain.com/api/dex": Get "https://argocd-dex-server:5556/api/dex/.well-known/openid-configuration": dial tcp: lookup argocd-dex-server on 10.43.0.10:53: server misbehaving

**Comment by ktzsolt** [comment]
I was able to circumvent this problem with setting these extraArgs:

```yaml
dex:
  enabled: true
  extraArgs:
    - --disable-tls 
server:
  extraArgs: 
    - --dex-server
    - http://argocd-argo-cd-dex.argocd.svc.cluster.local:5556
    - --dex-server-plaintext 
```

The dex server is not exposed to the outside, it is reached by the argocd-server and argocd-server has ingress and TLS is terminated on the ingress. So why is tls the default for dex that doesn't even work out of the box with the argocd generated tls certs?
