### ISSUE TITLE
[bitnami/postgresql-ha] postgresql-ha & pgpool with ldap connection , pam_authenticate failed: User not known to the underlying authentication module

### ISSUE THREAD

**Issue by kaili251196** [bitnami/charts#25492]
### Name and Version

bitnami/pgpool 4.5.1-debian-12-r2

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Helm installation 
2. Set up postgresql in HA
3. Integrated with LDAP enabled
4. postgresql set trust all in pghba
5. pgpool with pam authentication

### Are you using any custom parameters or values?

Customized LDAP
```yaml
ldap:
  enabled: true
  existingSecret: ""
  uri: "ldap://data.ldap.com:389"
  basedn: "DC=ldap,DC=com"
  binddn: "CN=dbservice,OU=database account,OU=AutomateAccount,DC=ldap,DC=com"
  bindpw: "ldappassword"
  bslookup: "OU=database account,OU=AutomateAccount,DC=ldap,DC=com"
  scope: "sub"
  tlsReqcert: ""
  nssInitgroupsIgnoreusers: root,nslcd
```
### What is the expected behavior?

pgpool able to authenticate from LDAP directory 
postgresql is set up as pgHbaTrustAll: true

### What do you see instead?
```
psql: error: connection to server at "postgres.ldap.com" (10.xx.xx.xx), port 5432 failed: FATAL:  failed authentication against PAM
DETAIL:  pam_authenticate failed: User not known to the underlying authentication module
```
### Additional information
```
ldapsearch -x -H "ldap://data.ldap.com:389" -D "CN=dbservice,OU=database account,OU=AutomateAccount,DC=ldap,DC=com" -w "ldappassword" -b "OU=database account,OU=AutomateAccount,DC=ldap,DC=com" -s sub "(objectClass=*)" 

Success! ldap search
```
---

Errors i am facing
```
psql "sslmode=require host=postgres.ldap.com port=5432 dbname=postgres user=dbservice"

psql: error: connection to server at "postgres.ldap.com" (10.xx.xx.xx), port 5432 failed: FATAL:  failed authentication against PAM
DETAIL:  pam_authenticate failed: User not known to the underlying authentication module
```
---

user dbservice is already create in postgresql database
