### ISSUE TITLE
Missing port assignment for http-shutdown in deployment chart

### ISSUE THREAD

**Issue by Daxcor69** [bitnami/charts#25507]
### Name and Version

bitnami/contour 17.0.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

deploy chart as a DEPLOYMENT  as daemonset works as expected.

### Are you using any custom parameters or values?
```yaml
contour:
  nodeSelector:
    node-role.kubernetes.io/bmproxy: ""
  resourcesPreset: "large"
  replicaCount: 2

envoy:
  kind: deployment
  replicaCount: 1

  nodeSelector:
    node-role.kubernetes.io/bmproxy: ""

  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: "x.x.x.x"

metrics:
  serviceMonitor:
    enabled: true
```
### What is the expected behavior?

successful deployment

### What do you see instead?

pod pending with the following error: 
```
Readiness probe errored: strconv.Atoi: parsing "http-shutdown": invalid syntax
```
### Additional information

port assignment for http-shutdown is missing from the template.
