### ISSUE TITLE
[bitnami/etcd] RBAC not working

### ISSUE THREAD

**Issue by robertcankney** [bitnami/charts#25525]
### Name and Version

bitnami/etcd 10.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. The environment is EKS on AWS, running Kubernetes 1.24
2. With the following custom values:
```
auth:
  rbac:
    create: true
    existingSecret: etcd-password
    existingSecretPasswordKey: PASSWORD
    allowNoneAuthentication: false
  client:
    secureTransport: true
    useAutoTLS: true
replicaCount: 3
```

3. Install works as expected
4. After install, RBAC is not set up at all. Getting any of the pods, I see these environmental variables:
```
- name: ALLOW_NONE_AUTHENTICATION
  value: "no"
- name: ETCD_ROOT_PASSWORD
  valueFrom:
    secretKeyRef:
      name: etcd-password
      key: PASSWORD
```
`kubectl exec`ing into the container, I can confirm the following variables are set:
```
ETCD_ROOT_PASSWORD=***REDACTED***
ALLOW_NONE_AUTHENTICATION=no
```

However, I see the following in the logs at startup:
```
{"level":"warn","ts":"2024-05-03T15:19:05.890308Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_ROOT_PASSWORD=***REDACTED***"}
```

This seems to be the source of the issue - I'm unsure why this is causing issues, though.

### Are you using any custom parameters or values?

Values.yaml:

```
auth:
  rbac:
    create: true
    existingSecret: etcd-password
    existingSecretPasswordKey: PASSWORD
    allowNoneAuthentication: false
  client:
    secureTransport: true
    useAutoTLS: true
replicaCount: 3
```

### What is the expected behavior?

RBAC should be enabled.

### What do you see instead?

```
{"level":"warn","ts":"2024-05-03T03:21:36.089445Z","logger":"etcd-client","caller":"v3@v3.5.13/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://***REDACTED***:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: authentication is not enabled"}
````

### Additional information

I tried this with chart versions 9.0.0, and 8.11.4 to no avail.
