### ISSUE TITLE
[bitnami/schema-registry] cannot start Schema Registry with external Kafka and SSL

### ISSUE THREAD

**Issue by meretri** [bitnami/charts#25522]
### Name and Version

bitnami/schema-registry

### What architecture are you using?

None

### What steps will reproduce the bug?

I am trying to deploy the schema registry with an external Kafka, which is already running. 

My auth section in my values.yaml looks like this:
```
auth:
  tls:
    enabled: false
    jksSecret: ""
    keystorePassword: ""
    truststorePassword: ""
    clientAuthentication: NONE
  kafka:
    jksSecret: kafka-jks
    tlsEndpointIdentificationAlgorithm: ""
    keystorePassword: pw
    truststorePassword: pw
    saslMechanism: PLAIN
externalKafka:
  brokers:
    - SSL://cdc-cluster-kafka-bootstrap.debezium.svc:9093
  listener:
    protocol: SSL
  sasl:
    user: user
    password: ""
    existingSecret: ""
                        
```

I have generated the secret like this:
```kubectl create secret generic kafka-jks --from-file=kafka.truststore.jks=client.truststore.jks --from-file=kafka.keystore.jks=kafka.keystore.jks```

The secret looks like this (removed the actual values for the secrets):
```
apiVersion: v1
data:
  kafka.keystore.jks: yyy
  kafka.truststore.jks: xxx
kind: Secret
metadata:
  creationTimestamp: "2024-05-03T13:23:17Z"
  name: kafka-jks
  namespace: schema-registry
  resourceVersion: "31829746"
  uid: 9524a074-e449-4ea3-bc69-b073e6efa485
type: Opaque
```
When I deploy the schema registry I get the following error:
```Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled with Kafka brokers.```

According to the documentation ([link](https://github.com/bitnami/charts/blob/main/bitnami/schema-registry/README.md)) one keystore should be enough, since I have set `tlsEndpointIdentificationAlgorithm: ""`

Can anyone point me to what's missing?

### What do you see instead?

as described above: ```Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled with Kafka brokers.```

### Additional information

I am using  bitnami/schema-registry:7.6.1-debian-12-r1 and the 18.0.4 release.

**Comment by meretri** [comment]
I tried with creating another secret, where I name the values `schema-registry.truststore.jks` like this:
`kubectl create secret generic kafka-jks-1 --from-file=schema-registry.truststore.jks=client.truststore.jks --from-file=schema-registry-0.keystore.jks=kafka.keystore.jks -n schema-registry`
```
auth:
  tls:
    enabled: false
    jksSecret: ""
    keystorePassword: ""
    truststorePassword: ""
    clientAuthentication: NONE
  kafka:
    jksSecret: kafka-jks-1
    tlsEndpointIdentificationAlgorithm: ""
    keystorePassword: pw
    truststorePassword: pw
    saslMechanism: PLAIN
externalKafka:
  brokers:
    - SSL://cdc-cluster-kafka-bootstrap.debezium.svc:9093
  listener:
    protocol: SSL
  sasl:
    user: user
    password: ""
    existingSecret: ""
```
Then I get a different error:
`cp: cannot create regular file '/opt/bitnami/schema-registry/certs/schema-registry.truststore.jks': Read-only file system`

**Comment by fmulero** [comment]
It seems there is no mount point for `/opt/bitnami/schema-registry/certs`. Probably adding an `extraVolumeMount` will fix the issue temporary. Could you give it a try?
```yaml
extraVolumeMounts:
  - name: empty-dir
    mountPath: /opt/bitnami/schema-registry/certs/
    subPath: app-certs
```
