### ISSUE TITLE
[bitnami / rabbitmq] not taking password from existingPasswordSecret

### ISSUE THREAD

**Issue by k8s-learner** [bitnami/charts#2557]
I am facing the same issue as mentioned in this ticket
#110

The solution provided was not working.

Can we please reopen this issue? I am facing the same problem.
@dani8art Your above solution is not fixing the problem. First, I things there was a typo. In your solution when created manually name should be "rabbitmq-password-secret" instead of secret-variable.

As you suggested I ran

`kubectl create secret generic rabbitmq-password-secret --from-literal=rabbitmq-password=test@123 -n rabbitmq`

even tried creating manually

```
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-password-secret
type: Opaque
data:    
  rabbitmq-password: cGFzc3dvcmQxMjM= # It is `password123` base64 encode 
```

Then I set existingPasswordSecret value in value.yaml

```
rabbitmq:
  ## RabbitMQ application username
  ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
  ##
  username: user

  ## RabbitMQ application password
  ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
  ##
  #password: password
  existingPasswordSecret: rabbitmq-password-secret
```
and I ran the helm
`helm install stable/rabbitmq --set rabbitmq.existingPasswordSecret=rabbitmq-password-secret --namespace rabbitmq`

Still it's not taking the correct password.
when I ran this command
`echo "Password : $(kubectl get secret --namespace rabbitmq trialco-rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)"`

I am just getting the blank Password
`Password :`
