### ISSUE TITLE
[postgresql] existingSecret does not work

### ISSUE THREAD

**Issue by LukeChannings** [bitnami/charts#2563]
**Which chart**:
postgresql:8.9.6

**Describe the bug**

I have a secret that looks like this:

```yaml
---
apiVersion: v1
data:
  postgresql-password: aVh5UDUwbk5tMwo=
kind: Secret
metadata:
  name: home-assistant-postgresql
  namespace: home-assistant
type: Opaque
```

I have deleted all data in the PV, and uninstalled that chart.
I have configured the chart with:

```yaml
useExistingSecret: home-assistant-postgresql
postgresqlUsername: home-assistant
postgresqlDatabase: home-assistant
```

When the pod starts, it outputs:

```
2020-05-08 21:48:17.491 GMT [180] FATAL:  password authentication failed for user "home-assistant"
2020-05-08 21:48:17.491 GMT [180] DETAIL:  Password does not match for user "home-assistant".
```

And I can't log in: `psql --host 127.0.0.1 -U home-assistant -d home-assistant -p 5432`

**Expected behavior**

I should be able to log in with the password defined in the secret

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4+k3s1", GitCommit:"3eee8ac3a1cf0a216c8a660571329d4bda3bdf77", GitTreeState:"clean", BuildDate:"2020-03-25T16:13:25Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by marcosbc** [comment]
AFAIK the correct property name is `existingSecret`, not `useExistingSecret`. Could you check if it works with that?

**Comment by LukeChannings** [comment]
Hey, that's a typo, the values I was using before I just gave up and used a regular deployment with `postgres/postgres` was:

```yaml
global:
postgresql:
    existingSecret: postgres-postgresql

image:
registry: docker.io
repository: bitnami/postgresql
tag: 11.7.0-debian-10-r99
pullPolicy: IfNotPresent
debug: true

volumePermissions:
enabled: false
image:
    registry: docker.io
    repository: bitnami/minideb
    tag: buster
    pullPolicy: Always
securityContext:
    runAsUser: 0

securityContext:
enabled: true
fsGroup: 1000
runAsUser: 1000

serviceAccount:
enabled: true

psp:
create: true

rbac:
create: true

replication:
enabled: false
user: repl_user
password: repl_password
slaveReplicas: 2
synchronousCommit: "on"
numSynchronousReplicas: 1
applicationName: my_application

postgresqlUsername: home-assistant
postgresqlDatabase: home-assistant
postgresqlDataDir: /bitnami/postgresql/data
extraEnv: []
ldap:
enabled: false
url: ""
server: ""
port: ""
prefix: ""
suffix: ""
baseDN: ""
bindDN: ""
bind_password:
search_attr: ""
search_filter: ""
scheme: ""
tls: false
service:
type: ClusterIP
port: 5432
annotations: {}
shmVolume:
enabled: true
chmod:
    enabled: true
persistence:
enabled: true
existingClaim: home-assistant-postgres

updateStrategy:
type: RollingUpdate

master:
nodeSelector: {}
affinity: {}
tolerations: []
labels: {}
annotations: {}
podLabels: {}
podAnnotations: {}
priorityClassName: ""
extraVolumeMounts: []
extraVolumes: []
sidecars: []

service: {}

slave:
nodeSelector: {}
affinity: {}
tolerations: []
labels: {}
annotations: {}
podLabels: {}
podAnnotations: {}
priorityClassName: ""
extraInitContainers: []
extraVolumeMounts: []
extraVolumes: []
sidecars: []

service: {}

resources:
requests:
    memory: 256Mi
    cpu: 250m

commonAnnotiations: {}

networkPolicy:
enabled: false

allowExternal: true

explicitNamespacesSelector: {}

livenessProbe:
enabled: true
initialDelaySeconds: 30
periodSeconds: 10
timeoutSeconds: 5
failureThreshold: 6
successThreshold: 1

readinessProbe:
enabled: true
initialDelaySeconds: 5
periodSeconds: 10
timeoutSeconds: 5
failureThreshold: 6
successThreshold: 1

metrics:
enabled: true
service:
    type: ClusterIP
    annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
    loadBalancerIP:
serviceMonitor:
    enabled: true
    additionalLabels: {}
prometheusRule:
    enabled: false
    additionalLabels: {}
    namespace: ""
    rules: []

image:
    registry: docker.io
    repository: bitnami/postgres-exporter
    tag: 0.8.0-debian-10-r106
    pullPolicy: IfNotPresent
securityContext:
    enabled: false
    runAsUser: 1000
livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
```

You can see my many attempts to get this to work in the commits of this PR - https://github.com/LukeChannings/kube-config/pull/22.

I tried both [`existingSecret`](https://github.com/LukeChannings/kube-config/pull/22/commits/627d7edb93ac71e13a4f7a69f14cadbd5322974e) and [`global.postgres.existingSecret`](https://github.com/LukeChannings/kube-config/pull/22/commits/a8a8caa3a6f213bd3d4c85b9fe9b927bd81e5927)
