### ISSUE TITLE
[bitnami/kafka] add support for helm parameter maps for extraConfig

### ISSUE THREAD

**Issue by rubenvw-ngdata** [bitnami/charts#25646]
### Name and Version

bitnami/kafka 28.1.1

### What is the problem this feature will solve?

With the migration to Kafka 3.5, an `extraConfig` parameter was added to the chart.
We regret that this is just a text value instead of a helm parameter map.
This choice blocks the overloading of a certain setting via additional values.yaml layers. 
With the current implementation, you need to duplicate all `extraConfig` if you want to change a single parameter in it.

As an example, instead of this
```yaml
extraConfig: |
  max.message.bytes = 1048576
  offsets.topic.replication.factor = 3
  default.replication.factor = 3
  delete.topic.enable = true
  auto.create.topics.enable = false
```
we would prefer to have
```yaml
extraConfig:
  max.message.bytes: 1048576
  offsets.topic.replication.factor: 3
  default.replication.factor: 3
  delete.topic.enable: true
  auto.create.topics.enable: false
```
to allow overloading.

### What is the feature you are proposing to solve the problem?

helm parameter maps to allow overloading the extraConfig.
