### ISSUE TITLE
SeaweedFS: Support other filer-storages then MariaDB

### ISSUE THREAD

**Issue by gtudan** [bitnami/charts#25642]
### Name and Version

bitnami/seaweedfs 0.1.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

* configure the chart with mariaDB.enabled: false
* configure an alternative storage using filer.config

### Are you using any custom parameters or values?

```yaml
  mariadb:
    enabled: false

  filer:
    config: |
      [redis2]
      enabled = true
      address = "redis:6379"
``` 

### What is the expected behavior?

It launches the filer and uses the configured persistence

### What do you see instead?

It will still launch the wait-for-db as init-container that tries to connect to the mariadb.
This container should only start if mariaDb is enabled (either via the chart, or an external db)
