### ISSUE TITLE
Username or password cannot contains char '.' 

### ISSUE THREAD

**Issue by yeahfo** [bitnami/charts#25652]
### Name and Version

bitnami/rabbitmq 14.1.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Username or password cannot contains char '.' 

### What do you see instead?

My yaml helmfile
```yaml
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: test-rabbitmq
    chart: bitnami/rabbitmq
    version: 14.1.2
    values:
      - image:
          registry: registry-1.docker.io
      - auth:
          username: rabbit.user
          password: rabbit.pass
      - extraEnvVars:
          - name: RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS
            value: 'true'
      - persistence:
          enabled: false
```

```shell
$ kubectl describe po test-rabbitmq-0 
......................
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  55s   default-scheduler  Successfully assigned default/test-rabbitmq-0 to worker230
  Normal   Pulled     50s   kubelet            Container image "registry-1.docker.io/bitnami/rabbitmq:3.13.2-debian-12-r0" already present on machine
  Normal   Created    50s   kubelet            Created container prepare-plugins-dir
  Normal   Started    49s   kubelet            Started container prepare-plugins-dir
  Normal   Pulled     46s   kubelet            Container image "registry-1.docker.io/bitnami/rabbitmq:3.13.2-debian-12-r0" already present on machine
  Normal   Created    46s   kubelet            Created container rabbitmq
  Normal   Started    46s   kubelet            Started container rabbitmq
  Warning  Unhealthy  24s   kubelet            Readiness probe failed:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 15672 after 0 ms: Couldn't connect to server
```

```shell
$ kubectl exec -i test-rabbitmq-0 -- curl -f --user rabbit.user:rabbit.pass 127.0.0.1:15672/api/health/checks/local-alarms

Defaulted container "rabbitmq" out of: rabbitmq, prepare-plugins-dir (init)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 15672 after 1 ms: Couldn't connect to server
command terminated with exit code 7
```
