### ISSUE TITLE
[bitnami/mongodb] error converting YAML to JSON: yaml: line 58: block sequence entries are not allowed in this context

### ISSUE THREAD

**Issue by psycotrompus** [bitnami/charts#25682]
### Name and Version

bitnami/mongodb 15.3.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Local KIND Cluster in Windows 11
2. values.yaml file:
```
architecture: standalone
useStatefulSet: true
auth:
  enabled: false
  rootUser: admin
  rootPassword: Passw0rd
persistence:
  enabled: true
  size: 2Gi
volumePermissions:
  enabled: true
resources:
  requests:
    cpu: 200m
    memory: 250Mi
```
3. Run `helm install mongodb bitnami/mongodb --values=values.yaml`
4. Error:
```
Error: INSTALLATION FAILED: YAML parse error on mongodb/templates/standalone/dep-sts.yaml: error converting YAML to JSON: yaml: line 58: block sequence entries are not allowed in this context
```

### Are you using any custom parameters or values?

```
architecture: standalone
useStatefulSet: true
auth:
  enabled: false
  rootUser: admin
  rootPassword: Passw0rd
persistence:
  enabled: true
  size: 2Gi
volumePermissions:
  enabled: true
resources:
  requests:
    cpu: 200m
    memory: 250Mi
```

### What is the expected behavior?

bitnami/mongodb chart should be installed without any errors.

### What do you see instead?

Error message in command prompt:

```
Error: INSTALLATION FAILED: YAML parse error on mongodb/templates/standalone/dep-sts.yaml: error converting YAML to JSON: yaml: line 58: block sequence entries are not allowed in this context
```
