### ISSUE TITLE
[bitnami/opensearch] chart not installed with pv enabled for dashboard

### ISSUE THREAD

**Issue by brianhong1117** [bitnami/charts#25690]
### Name and Version

bitnami/opensearch:1.0.3

### What architecture are you using?

None

### What steps will reproduce the bug?

1. set `dashboards.persistence.enabled` to _true_
2. install chart
3. shows error while installing

### Are you using any custom parameters or values?

```yaml
 persistence:
    ## @param dashboards.persistence.enabled Enable persistence using Persistent Volume Claims
    ##
    enabled: true
    ## @param dashboards.persistence.mountPath Path to mount the volume at.
    ##
    mountPath: /bitnami/opensearch-dashboards
    ## @param dashboards.persistence.subPath The subdirectory of the volume to mount to, useful in dev environments and one PV for multiple services
    ##
    subPath: ''
    ## @param dashboards.persistence.storageClass Storage class of backing PVC
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: 'local-volume'
    ## @param dashboards.persistence.annotations Persistent Volume Claim annotations
    ##
    annotations: {}
    ## @param dashboards.persistence.accessModes Persistent Volume Access Modes
    ##
    accessModes:
      - ReadWriteOnce
    ## @param dashboards.persistence.size Size of data volume
    ##
    size: 8Gi
    ## @param dashboards.persistence.existingClaim The name of an existing PVC to use for persistence
    ##
    existingClaim: ''
    ## @param dashboards.persistence.selector Selector to match an existing Persistent Volume for OpenSearch data PVC
    ## If set, the PVC can't have a PV dynamically provisioned for it
    ## E.g.
    ## selector:
    ##   matchLabels:
    ##     app: my-app
    ##
    selector: {}
    ## @param dashboards.persistence.dataSource Custom PVC data source
    ##
    dataSource: {}
```

### What is the expected behavior?

should install complete chart with dashboard pv and pvc initialized

### What do you see instead?

```
Release "opensearch" does not exist. Installing it now.
Error: template: opensearch/templates/dashboards/deployment.yaml:200:26: executing "opensearch/templates/dashboards/deployment.yaml" at <include "opensearch.dashboards.pvc" .>: error calling include: template: no template "opensearch.dashboards.pvc" associated with template "gotpl"
```
