### ISSUE TITLE
[bitnami/rabbitmq] global.storageClass and persistence.storageClass do the same

### ISSUE THREAD

**Issue by PhoneixS** [bitnami/charts#2571]
**Which chart**:
Bitnami/RabbitMQ 6.25.9

**Is your feature request related to a problem? Please describe.**
There are two properties to control the storage class for dynamic provisioning, `global.storageClass` and `persistence.storageClass`, and looking at the templates it seams as they are used in the same exact way which is confusing.

Also, the `persistence.storageClass` mention that it uses alpha but I can't see where it uses alpha version.

**Describe the solution you'd like**
I think one should be deprecated and favor one of them and remove the comment from `persistence.storageClass` about alpha usage. Probably `persistence.storageClass` is the most convenient parameter to let as primary as it's more explicit.

**Describe alternatives you've considered**
Probably this two options are there for compatibility with an old version and although the chart have been updated the comments haven't been updated so maybe the only need is to update the comment about alpha usage.

**Additional context**
I'm relatively new to Helm so I'm not 100% sure that the two options are exactly the same neither what is the backward compatibility of the project so this is why I haven't make a pull request.

**Comment by marcosbc** [comment]
We add `global.storageClass` since there could be multiple types of nodes in a chart (i.e. primary/secondary), and this way we standarize across all Bitnami charts and they support common options (like global.storageClass).

In the RabbitMQ chart specifically there is only one node type though, so it may not make sense at first. However, the option is supported in all (or most) other charts, so we believe it adds a lot of value to do it like that, even if it has the exact same functionality as another parameter with another name.

Note that global.storageClass > persistence.storageClass, but unless you set both you should not find any issue.

**Comment by PhoneixS** [comment]
It make sense to do it that way and having two parameters for the same thing.

What about the "alpha" in the documentation of `persistence.storageClass`?

**Comment by marcosbc** [comment]
I guess that is outdated and can be removed, let me check further.

**Comment by marcosbc** [comment]
After more checking, it looks like some of our charts really still depend on the alpha storageClass property, i.e. Node:

```
volume.alpha.kubernetes.io/storage-class: {{ ternary "default" (include "node.storageClass" .) (empty (include "node.storageClass" .)) }}
```

I've created an internal task for removing this annotation and update the READMEs so we stop referring to them as being 'alpha'. I'm marking this case as on-hold until it is solved.

**Comment by JustDoItSascha** [comment]
I'm trying to use the node chart and setting the persistence.storageClass Property, but I get the error: Error: YAML parse error on node/templates/pvc.yaml: error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context.

Does this error come from the topic discussed here? Or is it something else?

**Comment by marcosbc** [comment]
@JustDoItSascha What command is it you are executing? It works for us:

```
helm install mynode --set persistence.storageClass=AWSElasticBlockStore bitnami/node
```

**Comment by JustDoItSascha** [comment]
I tried installing it via Lens App. The chart used was 11.4.25, this was the full values spec:

```
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName
#   storageClass: myStorageClass

## Bitnami node image version
## ref: https://hub.docker.com/r/bitnami/node/tags/
##
image:
  registry: docker.io
  repository: bitnami/node
  tag: 10.21.0-debian-10-r18
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

## String to partially override node.fullname template (will maintain the release name)
##
# nameOverride:

## String to fully override node.fullname template
##
# fullnameOverride:

## Init containers parameters:
## volumePermissions: Change the owner and group of the persistent volume mountpoint to runAsUser:fsGroup values from the securityContext section.
##
volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/minideb
    tag: buster
    pullPolicy: Always
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName
  ## Init container' resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits: {}
    #   cpu: 100m
    #   memory: 128Mi
    requests: {}
    #   cpu: 100m
    #   memory: 128Mi

## Bitnami Git image version
## ref: https://hub.docker.com/r/bitnami/git/tags/
##
git:
  registry: docker.io
  repository: bitnami/git
  tag: 2.27.0-debian-10-r17
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

## Enable to download app from external git repository.
## Disable it if your docker image already includes your application at /app
##
getAppFromExternalRepository: true

## Git repository http/https
##
repository: https://github.com/bitnami/sample-mean.git
## Git repository revision to checkout
##
revision: master

## Specify the number of replicas for the application
##
replicas: 1

## Specify the port where your application will be running
##
applicationPort: 3000

## Define custom environment variables to pass to the image here
##
extraEnv: {}

## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Node labels for pod assignment. Evaluated as a template.
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for pod assignment. Evaluated as a template.
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: {}

## Pod Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001

## Node conatiners' resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits: {}
  #   cpu: 100m
  #   memory: 128Mi
  requests: {}
  #   cpu: 100m
  #   memory: 128Mi

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  path: /app/data
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  storageClass: nfs
  accessMode: ReadWriteOnce
  size: 1Gi

## Service paramaters
##
service:
  ## Service type
  ##
  type: ClusterIP
  ## HTTP Port
  ##
  port: 80
  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  # nodePort:
  ## Set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  # loadBalancerIP:
  ## Provide any additional annotations which may be required. This can be used to
  ## set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  annotations: {}

## Ingress paramaters
##
ingress:
  ## Set to true to enable ingress record generation
  ##
  enabled: false

  ## The list of hostnames to be covered with this ingress record.
  ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
  hosts:
    - name: node.local

      ## Set this to true in order to enable TLS on the ingress record
      ##
      tls: false

      ## Set this to true in order to add the corresponding annotations for cert-manager
      ##
      certManager: false

      ## If TLS is set to true, you must declare what secret will store the key/certificate for TLS
      ##
      tlsSecret: node.local-tls

      ## Ingress annotations done as key:value pairs
      ## For a full list of possible ingress annotations, please see
      ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
      ##
      ## If certManager is set to true, annotation kubernetes.io/tls-acme: "true" will automatically be set
      annotations:
      #  kubernetes.io/ingress.class: nginx

  secrets:
  ## If you're providing your own certificates, please use this to add the certificates as secrets
  ## key and certificate should start with -----BEGIN CERTIFICATE----- or
  ## -----BEGIN RSA PRIVATE KEY-----
  ##
  ## name should line up with a tlsSecret set further up
  ## If you're using cert-manager, this is unneeded, as it will create the secret for you if it is not set
  ##
  ## It is also possible to create and manage the certificates outside of this helm chart
  ## Please see README.md for more information
  # - name: node.local-tls
  #   key:
  #   certificate:

## MongoDB chart configuration
## ref: https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml
##
mongodb:
  ## Whether to deploy a mongodb server to satisfy the applications database requirements.
  ## To use an external database set this to false and configure the externaldb parameters
  install: false
  ## MongoDB custom user and database
  ## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#creating-a-user-and-database-on-first-run
  ##
  mongodbUsername: user
  mongodbDatabase: test_db
  mongodbPassword: secret_password

## Provision an external database (Only if mongodb.install is false)
## You can:
##    1) Pass an already existing Secret with your database credentials
##    2) Pass an already existing ServiceInstance name and specify the service catalog broker to automatically create a ServiceBinding for your application.
##
externaldb:
  ## Set to true if your external database has ssl enabled
  ##
  ssl: false
  ### You can use an existing secret containing your database credentials
  ### Please refer to the respective section in the README to know the details about this secret.
  ##
  secretName:
  ## Only if using Kubernetes Service Catalog you can specify the kind of broker used. Available options are osba|gce|aws
  ##
  type: osba
  ## If you provide the serviceInstanceName, the chart will create a ServiceBinding for that ServiceInstance
  ##
  broker:
    serviceInstanceName:
```
