### ISSUE TITLE
[bitnami/minio]Console web ui creating Access Keys failed, this causes the pod to restarted.

### ISSUE THREAD

**Issue by yeahfo** [bitnami/charts#25882]
### Name and Version

bitnami/minio 14.4.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

My helmfile yaml
```yaml
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: minio
    chart: bitnami/minio
    version: 14.4.2
    values:
      - service:
          type: NodePort
          nodePorts:
            api: "30900"
            console: "30901"
      - auth:
          rootUser: admin
          rootPassword: adminpwd
      - persistence:
          enabled: false
```

- Login to console web ui.
- Click the `Access Keys` menu.
- Create access key.
- Continuing to refresh the browser after a failed creation will cause the pod to restart continuously.

### What do you see instead?

Error and `Access key`  is not created.
