### ISSUE TITLE
Valkey: Metrics exporter uses wrong environment variables

### ISSUE THREAD

**Issue by gtudan** [bitnami/charts#25923]
### Name and Version

bitnami/valkey:0.1.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install the chart as usual
2. make sure to enable authentication for Valkey
3. enable the metrics exporter

### Are you using any custom parameters or values?

```yaml
valkey:
  metrics:
    enabled: true
  auth:
    enabled: true
```

### What is the expected behavior?

Metrics exporter is able to connect to the redis-master

### What do you see instead?

Metrics exporter get authentication errors

### Additional information

The exporter is still the original redis-exporter. But the configuration properties have been renamed to VALKEY_*, especially `VALKEY_PASSWORD`. They should still be `REDIS_*`

The metrics exporter works if I manually set the property:

```yaml
  metrics:
    enabled: true
    extraEnvVars:
      - name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: redis-secret
            key: REDIS
```
