### ISSUE TITLE
[bitnami/redis] persistence.labels are ignored

### ISSUE THREAD

**Issue by jbertozzi** [bitnami/charts#25942]
### Name and Version

bitnami/redis 19.3.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create a values file:

```yaml
commonLabels:
  blah: blah
master:
  persistence:
    labels:
     pvc-backup: enabled
sentinel:
  persistence:
    labels:
      pvc-backup: enabled
replica:
  persistence:
    labels:
      pvc-backup: enabled
```

2. Generate the manifests:

`helm template redis bitnami/redis --version 19.3.2 -f /tmp/redis-values.yaml   > /tmp/r.yaml`

3. Look in the statefulset the volumeClaimTemplates labels:

```yaml
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: redis-data
        labels:
          app.kubernetes.io/instance: redis
          app.kubernetes.io/name: redis
          app.kubernetes.io/component: replica
```

### Are you using any custom parameters or values?

```yaml
commonLabels:
  blah: blah
master:
  persistence:
    labels:
     pvc-backup: enabled
sentinel:
  persistence:
    labels:
      pvc-backup: enabled
replica:
  persistence:
    labels:
      pvc-backup: enabled
```

### What is the expected behavior?

yaml generated from Source template `redis/templates/{master,replicas,sentinel}/application.yaml` should contain labels defined in .Values.master.persistence.labels in .spec.containers[0].volumeClaimTemplates[0].metadata.labels.

### What do you see instead?

```
app.kubernetes.io/instance: redis
app.kubernetes.io/name: redis
app.kubernetes.io/component: replica
```

### Additional information

I don't think the call to `common.labels.matchLabels` is legit for the volumeClaimTemplates. Furthermore, this is not used in other charts (mongodb, postgresql, ...). 

I would be happy to submit a PR replacing this included statement.
