### ISSUE TITLE
Typo in postgresql-ha/templates/NOTES.txt causes deployment failure

### ISSUE THREAD

**Issue by kraihn** [bitnami/charts#25993]
### Name and Version

bitnami/postgresql-ha 13.0.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. A Kubernetes cluster running FluxCD v2.1.2
2. Deploying a FluxCD CRD for HelmRelease
3. Bitnami postgresql-ha chart values
4. There is an error parsing the Helm Chart:
```
reconciliation failed: Helm upgrade failed: template: postgresql-ha/templates/NOTES.txt:60:63: executing "postgresql-ha/templates/NOTES.txt" at <include "postgresql-ha.pgppol" .>: error calling include: template: no template "postgresql-ha.pgppol" associated with template "gotpl"
```

### Are you using any custom parameters or values?

```yaml
persistence:
    storageClass: secret
postgresql:
    password: secret
    repmgrPassword: secret
pgpool:
    adminPassword: secret
    customUsersSecret: secret
metrics:
    enabled
```

### What is the expected behavior?

The Helm Chart should deploy successfully.

### What do you see instead?
```
reconciliation failed: Helm upgrade failed: template: postgresql-ha/templates/NOTES.txt:60:63: executing "postgresql-ha/templates/NOTES.txt" at <include "postgresql-ha.pgppol" .>: error calling include: template: no template "postgresql-ha.pgppol" associated with template "gotpl"
```
### Additional information

It appears a type was introduced in the chart version 13.0.0 upgrade that introduced network policies.

[https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha/templates/NOTES.txt](https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha/templates/NOTES.txt)

The type is on line 60
`postgresql-ha.pgppol` should be `postgresql-ha.pgpool`
