### ISSUE TITLE
[bitnami/rabbitmq] extraPorts are not being passed to the headless service

### ISSUE THREAD

**Issue by aqeelat** [bitnami/charts#26102]
### Name and Version

bitnami/rabbitmq 14.1.4

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Install rabbitmq with extra ports.

### Are you using any custom parameters or values?

```yaml
extraContainerPorts:
    - name: stream
      containerPort: 5552
service:
    extraPorts:
        - name: stream
          port: 5552
          targetPort: stream
```

### What is the expected behavior?

Ports in the service `rabbitmq-headless` mirror the ones in `rabbitmq`

### What do you see instead?

The extra ports are not being mapped.

### Additional information

This can be fixed by adding this snippet to the headless service
```go
    {{- if .Values.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
```
