### ISSUE TITLE
Wrong variables definition in the skipper's ConfigMap

### ISSUE THREAD

**Issue by vicSenior** [bitnami/charts#26169]
### Name and Version

bitnami/spring-cloud-dataflow 26.7.1

### What architecture are you using?

amd64

### **Steps to reproduce:**
Use of the `helm template` command to generate a YAML file to inspect:
```console
# Variables:
HELM_RELEASE_NAME="test-instance-scdf-01"
K8S_NAMESPACE="scdf-01"

# Command:
$ helm template ${HELM_RELEASE_NAME} ./ --namespace ${K8S_NAMESPACE} -f my_values_01.yaml > test-instance-scdf-01_deployment.yaml --debug
install.go:231: [debug] CHART PATH: /home/victor/scdf/spring-cloud-dataflow
coalesce.go:286: warning: cannot overwrite table with non table for mariadb.metrics.extraVolumeMounts (map[primary:[] secondary:[]])
``` 
Inspect output YAML file `test-instance-scdf-01_deployment.yaml` for object skipper's ConfigMap:
```yaml
# Source: spring-cloud-dataflow/templates/skipper/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-instance-scdf-01-spring-cloud-dataflow-skipper
  labels:
    app.kubernetes.io/instance: test-instance-scdf-01
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: spring-cloud-dataflow
    app.kubernetes.io/version: 2.11.2
    helm.sh/chart: spring-cloud-dataflow-26.7.1
    app.kubernetes.io/component: skipper
  namespace: "scdf-01"
data:
  application.yaml: |-
    spring:
      cloud:
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  default:
                    environmentVariables:
                      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=${test-instance-scdf-01_KAFKA_SERVICE_HOST}:${test-instance-scdf-01_KAFKA_SERVICE_PORT}
                      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=${test-instance-scdf-01_ZOOKEEPER_SERVICE_HOST}:${test-instance-scdf-01_ZOOKEEPER_SERVICE_PORT}
                    readinessProbeDelay: 120
                    livenessProbeDelay: 90
                    podSecurityContext:
                      runAsUser: 1001
                    entryPointStyle: exec
                    imagePullPolicy: IfNotPresent
``` 
You can see that SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS has declared with the wrong value.
Same for SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES.

In fact, the environment variables in the skipper container are different:
```console
$ kubectl -n scdf-01 exec --stdin --tty scdf-01-spring-cloud-dataflow-skipper-86577f88b6-zhkkf -c skipper -- /bin/bash
$ env | grep -i _KAFKA_SERVICE_

TEST_INSTANCE_SCDF_01_KAFKA_SERVICE_PORT=9092
TEST_INSTANCE_SCDF_01_KAFKA_SERVICE_PORT_TCP_CLIENT=9092
TEST_INSTANCE_SCDF_01_KAFKA_SERVICE_HOST=10.108.228.239
``` 
So, the env. variables are in Uppercase and all special chars have been substituted with an underscore ("_").

${test-instance-scdf-01_KAFKA_SERVICE_HOST} not exist
${test-instance-scdf-01_KAFKA_SERVICE_PORT} not exist
Same for ZooKeeper:
${test-instance-scdf-01_ZOOKEEPER_SERVICE_HOST} not exist
${test-instance-scdf-01_ZOOKEEPER_SERVICE_PORT} not exist

### **Proposal for solving the problem**
Modify file `spring-cloud-dataflow/templates/skipper/configmap.yaml` in line 59 and 60:
- As is:
```javascript
- SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=${{ printf "{" }}{{ .Release.Name }}_KAFKA_SERVICE_HOST}:${{ printf "{" }}{{ .Release.Name }}_KAFKA_SERVICE_PORT}
- SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=${{ printf "{" }}{{ .Release.Name }}_ZOOKEEPER_SERVICE_HOST}:${{ printf "{" }}{{ .Release.Name }}_ZOOKEEPER_SERVICE_PORT}
``` 
- To be:
```javascript
- SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=${{ printf "{" }}{{ regexReplaceAll "\\W+" (upper .Release.Name) "_" }}_KAFKA_SERVICE_HOST}:${{ printf "{" }}{{ regexReplaceAll "\\W+" (upper .Release.Name) "_" }}_KAFKA_SERVICE_PORT}
- SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=${{ printf "{" }}{{ regexReplaceAll "\\W+" (upper .Release.Name) "_" }}_ZOOKEEPER_SERVICE_HOST}:${{ printf "{" }}{{ regexReplaceAll "\\W+" (upper .Release.Name) "_" }}_ZOOKEEPER_SERVICE_PORT}
``` 

### What do you see instead?

- SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=**${test-instance-scdf-01_KAFKA_SERVICE_HOST}**:**${test-instance-scdf-01_KAFKA_SERVICE_PORT}**
- SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=**${test-instance-scdf-01_ZOOKEEPER_SERVICE_HOST**}:**${test-instance-scdf-01_ZOOKEEPER_SERVICE_PORT}**

### **Release versions:**
I'm using Helm version 3.13.1, for Kubernetes environment 1.23.8.
SCDF version 2.11.2, with Helm chart version 26.7.1. 
```console
$ helm version
version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.20.8"}
``` 
```console
$ kubectl version --output=json
{
  "serverVersion": {
    "major": "1",
    "minor": "23",
    "gitVersion": "v1.23.8+vmware.3",
    "gitCommit": "53e803785668c31b8fcb41fc3607f3fdc3c87465",
    "gitTreeState": "clean",
    "buildDate": "2022-11-03T17:16:51Z",
    "goVersion": "go1.17.11",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
``` 
```console
$ cat ./spring-cloud-dataflow/Chart.yaml | grep 'appVersion:'
appVersion: 2.11.2

$ cat ./spring-cloud-dataflow/Chart.yaml | tail -n 1
version: 26.7.1
```
