### ISSUE TITLE
KC_PROXY deprecated, use proxy-headers

### ISSUE THREAD

**Issue by Loucool111** [bitnami/charts#26175]
### Name and Version

bitnami/keycloack 21.2.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy helm chart with the following values:

```yaml
replicaCount: 1
proxy: "edge"
production: true

cache:
  enabled: true
  stackName: kubernetes

service:
  type: NodePort

ingress:
  enabled: true

  path: "/*"
  hostname: "[REDACTED]"

  ingressClassName: alb

postgresql:
  enabled: false

externalDatabase:
  [REDACTED]
``` 

### What is the expected behavior?

normal startup

### What do you see instead?

Logs about deprecated KC_PROXY config
```
2024-05-20 22:56:14,193 WARN  [org.key.qua.run.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed in a future release:
	- proxy: Use proxy-headers.
Consult the Release Notes for details.
```
### Additional information

When using proxy: edge, what should be the config?
