### ISSUE TITLE
TLS for Redis

### ISSUE THREAD

**Issue by asgoel** [bitnami/charts#2622]
**Which chart**:
redis 10.6.14

**Is your feature request related to a problem? Please describe.**
Now that Redis 6.0 supports TLS, would it be possible to have native support in the chart for configuring TLS?

Generally I would use the `master.configmap` directive, but I also need to be able to pass in additional secrets for the TLS certs. Is there a way I can do that?

**Describe the solution you'd like**
An easy way to set up TLS for redis using helm values, with the option to provide a secret for the TLS certs.

**Comment by carrodher** [comment]
Hi, thanks for letting us know, it seems an interesting feature that we already support in other charts.
As the change is not trivial because it requires changes in the container image and in the chart, I just created an internal task in our backlog. We will incorporate it into our work process according to other tasks and priorities. In order to avoid stale bot closing the issue, I will set the `on-hold` label and we will update this thread once we implemented the required changes.

Thanks for your suggestions and for using the Bitnami charts.

**Comment by asgoel** [comment]
@carrodher thanks! is there any projected timeline on when this will get done?

Meanwhile, is there any way you know of that I could get this working with the current chart? The only thing missing is the ability to mount my own secrets into the container (which I would need to do for the certs). Is this possible?

**Comment by carrodher** [comment]
Hi, we are already working on it, so probably it will be released during the next week. Now it is possible to mount secrets but only for a password, we need to implement the logic to support other secrets. Anyway, PRs are welcome, if you found a way on your side to make it works don't hesitate to create a PR, our team will be happy to review it.

**Comment by rafariossaa** [comment]
Hi @asgoel ,
  We really appreciate any feedback provided.

Thanks forehand.

**Comment by tbnguyen1407** [comment]
Hello, there is an error with if/else in this line causing the certs not mounted on slave-statefulset:

https://github.com/bitnami/charts/blob/365514ff6a116dacd30b5d5c3c144f788b799930/bitnami/redis/templates/redis-slave-statefulset.yaml#L481

**Comment by joancafom** [comment]
Hi @tbnguyen1407 

Thanks so much for reporting! PR #2852 is going to be merged shortly and should be able to fix this problem 😄.

**Comment by thomas-riccardi** [comment]
Hello, using redis chart 10.7.5 with `tls.authClients=false` the probes (readiness/health) still send client certificates, using server key/cert.
Somehow in my case it doesn't work:
- server logs `1:M 25 Jun 2020 12:55:16.247 # Error accepting a client connection: error:1417C086:SSL routines:tls_process_client_certificate:certificate verify failed` in logs, no more info with `loglevel debug`, but that's an upstream redis issue..)
- server closes connexion
debugging with `openssl s_client -connect localhost:6379 -state -CAfile ca.crt -cert tls.crt -key tls.key`:
```
SSL3 alert read:fatal:unsupported certificate
140155281985984:error:14094413:SSL routines:ssl3_read_bytes:sslv3 alert unsupported certificate:../ssl/record/rec_layer_s3.c:1528:SSL alert number 43
```

I'm not familiar enough with TLS certificates to understand why redis-server rejects the client certificate, but in any case when I ask to disable client authentication via `tls.authClients=false` I would expect the redis helm chart to *not* send client certificates in its probes (and anywhere else if there are any).


(Also, the probe fails with a strange message: `Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.`, it seems https://github.com/bitnami/charts/blob/8f49e5254b590eb262332110e58b6925b9da8e84/bitnami/redis/templates/health-configmap.yaml#L19 should be changed to apply also for redis 6)

**Comment by thomas-riccardi** [comment]
(for more details:
I use https://cert-manager.io/ to:
- first create a selfsigned Issuer
- used to generate a Certificate `ca-root` (with `isCA: true`)
- used to bootstrap a `ca` Issuer
- and finally create a Certificate `redis` from the `ca` Issuer, which creates a `redis-tls` tls Secret that I pass to redis helm chart via `tls.certificatesSecret`.

I don't understand why redis-server rejects the client certificate: testing with `openssl s_server` and `openssl s_client` it works great:
```
# first, verify what `cert-manager` created is valid:
$ openssl verify -verbose -CAfile ca.crt tls.crt
tls.crt: OK

# then test client certificate validation
$ openssl s_server -accept 12345 -CAfile ca.crt -cert tls.crt -key tls.key -Verify 1 -state
$ openssl s_client -connect localhost:12345 -state -CAfile ca.crt -key tls.key
```

`cert-manager` scenario:
```yaml
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ca-root
spec:
  secretName: ca-key-pair
  isCA: true
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  commonName: local-selfsigned-root-ca
  organization:
  - Foo

---

apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: ca
spec:
  ca:
    secretName: ca-key-pair

---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: redis
spec:
  secretName: redis-tls
  issuerRef:
    name: ca
    kind: ClusterIssuer
  commonName: redis
  organization:
  - Foo
```

install redis 10.7.5 helm release named `redis`(same as commonName, service name)
`values.yaml`:
```yaml
tls:
  enabled: true
  authClients: false
  certificatesSecret: redis-tls
  certFilename: tls.crt
  certKeyFilename: tls.key
  certCAFilename: ca.crt
```
)
