### ISSUE TITLE
[bitnami/wordpress] Chart (22.3.0) deployment fails due to livenessProbe handler conflict

### ISSUE THREAD

**Issue by iamcryptoki** [bitnami/charts#26319]
### Name and Version

bitnami/wordpress chart Helm 22.3.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Enable livenessProbe with httpGet handler on WordPress containers.
2. Install or upgrade WordPress chart to 22.3.0.

### Are you using any custom parameters or values?

```yml
livenessProbe:
  httpGet:
    httpHeaders:
     - name: X-Forwarded-Proto
        value: https
    port: http
    scheme: HTTP
```

### What do you see instead?

The chart adds tcpSocket handler in addition to preconfigured httpGet handler.

![error_tcpsocket_handler_1](https://github.com/bitnami/charts/assets/22425397/cbfbffc5-ae3f-45ae-856a-41aeda5ac4a4)

<img width="1154" alt="error_tcpsocket_handler_2" src="https://github.com/bitnami/charts/assets/22425397/4a838490-e8f8-4970-99d6-f473efeadf90">
