### ISSUE TITLE
NGINX Chart 17.1.0 Deployment fails with HTTP 400 / bad request on liveness/readiness probe

### ISSUE THREAD

**Issue by cnocula-peg** [bitnami/charts#26326]
### Name and Version

bitnami/nginx-17.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Since the upgrade of our NGINX chart to nginx-17.1.0, our deployments have failed due to a bad request response on the readiness probe:

Changes introduced:
Old: (nginx-17.0.1)
```yaml
          httpGet:
            path: /
            port: http
            scheme: HTTP
```

New: (nginx-17.1.0)
```yaml
         tcpSocket:
         port: http
```

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Successful rollout deployment with the HELM chart version 17.1.0

### What do you see instead?

Startup failure and Helm rollback due to 400 / Bad Request responses

```
nginx 10:50:51.51 INFO  ==> ** NGINX setup finished! **

nginx 10:50:51.52 INFO  ==> ** Starting NGINX **
2024/05/22 10:50:51 [warn] 1#1: conflicting server name "" on 0.0.0.0:8443, ignored
nginx: [warn] conflicting server name "" on 0.0.0.0:8443, ignored
10.0.3.114 - - [22/May/2024:10:50:56 +0000] "GET / HTTP/1.1" 400 248 "-" "kube-probe/1.28+" "-"
10.0.3.114 - - [22/May/2024:10:51:01 +0000] "GET / HTTP/1.1" 400 248 "-" "kube-probe/1.28+" "-"
10.0.3.114 - - [22/May/2024:10:51:06 +0000] "GET / HTTP/1.1" 400 248 "-" "kube-probe/1.28+" "-"
10.0.3.114 - - [22/May/2024:10:51:11 +0000] "GET / HTTP/1.1" 400 248 "-" "kube-probe/1.28+" "-"
```

### Additional information

We are running on AWS EKS 1.28.

**Comment by juan131** [comment]
Introduced at https://github.com/bitnami/charts/pull/25969

**Comment by juan131** [comment]
Hi @cnocula-peg 

Are you using a custom server block? Does your solution returns a non-200 HTTP code when you accessing to `/`?

**Comment by cnocula-peg** [comment]
Hi @juan131,
we are not doing anything special. Plain Helm installation into an AWS EKS cluster:

```
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm search repo bitnami
          helm upgrade "docs-${{ env.product }}-my-app" bitnami/nginx --install --atomic --timeout 3m --create-namespace --namespace "docs-${{ env.product }}-my-app" \
          --set image.registry=${{ env.account }}.dkr.ecr.eu-central-1.amazonaws.com \
          --set image.repository=docs-${{ env.product }}-my-app-${{ env.environment }} \
          --set image.tag=${{ env.imageVersion }} \
          --values docs/values.yaml \
          --values docs/${{ env.environment }}/values.yaml
```

The values contain mostly Ingress annotations and service port definitions.

The server block is also pretty much default:

```
serverBlock: |-
  server {
    listen       8443 ssl;

    ssl_certificate      bitnami/certs/server.crt;
    ssl_certificate_key  bitnami/certs/server.key;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

    location / {
      root   html;
      index  index.html index.htm;
    }
  }
```

I had to pin the helm upgrade to `--version 17.0.2` to make our deployment work again.

**Comment by cnocula-peg** [comment]
@dgomezleon unfortunately your fix still does not work for me with chart version 17.2.0.

During the `helm upgrade` call, I now get a warning:

`W0523 10:46:11.468665   16278 warnings.go:70] unknown field "spec.template.spec.containers[0].readinessProbe.path"`

And I am still getting the 400 / Bad Request on the readiness probe:

```
10.0.2.157 - - [23/May/2024:10:46:21 +0000] "GET / HTTP/1.1" 400 248 "-" "kube-probe/1.28+" "-"
10.0.2.157 - - [23/May/2024:10:46:26 +0000] "GET / HTTP/1.1" 400 248 "-" "kube-probe/1.28+" "-"
10.0.2.157 - - [23/May/2024:10:46:31 +0000] "GET / HTTP/1.1" 400 248 "-" "kube-probe/1.28+" "-"
10.0.2.157 - - [23/May/2024:10:46:36 +0000] "GET / HTTP/1.1" 400 248 "-" "kube-probe/1.28+" "-"
10.0.2.157 - - [23/May/2024:10:46:41 +0000] "GET / HTTP/1.1" 400 248 "-" "kube-probe/1.28+" "-"
10.0.2.157 - - [23/May/2024:10:46:46 +0000] "GET / HTTP/1.1" 400 248 "-" "kube-probe/1.28+" "-"
10.0.2.157 - - [23/May/2024:10:46:51 +0000] "GET / HTTP/1.1" 400 248 "-" "kube-probe/1.28+" "-"
10.0.2.157 - - [23/May/2024:10:46:56 +0000] "GET / HTTP/1.1" 400 248 "-" "kube-probe/1.28+" "-"
```

Rendered output:
```
        app.kubernetes.io/version: 1.26.0
        helm.sh/chart: nginx-17.2.0
...
        livenessProbe:
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 5
        name: nginx
        ports:
        - containerPort: 8443
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
```

P.S.
By the way, I also get an (unrelated) warning in a different place:
`W0523 10:46:11.468694   16278 warnings.go:70] spec.template.spec.containers[0].ports[1]: duplicate port definition with spec.template.spec.containers[0].ports[0]`

**Comment by juan131** [comment]
@cnocula-peg thanks for reporting it! This PR should address the issue you're facing right now: https://github.com/bitnami/charts/pull/26394

Regarding the container ports? Could you share the values you're using ?

**Comment by cnocula-peg** [comment]
These are my service and container section values.
```
service:
  type: NodePort
  ports:
    http: 8443
  targetPort:
    http: 8443

containerPorts:
  http: 8443
```
