### ISSUE TITLE
[bitnami/kube-prometheus] kube-prometheus kubelet.serviceMonitor.relabelings not applying the target_label key into prometheus config

### ISSUE THREAD

**Issue by toporek3112** [bitnami/charts#26343]
### Name and Version

kube-prometheus version 8.17.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Kubernetes v1.28.7
2. bitnami/kube-prometheus helm chart version 8.17.1
3. standart deployment with kubelet exporter enabled
4. under kubelet.serviceMonitor.relabelings tried to configure

```yaml
    relabelings:
      - target_label: cluster
        replacement: ${labelCluster}
```

or

```yaml
    relabelings:
      - target_label: cluster
        action: replace
        replacement: ${labelCluster}
```

but I see prometheus throwing errors saying:

```
couldn't load configuration (--config.file="/etc/prometheus/config_out/prometheus.env.yaml"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: relabel configuration for replace action requires 'target_label' value
```

and after checking the 'target_label' is indeed not present although I specified it. Is this a bug?

### What is the expected behavior?

I would expect to see the target_label key together with the other keys that I specified

### What do you see instead?

Instead I can see only:

```yaml
  - replacement: CLUSTER-XY
```

or 

```
  - action: replace
    replacement: CLUSTER-XY
```

**Comment by juan131** [comment]
Hi @toporek3112 

Does your ServiceMonitor looks like this?

```console
$ helm template kube-prometheus oci://registry-1.docker.io/bitnamicharts/kube-prometheus -f custom-values.yaml -s templates/exporters/kubelet/servicemonitor.yaml
Pulled: registry-1.docker.io/bitnamicharts/kube-prometheus:9.2.1
Digest: sha256:61e0fcee27d9f84a7beb25b33d459eef104ef2e806c180cc7e5b3aad3f610cd4
---
# Source: kube-prometheus/templates/exporters/kubelet/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-prometheus-kubelet
  namespace: "default"
  labels:
    app.kubernetes.io/instance: kube-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/version: 0.74.0
    helm.sh/chart: kube-prometheus-9.2.1
    app.kubernetes.io/component: kubelet
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: kubelet
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: https-metrics
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        serverName: kubernetes
        insecureSkipVerify: true
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      relabelings:
        - action: replace
          replacement: ${labelCluster}
          target_label: cluster
    - port: https-metrics
      scheme: https
      path: /metrics/cadvisor
      honorLabels: true
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        serverName: kubernetes
        insecureSkipVerify: true
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
```

**Comment by toporek3112** [comment]
So I tried applying it again where my values.yaml was:
```
kubelet:
  enabled: true
  namespace: namespace
  serviceMonitor:
    https: true
    interval: ""
    relabelings:
      - action: replace
        replacement: ${labelCluster}
        target_label: cluster
```

and the deployed serviceMonitor yaml was: 
```
    relabelings:
    - action: replace
      replacement: [The actuall value of ${labelCLuster}]
```

I don't understand why the target_label key is missing in the serviceMonitor. What am I doing wrong? Or is it a bug of some sort? Idk if it helps but I'm using terraform to deploy this helm chart and the terraform preview is also showing me the correct config like: 

```
kubelet:
  enabled: true
  namespace: namespace
  serviceMonitor:
    https: true
    interval: ""
    relabelings:
      - action: replace
        replacement: [The actuall value of ${labelCLuster}]
        target_label: cluster
```
