### ISSUE TITLE
valkey sentinel broken

### ISSUE THREAD

**Issue by davhdavh** [bitnami/charts#26363]
### Name and Version

bitnami/valkey 0.20

### What architecture are you using?

amd64

### What steps will reproduce the bug?

https://github.com/bitnami/charts/blob/fd7d3072f8c542f55c1b328870d68db574da9f99/bitnami/valkey/templates/headless-svc.yaml#L29

is same value as 

https://github.com/bitnami/charts/blob/fd7d3072f8c542f55c1b328870d68db574da9f99/bitnami/valkey/templates/headless-svc.yaml#L33

and thus you get this error:

```
failed to create typed patch object (kube-public/redis-valkey-headless; /v1, Kind=Service): .spec.ports: duplicate entries for key [port=26379,protocol="TCP"]
```

### Are you using any custom parameters or values?
```yaml
valkey:
  fullnameOverride: redis-valkey

  sentinel:
    enabled: true
    persistence:
      enabled: false
    nodeSelector:
      kubernetes.io/os: linux

  replica:
    replicaCount: 3
    persistence:
      enabled: false
    nodeSelector:
      kubernetes.io/os: linux

  auth:
    enabled: false
    sentinel: false
```

### What is the expected behavior?

no error

### What do you see instead?

failed to create typed patch object (kube-public/redis-valkey-headless; /v1, Kind=Service): .spec.ports: duplicate entries for key [port=26379,protocol="TCP"]
