### ISSUE TITLE
[bitnami/grafana-loki] loki default configuration is incompatible with appVersion: 3.0.0

### ISSUE THREAD

**Issue by 3deep5me** [bitnami/charts#26373]
### Name and Version

bitnami/grafana-loki 4.2.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Try the `loki.overrideConfiguration` value or use the default configuration which is defined in the values.yaml
2. See the Compactor failing with the error `flag provided but not defined: -boltdb.shipper.compactor.working-directory`
 
### Are you using any custom parameters or values?
```yaml
  loki:
    #see https://grafana.com/docs/loki/latest/configure/ for detailed configuration options
    overrideConfiguration:
      ruler:
        external_url: http://observability-kube-prometh-alertmanager:9093
        alertmanager_url: http://observability-kube-prometh-alertmanager:9093
      storage_config:
        aws:
          bucketnames: loki
          endpoint: observability-minio:9000
          region: .
          access_key_id: ${username}
          secret_access_key: ${password}
          insecure: true
          s3forcepathstyle: true
```

### What is the expected behavior?

A starting compactor.

### What do you see instead?

`flag provided but not defined: -boltdb.shipper.compactor.working-directory`

### Additional information

It seems like there are more problems which are related to the major upgrade and the default configuration.
