### ISSUE TITLE
[bitnami/postgresql-ha] Missing volume certs in postgres-ha chart with tls enabled

### ISSUE THREAD

**Issue by usulkies** [bitnami/charts#26385]
### Name and Version

bitnami/postgres-ha 14.1.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Try creating the chart with tls enabled.
This portion of code:
```yaml
              {{- if .Values.postgresql.tls.enabled }}
              - name: certs
                mountPath: /certs
              {{- end }}
```
In `bitnami/postgresql-ha/templates/backup/cronjob.yaml` requires a volume named certs, but that volume is nowhere to be found.

### What is the expected behavior?

Successful apply using terraform

### What do you see instead?
```
╷
│ Error: 1 error occurred:
│       * CronJob.batch "my-pg-postgresql-ha-postgresql-pgdumpall" is invalid: spec.jobTemplate.spec.template.spec.containers[0].volumeMounts[1].name: Not found: "certs"
│ 
│   with module.mymodule.helm_release.controller_postgres[0],
│   on modules/mymodule/main.tf line 820, in resource "helm_release" "controller_postgres":
│  820: resource "helm_release" "controller_postgres" {
│ 
```
