### ISSUE TITLE
[bitnami/postgresql]: Error on CREAT EXTENSION earthdistance, Needs SUPERUSER

### ISSUE THREAD

**Issue by victorh5** [bitnami/charts#26384]
### Name and Version

bitnami/postgresql:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. In this environment: **docker-compose.yml**

```
version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=testbr
    volumes:
      - test_pg_data:/bitnami/postgresql

volumes:
  test_pg_data:
```

### What is the expected behavior?

The expected behavior was to create the extension.

### What do you see instead?

````
QueryFailedError: permission denied to create extension "earthdistance"
    at PostgresQueryRunner.query (/Users/victorhugomacieldelima/projects/test/test/api/node_modules/typeorm/src/driver/postgres/PostgresQueryRunner.ts:299:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Migration1715181587958.up (/Users/victorhugomacieldelima/projects/test/test/api/src/database/migrations/1715181587958-migration.ts:7:9)
    at async MigrationExecutor.executePendingMigrations (/Users/victorhugomacieldelima/projects/test/test/api/node_modules/src/migration/MigrationExecutor.ts:336:17)
    at async DataSource.runMigrations (/Users/victorhugomacieldelima/projects/test/test/api/node_modules/src/data-source/DataSource.ts:397:13)
    at async Object.handler (/Users/victorhugomacieldelima/projects/test/test/api/node_modules/src/commands/MigrationRunCommand.ts:76:13) {
  query: 'CREATE EXTENSION earthdistance CASCADE',
  parameters: undefined,
  driverError: error: permission denied to create extension "earthdistance"
      at /Users/victorhugomacieldelima/projects/test/test/api/node_modules/pg/lib/client.js:526:17
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/Users/victorhugomacieldelima/projects/teste/test/api/node_modules/typeorm/src/driver/postgres/PostgresQueryRunner.ts:249:25)
      at async Migration1715181587958.up (/Users/victorhugomacieldelima/projects/test/test/api/src/database/migrations/1715181587958-migration.ts:7:9)
      at async MigrationExecutor.executePendingMigrations (/Users/victorhugomacieldelima/projects/test/test/api/node_modules/src/migration/MigrationExecutor.ts:336:17)
      at async DataSource.runMigrations (/Users/victorhugomacieldelima/projects/test/test/api/node_modules/src/data-source/DataSource.ts:397:13)
      at async Object.handler (/Users/victorhugomacieldelima/projects/test/test/api/node_modules/src/commands/MigrationRunCommand.ts:76:13) {
    length: 170,
    severity: 'ERROR',
    code: '42501',
    detail: undefined,
    hint: 'Must be superuser to create this extension.',
````
