### ISSUE TITLE
Grafana Mimir - Error while configuring service monitors using bitnami mimir helm chart

### ISSUE THREAD

**Issue by higp14** [bitnami/charts#26389]
### Name and Version

bitnami/mimir 1.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. I deployed Grafana Mimir in K8 clusters using the Bitnami Helm chart
2. All the pods, STS, service seem to be running as expected with the s3 backend
3. On configuring service monitors, I don't seem to configure path: /metrics under https://artifacthub.io/packages/helm/bitnami/grafana-mimir?modal=template&template=ingester/servicemonitor.yaml

### Are you using any custom parameters or values?

I use values.yaml for customization. Not a lot of changes except for label and annotation and s3 backend
```yaml
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: ""
    annotations:
    labels:
    jobLabel: ""
    honorLabels: false
    interval: ""
    scrapeTimeout: ""
    metricRelabelings: []
    relabelings: []
    selector: {}
```
### What is the expected behavior?

Create a service monitor for mimir

### What do you see instead?
```
│ Error: template: grafana-mimir/templates/store-gateway/servicemonitor.yaml:17:22: executing "grafana-mimir/templates/store-gateway/servicemonitor.yaml" at <merge>: wrong number of args for merge: want at least 1 got 0
```
### Additional information

ref: https://artifacthub.io/packages/helm/bitnami/grafana-mimir
