### ISSUE TITLE
[bitnami/mlflow] MLFLOW_S3_ENDPOINT_URL not inject if i dont want to use minio

### ISSUE THREAD

**Issue by Alansyf** [bitnami/charts#26397]
### Name and Version

mlflow/1.2.0

### What architecture are you using?

None

### What steps will reproduce the bug?

it was working fine before and today I am upgrading my mlflow to the latest mlfow 2.13.0. 

In my values.yaml
I need to set minio to false due to company policy. 
```yaml
minio:
  ## @param minio.enabled Enable/disable MinIO&reg; chart installation
  ## to be used as an objstore for Mlflow
  ##
  enabled: false
```

But I have my custom s3 host,  e.g my company provided s3-compatible host:
```yaml
externalS3:
  host: "objectstore.xyz.com"
  port: 443
  ...
```

In this [PR](https://github.com/bitnami/charts/pull/25294/files) , it introduced that i must enable minio otherwise my custom value won't able to inject. 

I have to temporary remove the PR introduced condition.

### What do you see instead?

NA.
