### ISSUE TITLE
[bitnami/postgresql-ha] Upgrade from 14.1.0 to 14.1.1 fails due to invalid exporter pod spec

### ISSUE THREAD

**Issue by MalteJoe** [bitnami/charts#26396]
### Name and Version

bitnami/postresql-ha 14.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Using kubernetes 1.29.4

Upgrading helm release version from 14.1.0 to 14.1.1 

### Are you using any custom parameters or values?

Metrics are enabled via `--set metrics.enabled=true` and the have custom `metrics.resources`
as this seems to be related to the exporter readiness probe

### What is the expected behavior?

Successful upgrade

### What do you see instead?

The upgrade fails because of an invalid pod spec:
`create Pod postgres-postgresql-2 in StatefulSet postgres-postgresql failed error: Pod "postgres-postgresql-2" is invalid: spec.containers[1].livenessProbe: Required value: must specify a handler type`

The rendered spec `spec.containers[1].livenessProbe` with 14.1.1 looks like this:
```
livenessProbe:
  failureThreshold: 6
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
```

while with 14.1.0 it looked like this:
```
livenessProbe:
  failureThreshold: 6
  httpGet:
    path: /
    port: metrics
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
```

### Additional information

Probably introduced with https://github.com/bitnami/charts/pull/26388
