### ISSUE TITLE
[Kafka] KeeperErrorCode = NoAuth for /config/users/user

### ISSUE THREAD

**Issue by rdziwinski** [bitnami/charts#26406]
### Name and Version

bitnami/kafka:24.0.14

### What architecture are you using?

amd64

### What steps will reproduce the bug?

**env:**
k8s: 1.29.4
helm: 3.14.4
chart: 24.0.14

Hello, I need upgrade Kafka 3.5 from Zookeeper mode to Kraft. I perform upgrade helm chart from 23 to 24. After that kafka broker was restarted due error below.

### Are you using any custom parameters or values?

**Before: v23**

```yaml
auth: 
  clientProtocol: mtls
  externalClientProtocol: ""
  interBrokerProtocol: sasl
  sasl:
    mechanisms: plain,scram-sha-256,scram-sha-512
    interBrokerMechanism: plain 
    jaas:    
      interBrokerUser: kafka_broker
      interBrokerPassword:
      zookeeperUser: kafus
      zookeeperPassword:
      existingSecret: passwords

  tls:
    type: pem
    pemChainIncluded: false
    existingSecrets:
      - kafka-0-tls
      - kafka-1-tls
      - kafka-2-tls
    autoGenerated: false

allowPlaintextListener: false
interBrokerListenerName: INTERNAL
authorizerClassName: "kafka.security.authorizer.AclAuthorizer"

```

**After: v24**
```yaml
extraConfig: |
  auto.create.topics.enable = false
  num.partitions = 3
  default.replication.factor = 3
  delete.topic.enable = true
  log.flush.interval.ms = 1000
  log.retention.hours = 60
  log.retention.bytes = 1073741824
  log.segment.bytes = 1073741824
  allow.everyone.if.no.acl.found = true
  super.users=User:admin
  authorizer.class.name = org.apache.kafka.metadata.authorizer.StandardAuthorizer
  zookeeper.set.acl=false
  
listeners:
  client:
    containerPort: 9092
    protocol: SSL
    name: CLIENT
    sslClientAuth: required
  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: SASL_PLAINTEXT
  interbroker:
    containerPort: 9094
    protocol: SASL_PLAINTEXT
    name: INTERNAL
  external:
    containerPort: 9095
    protocol: SSL
    name: EXTERNAL
  sslClientAuth: required

sasl:
  enabledMechanisms: PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
  interBrokerMechanism: PLAIN
  controllerMechanism: PLAIN
  zookeeper:
    user: kafus
    password: "password"
  interbroker:
    user: kafka_broker
    password: "password"
  controller:
    user: controller_user
    password: "password"
  client:
    users:
      - user
    passwords: "password"

tls:
  type: PEM
  pemChainIncluded: false
  existingSecret: kafka-all-tls
  autoGenerated: false
  endpointIdentificationAlgorithm: https
  sslClientAuth: required


controller:
  replicaCount: 1
  controllerOnly: true
  zookeeperMigrationMode: true

broker:
  zookeeperMigrationMode: false
  replicaCount: 3
  minId: 0

kraft:
  enabled: true
  clusterId: "ididididid"

zookeeper:
  clusterDomain: k8s.infra.k.pl
  enabled: true
  replicaCount: 3
  auth:
    client:
      enabled: true
      clientUser: "kafus"
      clientPassword: "password"
      serverUsers: "kafus"
      serverPasswords: "password"
```

### What do you see instead?

Kafka broker restarted with error below:
```
kafka 10:21:53.13 DEBUG ==> Creating user user in zookeeper
Warning: --zookeeper is deprecated and will be removed in a future version of Kafka.
Use --bootstrap-server instead to specify a broker to connect to.
Error while executing config command with args '--zookeeper kafka-zookeeper:2181 --alter --add-config SCRAM-SHA-256=[iterations=8192,password=bitnami],SCRAM-SHA-512=[password=bitnami] --entity-type users --entity-name user'
org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /config/users/user
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:120)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at kafka.zookeeper.AsyncResponse.resultException(ZooKeeperClient.scala:563)
	at kafka.zk.KafkaZkClient.getEntityConfigs(KafkaZkClient.scala:435)
	at kafka.zk.AdminZkClient.fetchEntityConfig(AdminZkClient.scala:552)
	at kafka.admin.ConfigCommand$.alterConfigWithZk(ConfigCommand.scala:160)
	at kafka.admin.ConfigCommand$.processCommandWithZk(ConfigCommand.scala:121)
	at kafka.admin.ConfigCommand$.main(ConfigCommand.scala:95)
	at kafka.admin.ConfigCommand.main(ConfigCommand.scala)
```

### Additional information

I'm confused that in the new server.properties is JKS certs, instead of PEM as i declaration in tls.type=PEM

```
# TLS configuration
ssl.keystore.type=JKS
ssl.truststore.type=JKS
ssl.keystore.location=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
ssl.truststore.location=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
ssl.keystore.password=keystore-password
ssl.truststore.password=truststore-password
```

I'm trying to add acl for allow all for user "user" in zookeeper but after login in zookeeper pods and user jaas.conf with auth's I don't have permission.
