### ISSUE TITLE
[bitnami/mongodb] Problem with externalAccess and replicaset both enabled (slice index out of range)

### ISSUE THREAD

**Issue by octane100** [bitnami/charts#26423]
### Name and Version

bitnami/mongodb 15.6.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploying a Mongodb cluster with 3 replicasets and externalAccess enabled:

### Are you using any custom parameters or values?

values.yaml : 
```yaml
architecture: replicaset
replicaCount: 3
persistence:
  enabled: true
  storageClass: gp3
rbac:
  create: true
externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-scheme: internal
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-attributes: deletion_protection.enabled=false
      external-dns.alpha.kubernetes.io/hostname: "{{`{{ $.targetPod }}`}}.internal.domain.com"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
pdb:
  create: true
  maxUnavailable: 1
serviceAccount:
  create: true
  automountServiceAccountToken: true
automountServiceAccountToken: true
replicaSetName: "mongo32test"
auth:
  enabled: true
  rootUser: admin
  existingSecret: "mongo-secret"
arbiter:
  enabled: false
```

### What is the expected behavior?

Deployment running without error

### What do you see instead?

```
STDERR:
  Error: Failed to render chart: exit status 1: Error: template: sso/charts/mongodb/templates/replicaset/external-access-svc.yaml:23:49: executing "sso/charts/mongodb/templates/replicaset/external-access-svc.yaml" at <index $root.Values.externalAccess.service.annotationsList $i>: error calling index: reflect: slice index out of range
```

### Additional information

The issue has occurred since version 15.3.0 (https://github.com/bitnami/charts/pull/25397).

I can workaround the issue by adding these lines to the values.yaml : 
```yaml
externalAccess:
  service:
    annotationsList: # Workaround for bug introduced by https://github.com/bitnami/charts/pull/25397
      - 
      - 
      -  
```
