### ISSUE TITLE
[bitnami/jenkins] Jenkins, CASC, deprecated resources parameters

### ISSUE THREAD

**Issue by artur-borys** [bitnami/charts#26435]
### Name and Version

bitnami/jenkins 13.3.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Install the Helm chart
2. Observe the jenkins container logs

### Are you using any custom parameters or values?

  ``` yaml
  # omitted some confidential parameters, like passwords and domain etc.
  configAsCode:
    enabled: true
  agent:
    enabled: true
  plugins:
  - kubernetes
  - configuration-as-code
  - rebuild
  - dark-theme
  - pipeline-stage-view
  - git
  - workflow-multibranch
  - pipeline-model-definition
  ```

### What is the expected behavior?

The installation succeeds and I can login to Jenkins

### What do you see instead?

I can see an error message stating that ``resourceRequestCpu`` is deprecated.
```
2024-05-25 11:50:24.103+0000 [id=31] WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class org.csanchez.jenkins.plugins.kubernetes.PodTemplate#listener: type is abstract but not Describable.
2024-05-25 11:50:24.116+0000 [id=31] SEVERE jenkins.InitReactorRunner$1#onTaskFailed: Failed ConfigurationAsCode.init
io.jenkins.plugins.casc.ConfiguratorException: 'resourceRequestCpu' is deprecated
```

### Additional information

I can see that bitnami/jenkins has template for agent resources here: https://github.com/bitnami/charts/blob/main/bitnami/jenkins/templates/_helpers.tpl#L98

**Comment by artur-borys** [comment]
Adding to values this:
``` yaml
agent:
  enabled: true
  resourcesPreset: none
```

at least makes the installation pass, but it would be better to be able to configure the resources
