### ISSUE TITLE
[bitnami/postgresql-ha] nil pointer evaluating interface {}.postgresql after upgrade from 14.1.0 to 14.1.1 or 14.1.2

### ISSUE THREAD

**Issue by pfaelzerchen** [bitnami/charts#26434]
### Name and Version

bitnami/postgresql-ha 14.1.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. I'm using k3s and doing deployments with argo-cd in combination with a self-hosted gitea. Upgrades are regularly proposed by renovate.
2. Upgrade from 14.1.0 to 14.1.1 or 14.1.2 by modifying targetRevision of the argo Application.
3. argo-cd will show the following error:

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm template . --name-template authelia-postgres --namespace authelia --kube-version 1.29 --values /tmp/8577e11c-a159-4246-9aac-7972c47af8e7 <api versions removed> --include-crds` failed exit status 1: Error: template: postgresql-ha/templates/postgresql/statefulset.yaml:421:20: executing "postgresql-ha/templates/postgresql/statefulset.yaml" at <include "postgresql-ha.readinessProbeCommand" (dict "component" "postgresql" "context" $)>: error calling include: template: postgresql-ha/templates/_helpers.tpl:729:76: executing "postgresql-ha.readinessProbeCommand" at <include "postgresql-ha.postgresql.tlsCert" .>: error calling include: template: postgresql-ha/templates/_helpers.tpl:712:75: executing "postgresql-ha.postgresql.tlsCert" at <.Values.postgresql.tls.certFilename>: nil pointer evaluating interface {}.postgresql Use --debug flag to render out invalid YAML
```

### Are you using any custom parameters or values?

The extra intend is from spec.source.helm.valuesObject of the argo Application.

```yaml

        ## @section Global parameters
        ## Global Docker image parameters
        ## Please, note that this will override the image parameters, including dependencies, configured to use the global value
        ## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass

        ## @param global.storageClass Global StorageClass for Persistent Volume(s)
        global:
          storageClass: ceph-block   # database ensures replication itself

        ## @param fullnameOverride String to fully override common.names.fullname template
        ##
        fullnameOverride: postgres

        ## @param extraDeploy Array of extra objects to deploy with the release (evaluated as a template)
        ##
        extraDeploy: []

        ## @section PostgreSQL with Repmgr parameters

        ## PostgreSQL parameters
        ##
        postgresql:
          ## @param postgresql.replicaCount Number of replicas to deploy. Use an odd number. Having 3 replicas is the minimum to get quorum when promoting a new primary.
          ##
          replicaCount: 3

          ## PostgreSQL containers' resource requests and limits
          ## ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
          ## We usually recommend not to specify default resources and to leave this as a conscious
          ## choice for the user. This also increases chances charts run on environments with little
          ## resources, such as Minikube. If you do want to specify resources, uncomment the following
          ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
          ## @param postgresql.resourcesPreset Set container resources according to one common preset (allowed values: none, nano, small, medium, large, xlarge, 2xlarge). This is ignored if postgresql.resources is set (postgresql.resources is recommended for production).
          ## More information: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
          ##
          resourcesPreset: "micro"
          ## @param postgresql.resources Set container requests and limits for different resources like CPU or memory (essential for production workloads)
          ## Example:
          ## resources:
          ##   requests:
          ##     cpu: 2
          ##     memory: 512Mi
          ##   limits:
          ##     cpu: 3
          ##     memory: 1024Mi
          ##
          resources: {}

          ## PostgreSQL configuration parameters
          ## @param postgresql.username PostgreSQL username
          ## @param postgresql.password PostgreSQL password
          ## @param postgresql.database PostgreSQL database
          ##
          username: authelia
          password: ""
          database: authelia
          ## @param postgresql.existingSecret PostgreSQL password using existing secret
          ##
          existingSecret: postgres-secrets

          # @param postgresql.upgradeRepmgrExtension Upgrade repmgr extension in the database
          ##
          upgradeRepmgrExtension: false

          ## TLS configuration
          ##
          tls:
            ## @param postgresql.tls.enabled Enable TLS traffic support for end-client connections
            ##
            enabled: true
            ## @param postgresql.tls.preferServerCiphers Whether to use the server's TLS cipher preferences rather than the client's
            ##
            preferServerCiphers: true
            ## @param postgresql.tls.certificatesSecret Name of an existing secret that contains the certificates
            ##
            certificatesSecret: tls-postgres
            ## @param postgresql.tls.certFilename Certificate filename
            ##
            certFilename: tls.crt
            ## @param postgresql.tls.certKeyFilename Certificate key filename
            ##
            certKeyFilename: tls.key

        ## Pgpool parameters
        ##
        pgpool:
          ## @param pgpool.customUsersSecret Name of a secret containing the usernames and passwords of accounts that will be added to pgpool_passwd
          ## The secret must contain the keys "usernames" and "passwords" respectively.
          ##
          customUsersSecret: pgpool-secrets

          ## @param pgpool.existingSecret Pgpool admin password using existing secret
          ##
          existingSecret: pgpool-secrets

          ## @param pgpool.replicaCount The number of replicas to deploy
          ##
          replicaCount: 2

          ## Pgpool containers' resource requests and limits
          ## ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
          ## We usually recommend not to specify default resources and to leave this as a conscious
          ## choice for the user. This also increases chances charts run on environments with little
          ## resources, such as Minikube. If you do want to specify resources, uncomment the following
          ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
          ## @param pgpool.resourcesPreset Set container resources according to one common preset (allowed values: none, nano, small, medium, large, xlarge, 2xlarge). This is ignored if pgpool.resources is set (pgpool.resources is recommended for production).
          ## More information: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
          ##
          resourcesPreset: "micro"
          ## @param pgpool.resources Set container requests and limits for different resources like CPU or memory (essential for production workloads)
          ## Example:
          ## resources:
          ##   requests:
          ##     cpu: 2
          ##     memory: 512Mi
          ##   limits:
          ##     cpu: 3
          ##     memory: 1024Mi
          ##
          resources: {}

          ##
          ## TLS configuration
          ##
          tls:
            ## @param pgpool.tls.enabled Enable TLS traffic support for end-client connections
            ##
            enabled: true
            ## @param pgpool.tls.autoGenerated Create self-signed TLS certificates. Currently only supports PEM certificates
            ##
            autoGenerated: false
            ## @param pgpool.tls.preferServerCiphers Whether to use the server's TLS cipher preferences rather than the client's
            ##
            preferServerCiphers: true
            ## @param pgpool.tls.certificatesSecret Name of an existing secret that contains the certificates
            ##
            certificatesSecret: tls-postgres
            ## @param pgpool.tls.certFilename Certificate filename
            ##
            certFilename: tls.crt
            ## @param pgpool.tls.certKeyFilename Certificate key filename
            ##
            certKeyFilename: tls.key
            ## @param pgpool.tls.certCAFilename CA Certificate filename
            ## If provided, PgPool will authenticate TLS/SSL clients by requesting them a certificate
            ## ref: https://www.pgpool.net/docs/latest/en/html/runtime-ssl.html
            ##
            certCAFilename: ""

        ## @section Persistence parameters

        ## Enable persistence using Persistent Volume Claims
        ## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
        ##
        persistence:
          ## @param persistence.enabled Enable data persistence
          ##
          enabled: true

          ## @param persistence.storageClass Persistent Volume Storage Class
          ## If defined, storageClassName: <storageClass>
          ## If set to "-", storageClassName: "", which disables dynamic provisioning
          ## If undefined (the default) or set to null, no storageClassName spec is
          ## set, choosing the default provisioner.
          ##
          storageClass: ceph-block

          ## @param persistence.size Persistent Volume Claim size
          ##
          size: 2Gi
```

### What is the expected behavior?

helm installs without the given error.

### What do you see instead?

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm template . --name-template authelia-postgres --namespace authelia --kube-version 1.29 --values /tmp/8577e11c-a159-4246-9aac-7972c47af8e7 <api versions removed> --include-crds` failed exit status 1: Error: template: postgresql-ha/templates/postgresql/statefulset.yaml:421:20: executing "postgresql-ha/templates/postgresql/statefulset.yaml" at <include "postgresql-ha.readinessProbeCommand" (dict "component" "postgresql" "context" $)>: error calling include: template: postgresql-ha/templates/_helpers.tpl:729:76: executing "postgresql-ha.readinessProbeCommand" at <include "postgresql-ha.postgresql.tlsCert" .>: error calling include: template: postgresql-ha/templates/_helpers.tpl:712:75: executing "postgresql-ha.postgresql.tlsCert" at <.Values.postgresql.tls.certFilename>: nil pointer evaluating interface {}.postgresql Use --debug flag to render out invalid YAML
```

**Comment by pfaelzerchen** [comment]
The problem seems to still exist. I had to deactivate the readinessProbe for the moment.

**Comment by pfaelzerchen** [comment]
Is there any chance, this could be reopened? I added a custom `customReadinessProbe` to get around the bug.

```yaml
customReadinessProbe:
  failureThreshold: 6
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
  exec:
    command:
       - bash
       - -ec
       - |
        exec pg_isready -U "postgres" -d "sslcert=/opt/bitnami/postgresql/certs/tls.crt sslkey=/opt/bitnami/postgresql/certs/tls.key" -h 127.0.0.1 -p 5432
        [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
```
