### ISSUE TITLE
[bitnami/kafka] No NetworkPolicy for jmx metrics

### ISSUE THREAD

**Issue by Amikuto** [bitnami/charts#26459]
### Name and Version

bitnami/kafka 28.2.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy kafka helm chart in k8s cluster
2. Expose jmx metrics in values.yaml file

### Are you using any custom parameters or values?

```yaml
metrics:
  jms:
    enabled: true
  serviceMonitor:
    enabled: true
```

### What is the expected behavior?

I want to receive metrics from outside the pod. Helm chart should add a port for JMX metrics in the generated NetworkPolicy.

### What do you see instead?

When I try to obtain metrics from outside the pod with exposed JMX metrics, my connection is refused
No telnet:
![image](https://github.com/bitnami/charts/assets/56434766/c7a35e84-0e7b-4559-ab0e-db6c6f87246c)
No curl:
![image](https://github.com/bitnami/charts/assets/56434766/ed767d8e-d19e-4f9f-9c74-669566e4df7c)
Vmagent:
![image](https://github.com/bitnami/charts/assets/56434766/3424fd33-dec7-419f-9be4-6aa82ce13e7d)

### Additional information

When I expose metrics through JMX, an additional port for them is not added to the NetworkPolicy.
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-kraft
  namespace: kafka
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: kafka-kraft
      app.kubernetes.io/name: kafka
  ingress:
    - ports:
        - protocol: TCP
          port: 9092
        - protocol: TCP
          port: 9094
        - protocol: TCP
          port: 9093
        - protocol: TCP
          port: 9095
        - protocol: TCP
          port: 9308
  egress:
    - {}
  policyTypes:
    - Ingress
    - Egress
```

When added
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-kraft
  namespace: kafka
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: kafka-kraft
      app.kubernetes.io/name: kafka
  ingress:
    - ports:
        - protocol: TCP
          port: 9092
        - protocol: TCP
          port: 9094
        - protocol: TCP
          port: 9093
        - protocol: TCP
          port: 9095
        - protocol: TCP
          port: 9308
        - protocol: TCP
          port: 5556 # <-------------------------------------------------------
  egress:
    - {}
  policyTypes:
    - Ingress
    - Egress
```

```shell
/ # telnet kafka-kraft-jmx-metrics.kafka 5556
Connected to kafka-kraft-jmx-metrics.kafka
```
