### ISSUE TITLE
Put a requirements.txt it gives error

### ISSUE THREAD

**Issue by thispejo** [bitnami/charts#26465]
### Name and Version

helm airflow 18.1.1

### What architecture are you using?

None

### What steps will reproduce the bug?

add requirements.txt in yaml

### Are you using any custom parameters or values?

```yaml
auth:
  username: "xxxxxxxxxxxxxxx"   

executor: "CeleryKubernetesExecutor"
 
postgresql:
  primary:
    persistence:
      storageClass: "oci-bv"
    nodeSelector:
      name: AirflowHomo 

redis:
  master:
    persistence:
      storageClass: "oci-bv"  
    nodeSelector:
      name: AirflowHomo    
  replica:
    persistence:
      storageClass: "oci-bv"  
    nodeSelector:
      name: AirflowHomo         

requirements-volume-config: &requirements-volume-config
  extraVolumeMounts:
    - name: requirements
      mountPath: /bitnami/python/requirements.txt
      subPath: requirements.txt
  extraVolumes:
    - name: requirements
      configMap:
        name: airflow-requirements

web: 
  automountServiceAccountToken: true
  autoscaling:
    enable: true  
    minReplicas: 1
    maxReplicas: 3
  existingConfigmap: airflow-web-config
  <<: *requirements-volume-config    

  image:  
    debug: true

  replicaCount: 1
  nodeSelector:
    name: AirflowHomo 
  readinessProbe:
    enabled: true
    initialDelaySeconds: 120
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    
  resources:
    requests:
      cpu: 500m 
      memory: "500Mi" 
    limits:
      cpu: "2" 
      memory: "6Gi"

scheduler:
  replicaCount: 1
  autoscaling:
    enable: true  
    minReplicas: 1
    maxReplicas: 5  
    targetCPU: 80
    targetMemory: 80      
  nodeSelector:
    name: AirflowHomo 
  automountServiceAccountToken: true
  <<: *requirements-volume-config    

  resources:
    requests:
      cpu: "1500m" 
      memory: "4Gi" 
    limits:
      cpu: "3000m" 
      memory: "10Gi"

worker: 
  replicaCount: 1
  nodeSelector:
    name: AirflowHomo
  autoscaling:
    enable: true  
    minReplicas: 1
    maxReplicas: 5
    targetCPU: 80
    targetMemory: 80    
  readinessProbe:
    enabled: true
    initialDelaySeconds: 120
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
  automountServiceAccountToken: true
  <<: *requirements-volume-config      

  resources:
    requests:
      cpu: "3500m" 
      memory: "8Gi" 
    limits:
      cpu: "4000m" 
      memory: "14Gi"

git:
  dags: 
    enabled: true
    repositories:                    
      - repository: https://xxxxxxxxxxxxxxxxxxxx/_git/SaaS.Airflow      
        name: devops
        branch: main        
  sync:
    interval: 20
 
ldap:
  enabled: false 

extraEnvVars:
  - name: AIRFLOW__LOGGING__LOGGING_LEVEL
    value: "INFO"
  - name: AIRFLOW__SMTP__SMTP_HOST
    value: "smtp.gmail.com"
  - name: AIRFLOW__SMTP__SMTP_STARTTLS
    value: "True"
  - name: AIRFLOW__SMTP__SMTP_SSL
    value: "False"
  - name: AIRFLOW__SMTP__SMTP_USER
    value: "noreply@xxxx.xxxx.xx"
  - name: AIRFLOW__SMTP__SMTP_PORT
    value: "587"
  - name: AIRFLOW__SMTP__SMTP_PASSWORD
    value: "xxxxxxx" 
  - name: AIRFLOW__SMTP__SMTP_MAIL_FROM
    value: "noreply@xxxxx.xxxx.xxx"
  - name: PYTHONPATH
    value: "/opt/bitnami/airflow/dags/git_devops/airflowdags/"
  - name: AIRFLOW__KUBERNETES_EXECUTOR__LOGS_TASK_METADATA
    value: "True"
  - name: AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS_ON_FAILURE
    value: "True" #default false
  - name: AIRFLOW__LOGGING__CELERY_LOGGING_LEVEL
    value: "INFO"   
  - name: AIRFLOW_KUBERNETES_LOGGING_ENABLED
    value: "True" #default false      

extraDeploy:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: airflow-requirements
    data: #apache-airflow-providers-apache-spark==4.8.0
      requirements.txt: |
        Authlib==1.3.0
        pytz==2024.1         
        apache-airflow-providers-apache-spark[cncf.kubernetes] 
        apache-airflow-providers-cncf-kubernetes

ingress:
  enabled: True
  selfSigned: false
  ingressClassName: "nginx"  
  tls: true    
  extraRules: 
  - host: airflow-homo.xxxx.xxxx
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:            
          service:
            name: airflow-homo
            port:
              number: 8080

  extraTls:
  - hosts:
    - "airflow-homo.xxxx.xxx"
    secretName: certificado-airflow-tls
  secrets:
    - name: certificado-airflow-tls
      key: |-
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIB         
        -----END RSA PRIVATE KEY-----
      certificate: |-
        -----BEGIN CERTIFICATE-----
        MIIGPjCC VSn
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIIEijCCA3KgAwIBAgIQfU1CqStDHX5kU+ xxx
        MQs       
        -----END CERTIFICATE-----

metrics:
  enabled: true
  nodeSelector:
    name: AirflowHomo  
  serviceMonitor:
    enabled: true 
    namespace: monitoring
    interval: 10s
    scrapeTimeout: 5s
    honorLabels: true
    selector:
      app.kubernetes.io/name: "prometheus"
      app.kubernetes.io/instance: "monitoring-prod-kube-prome-prometheus"
``` 

### What do you see instead?
```
Downloading Authlib-1.3.0-py2.py3-none-any.whl (223 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 223.7/223.7 kB 14.3 MB/s eta 0:00:00
Installing collected packages: Authlib
ERROR: Could not install packages due to an OSError: [Errno 30] Read-only file system: '/opt/bitnami/airflow/venv/lib/python3.11/site-packages/authlib'
```
### Additional information
```
helm install airflow-homo oci://registry-1.docker.io/bitnamicharts/airflow -f kubernetes\airflow-homo\airflow_homo_bitnami.yaml --namespace=airflow-homo 
```
