### ISSUE TITLE
Kafka Broker Cannot Access Outside Kubernetes Cluster via ClusterIP Services

### ISSUE THREAD

**Issue by zeeshan018** [bitnami/charts#26463]
### Name and Version

29.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I followed the documentation provided for setting up Kafka with external ClusterIP services in Kubernetes. However, I'm encountering an issue where the Kafka broker cannot access outside the Kubernetes cluster.

Steps to Reproduce:

- Followed the documentation provided
- Configured the Kafka broker and ingress as instructed.
- Attempted to access Kafka from outside the Kubernetes cluster.

Expected Behavior:

The Kafka broker should be accessible from outside the Kubernetes cluster using the configured ClusterIP services and ingress.

Actual Behavior:
Encountering a timeout error: [AdminClient clientId=kafka-ui-admin-1716828247-137] Disconnecting from node -1 due to socket connection setup timeout. The timeout value is 9125 ms.

Additionally, I would appreciate it if someone could review my configuration to identify any potential mistakes or misconfigurations. Below is the configuration I've used:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: kafka-ingress
namespace: zee
annotations:
nginx.ingress.kubernetes.io/configuration-snippet: |
tcp: 9094: "{{ include "common.names.namespace" . }}/{{ include "common.names.fullname" . }}-0-external:9094"
spec:
ingressClassName: nginx
rules:

host: xxx.example.com
http:
paths:
path: /
pathType: ImplementationSpecific
backend:
service:
name: my-release-kafka-broker-0-external
port:
number: 9094
```

In value.yaml I used:
```
externalAccess.enabled=true
externalAccess.controller.service.type=ClusterIP
externalAccess.controller.service.ports.external=9094
externalAccess.controller.service.domain=test.testfuse.net
externalAccess.broker.service.type=ClusterIP
externalAccess.broker.service.ports.external=9094
externalAccess.broker.service.domain=test.testfuse.net
```

### What do you see instead?

![image](https://github.com/bitnami/charts/assets/141921581/0d92dd36-b2a1-4adc-abc1-417b14ee968e)
