### ISSUE TITLE
Fix permissions for apprepositories issue 5323 tanzu

### ISSUE THREAD

**Issue by cristi-vlad** [bitnami/charts#26478]
### Name and Version

bitnami/kubeapps

File: https://github.com/bitnami/charts/blob/main/bitnami/kubeapps/templates/apprepository/rbac.yaml

### What is the problem this feature will solve?

https://github.com/vmware-tanzu/kubeapps/issues/5323

### What is the feature you are proposing to solve the problem?

For role: {{ printf "%s-repositories-write" .Release.Name }}

- add "get" verb for "secrets" (it has only "create" https://github.com/vmware-tanzu/kubeapps/blob/main/chart/kubeapps/templates/apprepository/rbac.yaml#L153)

```yaml
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
```

For ClusterRole: {{ printf "kubeapps:%s:apprepositories-read" .Release.Namespace | quote }})

- add "secrets" resources with "get" verb (it is only apprepositories resource - https://github.com/vmware-tanzu/kubeapps/blob/main/chart/kubeapps/templates/apprepository/rbac.yaml#L171)

```yaml
  - apiGroups:
      - kubeapps.com
    resources:
      - secrets
    verbs:
      - get
```

For ClusterRole: {{ printf "kubeapps:%s:apprepositories-write" .Release.Namespace | quote }})

- add TO "secrets" resources :
```yaml
  - apiGroups:
      - "kubeapps.com"
```

### What alternatives have you considered?

In rancher, we had to manually add the above described rules.
