### ISSUE TITLE
[zookeeper] Crash when using podAnnotations

### ISSUE THREAD

**Issue by srilumpa** [bitnami/charts#2652]
**Which chart**:
zookeeper v5.14.3

**Describe the bug**
Adding custom pod annotations (using `podAnnotations` value) leads to crash when generating statefulset

**To Reproduce**
1. Generate a value file with at least one entry to the `podAnnotations` value
2. Try to apply the chart or make a diff
3. Helm crashes with `error converting YAML to JSON: yaml: line 34: mapping values are not allowed in this context`

**Expected behavior**
No crash when trying to deploy the zookeeper chart and proper annotations set. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Tests were done with the following in values.yaml:

```yaml
podAnnotations:
  linkerd.io/inject: disabled
```

Helm diff says :

```
Error: YAML parse error on /zookeeper/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 34: mapping values are not allowed in this context
helm.go:84: [debug] error converting YAML to JSON: yaml: line 34: mapping values are not allowed in this context
YAML parse error on /zookeeper/templates/statefulset.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	/home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	/home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	/home/circleci/helm.sh/helm/pkg/action/action.go:159
helm.sh/helm/v3/pkg/action.(*Install).Run
	/home/circleci/helm.sh/helm/pkg/action/install.go:238
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:229
main.newTemplateCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/template.go:66
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357

Error: plugin "diff" exited with error
helm.go:84: [debug] plugin "diff" exited with error
```

Helm template shows the following (snipped):

```yaml
spec:
  serviceName: RELEASE-NAME-zookeeper-headless
  replicas: 3
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper
      app.kubernetes.io/instance: RELEASE-NAME
      app.kubernetes.io/component: zookeeper
  template:
    metadata:
      name: RELEASE-NAME-zookeeper
      labels:
        app.kubernetes.io/name: zookeeper
        helm.sh/chart: zookeeper-5.14.3
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: zookeeper
      annotations:
        linkerd.io/inject: disabledprometheus.io/port: '9141'
        prometheus.io/scrape: "true"
```

Annotations are 

```yaml
annotations:
  linkerd.io/inject: disabledprometheus.io/port: '9141'
  prometheus.io/scrape: "true"
```

instead of 

```yaml
annotations:
  linkerd.io/inject: disabled
  prometheus.io/port: '9141'
  prometheus.io/scrape: "true"
```
