### ISSUE TITLE
[bitnami/contour] Typo in livenessProbe

### ISSUE THREAD

**Issue by dcardellino24** [bitnami/charts#26524]
### Name and Version

bitnami/contour 18.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When you run `helm upgrade --namespace contour contour oci://registry-1.docker.io/bitnamicharts/contour --version 18.1.1` you receive the following error:
```
Error: UPGRADE FAILED: cannot patch "contour-envoy" with kind Deployment: Deployment.apps "contour-envoy" is invalid: spec.template.spec.containers[1].livenessProbe: Required value: must specify a handler type
```

### Are you using any custom parameters or values?

```yaml
configInline:
  accesslog-format: json
  enableExternalNameService: true
  network:
    num-trusted-hops: 1
  timeouts:
    connection-idle-timeout: 650s
contour:
  ingressClass:
    name: ds
  manageCRDs: false
  resources:
    limits:
      memory: 150Mi
    requests:
      cpu: 10m
      memory: 150Mi
  networkPolicy:
    enabled: false
  certgen:
    networkPolicy:
      enabled: false
envoy:
  replicaCount: 10
  autoscaling:
    enabled: true
    minReplicas: 3
  containerPorts:
    http: 8080
  kind: deployment
  podAnnotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi
  networkPolicy:
    enabled: false
  service:
    externalTrafficPolicy: ""
    extraPorts:
    - name: http-extra
      port: 8080
      targetPort: 8080
    type: ClusterIP
  useHostPort: false
metrics:
  serviceMonitor:
    enabled: true
```

### What is the expected behavior?

That the Chart is upgraded successfully.

### What do you see instead?

```
Error: UPGRADE FAILED: cannot patch "contour-envoy" with kind Deployment: Deployment.apps "contour-envoy" is invalid: spec.template.spec.containers[1].livenessProbe: Required value: must specify a handler type
```
