### ISSUE TITLE
[bitnami/argo-cd] Liveness Probe always fails on applicationset-controller

### ISSUE THREAD

**Issue by ricoapon** [bitnami/charts#26547]
### Name and Version

bitnami/argocd 6.3.4

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Install ArgoCD using Bitnami Helm Charts. You can use default values, but make sure that applicationSet.enabled=true.

### Are you using any custom parameters or values?

```yaml
applicationSet:
  enabled: true
  serviceAccount:
    automountServiceAccountToken: true
```

### What is the expected behavior?

The pod "<namespace>-applicationset-controller-<hash>" starts correctly, and stays up and running.

### What do you see instead?

The pod starts correctly, readiness probe is OK. Then after 30 seconds, Kubernetes kills the pod. Event log show that the liveness probe returned a 404.

### Additional information

I added a customLivenessProbe to work around this issue, and that solved the problem. I configured the livenessProbe that was used in older versions:
```yaml
applicationset:
  customLivenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    tcpSocket:
      port: probe
    timeoutSeconds: 1
```
This solved the issue.

https://github.com/bitnami/charts/commit/641696157e9dcb47341bb68d04c62e7d49181312
This is the commit that changed the liveness probe. It seems to be intended, but I cannot find the documentation on why this is correct.

Another sidenote:
https://github.com/bitnami/charts/blob/main/bitnami/argo-cd/templates/applicationset/deployment.yaml#L121
You can see in this line 121 and 122 that it contains "livenessProbe:". They are duplicate lines. Helm doesn't seem to say that the yaml is invalid, but it is strange that we have duplicate lines. That should be removed I think.
