### ISSUE TITLE
[bitnami/postgresql-ha] Bug hostname "I have no name!" in release 14.1.3

### ISSUE THREAD

**Issue by GatoSnake** [bitnami/charts#26556]
### Name and Version

bitnami/postgresql-ha 14.1.3

### What architecture are you using?

None

### What steps will reproduce the bug?

1- Use this value.yaml configuration:

```yaml
global:
  postgresql:
    username: postgres
    password: postgres
    database: postgres
    repmgrUsername: repmgr
    repmgrPassword: repmgr
    repmgrDatabase: repmgr
  pgpool:
    adminUsername: pgpooladmin
    adminPassword: pgpooladmin
postgresql:
  password: postgres
  repmgrPassword: repmgr
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: postgresql
pgpool:
  adminPassword: pgpooladmin
  customUsers:
    usernames: user1,user2
    passwords: pass1,pass2
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: pgpool
```

2- Create the helm application with the command:

`helm install postgresql-ha oci://registry-1.docker.io/bitnamicharts/postgresql-ha -f values.yaml --create-namespace -n postgresql-ha`

3- Access to some pod and check the hostname:

<img width="228" alt="image" src="https://github.com/bitnami/charts/assets/2672846/80ed00bb-5f7e-4501-aef5-888fc1e9ff94">

4- Problem with repmgr using the command:

<img width="807" alt="image" src="https://github.com/bitnami/charts/assets/2672846/0a6d19d8-f75c-4149-9d1f-3dca7658b60a">

### What do you see instead?

<img width="372" alt="image" src="https://github.com/bitnami/charts/assets/2672846/503e8d3b-7073-411e-8383-1f88f4d0918a">
<img width="807" alt="image" src="https://github.com/bitnami/charts/assets/2672846/85aa9fd0-8e0a-4b7f-b863-47ef76ad1588">
