### ISSUE TITLE
[bitnami/helm-kafka] Pod CrashLoopBack State: While enable Sasl_ssl Configuration

### ISSUE THREAD

**Issue by zeeshan018** [bitnami/charts#26567]
### Name and Version

bitnami helm chart : 29.0.3

### What architecture are you using?

None

### What steps will reproduce the bug?

When I set up the `sasl_ssl` configuration in the values.yaml file, the pods go into a CrashLoopBackOff state. Upon investigation using the command:
```
kubectl logs pod-name -n namespace -c kafka-init
```
it indicates that the keystore file is not found.

### Are you using any custom parameters or values?

```yaml
kafka:
  install: true
  listeners:
    client: 
      protocol: SASL_SSL
      sslClientAuth: "required"
    controller:
      protocol: SASL_PLAINTEXT
    interbroker:
      protocol: SASL_SSL
    external:
      protocol: SASL_SSL
  sasl:
    interBrokerMechanism: PLAIN
    controllerMechanism: PLAIN
    interbroker:
      user: broker_user
      password: qawsedrf!
    controller:  
      user: controller_user
      password: frdeswaq!
    client:
      users:
        - user1
      passwords: password
  tls:
    keystorePassword: 1q2w3e4r
    truststorePassword: 1q2w3e4r
    keyPassword: 1q2w3e4r
    existingSecret: kafka-secret
    jksKeystoreKey: "<base64_encoded_keystore_data>"
    endpointIdentificationAlgorithm: ""
    jksTruststoreKey: "<base64_encoded_truststore_data>"
  controllerQuorumVoters: 0@kafka:9093
  controller:
    replicaCount: 1
    controllerOnly: true
    automountServiceAccountToken: true
  broker:
    replicaCount: 1
    automountServiceAccountToken: true
  externalAccess:
    enabled: true
    autoDiscovery:
      enabled: true
  rbac:
    create: true
```

### Additional information

If someone is facing this issue, please guide me ASAP. I am stuck and have checked the documentation but did not find information related to this error. I am using a load balancer for external access. You can see my configuration in the values.yaml file below. If I am missing something, please guide me
