### ISSUE TITLE
[bitnami/redis] ReadOnlyError(\"You can't write against a read only replica.\") for redis helm chart

### ISSUE THREAD

**Issue by AjayEdupuganti** [bitnami/charts#26578]
### Name and Version

bitnami/redis 7.2.5

### What architecture are you using?

None

### What steps will reproduce the bug?

Hi, i have a kubernetes cluster spinned up with kuberadm.
now i have a redis cluster inside it which is conigured using redis-sentinel helm chart.
and there are 3 redis pods one of them is a master.
i am accessing it from my service via
redis-sentinel.default.svc.cluster.local
Now my requests from service are randomly going to master and worker. and throwing Readonly error
how can i configure it that all the SETs go to master and Gets go to worker?

### Are you using any custom parameters or values?
```
global:
  redis:
    password: "my-password"

architecture: "replication"
auth:
  enabled: true

replica:
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: "ebs-sc"
    size: 5Gi

sentinel:
  enabled: true
  replicas: 3

master:
  persistence:
    enabled: true
    storageClass: "ebs-sc"
    size: 5Gi

replica:
  persistence:
    enabled: true
    storageClass: "ebs-sc"
    size: 5Gi
```

### What is the expected behavior?

set requests go to master and get requests go to worker

### What do you see instead?

requests are going randomly to master and worker
