### ISSUE TITLE
[bitnami/thanos] Thanos receive with autoscaling cannot be used

### ISSUE THREAD

**Issue by irizzant** [bitnami/charts#26580]
### Name and Version

bitnami/thanos 15.6.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. deploy bitnami thanos with Receive
2. enable autoscaling with minReplica > 1
3. check the hashring configuration

### Are you using any custom parameters or values?

```yaml
objstoreConfig: |-
  type: s3
  config:
    bucket: thanos
    endpoint: minio.minio.svc.cluster.local:9000
    access_key: 
    secret_key: 
    insecure: true
    
query:
  replicaLabel: ["replica","receive_replica","thanos_ruler_replica"]
  dnsDiscovery:
    sidecarsService: thanos-ruler-operated
    sidecarsNamespace: monitoring
  pdb:
    create: true
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 128Mi
      cpu: 500m
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPU: 75
    targetMemory: 75
  ingress:
    enabled: true
    hostname: query.localtest.me

queryFrontend:
  enabled: true
  resources:
    limits:
      memory: 192Mi
    requests:
      memory: 128Mi
      cpu: 100m
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPU: 75
    targetMemory: 75
  pdb:
    create: true
  ingress:
    enabled: true
    hostname: thanos.localtest.me

bucketweb:
  enabled: true
  ingress:
    enabled: true
    hostname: bucketweb.localtest.me

compactor:
  enabled: true

storegateway:
  enabled: true
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPU: 75
    targetMemory: 75
  resourcesPreset: medium
  timePartitioning:
    sharded:
      enabled: true
      timePartitioning:
      # One store for data older than 6 weeks
      - min: ""
        max: -6w
      # One store for data newer than 6 weeks and older than 2 weeks
      - min: -6w
        max: -2w
      # One store for data newer than 2 weeks
      - min: -2w
        max: ""
  service:
    additionalHeadless: true # Create a headless service for the storegateway component

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

minio:
  enabled: true
  auth:
    rootPassword: 
    rootUser: 
  monitoringBuckets: thanos
  accessKey:
    password: 
  secretKey:
    password: 
  resources:
    limits:
      memory: 3Gi
    requests:
      memory: 1Gi
      cpu: 1000m

receive:
  enabled: true
  replicaLabel: receive_replica
  tsdbRetention: 15m
  extraFlags:
  - --receive.split-tenant-label-name="tenant_id"
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 1Gi
      cpu: 1000m
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPU: 75
    targetMemory: 75
  pdb:
    create: true
  service:
    additionalHeadless: true # Create a headless service for the receive component
  ingress:
    enabled: true
    hostname: receive.localtest.me
```

### What is the expected behavior?

Receive hashring should show the actual ring configuration

### What do you see instead?

```json
[
  {
    "endpoints": [
      "thanos-receive-0.thanos-receive-headless.monitoring.svc.cluster.local:10901"
    ]
  }
]
```
The `thanos-receive` ConfigMap only takes into account the first instance, because of [this code](https://github.com/bitnami/charts/blob/c4cff71074d8424cecd46dc8dffaac3a498e6a15/bitnami/thanos/templates/_helpers.tpl#L575C1-L582)
which only takes into account the default replica count 1.

I think this should be either documented, for example by adding a warning while installing the Helm chart, or forbidden by throwing an error.

Also see https://github.com/thanos-io/thanos/issues/7054
