### ISSUE TITLE
[ bitnami/kubernetes-event-exporter ] - exec /opt/bitnami/kubernetes-event-exporter/bin/kubernetes-event-exporter: exec format error

### ISSUE THREAD

**Issue by vadimprt** [bitnami/charts#26593]
### Name and Version

bitnami/kubernetes-event-exporter:1.7.0

### What steps will reproduce the bug?

Deploying helm chart `kubernetes-event-exporter:3.7.0` using `bitnami/kubernetes-event-exporter:1.7.0` image getting this error on pod logs:
```
exec /opt/bitnami/kubernetes-event-exporter/bin/kubernetes-event-exporter: exec format error
```

**Comment by carrodher** [comment]
Could you provide more info about how the Helm chart is being deployed? What are the parameters/values you're overriding?

**Comment by vadimprt** [comment]
hi, here is my config.yaml

`image:
  registry: "internal-docker-registry:5000"
  repository: "bitnami/kubernetes-event-exporter"

podLabels:
  access-to-logstash: "true"
  kube-api-access: "true"

secret:
  name: "kafka-certs"
  mountPath: "/secrets"
  SecretData:
    certificate.crt: 'secret'

config:
  route:
    routes:
    - match:
      - receiver: "kafka"
      drop:
      - type: "Normal"
        reason: "Logging"
        message: "Timer*"
  receivers:
  - name: "kafka"
    kafka:
      clientId: "kube-event"
      topic: "kube-event-monitoring"
      brokers:
      - "logstash1:9093"
      - "logstash2:9093"
      - "logstash3:9093"
      compressionCodec: "snappy"
      tls:
        enable: true
        insecureSkipVerify: false
        caFile: "/secrets/certificate.crt"
      layout:
        kind: "{{ .InvolvedObject.Kind }}"
        namespace: "{{ .InvolvedObject.Namespace }}"
        name: "{{ .InvolvedObject.Name }}"
        reason: "{{ .Reason }}"
        message: "{{ .Message }}"
        type: "{{ .Type }}"
        createdAt: "{{ .GetTimestampISO8601 }}"`

**Comment by carrodher** [comment]
Are you able to reproduce the issue using default values.yaml? Is the image present in your internal registry in sync with the image defined in the Helm chart?

**Comment by vadimprt** [comment]
will try with default values.yaml
the image in the internal registry is this one https://hub.docker.com/layers/bitnami/kubernetes-event-exporter/1.7.0-debian-12-r4/images/sha256-e63e0cf4ce41726e892cce5a4a398f5063d8b41eaa20d7257353d21120e8683b?context=explore

**Comment by vadimprt** [comment]
same with default values

**Comment by carrodher** [comment]
We're not able to reproduce the issue, so it may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, or configured in your specific environment.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by vadimprt** [comment]
it looks like it related to kubernetes-event-exporter.config 

```
receivers:
  - name: "kafka"
    kafka:
      clientId: "kube-event"
      topic: "kube-event-monitoring"
      brokers:
      - "logstash1:9093"
      - "logstash2:9093"
      - "logstash3:9093"
      compressionCodec: "snappy"
      tls:
        enable: true
        insecureSkipVerify: false
        caFile: "/secrets/certificate.crt"
      layout:
        kind: "{{ .InvolvedObject.Kind }}"
        namespace: "{{ .InvolvedObject.Namespace }}"
        name: "{{ .InvolvedObject.Name }}"
        reason: "{{ .Reason }}"
        message: "{{ .Message }}"
        type: "{{ .Type }}"
        createdAt: "{{ .GetTimestampISO8601 }}"
```

any documentation available for configuring kafka receiver?
