### ISSUE TITLE
[bitnami/kibana] Prometheus metrics not found

### ISSUE THREAD

**Issue by pbn4** [bitnami/charts#2671]
**Which chart**:
bitnami/kibana: 5.1.2

**Describe the bug**

I'm unable to get the prometheus to scrape kibana metrics:

![Zrzut ekranu 2020-05-26 o 20 41 26](https://user-images.githubusercontent.com/11684414/82938028-73cb5080-9f91-11ea-9064-0d7df3d37f97.png)

**To Reproduce**
Use following values for the chart:

```
    service:
      type: NodePort
    elasticsearch:
      hosts:
      - elasticsearch-elasticsearch-master
      port: 9200
    metrics:
      enabled: true
      service:
        annotations:
      serviceMonitor:
        enabled: true
        namespace: monitoring
```

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}```

**Additional context**

It still doesn't work when I fix the metrics path to: `/_prometheus/metrics` and try to cURL it from inside the cluster: 404 is returned.

**Comment by javsalgar** [comment]
Hi,

Thank you very much for reporting. I just created this PR that should fix the issue https://github.com/bitnami/charts/pull/2678

**Comment by pbn4** [comment]
Hey @javsalgar  did you check that a path fix actually makes it work? Because I fixed service monitor too and it still didn't work.

**Comment by javsalgar** [comment]
Hi,

Did you also install the prometheus metrics Kibana plugin? That could be related. Note that currently the chart will not install the plugin unless you specify it.

**Comment by pbn4** [comment]
Probably not, I'm going to check it then.

**Comment by pbn4** [comment]
@javsalgar I have a following flux helm release definition:

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kibana
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: kibana
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: kibana
    version: 5.2.6
  values:
    plugins:
    - https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.8.0/kibana-prometheus-exporter-7.8.0.zip
    service:
      type: NodePort
    elasticsearch:
      hosts:
      - elasticsearch-elasticsearch-master
      port: 9200
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
```

and unfortunately prometheus is not able to scrap metrics:

```
http://10.0.1.38:5601/_prometheus/metrics - server returned HTTP status 404 Not Found
```

Could you point me to how to install this metrics plugin?
