### ISSUE TITLE
[bitnami/postgresql-ha] 14.0.10 volumePermissions.enabled wont work

### ISSUE THREAD

**Issue by gabrielfsousa** [bitnami/charts#26817]
### Name and Version

bitmani/postgresql-ha 14.0.10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

i just enable volumePermissions

```yaml
volumePermissions:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/os-shell
    tag: 12-debian-12-r19
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  podSecurityContext:
    enabled: true
    seLinuxOptions: null
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
    seccompProfile:
      type: RuntimeDefault
  resourcesPreset: "nano"
  resources: {}
```

### What is the expected behavior?

init-chmod-data to change the permissions in **/bitnami/postgresql/data**
wont do nothing, pod has NO LOGS

### What do you see instead?

container postgresql has the error:

`chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted `
