### ISSUE TITLE
[bitnami/apisix] Standalone Mode Not Working

### ISSUE THREAD

**Issue by james-mchugh** [bitnami/charts#26881]
### Name and Version

bitnami/apisix:3.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. On K3S 1.27.6
2. Deploy the Helm Chart with the following values.yaml for standalone mode (from the README): (`helm install bitnami/apisix --values values.yaml`)
3. Observe init container errors:
```console
$ kubectl describe pod apisix-data-plane-77d8db7f9d-68ffg
...
Error: secret "apisix-control-plane-api-token" not found
...

```

### Are you using any custom parameters or values?

```yaml
controlPlane:
  enabled: false
ingressController:
  enabled: false
etcd:
  enabled: false
dataPlane:
  extraConfig:
    deployment:
      role_data_plane:
        config_provider: yaml
  extraVolumes:
    - name: routes
      configMap:
        name: apisix-routes
  extraVolumeMounts:
    - name: routes
      mountPath: /opt/bitnami/apisix/conf/apisix.yaml
      subPath: apisix.yaml
extraDeploy:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: apisix-routes
    data:
      apisix.yaml: |-
        routes:
          -
            uri: /hello
            upstream:
                nodes:
                    "127.0.0.1:1980": 1
                type: roundrobin
```

### What is the expected behavior?

Data plane pod runs as expected in standalone mode without init containers trying to mount secrets for disabled components.

### What do you see instead?

Data plane pod fails with an error as it is trying to mount a secret for the control-plane that doesn't exist.
```
 Error: secret "apisix-control-plane-api-token" not found
```

### Additional information

Looking at the _helpers.tpl file, it appears that the `APISIX_ADMIN_API_TOKEN` environment variable that mounts the control plane secret is always included in the `apisix.prepareApisixInitContainer` template without any conditional logic to remove it if the control-plane is disabled. This named template is always used when deploying the data plane Deployment, so even if the control-plane is disabled, it still adds the environment variable for the control-plane's secret.
