### ISSUE TITLE
Send reminders from cron job

### ISSUE THREAD

**Issue by felixfriedrich** [bitnami/charts#2693]
**Which chart**:
redmine

**Is your feature request related to a problem? Please describe.**
Redmine supports sending reminder mails, see https://www.redmine.org/projects/redmine/wiki/RedmineReminderEmails
If I exec into the running redmine container, I can execute the rake task from the link and mails are being sent. If I create a cronjob doing the same it doesn't work, because the database is not configured correctly.

**Describe the solution you'd like**
A template for a cronjob being executed once a day sending reminder mails.

**Describe alternatives you've considered**
Non

**Additional context**
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: redmine-reminder
spec:
  schedule: "16 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: redmine-reminder
            image: docker.io/bitnami/redmine:4.1.1-debian-10-r43
            command: ['/bin/sh', '-c', '/opt/bitnami/redmine && bundle exec rake generate_secret_token && bundle exec rake redmine:send_reminders days=7 users=3 -e production']
            env:
              - name: REDMINE_DB_MYSQL
                value: "mariadb.default.svc.cluster.local"
              - name: REDMINE_DB_NAME
                value: "redmine"
              - name: REDMINE_DB_USERNAME
                value: "bitnami"
              - name: REDMINE_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: redmine
                    key: external-db-password
```

I created a cron job on Kubernetes manually in order to see what I would need to create a PR for the helm chart. If I exec into the cronjob container, I can see that `/opt/bitnami/redmine/config/database.yml` is not set up correctly. Unlike in the running redmine container, which serves the web interface.

I tried to understand how the `database.yml` file is set up correctly, but I didn't get very far. Any help with this is highly appreciated.
Also, would you accept a PR for this feature? I would introduce options like this:

```
reminders:
  enabled: false
  schedule: 0 4 * * *
```
