### ISSUE TITLE
[bitnami/cert-manager] automatically setting 'class:nginx' to the challenge

### ISSUE THREAD

**Issue by vanhoutenbos** [bitnami/charts#27050]
### Name and Version

bitnami/cert-manager latests

### What architecture are you using?

None

### What steps will reproduce the bug?

Use your template of the ClusterIssuer with 1 small adjustment (I want to use `IngressClassName` instead of class as suggested by cert-manager to be better, https://cert-manager.io/docs/configuration/acme/http01/#ingressclassname, but when doing so something still adds `class: nginx` to my challenge resource and the cert-manager-controller doesn't like that.

This is my clusterissuer;

```yaml
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    # Replace the EMAIL-ADDRESS placeholder with the correct email account
    email: EMAIL-ADDRESS
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
```

### What do you see instead?

A challenge resource with only the ingressClassName as an attribute
