### ISSUE TITLE
[bitnami/sonarqube] When volumePermissions is enabled and defined other user, plugins failed to install

### ISSUE THREAD

**Issue by DanielFran** [bitnami/charts#27058]
### Name and Version

bitnami/sonarqube 5.2.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1 - Override default values user/group:
2 - Activate Volume Permissions
3 - It fails to create directory opt/bitnami/sonarqube/extensions/dowloads

### Are you using any custom parameters or values?
````yaml
global:
  storageClass: my-sonarqube-storage
sonarqubeUsername: admin-sonar
sonarqubePassword: mypassword
podSecurityContext:
  fsGroup: 1006
containerSecurityContext:
  runAsUser: 1006
  runAsGroup: 1006
caCerts:
  enabled: true
  secret: mysecret
  containerSecurityContext:
    runAsUser: 1006
    runAsGroup: 1006
plugins:
  containerSecurityContext:
    runAsUser: 1006
    runAsGroup: 1006
persistence:
  enabled: true
volumePermissions:
  enabled: true
postgresql:
  primary:
    podSecurityContext:
      fsGroup: 1006
    containerSecurityContext:
      runAsUser: 1006
      runAsGroup: 1006
````

### What is the expected behavior?

All directory are created with the specific user

### What do you see instead?

Deploy is failing
