### ISSUE TITLE
[bitnami/mlflow] Chart does not map S3 host to tracking pod in MLFLow

### ISSUE THREAD

**Issue by rojo1997** [bitnami/charts#27088]
### Name and Version

bitnami/mlflow 1.4.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am using the GCP Kubernetes service and trying to store MLFlow artifacts in Google Storage.

### Are you using any custom parameters or values?

```yaml
tracking:
  enabled: true
  replicaCount: 1
  auth:
    enabled: true
    existingSecret: "mlflow"
    existingSecretUserKey: "MLFLOW_TRACKING_USERNAME"
    existingSecretPasswordKey: "MLFLOW_TRACKING_PASSWORD"
  service:
    type: ClusterIP
    ports:
      http: 80
  persistence:
    enabled: true
    mountPath: /bitnami/mlflow
    size: 8Gi
postgresql:
  enabled: true
  auth:
    username: bn_mlflow
    password: ""
    database: bitnami_mlflow
minio:
  enabled: false
externalS3:
  host: "storage.googleapis.com"
  port: 443
  existingSecret: "gcp-s3"
  existingSecretAccessKeyIDKey: "ACCESS_KEY"
  existingSecretKeySecretKey: "SECRET"
  protocol: "https"
  bucket: '{{ .Values | get "mlflow.tracking.externalS3.bucket" }}'
  serveArtifacts: true
```

### What is the expected behavior?

MLFlow is able to save the artifacts in Google Storage.

### What do you see instead?

MLFlow is not recognising the Google Storage host and is trying to connect to AWS S3.

### Additional information

I managed to solve it by adding the following environment variable:
```yaml
tracking:
  extraEnvVars:
    - name: MLFLOW_S3_ENDPOINT_URL
      value: "https://storage.googleapis.com"
```
