### ISSUE TITLE
[bitnami/elasticsearch] misbehavior  between the service name declaration and ingress backend name

### ISSUE THREAD

**Issue by ihiverlet** [bitnami/charts#27093]
### Name and Version

bitnami/elasticsearch 21.2.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

helm template -f values.yaml bitnami/elasticsearch --generate-name

### Are you using any custom parameters or values?

```yaml
global:
  kibanaEnabled: true
fullnameOverride: elastic-elasticsearch
ingress:
  enabled: true
  hostname: change.me
```

### What is the expected behavior?

The service name and ingress backend declaration should be the same

### What do you see instead?

```
# Source: elasticsearch/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elastic-elasticsearch
  namespace: "user-inesh"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/version: 8.14.0
    helm.sh/chart: elasticsearch-21.2.1
    app.kubernetes.io/component: elasticsearch
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: elastic-elasticsearch
                port:
                  name: tcp-rest-api
      host: change.me
```
```
# Source: elasticsearch/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-elasticsearch
  namespace: "user-inesh"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/version: 8.14.0
    helm.sh/chart: elasticsearch-21.2.1
    app.kubernetes.io/component: coordinating-only
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-rest-api
      port: 9200
      targetPort: rest-api
      nodePort: null
    - name: tcp-transport
      port: 9300
      nodePort: null
  selector:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/component: coordinating-only
```

### Additional information

We can see that the backend definition in the ingress only refers to the "common.names.fullname" template.

https://github.com/bitnami/charts/blob/901264004c90fda66a5ea024235b28ecc03b4a21/bitnami/elasticsearch/templates/ingress.yaml#L33

However, in the service definition "elasticsearch.service.name" is called and when the kibana is enabled it's not the same result.

https://github.com/bitnami/charts/blob/901264004c90fda66a5ea024235b28ecc03b4a21/bitnami/elasticsearch/templates/service.yaml#L9

https://github.com/bitnami/charts/blob/45e037e3de4988c8b92821a3f60afce594a91d54/bitnami/elasticsearch/templates/_helpers.tpl#L49
