### ISSUE TITLE
[bitnami/thanos] thanos servicemonitors are invalid in dual-stack mode

### ISSUE THREAD

**Issue by antonincms** [bitnami/charts#27103]
### Name and Version

bitnami/thanos 15.6.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hello, 

When deploying thanos in dual-stack mode and a serviceMonitor, with the provided values the "thanos-receive" service point to the thanos-receive-distributor pods and the "thanos-receive-headless" service point to the thanos-receive pods (which I guess was done to not change the URL of data ingestion). 

Unfortunately as the "thanos-receive" serviceMonitor point to the "thanos-receive" and the  "thanos-receive-distributor" serviceMonitor does not point to any service, the thanos-receive is not scrapped and the receive-distributor scrapped by the wrong job.

### Are you using any custom parameters or values?

```yaml
receive:
  enabled: true
  mode: dual-mode # Split receiver in distributor and receiver
  service:
    additionalHeadless: true # Required for hashring to work
receiveDistributor:
  enabled: true
```

### What is the expected behavior?

The "thanos-receive" serviceMonitor should instead point to the "thanos-receive-headless" service, and the "thanos-receive-distributor" serviceMonitor should point to the "thanos-receive" service. 

### What do you see instead?

The "thanos-receive" serviceMonitor point to the "thanos-receive" service, scrapping "thanos-receive-distributor" pods, and the "thanos-receive-distributor" serviceMonitor does not point to any service.

### Additional information

I think it could be fixed by changing the labels of the "thanos-receive" service to be `app.kubernetes.io/component: receive-distributor` instead of `app.kubernetes.io/component: receive` and add `prometheus-operator/monitor: "true"` to thanos-receive-headless.
