### ISSUE TITLE
[bitnami/mysql] can not started

### ISSUE THREAD

**Issue by charnet1019** [bitnami/charts#27106]
### Name and Version

bitnami/mysql 9.23.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Just change some values of values.yaml.
2. helm install
3. Enter mysql contaienr then exec `/opt/bitnami/scripts/mysql/entrypoint.sh /opt/bitnami/scripts/mysql/run.sh`
4. mysql can not started.

### Are you using any custom parameters or values?

```yaml
global:
  storageClass: local-path

diagnosticMode:
  enabled: true

image:
  debug: true

architecture: standalone

auth:
  rootPassword: xxxxxx
  createDatabase: false

primary:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  startupProbe:
    enabled: true
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 10
    successThreshold: 1
```

### What is the expected behavior?

mysql start success.

### What do you see instead?

```
I have no name!@mysql-qxaymx-0:/$ /opt/bitnami/scripts/mysql/entrypoint.sh /opt/bitnami/scripts/mysql/run.sh
mysql 01:43:09.63 INFO  ==> 
mysql 01:43:09.64 INFO  ==> Welcome to the Bitnami mysql container
mysql 01:43:09.64 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
mysql 01:43:09.65 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
mysql 01:43:09.66 INFO  ==> 
mysql 01:43:09.67 DEBUG ==> Copying files from /opt/bitnami/mysql/conf.default to /opt/bitnami/mysql/conf
mysql 01:43:09.68 INFO  ==> ** Starting MySQL setup **
mysql 01:43:09.72 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 01:43:09.73 INFO  ==> Initializing mysql database
mysql 01:43:09.74 DEBUG ==> Ensuring expected directories/files exist
mysql 01:43:09.76 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 01:43:09.77 DEBUG ==> Cleaning data directory to ensure successfully initialization
mysql 01:43:09.77 INFO  ==> Installing database



mysql 01:44:16.10 INFO  ==> Starting mysql in background
mysql 01:44:20.13 DEBUG ==> Executing SQL command:
select 1
1
mysql 01:44:20.16 INFO  ==> Configuring authentication
mysql 01:44:20.16 DEBUG ==> Executing SQL command:
DELETE FROM mysql.user WHERE user not in ('mysql.sys','mariadb.sys');
mysql 01:44:20.24 DEBUG ==> Configuring root user credentials
mysql 01:44:20.25 DEBUG ==> Executing SQL command:
-- create admin user
create user 'root'@'%' identified by "xxxxxx";
grant all on *.* to 'root'@'%' with grant option;
flush privileges;
mysql 01:44:20.65 DEBUG ==> removing the unknown user
mysql 01:44:20.67 DEBUG ==> Executing SQL command:
select Host from user where User='';
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql 01:44:20.80 INFO  ==> Running mysql_upgrade
mysql 01:44:20.81 INFO  ==> Stopping mysql
mysql 01:44:23.83 DEBUG ==> Waiting for mysql to unlock db files
Cannot find socket's device number.
Cannot stat /bitnami/mysql/data/ibdata1: Invalid argument
mysql 01:44:23.86 INFO  ==> Starting mysql in background


find: '/docker-entrypoint-startdb.d/': No such file or directory
mysql 01:46:04.28 INFO  ==> Stopping mysql
mysql 01:46:14.34 DEBUG ==> Waiting for mysql to unlock db files
Cannot find socket's device number.
Cannot stat /bitnami/mysql/data/ibdata1: Invalid argument
mysql 01:46:14.37 INFO  ==> Stopping mysql
mysql 01:46:24.43 DEBUG ==> Waiting for mysql to unlock db files
Cannot find socket's device number.
Cannot stat /bitnami/mysql/data/ibdata1: Invalid argument
mysql 01:46:24.46 INFO  ==> ** MySQL setup finished! **

mysql 01:46:24.54 INFO  ==> ** Starting MySQL **
```
