### ISSUE TITLE
Cannot set valid `loadBalancerSourceRanges` on K8s cluster

### ISSUE THREAD

**Issue by Setsushin** [bitnami/charts#27138]
### Name and Version

bitnami/spark

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set following configs in `values.yaml` (dummy example)
```yaml
# In values.yaml
service:
  type: LoadBalancer
  annotations:
    cloud.google.com/load-balancer-type: External
  allocateLoadBalancerNodePorts: true
  loadBalancerSourceRanges:
  - 1.1.1.1/32
  - 2.2.2.2/32
```
2. Run `helm upgrade --install spark bitnami/spark -f values.yaml`
3. Got the error

### Are you using any custom parameters or values?

```yaml
service:
  type: LoadBalancer
  annotations:
    cloud.google.com/load-balancer-type: External
  allocateLoadBalancerNodePorts: true
  loadBalancerSourceRanges:
  - 1.1.1.1/32
  - 2.2.2.2/32
```

### What is the expected behavior?

An external LoadBalancer service with corresponding IP source range should be created.

### What do you see instead?
```
❯ helm upgrade --install spark bitnami/spark -f values.yaml
Error: UPGRADE FAILED: cannot patch "spark-master-svc" with kind Service: Service "spark-master-svc" is invalid: spec.LoadBalancerSourceRanges: Invalid value: "[1.1.1.1/32 2.2.2.2/32]": must be a list of IP ranges. For example, 10.240.0.0/24,10.250.0.0/24 
```
### Additional information

I tried to use
```
loadBalancerSourceRanges: "[1.1.1.1/32, 2.2.2.2/32]"
```
as instead and it passed.
