### ISSUE TITLE
[bitnami/milvus] Cannot connect milvus with externalS3

### ISSUE THREAD

**Issue by rajan123456** [bitnami/charts#27139]
### Name and Version

bitnami/milvus 8.2.2

### What architecture are you using?

None

### What steps will reproduce the bug?

Deploy the latest milvus chart with externalS3

### Are you using any custom parameters or values?

```yaml
minio:
  enabled: false

externalS3:
  host: myspecialhost
  port: 9000
  accessKeyID: "admin"
  accessKeySecret: "password"
  protocol: "http"
  bucket: "milvus"
  rootPath: "file"
```

### What is the expected behavior?

Milvus should be able to startup and connect to externalS3

### What do you see instead?

Milvus fails to install and complains that the secret (Release-Name)-externals3 is not found.

### Additional information

milvus/templates/externals3-secret.yaml refers to .Values.enableS3 instead of .Values.externals3
