### ISSUE TITLE
RabbitMQ: Messaging topology operator - Status information missing from OperatorPolicy controller

### ISSUE THREAD

**Issue by DanielePalaia** [bitnami/charts#27146]
### Name and Version

bitnami/rabbitmq-cluster-operator:4.3.6

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Create a test RabbitMQ cluster:
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqcluster-sample
spec:
  replicas: 1
  resources:
    requests:
      cpu: "0.5"
      memory: 1Gi
    limits:
      cpu: "0.5"
      memory: 1Gi
  service:
    type: LoadBalancer
```
2. Create a simple policy:
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: policy-example
spec:
  name: transient # name of the policy
  pattern: "^amq." # regex used to match queues and exchanges
  applyTo: "queues" # set to 'queues', 'exchanges', or 'all'
  definition: # policy definition
    expires: 1800000
  rabbitmqClusterReference:
    name: rabbitmqcluster-sample  # rabbitmqCluster must exist in the same namespace as this resource
```
3. Describe it
```console
$ kubectl describe policy
Name:         policy-example
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  rabbitmq.com/v1beta1
Kind:         Policy
Metadata:
  Creation Timestamp:  2024-06-13T08:26:54Z
  Finalizers:
    deletion.finalizers.policies.rabbitmq.com
  Generation:        1
  Resource Version:  2651794
  UID:               231ec1ba-3ce7-469e-a361-092261f6de49
Spec:
  Apply To:  queues
  Definition:
    Expires:  1800000
  Name:       transient
  Pattern:    ^amq.
  Priority:   0
  Rabbitmq Cluster Reference:
    Name:  rabbitmqcluster-sample
  Vhost:   /
Status:
  Conditions:
    Last Transition Time:  2024-06-13T08:26:54Z
    Reason:                SuccessfulCreateOrUpdate
    Status:                True
    Type:                  Ready
  Observed Generation:     1
Events:
  Type    Reason             Age              From               Message
  ----    ------             ----             ----               -------
  Normal  SuccessfulDeclare  9s (x3 over 9s)  policy-controller  Successfully declare policy
```
As you can see the Status info are there

4. Create an operatorpolicy instead
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: OperatorPolicy
metadata:
  name: operator-policy
spec:
  name: my-operator-policy-6 # name of the operator policy
  pattern: "pippo"
  definition: # policy definition
    expires: 1800000
  rabbitmqClusterReference:
    name: rabbitmqcluster-sample # rabbitmqCluster must exist in the same namespace as this resource
```

5. If you describe it you will see the Status field is not there
```console
$ kubectl describe operatorpolicy
Name:         operator-policy
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  rabbitmq.com/v1beta1
Kind:         OperatorPolicy
Metadata:
  Creation Timestamp:  2024-06-13T08:25:08Z
  Finalizers:
    deletion.finalizers.operatorpolicies.rabbitmq.com
  Generation:        1
  Resource Version:  2650616
  UID:               22fcbb93-d118-42de-ac2e-f465fab8962b
Spec:
  Apply To:  queues
  Definition:
    Expires:  1800000
  Name:       my-operator-policy-6
  Pattern:    pippo
  Priority:   0
  Rabbitmq Cluster Reference:
    Name:  rabbitmqcluster-sample
  Vhost:   /
Events:
  Type    Reason             Age                  From                        Message
  ----    ------             ----                 ----                        -------
  Normal  SuccessfulDeclare  118s (x2 over 119s)  operator-policy-controller  Successfully declare operatorpolicy
```

I tried to investigate but the CRD seems updated to me.
If we do the same scenario using the default operator manifests I don't have this issue.

### What is the expected behavior?

The status information of the OperatorPolicy should be present. 

### What do you see instead?

The status information of the OperatorPolicy controller is not present
