### ISSUE TITLE
[bitnami/mongodb] Logging to stdout no longer default

### ISSUE THREAD

**Issue by lasseoe** [bitnami/charts#27150]
### Name and Version

bitnami/mongodb 14.12.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy MongoDB chart >=14.12.0

### Are you using any custom parameters or values?

No, happens with the most basic setup possible.

### What is the expected behavior?

Logging to stdout instead of /opt/bitnami/mongodb/logs/mongodb.log

### What do you see instead?

In 14.12.0 a new empty-dir was introduced, MongoDB now logs to a file instead of stdout, meaning the default behavior has changed.

```yaml
  - name: empty-dir
    mountPath: /opt/bitnami/mongodb/logs
    subPath: app-logs-dir
```

### Additional information

I see no way of overriding this behavior, except by perhaps adding a custom configuration section, ie.

```yaml
configuration: |-
  systemLog:
    quiet: false
```

but no matter how I structure it, MongoDB errors out immediately.

There's no mention of this change in the commit message, README or CHANGELOG.
