### ISSUE TITLE
[bitnami/airflow] liveness probe fail on worker pod

### ISSUE THREAD

**Issue by VincentDugard** [bitnami/charts#27196]
### Name and Version

bitnami/airflow 18.3.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Run the chart
2. airflow-worker liveness probe fail => "Liveness probe failed: sh: 1: source: not found"

### Are you using any custom parameters or values?

```yaml
worker:
  containerSecurityContext:
    enabled: true
    runAsGroup: 0
    readOnlyRootFilesystem: false
  extraEnvVars:
    - name: AIRFLOW__LOGGING__LOG_FILENAME_TEMPLATE
      value: dag_tasks.log
```

### What is the expected behavior?

liveness probe should work

### What do you see instead?

liveness probe doesn't work and container restart in loop

### Additional information

I think the problem come from this PR : https://github.com/bitnami/charts/pull/25971
But if that's the case it's weird nobody opened an issue before.
