### ISSUE TITLE
Ghost Ingress Annotations

### ISSUE THREAD

**Issue by apenney** [bitnami/charts#2722]
**Which chart**: ghost

**Describe the bug**

When I add any ingress annotations, in any way I've tried, such as:

```
ingress:
  enabled: true
  annotations:
    test: hmm
```

Or:

```
ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:us-east-2:x:certificate/x'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect","RedirectConfig":{"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
```

They fail to render with:

```
Error: YAML parse error on ghost/templates/ingress.yaml: error converting YAML to JSON: yaml: line 10: mapping values are not allowed in this context
helm.go:84: [debug] error converting YAML to JSON: yaml: line 10: mapping values are not allowed in this context
YAML parse error on ghost/templates/ingress.yaml
```
If I use `helm template g bitnami/ghost -f ./values.yaml --debug` I see:

```
metadata:
  name: g-ghost
  labels:
    app.kubernetes.io/name: ghost
    helm.sh/chart: ghost-10.0.7
    app.kubernetes.io/instance: g
    app.kubernetes.io/managed-by: Helm
  annotations:    test: hmm
    kubernetes.io/tls-acme: "true"
```

It seems to lose a newline, and then cram the first annotation onto the same line as 'annotations:'

**To Reproduce**

Here's my values.yaml:

```
# Don't allow empty db passwords!
allowEmptyPassword: false
ghostHost: x
ghostPath: /blog/
ghostUsername: admin@x
ghostEmail: engineering@x
ingress:
  enabled: true
  annotations:
    test: hmm
  hosts:
    - name: x.x
      path: /blog
  certManager: true
# External database to use
externalDatabase:
  host: xxx
  port: 3306
  user: ghost
  database: ghost
# We use an external database
mariadb:
  enabled: false
service:
  type: ClusterIP
```

`helm template g bitnami/ghost -f ./values.yaml --debug` should reproduce this

**Expected behavior**
The template to not blow up on me!

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
helm template g bitnami/ghost -f ./values.yaml --debug
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-21T01:25:41Z", GoVersion:"go1.13.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
