### ISSUE TITLE
[bitnami/argo-workflows] pods forbidden cannot patch resource "pods"

### ISSUE THREAD

**Issue by jgagnon44** [bitnami/charts#27439]
### Name and Version

bitnami/charts/argo-workflows 9.1.3

### What architecture are you using?

None

### What steps will reproduce the bug?

In my local Docker Desktop Kubernetes cluster context, I installed this Helm chart as follows:
```console
$ kubectl config current-context
docker-desktop

$ helm install jmg-test . -n argo-workflows --create-namespace -f local-values.yaml
NAME: jmg-test
LAST DEPLOYED: Tue Jun 18 12:51:47 2024
NAMESPACE: argo-workflows
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

### Are you using any custom parameters or values?

```yaml
argo-workflows:
  controller:
    serviceAccount:
      create: true
    workflowNamespaces:
      - argo-workflows
  
  server:
    auth:
      mode: server
    serviceAccount:
      create: true
  
  workflows:
    serviceAccount:
      create: true

  postgresql:
    enabled: false

  mysql:
    enabled: false
  
  externalDatabase:
    enabled: false
  
  ingress:
    enabled: true
    hostname: argo.devhost.beast-code-demo.com
    ingressClassName: nginx
```

### What is the expected behavior?

I'm not familiar with Argo Workflows or how the application is intended to be used. I simply opened the app and attempted to create a new workflow in the namespace I set up and provided. After a few moments, an error message was displayed. I then checked the app pod logs to see if there was anything to see.

![image](https://github.com/bitnami/charts/assets/56738211/f03dbe9c-9d79-4612-aa6e-49e1275c3955)

### What do you see instead?

The chart appears to have been successfully deployed and I can bring up the app (by port forwarding, not sure why ingress is not working) and attempt to create a new workflow in the namespace I have set up. I'm using the Lens application to watch the activity on the cluster. I can see a new pod created, but it quickly dies and disappears. When I look in the pod log for the controller, I see various error messages. See the attached log.

[jmg-test-argo-workflows-controller-846d9fddf5-xq5xx.log](https://github.com/user-attachments/files/15891008/jmg-test-argo-workflows-controller-846d9fddf5-xq5xx.log)

### Additional information

I captured the output from installing the Helm chart with the `--debug` flag set.

[debug.log](https://github.com/user-attachments/files/15891063/debug.log)
