### ISSUE TITLE
DokuWiki: Cannot access after helm upgrade

### ISSUE THREAD

**Issue by runar-indico** [bitnami/charts#2743]
**Which chart**:
 dokuwiki-6.0.18

**Describe the bug**
Cannot access the container via browser, after simple upgrade.

 I believe it may be due to some traffic being sent ass https to port 80 or similar, since the container prints this in the logs for every request:

```
10.244.1.116 - - [03/Jun/2020:11:20:12 +0000] "\x16\x03\x01" 400 226
```

**To Reproduce**
I did a simple upgrade, by only adding an annotation with `nginx.ingress.kubernetes.io/proxy-body-size: 100m`, along with my previous annotations. After that, I am unable to access the docu-container.

**Expected behavior**

Expected to reach the dokuwiki-container from the browser.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10", GitCommit:"e3c134023df5dea457638b614ee17ef234dc34a6", GitTreeState:"clean", BuildDate:"2019-07-08T03:40:54Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

Upgraded with this command: 

```bash
 helm upgrade dokuwiki -n docs -f docuwiki.yml bitnami/dokuwiki
```

Here is the yaml-file i used:

```yml
dokuwikiUsername: user
dokuwikiPassword: abc123
dokuwikiEmail: apps@example.com
dokuwikiFullName: User Name
dokuwikiWikiName: Docs
service:
  type: ClusterIP
ingress:
  hosts:
  - name: docs.indico.dev
    tls: true
    annotations: 
      kubernetes.io/ingress.class: "nginx"
      nginx.org/mergeable-ingress-type: "minion"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/proxy-body-size: 100m
persistence:
  enabled: true
  dokuwiki:
    storageClass: "nfs-client"
    accessMode: ReadWriteOnce
    size: 8Gi
```
