### ISSUE TITLE
redis replicas template does not have variable substitution for redis-data mountPath

### ISSUE THREAD

**Issue by tlittlefield** [bitnami/charts#27446]
### Name and Version

bitnami/redis 19.5.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We were attempting to deploy redis in k8s using local storage for both the master and replicas pods.  The master pod correctly mounted the local file from the specified path. The replicas pod went into crashloopbackoff when trying to access /data.  /data is not the location specified in the PVC.  After digging into the charts, we noticed a discrepancy between master and replicas.

master / application.yaml at about line 241:
```yaml
- name: redis-data
  mountPath: {{ .Values.master.persistence.path }}
```    
replicas / application.yaml at about line 261:
```yaml
- name: redis-data
  mountPath: /data
```
`/data` is hardcoded into the template and should be parameterized, similar to the master application.yaml

We worked around the problem by editing the statefulset and manually updating the path then killing the pod to allow it to be restarted with the new config.

### Are you using any custom parameters or values?

We are using a values.yaml file with:
```yaml
persistence:
    accessModes:
    - ReadWriteOnce
    annotations: {}
    dataSource: {}
    enabled: true
    existingClaim: "redis-data-redis-replicas-0"
    labels: {}
    medium: ""
    path: /home/k8s-volumes/redis-replicas
    selector: {}
    size: 8Gi
    sizeLimit: ""
    storageClass: local-storage
    subPath: ""
    subPathExpr: ""
```

### What is the expected behavior?

The pod schedules successfully, mounting the local data with the correct path.

### What do you see instead?

The redis replicas pod goes into crashloopbackoff with a panic on accessing /data, which does not exist.
