### ISSUE TITLE
[bitnami/argo-cd] Argo-CD Cluster Roles to support multiple namespaces, Dynamic Cluster Distribution issue with controller.

### ISSUE THREAD

**Issue by Jeremy-Boyle** [bitnami/charts#27449]
### Name and Version

bitnami/argo-cd 6.4.8

### What is the problem this feature will solve?

This will bring the bitnami helm chart for argo-cd to support multiple namespaces by providing cluster roles for services that need them and allow configuration from helm user.

## Adding cluster roles for the following:

```yaml
applicationSet:
  # Default value false
  clusterAdminAccess: false
  clusterRoleRules: []

notifications:
  # Default value false
  clusterAdminAccess: false
  clusterRoleRules: []

repoServer:
  # Default value false
  clusterAdminAccess: false
  clusterRoleRules: []

server:
  clusterAdminAccess: true
  clusterRoleRules: []
```

### Upstream examples (Check Mark = PR work done):
- [x] [applicationset](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-applicationset/clusterrole.yaml)
- [x] [notifications](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-notifications/clusterrole.yaml)
- [x] [repoServer](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-repo-server/clusterrole.yaml)
- [x] [server](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-server/clusterrole.yaml)
  - This needs to be updated this currently has a cluster role, however there's no way to disable this access and given by default. Default is to give cluster admin access which should not be the case unless explicitly allowed.

### What:
When enabling [Dynamic Cluster Distribution](https://argo-cd.readthedocs.io/en/stable/operator-manual/dynamic-cluster-distribution/#enabling-dynamic-distribution-of-clusters) env on the controller it causes a issue with the application-set not being able to find the deployment name for the app-controller when multi-namespace is used

By default argo-cd looks for argocd-application-controller, this causes the applicationset to fail unless the provided env is set on the controller [ARGOCD_APPLICATION_CONTROLLER_NAME](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-application-controller/deployment.yaml#L83)

### Changes:
Adding the ARGOCD_APPLICATION_CONTROLLER_NAME as a default env to be made providing the templated name to the controller in the templates [here](https://github.com/bitnami/charts/blob/main/bitnami/argo-cd/templates/application-controller/deployment.yaml#L166)

## Additionally fix:

PR:
- #27108

## Documentaion for setting up any-namespace
New documentation in read-me for setting up any-namespace configurtation, just explaining what values to set to allow this. Links to upstream will be provided in this documentation.

### Upstream documentation:
- [Applications in any namespace](https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/)
- [ApplicationSet in any namespace](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Appset-Any-Namespace/)
- [Notification in any namespace](https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/#namespace-based-configuration)
- [Reconfigure Argo CD to allow certain namespaces](https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/#reconfigure-argo-cd-to-allow-certain-namespaces)
- [Dynamic Cluster Distribution](https://argo-cd.readthedocs.io/en/stable/operator-manual/dynamic-cluster-distribution/)

## Using extraDeploy to provide the cluster roles and bindings in the values file, and controller.extraEnvVars

```yaml
# This requires makes for a unessaryly long values file
# Also, requires you know the templated service account name for each service inside the cluster rolebinding
extraDeploy:
- CLUSTER-ROLE-FOR-applicationset
- CLUSTER-ROLEBINDING-FOR-applicationset
- CLUSTER-ROLE-FOR-notifications
- CLUSTER-ROLEBINDING-FOR-notifications
- CLUSTER-ROLE-FOR-repoServer
- CLUSTER-ROLEBINDING-FOR-repoServer
- CLUSTER-ROLE-FOR-server
- CLUSTER-ROLEBINDING-FOR-server

controller:
  extraEnvVars:
  - name: ARGOCD_APPLICATION_CONTROLLER_NAME
    value: MANUALLY-SETTING-NAME-OF-TEMPLATED-DEPLOYMENT-NAME
    
```
