### ISSUE TITLE
[bitnami/rabbitmq] Failed to connect to 127.0.0.1 port 15672 after 0 ms: Couldn't connect to server

### ISSUE THREAD

**Issue by smietanka** [bitnami/charts#27460]
### Name and Version

bitnami/rabbitmq 14.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Write yaml file with values for helm chart with these properties:
```yaml
auth:
  username: "admin"
  password: "admin"
  erlangCookie: "admin"

# remove this when we will not figure out why, liveness and readiness probes are failing inside this cluster
# readinessProbe:
#   enabled: false
# livenessProbe:
#   enabled: false

service:
  type: NodePort
  nodePorts:
    manager: 31772
    amqp: 31874
    amqpTls: 31873
    dist: 30772
    epmd: 30469
    metrics: 30519
  extraPorts:
    - name: mqtt
      port: 1883
      nodePort: 31883
    - name: mqtts
      port: 8883
      nodePort: 31884

metrics:
  enabled: true

extraConfiguration: |
  mqtt.listeners.ssl.default = 8883
  mqtt.listeners.tcp.default = 1883

extraPlugins: rabbitmq_mqtt

initScripts:
  enable_mqtt_v5_feature_flag.sh: |
    #!/bin/sh
    # should be fine according to https://github.com/bitnami/charts/issues/17070 
    ! is_rabbitmq_running && rabbitmq_start_bg

    rabbitmqctl enable_feature_flag mqtt_v5

extraContainerPorts:
  - name: mqtt
    port: 1883
    containerPort: 1883
  - name: mqtts
    port: 8883
    containerPort: 8883

networkPolicy:
  extraIngress:
    - ports:
      - protocol: TCP
        port: 1883
      - protocol: TCP
        port: 8883

resources:
  requests:
    memory: 500Mi
    cpu: 50m
  limits:
    memory: 2000Mi
    cpu: 500m
```

2. run command `helm upgrade -i -f ./helm/broker/broker-values.yaml broker bitnami/rabbitmq --version 14.4.4`
3. I am getting an error 
```
W0620 07:49:42.883264   55484 warnings.go:70] unknown field "spec.template.spec.containers[0].ports[5].port"
W0620 07:49:42.883786   55484 warnings.go:70] unknown field "spec.template.spec.containers[0].ports[6].port"
Error: UPGRADE FAILED: cannot patch "endpoint-broker-rabbitmq-headless" with kind Service: Service "endpoint-broker-rabbitmq-headless" is invalid: [spec.ports[4].nodePort: Forbidden: may not be used when `type` is 'ClusterIP', spec.ports[5].nodePort: Forbidden: may not be used when `type` is 'ClusterIP']
```

4. When run command `helm upgrade -i -f ./helm/broker/broker-values.yaml broker bitnami/rabbitmq --version 14.0.0`
5. Pod is created with similar warnings from helm notes, and readiness and liveness probes are not working.

### Are you using any custom parameters or values?

Nope

### What is the expected behavior?

Pod is running with liveness and readiness probes OK

### What do you see instead?

For 14.4.4 helm chart version I am gettings for installed helm
```
W0620 07:49:42.883264   55484 warnings.go:70] unknown field "spec.template.spec.containers[0].ports[5].port"
W0620 07:49:42.883786   55484 warnings.go:70] unknown field "spec.template.spec.containers[0].ports[6].port"
Error: UPGRADE FAILED: cannot patch "endpoint-broker-rabbitmq-headless" with kind Service: Service "endpoint-broker-rabbitmq-headless" is invalid: [spec.ports[4].nodePort: Forbidden: may not be used when `type` is 'ClusterIP', spec.ports[5].nodePort: Forbidden: may not be used when `type` is 'ClusterIP']
```

But when I am using 14.0.0, the pod is created but its not fully running from context of cluster because of 
```
Name:             endpoint-broker-rabbitmq-0
Namespace:        default
Priority:         0
Service Account:  endpoint-broker-rabbitmq
Node:             lp-5cg327217j/172.18.250.103
Start Time:       Thu, 20 Jun 2024 07:49:57 +0200
Labels:           app.kubernetes.io/instance=endpoint-broker
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=rabbitmq
                  app.kubernetes.io/version=3.13.1
                  apps.kubernetes.io/pod-index=0
                  controller-revision-hash=endpoint-broker-rabbitmq-58484c7974
                  helm.sh/chart=rabbitmq-14.0.0
                  statefulset.kubernetes.io/pod-name=endpoint-broker-rabbitmq-0
Annotations:      checksum/config: 3711e24796d690aa5c29916450604129ecea268f7b837fa779f10998c51665f0
                  checksum/secret: 3a992cebbdb3419e283c78544f91df3901eb8dbe77a97d6cb3d5e97bac78e06a
                  prometheus.io/port: 9419
                  prometheus.io/scrape: true
Status:           Running
IP:               10.42.0.203
IPs:
  IP:           10.42.0.203
Controlled By:  StatefulSet/endpoint-broker-rabbitmq
Containers:
  rabbitmq:
    Container ID:    docker://dd5cce847f8ce8b9cc176f4f43c63d2d0c9773b99ba9943694219731aa5cd43b
    Image:           docker.io/bitnami/rabbitmq:3.13.1-debian-12-r0
    Image ID:        docker-pullable://bitnami/rabbitmq@sha256:8349abcac1b655162c520b5c46d699cd3c721508ae6c2dc3183a3c63a9491b30
    Ports:           5672/TCP, 25672/TCP, 15672/TCP, 4369/TCP, 9419/TCP, 1883/TCP, 8883/TCP
    Host Ports:      0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    SeccompProfile:  RuntimeDefault
    State:           Running
      Started:       Thu, 20 Jun 2024 07:54:01 +0200
    Last State:      Terminated
      Reason:        Error
      Exit Code:     1
      Started:       Thu, 20 Jun 2024 07:51:53 +0200
      Finished:      Thu, 20 Jun 2024 07:53:48 +0200
    Ready:           False
    Restart Count:   2
    Limits:
      cpu:     500m
      memory:  2000Mi
    Requests:
      cpu:      50m
      memory:   500Mi
    Liveness:   exec [sh -ec curl -f --user admin:$RABBITMQ_PASSWORD 127.0.0.1:15672/api/health/checks/virtual-hosts] delay=120s timeout=20s period=30s #success=1 #failure=6
    Readiness:  exec [sh -ec curl -f --user admin:$RABBITMQ_PASSWORD 127.0.0.1:15672/api/health/checks/local-alarms] delay=10s timeout=20s period=30s #success=1 #failure=3
    Environment:
      BITNAMI_DEBUG:              false
      MY_POD_IP:                   (v1:status.podIP)
      MY_POD_NAME:                endpoint-broker-rabbitmq-0 (v1:metadata.name)
      MY_POD_NAMESPACE:           default (v1:metadata.namespace)
      RABBITMQ_FORCE_BOOT:        no
      RABBITMQ_NODE_NAME:         rabbit@$(MY_POD_NAME).endpoint-broker-rabbitmq-headless.$(MY_POD_NAMESPACE).svc.cluster.local
      RABBITMQ_MNESIA_DIR:        /opt/bitnami/rabbitmq/.rabbitmq/mnesia/$(RABBITMQ_NODE_NAME)
      RABBITMQ_LDAP_ENABLE:       no
      RABBITMQ_LOGS:              -
      RABBITMQ_ULIMIT_NOFILES:    65536
      RABBITMQ_USE_LONGNAME:      true
      RABBITMQ_ERL_COOKIE:        <set to the key 'rabbitmq-erlang-cookie' in secret 'endpoint-broker-rabbitmq'>  Optional: false
      RABBITMQ_LOAD_DEFINITIONS:  no
      RABBITMQ_DEFINITIONS_FILE:  /app/load_definition.json
      RABBITMQ_SECURE_PASSWORD:   yes
      RABBITMQ_USERNAME:          admin
      RABBITMQ_PASSWORD:          <set to the key 'rabbitmq-password' in secret 'endpoint-broker-rabbitmq'>  Optional: false
      RABBITMQ_PLUGINS:           rabbitmq_management, rabbitmq_peer_discovery_k8s, rabbitmq_mqtt, rabbitmq_prometheus
    Mounts:
      /bitnami/rabbitmq/conf from configuration (rw)
      /docker-entrypoint-initdb.d/init-scripts from custom-init-scripts (rw)
      /opt/bitnami/rabbitmq/.rabbitmq/ from empty-dir (rw,path="app-erlang-cookie")
      /opt/bitnami/rabbitmq/.rabbitmq/mnesia from data (rw)
      /opt/bitnami/rabbitmq/etc/rabbitmq from empty-dir (rw,path="app-conf-dir")
      /opt/bitnami/rabbitmq/plugins from empty-dir (rw,path="app-plugins-dir")
      /opt/bitnami/rabbitmq/var/lib/rabbitmq from empty-dir (rw,path="app-tmp-dir")
      /opt/bitnami/rabbitmq/var/log/rabbitmq from empty-dir (rw,path="app-logs-dir")
      /tmp from empty-dir (rw,path="tmp-dir")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-zds6d (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True
  Initialized                 True
  Ready                       False
  ContainersReady             False
  PodScheduled                True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-endpoint-broker-rabbitmq-0
    ReadOnly:   false
  empty-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  configuration:
    Type:                Projected (a volume that contains injected data from multiple sources)
    SecretName:          endpoint-broker-rabbitmq-config
    SecretOptionalName:  <nil>
  custom-init-scripts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      endpoint-broker-rabbitmq-init-scripts
    Optional:  false
  kube-api-access-zds6d:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  4m54s                default-scheduler  Successfully assigned default/endpoint-broker-rabbitmq-0 to lp-5cg327217j
  Warning  BackOff    63s                  kubelet            Back-off restarting failed container rabbitmq in pod endpoint-broker-rabbitmq-0_default(695547ee-485f-4ba7-bb16-c1b053960e13)
  Normal   Pulled     51s (x3 over 4m54s)  kubelet            Container image "docker.io/bitnami/rabbitmq:3.13.1-debian-12-r0" already present on machine
  Normal   Created    51s (x3 over 4m54s)  kubelet            Created container rabbitmq
  Normal   Started    51s (x3 over 4m54s)  kubelet            Started container rabbitmq
  Warning  Unhealthy  20s (x9 over 4m24s)  kubelet            Readiness probe failed:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 15672 after 0 ms: Couldn't connect to server
```

### Additional information

Maybe a good thing to add here is that I have already one broker initialized inside the cluster with mostly the same helm values, but with different ports. So I have two RabbitMQ brokers with the MQTT plugin installed inside a cluster with different ports, using the same helm values yaml. 

The first broker is working fine.
