### ISSUE TITLE
[bitnami/mongodb]  Infinite loop in replicaSetConfigurationSettings.sh

### ISSUE THREAD

**Issue by leif-ateme** [bitnami/charts#27482]
### Name and Version

bitnami/mongodb 15.1.15

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi, when deploying mongodb using `replicaSetConfigurationSettings.enabled = true` the script [replicaSetConfigurationSettings.sh](https://github.com/bitnami/charts/blob/main/bitnami/mongodb/templates/replicaset/scripts-configmap.yaml#L212) never exits its while loop, and outputs logs forever. 

The custom configuration is correctly applied (confirmed using `rs.config()` in `mongosh`) so I am not sure why it never finishes. 

Looking at the script it seems `desiredEqualsactual` is always false so we never enter the if condition [here](https://github.com/bitnami/charts/blob/main/bitnami/mongodb/templates/replicaset/scripts-configmap.yaml#L276) so the loop never exits.

### Are you using any custom parameters or values?

```yaml
mongodb:
  architecture: replicaset
  replicaCount: 3
  replicaSetConfigurationSettings:
    enabled: true
    configuration:
      members[0].priority: 1
      members[1].priority: 1
      members[2].priority: 1
```

### What is the expected behavior?

[replicaSetConfigurationSettings.sh](https://github.com/bitnami/charts/blob/main/bitnami/mongodb/templates/replicaset/scripts-configmap.yaml#L212) should finish and stop printing logs.

### What do you see instead?

[replicaSetConfigurationSettings.sh](https://github.com/bitnami/charts/blob/main/bitnami/mongodb/templates/replicaset/scripts-configmap.yaml#L212) never exits and prints logs forever.

### Additional information

The logs
![image](https://github.com/bitnami/charts/assets/173387302/7dac062f-8c8c-46b9-8904-4c3eeff64a0e)
