### ISSUE TITLE
Kafka helm chart examples lead to literal '*' instead of wildcard

### ISSUE THREAD

**Issue by florian-besser** [bitnami/charts#27480]
### Name and Version

oci://registry-1.docker.io/bitnamicharts/kafka:29.3.4

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Apply the helm chart using the following values:
```yaml
extraConfigYaml:
  "authorizer.class.name": "org.apache.kafka.metadata.authorizer.StandardAuthorizer"
  "super.users": "User:controller_user;User:provisioning"
# Removed listeners, sasl and TLS entries
provisioning:
  enabled: true
  extraProvisioningCommands:
    - echo "Allow redpanda user to consume from any topic/group"
    - >-
      /opt/bitnami/kafka/bin/kafka-acls.sh
      --bootstrap-server $KAFKA_SERVICE
      --command-config $CLIENT_CONF
      --add
      --allow-principal User:redpanda
      --operation READ
      --operation DESCRIBE
      --operation DescribeConfigs
      --topic '*'
 # skipping auth:
```

This creates a K8s `job` that launches a pod using:
```yaml
Containers:
  kafka-provisioning:
    Command:
      /bin/bash
    Args:
      -efc
      echo "Configuring environment"
      . /opt/bitnami/scripts/libkafka.sh
      export CLIENT_CONF="${CLIENT_CONF:-/tmp/client.properties}"
      if [ ! -f "$CLIENT_CONF" ]; then
        touch $CLIENT_CONF
      
        kafka_common_conf_set "$CLIENT_CONF" security.protocol "SASL_SSL"
        kafka_common_conf_set "$CLIENT_CONF" ssl.keystore.type "PEM"
        kafka_common_conf_set "$CLIENT_CONF" ssl.truststore.type "PEM"
        ! is_empty_value "$KAFKA_CLIENT_KEY_PASSWORD" && kafka_common_conf_set "$CLIENT_CONF" ssl.key.password "$KAFKA_CLIENT_KEY_PASSWORD"
        file_to_multiline_property() {
            awk 'NR > 1{print line" \\"}{line=$0;}END{print $0" "}' <"${1:?missing file}"
        }
        kafka_common_conf_set "$CLIENT_CONF" ssl.keystore.key "$(file_to_multiline_property "/certs/kafka-pkcs8.key")"
        kafka_common_conf_set "$CLIENT_CONF" ssl.keystore.certificate.chain "$(file_to_multiline_property "/certs/kafka.crt")"
        kafka_common_conf_set "$CLIENT_CONF" ssl.truststore.certificates "$(file_to_multiline_property "/certs/kafka-ca.crt")"
        kafka_common_conf_set "$CLIENT_CONF" sasl.mechanism PLAIN
        kafka_common_conf_set "$CLIENT_CONF" sasl.jaas.config "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$SASL_USERNAME\" password=\"$SASL_USER_PASSWORD\";"
      fi
      
      echo "Running pre-provisioning script if any given"
      
                  
      
      kafka_provisioning_commands=(
                    "echo \"Allow redpanda user to consume from any topic/group\""
                    "/opt/bitnami/kafka/bin/kafka-acls.sh --bootstrap-server $KAFKA_SERVICE --command-config $CLIENT_CONF --add --allow-principal User:redpanda --operation READ --operation DESCRIBE --operation DescribeConfigs --topic '*'"
      )
      
      echo "Starting provisioning"
      for ((index=0; index < ${#kafka_provisioning_commands[@]}; index+=1))
      do
        for j in $(seq ${index} $((${index}+1-1)))
        do
            ${kafka_provisioning_commands[j]} & # Async command
        done
        wait  # Wait the end of the jobs
      done
      
      echo "Running post-provisioning script if any given"
      
                  
      
      echo "Provisioning succeeded"
      
```

### Are you using any custom parameters or values?

See above

### What is the expected behavior?

The resulting `redpanda` user should be able to read all topics

### What do you see instead?

The `redpanda` can read the topic `'*'`, meaning the topic with exactly the name `'*'`!

### Additional information

I tried the following alternatives, all without success:
```
      /opt/bitnami/kafka/bin/kafka-acls.sh
      --bootstrap-server $KAFKA_SERVICE
      --command-config $CLIENT_CONF
      --add
      --allow-principal User:redpanda
      --operation READ
      --operation DESCRIBE
      --operation DescribeConfigs
      --topic "*"
```
```
      /opt/bitnami/kafka/bin/kafka-acls.sh
      --bootstrap-server $KAFKA_SERVICE
      --command-config $CLIENT_CONF
      --add
      --allow-principal User:redpanda
      --operation READ
      --operation DESCRIBE
      --operation DescribeConfigs
      --topic \*
```

In the end, my workaround was running the `args` with `-efc` instead of the default `-ec`, and then I could just:
```
      /opt/bitnami/kafka/bin/kafka-acls.sh
      --bootstrap-server $KAFKA_SERVICE
      --command-config $CLIENT_CONF
      --add
      --allow-principal User:redpanda
      --operation READ
      --operation DESCRIBE
      --operation DescribeConfigs
      --topic *
```
