### ISSUE TITLE
while installing scripts of magento, it suddenly quited.

### ISSUE THREAD

**Issue by smth-hyj** [bitnami/charts#27494]
### Name and Version

bitnami/magento:2.4.7, latest

### What architecture are you using?

arm64

## envirnoment
- mem : 12G
- process : 12
- vm : centos stream 9 / vmware workstation 17 pro#27491
- docker version : 26.1.4 (server/client both)
- php version : 8.1.29

## configuration
I use docker-compose.yaml file
```
version: '3'
networks:
  magento2_default:
    driver: bridge
services:
  mariadb:
    image: bitnami/mariadb:11.2.4
    container_name: mariadb
    environment:
      - MARIADB_BIND_ADDRESS=0.0.0.0
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento
      - MARIADB_DATABASE=magento
    volumes:
      - mariadb_data:/bitnami/mariadb

  elasticsearch:
    image: elasticsearch:7.17.22
    container_name: elasticsearch
    environment:
      - node.name=elastic
      - cluster.name=elastic-docker-cluster
      - discovery.type=single-node
    ports:
      - '9200:9200'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    environment:
     - GF_SERVER_ROOT_URL=http://my.grafana.server/
     - GF_INSTALL_PLUGINS=grafana-clock-panel
     - user=$(id -u)
     - name=grafana
    volumes:
      - /grafana-data/grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - elasticsearch

  magento:
    image: bitnami/magento:2.4.7
    container_name: magento
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento
      - MAGENTO_DATABASE_NAME=magento
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_SEARCH_ENGINE=elasticsearch7
      - MAGENTO_SEARCH_ENGINE_HOST=elasticsearch
      - MAGENTO_SEARCH_ENGINE_PORT=9200
      - image.debug=true
    volumes:
      - magento_data:/bitnami/magento
    depends_on:
      - mariadb
      - elasticsearch
    cpus: 2                    # without these two arguments, it don't work well too
    mem_limit: 6MB  


volumes:
  mariadb_data:
    driver: local
  elasticsearch_data:
    driver: local
  magento_data:
    driver: local
```

## Run
docker compose run -d

after a few seconds
```
[/var/www/html/magento2]# docker logs magento
magento 11:06:35.71 INFO  ==> 
magento 11:06:35.72 INFO  ==> Welcome to the Bitnami magento container
magento 11:06:35.72 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
magento 11:06:35.72 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
magento 11:06:35.73 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
magento 11:06:35.73 INFO  ==> 
magento 11:06:35.74 INFO  ==> ** Starting Magento setup **
magento 11:06:35.79 INFO  ==> Generating sample certificates
Certificate request self-signature ok
subject=CN = example.com
realpath: /bitnami/apache/conf: No such file or directory
magento 11:06:37.99 INFO  ==> Configuring Apache ServerTokens directive
magento 11:06:38.07 INFO  ==> Configuring PHP options
magento 11:06:38.09 INFO  ==> Setting PHP expose_php option
magento 11:06:38.11 INFO  ==> Setting PHP output_buffering option
magento 11:06:38.21 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
magento 11:06:38.27 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
magento 11:06:38.39 INFO  ==> Ensuring Magento directories exist
magento 11:06:38.40 INFO  ==> Configuring permissions
magento 11:06:38.43 INFO  ==> Trying to connect to the database server
magento 11:06:38.45 INFO  ==> Trying to connect to Elasticsearch
magento 11:06:58.86 INFO  ==> Running Magento install script
[/var/www/html/magento2]# docker ps -a
CONTAINER ID   IMAGE                    COMMAND                   CREATED          STATUS                        PORTS                                                 NAMES
49473e6efde0   bitnami/magento:2.4.7    "/opt/bitnami/script…"   46 seconds ago   Exited (137) 18 seconds ago                                                         magento
d7852406db3c   grafana/grafana-oss      "/run.sh"                 46 seconds ago   Up 41 seconds                 0.0.0.0:3000->3000/tcp, :::3000->3000/tcp             grafana
25b0b9a9ed1b   elasticsearch:7.17.22    "/bin/tini -- /usr/l…"   46 seconds ago   Up 43 seconds                 0.0.0.0:9200->9200/tcp, :::9200->9200/tcp, 9300/tcp   elasticsearch
9506d0696600   bitnami/mariadb:11.2.4   "/opt/bitnami/script…"   46 seconds ago   Up 44 seconds                 3306/tcp                                              mariadb
```

### Are you using any custom parameters or values?

    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento
      - MAGENTO_DATABASE_NAME=magento
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_SEARCH_ENGINE=elasticsearch7
      - MAGENTO_SEARCH_ENGINE_HOST=elasticsearch
      - MAGENTO_SEARCH_ENGINE_PORT=9200

### What is the expected behavior?

I have to get in server: localhost:8080 but it doesnt work 
![image](https://github.com/bitnami/charts/assets/147927247/6fd4e258-8399-4d57-a288-31074086535d)

### What do you see instead?

some kind of magento admin page? Idk bc I never get it right

### Additional information

I have to finish this work until tomorrow so I am now considering use woocommerce....
