### ISSUE TITLE
Minio Ingress Probleme

### ISSUE THREAD

**Issue by pomland-94** [bitnami/charts#27497]
### Name and Version

bitnami/minio:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. On Premise Kubernetes Cluster
2. ingress-nginx Controller

### Are you using any custom parameters or values?

```yaml
global:
  storageClass: "rook-cephfs"
mode: distributed
auth:
  ## @param auth.rootUser MinIO&reg; root username
  ##
  rootUser: admin
  ## @param auth.rootPassword Password for MinIO&reg; root user
  ##
  rootPassword: "Test2024"
  ## @param auth.existingSecret Use existing secret for credentials details (`auth.rootUser` and `auth.rootPassword` will be ignored and picked up from this secret). The secret has to contain the keys `root-user` and `root-password`)
  ##
  existingSecret: ""
  useCredentialsFiles: false
  forceNewKeys: false
disableWebUI: false
tls:
  enabled: false
  autoGenerated: false
  existingSecret: ""
provisioning:
  enabled: true
  resourcesPreset: "medium"
  buckets:
    - name: artifacts
      versioning: Versioned
      quota:
        type: set
        size: 20GiB
      region: de-nbg1-dc
    - name: external-diffs
      versioning: Versioned
      quota:
        type: set
        size: 20GiB
      region: de-nbg1-dc3
    - name: uploads
      versioning: Versioned
      quota:
        type: set
        size: 20GiB
      region: de-nbg1-dc3
    - name: lfs
      versioning: Versioned
      quota:
        type: set
        size: 20GiB
      region: de-nbg1-dc3
    - name: packages
      versioning: Versioned
      quota:
        type: set
        size: 20GiB
      region: de-nbg1-dc3
    - name: dependency-proxy
      versioning: Versioned
      quota:
        type: set
        size: 20GiB
      region: de-nbg1-dc3
    - name: terraform-state
      versioning: Versioned
      quota:
        type: set
        size: 20GiB
      region: de-nbg1-dc3
    - name: pages
      versioning: Versioned
      quota:
        type: set
        size: 20GiB
      region: de-nbg1-dc3
    - name: ci-secure-files
      versioning: Versioned
      quota:
        type: set
        size: 20GiB
      region: de-nbg1-dc3
  config:
    - name: region
      options:
        name: de-nbg1-dc3
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"
resourcesPreset: "medium"
ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: minio.contentways.org
  path: /console
  pathType: ImplementationSpecific
  servicePort: minio-console
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: default-clusterissuer
  tls: true
  selfSigned: false
apiIngress:
  enabled: true
  ingressClassName: "nginx"
  hostname: minio.contentways.org
  path: /
  pathType: ImplementationSpecific
  servicePort: minio-api
  annotations:
    cert-manager.io/cluster-issuer: default-clusterissuer
  tls: true
  selfSigned: false
persistence:
  enabled: true
  storageClass: "rook-cephfs"
  mountPath: /bitnami/minio/data
  accessModes:
    - ReadWriteMany
  size: 100Gi
metrics:
  prometheusAuthType: public
  serviceMonitor:
    enabled: false
  prometheusRule:
    enabled: false
```

### What do you see instead?

When i try to open https://minio.contentways.org/console The Static Ressources are not loaded.
