### ISSUE TITLE
Kafka chart has incorrect extraListeners templating

### ISSUE THREAD

**Issue by asazanoff** [bitnami/charts#27508]
### Name and Version

bitnami/kafka 29.3.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Update `listeners.extraListeners` with more then one custom listener:
    ```yaml
    listeners:
      extraListeners:
       - name: CUSTOM
         containerPort: 9097
         protocol: SASL_PLAINTEXT
         sslClientAuth: ""
       - name: CUSTOM2
         containerPort: 4097
         protocol: SASL_PLAINTEXT
         sslClientAuth: ""
    ```
3. Run `helm template`

### What is the expected behavior?

Statefulset would have in ports
```yaml
            - name: custom
              containerPort: 9097
            - name: custom2
              containerPort: 4097
```

### What do you see instead?

Statefulset would have in ports
```yaml
            - name: custom
              containerPort: 9097- name: custom2
              containerPort: 4097
```
