### ISSUE TITLE
Supabase `auth.uid()` always null

### ISSUE THREAD

**Issue by n0rmanc** [bitnami/charts#27522]
### Name and Version

bitnami/supabase 5.2.7

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. install supabase by the command

```
$ helm upgrade --install --create-namespace -n jbs supabase oci://registry-1.docker.io/bitnamicharts/supabase -f ./values.yaml
```

2. create a supabase user
3. enter sql editor in studio 
4. select an authenticated role by impersonating the user.
5. run `select * from auth.uid()` query

### Are you using any custom parameters or values?

```yaml
publicURL: "http://api.456sms888.99k"
studio:
  enabled: true
  extraEnvVars:
    - name: HOSTNAME
      value: '0.0.0.0'
kong:
  ingress:
    enabled: true
    hostname: "api.456sms888.99k"
  service: 
    type: ClusterIP
```

### What is the expected behavior?

get user's id

### What do you see instead?

null

### Additional information

I checked both chart version `auth.uid` and the latest supabase version `auth.uid`.

chart version auth.uid()
```
CREATE OR REPLACE FUNCTION auth.uid()
    RETURNS uuid
    LANGUAGE sql
    STABLE
    SET search_path TO ''
    AS $function$
    SELECT
        nullif(current_setting('request.jwt.claim.sub', TRUE), '')::uuid;
$function$;
```

latest supabase version `auth.uid()`

``` 
CREATE OR REPLACE FUNCTION auth.uid()
 RETURNS uuid
 LANGUAGE sql
 STABLE
AS $function$
  select 
  coalesce(
    nullif(current_setting('request.jwt.claim.sub', true), ''),
    (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub')
  )::uuid
$function$
```

I updated the `auth.uid()` function, it works fine.
