### ISSUE TITLE
[bitnami/elasticsearch] xpack.security.http 

### ISSUE THREAD

**Issue by Harrys-git** [bitnami/charts#27520]
### Name and Version

bitnami/elasticsearch 21.1.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Install elasticsearch into Openshift.

### Are you using any custom parameters or values?

```
security
  enable: true
  tls:
    autoGenerate: true
    usePemCerts: true

extraConfig:
  xpack:
   security:
      enabled: true
      http:
        ssl:
          enabled: true
          key: <path to mounted corporate certs>
          certificate: <path to mounted corporate certs>
          certificate_authorities: <path to mounted corporate certs>

volume and volumemount set for certs...
```

### What is the expected behavior?

I expect Nodes to use autogenerated certs and for my extraConfig to override the default xpack.security.http settings where it will point to my own mounted certs. This would mean my nodes would use the autoGenerated and I would also be able to post data to the ingester using the mounted certs as they are trusted.

### What do you see instead?

I see in the containers that the /opt/bitnami/elasticsearch/config/elasticsearch.yaml instead has my xpack config aswell as its own default xpack.security.http settings which the default settings take precedence over mine.
example:
```
  xpack:
   security:
      enabled: true
      http:
        ssl:
          enabled: true
          key: <path to mounted corporate certs>
          certificate: <path to mounted corporate certs>
          certificate_authorities: <path to mounted corporate certs>

  xpack:
   security:
      enabled: true
      http:
        ssl:
          enabled: true
          key: /opt/bitnami/elasticsearch/config/certs/ca.crt
          certificate: /opt/bitnami/elasticsearch/config/certs/tls.crt
          certificate_authorities: /opt/bitnami/elasticsearch/config/certs/tls.key
```

### Additional information

Is there any way to permantly overwrite the  xpack.security.http config to use corporate certs instead of the node certs that are autogenerated. 
Just to reconfirm, I want to use autogenerated for node to node and my own for interacting with the nodes externally.
