### ISSUE TITLE
[bitnami/kong] No way to open additional ports on pods

### ISSUE THREAD

**Issue by george-d-atscale** [bitnami/charts#27556]
### Name and Version

bitnami/kong 12.2.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Open ports to the service using:
```yaml
  service:
    type: LoadBalancer
    extraPorts:
      - port: 11111
        targetPort: 11111
        protocol: TCP
        name: thrift
      - port: 15432
        targetPort: 15432
        protocol: TCP
        name: pgwire
```
Then try to reach the service over TCP via the loadbalancer TCP ingress.

### Are you using any custom parameters or values?

```yaml
database: "off"
  fullnameOverride: "kong"
kong: 
  extraEnvVars:
    - name: KONG_DATABASE
      value: "off"
    - name: status_listen
      value: 0.0.0.0:8100
    - name: trusted_ips
      value: 0.0.0.0/0,::/0
    - name: nginx_proxy_proxy_buffers
      value: "16 32K"
    - name: nginx_proxy_proxy_buffer_size
      value: "32K"
    - name: nginx_http_client_max_body_size
      value: "512M"
ingressController:
   extraEnvVars:
      - name: feature_gates
        value: "RewriteURIs=true"
  postgresql:
    enabled: false
  service:
    type: LoadBalancer
    extraPorts:
      - port: 11111
        targetPort: 11111
        protocol: TCP
        name: thrift
      - port: 15432
        targetPort: 15432
        protocol: TCP
        name: pgwire
```

### What is the expected behavior?

I should be able to open ports on the service and use Kong's TCP ingress to forward traffic to my other services.

### What do you see instead?

Connection Refused. 

### Additional information

There should be an additional extraPorts or extraContainerPorts list on the deployment (dep-ds.yaml ) file.
