### ISSUE TITLE
[bitnami/kafka] Setup of sasl authentication to external zookeeper during Kraft-Migration

### ISSUE THREAD

**Issue by ph311o** [bitnami/charts#27581]
### Name and Version

bitnami/kafka 29.3.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In https://github.com/bitnami/charts/issues/22729 the problem was addressed for brokers:
 SASL authentication to external Zookeeper was put into wrong config file. I fixed it in PR https://github.com/bitnami/charts/pull/23550.

During testing migration to kraft mode I recognized that the controller needs also a VolumeMount to the kafka_jaas.conf file to be able to properly connect to Zookeeper.

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Controller Statefulset needs:

```yaml
            {{- if .Values.sasl.zookeeper.user }}
            - name: kafka-config
              mountPath: /opt/bitnami/kafka/config/kafka_jaas.conf
              subPath: kafka_jaas.conf
            {{- end }}
``` 

like in https://github.com/bitnami/charts/blob/main/bitnami/kafka/templates/broker/statefulset.yaml#L314-L318

### What do you see instead?

Controller is not able to finalize migration to kraft mode as it cannot connect to Zookeeper with proper SASL authentication.

### Additional information

I will submit a PR to fix the issue.
