### ISSUE TITLE
Problem connecting to MongoDB

### ISSUE THREAD

**Issue by morzan1001** [bitnami/charts#27605]
### Name and Version

bitnami/mongodb:15.6.10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi, I am trying to run a MongoDB in my kubernetes cluster. For this, I really chose a very small and simple config, but I can't explain why the connections are failing. 

### Are you using any custom parameters or values?

The settings of my helmchart-valuefile are as follows: 

```yaml
mongodb:
  enabled: true 
  nodeSelector:
    kubernetes.io/arch: amd64

  auth:
    rootPassword: "SuperSpecialRootPass"
    username: "databaseUser"
    password: "databasePass"
    database: "userDB"

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 20Gi
    storageClass: "longhorn"
```

### What is the expected behavior?

A service is created, but unfortunately, my app (which runs in the same namespace) cannot connect to the mongodb.

### What do you see instead?

```
server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongodb.<namespace>.svc.cluster.local:27017, Type: Unknown, Last error: EOF }, ] }
```

### Additional information

As I said, my app and the database run in the same namespace and the database service is created correctly. Have I overlooked any settings? Thank you very much for your help.
