### ISSUE TITLE
Inconsistent MongoDB Connection Behavior with Docker Compose Configuration

### ISSUE THREAD

**Issue by G0ldan** [bitnami/charts#27602]
### Name and Version

bitnami/mongodb

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Use the provided Docker Compose file (see "Additional information" below) to set up the mongodb and mongo-express services.
2. Set `MONGO_HOST=mongodb` in the .env file.
3. Run the Docker Compose setup.
4. Observe that mongo-express connects to the database but a Node.js application fails to connect.
5. Change `MONGO_HOST` to `127.0.0.1` in the .env file.
6. Restart the Docker Compose setup.
7. Observe that the Node.js application connects to the database, but mongo-express fails to connect.

### Are you using any custom parameters or values?

Yes, the following custom parameters and values are used:

- Environment variables in the .env file:
```
        MONGO_HOST
        MONGO_PORT
        MONGO_USER
        MONGO_PASSWORD
        MONGO_SECONDARY_KEY
        MONGO_EXPRESS_AUTH_USERNAME
        MONGO_EXPRESS_AUTH_PASSWORD
```
- Docker Compose configuration:
        Port mappings
        MongoDB replica set settings
        MongoDB and Mongo Express environment variables

### What is the expected behavior?

Both mongo-express and the Node.js application should be able to connect to the MongoDB instance.

### What do you see instead?

A. When `MONGO_HOST` is set to `mongodb`:
- mongo-express connects to the database successfully.
- The Node.js application fails to connect to the database.

B. When `MONGO_HOST` is set to `127.0.0.1`:
- The Node.js application connects to the database successfully.
- mongo-express fails to connect to the database.

### Additional information

Here's the complete Docker Compose file:
```yaml
version: "3.9"

services:
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGODB_ADVERTISED_HOSTNAME: ${MONGO_HOST}
      MONGODB_ADVERTISED_PORT_NUMBER: ${MONGO_PORT}
      MONGODB_PORT_NUMBER: ${MONGO_PORT}
      MONGODB_ROOT_USER: ${MONGO_USER}
      MONGODB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: ${MONGO_SECONDARY_KEY}
    volumes:
      - ./database:/bitnami/mongodb

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:${MONGO_PORT}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_AUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_AUTH_PASSWORD}
    depends_on:
      - mongodb
    restart: unless-stopped
```

Here's a sample of the Node.js connection code:
```js
import mongoose from "mongoose"
import dotenv from "dotenv"

dotenv.config()

export const db_connect = async () => {
  console.log("Connecting to MongoDB...")

  const db = await mongoose.connect(
    `mongodb://${process.env.MONGO_USER}:${process.env.MONGO_PASSWORD}@${process.env.MONGO_HOST}:${process.env.MONGO_PORT}/${process.env.MONGO_DB_NAME}?authSource=admin`
  )

  console.log("Connected to MongoDB")
}

db_connect()
```
.env file sample:
```env
# MONGO
MONGO_HOST=127.0.0.1
MONGO_PORT=3001
MONGO_DB_NAME=MyApp
MONGO_USER=admin
MONGO_PASSWORD=password
MONGO_SECONDARY_KEY=X5ZxqCt4cQrQ3Zfr2zRBFk8R0eakYBaH

# MONGO EXPRESS
MONGO_EXPRESS_PORT=8080
MONGO_EXPRESS_AUTH_USERNAME=admin
MONGO_EXPRESS_AUTH_PASSWORD=password
```

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by G0ldan** [comment]
I found a solution to my problem. Here are the details:

Environment variables in the .env file:
```env
# MONGO
MONGO_HOST=127.0.0.1
MONGO_PORT=3001
MONGO_DB_NAME=MyApp
MONGO_USER=admin
MONGO_PASSWORD=password
MONGO_SECONDARY_KEY=X5ZxqCt4cQrQ3Zfr2zRBFk8R0eakYBaH

# MONGO EXPRESS
MONGO_EXPRESS_PORT=8080
MONGO_EXPRESS_AUTH_USERNAME=admin
MONGO_EXPRESS_AUTH_PASSWORD=password
```
Here's a sample of the Node.js connection code where I've added `&directConnection=true` to the mongodb url that fix the problem.
```js
import mongoose from "mongoose"
import dotenv from "dotenv"

dotenv.config()

export const db_connect = async () => {
  console.log("Connecting to MongoDB...")

  const db = await mongoose.connect(
    `mongodb://${process.env.MONGO_USER}:${process.env.MONGO_PASSWORD}@${process.env.MONGO_HOST}:${process.env.MONGO_PORT}/${process.env.MONGO_DB_NAME}?authSource=admin&directConnection=true`
  )

  console.log("Connected to MongoDB")
}

db_connect()
```

Here's the complete Docker Compose file:
```yaml
version: "3.9"

services:
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGODB_ADVERTISED_HOSTNAME: ${MONGO_HOST}
      MONGODB_ADVERTISED_PORT_NUMBER: ${MONGO_PORT}
      MONGODB_PORT_NUMBER: ${MONGO_PORT}
      MONGODB_ROOT_USER: ${MONGO_USER}
      MONGODB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: ${MONGO_SECONDARY_KEY}
    volumes:
      - ./database:/bitnami/mongodb

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:${MONGO_PORT}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_AUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_AUTH_PASSWORD}
    depends_on:
      - mongodb
    restart: unless-stopped
```
