### ISSUE TITLE
[bitnami/elasticsearch] touch Read-only file system error when initScripts defined

### ISSUE THREAD

**Issue by Karolline** [bitnami/charts#27607]
### Name and Version

bitnami/elasticsearch 21.2.3

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Configure chart to install with a custom init script
2. Get error

### Are you using any custom parameters or values?

```yaml
initScripts:
  my_init_script.sh: |
     #!/bin/sh
     echo "Do something."
```

### What is the expected behavior?

print "Do something." when elasticsearch is started

### What do you see instead?

```
Sourcing /docker-entrypoint-initdb.d/init-scripts/..2024_07_01_00_55_44.3456531485/my_init_script.sh as it is not executable by the current user, any error may cause initialization to fail
Do something.
touch: cannot touch '/bitnami/elasticsearch/.user_scripts_initialized': Read-only file system
```

### Additional information

I found similar issue [here](https://github.com/bitnami/charts/issues/24473) at the bitnami/grafana chart https://github.com/bitnami/charts/issues/24473

I followed the direction in the ticket which is adding an emptydir in specific path and the issue was resolved.
```yaml
extraVolumeMounts:
    - name: empty-dir
      mountPath: /bitnami/elasticsearch
      subPath: app-volume-dir
 ```

Could you apply this fix to elasticsearch chart?
