### ISSUE TITLE
Failed atomic move of /bitnami/kafka/data/test-0

### ISSUE THREAD

**Issue by michael-misiaszek** [bitnami/charts#27623]
### Name and Version

bitnami/kafka 3.7.1

### What architecture are you using?

None

### What steps will reproduce the bug?

- In Azure AKS
- Deploy via helm chart with values below:
- Create topic with Kafka UI or `kafka-topic.sh`
- Delete topic with Kafka UI or `kafka-topic.sh`

### Are you using any custom parameters or values?

Custom Yaml File:
```controller:
  containerSecurityContext:
    readOnlyRootFilesystem: false
  # Setting is Large
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 750m
      memory: 3072Mi
listeners:
  client:
    containerPort: 9092
    protocol: PLAINTEXT
    name: CLIENT

broker:
  containerSecurityContext:
    readOnlyRootFilesystem: false

extraConfig: |-
  delete.topic.enable = true
```

### What is the expected behavior?

Kafka topic gets deleted

### What do you see instead?

Kafka controller in crash loop

### Additional information

Things I've tried in my yaml:

```
controller:
  containerSecurityContext:
    readOnlyRootFilesystem: false
  # Setting is Large
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 750m
      memory: 3072Mi
listeners:
  client:
    containerPort: 9092
    protocol: PLAINTEXT
    name: CLIENT

broker:
  containerSecurityContext:
    readOnlyRootFilesystem: false

extraConfig: |-
  delete.topic.enable = true
#    deleteTopicEnable=true
#  logDirs=/opt/bitnami/kafka/logs

# Delete Topic 
# None of these worked
# controller:
#   containerSecurityContext:
#     runAsNonRoot: false
##################
# controller:
#   podSecurityContext:
#     enabled: false
#   containerSecurityContext:
#     runAsNonRoot: false
#     readOnlyRootFilesystem: false
# extraConfig: |-
#   deleteTopicEnable=true
#   logDirs=/opt/bitnami/kafka/logs

# volumePermissions:
#   enabled: true
#   containerSecurityContext:
#     runAsUser: 0
```
