### ISSUE TITLE
[bitnami/minio] containerPorts cannot work properly

### ISSUE THREAD

**Issue by Uijeong97** [bitnami/charts#27625]
### Name and Version

bitnami/minio:14.6.16

### What architecture are you using?

None

### What steps will reproduce the bug?

1. I want to use `containerPorts`.
2. Environment variables for `containerPorts` are not working

### Are you using any custom parameters or values?

```yaml
  containerPorts:
    api: 10000
    console: 10001
```

### What is the expected behavior?

* container env must have the relevant environment variable for `containerPorts` set

```yaml
  containers:
    - env:
        - name: MINIO_API_PORT_NUMBER
          value: '10000'
        - name: MINIO_CONSOLE_PORT_NUMBER
          value: '10001'
```

### What do you see instead?

* The variables of `MINIO_API_PORT_NUMBER` and `MINIO_CONSOLE_PORT_NUMBER` are missing

```yaml
  containers:
    - env:
# empty
```

### Additional information

There is a simple typo hiding in there, so I fixed it and it is working
