### ISSUE TITLE
[bitnami/elasticsearch] Mismatch between ServiceMonitor endpoint port name and service port name

### ISSUE THREAD

**Issue by pbn4** [bitnami/charts#2763]
**Which chart**:
bitnamis/elasticsearch: 12.3.1

**Describe the bug**

Prometheus is not able to detect a service described by ServiceMonitor because it's spec.endpoints port name is 'metrics' whereas metrics service exposes 'http-metrics'.
I believe the fix is to change ServiceMonitor definition to use `http-metrics` but I am not 100% sure this doesnt brake anything else. 

Attaching default yamls for easier lookup:

ServiceMonitor:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    helm.fluxcd.io/antecedent: monitoring:helmrelease/elasticsearch
  generation: 1
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: elasticsearch
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elasticsearch
    helm.sh/chart: elasticsearch-12.3.1
  name: elasticsearch-elasticsearch-metrics
  namespace: monitoring
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: elasticsearch
      app.kubernetes.io/name: elasticsearch
```

and service:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    helm.fluxcd.io/antecedent: monitoring:helmrelease/elasticsearch
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"helm.fluxcd.io/antecedent":"monitoring:helmrelease/elasticsearch","prometheus.io/path":"/metrics","prometheus.io/port":"9114","prometheus.io/scrape":"true"},"labels":{"app.kubernetes.io/component":"metrics","app.kubernetes.io/instance":"elasticsearch","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"elasticsearch","helm.sh/chart":"elasticsearch-12.3.1"},"name":"elasticsearch-elasticsearch-metrics","namespace":"monitoring"},"spec":{"ports":[{"name":"metrics","port":9114,"protocol":"TCP","targetPort":"metrics"}],"selector":{"app.kubernetes.io/component":"metrics","app.kubernetes.io/instance":"elasticsearch","app.kubernetes.io/name":"elasticsearch"},"sessionAffinity":"None","type":"ClusterIP"}}
    prometheus.io/path: /metrics
    prometheus.io/port: "9114"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: elasticsearch
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elasticsearch
    helm.sh/chart: elasticsearch-12.3.1
  name: elasticsearch-elasticsearch-metrics
  namespace: monitoring
spec:
  ports:
  - name: metrics
    port: 9114
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: elasticsearch
    app.kubernetes.io/name: elasticsearch
  sessionAffinity: None
  type: ClusterIP
```
