### ISSUE TITLE
global.compatibility.openshift.adaptSecurityContext only applies to pod securityContext, not container specs

### ISSUE THREAD

**Issue by dchandekstark** [bitnami/charts#27633]
### Name and Version

bitnami/apache 11.2.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

See https://github.com/bitnami/charts/blob/apache/11.2.6/bitnami/apache/templates/deployment.yaml#L58 and compare to container specs.

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Setting global.compatibility.openshift.adaptSecurityContext to `auto` or `force` applies to `securityContext` of container specs. 

### What do you see instead?

Show uid and gid for `preserve-logs-symlinks` initContainer:

```yaml
spec:
  template:
    spec:
      initContainers:
        - name: preserve-logs-symlinks
          securityContext:
            runAsUser: 1001
            runAsGroup: 0
```
