### ISSUE TITLE
$ in password break install chart

### ISSUE THREAD

**Issue by borgez** [bitnami/charts#2771]
**Which chart**:
postgresql-ha:3.2.9

**Describe the bug**
postgresql-0 cannot start with error in console
/opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh: line 21: An9: unbound variable

**To Reproduce**
1. user password with $
4. publish chart

**Expected behavior**
any password allowed

**Comment by andresbono** [comment]
Hi @borgez, thanks for opening this issue. What is the password parameter that you are using and that triggers the issue?

**Comment by borgez** [comment]
> Hi @borgez, thanks for opening this issue. What is the password parameter that you are using and that triggers the issue?

Hi, i try parameters like this, don't know which password triggers, after change password error gone

```
postgresql-ha:
  postgresql:
    # move to vars in release
    # do not use $
    # do not update without right pass (it regenerate)
    password: Qs&4&$E8RKm&lh!
    repmgrPassword: Qs&4&$E8RKm&lh!
```
