### ISSUE TITLE
[bitnami/apisix] Wrong Admin API port name in ingress

### ISSUE THREAD

**Issue by vladimirpetr** [bitnami/charts#27729]
### Name and Version

apisix-3.2.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install the chart with the default deployment mode _decoupled_
2. Disable TLS at the control plane by setting `controlPlane.tls.enabled: false`
3. Enable ingress to the control plane by setting `controlPlane.ingress.enabled: true` and complete the configuration of ingress.
4. Connect to the ingress host with the configured hostname and a configured key, e.g. 
`curl https://HOSTNAME/apisix/admin/routes -H 'X-API-KEY: thisismykey`. The request returns 503. 
6. If you make such a request directly to the backend service, the service returns correctly.

### Are you using any custom parameters or values?

Modified control plane settings:
```yaml
    controlPlane:
      enabled: true
      existingSecret: apisix-api-tokens
      existingSecretAdminTokenKey: admin-token
      existingSecretViewerTokenKey: viewer-token
      extraConfig:
        etcd:
          tls:
            verify: false
      pdb:
        maxUnavailable: "1"
      podAntiAffinityPreset: soft
      tls:
        enabled: false
      resources:
        limits:
          cpu: 300m
          memory: 300Mi
        requests:
          cpu: 100m
          memory: 300Mi
      ingress:
        enabled: true
        ingressClassName: nginx-internal
        hostname: "apiadmin.mydomain.local"
        path: /
        pathType: Prefix
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-staging
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-rotation-policy: Always
          cert-manager.io/revision-history-limit: "2"
        tls: true
      metrics:
        enabled: true
```

### What is the expected behavior?

The control plane is accessed over the ingress returns successfully.

### What do you see instead?

503 gets always returned.

### Additional information

The cause of the problem seems an incorrect port name in the ingress object. The ingress manifest sets
```
{{- $servicePort := (printf "%s-%s" (ternary "https" "http" .Values.controlPlane.tls.enabled) "admin") }}
backend: {{- include "common.ingress.backend" (dict "serviceName" (include "apisix.control-plane.fullname" . | trunc 63 | trimSuffix "-") "servicePort" $servicePort "context" $)  | nindent 14 }}
```

which results in the backend port name `http-admin` and with TLS `https-admin`.

The service, on the other hand, sets the port name to 

`{{ ternary "https" "http" .Values.controlPlane.tls.enabled }}-admin-api` 

resulting in `http-admin-api` and with TLS `https-admin-api`. The port names do not match and hence, the ingress controller returns 503 as it fails to access the configured port.
