### ISSUE TITLE
[bitnami/wordpress] chart: cannot use existingSecret value 

### ISSUE THREAD

**Issue by skyrise-l** [bitnami/charts#27805]
### Name and Version

bitnami/wordpress 22.4.17 

### What architecture are you using?

arm64

### What steps will reproduce the bug?

When deploying WordPress, I can easily use a username and password to connect to a remote database as the database service, but I encounter errors when using existingSecret. I tried the echo -n method mentioned in previous issues, but it didn't resolve the problem. Perhaps the documentation should provide an example of how to use existingSecret.
```
**db password is "password":**
echo -n "password" | base64
cGFzc3dvcmQ=
```

This is the secret yaml:
```yaml
apiVersion: v1
kind: Secret
metadata:
  annotations:
  name: wordpress-externaldb
  namespace: default
data:
  mariadb-password: cGFzc3dvcmQ=
type: Opaque
```
I also found an issue: when I download the repository and use Helm to install, existingSecret requires it to contain mariadb-password. However, when I use `helm install my-release oci://registry-1.docker.io/bitnamicharts/wordpress`, existingSecret seems to require the key XXX-password, where XXX appears to be the username.

If use:
`helm install my-release oci://registry-1.docker.io/bitnamicharts/wordpress --set mariadb.enabled=false --set externalDatabase.host=dbhost --set externalDatabase.database=wordpress --set externalDatabase.port=3306 --set existingSecret="wordpress-externaldb" --set replicaCount=2`
```
error:Error: couldn't find key wordpress-password in Secret default/wordpress-externaldb
```
### Are you using any custom parameters or values?
```yaml
mariadb:
  enabled: false
externalDatabase:
  host: dbhost
  port: 3306
  user: wordpress
  password: ""
  database: wordpress
  existingSecret:  wordpress-externaldb 
```
### What is the expected behavior?

Perhaps the documentation should provide an example of how to use existingSecret.

### What do you see instead?

<img width="764" alt="截屏2024-07-05 13 35 40" src="https://github.com/bitnami/charts/assets/57531827/0cc00ceb-d692-4378-b76c-ab9c2bd463b6">
