### ISSUE TITLE
Usage of GeoIP2 Filter in Fluent-bit

### ISSUE THREAD

**Issue by Rapsody09** [bitnami/charts#27843]
### Name and Version

bitnami/fluent-bit 2.2.3

### What is the problem this feature will solve?

Use GeoIP2 Filter available in Fluent-bit

### What is the feature you are proposing to solve the problem?

Hello, Is it possible to use GeoIP2 Filter in your fluent-bit package? I do not see anything about it in the Readme.
It would be great to be able to add more information about geo IP location to logs parsed by this FLuentbit

**Comment by Rapsody09** [comment]
Yes of course, it's just that we need a database to look for informations, for example GeoLite2-City.mmdb in the documentation from https://dev.maxmind.com/geoip/geolite2-free-geolocation-data .
Do you think it could be included directly in the docker image ? Or do I need to manage that by myself ?

**Comment by rafariossaa** [comment]
You need to manage it yourself.
For this, I would suggest to use an initContainer that would take care of downloading the file and doing other preparation taksk. You could use the `initContainers` parameter.

**Comment by Rapsody09** [comment]
OK thanks, I could make it work like that 👍 

```
extraVolumes:
- name: geoipdata
  emptyDir: {}

extraVolumeMounts:
- name: geoipdata
  mountPath: /usr/local/bin/geoipdata

initContainers:
- name: geoipdata
  image: curlimages/curl
  command: ["/bin/sh"]
  args:
    - -c
    - >-
      curl https://10.10.10.10/GeoLite2-City.mmdb -o /geoipdata/GeoLite2-City.mmdb &&
      curl https://10.10.10.10/GeoLite2-ASN.mmdb -o /geoipdata/GeoLite2-ASN.mmdb
  volumeMounts:
  - name: geoipdata
    mountPath: "/geoipdata"
```

And fluent-bit conf example :

```
    [FILTER]
        Name                geoip2
        Match_regex         *
        Database            /usr/local/bin/geoipdata/GeoLite2-City.mmdb
        Lookup_key          client.ip
        Record              client.geo.country client.ip %{country.names.en}
        Record              client.geo.city client.ip %{city.names.en}
```
