### ISSUE TITLE
[bitnami/opensearch] Can't override opensearch-security/config.yml - Read-only FS

### ISSUE THREAD

**Issue by wouali** [bitnami/charts#27859]
### Name and Version

bitnami/opensearch 1.2.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

With the Bitnami Chart, I am trying to deploy OpenSearch with OIDC integrated.

Run
`helm upgrade --install opensearch opensearch -f opensearch/values-aks.yaml`

See error 
```
opensearch 15:33:20.65 INFO  ==> 
opensearch 15:33:20.65 INFO  ==> Welcome to the Bitnami opensearch container
opensearch 15:33:20.66 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
opensearch 15:33:20.66 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
opensearch 15:33:20.66 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
opensearch 15:33:20.66 INFO  ==> 
cp: cannot create regular file '/opt/bitnami/opensearch/config/./opensearch-security/action_groups.yml': Read-only file system
cp: cannot create regular file '/opt/bitnami/opensearch/config/./opensearch-security/allowlist.yml': Read-only file system
cp: cannot create regular file '/opt/bitnami/opensearch/config/./opensearch-security/audit.yml': Read-only file system
cp: cannot create regular file '/opt/bitnami/opensearch/config/./opensearch-security/internal_users.yml': Read-only file system
cp: cannot create regular file '/opt/bitnami/opensearch/config/./opensearch-security/nodes_dn.yml': Read-only file system
cp: cannot create regular file '/opt/bitnami/opensearch/config/./opensearch-security/opensearch.yml.example': Read-only file system
cp: cannot create regular file '/opt/bitnami/opensearch/config/./opensearch-security/roles.yml': Read-only file system
cp: cannot create regular file '/opt/bitnami/opensearch/config/./opensearch-security/roles_mapping.yml': Read-only file system
cp: cannot create regular file '/opt/bitnami/opensearch/config/./opensearch-security/tenants.yml': Read-only file system
cp: cannot create regular file '/opt/bitnami/opensearch/config/./opensearch-security/whitelist.yml': Read-only file system
```

### Are you using any custom parameters or values?

Following the OpenSearch documentation, I have to override the `opensearch/config/opensearch-security/config.yml` file. Since the `config` and `extraConfig` chart parameters only override `opensearch/config/opensearch.yml`, I try to pass this conf through a `volume`.
values-aks.yaml :
```yaml
clusterName: opensearch

extraVolumes:
- name: security-config
  secret:
    secretName: opensearch-security-config

extraVolumeMounts:
- name: security-config
  mountPath:  /opt/bitnami/opensearch/config/opensearch-security/


security:
  enabled:  true
  adminPassword:  ""
  logstashPassword: ""
  existingSecret: "opensearch-credentials"
  tls:
    restEncryption: true
    autoGenerated: true
    verificationMode: "full"


master:
  masterOnly: true
  containerSecurityContext:
    enabled:  true
    readOnlyRootFilesystem: false


data:
  containerSecurityContext:
    enabled:  true
    readOnlyRootFilesystem: false
  

coordinating:
  containerSecurityContext:
    enabled:  true
    readOnlyRootFilesystem: false


ingest:
  enabled: true
  containerSecurityContext:
    enabled:  true
    readOnlyRootFilesystem: false


volumePermissions:
  enabled: false

sysctlImage:
  enabled: true

dashboards:
  enabled: false
```

### What is the expected behavior?

The configuration file is loaded from the mounted `volume`  and Opensearch goes on running its init scripts (load the security plugin files among other things).

### What do you see instead?

`Read-only file system` errors, even with `readOnlyRootFilesystem: false`.

### Additional information

Thank you for helping
