### ISSUE TITLE
[bitnami/minio] Provisioning policies with "/" in the name fails

### ISSUE THREAD

**Issue by greyarch** [bitnami/charts#27850]
### Name and Version

bitnami/minio 14.6.19

### What architecture are you using?

None

### What steps will reproduce the bug?

I'm trying to install the bitnami/minio chart using the "provisioning" section.
I want to provision policies. These policies however have "/" in the name, like this:
```yaml
  provisioning:
    enabled: true
    policies:
      - name: group1/group2/project
        statements:
          - effect: Allow
            actions:
              - s3:*
            resources:
              - arn:aws:s3:::*
```
I do this to use GitLab as an OIDC provider. I want to give different permissions to users depending on what group/project they are a member of.

### What is the expected behavior?

The chart should install without errors and the policies should be auto-provisioned.

### What do you see instead?

When I try to install/upgrade, I get the following error:

```sh
Error: UPGRADE FAILED: failed to create resource: ConfigMap "minio-provisioning" is invalid: data[policy-group1/group2/project.json]: Invalid value: "policy-group1/group2/project.json": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')
```
