### ISSUE TITLE
[bitnami/argo-cd] Applicationsets are not running when pods boot-up

### ISSUE THREAD

**Issue by raghavanrrs** [bitnami/charts#27869]
### Name and Version

bitnami/argo-cd 6.5.8

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. In eks cluster with bottlerocket ARM64 OS
2. after argcd-server pod running have to execute shell and run command to bringup applicationsets

`argocd-applicationset-controller --logformat text --loglevel info --metrics-addr :8085 --probe-addr :8081 --argocd-repo-server argocd-repo-server:8081 --policy sync`

4. even after enabling applicationSets.enabled: true in values.yaml, the applicationset-controller pods throwing error `[error: no configuration has been provided, try setting KUBERNETES_MASTER environment variable]` error.

### Are you using any custom parameters or values?
```
fullnameOverride: argocd
    controller:
      replicaCount: 1
      serviceAccount:
        create: true
        name: argocd-application-controller
      resources:
        requests:
          memory: "1000Mi"
        limits:
          memory: "1500Mi"
    notifications:
      enabled: true
    server:
      replicaCount: 2
      insecure: true
      serviceAccount:
        create: true
        name: argocd-server
      autoscaling:
        enabled: true
        minReplicas: 2
      config:
        ui.bannercontent: "Welcome to Argo Controller!"
        # Enables application status badge feature
        statusbadge.enabled: 'true'
        timeout.reconciliation: 180s
        resource.customizations: |
          configuration.konghq.com/KongPlugin:
            # List of json pointers in the object to ignore differences
            ignoreDifferences: |
              jsonPointers:
              - /config/enabled
          networking.k8s.io/Ingress:
              health.lua: |
                hs = {}
                hs.status = "Healthy"
                return hs
    repoServer:
      replicaCount: 1
      autoscaling:
        enabled: true
        minReplicas: 2
    dex:
      enabled: false
    redis:
      master:
        extraFlags:
        - "--maxmemory-policy allkeys-lru"
      resources:
        requests:
          cpu: "500m"
          memory: "1000Mi"
        limits:
          cpu: "1000m"
          memory: "1500Mi"
      replica:
        readinessProbe:
          enabled: true
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 90
        livenessProbe:
          enabled: true
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 90
```
### What is the expected behavior?

applicationsets should come up along with argocd-server

### What do you see instead?

only argocd-server
