### ISSUE TITLE
Talk to other services in default namespace instead of app namespace

### ISSUE THREAD

**Issue by nicdub** [bitnami/charts#27875]
### Name and Version

bitnami/opensearch

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Set the current namespace to `default` and deploy chart in `namespace2`

### Are you using any custom parameters or values?

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: namespace2
helmCharts:
  - name: opensearch
    includeCRDs: false
    valuesInline:
      global:
        storageClass: nfs-client
      ingress:
        enabled: true
        ingressClassName: nginx
    releaseName: opensearch
    version: 1.2.6
    repo: https://charts.bitnami.com/bitnami
```

### What is the expected behavior?

The pods should contact each other through servicename.namespace2.svc.cluster.local

### What do you see instead?

The pods try to contact each other through servicename.default.svc.cluster.local, for instance in 
opensearch-coordinating-0 logs, we can see `opensearch-coordinating-0.opensearch-coordinating-hl.default.svc.cluster.local: Name or service not known`
