### ISSUE TITLE
[bitnami/redis-cluster] incorrect indent for  extraVolumeMounts, extraVolumes, sideCar

### ISSUE THREAD

**Issue by fifa451** [bitnami/charts#2787]
**Which chart**:
redis-cluster 2.2.3

**Describe the bug**
when adding values for the **extraVolumeMounts**, **extraVolumes**, and **sidecar**, the helm output has an error. The causes of these errors are incorrect indent in statefuset templates therefore it output invalid k8s yaml file.

> Error: YAML parse error on redis-cluster/templates/redis-statefulset.yaml: error converting YAML to JSON: yaml: line 96: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 96: did not find expected key
YAML parse error on redis-cluster/templates/redis-statefulset.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	/home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	/home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	/home/circleci/helm.sh/helm/pkg/action/action.go:159
helm.sh/helm/v3/pkg/action.(*Install).Run
	/home/circleci/helm.sh/helm/pkg/action/install.go:238
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:229
main.newTemplateCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/template.go:66
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357

**To Reproduce**
1. Add the values to **extraVolumes** in the **values.yaml**
2. Run `helm template test-chart .`
3. It will show the error from above. 
4. If add values to **extraVolumes:** like these

```yaml
extraVolumeMounts:
  volumes:
    - name: "test-volume"
      mountPath: test-volume
      subPath: test-volume
```
The error is gone and output correct file which means the template indent isn't correct

```yaml
      volumes:
        - name: scripts
          configMap:
            name: test-chart-redis-cluster-scripts
            defaultMode: 0755
        - name: default-config
          configMap:
            name: test-chart-redis-cluster-default
        - name: redis-tmp-conf
          emptyDir: {}
      volumes:
      - configMap:
          name: test-config
        name: test-volume
```

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
