### ISSUE TITLE
ETCD liveness fail with client authentication enabled

### ISSUE THREAD

**Issue by sebglon** [bitnami/charts#27872]
### Name and Version

bitnami/etcd:v10.2.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. deploy etcd with mTLS authentication

### Are you using any custom parameters or values?
```yaml
    auth:
      rbac:
        enabled: true
        allowNoneAuthentication: false
        existingSecret: etcd-root-credentials
        existingSecretPasswordKey: password
      client:
        secureTransport: true
        existingSecret: etcd-tls-client
        enableAuthentication: true
        certFilename: tls.crt
        certKeyFilename: tls.key
        caFilename: ca.crt
      peer:
        secureTransport: true
        existingSecret: etcd-tls
        enableAuthentication: true
        certFilename: tls.crt
        certKeyFilename: tls.key
        caFilename: ca.crt
```
### What is the expected behavior?

ETCD nodes are running

### What do you see instead?

ETCD nodes are on crashloopBackoff due to `Warning  Unhealthy  8m37s (x6 over 12m)    kubelet  Liveness probe failed: Get "https://10.233.120.36:2379/livez": remote error: tls: certificate required`

### Additional information

Seems created by this PR: https://github.com/bitnami/charts/pull/25984

**Comment by sebglon** [comment]
Workarround is to replace the livenessProbe by the previous one:
```
    # use custom liveness due to issue: https://github.com/bitnami/charts/issues/27872
    customLivenessProbe:
      exec:
        command:
        - /opt/bitnami/scripts/etcd/healthcheck.sh
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
```

**Comment by andresbono** [comment]
Hi @sebglon, I can reproduce your issue. With mutual TLS, the client (in this case the kubelet sending the [HTTP probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#http-probes)) should provide a certificate, but that is not possible with `httpGet`.

```console
$ kubectl describe pod etcd-0
...
  Warning  Unhealthy  22s   kubelet            Liveness probe failed: Get "https://10.244.0.6:2379/livez": remote error: tls: certificate required

$ kubectl debug -it etcd-0 --image=bitnami/os-shell --target=etcd
$ curl -k https://localhost:2379/livez
curl: (56) OpenSSL SSL_read: OpenSSL/3.0.13: error:0A00045C:SSL routines::tlsv13 alert certificate required, errno 0
```

The issue with running `/opt/bitnami/scripts/etcd/healthcheck.sh` as a liveness probe is that it could lead to unnecessary restarts of the container, while checking the `/livez` endpoint is a more lightweight check and a better fit for this probe. That's the rationale behind https://github.com/bitnami/charts/pull/25984.

**Comment by andresbono** [comment]
A possible alternative solution is what it is stated in https://etcd.io/docs/v3.5/op-guide/monitoring/#health-check
> [...] any locations specified by --listen-metrics-urls will also respond to the /health endpoint. This can be useful if the standard endpoint is configured with mutual (client) TLS authentication, but a load balancer or monitoring service still needs access to the health check.

So when using mTLS, you would activate the separate metrics endpoint and use that one instead for the probes:

```yaml
metrics:
  useSeparateEndpoint: true

customLivenessProbe:
  httpGet:
    port: 9090
    path: /livez
    scheme: HTTP
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
```

What do you think? If you think this solution is suitable, we could try to incorporate the fix in the chart. Contributions are welcome!!!
