### ISSUE TITLE
[bitnami/rabbitmq] Cannot Create resources via Definitions

### ISSUE THREAD

**Issue by kemra102** [bitnami/charts#2788]
**Which chart**:
rabbitmq 6.25.13

**Describe the bug**
Using the "extraSecrets" method listed [here](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#load-definitions) I am trying to create a RabbitMQ cluster via Terraform and the aforementioned config in a values.yaml file. However the RabbitMQ pods never come up as healthy and give the following error when checking the logs:

```
2020-06-08 15:36:02.666 [warning] <0.945.0> HTTP access denied: user 'sysadmin' - invalid credentials
```

**To Reproduce**
1. Install Helm chart passing in `values.yaml` using `extraSecrets` to define a definitions file to pass in as well as your RabbitMQ user & password.
2. See error in pod logs.

**Expected behavior**
RabbitMQ cluster should spin up with RMQ resources defined.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
The `values.yaml` file being passed in uses Terraform's [template resource](https://www.terraform.io/docs/providers/template/index.html) and looks like so:

```
---
image:
  tag: ${rabbitmq_version}
replicas: 3
service:
  type: 'LoadBalancer'
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${rabbitmq_url}
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: ${additional_resource_tags}
    service.beta.kubernetes.io/aws-load-balancer-internal: 'true'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: '60'
podLabels:
  name: ${podlabel_name}
  env: ${podlabel_env}
  ecosystem: ${podlabel_ecosystem}
  product: ${podlabel_product}
rabbitmq:
  username: 'sysadmin'
  password: ${rabbitmq_password}
  erlangCookie: ${erlang_cookie}
  loadDefinition:
    enabled: true
    secretName: load-definition
  extraConfiguration: |
    management.load_definitions = /app/load_definition.json
    # management.load_definitions = /app/load_additional_definition.json
persistence:
  enabled: true
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "vhosts": [
          {
            "name": "/"
          }
        ]
      }
```
> NOTE: For those not familiar with Terraform templates, the `${}` parts are where vars are passed in from Terraform when building the file from the template.
