### ISSUE TITLE
[bitnami/clickhouse] Variable for the "volumeClaimTemplates" prefix name

### ISSUE THREAD

**Issue by SantiagoOrtegaBrcm** [bitnami/charts#27886]
### Name and Version

bitnami/ClickHouse v6.0.6

### What is the problem this feature will solve?

Users that want all Kubernetes pvc names associated with one application to start with a predetermined prefix (e.g. devops-shardx-y, or test-shardx-y) must change their naming convention to account for the currently hard-coded prefix "data-". (e.g. data-devops-shardx-y or data-test-shardx-y).

### What is the feature you are proposing to solve the problem?

The request is to change the hard-coded string "data-":
```yaml
volumeClaimTemplates:
    {{- if and $.Values.persistence.enabled (not $.Values.persistence.existingClaim) }}
    - metadata:
        name: data                     <===== default hard-coded prefix    
```
 to a variable:
 ```yaml
volumeClaimTemplates:
    {{- if and $.Values.persistence.enabled (not $.Values.persistence.existingClaim) }}
    - metadata:
        name: {{ .Values.persistence.volumeClaimTemplatePrefix }}                     <===== default variable prefix    
```
