### ISSUE TITLE
[bitnami/argo-cd] Applicationset throws error when enabling clusterAdminAccess

### ISSUE THREAD

**Issue by raghavanrrs** [bitnami/charts#27884]
### Name and Version

bitnami/argo-cd 6.5.8

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. In eks cluster 1.28
2. setting applicationSet.clusterAdminAccess: 'true'

### Are you using any custom parameters or values?
```
applicationSet:
      # Enable if you would like applicationSets to be used, default false
      enabled: true
      replicaCount: 2
      defaultArgs:
        enableLeaderElection: 'true'
      # Default is false
      clusterAdminAccess: 'true'
      serviceAccount:
        create: true
        name: argocd-applicationset-controller"
        automountServiceAccountToken: 'true'
```
### What is the expected behavior?

should create applicationSet with ClusterAdmin access

### What do you see instead?

Error: 1 error occurred:
│ 	* ClusterRoleBinding.rbac.authorization.k8s.io "argocd-applicationset-controller" is invalid: subjects[0].namespace: Required value
