### ISSUE TITLE
MariaDB 10.5 no longer working on helm chart.

### ISSUE THREAD

**Issue by Donkeyotee** [bitnami/charts#27889]
### Name and Version

bitnami/mariadb-galera

### What architecture are you using?

None

### What steps will reproduce the bug?

In Kubernetes 
- Client Version: v1.28.2
- Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
- Server Version: v1.28.6

Using the latest Helm chart. 
```yaml
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: 
    meta.helm.sh/release-namespace:
  creationTimestamp: "2024-07-10T19:30:01Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: mirth-mariadb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb-galera
    app.kubernetes.io/version: 11.3.2
    helm.sh/chart: mariadb-galera-13.2.7
  name: mirth-mariadb-mariadb-galera
```

If you try to use MySQL 10.5 it will fail because `wresp_mode` has been added as a default configuration.

This mysql config was introduced in 10.6 meaning the 10.5 MySQL LTS will not work with this helm chart anymore.

![image](https://github.com/bitnami/charts/assets/134731321/e7d02f24-4ec7-496c-9233-ab8bee58d382)

This is not a huge issue but does put me specifically in a bit of a pickle as I must use 10.5 for a bit longer.

### Are you using any custom parameters or values?

No

### What is the expected behavior?

10.5 would be able to run on this provided HELM chart.

### What do you see instead?

Pod crashback loop due to not understanding that newly introduced variable.

### Additional information

Nothing really just wanted to let you know and hope you may be able to remove it and allow it as an optional setting.
Thanks for maintaining this HELM
