### ISSUE TITLE
[bitnami/redis] Issues after upgrading on a k8s cluster having two different redis deployments

### ISSUE THREAD

**Issue by Dunge** [bitnami/charts#27918]
### Name and Version

bitnami/redis 19.6.1

### What architecture are you using?

None

### What steps will reproduce the bug?

I have a k8s cluster with two helm deployments of bitnami/redis in a separate namespace for a multi-tenant concept.
I updated from chart 17.10.3 to 19.6.1 (so Redis version 7.0.11 to 7.2.5).
Using the master-replica / sentinel type (3 pods each).

Previously the two sets of instances worked separately with absolutely no issues.

After upgrading, they all merged together as one big Redis service. I saw one master having 5 replicas connected, and sentinel logs switching the master every few seconds. This caused all my data to become corrupted and some secure information to be exposed to the other tenant that shouldn't have been visible. You can see how problematic this episode has been for us.

What could have caused the replicas from one deployment to connect to the master of another following this update? Was there anything changed in the service discovery part?

I finally managed to fix my issue by setting a different name under `sentinel.masterSet` on both deployments. Unfortunately had to delete my storage completely because the data was filled with invalid entries. Lost a lot of information in the process.

### Are you using any custom parameters or values?
```yaml
sentinel:
  enabled: true
  resourcesPreset: "small"

auth:
  enabled: false
  sentinel: false

master:
  persistence:
    size: {{ .Values.RedisDataSize }}
  resourcesPreset: "medium"
  disableCommands: []
    
replica:
  persistence:
    size: {{ .Values.RedisDataSize }}
  resourcesPreset: "medium"
  disableCommands: []
  
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  resourcesPreset: "small"

useHostnames: false
```
### What is the expected behavior?

Different deployments in different namespaces are to be isolated.

### What do you see instead?

Different deployments in different namespace connected to each other
