### ISSUE TITLE
KC_HOSTNAME_URL is set when it should not be (regression)

### ISSUE THREAD

**Issue by wkbrd** [bitnami/charts#27911]
### Name and Version

bitnami/keycloak 21.6.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Used the chart with:
I am using `proxy=edge,production=true`, `ingress.enabled=true`, `ingress.hostname=`, and `ingress.extraHosts[0].name=,ingress.extraHosts[0].path`

The chart does not work properly (pod goes into crashloop)

The `KC_HOSTNAME_URL` in my environment is resolving to `https://`.

This is due to the proxy hostname being used by Keycloak when proxy=edge is enabled.

This causes Keycloak to not start:
```
Invalid base URL for FrontEnd URLs: https://
2024-07-11T12:41:49.937012733-04:00 ERROR: Expected scheme-specific part at index 6: https:
2024-07-11T12:41:49.937043946-04:00 For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```
### Are you using any custom parameters or values?

Yes.
```
proxy=edge, production=true, ingress.enabled=true, ingress.hostname=, and ingress.extraHosts[0].name=,ingress.extraHosts[0]
```
### What is the expected behavior?

pod comes up and works properly.

### What do you see instead?

pod goes into crash loop

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by ngc4579** [comment]
I'm not sure if this is related, but the latest Chart version _21.6.1_ also breaks our existing installation:

```yaml
keycloak:
  production: true
  proxy: edge
  httpRelativePath: /<redacted>/keycloak/auth/
  ingress:
    enabled: true
    ingressClassName: nginx
    path: '{{ trimSuffix "/" .Values.httpRelativePath}}(/|$)(.*)'
    pathType: ImplementationSpecific
    hostname: <redacted>
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/affinity-mode: persistent
      nginx.ingress.kubernetes.io/session-cookie-path: '{{ trimSuffix "/" .Values.httpRelativePath}}'
      nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "true"
```

While Pods are starting as expected, firing up Keycloak in a browser results in an empty page refusing to load properly apart from a loading animation. Browser tools show an HTTP 418 error:

```
scheme
	https
host
	<redacted>
filename
	/realms/master/protocol/openid-connect/3p-cookies/step1.html
```

Note that the httpRelativePath part is missing from the request.
