### ISSUE TITLE
Redis Chart not found - Helm release using Flux CD 

### ISSUE THREAD

**Issue by nikhilbalekundargi** [bitnami/charts#2791]
**Which chart**:
Redis

**Describe the bug**

We are using flux in our GKE cluster to deploy Kubernetes yamls and deploy helm charts. Below is the helm release yaml for deploying Redis to our cluster using Flux helm operator -
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/locked: "true"
spec:
  releaseName: redis
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: bitnami/redis
  values:
    usePassword: true
    service:
      type: ClusterIP
      port: 6379
    cluster:
      enabled: true
```
Flux helm operator is not deploying the Redis to our cluster. Below is the error from logs
```
ts=2020-06-09T14:06:21.839631193Z caller=release.go:75 component=release release=redis targetNamespace=redis resource=redis:helmrelease/redis helmVersion=v3 info="starting sync run"
ts=2020-06-09T14:06:21.847528763Z caller=release.go:81 component=release release=redis targetNamespace=redis resource=redis:helmrelease/redis helmVersion=v3 error="failed to prepare chart for release: could not find valid chart source configuration for release"
```

**Expected behavior**
Redis should be deployed to our cluster

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.2", GitCommit:"a6ea66349ae3015618da4f547677a14b9ecc09b3", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
Hi, I just checked that the chart is published in the registry, for that I added the registry using the Helm CLI and checked `bitnami/redis` is present:
```console
$ helm repo add bitnami https://charts.bitnami.com/bitnami
"bitnami" has been added to your repositories

$ helm search repo bitnami/redis
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/redis        	10.6.18      	6.0.4      	Open source, advanced key-value store. It is of...
bitnami/redis-cluster	2.2.3        	6.0.4      	Open source, advanced key-value store. It is of...
```

Apart from that, I am not sure how can I help you, it seems something is not configured properly in the Flux helm operator.

**Comment by nikhilbalekundargi** [comment]
> Hi, I just checked that the chart is published in the registry, for that I added the registry using the Helm CLI and checked `bitnami/redis` is present:
> 
> ```
> $ helm repo add bitnami https://charts.bitnami.com/bitnami
> "bitnami" has been added to your repositories
> 
> $ helm search repo bitnami/redis
> NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
> bitnami/redis        	10.6.18      	6.0.4      	Open source, advanced key-value store. It is of...
> bitnami/redis-cluster	2.2.3        	6.0.4      	Open source, advanced key-value store. It is of...
> ```
> 
> Apart from that, I am not sure how can I help you, it seems something is not configured properly in the Flux helm operator.

Yes its working by adding the repo to cluster and if i run the command helm install my-redis bitnami/redis. But not working using flux helm release.

**Comment by carrodher** [comment]
It sounds like there is an issue with the Flux YAML, I didn't use Flux previously nor it's something we provide support for, but taking a look at the above code block it seems the indentation doesn't look very well-formed, in the same way, `service` as root parameter doesn't exist, you need to use `master.service`, `slave.service`, `metrics.service`, etc, [here](https://github.com/bitnami/charts/tree/master/bitnami/redis#parameters) you can find a full list with all the parameters (in one line format, you need to expand them to be used as YAML).

In the same way a `values:` section is needed, maybe something like this code can work
```yaml
spec:
  releaseName: redis
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: bitnami/redis
  values:
    usePassword: true
    master:
      service:
        type: ClusterIP
        port: 6379
    cluster:
      enabled: true
```

As I mention, we don't provide support for this kind of tools for deployments I was taking a look at the official repositories, like this one: https://github.com/fluxcd/helm-operator-get-started
I am sure in those repositories you can find more information. As part of the Bitnami team, I can help with specific issues in the chart itself but not with external tools to deploy charts.

**Comment by nikhilbalekundargi** [comment]
> It sounds like there is an issue with the Flux YAML, I didn't use Flux previously nor it's something we provide support for, but taking a look at the above code block it seems the indentation doesn't look very well-formed, in the same way, `service` as root parameter doesn't exist, you need to use `master.service`, `slave.service`, `metrics.service`, etc, [here](https://github.com/bitnami/charts/tree/master/bitnami/redis#parameters) you can find a full list with all the parameters (in one line format, you need to expand them to be used as YAML).
> 
> In the same way a `values:` section is needed, maybe something like this code can work
> 
> ```yaml
> spec:
>   releaseName: redis
>   chart:
>     repository: https://charts.bitnami.com/bitnami
>     name: bitnami/redis
>   values:
>     usePassword: true
>     master:
>       service:
>         type: ClusterIP
>         port: 6379
>     cluster:
>       enabled: true
> ```
> 
> As I mention, we don't provide support for this kind of tools for deployments I was taking a look at the official repositories, like this one: https://github.com/fluxcd/helm-operator-get-started
> I am sure in those repositories you can find more information. As part of the Bitnami team, I can help with specific issues in the chart itself but not with external tools to deploy charts.

@carrodher Thank you for the reply.

My bad, I missed values in the yaml, it was a copy paste error. Anyway, using the below yaml still the same issue

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/locked: "true"
spec:
  releaseName: redis
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: bitnami/redis
  values:
    usePassword: true
    master:
      service:
        type: ClusterIP
        port: 6379
    cluster:
      enabled: true
```

logs -

ts=2020-06-10T11:06:38.496189471Z caller=release.go:75 component=release release=redis targetNamespace=redis resource=redis:helmrelease/redis helmVersion=v3 info="starting sync run"
ts=2020-06-10T11:06:38.509430664Z caller=release.go:81 component=release release=redis targetNamespace=redis resource=redis:helmrelease/redis helmVersion=v3 error="failed to prepare chart for release: could not find valid chart source configuration for release"

**Comment by nikhilbalekundargi** [comment]
I changed the yaml to include version of the chart as below -

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/locked: "true"
spec:
  releaseName: redis
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: bitnami/redis
    version: 10.7.0
  values:
    usePassword: true
    master:
      service:
        type: ClusterIP
        port: 6379
    cluster:
      enabled: true
```

Logs -
```
ts=2020-06-10T11:54:40.846797215Z caller=release.go:81 component=release release=redis targetNamespace=redis resource=redis:helmrelease/redis helmVersion=v3 error="failed to prepare chart for release: chart unavailable: chart \"bitnami/redis\" version \"10.7.0\" not found in https://charts.bitnami.com/bitnami repository"
```

I even tried with version 10.6.8. version not found.

**Comment by nikhilbalekundargi** [comment]
We have found the correct config to deploy redis using Helm release. Below is the yaml for reference

```yaml
Below is the working yaml for reference -
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/locked: "true"
spec:
  releaseName: redis
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: redis
    version: 10.6.18
  values:
    usePassword: true
    master:
      service:
        type: ClusterIP
        port: 6379
    cluster:
      enabled: true
```


Closing the issue
