### ISSUE TITLE
[bitnami/apisix] Wait container at control plane fails with untrusted TLS certificates at etcd

### ISSUE THREAD

**Issue by vladimirpetr** [bitnami/charts#27924]
### Name and Version

bitnami/apisix 3.3.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set auto TLS for etcd
```yaml
etcd:
  auth:
    client:
      secureTransport: true
      useAutoTLS: true
```
2. Install chart with the default _decoupled_ mode kept

### Are you using any custom parameters or values?

```yaml
    etcd:
      enabled: true
      replicaCount: 1
      auth:
        rbac:
          create: false
          existingSecret: apisix-etcd-credentials
          existingSecretPasswordKey: password
        client:
          secureTransport: false
          useAutoTLS: true
    controlPlane:
      enabled: true
      existingSecret: apisix-api-tokens
      existingSecretAdminTokenKey: admin-token
      existingSecretViewerTokenKey: viewer-token
      extraConfig:
        deployment:
          etcd:
            tls:
              verify: false
    dataPlane:
      enabled: true
      pdb:
        maxUnavailable: "1"
      podAntiAffinityPreset: soft
      resources:
        limits:
          cpu: 300m
          memory: 300Mi
        requests:
          cpu: 100m
          memory: 300Mi
      ingress:
        enabled: false
      extraConfig:
        deployment:
          etcd:
            tls:
              verify: false
```

### What is the expected behavior?

The wait container as defined for the control plane pod in the helper templates should support skipping certificate verification and/or path to the corresponding CA certificate.

### What do you see instead?

The init container keeps failing due to an untrusted certificate at etcd. As a result, the control plane container never comes up:

```console
apisix-control-plane-544bccf49d-bb2kh wait-for-etcd curl: (7) Failed to connect to apisix-etcd port 2379 after 1 ms: Couldn't connect to server
apisix-control-plane-544bccf49d-bb2kh wait-for-etcd curl: (60) SSL certificate problem: self-signed certificate
apisix-control-plane-544bccf49d-bb2kh wait-for-etcd More details here: https://curl.se/docs/sslcerts.html
apisix-control-plane-544bccf49d-bb2kh wait-for-etcd
apisix-control-plane-544bccf49d-bb2kh wait-for-etcd curl failed to verify the legitimacy of the server and therefore could not
apisix-control-plane-544bccf49d-bb2kh wait-for-etcd establish a secure connection to it. To learn more about this situation and
apisix-control-plane-544bccf49d-bb2kh wait-for-etcd how to fix it, please visit the web page mentioned above.
```
