### ISSUE TITLE
bitnami/postgres-ha pgpool crash issues

### ISSUE THREAD

**Issue by DeprecatedLuke** [bitnami/charts#27920]
### Name and Version

bitnami/postgres-ha:15.5.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. default configuration with increased resource limits and changed passwords.
2. k3s v1.30 cluster, ceph rbd file backend, calico vxlan with hostendpoint configured.
3. wait until the bug occurs, setting low limits seems to cause the bug to occur much faster.

### Are you using any custom parameters or values?
```yaml
  postgresql-ha:
    clusterDomain: custom.cluster
    global:
      postgresql:
        database: gitea
        password: anything
        username: gitea
    enabled: true
    postgresql:
      replicaCount: 2
      upgradeRepmgrExtension: false
      repmgrPassword: anything
      postgresPassword: anything
      password: anything
    pgpool:
      adminPassword: anything
      replicaCount: 1
      resources:
        limits:
          cpu: 375m
          ephemeral-storage: 1Gi
          memory: 512Mi
        requests:
          cpu: 250m
          ephemeral-storage: 50Mi
          memory: 256Mi
    primary:
      persistence:
        size: 10Gi
```
### What is the expected behavior?

pgpool restarting properly.

### What do you see instead?

After a month or two, pgpool service gets stuck in a crashloop with no logs being output to the console. Deleting the pod is the only way to fix it.

### Additional information

Pgpool is the only pod that is showing this behavior out of around a hundred other pods, increased limits seemed to somewhat mitigate the issue, seems like an early crash at the entry point (before any logging occurs).

Unfortunately, there are pretty much no logs to provide as there aren't any except restart counter going up and replicating it is very inconsistent.
