### ISSUE TITLE
[bitnami/apisix] Wrong type of field loadBalancerSourceRanges

### ISSUE THREAD

**Issue by zeritti** [bitnami/charts#27960]
### Name and Version

bitnami/apisix 3.3.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Keep service type of the data plane at its default value `LoadBalancer`
2. Set loadbalancer source ranges, e.g.
```yaml
dataPlane:
  service:
    loadBalancerSourceRanges:
      - "192.168.1.0/24"
      - "192.168.2.0/24"
```
3. Install the chart

### Are you using any custom parameters or values?

```yaml
dataPlane:
  service:
    type: LoadBalancer
    loadBalancerSourceRanges:
      - "192.168.1.0/24"
      - "192.168.2.0/24"
etcd:
  replicaCount: 1
dashboard:
  enabled: false
```

### What is the expected behavior?

The defined source ranges of the loadbalancer service have been set and the release installed.

### What do you see instead?

Installation fails:

```
Error: 1 error occurred:
	* Service "apisix-data-plane" is invalid: spec.LoadBalancerSourceRanges: Invalid value:
 "[192.168.1.0/24 192.168.2.0/24]": must be a list of IP ranges. For example, 10.240.0.0/24,10.250.0.0/24
```

as the field `loadBalancerSourceRanges` is a string instead of an array. That is, instead of the correct

```yaml
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 192.168.1.0/24
    - 192.168.2.0/24
```

the field gets rendered as

```yaml
spec:
  type: LoadBalancer
  loadBalancerSourceRanges: [192.168.1.0/24 192.168.2.0/24]
```

### Additional information

The wrong type is present in all the service templates in the chart except for that of etcd. The service templates define the field like this:

```yaml
 {{- if and (eq .Values.controlPlane.service.type "LoadBalancer") (not (empty .Values.controlPlane.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.controlPlane.service.loadBalancerSourceRanges }}
 {{- end }}
```

To maintain the required array, it should be defined like this:
```yaml
 {{- if and (eq .Values.controlPlane.service.type "LoadBalancer") (not (empty .Values.controlPlane.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ toYaml .Values.controlPlane.service.loadBalancerSourceRanges | nindent 4 }}
 {{- end }}
```
