### ISSUE TITLE
Pod Labels are not applied to Deployment and PDB matchLabels selector

### ISSUE THREAD

**Issue by BiancaRapp** [bitnami/charts#27974]
### Name and Version

bitnami/matomo 7.3.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install bitnami/matomo chart with podLabels

### Are you using any custom parameters or values?

```yaml
podLabels:
  app.kubernetes.io/component: app
cronjobs:
  taskScheduler:
    enabled: false
  archive:
    enabled: true
    schedule : 5 * * * *
```

### What is the expected behavior?

Deployment and PDB have:
```yaml
selector:
  matchLabels: 
    app.kubernetes.io/instance: matomo-dev
    app.kubernetes.io/name: matomo
    app.kubernetes.io/component: app
```

### What do you see instead?

New label is only added to the Pod labels. It's missing in the matchLabels of PDB and deployment:
```yaml
selector:
  matchLabels: 
    app.kubernetes.io/instance: matomo-dev
    app.kubernetes.io/name: matomo
```

### Additional information

Default label selector of pod disruption budget is not working, when using the archive cron job. PDB selector is then also matching the archive cron job pod.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by danjmccay** [comment]
As a work-around, you can create a pdb using extraDeploy:

```
pdb:
  create: false

extraDeploy:
  - |
    apiVersion: policy/v1
    kind: PodDisruptionBudget
    metadata:
      name: matomo
    spec:
      minAvailable: 2
      selector:
        matchLabels:
          app.kubernetes.io/component: app
          app.kubernetes.io/instance: matomo
          app.kubernetes.io/name: matomo
```
