### ISSUE TITLE
[bitnami/fluentd] Mismatch between ServiceMonitor endpoint port name and service port name

### ISSUE THREAD

**Issue by pbn4** [bitnami/charts#2802]
**Which chart**:
[bitnami/fluentd] 1.2.0

**Describe the bug**
Basically the same as https://github.com/bitnami/charts/issues/2763. 

ServiceMonitor:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    helm.fluxcd.io/antecedent: monitoring:helmrelease/fluentd
  generation: 1
  labels:
    app.kubernetes.io/instance: fluentd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluentd
    helm.sh/chart: fluentd-1.2.0
  name: fluentd
  namespace: monitoring
spec:
  endpoints:
  - path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: fluentd
      app.kubernetes.io/name: fluentd
```

Fluentd Metrics Service:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    helm.fluxcd.io/antecedent: monitoring:helmrelease/fluentd
    prometheus.io/path: /metrics
    prometheus.io/port: "24231"
    prometheus.io/scrape: "true"
  labels:
    app: metrics
    app.kubernetes.io/instance: fluentd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluentd
    helm.sh/chart: fluentd-1.2.0
  name: fluentd-metrics
  namespace: monitoring
spec:
  clusterIP: 172.20.220.112
  ports:
  - name: tcp-metrics
    port: 24231
    protocol: TCP
    targetPort: 24231
  selector:
    app.kubernetes.io/instance: fluentd
    app.kubernetes.io/name: fluentd
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
