### ISSUE TITLE
All 3 Redis nodes configured as master node after restart kubernetes cluster

### ISSUE THREAD

**Issue by suxiaoxiaomm** [bitnami/charts#28114]
### Name and Version

redis-16.13.2

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Kubernetes 1.27. 
2. Running redis cluster with 3 nodes, 3 sentinels. No issues
3. Shutdown kuberentes cluster and then restart the cluster 
4. During Redis cluster startup, from log, I can see all 3 redis nodes were configured as master (all 3 nodes logged this line of log: `INFO  ==> Configuring the node as master`)
5. Under this condition, my applications can only connect to redis, but not able to write as not enough replica avaliable(I configured at least 1 replica)

### Are you using any custom parameters or values?

```yaml
global:
  storageClass: "default-custom"
  redis:
    password: "$APP_SEC_REDIS_PASSWORD"

auth:
  password: "$APP_SEC_REDIS_PASSWORD"

master:
  persistence:
    size: "4Gi"
  nodeSelector:
    pool: "database"
  resources:
    memory: "1Gi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "250m"

replica:
  podLabels:
    app: redis
  nodeSelector:
    pool: "database"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - redis
        topologyKey: kubernetes.io/hostname
  persistence:
    size: "4Gi"
  resources:
    requests:
      memory: "1.5Gi"
      cpu: "200m"
    limits:
      memory: "5Gi"
      cpu: "500m"

sentinel:
  enabled: true
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "250m"

metrics:
  enabled: true
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "100m"

pdb:
  create: true
  minAvailable: 2

commonConfiguration: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""
  # use key-space notification
  notify-keyspace-events KEA
  maxmemory 2000mb
  min-replicas-to-write 1
  min-replicas-max-lag 5
  maxmemory-policy allkeys-lru
  repl-diskless-sync yes
  client-output-buffer-limit normal 0 0 0 
  client-output-buffer-limit slave 512mb 128mb 60
  client-output-buffer-limit pubsub 32mb 8mb 60
```

### What is the expected behavior?

Expect only one node to be configured as master, the other 2 nodes are configured as replicas.

### What do you see instead?

All 3 nods are configured as masters.
