### ISSUE TITLE
[bitnami/keycloak] proxy:edge and httpRelativePath in combination are broken

### ISSUE THREAD

**Issue by MaxRink** [bitnami/charts#28121]
### Name and Version

bitnami/keycloak 21.6.3

### What architecture are you using?

None

### What steps will reproduce the bug?

we currently use 
```
proxy: edge
httpRelativePath: "/auth/"
ingress:
      enabled: true
      ingressClassName: keycloak
      hostname: keycloak.mytld.de
```

based upon that config i wouldd expect keycloak to listen on keycloak.mytld.de/auth/realms/master for the master real, but that isnt happening, its keycloak.mytld.de/realms/master
Thus all login into the UI fails, as all URLs returned by keyclaok in its rednered resources are wrong (/resources instead of /auth/resources for example).

Manually adding /auth to the  `KC_HOSTNAME_URL` makes everything work again, but IMO im not a friend of that approach
Keycloak should probably use x-forwarded headers behind an ingress instead of listening on an hostname

### What do you see instead?

A broken keycloak

**Comment by juan131** [comment]
Hi @MaxRink 

We just merged a PR (see https://github.com/bitnami/charts/pull/27890), could you please give a try to the version `21.7.0` as soon as it gets released (usually within a couple of hours)? Sorry for the incoveniences

**Comment by davidfrickert** [comment]
> Hi @MaxRink
> 
> We just merged a PR (see #27890), could you please give a try to the version `21.7.0` as soon as it gets released (usually within a couple of hours)? Sorry for the incoveniences

hey, not sure if this is the proper channel but this seems to be a breaking change since previously "proxy" held "edge" but after this change it can only have "forwarded" or "xforwarded", thus breaking existent installations.

**Comment by davidfrickert** [comment]
also it seems that setting "proxy" to "forwarded" does not even work because the chart does not allow setting production mode if "proxy" is not "edge"

**Comment by MaxRink** [comment]
> also it seems that setting "proxy" to "forwarded" does not even work because the chart does not allow setting production mode if "proxy" is not "edge"

Yup, that PR seems a bit hasty.
We use flux so i used postRenderers for implementing that with the 21.6.x releases
```yaml
  postRenderers:
    - kustomize:
        patches:
          # nuke the ENV var "KC_HOSTNAME_URL" from the keycloak statefulset
          - target:
              version: v1
              kind: StatefulSet
              name: keycloak
            patch: |
              apiVersion: apps/v1
              kind: StatefulSet
              metadata:
                name: keycloak
              spec:
                template:
                  spec:
                    containers:
                      - name: keycloak
                        env:
                          - name: KC_HOSTNAME_URL
                            $patch: delete
          # add "KEYCLOAK_PROXY_HEADERS: xforwarded" and "KEYCLOAK_HOSTNAME_STRICT: false" to the keycloak env configmap
          - target:
              version: v1
              kind: ConfigMap
              name: keycloak-env-vars
            patch: |
              - op: add
                path: /data/KEYCLOAK_PROXY_HEADERS
                value: xforwarded
              - op: add
                path: /data/KEYCLOAK_HOSTNAME_STRICT
                value: "false"
```
I will probably put up a PR to fix that tomorrow and with Keycloak 25 that could be migrated to hostname v2, which is a lot cleaner

**Comment by juan131** [comment]
Hi everyone!

I'm a little bit confused, what chart version are you using? Latest one? Could you please the exact values and version you're using? I'd like to reproduce the issue.

**Comment by davidfrickert** [comment]
> Hi everyone!
> 
> I'm a little bit confused, what chart version are you using? Latest one? Could you please the exact values and version you're using? I'd like to reproduce the issue.

For me 21.7.0 onwards is broken. 

values:

```
        auth:
          existingSecret: keycloak
        postgresql: 
          enabled: false
        externalDatabase:
          host: tools-pg
          user: bn_keycloak
          database: bitnami_keycloak
          existingSecret: bn-keycloak.tools-pg.credentials.postgresql.acid.zalan.do
          existingSecretUserKey: username
          existingSecretPasswordKey: password
        ingress:
          annotations: {{ include "external-tls.annotations" . | fromYaml | toJson }}
          enabled: true
          hostname: iam.djf.lol
          tls: true
        production: true
        proxy: edge
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 768Mi
        replicaCount: 3
```

The issue is that proxy: edge is no longer a valid value. the new proper value would be "forwarded" or "xforwarded". 
But the chart has some code that specifically does not let me use production mode without using proxy: edge... So yeah, the fix here would probably go by changing requirement of proxy: edge to proxy: forwarded or xforwarded to use production mode? Idk what "edge" maps to in the new format.
