### ISSUE TITLE
[bitnami/valkey-cluster] Cannot enable external-access

### ISSUE THREAD

**Issue by cloudymax** [bitnami/charts#28162]
### Name and Version

bitnami/valkey-cluster 0.1.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Enable external access
```yaml
cluster:
  init: true
  nodes: 6
  replicas: 1
  externalAccess:
    enabled: true
```

2. Attempt to template and get error

>$ helm template . -f test.yaml

> Error: template: valkey-cluster/templates/svc-cluster-external-access.yaml:17:38: executing "valkey-cluster/templates/svc-cluster-external-access.yaml" at <include "common.names.fullname" .>: error calling include: template: valkey-cluster/charts/common/templates/_names.tpl:27:14: executing "common.names.fullname" at <.Values.fullnameOverride>: can't evaluate field Values in type int
>
> Use --debug flag to render out invalid YAML

### Are you using any custom parameters or values?

```yaml
#fullnameOverride: "valkey"

usePassword: true
password: ""
existingSecret: "valkey-credentials"
existingSecretPasswordKey: "valkey_password"

tls:
  enabled: true
  authClients: true
  autoGenerated: true

service:
  ports:
    valkey: 6379
  type: ClusterIP
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster

persistence:
  enabled: true
  path: /bitnami/valkey/data
  storageClass: "local-path"
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: 8Gi

persistentVolumeClaimRetentionPolicy:
  enabled: false
  whenScaled: Retain
  whenDeleted: Retain

valkey:
  command: []
  args: []
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  podManagementPolicy: Parallel
  automountServiceAccountToken: false
  hostNetwork: false
  useAOFPersistence: "yes"
  containerPorts:
    valkey: 6379
    bus: 16379
  resourcesPreset: "nano"
  resources: {}

cluster:
  init: true
  nodes: 6
  replicas: 1
  externalAccess:
    enabled: true
    hostMode: false
    service:
      disableLoadBalancerIP: false
      type: LoadBalancer
      port: 6379
      loadBalancerIP: []
      loadBalancerSourceRanges: []

metrics:
  ## @param metrics.enabled Start a side-car prometheus exporter
  ##
  enabled: false
```

### What is the expected behavior?

It should template

### What do you see instead?

the error included above
