### ISSUE TITLE
[bitnami/keycloak] new hostname env var does not add httpRelativePath

### ISSUE THREAD

**Issue by gtudan** [bitnami/charts#28161]
### Name and Version

bitnami/keycloak:21.7.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install the chart with a httpRelativePath configured

### Are you using any custom parameters or values?

```yaml
keycloak:
  enabled: true
  httpRelativePath: /auth/
  ingress:
    enabled: true
    hostname: myHost.local
 ```

### What is the expected behavior?

The env var KC_HOSTNAME_URL should match the full URL: https://myHost.local/auth

### What do you see instead?

The variable only contains the hostname, but not the path:
```
KC_HOSTNAME_URL:              https://myHost.local
```
