### ISSUE TITLE
[bitnami/discourse] Discourse forum - Sidekiq mem leak

### ISSUE THREAD

**Issue by crazyfree** [bitnami/charts#28171]
### Name and Version

bitnami/discourse:3.2.4-debian-12-r0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Go install discourse from the helm chart https://artifacthub.io/packages/helm/bitnami/discourse 
2. Setup daily backup to S3 with big database, mine contains 9Gb of data (60k users and ton of posts)
3. Keep system running few days without access 
4. Check sidekiq RSS in path `/sidekiq/busy`
5. You'll see that mem increasing constantly even no access to frontend at all. In my case, it crashed after 5 days when I set values.yaml like below: 

### Are you using any custom parameters or values?

```yaml
resources:
  limits:
    memory: 4Gi
  requests:
    memory: 2Gi
discourse:
  skipInstall: true
  resources:
    limits:
      memory: 4Gi
    requests:
      memory: 2Gi
```

### What is the expected behavior?

either the sidekiq mem will be a constant or at least have a method to do health check and restart automatically when the limit reached. 

### What do you see instead?

sidekiq mem increasing day by day until it consumed all the RAM after all ram was consumed, the sidekiq process doesn't get terminated, it hangs forever, so I cannot know how to do health check and restart it automatically. 

### Additional information
![Screenshot 2024-07-19 at 13 17 55](https://github.com/user-attachments/assets/47653f40-e356-4611-97d2-fe54f5941817)

as you see in the screenshot, the 1 day started instance memory keeps increasing until reached the limitation

**Comment by crazyfree** [comment]
@javsalgar the setup for the sidekiq process in the bitnami discourse repo is totally different than in the discourse official repo. So it's quite hard for me to reach out upstream support.

**Comment by crazyfree** [comment]
plus, In the effort of reducing sidekiq worker threads I found that the `UNICORN_WORKERS` and `UNICORN_SIDEKIQS` env vars got no use in the bitnami/discourse image.  

Can you show me the alternative way to reduce sidekiq worker threads @javsalgar

**Comment by jotamartos** [comment]
Hi @crazyfree,

Those parameters are not supported in the Bitnami solution. However, we are open to contributions, would you like to improve the solution? You can follow the contributing guidelines in the Bitnami containers repo. The team will be more than happy to review the changes. You will need to add support for those env vars in the env file and the method that configures them in the conf file.

https://github.com/bitnami/containers/blob/main/bitnami/discourse/3/debian-12/rootfs/opt/bitnami/scripts/discourse-env.sh
https://github.com/bitnami/containers/blob/main/bitnami/discourse/3/debian-12/rootfs/opt/bitnami/scripts/libdiscourse.sh#L245

As a workaround, you can also use the DISCOURSE_EXTRA_CONF_CONTENT env var that takes care of appending all the configuration lines you need to the conf file. 

https://github.com/bitnami/containers/blob/main/bitnami/discourse/3/debian-12/rootfs/opt/bitnami/scripts/libdiscourse.sh#L276

Would that work for you?

**Comment by crazyfree** [comment]
well, before we can patch that, 
here is the workaround. 
The idea is to find zombie process and let the control plane does the restart.  

```yaml
livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                SIDEKIQ_PID=$(pgrep -f ^sidekiq)
                zombie_children=$(ps -eo pid,ppid,state | grep "$SIDEKIQ_PID Z" | wc -l)
                if [ "$zombie_children" -gt 0 ]; then
                  echo "Sidekiq has a zombie child"
                  exit 1
                fi
                exit 0
```

**Comment by crazyfree** [comment]
FYI, I realized that the command above won't help, some times, sidekiq just stop unreasonable. I'm thinking of adding dump-init to sidekiq container but seems I have to modify `sidekiq.command` to 
```yaml
command:
   - /shared/dump-init
   - -- 
   - /bin/bash
```
which is default to `["/opt/bitnami/scripts/discourse/entrypoint.sh"]`. Of course it's not success since the `/opt/bitnami/scripts/discourse/entrypoint.sh` has to be changed as well. 

Things become more and more complicated 🥵

**Comment by jotamartos** [comment]
The entrypoint is a script that performs some actions before [running the "run.sh" script](https://github.com/bitnami/containers/blob/main/bitnami/discourse/3/debian-12/rootfs/opt/bitnami/scripts/discourse/run.sh). You can mount your custom run.sh script in the pod/container and change the sidekiq.args parameter to execute your customized script.

```
## @section Sidekiq container parameters
sidekiq:
  ## @param sidekiq.command Custom command to override image cmd (evaluated as a template)
  ##
  command: ['/opt/bitnami/scripts/discourse/entrypoint.sh']
  ## @param sidekiq.args Custom args for the custom command (evaluated as a template)
  ##
  args: ['/opt/bitnami/scripts/discourse-sidekiq/run.sh']
```
