### ISSUE TITLE
Postgrsql keep restarting

### ISSUE THREAD

**Issue by xingya1822** [bitnami/charts#28174]
### Name and Version

bitnami/postgresql  15.5.16

### What architecture are you using?

amd64

### What steps will reproduce the bug?

just install with custom values

### Are you using any custom parameters or values?

```yaml
global:
  imageRegistry: "172.25.128.67:9002"
image:
  registry: "172.25.128.67:9002"
  repository: bitnami/postgresql
  tag: 16.3.0-debian-12-r19
auth:
  postgresPassword: "#Fgglgy0223"
primary:
  persistence:
    size: 50Gi
    storageClass: "rook-ceph-block"
  initdb:
    scripts:
      init-user-db.sh: |
        #!/bin/bash
        echo "------- 初始化XWIKI数据库 -------"
        set -e
        export PGPASSWORD='#Fgglgy0223'
        psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
        CREATE USER xwiki with ENCRYPTED PASSWORD 'xwiki';
        CREATE DATABASE xwiki;
        GRANT ALL PRIVILEGES ON DATABASE xwiki TO xwiki;
        \c xwiki
        GRANT USAGE,CREATE ON SCHEMA public TO xwiki;
        EOSQL
```

### What is the expected behavior?

postgresql run stablely

### What do you see instead?

postgresql keep restart

### Additional information
```
Readiness probe failed: 127.0.0.1:5432 - rejecting connections

Liveness probe failed: command "/bin/sh -c exec pg_isready -U \"postgres\" -h 127.0.0.1 -p 5432" timed out
```
