### ISSUE TITLE
Unable to set the absolute value for the memoryHighWatermark using templating

### ISSUE THREAD

**Issue by saravanan-ai** [bitnami/charts#28175]
### Name and Version

"bitnami/rabbitmq""14.6.1"

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. When I pass values like
```yaml
memoryHighWatermark:
  enabled: true
  type: absolute
  value: "{{ MEM_HIGH_WATERMARK }}"
```
and in the prod.yaml
`MEM_HIGH_WATERMARK: 1024Mi`
in qa.yaml
`MEM_HIGH_WATERMARK: 1024Mi`
in dev.yaml
`MEM_HIGH_WATERMARK: 819Mi`

It gives the error as {{ MEM_HIGH_WATERMARK }} is invalid SI quantity.

2. Now instead of if I hardcode the value as
```yaml
memoryHighWatermark:
  enabled: true
  type: absolute
  value: 819Mi
  ```
this works!! But I don't want this to be hardcoded. For CPU requests and memory also I pass it like "{{ CPU_REQUEST }}" and  "{{ MEM_REQUEST }}", this is picking the right value and it is working. Only the absolute value for the memory watermark is not working

### What is the expected behavior?

It should accept the value

### What do you see instead?

```{{ MEM_HIGH_WATERMARK }} is invalid SI quantity```

### Additional information

Could you check this?

Also, I have used value as Mi only not as MB.

I use helm chart version "14.6.1" of rabbitmq
