### ISSUE TITLE
[bitnami/redmine] Installation failing on OpenShift due to added capabilities (even with global.compatibility.openshift.adaptSecurityContext set to force)

### ISSUE THREAD

**Issue by kastl-ars** [bitnami/charts#28187]
### Name and Version

bitnami/redmine 29.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. I am running an OpenShift cluster.
2. I make sure to set the `global.compatibility.openshift.adaptSecurityContext` flag to `force`, to make sure the chart adapts everything so it can run on OpenShift.
3. The replicaset is forbidden due to the added capabilities (see [line 242](https://github.com/bitnami/charts/blob/main/bitnami/redmine/values.yaml#L242)).
4. I manually set `containerSecurityContext.capabilities.add` to `null` to overwrite the default value and do not add any capabilites
5. The chart installs fine and the pod seems to run fine.

## Working

```
[...]
global:
  compatibility:
    openshift:
      adaptSecurityContext: force
containerSecurityContext:
  capabilities:
    add: null
[...]
```

## Failing

```
[...]
global:
  compatibility:
    openshift:
      adaptSecurityContext: force
[...]
```

### What is the expected behavior?

Setting the  `global.compatibility.openshift.adaptSecurityContext` flag to `force` should also make sure that the capabilities do not get added.

### What do you see instead?

The replicaset for redmine is forbidden due to the capabilities that are to be added.
