### ISSUE TITLE
[bitnami/harbor] failed to initialize database: register db Ping `default`, failed to connect to `host=harbor-postgresql user=postgres database=registry`: server error (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01)) when setting existingSecret

### ISSUE THREAD

**Issue by jdaln** [bitnami/charts#28188]
### Name and Version

bitnami/harbor 22.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I use the following that I `kubectl apply -f` (of course that automatically takes care of base64enc nowadays):

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret-vars
  namespace: harbor
type: Opaque
stringData:
  CSRF_KEY: "Whateverthiscanbe"
  HARBOR_ADMIN_PASSWORD: "12345678Test"
  HARBOR_DATABASE_PASSWORD: "secure-postgres-password"
  POSTGRESQL_PASSWORD: "secure-postgres-password"
  REGISTRY_CREDENTIAL_USERNAME: "registryuser"
  REGISTRY_CREDENTIAL_PASSWORD: "passwordfortest"
  postgres-password: "secure-postgres-password"
```

and the values.yaml mentioned after.

I get the following error:

```console
$ kubectl logs harbor-exporter-657cb4d677-rdzv4 -n harbor
harbor-exporter 16:20:08.02 INFO  ==> 
harbor-exporter 16:20:08.11 INFO  ==> Welcome to the Bitnami harbor-exporter container
harbor-exporter 16:20:08.20 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
harbor-exporter 16:20:08.21 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
harbor-exporter 16:20:08.21 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
harbor-exporter 16:20:08.22 INFO  ==> 
harbor-exporter 16:20:08.31 INFO  ==> ** Starting harbor-exporter setup **
harbor-exporter 16:20:08.32 INFO  ==> No custom certificates were installed in the system

harbor-exporter 16:20:08.41 INFO  ==> ** harbor-exporter setup finished! **
harbor-exporter 16:20:09.21 INFO  ==> ** Wait for database connection **
harbor-exporter 16:20:09.21 INFO  ==> ** Starting harbor-exporter **
2024-07-17T16:20:09Z [INFO] [/common/dao/base.go:67]: Registering database: type-PostgreSQL host-harbor-postgresql port-5432 database-registry sslmode-"disable"
[ORM]2024/07/17 16:20:09 register db Ping `default`, failed to connect to `host=harbor-postgresql user=postgres database=registry`: server error (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))
2024-07-17T16:20:09Z [FATAL] [/cmd/exporter/main.go:56]: failed to initialize database: register db Ping `default`, failed to connect to `host=harbor-postgresql user=postgres database=registry`: server error (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))
```

### Are you using any custom parameters or values?
```
harbor:
  nameOverride: "harbor"
  externalURL: https://harbor.example.com
  logLevel: warn
  exposureType: ingress
  service:
    ports:
      http: 80
      https: 443

  core:
    existingEnvVarsSecret: "harbor-secret-vars"

  trivy:
    existingEnvVarsSecret: "harbor-secret-vars"

  jobservice:
    existingEnvVarsSecret: "harbor-secret-vars"

  ingress:
    core:
      ingressClassName: "nginx"
      pathType: Prefix
      hostname: harbor.example.com
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"     
      tls:
        - hosts:
          - harbor.example.com
          secretName: harbor.example.local

  persistence:
    enabled: true
    resourcePolicy: "keep"
    persistentVolumeClaim:
      registry:
        existingClaim: ""
        storageClass: ""
        subPath: ""
        accessModes:
          - ReadWriteOnce
        size: 20Gi
        annotations: {}
        selector: {}
      jobservice:
        existingClaim: ""
        storageClass: ""
        subPath: ""
        accessModes:
          - ReadWriteOnce
        size: 1Gi
        annotations: {}
        selector: {}
      trivy:
        storageClass: ""
        accessModes:
          - ReadWriteOnce
        size: 5Gi
        annotations: {}
        selector: {}

  postgresql:
    enabled: true
    auth:
      existingSecret: "harbor-secret-vars"

  metrics:
    enabled: true
    path: /metrics
    serviceMonitor:
      enabled: false
      namespace: ""
      interval: ""
      scrapeTimeout: ""
      labels: {}
      selector: {}
      relabelings: []
      metricRelabelings: []
      honorLabels: false
      jobLabel: ""
```

### What is the expected behavior?

The database pod should use the provided password

### What do you see instead?

It seems to be randomly generating a password
