### ISSUE TITLE
Mismatch Between Realm IDs in Pod Logs and PostgreSQL Database on EKS Deployment

### ISSUE THREAD

**Issue by armanfeyzi** [bitnami/charts#28197]
### Name and Version

bitnami/keycloak

### Issue Description

**Description:**
I'm experiencing an issue where the realm ID reported in the Keycloak pod logs does not match any realm ID in the PostgreSQL database. This mismatch occurs when deploying Keycloak on an EKS cluster using the Bitnami Helm chart. As a result, Keycloak cannot find the expected realm, leading to login errors.

**Environment:**
- **Keycloak version:** 24.0.5
- **Helm chart version:** 21.6.3
- **Kubernetes version:** 1.30
- **Cloud provider:** AWS EKS
- **Database:** AWS managed PostgreSQL

**Steps to Reproduce:**
1. Deploy Keycloak on an EKS cluster using the Bitnami Helm chart.
2. Connect Keycloak to an existing managed PostgreSQL database on AWS.
3. Attempt to log in to the Keycloak admin console.

### Custom parameters or values:

```yaml
#value.yaml

auth:
  adminUser: "admin"
  adminPassword: "admin"

postgresql:
  enabled: false
  persistence:
    storageClass: gp2
    size: 8Gi

externalDatabase:
  host: postgres-keyclock.xxxxxxx.eu-west-2.rds.amazonaws.com
  database: keycloak
  port: 5432

````

### What is the expected behavior?

**Expected Behavior:**
Keycloak should correctly identify and use the realm ID from the PostgreSQL database, allowing login without errors.

### What do you see instead?

**Actual Behavior:**
Keycloak logs report a realm ID that does not exist in the PostgreSQL database. The existing master realm ID in the database is different from the realm ID shown in the pod logs, causing a `user_not_found` error during login attempts.

**Keycloak Logs:**
```
keycloak 2024-07-22 12:25:02,236 WARN  [org.keycloak.events] (executor-thread-2) type="LOGIN_ERROR", realmId="f6c3e726-de0e-437b-9805-6e4312f3f82b", clientId="security-admin-console", userId="null", ipAddress="10.8.37.104", error="user_not_found", auth_method="openid-connect", auth_type="code", redirect_uri="https://key.mydomain.com/admin/master/console/", code_id="5fc5e195-f230-4d7a-a7d9-ca81e4090f6e", username="admin"
```

### Additional Information
- The master realm ID in the existing PostgreSQL database is different from the realm ID reported in the Keycloak pod logs.
- Any custom configurations applied to the Helm chart.
- Any steps already taken to try and resolve the issue.

By providing detailed information and context, I hope the Bitnami maintainers can understand the issue and offer a solution or fix in future releases.
