### ISSUE TITLE
[bitnami/charts] First slave after initial sentinel setup reports 127.0.0.1 as a current master

### ISSUE THREAD

**Issue by dm3ch** [bitnami/charts#2823]
**Which chart**:
redis

**Describe the bug**
After initial chart install with sentinel enabled and 2 slaves. First slave (slave-0) reports that current master is 127.0.0.1

**To Reproduce**
1. Install chart with next values:
```
usePasswordFile: true
cluster:
  enabled: true
  slaveCount: 2 # this results in 1+2 => 1+N, so we can get quorum for Sentinel
sentinel:
  enabled: true
  usePassword: false
  # we set this to match service name, for components not able to use sentinel
  # (may not be necessary)
  # defaults (upstream) to `mymaster`
  masterSet: mymaster
```
2. Wait until 3 pods would be created.
3. Execute following command for each of 3 pods:
```
kubectl exec <pod_name> -c sentinel -- redis-cli -p 26379 sentinel get-master-addr-by-name mymaster
```
4. Check that slave-1 and master-0 returns not 127.0.0.1 address while slave-0 returns 127.0.0.1

**Expected behavior**
All 3 pods reports same ip as a current master ip.

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I think this problem caused because master-0 and slave-0 pods are created at same time.
So when slave-0 is initialised it couldn't connect to other sentinels (cause master-0 is still initializing and slave-1 is not created at that time).

After manual restarting of slave-0 pod, it starts reporting master ip same as other 2 pods

**Comment by rafariossaa** [comment]
Hi,
  I was not able to reproduce the issue. This is what I did:
Changes in values.yaml used:
``` $ diff values.yaml values.yaml_orig 
50c50
<   enabled: true
---
>   enabled: false
53c53
<   usePassword: false
---
>   usePassword: true
211c211
< usePasswordFile: true
---
> usePasswordFile: false
```

```
$ helm install myredis  -f values.yaml .
```

```
$ kubectl exec myredis-slave-0  -c sentinel -- redis-cli -p 26379 sentinel get-master-addr-by-name mymaster
100.103.128.1
6379


 $ kubectl exec myredis-slave-1  -c sentinel -- redis-cli -p 26379 sentinel get-master-addr-by-name mymaster
100.103.128.1
6379```
Master IP:
``` $ kubectl exec myredis-master-0  -c sentinel -- cat /etc/hosts
# Kubernetes-managed hosts file.
...
100.103.128.1   myredis-master-0.myredis-headless.rafael.svc.cluster.local      myredis-master-0
```
Could you try again deleting first the PVCs ?

**Comment by dm3ch** [comment]
Tried to delete all PVCs before install:

Here's my additional values for test:
```
sentinel:
  enabled: true
  usePassword: false

usePasswordFile: true
```

Test results:
```
$ kubectl exec -n redis redis-slave-0  -c sentinel -- redis-cli -p 26379 sentinel get-master-addr-by-name mymaster
127.0.0.1
6379

$ kubectl exec -n redis redis-slave-1 -c sentinel -- redis-cli -p 26379 sentinel get-master-addr-by-name mymaster
10.233.99.53
6379
```

It's very strange, I'm able to reproduce such behaviour in 100% of my attempts.

I'll try to test that in some other k8s cluster.
