### ISSUE TITLE
[bitnami/kafka] ReplicationFactor of a Topic using single Broker has been not override in both zookeeper and kraft

### ISSUE THREAD

**Issue by th3cod3r** [bitnami/charts#28296]
### Name and Version

bitnami/kafka(29.3.7)

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am using kafka chart version 29.3.7 But in this version when i am trying to override the default values of kafka using below values.yaml
```
kafka:
  commonLabels:
    tier: base
  controller:
    replicaCount: 0
  kraft:
    enabled: false
  broker:
    replicaCount: 1
    persistence:
      size: 1Gi
  provisioning:
    enabled: true
    topics:
      - name: __consumer_offsets
        partitions: 50
        replicationFactor: 1
  listeners:
    client:
      containerPort: 9092
      protocol: PLAINTEXT
      name: CLIENT
      sslClientAuth: ""
    interbroker:
      containerPort: 9093
      protocol: PLAINTEXT
      name: INTERNAL
      sslClientAuth: ""
    external:
      containerPort: 9094
      protocol: PLAINTEXT
      name: EXTERNAL
      sslClientAuth: ""
  logRetentionHours: 48
  logRetentionBytes: _104857600
  logSegmentBytes: _104857600
  livenessProbe:
    initialDelaySeconds: 90
    timeoutSeconds: 20
  readinessProbe:
    initialDelaySeconds: 90
    timeoutSeconds: 20
  startupProbe:
    initialDelaySeconds: 90
    timeoutSeconds: 20
  zookeeper:
    enabled: true
    replicaCount: 1
    persistence:
      size: 1Gi
    livenessProbe:
      initialDelaySeconds: 90
      timeoutSeconds: 20
    readinessProbe:
      initialDelaySeconds: 90
      timeoutSeconds: 20
```
      
      With the above yaml i am using an external application which uses kafka and encountered below error
```
      org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 3 larger than available brokers: 1.
[2024-07-24 03:15:11,216] INFO [Admin Manager on Broker 100]: Error processing create topic request CreatableTopic(name='__consumer_offsets', numPartitions=50, replicationFactor=3, assignments=[], configs=[CreateableTopicConfig(name='compression.type', value='producer'), CreateableTopicConfig(name='cleanup.policy', value='compact'), CreateableTopicConfig(name='segment.bytes', value='104857600')]) (kafka.server.ZkAdminManager)
```

### What do you see instead?

It should uses single broker kafka and what i topics needs to be created, it should be created (as __consumer_offsets was not created by zookeeper)

**Comment by dgomezleon** [comment]
Hi @th3cod3r
 
The previous yaml does not seem to be ok. I can see everything (`provisioning`, `listeners`...) is under `kafka` section, and this is not creating topics. Maybe you wanted to try this.

```
  commonLabels:
    tier: base
  controller:
    replicaCount: 0
  kraft:
    enabled: false
  broker:
    replicaCount: 1
    persistence:
      size: 1Gi
  provisioning:
    enabled: true
    replicationFactor: 1
    topics:
      - name: __consumer_offsets
        partitions: 50
        replicationFactor: 1
  listeners:
    client:
      containerPort: 9092
      protocol: PLAINTEXT
      name: CLIENT
      sslClientAuth: ""
    interbroker:
      containerPort: 9093
      protocol: PLAINTEXT
      name: INTERNAL
      sslClientAuth: ""
    external:
      containerPort: 9094
      protocol: PLAINTEXT
      name: EXTERNAL
      sslClientAuth: ""
  logRetentionHours: 48
  logRetentionBytes: _104857600
  logSegmentBytes: _104857600
  livenessProbe:
    initialDelaySeconds: 90
    timeoutSeconds: 20
  readinessProbe:
    initialDelaySeconds: 90
    timeoutSeconds: 20
  startupProbe:
    initialDelaySeconds: 90
    timeoutSeconds: 20
  zookeeper:
    enabled: true
    replicaCount: 1
    persistence:
      size: 1Gi
    livenessProbe:
      initialDelaySeconds: 90
      timeoutSeconds: 20
    readinessProbe:
      initialDelaySeconds: 90
      timeoutSeconds: 20
```

Could you please double-check these values?

I hope it helps
