### ISSUE TITLE
Helm - PostgreSQL | How to enable PostGIS extension?

### ISSUE THREAD

**Issue by mabdelfattah** [bitnami/charts#2830]
As per the README.md file in the PostgreSQL Chart, the PostGIS is installed. However it is not enabled. The question is how to enable it? Considering the chart does not allow super users.

**Comment by carrodher** [comment]
Hi, PostGIS is installed but not enable, to enable it you can follow the regular approach, for example, the one described in the [official documentation](https://postgis.net/install/).

Using a new deployment from scratch, you can use the postgresql-client to enable it. 
```console
$ helm install my-pg bitnami/postgresql
(wait until the deployment is completed)

$ export POSTGRES_PASSWORD=$(kubectl get secret --namespace default my-pg-postgresql-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)

$ kubectl run my-pg-postgresql-client --rm --tty -i --restart='Never' --namespace default --image bitnami/postgresql:10 --env="PGPASSWORD=$POSTGRES_PASSWORD"  --command -- psql -h my-pg-postgresql-pgpool -p 5432 -U postgres -d postgres
```

Then, using the postgres CLI you can execute:
```console
$ postgres=# CREATE EXTENSION postgis;
CREATE EXTENSION

$ postgres=# SELECT PostGIS_Version();
            postgis_version            
---------------------------------------
 2.5 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
(1 row)
```

**Comment by mabdelfattah** [comment]
Thank you @carrodher , but any idea how to automate this? I don't want to run anything manually.

**Comment by Progdrasil** [comment]
I'm having this same issue. This happen for the postgis extension as well as the uuid-ossp extension.

**Comment by mabdelfattah** [comment]
@Progdrasil I think I found a solution (workaround)، which is basically leaving the username as `postgres` and set `postgresqlPostgresPassword`
```
postgresql:
  image:
    tag: 11.7.0
  postgresqlDatabase: 'my_app'
  postgresqlUsername: 'postgres'
  postgresqlPassword: 'my_app'
  postgresqlPostgresPassword: 'my_app'
```

**Comment by Progdrasil** [comment]
This helped, but now this means the database password is in the repository in plain text... It's a functional workaround but not a secure one

**Comment by carrodher** [comment]
Hi, there are several ways to configure the password, you can use for example a secret, on this way the password is not going appear in the repository in plain text. In the same way, instead of modifying the `values.yaml` you can also set the parameters directly in the install command, i.e `helm install --set postgresqlPassword=my_app`

Those are the different options to configure the password:
```yaml
 ## PostgreSQL admin password (used when `postgresqlUsername` is not `postgres`)
 ## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#creating-a-database-user-on-first-run (see note!)
 postgresqlPostgresPassword:

 ## PostgreSQL user (has superuser privileges if username is `postgres`)
 ## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#setting-the-root-password-on-first-run
 postgresqlUsername: postgres

 ## PostgreSQL password
 ## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#setting-the-root-password-on-first-run
 ##
 postgresqlPassword:

 ## PostgreSQL password using existing secret
 existingSecret: secret

 ## Mount PostgreSQL secret as a file instead of passing environment variable
 usePasswordFile: false
```
