### ISSUE TITLE
[bitnami/keycloak] Cannot load AdminUI with gce based ingress

### ISSUE THREAD

**Issue by rajan123456** [bitnami/charts#28357]
### Name and Version

bitnami/keycloak:21.7.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am trying to deploy Keycloak with APISIX as the ingress-controller. APISIX requires the path to be specified as /* instead of / in the ingress definition.

Due to this, post-deployment, the KC_HOSTNAME_URL env var gets specified as https://keycloak.docker.internal/* instead of https://keycloak.docker.internal/
Source: https://github.com/bitnami/charts/blob/2b15502a03c16d5c38877244650ff0d1f8f764b9/bitnami/keycloak/templates/statefulset.yaml#L230

Appears, it will also affect the KC_HOSTNAME_ADMIN_URL env var
Source: https://github.com/bitnami/charts/blob/2b15502a03c16d5c38877244650ff0d1f8f764b9/bitnami/keycloak/templates/statefulset.yaml#L223

### Are you using any custom parameters or values?

```
auth:
  adminUser: admin
  adminPassword: 2ewF79kM0R

ingress:
  enabled: true
  ingressClassName: apisix
  hostname: keycloak.docker.internal
  path: /*
  annotations:
    cert-manager.io/cluster-issuer: my-issuer
  tls: true

proxyAddressForwarding: true
proxy: edge
proxyHeaders: xforwarded
production: true

service:
  type: ClusterIP
```

### What is the expected behavior?

Keycloak UI should load successfully

### What do you see instead?

The Keycloak UI is forever stuck in **Loading the Admin UI** state.
Various static requests on the browser are appended with /* in the URI which causes a 404 error.

<img width="884" alt="image" src="https://github.com/user-attachments/assets/b9d8993a-a0cb-4f59-a9b8-e0dbddbe4e03">
