### ISSUE TITLE
[bitnami/argo-cd] templates/cluster-configs.yaml nil pointer error

### ISSUE THREAD

**Issue by EC-Sol** [bitnami/charts#28440]
### Name and Version

bitnami/argo-cd  6.6.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Kubernetes 1.27.8, helm v3.13.1
2. When Add like below to values.yaml. Then I meet error `Error: UPGRADE FAILED: template: argo-cd/templates/cluster-configs.yaml:11:16: executing "argo-cd/templates/cluster-configs.yaml" at <include "common.names.namespace" .>: error calling include: template: argo-cd/charts/common/templates/_names.tpl:63:20: executing "common.names.namespace" at <.Release.Namespace>: nil pointer evaluating interface {}.Namespace`

### Are you using any custom parameters or values?

```yaml
config:
  clusterCredentials:
  - name: <CLUSTER_NAME> # Ex. my-cluster
    server: <CLUSTER_URL OR IP> # Ex. https://10.10.10.10:6443
    config:
      bearerToken: <TOKEN>
      tlsClientConfig:
        insecure: false
        caData: <CA_DATA>
```

### What is the expected behavior?

No error

### What do you see instead?

![image](https://github.com/user-attachments/assets/695669d5-7c5e-4a97-a97b-f9bcb64b84fa)

### Additional information

Modify file `templates/cluster-configs.yaml` like below, We can solve this problem.
commented line is original contents.
```yaml
{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- range .Values.config.clusterCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" $ }}-cluster-{{ .name }}
  namespace: {{ include "common.names.namespace" $ | quote }} 
  # namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}
  # labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    # Mandatory label
    # Ref: https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#atomic-configuration
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/secret-type: cluster
  {{- if $.Values.commonAnnotations }}
  # {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  # annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  name: {{ .name }}
  server: {{ .server }}
  namespaces: {{ .namespaces }}
  config: |
    {{- .config | toPrettyJson | nindent 4 }}
---
{{- end }}
```
