### ISSUE TITLE
extraVolumeMounts for Spark in IBM Cloud

### ISSUE THREAD

**Issue by mohamedih** [bitnami/charts#2849]
**Which chart**:
Spark in IBM Cloud

**Describe the bug**
How can i add extra volume and extraVolumeMounts to the workers. I tried many combination but it failed. what is the format that i have to use t enter the details?
What this comment mean ?
"Array of extra volume mounts to be added to thehttps://github.com/bitnami/charts/issues/new/choose Spark worker deployment (evaluated as template). Normally used with"

**Comment by andresbono** [comment]
Hi @mohamedih, please check the format with the following example. It will create a volume from a configmap and it will be mounted in the worker pods:

`custom-values.yaml`:
```yaml
## Spark worker specific configuration
##
worker:
  ## Array to add extra volumes
  ##
  extraVolumes:
    - name: extra-volume
      configMap:
        name: extra-configmap
  ## Array to add extra mounts (normally used with extraVolumes)
  ##
  extraVolumeMounts:
    - name: extra-volume
      mountPath: /tmp/test/

```


```
$ kubectl create configmap extra-configmap --from-literal=file='content of the file'
configmap/extra-configmap created

$ helm install spark bitnami/spark -f custom-values.yaml

$ kubectl exec -it spark-worker-0 -- cat /tmp/test/file
content of the file
```
