### ISSUE TITLE
[bitnami/oauth2-proxy] Vault injection results in lost oauth2-proxy-config

### ISSUE THREAD

**Issue by ArkShocer** [bitnami/charts#28518]
### Name and Version

bitnami/oauth2-proxy 5.3.10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install OAuth2Proxy via helm and the attached values.yaml.

### Are you using any custom parameters or values?
```
#fullnameOverride: "oauth2-proxy"

automountServiceAccountToken: true

configuration:
  content: |-
    email_domains = [ "*" ]
    provider = "oidc"
    oidc_issuer_url = "https://login.microsoftonline.com/tenant_id/v2.0"
    pass_user_headers = true
    # return authenticated user to nginx
    set_xauthrequest = true
    skip_provider_button = false
    skip_auth_regex = "^/api/\\d+/webhook/"
    provider_display_name = "Example Azure AD"
    cookie_expire = "1h"
    cookie_httponly = false
    cookie_secure = true
    errors_to_info_log = true
    show_debug_on_error = true
    exclude_logging_paths = ["/ping"]
    upstreams = [ "file:///dev/null" ]

command: ["/bin/sh","-c"]
args: [". /vault/secrets/secrets.sh && oauth2-proxy"]

extraEnvVars:
  - name: OAUTH2_PROXY_CLIENT_ID
  - name: OAUTH2_PROXY_CLIENT_SECRET
  - name: OAUTH2_PROXY_COOKIE_SECRET

image:
  tag: 7.6.0-debian-12-r18

ingress:
  enabled: true
  ingressClassName: nginx
  path: /
  pathType: ImplementationSpecific
  hostname: auth.asd.example.com
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "mgmt-oauth2-proxy"
  vault.hashicorp.com/agent-inject-default-template: "json"
  vault.hashicorp.com/agent-inject-secret-oauth2-proxy.conf: "kv/mgmt/oauth2-proxy"
  vault.hashicorp.com/agent-inject-template-secrets.sh: |
    {{`{{- with secret "kv/mgmt/oauth2-proxy" -}}
    export OAUTH2_PROXY_CLIENT_ID="{{ .Data.data.OAUTH2_PROXY_CLIENT_ID }}"
    export OAUTH2_PROXY_CLIENT_SECRET="{{ .Data.data.OAUTH2_PROXY_CLIENT_SECRET }}"
    export OAUTH2_PROXY_COOKIE_SECRET="{{ .Data.data.OAUTH2_PROXY_COOKIE_SECRET }}"
    {{- end }}`}}

# Deploy redis subchart as part of oauth2-proxy
redis:
  enabled: true
  auth:
    enabled: true
  architecture: standalone

servicAccount:
  automountServiceAccountToken: true
```

### What is the expected behavior?

Pod is starting without issues and the secrets environment variables are injected successfully.

### What do you see instead?

Pod logs the following issue regardless of what the `content:` is
```text
[2024/07/25 13:13:35] [main.go:52] invalid configuration:
  missing setting for email validation: email-domain or authenticated-emails-file required.
      use email-domain=* to authorize all email addresses
```

### Additional information

If `command:` or `args:` is not set it does load the config since it doesn't throw the error in the logs anymore but says its missing the client_id and client_secret (obviously since I don't provide them in a normal k8s secret)

**Comment by juan131** [comment]
Hi @ArkShocer 

It seems you're populating your env. vars using Vault and its required pod annotations. I must be honest, I'm not familiar with this process but I'm assuming that's not the issue.

However, by overwriting the default "args" you're omitting the Helm chart logic below:

```yaml
          args:
            - --http-address=0.0.0.0:{{ .Values.containerPort }}
            {{- if or .Values.configuration.existingConfigmap .Values.configuration.content }}
            - --config=/bitnami/oauth2-proxy/conf/oauth2_proxy.cfg
            {{- end }}
            {{- if .Values.configuration.authenticatedEmailsFile.enabled }}
            - --authenticated-emails-file=/bitnami/oauth2-proxy/conf/authenticated-emails/authenticated-emails-list
            {{- end }}
            {{- if .Values.configuration.google.enabled }}
            - --google-admin-email={{ .Values.configuration.google.adminEmail }}
            - --google-service-account-json=/bitnami/oauth2-proxy/conf/google/service-account.json
            {{- if .Values.configuration.google.groups }}
            {{- range $group := .Values.configuration.google.groups }}
            - --google-group={{ $group }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.configuration.htpasswdFile.enabled }}
            - --htpasswd-file=/bitnami/oauth2-proxy/conf/htpasswd/users.txt
            {{- end }}
            {{- if .Values.configuration.redirectUrl }}
            - --redirect-url={{.Values.configuration.redirectUrl}}
            {{- end }}
            {{- if .Values.configuration.oidcIssuerUrl }}
            - --oidc-issuer-url={{.Values.configuration.oidcIssuerUrl}}
            {{- end }}
            {{- if .Values.configuration.whiteList }}
            - --whitelist-domain={{.Values.configuration.whiteList | quote}}
            {{- end }}
            {{- if .Values.extraArgs }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.extraArgs "context" $ ) | nindent 12 }}
            {{- end }}
```

In other words.. I'd expect that your custom would pass the `--config`, `--http-address`, ... flags to the `oauth2-proxy` after loading env vars defined at `/vault/secrets/secrets.sh`.

**Comment by ArkShocer** [comment]
@juan131 Thanks for the quick response! Adding `--config=/bitnami/oauth2-proxy/conf/oauth2_proxy.cfg --http-address=0.0.0.0:4180` did the trick for me 👍 

For anyone else having the same issue, this is what my values.yaml looks like:
```yaml
fullnameOverride: "oauth2-proxy"

automountServiceAccountToken: true

configuration:
  content: |-
    email_domains = [ "*" ]
    provider = "oidc"
    oidc_issuer_url = "https://login.microsoftonline.com/tenant_id/v2.0"
    pass_user_headers = true
    # return authenticated user to nginx
    set_xauthrequest = true
    skip_provider_button = false
    skip_auth_regex = "^/api/\\d+/webhook/"
    provider_display_name = "Azure AD"
    cookie_expire = "1h"
    cookie_httponly = false
    cookie_secure = true
    cookie_name = "__Secure-EXAMPLE-Auth"
    cookie_domains = [".sub.example.com"]
    errors_to_info_log = true
    show_debug_on_error = true
    exclude_logging_paths = ["/ping"]
    whitelist_domains = [".sub.example.com"]
    upstreams = [ "file:///dev/null" ]

command: ["/bin/sh","-c"]
args: [". /vault/secrets/secrets.sh && oauth2-proxy --config=/bitnami/oauth2-proxy/conf/oauth2_proxy.cfg --http-address=0.0.0.0:4180"]

ingress:
  enabled: true
  ingressClassName: nginx
  path: /
  pathType: ImplementationSpecific
  hostname: auth.sub.example.com
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "mgmt-oauth2-proxy"
  vault.hashicorp.com/agent-inject-default-template: "json"
  vault.hashicorp.com/agent-inject-secret-oauth2-proxy.conf: "kv/mgmt/oauth2-proxy"
  vault.hashicorp.com/agent-inject-template-secrets.sh: |
    {{`{{- with secret "kv/mgmt/oauth2-proxy" -}}
    export OAUTH2_PROXY_CLIENT_ID="{{ .Data.data.OAUTH2_PROXY_CLIENT_ID }}"
    export OAUTH2_PROXY_CLIENT_SECRET="{{ .Data.data.OAUTH2_PROXY_CLIENT_SECRET }}"
    export OAUTH2_PROXY_COOKIE_SECRET="{{ .Data.data.OAUTH2_PROXY_COOKIE_SECRET }}"
    {{- end }}`}}

# Deploy redis subchart as part of oauth2-proxy
redis:
  enabled: true
  auth:
    enabled: true
  architecture: standalone

servicAccount:
  automountServiceAccountToken: true
```
Then for each service I want to go through the OAuth2Proxy I used the following annotations in the ingress:
```yaml
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User,X-Auth-Request-Groups,X-Auth-Request-Email,X-Auth-Request-Preferred-Username"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.sub.example.com/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
    nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth"
```
