### ISSUE TITLE
[bitnami/memcached] high-availability behavior / inconsistent metrics endpoint

### ISSUE THREAD

**Issue by ScriptGod1337** [bitnami/charts#28515]
### Name and Version

bitnami/memcached 7.0.3

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Deployment with more than one `replicaCount` with metrics enabled
```
replicaCount: 2
architecture: "high-availability"
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  image:
    registry: ...
    repository: dockerhub/bitnami/memcached-exporter
```

3. Add values to the memcached. For example via nginx-ingress `global-rate-limit-memcached-host`
4. Check content of the memcached instances and read content of metrics endpoint

### What is the expected behavior?

- Both memcached instances contain the same items.
- The metrics endpoint returns either
    - overall status - if all memcached instances have the same state, or
    - status of all memcached instances

### What do you see instead?

The memcached instances contain different number of items

**memcached-0**
```
stats
STAT total_items 6
```
**memcached-1**
```
stats
STAT total_items 7
```

The metrics seems to point to one of those instances. Which one is maybe random picked (maybe during connection init?) and stays stable then.
**metrics**
```
# HELP memcached_items_total Total number of items stored during the life of this insta
# TYPE memcached_items_total counter
memcached_items_total 7
```

### Additional information

Is there no sync between the memcached instances? If no and this is the intended design, why does metrics not give figure from all?
