### ISSUE TITLE
Azure MSI

### ISSUE THREAD

**Issue by rhysjtevans** [bitnami/charts#2851]
**Which chart**:
External DNS 3.2.0

**Describe the bug**
My understanding is that I should be able to provide a values file with just provider: azure and azure.useManagedIdentityExtension = true and it should render fine. It does not add mount /etc/kubernetes/azure.json from the host.

If I negate the conditional at 
#L453 and #L512 it renders as expected.

The second part to this bug is the validateValues doesn't accept solely "azure.useManagedIdentityExtension"

**To Reproduce**
Using External DNS Helm Chart 3.2.0
`provider: azure
azure:
  useManagedIdentityExtension: true
`
Renders the following
```
# Source: external-dns/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: r-external-dns
  labels: 
    app.kubernetes.io/name: external-dns
    helm.sh/chart: external-dns-3.2.0
    app.kubernetes.io/instance: r
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels: 
      app.kubernetes.io/name: external-dns
      app.kubernetes.io/instance: r
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: external-dns
        helm.sh/chart: external-dns-3.2.0
        app.kubernetes.io/instance: r
        app.kubernetes.io/managed-by: Helm
      annotations:
    spec:      
      securityContext: 
        fsGroup: 1001
        runAsUser: 1001
      serviceAccountName: r-external-dns
      containers:
        - name: external-dns
          image: "docker.io/bitnami/external-dns:0.7.2-debian-10-r6"
          imagePullPolicy: "IfNotPresent"
          args:
            # Generic arguments
            - --log-level=info
            - --log-format=json
            - --policy=upsert-only
            - --provider=azure
            - --registry=txt
            - --interval=1m
            - --source=ingress
            # Azure Arguments
          env:
          ports:
            - name: http
              containerPort: 7979
          readinessProbe: 
            failureThreshold: 6
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe: 
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            # Azure mountPath(s)
            - name: azure-config-file
              readOnly: true
      volumes:
        # Azure volume(s)
        - name: azure-config-file

```

**Expected behavior**
when I render the template I should see correct Volumes and VolumeMounts and validateValues accepts only useManagedIdentityExtension

**Version of Helm and Kubernetes**:
Helm 3.2.1
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}

```

**Additional context**
