### ISSUE TITLE
ExternalAccess NodePort not working

### ISSUE THREAD

**Issue by sinamohsenifar** [bitnami/charts#28536]
### Name and Version

bitnami/kafka "29.3.13"
bitnami/kafka "29.3.10"

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. i created  a kafka cluster with 3 nodes and 1 controller . i want it to use NodePort for external access . the ports are perdefined (30092,30093,30094)
2. cluster created without any error. 
3. but no service can access to kafka from outside the kubernetes cluster. 

### Are you using any custom parameters or values?
```
sasl:
  enabledMechanisms: PLAIN
  interBrokerMechanism: PLAIN
  controllerMechanism: PLAIN
  zookeeper:
    user: ""
    password: ""
tls:
  zookeeper:
    enabled: false
extraEnvVars: []
controller:
  replicaCount: 1
  controllerOnly: true
  minId: 0
  automountServiceAccountToken: true
broker:
  replicaCount: 3
  extraEnvVars:
    - name: KFAKA_CFG_AUTO_CREATE_TOPICS_ENABLE
      value: "false"
    - name: KAFKA_CFG_LOG_RETENTION_HOURS
      value: "24"
  automountServiceAccountToken: true
service:
  type: ClusterIP
  ports:
    client: 9092
    controller: 9093
    interbroker: 9094
    external: 9095
  nodePorts:
    client: ""
    external: ""
  allocateLoadBalancerNodePorts: true
externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
  controller:
    forceExpose: true
    service:
      type: NodePort
      ports:
        external: 9093
      loadBalancerClass: ""
      loadBalancerIPs: []
      loadBalancerNames: []
      loadBalancerAnnotations: []
      loadBalancerSourceRanges: []
      allocateLoadBalancerNodePorts: true
      nodePorts: 
        - 31093
      externalIPs: []
      useHostIPs: false
      usePodIPs: false
      domain: ""
      publishNotReadyAddresses: false
      labels: {}
      annotations: {}
      extraPorts: []
  broker:
    service:
      type: NodePort
      ports:
        external: 9094
      nodePorts:
      - 30092
      - 30093
      - 30094
```
### What is the expected behavior?

that i can define nodeports for controller and broker and service and server.properties will confige correctly.

### What do you see instead?

i think with this configs, listeners are not configed well. i checked server.propertise from broker pods. and my nodeports arent show in listeners just they configed just in advertised listeners.
