### ISSUE TITLE
MySQLX port condition on the primary statefulset references the variable from the secondary config

### ISSUE THREAD

**Issue by abukharov** [bitnami/charts#28546]
### Name and Version

bitnami/mysql 11.1.14

### What architecture are you using?

amd64

### What steps will reproduce the bug?

If you deploy mysql out of the helmchart with the values:

```yaml
primary:
  enableMySQLX: true

  containerPorts:
    mysql: 3306
    mysqlx: 33060

  resourcesPreset: medium

  persistence:
    enabled: true
    storageClass: magi-fs
    size: 8Gi

  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.120.132
    ports:
      mysql: 3306
      mysqlx: 33060

secondary:
  replicaCount: 0
```

you won't be able to connect to mysqlx on the primary node.

### What is the expected behavior?

I can connect to the primary mysql on port 33060 via mysqlx

### What do you see instead?

```
alex@scirocco ~ took 3s
❯ telnet 192.168.120.132 33060
Connecting To 192.168.120.132...Could not open connection to the host, on port 33060: Connect failed

alex@scirocco ~ took 21s
```

```yaml
    name: mysql
    ports:
    - containerPort: 3306
      name: mysql
      protocol: TCP
    readinessProbe:
```

### Additional information

This line: https://github.com/bitnami/charts/blob/main/bitnami/mysql/templates/primary/statefulset.yaml#L226
needs to be `{{- if .Values.primary.enableMySQLX }}` instead of `{{- if .Values.secondary.enableMySQLX }}`
