### ISSUE TITLE
[bitnami/kibana] Use `extraEnvVars` without warnings (and without duplicate keys in resulting YAMLs)

### ISSUE THREAD

**Issue by oatmealb** [bitnami/charts#28548]
### Name and Version

bitnami/kibana 11.2.12

### What architecture are you using?

amd64

### What steps will reproduce the bug?

in values.yaml, set
```yml
extraEnvVars:
  - name: KIBANA_ELASTICSEARCH_TLS_VERIFICATION_MODE
    value: certificate
```
and then run `helm upgrade --install kibana --version 11.2.12 oci://registry-1.docker.io/bitnamicharts/kibana --create-namespace --namespace kibana -f values.yaml`

### What is the expected behavior?

I don't encounter warnings and I don't see duplication in templated YAMLs.

### What do you see instead?

I encounter warnings, f.e.:
```
W0728 14:42:33.875785   52244 warnings.go:70] spec.template.spec.containers[0].env[10]: hides previous definition of "KIBANA_ELASTICSEARCH_TLS_VERIFICATION_MODE"
```

Also, the resulting Deployment YAML is suboptimal – there're duplicate keys in `Environment`:
```yml
Environment:
      KIBANA_ELASTICSEARCH_TLS_VERIFICATION_MODE:  full
      KIBANA_ELASTICSEARCH_TLS_VERIFICATION_MODE:  certificate
     # ...
```

Is this warning avoidable? Am I misusing the chart?
