### ISSUE TITLE
[bitnami/postgresql-ha] Backup Storage Annotations aren't applied

### ISSUE THREAD

**Issue by sumebrius** [bitnami/charts#28545]
### Name and Version

bitnami/postgresql-ha

### What architecture are you using?

None

### What steps will reproduce the bug?

Set annotations via the `backup.cronjob.storage.annotations` value as per documentation.

### Are you using any custom parameters or values?

```yaml
backup:
  enabled: true
  cronjob:
    storage:
      resourcePolicy: "keep"
    annotations:
      k8up.io/backup: "true"
```

### What is the expected behavior?

Extra defined annotations are applied to the PVC

### What do you see instead?

Defined annotations are missing

### Additional information

Checking the template - it appears the PVC pulls annotations from `.Values.backup.cronjob.annotations` instead of `.Values.backup.cronjob.storage.annotations`
