### ISSUE TITLE
redis exporter dosen't auth against redis

### ISSUE THREAD

**Issue by Loki-Afro** [bitnami/charts#28564]
### Name and Version

bitnamicharts/valkey

### What architecture are you using?

None

### What steps will reproduce the bug?

1. enabled sentinel
2. enabled monitoring
3. installed helmcharts
4. consult metrics logs of any redis exporter container

### Are you using any custom parameters or values?

```yaml
      values:
        master:
          readinessProbe:
            timeoutSeconds: 5
        sentinel:
          enabled: true
          readinessProbe:
            timeoutSeconds: 5
        metrics:
          enabled: true
        networkPolicy:
          enabled: false
        serviceAccount:
          create: false
```

### What is the expected behavior?

redis exporter is exporting metrics

### What do you see instead?

logs from any of the (per default 3) redis exporters
```
time="2024-07-29T17:20:53Z" level=error msg="Redis INFO err: NOAUTH Authentication required."                                                                                                                                             time="2024-07-29T17:21:08Z" level=error msg="Couldn't set client name, err: NOAUTH Authentication required."
```

### Additional information

https://github.com/oliver006/redis_exporter?tab=readme-ov-file#authenticating-with-redis says nothing about env vars

**Comment by Loki-Afro** [comment]
here my workaround:

```
        master:
          readinessProbe:
            timeoutSeconds: 5
        sentinel:
          enabled: true
          readinessProbe:
            timeoutSeconds: 5
        metrics:
          enabled: true
          podMonitor:
            enabled: true
          serviceMonitor:
            enabled: true
          extraArgs:
            redis.password: $VALKEY_PASSWORD <--------
        networkPolicy:
          enabled: false
        serviceAccount:
          create: false
```
