### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] RabbitMQ Cluster does not form with Istio Service Mesh

### ISSUE THREAD

**Issue by kemra102** [bitnami/charts#28573]
### Name and Version

bitnami/rabbitmq-cluster-operator 4.3.14

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy a RabbitMQ `kind` via the CRD into a namespace with the label `istio-injection=enabled` (so the Istio/Envoy sidecar is automatically injected as a container on each RabbitMQ Pod.

### Are you using any custom parameters or values?

`values.yaml:`
```yaml
---
global:
  imageRegistry: central-docker-remote.internal.uk
  defaultStorageClass: gp3-standard

commonLabels:
  team: infra

clusterOperator:
  resources:
    requests:
      cpu: &minimumCPUCluster 50m
      memory: 192Mi
    limits:
      memory: 192Mi
  tolerations:
    - key: node.kubernetes.io/role
      value: core-co
      effect: NoSchedule

msgTopologyOperator:
  # Explicitly set the name otherwise we get a crazy long name.
  fullnameOverride: rabbitmq-messaging-topology-operator
  watchAllNamespaces: false
  hostNetwork: true
  resources:
    requests:
      cpu: &minimumCPUmsgTop 50m
      memory: 192Mi
    limits:
      memory: 192Mi
  tolerations:
    - key: node.kubernetes.io/role
      value: core-co
      effect: NoSchedule

# Extra resources managed by the Helm chart
extraDeploy:
  # VPA config for each Operator
  - apiVersion: autoscaling.k8s.io/v1
    kind: VerticalPodAutoscaler
    metadata:
      name: rabbitmq-cluster-operator
      labels:
        team: infra
    spec:
      resourcePolicy:
        containerPolicies:
        - containerName: rabbitmq-cluster-operator
          minAllowed:
            cpu: *minimumCPUCluster
      targetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: rabbitmq-cluster-operator
      updatePolicy:
        updateMode: Auto
  - apiVersion: autoscaling.k8s.io/v1
    kind: VerticalPodAutoscaler
    metadata:
      name: rabbitmq-messaging-topology-operator
      labels:
        team: infra
    spec:
      resourcePolicy:
        containerPolicies:
        - containerName: rabbitmq-cluster-operator
          minAllowed:
            cpu: *minimumCPUmsgTop
      targetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: rabbitmq-messaging-topology-operator
      updatePolicy:
        updateMode: Auto
```

`rabbitmqcluster.yaml:`
```yaml
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-core
  namespace: ${namespace}
  labels:
    team: infra
  annotations:
    rabbitmq.com/topology-allowed-namespaces: ${topology_allowed_namespaces}
spec:
  replicas: 3
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      memory: 1Gi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
      log.console = true
      log.default.level = debug
      log.file.level = debug
      cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
      cluster_formation.k8s.host = kubernetes.svc.local
      cluster_formation.k8s.address_type = hostname
      cluster_formation.k8s.service_name = rabbitmq-core-nodes
      cluster_formation.k8s.hostname_suffix = .rabbitmq-core-nodes.${namespace}.svc.cluster.local
  persistence:
    storageClassName: gp3-standard
    storage: 16Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - rabbitmq-core
          topologyKey: kubernetes.io/hostname
  tolerations:
    - key: node.kubernetes.io/role
      value: core-co
      effect: NoSchedule
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            topologySpreadConstraints:
              - labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: rabbitmq
                    app.kubernetes.io/name: rabbitmq-core
                matchLabelKeys:
                  - pod-template-hash
                topologyKey: topology.kubernetes.io/zone
                maxSkew: 1
                whenUnsatisfiable: ScheduleAnyway
              - labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: rabbitmq
                    app.kubernetes.io/name: rabbitmq-core
                matchLabelKeys:
                  - pod-template-hash
                topologyKey: kubernetes.io/hostname
                maxSkew: 1
                whenUnsatisfiable: ScheduleAnyway
```

### What is the expected behavior?

RabbitMQ is spun up but does not cluster, falling back to becoming 3 clusters of a single instance each. No error I can see is given in the logs.

### What do you see instead?

All 3 RabbitMQ instances clustered together.
