### ISSUE TITLE
AWS EFS Not Support/Working w/ HELM Bitnami Postgre SQL

### ISSUE THREAD

**Issue by imoisharma** [bitnami/charts#28591]
### Name and Version

https://artifacthub.io/packages/helm/bitnami/postgresql/15.5.20

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create a standard EFS as a storage class w/ dynamic provisioning.
2. Create an EKS nodegroup such as t3a or m6i.large etc.
3. Provision the Postgres with a custom value where to pass the `defaultStorageClass` as efs-sc. 

Note- In local with minikube the same chart release as well as EBS is working fine. Also, there is no issue w/ EFS configuration as I already have other HELM releases utilizing the same class for provisioning and using the efs over ebs.

### Are you using any custom parameters or values?
```yaml
global:
  compatibility:
    openshift:
      adaptSecurityContext: auto
  defaultStorageClass: "efs-sc"
```
### What is the expected behavior?

It should work it should not fail with exit code 1 error.an 

### What do you see instead?

<img width="1440" alt="Screenshot 2024-07-31 at 04 18 10" src="https://github.com/user-attachments/assets/1edd1be3-c289-42c3-b16b-f3edbfe852d8">
<img width="656" alt="Screenshot 2024-07-31 at 04 17 54" src="https://github.com/user-attachments/assets/931e4094-9577-4e94-b3cd-c54dc2d5eeee">

**Comment by maiorano84** [comment]
@imoisharma 

This may be coming too late for you, but given that @carrodher would rather spend the time copying and pasting a canned response instead of replying with anything useful, here's what I've generally learned in the hopes that somebody might stumble across this:

EKS switched over to containerd some time ago. As part of that, many Helm charts and containers have largely adapted by running under a security context that leverages non-privileged user and group IDs. In many cases, this is 1001. Many Bitnami charts also use this same UID / GID.

Depending on how you've set up your EFS Storage Class, your running Postgres process may not have the necessary permissions to write to the directory in your PV that's being managed by that storage class.

In my case, I've had to set up a separate storage class that matches the UID/GID of the running security context of Postgres / Redis / Galera / etc.

Here's a quick snippet that should help get you started in the right direction if you haven't already figured it out:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: postgres-sc
parameters:
    basePath: /dynamic_provisioning
    directoryPerms: "700"
    fileSystemId: <your-efs-filesystem-id>
    gid: "1001"
    provisioningMode: efs-ap
    uid: "1001"
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

Bitnami doesn't cover this very much in their docs, likely due to the fact that this isn't really so much unique to Bitnami but more to do with setting up EFS. The EFS CSI defaults for either the addon or Helm chart don't cover this in very much detail either, unfortunately.

That said, once I switched set the chart to use the updated SC, everything spun up for me without issue.

Hopefully this helps, and Bitnami Members / Contributers start actually looking at these issues in the future instead of hand-waving them away.
