### ISSUE TITLE
seaweedfs custom s3 config.json fails with "not a directory"

### ISSUE THREAD

**Issue by RangerRick** [bitnami/charts#28595]
### Name and Version

bitnami/seaweedfs 1.0.6

### What architecture are you using?

arm64

### What steps will reproduce the bug?

My environment is Kind 0.23.0 on macOS.

`values.yaml`:
```yaml
master:
  replicaCount: 1
  persistence:
    enabled: false
volume:
  replicaCount: 1
  dataVolumes:
    - name: data
      mountPath: /data
      persistence:
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 2Gi
filer:
  enabled: true
  replicaCount: 1
  existingConfigmap: "my-seaweedfs-filer-config"
s3:
  enabled: true
  replicaCount: 1
  auth:
    enabled: true
    existingSecret: "my-secret-integrations"
mariadb:
  enabled: false
```

`my-seaweedfs-filer-config.yaml` ConfigMap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "my-seaweedfs-filer-config"
data:
  filer.toml: |-
    [redis2]
    enabled = true
    address = "my-redis-master:6379"
    password = "some-password"
```

`my-secret-integrations.yaml` Secret:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: "my-secret-integrations"
stringData:
  config.json: |
    {
      "identities": [
        {
          "name": "admin",
          "credentials": [
            {
              "accessKey": "some-access-key",
              "secretKey": "some-secret-key"
            }
          ],
          "actions": [
            "Admin:bucket1",
            "List:bucket1",
            "Read:bucket1",
            "Tagging:bucket1",
            "Write:bucket1"
          ]
        }
      ]
    }
```

### What is the expected behavior?

s3 pod should come up

### What do you see instead?

Everything but S3 comes up.

The logs show:
```
2024-07-30 20:27:50.455Z I0730 20:27:50.455742 config.go:53 Reading : Config File "security" Not Found in "[/opt/bitnami/seaweedfs /opt/bitnami/seaweedfs/.seaweedfs /usr/local/etc/seaweedfs /etc/seaweedfs]"
2024-07-30 20:27:50.547Z I0730 20:27:50.547568 s3.go:210 S3 read filer buckets dir: /buckets
2024-07-30 20:27:50.548Z I0730 20:27:50.547651 s3.go:217 connected to filer my-seaweedfs-filer:8888 grpc address my-seaweedfs-filer:18888
2024-07-30 20:27:50.548Z W0730 20:27:50.547945 auth_credentials.go:149 fail to read /auth/config.json : open /auth/config.json: not a directory
2024-07-30 20:27:50.548Z F0730 20:27:50.548023 auth_credentials.go:124 fail to load config file /auth/config.json: fail to read /auth/config.json : open /auth/config.json: not a directory
```

It appears that when using an existing secret, something isn't going right with how the auth directory gets set up.

### Additional information

Let me know if there's anything you need me to do to reproduce it.

Thanks!

**Comment by RangerRick** [comment]
FYI, I was able to work around this by adding the following config, overriding the defaults from the seaweedfs deployment:

```yaml
  s3:
    ...
    args:
      - -logtostderr=true
      - -v=1
      - s3
      - -config=/my-secrets/config.json
      - -ip.bind=0.0.0.0
      - -port=8333
      - -port.grpc=18333
      - -filer=my-seaweedfs-filer:8888
    auth:
      enabled: true
      existingSecret: "my-secret-integrations"
    extraVolumes:
      - name: "my-secrets"
        secret:
          secretName: "my-secret-integrations"
    extraVolumeMounts:
      - name: "my-secrets"
        mountPath: "/my-secrets"
        readOnly: true
```
