### ISSUE TITLE
Condition: All nodes have the slave role (no master) at a same time, using Redis Sentinel @Kubernetes

### ISSUE THREAD

**Issue by BernardBerenes** [bitnami/charts#28599]
### Name and Version

bitnami/redis

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Applying redis persistence volume 
2. Helm install

### Are you using any custom parameters or values?

**This is my helm install command with params**

```
helm install redis bitnami/redis \
  --namespace redis \
  -f ./values.yaml \
  --set sentinel.enabled=true \
  --set sentinel.masterSet=mymaster \
  --set sentinel.quorum=2 \
  --set sentinel.downAfterMilliseconds=2000 \
  --set sentinel.parallelSyncs=1 \
  --set volumePermissions.enabled=true \
  --set replica.replicaCount=3 \
  --set auth.enabled=true \
  --set auth.password=**** \
  --set replica.persistence.size=200Mi \
  --set sentinel.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key="kubernetes.io/hostname" \
  --set sentinel.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].operator="In" \
  --set sentinel.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values[0]="worker1" \
  --set sentinel.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values[1]="worker2" \
  --set sentinel.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values[2]="worker3" \
  --set clusterDomain=cluster.local \
  --set nameOverride=redis
```
**values.yaml**
```yaml
cluster:
  enabled: true
  slaveCount: 2

persistence:
  enabled: true
  storageClass: "standard"
  size: 200Mi

tolerations:
  - key: "node.kubernetes.io/disk-pressure"
    operator: "Exists"
    effect: "NoSchedule"

networkPolicy:
  enabled: true

clusterDomain: cluster.local
nameOverride: redis

sentinel:
  enabled: true
  masterSet: mymaster
  quorum: 2
  down-after-milliseconds: 500
```

### What is the expected behavior?

There will always be one master among the 3 Redis nodes, and not all Redis nodes will be in the slave role at the same time. 

### What do you see instead?

<img width="216" alt="Screenshot 2024-07-31 at 14 53 33" src="https://github.com/user-attachments/assets/c0b0af38-6191-43eb-99f6-dd444c2acc06">

Role master always changed after connected, read write and switch to other node.
