### ISSUE TITLE
[bitnami/postgresql-ha] pgpool Container Crashes Due to Missing pgpool.conf File from ConfigMap Mount

### ISSUE THREAD

**Issue by anaskhantpl** [bitnami/charts#28612]
### Name and Version

bitnami/pgpool latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have running postgres cluster not `repmgr `in same environment. If i don't use any custom file mount, then its work perfectly. 
With pgpool.conf, The pgpool pod crashes with a `CrashLoopBackOff` status because it cannot find the `pgpool.conf` file at the specified mount path `/config`

### Deployment Details

**Helm Version:** v3.14.4
**Kubernetes Version:** v1.28.8+k3s1
**Environment:** Local Kubernetes cluster `K3d`
**OS:** Ubuntu 22.04

### Steps to Reproduce

**Values.yaml:**
```
replicaCount: 1

image:
  repository: bitnami/pgpool
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  ports:
    pgpool: 5432
    admin: 9898

env:
  PGPOOL_USER_CONF_FILE: /config/pgpool.conf
  PGPOOL_BACKEND_NODES: "0:db-cluster-rw.default:5432,1:db-cluster-ro.default:5432,2:db-cluster-r.default:5432"
  PGPOOL_SR_CHECK_USER: postgres
  PGPOOL_ENABLE_LDAP: "no"
  PGPOOL_POSTGRES_USERNAME: postgres
  PGPOOL_ADMIN_USERNAME: admin

secrets:
  PGPOOL_SR_CHECK_PASSWORD: A1VuuZ8UqwucLqexXAtWWLB84bVAqCaWhnC9DClQKAOis0yXh4k1EAp9LDx6tD
  PGPOOL_POSTGRES_PASSWORD: adminpassword
  PGPOOL_ADMIN_PASSWORD: adminpassword

#securityContext:
#  runAsUser: 0  # root user
securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

configMap:
  name: pgpool-config
  ```
  
**deployment.yaml:**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgpool.fullname" . }}
  labels:
    app: {{ include "pgpool.name" . }}
    chart: {{ include "pgpool.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "pgpool.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "pgpool.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.ports.pgpool | int  }}
        - containerPort: {{ .Values.service.ports.admin | int }}
        env:
        - name: PGPOOL_USER_CONF_FILE
          value: "{{ .Values.env.PGPOOL_USER_CONF_FILE }}"
        - name: PGPOOL_BACKEND_NODES
          value: "{{ .Values.env.PGPOOL_BACKEND_NODES }}"
        - name: PGPOOL_SR_CHECK_USER
          value: "{{ .Values.env.PGPOOL_SR_CHECK_USER }}"
        - name: PGPOOL_SR_CHECK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "pgpool.fullname" . }}-secret
              key: PGPOOL_SR_CHECK_PASSWORD
        - name: PGPOOL_ENABLE_LDAP
          value: "{{ .Values.env.PGPOOL_ENABLE_LDAP }}"
        - name: PGPOOL_POSTGRES_USERNAME
          value: "{{ .Values.env.PGPOOL_POSTGRES_USERNAME }}"
        - name: PGPOOL_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "pgpool.fullname" . }}-secret
              key: PGPOOL_POSTGRES_PASSWORD
        - name: PGPOOL_ADMIN_USERNAME
          value: "{{ .Values.env.PGPOOL_ADMIN_USERNAME }}"
        - name: PGPOOL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "pgpool.fullname" . }}-secret
              key: PGPOOL_ADMIN_PASSWORD
        volumeMounts:
        - name: config-volume
          mountPath: /config
          subPath: pgpool.conf
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser | int  }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "pgpool.fullname" . }}-config
          items:
          - key: pgpool.conf
            path: pgpool.conf
 ```
**configmap.yaml:**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgpool.fullname" . }}-config
  labels:
    app: {{ include "pgpool.name" . }}
    chart: {{ include "pgpool.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  pgpool.conf: |-
    logging_collector = on
    log_directory = '/tmp'
    log_filename = 'pgpool-%Y-%m-%d_%H%M%S.log'
    log_truncate_on_rotation = on
    log_rotation_size = 10MB
    
  ```

### Debugging:

**pgpool-logs:**

```
root@k3d:/home/anas# kubectl logs pgpool-5c8c844694-gg4g5
pgpool 20:12:10.42 INFO  ==> 
pgpool 20:12:10.42 INFO  ==> Welcome to the Bitnami pgpool container
pgpool 20:12:10.43 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
pgpool 20:12:10.43 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
pgpool 20:12:10.43 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
pgpool 20:12:10.43 INFO  ==> 
pgpool 20:12:10.44 INFO  ==> ** Starting Pgpool-II setup **
pgpool 20:12:10.47 INFO  ==> Validating settings in PGPOOL_* env vars...
pgpool 20:12:10.48 ERROR ==> The provided PGPOOL_USER_CONF_FILE: /config/pgpool.conf must exist.
```
**desc-configmap:**

```
root@k3d:/home/anas# kubectl describe configmap pgpool-config
Name:         pgpool-config
Namespace:    default
Labels:       app=pgpool
              app.kubernetes.io/managed-by=Helm
              chart=pgpool-0.1.0
              heritage=Helm
              release=pgpool
Annotations:  meta.helm.sh/release-name: pgpool
              meta.helm.sh/release-namespace: default

Data
====
pgpool.conf:
----
logging_collector = on
log_directory = '/tmp'
log_filename = 'pgpool-%Y-%m-%d_%H%M%S.log'
log_truncate_on_rotation = on
log_rotation_size = 10MB

BinaryData
====

Events:  <none>
```

### What do you see instead?

NULL
