### ISSUE TITLE
[bitnami/postgresql] $authEnabled NOTES.txt in Postgresql helm chart is not correct

### ISSUE THREAD

**Issue by vda** [bitnami/charts#28613]
### Name and Version

bitnami/postgresql --version 13.4.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I use this simple setting during install bitnami/postgresql helm chart

```yaml
auth:  
    existingSecret: my-secret
```
    
and got warning
```
WARNING: PostgreSQL has been configured without authentication, this is not recommended for production environments.
```

```
{{- $authEnabled := and (not (or .Values.global.postgresql.auth.existingSecret .Values.auth.existingSecret)) (or $postgresPassword .Values.auth.enablePostgresUser (and (not (empty $customUser)) (ne $customUser "postgres"))) }}
{{- if not $authEnabled }}

WARNING: PostgreSQL has been configured without authentication, this is not recommended for production environments.
{{- end }}
```

Seems like `(not (or .Values.global.postgresql.auth.existingSecret .Values.auth.existingSecret))` will be _FALSE_ if you set `.Values.global.postgresql.auth.existingSecret` or `.Values.auth.existingSecret` which leads to the fact that `$authEnabled` also will be _FALSE_

**Comment by vda** [comment]
even with such settings:

```
auth:
    database: my-db
    existingSecret: my-secret    
    
    enablePostgresUser: true
    postgresPassword: "aaa"
    username: "bbb"
    password: "ccc"    
    replicationUsername: repl_user
    replicationPassword: "ddd"
```
    
I got

_WARNING: PostgreSQL has been configured without authentication, this is not recommended for production environments._
