### ISSUE TITLE
[bitnami/influxdb] InfluxDB Relay healthcheck in GCP.

### ISSUE THREAD

**Issue by anton-chuhunou** [bitnami/charts#2862]
**Which chart**:
0.5.0

**Describe the bug**
GCP only supports HTTP 200 codes in its healthchecks. Since InfluxDB relay uses HTTP 204 for it's /ping endpoint, healthcheck never gets healthy status. Because of that LoadBalancer cannot forward traffic to this "unhealthy" backend and the whole setup is not working.

**To Reproduce**
1. Enable ingress in the helm chart.
2. Deploy helm chart.
3. Describe ingress: ```kubectl describe ingress xxxxxx```
4. Describe backend and healthcheck
```
gcloud compute backend-services describe xxxxxxxxxxxxxxxx --global
gcloud compute health-checks describe xxxxxxxxxxxxxxxx --global
```

**Comment by carrodher** [comment]
Hi, the readiness/liveness probe for **influxdb** consists basically in running the following command
```
influx -host $POD_IP -port {{ .Values.influxdb.containerPorts.http }} -execute "SHOW DATABASES"
```
https://github.com/bitnami/charts/blob/master/bitnami/influxdb/templates/influxdb/deployment-standalone.yaml#L192
in the same way the **influxdb relay** readiness/liveness probe is based on the socket connection
```yaml
          readinessProbe:
            tcpSocket:
              port: http
```
https://github.com/bitnami/charts/blob/master/bitnami/influxdb/templates/relay/deployment.yaml#L87

I don't remember to see this issue in all the different platforms we are testing like GKE, AKS, IKS, or TKG; it seems a very specific use case related to the platform. What do you suggest to make it works? PR are welcome just in case you find a proper solution. In the same way, the probes can be disabled by setting the `relay.readinessProbe.enabled` parameter to false (same for liveness and also influxdb deployment)

**Comment by AnCh7** [comment]
1. InfluxDB relay returns `HTTP 204 No Content` in it's /ping endpoint. See here:
```
if r.URL.Path == "/ping" && (r.Method == "GET" || r.Method == "HEAD") {
			w.Header().Add("X-InfluxDB-Version", "relay")
			w.WriteHeader(http.StatusNoContent)
			return
	}
```
https://github.com/influxdata/influxdb-relay/blob/master/relay/http.go

2. GCP healthchecks supports only HTTP 200 OK:
https://cloud.google.com/load-balancing/docs/health-check-concepts
```
When a health check uses the HTTP, HTTPS, or HTTP/2 protocol, each probe requires an HTTP 200 (OK) response code to be delivered before the probe timeout.
```

See similar ticket with telegraf: 
https://github.com/influxdata/telegraf/issues/4935

Since u have a forked InfluxDB relay version (BTW, I can't find its sources, there is only compiled binary), I thought  I might want to change it.

**Comment by marcosbc** [comment]
Thanks for the details @AnCh7. However, I'm not sure this affects the Bitnami chart, as it does not enable a `httpGet` readinessCheck/livenessCheck, instead it runs the command that @carrodher mentioned above.

**Comment by AnCh7** [comment]
As I can see here https://github.com/bitnami/charts/blob/master/bitnami/influxdb/templates/relay/deployment.yaml:
```
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.relay.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.relay.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.relay.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.relay.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.relay.readinessProbe.failureThreshold }}
```
InfluxDB Relay doesn't have any custom readiness/liveness probe logic, so it will be doing simple HTTP requests to relay pod (using `/` endpoint). These requests will fail because relay is not listening on `\`. It can be fixed by using instead `\ping`, relay is configured with this endpoint BUT it will still fail because GCP doen't understand HTTP 204 response.
