### ISSUE TITLE
[bitnami/minio] Ability to set different drivesPerNode and replica count for zones

### ISSUE THREAD

**Issue by jani888** [bitnami/charts#28682]
### Name and Version

bitnami/minio 14.6.16

### What is the problem this feature will solve?

Currently, there are 3 options, which configure the drive and node counts of the minio cluster: replicaCount, drivesPerNode and zones. 

When you create a pool (zone) in minio with a given replica count and drivesPerNode settings, you cannot change these parameters in the zone. Your only option is to create a new pool with the new config, and slowly decommission the old pool. 

The problem is, that with the bitnami/minio chart, you do not have the option to set different drivesPerNode and the replicaCount values for different zones. 

### What is the feature you are proposing to solve the problem?

It would be nice if you could set the replicaCount and drivesPerNode values on a per-zone basis. The api could look something like this:

```yaml
zones:
  zone1:
    statefulset:
      replicaCount: 2
      drivesPerNode: 2
  zone2:
    statefulset:
      replicaCount: 8
      drivesPerNode: 1
```
