### ISSUE TITLE
[bitnami/prometheus-operator] Add read permissions on namespaces for prometheus 

### ISSUE THREAD

**Issue by mboutet** [bitnami/charts#2873]
**Which chart**:
chart: bitnami/prometheus-operator
version: 0.20.3

**Is your feature request related to a problem? Please describe.**
Prometheus is unable to scrape metrics for objects in other namespaces than its own.

**Describe the solution you'd like**
Adding the following rule to [prometheus/clusterrole.yaml](https://github.com/bitnami/charts/blob/master/bitnami/prometheus-operator/templates/prometheus/clusterrole.yaml) seems to do the trick.
```
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
```

**Describe alternatives you've considered**
If we don't want to add this rule by default, we could allow the user to specify additional rules in the values. For instance, under `prometheus.rbac.additionalRules`.

**Additional context**
I was deploying the `bitnami/nginx-ingress-controller-5.3.19` with the following metrics values:
```
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: default
    prometheusRule:
      enabled: false
```
I'm using `bitnami/prometheus-operator` deployed in the `prometheus` namespace. I also tried setting the `metrics.serviceMonitor.namespace` to `prometheus` but it doesn't work either. With the additional rule I am proposing, prometheus is able to scrape all the nginx metrics.

Let me know if I'm misunderstanding something. Otherwise, I can open a PR with my proposed modifications.
