### ISSUE TITLE
[postgresql-ha] Using with multiple users/databases

### ISSUE THREAD

**Issue by sergeyshaykhullin** [bitnami/charts#2876]
**Which chart**: postgresql-ha

**Is your feature request related to a problem? Please describe.**
- I can use initDb script to create another db/user, but only once
- I have to use sql

**Describe the solution you'd like**
```yaml
postgresql:
  users:
  - name: ...
    ...
  databases:
  - name: ...
    owners:
    - ...
    ...
```

**Additional context**
It should be idempotent sql script, to add ability to add more users/databases later
