### ISSUE TITLE
[bitnami/kafka] Execution error using helm install bitnami/kafka 30.0.2

### ISSUE THREAD

**Issue by 35596035** [bitnami/charts#28770]
### Name and Version

bitnami/kafka 30.0.2

### What architecture are you using?

None

### What steps will reproduce the bug?

I use `helm install kafka-cluster bitnami/kafka -f mykafka-master-values.yaml -n kafka` for k8s
error msg:

`Error: INSTALLATION FAILED: template: kafka/templates/controller-eligible/statefulset.yaml:44:38: executing "kafka/templates/controller-eligible/statefulset.yaml" at <include (print $.Template.BasePath "/secrets.yaml") .>: error calling include: template: kafka/templates/secrets.yaml:131:23: executing "kafka/templates/secrets.yaml" at <include "common.secrets.passwords.manage" (dict "secret" (printf "%s-kraft-cluster-id" (include "common.names.fullname" .)) "key" "kraft-cluster-id" "providedValues" (list "kraft.clusterId") "length" 22 "context" $)>: error calling include: template: kafka/charts/common/templates/_secrets.tpl:117:16: executing "common.secrets.passwords.manage" at <eq .failOnNew false>: error calling eq: incompatible types for comparison`

**Comment by 35596035** [comment]
before installation I use `helm repo add bitnami https://charts.bitnami.com/bitnami`

**Comment by javsalgar** [comment]
Hi! Could you share the values.yaml you used?

**Comment by cwrau** [comment]
Huh, this is probably introduced by me, see https://github.com/bitnami/charts/pull/28581, but I can't reproduce this

With the following `secret.yaml`;

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
    kraft-cluster-id: {{ include "common.secrets.passwords.manage" (dict "secret" "mysecret" "key" "kraft-cluster-id" "providedValues" (list) "length" 22 "context" $) }}
```

and symlinking the bitnami common chart, this just works
