### ISSUE TITLE
[bitnami/minio] Minio Helm chart persistence not working on Windows 11 Docker Desktop w/ HyperV and Kubernetes

### ISSUE THREAD

**Issue by SledgeHammer01** [bitnami/charts#28784]
### Name and Version

bitnami/minio:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

* Windows 11 x64 Pro
* Docker Desktop 4.25.1 w/ Hyper-V backend and single node Kubernetes enabled
* Latest bitnami/minio helm chart
* c:\users\xxx\.minio folder is shared in Docker UI and I gave it full R/W permission in Windows to "Everyone".

When I deploy the Helm chart as below, the pod fails to start up with "Operation not permitted" when it tries to initialize the database. I also tried `volumePermissions.enabled` to true. Also tried changing all the security contexts to run as user/group 0, non-root to false, elevated permission = true, etc. Still no write access :(.

PVC:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: minio
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
```

PV:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /host_mnt/c/users/xxx/.minio
```

values:

```yaml
        auth:
          rootPassword: xxx
        ingress:
          enabled: true
          hostname: minio.xxx.com
          ingressClassName: nginx
        tls:
          existingSecret: minio-tls
        persistence:
          existingClaim: minio
        volumePermissions:
          enabled: true
        apiIngress:
          enabled: true
          hostname: minio-api.xxx.com
          ingressClassName: nginx
          tls: true
          extraTls:
            - hosts:
                - minio-api.xxx.com
              secretName: minio-api-tls
```

### What do you see instead?

When I deploy the Helm chart as below, the pod fails to start up with "Operation not permitted" when it tries to initialize the database.

### Additional information

```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  74s                default-scheduler  Successfully assigned minio/minio-5c746994b6-t9rfd to docker-desktop
  Normal   Pulled     75s                kubelet            Container image "docker.io/bitnami/os-shell:12-debian-12-r27" already present on machine
  Normal   Created    75s                kubelet            Created container volume-permissions
  Normal   Started    75s                kubelet            Started container volume-permissions
  Normal   Pulled     25s (x4 over 74s)  kubelet            Container image "docker.io/bitnami/minio:2024.8.3-debian-12-r0" already present on machine
  Normal   Created    25s (x4 over 74s)  kubelet            Created container minio
  Normal   Started    25s (x4 over 74s)  kubelet            Started container minio
  Warning  BackOff    5s (x10 over 72s)  kubelet            Back-off restarting failed container minio in pod minio-5c746994b6-t9rfd_minio(2a191ca1-2fa7-43df-929a-7c0c13996156)

```

```
 16:21:16.56 INFO  ==>
 16:21:16.56 INFO  ==> Welcome to the Bitnami minio container
 16:21:16.56 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
 16:21:16.57 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
 16:21:16.57 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
 16:21:16.57 INFO  ==>
 16:21:16.57 INFO  ==> ** Starting MinIO setup **
/opt/bitnami/scripts/libminio.sh: line 364: /bitnami/minio/data/.root_user: Operation not permitted
```

**Comment by SledgeHammer01** [comment]
If I use this config, then I don't get the "Operation not permitted" error, but I still get a crash backoff and nothing is written to the share. No indication of what the error is.

```
apiIngress:
  enabled: true
  extraTls:
    - hosts:
        - minio-api.xxx.com
      secretName: minio-api-tls
  hostname: minio-api.xxx.com
  ingressClassName: nginx
  tls: true
auth:
  rootPassword: xxx
containerSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
ingress:
  enabled: true
  hostname: minio.xxx.com
  ingressClassName: nginx
persistence:
  existingClaim: minio
tls:
  existingSecret: minio-tls
```
