### ISSUE TITLE
nodeSelector and the podAffinity settings don't seem to work for the postgresql chart 

### ISSUE THREAD

**Issue by Marck** [bitnami/charts#28821]
### Name and Version

postgresql chart version ~14.3.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?
0. label a node with the label `node-role.kubernetes.io/worker=worker` 
2. Setup a chart.yaml with the postgresl dep
```
dependencies:
  - name: postgresql
    version: ~14.3.1
    repository: "oci://registry-1.docker.io/bitnamicharts"
```
3. Setup a values.yaml as stated below

4. Deploy the chart:
```
helm install chart test .
```
5. Observe that the postgresql pod is not being scheduled
6. Remove the `nodeSelector` key and see that the pod is being scheduled (albeit on the wrong host, master in my case) so the podAffinity doesn't seem to work too

Am I doing something wrong?
The helm template looks correct when I use `helm template . > output.yaml` and contains a valid nodeselector and a valid affinity.

### Are you using any custom parameters or values?

```
postgresql:
  enabled: true
  image:
    tag: 16
  auth:
    username: username
    password: password
    database: databasename
  primary:
    affinity:
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  node-role.kubernetes.io/worker: 'worker'
              topologyKey: kubernetes.io/hostname
            weight: 1
    nodeSelector:
      node-role.kubernetes.io/worker: 'true'
```

### What is the expected behavior?

Pod being scheduled on the node with the defined nodelabel

### What do you see instead?

Pod hanging in preeemption failed
