### ISSUE TITLE
common.compatibility.renderSecurityContext function does not work for arrays

### ISSUE THREAD

**Issue by hamza-m-masood** [bitnami/charts#28832]
### Name and Version

common/latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?

The `common.compatibility.renderSecurityContext` function does not work with arrays. For example if you set the following in the any containerSecurityContext for any chart:
```yaml
  containerSecurityContext:
    privileged: true
    capabilities:
      add:
      - NET_ADMIN
```
You will see that the securityContext will have the privileged set to true but the capabilities will not exist because it includes an array.

### Are you using any custom parameters or values?

Provided above

### What is the expected behavior?

To have the functions acknowledge the array in the securityContext as well.

### What do you see instead?

I see the array not being rendered.
