### ISSUE TITLE
[bitnami/rabbitmq] ingress.extraHosts points to service 'http' which does not exists

### ISSUE THREAD

**Issue by farlop** [bitnami/charts#2887]
**Which chart**:
bitnami/rabbitmq 7.0.1

**Describe the bug**
In order to use an ingress with relative path 'xxx.yyy.com/rabbitmq' for accesing to management, you have to use the 'ingress.extraHosts' parameter because there is no 'ingress.path'.

When using this approach, ingress resources are pointed to servicePort named 'http' instead of 'http-stats'.

It looks like this line is wrong: https://github.com/bitnami/charts/blob/2d8b47cbabed122d1a7dad222ac6cc51731de5fe/bitnami/rabbitmq/templates/ingress.yaml#L33

and it should be like the default rule:
https://github.com/bitnami/charts/blob/2d8b47cbabed122d1a7dad222ac6cc51731de5fe/bitnami/rabbitmq/templates/ingress.yaml#L24

**To Reproduce**
Provide a values.yaml file like this one

```
ingress:
  enabled: true
  hostname:
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  extraHosts:
  - name: xxx.yyy.com
    path: /rabbitmq(/|$)(.*)
  extraTls:
  - hosts:
    - xxx.yyy.com
    secretName: tls
```

See that the ingress deployed is pointing to a service which does not exists:
```
Rules:
  Host                  Path  Backends
  ----                  ----  --------
  xxx.yyy.com
                        /rabbitmq   rabbitmq:http ()
```

**Expected behavior**
ingress deployed should be like 
```
...
Rules:
  Host                  Path  Backends
  ----                  ----  --------
  xxx.yyy.com
                        /rabbitmq(/|$)(.*)   rabbitmq:http-stats (10.244.1.36:15672)
...
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}```
```

- Output of `kubectl version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}```
```

**Additional context**
I have walkarounded the problem by patching the ingress resource

`kubectl patch ing rabbitmq --type=json -p="[{'op':'replace','path':'/spec/rules/0/http/paths/0/backend/servicePort','value':'http-stats'}]"`
