### ISSUE TITLE
[bitnami/redis-cluster] Tekton Sidecars redis-cluster change port

### ISSUE THREAD

**Issue by kirrg001** [bitnami/charts#28894]
### Name and Version

docker.io/bitnami/redis-cluster:7.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi there!

I am using Tekton Sidecars on IBM cloud and I am not able to change the port.

```yaml
sidecars:
    - name: redis-cluster-node-0
      image: docker.io/bitnami/redis-cluster:7.2
      env:
          - name: "ALLOW_EMPTY_PASSWORD"
            value: "yes"
          - name: "REDIS_NODES"
            value: "redis-cluster-node-0 redis-cluster-node-1 redis-cluster-node-2"
          - name: "REDIS_CLUSTER_CREATOR"
            value: "yes"
          - name: "REDIS_CLUSTER_REPLICAS"
            value: "0"
          - name: "REDIS_CLUSTER_SLEEP_BEFORE_DNS_LOOKUP"
            value: "10"
          - name: "REDIS_PORT_NUMBER"
            value: "6380"
    - name: redis-cluster-node-1
      image: docker.io/bitnami/redis-cluster:7.2
      env:
          - name: "ALLOW_EMPTY_PASSWORD"
            value: "yes"
          - name: "REDIS_NODES"
            value: "redis-cluster-node-0 redis-cluster-node-1 redis-cluster-node-2"
          - name: "REDIS_PORT_NUMBER"
            value: "6381"
```

The port is still 6379.

When setting "command" the port change works, but the cluster no longer works.

```yaml
      image: docker.io/bitnami/redis-cluster:7.2
      env:
          - name: "ALLOW_EMPTY_PASSWORD"
            value: "yes"
          - name: "REDIS_NODES"
            value: "redis-cluster-node-0 redis-cluster-node-1 redis-cluster-node-2"
          - name: "REDIS_CLUSTER_CREATOR"
            value: "yes"
          - name: "REDIS_CLUSTER_REPLICAS"
            value: "0"
          - name: "REDIS_CLUSTER_SLEEP_BEFORE_DNS_LOOKUP"
            value: "10"
          - name: "REDIS_PORT_NUMBER"
            value: "6380"     
      command:
        - "redis-server"
        - "--port"
        - "6380"
```

I also tried without luck:

```yaml
args:
   - "/opt/bitnami/scripts/redis-cluster/run.sh"
   - "--port"
   - "6380"
```

### Are you using any custom parameters or values?

No.

### What is the expected behavior?

The expected behavior is that each node runs on its own port.

### What do you see instead?

No port change.

### Additional information

refs https://github.com/bitnami/charts/issues/13270
refs https://github.com/bitnami/charts/issues/13270
