### ISSUE TITLE
annotation on init cluster job

### ISSUE THREAD

**Issue by Perfect-Web** [bitnami/charts#2890]
https://github.com/bitnami/charts/blob/15c13ec45a64f95eb624c3b542655c5985a8a5d9/bitnami/redis-cluster/templates/init-cluster.yaml#L8

in case of using istio autoinject, this job will never finish and the helm deployment will timeout.
we need to be able to specify 
`sidecar.istio.io/inject: "true"` on the job

**Comment by javsalgar** [comment]
Hi, 

In some charts we have a `commonAnnotations` value that would be added to all objects. Would it make sense for this case? Also, maybe the `podAnnotations` value could be used for the job as well.

**Comment by Perfect-Web** [comment]
@javsalgar any of the 2 approaches would work for my situation

**Comment by Perfect-Web** [comment]
@javsalgar infact not really, i would need the main pods to work with the annotation but the init cluster not, so i would opt for a `job only` annocation

**Comment by mboutet** [comment]
@Perfect-Web, would this PR I've been working on solve your problem? https://github.com/bitnami/charts/pull/2895

**Comment by Perfect-Web** [comment]
@mboutet no, i do not see how would that help, it doesnt add any annotations to it

**Comment by mboutet** [comment]
Oh ok, I see. I thought you needed to bypass the helm hooks annotation. Sorry.

**Comment by javsalgar** [comment]
After thinking about it, I would like to work on a batch of changes that cover your case amongst others, so stay tuned! As soon as I have a PR, I will update this ticket.

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that we released a major version that now allows annotations in the job. Please let us know if it covers your use case.

**Comment by Perfect-Web** [comment]
@javsalgar there are 2 problems i have found with the new version:

1. Failed to install app redis-cluster. Error: UPGRADE FAILED: YAML parse error on redis-cluster/templates/redis-statefulset.yaml: error converting YAML to JSON: yaml: line 30: could not find expected ':'

this is when having
```
  podAnnotations:
    sidecar.istio.io/inject: "true"
```

and 

2. when specifying redis.resources

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue. I installed the chart and found no issues, as you can see here:

```
❯ kubectl get pods red-redis-cluster-cluster-create-cqfwx -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    sidecar.istio.io/inject: "true"
  creationTimestamp: "2020-07-01T14:27:05Z"
```

It seems that you are doing an upgrade, does the same issue happen when deploying a fresh one?

**Comment by Perfect-Web** [comment]
@javsalgar indeed this is an upgrade, i need this to work as it is production ...

**Comment by javsalgar** [comment]
Hi,

But just to confirm, do you see the issue when deploying a fresh instance? I want to make sure that the issue only appears when upgrading, so we can narrow down the causes of the issue

**Comment by Perfect-Web** [comment]
@javsalgar this issue is still not solved ...

**Comment by Perfect-Web** [comment]
update: seems this happens only if you upgrade from v2 to v3

**Comment by Perfect-Web** [comment]
update2: after upgrade from v2 to v3, im trying to add the following

```
redis:
  podAnnotations:
    sidecar.istio.io/inject: "true"
  resources:
    requests:
      cpu: 30m
      memory: 500Mi
    limits:
      cpu: 30m
      memory: 505Mi
```

it will break with same errors as mentioned initially
