### ISSUE TITLE
[bitnami/keycloak] Not able to reuse pvc/pv from previous deploy

### ISSUE THREAD

**Issue by sule26** [bitnami/charts#28912]
### Name and Version

bitnami/keycloak 22.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Just apply the chart with default values.

### Are you using any custom parameters or values?

```yaml
global:
  defaultStorageClass: ebs-sc
auth:
  adminUser: admin
tls:
  enabled: true
  existingSecret: tls-keycloak
  usePem: true
production: true
nodeSelector:
  kubernetes.io/arch: amd64
service:
  type: ClusterIP
  http:
    enabled: true
  ports:
    http: 80
    https: 443
  # loadBalancerIP: ""
ingress:
  enabled: true
  ingressClassName: nginx-internal
  hostname: keycloak.internal
  hostnameStrict: true
  servicePort: https
  tls: true
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
logging:
  output: json
  level: INFO
```

### What is the expected behavior?

I expected to configure Keycloak through the UI, uninstall the application, then reinstall it, and still find my settings intact when reopening the UI.

### What do you see instead?

I'm encountering the same issue described in [this guide](https://docs.bitnami.com/kubernetes/faq/troubleshooting/troubleshooting-helm-chart-issues/#persistence-volumes-pvs-retained-from-previous-releases). When I delete the PVC and reinstall the application, a new PVC is created, but it binds to a different PV instead of the original one.
