### ISSUE TITLE
[bitnami/mongodb] MongoDB primary node and secondary node are always deployed in the same node in AWS EKS

### ISSUE THREAD

**Issue by chowwaihei1228** [bitnami/charts#2891]
**Which chart**:
mongodb (Version 7.14.8)

**Describe the bug**
I find the primary node and secondary node are deployed in the same node by using values-production.yaml. 

Then I try to use Pod Anti Affinity with **requiredDuringSchedulingIgnoredDuringExecution** to prevent such issue but failed. I observe the persistent volumes are created and mounted by the same node before the pods are created, and therefore both primary and secondary pods must be scheduled in that node. 

I see that there is no such issue in redis master and slave nodes, where all pods are install in distinct nodes in different AZs. 

**To Reproduce**
1. Edit values-production.yaml
```
affinity: 
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - mongodb
      topologyKey: failure-domain.beta.kubernetes.io/zone
```
2. helm install mongodb bitnami/mongodb -f values-production.yaml
3. kubectl get pod 
```
NAME                  READY   STATUS    RESTARTS   AGE
mongodb-arbiter-0     1/1     Running   0          19m
mongodb-primary-0     2/2     Running   0          19m
mongodb-secondary-0   0/2     Pending   0          19m  
```
4. kubectl describe pod mongodb-secondary-0
```
Events:
  Type     Reason             Age                From                Message
  ----     ------             ----               ----                -------
  Normal   NotTriggerScaleUp  27s                cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 max node group size reached
  Warning  FailedScheduling   25s (x4 over 31s)  default-scheduler   pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
  Warning  FailedScheduling   21s                default-scheduler   0/3 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules, 2 node(s) had volume node affinity conflict.
```

**Expected behavior**
Either primary node or secondary node cannot be created due to volume node affinity conflict.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @chowwaihei1228 

This is related to Primary and Secondary nodes to be part of different statefulsets. Therefore, it doesn't consider a conflict to have both a primary and a secondary in the same node.

This is going to change soon since we're working on a chat refactorization that will put together both primary and secondary nodes under the same statefulset.

**Comment by chowwaihei1228** [comment]
> Hi @chowwaihei1228
> 
> This is related to Primary and Secondary nodes to be part of different statefulsets. Therefore, it doesn't consider a conflict to have both a primary and a secondary in the same node.
> 
> This is going to change soon since we're working on a chat refactorization that will put together both primary and secondary nodes under the same statefulset.

Hi @juan131 

Got it thanks! I'm looking forward for the new version.

**Comment by juan131** [comment]
Hi everyone,

A new major version of MongoDB (**8.0.0**) was released including refactoring the way to expose MongoDB nodes outside the K8s cluster, so there's one service per node. It also groups every secondary and primary node under the same statefulset. Please feel free to give it a try since it should address this issue.

More info at https://github.com/bitnami/charts/tree/master/bitnami/mongodb#to-800

**Comment by percenuage** [comment]
Hello,

I'm using mongodb chart (v10.4.0) on GKE with production values (no arbiter) with 3 replicas. I have the same problem : All replicas are deployed in the same node which is not good for availability. Maybe I miss some configuration.

My current values : 
```
fullnameOverride: hyper-db

replicaCount: 3

image:
  tag: 4.2.11-debian-10-r57

architecture: replicaset

auth:
  enabled: false

arbiter:
  enabled: false

persistence:
  size: 1Gi

serviceAccount:
  create: false

resources:
  requests:
    memory: 256Mi
  limits:
    memory: 256Mi

```

![image](https://user-images.githubusercontent.com/6691104/105226504-58d0d080-5b60-11eb-838a-e65b80227949.png)
