### ISSUE TITLE
Add extraHosts and hosts from extraRules to tls block of Ingress resource

### ISSUE THREAD

**Issue by maxnitze** [bitnami/charts#28948]
### Name and Version

bitnami/*

### What is the problem this feature will solve?

Hostnames can be configured in many ways in `ingress` blocks in charts. here's an example from the [`bitnami/keycloak`](https://github.com/bitnami/charts/blob/main/bitnami/keycloak/) chart:

```yaml
ingress:
  enabled: true
  hostname: keycloak.my-first-domain.com
  annotations:
    # ...
  extraHosts:
    - name: login.my-first-domain.com
    - name: keycloak.my-second-domain.com
  extraRules:
    - host: login.my-second-domain.com
      http:
        # ...
```

When I now enable `tls`

```yaml
ingress:
  # ...
  tls: true
  # ...
```

this results in only `ingress.hostname` in the `tls` block of the Ingress resource:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: # ...
  # ...
spec:
  rules:
    # ...
  tls:
    - hosts:
        - "keycloak.my-first-domain.com"
      secretName: keycloak.my-first-domain.com-tls
  # ...
```

### What is the feature you are proposing to solve the problem?

Would it make sense to automatically add all hostnames, also the ones from `ingress.extraHosts` and from `ingress.extraRules`, to the `tls` block in the Ingress resource?

If so there would be two options (afaik).

Option 1: Add all hosts to single tls entry

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: # ...
  # ...
spec:
  rules:
    # ...
  tls:
    - hosts:
        - "keycloak.my-first-domain.com"
        - "login.my-first-domain.com"
        - "keycloak.my-second-domain.com"
        - "login.my-second-domain.com"
      secretName: keycloak.my-first-domain.com-tls
  # ...
```

Option 2: Create one tls entry per host

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: # ...
  # ...
spec:
  rules:
    # ...
  tls:
    - hosts:
        - "keycloak.my-first-domain.com"
      secretName: keycloak.my-first-domain.com-tls
    - hosts:
        - "login.my-first-domain.com"
      secretName: login.my-first-domain.com-tls
    - hosts:
        - "keycloak.my-second-domain.com"
      secretName: keycloak.my-second-domain.com-tls
    - hosts:
        - "login.my-second-domain.com"
      secretName: login.my-second-domain.com-tls
  # ...
```

One more thing to think about are duplicate entries. They probably need to be filtered out, so only one entry per domain is created (even though multiple entries should not break anything, I think).

What would be the way to go?

### What alternatives have you considered?

Manually adding them to the `ingress.extraTls` block is the way we are currently going in such cases. Here's an example:

```yaml
ingress:
  enabled: true
  hostname: keycloak.my-first-domain.com
  annotations:
    # ...
  extraHosts:
    - name: login.my-first-domain.com
    - name: keycloak.my-second-domain.com
  extraRules:
    - host: login.my-second-domain.com
      http:
        # ...
  tls: true
  extraTls:
    - secretName: login.my-first-domain.com-tls
      hosts:
        - "login.my-first-domain.com"
    - secretName: keycloak.my-second-domain.com-tls
      hosts:
        - "keycloak.my-second-domain.com"
    - secretName: login.my-second-domain.com-tls
      hosts:
        - "login.my-second-domain.com"
```

To reduce maintenance we sometimes use templating here:

```yaml
ingress:
  enabled: true
  hostname: keycloak.my-first-domain.com
  annotations:
  # ...
  extraHosts:
    - name: login.my-first-domain.com
    - name: keycloak.my-second-domain.com
  extraRules:
    - host: login.my-second-domain.com
      http:
      # ...
  tls: true
  extraTls: |-
    {{- range .Values.ingress.extraHosts }}
    - secretName: {{ tpl .name $ }}-tls
      hosts:
        - {{ tpl .name $ }}
    {{- end }}
    {{- range (include "common.tplvalues.render" (dict "value" .Values.ingress.extraRules "context" $) | fromYaml) }}
    - secretName: {{ .host }}-tls
      hosts:
        - {{ .host }}
    {{- end }}
```
