### ISSUE TITLE
[bitnami/postgresql-ha] XX000: unable to get session context , Unable to create a database when connecting via Pgpool.

### ISSUE THREAD

**Issue by Hareshraman** [bitnami/charts#28968]
### Name and Version

bitnami/postgresql-ha:14.2.16

### What architecture are you using?

None

### What steps will reproduce the bug?

Pre-requisite

Npgsql nuget: `"Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.4"`.
Postgresql-ha:14.2.16

I am encountering an issue while attempting to connect to a PostgreSQL Pgpool server using Entity Framework Core. The setup involves the utilization of the Postgresql HA Helm Chart by Bitnami, which sets up a high-availability PostgreSQL cluster. The intended behavior is for EF Core to create the database if it doesn't already exist and subsequently migrate data. However, upon initiating the connection and migration process, I am immediately confronted with the following error:
```
Npgsql.PostgresException (0x80004005): XX000: unable to get session context.
```
My architecture comprises a PostgreSQL Pgpool server orchestrated via the Bitnami Postgresql HA Helm Chart. The primary goal is to establish a connection using Entity Framework Core and perform migrations to set up the initial data structure. Regrettably, the encountered error is impeding progress.

Ideally, when EF Core connects to the PostgreSQL Pgpool server, it should be able to acquire the necessary session context to proceed with database operations, including database creation and data migration.

Steps Taken:

Configured the PostgreSQL Pgpool server using the Bitnami Postgresql HA Helm Chart. Attempted to connect to the database and initiate data migration using Entity Framework Core. Encountered the Npgsql.PostgresException with the error message indicating a failure to obtain the session context (XX000: unable to get session context).

1.  In our environment we're using postgresql-ha chart , 2 replicas of pgpool, and 3 replicas of Postgresql server. We use EF core, `<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.4" />` . 
2. We used to set `global.postgresql.database` as 'db1' 
3. We create migrations with the help of a helm hook job, which runs as a pre-install job that ensures migrations are created. 
4. The connection string in _npgsqlConnectionStringBuilder 
```
_npgsqlConnectionStringBuilder.Host = pgpool.infra.svc.cluster.local
_npgsqlConnectionStringBuilder.Port = 5432
_npgsqlConnectionStringBuilder.Database = db1
_npgsqlConnectionStringBuilder.Username = postgres
_npgsqlConnectionStringBuilder.Password = "randompassword"
```

Now to reproduce the issue.
1. Set `global.postgresql.database` empty, `postgresql.database` should be empty to ensure a database doesn't exist
2. Run a migration to ensure the `db1` database is created
3. Database is not created if it doesn't exist `db1` 

Does this mean we cannot create databases if my connection string is pgpool ? or only if connect to postgresql service. ? 

### Are you using any custom parameters or values?
```yaml
  postgresql-ha:
    persistence: 
      enabled: false
    global:
      postgresql:
        database: ""
    pgpool:
      ## @param pgpool.logConnections Log all client connections (PGPOOL_ENABLE_LOG_CONNECTIONS)
      logConnections: true
      ## @param pgpool.logHostname Log the client hostname instead of IP address (PGPOOL_ENABLE_LOG_HOSTNAME)
      logHostname: true
       ## @param pgpool.logPerNodeStatement Log every SQL statement for each DB node separately (PGPOOL_ENABLE_LOG_PER_NODE_STATEMENT)
      logPerNodeStatement: true
      ## pgpool.childMaxConnections The maximum number of client connections in each child process (PGPOOL_CHILD_MAX_CONNECTIONS)
      childMaxConnections: "150"
      ## pgpool.childLifeTime The time in seconds to terminate a Pgpool-II child process if it remains idle (PGPOOL_CHILD_LIFE_TIME)
      childLifeTime: "150"
      ## clientIdleLimit The time in seconds to disconnect a client if it remains idle since the last query (PGPOOL_CLIENT_IDLE_LIMIT)
      clientIdleLimit: "150"
      ## connectionLifeTime The time in seconds to terminate the cached connections to the PostgreSQL backend (PGPOOL_CONNECTION_LIFE_TIME)
      connectionLifeTime: "180"
      resources:
        limits:
          cpu: 750m
          memory: 1536Mi
        requests:
          cpu: 500m
          memory: 1024Mi
    postgresql:
      ## Maximum total connections postgres can handle
      maxConnections: "200"
      resources:
        requests:
          cpu: 500m
          memory: 1024Mi
        limits:
          cpu: 750m
          memory: 1536Mi
```
### What is the expected behavior?

1. Database is created if the database doesn't exist 
2. Migration created successfully. 

### What do you see instead?

1. Database is not created, if it doesn't exist.
