### ISSUE TITLE
[bitnami/elasticsearch] ServiceAccount not getting added and creation of the wrong serviceaccount

### ISSUE THREAD

**Issue by shin71** [bitnami/charts#28970]
### Name and Version

bitnami/elasticsearch 21.3.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

using eksctl to create the IRSA
```bash
eksctl create iamserviceaccount \
    --name aws-es-s3-backup \
    --namespace default \
    --cluster my-cluster \
    --attach-policy-arn arn:aws:iam::$account_id:policy/S3ElasticSearchBackupRepoPolicy \
    --override-existing-serviceaccounts \
    --approve
```
verify the formation of SA in both aws and eks cluster (verified)
```bash
kubectl get serviceaccount
eksctl get iamserviceaccount
```
check the mounting of tokens and IRSA for a test pod (working)
```YAML
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  serviceAccountName: aws-es-s3-backup
  automountServiceAccountToken: false 
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    # command: ["/bin/sh", "-c", "aws s3api get-bucket-location --bucket snaps.example.com && sleep 3600"] # for verifying permissions
    command: ["/bin/sh", "-c", "echo $AWS_WEB_IDENTITY_TOKEN_FILE && sleep 3600"]
```
`helm upgrade --install esk oci://registry-1.docker.io/bitnamicharts/elasticsearch --values "values-for-ES.yaml"
`

### Are you using any custom parameters or values?

```YAML
master:
  masterOnly: false
  replicaCount: 1
  # for existing SA
  automountServiceAccountToken: false 
  serviceAccount.create: false
  serviceAccount.name: aws-es-s3-backup
  serviceAccount.automountServiceAccountToken: false  
data:
  replicaCount: 0
coordinating:
  replicaCount: 0
ingest:
  replicaCount: 0

security:
  enabled: true
  # PASSWORD must be the same value passed to elasticsearch to get an "out of the box" experience
  elasticPassword: "elastic"
  tls:
    # AutoGenerate TLS certs for elastic
    autoGenerated: true
    verificationMode: full
```

### What is the expected behavior?

expected behavior was mounting of $AWS_WEB_TOKEN_FILE and no creation of any new serviceAccount

### What do you see instead?

it created a new SA itself even though i have set serviceaccount.create: false
```bash
$ kubectl get serviceaccount
NAME                       SECRETS   AGE
aws-es-s3-backup           0         68m
default                    0         85m
esk-elasticsearch-master   0         20s
```
esk-elasticsearch-master was created by it 

No mounting of the token and even checked the path where it should have been 
```bash
$ kubectl exec svc/esk-elasticsearch -it bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "elasticsearch" out of: elasticsearch, sysctl (init), copy-tls-certificates (init), copy-default-plugins (init)
I have no name!@esk-elasticsearch-master-0:/$ echo $AWS_WEB_IDENTITY_TOKEN_FILE

I have no name!@esk-elasticsearch-master-0:/$ ls /var/run/
lock  mount
I have no name!@esk-elasticsearch-master-0:/$ exit
exit
```

### Additional information

I tried hardcoding the name of the SA in the charts\bitnami\elasticsearch\templates\master\statefulset.yaml 
`serviceAccountName: {{ template "elasticsearch.master.serviceAccountName" . }}
`
to
`serviceAccountName: aws-es-s3-backup`
then mounting of the token worked in the pod
```
I have no name!@esk-elasticsearch-master-0:/$ echo $AWS_WEB_IDENTITY_TOKEN_FILE
/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```
 but it still created a SA in the cluster
```
 $ kubectl get serviceaccount
NAME                       SECRETS   AGE
aws-es-s3-backup           0         68m
default                    0         85m
esk-elasticsearch-master   0         20s
```

**Comment by javsalgar** [comment]
Hi,

Just to ensure, are you using the values like this?

```
master:
  serviceAccount.create: false
  serviceAccount.name: aws-es-s3-backup
  serviceAccount.automountServiceAccountToken: false  
```

or like this

```
master:
  serviceAccount:
    create: false
    name: aws-es-s3-backup
    automountServiceAccountToken: false  
```

I think helm would not parse it correctly if you are using flat yaml
