### ISSUE TITLE
[bitnami/minio] `defaultBuckets` causes errors in `distributed` mode

### ISSUE THREAD

**Issue by simonhammes** [bitnami/charts#29034]
### Name and Version

bitnami/minio 14.7.2

### What architecture are you using?

arm64

### What steps will reproduce the bug?

```bash
helm upgrade --install minio bitnami/minio --values values.yaml
```

### Are you using any custom parameters or values?

```yaml
mode: distributed

statefulset.replicaCount: 3

auth:
  rootUser: admin
  rootPassword: super-secure-password

defaultBuckets: files,images
```

### What is the expected behavior?

Pods are healthy 

**or**

an error message appears

(according to the comment in `values.yaml`, `defaultBuckets` is only supported in `standalone` mode, but its value is templated into the StatefulSet in `distributed mode` and it does not throw an error)

### What do you see instead?

Pods are constantly crashing

```
Expected MINIO_* environment name and values across all servers to be same
+ a host of other error messages
```

### Additional information

Using the provisioning job works fine :)

Related: https://github.com/bitnami/containers/issues/16846
