### ISSUE TITLE
[bitnami/keycloak] realms/master/metrics not found

### ISSUE THREAD

**Issue by gabriel-suela** [bitnami/charts#29046]
### Name and Version

bitnami/keycloack 21.8.0

### What architecture are you using?

None

### What steps will reproduce the bug?

```yaml
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

### What is the expected behavior?

scrape metrics from master realm

### What do you see instead?

Page not found

### Additional information

![image](https://github.com/user-attachments/assets/2e084463-5169-42a1-aeb4-912309c8049f)
![image](https://github.com/user-attachments/assets/2b04470b-0cbc-4763-bef3-f2c4b06932c9)
