### ISSUE TITLE
Redis: Data loss on helm chart update

### ISSUE THREAD

**Issue by jonathon2nd** [bitnami/charts#29094]
### Name and Version

redis:20.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy redis sentinel
Use it for a time
Update it
Observe data loss via metrics

### Are you using any custom parameters or values?

```yaml
global:
  storageClass: "linstor-replica-one-local"
auth:
  existingSecret: redis-secret
  existingSecretPasswordKey: password
  enabled: true
  sentinel: false
image:
  tag: 7.2.4-debian-12-r13
architecture: replication
useHostnames: false
replica:
  replicaCount: 3
  podAntiAffinityPreset: hard
  persistence:
    size: 8Gi
  resources:
    requests:
      memory: "500Mi"
      cpu: "250m"
    limits: {}
sentinel:
  masterSet: payment
  enabled: true
  image:
    tag: 7.2.4-debian-12-r10
  resources:
    requests:
      memory: "500Mi"
      cpu: "250m"
    limits: {}
  quorum: 2
  getMasterTimeout: 90
  automateClusterRecovery: false
  redisShutdownWaitFailover: true
  downAfterMilliseconds: 60000
  failoverTimeout: 180000
  parallelSyncs: 1
metrics:
  resources:
    requests: {}
    limits: {}
  enabled: true
  redisTargetHost: "localhost"
  serviceMonitor:
    port: http-metrics
    enabled: true
  podMonitor:
    port: metrics
    enabled: true
  prometheusRule:
    enabled: true
    namespace: ""
    additionalLabels:
    rules:
      - alert: RedisDown
        expr: redis_up{service="{{ template "common.names.fullname" . }}-metrics"} == 0
        for: 2m
        labels:
          severity: error
        annotations:
          summary: Redis&reg; instance {{ "{{ $labels.instance }}" }} down
          description: Redis&reg; instance {{ "{{ $labels.instance }}" }} is down
      - alert: RedisKeyEviction
        expr: |
          increase(redis_evicted_keys_total{service="{{ template "common.names.fullname" . }}-metrics"}[5m]) > 0
        for: 1s
        labels:
          severity: error
        annotations:
          summary: Redis&reg; instance {{ "{{ $labels.instance }}" }} has evicted keys
          description: |
            Redis&reg; instance {{ "{{ $labels.instance }}" }} has evicted {{ "{{ $value }}" }} keys in the last 5 minutes.
sysctl:
  enabled: true
  command:
    - /bin/sh
    - -c
    - |-
        install_packages procps
        sysctl -w net.core.somaxconn=10000
        echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
  mountHostSys: true
```

### What is the expected behavior?

Data retained after helm chart update

### What do you see instead?

![image](https://github.com/user-attachments/assets/122e1bd0-c085-4dc7-bed0-63a6f6d655b2)
![image](https://github.com/user-attachments/assets/b1ea9c63-136f-4b19-bfaa-5fb5b91eaeea)
![image](https://github.com/user-attachments/assets/b070b26f-4e46-4f4a-884e-40ff248ac04a)

### Additional information

Wanting to get input on what could be causing this. This is not the first time this has been observed.
