### ISSUE TITLE
[logstash] networkPolicies ingress not opened on UDP protocol

### ISSUE THREAD

**Issue by dr4Ke** [bitnami/charts#29129]
### Name and Version

bitnami/logstash:6.3.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm using the syslog plugin with both TCP and UDP listening ports.
- configure values.yaml with:
``` yaml
containerPorts:
  - name: syslog-udp
    containerPort: 5514
    protocol: UDP
  - name: syslog-tcp
    containerPort: 5514
    protocol: TCP
```
- the TCP port is working, but not the UDP port, when sending syslog messages

Since the protocol is not included in the networkPolicies template for ingresses, we can see that the resulting policy contains:
``` yaml
spec:
  egress:
    - {}
  ingress:
    - ports:
        - port: 9600
          protocol: TCP
        - port: 5514
          protocol: TCP
        - port: 5514
          protocol: TCP
```

### Are you using any custom parameters or values?

``` yaml
containerPorts:
  - name: syslog-udp
    containerPort: 5514
    protocol: UDP
  - name: syslog-tcp
    containerPort: 5514
    protocol: TCP
```

### What is the expected behavior?

Network policy ingress opened on both TCP and UDP ports.

### What do you see instead?

Network policy ingress opened on TCP only.
