### ISSUE TITLE
[bitnami/mariadb] MariaDB implement list of databases/usernames like in MongoDB chart

### ISSUE THREAD

**Issue by Syntax3rror404** [bitnami/charts#29130]
### Name and Version

bitnami/mariadb 19.0.5

### What is the problem this feature will solve?

This feature solves the problem that only 1 database and username is allowed to creating during the init process.
There are some usecases which require more users and databases. Until today additional users and databases you need to add by manual steps.

### What is the feature you are proposing to solve the problem?

In the MongoDB chart bitnami/mongodb there is a solution implemented which also perfect fits for MariaDB:

```yaml
  ## MongoDB(&reg;) custom users and databases
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/mongodb#creating-a-user-and-database-on-first-run
  ## @param auth.usernames List of custom users to be created during the initialization
  ## @param auth.passwords List of passwords for the custom users set at `auth.usernames`
  ## @param auth.databases List of custom databases to be created during the initialization
  ##
  usernames: []
  passwords: []
  databases: []
```

Please implement the same for MariaDB
