### ISSUE TITLE
[bitnami/tomcat] Unable to install tomcat if an initContainers is set within a yaml value file.

### ISSUE THREAD

**Issue by irenee25** [bitnami/charts#29158]
### Name and Version

bitnami/tomcat 11.2.18

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Export default value within a file.
Just edit the content of initContainers.

For example : 
```
initContainers:
  - name: init-create-dir
    image: alpine
    imagePullPolicy: Always
```

### Are you using any custom parameters or values?

Yes, using a custom initContainers

```
initContainers:
  - name: init-create-dir
    image: alpine
    imagePullPolicy: Always
```

### What is the expected behavior?

The template must generate a template as below : 

```
      initContainers:
        - name: volume-permissions
          image: docker.io/bitnami/os-shell:11-debian-11-r94
          imagePullPolicy: "IfNotPresent"
          command:
            - /bin/bash
            - -ec
            - |
                chown -R 1001:1001 /bitnami/tomcat
          securityContext:
            runAsUser: 0
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: data
              mountPath: /bitnami/tomcat

        - image: alpine
          imagePullPolicy: Always
          name: init-create-dir

```

### What do you see instead?

      initContainers:
        - name: volume-permissions
          image: docker.io/bitnami/os-shell:11-debian-11-r94
          imagePullPolicy: "IfNotPresent"
          command:
            - /bin/bash
            - -ec
            - |
                chown -R 1001:1001 /bitnami/tomcat
          securityContext:
            runAsUser: 0
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: data
              mountPath: /bitnami/tomcat

      - image: alpine
        imagePullPolicy: Always
        name: init-create-dir

### Additional information

To fix the issue, edit the code of  tomcat/templates/_pod.tpl, near line 62.

Replace 

```
{{- if .Values.initContainers }}
{{ include "common.tplvalues.render" (dict "value" .Values.initContainers "context" $)  }}
{{- end }}
```

by 

```
{{- if .Values.initContainers }}
{{ include "common.tplvalues.render" (dict "value" .Values.initContainers "context" $) | nindent 2 }}
{{- end }}
```
( add indentation +2 )

Rendered template will be correct.
