### ISSUE TITLE
valkey: Wrong protocol 'valkeys' in redis exporter

### ISSUE THREAD

**Issue by klauserber** [bitnami/charts#29173]
### Name and Version

bitnami/valkey 0.3.15

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install with tls enabled.

### Are you using any custom parameters or values?
```yaml
  replica:
    replicaCount: 3
  sentinel:
    enabled: true

  networkPolicy:
    enabled: true

  tls:
    enabled: true
    existingSecret: valkey-tls
    autoGenerated: false
    authClients: false
    certCAFilename: ca.crt
    certFilename: tls.crt
    certKeyFilename: tls.key

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        prometheus: default
    prometheusRule:
      defaults: true
      enabled: false
      # alertLabels: {}
      # additionalRules: []
      ## -- Amount of connections that are usually active
      # persistentConnections: 1
  auth:
    enabled: true
    existingSecret: valkey-auth
    existingSecretPasswordKey: "password"
```

### What is the expected behavior?

The Redis exporter can connect to the valkey instance:

```
time="2024-09-03T11:13:39Z" level=info msg="Redis Metrics Exporter v1.62.0    build date: 2024-07-17-05:32:02    sha1: 620cb9964b0d7d7033fe5f9858e0952b7269de4d    Go: go1.22.5    GOOS: linux    GOARCH: amd64"
time="2024-09-03T11:13:39Z" level=info msg="Providing metrics at :9121/metrics"
time="2024-09-03T11:13:49Z" level=error msg="Couldn't connect to redis instance (redis://localhost:6379)"
time="2024-09-03T11:14:07Z" level=error msg="Couldn't connect to redis instance (redis://localhost:6379)"
```

### What do you see instead?

The Redis exporter cannot connect to the valkey instance

### Additional information

The error is here: https://github.com/bitnami/charts/blob/27551d76ef425175540319c9f14fef8e09530a0c/bitnami/valkey/templates/sentinel/statefulset.yaml#L575

I think the Redis exporter does not understand the protocol 'valkeys'.

Workaround:

values.yaml
```yaml
extraEnvVars:
  - name: REDIS_ADDR
    value: rediss://localhost:6379
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by falk-w** [comment]
+1

**Comment by falk-w** [comment]
> ### Name and Version
> bitnami/valkey 0.3.15
> 
> ### What architecture are you using?
> amd64
> 
> ### What steps will reproduce the bug?
> Install with tls enabled.
> 
> ### Are you using any custom parameters or values?
> ```yaml
>   replica:
>     replicaCount: 3
>   sentinel:
>     enabled: true
> 
>   networkPolicy:
>     enabled: true
> 
>   tls:
>     enabled: true
>     existingSecret: valkey-tls
>     autoGenerated: false
>     authClients: false
>     certCAFilename: ca.crt
>     certFilename: tls.crt
>     certKeyFilename: tls.key
> 
>   metrics:
>     enabled: true
>     serviceMonitor:
>       enabled: true
>       additionalLabels:
>         prometheus: default
>     prometheusRule:
>       defaults: true
>       enabled: false
>       # alertLabels: {}
>       # additionalRules: []
>       ## -- Amount of connections that are usually active
>       # persistentConnections: 1
>   auth:
>     enabled: true
>     existingSecret: valkey-auth
>     existingSecretPasswordKey: "password"
> ```
> 
> ### What is the expected behavior?
> The Redis exporter can connect to the valkey instance:
> 
> ```
> time="2024-09-03T11:13:39Z" level=info msg="Redis Metrics Exporter v1.62.0    build date: 2024-07-17-05:32:02    sha1: 620cb9964b0d7d7033fe5f9858e0952b7269de4d    Go: go1.22.5    GOOS: linux    GOARCH: amd64"
> time="2024-09-03T11:13:39Z" level=info msg="Providing metrics at :9121/metrics"
> time="2024-09-03T11:13:49Z" level=error msg="Couldn't connect to redis instance (redis://localhost:6379)"
> time="2024-09-03T11:14:07Z" level=error msg="Couldn't connect to redis instance (redis://localhost:6379)"
> ```
> 
> ### What do you see instead?
> The Redis exporter cannot connect to the valkey instance
> 
> ### Additional information
> The error is here:
> 
> https://github.com/bitnami/charts/blob/27551d76ef425175540319c9f14fef8e09530a0c/bitnami/valkey/templates/sentinel/statefulset.yaml#L575
> 
> I think the Redis exporter does not understand the protocol 'valkeys'.
> 
> Workaround:
> 
> values.yaml
> 
> ```yaml
> extraEnvVars:
>   - name: REDIS_ADDR
>     value: rediss://localhost:6379
> ```

Unfortunately, the workaround does not work.

```
time="2024-09-09T14:02:12Z" level=info msg="Redis Metrics Exporter v1.62.0    build date: 2024-08-06-20:58:24    sha1: 620cb9964b0d7d7033fe5f9858e0952b7269de4d    Go: go1.22.6    GOOS: linux    GOARCH: amd64"
time="2024-09-09T14:02:12Z" level=info msg="Providing metrics at :9121/metrics"
time="2024-09-09T14:02:16Z" level=error msg="Couldn't connect to redis instance (valkeys://localhost:6379)"
```

The variable is already set:
```
        - name: REDIS_ADDR
          value: valkeys://localhost:6379
```

So setting:
```
metrics:
  extraEnvVars:
    - name: REDIS_ADDR
      value: rediss://localhost:6379
```

Has no effect at least in my deployment. I am using:
- https://github.com/bitnami/charts/tree/main/bitnami/valkey
version: 0.3.15
