### ISSUE TITLE
[bitnami/redis] Can't mount module within Redis

### ISSUE THREAD

**Issue by Bajix** [bitnami/charts#2917]
I'm having issues with mounting a module to be loaded into redis. My parent chart has this:

```
redis:
  enabled: true
  cluster:
    enabled: false
  spec:
    containers:
      volumeMounts:
        - mountPath: /etc/redis/libranker.dylib
          name: libranker
          subPath: libranker.dylib
    volumes:
    - hostPath:
        path: /packages/popularity-ranker/release
      name: libranker
  configmap: |-
    loadmodule /etc/redis/libranker.dylib
```

Is this the correct way of mounting the module? How should this be done
