### ISSUE TITLE
extraEnvVars only support name-value pairs.

### ISSUE THREAD

**Issue by aldemira** [bitnami/charts#29175]
### Name and Version

bitnami/redis 20.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

To use a subPathExpr for volume mounts first one needs to define an environment variable for example:

```yaml
extraEnvVars:
 - name: POD_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.name
```

With that, we can set a subPathExpr like so:
```yaml
persistence:
   existingClaim: "mysuper-pvc-claim"
   subPathExpr: "$(POD_NAME)"
```

With this setting env variable isn't generated because the template only checks for name-value pairs.

### Are you using any custom parameters or values?

master.extraEnvVars
replica.extraEnvVars
master.persistence.subPathExpr
replica.persistence.subPathExpr

### What is the expected behavior?

Templates should add the env variable as defined above.

### What do you see instead?

My env variable is ignored.
