### ISSUE TITLE
Neo4j `persistence.annotations` not working as expected

### ISSUE THREAD

**Issue by st3v** [bitnami/charts#29180]
### Name and Version

bitnami/neo4j 0.1.8

### What architecture are you using?

None

### What steps will reproduce the bug?

Run `helm template foo oci://registry-1.docker.io/bitnamicharts/neo4j --set-json persistence.annotations='{"bar": "baz"}' --set 'service.type=ClusterIP'` and look at the annotations on the `volumeClaimTemplate` of the `StatefulSet` resource.

### Are you using any custom parameters or values?

`--set-json persistence.annotations='{"bar": "baz"}' --set 'service.type=ClusterIP'`

### What is the expected behavior?

```shell
helm template foo oci://registry-1.docker.io/bitnamicharts/neo4j --set-json persistence.annotations='{"bar": "baz"}' --set 'service.type=ClusterIP'
```
```yaml
 volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          bar: baz
...
```

### What do you see instead?

```shell
helm template foo oci://registry-1.docker.io/bitnamicharts/neo4j --set-json persistence.annotations='{"bar": "baz"}' --set 'service.type=ClusterIP'
```
```yaml
 volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          Error: 'error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string
            into Go value of type map[string]interface {}'
...
```

### Additional information

If I "wrap" the annotations in another object things work...

```shell
helm template foo oci://registry-1.docker.io/bitnamicharts/neo4j --set-json persistence.annotations='{"wrapper": {"bar": "baz"}}' --set 'service.type=ClusterIP'
```
```yaml
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          bar: baz
...
```

Other charts do not require this extra "wrapper object". For example, the following works just fine:

* Cassandra: 
  `helm template foo oci://registry-1.docker.io/bitnamicharts/cassandra --set-json persistence.annotations='{"bar": "baz"}'`
  
* Postgresql: 
  `helm template foo oci://registry-1.docker.io/bitnamicharts/postgresql --set-json primary.persistence.annotations='{"bar": "baz"}'`
  
* MySQL: 
  `helm template foo oci://registry-1.docker.io/bitnamicharts/mysql --set-json primary.persistence.annotations='{"bar": "baz"}'`

I'm not certain but believe the problem might be due to the extra `fromYaml` at the end of [this line](https://github.com/bitnami/charts/blob/28cf5f7b8e48370b31d79ed596fd26697ac4a0dc/bitnami/neo4j/templates/statefulset.yaml#L302).
