### ISSUE TITLE
[bitnami/keycloak] setting initdbScripts causes startup error

### ISSUE THREAD

**Issue by p4block** [bitnami/charts#29194]
### Name and Version

bitnami/keycloak

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Set initDbScripts 

### Are you using any custom parameters or values?

```yaml
keycloak:
  auth:
    adminUser: admin
    existingSecret: keycloak-env
    passwordSecretKey: admin-password
  production: true
  proxy: edge
  replicaCount: 1
  service:
    type: ClusterIP
  ingress:  
    enabled: true
    annotations:
      # https://stackoverflow.com/a/68811151/1581433
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    ingressClassName: nginx-public
    hostname: our-domain
    tls: true

  initdbScripts:
    move-providers.sh: |
      #!/bin/bash
      echo true

  metrics:
    enabled: true
```

### What is the expected behavior?

Container starts

### What do you see instead?

Container start fails with
 ```
keycloak 09:25:29.01 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
touch: cannot touch '/bitnami/keycloak/.user_scripts_initialized': No such file or directory
```

### Additional information

Seen previously at #3537
