### ISSUE TITLE
[bitnami/grafana-mimir] mimir gateway password - excessive quotes

### ISSUE THREAD

**Issue by netikras** [bitnami/charts#29214]
### Name and Version

bitnamicharts/grafana-mimir

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```yaml
cat /tmp/values.mimir.yaml | yq '.gateway.auth'
enabled: true
existingSecret: null
password: el-gato-loco
username: awesome-metrics
```

```bash
helm template mimir --create-namespace -n mimir oci://registry-1.docker.io/bitnamicharts/grafana-mimir --values /tmp/values.mimir.yaml --dry-run 2>&-  | grep password
  password: "\"ZWwtZ2F0by1sb2Nv\""
```

### Are you using any custom parameters or values?

yes

### What is the expected behavior?

password is properly base64-encoded

### What do you see instead?

extra quotes around the password. This causes helm to fail with

```
Error: UPGRADE FAILED: failed to create resource: Secret in version "v1" cannot be handled as a Secret: illegal base64 data at input byte 0
```
