### ISSUE TITLE
[bitnami/thanos] thanos: error: expected command but got "bucket"

### ISSUE THREAD

**Issue by dbrennand** [bitnami/charts#2922]
**Which chart**:
bitnami/thanos: 
Output from helm list:
`thanos                  monitoring      1               2020-06-25 09:23:39.9358571 +0000 UTC   deployed        thanos-1.1.1                    0.13.0`

**Describe the bug**
When installing the chart, the bucketweb container fails to start and the following error is produced in the logs:
```
Error parsing commandline arguments: expected command but got "bucket"
thanos: error: expected command but got "bucket"
```

**To Reproduce**
1. Follow the [steps provided here](https://github.com/bitnami/charts/tree/master/bitnami/thanos#integrate-thanos-with-prometheus-and-alertmanager):
![image](https://user-images.githubusercontent.com/52419383/85697368-a328c680-b6d1-11ea-94ca-cff1f4d9239f.png)

I am using the following `values.yaml` file:
```yaml
objstoreConfig: |-
  type: AZURE
  config:
    storage_account: "thanosstor"
    storage_account_key: "redacted"
    container: "thanosdata"
    endpoint: "https://thanosstor.blob.example.endpoint.com/"
    max_retries: 0
querier:
  dnsDiscovery:
    sidecarsService: prometheus-operator-prometheus-thanos
    sidecarsNamespace: monitoring
bucketweb:
  enabled: true
compactor:
  enabled: true
storegateway:
  enabled: true
ruler:
  enabled: true
  alertmanagers:
    - http://prometheus-operator-alertmanager.monitoring.svc.cluster.local:9093
  config: |-
    groups:
      - name: "metamonitoring"
        rules:
          - alert: "PrometheusDown"
            expr: absent(up{prometheus="monitoring/prometheus-operator"})
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

**Expected behavior**
The helm chart deploys successfully first time without the container failing.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"bb95a3814e91321a3821d669afc3707a8f35015f", GitTreeState:"clean", BuildDate:"2020-04-28T22:50:11Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Command provided via args shown in `kubectl describe pod thanos-webbucket-* -n monitoring`:

```
    Args:
      bucket
      web
      --http-address=0.0.0.0:8080
      --log.level=info
      --objstore.config-file=/conf/objstore.yml
      --refresh=30m
      --timeout=5m
```
