### ISSUE TITLE
[bitnami/elasticsearch] kibana not booting up

### ISSUE THREAD

**Issue by maipal-c** [bitnami/charts#29297]
### Name and Version

bitnami/elasticsearch:21.3.12

### What architecture are you using?

arm64

### What steps will reproduce the bug?

with k3s running on aws r8g worker instances

CONFIG (values.yaml) 

```
global:
   kibanaEnabled: true
   defaultStorageClass: "ebs-gp3"
security:
   enabled: true
   tls:
      restEncryption: true
      autoGenerated: true

# Kibana configuration ===================================================================

kibana:
   resources:
      requests:
         cpu: 10m
         memory: 256Mi
      limits:
         cpu: 300m
         memory: 512Gi
   persistence:
      enabled: false
   elasticsearch:
      security:
         auth:
            enabled: true
            kibanaUsername: elastic
            kibanaPassword: "3eSyWQgLbmnDVy9g"
         tls:
            enabled: true
            existingSecret: "elasticsearch-master-crt"
            usePemCerts: true

# master node configuration ============================================================

master:
   heapSize: 128m
   resources:
      requests:
         cpu: 10m
         memory: 128Mi
      limits:
         cpu: 500m
         memory: 512Mi
   persistence:
      enabled: true
      size: 1Gi
   masterOnly: true
   replicaCount: 1
   affinity:
      nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
               - matchExpressions:
                    - key: node.kubernetes.io/allow-ebs-attach
                      operator: In
                      values:
                         - "true"
                    - key: node.kubernetes.io/provider
                      operator: In
                      values:
                         - "aws"

# data node configuration ==============================================================

data:
   heapSize: 512m
   resources:
      requests:
         cpu: 10m
         memory: 512Mi
      limits:
         cpu: 500m
         memory: 1.5Gi
   persistence:
      enabled: true
      size: 2Gi
   replicaCount: 1
   affinity:
      nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
               - matchExpressions:
                    - key: node.kubernetes.io/allow-ebs-attach
                      operator: In
                      values:
                         - "true"
                    - key: node.kubernetes.io/provider
                      operator: In
                      values:
                         - "aws"

# coordinating node configuration ======================================================

coordinating:
   replicaCount: 0

# ingest node configuration ============================================================

ingest:
   replicaCount: 0

# other configuration ==================================================================

sysctlImage:
   resources:
      requests:
         cpu: 10m
         memory: 128Mi
      limits:
         cpu: 100m
         memory: 256Mi

copyTlsCerts:
   resources:
      requests:
         cpu: 10m
         memory: 128Mi
      limits:
         cpu: 100m
         memory: 256Mi
```
run command

```
helm upgrade --install \
 elasticsearch oci://registry-1.docker.io/bitnamicharts/elasticsearch \
 --namespace databases \
 --create-namespace \
 --values values.yaml \
 --version 21.3.12
```

Kibana Error logs
```
$k logs pod/elasticsearch-kibana-7d4dd94b95-r95z2
Defaulted container "kibana" out of: kibana, copy-default-plugins (init)
kibana 14:47:34.40 INFO  ==>
kibana 14:47:34.41 INFO  ==> Welcome to the Bitnami kibana container
kibana 14:47:34.41 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
kibana 14:47:34.41 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
kibana 14:47:34.41 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
kibana 14:47:34.41 INFO  ==>
kibana 14:47:34.44 INFO  ==> ** Starting Kibana setup **
kibana 14:47:34.46 INFO  ==> Configuring/Initializing Kibana...
kibana 14:47:34.47 INFO  ==> Found mounted configuration directory
kibana 14:47:34.57 INFO  ==> ** Kibana setup finished! **

kibana 14:47:34.58 INFO  ==> ** Starting Kibana **
```

on k8s side its showing terminated status code 132

### What do you see instead?

crashing container within 20 sec of start
