### ISSUE TITLE
[bitnami/mariadb-galera] upgrading does not run mariadb-upgrade

### ISSUE THREAD

**Issue by fireba11** [bitnami/charts#29306]
### Name and Version

[bitnami/mariadb-galera] 

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm currently running with chart v9.2.1, trying to upgrade to latest (14.0.9 chart and mariadb version to get the new LTS 11.4)

### Are you using any custom parameters or values?
```
persistence:
  size: 10Gi

resources:
  requests:
    cpu: '1'
    memory: 512Mi
  limits:
    cpu: '1'
    memory: 1Gi

# required to run concludis install.php
extraFlags: "--log_bin_trust_function_creators=ON --sql_mode=NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION --binlog-expire-logs-seconds=86400 --innodb-ft-cache-size=16000000"

# start all pods at once, we don't know which one got the latest data
podManagementPolicy: Parallel

podAntiAffinityPreset: hard

podDisruptionBudget:
  create: true
  minAvailable: 2

extraEnvVars:
  - name: TZ
    value: "Europe/Berlin"
```
### What is the expected behavior?

Either documentation how to run the upgrade script or automagically running upgrade on node restart.

### What do you see instead?

It seems to try STS, then fails and quits ...
