### ISSUE TITLE
[bitnami/harbor] Image push to Harbor registry takes a minimum of 30min and can go upto 45min also

### ISSUE THREAD

**Issue by nanarun13** [bitnami/charts#29302]
### Name and Version

bitnami/harbor:22.0.8

### What architecture are you using?

None

### What steps will reproduce the bug?

We have a Harbor registry setup using bitnami charts in our Kubernetes cluster. It uses Traefik as the ingress controller.

As per the traefik documentation, we have configured the ingress values.yaml.

Initially for bigger images, when our Jenkins builds were executed, the stage where we run the image push to Harbor registry took a lot of time to do a docker push action and eventually would result in a timeout or throwing a "HTTP 499 Client Closed Request" error. After following a number of technical issues reported on similar issues in the internet, we made the below configuration changes to our ingress controller values.yaml file:
```
traefik:
------------------
some code here
------------------
  ports:
    web:
      address: ":80"
      forwardedHeaders:
        insecure: true
      http:
        redirections:
          entrypoint:
            to: websecure
            scheme: https
      transport:
        respondingTimeouts:
          readTimeout: 0s
          writeTimeout: 0s
          idleTimeout: 0s        
    websecure:
      address: ":443"
      forwardedHeaders:
        insecure: true
      transport:
        respondingTimeouts:
          readTimeout: 0s
          writeTimeout: 0s
          idleTimeout: 0s
-----------------------
some code here
------------------------
```
WIth the above configuration, the frequent timeouts/http error 499 seems to have considerably reduced, making the image push action also successful, but unfortunately with a huge time duration( approx 30min-45min), which is way too high!!

Also, we do not see any errors in the postgresql DB pod logs or any of the other Harbor pods (registry, job service, exporter, etc)

Could you please help us in this regard? Any other configuration changes either in traefik or Harbor part required?

### What do you see instead?

The harbor push stage in our cicd pipeline gets executed, but takes a very long time (upto 45 min) for the stage to complete, this time is too high considering productions executions.
