### ISSUE TITLE
elasticsearch tls expired cannot renew

### ISSUE THREAD

**Issue by ferdiina** [bitnami/charts#29319]
### Name and Version

bitnami/elasticsearch-19.10.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I deployed Elasticsearch using helm and automatically generated a certificate. One year later, the certificate has expired. How can I automatically renew the certificate?
```yaml
security:
  elasticPassword: xxxxxxxxxxx
  enabled: true
  tls:
    autoGenerated: true
    restEncryption: true
```

I try to delete certs in secret:
elasticsearch-data-crt
elasticsearch-master-crt 
but start failed because the mount object did not exist

also, I tried to issue a new certificate using ca.crt, but could not find ca.key

### What do you see instead?
```
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed 
```
![image](https://github.com/user-attachments/assets/e71abbc5-1822-4584-baab-3469c30de110)
