### ISSUE TITLE
The problem running keytool 

### ISSUE THREAD

**Issue by Setxand** [bitnami/charts#29325]
### Name and Version

bitnami/spring-cloud-dataflow (latest)

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. deploy default SCDF latest chart to local docker-desktop's or minikube k8s
2. exec to container `kubectl exec -it...`
3. `keytool -importcert -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit -alias keycloak -file /tmp/keycloak-cert/keycloak.cer` (whatever certificate)

### What is the expected behavior?

it's expected behavior but I can't do it when run as user 0

### What do you see instead?

Permission denied for the adding of the cert to the keystore. I tried to run it as user 0 and group 0 for container and pod: 
```yaml
  podSecurityContext:
    runAsUser: 0  
    enabled: true
    fsGroupChangePolicy: OnRootMismatch
    sysctls: [ ]
    supplementalGroups: [ ]

  containerSecurityContext:
    enabled: true
    seLinuxOptions: null
    runAsUser: 0
    runAsGroup: 0
    # Run the container as root user (UID 0)
    runAsNonRoot: false  # Remove this restriction, as we want to run as root
    privileged: true  # Enable privileged mode if required
    readOnlyRootFilesystem: false  # Ensure the root filesystem is writable so you can modify files
    allowPrivilegeEscalation: true
    capabilities:
      drop: [ "ALL" ]  # You can drop unneeded capabilities for security
    seccompProfile:
      type: "RuntimeDefault"
```

in this case, I add the cert to the keystore but it works not correctly, cause the user is different and I get such errors: "
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/api/v1/namespaces/scdf/pods/scdf-spring-cloud-dataflow-server-74b49d7795-46st9. Message: pods "scdf-spring-cloud-dataflow-server-74b49d7795-46st9" is forbidden: User "system:anonymous" cannot get resource "pods" in API group "" in the namespace "scdf". Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=null, kind=pods, name=scdf-spring-cloud-dataflow-server-74b49d7795-46st9, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=pods "scdf-spring-cloud-dataflow-server-74b49d7795-46st9" is forbidden: User "system:anonymous" cannot get resource "pods" in API group "" in the namespace "scdf", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={})."

I also tried it via initContainer (to add the cert), also permission denied.

Question: how can I safely add the certificate to jre, no matter what the way is? Either it's change the user to root (then what should I change to not have the errors?) or initEntities, or manual adding?
