### ISSUE TITLE
[bitnami/thanos] Excessive egress data 

### ISSUE THREAD

**Issue by FranAguiar** [bitnami/charts#29331]
### Name and Version

bitnami/thanos 15.4.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I was running 12.23.2 back in May, I updated it to 15.4.3. Everything seemed to work as always so I assumed it was all ok. Months later I realized that the egress data for the buckets in GCP was really high, started digging and finally figured it out, it was after the Thanos helm chart update.

I tried the latest version of the chart to check if it was a bug already fixed but I got the same result. When I compare the values between versions I see that the newest versions have a network policy with several options, I tried to deny egress data from Thanos, but then Thanos just stopped working.

It is a bug or just a misconfiguration on my side?

### Are you using any custom parameters or values?
```yaml
query.enabled: true
queryFrontend.enabled: false
storegateway.enabled: true
compactor.enabled: true
query.serviceGrpc.type: LoadBalancer
query.serviceGrpc.loadBalancerIP: x.x.x.x
existingObjstoreSecret: mySecret
image.registry: myReg
query.serviceGrpcannotations:
      cloud.google.com/load-balancer-type: "false"
```
### What is the expected behavior?

Less egress data.

### What do you see instead?

Excessive egress data and so many requests to storage.googleapis.com in Microsoft sentinel than before the update.

### Additional information

The screenshots attached show how the egress data drops after rollback the chart version
![Screenshot 2024-09-10 at 14 42 12](https://github.com/user-attachments/assets/1d94c76c-b1d0-4bac-8e67-a9aba0cc195a)
![Screenshot 2024-09-10 at 14 42 26](https://github.com/user-attachments/assets/c33789cc-9f7e-4b70-b0d3-32802e6c6d59)
