### ISSUE TITLE
[bitnami/minio] MinIO chart generating invalid networkPolicy when using extraIngress parameter

### ISSUE THREAD

**Issue by bartramakers** [bitnami/charts#29337]
### Name and Version

bitnami/minio 14.7.7

### What architecture are you using?

None

### What steps will reproduce the bug?

Use the minio chart with the following configuration in values.yaml

### Are you using any custom parameters or values?

```yaml
networkPolicy:
    enabled: true
    allowExternal: false
    allowExternalEgress: false
    extraIngress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: redacted1
    - from:
      - namespaceSelector:
          matchLabels:
            name: redacted2
```

### What is the expected behavior?

To have it create a NetworkPolicy with an ingress parameter like follows;

```yaml
ingress:
    # Allow inbound connections
    - ports:
        - port: 9001
        - port: 9000
      from:
        - podSelector:
            matchLabels:
              redacted-minio-client: "true"
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: redacted
              app.kubernetes.io/name: minio
    - from:
      - namespaceSelector:
          matchLabels:
            name: redacted1
    - from:
      - namespaceSelector:
          matchLabels:
            name: redacted2
```

### What do you see instead?

Instead, the extraIngress contents are included at the expected place, but also after the first entry for the `from` parameter:

```yaml
  ingress:
    # Allow inbound connections
    - ports:
        - port: 9001
        - port: 9000
      from:
        - podSelector:
            matchLabels:
              redacted-minio-client: "true"
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: redacted
              app.kubernetes.io/name: minio
        - from:
          - namespaceSelector:
              matchLabels:
                name: redacted1
        - from:
          - namespaceSelector:
              matchLabels:
                name: redacted2
    - from:
      - namespaceSelector:
          matchLabels:
            name: redacted1
    - from:
      - namespaceSelector:
          matchLabels:
            name: redacted2
```

### Additional information

Resulting in the following error on install:

```
W0910 16:29:17.937731  110795 warnings.go:70] unknown field "spec.ingress[0].from[2].from"
W0910 16:29:17.937753  110795 warnings.go:70] unknown field "spec.ingress[0].from[3].from"
```
