### ISSUE TITLE
[bitnami/postgresql] helm dependency

### ISSUE THREAD

**Issue by sallydeh** [bitnami/charts#29363]
### Name and Version

postgresql-12.1.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have added this to my helm chart dependencies:

 ```yaml
 - name: postgresql
    version: 12.1.9
    repository: "https://charts.bitnami.com/bitnami"
    tags:
      - database
```
and I configured valuse.yaml of my application to override the username and password of the dependent helm chart as follows:
```yaml
postgresql:
  name: postgres
  databasePort: 5432
  fullnameOverride: postgres
  auth:
    username: "testuser"
    password: "testpass"

  rbac:
    create: true
```

### What do you see instead?

after installing my application using Helm, the log of postgres pod is as follows:

```
 FATAL:  password authentication failed for user "testuser"
 DETAIL:  Role "testuser" does not exist.
```
Do you know how to enable my application to use Bitnami Postgres as a dependency by setting user and password?
