### ISSUE TITLE
[bitnami/harbor] missing b64enc of REGISTRY_HTTP_SECRET in harbor-registry secret

### ISSUE THREAD

**Issue by davgia** [bitnami/charts#29372]
### Name and Version

bitnami/harbor 23.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. create a new namespace
2. create a secret named harbor-setup-registry (secret content below)
3. install harbor chart (values below)

### Are you using any custom parameters or values?

``` yaml
# existing secret
apiVersion: v1
data:
  REGISTRY_HTPASSWD: aGFyYm9yX3JlZ2lzdHJ5X3VzZXI6JDJ5JDEwJDlMNFRjMERKYkZGTUI2UmRTQ3Vuck9wVEhkd2hpZDRrdEJKbUxEMDBiWWdxa2tHT3ZsbDNt      
  REGISTRY_HTTP_SECRET: dGVzdA==
  REGISTRY_REDIS_PASSWORD: dGVzdA==
kind: Secret
metadata:
  name: harbor-setup-registry
  namespace: test-harbor
type: Opaque
```

``` yaml
# chart values
registry:
  existingSecret: harbor-setup-registry
```

### What is the expected behavior?

The helm generated `harbor-registry` secret should have REGISTRY_HTTP_SECRET value base64 encoded

### What do you see instead?

The helm generated `harbor-registry` secret has REGISTRY_HTTP_SECRET value in plaintext, which causes the chart installation to fail.

I see that the b64enc call is missing from this line:

https://github.com/bitnami/charts/blob/6d9c981f179c3c383d699b7291b616ee1fb0cb92/bitnami/harbor/templates/registry/registry-secret.yaml#L51

This is the proof:

``` yaml
# helm upgrade --install harbor bitnami/harbor --version "23.0.3" -f values.yaml -n test-harbor --dry-run=server --debug > test.yaml
# Source: harbor/templates/registry/registry-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry
  namespace: "test-harbor"
  labels:
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    app.kubernetes.io/version: 2.11.1
    helm.sh/chart: harbor-23.0.3
type: Opaque
data:
  REGISTRY_HTPASSWD: "aGFyYm9yX3JlZ2lzdHJ5X3VzZXI6JDJ5JDEwJDlMNFRjMERKYkZGTUI2UmRTQ3Vuck9wVEhkd2hpZDRrdEJKbUxEMDBiWWdxa2tHT3ZsbDNt"
  REGISTRY_HTTP_SECRET: test # <----------------------- THIS IS NOT B64 ENCODED
  REGISTRY_REDIS_PASSWORD: "dGVzdA=="
```
