### ISSUE TITLE
HPA is not working properly due to replicas set

### ISSUE THREAD

**Issue by amoon78** [bitnami/charts#29388]
### Name and Version

bitnami/apache 11.2.17

### What architecture are you using?

arm64

### What steps will reproduce the bug?

When autoscaling is enabled to use HPA to rescale the pod per target setting, the pod doesn't rescale by HPA setting since `spec.replicas` is in deploy. (https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#migrating-deployments-and-statefulsets-to-horizontal-autoscaling)
https://github.com/bitnami/charts/blob/main/bitnami/apache/templates/deployment.yaml#L19 
Can we have a condition for the replica setting in the template? like, 
```yaml
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
```

And, regarding this issue (https://github.com/kubernetes/kubernetes/issues/74099) in the HPA controller, is it possible to switch the resource order in https://github.com/bitnami/charts/blob/main/bitnami/apache/templates/hpa.yaml#L24-L47

### What is the expected behavior?

* have a condition in `spec.replicas` for only autoscaling disable (https://github.com/bitnami/charts/blob/main/bitnami/apache/templates/deployment.yaml#L19 ) 
```yaml
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
```

* reorder resource type in hpa template (the resource order in https://github.com/bitnami/charts/blob/main/bitnami/apache/templates/hpa.yaml#L24-L47) 
```yaml
  metrics:
    {{- if .Values.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.autoscaling.targetMemory }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemory }}
        {{- end }}
    {{- end }}
    {{- if .Values.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.autoscaling.targetCPU }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPU }}
        {{- end }}
    {{- end }}
```

### What do you see instead?

* `spec.replicas` is always seen in deploying even hpa is enabled. 
* The HPA controller keeps trying to reorder the `spec.metrics` list
