### ISSUE TITLE
[bitnami/fluent-bit] Add yaml configuration in values and make it as a default configuration parameters

### ISSUE THREAD

**Issue by zhekazuev** [bitnami/charts#29399]
### Name and Version

bitnami/fluent-bit 2.3.18

### What is the problem this feature will solve?

Currently, Fluent Bit [supports two configuration formats](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit):
- [Classic mode](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/format-schema) - conf file
- [Yaml mode](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/yaml/configuration-file) - yaml configuration file

[Yaml configuration feature production ready sinse Fluent Bit 2.0](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/yaml), but it is not presented in Helm Chart.

### What is the feature you are proposing to solve the problem?

- add value, e.g. `config.yaml: {}` or `configirutation: {}` to `values.yaml` and mark it as an upstream
- add helper that will check if new configuration in `yaml` format is not empty and if not - use it instead of current `classic` format

### What alternatives have you considered?

- use existingConfigMap and some extra parameters to enforse app to use yaml config instead of classic config.

**Comment by zhekazuev** [comment]
Re-activate.

**Comment by migruiz4** [comment]
Hi @zhekazuev,

Thank you for your feature request.

The main issue is that the `bitnami/fluent-bit` is designed around configuration pieces defined in the `values.yaml`, then rendered into the `fluent-bit.conf` in the chart configmap:
https://github.com/bitnami/charts/blob/bfe0ca8fb6f797abb231e20ffeb94ea722ded27c/bitnami/fluent-bit/templates/configmap.yaml#L20-L24

That configuration file is then mounted as a volume and ingested by the bitnami/fluent-bit in its init command:
https://github.com/bitnami/containers/blob/62247b1d3102d3d5799d862c44a80b05baad4e15/bitnami/fluent-bit/3/debian-12/Dockerfile#L58

Because of that, it would not be possible to support **both** configuration methods simultaneously. 
In any case, we could drop support for the classic configuration mode and refactor the chart to use yaml settings.
The most we could do to support the other method would be a variable where the user must provide the entire configuration manually.

If you would like to use yaml configuration with the currently chart, it would be possible by following these steps:

- Build your own yaml configuration and create your confimap.
- Mount your configmap into the pods using `extraVolumes` and `extraVolumeMounts`.
- Override the container command using the `args` and/or `command` values.

**Comment by zhekazuev** [comment]
> Hi @zhekazuev,

Hi @migruiz4,

So, from my point of view we need:
- refactor entrypoint and cmd in Dockerfile - with `.sh` scripts like Bitnami used to do it in many other containers
- add new values for yaml config
- refactor helm chart helpers - with new upstream config
- update templates a bit - add some envs and update volume/volumeMount parameters

> That configuration file is then mounted as a volume and ingested by the `bitnami/fluent-bit` in its init command: https://github.com/bitnami/containers/blob/62247b1d3102d3d5799d862c44a80b05baad4e15/bitnami/fluent-bit/3/debian-12/Dockerfile#L58

What if we will use environment variable for passing config file in docker,  e.g.:

```dockerfile
ENV APP_VERSION="3.1.9" \
    BITNAMI_APP_NAME="fluent-bit" \
    PATH="/opt/bitnami/fluent-bit/bin:$PATH" \
    BITNAMI_FLUENT_BIT_CONFIG_FILE="/opt/bitnami/fluent-bit/conf/fluent-bit.conf"
...
ENTRYPOINT [ "/opt/bitnami/scripts/fluent-bit/entrypoint.sh" ]
CMD [ "/opt/bitnami/scripts/fluent-bit/run.sh" ]
```

As I can see, there are many Bitnami containers that uses that pattern - I just copied that from `mariadb-galera`.

> The main issue is that the `bitnami/fluent-bit` is designed around configuration pieces defined in the `values.yaml`, then rendered into the `fluent-bit.conf` in the chart configmap:
> 
> https://github.com/bitnami/charts/blob/bfe0ca8fb6f797abb231e20ffeb94ea722ded27c/bitnami/fluent-bit/templates/configmap.yaml#L20-L24

And then we will redefine this env and mounts if upstream `configuration: {}` in values not empty, e.g. `deployment.yaml` I think about:

```yaml
Example from external-dns: https://github.com/bitnami/charts/blob/bfe0ca8fb6f797abb231e20ffeb94ea722ded27c/bitnami/external-dns/templates/deployment.yaml#L388

kind: Deployment
metadata:
  name:  {{ include "fluent-bit.fullname" . }}
spec:
  template:
    spec:
      containers:
        - name: fluent-bit
          env:
            {{- if .Values.configuration }}
            - name: BITNAMI_FLUENT_BIT_CONFIG_FILE
              value: /opt/bitnami/fluent-bit/conf/fluent-bit.yaml
            {{- end }}
          volumeMounts:
            - name: config
            {{- if .Values.configuration }}
              mountPath: opt/bitnami/fluent-bit/conf/fluent-bit.yaml
              subPath: fluent-bit.yaml
             ...
            {{- end }}
      ...
      volumes:
        - name: empty-dir
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "fluent-bit.configuration.configMap" . }}
```

Here we don't need to do that than - I think better to not to do it:
> Override the container command using the args and/or command values.

And ConfigMap with upstream configuration:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluent-bit.configuration.configMap" . }}
data:
  {{- if  .Values.configuration }}
  custom_parsers.yaml: |
    {{- include "common.tplvalues.render" ( dict "value" .Values.configuration.customParsers "context" $ ) | nindent 4 }}
  fluent-bit.yaml: |
    {{- include "common.tplvalues.render" ( dict "value" .Values.configuration.service "context" $ ) | nindent 4 }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.configuration.inputs "context" $ ) | nindent 4 }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.configuration.filters "context" $ ) | nindent 4 }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.configuration.outputs "context" $ ) | nindent 4 }}
...
{{- end -}}
```

So, it's a draft and I think it's possible to do it more DRY than I did.

> Because of that, it would not be possible to support **both** configuration methods simultaneously. In any case, we could drop support for the classic configuration mode and refactor the chart to use yaml settings. The most we could do to support the other method would be a variable where the user must provide the entire configuration manually.

At the end, from my point of view it's possible to do that, but if we are going to create a new chart or release new MAJOR version with yaml settings, then there is no sense to implement changes I mentoined higher.

Tell me what do you think about all that and thanks for you last response.
