### ISSUE TITLE
[bitnami/discourse] Allow specifying GeoIP license keys in values

### ISSUE THREAD

**Issue by reknih** [bitnami/charts#29391]
### Name and Version

bitnami/discourse 14.1.3

### What is the problem this feature will solve?

When booting up, Discourse emits the following warning:

```
Please set DISCOURSE_MAXMIND_ACCOUNT_ID and DISCOURSE_MAXMIND_LICENSE_KEY. See https://meta.discourse.org/t/configure-maxmind-for-reverse-ip-lookups/173941 for more details.
```

Without current GeoIP databases, some moderation features of the Discourse forum are degraded.

### What is the feature you are proposing to solve the problem?

Add a value to the chart that allows setting this. This could look as follows:

```yaml
discourse:
  geoip:
    accountId: string # Goes into main config map
    licenseKey: string # Goes into main secret
```

### What alternatives have you considered?

I have tried using `discourse.extraEnvVarsSecret` to supply these values myself. This had no effect, likely because the underlying Docker image (`bitnami/discourse:3.3.1-debian-12-r3`) does not propagate these environment variables to the application.
