### ISSUE TITLE
[bitnami/elasticsearch] pod auto updates on some charts

### ISSUE THREAD

**Issue by maipal-c** [bitnami/charts#29406]
### Name and Version

bitnami/elasticsearch:21.3.12, bitnami/apisix3.2.5, bitnami/harbor:22.0.12

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. install bitnami/argocd chart on k8s cluster
2.  use the following config - 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: elasticsearch
   namespace: gitops
spec:
   project: default
   destination:
      server: https://kubernetes.default.svc
      namespace: databases
   sources:
      - repoURL: "registry-1.docker.io/bitnamicharts"
        targetRevision: 21.3.13
        path: elasticsearch
        chart: elasticsearch
        helm:
           valueFiles:
              - $rootDir/<values_yaml_file_path>
      - repoURL: "<values_yaml_file_repo"
        targetRevision: main
        ref: rootDir
   syncPolicy:
      automated:
         prune: true
         selfHeal: true
      syncOptions:
         - CreateNamespace=true
```

i am not sure how to check diff for statefull set

3. this same issue presents on few other charts from bitnami -
     - bitnami/apisix3.2.5 (creates new replicaset for all apisix deployments on any argo Application update)
     - bitnami/harbor:22.0.12 (creates new replicasets only for core & job deployments for the same)

### What is the expected behavior?

should not update or create new replicas without any secret or config change

I am not sure if its. a bug or a feature by chart it self. or maybe bug from argocd

i have few other charts from bitnami (postgresql-ha, kafka, vault & redis-cluster) which doesn't show this behavior

### What do you see instead?

4. when i investigated the main diff between new and old replicast. [difference here](https://www.textcompare.org?id=66e5515058847462b1dd22e8)

5. in case above link not working - 
    - pod template hash label has diff
    - checksum/secret annotation has diff

6. this happened when i updated tolerations for aws-ebs-csi-driver (another argocd Application on same cluster), all these above 3 Apps also got updated.
