### ISSUE TITLE
Redis with tls and tls.authClients=false should *not* send client certificates in probes

### ISSUE THREAD

**Issue by thomas-riccardi** [bitnami/charts#2940]
**Which chart**:
redis (possibly the redis-cluster too)

**Describe the bug**
With `tls.enabled=true` and `tls.authClients=false`, the healthcheck/readiness probes still use client certificates when communicating with the redis server.

This is an issue when the client certificate is not OK from the server point of view (which is frequent I suppose when we disable the authClients). Meaning probes fail, and the redis service never works.

(with `tls.authClients=false` redis does not mandate client cert, but when receives one it validates it and reject the connection if it's invalid)

**To Reproduce**
1. create redis release with `tls.enabled=true` and `tls.authClients=false`
2. use certificates that won't be accepted by redis server itself (when used by clients)
3. see probes failing and redis Service never working

Somehow in my case client certificate sent by the probe doesn't work:
- server logs `1:M 25 Jun 2020 12:55:16.247 # Error accepting a client connection: error:1417C086:SSL routines:tls_process_client_certificate:certificate verify failed` in logs, no more info with `loglevel debug`, but that's an upstream redis issue..)
- server closes connexion
debugging with `openssl s_client -connect localhost:6379 -state -CAfile ca.crt -cert tls.crt -key tls.key`:
```
SSL3 alert read:fatal:unsupported certificate
140155281985984:error:14094413:SSL routines:ssl3_read_bytes:sslv3 alert unsupported certificate:../ssl/record/rec_layer_s3.c:1528:SSL alert number 43
```

(Also, the probe fails with a strange message: `Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.`, it seems https://github.com/bitnami/charts/blob/8f49e5254b590eb262332110e58b6925b9da8e84/bitnami/redis/templates/health-configmap.yaml#L19 should be changed to apply also for redis 6)

**Expected behavior**
Redis with `tls.enabled=true` and `tls.authClients=false` should *not* send client certificates in probes.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-13T02:33:08Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

<details><summary>click here for more details on how I got certificates with cert-manager rejected by redis-server when used as client certificates</summary>
<p>

I use https://cert-manager.io/ (v0.13.1) to:
- first create a selfsigned Issuer
- used to generate a Certificate `ca-root` (with `isCA: true`)
- used to bootstrap a `ca` Issuer
- and finally create a Certificate `redis` from the `ca` Issuer, which creates a `redis-tls` tls Secret that I pass to redis helm chart via `tls.certificatesSecret`.

I don't understand why redis-server rejects the client certificate (probe fail, redis-server logs `certificate verify failed`):
testing certificates with `openssl s_server` and `openssl s_client` works great:
```
# first, verify what `cert-manager` created is valid:
$ openssl verify -verbose -CAfile ca.crt tls.crt
tls.crt: OK

# then test client certificate validation: it works
$ openssl s_server -accept 12345 -CAfile ca.crt -cert tls.crt -key tls.key -Verify 1 -state
$ openssl s_client -connect localhost:12345 -state -CAfile ca.crt -key tls.key

# testing redis-server with openssl s_client only:
$ openssl s_client -connect localhost:6379 -state -CAfile ca.crt -cert tls.crt -key tls.key 
...
SSL3 alert read:fatal:unsupported certificate
139796952641984:error:14094413:SSL routines:ssl3_read_bytes:sslv3 alert unsupported certificate:../ssl/record/rec_layer_s3.c:1528:SSL alert number 43
```

`cert-manager` scenario:
```yaml
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ca-root
spec:
  secretName: ca-key-pair
  isCA: true
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  commonName: local-selfsigned-root-ca
  organization:
  - Foo

---

apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: ca
spec:
  ca:
    secretName: ca-key-pair

---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: redis
spec:
  secretName: redis-tls
  issuerRef:
    name: ca
    kind: ClusterIssuer
  commonName: redis
  organization:
  - Foo
```

install redis 10.7.5 helm release named `redis`(same as commonName, service name)
`values.yaml`:
```yaml
tls:
  enabled: true
  authClients: false
  certificatesSecret: redis-tls
  certFilename: tls.crt
  certKeyFilename: tls.key
  certCAFilename: ca.crt
```

I just tried adding `client auth` to `usages` in the cert-manager Certificate, it didn't change anything.
```
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
```
Maybe it fails around verifying common name? or some other field?
</p>
</details>
