### ISSUE TITLE
Unable to disable persistence for redis

### ISSUE THREAD

**Issue by tpoxa** [bitnami/charts#2944]
**Which chart**:
redis

**Describe the bug**

I am trying to use Redis chart as a dependency. I really need the simplest redis running without persistence.

Here are my values.yaml

```
redis:
  persistence:
    enabled: false
  slave:
    persistence:
      enabled: false
  master:
    persistence:
      enable: false
  usePassword: false
  cluster:
    enabled: false
```

requirements.yaml

```
  - name: redis
    version: 10.7.5
    repository: https://charts.bitnami.com/bitnami

```

**To Reproduce**
Create empty helm chart
Add lines above to requirements
Add lines to values.yaml

**Expected behavior**
No pvc templates for stateful set

Instead, I see next
```
redis-data-project-name-redis-master-0                                 Pending                         
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Any ideas on how to disable persistence?

Thanks in advance.
