### ISSUE TITLE
[bitnami/kube-prometheus] generates invalid spec yaml if there is imagePullSecrets

### ISSUE THREAD

**Issue by rajeevnaikte** [bitnami/charts#29459]
### Name and Version

bitnami/kube-prometheus 8.6.0

### What architecture are you using?

None

### What steps will reproduce the bug?

- Include custom `imagePullSecrets` in values.yaml
e.g. 
```
imagePullSecrets:
  - name: mysecret
```

- run `helm install` or helm template`

### Are you using any custom parameters or values?

```
imagePullSecrets:
  - name: mysecret
```

### What is the expected behavior?

Generates valid k8s spec yaml

### What do you see instead?

Invalid k8s spec yaml (as seen from output of `helm template`)

```
apiVersion: monitoring.coreos.com/v1
  kind: Prometheus
  spec:
    additionalScrapeConfigs:
      name: additional-scrape-jobs-local-kube-prometheus-prometheus
      key: scrape-jobs.yaml  imagePullSecrets:
      - name: mysecret
```

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-kube-prometheus-operator
automountServiceAccountToken: trueimagePullSecrets:
  - name: mysecret
```
