### ISSUE TITLE
[bitnami/thanos] Thanos ruler don't support TLS on grpc

### ISSUE THREAD

**Issue by mcantinqc** [bitnami/charts#29458]
### Name and Version

thanos 0.36.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The querier can be configured to use TLS for GRPC client connections by adding the following configuration:

```
query:
  enabled: true
  grpc:
    client:
      tls:
        enabled: true
        autoGenerated: true
```

This configuration forces the querier to use TLS when calling GRPC endpoints.
However, there is currently no way to activate a similar TLS configuration for the ruler component.
For comparison, the storegateway component allows TLS configuration for its GRPC server using the following settings:

```
storegateway:
  enabled: true
  grpc:
    server:
      tls:
        enabled: true
        autoGenerated: true
```

The issue is that we need a way to enable TLS for GRPC connections on the ruler component, similar to how it's implemented for the querier and storegateway.

### What is the expected behavior?

GRPC TLS setup for ruler like for storegateway.

### What do you see instead?

> dialing connection: context deadline exceeded: connection error: desc = \"transport: authentication handshake failed: tls: first record does not look like a TLS handshake

### Additional information

Arguments like grpc-server-tls-cert, grpc-server-tls-client-ca and grpc-server-tls-key are fully supported by Thanos ruler : https://thanos.io/tip/components/rule.md/#flags.
