### ISSUE TITLE
[bitnami/redis] json schema too strict for any template-able value

### ISSUE THREAD

**Issue by piccit** [bitnami/charts#29451]
### Name and Version

bitnami/redis 20.0.4

### What architecture are you using?

None

### What steps will reproduce the bug?

1.  Set `.Values.commonLabels` to a string (containing Helm templating, for example)
2. Run `helm template .`
3. Observe error due to JSON schema validation

### Are you using any custom parameters or values?

```yaml
commonLabels: |
  app: {{ include "common.names.name" $ }}
  {{- with .Chart.AppVersion }}
  version: {{ . | quote }}
  {{- end -}}
```

### What is the expected behavior?

Strings should be allowed as this value is passed to `common.tplvalues.render`

### What do you see instead?

```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
redis:
- commonLabels: Invalid type. Expected: object, given: string
```

### Additional information

Per related issue #27319 and PR #27441, values that are templated should either be removed from the schema or correctly allow both objects and strings
