### ISSUE TITLE
PostgreSQL reports could not receive data from client: Connection reset by peer

### ISSUE THREAD

**Issue by ruinshe** [bitnami/charts#29490]
### Name and Version

bitnami/postgresql 15.5.20

### What architecture are you using?

amd64

### What steps will reproduce the bug?

After the PosgreSQL server started, the log shown about every 500ms.

```log
2024-09-18 03:53:21.920 GMT [2573] LOG:  could not receive data from client: Connection reset by peer
```

### Are you using any custom parameters or values?

```yaml
image:
  tag: 16.3.0-debian-12-r21

auth:
  enablePostgresUser: true
  existingSecret: postgresql-cluster-secrets

replication:
  synchronousCommit: off

architecture: standalone
primary:
  pgHbaConfiguration: |-
    local all all trust
    host all all localhost trust
    host replication repl_user all md5
    host all all all md5
  service:
    type: LoadBalancer
```

### What do you see instead?

The server should not report any error after started.

### Additional information

I setup this instance as other PostgreSQL instance's master, and all things go well but the log printed into the console again and again.
