### ISSUE TITLE
[mimir] uploading new block to long-term storage failed <...> mkdir /opt/bitnami/grafana-mimir/blocks: read-only file system

### ISSUE THREAD

**Issue by netikras** [bitnami/charts#29543]
### Name and Version

bitnami/mimir

### What architecture are you using?

amd64

### What steps will reproduce the bug?

IDK if these will repro the bug, but I have configured the chart to be using filesystem for storage with quite generous numbers under the .persistence.size value.

For some reason, after running for over a day, my ingesters are flooding their logs with

```
<...>
ts=2024-09-19T20:25:13.511130729Z caller=shipper.go:162 level=error user=anonymous msg="uploading new block to long-term storage failed" block=01J85KM2E89TSCTA8WNH9TJ9WY err="upload chunks: upload file /bitnami/grafana-mimir/tsdb/anonymous/01J85KM2E89TSCTA8WNH9TJ9WY/chunks/000001 as 01J85KM2E89TSCTA8WNH9TJ9WY/chunks/000001: mkdir /opt/bitnami/grafana-mimir/blocks: read-only file system"
ts=2024-09-19T20:25:13.511152569Z caller=shipper.go:158 level=info user=anonymous msg="uploading new block to long-term storage" block=01J85TFSP7AH4FFTTEHWQATKHY
ts=2024-09-19T20:25:13.511524316Z caller=shipper.go:162 level=error user=anonymous msg="uploading new block to long-term storage failed" block=01J85TFSP7AH4FFTTEHWQATKHY err="upload chunks: upload file /bitnami/grafana-mimir/tsdb/anonymous/01J85TFSP7AH4FFTTEHWQATKHY/chunks/000001 as 01J85TFSP7AH4FFTTEHWQATKHY/chunks/000001: mkdir /opt/bitnami/grafana-mimir/blocks: read-only file system"
```

store-gateway also has similar errors in its log:

```
kubectl  -n mimir logs mimir-grafana-mimir-store-gateway-0 | tail
ts=2024-09-19T20:26:52.27818486Z caller=seed.go:87 level=info msg="creating cluster seed file" cluster_id=1aa97f6c-fef3-49b2-a295-2f850fb3e117
ts=2024-09-19T20:26:52.278366148Z caller=seed.go:90 level=warn msg="failed to create cluster seed file" err="mkdir /opt/bitnami/grafana-mimir/blocks: read-only file system"
ts=2024-09-19T20:27:23.94882102Z caller=gateway.go:322 level=info msg="synchronizing TSDB blocks for all users" reason=periodic
ts=2024-09-19T20:27:23.952561681Z caller=gateway.go:328 level=info msg="successfully synchronized TSDB blocks for all users" reason=periodic
ts=2024-09-19T20:32:24.316487513Z caller=seed.go:87 level=info msg="creating cluster seed file" cluster_id=e9196cd6-ffc1-4881-9ac4-292f72b26d0b
ts=2024-09-19T20:32:24.316602862Z caller=seed.go:90 level=warn msg="failed to create cluster seed file" err="mkdir /opt/bitnami/grafana-mimir/blocks: read-only file system"
ts=2024-09-19T20:36:52.423271091Z caller=seed.go:87 level=info msg="creating cluster seed file" cluster_id=14aceb17-b226-4067-9b83-2e6f9b99b97c
ts=2024-09-19T20:36:52.42340828Z caller=seed.go:90 level=warn msg="failed to create cluster seed file" err="mkdir /opt/bitnami/grafana-mimir/blocks: read-only file system"
ts=2024-09-19T20:40:45.082410341Z caller=seed.go:87 level=info msg="creating cluster seed file" cluster_id=1d748580-9772-4072-9be3-62497bff9504
ts=2024-09-19T20:40:45.0825194Z caller=seed.go:90 level=warn msg="failed to create cluster seed file" err="mkdir /opt/bitnami/grafana-mimir/blocks: read-only file system"
```

the ingester's process looks like this

```
1001           1       0 10 19:50 ?        00:04:07 mimir -target=ingester -config.expand-env=true -config.file=/bitnami/grafana-mimir/conf/mimir.yaml -ingester.max-global-series-per-user=30000000 -distributor.ingestion-rate-limit=1000000 -distributor.ingestion-burst-size=5000000
```

and I see that its CWD is under /opt
```
I have no name!@mimir-grafana-mimir-ingester-1:/opt/bitnami/grafana-mimir$ ls -l /proc/1/cwd
lrwxrwxrwx. 1 1001 1001 0 Sep 19 20:08 /proc/1/cwd -> /opt/bitnami/grafana-mimir
```

So my question is: why does mimir try to archive blocks into CWD rather than the dedicated filesystem...?

```
I have no name!@mimir-grafana-mimir-ingester-1:/opt/bitnami/grafana-mimir$ df -hPT
Filesystem                                Type     Size  Used Avail Use% Mounted on
overlay                                   overlay  226G  7.6G  209G   4% /
tmpfs                                     tmpfs     64M     0   64M   0% /dev
/dev/sda1                                 ext4     226G  7.6G  209G   4% /tmp
/dev/disk/by-id/scsi-0HC_Volume_101316588 ext4     295G  7.1G  288G   3% /bitnami/grafana-mimir
shm                                       tmpfs     64M     0   64M   0% /dev/shm
tmpfs                                     tmpfs     16G     0   16G   0% /proc/acpi
tmpfs                                     tmpfs     16G     0   16G   0% /proc/scsi
tmpfs                                     tmpfs     16G     0   16G   0% /sys/firmware
I have no name!@mimir-grafana-mimir-ingester-1:/opt/bitnami/grafana-mimir$ 
```

config:

```yaml
I have no name!@mimir-grafana-mimir-ingester-1:/opt/bitnami/grafana-mimir$ cat /bitnami/grafana-mimir/conf/mimir.yaml
activity_tracker:
  filepath: /bitnami/grafana-mimir/activity.log
alertmanager_storage:
  backend: s3
  s3: {}
api:
  alertmanager_http_prefix: /alertmanager
  prometheus_http_prefix: /prometheus
blocks_storage:
  backend: filesystem
  bucket_store:
    chunks_cache:
      backend: memcached
      memcached:
        addresses: mimir-memcachedchunks:11211
        timeout: 450ms
    index_cache:
      backend: memcached
      memcached:
        addresses: mimir-memcachedindex:11211
        timeout: 450ms
    metadata_cache:
      backend: memcached
      memcached:
        addresses: mimir-memcachedmetadata:11211
        timeout: 450ms
    sync_dir: /bitnami/grafana-mimir/tsdb-sync
  filesystem: null
  tsdb:
    dir: /bitnami/grafana-mimir/tsdb
compactor:
  data_dir: /bitnami/grafana-mimir/compactor
frontend:
  cache_results: true
  parallelize_shardable_queries: true
  results_cache:
    backend: memcached
    memcached:
      addresses: mimir-memcachedfrontend:11211
      timeout: 500ms
frontend_worker:
  frontend_address: mimir-grafana-mimir-query-frontend-headless.mimir.svc:9095
  grpc_client_config:
    max_send_msg_size: 419430400
ingester:
  ring:
    final_sleep: 0s
    num_tokens: 512
    tokens_file_path: /bitnami/grafana-mimir/tokens
    unregister_on_shutdown: false
ingester_client:
  grpc_client_config:
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
limits:
  max_cache_freshness: 10m
  max_query_parallelism: 240
  max_total_query_length: 12000h
memberlist:
  abort_if_cluster_join_fails: false
  advertise_port: 7946
  bind_port: 7946
  compression_enabled: false
  join_members:
  - dns+mimir-grafana-mimir-gossip-ring.mimir.svc.cluster.local:7946
querier:
  max_concurrent: 16
query_scheduler:
  max_outstanding_requests_per_tenant: 800
server:
  grpc_listen_port: 9095
  grpc_server_max_concurrent_streams: 1000
  grpc_server_max_connection_age: 2m
  grpc_server_max_connection_age_grace: 5m
  grpc_server_max_connection_idle: 1m
  http_listen_port: 8080
store_gateway:
  sharding_ring:
    tokens_file_path: /bitnami/grafana-mimir/tokens
    wait_stability_min_duration: 1m
usage_stats:
  installation_mode: helm
```

### Are you using any custom parameters or values?

terraform template

```yaml
mimir:
  blockStorage:
    backend: ${storage.type}
    config:
      #      %{~ if storage.type == "filesystem" ~}

      #      %{~ endif ~}

      #      %{~ if storage.type == "s3" ~}
      access_key_id: ${storage.s3.access_key.id}
      secret_access_key: ${storage.s3.access_key.secret}

      region: ${storage.s3.region}
      bucket_name: ${storage.s3.bucket_name}
      endpoint: ${storage.s3.endpoint}
      insecure: false
#      %{~ endif ~}
serviceAccount:
  create: ${sa.create}
  name: ${sa.name}
  annotations: ${sa.annotations}
  automountServiceAccountToken: true
gateway:
  ingress:
    enabled: ${gateway.ingress.enabled}
    pathType: ImplementationSpecific
    ingressClassName: nginx
    hostname: ${gateway.ingress.domain}
    path: ${gateway.ingress.path}
    annotations: ${gateway.ingress.annotations}
    tls: false
    selfSigned: false
  auth:
    enabled: ${gateway.auth.enabled}
    username: "${gateway.auth.username}"
    password: "${gateway.auth.password}"
    existingSecret: "${gateway.auth.secret}"

ingester:
  replicas: 3
  #   resourcesPreset: large
  resources:
    requests:
      cpu: 500m
      memory: 2048Mi
    limits:
      memory: 4096Mi
  extraArgs:
    - -ingester.max-global-series-per-user=30000000
    - -distributor.ingestion-rate-limit=1000000
    - -distributor.ingestion-burst-size=5000000
  persistence:
    enabled: true
    size: ${ingester.persistence.size_g}Gi
    storageClass: ${storage.storageclass}

storeGateway:
  replicas: 2
  persistence:
    enabled: true
    size: 100Gi
    storageClass: ${storage.storageclass}

ruler:
  persistence:
    enabled: true
    storageClass: ${storage.storageclass}

compactor:
  enabled: true
  replicas: 2
  persistence:
    enabled: true
    storageClass: ${storage.storageclass}

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels: { }

minio:
  enabled: false

distributor:
  replicas: 3
  resources:
    requests:
      cpu: 200m
      memory: 1024Mi
    limits:
      memory: 2048Mi

queryFrontend:
  replicas: 2

memcached:
  enabled: true

querier:
  replicas: 2

```

### What is the expected behavior?

mimir NOT using a root filesystem to store archived blocks. Instead, using the dedicated /bitnami/grafana-mimir filesystem for this purpose

### What do you see instead?

mimir trying to archive blocks into a read-only root filesystem, i.e. mimir process' CWD.

### Additional information

It might be not a bug, it's perfectly possible I'm doing smth wrong. I need assistance to see what I'm doing wrong and how can I fix it.

**Comment by netikras** [comment]
Found the problem. Thanks to chatgpt, which hinted to look at the mimir.blockStorage.config.dir parameter I was missing. Docs helped me from there:

https://grafana.com/docs/mimir/latest/configure/configuration-parameters/#blocks_storage

The fixed snipped is:

```
mimir:
  blockStorage:
    backend: ${storage.type}
    config:
      #      %{~ if storage.type == "filesystem" }
      dir: /bitnami/grafana-mimir/blocks
      #      %{~ endif }
```

Also, removed excessive terraform newline trimming at the flow control blocks.
