### ISSUE TITLE
Ingress does not handle encoded characters (%2F) correctly for RabbitMQ management console in paths like (/queues/%2F/<any-queue>)and (/extensions/%2F/<any-extension>)

### ISSUE THREAD

**Issue by SaraAbdelhafeez** [bitnami/charts#29587]
### Name and Version

Chart Name: RabbitMQ Chart Version: 11.5.0 Helm Version: v3.15.2 Kubernetes Version: v1.27.13

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy the RabbitMQ Helm chart with the ingress configuration for path /rmq.
2. Access the RabbitMQ management console via the ingress at /rmq.
3. Navigate to the Queues tab and click on any specific queue. This generates a URL containing an encoded forward slash (%2F).
4. The browser returns a 404 error for these requests.
5. Alternatively, go to the Extensions tab and try to access any extension; this also results in a 404 error.

### Are you using any custom parameters or values?

the following ingress values are configured:

```yaml
ingress:
  enabled: true
  path: /rmq(/.*)
  pathType: ImplementationSpecific
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  extraRules:
    - http:
        paths:
        - path: /rmq/(.*)
          pathType: Prefix
          backend:
            service:
              name: rabbitmq
              port:
                number: 15672
```

### What is the expected behavior?

The RabbitMQ management console should correctly handle URLs containing encoded characters (like %2F) in the paths under the Queues tab and Extensions tab when accessed via the ingress. No 404 error should occur when accessing these tabs.

### What do you see instead?

When trying to access any queue under the Queues tab or any extension under the Extensions tab, a 404 error is returned. The URLs contain encoded forward slashes (%2F), which seem to be misinterpreted by the ingress, resulting in a 404 error. This issue does not occur when port-forwarding the RabbitMQ service directly (i.e., using kubectl port-forward on port 15672).
![image-20240820-082750](https://github.com/user-attachments/assets/b54cca29-06e9-4f91-b67c-bb1fe899d33b)

### Additional information

- Workaround: When port-forwarding the RabbitMQ service directly (using `kubectl port-forward svc/rabbitmq 15672:15672`), the URLs with %2F work as expected, and no 404 errors occur.
- Ingress Controller: Nginx ingress controller is being used.
- Nginx Version: Nginx ingress controller version v21.6.4
- The issue seems to be related to how the ingress handles encoded characters like %2F. The ingress doesn't properly pass these encoded characters through to the RabbitMQ service, leading to 404 errors.
