### ISSUE TITLE
[bitnami/redis-cluster] CrashLoopBackOff  

### ISSUE THREAD

**Issue by fonsecas72** [bitnami/charts#2959]
**Which chart**:

bitnami/redis-cluster 3.1.1

**Describe the bug**

CrashLoopBackOff of in the sts pod

Logs:

`sed: can't read /bitnami/redis/data/nodes.conf: No such file or directory`

**To Reproduce**

Basically I used the following (in GKE)

```

global:
  storageClass: standard

cluster:
  nodes: 2
  replicas: 1

podDisruptionBudget:
  minAvailable: 1

containerSecurityContext:
  fsGroup: 1001 # fixing bug in chart

volumePermissions:
  enabled: true

metrics:
  enabled: true
```

**Expected behavior**

**Version of Helm and Kubernetes**:

Helm 2.16.8
K8S 1.16.9

**Comment by mboutet** [comment]
I don't know if this is related to your problem, but you need at least 6 nodes (3 masters + 1 replica for each master, so 6 nodes total) for redis-cluster to work properly.

**Comment by fonsecas72** [comment]
Thanks. I tried it but now all of them have the error

```
NAME                                                  READY   STATUS             RESTARTS   AGE
redis-cluster-mode-k8s-cms-local-0                    1/2     CrashLoopBackOff   2          48s
redis-cluster-mode-k8s-cms-local-1                    1/2     CrashLoopBackOff   2          48s
redis-cluster-mode-k8s-cms-local-2                    1/2     CrashLoopBackOff   2          48s
redis-cluster-mode-k8s-cms-local-3                    1/2     CrashLoopBackOff   2          48s
redis-cluster-mode-k8s-cms-local-4                    1/2     Error              2          48s
redis-cluster-mode-k8s-cms-local-5                    1/2     CrashLoopBackOff   2          48s
```

error keeps

```
 20:16:30.87
 20:16:30.87 Welcome to the Bitnami redis-cluster container
 20:16:30.87 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
 20:16:30.87 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
 20:16:30.87
 20:16:30.87 INFO  ==> ** Starting Redis setup **
 20:16:30.89 INFO  ==> Initializing Redis...
Changing old IP xxx  by the new one xxxx
sed: can't read /bitnami/redis/data/nodes.conf: No such file or directory
```

**Comment by mboutet** [comment]
Did the cluster creation job run?

**Comment by fonsecas72** [comment]
no, seems not. It didn't even created it. 

Can it be because with `"helm.sh/hook": post-install,post-upgrade"`  it will only be executed on a successful installation ?

**Comment by mboutet** [comment]
If you have the `--wait` flag while installing, helm will wait for all the pod to be ready before running the hook. However, my guess is you have a volume permission issue. Is your storage class a disk or is it some kind of SMB/NFS?

**Comment by fonsecas72** [comment]
ok, seems I had a typo in resources (I'm required to set resources). Now I see the job, but it's in infinite loop 

I'm using GKE with standard volumes

```
redis-data-testing-redis-cluster-0                   Bound    pvc-c6ebea3a-dd50-46e1-a592-08b444abd87d   8Gi        RWO            standard       7m28s
redis-data-testing-redis-cluster-1                   Bound    pvc-5fd1ccb8-8c3b-45e2-b889-b55608931453   8Gi        RWO            standard       7m27s
redis-data-testing-redis-cluster-2                   Bound    pvc-0bf23c8d-9fa1-4089-b43f-edaf6b52619e   8Gi        RWO            standard       7m27s
redis-data-testing-redis-cluster-3                   Bound    pvc-f012067f-ac32-4f32-9ec1-f0c096beae70   8Gi        RWO            standard       7m27s
redis-data-testing-redis-cluster-4                   Bound    pvc-1e3a71b5-b0b6-4ac8-9cb9-f613def34411   8Gi        RWO            standard       7m27s
redis-data-testing-redis-cluster-5                   Bound    pvc-4f2a1280-2ad6-4d33-8d3c-5d2476fd4a3d   8Gi        RWO            standard       7m27s
```

Regarding permissions, they seem correct 

```
ls -lah /bitnami/redis/
total 12K
drwxrwxr-x 3 root root 4.0K Jun 29 08:32 .
drwxr-xr-x 3 root root 4.0K Jun 29 08:32 ..
drwxrwsr-x 3 1001 1001 4.0K Jun 29 21:02 data
```

**Comment by mboutet** [comment]
What are the logs for the job? The job should wait for all the nodes to be ready, so if you don't have the `--wait` flag, it can take some time until all the redis nodes are ready.

**Comment by fonsecas72** [comment]
loop with

```
Could not connect to Redis at testing-redis-cluster-0.testing-redis-cluster-headless:6379: Connection refused
Node testing-redis-cluster-0.testing-redis-cluster-headless not ready, waiting for all the nodes to be ready...
Could not connect to Redis at testing-redis-cluster-0.testing-redis-cluster-headless:6379: Connection refused
Node testing-redis-cluster-0.testing-redis-cluster-headless not ready, waiting for all the nodes to be ready...
```

helm runs until it times out with 

`Error: failed post-install: timed out waiting for the condition` 

let me with the "--wait" flag

**Comment by mboutet** [comment]
Were all the redis nodes "ready" during that time?

**Comment by fonsecas72** [comment]
yes, unless something odd was going on. But I have tried many ways. I always make sure I start from clean state before every try (sts, pvc, pv, job, cm)

btw, what the "can't read /bitnami/redis/data/nodes.conf: No such file or directory" means?

there is no file there and from the code I'm not sure it was supposed to be, was it?

After looking at the docker image i see it is expecting /opt/bitnami/redis/etc/redis.conf file but then in chart we are mounting the config to /opt/bitnami/redis/etc/redis-default.conf . Don't know if any relation with /bitnami/redis/data/nodes.conf though...

but maybe I can understand better and fix it if you help understand what the error usually means

**Comment by mboutet** [comment]
I think the `nodes.conf` is created by redis itself once the cluster is initialized. In my case, it seems like it's there as soon as the container starts, even when the cluster is still not initialized by the job.

Here are my values if it helps:
```
  password: your_password
  cluster:
    nodes: 9
    replicas: 2
  persistence:
    enabled: true
    storageClass: azure-disk-premium-retain-and-wait-for-first-consumer
    size: 8Gi
  redis:
    # 768mb is the same as 768Mi
    # Make sure to allocate more memory to the container
    # than the planned memory usage for the database (125%-150%?)
    configmap: |
      maxmemory 768mb
      maxmemory-policy allkeys-lfu
    resources:
      requests:
        memory: 1280Mi
        cpu: 125m
      limits:
        memory: 1280Mi
        cpu: 125m
  initJob:
    activeDeadlineSeconds: 600
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    resources:
      limits:
        cpu: 5m
        memory: 32Mi
      requests:
        cpu: 5m
        memory: 32Mi
```
I'm using the version `3.1.3`.
