### ISSUE TITLE
[bitnami/kafka] Wrong default value of `Xmx` in context of default value of `Containers.kafka.Limits.memory`

### ISSUE THREAD

**Issue by plblueraven** [bitnami/charts#29670]
### Name and Version

bitnami/kafka 30.1.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. `helm install test oci://registry-1.docker.io/bitnamicharts/kafka`
2. `kubectl describe pod kafka test-kafka-controller-0`

Containers will be like:
```yaml
Containers:
  kafka:
    Container ID:   docker://8570a5d92b65fde6769ea833935731bc8118dc75168c6527ad851e88d82a83f0
    Image:          docker.io/bitnami/kafka:3.8.0-debian-12-r5
    Image ID:       docker-pullable://bitnami/kafka@sha256:999ba91863ef67e13c5704c3145154d0484671222dab2a603bfdeedc4a9fbad7
    Ports:          9093/TCP, 9092/TCP, 9094/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Mon, 30 Sep 2024 18:50:02 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:                750m
      ephemeral-storage:  2Gi
      memory:             768Mi
    Requests:
      cpu:                500m
      ephemeral-storage:  50Mi
      memory:             512Mi
    Liveness:             exec [pgrep -f kafka] delay=10s timeout=5s period=10s #success=1 #failure=3
    Readiness:            tcp-socket :controller delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:                      false
      KAFKA_HEAP_OPTS:                    -Xmx1024m -Xms1024m
      KAFKA_KRAFT_CLUSTER_ID:             <set to the key 'kraft-cluster-id' in secret 'test-kafka-kraft-cluster-id'>  Optional: false
      KAFKA_KRAFT_BOOTSTRAP_SCRAM_USERS:  true
      KAFKA_CLIENT_USERS:                 user1
      KAFKA_CLIENT_PASSWORDS:             <set to the key 'client-passwords' in secret 'test-kafka-user-passwords'>  Optional: false
      KAFKA_INTER_BROKER_USER:            inter_broker_user
      KAFKA_INTER_BROKER_PASSWORD:        <set to the key 'inter-broker-password' in secret 'test-kafka-user-passwords'>  Optional: false
      KAFKA_CONTROLLER_USER:              controller_user
      KAFKA_CONTROLLER_PASSWORD:          <set to the key 'controller-password' in secret 'test-kafka-user-passwords'>  Optional: false
    Mounts:
      /bitnami/kafka from data (rw)
      /opt/bitnami/kafka/config/server.properties from kafka-config (rw,path="server.properties")
      /opt/bitnami/kafka/logs from logs (rw)
      /tmp from tmp (rw)
```

### Are you using any custom parameters or values?

No

### What is the expected behavior?

`Containers.kafka.Limits.memory` should be greater than `Xmx`.

### What do you see instead?

`Xmx` is set to `1024m` and at the same time `Containers.kafka.Limits.memory` is set to `768Mi` therefore OOM Killer will get its hands dirty.

### Additional information

IMO quick fix will be to decrease default `Xmx` or increase default `Containers.kafka.Limits.memory`.
On the other hand, long term fix should consider calculating `Xmx` based on `Containers.kafka.Limits.memory` value.
