### ISSUE TITLE
[bitnami/redmine] Redmine Chart Does Not Support Installation of Plugins Requiring bundle install

### ISSUE THREAD

**Issue by Arnuzasz** [bitnami/charts#29795]
### Name and Version

bitnami/redmine 30.0.0

### What is the problem this feature will solve?

When trying to install Redmine plugins that require running bundle install, the Redmine pod enters a CrashLoopBackOff state after restarting. This makes it impossible to install plugins that require additional gem dependencies, as the gems are not persisted across pod restarts, causing Redmine to fail due to missing gems.

### What is the feature you are proposing to solve the problem?

It would be helpful if the Helm chart could better support plugin installations that require gem dependencies via bundle install. Possible solutions include:

Official Support for Gem Persistence: Provide a mechanism to persist the gems installed via bundle install across pod restarts (e.g., mounting a volume specifically for vendor/bundle).
Documentation: Update the chart documentation with guidance on how to properly install Redmine plugins that require gem installations and persist them across pod restarts.

**Comment by dgomezleon** [comment]
Hi @Arnuzasz ,

Could you give us more info about the plugin you are trying to install? Have you considered using `extraVolumes`?

**Comment by Arnuzasz** [comment]
@dgomezleon I'm trying to install https://www.redmine.org/plugins/additionals and yes I have tried using `extraVolumes` but failed to get anything out of it.

**Comment by Arnuzasz** [comment]
After further investigation, I found that this issue does not occur with the official Redmine Docker image, which lacks the `.bundle/` directory. In contrast, the Bitnami image includes a `./bundle` directory, which appears to interfere with the plugin installation process. Also official Redmine Docker image does not have `bundle` frozen mode:  
```
bundle install
Don't run Bundler as root. Installing your bundle as root will break this application for all non-root users on this machine.
Bundler 2.5.17 is running, but your lockfile was generated with 2.5.11. Installing Bundler 2.5.11 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
Fetching bundler 2.5.11
Installing bundler 2.5.11
Don't run Bundler as root. Installing your bundle as root will break this application for all non-root users on this machine.
The list of sources changed, the dependencies in your gemfile changed, the gemspecs for path gems changed, but the lockfile can't be updated because frozen mode is set

You have added to the Gemfile:
* additionals

Run `bundle install` elsewhere and add the updated Gemfile to version control.
If this is a development machine, remove the Gemfile.lock freeze by running `bundle config set frozen false`.
```  This probably leads to failures when Redmine attempts to boot after plugins requiring additional gems.

**Comment by dgomezleon** [comment]
Hi @Arnuzasz 

Thanks for sharing your research.

I would propose to install the gems using an `initContainer`, that should work with `extraVolumeMounts` and `extraVolumes`,  as mentioned in [this example](https://github.com/bitnami/charts/blob/main/bitnami/redmine/values.yaml#L393-L401).

I hope it helps

**Comment by Arnuzasz** [comment]
Thank you for your suggestion @dgomezleon. I’ve implemented the configuration using an `initContainer`, along with `extraVolumes` and `extraVolumeMounts` as suggested. The plugins are being installed correctly, and the gems are persisted in the mounted `gem-volume`. However, I’m still encountering issues when Redmine attempts to start and run migrations.

Here’s what I did:

```
extraVolumes:
  - name: plugin-volume
    emptyDir: {}
  - name: gem-volume
    emptyDir: {}

extraVolumeMounts:
  - name: plugin-volume
    mountPath: /opt/bitnami/redmine/plugins
  - name: gem-volume
    mountPath: /opt/bitnami/redmine/vendor/bundle

initContainers:
  - name: install-plugins
    image: bitnami/redmine:5.1.3
    command:
      - /bin/bash
      - -c
      - |
        apt-get update -y
        apt-get install -y build-essential libxml2-dev libxslt1-dev libssl-dev zlib1g-dev default-libmysqlclient-dev libpq-dev -y
        cd /opt/bitnami/redmine/plugins
        git clone -b stable https://github.com/alphanodes/additionals.git
        cd /opt/bitnami/redmine
        bundle config set frozen false
        bundle install
    volumeMounts:
      - name: plugin-volume
        mountPath: /opt/bitnami/redmine/plugins/
      - name: gem-volume
        mountPath: /opt/bitnami/redmine/vendor/bundle
```

Installed the necessary dependencies.
Cloned the `additionals` plugin.
Set `bundle config set frozen false` and ran `bundle install` successfully in the `initcontainer`.

Despite this, the Redmine pod still fails during startup, specifically when trying to run migrations, which seems to lead to a crash.

Could this issue be related to file permissions when the main container starts? I’ve ensured the gems are installed in the correct location and persisted across restarts, but it seems something else is preventing the migration process from succeeding.

Any additional suggestions on how to debug this would be greatly appreciated!

Thanks for your help.
