### ISSUE TITLE
[bitnami/airflow] LivenessProbe creating defunct process in Bitnami/Airflow :19.0.0

### ISSUE THREAD

**Issue by mavenzer** [bitnami/charts#29806]
### Name and Version

Bitnami/Airflow 19.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi All, I have deployed Airflow 2.9.3 using the bitnami helm chart version 19.0.0. We are using the standard charts and customizing the `,securityContext,fsGroup, uids, gids` according to our namespace removed the `seccompProfile`, `readOnlyRootFilesystem`(for adding external dependencies).

The current LivenessProbe in the woker pod  is generating defunct process even if there are no DAGs in our Instance. 
#### Bitnami Airflow worker pod image used:  docker.io/bitnami/airflow-worker:2.9.3-debian-12-r4

```
 # livenessProbe:
          #   failureThreshold: 6
          #   initialDelaySeconds: 180
          #   periodSeconds: 20
          #   successThreshold: 1
          #   timeoutSeconds: 5
          #   exec:
          #     command:
          #       - sh
          #       - -c
          #       - |
          #         . /opt/bitnami/airflow/venv/bin/activate && \
          #         CONNECTION_CHECK_MAX_COUNT=0 python -m celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d celery@$(hostname) 
```

The defunct process  in the process Logs: 

```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1111117777+       1  0.2  0.0 2901500 204768 ?      Ss   15:18   0:09 [celeryd: celery@bitnami-airflow-gaming-0:MainProcess] -active- (celery worker --pid /opt/bitnami/airflow/tmp/airflow-worker.pid)
1111117777+     126  0.0  0.0 1254284 145740 ?      S    15:20   0:00 gunicorn: master [gunicorn]
1111117777+     127  0.0  0.0 1254284 144984 ?      S    15:20   0:00 gunicorn: worker [gunicorn]
1111117777+     128  0.0  0.0 1254284 144988 ?      S    15:20   0:00 gunicorn: worker [gunicorn]
1111117777+     177  0.0  0.0 2902596 173700 ?      S    15:20   0:00 [celeryd: celery@bitnami-airflow-gaming-0:ForkPoolWorker-1]
1111117777+     178  0.0  0.0 2902600 173672 ?      S    15:20   0:00 [celeryd: celery@bitnami-airflow-gaming-0:ForkPoolWorker-2]
1111117777+     179  0.0  0.0 2902604 173676 ?      S    15:20   0:00 [celeryd: celery@bitnami-airflow-gaming-0:ForkPoolWorker-3]
1111117777+     180  0.0  0.0 2902608 173692 ?      S    15:20   0:00 [celeryd: celery@bitnami-airflow-gaming-0:ForkPoolWorker-4]
1111117777+     181  0.0  0.0 2902612 173692 ?      S    15:20   0:00 [celeryd: celery@bitnami-airflow-gaming-0:ForkPoolWorker-5]
1111117777+     182  0.0  0.0 2902616 173708 ?      S    15:20   0:00 [celeryd: celery@bitnami-airflow-gaming-0:ForkPoolWorker-6]
1111117777+     183  0.0  0.0 2902620 170324 ?      S    15:20   0:00 [celeryd: celery@bitnami-airflow-gaming-0:ForkPoolWorker-7]
1111117777+     184  0.0  0.0 2902624 170296 ?      S    15:20   0:00 [celeryd: celery@bitnami-airflow-gaming-0:ForkPoolWorker-8]
1111117777+     185  0.0  0.0 2902628 170272 ?      S    15:20   0:00 [celeryd: celery@bitnami-airflow-gaming-0:ForkPoolWorker-9]
1111117777+     186  0.0  0.0 2902632 170304 ?      S    15:20   0:00 [celeryd: celery@bitnami-airflow-gaming-0:ForkPoolWorker-10]
1111117777+     187  0.0  0.0 2902636 170216 ?      S    15:20   0:00 [celeryd: celery@bitnami-airflow-gaming-0:ForkPoolWorker-11]
1111117777+     188  0.0  0.0 2902640 170296 ?      S    15:20   0:00 [celeryd: celery@bitnami-airflow-gaming-0:ForkPoolWorker-12]
1111117777+     189  0.0  0.0 2902644 170300 ?      S    15:20   0:00 [celeryd: celery@bitnami-airflow-gaming-0:ForkPoolWorker-13]
1111117777+     253  0.0  0.0   2576   928 pts/0    Ss   15:26   0:00 sh -i -c TERM=xterm sh
1111117777+     259  0.0  0.0   2576   924 pts/0    S+   15:26   0:00 sh
1111117777+     582  0.0  0.0   2576   920 pts/1    Ss   15:42   0:00 sh -i -c TERM=xterm sh
1111117777+     588  0.0  0.0   2576   944 pts/1    S+   15:42   0:00 sh
1111117777+     968  0.0  0.0      0     0 ?        Z    16:00   0:00 [python] <defunct>
1111117777+     969  0.0  0.0      0     0 ?        Z    16:03   0:00 [python] <defunct>
```

### Are you using any custom parameters or values?

customizing the `,securityContext,fsGroup, uids, gids` according to our namespace removed the `seccompProfile`, `readOnlyRootFilesystem`(for adding external dependencies).

Value.yaml 
```
## Global settings for the Bitnami Airflow Helm Chart

# Global settings
global:
  # Override Bitnami images
  imageRegistry: ""
  imagePullSecrets: []

# Common settings for all Airflow containers
common:
  securityContext:
    runAsUser: 1111117777
    runAsGroup: 1111117777
    fsGroup: 1111117777

## Scheduler settings
scheduler:
  securityContext:
    runAsUser: 1111117777
    runAsGroup: 1111117777
    fsGroup: 1111117777
  # Specify additional Airflow Scheduler container environment variables
  env: []
  # Customize the number of replicas for the Airflow Scheduler Deployment
  replicas: 1


## Worker settings
workers:
  securityContext:
    runAsUser: 1111117777
    runAsGroup: 1111117777
    fsGroup: 1111117777



## Web server settings
web:
  securityContext:
    runAsUser: 1111117777
    runAsGroup: 1111117777
    fsGroup: 1111117777


# Airflow base settings
airflow:
  # (Optional) Extra arguments to be passed to Airflow
  extraArgs: ""
  # Airflow External dependencies (install additional packages)
  extraPipPackages: []
  # Security Context settings
  securityContext:
    runAsUser: 1111117777
    runAsGroup: 1111117777
    fsGroup: 1111117777



```

### What do you see instead?

When I used the the below livenessProbe the defunct process is not there : 
```
livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 180
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - pgrep
                - -f
                - airflow-worker
```

After implementing the above Liveness Probe in the worker Pod there is no defunct process to be seem.

The defunct process are only generated at the worker pods not in the rest of the airflow components and I'm seeing liveness probe failing when I'm using the official bitnami helm chart configs for the liveness probe. 

Kubenetes version
OpenShift Container Platform 4.14

What are the disadvantages of using the above Livenessprobe in the worker pod and how to get rid of defunct process from the official bitnami charts.

**Comment by jotamartos** [comment]
I just launched the latest version of the Chart using the default configuration and saw that the process is executed properly. There is not a defunct process after executing the probe 

```
I have no name!@airflow-worker-0:/$ ps aux 
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1001           1  4.2  2.5 1372656 204296 ?      Ss   10:49   0:09 [celeryd: celery@airflow-worker-0:MainProcess] -active- (celery worker --pid /opt/bitnami/airflow/tmp/airflow-worker.pid)
1001         117  0.0  1.7 1259548 146528 ?      S    10:51   0:00 gunicorn: master [gunicorn]
1001         118  0.0  1.7 1259548 146012 ?      S    10:51   0:00 gunicorn: worker [gunicorn]
1001         119  0.0  1.7 1259548 146012 ?      S    10:51   0:00 gunicorn: worker [gunicorn]
1001         122  0.0  2.0 1373412 169128 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-1]
1001         123  0.0  2.0 1373416 169064 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-2]
1001         124  0.0  2.0 1373420 169072 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-3]
1001         125  0.0  2.0 1373424 169076 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-4]
1001         126  0.0  2.0 1373428 169080 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-5]
1001         127  0.0  2.0 1373432 169096 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-6]
1001         128  0.0  2.0 1373436 169088 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-7]
1001         129  0.0  2.0 1373440 169092 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-8]
1001         130  0.0  2.0 1373444 169104 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-9]
1001         131  0.0  2.0 1373448 169104 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-10]
1001         132  0.0  2.0 1373452 169108 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-11]
1001         133  0.0  2.0 1373456 169108 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-12]
1001         134  0.0  2.0 1373460 169112 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-13]
1001         135  0.1  2.0 1373464 169112 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-14]
1001         136  0.1  2.0 1373468 169120 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-15]
1001         137  0.0  2.0 1373472 169120 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-16]
1001         138  0.0  0.0   7196  3892 pts/0    Ss   10:52   0:00 bash
1001         193  1.4  0.0   2576   956 ?        Ss   10:53   0:00 sh -c . /opt/bitnami/airflow/venv/bin/activate && \ CONNECTION_CHECK_MAX_COUNT=0 python -m celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d celery@$(hostname) 
1001         203 97.7  1.7 1225364 141556 ?      R    10:53   0:02 python -m celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d celery@airflow-worker-0
1001         206  0.0  0.0  11040  4452 pts/0    R+   10:53   0:00 ps aux
I have no name!@airflow-worker-0:/$ ps aux 
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1001           1  4.2  2.5 1372656 204296 ?      Ss   10:49   0:09 [celeryd: celery@airflow-worker-0:MainProcess] -active- (celery worker --pid /opt/bitnami/airflow/tmp/airflow-worker.pid)
1001         117  0.0  1.7 1259548 146528 ?      S    10:51   0:00 gunicorn: master [gunicorn]
1001         118  0.0  1.7 1259548 146012 ?      S    10:51   0:00 gunicorn: worker [gunicorn]
1001         119  0.0  1.7 1259548 146012 ?      S    10:51   0:00 gunicorn: worker [gunicorn]
1001         122  0.0  2.0 1373412 169128 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-1]
1001         123  0.0  2.0 1373416 169064 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-2]
1001         124  0.0  2.0 1373420 169072 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-3]
1001         125  0.0  2.0 1373424 169076 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-4]
1001         126  0.0  2.0 1373428 169080 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-5]
1001         127  0.0  2.0 1373432 169096 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-6]
1001         128  0.0  2.0 1373436 169088 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-7]
1001         129  0.0  2.0 1373440 169092 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-8]
1001         130  0.0  2.0 1373444 169104 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-9]
1001         131  0.0  2.0 1373448 169104 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-10]
1001         132  0.0  2.0 1373452 169108 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-11]
1001         133  0.0  2.0 1373456 169108 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-12]
1001         134  0.0  2.0 1373460 169112 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-13]
1001         135  0.0  2.0 1373464 169112 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-14]
1001         136  0.1  2.0 1373468 169120 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-15]
1001         137  0.0  2.0 1373472 169120 ?      S    10:51   0:00 [celeryd: celery@airflow-worker-0:ForkPoolWorker-16]
1001         138  0.0  0.0   7196  3892 pts/0    Ss   10:52   0:00 bash
1001         207  0.0  0.0  11040  4380 pts/0    R+   10:53   0:00 ps aux
I have no name!@airflow-worker-0:/$ ps aux 
```

As you are using a custom configuration, could you please debug the changes and introduce them one by one so you find the reason of the issue? 

Thanks

**Comment by mavenzer** [comment]
Thanks a lot @jotamartos. Unfortunately, I cannot test the chart without changing the uids/gids . But do you think switching the UIDs/GIDs are causing the defunct processes?

**Comment by jotamartos** [comment]
I just did a quick test and changed the configuration but couldn't reproduce the issue 

```
diff --git a/bitnami/airflow/values.yaml b/bitnami/airflow/values.yaml
index 647d5920f7..477f3e23de 100644
--- a/bitnami/airflow/values.yaml
+++ b/bitnami/airflow/values.yaml
@@ -344,8 +344,9 @@ web:
   containerSecurityContext:
     enabled: true
     seLinuxOptions: {}
-    runAsUser: 1001
-    runAsGroup: 1001
+    runAsUser: 1111117777
+    runAsGroup: 1111117777
+    fsGroup: 1111117777
     runAsNonRoot: true
     privileged: false
     allowPrivilegeEscalation: false
@@ -679,8 +680,9 @@ scheduler:
   containerSecurityContext:
     enabled: true
     seLinuxOptions: {}
-    runAsUser: 1001
-    runAsGroup: 1001
+    runAsUser: 1111117777
+    runAsGroup: 1111117777
+    fsGroup: 1111117777
     runAsNonRoot: true
     privileged: false
     allowPrivilegeEscalation: false
@@ -1018,8 +1020,9 @@ worker:
   containerSecurityContext:
     enabled: true
     seLinuxOptions: {}
-    runAsUser: 1001
-    runAsGroup: 1001
+    runAsUser: 1111117777
+    runAsGroup: 1111117777
+    fsGroup: 1111117777
     runAsNonRoot: true
     privileged: false
     allowPrivilegeEscalation: false
@@ -1693,8 +1696,9 @@ metrics:
   containerSecurityContext:
     enabled: true
     seLinuxOptions: {}
-    runAsUser: 1001
-    runAsGroup: 1001
+    runAsUser: 1111117777
+    runAsGroup: 1111117777
+    fsGroup: 1111117777
     runAsNonRoot: true
     privileged: false
     allowPrivilegeEscalation: false

```

The process keeps working properly and no defunct process appears when running the ps command. You will need to debug this issue taking into account your changes and the infrastructure you are using. 

Thanks

**Comment by mavenzer** [comment]
I really appreciate @jotamartos  for helping me.  As there is no reproducible defunct process from your end with the custom values, I need to look into different direction to resolve the issue. 

 One question, Is there any difference  between the chart's liveliness probe i.e. 
```
 livenessProbe:
             failureThreshold: 6
             initialDelaySeconds: 180
             periodSeconds: 20
             successThreshold: 1
             timeoutSeconds: 5
             exec:
               command:
                 - sh
                 - -c
                 - |
                   . /opt/bitnami/airflow/venv/bin/activate && \
                   CONNECTION_CHECK_MAX_COUNT=0 python -m celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d celery@$(hostname) 

```

VS what we have used to get rid of the defunct processes: 
```
livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 180
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - pgrep
                - -f
                - airflow-worker

```
