### ISSUE TITLE
[bitname/redis-cluster] ExtraVolume didn't create, customised server label has error, and statefulset init container indent incorrect

### ISSUE THREAD

**Issue by fifa451** [bitnami/charts#2981]
**Which chart**:
redis-cluster 3.1.3

**Describe the bug**

* The extraVolume is not populated properly.
* The service customized label has error during the deployment.
* The int container in statefulset got errors.

**To Reproduce**
Steps to reproduce the behaviour:

* For **ExtraVolume**  
1. Add value to extraVolume section

```yaml
extraVolumes:
    - name: "test"
      secret:
        secretName: test
```
2. Run `helm template`
3.  The statefulset output volume section does not include new volume

* For **customized service label**
1. Add label value to service section 

```yaml
service:
  labels:
    test: test
```
2. Run `helm template`
3. The output has error
```bash
Error: YAML parse error on redis-cluster/templates/redis-svc.yaml: error converting YAML to JSON: yaml: line 9: mapping values are not allowed in this context
```
* For **Statefuset init container**  
1. Add **initContianer** values, under the **redis**

```yaml
redis:
  initContainers:
   - name: -init-config
      image: test:test
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "ls"]

```
2. enable the **sysImage** 

```yaml
sysctlImage:
  enabled: false
```
3. Run `helm template .`
4. The output error:

```bash
 YAML parse error on redis-cluster/templates/redis-statefulset.yaml: error converting YAML to JSON: yaml: line 114: did not find expected key
```

**Expected behavior**
* For **extraVolume**, the statefulset should have the customized volume.
* For **service lable**, the template output shouldn't have any errors.
* For  **Statefuset init container**  , the template output should have any errors.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by juan131** [comment]
Hi @fifa451 

There's an issue in the indentation of the values you shared (also the `:` are missing after `extraVolumes`):

```
extraVolumes
    - name: "test"
      secret:
        secretName: test
```

It should be:

```
redis:
  extraVolumes:
    - name: "test"
      secret:
        secretName: test
```

You're also missing the `:` after the `initContainers` and the container name shouldn't start with `-`:

```diff
redis:
- initContainers
+ initContainers:
-  - name: -init-config
+  - name: init-config
      image: test:test
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "ls"]
```

I also find there's an issue in the chart, and I created a PR to address it.
