### ISSUE TITLE
mysql secondary statefulset is not created

### ISSUE THREAD

**Issue by anjanaprasd** [bitnami/charts#29838]
### Name and Version

mysql-11.1.17

### What architecture are you using?
Kubernetes cluster

Hello everyone,

I am attempting to deploy a MySQL cluster using the Bitnami Helm chart, but I am facing an issue where only the primary StatefulSet is created, even though I have configured the chart to include secondary nodes.

I ran this command `helm template mysql-cluster bitnami/mysql --values newvalues.yml` and checked the output and  only saw primary set related configs 

Here are the details of my setup:
Helm Chart Information:
```
    Chart Name: Bitnami MySQL
    Helm Chart Version:mysql-11.1.17
    Kubernetes Version:1.30.0
```
Can someone please assist me with this?

### Are you using any custom parameters or values?

```yaml
auth:
  existingSecret: mysql-secret
  rootPasswordKey: mysql-root-password
  passwordKey: mysql-user-password
  replicationPasswordKey: mysql-replication-password

replication:
  enabled: true

primary:
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
  persistence:
    enabled: true
    existingClaim: pvc-mysql-primary
  initContainers:
    - name: init-permissions
      image: bitnami/minideb:latest
      command: ["sh", "-c", "mkdir -p /bitnami/mysql/data; chown -R 1001:1001 /bitnami/mysql/data"]
      volumeMounts:
        - name: data
          mountPath: /bitnami/mysql/

secondary:
  enabled: true
  replicaCount: 2
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
  persistence:
    enabled: true
    size: 10Gi
    storageClass: standard
  initContainers:
    - name: init-permissions
      image: bitnami/minideb:latest
      command: ["sh", "-c", "mkdir -p /bitnami/mysql/data; chown -R 1001:1001 /bitnami/mysql/data"]
      volumeMounts:
        - name: data
          mountPath: /bitnami/mysql/
```

### What is the expected behavior?

Only create primary set
