### ISSUE TITLE
postgresql-ha  huge_pages can't set by helm chart values.

### ISSUE THREAD

**Issue by taoyonggang** [bitnami/charts#29877]
### Name and Version

bitnami/postgresql-ha  14.2.34

### What architecture are you using?

None

### What steps will reproduce the bug?

Certainly. I'll draft an issue report in English, including the relevant parts of your configuration files with passwords removed. Here's the issue report:

We've encountered an issue where the `huge_pages = off` setting in PostgreSQL configuration does not take effect when deployed in a containerized environment using Helm charts. This occurs even when the setting is explicitly defined in both the `postgresql-ha-cm-values.yaml` and the `postgresql-extended-config.yaml` ConfigMap.

Configuration:
1. In `postgresql-ha-cm-values.yaml`:

```yaml
postgresql:
  extendedConfiguration: |-
    huge_pages = off
  initdb:
    args: "--set huge_pages=off"
  extendedConfCM: postgresql-extended-config
```

2. In `postgresql-extended-config.yaml`:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-extended-config
  namespace: gitlab
data:
  postgresql.conf: |
    huge_pages = off
    huge_page_size = 0
    # ... other configurations ...
```

Issue:
Despite these configurations, the `huge_pages = off` setting does not take effect. The PostgreSQL instance still attempts to use huge pages if they are enabled at the system level.

Root Cause:
It appears that the container inherits the host system's huge pages settings, overriding the PostgreSQL configuration.

Workaround:
We found a workaround that involves the following steps:
1. Set `vm.nr_hugepages = 0` at the system level before deploying PostgreSQL.
2. Deploy PostgreSQL with the configurations mentioned above.
3. After successful deployment, huge pages can be re-enabled at the system level if needed.
4. Subsequent container restarts do not reintroduce the issue, likely due to PostgreSQL's internal configuration being persisted.

Proposed Solution:
1. Update the Helm chart to include a pre-install hook that checks and potentially modifies the host system's huge pages setting.
2. Improve documentation to clearly explain this behavior and the necessary steps to ensure `huge_pages = off` takes effect.
3. Consider adding a warning or check in the chart to alert users if the system's huge pages setting conflicts with the desired PostgreSQL configuration.

Additional Notes:
- This issue highlights the complex interaction between container settings and host system configurations.
- A more robust solution might involve creating a custom Docker image that gracefully handles this configuration.

Please feel free to let me know if you need any further information or clarification on this issue.

### What do you see instead?

This issue report outlines the problem, includes relevant configuration snippets, explains the workaround you discovered, and proposes some potential solutions. It's written in a way that should be clear to the maintainers of the PostgreSQL Helm chart or the PostgreSQL Docker image.
