### ISSUE TITLE
[bitnami/keycloak] Keycloak Helm Chart + kubernetes Ingress + Angula Keycloak PoC

### ISSUE THREAD

**Issue by masalinas** [bitnami/charts#29885]
### Name and Version

bitnamicharts/keycloak

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1) Install a fresh Ubuntu 24.04 arm64 LTS version.
2) Install a fresh Docker 27.3.1 version
3) Install minikube 1.34.0 version.
4) Deploy Keycloak using the last Keycloak Helm chart wit this values:

```
auth:
  adminUser: admin
  adminPassword: password

proxyHeaders: xforwarded
```

5) Add minikube public IP to minikube.io domain in /etc/hosts

6) Configure two  ingress one to access Admin console and other to access to a  Keycloak Angular PoC application

- Admin Console Ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: keycloak-ingress
spec:
  rules:
  - host: minikube.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gsdpi-keycloak
              port:
                name: http
```

- Admin Angular Keycloak:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: portal-ingress
spec:
  rules:
  - host: minikube.io
    http:
      paths:
      - path: /morphingprojections-portal(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: uniovi-avib-morphingprojections-portal
            port: 
              name: http
```

7) Access to Admin Console works ok throw: `https://minikube.io` Create a realm called **avib**, client called **portal-ui**, and a user called **user** correctly.

8) Access to Angular Portal PoC thow: `https://minikube.io/morphingprojections-portal` not works with this error:

`Mixed Content: The page at 'https://minikube.io/morphingprojections-portal' was loaded over HTTPS, but requested an insecure frame 'http://minikube.io/realms/avib/protocol/openid-connect/3p-cookies/step1.html'. This request has been blocked; the content must be served over HTTPS.`

**Notes**: the Angular PoC worls ok using a kubectl port-forward

### What do you see instead?

Mixed Content: The page at 'https://minikube.io/morphingprojections-portal' was loaded over HTTPS, but requested an insecure frame 'http://minikube.io/realms/avib/protocol/openid-connect/3p-cookies/step1.html'. This request has been blocked; the content must be served over HTTPS.

### Additional information

I checked the same User Case following the Keycloak Kubernetes Default sample in https://www.keycloak.org/getting-started/getting-started-kube and **works ok**, of course in thiscase they don't use any chart directly only one deployment and service. **Something is not configured in the chart equals to keycloak sample**

**Comment by javsalgar** [comment]
Hi!

Did you check this issue? It also mentions about mixed content issues https://github.com/bitnami/charts/issues/6940

Also make sure to check the latest changes in keycloak 26 https://www.keycloak.org/docs/latest/upgrading/index.html#migrating-to-26-0-0

**Comment by masalinas** [comment]
Finally I resolved the url redirection but I obtain other error realted to the iframe policy, because My arquitecture is this one:

` Browser ------- HTTPS -----> Apache Proxy ------HTTP----->Minikube Ingress -----HTTP ----> Keycloak`

So Is try to open the Keycloak Admin Console from a HTTPS protocol the **Content-security Policy** configured in the master realm is triggered and my browser block the iframe inside the Keycloak Login View with this error:

```
I checked many comments in internet similar than you, but you explain more clear than others, but, it not works. My user case is simple a Keycloak deployed in development mode (without TLS) but remote access to from a TLS Proxy.
The error obtain is the clasical:
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure resource '<URL>'. This request has been blocked; the content must be served over HTTPS.Understand this error
ajaxRequestInterceptor.ps.js:1 Mixed Content:
The page at 'https://<DOMAIN>/admin/master/console/' was loaded over HTTPS, but requested an insecure resource 'http://<DOMAIN>//resources/master/admin/en'. This request has been blocked; the content must be served over HTTPS.
I tryed to update the policy called Content-Security-Policy in the master realm to have access to Keycloak Admin Console using:
frame-src 'self' https://<DOMAIN>; frame-ancestors 'self'; object-src 'none';
And serveral convination with http, htts, including also this config in frame-ancestors policy and frame-src, etc without any success
```

I tried to configure this policy in the master realm adding my https://domain but without any success. I would like configured Keycloak in development mode inside the kubernetes cluster, but this policy is blocking me as you see.

**Comment by masalinas** [comment]
Finally works the problem was that you must active **forwarded** and not **xforwarded**. Finally my **values.yaml** passed to bitnami chart is:

```
proxyHeaders: "forwarded"

extraEnvVars:
  - name: KC_BOOTSTRAP_ADMIN_USERNAME
    value: "admin"
  - name: KC_BOOTSTRAP_ADMIN_PASSWORD
    value: "password"
```
