### ISSUE TITLE
[bitnami/opensearch] LDAP configuration not working

### ISSUE THREAD

**Issue by sanekj** [bitnami/charts#29888]
### Name and Version

bitnami/opensearch:1.3.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

It is not possible to rewrite ldap configuration via env variables.
(Let's see my var definition below).

### Are you using any custom parameters or values?
```
extraEnvVars:
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_ENABLED
    value: "true"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_ENABLED
    value: "true"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_HOSTS
    value: "ldaps://fr2c306a.bbbbb.mydomain.com:3269"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_BIND_DN
    value: "cn=myuser,ou=Users02,ou=Users,ou=te,ou=lda,dc=mysubdomain,dc=mydomain,dc=com"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_PASSWORD
    value: "mypassword"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_USERBASE
    value: "dc=mydomain,dc=com"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_USERSEARCH
    value: "(sAMAccountName={0})"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_USERNAME_ATTRIBUTE
    value: "sAMAccountName"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_ROLEBASE
    value: ",OU=Groups04,OU=Groups,OU=au06,OU=wwu,OU=lda,DC=bbbbb,DC=mydomain,DC=com"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_ROLESEARCH
    value: "(member={0})"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_ROLENAME
    value: "cn"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_USERROLEATTRIBUTE
    value: "memberOf"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_ROLES
    value: "admin,readall"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_ENABLE_SSL
    value: "true"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_ENABLE_STARTTLS
    value: "false"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_TRUST_ALL_CERTIFICATES
    value: "true"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_VERIFY_HOSTNAMES
    value: "false"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_TIMEOUT_TCP_CONNECT
    value: "5000"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_TIMEOUT_TCP_READ
    value: "5000"
  - name: OPENSEARCH_SECURITY_AUTHZ_LDAP_PAGED_RESULTS_SIZE
    value: "1000"
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_HOSTS
    value: "ldaps://fr2c306a.bbbbb.mydomain.com:3269"
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_BIND_DN
    value: "cn=myuser,ou=Users02,ou=Users,ou=te,ou=lda,dc=mysubdomain,dc=mydomain,dc=com"
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_PASSWORD
    value: "mypassword"
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_USERBASE
    value: "dc=mydomain,dc=com"
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_USERSEARCH
    value: "(sAMAccountName={0})"
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_USERNAME_ATTRIBUTE
    value: "sAMAccountName"
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_ROLEBASE
    value: "OU=Groups04,OU=Groups,OU=au06,OU=wwu,OU=lda,DC=bbbbb,DC=mydomain,DC=com"
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_ROLESEARCH
    value: "(member={0})"
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_ROLENAME
    value: "cn"
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_USERROLEATTRIBUTE
    value: "memberOf"
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_ROLES
    value: "admin,readall"
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_ENABLE_SSL
    value: "true"
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_ENABLE_STARTTLS
    value: "false"
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_TRUST_ALL_CERTIFICATES
    value: "true"
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_VERIFY_HOSTNAMES
    value: "false"
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_TIMEOUT_TCP_CONNECT
    value: "15000"
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_TIMEOUT_TCP_READ
    value: "15000"
  - name: OPENSEARCH_SECURITY_AUTHC_LDAP_PAGED_RESULTS_SIZE
    value: "10000"
```
