### ISSUE TITLE
[bitnami/matomo] Failed to calculate the number of expected pods: jobs.batch does not implement the scale subresource

### ISSUE THREAD

**Issue by viceice** [bitnami/charts#29884]
### Name and Version

bitnami/matomo 8.0.13

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy chart with archive job enabled
2. See `Failed to calculate the number of expected pods: jobs.batch does not implement the scale subresource` warning

### Are you using any custom parameters or values?

```yaml
cronjobs:
  taskScheduler:
    enabled: false
  archive:
    schedule: 15 * * * *
```

### What is the expected behavior?

Don't see that warning

### What do you see instead?

Seeing the `Failed to calculate the number of expected pods: jobs.batch does not implement the scale subresource` warning for the `PodDisruptionBudget`

### Additional information

It looks like the pdb is also matching the archive job because the selector label are matching all matomo pods.

![image](https://github.com/user-attachments/assets/22deff46-0380-410a-93be-d0a3caf9a774)

![image](https://github.com/user-attachments/assets/fd8a8ee8-2cb6-4c90-86f7-3c926b0c11c2)

![image](https://github.com/user-attachments/assets/000f19ce-3f74-4a9a-809d-d1f170ca6a6b)

I think the matomo deployment should also get the `app.kubernetes.io/component` label and the pdb selector should also get that added.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by viceice** [comment]
please reopen, it's still an issue

**Comment by no-fy** [comment]
Thank you @viceice for pointing out the “component” label missing 
As a temporary fix, in the values,
I added a component label to the matomo pod using:
```
podLabels:
  app.kubernetes.io/component: matomo
```
Disabled the provided podDisruptionBudget :
```
pdb:
  create: false
```
And then created a custom PDB matching the component using the `extradeploy` option available in Bitnami charts :
```
extraDeploy:
  - apiVersion: policy/v1
    kind: PodDisruptionBudget
    metadata:
      name: matomo-pdb
    spec:
      maxUnavailable: 1
      selector:
        matchLabels:
          app.kubernetes.io/component: matomo
```
Hope it can help.
