### ISSUE TITLE
cannot create regular file '/opt/bitnami/schema-registry/certs/schema-registry.truststore.jks': Permission denied

### ISSUE THREAD

**Issue by chethan8592** [bitnami/charts#29891]
### Name and Version

bitnami/schema-registry: 7.7.1-debian-12-r0

### What architecture are you using?

None

### What steps will reproduce the bug?

below is my HELM chart configuration:
```yaml
global:
  imageRegistry: ""
  imagePullSecrets: []
  defaultStorageClass: ""
  compatibility:
    openshift:
      adaptSecurityContext: auto
kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
commonLabels: {}
commonAnnotations: {}
clusterDomain: cluster.local
extraDeploy: []
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity
image:
  registry: docker.io
  repository: bitnami/schema-registry
  tag: 7.7.1-debian-12-r0
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
command: []
args: []
automountServiceAccountToken: false
hostAliases: []
podLabels: {}
configuration: 
existingConfigmap: ""
log4j: 
  rootLogger: "DEBUG, stdout"
  loggers:
    io.confluent.kafka.schemaregistry: DEBUG
existingLog4jConfigMap: ""
auth:
  tls:
    enabled: false
    jksSecret: ""  # Secret containing your JKS files
    keystorePassword: ""
    truststorePassword: ""
    clientAuthentication: "NONE"
  kafka:
    jksSecret: "schema-registry-kafka-secret"  # Use the same secret for Kafka connection
    tlsEndpointIdentificationAlgorithm: ""
    keystorePassword: "password"
    truststorePassword: "password"
    saslMechanism: ""

listeners: http://0.0.0.0:8081
avroCompatibilityLevel: backward
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
replicaCount: 1
updateStrategy:
  type: RollingUpdate
nodeAffinityPreset:
  type: ""
  key: ""
  values: []
affinity: {}
nodeSelector: {}
tolerations: []
podManagementPolicy: OrderedReady
podAnnotations: {}
podAffinityPreset: ""
podAntiAffinityPreset: soft
priorityClassName: ""
topologySpreadConstraints: {}
schedulerName: ""
terminationGracePeriodSeconds: ""
lifecycleHooks: {}
podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  supplementalGroups: []
  fsGroup: 1001
  sysctls: []
containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"
resourcesPreset: "small"
resources: {}
livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 1
  periodSeconds: 20
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 1
  periodSeconds: 20
  failureThreshold: 6
  successThreshold: 1
startupProbe:
  enabled: false
  initialDelaySeconds: 10
  timeoutSeconds: 1
  periodSeconds: 5
  failureThreshold: 20
  successThreshold: 1
customLivenessProbe: {}
customReadinessProbe: {}
customStartupProbe: {}
extraVolumes: []
extraVolumeMounts: []
initContainers: []     

sidecars: []
pdb:
  create: true
  minAvailable: ""
  maxUnavailable: ""
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 11
  targetCPU: ""
  targetMemory: ""
  customPodMetrics: []
service:
  type: ClusterIP
  ports:
    http: 8081
  nodePorts:
    http: ""
  clusterIP: ""
  externalTrafficPolicy: Cluster
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  annotations: {}
  labels: {}
  extraPorts: []
  sessionAffinity: None
  sessionAffinityConfig: {}
  headless:
    annotations: {}
networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: true
  extraIngress: []
  extraEgress: []
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
ingress:
  enabled: false
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: schema-registry.local
  ingressClassName: ""
  path: /
  annotations: {}
  tls: false
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraTls: []
  secrets: []
  extraRules: []
serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: false
kafka:
  enabled: false
  controller:
    replicaCount: 1
  listeners:
    client:
      protocol: "PLAINTEXT"
  service:
    ports:
      client: 9092
  extraConfig: |-
    offsets.topic.replication.factor=1
  sasl:
    client:
      users:
        - user
      passwords: ""
externalKafka:
  brokers:
    - SSL://{environment}-connect.client.com:443
  listener:
    protocol: SSL
  sasl:
    user: ""
    password: ""
    existingSecret: ""
```

And below is my secret that has to connect with Kafka broker:
```yaml
apiVersion: v1
data:
  schema-registry-0.keystore.jks: "***"
  schema-registry.truststore.jks: "***"
kind: Secret
metadata:
  creationTimestamp: "2024-10-14T11:26:09Z"
  name: schema-registry-kafka-secret
  namespace: strimzi-demo
  resourceVersion: "345"
  uid: a19fc4ca-9691-4038-8c5f-***
type: Opaque
```

### What do you see instead?

getting error when deploying using HELM chart:
```
**cp: cannot create regular file '/opt/bitnami/schema-registry/certs/schema-registry.truststore.jks': Permission denied**
```
