### ISSUE TITLE
Unable to serve dashboards behind rev proxy (nginx) on K8s under path /os/dashboards

### ISSUE THREAD

**Issue by aceeric** [bitnami/charts#29902]
### Name and Version

bitnami/opensearch 1.3.11

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm unable to serve the dashboards under anything other than path `/`.

With this install command:
```
helm upgrade --install opensearch https://charts.bitnami.com/bitnami/opensearch-1.3.11.tgz\
  --namespace os\
  --create-namespace\
  --values see-below.yaml
```

### Are you using any custom parameters or values?

Here is the dashboard portion of my values file:
```yaml
dashboards:
  enabled: true
  persistence:
    enabled: true
  ingress:
    enabled: true
    hostname: xyz.org
    path: /os/dashboards/?(.*)
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
  resources: {}
  extraEnvVars:
  - name: SERVER_BASEPATH
    value: /os/dashboards
  #- name: SERVER_REWRITEBASEPATH
  #  value: "true"
```

### What is the expected behavior?

http://xyz.com/os/dashboards should work

### What do you see instead?

Redirects to http://xyz.com/app/home (i.e. ignores the `SERVER_BASEPATH` env var)

### Additional information

According to [this link](https://github.com/bitnami/containers/blob/main/bitnami/opensearch-dashboards/README.md), it's not clear that this environment variable - which is supported in the upstream image - is supported by the bitnami container though I don't know why it would not be...
