### ISSUE TITLE
[bitnami/consul] Error with Values.yaml 

### ISSUE THREAD

**Issue by pomland-94** [bitnami/charts#29955]
### Name and Version

bitnami/consul:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?

When i try to install Consul with my Custom Values i get a json error:

### Are you using any custom parameters or values?

```shell
clusterDomain: cluster.local
datacenterName: "DE-NBG1-DC3"
domain: "consul.svc.cluster.local"
raftMultiplier: "1"
gossipKey: "JT3qk2vPopJMbRUgFSKK29tdz2ed+bL/KeAQB/vjHbA="
tlsEncryptionSecretName: consul-tls
automountServiceAccountToken: true
configuration: |-
  {
    "ca_file": "/opt/bitnami/consul/certs/ca.pem",
    "cert_file": "/opt/bitnami/consul/certs/consul.pem",
    "key_file": "/opt/bitnami/consul/certs/consul-key.pem",
    "verify_incoming": true,
    "verify_outgoing": true,
    "verify_server_hostname": true
  }
containerPorts:
  http: 8500
  dns: 8600
  rpc: 8400
  rpcServer: 8300
  serfLAN: 8301
  serfWAN: 8302
replicaCount: 3
updateStrategy:
  type: RollingUpdate
containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  privileged: false
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"
  readOnlyRootFilesystem: true
resourcesPreset: "nano"
pdb:
  create: true
  minAvailable: "3"
serviceAccount:
  create: true
  automountServiceAccountToken: false
service:
  enabled: true
  ports:
    http: 80
  type: ClusterIP
ingress:
  enabled: false
persistence:
  enabled: true
  storageClass: "rook-cephfs"
  accessModes:
    - ReadWriteMany
  size: 20Gi
metrics:
  enabled: true
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
    readOnlyRootFilesystem: true
  serviceMonitor:
    enabled: false
```

### What do you see instead?

```shell
[root@admingw-01]
~/k8s-deployments/consul-cluster:helm install --namespace consul consul bitnami/consul -f values.yaml 
Error: INSTALLATION FAILED: 1 error occurred:
	* ConfigMap in version "v1" cannot be handled as a ConfigMap: json: cannot unmarshal object into Go struct field ConfigMap.data of type string


[root@admingw-01]
~/k8s-deployments/consul-cluster:
```

**Comment by javsalgar** [comment]
Hi!

Could you execute `helm template`  to see what the faulty configmap looks like?

**Comment by pomland-94** [comment]
```yaml
[root@admingw-01]
~/k8s-deployments/consul-cluster:helm --namespace consul template consul bitnami/consul -f values.yaml 
---
# Source: consul/templates/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: consul
  namespace: "consul"
  labels:
    app.kubernetes.io/instance: consul
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: consul
    app.kubernetes.io/version: 1.20.0
    helm.sh/chart: consul-11.3.17
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: consul
      app.kubernetes.io/name: consul
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - ports:
        - port: 8500
          protocol: TCP
        - port: 8400
          protocol: TCP
        - port: 8301
          protocol: TCP
        - port: 8301
          protocol: UDP
        - port: 8300
          protocol: TCP
        - port: 8600
          protocol: TCP
        - port: 8600
          protocol: UDP
---
# Source: consul/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: consul
  namespace: "consul"
  labels:
    app.kubernetes.io/instance: consul
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: consul
    app.kubernetes.io/version: 1.20.0
    helm.sh/chart: consul-11.3.17
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: consul
      app.kubernetes.io/name: consul
---
# Source: consul/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul
  namespace: "consul"
  labels:
    app.kubernetes.io/instance: consul
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: consul
    app.kubernetes.io/version: 1.20.0
    helm.sh/chart: consul-11.3.17
automountServiceAccountToken: false
---
# Source: consul/templates/gossip-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: consul-gossip-key
  namespace: "consul"
  labels:
    app.kubernetes.io/instance: consul
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: consul
    app.kubernetes.io/version: 1.20.0
    helm.sh/chart: consul-11.3.17
type: Opaque
data:
  gossip-key: SlQzcWsydlBvcEpNYlJVZ0ZTS0syOXRkejJlZCtiTC9LZUFRQi92akhiQT0=
---
# Source: consul/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-configuration
  namespace: "consul"
  labels:
    app.kubernetes.io/instance: consul
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: consul
    app.kubernetes.io/version: 1.20.0
    helm.sh/chart: consul-11.3.17
data:
  config.json:
    {
      "ca_file": "/opt/bitnami/consul/certs/ca.pem",
      "cert_file": "/opt/bitnami/consul/certs/consul.pem",
      "key_file": "/opt/bitnami/consul/certs/consul-key.pem",
      "verify_incoming": true,
      "verify_outgoing": true,
      "verify_server_hostname": true
    }
  connection.json: |
    {
      "retry_join": ["consul-headless.consul.svc.cluster.local"]
    }
---
# Source: consul/templates/consul-headless-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: consul-headless
  namespace: "consul"
  labels:
    app.kubernetes.io/instance: consul
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: consul
    app.kubernetes.io/version: 1.20.0
    helm.sh/chart: consul-11.3.17
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      protocol: TCP
      port: 8500
    - name: rpc
      port: 8400
    - name: serflan-tcp
      protocol: TCP
      port: 8301
    - name: serflan-udp
      protocol: UDP
      port: 8302
    - name: serfwan-tcp
      protocol: TCP
      port: 8302
    - name: serfwan-udp
      protocol: UDP
      port: 8301
    - name: rpc-server
      port: 8300
    - name: dns-tcp
      port: 8600
    - name: dns-udp
      protocol: UDP
      port: 8600
  selector:
    app.kubernetes.io/instance: consul
    app.kubernetes.io/name: consul
  sessionAffinity: None
---
# Source: consul/templates/metrics-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: consul-metrics
  namespace: "consul"
  labels:
    app.kubernetes.io/instance: consul
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: consul
    app.kubernetes.io/version: 1.20.0
    helm.sh/chart: consul-11.3.17
    app.kubernetes.io/component: metrics
  annotations:
    prometheus.io/port: "9107"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  
  ports:
    - name: http-metrics
      port: 9107
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: consul
    app.kubernetes.io/name: consul
---
# Source: consul/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: consul-ui
  namespace: "consul"
  labels:
    app.kubernetes.io/instance: consul
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: consul
    app.kubernetes.io/version: 1.20.0
    helm.sh/chart: consul-11.3.17
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/instance: consul
    app.kubernetes.io/name: consul
---
# Source: consul/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
  namespace: "consul"
  labels:
    app.kubernetes.io/instance: consul
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: consul
    app.kubernetes.io/version: 1.20.0
    helm.sh/chart: consul-11.3.17
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: consul
      app.kubernetes.io/name: consul
  replicas: 3
  podManagementPolicy: Parallel
  serviceName: consul-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: consul
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: consul
        app.kubernetes.io/version: 1.20.0
        helm.sh/chart: consul-11.3.17
      annotations:
        checksum/configuration: bf49b30f70989241a3ccc9f2108efb1dcb28d104d44955b2e785864912f8597f
        prometheus.io/port: "9107"
        prometheus.io/scrape: "true"
    spec:
      
      serviceAccountName: consul
      automountServiceAccountToken: true
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: consul
                    app.kubernetes.io/name: consul
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      containers:
        - name: consul
          image: docker.io/bitnami/consul:1.20.0-debian-12-r0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: http
              containerPort: 8500
            - name: rpc
              containerPort: 8400
            - name: serflan-tcp
              protocol: "TCP"
              containerPort: 8301
            - name: serflan-udp
              containerPort: 8301
              protocol: "UDP"
            - name: serfwan-tcp
              protocol: "TCP"
              containerPort: 8302
            - name: serfwan-udp
              containerPort: 8302
              protocol: "UDP"
            - name: rpc-server
              containerPort: 8300
            - name: dns-tcp
              containerPort: 8600
            - name: dns-udp
              containerPort: 8600
              protocol: "UDP"
          resources:
            limits:
              cpu: 150m
              ephemeral-storage: 2Gi
              memory: 192Mi
            requests:
              cpu: 100m
              ephemeral-storage: 50Mi
              memory: 128Mi
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: CONSUL_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CONSUL_RETRY_JOIN
              value: "consul-headless.consul.svc.cluster.local"
            - name: CONSUL_DISABLE_KEYRING_FILE
              value: "true"
            - name: CONSUL_BOOTSTRAP_EXPECT
              value: "3"
            - name: CONSUL_RAFT_MULTIPLIER
              value: "1"
            - name: CONSUL_DOMAIN
              value: "consul.svc.cluster.local"
            - name: CONSUL_DATACENTER
              value: "DE-NBG1-DC3"
            - name: CONSUL_GOSSIP_ENCRYPTION
              value: "yes"
            - name: CONSUL_GOSSIP_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: consul-gossip-key
                  key: gossip-key
            - name: CONSUL_UI
              value: "true"
            - name: CONSUL_HTTP_PORT_NUMBER
              value: "8500"
            - name: CONSUL_DNS_PORT_NUMBER
              value: "8600"
            - name: CONSUL_RPC_PORT_NUMBER
              value: "8400"
            - name: CONSUL_SERF_LAN_PORT_NUMBER
              value: "8301"
            - name: CONSUL_SERF_WAN_PORT_NUMBER
              value: "8302"
          envFrom:
          livenessProbe:
            exec:
              command:
                - consul
                - operator
                - raft
                - list-peers
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - consul
                - members
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          lifecycle:
            preStop:
              exec:
                command:
                  - consul
                  - leave
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/consul/conf
              subPath: app-conf-dir
            - name: empty-dir
              mountPath: /opt/bitnami/consul/tmp
              subPath: app-tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/consul/logs
              subPath: app-logs-dir
            - name: consul-tls-certs
              mountPath: "/opt/bitnami/consul/certificates/"
              readOnly: true
            - name: data
              mountPath: /bitnami/consul
            - name: consul-config
              mountPath: /opt/bitnami/consul/conf/config.json
              subPath: config.json
            - name: consul-config
              mountPath: /opt/bitnami/consul/conf/connection.json
              subPath: connection.json
        - name: metrics
          image: docker.io/bitnami/consul-exporter:0.12.1-debian-12-r6
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          command:
            - /bin/consul_exporter
            - --consul.server=consul-headless:8500
          ports:
            - name: metrics
              containerPort: 9107
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 150m
              ephemeral-storage: 2Gi
              memory: 192Mi
            requests:
              cpu: 100m
              ephemeral-storage: 50Mi
              memory: 128Mi
      volumes:
        - name: empty-dir
          emptyDir: {}
        - name: consul-config
          configMap:
            name: consul-configuration
        - name: consul-tls-certs
          secret:
            secretName: consul-tls
            items:
              - key: ca.pem
                path: ca.pem
              - key: consul.pem
                path: consul.pem
              - key: consul-key.pem
                path: consul.key.pem
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteMany"
        resources:
          requests:
            storage: "20Gi"
        storageClassName: rook-cephfs
[root@admingw-01]
~/k8s-deployments/consul-cluster:
```
