### ISSUE TITLE
[bitnami/contour] Unable to create a defaultBackend with a mounted Volume

### ISSUE THREAD

**Issue by GreatSymphonia** [bitnami/charts#29976]
### Name and Version

bitnami/contour

### What architecture are you using?

None

### What steps will reproduce the bug?

When attempting to create a contour ingress with a default backend, I am unable to create one with an extraVolume.

### Are you using any custom parameters or values?

```yaml
  extraVolumes:
    - emptyDir: {}
      name: nginx
  extraVolumeMounts:
    - mountPath: /opt/bitnami/nginx/tmp
      name: nginx
```

### What is the expected behavior?

I expect it to create a defaultBackend container (nginx with a default 404 landing page) with the aforementionned volume

### What do you see instead?

```shell
shell@shell:~$ helm upgrade --install lan-contour bitnami/contour --namespace lan-contour -f system/Lan_ETS/contour/values.yaml
Error: UPGRADE FAILED: YAML parse error on contour/templates/default-backend/deployment.yaml: error converting YAML to JSON: yaml: line 106: did not find expected '-' indicator
```
