### ISSUE TITLE
[bitnami/redis] sentinel readiness or livenees probe failed

### ISSUE THREAD

**Issue by PustyB** [bitnami/charts#29985]
### Name and Version

bitnami/redis 7.4.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Kubernetes v1.30.1, From time to time I get an error ”readiness probe failed: command “sh -c /health/ping_sentinel.sh 4” timed out” this happens on random nodes and only on the sentinel container. As you can see I increased the timeoutSeconds to 4 but it still doesn't help.

### Are you using any custom parameters or values?

```yaml
 sentinel:
   startupProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 22
  
    livenessProbe:
      enabled: true
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 6
  
    readinessProbe:
      enabled: true
      initialDelaySeconds: 20
      periodSeconds: 5
      timeoutSeconds: 4
      successThreshold: 1
      failureThreshold: 6
```

### What do you see instead?

From time to time it throws an error: `Readiness probe failed: command "sh -c /health/ping_sentinel.sh 4" timed out" or "Liveness probe failed: command "sh -c /health/ping_sentinel.sh 5" timed out`

### Additional information

I increased the CPU and RAM limits, but that didn't help. Is there anything else that can be done besides increasing timeoutSeconds?
