### ISSUE TITLE
[bitnami/discourse]: Plugins are installed in /opt/bitnami/discourse/plugins/plugins

### ISSUE THREAD

**Issue by VasquezPonte** [bitnami/charts#29990]
### Name and Version

bitnami/discourse 15.0.2

### What architecture are you using?

None

### What steps will reproduce the bug?

Install the helm chart 15.0.2 with a list of plugins defined in the values.yaml file.

### Are you using any custom parameters or values?

```
updateStrategy:
  type: Recreate
  rollingUpdate: null

discourse:
  plugins:
  - https://github.com/communiteq/discourse-anonymous-categories
  - https://github.com/paviliondev/discourse-custom-wizard
  - https://github.com/discourse/discourse-data-explorer
  - https://github.com/discourse/discourse-reactions
  - https://github.com/discourse/discourse-docs
  - https://github.com/gschlager/discourse-german-formal-locale
  - https://github.com/jonmbake/discourse-ldap-auth
  - https://github.com/paviliondev/discourse-locations
  - https://github.com/discourse/discourse-rss-polling
  - https://github.com/discourse/discourse-shared-edits
  - https://github.com/discourse/discourse-topic-voting
  - https://github.com/discourse/discourse-follow
  - https://github.com/discourse/discourse-solved
  - https://github.com/discourse/discourse-templates
  - https://github.com/discourse/discourse-calendar
  - https://github.com/discourse/discourse-chat-integration
  persistPlugins: false
```

### What is the expected behavior?

The plugins should be installed in  `/opt/bitnami/discourse/plugins/` and the list of installed plugins in the GUI should not be empty.

### What do you see instead?

The plugins are installed in `/opt/bitnami/discourse/plugins/plugins/` and the list of Plugins in the GUI is therefore empty.

### Additional information

I tested both cases “persistPlugins: **false**” and “persistPlugins: **true**” with the same result.

After making following changes, the Plugins were successfully installed.

```
--- a/bitnami/discourse/templates/deployment.yaml
+++ b/bitnami/discourse/templates/deployment.yaml
@@ -148,7 +148,7 @@ spec:
           args:
             - -ec
             - |
-              cp -r --preserve=mode /plugins /opt/bitnami/discourse/plugins
+              cp -r --preserve=mode /plugins /opt/bitnami/discourse/
               /opt/bitnami/scripts/discourse/entrypoint.sh /opt/bitnami/scripts/discourse/run.sh
           {{- end }}
           env:
@@ -267,7 +267,7 @@ spec:
               subPath: discourse
             {{- if .Values.discourse.plugins }}
             - name: empty-dir
-              subPath: app-plugins-dir
+              subPath: app-plugins-dir/plugins
               mountPath: {{ ternary "/plugins" "/opt/bitnami/discourse/plugins" .Values.discourse.persistPlugins }}
             {{- end }}
             {{- if .Values.discourse.extraVolumeMounts }}
@@ -382,7 +382,7 @@ spec:
             {{- if and .Values.discourse.plugins (not .Values.discourse.persistPlugins) }}
             - name: empty-dir
               mountPath: /opt/bitnami/discourse/plugins
-              subPath: app-plugins-dir
+              subPath: app-plugins-dir/plugins
             {{- end }}
             {{- if .Values.sidekiq.extraVolumeMounts }}
             {{- include "common.tplvalues.render" (dict "value" .Values.sidekiq.extraVolumeMounts "context" $) | nindent 12 }}
```
