### ISSUE TITLE
ETCD chart erro

### ISSUE THREAD

**Issue by Alpha-Zark** [bitnami/charts#30049]
### Name and Version

bitnami/etcd 10.4.0

### What architecture are you using?

None

### What steps will reproduce the bug?

when I use a gotmpl value file: 
```yaml
defrag:
  enabled: true
  cronjob:
    schedule: "0 0 * * *"
    concurrencyPolicy: Forbid
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
    restartPolicy: OnFailure
    podLabels:
      etcd/role: defrag
```
### Are you using any custom parameters or values?

I use a helmfile :
```yaml
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: etcd
    chart: bitnami/etcd
    namespace: etcd
    version: 10.4.0
    values:
      - ./etcd-values.yaml.gotmpl
    labels:
      app: etcd
```
 apply:
```
 helmfile -f ./helmfile.yaml \
--selector name=etcd \
-i \
apply
```
### What do you see instead?
```
 Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(CronJob.spec.jobTemplate.spec.template): unknown field "metadata:labels" in io.k8s.api.core.v1.PodTemplateSpec
```

### Additional information

I had try delete the "podLabels" and its values, but it still has this error log
