### ISSUE TITLE
[bitnami/etcd] Duplicated securityContext in Defrag CronJob

### ISSUE THREAD

**Issue by mikyll** [bitnami/charts#30053]
### Name and Version

bitnami/etcd 10.4.x

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Enable **etcd defrag**. For example, create the following `values_defrag_test.yaml`:
    
    ```yaml
    defrag:
      enabled: true
    ```
2. Render helm chart template (from `bitnami/etcd/` directory):
    
    ```bash
    helm template etcd . --dry-run --debug -f ./values_defrag_test.yaml.yaml > debug_test_defrag.yaml
    ```
    
Result (file `debug_test_defrag.yaml`):

```yaml
# [...]
---
# Source: etcd/templates/cronjob-defrag.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-defrag
  namespace: "default"
  labels:
    app.kubernetes.io/instance: etcd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: etcd
    app.kubernetes.io/version: 3.5.16
    helm.sh/chart: etcd-10.4.1
spec:
  concurrencyPolicy: Forbid
  schedule: "0 0 * * *"
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: etcd
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: etcd
            app.kubernetes.io/version: 3.5.16
            helm.sh/chart: etcd-10.4.1
        spec:
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 1001
            fsGroupChangePolicy: Always
            supplementalGroups: []
            sysctls: []
          containers:
            - name: etcd-defrag
              image: docker.io/bitnami/etcd:3.5.16-debian-12-r2
              imagePullPolicy: "IfNotPresent"
              securityContext:    # <-- First "correct" security context
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
                privileged: false
                readOnlyRootFilesystem: true
                runAsGroup: 1001
                runAsNonRoot: true
                runAsUser: 1001
                seLinuxOptions: {}
                seccompProfile:
                  type: RuntimeDefault
              env:
                - name: BITNAMI_DEBUG
                  value: "false"
              command: ["etcdctl"]
              args:
                - defrag
                - --cluster
                - --endpoints=[http://etcd-0.etcd-headless.default.svc.cluster.local:2379]
              resources:
                limits:
                  cpu: 150m
                  ephemeral-storage: 2Gi
                  memory: 192Mi
                requests:
                  cpu: 100m
                  ephemeral-storage: 50Mi
                  memory: 128Mi
              securityContext:    # <-- Duplicated security context
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
                privileged: false
                readOnlyRootFilesystem: true
                runAsGroup: 1001
                runAsNonRoot: true
                runAsUser: 1001
                seLinuxOptions: {}
                seccompProfile:
                  type: RuntimeDefault
# [...]
```

### Are you using any custom parameters or values?

`values_defrag_test.yaml`:

```yaml
defrag:
  enabled: true
```

### What is the expected behavior?

Render a single `spec.jobTemplate.spec.template.spec.containers[0].securityContext` in etcd-defrag CronJob.

### What do you see instead?

Duplicated `spec.jobTemplate.spec.template.spec.containers[0].securityContext` in etcd-defrag CronJob.

### Additional information

This issue is not critical, since the two configuration are identical
