### ISSUE TITLE
Custom ReplicaSet Config Failing to be Created

### ISSUE THREAD

**Issue by ZachThill** [bitnami/charts#30086]
### Name and Version

bitnami/mongodb:16.1.0

### What architecture are you using?

amd64

## Reproduce the issue:
Use my custom values file defined below and deploy it using version `16.1.0` of the bitnami/mongodb helm chart.

### Custom Values File

```
global:
  storageClass: gp2

clusterDomain: cluster.local

commonLabels:
  app: mongodb
commonAnnotations: {}

architecture: replicaset

replicaCount: 3
replicaSetHostnames: true

replicaSetConfigurationSettings:
  enabled: {{ .Values.cluster.eks.add_ons.mongodb.externalAccess.enabled }}
  configuration:
    members[0]._id: 0
    members[0].host: "{{ .Values.cluster.name }}-mongodb-0-internal.{{ .Values.cluster.hosted_zone.name }}:27017"
    members[0].priority: 5
    members[1]._id: 1
    members[1].host: "{{ .Values.cluster.name }}-mongodb-1-internal.{{ .Values.cluster.hosted_zone.name }}:27017"
    members[1].priority: 1
    members[2]._id: 2
    members[2].host: "{{ .Values.cluster.name }}-mongodb-2-internal.{{ .Values.cluster.hosted_zone.name }}:27017"
    members[2].priority: 1
    members[3]._id: 3
    members[3].host: mongodb-arbiter-0.mongodb-arbiter-headless.mongodb.svc.cluster.local:27017
    members[3].arbiterOnly: true
    members[3].buildIndexes: true
    members[3].hidden: true
    members[3].priority: 0

podLabels: {}
podAnnotations: {}

resources: {{ .Values.cluster.eks.add_ons.mongodb.resources }}

arbiter:
  enabled: true
  podLabels: {}
  podAnnotations: {}
  resources: {{ .Values.cluster.eks.add_ons.mongodb.arbiter.resources }}

tls:
  enabled: true
  mTLS:
    enabled: true
  autoGenerated: true
  mode: requireTLS

automountServiceAccountToken: true

externalAccess:
  enabled: {{ .Values.cluster.eks.add_ons.mongodb.externalAccess.enabled }}
  service:
    type: LoadBalancer
    portName: "mongodb"
    ports:
      mongodb: 27017
    publicNames:
      - "{{ .Values.cluster.name }}-mongodb-0-internal.{{ .Values.cluster.hosted_zone.name }}"
      - "{{ .Values.cluster.name }}-mongodb-1-internal.{{ .Values.cluster.hosted_zone.name }}"
      - "{{ .Values.cluster.name }}-mongodb-2-internal.{{ .Values.cluster.hosted_zone.name }}"
    annotationsList:
      - external-dns.alpha.kubernetes.io/hostname: "{{ .Values.cluster.name }}-mongodb-0-internal.{{ .Values.cluster.hosted_zone.name }}"
      - external-dns.alpha.kubernetes.io/hostname: "{{ .Values.cluster.name }}-mongodb-1-internal.{{ .Values.cluster.hosted_zone.name }}"
      - external-dns.alpha.kubernetes.io/hostname: "{{ .Values.cluster.name }}-mongodb-2-internal.{{ .Values.cluster.hosted_zone.name }}"

persistence:
  enabled: true
  # storageClass: ""      # Inherited from `global:` block
  accessModes:
    - ReadWriteOnce
  size: {{ .Values.cluster.eks.add_ons.mongodb.persistentVolumeSize }}
  annotations: {}
  mountPath: /bitnami/mongodb
  subPath: ""

persistentVolumeClaimRetentionPolicy:
  enabled: true
  whenScaled: Retain
  whenDeleted: Retain

serviceAccount:
  create: true
  name: mongodb
  annotations: {}
  automountServiceAccountToken: true

rbac:
  create: true
  rules:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
        - list
        - watch
        - update
```

### What is the expected behavior?

The `rs.conf` will be created with the given configuration and allow me to access my replicaSet without needing to specify a direct connection.

### What do you see instead?

When first initializing the replicaSet, the pods seem to startup and pass their readiness probes just fine but restart soon after due to there being no configuration I presume. When execing into the primary pod and accessing the DB, I see the following error when trying to view the `rs.conf()`:

```
I have no name!@mongodb-0:/scripts$ mongosh admin --host "mongodb-0.mongodb-headless.mongodb.svc.cluster.local" --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD --tls --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert
Current Mongosh Log ID:	671be19dc5cc31c3b8fe6910
Connecting to:		mongodb://<credentials>@mongodb-0.mongodb-headless.mongodb.svc.cluster.local:27017/admin?directConnection=true&authSource=admin&tls=true&tlsCertificateKeyFile=%2Fcerts%2Fmongodb.pem&tlsCAFile=%2Fcerts%2Fmongodb-ca-cert&appName=mongosh+2.3.2
Using MongoDB:		8.0.1
Using Mongosh:		2.3.2

For mongosh info see: https://www.mongodb.com/docs/mongodb-shell/

------
   The server generated these startup warnings when booting
   2024-10-25T17:38:21.666+00:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
   2024-10-25T17:38:22.555+00:00: For customers running the current memory allocator, we suggest changing the contents of the following sysfsFile
   2024-10-25T17:38:22.555+00:00: For customers running the current memory allocator, we suggest changing the contents of the following sysfsFile
   2024-10-25T17:38:22.555+00:00: We suggest setting the contents of sysfsFile to 0.
   2024-10-25T17:38:22.555+00:00: Your system has glibc support for rseq built in, which is not yet supported by tcmalloc-google and has critical performance implications. Please set the environment variable GLIBC_TUNABLES=glibc.pthread.rseq=0
   2024-10-25T17:38:22.555+00:00: vm.max_map_count is too low
------

admin> rs.conf()
MongoServerError[NotYetInitialized]: no replset config has been received
```
Reading the pod logs doesn't help at all because the `/scripts/replicaSetConfigurationSettings.sh` bash script responsible for setting up this configuration doesn't seem to output anything in the pod logs.

However, when concatenating the `/scripts/replicaSetConfigurationSettings.sh` bash script, I see that my custom configs are being passed at runtime:

```
# load Values.replicaSetConfigurationSettings.configuration into associtive array which makes iterating and string manipulation easy
declare -A desiredRsConf
desiredRsConf[members[0]._id]='0'
desiredRsConf[members[0].host]='mongodb-test-dev-mongodb-0-internal.spectruminternal.blue:27017'
desiredRsConf[members[0].priority]='5'
desiredRsConf[members[1]._id]='1'
desiredRsConf[members[1].host]='mongodb-test-dev-mongodb-1-internal.spectruminternal.blue:27017'
desiredRsConf[members[1].priority]='1'
desiredRsConf[members[2]._id]='2'
desiredRsConf[members[2].host]='mongodb-test-dev-mongodb-2-internal.spectruminternal.blue:27017'
desiredRsConf[members[2].priority]='1'
desiredRsConf[members[3]._id]='3'
desiredRsConf[members[3].arbiterOnly]='true'
desiredRsConf[members[3].buildIndexes]='true'
desiredRsConf[members[3].hidden]='true'
desiredRsConf[members[3].host]='mongodb-arbiter-0.mongodb-arbiter-headless.mongodb.svc.cluster.local:27017'
desiredRsConf[members[3].priority]='0'
```

My guess as to why this is failing, may be because I'm trying to configure the `member[X].host` values? The reason I'm doing this at all is because I cannot access all the nodes in the replicaSet **EXTERNALLY** unless the values are updated to match their advertised hostnames (*externalAccess.service.publicNames*). Without this, I'm only able to connect via direct connections which eliminates the whole purpose of deploying a replicaSet at all. 

### Additional information

If there is any way someone could help me either figure out how to connect to the replicaSet externally without needing to update the `rs.conf`, or how to stop the error provided above that would be much appreciated.
