### ISSUE TITLE
[bitnami/postgresql-ha] Chart does not work properly without setting pg credentials via values or using existingSecret

### ISSUE THREAD

**Issue by davidfrickert** [bitnami/charts#30105]
### Name and Version

bitnami/postgresql-ha 14.2.34

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install postgresql-ha with the provided values
2. Experience the postgres pod on a crash loop because `POSTGRES_POSTGRES_PASSWORD` is not passed to the pod

### Are you using any custom parameters or values?
```yaml
postgresql:
  replicaCount: 1
  database: keycloak
  username: keycloak
  initdbScripts:
    init.sql: |
      \connect keycloak;
      CREATE SCHEMA IF NOT EXISTS keycloak AUTHORIZATION keycloak;
```
### What is the expected behavior?

When not setting an existingSecret or passing the password for postgres user in values, I expect that the chart generates a password and sets `POSTGRES_POSTGRES_PASSWORD` on the postgres pod so that it initializes properly.

### What do you see instead?

When not setting an existingSecret or passing the password for postgres user in values, the chart generates a password for the postgres user but does not set `POSTGRES_POSTGRES_PASSWORD` on the postgres pod - so it crash loops.
This forces me to either set a credential for postgres user via values or use existingSecret, even though these secrets are generated properly if no credentials are passed via values.
