### ISSUE TITLE
[bitnami/mongodb] NodePort service is created with wrong targetPort

### ISSUE THREAD

**Issue by sgops** [bitnami/charts#3011]
**Which chart**:
bitnami/mongodb 8.0.1

**Describe the bug**
I am deploying mongodb chart with the following values:

```
architecture: replicaset
useStatefulSet: false

auth:
  enabled: true
  username: "user"
  rootPassword: "passwordroot"
  password: "passworduser"
  database: "db"

replicaSetName: rs0

replicaCount: 4

schedulerName: "stork"

persistence:
  enabled: true
  storageClass: "my-sc"
  accessModes:
    - ReadWriteOnce
  size: 1Gi

externalAccess:
  enabled: true
  service:
    type: NodePort
    port: 27017
    nodePorts:
      - 30001
      - 30002
      - 30003
      - 30004
```
The NodePort services get created but seem to have the wrong value for targetPort. targetPort is set to NodePort.

That's the relevant section of one of the created NodPort services:

```
spec:
  clusterIP: 10.43.214.213
  externalTrafficPolicy: Cluster
  ports:
  - name: tcp-mongodb
    nodePort: 32001
    port: 27017
    protocol: TCP
    targetPort: 32001
```

https://github.com/bitnami/charts/blob/e76971bc01439c2e1068e4e1cabddd8af3364144/bitnami/mongodb/templates/replicaset/external-access-svc.yaml#L43

This seems to be relevant line. 

`$root.Values.externalAccess.service.port`

could be used here in my opinion.

**Expected behavior**
I'd expect it to be the mongodb port 27017. If I set it manually, I can access mongodb via NodePort service successfully

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
latest v3 / rancher
```

- Output of `kubectl version`:

```
1.17.6
```
