### ISSUE TITLE
[bitnami/mongodb] Troubles Initializing MongoDB ReplicaSet - externalAccess Enabled

### ISSUE THREAD

**Issue by ZachThill** [bitnami/charts#30128]
### Name and Version

bitnami/mongodb:16.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Create a MongoDB replicaSet from scratch with no pre-existing PVCs or PVs, and enable `externalAccess` using any of the three `LoadBalancer` methods.

### Are you using any custom parameters or values?

```yaml
global:
  storageClass: gp2

image:
  debug: true

clusterDomain: cluster.local

commonLabels:
  app: mongodb
commonAnnotations: {}

architecture: replicaset

replicaCount: 3
replicaSetHostnames: true

podLabels: {}
podAnnotations: {}

resources: {}

arbiter:
  enabled: true
  podLabels: {}
  podAnnotations: {}
  resources: {}

tls:
  enabled: true
  mTLS:
    enabled: true
  autoGenerated: true
  mode: requireTLS

automountServiceAccountToken: true

externalAccess:
  enabled: true
  service:
    type: LoadBalancer
    portName: "mongodb"
    ports:
      mongodb: 27017
    publicNames:
      - "test-mongodb-0-internal.my-domain.com"
      - "test-mongodb-1-internal.my-domain.com"
      - "test-mongodb-2-internal.my-domain.com"
    annotationsList:
      - external-dns.alpha.kubernetes.io/hostname: "test-mongodb-0-internal.my-domain.com"
      - external-dns.alpha.kubernetes.io/hostname: "test-mongodb-1-internal.my-domain.com"
      - external-dns.alpha.kubernetes.io/hostname: "test-mongodb-2-internal.my-domain.com"

podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  supplementalGroups: []
  fsGroup: 1001

containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

persistence:
  enabled: true
  # storageClass: ""      # Inherited from `global:` block
  accessModes:
    - ReadWriteOnce
  size: 100Gi
  annotations: {}
  mountPath: /bitnami/mongodb
  subPath: ""

persistentVolumeClaimRetentionPolicy:
  enabled: true
  whenScaled: Retain
  whenDeleted: Retain

serviceAccount:
  create: true
  name: mongodb
  annotations: {}
  automountServiceAccountToken: true

rbac:
  create: true
  rules:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
        - list
        - watch
        - update
```

### What is the expected behavior?

The expected behavior is that the init containers will do their thing, `LoadBalancer` services will be created for each of the pods within the `mongodb` statefulSet, and persistent volumes will be provisioned/attached.  After this, the Mongodb pods will start and execute the `setup.sh` script that is dynamically created/mounted by the helm charts configMap resource. This script will go through the motions of sourcing other bitnami scripts and executing the `entrypoint.sh` script that is a part of the custom image itself. 

As of now, everything stated above is working as expected however there is a similar theme/error that occurs once the scripts try to initialize the primary node (mongodb-0).

The expected behavior after all of this would be that the replicaSet gets initialized and configured, but that's not the case no matter what a user tries.

### What do you see instead?

After the init container finished and the MongoDB container initiated, I followed the debug logs produced by the bitnami scripts:

```console
$ kl mongodb-0  --follow
Defaulted container "mongodb" out of: mongodb, dns-check (init), log-dir (init), generate-tls-certs (init)
mongodb 20:13:44.57 INFO  ==> Advertised Hostname: mongodb-test-dev-mongodb-0-internal.spectruminternal.blue
mongodb 20:13:44.57 INFO  ==> Advertised Port: 27017
realpath: /bitnami/mongodb/data/db: No such file or directory
mongodb 20:13:44.57 INFO  ==> Data dir empty, checking if the replica set already exists
MongoNetworkError: getaddrinfo ENOTFOUND mongodb-1.mongodb-headless.mongodb.svc.cluster.local
mongodb 20:13:44.94 INFO  ==> Pod name matches initial primary pod name, configuring node as a primary
mongodb 20:13:44.95 INFO  ==>
mongodb 20:13:44.95 INFO  ==> Welcome to the Bitnami mongodb container
mongodb 20:13:44.95 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 20:13:44.96 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 20:13:44.96 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
mongodb 20:13:44.96 INFO  ==>
mongodb 20:13:44.96 DEBUG ==> Copying files from /opt/bitnami/mongodb/conf.default to /opt/bitnami/mongodb/conf
mongodb 20:13:44.96 INFO  ==> ** Starting MongoDB setup **
mongodb 20:13:44.97 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 20:13:45.02 INFO  ==> Initializing MongoDB...
mongodb 20:13:45.07 INFO  ==> Writing keyfile for replica set authentication...
mongodb 20:13:45.07 INFO  ==> Deploying MongoDB from scratch...
mongodb 20:13:45.08 DEBUG ==> Starting MongoDB in background...
{"t":{"$date":"2024-10-28T20:13:45.109Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"main","msg":"Applied --setParameter options","attr":{"serverParameters":{"enableLocalhostAuthBypass":{"default":true,"value":true}}}}
about to fork child process, waiting until server is ready for connections.
forked process: 100
child process started successfully, parent exiting
MongoNetworkError: getaddrinfo ENOTFOUND mongodb-test-dev-mongodb-0-internal.spectruminternal.blue
mongodb 20:13:46.17 INFO  ==> Creating users...
mongodb 20:13:46.17 INFO  ==> Creating root user...
Current Mongosh Log ID:	671ff07a08990d919cfe6910
Connecting to:		mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&tls=true&tlsCertificateKeyFile=%2Fcerts%2Fmongodb.pem&tlsCAFile=%2Fcerts%2Fmongodb-ca-cert&tlsAllowInvalidHostnames=true&appName=mongosh+2.3.2
Using MongoDB:		8.0.1
Using Mongosh:		2.3.2

For mongosh info see: https://www.mongodb.com/docs/mongodb-shell/


To help improve our products, anonymous usage data is collected and sent to MongoDB periodically (https://www.mongodb.com/legal/privacy-policy).
You can opt-out by running the disableTelemetry() command.

test> { ok: 1 }
mongodb 20:13:46.85 INFO  ==> Creating user 'DB_Admin'...
test> Current Mongosh Log ID:	671ff07b1d2a580c94fe6910
Connecting to:		mongodb://<credentials>@127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&tls=true&tlsCertificateKeyFile=%2Fcerts%2Fmongodb.pem&tlsCAFile=%2Fcerts%2Fmongodb-ca-cert&tlsAllowInvalidHostnames=true&appName=mongosh+2.3.2
Using MongoDB:		8.0.1
Using Mongosh:		2.3.2

For mongosh info see: https://www.mongodb.com/docs/mongodb-shell/

------
   The server generated these startup warnings when booting
   2024-10-28T20:13:45.159+00:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
   2024-10-28T20:13:45.822+00:00: For customers running the current memory allocator, we suggest changing the contents of the following sysfsFile
   2024-10-28T20:13:45.822+00:00: For customers running the current memory allocator, we suggest changing the contents of the following sysfsFile
   2024-10-28T20:13:45.822+00:00: We suggest setting the contents of sysfsFile to 0.
   2024-10-28T20:13:45.822+00:00: Your system has glibc support for rseq built in, which is not yet supported by tcmalloc-google and has critical performance implications. Please set the environment variable GLIBC_TUNABLES=glibc.pthread.rseq=0
   2024-10-28T20:13:45.822+00:00: vm.max_map_count is too low
------

test> { ok: 1 }
mongodb 20:13:47.51 INFO  ==> Users created
mongodb 20:13:47.52 INFO  ==> Enabling authentication...
mongodb 20:13:47.54 INFO  ==> Configuring MongoDB replica set...
mongodb 20:13:47.54 INFO  ==> Stopping MongoDB...
mongodb 20:13:48.55 DEBUG ==> Starting MongoDB in background...
test> {"t":{"$date":"2024-10-28T20:13:48.582Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"main","msg":"Applied --setParameter options","attr":{"serverParameters":{"enableLocalhostAuthBypass":{"default":true,"value":false}}}}
about to fork child process, waiting until server is ready for connections.
forked process: 272
child process started successfully, parent exiting
MongoServerSelectionError: Server selection timed out after 30000 ms
mongodb 20:14:19.95 INFO  ==> Configuring MongoDB primary node
mongodb 20:14:50.78 WARN  ==> Problem initiating replica set
            request: rs.initiate({"_id":"rs0", "members":[{"_id":0,"host":"mongodb-test-dev-mongodb-0-internal.spectruminternal.blue:27017","priority":5}]})
            response: Current Mongosh Log ID:	671ff09c730f3702adfe6910
Connecting to:		mongodb://<credentials>@127.0.0.1:27017/admin?directConnection=true&serverSelectionTimeoutMS=2000&tls=true&tlsCertificateKeyFile=%2Fcerts%2Fmongodb.pem&tlsCAFile=%2Fcerts%2Fmongodb-ca-cert&tlsAllowInvalidHostnames=true&appName=mongosh+2.3.2
Using MongoDB:		8.0.1
Using Mongosh:		2.3.2

For mongosh info see: https://www.mongodb.com/docs/mongodb-shell/

------
   The server generated these startup warnings when booting
   2024-10-28T20:13:48.635+00:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
   2024-10-28T20:13:49.556+00:00: For customers running the current memory allocator, we suggest changing the contents of the following sysfsFile
   2024-10-28T20:13:49.556+00:00: For customers running the current memory allocator, we suggest changing the contents of the following sysfsFile
   2024-10-28T20:13:49.556+00:00: We suggest setting the contents of sysfsFile to 0.
   2024-10-28T20:13:49.556+00:00: Your system has glibc support for rseq built in, which is not yet supported by tcmalloc-google and has critical performance implications. Please set the environment variable GLIBC_TUNABLES=glibc.pthread.rseq=0
   2024-10-28T20:13:49.556+00:00: vm.max_map_count is too low
------

MongoServerError[InvalidReplicaSetConfig]: No host described in new configuration with {version: 1, term: 0} for replica set rs0 maps to this node
```
As you can see from the output above, we are receiving the following MongoDB error when running the `rs.initiate` command in mongosh:

```
MongoServerError[InvalidReplicaSetConfig]: No host described in new configuration with {version: 1, term: 0} for replica set rs0 maps to this node
```

Looking into this error, I saw many forums and even another person who had this same issue with the bitnami chart before. All of which, stated that the problem was most likely due to the fact that the hostnames you are trying to add to the `rs.conf` are not defined in the `/etc/hosts` file and therefore the pod cannot connect to itself or the other members of the replicaSet.

The chart does support adding `hostAliases` however, I don't know the resolved IPv4 address of my LoadBalancer service until everything is created (See my problem?). With this said, the `setup.sh` bash script should use something like nslookup to resolve the hostname ($MONGODB_ADVERTISED_HOSTNAME), and append it's definition to the `/etc/hosts` file. Doing so would most likely resolve the error defined above.

### Additional information

Here are the links to the forums I found about the error:
https://stackoverflow.com/questions/29211285/errmsg-no-host-described-in-new-configuration-1-for-replica-set-rs0-maps-to
https://dba.stackexchange.com/questions/180189/cant-run-rs-initiate-when-do-mongodb-replication-set

**Comment by ZachThill** [comment]
@jotamartos,
Thank you for taking a look into my issue. After updating my config to match your changes I'm still getting the same error as I was before where the replicaSet would appears to initialize properly, but then the pods would start to fail and restart. Accessing the DB locally after they pods restarted,  I wanted to check the `rs.conf`, and it's as iff the config isn't even being created:

![Screenshot 2024-11-06 at 2 44 11 PM](https://github.com/user-attachments/assets/70a8408f-dd6f-4fd4-95a2-a716f94cf28b)

I still think my original proposed solution may be something to look into. Reading the docs of the helm chart it doesn't seem that `autoDiscovery` and `publicNames` can be used together in tandem nor do I think that will fix the problem.

**Comment by jotamartos** [comment]
Let me try to reproduce the issue again in EKS. I'll update the ticket when having more information.

**Comment by jotamartos** [comment]
Hi, 

I just deployed the solution in a EKS cluster without problems: 

- Launch the solution using this values file

```
architecture: replicaset
replicaCount: 2
externalAccess:
  enabled: true
  service:
    type: LoadBalancer
    publicNames:
      - 'mongodb-0.DOMAIN'
      - 'mongodb-1.DOMAIN'
    annotationsList:
      - external-dns.alpha.kubernetes.io/hostname: mongodb-0.DOMAIN
      - external-dns.alpha.kubernetes.io/hostname: mongodb-1.DOMAIN
```

- Wait for the services to provide you with an IP
- Configure the DNS to point to the internal/external IP of the services
- Wait for the deployment to succeed

Doesn't this work for you? I confirmed that the cluster is fully configured using the `rs.status()` command 

```
 members: [
    {
      _id: 0,
      name: 'mongodb-0.DOMAIN:27017',
      health: 1,
      state: 1,
      stateStr: 'PRIMARY',
      uptime: 180,
      optime: { ts: Timestamp({ t: 1732882212, i: 1 }), t: Long('2') },
      optimeDate: ISODate('2024-11-29T12:10:12.000Z'),
      optimeWritten: { ts: Timestamp({ t: 1732882212, i: 1 }), t: Long('2') },
      optimeWrittenDate: ISODate('2024-11-29T12:10:12.000Z'),
      lastAppliedWallTime: ISODate('2024-11-29T12:10:12.100Z'),
      lastDurableWallTime: ISODate('2024-11-29T12:10:12.100Z'),
      lastWrittenWallTime: ISODate('2024-11-29T12:10:12.100Z'),
      syncSourceHost: '',
      syncSourceId: -1,
      infoMessage: '',
      electionTime: Timestamp({ t: 1732882042, i: 1 }),
      electionDate: ISODate('2024-11-29T12:07:22.000Z'),
      configVersion: 5,
      configTerm: 2,
      self: true,
      lastHeartbeatMessage: ''
    },
    {
      _id: 1,
      name: 'mongodb-arbiter-0.mongodb-arbiter-headless.test.svc.cluster.local:27017',
      health: 1,
      state: 7,
      stateStr: 'ARBITER',
      uptime: 163,
      lastHeartbeat: ISODate('2024-11-29T12:10:20.213Z'),
      lastHeartbeatRecv: ISODate('2024-11-29T12:10:20.213Z'),
      pingMs: Long('0'),
      lastHeartbeatMessage: '',
      syncSourceHost: '',
      syncSourceId: -1,
      infoMessage: '',
      configVersion: 5,
      configTerm: 2
    },
    {
      _id: 2,
      name: 'mongodb-1.DOMAIN:27017',
      health: 1,
      state: 2,
      stateStr: 'SECONDARY',
      uptime: 118,
      optime: { ts: Timestamp({ t: 1732882212, i: 1 }), t: Long('2') },
      optimeDurable: { ts: Timestamp({ t: 1732882212, i: 1 }), t: Long('2') },
      optimeWritten: { ts: Timestamp({ t: 1732882212, i: 1 }), t: Long('2') },
      optimeDate: ISODate('2024-11-29T12:10:12.000Z'),
      optimeDurableDate: ISODate('2024-11-29T12:10:12.000Z'),
      optimeWrittenDate: ISODate('2024-11-29T12:10:12.000Z'),
      lastAppliedWallTime: ISODate('2024-11-29T12:10:12.100Z'),
      lastDurableWallTime: ISODate('2024-11-29T12:10:12.100Z'),
      lastWrittenWallTime: ISODate('2024-11-29T12:10:12.100Z'),
      lastHeartbeat: ISODate('2024-11-29T12:10:20.417Z'),
      lastHeartbeatRecv: ISODate('2024-11-29T12:10:19.111Z'),
      pingMs: Long('0'),
      lastHeartbeatMessage: '',
      syncSourceHost: 'mongodb-0.DOMAIN:27017',
      syncSourceId: 0,
      infoMessage: '',
      configVersion: 5,
      configTerm: 2
    }
  ],
  ok: 1
```
