### ISSUE TITLE
[bitnami/clickhouse] Pod anti affinity topologyKey hostname can't be unset in combination with distributeReplicasByZone

### ISSUE THREAD

**Issue by MeneerVaten** [bitnami/charts#30132]
### Name and Version

bitnami/clickhouse 6.3.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Installed the chart clickhouse bitnami chart with version 6.3.0 with the values described below.

The outcome is the 2 statefulsets because of the 2 shards. With 3 replicas. So we have 6 clickhouse pods running

But the pod anti affinity leads that every pod is scheduled on a different node. I only want the affinity to be based on the shard with the zone.

I saw in the templates that this is coming from the bitnami common templates. But is there a way to get around this?

### Are you using any custom parameters or values?

```yaml
clickhouse:
  shards: 2
  replicaCount: 3
  distributeReplicasByZone: true
  podAntiAffinityPreset: hard
```

### What is the expected behavior?

```yaml
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/component: clickhouse
            app.kubernetes.io/instance: clickhouse
            app.kubernetes.io/name: clickhouse
            shard: '0'
        topologyKey: topology.kubernetes.io/zone
```

### What do you see instead?

```yaml
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/component: clickhouse
            app.kubernetes.io/instance: clickhouse
            app.kubernetes.io/name: clickhouse
        topologyKey: kubernetes.io/hostname
      - labelSelector:
          matchLabels:
            app.kubernetes.io/component: clickhouse
            app.kubernetes.io/instance: clickhouse
            app.kubernetes.io/name: clickhouse
            shard: '0'
        topologyKey: topology.kubernetes.io/zone
```

### Additional information

I saw this PR which makes it possible to get the pod anti affinity based on the zone https://github.com/bitnami/charts/pull/18948. But there is always the common templates pod anti affinity of bitnami common.
