### ISSUE TITLE
[bitnami/mongodb] pase error _helpers - illegal number syntax: "-"

### ISSUE THREAD

**Issue by junkiebev** [bitnami/charts#3014]
**Which chart**:
mongodb v8.01 (latest)

**Describe the bug**
When trying to deploy a mongodb with `externalAccess.enabled:true` and `autoDiscovery.enabled: true`, Helm is throwing the error:
**`Wait helm template failed. Error: parse error in "mongodb/templates/_helpers.tpl": template: mongodb/templates/_helpers.tpl:227: illegal number syntax: "-" : exit status 1**`

**To Reproduce**
Deploy mongodb: 8.01 with the following values:
```
architecture: replicaset
auth:
  enabled: true
  rootPassword: REDACTED
  username: REDACTED
  password: REDACTED
  database: REDACTED
  replicaSetKey: REDACTED
replicaSetName: rs0
replicaCount: 2
rbac:
  create: true
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 2048Mi
externalAccess:
  enabled: true
  service:
    type: LoadBalancer
  autoDiscovery:
    enabled: true
persistence:
  enabled: true
  size: 60Gi
arbiter:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 1024Mi
metrics:
  enabled: true
  service:
    type: LoadBalancer
```

**Expected behavior**
Chart deploys a 3 node replicaset (primary/secondary/arbiter)

**Version of Helm and Kubernetes**:

k8s 1.16.9
helm 3
