### ISSUE TITLE
[bitnami/argocd] PodDisruptionBudget for repo-server has wrong spec

### ISSUE THREAD

**Issue by ktzsolt** [bitnami/charts#30228]
### Name and Version

bitnami/argocd 7.0.21

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The problem with PodDisruptionBudget for repo-server is that in the spec the selector is `app.kubernetes.io/component: repoServer` 
https://github.com/bitnami/charts/blob/f6e62be0823be6af54b6cad537adf03a91630e0d/bitnami/argo-cd/templates/repo-server/pdb.yaml#L27

while the label selector for the repo server deployment is `app.kubernetes.io/component: repo-server`
https://github.com/bitnami/charts/blob/f6e62be0823be6af54b6cad537adf03a91630e0d/bitnami/argo-cd/templates/repo-server/deployment.yaml#L24

thus getting the "No matching pods found" event and degraded status for the repo server PDB.

Changing the PDB spec to repo-server fixes the problem, although the ArgoCD Application that manages ArgoCD itself will be out of sync.

Also, other labels have a mismatch of `repo-server` vs `repoServer`.

### What do you see instead?

`repoServer` instead of `repo-server` for labels.

### Additional information

This degradation surfaced in the application version change from 2.12.6 to 2.13.0 but the label mismatch issue was present from the beginning so while in the chart bitnami/argocd 7.0.20 pdb was not in degraded status but it was also reporting `currentHealthy: 0` 
```yaml
status:
  conditions:
    - lastTransitionTime: '2024-11-05T17:10:15Z'
      message: ''
      observedGeneration: 1
      reason: InsufficientPods
      status: 'False'
      type: DisruptionAllowed
  currentHealthy: 0
  desiredHealthy: 0
  disruptionsAllowed: 0
  expectedPods: 0
  observedGeneration: 1
```

The PDB gets degraded when installing bitnami/argocd 7.0.21 chart probably because the PDB CRD health check upgrade developments that are in the 2.13.0 application version: https://github.com/argoproj/argo-cd/pull/19826

Changing the selector in the PDB to repo-server as mentioned above will make the PDB not degraded and report `currentHealthy: 1`:
```yaml
status:
  conditions:
    - lastTransitionTime: '2024-11-05T17:28:14Z'
      message: ''
      observedGeneration: 2
      reason: SufficientPods
      status: 'True'
      type: DisruptionAllowed
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 2
```
