### ISSUE TITLE
Automatic datasource activation upon creation fails, requiring manual "Save & Test" for plugin connection

### ISSUE THREAD

**Issue by jcapote22** [bitnami/charts#30245]
### Name and Version

bitnami/grafana-operator-4.7.4

### What architecture are you using?

None

### What steps will reproduce the bug?

1- Deploy Grafana with Grafana Operator version 5.14.0-debian-12-r0.
2- Create a datasource resource in Kubernetes.
3- Observe the initial error "Query error: An error occurred within the plugin" when accessing the datasource in the Grafana UI.
4- Manually click "Save & Test" in the UI to establish the connection.

### Are you using any custom parameters or values?

```yaml
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: elasticsearch-peru
  namespace: grafana-operator-system
spec:
  valuesFrom:
    - targetPath: "basicAuthUser"
      valueFrom:
        secretKeyRef:
          name: "extra-credentials"
          key: "user"
    - targetPath: "secureJsonData.basicAuthPassword"
      valueFrom:
        secretKeyRef:
          name: "extra-credentials"
          key: "pass"
  instanceSelector:
    matchLabels:
      grafana: default
  datasource:
    access: proxy
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: false
      index: "banco-pe-omni*"
    secureJsonData:
      "basicAuthPassword": ${pass}
    name: ElasticBFPE
    type: elasticsearch
    url: https://internal url
    basicAuth: true
    basicAuthUser: ${user}
```

### What is the expected behavior?

Ideally, the Grafana Operator should automatically connect and validate each datasource upon creation, removing the need for manual intervention. This would significantly improve workflow efficiency, especially when deploying multiple datasources.

### What do you see instead?

Query error: An error occurred within the plugin

![image](https://github.com/user-attachments/assets/d99e5c04-cb8a-49dd-89c5-630db2163fdb)

### Additional information

When creating datasources in Grafana via Kubernetes resources, each datasource appears correctly in the Grafana UI. However, accessing the datasource shows the following error message:

"Query error: An error occurred within the plugin"
![image](https://github.com/user-attachments/assets/180db145-d1bf-47ee-b254-94e65c6c08fe)

Despite this initial error, the datasource successfully connects after manually clicking the "Save & Test" button in the UI. This process is problematic, especially when creating multiple datasources, as it requires manually opening each one and pressing "Save & Test" to establish the connection.

![image](https://github.com/user-attachments/assets/4eb1b813-2bf2-468e-b924-e8011787cd8d)

![image](https://github.com/user-attachments/assets/f07530e3-7f1d-47bc-96d6-856346330842)
