### ISSUE TITLE
Feature request: Grafana notifiers

### ISSUE THREAD

**Issue by alextes** [bitnami/charts#3031]
**Which chart**:
Grafana 3.0.1

**Is your feature request related to a problem? Please describe.**
Recreating the resource I have to recreate alert notification channels by hand.

**Describe the solution you'd like**
Declarative alert notification channels. The stable repo has a grafana chart that supports its under the name notifiers: https://github.com/helm/charts/tree/master/stable/grafana

Thanks for all the charts 🙏 !

**Comment by rafariossaa** [comment]
Hi @alextes ,
  Thanks for the suggestion, I am opening an internal task to study your request.
  We will come back as soon as we have news.
  In any case, if you want to send a PR we will be glad to review and merge it.


Best regards,

**Comment by alextes** [comment]
I'm no pro with Helm and a bit overburdened the next month but after that I could take a stab at it.

It's similar to what is done with the dashboard provider but simpler. In steps:
* create a configmap that looks something like:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-notification-channels
data:
  alert-notification-channels.yaml: |-
    notifiers:
      - name: opsgenie
        type: opsgenie
        uid: opsgenie
        # either
        org_id: 1
        is_default: true
        send_reminder: false
        frequency: 10m
        disable_resolve_message: false
        # See `Supported Settings` section for settings supporter for each
        # alert notification type.
        settings:
          apiKey: $API_KEY
          apiUrl: https://api.eu.opsgenie.com/v2/alerts
          autoClose: true
          overridePriority: false
```
* define the configmap as a volume for the grafana deployment
```yaml
volumes:
	- name: alert-notification-channels
  	  configMap:
   	    name: alert-notification-channels
```

* mount the volume to the right dir for grafana:
```yaml
volumeMounts:
  - name: alert-notification-channels
    mountPath: /opt/bitnami/grafana/conf/provisioning/notifiers
```
