### ISSUE TITLE
[bitnami/airflow] kubernetesexecutor worker dies after chart update from 20.0.2 -> 21.4.0

### ISSUE THREAD

**Issue by ebizboy** [bitnami/charts#30314]
### Name and Version

bitnami/airflow 21.4.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

on EKS 1.31 bitnami/airflow chart 20.0.2  upgrade to 21.4.0 with kubernetesexecutor setting

### Are you using any custom parameters or values?
```yaml
executor: KubernetesExecutor

redis:
  enabled: false

rbac:
  create: true

 worker:
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  tolerations:
    - key: airflow
      operator: Exists
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
          - key: eks.amazonaws.com/capacityType
            operator: In
            values:
            - ON_DEMAND
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
          - key: karpenter.sh/nodepool
            operator: In
            values:
            - airflow
          - key: karpenter.sh/capacity-type
            operator: In
            values:
            - on-demand
  resources:
    requests:
      cpu: 150m
      memory: 350Mi
    limits:
      cpu: 500m
      memory: 350Mi
  podAnnotations:
    karpenter.sh/do-not-disrupt: "true"
```
### What is the expected behavior?

works as usual

### What do you see instead?
```
worker fails with initcontainer  k8s-executor-init-config   terminated Error (exit code: 1)   docker.io/bitnami/airflow:2.10.2-debian-12-r8
load-dags waiting
```
