### ISSUE TITLE
[discourse] DISCOURSE_SMTP_ENABLE_START_TLS not work

### ISSUE THREAD

**Issue by wszgrcy** [bitnami/charts#30410]
### Name and Version

bitnami/discourse:15.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?
I delete all volume before install
I set `extraEnvVars` both `discourse` and `sidekiq`
```
  extraEnvVars:
   - name: DISCOURSE_SMTP_ENABLE_START_TLS
     value: 'false'
```
I can find `DISCOURSE_SMTP_ENABLE_START_TLS=false` in `env`

but 
![image](https://github.com/user-attachments/assets/8d3441ee-73a9-4327-90c3-62fd7eb5202b)

![image](https://github.com/user-attachments/assets/7605e640-004b-4b72-80aa-d2ef1270ea61)

### Are you using any custom parameters or values?
```yml
discourse:
  extraEnvVars:
   - name: DISCOURSE_SMTP_ENABLE_START_TLS
     value: 'false'



sidekiq:

  extraEnvVars:
   - name: DISCOURSE_SMTP_ENABLE_START_TLS
     value: 'false'
```

### What do you see instead?

enable_starttls_auto | true
