### ISSUE TITLE
Error starting bitnami postgres container

### ISSUE THREAD

**Issue by robcresswell** [bitnami/charts#30415]
### Name and Version

bitnami/postgres 16.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Seeing 

```
/opt/bitnami/scripts/libpostgresql.sh: line 395: POSTGRESQL_REPLICATION_USE_PASSFILE: unbound variable
```

I can post more specifics later, a bit time constrained, but this is a very minimal env

### What do you see instead?

I'd expect the container to start

**Comment by dmavrommatis** [comment]
same for `postgres:15.8.0` I had to pin `15.7.0` to get around this error.

**Comment by honcharof** [comment]
the same for 16.0.1

**Comment by benjaminch** [comment]
Same goes for `16.4.0`

**Comment by vikas-toptal** [comment]
Same goes for 14

**Comment by PSanetra** [comment]
Related: https://github.com/bitnami/containers/issues/74804

**Comment by PSanetra** [comment]
I am using this as a quick fix:

```yaml
primary:
  extraEnvVars:
    - name: POSTGRESQL_REPLICATION_USE_PASSFILE
      value: "false"
readReplicas:
  extraEnvVars:
    - name: POSTGRESQL_REPLICATION_USE_PASSFILE
      value: "false"
```
