### ISSUE TITLE
Use  private git repository in Airflow

### ISSUE THREAD

**Issue by mohamedih** [bitnami/charts#3043]
Hi,

I'm using Airflow Bitnami chart from IBM Cloud. I'm trying to connect to private git repository. 

I'm creating ssh secret like this:
`kubectl create secret generic git-ssh-key-secret --from-file=id_ed25519=.ssh/id_ed25519 --from-file=known_hosts=.ssh/known_hosts --from-file=id_id_ed25519.pub=.ssh/id_ed25519.pub`

I configured the secret name into airflow.gitCloneContainer.extraEnvVarsSecret
I see it correctly reflected in the pod. 
but for some reason i see the blow error in the container log 

> kubectl logs airflow34-e050-4f-web-89c9fdfc5-pvs48 -c git-clone-repository -n ews-airflow                                                            
Cloning into '/dags'...
No user exists for uid 1001
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

Kindly note i have tested the ssh key from my local and it works. Could you please advice ?

**Comment by dani8art** [comment]
Hi @mohamedih thank for opening the issue.

I would say you need to set volumes and volumeMounts instead, since `extraEnvVarsSecret` will only expose the secret fields as env vars. Could you try this?

```
airflow:
  gitCloneContainer:
    extraVolumeMounts:
      - mountPath: "./ssh"
         name: ssh-key
         readOnly: true
airflow:
  web:
    extraVolumes:
      - name: ssh-keys
        secret:
          secretName: git-ssh-key-secret
```

BTW, I would say you will need the `./ssh/config` as well.
