### ISSUE TITLE
[bitnami/airflow] Airflow Kubernetes Worker Pod Does Not Terminate After Job Completion

### ISSUE THREAD

**Issue by ebizboy** [bitnami/charts#30442]
### Name and Version

bitnami/airflow 21.8.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. KubernetesWorker, with sync git dag option
2. Just run

### Are you using any custom parameters or values?
```yaml
dags:
  enabled: true
  repositories:
  - repository: https://test:github_pat_key@github.com/test/airflow-dags.git
    name: "airflow-dags"
    branch: main

defaultInitContainers:
  loadDAGsPlugins:
    resources:
      requests:
        memory: "200Mi"
      limits:
        memory: "200Mi"

defaultSidecars:
  syncDAGsPlugins:
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "100Mi"
```
### What is the expected behavior?

The Pod should terminate properly once the KubernetesWorker job is completed

### What do you see instead?

sync-dags container still running forever
