### ISSUE TITLE
[bitnami/postgresql-ha] Helm chart templates field "enabled" in podSecurityContext of pgpool init container. 

### ISSUE THREAD

**Issue by caspereijkens** [bitnami/charts#30465]
### Name and Version

bitnami/postgresql-ha

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Enable `.Values.pgpool.tls.enabled`
2. That will activate 
```yaml
securityContext: {{- .Values.volumePermissions.podSecurityContext | toYaml | nindent 12 }}
```
In the pgpool deployment.
3. This leads to the field `enabled` being included in securityContext, which is of course not allowed by the Pod resource definition.

### What is the expected behavior?
```yaml
        securityContext:
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
          seccompProfile:
            type: RuntimeDefault
```
### What do you see instead?
```yaml
        securityContext:
          **enabled: true**
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
          seccompProfile:
            type: RuntimeDefault
```
