### ISSUE TITLE
With  configuring tls certificate can't open "Manage account" page

### ISSUE THREAD

**Issue by BohdanBohatov** [bitnami/charts#30473]
### Name and Version

[bitnami/keycloak]  24.0.4

### What architecture are you using?

None

### What steps will reproduce the bug?

What I did:

1. Env - aws
2. Installed nginx ingress for aws
3. Installed cert-manager "helm install   cert-manager jetstack/cert-manager   --namespace cert-manager   --create-namespace   --version v1.16.1   --set crds.enabled=true"
4. Installed issuer from cert-manger guide
5. Added ingress 

Expected page is situated in upper-rigth corner, click {user-name} first link

### Are you using any custom parameters or values?

`--version 24.0.4 --namespace keycloak-user-3-ns`

```
global:
  defaultStorageClass: keycloak-user-3-storage

extraVolumes:
  - name: efs-storage
    persistentVolumeClaim:
      claimName: keycloak-pv-claim

extraVolumeMounts:
    - name: efs-storage
      mountPath: /opt/bitnami/keycloak/themes

auth:
  adminUser: user
  adminPassword: {password}

postgresql:
  volumePermissions:
    enabled: true
  auth:
    password: {password}
    postgresPassword: {password}
    username: "db_user"

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: "{url}"
  tls: true
  annotations: {
    "cert-manager.io/issuer" : "keycloak-production",
    "kubernetes.io/tls-acme" : "true"
  }

```

### What is the expected behavior?

I can open "Manage account" page.

### What do you see instead?

I got 403 error to this url https://{my-url}/realms/master/protocol/openid-connect/login-status-iframe.html/init?client_id=account-console&origin=https%3A%2F%2F{my-url}

### Additional information

It works without TLS certificate. I belive this is not a bug, but I couldn't find any information in internet and in documentation why I got this issue.

Admin page also works well, only manage accout is not working.
