### ISSUE TITLE
[bitnami/wildfly] extraEnvVarsSecret not taken into account

### ISSUE THREAD

**Issue by jdaln** [bitnami/charts#30477]
### Name and Version

bitnami/wildfly 22.0.2

### What architecture are you using?

None

### What steps will reproduce the bug?

Default deployment with values.yaml below and the following secrets for testing (not base64 but kubernetes converts automatically for our testing):
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: wildfly-secret-envvars
  namespace: i2b2
type: Opaque
stringData:
  WILDFLY_PASSWORD: "3FeiW8945SDhksafeo@FG" 
  WILDFLY_USERNAME: admin
```

### Are you using any custom parameters or values?

```yaml
wildfly:
  nameOverride: "test-wildfly"
  logLevel: warn

  service:
    type: ingress

  extraEnvVarsSecret: "wildfly-secret-vars" <------ here

  ingress:
    ingressClassName: "nginx"
    pathType: Prefix
    hostname: wildfly.dev.example.com
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    tls:
      - hosts:
        - wildfly.dev.example.com
        secretName: wildfly.dev.example.com-tls 

  mgmtIngress:
    ingressClassName: "nginx"
    pathType: Prefix
    hostname: mgmt.wildfly.dev.example.com
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    tls:
      - hosts:
        - mgmt.wildfly.dev.example.com
        secretName: mgmt.wildfly.dev.example.com-tls  
```

### What is the expected behavior?

I would expect extraEnvVarsSecret password and username to be taken into account

### What do you see instead?

A password is generated as per default behavior and username is also default

### Additional information

- https://github.com/bitnami/charts/blob/main/bitnami/wildfly/templates/secrets.yaml#L17 should have a condition to consider extraEnvVarsSecret
- https://github.com/bitnami/charts/blob/ad308c2fcc162182933038eeff9a8880c0923991/bitnami/wildfly/templates/deployment.yaml#L127-L129 should be able to take from  extraEnvVarsSecret
