### ISSUE TITLE
Deploying Matomo chart in a sub-path

### ISSUE THREAD

**Issue by mHaderIBM** [bitnami/charts#30498]
### Name and Version

bitnami/matomo 9.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am trying to deploy this chart to our Kubernetes cluster (AWS) and want to expose it through a sub-path of our existing domain. Sorry if this is not the right place or if a bug is not the right template here. But I feel like this is not that much of an exotic use-case and it should be possible to tell the chart (or matomo???) which base-path it should have.

### Are you using any custom parameters or values?

```yaml
# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

global:
  defaultStorageClass: "<storage-class>"

replicaCount: 1
matomoUsername: <example>-mtm
matomoPassword: "<pw>"
matomoWebsiteName: <example-test>
matomoWebsiteHost: https://example.org/matomo

persistence:
  enabled: true
  storageClass: "<storage-class>"
  size: 8Gi
  
resourcesPreset: "small"

service:
  ## @param service.type Kubernetes Service type
  ##
  type: ClusterIP
cronjobs:
  taskScheduler:
    enabled: false
  archive:
    enabled: false

## Configure the ingress resource that allows you to access the
## Matomo installation. Set up the URL
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: "example.org"
  path: /matomo(/|$)(.*)
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/matomo(/|$)(.*) /$2 break;
      proxy_set_header X-Forwarded-Prefix /matomo;
  # nginx.ingress.kubernetes.io/x-forwarded-prefix: /matomo
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
  #   nginx.ingress.kubernetes.io/configuration-snippet: |
  #     more_set_headers "X-Forwarded-Uri: /matomo";

  ## @param ingress.tls Enable TLS configuration for the hostname defined at ingress.hostname parameter
  ## TLS certificates will be retrieved from a TLS secret with name: {{- printf "%s-tls" .Values.ingress.hostname }}
  ## You can use the ingress.secrets parameter to create this TLS secret or relay on cert-manager to create it
  ##
  tls: true
  selfSigned: false

  ## @param ingress.extraTls The tls configuration for additional hostnames to be covered with this ingress record.
  ## see: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
  ## extraTls:
  ## - hosts:
  ##     - matomo.local
  ##   secretName: matomo.local-tls
  ##
  extraTls:
    - hosts:
        - <example.org>
      secretName: example-org-tls

mariadb:
  enabled: true
  architecture: standalone
  auth:
    rootPassword: "<root-pw>"
  primary:
    persistence:
      enabled: true
      storageClass: "<storage-class"
    resourcesPreset: "small"

networkPolicy:
  enabled: false

extraEnvVars: 
  - name: MATOMO_PROXY_URI_HEADER
    value: "1"
  - name: MATOMO_PROXY_CLIENT_HEADERS
    value: "HTTP_X_FORWARDED_FOR,HTTP_CLIENT_IP,HTTP_LB_FORWARDED_FOR,HTTP_WAF_FORWARDED_FOR"
  - name: MATOMO_PROXY_HOST_HEADERS
    value: "HTTP_X_FORWARDED_FOR"
  - name: MATOMO_TRUSTED_HOSTS
    value: "example.org,example.org/matomo"
  - name: MATOMO_ENABLE_FORCE_SSL
    value: "yes"
  - name: MATOMO_ENABLE_ASSUME_SECURE_PROTOCOL
    value: "yes"
  - name: MATOMO_ENABLE_PROXY_HEADERS
    value: "1"
  - name: MATOMO_URL
    value: "https://example.org/matomo"
  - name: MATOMO_INSTALL_SUBDIRECTORY
    value: "/matomo"

initContainers:
  - name: custom-post-init-script
    image: bitnami/matomo
    command:
      - /bin/sh
      - docker-entrypoint-init.d/setup-reverse-proxy.sh
    volumeMounts:
      - name: matomo-data
        mountPath: /bitnami/matomo
      - name: custom-postinit
        mountPath: /docker-entrypoint-init.d

customPostInitScripts:
  setup-reverse-proxy.sh: |
    #!/bin/bash

    CONFIG_FILE="/bitnami/matomo/config/config.ini.php"
    SCRIPT_START="#Generated by setup-reverse-proxy.sh\n"
    SCRIPT_END="#End of setup-reverse-proxy.sh"

    # Variables
    FORCE_SSL="force_ssl = 1\n"
    ASSUME_SECURE_PROTOCOL="assume_secure_protocol = 1\n"
    PROXY_CLIENT_HEADERS="proxy_client_headers[] = HTTP_X_FORWARDED_FOR\nproxy_client_headers[] = HTTP_CLIENT_IP\nproxy_client_headers[] = HTTP_LB_FORWARDED_FOR\nproxy_client_headers[] = HTTP_WAF_FORWARDED_FOR\n"
    PROXY_HOST_HEADERS="proxy_host_headers[] = HTTP_X_FORWARDED_HOST\n"
    PROXY_URI_HEADER="proxy_uri_header = 1\n"

    if [ ! -e "$CONFIG_FILE" ]; then
        echo "Config-File does not yet exist. Will wait for post-init"
        exit 0
    fi

    if ! grep -q "#Generated by setup-reverse-proxy.sh" "$CONFIG_FILE"; then
       echo "Executing setup-reverse-proxy.sh"
       sed -i "s/\[General\]/[General]\n$SCRIPT_START$FORCE_SSL$ASSUME_SECURE_PROTOCOL$PROXY_CLIENT_HEADERS$PROXY_HOST_HEADERS$PROXY_URI_HEADER$SCRIPT_END/" "$CONFIG_FILE"
    else
       echo "Not executing setup-reverse-proxy.sh since already executed"
    fi
```

### What is the expected behavior?

I would expect the page to be available through https://example.org/matomo.

### What do you see instead?

It loads only the base index.php. Any other file required by the applications cannot be loaded, because Matomo always falls back to the same base URL (example.org) rather than the sub-path. 

<img width="356" alt="image" src="https://github.com/user-attachments/assets/ae0a0d37-6f2b-4f96-b3c5-5a2503f7fee5">

### Additional information

I did my share of crawling through various posts on google/stackoverflow/github-issues. As you can see by my values.yaml, I tried a lot. I am aware of the https://matomo.org/faq/how-to-install/faq_98/ page and did try that. Either matomo ignores the settings or I am passing them in wrong.  I did also find this issue here (https://github.com/bitnami/charts/issues/20228) and tried to use it, but the behaviour does not change. It keeps requesting the base-url instead of the sub-path. Found a similar issue in the matomo repo, but it just references back to the FAQ (https://github.com/matomo-org/matomo/issues/12562)
Thanks for your help.
