### ISSUE TITLE
Add Wordpress custom plugins and themes

### ISSUE THREAD

**Issue by pedrodsrodrigues** [bitnami/charts#30537]
### Name and Version

bitnami/wordpress 24.0.4

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. The environment I'm using consists mainly of the following:
- EKS
- Terraform
- Helm
  - `bitnami/wordpress` helm chart
    - Repository: `https://charts.bitnami.com/bitnami`
    - Chart: `wordpress`
    - Version: `24.0.4`
  - `ingress-nginx` (`https://kubernetes.github.io/ingress-nginx`) helm chart
2. I have a manifest to create the ingress, instead of using `bitnami/wordpress`'s helm chart, since I need to give a specific `secretName` and I don't see any way where I can do that through the `values.yml` file
3. I'm installing the `helm_release` through `Terraform`, and everything works just fine. I'm able to have the deployment up and running.
```
resource "helm_release" "test" {
  create_namespace = true
  name             = "test"
  chart            = "wordpress"
  namespace        = local.commons.namespace
  version          = "24.0.4"
  repository       = "https://charts.bitnami.com/bitnami"

  values = [
    templatefile(
      "${path.module}/helm/test/values.yml",
      merge(local.commons, local.applications.test, {
        app_image = "${data.aws_ecr_repository.test_provider.repository_url}:latest"
      })
    )
  ]
}
```

### Are you using any custom parameters or values?

```
commonLabels:
  app: "test-wordpress"
clusterDomain: "${site_domain}"
image:
  registry: docker.io
  repository: bitnami/wordpress
  tag: 6.5.3-debian-12-r6
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: true
wordpressUsername: "${wp_username}"
wordpressPassword: "${wp_password}"
wordpressEmail: "${wp_email}"
wordpressFirstName: "First"
wordpressLastName: "Last"
wordpressBlogName: "${site_name}"
wordpressTablePrefix: ""
wordpressScheme: https
wordpressSkipInstall: false
wordpressPlugins: none
allowEmptyPassword: false
replicaCount: 1
# extraVolumeMounts:
# - mountPath: /bitnami/wordpress
#   name: wordpress-data
#   subPath: wordress
initContainers:
- name: plugins-and-themes
  image: ${app_image}
  imagePullPolicy: Always
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
  command: ['sh', '-c', 'echo "wordpress: " && (ls -l /bitnami/wordpress || true) && echo "wp-content: " && (ls -l /bitnami/wordpress/wp-content || true) && echo "plugins: " && (ls -l /bitnami/wordpress/wp-content/plugins || true) && mkdir -p /bitnami/wordpress/wp-content/plugins && cp -RT /wp-app/wp-content/plugins/ /bitnami/wordpress/wp-content/plugins && echo "plugins after copy: " && ls /bitnami/wordpress/wp-content/plugins']
  # command: ['sh', '-c', 'echo "wordpress: " && (ls -l /bitnami/wordpress || true) && echo "wp-content: " && (ls -l /bitnami/wordpress/wp-content || true) && echo "plugins: " && (ls -l /bitnami/wordpress/wp-content/plugins || true)']
  # command: ['sh', '-c', 'mkdir -p /bitnami/wordpress/wp-content && cp -RT /wp-app/wp-content/ /bitnami/wordpress/wp-content && ls /bitnami/wordpress/wp-content/plugins']
  # command: ['sh', '-c', 'cp -r /var/www/html/wp-content /bitnami/wordpress/wp-content']
  volumeMounts:
  - mountPath: /bitnami/wordpress
    name: wordpress-data
    subPath: wordress
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: "hard"
  key: "kubernetes.io/arch"
  values:
  - "arm64"
tolerations:
- key: "arch"
  operator: "Equal"
  value: "amd64"
  effect: "NoExecute"
resourcesPreset: "micro"
service:
  type: ClusterIP
  ports:
    http: 80
    https: 443
  httpsTargetPort: https
  sessionAffinity: None
  sessionAffinityConfig: {}
  clusterIP: ""
  externalTrafficPolicy: Cluster
  extraPorts: []
persistence:
  enabled: false
autoscaling:
  enabled: false
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
mariadb:
  enabled: false
externalDatabase:
  host: "${db_host}"
  port: 3306
  user: "${db_user}"
  password: "${db_password}"
  database: "${db_name}"
```

### What is the expected behavior?

Being able to see my plugins (in the filesystem, and browser). I expected something like the following, inside the `wordpress` container, when executing `ls /bitnami/wordpress/wp-content/plugins`:
```
I have no name!@portal-wordpress-666fb64d6b-45b24:/$ ls /bitnami/wordpress/wp-content/plugins
advanced-custom-fields-pro test-simulators google-reviews gravityforms
```

### What do you see instead?

Inside the `wordpress` container:
```
I have no name!@portal-wordpress-666fb64d6b-45b24:/$ ls /bitnami/wordpress/wp-content/plugins
akismet  all-in-one-seo-pack  all-in-one-wp-migration  amp  google-analytics-for-wordpress  hello.php  index.php  jetpack  simple-tags  w3-total-cache  wp-mail-smtp
```

### Additional information

I have been the whole day trying to add custom plugins and themes, and reading docs and issues regarding this topic, but to no avail. I have noticed I'm far from being the only one with difficulties regarding adding custom plugins and themes, so it would be great to have a practical example of how to do it... I hope this issue will be solved and that it will help other people with the same problem. I know I put more information than is probably needed, but I think it can help debug the issue and maybe even help others who are in the same situation.

**Logs**
- I don't see any log that can be a real issue, in the `wordpress` container
- The `metrics` container returns the following:
```
time=2024-11-20T00:30:23.184Z level=INFO source=/bitnami/blacksmith-sandox/apache-exporter-1.0.9/src/github.com/Lusitaniae/apache_exporter/apache_exporter.go:66 msg="Starting apache_exporter" version="(version=1.0.9, branch=HEAD, revision=82e6a80a5b4e232b3d0f9263f39c4e1d28ed204c)"
time=2024-11-20T00:30:23.184Z level=INFO source=/bitnami/blacksmith-sandox/apache-exporter-1.0.9/src/github.com/Lusitaniae/apache_exporter/apache_exporter.go:67 msg="Build context" build="(go=go1.22.9, platform=linux/arm64, user=root@1967476c05c2, date=20241106-23:52:32, tags=netgo)"
time=2024-11-20T00:30:23.184Z level=INFO source=/bitnami/blacksmith-sandox/apache-exporter-1.0.9/src/github.com/Lusitaniae/apache_exporter/apache_exporter.go:68 msg="Collect metrics from" scrape_uri=http://status.localhost:8080/server-status/?auto
time=2024-11-20T00:30:23.184Z level=INFO source=/bitnami/blacksmith-sandox/apache-exporter-1.0.9/pkg/mod/github.com/prometheus/exporter-toolkit@v0.13.0/web/tls_config.go:347 msg="Listening on" address=[::]:9117
time=2024-11-20T00:30:23.184Z level=INFO source=/bitnami/blacksmith-sandox/apache-exporter-1.0.9/pkg/mod/github.com/prometheus/exporter-toolkit@v0.13.0/web/tls_config.go:350 msg="TLS is disabled." http2=false address=[::]:9117
time=2024-11-20T00:30:35.923Z level=ERROR source=/bitnami/blacksmith-sandox/apache-exporter-1.0.9/src/github.com/Lusitaniae/apache_exporter/collector/collector.go:567 msg="Error scraping Apache" err="error scraping Apache: Get \"http://status.localhost:8080/server-status/?auto\": dial tcp 127.0.0.1:8080: connect: connection refused"
```
- The `initContainer` called `prepare-base-dir` doesn't show anything special
- The `initContainer` I created, `plugins-and-themes`, shows the following:
```
wordpress: 
total 0
wp-content: 
ls: /bitnami/wordpress/wp-content: No such file or directory
plugins: 
ls: /bitnami/wordpress/wp-content/plugins: No such file or directory
plugins after copy: 
advanced-custom-fields-pro
test-simulators
google-reviews
gravityforms
```

**Comment by dgomezleon** [comment]
Hi @pedrodsrodrigues,

Have you tried with `wordpressPlugins` parameter?

For example, to install `google-reviews` and `gravityforms` I used `wordpressPlugins: "wp-reviews-plugin-for-google,wp-tools-gravity-forms-divi-module"`. I think they are the correct plugins, but please double-check them (you can use `wp plugin search NAME` command to figure out the exact name).

I hope it helps

**Comment by pedrodsrodrigues** [comment]
> Hi @pedrodsrodrigues,
> 
> Have you tried with `wordpressPlugins` parameter?
> 
> For example, to install `google-reviews` and `gravityforms` I used `wordpressPlugins: "wp-reviews-plugin-for-google,wp-tools-gravity-forms-divi-module"`. I think they are the correct plugins, but please double-check them (you can use `wp plugin search NAME` command to figure out the exact name).
> 
> I hope it helps

Hello

Thanks for the input. Unfortunately I don't think that parameter solves my problem, since I have custom plugins and those can't be activated through `wordpressPlugins` unless I'm able to put them inside the container first. Using `wordpressPlugins` seems like the next step.

**Comment by dgomezleon** [comment]
Hi @pedrodsrodrigues ,

What script are you using for loading those plugins? Do you have any custom plugin example so I could give a try?

Alternatively, you could also customize the container image to ship all the required artifacts for your use case.

**Comment by dgomezleon** [comment]
Hi @pedrodsrodrigues,

Now I see this particular scenario.

Try this: 

```
initContainers:
- name: plugins-and-themes
  image: ${app_image}
  imagePullPolicy: Always
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
  command: ['sh', '-c', 'cp -r --preserve=mode /wp-app/wp-content/plugins/* /emptydir/app-base-dir/wp-content/plugins/ && echo "plugins after copy: " && ls /emptydir/app-base-dir/wp-content/plugins/']
  volumeMounts:
  - name: empty-dir
    mountPath: /emptydir
```

Note that we use the emptydir volume. This is based on how the [deployment](https://github.com/bitnami/charts/blob/1cacaa54741ef79e47c8ca402ad97c9dbaa5103d/bitnami/wordpress/templates/deployment.yaml#L130-L159) works.

I was able to persist a file using that. Add also the copy for themes if needed.

I hope it helps

**Comment by pedrodsrodrigues** [comment]
Hi @dgomezleon ,

Sorry for such a delay.

That seems like it could be what I need, but I can't test it right now.

I ended up going with one of your suggestions (`you could also customize the container image to ship all the required artifacts for your use case.`) and it's working just fine regarding this issue in particular. I will be back in the future to try what you just suggested, when I have the time.

Thank you very much for the help. See you soon

**Comment by pedrodsrodrigues** [comment]
> Hi @pedrodsrodrigues,
> 
> Now I see this particular scenario.
> 
> Try this:
> 
> ```
> initContainers:
> - name: plugins-and-themes
>   image: ${app_image}
>   imagePullPolicy: Always
>   securityContext:
>     runAsNonRoot: true
>     runAsUser: 1001
>     runAsGroup: 1001
>   command: ['sh', '-c', 'cp -r --preserve=mode /wp-app/wp-content/plugins/* /emptydir/app-base-dir/wp-content/plugins/ && echo "plugins after copy: " && ls /emptydir/app-base-dir/wp-content/plugins/']
>   volumeMounts:
>   - name: empty-dir
>     mountPath: /emptydir
> ```
> 
> Note that we use the emptydir volume. This is based on how the [deployment](https://github.com/bitnami/charts/blob/1cacaa54741ef79e47c8ca402ad97c9dbaa5103d/bitnami/wordpress/templates/deployment.yaml#L130-L159) works.
> 
> I was able to persist a file using that. Add also the copy for themes if needed.
> 
> I hope it helps

Hi @DzeryCZ ,

It worked! I ended up having everything I wanted in the correct place. Thank you so much for your help!

**Comment by cheeyeelim** [comment]
I had a similar issue where the wordpress-data is not persisted for some reason, which means my customised wordpress root folder (i.e. custom themes and additional static files) is lost when the pod restarted.

I resorted to an initContainer that pulls data from S3, therefore does not require the creation of a custom image or persisted volume. Sharing in case it helps others.

```
initContainers:
  - name: copy-custom-base
    image: docker.io/bitnami/os-shell:12-debian-12-r31
    command:
      - /bin/bash
    args:
      - -ec
      - |
        #!/bin/bash

        # Install s3cmd to access S3
        apt-get update && apt-get -y install s3cmd

        # Download file
        cd /tmp
        s3cmd get --access_key={S3_ACCESS_KEY_ID} --secret_key={S3_SECRET_ACCESS_KEY} --host={S3_HOST} --host-bucket={S3_BUCKET} s3://wordpress-site-content-custom.tgz

        # Extract file
        tar -xzf wordpress-site-content-custom.tgz

        # Copy files over (except wp-config.php)
        cd /tmp/bitnami/wordpress/ && rm wp-config.php && cp -r ./* /emptydir/app-base-dir/

        # Regrant permission to default user
        chown -R 1001:1001 /emptydir/app-base-dir/

    volumeMounts:
      - name: empty-dir
        mountPath: /emptydir
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
      allowPrivilegeEscalation: true
```
