### ISSUE TITLE
Bitnami/EJBCA openshift BouncyCastle issue

### ISSUE THREAD

**Issue by MRLeflei** [bitnami/charts#30562]
### Name and Version

Bitnami/ejbca

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When deploying the EJBCA container to openshift the default managementCA keystore is corrupted.

I believe this is the cause:
```
ERROR [org.ejbca.core.ejb.StartupSingletonBean] (ServerService Thread Pool -- 106) BouncyCastle is not loaded by an EJBCA classloader, version conflict is likely: org.bouncycastle.jcajce.provider.asymmetric.x509.X509CertificateObject:"
[](url)
```
### Are you using any custom parameters or values?
```yaml
            - name: EJBCA_DATABASE_HOST
              value: "mariadb"
            - name: EJBCA_DATABASE_NAME
              value: "bitnami_ejbca"
            - name: EJBCA_DATABASE_USERNAME
              value: "bn_ejbca"
            - name: EJBCA_DATABASE_PASSWORD
              value: "Bitnami1234"
            - name: TLS_SETUP_ENABLED
              value: "true"
```
### What is the expected behavior?

Keystore is generated for superadmin

### What do you see instead?
```
INFO [org.ejbca.ra.EnrollWithRequestIdBean] (default task-5) Keystore could not be generated for user superadmin
```
### Additional information

This problem causes the ManagementCA to not generate certificates
