### ISSUE TITLE
[bitnami/milvus] 9.0.12 VPA semantic version mismatch for Milvus query nodes

### ISSUE THREAD

**Issue by DarthBubi** [bitnami/charts#30583]
### Name and Version

bitnami/milvus 9.0.12

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. AKS version 1.29.9, VPA managed by AKS
2. w/ VPA enabled for Query Node
3. Install via Terraform Helm provider or Helm directly 
4. Semantic version mismatch error. See log output.

### Are you using any custom parameters or values?

`values.yaml`:
```yaml
...
queryNode:
  tolerations: 
    - key: "workload"
      operator: "Equal"
      value: "milvus"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.azure.com/agentpool"
            operator: "In"
            values:
            - "milvuspool"
  resources:
    limits:
      cpu: "7"
      memory: "12Gi"
    requests:
      cpu: "3500m"
      memory: "4Gi"
  autoscaling:
    hpa:
      enabled: true
      targetCPU: "80"
    vpa:
      enabled: true
      minAllowed:
        cpu: "1"
        memory: "2Gi"
      maxAllowed:
        cpu: "7"
        memory: "12Gi"
...
```

set commands in Terraform:
```hcl
...
set {
    name = "queryNode.replicas"
    value = var.milvus_queryNode_replicas
  }

  set {
    name = "queryNode.autoscaling.hpa.minReplicas"
    type = "string"
    value = var.milvus_queryNode_minReplicas
  }

  set {
    name = "queryNode.autoscaling.hpa.maxReplicas"
    type = "string"
    value = var.milvus_queryNode_maxReplicas
  }
...
```

### What do you see instead?

 Semver mismatch:
`Error: template: milvus/templates/query-node/vpa.yaml:7:15: executing "milvus/templates/query-node/vpa.yaml" at <include "common.capabilities.vpa.apiVersion" .>: error calling include: template: milvus/charts/common/templates/_capabilities.tpl:160:39: executing "common.capabilities.vpa.apiVersion" at <semverCompare "<1.23-0" $kubeVersion>: error calling semverCompare: Invalid Semantic Version`

### Additional information

Output of `kubectl describe crd verticalpodautoscalers.autoscaling.k8s.io` [vpa_crd.txt](https://github.com/user-attachments/files/17869762/vpa_crd.txt)
