### ISSUE TITLE
Rabbitmq Could not download chart: invalid_reference: invalid tag

### ISSUE THREAD

**Issue by thanhhungtakeshi** [bitnami/charts#30582]
### Name and Version

bitnami/rabbitmq

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Im doing setup [FarmVibes.AI](https://github.com/microsoft/farmvibes-ai) which use Terraform to install `rabbitmq` on Azure VM.

OS: Ubuntu LTS20.04

Image tag: 3.10.8-debian-11-r4

Link to their terraform definition: https://github.com/microsoft/farmvibes-ai/blob/main/src/vibe_core/vibe_core/terraform/local/modules/kubernetes/rabbitmq.tf 

Yesterday (probably before the realease of new version of Rabbitmq), the setup run well. But now, it produces the error as below. I've tried to change the image tag, version but nothing work.

I have no expertise in this field, so it really weird and no clue for me to fix.

### What do you see instead?

2024-11-22 06:08:19,650 - INFO    - terraform: │ Error: could not download chart: invalid_reference: invalid tag
2024-11-22 06:08:19,650 - INFO    - terraform: │ 
2024-11-22 06:08:19,650 - INFO    - terraform: │   with module.kubernetes.helm_release.rabbitmq,
2024-11-22 06:08:19,650 - INFO    - terraform: │   on modules/kubernetes/rabbitmq.tf line 1, in resource "helm_release" "rabbitmq":
2024-11-22 06:08:19,650 - INFO    - terraform: │    1: resource "helm_release" "rabbitmq" {
2024-11-22 06:08:19,650 - INFO    - terraform: │ 
2024-11-22 06:08:19,650 - INFO    - terraform: ╵
2024-11-22 06:08:19,833 - ERROR   - farmvibes-ai local failed (Failed to apply terraform resources in /home/azureuser/.config/farmvibes-ai/terraform-user/local). Please see the above error descriptions. If you think this is an error with the program, please file an issue at https://github.com/microsoft/farmvibes-ai/issues. Please also include the contents of /home/azureuser/.cache/farmvibes-ai/farmvibes-ai-local.log in your issue.

**Comment by primeos-work** [comment]
I just ran into this as well but with the Keycloak chart.

It should work again if you update your `repository` in the `resource "helm_release"` block of the Helm provider (Terraform/OpenTofu) like this:
```diff
-  repository = "https://charts.bitnami.com/bitnami"
+  repository = "oci://registry-1.docker.io/bitnamicharts"
```

Source for the OCI URI: https://github.com/bitnami/charts?tab=readme-ov-file#tldr

This is likely related to this upstream issue: https://github.com/helm/helm/issues/13466 

https://charts.bitnami.com/bitnami/index.yaml redirects to https://repo.broadcom.com/bitnami-files/index.yaml and there I can see the `oci://` URIs being used:
```
  keycloak:
  - annotations:
      category: DeveloperTools
      images: |
        - name: keycloak
          image: docker.io/bitnami/keycloak:26.0.6-debian-12-r0
        - name: keycloak-config-cli
          image: docker.io/bitnami/keycloak-config-cli:6.1.6-debian-12-r6
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 26.0.6
    created: "2024-11-22T09:34:44.906798319Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 16.x.x
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Keycloak is a high performance Java-based identity and access management
      solution. It lets developers add an authentication layer to their applications
      with minimum effort.
    digest: a9d1b26667d1c1f974ab518c80bdf4c0d43bd4c80426519801e9991ae5c406b0
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/keycloak/img/keycloak-stack-220x234.png
    keywords:
    - keycloak
    - access-management
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: keycloak
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/keycloak
    urls:
    - oci://registry-1.docker.io/bitnamicharts/keycloak:24.2.2
    version: 24.2.2
```

This issue also seems to be a duplicate of https://github.com/bitnami/charts/issues/30561 (but that one didn't use the best title...).
https://github.com/bitnami/charts/issues/30538 is likely also related.
