### ISSUE TITLE
Provisioning job failing due to sleep timeout not being sufficient enough for minio cluster to be operational upon "mc admin service restart" command in provisioning job

### ISSUE THREAD

**Issue by choudham** [bitnami/charts#30597]
### Name and Version

14.8.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy Minio Helm chart version 14.8.5

Provisioning job fails since the data drives are not up

![image](https://github.com/user-attachments/assets/db639def-94ad-472f-a482-89d4ccd61368)

Screenshot 2024-11-22 at 10.41.00 AM.png
Based on the above upstream change to address the race condition in helm chart we have 5 sec sleep but based on the observation our environment it took more time forit to stabilize (approximately 3 mins … see prometheus graph)

### Are you using any custom parameters or values?
```yaml
USER-SUPPLIED VALUES:
auth:
  rootPassword: XXXX
  rootUser: XXXX
defaultBuckets: ""
global:
  defaultStorageClass: default
image:
  registry: docker.io
  repository: bitnami/minio
  tag: 2024.8.3-debian-12-r1
metrics:
  enabled: true
  prometheusRule:
    enabled: true
  serviceMonitor:
    enabled: true
    labels:
      prometheus: default
      release: platform-monitoring
mode: distributed
persistence:
  size: 300Gi
podAnnotations:
  prometheus.io/path: /minio/v2/metrics
  prometheus.io/port: "9000"
  prometheus.io/scrape: "true"
provisioning:
  buckets:
  - anonymous: true
    lifecycle:
    - disabled: false
      expiry:
        days: 30
        noncurrentVersionDays: 0
      id: 30dRetention
    name: test-A
    versioning: false
    withLock: false
  - lifecycle:
    - disabled: false
      expiry:
        days: 30
        noncurrentVersionDays: 0
      id: 30dRetention
    name: test-B
    versioning: false
    withLock: false
  - lifecycle:
    - disabled: false
      expiry:
        days: 30
        noncurrentVersionDays: 0
      id: 30dRetention
    name: test-C
    versioning: false
    withLock: false
  - lifecycle:
    - disabled: false
      expiry:
        days: 30
        noncurrentVersionDays: 0
      id: 30dRetention
    name: tunnel
    quota:
      size: 30GiB
      type: set
    versioning: false
    withLock: false
  - lifecycle:
    - disabled: false
      expiry:
        days: 30
        noncurrentVersionDays: 0
      id: 30dRetention
    name: test123
    versioning: false
    withLock: false
  - anonymous: true
    name: test-D
    versioning: false
    withLock: false
  enabled: true
resourcesPreset: xlarge
```
### What is the expected behavior?

The expected behavior is that the provisioning job should not fail.

Since sleep 5 is not enough, this should be parameterized and should be available as an option to be provided as a `values.yaml`

### What do you see instead?

![image](https://github.com/user-attachments/assets/2cc3d649-ebb2-43fb-90ec-a7cbc98cef1d)

### Additional information

https://github.com/bitnami/charts/blob/main/bitnami/minio/templates/provisioning-job.yaml#L149
Should be parameterized to be using a value in values.yaml
