### ISSUE TITLE
Kafka listeners sslClientAuth setting ignored for SSL configurations

### ISSUE THREAD

**Issue by rquintos** [bitnami/charts#30600]
### Name and Version

bitnami/kafka 31.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

**Description**

Installing kafka with a mix of SSL protocol listener auth types for `sslClientAuth` never sets a listener override, such as `listener.name.<sslListenerName>.ssl.client.auth`.  If the listener protocol set is `SSL` you will always get what is set at `tls.sslClientAuth` even if you set the optional `sslClientAuth` for the listener protocol.

> [!NOTE]  
> _Found this in chart 26.5.0, but I'm reporting it against 31.0.0 because I still see the same code in 31.0.0._

1. Setup SSL protocols for some or all of your listeners. (See custom values.yaml entries)
1. Perform a standard helm install
   ```console
   helm install kafka bitnami/kafka --version 31.0.0 --values=values.yaml
   ```

### Are you using any custom parameters or values?

This is a snippet of the core sections related to this issue.  This is a legacy setup so we have an existing zookeeper installed via a separate helm install.

```yaml
kraft:
  enabled: false
zookeeper:
  enabled: false
tls:
  truststorePassword: mypassword
  keystorePassword: mypassword
  type: JKS
  endpointIdentificationAlgorithm: ""
  sslClientAuth: "requested"
  existingSecret: my-existingsecret
  jksKeystoreKey: my.keystore.jks
  jksTruststoreKey: my.truststore.jks
listeners:
  client:
    containerPort: 9092
    protocol: SSL
    name: CLIENT
  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: SSL
    sslClientAuth: "none"
  interbroker:
    containerPort: 9094
    protocol: SSL
    name: INTERNAL
    sslClientAuth: "required"
  external:
    containerPort: 9095
    protocol: SSL
    name: EXTERNAL
    sslClientAuth: "required"
```

### What is the expected behavior?

Main expectation is that I'd get separate protocol listeners for each `SSL`  `sslClientAuth` I have set.

**ConfigMap**
Expected in the generated ConfigMap ` kafka-broker-configuration ` and the CLIENT protocol defaults to `tls.sslClientAuth` since `sslClientAuth` is not set.

```yaml
listener.name.internal.ssl.client.auth=required
listener.name.external.ssl.client.auth=required
listener.name.controller.ssl.client.auth=none
```
**The server.properties File in the Broker**
The server.properties file should then in turn get configured with the same configurations from the ConfigMap

```yaml
listener.name.internal.ssl.client.auth=required
listener.name.external.ssl.client.auth=required
listener.name.controller.ssl.client.auth=none
```

### What do you see instead?

None of the `listener.name.<sslListenerName>.ssl.client.auth` settings are written to the ConfigMap that is used to generate the `server.properties` file.

### Additional information

**Possible Introduction of This Change**
Upon reviewing [KIP-684](https://cwiki.apache.org/confluence/display/KAFKA/KIP-684+-+Support+mutual+TLS+authentication+on+SASL_SSL+listeners) it appears that functionality was added to create the override listener auth types for SASL_SSL.  However, in the scenario where I also want different auth types for multiple SSL listeners they get defaulted to `tls.sslClientAuth`.  This is because the `_helpers.tpl` logic that creates listener specific auth settings is nested in the `# Listeners SASL JAAS configuration` [section here](https://github.com/bitnami/charts/blob/064cce6bbcd9ac43b13d081e2e045923607add6e/bitnami/kafka/templates/_helpers.tpl#L591).

**Workaround**
As a workaround I explicitly add the values below to the `extraConfig` section.

```yaml
extraConfig: |-
    listener.name.internal.ssl.client.auth=required
    listener.name.external.ssl.client.auth=required
    listener.name.controller.ssl.client.auth=none
```

**Hints as to why this functionality is unintended**

If I read the [line 193 ](https://github.com/bitnami/charts/blob/064cce6bbcd9ac43b13d081e2e045923607add6e/bitnami/kafka/values.yaml#L193) of the `values.yaml` file I'm under the impression that the setting of `sslClientAuth` should override `tls.sslClientAuth`.

> _If SSL protocol is enabled, overrides tls.sslClientAuth for this listener._

If I also review the Configuration Options in [KIP-684](https://cwiki.apache.org/confluence/display/KAFKA/KIP-684+-+Support+mutual+TLS+authentication+on+SASL_SSL+listeners) I see that it notes...

> SSL listeners will continue to use this configuration with the following order of precedence (no change):
> 
> 1. `listener.name.<sslListenerName>.ssl.client.auth`
> 2. `ssl.client.auth`

However, the point 1 will never be satisfied since we never hit that logic in the `_helpers.tpl` file, as noted previously.

**Minor possible typo***
For the additional protocols listed in the values file, the comments read as:

> If SSL protocol is enabled, overrides tls.authType for this listener.

Is `tls.authType` supposed to read as `tls.sslClientAuth` as it is in [line 193 ](https://github.com/bitnami/charts/blob/064cce6bbcd9ac43b13d081e2e045923607add6e/bitnami/kafka/values.yaml#L193)?

**If this is a Bug**

If upon review of this issue this is confirmed to be missing functionality, I can push a potential pull request after testing if that helps out.
