### ISSUE TITLE
Chart repo problems?

### ISSUE THREAD

**Issue by brightdroid** [bitnami/charts#30609]
### Name and Version

different, e.g. postgresql

### What architecture are you using?

None

### What steps will reproduce the bug?

1. `helm show chart --repo https://charts.bitnami.com/bitnami postgresql --version 16.2.2`

### What is the expected behavior?

Chart info for version 16.2.2

### What do you see instead?
```
Error: invalid_reference: invalid tag
```
### Additional information

helm show chart of version 16.2.1 works without problem.

**Comment by rjacks24** [comment]
I'm getting the same for helm show chart --repo https://charts.bitnami.com/bitnami rabbitmq --version 15.0.7 
15.0.6 works

**Comment by carrodher** [comment]
This is likely related to this upstream issue: https://github.com/helm/helm/issues/13466.

As announced at https://github.com/bitnami/charts/issues/30110, we recently changed the URL field in the _index.yaml_ to use OCI.

**Comment by brightdroid** [comment]
So the repo at https://charts.bitnami.com/bitnami is deprecated and only oci will be available?

Problem: [kustomize does not support OCI repos](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/helmcharts/#long-term-support) - is there any solution for this?

**Comment by carrodher** [comment]
As reported in https://github.com/helm/helm/issues/13466, this problem stems from how the `helm ... --repo ...` command handles an _index.yaml_ file containing OCI URLs.

### Why is this issue appearing now?
Historically, Bitnami Helm charts were accessed by adding the Bitnami repository to the Helm CLI:
```
$ helm repo add bitnami https://charts.bitnami.com/bitnami
```
or by directly installing/pulling a specific Helm chart using the `--repo` flag:
```
$ helm pull --repo https://charts.bitnami.com/bitnami foo
```

In April 2023, [Bitnami introduced support for the OCI format](https://blog.bitnami.com/2023/04/httpsblog.bitnami.com202304bitnami-helm-charts-now-oci.html), recommending OCI-based installation as the primary method going forward. For example:
```
helm pull oci://registry-1.docker.io/bitnamicharts/external-dns --version 8.6.0
```

As detailed in our [recent announcement](https://blog.bitnami.com/2024/10/bitnami-helm-charts-moving-to-oci.html) and https://github.com/bitnami/charts/issues/30110, the traditional method is now being deprecated. Consequently, the _index.yaml_ served at `https://charts.bitnami.com/bitnami` now uses OCI URLs, exposing the above mentioned issue in the Helm CLI's handling of these URLs.

**Comment by brightdroid** [comment]
Problem two: [kustomize does not support OCI repos](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/helmcharts/#long-term-support)

So no more kustomize with bitnami charts?

**Comment by cglacet** [comment]
Do we **have** to migrate everything? What are the minimal changes that can be made to migrate? Is there any solution for skaffold?

**Comment by bh-tt** [comment]
We noticed this as well, and ran into problems with our setup that does not have direct internet access. Helm does not seem to provide a way to change the hostnames to our own mirror, which means we cannot deploy any bitnami helm charts. Quite strange, since most container-related tooling allows defining mirrors for each upstream registry (e.g. when you need to go to registry-1.docker.io for a container, instead use the docker-io.registry.example.com host to circumvent rate limits).

I suppose its just as well we recently changed most of our bitnami charts to kustomize bases from the upstream itself or our own plain yaml (see #30136).

**Comment by jasaltvik** [comment]
> Problem two: [kustomize does not support OCI repos](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/helmcharts/#long-term-support)
> 
> So no more kustomize with bitnami charts?

I think they actually do support it, but it's been quite the confusing journey: https://github.com/kubernetes-sigs/kustomize/pull/5167

This works for me with `kustomize build --enable-helm`

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: redis
  repo: oci://registry-1.docker.io/bitnamicharts/bitnami
  version: 20.3.0
  releaseName: redis-sentinel
  valuesFile: configs/helm-redis.yaml
  namespace: test
```

```shell
❯ kustomize version
v5.5.0
```

Unless I'm misunderstanding something here 😅

**Comment by brightdroid** [comment]
Thanks tried it again, got it working in argocd with this config:

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: postgresql
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: pg17
    namespace: postgres
    version: 16.2.2
    valuesFile: values.yaml
```
