### ISSUE TITLE
Tempo Using ‘local’ Backend Only in Monolithic Mode

### ISSUE THREAD

**Issue by cpeliciari** [bitnami/charts#30608]
### Name and Version

bitnami/tempo:3.7.13

### What architecture are you using?

None

### What steps will reproduce the bug?

Basically, the Tempo documentation states that the local backend should only be used in monolithic mode.
There should be a warning in the documentation mentioning this.

[Grafana Docs](https://grafana.com/docs/tempo/latest/configuration/#storage-block-configuration-example)
```yaml
# Storage configuration for traces
storage:

trace:

# The storage backend to use
# Should be one of "gcs", "s3", "azure" or "local" (only supported in the monolithic mode)
# CLI flag -storage.trace.backend
[backend: <string>]
```

[Chart](https://github.com/grafana/helm-charts/blob/c6a19af28c57970c3a9e2e09bc6bfd6ad496f788/charts/tempo-distributed/values.yaml#L1437)
```yaml
storage:
trace:
{{- if .Values.storage.trace.block.version }}
block:
version: {{.Values.storage.trace.block.version}}
{{- if .Values.storage.trace.block.dedicated_columns}}
parquet_dedicated_columns:
{{ .Values.storage.trace.block.dedicated_columns | toYaml | nindent 8}}
{{- end }}
{{- end }}
pool:
max_workers: {{ .Values.storage.trace.pool.max_workers }}
queue_depth: {{ .Values.storage.trace.pool.queue_depth }}
backend: {{.Values.storage.trace.backend}}
{{- if eq .Values.storage.trace.backend "s3"}}
s3:
{{- toYaml .Values.storage.trace.s3 | nindent 6}}
{{- end }}
{{- if eq .Values.storage.trace.backend "gcs"}}
gcs:
{{- toYaml .Values.storage.trace.gcs | nindent 6}}
{{- end }}
{{- if eq .Values.storage.trace.backend "azure"}}
azure:
{{- toYaml .Values.storage.trace.azure | nindent 6}}
{{- end }}
blocklist_poll: 5m
local:
path: /var/tempo/traces
wal:
path: /var/tempo/wal
```

### What do you see instead?
```
level=warn ts=2024-11-24T19:30:25.336663437Z caller=wal.go:110 msg="failed to replay block. removing." file=e0f96804-c124-4b4c-80a0-06035a98f189+single-tenant+vParquet4 err="error reading wal meta json: /bitnami/grafana-tempo/data/wal/e0f96804-c124-4b4c-80a0-06035a98f189+single-tenant+vParquet4/meta.json: open /bitnami/grafana-tempo/data/wal/e0f96804-c124-4b4c-80a0-06035a98f189+single-tenant+vParquet4/meta.json: no such file or directory"
```
