### ISSUE TITLE
[bitnami/redis-cluster] Unable to build cluster on development server , facing permission issue 

### ISSUE THREAD

**Issue by Harsh-Sharma-1** [bitnami/charts#30616]
### Name and Version

bitnami/redis-cluster 11.0.8

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Using the above-mentioned chart of the Redis cluster able to deploy the same in the local machine and successfully the cluster is also being created. 
2. Tried the same charts and same image on a Linux-based development server, facing the issue given below - 
```
# Fatal: Can't initialize Background Jobs. Error message: Operation not permitted
```
3. Even when trying the same image tag version [7.4.1-debian-12-r2] with some older charts versions it stocks in cluster creation and doesn't create the cluster and doesn't join its node. Pod giving error - 
```
Readiness probe failed: cluster_state:fail
```

### Are you using any custom parameters or values?

Not

### What is the expected behavior?

A cluster should be created and the pod is in `running state 1/1`.

### What do you see instead?

Cluster is not created

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by Harsh-Sharma-1** [comment]
I was able to resolve the permissions issue by using privileged: true.

However, my cluster is still stuck in the creation process. Although all the pods have successfully started, the cluster is not functioning properly. I am encountering the following event:

"Readiness probe failed: cluster_state:fail"

**Comment by cloudcoke** [comment]
It worked before specifying the resource, but after specifying the resource, `Readiness probe failed: cluster_state:fail` error also occurs to me.
However, after changing the image to `redis-cluster:7.4.1-debian-12-r2`, it worked properly.

Before values.yaml
```yaml
          usePassword: false
          persistence:
            enabled: false
          cluster:
            nodes: 3
            replicas: 0
```
After values.yaml
```yaml
       image:
            repository: bitnami/redis-cluster
            tag: 7.2.1-debian-11-r26
          usePassword: false
          persistence:
            enabled: false
          redis:
            resources:
              requests:
                cpu: "250m"
                memory: "0.5Gi"
              limits:
                cpu: "250m"
                memory: "0.5Gi"
          cluster:
            nodes: 3
            replicas: 0
```
