### ISSUE TITLE
[bitnami/keycloak] keycloak behind traefik works but doesn't log the client ip

### ISSUE THREAD

**Issue by mhazan01** [bitnami/charts#30627]
### Name and Version

bitnami/keycloak latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```
helm install keycloak oci://registry-1.docker.io/bitnamicharts/keycloak --create-namespace -n keycloak -f values.yaml
values.yaml contain configuration for ingress with traefik
```
### Are you using any custom parameters or values?
```
ingress:
  ingressClassName: "traefik"
extraEnvVars:
  - name: PROXY_ADDRESS_FORWARDING
    value: "true" 
```

### What is the expected behavior?

keycloak logs show real client ip

### What do you see instead?

keycloak logs show loadbalancer ip

### Additional information

i've been able to get the real client ip on the whoami container, using     forwardedHeaders: and proxyProtocol: but i'am unable to reproduce the configuration in the keycloak chart, i assumed PROXY_ADDRESS_FORWARDING was it. anyone able to help me figure out where and which parameters to add in the chart ?
