### ISSUE TITLE
Keycloak issue with enableDefaultInitContainers

### ISSUE THREAD

**Issue by anebi** [bitnami/charts#30686]
### Name and Version

bitnami/keycloak 24.1.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Set `enableDefaultInitContainers` to true

### What is the expected behavior?

When `enableDefaultInitContainers` is enabled, in the final container we want to see

- `/opt/bitnami/keycloak/providers`
- `/opt/bitnami/keycloak/data`

### What do you see instead?

When enableDefaultInitContainers is enabled In final container we see

- `/opt/bitnami/keycloak/providers/providers`
- `/opt/bitnami/keycloak/data/data`

### Additional information

Once the final keycloak container gets running check dirs:
- `/opt/bitnami/keycloak/providers`
- `/opt/bitnami/keycloak/data`

In those directories you will notice that there are subdirectories like this:

- `/opt/bitnami/keycloak/providers/providers`
- `/opt/bitnami/keycloak/data/data`

This is caused by 
```bash
              info "Copying writable dirs to empty dir"
              # In order to not break the application functionality we need to make some
              # directories writable, so we need to copy it to an empty dir volume
              cp -r --preserve=mode /opt/bitnami/keycloak/data /emptydir/app-data-dir
              cp -r --preserve=mode /opt/bitnami/keycloak/providers /emptydir/app-providers-dir
```
Doing a copy like this doesn't copy the directory content but instead, it copies the complete `data` and `providers` directories to `/emptydir/app-data-dir` and `/emptydir/app-providers-dir`. As a result, we get the problem:

- `/opt/bitnami/keycloak/providers/providers`
- `/opt/bitnami/keycloak/data/data`

In the final container the mount is like this:
```yaml
            - name: empty-dir
              mountPath: /opt/bitnami/keycloak/data
              subPath: app-data-dir
            - name: empty-dir
              mountPath: /opt/bitnami/keycloak/providers
              subPath: app-providers-dir
```
This mounts the app-data-dir to `/opt/bitnami/keycloak/data`, but app-data-dir has also `data/` subdirectory. The same is for `providers`
