### ISSUE TITLE
[bitnami/nginx-ingress-controller] To enable TCP traffic how to use tcpConfigMapNamespace

### ISSUE THREAD

**Issue by rkydx** [bitnami/charts#30698]
### Name and Version

nginx-ingress-controller, 9.9.3

### What architecture are you using?

None

### What steps will reproduce the bug?

I raised this issue here as I tried to find the solution from many other platforms but no where I got any insights.
I have deployed the ingress nginx controller (using bitnami helm chart)
After that, I deployed a Squid proxy in the namespace "squidns" to handle raw TCP/UDP traffic (e.g., as a generic TCP proxy). For this, I created a ConfigMap in the namespace "nginx-ingress" as below -
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: nginx-ingress
data:
  "3128": "squidns/squid-proxy-service:3128"
```

Now which parameter to configure in values.yaml of bitnami chart?
Will the below work? 
```yaml
tcpConfigMapNamespace: nginx-ingress/tcp-services
```

### What do you see instead?

No where mention how to use this parameter so at last raising this issue for help.
