### ISSUE TITLE
common.capabilities.webhook.ingress.apiVersion template not found

### ISSUE THREAD

**Issue by busyboy77** [bitnami/charts#30699]
### Name and Version

bitnami/argo-cd:7.0.25

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```console
$ helm upgrade --install --namespace argocd --create-namespace --values custome-values.yaml --dry-run argocd .
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/rke2/rke2.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/rancher/rke2/rke2.yaml
Release "argocd" does not exist. Installing it now.

Error: template: argo-cd/templates/applicationset/ingress-webhook.yaml:7:15: executing "argo-cd/templates/applicationset/ingress-webhook.yaml" at <include "common.capabilities.webhook.ingress.apiVersion" .>: error calling include: template: no template "common.capabilities.webhook.ingress.apiVersion" associated with template "gotpl"
```

### Are you using any custom parameters or values?

```yaml
global:
  ingressRouter: devops.ef.com
  ingressTlsCertificateSecret: ef-ingress-tls-secret
applicationSet:
  enabled: true
  clusterAdminAccess: true
  webhook:
    ingress:
      enabled: true
      apiVersion: ""
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
      labels: {}
      ingressClassName: "nginx"
      hostname: "{{ .Values.global.ingressRouter }}"
      path: /appset/api/webhook
      pathType: ImplementationSpecific
      tls:
         - hosts:
              -  "{{ .Values.global.ingressRouter }}"
           secretName: "{{ .Values.global.ingressTlsCertificateSecret }}"
      selfSigned: true
notifications:
  enabled: false
server:
  replicaCount: 1
  insecure: false
  configEnabled: true
  url: "{{ .Values.global.ingressRouter }}"
  config:
    url: "{{ .Values.server.url }}"
    application.instanceLabelKey: argocd.argoproj.io/instance
    dex.config: ""
  ingress:
    enabled: true
    selfSigned: true
    pathType: ImplementationSpecific
    hostname: "{{ .Values.global.ingressRouter }}"
    path: /argo(/|$)(.*)
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
    tls: true
    extraTls:
       - hosts:
           - "{{ .Values.global.ingressRouter }}"
         secretName: "{{ .Values.global.ingressTlsCertificateSecret }}"
    ingressClassName: "nginx"
  ingressGrpc:
    enabled: true
    pathType: ImplementationSpecific
    hostname: "{{ .Values.global.ingressRouter }}"
    path: /argogrpc(/|$)(.*)
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
    tls: true
    extraTls:
       - hosts:
           - "{{ .Values.global.ingressRouter }}"
         secretName: "{{ .Values.global.ingressTlsCertificateSecret }}"
    ingressClassName: "nginx"
repoServer:
  replicaCount: 1
dex:
  enabled: true
  replicaCount: 1
config:
  knownHosts: |
    gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9
  extraKnownHosts: ""
  createExtraKnownHosts: true
  secret:
    create: true
    annotations: {}
    githubSecret: ""
    gitlabSecret: ""
    bitbucketServerSecret: ""
    bitbucketUUID: ""
    gogsSecret: ""
    extra: {}
    argocdServerTlsConfig:
      key: ""
      crt: ""
    argocdServerAdminPassword: ""
    argocdServerAdminPasswordMtime: ""
    repositoryCredentials: {}
  clusterCredentials: []
```

### What is the expected behavior?

see above

### What do you see instead?

template not found 

### Additional information

see above.
