### ISSUE TITLE
problem with the TLS Certs in ingress.yaml

### ISSUE THREAD

**Issue by busyboy77** [bitnami/charts#30723]
### Name and Version

bitnami/argo-cd:7.0.25

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When deploying helm charts where the container is exposing 2 ports namely `http` and `https`, the default ingress template that defines the backend and its port can't evaluate the correct port when we have `tls: false` and `extraTls` is set

This will be true for all the helm charts using the `common.ingress.backend` template.

For Example in argo-cd, using the below snippet, notice, that I have set the `tls: true` and `extraTls` also populated, the targeted port is set to `https`

```yaml
applicationSet:
  enabled: true
  clusterAdminAccess: true
      tls: true
      extraTls:
         - hosts:
              -  "devops.ef.com
           secretName: ef-ingress-tls-secret
      selfSigned: false
```

the template function renders the ingress resource like the one below

```yaml
spec:
  ingressClassName: "nginx"
  rules:
    - host: devops211.ef.com"
      http:
        paths:
          - path: /appset/api/webhook(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: argocd-argo-cd-server
                port:
                  name: https
  tls:
    - hosts:
        - devops211.ef.com"
      secretName: devops211.ef.com"-tls
    - hosts:
      - devops211.ef.com
      secretName: ef-ingress-tls-secret
```

Now if I set the `tls: false` and just add the custom TLS cert ( which is our requirement to add our custom TLS cert ) 

```yaml
applicationSet:
  enabled: true
  clusterAdminAccess: true
  serviceAccount:
    create: true
    automountServiceAccountToken: true
  webhook:
    ingress:
      enabled: true
      annotations:
         nginx.ingress.kubernetes.io/rewrite-target: /$2
         nginx.ingress.kubernetes.io/use-regex: "true"
      labels: {}
      ingressClassName: "nginx"
      hostname: devops211.ef.com"
      path: /appset/api/webhook(/|$)(.*)
      pathType: ImplementationSpecific
      tls: false
      extraTls:
         - hosts:
              -  devops211.ef.com
           secretName: ef-ingress-tls-secret
      selfSigned: false
```

this results in the correct TLS cert but the target port is not `https`

```yaml
---
# Source: argo-cd/templates/applicationset/ingress-webhook.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-argo-cd-applicationset-controller
  namespace: "default"
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-cd
    app.kubernetes.io/version: 2.13.1
    helm.sh/chart: argo-cd-7.0.25
    app.kubernetes.io/component: applicationSet
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: "nginx"
  rules:
    - host: devops211.ef.com"
      http:
        paths:
          - path: /appset/api/webhook(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: argocd-argo-cd-server
                port:
                  name: http
  tls:
    - hosts:
      - devops211.ef.com
      secretName: ef-ingress-tls-secret
```

### Are you using any custom parameters or values?

```yaml
applicationSet:
  enabled: true
  clusterAdminAccess: true
  serviceAccount:
    create: true
    automountServiceAccountToken: true
  webhook:
    ingress:
      enabled: true
      annotations:
         nginx.ingress.kubernetes.io/rewrite-target: /$2
         nginx.ingress.kubernetes.io/use-regex: "true"
      labels: {}
      ingressClassName: "nginx"
      hostname: devops211.ef.com"
      path: /appset/api/webhook(/|$)(.*)
      pathType: ImplementationSpecific
      tls: false
      extraTls:
         - hosts:
              -  devops211.ef.com
           secretName: ef-ingress-tls-secret
      selfSigned: false
notifications:
  enabled: true
server:
  replicaCount: 1
  insecure: true
  configEnabled: true
  url: https://devops211.ef.com"
  config:
    ui.bannercontent: "Welcome to Argo Controller!"
    # Enables application status badge feature
    statusbadge.enabled: 'true'
    timeout.reconciliation: 180s
    # resource.customizations:
    url: "{{ .Values.server.url }}"
    application.instanceLabelKey: argocd.argoproj.io/instance
    dex.config: " asdf : oneTwothree"
  ingress:
    enabled: true
    selfSigned: false
    pathType: ImplementationSpecific
    hostname: devops211.ef.com
    path: /argo(/|$)(.*)
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
    tls: true
    extraTls:
       - hosts:
           - devops211.ef.com
         secretName: ef-ingress-tls-secret
    ingressClassName: "nginx"
  ingressGrpc:
    enabled: true
    selfSigned: false
    pathType: ImplementationSpecific
    hostname: devops211.ef.com"
    path: /argogrpc(/|$)(.*)
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
    tls: true
    extraTls:
       - hosts:
           - devops211.ef.com
         secretName: ef-ingress-tls-secret
    ingressClassName: "nginx"
repoServer:
  replicaCount: 1
dex:
  enabled: true
config:
  knownHosts: |
    gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9
  extraKnownHosts: ""
  createExtraKnownHosts: true
  secret:
    create: true
    annotations: {}
    githubSecret: ""
    gitlabSecret: ""
    bitbucketServerSecret: ""
    bitbucketUUID: ""
    gogsSecret: ""
    extra: {}
    argocdServerTlsConfig:
      key: ""
      crt: ""
    argocdServerAdminPassword: ""
    argocdServerAdminPasswordMtime: ""
    repositoryCredentials: {}
  clusterCredentials: []
redis:
  master:
    extraFlags:
    - "--maxmemory-policy allkeys-lru"
  resources:
    requests:
      cpu: "500m"
      memory: "1000Mi"
    limits:
      cpu: "1000m"
      memory: "1500Mi"
```

### What is the expected behavior?

the template used for defining the backend of an ingress resource has no idea about the `extraTls` enablement.

```yaml
spec:
  {{- if and .Values.applicationSet.webhook.ingress.ingressClassName (eq "true" (include "common.ingress.supportsIngressClassname" .)) }}
  ingressClassName: {{ .Values.applicationSet.webhook.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
    {{- if .Values.applicationSet.webhook.ingress.hostname }}
    - host: {{ .Values.applicationSet.webhook.ingress.hostname }}
      http:
        paths:
          {{- if .Values.applicationSet.webhook.ingress.extraPaths }}
          {{- toYaml .Values.applicationSet.webhook.ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ .Values.applicationSet.webhook.ingress.path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
            pathType: {{ .Values.applicationSet.webhook.ingress.pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "argocd.server" .) "servicePort" (ternary "https" "http" .Values.applicationSet.webhook.ingress.tls) "context" $)  | nindent 14 }}
    {{- end }}
    {{- range .Values.applicationSet.webhook.ingress.extraHosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "argocd.server" $) "servicePort" (ternary "https" "http" $.Values.applicationSet.webhook.ingress.tls) "context" $) | nindent 14 }}
    {{- end }}
  tls:
    {{- if .Values.applicationSet.webhook.ingress.tls }}
    - hosts:
        - {{ .Values.applicationSet.webhook.ingress.hostname }}
      secretName: {{ printf "%s-tls" .Values.applicationSet.webhook.ingress.hostname }}
    {{- end }}
    {{- if .Values.applicationSet.webhook.ingress.extraTls }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.applicationSet.webhook.ingress.extraTls "context" $ ) | nindent 4 }}
    {{- end }}
{{- end -}}
```

this line 
```yaml
backend: {{- include "common.ingress.backend" (dict "serviceName" (include "argocd.server" .) "servicePort" (ternary "https" "http" .Values.applicationSet.webhook.ingress.tls) "context" $)  | nindent 14 }}
```
has no idea whether the TLS Cert is coming from `extraTls` because we want to use our own ingress cert secret
