### ISSUE TITLE
[bitnami/clickhouse] unable to run init DB scripts in cluster mode

### ISSUE THREAD

**Issue by crazyfree** [bitnami/charts#30731]
### Name and Version

bitnami/clickhouse 7.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install chart as a dependency in `Chart.yaml` file 
```yaml
dependencies:
  - name: clickhouse
    version: 7.0.1
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: clickhouse.enabled
```
2. setup `values.yml` like below 
```yaml
clickhouse:
  enabled: true
  database:
    create: true
    name: test
  auth:
    username: guest
    password: guest
  clusterName: default
  shards: 2
  replicaCount: 1
  keeper:
    enabled: true
  zookeeper:
    enabled: false
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 0.5
      memory: 1Gi
  extraVolumeMounts:
    - name: clickhouse-init
      mountPath: /docker-entrypoint-initdb.d/init.sql
      subPath: init.sql
  extraVolumes:
    - name: clickhouse-init
      configMap:
        name: clickhouse-init-scripts
```
3. setup `clickhouse-init-scripts.yaml` configmap
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-init-scripts
data:
  init.sql: |
    -- create database if needed
    {{- if .Values.clickhouse.database.create }}
    CREATE DATABASE IF NOT EXISTS {{ .Values.clickhouse.database.name }} ON CLUSTER '{{ .Values.clickhouse.clusterName }}';
    {{- end }}

    USE {{ .Values.clickhouse.database.name }};

    -- SQL script to create tables
    CREATE TABLE IF NOT EXISTS embeddings_local ON CLUSTER '{{ .Values.clickhouse.clusterName }}' (
      id UInt64,
      article_id UInt64,
      embedding Array(Float32),
      created_at DateTime DEFAULT now()
    ) ENGINE = MergeTree()
    PARTITION BY toYYYYMM(create_at)    -- partition by year and month
    ORDER BY (created_at, article_id, id);
   -- Create distributed table 
  CREATE TABLE embeddings
    AS embeddings_local ON CLUSTER '{{ .Values.clickhouse.clusterName }}'
    ENGINE = Distributed('{{ .Values.clickhouse.clusterName }}', '{{ .Values.clickhouse.database.name }}', 'embeddings_local', (id, article_id));
```
4. deploy to docker desktop 
```bash
helm update --install --namespace=test \ 
  --values <path-to-values.yaml-file> \
  --create-namespace test \
  <helm directory>
```
5. After deployed successfully, check to see if test DB created 
```
kubectl exec -it <pod-name> -- clickhouse-client -u guest --password guest
show databases;
```
6. There is no test DB appears. 

### What is the expected behavior?

the test DB created successfully along with the embeddings table. 

### What do you see instead?

no test DB found

### Additional information
Clickhouse provisions on Docker Desktop latest version `4.36.0 (175267)` on Macbook Pro
