### ISSUE TITLE
[bitnami/airflow] Extra packages install fails

### ISSUE THREAD

**Issue by Nickmman** [bitnami/charts#30791]
### Name and Version

bitnami/airflow 18.3.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy airflow via helm using ArgoCD using custom values, disabling the readOnlyRootFilesystem and mounting a ConfigMap with the requirements.txt

### Are you using any custom parameters or values?

```yaml
web:
  containerSecurityContext:
    readOnlyRootFilesystem: false
  extraVolumes:
    - name: requirements
      configMap:
        name: requirements
  extraVolumeMounts:
    - name: requirements
      mountPath: /bitnami/python/
worker:
  containerSecurityContext:
    readOnlyRootFilesystem: false
  extraVolumes:
    - name: requirements
      configMap:
        name: requirements
  extraVolumeMounts:
    - name: requirements
      mountPath: /bitnami/python/
scheduler:
  containerSecurityContext:
    readOnlyRootFilesystem: false
  extraVolumes:
    - name: requirements
      configMap:
        name: requirements
  extraVolumeMounts:
    - name: requirements
      mountPath: /bitnami/python/
```
The ConfigMap spec is the following:
```yaml
data:
  "requirements.txt": |-
    apache-airflow-providers-apache-kafka
    kafka-python
```

### What is the expected behavior?

- Airflow pods can correctly install the extra modules
- The worker pod should have a RW filesystem

### What do you see instead?

- The scheduler and worker pods fail with "permission denied":
```
Downloading apache_airflow_providers_apache_kafka-1.6.1-py3-none-any.whl (26 kB)
Downloading kafka_python-2.0.2-py2.py3-none-any.whl (246 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 246.5/246.5 kB 16.8 MB/s eta 0:00:00
Downloading confluent_kafka-2.6.1-cp311-cp311-manylinux_2_28_x86_64.whl (3.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 90.3 MB/s eta 0:00:00
Installing collected packages: kafka-python, confluent-kafka, apache-airflow-providers-apache-kafka
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/opt/bitnami/airflow/venv/lib/python3.11/site-packages/kafka'
Check the permissions.


[notice] A new release of pip is available: 24.1 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
```
- The worker pod fails with Read-only filesystem (even though it is configured to not be readOnly based on the same values as scheduler and web):
```
Downloading apache_airflow_providers_apache_kafka-1.6.1-py3-none-any.whl (26 kB)
Downloading kafka_python-2.0.2-py2.py3-none-any.whl (246 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 246.5/246.5 kB 9.1 MB/s eta 0:00:00
Downloading confluent_kafka-2.6.1-cp311-cp311-manylinux_2_28_x86_64.whl (3.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 15.2 MB/s eta 0:00:00
Installing collected packages: kafka-python, confluent-kafka, apache-airflow-providers-apache-kafka
ERROR: Could not install packages due to an OSError: [Errno 30] Read-only file system: '/opt/bitnami/airflow/venv/lib/python3.11/site-packages/kafka'


[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
```

### Additional information

- The scheduler and worker pods have correctly set the filesystem to be RW, but it is not writable due to permissions. Per the deployment, the fsgroup is set to 1001 and changing it (also configuring runAsGroup) does not yield a different result.

- With the configuration of the worker pod, it fails to set the filesystem to be RW, as it still gets deployed with `readOnlyRootFilesystem: true`

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by Nickmman** [comment]
Thanks for getting back to me @carrodher, is there any good way to modify the permissions of the directory that the modules will reside in? I don't see anything specific in the helm chart that would allow this to work, aside from the fsgroup

**Comment by Nickmman** [comment]
@carrodher After some tweaking, I was able to get this to work with the following values:
```
extraDeploy:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: airflow-requirements
    data:
      requirements.txt: |
        apache-airflow-providers-apache-kafka
        kafka-python
worker:
  initContainers:
    - name: copy-python-env
      image: bitnami/airflow-worker:2.9.2-debian-12-r1
      command:
        - /bin/bash
      args:
        - -ec
        - |
          #!/bin/bash
          mv /opt/bitnami/airflow/venv/* /opt/bitnami/airflow/venv/.* /venv/ || true
      volumeMounts:
        - name: venv
          mountPath: /venv
    - name: init-fix-permissions
      image: bitnami/airflow-worker:2.9.2-debian-12-r1
      command:
        - sh
        - -c
        - |
          find /opt/bitnami/airflow/venv/ -type d -exec chown 1001 {} \;
      securityContext:
        runAsUser: 0
  containerSecurityContext:
    readOnlyRootFilesystem: false
  extraVolumes:
    - name: venv
      emptyDir: {}
    - name: requirements
      configMap:
        name: airflow-requirements
  extraVolumeMounts:
    - name: venv
      mountPath: /opt/bitnami/airflow/venv
    - name: requirements
      mountPath: /bitnami/python/
```
