### ISSUE TITLE
[bitnami/mongodb] dnsCheck needs $MY_POD_NAMESPACE to be set

### ISSUE THREAD

**Issue by JustDoItSascha** [bitnami/charts#30798]
### Name and Version

bitnami/mongodb: 16.3.2

### What architecture are you using?

arm64

### What steps will reproduce the bug?

If you look into the definition of the dnsCheck, you find this:

```yaml
- name: dns-check
  image: {{ include "mongodb.externalAccess.dnsCheck.image" . }}
  imagePullPolicy: {{ .Values.externalAccess.dnsCheck.image.pullPolicy | quote }}
  command:
    - /bin/bash
  args:
    - -ec
    - |
      # MONGODB_INITIAL_PRIMARY_HOST should be resolvable
      while ! (getent ahosts "{{ include "mongodb.initialPrimaryHost" . }}" | grep STREAM); do
        sleep 10
      done
  {{- if .Values.containerSecurityContext.enabled }}
  securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.containerSecurityContext "context" $) | nindent 12 }}
  {{- end }}
  {{- if .Values.externalAccess.dnsCheck.resources }}
  resources: {{- toYaml .Values.externalAccess.dnsCheck.resources | nindent 12 }}
  {{- else if ne .Values.externalAccess.dnsCheck.resourcesPreset "none" }}
  resources: {{- include "common.resources.preset" (dict "type" .Values.externalAccess.dnsCheck.resourcesPreset) | nindent 12 }}
  {{- end }}
{{- end -}}
```

It includes `mongodb.initialPrimaryHost`, which itself includes the namespace as `$(MY_POD_NAMESPACE)` instead of helm variable. But the environment variable MY_POD_NAMESPACE is not set in the context of the dnsCheck. So externalAccess is unable to work.

### What do you see instead?

dnsCheck failing with MY_POD_NAMESPACE: command not found

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by Rishav-Roushan-Infrrd** [comment]
Facing same Issue , when i enable external access , MY_POD_NAMESPACE: command not found, it works otherwise

**Comment by JustDoItSascha** [comment]
> Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).
> 
> Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Unfortunately I don't know how you typically would solve this. I mean I already found the issue. Would you set the environment variables in the DNS Check or would you change the command itself?

**Comment by Rishav-Roushan-Infrrd** [comment]
Issue:One solution(temperory)
Create the STS: Deploy the Helm chart as usual.
Edit the STS:
Access the STS configuration.
Modify the MY_POD_NAMESPACE environment variable to the desired value.
Save the changes.
Restart the STS:
Scale down the number of replicas to zero.
Scale up the number of replicas to the desired value.
Limitations:

This workaround is not a permanent solution.
It requires manual intervention each time the chart is updated or modified.
This manual process can be error-prone and time-consuming.

**Comment by JustDoItSascha** [comment]
Please reopen. It's still not fixed and it's blocking a whole feature of the chart.

**Comment by javsalgar** [comment]
Hi!

What I would do is set the environment variable like this:

```
{{/*
Init container definition to wait external DNS names.
*/}}
{{- define "mongodb.initContainers.dnsCheck" -}}
- name: dns-check
  image: {{ include "mongodb.externalAccess.dnsCheck.image" . }}
  imagePullPolicy: {{ .Values.externalAccess.dnsCheck.image.pullPolicy | quote }}
  command:
    - /bin/bash
  args:
    - -ec
    - |
      # MONGODB_INITIAL_PRIMARY_HOST should be resolvable
      while ! (getent ahosts "$MONGODB_INITIAL_PRIMARY_HOST" | grep STREAM); do
        sleep 10
      done
  {{- if .Values.containerSecurityContext.enabled }}
  securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.containerSecurityContext "context" $) | nindent 12 }}
  {{- end }}
  {{- if .Values.externalAccess.dnsCheck.resources }}
  resources: {{- toYaml .Values.externalAccess.dnsCheck.resources | nindent 12 }}
  {{- else if ne .Values.externalAccess.dnsCheck.resourcesPreset "none" }}
  resources: {{- include "common.resources.preset" (dict "type" .Values.externalAccess.dnsCheck.resourcesPreset) | nindent 12 }}
  {{- end }}
  env:
    - name: MONGODB_INITIAL_PRIMARY_HOST
      value: {{ include "mongodb.initialPrimaryHost" . | quote }}
{{- end -}}

```

As you discovered the issue, would you like to submit the PR with the change above?

**Comment by JustDoItSascha** [comment]
I think that the change will not work. You just moved the issue to another place. Like I wrote:

> It includes mongodb.initialPrimaryHost, which itself includes the namespace as $(MY_POD_NAMESPACE) instead of helm variable. But the environment variable MY_POD_NAMESPACE is not set in the context of the dnsCheck. So externalAccess is unable to work.

The MY_POD_NAMESPACE is missing. The question is: Why should a helm helper include itself another environment variable? Especially when this variable is also available in the helm context as an include?

So we could either fix the mongodb.initialPrimaryHost itself and not use $MY_POD_NAMESPACE anymore. Or we could set the MY_POD_NAMESPACE variable inside this container. And we could do this with two ways:

1. Inject the helm namespace variable as env variable.
2. Or use the kubernetes way:
```
env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```

But since I'm not knowing every function of this helm chart, I don't know if I don't see something important. Or what the "bitnami" way of solving this is.

I mean, if I look into the helper:

```
{{/*
Get initial primary host to configure MongoDB cluster.
*/}}
{{- define "mongodb.initialPrimaryHost" -}}
{{ ternary ( printf "%s-0.%s.$(MY_POD_NAMESPACE).svc.%s" (include "mongodb.fullname" .) (include "mongodb.service.nameOverride" .) .Values.clusterDomain ) ( first .Values.externalAccess.service.publicNames ) ( empty .Values.externalAccess.service.publicNames ) }}
{{- end -}}
```

I absolutely don't understand why it includes "mongodb.fullname", "mongodb.service.nameOverride", "Values.clusterDomain", etc. but then SUDDENLY `$(MY_POD_NAMESPACE)` instead of `.Release.Namespace` for example.

This looks so weird and wrong to me that I'm assuming that there is a reason for this that I just don't know.
