### ISSUE TITLE
[bitnami/external-dns] Records not generated for two-level subdomains

### ISSUE THREAD

**Issue by philipp-durrer-jarowa** [bitnami/charts#30799]
### Name and Version

bitnami/external-dns 8.6.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Use the Azure integration, and have a DNS zone e.g. example.com
2. Try to create an ingress with an external-dns annotation for hostname: `my.sub.example.com`

### Are you using any custom parameters or values?

```yaml
provider: azure
azure:
    resourceGroup: "my-rg"
    tenantId: "XXXXX"
    subscriptionId: "XXXXX"
    useManagedIdentityExtension: true
txtOwnerId: "my-aks"
policy: sync # to cleanup old entries!
metrics:
  enabled: true
domainFilters:
- example.com
```

### What is the expected behavior?

I expect external-dns to create a new A record `my.sub.` pointing to the ingress IP, since example.com is in the domainfilter list and my.sub.example.com is a valid domain it should be created in the Azure DNS Zone of example.com

### What do you see instead?

external-dns is ignoring my.sub.example.com until I add sub.example.com to the domainfilters but then it obviously complains about the lack of subdns-zone sub.example.com (which I really don't want to create).

What I think is needed is to adapt the zoneMatchParent feature from the AWS provider for Azure so external-dns can create the two-level subdomain entry. Alternatively, the domainfilter logic could be more explicit and when `*.example.com` is set, to accept all subdomains of that domain. Or as a rather ugly alternative, there should be a domain -> zone map where I could say `sub.example.com -> example.com`
