### ISSUE TITLE
upgrade fro 8.5.1 to 8.6.0: Error: invalid_reference: invalid tag

### ISSUE THREAD

**Issue by mpechner-akasa** [bitnami/charts#30811]
### Name and Version

bitnami/external-dns/8.6.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

upgrade from 8.5.1 to either 8.6.0 or 8.6.1
Get this error:   "Error: invalid_reference: invalid tag"

### Are you using any custom parameters or values?
```
resource "helm_release" "external_dns" {
  namespace        = local.external_dns_ns
  create_namespace = true

  name       = "external-dns"
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "external-dns"
  version    = var.external_dns_version

  values = [
    templatefile("${path.module}/config/external-dns-values.yaml.tftpl", {
      external_dns_role_arn = module.external_dns_irsa_role.iam_role_arn,
      aws_region            = var.aws_region
    })
  ]
}
```

```yaml
crd:
  create: true
sources:
  - crd
  - service
  - ingress
  - traefik-proxy
txtPrefix: MYCOMPANY
aws:
  region: ${aws_region}
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
serviceAccount:
  annotations:
    "eks.amazonaws.com/role-arn": ${external_dns_role_arn}
```

### What is the expected behavior?

The update from 8.5.1 to 8.6.0 or 8.6.1 would work.

### What do you see instead?
```
 Error: invalid_reference: invalid tag
│ 
│   with module.eks_defaults.module.ingress_controller.helm_release.external_dns,
│   on ../../modules/eks_default_installations/ingress-controller/external-dns.tf line 6, in resource "helm_release" "external_dns":
│    6: resource "helm_release" "external_dns" {
```
