### ISSUE TITLE
[Bitnami/mongodb] Question on custom configuration

### ISSUE THREAD

**Issue by torchlard** [bitnami/charts#3082]
I see that there's "configuration" setting in value.yaml, and the type is String, but I don't understand how to use it. Is there any detail explanation? The same question is on existingConfigmap. Hope someone helps

**Comment by marcosbc** [comment]
Hi @torchlard, those parameters allow you to set custom MongoDB configuration. You can set those parameters via `helm install` with `--set`:

```
helm install mychart --set configuration='# configuration file' bitnami/mongodb
helm install mychart --set existingConfigMap=mongodb-configmap bitnami/mongodb
```

For `configuration`, there are various ways to set it:

* Copy the values.yaml file to your computer, and edit it by hand adding the desired configuration, and then run `helm install ... bitnami/mongodb` with `--values /path/to/values.yaml`. Alternatively, you could use a tool such as Rancher or Kubeapps where you would specify the `values.yaml` file before deploying the chart in the UI.

Since it's usually tedious to maintain a configuration file inside another (YAML) configuration file, it's common to include it in a configmap: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-a-configmap-using-kubectl-create-configmap And once the configmap is created, just specify the name of it with `--set existingConfigMap=myconfigmap`.

**Comment by torchlard** [comment]
configuration='# configuration file'  <=== what do you mean by that?
I know how to use value.yaml in helm, but I dont't understand what exactly is the format for config file.
for example, I want to use config 
```yaml
  setParameter:
    wiredTigerConcurrentReadTransactions: 1024
```
do I write like this:
```
configuration: |-
  setParameter:
    wiredTigerConcurrentReadTransactions: 1024
```
OR like this in value.yaml ??
```
configuration: 'config.yaml'
```
I have tried to create configmap like this and put config in separate file
`kubectl create configmap mongo-config --from-file=config.yam`
and what's next? It is not working when I set `helm install mychart --set existingConfigMap=mongo-config bitnami/mongodb`

**Comment by marcosbc** [comment]
@torchlard Keep in mind that, when you're specifying the configuration via configmap or in the values.yaml file, you need to specify **the entire configuration file** and not only parts of it. Basically, what it will do, is to replace the entire configuration file with what you're specifying.

>Do I need to write like this:
>...
> OR like this in values.yaml ??
>...

The values.yaml file [contains an example](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml#L122-L160) which should work just by uncommenting the lines.

Since a single line will probably not work because of missing required configuration, use the first format with all the required configuration. I.e.:

```yaml
configuration: |-
  # where and how to store data.
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
  # where to write logging data
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0
  # network interfaces
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    bindIpAll: true
  # replica set options
  #replication:
    #replSetName: replicaset
    #enableMajorityReadConcern: true
  # process management options
  processManagement:
    fork: false
    pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
  # set parameter options
  setParameter:
    enableLocalhostAuthBypass: true
    wiredTigerConcurrentReadTransactions: 1024
  # security options
  security:
    authorization: disabled
    #keyFile: /opt/bitnami/mongodb/conf/keyfile
```

> I have tried to create configmap like this and put config in separate file [...] It is not working when I set `helm install mychart --set existingConfigMap=mongo-config bitnami/mongodb`

Is it not working because the deployment errors, or because it is not detecting the configuration file?
