### ISSUE TITLE
[bitnami/flux] source-controller init-container didn't work as expected

### ISSUE THREAD

**Issue by krone-rose** [bitnami/charts#30835]
### Name and Version

bitname/flux 141

### What architecture are you using?

amd64

### What steps will reproduce the bug?

deploy the helm chart and try to add an init container for the source controller

### Are you using any custom parameters or values?
```yaml
sourceController:
  extraVolumes:
    - name: cert-volume
      emptyDir: { }
  extraVolumeMounts:
    - name: cert-volume
      mountPath: /etc/ssl/certs/ca-certificates.crt
      subPath: ca.crt
      readOnly: false
  initContainers:
    - name: init-helm-controller-certs
      image: ****************************
      command: ["/bin/sh", "-c"]
      args:
        - |
          curl -o /tmp/basechain.crt https://*****/basechain/
          cat /tmp/basechain.crt /etc/ssl/certs/ca-certificates.crt > /var/tmp/ca.crt
          echo "CA chain combined and saved to /tmp/ca.crt"
      volumeMounts:
        - name: cert-volume
          mountPath: /var/tmp
```
### What is the expected behavior?

An init container is added to the flux source-controller deployment

### What do you see instead?

No init container is added ;)

### Additional information

I think here bitnami/flux/templates/source-controller/deployment.yaml in line 100
these
```
 {{- if .Values.initContainers }}
```
should be identical with the initContainer part in line 75
```
      {{- if or (and .Values.volumePermissions.enabled .Values.sourceController.persistence.enabled) .Values.sourceController.initContainers }}
```

When I add both tags in my values.yaml
```yaml
initContainers: []
```
and also
```
sourceController.initContainers: []
```
it works
