### ISSUE TITLE
cronjob backup not working with tls

### ISSUE THREAD

**Issue by pthpth** [bitnami/charts#30837]
### Name and Version

bitnami/postgres-ha:15.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Running the following helm command 
```console
$ helm install mypostgres-ha bitnami/postgresql-ha  -f values.yaml -n postgres-ha
Error: INSTALLATION FAILED: 1 error occurred:
        * CronJob.batch "postgres-ha-postgresql-ha-postgresql-pgdumpall" is invalid: spec.jobTemplate.spec.template.spec.containers[0].volumeMounts[1].name: Not found: "certs"
```

### Are you using any custom parameters or values?

Simplelest new-values.yaml file which creates the error
```yaml
pgpool:
  tls:
    enabled: true
    autoGenerated: true
posgtres:
  tls:
    enabled: true
    autoGenerated: true
backup:
  enabled: true
```

### What is the expected behavior?

I expect the deployment to be installed.

### What do you see instead?

I see the above error message.
```
Error: INSTALLATION FAILED: 1 error occurred:
        * CronJob.batch "postgres-ha-postgresql-ha-postgresql-pgdumpall" is invalid: spec.jobTemplate.spec.template.spec.containers[0].volumeMounts[1].name: Not found: "certs" 
```

### Additional information

The issue is the same as #20546 which was solved by PR #24468 in postgres charts, the same changes can be made for postgres-ha.
