### ISSUE TITLE
[bitnami/postgresql-ha] Setting postgresql.initdbScripts fails in current 14.15.0-debian-12-r2 container image

### ISSUE THREAD

**Issue by Stevenpc3** [bitnami/charts#30844]
### Name and Version

bitnami/postgresql-ha  15.0.2

### What architecture are you using?

None

### What steps will reproduce the bug?

Deploy the chart and override the initdbScripts with the latest 14.x.y chart version and it fails.

We use an override similar to the following 

```yaml
  postgresql:
      replicaCount: 1
      initdbScriptsCM: ""
      initdbScripts:
        crypto.sql: |
          CREATE EXTENSION pgcrypto
        my_init_script.sh: |
          #!/bin/sh
          pg_restore --verbose -U user -d userdb -1 /tmp/init-data/db-1
      extraInitContainers:
        - name: db-migration-test-init-data
          image: registry.gitlab.company.com:443/operational/test-data/db-migration-test/test:1.0.2
          command: ["/bin/sh"]
          args: ["-c", "cp -r * /tmp/init-data"]
          volumeMounts:
            - name: init-data
              mountPath: /tmp/init-data
          resources:
            limits:
              memory: 1G
            requests:
              cpu: 2
      extraVolumes:
        - name: init-data
          emptyDir: {}
      extraVolumeMounts:
        - name: init-data
          mountPath: /tmp/init-data
```

This will copy a db dump into the container then execute a load of that data on start.

This used to work but broke in this image https://github.com/bitnami/containers/commit/845b769998f568d004aefabe66697215c6ecfa40.

We have not isolated if it is the bitnami image or if it is the postgresql image that bitnami uses as a base. All images before this work with this chart.

### What is the expected behavior?

The postgresql instance loads the data and starts properly and has data ready to go when the user connects.

### What do you see instead?

The image will restart once on deploy, then come up after the restart and the data will not be loaded.
