### ISSUE TITLE
Harbor losses Docker Hub registry credentials daily

### ISSUE THREAD

**Issue by juliansotoca** [bitnami/charts#30852]
### Name and Version

bitnami/harbor:24.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I run 2 harbor instances in 2 AKS clusters and in both I have the same issue
I deploy harbor with argocd with this configuration:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  destination:
    namespace: harbor
    server: https://kubernetes.default.svc
  project: harbor
  source:
    repoURL: 'registry-1.docker.io/bitnamicharts'
    targetRevision: "24.0.2"
    path: harbor
    chart: harbor
    helm:
      parameters:
      - name: externalURL
        value: "https://harbor.com"
      - name: exposureType
        value: "ingress"
      - name: global.defaultStorageClass
        value: "default"
      - name: persistence.persistentVolumeClaim.jobservice.storageClass
        value: "azurefile"
      - name: persistence.persistentVolumeClaim.jobservice.accessMode
        value: "ReadWriteMany"
      - name: persistence.persistentVolumeClaim.jobservice.size
        value: "1Gi"
      - name: persistence.persistentVolumeClaim.registry.storageClass
        value: "azurefile"
      - name: persistence.persistentVolumeClaim.registry.accessMode
        value: "ReadWriteMany"
      - name: persistence.persistentVolumeClaim.registry.size
        value: "4Gi"
      values: |-
        adminPassword: "12345qwerty"
        ingress:
          core:
            hostname: "harbor.com"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
```

Everything is deployed and I can configure a docker registry using my credentials and use this registry on a proxy project working smoothly. Everyday there is a change in some secret and the registry stops working. 

### Are you using any custom parameters or values?

```yaml
    helm:
      parameters:
      - name: externalURL
        value: "https://harbor.com"
      - name: exposureType
        value: "ingress"
      - name: global.defaultStorageClass
        value: "default"
      - name: persistence.persistentVolumeClaim.jobservice.storageClass
        value: "azurefile"
      - name: persistence.persistentVolumeClaim.jobservice.accessMode
        value: "ReadWriteMany"
      - name: persistence.persistentVolumeClaim.jobservice.size
        value: "1Gi"
      - name: persistence.persistentVolumeClaim.registry.storageClass
        value: "azurefile"
      - name: persistence.persistentVolumeClaim.registry.accessMode
        value: "ReadWriteMany"
      - name: persistence.persistentVolumeClaim.registry.size
        value: "4Gi"
      values: |-
        adminPassword: "12345qwerty"
        ingress:
          core:
            hostname: "harbor.com"
```

### What is the expected behavior?

Don't have to create a new token with another user everyday.

### What do you see instead?

When I try to edit the endpoint I got the error "Failed to ping endpoint" when I push the Test Connection button. Even if I create a new token I still got the same error. I have to use another pair of Access ID and Access Secret to make it work.

Everyday there are 2 deployments that got redeployed because of changes in their annotations: _harbor-jobservice_ and _harbor-registry_. If I diff between deployment rollout history versions I see this:
```diff
$ diff revA.yaml revB.yaml
1c1
< deployment.apps/harbor-jobservice with revision #3
---
> deployment.apps/harbor-jobservice with revision #4
9c9
< 	pod-template-hash=5d8d6gg99
---
> 	pod-template-hash=b59cbbdcd
12,13c12,13
< 	checksum/secret: 87bba37dfb2d...
< 	checksum/secret-core: ff8b8e54f27d...
---
> 	checksum/secret: b71a1ce2bd33e...
> 	checksum/secret-core: d57d13cf2...
```

I got those yaml files with: `k -n harbor rollout history deployment/harbor-jobservice --revision=X > revX.yaml`
