### ISSUE TITLE
[rabbitmq] Don't Regenerate the Password

### ISSUE THREAD

**Issue by kferrone** [bitnami/charts#3094]
**Which chart**:
RabbitMQ 7.5.3

**Describe the bug**
If you update the chart the the password in the secret will regenerate and cause RabbitMQ to end up in an infinite crashloop.

**To Reproduce**
1. leave `auth.password` empty in the values
2. run the chart
3. change something, anything at all
4. re-deploy
5. notice the password is changed after an update

**Expected behavior**
Leave the password and erlang cookie alone when updating. 

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersi
on:"go1.14.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e
2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin
/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325
af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platf
orm:"linux/amd64"}
```

**Additional context**
All you need to do to solve this issue is add the following annotation to the secret in [this file](https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/templates/secrets.yaml)
```yaml
annotations:
  "helm.sh/resource-policy": no-upgrade-existing
```

**Comment by joancafom** [comment]
Hi @kferrone,

Thanks very much for your issue! When upgrading the application, the old values for passwords must be provided to ensure they are not altered. For further details on this, the process is described in the [Upgrading section](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#upgrading) of README.md. 

We are currently working on improving this behaviour, analysing and evaluating alternatives on what is the best way to tackle this problem. Thank you very much for your proposal, we will take it into account when implementing changes.

Thanks!

**Comment by kferrone** [comment]
I have made plenty of charts where the following works just fine:
```yaml
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/resource-policy": no-upgrade-existing
```
Then no secrets are changed after an update.

If anything at least allow us to add our own annotations to the secret. For example in the values file you could have something like:
```yaml
secretAnnotations: {}
```
Then I can do the following in my values.yaml:
```yaml
secretAnnotations:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/resource-policy": no-upgrade-existing
```
This way I can use the built in Helm feature for handling generated secrets.

**Comment by joancafom** [comment]
Hi @kferrone 

I am interested in this alternative, but have been investigating about the `resource-policy: no-upgrade-existing` and it seems like the official Helm release does not support it. I have been unable to find any official documentation nor [source code ](https://github.com/helm/helm/blob/master/pkg/kube/resource_policy.go) associated to it in the official repo (the only value that seems to be supported is `keep`).

I might be wrong, but it would be bizarre using an annotation by default that is not officially supported by helm itself. Do you by any chance have more information about it?

Thanks!

**Comment by kferrone** [comment]
Here is what I found for reference: https://github.com/helm/helm/pull/5290/files

I can't seem to find much about the `no-upgrade-existing`? I was told somewhere to do this and it has just worked for me. It seems Helm may have just gone with `keep`. 

Either way, I do know with `"helm.sh/hook": pre-install` on the secret, this will also give the desired effect as well. I simply know this works from experience. When secret is run in pre-install, then no other operation (including delete) will touch the secret from then on simply because install phase only ever happens once. Just don't give it a delete policy. 

I agree defaulting any of these annotations without proper testing and discussion is not desired. However, I'm extremely confident in what I need to do, please allow users to add their own arbitrary annotations.

Currently rabbitmq chart already supports arbitrary annotations on the following:
 - `.Values.podAnnotations`
 - `.Values.service.annotations`
 - `.Values.ingress.annotations`

In the values simply add a section to add arbitrary annotations to the secret.
values.yaml
```yaml
secretAnnotations: {}
```
In my values.yaml; I'll just overkill it to guarantee the secret won't change. 
```yaml
secretAnnotations:
  "helm.sh/hook": pre-install
  "helm.sh/resource-policy": keep
```

Here is the needed source code in the [secrets.yaml in the templates](https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/templates/secrets.yaml)
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  annotations: {{ toYaml .Values.secretAnnotations | nindent 4 }}
```
