### ISSUE TITLE
[bitnami/thanos] Query can't detect storagegateway and can't fetch metrics from it.

### ISSUE THREAD

**Issue by Wyifei** [bitnami/charts#30978]
### Name and Version

helm chart version: biname/thanos: 15.7.2.1

Thanos image version: bitnami/thanos:0.36.1-debian-12-r0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. args of query:
```yaml
      - args:
        - query
        - --log.level=info
        - --log.format=logfmt
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --query.replica-label=replica
        - --endpoint=dnssrv+_grpc._tcp.prod-thanos-discovery.kube-system.svc.cluster.local
        - --endpoint=dnssrv+_grpc._tcp.prod-thanos-storegateway.kube-system.svc.cluster.local
        - --alert.query-url=http://prod-thanos-query.kube-system.svc.cluster.local:9090
        - --query.replica-label=prometheus_replica
```
2. thanos storagegateway service:
```yaml
      apiVersion: v1
      kind: Service
        name: prod-thanos-storegateway
        namespace: kube-system
      spec:
        clusterIP: 172.20.3.221
        clusterIPs:
        - 172.20.3.221
        internalTrafficPolicy: Cluster
        ipFamilies:
        - IPv4
        ipFamilyPolicy: SingleStack
        ports:
        - name: http
          port: 9090
          protocol: TCP
          targetPort: http
        - name: grpc
          port: 10901
          protocol: TCP
          targetPort: grpc
        selector:
          app.kubernetes.io/component: storegateway
          app.kubernetes.io/instance: prod-thanos
          app.kubernetes.io/name: thanos
        sessionAffinity: None
        type: ClusterIP
```

and there is a valid endpoint for this service
```
NAME                                                   ENDPOINTS                                                                  AGE
prod-thanos-storegateway                  10.201.32.221:10902,10.201.32.221:10901                                    42m
```
3. query init logs, there isn't log like "add storage gateway as new store":
```
ts=2024-12-11T08:01:03.414459747Z caller=options.go:26 level=info protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
ts=2024-12-11T08:01:03.414882382Z caller=query.go:833 level=info msg="starting query node"
ts=2024-12-11T08:01:03.415174003Z caller=intrumentation.go:75 level=info msg="changing probe status" status=healthy
ts=2024-12-11T08:01:03.415196769Z caller=http.go:73 level=info service=http/server component=query msg="listening for requests and metrics" address=0.0.0.0:10902
ts=2024-12-11T08:01:03.415331267Z caller=tls_config.go:313 level=info service=http/server component=query msg="Listening on" address=[::]:10902
ts=2024-12-11T08:01:03.415345267Z caller=tls_config.go:316 level=info service=http/server component=query msg="TLS is disabled." http2=false address=[::]:10902
ts=2024-12-11T08:01:03.415371372Z caller=intrumentation.go:56 level=info msg="changing probe status" status=ready
ts=2024-12-11T08:01:03.415387593Z caller=grpc.go:167 level=info service=gRPC/server component=query msg="listening for serving gRPC" address=0.0.0.0:10901
ts=2024-12-11T08:01:09.046855579Z caller=endpointset.go:436 level=info component=endpointset msg="adding new sidecar with [storeEndpoints rulesAPI exemplarsAPI targetsAPI MetricMetadataAPI]" address=10.201.33.226:10901 extLset="{prometheus=\"kube-system/prod-prometheus\", prometheus_replica=\"prometheus-prod-prometheus-0\"}"
ts=2024-12-11T08:01:09.04689161Z caller=endpointset.go:436 level=info component=endpointset msg="adding new sidecar with [storeEndpoints rulesAPI exemplarsAPI targetsAPI MetricMetadataAPI]" address=10.201.33.75:10901 extLset="{prometheus=\"kube-system/prod-prometheus\", prometheus_replica=\"prometheus-prod-prometheus-1\"}"
ts=2024-12-11T08:01:09.046908401Z caller=endpointset.go:436 level=info component=endpointset msg="adding new store with [storeEndpoints]" address=172.20.3.221:10901 extLset="{prometheus=\"kube-system/prod\", prometheus_replica=\"prometheus-prod-0\"},{prometheus=\"kube-system/prod\", prometheus_replica=\"prometheus-prod-1\"},{prometheus=\"kube-system/prod-prometheus\", prometheus_replica=\"prometheus-prod-prometheus-0\"},{prometheus=\"kube-system/prod-prometheus\", prometheus_replica=\"prometheus-prod-prometheus-1\"}
```
4.In query UI, there is only prometheus store but not storagegateway

![image](https://github.com/user-attachments/assets/61c02f23-b49e-46b5-916d-d74db4beee54)

5. the result is query can't fetch metrics from storagegateway(backend is s3 bucket)

### Are you using any custom parameters or values?
```yaml
query:
  enabled: true
  dnsDiscovery:
    sidecarsService: ${environment}-thanos-discovery
    sidecarsNamespace: kube-system
  extraFlags:
    - "--query.replica-label=prometheus_replica"
  resources:
    limits:
      cpu: 50m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 50Mi
```
