### ISSUE TITLE
[bitnami/mongodb-sharded] cannot create directory '/bitnami/mongodb/data/db' in arbiter pod

### ISSUE THREAD

**Issue by shuhengyang** [bitnami/charts#30979]
### Name and Version

bitnami/mongodb-sharded

### What architecture are you using?

None

### What steps will reproduce the bug?
```
helm install mongodb  bitnami/mongodb-sharded --version 9.1.0 -f value.yaml 
```
### Are you using any custom parameters or values?
```
persistence.enables: false
```
### What do you see instead?
```
arbiter  pod ERROR: mkdir: cannot create directory '/bitnami/mongodb/data/db': Read-only file system
```

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by F-Node-Karlsruhe** [comment]
I ran into the same issue. Shouldn't be the standard db directory already created upon deployment? I know it needs to be there for the arbiter even though it does own any database.

What is the fix here? I already gave it its own persistence but this does not fix the problem.

```
shardsvr:
  arbiter:
    replicaCount: 1
  dataNode:
    replicaCount: 3
    persistence:
      enabled: true
      storageClass: local-path
      size: 32Gi
    resources:
      limits:
        memory: "8Gi"
      requests:
        cpu: "1000m"
        memory: "4Gi"
```
