### ISSUE TITLE
Elasticsearch volume cersts is empty-dir when security.enabled=true and security.autoGenerated=true 

### ISSUE THREAD

**Issue by Rebyrg** [bitnami/charts#30988]
### Name and Version

21.3.10

### What architecture are you using?

None

### What steps will reproduce the bug?

deploy the helm chart with the provided values.yaml below

### Are you using any custom parameters or values?

```yaml
security:
  enabled: true
  elasticPassword: "XXXX"
  tls:
    autoGenerated: true
    verificationMode: "none"
master:
  replicaCount: 3
  masterOnly: false
  extraRoles: ["data"]
  resourcesPreset: "medium"
  heapSize: "512m"
  persistence:
    storageClass: "gold"
    size: "2Gi"
data:
  replicaCount: 0
coordinating:
  replicaCount: 0
ingest:
  enabled: false
metrics:
  enabled: false

```

### What is the expected behavior?

3 nodes cluster up and running with TLS enabled and generated self signed certs mounted as volumes to nodes

### What do you see instead?

errors in logs of master node:

```
elasticsearch 16:27:21.73 INFO  ==>
elasticsearch 16:27:21.74 INFO  ==> Welcome to the Bitnami elasticsearch container
elasticsearch 16:27:21.75 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
elasticsearch 16:27:21.76 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
elasticsearch 16:27:21.77 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
elasticsearch 16:27:21.80 INFO  ==>
elasticsearch 16:27:21.82 INFO  ==> ** Starting Elasticsearch setup **
elasticsearch 16:27:21.93 WARN  ==> Setting ELASTICSEARCH_IS_DEDICATED_NODE is disabled.
elasticsearch 16:27:21.94 WARN  ==> ELASTICSEARCH_NODE_ROLES will be ignored and Elasticsearch will asume all different roles.
elasticsearch 16:27:21.94 ERROR ==> In order to configure the TLS encryption for Elasticsearch Transport you must provide your node key, certificate and a valid certification_authority certificate.
elasticsearch 16:27:21.95 ERROR ==> In order to configure the TLS encryption for Elasticsearch you must provide your node key, certificate and a valid certification_authority certificate.
```

### Additional information

The problem is in the file https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/templates/master/statefulset.yaml line number 356. 
When you enable security by setting `security.enabled=true` you always have empty-dir volume. It should be elasticsearch-certificates instead.

Change:
```yaml
            {{- if .Values.security.enabled }}
            - name: empty-dir
              mountPath: /opt/bitnami/elasticsearch/config/certs
              subPath: certs
            {{- end }}
```
to
```yaml
            {{- if .Values.security.enabled }}
            - name: elasticsearch-certificates
              mountPath: /opt/bitnami/elasticsearch/config/certs
            {{- end }}
```
