### ISSUE TITLE
[bitnami/schema-registry] Helm Install Fails with Kafka JKS Secret Error when Using AWS MSK with SSL

### ISSUE THREAD

**Issue by Haebuk** [bitnami/charts#31004]
### Name and Version

bitnami/schema-registry 7.8.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set up AWS MSK cluster with SSL encryption enabled
2. Deploy Schema Registry on EKS using Helm chart
3. Configure values.yaml with:
```yaml
kafka:
  enabled: false

externalKafka:
  brokers:
    - SSL://<my-first-broker-endpoint>:9094
    - SSL://<my-second-broker-endpoint>:9094
  listener:
    protocol: SSL
```
4. Run `helm install schema-registry bitnami/schema-registry -f values.yaml`
5. The installation fails with an error requiring JKS files even though we're using AWS-managed certificates:
```
kafka: auth.kafka.jksSecret
A secret containing the Schema Registry JKS files is required when TLS encryption is enabled
```

### What is the expected behavior?

The Helm chart should successfully install without requiring JKS files when using AWS MSK with SSL, as certificate management is handled by AWS MSK service.

### Additional information

Using AWS MSK for Kafka cluster
Certificates are managed by AWS
Schema Registry is being deployed on EKS
No manual JKS management is needed in the AWS MSK environment

We already have several applications deployed on EKS successfully communicating with MSK without any additional certificate configuration, which makes this JKS requirement seem unnatural and inconsistent with our existing setup.
