### ISSUE TITLE
Can't connect to Valkey when using password from existing secret

### ISSUE THREAD

**Issue by franz-dalitz** [bitnami/charts#31009]
### Name and Version

bitnami/valkey 2.2.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Environment: Rancher managed RKE2 clusters running on OpenSUSE Leap with applications managed by ArgoCD + Kustomize.

I created the secret "valkey" with the "password" field by just writing a secret manifest and applying it to the cluster in the same namespace as my valkey:

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: valkey
data:
  password: my_password_in_base64
```

This is my kustomization:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: valkey
  repo: oci://registry-1.docker.io/bitnamicharts
  releaseName: valkey
  version: 2.2.0
  valuesFile: ../../../base/valkey/values.yaml
  namespace: dev
```

I then tried to connect to valkey-primary using a client container as described in one of the valkey guides: https://valkey.io/blog/using-bitnami-valkey-chart/

```bash
kubectl run --namespace dev valkey-client --restart='Never' --env VALKEY_PASSWORD=my_valkey_password  --image docker.io/bitnami/valkey:8.0.0-debian-12-r0 --command -- sleep infinity
```
```bash
kubectl exec --tty -i valkey-client --namespace dev -- bash
```

Then doing `valkey-cli -h valkey-primary` and `auth my_password`.

### Are you using any custom parameters or values?

this is my values.yaml file content:

```yaml
global:
  defaultStorageClass: local-path

auth:
  enabled: true
  usePassword: true
  existingSecret: valkey
  existingSecretPasswordKey: password
```

### What is the expected behavior?

I'd assume a connection to be established successfully, then being able to test the setting and getting of values.

### What do you see instead?

I get the following error: `(error) WRONGPASS invalid username-password pair or user is disabled.`, even though I made sure of course, that namespaces and my chosen password are identical across all places.
Checking the valkey-primary-0 pod with `printenv` I can see that the `VALKEY_PASSWORD` env var is correct, yet connecting doesn't work.

### Additional information

I had Valkey deployed with its own password generation before, which worked flawlessly, though either valkey rotates passwords sometimes or there is an issue on my end with Argo, but since the password kept changing other pods using Valkey would lose the initially correct password and the ability to connect to Valkey, so I assumed this is what I need to do.
I also tested the password file version as suggested on the artifacthub page: https://artifacthub.io/packages/helm/bitnami/valkey but that didn't work, exactly the same issue.
