### ISSUE TITLE
bitnami/kafka failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256

### ISSUE THREAD

**Issue by wangchao732** [bitnami/charts#31010]
### Name and Version

bitnami/kafka  30.1.5

### What steps will reproduce the bug?
```yaml
externalAccess: true
```

```
# Listeners configuration
listeners=CLIENT://:9092,INTERNAL://:9095,EXTERNAL://:9094,CONTROLLER://:9093
advertised.listeners=CLIENT://:9092,INTERNAL://:9095
#listener.security.protocol.map=CLIENT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
listener.security.protocol.map=CLIENT:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
# KRaft process roles
process.roles=controller,broker
#node.id=
controller.listener.names=CONTROLLER
controller.quorum.voters=0@kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9093,1@kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9093,2@kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9093
# Kraft Controller listener SASL settings
sasl.mechanism.controller.protocol=PLAIN
listener.name.controller.sasl.enabled.mechanisms=PLAIN
listener.name.controller.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="controller_user" password="controller-password-placeholder" user_controller_user="controller-password-placeholder";
# Kafka data logs directory
log.dir=/bitnami/kafka/data
# Kafka application logs directory
logs.dir=/opt/bitnami/kafka/logs

# Common Kafka Configuration

sasl.enabled.mechanisms=PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
# Interbroker configuration
inter.broker.listener.name=INTERNAL
sasl.mechanism.inter.broker.protocol=PLAIN
# Listeners SASL JAAS configuration
listener.name.client.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required user_user1="password-placeholder-0";
listener.name.client.scram-sha-256.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required;
listener.name.client.scram-sha-512.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required;
listener.name.internal.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="inter_broker_user" password="interbroker-password-placeholder" user_inter_broker_user="interbroker-password-placeholder" user_user1="password-placeholder-0";
listener.name.internal.scram-sha-256.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="inter_broker_user" password="interbroker-password-placeholder";
listener.name.internal.scram-sha-512.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="inter_broker_user" password="interbroker-password-placeholder";
listener.name.external.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required user_user1="password-placeholder-0";
listener.name.external.scram-sha-256.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required;
listener.name.external.scram-sha-512.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required;
# End of SASL JAAS configuration

# Custom Kafka Configuration
```
When I use:
```
listener.security.protocol.map=CLIENT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
```
External production and consumption are both normal.

### Are you using any custom parameters or values?
```yaml
existingConfigmap: ""
extraConfig: ""
extraConfigYaml: {}
secretConfig: ""
existingSecretConfig: ""
log4j: ""
existingLog4jConfigMap: ""
heapOpts: -XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75
brokerRackAssignment: ""
interBrokerProtocolVersion: ""
listeners:
  client:
    containerPort: 9092
    protocol: SASL_PLAINTEXT
    name: CLIENT
    sslClientAuth: ""
  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: SASL_PLAINTEXT
    sslClientAuth: ""
  interbroker:
    containerPort: 9094
    protocol: SASL_PLAINTEXT
    name: INTERNAL
    sslClientAuth: ""
  external:
    containerPort: 9095
    protocol: SASL_PLAINTEXT
    name: EXTERNAL
    sslClientAuth: ""
  extraListeners: []
  overrideListeners: ""
  advertisedListeners: ""
  securityProtocolMap: ""
sasl:
  enabledMechanisms: PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
  interBrokerMechanism: PLAIN
  controllerMechanism: PLAIN
  oauthbearer:
    tokenEndpointUrl: ""
    jwksEndpointUrl: ""
    expectedAudience: ""
    subClaimName: "sub"
  interbroker:
    user: inter_broker_user
    password: ""
    clientId: inter_broker_client
    clientSecret: ""
  controller:
    user: controller_user
    password: ""
    clientId: controller_broker_client
    clientSecret: ""
  client:
    users:
      - user1
    passwords: ""
  zookeeper:
    user: ""
    password: ""
  existingSecret: ""
tls:
  type: JKS
  pemChainIncluded: false
  existingSecret: ""
  autoGenerated: false
  customAltNames: []
  passwordsSecret: ""
  passwordsSecretKeystoreKey: keystore-password
  passwordsSecretTruststoreKey: truststore-password
  passwordsSecretPemPasswordKey: ""
  keystorePassword: ""
  truststorePassword: ""
  keyPassword: ""
  jksKeystoreKey: ""
  jksTruststoreSecret: ""
  jksTruststoreKey: ""
  endpointIdentificationAlgorithm: https
  sslClientAuth: "required"

broker:
  replicaCount: 0
  minId: 100
  zookeeperMigrationMode: false
  config: ""
  existingConfigmap: ""
  extraConfig: ""
  extraConfigYaml: {}
  secretConfig: ""
  existingSecretConfig: ""
  heapOpts: -Xmx1024m -Xms1024m
  command: []
  args: []
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraContainerPorts: []
  automountServiceAccountToken: false

service:
  type: ClusterIP
  ports:
    client: 9092
    controller: 9093
    interbroker: 9094
    external: 9095
  extraPorts: []
  nodePorts:
    client: ""
    external: ""
  sessionAffinity: None
  sessionAffinityConfig: {}
  clusterIP: ""
  loadBalancerIP: ""
  loadBalancerClass: ""
  loadBalancerSourceRanges: []
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  annotations: {}
  headless:
    controller:
      annotations: {}
      labels: {}
    broker:
      annotations: {}
      labels: {}
externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
    image:
      registry: ""
      repository: registry.cn-hongkong.aliyuncs.com/bcldops/kubectl
      tag: 1.31.1-debian-12-r2
      digest: ""
      pullPolicy: IfNotPresent
      pullSecrets: []
    resourcesPreset: "nano"
    resources: {}
    containerSecurityContext:
      enabled: true
      seLinuxOptions: {}
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: "RuntimeDefault"
  controller:
    forceExpose: false
    service:
      type: NodePort
      ports:
        external: 9094
      loadBalancerClass: ""
      loadBalancerIPs: []
      loadBalancerNames: []
      loadBalancerAnnotations: []
      loadBalancerSourceRanges: []
      allocateLoadBalancerNodePorts: true
      nodePorts: []
      externalIPs: []
      useHostIPs: false
      usePodIPs: false
      domain: ""
      publishNotReadyAddresses: false
      labels: {}
      annotations: {}
      extraPorts: []
  broker:
    service:
      type: LoadBalancer
      ports:
        external: 9094
      loadBalancerClass: ""
      loadBalancerIPs: []
      loadBalancerNames: []
      loadBalancerAnnotations: []
      loadBalancerSourceRanges: []
      allocateLoadBalancerNodePorts: true
      nodePorts: []
      externalIPs: []
      useHostIPs: false
      usePodIPs: false
      domain: ""
      publishNotReadyAddresses: false
      labels: {}
      annotations: {}
      extraPorts: []

serviceAccount:
  create: true
  name: ""
  automountServiceAccountToken: false
  annotations: {}
rbac:
  create: true
```

### What do you see instead?
```console
$ cat /tmp/client.properties 
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-256
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required  username="user1" password="dY1LQ9rI4N";


$ kafka-console-producer.sh --producer.config /tmp/client.properties  --broker-list kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092 --topic test

>a
[2024-12-12 11:14:55,280] ERROR [Producer clientId=console-producer] Connection to node -3 (kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local/10.10.4.247:9092) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256 (org.apache.kafka.clients.NetworkClient)
[2024-12-12 11:14:55,281] WARN [Producer clientId=console-producer] Bootstrap broker kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092 (id: -3 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2024-12-12 11:14:55,849] ERROR [Producer clientId=console-producer] Connection to node -2 (kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local/10.10.3.78:9092) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256 (org.apache.kafka.clients.NetworkClient)
[2024-12-12 11:14:55,849] WARN [Producer clientId=console-producer] Bootstrap broker kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092 (id: -2 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
```
