### ISSUE TITLE
Provisioned Users not set in Mongo, cannot connect with them

### ISSUE THREAD

**Issue by BenjaminFourmaux** [bitnami/charts#31017]
### Name and Version

bitnami/mongodb 2.19.2

### What architecture are you using?

None

### What steps will reproduce the bug?

- Docker image: bitnami/mongodb:6.0.9
- ReplicaSet deployment mode
- Provisioned extra users

### Are you using any custom parameters or values?

Extra users provisioned in Values.yaml via `auth.usernames` and `auth.passwords`
Like :
```yaml
auth:
    rootUser: root
    rootPassword: "root"
    usernames:
      - "myapp_user"
    passwords:
      - "1234"
    databases:
      - "myapp"
```

### What is the expected behavior?

It's supposed to provisioned "myapp_user" user and I must to be able to connect with.
No user found when I type `db.getUsers()` in mongo Terminal, no where.

### What do you see instead?

- In deployed Kubernetes manifest of the ReplicaSet, env var `MONGODB_EXTRA_USERNAMES`, `MONGODB_EXTRA_PASSWORDS` and `MONGODB_EXTRA_DATABASES` are here.
- In the Secret `mongodb`, the `mongodb-passwords` data is set with extra password
- In the container terminal, the env var `$MONGODB_EXTRA_DATABASES` is set with extra password
- ConnectionString `mongodb://myapp_user:1234@mongodb-0.mongodb-headless.mynamespace.svc.cluster.local:27017,mongodb-1.mongodb-headless.mynamespace.svc.cluster.local:27017,mongodb-2.mongodb-headless.mynamespace.svc.cluster.local:27017,/?replicaSet=rs0` doesn't work, even with flag `--authenticationDatabase admin` or `--authenticationDatabase myapp`.
