### ISSUE TITLE
[bitnami/external-dns] unsupported protocol scheme "oci"

### ISSUE THREAD

**Issue by oliveirajoaop** [bitnami/charts#31029]
### Name and Version

bitnami/external-dns

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1 - Successfully deployed bitnami/external-dns version 8.5.1 to eks version 1.30.6 with flux 2.4.0
2 - Update external dns from version 8.5.1 to 8.6.0, 8.6.1 or 8.7.0

### Are you using any custom parameters or values?

No

### What is the expected behavior?

The update should run with no errors.

### What do you see instead?

Updating the helm-release to version 8.6.0, 8.6.1 or 8.7.0 will result in error with the message: 
chart pull error: failed to download chart for remote reference: Get "oci://registry-1.docker.io/bitnamicharts/external-dns:8.6.0": unsupported protocol scheme "oci" and chart pull error.

### Additional information

Helm Repo
```yaml---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.bitnami.com/bitnami
```

Helm release
```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 8.6.0 (8.6.1 or 8.7.0)
  interval: 1m
```
