### ISSUE TITLE
extra label in pod selector of  kibana's networkpolicy means it won't become ready or start properly

### ISSUE THREAD

**Issue by pfrydids** [bitnami/charts#31036]
### Name and Version

bitnami/kibana 11.4.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Standard deployment of kibana via the elasticsearch helm chart with the addition of a restrictive networkpolicy like
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dns-internal
spec:
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
  podSelector: {}
  policyTypes:
    - Egress
```
this will match the kibana pod 

The networkpolicy of the kibana chart will have an erroneous extra selector which is not present as a label on the kibana pod

https://github.com/bitnami/charts/blob/main/bitnami/kibana/templates/networkpolicy.yaml#L21

and so the networkpolicy allowing unfettered egress will not be applied.

I think line 21 should be removed.

### What is the expected behavior?

kibana will move to a ready state

### What do you see instead?

kibana is running but not ready
```
[2024-12-13T15:53:35.785+00:00][ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes.
```
