### ISSUE TITLE
Implement support for new protocol Cap'N'Proto in Thanos 

### ISSUE THREAD

**Issue by RainbowHerbicides** [bitnami/charts#31033]
### Name and Version

bitnami/thanos 15.9.2

### What is the problem this feature will solve?

Thanos team introduced a more efficient replication protocol [Cap’N Proto](https://capnproto.org/), mentioned here https://thanos.io/tip/components/receive.md/#replication-protocols but Helm chart Network policy (also STS and SVC) do not allow setting up permissions to use it (default flag + value `--receive.capnproto-address="0.0.0.0:19391"`). 

In my case - this protocol was used when Receiver split between ReceiveDistributor (set flag `--receive.replication-protocol=capnproto`) and Receive (set flag `--receive.capnproto-address="0.0.0.0:19391"`) and it showed a significant drop in CPU/RAM usage.

### What is the feature you are proposing to solve the problem?

Run several tests and just setting the `capnproto` port alongside with `http`, `grpc` and `remote` ports defined in Networkpolicy template is enough to make it work:
```yaml
spec:
  ingress:
  - ports:
    - port: 10902
      protocol: TCP
    - port: 10902
      protocol: TCP
    - port: 10901
      protocol: TCP
    - port: 10901
      protocol: TCP
    - port: 19291
      protocol: TCP
    - port: 19291
      protocol: TCP
    - port: 19391 <--- what we want to add
      protocol: TCP
```
IMHO, this should be a pretty trivial modification of the template, just need to add 2 lines in `thanos/templates/receive/networkpolicy.yaml`:
```yaml
        - port: {{ .Values.receive.containerPorts.capnproto }}
        - port: {{ .Values.receive.service.ports.capnproto }}
```
and default value in `values.yml` file:
```yaml
  containerPorts:
    http: 10902
    grpc: 10901
    remote: 19291
    capnproto: 19391
---
    ports:
      http: 10902
      grpc: 10901
      remote: 19291
      capnproto: 19391
```

During my tests, only modification of Networkpolicy was necessary to make it work correctly. Modification of Service or STS - haven't added any additional value 

### What alternatives have you considered?

There were 2 alternatives:
1. Fully disable Networkpolicy for Receive component
2. Fully disable Networkpolicy for the Receive component and write one that implements the same functionality but additionally allows ingress to 19391 port
