### ISSUE TITLE
[bitnami/mongodb-sharded] systemLogVerbosity is ignored

### ISSUE THREAD

**Issue by Nickmman** [bitnami/charts#31057]
### Name and Version

bitnami/mongodb-sharded 7.8.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy with ArgoCD
2. Add custom value to set verbosity
3. Watch as setting is ignored

### Are you using any custom parameters or values?

```
common:
  systemLogVerbosity: 3
systemLogVerbosity: 3
```

### What is the expected behavior?

MONGODB_SYSTEM_LOG_VERBOSITY is set to 3

### What do you see instead?

MONGODB_SYSTEM_LOG_VERBOSITY is set to 0
```
kubectl get application -n argocd mongodb-sharded -o yaml | grep -B1 systemLogVerbosity
        common:
          systemLogVerbosity: 3
        systemLogVerbosity: 3
--
              storageClass: ceph-block
          systemLogVerbosity: 3
--
          common:
            systemLogVerbosity: 3
--
          common:
            systemLogVerbosity: 3
          systemLogVerbosity: 3
--
            common:
              systemLogVerbosity: 3
            systemLogVerbosity: 3
--
            common:
              systemLogVerbosity: 3
            systemLogVerbosity: 3
```

From mongodb:
```
kubectl get all -o yaml | grep -A1 MONGODB_SYSTEM_LOG_VERBOSITY
      - name: MONGODB_SYSTEM_LOG_VERBOSITY
        value: "0"
--
      - name: MONGODB_SYSTEM_LOG_VERBOSITY
        value: "0"
--
      - name: MONGODB_SYSTEM_LOG_VERBOSITY
        value: "0"
--
      - name: MONGODB_SYSTEM_LOG_VERBOSITY
        value: "0"
--
      - name: MONGODB_SYSTEM_LOG_VERBOSITY
        value: "0"
--
      - name: MONGODB_SYSTEM_LOG_VERBOSITY
        value: "0"
--
      - name: MONGODB_SYSTEM_LOG_VERBOSITY
        value: "0"
--
      - name: MONGODB_SYSTEM_LOG_VERBOSITY
        value: "0"
--
      - name: MONGODB_SYSTEM_LOG_VERBOSITY
        value: "0"
--
      - name: MONGODB_SYSTEM_LOG_VERBOSITY
        value: "0"
--
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
--
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
--
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
--
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
--
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
```

### Additional information

Var is handled via https://github.com/bitnami/charts/blob/mongodb-sharded/7.8.0/bitnami/mongodb/templates/replicaset/statefulset.yaml#L288-L289
