### ISSUE TITLE
[binami/redis] Issue with Write Operations in Redis Bitnami Chart When Accessing via Ingress

### ISSUE THREAD

**Issue by er-sami777** [bitnami/charts#31067]
### Name and Version

bitnami/redis 20.2.1

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I have deployed Redis using the Bitnami Redis Helm chart with the following configuration (see below). The chart successfully creates a StatefulSet and two services: redis and redis-headless, both of type ClusterIP. I have configured an ingress to access Redis from outside the cluster, but I am encountering an issue with performing write operations using the domain attached to the ingress.

Step 1:
```bash
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install redis bitnami/redis -f redis-values.yaml --namespace redis --create-namespace
```
 
 ========= redis-values.yaml =========
```yaml
architecture: replication
sentinel:
  enabled: true
    
auth:
  enabled: true
  password: "password123"

master:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "gp3"
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: master

replica:
  replicaCount: 3
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "gp3"
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: replica
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50

sentinel:
  enabled: true

volumePermissions:
  enabled: true

global:
  storageClass: "gp3"

##### Monitoring Configuration #####
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: "monitoring"
    interval: 30s
```

================== ingress.yaml ============

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-ingress
  namespace: redis
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    terraform.io/destroy-order: "0"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/service-port: "6379"
spec:
  ingressClassName: nginx
  rules:
    - host: redis.smcdevops.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redis
                port:
                  number: 6379
```

I already added `6379` as listener in the created `NLB`

### Are you using any custom parameters or values?

- uthentication: Enabled with the password `password123`.
- Persistence: Enabled with a storage class of `gp3` and size of `10Gi` for both the master and replica.
- Topology Spread Constraints: Defined for both master and replica components.
- Sentinel: Enabled for `high availability`.
- Ingress Configuration: Added listener port `6397` for Redis connection.

### What is the expected behavior?

Write operations should work consistently when accessing Redis through the ingress domain, similar to how read operations are functioning correctly.

What do you see instead?: Write operations fail intermittently when accessing Redis via the ingress domain. Sometimes, I am able to perform write operations, but it is inconsistent.

### What do you see instead?

Write operations fail intermittently when accessing Redis via the ingress domain. Sometimes, I am able to perform write operations, but it is inconsistent.

### Additional information

- The Redis deployment is running with the Bitnami Redis Helm chart.
- The Redis setup is configured with replication and persistence enabled for the master and replica nodes.
- The ingress is configured to route traffic to `redis` and `redis-headless` services of type `ClusterIP`.
- The issue occurs when using the domain configured in the ingress for accessing Redis from `outside the Kubernetes cluster`.
- The write failure behavior is unpredictable and `occurs most of the time; say 9/10`.
