### ISSUE TITLE
[bitnami/Influxdb] RetentionDays parameter does not work on AWS S3 Storage

### ISSUE THREAD

**Issue by syakirali** [bitnami/charts#31084]
### Name and Version

bitnami/influxdb 6.5.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install influxdb chart with the backup option enabled and set uploadProviders to aws

### Are you using any custom parameters or values?

```yaml
backup:
  enabled: true
  retentionDays: 1
  cronjob:
    schedule: "0 0 * * *"

  uploadProviders:
    aws:
      enabled: true
      accessKeyID: "secret"
      secretAccessKey: "secret"
      bucketName: "s3://influxdb"
      endpoint: "http://s3url"

persistence:
  enabled: true
  size: 15Gi
```

### What is the expected behavior?

The old backup in AWS S3 storage was also deleted after the aws sync command.

### What do you see instead?

The old backup in AWS S3 storage still exists.
