### ISSUE TITLE
bitnami/external-dns  --- how to form fqdnTemplate with Values...

### ISSUE THREAD

**Issue by chris8205** [bitnami/charts#31081]
### Name and Version

bitnami/external-dns

### What architecture are you using?

amd64

### What steps will reproduce the bug?

i would like to do something like this..

```yaml
global:
  domain: mydomain.tld

external-dns:
  fqdnTemplates:
    - {{`{{.Name}}.{{.Namespace}}`}}.{{ .Values.global.domain }}
```

At the end I would like to get template names like
```
MyService.MyNamespace.mydomain.tld
```
### Are you using any custom parameters or values?

think something like this...
```yaml
  fqdnTemplates:
    - {{`{{.Name}}.{{.Namespace}}`}}.{{ .Values.global.domain }}
```
### What is the expected behavior?
```
--fqdnTemplate={{.Name}}.{{.Namespace}}.mydomain.tld
```
### What do you see instead?
```
--fqdnTemplate={{`{{.Name}}.{{.Namespace}}`}}.{{ .Values.global.domain }}
```
