### ISSUE TITLE
[bitnami/thanos] Inject shard environment variables into StoreGateway to enable dynamic discovery of peers for Groupcache.

### ISSUE THREAD

**Issue by debuggedme** [bitnami/charts#31111]
### Name and Version

bitnami/thanos 15.9.2

### What is the problem this feature will solve?

Inject shard environment variables into StoreGateway to enable dynamic discovery of peers for Groupcache.  

https://thanos.io/tip/components/store.md/#experimental-groupcache-caching-bucket-provider

**Comment by debuggedme** [comment]
```yaml
      --store.caching-bucket.config=
      type: GROUPCACHE  
      config:  
        self_url: http://$(POD_IP):10902
        peers:
          - dns+http://thanos-storegateway-$(SHARD).default.svc.cluster.local:10902
        groupcache_group: test_group
        dns_interval: 1s
        timeout: 2s
```
