### ISSUE TITLE
Incorrect publicBaseUrl  reference from  https://github.com/bitnami/charts/pull/28543

### ISSUE THREAD

**Issue by busyboy77** [bitnami/charts#31131]
### Name and Version

bitnami/kibana 11.4.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

https://github.com/bitnami/charts/pull/28543 has been implemented with an incorrect reference to the `basePath` parameter is now required to be appended exactly after the `publicBasePath` parameter

```yaml
 configuration:
     server:
       basePath: /ef-kibana
       rewriteBasePath: true
       publicBaseUrl: "https://myfqdn.com/ef-kibana"
```

but the automatic placement template in `templates/configmap.yaml` it is referenced incorrectly as below

```YAML
data:
  kibana.yml: |
    pid.file: /opt/bitnami/kibana/tmp/kibana.pid
    server.host: {{ .Values.configuration.server.host | quote }}
    server.port: {{ .Values.containerPorts.http }}
    elasticsearch.hosts: [{{ include "kibana.elasticsearch.url" . }}]
    {{- if .Values.configuration.server.basePath }}
    server.basePath: {{ .Values.configuration.server.basePath | quote }}
    {{- end }}
    {{- if or .Values.configuration.server.publicBaseUrl .Values.ingress.enabled }}
    server.publicBaseUrl: {{ default .Values.ingress.hostname .Values.configuration.server.publicBaseUrl }}
    {{- end }}
    server.rewriteBasePath: {{ .Values.configuration.server.rewriteBasePath }}

```

Details

When a custom configuration is used for kibana to be served behind ingress ( ingress-nginx in our case ), the newer version of kibana expects that the `basePath` should be automatically appended after the `.Values.ingress.hostname` or the value of `.Values.configuration.server.publicBaseUrl ` which if NOT Set, will be set to only the `.Values.ingress.hostname`, resulting in error  of bother `basePath` and `publicBaseUrl` are incorrect

Ideally it should 
```YAML
    {{- if  or .Values.ingress.tls  .Values.ingress.extraTls  }}
    {{- $scheme := "https://"  }}
    {{- else }}
    {{- $scheme := "http://" }}
    {{- end }} 
    {{- if  and ( not  .Values.configuration.server.publicBaseUrl)   .Values.ingress.enabled }}
    server.publicBaseUrl:  {{ $scheme  }}{{ .Values.ingress.hostname }}/{{ .Values.configuration.server.basePath }}
    {{- else }}
    server.publicBaseUrl:  {{ $scheme  }}{{ .Values.configuration.server.publicBaseUrl  }}/{{ .Values.configuration.server.basePath }}
    {{- end }}
```

### Are you using any custom parameters or values?

https://github.com/bitnami/charts/pull/28543

### What is the expected behavior?

https://github.com/bitnami/charts/pull/28543

### What do you see instead?

https://github.com/bitnami/charts/pull/28543

### Additional information

https://github.com/bitnami/charts/pull/28543
