### ISSUE TITLE
[bitnami/postgresql] `primary.persistence.storageClass` is conflicting with `include "common.storage.class"` causing helm install failure

### ISSUE THREAD

**Issue by Darkness4** [bitnami/charts#31140]
### Name and Version

bitnami/postgresql:16.3.3

### What architecture are you using?

arm64

### What steps will reproduce the bug?

By observing:

1. `helm template --version 16.3.3 --set primary.persistence.storageClass=example my-release oci://registry-1.docker.io/bitnamicharts/postgresql`
2. Check statefulset:

```yaml
  ...
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: example
        resources:
          requests:
            storage: "8Gi"
        storageClassName: example  # Conflict
```

By deploying:

1.  `helm install --version 16.3.3 --set primary.persistence.storageClass=example my-release oci://registry-1.docker.io/bitnamicharts/postgresql`

```txt
Helm install failed for release postgresql/postgresql with chart postgresql@16.3.3: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
line 300: mapping key "storageClassName" already defined at line 296
```

(The error message may not be accurate, but that's what gives me fluxcd).

### Are you using any custom parameters or values?

primary.persistence.storageClass=example

### What is the expected behavior?

It should install and storageClassName shouldn't appears twice.

### What do you see instead?

```yaml
# bitnami/postgresql/templates/primary/statefulset.yaml
  ...
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: example
        resources:
          requests:
            storage: "8Gi"
        storageClassName: example  # Conflict
```

```txt
Helm install failed for release postgresql/postgresql with chart postgresql@16.3.3: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
line 300: mapping key "storageClassName" already defined at line 296
```

### Additional information

A regression seems to have been introduced in this PR: https://github.com/bitnami/charts/pull/30858

16.3.0 work. >=16.3.1 doesn't.

References:

- Conflicting line 1: https://github.com/bitnami/charts/blob/61131de7b63913f4ef1cb9e7b5b2e8c593178b42/bitnami/postgresql/templates/primary/statefulset.yaml#L699-L700
- Conflicting line 2: https://github.com/bitnami/charts/blob/61131de7b63913f4ef1cb9e7b5b2e8c593178b42/bitnami/postgresql/templates/primary/statefulset.yaml#L707-L708
- "common.storage.class": https://github.com/bitnami/charts/blob/61131de7b63913f4ef1cb9e7b5b2e8c593178b42/bitnami/common/templates/_storage.tpl#L8-L22

This issue also happens with read replicas when using `replication` architecture.
