### ISSUE TITLE
Can not mount Volume to sidecar only

### ISSUE THREAD

**Issue by hket-tommyluk** [bitnami/charts#31151]
### Name and Version

bitnami/nginx 18.3.1

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Use the nginx helm chart.
2. In `values.yaml`, apply the custom parameters in the next part.
3. Render the helm chart

### Are you using any custom parameters or values?

`values.yaml`:
```yaml
sidecars: |-
  - volumeMounts:
      - name: vol
        mountPath: /vol
    //...

extraVolumes: |-
  - name: vol
    configMap:
      name: cm
```

### What is the expected behavior?

Successfully render templates

### What do you see instead?

This should be a valid usage but the validation in NOTES.txt is blocking me from doing this.
```
Error: execution error at (nginx/templates/NOTES.txt:71:4): 
VALUES VALIDATION:
nginx: missing-extra-volume-mounts
    You specified extra volumes but not mount points for them. Please set
    the extraVolumeMounts value
```

### Additional information

See also [_helpers.tpl L105-L112](https://github.com/bitnami/charts/blob/89e5604be18dff45ac2da9ff48383b97cb20a23d/bitnami/nginx/templates/_helpers.tpl#L105-L112)
