### ISSUE TITLE
redis sentinel extraEnvVars not effected

### ISSUE THREAD

**Issue by miniboxhaha** [bitnami/charts#31152]
### Name and Version

bitnami/redis 20.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```
helm install -f value.yaml my-redis-sentinel ../redis
```
### Are you using any custom parameters or values?

```yaml
sentinel:
   extraEnvVars: 
    - name: REDIS_SENTINEL_ANNOUNCE_IP
      value: "192.168.8.215"
    - name: REDIS_SENTINEL_ANNOUNCE_PORT
      value: "26379"
    - name: REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS
      value: "66666"
   externalMaster:
    # enabled: false
    enabled: true
    host: "192.168.8.215"
    port: 6379
```

### What is the expected behavior?

I expect sentinel return redis master use the value I set via `REDIS_SENTINEL_ANNOUNCE_IP`

### What do you see instead?

I try to get redis via sentinel outside k8s. I found sentinel return Redis master uses k8s internal name, which I can't use from outside.
So I tried to set `REDIS_SENTINEL_ANNOUNCE_IP`,  and seems not to effect in container.
Then I try other env from [redis sentinel docker image](https://hub.docker.com/r/bitnami/redis-sentinel)
check out the config file under **/opt/bitnami/redis-sentinel/sentinel.conf**
```
dir "/tmp"
port 26379
sentinel monitor mymaster my-redis-sentinel-node-1.my-redis-sentinel-headless.ha.svc.cluster.local 6379 2
# not working......
sentinel down-after-milliseconds mymaster 60000

# User-supplied sentinel configuration:
# End of sentinel configuration
sentinel auth-pass mymaster 123456
requirepass "123456"
sentinel myid aaa35c1d7034245afd333c786e737880884ef7ab

sentinel known-replica mymaster 192.168.8.242 6379

sentinel announce-hostnames yes
sentinel resolve-hostnames yes
sentinel announce-port 26379
# not working......
sentinel announce-ip "my-redis-sentinel-node-0.my-redis-sentinel-headless.ha.svc.cluster.local"

# Generated by CONFIG REWRITE
latency-tracking-info-percentiles 50 99 99.9
protected-mode no
user default on sanitize-payload #8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92 ~* &* +@all
sentinel config-epoch mymaster 1
sentinel leader-epoch mymaster 1
sentinel known-sentinel mymaster my-redis-sentinel-node-1.my-redis-sentinel-headless.ha.svc.cluster.local 26379 2c90b3ef284666c8ac5bafc56c6330ed78716609
sentinel current-epoch 1

sentinel known-replica mymaster my-redis-sentinel-node-2.my-redis-sentinel-headless.ha.svc.cluster.local 6379

sentinel known-replica mymaster my-redis-sentinel-node-0.my-redis-sentinel-headless.ha.svc.cluster.local 6379

sentinel known-sentinel mymaster my-redis-sentinel-node-2.my-redis-sentinel-headless.ha.svc.cluster.local 26379 7cbe9d29e5b106edc3f7d76ec6630c440977ad9a
```
