### ISSUE TITLE
Extra Containers feature is present in readme but missing in actual chart

### ISSUE THREAD

**Issue by fedir-indutnyi** [bitnami/charts#31181]
### Name and Version

bitnami/mariadb-galera 14.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The extra Containers feature is mentioned right in the main readme of the Helm chart for Bitnami Galera. 
Here is example from readme:
```yaml
extraContainers:
- name: '{{ .Chart.Name }}-eureka-sidecar'
  image: 'image:tag'
  env:
  - name: SERVICE_NAME
    value: '{{ template "common.names.fullname" . }}'
```
However, actual functionality is completely missing in the chart itself. Even by inspecting helm chart sources, I was able to find extraVolumes, but not extraContainers.
Expectedly, default values are also missing "extraContainers".

This is crucial functionality for my use case - I need to inject Wireguard Client as a container into galera node-0 pod.

Thank you!

### Are you using any custom parameters or values?

Yes, trying to add the following extraContainers values:

```yaml
  extraContainers:
    - name: wireguard
      image: linuxserver/wireguard:latest
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - SYS_MODULE
      volumeMounts:
        - mountPath: /etc/wireguard/wg0.conf
          name: wg-config
          subPath: wg0.conf

  extraVolumes:
    - name: wg-config
      configMap:
        name: wg-client-config
```
### What is the expected behavior?

Expected behavior: extra Volume Mount appears, and extra container appears.
Actual behavior: extra Volume Mount appears.

### What do you see instead?

Only extra volume appears in stateful set
