### ISSUE TITLE
bitnami/janusgraph stuck in wait-for-storage. Difficult to diagnose why

### ISSUE THREAD

**Issue by lonnie-intercax** [bitnami/charts#31182]
### Name and Version

bitnami/janusgraph 1.2.1

### What architecture are you using?

None

### What steps will reproduce the bug?

With helm values.yaml of

```yaml
storageBackend:
  cassandra:
    enabled: false
...
```

The Deployment is assigned to Pods but the wait-for-storage pod never completes successfully and so the janusgraph container is never allowed to get running.

### Are you using any custom parameters or values?

```yaml
storageBackend:
  cassandra:
    enabled: false

  external:
    backend: cql
    hostname: demo-dc1-service.k8ssandra-operator.svc.cluster.local
```

suitable user name and password are also provided.

### What is the expected behavior?

Well, ideally, everything is perfectly configured and JanusGraph comes into service. However, I expect to have to do some trial-and-error configuration settings to get the JanusGraph deployment connected with my existing k8ssandra-operator Cassandra service.

However, there is no way to get diagnostic info on why the configuration is wrong. There's also, of course, a sense that this might not be working at all yet for folk who choose not to use the available subchart for Cassandra.

### What do you see instead?

Of course, the gremlin.sh session within the init-container might be legitimately trying to reach a not-ready Cassandra service. However, if I exec into the wait-for-storage init-container, I find that it is unable to run its gremlin.sh script due to "securityContext"-like permissions problems.

### Additional information

It would be great to have a Values flag to disable the wait-for-storage init-container entirely. If not that, at least log the console output from trying to run the gremlin.sh script to a /tmp file for later diagnostic study.
