### ISSUE TITLE
[bitnami/keycloak] How to disable ssl_request ?

### ISSUE THREAD

**Issue by chominnn** [bitnami/charts#31194]
### What steps will reproduce the bug?
```yaml
image:
  registry: docker.io
  repository: bitnami/keycloak
  tag: 26.0.7-debian-12-r0
```

### What do you see instead?

We are sorry...
HTTPS required
