### ISSUE TITLE
[bitnami/kafka] JMX exporter sidecar wrong entrypoint

### ISSUE THREAD

**Issue by flostru** [bitnami/charts#31198]
### Name and Version

bitnami/kafka:31.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install chart with:

```yaml
metrics:
  jmx:
    enabled: true
```

jmx exporter sidecar wont start

### Are you using any custom parameters or values?

```yaml
metrics:
  jmx:
    enabled: true
```

### What is the expected behavior?

JMX Sidecar starting

### What do you see instead?

Error:  Unable to access jarfile jmx_prometheus_httpserver.jar

### Additional information

Previous jmx exporter image works:

```yaml
metrics:
  jmx:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/jmx-exporter
      tag: 1.0.1-debian-12-r9
```

Found this: https://github.com/bitnami/containers/pull/75698

Need to Backport this to jmx exporter args in template.
