### ISSUE TITLE
[bitnami/moodle] imagePullSecrets on container level is against spec

### ISSUE THREAD

**Issue by RalfBarth** [bitnami/charts#31199]
### Name and Version

bitnami/moodle 4.5.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Use bitnami/moodle 4.5.1 chart and custom values.yaml
2. Add some `certificates.customCAs` entries
3. Deployment will fail with `".spec.template.spec.initContainers[name="certificates"].imagePullSecrets: field not declared in schema"` due to `imagePullSecrets` for init container "certificates" are defined on container level, not Pod level. This is against spec: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#containers
4. Line of issue is here: https://github.com/bitnami/charts/blob/1fe7c59f415c46e5b1e002229d5d2027f167a320/bitnami/moodle/templates/deployment.yaml#L100C19-L100C20

### Are you using any custom parameters or values?

```
certificates:
  ## @param certificates.customCAs Defines a list of secrets to import into the container trust store
  ##
  customCAs:
    - secret: my-custom-ca
```

### What is the expected behavior?

Deploy without error

### What do you see instead?

Deployment fails during spec validation.

### Additional information

Remove the `imagePullSecrets` stanza from init container "certificates"
