### ISSUE TITLE
Kafka helm fails when provision topics: "can't evaluate field replicationFactor in type interface {}"

### ISSUE THREAD

**Issue by aparedero** [bitnami/charts#31206]
### Name and Version

bitnami/kafka:3.9.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In my case I'm using an AKS cluster but its a helm templating error.

Create and copy into a file basic configuration with "helm show values bitnami/kafka".

Enable provisionig and attempt to create topics:

```
provisioning:
  enabled: true
  automountServiceAccountToken: true
  numPartitions: 1
  replicationFactor: 1
  topics: ['topic','test']
```

### Are you using any custom parameters or values?

rbac and autodiscovery set to true enforces to enable *.automountServiceAccountToken to true. Other parameters remains with its default values.

### What is the expected behavior?

Helm Chart deployed, basic successful Helm message I see when I do same deployment but with provisioning.enabled=false

### What do you see instead?

Error: template: kafka/templates/provisioning/job.yaml:161:50: executing "kafka/templates/provisioning/job.yaml" at <$topic.replicationFactor>: can't evaluate field replicationFactor in type interface {}

### Additional information

The goal is to provision a couple of topics while installing and setting up Kafka, but the templating engine shows the error  `Error: template: kafka/templates/provisioning/job.yaml:161:50: executing "kafka/templates/provisioning/job.yaml" at <$topic.replicationFactor>: can't evaluate field replicationFactor in type interface {}`

**Comment by aparedero** [comment]
Closing. I don't see the relationship because Helm Chart templating it's not related to existing resources in k8s but after uninstalling Helm and removing manually PVC (remember that Helm does not delete pvc's), starting from scratch with the following configuration it works.

Leaving this ticket as reference in the future if someone gets similar error: Just remove your pvc's with

```
kubectl delete pvc data-kafka-controller-0 data-kafka-controller-1 data-kafka-controller-2 -n <namespace>
```

Attaching basic configuration with "topic" and "test" topics.

```
#[...]
provisioning:
  enabled: true
  automountServiceAccountToken: true
  numPartitions: 1
  replicationFactor: 1
  topics: []
  nodeSelector: {}
  tolerations: []
  extraProvisioningCommands: ["topic","test"]
  parallel: 1
  preScript: ""
  postScript: ""
#[...]
```

**Comment by aparedero** [comment]
**Update:** Closing. I was not defining the `topic` list inside properly.

Leaving this ticket as reference in the future if someone gets similar error: Just remove your pvc's with
Attaching basic configuration with topics "topic-test-1" and "topic-test-2".

```
#[...]
provisioning:
  enabled: true
  automountServiceAccountToken: true
  numPartitions: 1
  replicationFactor: 1
    - name: topic-test-1
      partitions: 1
      replicationFactor: 1
      config:
        max.message.bytes: 64000
        flush.messages: 1
    - name: topic-test-2
      partitions: 1
      replicationFactor: 1
      config:
        max.message.bytes: 64000
        flush.messages: 1
  nodeSelector: {}
  tolerations: []
  extraProvisioningCommands: []
  parallel: 1
  preScript: ""
  postScript: ""
#[...]
```

**Comment by aparedero** [comment]
**Update:** Closing. I was not defining the `topics` list inside properly.

Leaving this ticket as reference in the future if someone gets similar error: Just remove your pvc's with
Attaching basic configuration with topics "topic-test-1" and "topic-test-2".

```
#[...]
provisioning:
  enabled: true
  automountServiceAccountToken: true
  numPartitions: 1
  replicationFactor: 1
  topics:
    - name: seiv-messages
      partitions: 1
      replicationFactor: 1
      config:
        max.message.bytes: 64000
        flush.messages: 1
    - name: seiic-messages
      partitions: 1
      replicationFactor: 1
      config:
        max.message.bytes: 64000
        flush.messages: 1
  nodeSelector: {}
  tolerations: []
  extraProvisioningCommands: []
  parallel: 1
  preScript: ""
  postScript: ""
#[...]
```
