### ISSUE TITLE
[bitnami/valkey] More flexibility needed for handling CA certificate

### ISSUE THREAD

**Issue by lpellegr** [bitnami/charts#31218]
### Name and Version

bitnami/valkey 2.2.1

### What is the problem this feature will solve?

Some certificate issuers such as Let's Encrypt with Cert manager do not include a CA in the generated secret.

See the same issue that was already fixed weeks ago with [bitnami/redis https://github.com/bitnami/charts/issues/30305](https://github.com/bitnami/charts/issues/30305).

### What is the feature you are proposing to solve the problem?

`certCAFilename` must not be required when `tls` is enabled.

The same as https://github.com/bitnami/charts/commit/85219eb721efa640075325a1812d9ca8316a0a1a.

### What alternatives have you considered?

https://github.com/tdg5/bitnami-redis-ca-cert-shenanigans/blob/main/well-known-ca-values.yaml

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by gabriel-suela** [comment]
I cant make it work even with a cert generated by cert-manager with a CA. It always says bad certificate.


![Image](https://github.com/user-attachments/assets/56139402-a73b-47ec-b5b3-9f2afff29bad)
```yaml
tls:
  enabled: true
  autoGenerated: false
  existingSecret: valkey-cluster-cert
  certFilename: tls.crt
  certKeyFilename: tls.key
  certCAFilename: ca.crt
```

```yaml 
 - apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: valkey-cluster-cert
    spec:
      secretName: valkey-cluster-cert
      commonName: valkey-cluster
      dnsNames:
        - '*.valkey'
        - '*.valkey.default'
        - '*.valkey.default.svc'
        - '*.valkey.default.svc.cluster.local'
        - '*.valkey-headless'
        - '*.valkey-headless.default'
        - '*.valkey-headless.default.svc'
        - '*.valkey-headless.default.svc.cluster.local'
      usages:
        - signing
        - key encipherment
        - server auth
        - client auth
      issuerRef:
        kind: ClusterIssuer
        name: ca-issuer
```
