### ISSUE TITLE
[Question] How to use namespaceOverride in bitnami/postgres when installing as dependency

### ISSUE THREAD

**Issue by fgeck** [bitnami/charts#31219]
### Name and Version

bitnami/postgresql 14.3.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install a local chart dir:

```bash
mkdir test && cd test
touch values.yaml
touch Chart.yaml
cat <<EOF > Charts.yaml
apiVersion: v2
name: test
description: test
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: postgresql
    version: "^14.3.3"
    repository: https://charts.bitnami.com/bitnami
EOF
```

Then template the test chart using the values.yaml provided below:

```bash
helm dependency build test --skip-refresh
helm template test ./test -f ./test/values.yaml
```

### Are you using any custom parameters or values?

```yaml
global:
  namespaceOverride: default
namespaceOverride: default
postgresql:
  nameOverride: postgresql
  fullnameOverride: postgresql
  namespaceOverride: default
  global:
    namespaceOverride: default
```

### What is the expected behavior?

namespace is set to `default`

### What do you see instead?

namespace is the one my kube context points to

### Additional information

I hope that I am wrong and this is just a question, otherwise it should be treated as a bug.
