### ISSUE TITLE
tcpListenOptions configuration is incorrectly controlled by memoryHighWatermark.enabled setting

### ISSUE THREAD

**Issue by Kulivox** [bitnami/charts#31221]
### Name and Version

bitnami/rabbitmq 15.2.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Get rabbitmq 15.2.1 chart / set it as a chart dependency on a wrapper chart
2. Try to set any of the tcpListenOptions. For example, set `tcpListenOptions.keepalive` to true.
3. No TCP options will be set
4. Set `memoryHighWatermark.enabled` to True
5. TCP options will appear in the conf. secret

### Are you using any custom parameters or values?

```yaml
rabbitmq:
    enabled: true
    memoryHighWatermark:
      enabled: true
    tcpListenOptions:
      keepalive: true
 ```

### What is the expected behavior?

TCP options should not be controlled by `memoryHighWatermark` setting

### What do you see instead?

No TCP settings in the config, if the `memoryHighWatermark` is not enabled

### Additional information

I can create a PR, the fix should be trivial (move `{{end}}` of an `if`)
