### ISSUE TITLE
[bitnami/etcd] Defrag Job TLS Flags & Endpoint URL Issue

### ISSUE THREAD

**Issue by sachinphogat** [bitnami/charts#31255]
### Name and Version

etcd/10.7.0

### What steps will reproduce the bug?

Deploy ETCD Chart v10.7.0 with etcd defrag enabled and tls auth enabled.

Cronjob will be created with the below flags.
```yaml
            env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: ETCDCTL_CA_FILE
              value: /opt/bitnami/etcd/certs/client/ca.crt
            - name: ETCDCTL_KEY_FILE
              value: /opt/bitnami/etcd/certs/client/tls.key
            - name: ETCDCTL_CERT_FILE
              value: /opt/bitnami/etcd/certs/client/tls.crt
```
Also Endpoint is created as below.
```
            - --endpoints=[http://etcd-etcd-0.etcd-etcd-headless.iks-6233d4e4-f051-4c0e-ac2a-fcbdf7278249.svc.cluster.local:2379,http://etcd-etcd-1.etcd-etcd-headless.iks-6233d4e4-f051-4c0e-ac2a-fcbdf7278249.svc.cluster.local:2379,http://etcd-etcd-2.etcd-etcd-headless.iks-6233d4e4-f051-4c0e-ac2a-fcbdf7278249.svc.cluster.local:2379]
```
### Are you using any custom parameters or values?
```yaml
    auth:
      client:
        caFilename: ca.crt
        certFilename: tls.crt
        certKeyFilename: tls.key
        enableAuthentication: true
        existingSecret: etcd-etcd-client-tls
        secureTransport: true
        useAutoTLS: false
      peer:
        caFilename: ca.crt
        certFilename: tls.crt
        certKeyFilename: tls.key
        enableAuthentication: true
        existingSecret: etcd-etcd-peer-tls
        secureTransport: true
        useAutoTLS: false
      rbac:
        create: false
    autoCompactionRetention: 3h
    customLivenessProbe:
      exec:
        command:
        - /opt/bitnami/scripts/etcd/healthcheck.sh
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
    defrag:
      enabled: true
    replicaCount: 3
```

### What is the expected behavior?

ETCD Degrag should get completed successfully.

### What do you see instead?
```
{"level":"warn","ts":"2025-01-08T08:03:37.596559Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCDCTL_CA_FILE=/opt/bitnami/etcd/certs/client/ca.crt"}
{"level":"warn","ts":"2025-01-08T08:03:37.596746Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCDCTL_KEY_FILE=/opt/bitnami/etcd/certs/client/tls.key"}
{"level":"warn","ts":"2025-01-08T08:03:37.596757Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCDCTL_CERT_FILE=/opt/bitnami/etcd/certs/client/tls.crt"}
{"level":"warn","ts":"2025-01-08T08:03:48.198505Z","logger":"etcd-client","caller":"v3@v3.5.17/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0001741e0/etcd-etcd-0.etcd-etcd-headless.6233d4e4-f051-4c0e-ac2a-fcbdf7278249.svc.cluster.local:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing: dial tcp: address http://etcd-etcd-2.etcd-etcd-headless.6233d4e4-f051-4c0e-ac2a-fcbdf7278249.svc.cluster.local:2379]: too many colons in address\""}
Error: failed to fetch endpoints from etcd cluster member list: context deadline exceeded
```
### Additional information

We need to change env variable based on etcdctl v3 as current ones are only v2 supported.
Also, we need to add endpoints as https instead of http.
