### ISSUE TITLE
[bitnami/mongodb] volumeclaim created even if persistence: false

### ISSUE THREAD

**Issue by Shadowraze228** [bitnami/charts#3126]
**Which chart:** mongo-sharded

**Describe the bug:**
VolumeClaim template created even if persistence: false
https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/replicaset/statefulset.yaml#L362

**To Reproduce**
1. This values.yml
```
  image:
    tag: 4.2
  architecture: "replicaset"
  useStatefulSet: true
  replicaCount: 3
  replicaSetName: "testrs"
  auth:
    enabled: true
    replicaSetKey: "replicasetkey"
    rootPassword: "test"
    username: "test"
    password: "test"
    database: "test"
  persistence:
    enabled: false
```
2. Deploy
```
helm install --name my-release \
   bitnami/mongodb
```

**Expected behavior:**
MongoDB replicaset created without any pv/pvc.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```
