### ISSUE TITLE
[bitnami/common] renderSecurityContext shouldn't remove seLinuxOptions when privileged

### ISSUE THREAD

**Issue by valleedelisle** [bitnami/charts#31278]
### Name and Version

bitnami/common 2.20.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

* Deploying a chart using `containerSecurityContext.privileged` with additional `seLinuxOptions` 

* `renderSecurityContext` will remove the `seLinuxOptions`.

### Are you using any custom parameters or values?

```yaml
containerSecurityContext:
  enabled: true
  seLinuxOptions:
    type: "spc_t"
  privileged: true
  runAsUser: 0
  runAsNonRoot: false
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: true
```

We use the `spc_t` on our minio deployment since it contains billions of small files. Without this, Openshift is unable to start the pods in a timely manner.

Adding the `spc_t` is a [Redhat recommendation](https://access.redhat.com/solutions/6221251) and it needs to be there even if the pods are privileged.

### What is the expected behavior?

My expectation is that `seLinuxOptions` will be retained even if we use `privileged`

### What do you see instead?

`seLinuxOptions` is removed

### Additional information

This behavior was introduced with this commit: 5f0bdde77cf05afa20cb4a800090748a8d102d02
