### ISSUE TITLE
[bitnami/mongodb] remove undefined rts key from network policy template

### ISSUE THREAD

**Issue by trust56** [bitnami/charts#31284]
### Name and Version

bitnami/mongodb 14.8.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm using not the default mongodb port 27017, but 27117-27119 (different ports for each replicaset members), so I had to modify the network policy. I've set the network policy via Helm values, see below.

Doing this I'll receive an error when deploying this Helm release.
```
Error: template: mongodb/templates/networkpolicy.yaml:45:64: executing "mongodb/templates/networkpolicy.yaml" at <.Values.rts.networkPolicy.extraEgress>: nil pointer evaluating interface {}.networkPolicy
```

### Are you using any custom parameters or values?

I've enabled `networkpolicy` and `extraEgress` in my Helm release like so:
```yaml
    networkPolicy:
      enabled: true
      allowExternalEgress: false
      extraIngress:
        - ports:
            - port: 27117
            - port: 27118
            - port: 27119
      extraEgress:
        - ports:
            - port: 27117
              protocol: TCP
            - port: 27118
              protocol: TCP
            - port: 27119
              protocol: TCP
          to:
            - podSelector:
                - matchLabels:
                    - app.kubernetes.io/instance: mongodb
                    - app.kubernetes.io/name: mongodb
```

### What is the expected behavior?

It should enable the egress Network policy.

### What do you see instead?

```
Error: template: mongodb/templates/networkpolicy.yaml:45:64: executing "mongodb/templates/networkpolicy.yaml" at <.Values.rts.networkPolicy.extraEgress>: nil pointer evaluating interface {}.networkPolicy
```

### Additional information

I checked the template code of the [networkPolicy](https://github.com/bitnami/charts/blob/main/bitnami/mongodb/templates/networkpolicy.yaml) and I see this line which seems wrong

```yaml
{{- include "common.tplvalues.render" ( dict "value" .Values.rts.networkPolicy.extraEgress "context" $ ) | nindent 4 }}
```

What is an `rts`? I see no such thing in the helm values. Shouldn't it be?

```yaml
{{- include "common.tplvalues.render" ( dict "value" .Values.networkPolicy.extraEgress "context" $ ) | nindent 4 }}
```

I see this issue is present in chart version 14.8.1 and all later versions ever since.
