### ISSUE TITLE
postgresql-ha  Unable to start after mounting PVC

### ISSUE THREAD

**Issue by Kl981** [bitnami/charts#31306]
### Name and Version

bitnami/postgresql-ha:15.1.4

### What architecture are you using?

None

### What steps will reproduce the bug?

In the case of 3 pods, if I mount PVC, Pod1 `ha-postgresql-0` will report an error:
```
DETAIL:  File "base/16385/PG_VERSION" is missing.
FATAL: "base/16385" is not a valid data directory
```
Pod2 `postgresql-ha-postgresql-1` and `postgresql-ha-postgresql-2` both report errors:
```
 Starting PostgreSQL in background...
pg_ctl: directory "/bitnami/postgresql/data" is not a database cluster directory
```
### Are you using any custom parameters or values?
```yaml
volumePermissions:
  enabled: true

persistence:
  enabled: true
  existingClaim: "ack-nas-postgresql-data-pvc-demo"
  storageClass: "-"
  mountPath: /bitnami/postgresql
  accessModes:
    - ReadWriteOnce

persistentVolumeClaimRetentionPolicy:
  enabled: true
  whenScaled: Retain
  whenDeleted: Retain
```
### What is the expected behavior?

All three pods are available

### Additional information

Postgresql-1 and Postgresql-2 error first
```
pg_ctl: directory "/bitnami/postgresql/data" is not a database cluster directory
```
Then ha-postgresql-0 will report an error: 
```
DETAIL:  File "base/16385/PG_VERSION" is missing.
FATAL: "base/16385" is not a valid data directory
```
