### ISSUE TITLE
[bitnami/mongodb] unable to override chart values

### ISSUE THREAD

**Issue by rajan123456** [bitnami/charts#3133]
**Which chart**: bitnami/mongodb (8.1.1)

**Is your feature request related to a problem? Please describe.** Help request

I am new to Helm and using Helm 3. I am trying to build a simple helm chart which depends on the mongodb helm chart.

This is the structure of my chart:
```
mychart
|- charts\
|--|- mongodb-8.1.1.tgz
|- Chart.yaml
|- values.yaml
```
I am trying to override the value of rootPassword (and some other properties) through the values.yaml file of the parent chart. However, it does not override the value specified and reverts to the default values from the mongodb chart.

It would be a great help to understand what I am doing wrong and how can I override the value of the child chart from the parent chart.

Here are the contents of my files:

Chart.yaml
```
apiVersion: v2
name: mychart
appVersion: "1.0"
description: mychart has the best description
version: 0.1.0
type: application
dependencies:
  - name: mongodb
    version: 8.1.1
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
```
values.yaml
```
mongodb:
    global:
        namespaceOverride: production
    fullnameOverride: mongo-mychart
    useStatefulSet: true
    auth:
        rootPassword: example
    persistence:
        size: 100Mi
```
**Describe the solution you'd like**
Would expect the values overridden from the parent chart (mychart) to be used in the mongodb dependency.

**Describe alternatives you've considered**
Passing overrides directly through the command line works as expected.
```
helm template mychart --set global.namespaceOverride=production,fullnameOverride=mongo-mychart,useStatefulSet=true,auth.rootPassword=example,persistence.size=100Mi bitnami/mongodb
```

**Additional context**
NA
