### ISSUE TITLE
[bitnami/keycloak] MountVolume.SetUp failed for volume "kube-api-access-4xwxg" 

### ISSUE THREAD

**Issue by alekseytivonchik** [bitnami/charts#31347]
### Name and Version

bitnami/keycloak 24.4.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Installing a Helm chart in Kubernetes version v1.31.4
2. Run `helm install keycloak -n keycloak -f values.yaml .` 
3. Encountering an error during pod initialization

### Are you using any custom parameters or values?

```
storageClass: "local-storage"
proxy: "edge"
type: NodePort
externalDatabase:
  host: ""
  port: ""
  user: ""
  database: ""
  password: ""
  existingSecret: "keycloak-auth"
  existingSecretHostKey: "pg_host"
  existingSecretPortKey: "pg_port"
  existingSecretUserKey: "pg_user"
  existingSecretDatabaseKey: "pg_db"
  existingSecretPasswordKey: "pg_passwd"
```

### What is the expected behavior?

Pod in status "Running"

### What do you see instead?

Warning  FailedMount  80s (x486 over 16h)  kubelet  (combined from similar events): MountVolume.SetUp failed for volume "kube-api-access-4xwxg" : write /var/lib/kubelet/pods/a1353f7b-0123-49e6-85ed-aaabe5d09a69/volumes/kubernetes.io~projected/kube-api-access-4xwxg/..2025_01_14_07_19_56.263343095/ca.crt: no space left on device

### Additional information

Chart version 21.0.1 install successfully

There is more than enough disk space on the cluster’s worker node
```
root@k8s-dev-pool0:~# df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        98G   11G   83G  12% /
root@k8s-dev-pool0:~# df -i /
Filesystem      Inodes  IUsed   IFree IUse% Mounted on
/dev/sda2      6553600 134310 6419290    3% /
root@k8s-dev-pool0:~# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sda      8:0    0  100G  0 disk
├─sda1   8:1    0    1M  0 part
└─sda2   8:2    0  100G  0 part /
sr0     11:0    1 1024M  0 rom
```
