### ISSUE TITLE
passwordUpdate job is missing "." in include statement

### ISSUE THREAD

**Issue by nix-power** [bitnami/charts#31367]
### Name and Version

bitnami/postgresql 16.4.2

### What architecture are you using?

None

### What steps will reproduce the bug?

render the chart or try to deploy it
```
helm template postgresql  .
```

### Are you using any custom parameters or values?

```yaml
 passwordUpdateJob:
      enabled: true
      previousPasswords:
        existingSecret: postgresql-credentials
```

### What is the expected behavior?

To render template successfully

### What do you see instead?

```
Error: template: idp/charts/keycloak/charts/postgresql/templates/update-password/job.yaml:60:37: 
executing "idp/charts/keycloak/charts/postgresql/templates/update-password/job.yaml" 
at <include>: wrong number of args for include: want 2 got 1
```

**Comment by nix-power** [comment]
There is a fixing PR issued

https://github.com/bitnami/charts/pull/31364

**Comment by nix-power** [comment]
Everything is OK now, except that Chart version of 24.4.3 could not be downloaded from charts.bitnami.com/bitnami

```
dependencies:
  - name: keycloak
    condition: idp.enabled
    version: 24.4.3
    repository: https://charts.bitnami.com/bitnami
```


Error: can't get a valid version for repositories keycloak. Try changing the version constraint in Chart.yaml
