### ISSUE TITLE
error response NOT_COORDINATOR. isDisconnected: false. Rediscovery will be attempted-Kafka

### ISSUE THREAD

**Issue by abbabe** [bitnami/charts#31376]
### Name and Version

Kafka Helm Chart targetRevision:  30.1.8 

### What architecture are you using?

None

### What steps will reproduce the bug?

Hello,
I edited values.yml in Bitnami Kafka Helm chart Kraft mode as follows. I get the following error message when the controller replica count is 3 or 2. Although I made various config additions, I could not solve the problem. Could you please help me with the issue?  

I edited the settings as Plaintext so that there is no problem with brokers' communication. Actually, I want to trade `SASL_PLANTEXT` and provide access from outside. I don't get any error in connecting to the header. I only get the following error.
```
error response NOT_COORDINATOR. isDisconnected: false. Rediscovery will be attempted

Request joining group due to: rebalance failed due to 'This is not the correct coordinator.' (NotCoordinatorException)
(Re-)joining group
Group coordinator kafka.dagi.com:9095 (id: 2147483646 rack: null) is unavailable or invalid due to cause: error response NOT_COORDINATOR. isDisconnected: false. Rediscovery will be attempted.

JoinGroup failed: This is not the correct coordinator. Marking coordinator unknown. Sent generation was Generation{generationId=-1, memberId=''', protocol='null'}
```

### Are you using any custom parameters or values?
```yaml
kraft:
  enabled: true
listeners:

  client:
    containerPort: 9092
    protocol: PLAINTEXT # SASL_PLAINTEXT #
    name: CLIENT
    #sslClientAuth: ""

  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol:  PLAINTEXT # SASL_PLAINTEXT #
    #sslClientAuth: ""
  
  interbroker:
    containerPort: 9094
    protocol: PLAINTEXT #  SASL_PLAINTEXT #
    name: INTERNAL
   #sslClientAuth: ""
  
  external:
    containerPort: 9095
    protocol: PLAINTEXT # SASL_PLAINTEXT # 
    name: EXTERNAL
    #sslClientAuth: ""

  advertisedListeners: "CLIENT://kafka-controller-headless.kafka:9092,INTERNAL://kafka-controller-headless.kafka:9094,EXTERNAL://kafka.dagi.com:9095"
  securityProtocolMap: "CLIENT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
  
sasl:


  enabledMechanisms: PLAIN,SCRAM-SHA-256,SCRAM-SHA-512

  interBrokerMechanism: PLAIN

  controllerMechanism: PLAIN


  oauthbearer:
    tokenEndpointUrl: ""
    jwksEndpointUrl: ""
    expectedAudience: ""
    subClaimName: "sub"

  interbroker:
    user: inter_broker_user_dagi
    password: ""
    clientId: inter_broker_client_dagi
    clientSecret: ""

  controller:
    user: controller_user_dagi
    password: ""
    clientId: controller_broker_client_dagi
    clientSecret: ""
  
  client:
    users:
      - dagi # user1
    passwords: ""

controller:

  replicaCount: 3
  persistence:
   
    enabled: true
    storageClass: ""
    
    accessModes:
      - ReadWriteOnce
  
    size: 10Gi
  extraConfig: |
    group.consumer.max.session.timeout.ms=90000
    group.consumer.session.timeout.ms=60000
    group.consumer.max.heartbeat.interval.ms=30000
    group.consumer.heartbeat.interval.ms=25000
    offsets.topic.replication.factor=3
    transaction.state.log.replication.factor=3
    transaction.state.log.min.isr=3
    default.replication.factor=3
    socket.connection.setup.timeout.max.ms=50000
    socket.connection.setup.timeout.ms=20000
    
broker:
 
  replicaCount: 0
  persistence:
    
    enabled: true
    storageClass: ""

    accessModes:
      - ReadWriteOnce

    size: 8Gi
externalAccess:
  enabled: true

  controller:
    service: 
      type: ClusterIP # NodePort # 
      # nodePorts: ["30396","30397","30398"]
       #- 30396
       #- 30397
       #- 30398
      ports:
        external: 9095
      domain: kafka.dagi.com
  
  broker:
    service:
      type: ClusterIP # NodePort # 
      # nodePorts: ["30396","30397","30398"]
      #  - 30396
      #  - 30397
      #  - 30398
      ports:
        external: 9095
      domain: kafka.dagi.com

metrics:
  jmx:  
    enabled: true
    kafkaJmxPort: 5555
    extraRules:
      - pattern: "kafka.server<type=raft-metrics><>(current-state): (.+)"
        name: kafka_server_raft_metrics
        labels:
          name: $1
          state: $2
        value: 1
      - pattern: "kafka.server<type=raft-metrics><>(.+): (.+)"
        name: kafka_server_raft_metrics
        labels:
          name: $1
```
