### ISSUE TITLE
Set the ruler config file flag via the helm chart

### ISSUE THREAD

**Issue by jessebot** [bitnami/charts#31375]
### Name and Version

bitnami/thanos 15.9.2

### What is the problem this feature will solve?

Right now, in the thanos chart, the ruler's `--rule-file=/conf/rules/*.yml` arg is hardcoded in the ruler Statefulset.

### What is the feature you are proposing to solve the problem?

I'd like to see the `--rule-file` as a configurable parameter, so that we can change the directory or file extension (`yaml` vs `yml`, for instance). It would look like this:

```yaml
ruler:
  ## @param ruler.ruleFile Change the location Thanos checks for rule files
  ##
  ruleFile: "/conf/rules/*.yml"
```

It would still default to the current location so it does not introduce a breaking change. I will work on this PR.

### What alternatives have you considered?

none, as I don't want to have to override the entire args section.
