### ISSUE TITLE
[bitnami/thanos] support using an existing PVC for Thanos Ruler rules config files

### ISSUE THREAD

**Issue by jessebot** [bitnami/charts#31379]
### Name and Version

bitnami/thanos 15.9.2

### What is the problem this feature will solve?

Right now, it is required that users of Thanos Ruler via the bitnami Thanos helm chart provide either of:

- `ruler.config` (a string)
- `ruler.existingConfigmap` (a configmap)

This assumes users want to provide their rules via a single ConfigMap or secret. I use the [kiwigrid/k8s-sidecar](https://github.com/kiwigrid/k8s-sidecar) sidecar container to automatically grab ConfigMaps matching a specific label and load them into a specific directory for Thanos Ruler to pick up. (This is similar to the same offering by Grafana for automatically detecting new Dashboards) Because of this, I can't provide either a ConfigMap nor the config string.

### What is the feature you are proposing to solve the problem?

I'd like to see something like `ruler.existingConfigClaim` to allow using a persistent volume that both the Thanos ruler container and the side car container can mount. This would allow also for an initContainer to run before the ruler and populate the `/config/rules` directory. When combined with #31377 this can allow full self service of creating additional alerting rules, instead of having it centrally managed and overloading a specific team or team member to handle updates to one giant ConfigMap.

In the values.yaml, it could look like this:

```yaml
ruler:
  ## @param ruler.existingConfigClaim provide an existing persistent volume claim to mount for the ruler's rules
  existingConfigClaim: ""
```

For reference, the ruler config is currently required to be a single config map here:
https://github.com/bitnami/charts/blob/7432a317f4126ac2ca2b3a56e731d483a92b752a/bitnami/thanos/templates/ruler/statefulset.yaml#L261-L262

This would need to be changed to allow something like:

```yaml
        - name: ruler-config
          {{- if and .Values.ruler.existingConfigClaim (not .Values.ruler.config) (not .Values.ruler.existingConfigmap) }}
          persistentVolumeClaim:
            claimName: {{ .Values.ruler.existingConfigClaim }}
          {{- else }}
          configMap:
            name: {{ include "thanos.ruler.configmapName" . }}
          {{- end }}
```

I can work on this PR later today.
