### ISSUE TITLE
TLS not in networkpolicy

### ISSUE THREAD

**Issue by Klwilson2272** [bitnami/charts#31411]
### Name and Version

bitnami/zookeeper

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. environment
When deploying the zookeeper chart with tls enabled, and external ingerss enabled. The network policy only allows for 2181 port. I expected that I would be able to use the 3181 when TLS is configured. The Network policy should include 3181 when tls.enabled is configured to allow consistent configuration. 

2. config
```yaml
zookeeper:
  replicaCount: 3
  service:
    type: NodePort
    nodePorts:
      client: "32181"
      tls: "31181"
  persistence:
    storageClass: zookeeper-data
  resourcesPreset: small
  tls:
    client: 
      enabled: true
      autoGenerated: true
    resourcesPreset: small
  metrics:
    enabled: true
```
5. run

Deploy the helm chart with the above configurtation.

6. error
```
openssl s_client -connect host:31181 fails with a timeout. 
Attempting to use kazoo with:
from kazoo.client import KazooClient

# Create a Kazoo client and connect to ZooKeeper
zk = KazooClient(hosts='192.168.16.2:31181', use_ssl=True, verify_certs=False)
zk.start()

# Create a node
zk.create("/my_node", b"Hello, ZooKeeper!")

# Get the value of a node
data, stat = zk.get("/my_node")
print("Data:", data.decode('utf-8'))

# Watch for changes to a node
@zk.DataWatch("/my_node")
def watch_node(data, stat):
    print("Node changed:", data.decode('utf-8'))

# Create a lock
lock = zk.Lock("/my_lock")
with lock:
    # Critical section
    print("Lock acquired")

# Close the connection
zk.stop()
```
Also times out with a error. 

After modifying the networkpolicy and adding port 3181. I was able to connect with openssl and the kazoo client without issues. I edited the network policy and added the 3181 and protocol TCP below. 
```yaml
spec:
  egress:
  - {}
  ingress:
  - ports:
    - port: 2181
      protocol: TCP
    - port: 3181
      protocol: TCP
    - port: 9141
      protocol: TCP
```

### What is the expected behavior?

Expected to be able to connect using TLS when configured.

### What do you see instead?

timeout errors
