### ISSUE TITLE
[bitnami/spring-cloud-dataflow] libsnappyjava.so not found in prometheus-rsocket-proxy

### ISSUE THREAD

**Issue by vai-thnas** [bitnami/charts#31453]
### Name and Version

bitnami/spring-cloud-dataflow 34.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. On an AWS EKS cluster
2. Running with Kubernetes v1.30, AL2 nodes 5.10.230-223.885.amzn2.x86_64
3. Deploy with
```
helm upgrade "dataflow" "artifactory/spring-cloud-dataflow" \
  -f "helm/values.yaml" \
  --install \
  --atomic \
  --namespace dataflow \
  --create-namespace \
  --version "34.0.0" \
  --wait \
  --timeout=10m0s
```
4. Functionally everything seems to work and the metrics can be scraped, but the prometheus-rsocket-proxy logs are filled with errors

### Are you using any custom parameters or values?

```
global:
  imageRegistry: "$DOCKER_IMAGE_REGISTRY"
  imagePullSecrets:
    - "$DOCKER_IMAGE_PULL_SECRET_NAME"
server:
  replicaCount: 1
  configuration:
    batchEnabled: true
    streamingEnabled: false
mariadb:
  enabled: false
skipper:
  enabled: false
rabbitmq:
  enabled: false
externalDatabase:
  dataflow:
    url: "$POSTGRES_URL"
    user: "$POSTGRES_USER"
    password: "$POSTGRES_PASSWORD"
  hibernateDialect: org.hibernate.dialect.PostgreSQLDialect
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  readinessProbe:
    initialDelaySeconds: 60
  livenessProbe:
    initialDelaySeconds: 60
```

### What is the expected behavior?

No errors in the logs

### What do you see instead?

In the bitnami/prometheus-rsocket-proxy:1.5.3-debian-12-r31 container's logs

1. After container starts, an error logs complains that `/tmp/snappy-1.1.10-b15b886e-73d2-47ba-ba4e-cc9fe5941d72-libsnappyjava.so` cannot be found
2. Every 30 seconds, 2 stack traces (one at WARN one at ERROR level) are complaining that `org.xerial.snappy.Snappy` cannot be initialized

Logs dump : [prometheus-proxy.log](https://github.com/user-attachments/files/18453414/prometheus-proxy.log)

### Additional information

tried overriding prometheus-rsocket-proxy to latest version 1.5.3-debian-12-r34 but same errors

**Comment by dgomezleon** [comment]
Hi @vai-thnas ,

Could you please confirm if you face the same issue using the latest version 34.1.1 and the values below? (the only change is the externaldatabase):

```
server:
  replicaCount: 1
  configuration:
    batchEnabled: true
    streamingEnabled: false
mariadb:
  enabled: false
postgresql:
  enabled: true
skipper:
  enabled: false
rabbitmq:
  enabled: false
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  readinessProbe:
    initialDelaySeconds: 60
  livenessProbe:
    initialDelaySeconds: 60
```

If so, please confirm if it happens just after starting the chart.
