### ISSUE TITLE
Incorrect Documentation/Misleading Warning for postgresql.resources

### ISSUE THREAD

**Issue by jonchun** [bitnami/charts#31467]
### Name and Version

kubeapps-17.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy kubeapps with default settings.
2. Set the following values:
```yaml
postgresql:
  resourcesPreset: none
  resources:
    requests:
      cpu: "1"
      memory: 512Mi
    limits:
      memory: 1024Mi
```

### What do you see instead?

This does NOT work as documented. The solution is in #31265 which is to set it under the primary: key (or readReplicas according to https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml)
e.g. 
```yaml
postgresql:
  primary:
    resourcesPreset: none
    resources:
      requests:
        cpu: "1"
        memory: 512Mi
      limits:
        memory: 3072Mi
```

While that resolves the issue, there is still a misleading warning that shows up warning about a key that has no effect.
```
WARNING: There are "resources" sections in the chart not set. Using "resourcesPreset" is not recommended for production. For production installations, please set the following values according to your workload needs:
  - postgresql.resources
```
