### ISSUE TITLE
[bitnami/discourse] Setting readonlyFilesystem to true, restart pods

### ISSUE THREAD

**Issue by divyanshch2019** [bitnami/charts#31463]
### Name and Version

bitnami/discourse 7.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install the helm chart with the following values.yaml
```
containerSecurityContext:
 enabled: true
 allowPrivilegeEscalation: false
 readOnlyRootFilesystem: true

```

### Are you using any custom parameters or values?

```
securityContext:
 runAsNonRoot: true
 runAsUser: 1000
 runAsGroup: 1000
 seccompProfile:
  type: RuntimeDefault
```

### What is the expected behavior?

The discourse pod should run without any errors

### What do you see instead?

`/opt/bitnami/scripts/libpostgresqlclient.sh: line 53: cannot create temp file for here-document; Read-only file system`
