### ISSUE TITLE
[bitnami/postgresql-ha] /opt/bitnami/scripts/libldapclient.sh: line 104: /etc/nslcd.conf: Permission denied

### ISSUE THREAD

**Issue by caspereijkens** [bitnami/charts#31480]
### Name and Version

bitnami/postgresql-ha:15.1.6

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Enable LDAP and fill in the required fields.
2. Run pgpool container as user 1001.
3. `/opt/bitnami/scripts/libldapclient.sh: line 104: /etc/nslcd.conf: Permission denied`

In this line indeed I see 
```
cat >"/etc/nslcd.conf"
```

### Are you using any custom parameters or values?

```yaml
  volumePermissions:
    enabled: true
    podSecurityContext:
      enabled: true
      seLinuxOptions: {}
      readOnlyRootFilesystem: false
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    resourcesPreset: "nano"
```

### What is the expected behavior?

I expected pgpool to start up without any issues given the minimal amount of changed variables.

### What do you see instead?

```
/opt/bitnami/scripts/libldapclient.sh: line 104: /etc/nslcd.conf: Permission denied  
```

This is not strange, since `/etc/nslcd.conf` is owned by root
```console
$ ls -al | grep nslcd
-rw-rw---- 1 root root     674 Dec 28 11:58 nslcd.conf
```

### Additional information

Please teach me how to run ldap in postgresql-ha rootless.

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by caspereijkens** [comment]
Hi @carrodher ,

Thank you for your answer. I found the links you posted via another issue already. 

So, what do you suggest concretely, adjust the permissions on the required files via the Dockerfile? 

Best regards,
Casper

**Comment by carrodher** [comment]
No via the Dockerfile but using the `securityContext` within the Helm chart and/or adjusting the permissions of the local volume.

**Comment by caspereijkens** [comment]
I'm not sure what you mean here. Could you please verify if this is what you mean? 
```
pgpool:
  extraVolumeMounts:
  - name: trusted-cert-secret-volume
    mountPath: /etc/ssl/certs
  - name: trusted-cert-secret-volume
    mountPath: /etc/openldap/certs

  extraVolumes:
  - name: trusted-cert-secret-volume
    secret:
      secretName: my-secret-crt
      items:
      - key: tls.crt
        mode: 256
        path: ca-certificates.crt

  tls:
    enabled: true
    certificatesSecret: my-secret-crt
    certKeyFilename: tls.crt
    certFilename: tls.key
    certCAFilename: ca.crt
  
  containerSecurityContext:
    readOnlyRootFilesystem: false


volumePermissions:
  enabled: true
  podSecurityContext:
    enabled: true
    seLinuxOptions: {}
    readOnlyRootFilesystem: false
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

ldap:
  enabled: true
  uri: "<enter-here>"
  basedn: "<enter-here>"
  binddn: "<enter-here>"
  bindpw: "<enter-here>"
  tlsReqcert: "demand"
  nssInitgroupsIgnoreusers: root,nslcd
```
Just this produces the error in the title. Could you please point out my error here?

BR Casper
