### ISSUE TITLE
[bitnami/minio] Chart not found

### ISSUE THREAD

**Issue by bonzonkim** [bitnami/charts#31489]
### Name and Version

bitnami/minio 14.10.5

### What architecture are you using?

None

### What steps will reproduce the bug?

I am trying to deploy [minio](https://artifacthub.io/packages/helm/bitnami/minio)

- minio-template.yaml
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: minio
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.10.5
    chart: bitnami/minio
    helm:
      releaseName: minio
      {{- $files := .Files }}
      values: |
        {{- $files.Get "conf/minio-conf.yaml" | nindent 12 }}
  syncPolicy:
    {{- toYaml .Values.argocd.autoSyncPolicy | nindent 8 }}
```
- minio-conf.yaml
```yaml
auth:
  rootUser: admin
  rootPassword: root
ingress:
  enabled: true
  ingressClassName: traefik
  hostname: minio-ind.example.com
  extraTls:
    - hosts:
      - minio-ind.example.com
      secretName: example-com-tls
apiIngress:
  enabled: true
  ingressClassName: traefik
  hostname: minio-ind-api.example.com
  extraTls:
    - hosts:
      - minio-ind-api.example.com
      secretName: example-com-tls

 
tls:
  enabled: true
  existingSecret: example-com-tls
```
when I push these files to Github Repo and sync argocd apps
it says
```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm pull --destination /tmp/304546d2-d00e-423b-9dd4-445ae1041d96 --version 14.10.5 --repo https://charts.bitnami.com/bitnami bitnami/minio` failed exit status 1: Error: chart "bitnami/minio" version "14.10.5" not found in https://charts.bitnami.com/bitnami repository
```

so I tried manually add `helm repo add https://charts.bitnami.com/bitnami` then `helm repo update`in the `argocd-server` pod, and re-sync apps still see this error

### What is the expected behavior?

it should deploy minio 

### What do you see instead?

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm pull --destination /tmp/304546d2-d00e-423b-9dd4-445ae1041d96 --version 14.10.5 --repo https://charts.bitnami.com/bitnami bitnami/minio` failed exit status 1: Error: chart "bitnami/minio" version "14.10.5" not found in https://charts.bitnami.com/bitnami repository
```
