### ISSUE TITLE
[bitnami/redmine] Containers not respecting SECRET_KEY_BASE variable when generating secret_token.rb

### ISSUE THREAD

**Issue by duanehughes** [bitnami/charts#31493]
### Name and Version

bitnami/redmine 32.1.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When logging in, users receive "Invalid form authenticity token."

When running the Helm chart in our Kubernetes cluster in Azure AKS, we have populated the values file with ExtraEnvVars as follows:
```yaml
extraEnvVars:
  - name: SECRET_KEY_BASE
    value: my80charactersecretkeygoeshere
```

We have set the replicas value to "2".

When opening the shell on the containers, the expected `SECRET_KEY_BASE` environment variable is there, and the value is correctly set to the extraEnvVars value above.

However, the contents of _/opt/bitnami/redmine/config/initializers/secret_token.rb_ remain different on each container.

e.g:  
container-1:
```
RedmineApp::Application.config.secret_key_base = 'dc4b387e015cd2d5a1f9b4c82a5d9c00cc26635d460d2e205f46cdbf1a43a4c05160d0d0c62ccc54'
```
container-2:
```
RedmineApp::Application.config.secret_key_base = '2d66fc5de07dce3bd1d8bc975e11e03a9aa822342c40af17c2188499f3f6a02ea8da757bb728db82'
```

### Are you using any custom parameters or values?

Relevant section of values.yaml:
```yaml
extraEnvVars:
  - name: SECRET_KEY_BASE
    value: my80charactersecretkeygoeshere
## @param extraEnvVarsCM Name of existing ConfigMap containing extra env vars
##
extraEnvVarsCM: ""
## @param extraEnvVarsSecret Name of existing Secret containing extra env vars
##
extraEnvVarsSecret: ""
## @section Redmine deployment parameters

## @param replicaCount Number of Redmine replicas to deploy
## NOTE: ReadWriteMany PVC(s) are required if replicaCount > 1
##
replicaCount: 2
## Container ports
## @param containerPorts.http Redmine HTTP container port
##
```

I have also tried adding the following settings to _/bitnami/redmine/config/configuration.yaml_ (which lives on persistent storage), but they have made no difference:

```
...
secret_token: 'my80charactersecretkeygoeshere'
...
production:
# specific configuration options for development environment
# that overrides the default ones
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
development:
```

### What is the expected behavior?

The expected behavior is that the contents of each _/opt/bitnami/redmine/config/initializers/secret_token.rb_ should match.

### What do you see instead?

As mentioned before, the contents of _/opt/bitnami/redmine/config/initializers/secret_token.rb_ are different on each container.

e.g:  
container-1:
```
RedmineApp::Application.config.secret_key_base = 'dc4b387e015cd2d5a1f9b4c82a5d9c00cc26635d460d2e205f46cdbf1a43a4c05160d0d0c62ccc54'
```
container-2:
```
RedmineApp::Application.config.secret_key_base = '2d66fc5de07dce3bd1d8bc975e11e03a9aa822342c40af17c2188499f3f6a02ea8da757bb728db82'
```
