### ISSUE TITLE
[bitnami/common] Template rendering is trying to call function

### ISSUE THREAD

**Issue by notwaf** [bitnami/charts#31503]
### Name and Version

bitnami/common v2.29.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. use these configs:
values.yaml
```
configMap:
  data:
    blah: "xcbvxcvbcbv{{ `{{ASDF}}` }}iouyyiouoiyu"
```

configmap.yaml
```
{{- $allValues := include "common.tplvalues.render" ( dict "value" ( include "common.tplvalues.merge" ( dict "values" ( list $.Values .Values $ . ) "context" $ ) ) "context" $ ) | fromYaml }}
{{- with $allValues.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: blah
data:
{{ .data | toYaml | indent 2 }}
{{- end }}
```

2.run helm

### What is the expected behavior?

yaml should render successfully with the following output:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: blah
data:
  blah: "xcbvxcvbcbv{{ASDF}}iouyyiouoiyu"
```

### What do you see instead?

`template: gotpl:5: function "ASDF" not defined`

### Additional information
definitely could be doing something wrong, but seems odd that it breaks like this.

**Comment by javsalgar** [comment]
Hi,

Does the issue happen with this?

```
    blah: "xcbvxcvbcbv{{ print "{{ASDF}}" }}iouyyiouoiyu"
```

**Comment by notwaf** [comment]
@javsalgar also tried with `printf` as well and same issue.

**Comment by javsalgar** [comment]
Could you try removing the common.tplvalues.merge? I think it is being evaluated twice I would like to confirm it

**Comment by notwaf** [comment]
replaced the first line with `{{- $allValues := include "common.tplvalues.render" ( dict "value" ( include "common.tplvalues.merge" ( dict "values" .Values "context" $ ) | fromYaml }}`. did not change. still the same function undefined error.

**Comment by notwaf** [comment]
don't remember this issue happening a few version ago. wondering if it is because of https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_tplvalues.tpl#L15

**Comment by notwaf** [comment]
@dgomezleon @javsalgar any updates here? we are basically blocked on this issue. not sure if there is a work-around for this?

**Comment by dgomezleon** [comment]
Hi @notwaf ,

Would this work for you? 

* configmap.yaml

```
{{- $allValues := include "common.tplvalues.render" ( dict "value" ( include "common.tplvalues.merge" ( dict "values" ( list $.Values .Values $ . ) "context" $ ) ) "context" $ ) | fromYaml }}
{{- with $allValues.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: blah
data:
{{ .data | toYaml | replace "{{`" "{{"| replace "`}}" "}}" | indent 2 }}
{{- end }}
```

* values.yaml
```
configMap:
  data:
    blah: "xcbvxcvbcbv{{`ASDF`}}iouyyiouoiyu"
```

It produces the expected output for me.

**Comment by notwaf** [comment]
nope, no change. still produces the "function undefined" error for me

**Comment by javsalgar** [comment]
Hi,

I tried this and it worked without issues

configmap.yaml
```
kind: ConfigMap
metadata:
  name: blah
data:  {{ include "common.tplvalues.render" (dict "value" .Values.configMap "context" $) | nindent 2 }}
```

values.yaml
```
configMap:
  data:
    blah: "xcbvxcvbcbv{{ `{{ASDF}}` }}iouyyiouoiyu"
```

This provided the expected output

```
# Source: kafka/templates/sample.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: blah
data:
  data:
    blah: xcbvxcvbcbv{{ASDF}}iouyyiouoiyu
```

**Comment by notwaf** [comment]
yep, that does work. is the merge not needed to merge many different included `values.yaml` files together?

**Comment by javsalgar** [comment]
Let me see if I understand it correctly, could you explain in more detail what you want to achieve, and how the values would look like?

Is it that you want the `configMap` section to be an array? Could you please provide a more thorough example that justifies the need to use tplValues.merge

**Comment by notwaf** [comment]
do realise that i forgot to mention that we use helmfile. the helmfile includes all of these values files:
```yaml
---
releases:
  - name: blah
    namespace: blah
    chart: ../the-chart
    values:
      - base.yaml
      - ../../environments/{{ .Environment.Name }}.yaml
      - {{ .Environment.Name }}.yaml
```


the existing yaml files are still good, with a few additions:
values.yaml
```yaml
configMap:
  data:
    blah: "xcbvxcvbcbv{{ `{{ASDF}}` }}iouyyiouoiyu"
```

shared.yaml
```yaml
configMap:
  data:
    foo: iouyyiouoiyu
    merge: together
```
