### ISSUE TITLE
jmx or kafka exporter is not exporting kafka_consumergroup_lag metrics

### ISSUE THREAD

**Issue by skliarie** [bitnami/charts#31511]
### Name and Version

bitnami/jmx-exporter jmx-exporter:1.1.0-debian-12-r2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I enabled oci://registry-1.docker.io/bitnamicharts/kafka helm chart 31.2.0 (with jmx-exporter:1.1.0-debian-12-r2), enabled jmx metrics and see that kafka_consumergroup_lag metrics is not exported anymore.

Probably related to this issue: https://github.com/danielqsj/kafka_exporter/issues/407

Some suggested to use rules for jmx exporter:
https://stackoverflow.com/questions/77401829/exposing-kafka-topic-lags-using-kafka-jmx-exporter

I guess it is doable using metrics.jmx.extraRules in the helm chart. I am not sure what is the right syntax and whether it will work at all, please help me.

### Are you using any custom parameters or values?

no

### What is the expected behavior?

To see kafka_consumergroup_lag metrics somehow - KEDA uses it to autoscale consumer pods

### What do you see instead?

no kafka_consumergroup_lag metrics

**Comment by javsalgar** [comment]
Hi!

You can use the extraRules section just like the rules section in the SO ticket you shared:
```
extraRules:
- pattern: kafka.consumer<type=consumer-fetch-manager-metrics, client-id=(.+), topic=(.+), partition=(.+)><>(records-lag)
  name: kafka_consumer_fetch_records_lag
  labels:
    clientId: "$1"
    topic: "$2"
    partition: "$3"
    help: "Kafka Consumer Fetch Records Lag"
    type: GAUGE
```
