### ISSUE TITLE
[bitnami/etcd] PreUpgrade Job Issue

### ISSUE THREAD

**Issue by sachinphogat** [bitnami/charts#31517]
### Name and Version

bitnami/etcd 11.0.1

### What architecture are you using?

None

### What steps will reproduce the bug?

When we install bitnami/etcd 11.0.1, pre upgrade job fails with below logs.

**Logs:**
```
etcd 15:14:22.69 INFO  ==>
etcd 15:14:22.69 INFO  ==> Welcome to the Bitnami etcd container
etcd 15:14:22.69 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
etcd 15:14:22.70 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
etcd 15:14:22.70 INFO  ==>

Error: open /opt/bitnami/etcd/certs/client/tls.crt: permission denied
etcd 15:14:22.82 ERROR ==> Unable to list members, are all members healthy?
```
This is due to job not having securityContext for fsgroup.
**Change Required:** 
```yaml
securityContext:
      fsGroup: 1001
      fsGroupChangePolicy: Always
```
After adding this below error is coming up.
**Logs:**
```
etcd 15:18:35.64 INFO  ==>
etcd 15:18:35.65 INFO  ==> Welcome to the Bitnami etcd container
etcd 15:18:35.65 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
etcd 15:18:35.65 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
etcd 15:18:35.66 INFO  ==>

{"level":"warn","ts":"2025-01-22T15:18:40.723890Z","logger":"etcd-client","caller":"v3@v3.5.17/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000f0000/etcd-etcd-0.etcd-etcd-headless.iks-0cb58162-2905-45e1-9600-05d0db7e3b57.svc.cluster.local:2380","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"error reading server preface: EOF\""}
Error: context deadline exceeded
etcd 15:18:40.73 ERROR ==> Unable to list members, are all members healthy?
```

This error is due to etcd endpoint connecting to 2380 which is only for peers not for client. We need to change endpoint port to 2379.

Change required from :
```yaml
        - name: ETCD_INITIAL_CLUSTER
          value: etcd-etcd-0=https://etcd-etcd-0.etcd-etcd-headless.iks-0cb58162-2905-45e1-9600-05d0db7e3b57.svc.cluster.local:2380,etcd-etcd-1=https://etcd-etcd-1.etcd-etcd-headless.iks-0cb58162-2905-45e1-9600-05d0db7e3b57.svc.cluster.local:2380,etcd-etcd-2=https://etcd-etcd-2.etcd-etcd-headless.iks-0cb58162-2905-45e1-9600-05d0db7e3b57.svc.cluster.local:2380
```
To:
```yaml
        - name: ETCD_INITIAL_CLUSTER
          value: etcd-etcd-0=https://etcd-etcd-0.etcd-etcd-headless.iks-0cb58162-2905-45e1-9600-05d0db7e3b57.svc.cluster.local:2379,etcd-etcd-1=https://etcd-etcd-1.etcd-etcd-headless.iks-0cb58162-2905-45e1-9600-05d0db7e3b57.svc.cluster.local:2379,etcd-etcd-2=https://etcd-etcd-2.etcd-etcd-headless.iks-0cb58162-2905-45e1-9600-05d0db7e3b57.svc.cluster.local:2379
```
### Are you using any custom parameters or values?
```yaml
    auth:
      client:
        caFilename: ca.crt
        certFilename: tls.crt
        certKeyFilename: tls.key
        enableAuthentication: true
        existingSecret: etcd-etcd-client-tls
        secureTransport: true
        useAutoTLS: false
      peer:
        caFilename: ca.crt
        certFilename: tls.crt
        certKeyFilename: tls.key
        enableAuthentication: true
        existingSecret: etcd-etcd-peer-tls
        secureTransport: true
        useAutoTLS: false
      rbac:
        create: false
    autoCompactionRetention: 3h
    customLivenessProbe:
      exec:
        command:
        - /opt/bitnami/scripts/etcd/healthcheck.sh
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5

```
### What is the expected behavior?

Pre Upgrade Job should be succeed.

### What do you see instead?
```
etcd 15:14:22.69 INFO  ==>
etcd 15:14:22.69 INFO  ==> Welcome to the Bitnami etcd container
etcd 15:14:22.69 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
etcd 15:14:22.70 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
etcd 15:14:22.70 INFO  ==>

Error: open /opt/bitnami/etcd/certs/client/tls.crt: permission denied
etcd 15:14:22.82 ERROR ==> Unable to list members, are all members healthy?
```
