### ISSUE TITLE
[bitnami/thanos] Ruler configmap not loading since chart 15.10.0

### ISSUE THREAD

**Issue by svenjochems-nsx** [bitnami/charts#31525]
### Name and Version

bitnami/thanos 15.10.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. values.yaml
```
  ruler:
    enabled: true
    existingConfigmap: "custom-thanos-rules"
```
2. Create configMap `custom-thanos-rules` with `xxx.yml` files
3. Deploy thanos ruler

### What is the expected behavior?

The thanos-ruler pod loads all files from the configMap. Log message is logged with number of files, in my case `5`
```
caller=rule.go:1043 level=info component=rules msg="reload rule files" numFiles=5
```

### What do you see instead?

The thanos-ruler pod  does not load any files from the configMap.
```
caller=rule.go:1043 level=info component=rules msg="reload rule files" numFiles=0
```

### Additional information

This could be related to https://github.com/bitnami/charts/pull/31377 or the ruler image update.

The diff in argo-cd shows the following (left = `15.10.2`, right = `15.9.2`)
There is a difference in double quotes added in the new version around the `--rule-file` parameter.
![Image](https://github.com/user-attachments/assets/3b883fef-c8e1-43e6-9383-f611c2bc3add)

**Comment by javsalgar** [comment]
Hi!

Could you share an example configmap that triggers the issue?

**Comment by migruiz4** [comment]
Thank you for the detailed explanation! 

I think this was the cause of the issue: https://github.com/bitnami/charts/pull/31377

I have submitted this PR reverting the quote change (while keeping the feature added in the previous PR).

@svenjochems-nsx I would appreciate it if you could give it a try and confirm it fixes the issue.

**Comment by svenjochems-nsx** [comment]
@migruiz4 

Thanks!

I'm using argocd to deploy the chart. I there a chart version I can use to test this fix?

**Comment by mikkeschiren** [comment]
I am using `.ruler.existingConfigmap` and also have the issue.

**Comment by mikkeschiren** [comment]
And - tested out the removal of quotes, which fixed the issue for me.

**Comment by michael-niemand** [comment]
removing the quotes did NOT solve the issue for me (version 15.12.2, deploying with flux)

```
...
      affinity: {}
      logFormat: json
      alertmanagers:
        - http://alertmanager-operated.monitoring.svc.cluster.local:9093
      existingConfigmap: thanos-rules <--- was "thanos-rules" before, makes no difference
      enabled: true
...

```

**Comment by Avatos** [comment]
I can confirm that the quoted rule-file flag is causing this issue. As a workaround I used the extraFlags helm value to have a working config for the current chart version.
```yaml
ruler:
  extraFlags:
  - --rule-file=/conf/rules/*.yml 
```
