### ISSUE TITLE
[bitnami/milvus] Milvus helm deployment fails to check-for-s3 when using GCS

### ISSUE THREAD

**Issue by cisarpavel** [bitnami/charts#31538]
### Name and Version

bitnami/milvus:11.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. prepare values like this:
  ```
    externalS3:
      host: storage.googleapis.com
      port: 443
      bucket: "my-bucket"
      tls:
        enabled: true
      cloudProvider: "gcp"
      accessKeyID: "my-access-id"
      accessKeySecret: "my-secret-key"
  ```
2. and just deploy 

### Are you using any custom parameters or values?

  ```
    externalS3:
      host: storage.googleapis.com
      port: 443
      bucket: "my-bucket"
      tls:
        enabled: true
      cloudProvider: "gcp"
      accessKeyID: "my-access-id"
      accessKeySecret: "my-secret-key"
  ```

### What is the expected behavior?

wait-for-s3 command should successfully recognize existing bucket in GCS.

### What do you see instead?

```
Checking connection to https://storage.googleapis.com:443
... many checks
Error connecting to https://storage.googleapis.com:443
```
Simple `curl` without extra headers is not sufficient test.
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>MissingSecurityHeader</Code><Message>Your request was missing a required header.</Message><Details>Authorization</Details></Error>
```
