### ISSUE TITLE
[bitnami/etcd] Error while upgrading from 4.8.9 to 4.8.14

### ISSUE THREAD

**Issue by mboutet** [bitnami/charts#3158]
**Which chart**:
etcd-4.8.14

**Describe the bug**
Error updating chart from 4.8.9 to 4.8.14

**To Reproduce**
1. Install etcd-4.8.9
```
  priorityClassName: high-priority
  etcd:
    initialClusterState: new
  statefulset:
    replicaCount: 3
  pdb:
    enabled: true
    minAvailable: 2
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels: {{- include "etcd.etcd.matchLabels" . | nindent 10 }}
  auth:
    rbac:
      enabled: true
  persistence:
    enabled: true
    storageClass: azure-disk-premium-retain-and-wait-for-first-consumer
    size: 8Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 256Mi
      cpu: 200m
  disasterRecovery:
    enabled: true
    cronjob:
      snapshotHistoryLimit: 3
      historyLimit: 3
    pvc:
      storageClassName: azure-file-standard-zrs-retain-and-wait-for-first-consumer
      size: 32Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
```
2. Upgrade the chart to 4.8.14 with `etcd.initialClusterState=existing`
3. See error
```
==> Bash debug is off
==> Detected data from previous deployments...
==> Updating member in existing cluster...
Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex
```

**Expected behavior**
It should work (it used to work up to 4.8.9 at least)

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-27T00:38:11Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"c02cd11cc8bced1391937fe271c3b9c9fe9befa0", GitTreeState:"clean", BuildDate:"2020-06-24T19:57:20Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
