### ISSUE TITLE
[bitnami/wordpress] mariadb readiness probe fails

### ISSUE THREAD

**Issue by a01fe** [bitnami/charts#3159]
**Which chart**:
bitnami/wordpress-9.3.21

**Describe the bug**
The `wordpress-maria` stateful set is stuck in a crash loop because the `wordpress-mariadb-0` pod's readiness probe fails with:

```
Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)' Check that mysqld is running and that the socket: '/opt/bitnami/mariadb/tmp/mysql.sock' exists!
```

It worked ok after the initial `helm install` but now fails as above after nodes were restarted for installing OS updates.

`/opt/bitnami/mariadb/tmp/mysql.sock` does not exist in the container:

```
$ kubectl exec -i -t -n wga wordpress-mariadb-0 -- sh -c "ls -l /opt/bitnami/mariadb/tmp"
total 0
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:34:02Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4+k3s1", GitCommit:"97b7a0e9df2883f08028fb7171c1e62fc1899a0c", GitTreeState:"clean", BuildDate:"2020-06-18T01:30:45Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
`wordpress-mariadb-0` container logs:

```
mariadb 21:25:36.62 
mariadb 21:25:36.62 Welcome to the Bitnami mariadb container
mariadb 21:25:36.62 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 21:25:36.63 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 21:25:36.63 
mariadb 21:25:36.63 INFO  ==> ** Starting MariaDB setup **
mariadb 21:25:36.64 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 21:25:36.64 INFO  ==> Initializing mariadb database
mariadb 21:25:36.65 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mariadb 21:25:36.65 INFO  ==> Using persisted data
mariadb 21:25:36.68 INFO  ==> Running mysql_upgrade
mariadb 21:25:36.68 INFO  ==> Starting mariadb in background
```

Values applied on `helm install`:

```
global:
  storageClass: longhorn

wordpressUsername: admin
wordpressPassword: <redacted>
wordpressEmail: <redacted>
wordpressFirstName: <redacted>
wordpressLastName: <redacted>
wordpressBlogName: <redacted>
wordpressScheme: https

livenessProbeHeaders:
  - name: X-Forwarded-Proto
    value: https
readinessProbeHeaders:
  - name: X-Forwarded-Proto
    value: https

updateStrategy:
  type: Recreate

replicaCount: 1

service:
  type: ClusterIP

ingress:
  enabled: true
  hostname: <redacted>
  annotations:
    kubernetes.io/ingress.class: traefik-external

persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 2Gi

mariadb:
  rootUser:
    password: <redacted>
  master:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 8Gi

```
