### ISSUE TITLE
[bitnami/redis] after election, Redis master attempts to replicate from itself

### ISSUE THREAD

**Issue by chris-vest** [bitnami/charts#31617]
### Name and Version

bitnami/redis 20.6.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Set up Redis cluster using the given settings, and after an election, the master will try to sync from itself.

```
redis-test-seq-redis-sentinel-ue1-node-2 redis 1:S 28 Jan 2025 10:10:23.927 * Connecting to MASTER redis-test-seq-redis-sentinel-ue1-node-2.redis-test-seq-redis-sentinel-ue1-headless.redis-test-seq.svc.cluster.local:6379
redis-test-seq-redis-sentinel-ue1-node-2 redis 1:S 28 Jan 2025 10:10:23.927 * MASTER <-> REPLICA sync started
redis-test-seq-redis-sentinel-ue1-node-2 redis 1:S 28 Jan 2025 10:10:23.927 * Non blocking connect for SYNC fired the event.
redis-test-seq-redis-sentinel-ue1-node-2 redis 1:S 28 Jan 2025 10:10:23.927 * Master replied to PING, replication can continue...
redis-test-seq-redis-sentinel-ue1-node-2 redis 1:S 28 Jan 2025 10:10:23.927 * Trying a partial resynchronization (request 49feb8dee03e307c8cf19575a02be2228ec92403:32706362302).
redis-test-seq-redis-sentinel-ue1-node-2 redis 1:S 28 Jan 2025 10:10:23.927 * Master is currently unable to PSYNC but should be in the future: -NOMASTERLINK Can't SYNC while not connected with my master
```

As you can see, the pod `redis-test-seq-redis-sentinel-ue1-node-2` tries to connect to itself via `redis-test-seq-redis-sentinel-ue1-node-2.redis-test-seq-redis-sentinel-ue1-headless.redis-test-seq.svc.cluster.local:6379`. This causes a number of issues, and often takes a long time and a lot of reelections before it resolves itself.

### Are you using any custom parameters or values?

```yaml
replica:
  externalMaster:
    enabled: true
    host: redis-sentinel-master.redis-test-seq.svc.cluster.local

sentinel:
  enabled: true
  externalMaster:
    enabled: true
    host: redis-sentinel-master.redis-test-seq.svc.cluster.local

architecture: "replication"
```

Also happens without `replica.externalMaster.enabled=true`:

```yaml
sentinel:
  enabled: true
  externalMaster:
    enabled: true
    host: redis-sentinel-master.redis-test-seq.svc.cluster.local

architecture: "replication"
```

### What is the expected behavior?

The newly elected master should not attempt to resync from itself after it has been elected.

### What do you see instead?

The master attempts to sync from itself after it has been elected, which means applications using Sentinel cannot write to the master during this time. Usually 2 - 3 elections need to happen before it resolves, and in this time a lot of errors have occurred.

You can see the metrics here: 

![Image](https://github.com/user-attachments/assets/9ab77860-92f0-4f58-ad08-a94cbf5ecc16)

After the third election, the newly elected master stops trying to sync from itself, and the cluster is now healthy again.
