### ISSUE TITLE
[bitnami/redis] Custom redis metrics don't show up properly amongst metrics

### ISSUE THREAD

**Issue by rlenkov** [bitnami/charts#31619]
### Name and Version

bitnami/redis

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have a simple redis setup where I'd like to test creating some custom metrics. Here's my values.yaml file:

```yaml
architecture: standalone
commonLabels:
  app: redis-master
metrics:
  enabled: true
  extraVolumeMounts:
    - name: redis-metrics-script-file
      mountPath: "/mnt/redis/"
      readOnly: true
  extraVolumes:
    - name: "redis-metrics-script-file"
      configMap:
        name: "redis-metrics-script"
  extraArgs:
    script: "/mnt/redis/pubsub_metrics.lua"
extraDeploy:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: "redis-metrics-script"
    data:
      pubsub_metrics.lua: |
        local active_channels = redis.call('PUBSUB', 'CHANNELS')
        return {'custom_redis_pubsub_active_channels', tostring(#active_channels)}
```

I did a port forward on my metrics endpoint to look at the raw metrics and I'd expect to see this `custom_redis_pubsub_active_channels` metric show up but it's not there. I see a reference to it via the `redis_script_values` metric as such:
```
# HELP redis_script_result Result of the collect script evaluation
# TYPE redis_script_result gauge
redis_script_result{filename="/mnt/redis/pubsub_metrics.lua"} 1
# HELP redis_script_values Values returned by the collect script
# TYPE redis_script_values gauge
redis_script_values{filename="/mnt/redis/pubsub_metrics.lua",key="custom_redis_pubsub_active_channels"} 0
```

Is there a way to add custom metrics properly, or in a best case, even defining type (gauge, counter, etc)?

### Are you using any custom parameters or values?

No custom parameters used.

### What is the expected behavior?

I'd expect the custom metrics to show up as built-in metrics, like:
```
# HELP redis_memory_used_lua_bytes memory_used_lua_bytes metric
# TYPE redis_memory_used_lua_bytes gauge
redis_memory_used_lua_bytes 34816
```

### What do you see instead?

I don't see the custom metric showing up.

### Additional information

I use the otlc prometheus receiver to collect the metrics and send them to kibana, which might be a bit special of a setup, but as I said above, the problem arises earlier, detectable at the redis metrics endpoint. So I think my scraping setup is not relevant here.
