### ISSUE TITLE
[bitnami/zookeeper] healthcheck with SSL and auth "none" results in stale openssl procesess

### ISSUE THREAD

**Issue by Drumar** [bitnami/charts#31613]
### Name and Version

bitnami/zookeeper 13.7.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. In this environment: An AWS EKS cluster
2. with this config: see the values.yaml provided
4. Run ...: helm install
5. See error: the service seems to startup just nice. However, after some time the healthcheck fails due to a fork error because of insufficient resouces. Deeper inspection learns that there are many <defunct>  openssl processes.

In issue #29603 this problem was already reported, but the ticket is closed due to inactivity. The problem lies in the healthcheck because there is no mTLS the client certificates are never read, leading to never-ending openssl commands.

### Are you using any custom parameters or values?
```yaml
image:
  ## default is false
  debug: true

auth:
  client:
    ## default is false: I know the values are not used, because enabled is false. It is intended to use it at some point though.
    enabled: false
    clientUser: zooclient
    clientPassword: zooPassword
    serverUsers: zooserver
    serverPasswords: zooPassword
  quorum:
    enabled: false
    learnerUser: zoolearner
    learnerPassword: zooPassword
    serverUsers: zoolearner
    serverPasswords: zooPassword

extraVolumes:
- name: zookeeper-keystore
  secret:
    defaultMode: 288
    secretName: zookeeper-keystore
- name: zookeeper-truststore
  secret:
    defaultMode: 288
    secretName: zookeeper-truststore

extraVolumeMounts:
- name: zookeeper-keystore
  mountPath: /certs/keystore
  readOnly: true
- name: zookeeper-truststore
  mountPath: /certs/truststore
  readOnly: true

fourlwCommandsWhitelist: conf,cons,crst,dump,envi,ruok,srst,srvr,stat,wchs,wchc,dirs,wchp,mntr,isro,gtmk,stmk
logLevel: INFO
replicaCount: 3

startupProbe:
  enabled: true

resources:
  requests:
    cpu: 2
    memory: 512Mi
  limits:
    cpu: 3
    memory: 1024Mi

pdb:
  maxUnavailable: 1
service:
  annotations: {
      service.beta.kubernetes.io/aws-load-balancer-internal: "true",
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip",
      service.beta.kubernetes.io/aws-load-balancer-subnets: "mysubnet1, mysubnet2, mysubnet3"
    }
  type: LoadBalancer

persistence:
  enabled: true
  storageClass: efs-zookeeper-sc
  size: 10Gi

## This one is for Prometheus -> to be filled in later.
metrics:
  enabled: false
  service:
    type: ClusterIP

tls:
  client:
    enabled: true
    auth: "none"
    autoGenerated: false
    existingSecret: zookeeper-certs
    existingSecretKeystoreKey: keystore.jks
    existingSecretTruststoreKey: zookeeper.truststore.jks
    keystorePassword: mykeystorepassword
    truststorePassword: mytruststorepassword
  quorum:
    enabled: false

## Add more time for the livenessProbe; I have the feeling we're just having a few too many timeouts
livenessProbe:
  timeoutSeconds: 8
  probeCommandTimeout: 5
  periodSeconds: 12

## Add more time for the readinessProbe; I have the feeling we're just having a few too many timeouts
readinessProbe:
  periodSeconds: 12
  timeoutSeconds: 8
  probeCommandTimeout: 4
```

### What is the expected behavior?

No zombies, but a happily running healthcheck

### What do you see instead?

`ps -ef | grep openssl | wc -l`
435
