### ISSUE TITLE
[bitnami/etcd] preupgrade job fails due to affinity rules and pod annotations

### ISSUE THREAD

**Issue by ismaildem** [bitnami/charts#31618]
### Name and Version

bitnami/etcd 11.0.4

### What architecture are you using?

None

### What steps will reproduce the bug?

We try to deploy bitnami/etcd 11.0.4 with podAnnotations and affinity 

### Are you using any custom parameters or values?

```yaml
...

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - etcd
      topologyKey: topology.kubernetes.io/zone

podAnnotations:
  my.important.annotation: something
...
```

### What is the expected behavior?

preupgrade job should work

### What do you see instead?

Due to the affinity rules, which we have defined for the etcd pods, the preupgrade Job failed. The preupgrade job can't be scheduled and is stuck in Pending. 
Are the Affinity Rules for the preupgrade job really necessary?

It is the same with the annotations. We use the annotations to make some changes in the pods using mutating webhooks.
Due to this, the prupgrade job also fails here, because the mutating webhook fails.

Perhaps it should be allowed separate values for the preupgrade job or at least make the affinity and the annotations switch off for it.
