### ISSUE TITLE
[bitnami/postgresql-ha] Add backups retention for cronjob dumps

### ISSUE THREAD

**Issue by ESlam-Yousry** [bitnami/charts#31647]
### Name and Version

bitnami/postgres-ha
version: latest

### What is the problem this feature will solve?

This will enable you control retention of postgres dump files, In order not to let PersistentVolumeClaim be full because no control made on these files and it can take persist dump files forever

### What is the feature you are proposing to solve the problem?

so simple solution to add find command to control how many backup files we can keep in ${PG_DUMP_DIR} as the following
```
        spec:
          containers:
          - command:
            - /bin/sh
            - -c            
            - |
              # keeping 5 backup files (5 days backups)
              find ${PGDUMP_DIR} -type f -name "pg_dumpall-*.pgdump"  | awk -F'[-.]' '{print $2"-"$3"-"$4, $0}'  | awk -v cutoff="$(date -d '4 days ago' +%Y-%m-%d)" '$1 < cutoff {print $2}'  | xargs rm -f
              # dumping database
              pg_dumpall --clean --if-exists --load-via-partition-root --quote-all-identifiers
              --no-password --file=${PGDUMP_DIR}/pg_dumpall-$(date '+%Y-%m-%d-%H-%M').pgdump
```
