### ISSUE TITLE
No connection to nodes

### ISSUE THREAD

**Issue by pzabolotniy** [bitnami/charts#31672]
### Name and Version

bitnami/redis-cluster:7.4.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Environment:
```
> docker system info
Client:
 Version:    27.4.0
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  ai: Ask Gordon - Docker Agent (Docker Inc.)
    Version:  v0.5.1
    Path:     /Users/zabolotniy/.docker/cli-plugins/docker-ai
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.2-desktop.1
    Path:     /Users/zabolotniy/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.31.0-desktop.2
    Path:     /Users/zabolotniy/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.37
    Path:     /Users/zabolotniy/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Beta) (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/zabolotniy/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/zabolotniy/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.27
    Path:     /Users/zabolotniy/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/zabolotniy/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.4.0
    Path:     /Users/zabolotniy/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/zabolotniy/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.15.1
    Path:     /Users/zabolotniy/.docker/cli-plugins/docker-scout

Server:
 Containers: 6
  Running: 1
  Paused: 0
  Stopped: 5
 Images: 1
 Server Version: 27.4.0
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.10.14-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.656GiB
 Name: docker-desktop
 ID: 67f9dad8-fc08-488c-abbd-69d8493d4b98
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/zabolotniy/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```
2. Config:
```
docker-compose.yml:
networks:
  redisnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.4
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.4
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.4
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:7.4
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:7.4
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:7.4
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'  
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_PORT_NUMBER=8000'
    networks:
      redisnet:
        ipv4_address: 172.18.0.2
```
3. Run
```
docker compose up -d
```
4. Check logs in redis-node-5 container:
```
docker logs bitnami-redis-cluster-redis-node-0-1
```

### Are you using any custom parameters or values?

No custom variables

### What is the expected behavior?

No error logs.
Connection to redis-node-0 and rest of the nodes is established succesfully

### What do you see instead?

Error logs
```
38:C 30 Jan 2025 08:25:39.714 # WARNING: Changing databases number from 16 to 1 since we are in cluster mode
38:C 30 Jan 2025 08:25:39.714 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
38:C 30 Jan 2025 08:25:39.714 * Redis version=7.4.2, bits=64, commit=00000000, modified=1, pid=38, just started
38:C 30 Jan 2025 08:25:39.714 * Configuration loaded
38:M 30 Jan 2025 08:25:39.714 * monotonic clock: POSIX clock_gettime
38:M 30 Jan 2025 08:25:39.716 * Running mode=cluster, port=8000.
Could not connect to Redis at redis-node-0:8000: Name or service not known
Node redis-node-0 not ready, waiting for all the nodes to be ready...
38:M 30 Jan 2025 08:25:39.723 * No cluster configuration found, I'm 5b00979c8d58ff3cb69758f8d879bbc613b85ff7
38:M 30 Jan 2025 08:25:39.728 * Server initialized
38:M 30 Jan 2025 08:25:39.730 * Creating AOF base file appendonly.aof.1.base.rdb on server start
38:M 30 Jan 2025 08:25:39.732 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
38:M 30 Jan 2025 08:25:39.732 * Ready to accept connections tcp
Could not connect to Redis at redis-node-0:8000: Name or service not known
Node redis-node-0 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at redis-node-0:8000: Name or service not known
Node redis-node-0 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at redis-node-0:8000: Name or service not known
```
