### ISSUE TITLE
[bitnami/rabbitmq] helm chart mutiple user creation have issue when used with user defined value file

### ISSUE THREAD

**Issue by iamraj007** [bitnami/charts#31673]
### Name and Version

bitnamicharts/rabbitmq  4.0.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install rabbitmq helm chart with Value file in rabbitmq ns 
CHART NAME: rabbitmq
CHART VERSION: 15.2.4
APP VERSION: 4.0.5
NAMESPACE: rabbitmq
Kubernetes version: 1.28.15

helm command:

helm install rabbitmq  rabbitmq/rabbitmq -f value_rabbitmq.yaml --namespace rabbitmq --create-namespace

```
File name: value_rabbitmq.yaml 
auth:
  password: CHA/aAw230029
auth:
  username: myadmuser
extraSecrets:
   load-definition:
     load_definition.json: |
       {
         "users": [
           {
             "name":"service",
             "password_hash":"uZdUyJEGH57+18XXXXXXXXXXXXXXXXXXXXXX7I45la",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":"serviceapp"
           }
         ],
         "vhosts": [
           {
             "name": "service"
           }
         ],
         "permissions": [
           {
             "user":"service",
             "vhost":"service",
             "configure":".*",
             "write":".*",
             "read":".*"
           }
         ],
         "policies": [
           {
             "vhost": "service",
             "name": "KindOfHA",
             "pattern": ".*",
             "apply-to": "all",
             "definition": {
               "dead-letter-strategy": "at-most-once",
               "delivery-limit": -1
             }
           }
         ],
         "users": [
           {
             "name": "{{ .Values.auth.username }}",
             "password": "{{ .Values.auth.password }}",
             "tags": "administrator"
           }
         ]
       }
loadDefinition:
  enabled: true
  existingSecret: load-definition
extraConfiguration: |
  load_definitions = /app/load_definition.json
replicaCount: 3
```

2.  Validate in running pod if users created as expected?
```
I have no name!@rabbitmq-0:/app$ tail /app/load_definition.json
    }
  ],
  "users": [
    {
      "name": "myuser",
      "password": "",
      "tags": "administrator"
    }
  ]
}
I have no name!@rabbitmq-0:/app$


$ rabbitmqctl list_users --formatter json
[
{"user":"service","tags":["serviceapp"]}
]
I have no name!@rabbitmq-0:/app$
```

3. Expected outcome: 
User "myuser" should be created with given password for which seams to have empty password from mounted json file (also user was to be tagged: administrator) but its not created and only other user was created named "service". 

### Are you using any custom parameters or values?

 helm install rabbitmq  rabbitmq/rabbitmq -f Value_rabbitmq.yaml --namespace rabbitmq --create-namespace

Value_rabbitmq.yaml file":
```
auth:
  password: CHA/aAw230029
auth:
  username: myadmuser
extraSecrets:
   load-definition:
     load_definition.json: |
       {
         "users": [
           {
             "name":"service",
             "password_hash":"uZdUyJEGH57+18XXXXXXXXXXXXXXXXXXXXXX7I45la",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":"serviceapp"
           }
         ],
         "vhosts": [
           {
             "name": "service"
           }
         ],
         "permissions": [
           {
             "user":"service",
             "vhost":"service",
             "configure":".*",
             "write":".*",
             "read":".*"
           }
         ],
         "policies": [
           {
             "vhost": "service",
             "name": "KindOfHA",
             "pattern": ".*",
             "apply-to": "all",
             "definition": {
               "dead-letter-strategy": "at-most-once",
               "delivery-limit": -1
             }
           }
         ],
         "users": [
           {
             "name": "{{ .Values.auth.username }}",
             "password": "{{ .Values.auth.password }}",
             "tags": "administrator"
           }
         ]
       }
loadDefinition:
  enabled: true
  existingSecret: load-definition
extraConfiguration: |
  load_definitions = /app/load_definition.json
replicaCount: 3
```

### What is the expected behavior?

Was expecting  2 user creation but can see only 1.

$ rabbitmqctl list_users --formatter json
[
{"user":"service","tags":["serviceapp"]}
]
I have no name!@rabbitmq-0:/app$

### What do you see instead?

Only one user named "service" was created.

### Additional information

If loadDefinition is set to true then user creation dont work (even if given in value file)that is a known limitation given in [Readme page](https://github.com/bitnami/containers/blob/main/bitnami/rabbitmq/README.md)
loadDefinition:
  enabled: true

See RABBITMQ_SECURE_PASSWORD below: 

| Name                                           | Description                                                                                                                                                                                      | Default Value                        |
|------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------|
| `RABBITMQ_CONF_FILE`                           | RabbitMQ configuration file.                                                                                                                                                                     | `${RABBITMQ_CONF_DIR}/rabbitmq.conf` |
| `RABBITMQ_DEFINITIONS_FILE`                    | Whether to load external RabbitMQ definitions. This is incompatible with setting the RabbitMQ password securely.                                                                                 | `/app/load_definition.json`          |
| `RABBITMQ_SECURE_PASSWORD`                     | Whether to set the RabbitMQ password securely. **This is incompatible with loading external** RabbitMQ definitions.                                                                                  | `no`                                 |

I open to see user who have got this working and correct myself.

**Comment by iamraj007** [comment]
Also this is what was trying to accomplish. 
At the end wish to have load-definition file create a user or two and create one more user with admin privilege.
So that we have 2 or more different user and the admin one is created with some new/system generated secrete (that are not stored in chart values..)

**Comment by fmulero** [comment]
Hi @iamraj007, thanks for using bitnami/charts.

Not sure if I understood your issue but I've seen an error in your `load_definition.json` file, the `users` key appears twice, so one of them is not being taking into account. Please try this:

```yaml
auth:
  password: XXXXXXXXXXX
auth:
  username: myadmuser
extraSecrets:
   load-definition:
     load_definition.json: |
       {
         "users": [
           {
             "name":"service",
             "password_hash":"uZdUyJEGH57+18XXXXXXXXXXXXXXXXXXXXXX7I45la",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":"serviceapp"
           },
           {
             "name": "{{ .Values.auth.username }}",
             "password": "{{ .Values.auth.password }}",
             "tags": "administrator"
           }
         ],
         "vhosts": [
           {
             "name": "service"
           }
         ],
         "permissions": [
           {
             "user":"service",
             "vhost":"service",
             "configure":".*",
             "write":".*",
             "read":".*"
           }
         ],
         "policies": [
           {
             "vhost": "service",
             "name": "KindOfHA",
             "pattern": ".*",
             "apply-to": "all",
             "definition": {
               "dead-letter-strategy": "at-most-once",
               "delivery-limit": -1
             }
           }
         ]
       }
loadDefinition:
  enabled: true
  existingSecret: load-definition
extraConfiguration: |
  load_definitions = /app/load_definition.json
replicaCount: 3
```

**Comment by iamraj007** [comment]
That was on purpose, I was trying to create two users with different
privileges
That is why we have two of them in load definition, is there any other way
to import user's definition when we are using loadDefinition import?

**Comment by iamraj007** [comment]
> Hi [@iamraj007](https://github.com/iamraj007), thanks for using bitnami/charts.
> 
> Not sure if I understood your issue but I've seen an error in your `load_definition.json` file, the `users` key appears twice, so one of them is not being taking into account. Please try this:
> 
> auth:
>   password: XXXXXXXXXXX
> auth:
>   username: myadmuser
> extraSecrets:
>    load-definition:
>      load_definition.json: |
>        {
>          "users": [
>            {
>              "name":"service",
>              "password_hash":"uZdUyJEGH57+18XXXXXXXXXXXXXXXXXXXXXX7I45la",
>              "hashing_algorithm":"rabbit_password_hashing_sha256",
>              "tags":"serviceapp"
>            },
>            {
>              "name": "{{ .Values.auth.username }}",
>              "password": "{{ .Values.auth.password }}",
>              "tags": "administrator"
>            }
>          ],
>          "vhosts": [
>            {
>              "name": "service"
>            }
>          ],
>          "permissions": [
>            {
>              "user":"service",
>              "vhost":"service",
>              "configure":".*",
>              "write":".*",
>              "read":".*"
>            }
>          ],
>          "policies": [
>            {
>              "vhost": "service",
>              "name": "KindOfHA",
>              "pattern": ".*",
>              "apply-to": "all",
>              "definition": {
>                "dead-letter-strategy": "at-most-once",
>                "delivery-limit": -1
>              }
>            }
>          ]
>        }
> loadDefinition:
>   enabled: true
>   existingSecret: load-definition
> extraConfiguration: |
>   load_definitions = /app/load_definition.json
> replicaCount: 3


Thanks for the input, was able to create those two users (i ignored the json user block should have put it together).

The issue i am still facing with above is the password given in auth.password from json is not working even if i update password and  pass hashing to rabbit_password_hashing_sha256 (in case plain text was issue).
```
> auth:
>   password: XXXXXXXXXXX
            Above should match with load_definition.json value of users.password (and should work):
users: [
          { "password": "{{ .Values.auth.password }}",
```
In logs all i get is [warning] <0.1524.0> HTTP access denied: user 'myuser' - **invalid credentials**

**Comment by fmulero** [comment]
Same problem in your configuration two entries for `auth` key, the second overrides the first. Try this:
```yaml
auth:
  username: myadmuser
  password: XXXXXXXX
...
```

**Comment by iamraj007** [comment]
> Same problem in your configuration two entries for `auth` key, the second overrides the first. Try this:
> 
> auth:
>   username: myadmuser
>   password: XXXXXXXX
> ...

Thanks @fmulero that works.

Last question just in case there is any way..
Is it possible that a default user/admin is created by rabbitmq/chart as secret (so that it remain secured and not in any repository as git commit) and we are able to define/import with user definition(like above in this git issue) which create a user or two?

**Comment by fmulero** [comment]
You can create your own secret and with the rabbitmq password, for instance:
```console
$ kubectl create secret generic mysecret --from-literal=rabbitmq-password=XXXXXXXXXXXX
secret/mysecret created
```

And set that secret in your values file:
```yaml
auth:
  username: myadmuser
  existingPasswordSecret: mysecret
...
```

In this case you can not use the extraSecrets template as it is, because you don't have the value `auth.password`. You could use something like this:
```json
           {
             "name": "{{ .Values.auth.username }}",
             "password": "{{ ( b64dec ( get ( lookup "v1" "Secret" "default" "mysecret").data "rabbitmq-password" ) )}}",
             "tags": "administrator"
           }
```

But function lookup has a lot of limitation, please check them in the [official documentation](https://helm.sh/docs/chart_template_guide/function_list/#lookup)

With this, I'll close this case. If you have any other question or problem please open a new issue.
