### ISSUE TITLE
[bitnami/kube-state-metrics] Enable customResourceStateMetrics in kube-state-metrics to monitor VPAs

### ISSUE THREAD

**Issue by stucki-stuck** [bitnami/charts#31686]
### Name and Version

bitnami/kube-state-metrics

### What is the problem this feature will solve?

Since version 2.9 of `kube-state-metrics`, metrics support for kubernetes VPAs has been moved to custom metrics. 

These articles explain how to configure them: 
- https://medium.com/linkbynet/request-limits-recommendations-using-vpa-goldilocks-and-grafana-2239b19bfd1
- https://www.vrchr.fr/posts/2024/2024-01-09-kube-state-metrics-vpa/
- https://gist.github.com/rverchere/780bd988b8f385a00644a1ec9f425be3
- https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/extend/customresourcestate-metrics.md#verticalpodautoscaler

But they all use [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts/blob/c1986fc920d93d7aa791a0f3f19d467b5801ef4c/charts/kube-state-metrics/values.yaml#L407) . 
This feature is missing from the bitnami chart.

### What is the feature you are proposing to solve the problem?

I'm going to open a PR that implements this mechanism.

For those looking for the VPA metrics configuration in grafana, I've set the `values.yaml` for the `bitnami/kube-state-metrics` chart as follow:
```yaml
  rbac:
    rules:
      - apiGroups: ["autoscaling.k8s.io"]
        resources:
          - verticalpodautoscalers
        verbs: ["list", "watch"]
  customResourceState:
    enabled: true
    configuration:
      kind: CustomResourceStateMetrics
      spec:
        resources:
          - groupVersionKind:
              group: autoscaling.k8s.io
              kind: "VerticalPodAutoscaler"
              version: "v1"
            labelsFromPath:
              verticalpodautoscaler: [metadata, name]
              namespace: [metadata, namespace]
              target_api_version: [spec, targetRef, apiVersion]
              target_kind: [spec, targetRef, kind]
              target_name: [spec, targetRef, name]
            metrics:
              # Labels
              - name: "verticalpodautoscaler_labels"
                help: "VPA container recommendations. Kubernetes labels converted to Prometheus labels"
[... The remainder is here : https://gist.github.com/rverchere/780bd988b8f385a00644a1ec9f425be3 ...]
```
Then follow the tutorial to the end: https://medium.com/linkbynet/request-limits-recommendations-using-vpa-goldilocks-and-grafana-2239b19bfd1
