### ISSUE TITLE
Valkey maxmemory gets ignored

### ISSUE THREAD

**Issue by DasMagischeToastbrot** [bitnami/charts#31690]
### Name and Version

bitnami/valkey-cluster 2.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: valkey
  namespace: my-test
spec:
  interval: 1h0m0s
  url: oci://registry-1.docker.io/bitnamicharts/valkey-cluster
  ref:
    tag: 2.1.1
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
  namespace: my-test
spec:
  chartRef:
    kind: OCIRepository
    name: valkey
    namespace: my-test
  interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: valkey-values
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-values
  namespace: my-test
data:
  values.yaml: |
    cluster:
      nodes: 6
    existingSecret: my-valkey-password
    metrics:
      service:
        ports:
          http: 8010
      enabled: true
    valkey:
      resourcesPreset: micro
      configmap:  |
        maxmemory-policy: allkeys-lru
        maxmemory: 350mb
    pdb:
      maxUnavailable: "2"
    networkPolicy:
      enabled: false

```

### What is the expected behavior?

It should respect the maxmemory

### What do you see instead?

![Image](https://github.com/user-attachments/assets/26c46aa2-49ff-4fc1-b0c2-943e4984c48a)
