### ISSUE TITLE
[bitnami/airflow] `worker_container_repository` in `airflow.cfg` does not use `global.imageRegistry`

### ISSUE THREAD

**Issue by AbigailColwell** [bitnami/charts#31693]
### Name and Version

bitnami/airflow 22.4.7

### What architecture are you using?

None

### What steps will reproduce the bug?

1. run `helm template airflow oci://registry-1.docker.io/bitnamicharts/airflow  --set 'global.imageRegistry=docker.my-company.com' --set 'global.security.allowInsecureImages=true' --set 'executor=KubernetesExecutor'`
2. Find the output for `airflow/templates/config/configmap.yaml`
```yaml
# Source: airflow/templates/config/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow
  namespace: "my-namespace"
  labels:
    app.kubernetes.io/instance: airflow
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: airflow
    app.kubernetes.io/version: 2.10.4
    helm.sh/chart: airflow-22.4.7
data:
  airflow.cfg: |-
    [core]
    executor = KubernetesExecutor
    load_examples = False
    [kubernetes_executor]
    delete_worker_pods = True
    delete_worker_pods_on_failure = True
    namespace = my-namespace
    pod_template_file = /opt/bitnami/airflow/config/pod_template.yaml
    worker_container_repository = docker.io/bitnami/airflow
    worker_container_tag = 2.10.4-debian-12-r4
```

### Are you using any custom parameters or values?

`--set 'global.imageRegistry=docker.my-company.com' --set 'global.security.allowInsecureImages=true' --set 'executor=KubernetesExecutor'`

### What is the expected behavior?

I expect the `worker_container_repository` in `airflow.cfg` to be `docker.my-company.com/bitnami/airflow` since all other images in the deployment use `docker.my-company.com` as the registry.

### What do you see instead?

`worker_container_repository = docker.io/bitnami/airflow`

### Additional information

Its easy enough to get around this by setting `image.registry=docker.my-company.com` but it would be nice to not have to have this in two places
