### ISSUE TITLE
[bitnami/opensearch] OpenSearch snapshots Job fails when OpenSearch cluster uses TLS certificates.

### ISSUE THREAD

**Issue by tadeusz-delphai** [bitnami/charts#31710]
### Name and Version

bitnami/opensearch 1.5.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy the OpenSearch cluster with the security plugin enabled and with TLS certificates, and with the snapshots functionality enabled.
2. Observe the `opensearch-snapshots` Job. It stays in the `Failed` condition, with two lines of logs for each attempt:

```
curl: (52) Empty reply from server
curl: (52) Empty reply from server
```

### Are you using any custom parameters or values?

Security plugin configuration values:
```yaml
security:
  enabled: true
  existingSecret: exampleSecret  # that might be not important for a minimum repro?
  tls:
    enabled: true
    autoGenerated: true
    restEncryption: true
```

Snapshots values:
```yaml
snapshots:
  enabled: true
  persistence:
    enabled: true
    size: 1Ti
    accessModes:   # this is Azure AKS specific, adjust to whatever your k8s environment needs
      - "ReadWriteMany"
    storageClass: "azureblob-fuse-premium"
snapshotRepoPath: "/snapshots"
```

### What is the expected behavior?

The `opensearch-snapshots` Job can execute and eventually reach the `Succeeded` condition. The snapshot is written on the PVC storage.

### What do you see instead?

The `opensearch-snapshots` Job stays in the `Failed` condition, with two lines of logs for each retry attempt:

```
curl: (52) Empty reply from server
curl: (52) Empty reply from server
```

### Additional information

See https://github.com/bitnami/charts/blob/1b1c34a879fd2726ac21c3f2ceb111b15aab8cab/bitnami/opensearch/templates/snapshots/init-job.yaml#L40 and https://github.com/bitnami/charts/blob/1b1c34a879fd2726ac21c3f2ceb111b15aab8cab/bitnami/opensearch/templates/snapshots/init-job.yaml#L51 for `curl` commands that call OpenSearch API using hardcoded `http://` schema and ignore any TLS configuration on the OpenSearch cluster nodes that they try to contact.
