### ISSUE TITLE
[bitnami/external-dns] error during applying template on Azure DevOps

### ISSUE THREAD

**Issue by amonbts** [bitnami/charts#31791]
### Name and Version

bitnami/external-dns 8.7.3

### What architecture are you using?

None

### What steps will reproduce the bug?

1. I'm using Azure DevOps with a task: HelmDeploy@1 to deploy the bitnami/external-dns chart 
2. During the execution task I got an error that indicated that some of the objects were empty: 
`##[error]Capturing deployment metadata failed with error: TypeError: Cannot read properties of null (reading 'kind')`

### Are you using any custom parameters or values?

values.yaml
```yaml
crd:
  create: true
```

### What is the expected behavior?

Task should  finish with out error

### What do you see instead?

Error during execution helm
`##[error]Capturing deployment metadata failed with error: TypeError: Cannot read properties of null (reading 'kind')`

### Additional information

The problem is caused by crd file https://github.com/bitnami/charts/blob/external-dns/8.7.3/bitnami/external-dns/templates/crds/crd.yaml.

```yaml
# Source: https://raw.githubusercontent.com/kubernetes-sigs/external-dns/v{version}/docs/contributing/crd-source/crd-manifest.yaml
# Version: 0.15.1
# Conditional: .Values.crd.create
{{- if .Values.crd.create }}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
......
    storage: true
    subresources:
      status: {}
{{- end }}
```

Because of the construction of the file, it does not matter if `crd.create=true` or not we will always get an error because will will always get an empty object just with comments like below

```yaml
---
# Source: https://raw.githubusercontent.com/kubernetes-sigs/external-dns/v{version}/docs/contributing/crd-source/crd-manifest.yaml
# Version: 0.15.1
# Conditional: .Values.crd.create
---
```
And this in the end produce the aforementioned error

![Image](https://github.com/user-attachments/assets/391c4c38-cb6c-4d3e-9b18-d3c8dd460f92)
