### ISSUE TITLE
MongoDB Metrics Pod Fails

### ISSUE THREAD

**Issue by rrileyca** [bitnami/charts#31818]
### Name and Version

bitnami/mongodb 16.4.2

### What architecture are you using?

None

### What steps will reproduce the bug?

When upgrading from a replicaset deployment from version 16.3.0 to 16.4.2, we noticed the metrics pod throws a lot of errors and ultimately does not work when Prometheus scrapes it. Errors look like this line, one per db/collection (note `myDb` and `myCollection` change per line):
```
time="2025-02-06T20:54:38Z" level=error msg="cannot get $collstats cursor for collection myDb.myCollection: context deadline exceeded" collector=collstats
``` 

In another Pod we saw these errors. Note that `123.123.123.123` is our IP in kube.
```
time="2025-02-06T20:41:22Z" level=error msg="failed to run command: getCmdLineOptions: cannot execute getCmdLineOpts command: context deadline exceeded" collector=diagnostic_data
time="2025-02-06T20:49:52Z" level=error msg="Failed to get database names: cannot get the database names list: context deadline exceeded" collector=dbstats
time="2025-02-06T20:49:52Z" level=error msg="Failed to decode currentOp response: context deadline exceeded" collector=currentop
2025/02/06 20:49:52 http: panic serving 123.123.123.123:35416: descriptor %!s(PANIC=String method: runtime error: invalid memory address or nil pointer dereference) is invalid: context deadline exceeded
goroutine 38195 [running]:
net/http.(*conn).serve.func1()
        /opt/bitnami/go/src/net/http/server.go:1947 +0xbe
panic({0xdb00e0?, 0xc0055f6900?})
        /opt/bitnami/go/src/runtime/panic.go:785 +0x132
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(...)
        /bitnami/blacksmith-sandox/mongodb-exporter-0.43.1/pkg/mod/github.com/prometheus/client_golang@v1.20.5/prometheus/registry.go:406
github.com/percona/mongodb_exporter/exporter.(*Exporter).makeRegistry(0xc000475620, {0x1116c70, 0xc007d65f10}, 0xc0000ccb40, {0x1112c50, 0xc006f5f320}, {{0x17c74a0, 0x0, 0x0}, 0x0, ...})
        /bitnami/blacksmith-sandox/mongodb-exporter-0.43.1/src/github.com/percona/mongodb_exporter/exporter/exporter.go:222 +0x1085
github.com/percona/mongodb_exporter/exporter.RunWebServer.(*Exporter).Handler.func2({0x1115f50, 0xc00700c1c0}, 0xc00664b040)
        /bitnami/blacksmith-sandox/mongodb-exporter-0.43.1/src/github.com/percona/mongodb_exporter/exporter/exporter.go:352 +0x445
net/http.HandlerFunc.ServeHTTP(0x17a4d20?, {0x1115f50?, 0xc00700c1c0?}, 0x83d536?)
        /opt/bitnami/go/src/net/http/server.go:2220 +0x29
net/http.(*ServeMux).ServeHTTP(0x470439?, {0x1115f50, 0xc00700c1c0}, 0xc00664b040)
        /opt/bitnami/go/src/net/http/server.go:2747 +0x1ca
net/http.serverHandler.ServeHTTP({0xc007070b10?}, {0x1115f50?, 0xc00700c1c0?}, 0x6?)
        /opt/bitnami/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc007037c20, {0x1116bc8, 0xc000475950})
        /opt/bitnami/go/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 11
        /opt/bitnami/go/src/net/http/server.go:3360 +0x485
```

### Are you using any custom parameters or values?

Yes. In order to make metrics work with a Let's Encrypt TLS certificate, we had to do this:

```yaml
metrics:
      args:
        - /bin/mongodb_exporter --collect-all --compatible-mode --web.listen-address
          ":9216" --mongodb.uri "mongodb://$(echo $MONGODB_METRICS_USERNAME | sed -r
          's/@/%40/g;s/:/%3A/g'):$(echo $MONGODB_METRICS_PASSWORD | sed -r 's/@/%40/g;s/:/%3A/g')@localhost:27017/admin?tls=true&tlsCAFile=/certs/mongodb-ca-cert&tlsAllowInvalidCertificates=true&tlsAllowInvalidHostnames=true&tlsInsecure=true"
```

### What do you see instead?

The errors noted above
