### ISSUE TITLE
[bitnami/clickhouse] Latest clickhouse chart 8.0.0 using image 25.1.3-debian-12-r0 is broken

### ISSUE THREAD

**Issue by nkalev** [bitnami/charts#31837]
### Name and Version

bitnami/clickhouse

### What architecture are you using?

amd64

### What steps will reproduce the bug?

New install using helm chart version 8.0.0 and image 25.1.3-debian-12-r0 seems to be broken.
Clickhouse user in the system is created with UID 999 and GID 999, unfortunately the data is set / created to use GID 1001
Upgrading from older version results int he same situation and process is unable to start port probing always returns "Operation not permitted"

### Are you using any custom parameters or values?
```yaml
image:
  registry: docker.io
  repository: bitnami/clickhouse
  tag: 25.1.3-debian-12-r0
  pullPolicy: IfNotPresent
shards: 1 
replicaCount: 1
      
livenessProbe:
  enabled: true
  failureThreshold: 3
  initialDelaySeconds: 240
  periodSeconds: 60
  successThreshold: 1
  timeoutSeconds: 30
readinessProbe:
  enabled: true
  failureThreshold: 3
  initialDelaySeconds: 240
  periodSeconds: 60
  successThreshold: 1
  timeoutSeconds: 30

resources:
  requests:
    cpu: 2
    memory: 8Gi
  limits:
    cpu: 4
    memory: 16Gi

persistence:
  enabled: true
  storageClass: "gp3"
  accessModes:
    - ReadWriteOnce
  size: 200Gi
```

### What is the expected behavior?

the single clickhouse instance should be able to boot with clean new DB and be ready to accept connections.

### What do you see instead?

Clickhouse pod is going in CrashLoop cycle
