### ISSUE TITLE
[bitnami/kibana] Deployment issue during computing configmap.yaml

### ISSUE THREAD

**Issue by jaudiger** [bitnami/charts#31859]
### Name and Version

bitnami/kibana 11.4.4

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I'm updating the bitnami/kibana from 11.4.0 to 11.4.4. I also tested with 11.4.1, and the bug is already there. I can't deploy cabana by just setting an ingress with hostname to `localhost` and without TLS.

### Are you using any custom parameters or values?

```yaml
ingress:
  enabled: true
  hostname: localhost
```

### What is the expected behavior?

`server.publicBaseUrl` should be properly computed based on the current configuration.

### What do you see instead?

Error: template: kibana/templates/configmap.yaml:29:75: executing "kibana/templates/configmap.yaml" at <.Values.ingress.extraTls>: wrong type for value; expected bool; got []interface {}

### Additional information

It seems to have something to do with: https://github.com/bitnami/charts/commit/bfc5ecf0cb05d1831aec4d0e937f4c23c114933a

**Comment by jaudiger** [comment]
Has it been solved ? I mean, if the issue is closed automatically by the agent, should I re-open a new one ?

**Comment by fmulero** [comment]
Hi @jaudiger, Thanks for using bitnami/charts.

I am trying to reproduce your issue, and I am not having luck (I am facing different errors not related to yours probably due to my configuration). Could you share a simple scenario to reproduce it?

**Comment by jaudiger** [comment]
Sure. I'll share some part of my configuration:

```yml
elasticsearch:
  port: 9200
  hosts:
    - elasticsearch-master-0.alaska-elasticsearch-master-hl.default.svc.cluster.local
    - elasticsearch-master-1.alaska-elasticsearch-master-hl.default.svc.cluster.local
    - elasticsearch-master-2.alaska-elasticsearch-master-hl.default.svc.cluster.local

# Ingress parameters
ingress:
  enabled: true
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ip-address-type: dualstack
    alb.ingress.kubernetes.io/healthcheck-path: /status
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: ''
    alb.ingress.kubernetes.io/group.name: ''
    alb.ingress.kubernetes.io/auth-type: oidc
    alb.ingress.kubernetes.io/auth-idp-oidc: ''
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-scope: "email openid phone profile"
  path: /*
  hostname: localhost
  # Workaround for https://github.com/bitnami/charts/issues/31859
  tls: false
  extraTls: false
```

Without the workaround at the end of the configuration, I'm facing the error pointed in this issue.
