### ISSUE TITLE
Empty registry causes images to have a leading "/" before their name if other dependencies are present

### ISSUE THREAD

**Issue by o10s** [bitnami/charts#31856]
### Name and Version

bitnami/common 2.27.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hello! 

We have a situation currently going on at work that is a bit strange to me and I suspect a bug in the common chart.

Here is the situation:
We have a library chart that has common as a dependency, on top of that I defined a bunch of templates for deployments, ingresses, etc.
Since this is based on the common chart I can take advantage of common to infer image names in my deployment template file.

I do so like this:
```yaml
# _deployment.tpl
# shortened for readability
containers:
        - name: {{ .Chart.Name }}
          image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}  
```

In the export values, I set up my image with every parameter as "" (empty)
```yaml
# exported values (shortened)
global:
      imageRegistry: ""
image:
      ## @param image.registry Image registry
      ##
      registry: ""
      ## @param image.repository Image repository
      ##
      repository: ""
      ## @param image.tag Image tag (immutable tags are recommended)
      ##
      tag: latest
      ## @param image.digest Image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag
      ##
      digest: ""
```

Now I package this library in a custom helm chart so that our developers can simply use it as a dependency and have the least amount of work, so that they don't use directly the library making this new chart our common helm chart.

Now, because nodes are already connected to a default registry devs can simply use my common chart as a dependency and add their own custom values, without the need to add the registry, and only the repository.

Something like this:
```yaml
# dev-values
  image:
    repository: my-app
    tag: my-tag
```

Doing so results in a working template, and the user has as a final image name "my-app:my-tag".
Until here all works as expected.

Now though if the developer were to add another dependency in his chart.yaml for instance to add in a postgres DB, the resulting image of his deployment is now "/my-app:my-tag" do note the leading "/". This happens without any other changes to the dev helm only adding the dependency causes this, which makes me think that this particular template might be the culprit:

```yaml
# common _images.tpl
{{- if $registryName }}
    {{- printf "%s/%s%s%s" $registryName $repositoryName $separator $termination -}}
{{- else -}}
    {{- printf "%s%s%s"  $repositoryName $separator $termination -}}
{{- end -}}
```

Somehow even with the registry set to "" I end up in the if case and not in the else where I end up if I don't have other dependencies.
I also noted that this variable is defined as the following in the same file:
```yaml
# common _images.tpl
{{- $registryName := default .imageRoot.registry ((.global).imageRegistry) -}}
```

Could it be that if other dependencies do define a registry it somehow makes the value not empty? and therefore the if catches it?

Here are the steps to reproduce:

1. Create a library chart that uses common as a base
2. In this library create a deployment template that uses this for its image:
`image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}`
3. Export default values for registry as being "" (empty)
4. Create a chart that uses this library
5. Use this newly created chart as a dependency in another chart
6. In this newly created chart add in other dependencies (such as pgadmin or other)
7. For your values define only the repository but not the registry - leaving the registry empty
8. Do a helm template with your new chart
9. The resulting image will be /your-repo:TAG

Thank you for any feedback on this !

### What is the expected behavior?

The expected behavior is for my images to remain without a leading "/" if the registry is defined as "" 

### What do you see instead?

I do see that the registries are indeed with a leading "/" but only when there are multiple dependencies on top of my own
