### ISSUE TITLE
Allow to set S3 accesskey and secretkey from existing secret

### ISSUE THREAD

**Issue by hongbo-miao** [bitnami/charts#31861]
### Name and Version

bitnami/harbor 24.3.0

### What is the problem this feature will solve?

Bases on https://github.com/bitnami/charts/blob/main/bitnami/harbor/values.yaml#L452-L453

For these two fields
```
persistence.imageChartStorage.s3.accesskey
persistence.imageChartStorage.s3.secretkey
```

We have to provide in plain text?
How to provide from an existing secret? Thanks!

### What is the feature you are proposing to solve the problem?

Something like would be great! ☺️

```yaml
existingSecret: "my-harbor-secret"
accessKeyExistingSecret: "s3-access-key"
secretKeyExistingSecret: "s3-secret-key" 
```
