### ISSUE TITLE
[bitnami/rabbitmq] Streams/Superstreams support

### ISSUE THREAD

**Issue by metron2** [bitnami/charts#31868]
### Name and Version

bitnami/rabbitmq 15.3.0

### What is the problem this feature will solve?

What is a Stream
RabbitMQ Streams is a persistent replicated data structure that can complete the same tasks as queues: they buffer messages from producers that are read by consumers. However, streams differ from queues in two important ways: how messages are stored and consumed.

Streams model an append-only log of messages that can be repeatedly read until they expire. Streams are always persistent and replicated. A more technical description of this stream behavior is “non-destructive consumer semantics”.

To read messages from a stream in RabbitMQ, one or more consumers subscribe to it and read the same messages as many times as they want.

### What is the feature you are proposing to solve the problem?

The implementation is kind of annoying. Streams clients connect over amqp but then directly connect to each node.

By default the streams_plugin uses port 5552.

Each node should set `stream.advertised_host` to the fqdn of the pod or maybe LB (especially if exposed externally). There's more details here. https://www.rabbitmq.com/docs/stream

Container Ports, host ports and network policy will have to be updated to allow 5552. Probably the advertised_host and advertised_host_tls will need a new values map.

**Comment by metron2** [comment]
We did get TLS working but I still think it's worth integrating this. 

```
extraConfiguration:
      stream.listeners.ssl.1 = 5551
      stream.advertised_host = rabbitmq-amqp-$(STATEFULSET_ORDINAL_NUMBER).<fqdn>
extraEnvVars:
   - name: STATEFULSET_ORDINAL_NUMBER
     valueFrom:
        fieldRef:
          fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
    networkPolicy:
extraIngress:
    - ports:
        - port: 5551
        - port: 5552
        - port: 6000
          endPort: 6500
```

This lets you use TLS with streams as long as you have per node load balancers to expose the cluster. We made the load balancers manually but it just has the pod name in the selector.

```
  selector:
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/name: rabbitmq
    statefulset.kubernetes.io/pod-name: rabbitmq-0
```

Hopefully this helps someone.
