### ISSUE TITLE
[bitnami/elasticsearch] renewed TLS certificates no longer auto-reloading

### ISSUE THREAD

**Issue by ianroberts** [bitnami/charts#31872]
### Name and Version

bitnami/elasticsearch 21.4.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create a TLS certificate and store it in a secret
2. Install the elasticsearch chart with `security.tls.master.existingSecret` pointing at this secret
3. Renew (or otherwise replace) the certificate in the secret

I use `cert-manager` (in my case with Hashcorp Vault as the underlying certificate issuer), which automatically renews certificates when they are close to expiry.

### What is the expected behavior?

Elasticsearch should pick up the updated certificate automatically and start using it for future connections.

### What do you see instead?

Elasticsearch continues to use the old pre-renewal certificate until the pods are re-created.

### Additional information

Elasticsearch watches its TLS key and certificate files and automatically reloads them when it detects that they have been modified.

The problem was introduced in PR #27491.  Prior to this elasticsearch was pointed directly at the certificate files in the volume corresponding to the mounted secret, so when the secret is modified the files in this volume change, Elasticsearch detects the change and reloads the certificates.  But the above PR introduced an init container that copies the certificate files to a separate `emptyDir` volume, and it is _that_ volume that is now mounted into the main container, not the original secret.  This effectively takes a "snapshot" of the certificate files as they were at the time the pod was created, and subsequent updates to the certificate are ignored.

If I manually update the `tls crt` file inside each elasticsearch pod with `kubectl exec`, the process _does_ detect the new certificate and start using it immediately, no restart is required.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by ianroberts** [comment]
Still relevant - fix for the associated containers issue is under final review, once that is released I will update the image tag in the PR for this issue and it will be ready to merge.

**Comment by ianroberts** [comment]
Still relevant, but the PR is still blocked waiting for the underlying fix in containers.

**Comment by ianroberts** [comment]
My current workaround is to declare an additional [sidecar container](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/) (i.e. an _init_ container with `restartPolicy: Always`) that atomically re-copies the cert from the secret volume into the emptyDir volume every 24 hours:

```yaml
initContainers:
- name: watch-certificates
  image: docker.io/bitnami/os-shell:12-debian-12-r34
  restartPolicy: Always
  command:
  - /bin/sh
  - -c
  - |
    while true ; do
      # Every 24 hours...
      sleep 86400
      # atomically replace the current tls.crt in the emptydir with the one
      # from the secret - this assumes that the tls.key and ca.crt do not
      # change when the certificate is renewed, which is the case in my
      # setup (cert-manager issuing a certificate from Hashicorp Vault)
      # but may not be a valid assumption in all cases
      cat /certs/tls.crt > /tmp/tls.crt.tmp
      mv /tmp/tls.crt.tmp /tmp/tls.crt
    done
  volumeMounts:
    - name: elasticsearch-certificates
      mountPath: /certs
    - name: empty-dir
      mountPath: /tmp
      subPath: certs
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    privileged: false
    readOnlyRootFilesystem: true
    runAsGroup: 1001
    runAsNonRoot: true
    runAsUser: 1001
    seLinuxOptions: {}
    seccompProfile:
      type: RuntimeDefault
  resources:
    limits:
      cpu: 150m
      ephemeral-storage: 2Gi
      memory: 192Mi
    requests:
      cpu: 100m
      ephemeral-storage: 50Mi
      memory: 128Mi
```
