### ISSUE TITLE
[bitnami/redmine] Pod crashes after installing RedmineUp Agile plugin

### ISSUE THREAD

**Issue by stefano-vardanega** [bitnami/charts#31931]
### Name and Version

bitnami/redmine32.1.4

### What architecture are you using?

None

### What steps will reproduce the bug?

I got a perfectly working redmine helm chart with TLS and let's encrypt certs and public dns name.
I got a nginx ingress with a load balancer, and everything in place.

To reproduce the problem start from scartch: 

`helm install redmine19 -f redmine-values-test19.yaml oci://registry-1.docker.io/bitnamicharts/redmine`

Copy the unzipped plugin folder to the pod plugins PVC volume mount:

`gas@PC19:/mnt/d/src/acsw03/git/redmine$ k cp redmine_agile redmine19-745d648947-rw78d:/bitnami/redmine/plugins`

Enter the pod:

```bash
#inside the pod bash
root@redmine19-745d648947-rw78d:/# cd /opt/bitnami/redmine/
root@redmine19-745d648947-rw78d:/opt/bitnami/redmine# bundle config set frozen false
root@redmine19-745d648947-rw78d:/opt/bitnami/redmine# bundle install
#Don't run Bundler as root. Installing your bundle as root will break this application for all non-root users on this machine.
#Fetching gem metadata from https://rubygems.org/.........
#...other outputs....
#Bundled gems are installed into `./vendor/bundle`

root@redmine19-745d648947-rw78d:/opt/bitnami/redmine# bundle exec rake redmine:plugins NAME=redmine_agile RAILS_ENV=production
#== 1 CreateIssueStatusOrders: migrating =======================================
#-- create_table(:issue_status_orders, {:options=>"ENGINE=InnoDB", :id=>:integer})
#...other migration logs....
#== 8 AddSharingToAgileSprint: migrated (0.0167s) ==============================
```
The migration went fine, so I restart the redmine service and get the plugin working!
```bash
root@redmine19-745d648947-rw78d:/opt/bitnami/redmine# bundle exec passenger-config restart-app /opt/bitnami/redmine
#Restarting /opt/bitnami/redmine (production)
root@redmine19-745d648947-rw78d:/opt/bitnami/redmine#
```

![Image](https://github.com/user-attachments/assets/8484345c-0f23-4ac5-bdd9-9b86ec5a9638)

![Image](https://github.com/user-attachments/assets/41080f44-a656-4f30-993a-f6874adae5f6)

Simulate a pod reboot:

```bash
gas@PC19:/mnt/d/src/acsw03/git/redmine$ k scale --replicas=0 deployment redmine19
#deployment.apps/redmine19 scaled
#gas@PC19:/mnt/d/src/acsw03/git/redmine$ k get po
#NAME                  READY   STATUS    RESTARTS   AGE
#redmine19-mariadb-0   1/1     Running   0          14m

#restart the pod
gas@PC19:/mnt/d/src/acsw03/git/redmine$ k scale --replicas=1 deployment redmine19
#deployment.apps/redmine19 scaled
#gas@PC19:/mnt/d/src/acsw03/git/redmine$ k get po -w
#NAME                         READY   STATUS              RESTARTS   AGE
#redmine19-745d648947-ftsfk   0/1     ContainerCreating   0          3s
#redmine19-mariadb-0          1/1     Running             0          14m
#redmine19-745d648947-ftsfk   0/1     Running             0          12s
#redmine19-745d648947-ftsfk   0/1     Error               0          13s
#redmine19-745d648947-ftsfk   0/1     CrashLoopBackOff    1 (2s ago)   16s
```

From now on the pod never restarts. The logs stops at databse migration phase:

```
gas@PC19:/mnt/d/src/acsw03/git/redmine$ k logs -f redmine19-745d648947-ftsfk
redmine 13:48:19.34 INFO  ==>
redmine 13:48:19.34 INFO  ==> Welcome to the Bitnami redmine container
redmine 13:48:19.34 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
redmine 13:48:19.34 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
redmine 13:48:19.35 INFO  ==>
redmine 13:48:19.36 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
redmine 13:48:19.37 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
redmine 13:48:19.44 INFO  ==> Restoring persisted Redmine installation
redmine 13:48:19.52 INFO  ==> Trying to connect to the database server
redmine 13:48:19.63 INFO  ==> Executing database migrations
gas@PC19:/mnt/d/src/acsw03/git/redmine$
```

The pod k8s logs says:
```
Warning  BackOff                 1s (x80 over 15m)  kubelet                  Back-off restarting failed container redmine19 in pod redmine19-745d648947-ftsfk_default(2b481eca-cc05-4b97-bf82-6c45018f2ea2)
```

Removing the `/bitnami/redmine/plugins/redmine_agile` folder, the pod starts successfully.

### Are you using any custom parameters or values?
```
global:
  imagePullSecrets:
    - dockerhub-image-pull-secret

redmineUsername: pippo
redminePassword: pippopippo
redmineEmail: pippo@pippo.it
smtpHost: smtp.gmail.com
smtpPort: 587
smtpUser: pippo@pippo.it
smtpPassword: pippopippo

replicaCount: 1
containerPorts:
  http: 3000
resources:
  requests:
    cpu: 2
    memory: 3Gi
  limits:
    cpu: 3
    memory: 4Gi


service:
  type: ClusterIP
  ports:
    http: 3000
    
persistence:
  enabled: true
  size: 16Gi

databaseType: mariadb
mariadb:
  enabled: true
  auth:
    rootPassword: pippoppippo
    username: pippo
    password: "pippo"
  architecture: standalone
  primary:
    persistence:
      enabled: true
      size: 15Gi

postgresql:
  enabled: false

ingress:
  enabled: true
  certManager: true
  ingressClassName: "nginx"
  hostname: redmine.pippo.it
  path: /
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
  tls: true
```

### What do you see instead?
```
Warning  BackOff                 1s (x80 over 15m)  kubelet                  Back-off restarting failed container redmine19 in pod redmine19-745d648947-ftsfk_default(2b481eca-cc05-4b97-bf82-6c45018f2ea2)
```
The pod don't start anymore.
