### ISSUE TITLE
[bitnami/logstash] NetworkPolicy.networking.k8s.io "logstash" is invalid: [spec.ingress[0].ports[1].port: Invalid value

### ISSUE THREAD

**Issue by Yitter96** [bitnami/charts#31939]
### Name and Version

bitnami/logstash 6.4.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy the Logstash Helm chart with the following custom values:
```yaml
networkPolicy:
  enabled: true
extraContainerPorts:
  - name: beats
    containerPort: 5044
    protocol: TCP
```
2. Apply the Helm chart and observe the NetworkPolicy resource creation.

### What is the expected behavior?

The `NetworkPolicy` ingress ports should be correctly configured with the specified `containerPort` and protocol from the `extraContainerPorts` list. For example:
```yaml
  ingress:
    - ports:
        - port: 8080
          protocol: TCP
        - port: 5044
          protocol: TCP
        - port: 9600
```

### What do you see instead?

Instead, the `NetworkPolicy` ingress ports are incorrectly configured, and the entire array is being passed as the port value. This results in an error similar to:
```yaml
  ingress:
    - ports:
        - port: 8080
          protocol: TCP
        - port: map[containerPort:5044 name:beats protocol:TCP]
          protocol: TCP
        - port: 9600
```

### Additional information

The issue appears to be in the Helm chart template where the `extraContainerPorts` are being processed. The template incorrectly references the entire array instead of the `containerPort` field:
```yaml
{{- range .Values.extraContainerPorts }}
- port: {{ . }}
  protocol: {{ default "TCP" .protocol }}
{{- end }}
```
Instead, it should be:
```yaml
{{- range .Values.extraContainerPorts }}
- port: {{ .containerPort }}
  protocol: {{ default "TCP" .protocol }}
{{- end }}
```
This bug prevents the `NetworkPolicy` from being correctly applied when `extraContainerPorts` are used.
[Problem source line](https://github.com/bitnami/charts/blob/logstash/6.4.4/bitnami/logstash/templates/networkpolicy.yaml#L62)
