### ISSUE TITLE
bitnami/elasticsearch missing new line in kibana configmap

### ISSUE THREAD

**Issue by DeprecatedLuke** [bitnami/charts#31962]
### Name and Version

bitnami/elasticsearch 21.4.5

### What architecture are you using?

None

### What steps will reproduce the bug?

Not relevant.

### Are you using any custom parameters or values?
```yaml
global:
  kibanaEnabled: true

elasticsearch:
  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0
  security:
    enabled: true
    tls:
      restEncryption: false
      autoGenerated: true

  kibana:
    updateStrategy:
      type: Recreate
    elasticsearch:
      security:
        auth:
          enabled: true
        tls:
          enabled: false
          existingSecret: analytics-elasticsearch-master-crt
          usePemCerts: true
```

### What is the expected behavior?

```
pid.file: /opt/bitnami/kibana/tmp/kibana.pid
server.host: "0.0.0.0"
server.port: 5601
elasticsearch.hosts: [http://analytics-elasticsearch:9200]
server.publicBaseUrl: https://host.minidev.app
server.rewriteBasePath: false
```

### What do you see instead?

```
pid.file: /opt/bitnami/kibana/tmp/kibana.pid
server.host: "0.0.0.0"
server.port: 5601
elasticsearch.hosts: [http://analytics-elasticsearch:9200]server.publicBaseUrl: https://iconic-analytics.minidev.app
server.rewriteBasePath: false
```

### Additional information

Missing new line in analytics-kibana-conf configmap configuration.

**Comment by gongomgra** [comment]
Hi @DeprecatedLuke,

Thanks for reporting this issue. There is a related PR to fix this

https://github.com/bitnami/charts/pull/30807

**Comment by jaudiger** [comment]
With the PR merged, I'm now getting:

```bash
Error: template: kibana/templates/configmap.yaml:31:58: executing "kibana/templates/configmap.yaml" at <include>: wrong number of args for include: want 2 got 4
```

**Comment by gongomgra** [comment]
Hi @jaudiger,

Thanks for your message. Can you provide us with your custom values.yaml so we can try to reproduce your issue? I have not been able to reproduce it with our default runtime parameters:

```
$ helm template -n kibana kibana -f .vib/kibana/runtime-parameters.yaml bitnami/kibana
```

I have also checked updated chart has been correctly deployed in our testing environment after the merge

![Image](https://github.com/user-attachments/assets/25a34151-cef9-4173-a227-625ddd4c2e82)

**Comment by jaudiger** [comment]
Hi @gongomgra, sure, here is the values I used on my side for Kibana:

```yml
elasticsearch:
  port: 9200
  hosts:
    - elasticsearch-master-0.alaska-elasticsearch-master-hl.default.svc.cluster.local
    - elasticsearch-master-1.alaska-elasticsearch-master-hl.default.svc.cluster.local

initScriptsCM: "init"

# Ingress parameters
ingress:
  enabled: true
  ingressClassName: alb
  hostname: localhost
  path: /*
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ip-address-type: dualstack
    alb.ingress.kubernetes.io/healthcheck-path: /status
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/group.name: ''
    alb.ingress.kubernetes.io/auth-type: oidc
    alb.ingress.kubernetes.io/auth-scope: "email openid profile"
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-idp-oidc: ''
  # Workaround for https://github.com/bitnami/charts/issues/31859
  tls: false
  extraTls: false
```

I tested a few minutes ago with the chart version "11.5.0", and I'm still having this issue.
