### ISSUE TITLE
grafana-operator importing grafanaCom dashboards breaks templating

### ISSUE THREAD

**Issue by mobidyc** [bitnami/charts#31961]
### Name and Version

bitnamicharts/grafana-operator 4.9.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy the grafana-operator charts.

2. Deploy a GrafanaDatasource

```yaml
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
  namespace: default
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/instance: grafana-operator
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana-operator
  datasource:
    name: prometheus
    type: prometheus
    access: proxy
    url: http://kube-prometheus-prometheus:9090
    isDefault: true
    jsonData:
      'tlsSkipVerify': true
      'timeInterval': "5s"
```

3. import a dashboard - I tried with or without `datasources` and a mix of different values with same result:

```yaml
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: grafana-dashboard-redis-11835
  namespace: default
  labels:
    app: grafana
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/instance: grafana-operator
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana-operator
  # https://grafana.com/grafana/dashboards/13502-minio-dashboard/
  grafanaCom:
    id: 13502
    revision: 26
  datasources:
    - datasourceName: prometheus
      inputName: prometheus
```

### Are you using any custom parameters or values?

Should not impact the result, but the values.yaml customization are:

```yaml
operator:
  enabled: true
  prometheus:
    serviceMonitor:
      enabled: true

grafana:
  enabled: true
  config:
    server:
      root_url: "http://grafana-operator-grafana-service:3000/grafana"
      serve_from_sub_path: "true"
```

### What is the expected behavior?

I expect the templating variables to be working

### What do you see instead?

The data source is lost in the the templating variables
