### ISSUE TITLE
[Bitnami/Airflow] Web baseUrl not working with path based routing

### ISSUE THREAD

**Issue by mxmdt3** [bitnami/charts#31985]
### Name and Version

bitnami/airflow 22.4.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`AIRFLOW_BASE_URL` has been deprecated in favor of `web.baseUrl` but it does not work with a path.
The ingress can be used to route a path to the web server but the baseUrl is not added properly to `AIRFLOW__WEBSERVER__BASE_URL` or its equivalent configuration.

### Are you using any custom parameters or values?
```yaml
ingress:
    enabled: true
    path: /airflow
web:
  baseUrl: http://0.0.0.0:8080/airflow
```
### What is the expected behavior?

I would expect this URL to be served
http://my-server/airflow
Could you fix `web.baseUrl` to be able to deal with path based routing?

### What do you see instead?

404

### Additional information

The workaround I came up with is the following:
```yaml
 web:
    extraEnvVars:
    - name: AIRFLOW__WEBSERVER__BASE_URL
      value: http://0.0.0.0:8080/airflow
    customReadinessProbe:
      httpGet:
        path: /airflow/health
        port: http
```
