### ISSUE TITLE
[bitnami/mongodb] helm upgrade failing

### ISSUE THREAD

**Issue by StickNitro** [bitnami/charts#3201]
**Which chart**:
The name (and version) of the affected chart

bitnami/mogodb:latest

**Describe the bug**

Running through a Azure DevOps pipeline we are getting a failure when running an upgrade, the yaml is:

```
                - task: HelmDeploy@0
                  inputs:
                    connectionType: "Azure Resource Manager"
                    azureSubscription: "apdasa-azure"
                    azureResourceGroup: "asa"
                    kubernetesCluster: "asa"
                    namespace: "ci"
                    command: upgrade
                    chartType: "Name"
                    chartName: "bitnami/mongodb"
                    releaseName: "asa-users-mongo"
                    overrideValues: "mongodbUsername=*****,mongodbPassword=*****,mongodbDatabase=usersdb"
```

And the error we are getting is:

```
Error: UPGRADE FAILED: cannot patch "asa-users-mongo-mongodb" with kind Deployment: Deployment.apps "asa-users-mongo-mongodb" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"mongodb", "app.kubernetes.io/instance":"asa-users-mongo", "app.kubernetes.io/name":"mongodb"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

The command being run in devops is:

```
/opt/hostedtoolcache/helm/3.2.4/x64/linux-amd64/helm upgrade --namespace ci --install --set mongodbUsername=*****,mongodbPassword=*****,mongodbDatabase=usersdb --wait asa-users-mongo bitnami/mongodb
```
This is part of a pipeline that installs helm and adds the bitnami/mongodb repo.

**Expected behavior**

Expect mongodb to be installed in the namespace specified

**Version of Helm and Kubernetes**:
Helm: 3.2.4
Kubectl: 1.18.6

**Additional context**

Command used to add repo:

```
helm repo --namespace ci add bitnami https://charts.bitnami.com/bitnami
```
