### ISSUE TITLE
[bitnami/wordpress] Duplicate records in external db

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [bitnami/charts#3205]
**Which chart**:
wordpress:9.3.22

**Describe the bug**
When I deploy the chart connecting to an external Azure MariaDB database, my fields are duplicated
![image](https://user-images.githubusercontent.com/13748882/88298166-71ca0780-cd1e-11ea-945a-79a745559359.png)

**To Reproduce**
1. Install the chart
2. Check the DB for duplicate records

**Expected behavior**
No matter how many replicas I have or how many times I redeploy, records shouldn't be duplicated.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"2b13e288f94dd2577d4ff7261f9eb76b1d5692a1", GitTreeState:"clean", BuildDate:"2020-06-01T21:55:34Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I am running with 3 replica sets and I see this issue around 80% of the times.

**Comment by carrodher** [comment]
Hi, to try to reproduce the issue on our side, can you share with us the `helm install` command used to deploy the chart with the external database?

**Comment by SayakMukhopadhyay** [comment]
`helm install wordpress-blog bitnami/wordpress -f ./wp-helm-values.yaml --namespace wordpress-blog`
The `wp-helm-values` looks like
```
fullnameOverride: wordpress-blog
allowEmptyPassword: false
allowOverrideNone: true
replicaCount: 3
service:
  type: ClusterIP
  externalTrafficPolicy: Local
mariadb:
  enabled: false
persistence:
  accessMode: ReadWriteMany
  storageClass: files
extraVolumes:
  - name: db-ca-cert
    secret:
      secretName: ca-cert
      items:
        - key: certificate
          path: db-certificate.crt.pem
extraVolumeMounts:
  - name: db-ca-cert
    mountPath: /etc/ssl/certs
extraEnv:
  - name: WORDPRESS_DATABASE_SSL_CA_FILE
    value: /etc/ssl/certs/db-certificate.crt.pem
wordpressUsername: admin
wordpressPassword: redacted
wordpressEmail: redacted
wordpressFirstName: Admin
wordpressLastName: User
wordpressBlogName: MYBlog
externalDatabase:
  host: redacted.mariadb.database.azure.com
  user: redacted
  password: "redacted"
  database: wp_myblog
```
