### ISSUE TITLE
Custom Helm Chart for Bitnami Redis to Support Redis Stack Server (Sentinel Example)

### ISSUE THREAD

**Issue by samuelexferri** [bitnami/charts#32073]
### Name and Version

bitnami/redis 20.7.1

### What is the problem this feature will solve?

It would be great if Bitnami provided direct configuration support for Redis Stack Server within their official Helm chart.

### What is the feature you are proposing to solve the problem?

I want to share how I successfully created a custom Helm chart based on Bitnami Redis to support Redis Stack Server and its modules, including RediSearch, RedisJSON, RedisTimeSeries, RedisBloom, and RedisGraph.

This guide explains the steps taken to modify Bitnami's Redis Helm chart, allowing it to run Redis Stack Server while preserving support for Sentinel mode and other configurations.

**1. Setting Up a Helm Repository**
To distribute the custom chart, I created a Helm repository using a GitHub repository and GitHub Pages. This approach allows easy versioning and distribution of Helm charts.

**2. Cloning and Modifying the Bitnami Redis Chart**
I started by copying the existing Bitnami `charts/redis` directory and modifying it to support Redis Stack Server. Here are the key changes:

- Updated the `Chart.yaml` file:

  - Modified the versioning scheme by appending `-MYVERSION1` to differentiate from the original Bitnami chart.
- Modified the Redis startup command in `charts/redis/templates/scripts-configmap.yaml`:

  - Replaced `redis-server` with `redis-stack-server` command, ensuring that the Redis Stack Server binary is executed instead of the standard Redis binary.

  - Important: The Sentinel startup command should remain unchanged to avoid breaking Sentinel functionality:

    `exec redis-server /opt/bitnami/redis-sentinel/etc/sentinel.conf {{- if .Values.tls.enabled }} "${ARGS[@]}" {{- end }} --sentinel`

**3. Installing Redis Stack Server Using Helm**
After modifying the Helm chart, I deployed it using helm install with a custom values file (`redis-stack-server-bitnami-values.yaml`). Below is an example configuration that enables Redis Sentinel mode and ensures that Redis Stack Server is correctly deployed:

```yaml
global:
  security:
    allowInsecureImages: true

image:
  repository: redis/redis-stack-server
  tag: 7.4.0-v3

auth:
  enabled: true
  sentinel: true
  password: <REDIS-STACK-SERVER-PASSWORD>
  acl:
    enabled: false
    users: []

replica:
  replicaCount: 3
  extraFlags:
    - '--protected-mode no'
  resources:
    requests:
      cpu: '250m'
      memory: '512Mi'
    limits:
      cpu: '1'
      memory: '4Gi'
  podAffinityPreset: ''
  podAntiAffinityPreset: 'soft'
  persistence:
    enabled: true
    size: 50Gi
    storageClass: do-block-storage
  automountServiceAccountToken: true

sentinel:
  enabled: true
  masterSet: 'mymaster'
  quorum: 2
  masterService:
    enabled: true
    type: ClusterIP

rbac:
  create: true

serviceAccount:
  create: true
  name: 'redis-stack-server-service-account'
  automountServiceAccountToken: true
```

**4. Deploying the Custom Helm Chart**
To deploy the Redis Stack Server with the customized Helm chart, I ran the following command:

```
helm upgrade -i redis-stack-server redis \
  --atomic \
  --repo https://<YOUR-HELM-REPO>.github.io/helm-charts \
  --version 20.7.1-MYVERSION1 \
  --namespace redis \
  --values k8s/redis-stack-server-bitnami-values.yaml
```

**Conclusion**
It would be great if Bitnami provided direct configuration support for Redis Stack Server within their official Helm chart. This would allow users to enable Redis Stack Server and its modules through Helm values rather than requiring manual modifications.

In a similar way, I believe it will also be possible to extend support for Redis Cluster mode within the modified Bitnami Helm chart. 

I hope this guide helps others looking to run Redis Stack Server with Bitnami’s Helm chart. Feel free to contribute, provide feedback, or suggest improvements!
