### ISSUE TITLE
MongoDB configmap not updating

### ISSUE THREAD

**Issue by kwill4026** [bitnami/charts#3213]
**Which chart**:
bitnami/mongodb
```
name: mongodb
version: 8.2.1
appVersion: 4.2.8
```

**Describe the bug**
I noticed when I perform a helm install using the default bitnami/mongodb chart (with no values changed), then proceed with a helm upgrade of that same deployment but with the **configuration:** details not commented, it will upgrade and install fine. I can see a configmap was created and bashing into the pods I can see the mongod conf settings were consumed. However if I decide to first pull down the bitnami/mongdb chart, comment out those parameters in the **configuration:** and helm install, the pod will NOT load. Why is this? 

**To Reproduce**
1. Pull down the bitnami/mongodb chart, CD to the directory and install with **helm install my-mongo -f values-production.yaml .**
2. The pods should create fine with no problems. To avoid long waiting times I set my replica count to 2. 
```
NAME                     READY   STATUS    RESTARTS   AGE
pod/my-mongo-mongodb-0   1/1     Running   0          2m57s
pod/my-mongo-mongodb-1   1/1     Running   0          2m3s

NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
service/kubernetes                  ClusterIP   172.20.0.1       <none>        443/TCP     290d
service/my-mongo-mongodb-headless   ClusterIP   None             <none>        27017/TCP   2m57s
service/my-mongo-mongodb-metrics    ClusterIP   172.20.113.121   <none>        9216/TCP    2m57s

NAME                                READY   AGE
statefulset.apps/my-mongo-mongodb   2/2     2m57s
```
3. Now go back into the **values.production.yaml** file and comment out the parameters in the **configuration** section. Make sure to comment **configuration: ""** so the chart can instead take the other parameters you just commented out. Just to ensure this conf parameters will take and update into the current chart. I will go ahead and comment **bindIpAll:true** and instead add **bindIp:0.0.0.0**
```
configuration: |
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    ##bindIpAll: true
    bindIp:0.0.0.0
  replication:
     replSetName: rs0
     enableMajorityReadConcern: true
  processManagement:
    fork: false
    pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
  setParameter:
    enableLocalhostAuthBypass: true
  security:
    authorization: enabled
    keyFile: /opt/bitnami/mongodb/conf/keyfile

#configuration: ""
```
4. Now upgrade the deployment named **my-mongo** with the config changes just made. **helm upgrade my-mongo -f values-production.yaml. The pods run as expected, it creates the configmap my-mongo-mongodb with the updated values. and when I bash into the container, go to the mongodb.conf I can see it. Perfect. 

```
helm ls
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART        	APP VERSION
my-mongo	default  	2       	2020-07-24 08:22:36.384294652 -0400 EDT	deployed	mongodb-8.2.0	4.2.8   

kubectl get all
NAME                     READY   STATUS    RESTARTS   AGE
pod/my-mongo-mongodb-0   1/1     Running   0          8m6s
pod/my-mongo-mongodb-1   1/1     Running   0          8m37s

NAME                                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
service/kubernetes                  ClusterIP   172.20.0.1      <none>        443/TCP     290d
service/my-mongo-mongodb-headless   ClusterIP   None            <none>        27017/TCP   17m
service/my-mongo-mongodb-metrics    ClusterIP   172.20.195.83   <none>        9216/TCP    17m

NAME                                READY   AGE
statefulset.apps/my-mongo-mongodb   2/2     17m
```
```
kubectl get cm
NAME                            DATA   AGE
my-mongo-mongodb                1      50s
my-mongo-mongodb-init-scripts   1      9m44s
my-mongo-mongodb-scripts        1      9m44s
```
```
I have no name!@my-mongo-mongodb-0:/opt/bitnami/mongodb/conf$ ls
keyfile  mongodb.conf
I have no name!@my-mongo-mongodb-0:/opt/bitnami/mongodb/conf$ cat mongodb.conf 
storage:
  dbPath: /bitnami/mongodb/data/db
  journal:
    enabled: true
  directoryPerDB: false
systemLog:
  destination: file
  quiet: false
  logAppend: true
  logRotate: reopen
  path: /opt/bitnami/mongodb/logs/mongodb.log
  verbosity: 0
net:
  port: 27017
  unixDomainSocket:
    enabled: true
    pathPrefix: /opt/bitnami/mongodb/tmp
  ipv6: false
  #bindIpAll: true
  bindIp: 0.0.0.0
replication:
  replSetName: rs0
  enableMajorityReadConcern: true
processManagement:
  fork: false
  pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
setParameter:
  enableLocalhostAuthBypass: true
security:
  authorization: enabled
  keyFile: /opt/bitnami/mongodb/conf/keyfile
```
5. Now if I delete the entire deployment and instead of installing the default chart, I decide to immediately installed the chart WITH the  parameters from the **configuration:** section of the values-production.yaml file commented out, the pods crash and never load. 
See below. 
```
kubectl get all
NAME                     READY   STATUS             RESTARTS   AGE
pod/my-mongo-mongodb-0   0/1     CrashLoopBackOff   1          39s

NAME                                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
service/kubernetes                  ClusterIP   172.20.0.1      <none>        443/TCP     290d
service/my-mongo-mongodb-headless   ClusterIP   None            <none>        27017/TCP   39s
service/my-mongo-mongodb-metrics    ClusterIP   172.20.198.65   <none>        9216/TCP    39s

NAME                                READY   AGE
statefulset.apps/my-mongo-mongodb   0/2     39s

kubectl logs pod/my-mongo-mongodb-0
Advertised Hostname: my-mongo-mongodb-0.my-mongo-mongodb-headless.default.svc.cluster.local
Pod name matches initial primary pod name, configuring node as a primary
mongodb 12:41:30.94 
mongodb 12:41:30.94 Welcome to the Bitnami mongodb container
mongodb 12:41:30.94 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 12:41:30.94 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 12:41:30.95 
mongodb 12:41:30.95 INFO  ==> ** Starting MongoDB setup **
mongodb 12:41:30.96 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 12:41:30.97 INFO  ==> Initializing MongoDB...
mongodb 12:41:30.98 DEBUG ==> /mongodb.conf mounted. Skipping setting port and IPv6 settings
mongodb 12:41:30.98 DEBUG ==> /mongodb.conf mounted. Skipping setting log settings
mongodb 12:41:30.98 DEBUG ==> /mongodb.conf mounted. Skipping setting storage settings
mongodb 12:41:30.98 INFO  ==> Deploying MongoDB from scratch...
mongodb 12:41:30.98 DEBUG ==> Starting MongoDB in background...
about to fork child process, waiting until server is ready for connections.
forked process: 35
ERROR: child process failed, exited with error number 1
To see additional information in this output, start without the "--fork" option.
```

**Expected behavior**
I assumed I could comment out the configuration section in the values-production.yaml file and helm install right away, without having to first install the default chart first, then upgrading with the parameters I specified.

**Version of Helm and Kubernetes**:
```
helm version:
version.BuildInfo{Version:"v3.2.2", GitCommit:"a6ea66349ae3015618da4f547677a14b9ecc09b3", GitTreeState:"clean", GoVersion:"go1.13.12"}

kubectl version:
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-22T06:44:59Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by kwill4026** [comment]
I also just noticed when I comment out all the configuation parameters but only comment **#keyFile: /opt/bitnami/mongodb/conf/keyfile** and peform a helm install, it causes the pods to run but each have a restart of 1 associated with it. The logs will of course complain about "not authorized". 
```
 kubectl get all
NAME                     READY   STATUS    RESTARTS   AGE
pod/my-mongo-mongodb-0   1/1     Running   1          12m
pod/my-mongo-mongodb-1   1/1     Running   1          11m
```
```
kubectl logs pod/my-mongo-mongodb-0
2020-07-24T13:09:18.340+0000 I  ACCESS   [conn107] Unauthorized: not authorized on admin to execute command { endSessions: [ { id: UUID("2aa9a1ad-e60e-4766-84b9-4a080df17d8d") } ], $db: "admin" }
2020-07-24T13:09:18.340+0000 I  NETWORK  [conn107] end connection 127.0.0.1:41268 (0 connections now open)
2020-07-24T13:09:28.335+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:41304 #108 (1 connection now open)
2020-07-24T13:09:28.336+0000 I  NETWORK  [conn108] received client metadata from 127.0.0.1:41304 conn108: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.2.8" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 10 (buster)"", architecture: "x86_64", version: "Kernel 4.14.177-139.253.amzn2.x86_64" } }
2020-07-24T13:09:28.339+0000 I  ACCESS   [conn108] Unauthorized: not authorized on admin to execute command { endSessions: [ { id: UUID("ae78c796-73ed-45ff-a11b-87704753cb8b") } ], $db: "admin" }
2020-07-24T13:09:28.339+0000 I  NETWORK  [conn108] end connection 127.0.0.1:41304 (0 connections now open)
```

**Comment by andresbono** [comment]
Hi @kwill4026, thanks for the detailed steps to reproduce the issue. We are going to try it. If we need more information, we will get back to you.

**Comment by andresbono** [comment]
I think we have found the issue. If you check https://github.com/bitnami/bitnami-docker-mongodb/blob/2cc1b6f2f8d43252826559d9b184787a9c444b8a/4.2/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh#L1002-L1008

```
        mongodb_start_bg
        mongodb_create_users
        if [[ -n "$MONGODB_REPLICA_SET_MODE" ]]; then
            if [[ -n "$MONGODB_REPLICA_SET_KEY" ]]; then
                mongodb_create_keyfile "$MONGODB_REPLICA_SET_KEY"
                mongodb_set_keyfile_conf
            fi
```

MongoDB is being started before the keyfile is created. It should be done the other way around. We will continue investigating it and updating this issue.

**Comment by andresbono** [comment]
Hi again @kwill4026, changing the order in the actions to start the service and create the key file is not working as expected for all the scenarios that we test, so we will need to continue investigating it.

For now, can you keep working with it by first installing the chart and then upgrading it with the new configuration as you mention?

**Comment by kwill4026** [comment]
@andresbono thanks, I too tried changing the order and still no luck. For now I will do the default install then upgrade chart.

**Comment by togikirankumar** [comment]
Hey @kwill4026 i am facing the same problem i.e installing mongo with updated configuration (uncommentated) . Is this fixed.
` For now I will do the default install then upgrade chart.`
Will this work , the method which you talked about.

**Comment by andresbono** [comment]
Hi @togikirankumar, we have made many major changes in the chart since this issue was initially reported, but this still seems to be a bug. You can try the `install` + `upgrade` work-around and let us know.

**Comment by franklin432** [comment]
@togikirankumar what @andresbono said. I have not attempted to mess with the updated configuration section since I made the comment. I was only doing that to attempt to include TLS into the helm chart. Now the chart itself is integrated with TLS/SSL.

**Comment by togikirankumar** [comment]
Hi @andresbono  . I tried the lastest version but still the same issue. When i installed using the configuration as commented its working perfectly fine but when i uncommented the same configuration with architecture **replicaset** its going into crashloop.

### MongoDB version
```
name: mongodb
version: 10.6.2
appVersion: 4.4.3
```

### To reproduce
**with uncommented configuration**
1. helm repo add bitnami https://charts.bitnami.com/bitnami
2. Pull down the values files i.e values.yaml
3. helm upgrade --install mongodb bitnami/mongodb -n <namespace>  --values [values.yaml](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml)

`configuration: |-
  # where and how to store data.
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
  # where to write logging data
  systemLog:
    destination: file
    quiet: true
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0
  # network interfaces
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    bindIpAll: true
  # replica set options
  replication:
    replSetName: rs0
    enableMajorityReadConcern: true
  # process management options
  processManagement:
    fork: false
    pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
  # set parameter options
  setParameter:
    enableLocalhostAuthBypass: true
  # security options
  security:
    authorization: enabled
    keyFile: /opt/bitnami/mongodb/conf/keyfile
`

`**kg po -n db**                       
NAME                READY   STATUS             RESTARTS   AGE
mongodb-0           0/1     CrashLoopBackOff   3          117s
mongodb-arbiter-0   1/1     Running            0          117s
`

`**k logs mongodb-0  mongodb -n db**                
Advertised Hostname: mongodb-0.mongodb-headless.databases.svc.cluster.local
Pod name matches initial primary pod name, configuring node as a primary
mongodb 09:35:03.73 
mongodb 09:35:03.74 Welcome to the Bitnami mongodb container
mongodb 09:35:03.74 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 09:35:03.74 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 09:35:03.74 
mongodb 09:35:03.74 INFO  ==> ** Starting MongoDB setup **
mongodb 09:35:03.77 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 09:35:03.79 INFO  ==> Initializing MongoDB...
mongodb 09:35:03.80 INFO  ==> Deploying MongoDB from scratch...
`

`**k logs mongodb-arbiter-0  mongodb-arbiter -n db**   
mongodb 09:34:18.31 
mongodb 09:34:18.31 Welcome to the Bitnami mongodb container
mongodb 09:34:18.31 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 09:34:18.31 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 09:34:18.31 
mongodb 09:34:18.31 INFO  ==> ** Starting MongoDB setup **
mongodb 09:34:18.33 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 09:34:18.35 INFO  ==> Initializing MongoDB...
mongodb 09:34:18.37 INFO  ==> Deploying MongoDB from scratch...
mongodb 09:34:19.47 INFO  ==> Creating users...
mongodb 09:34:19.47 INFO  ==> Users created
mongodb 09:34:19.47 INFO  ==> Writing keyfile for replica set authentication...
mongodb 09:34:19.51 INFO  ==> Configuring MongoDB replica set...
mongodb 09:34:19.52 INFO  ==> Stopping MongoDB...
mongodb 09:34:22.36 INFO  ==> Trying to connect to MongoDB server mongodb-0.mongodb-headless.databases.svc.cluster.local...
cannot resolve host "mongodb-0.mongodb-headless.databases.svc.cluster.local": lookup mongodb-0.mongodb-headless.databases.svc.cluster.local: no such host
cannot resolve host "mongodb-0.mongodb-headless.databases.svc.cluster.local": lookup mongodb-0.mongodb-headless.databases.svc.cluster.local: no such host
`

**Comment by franklin432** [comment]
@togikirankumar I too tried the latest version of the chart and the helm install then helm upgrade option works for me. 


1. Default Configuration with only change to the values.yaml file to be the architecture from standalone to replicaset
2. This installed fine.
3. helm upgrade of the existing chart name by first commenting out the **configuration:** section in the values.yaml file. To easily confirm the config will take, I changed the existing **bindIpAll: true** to **bindIp: 0.0.0.0** which are both the same. security.authorization should be of course set to **enabled**.
```
configuration: |-
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
  systemLog:
    destination: file
    quiet: true
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    bindIp: 0.0.0.0
    #bindIpAll: true
  replication:
    replSetName: rs0
    enableMajorityReadConcern: true
  processManagement:
        fork: false
        pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
  setParameter:
       enableLocalhostAuthBypass: true
  security:
    authorization: enabled
    keyFile: /opt/bitnami/mongodb/conf/keyfile
```

The name of my helm project is mymongo. Attempting to run the command: helm upgrade -f mymongo -f values.yaml .
gives me an error stating I need to specify my current mongodb root password and replicaset key in order to continue with the upgrade. This can be done with the --set commands. 

I do this with the command: helm upgrade mymongo -f values.yaml . --set auth.rootPassword=<password> --set auth.replicaSetKey=<replicasetkey>

The chart gets upgraded fine with the configuration I had commented out from the values.yaml file. I can confirm it took by running **kubectl get cm** which shows a new configmap as well as when I bash into the pod I can see **bindIp: 0.0.0.0** in the mongod.conf instead of the original **bindIpAll: true**

**Comment by franklin432** [comment]
However attempting to pull down the bitnami/mongodb chart, uncommenting the configuration parameters and performing a helm install will causes the errors you were seeing with the  crashing of the pod.  For now you will have to stick with the default install, make your changes, then helm upgrade to take your changes. 
```
NAME                READY   STATUS             RESTARTS   AGE
mongodb-0           0/1     CrashLoopBackOff   3          117s
mongodb-arbiter-0   1/1     Running            0          117s
```

**Comment by togikirankumar** [comment]
Thank yo so much @franklin432 , works perfectly now.

**Comment by andresbono** [comment]
Thanks, @togikirankumar, @franklin432. I'm adding the details from this issue to our internal task, but for now, please stick to the "default install + upgrade" workaround.

**Comment by emrekgn** [comment]
Hi, 

I have the same issue and the proposed workaround (default install + upgrade) works successfully. So thank you so much for that! 

May I ask do we have any updates on the issue?
And just out of curiosity, why is changing the order of key file creation (`mongodb_create_keyfile`) and mongodb startup (I guess `mongodb_start_bg`) problematic?

**Comment by andresbono** [comment]
Hi @emrekgn, it's great that the workaround worked for you!

I'm afraid that the internal task is still in our backlog, no updates so far.

> And just out of curiosity, why is changing the order of key file creation (mongodb_create_keyfile) and mongodb startup (I guess mongodb_start_bg) problematic?

That was just an hypothesis, but changing the order is not making it work: https://github.com/bitnami/charts/issues/3213#issuecomment-667175566...

Any suggestions to solve the issue will be appreciated.

**Comment by lireanne** [comment]
In case anyone still experiences the same issue: I was still having trouble with mongodb pods crashing following `helm install my-mongo -f values-production.yaml` with non-empty `configuration` settings. The aforementioned workaround of default install + upgrade unfortunately did not solve the issue for me. 

My solution:
 - Create a configMap `mongod-conf` with the configurations I needed
 - In `values-production.yaml`, leave the `configuration` parameter empty and add `extraVolumeMounts`/`extraVolumes` parameters to bind to the configMap
```
extraVolumeMounts:
- name: mongod-conf
  mountPath: "/opt/bitnami/mongodb/conf/mongod.conf"
  subPath: mongod.conf
extraVolumes:
- name: mongod-conf
  configMap:
    name: mongod-conf
```
- Helm install as usual
