### ISSUE TITLE
[bitnami/valkey] Chart with auth.usePasswordFiles: true trying to mount valkey-password even with auth.enabled: false

### ISSUE THREAD

**Issue by Sad-Soul-Eater** [bitnami/charts#32154]
### Name and Version

bitnami/valkey 2.4.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy valkey chart version 2.4.0 which includes new (https://github.com/bitnami/charts/pull/32121 usePasswordFiles=true by default) changes

### Are you using any custom parameters or values?

```yaml
architecture: standalone
auth:
  enabled: false
global:
  defaultStorageClass: flash-iscsi
primary:
  kind: Deployment
  updateStrategy:
    type: Recreate
  resources:
    requests: { cpu: 20m, memory: 128Mi }
    limits: { memory: 256Mi }
  persistence:
    annotations:
      k8up.io/backup: "true"
    size: 512Mi
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenDeleted: Delete
```

### What is the expected behavior?

Do not mount non-existed valkey-password secret when `auth.enabled: false`
https://github.com/bitnami/charts/blob/fdbd862be60ddbea1ea1e919cac7cbdf0814048e/bitnami/valkey/templates/primary/application.yaml#L426-L437

### What do you see instead?

Pod cannot start because secret for `valkey-password` volume is not existing when  `auth.enabled: false`
