### ISSUE TITLE
[bitnami/valkey] Valkey metrics crashes: password not in the right format

### ISSUE THREAD

**Issue by awoimbee** [bitnami/charts#32195]
### Name and Version

bitnami/valkey 2.4.0

### What architecture are you using?

None

### What steps will reproduce the bug?

```
helm install valkey oci://registry-1.docker.io/bitnamicharts/valkey --set auth.enabled=true --set auth.password=abcd --set architecture=replication --set sentinel.enabled=true --version 2.4.0
```

### What do you see instead?

```
level=fatal msg="Error loading redis passwords from file /secrets/valkey-password, err: invalid character 'a' looking for beginning of value"
```
(here 'a' is the first letter of my dummy password)

### Additional information

I tried adding quotes around the pasword:
```
level=fatal msg="Error loading redis passwords from file /secrets/valkey-password, err: json: cannot unmarshal string into Go value of type map[string]string"
```

I tried `{"password": "abcd"}`, but then it's sentinel that wasn't happy:
```
>>> 'sentinel auth-pass myprimary {"password": "w5LZzdt16V3jMWOSjsQ1"}'
```

**Comment by awoimbee** [comment]
I'm using pulumi, this works:
```javascript
values: {
  architecture: "replication",
  sentinel: {
    enabled: true,
  },
  auth: {
    enabled: true,
    password: password
  },
  metrics: {
    enabled: true,
    extraEnvVars: [{
      name: "REDIS_PASSWORD",
      value: pulumi.interpolate`{"password": "${password}"}`
    }],
    serviceMonitor: {
      enabled: true,
      namespace: globals.monitoringNamespaceName,
    },
  },
},
```

**Comment by agiletea** [comment]
ENV: 
Azure Kubernetes 1.28.15
Helm v3.9
Chart Structure:

workplan-publisher
  - charts
    - mongodb
    - rabbitmq
    - webapi
    - worker
  - values.yaml

We have just upgraded to this chart version and immediately our services are failing to connect. On inspection, it seems that **when the Rabbit Mq chart is declared as a dependent subchart**, we can see that the auth.password value is now base64 encoded **TWICE** which seems to be the issue. I've tested this by logging in with the base64 encoding version of the password IN QUOTES and it lets me in. If I deploy the chart locally as a single chart (Docker Desktop), the rabbitmq-password is correctly stored as a single base 64 encoding.

We previously used version 10.1.16. Pulling both charts down locally we can see the secrets.yaml in v10 displays the correct value. With v15.3.3 that values is now double encoded and incorrect.

Out top level chart:
``` yaml
apiVersion: v2
appVersion: 1.0.0.preview-1.0
dependencies:
- name: rabbitmq
  repository: https://charts.bitnami.com/bitnami
  version: 15.3.3
- name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 13.18.5
description: A Helm chart for Kubernetes
name: workplan-publisher
type: application
version: 25.02.278

```
