### ISSUE TITLE
[bitnami/mongodb] metrics exporter doesn't work with mTLS

### ISSUE THREAD

**Issue by lasseoe** [bitnami/charts#32191]
### Name and Version

bitnami/mongodb 16.4.5

### What architecture are you using?

None

### What steps will reproduce the bug?

Deploy mongodb with mTLS enabled and custom certificates.

Certificate extensions look like this, and incrementing the number for each pod:
DNS.1 = mongodb-headless
DNS.2 = mongodb-0
DNS.3 = mongodb-0.mongodb-headless.mongo-test.svc.cluster.local

### Are you using any custom parameters or values?
```yaml
architecture: replicaset
auth:
  enabled: true
  usernames:
    - "somedbuser"
  databases:
    - "somedb"
  existingSecret: "mongodb"
tls:
  enabled: true
  mTLS:
    enabled: true
  autoGenerated: false
  mode: requireTLS
  replicaset:
    existingSecrets:
      - mongodb-0-cert
      - mongodb-1-cert
      - mongodb-2-cert
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```
### What is the expected behavior?

Metrics in Prometheus.

### What do you see instead?

No metrics in Prometheus because mongodb_exporter connects to localhost instead of the actual pod hostname.  Adding "localhost" to the certificates is not really an option.

```
time="2025-02-26T19:12:36Z" level=error msg="Cannot connect to MongoDB: cannot connect to MongoDB: server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: localhost:27017, Type: Unknown, Last error: tls: failed to verify certificate: x509: certificate is valid for mongodb-headless, mongodb-0, mongodb-0.mongodb-headless, mongodb-0.mongodb-headless.mongo-test.svc.cluster.local, not localhost }, ] }"
```

### Additional information

Everything else works just fine with our custom certificates
