### ISSUE TITLE
[bitnami/redis]: secretPasswordKey used as filename for

### ISSUE THREAD

**Issue by brightdroid** [bitnami/charts#32214]
### Name and Version

bitnami/redis 20.10.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. deploy chart using an existing secret with example values given below

### Are you using any custom parameters or values?

```yaml
auth:
  existingSecret: redis-secret
  existingSecretPasswordKey: password-key
```

### What is the expected behavior?

Chart should use the filename given in `volumes:`

### What do you see instead?

Chart uses wrong filename (name of `existingSecretPasswordKey`) for env var REDIS_PASSWORD_FILE.
