### ISSUE TITLE
[bitnami/cassandra] <eq .failOnNew false>: error calling eq: incompatible types for comparison

### ISSUE THREAD

**Issue by Jupi43** [bitnami/charts#32210]
### Name and Version

bitnami/cassandra 12.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Existing cassandra cluster in kubernetes (3 replicas), version 4.1.7  deployed using helm chart 11.3.2,  existing secret "cassandra" with key "cassandra-password"
2.  Trying to upgrade cassandra to version 5.0.3 with latest chart 12.2.0

### Are you using any custom parameters or values?
```
global:
  security:
    allowInsecureImages: true
usePasswordFiles: false
diagnosticMode:
  enabled: false
image:
  registry: own.repo.mirror.prv
  repository: library/bitnami/cassandra
  tag: 5.0.3
dbUser:
  user: cassandra
  forcePassword: false
  password: ""
  existingSecret: ""
cluster:
  name: cassandra
  seedCount: 3
  numTokens: 16
  datacenter: dc1
  rack: rack1
  endpointSnitch: SimpleSnitch
  clientEncryption: false
  extraSeeds: []
  enableUDF: false
jvm:
  maxHeapSize: "3200M"
  newHeapSize: "200M"
extraEnvVars:
  - name: CASSANDRA_AUTHENTICATOR
    value: AllowAllAuthenticator
  - name: CASSANDRA_AUTHORIZER
    value: AllowAllAuthorizer
  - name: CASSANDRA_MOUNTED_CONF_DIR
    value: /opt/bitnami/custom_conf
  - name: LOCAL_JMX
    value: "no"
  - name: MY_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
replicaCount: 3
podLabels: {"run" : "cassandra"}
resources:
  limits: 
    cpu: 2
    memory: 6Gi
  requests: 
    cpu: 2
    memory: 6Gi
customLivenessProbe:
  exec:
    command:
    - /bin/bash
    - -ec
    - |
      nodetool -u $CASSANDRA_USER -pw $CASSANDRA_PASSWORD status
  initialDelaySeconds: 60
  periodSeconds: 5
  timeoutSeconds: 30
  successThreshold: 1
  failureThreshold: 48
customReadinessProbe:
  exec:
    command:
    - /bin/bash
    - -ec
    - |
      nodetool -u $CASSANDRA_USER -pw $CASSANDRA_PASSWORD status | grep -E "^UN\\s+${POD_IP}"
  initialDelaySeconds: 60
  periodSeconds: 5
  timeoutSeconds: 30
  successThreshold: 1
  failureThreshold: 48
customStartupProbe: {}
lifecycleHooks:
  preStop:
    exec:
      command:
      - bash
      - -ec
      - nodetool  -u $CASSANDRA_USER -pw $CASSANDRA_PASSWORD status
extraVolumes: 
  - name: cassandra
    nfs:
      server: my.nfs
      path: /nfs4k8s_logs/cassandra
  - name: data
    nfs:
      server: my.nfs
      path: /nfs4k8s_data/cassandra
  - name: logback
    configMap:
      name: cassandra-configmap
extraVolumeMounts:
  - mountPath: /opt/bitnami/cassandra/logs
    name: cassandra
    subPathExpr: $(POD_NAME)     
  - mountPath: /bitnami/cassandra
    name: data
    subPathExpr: $(POD_NAME)
  - mountPath: /opt/bitnami/custom_conf
    name: logback
pdb:
  create: false
persistence:
  enabled: false
metrics:
  enabled: false
tls:
  internodeEncryption: none
  clientEncryption: false
  autoGenerated: false
```

### What is the expected behavior?

Existing cluster upgraded from 4.1.7 to 5.0.3

### What do you see instead?

Helm error:

`Error: template: cassandra/templates/cassandra-secret.yaml:18:25: executing "cassandra/templates/cassandra-secret.yaml" at <include "cassandra.password" .>: error calling include: template: cassandra/templates/_helpers.tpl:259:12: executing "cassandra.password" at <include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "cassandra-password" "providedValues" (list "dbUser.password") "context" $)>: error calling include: template: cassandra/charts/common/templates/_secrets.tpl:124:16: executing "common.secrets.passwords.manage" at <eq .failOnNew false>: error calling eq: incompatible types for comparison`
