### ISSUE TITLE
[bitnami/external-dns]: Error when AWS node have IMDSv2 required

### ISSUE THREAD

**Issue by MonkzCode** [bitnami/charts#32216]
### Name and Version

external-dns 8.7.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Check my description given below

### What is the expected behavior?

external-dns should work on AWS EKS spot nodes with `IMDSv2=Required`

### What do you see instead?

I see error message:
```
time="2025-02-28T14:21:12Z" level=info msg="Using inCluster-config based on serviceaccount-token"
time="2025-02-28T14:21:12Z" level=info msg="Created Kubernetes client https://10.10.0.1:443"
time="2025-02-28T14:21:18Z" level=error msg="Failed to do run once: soft error\nrecords retrieval failed: soft error\nfailed to list hosted zones: operation error Route 53: ListHostedZones, get identity: get credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, canceled, context deadline exceeded"
```

### Additional information

My config to deploy external-dns:
```yaml
external-dns:
  enabled: true
  aws:
    zoneType: ""
    region: eu-central-1
    credentials:
      accessKey:
      secretKey:
  txtOwnerId: Z0000000ZZ0ZZZZZZ00Z
  txtPrefix: "txt-"
  policy: upsert-only
  domainFilters:
    - my.dev
    - my.lan
```

I have noderole with attached policy (recommended for aws route 53)

Now, AWS EKS nodes have IMDSv2 switched on by default, if (thru AWS webconlsole) I change it back to `IMDSv2=Optional `external-dns immediately works as expected 

Please, help, what should I do?
