### ISSUE TITLE
[bitnami/valkey] Setting existingSecretPasswordKey makes Valkey pod failed to start

### ISSUE THREAD

**Issue by hongbo-miao** [bitnami/charts#32225]
### Name and Version

bitnami/valkey 2.4.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```yaml
auth:
  enabled: true
  sentinel: true
  existingSecret: hm-ray-cluster-valkey-secret
  existingSecretPasswordKey: VALKEY_PASSWORD
primary:
  replicaCount: 1
  persistence:
    accessModes: ["ReadWriteOnce"]
    size: 1Gi
    storageClass: production-hm-ray-cluster-valkey-storage-class
replica:
  replicaCount: 3
  persistence:
    accessModes: ["ReadWriteOnce"]
    size: 1Gi
    storageClass: production-hm-ray-cluster-valkey-storage-class
sentinel:
  enabled: true
```

gives error

```sh
 06:41:26.70 INFO  ==> about to run the command: REDISCLI_AUTH=$VALKEY_PASSWORD timeout 90 valkey-cli -h hm-ray-cluster-valkey.production-hm-ray-cluster-valkey.svc.cluster.local -p 26379 sentinel get-primary-addr-by-name myprimary
Could not connect to Valkey at hm-ray-cluster-valkey.production-hm-ray-cluster-valkey.svc.cluster.local:26379: Connection refused
Could not connect to Valkey at hm-ray-cluster-valkey.production-hm-ray-cluster-valkey.svc.cluster.local:26379: Connection refused
 06:41:36.73 INFO  ==> Configuring the node as primary
1:C 02 Mar 2025 06:41:36.749 * oO0OoO0OoO0Oo Valkey is starting oO0OoO0OoO0Oo
1:C 02 Mar 2025 06:41:36.749 * Valkey version=8.0.2, bits=64, commit=00000000, modified=1, pid=1, just started
1:C 02 Mar 2025 06:41:36.749 * Configuration loaded
1:M 02 Mar 2025 06:41:36.749 * monotonic clock: POSIX clock_gettime
1:M 02 Mar 2025 06:41:36.750 * Running mode=standalone, port=6379.
1:M 02 Mar 2025 06:41:36.751 * Server initialized
1:M 02 Mar 2025 06:41:36.755 * Creating AOF base file appendonly.aof.1.base.rdb on server start
1:M 02 Mar 2025 06:41:36.761 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
1:M 02 Mar 2025 06:41:36.761 * Ready to accept connections tcp
 06:45:37.53 INFO  ==> Found previous primary hm-ray-cluster-valkey-node-0.hm-ray-cluster-valkey-headless.production-hm-ray-cluster-valkey.svc.cluster.local in /opt/bitnami/valkey-sentinel/etc/sentinel.conf
 06:45:37.54 INFO  ==> about to run the command: REDISCLI_AUTH=$VALKEY_PASSWORD timeout 90 valkey-cli -h hm-ray-cluster-valkey.production-hm-ray-cluster-valkey.svc.cluster.local -p 26379 sentinel get-primary-addr-by-name myprimary
Could not connect to Valkey at hm-ray-cluster-valkey.production-hm-ray-cluster-valkey.svc.cluster.local:26379: Connection refused
Could not connect to Valkey at hm-ray-cluster-valkey.production-hm-ray-cluster-valkey.svc.cluster.local:26379: Connection refused

*** FATAL CONFIG FILE ERROR (Version 8.0.2) ***
Reading the configuration file, at line 10
>>> 'requirepass'
wrong number of arguments
```

### What is the expected behavior?

I expect it uses field `VALKEY_PASSWORD` based on

```
existingSecretPasswordKey: VALKEY_PASSWORD
```

### What do you see instead?

The log seems it uses `VALKEY_PASSWORD`, however, the pod still failed to start.

### Additional information

If I remove 
```
existingSecretPasswordKey: VALKEY_PASSWORD
```

and my secret uses default key `valkey-password` with my custom password as value, the pod can succeed starting.

So I feel something wrong with `existingSecretPasswordKey` right now.
