### ISSUE TITLE
[bitnami/nats] Add support for optional JetStream store directory

### ISSUE THREAD

**Issue by javirln** [bitnami/charts#32232]
### Name and Version

bitnami/nats:9.x.x

### What is the problem this feature will solve?

As mentioned in the [Upgrading section](https://github.com/bitnami/charts/tree/main/bitnami/nats#to-900) of the NATS chart, the location of the Jetstream store directory has changed, and it is up to users to make the necessary adjustments for it to work after the update.

This issue occurs only if the Jetstream store folder contains data, such as stream information. Attempting an update under these circumstances causes the health check to fail, leading to pod restarts.

Example:
```
nats [1] [INF] Starting nats-server
nats [1] [INF]   Version:  2.10.26
nats [1] [INF]   Git:      [14fa949]
nats [1] [INF]   Name:     upstream-release-nats-0
nats [1] [INF]   Node:     fpGBSQ92
nats [1] [INF]   ID:       NC3RIAXXXYGP6LBDQNVQ5LNORTRGX25F7BQPW5I5KQ3NBCW6BCXKQVAR
nats [1] [INF] Using configuration file: /etc/nats-server.conf
nats [1] [INF] Starting http monitor on 0.0.0.0:8222
nats [1] [INF] Starting JetStream
nats [1] [INF]     _ ___ _____ ___ _____ ___ ___   _   __  __
nats [1] [INF]  _ | | __|_   _/ __|_   _| _ \ __| /_\ |  \/  |
nats [1] [INF] | || | _|  | | \__ \ | | |   / _| / _ \| |\/| |
nats [1] [INF]  \__/|___| |_| |___/ |_| |_|_\___/_/ \_\_|  |_|
nats [1] [INF]
nats [1] [INF]          https://docs.nats.io/jetstream
nats [1] [INF]
nats [1] [INF] ---------------- JETSTREAM ----------------
nats [1] [INF]   Max Memory:      953.67 MB
nats [1] [INF]   Max Storage:     8.00 GB
nats [1] [INF]   Store Directory: "/data/jetstream"
nats [1] [INF] -------------------------------------------
nats [1] [INF] Listening for client connections on 0.0.0.0:4222
nats [1] [INF] Server is ready
nats [1] [WRN] Healthcheck failed: "JetStream account 'jetstream' could not be resolved"
nats [1] [WRN] Healthcheck failed: "JetStream account 'jetstream' could not be resolved"
nats [1] [WRN] Healthcheck failed: "JetStream account 'jetstream' could not be resolved"
nats [1] [WRN] Healthcheck failed: "JetStream account 'jetstream' could not be resolved"
nats [1] [WRN] Healthcheck failed: "JetStream account 'jetstream' could not be resolved"
nats [1] [WRN] Healthcheck failed: "JetStream account 'jetstream' could not be resolved"
nats [1] [INF] Initiating Shutdown...
nats [1] [INF] Initiating JetStream Shutdown...
nats [1] [INF] JetStream Shutdown
nats [1] [INF] Server Exiting..
```

### What is the feature you are proposing to solve the problem?

To facilitate the transition from a previous version to the latest one that uses the scratch base images, I suggest adding a new config_path field under the Jetstream options. This would point to an already existing configuration of the Chart, if available. Example

```yaml
# values.yaml
## JetStream Configuration
## ref: https://docs.nats.io/running-a-nats-service/configuration/resource_management
## @param jetstream.enabled Switch to enable/disable JetStream
## @param jetstream.maxMemory Max memory usage for JetStream
## @param jetstream.storeDirectory The store directory for JetStream
##
jetstream:
  enabled: false
  maxMemory: 1G
  storeDirectory: /data/jetstream
```

And the needed changes on the templates to craft the final configuration.

### What alternatives have you considered?

There's a possibility that an existing configuration may not be recognized by the latest version, one straightforward solution is to rename the chart-release. This forces the creation of new PVCs, but it results in data loss.
