### ISSUE TITLE
[bitnami/redis-cluster] volumePermission fails to start with error "/bin/chown: invalid spec: '1001:'"

### ISSUE THREAD

**Issue by happyyangyuan** [bitnami/charts#3225]
**Which chart**:
redis-cluster:3.1.6

**Describe the bug**
volumePermission container fails to start with error "/bin/chown: invalid spec: '1001:'".
The volumePermission init container use varable name "containerSecurityContext.fsGroup" but this chart default values.yaml only provides "podSecurityContext.fsGroup"

template/redis-statefulset.yaml
```yaml
{{- if $needsVolumePermissions }}
        - name: volume-permissions
          # here is ".Values.containerSecurityContext.fsGroup"
          command: ["/bin/chown", "-R", "{{ .Values.containerSecurityContext.runAsUser }}:{{ .Values.containerSecurityContext.fsGroup }}", "{{ .Values.persistence.path }}"]
```

```yaml
      securityContext:
        # here is "podSecurityContext.fsGroup"
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
        {{- if .Values.podSecurityContext.sysctls }}
```

**To Reproduce**

Set volumePermission=true and run this chart
