### ISSUE TITLE
rabbitmq-cluster-operator is not respecting rabbitmqImage option

### ISSUE THREAD

**Issue by bober2000** [bitnami/charts#32339]
### Name and Version

bitnami/rabbitmq-cluster-operator:3.20.1

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. installed operator using terraform. Deployment yaml:
```yaml
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          annotations:
            Expense_type: r_and_d
            operations.company.com/service: rabbitmq-cluster-operator
          labels:
            app.kubernetes.io/component: rabbitmq-operator
            app.kubernetes.io/instance: rabbitmq-cluster-operator
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: rabbitmq-cluster-operator
            app.kubernetes.io/part-of: rabbitmq
            app.kubernetes.io/version: 2.7.0
            helm.sh/chart: rabbitmq-cluster-operator-3.20.1
          name: rabbitmq-cluster-operator
          namespace: rabbitmq
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/component: rabbitmq-operator
              app.kubernetes.io/instance: rabbitmq-cluster-operator
              app.kubernetes.io/name: rabbitmq-cluster-operator
          strategy:
            type: RollingUpdate
          template:
            metadata:
              labels:
                app.kubernetes.io/component: rabbitmq-operator
                app.kubernetes.io/instance: rabbitmq-cluster-operator
                app.kubernetes.io/managed-by: Helm
                app.kubernetes.io/name: rabbitmq-cluster-operator
                app.kubernetes.io/part-of: rabbitmq
                app.kubernetes.io/version: 2.7.0
                helm.sh/chart: rabbitmq-cluster-operator-3.20.1
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: dedicated-for
                        operator: In
                        values:
                        - rabbitmq-main
              automountServiceAccountToken: true
              containers:
              - args:
                - --metrics-bind-address=:9782
                command:
                - /manager
                env:
                - name: OPERATOR_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: DEFAULT_RABBITMQ_IMAGE
                  value: 000000000000.dkr.ecr.us-east-1.amazonaws.com/docker.io/bitnami/rabbitmq:3.12.13-debian-12-r2
                - name: DEFAULT_USER_UPDATER_IMAGE
                  value: 000000000000.dkr.ecr.us-east-1.amazonaws.com/docker.io/bitnami/rmq-default-credential-updater:1.0.4-debian-12-r14
                envFrom: null
                image: 000000000000.dkr.ecr.us-east-1.amazonaws.com/docker.io/bitnami/rabbitmq-cluster-operator:2.7.0-debian-12-r8
                imagePullPolicy: IfNotPresent
                livenessProbe:
                  failureThreshold: 5
                  httpGet:
                    path: /metrics
                    port: http
                  initialDelaySeconds: 5
                  periodSeconds: 30
                  successThreshold: 1
                  timeoutSeconds: 5
                name: rabbitmq-cluster-operator
                ports:
                - containerPort: 9782
                  name: http
                  protocol: TCP
                readinessProbe:
                  failureThreshold: 5
                  httpGet:
                    path: /metrics
                    port: http
                  initialDelaySeconds: 5
                  periodSeconds: 30
                  successThreshold: 1
                  timeoutSeconds: 5
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  privileged: false
                  readOnlyRootFilesystem: true
                  runAsGroup: 1001
                  runAsNonRoot: true
                  runAsUser: 1001
                  seLinuxOptions: null
                  seccompProfile:
                    type: RuntimeDefault
              initContainers: null
              securityContext:
                fsGroup: 1001
                fsGroupChangePolicy: Always
                supplementalGroups: []
                sysctls: []
              serviceAccountName: rabbitmq-cluster-operator
              tolerations:
              - key: dedicated-for
                operator: Equal
                value: rabbitmq-main
```
Setting
```yaml
rabbitmqImage:
  registry: ${ecr_cache_prefix}
  repository: docker.io/bitnami/rabbitmq
  
credentialUpdaterImage:
  registry: ${ecr_cache_prefix}
  repository: docker.io/bitnami/rmq-default-credential-updater

clusterOperator:
  image:
    registry: ${ecr_cache_prefix}
    repository: docker.io/bitnami/rabbitmq-cluster-operator
```
in values files - where ecr_cache_prefix is `000000000000.dkr.ecr.us-east-1.amazonaws.com` for using AWS ECR Cache.
2. I've created RabbitMQ cluster using this manifest
```yaml
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        metadata:
          annotations:
            Expense_type: r_and_d
            operations.company.com/team: sn-devops
            rabbitmq.com/topology-allowed-namespaces: '*'
          labels:
            app: rabbitmq-main
          name: rabbitmq-main
          namespace: rabbitmq
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: dedicated-for
                    operator: In
                    values:
                    - rabbitmq-main
          override:
            service:
              spec:
                ports:
                - name: prometheus
                  port: 15692
                  protocol: TCP
            statefulSet:
              spec:
                template:
                  metadata:
                    annotations:
                      Expense_type: r_and_d
                    labels:
                      app: rabbitmq-main
                      sidecar.istio.io/inject: "true"
          persistence:
            storage: 64Gi
            storageClassName: rabbitmq-main-gp3
          rabbitmq:
            additionalConfig: |
              vm_memory_high_watermark.relative = 0.4
              vm_memory_high_watermark_paging_ratio = 0.75
              ssl_options.fail_if_no_peer_cert = false
              ssl_options.verify = verify_none
              tcp_listen_options.keepalive = true
            additionalPlugins:
            - rabbitmq_top
            - rabbitmq_consistent_hash_exchange
            - rabbitmq_shovel
            - rabbitmq_shovel_management
            - rabbitmq_federation
            - rabbitmq_federation_management
            - rabbitmq_peer_discovery_aws
            - prometheus_rabbitmq_exporter
          replicas: 3
          resources:
            limits:
              cpu: 1500m
              memory: 3500Mi
            requests:
              cpu: 200m
              memory: 3500Mi
          tolerations:
          - key: dedicated-for
            operator: Equal
            value: rabbitmq-main
```
but I still see default image in StatefulSet
```console
$ k get statefulset rabbitmq-main-server -o jsonpath="{.spec.template.spec.containers[*].image}" -n rabbitmq
docker.io/bitnami/rabbitmq:3.11.22-debian-11-r2
```
Operator and messaging-topology-operator at the same time are ok:
```
$ k get deployment rabbitmq-cluster-operator -o jsonpath="{.spec.template.spec.containers[*].image}" -n rabbitmq
000000000000.dkr.ecr.us-east-1.amazonaws.com/docker.io/bitnami/rabbitmq-cluster-operator:2.7.0-debian-12-r8
```

### Are you using any custom parameters or values?
```yaml
rabbitmqImage:
  registry: 000000000000.dkr.ecr.us-east-1.amazonaws.com
  repository: docker.io/bitnami/rabbitmq
  
credentialUpdaterImage:
  registry: 000000000000.dkr.ecr.us-east-1.amazonaws.com
  repository: docker.io/bitnami/rmq-default-credential-updater

clusterOperator:
  image:
    registry: 000000000000.dkr.ecr.us-east-1.amazonaws.com
    repository: docker.io/bitnami/rabbitmq-cluster-operator
```
### What is the expected behavior?

RabbitMQ cluster pods created by operator are using repository set in values

### What do you see instead?

RabbitMQ cluster pods created by operator are using default repository
