### ISSUE TITLE
harbor-registry secret is broken when existingSecret is set

### ISSUE THREAD

**Issue by dee-kryvenko** [bitnami/charts#32386]
### Name and Version

bitnami/harbor 24.3.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Somewhere between the versions 20.1.1 and 24.3.3, in this [commit](https://github.com/bitnami/charts/commit/84fae4bdd3985037f1ccfe60156b0c3dbf760a3e#diff-627f4709e86604da4a5c312c5b19170011250446e68925a43851b615fc032dd8L6), the harbor chart got a regression. I am supplying my own pre existent secrets i.e.

```yaml
            registry:
              existingSecret: harbor-configurator-registry-htpasswd
              tls:
                existingSecret: harbor-registry-internal-tls
```

The chart now still wants to create a harbor-registry secret with following content:

```yaml
data:
  REGISTRY_HTPASSWD: ++++++++
  REGISTRY_HTTP_SECRET: ++++++++
  REGISTRY_REDIS_PASSWORD: ++++++++
```

Also please be cognizant that not everyone want to use helm in the prescribed opinionated way. ArgoCD exists. The chart must provide an option to be used in the `helm template` scenario, unconditional use of runtime functions is not acceptable. ArgoCD users should not be getting out of sync warnings because `helm template` randomize REGISTRY_HTPASSWD on every refresh.

cc @jdaln
