### ISSUE TITLE
rabbitmq-cluster-operator still uses old rabbitmq image

### ISSUE THREAD

**Issue by BeyondEvil** [bitnami/charts#32383]
### Name and Version

bitnami/rabbitmq-cluster-operator:4.4.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install the helm chart.

Run

```
❯ kubectl get statefulset rabbitmq-cluster-server -n rabbitmq-system -o wide
NAME                      READY   AGE     CONTAINERS   IMAGES
rabbitmq-cluster-server   1/1     5m29s   rabbitmq     docker.io/bitnami/rabbitmq:3.13.2-debian-12-r4
```

### Are you using any custom parameters or values?

Yes, values file:

```yaml
global:
  defaultStorageClass: 'gp3'
```

### What is the expected behavior?

That the chart installs the correct image (4.0.7-*) as detailed by the chart.

### What do you see instead?

Old image: 3.13.2-*

**Comment by BeyondEvil** [comment]
I think the real issue here is a mismatch between the rabbitmq-cluster-operator and the RabbitMQCluster CRD.

The cluster-operator pod indeed gets 4.0.7, but the CRD pods (cluster-operator-server) gets 3.13.2

**Comment by BeyondEvil** [comment]
To reproduce:

Install the chart:

Chart.yaml

```yaml
apiVersion: v2
name: rabbitmq
description: Rabbit MQ
type: application
version: 0.1.0
dependencies:
  - name: rabbitmq-cluster-operator
    version: 4.4.6
    repository: registry-1.docker.io/bitnamicharts
```

Then apply the CR:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: rabbitmq-system
spec:
  replicas: 1
```
