### ISSUE TITLE
[bitnami/fluentd] Aggregator service type in values is not being used in actual service

### ISSUE THREAD

**Issue by fsschmitt** [bitnami/charts#3239]
**Which chart**:
- bitnami/fluentd v1.2.9 (and older)

**Describe the bug**
In the `values.yaml` file it allows users to specify the `type` and `annotations` of the aggregator service as well as setting some LoadBalancer values such as `LoadBalancerIP` and `loadBalancerSourceRanges`

```yaml
aggregator:
  service:
    ## Service type
    ##
    type: ClusterIP

    ## Service ports
    ##
    ports:
      # syslog-udp:
      #   port: 5140
      #   targetPort: syslog-udp
      #   protocol: UDP
      #   nodePort: 31514
      # syslog-tcp:
      #   port: 5140
      #   targetPort: syslog-tcp
      #   protocol: TCP
      #   nodePort: 31514
      # tcp:
      #   port: 24224
      #   targetPort: tcp
      #   protocol: TCP
      http:
        port: 9880
        targetPort: http
        protocol: TCP

    ## loadBalancerIP for the forwarders service (optional, cloud specific)
    ## ref: http://kubernetes.io/docs/user-guide/services/#type-loadbalancer
    ##
    # loadBalancerIP:

    ## Load Balancer sources
    ## https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
    ##
    # loadBalancerSourceRanges:
    #   - 10.10.10.0/24

    ## Set the Cluster IP to use
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#choosing-your-own-ip-address
    ##
    # clusterIP: None

    ## Provide any additional annotations which may be required
    ##
    annotations: {}
```

Although on the service specification it is: 
```yaml
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  {{- range $key, $value := .Values.aggregator.service.ports }}
    - name: {{ $key }}
      {{ toYaml $value | nindent 6 }}
  {{- end }}
  selector: {{- include "fluentd.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: aggregator
{{- end -}}
```

**To Reproduce**
1. On `values.yaml` set the `aggregator.service.type` to `LoadBalancer`
2. On `values.yaml` add an annotation on the `aggregator.service.annotation` value
3. Install the Helm Chart
4. `kubectl get services`
5. See that the service created is of type ClusterIP
6. See that the service created does not have the annotation added

**Expected behavior**
It is expected that the `aggregator` service reflects the settings available on the `values.yaml` file.

**Version of Helm and Kubernetes**:

Helm Version:
```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-gke.6", GitCommit:"14bc8ad5f8c245f1240a8e4eab128c4d51bfeffe", GitTreeState:"clean", BuildDate:"2020-05-30T02:07:03Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
