### ISSUE TITLE
[bitnami/kibana] Default values for updateStrategy and accessMode prevent successful helm upgrade

### ISSUE THREAD

**Issue by luischre** [bitnami/charts#32422]
### Name and Version

bitnami/kibana 11.5.2

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Deploy kibana with bitnami helm charts in some old version
2. Perform a helm upgrade

--> Upgrade will fail because the pvc is attached to the old pod

Workaround:

1. Deploy kibana with bitnami helm charts in some old version
2. Scale down kibana
3. Perform a helm upgrade

--> Upgrade will succeed

### Are you using any custom parameters or values?

Yes, but not for the affected values, there I am simply using the defaults:
```yaml
persistence:
  accessModes:
    - ReadWriteOnce

updateStrategy:
  type: RollingUpdate
```

As reference:
https://github.com/bitnami/charts/blob/main/bitnami/kibana/values.yaml#L263
https://github.com/bitnami/charts/blob/main/bitnami/kibana/values.yaml#L120

### What is the expected behavior?

Default values should have reasonable default values that work together and not against each other.

### What do you see instead?

Default values which are not compatible with each other.

### Additional information

From my understanding `RollingUpdate` and `ReadWriteOnce` can not work together. The new pod will always be stuck because the old pod still holds on to the PVC.

Not sure what is the best practice for such a use case but I guess it would either require the combination of:
* `Recreate` and `ReadWriteOnce` 
* `RollingUpdate` and `ReadWriteMany`

Else you will always need an additional scale down step for every update.

**Comment by javsalgar** [comment]
Hi,

For this kind of scenarios, the default `affinity` values should make the new pod to be deployed in the same k8s node as the previous one. Did you change any affinity setting?

**Comment by luischre** [comment]
Hi,

thanks for your answer. I don't have any custom values for `affinity`. But if I see it correctly there also no `affinity` default values? https://github.com/bitnami/charts/blob/main/bitnami/kibana/values.yaml#L663

But even if there would be according values, then it still wouldn't be granted that it would work out. The PVC will be mounted to the old pod and the new pod won't succeed with the mount or am I missing anything?

**Comment by luischre** [comment]
Okay, have to correct myself there are no default values in the values.yaml but I found the according part in the deployment.yaml:
https://github.com/bitnami/charts/blob/1b85a12d4d80968a403871b89843f7c3b568fdb2/bitnami/kibana/templates/deployment.yaml#L46

The only one that has a default value is podAntiAffinity:
https://github.com/bitnami/charts/blob/20e95a7001ccb50abbd23d8a445b489857c5222a/bitnami/kibana/values.yaml#L638

Checked my deployment for me this results in:
```
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: elastic-kibana
                    app.kubernetes.io/name: kibana
                topologyKey: kubernetes.io/hostname
```

And if I am not mistaken this is exactly the opposite of what you described. It rather makes sure that they never end up on the very same node?

**Comment by javsalgar** [comment]
Could you try setting it like this?

```
podAffinityPreset: soft
podAntiAffinityPreset: ""
```

**Comment by luischre** [comment]
I just got to test your proposed values. While I do see the according setting in the deployment when applying the change, I still see the new pod being deployed on a different node.

````
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: elastic-kibana
                    app.kubernetes.io/name: kibana
                topologyKey: kubernetes.io/hostname
```

I even did two upgrades in case I needed one to apply the change and only in the second one it would take effect but even the second one put the pod on a different node.

Maybe it's due to being only "soft" and combined with load on the cluster the scheduler hence disregards the affinity setting? In any case for me it results in the same: Upgrades work fine if I remember to scale down kibana upfront and otherwise they will get stuck.
