### ISSUE TITLE
Support persistentVolumeClaimRetentionPolicy in Kafka StatefulSets

### ISSUE THREAD

**Issue by matake01** [bitnami/charts#32455]
### Name and Version

bitnami/kafka 31.5.0

### What is the problem this feature will solve?

Since Kubernetes v1.32 the feature [PersistentVolumeClaim retention](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention) was announced stable . There is no opportunity to configure this value in the current chart version.

The configuration is needed for ephemeral situations which depends on auto-retention. 

### What is the feature you are proposing to solve the problem?

Add support for following fields in `values.yaml`:

```
broker:
  persistence:
    persistentVolumeClaimRetentionPolicy:
      enabled: true
        whenDeleted: Retain/Delete
        whenScaled: Retain/Delete
controller:
  persistence:
    persistentVolumeClaimRetentionPolicy:
      enabled: true
        whenDeleted: Retain/Delete
        whenScaled: Retain/Delete
```
