### ISSUE TITLE
[bitnami/etcd] Defrag CronJob - `auth: user name is empty`

### ISSUE THREAD

**Issue by Daniel-Vaz** [bitnami/charts#32476]
### Name and Version

bitnami/etcd 11.1.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy the ETCd Chart with RBAC and existing Secret. 
2. Enable the Defrag CronJob.
3. Verify that the Job fails with `"error":"rpc error: code = Unknown desc = auth: user name is empty"`

### Are you using any custom parameters or values?

```yaml
auth:
  rbac:
    create: true
    allowNoneAuthentication: false
    existingSecret: etcd-mimir
    existingSecretPasswordKey: MIMIR_ETCD
  token:
    enabled: false

autoCompactionMode: "periodic"
autoCompactionRetention: "10m"
defrag:
  enabled: true
```

### What is the expected behavior?

The CronJob should support having extra environment variable passed to it so defrag jobs run successfully. 

### What do you see instead?

Job Pods fail with: `"error":"rpc error: code = Unknown desc = auth: user name is empty"`
