### ISSUE TITLE
[bitnami/appsmith] Google Oauth 2.0 Always Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by 3-commerce** [bitnami/charts#32478]
### Name and Version

bitnami/appsmith 1.64.0-debian-12-r1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Use Helm Chart Bitnami Appsmith
2. Create new Client in Google Auth Platform.
3. Login to Appsmith and go to Admin Settings > Authentication for enabling Google login
4. Paste the Client ID and Client Secret
5. On number 2, the Authorized JavaScript origins and Authorized redirect URIs are filled in from generated Appsmith google login
Authorized JavaScript : https://domain.tld
Authorized redirect URIs : https://domain.tld/login/oauth2/code/google

After that i rollout `appsmith-backend` pod and the Google Login appears in the login page Appsmith bitnami.

However, after logging in using my e-mail the error like this

Access Block This app's request is invalid with error details

```
Error 400: redirect_uri_mismatch

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policies.

If you're the developer of the app, register a redirect URI in the Google Cloud Console.
Request details: redirect_uri=http://domain.tld/login/oauth2/code/google flowName=GeneralOAuthFlow
```

After some time, i got that redirect_uri is using http protocols. i don't know if it's affected to this error.
For additional settings, i have also set the Custom Domain to https://domain.tld

### Are you using any custom parameters or values?

```yaml
redis:
  architecture: standalone

mongodb:
  persistence:
    size: 20Gi
  architecture: replicaset

image:
  tag: 1.64.0-debian-12-r1

backend:
  existingSecret: appsmith-secrets
  existingSecretPasswordKey: appsmith-admin-password
  existingSecretEncryptionSaltKey: appsmith-encryption-salt
  existingSecretEncryptionPasswordKey: appsmith-encryption-password
  persistence:
    size: 20Gi
```

### What is the expected behavior?

I can login using Google mail account

### What do you see instead?

Sign Up or Login with email through Google SSO
