### ISSUE TITLE
Redis-sentinel with ACL doesn't work if default password is randomly generated

### ISSUE THREAD

**Issue by GautaA** [bitnami/charts#32497]
### Name and Version

bitnami/redis 20.11.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm repo update
$ helm install redis bitnami/redis --namespace redis --create-namespace --version 20.11.3 -f values-sentinel.yaml
```

### Are you using any custom parameters or values?

```yaml
architecture: replication
sentinel:
  enabled: true
  downAfterMilliseconds: 5000
  failoverTimeout: 30000
auth:
  enabled: true
  acl:
    enabled: true
    sentinel: true
    users:
      - username: "testuser"
        password: "testpassword"
        enabled: "on"
        commands: "+@all"
        keys: "~*"
        channels: "&*"
```

### What is the expected behavior?

For pods to start and to be in ready state.

### What do you see instead?

```
redis-node-0   1/2     Running   0          3m23s
```

The redis container starts successfully while the sentinel one doesn't. 
When describing the pod, I can see the following event:

```
Warning  Unhealthy  104s (x29 over 6m34s)  kubelet  Startup probe failed: NOAUTH Authentication required.
AUTH failed: WRONGPASS invalid username-password pair or user is disabled.
```

### Additional information

After playing around with values file for a bit, this only happens when the parameter:
`auth.password` is not set (so when it generates a random 10-character alphanumeric string)

When `auth.password` is set, both of the containers spin up normally and everything works as expected.

If my configuration is wrong, please let me know, if this is intended behavior I would suggest updating the documentation so it's a bit more clear.
Thanks!

**Comment by drtinkerer** [comment]
+1

I am facing the similar issue.

additional info my case being password for `default` user is not randomly generated, but I am picking it up from secret.
This is my values.yaml 

```
architecture: replication
sentinel:
  enabled: true
  downAfterMilliseconds: 5000
  failoverTimeout: 30000
auth:
  enabled: true
  acl:
    enabled: true
    existingSecret: "redis-password"
    existingSecretPasswordKey: "redis-password"
    sentinel: true
    users:
      - username: "testuser"
        password: "testpassword"
        enabled: "on"
        commands: "+@all"
        keys: "~*"
        channels: "&*"
```


Secondly, i tried with mounting ACL file as volume like this.

```
architecture: replication
sentinel:
  enabled: true
  downAfterMilliseconds: 5000
  failoverTimeout: 30000
auth:
  enabled: true
  acl:
    enabled: true
    existingSecret: "redis-password"
    existingSecretPasswordKey: "redis-password"
    sentinel: true
      extraVolumes:
        - name: redis-acl-list
          secret:
            secretName: redis-acl-list
      extraVolumeMounts:
        - name: redis-acl-list
          readOnly: true
          subPath: users.acl
          mountPath: "/opt/bitnami/etc/redis/users.acl"
```

But the error about `AUTH failed: WRONGPASS invalid username-password pair or user is disabled.`

error persists.

**Comment by JakobStadlhuber** [comment]
@fmulero you mentioned workaround does not work I still got the error
> * Setting a password in the value `auth.password`
> * Creating your own redis secret and setting the values  `auth.existingSecret` and `auth.existingSecretPasswordKey`

**Comment by fmulero** [comment]
Hi @JakobStadlhuber, Could you share the values you are testing?

**Comment by JakobStadlhuber** [comment]
```yaml

stage: Dev
redis:
  architecture: replication
  global:
    defaultStorageClass: "managed-csi-premium"
  sentinel:
    enabled: true
  image:
    tag: 7.4.2-debian-12-r6
  auth:
    enabled: true
    existingSecret: redis-secrets
    existingSecretPasswordKey: password
#    acl:
#      enabled: true
#      sentinel: true
#      users:
#       - username: "appsmith"
#         password: REDIS_APPSMITH_SECRET
#         valueFrom:
#           secretKeyRef:
#             name: redis-secrets
#             key: REDIS_APPSMITH_SECRET
#         enabled: "on"
#         commands: "+@all"
#         keys: "~db1:*"
#         channels: "&*"
#       - username: "user2"
#         password: REDIS_WINKKAI_SECRET
#         valueFrom:
#           secretKeyRef:
#             name: redis-secrets
#             key: REDIS_WINKKAI_SECRET
#         enabled: "on"
#         commands: "+@all"
#         keys: "~db2:*"
#         channels: "&*"
  metrics:
    enabled: true
    podAnnotations:
      #prometheus.io/path: "/scrape"
      prometheus.io/port: "9121"
      prometheus.io/scrape: "true"

```

**Comment by JakobStadlhuber** [comment]
Comment in the part of acl

**Comment by fmulero** [comment]
Yes, definitively my previous suggestion does not apply in your case.

I think, I understood what you are trying to do, but you are mixing different concepts here. First of all the schema supported by the `redis.acl.users` value is this one (any other other value added will be ignored): https://github.com/bitnami/charts/blob/3e8ed41b493b1c92d2dea76d09e5e63c39a006e3/bitnami/redis/values.yaml#L182-L188

Those values will be used to build the [configmap containing the ACL configuration](https://github.com/bitnami/charts/blob/3e8ed41b493b1c92d2dea76d09e5e63c39a006e3/bitnami/redis/templates/configmap.yaml#L51-L64), so the `valueFrom.secretKeyRef` (used in container env vars) does not make sense here.

Said that, I think the password value can be "templated" to allow things like this:
```yaml
acl:
  users:
    - username: "appsmith"
       password: "{{ (lookup "v1" "Secret" "mynamespace" "redis-secrets").data.REDIS_APPSMITH_SECRET}}"
       enabled: "on"
       commands: "+@all"
       keys: "~db1:*"
       channels: "&*"
```

That could be a nice feature, would you like to contribute by creating a PR? We will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
