### ISSUE TITLE
etcd chart not idempotent(?)

### ISSUE THREAD

**Issue by niclan** [bitnami/charts#32498]
### Name and Version

bitnami/etcd 11.1.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Helm deploying bitnami/etcd to EKS
2. Command: `helm upgrade --install --force --namespace "ops-staging" --values=values.yaml vault-etcd "oci://registry-1.docker.io/bitnamicharts/etcd" --version 11.1.5`
3. Everything comes up nicely, but making a change to values.yaml (or not) and wanting to redo the deployment:
4. `helm upgrade --install --force --namespace "ops-staging" --values=values.yaml vault-etcd "oci://registry-1.docker.io/bitnamicharts/etcd" --version 11.1.5`

Errs:
```diff
Pulled: registry-1.docker.io/bitnamicharts/etcd:11.1.5
Digest: sha256:16a80b523db657aa81d8abbbfe8d9074c41d2764c33af21a17f8456734f55b1d
Error: UPGRADE FAILED: failed to replace object: PersistentVolumeClaim "vault-etcd-snapshotter" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests and volumeAttributesClassName for bound claims
  core.PersistentVolumeClaimSpec{
        AccessModes:      {"ReadWriteMany"},
        Selector:         nil,
        Resources:        {Requests: {s"storage": {i: {...}, Format: "BinarySI"}}},
-       VolumeName:       "pvc-618e256d-9ef1-453f-8c84-a4da8d86900d",
+       VolumeName:       "",
        StorageClassName: &"efs-shared",
        VolumeMode:       &"Filesystem",
        ... // 3 identical fields
  }
```

5. Does not help to uninstall and then reinstall either.

### Are you using any custom parameters or values?

I have this in values.yaml:

```yaml
# this is the token for the test cluster - the production token is
# given on the helm command line.
initialClusterToken: beeNgoo3

replicaCount: 3

persistence:
  enabled: true
  storageClass: "efs-shared"
  accessModes:
    - ReadWriteMany
  size: 32Gi

disasterRecovery:
  enabled: true
  snapshotHistoryLimit: 3
  
  pvc:
    storageClassName: "efs-shared"
    size: 32Gi

preUpgradeJob:
  enabled: false

networkPolicy:
  # This enforces only access from pods with the right labels.
  # Whatever that is.
  allowExternal: false

auth:
  peer:
    secureTransport: true
    useAutoTLS: true
    
  # Not enableling client security - vault will only send encrypted
  # traffic to the etcd cluster anyway and the "allowExternal" network
  # config will prevent any other traffic.

metrics:
  enabled: true
  useSeparateEndpoint: true
```

### What is the expected behavior?

Expected to be able to install/update the chart.

### What do you see instead?

Error message about "vault-etcd-snapshotter" PVC attribute being immutable.
