### ISSUE TITLE
[bitnami/airflow] Liveness of Scheduler and Worker failed

### ISSUE THREAD

**Issue by hintdesk** [bitnami/charts#32492]
### Name and Version

bitnami/airflow 22.7.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Completely new install of airflow on K8s Cluster with command "helm install oci://***/airflow"

### Are you using any custom parameters or values?

Only some of parameters are set
```
loadExamples: false
ingress:
  enabled: true
  hostname: xxx
  extraTls:
    - hosts:
        - xxx
      secretName: xxx-tls
dags:
  enabled: true
  repositories:
    - repository: xxx/airflow.git
      name: xxx_airflow
      branch: main
      path: /dags
```
### What is the expected behavior?

Liveness Probe should work

### What do you see instead?

Liveness probe failed

<img width="691" alt="Image" src="https://github.com/user-attachments/assets/89c0195a-8760-4e9a-b991-08b74ce531fb" />

### Additional information

Both scheduler and worker pods have problem with liveness probe with fresh installation.
I don't see any Error log in scheduler and worker pods. The pods work well but some how liveness probe command failed.
I think Liveness Probe command is somehow syntax broken.

I have temporarily disabled livenessProbe of scheduler and worker as a solution from keeping the pods get restarting.
```
scheduler:
  livenessProbe:
    enabled: false
worker:
  livenessProbe:
    enabled: false
```
