### ISSUE TITLE
[parse/25.0.1] Helm install failed: error while running post render on files: map[string]interface {}(nil)

### ISSUE THREAD

**Issue by AsoTora** [bitnami/charts#32508]
### Name and Version

parse/25.0.1

### What architecture are you using?

None

### What steps will reproduce the bug?

K8S installation of Parse helm chart with FluxCD fails on the kustomize post-renderer step:

### Are you using any custom parameters or values?

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: parse
  namespace: playground
spec:
  releaseName: parse
  chart:
    spec:
      chart: parse
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: infra-tools
      version: "25.x.x"
  install:
    crds: CreateReplace
  interval: 1h
  values: # https://github.com/bitnami/charts/blob/parse/25.0.1/bitnami/parse/values.yaml
    server:
      enabled: true
      service:
        type: ClusterIP
        ports:
          http: 1337
    dashboard:
      enabled: true
      service:
        type: ClusterIP
        ports:
          http: 80
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
      dashboard:
        hostname: parse-dashboard
      server:
        hostname: parse-server
```

### What do you see instead?

Error I get:
```
Helm install failed for release playground/parse with chart parse@25.0.1: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 173: mapping key "resources" already defined at line 144
```
### Additional information

I assume this is some kustomize bug, but it only comes up when service+ingress values are presented, when installing the same chart with generic values everything works.

**Comment by AsoTora** [comment]
looks like the helm chart generates 2 resource blocks: one comes from the resourcePreset, second from the resources:{} block.

input values:

```yml
server:
  enabled: true
  service:
    type: ClusterIP
    ports:
      http: 1337
dashboard:
  enabled: true
  service:
    type: ClusterIP
    ports:
      http: 80

mongodb:
  enabled: false
```

output of `helm template parse-24.1.4.tgz --values values.yml > output.yml`

```yml
---
# Source: parse/templates/dashboard-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-parse-dashboard
  namespace: "playground"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: parse
    app.kubernetes.io/version: 6.1.0
    helm.sh/chart: parse-24.1.4
    app.kubernetes.io/component: dashboard
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: parse
      app.kubernetes.io/component: dashboard
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: parse
        app.kubernetes.io/version: 6.1.0
        helm.sh/chart: parse-24.1.4
        app.kubernetes.io/component: dashboard
    spec:
      serviceAccountName: release-name-parse-server
      
      automountServiceAccountToken: false
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: release-name
                    app.kubernetes.io/name: parse
                    app.kubernetes.io/component: dashboard
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      initContainers:
        - name: create-default-config
          image: docker.io/bitnami/parse-dashboard:6.1.0-debian-12-r0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          command:
            - /bin/bash
          args:
            - -ec
            - |
              #!/bin/bash

              # HACK: We need to create this file in the emptyDir volume to make it writable
              # in the
              touch /default-conf/config.json
          resources:
            limits:
              cpu: 150m
              ephemeral-storage: 2Gi
              memory: 192Mi
            requests:
              cpu: 100m
              ephemeral-storage: 50Mi
              memory: 128Mi
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
            - name: empty-dir
              mountPath: /default-conf
              subPath: app-default-conf-dir
      containers:
        - name: parse-dashboard
          image: docker.io/bitnami/parse-dashboard:6.1.0-debian-12-r0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: PARSE_DASHBOARD_USER
              value: user
            - name: PARSE_DASHBOARD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-name-parse
                  key: parse-dashboard-password
            - name: PARSE_HOST
              value: "127.0.0.1"
            - name: PARSE_USE_HOSTNAME
              value: "no"
            - name: PARSE_PORT_NUMBER
              value: "1337"
            - name: PARSE_PROTOCOL
              value: "http"
            - name: PARSE_APP_ID
              value: "myappID"
            - name: PARSE_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: release-name-parse
                  key: master-key
            - name: PARSE_DASHBOARD_APP_NAME
              value: "MyDashboard"
            - name: PARSE_FORCE_OVERWRITE_CONF_FILE
              value: "yes"
          resources:
            limits:
              cpu: 150m
              ephemeral-storage: 2Gi
              memory: 192Mi
            requests:
              cpu: 100m
              ephemeral-storage: 50Mi
              memory: 128Mi
          ports:
            - name: http-dashboard
              containerPort: 4040
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 240
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            tcpSocket:
              port: http-dashboard
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /
              port: http-dashboard
          resources:
            limits:
              cpu: 150m
              ephemeral-storage: 2Gi
              memory: 192Mi
            requests:
              cpu: 100m
              ephemeral-storage: 50Mi
              memory: 128Mi
          volumeMounts:
            - name: empty-dir
              mountPath: /bitnami/parse-dashboard
              subPath: app-data-dir
            - name: empty-dir
              mountPath: /opt/bitnami/parse-dashboard/config.json
              subPath: app-default-conf-dir/config.json
            - name: empty-dir
              mountPath: /opt/bitnami/parse-dashboard/tmp
              subPath: app-tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/parse-dashboard/logs
              subPath: app-logs-dir
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
      volumes:
        - name: empty-dir
          emptyDir: {}
---
```

which breaks kustomize
