### ISSUE TITLE
Airflow Chart syntax error

### ISSUE THREAD

**Issue by YaphetKG** [bitnami/charts#32581]
### Name and Version

bitnami/airflow 22.7.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. When  providing setupDBJob.resources , the actual value is inject to templates/setup-db-job.yaml  but the indentation defined in the file is incorrect https://github.com/bitnami/charts/blob/5f50d43900bd5305b9d83ceddd17354081109641/bitnami/airflow/templates/setup-db-job.yaml#L49

### Are you using any custom parameters or values?
```yaml
setupDBJob:
  resources:
    limits:
      cpu: 1
      memory: 1Gi
      ephemeral-storage: 256Gi
```
### What is the expected behavior?

The Setup job template should not generate syntax error, and the job should run with the resources defined.

### What do you see instead?

syntax error :
```
Error: UPGRADE FAILED: YAML parse error on .../airflow/templates/setup-db-job.yaml: error converting YAML to JSON: yaml: line 136: mapping values are not allowed in this context
```
