### ISSUE TITLE
"Error: secret "kafka-kraft" not found"

### ISSUE THREAD

**Issue by xilokaine** [bitnami/charts#32606]
### Name and Version

bitnami/kafka:32.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I get the same configuration as 31.5.0 with new images. A complete fresh installation, and it fails with a `kafka-kraft  secret not found !`
It should normally be created if the clusterId is not set and it's my situation. 
Deleted the pvc ....

### What do you see instead?

"Error: secret "kafka-kraft" not found"

**Comment by jgresty** [comment]
It appears the kafka-kraft secret is inside of the `{{- if (include "kafka.createSaslSecret" .) }}` block, setting both `listeners.controller.protocol` and `listeners.interbroker.protocol` to PLAINTEXT will not create this secret however it will still be referenced in the broker statefulset env vars

**Comment by richardr1126** [comment]
Also getting this issue using in 4.0.0:
```
listeners:
  client:
    protocol: SSL
    name: CLIENT
  controller:
    protocol: SSL
  interbroker:
    protocol: SSL
  external:
    protocol: SSL
    name: EXTERNAL

tls:
  enabled: true
  type: PEM
  pemChainIncluded: true
  sslClientAuth: none
```
