### ISSUE TITLE
[bitnami/schema-registry] Schema Registry Pod Running but Cannot Access via HTTPS | not accessibe via LoadBalance

### ISSUE THREAD

**Issue by shivam-cse** [bitnami/charts#32616]
### Name and Version

bitnami /schema-registry 24.0.0

### What architecture are you using?

None

### What steps will reproduce the bug?

I have deployed the Bitnami Schema Registry Helm chart on my GKE cluster. The pod is running, but I am unable to access it via HTTPS.

My strimzi kafka cluster deployed in 'kafka' namespace.

I am using the below cmd to install the helm chart in 'schema-registry' namespace
`helm upgrade confluent-schema-registry oci://registry-1.docker.io/bitnamicharts/schema-registry -n schema-registry -f values.yaml --install --create-namespace`

I have generated the JKS files using the following steps

**step-1.  create the kafkaUser (as we are using the strimzi kafka cluster)**
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: schema-registry-user #  Name of the Kafka user, confluent-schema-registry
  namespace: kafka #  Namespace where the Kafka cluster is deployed
  labels:
    strimzi.io/cluster: my-kafka-poc-tf  #  Links this user to the Kafka cluster
spec:
  authentication:
    type: tls  #  Enforces TLS authentication (certificate-based access)
    # type: scram-sha-512  #  Enforces SCRAM-SHA-512 authentication (username/password-based access)
  authorization:
    type: simple  #  Enables ACL-based access control
    acls:
      # ✅ Grant Schema Registry full access to the "registry-schemas" topic
      - resource:
          type: topic
          name: _schemas
          patternType: literal
        operation: All  #  Allows full access (Read, Write, Delete, Describe, etc.)
        type: allow

      # ✅ Allow Schema Registry to create and manage its consumer groups
      - resource:
          type: group
          name: schema-registry
          patternType: prefix
        operation: All  #  Allows full control of consumer groups starting with "schema-registry"
        type: allow

      # ✅ Allow Schema Registry to read Kafka's consumer offsets
      - resource:
          type: topic
          name: __consumer_offsets
          patternType: literal
        operation: Describe  #  Only allows reading offset metadata (not writing)
        type: allow

```

step-2: Generate the following JKS  files from kafkaUser secret (In step-1)
 schema-registry.truststore.jks, schema-registry-0.truststore.jks
```bash
#!/bin/bash

set -e  # Exit immediately if any command fails
set -o pipefail  # Catch errors in piped commands

# Define variables
NAMESPACE="kafka"
USER_SECRET="schema-registry-user"
CA_SECRET="my-kafka-poc-tf-cluster-ca-cert"

# Retrieve secrets
userCrtBase64=$(kubectl get secret "$USER_SECRET" -n "$NAMESPACE" -o jsonpath='{.data.user\.crt}')
userKeyBase64=$(kubectl get secret "$USER_SECRET" -n "$NAMESPACE" -o jsonpath='{.data.user\.key}')
caCrtBase64=$(kubectl get secret "$CA_SECRET" -n "$NAMESPACE" -o jsonpath='{.data.ca\.crt}')

# Decode Base64
userCrt=$(echo "$userCrtBase64" | base64 --decode)
userKey=$(echo "$userKeyBase64" | base64 --decode)
caCrt=$(echo "$caCrtBase64" | base64 --decode)

# Define paths for temporary files
userCrtPath="user.crt"
userKeyPath="user.key"
caCrtPath="ca.crt"
p12Path="user.p12"
jksPath="schema-registry-0.keystore.jks"
truststorePath="schema-registry.truststore.jks"

# Save decoded certificates to files
echo "$userCrt" > "$userCrtPath"
echo "$userKey" > "$userKeyPath"
echo "$caCrt" > "$caCrtPath"

# Ensure cleanup on exit
trap 'rm -f "$userCrtPath" "$userKeyPath" "$caCrtPath" "$p12Path"' EXIT

# Convert user.crt and user.key to PKCS12 format
openssl pkcs12 -export -in "$userCrtPath" -inkey "$userKeyPath" -out "$p12Path" -password pass:changeit -name schema-registry-user

# Create a Java KeyStore (JKS) from the PKCS12 file
keytool -importkeystore -srckeystore "$p12Path" -srcstoretype pkcs12 -destkeystore "$jksPath" -deststoretype jks -srcstorepass changeit -deststorepass changeit

# Create a Java TrustStore and import ca.crt
keytool -import -file "$caCrtPath" -keystore "$truststorePath" -storepass changeit -noprompt -alias ca-cert

# Clean up temporary files
# rm -f "$userCrtPath" "$userKeyPath" "$caCrtPath" "$p12Path"

# Display success message
echo "Java KeyStore ($jksPath) and TrustStore ($truststorePath) created successfully."
```
 
step-3: Generate following jks files from the kafka-cluster certs
ssl.truststore.jks, ssl.keystore.jks

```bash
#!/bin/bash

# Retrieve ca.key from the secret 'my-kafka-poc-tf-cluster-ca'
caKeyBase64=$(kubectl get secret my-kafka-poc-tf-cluster-ca -n kafka -o jsonpath='{.data.ca\.key}')
caKey=$(echo "$caKeyBase64" | base64 -d)

# Retrieve ca.crt from the secret 'my-kafka-poc-tf-cluster-ca-cert'
caCrtBase64=$(kubectl get secret my-kafka-poc-tf-cluster-ca-cert -n kafka -o jsonpath='{.data.ca\.crt}')
caCrt=$(echo "$caCrtBase64" | base64 -d)

# Save ca.crt and ca.key to temporary files
caCrtPath="ca.crt"
caKeyPath="ca.key"
echo "$caCrt" > "$caCrtPath"
echo "$caKey" > "$caKeyPath"

# Save the provided OpenSSL configuration to a file
cat <<EOF > schema_registry.cnf
[req]
distinguished_name = req_distinguished_name
req_extensions = req_ext

[req_distinguished_name]
countryName                     = Country Name (2 letter code)
countryName_default             = IN
stateOrProvinceName             = State or Province Name (full name)
stateOrProvinceName_default     = mystate
localityName                    = Locality Name (eg, city)
localityName_default            = mycity
0.organizationName              = Organization Name (eg, company)
0.organizationName_default      = my-self
organizationalUnitName          = Organizational Unit Name (eg, section)
organizationalUnitName_default  = Engineering
commonName                      = Common Name (e.g. server FQDN or YOUR name)
commonName_default              = schema-registry.default.svc
commonName_max                  = 64

[req_ext]
subjectAltName = @alt_names

[alt_names]
DNS.1 = schema-registry.default.svc
DNS.2 = schema-registry-0
DNS.3 = schema-registry-0.default
DNS.4 = schema-registry-0.default.svc
EOF

# Create a CSR using OpenSSL
openssl req -new -out server.csr -keyout server.key -config schema_registry.cnf -batch -nodes

# Sign the CSR with the CA certificate
openssl x509 -req -in server.csr -CA "$caCrtPath" -CAkey "$caKeyPath" -CAcreateserial -out server.crt -days 365 -extensions req_ext -extfile schema_registry.cnf

# Convert the certificate and key to PKCS12 format
openssl pkcs12 -export -in server.crt -inkey server.key -out server.p12 -password pass:changeit -name schema-registry

# Create a Java KeyStore (JKS) from the PKCS12 file
keytool -importkeystore -srckeystore server.p12 -srcstoretype pkcs12 -destkeystore ssl.keystore.jks -deststoretype jks -srcstorepass changeit -deststorepass changeit

# Create a Java TrustStore and import the CA certificate
keytool -import -file "$caCrtPath" -keystore ssl.truststore.jks -storepass changeit -noprompt -alias ca-cert

# Clean up temporary files
rm -f schema_registry.cnf server.csr server.crt server.key server.p12 "$caCrtPath" "$caKeyPath" ca.srl

# Display success message
echo "Certificate, Key, JKS, and TrustStore created successfully."
```

step-4: create the secret in 'schema-registry' namespace
```
kubectl create secret generic schema-registry-user-jks -n schema-registry \
--from-file=./schema-registry.truststore.jks \
--from-file=./schema-registry-0.keystore.jks \
--from-file=./ssl.truststore.jks \
--from-file=./ssl.keystore.jks
```

### Are you using any custom parameters or values?

**I have used this values.yaml file** 
```yaml
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
clusterDomain: cluster.local

## @section Schema Registry parameters
image:
  registry: docker.io
  repository: bitnami/schema-registry
  tag: 7.9.0-debian-12-r0
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false

command: []
args: []
podLabels: {}

configuration: |-
  listeners = https://0.0.0.0:8081
  inter.instance.protocol = https
  kafkastore.bootstrap.servers = SSL://my-kafka-poc-tf-kafka-bootstrap.kafka.svc:9093
  host.name = schema-registry
  kafkastore.topic = _schemas
  kafkastore.security.protocol = SSL
  avro.compatibility.level = forward

  kafkastore.ssl.keystore.location = /opt/bitnami/schema-registry/certs/schema-registry.keystore.jks
  kafkastore.ssl.keystore.password = changeit
  kafkastore.ssl.truststore.location = /opt/bitnami/schema-registry/certs/schema-registry.truststore.jks
  kafkastore.ssl.truststore.password = changeit

  ssl.keystore.location = /opt/bitnami/schema-registry/certs/ssl.keystore.jks
  ssl.keystore.password = changeit
  ssl.truststore.location = /opt/bitnami/schema-registry/certs/ssl.truststore.jks
  ssl.truststore.password = changeit

  ssl.key.password=changeit
  debug = true

existingConfigmap: ""
log4j: {}
existingLog4jConfigMap: ""

## Authentication parameteres
auth:
  tls:
    enabled: true
    jksSecret: "schema-registry-user-jks"
    keystorePassword: "changeit"
    truststorePassword: "changeit"
    ## Valid options: NONE, REQUESTED, over REQUIRED
    clientAuthentication: NONE
  
  ## Parameters to configure authentication with kafka brokers
  kafka:
    jksSecret: "schema-registry-user-jks"
    tlsEndpointIdentificationAlgorithm: ""
    keystorePassword: "changeit"
    truststorePassword: "changeit"
    saslMechanism: PLAIN # SCRAM-SHA-512

listeners: https://0.0.0.0:8081
## Valid options: none, backward, backward_transitive, forward, forward_transitive, full, or full_transitive
avroCompatibilityLevel: backward
extraEnvVarsCM: ""
extraEnvVarsSecret: ""

## @section Schema Registry statefulset parameters
replicaCount: 1

affinity: {}
nodeSelector: {}
tolerations: []
podAnnotations: {}
priorityClassName: ""

podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  supplementalGroups: []
  fsGroup: 1001

containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"

resourcesPreset: "small"
## Schema Registry containers' resource requests and limits.
resources: {}
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 1
  periodSeconds: 20
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 1
  periodSeconds: 20
  failureThreshold: 6
  successThreshold: 1
startupProbe:
  enabled: false
## Extra volumes
extraVolumes: []
# # extraVolumeMounts: []
extraVolumeMounts:
  - name: empty-dir
    mountPath: /opt/bitnami/schema-registry/certs/
    subPath: app-certs

## Schema Registry Pod Disruption Budget configuration
pdb:
  create: false
  minAvailable: 1
  maxUnavailable: ""

## Schema Registry Autoscaling parameters.
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 11
  targetCPU: ""
  targetMemory: ""
  customPodMetrics: []

service:
  type: LoadBalancer
  ports:
    http: 8081
  nodePorts:
    http: "30001"
 
  clusterIP: ""
  
  externalTrafficPolicy: Cluster
 
  loadBalancerIP: ""
 
  loadBalancerSourceRanges: []
  
  annotations: {}
  
  labels: {}
  
  extraPorts: []
  
  sessionAffinity: None
  
  sessionAffinityConfig: {}
 
  headless:
    annotations: {}

ingress:
  enabled: false
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: schema-registry.local
  ingressClassName: ""
  path: /
  annotations: {}
  tls: false
  ## @param ingress.selfSigned Create a TLS secret for this ingress record using self-signed certificates generated by Helm
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraTls: []
  secrets: []
  extraRules: []

## @section RBAC parameters
serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: true

## @section Kafka chart parameters
kafka:
  enabled: false

externalKafka:
  brokers:
    - SSL://my-kafka-poc-tf-kafka-bootstrap.kafka.svc:9093
  listener:
    # protocol: SASL_SSL
    protocol: SSL
  sasl:
    user: ""
    password: ""
    existingSecret: ""
```

### What is the expected behavior?

It seems everything is in running status.
```console
$ k get all -n schema-registry
NAME                              READY   STATUS    RESTARTS   AGE
pod/confluent-schema-registry-0   0/1     Running   0          31m

NAME                                         TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)          AGE
service/confluent-schema-registry            LoadBalancer   x.x.x.x   x.x.x.x  8081:30001/TCP   31m
service/confluent-schema-registry-headless   ClusterIP      None            <none>          8081/TCP         31m

NAME                                         READY   AGE
statefulset.apps/confluent-schema-registry   0/1     31m
```

### What do you see instead?

Now trying to access the schema-registry server by the extrnal IPs

First, I download the certs generated by the kafkaUser in step-1 and then make the following call

```console
$ curl -X  GET --cacert ca.crt --cert user.crt --key user.key  https://x.x.x.x:8081/subjects
      Got the errors from curl command: curl: (7) Failed to connect to x.x.x.x port 8081 after 312 ms: 
      Connection refused
```

Questions:
Are the certificates I’m using correct when calling https://x.x.x.x:8081/subjects? 
Did I make any mistakes in my steps?

**=====================UPDATED==========================

I verified that accessing the Schema Registry works via `kubectl port-forward`, but requests to the external IP configured via a LoadBalancer in `values.yaml` fail.  

$ kubectl port-forward svc/confluent-schema-registry 8081:8081 -n schema-registry  
$ curl -k https://localhost:8081/config  
{"compatibilityLevel":"FORWARD"}  

This suggests an issue with the service configuration in `values.yaml`.  

1. Review the service section in `values.yaml`.  
2. Specify which certificates are required for HTTPS requests to the external IP (e.g., from `kafkaUser` or self-generated).  
3. Provide guidance to restrict client access (e.g., allowing producers/consumers to read and admins to write/update schemas on schema-registry server).**
