### ISSUE TITLE
[bitnami/mongodb] Mongo arbiter startupProbe script not present in image

### ISSUE THREAD

**Issue by 4SH-gaupee** [bitnami/charts#32639]
### Name and Version

bitnami/mongodb 15.6.26

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Using the default value chart and only turning on the startupProbe for arbiter

```yaml
  ## MongoDB(&reg;) Arbiter pods' startup probe. Evaluated as a template.
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
  ## @param arbiter.startupProbe.enabled Enable startupProbe
  ## @param arbiter.startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
  ## @param arbiter.startupProbe.periodSeconds Period seconds for startupProbe
  ## @param arbiter.startupProbe.timeoutSeconds Timeout seconds for startupProbe
  ## @param arbiter.startupProbe.failureThreshold Failure threshold for startupProbe
  ## @param arbiter.startupProbe.successThreshold Success threshold for startupProbe
  ##
  startupProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 30
```
```
helm install bitnami/mongodb --version=15.6.26 -f default.yaml --generate-name
```

### What is the expected behavior?

Arbiter start properly 

### What do you see instead?

```
On the arbiter pod :
Startup probe failed: OCI runtime exec failed: exec failed: unable to start container process: exec: "/bitnami/scripts/startup-probe.sh": stat /bitnami/scripts/startup-probe.sh: no such file or directory: unknown
```

When connection to the pod, there's only `/bitnami/mongodb/data` no `scripts` directory.
