### ISSUE TITLE
Headless service targetPort does not match statefulset (Sentinel enabled) containerPort

### ISSUE THREAD

**Issue by TimMartinRiG147** [bitnami/charts#32646]
### Name and Version

bitnami/valkey 2.4.7

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Deploy Valkey with a 3 node cluster with Sentinel enabled. The valkey-headless service will have the below config:

```yaml
 - name: tcp-redis
    port: 6379
    targetPort: redis
```

while the statefulset will have the following config:

```yaml
ports:
  - name: valkey
    containerPort: 6379
```

the targetport and name should match

### Are you using any custom parameters or values?

```yaml
  auth:
    enabled: false
    sentinel: false
    password: ""
    existingSecret: ""
    existingSecretPasswordKey: ""
    usePasswordFiles: false
    usePasswordFileFromSecret: false

  sentinel:
    enabled: true
```

### What is the expected behavior?

The TargetPort and ContainerPort should match, either `valkey` or `redis`. Or have an option to change and not be hardcoded. 

### What do you see instead?

The TargetPort and ContainerPort are different and are not able to change
