### ISSUE TITLE
[bitnami/nginx] Default values for ingress hostname creates redundant ingress rule

### ISSUE THREAD

**Issue by KonstantinKlimov** [bitnami/charts#3264]
**Which chart**:
nginx 6.0.2

**Describe the bug**
The default value for ingress hostname in values.yaml doesn't allow to create a single ingress rule with a path.

**To Reproduce**
1. Use the following ingress config
```
    ingress:
      hosts:
      - name: my-domain.com
        path: /path
```
2. Generate helm templates based on the config

**Expected behavior**
Generated Ingress template should have the following rules block that contains only one rule:
```
spec:
  rules:
    - host: my-domain.com
      http:
        paths:
          - path: /path
            backend:
              serviceName: "serviceName"
              servicePort: http
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v3.1.0
```

- Output of `kubectl version`:

```
v1.15.5
```
**Additional context - Actual behavior**
It creates the following snippet:
```
spec:
  rules:
    - host: example.local
      http:
        paths:
          - path: /
            backend:
              serviceName: "serviceName"
              servicePort: http
    - host: my-domain.com
      http:
        paths:
          - path: /path
            backend:
              serviceName: "serviceName"
              servicePort: http
```
