### ISSUE TITLE
[bitnami/apisix] APISIX chart 4.2.0 fails to deploy

### ISSUE THREAD

**Issue by reinvantveer** [bitnami/charts#32643]
### Name and Version

bitnami/apisix:4.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. We're using ArgoCD to deploy, using helm charts
2. We're using the following simplified Application resource to deploy APISIX:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: auth
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: apisix
    targetRevision: "4.2.0"
```

But the `api-gateway-etcd-pre-upgrade` startup job fails with the following:

```
MountVolume.SetUp failed for volume "etcd-jwt-token" : secret "api-gateway-etcd-jwt-token" not found
```

It appears it is waiting on the jwt secret that is created downstream in the deployment procedure, but it is not deployed until the pre-upgrade job is finished.

### Are you using any custom parameters or values?

See Application yaml

### What is the expected behavior?

A fully deployed APISIX application

### What do you see instead?

```
MountVolume.SetUp failed for volume "etcd-jwt-token" : secret "api-gateway-etcd-jwt-token" not found
```

![Image](https://github.com/user-attachments/assets/c9bca7d2-d3ac-4d9e-a525-064f9c883565)
