### ISSUE TITLE
[bitnami/minio] Minio distributed error Content-Length

### ISSUE THREAD

**Issue by CarTerr** [bitnami/charts#32666]
### Name and Version

bitnami/minio 15.0.3

### What architecture are you using?

None

### What steps will reproduce the bug?

my valuse-test.yaml

```
image:
  registry: docker.io
  repository: bitnami/minio
  tag: 2025.2.7-debian-12-r0

mode: distributed

auth:
  rootUser: admin
  rootPassword: "Rdflhfnec2025"

ingress:
  enabled: true
  hostname: minio.tests.com
  tls: true

apiIngress:
  enabled: true
  hostname: api.minio.tests.com
  tls: true

persistence:
  enabled: true
  storageClass: "glusterfs-retain"
  size: 100Gi
```

when run command in one of pods

```
touch /tmp/1.txt
truncate -s 12191 /tmp/1.txt
mc put /tmp/1.txt myminio/123 --debug
```
I get 
`
<ERROR> unable to upload. You did not provide the number of bytes specified by the Content-Length HTTP header.
`
[debug.txt](https://github.com/user-attachments/files/19504462/debug.txt)

### What do you see instead?

![Image](https://github.com/user-attachments/assets/4dd2291e-aa69-4e51-8d37-3dcd9920cca6)

![Image](https://github.com/user-attachments/assets/28f3c3ad-cfbb-4cc2-be71-f0498631fe47)
