### ISSUE TITLE
[bitnami/rabbitmq] password regenerated on pod restart regardless of values file/enviroment variables

### ISSUE THREAD

**Issue by steinad** [bitnami/charts#3271]
**Which chart**:
bitnami/rabbitmq 7.5.6 (also 6.25.1)

**Describe the bug**
After deployment, if the pod restarts (due to readiness/liveliness probe, etc) the values file/environment variable specified username is created, but the password is regenerated, causing applications to fail to authenticate.

**To Reproduce**

`helm install rabbitmq bitnami/rabbitmq -f values.yaml`

with values.yaml:

```yaml
rabbitmq:
  nameOverride: rabbitmq
  auth:
    username: admin
    password: password
    erlangCookie: 'secretcookie'
  persistence:
    enabled: false
```

**Expected behavior**

rabbitmq should always use the values from the values file.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.6-1+64f53401f200a7", GitCommit:"64f53401f200a7a5977955a74ad3f997302774ca", GitTreeState:"clean", BuildDate:"2020-07-15T19:59:02Z", GoVersion:"go1.14.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

I am testing this currently in microk8s, but I have seen this in a rancher launched cluster as well.

I can exec into the container and run `rabbitmqctl change_password admin password` and the clients can authenticate again.

**Edit:** here's the log output. The container restart occurs at line 10 - you can see the time jump
[rabbitmq.log](https://github.com/bitnami/charts/files/4996645/rabbitmq.log)

**Comment by marcosbc** [comment]
@steinad The problem is you have disabled persistence:

```
  persistence:
    enabled: false
```

So between a pod recreation, no data will be saved, so if you had changed the password it will be reset to "password" again. That is expected until you enable persistence.

**Comment by marcosbc** [comment]
Just in case, I've tried to follow these steps in case there could be an issue setting the user credentials in a second run to the value provided in your values.yaml.

1. created a deployment with the values you used previously (i.e. password "password" and without persistence)
2. deleted the pod
3. the access still works with the "admin"/"password" credentials

Which makes sense, since a non-persisted run would act as a new deployment.

**Comment by steinad** [comment]
Perhaps I was unclear about this, but the storage is **not** being reset, and the environment variables (including `RABBITMQ_USERNAME=admin` and `RABBTMQ_PASSWORD=password` are not changing. After the container restarts, the password is not being set to `password`, but I can manually change the password to `password`.

From the attached logs after the container restart:
```
2020-07-29T14:04:51.350252309-04:00  18:04:51.34 INFO  ==> ** Starting RabbitMQ setup **
2020-07-29T14:04:51.361133065-04:00  18:04:51.35 INFO  ==> Validating settings in RABBITMQ_* env vars..
2020-07-29T14:04:51.380524265-04:00  18:04:51.37 INFO  ==> Initializing RabbitMQ...
2020-07-29T14:04:51.411255792-04:00  18:04:51.40 INFO  ==> Persisted data detected. Restoring...
2020-07-29T14:04:51.421726853-04:00  18:04:51.40 INFO  ==> ** RabbitMQ setup finished! **
```

**Comment by steinad** [comment]
Here's another post-restart log, this time with `image.debug: true`

[rabbitmq-reboot.log](https://github.com/bitnami/charts/files/5002970/rabbitmq-reboot.log)

And also a `kubectl describe` on the pod post-restart.

[rabbitmq-reboot-describe.txt](https://github.com/bitnami/charts/files/5002983/rabbitmq-reboot-describe.txt)

**Comment by marcosbc** [comment]
I think I know what is the issue here. It looks like we are using "rabbitmq:" as a top-level entry:

```yaml
rabbitmq:
  nameOverride: rabbitmq
  auth:
    username: admin
    password: password
    erlangCookie: 'secretcookie'
  persistence:
    enabled: false
```

However, when you install the `bitnami/rabbitmq` chart it should be like this:

```yaml
nameOverride: rabbitmq
auth:
  username: admin
  password: password
  erlangCookie: 'secretcookie'
persistence:
  enabled: false
```

That is the reason why it was not picking your password, and why persistence was being enabled anyways.
