### ISSUE TITLE
[bitnami/external-dns] Istio VirtualService support is not working

### ISSUE THREAD

**Issue by Karthik-13** [bitnami/charts#3275]
**Which chart**:
bitnami/external-dns-3.2.5

**Describe the bug**
Istio VirtualService support is not working.

**To Reproduce**
1. Deploy the external-dns chart with following values which enables monitoring istio virtualservices for host entries:
```
sources:
  - service
  - ingress
  - istio-gateway
  - istio-virtualservice
```
2. Monitor the external-dns pod. It will fail to start.
3. See the container logs which throw the following error: 
```time="2020-07-30T10:40:18Z" level=fatal msg="flag parsing error: enum value must be one of service,ingress,node,istio-gateway,cloudfoundry,contour-ingressroute,fake,connector,crd,empty,skipper-routegroup,openshift-route, got 'istio-virtualservice'"```

**Expected behavior**

The external-dns container should run successfully and pickup host entries from Istio virtualservice.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.6", GitCommit:"dd2e5695da88625b190e6b22e9542550ab503a47", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.6", GitCommit:"dd2e5695da88625b190e6b22e9542550ab503a47", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:17:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

The docker image specified in the values.yaml doesnot support the Istio virtualservice source feature. Building the external dns image directly using the code the repository[https://github.com/kubernetes-sigs/external-dns], I was able to successfully deploy external-dns with virtualservice support.

**Comment by javsalgar** [comment]
Hi,

According to https://github.com/helm/charts/pull/22669#issuecomment-666560583

> @Karthik-13 Yep, IMO that's not this charts responsibility. I built off master and pushed to our private registry, the functionality should be available in the next tagged release of external-dns.

As soon as the new tagged version is ready, our automated system will work on updating the chart. So please stay tuned :)

**Comment by carpenike** [comment]
Should this now be resolved with v0.7.3?

**Comment by javsalgar** [comment]
Hi,

Potentially this should be fixed, did you find any issue trying it?

**Comment by javsalgar** [comment]
Hi,

It looks like there are some configuration parameters missing. Did you report it to the external-dns devs?

**Comment by carpenike** [comment]
Not yet -- just started kicking the tires with it. Will check in on that side as well if I can't get it working and update this thread.

**Comment by carpenike** [comment]
Getting this error by default in External-DNS logs:

```
time="2020-08-27T15:40:59Z" level=debug msg="No endpoints could be generated from VirtualService istio-system/kiali"                                                                                                                     time="2020-08-27T15:40:59Z" level=debug msg="No endpoints could be generated from VirtualService kube-system/auth"
```

Adding in the following annotation registers the DNS record successfully:

```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auth
  namespace: kube-system
  annotations:
    external-dns.alpha.kubernetes.io/target: 10.45.10.20
spec:
  hosts:
    - 'auth.holthome.net'
  gateways:
    - istio-system/istio-system-ingress-gateway
  http:
    - match:
        - port: 443
      route:
        - destination:
            port:
              number: 80
            host: oauth2-proxy.kube-system.svc.cluster.local
```

Per FAQ: https://github.com/kubernetes-sigs/external-dns/blob/master/docs/faq.md#user-content-are-other-ingress-controllers-supported

Anyone know if this should this be necessary?
