### ISSUE TITLE
[bitnami/postgresql-ha] storageClassName is rendered twice in volumeClaimTemplates, causing YAML parsing errors

### ISSUE THREAD

**Issue by rlevillain-ops** [bitnami/charts#32776]
### Name and Version

bitnami/postgresql-ha main

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hello !

When setting persistence.storageClass in values.yaml, the postgresql-ha chart renders the storageClassName field twice in the volumeClaimTemplates template file (bitnami/postgresql-ha/templates/postgresql/statefulset.yaml).  

```
   volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
       [...]
      spec:
        accessModes:
        [...]
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{- if .Values.persistence.selector }}
        selector: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.selector "context" $) | nindent 10 }}
        {{- end -}}
        {{- include "common.storage.class" (dict "persistence" .Values.persistence "global" .Values.global) | nindent 8 }}
```
[This PR](https://github.com/bitnami/charts/pull/30993) has added the storageClass set up for PVC :
```
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
```
But hasn't removed 
` {{- include "common.storage.class" (dict "persistence" .Values.persistence "global" .Values.global) | nindent 8 }}`

Rendered with a basic .Values.persistence.storageClass input I get: 

```
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: gp2-retain
        resources:
          requests:
            storage: "1Gi"
        storageClassName: gp2-retain
```

This leads to an invalid YAML manifest (YAMLException: duplicated mapping key - storageClassName - ) . I am still able to deploy (but tools like lens won't parse it).

I understand the global/specific distinction but wouldn't it be preferable to have a fallback mechanism  instead of parallel mentions of storageClassName ? 

### Are you using any custom parameters or values?

.Values.persistence.storageClass= gp2-retain

### What is the expected behavior?

Parsable .yaml file

### What do you see instead?

Errors parsing the yaml file
