### ISSUE TITLE
[bitnami/airflow] Git clone doesn't include submodules

### ISSUE THREAD

**Issue by JKrehling** [bitnami/charts#32786]
### Name and Version

bitnami/airflow

### What architecture are you using?

None

### What steps will reproduce the bug?

https://github.com/bitnami/charts/blob/main/bitnami/airflow/templates/_init_containers_sidecars.tpl#L351 

There are no submodules being pulled with this git clone command.  

Instead of hardcoding everything though I think just adding on the ability to add {{ whatever i want }} would be more robust. 

### Are you using any custom parameters or values?

```
  dags:
  enabled: false
  existingConfigmap: ""
  ## E.g:
  ## repositories:
  ##   - repository: https://github.com/myuser/myrepo
  ##     branch: main
  ##     name: my-dags
  ##     path: /
  ##
```

### What is the expected behavior?

Being able to pull all required submodules etc...

### What do you see instead?

Not pulling submodules
