### ISSUE TITLE
[bitnami/airflow] The Arflow setup-db-job is never created by argocd

### ISSUE THREAD

**Issue by sondn98** [bitnami/charts#32804]
### Name and Version

bitnami/airflow 22.7.2

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I'm deploying Apache Airflow using ArgoCD, both via the Bitnami Helm charts. All Airflow resources are deployed successfully, except for the `setup-db-job`, which is responsible for initializing the Airflow database. The job is not even created.

After investigating, I found that the default annotations helm.sh/hook and helm.sh/hook-delete-policy prevent the job from being created due to ArgoCD's hook management mechanism. Unfortunately, there is no option to remove these annotations via the values.yaml file.

Would it be a valid change request to allow the removal of these annotations in the `setup-db-job` template? We could leave the default values for the job annotations in the values.yaml file, along with a note explaining the behavior. This would allow users to customize or disable the annotations if needed. This would improve compatibility with ArgoCD and other deployment workflows.

### Are you using any custom parameters or values?
```yaml
airflow:
  auth:
    username: airflow
    existingSecret: airflow-auth-secret

  executor: CeleryExecutor
  loadExamples: true

  image:
    registry: docker.io
    repository: bitnami/airflow
    tag: 2.10.5-debian-12-r7

  dags:
    enabled: false

  plugins:
    enabled: false

  defaultInitContainers:
    prepareConfig:
      resourcesPreset: "none"
      resources: {}

    waitForDBMigrations:
      resourcesPreset: "none"
      resources: {}

    loadDAGsPlugins:
      resourcesPreset: "none"
      resources: {}

  web:
    baseUrl: airflow.fabricator.work:443
    containerPorts:
      http: 8080
    replicaCount: 1
    resourcesPreset: "none"
    resources: {}

  scheduler:
    replicaCount: 1
    resourcesPreset: "none"
    resources: {}

  dagProcessor:
    enabled: false

  triggerer:
    enabled: false

  worker:
    containerPorts:
      http: 8793
    replicaCount: 1
    resourcesPreset: "none"
    resources: {}

  setupDBJob:
    enabled: true
    backoffLimit: 10
    resourcesPreset: "none"
    resources: {}

  service:
    type: ClusterIP
    ports:
      http: 8080

  ingress:
    enabled: false

  serviceAccount:
    create: true
  rbac:
    create: false

  metrics:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/statsd-exporter
      tag: 0.28.0-debian-12-r11
    existingConfigmap: "airflow-statsd-mapping-config"
    containerPorts:
      ingest: 9125
      metrics: 9102
    resourcesPreset: "none"
    resources: {}
    service:
      ports:
        ingest: 9125
        metrics: 9102
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      interval: "30s"
      scrapeTimeout: "30s"
      honorLabels: true

  postgresql:
    enabled: false

  externalDatabase:
    host: postgresql.postgresql.svc.cluster.local
    port: 5432
    user: airflow
    database: airflow
    existingSecret: airflow-pg-secret
    existingSecretPasswordKey: airflow-pg-password

  redis:
    enabled: true
    auth:
      enabled: true
      existingSecret: "airflow-redis-secret"
    architecture: standalone
    master:
      service:
        ports:
          redis: 6379
      resourcesPreset: "none"
      resources: {}
```

### What do you see instead?

The `setup-db-job` is not created by Argocd

**Comment by javsalgar** [comment]
Hi!

Thank you so much for opening the ticket. Sure, we could move these annotations to the values.yaml file if that helps with the argo-cd integration. Would you like to submit a PR applying this change?

**Comment by muratc** [comment]
is there any workaround for this when installing with argocd? the job does not get created at all.

**Comment by sondn98** [comment]
Hi @muratc,
from my point of view, there's no quick-win solution other then just making your own version - a copy of the chart with the removal of the hard-coded annotations
For a long-term solution, could you kindly submit a pr for them?

**Comment by muratc** [comment]
Hi @sondn98, it turns out if you disable this job (with setupDBJob.enabled:false), the web container does the same? thing during startup. this workaround was already explained in the readme and i believe it is working fine. so i think this could be one way to go..

**Comment by sondn98** [comment]
It requires to do some db manual setup, doesn't it? If you're cool with it, then just go ahead

**Comment by Nickmman** [comment]
I encountered this same issue with versions up until the latest release, 24.2.4. Even deleting the ArgoCD application and letting it get recreated does not trigger the job.

**Comment by Nickmman** [comment]
Still an active issue.

**Comment by muratc** [comment]
> It requires to do some db manual setup, doesn't it? If you're cool with it, then just go ahead

i didn't need to do anything else actually. i am new to airflow and not sure if i am missing anything as far as this job was supposed to do, but i could start airflow and get some dags running.

**Comment by Nickmman** [comment]
I was able to trigger the job with the following values:
```
    setupDBJob:
      annotations:
        argocd.argoproj.io/hook: Sync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded
```

However, the job never finishes, crashloops and halts the normal progression.

@javsalgar can this get reopened?
