### ISSUE TITLE
[bitnami/cassandra] Port 8080 for integration with Prometheus isn't exposed by the Service

### ISSUE THREAD

**Issue by Iamcerba** [bitnami/charts#3282]
**Which chart**: cassandra

**Description**:
When enabling metrics they couldn't be accessed via Service (port 8080).

**Steps to reproduce:**
1. In values.yaml enable metrics:
```
metrics:
  enabled: true
```
2. Install the chart:
```
helm install cassandra . --namespace default
```
3. Enable Kubernetes proxy:
```
kubectl proxy --port=7777
```
4. Try to gain metrics:
```
http://localhost:7777/api/v1/namespaces/default/services/http:janusgraph-cassandra:8080/proxy
```
5. As a result, you will see the following response:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no service port 8080 found for service \"cassandra-cassandra\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
```

**Expected behavior**:
1. If I extend the Service with additional "metrics" port:
```
(ommited)
spec:
  ports:
    - name: cql
      protocol: TCP
      port: 9042
      targetPort: cql
    - name: thrift
      protocol: TCP
      port: 9160
      targetPort: thrift
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: metrics
(ommited)
```
then I will be able to receive metrics which could be used in Prometheus:
```
# HELP cassandra_stats node stats
# TYPE cassandra_stats gauge
cassandra_stats{cluster="cassandra",datacenter="datacenter1",keyspace="",table="",name="org:apache:cassandra:metrics:droppedmessage:batch_store:dropped:count",} 0.0
...
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a2cfecc33f6911261fb8a670d2df2714094002a6", GitTreeState:"clean", BuildDate:"2020-05-29T21:50:25Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**:
I didn't get why "bitnami/cassandra-exporter" image is a part of Cassandra pods. Usually in bitnami charts metrics have their own dedicated pod and service. Maybe I missed something and metrics could be used in Prometheus somehow with current version of the chart?..
