### ISSUE TITLE
[bitnami/keycloak] is not allowing local hostname with port forwarding when Ingress also enabled

### ISSUE THREAD

**Issue by knraju483** [bitnami/charts#32832]
### Name and Version

bitnami/keycloak 26.0.7

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Hi, 

I need configurations for accepting Keycloak UI with Ingress and port forward at the same. I also disabled admin UI ingress for production and disabled access through normal ingress and it only allow auth API request. 

Kindly help me on supporting both Ingress/port forwarding connection with local host. 

Following my configuration for keycloak 
```
data:
  JAVA_OPTS_APPEND: -Djgroups.dns.query=keycloak-headless.svc.cluster.local
  KC_BOOTSTRAP_ADMIN_USERNAME: ""
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgres:5432/idam
  KC_PROXY: edge
  KEYCLOAK_CACHE_STACK: kubernetes
  KEYCLOAK_CACHE_TYPE: ispn
  KEYCLOAK_DATABASE_HOST: plt-postgres-pooler-rw
  KEYCLOAK_DATABASE_NAME: idam
  KEYCLOAK_DATABASE_PORT: "5432"
  KEYCLOAK_ENABLE_HTTPS: "false"
  KEYCLOAK_ENABLE_STATISTICS: "true"
  KEYCLOAK_HOSTNAME: https://keycoak.abc.net/auth/
  KEYCLOAK_HOSTNAME_STRICT: "false"
  KEYCLOAK_HTTP_PORT: "8080"
  KEYCLOAK_LOG_LEVEL: INFO
  KEYCLOAK_LOG_OUTPUT: default
  KEYCLOAK_PRODUCTION: "false"
  KEYCLOAK_PROXY_HEADERS: xforwarded
```

Regards

### What do you see instead?

I want to access the Keycloak Admin UI with portforwarding local host connection when I am disabled admin Ingress and annotation is added for normal ingress to block the access for UI and allow only for auth api requst.
