### ISSUE TITLE
[bitnami/minio] Minio provisioning root-user: No such file or directory

### ISSUE THREAD

**Issue by Bykow** [bitnami/charts#32850]
### Name and Version

bitnami/minio 16.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In k8s, using helm chart, rendered by kustomize, the minio provisioning fails with:

`minio /bin/bash: line 61: /opt/bitnami/minio/secrets/root-user: No such file or directory`

This was introduced starting from 16.0.x

### Are you using any custom parameters or values?

Relevant part of `values.yaml`:
```

provisioning:
  enabled: true
  buckets:
    - name: something
      region: eu-west-1
      quota:
        type: set
        size: 50GiB
  usersExistingSecrets:
    - something-user
```

### What is the expected behavior?

The provision should start and function as expected.

### What do you see instead?

The minio container does not succeed with 
`minio /bin/bash: line 61: /opt/bitnami/minio/secrets/root-user: No such file or directory`

**Comment by migruiz4** [comment]
Hi @Bykow,

I have submitted this PR that I think should fix your issue: https://github.com/bitnami/charts/pull/32882

Could you please confirm if you are have set a value for the following settings?

```yaml
auth:
  existingSecret: ""
  rootUserSecretKey: ""
  rootPasswordSecretKey: ""
```

The issue affected deployment using `rootUserSecretKey` and/or `rootPasswordSecretKey`.

**Comment by Bykow** [comment]
Hi @migruiz4 

No these values are set in my deployment, what would be the right way to provision a root admin from a secret if not using these ?

```
auth:
  existingSecret: minio-secret
  rootUserSecretKey: minio-root-user
  rootPasswordSecretKey: minio-root-password
```
