### ISSUE TITLE
[matomo] failed to create resource: CronJob.batch "matomo-archive" is invalid: spec.jobTemplate.spec.template.spec.containers[0].volumeMounts[1].name:

### ISSUE THREAD

**Issue by hakakou** [bitnami/charts#32884]
### Name and Version

bitnami/matomo 9.3.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

- microk8s
- `helm install matomo oci://registry-1.docker.io/bitnamicharts/matomo --namespace matomo -f values.yaml`

### Are you using any custom parameters or values?

```yaml
ingress:
  enabled: true
  hostname: xxx.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls: true
  extraTls:
    - hosts:
        - xxx.com
      secretName: tls-matomo

mariadb:
  enabled: false

externalDatabase:
  host: xx
  port: 3306
  user: admin
  password: admin
  database: matomo
```

### What is the expected behavior?

Should not fail

### What do you see instead?

Error:
`Error: UPGRADE FAILED: failed to create resource: CronJob.batch "matomo-archive" is invalid: spec.jobTemplate.spec.template.spec.containers[0].volumeMounts[1].name: Not found: "matomo-secrets"`
