### ISSUE TITLE
bitnami postgresql chart deployment crashloop

### ISSUE THREAD

**Issue by daydone** [bitnami/charts#32943]
### Name and Version

bitnami/postgresql-16.6.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

- [ ] In this environment: Kubernetes cluster with Longhorn storage class
- [ ] With this config: Deploy PostgreSQL using Bitnami Helm chart
- [ ] Run: helm install postgres -n dev -f ./postgresql-values.yaml oci://registry-1.docker.io/bitnamicharts/postgresql
- [ ] See error: PostgreSQL container crashes with "Bus error (core dumped)" during initialization

The error appears consistently during PostgreSQL database initialization with both 17.4.0 and 15.5.0 versions, and occurs specifically when PostgreSQL's initdb process tries to create configuration files.Retry[Claude can make mistakes. Please double-check responses.](https://support.anthropic.com/en/articles/8525154-claude-is-providing-incorrect-or-misleading-responses-what-s-going-on)

### Are you using any custom parameters or values?

postgresql-values.yaml is
```yaml
global:
  postgresql:
    auth:
      postgresPassword: "longhorn"
      username: "pg_admin"
      password: "supersecretpassword"
      database: "mydb"

nameOverride: "chirpstack-postgresql"
namespaceOverride: "dev"

image:
  tag: "15.5.0-debian-11-r0"

volumePermissions:
  enabled: true
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

primary:
  extraEnvVars:
    - name: "BITNAMI_DEBUG"
      value: "true"
    - name: "POSTGRESQL_SHARED_PRELOAD_LIBRARIES"
      value: ""
    - name: "POSTGRESQL_SHARED_BUFFERS"
      value: "128MB"
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
```

### What is the expected behavior?

I expect the statefulSet to deploy and be useable and accessible with the `supersecretpassword` and the `ph_admin`

### What do you see instead?

```shell
Defaulted container "postgresql" out of: postgresql, init-chmod-data (init)
postgresql 19:51:51.25 INFO  ==> 
postgresql 19:51:51.34 INFO  ==> Welcome to the Bitnami postgresql container
postgresql 19:51:51.34 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 19:51:51.35 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql 19:51:51.44 INFO  ==> 
postgresql 19:51:51.54 DEBUG ==> Configuring libnss_wrapper...
postgresql 19:51:51.84 INFO  ==> ** Starting PostgreSQL setup **
postgresql 19:51:52.15 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 19:51:52.34 INFO  ==> Loading custom pre-init scripts...
postgresql 19:51:52.45 INFO  ==> Initializing PostgreSQL database...
postgresql 19:51:52.54 DEBUG ==> Ensuring expected directories/files exist...
postgresql 19:51:52.84 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 19:51:52.85 INFO  ==> Generating local authentication configuration
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /bitnami/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
Bus error (core dumped)
child process exited with exit code 135
initdb: removing contents of data directory "/bitnami/postgresql/data"
running bootstrap script ... 
````

### Additional information

I am not sure what I am doing wrong in my deployment to cause this repeated error.
```sh
creating configuration files ... ok
Bus error (core dumped)
child process exited with exit code 135
```
I have also tried a MUCH more simplified version of my values file with no change in behavior.
