### ISSUE TITLE
Built in backup script broken by :"Set usePasswordFiles=true by default #32115"

### ISSUE THREAD

**Issue by bogronk** [bitnami/charts#32959]
### Name and Version

bitnami/postgresql:16.6.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Backups fail when using password files with the error "no password supplied". 
Overriding with `usePasswordFiles=false` to use env vars restores functionality.
Cannot find any override or doc to make it fetch the password from the files instead.

### Are you using any custom parameters or values?

```yaml
backup:
  ## @param backup.enabled Enable the logical dump of the database "regularly"
  enabled: true
```

### What is the expected behavior?

Working backups :)

### What do you see instead?
```
pg_dumpall: error: connection to server at "name-of-pgcontainer" (ip of pgcontainer), port 5432 failed: fe_sendauth: no password supplied
```
