### ISSUE TITLE
[bitnami/keycloak] Add ability to directly add themes to the /opt/bitnami/keycloak/themes dir using initContainer

### ISSUE THREAD

**Issue by briansterling** [bitnami/charts#32974]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

Currently have a need to drop un-packaged theme files directly into the themes dir. Right now we modify the chart prior to deployment to expose the themes dir similarly to the providers dir. Adding support for the /themes directory via initContainer similar to commit [9de041c](https://github.com/bitnami/charts/commit/9de041c92e2788a108631052aa5401a9469e3592) would add functionality for custom themes not packaged as a .jar. 

### What is the feature you are proposing to solve the problem?

Add the follwing to the statefulset to expose the /themes dir as a writable dir so functionality is native to the chart so themes can be added to the themes /dir directly via initContainer

`cp -r --preserve=mode /opt/bitnami/keycloak/themes /emptydir/app-themes-dir`

```
- name: empty-dir
  mountPath: /opt/bitnami/keycloak/themes
  subPath: app-themes-dir 
```

**Comment by arnaudclerc** [comment]
This broke previous way of adding theme to keycloak
```yaml
  extraVolumes:
    - name: shared-volume
      emptyDir: {}
  extraVolumeMounts:
    - name: shared-volume
      mountPath: /opt/bitnami/keycloak/themes
  initContainers:
    - name: keycloak-theme-provider
      image: docker.domain.fr/ops/keycloak-theme:2.0
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying theme..."
          cp -R /my-theme/* /custom_theme
          echo "Theme successfully added !"
      volumeMounts:
        - name: shared-volume
          mountPath: /custom_theme
```

This way was documented everywhere on the web (nothing from bitnami tho)
now there is no real documentation to add theme and the previous easy method is now broken.

Can this feature be reverted (using enabler) / documented ?

here's how Keycloak has documented it:
https://github.com/bitnami/containers/tree/main/bitnami/keycloak#adding-custom-themes
https://www.keycloak.org/docs/23.0.7/server_development/#creating-a-theme
