### ISSUE TITLE
[bitnami/postgresql-ha] Inconsistent failover behavior in multi-Pgpool setup on manual primary psql pod deletion

### ISSUE THREAD

**Issue by TokuiNico** [bitnami/charts#32982]
### Name and Version

bitnami/postgresql-ha 15.3.11

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Deploy the chart with 3 PostgreSQL pods and 2 Pgpool pods.
2. Wait until everything is in a healthy state.
3. Manually delete the current PostgreSQL primary pod to trigger failover.
4. Observe the logs and behavior of both Pgpool pods.

### Are you using any custom parameters or values?

```yaml
postgresql:
  replicaCount: 3
  username: postgres
  password: postgres-password
  repmgrUsername: repmgr
  repmgrPassword: repmgr-password

  extraEnvVars:
    - name: TZ
      value: Asia/Taipei

  pgHbaConfiguration: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     scram-sha-256
    host    all             all             0.0.0.0/0               scram-sha-256
    host    all             all             ::0/0                   scram-sha-256
    host    repmgr          repmgr          0.0.0.0/0               scram-sha-256
    host    repmgr          repmgr          ::0/0                   scram-sha-256
    local   replication     repmgr                                  scram-sha-256
    host    replication     repmgr          0.0.0.0/0               scram-sha-256
    host    replication     repmgr          ::0/0                   scram-sha-256

  extendedConf: |
    password_encryption = 'scram-sha-256'


pgpool:
  replicaCount: 2
  adminUsername: admin
  adminPassword: admin-password
  customUsers:
    usernames: convoy
    passwords: convoy-password

  extraEnvVars:
    - name: TZ
      value: Asia/Taipei

persistence:
  enabled: true
  size: 8Gi

volumePermissions:
  enabled: true

```

### What is the expected behavior?

Both Pgpool pods should detect the failure, promote a new primary if necessary, and reflect consistent role/pg_role states in SHOW pool_nodes;.

### What do you see instead?

Only one Pgpool pod executes failover and updates the primary correctly.
The other Pgpool pod fails to recover, and continuously logs errors such as:
```
FATAL:  failed to create a backend 1 connection
DETAIL:  not executing failover because failover_on_backend_error is off
WARNING:  failed to connect to PostgreSQL server, getaddrinfo() failed with error "Name or service not known"
...
FATAL:  Backend throw an error message
HINT:  BACKEND Error: "recovery is in progress"
```

Additionally, `SHOW pool_nodes;` shows inconsistent states between role and pg_role, such as:
```
 node_id |                           hostname                           | port | status | pg_status | lb_weight |  role   | pg_role | select_
cnt | load_balance_node | replication_delay | replication_state | replication_sync_state | last_status_change
---------+--------------------------------------------------------------+------+--------+-----------+-----------+---------+---------+--------
----+-------------------+-------------------+-------------------+------------------------+---------------------
 0       | postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless | 5432 | up     | up        | 0.333333  | standby | primary | 122
    | false             | 0                 |                   |                        | 2025-04-14 10:25:39
 1       | postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless | 5432 | up     | up        | 0.333333  | primary | standby | 124
    | false             | 0                 |                   |                        | 2025-04-14 10:24:48
 2       | postgresql-ha-postgresql-2.postgresql-ha-postgresql-headless | 5432 | up     | up        | 0.333333  | standby | standby | 115
    | true              | 0                 |                   |                        | 2025-04-14 10:24:09```
```
### Additional information

- I suspect this may be related to the default setting failover_on_backend_error = off in Pgpool.
- Manually restarting the failing Pgpool pod seems to resolve the inconsistency.
- When running with only one Pgpool pod, everything works as expected and failover behaves correctly. The issue only occurs when multiple Pgpool pods are deployed.
