### ISSUE TITLE
Dremio ingress refers to wrong service port

### ISSUE THREAD

**Issue by belov38** [bitnami/charts#32981]
### Name and Version

bitnami/dremio 0.6.3

### What architecture are you using?

None

### What steps will reproduce the bug?

Deploy a chart with ingress enabled

### Are you using any custom parameters or values?

```yaml
service:
  type: ClusterIP
ingress:
  enabled: true
  hostname: dremio.example.com
```

### What is the expected behavior?

I expect ingress points to the correct service

### What do you see instead?

```yaml
# kubectl get ingress -oyaml
...
- host: dremio.example.com
      http:
        paths:
        - backend:
            service:
              name: dremio-demo
              port:
                name: http ## Here?
          path: /
          pathType: ImplementationSpecific
...
```
The same time 
```yaml
# kubectl get svc dremio-demo -oyaml
apiVersion: v1
kind: Service
metadata:
  name: dremio-demo
...
spec:
  ports:
    - name: http-web
      port: 9047
      protocol: TCP
      targetPort: web
...
```

### Additional information

Workaround:
Add the section
```yaml
ingress:
  enabled: true
  hostname: dremio.example.com
  extraRules:
    - host: dremio-ui.example.copm
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dremio-demo # different in your env
                port:
                  number: 9047
```
