### ISSUE TITLE
[bitnami/external-dns] cloudflare credentials bug

### ISSUE THREAD

**Issue by tschlaepfer** [bitnami/charts#33007]
### Name and Version

bitnami/external-dns

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy external-dns with the following values:
```yaml
cloudflare:
  secretName: "cloudflare-api-token"
  proxied: true

txtEncrypt:
  enabled: true
```

### Are you using any custom parameters or values?
```yaml
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists

resources:
  limits:
    cpu: 20m
    memory: 256Mi
  requests:
    cpu: 5m
    memory: 128Mi

provider: cloudflare

cloudflare:
  apiToken: "dummy-token"
  secretName: "cloudflare-api-token"
  proxied: true

txtEncrypt:
  enabled: true

extraArgs:
  txt-wildcard-replacement: wildcard
  cloudflare-region-key: eu
# Enable external DNS to remove entries in the ingress resource is removed
# policy: sync

serviceAccount:
  create: true

podSecurityContext:
  fsGroup: 65534
  runAsUser: 0

domainFilters:
  - "4data.ch"
```
### What is the expected behavior?

The chart should deploy external-dns using the Cloudflare provider with the credentials provided in the secret, no dummy values for cloudflare.apiKey or cloudflare.apiToken should be required. Hence, the secret template should evaluate whether cloudflare.secretName is provided or not. If provided, there is no need to add the cloudflare credentials to this secret.

### What do you see instead?

When deploying external-dns and using Cloudflare as provider while having txt encryption enabled, the chart tries to create a secret. However, the creation fails because the secret templates expect either the cloudflare.apiKey or cloudflare.apiToken values to be present. As a result, the installation fails if no "dummy" value for one of the values is provided.
