### ISSUE TITLE
Pod disruption budget not created

### ISSUE THREAD

**Issue by mdesouky** [bitnami/charts#33002]
### Name and Version

bitnami/external-dns 8.7.11

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Apply terraform code to deploy the helm release
2. Check pdb via the command `kubectl get pdb -n external-dns` or `kubectl get pdb -A`

### Are you using any custom parameters or values?

```yaml
USER-SUPPLIED VALUES:
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: karpenter.sh/nodepool
          operator: In
          values:
          - system
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - topologyKey: kubernetes.io/hostname
aws:
  assumeRoleArn: arn:aws:iam::305686791668:role/onuptick.com-dns-cross-account-role
  region: ap-southeast-2
domainFilters:
- onuptick.com
- dev-au-2a.onuptick.com
logLevel: debug
pdb:
  create: true
  minAvailable: 1
policy: sync
replicaCount: 1
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 64Mi
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::836245893229:role/dev-au-2a-ext-dns-role-2025041504041775170000001d
  create: true
  name: external-dns-sa
serviceMonitor:
  enabled: true
  namespace: monitor
sources:
- ingress
- service
txtOwnerId: dev-au-2a
```

### What is the expected behavior?

To see a pod disruption budget created

### What do you see instead?

Nothing
```console
$ kubectl get pdb -n external-dns
No resources found in external-dns namespace.

$ kubectl get pdb -A                                        
NAMESPACE     NAME                           MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
karpenter     karpenter                      N/A             1                 1                     31m
kube-system   aws-load-balancer-controller   1               N/A               1                     31m
kube-system   coredns                        N/A             1                 1                     37m
kube-system   ebs-csi-controller             N/A             1                 1                     32m
nginx         ingress-nginx-controller       2               N/A               0                     30m
```

### Additional information

Neither setting `minAvailable` or `maxUnavailable` make any difference; no pdb is created when `pdb.create:true`
