### ISSUE TITLE
How to add additional database drivers

### ISSUE THREAD

**Issue by mwptcw** [bitnami/charts#33000]
### Name and Version

bitnami/superset

### What architecture are you using?

None

### What steps will reproduce the bug?

I want to add additional drivers to the helm.
Apache's chart has a `bootStrapScript.sh` that we can utilize

### Are you using any custom parameters or values?

I attempted to override the run command for the webserver, but that failed (e.g. `pip install clickhouse-connect && /opt/bitnami/scripts/superset/run.sh`)

### What do you see instead?

Unable to find any section in `values` that could be used for this

**Comment by jotamartos** [comment]
Thank you for using Bitnami. Wouldn't creating a new initContainer work for you? You can create one that mounts any required volumes and run the pip install command.

Another option would be to customize the Bitnami image by adding the extra pip packages and use that customized docker image to launch the chart. 

You can always [contribute](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) to the project and request to add additional actions to install any extra pip package in the entrypoint.sh script [as Airflow does](https://github.com/bitnami/containers/blob/main/bitnami/airflow/3/debian-12/rootfs/opt/bitnami/scripts/airflow/entrypoint.sh#L30). The team will be more than happy to review your suggestion.

**Comment by jotamartos** [comment]
Update:

I can see the Superset container already includes the customization to install extra Python packages. You simply need to mount a requirements.txt file at /bitnami/python/requirements.txt and the entrypoint script will take care of installing them.

https://github.com/bitnami/containers/blob/main/bitnami/superset/4/debian-12/rootfs/opt/bitnami/scripts/superset/entrypoint.sh#L26

**Comment by jotamartos** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the root group, as the random user (1001 by default) is a member of this root group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

These changes should make the deployment work 

```
diff --git a/bitnami/superset/values.yaml b/bitnami/superset/values.yaml
index af9b214a09..dc1a8366ca 100644
--- a/bitnami/superset/values.yaml
+++ b/bitnami/superset/values.yaml
@@ -370,10 +370,20 @@ web:
   extraEnvVarsSecret: ""
   ## @param web.extraVolumes Optionally specify extra list of additional volumes for the Superset webserver pods
   ##
-  extraVolumes: []
+  extraVolumes:
+    - name: venv
+      emptyDir: {}
+    - name: "requirements"
+      configMap:
+        name: "superset-requirements-config"
   ## @param web.extraVolumeMounts Optionally specify extra list of additional volumeMounts for the Superset webserver containers
   ##
-  extraVolumeMounts: []
+  extraVolumeMounts:
+    - name: venv
+      mountPath: /opt/bitnami/superset/venv
+    - name: "requirements"
+      mountPath: "/bitnami/python/requirements.txt"
+      subPath: "requirements.txt"
   ## @param web.sidecars Add additional sidecar containers to the Superset webserver pods
   ## e.g:
   ## sidecars:
@@ -394,7 +404,28 @@ web:
   ##    imagePullPolicy: Always
   ##    command: ['sh', '-c', 'echo "hello world"']
   ##
-  initContainers: []
+  initContainers:
+    - name: copy-python-env
+      image: bitnami/superset:4.1.2-debian-12-r5
+      command:
+        - /bin/bash
+      args:
+        - -ec
+        - |
+          #!/bin/bash
+          mv /opt/bitnami/superset/venv/* /opt/bitnami/superset/venv/.* /venv/ || true
+      volumeMounts:
+        - name: venv
+          mountPath: /venv
+    - name: init-fix-permissions
+      image: bitnami/superset:4.1.2-debian-12-r5
+      command:
+        - sh
+        - -c
+        - |
+          find /opt/bitnami/superset/venv/ -type d -exec chown 1001 {} \;
+      securityContext:
+        runAsUser: 0
   ## Pod Disruption Budget configuration
   ## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb
   ## @param web.pdb.create Enable/disable a Pod Disruption Budget creation

```

You can get more info about this in [this other post](https://github.com/bitnami/charts/issues/30791).

**Comment by mwptcw** [comment]
That worked well.  Thank you!
Here's the values in non-diff format

```yaml
web:   
  extraVolumeMounts:
    - name: "venv"
      mountPath: "opt/bitnami/superset/venv"
    - name: "requirements"
      mountPath: "/bitnami/python/requirements.txt"
      subPath: "requirements.txt"
  
  extraVolumes:
    - name: "venv"
      emptyDir: {}
    - name: "requirements"
      configMap:
        name: "superset-requirements-config"
        
  initContainers:
    - name: "copy-python-env"
      image: bitnami/superset:4.1.2-debian-12-r5
      command:
        - /bin/bash
      args:
        - -ec
        - |
          #!/bin/bash
          mv /opt/bitnami/superset/venv/* /opt/bitnami/superset/venv/.* /venv/ || true
      volumeMounts:
        - name: "venv"
          mountPath: "/venv"
    - name: init-fix-permissions
      image: bitnami/superset:4.1.2-debian-12-r5
      command:
        - sh
        - -c
        - |
          find /opt/bitnami/superset/venv/ -type d -exec chown 1001 {} \;
      securityContext:
        runAsUser: 0
```

Thanks again!
