### ISSUE TITLE
unable to deploy dremio using argocd

### ISSUE THREAD

**Issue by GiulioMezzotero** [bitnami/charts#33015]
### Name and Version

bitnami/dremio 1.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Locally I'm able to deploy Dremio in this way:
```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install dremio bitnami/dremio
cd ..
cd snap
./k9s/current/bin/k9s
```
And then accessing it on `localhost:9047` with username and pw given in the secret.

But I also want to deploy it via Argo with the following file `dremio.yaml`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dremio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: dremio
    targetRevision: 1.0.0
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
 ```

Here, I have a failure on the pod `dremio-coordinator-0` with this error on the logs: `Caused by: java.net.UnknownHostException: dremio-executor-default-0.dremio-headless.argocd.svc.cluster.local: Name or service not known`.

Debugging I have noticed that the `dremio-headless` service asks for a "fabric" and a "conduit" port while the statefultset `dremio-executor-default` creates pods with ports named "server-fabric" and "server-conduit".

Could it be this mismatching on the names that causes the error? 
Could another explanation be that, with argo, relying on a gke cluster (having 4 nodepools distributed), this creates network problems? In fact, locally, with Kind, I have only one nodepool.

### What is the expected behavior?

Healthy pod `dremio-coordinator-0`

### What do you see instead?

Crashed pod `dremio-coordinator-0`
