### ISSUE TITLE
[bitnami/keycloak] Cannot bootstrap temporary/admin user with password

### ISSUE THREAD

**Issue by alesandrino** [bitnami/charts#33025]
### Name and Version

bitnami/keycloak 24.0.0 and above

### What architecture are you using?

None

### What steps will reproduce the bug?

1. We deploy the Bitnami Keycloak chart to a Azure AKS cluster using an external database.
2. We deploy the chart using the custom values listed below.
3. When I deploy any version starting from 24.x the deployment still succeeds. The log also mentions that the temporary user was created.

`
[org.keycloak.services] (main) KC-SERVICES0077: Created temporary admin user with username admin
`

### Are you using any custom parameters or values?

``` yaml
keycloak:
  enabled: true
  global:
    storageClass: 'azure-managed-hdd-standard'
  service:
    # the service is not directly exposed (only via nginx), needs to be reachable only inside the cluster
    type: ClusterIP
  auth:
    existingSecret: *commonSecrets
    passwordSecretKey: keycloak-adminpassword
    adminUser: admin
  # we do TLS termination in the nginx proxy, therefore disable here
  tls:
    enabled: false
  production: true
  proxyHeaders: xforwarded
  postgresql:
    enabled: false
  # The external database section must be here to keep the Bitnami chart happy,
  # but we are overriding everything in the extra environment variables.
  externalDatabase:
    existingSecret: *commonSecrets
    existingSecretHostKey: keycloak-database-host
    port: 1433
    existingSecretUserKey: keycloak-database-user
    existingSecretDatabaseKey: keycloak-database-name
    existingSecretPasswordKey: keycloak-database-password
  extraEnvVars:
    - name: KC_HOSTNAME
      value: "auth.***************.com"
    # Override the database vendor. (Bitnami environment variable)
    - name: KEYCLOAK_DATABASE_VENDOR
      value: "mssql"
    # Override the JDBC driver. (Bitnami environment variable)
    - name: KEYCLOAK_JDBC_DRIVER
      value: "sqlserver"
    # Disable XA transactions. (not supported for Azure SQL)
    - name: KC_TRANSACTION_XA_ENABLED
      value: 'false'
    # Override the database username.
    - name: KC_DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: *commonSecrets
          key: keycloak-database-user
    # Override the database password.
    - name: KC_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: *commonSecrets
          key: keycloak-database-password
    # Override the database connection string.
    - name: KC_DB_URL
      valueFrom:
        secretKeyRef:
          name: *commonSecrets
          key: keycloak-database-connectionstring
    - name: KC_HTTP_ENABLED
      value: "true"
    - name: KC_HEALTH_ENABLED
      value: "true"
```

### What is the expected behavior?

I would like to login using the bootstrap admin credentials.

### What do you see instead?

When I open up the admin console and attempt to login using the credentials configured for the temporary/admin user, I cannot login. The log tells me that my credentials are wrong:

`
2025-04-15T11:53:52.770750972Z 2025-04-15 11:53:52,762 WARN  [org.keycloak.events] (executor-thread-1) type="LOGIN_ERROR", realmId="e1a0aeb0-a3b2-4e0f-b9ab-77583a2b65ca", realmName="master", clientId="admin-cli", userId="c9d9d8fe-0e7c-42bd-9a8d-0f65e93e0c46", ipAddress="*************", error="invalid_user_credentials", auth_method="openid-connect", grant_type="password", client_auth_method="client-secret", username="admin"
`

### Additional information

We use Azure SQL as an external database. We understand that this is not officially supported, but it works fine using the configured values for 22.x and 23.x. 
Note, that is is not upgrade related. I used a fresh / empty cluster for the deployment.
