### ISSUE TITLE
[bitnami/superset] Fresh installation failed when using `ingress.extraHosts`

### ISSUE THREAD

**Issue by moonlight8978** [bitnami/charts#33031]
### Name and Version

bitnami/superset 2.0.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. I'm trying to deploy `superset` chart into a k3s cluster
2. The config I used was
`helmfile.yaml`
```yaml
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: superset
    namespace: superset
    chart: bitnami/superset
    version: 2.0.0
    values:
      - superset/values.yaml
```
3. Deploy above chart with
```bash
helmfile apply
```
4. The following error has been thrown
```txt
Error: template: superset/templates/ingress.yaml:45:96: executing "superset/templates/ingress.yaml" at <include "common.names.fullname" .>: error calling include: template: superset/charts/common/templates/_names.tpl:27:14: executing "common.names.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride
```

### Are you using any custom parameters or values?

```yaml
ingress:
  enabled: true
  pathType: Prefix
  hostname: 192.168.1.15.sslip.io
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-traefik-config-auth@kubernetescrd
  extraHosts:
    - name: 192.168.1.16.sslip.io
      path: /

# ... postgresql, and redis config
```

### What is the expected behavior?

the app is deployed successfully

### What do you see instead?

Error: template: superset/templates/ingress.yaml:45:96: executing "superset/templates/ingress.yaml" at <include "common.names.fullname" .>: error calling include: template: superset/charts/common/templates/_names.tpl:27:14: executing "common.names.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride

### Additional information

The chart is deployed successfully without `ingress.extraHosts`

The possible cause:
The different value of `.` between `backend` used for `.Values.ingress.hostname` (was the context)
https://github.com/bitnami/charts/blob/00d63efcda779c41bff2429fab8f8703abe9b8dc/bitnami/superset/templates/ingress.yaml#L35

and `backend` used for `.Values.ingress.extraHosts` (was the host object iterator)
https://github.com/bitnami/charts/blob/00d63efcda779c41bff2429fab8f8703abe9b8dc/bitnami/superset/templates/ingress.yaml#L45
