### ISSUE TITLE
[bitnami/logstash] Headless Service does not include extra Ports

### ISSUE THREAD

**Issue by Charismara** [bitnami/charts#33054]
### Name and Version

bitnami/logstash 6.4.7

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Add an extra Port in `.service.extraPorts`
2. Deploy the Chart
3. --> The created headless service does not include the defined extra port

### Are you using any custom parameters or values?

```yaml

service:
  extraPorts:
    - name: tcp-input
      port: 1514
      targetPort: tcp-input
      protocol: TCP
extraContainerPorts:
   - name: tcp-input
     containerPort: 1514
     protocol: tcp
```

### What is the expected behavior?

The extra port should be available in the headless service

### What do you see instead?

only the default port is available
