### ISSUE TITLE
[bitnami/clickhouse] Cannot set logging level

### ISSUE THREAD

**Issue by kskitek** [bitnami/charts#33051]
### Name and Version

bitnami/clickhouse v24.12

### What architecture are you using?

None

### What steps will reproduce the bug?

Deploy clickhouse for the first time on a kubernetes cluster with custom logLevel.

### Are you using any custom parameters or values?

custom values.yaml
```
image:
  tag: "24.12.1"
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 2Gi

replicaCount: 1
shards: 1
keeper:
  replicaCount: 1

persistence:
  enabled: true
  size: 20Gi

logLevel: warning

auth:
  username: 
  password: 
```

I had to change the image tag version because of https://github.com/ClickHouse/ClickHouse/issues/71417

### What is the expected behavior?

The logging level is properly set to warning.

### What do you see instead?

I get trace log level. This is the log level stats from just 5minutes:

![Image](https://github.com/user-attachments/assets/70f71358-604a-4ac4-8efc-b37bc52c14f9)

### Additional information

I can see the server is started with `/opt/bitnami/clickhouse/bin/clickhouse-server--config-file=/opt/bitnami/clickhouse/etc/config.xml` - this file is not changed in any way byt the chart logLevel variable.
The logLevel variable is set in a configmap and then mounted to `/bitnami/clickhouse/etc/config.d/02-logger.xml` but I don't see this file (or directory) referenced anywhere explicitly.
