### ISSUE TITLE
Mismatched serfWAN and serfLAN in consul-headless-service.yaml

### ISSUE THREAD

**Issue by sharkzeeh** [bitnami/charts#33076]
### Name and Version

bitnami/consul 11.4.11

### What architecture are you using?

None

### What steps will reproduce the bug?

Hello!
I ran into the following error during an upgrade from bitnami/consul:11.0.0 to bitnami/consul:11.4.11
```sh
$ helm upgrade  ./chart-11.4.11
Error: UPGRADE FAILED: cannot patch "consul-test-headless" with kind Service: Service "consul-test-headless" is invalid: spec.ports[4].name: Duplicate value: "serflan-udp"
```

P.S. The dry-run upgrade passed, however. 

It seems that [this commit](https://github.com/bitnami/charts/commit/eab7bf8624256b909dc765342910b510982e4768) added some additional ports to the service spec (see [file at this commit](https://github.com/bitnami/charts/blob/eab7bf8624256b909dc765342910b510982e4768/bitnami/consul/templates/consul-headless-service.yaml))

```yaml
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - ...
    - name: serflan-tcp
      protocol: TCP
      port: {{ .Values.containerPorts.serfLAN }}
    - name: serflan-udp
      protocol: UDP
      port: {{ .Values.containerPorts.serfWAN }} <--- should not this be serfLAN?
    - name: serfwan-tcp
      protocol: TCP
      port: {{ .Values.containerPorts.serfWAN }}
    - name: serfwan-udp
      protocol: UDP
      port: {{ .Values.containerPorts.serfLAN }} <--- should not this be serfWAN ?
```

After I swapped the ports in question I managed to upgrade via
```sh
$ helm upgrade consul-test ./chart-11.4.11
```

### What is the expected behavior?

Successful upgrade after setting the same ports in `values.yaml`

```yaml
containerPorts:
  http: 8500
  dns: 8600
  rpc: 8400
  rpcServer: 8300
  serfLAN: 8301
  serfWAN: 8302 <--- this was not present in values.yaml in 11.0.0
```

### What do you see instead?

```sh
$ helm upgrade  ./chart-11.4.11
Error: UPGRADE FAILED: cannot patch "consul-test-headless" with kind Service: Service "consul-test-headless" is invalid: spec.ports[4].name: Duplicate value: "serflan-udp"
```
