### ISSUE TITLE
[bitnami/nginx] Preexisting custom conf files are ignored

### ISSUE THREAD

**Issue by davgia** [bitnami/charts#33071]
### Name and Version

bitnami/nginx 19.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. create a new container image that uses bitnami/nginx as base image
2. add custom nginx configuration file through Dockerfile (following the official doc her: https://github.com/bitnami/containers/tree/main/bitnami/nginx#configuration) in:
  - `/opt/bitnami/nginx/conf/bitnami`
  - `/opt/bitnami/nginx/conf/server_blocks`
3. deploy the new image on kubernetes using the `bitnami/nginx` chart (version 19.1.1)
4. custom server blocks are not present in the running pod

## Custom files

``` sh
# .docker/conf/bitnami/test.conf
expires $expires;
```

``` sh
# .docker/conf/server_blocks/test.conf
map $sent_http_content_type $expires {
    default     off;
    text/html   epoch;
    text/css    epoch;
    application/javascript  epoch;
}
```

## Dockerfile

``` Dockerfile
FROM bitnami/nginx

COPY ./docker/conf/bitnami/*.conf /opt/bitnami/nginx/conf/bitnami

COPY ./docker/conf/server_blocks/*.conf /opt/bitnami/nginx/conf/server_blocks
```

## Helm chart values

``` yaml
global:
  imageRegistry: [MY_HARBOR_INSTANCE_URL]
  imagePullSecrets:
  - [MY_HARBOR_PULL_SECRETS_SECRET_NAME]
  security:
    allowInsecureImages: true

frontend:
  nameOverride: "frontend-test"
  fullnameOverride: "frontend-test"
  service:
    type: ClusterIP
  image:
    tag: [MY_CUSTOM_TAG]
    repository: [MY_CUSTOM_IMAGE]
  resources:
    requests:
      memory: "256Mi"
    limits:
      memory: "384Mi"
      cpu: "100m"
  containerSecurityContext:
    readOnlyRootFilesystem: false
  tls:
    enabled: false
```

### What is the expected behavior?

The Kubernetes Pod should have and should allow to use the custom conf file added in the container image.

### What do you see instead?

The Kubernetes Pod does not have the custom configuration files (the emptydir mounted volume clears all existing conf files).

### Additional information

1. I do not see this behaviour in chart version 15.4.5
2. I would probably expose an additional value to disable the following volume mount:
    ``` yaml
                - name: empty-dir
                  mountPath: /opt/bitnami/nginx/conf
                  subPath: app-conf-dir
    ```
   even if I don't know why it is like that.. maybe for security reason? I don't know.
