### ISSUE TITLE
Mongodb backup cronjob AuthenticationFailed, cant read password from file

### ISSUE THREAD

**Issue by BoKKeR** [bitnami/charts#33099]
### Name and Version

bitnami/mongodb@16.5.1

### What steps will reproduce the bug?

k8s v1.32.3
bitnami/mongodb@16.5.1
Talos 1.9.5

New mongodb replicated setup. 
Enable backup cronjob
Trigger cronjob
Get auth error

### Are you using any custom parameters or values?
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    global:
      defaultStorageClass: "local-path-provisioner"
    auth:
      enabled: true
      existingSecretPasswordKey: mongodb
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    persistence:
      enabled: true
      storageClass: local-path-provisioner
    architecture: replicaset
    backup:
      enabled: true
        schedule: "@daily"
        storage:
          subPath: mongodb-backup
          existingClaim: unraid-un-nvme-pvc
    externalAccess:
         enabled: false
```
### What is the expected behavior?

Expected to have the backup be able to authorize and backup the database

### What do you see instead?

The backup fails with the following error 

```
Failed: can't create session: failed to connect to mongodb://mongodb-headless:27017/: connection() error occurred during connection handshake: auth error: unable to authen
ticate using mechanism "SCRAM-SHA-256": (AuthenticationFailed) Authentication failed.
```

### Additional information

I somehow managed to debug the issue and have a workaround for it. In my opinion, the issue is related to how the secret is being read from the file.

```
export MONGODB_ROOT_PASSWORD="$(< $MONGODB_ROOT_PASSWORD_FILE)"
```

This works

```
export MONGODB_ROOT_PASSWORD="$(cat $MONGODB_ROOT_PASSWORD_FILE)"
```

The above fixes the problem for me.

But to test it, I had to base64 for the command which normally followed to be able to use it with the helm chart, otherwise the variable names would not appear in the cronjob

```yaml
    backup:
      enabled: true
      cronjob:
        command:
            - /bin/sh
            - -c
            - |
              export MONGODB_ROOT_PASSWORD="$(cat $MONGODB_ROOT_PASSWORD_FILE)"
              eval "$(echo bW9uZ29kdW1wIC0tdXNlcm5hbWU9JHtNT05HT0RCX1JPT1RfVVNFUn0gLS1wYXNzd29yZD0ke01PTkdPREJfUk9PVF9QQVNTV09SRH0gLS1hdXRoZW50aWNhdGlvbkRhdGFiYXNlPWFkbWluIC0taG9zdD0ke01PTkdPREJfU0VSVklDRV9OQU1FfSAtLXBvcnQ9JHtNT05HT0RCX1BPUlRfTlVNQkVSfSAke01PTkdPREJfQ0xJRU5UX0VYVFJBX0ZMQUdTfS0tb3Bsb2cgLS1nemlwIC0tYXJjaGl2ZT0ke01PTkdPRFVNUF9ESVJ9L21vbmdvZHVtcC0kKGRhdGUgJyslWS0lbS0lZC0lSC0lTScpLmd6 | base64 -d)"
```
