### ISSUE TITLE
[bitnami/keycloak] Chart referencing wrong keys when using `externalDatabase`

### ISSUE THREAD

**Issue by Luzifer** [bitnami/charts#33106]
### Name and Version

bitnami/keycloak 24.5.4+

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Use `bitnami/keycloak` with version 24.5.4 or later
2. Use an `externalDatabase` with a secret only providing `username` and `password` (Zalando PG Operator)
3. Apply values-snippet provided below
4. Notice pods not being scheduled as of `MountVolume.SetUp failed for volume "keycloak-secrets" : references non-existent secret key: db-host`
5. Debug template and see snippet from "What do you see instead?"

### Are you using any custom parameters or values?

```yaml
# ...

externalDatabase:
  host: keycloak-pg
  database: keycloak
  existingSecret: keycloak.keycloak-pg.credentials.postgresql.acid.zalan.do
  existingSecretUserKey: username
  existingSecretPasswordKey: password

# ...
```

### What is the expected behavior?

Fields `username` and `password` are taken from the referenced secret

### What do you see instead?

Fields `password` and `db-host` are taken from the referenced secret (therefore leading to K8s not being able to schedule the pod as `db-host` is not part of the referenced secret)

```yaml
# ...
  volumes:
# ...
  - name: keycloak-secrets
    projected:
      defaultMode: 420
      sources:
      - secret:
          name: keycloak
      - secret:
          items:
          - key: password
            path: db-password
          - key: db-host             # <--- should be "username"
            path: db-username
          name: keycloak.keycloak-pg.credentials.postgresql.acid.zalan.do
```

### Additional information

Code leading to the issue (specific for this issue L405 but the other keys need fixing too):

https://github.com/bitnami/charts/blob/408bc3f3ece7839e610a4e02ced15cfb692c5ee1/bitnami/keycloak/templates/statefulset.yaml#L391-L411
