### ISSUE TITLE
Unable to pass external kafka sasl secret with different key

### ISSUE THREAD

**Issue by sameergithub5** [bitnami/charts#33103]
### Name and Version

bitnami/schema-registry  24.0.0

### What architecture are you using?

None

### What steps will reproduce the bug?

I am using bitnami/schema-registry 24.0.0 helm chart to deploy schema registry, which I want to connect to my existing scram 512 sasl auth kafka.
Helm expects to have a secret key with client-passwords, but I can't have the same key name. I see the secret, and it's hardcoded in secret.
I have the sasl password in secret, but it's with key kafkapass, how do I handle this??
How do I use this helm then to connect to existing/external Kafka with SASL auth

### What do you see instead?

I see it's expecting client-passwords key, andthe  pod does not start

**Comment by sameergithub5** [comment]
`global:
  imageRegistry: ""
  imagePullSecrets: []
  defaultStorageClass: ""
  security:
    allowInsecureImages: false
  compatibility:
    openshift:
      adaptSecurityContext: auto
image:
  registry: docker.io
  repository: bitnami/schema-registry
  tag: 7.9.0-debian-12-r3
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false

diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity
auth:
  tls:
    enabled: false
  kafka:
    saslMechanism: SCRAM-SHA-512
listeners: http://0.0.0.0:8081
avroCompatibilityLevel: backward
replicaCount: 1
updateStrategy:
  type: RollingUpdate
affinity:
  key: Pool
  operator: In
  values: kafka 
tolerations: 
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: kafka 
resources:
  requests:
    cpu: 1
    memory: 512Mi
  limits:
    cpu: 2
    memory: 1024Mi
service:
  type: LoadBalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "kaka.test.net"
    external-dns.alpha.kubernetes.io/ttl: "60"
    service.beta.kubernetes.io/aws-load-balancer-name: kafka-schema-registry"
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
#    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
#   service.beta.kubernetes.io/aws-load-balancer-target-type: "ip" # or instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
  #  service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "ssl"
  ports:
    http: 8081
  nodePorts:
    http: ""
  clusterIP: ""
  externalTrafficPolicy: Cluster
  annotations: {}
  labels: {}
  extraPorts: []
  sessionAffinity: None
  sessionAffinityConfig: {}
  headless:
    annotations: {}

kafka:
  enabled: false
externalKafka:
  brokers:
    - SASL_PLAINTEXT://test-kafka-bootstrap.kafka-test.svc:9092
  listener:
    protocol: SASL_PLAINTEXT
  sasl:
    user: admin
 #   password: "${}"
    existingSecret: "kafadmin" <--This only works if the password is saved with key client-passwords in secret.

extraEnvVars: 
  - name: SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION
    value: "/opt/bitnami/schema-registry/certs/ssl.keystore.jks"
  - name: SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION
    value: "/opt/bitnami/schema-registry/certs/ssl.truststore.jks"
#extraEnvVarsSecret:
#  SCHEMA_REGISTRY_SSL_KEY_PASSWORD:
#    name: dbops-hc-vault-kafka-secrets
#    keyName: dbops_hc_vault_schemaregsslkeypass
#  SCHEMA_REGISTRY_KAFKA_SASL_PASSWORDS:
#    name: dbops-hc-vault-kafka-secrets
#    keyName: dbops_hc_vault_kafadmin

networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: true
ingress:
  enabled: false
serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: false
pdb:
  create: true
  minAvailable: ""
  maxUnavailable: ""
autoscaling:
  enabled: false
podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  supplementalGroups: []
  fsGroup: 1001
  sysctls: []
containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"
livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 1
  periodSeconds: 20
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 1
  periodSeconds: 20
  failureThreshold: 6
  successThreshold: 1
startupProbe:
  enabled: false
  initialDelaySeconds: 10
  timeoutSeconds: 1
  periodSeconds: 5
  failureThreshold: 20
  successThreshold: 1
customLivenessProbe: {}
customReadinessProbe: {}
customStartupProbe: {}
`

**Comment by toniiiik** [comment]
@sameergithub5  I had same problem and find workaround. But for sure option to set custom key of the secret will be much better.

this is in the script which initialize environment variables
```bash
export SCHEMA_REGISTRY_KAFKA_TRUSTSTORE_PASSWORD="${SCHEMA_REGISTRY_KAFKA_TRUSTSTORE_PASSWORD:-}"
SCHEMA_REGISTRY_KAFKA_SASL_USER="${SCHEMA_REGISTRY_KAFKA_SASL_USER:-"${SCHEMA_REGISTRY_KAFKA_SASL_USERS:-}"}"
export SCHEMA_REGISTRY_KAFKA_SASL_USER="${SCHEMA_REGISTRY_KAFKA_SASL_USER:-}"
SCHEMA_REGISTRY_KAFKA_SASL_PASSWORD="${SCHEMA_REGISTRY_KAFKA_SASL_PASSWORD:-"${SCHEMA_REGISTRY_KAFKA_SASL_PASSWORDS:-}"}"
export SCHEMA_REGISTRY_KAFKA_SASL_PASSWORD="${SCHEMA_REGISTRY_KAFKA_SASL_PASSWORD:-}"
```

so variables _SCHEMA_REGISTRY_KAFKA_SASL_USER_, _SCHEMA_REGISTRY_KAFKA_SASL_PASSWORD_ have precedence.

As a workaround you can set these variables as extraEnvVars. Here is example of value file
```yaml
externalKafka:
  brokers: SASL_PLAINTEXT://shared-kafka-brokers:9092
  listener:
    protocol: SASL_PLAINTEXT
  sasl:
    user: schema-registry
    password: # TBD patch secret key client-credentials => password
    existingSecret: schema-registry #expected key in secret is client-passwords.
kafka:
  enabled: false

#workaround for existingSecret hardcoded key
userPasswordFiles: true


extraEnvVars:
  - name: SCHEMA_REGISTRY_KAFKA_SASL_USER
    value: schema-registry
  - name: SCHEMA_REGISTRY_KAFKA_SASL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: schema-registry
        key: password
auth:
  kafka:
    saslMechanism: SCRAM-SHA-512
```
