### ISSUE TITLE
[bitnami/keycloak] Invalid volume projection when using `externalDatabase`

### ISSUE THREAD

**Issue by shadow1runner** [bitnami/charts#33124]
### Name and Version

bitnami/keycloak 24.5.7

### What architecture are you using?

None

### What steps will reproduce the bug?

Using values like

```yaml
postgresql:
  enabled: false
externalDatabase:
  existingSecret: keycloak-db-app
  existingSecretHostKey: host
  existingSecretUserKey: user
  existingSecretDatabaseKey: dbname
  existingSecretPasswordKey: password
```

results in a sts.spec.volumes to be rendered as follows:
> Note the repeated usage of `key: host`

```yaml
...
volumes:
- name: keycloak-secrets
  projected:
    defaultMode: 420
    sources:
    - secret:
        name: keycloak-db-app
        items:
        - key: password
          path: db-password
        - key: host
          path: db-host
        - key: host
          path: db-user
        - key: host
          path: db-dbname
```

### What is the expected behavior?

using the keys as specified in the values

### What do you see instead?

> Note the repeated usage of `key: host`
