### ISSUE TITLE
[bitnami/valkey]  Metrics container: ephemeral local storage get bloated and whole pod got evict

### ISSUE THREAD

**Issue by ook** [bitnami/charts#33125]
### Name and Version

bitnami/valkey 2.4.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy Valkey 8.0.2, allkeys-LRU policy, no persistence at all (valkey or metrics).
Please note: the ephemeral storage set is only here to "buy" some time before the ephemeral bloat and eviction. It happens with the default configuration as well.

### Are you using any custom parameters or values?

```yaml
USER-SUPPLIED VALUES:
architecture: standalone
auth:
  enabled: false
commonConfiguration: |
  maxmemory 100G
  maxmemory-policy allkeys-lru
image:
  tag: 8.0-debian-12
metrics:
  enabled: true
  resources:
    limits:
      ephemeral-storage: 100Gi
    requests:
      ephemeral-storage: 20Gi
namespace: cultsprod
primary:
  persistence:
    enabled: false
  resources:
    requests:
      memory: 105Gi
usePassword: false
```

### What is the expected behavior?

Valkey and its metrics sidecar will live and serve happy forever.

### What do you see instead?

Metrics ephemeral gets full, and the whole pod is evicted, with the primary Valkey container.

### Additional information

Consuming Prometheus metrics data doesn’t prevent ephemeral storage from getting stuck.
