### ISSUE TITLE
[bitnami/redis] PVC is not created with kind: Deployment and architecture: replication

### ISSUE THREAD

**Issue by jozenstar** [bitnami/charts#33142]
### Name and Version

bitnami/redis 20.13.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy the HelmRelease with `kind: Deployment` and `architecture: replication`

### Are you using any custom parameters or values?

```yaml
values:
    architecture: replication
    auth:
      enabled: false
    metrics:
      enabled: true
    master:
      kind: Deployment
      persistence:
        enabled: true
        size: 15Gi
        storageClass: gp3
      resources:
        limits:
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
    replica:
      kind: Deployment
      replicaCount: 2
```

### What is the expected behavior?

PVC is created and pods can start

### What do you see instead?

PVC isn't created and pods never start

### Additional information

There's this condition 
```
{{- if and (eq .Values.architecture "standalone") (eq .Values.master.kind "Deployment") (.Values.master.persistence.enabled) (not .Values.master.persistence.existingClaim) }}
```
in this file
https://github.com/bitnami/charts/blob/main/bitnami/redis/templates/master/pvc.yaml

I don't know why pvc should only be created in a standalone mode.
