### ISSUE TITLE
[bitnami/fluent-bit] File not created in /fluent-bit/etc when using extraFiles

### ISSUE THREAD

**Issue by jpinxten** [bitnami/charts#33161]
### Name and Version

bitnami/fluent-bit 3.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy the helmchart with `extraFiles`

### Are you using any custom parameters or values?

```yaml
daemonset:
  enabled: true

config:
  extraFiles:
    sshd_parser.lua: |
      function map_to_ecs(tag, timestamp, record)
        ...
      end
```

### What is the expected behavior?

According to the Helm chart comment "This allows adding more files with arbitrary filenames to /fluent-bit/etc by providing key/value pairs." — I expect the file to be created under /fluent-bit/etc.

### What do you see instead?

The file is not present in `/fluent-bit/etc`, also not under `/opt/bitnami/fluent-bit/....`

### Additional information

I used the following command to look for the file: `kubectl exec pod/<fluentbit-pod> -- ls <path>`

I've tried searching both `/fluent-bit/etc` and `/opt/bitnami/fluent-bit/...` without success.

Btw, I'm actually trying to add a Lua script so I can use this in a filter.
