### ISSUE TITLE
[bitnami/elasticsearch] Plugin installation fails with missing directory

### ISSUE THREAD

**Issue by head-gardener** [bitnami/charts#33231]
### Name and Version

bitnami/elasticsearch 21.6.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Chart version 21.6.3, app version 8.18.0, image `tag 8.18.0-debian-12-r2` fail to install plugins.

### Are you using any custom parameters or values?

My values.yaml:
```yaml
plugins: "analysis-phonetic,analysis-icu,analysis-stempel"

image:
  tag: 8.18.0-debian-12-r2
  pullPolicy: Always

master:
  masterOnly: false
  replicaCount: 1
data:
  replicaCount: 0
coordinating:
  replicaCount: 0
ingest:
  replicaCount: 0
```

### What is the expected behavior?

Pod should start without errors and with plugins installed.

### What do you see instead?

Pod startup fails with following output:
```
elasticsearch 19:23:20.25 INFO  ==>
elasticsearch 19:23:20.25 INFO  ==> Welcome to the Bitnami elasticsearch container
elasticsearch 19:23:20.25 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
elasticsearch 19:23:20.25 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
elasticsearch 19:23:20.26 INFO  ==>
elasticsearch 19:23:20.26 INFO  ==> ** Starting Elasticsearch setup **
elasticsearch 19:23:20.29 WARN  ==> Setting ELASTICSEARCH_IS_DEDICATED_NODE is disabled.
elasticsearch 19:23:20.29 WARN  ==> ELASTICSEARCH_NODE_ROLES will be ignored and Elasticsearch will asume all different roles.
elasticsearch 19:23:20.29 INFO  ==> Configuring/Initializing Elasticsearch...
elasticsearch 19:23:20.31 INFO  ==> Custom configuration file detected, using it...
find: '/bitnami/elasticsearch/plugins': No such file or directory
```

### Additional information

Changing repos (e.g. `https://repo1.maven.org/maven2/org/elasticsearch/plugin/analysis-icu/2.4.6/analysis-icu-2.4.6.zip` or `file:///analysis-icu-8.18.0.zip`) produces the same behavior.
