### ISSUE TITLE
[bitnami/ejbca] Unable to startup successfully a fresh instnace

### ISSUE THREAD

**Issue by mangusbrother** [bitnami/charts#33259]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

N/A

### bndiagnostic output
```
ejbca 18:53:30.67 INFO  ==> 
ejbca 18:53:30.68 INFO  ==> Welcome to the Bitnami ejbca container
ejbca 18:53:30.69 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
ejbca 18:53:30.69 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
ejbca 18:53:30.70 INFO  ==>
ejbca 18:53:30.71 INFO  ==> ** Starting ejbca setup **
ejbca 18:53:30.73 WARN  ==> Skipping export of 'EJBCA_WILDFLY_ADMIN_PASSWORD'. '/opt/bitnami/wildfly/tmp/wildfly_admin.pwd' is not readable.
ejbca 18:53:30.73 INFO  ==> Validating settings in EJBCA_* env vars...
ejbca 18:53:30.74 INFO  ==> Initializing EJBCA...
ejbca 18:53:30.89 INFO  ==> Deploying EJBCA from scratch
ejbca 18:53:56.12 INFO  ==> Creating database tables and indexes
mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
ejbca 18:54:01.31 INFO  ==> Creating wildfly management user...
ejbca 18:54:02.14 INFO  ==> Starting wildfly...
ejbca 18:54:19.30 INFO  ==> Creating data source
ejbca 18:54:29.05 INFO  ==> Configure WildFly Remoting
ejbca 18:54:43.64 INFO  ==> Configure logging
ejbca 18:54:57.67 INFO  ==> Remove the ExampleDS DataSource
ejbca 18:55:09.37 INFO  ==> Configure email
ejbca 18:55:23.73 INFO  ==> Configure redirection
ejbca 18:55:43.88 INFO  ==> Deploying EJBCA application
ejbca 18:56:18.98 INFO  ==> Deployment done
ejbca 18:56:18.99 INFO  ==> Generating CA
ejbca 18:56:22.63 INFO  ==> Init CA
ejbca 18:56:31.63 INFO  ==> Add superadmin user
ejbca 18:56:38.30 INFO  ==> Add RA Entity
ejbca 18:56:41.74 INFO  ==> Set RA status to new
ejbca 18:56:44.82 INFO  ==> Set RA entity password
ejbca 18:56:47.95 INFO  ==> Export entity certificate
ejbca 18:56:55.71 INFO  ==> Load the CAs in the trustkeystore
Certificate was added to keystore
ejbca 18:57:03.16 INFO  ==> HTTP(S) Listener Configuration
ejbca 19:00:54.03 ERROR ==> Timeout waiting for Wildfly to be ready
```

### bndiagnostic was not useful. Could you please tell us why?

Not even starting up 

### Describe your issue as much as you can

I am trying to set up bitnami/ejbca in my Kubernetes cluster. 
It seems like the startup, for the most part, proceeds fine. I can see some tables being created in mariadb, but then it fails, waiting for WildFly to start, and crashes. This has happened each time I start it up.
I am on a fresh installation, as such, I have cleared out the volumes of both mariadb and ejbca to test things ou,t and this yielded no benefit.

I have built my configuration based on the Docker Hub config page, both the docker commands and the docker-compose.yml  (on that note, the docker-compose sample in the docs lacks `MARIADB_ROOT_PASSWORD` or equivalent, which is required for first startup) 

Here is my full configuration:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca
  namespace: guest-services
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: ca
  template:
    metadata:
      labels:
        app: ca
    spec:
      initContainers:
        - name: ca-mariadb
          image: docker.io/bitnami/mariadb:latest
          restartPolicy: Always
          env:
            - name: MARIADB_DATABASE
              value: "bitnami_ejbca"
            - name: MARIADB_USER
              value: "bn_ejbca"
            - name: MARIADB_PASSWORD
              value: "Bitnami1234"
            - name: MARIADB_ROOT_PASSWORD
              value: "Bitnami1234"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /bitnami/mariadb
              name: shared-data-ca
              subPath: mariadb
      containers:
      - name: ca
        image: docker.io/bitnami/ejbca:9
        env:
          - name: EJBCA_DATABASE_USERNAME
            value: "bn_ejbca"
          - name: EJBCA_DATABASE_PASSWORD
            value: "Bitnami1234"
          - name: EJBCA_DATABASE_HOST
            value: "127.0.0.1"
          - name: EJBCA_DATABASE_NAME
            value: "bitnami_ejbca"
        ports:
        - containerPort: 8080
        - containerPort: 8443
        - containerPort: 8009
        resources:
          limits:
            memory: "2048Mi"
            cpu: "2000m"
          requests:
            memory: "1024Mi"
            cpu: "250m"
        volumeMounts:
        - mountPath: /bitnami/wildfly
          name: shared-data-ca
          subPath: data
      - name: adminer
        image: adminer:latest
        command: [ "php", "-S", "[::]:8081", "-t", "/var/www/html"]
        env:
          - name: ADMINER_DEFAULT_SERVER
            value: "127.0.0.1:3306"
        ports:
          - containerPort: 8081
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: shared-data-ca
        persistentVolumeClaim:
          claimName: ca-local-pvc
```

The volumes:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ca-local-pv
  namespace: guest-services
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb-storage
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1001
    - gid=1001
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: ca-smb-volume
    volumeAttributes:
      source: "//192.168.1.146/Container Mapped Config/Azys-La/ca"
    nodeStageSecretRef:
      name: smb-secret
      namespace: guest-services
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-local-pvc
  namespace: guest-services
spec:
  storageClassName: smb-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

And just for the sake of completion. This is the service for this deployment. The ports here are then used by an nginx deployment acting as an ingress

```yaml
apiVersion: v1
kind: Service
metadata:
  name: ca
  namespace: guest-services
spec:
  selector:
    app: ca
  ports:
    - protocol: TCP
      port: 8009
      targetPort: 8009
      name: ca-http8009
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: ca-http8
    - protocol: TCP
      port: 8443
      targetPort: 8443
      name: ca-https8
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: ca-adminer
  type: ClusterIP
```
