### ISSUE TITLE
[bitnami/keycloak] Infinite loop on keycloak with openid-connect

### ISSUE THREAD

**Issue by 7adityaraj** [bitnami/charts#33255]
### Name and Version

bitnami/keycloak 24.5.0 infinite loop with openid-connect login 

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have setup keycloak recent version `24.5.0` and deployed via terraform helm release.

keycloak is running in aws eks cluster and pointed with AWS ALB (example: keycloak.dev.domain.com)

issue:
 -  login with service app (app1.dev.domain.com) redirects to Azure login and then keeps an infinite loop 🛑 
 - this is what I find while browser inspect (Recalculated absoluteURI to https://keycloak.dev.domain.com/realms/erp/protocol/openid-connect/auth?client_id=ui&redirect_uri=https%3A%2F%2Ferp.dev.domain.com%2F%23iss%3Dhttps%253A%252F%252Fkeycloak.dev.domain.com%252Frealms%252Ferp%26iss%3Dhttps%253A%252F%252Fkeycloak.dev.domain.com%252Frealms%252Ferp%26iss%3Dhttps%253A%252F%252Fkeycloak.dev.domain.com%252Frealms%252Ferp%26iss%3Dhttps%253A%252F%252Fkeycloak.dev.domain.com%252Frealms%252Ferp%26iss%3Dhttps%253A%252F%252Fkeycloak.dev.domain.com%252Frealms%252Ferp%26iss%3Dhttps%253A%252F%252Fkeycloak.dev.domain.com%252Frealms%252Ferp%26iss%3Dhttps%253A%252F%252F)
 - local login to keycloak is fine ✅ 
 - login via azure AD without service app, direct login to keycloak is fine ✅ 

Could someone please explain what the issue is with this setup?

- (FYI) app1.dev.domain.com > ALB > Cloudfront > S3

The content of values.yaml:
```yaml
auth:
  createAdminUser: true
  adminUser: admin-user
  existingSecret: keycloak-tokens-parameter-store
  passwordSecretKey: keycloak-admin-user-pass

postgresql:
  enabled: false

externalDatabase:
  existingSecret: keycloak-tokens-parameter-store
  existingSecretHostKey: keycloak-db-host
  existingSecretPasswordKey: keycloak-db-pass
  port: 5432
  user: ${db_user}
  database: ${database}

service:
  type: NodePort

## have removed proxy and production but had the similar issue
proxy: edge 
production: true

extraEnvVars:
  - name: BITNAMI_DEBUG
    value: "true"
  - name: KEYCLOAK_LOG_LEVEL
    value: DEBUG
  - name: KEYCLOAK_HOSTNAME
    value: ${hostname_https}
  - name: KEYCLOAK_HOSTNAME_ADMIN
    value: ${hostname_https}
  - name: KC_HOSTNAME_STRICT_HTTPS
    value: "false"
  - name: KEYCLOAK_PROXY_HEADERS
    value: forwarded
  - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KC_HTTP_ENABLED
    value: "true"

ingress:
  enabled: true
  path: /
  pathType: Prefix
  hostname: ${hostname}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-name: keycloak-${env}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/success-codes: '200,301,302'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '60'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: ${acm_arn}

autoscaling:
  enabled: ${asg_enable}
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 90
  targetMemory: 90

replicaCount: ${replicaCount}
podManagementPolicy: Parallel

terminationGracePeriodSeconds: 150

livenessProbe:
  enabled: true
  initialDelaySeconds: 300
  periodSeconds: 1
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 10
```

kc.sh show-config from keycloak container (some values are redacted)
```
kc.bootstrap-admin-password =  ******* (ENV)
kc.bootstrap-admin-password-file =  /opt/bitnami/keycloak/secrets/keycloak-admin-user-pass (ENV)
kc.bootstrap-admin-username =  admin-user (ENV)
kc.cache =  ispn (keycloak.conf)
kc.cache-stack =  kubernetes (keycloak.conf)
kc.db =  postgres (keycloak.conf)
kc.db-password =  ******* (keycloak.conf)
kc.db-url =  jdbc:postgresql://keycloak-dev.afaegdddfea.eu-central-1.rds.amazonaws.com:5432/kc_dev?currentSchema=public (keycloak.conf)
kc.db-username =  admin (keycloak.conf)
kc.health-enabled =  false (keycloak.conf)
kc.hostname =  http://keycloak.dev.domain.com/ (keycloak.conf)
kc.hostname-strict =  false (keycloak.conf)
kc.http-enabled =  true (keycloak.conf)
kc.http-port =  8080 (keycloak.conf)
kc.http-relative-path =  / (keycloak.conf)
kc.https-port =  8443 (keycloak.conf)
kc.log-console-output =  default (keycloak.conf)
kc.log-level =  DEBUG (keycloak.conf)
kc.metrics-enabled =  false (keycloak.conf)
kc.provider.file.keycloak-metrics-spi-7.0.0.jar.last-modified =  1745936054527 (Persisted)
kc.proxy-headers =  xforwarded (keycloak.conf)
kc.spi-admin-realm =  master (ENV)
kc.spi-connections-infinispan-quarkus-stack =  kubernetes (keycloak.conf)
kc.spi-hostname-v2-hostname =  http://keycloak.dev.domain.com (keycloak.conf)
kc.spi-hostname-v2-hostname-strict =  false (keycloak.conf)
kc.spi-theme-cache-templates =  false (classpath keycloak.conf)
kc.spi-theme-cache-themes =  false (classpath keycloak.conf)
kc.spi-theme-static-max-age =  -1 (classpath keycloak.conf)
kc.version =  26.1.4 (SysPropConfigSource)
```

Client configs: (replacing domain name as example):

<img width="872" alt="Image" src="https://github.com/user-attachments/assets/bb00a84b-1beb-49ba-80ca-d2da3e76e5b9" />

### Are you using any custom parameters or values?

```yaml
extraEnvVars:
  - name: BITNAMI_DEBUG
    value: "true"
  - name: KEYCLOAK_LOG_LEVEL
    value: DEBUG
  - name: KEYCLOAK_HOSTNAME
    value: ${hostname_https}
  - name: KEYCLOAK_HOSTNAME_ADMIN
    value: ${hostname_https}
  - name: KC_HOSTNAME_STRICT_HTTPS
    value: "false"
  - name: KEYCLOAK_PROXY_HEADERS
    value: forwarded
  - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KC_HTTP_ENABLED
    value: "true"
```

### What is the expected behavior?

How to prevent the redirect loop while trying to login via other app/domain

### What do you see instead?

the domain name should not repeat in redirect_uri:
```
https://keycloak.dev.domain.com/realms/erp/protocol/openid-connect/auth?client_id=ui&redirect_uri=https%3A%2F%2Ferp.dev.domain.com%2F%23iss%3Dhttps%253A%252F%252Fkeycloak.dev.domain.com%252Frealms%252Ferp%26iss%3Dhttps%253A%252F%252Fkeycloak.dev.domain.com%252Frealms%252Ferp%26iss%
```
