### ISSUE TITLE
[bitnami/redis] sentinel.externalAccess.service.annotations values are ignored

### ISSUE THREAD

**Issue by MarijnMB** [bitnami/charts#33270]
### Name and Version

bitnami/redis 20.13.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Values entered for `sentinel.externalAccess.service.annotations` key in _values.yaml_ are ignored, never end up in the service k8s resource.

### Are you using any custom parameters or values?

```yaml
sentinel:
  enabled: true
  externalAccess:
    enabled: true
    service:
      annotations:
        yomomma: fat
```

### What is the expected behavior?

The Kubernetes service has any annotation set in the _values.yaml_ file supplied.

### What do you see instead?

None of the custom annotations present
