### ISSUE TITLE
[bitnami/kafka] bug: provisioning job will fail when startup kafka with ssl

### ISSUE THREAD

**Issue by chenraoCR** [bitnami/charts#33301]
### Name and Version

bitnami/kafka:32.2.2

### What architecture are you using?

None

### What steps will reproduce the bug?

1. deploy bitnami/kafka:32.2.2 helm chart, kafka-controller can startup, but kafka-provisioning job will fail

![Image](https://github.com/user-attachments/assets/1449a633-3b7e-4167-a83c-b7a2db3e2fe4)

![Image](https://github.com/user-attachments/assets/f49064f1-0c53-4c17-a8bf-2e60a65d6fb7)

### Are you using any custom parameters or values?

```
listeners:
  client:
    protocol: SSL
tls:
  type: pem
  existingSecret: kafka-tls-secret
provisioning:
  enabled: true
  topics:
    - name: test
  auth:
    tls:
      type: pem
      certificatesSecret: kafka-tls-secret
```

### What is the expected behavior?

kafka-controller pod should startup and also kafka-provisioning job should succeed and topic `test` should be created

### What do you see instead?

kafka-provisioning job failed

### Additional information

the initContainer `wait-for-available-kafka` will failed as in the container, it will use kafka client properties file, if kafka startup with ssl, means we set  `.Values.listeners.client.protocol` to SSL, then in `client.properties` file, we make ssl related settings, but we did not mount the certs into this ininContainer
