### ISSUE TITLE
mongo - mistake in pdb documentation

### ISSUE THREAD

**Issue by macikacz** [bitnami/charts#3332]
In readme there is PBD documentation for database/arbiter:

pdb.minAvailable   nil
**pdb.maxUnavailable 1**

But in values.yaml  properties have different values:
```

pdb:
  create: false
  ## Min number of pods that must still be available after the eviction
  ##
  minAvailable: 1
  ## Max number of pods that can be unavailable after the eviction
  ##
  # maxUnavailable: 1
```
