### ISSUE TITLE
Schema-registry helm does not allow ssl port as service

### ISSUE THREAD

**Issue by sameergithub5** [bitnami/charts#33323]
### Name and Version

bitnami/schema-registy:24.0.0

### What architecture are you using?

None

### What steps will reproduce the bug?

We want to enable https listener for schema registry, but whenever we put the extra ports option apart from 8081/http it does not expose it in the service.
```yaml
listeners: http://0.0.0.0:8081, https://0.0.0.0:8082
 ports:
    http: 8081
    https: 8082
```

### Are you using any custom parameters or values?

No.

### What is the expected behavior?

We expect it to be exposed same port as http 8081 port something like https://localhost:8082

### What do you see instead?

It only gives us the 8081 interface, nothing on 8082
