### ISSUE TITLE
[bitnami/postgresql] adding pvc for replication pods in baremetal setups

### ISSUE THREAD

**Issue by raphaelcervantes** [bitnami/charts#3341]
**Which chart**:
postgresql-8.9.2

**Is your feature request related to a problem? Please describe.**
In bare-metal setups, you have to supply the storage class and persistent volumes manually (there is no automatic provisioner like there is in AWS). The chart doesn't seem to allow me to specify a persistent volume claim for each replication pod.

To go more in detail. 
I installed kubernetes in my own setup. I defined my own storage class. 
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```
My own pv
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-test-pv
  labels:
    type: local
    app: postgresql
spec:
  storageClassName: local-storage
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/bitnami/postgresql"
```
And my own pvc
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-test-pvc
  labels:
    app: postgresql
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
```

I am able to get the postgresql installation to properly use my persistent volume. Below is my custom values for the postgresql helm chart.
```
postgresqlUsername: "orpheus_master"
existingSecret: postgres-secret

persistence:
  enabled: true
  existingClaim: postgres-test-pvc

volumePermissions:
  enabled: true
```

However, if I try to add replication, 
```
postgresqlUsername: "orpheus_master"
existingSecret: postgres-secret

persistence:
  enabled: true
  existingClaim: postgres-test-pvc

volumePermissions:
  enabled: true

updateStrategy:
  type: RollingUpdate

replication:
  enabled: true
  user: repl_user
  ## password: repl_password
  slaveReplicas: 1
  ## Set synchronous commit mode: on, off, remote_apply, remote_write and local
  ## ref: https://www.postgresql.org/docs/9.6/runtime-config-wal.html#GUC-WAL-LEVEL
  synchronousCommit: "on"
  ## From the number of `slaveReplicas` defined above, set the number of those that will have synchronous replication
  ## NOTE: It cannot be > slaveReplicas
  numSynchronousReplicas: 1
  ## Replication Cluster application name. Useful for defining multiple replication policies
  applicationName: my_application0
```
then the standby pod doesn't have a pvc to bind to. 
```
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  running "VolumeBinding" filter plugin for pod "postgresql-test-slave-0": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling  <unknown>  default-scheduler  running "VolumeBinding" filter plugin for pod "postgresql-test-slave-0": pod has unbound immediate PersistentVolumeClaims

```
I don't see how I can configure the standby pods to use another pvc (or to not use persistence).

**Describe the solution you'd like**
I would like to assign a pvc to the replication pods.

**Describe alternatives you've considered**
I've considered not having replication.

**Additional context**
