### ISSUE TITLE
[bitnami/postgresql] hostpath pv + init.d file = touch .user_scripts_initialized': Permission denied

### ISSUE THREAD

**Issue by arobert-delfingen** [bitnami/charts#3345]
**Which chart**:
postgresql-9.1.2

**Describe the bug**
When using the postgres chart with a persistent volume of type HostPath and an init.d file the pod stay at CrashLoopBackOff, logs show the error : 
`touch: cannot touch '/bitnami/postgresql/.user_scripts_initialized': Permission denied`

**To Reproduce**
1. Use following pv :
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-postgresql-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /tmp/{{ .Release.Name }}/postgresql
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Release.Name }}-pvc-volume-postgres
```

2. Use following pvc :
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc-volume-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: {{ .Release.Name }}-postgresql-pv
```

3. Put a file called init.sh in docker-entrypoint-initdb.d folder containing
```
#!/bin/bash
echo "**** init postgres script called !***"
```

4. Use following values : 
```
volumePermissions:
  enabled: true
persistence:
  existingClaim: "{{ .Release.Name }}-pvc-volume-postgres"
```

**Expected behavior**
The pod starts properly.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.11-gke.5", GitCommit:"baccd25d44f1a0d06ad3190eb508784efbb990a5", GitTreeState:"clean", BuildDate:"2020-06-25T22:55:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Constated in GKE & RKE
