### ISSUE TITLE
Additional labels in alert-rules

### ISSUE THREAD

**Issue by vi4vikas** [bitnami/charts#33495]
### Name and Version

bitnami/thanos 16.0.5

### What is the problem this feature will solve?

In [alert-rule](https://github.com/bitnami/charts/tree/main/bitnami/thanos/templates/alert-rule), the additional labels are commonly used for PrometheusRule objects (containing a list of all the alert rules) and for each alert rule itself. Due to this, we cannot have a dynamic variable in the alert-rule's labels that would have been otherwise possible. 
For example: 
If we set `.Values.metrics.prometheusRule.additionalLabels` to something like:
```yaml
key1: value1
key2: value2
cluster: "{{`{{`}} $labels.cluster {{`}}`}}"
```
then the template is populated as:
> PrometheusRule Kubernetes Object:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: thanos-ruler
  namespace: "monitoring"
  labels:
    cluster: '{{ $labels.cluster }}'
    key1: value1
    key2: value2
spec:
...
```
and
> Alert Rule
```yaml
- alert: ThanosRuleQueueIsDroppingAlerts
annotations:
  description: Thanos Rule {{ $labels.instance }} is failing to queue alerts.
  runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosrulequeueisdroppingalerts
  summary: Thanos Rule is failing to queue alerts.
expr: |
  sum by (job, instance) (rate(thanos_alert_queue_alerts_dropped_total{job=~".*thanos-rule.*"}[5m])) > 0
for: 5m
labels:
  severity: critical
  key1: value1
  key2: value2
  cluster: '{{ $labels.cluster }}'
```

The later is fine, but with the PrometheusRule Kubernetes Object, Kubernetes complains about an invalid character. The error is as:
```
Error: UPGRADE FAILED: cannot patch "thanos-component-absent" with kind PrometheusRule: PrometheusRule.monitoring.coreos.com "thanos-component-absent" is invalid: metadata.labels: Invalid value: "{{ $labels.cluster }}": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

----

> Also, kinda similar issue is with annotations, where the annotation in `PrometheusRule` and `alert rule` is populated by the same variable. The user might not want to have the same annotations on both places.

### What is the feature you are proposing to solve the problem?

The proposed solution is to have 2 different helm parameters for both the labels, something like:
`.Values.commonLabels` and `.Values.commonAnnotations` to fill up for PrometheusRule object and 
`.Values.metrics.prometheusRule.labels` and `.Values.metrics.prometheusRule.annotations` to fill up for alert-rules.
