### ISSUE TITLE
[bitnami/postgresql-ha] Unable to set postgresql max_connections higher than 500

### ISSUE THREAD

**Issue by Linuxine** [bitnami/charts#33528]
### Name and Version

bitnami/postgresql-ha-15.1.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Hi,

When installing the postgresql-ha chart, I cannot set the parameter `max_connections` for Postgres above 500. I have succesfully set the environnement variable `$POSTGRESQL_MAX_CONNECTIONS`  to `1024` in the pods, I can see it connected to a pod or in my pod description:
```
POSTGRESQL_MAX_CONNECTIONS:              1024
```

The value is also present in the configuration file used by postgres:

```
/$ grep max_connections /opt/bitnami/postgresql/conf/postgresql.conf
max_connections = '1024'

postgres=# show config_file;
                 config_file
----------------------------------------------
 /opt/bitnami/postgresql/conf/postgresql.conf
```

But when checking what is the applied value in postgres, I get 500:

```
postgres=# show max_connections;
 max_connections
-----------------
 500
(1 row)
```

The only place where I find this value is in the file `/bitnami/postgresql/data/postgresql.auto.conf` which contains:

```
I have no name!@pg-ha-postgresql-ha-postgresql-1:/bitnami/postgresql/data$ cat postgresql.auto.conf
# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.
max_connections = '500'
```

So I guess an ALTER SYSTEM command must be performed at the init of Posgres to set this variable ? But I have inspected the image scripts, the helm chart, I am not able to determine where this value comes from.

### Are you using any custom parameters or values?

My value file for the installation is a followed:

```yaml
postgresql:
  replicaCount: 3
  username: xxx
  existingSecret: my-xx
  repmgrUsername: repmgr
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
      ephemeral-storage: 50Mi
  extendedConf: |-
    huge_pages = off
  maxConnections: 1024

volumePermissions:
  enabled: true

pgpool:
  replicaCount: 3
  adminUsername: admin
  existingSecret: xxx
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
      ephemeral-storage: 50Mi

persistence:
  enabled: true
```

### What is the expected behavior?

I was expected my `max_connections` setting to be set to 1024.

### What do you see instead?

The `max_connections` setting is set to 500, and I have no idea where this value comes from

### Additional information

Any help would be greatly appreciated ! Thanks a lot for your time !
