### ISSUE TITLE
[bitnami/keycloak] Java 21.0.6 crash on Apple M4 ARM in bitnami/keycloak-config-cli:6.4.0

### ISSUE THREAD

**Issue by m4dm4rtig4n** [bitnami/charts#33526]
### Name and Version

bitnami/keycloak:24.6.4

### What architecture are you using?

None

### What steps will reproduce the bug?

```bash
docker run --rm --name keycloak-config-cli bitnami/keycloak-config-cli:6.4.0
```

### Are you using any custom parameters or values?
```
keycloak:
  # https://artifacthub.io/packages/helm/bitnami/keycloak
  enabled: true
  production: true
  tls:
    autoGenerated: true
    enabled: true
  auth:
    adminUser: user
    existingSecret: keycloak
    passwordSecretKey: auth_admin_password
  postgresql:
    enabled: false
  externalDatabase:
    existingSecret: postgresql
    existingSecretDatabaseKey: database
    existingSecretHostKey: hostname
    existingSecretPasswordKey: user_password
    existingSecretPortKey: port
    existingSecretUserKey: username
  adminIngress:
    enabled: true
    hostname: auth-admin.localdev.me
  ingress:
    enabled: true
    hostname: auth.localdev.me
    ingressClassName: nginx
  initContainers:
  - args:
    - "until pg_isready -h $(POSTGRES_HOSTNAME) -p $(POSTGRES_PORT); do\n  echo \"Waiting\
      \ for PostgreSQL at $(POSTGRES_HOSTNAME):$(POSTGRES_PORT)...\";\n  sleep 2;\n\
      done\n"
    command:
    - sh
    - -c
    env:
    - name: POSTGRES_HOSTNAME
      valueFrom:
        secretKeyRef:
          key: hostname
          name: postgresql
    - name: POSTGRES_PORT
      valueFrom:
        secretKeyRef:
          key: port
          name: postgresql
    image: docker.io/postgres:14.17
    name: wait-for-postgres
  keycloakConfigCli:
    enabled: true
    existingConfigmap: keycloak
```
### What is the expected behavior?

Just run correctly with M4 :)

### What do you see instead?

Hey team,

There’s currently an issue running `bitnami/keycloak-config-cli:6.4.0` on Apple M4 (ARM) chips.

The core Keycloak project fixed this upstream ([[keycloak/keycloak#36008](https://github.com/keycloak/keycloak/issues/36008)](https://github.com/keycloak/keycloak/issues/36008)) by updating to Java 21.0.7+, which resolves SIGILL crashes on M4.

However, `bitnami/keycloak-config-cli` is still shipping with Java 21.0.6, which reproduces the same crash:

```
docker run --rm --name keycloak-config-cli bitnami/keycloak-config-cli:6.4.0
...
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x0000ffff8250ac5c, pid=1, tid=7
#
# JRE version:  (21.0.6+10)
# Java VM: OpenJDK 64-Bit Server VM (21.0.6+10-LTS, linux-aarch64)
...
# The crash happened outside the Java Virtual Machine in native code.
```

### Temporary fix ###

Add `-XX:UseSVE=0` to JVM 
```yaml
  keycloakConfigCli:
    enabled: true
    existingConfigmap: keycloak
    extraEnvVars:
    - name: JAVA_TOOL_OPTIONS
      value: -XX:UseSVE=0
```

### Additional information

**Expected behavior:**
Update the Java base image to 21.0.7+ (same as upstream Keycloak) to ensure M4 compatibility.

Thanks for addressing this!
