### ISSUE TITLE
[bitnami/grafana-operator] bug: json: cannot unmarshal string into Go struct field Route.items.spec.route.routes.matchers if type v1beta.Matcher

### ISSUE THREAD

**Issue by notjames** [bitnami/charts#33597]
### Name and Version

bitnami/grafana-operator:5.17.0-debian-12-r2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm still trying to determine this. TBD. It's a GrafanaNotificationPolicy CR I've installed. 

I only have two CRs installed:
```
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaNotificationPolicy
metadata:
  labels:
    argocd.argoproj.io/instance: grafana-alerts
  name: root-policy
  namespace: grafana
spec:
  allowCrossNamespaceImport: false
  instanceSelector:
    matchLabels:
      dashboards.grafana.com/instance: grafana
  resyncPeriod: 10m0s
  route:
    receiver: grafana-default-email
    routes:
      - matchers:
          - team=current-email
        receiver: grafana-default-email

```

```
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaNotificationPolicy
metadata:
  labels:
    argocd.argoproj.io/instance: grafana-alerts
  name: current-email
  namespace: grafana
spec:
  allowCrossNamespaceImport: false
  instanceSelector:
    matchLabels:
      dashboards.grafana.com/instance: grafana
  resyncPeriod: 10m0s
  route:
    receiver: grafana-default-email
    routes:
      - matchers:
          - team=current-email
        receiver: grafana-default-email
```

### Are you using any custom parameters or values?

Nothing custom.

### What is the expected behavior?

I would expect a linting of the CR to occur such that an error should be handled if the CR is invalid.

### What do you see instead?

Getting the following error:
```
1 reflector.go:166] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.32.2/tools/cache/reflector.go:251: Failed to watch *v1beta1.GrafanaNotificationPolicy: failed to list *v1beta1.GrafanaNotificationPolicy: json: cannot unmarshal string into Go struct field Route.items.spec.route.routes.matchers of type v1beta1.Matcher" logger="UnhandledError"
```

Seems like this should be a handled error but I'm still tracking down the offending JSON.
