### ISSUE TITLE
[bitnami/grafana] Service Monitor "wrong number of args for include: want 2 got 0" since `v11.6.4`

### ISSUE THREAD

**Issue by Nicolas-M** [bitnami/charts#33623]
### Name and Version

bitnami/grafana 11.6.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Enable the Grafana's chart metrics' service monitor:

```yaml
## Prometheus metrics
##
metrics:
  ## @param metrics.enabled Enable the export of Prometheus metrics
  ##
  enabled: true
  ## Prometheus Operator ServiceMonitor configuration
  serviceMonitor:
    ## @param metrics.serviceMonitor.enabled if `true`, creates a Prometheus Operator ServiceMonitor (also requires `metrics.enabled` to be `true`)
    ##
    enabled: true
``` 

2.  Install the helm chart.

### Are you using any custom parameters or values?

Setting `namespaceOverride` does not resolve the issue either. This error has been present in the chart since the changes in `v11.6.4`

### What is the expected behavior?

The chart can be deployed successfully. 

### What do you see instead?

The chart fails with an error similar to the one below. 

> Error: error running dry run for a diff: template: grafana/templates/servicemonitor.yaml:11:24: executing "grafana/templates/servicemonitor.yaml" at <include>: wrong number of args for include: want 2 got 0

### Additional information

_Note: I am using Terraform to deploy the chart (hence the format of the error message, but I believe the error still applies._
