### ISSUE TITLE
[bitnami/keycloak] No admin console loaded

### ISSUE THREAD

**Issue by cmonty14** [bitnami/charts#33664]
### Name and Version

bitnami/keycloak 1.23

### What architecture are you using?

None

### What steps will reproduce the bug?

I configured K8s with an Istio Gateway ingress controller.
For deployment of bitnami/keycloak I'm using these values.yaml:
```yaml
global:
  storageClass: "default"

# PostgreSQL Configuration
postgresql:
  enabled: true
  auth:
    username: "keycloak"
    password: "keycloak"
    database: "keycloakdb"

# Keycloak Configuration
keycloak:
  auth:
    adminUser: ""
    adminPassword: ""

ingress:
  enabled: false

logging:
  level: DEBUG

extraEnvVars:
  - name: KEYCLOAK_PROXY
    value: "edge"
  - name: KEYCLOAK_HOSTNAME
    value: "keycloak.sle-stage.devsys.net"
```

Istio gateway is configured with SSL Termination.
And here's the virtual service manifest:
```yaml
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: keycloak
  namespace: keycloak
spec:
  hosts:
    - "keycloak.sle-stage.devsys.net"  # Match the host in your Gateway
  gateways:
    - istio-system/sle-stage-gateway  # Reference your Gateway
  http:
    - match:
        - uri:
            prefix: "/"  # For keycloak.sle-stage.devsys.net, match all paths and port 80
      route:
        - destination:
            host: keycloak
            port:
              number: 80

```
Could you please assist with troubleshooting this issue?

THX

### What is the expected behavior?

Login screen

### What do you see instead?

![Image](https://github.com/user-attachments/assets/ce261701-67fe-4995-b561-0486385ab293)
