### ISSUE TITLE
[bitnami/contour] Envoy config is not update by helm chart

### ISSUE THREAD

**Issue by djsmicks** [bitnami/charts#33663]
### Name and Version

bitnami/contour 19.3.2

### What architecture are you using?

None

### What steps will reproduce the bug?

`configInline` appears to only update the contour pod and not the envoy pods creating unexpected results.

Timeout and circuit-breaker are not correctly setup in envoy.

in my helm chart i set 

```
configInline:
  cluster:
    circuit-breakers:
      max-connections: 100000000
      max-pending-requests: 50000000
      max-requests: 100000000
      max-retries: 5
    per-connection-buffer-limit-bytes: 100485760
  timeouts:
    request-timeout: infinity
    stream-idle-timeout: infinity
    connection-idle-timeout: infinity
    connection-shutdown-grace-period: 30s
    connect-timeout: 30s
  listener:
    per-connection-buffer-limit-bytes: 100485760
```

To validate if this config applied correctly, I kubectl exec into the envoy pod

Then run `cat config/envoy.json`
Where i get 

```
{"static_resources":{"clusters":[{"name":"contour","alt_stat_name":"contour_contour_8001","type":"STRICT_DNS","connect_timeout":"5s","load_assignment":{"cluster_name":"contour","endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"address":"contour","port_value":8001}}}}]}]},"circuit_breakers":{"thresholds":[{"priority":"HIGH","max_connections":100000,"max_pending_requests":100000,"max_requests":60000000,"max_retries":50,"track_remaining":true},{"max_connections":100000,"max_pending_requests":100000,"max_requests":60000000,"max_retries":50,"track_remaining":true}]},"typed_extension_protocol_options":{"envoy.extensions.upstreams.http.v3.HttpProtocolOptions":{"@type":"type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions","explicit_http_config":{"http2_protocol_options":{}}}},"transport_socket":{"name":"envoy.transport_sockets.tls","typed_config":{"@type":"type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext","common_tls_context":{"tls_params":{"tls_maximum_protocol_version":"TLSv1_3"},"tls_certificate_sds_secret_configs":[{"name":"contour_xds_tls_certificate","sds_config":{"path_config_source":{"path":"/config/resources/sds/xds-tls-certificate.json"},"resource_api_version":"V3"}}],"validation_context_sds_secret_config":{"name":"contour_xds_tls_validation_context","sds_config":{"path_config_source":{"path":"/config/resources/sds/xds-validation-context.json"},"resource_api_version":"V3"}}}}},"upstream_connection_options":{"tcp_keepalive":{"keepalive_probes":3,"keepalive_time":30,"keepalive_interval":5}}},{"name":"envoy-admin","alt_stat_name":"contour_envoy-admin_9001","type":"STATIC","connect_timeout":"0.250s","load_assignment":{"cluster_name":"envoy-admin","endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"pipe":{"path":"/admin/admin.sock","mode":420}}}}]}]}}]},"dynamic_resources":{"lds_config":{"api_config_source":{"api_type":"GRPC","transport_api_version":"V3","grpc_services":[{"envoy_grpc":{"cluster_name":"contour","authority":"contour"}}]},"resource_api_version":"V3"},"cds_config":{"api_config_source":{"api_type":"GRPC","transport_api_version":"V3","grpc_services":[{"envoy_grpc":{"cluster_name":"contour","authority":"contour"}}]},"resource_api_version":"V3"}},"layered_runtime":{"layers":[{"name":"dynamic","rtds_layer":{"name":"dynamic","rtds_config":{"api_config_source":{"api_type":"GRPC","transport_api_version":"V3","grpc_services":[{"envoy_grpc":{"cluster_name":"contour","authority":"contour"}}]},"resource_api_version":"V3"}}},{"name":"admin","admin_layer":{}}]},"admin":{"access_log":[{"name":"envoy.access_loggers.file","typed_config":{"@type":"type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog","path":"/dev/null"}}],"address":{"pipe":{"path":"/admin/admin.sock","mode":420}}},"default_regex_engine":{"name":"envoy.regex_engines.google_re2","typed_config":{"@type":"type.googleapis.com/envoy.extensions.regex_engines.v3.GoogleRE2"}}}
```

### Are you using any custom parameters or values?

```
configInline:
  cluster:
    circuit-breakers:
      max-connections: 100000000
      max-pending-requests: 50000000
      max-requests: 100000000
      max-retries: 5
    per-connection-buffer-limit-bytes: 100485760
  timeouts:
    request-timeout: infinity
    stream-idle-timeout: infinity
    connection-idle-timeout: infinity
    connection-shutdown-grace-period: 30s
    connect-timeout: 30s
  listener:
    per-connection-buffer-limit-bytes: 100485760
```

### What is the expected behavior?

```
max_connections":100000000,"max_pending_requests":50000000,"max_requests":100000000,"max_retries":5
connect-timeout: 30s
```
### What do you see instead?

```
max_connections":100000,"max_pending_requests":100000,"max_requests":60000000,"max_retries":50
connect-timeout: 5s
```
