### ISSUE TITLE
[bitnami/airflow] unable to run  version  airflow-10.2.8

### ISSUE THREAD

**Issue by sergesteban** [bitnami/charts#33685]
### Name and Version

bitnami/airflow 10.2.8

### What architecture are you using?

arm64

### Name and Version
bitnami/airflow:10.2.8

### Context
I need to update an airflow deployment that was deployed using version 10.2.8.

that version is old and it is not available 
`helm search repo bitnami/airflow --versions | grep 10.2.8`

- What I can do is to check which version is using the current deployment, package it local, upload to private repository, upgrade the value.yaml 

`helm get manifest airflow --namespace production | pbcopy`

results to se that I am using the following
```
helm.sh/chart: airflow-10.2.8
helm.sh/chart: redis-16.11.2
helm.sh/chart: postgresql-11.6.2
```

I downloaded each of this versions
- https://github.com/bitnami/charts/tree/airflow/10.2.8
- https://github.com/bitnami/charts/tree/postgresql/11.6.2
- https://github.com/bitnami/charts/tree/redis/16.11.2

first i tried only with postgresql since redis still has a 16.x.x version available
```
helm dependency update ./airflow
helm package ./airflow
```

following is the Chart.yml in ./airflow/
```yml
annotations:
  category: WorkFlow
apiVersion: v2
appVersion: 2.1.2
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: file://charts/postgresql
  version: 10.9.0
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 16.x.x
description: Apache Airflow is a platform to programmatically author, schedule and
  monitor workflows.
home: https://github.com/bitnami/charts/tree/master/bitnami/airflow
icon: https://bitnami.com/assets/stacks/airflow/img/airflow-stack-220x234.png
keywords:
- apache
- airflow
- workflow
- dag
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: airflow
sources:
- https://github.com/bitnami/bitnami-docker-airflow
- https://airflow.apache.org/
version: 10.2.8
```

### Are you using any custom parameters or values?

```
kubeVersion:
nameOverride:
fullnameOverride:
executor: "CeleryExecutor"
configurationConfigMap:
dagsConfigMap:
loadExamples: false
auth:
  forcePassword: true
  username: administrator
  password: {token}
  fernetKey: {token}
web:
  image:
    registry: docker.io
    repository: bitnami/airflow
    #tag: 2.0.0-debian-10-r8
    tag: 2.1.0-debian-10-r0
    pullPolicy: IfNotPresent
    pullSecrets: []
    debug: false
  replicaCount: 1
  hostAliases: []
  baseUrl: https://airflow-staging.agranimo.com
  containerPort: 8080
  extraEnvVars:
  - name: PYTHONPATH
    value: "${PYTHONPATH}:/opt/bitnami/airflow/dags/git_dataflow-dags:/opt/bitnami/airflow/plugins/git_dataflow-plugins"
  extraVolumeMounts:
    - name: airflow-pip-requirements-staging
      mountPath: /bitnami/python
  extraVolumes:
    - name: airflow-pip-requirements-staging
      configMap:
        name: dags-requirements
  livenessProbe:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
scheduler:
  image:
    registry: docker.io
    repository: bitnami/airflow-scheduler
    #tag: 2.0.0-debian-10-r8
    tag: 2.0.2-debian-10-r30
    pullPolicy: IfNotPresent
    pullSecrets: []
    debug: false
  replicaCount: 1
  extraEnvVars:
  - name: PYTHONPATH
    value: "${PYTHONPATH}:/opt/bitnami/airflow/dags/git_dataflow-dags:/opt/bitnami/airflow/plugins/git_dataflow-plugins"
  extraVolumeMounts:
    - name: airflow-pip-requirements-staging
      mountPath: /bitnami/python
  extraVolumes:
    - name: airflow-pip-requirements-staging
      configMap:
        name: dags-requirements
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
  priorityClassName: ''
worker:
  image:
    registry: docker.io
    repository: bitnami/airflow-worker
    #tag: 2.0.0-debian-10-r8
    tag:  2.0.2-debian-10-r29
    pullPolicy: IfNotPresent
    pullSecrets: []
    debug: false
  port: 8793
  replicaCount: 1
  hostAliases: []
  extraEnvVars:
  - name: PYTHONPATH
    value: "${PYTHONPATH}:/opt/bitnami/airflow/dags/git_dataflow-dags:/opt/bitnami/airflow/plugins/git_dataflow-plugins"
  extraVolumeMounts:
    - name: airflow-pip-requirements-staging
      mountPath: /bitnami/python
  extraVolumes:
    - name: airflow-pip-requirements-staging
      configMap:
        name: dags-requirements
  livenessProbe:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
  autoscaling:
    enabled: false
  updateStrategy: RollingUpdate
git:
  image:
    registry: docker.io
    repository: bitnami/git
    # tag: 2.30.0-debian-10-r27
    tag: 2.31.1-debian-10-r53
    pullPolicy: IfNotPresent
    pullSecrets: []
  dags:
    enabled: true
    repositories:
      - repository: https://{token}@gitlab.com/agranimo/dataflow.git
        branch: develop
        name: dataflow-dags
        path: "src/dags"
  plugins:
    enabled: true
    repositories: 
      - repository: https://{token}@gitlab.com/agranimo/dataflow.git
        branch: develop
        name: dataflow-plugins
        path: "src/plugins"
ldap:
  enabled: false
rbac:
  create: true
serviceAccount:
  create: true
podSecurityContext:
  enabled: true
  fsGroup: 1001
containerSecurityContext:
  enabled: true
  runAsUser: 1001
networkPolicies:
  enabled: false
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
podAffinityPreset: ''
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ''
  key: ''
  values: []
postgresql:
  enabled: true
  postgresqlUsername: bn_airflow
  postgresqlPassword: {token}
  postgresqlDatabase: bitnami_airflow
  existingSecret:
redis:
  enabled: true
  cluster:
    enabled: false
  existingSecret:
metrics:
  enabled: false
extraDeploy: []

```

### What is the expected behavior?

I would like to deploy in local 

### What do you see instead?

logs
```
[2025-05-14 00:35:59,516] {plugins_manager.py:232} ERROR - Failed to import plugin /opt/bitnami/airflow/plugins/git_dataflow-plugins/operators/integrations/agrospace_operator.py
[2025-05-14 00:36:00,179] {providers_manager.py:295} WARNING - Exception when importing 'airflow.providers.microsoft.mssql.hooks.mssql.MsSqlHook' from 'apache-airflow-providers-microsoft-mssql' package: /opt/bitnami/airflow/venv/lib/python3.8/site-packages/pymssql/_pymssql.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
[2025-05-14 00:36:00,591] {providers_manager.py:295} WARNING - Exception when importing 'airflow.providers.microsoft.mssql.hooks.mssql.MsSqlHook' from 'apache-airflow-providers-microsoft-mssql' package: /opt/bitnami/airflow/venv/lib/python3.8/site-packages/pymssql/_pymssql.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
administrator already exist in the db
airflow 00:36:06.90 INFO  ==> Persisting Airflow installation
airflow 00:36:07.24 INFO  ==> ** Airflow setup finished! **

airflow 00:36:07.37 INFO  ==> ** Starting Airflow **
```

`airflow-web-6d8f74c494-rnm97         1/2     CrashLoopBackOff   8 (0s ago)     42m`

### Additional information

I would like to know if this thought process is ok?
How can I ultimately upgrade the deployment in production safetly?
