### ISSUE TITLE
[bitnami/nginx] Helm upgrade fails with YAML parse error when using wildcard Ingress hostname in bitnami/nginx 20.0.2

### ISSUE THREAD

**Issue by kkmarv** [bitnami/charts#33692]
### Name and Version

bitnami/nginx 20.0.2

### What architecture are you using?

None

### What steps will reproduce the bug?

1. On my local machine
2. I set the Ingress hostname to a wildcard in values.yaml: 
   `ingress.hostname: "*.example.com"`
3. and then run 'helm upgrade -i nginx https://charts.bitnami.com/bitnami/nginx-20.0.2.tgz --values ./values.yaml'
4. I get a YAML parse error 

### Are you using any custom parameters or values?

```yaml
# values.yaml

ingress:
  enabled: true
  tls: true
  hostname: "*.example.com"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
```

### What is the expected behavior?

I expect the Helm templates to be able to handle wildcard hostnames, resulting in a succesfully created Ingress resource.

### What do you see instead?

```shell
Error: UPGRADE FAILED: YAML parse error on nginx/templates/ingress.yaml: error converting YAML to JSON: yaml: line 50: did not find expected alphabetic or numeric character
```

### Additional information

Helm templates should sanitize or encode wildcard hostnames to ensure they generate valid Kubernetes resources, especially for use in TLS secret names.

Relevant part:
https://github.com/bitnami/charts/blob/c8e3e76d9d2da66286eb512390ed7ce49199676b/bitnami/nginx/templates/ingress.yaml#L61
