### ISSUE TITLE
[bitnami/keycloak] Configuration in values.yaml is not set in container

### ISSUE THREAD

**Issue by cmonty14** [bitnami/charts#33697]
### Name and Version

bitnami/keycloak 24.3.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Define values.yaml

2. Deploy keycloak using `helm install keycloak bitnami/keycloak --namespace keycloak -f .\values.yaml`
3. Verify keycloak configuration using `kc.sh show-config`

### Are you using any custom parameters or values?

```
global:
  defaultStorageClass: "default"

# PostgreSQL Configuration
postgresql:
  enabled: true
  auth:
    username: "keycloak"
    password: ""
    database: "keycloakdb"

# Keycloak Configuration
keycloak:
  auth:
    adminUser: ""
    adminPassword: ""
  production: false
  proxy: "edge"
  proxyHeaders: "xforwarded"

ingress:
  enabled: false

logging:
  level: INFO
```

### What is the expected behavior?

Configuration parameters are set:
KC_PROXY=edge
KC_PROXY_HEADERS=xforwarded

### What do you see instead?

```
kc.sh show-config
Appending additional Java properties to JAVA_OPTS
Current Mode: development
Current Configuration:
        kc.health-enabled =  false (keycloak.conf)
        kc.cache-stack =  kubernetes (keycloak.conf)
        kc.db-username =  keycloak (keycloak.conf)
        kc.spi-admin-realm =  master (ENV)
        kc.spi-theme-static-max-age =  -1 (classpath application.properties)
        kc.spi-theme-cache-themes =  false (classpath application.properties)
        kc.log-level-org.infinispan.transaction.lookup.JBossStandaloneJTAManagerLookup =  WARN (classpath application.properties)
        kc.log-level-io.quarkus.config =  off (classpath application.properties)
        kc.log-console-output =  default (keycloak.conf)
        kc.hostname-strict =  false (keycloak.conf)
        kc.http-management-relative-path =  / (Persisted)
        kc.https-port =  8443 (keycloak.conf)
        kc.metrics-enabled =  false (keycloak.conf)
        kc.bootstrap-admin-username =  user (ENV)
        kc.db =  postgres (keycloak.conf)
        kc.db-password =  ******* (keycloak.conf)
        kc.log-level-io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor =  warn (classpath application.properties)
        kc.version =  26.2.4 (SysPropConfigSource)
        kc.db-url =  jdbc:postgresql://keycloak-postgresql:5432/keycloakdb?currentSchema=public (keycloak.conf)
        kc.http-relative-path =  / (keycloak.conf)
        kc.http-enabled =  true (keycloak.conf)
        kc.log-level-org.jboss.resteasy.resteasy_jaxrs.i18n =  WARN (classpath application.properties)
        kc.log-level-io.quarkus.arc.processor.BeanArchives =  off (classpath application.properties)
        kc.cache =  ispn (keycloak.conf)
        kc.log-level-io.quarkus.deployment.steps.ReflectiveHierarchyStep =  error (classpath application.properties)
        kc.spi-theme-cache-templates =  false (classpath application.properties)
        kc.http-port =  8080 (keycloak.conf)
        kc.bootstrap-admin-password-file =  /opt/bitnami/keycloak/secrets/admin-password (ENV)
        kc.log-level =  INFO (keycloak.conf)
        kc.provider.file.keycloak-metrics-spi-7.0.0.jar.last-modified =  1747209190021 (Persisted)
        kc.log-level-io.quarkus.arc.processor.IndexClassLookupUtils =  off (classpath application.properties)
        kc.log-level-org.hibernate.engine.jdbc.spi.SqlExceptionHelper =  off (classpath application.properties)
```
