### ISSUE TITLE
[bitnami/redis]  Regression regarding ACL with helper function

### ISSUE THREAD

**Issue by TarQ1** [bitnami/charts#33702]
### Name and Version

bitnami/redis 21.0.3 to 20.11.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1, Using an umbrella chart
2. Run `helm -n dev upgrade --install --timeout 10m redis /home/devops/work/helmredis/chart -f /tmp/ssm/dev/dev/redis/24624/dev/dev.yaml --set env=dev`

here is my umbrella chart :
```
apiVersion: v2
name: redis
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: 1.0.0

dependencies:
- name: redis
  version: "21.0.3"
  repository: "https://charts.bitnami.com/bitnami"

```

### Are you using any custom parameters or values?

```
redis:
  global:
    imageRegistry: XXXXXXXXXXXX.dkr.ecr.eu-west-3.amazonaws.com/docker-hub
  auth:
    enabled: true
    password: "XXXXXXXXXXXX"
    acl:
      enabled: true
      sentinel: false
      users:
      - username: "myuser"
        password: "XXXXXXXXXXXX"
        enabled: "on"
        commands: "+@all -@dangerous"
        keys: "~*"
        channels: "&*"

  sentinel:
    enabled: true
    image:
      registry: XXXXXXXXXXXX.dkr.ecr.eu-west-3.amazonaws.com/docker-hub

  commonConfiguration: |
    port 6379
    timeout 300
    loglevel notice
    databases 16

    appendonly no

global:
  security:
    allowInsecureImages: true
```

### What is the expected behavior?

Release "redis" has been upgraded. Happy Helming!

### What do you see instead?

You get the following error:
```
Error: UPGRADE FAILED: template: redis/charts/redis/templates/sentinel/statefulset.yaml:49:38: executing "redis/charts/redis/templates/sentinel/statefulset.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: redis/charts/redis/templates/configmap.yaml:62:28: executing "redis/charts/redis/templates/configmap.yaml" at <include "common.secrets.get" (dict "secret" $userSecret "key" .username "context" $)>: error calling include: template: redis/charts/redis/templates/_helpers.tpl:218:20: executing "common.secrets.get" at <index $secret.data .key>: error calling index: index of untyped nil
```

### Additional information

In the version `20.11.5` the bug does not appear since `common.secrets.get` was not defined in `_helpers.tpl` and not used in `configmap.yaml` 

Thanks
