### ISSUE TITLE
rabbitmq-cluster/toplogy-operator broken startup command

### ISSUE THREAD

**Issue by Soortor** [bitnami/charts#33716]
### Name and Version

4.4.11

### What steps will reproduce the bug?

The last working version was 4.4.7.

Since then, the startup command has changed from "/manager" to "manager".

This produces the following error on startup: 

```
rabbitmq-topology-operator "runc create failed: unable to start container process: exec: "manager"
```

### What do you see instead?

Reverting the command to the one with a backslash fixes the issue.

**Comment by carrodher** [comment]
Could you please provide more info about how you are deploying the chart?

**Comment by Soortor** [comment]
The chart is deployed via ArgoCD using two files.

Chart.yaml
```yaml
apiVersion: v2
name: rabbitmq-operator
description: RabbitMQ Operator Helm Chart

version: 1.0.0

dependencies:
  - name: rabbitmq-cluster-operator
    version: 4.4.11
    repository: https://charts.bitnami.com/bitnami
```

Values.yaml
```yaml
rabbitmq-cluster-operator:
  global:
    imageRegistry: "redacted"
    security:
      allowInsecureImages: true
  clusterOperator:
    image:
      repository: docker.io/rabbitmqoperator/cluster-operator
      tag: 2.13.0
    nodeSelector:
      kubernetes.azure.com/agentpool: main
  msgTopologyOperator:
    image:
      repository: docker.io/rabbitmqoperator/messaging-topology-operator
      tag: 1.17.0
    nodeSelector:
      kubernetes.azure.com/agentpool: main
```
