### ISSUE TITLE
image registry does not overwrite global.imageRegistry

### ISSUE THREAD

**Issue by davgia** [bitnami/charts#33710]
### Name and Version

bitnami/common 2.31.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. (just for context) harbor private instance with two projects:
   * my-project: contains a custom bitnami nginx image
   * docker.io: proxy cache for registry-1.docker.io
3. (just for context) empty namespace in Kubernetes cluster 1.31.4
4. deploy nginx chart: `helm template oci://registry-1.docker.io/bitnamicharts/nginx -n demo -f values.yaml`
5. the deployment manifest has the wrong metrics image

### Are you using any custom parameters or values?

``` yaml
global:
  imageRegistry: harbor.example.com
  security:
    allowInsecureImages: true

image:
  tag: 1.0.0
  repository: my-project/frontend # <-- this is fine because of the global image registry

metrics:
  enabled: true
  image:
    registry: harbor.example.com/docker.io # <-- this seems to be ignored
    # repository: docker.io/bitnami/nginx-exporter <-- this is what I use to achieve what I need
```

### What is the expected behavior?

the explicit declaration of the registry in the specific image block should override the global.imageRegistry value, instead I see that global value is used instead

### What do you see instead?

This is the renderer deployment (snippet, I've removed not relevant values):

``` yaml
# Source: nginx/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
# [...]
spec:
# [...]
  template:
# [...]
    spec:
# [...]
      containers:
        - name: nginx
          image: harbor.example.com/my-project/frontend:1.0.0
# [...]
        - name: metrics
          image: harbor.example.com/bitnami/nginx-exporter:1.4.2-debian-12-r1
# [...]
```

For me, the explicit declaration of the registry should override the global.imageRegistry value, so it should be:

``` yaml
# Source: nginx/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
# [...]
spec:
# [...]
  template:
# [...]
    spec:
# [...]
      containers:
        - name: nginx
          image: harbor.example.com/my-project/frontend:1.0.0
# [...]
        - name: metrics
          image: harbor.example.com/docker.io/bitnami/nginx-exporter:1.4.2-debian-12-r1
# [...]
```
