### ISSUE TITLE
default pipeline configuration is still being used instead of my custom

### ISSUE THREAD

**Issue by uchris13** [bitnami/charts#33730]
### Name and Version

bitnami/logstash 8.18.0-debian-12-r0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am deploying via ansible. Nothing fails but the pipeline is loaded as per default and not my configuration

### Are you using any custom parameters or values?

These are the values & configmap i am using

```yaml
replicaCount: 3

image:
  registry: docker.io
  repository: bitnami/logstash
  tag: 8.18.0-debian-12-r0
  pullPolicy: IfNotPresent

enableMultiplePipelines: false
configFileName: "logstash.conf"

existingPipeline:
  configMap: "logstash-pipeline"
  mountPath: "/bitnami/logstash/pipeline"

extraConfigurationFiles:
  logstash.yml: |
    api.http.host: "0.0.0.0"
    path.data: /bitnami/logstash/data
    queue.type: persisted
    queue.max_bytes: 1gb
    pipeline.buffer.type: heap

persistence:
  enabled: true
  storageClass: ceph-rbd
  accessModes:
    - ReadWriteOnce
  size: 20Gi
  mountPath: /bitnami/logstash/data

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2
    memory: 2Gi

volumePermissions:
  enabled: true
  securityContext:
    runAsUser: 0

podSecurityContext:
  fsGroup: 1001

containerSecurityContext:
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - "ALL"
  seccompProfile:
    type: RuntimeDefault

extraEnvs:
  - name: TZ
    value: Europe/Madrid

initContainers:
  - name: install-opensearch-plugin
    image: docker.io/bitnami/logstash:8.18.0-debian-12-r0
    command:
      - /bin/bash
      - -ec
      - |
        /opt/bitnami/logstash/bin/logstash-plugin install --no-verify logstash-output-opensearch
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: logstash-plugins
        mountPath: /opt/bitnami/logstash/plugins

extraVolumes:
  - name: logstash-plugins
    emptyDir: {}

extraVolumeMounts:
  - name: logstash-plugins
    mountPath: /opt/bitnami/logstash/plugins

livenessProbe:
  enabled: true
  initialDelaySeconds: 90
  periodSeconds: 10
  failureThreshold: 6

readinessProbe:
  enabled: true
  initialDelaySeconds: 45
  periodSeconds: 10
  failureThreshold: 6

podAntiAffinityPreset: hard
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: logging
data:
  logstash.conf: |
    input {
      tcp {
        port => 5044
        codec => json
      }
    }
    output {
      opensearch {
        hosts => ["https://opensearch-ha-svc.opensearch.svc:9200"]
        auth_type => {
          type => "basic"
          user => "admin"
          password => "admin"
        }
        ssl => true
        ssl_certificate_verification => false
        index => "logs-%{+YYYY.MM.dd}"
      }
    }
```

### What do you see instead?
```
kubectl exec -n logging logstash-0 -- cat /opt/bitnami/logstash/pipeline/logstash.conf
Defaulted container "logstash" out of: logstash, volume-permissions (init), install-opensearch-plugin (init)
input {
  # udp {
  #   port => 1514
  #   type => syslog
  # }
  # tcp {
  #   port => 1514
  #   type => syslog
  # }
  http { port => 8080 }

}
output {
  # elasticsearch {
  #   hosts => ["${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]
  #   manage_template => false
  #   index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
  # }
  # gelf {
  #   host => "${GRAYLOG_HOST}"
  #   port => ${GRAYLOG_PORT}
  # }
  stdout {}
```
