### ISSUE TITLE
[bitnami/thanos] cant start some services because wrong mount of storeconfig

### ISSUE THREAD

**Issue by lfdominguez** [bitnami/charts#3375]
https://github.com/bitnami/charts/blob/5f4552393784db0359a7d6e2a3186fb8cb26aa02/bitnami/thanos/templates/storegateway/statefulset.yaml#L104

Hi, my deploy of the last chart version make a CrashLoopBackError on some services: example of thanos-storegateway log:

![image](https://user-images.githubusercontent.com/5604131/89791220-012e3380-daf1-11ea-9b89-81caee9f9b29.png)

My values.yaml is:

```yaml
objstoreConfig: |-
  type: s3
  config:
    bucket: thanos
    endpoint: {{ include "thanos.minio.fullname" . }}.monitor.svc.cluster.local:9000
    access_key: minio
    secret_key: minio123
    insecure: true
querier:
  dnsDiscovery:
    sidecarsService: prometheus-operator-prometheus-thanos
    sidecarsNamespace: monitoring
bucketweb:
  enabled: true
compactor:
  enabled: true
storegateway:
  enabled: true
ruler:
  enabled: true
  alertmanagers:
    - http://prometheus-operator-alertmanager.monitor.svc.cluster.local:9093
  config: |-
    groups:
      - name: "metamonitoring"
        rules:
          - alert: "PrometheusDown"
            expr: absent(up{prometheus="monitoring/prometheus-operator"})
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
minio:
  enabled: true
  accessKey:
    password: "minio"
  secretKey:
    password: "minio123"
  defaultBuckets: "thanos"
```
I think that the problem is how you mount the secret, you're mounting the overall secret, in this case, kubernetes mount in a directory all the keys, because that the error of `is a directory`
