### ISSUE TITLE
[bitnami/postgres-ha] witness matches multiple PodDisruptionBudgets

### ISSUE THREAD

**Issue by whg517** [bitnami/charts#33798]
### Name and Version

bitnami/postgres 16.0.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

helm install postgresql-ha oci://registry-1.docker.io/bitnamicharts/postgresql-ha --version 16.0.5 -f postgresql-ha-values.yaml

describe witness pod:

```log
│ Events:
│   Type     Reason     Age                     From               Message
│   ----     ------     ----                    ----               -------
│   Normal   Scheduled  6m39s                   default-scheduler  Successfully assigned infra-database/postgresql-ha-postgresql-witness-0 to prod-kube1-sh-node-014.tendata.k8s
│   Normal   Pulled     6m37s                   kubelet            Container image "docker.io/bitnami/os-shell:12-debian-12-r43" already present on machine
│   Normal   Created    6m37s                   kubelet            Created container init-chmod-data
│   Normal   Started    6m37s                   kubelet            Started container init-chmod-data
│   Normal   Created    5m9s (x2 over 6m36s)    kubelet            Created container postgresql
│   Normal   Started    5m8s (x2 over 6m36s)    kubelet            Started container postgresql
│   Warning  Unhealthy  3m39s (x12 over 5m59s)  kubelet            Liveness probe failed: bash: line 1: $POSTGRES_PASSWORD_FILE: ambiguous redirect
│ psql: error: connection to server at "127.0.0.1", port 5432 failed: fe_sendauth: no password supplied
│   Normal   Killing                       3m39s (x2 over 5m9s)  kubelet            Container postgresql failed liveness probe, will be restarted
│   Warning  FailedPreStopHook             3m39s (x2 over 5m9s)  kubelet            PreStopHook failed
│   Normal   Pulled                        93s (x5 over 6m36s)   kubelet            Container image "docker.io/bitnami/postgresql-repmgr:17.5.0-debian-12-r2" already present on machine
│   Warning  MultiplePodDisruptionBudgets  8s (x7 over 2m8s)     controllermanager  Pod "infra-database"/"postgresql-ha-postgresql-witness-0" matches multiple PodDisruptionBudgets.  Chose "postgresql-ha-postgresql" arbitrarily.
```

### Are you using any custom parameters or values?

```yaml
# 使用 bitnami 的 postgresql-ha chart 部署 PostgreSQL 高可用集群
# helm pull oci://registry-1.docker.io/bitnamicharts/postgresql-ha --version 16.0.5
# helm install postgresql-ha oci://registry-1.docker.io/bitnamicharts/postgresql-ha --version 16.0.5 -f postgresql-ha-values.yaml
#

global:
  storageClass: openebs-single-replica
  postgresql:
    # Existing secret with postgresql password, must contain key:
    #   - `password` (for the postgres user)
    #   - `repmgr-password` (for the repmgr user)
    existingSecret: postgresql-password
  pgpool:
    # Existing secret with pgpool admin password, must contain key:
    #   - `admin-password`
    existingSecret: pgpool-password

# If your cluster is using a custom domain, must be set.
clusterDomain: ******

postgresql:
  # Having 3 replicas is the minimum to get quorum when promoting a new primary.
  replicaCount: 3
  resources:
    requests:
      cpu: 2
      memory: 2Gi
    limits:
      cpu: 2
      memory: 2Gi
  maxConnections: 10000
  usePgRewind: true  # 在出现双主问题时，可以使用 pg_rewind 工具来恢复数据一致性
  repmgrFenceOldPrimary: true # 在节点恢复时，确保旧的主节点被正确地降级为备用节点，从而避免双主问题
  extendedConf: |
    max_slot_wal_keep_size = '1GB'


pgpool:
  replicaCount: 3
  customUsersSecret: pgpool-customusers
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 500m
      memory: 2Gi


witness:
  create: true
  replicaCount: 1
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 512Mi


persistence:
  enabled: true
  size: 40Gi

persistentVolumeClaimRetentionPolicy:
  enabled: true
  whenScaled: Retain
  whenDeleted: Retain

# 需要开启卷权限，要不然可能会出现无法写入配置的情况
volumePermissions:
  enabled: true

```

### What is the expected behavior?

witness pod is fine, bit it CrashLoopBackOff.

### What do you see instead?

witness pod is fine, bit it got `matches multiple PodDisruptionBudgets` warning.

### Additional information

i note `postgresql` has `role=data` label and `witness` has `role=witness` label , so i fix it to add additional label `role=data` to postgresql pdb.
