### ISSUE TITLE
[bitnami/airflow] DB migration does not run on argocd

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [bitnami/charts#33807]
### Name and Version

bitnami/airflow 24.1.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Hi ! 

We are trying to deploy airflow bitnami via argocd with this config.
```
airflow:
  setupDBJob:
    enabled: true
    useHelmHooks: false
    applyCustomEnv: false

```

But for some reason the migration script never gets started.
I took a look at the files and it seems that setupDBJob need to be enabled for the job to be triggered but I can't even see it in `k get jobs`.

Would you have any clue please? 

Thanks !

### What do you see instead?

Jobs never gets started
