### ISSUE TITLE
Custom logo not being loaded

### ISSUE THREAD

**Issue by lukeemhigh** [bitnami/charts#33818]
### Name and Version

bitnami/superset 0.13.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am currently facing an issue while trying to brand and instance of superset with some custom logos/favicons, but my logo isn't showing correctly.

I have setup a configMap containing the files and then mounted that through the `extraVolumeMounts` key in my `values.yaml` file (see below).

I also tried to mount the files under a different path but with no luck.

Lookin for the files inside the pod, I can find them, but are owned by root. Is this a problem?

![Image](https://github.com/user-attachments/assets/ef083081-08ab-4966-a338-e7d6d5ea4dba)

### Are you using any custom parameters or values?

```yaml
  configOverrides:
    my_override: |
      APP_ICON = "/static/assets/images/company_logo.png"
      FAVICONS = [{"href": "/static/assets/images/company_logo.png"}]
      SUPERSET_LOGO_TARGET_PATH = "/"

   extraVolumes:
     - name: logo-volume
       configMap:
         name: logo-configmap
  
   extraVolumeMounts:
     - name: logo-volume
       mountPath: /app/superset/static/assets/images/
       readOnly: false
```

### What is the expected behavior?

Custom logos being properly shown.

### What do you see instead?

![Image](https://github.com/user-attachments/assets/b61b8fe4-a61e-4534-b4ee-03f1d7733a23)

### Additional information

I think the problem may be that the custom assets are owned by root by default and I can't change ownership even with `readOnly` set to `false`.
