### ISSUE TITLE
[bitnami/redis] Sentinel - Prestop hooks don't use external hostnames and don't log to container stdout

### ISSUE THREAD

**Issue by nicolas-laduguie** [bitnami/charts#33828]
### Name and Version

bitnami/redis 21.1.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Create a sentinel enabled cluster, with externalAccess.enabled= true, and providing a list of sentinel.externalAccess.service.loadBalancerIP
Wait for the cluster to be ready
Stop the master pod
The prestop hook will not log anything and will not wait for the failover to happen, because the identified hostname and the master hostname will differ.

### Are you using any custom parameters or values?

```yaml
sentinel:
  externalAccess:
    enabled: true
    service:
      loadBalancerIP:
        - redis-node-0.customdomain
        - redis-node-1.customdomain
        - redis-node-2.customdomain
     disableLoadBalancerIP: true
```

### What is the expected behavior?

The prestop hooks (both prestop-sentinel.sh and prestop-redis.sh) should identify the current node hostname with its external hostname, given that we enabled sentinel.externalAccess, that we provided loadBalancerIP list, which makes nodes identified by those loadBalancerIPs with `replica-announce-ip` and `sentinel announce-ip`

### What do you see instead?

No logs from prestop hook, and the master is being terminated non gracefully, so without triggering a sentinel failover.
