### ISSUE TITLE
[bitnami/apisix] Fix DOCS for Standalone Mode

### ISSUE THREAD

**Issue by jmorenoc-o** [bitnami/charts#33838]
### Name and Version

bitnami/apisix 4.2.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When using the documentation example values for standalone_mode: https://github.com/bitnami/charts/tree/main/bitnami/apisix#standalone-mode

And execute:
`helm template .`

I have an error.

### Are you using any custom parameters or values?

Documented example values for standalone mode https://github.com/bitnami/charts/tree/main/bitnami/apisix#standalone-mode

Values:
```yaml
controlPlane:
  enabled: false
ingressController:
  enabled: false
etcd:
  enabled: false
dashboard:
  enabled: false
dataPlane:
  extraConfig:
    deployment:
      role_data_plane:
        config_provider: yaml
  extraVolumes:
    - name: routes
      configMap:
        name: apisix-routes
  extraVolumeMounts:
    - name: routes
      mountPath: /usr/local/apisix/conf/apisix.yaml
      subPath: apisix.yaml
extraDeploy:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: apisix-routes
    data:
      apisix.yaml: |-
        routes:
          -
            uri: /hello
            upstream:
                nodes:
                    "127.0.0.1:1980": 1
                type: roundrobin
        #END

```

### What is the expected behavior?

Generate template without errors.

### What do you see instead?

```
Error: template: apisix/charts/apisix/templates/data-plane/dep-ds.yaml:88:12: executing "apisix/charts/apisix/templates/data-plane/dep-ds.yaml" at <include "apisix.renderConfInitContainer" (dict "component" "data-plane" "context" $)>: error calling include: template: apisix/charts/apisix/templates/_helpers.tpl:674:118: executing "apisix.renderConfInitContainer" at <include "apisix.etcd.authEnabled" .>: error calling include: template: apisix/charts/apisix/templates/_helpers.tpl:550:14: executing "apisix.etcd.authEnabled" at <.Values.etcd.enabled>: nil pointer evaluating interface {}.etcd
```

### Additional information

I solve the problem using:

`usePasswordFiles: false`

Please review and update DOCS or tell me if I am doing something wrong.
