### ISSUE TITLE
Readiness health check causing memory leak/spike & ooming

### ISSUE THREAD

**Issue by danfoley1991** [bitnami/charts#33844]
### Name and Version

bitnami/zookeeper:13.8.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We are running zookeeper in a particular vanilla way but clearly must be doing something wrong because this isn't a wide spread issue. We are currently digging down into it but thought i'd raise this to get some parallel thought on it.

The issue is we see a memory jump every time the readiness probe kicks in. If I omit the readiness probe the memory stays stable and then if i manually trigger it i emulate the spike. This continues until an OOM and then it restarts and the process starts again.

Values located below.
```
zookeeper:
  replicaCount: 1

  persistence:
    storageClass: ceph-retain
    size: 8Gi

  auth:
    client:
      enabled: true
      clientUser: zookeeper-client
      serverUsers: zookeeper-client
      existingSecret: zookeeper-client-auth
    quorum:
      enabled: true
      learnerUser: zookeeper-quorum
      serverUsers: zookeeper-quorum
      existingSecret: zookeeper-quorum-auth
  tls:
    client:
      enabled: true
      auth: none
      autoGenerated: false
      existingSecret: zookeeper-client-tls-certs
      existingSecretKeystoreKey: keystore.jks
      existingSecretTruststoreKey: truststore.jks
      passwordsSecretName: zookeeper-client-tls-certs-passwords
      passwordsSecretKeystoreKey: keystore.password
      passwordsSecretTruststoreKey: truststore.password
    quorum:
      enabled: true
      auth: need
      autoGenerated: false
      existingSecret: zookeeper-quorum-tls-certs
      existingSecretKeystoreKey: keystore.jks
      existingSecretTruststoreKey: truststore.jks
      passwordsSecretName: zookeeper-quorum-tls-certs-passwords
      passwordsSecretKeystoreKey: keystore.password
      passwordsSecretTruststoreKey: truststore.password
    
  livenessProbe:
    enabled: false

  startupProbe:
    enabled: true


  ###
  # The following variables are set to continue using existing functionality
  serviceAccount:
    create: false
    automountServiceAccountToken: true

  usePasswordFiles: false

  containerSecurityContext:
    readOnlyRootFilesystem: false
  
  autopurge:
    snapRetainCount: 1
    purgeInterval: 1
  ###

  service:
    type: ClusterIP # Only for AWS ALB to work (HS we can use clusterIP)
    tls:
      client_cert_pem_path: ''
      client_key_pem_path: ''

  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

  metrics:
    enabled: true
```

Appreciate any advice on this

### What do you see instead?

Manually triggering the readiness check:
```
$ /opt/bitnami/scripts/zookeeper/healthcheck.sh
zookeeper 17:55:22.51 INFO  ==> Zookeeper healthcheck succeeded
```
