### ISSUE TITLE
[bitnami/kafka] Kafka Access Issue from External Clients

### ISSUE THREAD

**Issue by sovu9991** [bitnami/charts#33861]
### Name and Version

bitnami/kafka 3.7.0-debian-12-r3

### What architecture are you using?

None

### What steps will reproduce the bug?

I have set up a Kafka cluster with the version 3.7.0-debian-12-r3 in AKS following this [doc](https://artifacthub.io/packages/helm/bitnami/kafka#accessing-kafka-brokers-from-outside-the-cluster), intending to use it both inside and outside the cluster. 
Inside the cluster, it works perfectly with port 9092 and 9095; however, we encounter issues when accessing Kafka from outside with port 9095.

Configuration:

```
listeners:
  advertisedListeners: CLIENT://:9092,INTERNAL://:9093,EXTERNAL://:9095
  client:
    containerPort: 9092
    name: CLIENT
    protocol: SASL_PLAINTEXT
    sslClientAuth: ''
  controller:
    containerPort: 9094
    name: CONTROLLER
    protocol: SASL_PLAINTEXT
    sslClientAuth: ''
  external:
    containerPort: 9095
    name: EXTERNAL
    protocol: SASL_PLAINTEXT
    sslClientAuth: ''
  extraListeners: []
  interbroker:
    containerPort: 9093
    name: INTERNAL
    protocol: SASL_PLAINTEXT
    sslClientAuth: ''
```
```
externalAccess:
  autoDiscovery:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      enabled: true
      readOnlyRootFilesystem: true
      runAsGroup: 1001
      runAsNonRoot: true
      runAsUser: 1001
      seLinuxOptions: {}
      seccompProfile:
        type: RuntimeDefault
    enabled: false
    image:
      digest: ''
      pullPolicy: IfNotPresent
      pullSecrets: []
      registry: docker.io
      repository: bitnami/kubectl
      tag: 1.30.0-debian-12-r0
    resources: {}
    resourcesPreset: small
  broker:
    service:
      allocateLoadBalancerNodePorts: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: '{{ .targetPod }}.dev.thisiscompanyname.net'
        service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
      domain: ''
      externalIPs: []
      extraPorts: []
      labels: {}
      loadBalancerAnnotations: []
      loadBalancerClass: ''
      loadBalancerIPs:
        - 10.161.155.53
        - 10.161.155.50
        - 10.161.155.49
      loadBalancerNames: []
      loadBalancerSourceRanges: []
      nodePorts: []
      ports:
        external: 9095
      publishNotReadyAddresses: false
      type: LoadBalancer
      useHostIPs: true
      usePodIPs: false
  controller:
    forceExpose: false
    service:
      allocateLoadBalancerNodePorts: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: '{{ .targetPod }}.dev.thisiscompanyname.net'
        service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
      domain: ''
      externalIPs: []
      extraPorts: []
      labels: {}
      loadBalancerAnnotations: []
      loadBalancerClass: ''
      loadBalancerIPs:
        - 10.161.155.53
        - 10.161.155.50
        - 10.161.155.49
      loadBalancerNames: []
      loadBalancerSourceRanges: []
      nodePorts: []
      ports:
        external: 9095
      publishNotReadyAddresses: false
      type: LoadBalancer
      useHostIPs: true
      usePodIPs: false
  enabled: true
```

### Are you using any custom parameters or values?

No, did not add any extra parameter other than the above configuration

### What is the expected behavior?

When I run inside AKS cluster:

```
~$ kcat -b kafka.dev.thisiscompanyname.net:9095 -X security.protocol=SASL_PLAINTEXT -X sasl.mechanism=PLAIN -X sasl.username=user -X sasl.password=thisisverystrongpassword -L
Metadata for all topics (from broker -1: sasl_plaintext://kafka.dev.thisiscompanyname.net:9095/bootstrap):
 3 brokers:
  broker 0 at kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9095 (controller)
  broker 1 at kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9095
  broker 2 at kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9095
 21 topics:
...
```

```
~$ kcat -b kafka.dev.thisiscompanyname.net:9095 -X security.protocol=SASL_PLAINTEXT -X sasl.mechanism=PLAIN -X sasl.username=user -X sasl.password=thisisverystrongpassword -t machines
% Auto-selecting Consumer mode (use -P or -C to override)
{"Ramp":104.28125762939453,"CycleStart":false,"timestamp":"2025-05-10T14:03:37.100383589+00:00"}
{"timestamp":"2025-05-10T14:03:37.199665995+00:00","Ramp":98.7397232055664,"CycleStart":false}
{"CycleStart":false,"timestamp":"2025-05-10T14:03:37.300381872+00:00","Ramp":96.80904388427734}
{"Ramp":104.97090911865234,"CycleStart":false,"timestamp":"2025-05-10T14:03:37.399983972+00:00"}
{"timestamp":"2025-05-10T14:03:37.499630472+00:00","Ramp":101.09296417236328,"CycleStart":false}
{"Ramp":96.16888427734375,"CycleStart":false,"timestamp":"2025-05-10T14:03:37.600380248+00:00"}
```

### What do you see instead?

When I run outside AKS cluster:

```
~$ kcat -b kafka.dev.thisiscompanyname.net:9095 -X security.protocol=SASL_PLAINTEXT -X sasl.mechanism=PLAIN -X sasl.username=user -X sasl.password=thisisverystrongpassword -L
Metadata for all topics (from broker -1: sasl_plaintext://kafka.dev.thisiscompanyname.net:9095/bootstrap):
 3 brokers:
  broker 0 at kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9095 (controller)
  broker 1 at kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9095
  broker 2 at kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9095
 21 topics:
...
```

```
~$ kcat -b kafka.dev.thisiscompanyname.net:9095 -X security.protocol=SASL_PLAINTEXT -X sasl.mechanism=PLAIN -X sasl.username=user -X sasl.password=thisisverystrongpassword -t machines
% Auto-selecting Consumer mode (use -P or -C to override)
%4|1747998594.291|FAIL|rdkafka#consumer-1| [thrd:sasl_plaintext://kafka-controller-0.kafka-controller-headless.k]: sasl_plaintext://kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9095/0: Connection setup timed out in state CONNECT (after 30351ms in state CONNECT)
% ERROR: Local: Broker transport failure: sasl_plaintext://kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9095/0: Connection setup timed out in state CONNECT (after 30351ms in state CONNECT)
%4|1747998594.396|FAIL|rdkafka#consumer-1| [thrd:sasl_plaintext://kafka-controller-2.kafka-controller-headless.k]: sasl_plaintext://kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9095/2: Connection setup timed out in state CONNECT (after 30455ms in state CONNECT)
%4|1747998594.398|FAIL|rdkafka#consumer-1| [thrd:sasl_plaintext://kafka-controller-1.kafka-controller-headless.k]: sasl_plaintext://kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9095/1: Connection setup timed out in state CONNECT (after 30458ms in state CONNECT)
```

### Additional information

This issue has been fixed by updated to higher version.
