### ISSUE TITLE
[bitnami/kafka] Undocumented breaking changes from 31.* to 32.*

### ISSUE THREAD

**Issue by igloo12** [bitnami/charts#33873]
### Name and Version

bitnami/kafka 32.*

### What architecture are you using?

None

### What steps will reproduce the bug?

extraConfig chart value has been removed with no mention

```yaml
extraConfig: |
  allow.everyone.if.no.acl.found=true
  authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer
  super.users=User:admin;User:controller_user;User:inter_broker_user
```

Also $CLIENT_CONF has been removed 

```yaml
provisioning:
  enabled: true
  extraProvisioningCommands:
    - "/opt/bitnami/kafka/bin/kafka-acls.sh --bootstrap-server $KAFKA_SERVICE --command-config $CLIENT_CONF --add --allow-principal User:XXX --consumer --topic fusion_ --group XXX --resource-pattern-type prefixed"
```

### What do you see instead?

$CLIENT_CONF has been replaced with `/shared/client.properties`? 

```yaml
provisioning:
  enabled: true
  extraProvisioningCommands:
    - "/opt/bitnami/kafka/bin/kafka-acls.sh --bootstrap-server $KAFKA_SERVICE --command-config /shared/client.properties --add --allow-principal User:XXX --consumer --topic fusion_ --group XXX --resource-pattern-type prefixed"
```

And replacing extraConfig with overrideConfiguration

```yaml
overrideConfiguration: 
  allow.everyone.if.no.acl.found: true
  authorizer.class.name: org.apache.kafka.metadata.authorizer.StandardAuthorizer
  super.users: "User:admin;User:controller_user;User:inter_broker_user"
```
