### ISSUE TITLE
[bitnami/kuberay] Wrong indentation in KubeRay cluster template

### ISSUE THREAD

**Issue by cmontemuino** [bitnami/charts#33887]
### Name and Version

bitnami/kuberay 1.4.10

### What architecture are you using?

None

### What steps will reproduce the bug?

1. `helm template` with non-default config to render `nodeAffinity` in RayCluster

### Are you using any custom parameters or values?

```yaml
cluster:
  head:
    nodeAffinityPreset:
      key: k8s_role
      type: soft
      values:
        - agent
    podAffinityPreset: soft
  worker:
    common:
      nodeAffinityPreset:
        key: k8s_role
        type: soft
        values:
          - agent
      podAffinityPreset: soft
```

### What do you see instead?

```yaml
# ...
  workerGroupSpecs:
    - groupName: default
      rayStartParams: {}
      replicas: 1
      # ...
        spec:
          # ...
          affinity:
            podAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        app.kubernetes.io/instance: my-kuberay
                        app.kubernetes.io/name: kuberay
                        app.kubernetes.io/component: cluster-worker-default
                    topologyKey: kubernetes.io/hostname
                  weight: 1
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        app.kubernetes.io/instance: my-kuberay
                        app.kubernetes.io/name: kuberay
                        app.kubernetes.io/component: cluster-worker-default
                    topologyKey: kubernetes.io/hostname
                  weight: 1
            nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                    - key: k8s_role
                      operator: In
                      values:
                        - "agent"
                weight: 1
# ...
```

### Additional information

Error is here:
https://github.com/bitnami/charts/blob/286eab651e84221976a3a60645a3e61e639f1474/bitnami/kuberay/templates/cluster/raycluster.yaml#L174C13-L174C185

It should be `nindent 14` instead.
