### ISSUE TITLE
[bitnami/flink] JobManager Fails to Start: "syntax error: operand expected" and "Insufficient Memory for the Java Runtime Environment"

### ISSUE THREAD

**Issue by always-web** [bitnami/charts#33932]
### Name and Version

bitnami/flink 2.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. k8s cluster
2. I installed it normally using the Helm command.

### Are you using any custom parameters or values?

```yaml
global:
  security:
    allowInsecureImages: true

diagnosticMode:
  enabled: false

image:
  registry: ***
  repository: library/bitnami/flink
  tag: 2.0.0-debian-12-r5

jobmanager:
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 4
      memory: 8Gi
taskmanager:
  replicaCount: 2
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 4
      memory: 8Gi
```

### What is the expected behavior?

I expect it to start up successfully.

### What do you see instead?

```
flink 09:56:13.86 INFO  ==>
flink 09:56:13.86 INFO  ==> Welcome to the Bitnami flink container
flink 09:56:13.86 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
flink 09:56:13.86 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
flink 09:56:13.86 INFO  ==>
flink 09:56:13.87 INFO  ==> ** Starting Apache Flink jobmanager setup **
flink 09:56:13.99 INFO  ==> ** FLINK jobmanager setup finished! **

flink 09:56:14.00 INFO  ==> ** Starting Apache Flink Job Manager
/opt/bitnami/flink/bin/config.sh: line 288: > 17 : syntax error: operand expected (error token is "> 17 ")
[ERROR] The execution result is empty.
[ERROR] Could not get JVM parameters and dynamic configurations properly.
[ERROR] Raw output from BashJavaUtils:
[0.002s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /tmp/hs_err_pid342.log
```
