### ISSUE TITLE
[bitnami/joomla] ingress yaml

### ISSUE THREAD

**Issue by ceejoyce** [bitnami/charts#3398]
**Which chart**: 
bitnami/joomla 8.04

**Describe the bug**
Unable to add additional hosts and tls entries to ingress section of values.yaml

**To Reproduce**
 ```
  hosts:
  - name: somedomain.org
    path: /
 
  tls:
  - hosts: 
      - somedomain.org        
    secretName: sd-k8s.tls
```

Results in the following...
`Error: YAML parse error on joomla/templates/ingress.yaml: error converting YAML to JSON: yaml: line 23: did not find expected key`
 
**Expected behavior**
Ingress records added.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"169db3bff4b5fb7722e967c5b6356713f05f15ed", GitTreeState:"clean", BuildDate:"2020-04-03T16:14:09Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Also noted that there's numerous references to "drupal" within the yaml.values and the docs so clearly some copy/pasting that needs tidying up.

**Comment by carrodher** [comment]
Thanks for reporting both issues, it seems an indentation issue, I just created the above PR fixing it.
With the changes in the PR I am able to set the above parameters on both ways, using `--set` or modifying the _values.yaml_, for example
```console
$  helm template . --set ingress.enabled=true --set ingress.hosts[0].name=newjoomla.local --set ingress.hosts[0].path=/new/path --set ingress.tls[0].hosts[0]=newjoomla.local --set ingress.tls[0].secretName=joomla.local-tls
```
produces
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: RELEASE-NAME-joomla
  labels:
    app.kubernetes.io/name: joomla
    helm.sh/chart: joomla-8.0.5
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  rules:
  - host: joomla.local
    http:
      paths:
        - path: /
          backend:
            serviceName: RELEASE-NAME-joomla
            servicePort: 80
  - host: newjoomla.local
    http:
      paths:
      - path: /new/path
        backend:
          serviceName: RELEASE-NAME-joomla
          servicePort: http
  tls:
    - hosts:
      - newjoomla.local
      secretName: joomla.local-tls
```
without errors parsing the template.
