### ISSUE TITLE
[bitnami/clickhouse] Missing CHOWN capability for volume-permissions init container

### ISSUE THREAD

**Issue by utay** [bitnami/charts#33990]
### Name and Version

bitnami/clickhouse 9.2.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Migrate bitnami/clickhouse from 8.0.9 to 9.2.5

### What is the expected behavior?

The `volume-permissions` init container should successfully run `chown` and terminate 

### What do you see instead?

I see `Operation not permitted` errors in the `volume-permissions` init container logs when it runs:
```
find /bitnami/clickhouse -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" |  xargs -r chown -R 1001:1001
```

### Additional information

I fixed it by adding:
```
defaultInitContainers:
  volumePermissions:
    enabled: true
    containerSecurityContext:
      capabilities:
        add:
          - CHOWN
```

That should be the default I think
