### ISSUE TITLE
[bitnami/kafka] Bitnami Kafka upgrade from chart 31.4.0 to 32.2.8 fails due to controller.quorum config mismatch

### ISSUE THREAD

**Issue by TatsianaGerasimovich** [bitnami/charts#34015]
### Name and Version

bitnami/kafka 32.2.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Have an existing Kafka deployment using Bitnami Helm chart `31.4.0` (Kafka version `3.9.0-debian-12-r10`). Our chart configuration:
```
kafka:
  kraft:
    clusterId:  
  image:
    tag: 3.9.0-debian-12-r10
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    external:
      protocol: PLAINTEXT
  controller:
    controllerOnly: true
    replicaCount: 1
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
  broker:
    replicaCount: 1
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
  #config: |-
  extraConfig: |-
    # Configuration for log flush interval based on the number of messages
    log.flush.interval.messages=10000
    # Configuration for log flush interval based on time (in milliseconds)
    log.flush.interval.ms=1000
    # Maximum retention size for the log (in bytes)
    log.retention.bytes=1073741824
    # Maximum size of a message (in bytes)
    message.max.bytes=1000012
    # Replication factor for the offsets topic
    offsets.topic.replication.factor=1
    # Minimum ISR (In-Sync Replicas) for the transaction state log
    transaction.state.log.min.isr=1
    # Replication factor for the transaction state log
    transaction.state.log.replication.factor=1
  metrics:
    kafka:
      enabled: false
    jmx:
      enabled: false
    serviceMonitor:
      enabled: false
      selector:
        project: "test"
```

2. Attempt to upgrade using Helm to chart `32.2.8` (Kafka version `4.0.0-debian-12-r5`) with data persistence enabled. Upgraded chart configuration:
```
kafka:
  tls:
    autoGenerated:
      enabled: false
  clusterId:  
  image:
    tag: 4.0.0-debian-12-r5
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    external:
      protocol: PLAINTEXT
  controller:
    controllerOnly: true
    replicaCount: 1
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
  broker:
    replicaCount: 1
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
  overrideConfiguration:
    kraft.version: 1
    log.flush.interval.messages: 10000
    log.flush.interval.ms: 1000
    log.retention.bytes: 1073741824
    message.max.bytes: 1000012
    offsets.topic.replication.factor: 1
    transaction.state.log.min.isr: 1
    transaction.state.log.replication.factor: 1
  metrics:
    kafka:
      enabled: false
    jmx:
      enabled: false
    serviceMonitor:
      enabled: false
      selector:
        project: "test"
```
3. Kafka fails to start, controller pod keeps to display repeating log:
`MetadataLoader id=0] InitializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet.`
4. Manually editing `server.properties` in the configmap to set `controller.quorum.voters` instead of the new `controller.quorum.bootstrap.servers` resolves the issue

![Image](https://github.com/user-attachments/assets/fce17c4e-efc1-400c-b64d-9f364a90ecf9)

### What is the expected behavior?

Kafka controller and broker should successfully start after upgrade.

### What do you see instead?

Kafka controller gets stuck in an infinite log loop, showing:
`MetadataLoader id=0] InitializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet.`
Eventually, the Kafka broker pod crashes.

### Additional information

We suspect the issue is due to incompatible changes in controller properties and `kraft.version` is set to 1 by default — notably replacing `controller.quorum.voters` with `controller.quorum.bootstrap.servers`.

Manually reverting this change allows the controller to start successfully.

Are the following Apache Kafka issues relevant to this bug and might solve the problem in a future release?

- https://issues.apache.org/jira/browse/KAFKA-18979
- https://issues.apache.org/jira/browse/KAFKA-16538

Any advice on how to properly migrate from chart 31.4.0 to 32.2.8 while preserving existing data and quorum would be greatly appreciated.
