### ISSUE TITLE
'Update Password Job' Fails because of incorrect value path

### ISSUE THREAD

**Issue by jroddev** [bitnami/charts#34028]
### Name and Version

bitnami/mysql 13.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Update Password job is failing with basic config
```yaml
auth:
  existingSecret: "${root_credentials}"
passwordUpdateJob:
  enabled: true
  previousPasswords:
    existingSecret: "${previous_root_credentials}"
```

1. Deploy MySQL chart
2. Add the `PasswordUpdateJob` to values and deploy again
3. Observe job failure

### What is the expected behavior?

UpdatePasswordJob runs successfully

### What do you see instead?

Looks like [this line](https://github.com/bitnami/charts/blob/eb57020cda6719e2f8e6a29714e5fe7e34f5ad32/bitnami/mysql/templates/update-password/job.yaml#L59) is using the wrong variable
`{{- if .Values.usePasswordFiles }}` should be `{{- if .Values.auth.usePasswordFiles }}`

`.Values.auth.usePasswordFiles` is true by default and `.Values.usePasswordFiles` doesn't exist in  (therefore false?)
What this means is that the previous and next passwords are mounted as files but then never sourced into the rotate script and the job fails. It does not log what the error is
```
mysql 03:35:22.57 INFO  ==> Starting password update job                                                                                                                                                          
mysql 03:35:22.61 INFO  ==> Updating root password                                                                                                                                                                
stream closed EOF for core/mysql-password-update-jng56 (update-credentials)
```

It also seems to crash by running mysql instance somehow but I haven't dug into that. The workaround is to make use that `usePasswordFiles` is also set to true at the values root.
```yaml
usePasswordFiles: true
auth:
  existingSecret: "${root_credentials}"
  usePasswordFiles: true

passwordUpdateJob:
  enabled: true
  previousPasswords:
    existingSecret: "${previous_root_credentials}"
```

The Postgres update-job does use the correct `.Values.auth.usePasswordFiles` at [that line](
https://github.com/bitnami/charts/blob/eb57020cda6719e2f8e6a29714e5fe7e34f5ad32/bitnami/postgresql/templates/update-password/job.yaml#L61)
