### ISSUE TITLE
[bitnami/external-dns] istio-virtualservice does not create entries in Infoblox

### ISSUE THREAD

**Issue by razvan-ig** [bitnami/charts#3403]
**Which chart**:
external-dns-3.3.0

**Describe the bug**
Started with a very basic setup of httpbin, as per https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/istio.md#using-a-virtualservice-as-a-source, added a VirtualService, tailing the logs in debug mode, on kubectl apply I see

`external-dns-6f7d8c6cc9-dgphl external-dns time="2020-08-12T17:50:11Z" level=debug msg="service added"`

and a few secs later (polling 1min)

`external-dns-6f7d8c6cc9-dgphl external-dns time="2020-08-12T17:50:57Z" level=debug msg="No endpoints could be generated from VirtualService test/httpbin"`

Other types of resources work, namely Service of type LoadBalancer creates A records fine

```
    spec:
      containers:
      - args:
        - --log-level=debug
        - --log-format=text
        - --domain-filter=k8s.test.local
        - --policy=sync
        - --provider=infoblox
        - --namespace=test
        - --registry=txt
        - --interval=1m
        - --source=service
        - --source=istio-virtualservice
        - --infoblox-grid-host=grid.local
        - --infoblox-wapi-version=2.3.1
        - --infoblox-view=internal
```

Any hints for further debugging are most welcome
