### ISSUE TITLE
Kube-Prometheus support for agent-mode

### ISSUE THREAD

**Issue by Leaced** [bitnami/charts#34094]
### Name and Version

bitnami/kube-prometheus

### What is the problem this feature will solve?

When collecting metrics from multiple prometheus instances with `remote_write` every prometheus will manage its own TSDB. So we need resources to store duplicate data and the increased complexity also increases the possibility of errors like out-of-order samples.

### What is the feature you are proposing to solve the problem?

Using Prometheus in agent mode with the `--agent` flag could solve this problem. This flag currently does not work because it is incompatible with the tsdb-correlated flags from the Helm chart.

A `prometheus.agentmode.enabled` flag could be a solution.

### What alternatives have you considered?

At the moment, we have `prometheus.enabled: false` as a value and create the service-account and the Prometheus by ourselves.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by Leaced** [comment]
For the last 2 weeks I used a prometheus agent managed by the prometheus operator of the helm chart and it works fine.

It mostly works to just change the kind from "Prometheus" to "PrometheusAgent". We just need to omit a few values from the yaml like "spec.alerting", because they do not exist for prometheus Angents.

So i see a few options:

1) The prometheus.agentmode.enabled value for the helm chart
If set, it could change the kind from prometheus to prometheusAgent and would omit values not existing in PrometheusAgent from the generated yaml.
I am not sure, if this can be a clean solution.

2) A separate part in the helmchart values for an PrometheusAgent
This could be a very clean solution, but a lot of work would be doubled. It would introduce the risk of a drift in functionality.

3) An Option to disable prometheus while still creating the serviceMonitors and ClusterRoles.
This is not the asked feature, but would also be very helpfull. So it would be possible to disable prometheus and use an agent with the roles and serviceMonitors still managed by the helm chart

I'm very unexperienced with writing helm charts and I'm not sure which solution is wanted. For me solution 3 seems like a solution until we have a better one. What do you think?

**Comment by Leaced** [comment]
Here is a very basic Prometheus agent which is working with the ServiceAccounts and ServiceMonitors managed by the Helm chart:
```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusAgent
metadata:
  name: prometheus-agent
  namespace: monitoring
spec:
  replicas: 1
  serviceAccountName: kube-prometheus-prometheus
  image: ...
  securityContext:
    fsGroup: 1001
    fsGroupChangePolicy: Always
    supplementalGroups: []
    sysctls: []
  selector: app.kubernetes.io/instance=kube-prometheus-prometheus,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,operator.prometheus.io/name=kube-prometheus-prometheus,prometheus=kube-prometheus-prometheus
  externalLabels:
    cluster: test-1
  remoteWrite:
    - url: https://test.cluster
  serviceMonitorNamespaceSelector: {"monitoring"}
  scrapeConfigNamespaceSelector: {"monitoring"}
  serviceMonitorSelector: {}
  logLevel: info
```

All the other stuff is once generated with the helm chart, then exported. Then the helm chart disabled Prometheus. The Serviceaccount etc., was imported and is now used by this agent
