### ISSUE TITLE
Combined Deployment template for standalone/distributed breaks existing standalone deployment updates

### ISSUE THREAD

**Issue by kevinastone** [bitnami/charts#34103]
### Name and Version

bitnami/minio v17.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Have a previous `standalone` deployment from pre-17.0 (such as `16.0.11`) and then try to helm upgrade to `17.0.2`.

### Are you using any custom parameters or values?

`--set mode=standalone`

### What is the expected behavior?

Previously, the Deployment `spec.selector` for pre-17.0 was:
```
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: minio
      app.kubernetes.io/name: minio
```

Here's the previous `deployment.yaml` template for these `spec.selector`: https://github.com/bitnami/charts/blob/minio/16.0.11/bitnami/minio/templates/standalone/deployment.yaml#L16-L19

### What do you see instead?

Now with the merged `application.yaml` [template](https://github.com/bitnami/charts/blob/minio/17.0.2/bitnami/minio/templates/application.yaml#L26-L31) from v17 that combines standalone and distributed into a single template, it tries to generate the following Deployment spec fragment:

```
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: minio
      app.kubernetes.io/name: minio
      app.kubernetes.io/component: minio
      app.kubernetes.io/part-of: minio
```

This updated Deployment is rejected since `spec.selector` is immutable for deployed Deployments:

```
Helm upgrade failed for release minio/minio with chart minio@17.0.2+67479a878d98
: cannot patch "minio" with kind Deployment: Deployment.apps "minio" is invalid: spec.selector: Invalid val
ue: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"minio", "app.kubernetes.i
o/instance":"minio", "app.kubernetes.io/name":"minio", "app.kubernetes.io/part-of":"minio"}, MatchExpressio
ns:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
