### ISSUE TITLE
[bitnami/postgresql] postgres replicastion insert block

### ISSUE THREAD

**Issue by einsli** [bitnami/charts#34104]
### Name and Version

bitnami/postgres 16.7.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I deployed PostgreSQL version 16.7.4 using the Bitnami Helm chart with the architecture set to replication mode.

After deployment, I noticed that INSERT operations get blocked, while SELECT queries work fine.

The error message from the logs is:

2025-06-04 13:19:12.401 GMT [11290] ERROR:  canceling statement due to user request
2025-06-04 13:19:12.401 GMT [11290] CONTEXT:  while inserting index tuple (0,12) in relation "kv"
2025-06-04 13:19:12.401 GMT [11290] STATEMENT:  
-- name: BatchSet :exec
INSERT INTO kv (jid, key, value)
SELECT $1,
       unnest($2::text[]),
       unnest($3::text[])
ON CONFLICT (jid, key)
DO UPDATE
SET value = EXCLUDED.value;

### What do you see instead?

2025-06-04 13:19:12.401 GMT [11290] ERROR:  canceling statement due to user request
2025-06-04 13:19:12.401 GMT [11290] CONTEXT:  while inserting index tuple (0,12) in relation "kv"
2025-06-04 13:19:12.401 GMT [11290] STATEMENT:  
-- name: BatchSet :exec
INSERT INTO kv (jid, key, value)
SELECT $1,
       unnest($2::text[]),
       unnest($3::text[])
ON CONFLICT (jid, key)
DO UPDATE
SET value = EXCLUDED.value;

**Comment by javsalgar** [comment]
Hi!

Could you share a sample SQL that triggers the issue? We would like to reproduce it on our side.

**Comment by einsli** [comment]
Here is the sql for
### create table 
```sql
create table kv
(
    jid bigint not null,
    key   text   not null,
    value text   not null,
    primary key (jid, key)
);
```
### insert sql
```sql
INSERT INTO kv (jid, key, value)
VALUES (1001, 'username', 'alice');
```

### here is my overwrite values
```yaml
postgresql:

  architecture: replication

  replication:
    ## @param replication.synchronousCommit Set synchronous commit mode. Allowed values: `on`, `remote_apply`, `remote_write`, `local` and `off`
    ## @param replication.numSynchronousReplicas Number of replicas that will have synchronous replication. Note: Cannot be greater than `readReplicas.replicaCount`.
    ## ref: https://www.postgresql.org/docs/current/runtime-config-wal.html#GUC-SYNCHRONOUS-COMMIT
    ##
    synchronousCommit: "on"
    numSynchronousReplicas: 2
    ## @param replication.applicationName Cluster application name. Useful for advanced replication settings
    ##
    applicationName: pg_application
  ## @param containerPorts.postgresql PostgreSQL container port
  primary:
    persistence:
      size: 200Gi
    resources:
      requests:
        cpu: 2
        memory: 2Gi
      limits:
        cpu: 4
        memory: 4Gi
    extendedConfiguration: "max_connections = 1000"
  readReplicas:
    persistence:
      size: 200Gi
    resources:
      requests:
        cpu: 2
        memory: 2Gi
      limits:
        cpu: 4
        memory: 4Gi
    extendedConfiguration: "max_connections = 1000"
  backup:
    ## @param backup.enabled Enable the logical dump of the database "regularly"
    enabled: true
    cronjob:
      ## @param backup.cronjob.schedule Set the cronjob parameter schedule
      schedule: "@daily"
      ## @param backup.cronjob.timeZone Set the cronjob parameter timeZone
      timeZone: ""
      ## @param backup.cronjob.concurrencyPolicy Set the cronjob parameter concurrencyPolicy
      concurrencyPolicy: Allow
    storage:
      size: 200G
```

**Comment by fmulero** [comment]
Hi @einsli, I think you have the solution of your issue in the values you shared:
```yaml
postgresql:

  architecture: replication

  replication:
    ## @param replication.synchronousCommit Set synchronous commit mode. Allowed values: `on`, `remote_apply`, `remote_write`, `local` and `off`
    ## @param replication.numSynchronousReplicas Number of replicas that will have synchronous replication. Note: Cannot be greater than `readReplicas.replicaCount`.
    ## ref: https://www.postgresql.org/docs/current/runtime-config-wal.html#GUC-SYNCHRONOUS-COMMIT
    ##
    synchronousCommit: "on"
    numSynchronousReplicas: 2
```

`readReplicas.replicaCount` is 1 by default and you are setting `numSynchronousReplicas: 2`. With this configuration you need at least 2 readReplicas synced to complete the commit. Please increase `readReplicas.replicaCount` value.
