### ISSUE TITLE
[bitnami/grafana] Extra secret mounts

### ISSUE THREAD

**Issue by semyon2105** [bitnami/charts#3421]
**Which chart**: grafana 3.4.0

**Is your feature request related to a problem? Please describe.**
My grafana.ini config file looks like this:
```
[database]
    type = postgres
    ...
    user = $__file{/secrets/pg_user}
    password = $__file{/secrets/pg_password}

[dashboards]
    min_refresh_interval = 1m
...
```
I would like to be able to load parts of my `grafana.ini` config from mounted k8s secrets using Grafana's [file provider](https://grafana.com/docs/grafana/latest/administration/configuration/#file-provider), while having the rest of my config in a configmap. This is more convenient to maintain than having the whole `grafana.ini` in a secret.

**Describe the solution you'd like**
A `values.yaml` section like `extraConfigmaps` but for secrets.

**Describe alternatives you've considered**
- Whole `grafana.ini` in a secret
  We store Helm values in the project repository. I would like to have as much configuration as possible stored there, so it's desirable to keep the non-secret `grafana.ini` configuration options in the repo. `grafana.ini` secret won't work out in this case, because you'd have to keep the whole thing with the passwords there or use some kind of git crypto solution which I would like to avoid.

**Comment by semyon2105** [comment]
I found out I could use a combination of `extraVolumes` and `extraVolumeMounts` sections to mount a secret. It ended up looking like this:

```
extraVolumes:
  - name: secrets
    secret:
      secretName: secret
      defaultMode: 0400
      items:
        - key: pg-user
          path: pg-user
        - key: pg-password
          path: pg-password

extraVolumeMounts:
  - name: secret
    mountPath: /secrets
    readOnly: true
```

A section like `extraSecrets` isn't really needed anymore because the solution above is more generic.
