### ISSUE TITLE
[Bitnami/kafka] Encountering java.lang.IllegalAccessError while deploying a Kafka source connector for MongoDB Kafka Connect plugin

### ISSUE THREAD

**Issue by bmaurya88** [bitnami/charts#34260]
### Name and Version

Bitnami/Kafka 31.5.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

-  I have deployed Kafka(3.9.0) and Zookeeper using the Bitnami Kafka chart(31.5.0) with replicas for each.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bitnami-kafka-helm-values
  namespace: bitnami-qa-kafka
data:
  values.yaml: |
    
    broker:
      replicaCount: 3
      extraConfig: |-
        offsets.topic.replication.factor=3
        inter.broker.protocol.version=3.5
        delete.topic.enable=false
        log.retention.hours=168
        log.retention.bytes=1073741824
        default.replication.factor=3
        replica.fetch.max.bytes=1048576
        message.max.bytes=1048576
        max.request.size=1048576
      livenessProbe:
        enabled: true
        initialDelaySeconds: 30
        timeoutSeconds: 5
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
      readinessProbe:
        enabled: true
        initialDelaySeconds: 30
        failureThreshold: 6
        timeoutSeconds: 5
        periodSeconds: 10
        successThreshold: 1
      persistence:
        enabled: true
        storageClass: "aiops-bitnami-kafka-data"
        selector:
          matchLabels:
            type: data
        size: 20Gi
        mountPath: /bitnami/kafka
      logPersistence:
        enabled: true
        storageClass: "aiops-bitnami-kafka-data"
        selector:
          matchLabels:
            type: logs
        size: 5Gi
        mountPath: /opt/bitnami/kafka/logs
    kraft:
      enabled: false
    zookeeper:
      enabled: true
      replicaCount: 3
      persistence:
        enabled: true
        storageClass: "aiops-bitnami-zookeeper-data"
        accessModes:
          - ReadWriteOnce
        size: 5Gi
      readinessProbe:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 10
        failureThreshold: 10
        successThreshold: 1
      livenessProbe:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 10
        failureThreshold: 10
        successThreshold: 1
      containerPorts:
        quorum: 3888
        leaderElection: 3889
      extraEnvVars:
        - name: ZOO_LISTEN_ALLIPS_ENABLED
          value: "yes"
    listeners:
      client:
        containerPort: 9092
        protocol: PLAINTEXT
        name: CLIENT
        sslClientAuth: ""
      controller:
        name: CONTROLLER
        containerPort: 9093
        protocol: PLAINTEXT
        sslClientAuth: ""
      interbroker:
        containerPort: 9094
        protocol: PLAINTEXT
        name: INTERNAL
      external:
        containerPort: 9095
        protocol: PLAINTEXT
        name: EXTERNAL
```
- Now I have deployed the Kafka Connect using the below values.yaml

```yaml
extraDeploy:
      - |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: {{ include "common.names.fullname" . }}-connect
          labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
            app.kubernetes.io/component: connector
        spec:
          replicas: 1
          selector:
            matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 6 }}
              app.kubernetes.io/component: connector
          template:
            metadata:
              labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 8 }}
                app.kubernetes.io/component: connector
            spec:
              imagePullSecrets:
                - name: docker-secret
              containers:
                - name: connect
                  image: docker.my-private-repo.com/dev/bitnami-kafka-connect:3.9.0_1
                  imagePullPolicy: IfNotPresent
                  ports:
                    - name: connector
                      containerPort: 8083
                  volumeMounts:
                    - name: configuration
                      mountPath: /bitnami/kafka/config
              volumes:
                - name: configuration
                  configMap:
                    name: {{ include "common.names.fullname" . }}-connect
      - |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: {{ include "common.names.fullname" . }}-connect
          labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
            app.kubernetes.io/component: connector
        data:
          connect-distributed.properties: |-
            bootstrap.servers = bitnami-kafka-broker-headless:9092
            group.id: bitnami-kafka-connect
            key.converter: org.apache.kafka.connect.storage.StringConverter
            value.converter: org.apache.kafka.connect.storage.StringConverter
            key.converter.schemas.enable: false
            value.converter.schemas.enable: false
            offset.storage.topic: connect-offsets
            config.storage.topic: connect-configs
            status.storage.topic: connect-status
            ...
          mongodb.properties: |-
            connection.uri=mongodb://mongodb-test:******@bitnami-mongodb-headless:27017
            ...
      - |
        apiVersion: v1
        kind: Service
        metadata:
          name: {{ include "common.names.fullname" . }}-connect
          labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
            app.kubernetes.io/component: connector
        spec:
          ports:
            - protocol: TCP
              port: 8083
              targetPort: connector
          selector: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
            app.kubernetes.io/component: connector
    controller:
      replicaCount: 0
```
Now, I was trying to deploy to create the Kafka source connector using the below JSON and port-forwarding the Kafka Connect pod to a local machine.
```
 curl -X POST http://localhost:8083/connectors   -H "Content-Type: application/json"   -d '{
    "name": "kafka-source-connector",
    "config": {
      "connector.class": "com.mongodb.kafka.connect.MongoSourceConnector",
      "connection.uri": "mongodb://mongodb-test:********@bitnami-mongodb-headless.bitnami-qa-mongodb.svc.cluster.local:27017/?authSource=admin",
      "publish.full.document.only": "true",
      "tasks.max": "1",
      "output.format.value": "json",
      "publish.full.document.only.tombstone.on.delete": "false",
      "output.format.key": "json",
      "database": "mongotest",
      "collection": "testing",
      "topic.pre^Cx": "mongo",
      "key.converter.schemas.enable": "false",
      "value.converter.schemas.enable": "false",
      "value.converter": "org.apache.kafka.connect.storage.StringConverter",
      "key.converter": "org.apache.kafka.connect.storage.StringConverter"
    }
  }'
```
- Once I send request to create the above connector, I get the success message from kafka connect.
- Now, if I check the Kafka Connect pod logs, then I get the following error - 

```
[2025-06-09 06:45:22,406] ERROR [kafka-source-connector|task-0] WorkerSourceTask{id=kafka-source-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:234)
java.lang.IllegalAccessError: failed to access class org.apache.kafka.common.utils.SystemTime from class com.mongodb.kafka.connect.source.StartedMongoSourceTask (org.apache.kafka.common.utils.SystemTime is in unnamed module of loader 'app'; com.mongodb.kafka.connect.source.StartedMongoSourceTask is in unnamed module of loader org.apache.kafka.connect.runtime.isolation.PluginClassLoader @4ae3c1cd)
        at com.mongodb.kafka.connect.source.StartedMongoSourceTask.<init>(StartedMongoSourceTask.java:158)
        at com.mongodb.kafka.connect.source.MongoSourceTask.start(MongoSourceTask.java:152)
        at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.initializeAndStart(AbstractWorkerSourceTask.java:279)
        at org.apache.kafka.connect.runtime.WorkerTask.doStart(WorkerTask.java:176)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:281)
        at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:79)
        at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:238)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
[2025-06-09 06:45:22,409] INFO [kafka-source-connector|task-0] Stopping MongoDB source task (com.mongodb.kafka.connect.source.MongoSourceTask:185)
[2025-06-09 06:45:22,410] INFO [kafka-source-connector|task-0] [Producer clientId=connector-producer-kafka-source-connector-0] Closing the Kafka producer with timeoutMillis = 30000 ms. (org.apache.kafka.clients.producer.KafkaProducer:1382)
[2025-06-09 06:45:22,420] INFO [kafka-source-connector|task-0] Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:685)
[2025-06-09 06:45:22,420] INFO [kafka-source-connector|task-0] Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:689)
```

- I tried to add below options to skip above restrictions by adding KAFKA_OPTS param from pod's env, dockerfile, custom entrypoint.sh but did not worked. 
- Here is my customized dockerfile which has created the kafka connect image - 

```dockerfile
FROM bitnami/kafka:@kafka.version@

# Download the MongoDB Kafka Connector
RUN mkdir -p /opt/bitnami/kafka/libs && \
    curl -L https://search.maven.org/remotecontent?filepath=org/mongodb/kafka/mongo-kafka-connect/1.11.0/mongo-kafka-connect-1.11.0-all.jar \
    -o /opt/bitnami/kafka/libs/mongo-kafka-connect.jar

# Create a custom directory for scripts
USER root
RUN mkdir -p /custom-scripts
COPY connect-distributed-wrapper.sh /custom-scripts/
RUN chmod +x /custom-scripts/connect-distributed-wrapper.sh

# Switch back to non-root user (Bitnami default)
USER 1001

CMD ["/custom-scripts/connect-distributed-wrapper.sh"]
```

Addtional  things I tried which did not worked - 
> Added mong kafka connect jar on separate plugin path.
> Added pluging.path with customized path and without it
-> Upgraded the mongo kafka connect jar to 1.13.1 but.

None of the above is worked for me. 

Does anyone have any idea what I am doing wrong? Or any pointers/help to fixed the issue. 

Thanks in advance.

### Are you using any custom parameters or values?
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bitnami-kafka-helm-values
  namespace: bitnami-qa-kafka
data:
  values.yaml: |
    
    broker:
      replicaCount: 3
      extraConfig: |-
        offsets.topic.replication.factor=3
        inter.broker.protocol.version=3.5
        delete.topic.enable=false
        log.retention.hours=168
        log.retention.bytes=1073741824
        default.replication.factor=3
        replica.fetch.max.bytes=1048576
        message.max.bytes=1048576
        max.request.size=1048576
      livenessProbe:
        enabled: true
        initialDelaySeconds: 30
        timeoutSeconds: 5
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
      readinessProbe:
        enabled: true
        initialDelaySeconds: 30
        failureThreshold: 6
        timeoutSeconds: 5
        periodSeconds: 10
        successThreshold: 1
      persistence:
        enabled: true
        storageClass: "aiops-bitnami-kafka-data"
        selector:
          matchLabels:
            type: data
        size: 20Gi
        mountPath: /bitnami/kafka
      logPersistence:
        enabled: true
        storageClass: "aiops-bitnami-kafka-data"
        selector:
          matchLabels:
            type: logs
        size: 5Gi
        mountPath: /opt/bitnami/kafka/logs
    kraft:
      enabled: false
    zookeeper:
      enabled: true
      replicaCount: 3
      persistence:
        enabled: true
        storageClass: "aiops-bitnami-zookeeper-data"
        accessModes:
          - ReadWriteOnce
        size: 5Gi
      readinessProbe:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 10
        failureThreshold: 10
        successThreshold: 1
      livenessProbe:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 10
        failureThreshold: 10
        successThreshold: 1
      containerPorts:
        quorum: 3888
        leaderElection: 3889
      extraEnvVars:
        - name: ZOO_LISTEN_ALLIPS_ENABLED
          value: "yes"
    listeners:
      client:
        containerPort: 9092
        protocol: PLAINTEXT
        name: CLIENT
        sslClientAuth: ""
      controller:
        name: CONTROLLER
        containerPort: 9093
        protocol: PLAINTEXT
        sslClientAuth: ""
      interbroker:
        containerPort: 9094
        protocol: PLAINTEXT
        name: INTERNAL
      external:
        containerPort: 9095
        protocol: PLAINTEXT
        name: EXTERNAL
extraDeploy:
      - |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: {{ include "common.names.fullname" . }}-connect
          labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
            app.kubernetes.io/component: connector
        spec:
          replicas: 1
          selector:
            matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 6 }}
              app.kubernetes.io/component: connector
          template:
            metadata:
              labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 8 }}
                app.kubernetes.io/component: connector
            spec:
              imagePullSecrets:
                - name: docker-secret
              containers:
                - name: connect
                  image: docker.my-private-repo.com/dev/bitnami-kafka-connect:3.9.0_1
                  imagePullPolicy: IfNotPresent
                  ports:
                    - name: connector
                      containerPort: 8083
                  volumeMounts:
                    - name: configuration
                      mountPath: /bitnami/kafka/config
              volumes:
                - name: configuration
                  configMap:
                    name: {{ include "common.names.fullname" . }}-connect
      - |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: {{ include "common.names.fullname" . }}-connect
          labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
            app.kubernetes.io/component: connector
        data:
          connect-distributed.properties: |-
            bootstrap.servers = bitnami-kafka-broker-headless:9092
            group.id: bitnami-kafka-connect
            key.converter: org.apache.kafka.connect.storage.StringConverter
            value.converter: org.apache.kafka.connect.storage.StringConverter
            key.converter.schemas.enable: false
            value.converter.schemas.enable: false
            offset.storage.topic: connect-offsets
            config.storage.topic: connect-configs
            status.storage.topic: connect-status
            ...
          mongodb.properties: |-
            connection.uri=mongodb://mongodb-test:******@bitnami-mongodb-headless:27017
            ...
      - |
        apiVersion: v1
        kind: Service
        metadata:
          name: {{ include "common.names.fullname" . }}-connect
          labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
            app.kubernetes.io/component: connector
        spec:
          ports:
            - protocol: TCP
              port: 8083
              targetPort: connector
          selector: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
            app.kubernetes.io/component: connector
    controller:
      replicaCount: 0
```
### What is the expected behavior?

I wanted to successfully deploy Kafka source connector where I want to publish the message on a kafka topic if there is any collection is configured while deploying the connector.

### What do you see instead?
```
**curl http://localhost:8083/connectors**
["kafka-source-connector"]
```
```
curl http://localhost:8083/connectors/kafka-source-connector/status

{"name":"kafka-source-connector","connector":{"state":"RUNNING","worker_id":"10.129.115.236:8083"},"tasks":[{"id":0,"state":"FAILED","worker_id":"10.129.115.236:8083","trace":"java.lang.IllegalAccessError: failed to access class org.apache.kafka.common.utils.SystemTime from class com.mongodb.kafka.connect.source.StartedMongoSourceTask (org.apache.kafka.common.utils.SystemTime is in unnamed module of loader 'app'; com.mongodb.kafka.connect.source.StartedMongoSourceTask is in unnamed module of loader org.apache.kafka.connect.runtime.isolation.PluginClassLoader @4ae3c1cd)\n\tat com.mongodb.kafka.connect.source.StartedMongoSourceTask.<init>(StartedMongoSourceTask.java:158)\n\tat com.mongodb.kafka.connect.source.MongoSourceTask.start(MongoSourceTask.java:152)\n\tat org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.initializeAndStart(AbstractWorkerSourceTask.java:279)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doStart(WorkerTask.java:176)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:281)\n\tat org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:79)\n\tat org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:238)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)\n\tat java.base/java.util.concurrent.FutureTask.run(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n"}],"type":"source"}
```
