### ISSUE TITLE
Add hostAlias under Redmine

### ISSUE THREAD

**Issue by lionelyoung** [bitnami/charts#3427]
**Which chart**:
redmine

**Is your feature request related to a problem? Please describe.**
feature request

**Describe the solution you'd like**
I'd like a value option to add hostAlias under spec, so I can access minikube externaldb, like so:
```
      hostAliases:
      - ip: "192.168.64.1"
        hostnames:
        - "host.minikube.internal"
```

**Describe alternatives you've considered**
I've deployed the chart and then kubectl edit deployment, and add it manually
