### ISSUE TITLE
[bitnami/mongodb] initdbScriptsConfigMap not used

### ISSUE THREAD

**Issue by Marck** [bitnami/charts#34278]
### Name and Version

bitnami/mongodb 16.5.16

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have created a Helm chart that uses MongoDB as a dependency and everything seems to be running fine, but the `initdbScriptsConfigMap` parameter is not. 

### Are you using any custom parameters or values?

My chart.yaml
```yaml
apiVersion: v2
name: chart-name
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "9.1.120"
dependencies:
  - name: mongodb
    version: 16.5.16
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
```

My values for mongodb:
```yaml
mongodb:
  enabled: true
  fullnameOverride: mongodb
  image:
    registry: docker.io
    repository: bitnami/mongodb
    tag: 8.0.10
    pullPolicy: IfNotPresent
  auth:
    enabled: true
    existingSecret: mongodb-credentials
    usernames: ['user'] # must be array
    passwordKey: mongodb-passwords # must be an array
    databases: ['database'] # must be array
  extraEnvVars:
    - name: MONGO_INITDB_ROOT_USERNAME
      valueFrom:
        secretKeyRef:
          name: mongodb-credentials
          key: mongodb-root-username
    - name: MONGO_INITDB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mongodb-credentials
          key: mongodb-root-password
    - name: MONGO_USER
      value: user
    - name: MONGO_PASS
      valueFrom:
        secretKeyRef:
          name: mongodb-credentials
          key: mongodb-password
    - name: MONGO_DBNAME
      value: database
    - name: MONGO_AUTHSOURCE
      value: admin
  initdbScripts: {}
  initdbScriptsConfigMap: "mongodb-user-init"
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/worker: 'true'
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    supplementalGroups: []
    fsGroup: 100
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1024
    runAsGroup: 100
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
  resourcesPreset: "small"
  ports:
    mongodb: 27017
  pdb:
    enabled: false
  
  volumes:
    pvc:
      enabled: true
      name: mongodb-data
      size: 2Gi
      accessModes:
        - ReadWriteOnce
    pv:
      enabled: true
      name: mongodb-data
      storageClassName: mongodb-data
      size: 2Gi
      accessModes:
        - ReadWriteOnce
      nfs:
        server: X
        path: "/volume1/mongodb-data"
  
  # Using a custom PVC template
  persistence:
    enabled: true
    name: mongodb-data
    existingClaim: "mongodb-data"
    size: 2Gi
```

My configmap with the initial user creation:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-user-init
data:
  init-mongo.sh: |
    #!/bin/bash

    if which mongosh > /dev/null 2>&1; then
      mongo_init_bin='mongosh'
    else
      mongo_init_bin='mongo'
    fi
    "${mongo_init_bin}" <<EOF
    use ${MONGO_AUTHSOURCE}
    db.auth("${MONGO_INITDB_ROOT_USERNAME}", "${MONGO_INITDB_ROOT_PASSWORD}")
    db.createUser({
      user: "${MONGO_USER}",
      pwd: "${MONGO_PASS}",
      roles: [
        { db: "${MONGO_DBNAME}", role: "dbOwner" },
        { db: "${MONGO_DBNAME}_stat", role: "dbOwner" },
        { db: "${MONGO_DBNAME}_audit", role: "dbOwner" }
      ]
    })
    EOF
```

### What is the expected behavior?

To get the user created

### What do you see instead?

My MongoDB logs (I deleted all PVs and PVCs and the data off the NFS server):
```
mongodb 07:14.19 [INFO [0m ==>
mongodb 07:14.19 [INFO [0m ==> [1mWelcome to the Bitnami mongodb container[0m
mongodb 07:14.19 [INFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
mongodb 07:14.19 [INFO [0m ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
mongodb 07:14.19 [INFO [0m ==>
mongodb 07:14.20 [INFO [0m ==> ** Starting MongoDB setup **
mongodb 07:14.21 [INFO [0m ==> Validating settings in MONGODB_* env vars...
mongodb 07:14.24 [INFO [0m ==> Initializing MongoDB...
mongodb 07:14.31 [INFO [0m ==> Deploying MongoDB from scratch...
MongoNetworkError: connect ECONNREFUSED 10.42.1.16:27017
mongodb 07:16.92 [INFO [0m ==> Creating users...
mongodb 07:16.92 [INFO [0m ==> Creating root user...
Current Mongosh Log ID:	68473ef54c95b2ec3169e327
Connecting to:		mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&tlsAllowInvalidHostnames=true&appName=mongosh+2.5.2
Using MongoDB:		8.0.10
Using Mongosh:		2.5.2

For mongosh info see: https://www.mongodb.com/docs/mongodb-shell/


To help improve our products, anonymous usage data is collected and sent to MongoDB periodically (https://www.mongodb.com/legal/privacy-policy).
You can opt-out by running the disableTelemetry() command.

------
   The server generated these startup warnings when booting
   2025-06-09T20:07:15.988+00:00: For customers running the current memory allocator, we suggest changing the contents of the following sysfsFile
   2025-06-09T20:07:15.988+00:00: We suggest setting the contents of sysfsFile to 0.
   2025-06-09T20:07:15.988+00:00: Your system has glibc support for rseq built in, which is not yet supported by tcmalloc-google and has critical performance implications. Please set the environment variable GLIBC_TUNABLES=glibc.pthread.rseq=0
   2025-06-09T20:07:15.988+00:00: vm.max_map_count is too low
   2025-06-09T20:07:15.988+00:00: We suggest setting swappiness to 0 or 1, as swapping can cause performance problems.
------

test> { ok: 1 }
mongodb 07:18.30 [INFO [0m ==> Creating user 'unifi'...
test> Current Mongosh Log ID:	68473ef64ad021040369e327
Connecting to:		mongodb://<credentials>@127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&tlsAllowInvalidHostnames=true&appName=mongosh+2.5.2
Using MongoDB:		8.0.10
Using Mongosh:		2.5.2

For mongosh info see: https://www.mongodb.com/docs/mongodb-shell/

------
   The server generated these startup warnings when booting
   2025-06-09T20:07:15.988+00:00: For customers running the current memory allocator, we suggest changing the contents of the following sysfsFile
   2025-06-09T20:07:15.988+00:00: We suggest setting the contents of sysfsFile to 0.
   2025-06-09T20:07:15.988+00:00: Your system has glibc support for rseq built in, which is not yet supported by tcmalloc-google and has critical performance implications. Please set the environment variable GLIBC_TUNABLES=glibc.pthread.rseq=0
   2025-06-09T20:07:15.988+00:00: vm.max_map_count is too low
   2025-06-09T20:07:15.988+00:00: We suggest setting swappiness to 0 or 1, as swapping can cause performance problems.
------

test> { ok: 1 }
mongodb 07:19.44 [INFO [0m ==> Users created
mongodb 07:19.49 [INFO [0m ==> Enabling authentication...
mongodb 07:19.50 [INFO [0m ==> Stopping MongoDB...
mongodb 07:20.52 [INFO [0m ==> ** MongoDB setup finished! **
test>
mongodb 07:20.55 [INFO [0m ==> ** Starting 

< log truncated >

{"t":{"$date":"2025-06-09T17:48:27.328+00:00"},"s":"I",  "c":"ACCESS",   "id":20251,   "ctx":"conn12","msg":"Supported SASL mechanisms requested for unknown user","attr":{"user":{"user":"user","db":"admin"}}}
```

### Additional information

Maybe I'm using it incorrectly. I have searched for older issues and can't find any for this, so I think that is the case.
Can you point me to the correct way if that is the case?
When I run the script in the mongodb container, I can connect from my other pod and get a correct user:
```
kubectl exec -it -n namespace mongodb-86575b4fff-78wjm -- sh /docker-entrypoint-initdb.d/init-mongo.sh
```

```
Defaulted container "mongodb" out of: mongodb, log-dir (init)
Current Mongosh Log ID: 684743f7685319b0ec69e327
Connecting to:          mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.5.2
Using MongoDB:          8.0.10
Using Mongosh:          2.5.2

For mongosh info see: https://www.mongodb.com/docs/mongodb-shell/

test> use admin
switched to db admin
admin> db.auth("root", "root-password-here")
{ ok: 1 }
admin> db.createUser({
...   user: "user",
...   pwd: "password-here",
...   roles: [
...     { db: "user", role: "dbOwner" },
...     { db: "user_stat", role: "dbOwner" },
...     { db: "user_audit", role: "dbOwner" },
...     { db: "admin", role: "clusterMonitor" }
...   ]
... })
{ ok: 1 }
admin> % 

```

Thanks in advance. Much appreciated.
