### ISSUE TITLE
Are the new services names absolutely necessary?

### ISSUE THREAD

**Issue by zenbones** [bitnami/charts#34332]
### Name and Version

bitnami/kafka 32.2.13

### What is the problem this feature will solve?

Service names have changed from a few versions ago, having...
```
<release name>-kafka-controller-<instance number>-external
```
...to...
```
<release name>-kafka-controller-<instance number>.<release name>-kafka-controller-headless.<release name>}.svc.cluster.local
```
This is given essentially the same configuration. Have I done something wrong? Is there some new mapping I need to provide to avoid this punishment? This took a while to find because I was not expecting any change, and then to find out this monster was chosen? It seems unnecessary.

### What is the feature you are proposing to solve the problem?

Go back to the old service name, or allow an alias to be mapped.

**Comment by juan131** [comment]
Hi @zenbones 

Could you please share the values you're using? The "external" names shouldn't be affected by any change we introduced on internal names. Thanks in advance.

**Comment by zenbones** [comment]
Here's the entire section. Changes from the prior version are...

1) externalAccess.service.broker and externalAccess.service.controller -> externalAcces.broker.service and externalAcces.controller.service
2) added  defaultInitContainers.autoDiscovery.enabled
3) added   broker.automountServiceAccountToken and controller.automountServiceAccountToken
4) changed extraConfiguration: [] -> overrideConfiguration: {}

...and I think that's about it.

```
kafka:
  global:
    storageClass: gp2
  externalAccess:
    enabled: true
    autoDiscovery:
      enabled: true
    broker:
      service:
        type: LoadBalancer
        ports:
          external: 9095
    controller:
      service:
        type: LoadBalancer
        ports:
          external: 9095
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "{{ .targetPod }}.forio.internal"
  serviceAccount:
    create: true
  rbac:
    create: true
  defaultInitContainers:
    autoDiscovery:
      enabled: true
  tls:
    sslClientAuth: none
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    external:
      protocol: PLAINTEXT
  broker:
    automountServiceAccountToken: true
  controller:
    replicaCount: 2
    automountServiceAccountToken: true
    nodeSelector:
      kubernetes.io/os: linux
      silo: production-gxl
    podAntiAffinityPreset: soft
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: "ScheduleAnyway"
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: "{{ .Release.Name }}"
            app.kubernetes.io/name: "kafka"
    pdb:
      create: true
      maxUnavailable: 1
    extraEnvVars:
      - name: "JMX_PORT"
        value: "9101"
    overrideConfiguration:
      # For Acks=0
      # as few as 1 might be fine, consumer threads * broker nodes, at a guess (24 is still small)
      num.partitions: 24
      # default for number of replicas
      default.replication.factor: 1
      # min.insync.replicas=1, acks=0, replication.factor=1 for fast and un-replicated
      min.insync.replicas: 1

      # The Best Of The Rest
      # must have
      auto.create.topics.enable: true
      # allow re-balances
      auto.leader.rebalance.enable: true
      # none, gzip, lz4, snappy, and zstd (prefer lz4 as fastest if not smallest)
      compression.type: lz4
      # seems like we should
      delete.topic.enable: true
      # default 3000 (wait for consumers to join before first re-balance)
      group.initial.rebalance.delay.ms: 3000
      # how often to run the re-balance check
      leader.imbalance.check.interval.seconds: 300
      # The allowed percentage of partitions for which the broker is not the preferred leader before a re-balance occurs
      leader.imbalance.per.broker.percentage: 10
      # general consensus
      log.cleaner.backoff.ms: 15000
      # (24 hours) the retention time for deleted tombstone markers (as we do not use keys this should make no difference)
      log.cleaner.delete.retention.ms: 86400000
      # we want this
      log.cleaner.enable: true
      # if we were using keys we might use 'compact,delete'
      log.cleanup.policy: delete
      # (5 minutes) should be lower than log.retention.ms
      log.retention.check.interval.ms: 300000
      # ttl for messages (28 minutes)
      log.retention.ms: 1680000
      # maybe not necessary but not harmful
      log.segment.delete.delay.ms: 60000
      # default 1048588 (1mb, but slightly more than replica.fetch.max.bytes)
      message.max.bytes: 1048588
      # default 8
      num.io.threads: 8
      # default 3
      num.network.threads: 3
      # general consensus
      num.recovery.threads.per.data.dir: 2
      # we curretly have just 2 servers
      offsets.topic.replication.factor: 2
      # default 500 (limit the size of the request queue before the network thread is blocked)
      queued.max.requests: 500
      # default (1mb, but slightly less than message.max.bytes)
      replica.fetch.max.bytes: 1048576
      # default 30000 (upper limit on how long a producer must wait for acknowledgement, but also how quickly slow queues are removed)
      replica.lag.time.max.ms: 10000
      # we curretly have just 2 servers
      transaction.state.log.min.isr: 2
      # we curretly have just 2 servers
      transaction.state.log.replication.factor: 2
      # defaults to false, but if there's no in-sync follower when a leader fails, then no leader can be elected
      unclean.leader.election.enable: true
    podAnnotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      ad.datadoghq.com/kafka.check_names: '["kafka"]'
      ad.datadoghq.com/kafka.init_configs: '[{"is_jmx": true, "collect_default_metrics": true}]'
      ad.datadoghq.com/kafka.instances: |
        [
          {
            "host": "%%host%%",
            "port": "9101"
          }
        ]
    heapOpts: "-Xmx1024m -Xms1024m"
    resources:
      limits:
        cpu: 1000m
        memory: 1792Mi

```
