### ISSUE TITLE
[bitnami/airflow] Missing AIRFLOW__API_AUTH__JWT_SECRET environment variable in Helm Chart 24.1.2

### ISSUE THREAD

**Issue by MaAd12345** [bitnami/charts#34347]
### Name and Version

bitnami/airflow 24.1.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

After upgrading from bitnami/airflow:3.0.1-debian-12-r1 (Helm Chart version 24.1.0) to bitnami/airflow:3.0.1-debian-12-r4 with Helm Chart version 24.1.2, the AIRFLOW__API_AUTH__JWT_SECRET environment variable is no longer being created in the deployment definitions, causing startup failures.

Helm Chart Version: 24.1.2
Previous Image: bitnami/airflow:3.0.1-debian-12-r1
Current Image: bitnami/airflow:3.0.1-debian-12-r4
Update Date: June 11, 2025

1. Update Bitnami Airflow Helm Chart to version 24.1.2
2. Upgrade image from bitnami/airflow:3.0.1-debian-12-r1 to bitnami/airflow:3.0.1-debian-12-r4
3. Deploy the updated chart
4. Observe startup failures in Airflow pods

### Are you using any custom parameters or values?

```yaml
  auth:
    existingSecret: "airflow-auth-secrets"
```
in the same manner as described in the README. No changes before upgrade.

### What is the expected behavior?

The AIRFLOW__API_AUTH__JWT_SECRET environment variable should be automatically configured in all relevant deployments and statefulsets.

### What do you see instead?

The AIRFLOW__API_AUTH__JWT_SECRET environment variable is missing from the deployment configurations, causing pods to fail during startup.

The missing environment variable affects the following Kubernetes resources:

All Airflow deployments
Triggerer StatefulSet
ConfigMap "pod_template" (used for worker pod creation)

### Additional information

**Workaround**

Manually adding the following environment variable to the affected deployments resolves the issue:
```yaml
- name: AIRFLOW__API_AUTH__JWT_SECRET
  value: cat /opt/bitnami/airflow/secrets/airflow-jwt-secret-key
```

**Comment by JorgeAbrego** [comment]
I did the following

in the values file, I defined auth path like this

```yaml
auth:
  existingSecret: airflow-secrets
  username: admin
```

Then I created the secret as follows:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: airflow
type: Opaque
data:
  airflow-password: xxx
  airflow-fernet-key: xxx
  airflow-secret-key: xxx
  airflow-jwt-secret-key: xxx
  postgresql-password: xxx
  redis-password: xxx
```

It worked smoothly
