### ISSUE TITLE
dremio external s3 does not work as advertised

### ISSUE THREAD

**Issue by danieljimenez** [bitnami/charts#34504]
### Name and Version

dremio chart

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Attempt to follow instructions in documentation to setup externals3 (documentation has some inaccuracies)
2. When pods begin to start, wait-for-s3 attempts to connect:

```
Checking connection to https://:443
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
Error connecting to https://:443
```

I'm not sure what values to use to get an external s3 bucket working.

### What is the expected behavior?

dremio starts with a connect to s3 instead of minio

### What do you see instead?

dremio fails to start. the wait-for-s3 container contains the logs:

```
Checking connection to https://:443
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
Error connecting to https://:443
```

**Comment by danieljimenez** [comment]
If I set `externals3.host` to `s3.amazonaws.com`, I receive:

```
Checking connection to https://s3.amazonaws.com:443
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
Error connecting to https://s3.amazonaws.com:443
```

**Comment by jotamartos** [comment]
>I'm not sure what values to use to get an external s3 bucket working.

Depending on your configuration, the deployment generates a secret with the settings to connect to the s3 bucket. 

```
$ kubectl get secret dremio-core-site -o yaml
Warning: Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
apiVersion: v1
data:
  core-site.xml: PD94bWwgdmVyc2lvbj0iMS4wIj8+Cjxj...
```

If you check that core-site.xml file, it includes the s3 configuration. 

Regarding using an external s3 host, [you can use "minio", "aws" or "other" as distStorageType](https://github.com/bitnami/charts/blob/main/bitnami/dremio/values.yaml#L171). It's true that the AWS section in the readme is wrong, would you like to [contribute](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md)? The distStorageType parameter should be set to 'aws'.

https://github.com/bitnami/charts/tree/main/bitnami/dremio#aws-as-distributed-storage-using-access-key-authentication

Remember to disable the local minio as you will be using an external host.

**Comment by danieljimenez** [comment]
I've tried this, but I could not get it to work per the above errors from the init containers. Maybe if you provided me with some to try that might work? 

I don't feel comfortable updating documentation for code I've not written, sorry.

**Comment by danieljimenez** [comment]
I just tested again using the info from my initial post and I can confirm, even with distStorageType set to AWS, connectivity to S3 does not work, results in the same logs.

**Comment by danieljimenez** [comment]
Hi there, another update from my previous testing not defining host causes the above wait-for-s3 error, but it's not clear what to define it as. s3.amazonaws.com does not work.

**Comment by danieljimenez** [comment]
Some more examples:

This does not work, it complains that it's missing a secret named dremio-externals3

```yaml
externalS3:
  accessKeyID: --
  accessKeySecret: --
  bucket: my bucket
  # this value is required or the initContainer wait-for-s3 will not succeed
  # I tried s3.amazonaws.com but the container seems to look for an aws request id, regardless
  # of if the request passed or not. you do not need access to the bucket nor does the bucket
  # even have to be real
  host: anyvaluehere.s3.amazonaws.com
  region: us-east-2
```

If I create that secret with the proper values then I receive errors about the bucket being in the wrong region. I believe Dremio is trying to access the wrong buckets.

**Comment by danieljimenez** [comment]
```
	Caused by: com.dremio.plugins.util.ContainerNotFoundException: Error while looking up bucket scratch
		at com.dremio.plugins.s3.store.S3FileSystem.getUnknownContainer(S3FileSystem.java:373)
		at com.dremio.plugins.util.ContainerFileSystem.getFileSystemForPath(ContainerFileSystem.java:321)
		at com.dremio.plugins.util.ContainerFileSystem.mkdirs(ContainerFileSystem.java:533)
		at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:2496)
		at com.dremio.exec.hadoop.HadoopFileSystem.mkdirs(HadoopFileSystem.java:338)
		at com.dremio.io.file.FilterFileSystem.mkdirs(FilterFileSystem.java:106)
		at com.dremio.exec.store.dfs.LoggedFileSystem.mkdirs(LoggedFileSystem.java:133)
		at com.dremio.exec.store.dfs.FileSystemPlugin.createIfNecessary(FileSystemPlugin.java:951)
		... 9 common frames omitted
```

It appears I'm right, dremio, is for some reason, trying to access buckets like its a minio setup. There, of course, is no bucket name "scratch" available to write to.

**Comment by danieljimenez** [comment]
```yaml
externalS3:
  bucket: real-bucket
  path: /dremio
  host: realbucket.s3.amazonaws.com
  existingSecret: dremio-secrets
  existingSecretAccessKeyIDKey: DREMIO_AWS_ACCESS_KEY_ID
  existingSecretKeySecretKey: DREMIO_AWS_SECRET_ACCESS_KEY
  region: us-east-2
```

In this example, dremio fails when it attempts to write to a bucket named `dremio`

**Comment by danieljimenez** [comment]
#34784 is caused by this error, can Bitnami assist before I have to tear up the chart?

**Comment by danieljimenez** [comment]
@carrodher any thoughts here? Chart is busted when trying to use s3 in any fashion. I do not believe you can use S3 for either the distributed store or internally to dremio. Both try to talk to minio even though it's disabled.

```yaml
externalS3:
  bucket: real-bucket
  path: /dremio
  host: realbucket.s3.amazonaws.com
  existingSecret: dremio-vault-secrets
  existingSecretAccessKeyIDKey: DREMIO_AWS_ACCESS_KEY_ID
  existingSecretKeySecretKey: DREMIO_AWS_SECRET_ACCESS_KEY
  region: us-east-2

dremio:
  distStorageType: aws
  auth:
    enabled: true
    username: admin
    password: admin1
    firstName: Admin
    lastName: Account
    email: dremio@example.com

minio:
  enabled: false
```
