### ISSUE TITLE
[bitnami/thanos] Mount path issue with chart 2.3.1 and ruler.

### ISSUE THREAD

**Issue by Whyeasy** [bitnami/charts#3451]
**Which chart**:
[bitnami/thanos] 2.3.1

**Describe the bug**
With the latest PR: https://github.com/bitnami/charts/pull/3396.

It produces the following error in the ruler when providing objstore.yml via excisting secret:
```
caller=grpc.go:92 component=rules service=gRPC/server component=rule msg="registering as gRPC StoreAPI and RulesAPI"
level=error ts=2020-08-18T09:19:06.886545359Z caller=main.go:185 err="open /conf/objstore/objstore.yml: no such file or directory
```

If code block can be removed to fix this issue.

```yaml
- name: objstore-config
{{- if .Values.existingObjstoreSecretItems }}
mountPath: /conf
{{- else }}
mountPath: /conf/objstore
{{- end }}
```

**To Reproduce**
1. Provide the objstore.yml with `existingObjstoreSecretItems`.
2. Start ruler

**Expected behavior**
It should mount the secret in the right location and start.
