### ISSUE TITLE
Subpath for matomo persistence

### ISSUE THREAD

**Issue by BoKKeR** [bitnami/charts#34516]
### Name and Version

matomo/9.3.8

### What is the problem this feature will solve?

Most bitnami charts allow for setting the subpath on the PVC, this allows for using a NFS storage PVC with multiple subpaths (subfolders). This is not possible today with matomo.

### What is the feature you are proposing to solve the problem?

Add subpath to persistance. Example from mariadb-galera which is also a bitnami chart
```
    persistence:
      enabled: true
      existingClaim: unraid-un-nvme-pvc
      subPath: mariadb-galera
```
