### ISSUE TITLE
[bitnami/minio] Root user not superuser

### ISSUE THREAD

**Issue by hrvatskibogmars** [bitnami/charts#34525]
### Name and Version

bitnami/minio:2025.5.24-debian-12-r6

### What architecture are you using?

None

### What steps will reproduce the bug?

I am using 17.0.5 helm chart version.

I have a pretty basic setup of Minio. I have also enabled `console:true`. I am able to port-forward with the admin user to the console, but I don't have consoleAdmin. I can only create a bucket and that's it.

How can I grant this auth: root user superuser admin privileges. Since this user should be superuser?

### Are you using any custom parameters or values?

```yaml
    auth:
      ## @param auth.rootUser MinIO&reg; root username
      ##
      rootUser: admin
      ## @param auth.rootPassword Password for MinIO&reg; root user
      ##
      rootPassword: "test"
      ## @param auth.existingSecret Use existing secret for credentials details (`auth.rootUser` and `auth.rootPassword` will be ignored and picked up from this secret).
      ##
      existingSecret: ""
      ## @param auth.rootUserSecretKey Key where the MINIO_ROOT_USER username is being stored inside the existing secret `auth.existingSecret`
      ##
      rootUserSecretKey: ""
      ## @param auth.rootPasswordSecretKey Key where the MINIO_ROOT_USER password is being stored inside the existing secret `auth.existingSecret`
      ##
      rootPasswordSecretKey: ""
      ## @param auth.forcePassword Force users to specify required passwords
      ##
      forcePassword: false
      ## @param auth.usePasswordFiles Mount credentials as a files instead of using an environment variable
      ##
      usePasswordFiles: true
      ## @param auth.useSecret Uses a secret to mount the credential files.
      ##
      useSecret: true
      ## @param auth.forceNewKeys Force root credentials (user and password) to be reconfigured every time they change in the secrets
      ##
      forceNewKeys: false
```

### What do you see instead?

When I log in as root user I can only create buckets. In previous versions of helm chart this user was able to create policies, groups, etc.
