### ISSUE TITLE
[bitnami/minio] Console podSecurityContext is not adapted to OpenShift

### ISSUE THREAD

**Issue by dmitrii-parshenkov** [bitnami/charts#34572]
### Name and Version

bitnami/minio 17.0.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When rending charts with openShift compatibility, one can clearly see that the podSecurityContext is not being adapted:

1. Render charts with the compatibility enabled and disabled

```
ocpmanifests=$(helm template oci://mirror.gcr.io/bitnamicharts/minio --version 17.0.5 --set global.compatibility.openshift.adaptSecurityContext=force)
vanillamanifests=$(helm template oci://mirror.gcr.io/bitnamicharts/minio --version 17.0.5 --set global.compatibility.openshift.adaptSecurityContext=auto)
```

2. Check that API's podSecurityContext is being adapted:

```
echo "$vanillamanifests" | yq 'select(.kind == "Deployment" and .metadata.name == "release-name-minio") | .spec.template.spec.securityContext'

# fsGroup: 1001
# fsGroupChangePolicy: OnRootMismatch
# supplementalGroups: []
# sysctls: []

echo "$ocpmanifests" | yq 'select(.kind == "Deployment" and .metadata.name == "release-name-minio") | .spec.template.spec.securityContext'

# fsGroupChangePolicy: OnRootMismatch
# supplementalGroups: []
# sysctls: []
```

3. Check that Console's podSecurityContext is NOT being adapted:

```
echo "$vanillamanifests" | yq 'select(.kind == "Deployment" and .metadata.name == "release-name-minio-console") | .spec.template.spec.securityContext'

# fsGroup: 1001
# fsGroupChangePolicy: Always
# supplementalGroups: []
# sysctls: []

echo "$ocpmanifests" | yq 'select(.kind == "Deployment" and .metadata.name == "release-name-minio-console") | .spec.template.spec.securityContext'

# fsGroup: 1001
# fsGroupChangePolicy: Always
# supplementalGroups: []
# sysctls: []
```

When creating the charts, the podSecurityContext in `minio/templates/console/deployment.yaml` was not set to render using a compatibility function:

```yaml
# line 71-73 in minio/templates/console/deployment.yaml
      {{- if .Values.console.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.console.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}

# line 87-89 in minio/templates/application.yaml
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.podSecurityContext "context" .) | nindent 8 }}
      {{- end }}
```

### Are you using any custom parameters or values?

--set global.compatibility.openshift.adaptSecurityContext=force

### What is the expected behavior?

```yaml
fsGroupChangePolicy: Always
supplementalGroups: []
sysctls: []
```

### What do you see instead?

```yaml
fsGroup: 1001
fsGroupChangePolicy: Always
supplementalGroups: []
sysctls: []
```
