### ISSUE TITLE
Kafka doesn't start after SSL was configured with existingCert or AutoGenerated certs.

### ISSUE THREAD

**Issue by vsfomin** [bitnami/charts#34577]
### Name and Version

bitnami/kafka:4.0.0-debian-12-r7

### What architecture are you using?

None

### What steps will reproduce the bug?

I've installed Bitnami Kafka chart 
I installed the Bitnami Kafka chart 32.2.17 AppVersion 4.0.0 in Kraft mode (by default) and configured external interaction with the cluster. In this setup, Kafka works stably, and there is a connection to the broker. Next, I try to enable SSL, after which the controller and broker stop loading. I have tried using my existing secret as well as auto-generating PEM certificates. The result is the same.

The error that I've seen: 
```
Caused by: java.security.cert.CertificateException: Unknown identification algorithm: null
```

```
inter.broker.listener.name=INTERNAL
listener.security.protocol.map=CONTROLLER:SSL,CLIENT:SSL,INTERNAL:SSL
listeners=CLIENT://:9092,INTERNAL://:9094,CONTROLLER://:9093
log.dir=/bitnami/kafka/data
logs.dir=/opt/bitnami/kafka/logs
process.roles=controller,broker
ssl.client.auth=required
ssl.endpoint.identification.algorithm=null
ssl.keystore.location=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
ssl.keystore.type=JKS
ssl.truststore.location=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
ssl.truststore.type=JKS
```

```yaml
image:
  debug: false
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: docker.io
  repository: bitnami/kafka
  tag: 4.0.0-debian-12-r7
initContainers: []
interBrokerProtocolVersion: ""
kubeVersion: ""
listeners:
  advertisedListeners: ""
  client:
    containerPort: 9092
    name: CLIENT
    protocol: SSL
    sslClientAuth: required
  controller:
    containerPort: 9093
    name: CONTROLLER
    protocol: SSL
    sslClientAuth: required
  external:
    containerPort: 9095
    name: EXTERNAL
    protocol: SSL
    sslClientAuth: required
  extraListeners: []
  interbroker:
    containerPort: 9094
    name: INTERNAL
    protocol: SSL
    sslClientAuth: required
  provisioning:
    args: []
    auth:
      tls:
        caCert: ca.crt
        cert: tls.crt
        certificatesSecret: kafka-client-cert-secret
        key: tls.key
        keyPassword: testpass
        keyPasswordSecretKey: ""
        keystore: keystore.jks
        keystorePassword: testpass
        keystorePasswordSecretKey: ""
        passwordsSecret: ""
        truststore: truststore.jks
        truststorePassword: testpass
        truststorePasswordSecretKey: ""
        type: PEM
    automountServiceAccountToken: false
    command: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      enabled: true
  
```

### What do you see instead?

This is all output in Kafka's POD:
```
Importing keystore /certs/kafka.keystore.p12 to /certs/kafka.keystore.jks...
Entry for alias 1 successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
Certificate was added to keystore
...
Caused by: java.security.cert.CertificateException: Unknown identification algorithm: null
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source) ~[?:?]
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source) ~[?:?]
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source) ~[?:?]
```

**Caused by: java.security.cert.CertificateException: Unknown identification algorithm: null**

 endpointIdentificationAlgorithm: ""  - maybe this is the root cause, but I need to keep it empty, I think. 
(Disable server host name verification by setting ssl.endpoint.identification.algorithm to an empty string.)

**Comment by vsfomin** [comment]
[values.txt](https://github.com/user-attachments/files/20839063/values.txt)
Whole values file

**Comment by carrodher** [comment]
You're correct in identifying that the root cause is related to the `ssl.endpoint.identification.algorithm` setting. The error:
```
Caused by: java.security.cert.CertificateException: Unknown identification algorithm: null
```
suggests that Kafka is interpreting null literally instead of disabling hostname verification, which is what you intended.

To disable server hostname verification properly, you need to explicitly set the `ssl.endpoint.identification.algorithm` to an empty string, not to _null_.

In your Kafka configuration, it should look like this:

```
ssl.endpoint.identification.algorithm=
```

However, in the current deployment, the value is being passed as _null_, which Java does not interpret as “disabled,” but instead triggers an error, as you observed.

You can add the following to your Helm chart’s values.yaml under the extraEnvVars section:

```yaml
extraEnvVars:
  - name: KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
    value: ""
```
Alternatively, in the listeners section, if you’re passing values via Helm, make sure the final rendered value ends up with:

```
ssl.endpoint.identification.algorithm=
```
