### ISSUE TITLE
[bitnami/postgresql] persistence.existingClaim No Longer Working?

### ISSUE THREAD

**Issue by sguidos** [bitnami/charts#3463]
**Which chart**:  bitnami/postgresql   (latest)

**Describe the bug**
Pod errors with "Back-off restarting failed container"
kubectl logs for pod shows "postgres: could not access directory "/bitnami/postgresql/data": Permission denied"

**To Reproduce**
```    
helm install bullseye-postgresql bitnami/postgresql \
    --set service.type=LoadBalancer \
    --set securityContext.runAsUser=0 \
    --set securityContext.fsGroup=0 \
    --set persistence.existingClaim=pgdata-pvc
```
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  storageClassName: hostpath
  hostPath:
    path: "/tmp/pgdata"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: hostpath
```

**Expected behavior**
postgresql uses the PVC to persist the database files

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I will swear that yesterday the above helm install command was working on both my Docker Desktop for Windows (Helm v2 and kubectl v1.15.5) and Kubernetes installed on Ubuntu v20.04 running on AWS (Helm v3 and kubeclt v1.18.8) but today the postgres pod seems to ignore the "persistence.existingClaim" parameter, and tries to create the database in the default "/bitnami/postgresql/data" folder.  (Even so, I would think that the securityContext=0 should have sufficient permissions there?)

On the Ubuntu AWS instance, the default "data-bullseye-postgresql-postgresql-0" PVC is created, even though we are specifying our own PVC to use; on Docker Desktop for Windows, the default "data-bullseye-postgresql-postgresql-0" PVC is not created.

I do see that code adding options for slave persistence was merged overnight and a new chart version created.

If I leave in the two securityContext parameters but remove the persistence.existingClaim parameter, the Docker Desktop for Windows instance will create persisted storage using its "hostpath" default storage class at its default location on the DockerDesktopVM, but the Ubuntu running on AWS has no default storage class and I cannot figure out how to create one (or if that is even possible).

I'm a bit of a K8S noob, so any help is appreciated, thanks.

**Comment by andresbono** [comment]
Hi @sguidos, we couldn't reproduce the issue with bitnami/postgresql `9.2.1`, the latest published version of the chart. What is the version that you are using?

**Comment by sguidos** [comment]
I finally found my problem.  When using a hostpath PersistentVolume that directory must exist on the disk.  Unfortunately, if the directory does not exist, creation of the PersistentVolume will not throw an error, and this is the intentional behavior of a PV, see [https://github.com/kubernetes/kubernetes/issues/48463#issuecomment-319825352](url)  The fact that the directory must exist and that no error is thrown is not well documented (at least in my opinion, LOL, but that's another issue).

So in the K8S Dashboard, my PV and PVC showed "green" with no errors.  However when postgres fires up it cannot find the path specified in the existingClaim's PV, and so it uses its default "/bitnami/postgresql/data" folder.

I would like to suggest that when postgres "defaults" to a different directory than is found in the existingClaim PV, that fact is logged for troubleshooting purposes.  Is this suggestion appropriate for this chart team, or more appropriate for the postgresql team?  Seeing a log entry similar to "Could not find the directory '/xxxx/yyy/zzz' specified in the existingClaim / PVC, using default folder of '/bitnami/postgresql/data' instead" would be very helpful for troubleshooting, thanks.

**Comment by andresbono** [comment]
Hi @sgidos, we are glad you could solve the issue. About your suggestion, there is a problem. The hostPath of the persistent volume is transparent to the container validation logic, so it would be difficult to achieve what you are describing. As an alternative you might want to try with the `local-storage` class: https://kubernetes.io/docs/concepts/storage/volumes/#local

We tried the following:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-local-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  storageClassName: local-storage
  local:
    path: /tmp/dir_does_not_exist
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-worker
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage
```

And we installed the chart with:

```
helm install postgresql bitnami/postgresql --set persistence.existingClaim=pgdata-local-pvc
```


It is very similar to hostPath but the pod will be in status `ContainerCreating` until the directory exists. If you describe the pod:

```
  Warning  FailedMount  19s (x8 over 83s)  kubelet, kind-worker  MountVolume.NewMounter initialization failed for volume "pgdata-local-pv" : path "/tmp/dir_does_not_exist" does not exist
```
