### ISSUE TITLE
[bitnami/kafka] Settings are not added to server.properties via env vars

### ISSUE THREAD

**Issue by vsfomin** [bitnami/charts#34654]
### Name and Version

bitnami/kafka  32.2.17

### What steps will reproduce the bug?
I need to add some custom configuration to server.properties :
```
super.users
authorized.class.name
allow.everyone.if.no.acl.found
ssl.endpoint.identification.algorythm
```
For some reason, I can't add additional settings to _server.properties by adding additional Environment Variables:
`KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=` works for me, it is present in the server.options. But other variables are not in _server.properties , for example `KAFKA_CFG_AUTHORIZER_CLASS_NAME` or `KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND`
But I see it in _env_ command output:
```
$ env | grep CFG
KAFKA_CFG_SUPER_USERS=User:CN=hrdh-kafka-01.hrdh-kafka-01.svc.cluster.local;
KAFKA_CFG_PROCESS_ROLES=broker
KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=false
KAFKA_CFG_AUTHORIZER_CLASS_NAME=org.apache.kafka.metadata.authorizer.StandardAuthorizer
KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
```

Env part from broker StatefulSet:
```yaml
          env:
            - name: KAFKA_HEAP_OPTS
              value: '-Xmx1024m -Xms1024m'
            - name: KAFKA_CFG_PROCESS_ROLES
              value: broker
            - name: BITNAMI_DEBUG
              value: 'true'
            - name: KAFKA_KRAFT_CLUSTER_ID
              valueFrom:
                secretKeyRef:
                  name: hrdh-kafka-01-kraft
                  key: cluster-id
            - name: KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
              value: ' '
            - name: KAFKA_CFG_SUPER_USERS
              value: User:CN=hrdh-kafka-01.hrdh-kafka-01.svc.cluster.local;
            - name: KAFKA_CFG_AUTHORIZER_CLASS_NAME
              value: org.apache.kafka.metadata.authorizer.StandardAuthorizer
            - name: KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND
              value: 'false'
```
```console
$ cat /opt/bitnami/kafka/config/server.properties
advertised.listeners=CLIENT://hrdh-kafka-01-broker-0.hrdh-kafka-01-broker-headless.hrdh-kafka-01.svc.cluster.local:9092,INTERNAL://hrdh-kafka-01-broker-0.hrdh-kafka-01-broker-headless.hrdh-kafka-01.svc.cluster.local:90
94,EXTERNAL://100.78.3.40:31195
controller.listener.names=CONTROLLER
controller.quorum.bootstrap.servers=hrdh-kafka-01-controller-0.hrdh-kafka-01-controller-headless.hrdh-kafka-01.svc.cluster.local:9093
inter.broker.listener.name=INTERNAL
listener.security.protocol.map=CONTROLLER:SSL,CLIENT:SSL,INTERNAL:SSL,EXTERNAL:SSL
listeners=CLIENT://:9092,INTERNAL://:9094,EXTERNAL://:9095
log.dir=/bitnami/kafka/data
logs.dir=/opt/bitnami/kafka/logs
process.roles=broker
ssl.client.auth=required
ssl.endpoint.identification.algorithm=
ssl.keystore.location=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
ssl.keystore.type=JKS
ssl.truststore.location=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
ssl.truststore.type=JKS
node.id=100
ssl.keystore.password=****
ssl.truststore.password=****
```

### What is the expected behavior?

When adding variables to `extraEnvVars` I should see the configured extra options in _server.properties 

### What do you see instead?

I don't see any additional configuration based on env vars like `KAFKA_CFG....`
