### ISSUE TITLE
Dynamic redis maxmemory based on container's memory request

### ISSUE THREAD

**Issue by georgelupu** [bitnami/charts#34674]
### Name and Version

bitnami/redis:latest

### What is the problem this feature will solve?

Problem: Redis maxmemory has to be adjusted manually in the Values file to accommodate the changing workload.

### What is the feature you are proposing to solve the problem?

I am looking at the latest Bitnami Redis docs, and I cannot find a way to dynamically adjust Redis maxmemory based on the container's memory request. 
It would be nice to include such a feature by default in the chart (at least during the initial container start).
Examples of values that we can provide:
```yaml
    dynamicMaxmemory:
      enabled: true # Set to false to disable this feature
      percentage: 80 # Percentage of container's memory limit to use for maxmemory
      fallbackMaxmemory: "512Mi" # Fallback if cgroup limit cannot be determined 
```
We can go even one step further - if VPA is used to adjust on the fly the container's memory, run periodically a cronjob of some sort to adjust the maxmemory on the fly (without restarting Redis).

### What alternatives have you considered?

Workaround: 
(1) Build a custom initContainer to calculate the maxmemory and dump that value to a file which will be used by redis at startup:
```
LIMIT_BYTES=$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes)
MAXMEMORY_BYTES=$((LIMIT_BYTES * 80 / 100))

echo "maxmemory ${MAXMEMORY_BYTES}" > /opt/bitnami/redis/conf/extra.conf
exec redis-server /opt/bitnami/redis/conf/redis.conf --include /opt/bitnami/redis/conf/extra.conf
```
(2) Use a sidecar cron container or k8s crontab (that has kubectl, jq, redis-cli) to periodically CONFIG SET MAXMEMORY in case VPA updates the container's memory request.
