### ISSUE TITLE
mongodb deployment on kubernetes  with nodeport externalAccess ,but not access.

### ISSUE THREAD

**Issue by wangchao732** [bitnami/charts#34684]
### Name and Version

binnami/mongodb:16.5.25

### What steps will reproduce the bug?

kubernetes: 1.23

### Are you using any custom parameters or values?

values.yaml externalAccess:
```yaml
externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
    image:
      registry: "registry.cn-hongkong.aliyuncs.com"
      repository: bcldops/kubectl
      tag: 1.33.2-debian-12-r0
      digest: ""
      pullPolicy: IfNotPresent
      pullSecrets: []
    resourcesPreset: "nano"
    resources: {}
  dnsCheck:
    image:
      registry: "registry.cn-hongkong.aliyuncs.com"
      repository: bcldops/os-shell
      tag: 12-debian-12-r47
      digest: ""
      pullPolicy: IfNotPresent
      pullSecrets: []
    resourcesPreset: "nano"
    resources: {}
  externalMaster:
    enabled: false
    host: ""
    port: 27017
  service:
    type: NodePort
    portName: "mongodb"
    ports:
      mongodb: 27017
    loadBalancerIPs: []
    publicNames: []
    loadBalancerClass: ""
    loadBalancerSourceRanges: []
    allocateLoadBalancerNodePorts: true
    externalTrafficPolicy: Local
    
    nodePorts: [30010,30020,30030]
    domain: "192,168.11.107"
    extraPorts: []
    annotations: {}
    annotationsList: []
    sessionAffinity: None
    sessionAffinityConfig: {}
  hidden:
    enabled: false
    service:
      type: LoadBalancer
      portName: "mongodb"
      ports:
        mongodb: 27017
      loadBalancerIPs: []
      loadBalancerClass: ""
      loadBalancerSourceRanges: []
      allocateLoadBalancerNodePorts: true
      externalTrafficPolicy: Local
      
      nodePorts: []
      domain: ""
      extraPorts: []
      annotations: {}
      sessionAffinity: None
      sessionAffinityConfig: {}
```

### What is the expected behavior?

mongo-shell can be connected!! But mongodb://xxx:27017 error:
```
pymongo.errors.ServerSelectionTimeoutError: mongodb-arbiter-0.mongodb-arbiter-headless.mongodb.svc.cluster.local:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms),mongodb-0.mongodb-headless.mongodb.svc.cluster.local:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms),mongodb-1.mongodb-headless.mongodb.svc.cluster.local:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms), Timeout: 5.0s, Topology Description: <TopologyDescription id: 685e0c09a8119791b05f6077, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-0.mongodb-headless.mongodb.svc.cluster.local', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb-0.mongodb-headless.mongodb.svc.cluster.local:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms)')>, <ServerDescription ('mongodb-1.mongodb-headless.mongodb.svc.cluster.local', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb-1.mongodb-headless.mongodb.svc.cluster.local:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms)')>, <ServerDescription ('mongodb-arbiter-0.mongodb-arbiter-headless.mongodb.svc.cluster.local', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb-arbiter-0.mongodb-arbiter-headless.mongodb.svc.cluster.local:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms)')>]>
```
