### ISSUE TITLE
bitnami/valkey-cluster Doesnt create a statefulset when using cluster.externalAccess.enabled=true

### ISSUE THREAD

**Issue by bjarnelundqvist** [bitnami/charts#34693]
### Name and Version

bitnami/valkey-cluster 3.0.14

### What steps will reproduce the bug?

`helm template valkey bitnami/valkey-cluster --version 3.0.14 --values values.yaml --namespace valke` 

With values file
```yaml
cluster:
  nodes: 3
  externalAccess:
    enabled: true
    service:
      type: LoadBalancer

existingSecret: "valkey-secret"
existingSecretPasswordKey: "password"

metrics:
  enabled: true
```

Does not create the file templates/valkey-statefulset.yaml.
But with
```yaml
cluster:
  nodes: 3

existingSecret: "valkey-secret"
existingSecretPasswordKey: "password"

metrics:
  enabled: true
``` 
it does.

### Are you using any custom parameters or values?

```yaml
cluster:
  externalAccess:
    enabled: true
    service:
      type: LoadBalancer
```
### What is the expected behavior?

templates/valkey-statefulset.yaml should be created

### What do you see instead?

Missing file
