### ISSUE TITLE
[bitnami/dremio] engine overrides clobber each other

### ISSUE THREAD

**Issue by danieljimenez** [bitnami/charts#34703]
### Name and Version

bitnami/dremio

### What steps will reproduce the bug?

1. Using a release.yaml of below, both engine statefulsets will have the same tolerance of "heavy".

```yaml
executor:
  common:
    # shared defaults for all engines
    tolerations: []
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1Gi

  engines:
    - name: light
      overrides:
        # light engine gets low resources + a “light” toleration
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 512Mi
        tolerations:
          - key: "node-role.kubernetes.io/light"
            operator: Exists

    - name: heavy
      overrides:
        # heavy engine gets bigger resources + a “heavy” toleration
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 2
            memory: 4Gi
        tolerations:
          - key: "node-role.kubernetes.io/heavy"
            operator: Exists
```

[rendered-chart.txt](https://github.com/user-attachments/files/20968643/rendered-chart.txt)

### What do you see instead?

The helm chart attaches the tolerance for the heavy engine to all engines, and discards the overrides and common field. Seems to be a merge issue.
