### ISSUE TITLE
[bitnami/kafka] Invalid YAML generated when using listeners.extraListeners due to improper newline handling

### ISSUE THREAD

**Issue by roikyeutpu** [bitnami/charts#34731]
### Name and Version

bitnami/kafka 32.2.18

### What steps will reproduce the bug?

When using `listeners.extraListeners` to configure multiple additional ports (e.g., for `SASL_PLAINTEXT` and `SSL`), the rendered YAML is invalid. The Helm template for `extraListeners` does not insert newlines between list items, causing multiple - name: entries to appear on the same line, which is not valid YAML. This causes Helm to fail with the following error:
```
Error: YAML parse error on kafka/templates/controller-eligible/statefulset.yaml: error converting YAML to JSON: yaml: line 361: mapping values are not allowed in this context
```
To Reproduce
Use the following simplified values.yaml:
```yaml
listeners:
  client:
    containerPort: 9092
  interbroker:
    containerPort: 9094
  extraListeners:
    - name: sasl_plaintext
      containerPort: 9095
      protocol: SASL_PLAINTEXT
    - name: ssl
      containerPort: 9096
      protocol: SSL
```
Then run:
```
helm template kafka bitnami/kafka --version 32.2.18 -f values.yaml --debug
```
Note that there are many other fields that are required to correctly render when SSL is enabled, but the given simplified values.yaml will show the immediate issue.

### What is the expected behavior?

Properly formatted list with newlines:
```yaml
ports:
  - name: controller
    containerPort: 9093
  - name: client
    containerPort: 9092
  - name: interbroker
    containerPort: 9094
  - name: sasl_plaintext
    containerPort: 9095
  - name: ssl
    containerPort: 9096
```

### What do you see instead?

The rendered `containers.ports` section includes:
```yaml
ports:
  - name: controller
    containerPort: 9093
  - name: client
    containerPort: 9092
  - name: interbroker
    containerPort: 9094
  - name: sasl_plaintext
    containerPort: 9095- name: ssl
    containerPort: 9096
```
This YAML is invalid due to the lack of a newline between the two extra listeners.

### Additional information

**Root Cause**
The helper function `kafka.extraListeners.containerPorts` (in _helpers.tpl) trims all whitespace between looped entries:
```yaml
{{- define "kafka.extraListeners.containerPorts" -}}
{{- range $listener := .Values.listeners.extraListeners -}}
- name: {{ lower $listener.name}}
  containerPort: {{ $listener.containerPort }}
{{- end -}}
{{- end -}}
```
Because all blocks use `{{- and -}}`, Helm strips newlines between list items, resulting in malformed YAML.

**Proposed Fix**
I believe _helpers.tpl should be updated to preserve spacing between list items:
```yaml
{{- define "kafka.extraListeners.containerPorts" -}}
{{- range $listener := .Values.listeners.extraListeners }}
- name: {{ lower $listener.name }}
  containerPort: {{ $listener.containerPort }}
{{- end -}}
{{- end -}}

```
Specifically, remove the trailing - from `{{- define "kafka.extraListeners.containerPorts" -}}` to allow a newline after each list item.

**Environment**
* Helm version: v3.15.0
* OS: macOS / Linux (any)

**Additional Context**
This is blocking deployment of valid multi-listener configurations (e.g., TLS and SASL) via Helm.
