### ISSUE TITLE
[stable/prometheus-operator] podMetaData not being set by helm

### ISSUE THREAD

**Issue by eperdeme** [bitnami/charts#3473]
**Which chart**:
stable/prometheus-operator 0.30.0 / master

**Describe the bug**
When setting the PodMetaData values the template is not using them

**To Reproduce**
1. Create a my-values.yaml with contents
```
prometheus:
    podMetaData:
        labels: 
           hello: true
           cows: likecrass
           app: cows
        annotations:
           name: moo
           cows: cows
```
2. helm template . -f prometheus.yaml   | grep cows
3. Grep returns empty

**Expected behavior**
I would expect to see labels + annotations on the prometheus pod and in the helm template output.

**Version of Helm and Kubernetes**:

```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}
```

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T11:06:25Z", GoVersion:"go1.14.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
