### ISSUE TITLE
[bitnami/postgresql] permission error if initdbScripts defined

### ISSUE THREAD

**Issue by raphaelcervantes** [bitnami/charts#3537]
**Which chart**:
postgresql-9.3.3

**Describe the bug**
If I set` persistence.enabled = True` and then add a script to the `initdbScripts` dictionary, then I get a permission error
```
postgresql 15:05:07.21 INFO  ==> Starting PostgreSQL in background...
touch: cannot touch '/bitnami/postgresql/.user_scripts_initialized': Permission denied
```
The error does not occur if `initdbScripts` is empty. Also, the error does not occur if `initdbScripts` has data, but the `persistence.enabled=False`.

**To Reproduce**
1. Define a custom values file.
```
[external_charts] cat postgresql-minimal-values.yaml                                         feature/na_log_view  ✭ ✱
postgresqlUsername: "orpheus_master"
existingSecret: postgres-secret

persistence:
  enabled: true
  existingClaim: postgres-pvc

volumePermissions:
  enabled: true

initdbScripts:
  10_setup.sql: |
    CREATE DATABASE sensor_data WITH TEMPLATE = template0;
```

2. Install the postgresql helm chart with the custom values.
`[external_charts] helm install postgres-minimal bitnami/postgresql -f postgresql-minimal-values.yaml`

3. Observe that the postgresql pod goes into a CrashLoop.
```
[k8_secrets] kubectl get pods                                                                                        
NAME                            READY   STATUS             RESTARTS   AGE
postgres-minimal-postgresql-0   0/1     CrashLoopBackOff   6          10m
```

4. Look at the postgres pod logs. Find the permission error.
```
[k8_secrets] kubectl logs postgres-minimal-postgresql-0                                                              
postgresql 15:10:58.90 
postgresql 15:10:58.90 Welcome to the Bitnami postgresql container
postgresql 15:10:58.90 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 15:10:58.91 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 15:10:58.91 
postgresql 15:10:58.92 INFO  ==> ** Starting PostgreSQL setup **
postgresql 15:10:58.94 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 15:10:58.95 INFO  ==> Loading custom pre-init scripts...
postgresql 15:10:58.95 INFO  ==> Initializing PostgreSQL database...
postgresql 15:10:58.97 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 15:10:58.97 INFO  ==> Generating local authentication configuration
postgresql 15:10:58.98 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 15:10:58.98 INFO  ==> Configuring replication parameters
postgresql 15:10:59.00 INFO  ==> Configuring fsync
postgresql 15:10:59.01 INFO  ==> Loading custom scripts...
postgresql 15:10:59.01 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
postgresql 15:10:59.02 INFO  ==> Starting PostgreSQL in background...
touch: cannot touch '/bitnami/postgresql/.user_scripts_initialized': Permission denied
postgresql 15:10:59.20 INFO  ==> Stopping PostgreSQL...
```

**Expected behavior**
I expect that the pod to be able to start with the initdBScripts defined.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"archive", BuildDate:"2020-07-01T16:28:46Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by andresbono** [comment]
Hi @raphaelcervantes, we couldn't reproduce it in our environment. What is the type of Persistent Volume Claim that you are specifying with `existingClaim: postgres-pvc`? That volume is mounted in `/bitnami/postgresql` and, for some reason, it seems it is not writable. Can you check it?

```
$ kubectl exec -it postgresql-postgresql-0 -- ls -la /bitnami/postgresql
total 12
drwxrwxrwx  3 root root 4096 Aug 28 13:32 .
drwxr-xr-x  3 root root 4096 Aug 18 10:49 ..
drwx------ 19 1001 1001 4096 Aug 28 13:32 data
-rw-r--r--  1 1001 root    0 Aug 28 13:32 .user_scripts_initialized
```

You can check it by removing the `initdbScrips` value so it doesn't fail for you.

**Comment by raphaelcervantes** [comment]
Thank you for looking into this.

I configure a storage class, a persistent volume, and a persistent volume claim.

### Storage class local-storage-class.yaml
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```
### persistent volume postgres-pv.yaml
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    type: local
    app: postgresql
spec:
  storageClassName: local-storage
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/bitnami/postgresql"
```
### Persistent volume claim postgres-pvc.yaml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  labels:
    app: postgresql
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
```
After removing my `initdbScripts`, I run you ls command
```
[external_charts] kubectl exec -it postgres-minimal-postgresql-0 -- ls -la /bitnami/postgresql 
total 12
drwxr-xr-x  3 root root 4096 Aug 28 14:43 .
drwxr-xr-x  3 root root 4096 Aug 18 10:49 ..
drwx------ 19 1001 1001 4096 Aug 28 14:44 data
```
On my local host, I create the` bitnami/postgresql `using `sudo mkdir -p /bitnami/postgresql `

It looks like the permissions for the `bitnami/postgresql` folder are different than yours.
