### ISSUE TITLE
Error deploying bitnami/drupal using an external azure mariadb

### ISSUE THREAD

**Issue by foroozf001** [bitnami/charts#3547]
**Which chart**:
Helm-chart: bitnami/drupal (9.0.3)
Kubernetes version: 1.17.7
MariaDB version: 10.3

**Describe the bug**
Deploying the ```bitnami/drupal``` Helm-chart with default parameter values goes perfectly fine. But in this case I am not running MariaDb in a pod on Kubernetes, but as a service in Azure. To make Drupal connect to this MariaDb I am passing ```mariadb.enabled=false``` and the ```externalDatabase```-parameters. I have these parameters setup in a yaml-file and I'm passing this file as an argument to the Helm-chart. It seems to me that setting ```mariadb.enabled``` to false will always result in an error message. 

```
--- 
ingress: 
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: addon-http-application-routing
  hostname: "<MY_HOSTNAME>"

service: 
  type: ClusterIP

drupalPassword: "drupal"
drupalUsername: "user"

externalDatabase:
  host: "<DB_HOSTNAME>"
  port: 3306
  user: "user"
  password: "drupal"
  database: "test"

mariadb:
  enabled: false
```

**To Reproduce**
1. Install bitnami repo:
```
% helm repo add bitnami https://charts.bitnami.com/bitnami
```
2. Set mariadb.enabled to false via either a yaml-file or command line:
3. Install the Helm chart onto namespace in AKS cluster:
```
% helm install drupal bitnami/drupal -f values.yaml -n drupal
```
or
```
% helm install drupal bitnami/drupal -n drupal --set mariadb.enabled=false --set externalDatabase.host=<DB_HOSTNAME> --set externalDatabase.port=3306 --set externalDatabase.user="user" --set ex
ternalDatabase.password="drupal" --set externalDatabase.database="test"
```
```
Error: template: drupal/templates/NOTES.txt:57:28: executing "drupal/templates/NOTES.txt" at <include "common.validations.values.mariadb.passwords" (dict "secretName" (include "drupal.mariadb.fullname" .) "context" $)>: error calling include: template: drupal/charts/common/templates/_validations.tpl:68:98: executing "common.validations.values.mariadb.passwords" at <.context.Values.mariadb.secret.requirePasswords>: nil pointer evaluating interface {}.requirePasswords
```

**Expected behavior**
I expect the Helm chart to install successfully like so:
```
NAME: drupal
LAST DEPLOYED: Fri Aug 28 18:38:36 2020
NAMESPACE: drupal
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
*******************************************************************
*** PLEASE BE PATIENT: Drupal may take a few minutes to install ***
*******************************************************************

1. Get the Drupal URL:

  You should be able to access your new Drupal installation through

  <MY_HOSTNAME>

2. Login with the following credentials

  echo Username: user
  echo Password: $(kubectl get secret --namespace drupal drupal -o jsonpath="{.data.drupal-password}" | base64 --decode)
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

- Output of `kubectl version --client`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
