### ISSUE TITLE
[bitnami/moodle] If external db is used, installation of charts fails because mariadb password is not set

### ISSUE THREAD

**Issue by petarGitNik** [bitnami/charts#3557]
**Which chart**:
chart: bitnami/moodle
version: 8.1.1

**Describe the bug**

If `mariadb.enabled: false` then chart installation fails with:

```
Error: template: moodle/templates/NOTES.txt:72:28: executing "moodle/templates/NOTES.txt" at <include "common.validations.values.mariadb.passwords" (dict "secretName" (include "moodle.mariadb.fullname" .) "context" $)>: error calling include: template: moodle/charts/common/templates/_validations.tpl:68:98: executing "common.validations.values.mariadb.passwords" at <.context.Values.mariadb.secret.requirePasswords>: nil pointer evaluating interface {}.requirePasswords
```

This seems to be because of `bitnami/common` subchart (it executes no matter if mariadb is disabled or not).

**To Reproduce**

0. Deploy external database with bitnami/mysql

```sh
helm upgrade mysql bitnami/mysql \
    --install --atomic --cleanup-on-fail \
    --namespace default --version 6.14.8 \
    --set db.user=moodle
    --set 'db.password=Password123!'
    --set db.name=moodle
```

1. Make values-override.yaml

```yaml
moodleUsername: admin                                                           
moodlePassword: Password123!                                                    
moodleEmail: admin@moodle.local                                                 
                                                                                
mariadb:
  enabled: false
```

2. Deploy chart with:

```sh
helm upgrade moodle bitnami/moodle \
    --install --atomic --cleanup-on-fail \
    --namespace default --version 8.1.1 \
    --values values-overrideyaml \
    --set externalDatabase.user=moodle \
    --set externalDatabase.password=Password123! \
    --set externalDatabase.database=moodle \
    --set externalDatabase.host=mysql.default.svc.cluster.local
```

**Expected behavior**

Installation should not fail.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
N/A

**Comment by petarGitNik** [comment]
I think this is the line in the common chart that is causing the issue: https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_validations.tpl#L68. I had to disable mariadb in the following way in the `values.yaml`:

```yaml
  mariadb:
    enabled: false
    secret:
      requirePasswords: false
```

`mariadb.secret.requiredPasswords` is not listed in bitnami/moodle readme nor it can be found in `values.yaml`, but it needs to be disabled if one is to use Moodle chart with external database.
