### ISSUE TITLE
Cannot implement TLS

### ISSUE THREAD

**Issue by khadka-prakash** [bitnami/charts#3594]
**Which chart**:
Thanos/2.3.2

**Describe the bug**
I am trying to implement TLS in thanos server using helmfile. I have the following in my helmfile

```
repositories:
- name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: thanos 
    namespace: monitoring 
    chart: bitnami/thanos 
    version: 2.3.2
    set:
    - name: "querier.grpcTLS.server.secure"
      value: true
    - name: "querier.grpcTLS.server.cert"
      value: "./thanos/ssl/cert.crt" 
    - name: "querier.grpcTLS.server.key"
      value: "./thanos/ssl/cert.key"
    - name: "querier.grpcTLS.client.secure"
      value: true
    - name: "querier.grpcTLS.client.cert"
      value: "./thanos/ssl/cert.crt"
    - name: "querier.grpcTLS.client.key"
      value: "./thanos/ssl/cert.key"
    values:
    - "./thanos/values.yaml"
```
When I run `helmfile sync` I am getting the following error:

```
ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: UPGRADE FAILED: template: thanos/templates/querier/tls-server-secret.yaml:12:50: executing "thanos/templates/querier/tls-server-secret.yaml" at <b64enc>: invalid value; expected string

COMBINED OUTPUT:
  Error: UPGRADE FAILED: template: thanos/templates/querier/tls-server-secret.yaml:12:50: executing "thanos/templates/querier/tls-server-secret.yaml" at <b64enc>: invalid value; expected string
```

**Expected behavior**
Thanos should have been configured with TLS

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.0-rc.2", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.2", GitCommit:"fb7add51f767aae42655d39972210dc1c5dbd4b3", GitTreeState:"clean", BuildDate:"2020-06-01T22:20:10Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```
