### ISSUE TITLE
transport: received the unexpected content-type \"text/html\"" 

### ISSUE THREAD

**Issue by khadka-prakash** [bitnami/charts#3606]
**Which chart**:
Thanos/2.3.2

**Describe the bug**
I have used TLS to communicate between thanos server and sidecars. I have set grpcTLS client to true and have setup certificates in values.yaml. 

I have used ingress-nginx in each cluster where I have installed thanos as sidecar. The ingress looks like following:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx          
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "default/thanos-ca-secret"
  name: thanos-ingress
  namespace: default
spec:
  rules:
  - host: sidecar-domain.com
    http:
      paths: 
      - path: /
        backend:
          serviceName: prometheus-operator-prometheus-thanos
          servicePort: grpc 
  tls:
  - hosts:
    - sidecar-domain.com
    secretName: thanos-ingress-secret
```
When I set ` nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"` then I get the following error in the thanos server querier pod:

```
level=warn ts=2020-09-04T11:23:37.374917053Z caller=storeset.go:487 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from sidecar-domain.com:443: rpc error: code = Internal desc = Bad Request: HTTP status code 400; transport: received the unexpected content-type \"text/html\"" address=sidecar-domain.com:443
```

But if I set `nginx.ingress.kubernetes.io/auth-tls-verify-client: "off"` in thanos sidecar ingress-nginx then it works but in querier dashboard I do not see `ruler` and `store` anymore. Only the sidecar shows up. In querier at this point shows the following error:

``` 
level=warn ts=2020-09-04T12:06:35.943778174Z caller=storeset.go:487 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from 10.82.15.15:10901: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: authentication handshake failed: tls: first record does not look like a TLS handshake\"" address=10.82.15.15:10901
level=warn ts=2020-09-04T12:06:35.94419347Z caller=storeset.go:487 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from prometheus-operator-prometheus-thanos.default.svc.cluster.local:10901: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: authentication handshake failed: tls: first record does not look like a TLS handshake\"" address=prometheus-operator-prometheus-thanos.default.svc.cluster.local:10901
level=warn ts=2020-09-04T12:06:35.944370406Z caller=storeset.go:487 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from 10.82.2.43:10901: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: authentication handshake failed: tls: first record does not look like a TLS handshake\"" address=10.82.2.43:10901
```

I think this is because it is communicating in Plain text. Also, I would like to add, the thanos sidecar domain `sidecar-domain.com` shows 502 bad gateway but in ingress pod log I can see the valid request:

```
10.244.1.43 - - [04/Sep/2020:11:54:00 +0000] "POST /thanos.Store/Info HTTP/2.0" 200 325 "-" "grpc-go/1.29.1" 20 0.002 [default-prometheus-operator-prometheus-thanos-grpc] [] 10.244.1.59:10901 367 0.000 200 e23a27f264d0a87e67bddb83031a8b3b
```

What am I missing? How do  I configure  TLS correctly?

**To Reproduce**
Try to configure Thanos with TLS enabled.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.0-rc.2", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.2", GitCommit:"fb7add51f767aae42655d39972210dc1c5dbd4b3", GitTreeState:"clean", BuildDate:"2020-06-01T22:20:10Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I have followed [this](https://docs.bitnami.com/tutorials/create-multi-cluster-monitoring-dashboard-thanos-grafana-prometheus/) documentation

**Comment by khadka-prakash** [comment]
After a few research, I came to know that the ca.crt was wrong. I have used cert-manager to issue letsencrypt certificate. I am now using ca certificate from https://curl.haxx.se/ca/cacert.pem. I then created the secret with the following commands:

```
kubectl create secret tls thanos-ingress-secret --key ./cert.key --cert ./cert.crt
kubectl create secret generic thanos-ca-secret --from-file=ca.crt=./cacert.pem
```

The above commands are taken from [https://itnext.io/monitoring-kubernetes-workloads-with-prometheus-and-thanos-4ddb394b32c](https://itnext.io/monitoring-kubernetes-workloads-with-prometheus-and-thanos-4ddb394b32c)

After that, I applied the following ingress

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx          
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "default/thanos-ca-secret"
  name: thanos-ingress
  namespace: default
spec:
  rules:
  - host: yourhostname.com
    http:
      paths: 
      - path: /
        backend:
          serviceName: prometheus-operator-prometheus-thanos
          servicePort: grpc 
  tls:
  - hosts:
    - yourhostname.com
    secretName: thanos-ingress-secret
```

It now works as expected. I will leave this issue as it is incase if someone like to add something.
