### ISSUE TITLE
[bitnami/moodle] Unable to set hosts & path

### ISSUE THREAD

**Issue by benjaminwinokur** [bitnami/charts#3617]
**Which chart**:
bitnami/moodle 8.1.1

**Describe the bug**
I am unable to set hosts[0].name and hosts[0].path 

**To Reproduce**
1. Run the following 

```
helm install my-release --dry-run --debug \
--set ingress.enabled=True \
--set ingress.hostname=www.example.com \
--set ingress.hosts[0].name=www.example.com \
--set ingress.hosts[0].path=/* \
--set ingress.annotations."kubernetes\.io/ingress\.global-static-ip-name=global-static-ip" \
--set service.type=NodePort \
bitnami/moodle
```

> Error: YAML parse error on moodle/templates/ingress.yaml: error converting YAML to JSON: yaml: line 20: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 20: did not find expected key
YAML parse error on moodle/templates/ingress.yaml

**Expected behavior**
I would expect to be able to set the host name and the path to the domain name and the ingress path.

**Version of Helm and Kubernetes**:

- Output of `helm version`: v3.2.1

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
Thanks for creating this issue, I was able to reproduce it. In the same way, I just created a PR fixing the issue, it was just an indentation typo (see attached PR).

Once applied the fix and using your install command but with the `--dry-run` flag, this is the ingress template that it's going to use:
```yaml
# Source: moodle/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-release-moodle
  labels:
    app.kubernetes.io/name: moodle
    helm.sh/chart: moodle-8.1.2
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.global-static-ip-name: global-static-ip
spec:
  rules:
  - host: www.example.com
    http:
      paths:
        - path: /
          backend:
            serviceName: my-release-moodle
            servicePort: 80
  - host: www.example.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: my-release-moodle
          servicePort: http
```

Once merged the PR this issue is going to be automatically closed, but feel free to reopen it if needed. In the same way, please take into account that although the code is merged in GH, the new chart version may take some time to appear in the chart repository due to the internal test & release process we follow.
