### ISSUE TITLE
[bitnami/postgresql] helm dependency build failed when using helm2

### ISSUE THREAD

**Issue by skyrain** [bitnami/charts#3643]
**Which chart**:
bitnami/postgresql

**Describe the bug**
The readme says this chart supports to run `helm2`. However,

With `helm 2`
run 
```
helm dependency build
```

failed with 
```
error: requirements.lock is out of sync with requirements.yaml
```

This seems like due to we created `requirement.lock` file using `helm 3` instead `helm 2`.

In `helm 3`:

```
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 0.6.2
digest: sha256:f0418c48609cf84f6301bf0a66340d84ee66d24b8c29de42904ee92afddf4f33
generated: "2020-09-09T18:55:03.029607-07:00"
```

In `helm 2`:
```
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 0.x.x
digest: sha256:740783295d301fdd168fafdbaa760de27ab54b0ff36b513589a5a2515072b885
generated: "2020-09-09T18:59:06.80774-07:00"
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.10", GitCommit:"bceca24a91639f045f22ab0f41e47589a932cf5e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.10", GitCommit:"bceca24a91639f045f22ab0f41e47589a932cf5e", GitTreeState:"clean"}
```

- Output of `kubectl version`:

**Additional context**
Proposal solution, upgrade Chart.yaml `apiversion` to `v2`, but it will limited only helm3 users to use this chart.

This bug is blocking `argocd` from using this chart, as `argocd` is using `apiversion` to determine whether to use `helm2` or `helm3` to run `dependency build`.  

```
. Argo CD will use Helm 3 to render charts that use apiVersion: v2 in the Chart.yaml file. Helm 2 charts will continue to be rendered using the Helm 2 binary.
```
