### ISSUE TITLE
[Bitnami/kube-prometheus] Kube-State-Metrics pod in CrashLoopBackOff state

### ISSUE THREAD

**Issue by dbrennand** [bitnami/charts#3650]
**Which chart**:
[Bitnami/kube-prometheus] kube-prometheus-1.1.0   0.41.1

**Describe the bug**
kube-state-metrics container is in a CrashLoopBackOff state.

Potentially due to the following line in logs: `2020/09/10 15:08:40 listen tcp 0.0.0.0:8080: bind: address already in use`

**To Reproduce**
values.yaml file used:
```yaml
fullnameOverride: prometheus-operator
operator:
  logLevel: error
prometheus:
  retention: 30d
  logLevel: error
  replicaCount: 3
  scrapeInterval: 1m
  evaluationInterval: 1m
  thanos:
    create: true
    objectStorageConfig:
      secretName: thanos-objstore-config
      secretKey: thanos.yaml
  additionalScrapeConfigsExternal:
    enabled: true
    name: prometheus-operator-prometheus-scrape-config
    key: additional-scrape-configs.yaml
  # Required by Thanos
  disableCompaction: true
  persistence:
    enabled: true
    storageClass: managed-standard-expansion
    size: 100Gi
alertmanager:
  logLevel: error
  externalConfig: true
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: managed-standard-expansion
  configMaps:
    - alertmanager-email-template
```

Using Helm v3:
```
helm install prometheus-operator `
--values=.\prometheus-values.yaml `
--namespace monitoring `
bitnami/kube-prometheus
```
I also manually cloned the repo, changed directory into the kube-prometheus chart directory and ran `helm dependencies update`. Issue still persists. 

**Expected behavior**
The kube-state-metrics pod isn't in a CrashLoopBackOff state

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"60e16a24c034b4f3ebe621a802fee4c9a14e8caf", GitTreeState:"clean", BuildDate:"2020-08-13T21:59:38Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional Context**
I understand that replicating my exact setup will be challenging. But if anyone can reproduce this then I would appreciate the help.
