### ISSUE TITLE
[bitnami/jasper] Unable to add ojdbc6.jar to setup datasource connection for Oracle

### ISSUE THREAD

**Issue by seedarren** [bitnami/charts#3661]
I use helm chart to run jasper report and not able to add ojdbc6.jar to setup datasource connection for Oracle

`helm install jasperserver bitnami/jasperreports -f jasper-server-values.yaml`

The content of jasper-server-values.yaml as follow:
```
enabled: true
  image:
    tag: 7.8.0
  fullnameOverride: jasperreports
  jasperreportsUsername: jasperadmin
  jasperreportsPassword: jasperadmin
  mariadb:
    mariadbRootPassword: password
    volumePermissions:
      enabled: true
    master:
      persistence:
        storageClass: standard
        size: 3Gi
  persistence:
    storageClass: standard
    accessMode: ReadWriteOnce
    size: 3Gi
  service:
    type: NodePort
    # HTTP Port
    port: 7080
    nodePorts:
      http: 32395
```

![image](https://user-images.githubusercontent.com/32858519/92983946-2ee40f00-f4d9-11ea-941b-2fdb4069821d.png)
