### ISSUE TITLE
[bitnami/nginx] Letting hosts empty causes error (only using hostname)

### ISSUE THREAD

**Issue by aeimer** [bitnami/charts#3668]
**Which chart**:
The name (and version) of the affected chart

bitnami/nginx 6.2.1

**Describe the bug**

Install the chart with valuefile

```yaml
ingress:
  enabled: true
  hostname: &host example.com
  # hosts: [] # This seems to be a bug...
  annotations:
    kubernetes.io/ingress.class: main
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.example.com"
  tls:
    - hosts:
        - *host
      secretName: tls-secret-example
```

to get a 

`Error: template: nginx/templates/ingress.yaml:26:15: executing "nginx/templates/ingress.yaml" at <.name>: can't evaluate field name in type interface {}`

when commenting in the `ingress.hosts: []` the release works.

**To Reproduce**

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**
