### ISSUE TITLE
[bitnami/rabbitmq] `image.pullSecrets` doesn't seem to work, only `global.imagePullSecrets`

### ISSUE THREAD

**Issue by tschale** [bitnami/charts#3676]
**Which chart**:
bitnami/rabbitmq 7.5.7

**Describe the bug**
- usage of custom image registry
- setting of `image.pullSecrets`
- statefulset is rendered without `imagePullSecrets`
- statefulset is however rendered with `imagePullSecrets` when `global.imagePullSecrets` is set

**To Reproduce**
1. set custom registry
2. set `image.pullSecrets`

**Expected behavior**
`image.pullSecrets` should render the statefulsets `imagePullSecrets`

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}
```

- Output of `kubectl version`:

[not relevant, occurs with `helm template`]

**Additional context**
The helper is defined as follows:
![image](https://user-images.githubusercontent.com/5681839/93186565-1117e380-f73f-11ea-84fb-5cbc15cea52b.png)
Might it be problematic that I don't have `.Values.volumePermissions.image` set?

**Comment by carrodher** [comment]
There are several things and values that can be modified:

- `image.pullSecrets`, modify the pullSecret for the main RabbitMQ image
- `volumePermissions.image.pullSecrets`, modify the pullSecret for the volumePermissions secondary image used as initContainer, this container is not enabled by default. [Here](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#adjust-permissions-of-the-persistence-volume-mountpoint) you can find more info.
- `global.imagePullSecrets`, that will override the default parameters, even including dependencies.

Checking each of the options:

- `image.pullSecrets`
```console
$ helm template rabbitmq --set image.pullSecrets[0]=rabbitmqPullSecret bitnami/rabbitmq
```
```yaml
    spec:
      imagePullSecrets:
        - name: rabbitmqPullSecret
      serviceAccountName: rabbitmq
```

- `volumePermissions.image.pullSecrets`
```console
$ helm template rabbitmq1 --set volumePermissions.image.pullSecrets[0]=volumePullSecret bitnami/rabbitmq
```
```yaml
    spec:
      imagePullSecrets:
        - name: rabbitmqPullSecret
      serviceAccountName: rabbitmq1
      securityContext:
```

- Both
```console
$ helm template rabbitmq2 --set image.pullSecrets[0]=rabbitmqPullSecret --set volumePermissions.image.pullSecrets[0]=volumePullSecret bitnami/rabbitmq
```
```yaml
    spec:
      imagePullSecrets:
        - name: rabbitmqPullSecret
        - name: volumePullSecret
      serviceAccountName: rabbitmq2
```

- Setting more than one secret for one of the images
```console
helm template rabbitmq3 --set image.pullSecrets[0]=rabbitmqPullSecret --set image.pullSecrets[1]=anotherRabbitmqPullSecret --set volumePermissions.image.pullSecrets[0]=volumePullSecret bitnami/rabbitmq
```
```yaml
    spec:
      imagePullSecrets:
        - name: rabbitmqPullSecret
        - name: anotherRabbitmqPullSecret
        - name: volumePullSecret
      serviceAccountName: rabbitmq3
```

- Using only global
```console
$ helm template rabbitmq4 --set global.imagePullSecrets[0]=globalPullSecret bitnami/rabbitmq
```
```yaml
    spec:
      imagePullSecrets:
        - name: globalPullSecret
      serviceAccountName: rabbitmq4
```

- Using global plus some of the per-image ones:
```console
$ helm template rabbitmq5 --set global.imagePullSecrets[0]=globalPullSecret --set image.pullSecrets[0]=rabbitmqPullSecret bitnami/rabbitmq
```
```yaml
    spec:
      imagePullSecrets:
        - name: globalPullSecret
        - name: rabbitmqPullSecret
```

For me the different approaches produce a valid output, please, can you share with us your specific `helm install` command if you're setting the parameters via CLI or your `values.yaml` if you implemented your changes via file?

**Comment by tschale** [comment]
Thanks for your effort @carrodher! 

We use a values file with following section for rabbitmq:

```
rabbitmq:
  image:
    registry: path.to.custom.registry
    repository: image-repository
    pullSecrets:
      - customPullSecrets
```

Using this, the imagePullSecret is not rendered, however when specifying following (and excluding `rabbitmq.image.pullSecrets`) it will be rendered:

```
global:
  imagePullSecrets:
    - customPullSecrets
```

**Comment by carrodher** [comment]
The `image` block shouldn't be placed under a `rabbitmq` block, you should place it at top-level in your values file:
```yaml
image:
  registry: path.to.custom.registry
  repository: image-repository
  tag: latest
  pullSecrets:
    - customPullSecrets
```
with that change, this is the resulting _statefulset.yaml_:
```yaml
    spec:
      imagePullSecrets:
        - name: customPullSecrets
      serviceAccountName: rabbitmq
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      terminationGracePeriodSeconds: 10
      containers:
        - name: rabbitmq
          image: path.to.custom.registry/image-repository:latest
          imagePullPolicy: "IfNotPresent"
```
Please note that apart from moving the `image` block to the top level, I also added the `tag` parameter, but the rest is the same code block you're using

**Comment by tschale** [comment]
I should have written that we're using it as a dependency. In that project we have the .tgz checked in under `charts`. In that case the values should be under a rabbitmq block, or shouldn't they?

**Comment by carrodher** [comment]
Yes, if you're using it as a subchart it is fine adding it under `rabbitmq`. Having said this, it should work setting it as you're doing. I tried your approach in the following way:

- Created the following _requirements.yaml_:
```yaml
 dependencies:
   - name: rabbitmq
     version: 7.x.x
     repository: https://charts.bitnami.com/bitnami
     condition: rabbitmq.enabled
     tags:
       - rabbitmq
```
- Then `helm dep update` checking that the chart is added into the `charts/` folder
- Add the following block in the _values.yaml_
```yaml
rabbitmq:
  enabled: true
  image:
    registry: path.to.custom.registry
    repository: image-repository
    tag: latest
    pullSecrets:
      - customPullSecrets
```
- `helm install --dry-run --debug mychart .`
```yaml
# Source: mychart/charts/rabbitmq/templates/statefulset.yaml
...
    spec:
      imagePullSecrets:
        - name: customPullSecrets
      ...
      containers:
        - name: rabbitmq
          image: path.to.custom.registry/image-repository:latest
          imagePullPolicy: "IfNotPresent"
```
according to that, the `imagePullSecrets` and the `image` is properly set in the yaml.

Are you doing something different? What is the result you obtain following the above steps?

**Comment by tschale** [comment]
The only difference would be that we don't list it as a dependency in `Chart.yaml`, but include the .tgz directly. But that shouldn't make a difference... If I `helm template` it, the `imagePullSecrets` is just missing in `statefulset.yaml`, the `image` however is set correctly...
Hmm, I'm not sure whether it's worth to investigate more, as it doesn't seem to be clearly reproducable. As we can work with the setting in `global` we're also not blocked. Should we just close this issue?

**Comment by carrodher** [comment]
It's really really weird. I just checked your approach, just including the rabbitmq `.tgz` in the _charts/_ folder, adding the above values to the _values.yaml_ and running the `helm install --dry-run` command, but the result is always the same.

What I noticed is that I am using the latest version every time
```console
$ helm repo update && helm search repo bitnami/rabbitmq
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈

NAME            	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/rabbitmq	7.6.6        	3.8.8      	Open source message broker software that implem...
```
while it seems you're using an older one (`7.5.7`), just in case there was a known issue solved in recent versions, can you try using the latest one?

**Comment by tschale** [comment]
Sorry for  not responding in the meantime, it has  slipped a little bit from my radar. I hope I'll get to it during this week.

**Comment by mes5k** [comment]
Seeing the exact same behavior on the latest release of the rabbitmq chart.

**Comment by mes5k** [comment]
So, I think the problem occurs when the rabbitmq chart gets nested within other charts.  In my situation I have a wrapper chart that has the rabbitmq chart as a dependency which includes all of our custom stuff (load definition, etc.).  I then have other charts that depend on my wrapper chart.  So my dependencies look like:

top_level_chart  ->  rabbitmq_wrapper -> rabbitmq

When I run `helm install --dry-run --debug ...` on top_level_chart I see in the generated values:

```
rabbitmq_wrapper:
  rabbitmq:
     image:
        pullSecrets:
           - mysecret
```

I don't understand helm value dependency composition well enough to be sure, but I don't think the `_helpers.tpl` function in the rabbitmq chart can see that value if it's only looking for `.Values.image`.  Not sure what the fix would be.
