### ISSUE TITLE
postInstallation error when setup phabricator with helm - 

### ISSUE THREAD

**Issue by pacobuenaparte** [bitnami/charts#3685]
**Which chart**:
bitnami/phabricator
App Version: 2020.31.0
Chart Version: 9.1.15

**Describe the bug**
Initialization process fails with the following error :

```
phabric INFO  Creating Database...
phabric INFO  Configuring Phabricator...
phabric INFO  Configuring SMTP...
Error executing 'postInstallation': [2020-09-16 09:01:24] EXCEPTION: (Exception) Database initialization on host "phabricator-polynom-mariadb:3306" applied no patches! at [<phabricator>/src/infrastructure/storage/management/workflow/PhabricatorStorageManagementWorkflow.php:1005]
arcanist(head=stable, ref.stable=ccd39feb6d3b), phabricator(head=stable, ref.stable=5e3768473711)
  #0 PhabricatorStorageManagementWorkflow::doUpgradeSchemata(array, NULL, boolean, boolean) called at [<phabricator>/src/infrastructure/storage/management/workflow/PhabricatorStorageManagementWorkflow.php:903]
  #1 PhabricatorStorageManagementWorkflow::upgradeSchemata(array, NULL, boolean, boolean) called at [<phabricator>/src/infrastructure/storage/management/workflow/PhabricatorStorageManagementUpgradeWorkflow.php:78]
  #2 PhabricatorStorageManagementUpgradeWorkflow::didExecute(PhutilArgumentParser) called at [<phabricator>/src/infrastructure/storage/management/workflow/PhabricatorStorageManagementWorkflow.php:107]
  #3 PhabricatorStorageManagementWorkflow::execute(PhutilArgumentParser) called at [<arcanist>/src/parser/argument/PhutilArgumentParser.php:492]
  #4 PhutilArgumentParser::parseWorkflowsFull(array) called at [<arcanist>/src/parser/argument/PhutilArgumentParser.php:377]
  #5 PhutilArgumentParser::parseWorkflows(array) called at [<phabricator>/scripts/sql/manage_storage.php:249]
```

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:18:22Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Values**:
```
image:
  registry: docker.io
  repository: bitnami/phabricator
  tag: 2020.31.0-debian-10-r20
  pullPolicy: IfNotPresent
phabricatorHost: phabricator.mycompany.com
phabricatorUsername: xxxxxxxxxxxx
phabricatorPassword: "xxxxxxxxxxxxxxxx"
phabricatorEmail: xxxxxxxxxxxxxxx@mycompany.com
phabricatorFirstName: XXXXXX
phabricatorLastName: XXXXX

smtpHost: "ssl://email-smtp.eu-central-1.amazonaws.com"
smtpPort: 465
smtpUser: xxxxxxxxxxxxxxxxxxxxxx
smtpPassword: "xxxxxxxxxxxxxxxxxxxxxx"
smtpProtocol: ssl

mariadb:
  enabled: true
  replication:
    enabled: true
  rootUser:
    password: XXXXXXXXXX

  master:
    ## Disable local_infile for MariaDB: https://secure.phabricator.com/T13238
    extraFlags: "--local-infile=0"
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 8Gi

service:
  type: NodePort
  externalTrafficPolicy: Cluster

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 20Gi

resources:
  requests:
    memory: 512Mi
    cpu: 300m
```
