### ISSUE TITLE
[bitnami/rabbitmq] Error: UPGRADE FAILED: cannot patch "rabbitmq" with kind StatefulSet: StatefulSet.apps "rabbitmq" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

### ISSUE THREAD

**Issue by xlanor** [bitnami/charts#3723]
**Which chart**:
bitnami/rabbitmq (7.6.6)

**Describe the bug**

After installing the chart as per the README instructions, I'm trying to update some of the chart details, by overriding some of the values in a seperate yaml file, using the command
`helm upgrade -f values-update.yaml rabbitmq bitnami/rabbitmq`

**To Reproduce**
1. Install the helm chart as per README
2. create a new values yaml file
```
## RabbitMQ Authentication parameters
##
auth:
  ## RabbitMQ application username
  ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
  ##
  username: user

  ## RabbitMQ application password
  ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
  ##
  password: value
  # existingPasswordSecret: name-of-existing-secret

  ## Erlang cookie to determine whether different nodes are allowed to communicate with each other
  ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
  ##
  erlangCookie: some-value
  # existingErlangSecret: name-of-existing-secret

advancedConfiguration: |-

  ## Number of RabbitMQ replicas to deploy
  ##
  replicaCount: 3
```

3. Execute `helm upgrade -f values-update.yaml rabbitmq bitnami/rabbitmq`

This results in the following output
```
Error: UPGRADE FAILED: cannot patch "rabbitmq" with kind StatefulSet: StatefulSet.apps "rabbitmq" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```
**Expected behavior**
The values should be updated

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
