### ISSUE TITLE
READONLY error while performing write operation from remote redis-cli 

### ISSUE THREAD

**Issue by jhoomsharabi** [bitnami/charts#3745]
**Which chart**:
Redis Chart Version 9.5.4

**Describe the bug**
HA setup of redis sentinel giving error of Unable to write against readonly replica when try to write from remote redis cli 

**To Reproduce**
I am setting Redis Sentinel HA setup from Bitnami redis helm chart, redis sentinel get deployed without any issue and I am able to perform basic commands of both sentinel and redis on my k8s cluster where 
my redis sentinel is deployed, here I expose the redis-headless service so that I can connect redis remotly and perform all the operations, I am able to connect redis server from remote redis-cli (remote m/c)
```
~]# redis-cli -h <host_name> -p 6379
```
when I try to insert some data using below commands, I get READONLY error
```
<host_name>:6379> MSET kill till
(error) READONLY You can't write against a read only replica.
```
I am exposing redis service like this:
```
kubectl expose service redis-headless -n namespace --port=6379 --target-port=6379 --name=redis-external-svc --external-ip=10.132.135.189
```

The above issue is not cosistent sometimes it works but mostly it doesn't work.

Tried to debug the issue and found that, when you say Sentinel enabled "true" it creates svc with:
```
Selector:          app=redis,release=redis
```
so this gives me feeling that as its role is not master so externally it tries to connect sometimes to readonly slave and sometimes to writable master, maybe the redis service should have 
```
Selector:          role=master
```

**Expected behavior**
When I connect HA redis from remote redis-cli, always I should be able perform all kinds of operations for Redis master 

**Version of Helm and Kubernetes**:
 
- Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:17:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
If I edit the exposed service like this:
```
~]# kubectl edit svc redis-external-svc -n namespace
```
and update "ports:"
```yaml
ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: redis-sentinel
    port: 26379
    protocol: TCP
    targetPort: redis-sentinel
```
than I am able to perform the write operations without any issue.

**Comment by jhoomsharabi** [comment]
With more debugging into the issue what I found is if I expose k8s service like this:

~]# kubectl expose service redis-headless -n namespace --name=redis-external-svc --external-ip=10.132.135.189

i.e. by removing "--port" and "--target-port=" 
than it works

**Comment by miguelaeh** [comment]
Hi @jhoomsharabi ,
The issue here seems to be that the service redirects the traffic to the pods without having in mind which one is the master. Since the Redis replicas are read-only you cannot perform write operations into them. That's why it is failing sometimes only, because whe your request is passed to the master it works, and when it is passed to the slaves it doesn't work.
Try to expose the redis-master-svc and it should work all the times. https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/redis-master-svc.yaml

**Comment by jhoomsharabi** [comment]
Hi @miguelaeh ,
Thanks for a quick reply, this is HA sentinel setup and trying to expose the service to perform redis master write operations remotely.
If I expose redis-master-svc and if master goes down and new master is assigned so will this exposed service will work as it is or I will have to again come back delete the exposed service and recreate it again against redis-master-svc

**Comment by miguelaeh** [comment]
Hi @jhoomsharabi ,
I am sorry for my confusion. If you are using Redis with sentinel the service used should be `redis-with-sentinel-svc`.
Now, what happens here is, that service will return the master ip from inside the k8s cluster, that will not be aailable from outside. We need to implement here something like we are doing for `redis-cluster` where we create a service per pod to expose it to outside of the k8s custer.
Thank you for the feed back, we will add that feature, nevertheless I cannot provide an estimated date for that.
Regards.

**Comment by jhoomsharabi** [comment]
Hi @miguelaeh ,
Thanks for taking up this feature/task request, just for information putting down the workaround I tried.

Redis Sentinel HA deployment already creates svc's "redis" and "redis-headless" so there is no difference in creating a separate new svc from ```redis-with-sentinel-svc``` as the content of "redis" and "redis-headless"  is same as that of redis-with-sentinel-svc.

So I created a "redis-with-sentinel-svc-updated.yaml" with following content:

```
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-master
  labels:
    app: redis
    chart: redis-9.5.4
    release: redis
    heritage: Helm
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  - name: redis-sentinel
    port: 26379
    targetPort: redis-sentinel
  selector:
    app: redis
    release: redis
    role: master
```
```
s]# kubectl apply -f redis-with-sentinel-svc.yaml
```
The above created svc is really not good idea, it will work for sometime but will not be able to handle the failover situation due to introduction of "role: master".
When master goes down and a new master is selected I will not able to connect redis-master from remote redis-cli.

**Comment by juan131** [comment]
Instead of doing so, I'd create a service per pod:

- Service0:

```
apiVersion: v1
kind: Service
metadata:
  name: redis-1
  labels:
    app: redis
    release: redis
    pod: redis-master-0
spec:
  type: NodePort
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  - name: redis-sentinel
    port: 26379
    targetPort: redis-sentinel
  selector:
    app: redis
    release: redis
    statefulset.kubernetes.io/pod-name: redis-master-0
```

- Service1:

```
apiVersion: v1
kind: Service
metadata:
  name: redis-1
  labels:
    app: redis
    release: redis
    pod: redis-slave-0
spec:
  type: NodePort
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  - name: redis-sentinel
    port: 26379
    targetPort: redis-sentinel
  selector:
    app: redis
    release: redis
    statefulset.kubernetes.io/pod-name: redis-slave-0
```

- Service2:

```
apiVersion: v1
kind: Service
metadata:
  name: redis-2
  labels:
    app: redis
    release: redis
    pod: redis-slave-1
spec:
  type: NodePort
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  - name: redis-sentinel
    port: 26379
    targetPort: redis-sentinel
  selector:
    app: redis
    release: redis
    statefulset.kubernetes.io/pod-name: redis-slave-1
```

So.. now you can access each pod individually outside the cluster. The only missing part is configuring your Redis client with the list of `IPs:Port` to be used to access each Redis member, and have a mechanisms to detect which of them is taking the "master" role at every moment.
