### ISSUE TITLE
[bitnami/kafka] ssl.client.auth is set to "required" when it should be "none"

### ISSUE THREAD

**Issue by ChangSurrey** [bitnami/charts#3755]
**Which chart**:
kafka v11.8.5

**Describe the bug**
When using `tls` client authentication protocol, `ssl.client.auth` should not be needed as it is required by `mtls` protocol only according to the comments in `values.yaml`. 

However, after deploying it, `ssl.client.auth` is set to `required` in `server.properties`. 

**To Reproduce**
I'm using the following custom values file:
```
zookeeper:
  enabled: true

externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true

  service:
    type: LoadBalancer
    port: 9094

deleteTopicEnable: true

rbac:
  create: true

auth:
  clientProtocol: tls
  interBrokerProtocol: plaintext
  jksSecret: kafka-tls-secret
  tlsEndpointIdentificationAlgorithm: ""
```

**Expected behavior**
`ssl.client.auth` should not be set, or should be set to `none`.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:13:57Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-065dce", GitCommit:"065dcecfcd2a91bd68a17ee0b5e895088430bd05", GitTreeState:"clean", BuildDate:"2020-07-16T01:44:47Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```
