### ISSUE TITLE
[bitnami/fluentd] add RPC for dynamic configmap/secret change

### ISSUE THREAD

**Issue by lukasmrtvy** [bitnami/charts#3763]
**Which chart**:
FluentD

**Is your feature request related to a problem? Please describe.**
FluentD is not reloaded when secret(TLS certificate)/configmap is changed. ( .. it must be reloaded via kubectl rollout restart )

**Describe the solution you'd like**
Would be nice to have enabled RPC https://docs.fluentd.org/deployment/rpc#configuration and have some configmap/secret reloader as a sidcar to FluentD.

**Describe alternatives you've considered**
Similar projects that are using rpc for reloading:
- https://github.com/vmware/kube-fluentd-operator/blob/master/config-reloader/fluentd/reloader.go#L31
- https://github.com/banzaicloud/logging-operator/blob/master/pkg/resources/fluentd/statefulset.go#L166

**Additional context**
Guys? Is possible create image/helm chart also for FluentBit ?

Thanks

**Comment by FraPazGal** [comment]
Hello @lukasmrtvy,

Thanks for your input! I have created an internal task related to this and the team will give it a look, but I'm unable to give you an ETA.

Regarding fluentbit, I'm sorry to say that there is no planned support for it at the moment.

**Comment by lukasmrtvy** [comment]
@FraPazGal what is also important... one should be able to specify fluentd config via helm chart directly = change will reload deployment ( if it is converted to configmap, thats not same as auto config reload via /api/config.reload endpoint ) 
For example:
https://github.com/helm/charts/blob/master/stable/fluent-bit/values.yaml#L181

**Comment by FraPazGal** [comment]
Hello @lukasmrtvy,

Thanks for the additional info! It will help our team once this task is assigned to someone.

**Comment by FraPazGal** [comment]
In the meantime, please feel free to create a PR implementing the changes. It would be a big help to have it implemented as soon as possible and we would be happy to review!

**Comment by davidkarlsen** [comment]
Related: https://github.com/helm/charts/issues/21235#issuecomment-710120813

**Comment by lukasmrtvy** [comment]
@FraPazGal any progress on this ?

fluentd-config:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluentd.conf: |
    <system>
      rpc_endpoint 127.0.0.1:24444
    </system>
    ...
```

values.yaml:
```
aggregator:
  configMap: fluentd-config
  sidecars:
    - name: watch
      image: weaveworks/watch:master-5b2a6e5
      imagePullPolicy: IfNotPresent
      args: ["-v", "-t", "-p=/opt/bitnami/fluentd/conf/", "curl", "-X", "GET", "--fail", "-o", "-", "-sS", "http://127.0.0.1:24444/api/config.reload"]
      volumeMounts:
      - name: fluentd-config
        mountPath: /opt/bitnami/fluentd/conf  
```
is working for me. Is there any chance for adpoting this mechanism ? Thanks
