### ISSUE TITLE
Error installing new version 12.7.0

### ISSUE THREAD

**Issue by digiserg** [bitnami/charts#3767]
**Which chart**:
elasticsearch 12.7.0

**Describe the bug**
On upgrading from 12.6.4 I get:

`Error: template: elasticsearch/templates/cronjob.yaml:70:29: executing "elasticsearch/templates/cronjob.yaml" at <include "common.affinities.pods" (dict "type" .Values.curator.podAffinityPreset "component" "curator" "context" $)>: error calling include: template: elasticsearch/charts/common/templates/_affinities.tpl:89:9: executing "common.affinities.pods" at <eq .type "soft">: error calling eq: invalid type for comparison
`
**To Reproduce**
I use helmfile and this is my config:

```yaml
  - name: elastic
    chart: "bitnami/elasticsearch"
    wait: true
    values:
      - fullnameOverride: axon-elastic
      - imageTag: "7.8.0"
      - data:
          replicas: 1
          persistence:
            size: 1Gi
            enabled: true
            accessModes: [ "ReadWriteOnce" ]
      - curator:
          enabled: true
          replicas: 1
      - master:
          replicas: 1
          persistence:
            size: 1Gi
            enabled: true
            accessModes: [ "ReadWriteOnce" ]
```

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
v3.3.0-rc.1
```

- Output of `kubectl version`:

```
Major:"1", Minor:"18", GitVersion:"v1.18.6"
```

**Additional context**
