### ISSUE TITLE
[bitnami/ghost] upgrade does not remove previous pod

### ISSUE THREAD

**Issue by erictse** [bitnami/charts#3769]
**Which chart**:
bitnami/ghost
3.33.0-debian-10-r6

**Describe the bug**
When trying to use `helm upgrade` for bitnami/ghost, a new pod runs, but the old deployment remains, preventing the new pod from obtaining resources to start.

**To Reproduce**
1. `helm install blog bitnami/ghost`
2. `helm upgrade blog bitnami/ghost --set ghostBlogTitle=foo`
3. `kubectl get pods`
```
NAME                                      READY   STATUS      RESTARTS   AGE
blog-ghost-865fb8cfb4-5rvhw               0/1     Init:0/1    0          4m41s
blog-ghost-9d4d9c658-cc729                0/1     Running     0          2m16s
```

**Expected behavior**
The old pod should terminate and the new pod should be `Running`.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-dispatcher", GitCommit:"fd22db44e150011eccc8729db223945384460143", GitTreeState:"clean", BuildDate:"2020-07-24T07:48:37Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by erictse** [comment]
By the way, it still doesn't work when using an external MariaDB instance, but it seems to work correctly if I don't use persistent volumes for the app. Maybe it's a timing issue.

**Comment by juan131** [comment]
Hi @erictse 

Are you using local persisten volumes? It looks like that's a problem due to the new pod being scheduled on a different node.

K8s is trying to mount the existing PV (the one used in the old pod) in the new one. However, it's unable to do so since it's a local volume and it belongs to a different node.

You have two alternatives here:

- Option A) Do not use local PVs
- Option B) Set the `affinity` property in your **values.yaml** to ensure both pods are scheduled in the same node. For instance:

```yaml
affinity:
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
      matchLabels:
        app.kubernetes.io/name: ghost
        app.kubernetes.io/instance: ghost
      namespaces:
      - default
      topologyKey: kubernetes.io/hostname
```
