### ISSUE TITLE
[bitnami/kafka] Is possible to configure the Kafka using AWS ALB ingress?

### ISSUE THREAD

**Issue by thiagoananias** [bitnami/charts#3792]
kafka:

I've managed to create the Kafka on Kubernetes using the commands

helm install INSTALLATION_NAME bitnami/kafka --set serviceAccount.create=true,rbac.create=true,replicaCount=2,externalAccess.enabled=true,externalAccess.service.type=NodePort,externalAccess.autoDiscovery.enabled=true,auth.clientProtocol=sasl,auth.jaas.clientUsers=user,auth.jaas.clientPasswords=pass

I'am installing it on AWS EKS and i would like to configure an the ALB Controller to have an Ingress with a pretty URL:

Here is my ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/listen-ports:  '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:sa-east-1:NUMBER:certificate/NUMBER
    external-dns.alpha.kubernetes.io/hostname: MYHOST.COM
spec:
  rules:
    - host: MYHOST.COM
      http:
        paths:
          - path: /*
            backend:
              serviceName: myservice
              servicePort: 9094
```

It seems to be all set.. but when I try to connect a producer it does not work. The POD seems to receive the commutication but it gives this error:
 
`WARN [SocketServer brokerId=0] Unexpected error from /192.168.73.111; closing connection (org.apache.kafka.common.network.Selector) org.apache.kafka.common.network.InvalidReceiveException: Invalid receive
`
i've found this post that the problem may be that the communication is using the http protocol
https://groups.google.com/g/confluent-platform/c/UXgdB1A2fk0

Is possible to configure using the aws alb ingress?
