### ISSUE TITLE
[bitnami/redis-cluster] redis.extraEnvVars leads to invalid templates

### ISSUE THREAD

**Issue by razzu** [bitnami/charts#3845]
Hi,

I ran into an issue when trying to use the `redis.extraEnvVars` parameter.

I get the following error when trying to deploy/upgrade the Redis cluster:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[1]): unknown field "value" in io.k8s.api.core.v1.Container
helm.go:94: [debug] error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[1]): unknown field "value" in io.k8s.api.core.v1.Container
```

For a minimal reproduction of this, consider a `redis-cluster.yml` values file with the following contents:
```
extraEnvVars:
  - name: POD_UID
    valueFrom:
      fieldRef:
        fieldPath: metadata.uid
```

And the following installation command:
```
helm install --timeout 600s redis-cluster bitnami/redis-cluster
        --values redis-cluster.yml
```

I've traced this to a rendering issue, where the contents of the `redis.extraEnvVars` parameter are not indented sufficiently.
Running the following command:
```
helm template redis-cluster bitnami/redis-cluster --values redis-cluster.yml
```
The rendered template looks like:
```
[...]
          env:
            - name: REDIS_NODES
              value: "redis-cluster-0.redis-cluster-headless redis-cluster-1.redis-cluster-headless redis-cluster-2.redis-cluster-headless redis-cluster-3.redis-cluster-headless redis-cluster-4.redis-cluster-headless redis-cluster-5.redis-cluster-headless redis-cluster-6.redis-cluster-headless redis-cluster-7.redis-cluster-headless "
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: REDIS_AOF_ENABLED
              value: "yes"
            - name: REDIS_TLS_ENABLED
              value: "no"
            - name: REDIS_PORT
              value: "6379"
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
[...]
```

It's visible that the added environment variables are indented too far to the left (1 level behind the parent `env` key).
