### ISSUE TITLE
[bitnami/redis] volume-permissions conteiner not start 

### ISSUE THREAD

**Issue by serg-bs** [bitnami/charts#3848]
**Which chart**:
redis

**Describe the bug**
I want deploy redis to bare metal.
This subchart will be deployed simultaneously with persistentvolume.
I want redis chart automatically change permission like mongo or postgres chart. 

Main problem is 

```
{{- $needsVolumePermissions := and .Values.volumePermissions.enabled (and ( and .Values.master.persistence.enabled (not .Values.persistence.existingClaim) ) .Values.securityContext.enabled) }}
```
suggest remove **not .Values.persistence.existingClaim**

**Step to reproduse** 
1. Deploy pv and pvc with manual storage class
2. Deploy chart on bare metal with
```
redis:
  usePassword: false
  fullnameOverride: redis-rsmp
  volumePermissions:
    enabled: true
  persistence:
    existingClaim: redis-0
```
3. initContainers volume-permissions not started
