### ISSUE TITLE
Influxdb livenessProbe  & readiness check broken

### ISSUE THREAD

**Issue by YunaBraska** [bitnami/charts#3868]
**Which chart**:
Bitnami InfluxDB 0.6.7

**Describe the bug**
Error: `Readiness probe failed: timeout: can't execute '29s': No such file or directory`
`deployment-standalone.yaml` and `statefulset-high-availability.yaml` the `readinessProbe` and `livenessProbe` are using the `timeout` command wrong instead of `timeout 29s` should be `timeout -t 29`
Output of `timeout --help` on the pod:

```
Usage: timeout [-t SECS] [-s SIG] PROG ARGS)
```
After fixing the timeout, the checks are failing due wrong influx db. I couldn't get why :( 
```
ERR: authorization failed
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
```

**To Reproduce**
1) Use the Influxdb of the bitnami chart
2) `helm template` &&` kubectl apply`

**Expected behavior**
livenessProbe & readinessProbe running without errors so the pod don't restart

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
2.16.5
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:08:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
-

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. I was unable to reproduce the issue. I tried installing the latest version of the chart 0.6.8 with this command

```
helm install influ bitnami/influxdb
```

And found no issues 

```
 1 ❯ kubectl get pods
NAME                             READY   STATUS    RESTARTS   AGE
influ-influxdb-67c8d795d-d8kmf   1/1     Running   0          3m34s
```

Also, I entered the container and didn't see an error in the timeout command

```
I have no name!@influ-influxdb-67c8d795d-d8kmf:/$ timeout --help
Usage: timeout [OPTION] DURATION COMMAND [ARG]...
  or:  timeout [OPTION]
Start COMMAND, and kill it if still running after DURATION.

Mandatory arguments to long options are mandatory for short options too.
      --preserve-status
```

Did you do any changes in the values.yaml file?

**Comment by YunaBraska** [comment]
My configuration is like this but you will run in the situation with this ticket #3863 (Pull Request: https://github.com/bitnami/charts/pull/3903) before reaching the mentioned issue: 

```
influxdb:
  enabled: false
  image:
    repository: influxdb
    tag: 1.8.0-alpine
  resources:
    limits:
      cpu: 1
      memory: 2000Mi
    requests:
      cpu: 1
      memory: 2000Mi
  volumePermissions:
    enabled: true
    securityContext:
      runAsUser: 0
      fsGroup: 0
  influxdb:
    securityContext:
      fsGroup: 0
      runAsUser: 0
      enabled: true
```
