### ISSUE TITLE
[wordpress] Support Certificate in Ingress

### ISSUE THREAD

**Issue by emreberber** [bitnami/charts#3882]
**Which chart**:
Chart : wordpress

**Additional context**
Hi,

I want publish wordpess with https. I use rancher and cert-manager.

I create Certificate with cert-manager.io, for example (my domain is test-tk8s.cloud) : 
```
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: app-certificate
spec:
  dnsNames:
    - test.tk8s.cloud
  secretName: app-certificate
  issuerRef:
    name: test-k8s-cloud-issuer
    kind: ClusterIssuer
```
If i use this certificate in ingress i should do like this : 
```
...
spec:
  tls:
    - secretName: app-certificate
...
```

How can i use this format in Wordpress helm chart with values.yaml ? I can't see Certificate yaml file .

Thanks

**Comment by chrisDeFouRire** [comment]
Here's what has worked for me:

```
ingress:
  enabled: true
  certManager: true
  hostname: "www.website.com"
  tls: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt"
```

I didn't use an explicit Certificate though, it's a letsencrypt auto-issued cert...

**Comment by FraPazGal** [comment]
Hi @emreberber!

Thanks a lot @chrisDeFouRire for helping out! Like he commented, you can assign the necessary values using the `ingress` options. If I'm not mistaken, it should be fairly similar to the provided example, even though yours is not an auto-issued certificate. 

Although there is not a `certificate.yaml` file, you can supply it as a secret using `ingress.secrets`. For a detailed explanation, please visit [this section](https://github.com/bitnami/charts/tree/master/bitnami/wordpress#tls-secrets) of our README.

**Comment by emreberber** [comment]
Thanks @chrisDeFouRire , @FraPazGal 

I add these,

```
ingress:
  enabled: true

  certManager: true

  hostname: wp-dev.tk8s.gozen.cloud

  annotations:
    cert-manager.io/cluster-issuer: "doge-k8s-gozen-cloud-issuer"
    kubernetes.io/ingress.class: "nginx"
  tls: false
  extraTls:
  - hosts:
      - wp-dev.tk8s.gozen.cloud
    secretName: wordpress.local-tls
```

And it create cretificate. My problem is solved.

https://docs.bitnami.com/tutorials/secure-wordpress-kubernetes-managed-database-ssl-upgrades/#secure-traffic-with-tls-and-lets-encrypt-ssl-certificates
