### ISSUE TITLE
[bitnami/postgresql-ha] Collision for secret mount paths in pgpool

### ISSUE THREAD

**Issue by enote-kane** [bitnami/charts#3922]
**Which chart**:
postgresql-ha 3.8.0

**Describe the bug**
When enabling options `pgpool.usePasswordFile` and `postgresql.usePasswordFile`, the Helm chart tries to mount two separate secrets into the same path, resulting into the following error:
```
Release "mms" does not exist. Installing it now.
Error: Deployment.apps "mms-postgresql-ha-pgpool" is invalid: spec.template.spec.containers[0].volumeMounts[1].mountPath: Invalid value: "/opt/bitnami/pgpool/secrets/": must be unique
```

**To Reproduce**
1. Set value `postgresql.usePasswordFile` to `true`
2. Set value `pgpool.usePasswordFile` to `true`
3. Prepare a secret and specify its name in `postgresql.existingSecret` and `pgpool.existingSecret`
4. Try to install the Helm chart

**Expected behavior**
Secret is mounted once or separate mount paths are used.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by enote-kane** [comment]
The fix that I am using currently is to specify files + subPath explicitly in the `pgpool/deployment.yml` for `volumeMounts`:
```yaml
{{- if .Values.postgresql.usePasswordFile }}
- name: postgresql-password
  subPath: pgpool-password
  mountPath: /opt/bitnami/pgpool/secrets/pgpool-password
- name: postgresql-password
  subPath: pgpool-sr-check-password
  mountPath: /opt/bitnami/pgpool/secrets/pgpool-sr-check-password
{{- end }}
{{- if .Values.pgpool.usePasswordFile }}
- name: pgpool-password
  subPath: admin-password
  mountPath: /opt/bitnami/pgpool/secrets/admin-password
{{- end }}
```
