### ISSUE TITLE
[bitnami/mariadb] Service to access DB not created/available in env var, but previously was?

### ISSUE THREAD

**Issue by virgil9306** [bitnami/charts#3924]
**Which chart**:
`bitnami/mariadb` - this version: https://github.com/bitnami/charts/pull/3849

**Describe the bug**
Previously I could connect to MariaDB via the IP made available in the environment variable `{SVCNAME}_SERVICE_HOST`. Now, such a service is NOT created, and only `{SVCNAME}_PRIMARY_SERVICE_HOST`, `{SVCNAME}_SECONDARY_SERVICE_HOST` are available in environment variables.

Similar to this but for a different chart: https://github.com/bitnami/charts/issues/3830#issuecomment-701972854

**To Reproduce**
1. Deploy with:

```
helm upgrade --install {SVCNAME} \
    --values overrides.yaml \
    --namespace $1 \
    --set auth.username=$2 \
    --set auth.password=$3 \
    --set auth.rootPassword=$4 \
    --set auth.replicationPassword=$5 \
    --set auth.forcePassword='true' \
    bitnami/mariadb
```

where `overrides.yaml` is:

```
architecture: replication
metrics.enabled: true
db:
  name: strapi
primary: # master
  persistence:
    size: 5Gi
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi
secondary: # slave
  persistence:
    size: 5Gi
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi
```

**Expected behavior**
Previous version created a headless service and put the IP in environment variable for me. Also was using slave nodes.

If I can now use `{SVCNAME}_PRIMARY_SERVICE_HOST` then the docs should say. Is that the correct approach?

`helm get notes ...` just says:

```
2. To connect to primary service (read/write):

      mysql -h {svc}-primary.{namespace}.svc.cluster.local -uroot -p my_database

3. To connect to secondary service (read-only):

      mysql -h {svc}-secondary.{namespace}.svc.cluster.local -uroot -p my_database
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-07-04T15:01:15Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
