### ISSUE TITLE
[bitnami/elasticsearch] cluster won't start because of the lack of discovery settings (at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured)

### ISSUE THREAD

**Issue by polymorpher** [bitnami/charts#3938]
**Which chart**:
bitnami/elasticsearch:7.9.2

**Describe the bug**
Deploying using settings that assign AWS LoadBalancer IPs (see settings below) for coordinating nodes result in the following errors, causing nodes to repeatedly fail and restart. It's unclear how the recommended fix via discovery settings can be passed to the chart (reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/discovery-settings.html and https://discuss.elastic.co/t/problems-with-access-to-elasticsearch-form-outside-machine/172450/3). See log below.
Settings:
```
coordinating:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-xxx-123,eipalloc-xxx-456"
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    type: LoadBalancer
    externalTrafficPolicy: Local
    ports:
    - name: http
      port: 9200
      protocol: TCP
    - name: tcp
      port: 9300
      protocol: TCP
```

Error log.
```
{0.0.0.0:9300}" }
{"type": "server", "timestamp": "2020-10-07T18:44:04,107Z", "level": "INFO", "component": "o.e.b.BootstrapChecks", "cluster.name": "docker-cluster", "node.name": "es-elasticsearch-master-0", "message": "bound or publishing to a non-loopback address, enforcing bootstrap checks" }
ERROR: [1] bootstrap checks failed
[1]: the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured
ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/docker-cluster.log
```

**To Reproduce**
1. `helm install es bitnami/elasticsearch`
2. See error log in any node.

**Expected behavior**
Cluster up and running, error free.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:38Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
none
