### ISSUE TITLE
Spring Cloud Data Flow External Database Issues

### ISSUE THREAD

**Issue by tkvangorder** [bitnami/charts#3939]
Chart: bitnami/spring-cloud-dataflow, Version  0.7.4

I am trying to set the provided values such that I can use MS SQL Server as my database to host the task/job schemas.
I first tried using the externalDatabase.* properties but the formatting for the JDBC URL is not correct. For my experiment, I have just deployed an MSSQL Server into my cluster and I am using a service named "mssql-server".

```
externalDatabase:
  host: mssql-server
  port: 1433
  scheme: "sqlserver"
  driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  dataflow:
    user: dataflow
    password: "<mypassword>"
  skipper:
    user: dataflow
    password: "<mypassword>"
  hibernateDialect: "org.hibernate.dialect.SQLServer2012Dialect"

```

Helm correctly applies the chart to my cluster but once I hit the dataflow server, I see an error in the logs: 

```
Caused by: org.springframework.jdbc.support.MetaDataAccessException: Could not get Connection for extracting meta-data; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: The port number 1433/dataflow is not valid.
```

It feels like the provided properties for customization are geared towards mariadb and do not work when attempting to use MSSQL Server.

**Expected behavior**
Ideally, I would like to just specify the jdbc url via :  
```
externalDatabase:
  url: jdbc:sqlserver://mssql-server
.
.
.
```

In my second attempt to do this, I attempted to set the JDBC URL via an environment variable: 

```
server:
  extraEnvVars:
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:sqlserver://mssql-server"
  - name: SPRING_DATASOURCE_USERNAME
    value: "dataflow"
  - name: SPRING_DATASOURCE_PASSWORD
    value: "<my password>"
```

Unfortunately, this results in an error when I attempt to apply the chart: 

```
helm install my-release -f ./scdf-settings.yaml bitnami/spring-cloud-dataflow
Error: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.v1.EnvVar.Value: Name: ReadString: expects " or n, but found 0, error found in #10 byte of ...|,{"name":0,"value":"|..., bigger context ...|mposed-task-runner:2.6.2-debian-10-r13"},{"name":0,"value":"map[name:SPRING_DATASOURCE_URL value:jdb|...
```

I investigate the issue via `helm template -f ./scdf-settings.yaml bitnami/spring-cloud-dataflow` and it looks like environment variables are not being mapped correctly in the template output: 

```
            - name: SPRING_CLOUD_DATAFLOW_TASK_COMPOSED_TASK_RUNNER_URI
              value: 'docker://docker.io/bitnami/spring-cloud-dataflow-composed-task-runner:2.6.2-debian-10-r13'
            - name: 0
              value: "map[name:SPRING_DATASOURCE_URL value:jdbc:sqlserver://mssql-server]"
            - name: 1
              value: "map[name:SPRING_DATASOURCE_USERNAME value:dataflow]"
            - name: 2
              value: "map[name:SPRING_DATASOURCE_PASSWORD value:<my password>]"
```

I will explore using a config map next, but I thought I would report the experience so far. I feel like these would be relatively easy to fix, but I am just learning Kubernetes and Helm, so I am not quite comfortable providing a PR. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
