### ISSUE TITLE
 MinIO Helm Persistent Volume General

### ISSUE THREAD

**Issue by ptitpoulpe** [bitnami/charts#3945]
**Which chart**:
bitnami/minio 3.7.11

**Describe the bug**
I'm using bitnami/minio chart with skaffold, but I cannot find a way to have the PersistentVolume not deleted when skaffold shutdown. (It works well with bitnami/postgresql)

**To Reproduce**
Run skaffold dev with the following skaffold.yaml, add a file in Minio, shutdown skaffold, rerun skaffold and try to access file uploaded.
```yaml
apiVersion: skaffold/v2beta6
kind: Config
deploy:
  helm:
    releases:
    - name: minio
      chartPath: bitnami/minio
      remote: true
      version: 3.x.x
      wait: true
      setValues:
        accessKey.password: "deadbeef"
        secretKey.password: "badc0ffee"
        defaultBuckets: "irma;argo"
        volumePermissons.enabled: true
        persistence.enabled: true
        fullnameOverride: minio
```

**Expected behavior**
Having access to uploaded file.
