### ISSUE TITLE
[bitnami/harbor] chartmuseum is broken with default values

### ISSUE THREAD

**Issue by HaveFun83** [bitnami/charts#3952]
**Which chart**:
bitnami/harbor >= 7.4.0

**Describe the bug**
The chartmuseum within harbor is unable to serve charts when the default chart values are used.

**To Reproduce**
1. deploy harbor with chartmuseum enabled
2. On the UI goto repositroy > Helm Charts
3. Upload a Chart
4. Click on chart and get 
```
fail to get chart version: not found
```
on the UI and the following log in the chartmuseum pod:
```
2020-10-07T16:29:18.041Z        WARN    [858] Request served    {"path": "/https://core.harbor.lan/chartsRepo/public/charts/grafana-5.7.2.tgz", "comment": "", "latency": "58.128µs", "clientIP": "10.102.65.126", "method": "GET", "statusCode": 404, "reqID": "658ff2ff-745a-4357-95d4-2f9c0438d178"}
```

**Expected behavior**
The chart details should be served without an error

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
After setting the following custom values from upstream chart and flushing the redis cache.
Chartmuseum served the charts without any errors:
```
## Chartmuseum parameters
##
chartmuseum:
    chartRepoName: 'chartrepo'
    contextPath: ""
    indexLimit: 0
    maxStorageObjects: 0
    maxUploadSize: "20971520"
    chartPostFormFieldName: "chart"
    provPostFormFieldName: "prov"
```
upstream values can be found here:
https://github.com/goharbor/harbor-helm/blob/master/templates/chartmuseum/chartmuseum-cm.yaml

**Comment by dani8art** [comment]
Hi @HaveFun83 thank you for opening the issue,

Unfortunately, I was not able to reproduce the issue, did you use any other value or any useful info that I can use to reproduce it?

```
$ helm install harbor bitnami/harbor
```

```
$ export SERVICE_IP=$(kubectl get svc --namespace default harbor --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
$ echo "Harbor URL: http://$SERVICE_IP/"
```

![Screenshot 2020-10-15 at 15 33 00](https://user-images.githubusercontent.com/4376304/96135151-bd461900-0efb-11eb-8267-e0a94c3954f1.png)

**Comment by HaveFun83** [comment]
@dani8art thanks for locking into this. 
As we run harbor in HA mode we scaled all replicas to 2 pods and set the imageChartStorage to an s3 endpoint.
Additional we set the global externalURL and `absoluteUrl: true` within the chartmuseum values.

Can you check this with the specific chart version 7.4.0?

**Comment by dani8art** [comment]
Hi @HaveFun83 i'm still unable to reproduce it, could you share the exact values (removing sensible data) and the exact step you followed so we can try to reproduce it?
Thanks.

**Comment by HaveFun83** [comment]
here are the helm values we are still on chart version 7.4.0

```yaml
coreImage:
  registry: docker.io
  repository: bitnami/harbor-core
  tag: 2.0.2
portalImage:
  registry: docker.io
  repository: bitnami/harbor-portal
  tag: 2.0.2
jobserviceImage:
  registry: docker.io
  repository: bitnami/harbor-jobservice
  tag: 2.0.2
registryImage:
  registry: docker.io
  repository: bitnami/harbor-registry
  tag: 2.0.2
registryctlImage:
  registry: docker.io
  repository: bitnami/harbor-registryctl
  tag: 2.0.2
trivyImage:
  registry: docker.io
  repository: bitnami/harbor-adapter-trivy
  tag: 2.0.2
clairImage:
  registry: docker.io
  repository: bitnami/harbor-clair
  tag: 2.0.2
clairAdapterImage:
  registry: docker.io
  repository: bitnami/harbor-adapter-clair
  tag: 2.0.2
notaryServerImage:
  registry: docker.io
  repository: bitnami/harbor-notary-server
  tag: 2.0.2
notarySignerImage:
  registry: docker.io
  repository: bitnami/harbor-notary-signer
  tag: 2.0.2
chartMuseumImage:
  registry: docker.io
  repository: bitnami/chartmuseum
  tag: 0.12.0
nginxImage:
  registry: docker.io
  repository: bitnami/nginx
  tag: 1.19.1

service:
  tls:
    existingSecret: "core-harbor-ingress"
    notaryExistingSecret: "notary-harbor-ingress"

## Ingress parameters
ingress:
  enabled: true
  hosts:
    core: core.private.lan
    notary: notary.private.lan
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
    kubernetes.io/tls-acme: "true"
externalURL: https://core.private.lan

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      storageClass: rbd-hdd
      accessMode: ReadWriteOnce
      size: 5Gi
    jobservice:
      storageClass: rbd-hdd
      accessMode: ReadWriteOnce
      size: 1Gi
    chartmuseum:
      storageClass: rbd-hdd
      accessMode: ReadWriteOnce
      size: 5Gi
    trivy:
      storageClass: rbd-hdd
      accessMode: ReadWriteOnce
      size: 5Gi

  ## Define which storage backend is used for registry and chartmuseum to store
  ## images and charts
  imageChartStorage:
    disableredirect: true
    type: s3
    s3:
      region: us-west-1
      bucket: imagechartstore
      accesskey: xxx
      secretkey: vvv
      regionendpoint: http://s3.private.lan

logLevel: info

## The initial password of Harbor admin. Change it from portal after launching Harbor
harborAdminPassword: aaa

## Harbor nginx parameters
nginx:
  replicas: 2

## Harbor Portal parameters
portal:
  replicas: 2

## Harbor Core parameters
core:
  replicas: 2
  # The secret key used for encryption. Must be a string of 16 chars.
  secretKey: "bbb"

## Harbor Jobservice parameters
jobservice:
  # replicas >=2 need ReadWriteMany or S3 ObjectStore
  replicas: 2
  jobLogger: database

## Harbor registry parameters
registry:
  # replicas >=2 need ReadWriteMany or S3 ObjectStore
  replicas: 2

## Chartmuseum parameters
chartmuseum:
  # replicas >=2 need ReadWriteMany or S3 ObjectStore
  replicas: 2
  absoluteUrl: true
  chartRepoName: 'chartrepo'
  contextPath: ""
  indexLimit: 0
  maxStorageObjects: 0
  maxUploadSize: "20971520"
  chartPostFormFieldName: "chart"
  provPostFormFieldName: "prov"




## Clair parameters
clair:
  replicas: 2

## Trivy adapter parameters
trivy:
  replicas: 2

## Notary parameters
notary:
  enabled: false
  server:
    replicas: 2
  signer:
    replicas: 2

## Redis chart configuration
redis:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/redis
    tag: 6.0.7
  cluster:
    enabled: true
    slaveCount: 2
  clusterDomain: "cluster.local"
  usePassword: true
  password: "ccc"
  master:
    persistence:
      enabled: true
      storageClass: rbd-hdd
      accessModes:
      - ReadWriteOnce
      size: 8Gi
    disableCommands: []
  slave:
    persistence:
      enabled: true
      storageClass: rbd-hdd
      accessModes:
      - ReadWriteOnce
      size: 8Gi

  metrics:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/redis-exporter
      tag: 1.11.1
    serviceMonitor:
      enabled: true
      selector:
        prometheus/cluster: "true"

## PostgreSQL chart configuration
postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 11.9.0
  replication:
    enabled: true
    user: repl_user
    password: "xxxx"
    slaveReplicas: 2
  postgresqlUsername: postgres
  postgresqlPassword: "xxxx"
  postgresqlDatabase: postgres
  postgresqlExtendedConf:
    maxConnections: 1024
  initdbScripts:
    initial-notaryserver.sql: |
      CREATE DATABASE notaryserver;
      CREATE USER server;
      alter user server with encrypted password 'xxx';
      GRANT ALL PRIVILEGES ON DATABASE notaryserver TO server;
    initial-notarysigner.sql: |
      CREATE DATABASE notarysigner;
      CREATE USER signer;
      alter user signer with encrypted password 'xxx';
      GRANT ALL PRIVILEGES ON DATABASE notarysigner TO signer;
    initial-registry.sql: |
      CREATE DATABASE registry ENCODING 'UTF8';
      \c registry;
      CREATE TABLE schema_migrations(version bigint not null primary key, dirty boolean not null);
  persistence:
    enabled: true
    storageClass: rbd-hdd
    accessModes:
    - ReadWriteOnce
    size: 8Gi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        prometheus/cluster: "true"
    image:
      registry: docker.io
      repository: bitnami/postgres-exporter
      tag: 0.8.0

```

**Comment by dani8art** [comment]
Hi @HaveFun83 thanks for sharing, we will try to reproduce it taking this into account.

**Comment by dani8art** [comment]
Hi @HaveFun83 after some investigation we found something wire in your values

```yaml
## Chartmuseum parameters
chartmuseum:
  # replicas >=2 need ReadWriteMany or S3 ObjectStore
  replicas: 2
```

>   `# replicas >=2 need ReadWriteMany or S3 ObjectStore`

it seems like ReadWriteMany is required but I can see you are using ReadWriteOnce

```yaml
persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      storageClass: rbd-hdd
      accessMode: ReadWriteOnce
      size: 5Gi
    jobservice:
      storageClass: rbd-hdd
      accessMode: ReadWriteOnce
      size: 1Gi
    chartmuseum:
      storageClass: rbd-hdd
      accessMode: ReadWriteOnce
```

please, could you try using the proper access mode or using an S3 bucket instead?

**Comment by HaveFun83** [comment]
> Hi @HaveFun83 after some investigation we found something wire in your values
> 
> ```yaml
> ## Chartmuseum parameters
> chartmuseum:
>   # replicas >=2 need ReadWriteMany or S3 ObjectStore
>   replicas: 2
> ```
> 
> > `# replicas >=2 need ReadWriteMany or S3 ObjectStore`
> 
> it seems like ReadWriteMany is required but I can see you are using ReadWriteOnce
> 
> ```yaml
> persistence:
>   enabled: true
>   persistentVolumeClaim:
>     registry:
>       storageClass: rbd-hdd
>       accessMode: ReadWriteOnce
>       size: 5Gi
>     jobservice:
>       storageClass: rbd-hdd
>       accessMode: ReadWriteOnce
>       size: 1Gi
>     chartmuseum:
>       storageClass: rbd-hdd
>       accessMode: ReadWriteOnce
> ```
> 
> please, could you try using the proper access mode or using an S3 bucket instead?

The pv's are not created as we used an s3 bucket for imagechartstore:
```yaml
  imageChartStorage:
    disableredirect: true
    type: s3
    s3:
      region: us-west-1
      bucket: imagechartstore
      accesskey: xxx
      secretkey: vvv
      regionendpoint: http://s3.private.lan
```

**Comment by juan131** [comment]
Hi @HaveFun83 

Did you enable any of the rest of parameters to configure S3 as the image&chart storage? I mean, the ones below?

```yaml
persistence:
  ...
  imageChartStorage:
    ...
    s3:
      ...
      #encrypt: false
      #keyid: mykeyid
      #secure: true
      #skipverify: false
      #v4auth: true
      #chunksize: "5242880"
      #rootdirectory: /s3/object/name/prefix
      #storageclass: STANDARD
      #multipartcopychunksize: "33554432"
      #multipartcopymaxconcurrency: 100
      #multipartcopythresholdsize: "33554432"
```

Could you please share the logs of Chartmuseum containers?
