### ISSUE TITLE
[bitnami/postgresql-ha] Flaky unrecoverable startup/initialization failures

### ISSUE THREAD

**Issue by enote-kane** [bitnami/charts#3986]
**Which chart**:
bitnami/postgresql-ha version 4.0.0

**Describe the bug**
Setup or repmgr sometimes (but not always) fails resulting in endless `CrashLoopBackOff` of PostgreSQL pods.

**To Reproduce**
1. Install Helm chart

**Expected behavior**
A working cluster.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

At first startup of the primary PostgreSQL container, the following get's logged:
```
postgresql-repmgr 12:30:30.49 
postgresql-repmgr 12:30:30.49 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 12:30:30.49 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 12:30:30.49 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 12:30:30.50 
postgresql-repmgr 12:30:30.50 DEBUG ==> Configuring libnss_wrapper...
postgresql-repmgr 12:30:30.51 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 12:30:30.55 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 12:30:30.56 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 12:30:30.56 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 12:30:30.57 DEBUG ==> Checking node 'defaults-postgresql-ha-postgresql-0.defaults-postgresql-ha-postgresql-headless.pg-test.svc.cluster.local:5432'...
psql: error: could not connect to server: could not connect to server: Connection refused
        Is the server running on host "defaults-postgresql-ha-postgresql-0.defaults-postgresql-ha-postgresql-headless.pg-test.svc.cluster.local" (10.20.3.149) and accepting
        TCP/IP connections on port 5432?
postgresql-repmgr 12:30:30.58 DEBUG ==> Skipping: failed to get primary from the node 'defaults-postgresql-ha-postgresql-0.defaults-postgresql-ha-postgresql-headless.pg-test.svc.cluster.local:5432'!
postgresql-repmgr 12:30:30.59 DEBUG ==> Checking node 'defaults-postgresql-ha-postgresql-1.defaults-postgresql-ha-postgresql-headless.pg-test.svc.cluster.local:5432'...
psql: error: could not connect to server: could not translate host name "defaults-postgresql-ha-postgresql-1.defaults-postgresql-ha-postgresql-headless.pg-test.svc.cluster.local" to address: Name or service not known
postgresql-repmgr 12:30:30.61 DEBUG ==> Skipping: failed to get primary from the node 'defaults-postgresql-ha-postgresql-1.defaults-postgresql-ha-postgresql-headless.pg-test.svc.cluster.local:5432'!
postgresql-repmgr 12:30:30.62 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 12:30:30.63 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 12:30:30.65 DEBUG ==> Injecting a new postgresql.conf file...
postgresql-repmgr 12:30:30.65 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 12:30:30.73 DEBUG ==> Injecting a new pg_hba.conf file...
postgresql-repmgr 12:30:30.74 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 12:30:30.75 DEBUG ==> Node ID: '1000', Rol: 'primary', Primary Node: ':5432'
postgresql-repmgr 12:30:30.75 INFO  ==> Initializing Repmgr...
postgresql-repmgr 12:30:30.75 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 12:30:30.76 DEBUG ==> Copying files from /bitnami/postgresql/conf to /opt/bitnami/postgresql/conf
postgresql-repmgr 12:30:30.77 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 12:30:30.77 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql-repmgr 12:30:30.77 DEBUG ==> Ensuring expected directories/files exist...
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /bitnami/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
syncing data to disk ... ok


Success. You can now start the database server using:

    /opt/bitnami/postgresql/bin/pg_ctl -D /bitnami/postgresql/data -l logfile start

postgresql-repmgr 12:30:37.56 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2020-10-12 12:30:37.595 GMT [125] LOG:  starting PostgreSQL 12.4 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2020-10-12 12:30:37.596 GMT [125] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-10-12 12:30:37.596 GMT [125] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
2020-10-12 12:30:37.596 GMT [125] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2020-10-12 12:30:37.599 GMT [125] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-10-12 12:30:37.612 GMT [125] LOG:  redirecting log output to logging collector process
2020-10-12 12:30:37.612 GMT [125] HINT:  Future log output will appear in directory "/opt/bitnami/postgresql/logs".
2020-10-12 12:30:37.616 GMT [127] LOG:  database system was shut down at 2020-10-12 12:30:36 GMT
2020-10-12 12:30:37.626 GMT [125] LOG:  database system is ready to accept connections
 done
server started
2020-10-12 12:30:43.822 GMT [147] FATAL:  role "app" does not exist
CREATE DATABASE
postgresql-repmgr 12:30:46.56 INFO  ==> Changing password of postgres
ALTER ROLE
postgresql-repmgr 12:30:46.58 INFO  ==> Creating user app
CREATE ROLE
postgresql-repmgr 12:30:46.61 INFO  ==> Granting access to "app" to the database "test_db"
GRANT
postgresql-repmgr 12:30:46.62 INFO  ==> Creating replication user repmgr
CREATE ROLE
postgresql-repmgr 12:30:46.67 INFO  ==> Configuring replication parameters
postgresql-repmgr 12:30:46.70 INFO  ==> Configuring fsync
postgresql-repmgr 12:30:46.71 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 12:30:46.72 INFO  ==> Creating repmgr user: repmgr
2020-10-12 12:30:46.733 GMT [201] ERROR:  role "repmgr" already exists
2020-10-12 12:30:46.733 GMT [201] STATEMENT:  CREATE ROLE "repmgr" WITH LOGIN CREATEDB PASSWORD 'repmgr-pass';
ERROR:  role "repmgr" already exists
ALTER ROLE
ALTER ROLE
postgresql-repmgr 12:30:46.77 INFO  ==> Creating repmgr database: repmgr
CREATE DATABASE
postgresql-repmgr 12:30:55.16 INFO  ==> Stopping PostgreSQL...
2020-10-12 12:30:55.169 GMT [125] LOG:  received smart shutdown request
2020-10-12 12:30:55.174 GMT [125] LOG:  background worker "logical replication launcher" (PID 134) exited with exit code 1
2020-10-12 12:30:55.177 GMT [128] LOG:  shutting down
2020-10-12 12:31:03.816 GMT [247] FATAL:  the database system is shutting down
postgresql-repmgr 12:31:05.19 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 12:31:05.19 INFO  ==> Registering Primary...
ERROR: connection to database failed
DETAIL: 
could not connect to server: Connection refused
        Is the server running on host "defaults-postgresql-ha-postgresql-0.defaults-postgresql-ha-postgresql-headless.pg-test.svc.cluster.local" (10.20.3.149) and accepting
        TCP/IP connections on port 5432?

DETAIL: attempted to connect using:
  user=repmgr password=repmgr-pass connect_timeout=5 dbname=repmgr host=defaults-postgresql-ha-postgresql-0.defaults-postgresql-ha-postgresql-headless.pg-test.svc.cluster.local port=5432 fallback_application_name=repmgr
postgresql-repmgr 12:31:05.20 INFO  ==> Stopping PostgreSQL...
2020-10-12 12:31:06.568 GMT [125] LOG:  database system is shut down
```

...and subsequent runs of the same pod yield:
```
postgresql-repmgr 12:31:08.45 
postgresql-repmgr 12:31:08.45 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 12:31:08.46 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 12:31:08.46 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 12:31:08.46 
postgresql-repmgr 12:31:08.46 DEBUG ==> Configuring libnss_wrapper...
postgresql-repmgr 12:31:08.47 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 12:31:08.50 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 12:31:08.50 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 12:31:08.50 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 12:31:08.51 DEBUG ==> Checking node 'defaults-postgresql-ha-postgresql-0.defaults-postgresql-ha-postgresql-headless.pg-test.svc.cluster.local:5432'...
psql: error: could not connect to server: could not connect to server: Connection refused
        Is the server running on host "defaults-postgresql-ha-postgresql-0.defaults-postgresql-ha-postgresql-headless.pg-test.svc.cluster.local" (10.20.3.149) and accepting
        TCP/IP connections on port 5432?
postgresql-repmgr 12:31:08.52 DEBUG ==> Skipping: failed to get primary from the node 'defaults-postgresql-ha-postgresql-0.defaults-postgresql-ha-postgresql-headless.pg-test.svc.cluster.local:5432'!
postgresql-repmgr 12:31:08.52 DEBUG ==> Checking node 'defaults-postgresql-ha-postgresql-1.defaults-postgresql-ha-postgresql-headless.pg-test.svc.cluster.local:5432'...
psql: error: could not connect to server: could not translate host name "defaults-postgresql-ha-postgresql-1.defaults-postgresql-ha-postgresql-headless.pg-test.svc.cluster.local" to address: Name or service not known
postgresql-repmgr 12:31:08.54 DEBUG ==> Skipping: failed to get primary from the node 'defaults-postgresql-ha-postgresql-1.defaults-postgresql-ha-postgresql-headless.pg-test.svc.cluster.local:5432'!
postgresql-repmgr 12:31:08.54 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 12:31:08.55 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 12:31:08.55 DEBUG ==> Injecting a new postgresql.conf file...
postgresql-repmgr 12:31:08.55 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 12:31:08.63 DEBUG ==> Injecting a new pg_hba.conf file...
postgresql-repmgr 12:31:08.64 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 12:31:08.64 DEBUG ==> Node ID: '1000', Rol: 'primary', Primary Node: ':5432'
postgresql-repmgr 12:31:08.65 INFO  ==> Initializing Repmgr...
postgresql-repmgr 12:31:08.65 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 12:31:08.66 DEBUG ==> Copying files from /bitnami/postgresql/conf to /opt/bitnami/postgresql/conf
postgresql-repmgr 12:31:08.66 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 12:31:08.66 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql-repmgr 12:31:08.66 DEBUG ==> Ensuring expected directories/files exist...
postgresql-repmgr 12:31:08.68 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql-repmgr 12:31:08.70 INFO  ==> Configuring replication parameters
postgresql-repmgr 12:31:08.73 INFO  ==> Configuring fsync
postgresql-repmgr 12:31:08.74 DEBUG ==> Skipping repmgr configuration...
postgresql-repmgr 12:31:08.74 INFO  ==> Stopping PostgreSQL...
postgresql-repmgr 12:31:08.75 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **

postgresql-repmgr 12:31:08.77 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2020-10-12 12:31:08.817 GMT [142] LOG:  starting PostgreSQL 12.4 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2020-10-12 12:31:08.818 GMT [142] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-10-12 12:31:08.818 GMT [142] LOG:  listening on IPv6 address "::", port 5432
2020-10-12 12:31:08.821 GMT [142] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-10-12 12:31:08.854 GMT [142] LOG:  redirecting log output to logging collector process
2020-10-12 12:31:08.854 GMT [142] HINT:  Future log output will appear in directory "/opt/bitnami/postgresql/logs".
2020-10-12 12:31:08.858 GMT [144] LOG:  database system was shut down at 2020-10-12 12:31:01 GMT
2020-10-12 12:31:08.867 GMT [142] LOG:  database system is ready to accept connections
 done
server started
postgresql-repmgr 12:31:08.90 INFO  ==> ** Starting repmgrd **
[2020-10-12 12:31:08] [NOTICE] repmgrd (repmgrd 5.1.0) starting up
[2020-10-12 12:31:08] [ERROR] repmgr extension not found on this node
[2020-10-12 12:31:08] [DETAIL] repmgr extension is available but not installed in database "repmgr"
[2020-10-12 12:31:08] [HINT] check that this node is part of a repmgr cluster
```

Tests executed with the following values:
```yaml
postgresqlImage:
  registry: docker.io
  repository: bitnami/postgresql-repmgr
  tag: 12.4.0-debian-10-r60
  pullPolicy: IfNotPresent
  debug: true
pgpoolImage:
  registry: docker.io
  repository: bitnami/pgpool
  tag: 4.1.4-debian-10-r19
  pullPolicy: IfNotPresent
  debug: true
volumePermissionsImage:
  registry: docker.io
  repository: bitnami/minideb
  tag: buster
  pullPolicy: Always
metricsImage:
  registry: docker.io
  repository: bitnami/postgres-exporter
  tag: 0.8.0-debian-10-r242
  pullPolicy: IfNotPresent
  debug: false
clusterDomain: cluster.local
postgresql:
  labels: {}
  podLabels: {}
  replicaCount: 2
  updateStrategyType: RollingUpdate
  podAnnotations: {}
  affinity: {}
  nodeSelector: {}
  priorityClassName: ""
  tolerations: {}
  securityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
  resources:
    limits: {}
    requests: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 6
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 6
  pdb:
    create: false
    minAvailable: 1
  username: app
  password: my-app-pass
  database: test_db
  postgresPassword: pg-pass
  upgradeRepmgrExtension: false
  pgHbaTrustAll: false
  syncReplication: false
  repmgrUsername: repmgr
  repmgrPassword: repmgr-pass
  repmgrDatabase: repmgr
  repmgrLogLevel: NOTICE
  repmgrConnectTimeout: 5
  repmgrReconnectAttempts: 3
  repmgrReconnectInterval: 5
pgpool:
  customUsers:
  customUsersSecret:
  srCheckDatabase: test_db
  labels: {}
  podLabels: {}
  replicaCount: 1
  podAnnotations: {}
  affinity: {}
  nodeSelector: {}
  priorityClassName: ""
  tolerations: {}
  securityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
  resources:
    limits: {}
    requests: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  pdb:
    create: false
    minAvailable: 1
  updateStrategy: {}
  adminUsername: admin
  adminPassword: pgpool-pass
  useLoadBalancing: true
  tls:
    enabled: false
    preferServerCiphers: true
    certificatesSecret: ""
    certFilename: ""
    certKeyFilename: ""
    certCAFilename:
ldap:
  enabled: false
  uri:
  base:
  binddn:
  bindpw:
  bslookup:
  scope:
  tlsReqcert:
  nssInitgroupsIgnoreusers: root,nslcd
volumePermissions:
  enabled: false
  securityContext:
    runAsUser: 0
  resources:
    limits: {}
    requests: {}
metrics:
  enabled: true
  securityContext:
    enabled: true
    runAsUser: 1001
  resources:
    limits: {}
    requests: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 6
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 6
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
  serviceMonitor:
    enabled: false
    selector:
      prometheus: kube-prometheus
    relabelings: []
    metricRelabelings: []
persistence:
  enabled: true
  mountPath: /bitnami/postgresql
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  annotations: {}
service:
  type: ClusterIP
  port: 5432
  annotations: {}
networkPolicy:
  enabled: true
  allowExternal: false
```
