### ISSUE TITLE
bitnami/influxdb doesn't create default database

### ISSUE THREAD

**Issue by YunaBraska** [bitnami/charts#3995]
**Which chart**:
bitnami/influxdb version 0.6.9

**Describe the bug**
I start influxdb chart with settings `database: "test_db"`, `authEnabled: false`, `architecture: high-availability`. 
When I then connect from Grafana or with the influx client to the influxdb, then it didn't created the database `test_db`.

**To Reproduce**
My settings:
```
influxdb:
  enabled: true
  resources:
    limits:
      cpu: 1
      memory: 2000Mi
    requests:
      cpu: 1
      memory: 2000Mi
  metrics:
    enabled: true
  database: "test_db"
  authEnabled: false
  relay:
    replicaCount: 2
  influxdb:
    replicaCount: 3
    database: "test_db"
  architecture: high-availability
```
2) `helm template` and `kubectl apply`

**Expected behavior**
Creates the database `test_db` on startup

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v2.16.5
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:08:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Maybe I understand something wrong, as I am new to helm thingy ;) But couldn't get the answer from the readme. Thx for helping me out
