### ISSUE TITLE
[bitnami/external-dns] Error: YAML parse error on external-dns/templates/deployment.yaml with podAnnotations

### ISSUE THREAD

**Issue by adaphi** [bitnami/charts#4024]
**Which chart**:
external-dns 3.4.6

**Describe the bug**
Trying to install 3.4.6 of the external DNS chart with a set of values that includes both podAnnotations and metrics.podAnnotations throws this error:

```
Error: YAML parse error on external-dns/templates/deployment.yaml: error converting YAML to JSON: yaml: line 25: mapping values are not allowed in this context
```

**To Reproduce**
Run a helm install of the chart with the following values file:
```
provider: aws
metrics:
  enabled: true
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "7979"
podAnnotations:
  iam.amazonaws.com/role: "arn:aws:iam::000000000000:role/my-aws-role"
```

**Expected behavior**
The template should parse properly and external-dns should be installed

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Using `helm template --debug` you can see that it results in the following annotations on the deployment:

```
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns
        helm.sh/chart: external-dns-3.4.6
        app.kubernetes.io/instance: my-external-dns
        app.kubernetes.io/managed-by: Helm
      annotations:

        iam.amazonaws.com/role: arn:aws:iam::000000000000:role/my-aws-roleprometheus.io/port: "7979"
        prometheus.io/scrape: "true"
```
so it looks like it's just having issues joining the two.

For now the workaround is to just use one of the annotation blocks instead of both.
