### ISSUE TITLE
[bitnami/cassandra] Using G1GC

### ISSUE THREAD

**Issue by mquilling** [bitnami/charts#4027]
**Which chart**:
Cassandra

**Is your feature request related to a problem? Please describe.**
Is it possible to enable G1GC through this chart?  The GC JVM options are in jvm.options but I have not found a way to update that and remove CMS and enable G1GC.  I can append options the jvm.extraOpts but there are some settings I need to remove.

**Describe the solution you'd like**
A way to specify the GC

**Comment by carrodher** [comment]
At this moment it is possible to set the value for Java Virtual Machine extra options (`JVM_EXTRA_OPTS`) by setting the `jvm.extraOpts` parameter but I think there is not an alternative parameter to remove jvm options. As it is difficult for us to contemplate all the use cases PRs are welcome in order to add new features to the charts and/or containers, just in case you have something in mind about how your use case can be solved

**Comment by mquilling** [comment]
Hi @carrodher,

I was looking through the template and see `existingConfiguration` is mounted to `/opt/bitnami/cassandra/conf` this is the directory where the `jvm.options` file lives.  I think this might work but not sure how to set this values - do you have an example?

**Comment by carrodher** [comment]
You can mount your custom configuration file(s) for Cassandra. This is done by setting the `existingConfiguration` parameter with the name of an existing ConfigMap that includes the custom configuration file(s).

You need to create the ConfigMap with the Cassandra configuration placing the Cassandra configuration under the `data` object in the ConfigMap. When creating this ConfigMap you need to provide a name, this name is the one you need to use in the `existingConfiguration` parameter for the chart to use the ConfigMap and apply your custom Cassandra configuration.

[Here](https://kubernetes.io/docs/concepts/configuration/configmap/) you can find more info about the ConfigMaps in k8s, but at the end, you need to create a ConfigMap object like the following one adding the Cassandra configuration:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-config
data:
  # Replace this sample data with the Cassandra configuration (in the format supported by Cassandra)
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
```
