### ISSUE TITLE
[zookeeper] Unable to specify consul service annotations

### ISSUE THREAD

**Issue by sergeyshaykhullin** [bitnami/charts#4030]
**Which chart**:
zookeeper 5.22.0

**Describe the bug**

I add consul annotations for service to autoregister it, but getting error (additional context)
It might be, because `/` in annotation is used

**To Reproduce**

Add consul service annotations

```yaml
service:
  annotations:
    consul.hashicorp.com/service-sync: "true"
    consul.hashicorp.com/service-name: zookeeper
    consul.hashicorp.com/service-port: tcp-client
```

**Expected behavior**

Zookeeper chart add annotations to k8s service

**Version of Helm and Kubernetes**:

Helm 3.2.3
K8s Server + Client 1.19.3

**Additional context**

Ansible log:
`
fatal: [node1]: FAILED! => {"changed": false, "command": "/usr/local/bin/helm --namespace=zookeeper --version=5.22.0 upgrade -i --reset-values -f=/tmp/tmpdp7fmyv3.yml zookeeper bitnami/zookeeper", "msg": "Failure when executing Helm command. Exited 1.\nstdout: \nstderr: Error: UPGRADE FAILED: YAML parse error on zookeeper/templates/svc.yaml: error converting YAML to JSON: yaml: line 14: did not find expected key\n", "stderr": "Error: UPGRADE FAILED: YAML parse error on zookeeper/templates/svc.yaml: error converting YAML to JSON: yaml: line 14: did not find expected key\n", "stderr_lines": ["Error: UPGRADE FAILED: YAML parse error on zookeeper/templates/svc.yaml: error converting YAML to JSON: yaml: line 14: did not find expected key"], "stdout": "", "stdout_lines": []}
`
