### ISSUE TITLE
[bitnami/external-dns] DNS names are created in favor of nginx-ingress-controller but should be to another balancer

### ISSUE THREAD

**Issue by evgmoskalenko** [bitnami/charts#4036]
**Which chart**:

* **Chart version:** external-dns: 3.4.6
* **Kubernetes version:** v1.18.8-eks-7c9bda 

**Describe the bug**

I have two balancers:

1. AWS Classic Load Balancer for nginx-ingress-controller
2. AWS Classic Load Balancer for the second deployment - Argocd (for example)

When I deploy "external-dns" and "Argocd" and "nginx-ingress-controller". External-dns create DNS to nginx-ingress-controller AWS ELB. But this is not the correct behavior, because with the annotations I say that the DNS name should be created for the deployment of Argocd, therefore the DNS should be created for the Argocd balancer, but created to nginx-ingress-controller :-)

My Argocd configuration looks like:

```
server:
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: argocd.my-fqdn.com
      service.beta.kubernetes.io/aws-load-balancer-internal: "false"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "ssl"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: my_aws_acm_certificate_arn
      service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-2016-08"
      service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "false"
    labels: {}
    type: LoadBalancer
    servicePortHttps: 443
    servicePortHttpsName: https

  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/hostname: argocd.my-fqdn.com
    labels: {}
    hosts:
      - argocd.my-fqdn.com
    paths:
      - /
    tls: []
```

My nginx-ingress-controller configuration looks like:

```
  service:
    enabled: true
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "false"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    type: LoadBalancer
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-eks-7c9bda", GitCommit:"7c9bda52c425d0d56d7b93f1377a826b4132c05c", GitTreeState:"clean", BuildDate:"2020-08-28T23:04:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

Occurs sporadically... I have been using external-dns for quite some time now, everything was fine until today.
