### ISSUE TITLE
unable to add serviceMonitor to mariadb after install

### ISSUE THREAD

**Issue by si458** [bitnami/charts#4048]
**Which chart**:
mariadb latest version

**Describe the bug**
i installed mariadb via helm no problem, but then i discovered i needed to install the servicemonitor which i forgot
so changed my yaml file then when i try to `helm upgrade` i keep getting 
```
Error: UPGRADE FAILED: cannot patch "mariadb" with kind StatefulSet: StatefulSet.apps "mariadb" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

**To Reproduce**
1. helm install mariadb bitnami/mariadb -f myconf.yaml
```
global:
  storageClass: longhorn
auth:
  rootPassword: abc123
replication:
  enabled: false
metrics:
  enabled: true
```
2. helm upgrade mariadb bitnami/mariadb -f myconf.yaml
```
global:
  storageClass: longhorn
auth:
  rootPassword: abc123
replication:
  enabled: false
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```
3. ERRORS OUT

**Expected behavior**
no error and it install serviceMonitor alongside running mariadb pod

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8+k3s1", GitCommit:"6b595318666804506c19cfc3d3d228423d38fab1", GitTreeState:"clean", BuildDate:"2020-08-14T20:42:29Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
