### ISSUE TITLE
[bitnami/ghost] tls secret not generated as expected

### ISSUE THREAD

**Issue by ChipWolf** [bitnami/charts#4056]
**Which chart**:
Ghost 10.1.19

**Describe the bug**
Despite what is documented and appears in the template, the `secretName` for the ingress TLS configuration isn't set.

**To Reproduce**
1. Deploy the chart with the following values:
```yaml
    ghostProtocol: https
    ghostUsername: john.smith@example.org
    ghostEmail: john.smith@example.org
    ghostBlogTitle: Example Blog
    service:
      type: ClusterIP
    ingress:
      enabled: true
      certManager: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/enable-global-auth: "false"
      hosts:
        - name: blog.example.org
          tls: true
```
2. Inspect the deployed ingress
![](https://i.cwlf.uk/L40yX)

**Expected behavior**
The `secretName` should be set to the default value.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-30T20:56:21Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ChipWolf** [comment]
This is probably also worthy of note, the Ghost instance seems to have some unusual defaults, there's an additional slash prior to the port ![](https://i.cwlf.uk/EPZ9P)

**Comment by juan131** [comment]
Hi @ChipWolf 

The reason for that behaviour is that you're overwriting 1st element of the "hosts" array (removing the default value for "tlsSecret"):

```yaml
ingress:
    hosts:
      - name: blog.example.org
        tls: true
```

Anyway, I created this [PR](https://github.com/bitnami/charts/pull/4057) so it fallbacks in the ingress hostname adding the `-tls` suffix.
