### ISSUE TITLE
[bitnami/ghost] ghostPassword and mariadb passwords required by validation using default values

### ISSUE THREAD

**Issue by ChipWolf** [bitnami/charts#4066]
**Which chart**:
Ghost 10.1.20

**Describe the bug**
Helm outputs password errors from the validator stating the `ghostPassword` and `mariadb` passwords must not be empty. This is despite the default values for `allowEmptyPassword` for the database set to `true` and the default value for `ghostPassword` set to randomly generate.

**To Reproduce**

https://github.com/bitnami/charts/blob/master/bitnami/ghost/values.yaml#L85
1. Deploy the chart with the helm-operator using the following values
```yaml
    ghostProtocol: https
    ghostUsername: john.smith@example.org
    ghostEmail: john.smith@example.org
    ghostBlogTitle: Example Blog
    service:
      type: ClusterIP
    ingress:
      enabled: true
      certManager: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/enable-global-auth: "false"
      hosts:
        - name: blog.example.org
          tls: true
```
2. Check the output of the chart deployment:
```
  Warning  FailedReleaseSync  2m36s  helm-operator  synchronization of release 'ghost' in namespace 'ghost' failed: dry-run upgrade failed: dry-run upgrade for comparison failed: template: ghost/templates/NOTES.txt:77:4: executing "ghost/templates/NOTES.txt" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" $passwordErrors "context" $)>: error calling include: template: ghost/charts/common/templates/_errors.tpl:18:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail:
PASSWORDS ERROR: you must provide your current passwords when upgrade the release
    'ghostPassword' must not be empty, please add '--set ghostPassword=$GHOST_PASSWORD' to the command. To get the current value:

        export GHOST_PASSWORD=$(kubectl get secret --namespace ghost ghost -o jsonpath="{.data.ghost-password}" | base64 --decode)

    'mariadb.rootUser.password' must not be empty, please add '--set mariadb.rootUser.password=$MARIADB_ROOT_PASSWORD' to the command. To get the current value:

        export MARIADB_ROOT_PASSWORD=$(kubectl get secret --namespace ghost ghost-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)

    'mariadb.db.password' must not be empty, please add '--set mariadb.db.password=$MARIADB_PASSWORD' to the command. To get the current value:

        export MARIADB_PASSWORD=$(kubectl get secret --namespace ghost ghost-mariadb -o jsonpath="{.data.mariadb-password}" | base64 --decode)
```
3. See error

**Expected behavior**
The chart should deploy sucessfully without specifying any passwords, as the `ghostPassword` should be randomly generated and the database should permit the passwords to be empty.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-30T20:56:21Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
