### ISSUE TITLE
[bitnami/redis] How to Access Redis Master Node in the Redis Sentinel Deployment outside the K8s Cluster

### ISSUE THREAD

**Issue by shenqinb** [bitnami/charts#4082]
**Which chart**:
 bitnami/redis

**Is your feature request related to a problem? Please describe.**
Step 1: Helm install the Redis Sentinel Cluster into the K8s cluster.
Step 2: Expose the Redis Sentinel Service via Ingress to make it accessible outside the cluster (Redis Port 6379, Sentinel 26379).
Step 3: Now I want to write something into Redis, I first connect to sentinel port 26379 to get the Redis Master Node IP and Port. but the returned IP and Port are not accessible outside the cluster.

How we can deploy Redis Sentinel Cluster, and make it accessible outside the cluster?

**Comment by juan131** [comment]
Hi @shenqinb 

You can expose Redis master outside the cluster using the `master.service.type` parameter (set it to `NodePort` or `LoadBalancer` types). That said, it's very likely that Redis Sentinel is not returning the external IP/port or the Redis master node but the internal ones instead.

Could you please run the command below and share the output so I can reproduce the same scenario on my side? 

```console
$ helm get values
```

Remember to change the placeholder _MY_RELEAS_NAME_ with the actual name you chose for you Redis chart release.

**Comment by shenqinb** [comment]
@juan131 hi, Thanks for your reply,
I'm trying to deploy with NodePort, below is the values, in the values, I enable the sentinel with `sentinel.enabled=true`,
```
cluster:
  enabled: true
  slaveCount: 3
clusterDomain: cluster.local
configmap: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""
global:
  redis: {}
image:
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: bitnami/redis
  tag: 6.0.8-debian-10-r0
master:
  affinity: {}
  command: /run.sh
  configmap: null
  customLivenessProbe: {}
  customReadinessProbe: {}
  disableCommands:
  - FLUSHDB
  - FLUSHALL
  extraEnvVars: []
  extraEnvVarsCM: []
  extraEnvVarsSecret: []
  extraFlags: []
  livenessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
  persistence:
    accessModes:
    - ReadWriteOnce
    enabled: true
    matchExpressions: {}
    matchLabels: {}
    path: /data
    size: 8Gi
    subPath: ""
  podAnnotations: {}
  podLabels: {}
  priorityClassName: {}
  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1
  service:
    annotations: {}
    labels: {}
    loadBalancerIP: null
    port: 6379
    type: ClusterIP
  shareProcessNamespace: false
  statefulset:
    updateStrategy: RollingUpdate
metrics:
  enabled: false
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: bitnami/redis-exporter
    tag: 1.11.1-debian-10-r12
  podAnnotations:
    prometheus.io/port: "9121"
    prometheus.io/scrape: "true"
  prometheusRule:
    additionalLabels: {}
    enabled: false
    namespace: ""
    rules: []
  service:
    annotations: {}
    labels: {}
    type: ClusterIP
  serviceMonitor:
    enabled: false
    selector:
      prometheus: kube-prometheus
networkPolicy:
  allowExternal: true
  enabled: false
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
password: ""
persistence:
  existingClaim: null
podDisruptionBudget:
  enabled: false
  minAvailable: 1
podSecurityPolicy:
  create: false
rbac:
  create: false
  role:
    rules: []
redisPort: 6379
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
sentinel:
  configmap: null
  customLivenessProbe: {}
  customReadinessProbe: {}
  downAfterMilliseconds: 60000
  enabled: true
  failoverTimeout: 18000
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: bitnami/redis-sentinel
    tag: 6.0.8-debian-10-r1
  initialCheckTimeout: 5
  livenessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
  masterSet: mymaster
  parallelSyncs: 1
  port: 26379
  quorum: 2
  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1
  service:
    annotations: {}
    labels: {}
    loadBalancerIP: null
    redisNodePort: 30001
    redisPort: 6379
    sentinelNodePort: 30000
    sentinelPort: 26379
    type: NodePort
  staticID: false
  usePassword: true
serviceAccount:
  create: false
  name: null
slave:
  affinity: {}
  command: /run.sh
  configmap: null
  customLivenessProbe: {}
  customReadinessProbe: {}
  disableCommands:
  - FLUSHDB
  - FLUSHALL
  extraEnvVars: []
  extraEnvVarsCM: []
  extraEnvVarsSecret: []
  extraFlags: []
  livenessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  persistence:
    accessModes:
    - ReadWriteOnce
    enabled: true
    matchExpressions: {}
    matchLabels: {}
    path: /data
    size: 8Gi
    subPath: ""
  podAnnotations: {}
  podLabels: {}
  port: 6379
  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 10
  service:
    annotations: {}
    labels: {}
    loadBalancerIP: null
    port: 6379
    type: ClusterIP
  shareProcessNamespace: false
  spreadConstraints: {}
  statefulset:
    updateStrategy: RollingUpdate
sysctlImage:
  command: []
  enabled: false
  mountHostSys: false
  pullPolicy: Always
  registry: docker.io
  repository: bitnami/minideb
  resources: {}
  tag: buster
tls:
  authClients: true
  certCAFilename: ca.pem
  certFilename: cert.pem
  certKeyFilename: cert.key
  certificatesSecret: redis-certificates-tls-secret
  enabled: false
usePassword: true
usePasswordFile: false
volumePermissions:
  enabled: false
  image:
    pullPolicy: Always
    registry: docker.io
    repository: bitnami/minideb
    tag: buster
  resources: {}
```

**Comment by juan131** [comment]
Hi @shenqinb 

I can reproduce the issue.. It seems we need to configure the IP and Port to be announced, see:

- https://redis.io/topics/sentinel#sentinel-docker-nat-and-possible-issues

@rafariossaa @miguelaeh do you know if we have already a way to do this automatically?

**Comment by miguelaeh** [comment]
Hi,
We are doing this for the `bitnami/redis-cluster` helm chart, but I think it is not implemented in this one. Maybe @rafariossaa has more information about this

**Comment by rafariossaa** [comment]
Hi,
  Yes, we have this configuration in `bitnami/redis-cluster`, but not in `bitnami/redis`.

**Comment by juan131** [comment]
@rafariossaa @miguelaeh did we implement this on Redis chart? If not, I will proceed to open an internal task to address this issue asap.

**Comment by youngnicks** [comment]
Instead of using node port to expose the master, would it be better to have a dedicated master service? Sentinel can be configured to execute a command when the master is changed. This script could update pod labels to switch which pod the service is routing to.

Doing it this way would remove the need for clients to even know about Sentinel as the master service should always be pointing to the latest master.

I'm currently working on creating the update script. I have listed all of the changes I can think of below.

**Sentinel Configuration**
_sentinel.configmap_
`sentinel client-reconfig-script mymaster /path/to/script`

**Script**
```
# The following arguments are passed to the script:
# <master-name> <role> <state> <from-ip> <from-port> <to-ip> <to-port>
add master label to new master
remove master label from old master (if possible)
```

**Comment by juan131** [comment]
Hi @youngnicks 

Thanks for sharing your proposal.

How do you plan to automate the execution of this script? 
- Do you plan to execute the script in the same container where Sentinel is running?
- Do you plan to have a cronjob running in your K8s cluster with RBAC permissions to make requests to the K8s API?

**Comment by youngnicks** [comment]
Hi @juan131 

Like I stated above, Sentinel has a hook to run a script when a new master is selected. Therefore, the execution of this script would best be done in the Sentinel container. Currently, I'm thinking of a sidecar container with kubectl to manage the labels but curl could also be used. I'm guessing the pod would need the appropriate RBAC permissions to update its own labels.

```
# Add label to pod by IP
kubectl label pod --field-selector status.podIP=$to-ip master=true

# Remove label from pod by IP
kubectl labe pod --field-selector status.podIP=$from-ip master-
```

**Comment by juan131** [comment]
Hi @youngnicks 

It sounds interesting but risky. I mean, a potential attacker that gains access to your Sentinel pods (exploiting any security vulnerability that Redis may have) could gain control of your cluster if it has permissions to query the K8s API.

Therefore, I highly recommend you to limit the scope of actions the container can perform by defining strict RBAC rules.

**Comment by youngnicks** [comment]
Hi @juan131 

I have thought of this and am considering putting Sentinel/kubectl in its own pod with pod affinity for the Redis instances. I will still also have strict RBAC to hopefully limit just updating the label.

**Comment by juan131** [comment]
Hi @youngnicks 

I think you don't need to get that far. You can still run Sentinels as a sidecar container in Redis pod, but double-check the pod has only RBAC permissions to do the required changes in the labels and nothing else.

You can also play with the "SecurityContext" (see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#securitycontext-v1-core) used in the Sentinel sidecar so you ensure that it's executed as a non-root container with no privilege escalation possibilities.

**Comment by youngnicks** [comment]
I was able to get this idea working. When the current master goes down a new one is elected and the labels are updated. However, it seems to take Sentinel longer to elect a new master and run the script than it does for Kubernetes to bring up a replacement pod. Because of this, it seems to be better to not use Sentinel and Cluster as it is less resources and faster recovery times. I'm wondering if having Sentinel and Redis in the same pod is the cause for the slower Sentinel response time.

I don't have the bandwidth to separate Sentinel from Redis at the moment, but can share what I currently have if anyone is interested in picking it up from here.

**Comment by juan131** [comment]
Hi @youngnicks 

> it seems to take Sentinel longer to elect a new master and run the script than it does for Kubernetes to bring up a replacement pod. Because of this, it seems to be better to not use Sentinel and Cluster as it is less resources and faster recovery times

Sorry I'm a little bit confused. What do you mean when "it seems to be better to not use Sentinel and Cluster"? Are you talking about the Redis Cluster chart?

>  I'm wondering if having Sentinel and Redis in the same pod is the cause for the slower Sentinel response time.

It shouldn't affect that as far as each container (sentinel and redis) has enough resources.

**Comment by youngnicks** [comment]
I was referring to the cluster option in this chart which enables master/slave. There is still a benefit to using master/slave topology if you have a high read load. The application I'm currently working on does not have that so there is no benefit for us. 

Sentinel OTOH took longer to elect a new leader than Kubernetes took to spin up a replacement pod. I don't think resources are an issue but rather Sentinel losing a member and needing to deal with that before electing a new Redis master. I'm not a Redis expert so I could be wrong.

**Comment by juan131** [comment]
Hi @youngnicks 

> Sentinel OTOH took longer to elect a new leader than Kubernetes took to spin up a replacement pod. I don't think resources are an issue but rather Sentinel losing a member and needing to deal with that before electing a new Redis master. I'm not a Redis expert so I could be wrong.

Did you play with the `REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS` and `REDIS_SENTINEL_FAILOVER_TIMEOUT` to improve this experience? See https://github.com/bitnami/bitnami-docker-redis-sentinel#environment-variables

**Comment by youngnicks** [comment]
Hi @juan131 

I had not, thanks for the pointer. Playing with those I was able to get a switchover to happen much faster (~7s). I'll need to make a few more tweaks to prevent some issues such as the master stateful set being added to the master service when it comes back online. It is shortly removed as it's not actually a master, but I don't want to risk the possibility of requests going to it.

I'm still thinking of separating out the Sentinels to reduce the number of Redis slaves needed. I'll create a PR once I get this working well if you are interested in operating this way.

FWIW there is a risk of losing data using Sentinel that you wouldn't have with Master only. The drawback is that the database would be down until Kubernetes brings the instance back up.

**Comment by juan131** [comment]
> I had not, thanks for the pointer. Playing with those I was able to get a switchover to happen much faster (~7s)

Great!!

>  I'll need to make a few more tweaks to prevent some issues such as the master stateful set being added to the master service when it comes back online

Shouldn't be easier to force a new election once the master is back so it recover its previous status?

> I'm still thinking of separating out the Sentinels to reduce the number of Redis slaves needed. I'll create a PR once I get this working well if you are interested in operating this way.

Could you please elaborate more the reasons behind this separation?

**Comment by youngnicks** [comment]
> Shouldn't be easier to force a new election once the master is back so it recover its previous status?

The master label is updated shortly after it comes online. The issue is that there are a few seconds where it has the master label and it picked up by the Service. I'd like to avoid any potential calls to a non-master even if it is only a few seconds.

> Could you please elaborate more the reasons behind this separation?

Sentinel should have a quorum of at least 2, meaning at least 3 instances. I'd like the ability to have 2 Redis instances (primary/backup) instead of needing 3. Separating Sentinel from Redis would allow that.

**Comment by juan131** [comment]
> The master label is updated shortly after it comes online. The issue is that there are a few seconds where it has the master label and it picked up by the Service. I'd like to avoid any potential calls to a non-master even if it is only a few seconds.

Fair enough.

> Sentinel should have a quorum of at least 2, meaning at least 3 instances. I'd like the ability to have 2 Redis instances (primary/backup) instead of needing 3. Separating Sentinel from Redis would allow that.

Interesting approach. @miguelaeh what do you think about this? Should we consider a separate deployment/sts for Sentinel nodes?

**Comment by miguelaeh** [comment]
Hi guys, thank you very much for the extended discussion, I added my concerns to the PR.

**Comment by youngnicks** [comment]
@juan131 @miguelaeh 
For Sentinel I had another idea on how to reduce the number of Redis instances without removing Sentinel from the pods. I don't know if it would be too complex to have a separate Sentinel only deployment which a computed number of replicas. It would be sentinel count - redis count. This way you still get the benefits of having Sentinel in the same pod but can also have just two Redis instances.

**Comment by miguelaeh** [comment]
Hi @youngnicks ,
Is there a strong reason for not be using Redis Cluster in this case? I think you said you don't have a big read load, so maybe it will better fit your requirements. That said, not sure why you want only two Redis instances, Redis cluster will have 6 by default.

**Comment by youngnicks** [comment]
Hi @miguelaeh 

Some of our instances are fairly small and used as a work queue so a full cluster is not needed. Other instances are using the multiple database feature which is not available in Redis Cluster.

**Comment by miguelaeh** [comment]
Thanks for the clarifications.
I think for this kind of specific case you should modify the Helm Chart as you need, but maybe the amount of other users needing this feature is really low.

**Comment by deepakkrmodi** [comment]
@miguelaeh @juan131 I have not enabled sentinel in my deployment, and in my setup I have one master and two slaves for redis, but still i am getting "READONLY You can't write against a read only replica." . What can be the potential cause?

**Comment by bmistrapau** [comment]
Hi,

I am also interested in this functionality. We want to expose a redis with sentinel setup (3 nodes) outside of kubernetes cluster.

**Comment by juan131** [comment]
Hi @bmistrapau 

Could you please provide more information about: what issues did you find, what your tried so far, and what values did you modified when installing the chart? Thanks in advance.

**Comment by bmistrapau** [comment]
Hi @juan131,

I'm using bitnami redis chart version 14.1.1 with these values.yaml:

`master:
  persistence:
    enabled: false
replica:
  persistence:
    enabled: false
  preExecCmds:  |
    echo "" >> /opt/bitnami/redis/etc/replica.conf
    echo "replica-announce-ip $POD_IP" >> /opt/bitnami/redis/
  extraEnvVars:
    - name: "POD_IP"
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
sentinel:
  enabled: true`

I also have 2 different kubernetes clusters with istio sidecar injection enabled at namespace level. (k8s 1.20, istio 1.8). The istio is installed with multi-cluster, in multy-primary different network architecture (https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/)
So, I want to access the redis master from both k8s clusters. Istio in does not support in multi-cluster architecture headless services, but only Cluster IP services.
So, having a fix CluterIP service name for the master, would help a lot to access it from both clusters.

**Comment by juan131** [comment]
Hi @bmistrapau 

First of all, our charts are not designed to work with Istio. That said, they can be integrated with Istio since they can be extended adding custom sidecar containers, labels, annotations, etc.
I want to be clear on this because we don't test the integration with Istio in our pipeline and, therefore, we don't officially support it. As a consequence, we cannot guarantee that we will not break the compatibility with Istio in the future since we're not taking into account during the development process any possible consequence affecting this integration.

---

> So, I want to access the Redis master from both k8s clusters. Istio in does not support in multi-cluster architecture headless services, but only Cluster IP services.
> So, having a fix ClusterIP service name for the master, would help a lot to access it from both clusters.

Sticking to the point you brought up, this chart allows to configure the service type to use to access the Redis master node using the `master.service.type`, and you can also use `master.service.clusterIP` to choose the service Cluster IP. See:

- https://github.com/bitnami/charts/tree/master/bitnami/redis#redistm-master-configuration-parameters

When you install the chart with `replication` architecture, 3 services are created:

- A service that points to "master" nodes.
- A service that points to "replica" nodes.
- A headless service that points to every Redis node.

**Comment by usefree** [comment]
hello, from this long story i can not found a working solution. Is there some options to enable, or may be it is possible to create extra ingress/service in k8s and point it to sentinel port of redis pod?
Thanks!

**Comment by juan131** [comment]
Hi @usefree 

There's a sentinel service that's automatically created when `architecture=replication` and `sentinel.enabled=true`, see:

- https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/sentinel/service.yaml

You also have an "extraDeploy" parameter that allows you to add any custom manifest when you install the chart, see:

- https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml#L44

**Comment by arcanis** [comment]
@juan131 It's certainly a matter of being more familiar with K8s / Helm, but even with your lead I'm still not sure I understand. How can we connect to the sentinel service in a way that we don't have to care about their internal ips?

What I tried so far is to bind the port 26379 from the chart to my host (after enabling sentinel + setting the replication architecture), but when my client connects to it it gets returned the internal ips. Is it the wrong way to connect to the sentinel service? The only other option I see is to connect via 6379, but then I suspect it makes the replicas useless.

**Comment by juan131** [comment]
Hi @arcanis 

We would have to configure the IP and Port to be announced, see:

- https://redis.io/topics/sentinel#sentinel-docker-nat-and-possible-issues

But that something we don't support in this chart (yet). We have a task to work on this feature but we didn't find the required time to work on it. I'll try to raise its priority.

**Comment by jonathon2nd** [comment]
Would it be possible to add `HostPort` support to the chart?

**Comment by juan131** [comment]
Yes, we already support it in other charts such as Cassandra or Kiam, see the `hostNetwork` parameter at:

- https://github.com/bitnami/charts/tree/master/bitnami/cassandra/README.md
- https://github.com/bitnami/charts/blob/master/bitnami/kiam/README.md

Would that work for you?

**Comment by jonathon2nd** [comment]
I think we are going to do something different. I bet this would help others though. If you could set to use hostip and a series of hostports and if redis+sentinel were aware of them, this could work for some people for setting up redis sentinel which is externally available.

**Comment by juan131** [comment]
Hi @jonathon2nd 

Using the host IP/port doesn't scale on production environments where you actually have thousands of workloads running that may potentially require to be exposed outside the cluster. And, it's not also a good practice in terms of security since you're exposing ports on your K8s nodes which increase the attack surface for potential attackers.

**Comment by michaelgeorgeattard** [comment]
Hi, is there a known workaround for exposing a Redis cluster outside of Kubernetes and leveraging high-availability?

At the moment we cannot use the `redis-cluster` Bitnami Helm chart as we do not have access to `LoadBalancer` services (bare-metal solution).

**Comment by juan131** [comment]
Hi @michaelgeorgeattard 

I'm afraid that, at this very moment, this is a limitation we haven't solve yet. I'll try to do my best to increase the priority of the associated task so it's assigned to one of our engineers asap.

**Comment by juan131** [comment]
By the way, please check the solutions proposed in [this issue](https://github.com/bitnami/charts/issues/5424). They use a proxy to manage all the redirections, and it's a great a workaround for this problem.

**Comment by mikekuzak** [comment]
Hi, @Maelstrom96 @juan131 
I'm not quite sure I understand how this suppose to work really. I configured the nodePort but when trying to connect from outside using a Java app I'm getting hostnames which are not known outside the cluster. How is this suppose to work? 

Helm: 15.6.0
Redis: 6.2.6-debian-10-r46
K8s: v1.19.5

```
#https://github.com/helm/charts/blob/master/stable/redis/values-production.yaml

global: 
  redis:
    password: xxxxx

image:
  registry: docker.io
  repository: bitnami/redis
  tag: 6.2.6-debian-10-r46

architecture: replication

replica:
  persistence:
     enabled: false
  replicaCount: 3
  resources:
     requests:
     limits:
       memory: 4Gi
       cpu: 2000m  

sentinel:
   enabled: true
   service:
      type: NodePort
   image:
     tag: 6.2.6-debian-10-r46
   masterSet: master
   quorum: 2
   configuration: |-
     protected-mode no
   resources:
     requests:
       memory: 4Gi
       cpu: 2000m

commonConfiguration: |-  
  # Enable AOF https://redis.io/topics/persistence#append-only-file 
  appendonly no
  # Disable RDB persistence, AOF persistence already enabled.  
  save ""

## Sysctl InitContainer
## used to perform sysctl operation to modify Kernel settings (needed sometimes to avoid warnings)
# https://docs.bitnami.com/kubernetes/infrastructure/redis/administration/configure-kernel-settings/
sysctlImage:
  enabled: true
  mountHostSys: true
  command:
    - /bin/sh
    - -c
    - |-
      install_packages procps
      sysctl -w net.core.somaxconn=10000
```

Which service should be used to connect to the sentinels ? 

```
redis                   redis-cache                        NodePort       10.43.210.134   <none>                                                                                                                                                                         30001:30001/TCP,30000:30000/TCP,26379:30226/TCP,6379:30711/TCP               110m
redis                   redis-cache-headless               ClusterIP      None            <none>                                                                                                                                                                         6379/TCP,26379/TCP                                                           114m
redis                   redis-cache-node-0                 NodePort       10.43.60.131    <none>                                                                                                                                                                         30002:30002/TCP,30003:30003/TCP,26379:31865/TCP,6379:30268/TCP               110m
redis                   redis-cache-node-1                 NodePort       10.43.7.255     <none>                                                                                                                                                                         30004:30004/TCP,30005:30005/TCP,26379:31775/TCP,6379:30094/TCP               110m
redis                   redis-cache-node-2                 NodePort       10.43.53.58     <none>                                                                                                                                                                         30006:30006/TCP,30007:30007/TCP,26379:31003/TCP,6379:31633/TCP               110m
```
Here the test:
```
 public static void main( String[] args )
    {
        Config config = new Config();
        config.useSentinelServers()
              .addSentinelAddress("redis://10.128.202.101:30006")
              .addSentinelAddress("redis://10.128.202.102:30004")
              .addSentinelAddress("redis://10.128.202.103:30002")
              .setMasterName("master")
              .setPassword("xxxxx");


        RedissonClient redisson = Redisson.create(config);


        // perform operations

        // implements java.util.concurrent.ConcurrentMap
        RMap<String, String> map = redisson.getMap("simpleMap");
        map.put("mapKey", "This is a map value");

        String mapValue = map.get("mapKey");
        System.out.println("stored map value: " + mapValue);

        // implements java.util.concurrent.locks.Lock
        RLock lock = redisson.getLock("simpleLock");
        lock.lock();

        try {
           // do some actions
        } finally {
           lock.unlock();
        }

        redisson.shutdown();
    }
    ```
    
    Result:
    ```
    Exception in thread "main" org.redisson.client.RedisConnectionException: SENTINEL SENTINELS command returns empty result! Set checkSentinelsList = false to avoid this check.
	at org.redisson.connection.SentinelConnectionManager.<init>(SentinelConnectionManager.java:194)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:193)
	at org.redisson.Redisson.<init>(Redisson.java:67)
	at org.redisson.Redisson.create(Redisson.java:108)
	at redis.sentinel.Application.main(Application.java:22)
Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'redis-cache-node-2.redis' failed to resolve 'redis-cache-node-2.redis.mydomian.com' after 8 queries 
```

Unfortunately there is no good example or any documentation hint. Thanks for any guidance or advice.
