### ISSUE TITLE
[bitnami/ghost] Ghost account not generated by chart, webui shows inital setup flow

### ISSUE THREAD

**Issue by krangence** [bitnami/charts#4091]
**Which chart**:
ghost: 10.1.20

**Describe the bug**
Despite chart configuration set to create a ghost account, once deployed and you visit /ghost endpoint the initial setup flow / wizard is shown.

![](https://i.imgur.com/Nt6ZmAg.png)

**To Reproduce**
1. deploy chart with the following values: 
``` yaml
    ghostHost: blog.example.org
    ghostProtocol: https
    ghostPort: 443
    ghostUsername: johnsmith@example.com
    ghostPassword: password123
    ghostEmail: johnsmith@example.com
    ghostBlogTitle: JohnSmith
    service:
      type: ClusterIP
    ingress:
      enabled: true
      certManager: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/enable-global-auth: "false"
      hosts:
        - name: blog.example.com
          tls: true
          tlsSecret: ghost-tls
    global:
      storageClass: generic
    mariadb:
      rootUser:
        password: ""
      db:
        password: ""
      master:
        persistence:
          enabled: false
          accessMode: ReadWriteOnce
```
**Expected behavior**
As the username and password are specified, the /ghost endpoint should show the signin form as an account should already exist

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-19T09:16:25Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
