### ISSUE TITLE
mongodb: creating replicaset doesn't create any services beside the headless service when mongodb chart used as a dependency

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [bitnami/charts#4093]
I'm trying to create a replica set and access it from mongo-express , as per the docs creating replicaset will create a service per pod which is not happening with me. 

Here is my config:

```
mongodb:
  auth:
    rootPassword: password
    replicaSetKey: key1234567890
  architecture: replicaset
  arbiter:
    enabled: false
  replicaCount: 1
```

the result is only 1 service which is headless, means no access to it:
ecomm-mongodb-headless          ClusterIP   None             <none>        27017/TCP

any idea how to fix this?

**Comment by carrodher** [comment]
When `replicaset` is enabled you are going to only see an "internal" headless service that is going to create a hostname per pod. If you want to access MongoDB from outside the cluster you need to use the `externalAccess.enabled=true` and related parameters where a service per pod is created, please take a look at this section in the README: https://github.com/bitnami/charts/tree/master/bitnami/mongodb#replicaset-accessing-mongodb-nodes-from-outside-the-cluster

Apart from that, with `replicaCount: 1` only one pod is going to be deployed so only one service is expected. In the same way, when installing the chart you can see some notes with the instruction to access MongoDB from inside and outside the cluster depending on the parameters you are setting, you can also see those notes at any time once the chart is installed by running `helm get notes RELEASE_NAME`

**Comment by ahmed-adly-khalil** [comment]
@carrodher Thanks for replying to me. What i want is to access mongo from inside the cluster from mongo express while I'm using replicaset. The situation is that i'm running my application chart and using both mongo and mongo-express as an external dependency. I'm still failing to get mongo-express to connect to mongodb simply because i don't know where to point the connection between them and i don't want to use external access because in this case it's not external. 


Here is my setyp:

Chart.yaml -> this is my own application chart:
```
dependencies:
  ### MongoDB ### https://artifacthub.io/packages/helm/bitnami/mongodb
  - name: mongodb
    version: 9.2.5
    repository: https://charts.bitnami.com/bitnami
  ### MongoDB Express ### https://artifacthub.io/packages/helm/cowboysysop/mongo-express
  - name: mongo-express
    version: 1.3.1
    repository: https://cowboysysop.github.io/charts
```

Values.yaml
```
mongodb:
  replicaCount: 1
  auth:
    rootPassword: password
    replicaSetKey: key1234567890
  architecture: replicaset
  useStatefulSet: true
  arbiter:
    enabled: false
  service:
    type: LoadBalancer


mongo-express:
  mongodbServer: ecomm-mongodb # -> What to put here??? 
  mongodbEnableAdmin: true
  mongodbAdminUsername: root
  mongodbAdminPassword: password
```

Thank you very much
