### ISSUE TITLE
[bitnami/thanos] Ingress templating with ArgoCD adds a "---apiVersion" attribute

### ISSUE THREAD

**Issue by paulden** [bitnami/charts#4100]
**Which chart**:
bitnami/thanos in version 2.5.1

**Describe the bug**
Hello everyone, thanks for your work on this repository with great Helm charts!
I am using ArgoCD to deploy Thanos on a Kubernetes cluster with the Bitnami Helm Chart. I need to expose it via HTTP and GRPC so I enabled both ingress but it seems to be messing with the templating and fails to deploy either ingresses. As a result, I get this error: 

```
error validating data: ValidationError(Ingress): unknown field "---apiVersion" in io.k8s.api.extensions.v1beta1.Ingress
```

And the manifest found in ArgoCD:

```yaml
---
'---apiVersion': extensions/v1beta1
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: thanos
    argocd.argoproj.io/instance: thanos
    helm.sh/chart: thanos-2.5.1
  name: thanos-grpc
  namespace: monitoring
spec:
  rules:
  - host: thanos-grpc.local
    http:
      paths:
      - backend:
          serviceName: thanos-querier
          servicePort: grpc
        path: /
  - host: tools.mysubdomain.com
    http:
      paths:
      - backend:
          serviceName: thanos-querier
          servicePort: grpc
        path: /thanos-grpc
```

**To Reproduce**
1. Enable both GRPC and HTTP ingresses
2. Deploy chart on Kubernetes cluster using ArgoCD

**Expected behavior**
Both ingresses are up and running.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v3.3.4
```

- Output of `kubectl version`:

```
v1.17.9
```

**Additional context**

Here are the values I provide to my chart:

```yaml
existingObjstoreSecret: thanos-objstore-config
  querier:
    extraFlags:
      - "--web.external-prefix=thanos"
    dnsDiscovery:
      sidecarsService: thanos-sidecar-service
      sidecarsNamespace: monitoring
    ingress:
      enabled: true
      grpc:
        enabled: true
        extraHosts:
          - name: "tools.mysubdomain.com"
            path: "/thanos-grpc"
  storegateway:
    enabled: true
  compactor:
    enabled: true
```

- After cloning the Bitnami repository `helm template` outputs the expected manifest without the extra line `'---apiVersion'`.
- I dove into the ArgoCD source code to run tests and I found that templating happened as expected but I may be missing something.
- I figured it might come from the [ingress.yaml](https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/querier/ingress.yaml) with two documents in a single file but I can't seem to have it working. I tried adding and moving `---` around to split documents explicitly but I could not find a way to have it templated correctly by ArgoCD. **Splitting the `ingress.yaml` into two separate files `ingress-http.yaml` and `ingress-grpc.yaml` does work however** (besides, [Helm recommends avoiding multiple documents in a single file](https://helm.sh/docs/chart_template_guide/yaml_techniques/#embedding-multiple-documents-in-one-file) citing debug difficulties).

**Comment by paulden** [comment]
I found that actually, ArgoCD is running Helm 2 since `apiVersion` is `v1`, so it is running at `2.15.2` and I can now reproduce the templating issue running `helm template` with this specific version.

With the [Alpine Docker image 2.15.2](https://hub.docker.com/layers/alpine/helm/2.15.2/images/sha256-d1bc954505f48af51e0d5de1e2636e69bab09da41f105e403f7e91cef32f4242?context=explore):

```
helm template .
```

outputs among other manifests:

```yaml
---
# Source: thanos/templates/querier/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: release-name-thanos-querier
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-2.5.1
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
  annotations:
spec:
  rules:
    - host: thanos.local
      http:
        paths:
          - path: /
            backend:
              serviceName: release-name-thanos-querier
              servicePort: http
---apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: release-name-thanos-grpc
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-2.5.1
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
  annotations:
spec:
  rules:
    - host: thanos-grpc.local
      http:
        paths:
          - path: /
            backend:
              serviceName: release-name-thanos-querier
              servicePort: grpc
```

And there the `--apiVersion` is present.
