### ISSUE TITLE
[bitnami/thanos] querier and bucketweb ingress config

### ISSUE THREAD

**Issue by ghost** [bitnami/charts#4127]
**Which chart**:
Thanos, after update to version 2.4.0

**Describe the bug**
Not able to create querier and bucketweb ingress with tls config - [code](https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/querier/ingress.yaml#L34:L39)

**To Reproduce**
My config
```
querier:
  ingress:
    enabled: true
    hostname: thanos-${name}.${operational_dns_name}
    annotations:
      kubernetes.io/ingress.class: operational
      cert-manager.io/cluster-issuer: "letsencrypt-production"
```

**Expected behavior**
Creates ingress object with tls configuration block

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
Applying through ArgoCD 1.7.8
```

**Additional context**
kube-prometheus-stack is using this configuration. How should I configure this with this chart?
```
tls:
  - hosts:
      - alertmanager-${name}.${operational_dns_name}
    secretName: alertmanager-${name}.${operational_dns_name}-tls
```

**Comment by miguelaeh** [comment]
Hi @janlud ,
Are you providing the certificates into `querier.ingress.secrets`? https://github.com/bitnami/charts/blob/276d3279c45d5a822ced459226f65780ac1f7bfd/bitnami/thanos/values.yaml#L380
Also `querier.ingress.tls.enabled=true`

Can you share how are you deploying it?

**Comment by janlud** [comment]
Hi @miguelaeh,

I added `querier.ingress.tls.enabled=true` but it didn't help.
I want to use cert-manager so I don't think I need to add `secrets: []` right?
Before the update to chart 2.4.0 it was all working fine for me with the `tls:` part of the configuration. I have two levels of queriers and I was able to query through both of them from Grafana to Prometheus and the deployment method didn't change (Helm chart deployed with ArgoCD to the cluster).

This is the generated desired manifest in ArgoCD:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: operational
  labels:
    app.kubernetes.io/instance: aaa-bbb-ccc-ddd-thanos
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-2.5.3
  name: thanos-querier
  namespace: monitoring
spec:
  rules:
    - host: thanos-aaaaa.bbbbbb.xyz
      http:
        paths:
          - backend:
              serviceName: thanos-querier
              servicePort: http
            path: /
```

**Comment by janlud** [comment]
I think my problem is that this part of the config - https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/querier/ingress.yaml#L36:L39
Doesn't get rendered because I don't have secrets to add. How can I do this if I want to use cert-manager cert?

I also tried to add `cert-manager: true` without success.

Thanks!

**Comment by miguelaeh** [comment]
Hi @janlud ,
For certmanager this chart has the following options:
`bucketweb.ingress.certManager`
`querier.ingress.grpc.certManager`
`querier.ingress.certManager`

To configure the proper annotations for cert manager into that file you need to add `querier.ingress.certManager=true`. See https://github.com/bitnami/charts/blob/135c0e34f3f725a31f77be83484c994fbf03474b/bitnami/thanos/templates/querier/ingress.yaml#L8

**Comment by janlud** [comment]
thanks @miguelaeh, (the author of the issue is me, just was consolidating my accounts)

I added it and ended up with this
```
querier:
            ingress:
              enabled: true
              hostname: thanos-${name}.${operational_dns_name}
              certManager: true
              annotations:
                kubernetes.io/ingress.class: operational
            tls:
              enabled: true
```
so the manifest then looks like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: operational
    kubernetes.io/tls-acme: 'true'
  labels:
    app.kubernetes.io/instance: aaa-bbb-ccc-thanos
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-2.5.3
  name: thanos-querier
  namespace: monitoring
spec:
  rules:
    - host: thanos-aaa.bbbb.xyz
      http:
        paths:
          - backend:
              serviceName: thanos-querier
              servicePort: http
            path: /
```

Would you or someone else had a working example maybe? By looking at the chart it seems to me that if I leave the `{{- if .Values.querier.ingress.secrets }}` empty, it will never render the `tls:` part of the config. But I cannot add those because I don't want to use my own certificate (and also values.yaml says the same thing - `secrets` shouldn't be mandatory).

Also the grpc ingress is using `{{- if .Values.querier.ingress.grpc.tls }}` and not `{{- if .Values.querier.ingress.secrets }}` in the same place, is this maybe a bug in the chart?
https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/querier/ingress-grpc.yaml#L36
