### ISSUE TITLE
Autogeneration of the Chart documentation.

### ISSUE THREAD

**Issue by Cellebyte** [bitnami/charts#4142]
**Is your feature request related to a problem? Please describe.**
Every contributor needs to write a lot of documentation inside his chart.
I tried automating this, but the result was less then perfect.
I just want to start a discussion about that.

**Additional context**

The script used to generate the table can be found here.
[https://gist.github.com/Cellebyte/ec629603952a98be1d7dbcd9b7aac3f4](https://gist.github.com/Cellebyte/ec629603952a98be1d7dbcd9b7aac3f4)

## ouput
```md
# values.yaml
|                       Parameter                        |                                                                    Description                                                                     |                Default                |
|--------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------|
| rbac.create                                            | create specifies whether to install and use RBAC rules.                                                                                            | True                                  |
| psp.create                                             | create specifies whether to install Pod Security Policies.                                                                                         | False                                 |
| prometheusRule.enabled                                 |                                                                                                                                                    | False                                 |
| controller.image.registry                              |                                                                                                                                                    | docker.io                             |
| controller.image.repository                            |                                                                                                                                                    | bitnami/metallb-controller            |
| controller.image.tag                                   |                                                                                                                                                    | 0.9.3-debian-10-r156                  |
| controller.image.pullPolicy                            |                                                                                                                                                    | IfNotPresent                          |
| controller.rbac.create                                 | create specifies whether to install and use RBAC rules.                                                                                            | True                                  |
| controller.psp.create                                  | create specifies whether to install Pod Security Policies.                                                                                         | True                                  |
| controller.tolerations                                 |                                                                                                                                                    | []                                    |
| controller.podAffinityPreset                           |                                                                                                                                                    |                                       |
| controller.podAntiAffinityPreset                       |                                                                                                                                                    | soft                                  |
| controller.nodeAffinityPreset.type                     | Node affinity type Allowed values: soft, hard                                                                                                      |                                       |
| controller.nodeAffinityPreset.key                      | Node affinity type Allowed values: soft, hard                                                                                                      |                                       |
| controller.nodeAffinityPreset.values                   | Node affinity type Allowed values: soft, hard                                                                                                      | []                                    |
| controller.serviceAccount.create                       | Specifies whether a ServiceAccount should be created                                                                                               | True                                  |
| controller.serviceAccount.name                         | Specifies whether a ServiceAccount should be created                                                                                               |                                       |
| controller.securityContext.enabled                     |                                                                                                                                                    | True                                  |
| controller.securityContext.runAsNonRoot                |                                                                                                                                                    | True                                  |
| controller.securityContext.runAsUser                   |                                                                                                                                                    |                                  1001 |
| controller.securityContext.fsGroup                     |                                                                                                                                                    |                                  1001 |
| controller.securityContext.allowPrivilegeEscalation    |                                                                                                                                                    | False                                 |
| controller.securityContext.readOnlyRootFilesystem      |                                                                                                                                                    | True                                  |
| controller.securityContext.capabilities.drop           |                                                                                                                                                    | ['ALL']                               |
| controller.revisionHistoryLimit                        |                                                                                                                                                    |                                     3 |
| controller.terminationGracePeriodSeconds               |                                                                                                                                                    |                                     0 |
| controller.containerPort.metrics                       |                                                                                                                                                    |                                  7472 |
| controller.livenessProbe.enabled                       |                                                                                                                                                    | True                                  |
| controller.livenessProbe.failureThreshold              |                                                                                                                                                    |                                     3 |
| controller.livenessProbe.initialDelaySeconds           |                                                                                                                                                    |                                    10 |
| controller.livenessProbe.periodSeconds                 |                                                                                                                                                    |                                    10 |
| controller.livenessProbe.successThreshold              |                                                                                                                                                    |                                     1 |
| controller.livenessProbe.timeoutSeconds                |                                                                                                                                                    |                                     1 |
| controller.readinessProbe.enabled                      |                                                                                                                                                    | True                                  |
| controller.readinessProbe.failureThreshold             |                                                                                                                                                    |                                     3 |
| controller.readinessProbe.initialDelaySeconds          |                                                                                                                                                    |                                    10 |
| controller.readinessProbe.periodSeconds                |                                                                                                                                                    |                                    10 |
| controller.readinessProbe.successThreshold             |                                                                                                                                                    |                                     1 |
| controller.readinessProbe.timeoutSeconds               |                                                                                                                                                    |                                     1 |
| controller.prometheus.serviceMonitor.enabled           | Prometheus Operator service monitors  enable support for Prometheus Operator                                                                       | False                                 |
| controller.prometheus.serviceMonitor.jobLabel          | Prometheus Operator service monitors  enable support for Prometheus Operator                                                                       | app.kubernetes.io/name                |
| controller.prometheus.serviceMonitor.interval          | Prometheus Operator service monitors  enable support for Prometheus Operator                                                                       |                                       |
| controller.prometheus.serviceMonitor.metricRelabelings | Prometheus Operator service monitors  enable support for Prometheus Operator                                                                       | []                                    |
| controller.prometheus.serviceMonitor.relabelings       | Prometheus Operator service monitors  enable support for Prometheus Operator                                                                       | []                                    |
| speaker.image.registry                                 |                                                                                                                                                    | docker.io                             |
| speaker.image.repository                               |                                                                                                                                                    | bitnami/metallb-speaker               |
| speaker.image.tag                                      |                                                                                                                                                    | 0.9.3-debian-10-r166                  |
| speaker.image.pullPolicy                               |                                                                                                                                                    | IfNotPresent                          |
| speaker.rbac.create                                    | create specifies whether to install and use RBAC rules.                                                                                            | True                                  |
| speaker.psp.create                                     | create specifies whether to install Pod Security Policies.                                                                                         | True                                  |
| speaker.tolerations                                    |                                                                                                                                                    | []                                    |
| speaker.serviceAccount.create                          | Specifies whether a ServiceAccount should be created                                                                                               | True                                  |
| speaker.serviceAccount.name                            | Specifies whether a ServiceAccount should be created                                                                                               |                                       |
| speaker.daemonset.terminationGracePeriodSeconds        | Configure the grace time period for sig term ref: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/hook-handler-execution  |                                     2 |
| speaker.daemonset.hostPorts.metrics                    | Configure the grace time period for sig term ref: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/hook-handler-execution  |                                  7472 |
| speaker.securityContext.enabled                        |                                                                                                                                                    | True                                  |
| speaker.securityContext.runAsUser                      |                                                                                                                                                    |                                     0 |
| speaker.securityContext.allowPrivilegeEscalation       |                                                                                                                                                    | False                                 |
| speaker.securityContext.readOnlyRootFilesystem         |                                                                                                                                                    | True                                  |
| speaker.securityContext.capabilities.drop              |                                                                                                                                                    | ['ALL']                               |
| speaker.securityContext.capabilities.add               |                                                                                                                                                    | ['NET_ADMIN', 'NET_RAW', 'SYS_ADMIN'] |
| speaker.extraEnvVars                                   |                                                                                                                                                    | []                                    |
| speaker.livenessProbe.enabled                          |                                                                                                                                                    | True                                  |
| speaker.livenessProbe.failureThreshold                 |                                                                                                                                                    |                                     3 |
| speaker.livenessProbe.initialDelaySeconds              |                                                                                                                                                    |                                    10 |
| speaker.livenessProbe.periodSeconds                    |                                                                                                                                                    |                                    10 |
| speaker.livenessProbe.successThreshold                 |                                                                                                                                                    |                                     1 |
| speaker.livenessProbe.timeoutSeconds                   |                                                                                                                                                    |                                     1 |
| speaker.readinessProbe.enabled                         |                                                                                                                                                    | True                                  |
| speaker.readinessProbe.failureThreshold                |                                                                                                                                                    |                                     3 |
| speaker.readinessProbe.initialDelaySeconds             |                                                                                                                                                    |                                    10 |
| speaker.readinessProbe.periodSeconds                   |                                                                                                                                                    |                                    10 |
| speaker.readinessProbe.successThreshold                |                                                                                                                                                    |                                     1 |
| speaker.readinessProbe.timeoutSeconds                  |                                                                                                                                                    |                                     1 |
| speaker.prometheus.serviceMonitor.enabled              | Prometheus Operator service monitors  enable support for Prometheus Operator                                                                       | False                                 |
| speaker.prometheus.serviceMonitor.jobLabel             | Prometheus Operator service monitors  enable support for Prometheus Operator                                                                       | app.kubernetes.io/name                |
| speaker.prometheus.serviceMonitor.interval             | Prometheus Operator service monitors  enable support for Prometheus Operator                                                                       |                                       |
| speaker.prometheus.serviceMonitor.metricRelabelings    | Prometheus Operator service monitors  enable support for Prometheus Operator                                                                       | []                                    |
| speaker.prometheus.serviceMonitor.relabelings          | Prometheus Operator service monitors  enable support for Prometheus Operator                                                                       | []                                    |

```

## source
```yaml
## Default values for metallb.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName

## To configure MetalLB, you must specify ONE of the following two
## options.
#
## existingConfigMap specifies the name of an externally-defined
## ConfigMap to use as the configuration. Helm will not manage the
## contents of this ConfigMap, it is your responsibility to create it.
#
# existingConfigMap: metallb-config
#
## configInline specifies MetalLB's configuration directly, in yaml
## format. When configInline is used, Helm manages MetalLB's
## configuration ConfigMap as part of the release, and
## existingConfigMap is ignored.
## Refer to https://metallb.universe.tf/configuration/ for
## available options.
#
configInline: {}

## String to partially override metallb.fullname include (will maintain the release name)
##
# nameOverride:

## String to fully override metallb.fullname template
##
# fullnameOverride:

## RBAC creation for controller and speaker
##
rbac:
  ## create specifies whether to install and use RBAC rules.
  ## 
  create: true

## PSP creation for controller and speaker
##
psp:
  # create specifies whether to install Pod Security Policies.
  create: false

# Prometheus Operator alertmanager alerts
prometheusRule:
  enabled: false

## Add labels to all the deployed resources
##
commonLabels: {}

## Add annotations to all the deployed resources
##
commonAnnotations: {}

## Metallb Controller deployment.
## ref: https://hub.docker.com/r/bitnami/metallb-controller/tags
controller:
  image:
    registry: docker.io
    repository: bitnami/metallb-controller
    tag: 0.9.3-debian-10-r156
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName

  ## If global .Values.rbac.create is disabled no rbac is created.
  ## This value is then meaningless
  ## Defines if the controller rbac should be created.
  ##
  rbac:
    ## create specifies whether to install and use RBAC rules.
    ## 
    create: true

  ## If global .Values.psp.create is disabled no psp is created.
  ## This value is then meaningless
  ## Defines if the controller psp should be created.
  ##
  psp:
    ## create specifies whether to install Pod Security Policies.
    ##
    create: true

  ## Controller container resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}
    ## We usually recommend not to specify default resources and to leave this as a conscious
    ## choice for the user. This also increases chances charts run on environments with little
    ## resources, such as Minikube. If you do want to specify resources, uncomment the following
    ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 100Mi
    # requests:
    #   memory: 25Mi
    #   cpu: 25m
  ## Node labels for pod assignment
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}

  ## Tolerations for pod assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []

  ## Affinity for pod assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  affinity: {}

  ## Pod annotations
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  podAnnotations: {}

  ## Additional pod labels
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  ##
  podLabels: {}

  ## Pod affinity preset
  ## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  ## Allowed values: soft, hard
  ##
  podAffinityPreset: ""

  ## Pod anti-affinity preset
  ## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  ## Allowed values: soft, hard
  ##
  podAntiAffinityPreset: soft

  ## Node affinity preset
  ## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
  ## Allowed values: soft, hard
  ##
  nodeAffinityPreset:
    ## Node affinity type
    ## Allowed values: soft, hard
    type: ""
    ## Node label key to match
    ## E.g.
    ## key: "kubernetes.io/e2e-az-name"
    ##
    key: ""
    ## Node label values to match
    ## E.g.
    ## values:
    ##   - e2e-az1
    ##   - e2e-az2
    ##
    values: []

  serviceAccount:
    # Specifies whether a ServiceAccount should be created
    create: true
    # The name of the ServiceAccount to use.  If not set and create is
    # true, a name is generated using the fullname template
    name: ""


  ## Pod securityContext
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  ##
  securityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
    fsGroup: 1001
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
      - ALL

  ## Configure the revisionHistoryLimit of the Controller deployment
  ## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#revision-history-limit
  ##
  revisionHistoryLimit: 3

  ## Configure the grace time period for sig term
  ## ref: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution
  ##
  terminationGracePeriodSeconds: 0

  ## Configures the ports the MetalLB Controller listens on for metrics
  ##
  containerPort:
    metrics: 7472

  ## Liveness and readiness probe values
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
  ##
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1

  prometheus:
    ## Prometheus Operator service monitors
    ##
    serviceMonitor:
      ## enable support for Prometheus Operator
      ##
      enabled: false
      ## Job label for scrape target
      ##
      jobLabel: "app.kubernetes.io/name"
      ## Scrape interval. If not set, the Prometheus default scrape interval is used.
      ##
      interval: ""
      metricRelabelings: []
      relabelings: []

## Metallb Speaker daemonset.
## ref: https://hub.docker.com/r/bitnami/metallb-speaker/tags
speaker:
  image:
    registry: docker.io
    repository: bitnami/metallb-speaker
    tag: 0.9.3-debian-10-r166
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName

  ## If global .Values.rbac.create is disabled no rbac is created.
  ## This value is then meaningless
  ## Defines if the speaker rbac should be created.
  ##
  rbac:
    ## create specifies whether to install and use RBAC rules.
    ## 
    create: true

  ## If global .Values.psp.create is disabled no psp is created.
  ## This value is then meaningless
  ## Defines if the speaker psp should be created.
  ##
  psp:
    ## create specifies whether to install Pod Security Policies.
    ##
    create: true

  ## Speaker container resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}
    ## We usually recommend not to specify default resources and to leave this as a conscious
    ## choice for the user. This also increases chances charts run on environments with little
    ## resources, such as Minikube. If you do want to specify resources, uncomment the following
    ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 100Mi
    # requests:
    #   memory: 25Mi
    #   cpu: 25m
  ## Node labels for pod assignment
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}

  ## Tolerations for pod assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []

  ## Affinity for pod assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  affinity: {}

  ## Pod annotations
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  podAnnotations: {}

  ## Additional pod labels
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  ##
  podLabels: {}

  serviceAccount:
    # Specifies whether a ServiceAccount should be created
    create: true
    # The name of the ServiceAccount to use.  If not set and create is
    # true, a name is generated using the fullname template
    name: ""

  ## Daemonset configuration
  ##
  daemonset:
    ## Configure the grace time period for sig term
    ## ref: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution
    ##
    terminationGracePeriodSeconds: 2
    ## HTTP Metrics Endpoint
    ##
    hostPorts:
      metrics: 7472

  ## Defines a secret to use outside of the auto generated
  ## Default: {{ randAlphaNum 256 | b64enc | quote }}
  ## The auto generated has secretName: {{ "common.names.fullname" }}-memberlist
  ## and secretKey: secretkey
  ##
  # secretName:
  # secretKey:

  ## Pod securityContext
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  ##
  securityContext:
    enabled: true
    runAsUser: 0
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
      - ALL
      add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN

  ## An array to add extra env vars
  ## For example:
  ## extraEnvVars:
  ##  - name: MY_ENV_VAR
  ##    value: env_var_value
  ##
  extraEnvVars: []

  ## Liveness and readiness probe values
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
  ##
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1

  prometheus:
    ## Prometheus Operator service monitors
    ##
    serviceMonitor:
      ## enable support for Prometheus Operator
      ##
      enabled: false
      ## Job label for scrape target
      ##
      jobLabel: "app.kubernetes.io/name"
      ## Scrape interval. If not set, the Prometheus default scrape interval is used.
      ##
      interval: ""
      metricRelabelings: []
      relabelings: []

```
