### ISSUE TITLE
[bitnami/etcd] If podAnnotations are provided prometheus annotations are injected even if metrics are disabled.

### ISSUE THREAD

**Issue by GeckoSplinter** [bitnami/charts#4145]
**Which chart**:
ETCD 4.12.X

**Describe the bug**
If a podAnnotation is provided the the check for metrics activation is skipped and prometheus podAnnotations are provided anyway.

**To Reproduce**

values.yaml
```yaml
podAnnotations:
  test: "test"

metrics:
  enabled: false
```
```
helm template etcd-test . -f ./values-test.yaml --dry-run
```

the templating result in StatefulSet is  :
```yaml
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etcd
        helm.sh/chart: etcd-4.12.1
        app.kubernetes.io/instance: etcd-test
        app.kubernetes.io/managed-by: Helm
      annotations:
        test: test
        prometheus.io/port: "2379"
        prometheus.io/scrape: "true"
```

**Expected behavior**
If `metrics.enabled` is set to `false` metrics should be disabled
or if `metrics.serviceMonitor.enabled` is set to `true` prometheus annotations should not be injected.

```yaml
podAnnotations:
  test: "test"
```
or 
```yaml
podAnnotations:
  test: "test"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

should give 
```yaml
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etcd
        helm.sh/chart: etcd-4.12.1
        app.kubernetes.io/instance: etcd-test
        app.kubernetes.io/managed-by: Helm
      annotations:
        test: test
```

**Additional context**
Opening a PR to fix that.
