### ISSUE TITLE
[bitnami/harbor] Intermittently cannot log into the web page after upgrading to chart v8.x

### ISSUE THREAD

**Issue by ajchiarello** [bitnami/charts#4148]
**Which chart**:
Harbor v8.1.1

**Describe the bug**
After installing this version of the chart, I cannot log into the web page reliably. Sometimes, if I redeploy all the containers, the login works for a while before stopping again. No error is presented - the login just hangs forever.

**To Reproduce**

1. Install the chart
2. Attempt to login

**Expected behavior**
Logins to work consistently.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I have been running chart version 7.1.1 for some time with no problems, with the same configuration.

**Comment by miguelaeh** [comment]
Hi @ajchiarello ,
Could you share the exact command you are using to install the chart?

**Comment by ajchiarello** [comment]
Hi @miguelaeh - I'm installing it using the terraform helm provider. I've also tried the install directly via the helm cli, with no change in behavior. Here is the values file I am applying, with sensitive information redacted: 

```
chartmuseum:
  replicas: 3
  resources:
    limits:
      cpu: 3000m
      memory: 200Mi
    requests:
      cpu: 250m
      memory: 30Mi

clair:
  enabled: false

containerSecurityContext:
  runAsUser: 1001
  runAsNonRoot: true

core:
  csrfKey: <REDACTED>
  replicas: 3
  resources:
    limits:
      cpu: 4000m
      memory: 1000Mi
    requests:
      cpu: 250m
      memory: 30Mi
  secret: <REDACTED>
  secretKey: <REDACTED>

externalURL: https://<REDACTED>

harborAdminPassword: <REDACTED>

internalTLS:
  enabled: true

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1000"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1000"
  hosts:
    core: <REDACTED>
    notary: <REDACTED>

jobservice:
  podAnnotations:
    backup.velero.io/backup-volumes: job-logs
  replicas: 3
  resources:
    limits:
      cpu: 300m
      memory: 1500Mi
    requests:
      cpu: 30m
      memory: 250Mi

notary:
  server:
    resources:
      limits:
        cpu: 50m
        memory: 300Mi
      requests:
        cpu: 5m
        memory: 30Mi
  signer:
    resources:
      limits:
        cpu: 50m
        memory: 300Mi
      requests:
        cpu: 5m
        memory: 30Mi

persistence:
  persistentVolumeClaim:
    chartmuseum:
      accessMode: ReadWriteMany
      existingClaim: harbor-chartmuseum
      size: 5Gi
      storageClass: "-"
    jobservice:
      accessMode: ReadWriteMany
      existingClaim: harbor-jobservice
      size: 5Gi
      storageClass: "-"
    registry:
      accessMode: ReadWriteMany
      existingClaim: harbor-registry
      size: 350Gi
      storageClass: "-"

podSecurityContext:
  fsGroup: 1001

portal:
  replicas: 3
  resources:
    limits:
      cpu: 3000m
      memory: 400Mi
    requests:
      cpu: 300m
      memory: 40Mi

postgresql:
  master:
    podAnnotations:
      backup.velero.io/backup-volumes: data
  postgresqlExtendedConf:
    max_connections: 1024
  replication:
    enabled: true
  resources:
    limits:
      cpu: 2000m
      memory: 4096Mi
  slave:
    podAnnotations:
      backup.velero.io/backup-volumes: data
  volumePermissions:
    enabled: true

redis:
  cluster:
    enabled: true
  master:
    persistence:
      enabled: false
    resources:
      limits:
        cpu: 1000m
        memory: 2560Mi
      requests:
        cpu: 100m
        memory: 256Mi
  slave:
    persistence:
      enabled: false
    resources:
      limits:
        cpu: 1000m
        memory: 2560Mi
      requests:
        cpu: 100m
        memory: 256Mi

registry:
  controller:
    resources:
      limits:
        cpu: 250m
        memory: 1500Mi
      requests:
        cpu: 25m
        memory: 150Mi
  registry:
    resources:
      limits:
        cpu: 2000m
        memory: 250Mi
      requests:
        cpu: 200m
        memory: 25Mi
  relativeurls: true
  replicas: 3

service:
  tls:
    existingSecret: <REDACTED>
    notaryExistingSecret: <REDACTED>
```
