### ISSUE TITLE
[bitnami/grafana] Failed to start container - Are you trying to mount a directory onto a file (or vice-versa)? 

### ISSUE THREAD

**Issue by marangiop** [bitnami/charts#4149]
**Which chart**:
Grafana chart version 3.4.5 

**Describe the bug**
I am having problems with deploying the Grafana chart. This is the error I get after installing with helm:

```
Events:
  Type     Reason     Age                From                                        Message
  ----     ------     ----               ----                                        -------
  Normal   Scheduled  <unknown>          default-scheduler                           Successfully assigned default/grafana-cc9b47498-cdxvj to onekube-ip-10-38-3-77.localdomain
  Normal   Pulling    2m34s              kubelet, onekube-ip-10-38-3-77.localdomain  Pulling image "docker.io/bitnami/grafana:7.2.2-debian-10-r0"
  Normal   Pulled     91s                kubelet, onekube-ip-10-38-3-77.localdomain  Successfully pulled image "docker.io/bitnami/grafana:7.2.2-debian-10-r0"
  Warning  Failed     55s                kubelet, onekube-ip-10-38-3-77.localdomain  Error: failed to start container "grafana": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/5eb57e6b-5064-4602-b40e-92134d5077ca/volume-subpaths/grafana-ini/grafana/0\\\" to rootfs \\\"/var/lib/docker/overlay2/ad8c0652342f3aba27095144dc9f8d62d30dd702aee4c2518633d07b07ff64d5/merged\\\" at \\\"/var/lib/docker/overlay2/ad8c0652342f3aba27095144dc9f8d62d30dd702aee4c2518633d07b07ff64d5/merged/opt/bitnami/grafana/conf/grafana.ini\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

```

**To Reproduce**

pv.yaml 
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-5
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/grafana/data-persistence5/"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-4
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
     path: "/root/grafana/data-persistence4/"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
        path: "/root/grafana/data-persistence3/"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/grafana/data-persistence2/"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/grafana/data-persistence1/"
    type: DirectoryOrCreate

```
grafana-configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini-config
data:
  grafana.ini: |-
    [server]
    domain = grafana.grapevine-project.eu
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
    serve_from_sub_path = true
```
datasource.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: sample-grafana-datasource
  labels:
      grafana_datasource: "1"
type: Opaque
stringData:
  datasource.yaml: |-
     apiVersion: 1
     datasources:
     - name: Prometheus-server
       type: prometheus
       access: proxy
       orgId: 1
       url: http://prometheus-service:9090
       isDefault: true
```
    
grafana-values.yaml
```
ingress:
  enabled: True
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - name: some.domain.name.eu
      paths: ["/grafana(/|$)(.*)"]
datasources:
  secretName: sample-grafana-datasource
metrics:
  enabled: true
config:
  useGrafanaIniFile: true
  grafanaIniConfigMap: grafana-cm
persistence:
  enabled: false
```

Helm command is 
`helm install -n grafana bitnami/grafana -f grafana-values.yaml`

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by FraPazGal** [comment]
Hi @marangiop,

Thanks for using our chart! From what I see, the error should be caused by the `grafana.ini` file been wrongly mounted, but I couldn't reproduce the issue. The steps I followed were:

```
$ kubectl apply -f grafana-configmap.yaml
$ helm install grafana bitnami/grafana -f values.yaml
$ kubectl get pods

NAME                      READY   STATUS    RESTARTS   AGE
grafana-769f98979-pmb8d   1/1     Running   0          85s

$ kubectl exec grafana-769f98979-pmb8d --stdin --tty -- bash
```

```
I have no name!@grafana-5ff559bc5c-b44xv:/opt/bitnami/grafana/conf$ ls
defaults.ini  grafana.ini  ldap.toml  ldap_multiple.toml  provisioning
I have no name!@grafana-5ff559bc5c-b44xv:/opt/bitnami/grafana/conf$ cat grafana.ini
[server]
domain = grafana.grapevine-project.eu
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
serve_from_sub_path = true
```

I saw that you are installing your chart in the grafana namespace, are you also deploying `grafana-configmap.yaml` in the same namespace? Also, in your `grafana-values.yaml` the name of the configMap in `grafanaIniConfigMap` is not the same from the one you defined in the configMap.

**Comment by marangiop** [comment]
Hi @FraPazGal ,

Thank you for the reply. 

I have fixed the `configmap.yaml` file so it contains the correct configmap being referenced within the `values.yaml` file, but creating the configmap in a namespace called "grafana" gave me issues (pod was not able to find the confimap), so I did not specify the namespace

configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-cm
data:
  grafana.ini: |-
    [server]
    domain = grafana.grapevine-project.eu
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
    serve_from_sub_path = true
```

values.yaml 
```
ingress:
  enabled: True
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - name: grafana.grapevine-project.eu
      paths: ["/grafana(/|$)(.*)"]
datasources:
  secretName: sample-grafana-datasource
metrics:
  enabled: true
config:
  useGrafanaIniFile: true
  grafanaIniConfigMap: grafana-cm
persistence:
  enabled: false
```

kubectl get pods
```
NAME                                                READY   STATUS    RESTARTS   AGE
grafana-7ddfb9878b-bl877                            1/1     Running   0          4m35s
```
kubectl describe po  grafana-7ddfb9878b-bl877
```
Events:
  Type     Reason     Age                    From                                        Message
  ----     ------     ----                   ----                                        -------
  Normal   Scheduled  <unknown>              default-scheduler                           Successfully assigned default/grafana-7ddfb9878b-bl877 to onekube-ip-10-38-3-77.localdomain
  Normal   Pulled     10m                    kubelet, onekube-ip-10-38-3-77.localdomain  Container image "docker.io/bitnami/grafana:7.2.2-debian-10-r0" already present on machine
  Normal   Created    10m                    kubelet, onekube-ip-10-38-3-77.localdomain  Created container grafana
  Normal   Started    10m                    kubelet, onekube-ip-10-38-3-77.localdomain  Started container grafana
  Warning  Unhealthy  9m47s (x2 over 9m57s)  kubelet, onekube-ip-10-38-3-77.localdomain  Readiness probe failed: Get http://10.244.4.29:3000/: dial tcp 10.244.4.29:3000: connect: connection refused

```

kubectl describe ingress grafana
```
Name:             grafana
Namespace:        default
Address:          10.38.3.76
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host                          Path  Backends
  ----                          ----  --------
  grafana.grapevine-project.eu
                                /grafana(/|$)(.*)   grafana:http (10.244.4.29:3000)
Annotations:                    nginx.ingress.kubernetes.io/rewrite-target: /$1
Events:
  Type    Reason  Age   From                      Message
  ----    ------  ----  ----                      -------
  Normal  CREATE  12m   nginx-ingress-controller  Ingress default/grafana
  Normal  UPDATE  11m   nginx-ingress-controller  Ingress default/grafana

```

kubectl exec grafana-769f98979-pmb8d --stdin --tty -- bash
```
I have no name!@grafana-7ddfb9878b-bl877:/opt/bitnami/grafana$ cd /opt/bitnami/grafana/conf/
I have no name!@grafana-7ddfb9878b-bl877:/opt/bitnami/grafana/conf$ ls
defaults.ini  grafana.ini  ldap.toml  ldap_multiple.toml  provisioning
I have no name!@grafana-7ddfb9878b-bl877:/opt/bitnami/grafana/conf$ cat grafana.ini
[server]
domain = some.domain.name.eu
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
serve_from_sub_path = true
```

The problem is that I am still getting a `404 Not Found nginx/1.19.2` page at `some.domain.name.eu`. Do you see anything wrong with my `values.yaml` file? I tried to play around with the ingress section of the `values.yaml ` file (while leaving the rest of the file untouched=, but still, not able to fix the error with the page.

```
ingress:
  enabled: True
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 300m
```

```
ingress:
  enabled: True
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
```

**Comment by marangiop** [comment]
@FraPazGal ?

**Comment by FraPazGal** [comment]
Hi @marangiop,

I don't see anything that stands out that really stands out. Could you try to use `"/"` as the ingress path to rule out an error on the regex?

**Comment by marangiop** [comment]
Hi @FraPazGal,

I tried with the following values.yaml file, but no luck

```

ingress:
  enabled: True
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - name: some.domain.name.eu
      paths: ["/"]
datasources:
  secretName: sample-grafana-datasource
metrics:
  enabled: true
config:
  useGrafanaIniFile: true
  grafanaIniConfigMap: grafana-cm
persistence:
  enabled: false
```
