### ISSUE TITLE
[bitnami/nginx] extraDeploy not working after it changed to "range"

### ISSUE THREAD

**Issue by osca** [bitnami/charts#4177]
**Which chart**:
bitnami/nginx (7.1.5)

**Describe the bug**
After merging pull request #4161 our values.yaml is not working anymore. "extraDeploy" changed from "if" to "range" and we get following error:

```
Error: UPGRADE FAILED: template: nginx/templates/extra-list.yaml:1:17: executing "nginx/templates/extra-list.yaml" at <.Values.extraDeploy>: range can't iterate over - apiVersion: v1
##[error]Error: UPGRADE FAILED: template: nginx/templates/extra-list.yaml:1:17: executing "nginx/templates/extra-list.yaml" at <.Values.extraDeploy>: range can't iterate over - apiVersion: v1
  data:
    config.json: '{"apiUrl": "https://some.api.io"}'
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: {{ include "common.names.fullname" . }}-config
```

**To Reproduce**
values.yaml:
```
...
extraDeploy: |-
  - apiVersion: v1
    data:
      config.json: '{"apiUrl": "https://some.api.io"}'
    kind: ConfigMap
    metadata:
      creationTimestamp: null
      name: {{ include "common.names.fullname" . }}-config
...
```

**Expected behavior**
In pull request #4161 it is said, that no changes of values.yaml need to be done.

**Additional information**
I tried to adapt the extraDeploy in our values.yaml as described in bitnami/kong's example, but with the same result.

**Comment by miguelaeh** [comment]
Hi @osca ,
This needs to be an array, deleting the `|-` should work:
```
...
extraDeploy:
  - apiVersion: v1
    data:
      config.json: '{"apiUrl": "https://some.api.io"}'
    kind: ConfigMap
    metadata:
      creationTimestamp: null
      name: {{ include "common.names.fullname" . }}-config
...

```

**Comment by osca** [comment]
Hey @miguelaeh,

I tried this, but now it stucks at the inclusion of fullname:

```
...
name: {{ include "common.names.fullname" . }}
...
```

with:

```
Error: failed to parse values-staging.yaml: error converting YAML to JSON: yaml: line 18: did not find expected key
```

**Comment by juan131** [comment]
Hi @osca 

Could you try with the values below?

```
extraDeploy:
  - apiVersion: v1
    data:
      config.json: '{"apiUrl": "https://some.api.io"}'
    kind: ConfigMap
    metadata:
      creationTimestamp: null
      name: "{{ include \"common.names.fullname\" . }}-config"
```
