### ISSUE TITLE
[bitnami/rabbitmq ] Rabbitmq pods stuck in CrashLoopBackOff state.

### ISSUE THREAD

**Issue by yolossn** [bitnami/charts#4179]
**Which chart**:
The name (and version) of the affected chart
chart: `rabbitmq`
Version: `7.6.9`
**Describe the bug**
Pod stuck in `CrashLoopBackOff` state.
`Logs:`
```
 09:45:50.60 
 09:45:50.60 Welcome to the Bitnami rabbitmq container
 09:45:50.61 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
 09:45:50.61 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
 09:45:50.61 
 09:45:50.61 INFO  ==> ** Starting RabbitMQ setup **
 09:45:50.63 INFO  ==> Validating settings in RABBITMQ_* env vars..
 09:45:50.64 INFO  ==> Initializing RabbitMQ...
 09:45:50.68 INFO  ==> Starting RabbitMQ in background...
 09:47:42.76 ERROR ==> Couldn't start RabbitMQ in background.
```
Diagnostic info:

```
DIAGNOSTICS
===========

attempted to contact: ['rabbit@rabbitmq-0.rabbitmq-headless.rabbitmq.svc.cluster.local']

rabbit@rabbitmq-0.rabbitmq-headless.rabbitmq.svc.cluster.local:
  * connected to epmd (port 4369) on rabbitmq-0.rabbitmq-headless.rabbitmq.svc.cluster.local
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on rabbitmq-0.rabbitmq-headless.rabbitmq.svc.cluster.local
  * suggestion: start the node

Current node details:
 * node name: 'rabbitmqcli-692-rabbit@rabbitmq-0.rabbitmq-headless.rabbitmq.svc.cluster.local'
 * effective user's home directory: /opt/bitnami/rabbitmq/.rabbitmq
 * Erlang cookie hash: hhYoDs/ehXLl026jrmnWJQ==

```

**To Reproduce**

> helm install rabbitmq -f values.yaml bitnami/rabbitmq

`values.yaml`
```yaml
plugins: "rabbitmq_management"

auth:
  username: admin
  password: secretpassword
  erlangCookie: 1lOBkQT8vBdA4hfoGM8MkgzfEjA27chE

persistence:
  size: 2Gi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    additionalLabels:
      release: monitoring
```

**Expected behavior**
Pods running 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
