### ISSUE TITLE
HOWTO extraEnvVars

### ISSUE THREAD

**Issue by santacruz123** [bitnami/charts#4184]
`In order to pass custom environment variables use the extraEnvVars property. Using extraEnvVars with KAFKA_CFG_ is the preferred and simplest way to add custom Kafka parameters not otherwise specified in this chart.`

It's not clear how to use it from documentation

This way:
values.yaml
```
extraEnvVars:
  - message.max.bytes=5485760
  - max.request.size=5485760
  - max.partition.fetch.bytes=5485760
```
or this way
```
extraEnvVars:
  - KAFKA_CFG_MESSAGE_MAX_BYTES: 5485760
  - KAFKA_CFG_MAX_REQUEST_SIZE: 5485760
  - KAFKA_CFG_MAX_PARTITION_FETCH_BYTES: 5485760
```

does not work any way
