### ISSUE TITLE
[bitnami / rabbitmq] not taking password from existingPasswordSecret

### ISSUE THREAD

**Issue by InsOpDe** [bitnami/charts#4203]
**Which chart**:
```
 rabbitmq
 version: 7.7.1
 repository: https://charts.bitnami.com/bitnami
```

**Describe the bug**
Cannot login after pod startup. The provided password seems not to be used

**To Reproduce**
run it with following values
```yaml
fullnameOverride: rabbitmq
auth:
  username: rabbitmq
  existingPasswordSecret: rabbitmq-secret
```
Secret
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  rabbitmq-password: {{ randAlphaNum 10 | b64enc | quote }}
```

Ssh to pod:
`kubectl exec -it rabbitmq-0 bash`

Get pass
```
$ env | grep PASS
RABBITMQ_PASSWORD=FmA7La6EPB
```

Authenticate with user and pass
```
$ rabbitmqctl authenticate_user rabbitmq FmA7La6EPB
Authenticating user "rabbitmq" ...
Error:
Error: failed to authenticate user "rabbitmq"
user 'rabbitmq' - invalid credentials
```

**Expected behavior**

```
$ rabbitmqctl authenticate_user rabbitmq FmA7La6EPB
Authenticating user "rabbitmq" ...
Success
```

If I change the password like so
```
$ change_password rabbitmq FmA7La6EPB
Changing password for user "rabbitmq" ...
```
it works

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
