### ISSUE TITLE
[bitnami/mysql] can't evaluate field pullSecrets in type interface {}

### ISSUE THREAD

**Issue by GeKasap** [bitnami/charts#4221]
**Which chart**:
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: mysql
    version: 6.14.11

**Describe the bug**
Helm operator is failing to deploy mysql release, due to a syntax error in chart.
More specifically I get the following error in both master-statefulset and slave-statefulset (when replication is enabled).

```
{"caller":"release.go:316","component":"release","error":"installation failed: template: mysql/templates/master-statefulset.yaml:26:4: executing \"mysql/templates/master-statefulset.yaml\" at \u003cinclude \"mysql.imagePullSecrets\" .\u003e: error calling include: template: mysql/templates/_helpers.tpl:159:48: executing \"mysql.imagePullSecrets\" at \u003c.Values.metrics.image.pullSecrets\u003e: can't evaluate field pullSecrets in type interface {}","helmVersion":"v3","phase":"install",.......}
```
I have checked the _helpers.tpl and I have two comments:
* I think that lines 159-169 should be removed as are the same with 147-158 + 170
* Duplication is not a serious issue. IMHO, the `end` line 158 should be deleted (as it closes the initial if statement and the `else if` of line 159 is without respective `if`) and another one to be added after line 171.

IMHO the second bullet is causing the issue, but maybe I am wrong. Please elaborate.

**To Reproduce**
```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: local-db
  namespace: db
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: local-db
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: mysql
    version: 6.14.11
  values:
    image:
      registry: internal-registry.example.com
      repository: bitnami/mysql
      tag: 8.0
    replication:
      enabled: false
    clusterDomain: my-db.local
    existingSecret: my-secret
    metrics:
      enabled: true
    db:
      user: my_user
      name: my_db
```

**Expected behavior**
Mysql DB to be deployed

**Version of Helm and Kubernetes**:

- Output of `helm version`:

Helm v3 deployed with helm operator 1.2.0

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.20", GitCommit:"0ac5f81eecab42bff5ef74f18b99d8896ba7b89b", GitTreeState:"clean", BuildDate:"2020-09-09T00:48:20Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by marcosbc** [comment]
Hi @GeKasap, I don't think lines 159-169 should be removed. If we were to indent those lines for easier readability:

```yaml
{{- if .Values.global }}
  {{- if .Values.global.imagePullSecrets }}
    imagePullSecrets:
    {{- range .Values.global.imagePullSecrets }}
      - name: {{ . }}
    {{- end }}
  {{- else if or .Values.image.pullSecrets .Values.metrics.image.pullSecrets .Values.volumePermissions.image.pullSecrets }}
    imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- range .Values.metrics.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- range .Values.volumePermissions.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
  {{- end -}}
{{- else if or .Values.image.pullSecrets .Values.metrics.image.pullSecrets .Values.volumePermissions.image.pullSecrets }}
  imagePullSecrets:
  {{- range .Values.image.pullSecrets }}
    - name: {{ . }}
  {{- end }}
  {{- range .Values.metrics.image.pullSecrets }}
    - name: {{ . }}
  {{- end }}
  {{- range .Values.volumePermissions.image.pullSecrets }}
    - name: {{ . }}
  {{- end }}
{{- end -}}
```

You can see that the first block refers to global secrets:

```yaml
{{- if .Values.global }}
  {{- if .Values.global.imagePullSecrets }}
    imagePullSecrets:
    {{- range .Values.global.imagePullSecrets }}
      - name: {{ . }}
    {{- end }}
  {{- else if or .Values.image.pullSecrets .Values.metrics.image.pullSecrets .Values.volumePermissions.image.pullSecrets }}
    imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- range .Values.metrics.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- range .Values.volumePermissions.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
  {{- end -}}
```

And the second block to image-specific secrets:

```
{{- else if or .Values.image.pullSecrets .Values.metrics.image.pullSecrets .Values.volumePermissions.image.pullSecrets }}
  imagePullSecrets:
  {{- range .Values.image.pullSecrets }}
    - name: {{ . }}
  {{- end }}
  {{- range .Values.metrics.image.pullSecrets }}
    - name: {{ . }}
  {{- end }}
  {{- range .Values.volumePermissions.image.pullSecrets }}
    - name: {{ . }}
  {{- end }}
{{- end -}}
```

I would say there is an issue with respect to how you are deploying your chart. Could you show us the deployment command (or the "image" sections in your values.yaml)?

**Comment by GeKasap** [comment]
Hello.
Thanks for your response and I am sorry for late response from my side.
Ok, I see, you had to expand it like this, because `and` is not working, as it should be and you have to break the condition to two lines 
`{{- if .Values.global }}
  {{- if .Values.global.imagePullSecrets }}
`
I am not deploying the chart manually ( I will try to do it and post the results), but I am doing it using a Helm Release, so FluxCD is actually failing. I have posted the HelmRelease contents in the original post.

**Comment by javsalgar** [comment]
Hi,

I don't have experience with this way of deploying the charts, but it seems that one of the sections is being converted to null, as if it weren't using the default values. Does it have a debug mode or something that shows more verbosity?

**Comment by GeKasap** [comment]
Ok, I found the issue.
It is weird that manual installation works with the below values
```yaml
clusterDomain: test-db.local
db:
  user: myuser
  name: mydb
existingSecret: my-db-secret
```

But it was failing with the above error, when trying to deploy it via helm. I read more carefully the code, and realized that it is using `.Values.metrics.image.pullSecrets` but this is not defined anywhere. So, I had to define it in my HelmRelease, even if this is an empty value '**pullSecrets: []**'. Though, it is weird that it is not failing in the other two checks `.Values.image.pullSecrets .Values.metrics.image.pullSecrets` and  `.Values.volumePermissions.image.pullSecrets`.
Note, I have used the latest chart version.
So, my final HelmRelease is:
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: local-db
  namespace: db
spec:
  releaseName: local-db
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: mysql
    version: 7.0.0
  values:
    image:
      registry: internal-registry.example.com
      repository: bitnami/mysql
      tag: 8.0.22
    clusterDomain: my-db.local
    existingSecret: my-secret
    metrics:
      enabled: true
      image:
        repository: bitnami/mysqld-exporter
        pullSecrets: []
    db:
      user: myuser
      name: mydb
```

The chart is now deployed successfully from fluxcd.
Thanks for your support
