### ISSUE TITLE
[bitnami/postgresql] FATAL:  data directory "/data/pgdata" has wrong ownership

### ISSUE THREAD

**Issue by Skallwar** [bitnami/charts#4228]
**Which chart**:
postgres
version: 9.8.11

**Describe the bug**
When deploying postgres chart with an [official image](https://hub.docker.com/_/postgres) (arm64v8) I get a ``FATAL:  data directory "/data/pgdata" has wrong ownership`` error.

**To Reproduce**
postgresql.values.yml
``` yml
image:
  registry: docker.io
  repository: postgres
  tag: 13.0

  pullPolicy: IfNotPresent

  debug: true

volumePermissions:
  enabled: true
  image:
    registry: docker.io
    repository: alpine
    tag: 3.12.1

    pullPolicy: IfNotPresent

  securityContext:
    runAsUser: 0

securityContext:
  enabled: true
  runAsUser: 999
  fsGroup: 999

containerSecurityContext:
  enabled: true
  runAsUser: 999

postgresqlDataDir: /data/pgdata
 
(... default ...)

persistence:
 enabled: true
 mountPath: /data/
 existingClaim: "storage"
 accessMode: ReadWriteMany
 size: "10Gi"
 
(... default ...)
```

Then run ``helm install postgresql bitnami/postgresql --values postgresql.values.yml``

**Expected behavior**
Should not output ``FATAL:  data directory "/data/pgdata" has wrong ownership``

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```

- Output of `k3s kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3+k3s1", GitCommit:"974ad30be7b7b15f695d88e46ffa96a4d43b2370", GitTreeState:"clean", BuildDate:"2020-10-16T00:18:50Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3+k3s1", GitCommit:"974ad30be7b7b15f695d88e46ffa96a4d43b2370", GitTreeState:"clean", BuildDate:"2020-10-16T00:18:50Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/arm64"}
```

**Additional context**
NOTES:
 - I used ``runUser: 999`` because [this](https://github.com/helm/charts/issues/19132#issuecomment-561374227) used to work. Default value (1001) did not work either
 - ``postgresqlDataDir`` and ``persistence.mountPath`` come from [this](https://docs.bitnami.com/kubernetes/infrastructure/postgresql/get-started/differences-docker-image/)
