### ISSUE TITLE
prometheus rules not taken into account

### ISSUE THREAD

**Issue by guillaume1987** [bitnami/charts#4253]
**Which chart**:
bitnami/mongodb v9.3.1

**Describe the bug**
The prometheus rules added in the values.yaml file are not taken into account.

**To Reproduce**

1. In values.yaml file:
```
  prometheusRule:
    enabled: false
    additionalLabels:
      release: monitoring
    namespace: monitoring
    rules:
    - alert: MongodbReplicationLag
      expr: avg(mongodb_mongod_replset_member_optime_date{state="PRIMARY"}) - avg(mongodb_mongod_replset_member_optime_date{state="SECONDARY"}) > 10
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: MongoDB replication lag
        description: Mongodb replication lag is more than 10s
```
2. helm upgrade mongodb bitnami/mongodb -f mongodb/values.yml
```
coalesce.go:196: warning: cannot overwrite table with non table for rules (map[])
coalesce.go:196: warning: cannot overwrite table with non table for rules (map[])
```
... normal helm deployment

**Expected behavior**
A PrometheusRules resource should be created with all the rules defined in it.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
A possible reason could come from the fact that metrics.prometheusRule.rules is expecting a dictionary in the template instead of a list of dictionary.

**Comment by carrodher** [comment]
Are you enabling the metrics and the Prometheus rules? You should add something like
```yaml
metrics:
  enabled: true
  prometheusRule:
    enabled: true
```
and then the rest of parameters. If not, this condition is not going to be true and the object is not going to be deployed https://github.com/bitnami/charts/blob/d90a33d2262692a1876047ae503afbae1b803a3a/bitnami/mongodb/templates/prometheusrule.yaml#L1

Once added the above parameters, you can see if the object is deployed by running
```console
$ helm template mongodb . -f my-values.yaml -s templates/prometheusrule.yaml
---
# Source: mongodb/templates/prometheusrule.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mongodb
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-9.3.1
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    release: monitoring
spec:
  groups:
    - alert: MongodbReplicationLag
      annotations:
        description: Mongodb replication lag is more than 10s
        summary: MongoDB replication lag
      expr: avg(mongodb_mongod_replset_member_optime_date{state="PRIMARY"}) - avg(mongodb_mongod_replset_member_optime_date{state="SECONDARY"})
        > 10
      for: 5m
      labels:
        severity: critical
```

**Comment by carrodher** [comment]
That is how the template is created right now, I mean everything under the `rule:` section in the _values.yaml_ is what it's going to appear under the `groups:` section in the template. Something similar happens with `additionalLabels:`, those labels placed in that section in the _values.yaml_ are going to appears under the `labels:` section in the template, but without the `additionalLabels:` header.

But you're right, checking the [official documentation](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/), it seems `rules:` should be placed under `groups:` once rendered the template. I just applied those changes:

```diff
@ bitnami/mongodb/templates/prometheusrule.yaml:13 @ metadata:
    {{- end }}
spec:
  groups:
+   rules:
-   {{- include "common.tplvalues.render" (dict "value" .Values.metrics.prometheusRule.rules "context" $) | nindent 4 }}
+     {{- include "common.tplvalues.render" (dict "value" .Values.metrics.prometheusRule.rules "context" $) | nindent 4 }}
{{- end }}
```
testing those changes locally, this is the template generated:
```console
$ helm template mongodb . -f my-values.yaml -s templates/prometheusrule.yaml
---
# Source: mongodb/templates/prometheusrule.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mongodb
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.0.0
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    release: monitoring
spec:
  groups:
    rules:
    - alert: MongodbReplicationLag
      annotations:
        description: Mongodb replication lag is more than 10s
        summary: MongoDB replication lag
      expr: avg(mongodb_mongod_replset_member_optime_date{state="PRIMARY"}) - avg(mongodb_mongod_replset_member_optime_date{state="SECONDARY"})
        > 10
      for: 5m
      labels:
```

Would you like to give a try to the above solution? If you have the chart repo cloned locally you only need to add the above changes to _templates/prometheusrule.yaml_ and run `helm install mongodb . -f my-values.yaml`. If this solution work for you, you can create a PR. If not, I can do it, but I would like to check if that approach solves your issue.

**Comment by guillaume1987** [comment]
Almost there, we are just missing a "-" before the _rules_ field:
`error: error validating "mongodb/prometheusrule.yml": error validating data: ValidationError(PrometheusRule.spec.groups): invalid type for com.coreos.monitoring.v1.PrometheusRule.spec.groups: got "map", expected "array"; if you choose to ignore these errors, turn validation off with --validate=false`

**Comment by carrodher** [comment]
🤦 You're right, I used the official doc example where the `-` is not in `rules:` but in `name:`, I will send a PR with the changes

**Comment by carrodher** [comment]
With the changes in the above PR, now the result is
```console
$ helm template mongodb . -f my-values.yaml -s templates/prometheusrule.yaml
# Source: mongodb/templates/prometheusrule.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mongodb
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.0.0
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    release: monitoring
spec:
  groups:
  - rules:
    - alert: MongodbReplicationLag
      annotations:
        description: Mongodb replication lag is more than 10s
        summary: MongoDB replication lag
      expr: avg(mongodb_mongod_replset_member_optime_date{state="PRIMARY"}) - avg(mongodb_mongod_replset_member_optime_date{state="SECONDARY"})
        > 10
      for: 5m
      labels:
        severity: critical
```

**Comment by guillaume1987** [comment]
Sry, I didn't know, but the "name" field is also required: 
`error: error validating "mongodb/prometheusrule.yml": error validating data: ValidationError(PrometheusRule.spec.groups[0]): missing required field "name" in com.coreos.monitoring.v1.PrometheusRule.spec.groups; if you choose to ignore these errors, turn validation off with --validate=false`

**Comment by carrodher** [comment]
Ok, so the previous approach can work fine, but you need to add the `name:` as part of the rule in the values:
```yaml
metrics:
  enabled: true
  prometheusRule:
    enabled: true
    additionalLabels:
      release: monitoring
    namespace: monitoring
    rules:
    - name: rule1
      rules:
      - alert: MongodbReplicationLag
        expr: avg(mongodb_mongod_replset_member_optime_date{state="PRIMARY"}) - avg(mongodb_mongod_replset_member_optime_date{state="SECONDARY"}) > 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: MongoDB replication lag
          description: Mongodb replication lag is more than 10s
    - name: rule2
      rules:
      - alert: HighRequestLatency
        expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High request latency
```
With that example I am creating two rules in the values, then it is rendered in the following way:
```console
$ helm template mongodb . -f my-values.yaml -s templates/prometheusrule.yaml
# Source: mongodb/templates/prometheusrule.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mongodb
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.0.1
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    release: monitoring
spec:
  groups:
    - name: rule1
      rules:
      - alert: MongodbReplicationLag
        annotations:
          description: Mongodb replication lag is more than 10s
          summary: MongoDB replication lag
        expr: avg(mongodb_mongod_replset_member_optime_date{state="PRIMARY"}) - avg(mongodb_mongod_replset_member_optime_date{state="SECONDARY"})
          > 10
        for: 5m
        labels:
          severity: critical
    - name: rule2
      rules:
      - alert: HighRequestLatency
        annotations:
          summary: High request latency
        expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
        for: 10m
        labels:
          severity: page
```

I will update the PR by adding this example as documentation, but the template shouldn't be modified
