### ISSUE TITLE
[bitnami/phpmyadmin] HTTP 502 after completed import

### ISSUE THREAD

**Issue by thannaske** [bitnami/charts#4308]
**Which chart**:
bitnami/phpmyadmin-6.5.4

**Describe the bug**
HTTP 502 error is thrown right after a completed import of a pretty standard 1 MB sql file, although the import has been completed successfully.

**To Reproduce**

1. Install the chart together with a default MySQL or MariaDB chart
2. Log in to phpmyadmin (externally, exposed via default nginx-ingress)
3. Create a new empty database
4. Try to import a sql-file that creates a table and a few records
5. Instead of a redirection back to the table's content with a success message, a HTTP 502 error is shown
6. After clicking "Back" in your browser everything is fine again and the records have been imported correctly

**Expected behavior**
The redirection should not end in a HTTP 502 but rather show a success message.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.15.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"archive", BuildDate:"2020-10-16T20:58:56Z", GoVersion:"go1.15.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
- values.yaml:

```
db:
  host: mysql
  port: 3306
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  enabled: true
  hosts:
  - name: REDACTED
    tls: true
    tlsSecret: REDACTED-tls
extraEnvVars:
  - name: PHP_MEMORY_LIMIT
    value: "512M"
  - name: PHP_POST_MAX_SIZE
    value: "200M"
  - name: PHP_UPLOAD_MAX_FILESIZE
    value: "200M"
  - name: PHP_EXPOSE_PHP
    value: "no"
```
The addition of the `extraEnvVars` didn't help to resolve the issue. 

```
$ kubectl get ingresses pma-staging-phpmyadmin -o jsonpath={.metadata.annotations}
{"cert-manager.io/cluster-issuer":"letsencrypt-prod","ingress.kubernetes.io/rewrite-target":"/","meta.helm.sh/release-name":"pma-staging","meta.helm.sh/release-namespace":"default","nginx.ingress.kubernetes.io/proxy-body-size":"128m","nginx.ingress.kubernetes.io/proxy-max-temp-file-size":"1024m","nginx.ingress.kubernetes.io/proxy-read-timeout":"120","nginx.ingress.kubernetes.io/proxy-send-timeout":"120","nginx.ingress.kubernetes.io/rewrite-target":"/"}           
```
Limits have been raised at ingress-level, too.
