### ISSUE TITLE
existing secret name for ingress tls (primary host)

### ISSUE THREAD

**Issue by ashokspeelyaal** [bitnami/charts#4342]
**Which chart**:
keycloak. 0.1.2

**Is your feature request related to a problem? Please describe.**
Currently it is not possible to give existing secret name in ingress.secrets

**Describe the solution you'd like**
Is it possible to include an option to provide existing secret name?  Not in extra hosts, I mean for the primary hostname.  
I like to manage secrets cluster wise, especially with wild card certificates, used in multiple context. It is easier and efficient to refer to existing secret name instead of copying and pasting certificate and key for every need of deployment. 

**Describe alternatives you've considered**

**Additional context**
When I try to add external secret name. I get error. 

` cannot be imported into the current release: invalid ownership metadata; annotation validation error: key \"meta.helm.sh/release-name\" must equal `

**Comment by javsalgar** [comment]
Hi,

I'm not sure if I understood the issue. From what I see here:


```
    {{- if .Values.ingress.tls }}
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
    {{- end }}
```

You could have a secret that already contains the tls certificate that you are looking for as long as it is called <hostname>-tls. Wouldn't that work for your case?

**Comment by ashokspeelyaal** [comment]
@javsalgar  No that is not working I get an error as it looks for the same release name. 

`cannot be imported into the current release: invalid ownership metadata; annotation validation error: key \"meta.helm.sh/release-name\" must equal`

**Comment by juan131** [comment]
Hi @ashokspeelyaal 

In theory, you should be able to use `ingress.ExtraTls` use an existing secret. See: 

Parameter | Description | Default
-- | -- | --
ingress.extraTls[0].hosts[0] | TLS configuration for additional hostnames to be covered | nil
ingress.extraTls[0].secretName | TLS configuration for additional hostnames to be covered | nil

```yaml
ingress:
  enabled: true
  hostname: a.b.c
  extraTls:
    - hosts:
         - a.b.c
      secretName: MY_EXISTING_SECRET
```

The Ingress rule would like like this:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
  namespace: default
  labels:
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-1.0.1
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: keycloak
spec:
  rules:
    - host: a.b.c
      http:
        paths:
          - path: /
            backend:
              serviceName: keycloak
              servicePort: http
  tls:
    - hosts:
      - a.b.c
      secretName: MY_EXISTING_SECRET
```
