### ISSUE TITLE
[bitnami/thanos] inconsistent caching configuration in values.yaml

### ISSUE THREAD

**Issue by mhulscher** [bitnami/charts#4344]
**Which chart**:

bitnami/thanos

**Is your feature request related to a problem? Please describe.**

Recently the query-frontend component has been added to the thanos helm-chart. The query-frontend supports caching query-range results in memcache or in memory. This configuration can be passed in the `values.yaml` file at `queryFrontend.config`.

However, other components that consume configmaps for cache configuration are configured in a different way. Whereas the query caching configuration lives under the `queryFrontend` key, that's not true for the following settings:

| key | desc |
|---|---|
| `objstoreConfig` | rightfully at top-level because it is shared by multiple components (at least storegateway and compactor)
| `indexCacheConfig` | lives at the top-level but is specific to the storegateway 
| `bucketCacheConfig` | lives at the top-level but is specific to the storegateway

Additionally, the next release of thanos seems to support a 2nd caching configuration for the query-frontend component; caching of labels: https://github.com/thanos-io/thanos/pull/3315 . This would make the current key at `queryFrontend.config` confusing. Am I configuring the query-range result cache or the labels cache?

**Describe the solution you'd like**

I am curious to know if there has already been discussions regarding this topic.

I can see at least two options to make the caching configurations more consistent.

1. Move all caching configuration to the top-level of the `values.yaml` and use specific names, for example:
```yaml
indexCacheConfig:
  foo: bar

queryRangeResultCacheConfig:
  baz: qux
```

2. Move all caching configuration under their respective component and use specific key names, for example
```yaml
storegateway:
  indexCacheConfig:
    foo: bar

  bucketCacheConfig:
    baz: qux

queryFrontend:
  queryRangeResultCacheConfig:
    foo: bar

  LabelsResponseCacheConfig:
    baz: qux

```

Regardless of what would happen, this will likely result in a backwards incompatible change in the format of the `values.yaml` file.

If there's a preferred direction then I am willing to help author a PR.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A
