### ISSUE TITLE
[bitnami/keycloak] nil pointer evaluating interface {}.fullnameOverride

### ISSUE THREAD

**Issue by Gearme** [bitnami/charts#4355]
**Which chart**:
keycloak v0.1.2

**Describe the bug**
Attempting to install from this chart returns:
```Error: template: keycloak/templates/_helpers.tpl:8:14: executing "keycloak.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride```

**To Reproduce**
Attempt to install keycloak on the specified Helm and Kubernetes versions managed by Rancher.

**Expected behavior**
Installation without problems evaluating [_helpers.tpl](https://github.com/bitnami/charts/blob/master/bitnami/keycloak/templates/_helpers.tpl).

**Version of Helm and Kubernetes**:
Helm v2.16.8-rancher1
Kubernetes (K3s) v1.18.9+k3s1

**Additional context**
At first glance possibly related to [this Helm issue](https://github.com/helm/helm/issues/8026).
Possibly a new issue introduced in [b7a5f54](https://github.com/bitnami/charts/commit/b7a5f543c261cf519f011ff3e62d0f2b2f055f12) a week ago with [_helpers.tpl](https://github.com/bitnami/charts/blob/master/bitnami/keycloak/templates/_helpers.tpl).

**Comment by miguelaeh** [comment]
Hi @Gearme ,
Could you share the exact command you are using to install the Helm Chart please?

**Comment by Gearme** [comment]
Sure:
```
$ helm install --namespace=entw --timeout=10m0s --values=/home/shell/helm/values-keycloak-0.1.2.yaml --version=0.1.2 --wait=true keycloak /home/shell/helm/keycloak-0.1.2.tgz 
Error: template: keycloak/templates/_helpers.tpl:8:14: executing "keycloak.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride 
```
The values.yaml does not include a `fullnameOverride` key.

**Comment by miguelaeh** [comment]
Hi @Gearme ,
Could you share the values too please? I am not able to get the error. Have you tried with Helm 3? Helm 2 reached its end of live.

**Comment by Gearme** [comment]
After some trial and error I was able to narrow the problem down to my extraHosts in the ingress section, so I'll forego sending the entire yaml:

```
ingress:
  annotations: {}
  certManager: false
  enabled: true
  extraHosts:
    - name: project0.example.org
      path: /auth
    - name: project1.example.org
      path: /auth
    - name: project2.example.org
      path: /auth
    - name: project3.example.org
      path: /auth
  extraTls: []
  hostname: auth.example.org
  secrets: []
  tls: false
```
