### ISSUE TITLE
[bitnami/kong] Bad indentation in extraVolumes

### ISSUE THREAD

**Issue by alesanmed** [bitnami/charts#4356]
**Which chart**:
bitnami/kong

**Describe the bug**
In the [deployment](https://github.com/bitnami/charts/blob/master/bitnami/kong/templates/deployment.yaml) line 346 the indentation of extraVolumes content is set to 6, but the other elements of the array has an indentation of 8, causing an invalid yaml:

```yaml
      volumes:
        - name: health
          configMap:
            name: kong-scripts
            defaultMode: 0755
      - configMap:
          name: run-script
        name: run-script
```

**To Reproduce**

1. Add something to the ExtraVolumes variable
2. Compile the templates with `heml template <release_name> bitnami/kong -f values.yaml --debug --dry-run`
3. Inspect the deployment template

**Expected behavior**
Should generate a valid yaml

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
