### ISSUE TITLE
MediaWiki + Traefik 2.3.2 (bad gateway - GET / HTTP/1.1" 301)

### ISSUE THREAD

**Issue by KlugmannM** [bitnami/charts#4360]
Hello,

I tried to install on a VPS via docker-compose Mediawiki. The reverse proxy is Traefik which works with Nextcloud;Portainer without restrictions. Based on your template I have adapted the docker-compose.yml.

```
bitnami-docker-mediawiki 1.34.2-debian-10-r5 release
docker-compose version 1.25.4
traefik version v2.3.2
VPS Debian 10
```
```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_mediawiki
      - MARIADB_DATABASE=bitnami_mediawiki
    volumes:
      - '/opt/containers/mediawiki/mariadb_data:/bitnami/mariadb'
    networks:
      - default
  mediawiki:
    image: 'docker.io/bitnami/mediawiki:1-debian-10'
    environment:
      - MEDIAWIKI_DATABASE_HOST=mariadb
      - MEDIAWIKI_DATABASE_PORT_NUMBER=3306
      - MEDIAWIKI_DATABASE_USER=bn_mediawiki
      - MEDIAWIKI_DATABASE_NAME=bitnami_mediawiki
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/opt/containers/mediawiki/mediawiki_data:/bitnami/mediawiki'
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mediawiki.entrypoints=http"
      - "traefik.http.routers.mediawiki.rule=Host(`####.eu`)"
      - "traefik.http.middlewares.mediawiki-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.mediawiki.middlewares=mediawiki-https-redirect"
      - "traefik.http.routers.mediawiki-secure.entrypoints=https"
      - "traefik.http.routers.mediawiki-secure.rule=Host(`####.eu`)"
      - "traefik.http.routers.mediawiki-secure.tls=true"
      - "traefik.http.routers.mediawiki-secure.tls.certresolver=http"
      - "traefik.http.routers.mediawiki-secure.service=mediawiki"
      - "traefik.http.services.mediawiki.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - default
      - proxy
networks:
  proxy:
    external: true
```
So far everything could be installed without any problems, the containers run smoothly according to the logs.
If I now go to the given URL there is always badgateway.
[log_mediawiki](https://github.com/bitnami/charts/files/5538180/log_mediawiki.txt)

So when I change Port=80 to "traefik.http.services.mediawiki.loadbalancer.server.port=8080" i get the follwing

[log_Port8080_mediawiki.txt](https://github.com/bitnami/charts/files/5538210/log_Port8080_mediawiki.txt)

Do you have ideas or suggestions for a solution. Would be very grateful! I can't see the forest for the trees anymore.

**Comment by miguelaeh** [comment]
Hi @KlugmannM ,
Could you describe your scenario please? 
IF you are trying to access Mediwiki from the host where you deployed the containers have in mind you you will need to map a port in the docker-compose file. Adding a section like:
```
ports:
   80:8080
   443:8443
```

**Comment by KlugmannM** [comment]
I had assumed that ports 8080 and 8443 were the default ports of the Mediawiki container.
In my opinion the task of Traefik as a reverse proxy is to route via Port80/Port443 to the ports of the respective container (Mediawiki) or others if they are in the same network. Therefore, docker-compose.yml should not describe ports (80/443) - Traefik will do that for you. Correct me if I am wrong.

My scenario:

CloudServer/VPS:
- Debian 10
- Connection via SSH/Terminal

Entry point:
```
**docker-compose.yml**
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./data/dynamic_conf.yml:/dynamic_conf.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.####.eu`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=##user:PW##"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.####.eu`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=http"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "providers.file.filename=/dynamic_conf.yml"

networks:
  proxy:
    external: true
```

```
**dynamic_conf.yml**
tls:
  options:
    default:
      minVersion: VersionTLS12

      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256

      curvePreferences:
        - CurveP521
        - CurveP384

      sniStrict: true

http:
  middlewares:
    secHeaders:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        sslRedirect: true
        #HSTS Configuration
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
```

```
**traefik.yml**
api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/dynamic_conf.yml"

certificatesResolvers:
  http:
    acme:
      email: test@example.com
      storage: acme.json
      httpChallenge:
        entryPoint: http
```

Container via Docker
- Nextcloud
- Portainer
- Traefik
- Mediawiki
```
CONTAINER ID        IMAGE                            COMMAND                  CREATED              STATUS              PORTS                                      NAMES
565105b6a46c        bitnami/mediawiki:1-debian-10    "/opt/bitnami/script…"   About a minute ago   Up About a minute   8080/tcp, 8443/tcp                         mediawiki_mediawiki_1
7d9e22690e5a        bitnami/mariadb:10.3-debian-10   "/opt/bitnami/script…"   48 minutes ago       Up 48 minutes       3306/tcp                                   mediawiki_mariadb_1
35d57ef4b00a        nextcloud                        "/entrypoint.sh apac…"   4 days ago           Up 4 days           80/tcp                                     nextcloud-app
9a6bfc64d532        redis:alpine                     "docker-entrypoint.s…"   4 days ago           Up 4 days           6379/tcp                                   nextcloud-redis
85023ef9b6ad        mariadb                          "docker-entrypoint.s…"   4 days ago           Up 4 days           3306/tcp                                   nextcloud-db
b829bf97a3c3        traefik:latest                   "/entrypoint.sh trae…"   6 days ago           Up 4 days           0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   traefik
754c4cc8d31c        portainer/portainer:latest       "/portainer"             6 days ago           Up 6 days           9000/tcp          
```                         portainer

The Mediawiki setup is the same as described above.

Best regards.
