### ISSUE TITLE
[bitnami/nginx] unable to deply when using value-defined secrets

### ISSUE THREAD

**Issue by tristanlins** [bitnami/charts#4394]
**Which chart**

<details>
  <summary>`helm show chart bitnami/nginx`</summary>

```
annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 1.19.4
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: Chart for the nginx server
home: https://github.com/bitnami/charts/tree/master/bitnami/nginx
icon: https://bitnami.com/assets/stacks/nginx/img/nginx-stack-220x234.png
keywords:
- nginx
- http
- web
- www
- reverse proxy
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: nginx
sources:
- https://github.com/bitnami/bitnami-docker-nginx
- http://www.nginx.org
version: 8.0.0
```

</details>

**Describe the bug**
This looks like the same as in #3885

**To Reproduce**

`nginx.yaml`
```yaml
ingress:
  enabled: true
  hostname: test.localdomain
  tls: true
  secrets:
    - name: test.localdomain-tls
      key: |
        -----BEGIN PRIVATE KEY-----
        ...
      certificate: |
        -----BEGIN CERTIFICATE-----
        ...
```

```shell
$ helm template nginx bitnami/nginx --namespace nginx --values nginx.yaml
Error: template: nginx/templates/tls-secrets.yaml:8:14: executing "nginx/templates/tls-secrets.yaml" at <include "common.labels.standard" .>: error calling include: template: nginx/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: nginx/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```

The error occurs only when `secrets` is defined.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3+k3s3", GitCommit:"0e4fbfefe1dd8734756dfa4f9ab4fc89665cece4", GitTreeState:"clean", BuildDate:"2020-11-13T07:19:02Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
