### ISSUE TITLE
[bitnami/wordpress] Cannot use custom configmap for php.ini

### ISSUE THREAD

**Issue by EvgeniGordeev** [bitnami/charts#4398]
**[bitnami/wordpress]**:
`9.9.3`

**Describe the bug**
Cannot use custom configmap to modify /opt/bitnami/php/conf/php.ini. 

```
Error executing 'postInstallation': EROFS: read-only file system, open '/opt/bitnami/php/conf/php.ini'
```

**To Reproduce**

1. Following the suggestion to modify php.ini with custom configmap https://github.com/bitnami/charts/issues/3757#issuecomment-698197535
2. Create custom configmap: 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-php-config
data:
  php.ini: |
    upload_max_filesize = 6040M
    post_max_size = 6040M
```
3. Use `extraVolumes` and `extraVolumeMounts` to override php.ini: 

```yaml
  extraVolumeMounts:
    - name: wordpress-php-config
      subPath: php.ini
      mountPath: /opt/bitnami/php/etc/php.ini
  extraVolumes:
    - name: wordpress-php-config
      configMap:
        defaultMode: 436 # tried different modes, doesn't help
        name: wordpress-php-config
```
4. See error `Error executing 'postInstallation': EROFS: read-only file system, open '/opt/bitnami/php/conf/php.ini'`

**Expected behavior**
php.ini can be customized.

**Version of Helm and Kubernetes**:

```bash

~ % helm version
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"dirty", GoVersion:"go1.15.3"}

~ % kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}```
