### ISSUE TITLE
[bitnami/rabbitmq] networkpolicy's `from` definition uses old labels

### ISSUE THREAD

**Issue by zerkms** [bitnami/charts#4400]
**Which chart**:
rabbitmq v8.0.3

**Describe the bug**
At the moment it's defined as

```yaml
        - podSelector:
            matchLabels:
              app: {{ template "rabbitmq.name" . }}
              release: {{ .Release.Name }}
```

should be 

```yaml
app.kubernetes.io/name: ...
app.kubernetes.io/instance: ...
```

**To Reproduce**
Check
https://github.com/bitnami/charts/blob/cfe550523c25cda89dfb5b4d52e3b6fc8eaed070/bitnami/rabbitmq/templates/networkpolicy.yaml#L24-L27
and
https://github.com/bitnami/charts/blob/cfe550523c25cda89dfb5b4d52e3b6fc8eaed070/bitnami/rabbitmq/templates/statefulset.yaml#L20

**Expected behavior**
Labels should match (otherwise no traffic would be allowed)

**Version of Helm and Kubernetes**:
N/a

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**
