### ISSUE TITLE
[bitnami/rabbitmq] LivenessProbe   and ReadinessProbe errored: rpc error: code = DeadlineExceeded desc = failed to exec in container: timeout 20s exceeded: context deadline exceeded

### ISSUE THREAD

**Issue by yuzujoe** [bitnami/charts#4404]
**Which chart**:
rabbitmq v3.8.5-debian-10-r38

**Describe the bug**
I wanted to use rabbitmq in an OSS called reportportal、I installed rabbitmq via helm chart and found the following
Both readiness and liveness probes will time out

install this doc
https://github.com/reportportal/kubernetes/tree/master/reportportal/v5#5-rabbitmq-installation

```
$ kubectl describe pod rabbitmq-0

 Warning  Unhealthy  3m20s (x2 over 6m52s)  kubelet, ip-172-20-23-244.ap-northeast-1.compute.internal  Readiness probe errored: rpc error: code = DeadlineExceeded desc = failed to exec in container: timeout 20s exceeded: context deadline exceeded
Warning  Unhealthy  87s (x2 over 4m59s)    kubelet, ip-172-20-23-244.ap-northeast-1.compute.internal  Liveness probe errored: rpc error: code = DeadlineExceeded desc = failed to exec in container: timeout 20s exceeded: context deadline exceeded
```

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-eks-7c9bda", GitCommit:"7c9bda52c425d0d56d7b93f1377a826b4132c05c", GitTreeState:"clean", BuildDate:"2020-08-28T23:04:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by yuzujoe** [comment]
When I hit it from the shell, it was taking much longer than the timeout setting, I think I need to fix the chart, what do you think?

```
time rabbitmq-diagnostics -q check_running
RabbitMQ on node rabbit@rabbitmq-0.rabbitmq-headless.reportportal.svc.cluster.local is fully booted and running
real	1m10.234s
user	0m1.206s
sys	0m0.562s
```

**Comment by miguelaeh** [comment]
Hi @yuzujoe ,
Have you tried to use a bigger timeout in the liveness and readiness probes? Maybe your cluster is slow and the timeout is reached before the pod is running properly.

**Comment by yuzujoe** [comment]
Hi @miguelaeh 

Yes stretched timeout is now working properly.
I'm wondering if anyone else is having a similar problem, if others are having a similar problem there is a way to rewrite the manifest?

**Comment by miguelaeh** [comment]
It is totally configurable using parameters: https://github.com/bitnami/charts/blob/84b4eb056a3ae1d798a4918aa0fa2e0d8c62758d/bitnami/rabbitmq/values.yaml#L390

I don't think we should change the default values in the repo because it will be a major version of the chart and it highly depends on the K8s cluster.

**Comment by yuzujoe** [comment]
OK

I'm going to close this issue as I've solved my own problems.

**Comment by mteodori** [comment]
I have the same issue including the chart as a requirement in a chart of mine running on EKS single node m4.2xlarge, @yuzujoe can you share the values you set? thanks

**Comment by mtparet** [comment]
I wondering if you have been hit by this AWS bug https://github.com/awslabs/amazon-eks-ami/issues/563

**Comment by yuzujoe** [comment]
@mteodori 
I simply stretched the timeoutSecounds time of readiness and liveness.

I set the timeout time to 90 seconds to spare as it was taking roughly a minute to run the same command from the shell of the pod

**Comment by mteodori** [comment]
thanks guys, will try that otherwise move to the AWS managed service

**Comment by dani8art** [comment]
Hi!

if you are using `bitnami/rabbitmq` as the main chart you must use

```yaml
## RabbitMQ containers' liveness and readiness probes.
## ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
##
livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  timeoutSeconds: 20
  periodSeconds: 30
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 20
  periodSeconds: 30
  failureThreshold: 3
  successThreshold: 1
```

If you are using it as a sub chart you must use

```yaml
rabbitmq:
  ## RabbitMQ containers' liveness and readiness probes.
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
  ##
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    timeoutSeconds: 20
    periodSeconds: 30
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 20
    periodSeconds: 30
    failureThreshold: 3
    successThreshold: 1
```

Thanks!
