### ISSUE TITLE
Usage of global.postgresql.existingSecret and global.postgresql.postgresqlUsername overrides leads to password authentication

### ISSUE THREAD

**Issue by Vlad1mir-D** [bitnami/charts#4474]
**Which chart**:
PostgreSQL 10.1.0

**Describe the bug**
When `postgresqlUsername` and `existingSecrets` were overridden using `global.postgresql.postgresqlUsername` and `global.postgresql.existingSecrets`, no password for (superadmin) `postgres` user was set.

This was caused by the wrong condition in `templates/statefulset.yaml`:
```
{{- if and (not (eq .Values.postgresqlUsername "postgres")) (or .Values.postgresqlPostgresPassword (include "postgresql.useExistingSecret" .)) }}
```
which leads to the absence of
```
        - name: POSTGRES_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgresql-postgres-password
              name: test-secret
```

**To Reproduce**
Following steps:
1. `helm install test-postgres bitnami/postgresql --render-subchart-notes --create-namespace -n web-dev --set global.postgresql.existingSecret=test-secret --set global.postgresql.postgresqlUsername=test`
2. `export POSTGRES_ADMIN_PASSWORD=$(kubectl get secret --namespace web-dev test-secret -o jsonpath="{.data.postgresql-postgres-password}" | base64 --decode)`
3. `kubectl port-forward --namespace web-dev svc/test-postgres-postgresql 5432:5432 &`
4. `PGPASSWORD="$POSTGRES_ADMIN_PASSWORD" psql --host 127.0.0.1 -U postgres -d postgres -p 5432`
will lead to
```
psql: FATAL:  password authentication failed for user "postgres"
```

Additionally, `kubectl -n web-dev edit statefulset test-postgres-postgresql` will reveal the absence of `POSTGRES_POSTGRES_PASSWORD` in the output.

**Expected behavior**

Successful connection to the DB and presence of 
```
        - name: POSTGRES_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgresql-postgres-password
              name: test-secret
```
in the `statefulset` definition.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.13-gke.1400", GitCommit:"00c919adfe4adf308bcd7c02838f2a1b60482f02", GitTreeState:"clean", BuildDate:"2020-10-28T09:22:18Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

Probably all of the globally-overridable variables should be handled by the appropriate helpers.
