### ISSUE TITLE
Kafka Chart's liveness and readiness probes have a bug that donot allow the use of custom probes

### ISSUE THREAD

**Issue by arihantsurana** [bitnami/charts#4490]
**Which chart**:
Kafka (12.2.0)

**Describe the bug**
The custom liveness and readiness probes have a typo in the stateful set template. Thus defining a custom probe has no effect and the stateful set is templated without a probe.

**To Reproduce**

1. Define values with:
```

          livenessProbe:
            enabled: false
          customLivenessProbe:
            exec:
              command:
              - /bin/bash
              - "-c"
              - "ps -ef | grep java"
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 2
            periodSeconds: 10
            successThreshold: 1
```
2. Template chart with helm template
3. See missing liveness probe in stateful set template

**Expected behavior**
the Custom liveness probe should be present in the stateful set template.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"dirty", GoVersion:"go1.15.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"39a145ca3413079bcb9c80846488786fed5fe1cb", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:14Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
None
