### ISSUE TITLE
[bitnami/consul] different port name between servicemonitor and metric-svc

### ISSUE THREAD

**Issue by NoahIronMan** [bitnami/charts#4513]
metrics-svc.yaml:
```
ports: 
- name: http-metrics
     port: 9107
     targetPort: metrics
```

servicemonitor.yaml:
```
endpoints:
    - port: metrics
      {{- if .Values.metrics.serviceMonitor.interval }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
```

Then prometheus cannot get target because of this difference.
