### ISSUE TITLE
NodeJS chart creates "my-app-node" deployment even when using my own image.

### ISSUE THREAD

**Issue by jwanga** [bitnami/charts#4525]
**Which chart**:
node 14.5.1

**Describe the bug**
Im using "image.repository" to set a custom image built onto of the Bitnami nodes container. I've notice that when I install the chart it include creates 3 deployments. 1 for my-app 1 for my-app-mongodb and 1 for my-app-node. Perhaps I misunderstand but, it seems to me that that the "my-app-node" deployment is extraneous since my custom image was deployed to "my-app"

**To Reproduce**
Here is my value.yaml:
```yaml
# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # repository: bitnami/node
  repository: gcr.io/xxxx-xxxx-xxxx/my-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  
applicationPort: 8080

service:
  type: NodePort
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.global-static-ip-name: my-app-ip
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  
  hosts:
    - name: my-app.com
      paths: ['/']
      tls: true
      certManager: true
      tlsSecret: my-app-secret-letsencrypt-prod
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        acme.cert-manager.io/http01-edit-in-place: "true"
  tls:
   - secretName: my-app-secret-letsencrypt-prod
     hosts:
      - my-app.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# node
mongodb.install: true
```

Here is the output of kubectl get all:
```sh
NAME                                            READY   STATUS    RESTARTS   AGE
pod/my-app-65b9f6cc95-tm4d9           1/1     Running   0          2m2s
pod/my-app-mongodb-77bd7c6dd8-cgbhl   1/1     Running   0          2m1s
pod/my-app-node-6b9576cc88-g6rdl      1/1     Running   0          2m3s

NAME                               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/my-app           NodePort    10.103.0.177    <none>        8080:32387/TCP   2m3s
service/my-app-mongodb   ClusterIP   10.99.220.69    <none>        27017/TCP        2m3s
service/my-app-node      ClusterIP   10.97.223.178   <none>        80/TCP           2m3s
service/kubernetes                 ClusterIP   10.96.0.1       <none>        443/TCP          33d

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/my-app           1/1     1            1           2m3s
deployment.apps/my-app-mongodb   1/1     1            1           2m3s
deployment.apps/my-app-node      1/1     1            1           2m3s

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/my-app-65b9f6cc95           1         1         1       2m3s
replicaset.apps/my-app-mongodb-77bd7c6dd8   1         1         1       2m3s
replicaset.apps/my-app-node-6b9576cc88  
```

**Expected behavior**
I expect that only the "my-app" and "my-app-mongodb" deployments would be deployed and not "my-app-node" since it is not used when using a custom image.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
This behavior occurs both locally using Docker Desktop and on GKE
