### ISSUE TITLE
'mongodb.auth.rootPassword' must not be empty when upgrading nodejs chart

### ISSUE THREAD

**Issue by jwanga** [bitnami/charts#4527]
**Which chart**:
node 14.5.1

**Describe the bug**
I receive the following error when attempting to upgrade my helm chart:
```sh
Error: UPGRADE FAILED: template: my-app/charts/node/templates/NOTES.txt:36:4: executing "my-app/charts/node/templates/NOTES.txt" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" $passwordValidationErrors "context" $)>: error calling include: template: my-app/charts/node/charts/common/templates/_errors.tpl:18:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail: 
PASSWORDS ERROR: you must provide your current passwords when upgrade the release
    'mongodb.auth.rootPassword' must not be empty, please add '--set mongodb.auth.rootPassword=$MONGODB_ROOT_PASSWORD' to the command. To get the current value:

        export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default my-app-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)
```

**To Reproduce**

1. My chart.yaml
```yaml
apiVersion: v2
name: my-app
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 0.1.0

dependencies:
- name: node
  version: "^14.0.0"
  repository: "https://charts.bitnami.com/bitnami"

```
2. my values.yaml
```yaml
  # Default values for my-app.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  replicaCount: 1

  image:
    # repository: bitnami/node
    repository: gcr.io/xxxx-xxxx-xxxx/my-app
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
    
  applicationPort: 8080

  service:
    type: NodePort
    port: 8080

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.global-static-ip-name: my-app-ip
      cert-manager.io/cluster-issuer: letsencrypt-prod
      acme.cert-manager.io/http01-edit-in-place: "true"
    
    hosts:
      - name: my-app.com
        paths: ['/']
        tls: true
        certManager: true
        tlsSecret: my-app-secret-letsencrypt-prod
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          acme.cert-manager.io/http01-edit-in-place: "true"
    tls:
     - secretName: my-app-secret-letsencrypt-prod
       hosts:
        - my-app.com

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

  # node
  mongodb.install: true
```
3. install chart
```sh
helm install --dependency-update my-app .
```
4. Set environment variable:
```sh
export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default my-app-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)
```
5. Attempt to upgrade chart
```sh
helm upgrade --set mongodb.auth.rootPassword=$MONGODB_ROOT_PASSWORD my-app .
```
6. Observe error
```sh
Error: UPGRADE FAILED: template: my-app/charts/node/templates/NOTES.txt:36:4: executing "my-app/charts/node/templates/NOTES.txt" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" $passwordValidationErrors "context" $)>: error calling include: template: my-app/charts/node/charts/common/templates/_errors.tpl:18:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail: 
PASSWORDS ERROR: you must provide your current passwords when upgrade the release
    'mongodb.auth.rootPassword' must not be empty, please add '--set mongodb.auth.rootPassword=$MONGODB_ROOT_PASSWORD' to the command. To get the current value:

        export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default my-app-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)
```

**Expected behavior**
I expect my chart to upgrade successfully.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by jwanga** [comment]
Solved. the problem was that my values.yaml was not addressing the node subchart. I changed my values.yaml move all the values under "node" as follows:
```yaml
node:
  replicaCount: 1

  image:
    # repository: bitnami/node
    repository: gcr.io/xxxx-xxxx-xxxx/my-app
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
```
