### ISSUE TITLE
MySQL v8.0.0 - auth.database is not overridden

### ISSUE THREAD

**Issue by teivah** [bitnami/charts#4543]
**Which chart**:
mysql v8.0.0

**Describe the bug**
`auth.database` is not overridden

**To Reproduce**
1. Install MySQL chart

`Chart.yaml`:
```yaml
dependencies:
  - name: mysql
    version: 8.0.0
    repository: https://charts.bitnami.com/bitnami
```

`values.yaml`:
```yamlmysql:
  auth:
    username: foo
    database: db
    rootPassword: bar
    password: bar
```

2. Connect and list the existing databases

**Expected behavior**
A database called `db` is created. Instead, I can see only a `my_database` which is the default value of `auth.database`.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
