### ISSUE TITLE
[bitnami/mongodb] Helm install not working

### ISSUE THREAD

**Issue by michelefa1988** [bitnami/charts#4564]
**Which chart**:
Latest Master, v10.1.3

**Describe the bug**
Running the helm install command with the configuration below throws an error `Error: no objects visited`

**To Reproduce**

```helm upgrade --install mymongo --values values2.yaml ./mongodb```

values2.yaml:
```
clusterDomain: cluster.local

architecture: replicaset


useStatefulSet: false

auth:
  enabled: false
  rootPassword: "asdas"
  replicaSetKey: "asd"



replicaCount: 2

persistence:
  enabled: true

  accessModes:
    - ReadWriteOnce
  size: 8Gi
  annotations: {}
  mountPath: /bitnami/mongodb
  subPath: ""

service:
  type: ClusterIP
  port: 27017
  portName: mongodb
  nodePort: ""
  # clusterIP: None
  externalIPs: []
  # loadBalancerIP:
  loadBalancerSourceRanges: []
  annotations: {}

externalAccess:
  enabled: true
  ##
  autoDiscovery:
    ## Enable external IP/ports auto-discovery
    ##
    enabled: false
    ## Bitnami Kubectl image
    ## ref: https://hub.docker.com/r/bitnami/kubectl/tags/
    ##
    image:
      registry: docker.io
      repository: bitnami/kubectl
      tag: 1.18.12-debian-10-r2
      pullPolicy: IfNotPresent
      pullSecrets: []
    resources:
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      limits: {}
      #   cpu: 100m
      #   memory: 128Mi
      requests: {}
      #   cpu: 100m
      #   memory: 128Mi
  service:
    type: LoadBalancer
    port: 27017
    loadBalancerIPs: []
    loadBalancerSourceRanges: []
    nodePorts: []
    # domain: mydomain.com
    annotations: {}

```

**Expected behavior**
The Helm chart installs in a replicaset configuration. I will also have a service of type LoadBalancer having an internal IP

**Version of Helm **: v3.1.0

- Output of `helm version`: 

```
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

- Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"37c06f456fdb4d25e402b5fbcb72cd6a77a021a9", GitTreeState:"clean", BuildDate:"2020-09-18T21:59:14Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
(paste your output here)
```

**Additional context**
Add any other context about the problem here.
