### ISSUE TITLE
Updating policy definitions in loadDefinitions.existingSecret doesn't update policies

### ISSUE THREAD

**Issue by mltsy** [bitnami/charts#4571]
**Which chart**: rabbitmq 7.7.1

**Describe the bug**
I can define vhosts and policies in load_definitions file, but if I try to update the policy definitions, the updates aren't applied to the cluster.

**To Reproduce**

I've been using the Terraform helm provider, and I don't *think* this is a problem with the provider, so I'm going to describe what I believe it's doing without referencing Terraform:

1. Create a kubernetes secret containing a minimal load_definitions file (see example below)
1. Install the chart, referencing the given secret in the `loadDefinitions.existingSecret` value
1. Add some policy to the load_definitions file (see second example below)
1. Upgrade the release
    - Note: I set an unused value here containing a hash of the file contents, just to force terraform to notice the change - I'm not sure if setting a new value is useful/necessary on the Helm side or not (to avoid a no-op kind of response).
1. Visit the management UI
1. Navigate to Admin > Policits
1. See error (lack of new policies)

**Expected behavior**
I would expect it to modify the policies based on the load_definitions file.

**Version of Helm and Kubernetes**:

- Output of `helm version`: 3.3.4
(I can't run `helm version` on the Terraform Cloud server, but this is the version it's supposed to be using)

- Output of `kubectl version`:
I can't figure out how to get this information from terraform.  But it should be a relatively up-to-date version.

**Additional context**
I haven't ever tried this with rabbit outside of the helm chart, so I'm not sure what the correct process is, but based on [the docs](https://www.rabbitmq.com/definitions.html) saying "The definitions in the file will not overwrite anything already in the broker." it sounds like it should work to import the file after boot time at least to add new queues and policies...

**Comment by andresbono** [comment]
Hi @mltsy, is the secret mounted as a file being updated in the container? We tried the following with successful results:

`custom-values.yaml`
```yaml
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "users": [
          {
            "name": "user",
            "password": "CHANGEME",
            "tags": "administrator"
          }
        ],
        "vhosts": [
          {
            "name": "/"
          }
        ]
      }
loadDefinition:
  enabled: true
  existingSecret: load-definition
extraConfiguration: |
  load_definitions = /app/load_definition.json
```

```console
$ helm install rabbitmq bitnami/rabbitmq --version 7.7.1 -f custom-values.yaml
$ kubectl exec -it rabbitmq-0 -- cat /app/load_definition.json
{
  "users": [
    {
      "name": "user",
      "password": "CHANGEME",
      "tags": "administrator"
    }
  ],
  "vhosts": [
    {
      "name": "/"
    }
  ]
}
$ kubectl exec -it rabbitmq-0 -- curl -u user:CHANGEME http://localhost:15672/api/users
[{"name":"user","password_hash":"yF3zYemcfCPZJJvA8ttAou6rOIxJ3WXIW2ODyCPp9JTa3kOy","hashing_algorithm":"rabbit_password_hashing_sha256","tags":"administrator"}]
```

Modify custom-values.yaml to update the password from CHANGEME to CHANGEME2

```console
$ helm upgrade rabbitmq bitnami/rabbitmq --version 7.7.1 -f custom-values.yaml --set auth.password=ignore --set auth.erlangCookie=ignore
$ kubectl exec -it rabbitmq-0 -- cat /app/load_definition.json
{
  "users": [
    {
      "name": "user",
      "password": "CHANGEME2",
      "tags": "administrator"
    }
  ],
  "vhosts": [
    {
      "name": "/"
    }
  ]
}
$ kubectl exec -it rabbitmq-0 -- curl -u user:CHANGEME http://localhost:15672/api/users
{"error":"not_authorised","reason":"Login failed"}
$ kubectl exec -it rabbitmq-0 -- curl -u user:CHANGEME2 http://localhost:15672/api/users
[{"name":"user","password_hash":"RIZ/pAjyMQvjgLRhoZENHgRJUw7OaK2tKFxQDa4UBRdyR/Tq","hashing_algorithm":"rabbit_password_hashing_sha256","tags":"administrator"}]
```

Everything seems to be working fine. To better understand the issue, let us know if there are differences between my testing and yours.
