### ISSUE TITLE
Not able to configure container security context for the metrics container

### ISSUE THREAD

**Issue by stuart-thomas** [bitnami/charts#4594]
**Which chart**:
redis v 12.1.1

**Describe the bug**

When I enable metrics and set `containerSecurityContext.enabled: true` and configure some settings, such as `containerSecurityContext.allowPrivilegeEscalation: false`, in my values.yaml and install the chart the metrics container is not configured with the required security context

In the example shown in [best practises](https://docs.bitnami.com/tutorials/bitnami-best-practices-hardening-charts/#integration-with-logging-and-monitoring-tools) it would seem that the the metrics container should have the container security context configuration applied.

**To Reproduce**

Create a values.yaml with the following properties set:
```
metrics.enabled: false

containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false
  runAsUser: 1000
  capabilities:
    drop:
      - ALL
```
Install the chart using the values.yaml file

Get the manifests from the server and check the metrics container defined in the StatefulSet. It does not have a securityContext defined

**Expected behavior**

Using the example above the metrics container definition should include the following:

```
spec:
   ...
   template:
      ...
      spec:
      ...
         containers:
           - name: metrics
              ...
              securityContext:
                 allowPrivilegeEscalation: false
                 capabilities:
                    drop:
                       - ALL
                 runAsUser: 1000
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"c86ad89b8715ed17fd55b87cbb2888ccc6fa9878", GitTreeState:"clean", BuildDate:"2020-09-25T01:53:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
