### ISSUE TITLE
[bitnami/kube-prometheus] Unable to setup alertmanager with config

### ISSUE THREAD

**Issue by x20mar** [bitnami/charts#4596]
**Which chart**:
[bitnami/kube-prometheus] (latest)

**Describe the bug**
I am unable to get alertmanager to pull any of the config set via my values.yaml

**To Reproduce**
Steps to reproduce the behaviour:

- Create a values.yaml file with following:

```yaml
prometheus:
  enabled: true
  ## PrometheusRule defines recording and alerting rules for a Prometheus instance.
  ##
  additionalPrometheusRules:
    - name: custom-recording-rules
      groups:
        - name: sum_node_by_job
          rules:
            - record: job:kube_node_labels:sum
              expr: sum(kube_node_labels) by (job)
        - name: sum_prometheus_config_reload_by_pod
          rules:
            - record: job:prometheus_config_last_reload_successful:sum
              expr: sum(prometheus_config_last_reload_successful) by (pod)
    - name: custom-alerting-rules
      groups:
        - name: prometheus-config
          rules:
            - alert: PrometheusConfigurationReload
              expr: prometheus_config_last_reload_successful > 0
              for: 1m
              labels:
                severity: error
              annotations:
                summary: "Prometheus configuration reload (instance {{ $labels.instance }})"
                description: "Prometheus configuration reload error\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
        - name: custom-node-exporter-alerting-rules
          rules:
            - alert: PhysicalComponentTooHot
              expr: node_hwmon_temp_celsius > 75
              for: 5m
              labels:
                severity: warning
              annotations:
                summary: "Physical component too hot (instance {{ $labels.instance }})"
                description: "Physical hardware component too hot\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
            - alert: NodeOvertemperatureAlarm
              expr: node_hwmon_temp_alarm == 1
              for: 5m
              labels:
                severity: critical
              annotations:
                summary: "Node overtemperature alarm (instance {{ $labels.instance }})"
                description: "Physical node temperature alarm triggered\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

## Configuration for alertmanager
## ref: https://prometheus.io/docs/alerting/alertmanager/
##
alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
      slack_api_url: "https://hooks.slack.com/services/my-slack-webhook"
    route:
      receiver: "slack-notifications"
    receivers:
      - name: "slack-notifications"
        slack_configs:
          - channel: "#exceptions"
            send_resolved: true
            icon_url: https://avatars3.githubusercontent.com/u/3380462
            title: |-
              [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
              {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
                {{" "}}(
                {{- with .CommonLabels.Remove .GroupLabels.Names }}
                  {{- range $index, $label := .SortedPairs -}}
                    {{ if $index }}, {{ end }}
                    {{- $label.Name }}="{{ $label.Value -}}"
                  {{- end }}
                {{- end -}}
                )
              {{- end }}
            text: >-
              {{ range .Alerts -}}
              *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

              *Description:* {{ .Annotations.description }}

              *Details:*
                {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                {{ end }}
              {{ end }}

```

- Install kube-prometheus

```bash
kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install prometheus -f values.yaml bitnami/kube-prometheus -n metrics
```

- Create tunnel to alertmanager UI

```bash
kubectl port-forward --namespace metrics svc/prometheus-kube-prometheus-alertmanager 9093:9093
```

- Go to status page to see config at http://localhost:9093/#/status

**Expected behaviour**
Alertmanager uses config passed through and can be seen at http://localhost:9093/#/status

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```bash
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```

- Output of `kubectl version`:

```bash
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.4300", GitCommit:"7ed5ddc0e67cb68296994f0b754cec45450d6a64", GitTreeState:"clean", BuildDate:"2020-10-28T09:23:22Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I also tried setting this up using an external config but also with no luck.
