### ISSUE TITLE
[bitnami/dokuwiki] Multiple ingress hosts not working

### ISSUE THREAD

**Issue by landakram** [bitnami/charts#4618]
**Which chart**:
bitnami/dokuwiki
latest

**Describe the bug**

When attempting to use multiple ingress hosts, only the last ingress is created. It appears to be the same problem as https://github.com/bitnami/bitnami-docker-odoo/issues/74#issuecomment-525624494, given that the templates are similar. 

**To Reproduce**

(I am using helm through ansible). Add the following parameters:

```yml
      ingress:
        enabled: true
        hosts:
        - name: "dokuwiki.{{ ingress_server_ip }}.nip.io"
        - name: "dokuwiki.{{ some_other_ip }}.nip.io"
```

After running helm, only one ingress rule is created for `dokuwiki.{{ some_other_ip }}.nip.io`.

**Expected behavior**

Two ingress rules total are created for `dokuwiki.{{ ingress_server_ip }}.nip.io` and `dokuwiki.{{ some_other_ip }}.nip.io`.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5+k3s1", GitCommit:"58ebdb2a2ec5318ca40649eb7bd31679cb679f71", GitTreeState:"clean", BuildDate:"2020-05-06T23:43:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5+k3s1", GitCommit:"58ebdb2a2ec5318ca40649eb7bd31679cb679f71", GitTreeState:"clean", BuildDate:"2020-05-06T23:43:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
N/A
