### ISSUE TITLE
[bitnami/rabbitmq] Unable to change the NLB service externalTrafficPolicy

### ISSUE THREAD

**Issue by tlperini** [bitnami/charts#4637]
**Which chart**
bitnami/rabbitmq --version 7.7.1

**Is your feature request related to a problem? Please describe.**
The default NLB externalTrafficPolicy service spec is set to `Cluster` and we don't have the possibility to change it to `Local`.

**Describe the solution you'd like**
Add the possibility to configure the externalTrafficPolicy service spec through the values.yaml file.

**Describe alternatives you've considered**
Add the `service.externalTrafficPolicy` value in values.yaml.
```
service:
  ...
  externalTrafficPolicy: Cluster
  ...

```
Handle it in the svc.yaml template file:
```
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ...
```

**Additional context**
That is a related kubernetes issue: https://github.com/kubernetes/kubernetes/issues/80996
