### ISSUE TITLE
Cannot deploy more than one mongodb pod in the same k8s cluster due to endpoint service address collision

### ISSUE THREAD

**Issue by Darnesey** [bitnami/charts#4638]
**Which chart**:
mongodb-10.1.3

**Describe the bug**
Port names must be unique in a k8s cluster. Otherwise, endpoint ports of the same names will share ip addresses. This means that two mongodb pods with different clusterIP's will both have services that share two endpoints (clusterIP_1:27017, clusterIP_2:27017). This results in intermittent requests being sent to the wrong DB.

standalone/dep-sts.yaml:
``` yaml
ports:
  - name: mongodb    # <-- Fixed. Should be dynamically set with a values property
     containerPort: 27017 
```

standalone/svc.yaml:
``` yaml
- name: {{ .Values.service.portName }}
   port: {{ .Values.service.port }}
   targetPort: mongodb   # <- Fixed. Should be dynamically set with the same values property as suggested in dep-sts.yaml
```

Note that this issue appears to also be the case for both the arbiter and replicaset templates.

**Comment by juan131** [comment]
Hi @Darnesey 

Thanks for opening this issue! 

> Port names must be unique in a k8s cluster. 

This is not true. You can have as many services as you want in a cluster defining the same ports and names.

> Otherwise, endpoint ports of the same names will share ip addresses. This means that two mongodb pods with different clusterIP's will both have services that share two endpoints (clusterIP_1:27017, clusterIP_2:27017). This results in intermittent requests being sent to the wrong DB.

I think you are mixing concepts. Let's see how to access MongoDB with an example:

- Install MongoDB using a replicaset architecture and two replicas:

```console
$ helm install mongodb bitnami/mongodb --set architecture=replicaset --set replicaCount=2
```

- As you can see, three pods are created:

```
$ kubectl get pods
NAME                READY   STATUS    RESTARTS   AGE
mongodb-0           1/1     Running   0          2m30s
mongodb-1           1/1     Running   0          2m8s
mongodb-arbiter-0   1/1     Running   0          2m30s
```

- One of them it's an "arbiter" node that belongs to the "mongodb-arbiter" statefulset. And the other two pods are MongoDB nodes that belongs to the "mongodb" statefulset:

```
$ kubectl get sts
NAME              READY   AGE
mongodb           2/2     2m58s
mongodb-arbiter   1/1     2m58s
```

- There are also two "headless" services created: one for "mongodb" nodes, and another for "mongodb-arbiter" nodes:

```
$ kubectl get svc
NAME                       TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)     AGE
mongodb-arbiter-headless   ClusterIP   None           <none>        27017/TCP   3m26s
mongodb-headless           ClusterIP   None           <none>        27017/TCP   3m26s
$ kubectl get endpoints
NAME                       ENDPOINTS                            AGE
mongodb-arbiter-headless   10.224.2.14:27017                    4m1s
mongodb-headless           10.224.1.5:27017,10.224.2.15:27017   4m1s
```

"Headless" services are very special since they create a unique FQDN per pod. In our example, to access the "mongodb" nodes we can use the hostnames below to access them individually:

- `mongodb-0.mongodb-headless.default.svc.cluster.local` to access `mongodb-0`
- `mongodb-1.mongodb-headless.default.svc.cluster.local` to access `mongodb-1`

Therefore, I can create a MongoDB client in the K8s cluster, and use the commands below to access the MongoDB pods:

```console
$ mongo admin --host "mongodb-0.mongodb-headless.default.svc.cluster.local:27017,mongodb-1.mongodb-headless.default.svc.cluster.local:27017" --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD
```

**Comment by Darnesey** [comment]
Hi @juan131 

Thanks for the quick response. I could be mixing up my understanding here. I should also state that we have separate microservices that were designed to have their own database. Plus, we structure our helm charts to have them as dependencies for each microservice that requires one. This is why we currently have multiple standalone mongodb charts. Maybe in the future we can think about combining DBs but we're not there yet.

To clarify on the issue, this is what I'm seeing:
I created a sandbox helm chart to reproduce this issue. 
```
mongodb-test
|- charts
|  |- microservice1
|  |- microservice2 # both, you can assume are separate services that have their own isolated mongodb database
| templates/         # empty except for NOTES.txt
| Chart.yaml
| values.yaml
```
mongodb-test/values.yaml:
``` yaml
# Skeleton values from 'helm create …' command plus,
microservice1:
  mongodb:
    enabled: true
    architecture: standalone
    fullnameOverride: mongodb-1
    auth:
      enabled: false
    startupProbe:
      successThreshold: 1

microservice2:
  mongodb:
    enabled: true
    architecture: standalone
    fullnameOverride: mongodb-2
    auth:
      enabled: false
    startupProbe:
      successThreshold: 1
```

I then install my helm chart under a specific namespace (the namespace doesn't matter as this is reproducible under the default namespace as well)
``` bash
helm install mongodb-test .\mongodb-test\ -n namespace1 --create-namespace
```
![image](https://user-images.githubusercontent.com/11618932/101508428-a93ff600-3945-11eb-9cb4-461d3f074750.png)

Note that the Endpoints property is showing the two same IP addresses, instead of one, for both services. If you run the describe command on each pod, you will see that the pods have either one of those addresses. The end result my team is seeing is that when a request is sent to one of those DBs, the service appears to have two endpoint IP addresses to choose from so it picks one. I'm guessing it's assuming they are replicas of the same pod. 

To your point about the FQDN resolution, as you can see from the image above, we have unique randomly generated strings appended to each pod name so trying to communicate with `pod.servicename.namespace.svc.cluster.local` is not really going to work unless I'm missing something. But even so, I shouldn't have to specify a pod name anyways since I have separate k8s services for each mongodb pod.

Now when I tweak the helm chart for mongodb to specify a unique port name for the mongodb pods (and the targetPort name their corresponding service routes to), this problem goes away.
![image](https://user-images.githubusercontent.com/11618932/101508576-d8eefe00-3945-11eb-9a86-83b271a64806.png)

Now the endpoints have only a single IP address, and our application no longer has intermittent DB query errors.

My understanding from what I've learned from playing around with this environment is that it doesn't matter which architecture I choose from mongodb. I have tried this with standalone and with replicasets and the endpoints are always combined if the targetPort's name is the same. 

Interestingly enough, I did try deploying two mongodb charts separately via separate helm install commands and that works fine (no combined endpoints). It's when they share a parent helm chart that these combine, likely due to how helm deploys each k8s yaml configuration.

**Comment by Darnesey** [comment]
My teammate looked into this issue some more and found that if we override the `.Values.nameOverride` property within mongodb, the selectors between the two services will be unique enough to separate the endpoints and fix our issue. 

### Fix
mongodb-test/values.yaml:
``` yaml
microservice1:
  mongodb:
    enabled: true
    architecture: standalone
    fullnameOverride: mongodb-1
    nameOverride: microservice1-mongodb   # <- Updates the selector labels and makes the two endpoints unique
    auth:
      enabled: false

microservice2:
  mongodb:
    enabled: true
    architecture: standalone
    fullnameOverride: mongodb-2
    nameOverride: microservice2-mongodb
    auth:
      enabled: false
```

Thanks for your help!
