### ISSUE TITLE
Driver remains in 'submitted' status with spark-submit in 'cluster' mode

### ISSUE THREAD

**Issue by gkulkarni32** [bitnami/charts#4656]
**Which chart**:
bitnami/spark

**Describe the bug**
I deployed the spark cluster using bitnami/spark helm chart. I submitted an application using the spark-submit command in 'cluster' mode and is in 'RUNNING' status. If I try to submit another application using the spark-submit command in 'cluster' mode, it remains in 'SUBMITTED' status. Basically I'm unable to have 2 applications run in parallel in 'cluster' mode on the spark cluster. 

**To Reproduce**

Deploy the spark cluster: 
`helm install dp bitnami/spark -n spark-operator --set image.registry=<registry> --set image.repository=<custom image repo> --set image.tag=<image tab> --set service.type=LoadBalancer --set metrics.enabled=true`

I get 1 master and 2 worker nodes. 

Run the application: 

```
kubectl run --namespace spark-operator dp-spark-client --rm --tty -i --restart='Never' \
 --image <custom-image> \
 -- spark-submit --master spark://10.109.23.116:7077 \
 --deploy-mode cluster \
 --class com.dataplatforms.kafka.spark.TradeSparkConsumerApplication \
 --driver-memory 500M --conf spark.executor.memory=1g --conf spark.cores.max=1 \
 examples/jars/trade-spark-consumer-0.0.1-SNAPSHOT.jar param1 springtrades springsparktrades
```

If I trigger another application using the same jar or a different jar, It remains in 'SUBMITTED' status:
```
kubectl run --namespace spark-operator dp-spark-client --rm --tty -i --restart='Never' \
    --image harbor-repo.vmware.com/dockerhub-proxy-cache/gkulkarni32/custom-bitnami-spark:v16 \
    -- spark-submit --master spark://10.109.23.116:7077 \
    --deploy-mode cluster \
    --class org.apache.spark.examples.SparkPi \
    examples/jars/spark-examples_2.12-3.0.1.jar 5
```

**Expected behavior**
I'm expecting both the applications to run in parallel.

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.14+vmware.1", GitCommit:"bbf52cd6cf83a50507e943b717ed321d383a37b5", GitTreeState:"clean", BuildDate:"2020-08-19T23:48:38Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by dani8art** [comment]
Hi @gkulkarni32, after some researches, it seems to be a missing resources issue. I mean, when you are submitting an application you don't only have to take into account resources for the application itself but for both application and driver inside the cluster, I can see two way of handle it:

1. To increase the resources in the cluster by adding more worker nodes, **that was what we tested**. 

```console
$ helm install spark bitnami/spark --set image.repository=darteaga/spark --set image.tag=1606989025 --set worker.replicaCount=5
```

then you can see both applications running in parallel:
![Screenshot 2020-12-09 at 15 41 14](https://user-images.githubusercontent.com/4376304/101644474-82f98380-3a35-11eb-8a12-b513a5ca2ee5.png)

2. To limit the resources for applications and its drivers using `spark-submit` command's flags. I found this[ link ](https://stackoverflow.com/questions/49381168/list-of-spark-submit-options)very useful to do it by this way

**Comment by gkulkarni32** [comment]
Thank you @dani8art for the pointer . Even after increasing the replicas, It looks like we always need to specify the resources to limit the cores each application uses, otherwise the second application remains in 'SUBMITTED' status. 

I increased the workers to 5 and always set the executor cores to max 1 like below to get it working. 

kubectl run --namespace spark-operator dp-spark-client --rm --tty -i --restart='Never' \
 --image harbor-repo.vmware.com/dockerhub-proxy-cache/gkulkarni32/custom-bitnami-spark:v16 \
 -- spark-submit --master spark://10.101.72.61:7077 \
 --deploy-mode cluster \
 --class com.dataplatforms.kafka.spark.TradeSparkConsumerApplication \
 --driver-memory 500M --conf spark.executor.memory=1g --conf spark.cores.max=1 \
 examples/jars/trade-spark-consumer-0.0.1-SNAPSHOT.jar 10.216.52.136:9092 springtrades springsparktrades

**Comment by dani8art** [comment]
Yes, you should control the resources so that the application and its driver don't spread across the cluster.

> 1 in YARN mode, all the available cores on the worker in standalone and Mesos coarse-grained modes

The default value for `spark.executor.cores` make the application to get all the nodes in the cluster.

You may be interested in define the default configuration for application submission that could be done by performing the following steps.

1. Create a ConfigMap with your default config

**spark-defaults.conf**
```ini
spark.master=spark://spark-master-svc:7077
spark.submit.deployMode=cluster

spark.cores.max=1
spark.driver.cores=1
spark.driver.memory=512m
spark.executor.cores=1
spark.executor.memory=512m
```

```console
$ k create configmap spark-defaults-conf --from-file=spark-defaults.conf
```

2. Prepare your `values.yaml`

```yaml
confVolume: &confVolume
  extraVolumes:
    - name: spark-defaults-conf
      configMap:
        name: spark-defaults-conf
  extraVolumeMounts:
    - name: spark-defaults-conf
      mountPath: /opt/bitnami/spark/conf/spark-defaults.conf
      subPath: spark-defaults.conf
  podAnnotations: |
    checksum/defaultsconf: {{ lookup "v1" "ConfigMap" .Release.Namespace  "spark-defaults-conf" | toYaml | sha256sum }}

worker:
  replicaCount: 5
  <<: *confVolume

master:
  <<: *confVolume
``` 

3. upgrade/install the chart

```console
$ helm upgrade --install spark bitnami/spark -f values.yaml
```

4. execute your `spark-submit` command, you have two options: from one of the worker pods or create a Job that will submit the application

**spark-submit-job.yaml**
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: spark-client
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - image: bitnami/spark
          command:
            - /opt/bitnami/scripts/spark/entrypoint.sh
            - spark-submit
            - --class
            - org.apache.spark.examples.SparkPi
            - examples/jars/spark-examples_2.12-3.0.1.jar
            - '5'
          name: spark-client
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: spark-defaults-conf
              mountPath: /opt/bitnami/spark/conf/spark-defaults.conf
              subPath: spark-defaults.conf
      restartPolicy: Never
      volumes:
        - name: spark-defaults-conf
          configMap:
            name: spark-defaults-conf
```

```console
$ k apply -f spark-submit-job.yaml
```

With that, you can apply a default configuration to all your submission.
