### ISSUE TITLE
[kafka] When run kafka-ropics.sh it throws port already in use

### ISSUE THREAD

**Issue by sergeyshaykhullin** [bitnami/charts#4704]
**Which chart**:
kafka

**Describe the bug**
I started researching to provision kafka topics https://github.com/bitnami/charts/issues/4651 from helm chart and tried to run kafka-topics.sh manually. When i ran it, i got an exception that port is already in use

**To Reproduce**
1. Run kafka cluster
2. `kubectl exec -it kafka-0 -n kafka kafka -- bash`
3. `export KAFKA_OPTS="-Djava.security.auth.login.config=/opt/bitnami/kafka/conf/kafka_jaas.conf"`
4. `/opt/bitnami/kafka/bin/kafka-topics.sh --create --zookeeper SERVER-IP:2181 --replication-factor 1 --partitions 1 --topic test`

**Expected behavior**
I can use kafka-topics.sh without exceptions

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

Docs https://docs.bitnami.com/aws/infrastructure/kafka/administration/run-producer-consumer/

Exception
```
I have no name!@kafka-0:/$ export KAFKA_OPTS="-Djava.security.auth.login.config=/opt/bitnami/kafka/conf/kafka_jaas.conf"I have no name!@kafka-0:/$ /opt/bitnami/kafka/bin/kafka-topics.sh --create --zookeeper SERVER-IP:2181 --replication-factor 1 --partitions 1 --topic test                                                                                        Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 5555; nested exception is:         java.net.BindException: Address already in use (Bind failed)                                                    jdk.internal.agent.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 5555; nested exception is:                                                                                                                            java.net.BindException: Address already in use (Bind failed)                                                            at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:491)                                                                                                                     at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:447)                                             at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:599)                                     Caused by: java.rmi.server.ExportException: Port already in use: 5555; nested exception is:                                     java.net.BindException: Address already in use (Bind failed)                                                            at java.rmi/sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:335)                                            at java.rmi/sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:243)                                      at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:412)                                        at java.rmi/sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)                                                    at java.rmi/sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:234)                                     at java.rmi/sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:220)                                                  at java.rmi/sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:180)                                                 at jdk.management.agent/sun.management.jmxremote.SingleEntryRegistry.<init>(SingleEntryRegistry.java:49)                at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.exportMBeanServer(ConnectorBootstrap.java:836)                                                                                                                              at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:479)                                                                                                                     ... 2 more                                                                                                      Caused by: java.net.BindException: Address already in use (Bind failed)                                                         at java.base/java.net.PlainSocketImpl.socketBind(Native Method)                                                         at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)                                    at java.base/java.net.ServerSocket.bind(ServerSocket.java:395)                                                          at java.base/java.net.ServerSocket.<init>(ServerSocket.java:257)                                                        at java.base/java.net.ServerSocket.<init>(ServerSocket.java:149)                                                        at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createServerSocket(TCPDirectSocketFactory.java:45)             at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newServerSocket(TCPEndpoint.java:670)                                     at java.rmi/sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:324)                                            ... 11 more                                                                                                     I have no name!@kafka-0:/$
```

**Comment by dani8art** [comment]
Hi @sergeyshaykhullin 

I've tried to reproduce it but I couldn't, this is what I did:

```
$ helm install kk bitnami/kafka
$ k exec -ti kk-kafka-0 -- bash
$ /opt/bitnami/kafka/bin/kafka-topics.sh --create --zookeeper kk-zookeeper:2181 --replication-factor 1 --partitions 1 --topic test
Created topic test.
```

- Why do you need to use `export KAFKA_OPTS="-Djava.security.auth.login.config=/opt/bitnami/kafka/conf/kafka_jaas.conf"`?
- Could you share a bit more about your installation config?

Thanks!

**Comment by sergeyshaykhullin** [comment]
KAFKA_OPTS is in docs, i just copy-pasted, i don't think it is required

This is rendered values.yaml template, i am using external zookeeper

```yaml
pdb:
  create: true

heapOpts: -Xmx512m -Xms512m

deleteTopicEnable: true
autoCreateTopicsEnable: false

logFlushIntervalMessages: 10000
logFlushIntervalMs: 1000
logRetentionBytes: '5368709120'
logRetentionCheckIntervalMs: 600000
logRetentionHours: 168
logSegmentBytes: '536870912'
maxMessageBytes: '1048576'

numPartitions: 3
defaultReplicationFactor: 3
offsetsTopicReplicationFactor: 3
transactionStateLogReplicationFactor: 3
transactionStateLogMinIsr: 3

numIoThreads: 2
numNetworkThreads: 4
numRecoveryThreadsPerDataDir: 1

socketSendBufferBytes: 102400
socketReceiveBufferBytes: 102400
socketRequestMaxBytes: '104857600'

zookeeperConnectionTimeoutMs: 6000

auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext

allowPlaintextListener: true

replicaCount: 3

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1024Mi

externalAccess:
  enabled: false

persistence:
  enabled: true
  storageClass: local
  size: 5Gi

service:
  annotations:
    consul.hashicorp.com/service-sync: "true"
    consul.hashicorp.com/service-name: kafka
    consul.hashicorp.com/service-port: tcp-client

metrics:
  kafka:
    enabled: true
  jmx:
    enabled: true
  serviceMonitor:
    enabled: true

zookeeper:
  enabled: false

externalZookeeper:
  servers:
  - zookeeper.zookeeper
```
