### ISSUE TITLE
[bitnami/phabricator] Is that possible to specify the http(s) proxy in values.yaml for Phabricator to connect to internet GIT Repo?

### ISSUE THREAD

**Issue by wantdrink** [bitnami/charts#4716]
**Which chart**:
phabricator: 10.1.1

**Is your feature request related to a problem? Please describe.**
I've established a Phabricator and found that the service in internal network cannot connect to Github directly, and I didn't find a place to specify the http(s) proxy for connecting to GIT service in values.yaml or configure that in Phabricator UI after googling.

**Describe the solution you'd like**
Is that possible to enable http(s) proxy for connecting to GIT in values?

Thanks a lot.

**Comment by miguelaeh** [comment]
Hi @wantdrink ,
It seems it can't be done directly in the values.yaml. Does this guide work for your case? https://docs.bitnami.com/bch/apps/phabricator/configuration/configure-external-repo/

**Comment by wantdrink** [comment]
Thanks @miguelaeh .
I read this (also tried to search with word 'proxy' first), it seems that it illustrate how to create the repo with normal access. But still no way to specify a http(s) proxy.
Then I tried to find some clues in https://hub.docker.com/r/bitnami/phabricator/ and unfortunately no such env explained.
Maybe run it with docker-compose instead of chart, and specify the OS level proxy might work? Such as ENV http_proxy & https_proxy.

**Comment by miguelaeh** [comment]
Hi @wantdrink ,
AFAIK there is not a way to specify that right now in the Helm Chart.
What you are suggesting could work, but I have never tried that. You could also try to modify the chart to add those env vars in the deployment instead of using docker-compose.
We would really appreciate it if you could let us know if that works.

**Comment by wantdrink** [comment]
Thanks @miguelaeh , I'll try it and update here.

**Comment by wantdrink** [comment]
I've tried w/o http proxy first but failed.
Here is my values with ingress:

```
phabricatorHost: localk8s.com

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
  hosts:
    - name: ingre.localk8s.com
      path: /phabricator(/|$)(.*)
      tls: true      
      tlsSecret: ing-secret

```

And access https://ingre.localk8s.com/phabricator will be redirected to https://ingre.localk8s.com/auth/register/.
The response is:
```
{
    "faultstring": "The resource could not be found."
}
```
Does phabricator support ingress rewrite? Thanks.

**Comment by FraPazGal** [comment]
Hello @wantdrink,

In principle, it should support it. Does the `faultstring` response appear once redirected to `https://ingre.localk8s.com/auth/register/`? I'll try to reproduce this behaviour and come back with my findings!

**Comment by wantdrink** [comment]
Thank you @FraPazGal.
I'm not sure whether it's correct if I set the host as below:

`phabricatorHost: localk8s.com
`

**Comment by wantdrink** [comment]
It seems that with the rewrite ingress, clicking login button will be redirected to ingre.localk8s.com/auth/register.
Now ingress cannot handle it since it doesn't recognize this path.

**Comment by FraPazGal** [comment]
Hello @wantdrink,

I got exactly the same result that you describe in your last comment. I looked into [Phabricator's documentation](https://secure.phabricator.com/book/phabricator/article/configuration_guide/) and it seems this feature is not supported 

> You can either install Phabricator on a subdomain (like phabricator.example.com) or an entire domain, but you can not install it in some subdirectory of an existing website. 

This was confirmed by Evan Priestley, Phabricator Lead, in an old [stackoverflow post](https://stackoverflow.com/questions/18720579/how-to-configure-phabricator-with-a-non-root-url), so it seems there is no ENV to enable this.

**Comment by wantdrink** [comment]
Thank you @FraPazGal, I'll try to use ingress without redirect.

**Comment by wantdrink** [comment]
Tested with docker composer and the image works good with https_proxy env.
Will try to change a little in the chart to add this env if defined and test. But I have to use kube proxy to test since the re-write is not allowed.

**Comment by miguelaeh** [comment]
Thank you very much for the update!

Just a question, did you try setting the `phabricatorHost` like the redirected domain? I mean:
```
phabricatorHost: ingre.localk8s.com

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
  hosts:
    - name: ingre.localk8s.com
      path: /phabricator(/|$)(.*)
      tls: true      
      tlsSecret: ing-secret
```

**Comment by wantdrink** [comment]
Yes @miguelaeh, below is the configuration:


```
phabricatorHost: ingre.localk8s.com

ingress:
  enabled: true
  certManager: false

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"

  hosts:
    - name: ingre.localk8s.com
      path: /phabricator(/|$)(.*)
      tls: true
      tlsHosts:
        - ingre.localk8s.com
      tlsSecret: ing-secret
```

The difference is the host is FQDN.
