### ISSUE TITLE
Port 9419 is not available for metrics collection

### ISSUE THREAD

**Issue by volkmydj** [bitnami/charts#4722]
**Which chart**:
name: rabbitmq
version: 8.5.4

**Describe the bug**
Port 9419 is not available from the host itself

**To Reproduce**

1. Install the chart `helm install rabbitmq-release -f values.yaml --set persistence.existingClaim=rabbit-nfs-pvc --set auth.username=admin --set auth.password=123qweASD bitnami/rabbitmq`
```
To access the RabbitMQ Prometheus metrics, get the RabbitMQ Prometheus URL by running:

    kubectl port-forward --namespace default svc/rabbitmq-release 9419:9419 &
    echo "Prometheus Metrics URL: http://127.0.0.1:9419/metrics"
```

2. `kubectl exec -it rabbitmq-release-0 -- curl http://localhost:9419`
```
curl: (7) Failed to connect to localhost port 9419: Connection refused
command terminated with exit code 7
```

3. `
    kubectl port-forward --namespace default svc/rabbitmq-release 9419:9419 & echo "Prometheus Metrics URL: http://127.0.0.1:9419/metrics"`

```
Unable to listen on port 9419: Listeners failed to create with the following errors: [unable to create listener: Error listen tcp4 127.0.0.1:9419: bind: address already in use unable to create listener: Error listen tcp6 [::1]:9419: bind: address already in use]
error: unable to listen on any of the requested ports: [{9419 9419}]

[2]  + 48987 exit 1     kubectl port-forward --namespace default svc/rabbitmq-release 9419:9419
```

**Expected behavior**
Port 9419 is not available.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:18:22Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
My `values.yaml`

```yaml
image:
  registry: docker.io
  repository: bitnami/rabbitmq
  tag: 3.8.2-debian-10-r30

  debug: false
  pullPolicy: IfNotPresent

rbacEnabled: true
 podManagementPolicy: OrderedReady

rabbitmq:
  username: user
  logs: "-"

  setUlimitNofiles: true
  ulimitNofiles: "65536"
  maxAvailableSchedulers: 2
  onlineSchedulers: 1

  ## Plugins to enable
  plugins: "rabbitmq_management rabbitmq_peer_discovery_k8s"
  extraPlugins: "rabbitmq_auth_backend_ldap"
  clustering:
    address_type: hostname
    rebalance: false

  loadDefinition:
    enabled: false
    secretName: load-definition
  env: {}

  ## Configuration file content: required cluster configuration
  ## Do not override unless you know what you are doing. To add more configuration, use `extraConfiguration` of `advancedConfiguration` instead
  configuration: |-
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.node_cleanup.interval = 10
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    # queue master locator
    queue_master_locator=min-masters
    # enable guest user
    loopback_users.guest = false
  # auth:
  #   username: admin
  extraConfiguration: |-
    # default_vhost = default-vhost
    # default_permissions.configure = .*
    # default_permissions.read = .*
    # default_permissions.write = .*
    #disk_free_limit.absolute = 50MB
    #management.load_definitions = /app/load_definition.json
  advancedConfiguration: |-
  tls:
    enabled: false
    failIfNoPeerCert: true
    sslOptionsVerify: verify_peer
    caCertificate: |-
    serverCertificate: |-
    serverKey: |-
    # existingSecret: name-of-existing-secret-to-rabbitmq

ldap:
  enabled: false
  server: ""
  port: "389"
  user_dn_pattern: cn=${username},dc=example,dc=org
  tls:
    # If you enabled TLS/SSL you can set advaced options using the advancedConfiguration parameter.
    enabled: false

service:
  type: ClusterIP
  # nodePort: 30672
  loadBalancerIP: 172.27.53.26
  port: 5672
  tlsPort: 5671
  distPort: 25672
  managerPort: 15672
  annotations:
    {}
    # service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  # loadBalancerSourceRanges:
  # - 10.10.10.0/24
  # extraPorts:
  # extraContainerPorts:

# Additional pod labels to apply
podLabels: {}
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
  extra: {}

persistence:
  enabled: true
  # storageClass: "-"
  accessMode: ReadWriteOnce
  existingClaim: "rabbit-nfs-pvc"

  # If you change this value, you might have to adjust `rabbitmq.diskFreeLimit` as well.
  size: 8Gi

  # persistence directory, maps to the rabbitmq data directory
  path: /opt/bitnami/rabbitmq/var/lib/rabbitmq
resources: {}

networkPolicy:
  enabled: false
  allowExternal: true
  # additionalRules:
  #  - matchLabels:
  #    - role: frontend
  #  - matchExpressions:
  #    - key: role
  #      operator: In
  #      values:
  #        - frontend
replicas: 1
# priorityClassName: ""
updateStrategy:
  type: RollingUpdate
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  {}
  # maxUnavailable: 1
  # minAvailable: 1
podAnnotations: {}

ingress:
  enabled: false
  path: /
  tls: false
  tlsSecret: myTlsSecret
  annotations: {}
  #  kubernetes.io/ingress.class: nginx
  #  kubernetes.io/tls-acme: true
livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  timeoutSeconds: 20
  periodSeconds: 30
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 20
  periodSeconds: 30
  failureThreshold: 3
  successThreshold: 1

metrics:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/rabbitmq-exporter
    tag: 0.29.0-debian-10-r28
    pullPolicy: IfNotPresent
    # pullSecrets:
    #   - myRegistryKeySecretName
  env: {}
  port: 9419
  rabbitmqAddress: localhost
  capabilities: "bert,no_sort"
  resources: {}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9419"

  livenessProbe:
    enabled: true
    initialDelaySeconds: 15
    timeoutSeconds: 5
    periodSeconds: 30
    failureThreshold: 6
    successThreshold: 1

  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    timeoutSeconds: 5
    periodSeconds: 30
    failureThreshold: 3
    successThreshold: 1

  serviceMonitor:
    enabled: true
    namespace: "monitoring"
    interval: 30s
    # scrapeTimeout: 30s
    # relabellings:
    honorLabels: false
    # release: ""
    additionalLabels: {}

  prometheusRule:
    enabled: false
    additionalLabels: {}
    namespace: ""
    rules:
      []

volumePermissions:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/minideb
    tag: buster
    pullPolicy: Always
    # pullSecrets:
    #   - myRegistryKeySecretName
  resources: {}

forceBoot:
  enabled: false
extraSecrets:
  {}
```
