### ISSUE TITLE
is our `index.yaml` correct

### ISSUE THREAD

**Issue by sebgoa** [bitnami/charts#474]
It seems to me the index.yaml is incorrect, with a wrong `urls` field. It lacks the actualy URL and only references the tarball.

```
wget https://charts.bitnami.com/incubator/index.yaml
more index.yaml 
apiVersion: v1
entries:
  apache:
  - created: 2017-11-30T18:40:04.582855774Z
    description: Chart for Apache HTTP Server
    digest: 190a7bfc84d8b5bcee1ae76f6fb12226fda1d7bcefb171989a909beb67271c42
    engine: gotpl
    home: https://httpd.apache.org
    keywords:
    - apache
    - http
    - https
    - www
    - web
    - reverse proxy
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: apache
    sources:
    - https://github.com/bitnami/bitnami-docker-apache
    urls:
    - apache-0.3.7.tgz
    version: 0.3.7
```

You end up being able to search the index, but you cannot install the charts.

cc/ @sameersbn @prydonius

**Comment by anguslees** [comment]
I note the "stable" `index.yaml` has fully qualified URLs, even though they have the same prefix as the index.

```
 % curl -sL https://kubernetes-charts.storage.googleapis.com/index.yaml | grep -2 urls: | head
    sources:
    - https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler
    urls:
    - https://kubernetes-charts.storage.googleapis.com/acs-engine-autoscaler-2.1.1.tgz
    version: 2.1.1
--
    sources:
    - https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler
    urls:
    - https://kubernetes-charts.storage.googleapis.com/acs-engine-autoscaler-2.1.0.tgz
```
