### ISSUE TITLE
livenessProbe and readinessProbe httpGet.path configurable

### ISSUE THREAD

**Issue by mrgasco** [bitnami/charts#4750]
**Which chart**:
bitnami/tomcat

**Is your feature request related to a problem? Please describe.**
I would like to configure the livenessProbe and readinessProbe httpGet paramethers

**Describe the solution you'd like**
livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ ternary "https" "http" .Values.livePath}}
              port: {{ ternary "https" "http" .Values.healthcheckHttps }}

**Describe alternatives you've considered**
using customLivenessProbe

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. From what I see in the template, the you can define these parameters in the values.yaml

```

## Liveness and Readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
##
livenessProbe:
  enabled: true
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 120
  periodSeconds: 10
  failureThreshold: 6
  timeoutSeconds: 5
  successThreshold: 1
readinessProbe:
  enabled: true
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 3
  timeoutSeconds: 3
  successThreshold: 1


```

Did you try changing them? Did you find any issue?
