### ISSUE TITLE
Labels are not set in pods

### ISSUE THREAD

**Issue by EricPE69** [bitnami/charts#4760]
**Which chart**:

mariadb-galera 5.3.2

**Describe the bug**

When I try to use "podLabels" labels are not set in the pods.

"podLabels" is not used in templates:

```yaml
 template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}`
 ```

It works with "podAnnotations".

**To Reproduce**

Try to set `poLlabels` and test with helm template

**Expected behavior**

Labels are set in pods with values in podLabels

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.14", GitCommit:"d2a081c8e14e21e28fe5bdfa38a817ef9c0bb8e3", GitTreeState:"clean", BuildDate:"2020-08-13T12:33:34Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.12+vmware.1", GitCommit:"46e19b7a51ad522f50ce60f80945d885b772d3ae", GitTreeState:"clean", BuildDate:"2020-06-29T22:32:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
