### ISSUE TITLE
kiam chart connectivity issues

### ISSUE THREAD

**Issue by voor** [bitnami/charts#4777]
**Which chart**:
`bitnami/kiam`
version: 0.1.7

**Describe the bug**
kiam-agent is unable to connect to the kiam-server

**To Reproduce**

TKG (Cluster API AWS) on AWS, using Ubuntu 18.04 base images.  kiam server role is assumed from the IAM Instance Role on the master node:
```
  AWSIAMRoleKIAMServer:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
              - sts:TagSession
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt AWSIAMRoleControlPlane.Arn
        Version: 2012-10-17
      Policies:
        - PolicyName: assume-required-roles
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                  - sts:TagSession
                # Here we specify the roles that the worker pods are allowed to assume. Notice
                # it can contain wildcards (NB it is not a regex).
                Resource: !Sub "arn:${AWS::Partition}:iam::*:role/*.pod.tkg.tanzu"
      RoleName: kiam-server.cluster-api-provider-aws.sigs.k8s.io
    Type: AWS::IAM::Role
```

Values for chart rendering:
```
image:
  tag: 3 # Use Photon3 based image.

agent:
  tlsSecret: kiam-agent-tls
  tlsCerts:
    certFileName: tls.crt
    keyFileName: tls.key
    caFileName: ca.crt

  metrics:
    enabled: false
    servicemonitor:
      enabled: false

  iptables: true

  gatewayTimeoutCreation: 500s

  containerSecurityContext:
    runAsNonRoot: false
    runAsUser: 0
    capabilities:
      add:
      - NET_ADMIN

  extraEnvVars:
  - name: AWS_REGION
    valueFrom:
      secretKeyRef:
        name: kiam-config
        key: region
  - name: AWS_DEFAULT_REGION
    valueFrom:
      secretKeyRef:
        name: kiam-config
        key: region

server:
  resourceType: deployment
  replicaCount: 1

  sslCertHostPath: /etc/ssl/certs

  extraArgs:
    region: $(AWS_REGION)
    session: tanzu

  extraEnvVars:
  - name: AWS_REGION
    valueFrom:
      secretKeyRef:
        name: kiam-config
        key: region
  - name: AWS_DEFAULT_REGION
    valueFrom:
      secretKeyRef:
        name: kiam-config
        key: region
  - name: ASSUME_ROLE_ARN
    valueFrom:
      secretKeyRef:
        name: kiam-config
        key: roleArn

  tlsSecret: kiam-server-tls
  tlsCerts:
    certFileName: tls.crt
    keyFileName: tls.key
    caFileName: ca.crt

  roleBaseArn: null

  assumeRoleArn: $(ASSUME_ROLE_ARN)

  dnsPolicy: Default

  metrics:
    enabled: false
    serviceMonitor:
      enabled: false

  nodeSelector:
    node-role.kubernetes.io/master: ""

  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  # these are automatically added to daemonsets, so we need them manually since deployment: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#taints-and-tolerations
  - key: "node-role.kubernetes.io/not-ready"
    effect: "NoSchedule"
    operator: "Exists"
  - key: "node-role.kubernetes.io/unreachable"
    effect: "NoSchedule"
    operator: "Exists"
  - key: "node-role.kubernetes.io/disk-pressure"
    effect: "NoSchedule"
    operator: "Exists"
  - key: "node-role.kubernetes.io/memory-pressure"
    effect: "NoSchedule"
    operator: "Exists"
  - key: "node-role.kubernetes.io/unschedulable"
    effect: "NoSchedule"
    operator: "Exists"
  - key: "node-role.kubernetes.io/network-unavailable"
    effect: "NoSchedule"
    operator: "Exists"
```

Additional fields added:
```
#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.not_op(overlay.subset({"kind": "Namespace"})),expects="0+"
---
#@overlay/match missing_ok=True
metadata:
  #@overlay/match missing_ok=True
  namespace: kiam

---
apiVersion: v1
kind: Namespace
metadata:
  name: kiam
  annotations:
    iam.amazonaws.com/permitted: ".*"
---
apiVersion: v1
kind: Secret
metadata:
  name: kiam-config
  namespace: kiam
type: Opaque
stringData:
  region: #@ data.values.aws_region
  roleArn: #@ data.values.kiam_role_arn
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: kiam-selfsigned-issuer
  namespace: kiam
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kiam-serving-cert
  namespace: kiam
spec:
  secretName: kiam-ca-tls
  commonName: "kiam-ca"
  isCA: true
  issuerRef:
    name: kiam-selfsigned-issuer
  usages:
  - "any"
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: kiam-ca-issuer
  namespace: kiam
spec:
  ca:
    secretName: kiam-ca-tls
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kiam-agent
  namespace: kiam
spec:
  secretName: kiam-agent-tls
  commonName: agent
  issuerRef:
    name: kiam-ca-issuer
  usages:
  - "any"
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kiam-server
  namespace: kiam
spec:
  secretName: kiam-server-tls
  issuerRef:
    name: kiam-ca-issuer
  usages:
  - "any"
  dnsNames:
  - "localhost"
  - "kiam-server"
  - kiam-server.kiam.svc
  - kiam-server.kiam.svc.cluster.local
  ipAddresses:
  - "127.0.0.1"
```

**Expected behavior**
kiam agent should be able to connect to kiam server so that it can properly pass roles down to pods running on the workers.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3+vmware.1", GitCommit:"2ac9e7ea06a1230ca196931def19d2bb67b580c7", GitTreeState:"clean", BuildDate:"2020-11-17T00:08:07Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
