### ISSUE TITLE
[bitnami/nginx-ingress-controller] Enable custom /nginx_status settings

### ISSUE THREAD

**Issue by aeimer** [bitnami/charts#4778]
**Which chart**: bitnami/nginx-ingress-controller
The name (and version) of the affected chart.

**Is your feature request related to a problem? Please describe.**

I would like to make the `/nginx_status` site available to all service inside of the cluster, the `127.0.01` binding does not work for us as we are using instana which runs as a Daemonset.

Currently there is this in the nginx.conf:
```
# health checks in cloud providers require the use of port 80
location /healthz {
	access_log off;
	return 200;
}

# this is required to avoid error if nginx is being monitored
# with an external software (like sysdig)
location /nginx_status {
	allow 127.0.0.1;
	deny all;
	access_log off;
	stub_status on;
}
```

And i need to adapt that `allow` and `deny` part.
Whats the best way to do that?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by javsalgar** [comment]
Hi,

According to https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/custom-template/ It is possible to use a custom template. In that case, you could create a configmap with your custom nginx.tmpl and then use the `extraVolumes` and `extraVolumeMounts` values in the chart.

```
extraVolumes:
  - name: nginx-template-volume
     configMap:
       name: nginx-template
       items:
         - key: nginx.tmpl
           path: nginx.tmpl

extraVolumeMounts:
  - mountPath: /etc/nginx/template
    name: nginx-template-volume
    readOnly: true
```
