### ISSUE TITLE
bitnami/wordpress: ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend

### ISSUE THREAD

**Issue by acim** [bitnami/charts#4791]
**Which chart**:
bitnami/wordpress

**Describe the bug**
diff fails, probably install and upgrade as well.

**To Reproduce**

**Expected behavior**
To show diff and be able to upgrade.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

```txt
STDERR:
  Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[1].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[1].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]
  Error: plugin "diff" exited with error

COMBINED OUTPUT:
  Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[1].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[1].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]
  Error: plugin "diff" exited with error
```

So ingress.yaml should support new syntax.

```txt
❯ k explain ingress.spec.rules.http.paths.backend.service
KIND:     Ingress
VERSION:  networking.k8s.io/v1

RESOURCE: service <Object>

DESCRIPTION:
     Service references a Service as a Backend. This is a mutually exclusive
     setting with "Resource".

     IngressServiceBackend references a Kubernetes Service as a Backend.

FIELDS:
   name	<string> -required-
     Name is the referenced service. The service must exist in the same
     namespace as the Ingress object.

   port	<Object>
     Port of the referenced service. A port name or port number is required for
     a IngressServiceBackend.
```

**Comment by carrodher** [comment]
In order to reproduce the issue and find the proper solution, can you share the exact parameters you are providing to the `helm install`/`helm template` command or the steps to reproduce the issue?

**Comment by acim** [comment]
If you look at the following snippet of https://github.com/bitnami/charts/blob/master/bitnami/wordpress/templates/ingress.yaml:

```yaml
spec:
  rules:
    {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          {{- if .Values.ingress.extraPaths }}
          {{- toYaml .Values.ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ include "common.names.fullname" . }}
              servicePort: http
    {{- end }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .name }}
      http:
        paths:
          - path: {{ default "/" .path }}
            backend:
              serviceName: {{ include "common.names.fullname" $ }}
              servicePort: http
    {{- end }}
```
You can see that is uses serviceName and servicePort, but as kubectl explain from my post above shows, this should be:

```yaml
service:
  name: xxx
  port: yyy
```
So ingress.yaml from the chart can't produce ingress manifest compatible with networking.k8s.io/v1 without matter of the settings.

By the way, I use helmfile and here are my settings:

```yaml
helmDefaults:
  kubeContext: redacted
releases:
- name: example-eu
  chart: bitnami/wordpress
  namespace: default
  values:
  - wordpressUsername: redacted
  - wordpressPassword: {{ requiredEnv "WORDPRESS_EXAMPLE_PASSWD" }}
  - wordpressEmail: redacted@gmail.dcom
  - wordpressFirstName: John
  - wordpressLastName: Doe
  - wordpressBlogName: example.eu
  - wordpressTablePrefix: redacted
  - allowEmptyPassword: false
  - allowOverrideNone: true
  - smtpHost: smtp.example.com
  - smtpPort: 587
  - smtpUser: noreply@example.eu
  - smtpPassword: {{ requiredEnv "SMTP_EXAMPLE_PASSWD" }}
  - smtpUsername: noreply@example.eu
  - smtpProtocol: tls
  - service:
      type: ClusterIP
      externalTrafficPolicy: Local
  - persistence:
      enabled: true
      size: 2Gi
  - resources:
      requests:
        memory: 256Mi
        cpu: 100m
  - ingress:
      enabled: true
      hostname: example.eu
      extraHosts:
      - name: www.example.eu
        path: /
      extraTls:
      - hosts:
        - example.eu
        - www.example.eu
        secretName: example-eu-tls
  - mariadb:
      enabled: false
  - externalDatabase:
      host: mariadb.db.svc
      user: redacted
      password: {{ requiredEnv "MARIADB_EXAMPLE_PASSWD" }}
      database: redacted
```

You can probably reproduce the but simply by trying to install the chart on Kubernetes 1.20 or 1.20.1.
But as I said, this is not relevant at all.

**Comment by carrodher** [comment]
Thanks for your explanation. I just created an internal task to fix the issue as there are several Helm Charts using the same ingress template. In the same way, we should keep the backward compatibility with previous k8s versions so it is something we need to check carefully. We will update the issue with more information.

**Comment by acim** [comment]
Yes, I realised the dependency on the common chart and different implementations for different Kubernetes versions and this is why I decided not to provide a PR, which I often do. This time it will require more work, just like you said 😊 Thank you.

**Comment by alexdor** [comment]
@carrodher I've patched the ingress already by introducing a new value (called pathType) and keeping backwards compatibility.  These are the changes that I made on the http key of the ingress:

```yaml
      http:
        paths:
          {{- if .Values.ingress.extraPaths }}
          {{- toYaml .Values.ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ .Values.ingress.path }}
          {{- if  .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
            pathType: {{ default "Prefix" .Values.pathType }}
            backend:
              service:
                name: {{ include "common.names.fullname" $ }}
                port:
                  name: http
          {{- else }}
              serviceName: {{ include "common.names.fullname" . }}
              servicePort: http
          {{- end }}
```

I didn't do a pr because you said that you want to handle it internally (hopefully the above should help), but let me know if you want me to open a pr, I'd be more than happy to do it :)
