### ISSUE TITLE
Issue while creating additional users using Helm chart on Azure Kubernetes Service

### ISSUE THREAD

**Issue by 1993Saurabh** [bitnami/charts#4800]
Hi,
I am currently having an issue while creating the users using Helm charts and Azure Kubernetes Services who can login into the RabbitMQ management console. 

I am using the load_definitions.json file to load it into the Kubernetes secret and then providing the file path to overrides file under extraConfiguration. Below is the content of both the files I am using currently to install the RabbitMQ using Helm chart:

**overrides.yaml**

```yaml
image:
  registry: azure-container-registry.azurecr.io
  repository: bitnami/rabbitmq
  tag: 3.8.2-debian-10-r30

metrics:
  image:
    registry: azure-container-registry.azurecr.io
    repository: bitnami/rabbitmq-exporter
    tag: 0.29.0-debian-10-r28

volumePermissions:
  image:
    registry: azure-container-registry.azurecr.io
    repository: bitnami/minideb
    tag: buster

loadDefinition:
  enabled: true
  existingSecret: "rabbitmq-load-definition"
  
extraConfiguration: |
  load_definitions = /app/load_definition.json

auth:
  password: password
  erlangCookie: OYs54TlVmtxqdaDcu7xc12syQTrZ0nt6
```

**load_definition.json**

```json
{
    "users": [
      {
        "name": "saurabh",
        "password": "Passw0rd12",
        "tags": "administrator"
      },
      {
        "name": "saurabh1",
        "password": "Passw0rd12",
        "tags": "management"
      }
    ],
    "vhosts": [
      {
        "name": "/"
      },
      {
        "name": "/myvhost1"
      }
    ],
    "permissions":[
      {
        "user": "saurabh",
        "vhost": "/",
        "configure": ".*",
        "write": ".*",
        "read": ".*"
      },
      {
        "user": "saurabh1",
        "vhost": "/myvhost1",
        "configure": ".*",
        "write": ".*",
        "read": ".*"
      }
    ]
}
```

The users are not getting created when I install the helm chart in Azure Kubernetes Service cluster. Even though I am not able to login into the RabbitMQ management console using the default user's credentials.

However when I create the users using the following three commands, I am successfully able to login into the console using the below credentials:
```
rabbitmqctl add_user test test
rabbitmqctl set_user_tags test administrator
rabbitmqctl set_permissions -p / test ".*" ".*" ".*"
```
I am not sure where I am doing wrong. May be if anyone out there can help me out in this regard, I would be really grateful.
Any reference or the sample files would be really helpful too.

**Comment by carrodher** [comment]
> The users are not getting created when I install the helm chart in Azure Kubernetes Service cluster. Even though I am not able to login into the RabbitMQ management console using the default user's credentials.

Do you mean the credentials for the users defined in the load_definition or the default credentials set by `auth.password`?

There is a different way to create the load_definition without creating the secret manually. If needed, you can use `extraSecrets` to let the chart create the secret for you. This way, you don't need to manually create it before deploying a release. These secrets can also be templated to use supplied chart values. Just in case there is any issue with the manually created secret. For example:
```yaml
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "users": [
          {
            "name": "{{ .Values.auth.username }}",
            "password": "{{ .Values.auth.password }}",
            "tags": "administrator"
          }
        ],
        "vhosts": [
          {
            "name": "/"
          }
        ]
      }
loadDefinition:
  enabled: true
  existingSecret: load-definition
extraConfiguration: |
  load_definitions = /app/load_definition.json
```

Apart from that, can you check the container logs looking for any entry related to the `load_definitions`?
