### ISSUE TITLE
[bitnami/redis] Slave data directory not found

### ISSUE THREAD

**Issue by EArminjon** [bitnami/charts#4805]
**Which chart**:

I add the following chart as dependencies in my Chart.yaml
```
dependencies:
  - name: redis
    version: 12.2.3
    repository: "https://charts.bitnami.com/bitnami"
```

**Describe the bug**

Master have issue :
```
kubectl logs -f myrelease-redis-master-0
useradd: Permission denied.
useradd: cannot lock /etc/passwd; try again later.
chown: invalid user: 'redis'
←[38;5;6mredis ←[38;5;5m16:43:08.78 ←[0m←[38;5;2mINFO ←[0m ==> ** Starting Redis **
1:C 21 Dec 2020 16:43:08.792 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 21 Dec 2020 16:43:08.792 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 21 Dec 2020 16:43:08.792 # Configuration loaded
1:M 21 Dec 2020 16:43:08.795 * Running mode=standalone, port=6379.
1:M 21 Dec 2020 16:43:08.795 # Server initialized
1:M 21 Dec 2020 16:43:08.796 * Ready to accept connections
```

Slave cannot be created 

```
kubectl describe pod my-release-redis-slave-0

Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  20s                default-scheduler  Successfully assigned staging/myrelease-redis-slave-0 to girk8s-nodepp-101
  Normal   Pulled     16s                kubelet            Successfully pulled image "docker.io/bitnami/minideb:buster" in 1.036042645s
  Normal   Pulling    15s (x2 over 17s)  kubelet            Pulling image "docker.io/bitnami/minideb:buster"
  Normal   Created    14s (x2 over 16s)  kubelet            Created container volume-permissions
  Warning  Failed     14s (x2 over 16s)  kubelet            Error: failed to start container "volume-permissions": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"chown -R 10
01:1001 /data\\n\": stat chown -R 1001:1001 /data\n: no such file or directory": unknown
  Normal   Pulled     14s                kubelet            Successfully pulled image "docker.io/bitnami/minideb:buster" in 1.109908457s

```

**To Reproduce**

1. Add chart to an existing chart as dependencies
2. Helm install

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by EArminjon** [comment]
Fix first part of the error (user add permission denied) 

In your values.yaml, on top :
```
redis:
 securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
```

**Comment by EArminjon** [comment]
Master error fixed when override my values.yaml with the following options :

```
redis:
  volumePermissions:
    enabled: true
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
```

Slave still won't work (/data not found...)

**Comment by EArminjon** [comment]
Note: 

With the following config and the deprecated chart https://github.com/helm/charts/tree/master/stable/redis, it works...

```
redis:
  securityContext:
    enabled: true
    runAsUser: 0
    fsGroup: 2000
```
