### ISSUE TITLE
[bitnami/zookeeper] readinessProbe and livenessProbe failed after enable Zookeeper TLS

### ISSUE THREAD

**Issue by shenqinb** [bitnami/charts#4811]
**Which chart**:
[bitnami/zookeeper]: 6.2.0

**Describe the bug**
After enabling Zookeeper TLS, the livenessProbe and readinessProbe failed, the zookeeper Pod keep READY=0/1, but the Pod is actually working which can be connected via zkCli.  currently it works well after I disable the livenessProbe and readinessProbe. 

**Screen Shut for Pods status:**
![image](https://user-images.githubusercontent.com/5157526/102857493-7b899f80-4463-11eb-885e-2f58f1d3043b.png)

**Output of describing a Pod (kubectl describe pod zookeeper-0 -n zookeeper):**
![image](https://user-images.githubusercontent.com/5157526/102857581-a83db700-4463-11eb-8eb4-a97fc93d8c2e.png)

**TLS configurations in values.yaml:**
```
service:
  type: ClusterIP
  port: 2181
  followerPort: 2888
  electionPort: 3888
  publishNotReadyAddresses: true
  tls:
    client_enable: true
    quorum_enable: true
    disable_base_client_port: true

    client_port: 3181

    client_keystore_path: path/zookeeper-keystore.p12
    client_keystore_password: ****************
    client_truststore_path: path/zookeeper-truststore.jks
    client_truststore_password: ******************

    quorum_keystore_path: path/zookeeper-keystore.p12
    quorum_keystore_password: ******************
    quorum_truststore_path: path/zookeeper-truststore.jks
    quorum_truststore_password: ******************
  annotations: {}
  headless:
    annotations: {}
```

**livenessProbe and readinessProbe configurations in values.yaml:**
```
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
  probeCommandTimeout: 5

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
  probeCommandTimeout: 5
```
