### ISSUE TITLE
[bitnami/kube-prometheus] `additionalScrapeConfigs` for direct config provision.

### ISSUE THREAD

**Issue by jjangga0214** [bitnami/charts#4843]
**Which chart**:
bitnami/kube-prometheus

**Is your feature request related to a problem? Please describe.**
`additionalScrapeConfigsExternal` enforces creating an additional secret. This is cumbersome.

**Describe the solution you'd like**
Enable directly writing scrape config.
For instance, [prometheus-community/kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) enables it by `prometheus.prometheusSpec.additionalScrapeConfigs`, like this.

```yaml
prometheus:
  prometheusSpec:
    # REF: https://github.com/prometheus-community/helm-charts/blob/1b967eed322a618f7007725e48496c9f16120e24/charts/kube-prometheus-stack/values.yaml#L2003
    ## AdditionalScrapeConfigs allows specifying additional Prometheus scrape configurations. Scrape configurations
    ## are appended to the configurations generated by the Prometheus Operator. Job configurations must have the form
    ## as specified in the official Prometheus documentation:
    ## https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config. As scrape configs are
    ## appended, the user is responsible to make sure it is valid. Note that using this feature may expose the possibility
    ## to break upgrades of Prometheus. It is advised to review Prometheus release notes to ensure that no incompatible
    ## scrape configs are going to break Prometheus after the upgrade.
    additionalScrapeConfigs:
      - job_name: 'opentelemetry-collector'
        # metrics_path defaults to '/metrics'
        # scheme defaults to 'http'.      
        static_configs:
          - targets: ['opentelemetry-collector:8889']
```

Thanks!
