### ISSUE TITLE
Possible to set log_format in the nginx helm chart?

### ISSUE THREAD

**Issue by DanTulovsky** [bitnami/charts#4855]
Hi,

In the nginx helm chart, is it possible to change the log_format option?  I specifically would like to use [this](https://grafana.com/grafana/dashboards/12559), but, as a general question, it's not clear how I would change the generated nginx config.  Is serverBlock the right place to do it? is there an example somewhere?

Thank you
Dan

P.S. My config is very straight forward, the following are the overrides:

```
cloneStaticSiteFromGit:
  enabled: true
  repository: https://github.com/DanTulovsky/wetsnow.com.git
  branch: main
  interval: 60

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  httpsPort: 443

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  namespace: monitoring
  selector:
    prometheus: prometheus

pdb:
  create: true
  minAvailable: 1
```
