### ISSUE TITLE
[wordpress] unable to install -- error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "service" in io.k8s.api.networking.v1beta1.IngressBackend

### ISSUE THREAD

**Issue by huang-jy** [bitnami/charts#4866]
**Which chart**:
The name (and version) of the affected chart
**Describe the bug**
Wordpress

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**
Successful deployment of wordpress

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

On deploying, I get this:

```
Release "wordpress-dev" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "service" in io.k8s.api.networking.v1beta1.IngressBackend

```

The chart was able to be deployed yesterday -- was a change made?

I noticed in the closed issues, #4791 which seems similar, but is marked as closed

**Comment by huang-jy** [comment]
Installing the specific chart version 10.1.5 will work, but installing latest (10.2.0) will not

**Comment by alemorcuq** [comment]
Hi, @huang-jy.

Can you share how you are installing the chart?

**Comment by huang-jy** [comment]
I am using helm3 via a makefile, the actual command is:

```
	helm3 upgrade --install --atomic --wait --namespace wordpress-dev \
		--timeout 6000s \
	  wordpress-dev \
	  bitnami/wordpress \
		--create-namespace \
		--version 10.1.5 \
	  --values=wordpress-dev-values.yaml
```


The values.yaml is as follows (some redacted)

```
wordpressEmail: [REDACTED]
wordpressFirstName: "John"
wordpressLastName: "Doe"
wordpressBlogName: "John Doe's Blog"
wordpressScheme: http
wordpressExtraConfigContent: "define( 'WP_CACHE', true );"
healthcheckHttps: false
ingress:
  enabled: true
  certManager: true
  tls: true
  hostname: blog.johndoe.example.com
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: 1G

```
