### ISSUE TITLE
[keycloak] empty page for admin console

### ISSUE THREAD

**Issue by abdennour** [bitnami/charts#4878]
First of all, i am really impressed with the quality of charts released by Bitnami.
I wanna say Kudos to them & to their innovative design pattern!

**Which chart**:
The name (and version) of the affected chart
- chart name: bitnami/keycloak
- chart version: 1.1.5

**Describe the bug**
The Administration console page () is empty (blank) 
**To Reproduce**

1. Go to Home page **https://{{.Values.ingress.hostname}}/auth**
2. Click on 'Administration Console' appears at left : 
![image](https://user-images.githubusercontent.com/1788384/103447862-f6dc2400-4ca1-11eb-91c4-60a48421b049.png)
3. See empty page under https://{{.Values.ingress.hostname}}/auth/admin/master/console/
![image](https://user-images.githubusercontent.com/1788384/103447918-dcef1100-4ca2-11eb-8530-cdd2f91d06be.png)

**Expected behavior**
We expects that the admin console works fine, and it should show login form.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

This is the JS console of the browser: 

![image](https://user-images.githubusercontent.com/1788384/103448167-a3200980-4ca6-11eb-803a-d7ea24d9a180.png)

and This is my values : 

```yaml
global:
  imageRegistry: nexus.company.com
  imagePullSecrets:
    - nexus
  storageClass: nfs-sea

#######################
## DNS configuration ##
#######################
ingress:
  ## Set to true to enable ingress record generation
  enabled: true
  certManager: false
  hostname: sso.devops.company.com
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: vault-issuer
  tls: false

######################
## DB configuration ##
######################
postgresql:
  enabled: false
externalDatabase:
# {{ .Environment.Values.keycloak.dbPass }}
  ## Database host
  ##
  host: keycloak-db-postgresql.auth
  ## Database port
  ##
  port: 5432
  ## non admin username for Keycloak Database
  ##
  user: {{ .Environment.Values.keycloak.dbUser }}
  ## Database password
  ##
  password: {{ .Environment.Values.keycloak.dbPass }}
  ## Database name
  ##
  database: {{ .Environment.Values.keycloak.dbName }}

```
