### ISSUE TITLE
[mongodb-sharded] shard index as a label

### ISSUE THREAD

**Issue by maxisam** [bitnami/charts#4918]
Somehow this change is gone.

https://github.com/bitnami/charts/pull/2166

https://github.com/bitnami/charts/blob/60525899c60309f42520ce0b4f3f4c3b2f27a21e/bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml#L41

master

https://github.com/bitnami/charts/blob/master/bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml

This is the change removed this feature

https://github.com/bitnami/charts/pull/4494

**Comment by carrodher** [comment]
Hi, this feature was not removed it was modified and now it is using a different approach. With the changes in https://github.com/bitnami/charts/pull/4494 all the Bitnami charts are following the same approach for affinity there are some pros in the new approach such as a balanced UX for both advanced Kubernetes admins and less experienced user, opinionated presets but users can still define their own affinity, 100% customizable, or no backward incompatibility; by cons, there is more complexity in the templates.

In the case you are describing, the affinity is set in the [shard-data statefulset](https://github.com/bitnami/charts/blob/master/bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml#L42):
```yaml
{{- if $.Values.shardsvr.dataNode.affinity }}
affinity: {{- include "common.tplvalues.render" (dict "value" $.Values.shardsvr.dataNode.affinity "context" $) | nindent 8 }}
{{- else }}
affinity:
  podAffinity: {{- include "common.affinities.pods" (dict "type" $.Values.shardsvr.dataNode.podAffinityPreset "component" "shardsvr" "context" $) | nindent 10 }}
  podAntiAffinity: {{- include "common.affinities.pods" (dict "type" $.Values.shardsvr.dataNode.podAntiAffinityPreset "component" "shardsvr" "context" $) | nindent 10 }}
  nodeAffinity: {{- include "common.affinities.nodes" (dict "type" $.Values.shardsvr.dataNode.nodeAffinityPreset.type "key" $.Values.shardsvr.dataNode.nodeAffinityPreset.key "values" $.Values.shardsvr.dataNode.nodeAffinityPreset.values) | nindent 10 }}
{{- end }}
```
Those parameters are defined in the _values.yaml_ around [this line](https://github.com/bitnami/charts/blob/master/bitnami/mongodb-sharded/values.yaml#L137).

In the same way, you can find more information in [this README section](https://github.com/bitnami/charts/tree/master/bitnami/mongodb-sharded#setting-pods-affinity).

**Comment by maxisam** [comment]
@carrodher where is the part for variable dataNodeLoopId?

**Comment by maxisam** [comment]
so before I can use 

```yml
              matchLabels:
                shard: "{{ .dataNodeLoopId }}"
```

What should I do now?

**Comment by carrodher** [comment]
Yes, that's true, this option seems to be removed by mistake. I just created a PR to add it again

**Comment by carrodher** [comment]
Basically the option is added back again and some information was included in the values.yaml.
```console
$ helm template . -s templates/shard/shard-data-statefulset.yaml -f values.yaml
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb-sharded
        helm.sh/chart: mongodb-sharded-3.2.9
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: shardsvr
        shard: "0"
    spec:
      affinity:
        matchLabels:
          shard: '0'
...
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb-sharded
        helm.sh/chart: mongodb-sharded-3.2.9
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: shardsvr
        shard: "1"
    spec:
      affinity:
        matchLabels:
          shard: '1'
```
just by setting
```yaml
affinity:
  matchLabels:
    shard: "{{ .dataNodeLoopId }}"
```
in the _values.yaml_
