### ISSUE TITLE
[bitnami/wordpress] -- extraTls block creates additional cert rather than bundle into main

### ISSUE THREAD

**Issue by huang-jy** [bitnami/charts#4924]
**Which chart**:
bitnami/wordpress (latest version)

**Describe the bug**
I want to create a cert that has the main domain (for example www.joebloggs.com) and some subdomains (for example, blog.joebloggs.com and archive.joebloggs.com)

When using the extraTls block, it does not create an ingress that I would expect for a multi-name SSL cert. 

**To Reproduce**

Create an installation with the following ingress override (values.yaml) (annotations optional, replace with a domain you control):

```
ingress:
  enabled: true
  certManager: true
  tls: true
  hostname: www.joebloggs.com
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: 1G
```

This will create a cert successfully. With the ingress formatted like this:

```
    tls:
    - hosts:
      - www.joebloggs.com
      secretName: www.joebloggs.com-tls
```

This is fine and behaves as expected

Now I want to add two additional names to the cert. According to the readme.md (https://github.com/bitnami/charts/tree/master/bitnami/wordpress) and the example in the values.yaml (https://github.com/bitnami/charts/blob/b7836ee7dcb1067e466b772ae626fbc0b4c14cd2/bitnami/wordpress/values.yaml#L481) I use this updated values.yaml override:

```
ingress:
  enabled: true
  certManager: true
  tls: true
  extraTls:
    - hosts:
        - blog.joebloggs.com
        - archive.joebloggs.com
      secretName: extra-ssl-tls      
  hostname: www.joebloggs.com
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: 1G
```

This creates the following ingress block:

```
    tls:
    - hosts:
      - www.joeblogss.com
      secretName: www.joebloggs.com-tls
    - hosts:
      - blog.joebloggs.com
      - archive.joebloggs.com
      secretName: extra-ssl-tls 
```

This would create two TWO certs -- one for www.joebloggs.com and one for blog.joebloggs.com and archive.joebloggs.com.

Is there a reason why we can't do this instead:

```
    tls:
    - hosts:
      - www.joeblogss.com
      - blog.joebloggs.com
      - archive.joebloggs.com
      secretName: www.joebloggs.com-tls
```

This would create one cert rather than two, with all the names covered?

**Expected behavior**
One cert create covering the main host and the alternative names

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
