### ISSUE TITLE
[bitnami/redis-cluster] cluster cannot recover from failing states

### ISSUE THREAD

**Issue by ItsReddi** [bitnami/charts#4935]
**Which chart**:
redis-cluster (4.2.1)

**Describe the bug**
Readiness & liveness probes are killing pods that are in recovery process.
![grafik](https://user-images.githubusercontent.com/3147888/104171694-50132880-5403-11eb-9a15-116aca0d2e09.png)
The problem is that both liveness and readiness will timeout for a long time after:
```
1:S 11 Jan 2021 10:39:51.129 * MASTER <-> REPLICA sync: receiving 1142826033 bytes from master to disk
1:S 11 Jan 2021 10:40:36.520 * MASTER <-> REPLICA sync: Flushing old data  <------
```

**To Reproduce**

1. start a cluster and enable Probes for Example: (already set higher values than the default ones)
```
    livenessProbe:
      enabled: true
      initialDelaySeconds: 120
      periodSeconds: 5
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5
    readinessProbe:
      enabled: true
      initialDelaySeconds: 300
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 10
```
2. Write some data maybe 5GB
3. fail something for example one of the slaves (delete the pod)

**Expected behavior**
Slave must finish the sync otherwise the slave is restarting again and again.
