### ISSUE TITLE
[bitnami/redis-cluster] register instance in global context

### ISSUE THREAD

**Issue by kuznero** [bitnami/charts#4949]
**Which chart**: bitnami/redis-cluster

**Is your feature request related to a problem? Please describe.**

Consider the following excerpt from the values file:

```yaml
cluster:
  externalAccess:
    enabled: true
    type: LoadBalancer
    port: 6379
    loadBalancerIP: []
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "subnet"
      external-dns.alpha.kubernetes.io/hostname: cluster.company.com
```

When generating a template it becomes obvious that `external-dns.alpha.kubernetes.io/hostname` produces same values 3 times (for the number of master nodes).

**Describe the solution you'd like**

Instead what would be needed is to be able to do the following:

```yaml
cluster:
  externalAccess:
    enabled: true
    type: LoadBalancer
    port: 6379
    loadBalancerIP: []
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "subnet"
      external-dns.alpha.kubernetes.io/hostname: cluster-{{ .instance }}.company.com
```

But it is not currently possible.
