### ISSUE TITLE
[bitnami/thanos] add support for mounting existing secret for grpcTLS config in Query

### ISSUE THREAD

**Issue by IbraheemAlSaady** [bitnami/charts#5030]
**Which chart**:
Current chart version: 3.3.0

**Is your feature request related to a problem? Please describe.**
My current issue is providing the config under grpcTLS as plain text. there is no option to provide an existing secret

**Describe the solution you'd like**
A solution would be to provide a configuration for defining an existing secret and mount the secret . Something like this

values.yaml sample config
```YAML
query:
  grpcTLS:
    server:
      secure: true
      cert: ""
      key: ""
      ca : ""

      ## Use existing Secret that contains the ca, key, and cert
      existingSecretName: someSecret # <<< This is a new field
      certFile: "/tls/server/cert.pem" <<< This is a new field
      keyFile: "/tls/server/key.pem" <<< This is a new field
      caFile: "/tls/server/ca.pem" <<< This is a new field
    client:
      # same as server
      ...
```
The query templates will be adjusted. 

Please let me know, I can pick this up and have a PR ready
