### ISSUE TITLE
[mysq,parse,spring-cloud-dataflow] Missing `extraDeploy` templates in some charts.

### ISSUE THREAD

**Issue by randreev1321** [bitnami/charts#5041]
**Which chart**:
mysql: 8.2.4
parse: 14.0.0
spring-cloud-dataflow: 2.5.0

**Describe the bug**
The charts are missing a template file for the `extraDeploy` parameter, the using of which is mentioned in README.md . Because of this, it is not possible to deploy additional manifests that may be needed.

**To Reproduce**

1. Deploy some of the described chart with defined `extraDeploy` parameter. As example:
```
extraDeploy:
- |-
  apiVersion: {{ include "podsecuritypolicy.apiVersion" . }}
  kind: PodSecurityPolicy
  metadata:
    name: {{ template "common.names.fullname" . }}
    labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonAnnotations }}
    annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  spec:
    privileged: false
    volumes:
      - 'configMap'
      - 'secret'
      - 'persistentVolumeClaim'
      - 'emptyDir'
      - 'projected'
    hostNetwork: false
    hostIPC: false
    hostPID: false
    runAsUser:
      rule: 'RunAsAny'
    seLinux:
      rule: 'RunAsAny'
    supplementalGroups:
      rule: 'MustRunAs'
      ranges:
        - min: 1
          max: 65535
    fsGroup:
      rule: 'MustRunAs'
      ranges:
        - min: 1
          max: 65535
    readOnlyRootFilesystem: false
```
2. Check that defined in parameter manifest is missing.

**Expected behavior**
Defined in `extraDeploy` manifests have been deployed.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v3.4.2
```

- Output of `kubectl version`:

```
v1.19.2
```
