### ISSUE TITLE
Trying to enable ACL 

### ISSUE THREAD

**Issue by crevillo** [bitnami/charts#5088]
Hello. I have a question on enabling ACL for consul. 
I'm setting my custom values like this
```
consul:
  metrics:
    enabled: true
  configuration: true
  configmap: |-
    '{
      "primary_datacenter": "dc1",
      "acl": {
        "enabled": true,
        "default_policy": "allow",
        "down_policy": "extend-cache"
      }
    }'
```

When applying those changes the configMap looks like 
```
apiVersion: v1
data:
  config.json: >-
    { "primary_datacenter": "dc1", "acl": { "enabled": true, "default_policy":
    "allow", "down_policy": "extend-cache" } }
  connection.json: |
    {
      "retry_join": ["consul-headless.consul.svc.cluster.local"]
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: consul
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: consul
    argocd.argoproj.io/instance: consul
    helm.sh/chart: consul-9.0.3
  name: consul-configuration
  namespace: consul
```

but still in the pod i can see this kind of erro over and over again. 
```
  2021-01-19T11:36:16.992Z [ERROR] agent.http: Request error: method=GET url=/v1/agent/members?segment=_all from=127.0.0.1:34290 error="ACL not found"
```

Do you know that `ACL not found` means and how to solve this problem? i've read that i should execute `consul acl bootstrap`to generate a "master" token, but when executing that command i get a response from the server saying that `ACL is not enabled`

Thanks for your time.
