### ISSUE TITLE
Adding EKS standard service annotations

### ISSUE THREAD

**Issue by zenbones** [bitnami/charts#5145]
rabbitmq 8.7.2 (also memcached 5.4.2)

Looking to add standard service.annotations for EKS...

```
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      external-dns.alpha.kubernetes.io/hostname: my.dns.name
      external-dns.alpha.kubernetes.io/ttl: 300
```

Unfortunately, the templating chokes on the '-' in external-dns.alpha.kubernetes.io, and I can't find a way around it.

Error: unable to build kubernetes objects from release manifest: unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found 3, error found in #10 byte of ...|.io/ttl":300,"servic|..., bigger context ...|tations":{"external-dns.alpha.kubernetes.io/ttl":300,"service.beta.kubernetes.io/aws-load-balancer-i|...

I know this doesn't have to be because other charts I use which consume service.annotations do not have this problem., for instance, this works without complaint...

```
    service:
      type: {{ .Values.mychart.service.type }}
      {{- with .Values.mychart.service.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```
Any help appreciated.
