### ISSUE TITLE
bitnami/mongodb External Access when set to NodePort is causing external connection to the cluster to fail

### ISSUE THREAD

**Issue by franklin432** [bitnami/charts#5157]
**Which chart**:
```
apiVersion: v2
name: mongodb
version: 10.4.0
appVersion: 4.4.3
```

**Describe the bug**
Users are unable to connect externally to the mongo cluster when externalAccess.enabled and autoDiscovery.enabled are set to true, as well as when externalAccess.service.type is set to NodePort. When attempting to connect it is looking for the internal Kubernetes IP and not the node IP. 

**To Reproduce**
I am using NodePorts instead of LoadBalancers for my setup and am getting the same error in regards to **The server certificate does not match the remote host name. Hostname: {IP1} does not match SAN(s): {the list of CNs configured}.** In my setup to connect to my database node from outside I need the primary and secondary node name/IP in addition to the nodePort. 
I was able to resolve this by including the Pod's IP, which you can simply get from kubectl describe <podName>, into the altNames of the certificate creation in the initContainer. I passed the following as an env variable in the generate-tls-certs initContainer AND the mongodb container:
```
env: 
    - name: MY_POD_IP
      valueFrom: 
          fieldRef: 
             fieldPath: status.podIP
```

I then added as an extra SAN in the altNames of the cert creation, $MY_POD_IP.
```
               DNS.1 = $svc 
               DNS.2 = $my_hostname 
               DNS.3 = $my_hostname.$svc.$MY_POD_NAMESPACE.svc.cluster.local 
               DNS.4 = localhost 
               DNS.5 = 127.0.0.1 
               DNS.6 = $MY_POD_IP
```
$MY_POD_IP represents the IP of the pod, which is the same IP that was showing up in the logs saying the IP did not match the SAN. With this, I am now able to start up the replicaset with no errors because the server certificate, which includes $MY_POD_IP as a SAN, now matches the host name. Also when I bash into the mongo primary pod and attempt to connect internally, I am able to connect using the Pod IP as the host. 
However  when I attempt to connect to my cluster externally via a mongo client on my local desktop, the mongo connection (including the Pod IP as the host, the node port and TLS settings) does not work. The error seen:
```
"The server certificate does not match the remote host name, "attr":{"remoteHost": "nodeName.xxx.com", "certificateNames":"SAN(s):{the list of CNs configured SANs}. 
```

In my environment, when attempting to connect externally, it instead requires the node name or node IP of the node that is hosting the mongodb-0 pod, to be specified as the host and not the actual IP of the pod as stated before. 
You can retrieve this from the kubectl describe <podName> command, under the **Node** section. In order to get each pod in the replicaset to contain this, I included it as an env variable just as I had done before with the IP env. 

I passed the following as an env variable in the generate-tls-certs initContainer and the mongodb container:
```
env: 
    - name: MY_NODE_NAME
      valueFrom: 
          fieldRef: 
             fieldPath: spec.nodeName
```

kubectl describe <mongoPodName-0> gives me the name/IP of the Node that is hosting my mongo primary pod. I retrieve the other pods name/IP in my replicaset this way then attempt to connect to it with:
 ./mongo -u root -p mypassword --host <nodeName0:30007>, <nodeName1:30008> --tls --tlsCertificateKeyFile /tls/mongodb.pem --tlsCAFile /tls/mongodb-ca-cert 

This works for me and I am able to connect externally because the server cert SAN now contains the podIP and the NodeName of the node hosting my mongodb-0 primary pod and the same for my mongodb-1 secondary pod. 

**Expected behavior**
I expect from the changes I have included above for connecting externally to work.
I expect the following to be added to the /replicaset/statefulset.yaml in the **name: generate-tls-certs** section in addition to whatever was originally there, in order for this to work. *NOTE: Make sure to include your own personal domain names in the SAN if needed.
```
env: 
    - name: MY_POD_IP
      valueFrom: 
          fieldRef: 
             fieldPath: status.podIP
    - name: MY_NODE_NAME
      valueFrom: 
          fieldRef: 
             fieldPath: spec.nodeName   
```

```
      DNS.1 = $svc 
      DNS.2 = $my_hostname 
      DNS.3 = $my_hostname.$svc.$MY_POD_NAMESPACE.svc.cluster.local 
      DNS.4 = localhost 
      DNS.5 = 127.0.0.1 
      DNS.6 = $MY_POD_IP
      DNS.7 = $MY_NODE_NAME
```

Of course the values.yaml file should contain the appropriate parameters to enable the NodePort access to look as:
```

## External Access to MongoDB nodes configuration
##
externalAccess:
  ## Enable Kubernetes external cluster access to MongoDB nodes
  ##
  enabled: true
  ## External IPs auto-discovery configuration
  ## An init container is used to auto-detect LB IPs or node ports by querying the K8s API
  ## Note: RBAC might be required
  ##
  autoDiscovery:
    ## Enable external IP/ports auto-discovery
    ##
    enabled: true
.
.
.

```

```
service:
    ## Service type. Allowed values: LoadBalancer or NodePort
    ##
    type: NodePort
    ## Port used when service type is LoadBalancer
    ##
    port: 27017
    ## Array of load balancer IPs for each MongoDB node. Length must be the same as replicaCount
    ## Example:
    ## loadBalancerIPs:
    ##   - X.X.X.X
    ##   - Y.Y.Y.Y
    ##
    loadBalancerIPs: []
    ## Load Balancer sources
    ## ref: https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for- 
          loadbalancer-service
    ## Example:
    ## loadBalancerSourceRanges:
    ## - 10.10.10.0/24
    ##
    loadBalancerSourceRanges: []
    ## Array of node ports used for each MongoDB nodes. Length must be the same as replicaCount
    ## Example:
    nodePorts:
       - ""
       - ""
       - ""

    #nodePorts: []
    ## When service type is NodePort, you can specify the domain used for MongoDB advertised hostnames.
    ## If not specified, the container will try to get the kubernetes node external IP
    ##
    # domain: mydomain.com
    ## Provide any additional annotations which may be required. Evaluated as a template
    ##
    annotations: {}
```

**Version of Helm and Kubernetes**:
```
helm version: v3.3.4
```

- Output of `kubectl version`:

```
Server: 1.14.5
Client: 1.15.11
```
