### ISSUE TITLE
Redis: Error condition on socket for SYNC: No route to host

### ISSUE THREAD

**Issue by elucidsoft** [bitnami/charts#5164]
I don't think this https://github.com/bitnami/charts/pull/3658 is resolved.  I went a while without having this issue, then all the sudden I have had it happen twice in two weeks on our production server using the latest version of the helm package.  

This is very maddening as it seems completely random.  I am using sentinel: enabled, and staticID: true. The error logs don't really contain anything other than the error "Error condition on socket for SYNC: No route to host" and "Could not connect to Redis at 10.20.8.9:26379: Connection timed out".

**Comment by rafariossaa** [comment]
Hi,
  Could you indicate which cluster are you using, the install command or values you are using and if you have some clue about the random conditions? Maybe nodes shutdown or something like this.

**Comment by tom-schoener** [comment]
We have the same problem with our sentinel setup.
That's our config:

```yaml
image:
  tag: 6.0.10-debian-10-r19

metrics:
  enabled: true

existingSecret: "redis-admin-credentials"
existingSecretPasswordKey: "password"

global:
  storageClass: "ssd"

cluster:
  enabled: true
  slaveCount: 2

sentinel:
  masterSet: redis-master
  enabled: true
  service:
    redisPort: 6379
    sentinelPort: 26379
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"
```

We can reproduce the issue by deleting the master pod. We noticed that the second redis node still tries to connect to the old master server, in this case `10.0.0.15:6379`:

```
redis 1:S 18 Feb 2021 13:17:28.504 * Connecting to MASTER 10.0.0.15:6379
redis 1:S 18 Feb 2021 13:17:28.504 * MASTER <-> REPLICA sync started
redis 1:S 18 Feb 2021 13:17:28.506 # Error condition on socket for SYNC: No route to host
```

The new redis node, that starts after we deleted the master pod, now logs:

```
sentinel Could not connect to Redis at 10.0.0.15:26379: Connection timed out
``` 

Indeed, the server at 10.0.0.15 does not exist anymore. The actual Setup and IPs look like this:

```
redis-node-0         1/3                       16 CrashLoopBackOff    10.0.0.16          
redis-node-1         3/3                        0 Running                        10.0.1.17
```

Is this a configuration problem or a problem with the helm chart?
