### ISSUE TITLE
[bitnami/postgres-ha] full TLS support for backend PQ

### ISSUE THREAD

**Issue by danielzhanghl** [bitnami/charts#5170]
**Which chart**:
The name (and version) of the affected chart.
bitnami/postgres-ha
**Is your feature request related to a problem? Please describe.**

right now the PQPool support TLS setting with frontend, and how about backend? 
and seems the PQ database still TLS disabled, is there procedure on how to enable that by this chart?
thanks.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by soonoo** [comment]
@danielzhanghl 
 I'm not sure but below properties might be working. Secret named `postgresql-cert` should exist in your cluseter.
```yaml
postgresql:
  extraVolumes:
    - name: postgresql-cert
      secret:
        secretName: postgresql-cert
        defaultMode: 0640
  extraVolumeMounts:
    - name: postgresql-cert
      mountPath: /var/run/postgresql-cert
  extraEnvVars:
    - name: POSTGRESQL_ENABLE_TLS
      value: "yes"
    - name: POSTGRESQL_TLS_CERT_FILE
      value: "/var/run/postgresql-cert/tls.crt"
    - name: POSTGRESQL_TLS_KEY_FILE
      value: "/var/run/postgresql-cert/tls.key
```
