### ISSUE TITLE
Memcached chart updated to 5.4.3 but using it fails in helm update

### ISSUE THREAD

**Issue by zenbones** [bitnami/charts#5177]
memcached 5.4.3

> helm dependency update ./mydir

Error: can't get a valid version for repositories memcached. Try changing the version constraint in Chart.yaml

**Comment by carrodher** [comment]
It seems you are using Memcached as a subchart, right? What does the `Chart.yaml` (and `Chart.lock`) look like in your parent chart?

If you want to use the latest major version you can define something like the below code block in your `Chart.yaml`:
```yaml
...
dependencies:
  - name: memcached
    repository: https://charts.bitnami.com/bitnami
    version: 5.x.x
...
```
then when running `helm dep update` or `helm dep build` a `charts/` folder with the latest version of Memcached chart (in branch 5) should appear, in the same way, a `Chart.lock` file with the exact version.
