### ISSUE TITLE
[Bitnami / Keycloak] Automatic Keycloak realm import not working

### ISSUE THREAD

**Issue by pixtim** [bitnami/charts#5178]
**Which chart**:
keycloak 1.1.5

**Describe the bug**
Unable to configure chart to import for `realm.json` when setting `KEYCLOAK_IMPORT` environment variable with `-Dkeycloak.profile.feature.upload_scripts=enabled` argument.

**To Reproduce**
- Create a ConfigMap with the `realm.json` content exported from Keycloak UI.
- Mount it to the Keycloak pod and set the `KEYCLOAK_IMPORT` and `KEYCLOAK_EXTRA_ARGS` environment variables.
```
keycloak:
  enabled: true
  auth:
    adminUser: admin
    adminPassword: secret
  extraEnvVars:
    - name: KEYCLOAK_IMPORT
      value: /config/realm.json
    - name: KEYCLOAK_EXTRA_ARGS
      value: -Dkeycloak.profile.feature.upload_scripts=enabled
  extraVolumeMounts:
    - name: config
      mountPath: "/config"
      readOnly: true    
  extraVolumes:
    - name: config
      configMap:
        name: keycloak-realm
        items:
        - key: "realm.json"
          path: "realm.json"
  ingress:
    enabled: true
    hosts:
      - name: keycloak.local
        path: /
        tls: false
    annotations:
      kubernetes.io/ingress.class: public
```
- Notice that the Keycloak logs do not indicate that an import is being attempted. The JVM arguments does not include the system property in the pod logs (but the pod fails to start if I enter an invalid property which indicates that it is considering the property).

**Expected behavior**
I think the pod should start with the `-D` argument set and the pod should pick up the `KEYCLOAK_IMPORT` environment variable and automatically import the realm when Keycloak starts. I'm not sure if I missed something. I think Keycloak would have displayed an import error if something went wrong - but it looks like the import is not starting.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.1-34+e7db93d188d0d1", GitCommit:"e7db93d188d0d12f2fe5336d1b85cdb94cb909d3", GitTreeState:"clean", BuildDate:"2021-01-11T23:48:42Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.1-34+e7db93d188d0d1", GitCommit:"e7db93d188d0d12f2fe5336d1b85cdb94cb909d3", GitTreeState:"clean", BuildDate:"2021-01-11T23:50:46Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
See links:
- http://www.mastertheboss.com/jboss-frameworks/keycloak/keycloak-with-docker
- https://keycloak.discourse.group/t/cant-import-realm-using-docker-image/259/18
I've attached the Keycloak logs, environment variables, and mount.
[mount.txt](https://github.com/bitnami/charts/files/5852158/mount.txt)
[logs-from-keycloak-in-hex-dev-keycloak-0.txt](https://github.com/bitnami/charts/files/5852159/logs-from-keycloak-in-hex-dev-keycloak-0.txt)
[env.txt](https://github.com/bitnami/charts/files/5852160/env.txt)

Thanks for helping. Please let me know if there is another forum I should ask for help. 👍

**Comment by andresbono** [comment]
Hi @pixtim, there are some things that you can try. Some considerations:

- It seems that the `upload_scripts` option is not needed anymore and it is deprecated. See this table: [Server Installation: Profiles](https://www.keycloak.org/docs/11.0/server_installation/#profiles).
- The bitnami/keycloak container doesn't read the `KEYCLOAK_IMPORT` environment-variable, so you will need to specify the path for the file as an argument of the daemon command with `KEYCLOAK_EXTRA_ARGS`.

You can try this alternative `extraEnvVars` block:

```
  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "-Dkeycloak.import=/config/realm.json"
```

Let us know if it works as expected.

**Comment by pixtim** [comment]
Thanks @andresbono! :smiley: 

I used the `keycloak.import` system property and now my realm is being imported.

```yaml
keycloak:
  enabled: true
  auth:
    adminUser: admin
    adminPassword: secret
  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "-Dkeycloak.import=/config/realm.json"      
  extraVolumeMounts:
    - name: config
      mountPath: "/config"
      readOnly: true
  extraVolumes:
    - name: config
      configMap:
        name: keycloak-realm
        items:
        - key: "realm.json"
          path: "realm.json"
  ingress:
    enabled: true
    hosts:
      - name: keycloak.local
        path: /
        tls: false
    annotations:
      kubernetes.io/ingress.class: public
```

The material I used must have been outdated. The helm chart is working really well, thanks Bitnami!

**Comment by michaeljmarshall** [comment]
@andresbono - It'd be great to include the information from this issue in the helm chart's README. Even just a reference to using the `KEYCLOAK_EXTRA_ARGS` and the documentation from keycloak https://www.keycloak.org/docs/latest/server_admin/#_export_import would be really valuable.

**Comment by Mauraza** [comment]
Hi  @michaeljmarshall,

You can find this information in the README.md of the container https://github.com/bitnami/bitnami-docker-keycloak#extra-arguments-to-keycloak-startup

**Comment by dharmendrakariya** [comment]
Any update here?

**Comment by Mauraza** [comment]
Hi @Montralis,


> > Hi @michaeljmarshall,
> > You can find this information in the README.md of the container https://github.com/bitnami/bitnami-docker-keycloak#extra-arguments-to-keycloak-startup
> 
> This page does not exist anymore

This is the new link https://github.com/bitnami/containers/tree/main/bitnami/keycloak#extra-arguments-to-keycloak-startup

**Comment by songhanpoo** [comment]
> Thanks @andresbono! 😃
> 
> I used the `keycloak.import` system property and now my realm is being imported.
> 
> ```yaml
> keycloak:
>   enabled: true
>   auth:
>     adminUser: admin
>     adminPassword: secret
>   extraEnvVars:
>     - name: KEYCLOAK_EXTRA_ARGS
>       value: "-Dkeycloak.import=/config/realm.json"      
>   extraVolumeMounts:
>     - name: config
>       mountPath: "/config"
>       readOnly: true
>   extraVolumes:
>     - name: config
>       configMap:
>         name: keycloak-realm
>         items:
>         - key: "realm.json"
>           path: "realm.json"
>   ingress:
>     enabled: true
>     hosts:
>       - name: keycloak.local
>         path: /
>         tls: false
>     annotations:
>       kubernetes.io/ingress.class: public
> ```
> 
> The material I used must have been outdated. The helm chart is working really well, thanks Bitnami!

They're already updated structure value.yaml
btw, we also create secret by command below
```
❯ kubectl -n dev create secret generic realm-secret --from-file=realm.json
```
It's working on my site, sample value.yaml
```

extraEnvVars:
  - name: KEYCLOAK_EXTRA_ARGS # override values from the conf file
    value: --import-realm

extraVolumes:
  - name: realm-secret
    secret:
      secretName: realm-secret

extraVolumeMounts:
  - name: realm-secret
    mountPath: "/opt/bitnami/keycloak/data/import"
    readOnly: true

```
