### ISSUE TITLE
Unable to use RewriteEngine on htaccess

### ISSUE THREAD

**Issue by ylacaute** [bitnami/charts#5210]
Chart bitnami/wordpress 
helm.sh/chart: wordpress-10.4.6
docker.io/bitnami/wordpress:5.6.0-debian-10-r32

**Describe the bug**
When we add a security plugin (Wordfence or whatever) which update the .htaccess files, Wordpress is not working anymore (many 404, 502 and even, sometimes, 503 HTTP errors).

This ticket focus on `RewriteEngine On` : as soon as we are using it, all urls break and return a 404, excepted the root (mySite.com)

**To Reproduce**
1. Install wordpress as usual
2. Add a .htaccess in the root wordpress directory
3. Add this content, for example:

```
# Block author scans
RewriteEngine On
RewriteBase /
RewriteCond %{QUERY_STRING} (author=\d+) [NC]
RewriteRule .* - [F]
```

**Expected behavior**
No 404

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Maybe the problem come from the way I configured my cluster / ingress / ingress-controller (I am learning K8S)

Extract of the values configuration:
```yaml
values:
  allowOverrideNone: false
  ingress:
    enabled: true
    hostname: sample.com
  tls: true
  backend:
    serviceName: sample
    serviceport: 8080
```

Extract of the created ingress :
```yaml
spec:
  rules:
  - host: sample.com
    http:
      paths:
      - backend:
          service:
            name: sample-wordpress
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
```

From what I understand, nginx redirect mySite:80 to the pod:8080, maybe there a problem with that...
Or maybe we need to use "Allowoverride" but I fixed it to false
Anyway, everythings is working fine untill I configure some security rules in this .htaccess.
