### ISSUE TITLE
[bitnami/wordpress] Usage and syntax for customPostInitScripts

### ISSUE THREAD

**Issue by mamanteg** [bitnami/charts#5231]
Hi,
I'm trying to figure out how customPostInitScripts can be used to run some simple post config in Wordpress like creating additional users or adding plugins and themes to the running container.

First of all I'd like to understand if this is the best way to complete those tasks or maybe you can suggest a better way.
I thought that a user can easily added by adding:

```yaml
customPostInitScripts:
    adduser.sh: |
        #!/bin/bash
        wp user create bob bob@example.com --role=author
```
but apparently the script is not run at all, so I assume I'm missing a piece there.
I'm currently deploying the helm chart through kubeapp, by editing the yaml before the deployment.
