### ISSUE TITLE
Adding possibility to define keystore and truststore secrets separately

### ISSUE THREAD

**Issue by DzeryCZ** [bitnami/charts#5278]
**Which chart**:
Cassandra

**Is your feature request related to a problem? Please describe.**
Currently there is a possibility to pass `truststore` and `keystore` with passwords via k8s secrets and specify the name of the secret in `tlsEncryptionSecretName`. I see there one main limitation: 
- Both the `truststore` and the `keystore` has to be stored in one k8s secret

**Describe the solution you'd like**
I'm affraid, It's hard to solve this without introducting breaking change or adding too much complexity to the chart at this moment.

_Breaking change solution:_
- Change chart variable `tlsEncryptionSecretName` to `tlsEncryption` with this structure:
```yaml
tlsEncryption:
  truststoreSecret: <name-of-a-secret>
  keystoreSecret: <name-of-a-secret>
  truststorePasswordSecret: <name-of-a-secret>
  keystorePasswordSecret: <name-of-a-secret>
```

Additional comlexity solution:
- Leave there `tlsEncryptionSecretName` and add `tlsEncryption` as shown above. But the thing is, that the chart will be more complex. 

---

I can solve this also by using `extraEnvVars` and `extraVolumes`. I was just curious, whether anybody else is limited by this solution.

**Comment by miguelaeh** [comment]
Hi @DzeryCZ ,
In case we implement that, I think we should go for the second option to avoid breaking changes. Other option would be to wait for a new major version to add the changes like the first option your proposed.

**Comment by DzeryCZ** [comment]
At the end we solved it via custom volume configuation.

Posting it here, in case anybody else is interested/needs it.

```yaml
    # Setting up keystore + truststore
    # beginning
    - name: CASSANDRA_INTERNODE_ENCRYPTION
      value: "all"
    - name: CASSANDRA_CLIENT_ENCRYPTION
      value: "true"
    - name: CASSANDRA_TRUSTSTORE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "app-truststore"
          key: "truststore-password"
    - name: CASSANDRA_KEYSTORE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "app-keystore"
          key: "keystore-password"

  extraVolumeMounts:
    - name: encryption-secrets-keystore
      mountPath: /bitnami/cassandra/secrets/keystore
      subPath: keystore.jks
    - name: encryption-secrets-truststore
      mountPath: /bitnami/cassandra/secrets/truststore
      subPath: truststore.jks

  extraVolumes:
    - name: encryption-secrets-keystore
      secret:
        secretName: keystore
    - name: encryption-secrets-truststore
      secret:
        secretName: truststore
    # end
```
