### ISSUE TITLE
phpmyadmin fails to install on v1.19.6-gke.600, no apiVersion for ingress record generated

### ISSUE THREAD

**Issue by itspngu** [bitnami/charts#5280]
**Which chart**:
phpmyadmin-8.1.0

**Describe the bug**
Installation of the chart fails for me because there's no api version being generated for the ingress. Not sure what exactly the cause might be so I'll leave this here for somebody to look at after working around it by specifying the api version in `values.yaml` myself.

**To Reproduce**

1. Enable ingress creation without passing `ingress.apiVersion` or `global.kubeVersion`.
2. Run `helm install phpmyadmin bitnami/phpmyadmin -n phpmyadmin -f values.yaml --debug`
3. Output:

```bash
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /home/pngu/.cache/helm/repository/phpmyadmin-8.1.0.tgz

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: apiVersion not set
helm.go:81: [debug] error validating "": error validating data: apiVersion not set
helm.sh/helm/v3/pkg/kube.scrubValidationError
	/home/circleci/helm.sh/helm/pkg/kube/client.go:580
helm.sh/helm/v3/pkg/kube.(*Client).Build
	/home/circleci/helm.sh/helm/pkg/kube/client.go:173
helm.sh/helm/v3/pkg/action.(*Install).Run
	/home/circleci/helm.sh/helm/pkg/action/install.go:255
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:241
main.newInstallCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
unable to build kubernetes objects from release manifest
helm.sh/helm/v3/pkg/action.(*Install).Run
	/home/circleci/helm.sh/helm/pkg/action/install.go:257
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:241
main.newInstallCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
```

**Expected behavior**
Proper templating of an ingress record.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-gke.600", GitCommit:"12fc96946f2f552033c0345de2219382257670e3", GitTreeState:"clean", BuildDate:"2020-12-29T09:16:20Z", GoVersion:"go1.15.2b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

You can circumvent the problem by specifying apiVersion yourself:

```yaml
# values.yaml
## Ingress configuration
ingress:
  ## Set to true to enable ingress record generation
  enabled: true

  # set this, according to your cluster's version
  apiVersion: "networking.k8s.io/v1"
```

Output of `helm template phpmyadmin bitnami/phpmyadmin -n phpmyadmin -f values.yaml --debug`:

```yaml
# install.go:172: [debug] Original chart version: ""
# install.go:189: [debug] CHART PATH: /home/pngu/.cache/helm/repository/phpmyadmin-8.1.0.tgz

---
# Source: phpmyadmin/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app.kubernetes.io/name: phpmyadmin
    helm.sh/chart: phpmyadmin-8.1.0
    app.kubernetes.io/instance: phpmyadmin
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP

  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      nodePort: null
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      nodePort: null
  selector:
    app.kubernetes.io/name: phpmyadmin
    app.kubernetes.io/instance: phpmyadmin
---
# Source: phpmyadmin/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app.kubernetes.io/name: phpmyadmin
    helm.sh/chart: phpmyadmin-8.1.0
    app.kubernetes.io/instance: phpmyadmin
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: phpmyadmin
      app.kubernetes.io/instance: phpmyadmin
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: phpmyadmin
        helm.sh/chart: phpmyadmin-8.1.0
        app.kubernetes.io/instance: phpmyadmin
        app.kubernetes.io/managed-by: Helm
    spec:

      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "status.localhost"
      affinity:
        podAffinity:

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: phpmyadmin
                    app.kubernetes.io/instance: phpmyadmin
                namespaces:
                  - phpmyadmin
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:

      securityContext:
        fsGroup: 1001
      containers:
        - name: phpmyadmin
          image: docker.io/bitnami/phpmyadmin:5.0.4-debian-10-r80
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1001
          env:
            - name: DATABASE_PORT_NUMBER
              value: "3306"
            - name: DATABASE_HOST
              value: "123.123.123.123"
            - name: PHPMYADMIN_ALLOW_NO_PASSWORD
              value: "false"
            - name: DATABASE_ENABLE_SSL
              value: "no"
            - name: PMA_ABSOLUTE_URI
              value: https://phpmy.admin.org/
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          resources:
            limits: {}
            requests: {}
          volumeMounts:
      volumes:
---
# Source: phpmyadmin/templates/ingress.yaml
apiVersion:         # <--- this right here is broken
kind: Ingress
metadata:
  name: phpmyadmin
  labels:
    app.kubernetes.io/name: phpmyadmin
    helm.sh/chart: phpmyadmin-8.1.0
    app.kubernetes.io/instance: phpmyadmin
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    - host: phpmy.admin.org
      http:
        paths:
          - path:
            pathType: ImplementationSpecific
            backend:
              service:
                name: phpmyadmin
                port:
                  name: http
  tls:
    - hosts:
        - phpmy.admin.org
      secretName: phpmy.admin.org-tls
```

**Comment by dani8art** [comment]
Hi @itspngu ,

Regarding the implementation https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_capabilities.tpl, I did some tests on my local:

```console
$ helm create test-chart
```
**add common dependency to the test-chart**

```yaml
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
```

```console
$ helm dep update test-chart
```

**edit your `test-chart/templates/NOTES.txt`**

```
{{ .Capabilities.KubeVersion }}

{{ include "common.capabilities.ingress.apiVersion" . }}

{{- if semverCompare "<1.19-0" "v1.19.6-gke.600" }}
{{ print "networking.k8s.io/v1beta1" }}
{{- else -}}
{{ print "networking.k8s.io/v1" }}
{{- end }}
```

**then I got this output**

```
$ helm install test test-chart/ --dry-run
NOTES:
v1.16.15-gke.6000

networking.k8s.io/v1beta1
networking.k8s.io/v1
```

So after my tests, it seems the helper is working fine, could you perform those actions in your environment, please? so we can figure out what is happening

**Comment by itspngu** [comment]
Hey! Mine looks a little strange... the versions are on the same line. I guess you formatted your output when posting here?

```bash
$ helm install test test-chart/ --dry-run
[...]
NOTES:
v1.19.6-gke.1700

networking.k8s.io/v1networking.k8s.io/v1
```
But it does seem to provide valid output. Unfortunately GKE rolled out a new release yesterday, but I'm starting to think it's not related to the cluster version - initially I suspected that the helper function doesn't like v19+. 
Perhaps this is more of a hiccup that's specific to what I was doing, so feel free to not spend too much time investigating this issue unless somebody else comes along with the same problem.

Here's the full thing:

```yaml
NAME: test
LAST DEPLOYED: Thu Jan 28 11:11:21 2021
NAMESPACE: default
STATUS: pending-install
REVISION: 1
HOOKS:
---
# Source: test-chart/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "test-test-chart-test-connection"
  labels:
    helm.sh/chart: test-chart-0.1.0
    app.kubernetes.io/name: test-chart
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['test-test-chart:80']
  restartPolicy: Never
MANIFEST:
---
# Source: test-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-test-chart
  labels:
    helm.sh/chart: test-chart-0.1.0
    app.kubernetes.io/name: test-chart
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: test-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-test-chart
  labels:
    helm.sh/chart: test-chart-0.1.0
    app.kubernetes.io/name: test-chart
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: test-chart
    app.kubernetes.io/instance: test
---
# Source: test-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-test-chart
  labels:
    helm.sh/chart: test-chart-0.1.0
    app.kubernetes.io/name: test-chart
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test-chart
      app.kubernetes.io/instance: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-chart
        app.kubernetes.io/instance: test
    spec:
      serviceAccountName: test-test-chart
      securityContext:
        {}
      containers:
        - name: test-chart
          securityContext:
            {}
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}

NOTES:
v1.19.6-gke.1700

networking.k8s.io/v1networking.k8s.io/v1
```
