### ISSUE TITLE
[bitnami/mongodb] Automatically provide rootPassword and replicaSetKey on Helm upgrade

### ISSUE THREAD

**Issue by percenuage** [bitnami/charts#5300]
**Which chart**:
bitnami/mongodb@10.5.1

**Is your feature request related to a problem? Please describe.**
I don't want to provide sensitive secret like `rootPassword `or/and `replicaSetKey` in `values.yaml`. So I let the chart to randomly create for me. The job is doing well! 

However, I'm using this chart as subchart and I often use the command `helm upgrade ...`. So I have to provide  `--set auth.replicaSetKey=$MONGODB_REPLICA_SET_KEY` and `--set auth.rootPassword=$MONGODB_ROOT_PASSWORD` manually (cf. screenshot).

I'm also using `helm upgrade` with continuous integration.

**Describe the solution you'd like**
It would be very good, if the chart can automatically provides these secrets on upgrade.

I think it's possible because these secrets are already existed in kube secret after first install. But I don't know how to do it.

What do you think?

**Describe alternatives you've considered**
Another solution, is to provide by myself these secrets with kube secret like environment variable:
```
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  MONGODB_REPLICA_SET_KEY: xxxxxxxxx
  MONGODB_ROOT_PASSWORD: xxxxxxxxxx
```
And I could use this value in the chart for reference: `extraEnvVarsSecret: my-secret`

**Additional context**
![image](https://user-images.githubusercontent.com/6691104/106135751-a359da80-6168-11eb-9795-d3be60d5626b.png)
