### ISSUE TITLE
External DNS support for ISTIO

### ISSUE THREAD

**Issue by cyperplex** [bitnami/charts#5313]
**Which chart**:
external-dns-4.0.0

**Describe the bug**
In setting up ISTIO to work with external DNS to create and manage DNS records, additional RBAC changes are needed to allow external dns to access the gateway resources under the api group : networking.istio.io. 

The external dns helm chart provides no discernable way to pass in this additional set of permission requirements to the cluster role and as such we are manually executing a patch on the role. 

ie
      kubectl patch clusterrole external-dns --type='json' \
        -p='[{"op": "add", "path": "/rules/4", "value": { "apiGroups": [ "networking.istio.io"], "resources": ["gateways"],"verbs": ["get", "watch", "list" ]} }]'

As identified in:
https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/istio.md

Can the helm chart allow for additional RBAC permissions to be added via the values file?

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. I see that our current RBAC rules have the following

```
  - apiGroups:
      - extensions
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.istio.io
    resources:
      - gateways
      - virtualservices
    verbs:
      - get
      - list
      - watch

```

What would be missing in the rule?
