### ISSUE TITLE
[redis-cluster] zombie processes caused by health checks

### ISSUE THREAD

**Issue by viceice** [bitnami/charts#5328]
**Which chart**:
redis-cluster v4.2.8

**Describe the bug**
Same issue as in #2441 getting zombie processes because of healthchecks

**To Reproduce**

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by viceice** [comment]
```
4048359 ?        Sl     2:15 /var/lib/rancher/k3s/data/8f4b194129852507eab4a55117fc942e0688ec9a70ffdaa5911ccc6652220f76/bin/containerd-shim-runc-v2 -namespace k8s.io -id 2a5e10a7dc5f15c22433da7d65fb9
4048380 ?        Ss     0:00  \_ /pause
4048477 ?        Ssl    1:16  \_ redis-server *:6379
1693178 ?        Z      0:00      \_ [ping_readiness_] <defunct>
2805839 ?        Z      0:00      \_ [ping_readiness_] <defunct>
```

**Comment by FraPazGal** [comment]
Thanks for pointing this @viceice! I have created a PR to fix this that should be merged shortly.

**Comment by viceice** [comment]
I'v again strange zombie issues

![image](https://user-images.githubusercontent.com/1798109/108684632-6c6eae80-74f3-11eb-994e-8c6ad8c597bf.png)

```yaml
image:
  registry: gcr.io
  repository: bitnami-containers/redis-cluster
  tag: 6.0.10

cluster:
  nodes: 6
  replicas: 1

redis:
  resources:
    requests:
      memory: 10Mi
    limits:
      memory: 32Mi
  tolerations:
    - key: kriese.eu/hosted
      operator: Exists
      effect: NoSchedule

persistence:
  enabled: false

existingSecretPasswordKey: password
usePasswordFile: true
```

`existingSecret`  is passed via `set`, chart version is `4.3.1`
