### ISSUE TITLE
[mariadb-galera] Prevent startup of other nodes / Readiness of first node during custom file loading

### ISSUE THREAD

**Issue by cwrau** [bitnami/charts#5336]
**Which chart**:
mariadb-galera version 5.4.0, probably also 5.5.0

**Is your feature request related to a problem? Please describe.**
My problem is, that when I'm using (large / 35MB) initial data, the readinessProbe trips to ready before the initial dump is completely loaded and the real DB started up.

This leads to a race condition (?) between the next node which doesn't load the initial data and just creates an empty DB and is the first to create the cluster.

This, in turn, leads to a couple of restarts of the first node until it just joins the second nodes cluster and clears its own initial data.

**Describe the solution you'd like**
Maybe use another port for the DB that gets started for the initial data, therefore the readinessProbe doesn't trip

But then we'd need a different livenessProbe; a probe that checks either of the ports is open, not just the live one

**Describe alternatives you've considered**
My current workaround is to use the startupProbe, but as this is time-based it's not ideal, as new nodes take a long time to start and might not always work, if the initial loading takes even longer than expected.

**Additional context**

**Comment by migruiz4** [comment]
Hi @cwrau ,

Could you please provide more details about your use case?

What method are you using to load the initial data? Are you modifying any setting inside values.yml?

As a workaround for your issue, I'd say one solution would be initializing your deployment with a single replica, then when the initial data is loaded increase the number of nodes.

The other solution would be the one you are using: increasing the initialDelaySeconds of the readiness probe so the other nodes are not deployed until the first node has been initialized, but that would delay the deployment of all the other nodes.

**Comment by cwrau** [comment]
I'm using an init container to copy the SQL file into the container;

```yaml
      extraVolumes:
        - name: initial-data
          emptyDir:
            medium: Memory
      extraVolumeMounts:
        - name: initial-data
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
      extraInitContainers:
        - name: copy-initial-data
          image: IMAGE
          command:
            - sh
            - -c
            - -ex
            - 'cp /docker-entrypoint-initdb.d/* /initial-data/'
          volumeMounts:
            - name: initial-data
              mountPath: /initial-data
```

That's not an option, as these instances are created automatically
