### ISSUE TITLE
[bitnami/mongodb] pods only deploying to one node

### ISSUE THREAD

**Issue by MichaelMichaelMichaelMichaelMichael** [bitnami/charts#5353]
**Which chart**:
chart: bitnami/mongodb
app version: 4.4.3
chart version: mongodb-10.6.1

**Describe the bug**
Pods of the mongodb replicaset are all deploying on the same node, mostly nuc2. 
```
kubectl get pods -n mongodb  -o wide
NAME                READY   STATUS    RESTARTS   AGE     IP            NODE   NOMINATED NODE   READINESS GATES
mongodb-arbiter-0   1/1     Running   0          3m59s   10.42.8.107   nuc2   <none>           <none>
mongodb-0           1/1     Running   0          3m59s   10.42.8.108   nuc2   <none>           <none>
mongodb-1           1/1     Running   0          3m45s   10.42.8.110   nuc2   <none>           <none>
mongodb-2           1/1     Running   0          3m30s   10.42.8.112   nuc2   <none>           <none>
```
I've noticed that the pods get their own claims:
```
kubectl get pvc -n mongodb 
NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
mongodb-pv-claim    Bound    mongodb-pv-volume                          1200Gi     RWO            manual         21m
datadir-mongodb-0   Bound    pvc-99dbac94-9c8b-4189-a289-db53d75aa47a   8Gi        RWO            local-path     20m
datadir-mongodb-1   Bound    pvc-fe2caa7a-7cdf-4ecd-8524-5ede3944d412   8Gi        RWO            local-path     19m
datadir-mongodb-2   Bound    pvc-ad59003a-41f5-48a1-8414-08d5ceff936d   8Gi        RWO            local-path     19m
```

**To Reproduce**

1. kubectl create ns mongodb
2. kubectl apply -f 01-storage-V2-PV-mongodb.yml
3. kubectl -n mongodb apply  -f 02-mongodb-PV-claim.yml
4. helm install   mongodb --values 03-mongodb.yaml --namespace mongodb bitnami/mongodb
5. kubectl get pods -n mongodb  -o wide
6. kubectl get pvc -n mongodb

**Expected behavior**
Pods of the mongodb replicaset are equally deploying on distinct nodes, max 1 worker per node. The pods shall node share that one directory on nuc2, but worker-0 shall use the directory from nuc0, worker-1 --> nuc1, ... 
The assignation of the pv claims shall proceed correctly so I can use the entire 1200 Gi for MongoDB.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7+k3s1", GitCommit:"5a00e38db4c198fb0725a6b709380aed8053d637", GitTreeState:"clean", BuildDate:"2021-01-14T23:09:37Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/arm64"}
```

**Additional context**
The cluster consists of 7 Raspberry Pi 4Bs and 3 Intel NUCs. On the Intel NUCs, there is an SSD each mounted on /dev/sda1 (formatted as XFS) on which the mongodb files shall reside. MongoDB shall only run on the NUCs (as for the architecture of MongoDB and their speed). The cluster has been install using [k3sup](https://github.com/alexellis/k3sup).  
Architecture of the NUCs:
```
uname -a 
Linux nuc0 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

The Config files:
`01-storage-V2-PV-mongodb.yml:`
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sda1/mongodb"
```
`02-mongodb-PV-claim.yml:`
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1200Gi
```
`03-mongodb.yaml:`
```
architecture: replicaset
replicaCount: 3
persistence:
    existingClaim: "mongodb-pv-claim"
auth:
    rootPassword: secret-root-pwd
arbiter:
        nodeSelector: 
                kubernetes.io/hostname: nuc0
                kubernetes.io/hostname: nuc1
                kubernetes.io/hostname: nuc2
nodeSelector: 
        kubernetes.io/hostname: nuc0
        kubernetes.io/hostname: nuc1
        kubernetes.io/hostname: nuc2
externalAccess:
        enabled: true
externalAccess:
        service:
                loadBalancerIPs:
                        - 192.168.22.200
                        - 192.168.22.201
                        - 192.168.22.202
```
note: 192.168.22.200 .. 202 are the IP addresses of nuc0 .. 2
Thank you in advance for any advice. 
PS: Bonus question, if I may - could I run the arbiter on one of the Raspi nodes? How would I have to deploy that?

**Comment by andresbono** [comment]
Hi @MichaelMichaelMichaelMichaelMichael, you are creating a local PV that is attached to a particular node in your cluster. All the pods that are using that PV will need to be attached to the same node. You can try to disable persistence and you will see that the pods will be scheduled in different nodes, following the scheduler algorithm.

> PS: Bonus question, if I may - could I run the arbiter on one of the Raspi nodes? How would I have to deploy that?

We are not supporting ARM architectures currently, so I'm afraid that the containers won't be able to run on a Raspberry Pi.

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
Hi, thank you for your quick reply. I've tried it, but it all concentrates on one node:
```
$ cat 03-mongodb-test.yaml 
architecture: replicaset
replicaCount: 3
persistence:
        enabled: false
auth:
    rootPassword: secret-root-pwd
arbiter:
        nodeSelector: 
                kubernetes.io/hostname: nuc1
                kubernetes.io/hostname: nuc0
                kubernetes.io/hostname: nuc2
nodeSelector: 
        kubernetes.io/hostname: nuc1
        kubernetes.io/hostname: nuc2
        kubernetes.io/hostname: nuc0
```
I've deleted all PV and PVC definitions and then executed:
```
$ helm install   mongodb --values 03-mongodb-test.yaml --namespace mongodb bitnami/mongodb
...
$ kubectl get pods -n mongodb -o wide
NAME                READY   STATUS    RESTARTS   AGE     IP            NODE   NOMINATED NODE   READINESS GATES
mongodb-arbiter-0   1/1     Running   0          2m34s   10.42.8.157   nuc2   <none>           <none>
mongodb-0           1/1     Running   0          2m34s   10.42.6.80    nuc0   <none>           <none>
mongodb-1           1/1     Running   0          2m20s   10.42.6.81    nuc0   <none>           <none>
mongodb-2           1/1     Running   0          2m14s   10.42.6.82    nuc0   <none>           <none>
```
If I omit the nodeSelectors, then deployments start on the Raspberry Pi nodes (thanks for answering the bonus question, BTW) which is not what I want. So the nodeSelectors are fine. 

I don't know if my approach is feasible at all, but in the end, the storage shall be a locally attached 2TB SDD local drive per node; and if a node crashes, the other nodes shall take over, keeping the replicaSet up. Graphically spoken: 

```
before crash:
+-------------------+ +-----------+ +-----------+
|nuc0:              | |nuc1:      | |nuc2:      |
|                   | |           | |           |
| /dev/sda1         | | /dev/sda1 | | /dev/sda1 |
| mongodb-0         | | mongodb-1 | | mongodb-2 |
| mongodb-arbiter-0 | |           | |           |
+-------------------+ +-----------+ +-----------+

{----------------------rs0----------------------}

after crash of nuc0:
+-------------------+ +-----------+ 
|nuc1:              | |nuc2:      | 
|                   | |           | 
| /dev/sda1         | | /dev/sda1 |
| mongodb-1         | | mongodb-2 | 
| mongodb-arbiter-0 | |           | 
+-------------------+ +-----------+ 

{---------------rs0---------------}

```

**Comment by andresbono** [comment]
Oh, I see the problem now. It is in the way you are defining the node selector:

```
nodeSelector: 
        kubernetes.io/hostname: nuc1
        kubernetes.io/hostname: nuc2
        kubernetes.io/hostname: nuc0
```

This is defining a map (`nodeSelector`) which keys should be unique, but you are repeating the same key (`kubernetes.io/hostname`) 3 times. It takes only one of the values, probably the last one.

 You may want to use a set of labels that are unique in your cluster for the nodes that you want to use for scheduling. Typically, `kubernetes.io/arch` is automatically added to the nodes. You can make use of that one to restrict the pod scheduling onto the amd64 nodes only.

Check the current labels with:

```
$ kubectl get nodes --show-labels
```

Proposed `values.yaml`:

```
architecture: replicaset
replicaCount: 3
auth:
    rootPassword: secret-root-pwd
arbiter:
        nodeSelector:
                kubernetes.io/arch: amd64
nodeSelector:
        kubernetes.io/arch: amd64
```

If you want more advanced settings, you will need to use `affinity` instead of `nodeSelector`: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity

Also please note this comment in the `values.yaml`: https://github.com/bitnami/charts/blob/1d2da656d1da80941741d453b0e8dfcac7a7da9f/bitnami/mongodb/values.yaml#L447-L449

This is due to the fact that a statefulset should be able to scale the number of replicas and this wouldn't be possible if the PVC are not dynamically created.
