### ISSUE TITLE
wordpress | volumePermissions init container takes a long time (chmod -R)

### ISSUE THREAD

**Issue by floek** [bitnami/charts#5371]
**Which chart**:
wordpress-10.6.0

**Is your feature request related to a problem? Please describe.**
See https://github.com/bitnami/charts/issues/2046
With volumePermissions set the pods take a long time to start because the do a `chmod -R` every time on the Wordpress data directory. For the initialisation a simple `chown 1001:1001 /bitnami/wordpress` would be enough.

**Describe the solution you'd like**
Remove `-R`

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by andresbono** [comment]
Hi @floek, thanks for opening this issue.

The volumePermissions init container has two main purposes:

- For cases where the default k8s `runAsUser` and `fsUser` values do not work.
- Change permissions/ownership in volumes with existing data but using old permissions settings that need to be adapted. (In this case `-R` is needed).

Please note that you might want to use the `volumePermissions.enabled=true` parameter only for the first time that you run helm. Following ones will keep the correct permissions as the data is persisted and you can skip the long running command.

**Comment by floek** [comment]
Okay, I don't want to have "special first time only" options in my setup. So I switched from `volumePermissions.enabled=true` to:
```yaml
initContainers:
  - name: volume-permissions
    image: bitnami/minideb
    imagePullPolicy: Always
    command: ['sh', '-c', 'chown 1001:1001 /bitnami/wordpress']
    volumeMounts:
    - mountPath: /bitnami/wordpress
      name: wordpress-data
      subPath: wordpress
```
