### ISSUE TITLE
[bitnami/spark] Ingress backend is set to release name rather than master service

### ISSUE THREAD

**Issue by bbezak** [bitnami/charts#5385]
**Which chart**:
spark-5.1.1

**Describe the bug**
Ingress backend is set to release name rather than master service
https://github.com/bitnami/charts/blob/master/bitnami/spark/templates/ingress.yaml#L34

**To Reproduce**

1. Deploy helm chart:
```
helm install test-spark \
  --set ingress.enabled=true bitnami/spark
```
2. Check services names:
```
kubectl get svc | grep spark
test-spark-headless                  ClusterIP      None             <none>           <none>                       12m
test-spark-master-svc                ClusterIP      10.254.235.90    <none>           7077/TCP,80/TCP              12m
```
3. Check ingress backend name:
```
kubectl get ingress test-spark-ingress -o yaml
...
      paths:
      - backend:
          serviceName: test-spark
          servicePort: http
        path: /
        pathType: ImplementationSpecific
```
**Expected behavior**
Ingress backend should be set to master service name - in this case 'test-spark-master-svc'

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:22:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
