### ISSUE TITLE
kubewatch: missing rbac 'event' permission

### ISSUE THREAD

**Issue by disconn3ct** [bitnami/charts#5410]
**Which chart**:
kubewatch 3.1.0 (binary is 84a34db93f cross-compiled for arm64)

**Describe the bug**
With `rbac.create` enabled, it cannot read events:
`E0205 17:58:07.956683 1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.16.8/tools/cache/reflector.go:96: Failed to list *v1.Event: events is forbidden: User "system:serviceaccount:kubewatch:kubewatch" cannot list resource "events" in API group "" at the cluster scope`

**To Reproduce**
install with `rbac.create: true`, `resourcesToWatch.daemonset: true` (possibly unnecessary)

View logs

**Expected behavior**
Normal startup

**Version of Helm and Kubernetes**:
Helm v3 in-cluster (via fluxcd v2)
K8S 1.19.5+k3s2

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.14-dispatcher", GitCommit:"766e62361387c284022a97270f0997d67ae792d0", GitTreeState:"clean", BuildDate:"2020-12-01T16:13:56Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5+k3s2", GitCommit:"746cf4031370f443bf1230272bc79f2f72de2869", GitTreeState:"clean", BuildDate:"2020-12-18T01:42:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/arm64"}
```

**Additional context**

**Comment by Mauraza** [comment]
Hi @disconn3ct,

I no able to reproduce the problem, could you add more information about where are you running this chart? could you check if appear events in your list of permission?

**Comment by bugok** [comment]
I recently got the same message. It was because I didn't specify `rbac.create: true`. After fixing that - kubewatch started to work properly.

**Comment by disconn3ct** [comment]
I haven't had a chance to retest unfortunately. I had rbac.create set (otherwise there would be no role at all: https://github.com/bitnami/charts/blob/master/bitnami/kubewatch/templates/clusterrole.yaml#L1

I will retest this weekend and report back

**Comment by bugok** [comment]
While trying again, I think I got a repro for this error. 

I'm experiencing this when using a custom image. 

Imagine this values file: 

```
rbac:
  create: true
slack:
  enabled: false
```

Running the following works (error doesn't show up): 
```
helm upgrade -i kubewatch bitnami/kubewatch -f ~/tmp/kubewatch.yaml --version 3.1.2
```

However, when using a custom image, the error shows up: 
```
rbac:
  create: true
slack:
  enabled: false
image:
  registry: 'myregistery.io'
  repository: 'kubewatch'
  tag: '1.0.0'
  pullSecrets:
  - myPullSecret
```

**Comment by bugok** [comment]
https://github.com/bitnami/charts/pull/5709 should fix this.

**Comment by disconn3ct** [comment]
That is perfect. Thanks!!

**Comment by MostafaWael-CA** [comment]
I faced the same issue and needed to solve it manually by adding: 
```
- verbs:
      - get
      - list
      - watch
    apiGroups:
      - events.k8s.io
    resources:
      - events
```
to my ClusterRole.

**Comment by Mostafa-wael** [comment]
I faced the same issue and needed to solve it manually by adding these configurations to my ClusterRole.: 
```
- verbs:
      - get
      - list
      - watch
    apiGroups:
      - events.k8s.io
    resources:
      - events
```


```
Update:
You can achieve the same by adding the same roles to your `rbac` configuration
rbac:
  create: true
  customRoles:
    - apiGroups: ["events.k8s.io"]
      resources: ["events"]
      verbs: ["get", "list", "watch"]
```
