### ISSUE TITLE
Issue with kafka bitnami helm chart ssl handshake failure with prometheus endpoint

### ISSUE THREAD

**Issue by avanichy25** [bitnami/charts#5411]
I have delpoyed kafka bitnami helm charts with client ssl and external access load balancer along with jmx-exporter and kafka-exporter enabled. I am having issue with kafka pods complaining "[2021-02-06 01:42:18,586] INFO [SocketServer brokerId=0] Failed authentication with /xx.xxx.xx.xx (SSL handshake failed) (org.apache.kafka.common.network.Selector)".  The ip is prometheus endpoint.
kafka bitnami charts 

```
annotations:
  category: Infrastructure
apiVersion: v1
appVersion: 2.6.0
description: Apache Kafka is a distributed streaming platform.
home: https://kafka.apache.org/
icon: https://bitnami.com/assets/stacks/kafka/img/kafka-stack-110x117.png
keywords:
- kafka
- zookeeper
- streaming
- producer
- consumer
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: kafka
sources:
- https://github.com/bitnami/bitnami-docker-kafka
version: 11.8.3
```
Prometheus operator:
```
annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts
    - name: Upstream Project
      url: https://github.com/prometheus-operator/kube-prometheus
  artifacthub.io/operator: "true"
apiVersion: v1
appVersion: 0.38.1
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards,
  and Prometheus rules combined with documentation and scripts to provide easy to
  operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus
  Operator.
home: https://github.com/prometheus-operator/kube-prometheus
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
keywords:
- operator
- prometheus
- kube-prometheus
maintainers:
- name: vsliouniaev
- name: bismarck
- email: gianrubio@gmail.com
  name: gianrubio
- email: github.gkarthiks@gmail.com
  name: gkarthiks
- email: scott@r6by.com
  name: scottrigby
- email: miroslav.hadzhiev@gmail.com
  name: Xtigyro
name: kube-prometheus-stack
sources:
- https://github.com/prometheus-community/helm-charts
- https://github.com/prometheus-operator/kube-prometheus
version: 9.4.10
```
