### ISSUE TITLE
Airflow environment variable change during helm install

### ISSUE THREAD

**Issue by jagusztinl** [bitnami/charts#5415]
**Which chart**:
The name (and version) of the affected chart.
azure-marketplace/airflow

**Is your feature request related to a problem? Please describe tasks**

How can I change environment variables like 
AIRFLOW__WEBSERVER__EXPOSE_CONFIG ?

I would like to enable it to help development tasks.

**Describe the solution you'd like**

I would like a possibility  or description to change environment variables during helm instal....

**Describe alternatives you've considered**

Rebuild the Bitnami Airflow images. IT is not enogh flexible.

**Additional context**

**Comment by andresbono** [comment]
Hi @jagusztinl, you can use the following parameter, depending on the node you want to change the environment-variable: `web.extraEnvVars`.

https://github.com/bitnami/charts/blob/15c7d151892faed9a6cd75cf22d1ef28b31b11d2/bitnami/airflow/values.yaml#L121-L123

This is an example of `values.yaml`:

```yaml
web:
  extraEnvVars:
    - name: 'AIRFLOW__WEBSERVER__EXPOSE_CONFIG'
      value: 'True'
    - name: 'AIRFLOW_EMAIL'
      value: 'a@b.c'
```
