### ISSUE TITLE
[bitnami/redis] After failover, there will be two masters (with simple reproducible experiments included!)

### ISSUE THREAD

**Issue by fzyzcjy** [bitnami/charts#5418]
**Which chart**:
redis

**Describe the bug**

Hi thanks for the lib! I do find a bug: After failover, there will be two masters.

Steps:

1. Install the helm chart. Now we will see master pod (pod A) and slave pod (pod B).
2. **Kill** (i.e. delete) the master pod (call it pod A). Kubernetes will auto recreate another master pod (call it pod A2).
3. Verify that pod A2 has **different ip** compared with pod A. (This should be the usual case since k8s never guarantee static ip)
4. Then **both A2 and B think they are masters!** (Verify by, for example: run `INFO replication` and see the roles. Or `SET k v` on both instances, and observe that they do not replicate. Or look at `SENTINEL REPLICAS mymaster`, and see sentinels do not even know the existence of pod A2.) 

Guess of why this happens:

When pod A2 is created, it is configured as a master by the bitnami startup scripts / pod spec. Moreover, it has a brand new ip. Thus, it is as if **this pod A2 is a separate unrelated brand-new redis instance** which has completely **no** relationship with the original pod A/B/sentinels. Thus, it is not recognized, and of course it is not a slave of pod B.

Thanks

**Comment by migruiz4** [comment]
Hi @fzyzcjy,

When using Redis Sentinel it is recommended to use at least 3 replicas to prevent split-brain (The behavior described above).
It can be done by setting `cluster.slaveCount: 3` in your values.yaml.

If you'd like to find more information about this, please check Redis Sentinel documentation: https://redis.io/topics/sentinel

I think the main problem here is the 2-node Redis sentinel cluster being the default because of using the `cluster.slaveCount` setting, so I will also create an internal task to fix it.

Thank you for reporting this, if you have any further questions let me know.

**Comment by ricoberger** [comment]
Hi @migruiz4, we are seeing a similar problem with version `12.7.3` of the Helm chart and the following values:

```yaml
image:
  registry: docker.io
  repository: bitnami/redis
  tag: 6.0.9-debian-10-r66
  pullPolicy: IfNotPresent

fullnameOverride: redis

cluster:
  enabled: true
  slaveCount: 3

sentinel:
  enabled: true
  usePassword: false
  masterSet: mymaster
  initialCheckTimeout: 5
  quorum: 2
  downAfterMilliseconds: 5000
  failoverTimeout: 18000
  parallelSyncs: 1

usePassword: false

tls:
  enabled: false

configmap: |-
  # Disable AOF https://redis.io/topics/persistence#append-only-file
  appendonly no

podDisruptionBudget:
  enabled: true
  minAvailable: 0
  maxUnavailable: 1
```

We have the following Pods running (master is `172.25.0.220`):

```
NAME           READY   STATUS    RESTARTS   AGE     IP             NODE                              NOMINATED NODE   READINESS GATES
redis-node-0   3/3     Running   1          8m33s   172.25.9.114   worker-main-dev-dd554d99c-2f4sr   <none>           <none>
redis-node-1   3/3     Running   3          11m     172.25.0.220   worker-main-dev-dd554d99c-nbj6q   <none>           <none>
redis-node-2   3/3     Running   0          12m     172.25.5.187   worker-main-dev-dd554d99c-hwnf9   <none>           <none>
```

Now we run `k rollout restart statefulset redis-node`, which restarts all Pods, starting with `redis-node-2`.

When `redis-node-2` (IP: `172.25.13.188`) becomes ready, then Redis reports two different masters:

- `redis-node-0` reports `172.25.0.220` as master
- `redis-node-1` is restarted multiple times
- `redis-node-2` reports `172.25.13.188` as master

After some minutes `redis-node-1` becomes ready and reports `172.25.13.188` as master, then `redis-node-0` is restarted and reports `172.25.13.188` as master once it is ready.
