### ISSUE TITLE
[bitnami/grafana-operator] A way to set adminUser and adminPassword

### ISSUE THREAD

**Issue by a0s** [bitnami/charts#5420]
**Which chart**:
grafana-operator

**Is your feature request related to a problem? Please describe.**
Need a way to set `adminUser` and `adminPassword` explicitly.

**Describe the solution you'd like**
We already have `adminUser` and `adminPassword` in [Grafana's CRD](https://github.com/bitnami/charts/blob/99fb55a65204405943730cae845d755836a7026c/bitnami/grafana-operator/crds/grafanas.yaml#L40). So, it would be nice to have same keys existing in the helm chart. For now, it doesn't.

**Describe alternatives you've considered**
There is no alternatives, except fetching auto-generate user/pass after start of grafana.

Running grafana with additional `grafana-config-env`:
```yaml
Containers:
  grafana:
    Environment Variables from:
      grafana-config-env  ConfigMap  Optional: false
    Environment:
      LAST_CONFIG:                 714b3e28131c5eb375f17c78cc9f7f3c3978c47732c4653daef2a34647f0902a
      LAST_DATASOURCES:
      GF_SECURITY_ADMIN_USER:      <set to the key 'GF_SECURITY_ADMIN_USER' in secret 'grafana-admin-credentials'>      Optional: false
      GF_SECURITY_ADMIN_PASSWORD:  <set to the key 'GF_SECURITY_ADMIN_PASSWORD' in secret 'grafana-admin-credentials'>  Optional: false
```
Thus `grafana.envFrom` key with configmap which include `GF_SECURITY_ADMIN_USER` and `GF_SECURITY_ADMIN_PASSWORD` is not helping [by design](https://stackoverflow.com/questions/54398272/override-env-values-defined-in-container-spec).

**Additional context**
version: grafana-operator app_version=3.8.1
