### ISSUE TITLE
[bitnami/moodle] Incorrect type description on ingress annotation values lead to misunderstanding 

### ISSUE THREAD

**Issue by sida-khalibre** [bitnami/charts#5422]
**Which chart**:
bitnami/moodle version 11.0.2

**Describe the bug**
In README  there is incorrect type of ingress annotation values lead to misunderstanding. The "[ ]" is expect to be a list but in vlaues.yaml expect it as key value pair.

**To Reproduce**

1. In custom values.yaml define ingress annotation like: 

      ```
      ingress:
        enable: true
        annotations:
          - traefik.ingress.kubernetes.io/router.entrypoints: websecure
          - traefik.ingress.kubernetes.io/router.middlewares: traefik-secured-header@kubernetescrd
          - traefik.ingress.kubernetes.io/router.tls: "true"
      ```
2. Run helm install will cause error.

**Expected behavior**
Ingress annotation should list as map.

          ```
          ingress:
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.middlewares: traefik-secured-header@kubernetescrd
              traefik.ingress.kubernetes.io/router.tls: "true"
          ```
In README should update is as map of key value.
