### ISSUE TITLE
[bitnami/thanos] query do not start if query.grpcTLS.client.secure is set without TLS config

### ISSUE THREAD

**Issue by Tassatux** [bitnami/charts#5437]
**Which chart**:
bitnami/thanos version >= 3.6.0

**Describe the bug**
The Thanos query refuse to start if no gRPC TLS client config is provided. Before 3.6.0, we could use gRPC TLS client without providing certificates, as described in https://github.com/bitnami/charts/issues/3988.
The PR https://github.com/bitnami/charts/pull/5058 changed this behavior, leading to the following error on query start:

```
level=info ts=2021-02-09T17:15:35.999068898Z caller=client.go:54 msg="enabling client to server TLS"
level=error ts=2021-02-09T17:15:35.999292402Z caller=main.go:130 err="open /tls/client/ca-cert: no such file or directory\nreading client CA\ngithub.com/thanos-io/thanos/pkg/tls.NewClientConfig\n\t/app/pkg/tls/options.go:69\ngithub.com/thanos-io/thanos/pkg/extgrpc.StoreClientGRPCOpts\n\t/app/pkg/extgrpc/client.go:56\nmain.runQuery\n\t/app/cmd/thanos/query.go:262\nmain.registerQuery.func1\n\t/app/cmd/thanos/query.go:161\nmain.main\n\t/app/cmd/thanos/main.go:128\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nbuilding gRPC client\nmain.runQuery\n\t/app/cmd/thanos/query.go:264\nmain.registerQuery.func1\n\t/app/cmd/thanos/query.go:161\nmain.main\n\t/app/cmd/thanos/main.go:128\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\npreparing query command failed\nmain.main\n\t/app/cmd/thanos/main.go:130\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"
```

**To Reproduce**

1. Install chart 3.5.0 with the following values:
```yaml
query:
  enabled: true
  grpcTLS:
    client:
      secure: true
```
2. Upgrade to version >= 3.6.0

**Expected behavior**
Thanos query should start even if no client TLS config is provided.

**Comment by miguelaeh** [comment]
Hi @Tassatux ,
Maybe I misunderstood the issue but at:
```
query:
  enabled: true
  grpcTLS:
    client:
      secure: true
```
you are specifying yo use a secure connection, so that implies to use the certificates.
Did you try `query.grpcTLS.client.secure=false` ?

**Comment by Tassatux** [comment]
My bad, I oversimplified the problem, it only make sense when there stores exposed over TLS:

```yaml
query:
  enabled: true
  grpcTLS:
    client:
      secure: true
  stores:
    - thanos-grpc.cluster1.company.com:443
    - thanos-grpc.cluster2.company.com:443
```

I have the exact same problem than https://github.com/bitnami/charts/issues/3988, I've got multiple cluster exposing Thanos gRPC endpoint via Nginx ingress controller (which only permit gRPC with TLS). As it's not possible to configure per store TLS configuration on Thanos query for now, I only rely on the `--grpc-client-tls-secure` query option to retrieve metrics using TLS, ignoring CA verification of cert identification.

But if I disable this option via `secure: false`, the query start but isn't able to communicate with TLS endpoints:

```
level=warn ts=2021-02-10T09:55:57.099276591Z caller=storeset.go:458 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from thanos-grpc.cluster1.company.com:443: rpc error: code = DeadlineExceeded desc = latest balancer error: connection closed" address=thanos-grpc.cluster1.company.com:443
level=warn ts=2021-02-10T09:55:57.099357907Z caller=storeset.go:458 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from thanos-grpc.cluster2.company.com:443: rpc error: code = DeadlineExceeded desc = latest balancer error: connection closed" address=thanos-grpc.cluster2.company.com:443
```

So I guess keeping options `--grpc-client-tls-{cert,key,ca}` modular is a good idea since they're not mandatory on Thanos query and we couldn't express yet per store TLS configuration (https://github.com/thanos-io/thanos/issues/977)

**Comment by miguelaeh** [comment]
Hi @Tassatux ,
In that case, with the configuration you provided the flag `--grpc-client-tls-secure` should be the only one set.
I think the issue is that the `/tls/client/ca.pem` will not be created since the `query.grpcTLS.client.ca` is not set, and from the log you shared, it seems that Thanos requires it:
> level=error ts=2021-02-09T17:15:35.999292402Z caller=main.go:130 err="open /tls/client/ca-cert: no such file or directory

**Comment by Tassatux** [comment]
This doesn't seem to be the case:

```
helm template thanos-test bitnami/thanos --set "query.grpcTLS.client.secure=true" --set "query.stores[0]=thanos-grpc.cluster1.company.com:443" --set "query.stores[1]=thanos-grpc.cluster2.company.com:443" --version 3.8.4
```

```yaml
      containers:
        - name: query
          image: docker.io/bitnami/thanos:0.18.0-scratch-r0
          imagePullPolicy: "IfNotPresent"
          args:
            - query
            - --log.level=info
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --query.replica-label=replica
            - --store=thanos-grpc.cluster1.company.com:443
            - --store=thanos-grpc.cluster2.company.com:443
            - --grpc-client-tls-secure
            - --grpc-client-tls-cert=/tls/client/tls-cert
            - --grpc-client-tls-key=/tls/client/tls-key
            - --grpc-client-tls-ca=/tls/client/ca-cert
```

I've submited a PR to bring back the old behavior while keeping the new `query.grpcTLS.client.existingSecret` option: https://github.com/bitnami/charts/pull/5457
