### ISSUE TITLE
[bitnami/redis] Replicas on different nodes

### ISSUE THREAD

**Issue by avadhanij** [bitnami/charts#5440]
Relative newbie to k8s, and I wanted to know if there is a way to bring up the replica stateful sets on different individual k8s nodes. 

I understand this what daemon sets are used for, but this chart is using stateful sets. I can separate the master and replicas by setting different node selectors, but it would be cool to actually have the replicas them selves on different nodes. This provides true HA, and quorum requirements for sentinels when nodes need to be taken down for maintenance.

Is this possible? Or am I getting this all wrong?

**Comment by migruiz4** [comment]
Hi @avadhanij ,

I think the solution you are looking for is pod [affinity/anti-affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity).

In this case, if you wanted each replica to be allocated in a different host, you'd need to set antiAffinity similar to this:
```
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
               podAffinityTerm:
                 labelSelector:
                   matchLabels:
                     app: 'redis'
                     release: RELEASE-NAME
                 topologyKey: kubernetes.io/hostname
```

The bitnami/redis chart configures your pods by default with the labels `app`, `release`, and `chart` labels, but you could also add custom labels to your pods using `podLabels` and use them for your antiAffinity selector.

When using the above configuration, Kubernetes will not deploy a new pod where an existing pod matching the labels `app` and `release` is already running. But you have to keep in mind you can only have as many replicas as Kubernetes hosts.

I hope it helps.
