### ISSUE TITLE
[bitnami/airflow] worker pods are scaled to Maximum size, even though there is no workloads/DAGS running

### ISSUE THREAD

**Issue by iAshishHere** [bitnami/charts#5444]
**Which chart**:
bitnami/airflow

**Describe the bug**
Airflow worker pods are autoscaled to Max, even though there is no DAGS/Workloads running.

**To Reproduce**

helm repo add bitnami https://charts.bitnami.com/bitnami

helm install my-release airflow

Below mentioned is the configuration I am using in my Helm chart.

`executor: 'CeleryExecutor'`

```
worker:
   resources:
      limits:
         cpu: 250m
         memory: 10Gi
       requests:
         memory: 256Mi
         cpu: 100m
```

```
worker:
  autoscaling:
      enabled: true
      replicas:
        min: 1
        max: 7
      targets:
        cpu: 70
        memory: 70      
```
**See error**

All the worker pods ( kubectl get pods )

![image](https://user-images.githubusercontent.com/29349091/107502454-acae6280-6bbe-11eb-896c-345f7abdf923.png)

See the current memory utilization, its 317%  (kubectl get hpa)

![image](https://user-images.githubusercontent.com/29349091/107502320-88528600-6bbe-11eb-9003-df9a1c3a1f2c.png)

**Expected behavior**
Since there is no workload/DAGs present, it is not supposed to autoscale to maximum replica count.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v3.4.2"
```

- Output of `kubectl version`:

```
v1.16.10
```

**Additional context**
I am not sure what metrics (request and limits) should be kept for default which is consumed by the worker nodes, but according to me, if there are no workload/DAGs then there is no point in all the workers running unnecessarily.
I am using **CeleryExecutor** and below is the image I am using for worker nodes.
```
worker:
  image:
      registry: docker.io
      repository: bitnami/airflow-worker
      tag: 1.10.14-debian-10-r43
```

**Comment by carrodher** [comment]
In order to reproduce the issue, can you share with us the values you are using to deploy the chart? In the beginning, you mention some values related to the worker resources and autoscaling, apart from that, as the additional context you're also referring to a different image (with different I mean, not the default one included in the chart). Apart from that, are you doing any extra customization? It's just to try to reproduce the issue with the exact parameters you're using.

On the other hand, it would be useful to know the chart version you are using, since the Airflow chart is using by default the Airflow 2.X version since some weeks ago, but you are replacing the worker image with Airflow 1.X, so I am not sure if this can be causing some issues. Can you confirm what is the chart version and what version of Airflow is used in that chart?

**Comment by iAshishHere** [comment]
Following are the images I am using.
```
web:
  image:
    registry: docker.io
    repository: bitnami/airflow
    tag: 1.10.14-debian-10-r41
```
```
scheduler:
  image:
    registry: docker.io
    repository: bitnami/airflow-scheduler
    tag: 1.10.14-debian-10-r43
```
```
worker:
  image:
      registry: docker.io
      repository: bitnami/airflow-worker
      tag: 1.10.14-debian-10-r43
```
I have used Azure File share to mount my dags
```
airflow: 
  storageaccount:
    secret: "sa-secret"
  externalmount:
    azurefileshare: true

  azurefileshare:
    dags: airflow-dag
    plugins: airflow-plugins
    logs: airflow-logs
    test: airflow-tests
    requirement: requirement
```

   
Rest all to default values.
