### ISSUE TITLE
[bitnami/airflow] Unable to mount the dags folder or logs folder to EFS PV 

### ISSUE THREAD

**Issue by ashishmgofficial** [bitnami/charts#5451]
**Which chart**:
8.0.3

**Describe the bug**
Not able to mount the dags [ /opt/bitnami/airflow/dags or /opt/bitnami/airflow] as well as logs folder to Amazon EFS . Also no provision for s3 remote logging found in the chart

**To Reproduce**

1. Create PV and PVC as below :
pv.yaml

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <File system ID>
```

pvc.yaml

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 3Gi
```

2. Create deploy.yaml for providing mount information for each web, scheduler and worker section 

```
  extraVolumeMounts:
    - name: airflow-web
      mountPath: /opt/bitnami/airflow
  extraVolumes:
      - name: airflow-web
        persistentVolumeClaim:
          claimName: airflow-claim

```

3. deploy the chart using helm install -f deploy.yaml airflow .....

**Expected behavior**
Dag folder and Log folder mounted successfully and able to deploy dags from EFS . Also able to see worker pod logs from UI (Now it complains worker not found )
