### ISSUE TITLE
[bitnami/discourse] Add support for persistant volume selector to discourse chart pcv.yaml

### ISSUE THREAD

**Issue by ArcticSnowman** [bitnami/charts#5454]
**Which chart**:
Discourse

**Is your feature request related to a problem? Please describe.**
Add selector support to the PVC template

**Describe the solution you'd like**
In the values.yaml 
```yaml
persistence:
  enabled: true
  ## discourse & sidekiq data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  ##
  ## If you want to reuse an existing claim, you can pass the name of the PVC using
  ## the existingClaim variable
  # existingClaim: your-claim
  accessMode: ReadWriteMany
  size: 10Gi
  selector:
    matchLabels:
       <label>:<value>
```
This would generate a selector clause for the PVC.   Similar to what the Postgresql and Redis template do.
