### ISSUE TITLE
[bitnami/rabbitmq] unable to set tag_queries

### ISSUE THREAD

**Issue by reyerdam** [bitnami/charts#5462]
**Which chart**:
bitnami/rabbitmq 8.9.2

**Describe the bug**
setting ldap: tag_queries_management and tag_queries_administrator and vhost acess failed in new format with json errors.

**To Reproduce**
the following advancedConfig:

```
advancedConfiguration: |-
## LDAP configuration
##
ldap:
  enabled: true
  ## List of LDAP servers hostnames
  ##
  servers: [ldap.internalcom.local]
  ## LDAP servers port
  ##
  #port: "636"
  bind_password: "XXXXXXX"
  user_dn_pattern: "uid=${username},ou=users,ou=tooluser,ou=accounts,o=internalcom,c=US"
  other_bind: "uid=tooluser,ou=accounts,ou=services,o=internalcom,c=US"
  tag_queries_administrator: "{in_group,"uid=12345,ou=roles,ou=mytool,ou=accounts,o=internalcom,c=US"}"
  tag_queries_management: "{constant, true}" 
  vhost_access_query: true
  resource_access_query: true 
  
  tls:
    ## If you enabled TLS/SSL you can set advaced options using the advancedConfiguration parameter.
    ##
    enabled: false

```

1. Line https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml#L276

also the Documentation gives no hint how to deal with the new config format for ldap also.

**Expected behavior**
tag queries should be configurable using the new config format instead of the old one.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Version:"v3.3.4
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
documentation about ldap at bitnami doesn't show a working example for setting tags the new format way.
