### ISSUE TITLE
[postgresql] one has to provide `existingSecret` to create one on the fly

### ISSUE THREAD

**Issue by Morriz** [bitnami/charts#5463]
In order to provide passwords so that those do not get re-generated every time, it is now needed to provide `existingSecret` which, according to the docs, should point to a pre-deployed secret, when in fact it is being used to create a secret on the fly.

Sample values:
```yaml
authProxy:
  enabled: false
  external: true
postgresql:
  existingSecret: zoomazumzum
  postgresqlPassword: duzzitmadda
  replication:
    password: agennoshomo
securityContext:
  enabled: true
```

**Comment by Morriz** [comment]
I had to do a lot to figure this out, and I deem this to be a bug. The docs might be ok, but the workings should reflect those docs.

**Comment by javsalgar** [comment]
Hi,

Let me see if I understand this correctly. When you specify existingSecret, is it creating a secret with the name `zoomazumzum`? Another option to not regenerate the secret would be providing the `postgresqlPassword` and `replication.password` values.

**Comment by Morriz** [comment]
But as you can see I did. If I leave `postgresql.existingSecret` empty it will create its own with generated passwords

**Comment by javsalgar** [comment]
Hi,

Could you specify which exact chart you are using? Are you using the bitnami/postgresql chart or you are using another chart that has the bitnami/postgresql as a subchart? If you are using bitnami/postgresql, then the existingSecret and password sections should not go inside the `postgresql` map.

**Comment by Morriz** [comment]
I am using the `kubeapp` chart.

**Comment by javsalgar** [comment]
Hi,

I checked the kubeapps chart, and I see this

```
# Source: kubeapps/templates/db-secret-bootstrap.yaml
apiVersion: v1
kind: Secret
metadata:
  name: zoomazumzum
  annotations:
    helm.sh/hook: pre-install
  labels:
    chart: kubeapps-5.1.0
    helm.sh/chart: kubeapps-5.1.0
    release: kubeapps
    app.kubernetes.io/instance: kubeapps
    heritage: Helm
    app.kubernetes.io/managed-by: Helm
data:
  postgresql-password: "MDkwdzZ2dHN4Mg=="
  postgresql-replication-password: "RkY4RmwzMkRWWA=="
```

In this case, my advice would be to check with the kubeapps team (as we are only mirroring the kubeapps chart here). https://github.com/kubeapps/kubeapps/issues
