### ISSUE TITLE
[bitnami/mongodb] Permission denied using Minikube and volumePermissions set to true

### ISSUE THREAD

**Issue by krinklesaurus** [bitnami/charts#5501]
**Which chart**:
`bitnami/mongodb version: 9.0.0`

**Describe the bug**
I try to run MongoDB locally using the Helm chart on Minikube. The init container to change the permissions of the mounted folder runs with no errors and returns 0, but the ownership remains 1000:1000 instead of 1001:1001. I tried to change the ownership manually running a Busybox container with the same security context as the `volume-permissions` container but no success. 

**To Reproduce**

1. Start Minikube using Virtualbox on MacOS. $LOCAL_DATA_DIR is set to an arbitrary directory.
```
minikube start --driver=virtualbox \
                --mount --mount-string="$(LOCAL_DATA_DIR):/tmp/data"
```

2. Install StorageClass
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

3. Install PersistentVolume:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: mongodb
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data/mongodb"
```

4. Install Namespace
```
apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
```

5. Install PersistentVolumeClaim
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: mongodb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

6. Install MongoDB using Helm chart:
```
# Source: mongodb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-9.0.0
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
secrets:
  - name: mongodb
---
# Source: mongodb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-9.0.0
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  mongodb-root-password:  "some-password"
---
# Source: mongodb/templates/standalone/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-9.0.0
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
      nodePort: null
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/component: mongodb
---
# Source: mongodb/templates/standalone/dep-sts.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-9.0.0
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
      app.kubernetes.io/instance: mongodb
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb
        helm.sh/chart: mongodb-9.0.0
        app.kubernetes.io/instance: mongodb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: mongodb
    spec:
      
      serviceAccountName: mongodb
      securityContext:
        fsGroup: 1001
      initContainers:
        - name: volume-permissions
          image: docker.io/bitnami/minideb:buster
          imagePullPolicy: "Always"
          command:
            - /bin/bash
            - -ec
          args:
            - |
              mkdir -p /bitnami/mongodb
              chown -R "1001:1001" "/bitnami/mongodb"
          securityContext:
            runAsUser: 0
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: datadir
              mountPath: /bitnami/mongodb
      containers:
        - name: mongodb
          image: docker.io/bitnami/mongodb:4.2.8-debian-10-r39
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-root-password
            - name: ALLOW_EMPTY_PASSWORD
              value: "no"
            - name: MONGODB_SYSTEM_LOG_VERBOSITY
              value: "0"
            - name: MONGODB_DISABLE_SYSTEM_LOG
              value: "no"
            - name: MONGODB_ENABLE_IPV6
              value: "no"
            - name: MONGODB_ENABLE_DIRECTORY_PER_DB
              value: "yes"
          ports:
            - name: mongodb
              containerPort: 27017
          livenessProbe:
            exec:
              command:
                - pgrep
                - mongod
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: datadir
              mountPath: /bitnami/mongodb
              subPath: 
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: mongodb-pvc
```

MongoDB container output from `kubectl logs -f pod/mongodb-[podid] -n mongodb` is

```
mongodb 15:17:19.05
mongodb 15:17:19.05 Welcome to the Bitnami mongodb container
mongodb 15:17:19.05 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 15:17:19.05 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 15:17:19.06
mongodb 15:17:19.06 INFO  ==> ** Starting MongoDB setup **
mongodb 15:17:19.07 INFO  ==> Validating settings in MONGODB_* env vars...
mkdir: cannot create directory '/bitnami/mongodb/data': Permission denied
```
and Pod description is

```
Name:         mongodb-849758754d-4vz7r
Namespace:    mongodb
Priority:     0
Node:         minikube/192.168.99.111
Start Time:   Mon, 15 Feb 2021 16:16:39 +0100
Labels:       app.kubernetes.io/component=mongodb
              app.kubernetes.io/instance=mongodb
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=mongodb
              helm.sh/chart=mongodb-9.0.0
              pod-template-hash=849758754d
Annotations:  <none>
Status:       Running
IP:           172.17.0.6
IPs:
  IP:           172.17.0.6
Controlled By:  ReplicaSet/mongodb-849758754d
Init Containers:
  volume-permissions:
    Container ID:  docker://50143b838c6a607eb83a88b95f33df4aadcf34664175244c80aa2440a992f419
    Image:         docker.io/bitnami/minideb:buster
    Image ID:      docker-pullable://bitnami/minideb@sha256:216724a074ba5ea5d08db0376059fb21ada97f8a13769d5c7e5f0ab1e72f3e01
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
      -ec
    Args:
      mkdir -p /bitnami/mongodb
      chown -R "1001:1001" "/bitnami/mongodb"

    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 15 Feb 2021 16:16:47 +0100
      Finished:     Mon, 15 Feb 2021 16:16:47 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /bitnami/mongodb from datadir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from mongodb-token-xdgbr (ro)
Containers:
  mongodb:
    Container ID:   docker://e4c91c8435991018d21f775259b1ebbca66555e3375917a2a68105b1aaa48f87
    Image:          docker.io/bitnami/mongodb:4.2.8-debian-10-r39
    Image ID:       docker-pullable://bitnami/mongodb@sha256:3752a5f89467d2808c0875058225a8c09eae11fd68cc71a40b751559f0d77034
    Port:           27017/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 15 Feb 2021 16:18:01 +0100
      Finished:     Mon, 15 Feb 2021 16:18:01 +0100
    Ready:          False
    Restart Count:  3
    Liveness:       exec [pgrep mongod] delay=30s timeout=5s period=10s #success=1 #failure=6
    Readiness:      exec [mongo --eval db.adminCommand('ping')] delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:                    false
      MONGODB_ROOT_PASSWORD:            <set to the key 'mongodb-root-password' in secret 'mongodb'>  Optional: false
      ALLOW_EMPTY_PASSWORD:             no
      MONGODB_SYSTEM_LOG_VERBOSITY:     0
      MONGODB_DISABLE_SYSTEM_LOG:       no
      MONGODB_ENABLE_IPV6:              no
      MONGODB_ENABLE_DIRECTORY_PER_DB:  yes
    Mounts:
      /bitnami/mongodb from datadir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from mongodb-token-xdgbr (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  datadir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mongodb-pvc
    ReadOnly:   false
  mongodb-token-xdgbr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mongodb-token-xdgbr
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  2m4s               default-scheduler  Successfully assigned mongodb/mongodb-849758754d-4vz7r to minikube
  Normal   Pulling    2m3s               kubelet            Pulling image "docker.io/bitnami/minideb:buster"
  Normal   Pulled     116s               kubelet            Successfully pulled image "docker.io/bitnami/minideb:buster" in 7.50652583s
  Normal   Created    116s               kubelet            Created container volume-permissions
  Normal   Started    116s               kubelet            Started container volume-permissions
  Normal   Pulling    115s               kubelet            Pulling image "docker.io/bitnami/mongodb:4.2.8-debian-10-r39"
  Normal   Pulled     85s                kubelet            Successfully pulled image "docker.io/bitnami/mongodb:4.2.8-debian-10-r39" in 29.674416388s
  Normal   Created    42s (x4 over 85s)  kubelet            Created container mongodb
  Normal   Started    42s (x4 over 85s)  kubelet            Started container mongodb
  Normal   Pulled     42s (x3 over 85s)  kubelet            Container image "docker.io/bitnami/mongodb:4.2.8-debian-10-r39" already present on machine
  Warning  BackOff    26s (x8 over 84s)  kubelet            Back-off restarting failed container
```

Using `minikube ssh` gives me the following ownership info
```
drwxr-xr-x 1 docker docker 64 Feb 15 15:16 /tmp/data/mongodb
```

Using a busybox container with the same security context as the `volume-permissions` container shows me
```
drwxr-xr-x    1 1000     1000            64 Feb 15 15:16 /bitnami/mongodb
```

**Expected behavior**
The ownership of the /bitnami/mongodb should be 1001:1001 so MongoDB container can access the folder

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

thanks for any help
