### ISSUE TITLE
[bitnami/spark] Spark helm chart does not support setting seLinuxOptions

### ISSUE THREAD

**Issue by bbezak** [bitnami/charts#5503]
**Which chart**:
spark-5.1.2

**Describe the bug**
Spark helm chart does not support setting seLinuxOptions. It is a problem on SElinux enabled k8s nodes, when using shared storage as extraVolumes for spark workers - several workers are not able to access shared PVCs.

**To Reproduce**

1. Deploy spark helm chart with extra volumes on SElinux enabled k8s nodes
```
cat >values-spark.yaml <<END
---
master:
  extraVolumes:
    - name: spark-data
      persistentVolumeClaim:
        claimName: spark-data
  extraVolumeMounts:
    - name: spark-data
      mountPath: '/sparkdata'
worker:
  extraVolumes:
    - name: spark-data
      persistentVolumeClaim:
        claimName: spark-data
  extraVolumeMounts:
    - name: spark-data
      mountPath: '/sparkdata'
END

helm install test-spark bitnami/spark --values values-spark.yaml
```
2. Try to access shared storage from pod that has different SElinux context
```
kubectl exec -it test-spark-worker-0 bash -- ls -la /sparkdata
ls: cannot open directory '/sparkdata': Permission denied
command terminated with exit code 2
```

**Expected behavior**
Ability to set seLinuxOptions via Spark statefulset securityContext 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:22:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
