### ISSUE TITLE
mariadb-galera does not bootstrap after failure

### ISSUE THREAD

**Issue by meezaan** [bitnami/charts#5507]
<!--
 Before you open the bug report please review the following troubleshooting guide:

 - [Troubleshoot Bitnami Helm Chart Issues](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues)
 -->

**Which chart**:
mariadb-galera - both 5.5.0 and 5.5.1

**Describe the bug**
When trying to bootstrap the cluster after a crash using values in the YAML, none of the correct env variables are set.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a values.yml file with the following:
```
bootstrap:
## Node to bootstrap from, you will need to change this parameter in case you want to bootstrap from other node
##
  bootstrapFromNode: 0
  ## Force safe_to_bootstrap in grastate.date file.
  ## This will set safe_to_bootstrap=1 in the node indicated by bootstrapFromNode.
  ##
  forceSafeToBootstrap: true
```
2. Upgrade the helm chart.
3. SSH into the the helm chart
4. Run ``` echo $NODE_ID```, it's null.
5. Run ```echo $MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP```, it's empty.
6. Run ```echo $MARIADB_GALERA_CLUSTER_BOOTSTRAP```, it's empty.

I would expect to see values in all of these, but I don't. This to me means that when the container starts up, the startup script does not run correctly, which I can see is:

```                                                                                                                                                                                                                                                            
# Bootstrap from the indicated node   
                                                                                                                                                                                                                                
NODE_ID="${MY_POD_NAME#"db-mariadb-galera-"}"                                                                                                                                                                                                                               if [[ "$NODE_ID" -eq "0" ]]; then                                                                                                                                                                                                                                      
          export MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes                                                                                                                                                                                                                        
          export MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes                                                                                                                                                                                                                         fi

```

**Expected behavior**
I would expect $NODE_ID to be 0 and MARIADB_GALERA_CLUSTER_BOOTSTRAP and MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP to be yes.

**Version of Helm and Kubernetes**:
Helm v3.5.2 and Kubernetes v19.

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I was just doing some testing on recovery before releasing this into production. Not sure if I am doing something wrong.

**Comment by juan131** [comment]
Hi @meezaan 

Your values.yaml should look like this instead (please note you were missing the `galera` level):

```yaml
## Galera configuration
##
galera:
  ## Bootstraping options
  ## ref: https://github.com/bitnami/bitnami-docker-mariadb-galera#bootstraping
  ##
  bootstrap:
  ## Node to bootstrap from, you will need to change this parameter in case you want to bootstrap from other node
  ##
    bootstrapFromNode: 0
    ## Force safe_to_bootstrap in grastate.date file.
    ## This will set safe_to_bootstrap=1 in the node indicated by bootstrapFromNode.
    ##
    forceSafeToBootstrap: true
```

--- 

Are you also passing the `rootUser.password`, `db.password` and `galera.mariabackup.password` parameters when upgrading the chart? Please note you could face credentials issues if you don't use the same ones that were used during the 1st installation of the chart. Find more info at:

- https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera#upgrading
