### ISSUE TITLE
Add ingressClassName field for newer version of K8s

### ISSUE THREAD

**Issue by felixep** [bitnami/charts#5514]
**Which chart**:
WordPress

**Is your feature request related to a problem? Please describe.**
Could you please add compatibility with K8s 1.18+ by adding the ingressClassName field to the ingress definition. For more information you can check [here](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/)

 
This can be done by adding an extra parameter to the values.yml file and a three lines to the ingress definition as follow

```
ingress:
  ## Set to true to enable ingress record generation
  ##
  enabled: false

  ## IngressClassName is used to reference the IngressClass that should be used to implement this Ingress.
  ## This is required for Kubernetes 1.18+ versions. 
  ## ref: https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/
  ## 
  ingressclassname: ingressClassName
```

```
spec:
  {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
  ingressClassName: {{ .Values.ingress.ingressclassname | quote }}
  {{- end }}
  rules:

```
