### ISSUE TITLE
Grafana ldap.enabled=true doesn't setup grafana.ini

### ISSUE THREAD

**Issue by adrianovieira** [bitnami/charts#5532]
**Which chart**:
The name (and version) of the affected chart
grafana-5.2.3

**Describe the bug**

Even when I set `ldap.enabled: true` on my own values it doesn't setup `grafana.ini`. It remains like:

```toml
[auth.ldap]
;enabled = false
;config_file = /etc/grafana/ldap.toml
;allow_sign_up = true
```

**To Reproduce**

1. set you ldap values, e.g.:
```yaml
ldap:
  enabled: true
  allowSignUp: false
  ## configMap with LDAP configuration file (ldap.toml)
  configMapName: grafana-ldap-toml
```
2. helm install ... e.g.:  `helm install grafana bitnami/grafana -n grafana --values myvalues.yml`
3. check `grafana.ini` `[auth.ldap]`, e.g:
    `kubectl -n grafana exec grafana-54d86b565f-jp5cd cat conf/grafana.ini`

**Expected behavior**
That `[auth.ldap]` block be updated if `ldap.enabled: true`

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by miguelaeh** [comment]
Hi @adrianovieira ,
I have been able to reproduce the issue. Indeed there are not log related to LDAP after signin. I will create an internal task to check it in deeper.
Thank you for reporting.
Regards

**Comment by AndrewwHummer** [comment]
Did you find a solution to this? 
We are currently facing the same problem.
Thanks!

**Comment by adedamolalawal** [comment]
There is a `grafana.ini` value in the values.yaml you need to configure.
```
grafana.ini:
      auth.ldap:
        enabled: true
        allow_sign_up: false
        config_file: /etc/grafana/ldap.toml
```

This should fix the issue.
