### ISSUE TITLE
Notary returning 500 when trying to notary init

### ISSUE THREAD

**Issue by anthonyvetter** [bitnami/charts#5551]
**Which chart**:
The name (and version) of the affected chart
Harbor chart version 2.1.3

**Describe the bug**
After deploying Harbor and Notary, and setting up TLS, I run
```
❯ notary -s https://<notary-domain>:<port> -d ~/.docker/trust init <registry-domain>/<project>/<repo>
Root key found, using: <hash>
Enter passphrase for root key with ID <hash>:
Enter passphrase for new targets key with ID <hash>:
Repeat passphrase for new targets key with ID <hash>:
Enter passphrase for new snapshot key with ID <hash>:
Repeat passphrase for new snapshot key with ID <hash>:
Enter username: <registry-username>
Enter password:

* fatal: unable to reach trust server at this time: 500.
```
If I run the same command but purposefully put in incorrect creds, I get a 401: Unauthorized, so at least that step is happening. 

I am new to Notary so this is likely NOT a bug in the code or anything. But following guides and talking to others, I am not sure what I am doing wrong here. 

**To Reproduce**

1. Install Harbor `helm install harbor bitnami/harbor -f harbor-values.yaml -n harbor`
Values file:
```
harborAdminPassword: some-secure-password

service:
  type: ClusterIP
  tls:
    enabled: true
    existingSecret: harbor-tls-prod
    notaryExistingSecret: notary-tls-prod

ingress:
  enabled: true
  hosts:
    core: registry.example.org
    notary: notary.example.org
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod  # use letsencrypt-staging as the cluster issuer for TLS certs
    ingress.kubernetes.io/force-ssl-redirect: "true"     # force https, even if http is requested
    kubernetes.io/ingress.class: contour                 # using Contour for ingress
    kubernetes.io/tls-acme: "true"                       # using ACME certificates for TLS
externalURL: https://registry.example.org

portal:
  tls:
    existingSecret: harbor-tls-prod
```
I used xip.io, contour, and lets-encrypt for TLS and routing. This is installed on GKE.
2. create a project and registry in harbor
3. run `notary -s https://<notary-domain>:<port> -d ~/.docker/trust init <registry-domain>/<project>/<repo>`

**Expected behavior**
I expect that the Notarty server should be reachable.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
❯ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
❯ k version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.15-gke.800", GitCommit:"fa6f8f9671a3ba4b1790bac677bb72b04204e8fc", GitTreeState:"clean", BuildDate:"2020-12-21T09:19:13Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by juan131** [comment]
Hi @anthonyvetter 

There are two parameters (see https://github.com/bitnami/charts/tree/master/bitnami/harbor#harbor-registry-parameters)  that define the user/password to be used to access Harbor Registry, see:

Parameter | Description | Default
-- | -- | --
registry.credentials.username | The username for accessing the registry instance, which is hosted by htpasswd auth mode. More details see official docs. | harbor_registry_user
registry.credentials.password | The password for accessing the registry instance, which is hosted by htpasswd auth mode. More details see official docs. It is suggested you update this value before installation. | harbor_registry_passwor

I assume that you're using these values, right?

**Comment by juan131** [comment]
Hi @anthonyvetter 

I was able to reproduce the issue and I'm trying to figure out what's going on...

I found errors like the one below in my notary server pod:

```
{"go.version":"go1.15.6","http.request.host":"notary.juan.cluster","http.request.id":"113fc0ce-319e-426a-a4e2-c5e878a7a76f","http.request.method":"GET","http.request.remoteaddr":"10.142.0.57","http.request.uri":"/v2/registry.juan.cluster/newproject/minideb:latest/_trust/tuf/timestamp.key","http.request.useragent":"Go-http-client/1.1","level":"error","msg":"500 GET timestamp key: rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0\"","registry.juan.cluster/newproject/minideb:latest":"gun","time":"2021-02-19T11:47:30Z"}
```

**Comment by juan131** [comment]
I mean, I left the `notary.secretName` empty (null), so `notary-signer-ca.crt`, `notary-signer.crt` and `notary-signer.key` were auto-generated (see https://github.com/bitnami/charts/blob/master/bitnami/harbor/templates/notary/notary-secret.yaml#L15)

Parameter | Description | Default
-- | -- | --
notary.secretName | Fill the name of a kubernetes secret if you want to use your own TLS certificate authority, certificate and private key for notary communications. The secret must contain keys named notary-signer-ca.crt, notary-signer.key and notary-signer.crt that contain the CA, certificate and private key. They will be generated if not set. | nil

**Comment by anthonyvetter** [comment]
Logs from Notary pod, basically this, repeated:
`2021/02/22 23:47:04 grpc: Server.Serve failed to complete security handshake from "10.76.1.1:55524": EOF`
I too left `notary.secretName' empty

**Comment by juan131** [comment]
Hi @anthonyvetter 

I could get it working (even using self-signed certificates) after applying the fix available on this PR. This is the **values.yaml** I used:

```yaml
```

notary --tlscacert /etc/docker/certs.d/registry.juan.cluster/ca.crt -s https://notary.juan.cluster -d /tmp/trust init registry.juan.cluster/project/minideb

**Comment by juan131** [comment]
Hi @anthonyvetter 

I could get it working (even using self-signed certificates) after applying the fix available on the PR i just referenced. This is the **values.yaml** I used:

```yaml
harborAdminPassword: some-secure-password
service:
  type: ClusterIP
  tls:
    enabled: true
ingress:
  enabled: true
  hosts:
    core: registry.juan.cluster
    notary: notary.juan.cluster
  annotations:
    kubernetes.io/ingress.class: nginx
externalURL: https://registry.juan.cluster
```

```console
$ helm install harbor bitnami/harbor -f values.yaml
```

> Note: I modified my `/etc/hosts` associating `registry.juan.cluster` and `notary.juan.cluster` to the IP where the NGINX Ingress Controller I have in my cluster is exposed.

As you can see, everything is self-signed. To be able to login with `docker login` and push containers with `docker push`, I had to do a trick to trust the certificates.

```console
$ mkdir -p /etc/docker/certs.d/registry.juan.cluster/
$ kubectl get secrets harbor-ingress -o json | jq -r '.data["ca.crt"]' | base64 --decode > /etc/docker/certs.d/registry.juan.cluster/ca.crt
$ kubectl get secrets harbor-ingress -o json | jq -r '.data["tls.crt"]' | base64 --decode > /etc/docker/certs.d/registry.juan.cluster/registry.juan.cluster.cert
$ kubectl get secrets harbor-ingress -o json | jq -r '.data["tls.key"]' | base64 --decode > /etc/docker/certs.d/registry.juan.cluster/registry.juan.cluster.key
```

After that, I published a container in a new project I created in Harbor named `project`:

```console
$ docker login registry.juan.cluster
Authenticating with existing credentials...
Login Succeeded
$ docker pull bitnami/minideb
$ docker tag bitnami/minideb:latest registry.juan.cluster/project/minideb:latest
$ docker push registry.juan.cluster/project/minideb
```

Finally, I used `notary` (note I added `--tlscacert` to trust the CA):

```consolse
$ notary --tlscacert /etc/docker/certs.d/registry.juan.cluster/ca.crt -s https://notary.juan.cluster -d /tmp/trust init registry.juan.cluster/project/minideb
```
