### ISSUE TITLE
[grafana] mkdir: cannot create directory '/opt/bitnami/grafana/data/plugins': Permission denied

### ISSUE THREAD

**Issue by adrianovieira** [bitnami/charts#5568]
**Which chart**:
The name (and version) of the affected chart

Grafana-5.2.3
```yaml
image:
  registry: docker.io
  repository: bitnami/grafana
  tag: 7.4.2
```

**Describe the bug**

Trying to mount a PV/PVC from a nfs storage (NAS).

**To Reproduce**

1. alocate space and share it from NAS
2. create a PV: `grafana-data-pv`
3. create a PVC: `grafana-data-pvc`
4. define _values_
   ```yaml
    persistence:
      enabled: true
      storageClass: "-"
      existingClaim: grafana-data-pvc
      accessMode: ReadWriteMany
      size: 10Gi
   ````
5. `helm install grafana -n grafana-staging bitnami/grafana --values myvalues.yml`
6. check pod logging: `kubectl -n grafana-staging logs <pod_name>`
   ```
   mkdir: cannot create directory '/opt/bitnami/grafana/data/plugins': Permission denied
   ```
**Expected behavior**

That shared mount point mounted on containers for grafana data

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

- PV
<details>

```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: <nas-nfsserver.local>
    path: "/GRAFANA-DATA"
```
</details>

- PVC
<details>

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: grafana-data-pv
  resources:
    requests:
      storage: 10Gi
```
</details>
