### ISSUE TITLE
[bitnami/kafka] Default Kafka-Config values override in values.yaml

### ISSUE THREAD

**Issue by sveba** [bitnami/charts#5578]
Why do you need to change the default config values for the kafka brokers in the values.yaml? I mean: https://github.com/bitnami/charts/blob/91dbd11bcdd9284029e5857235b0b7b0ddade1b5/bitnami/kafka/values.yaml#L122-L207

Logs directory is the only value, where I see, that a change is needed. The other props are not required by the docker image and are in some cases impossible to override. Like this one, I would like to change it to default value of `9223372036854775807`. This is not possible, because the value is being parsed to `int`: 
https://github.com/bitnami/charts/blob/91dbd11bcdd9284029e5857235b0b7b0ddade1b5/bitnami/kafka/values.yaml#L131

**Comment by juan131** [comment]
Comments added on your PR @sveba

**Comment by sveba** [comment]
@juan131 
Thank you for your comment.

I would like to discuss the general problem with predefined values.  

1. What is the intension of setting those? 
2. Why not go with default Apache-Kafka values and let the user decide what to change, if needed. The Bitnami-Kafka-Image can be run without setting any ENVVAR

**Comment by juan131** [comment]
Honestly I don't know it @sveba 

I just saw these default values have been there since the very beginning, see:

- https://github.com/bitnami/charts/pull/681/files#diff-eb48889a737011f08ce276531652461851fa335e5988268092b6698e44870cce

@tompizmor do you remember where this comes from or what's the reason to use them?

**Comment by tompizmor** [comment]
I may know the reason...

The first version of the chart (and the kafka container) didn't support configuring all Kafka properties through env vars (that feature was added in #1202) so we only exposed the main properties with the Kafka default values at that time. 

Right now, as we can set any kafka property with `KAFKA_CFG_XXX` env vars, it wouldn't be necessary to maintain those properties configuration in the values.yaml.

Taking the `logFlushIntervalMessages` as an example, currently is set in the _values.yaml_ as:

```
## The number of messages to accept before forcing a flush of data to disk.
##
logFlushIntervalMessages: _10000
```


and it is used from _statefulset.yaml_ as:

```
            - name: KAFKA_CFG_LOG_FLUSH_INTERVAL_MESSAGES
              value: {{ .Values.logFlushIntervalMessages | replace "_" "" | quote }
```


The same could be accomplish if we delete the previous blocks and simply define this extra environment variable in the values.yaml:

```
## All the parameters from the configuration file can be overwritten by using environment variables with this format: KAFKA_CFG_{KEY}
## ref: https://github.com/bitnami/bitnami-docker-kafka#configuration
## Example:
## extraEnvVars:
##   - name: KAFKA_CFG_BACKGROUND_THREADS
##     value: "10"
##
extraEnvVars:
  - name: KAFKA_CFG_LOG_FLUSH_INTERVAL_MESSAGES
     value: "10000"
```
