### ISSUE TITLE
[bitnami/redis] readOnlyRootFilesystem

### ISSUE THREAD

**Issue by ANGkeith** [bitnami/charts#5600]
**Which chart**:
redis-12.7.4

**Describe the bug**
Pods is unable to start when running as readOnlyRootFilesystem, producing the following error message
``` bash
/run.sh: line 23: cannot create temp file for here-document: Read-only file system
```

**To Reproduce**

Install the helm chart using the following values.yaml
``` yaml
containerSecurityContext:
  enabled: true
  readOnlyRootFilesystem: true
```

**Expected behavior**
Expected the redis to be running
