### ISSUE TITLE
Provide syncTimeZone option

### ISSUE THREAD

**Issue by fangzhengjin** [bitnami/charts#5630]
**Is your feature request related to a problem? Please describe.**
Provide syncTimeZone option

**Describe the solution you'd like**
Since not all charts currently provide extraVolumeMounts and extraVolumes options, when these two options are not provided, I cannot customize the time zone of the container synchronization node, and the time zone of the container synchronization node should be a very common operation, whether to consider adding the option ?

**Describe alternatives you've considered**

Add `global.syncTimeZone` option, when set to true, the node time zone is automatically mounted to the container.

Temporary method, in the chart that provides extraVolumeMounts and extraVolumes options, you can configure it like this:

```yaml
extraVolumeMounts: 
  - name: local-time
    mountPath: /etc/localtime
    readOnly: true
extraVolumes:
  - name: local-time
    hostPath:
      path: /etc/localtime
```
