### ISSUE TITLE
not able to add config map in bitnami postgreql  using  values.yaml

### ISSUE THREAD

**Issue by prakashmnnit81** [bitnami/charts#5633]
I am trying to add config map in bitnami postgreqsql  from values.yaml using option  but unable to see config map in deployment 
primary:  
    extraVolumes: | 
      - name: testscript
        configMap:
          name: testconfig         
    extraVolumeMounts: |
      - mountPath: /test/temp
        name: testscript

**Comment by javsalgar** [comment]
Hi,

Could you check that in the generated yaml you see the proper section  for the configmap? kubectl get pods -o yaml <name of the statefulset>

**Comment by prakashmnnit81** [comment]
hello @javsalgar,
Thanks for replying, I have generated the yaml after sending the above command  below is response not found the volumemount with above name
![image](https://user-images.githubusercontent.com/24299719/109694696-1a8fed80-7bb1-11eb-9ccf-1d78f5625e1c.png)

**Comment by javsalgar** [comment]
Hi,

I used this

```
primary:
  extraVolumes:
    - name: testscript
      configMap:
        name: testconfig
  extraVolumeMounts:
    - mountPath: /test/temp
      name: testscript
```

Ran `helm install --debug --dry-run` to see the generated YAML and got this

```
...
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: data
              mountPath: /bitnami/postgresql
              subPath:
            - mountPath: /test/temp
              name: testscript

...

      volumes:
        - configMap:
            name: testconfig
          name: testscript
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
```

Could you confirm that you are using the proper YAML formatting?
