### ISSUE TITLE
Keycloak with KUBE_PING will sometimes fail and manifest as failed redirect, also upgrading to higher replica count fails

### ISSUE THREAD

**Issue by doctorpangloss** [bitnami/charts#5634]
**Which chart**:
`keycloak-2.1.2`

**Describe the bug**
A failure in `KUBE_PING` leads to a successful installation and good liveness/readiness but login to the admin console will fail with a redirect.

Not sure yet what would aggravate KUBE_PING failure on install because it's not consistent.

**To Reproduce**

1. Configure with:
    ```
    replicaCount: 1
    serviceDiscovery:
      enabled: false
    ```
2. `helm install --debug keycloak bitnami/keycloak --values=./keycloak-values.yaml`
3. Everything works.
4. Upgrade (to force the issue to repro) or install originally (spotty?) with:
    ```
    replicaCount: 2
    serviceDiscovery:
      enabled: true
    ```
3. Observe the following error in console:

```
[0m[0m22:38:09,698 INFO  [org.jgroups.protocols.kubernetes.KUBE_PING] (ServerService Thread Pool -- 60) namespace default set; clustering enabled
[0m[33m22:38:13,164 WARN  [org.jgroups.protocols.kubernetes.KUBE_PING] (ServerService Thread Pool -- 60) failed getting JSON response from Kubernetes Client[masterUrl=https://10.96.0.1:443/api/v1, headers={Authorization=#MASKED:911#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@587954f0] for cluster [ejb], namespace [default], labels [null]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [java.io.IOException: Server returned HTTP response code: 403 for URL: https://10.96.0.1:443/api/v1/namespaces/default/pods]]
...
[0m[33m22:38:40,281 WARN  [org.jgroups.protocols.kubernetes.KUBE_PING] (thread-5,null,keycloak-1) failed getting JSON response from Kubernetes Client[masterUrl=https://10.96.0.1:443/api/v1, headers={Authorization=#MASKED:911#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@587954f0] for cluster [ejb], namespace [default], labels [null]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [java.io.IOException: Server returned HTTP response code: 403 for URL: https://10.96.0.1:443/api/v1/namespaces/default/pods]]
```
4. Observe you can't log into the admin console because it will not correctly build a session.

**Expected behavior**
`KUBE_PING` needs a permission that the chart is not given, at least, by default on `minikube` for my testing purposes.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Probably just a matter of configuring the service account correctly.

**Comment by doctorpangloss** [comment]
Basically you need something like this?

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jgroups-kubeping-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jgroups-kubeping-api-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jgroups-kubeping-pod-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "bitnami-keycloak.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
```
