### ISSUE TITLE
Kube-prometheus: variable format for additionnal jobs configuration

### ISSUE THREAD

**Issue by RomainPhil** [bitnami/charts#5642]
**Which chart**:
chart : kube-prometheus-4.1.1  
app Version: 0.46.0 

**Describe the bug**
For an integration with istio i want to add the job description to get the different metrics from istio component

got the following issue:

`Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Prometheus.spec.configMaps[0]): invalid type for com.coreos.monitoring.v1.Prometheus.spec.configMaps: got "map", expected "string"`

the yml i've integrate is okay for me but maybe it's not the right variable to modifiate

**To Reproduce**

1. after the default installation `helm install prometheus bitnami/kube-prometheus`
2. Update the variable prometheus.configmaps: with 

```
  configMaps: 
  - job_name: 'pilot'
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - istio-system

    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: istio-pilot;http-monitoring

```
3. `helm upgrade -f values-update.yml  prometheus bitnami/kube-prometheus`

**Expected behavior**
 
I've expected the config map to be accepted and after that the prometheus to start recoling data from istio component

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
$ helm version
version.BuildInfo{Version:"v3.5.1", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.7"}  
```

- Output of `kubectl version`:

```
$ kubectl  version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

this helm chart is actually deployed on Windows 10  kubernetes desktop with the default configuration for istio without other configuration

for the same istio configuration 

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: default
  values:
    global:   
      istioNamespace: istio-system
```
