### ISSUE TITLE
[bitnami/kafka] `extraDeploy` doesn't render with example in documentation

### ISSUE THREAD

**Issue by adamlehenbauer-cubic** [bitnami/charts#5649]
**Which chart**:
bitnami/kafka

**Describe the bug**
When using the `extraDeploy` parameter as the documentation indicates, the template fails to render with the message:

```
Error: template: kafka-bitnami/charts/kafka/templates/extra-list.yaml:1:17: executing "kafka-bitnami/charts/kafka/templates/extra-list.yaml" at <.Values.extraDeploy>: range can't iterate over - apiVersion: v1
...
```

**To Reproduce**

1. Create a trivial chart depending on the bitnami/kafka chart, e.g.

```
apiVersion: v2
name: kafka-bitnami
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: kafka
    version: 12.9.4
    repository: https://charts.bitnami.com/bitnami
```

2. Give a values.yaml with the documented `extraDeploy` value:

```
kafka:
  extraDeploy: |-
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: {{ include "kafka.fullname" . }}-connect
        labels: {{- include "common.labels.standard" . | nindent 6 }}
          app.kubernetes.io/component: connector
      spec:
        replicas: 1
        selector:
          matchLabels: {{- include "common.labels.matchLabels" . | nindent 8 }}
            app.kubernetes.io/component: connector
        template:
          metadata:
            labels: {{- include "common.labels.standard" . | nindent 10 }}
              app.kubernetes.io/component: connector
          spec:
            containers:
              - name: connect
                image: KAFKA-CONNECT-IMAGE
                imagePullPolicy: IfNotPresent
                ports:
                  - name: connector
                    containerPort: 8083
                volumeMounts:
                  - name: configuration
                    mountPath: /opt/bitnami/kafka/config
            volumes:
              - name: configuration
                configMap:
                  name: {{ include "kafka.fullname" . }}-connect
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: {{ include "kafka.fullname" . }}-connect
        labels: {{- include "common.labels.standard" . | nindent 6 }}
          app.kubernetes.io/component: connector
      data:
        connect-standalone.properties: |-
          bootstrap.servers = {{ include "kafka.fullname" . }}-0.{{ include "kafka.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.service.port }}
          ...
        mongodb.properties: |-
          connection.uri=mongodb://root:password@mongodb-hostname:27017
          ...
    - apiVersion: v1
      kind: Service
      metadata:
        name: {{ include "kafka.fullname" . }}-connect
        labels: {{- include "common.labels.standard" . | nindent 6 }}
          app.kubernetes.io/component: connector
      spec:
        ports:
          - protocol: TCP
            port: 8083
            targetPort: connector
        selector: {{- include "common.labels.matchLabels" . | nindent 6 }}
          app.kubernetes.io/component: connector
```

3. Attempt to render the chart, e.g. `helm install kafka --dry-run -f kafka-bitnami/values-demo.yaml kafka-bitnami`

**Expected behavior**

For the chart to be rendered (and installed, when asked) with the extra resources added.
For the extra resources configured under `extraDeploy` to be interpreted as valid templates.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
helm version
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

I'm trying to add an additional service port, but ran into the `range can't iterate over` with my service template modified from the example. Attempting the straight example given in the docs (and when removing the `...` lines) gives the same error.

**Comment by LorenzoPiazza** [comment]
Hi! I had the same problem: Using the extraDeploy values copied from the documentantion doesn't work.
I resolved using a Yaml list of multi-line string. So using the `-` as _block sequence entry indicator_ for each K8s resources I want to deploy, followed by `|` to say that the element of the list is a multi-line string.
I also had to correct some `nindent `value reducing them.
In this way it works for me!

Here it is my extraDeploy:

```
extraDeploy:
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: {{ include "kafka.fullname" . }}-connect
      labels: {{- include "common.labels.standard" . | nindent 4 }}
        app.kubernetes.io/component: connector
    spec:
      replicas: 1
      selector:
        matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
          app.kubernetes.io/component: connector
      template:
        metadata:
          labels: {{- include "common.labels.standard" . | nindent 8 }}
            app.kubernetes.io/component: connector
        spec:
          containers:
            - name: connect
              image: confluentinc/kafka-connect-hdfs3:1.1.1
              imagePullPolicy: IfNotPresent
              ports:
                - name: connector
                  containerPort: 8083
              volumeMounts:
                - name: configuration
                  mountPath: /opt/bitnami/kafka/config
          volumes:
            - name: configuration
              configMap:
                name: {{ include "kafka.fullname" . }}-connect
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ include "kafka.fullname" . }}-connect
      labels: {{- include "common.labels.standard" . | nindent 4 }}
        app.kubernetes.io/component: connector
    data:
      connect-standalone.properties: |-
        bootstrap.servers = {{ include "kafka.fullname" . }}-0.{{ include "kafka.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.service.port }}
      mongodb.properties: |-
        connection.uri=mongodb://root:password@mongodb-hostname:27017
  - | 
    apiVersion: v1
    kind: Service
    metadata:
      name: {{ include "kafka.fullname" . }}-connect
      labels: {{- include "common.labels.standard" . | nindent 4 }}
        app.kubernetes.io/component: connector
    spec:
      ports:
        - protocol: TCP
          port: 8083
          targetPort: connector
      selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
        app.kubernetes.io/component: connector
```
