### ISSUE TITLE
Allow ClusterIP in externalAccess.service.type to expose Mongodb through nginx

### ISSUE THREAD

**Issue by olivierboudet** [bitnami/charts#5683]
**Which chart**:
bitnami/mongodb:10.7.2

**Is your feature request related to a problem? Please describe.**
I want to enable externalAccess to my replicaset through ingress-nginx tcp service. The chart does not allow to create a ClusterIP service for externalAccess, just LoadBalancer or NodePort. And it creates only a headless service.

**Describe the solution you'd like**
I would like to allow ClusterIP in externalAccess.service.type to use it with ingress-nginx. Like this in nginx configmap : 
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: tcp-services
data:
  27017: "{{ .Release.Namespace }}/mongo:27017"
```
