### ISSUE TITLE
[bitnami/redis-cluster] external access with Metallb

### ISSUE THREAD

**Issue by vitosans** [bitnami/charts#5688]
**Which chart**:
```
helm show chart bitnami/redis-cluster
annotations:
  category: Database
apiVersion: v2
appVersion: 6.0.12
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: Open source, advanced key-value store. It is often referred to as a data structure server since keys can contain strings, hashes, lists, sets and sorted sets.
home: https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster
icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
keywords:
- redis
- keyvalue
- database
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: redis-cluster
sources:
- https://github.com/bitnami/bitnami-docker-redis
- http://redis.io/
version: 4.4.0
```

**Describe the bug**
Following the guide to deploying a cluster and open external access. Cluster gets deployed and I am told to do a helm upgrade with the LoadBalanced ports - I do the helm upgrade and the svc switch from LoadBalancer to ClusterIP and I am unable to make connections from external hosts outside the cluster.   

**To Reproduce**

1. helm install redis-dev-cluster -f values.yaml bitnami/redis-cluster
[values.yaml](https://gist.github.com/vitosans/0a907748ddd5ea431f529970b20a8307)

Output:
```
NAME: redis-dev-cluster
LAST DEPLOYED: Thu Mar  4 15:02:24 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **


To get your password run:
    export REDIS_PASSWORD=$(kubectl get secret --namespace "default" redis-cluster -o jsonpath="{.data.redis-password}" | base64 --decode)

To connect to your Redis(TM) server from outside the cluster check the following information:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w redis-cluster'

    You will have a different external IP for each Redis(TM) node. Get the external ip from `-external` suffixed services: `kubectl get svc`.
    Redis(TM) port: 6379
    Once the LoadBalancerIPs are ready, you need to provide them and perform a Helm Upgrade:

    helm upgrade redis-dev-cluster --set "cluster.externalAccess.enabled=true,cluster.externalAccess.service.type=LoadBalancer,cluster.externalAccess.service.loadBalancerIP[0]=load-balancerip-0,cluster.externalAccess.service.loadBalancerIP[1]=load-balancerip-1,cluster.externalAccess.service.loadBalancerIP[2]=load-balancerip-2,cluster.externalAccess.service.loadBalancerIP[3]=load-balancerip-3,cluster.externalAccess.service.loadBalancerIP[4]=load-balancerip-4,cluster.externalAccess.service.loadBalancerIP[5]=load-balancerip-5" bitnami/redis-cluster
    Where loadbalancer-ip-i are the LoadBalancerIPs provided by the cluster.
```

2. kubectl get svc

Output:
```
NAME                     TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                          AGE
redis-cluster            LoadBalancer   10.233.12.6     172.23.3.57   6379:30638/TCP                   7m41s
redis-cluster-0-svc      LoadBalancer   10.233.45.39    172.23.3.58   6379:31182/TCP,16379:32402/TCP   7m40s
redis-cluster-1-svc      LoadBalancer   10.233.30.41    172.23.3.54   6379:31720/TCP,16379:30454/TCP   7m42s
redis-cluster-2-svc      LoadBalancer   10.233.23.105   172.23.3.53   6379:30126/TCP,16379:30033/TCP   7m42s
redis-cluster-3-svc      LoadBalancer   10.233.51.20    172.23.3.55   6379:30635/TCP,16379:30105/TCP   7m41s
redis-cluster-4-svc      LoadBalancer   10.233.9.43     172.23.3.56   6379:30754/TCP,16379:30782/TCP   7m41s
redis-cluster-5-svc      LoadBalancer   10.233.60.253   172.23.3.59   6379:31012/TCP,16379:30820/TCP   7m40s
redis-cluster-headless   ClusterIP      None            <none>        6379/TCP,16379/TCP               7m42s
redis-cluster-metrics    ClusterIP      10.233.18.51    <none>        9121/TCP                         7m42s
```

3. prepare the helm update as suggested in the helm notes. 

```
helm upgrade redis-dev-cluster --set password=secret_password --set \ "cluster.externalAccess.enabled=true, \
cluster.externalAccess.service.type=LoadBalancer, \
cluster.externalAccess.service.loadBalancerIP[0]=172.23.3.58, \
cluster.externalAccess.service.loadBalancerIP[1]=172.23.3.54, \
cluster.externalAccess.service.loadBalancerIP[2]=172.23.3.53, \
cluster.externalAccess.service.loadBalancerIP[3]=172.23.3.55, \
cluster.externalAccess.service.loadBalancerIP[4]=172.23.3.56, \
cluster.externalAccess.service.loadBalancerIP[5]=172.23.3.59" \
bitnami/redis-cluster`
```
4. kubectl get svc
```
NAME                                       TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)              AGE
redis-dev-cluster-redis-cluster            ClusterIP   10.233.19.17   <none>        6379/TCP             35s
redis-dev-cluster-redis-cluster-headless   ClusterIP   None           <none>        6379/TCP,16379/TCP   35s
```

**Expected behavior**
I would expect a Loadbalanced IP for the redis-dev-cluster-redis-cluser

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by vitosans** [comment]
Here is the updated helm yaml:

```
  path: /bitnami/redis/data
  size: 8Gi
  storageClass: null
  subPath: ""
podDisruptionBudget: {}
podSecurityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
  sysctls: null
podSecurityPolicy:
  create: false
rbac:
  create: false
  role:
    rules: []
redis:
  affinity: {}
  args: []
  busPort: 16379
  command: []
  configmap: null
  customLivenessProbe: {}
  customReadinessProbe: {}
  extraEnvVars: []
  extraEnvVarsCM: null
  extraEnvVarsSecret: null
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  initContainers: []
  lifecycleHooks: null
  livenessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
  nodeAffinityPreset:
    key: ""
    type: ""
    values: []
  nodeSelector: {}
  podAffinityPreset: ""
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  port: 6379
  priorityClassName: null
  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1
  resources: {}
  schedulerName: null
  shareProcessNamespace: false
  sidecars: []
  tolerations: []
  topologySpreadConstraints: []
  useAOFPersistence: "yes"
service:
  annotations: {}
  labels: {}
  port: 6379
  type: ClusterIP
serviceAccount:
  create: false
  name: null
statefulset:
  rollingUpdatePartition: null
  updateStrategy: RollingUpdate
sysctlImage:
  command: []
  enabled: false
  mountHostSys: false
  pullPolicy: Always
  pullSecrets: null
  registry: docker.io
  repository: bitnami/bitnami-shell
  resources: {}
  tag: "10"
tls:
  authClients: true
  certCAFilename: null
  certFilename: null
  certKeyFilename: null
  certificatesSecret: null
  dhParamsFilename: null
  enabled: false
updateJob:
  activeDeadlineSeconds: 600
  affinity: {}
  annotations: {}
  args: null
  command: null
  extraEnvVars: []
  extraEnvVarsCM: null
  extraEnvVarsSecret: null
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  initContainers: []
  nodeAffinityPreset:
    key: ""
    type: ""
    values: []
  nodeSelector: {}
  podAffinityPreset: ""
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  priorityClassName: null
  resources:
    limits: {}
    requests: {}
  tolerations: []
usePassword: true
usePasswordFile: false
volumePermissions:
  enabled: false
  image:
    pullPolicy: Always
    pullSecrets: null
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: "10"
  resources: {}
```

**Comment by vitosans** [comment]
**After running update. **:
```
' cluster':
  externalAccess:
    enabled: true
    service:
      loadBalancerIP:
      - 172.23.3.56
      - 172.23.3.57
      - 172.23.3.59
      - 172.23.3.54
      - 172.23.3.58
      - 172.23.3.55
      type: LoadBalancer
cluster:
  externalAccess:
    enabled: false
    service:
      annotations: {}
      loadBalancerIP: []
      port: 6379
      type: LoadBalancer
  init: true
  nodes: 6
  replicas: 1
  update:
    addNodes: false
    currentNumberOfNodes: 6
    newExternalIPs: []
common:
  exampleValue: common-chart
  global:
    redis: {}
commonAnnotations: null
commonLabels: null
containerSecurityContext:
  enabled: true
  runAsUser: 1001
  sysctls: null
existingSecret: null
existingSecretPasswordKey: null
extraDeploy: []
fullnameOverride: null
global:
  redis: {}
image:
  pullPolicy: IfNotPresent
  pullSecrets: null
  registry: docker.io
  repository: bitnami/redis-cluster
  tag: 6.0.12-debian-10-r0
initJob:
  activeDeadlineSeconds: 600
  affinity: {}
  annotations: {}
  args: null
  command: null
  extraEnvVars: []
  extraEnvVarsCM: null
  extraEnvVarsSecret: null
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  initContainers: []
  nodeAffinityPreset:
    key: ""
    type: ""
    values: []
  nodeSelector: {}
  podAffinityPreset: ""
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  priorityClassName: null
  resources:
    limits: {}
    requests: {}
  tolerations: []
metrics:
  enabled: false
  extraArgs: {}
  image:
    pullPolicy: IfNotPresent
    pullSecrets: null
    registry: docker.io
    repository: bitnami/redis-exporter
    tag: 1.17.1-debian-10-r9
  podAnnotations:
    prometheus.io/port: "9121"
    prometheus.io/scrape: "true"
  podLabels: {}
  prometheusRule:
    additionalLabels: {}
    enabled: false
    namespace: ""
    rules: []
  resources: {}
  service:
    annotations: {}
    labels: {}
    loadBalancerIP: null
    type: ClusterIP
  serviceMonitor:
    enabled: false
    interval: null
    namespace: null
nameOverride: null
networkPolicy:
  allowExternal: true
  enabled: false
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
password: secret-password
persistence:
  accessModes:
  - ReadWriteOnce
  enabled: true
  matchExpressions: {}
  matchLabels: {}
  path: /bitnami/redis/data
  size: 8Gi
  storageClass: null
  subPath: ""
podDisruptionBudget: {}
podSecurityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
  sysctls: null
podSecurityPolicy:
  create: false
rbac:
  create: false
  role:
    rules: []
redis:
  affinity: {}
  args: []
  busPort: 16379
  command: []
  configmap: null
  customLivenessProbe: {}
  customReadinessProbe: {}
  extraEnvVars: []
  extraEnvVarsCM: null
  extraEnvVarsSecret: null
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  initContainers: []
  lifecycleHooks: null
  livenessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
  nodeAffinityPreset:
    key: ""
    type: ""
    values: []
  nodeSelector: {}
  podAffinityPreset: ""
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  port: 6379
  priorityClassName: null
  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1
  resources: {}
  schedulerName: null
  shareProcessNamespace: false
  sidecars: []
  tolerations: []
  topologySpreadConstraints: []
  useAOFPersistence: "yes"
service:
  annotations: {}
  labels: {}
  port: 6379
  type: ClusterIP
serviceAccount:
  create: false
  name: null
statefulset:
  rollingUpdatePartition: null
  updateStrategy: RollingUpdate
sysctlImage:
  command: []
  enabled: false
  mountHostSys: false
  pullPolicy: Always
  pullSecrets: null
  registry: docker.io
  repository: bitnami/bitnami-shell
  resources: {}
  tag: "10"
tls:
  authClients: true
  certCAFilename: null
  certFilename: null
  certKeyFilename: null
  certificatesSecret: null
  dhParamsFilename: null
  enabled: false
updateJob:
  activeDeadlineSeconds: 600
  affinity: {}
  annotations: {}
  args: null
  command: null
  extraEnvVars: []
  extraEnvVarsCM: null
  extraEnvVarsSecret: null
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  initContainers: []
  nodeAffinityPreset:
    key: ""
    type: ""
    values: []
  nodeSelector: {}
  podAffinityPreset: ""
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  priorityClassName: null
  resources:
    limits: {}
    requests: {}
  tolerations: []
usePassword: true
usePasswordFile: false
volumePermissions:
  enabled: false
  image:
    pullPolicy: Always
    pullSecrets: null
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: "10"
  resources: {}
```
