### ISSUE TITLE
influx v2, high-availability, 2x relay, cannot logon webui

### ISSUE THREAD

**Issue by latituder** [bitnami/charts#5715]
**Which chart**:
The name (and version) of the affected chart
```
annotations:
  category: Database
apiVersion: v2
appVersion: 2.0.4
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: InfluxDB(TM) is an open source time-series database designed to handle
  large write and read loads in real-time.
home: https://github.com/bitnami/charts/tree/master/bitnami/influxdb
icon: https://bitnami.com/assets/stacks/influxdb/img/influxdb-stack-220x234.png
keywords:
- influxdb
- tick
- database
- timeseries
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: influxdb
sources:
- https://github.com/bitnami/bitnami-docker-influxdb
- https://www.influxdata.com/products/influxdb-overview/
version: 2.0.4
```
**Describe the bug**
Use HELM3 implement with high-availability arch, influxdb.replicaCount=2 and relay.replicaCount=1;
(if set  influxdb.replicaCount=1 and relay.replicaCount=1, the issue doesn't occur)
Influx can be implented successful, Pods can start;
in the WebUI, enter admin password, it process a while and return to the login screen.
(if enter a wrong password, it will promote "Could not sign in". if give correct password, it will just return to the logon screen)

**To Reproduce**

```
helm install --namespace=influx-v2-test --wait --set-string architecture=high-availability --set-string networkPolicy.enabled=true --set-string persistence.storageClass=nfs-ccloud-rwx --set-string persistence.accessMode=haas-cpu-memory-moni-influx-v2 --set-string persistence.size=16Gi --set-string auth.user.bucket=BUCKET_haas-cpu-memory-moni-influx-v2,auth.user.org=ORG_haas-cpu-memory-moni-influx-v2 --set-string auth.admin.username=admin,auth.admin.password=1hAbyMOx06GZehcJ9KDj --set-string auth.writeUser.username=influx_rw,auth.writeUser.password=aoa4qpulYxcikBUFOu7j --set-string auth.readUser.username=influx_r,auth.readUser.password=JbGBLW8Dpf1cbwZGhfmH --set-string influxdb.replicaCount=2,relay.replicaCount=1 --set-string resources.requests.cpu=0.1,resources.requests.memory=256Mi --set-string resources.limits.memory=8Gi,resources.limits.cpu=4 --set-string relay.resources.requests.cpu=0.1,relay.resources.requests.memory=256Mi --set-string relay.resources.limits.memory=8Gi,relay.resources.limits.cpu=4 --set-string ingress.enabled=true --set-string ingress.pathType=ImplementationSpecific --set-string ingress.hostname=haas-cpu-memory-moni-influx-v2.<domain-name>,ingress.tls=true,ingress.path=/ haas-cpu-memory-moni-influx-v2 ./influxdb
```

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I've followed https://github.com/bitnami/charts/issues/5691 to fixed an ingress issue. so the ingress shall work proplery now.
