### ISSUE TITLE
[bitnami/metallb] Affinities and Anti-Affinities

### ISSUE THREAD

**Issue by rahulvinodsharma** [bitnami/charts#5717]
**Which chart**:
[bitnami/metallb]

**Describe the bug**

metallb-controller-pod not scheduling another than master node.

**To Reproduce**

`helm install metallb bitnami/metallb -n metallb-system -f value.yaml`

**Expected behavior**
metallb-controller-pod should be deployed on any available node, as there is no nodeselector in default values.yaml files.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.1", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by migruiz4** [comment]
Hi @rahulsadanandan,

Using default `values.yaml`, the controller pod specs will look as it follows:

`$ helm template bitnami/metallb`
```yaml
---
# Source: metallb/templates/controller/deployment.yaml
apiVersion: apps/v1
kind: Deployment
...
    spec:
      
      serviceAccountName: RELEASE-NAME-metallb-controller
      terminationGracePeriodSeconds: 0
      nodeSelector:
        "kubernetes.io/os": linux
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: metallb
                    app.kubernetes.io/instance: RELEASE-NAME
                    app.kubernetes.io/component: controller
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
```

As you can see, the only conditions by default are:
- The Kubernetes node should include the label `"kubernetes.io/os": linux`
- PodAntiAffinity prevents deploying two replicas in the same node.

I tried to reproduce your case using the latest version of the bitnami/metallb chart (v2.3.2) and the default `values.yaml`, and the pod was deployed in a Kubernetes worker node, as there isn't anything preventing it in the manifest.

Could you please share some more details about your case? Maybe a `kubectl pod describe`?
