### ISSUE TITLE
[bitnami/mongodb] pvc gets deleted when upgrading helm chart

### ISSUE THREAD

**Issue by lusu007** [bitnami/charts#5724]
**Which chart**:
mongodb 10.10.0

**Describe the bug**
When upgrading the helm chart the pvcs of an existing replicaset gets deleted.

**To Reproduce**
Install mongodb replicaset then upgrade the helm chart.

**Expected behavior**
PVCs doesn't get deleted

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc"
, Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:10:32Z", GoVersion:"go1.15.2", Compiler:"gc"
, Platform:"linux/amd64"}
```

**Additional context**
None. If more information is needed just contact me.

**Comment by andresbono** [comment]
Hi @lusu007, can you share the specific values that you are using to install and upgrade the helm chart? What are the original version you are upgrading from?

**Comment by lusu007** [comment]
Hey @andresbono,
I upgraded from version 10.6.2 to 10.10.0. 

Mongodb is deployed via argocd with the following values.yaml:
```
namespace: &mongodbNamespace stage-mongodb
mongodb:
  global:
    namespaceOverride: *mongodbNamespace
    imagePullSecrets:
      - dockerhub
    storageClass: csi-cinder-high-speed
  architecture: replicaset
  auth:
    database: admin
    username: legend
    existingSecret: mongodb-secret
  replicaSetName: mongodb
  replicaCount: 3
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: global-prometheus-stack
```
