### ISSUE TITLE
Ingress is not created for bundeled kibana in elasticsearch

### ISSUE THREAD

**Issue by wissamataleh** [bitnami/charts#5725]
**Which chart**:
elasticsearch - version: 14.5.0
kibana - version: 7.2.3

**Describe the bug**
Ingress is not created for bundled kibana in elasticsearch chart.

**To Reproduce**
1. Enable ingress in kibana subchart and add apiVersion capabilities in common subchart
```
...
kibana:
  ingress:
    enabled: true
    certManager: false
    hostname: kibana.local
    path: /
    pathType: Prefix
    tls: false
    annotations: {}
...
common:
  capabilities:
    ingress:
      apiVersion: networking.k8s.io/v1
  ingress:
    supportsPathType: true
....
```
2. install elasticsearch chart.

**Expected behavior**
Ingress resource for kibana is created.

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
