### ISSUE TITLE
[bitnami/kubewatch] Values in values.yaml don't match application code

### ISSUE THREAD

**Issue by bugok** [bitnami/charts#5729]
**Which chart**:
kubewatch 3.1.3

**Describe the bug**
The application code [declares the following options](https://github.com/bitnami-labs/kubewatch/blob/master/config/config.go#L50): 
```
// Resource contains resource configuration
type Resource struct {
	Deployment            bool `json:"deployment"`
	ReplicationController bool `json:"rc"`
	ReplicaSet            bool `json:"rs"`
	DaemonSet             bool `json:"ds"`
	Services              bool `json:"svc"`
	Pod                   bool `json:"po"`
	Job                   bool `json:"job"`
	Node                  bool `json:"node"`
	ClusterRole           bool `json:"clusterrole"`
	ServiceAccount        bool `json:"sa"`
	PersistentVolume      bool `json:"pv"`
	Namespace             bool `json:"ns"`
	Secret                bool `json:"secret"`
	ConfigMap             bool `json:"configmap"`
	Ingress               bool `json:"ing"`
}
```

In the chart's `values.yaml` the following options are documented:
```
# Resources to watch
resourcesToWatch:
  deployment: true
  replicationcontroller: false
  replicaset: false
  daemonset: false
  services: false
  pod: true
  job: false
  persistentvolume: false
```

This makes it so that if we pass `resourcesToWatch.services: true`, nothing will change. 

**To Reproduce**

- Deploy the chart with a mismatched value, verify that nothing changed. 

**Expected behavior**
Have the documentation match the application code

**Version of Helm and Kubernetes**:
Irrelevant.

- Output of `helm version`:
Irrelevant.

- Output of `kubectl version`:
Irrelevant

**Additional context**
None

**Comment by migruiz4** [comment]
Hi @bugok ,

I'm sorry but I could understand what you mean by

> This makes it so that if we pass resourcesToWatch.services: true, nothing will change.

I tried to reproduce your issue, but the current configuration seems to be working as intended.

### Test 1

**values.yaml**
```yaml
resourcesToWatch:
  deployment: false
  replicationcontroller: false
  replicaset: false
  daemonset: false
  services: false
  pod: false
  job: false
  persistentvolume: false
```
Installing using **--set resourcesToWatch.services=true**, only services will be monitored.
```
> helm install kw-test bitnami/kubewatch --set resourcesToWatch.services=true
> kubectl get pods
NAME                                        READY   STATUS    RESTARTS   AGE
kw-test-kubewatch-9c9944f94-svktx           1/1     Running   0          9s
...
> kubectl logs kw-test-kubewatch-9c9944f94-svktx
==> Config file exists...
time="2021-03-09T09:57:10Z" level=info msg="Starting kubewatch controller" pkg=kubewatch-service
time="2021-03-09T09:57:10Z" level=info msg="Processing add to service: default/kubernetes" pkg=kubewatch-service
time="2021-03-09T09:57:10Z" level=info msg="Processing add to service: default/md-test-mariadb" pkg=kubewatch-service
...
```

### Test 2

**values.yaml**
```yaml
resourcesToWatch:
  deployment: true
  replicationcontroller: true
  replicaset: true
  daemonset: true
  services: true
  pod: true
  job: true
  persistentvolume: true
```

Uninstalled, reinstalled without `--set` flag, and the pod logs show all resources will be monitored:

```
> kubectl logs kw-test-kubewatch-65b8bb87c9-ncbhq
==> Config file exists...
time="2021-03-09T09:20:31Z" level=info msg="Starting kubewatch controller" pkg=kubewatch-daemonset
time="2021-03-09T09:20:31Z" level=info msg="Starting kubewatch controller" pkg=kubewatch-replicaset
time="2021-03-09T09:20:31Z" level=info msg="Starting kubewatch controller" pkg=kubewatch-pod
time="2021-03-09T09:20:31Z" level=info msg="Starting kubewatch controller" pkg="kubewatch-persistent volume"
time="2021-03-09T09:20:31Z" level=info msg="Starting kubewatch controller" pkg=kubewatch-job
time="2021-03-09T09:20:31Z" level=info msg="Starting kubewatch controller" pkg="kubewatch-replication controller"
time="2021-03-09T09:20:31Z" level=info msg="Starting kubewatch controller" pkg=kubewatch-deployment
time="2021-03-09T09:20:31Z" level=info msg="Starting kubewatch controller" pkg=kubewatch-service
time="2021-03-09T09:20:31Z" level=info msg="Processing add to service: default/kubernetes" pkg=kubewatch-service
time="2021-03-09T09:20:31Z" level=info msg="Processing add to service: default/md-test-mariadb" pkg=kubewatch-service
time="2021-03-09T09:20:31Z" level=info msg="Processing add to service: default/pg-test-postgresql" pkg=kubewatch-service
time="2021-03-09T09:20:31Z" level=info msg="Processing add to service: default/pg-test-postgresql-headless" pkg=kubewatch-service
time="2021-03-09T09:20:31Z" level=info msg="Processing add to service: kube-system/kp-kube-prometheus-kubelet" pkg=kubewatch-service
time="2021-03-09T09:20:31Z" level=info msg="Processing add to service: kube-system/kube-dns" pkg=kubewatch-service
time="2021-03-09T09:20:31Z" level=info msg="Processing add to persistent volume: pvc-05aca501-8ace-4acf-94fd-adeacafbaa7e" pkg="kubewatch-persistent volume"
time="2021-03-09T09:20:31Z" level=info msg="Processing add to persistent volume: pvc-5fcc9844-6409-4534-a4ea-35a87ba7eb39" pkg="kubewatch-persistent volume"
time="2021-03-09T09:20:31Z" level=info msg="Processing add to persistent volume: pvc-7cbf06bb-b7a6-4fd6-b5db-b518322e347e" pkg="kubewatch-persistent volume"
time="2021-03-09T09:20:31Z" level=info msg="Processing add to persistent volume: pvc-cc7a5bcc-0868-44cd-880f-6eba4f20de70" pkg="kubewatch-persistent volume"
time="2021-03-09T09:20:31Z" level=info msg="Processing add to replicaset: default/kw-test-kubewatch-65b8bb87c9" pkg=kubewatch-replicaset
time="2021-03-09T09:20:31Z" level=info msg="Processing add to replicaset: kube-system/coredns-f9fd979d6" pkg=kubewatch-replicaset
time="2021-03-09T09:20:31Z" level=info msg="Processing add to daemonset: kube-system/kube-proxy" pkg=kubewatch-daemonset
time="2021-03-09T09:20:31Z" level=info msg="Processing add to deployment: default/kw-test-kubewatch" pkg=kubewatch-deployment
...
```

I understand what you mean that the Resource struct definition may be confusing and I cannot tell why `services:true` is setting `Resource.Services` (and not `svc` instead) as I haven't been personally involved in the development of kubewatch.

But the format of `$HOME/.kubewatch.yaml` is defined like that in:
https://github.com/bitnami-labs/kubewatch/blob/v0.1.0/kubewatch-configmap.yaml
and
https://github.com/bitnami-labs/kubewatch/blob/v0.1.0/README.md#viewing-config 

Maybe you are experiencing a different issue not related to the `resourcesToWatch` configuration? 

Any information you can provide about your case would be useful: pod logs, customizations of the values.yaml ...

**Comment by bugok** [comment]
@migruiz4: Thanks for your response and your detailed testing. 
Maybe this is because of the fact that I'm using a custom image where I define a custom handler of mine. 
Is it possible that the default fetched image has those option names available?

**Comment by migruiz4** [comment]
The base image used by the chart by default is `bitnami/kubewatch:0.1.0-debian-10-r186`.

You can find the source code of that image in this repository: https://github.com/bitnami/bitnami-docker-kubewatch
As you can see it doesn't include any additional logic to transform `.kubewatch.yaml`.

---

Is it possible your image is not setting $HOME (or alternatively $KW_CONFIG) to the folder where you are mounting your `.kubewatch.yaml` file?

Check that the bitnami/kubewatch chart will mount the `.kubewatch.yaml` ConfigMap at `/opt/bitnami/kubewatch/.kubewatch.yaml` inside the container.
```
          volumeMounts:
            - name: configuration
              mountPath: /opt/bitnami/kubewatch/.kubewatch.yaml
              subPath: .kubewatch.yaml
```

If Kubewatch doesn't find `.kubewatch.yaml` at `$HOME/.kubewatch.yaml` (or alternatively, in version 0.1.0 $KW_CONFIG/.kubewatch.yaml)  it will create an empty configfile in that location.
```
func createIfNotExist() error {
	// create file if not exist
	configFile := filepath.Join(configDir(), ConfigFileName)
	_, err := os.Stat(configFile)
	if err != nil {
		if os.IsNotExist(err) {
			file, err := os.Create(configFile)
			if err != nil {
				return err
			}
			file.Close()
		} else {
			return err
		}
	}
	return nil
}
```
That could be a reason why your changes to the `values.yaml` are not taking effect, but as I said I'm just guessing without seeing your image files.

**Comment by bugok** [comment]
Unfortunately, I can't share the code for my custom image. 
I can say that the custom image is based on the kubewatch docker image: https://github.com/bitnami-labs/kubewatch/blob/master/Dockerfile

The only changes I have in my custom image are adding another (custom) handler which is similar to the webook handler, but needs to be in another format. 

I think the point I'm missing is how does the kubewatch binary is able to identify options like `services` where they don't show up in the kubewatch code. 

In terms of entrypoint: I am setting the `KW_CONFIG ` to `/opt/bitnami/kubewatch` so based on what happens in the chart - the resources described under `resourcesToWatch` are just copied to the configmap: 

from the container: 

```
# HOME=/opt/bitnami/kubewatch /bin/kubewatch config view
Contents of ~/.kubewatch.yaml
handler:
resource:
  clusterrole: false
  configmap: true
  deployment: true
  ds: true
  ing: true
  job: true
  node: true
  ns: false
  po: true
  pv: true
  rc: true
  rs: true
  sa: true
  secret: true
  svc: true
namespace: ""
```

Which is working as expected. 

I think the core issue here is how to document the options. 
I see that the link you referenced (https://github.com/bitnami/bitnami-docker-kubewatch#configuration-file) has more options.
I'm not sure how those work. Obviously, they do. I just don't understand how, as I don't see references to those names in the code.
