### ISSUE TITLE
pvc for kafka with separate directory for every pod

### ISSUE THREAD

**Issue by mchepukov** [bitnami/charts#5745]
How to create separate data directory for every kafka's pod in pvc.
```
persistence:
  enabled: true
  existingClaim: "kafka"
  storageClass: "-"
  accessModes:
    - ReadWriteOnce
  size: 8Gi
```

For example we have hostPath to /mnt/kafka directory, when only one pod run on node - it's ok, because it's create data directory only for this pod, and it's will be like kafka0 - node1, kafka1 - node2, kafka2-node3, but if node unschedulable it can be like x - node1, kafka0  - node2, kafka1 - node 2, and kafka wouldn't startup.

How can I make /mnt/kafka/kafka0, /mnt/kafka/kafka1, /mnt/kafka/kafka2 on each node?

**Comment by carrodher** [comment]
At this moment, the different parameters to handle persistence in the chart are:
- `extraVolumeMounts` to add an extra volumeMount(s) to Kafka containers
- The `persistence.*` parameters you are mentioning

But in the end, this is something handled by k8s itself and I am not sure if it is something that can be customized with that much fine grain.

In the statefulset:
```yaml
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            ...
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
```
Whatever you set as `extraVolumeMounts` is going to be applied at that point:
```yaml
## extraVolumes and extraVolumeMounts allows you to mount other volumes
## Examples:
# extraVolumes:
#   - name: kafka-jaas
#     secret:
#       secretName: kafka-jaas
# extraVolumeMounts:
#   - name: kafka-jaas
#     mountPath: /bitnami/kafka/config/kafka_jaas.conf
#     subPath: kafka_jaas.conf
extraVolumes: []
extraVolumeMounts: []
```
but I am not 100% sure if it is going to cover your use case since it is going to be handled like the other volumes.
