### ISSUE TITLE
deployment problem: ingress tls values - wildcard cert problem

### ISSUE THREAD

**Issue by bjin01** [bitnami/charts#5746]
**Which chart**:
bitnami/dokuwiki                        11.1.3          20200729.0.0

**Describe the bug**
I manually created tls-ca and secret with cert and key in default namespace that I use.
The cert is signed by letsenscript, a wild card cert.
```
 kubectl create secret tls dokuwiki.local-tls --cert tls.crt --key tls.key
 kubectl create secret generic tls-ca --from-file=fullchain.pem=./fullchain.pem
```
Trying to deploy with helm 3 and get errors.

```
# helm install mywiki bitnami/dokuwiki -f values.yaml
Error: template: dokuwiki/templates/tls-secrets.yaml:7:14: executing "dokuwiki/templates/tls-secrets.yaml" at <include "common.labels.standard" .>: error calling include: template: dokuwiki/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: dokuwiki/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```

values.yaml:
```yaml
---
  certificates: 
    customCAs: "tls-ca"
    customCertificate: 
      certificateSecret: "dokuwiki.local-tls"
      chainSecret: 
        name: "tls-ca"
  dokuwikiEmail: "bj@test.com"
  dokuwikiPassword: "test"
  dokuwikiUsername: "user"
  dokuwikiWikiName: "My wiki"
  ingress: 
    enabled: "true"
    hostname: "boki.bocap.cloud"
    secrets: 
      - certificate: "dokuwiki.local-tls"
    tls: "true"
  persistence: 
    storageClass: "myclass"
```

**To Reproduce**

1. Create a custom secret with cert + key and use it in values.yaml and deploy dokuwiki with latest chart.

**Expected behavior**
Could you explain the correct syntax to use for custom cert in ingress section?
In previous version of chart dokuwiki-9.2.1  20200729.0.0 I used same certificate which is wildcard cert and no problem.

dokuwiki-9.2.1  20200729.0.0
values.yaml:
```yaml
ingress:
   ## Set to true to enable ingress record generation
   ##
   enabled: true

   ## The list of hostnames to be covered with this ingress record.
   ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
   ##
   hosts:
     - name: test.bocap.cloud

       ## Set this to true in order to enable TLS on the ingress record
       ## A side effect of this will be that the backend dokuwiki service will be connected at port 443
       ##
       tls: true

       ## Set this to true in order to add the corresponding annotations for cert-manager
       ##
       certManager: false

       ## If TLS is set to true, you must declare what secret will store the key/certificate for TLS
       ##
       tlsSecret: dokuwiki.local-tls
```
**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
# helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl version`:

```
 # kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-17T11:52:32Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
