### ISSUE TITLE
[mongo] Redeploying designated initial primary pod after node (and storage) failure caused desync of ReplicaSet

### ISSUE THREAD

**Issue by mklokocka** [bitnami/charts#5752]
**Which chart**:
bitnami/mongodb 9.3.1

**Describe the bug**
We are using mongodb set up using bitnami helm chart. We are using the `replicaset` architecture with 3 replicas. Since there are high volumes of data going through the DB, we wanted to avoid network overhead and we are using local storage of hosts for persistence (using https://github.com/rancher/local-path-provisioner). We are running on 3 different nodes. The node running our "initial primary pod" `mongodb-0` failed permanently, and we were forced to recreate it. Note, that the replica set itself was still running with 2 replicas without problems, with `mongodb-0` still being present in the configuration.

However, since the new pod started without any present data, it started to initialize the whole replica set anew, even when there were two pods still up and running with no problems. This meant that the whole replica set started failing because of the mismatched configurations. In the end we were forced to edit the `setup.sh` to force the initial primary pod to point to `mongodb-1`, to allow the newly started `mongodb-0` to be correctly synced with the replica set.

This happens due to the scripts present in the bitnami mongo image, most notably the part [here](https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.2/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh#L1038-L1056). As far as I can understand, since there are no db data files in the host (since it is a new node altogether), it reinitializes the whole replica set because the pod considers itself as a primary node due to [this](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/replicaset/scripts-configmap.yaml#L76).

**To Reproduce**
First of all, our `values.yaml`:
```yaml
# Docs: https://github.com/bitnami/charts/tree/master/bitnami/mongodb

# Image setting, replaced by custom image for NUMA compatibility with kustomize.
image:
  tag: 4.2.10-debian-10-r12

# Mongo DB params.
architecture: replicaset

# Helm chart has messy naming conventions for secrets, gotta handle this in script with sed.
auth:
  enabled: true
  existingSecret: <secrets>

replicaSetName: <rs-name>

extraEnvVarsSecret: <secrets>

initdbScriptsConfigMap: mongodb-custom-scripts

# Sets up:
# wiredTigerCacheSizeGB - to properly set internal cache size in containerized environment
# taskExecutorPoolSize - to avoid MongoDB starving CPU from other containers running on the same node.
extraFlags:
  - "--wiredTigerCacheSizeGB 31.5"
  - "--setParameter taskExecutorPoolSize=4"

replicaCount: 3

podSecurityContext:
  enabled: false

containerSecurityContext:
  enabled: false

resources:
  requests:
    memory: "64Gi"
    cpu: "2.0"
  limits:
    memory: "64Gi"
    cpu: "4.0"

pdb:
  create: true

# Persistence.
persistence:
  storageClass: "local-path"
  size: 200Gi

# RBAC.
serviceAccount:
  create: false

# Volume permissions.
volumePermissions:
  enabled: true
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.1"
    limits:
      memory: "512Mi"
      cpu: "0.5"

# Arbiter.
arbiter:
  enabled: false

# Metrics.
metrics:
  enabled: false

```

Since we are not using Helm, we converted this to kustomize using the following scripts:

```bash
#! /bin/bash -e

# Convert MongoDB Helm Chart into Kustomize compatible resources.
# https://github.com/bitnami/charts/tree/master/bitnami/mongodb
# Skipping nameprefix to avoid annoying namePrefix value in kustomization.yaml.
# Skipping configmap to avoid the implicit renaming of scripts it does.
docker run -i -v $PWD:/mongodb --entrypoint /bin/sh containersol/helm-convert << EOF

helm repo add bitnami https://charts.bitnami.com/bitnami
helm convert \
  --force \
  --skip-transformers nameprefix,configmap,secret \
  --name mongodb \
  -f mongodb/values.yaml \
  bitnami/mongodb

  # Rename bad references to secret.
  sed -i 's/mongodb-root-password/MONGODB_ROOT_PASSWORD/g' /mongodb/mongodb-statefulset.yaml
  sed -i 's/mongodb-replica-set-key/MONGODB_REPLICA_SET_KEY/g' /mongodb/mongodb-statefulset.yaml

  # Remove annoying -headless postfix from mongodb service.
  sed -i 's/-headless//g' /mongodb/mongodb-headless-svc.yaml
  sed -i 's/-headless//g' /mongodb/mongodb-statefulset.yaml

EOF

```

Lastly, we have a small customized Dockerfile for mongo:

```Dockerfile
FROM docker.io/bitnami/mongodb:4.2.10-debian-10-r12

USER root

RUN install_packages numactl
RUN sed -i 's/"${cmd}"/"numactl" "--interleave=all" "${cmd}"/g' /opt/bitnami/scripts/mongodb/run.sh

USER 1001
```

To reproduce it should be enough to:

1. Start the stateful set on 3 different nodes (using a topology constraint to ensure each node gets a single pod).
2. Simulate a node failure for the node running pod `mongodb-0`, clearing the local storage in the process.
3. Restarting the `mongodb-0` pod.
4. Replica set should be unsynced at this moment, with 2 pods being in the replica set initialized in step 1., and the new `mongodb-0` pod being in a new replica set only with itself in it.

**Expected behavior**:
The `mongodb-0` should be correctly added back to the old replica set.

**Proposed fix**:
I understand it is infeasible to be keeping an env. variable with the list of all pods in the statefulset as that defeats the purpose of scalability of the deployment (as was discussed [here](https://github.com/bitnami/bitnami-docker-mongodb/issues/187)). Perhaps this could be handled by a simple DNS resolution?

We can get a list of all IPs of the statefulset using the headless service (however, note that `publishNotReadyAddresses: true`) as follows:
```bash
getent hosts <service name>.<namespace>.svc.cluster.local. | awk '{ print $1 }'
```

Using mongo CLI we can then iteratively check all the IPs for a primary node (`db.isMaster().ismaster`). Once we find the current primary we can export the correct env. vars:
```bash
export MONGODB_REPLICA_SET_MODE="secondary"
export MONGODB_?INITIAL?_PRIMARY_HOST=<IP we got>
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

Converted to kustomize using `containersol/helm-convert`.

- Output of `kubectl version`:

Not relevant.

**Additional context**
Interestingly, it is also quite unclear what happens when a new pod is started and added to the statefulset when the primary pod is not actually the initial pod (`MONGODB_INITIAL_PRIMARY_HOST`). Will it fail? Will it succeed somehow?
