### ISSUE TITLE
grafana-operator chart does not pass global.imagePullSecrets to grafana deployment

### ISSUE THREAD

**Issue by JamesCacioppo** [bitnami/charts#5762]
**Which chart**:
grafana-operator 0.3.1

**Describe the bug**
global.imagePullSecrets from values.yaml is not used when pulling bitnami/grafana image even though global.imageRegistry is used.  This prevents the image from being pulled from the private registry specified in global.imageRegistry.

**To Reproduce**
1. add values to values.yaml
```
grafana-operator:
  enabled: true
  global:
    imagePullSecrets: [ regcred ]
    imageRegistry: some.registry.net
```
2.helm install name [chart]

**Expected behavior**
Deployment grafana-deployment should have `spec.containers.imagePullSecrets` and it's value should be `regcred`

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:23:45Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
```

**Additional context**
We're operating in an air-gapped environment so everything has to pull from a private registry.  The grafana operator pulls just fine using the registry and image pull secret but it's this additional image that seems to be the problem.

**Comment by marcosbc** [comment]
Hi @JamesCacioppo, it seems you are using the `grafana-operator` parent key, which should not be added in the `values.yaml` file of the Grafana Operator chart.

If I modify my values.yaml in the following way:

```diff
diff --git a/bitnami/grafana-operator/values.yaml b/bitnami/grafana-operator/values.yaml
index 2cbd49521..a6beb430b 100644
--- a/bitnami/grafana-operator/values.yaml
+++ b/bitnami/grafana-operator/values.yaml
@@ -2,10 +2,10 @@
 ## Please, note that this will override the image parameters, including dependencies, configured to use the global value
 ## Current available global Docker image parameters: imageRegistry, imagePullSecrets
 ##
-# global:
-#   imageRegistry: myRegistryName
-#   imagePullSecrets:
-#     - myRegistryKeySecretName
+global:
+  imageRegistry: myRegistryName
+  imagePullSecrets:
+    - myRegistryKeySecretName

 ## String to partially override common.names.fullname include (will maintain the release name)
 ##
```

And then run `helm template` with custom inputs, I can see image pull secrets being added to the template:

```yaml
# Source: grafana-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
...
spec:
  replicas: 1
  ...
  template:
    ...
    spec:
      imagePullSecrets:
        - name: myRegistryKeySecretName
```

Could you verify if that solves your issues?

**Comment by JamesCacioppo** [comment]
@marcosbc Thanks for the response.  I should have been more clear.  I'm not modifying the grafana-operator chart directly.  I have the following:
```
➜ supporting-infra git:(grafana-operator-fix) ✗ tree
.
├── Chart.lock
├── Chart.yaml
├── charts
│   ├── argo-cd-2.11.3.tgz
│   ├── grafana-operator-0.3.1.tgz
│   ├── kube-prometheus-3.0.1.tgz
│   ├── localstack-0.1.2.tgz
│   ├── metrics-server-5.3.4.tgz
│   └── mongodb-10.10.0.tgz
├── templates
│   └── GrafanaDatasetPrometheus.yaml
└── values.yaml
```

The contents of `supporting-infra/chart.yaml` are:
```
apiVersion: v2
name: supporting-infra
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: metrics-server
  version: 5.3.4
  repository: https://charts.bitnami.com/bitnami
  condition: metrics-server.enabled

- name: kube-prometheus
  version: 3.0.1
  repository: https://charts.bitnami.com/bitnami
  condition: kube-prometheus.enabled

- name: grafana-operator
  version: 0.3.1
  repository: https://charts.bitnami.com/bitnami
  condition: grafana-operator.enabled

- name: argo-cd
  version: 2.11.3
  repository: https://argoproj.github.io/argo-helm
  condition: argo-cd.enabled

- name: localstack
  version: 0.1.2
  repository: http://helm.localstack.cloud
  condition: localstack.enabled
```

And finally the contents of `supporting-infra/values.yaml`:
```
metrics-server:
  enabled: true
  global:
    imagePullSecrets: [ regcred ]
    imageRegistry: docker-hub.myNexusProxy.net
  apiService:
    create: true
  extraArgs:
    kubelet-insecure-tls: true

kube-prometheus:
  enabled: true
  global:
    imagePullSecrets: [ regcred ]
    imageRegistry: docker-hub.myNexusProxy.net

grafana-operator:
  enabled: true
  global:
    imagePullSecrets: [ regcred ]
    imageRegistry: docker-hub.myNexusProxy.net

argo-cd:
  enabled: true
  global:
    imagePullSecrets: [ regcred ]
    image:
      repository: docker-hub.myNexusProxy.net/argoproj/argocd

localstack:
  enabled: false
  image:
    repository: docker-hub.myNexusProxy.net/localstack/localstack
  imagePullSecrets:
    - name: regcred
```

I then install this chart with `helm install daas-infra .` and I get two deployments related to grafana:
```
➜  supporting-infra git:(grafana-operator-fix) ✗ k get deployments
NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
daas-infra-grafana-operator           1/1     1            1           59m
daas-infra-kube-prometheus-operator   1/1     1            1           59m
daas-infra-kube-state-metrics         1/1     1            1           59m
grafana-deployment                    0/1     1            0           58m
```
The one named "daas-infra-grafana-operator" is fine.
```
➜  supporting-infra git:(grafana-operator-fix) ✗ k get deployment daas-infra-grafana-operator -o json | jq .spec.template.spec.imagePullSecrets
[
  {
    "name": "regcred"
  }
]
```
The one named "grafana-deployment" is where the problem lies.
```
➜ supporting-infra git:(grafana-operator-fix) ✗ k get deployment grafana-deployment -o json | jq .spec.template.spec.imagePullSecrets
null
```
Helm is templating in the grafana-operator.global.imageRegistry value just not the imagePullSecrets to go along with it which results in a failed image pull.
