### ISSUE TITLE
[bitnami/harbor] Notary Ingress secret using core ingress secret

### ISSUE THREAD

**Issue by chrisbsmith** [bitnami/charts#5770]
**Which chart**:
[bitnami/harbor]

**Describe the bug**
I've been deploying this in an EKS v1.19 cluster running nginx-ingress controller and cert-manager v1.2.0 and have noticed that cert-manager creates two certificates but only a single secret.

Looking into the code, the core ingress secret is also referenced in the notary ingress object. When in this configuration, visiting https://harbor.mydomain.com would warn with a CA invalid prompt. Investigation of the certificate showed that it was from the generic ingress certificate. While visiting https://notary.mydomain.com returned the expected LetsEncrypt certificate.

I changed the below value to `{{ include "harbor.ingress-notary" }}` and cert-manager created two secrets and both domain endpoints return valid LetsEncrypt certificates

https://github.com/bitnami/charts/blob/5fd202d22c8af0546b31f2c11cf89d5e8a5dd408/bitnami/harbor/templates/ingress/ingress.yaml#L122

**To Reproduce**

1. Deploy Harbor into a cluster using nginx-ingress controller and cert-manager
2. Visit both domains. Notice that the harbor domain returns a Kubernetes ingress certificate while notary returns a valid LetsEncrypt certificate

**Expected behavior**
Both domains should return a valid LetsEncrypt certificate

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.3", GitCommit:"01849e73f3c86211f05533c2e807736e776fcf29", GitTreeState:"clean", BuildDate:"2021-02-18T12:10:55Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I'm still just getting started with Harbor and Notary, so it's possible that this works in some cases, but it does not when using my setup described above. I suppose it is possible that the original context would work if a wildcard cert was provided to the `harbor-ingress` secret.

**Comment by marcosbc** [comment]
Hi @chrisbsmith, could you share how you are deploying Harbor to enable TLS authentication?

Note that there are three options that may be used to determine the secret to use: `service.tls.notaryExistingSecret`, `service.tls.existingSecret` and `harbor.ingress`. Could it be possible that one of those are enabled in your options, causing the issues you're seeing?

**Comment by chrisbsmith** [comment]
Hi @marcosbc ,

Below is my values file that I use to overwrite the defaults.

```yaml
externalURL: https://harbor.mydomain.io
ingress:
  enabled: true
  certManager: true

  hosts:
    core: harbor.mydomain.io
    notary: notary.mydomain.io

  annotations:
    ingress.kubernetes.io/ssl-redirect: 'true'
    ingress.kubernetes.io/proxy-body-size: '0'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
    cert-manager.io/cluster-issuer: "letsencrypt-staging"

internalTLS:
  enabled: true
```

Maybe `{{ include  "harbor.ingress" .  }}` gets templated differently for the different options?  However, in my testing, cert-manager needs to write secrets to two different secrets the above template was templated out as the same values.
