### ISSUE TITLE
[bitnami/wordpress] Wordpress Deployment mounts default MariaDB secret even when mariadb.auth.existingSecret is specified

### ISSUE THREAD

**Issue by evtimmy** [bitnami/charts#5774]
**Which chart**:
bitnami/wordpress-10.6.10

**Describe the bug**
We are trying out the chart with our own secret generated for mariadb. Where things brake is the wordpress chart doesn't check if mariadb existing secret is configured.

**To Reproduce**
1. Create secret for mariadb:
```
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-existing
  labels:
    app.kubernetes.io/name: mariadb
type: Opaque
data:
  mariadb-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  mariadb-password: {{ randAlphaNum 10 | b64enc | quote }}
  mariadb-replication-password: {{ randAlphaNum 10 | b64enc | quote }}

```
2. Install wordpress chart: 

```
# config.yaml

mariadb:
  enabled: true
  auth:
    existingSecret: mariadb-existing
```
helm install blog bitnami/wordpress --values=config.yaml

3. Result:
wordpress pod crashes with CreateContainerConfigError, can't find "maria-db" which is the default secret from the mariadb subchart:
```
Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  21s (x2 over 21s)  default-scheduler  0/1 nodes are available: 1 Insufficient cpu.
  Normal   Scheduled         16s                default-scheduler  Successfully assigned dev/blog-wordpress-ccccf5448-757jq to minikube
  Normal   Pulled            2s (x4 over 15s)   kubelet            Container image "docker.io/bitnami/wordpress:5.6.2-debian-10-r8" already present on machine
  Warning  Failed            2s (x4 over 15s)   kubelet            Error: secret "blog-mariadb" not found
```

**Expected behavior**
wordpress pod should pick up the existingSecret as configured for mariadb instead of using the default secret name.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
