### ISSUE TITLE
[bitnami/minio] ERROR ==> Number of nodes must even and greater than 4.

### ISSUE THREAD

**Issue by viceice** [bitnami/charts#5793]
**Which chart**: minio 6.4.0

**Describe the bug**
 I get  `ERROR ==> Number of nodes must even and greater than 4.` message when upgrading from v6.2.0.

**To Reproduce**

1. install chart v6.2.0 with values below
2. upgrade to v6.4.0

*values.yml*
```yaml
image:
  registry: gcr.io
  repository: bitnami-containers/minio
  tag: 2021.3.4

mode: distributed
replicaCount: 4

global:
  storageClass: nfs-xxx-hq

useCredentialsFile: true

persistence:
  size: 25Gi
  storageClass: nfs-md-hq

ingress:
  enabled: true
  hostname: s3.xxx.com
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'

resources:
  requests:
    memory: 256Mi
    cpu: 250m

```

**Expected behavior**
Upgrade succeeds

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4+k3s1", GitCommit:"838a906ab5eba62ff529d6a3a746384eba810758", GitTreeState:"clean", BuildDate:"2021-02-22T19:49:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Output of  `terraform version`
```
Terraform v0.14.8
+ provider registry.terraform.io/gavinbunney/kubectl v1.10.0
+ provider registry.terraform.io/hashicorp/helm v2.0.3
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.2
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/kreuzwerker/docker v2.11.0
```

**Additional context**

I'm using terraform to deploy helm chart.
I'm using [nfs-subdir-external-provisioner](https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner) chart for nfs pvc

**Comment by viceice** [comment]
Looks like the issue was cause by the already pulled image `gcr.io/bitnami-containers/minio:2021.3.4` which seems not compatible with latest chart changes.

My workaround was to remove the tag from `values.yml` and now it works again. Also updsated the latest `statefulset` changes.

```yml
image:
  registry: gcr.io
  repository: bitnami-containers/minio

clientImage:
  registry: gcr.io
  repository: bitnami-containers/minio-client

mode: distributed

statefulset:
  replicaCount: 4
  zones: 1
  drivesPerNode: 1

global:
  storageClass: nfs-md-hq

useCredentialsFile: true

persistence:
  size: 25Gi
  storageClass: nfs-md-hq

ingress:
  enabled: true
  hostname: s3.xxx.com
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'

resources:
  requests:
    memory: 256Mi
    cpu: 250m

startupProbe:
  enabled: true
```

Next time mabe better to make a major release for such big changes 🙃
