### ISSUE TITLE
[bitnami/mariadb-galera] cluster running on IPV6 only k8s never connect with peers shows wsrep_cluster_size 1

### ISSUE THREAD

**Issue by panduraju50** [bitnami/charts#5842]
Hi, 
I am trying to install galera-mariadb cluster on IPV6, but facing issue with wsrep_cluster_size it shows "1"

## Which Chart:
bitnami/mariadb-galera

To Reproduce:
1. use 
```bash 
helm install galera --set securityContext.enabled=true -f values-production.yaml ./mariadb-galera
```
 
2.
```bash
export ROOT_PASSWORD=$(kubectl get $(kubectl get secret -l app.kubernetes.io/name=mariadb-galera -o name) -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)
```

3. 
```bash
for NODE in $(kubectl get pod -l app.kubernetes.io/name=mariadb-galera -o name) ; do echo " ------- ${NODE} -------" ; kubectl exec -it ${NODE} -c mariadb-galera -- mysql -uroot -p${ROOT_PASSWORD} -e "show status where Variable_name in ('wsrep_cluster_size','wsrep_incoming_addresses','wsrep_local_state_comment');" ; done
```

I tried following this issue "#1459" and understood much more on this issue. But I am not able to find the solution to enable connectivity.
Providing logs - values files, along with wsrep options.

You can find logs, and values.yaml from the following link.
[logs] (https://gist.github.com/panduraju50/00c31dba706a60af9b95b27e9cb4b5da)
Can some one help me on this, please please???

**Comment by panduraju50** [comment]
I tried following this issue "https://github.com/bitnami/charts/issues/1459" and understood much more on this issue. But I am not able to find the solution to enable connectivity. 
Providing logs - values files, along with wsrep options. 
https://gist.github.com/panduraju50/00c31dba706a60af9b95b27e9cb4b5da

**Comment by carrodher** [comment]
Hi, what is the chart version you're using (`helm ls`)? The _values-production.yaml_ support was dropped some time ago so it's difficult for us to compare what was the parameters you customized. Instead of the whole file, can you share with us what are the parameters you changed?

In the same way, according to the mentioned issue, it seems at the end everything was related to the Kubernetes Cluster's Domain Name, did you double-check the value set for `clusterDomain` is correct and not the default one (`cluster.local`)?
Did you have the chance to test the same configuration in a non-IPv6 cluster? The referenced issue was pretty similar and it was using IPv4, so I am not sure if in this case, the protocol is something determining or not

**Comment by panduraju50** [comment]
```[kube@vm-rm-k8s-node1 mariadb-galera]$ helm list
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
galera  namespace-galera    1               2021-03-18 18:24:17.821301522 +0000 UTC deployed        mariadb-galera-5.6.5    10.5.9
```
Name, did you double-check the value set for clusterDomain is correct and not the default one (cluster.local)?
Yes, I checked and renamed cluster.local to <mycompany>.local

Did you have the chance to test the same configuration in a non-IPv6 cluster?
no, I haven't tested the same configuration on a non-IPv6 cluster. Even if I test on ipv4 Galera cluster setting will be changed.

I renamed values.yaml to values-production.yaml, but I had changed configurations accordingly to support IPV6 
changes i tried ```bind_address=:: and bind_address=::1```

```
  [galera]
  wsrep_on=ON
  wsrep_provider=/opt/bitnami/mariadb/lib/libgalera_smm.so
  wsrep_sst_method=mariabackup
  wsrep_slave_threads=4
  wsrep_cluster_address=gcomm://[node1ipv6]:4567,[node2ipv6]:4567,[node3ipv6]:4567
  wsrep_cluster_name=galera
  wsrep_sst_auth="mariabackup:"
  wsrep_provider_options="gmcast.listen_addr=tcp://[::]:4567"
  wsrep_node_address=[node1ipv6]:4567
  wsrep_node_incoming_address="[node1ipv6]:3306,[node2ipv6]:3306,[node3ipv6]:3306"
  wsrep_sst_receive_address=[node1ipv6]:4444
  # Enabled for performance per https://mariadb.com/kb/en/innodb-system-variables/#innodb_flush_log_at_trx_commit
  innodb_flush_log_at_trx_commit=2
  # MYISAM REPLICATION SUPPORT #
  wsrep_replicate_myisam=ON
  [sst]
  sockopt=",pf=ip6"
```

**Comment by carrodher** [comment]
I am not able to reproduce the issue following the steps described at https://github.com/bitnami/charts/issues/1459, but in my case, I am following the same steps in an IPv4 cluster. Although, according to your output in gist:
```
------- pod/galera-mariadb-galera-0 -------
+---------------------------+-------------------------------------------------------------------------------------------------------------------------+
| Variable_name | Value |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------+
| wsrep_local_state_comment | Synced |
| wsrep_incoming_addresses | [ipv6]:3306,[ipv6]:3306,[ipv6]:3306 |
| wsrep_cluster_size | 1 |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------+
```
it seems the IPv6 is being taken into account without issues, but the real issue is the cluster size, which shouldn't be an issue once fixed the issue in the `clusterDomain` parameter

**Comment by panduraju50** [comment]
@carrodher , firstly, thank you soo much for your time. 
Regarding clusterDomain parameter, I had changed the ```cluster.local``` to ```<company>.local``` is there anything I am missing here?

Its been a while I am trying to solve this issue. It would be great if any further help :(

**Comment by carrodher** [comment]
I am not an expert in wsrep, sorry if it's a very basic question. According to the configuration block, you are setting some IPs (`node1ipv6`, `node2ipv6`, and `node3ipv6`) are those values placeholders to avoid sharing here the real IPs or are the real value set in the configuration? How do you know in advance what that value will be? 

```
  [galera]
  wsrep_on=ON
  wsrep_provider=/opt/bitnami/mariadb/lib/libgalera_smm.so
  wsrep_sst_method=mariabackup
  wsrep_slave_threads=4
  wsrep_cluster_address=gcomm://[node1ipv6]:4567,[node2ipv6]:4567,[node3ipv6]:4567
  wsrep_cluster_name=galera
  wsrep_sst_auth="mariabackup:"
  wsrep_provider_options="gmcast.listen_addr=tcp://[::]:4567"
  wsrep_node_address=[node1ipv6]:4567
  wsrep_node_incoming_address="[node1ipv6]:3306,[node2ipv6]:3306,[node3ipv6]:3306"
  wsrep_sst_receive_address=[node1ipv6]:4444
  # Enabled for performance per https://mariadb.com/kb/en/innodb-system-variables/#innodb_flush_log_at_trx_commit
  innodb_flush_log_at_trx_commit=2
  # MYISAM REPLICATION SUPPORT #
  wsrep_replicate_myisam=ON
```

Regarding the cluster domain this is something set by the cluster-admin when deploying the cluster; if set kubelet will configure all containers to search this domain in addition to the host's search domains. If you don't know what is the proper value you will need to contact the cluster-admin, by default it's `cluster.local`, but it can be changed.

**Comment by panduraju50** [comment]
> I am not an expert in wsrep, sorry if it's a very basic question. According to the configuration block, you are setting some IPs (`node1ipv6`, `node2ipv6`, and `node3ipv6`) are those values placeholders to avoid sharing here the real IPs or are the real value set in the configuration? How do you know in advance what that value will be?
> 
> ```
>   [galera]
>   wsrep_on=ON
>   wsrep_provider=/opt/bitnami/mariadb/lib/libgalera_smm.so
>   wsrep_sst_method=mariabackup
>   wsrep_slave_threads=4
>   wsrep_cluster_address=gcomm://[node1ipv6]:4567,[node2ipv6]:4567,[node3ipv6]:4567
>   wsrep_cluster_name=galera
>   wsrep_sst_auth="mariabackup:"
>   wsrep_provider_options="gmcast.listen_addr=tcp://[::]:4567"
>   wsrep_node_address=[node1ipv6]:4567
>   wsrep_node_incoming_address="[node1ipv6]:3306,[node2ipv6]:3306,[node3ipv6]:3306"
>   wsrep_sst_receive_address=[node1ipv6]:4444
>   # Enabled for performance per https://mariadb.com/kb/en/innodb-system-variables/#innodb_flush_log_at_trx_commit
>   innodb_flush_log_at_trx_commit=2
>   # MYISAM REPLICATION SUPPORT #
>   wsrep_replicate_myisam=ON
> ```
> 
> Regarding the cluster domain this is something set by the cluster-admin when deploying the cluster; if set kubelet will configure all containers to search this domain in addition to the host's search domains. If you don't know what is the proper value you will need to contact the cluster-admin, by default it's `cluster.local`, but it can be changed.

**Comment by panduraju50** [comment]
According to the configuration block, you are setting some IPs (node1ipv6, node2ipv6, and node3ipv6) are those values placeholders to avoid sharing here the real IPs or are the real value set in the configuration? How do you know in advance what that value will be?


I repeatedly observe that the podIPs are same when ever I recreate the deployment with helm, so I tried giving PODIP's as incoming IPs.

Regarding the cluster domain this is something set by the cluster-admin when deploying the cluster; if set kubelet will configure all containers to search this domain in addition to the host's search domains. If you don't know what is the proper value you will need to contact the cluster-admin, by default it's cluster.local, but it can be changed.

This part I understood clearly from the "#1459" and found the domain from the cluster admin and recreated the cluster by changing the variable name of ```clusterDomain```

**Comment by carrodher** [comment]
If the `clusterDomain` is properly set I am running out of ideas. Just check the same approach in an IPv4 cluster in order to discard an issue with the IPv6 configuration or ask in a MariaDB experts forum just in case there is something not working as expected with the wsrep configuration

**Comment by panduraju50** [comment]
Still the issue persist, able to bring up galera cluster on ipv4 not on ipv6, We tried changing the properties to default and tried on ipv6, master1 is up but the master2 havent received mysqld to bring up the mysql service. Is there any optional wsrep configuration to get it transferred?

**Comment by carrodher** [comment]
I am not sure if there is something we can improve in the chart itself or if it is something related to the wsrep configuration itself. I will create an internal task to properly investigate it, but I can't provide an ETA to have some conclusion, it is going to depend on other priorities the team has.

 In the meantime, I would recommend you check the issue in any forum specialized in MariaDB, just in case you can find any idea there

**Comment by carrodher** [comment]
I just added the `on-hold` label to prevent the issue to be automatically closed in the future

**Comment by gwvandesteeg** [comment]
Have you verified that the configuration you're passing to the pods is actually present in the nodes using `SHOW VARIABLES`;
Just checking re: https://github.com/bitnami/charts/issues/7198

**Comment by nicolaerosia** [comment]
I also cannot get the mariadb galera chart to work on IPv6. Did you manage to do it?

**Comment by carrodher** [comment]
Hi, can you please describe how are you installing the Helm chart, the custom parameters you're using and the issue you're facing?

**Comment by panduraju50** [comment]
Hi @gwvandesteeg , as suggested I did  checked with ```SHOW VARIABLES```. But the issue is communication between two pods which are running on two different worker nodes. There is an IP conflict and I was not able to spinup more than one pod. Presently i am using Yugabyte/charts which works fine for my project on IPv6

**Comment by nicolaerosia** [comment]
I will provide a reproducer on kind since minikube does not support ipv6 only

**Comment by ioachim-hub** [comment]
# This is a reproducer
*kind.yaml*
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
  - role: control-plane
  - role: worker
    image: docker.io/kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
  - role: worker
    image: docker.io/kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
networking:
  ipFamily: ipv6
  apiServerAddress: "::"
  apiServerPort: 6443
```

helmfile.yaml
```
# yaml-language-server: $schema=https://json.schemastore.org/helmfile.json

helmDefaults:
  timeout: 600
  skipDeps: true
  historyMax: 2

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

missingFileHandler: Error

releases:
  # chart: https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera
  # history: https://github.com/bitnami/charts/commits/master/bitnami/mariadb-galera
  # https://artifacthub.io/packages/helm/bitnami/mariadb-galera/6.2.2
  # https://charts.bitnami.com/bitnami/mariadb-galera-6.2.2.tgz
  - name: mariadb-galera
    chart: bitnami/mariadb-galera
    namespace: default
    version: 6.2.2
    values:
      - rootUser:
          user: root
          password: "98cNUsR3gEyfYMrW"
          forcePassword: true
      - podAntiAffinityPreset: hard
      - replicaCount: 2
      - livenessProbe:
          enabled: true
          periodSeconds: 60
          timeoutSeconds: 10
      - readinessProbe:
          enabled: true
          periodSeconds: 60
          timeoutSeconds: 10
      - galera:
          mariabackup:
            user: mariabackup
            password: "qHmBRW7UfcVv27OD"
            forcePassword: true
```
