### ISSUE TITLE
[bitnami/airflow] Enabling Ingress and TLS

### ISSUE THREAD

**Issue by raefezzeldin** [bitnami/charts#5862]
I am trying to install airflow chart with enabling Ingress and using TLS Certificates configured by Kupeapps by modifying the following parameters :

```
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  apiVersion: null
  certManager: true
  enabled: true
  hosts:
  - name: XXXXXX.XXX.XX
    path: /
    tls: true
    tlsHosts:
    - XXXXXX.XXX.XX
    tlsSecret: airflow-tsl
  pathType: ImplementationSpecific
  secrets: null
```

and when I tried to access the domain XXXXXX.XXX.XX it keeps telling me 

Bad Request

Error parsing headers: 'limit request headers fields size'

However when I try to access it through the Public Ip it worked fine.
