### ISSUE TITLE
[bitnami/wordpress/rwx] Regression since the commit 145f5c2 was published today - "range can't iterate over ReadWriteMany" - impossible to deploy wordpress in RWX mode anymore

### ISSUE THREAD

**Issue by corend** [bitnami/charts#5870]
Hello,

Since this change https://github.com/bitnami/charts/commit/145f5c2a81e40b02c3846465f356647ddd867f9b was committed today I have the following error by simply configuring a "accessModes: ReadWriteMany" (it was working before this commit for sure, as today I did multiple installs without issues with exactly the same custom Yaml before this change was pushed):

> Error: template: wordpress/templates/pvc.yaml:16:19: executing "wordpress/templates/pvc.yaml" at <.Values.persistence.accessModes>: range can't iterate over ReadWriteMany

Do you have the same issue?

I'm using Longhorn NFS provisionner on my cluster, hope this could help.

```yaml
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
persistence:
  enabled: true
  storageClass: longhorn-nfs
  accessModes: ReadWriteMany
  size: 10Gi
```
