### ISSUE TITLE
[bitnami/thanos] Default receive component unable to modify PVC

### ISSUE THREAD

**Issue by VihanAgarwal97** [bitnami/charts#5873]
Chart Version: `3.13.1`
Kubernetes Version: `v1.18.15`

Values: 
```
image:
  tag: 0.18.0
query:
  enabled: true
  logLevel: debug            
  replicaLabel: [cluster]
  dnsDiscovery:
    sidecarsService: thanos-sidecar
    sidecarsNamespace: logging
  podAnnotations:
    iam.amazonaws.com/role: '/logging/thanos-role'
queryFrontend:
  enabled: true
  logLevel: debug          
  podAnnotations:
    iam.amazonaws.com/role: '/logging/thanos-role'
bucketweb:
  enabled: true
  logLevel: debug
  refresh: 30m
  timeout: 5m
  podAnnotations:
    iam.amazonaws.com/role: '/logging/thanos-role'
compactor:
  enabled: true
  logLevel: debug
  retentionResolutionRaw: 7d
  retentionResolution5m: 7d
  retentionResolution1h: 7d
  podAnnotations:
    iam.amazonaws.com/role: '/logging/thanos-role'
  persistence:
    enabled: true
    storageClass: gp2
    size: 50Gi
storegateway:
  enabled: true
  logLevel: debug
  podAnnotations:
    iam.amazonaws.com/role: '/logging/thanos-role'
  persistence:
    enabled: true
    storageClass: gp2
    size: 50Gi
receive:
  enabled: true
  logLevel: debug
  podAnnotations:
    iam.amazonaws.com/role: '/logging/thanos-role'
  replicaLabel: cluster
  persistence:
    enabled: true
    size: 50Gi
```

I expect this to work as I am (mostly) using defaults.  However, the `StatefulSet` is unable to create directories on the underlying FS - 
```
mkdir /var/thanos/receive/default-tenant: permission denied\ncreate default tenant data dir
```

I haven't found a fix yet, but I assume that I will need to fork this chart and update the `securityContext`. I believe that the `receive.securityContext.fsGroup` and `receive.securityContext.runAsUser` is not enough.

**Comment by VihanAgarwal97** [comment]
Closing this because I found https://github.com/bitnami/charts/tree/master/bitnami/thanos#adjust-permissions-of-persistent-volume-mountpoint 
derp

**Comment by VihanAgarwal97** [comment]
I am going to reopen this because setting the volumePermissions did not fix this.
```
❯ kc logs -f thanos-receive-0 -n logging
level=debug ts=2021-03-23T16:26:53.43048239Z caller=main.go:64 msg="maxprocs: Leaving GOMAXPROCS=[2]: CPU quota undefined"
level=warn ts=2021-03-23T16:26:53.431317251Z caller=receive.go:210 component=receive msg="setting up receive"
level=info ts=2021-03-23T16:26:53.431343784Z caller=options.go:23 component=receive protocol=HTTP msg="disabled TLS, key and cert must be set to enable"
level=info ts=2021-03-23T16:26:53.431401766Z caller=factory.go:46 component=receive msg="loading bucket configuration"
level=info ts=2021-03-23T16:26:53.43176219Z caller=receive.go:616 component=receive msg="found legacy storage, migrating to multi-tsdb layout with default tenant" defaultTenantID=default-tenant
level=error ts=2021-03-23T16:26:53.432270103Z caller=main.go:130 err="mkdir /var/thanos/receive/default-tenant: permission denied\ncreate default tenant data dir: /var/thanos/receive/default-tenant\nmain.migrateLegacyStorage\n\t/app/cmd/thanos/receive.go:624\nmain.runReceive\n\t/app/cmd/thanos/receive.go:246\nmain.registerReceive.func1\n\t/app/cmd/thanos/receive.go:130\nmain.main\n\t/app/cmd/thanos/main.go:128\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nmigrate legacy storage in /var/thanos/receive to default tenant default-tenant\nmain.runReceive\n\t/app/cmd/thanos/receive.go:247\nmain.registerReceive.func1\n\t/app/cmd/thanos/receive.go:130\nmain.main\n\t/app/cmd/thanos/main.go:128\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\npreparing receive command failed\nmain.main\n\t/app/cmd/thanos/main.go:130\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"
```

**Comment by VihanAgarwal97** [comment]
I think the chart doesn't have the initContainer defined for the receive component https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/receive/statefulset.yaml#L35

**Comment by rafariossaa** [comment]
Hi,
  Checking your values, I missed the paremeter `storageclass` for `receive`.
  Could you check that ?

**Comment by VihanAgarwal97** [comment]
I actually just found the issue. The default values for `securityContext` in https://github.com/bitnami/charts/tree/master/bitnami/thanos#thanos-receive-parameters are wrong. It is actually, `false`, `nil`, `nil`, respectively.
Setting the following values worked
```
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
```
