### ISSUE TITLE
Unable to provision topics on creation, validation error

### ISSUE THREAD

**Issue by SeanM96** [bitnami/charts#5882]
```
Error: UPGRADE FAILED: post-upgrade hooks failed: unable to build kubernetes object for post-upgrade hook service/charts/kafka/templates/kafka-provisioning.yaml: error validating "": error validating data: ValidationError(Job.spec.template.spec.containers[0]): unknown field "volumes" in io.k8s.api.core.v1.Container
```

When deploying with values:

```yaml
  allowPlaintextListener: false
  fullnameOverride: kafka-server
  auth:
    jksSecret: kafka-certs
    jksPassword: ...
    clientProtocol: tls
    interBrokerProtocol: sasl
    jaas:
      clientUsers:
        - user
      clientPasswords:
        - ...
  extraEnvVars:
    - name: KAFKA_ZOOKEEPER_PROTOCOL
      value: sasl
    - name: KAFKA_ZOOKEEPER_USER
      value: user
    - name: KAFKA_ZOOKEEPER_PASSWORD
      value: ...
  zookeeper:
    auth:
     enabled: true
     serverUsers: user
     serverPasswords: ...
     clientUser: user
     clientPassword: ...
  provisioning:
    enabled: true
    topics: 
      - name: topic5
        partitions: 1
        replicationFactor: 1
        config:
          max.message.bytes: 64000
          flush.messages: 1
      - name: topic3
        partitions: 1 
        replicationFactor: 1 
        config:
          max.message.bytes: 64000
          flush.messages: 1
      - name: topic2
        partitions: 1 
        replicationFactor: 1
        config:
          max.message.bytes: 64000
          flush.messages: 1
      - name: topic
        partitions: 1
        replicationFactor: 1
        config:
          max.message.bytes: 64000
          flush.messages: 1
```
