### ISSUE TITLE
Redis master.persistence.storageClass not working

### ISSUE THREAD

**Issue by lolziac** [bitnami/charts#5921]
**Which chart**:
Redis 5.0.12

**Describe the bug**
master.persistence.storageClass has no effect when placed on values.yaml
example (**Azure**): storageClass: **managed-premium**

It works only when used within global:
global:
  storageClass: managed-premium

**To Reproduce**

1. Edit values.yaml
2. got to master persistence and add storageClass
`  persistence:`
`     enabled: true`
`     storageClass: managed-premium`

3. Save the file
4. deploy via kubectl, volumes are created with default setting

**Expected behavior**
Should create disks with manged-premium

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Helm 3.4.0
```

- Output of `kubectl version`:

```
Kubectl 1.19.3
```

**Additional context**
Azure AKS

**Comment by javsalgar** [comment]
Hi,

I am unable to reproduce the issue. I tried this 

```
❯ helm template redis bitnami/redis --set master.persistence.storageClass="managed-premium" -s templates/redis-master-statefulset.yaml
---
# Source: redis/templates/redis-master-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-master
  namespace: "default"
  labels:
    app: redis
    chart: redis-12.9.0
    release: redis
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: redis
      release: redis
      role: master
  serviceName: redis-headless
  template:
    metadata:
      labels:
        app: redis
        chart: redis-12.9.0
        release: redis
        role: master
      annotations:
        checksum/health: 26cd5f2eecb8f2900b65e250e3b71d4f3e10dc58185448886c2b8f53aed57f00
        checksum/configmap: b6ab687628e723af856bed8dcf255065671d78cc214b2cf45e0d6b2db974672e
        checksum/secret: a0af0d4127e47dd873aced50783e256d4c373e06a6315d39e751725c5801f73c
    spec:

      securityContext:
        fsGroup: 1001
      serviceAccountName: default
      containers:
        - name: redis
          image: docker.io/bitnami/redis:6.0.12-debian-10-r3
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 1001
          command:
            - /bin/bash
            - -c
            - /opt/bitnami/scripts/start-scripts/start-master.sh
          env:
            - name: REDIS_REPLICATION_MODE
              value: master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: REDIS_TLS_ENABLED
              value: "no"
            - name: REDIS_PORT
              value: "6379"
          ports:
            - name: redis
              containerPort: 6379
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            # One second longer than command timeout should prevent generation of zombie processes.
            timeoutSeconds: 6
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - /health/ping_liveness_local.sh 5
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - /health/ping_readiness_local.sh 1
          resources:
            null
          volumeMounts:
            - name: start-scripts
              mountPath: /opt/bitnami/scripts/start-scripts
            - name: health
              mountPath: /health
            - name: redis-data
              mountPath: /data
              subPath:
            - name: config
              mountPath: /opt/bitnami/redis/mounted-etc
            - name: redis-tmp-conf
              mountPath: /opt/bitnami/redis/etc/
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: start-scripts
          configMap:
            name: redis-scripts
            defaultMode: 0755
        - name: health
          configMap:
            name: redis-health
            defaultMode: 0755
        - name: config
          configMap:
            name: redis
        - name: redis-tmp-conf
          emptyDir: {}
        - name: tmp
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        labels:
          app: redis
          release: redis
          heritage: Helm
          component: master
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
        storageClassName: managed-premium
        selector:
  updateStrategy:
    type: RollingUpdate
```

As you can ese, the storageClass is in the YAML. Any other value I am missing?
