### ISSUE TITLE
ingress.yaml with extraHost not working

### ISSUE THREAD

**Issue by grobv** [bitnami/charts#5927]
**which chart**
keycloak

**Describe the bug**
extraHost with ingress.yaml not running as "Values.ingress.servicePort" cannot get resolved
error: Error: template: keycloak/templates/ingress.yaml:44:135: executing "keycloak/templates/ingress.yaml" at <.Values.ingress.servicePort>: nil pointer evaluating interface {}.ingress

**To Reproduce**

1. add an extraHost in values.yaml

**Expected behavior**
**1a) adjust ingress.yaml to set servicePort in values.yaml like** 
`backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" $) "servicePort" .servicePort "context" $) | nindent 14 }}`

so values.yaml would be like:
```
extraHosts:
- name: keycloak.local
servicePort: https
path: /
```

**1b) adjust ingress.yaml for set service port to http**
`backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" $) "servicePort" "http" "context" $) | nindent 14 }}`

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:53:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64
```

**Comment by alemorcuq** [comment]
Hi, @grobv.

I can't reproduce your issue. Here's what I'm doing: I'm enabling Ingress and creating and extra host. This is my custom values file:

```
❯ cat my.yaml
ingress:
  enabled: true
  extraHosts:
  - name: extra.local
```

I can successfully install the chart using that values file and the Ingress resource looks like this:

```
# Source: keycloak/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kc-keycloak
  namespace: amoreno
  labels:
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-2.4.2
    app.kubernetes.io/instance: kc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: keycloak
spec:
  rules:
    - host: keycloak.local
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              serviceName: kc-keycloak
              servicePort: http
    - host: extra.local
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              serviceName: kc-keycloak
              servicePort: http
```
