### ISSUE TITLE
[bitnami/redis] Redis chart has invalid priorityClassName

### ISSUE THREAD

**Issue by kuznero** [bitnami/charts#5954]
**Which chart**: bitnami/redis

**Describe the bug**

The helm chart has a default for the priorityClassName as `{}` where it should be `nil` instead.

```bash
helm upgrade redis bitnami/redis
# coalesce.go:196: warning: cannot overwrite table with non table for priorityClassName (map[])
```

My chart values use:

```yaml
master:
  priorityClassName: high-priority
slave:
  priorityClassName: high-priority
```

**Additional context**

This was fixed at some point (see issue #3997) that was then re-introduced https://github.com/bitnami/charts/commit/3a232d78e33b4e5a4a332114534e38e502eab766
