### ISSUE TITLE
[bitnami/MongoDB]Unable to modify the value of the root password via the values.yaml

### ISSUE THREAD

**Issue by SellamiRami** [bitnami/charts#5958]
**Which chart**:
The MongoDB Helm Chart  (V10.11.1)

**Describe the bug**
I want to integrate the Helm Chart of MongoDB with Adminer. I updated the values.yaml in order to enable the authentication and to update the value of the root password, the username and the password. However, the root password is not updated and its value still on the random 10 character long alphanumeric string by default. In addition, I am not able to connect my self using the username and the password defined in the values.yaml either directly in Mongodb or via Adminer.
I want to precise that I succeeded to connect using the (root/random 10 character password) in Adminer (and not using the other account).

The values.yaml:
```yaml
...
mongodb:
  clusterDomain: "fadi-mongodb"
  enabled: true
  persistence:
    enabled: true
  auth:
    enabled: true
    username: "admin"
    rootpassword: "password1"
    password: "password1"
    database: "mdb"
...
```
The chart.yaml:
```yaml
...
dependencies:
...
- name: mongodb
  version: ~10.9.0
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled
```
**Expected behavior**
The content of the root password is password1.
Able to connect to the database 'mdb' using the credentials admin/password1

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Could you please help me in fixing my problem. I'm very thankful in advance for your help.
