### ISSUE TITLE
[minio] Usage distributed mode,Pod keeps restarting

### ISSUE THREAD

**Issue by GounGG** [bitnami/charts#5962]
**Version:**
helm: v3
minio chart: 6.5.0
kubernetes: 1.18

values.yaml
```yaml
volumePermissions:
  enabled: true

mode: distributed
useCredentialsFile: true
disableWebUI: false
```

error log:
```shell
Disk `/data` the same as the system root disk.
Disk will not be used. Please supply a separate disk and restart the server.
Disk `http://thanos-minio-2.thanos-minio-headless.thanos-server.svc.cluster.local:9000/data` the same as the system root disk.
Disk will not be used. Please supply a separate disk and restart the server.
```
