### ISSUE TITLE
[bitnami|helm|magento] Magento not accessible via ingress controller

### ISSUE THREAD

**Issue by RudolfGross** [bitnami/charts#5967]
Helm Chart Version 17.2.5, APP Version: 2.4.2
Cant get Magento work on Kubernetes.

Install Script works and Magento gets installed but is not accessible via ingress domain.
Using nginx-ingress controller -> Response is Error 502

I also don't really get why magento/apache does not change the vhost.
```
magento 15:34:43.35 INFO ==> ** Starting Apache **
[Tue Mar 30 15:34:43.394250 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
```
values:
```yaml
containerPorts:
  http: 8080
  https: 8443

hostAliases:
- hostnames:
  - magento.local
  ip: 127.0.0.1

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  certManager: true
  enabled: true
  extraTls: []
  hostname: magento.domain.com
  path: /
  pathType: ImplementationSpecific
  tls: true

service:
  externalTrafficPolicy: Cluster
  httpsPort: 443
  nodePorts:
    http: ""
    https: ""
  port: 80
  type: ClusterIP
```

Service doesn't work with Ports 8443 and 8080 as well.

Any advise would be ver helpful.
