### ISSUE TITLE
When Load-definitions config is used in values file rabbitmq-password is nowhere to be found in the secrets created

### ISSUE THREAD

**Issue by Eugenevml** [bitnami/charts#5976]
**Which chart**:
rabbitmq (latest version)

**Describe the bug**
When deploying latest rabbitmq chart using load definitions as described in the manual the first secret gets deployed only containing Erlang cookie and user password to access RabbitMQ Management Console is nowhere to be found. 

This is what my values file contains (as suggested in the part of the manual that speaks about load-definitions): 
```yaml
auth:
  password: CHANGEME
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "users": [
          {
            "name": "{{ .Values.auth.username }}",
            "password": "{{ .Values.auth.password }}",
            "tags": "administrator"
          }
        ],
        "vhosts": [
          {
            "name": "/"
          }
        ]
      }
loadDefinition:
  enabled: true
  existingSecret: load-definition
extraConfiguration: |
  load_definitions = /app/load_definition.json
```
I deploy it via Jenkins using the following configs. Main part of the Jenkins config below: 

```
 RELEASE_NAME = 'rabbitmq-test'
      }
      steps {
        sh "mkdir -p ${HELM_HOME}"
        sh "mkdir -p ${XDG_CACHE_HOME}"
        sh "mkdir -p ${XDG_CONFIG_HOME}"
        sh "mkdir -p ${XDG_DATA_HOME}"

        sh "helm repo add bitnami https://charts.bitnami.com/bitnami"
        sh "helm repo update"

        sh "kubectl config set-cluster staging --server=${CLUSTER_IP}"
        sh "kubectl config set-credentials jenkins --token=${JENKINS_TOKEN}"
        sh "kubectl config set clusters.staging.certificate-authority-data ${KUBERNETES_CA}"
        sh "kubectl config set-context jenkins@staging --cluster=staging --user=jenkins"
        sh "kubectl config use-context jenkins@staging"

        sh """helm upgrade ${env.RELEASE_NAME} bitnami/rabbitmq \
          --install \
          --kubeconfig ${KUBECONFIG} \
          --namespace ${env.NAMESPACE} \
          --values rabbitmq/values.bitnami-rabbitmq.stg.yaml \
          --set rabbitmqErlangCookie=${ERLANG_COOKIE} \
          --wait"""
      }
    }
```

values.bitnami-rabbitmq.stg.yaml  only contains load-definition config stated above. 
I realize that load-definition secret takes precedence over any configuration done through Helm values. But please explain how to access management console now. 

**Expected behavior**

My goal is to template via values file a number of users, policies, vhosts and permissions and make them deployable on each upgrade to the rabbitmq instance. This is working very well in rabbitmq-ha (deprecated chart). At the same time I need to have an option to access management console. I tried putting administrator user in the load-definitions but this doesn't seem to work as I can't query the password from there as follows: 
kubectl get secret --namespace rabbitmq load-definition -o jsonpath="{.data.rabbitmq-password}" | base64 --decode -o yaml

When chart is deployed without that load-definitions config secret rabbitmq-test gets created containing rabbitmq-password that can be decoded and used to access management console. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:40:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.7800", GitCommit:"cef3156c566a1d1a4b23ee360a760f45bfbaaac1", GitTreeState:"clean", BuildDate:"2020-12-14T09:12:37Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```
