### ISSUE TITLE
[bitnami/*] checksum/secret annotation is incorrect if secret is randomly generated

### ISSUE THREAD

**Issue by charfa** [bitnami/charts#5977]
**Which chart**:
I encountered this error in `rabbitmq-8.11.5`, but I expect that a similar problem exists in all charts that utilize `checksum/secret` annotation.

**Describe the bug**
When `checksum/secret` annotation is generated it renders the template with secrets again, which causes the randomly generated passwords to be re-generated and different than the ones in actually created secret. As a result, even if the same password that was actually used is then provided during `helm upgrade`, the checksum will change and cause a restart of all pods. This may not be a big deal when upgrade would cause the pods to restart anyway, but if rabbitmq is used as a subchart and the upgrade doesn't have an impact on it, then pods restarting unnecessarily is annoying.

**To Reproduce**

```
> helm install rr bitnami/rabbitmq
[... success ...]
> RABBIT_PASSWORD=$(kubectl get secret --namespace default rr-rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)
> RABBIT_ERLANG_COOKIE=$(kubectl get secret --namespace default rr-rabbitmq -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 --decode)
> CHECKSUM_SECRET_BEFORE=$(kubectl get statefulsets.apps --namespace default rr-rabbitmq -o jsonpath="{.spec.template.metadata.annotations.checksum/secret}")
> helm upgrade rr bitnami/rabbitmq --set auth.password=$RABBIT_PASSWORD --set auth.erlangCookie=$RABBIT_ERLANG_COOKIE
[... success ...]
> CHECKSUM_SECRET_AFTER=$(kubectl get statefulsets.apps --namespace default rr-rabbitmq -o jsonpath="{.spec.template.metadata.annotations.checksum/secret}")
> [ $CHECKSUM_SECRET_BEFORE == $CHECKSUM_SECRET_AFTER ] && echo OK || echo FAIL
FAIL
```

**Expected behavior**
`checksum/secret` annotation shouldn't change if used secrets are the same during upgrade as the ones generated during first install.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I consider this a minor bug - the erroneous behavior is a potentially unnecessary restart of pods, but an upgrade often forces a restart anyways. And it only happens on first upgrade after fresh install, subsequent upgrade will set the checksum correctly (as the secrets are not randomly generated anymore.

I also checked if maybe this would be fixed with https://github.com/bitnami/charts/pull/4831, but the behavior is the same.

**Comment by marcosbc** [comment]
Hi @charfa,

> As a result, even if the same password that was actually used is then provided during `helm upgrade`, the checksum will change and cause a restart of all pods

Checking the logic, I don't see how that could happen except in the case that not all passwords/keys/secrets were specified in the same way.

For instance, `secrets.yaml` depends on the following inputs:

* Labels
* `.auth.existingPasswordSecret` / `.auth.password`
* `.auth.existingErlangSecret` / `.auth.erlangCookie`
* `.extraSecretsPrependReleaseName` / `.extraSecrets`

So if there is any type of variance in those values between the `helm install` and `helm upgrade`, Helm would detect there being a checksum change.

Could you triple confirm that those values are using the exact same values between `helm install` and `helm upgrade`?

**Comment by charfa** [comment]
As I mentioned, on first install the password is randomly generated (i.e. `auth.password` and `auth.erlangCookie` are not set). Problem is, it is randomly generated twice, once to create the actual secret, second time to generate `checksum/secret`. So the checksum ends up being incorrect.

**Comment by marcosbc** [comment]
My understanding from the issue is that the pod will only be restarted during the first `helm upgrade` (and not successive ones), given there being no changes to the passwords, right?

I'm not sure how this could be fixed though. It seems like an actual limitation of the current approach that cannot be avoided for now. It would require some sort of global variables, but my understanding is that [Helm doesn't support that](https://pkg.go.dev/text/template#hdr-Variables):

> A template invocation does not inherit variables from the point of its invocation.

**Comment by luddskunk** [comment]
I am experiencing the same thing. Using ArgoCD and a GitOps model with this chart makes RabbitMQ constantly to become out of sync. Quite annoying if you do not wish to hardcode a password for your RabbitMQ into version control or similar.

Let me know if anyone has tips or an idea to circumvent this issue! Thanks!

**Comment by rafariossaa** [comment]
Hi
  In your case, have you tried using a create a secret for the credentials and reuse the secret across re-deployments ?

**Comment by luddskunk** [comment]
Hello @rafariossaa !

I am not doing anything with my deployment, it just seems to "happen over time"

**Comment by alexshuraits** [comment]
I have worked around this issue by creating the secret with the ErlangSecret and the PasswordSecret, e.g.
```
apiVersion: v1
kind: Secret
metadata:
  name: mq-credentials
type: Opaque
stringData:
  password: mq-password
  erlang: f8RviqfKZEx3Mqbz
```
and adding to helm chart values:
```
  auth:
    username: mq
    existingErlangSecret: mq-credentials
    existingSecretErlangKey: erlang
    existingPasswordSecret: mq-credentials
    existingSecretPasswordKey: password
```
also I didn't specify any of `extraSecrets`

**Comment by ashuraits** [comment]
I have worked around this issue by creating the secret with the ErlangSecret and the PasswordSecret, e.g.
```
apiVersion: v1
kind: Secret
metadata:
  name: mq-credentials
type: Opaque
stringData:
  password: mq-password
  erlang: f8RviqfKZEx3Mqbz
```
and adding to helm chart values:
```
  auth:
    username: mq
    existingErlangSecret: mq-credentials
    existingSecretErlangKey: erlang
    existingPasswordSecret: mq-credentials
    existingSecretPasswordKey: password
```
also I didn't specify any of `extraSecrets`
