### ISSUE TITLE
[bitnami/postgresql] Allow running when read-only FS i set

### ISSUE THREAD

**Issue by byo** [bitnami/charts#5986]
**Which chart**:
postgresql 10.3.11

**Is your feature request related to a problem? Please describe.**
Vanilla chart can not run in an environment where `readOnlyRootFilesystem` is forced through Pod Security Policy.

**Describe the solution you'd like**
It should be possible to run vanilla `postgresql` chart on a cluster where `readOnlyRootFilesystem` is forced without an issue.

Running containers with read-only FS is advised by the [OWASP Docker Security Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html#rule-8-set-filesystem-and-volumes-to-read-only) and can prevent exploitation of various vulnerabilities discovered within postgresql itself.

**Describe alternatives you've considered**
It is currently possible to run the chart by adding few extra `emptyDir` volumes and an init container that copy files from the original image to the volume mounted under the `/opt/bitnami/postgresql/conf` path.

Here's an excerpt from a working deployment values on a constrained cluster:

```yaml
postgresql:
  enabled: true

  image:
    # Please also update the following value:
    #   postgresql.primary.extraInitContainers.0.image
    # if those values change
    repository: bitnami/postgresql
    tag: 11.11.0-debian-10-r24

  resources: ...

  # Remounting some locations as rw volumes to allow running
  # off rw filesystem
  primary:
    extraVolumes:
      - name: tmp
        emptyDir: {}
      - name: conf
        emptyDir: {}
      - name: tmp2
        emptyDir: {}
    extraVolumeMounts:
      - name: tmp
        mountPath: /tmp
      - name: conf
        mountPath: /opt/bitnami/postgresql/conf
      - name: tmp2
        mountPath: /opt/bitnami/postgresql/tmp/
    extraInitContainers:
      - name: prepare-rw-conf
        image: bitnami/postgresql:11.11.0-debian-10-r24
        resources: ...
        volumeMounts:
          - name: conf
            mountPath: /rw
        command:
          - sh
          - -eux
          - -c
          - |
            # Prepare rw paths
            rm -rf /rw/*
            cp -rT /opt/bitnami/postgresql/conf/ /rw
```

Even though this solution works, it's not perfect since it has to be copied into every new postgresql installation.

In addition to that, the trick with copying data to `conf` volume in an extra init container seems like a workaround that could be easily fixed within the bitnami chart itself (e.g. storing all generated / modified files in some subfolder or copy the conf files from some other location when setting up postgresql instance).

In the attached values, it's also required to specify a correct image to the init container that must be in-sync with the main postgresql image (although I believe this could be fixed by [import-values](https://helm.sh/docs/topics/charts/#importing-child-values-via-dependencies) or by using some template from postgresql chart).
