### ISSUE TITLE
[bitnami/postgresql-ha] Lack of permissions on data directory

### ISSUE THREAD

**Issue by kmute90** [bitnami/charts#5991]
**Which chart**:
postgresql-ha 6.8.1

**Describe the bug**
Simple installation of the chart on Azure AKS.

**Pod output:**
```
postgresql-repmgr 15:07:46.05
postgresql-repmgr 15:07:46.05 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 15:07:46.06 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 15:07:46.06 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 15:07:46.06
postgresql-repmgr 15:07:46.09 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 15:07:46.13 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 15:07:46.13 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 15:07:46.14 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 15:07:46.18 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 15:07:46.19 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 15:07:46.19 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 15:07:46.36 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 15:07:46.37 INFO  ==> Initializing Repmgr...
postgresql-repmgr 15:07:46.38 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 15:07:46.42 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 15:07:46.42 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
postgresql-repmgr 15:07:46.44 WARN  ==> Lack of permissions on data directory!
chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
postgresql-repmgr 15:07:46.44 WARN  ==> Lack of permissions on data directory!
```

**here is my values.yaml:**

```
postgresql:
  nodeSelector: 
    agentpool: toolspool

pgpool:
  replicaCount: 1
  nodeSelector:
    agentpool: toolspool
  
persistence:
  storageClass: "azurefile-premium"
  mountPath: /bitnami/postgresql
  accessModes:
    - ReadWriteOnce
  size: 100Gi

volumePermissions:
  enabled: true

service:
  type: NodePort
  nodePort: 35432

metrics:
  enabled: true
```

**To Reproduce**
```
helm install postgresql bitnami/postgresql-ha -f values.yaml
```

**Expected behavior**
working postgresql

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T15:16:40Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
