### ISSUE TITLE
[bitnami/rabbitmq] When use load_definitions that unable to scale statefulset

### ISSUE THREAD

**Issue by sereneliesti** [bitnami/charts#5994]
**Which chart**:
Chart: bitnami/rabbitmq 8.11.5
Rabbitmq image tag: 3.8.14

**Describe the bug**
When use load_definitions functional - there is no way to scale rabbitmq to more replicas, for example, 
we have a values.yaml with this values:
```yaml
   nameOverride: example-rabbitmq 
   replicaCount: 1
   podManagementPolicy: Parallel
   persistence:
       enabled: true
       storageClass: example-local-storage
  loadDefinition:
    enabled: true
    existingSecret: example-rabbitmq-definitions
  extraSecrets:
    example-rabbitmq-definitions:
      load_definition.json: |
        {
          "users": [
             {
               "name": "exampleadmin",
               "password": "exampleadmin",
               "tags": "administrator"
             }
          ],
          "vhosts": [
            {
              "name": "/"
            }
          ],
          "permissions": [
            {
              "user": "exampleadmin",
              "vhost": "/",
              "configure": ".*",
              "write": ".*",
              "read": ".*"
            }
          ],
          "parameters": [
           ],
          "policies": [         
          ]
        }
  extraConfiguration: |
    load_definitions = /app/load_definition.json
```

We do a `helm install` command with this values, and get rabbitmq with one normal running pod. Also there is a two new
secrets - example-rabbitmq-definitions with our load_definitions.json and example-rabbitmq with rabbitmq-erlang-cookie value, for example: `rabbitmq-erlang-cookie: d3FmS05GVDAzUjBsM2NFbFU5VldVclFCM1FaSDlhWkU=`

After that, we need to scale our rabbitmq cluster to 3 replicas, we change replicaCount values to 3, and do 
`helm upgrade`, but there is a error like:

> 'auth.erlangCookie' must not be empty, please add '--set auth.erlangCookie=$RABBITMQ_ERLANG_COOKIE' to the command. To get the current value:

        export RABBITMQ_ERLANG_COOKIE=$(kubectl get secret --namespace "testi" example-rabbitmq -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 --decode)

If we add auth.existingErlangSecret values, like `auth.existingErlangSecret: rabbitmq` helm upgrade is finish succesfull,
but two new pods do not start with error 

> Error: couldn't find key rabbitmq-erlang-cookie in Secret test/example-rabbitmq 

and there is true - secret example-rabbitmq do not include any record in data field, and rabbitmq-erlang-cookie was gone from secret, i.e. 
```console
$ kubectl get secret example-rabbitmq -o yaml
apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: example-rabbitmq 
    meta.helm.sh/release-namespace: test
  creationTimestamp: "2021-04-02T13:19:12Z"
  labels:
    app.kubernetes.io/instance: example-rabbitmq 
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: example-rabbitmq 
    helm.sh/chart: rabbitmq-8.11.5
  name: example-rabbitmq 
  namespace: test
  resourceVersion: "806789351"
  selfLink: /api/v1/namespaces/test/secrets/example-rabbitmq 
  uid: 136c8de7-dbdb-4dcd-90a1-fd4f6f532a11
type: Opaque
```
is there is a normal way to helm upgrade chart with load_definitions functionality? Or maybe there is impossible to
scale replicas with values.yaml, but only with `kubectl scale sts example-rabbitmq --replicas=3` command (because 
scaling sts with command was working as expected, and after command there is 3 pods in one rabbitmq cluster)?
Or maybe we do something wrong, and there is another way to do this? Or load_definitions work only to first
start of cluster and we can't use this for follow chart changes?

**To Reproduce**
1. Create a rabbitmq sts with replicaCount:1 and load_definitions functional via `helm install`
2. Change replicaCount to replicaCount:3
3. Do helm upgrade 
4. Face with `'auth.erlangCookie' must not be empty` error
5. Add auth.existingErlangSecret for created after 1 secret
6. Do helm upgrade
7. Face with `Error: couldn't find key rabbitmq-erlang-cookie in Secret test/example-rabbitmq `

**Expected behavior**
We change replicaCount to any number in values.yaml, do `helm upgrade` and get a normal rabbitmq cluster
with n nodes

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:40:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"windows/amd64"}

```

**Additional context**
