### ISSUE TITLE
[bitnami/nats] client-svc not compatible with Istio

### ISSUE THREAD

**Issue by dsargent3220** [bitnami/charts#5999]
Current chart sets the service port name to `client`, this does not allow istio to configure properly to the port.
https://github.com/bitnami/charts/blob/master/bitnami/nats/templates/client-svc.yaml
Changing the port name to `tcp` fixes this and allows Istio to route traffic to the service over MTLS properly.
From:
```
spec:
  clusterIP: 10.43.72.78
  clusterIPs:
  - 10.43.72.78
  ports:
  - name: client
    port: 4222
    protocol: TCP
    targetPort: client
```
To:
```
spec:
  clusterIP: 10.43.72.78
  clusterIPs:
  - 10.43.72.78
  ports:
  - name: tcp
    port: 4222
    protocol: TCP
    targetPort: client
```

See: https://github.com/nats-io/nats-operator/issues/88
I don't think there is any reason to have the port name match the service name.
It would probably be wise to change all of the services port names to `tcp`
i.e.
* client-svc.yaml
* cluster-svc.yaml
* headless-svc.yaml
* metrics-svc.yaml
* monitoring-svc.yaml

Versions:
Istio 1.8.300
nats: bitnami 6.2.3 (latest as of the time of this writing)
