### ISSUE TITLE
RabbitMQ pod in CrashLoopBackOff state after setting command

### ISSUE THREAD

**Issue by anthonyvk** [bitnami/charts#6040]
**Which chart**:
RabbitMQ chart. Version : 8.2.0

**Describe the bug**
RabbitMQ pod in CrashLoopBackOff state after setting command in the values.yaml. 
I removed from values.yaml and tried setting in statefulset.yaml in the command section, it is going in the CrashLoopBackOff state . 
If I do no specify the command, the deployment goes fine.

**To Reproduce**
**Set this on values.yaml of rabbitmq chart :** 

```
## Command and args for running the container (set to default if not set). Use array form
##
command:
  - ls
```

or hardcode in statefulset.yaml

```
      containers:
        - name: rabbitmq
          image: {{ template "rabbitmq.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.containerSecurityContext }}
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- end }}
          command:
            - ls

```
**Expected behavior**
Deployment should go fine.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v3.3.4+ga61ce56
```

- Output of `kubectl version`:

```
Client Version: v1.18.6
Server Version: v1.19.7

```

**Comment by carrodher** [comment]
This is something expected since you're trying to execute a command (and it should be executed) that ends once executed so the container dies at the same time.

You can easily see what is happening by using docker-compose:
```yaml
 version: '2'

 services:
   rabbitmq:
     image: docker.io/bitnami/rabbitmq:3.8
     command: ls
     ports:
       - '4369:4369'
       - '5672:5672'
       - '25672:25672'
       - '15672:15672'
     volumes:
       - 'rabbitmq_data:/bitnami'
 volumes:
   rabbitmq_data:
     driver: local
```
I just added `command: ls` to the default docker-compose present at https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/docker-compose.yml.

Then, deploying this docker-compose:
```console
$ docker-compose up
Creating network "bitnami-docker-rabbitmq_default" with the default driver
Creating volume "bitnami-docker-rabbitmq_rabbitmq_data" with local driver
Creating bitnami-docker-rabbitmq_rabbitmq_1 ... done
Attaching to bitnami-docker-rabbitmq_rabbitmq_1
rabbitmq_1  | rabbitmq 16:27:27.82
rabbitmq_1  | rabbitmq 16:27:27.82 Welcome to the Bitnami rabbitmq container
rabbitmq_1  | rabbitmq 16:27:27.82 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
rabbitmq_1  | rabbitmq 16:27:27.82 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
rabbitmq_1  | rabbitmq 16:27:27.82
rabbitmq_1  |
rabbitmq_1  | bin
rabbitmq_1  | bitnami
rabbitmq_1  | boot
rabbitmq_1  | dev
rabbitmq_1  | etc
rabbitmq_1  | home
rabbitmq_1  | lib
rabbitmq_1  | lib64
rabbitmq_1  | media
rabbitmq_1  | mnt
rabbitmq_1  | opt
rabbitmq_1  | proc
rabbitmq_1  | root
rabbitmq_1  | run
rabbitmq_1  | sbin
rabbitmq_1  | srv
rabbitmq_1  | sys
rabbitmq_1  | tmp
rabbitmq_1  | usr
rabbitmq_1  | var
bitnami-docker-rabbitmq_rabbitmq_1 exited with code 0
```
from the previous logs, `ls` is executed and the result is showed in the logs, but the container ends once the command is executed. Something similar is happening with the Helm Chart, but the logs are less accessible since the container is not running.

The `command` parameter was created to override the default entrypoint when using a custom image not based on the Bitnami one.
