### ISSUE TITLE
Mongodb TLS 

### ISSUE THREAD

**Issue by ppathard** [bitnami/charts#6045]
I am trying to reuse the same certificate that we use for vault in mongodb. Vault requires CA signed cert, hence we are using kubernetes as Signing Authority.

```
# Generate private key
openssl genrsa -out root.key 2048

# Generate Certificate SIgning Request
openssl req -new -key root.key -subj "/CN=*.${NAMESPACE}.svc" -out server.csr -config csr.conf
# Create the CertificateSigningRequest on Kubernetes
kubectl create -f csr.yaml;
# Approve the certificate request
kubectl certificate approve ${CSR_NAME};
# Get the  certificate and store in crt
serverCert=$(kubectl get csr ${CSR_NAME} -o jsonpath='{.status.certificate}');
echo "${serverCert}" | openssl base64 -d -A -out ${TMPDIR}/root.crt;
# Copy the kubernetes ca crt file 
cp -f /var/run/secrets/kubernetes.io/serviceaccount/ca.crt root.ca;


cat root.crt root.key > client-pem
kubectl create secret generic mongo-tls \
 --namespace ${NAMESPACE} \
 --from-file=client-pem=client-pem \
 --from-file=mongodb-ca-cert=root.ca  \
 --from-file=mongodb-ca-key=root.key
```

I keep getting the error CA Key and Private Key do not match. Please find necessary files below. Can some one help please ?

**csr.conf**
-----
```
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names
[alt_names]
DNS.1 = ${RELEASE_NAME}-*-svc
DNS.2 = *.${NAMESPACE}
DNS.3 = *.${NAMESPACE}.svc
DNS.4 = *.${NAMESPACE}.svc.cluster.local
DNS.5 = *-mongodb-headless
DNS.6 = *-mongodb-headless.${NAMESPACE}
DNS.7 = *-mongodb-headless.${NAMESPACE}.svc
DNS.8 = *-mongodb-headless.${NAMESPACE}.svc.cluster.local
DNS.9 = *-mongodb-*
```

**csr.yaml**
----
```
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
 name: ${CSR_NAME}
spec:
 groups:
 - system:authenticated
 request: $(cat server.csr | base64 | tr -d '\n')
 usages:
 - digital signature
 - key encipherment
 - server auth
```

**Comment by alvneiayu** [comment]
hi @ppathard 

I am trying to reproduce it. Let me investigate your problem and I going to come back as soon as possible with some information.

Thanks

**Comment by alvneiayu** [comment]
hi @ppathard 

I tried to reproduce the issue generating my own cert, key and pem:

```
openssl genrsa -out mongoCA.key 2048
openssl req -x509 -new -subj "/C=US/ST=NY/L=New York/O=Example Corp/OU=IT Department/CN=mongoCA" -key mongoCA.key -out mongoCA.crt

openssl req -new -nodes -subj "/C=US/ST=NY/L=New York/O=Example Corp/OU=IT Department/CN=ownsecret" -keyout ownsecret.key -out ownsecret.csr
openssl x509 -req -days 365 -in ownsecret.csr -out ownsecret.crt -CA mongoCA.crt -CAkey mongoCA.key -CAcreateserial -extensions req
cat ownsecret.key ownsecret.crt > ownsecret.pem

kubectl create secret generic own-tls  --namespace default  --from-file=client-pem=ownsecret.pem  --from-file=mongodb-ca-cert=ownsecret.crt --from-file=mongodb-ca-key=ownsecret.pem
```
I checked the connection:

```
openssl s_client -connect 127.0.0.1:27017
CONNECTED(00000003)
Can't use SSL_get_servername
depth=1 C = US, ST = NY, L = New York, O = Example Corp, OU = IT Department, CN = mongodb-primary
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=1 C = US, ST = NY, L = New York, O = Example Corp, OU = IT Department, CN = mongodb-primary
verify error:num=24:invalid CA certificate
verify return:1
depth=1 C = US, ST = NY, L = New York, O = Example Corp, OU = IT Department, CN = mongodb-primary
verify error:num=26:unsupported certificate purpose
verify return:1
depth=0 C = US, O = My Organisations, OU = IT, CN = my-test-mongodb-645bc74976-tmwxq
verify return:1
---
...
```
And it seems that the chart is working properly. I can not reproduce any issue enabling the TLS in mongoDB with secrets. I think that you are having problems with the format of one of your file.

I hope that I helped you. Thanks for your time

Álvaro

**Comment by ppathard** [comment]
@alvneiayu  are you saying that when I set the existingSecret mongodb does not create its own certificate ?

In the templates/replicaset/statefulset.yaml
I dont see condition {{- if .Values.tls.enabled }} not existingSecret .

```
- name: generate-tls-certs
          image: {{ include "mongodb.tls.image" . }}
          imagePullPolicy: {{ .Values.tls.image.pullPolicy | quote }}
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
          - name: certs-volume
            mountPath: /certs/CAs
          - name: certs
            mountPath: /certs
          command:
            - sh
            - "-c"
            - |
              /bin/bash <<'EOF'
              my_hostname=$(hostname)
              svc=$(echo -n "$my_hostname" | sed s/-[0-9]*$//)-headless
              cp /certs/CAs/* /certs/
              cat >/certs/openssl.cnf <<EOL
              [req]
              req_extensions = v3_req
              distinguished_name = req_distinguished_name
              [req_distinguished_name]
              [ v3_req ]
              basicConstraints = CA:FALSE
              keyUsage = nonRepudiation, digitalSignature, keyEncipherment
              subjectAltName = @alt_names
              [alt_names]
              DNS.1 = $svc
              DNS.2 = $my_hostname
              DNS.3 = $my_hostname.$svc.$MY_POD_NAMESPACE.svc.cluster.local
              DNS.4 = localhost
              DNS.5 = 127.0.0.1
              DNS.6 = 10.60.6.106
              DNS.7 = 10.60.7.201
              {{- if .Values.externalAccess.service.loadBalancerIPs }}
              {{- range $key, $val := .Values.externalAccess.service.loadBalancerIPs }}
              IP.{{ $key }} = {{ $val | quote }}
              {{- end }}
              {{- end }}
              EOL

              export RANDFILE=/certs/.rnd && openssl genrsa -out /certs/mongo.key 2048
              #Create the client/server certificate
              openssl req -new -key /certs/mongo.key -out /certs/mongo.csr -subj "/C=US/O=My Organisations/OU=IT/CN=$my_hostname" -config /certs/openssl.cnf
              #Signing the server certificate with the CA cert and key
              openssl x509 -req -in /certs/mongo.csr -CA /certs/mongodb-ca-cert -CAkey /certs/mongodb-ca-key -CAcreateserial -out /certs/mongo.crt -days 3650 -extensions v3_req -extfile /certs/openssl.cnf
              rm /certs/mongo.csr
              #Concatenate to a pem file for use as the client PEM file which can be used for both member and client authentication.
              cat /certs/mongo.crt /certs/mongo.key > /certs/mongodb.pem
              cd /certs/
              shopt -s extglob
              rm -rf !(mongodb-ca-cert|mongodb.pem|CAs|openssl.cnf)
              chmod 0600 mongodb-ca-cert mongodb.pem
              EOF
        {{- end }}
```

**Comment by alvneiayu** [comment]
hi @ppathard 

No, maybe I explained bad, sorry. You have two options to use TLS in MongoDB. The first one is to create your own secret and setting up the existingSecret option. To do that, I created my own certificate, key and pem following the commands that I shared with you and I created the secret. Then, I installed the mongodb chart:

```
helm install my-test bitnami/mongodb --set tls.enabled=true --set tls.existingSecret=own-tls
```

And it works properly. The chart is using the secret generated manually.

The second options is without using the existingSecret key:

```
helm install my-test bitnami/mongodb --set tls.enabled=true
```

And the chart will create a secret with the certificate, key and pem generated by itself.

```
cat bitnami/mongodb/templates/secrets-ca.yaml

{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) -}}
{{- $cn := printf "%s.%s.svc.cluster.local" ( include "mongodb.fullname" . ) .Release.Namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mongodb.caSecretName" . }}
  namespace: {{ template "mongodb.namespace" . }}
  labels:
   {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  {{ if and .Values.tls.caCert .Values.tls.caKey }}
  {{- $ca := buildCustomCert .Values.tls.caCert .Values.tls.caKey -}}
  {{- $cert := genSignedCert $cn nil nil 3650 $ca -}}
  {{- $pem := printf "%s%s" $cert.Cert $cert.Key -}}
  mongodb-ca-cert: {{ b64enc $ca.Cert }}
  mongodb-ca-key: {{ b64enc $ca.Key }}
  client-pem: {{ b64enc $pem }}
  {{- else -}}
  {{- $ca:= genCA "myMongo-ca" 3650 -}}
  {{- $cert := genSignedCert $cn nil nil 3650 $ca -}}
  {{- $pem := printf "%s%s" $cert.Cert $cert.Key -}}
  mongodb-ca-cert: {{ b64enc $ca.Cert }}
  mongodb-ca-key: {{ b64enc $ca.Key }}
  client-pem: {{ b64enc $pem }}
  {{- end -}}
{{- end -}}
```

```
helm template my-test bitnami/mongodb --set tls.enabled=true
...
# Source: mongodb/templates/secrets-ca.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-test-mongodb-ca
  namespace: default it is working properly
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.12.2
    app.kubernetes.io/instance: my-test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  mongodb-ca-cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGakNDQWY2Z0F3SUJBZ0lSQU5xZXdjckxJQ3hBQUhab24vRE5WTFl3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2JYbE5iMjVuYnkxallUQWVGdzB5TVRBME1Ea3hOakk1TURaYUZ3MHpNVEEwTURjeApOakk1TURaYU1CVXhFekFSQmdOVkJBTVRDbTE1VFc5dVoyOHRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJEd0F3Z2dFS0FvSUJBUUM1d05NQ1ZKMXhrcE1BYlZCN0FIa0craU5lQ0xJUUdqY3UvVU95Sm5aSG10cWsKSVFXOGhqcENxM2R5NlhRZjVSMTRBcGJUM0RDdkFDVVBKTlN5REdINTd2Z0s2QTFZd1V4aUlKZzRHWFJaeU9JSAorK1E3UTA0akQzbC85NytaWFNxR0hmVmFWRndWRHBCWVBPa0c3bDhVZ1NhMVNIdjlvamM2SU45VXdYWk1QckphClNhUDlRcnlScytCbmJ2N0VkbDZNMlF1SEF3dzlHVXYyTGRpTC9oR2FCNEtQNVhrNUxtdUI5S1doUjEyUU1ZME0KNlBKd0poTThyU1U2cEN0VWJWNktEVUdjUmZMeGdHTzk0R2ZDKzFNUTNDOFpOVnlXTm0yOFdZUTVXeGxWQlZuOQpIcUJSUGlxclA1UVJISW5tc0hJc2pxM3lya2FiRmxEaUZINWFTUVBCQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCCi93UUVBd0lDcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC8KQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVSHBPWkJpcHlKOCtmbWt0ZDJ3UjR3WmU5UVZJd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBSXRpZXMzRndVUzdLY2g0eDVsdFB5amZJMS9BNlpJak9NVGVJUnpYRjBiV1ZVYStUdldlCjVVMmplVHNzTjA0dEtvQ0xuZUdiREQ1WlkvVmlDbFFvME9hb1JTMm1XWTJQeEVsNktjZ3dGTW9vS3FJNVJiZTYKbUVBbTl4cUNkSG5XaVkrbFZzM0dyU25CcHdaVFBMYWgzL25GNUNnZUtpSVRPYjNEcVhFd2dXVGE0SUtJdHNLZgpkdEg5ZzNOV1BjY3VFaVJZMTUzU24rQjRPalZBRFBWaXpnM2FYNVh3bHVhNlVNWGt6Zk45VXJTTDRnbGpJQmh5CjMvZGhHdXJNdW5wTDhDTlBvYmMwSUtRM080ZE1yVFlJQVlOakdyMWpIbU11VWpKTWM2K09lM29lTWRFcktOYTQKVm5henhseEdJMzlaZjN2eGRIMjRsUU8yUTI1WWlLQm8xOVE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  mongodb-ca-key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdWNEVEFsU2RjWktUQUcxUWV3QjVCdm9qWGdpeUVCbzNMdjFEc2laMlI1cmFwQ0VGCnZJWTZRcXQzY3VsMEgrVWRlQUtXMDl3d3J3QWxEeVRVc2d4aCtlNzRDdWdOV01GTVlpQ1lPQmwwV2NqaUIvdmsKTzBOT0l3OTVmL2UvbVYwcWhoMzFXbFJjRlE2UVdEenBCdTVmRklFbXRVaDcvYUkzT2lEZlZNRjJURDZ5V2ttagovVUs4a2JQZ1oyNyt4SFplak5rTGh3TU1QUmxMOWkzWWkvNFJtZ2VDaitWNU9TNXJnZlNsb1VkZGtER05ET2p5CmNDWVRQSzBsT3FRclZHMWVpZzFCbkVYeThZQmp2ZUJud3Z0VEVOd3ZHVFZjbGpadHZGbUVPVnNaVlFWWi9SNmcKVVQ0cXF6K1VFUnlKNXJCeUxJNnQ4cTVHbXhaUTRoUitXa2tEd1FJREFRQUJBb0lCQUFWQlBUYnRxZDZTcFBINApKYlMxR0xkbjBDUlMzcWF4OXltdkpJRWZzV3pwSnBKS0ZOMTJkcU40TWxMZjQ5Y2JKakJFOG50ZjJVaTZHbEpKClduTUhBcWFOYWhyMDRadkhMQ0FDaUF2ZVBIcGx3bTh6WXd1Q0plMjcvRlh3YmswcVk0K1R2V01teTh3VXMyU3IKcEhQN3ZsallKbjR1Wk1PU0dUbmR3RE9ublc4ZXNvNkQ1SlNGRXdDTlhDZjY0YWpxK3NDbjlqNXNhWmVodC9NQwpGOXE4YU42K3lIRytLc0dsSkpBU0RPbnlBL3hza2pseTVXYlhkaVgvWDdTVXl4cEhGNjhVbFZIeWdtMmlkbUlwCk5wSGs1QlBabVY1bU91TUYvVWVEWDNhQmpjelpMNERyK1FOU2dRYUJobGZ3UEV6MEk1Ymg1ZlVEV25CRXlzZkIKcUlZYjJnRUNnWUVBeC9EYXZjQVluTTBaUWdSanY1clo1WUpObDdpVzdWT1h2bitOMGdhdGNhTkgvNmY2SlVYUQpVeWlkb2xCZVBaWXhyaHhqdjcwRFA0anhmYnRyZXIvS3VxeEIyZjFSdlFIYmVPRzZvc0d6a1djSjdOblJXQWdICks3MkdqaHVwbVcyM3NIVnZyWGJ4ckw0ak9EaGJrVU54c1pmTlA5V09zVzBDM0lYVUM1bll6TkVDZ1lFQTdkV2cKTGtKMWxPbElnR0JxUzU0UDgvdUlrUWFyRlQyTnd2QWhKaW9sVW5yTTRRRDNJa1NTaVdncTk3ZktORm9HcjIv it is working properlyegppMklhSVJuNllpL2xEcHBvWUM3eTF4MjhHVElUWVBoZkhCNVovS2pDNXRiSUZnNTZWTmZMcFg1OEtKVGZKbGJnCkhUUFhXaW1EaG5NTURiemVCWHJlQ09uYVY2WUpGMzYyRGJXZHcvRUNnWUFIcGZ3SUpEQU0xMyt1MmRJakF6NXcKbkNKeHVscnpxeTN6MkpkSlFINGtDYlg0WHFtZ0FXS3R1N0VFQTRVSFlCWjRiWmVYUHhpL3RuSmVkK3Z0bnlhWApLMzI5WkFaYmI1WEFzd25icmdNN2ZiQ1FnZWlUTUlOdHRldE94bG9maDJYdWR4K1ZpQ1pJa0dGeWhoMWltaXpnCk9VbGR0c0tsb09EcUpLaHU1U3k0OFFLQmdRRExmVkVNNDI0SkY4UWhtdHkza0Npa0h4Mk13RURXN3BDQkxzV2UKQ3NkZUY1VitHajVZd29VQ0xlODlmYkh6TXVldmFVRGVpL1JCU0NIVHFwajM4cUxGVU1ZVHlld3JQbzRZRk1vRAptL0J3WGRCTWc0NDBXUFRQN01iZjlTV3o3eFF5a0hnMlpDbW9pZ1p2bmJXOWQxQWJMaklWUEVqRlgxaytFZnNnCkpia3pjUUtCZ0RuNFFaTmRIcHpXdXZhcWh0bUtrRFljUitvMDl0akZEdkcyZFlSbkRHNGgrSGc0NFF6Nlg3Y0EKN29yRDllTTgrV01YamFrR3R2T0d1SEUrNFQ5ZlBITWo3YnRCaWlkS2ZQNmgzeFRUQ1ZPL1F5MUs3Zk5QcmlUcgp4ejdJRndvYXdPNXM5endqME04M2RmeWs1bzVQTHJDaExNajhKdWhWQnRoQ2NoZjRhenBHCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  client-pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURORENDQWh5Z0F3SUJBZ0lSQUlySWxKaFpHVjRVM1ZBUHRDZXM4UU13RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2JYbE5iMjVuYnkxallUQWVGdzB5TVRBME1Ea3hOakk1TURaYUZ3MHpNVEEwTURjeApOakk1TURaYU1EUXhNakF3QmdOVkJBTVRLVzE1TFhSbGMzUXRiVzl1WjI5a1lpNWtaV1poZFd4MExuTjJZeTVqCmJIVnpkR1Z5TG14dlkyRnNNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQThydnAKZ1dhQjJPdXVjS3FYMlpWbUwvQnh0MkZ5eitnTjdoR3lSRitFN29jZm4wS1VpSFBaU0N6SWtBMWxINFB3Ym80WApzcE95WUc0WEVoNUMrSUwwTWpGZ3hVdkl4WVhRek4zY1NTQjZibWZiZzQ0OGhPbjZFZkNORjU4VXlpK1lNRE11CmtqUlJncFgvVGVvZE9GTVNZdVA3VmhNcHhmNlo4WUpUT2taNG12aFNRRVNzM3UxSHNubzNGVTFwd3JZTEZSdzcKd3N6N1lQdEl0VG9FcDV5em1pOFRGMHpJTWd0bTRIUmp1aVlieXZ4eHdDNGJWb3JxYUl3MTVwWnpGWTlMZ2dURApaMS9zOEQvZzJsaC9uT1U2dVlSSG0rTlRJVU1yeWVyMFZ2V0JreXRyaytXTHhJcytWSTVmMHg2YVN3NmFTajQxCldscWZrQUJvZkU2R0JtTHpLUUlEQVFBQm8yQXdYakFPQmdOVkhROEJBZjhFQkFNQ0JhQXdIUVlEVlIwbEJCWXcKRkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQi93UUNNQUF3SHdZRFZSMGpCQmd3Rm9BVQpIcE9aQmlweUo4K2Zta3RkMndSNHdaZTlRVkl3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUNoUHorQWpqNWtKCi9FUVZSZUREb01pWmZ1UE5LUE9hSmJKbmljOHBTdjVUaklCN2RUcWVhVTBTNzJKbEY4Q3pJSFRLNkt0NjJ0cDcKOHVWRDkwQ2hSb3dKdENRa2NZcXhsUlV3d2p5SGpORjFBOVdkTXc0QkhxN3daSS9iVlZNRkpyZmRWVUR4RUc0cQpiQnJSRmxKeHVjRXZuODRRRStUM2hTSitkc09oOXF4UVFaNlZFbnhCd3hIdUtQN1pjZkJ0bUt0ejhTY1c0S0FrCmFaTTFYQndMZk1oVkM0ckxqVkZRa0JxU0JORU14Sk0vOENrVDE1Yis3NXU3MkZFRzJHMG5aSGlsU2ZjSWdmQVQKMWUzVXU4WjVWVmZRL0h2ZDZmQWgvME96SGJic0toZGlYc3llTFMwUCtqei9VN20xK2M4bmFMMkdEd05WbTJacgpmNHk3dEhFTFJMYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIFJTQSBQUklWQVRFIEtFWS0tLS0tCk1JSUVwQUlCQUFLQ0FRRUE4cnZwZ1dhQjJPdXVjS3FYMlpWbUwvQnh0MkZ5eitnTjdoR3lSRitFN29jZm4wS1UKaUhQWlNDeklrQTFsSDRQd2JvNFhzcE95WUc0WEVoNUMrSUwwTWpGZ3hVdkl4WVhRek4zY1NTQjZibWZiZzQ0OApoT242RWZDTkY1OFV5aStZTURNdWtqUlJncFgvVGVvZE9GTVNZdVA3VmhNcHhmNlo4WUpUT2taNG12aFNRRVNzCjN1MUhzbm8zRlUxcHdyWUxGUnc3d3N6N1lQdEl0VG9FcDV5em1pOFRGMHpJTWd0bTRIUmp1aVlieXZ4eHdDNGIKVm9ycWFJdzE1cFp6Rlk5TGdnVERaMS9zOEQvZzJsaC9uT1U2dVlSSG0rTlRJVU1yeWVyMFZ2V0JreXRyaytXTAp4SXMrVkk1ZjB4NmFTdzZhU2o0MVdscWZrQUJvZkU2R0JtTHpLUUlEQVFBQkFvSUJBUUNVUURiV3BKL3J0ODViCjI2VlE3QkYwZUJ0TUVFV0tPOFcrUUtxclhkZVh3NG1Kd0tWdFRheElpNm1YYWNiNFg2SUtNOWkvWmJ2TmI0L0IKcmgvakhrQTlJN0ZoN3U1WnpXZ0FxQVJ4MlZkTmRUczU5elo1UzFwRGVMTUQyVkplUm9GaDl2Q2J0VDZQVGtPVwo5OFVPOEpYTE5rajhna25DTnNVWkh5cnI3Ynlka0pwVGxiWW1pdVduMWVCR3FlVXpmbnZHeFNRYXhlMFN4by9wCklhOG1ZZzYwNnJZUS9GOFZDQUpia0NCWTlhdCs1U05VWERpbW1PaXFITmYwNzJvVWVKNWhoaXVZRTg1cVFPM1MKM0NGQTNjVzZaZzlBL1FTaWwxL3ZpZXAwRTQvdDNVbkZkWGVoTUw5dkZVakNyZ0JQbE1UTU9nUXF0cVk0KzlHWApNMXlTbFdqZEFvR0JBUGtsRDNkYkJQMEdJMXFkUlQrRXNrOTdPclMvbzBrWkcyWm5MWnFxMVNQWmk3RTJ0Slo3CnAzTzJPaTVZMzg2M1JpR1JaMWlrdEZrMkhycW1aeU1icGZWZDRRUTRFcElBT2w0Y1Zoc08yY1I4cFFWZGh5M0MKd1pHYndvbHJuVUhJanR2VmlxKzQ4bit1VWt1aTZjazc2cVZaREdUbDFnamNYbXdRQnpHb2lLRmZBb0dCQVBscApzZ2RrOVZnUlJjY1NaYUhqNDMyT0VaUTJyZzVaT05NS1U4TXdCVHBtK3hsblEvNmRZZm85eHFCVm5YdnZQdzdRCnpya2IxSW0rOGFkNHphMENNSDFKeVpsU0hIN1dEeXJ1VEF0MDVaT1JPZU5IdWxadE1uUExRWWlXeEtNRWl0SjcKOE15ajZmQzQ1SWVEOXpoSncwVlYvNFhDL245SWRjVGRFUm9kZGhCM0FvR0FWVFI4ZHBnMU80YzIzZzE5R2p6NgpjajQxbEkwWmZhMU5kcGNBdksyQjJSSFVPVlg1S3FHOVlkQkhVNFJuZmgybHFXTTkwYzM2TTZ4VGxBZkdxL1lQCnFydGhjZnp2Tk9sSkROaHFCalRzK3NxWjhSek1WelVNMkF4SjJvOW9KNUE4Y3lnemx1Y01YK2d4RXRielZ6UGIKaXBMS3IxTC9BT2JFai9ablQyOVEwc2NDZ1lBQkRPVG5DeEhOY1NVdUZYSEFJTW1RZWN5eEp4bk1qYXVqbCtPSwphdVZhdlp4Skd4bzZORWQ1V2xFLzA1eDZMU1BDMkRaR3FVdFgyU29EWG9yZk02Y29uK3J0Ymw4WVdhWnVzOW8yCklpUGxYek16TmRZZkR3NnJWaXZNZTNZUWliQmIrcEdsQ3Z1dE85b2FoLysraVBEOWxjTWh1UlNCVExqU1Ayd1gKQkJDL09RS0JnUUN0N2EyOS9Yd21SSFJsRHgvb3k3UzRhcUdWZm0rVWRRMy9jc1VVS3BPcDZPY0xtcE9Wb3FzeQpGQjJncWZqVTRrTVJ6QmlQbEFRdkp4QkRwa2ZEZU84WEp6b2l3ekh3bFdOSVdBdFl0ZzhFaDZSM1YzekNvVHBSCjA4b2tJZFVkVkxSNjRhU1NHWDZ6TkdqSStyYkN6YVlxVUhwTjlOZWllUzR4Vkp4NXNZSFRVZz09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
...
```

Both options are working properly right now in the MongoDB chart. I can not reproduce any issue using TLS.

I hope that I helped you, let me know if I can help you with something else.

Álvaro
