### ISSUE TITLE
[bitnami/cassandra] Multinode Cassandra 20x slower than Singlenode MSSQL

### ISSUE THREAD

**Issue by turowicz** [bitnami/charts#6086]
We gather sensor data in a centralised database. It is a write-heavy NoSQL workflow. Our data model is key-value with partitioning, meaning that Cassandra is much suited to our scenarios than MSSQL. It's because we have originally built our system on Azure Table Storage but have since moved it to on-premise, using MS SQL. Now that we have realised that we should drop MSSQL and use Cassandra instead, we have migrated our software and deployed the database with the following variables:

```
replicaCount: 2
cluster:
  endpointSnitch: GossipingPropertyFileSnitch
image:
  tag: 3.11.10-debian-10-r23
dbUser:
  user: (redacted)
  forcePassword: true
  password: (redacted)
persistence:
  size: 20Gi
  enabled: true
  storageClass: microk8s-hostpath
metrics:
  serviceMonitor:
    enabled: true
    interval: 15s
resources:
  limits:
    cpu: 2
    memory: 12Gi
  requests:
    cpu: 2
    memory: 4Gi
```

Unfortunately in our tests the system running on the above Cassandra is 10x-20x slower than the MSSQL instance. Could anyone explain why that is? The MSSQL in question had 1 cores and 6Gi memory.
