### ISSUE TITLE
[bitnami/wordpress] Wordpress app crashes on AKS cluster with AzureFile storage

### ISSUE THREAD

**Issue by MamataTayade** [bitnami/charts#6114]
**Env:**
Cluster: AKS v1.18.14
StorageClass: csi-azurefile-premium-lrs-im (Premium_LRS, Immediate BindingType)

**Steps to reproduce the issue:**
```
1. kubectl create ns wordpress
2. helm repo add bitnami https://charts.bitnami.com/bitnami
3. helm repo update
4. helm install wp bitnami/wordpress --namespace wordpress --set persistence.storageClass=csi-azurefile-premium-lrs-im --set mariadb.primary.persistence.storageClass=csi-azurefile-premium-lrs-im
5. Observe the app status after some time:
    kubectl --namespace wordpress get pods
```

For a WordPress-MariaDB app deployed with AzureFile storage, the pods went into the **CrashLoopBackOff** state.
```
#  kubectl --namespace mt-wordpress get all,pvc
NAME                               READY   STATUS             RESTARTS   AGE
pod/wp-mariadb-0                   0/1     CrashLoopBackOff   7          27m
pod/wp-wordpress-5886cf57c-4fsnw   0/1     CrashLoopBackOff   8          27m

NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)                      AGE
service/wp-mariadb     ClusterIP      10.0.136.162   <none>         3306/TCP                     27m
service/wp-wordpress   LoadBalancer   10.0.244.118   20.88.224.48   80:30453/TCP,443:31889/TCP   27m

NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/wp-wordpress   0/1     1            0           27m

NAME                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/wp-wordpress-5886cf57c   1         1         0       27m

NAME                          READY   AGE
statefulset.apps/wp-mariadb   0/1     27m

NAME                                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                   AGE
persistentvolumeclaim/data-wp-mariadb-0   Bound    pvc-eb044e8a-888b-47b8-9b84-ade590af88d3   20Gi       RWO            csi-azurefile-premium-lrs-im   50m
persistentvolumeclaim/wp-wordpress        Bound    pvc-24850ca4-b20f-4c9f-8b56-1f339d1c1df6   10Gi       RWO            csi-azurefile-premium-lrs-im   27m
```

**Logs of WordPress pod:**
```
WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing wordpress
wordpre INFO  ==> Preparing Varnish environment
wordpre INFO  ==> Preparing Apache environment
wordpre INFO  ==> Preparing PHP environment
mysql-c INFO  Trying to connect to MySQL server
```

**Logs of MariaDB pod:**
```
mariadb 07:05:45.54 INFO  ==> ** Starting MariaDB setup **
mariadb 07:05:45.56 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 07:05:45.56 INFO  ==> Initializing mariadb database
mariadb 07:05:45.58 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mariadb 07:05:45.59 INFO  ==> Using persisted data
mariadb 07:05:45.61 INFO  ==> Running mysql_upgrade
mariadb 07:05:45.62 INFO  ==> Starting mariadb in background
/opt/bitnami/scripts/libos.sh: line 252:    46 Aborted                 (core dumped) "$@" > /dev/null 2>&1
```

Dry-run yaml of the WordPress app:
[bitnami-wordpress-azurefile-dry-run.txt](https://github.com/bitnami/charts/files/6316270/bitnami-wordpress-azurefile-dry-run.txt)

**Comment by Mauraza** [comment]
Hi @MamataTayade,

I have not been able to reproduce it, could I change the value of `BITNAMI_DEBUG` to `true` in the `statefulset.yaml` and copy the logs from MariaDB?

**Comment by MamataTayade** [comment]
Hi @Mauraza 
As per your suggestion, set BITNAMI_DEBUG to "true" in the StateFul set.
```
  containers:
  - env:
    - name: BITNAMI_DEBUG
      value: "yes"
    - name: MARIADB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mariadb-root-password
          name: wp-mariadb
```

It is strangely printing char 'y' continuously.
```
# kubectl -n mt-wordpress logs pod/wp-mariadb-0
y
y
y
y
y
y
y
y
y
y
y
y
y
...
```

**Comment by Mauraza** [comment]
Hi @MamataTayade,

Could you try with this ⬇️ ?

```yaml
          env:
            - name: BITNAMI_DEBUG
              value: "true"
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-mariadb
                  key: mariadb-root-password
            - name: MARIADB_USER
```
