### ISSUE TITLE
Sentinel doesn't connect to redis container in Kubernetes IPv6 environment

### ISSUE THREAD

**Issue by davidegagliardi** [bitnami/charts#6116]
Redis chart 6.0

**Describe the bug**
I deployed Redis via helm installation over my infrastructure (Master-Slave with Sentinel). Redis master is correctly communicating with the slaves and replicating the db. Sentinel fails in connecting to redis in the same pod (works only with IPv4)

I added bind :: to configmap in values.yaml in order to connect from a client to sentinel via IPv6

Checking with `sentinel masters` the status of master in the same pod  is `10) "s_down, master, disconnected"`

**To Reproduce**
Default config from [values.yaml](https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml) enabling cluster and sentinel

**Expected behavior**
Sentinel gets information from redis and starts failover when pod is not working

**Version of Helm and Kubernetes**:

- Output of `helm version`: v3.4.0

- Output of `kubectl version`: Client 1.20.4, Server 1.20.4

**Comment by alvneiayu** [comment]
hi @davidegagliardi 

Could you share with me the logs, please?

Thanks

Álvaro

**Comment by davidegagliardi** [comment]
Here redis log from master node:
```
 11:59:22.34 INFO  ==> my-release-redis-headless.default.svc.cluster.local has my IP: fd00:aaaa:94:ffff:586:9369:22c6:384a
I am master
redis 11:59:22.37 INFO  ==> ** Starting Redis **
1:C 20 Apr 2021 11:59:22.393 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 20 Apr 2021 11:59:22.393 # Redis version=6.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 20 Apr 2021 11:59:22.393 # Configuration loaded
1:M 20 Apr 2021 11:59:22.395 * Running mode=standalone, port=6380.
1:M 20 Apr 2021 11:59:22.395 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 20 Apr 2021 11:59:22.395 # Server initialized
1:M 20 Apr 2021 11:59:22.395 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled (set to 'madvise' or 'never').
1:M 20 Apr 2021 11:59:22.395 * Ready to accept connections
1:M 20 Apr 2021 11:59:57.380 * Replica [fd00:aaaa:94:ffff:cbb1:7abd:7bb7:65ff]:6380 asks for synchronization
1:M 20 Apr 2021 11:59:57.380 * Full resync requested by replica [fd00:aaaa:94:ffff:cbb1:7abd:7bb7:65ff]:6380
1:M 20 Apr 2021 11:59:57.381 * Replication backlog created, my new replication IDs are 'e9493bc524c648e7f74d95863723e25561dfae66' and '0000000000000000000000000000000000000000'
1:M 20 Apr 2021 11:59:57.381 * Starting BGSAVE for SYNC with target: disk
1:M 20 Apr 2021 11:59:57.381 * Background saving started by pid 64
64:C 20 Apr 2021 11:59:57.388 * DB saved on disk
64:C 20 Apr 2021 11:59:57.389 * RDB: 0 MB of memory used by copy-on-write
1:M 20 Apr 2021 11:59:57.485 * Background saving terminated with success
1:M 20 Apr 2021 11:59:57.486 * Synchronization with replica [fd00:aaaa:94:ffff:cbb1:7abd:7bb7:65ff]:6380 succeeded
1:M 20 Apr 2021 12:00:27.834 * Replica [fd00:aaaa:94:ffff:bfc6:b65b:1c9f:8426]:6380 asks for synchronization
1:M 20 Apr 2021 12:00:27.834 * Full resync requested by replica [fd00:aaaa:94:ffff:bfc6:b65b:1c9f:8426]:6380
1:M 20 Apr 2021 12:00:27.834 * Starting BGSAVE for SYNC with target: disk
1:M 20 Apr 2021 12:00:27.834 * Background saving started by pid 114
114:C 20 Apr 2021 12:00:27.841 * DB saved on disk
114:C 20 Apr 2021 12:00:27.841 * RDB: 0 MB of memory used by copy-on-write
1:M 20 Apr 2021 12:00:27.906 * Background saving terminated with success
1:M 20 Apr 2021 12:00:27.906 * Synchronization with replica [fd00:aaaa:94:ffff:bfc6:b65b:1c9f:8426]:6380 succeeded
```

And here log from sentinel master node:
```
 11:59:22.56 INFO  ==> my-release-redis-headless.default.svc.cluster.local has my IP: fd00:aaaa:94:ffff:586:9369:22c6:384a
 11:59:22.57 INFO  ==> Sentinels clean up done
1:X 20 Apr 2021 11:59:22.595 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:X 20 Apr 2021 11:59:22.595 # Redis version=6.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
1:X 20 Apr 2021 11:59:22.595 # Configuration loaded
1:X 20 Apr 2021 11:59:22.596 * Running mode=sentinel, port=6381.
1:X 20 Apr 2021 11:59:22.596 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:X 20 Apr 2021 11:59:22.598 # Sentinel ID is 245d8f7a469900cc58132d536ced94101aa70c6b
1:X 20 Apr 2021 11:59:22.598 # +monitor master mymaster fd00:aaaa:94:ffff:586:9369:22c6:384a 6380 quorum 2
1:X 20 Apr 2021 11:59:42.629 # +sdown master mymaster fd00:aaaa:94:ffff:586:9369:22c6:384a 6380
1:X 20 Apr 2021 11:59:52.577 # +reset-master master mymaster fd00:aaaa:94:ffff:586:9369:22c6:384a 6380
1:X 20 Apr 2021 12:00:12.661 # +sdown master mymaster fd00:aaaa:94:ffff:586:9369:22c6:384a 6380
1:X 20 Apr 2021 12:00:28.839 # +reset-master master mymaster fd00:aaaa:94:ffff:586:9369:22c6:384a 6380
1:X 20 Apr 2021 12:00:48.889 # +sdown master mymaster fd00:aaaa:94:ffff:586:9369:22c6:384a 6380
```
Redis is correctly creating replicas with the slaves, whereas sentinel doesn't communicate with the master.

**Comment by alvneiayu** [comment]
hi @davidegagliardi 

I am trying to reproduce the issue. I will come back with some feedback soon.

Thanks for your time

Álvaro

**Comment by alvneiayu** [comment]
hi @davidegagliardi 

I am not expert in Redis with IPV6. I am trying to set up the bind but I am not having good results. Could you share with me your values, please?

```
helm get values [RELEASE-NAME]
```

Thank you very much.

Álvaro

**Comment by davidegagliardi** [comment]
```
USER-SUPPLIED VALUES:
cluster:
  enabled: true
  slaveCount: 2
clusterDomain: cluster.local
configmap: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""
containerSecurityContext:
  enabled: true
  runAsUser: 1001
global:
  redis: {}
image:
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: bitnami/redis
  tag: 6.0.12-debian-10-r33
master:
  affinity: {}
  command: /run.sh
  configmap: null
  customLivenessProbe: {}
  customReadinessProbe: {}
  disableCommands:
  - FLUSHDB
  - FLUSHALL
  extraEnvVars: []
  extraEnvVarsCM: []
  extraEnvVarsSecret: []
  extraFlags: []
  hostAliases: []
  livenessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
  persistence:
    accessModes:
    - ReadWriteOnce
    enabled: true
    matchExpressions: {}
    matchLabels: {}
    path: /data
    size: 8Gi
    subPath: ""
    volumes: null
  podAnnotations: {}
  podLabels: {}
  preExecCmds: ""
  priorityClassName: null
  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1
  service:
    annotations: {}
    externalTrafficPolicy: Cluster
    labels: {}
    loadBalancerIP: null
    port: 6379
    type: ClusterIP
  shareProcessNamespace: false
  statefulset:
    annotations: {}
    labels: {}
    updateStrategy: RollingUpdate
    volumeClaimTemplates:
      annotations: {}
      labels: {}
metrics:
  enabled: false
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: bitnami/redis-exporter
    tag: 1.20.0-debian-10-r12
  podAnnotations:
    prometheus.io/port: "9121"
    prometheus.io/scrape: "true"
  priorityClassName: null
  prometheusRule:
    additionalLabels: {}
    enabled: false
    namespace: ""
    rules: []
  redisTargetHost: localhost
  service:
    annotations: {}
    externalTrafficPolicy: Cluster
    labels: {}
    type: ClusterIP
  serviceMonitor:
    enabled: false
    metricRelabelings: []
    relabelings: []
    selector:
      prometheus: kube-prometheus
networkPolicy:
  allowExternal: true
  enabled: false
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
password: ""
persistence:
  existingClaim: null
podDisruptionBudget:
  enabled: false
  minAvailable: 1
podSecurityPolicy:
  create: false
rbac:
  create: false
  role:
    rules: []
redisPort: 6379
securityContext:
  enabled: true
  fsGroup: 1001
sentinel:
  cleanDelaySeconds: 5
  configmap: null
  customLivenessProbe: {}
  customReadinessProbe: {}
  downAfterMilliseconds: 20000
  enabled: true
  extraEnvVars: []
  extraEnvVarsCM: []
  extraEnvVarsSecret: []
  failoverTimeout: 18000
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: bitnami/redis-sentinel
    tag: 6.0.12-debian-10-r24
  initialCheckTimeout: 5
  livenessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
  masterSet: mymaster
  metrics:
    enabled: false
    image:
      pullPolicy: IfNotPresent
      registry: docker.io
      repository: bitnami/redis-sentinel-exporter
      tag: 1.7.1-debian-10-r105
    resources:
      limits: {}
      requests: {}
    service:
      annotations: {}
      externalTrafficPolicy: Cluster
      labels: {}
      port: 9355
      type: ClusterIP
    serviceMonitor:
      enabled: false
      selector:
        prometheus: kube-prometheus
  parallelSyncs: 1
  port: 26379
  preExecCmds: ""
  quorum: 2
  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1
  service:
    annotations: {}
    externalTrafficPolicy: Cluster
    labels: {}
    loadBalancerIP: null
    redisPort: 6379
    sentinelPort: 26379
    type: ClusterIP
  staticID: false
  usePassword: false
serviceAccount:
  create: false
  name: null
slave:
  affinity: {}
  command: /run.sh
  configmap: null
  customLivenessProbe: {}
  customReadinessProbe: {}
  disableCommands:
  - FLUSHDB
  - FLUSHALL
  extraEnvVars: []
  extraEnvVarsCM: []
  extraEnvVarsSecret: []
  extraFlags: []
  hostAliases: []
  livenessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  persistence:
    accessModes:
    - ReadWriteOnce
    enabled: true
    matchExpressions: {}
    matchLabels: {}
    path: /data
    size: 8Gi
    subPath: ""
  podAnnotations: {}
  podLabels: {}
  port: 6379
  preExecCmds: ""
  priorityClassName: null
  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 10
  service:
    annotations: {}
    externalTrafficPolicy: Cluster
    labels: {}
    loadBalancerIP: null
    port: 6379
    type: ClusterIP
  shareProcessNamespace: false
  spreadConstraints: {}
  statefulset:
    annotations: {}
    labels: {}
    updateStrategy: RollingUpdate
    volumeClaimTemplates:
      annotations: {}
      labels: {}
sysctlImage:
  command: []
  enabled: false
  mountHostSys: false
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: bitnami/bitnami-shell
  resources: {}
  tag: "10"
tls:
  authClients: true
  certCAFilename: null
  certFilename: null
  certKeyFilename: null
  certificatesSecret: null
  enabled: false
usePassword: false
usePasswordFile: false
volumePermissions:
  enabled: false
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: "10"
  resources: {}
  securityContext:
    runAsUser: 0

    updateStrategy: RollingUpdate
    volumeClaimTemplates:
      annotations: {}
      labels: {}
sysctlImage:
  command: []
  enabled: false
  mountHostSys: false
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: bitnami/bitnami-shell
  resources: {}
  tag: "10"
tls:
  authClients: true
  certCAFilename: null
  certFilename: null
  certKeyFilename: null
  certificatesSecret: null
  enabled: false
usePassword: false
usePasswordFile: false
volumePermissions:
  enabled: false
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: "10"
  resources: {}
  securityContext:
    runAsUser: 0

    matchExpressions: {}
    matchLabels: {}
    path: /data
    size: 8Gi
    subPath: ""
  podAnnotations: {}
  podLabels: {}
  port: 6379
  preExecCmds: ""
  priorityClassName: null
  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 10
  service:
    annotations: {}
    externalTrafficPolicy: Cluster
    labels: {}
    loadBalancerIP: null
    port: 6379
    type: ClusterIP
  shareProcessNamespace: false
  spreadConstraints: {}
  statefulset:
    annotations: {}
    labels: {}
    updateStrategy: RollingUpdate
    volumeClaimTemplates:
      annotations: {}
      labels: {}
sysctlImage:
  command: []
  enabled: false
  mountHostSys: false
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: bitnami/bitnami-shell
  resources: {}
  tag: "10"
tls:
  authClients: true
  certCAFilename: null
  certFilename: null
  certKeyFilename: null
  certificatesSecret: null
  enabled: false
usePassword: false
usePasswordFile: false
volumePermissions:
  enabled: false
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: "10"
  resources: {}
  securityContext:
    runAsUser: 0
```
