### ISSUE TITLE
Redis using predefined PV and PVC failing to start with error in init container

### ISSUE THREAD

**Issue by zaf187** [bitnami/charts#6126]
**Which chart**:
bitnami/redis 
redis-13.0.1
6.2.1

**Describe the bug**
When I create the helm chart with the some custom configurations the init container fails to come up. I see an error in the logs;
`chown: changing ownership of '/data': Operation not permitted`

**To Reproduce**
I am using my own PV and PVC which i have created in my cluster / namespace already. The PV points to an nfs hostpath on a server. The path on that server has 777 permissions on the folder and owner:group set to root:root.

Here is the custom values.yaml i am using;
```
cluster:
  enabled: false
usePassword: false
persistence:
  existingClaim: redis-pvc
  enabled: true
volumePermissions:
  enabled: true
```
deploying the helm chart with this command
`helm install redis-custom -f ./values.yaml bitnami/redis -n my-space`

Then when you check the logs for the pod, it says init failed with the following message logged in the init container;
`chown: changing ownership of '/data': Operation not permitted`

**Expected behavior**
Redis should be running with a single master node

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

This definitely looks like an issue with the PVC technology that you are using. Could you provide more details about it ? Which is your Kubernetes cluster?

**Comment by zaf187** [comment]
I am running an on premise kubernetes cluster, what would you like to know?

**Comment by javsalgar** [comment]
How are you setting up PVCs?I imagine that you had to deploy some sort of provider.

**Comment by zaf187** [comment]
Here's my PV yaml;
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    app: redis-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs/home/redis-data
    readOnly: false
    server: host.name.com
```

This is my PVC yaml;
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: redis-data
```

Is this what you were looking for? do you suspect it has something to do with the `storageClassName`?
