### ISSUE TITLE
[bitnami/redis-cluster] Cluster has no zero downtime when one of masters was killed

### ISSUE THREAD

**Issue by lapinosore** [bitnami/charts#6156]
**Which chart**:
bitnami/redis-cluster   5.0.0

**Describe the bug**
When i kill one of master nodes, service says me: "cluster is down" for 1-2 sec.

**Expected behavior**
When one of masters has down, there is no downtime.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"4d62230f10af41cec2851b5b113874f6d2098297", GitTreeState:"clean", BuildDate:"2021-03-22T23:01:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
redis-values.yml:
```
redis:
  resources:
    requests:
      memory: "50M"
    limits:
      memory: "200M"
## Prometheus Exporter / Metrics
##
metrics:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/redis-exporter
    tag: 1.20.0-debian-10-r1
    pullPolicy: IfNotPresent
  ## Metrics exporter pod Annotation and Labels
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
```

.NET Client connection config:
```
var redisConfig = new ConfigurationOptions()
            {
                EndPoints = {{dbSettings.Host, dbSettings.Port}}, //Service in k8s cluster
                AllowAdmin = true,
                ClientName = "QueueService",
                ReconnectRetryPolicy = new LinearRetry(5000),
                AbortOnConnectFail = false,
            };
```

**Comment by lapinosore** [comment]
Also trying that settings:
```
cluster:
  nodes: 9
  replicas: 2
```
And it's create 3 master and 6 slaves. Doesnt solve.

**Comment by rafariossaa** [comment]
Hi,
  As you are using the SVC in kubernetes, have you tried to decrease the liveness time ?
  Kubernetes needs some time to realize that one of the pods has died and remove it from the loadbalancer (service), and this will take some time.

**Comment by lapinosore** [comment]
Tryin with demo client pod, have no error when i kill one of masters pod.
```
redis-cli -c -h queue-redis-redis-cluster -a "" SMEMBERS users
```
But with StackExchange lib i get error.
I think i doing wrong in connection algorythm.
```
 var redisConfig = new ConfigurationOptions()
            {
                EndPoints = {{dbSettings.Host, dbSettings.Port}}, // k8s SVC
                AllowAdmin = true,
                ClientName = "QueueService",
                ReconnectRetryPolicy = new LinearRetry(5000),
                AbortOnConnectFail = false,
            };
            if (!string.IsNullOrEmpty(dbSettings.Password))
                redisConfig.Password = dbSettings.Password;

            //SERVICES
            services.AddScoped(x => ConnectionMultiplexer.Connect(redisConfig).GetDatabase());
```

**Comment by lapinosore** [comment]
What time i should decrease?
```
redis:
  livenessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5
```
Period seconds?
