### ISSUE TITLE
requirements.txt not taken into account

### ISSUE THREAD

**Issue by pgrandjean** [bitnami/charts#6190]
**Which chart**
source:
repoURL: 'https://charts.bitnami.com/bitnami'
targetRevision: 9.0.5

**Describe the bug**

I am mounting some extra volumes in order to install additional airflow providers, but modules are not installed. The extra volumes:

```yaml
worker:
  extraVolumes:
  - name: requirements
    emptyDir: {}

  extraVolumeMounts:
  - name: requirements
    mountPath: /bitnami/python/requirements.txt
    subPath: requirements.txt
```

There is documentation referencing some code [here](https://github.com/bitnami/bitnami-docker-airflow/blob/cafc8eab1efddb5efda5a00cc861ef10f35f1d49/1/debian-10/rootfs/run.sh#L14), but it looks like this code has disappeared in the latest version 9.0.5. If this has changed, how to specify additional modules to be installed now?
