### ISSUE TITLE
[Bitnami/Wordpress] coalesce.go:160: warning: skipped value for tolerations: Not a table.

### ISSUE THREAD

**Issue by corend** [bitnami/charts#6237]
**Which chart**:
Wordpress

**Describe the bug**
coalesce.go:160: warning: skipped value for tolerations: Not a table.

**To Reproduce**
- configure a Yaml file for Wordpress and execute it, first output is this warning message (not blocking): coalesce.go:160: warning: skipped value for tolerations: Not a table.

```YAML
service:
  type: ClusterIP
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
    nginx.ingress.kubernetes.io/client-max-body-size: 200m
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
  certManager: true
  enabled: true
  #to be updated with the correct URL of the website
  hostname: hiddendata.for.here
  secrets: []
  tls: true
mariadb:
  enabled: false
externalDatabase:
  host: IP
  port: PORT
  database: DATABASE
  user: USER
  password: PASSWORD
resources:
  requests:
    memory: 512Mi
    cpu: 300m
pdb:
  create: true
  minAvailable: 1
replicaCount: 1
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
persistence:
  enabled: true
  storageClass: NFS
  accessModes:
    - ReadWriteMany
  size: 10Gi
initContainers:
  - name: volume-permissions
    image: bitnami/minideb
    imagePullPolicy: Always
    command: ['sh', '-c', 'chown 1001:1001 /bitnami/wordpress']
    volumeMounts:
    - mountPath: /bitnami/wordpress
      name: wordpress-data
      subPath: wordpress
nodeSelector:
  env: SELECTOR
allowEmptyPassword: false
extraVolumeMounts:
  - name: php-ini
    mountPath: /opt/bitnami/php/etc/conf.d
extraVolumes:
  - name: php-ini
    configMap:
      name: php-ini
customPostInitScripts:
  wp_memory_limit.sh: |
    sed -i "/.*That's all, stop editing! Happy publishing.*/i define('WP_MEMORY_LIMIT', '512M');" /opt/bitnami/wordpress/wp-config.php
wordpressConfigureCache: true
memcached:
  enabled: true
  service:
    port: PORTMEMCACHED
```

**Expected behavior**
No warning and a clear error explained when it is needed to identify the root cause and fix it without asking help on GitHub.

**Kubernetes Version**
v1.20.4

- Output of `kubectl version`:

```
Client Version:"v1.20.2" - Server Version:"v1.20.4"
```

- Output of `helm version`:

```
Version:"v3.5.4"
```
