### ISSUE TITLE
[bitnami/mongodb] pods fail when change configuration options

### ISSUE THREAD

**Issue by Mutantt** [bitnami/charts#6277]
**Which chart**:
mongodb/10.11.2

**Describe the bug**
i have no problem when running the chart with default values,it worked without any issue,but when i exec into the one of the pods and copy its /opt/bitnami/mongodb/confmongodb.conf contents and use it in configuration section in the values.yaml file for another deploying it doesnt work,i receive "ERROR: child process failed, exited with 1" and pod goes to crashloopbackoff state.

**To Reproduce**
1- deploy the chart with default value(i didnt use arbiter)
2- exec into one of the pods and copy contents of /opt/bitnami/mongodb/conf/mongodb.conf 
3- paste that contents in the configuration: |- section in values.yaml
4-deploy it again in another namespace or with different name 

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:18:22Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
i wanted to add some extraconfig in configuration section but i faced with this problem,so i decided to try with default configuration which bitnami mongodb had when was up but the problem persisted, so what did i miss?

**Comment by juan131** [comment]
Hi @Mutantt 

I was unable to reproduce the issue following the steps below:

- Install MongoDB and the generated `mongodb.conf`:

```console
$ helm install mongodb bitnami/mongodb
$ kubectl cp $(kubectl get pods -l app.kubernetes.io/instance=mongodb -o jsonpath='{.items[0].metadata.name}'):/opt/bitnami/mongodb/conf/mongodb.conf /tmp/mongodb.conf
```

- Create a **values.yaml** including the `mongodb.conf`:

```yaml
configuration: |-
  # where and how to store data.
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
  # where to write logging data
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0
  # network interfaces
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    bindIpAll: true
  # process management options
  processManagement:
    fork: false
    pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
  # set parameter options
  setParameter:
    enableLocalhostAuthBypass: false
  # security options
  security:
    authorization: enabled
podAffinityPreset: hard
podAntiAffinityPreset: ""
```

- Upgrade MongoDB release using the **values.yaml**:

```console
$ export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace "default" mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)
$ helm upgrade mongodb bitnami/mongodb --set auth.rootPassword=$MONGODB_ROOT_PASSWORD -f values.yaml
```

**Comment by Mutantt** [comment]
Hi @juan131 
i checked your way to upgrade configuration and it worked without any issue.after that i decided to check clean install,i used helm delete to delete mongo and also i deleted corresponding pvc and installed the chart with values file including generated mongodb.conf content in configuration but i faced the same issue again. would you please advise?

here is my values file:
---

  global:
      image:
        repository: bitnami/mongodb
        tag: 4.4.4-debian-10-r41
        # debug: true
      # systemLogVerbosity: 5
      architecture: replicaset
      auth:
        enabled: true
        existingSecret: mongodb-credentials
      directoryPerDB: true
      replicaCount: 3
      arbiter:
        enabled: false
      resources:
        limits:
          cpu: 2
          memory: 8192Mi
        requests:
          cpu: 1
          memory: 4096Mi
      persistence:
        size: 8Gi
      configuration: |-
        storage:
          dbPath: /bitnami/mongodb/data/db
          journal:
            enabled: true
          directoryPerDB: true
        # where to write logging data.
        systemLog:
          destination: file
          quiet: false
          logAppend: true
          logRotate: reopen
          path: /opt/bitnami/mongodb/logs/mongodb.log
          verbosity: 0
        # network interfaces
        net:
          port: 27017
          unixDomainSocket:
            enabled: true
            pathPrefix: /opt/bitnami/mongodb/tmp
          ipv6: false
          bindIpAll: true
          #bindIp:
        # replica set options
        replication:
          replSetName: rs0
          enableMajorityReadConcern: true
        # sharding options
        #sharding:
          #clusterRole:
        # process management options
        processManagement:
           fork: false
           pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
        # set parameter options
        setParameter:
           enableLocalhostAuthBypass: false
        # security options
        security:
          authorization: enabled
          keyFile: /opt/bitnami/mongodb/conf/keyfile
      metrics:
        enabled: true
        image:
          repository: bitnami/mongodb-exporter
          tag: 0.11.2-debian-10-r114
        resources:
          limits:
            cpu: 1
            memory: 1024Mi
          requests:
            cpu: 250m
            memory: 256Mi
        serviceMonitor:
          enabled: true
          namespace: monitoring
          additionalLabels:
            app: kube-prometheus-stack-prometheus
            release: prometheus-stack

**Comment by juan131** [comment]
Hi @Mutantt 

Thanks for the details! I can see you're customizing several parameters (e.g. you're using `architecture=replicaset` and you're also enabling metrics).

Let's try to reduce the issue in a "simpler" setup:

1. First, try to reproduce the issue disabling metrics and using `architecture=standalone`.
2. If everything goes well. Try to do the same using `architecture=replicaset` and disabling metrics.
3. If you reproduce the issue in step 2. Please share te logs from both primary and secondary nodes.

**Comment by Mutantt** [comment]
Dear @juan131 thank you for your reply.
I checked "architecture=standalone,metrics: enabled&disabled" / "architecture=replicaset,metrics=enabled&disabled" and the result was the same: here is the logs of primary pod as the secondary pods didn't appear after the master issue:

---
mongodb 09:28:54.43 
mongodb 09:28:54.46 Welcome to the Bitnami mongodb container
mongodb 09:28:54.48 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 09:28:54.51 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 09:28:54.52 
mongodb 09:28:54.54 INFO  ==> ** Starting MongoDB setup **
mongodb 09:28:54.61 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 09:28:54.78 INFO  ==> Initializing MongoDB...
mongodb 09:28:54.80 DEBUG ==> /mongodb.conf mounted. Skipping setting port and IPv6 settings
mongodb 09:28:54.83 DEBUG ==> /mongodb.conf mounted. Skipping setting log settings
mongodb 09:28:54.84 DEBUG ==> /mongodb.conf mounted. Skipping setting storage settings
mongodb 09:28:54.89 INFO  ==> Deploying MongoDB from scratch...
mongodb 09:28:54.94 DEBUG ==> Starting MongoDB in background...
about to fork child process, waiting until server is ready for connections.
forked process: 36
ERROR: child process failed, exited with 1
To see additional information in this output, start without the "--fork" option.
---

and here is my trimmed values.yaml file content:
```yaml
image:
  repository: bitnami/mongodb
  tag: 4.4.4-debian-10-r41
  debug: true
# systemLogVerbosity: 5
architecture: standalone
auth:
  enabled: true
  existingSecret: mongodb-credentials
directoryPerDB: true
# replicaCount: 3
arbiter:
  enabled: false
resources:
  limits:
    cpu: 2
    memory: 8192Mi
  requests:
    cpu: 1
    memory: 4096Mi
persistence:
  size: 8Gi
configuration: |-
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: true
    wiredTiger:
      engineConfig:
        cacheSizeGB: 3
  # where to write logging data.
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0
  # network interfaces
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    bindIpAll: true
    #bindIp:
  # replica set options
  replication:
    replSetName: rs0
    enableMajorityReadConcern: true
  # sharding options
  #sharding:
    #clusterRole:
  # process management options
  processManagement:
     fork: false
     pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
  # set parameter options
  setParameter:
     enableLocalhostAuthBypass: false
  # security options
  security:
    authorization: enabled
    keyFile: /opt/bitnami/mongodb/conf/keyfile
metrics:
  enabled: false
```
