### ISSUE TITLE
[bitnami/logstash] Can't manually attribute port number for NodePort

### ISSUE THREAD

**Issue by pbrissaud** [bitnami/charts#6278]
**Which chart**:
Logstash 3.3.2

**Is your feature request related to a problem? Please describe.**
I can't manually define node port number in the chart. If I modify `service.type` to **NodePort** and I add a **nodePort** attribute to each port in `service.ports`, I have the following error :
```bash
Error: UPGRADE FAILED: cannot patch "logstash-headless" with kind Service: Service "logstash-headless" is invalid: spec.ports[1].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```

**Describe the solution you'd like**
I will like to have the possibility to manually attribute the nodePort like the official chart does.  

**Describe alternatives you've considered**
If I delete the `templates/headless-svc` file, I can deploy the chart and the node port is well defined

**Additional context**

working values.yaml file if I delete the headless-svc template :
```yaml
service:
  type: NodePort
  ports:
    syslog-tcp:
      port: 1514
      targetPort: syslog-tcp
      protocol: TCP
      nodePort: 31044 
```
