### ISSUE TITLE
[bitnami/thanos] bucketweb now uses different health probe's paths (v0.20.0+)

### ISSUE THREAD

**Issue by lorenzo-biava** [bitnami/charts#6293]
**Which chart**:
Thanos

**Describe the bug**
The probe's paths for bucketweb need be updated when using v0.20.0+

https://github.com/bitnami/charts/blob/master/bitnami/thanos/values.yaml#L988

```yaml
  livenessProbe:
    httpGet:
      path: /-/healthy
  readinessProbe:
    httpGet:
      path: /-/ready
```

**To Reproduce**

1. Install bucketweb v0.20.0
2. The probes will fail
