### ISSUE TITLE
[bitnami/keycloak] Unable to create an ingress without a hostname

### ISSUE THREAD

**Issue by turowicz** [bitnami/charts#6299]
My client requires us to deploy keycloak that is accessible by an IP address, not a DNS name. It is not possible at this stage of cooperation to modify their DNS. Therefore I need to create such ingress rule:

`http://*/svc/identity/(.*) ⇢ identity-keycloak:80`

**Comment by turowicz** [comment]
Looking at the ingress.yaml it seems to be impossbile without modifying it at the moment.

**Comment by turowicz** [comment]
On top of that, the client uses a different IP from his internal network, than the VPN IP we have to access the cluster. Our VPN IP is dynamic so we can't hardcode it in the deployment.

**Comment by turowicz** [comment]
I need to create such ingress:

```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/instance: client
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: client-identity-path
    helm.sh/chart: MegaChart-0.1.0
  annotations:
    meta.helm.sh/release-name: client
    meta.helm.sh/release-namespace: default
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /svc/identity/(.*)
            pathType: Prefix
            backend:
              service:
                name: client-identity
                port:
                  number: 80
```

**Comment by carrodher** [comment]
Thanks, the PR was merged, feel free to reopen the issue if something is not working as expected. Please, take into account the release of the chart can be delayed once merged the code in GitHub

**Comment by turowicz** [comment]
@carrodher the change is not yet available in chart repo. Can I get any information on the status of the CI/CD rollout?

**Comment by turowicz** [comment]
@marcosbc thank you!

**Comment by marcosbc** [comment]
BTW it seems like it was released now, let us know if you continue finding issues

**Comment by turowicz** [comment]
Thank you so much

**Comment by turowicz** [comment]
The ingress now also works by path and no hostname!

Unfortunately keycloak doesn't infer the address properly, it excludes the path. I will have to try and fix it now in the configuration.

**Comment by turowicz** [comment]
OK I've managed it with the following:

```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/rewrite-target: /auth/$1
spec:
  rules:
    - http:
        paths:
          - path: /auth/(.*)
            pathType: Prefix
            backend:
              service:
                name: client-identity
                port:
                  number: 80

```
