### ISSUE TITLE
[bitnami/wordpress] Values from values file not picked up

### ISSUE THREAD

**Issue by AdnanHodzic** [bitnami/charts#6305]
**Which chart**:
wordpress-10.11.2

**Describe the bug**

When installing the chart values are not picked up from values.yaml file, but are picked up using `--set`

**To Reproduce**

Installing this chart using:

```console
helm install wordpress bitnami/wordpress \
  --set wordpressUsername=redacted \
  --set wordpressPassword=redacted\
  --set ingress.enabled=true \
  --set service.type=ClusterIP \
  --set ingress.enabled=true \
  --set ingress.certManager=true \
  --set mariadb.enabled=false \
  --set externalDatabase.host=redacted \
  --set externalDatabase.port=redacted \
  --set externalDatabase.database=redacted \
  --set externalDatabase.user=redacted \
  --set externalDatabase.password=redacted \
  --set mariadb.auth.database=redacted \
  --set mariadb.auth.rootPassword=redacted
```

works great and WordPress will work as expected. However, if I install it by running:

```console
helm install wordpress bitnami/wordpress -f prod-values.yaml 
```

prod-values.yaml contents:
```yml
# wordpress
wordpressUsername: redacted
wordpressPassword: redacted
# ingress/tls
ingress.enabled: true
service.type: ClusterIP
ingress.enabled: true
ingress.certManager: true
# mariadb
mariadb.enabled: false
externalDatabase.host: redacted
externalDatabase.port: redacted
externalDatabase.database: redacted
externalDatabase.user: redacted
externalDatabase.password: redacted
mariadb.auth.database: redacted                                                                                                                  
mariadb.auth.rootPassword: redacted
# wordpress additional config
wordpressExtraConfigContent: |
  @ini_set( 'post_max_size', '128M');
  @ini_set( 'memory_limit', '256M' );
  @ini_set( 'max_execution_time', '300' );
  @ini_set( 'max_input_time', '300' );
  define( 'WP_MEMORY_LIMIT', '512M' );
```

nothing under `#mariadb` will be picked up and chart will install MariaDB instead of relying on external database setup.

**Expected behavior**

I expect values in `prod-values.yaml` to be picked up as they are when using `--set`.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-16T18:16:59Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-gke.1600", GitCommit:"4f6f69fd81ca8cb6962a2f7e1ed9c7880834cf71", GitTreeState:"clean", BuildDate:"2021-03-08T19:22:13Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```

**Comment by Mauraza** [comment]
Hi @AdnanHodzic,

Could you try with these values.yaml?
```yml
# wordpress
wordpressUsername: redacted
wordpressPassword: redacted
# ingress/tls
ingress:
  enabled: true
  certManager: true
service.type: ClusterIP

# mariadb
mariadb:
  enabled: false
  auth:
    database: redacted  
    rootPassword: redacted
externalDatabase:
  host: redacted
  port: redacted
  database: redacted
  user: redacted
  password: redacted
# wordpress additional config
wordpressExtraConfigContent: |
  @ini_set( 'post_max_size', '128M');
  @ini_set( 'memory_limit', '256M' );
  @ini_set( 'max_execution_time', '300' );
  @ini_set( 'max_input_time', '300' );
  define( 'WP_MEMORY_LIMIT', '512M' );

```
