### ISSUE TITLE
[bitnami/redis] allow suffix configuration

### ISSUE THREAD

**Issue by agnaite** [bitnami/charts#6307]
**Which chart**:
* chart: `bitnami/redis`
* verion: `14.1.0`

**Is your feature request related to a problem? Please describe.**
We are trying to avoid the `master`/`slave` terminology, however, the suffix `-master` is always appended to the resources generated. 

**Describe the solution you'd like**
I would like to be able to `--set suffix=redis-leader`.

**Describe alternatives you've considered**
Renaming everything manually. 

**Additional context**
I tried using `--set fullnameOverride=redis-leader`, but it resulted in naming like so:

```yaml
# Source: redis/templates/master/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-leader-master
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-14.1.0
    app.kubernetes.io/instance: logging
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: master
```

Thank you 🙌
