### ISSUE TITLE
External-DNS 5.0.0 breaks Azure Private DNS

### ISSUE THREAD

**Issue by pinkfloydx33** [bitnami/charts#6319]
**Which chart**:
External-DNS

**Describe the bug**
Unable to upgrade to latest chart 5.0.0 (from 4.12.2 which was the previous version). It appears to be new logic within the docker image as reverting from the new `0.8.0-debian-10-r0` tag to the previous `0.7.6-debian-10-r91` works just fine (and using the latest tag on the previous chart exhibits the same failure).

The application is searching for `/etc/kubernetes/azure.json` which by the very logic in the chart cannot exist for Azure Private DNS. The application throws an error and then the helm upgrade aborts.

Despite the fact that the upstream documentation seems to imply that you MUST use the secret versions of `aadClientId`/`aadClientSecret` when using private-dns, that is simply not true. You may use the same exact azure.json file that is used for the azure provider for the azure-private-dns. (I have verified it works just fine by manually editing the deployment and creating the secret manually). 

Of note, I am using managed identity along with pod identity. Once I provide the *manually* created azure.json file, the output of the application says that its using the managed identity. But I can't get this far with the latest updates when using the chart directly.

I don't know how/why it was working without the mapped file in the previous chart version. Originally I suspected that it was the pod-identity label I add to the deployment, however I've removed it and can get the application running without it (both the prior working chart and the manually modified new chart). 

Possible solutions could be: 
- re-ordering the logic when `azure.useManagedIdentityExtension` is `true` 
- an extra option to force the use of the azure.json file (for example: `azure.useAzureJson`). 

Anything would be great so that I don't have to override the `tag` and then never get an update.

**To Reproduce**
Here are the chart values that I am using (with sensitive data redacted):

```yaml
annotationFilter: ""
azure:
  resourceGroup: rg-my-group
  subscriptionId: 00000A00-0A00-000A-000A-0A0AA000000A
  tenantId: 00000A00-0A00-000A-000A-0A0AA000000A
  useManagedIdentityExtension: true
crd:
  create: false
extraArgs:
  ignore-ingress-tls-spec: null
  log-level: $(ExtDnsLogLevel)
extraEnv:
- name: ExtDnsLogLevel
  valueFrom:
    configMapKeyRef:
      key: LogLevel
      name: external-dns-config
- name: EXTERNAL_DNS_DOMAIN_FILTER
  valueFrom:
    configMapKeyRef:
      key: DomainFilter
      name: external-dns-config
interval: 1m
logLevel: ""
nodeSelector:
  kubernetes.io/os: linux
podLabels:
  aadpodidbinding: external-dns
policy: sync
provider: azure-private-dns
replicas: 2
sources:
- ingress
```

**Expected behavior**
Chart should deploy and if all values are provided, use the azure.json version of the secret.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"54684493f8139456e5d2f963b23cb5003c4d8055", GitTreeState:"clean", BuildDate:"2021-03-22T23:02:59Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
