### ISSUE TITLE
[bitnami/jasperreports] Error executing 'postInstallation'

### ISSUE THREAD

**Issue by justin-cha** [bitnami/charts#6333]
jasperreports fails to start with message:
```
Error executing 'postInstallation': Files to substitute resolved to an empty list
```

This occurs using chart version 10.2.6 with values:
```
  jasperreportsUsername: tc-jasper-user
  jasperreportsPassword: <12 char password>
  service:
    type: ClusterIP
    port: 8080
  mariadb:
    auth:
      password: <another 12 char password>
      rootPassword: <and another 12 char password>
```

This has occurred both when deploying in a Minikube cluster and an AWS EKS cluster
