### ISSUE TITLE
[bitnami/common] Node affinity values must be quoted.

### ISSUE THREAD

**Issue by wrossmann** [bitnami/charts#6349]
**Which chart**:
bitnami/common 1.4.3

**Describe the bug**
The affinities template helper does not quote nodeAffinity match rule values, resulting in supplied values being misinterpreted by Kubernetes.

eg:
```
    nodeAffinityPreset:
      type: hard
      key: node-role.company.com/platform-services
      values:
        - "true"
```
results in the following in the rendered template:
```
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.company.com/platform-services
                    operator: In
                    values:
                      - true
```
which results in an error like:
```
v1.NodeSelectorRequirement.Values: []string: ReadString: expects " or n, but found t, error found in #10 byte of ...|values":[true]
```

**To Reproduce**

1. Pick a Bitnami chart of your choice, eg: Redis.
2. Create a values file containing the above `nodeAffinityPreset` block, eg:
```
  master:
    nodeAffinityPreset:
      type: hard
      key: node-role.company.com/platform-services
      values:
        - "true"
```
3. Attempt to install the chart.

**Expected behavior**
The string `"true"` should be quoted in the rendered template, and the chart should install cleanly.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
Nada
