### ISSUE TITLE
DAGs not running using Kubernetes Executor

### ISSUE THREAD

**Issue by Jagadeepkosuri** [bitnami/charts#6362]
**Which chart**:
Airflow. Chart : 8.0.4

**Describe the bug**
I'm trying to use Kubernetes Executor to run my DAGs. Initially faced a error like worker pods stay in Intializing state for long time and suspends. 
Fixed that error after doing below changes to values.yaml file #5569 
```yaml
airflow:
worker:
extraEnvVars:
- name: AIRFLOW_WEBSERVER_HOST
value: "{{ include "common.names.fullname" . }}"
- name: AIRFLOW_WEBSERVER_PORT_NUMBER
value: "{{ .Values.service.port }}"
```

After this if i try to run DAGs, DAGs either go to Failed state or doesn't schedule the next tasks. Only start taks is run and subsequent tasks doesn't get scheduled. 

I tried with latest chart 9.0.5, but still couldn't run DAGs using KubernetesExecutor. Tried lot of ways to debug. Checked if anything is missed in templates/config/config.yaml . Checked if any environment variables or volumeMounts are missing. But couldn't find out why.

I wanted to know if anyone of you guys were able to run your own DAGs with KubernetesExecutor correctly. If yes , please share your values.yaml file. 

I have mounted Azure files to my VM. And using those mounted volumes as local paths and mounting them to all my pods for dags, plugins , logs and passing requirements.txt

**To Reproduce**
Same as above

**Expected behavior**
Suggestion or values.yaml file to run DAGs using KubernetesExecutor
You can give me the changes made in values.yaml where KubernetesExecutor is working well.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
  
```
Helm3
```

- Output of `kubectl version`:

```
Rancher K3s
```

**Additional context**
