### ISSUE TITLE
metrics.prometheusrule.enabled=true not working

### ISSUE THREAD

**Issue by kubealex** [bitnami/charts#6363]
**Which chart**:
mongodb 

**Describe the bug**
Error: YAML parse error on mongodb/templates/prometheusrule.yaml: error converting YAML to JSON: yaml: line 14: could not find expected ':'

**To Reproduce**
helm install mongodb-svc bitnami/mongodb --set architecture="standalone" --set metrics.prometheusRule.enabled=true --set metrics.enabled=true

**Expected behavior**
Create stuff

**Version of Helm and Kubernetes**:
3+, 1.21
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by carrodher** [comment]
It seems you didn't specify the rule, can you take a look at [this section of the README](https://github.com/bitnami/charts/tree/master/bitnami/mongodb#use-custom-prometheus-rules)?

I was able to deploy the chart by running:
```
helm install mongodb-svc bitnami/mongodb -f myvalues.yaml
```
where `myvalues.yaml` is
```yaml
architecture: standalone
metrics:
  enabled: true
  prometheusRule:
    enabled: true
    rules:
    - name: rule1
      rules:
      - alert: HighRequestLatency
        expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High request latency
```
and the prometheusrule.yaml is rendered as the following code block:
```yaml
# Source: mongodb/templates/prometheusrule.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mongodb-svc
  namespace: default
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.15.2
    app.kubernetes.io/instance: mongodb-svc
    app.kubernetes.io/managed-by: Helm
spec:
  groups:
  - name: rule1
    rules:
    - alert: HighRequestLatency
      annotations:
        summary: High request latency
      expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
      for: 10m
      labels:
        severity: page
```
