### ISSUE TITLE
Customize configuration and start security to start error reporting

### ISSUE THREAD

**Issue by lifei825** [bitnami/charts#6366]
**Which chart**:
mongodb-10.15.2.tgz

**Describe the bug**
Customize configuration and start security to start error reporting
error: ERROR: child process failed, exited with 1

**To Reproduce**
values.yaml:
```
configuration: |-
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    bindIpAll: true
  replication:
    replSetName: rs-cmdb
    enableMajorityReadConcern: true
  processManagement:
    fork: false
    pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
  setParameter:
    enableLocalhostAuthBypass: false
  security:
    authorization: enabled
    keyFile: /opt/bitnami/mongodb/conf/keyfile
```

please why，How to solve it，thanks！
