### ISSUE TITLE
[ETCD] A three node cluster fails to recover after a single node is killed. But if two or even all nodes of the cluster die, it recovers. 

### ISSUE THREAD

**Issue by wnke** [bitnami/charts#6372]
**Which chart**:
etcd 6.2.4

**Describe the bug**
A three node cluster fails to recover after a single node is killed. But if two or even all nodes of the cluster die, it recovers. 

**To Reproduce**
1. `kubectl delete pod $POD_NAME` to kill one of the cluster pods

**Expected behavior**
Since there is no lost of quorum, the etcd cluster should recover seamlessly. 

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.17-gke.100", GitCommit:"c702fe983d18291df698149425102b51a8258b71", GitTreeState:"clean", BuildDate:"2021-03-19T09:19:23Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```

**Additional context**
values.yaml:
```
nameOverride: etcd-cluster
image:
  registry: docker.io
  repository: bitnami/etcd
  tag: 3.4.16-debian-10-r0

podManagementPolicy: Parallel
removeMemberOnContainerTermination: true
podAnnotations:
  sidecar.istio.io/inject: "false"

serviceAccount:
  create: true
  name: etcd-cluster

## etcd containers' SecurityContext
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
##
podSecurityContext:
  enabled: true
  fsGroup: 1337

## etcd pods' Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
##
containerSecurityContext:
  enabled: true
  runAsUser: 1337
  runAsNonRoot: true

auth:
  rbac:
    enabled: false
    allowNoneAuthentication: true
autoCompactionRetention: 12
autoCompactionMode: periodic

replicaCount: 3
updateStrategy:
  ## Update strategy type, can be set to RollingUpdate or OnDelete.
  ##
  type: RollingUpdate

containerPorts:
  client: 2379
  peer: 2380

extraEnvVars:
  - name: BITNAMI_DEBUG
    value: "true"

resources:
  ## We usually recommend not to specify default resources and to leave this as a conscious
  ## choice for the user. This also increases chances charts run on environments with little
  ## resources, such as Minikube. If you do want to specify resources, uncomment the following
  ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  ## e.g:
  ## limits:
  ##   cpu: 500m
  ##   memory: 1Gi
  ##
  limits: {}
  requests:
    cpu: 500m
    memory: 1Gi

livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
readinessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
startupProbe:
  enabled: false
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 60

podAntiAffinityPreset: hard

pdb:
  create: true
  ## Min number of pods that must still be available after the eviction
  ##
  minAvailable: 2
  ## Max number of pods that can be unavailable after the eviction
  ##
  maxUnavailable: 0

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  ## If true, use a Persistent Volume Claim. If false, use emptyDir.
  ##
  enabled: true
  ## Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  ## Persistent Volume Claim annotations (evaluated as a template)
  ##
  annotations: {}
  ## Persistent Volume Access Modes
  ##
  accessModes:
    - ReadWriteOnce
  ## Persistent Volume size
  ##
  size: 8Gi
  ## Provide any additional label selector to further filter the set of volumes (evaluated as a template)
  ## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector
  ##
  selector: {}

metrics:
  enabled: true
  ## Annotations for the Prometheus metrics on etcd pods
  ##
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2379"

volumePermissions:
  enabled: true
## Enable auto disaster recovery by periodically snapshotting the keyspace:
## - It creates a cronjob to periodically snapshotting the keyspace
## - It also creates a ReadWriteMany PVC to store the snapshots
## If the cluster permanently loses more than (N-1)/2 members, it tries to
## recover itself from the last available snapshot.
##
disasterRecovery:
  enabled: true
  cronjob:
    ## Schedule in Cron format to save snapshots
    ## See https://en.wikipedia.org/wiki/Cron
    ##
    schedule: "*/30 * * * *"
    ## Number of successful finished jobs to retain
    ##
    historyLimit: 3
    ## Number of etcd snapshots to retain, tagged with date
    ##
    snapshotHistoryLimit: 5
    ## Pod annotations
    ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
    ##
    podAnnotations:
      sidecar.istio.io/inject: "false"
    ## Configure resource requests and limits for snapshotter containers
    ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
    ##
    resources:
      ## We usually recommend not to specify default resources and to leave this as a conscious
      ## choice for the user. This also increases chances charts run on environments with little
      ## resources, such as Minikube. If you do want to specify resources, uncomment the following
      ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      ## e.g:
      ## limits:
      ##   cpu: 500m
      ##   memory: 1Gi
      ##
      limits: {}
      requests: {}
  pvc:
    ## A manually managed Persistent Volume and Claim
    ## If defined, PVC must be created manually before volume will be bound
    ## The value is evaluated as a template, so, for example, the name can depend on .Release or .Chart
    ##
    existingClaim: etcd-nfs-pvc
    ## PVC Storage Request
    ##
    #size: 2Gi
    ## storageClassName, choose a storageClassName with ReadWriteMany support
    ##
    #storageClassName: nfs

```
