### ISSUE TITLE
[Elasticsearch] Cannot start with shared PVC

### ISSUE THREAD

**Issue by Vlizer** [bitnami/charts#6376]
**Which chart**:
elasticsearch:7.9.2

**Describe the bug**
Hello,
I have pulled the chart to my local machine, changed values to use existing PVC:
```
extraVolumes:
  - name: elasticsearch-custom-config
    configMap:
      defaultMode: 0777
      name : elasticsearch-custom-config
extraVolumeMounts:
  - name: elasticsearch-custom-config
    mountPath: /opt/bitnami/elasticsearch/config/elasticsearch_custom.yml
    subPath: elasticsearch_custom.yml
    readOnly: true
    ...
existingClaim: elasticsearch-data
```
and also added extra volume with configMap
```
apiVersion: v1
data:
  elasticsearch_custom.yml: |-
    node:
      max_local_storage_nodes: 40
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: elasticsearch
    app.kubernetes.io/name: elasticsearch
  name: elasticsearch-custom-config
  namespace: kube-logs
```

In master-0 logs:
![image](https://user-images.githubusercontent.com/12148362/118398971-2c831780-b65b-11eb-8019-f01fe4afd23f.png)
master-1 logs:
![image](https://user-images.githubusercontent.com/12148362/118398984-43c20500-b65b-11eb-8776-7f7e8a7e6f90.png)

There is no issue found on the k8s side, volume is correctly attached.
Volume:
![image](https://user-images.githubusercontent.com/12148362/118399276-b8e20a00-b65c-11eb-9fb2-250c8a39575d.png)

**Expected behaviour**
 - Start elasticsearch correctly
 - Find a way to have a single PV shared between all nodes 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:15:16Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"8ab00ff68a1763b5a506a7073cb8e67b12dfbcd7", GitTreeState:"clean", BuildDate:"2021-03-10T23:40:01Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```

**Additional context**
In the company, we have used Azure monitor for the last 2 years. We have decided to give a chance of EFK stack to check if it could solve our current problems. So if you have any hints to setup it correctly, it would be appreciated.
