### ISSUE TITLE
Readiness probe failed: Get "https://10.1.0.153:8080/wp-login.php": http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by polRk** [bitnami/charts#6377]
**Which chart**:
wordpress

**Describe the bug**
Readiness probe failed: Get "https://10.1.0.153:8080/wp-login.php": http: server gave HTTP response to HTTPS client

**To Reproduce**
helm upgrade --install as-master bitnami/wordpress -f values.yaml

```

initContainers:
  - name: sync
    image: k8s.gcr.io/git-sync/git-sync:v3.3.0
    imagePullPolicy: IfNotPresent
    env:
      - name: GIT_SYNC_BRANCH
        value: "master"
      - name: GIT_SYNC_ROOT
        value: "/bitnami/wordpress"
      - name: GIT_SYNC_DEST
        value: "wp-content"
      - name: GIT_SYNC_ONE_TIME
        value: "true"
    volumeMounts:
      - name: wordpress-data
        mountPath: /bitnami/wordpress
```

**Expected behavior**
Readiness probe success

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Mauraza** [comment]
Hi @polRk,

Could you add the logs of the container of Wordpress?

**Comment by polRk** [comment]
@Mauraza Not, but i remember, that apache logs only 200 statuses.

I fixed it after adding header section (ignore 302 codes) in values.yaml

**Comment by axot** [comment]
I got same error since yesterday with no-touch, the all running Pods got this.
I'm still figure out is this caused by wordpress automatic upgrade.

**Comment by axot** [comment]
My issue was fixed by Enable/Disable `Enforce SSL` option in iThemes Security. I think it is an inside upgrade related problem (new 8.0 release).

**Comment by Mauraza** [comment]
Hi @axot,

Thanks for sharing your solution!

**Comment by giannoug** [comment]
I'm also facing this issue with a new installation (no upgrade, etc). My values.yaml contains trivial overrides, I believe the `wordpressScheme` is causing issues in my case

**Comment by Mauraza** [comment]
Hi @giannoug,

Could you share your `values.yaml`?

**Comment by giannoug** [comment]
Hello @Mauraza,
here are the overrides:
```
wordpress:
  wordpressUsername: thewpuser
  wordpressPassword: thewppassword
  wordpressEmail: thewpuser@example.com
  wordpressBlogName: wpuser's blog
  wordpressScheme: https
  # Need to disable this
  # Ref: https://github.com/bitnami/charts/issues/6377
  readinessProbe:
    enabled: false
  service:
    type: ClusterIP
  ingress:
    enabled: true
    certManager: true
    tls: true
    hostname: example.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    extraHosts:
      - name: www.example.com
    extraTls:
      - hosts: [www.example.com]
        secretName: "www.example.com-tls"
  mariadb:
    auth:
      rootPassword: xxx
      password: zzz
```

**Comment by Mauraza** [comment]
Hi @giannoug,

In your values.yaml the `readinessProbe.enabled=false`  but did you check the comment in the values.yaml?

https://github.com/bitnami/charts/blob/e73b788e04344e5a1e3c0f41cca8adc7a8476d1e/bitnami/wordpress/values.yaml#L431-L446

Could you try adding the `readinessProbe.httpHeaders`?

**Comment by giannoug** [comment]
@Mauraza I did. I'm not using an LB, I'm using a ClusterIP which does not HTTPS-terminate 🤔 I managed to fix this though by adding the following:
```
  readinessProbe:
    httpGet:
      port: https
      scheme: HTTPS
```
