### ISSUE TITLE
Override default secretName in node/templates/ingress.yaml

### ISSUE THREAD

**Issue by asanderson** [bitnami/charts#6379]
**Which chart**:
node 15.2.8

**Is your feature request related to a problem? Please describe.**
Line 53 of https://github.com/bitnami/charts/blob/master/bitnami/node/templates/ingress.yaml sets the ingress secretName to `ingress.hostname-tls` with no way to override it for pre-existing secret.

**Describe the solution you'd like**
Add a setting which overrides the ingress secretName.

**Describe alternatives you've considered**
Tried setting `ingress.secrets[0].*` but ingress template does not override.

**Additional context**
N/A

**Comment by alvneiayu** [comment]
hi @asanderson 

You have a way to override the ingress secretName without including any new support. This is an example:

```
ingress:
  enabled: true
  hostname: foo.bar
  tls: false
  extraTls:
    - hosts:
        - foo.bar
      secretName: XXXX
```

Including those lines, you can set up your own secret name for the ingress.

I hope that I have helped you

Thanks a lot

Álvaro
