### ISSUE TITLE
[postgresql-ha] Using postgresql.existingSecret causes repmgr authentation error

### ISSUE THREAD

**Issue by krichter722** [bitnami/charts#6392]
**Which chart**:
bitnami/postgresql-ha 7.4.1

**Describe the bug**
Using an existing secret with keys `postgresql-password` and `repmgr-password` which is passed as chart value `postgresql.existingSecret` causes the second replica/pod in the statefulset to fail due to

```
2021-05-13 15:30:30.251 GMT [163] FATAL:  password authentication failed for user "repmgr"
2021-05-13 15:30:30.251 GMT [163] DETAIL:  Password does not match for user "repmgr".
	Connection matched pg_hba.conf line 1: "host     all            repmgr    0.0.0.0/0    md5"
[2021-05-13 15:30:30] [ERROR] connection to database failed
[2021-05-13 15:30:30] [DETAIL] 
FATAL:  password authentication failed for user "repmgr"
```

When specifying `pgpoolImage.debug=true` one sees

```
$ kubectl -n some-namespace logs deployment/postgresql-ha-release-pgpool
pgpool 08:20:55.61 
pgpool 08:20:55.61 Welcome to the Bitnami pgpool container
pgpool 08:20:55.62 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-pgpool
pgpool 08:20:55.62 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-pgpool/issues
pgpool 08:20:55.62 
pgpool 08:20:55.62 INFO  ==> ** Starting Pgpool-II setup **
pgpool 08:20:55.65 INFO  ==> Validating settings in PGPOOL_* env vars...
pgpool 08:20:55.66 INFO  ==> Initializing Pgpool-II...
pgpool 08:20:55.67 INFO  ==> Generating pg_hba.conf file...
pgpool 08:20:55.68 INFO  ==> Generating pgpool.conf file...
sed: -e expression #1, char 61: unterminated `s' command
```

**To Reproduce**

Reproducer in GitLab CI (personal choice):

```
variables:
  CLUSTER_NAME: "bitnami-psql-116-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_IID"
  CLUSTER_VERSION: "1.19.9-gke.1900"
  CLUSTER_MASCHINE_TYPE: e2-standard-4
  CLUSTER_ZONE: us-central1-c
  HELM_VERSION: "3.5.4"

stages:
  - setup-cluster
  - setup-operations
  - tear-down-cluster

setup-cluster:
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:340.0.0
  stage: setup-cluster
  script:
    - gcloud config set project $PROJECT_ID
    - gcloud auth activate-service-account --key-file "$GOOGLE_KEY"
    - gcloud config set compute/zone $CLUSTER_ZONE
    - gcloud beta container clusters create $CLUSTER_NAME --machine-type=$CLUSTER_MASCHINE_TYPE --cluster-version=$CLUSTER_VERSION --no-enable-stackdriver-kubernetes --enable-autoupgrade

setup-cluster-operations:
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:340.0.0
  stage: setup-operations
  script:
    - gcloud config set project $PROJECT_ID
    - gcloud auth activate-service-account --key-file "$GOOGLE_KEY"
    - gcloud config set compute/zone $CLUSTER_ZONE
    - gcloud config set container/cluster $CLUSTER_NAME
    - gcloud container clusters get-credentials $CLUSTER_NAME
    - curl https://get.helm.sh/helm-v$HELM_VERSION-linux-amd64.tar.gz > helm-v$HELM_VERSION-linux-amd64.tar.gz && tar xf helm-v$HELM_VERSION-linux-amd64.tar.gz && rm helm-v$HELM_VERSION-linux-amd64.tar.gz && mkdir -p /usr/local/bin && mv linux-amd64/helm /usr/local/bin/
    - kubectl version
    - helm version
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo update
    - kubectl create namespace some-namespace
    - kubectl -n some-namespace apply -f postgres-secret.yml
    - helm install postgresql-ha-release bitnami/postgresql-ha --namespace some-namespace --version 7.4.0 --wait --set postgresql.existingSecret=postgres-secret || true
    - helm -n some-namespace ls --all
    - kubectl get pods --all-namespaces
    - kubectl -n some-namespace logs pod/postgresql-ha-release-postgresql-0
    - kubectl -n some-namespace logs pod/postgresql-ha-release-postgresql-1

tear-down-cluster:
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:340.0.0
  stage: tear-down-cluster
  when: always
  script:
    - gcloud config set project $PROJECT_ID
    - gcloud auth activate-service-account --key-file "$GOOGLE_KEY"
    - gcloud config set compute/zone $CLUSTER_ZONE
    - gcloud config set container/cluster $CLUSTER_NAME
    - gcloud container clusters get-credentials $CLUSTER_NAME
    - python3 k8s-ci-tools/find_disks.py
    - cat disk-name-suffixes
    - gcloud container clusters delete --quiet $CLUSTER_NAME
    - python3 k8s-ci-tools/delete_disks.py
```

with `postgres-secret.yml`

```
apiVersion: v1
kind: Secret
metadata:
  name: "postgres-secret"
type: Opaque
data:
  postgresql-password: "cG9zdGdyZXMK"
  repmgr-password: "cG9zdGdyZXMK"
```
and `values.yml`

```
postgresql:
  existingSecret: "postgres-secret"
```

**Expected behavior**
Afaiu the REAMDE a secret with the specified keys is supposed to work, i.e. create a deployment with pgpool and PostgreSQL pods which can comminicate with each other and provide the functionality of a HA cluster.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1900", GitCommit:"008fd38bf3dc201bebdd4fe26edf9bf87478309a", GitTreeState:"clean", BuildDate:"2021-04-14T09:22:08Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
`libfile.sh` contains the note
```
    # We should avoid using 'sed in-place' substitutions
    # 1) They are not compatible with files mounted from ConfigMap(s)
    # 2) We found incompatibility issues with Debian10 and "in-place" substitutions
```
