### ISSUE TITLE
mariadb as dependency after running a while CrashLoopBackOff 

### ISSUE THREAD

**Issue by kivi** [bitnami/charts#6394]
**Which chart**:
    version: 7.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: bitnami/mariadb

**Describe the bug**
I am running mariadb as a dependency in a Chart where I have configured Matomo. It was working and started to fail after a while. I think, it started to fail, when the pod first time crashed and restarted. 

After enabling setting the log level to debug:

```js
2021-05-17 18:37:11 0 [Note] Added new Master_info '' 
to hash table                                         IP: '127.0.0.1'.  
2021-05-17 18:37:11 0 [Note] /opt/bitnami/mariadb/sbin@% root@matomo-mar/mysqld: ready for connections.
Version: '10.3.24-MariaDB-log'  socket: '/opt/bitnami/o entries succeedemariadb/tmp/mysql.sock'  port: 3306  Source distribution                                                    to hash table     
2021-05-17 18:37:12 9 [Warning] Access denied for user/mysqld: ready for 'root'@'localhost' (using password: YES)
Version check failed. Got the following error when calmariadb/tmp/mysql.ling the 'mysql' command line client
ERROR 1045 (28000): Access denied for user 'root'@'loc 'root'@'localhostalhost' (using password: YES)
FATAL ERROR: Upgrade failed                           ling the 'mysql' c
mariadb 18:37:12.98 INFO  ==> Stopping mariadb  
```

**To Reproduce**
As a base Chart I use:   https://github.com/brunowego/matomo-helm

And I have the changed slightly the dependency:

dependencies:
  - name: mariadb
    version: 7.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: bitnami/mariadb
    tags:
      - database

The secrets are set:
```kubernetes
k describe secret matomo-mariadb

Name:         matomo-mariadb
Namespace:    matomo
Labels:       app=mariadb
              app.kubernetes.io/managed-by=Helm       
              chart=mariadb-7.10.4
              heritage=Helm
              release=matomo
Annotations:  meta.helm.sh/release-name: matomo       
              meta.helm.sh/release-namespace: matomo  

Type:  Opaque

Data
====
mariadb-replication-password:  10 bytes
mariadb-root-password:         10 bytes
```

**Expected behavior**
The error should not happen `Access denied for user 'root'@'loc 'root'@'localhostalhost' (using password: YES)`

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alemorcuq** [comment]
Did you redeploy the chart or something like that? If that's the case, it's possible that a new secret was generated for the database which does not match the existing credentials in the PVC.

Can you share the logs of the MariaDB pod and the output of `kubectl describe <mariadb pod>` ?

**Comment by kivi** [comment]
That is very likely. Since I not so familiar with Helm and Kubernetes. I tried different scripts and one point I lost track, of what exactly happend. 
I thought with Helm on my side, I am save to repeat installations, so things are idempotent or updates go fluently with no affect on credentials with no additional consideration of credentials.

I can say that it was running a couple of weeks, then the slave Mariadb crashed and some days later master also got into the crash loop.

```yaml
Name:         matomo-mariadb-master-0
Namespace:    matomo
Priority:     0
Node:         pool-8dzwo0szt-8bsw3/10.114.0.7
Start Time:   Mon, 17 May 2021 20:36:59 +0200
Labels:       app=mariadb
              chart=mariadb-7.10.4
              component=master
              controller-revision-hash=matomo-mariadb-master-7c46fcb967 
              heritage=Helm
              release=matomo
              statefulset.kubernetes.io/pod-name=matomo-mariadb-master-0
Annotations:  <none>
Status:       Running
IP:           10.244.2.88
IPs:
  IP:           10.244.2.88
Controlled By:  StatefulSet/matomo-mariadb-master
Containers:
  mariadb:
    Container ID:   containerd://3e45640baf276a81e411b06e3efbbb7c6040778bef4514eea2508c8ed9fbfdd6
    Image:          docker.io/bitnami/mariadb:10.3.24-debian-10-r49
    Image ID:       docker.io/bitnami/mariadb@sha256:d573eb974147a3210dcf6c6aa053cee59429d9d59b7c76ca8ff1fe70467033ee
    Port:           3306/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 18 May 2021 15:59:53 +0200
      Finished:     Tue, 18 May 2021 15:59:57 +0200
    Ready:          False
    Restart Count:  229
    Liveness:       exec [sh -c password_aux="${MARIADB_ROOT_PASSWORD:-}"
if [ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]; then
    password_aux=$(cat $MARIADB_ROOT_PASSWORD_FILE)
fi
mysqladmin status -uroot -p$password_aux
] delay=120s timeout=1s period=10s #success=1 #failure=3
    Readiness:  exec [sh -c password_aux="${MARIADB_ROOT_PASSWORD:-}"
if [ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]; then
    password_aux=$(cat $MARIADB_ROOT_PASSWORD_FILE)
fi
mysqladmin status -uroot -p$password_aux
] delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment:
      BITNAMI_DEBUG:                 true
      MARIADB_ROOT_PASSWORD:         <set to the key 'mariadb-root-password' in secret 'matomo-mariadb'>  Optional: false
      MARIADB_DATABASE:              my_database
      MARIADB_REPLICATION_MODE:      master
      MARIADB_REPLICATION_USER:      replicator
      MARIADB_REPLICATION_PASSWORD:  <set to the key 'mariadb-replication-password' in secret 'matomo-mariadb'>  Optional: false
    Mounts:
      /bitnami/mariadb from data (rw)
      /opt/bitnami/mariadb/conf/my.cnf from config (rw,path="my.cnf")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-cgh9l (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-matomo-mariadb-master-0
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      matomo-mariadb-master
    Optional:  false
  default-token-cgh9l:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-cgh9l
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason   Age                   From     Message
  ----     ------   ----                  ----     -------
  Warning  BackOff  84s (x5413 over 19h)  kubelet  Back-off restarting failed container
```

Thanks for revising my configurations.
