### ISSUE TITLE
[bitnami/nginx-ingress-controller] http to https 308 redirect loop

### ISSUE THREAD

**Issue by babatundebusari** [bitnami/charts#6411]
**Which chart:**
[bitnami/nginx-ingress-controller] version 7.6.1

**Describe the bug:**
There is a 308 redirect loop when trying to redirect http to https

setting this does NOT even redirect
```
nginx.ingress.kubernetes.io/ssl-redirect: "true"
```

and setting this causes 308 redirect loop

```
nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
```

**To Reproduce:**

set the following for the nginx ingress controller

```
service:
  targetPorts:
    http: http
    https: http
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "acm cert here"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
```

and then from the service using the ingress class
add this annotation to redirect http to https

```
  annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
```

**Expected behavior**
What annotations do we need to make http to https redirect work???

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
What annotations do we need to makehttp to https work???

Thanks
