### ISSUE TITLE
[bitnami:redis-cluster] redis-statefulset.yaml set wrong paths of entrypoint.sh and run.sh

### ISSUE THREAD

**Issue by chhaosh** [bitnami/charts#6413]
**Which chart**:
The name (and version) of the affected chart
bitnami/redis-cluster

**Describe the bug**
File
https://github.com/bitnami/charts/blob/master/bitnami/redis-cluster/templates/redis-statefulset.yaml
set ARGS:
/opt/bitnami/scripts/redis-cluster/entrypoint.sh /opt/bitnami/scripts/redis-cluster/run.sh
However there are no such files in docker image bitnami/redis:6.2.3-debian-10-r2, the correct path is 
/opt/bitnami/scripts/redis/entrypoint.sh /opt/bitnami/scripts/redis/run.sh

So after helm install, all Pods are CrashLoopBackOff with error log
$ k logs my-release-redis-cluster-5 -p
/bin/bash: line 11: /opt/bitnami/scripts/redis-cluster/entrypoint.sh: No such file or directory

**To Reproduce**

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by alvneiayu** [comment]
hi @chhaosh 

I can not reproduce your problem. I already installed the redis cluster chart with the default values and I can not reproduce your problem. The redis cluster stateful will use docker.io/bitnami/redis-cluster:6.2.3-debian-10-r2 not bitnami/redis:6.2.3-debian-10-r2 image:

```
helm template temp . -s templates/redis-statefulset.yaml
---
# Source: redis-cluster/templates/redis-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: temp-redis-cluster
  labels:
    app.kubernetes.io/name: redis-cluster
    helm.sh/chart: redis-cluster-6.0.6
    app.kubernetes.io/instance: temp
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-cluster
      app.kubernetes.io/instance: temp
  replicas: 6
  serviceName: temp-redis-cluster-headless
  podManagementPolicy: "Parallel"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-cluster
        helm.sh/chart: redis-cluster-6.0.6
        app.kubernetes.io/instance: temp
        app.kubernetes.io/managed-by: Helm
      annotations:
        checksum/scripts: f53a47aba32ed4763470a6cad1c4a5e68cc352608afd2e462c584ad4d797bbb7
        checksum/secret: 2a1fe4cea6873447149bbea2d1923be57c0545759051088a9f6b9ace69febef7
    spec:
      enableServiceLinks: false
      
      securityContext:
        fsGroup: 1001
      serviceAccountName: default
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: redis-cluster
                    app.kubernetes.io/instance: temp
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      containers:
        - name: temp-redis-cluster
          image: docker.io/bitnami/redis-cluster:6.2.3-debian-10-r2
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 1001
          command: ['/bin/bash', '-c']
          args:
            - |
              # Backwards compatibility change
              if ! [[ -f /opt/bitnami/redis/etc/redis.conf ]]; then
                  echo COPYING FILE
                  cp  /opt/bitnami/redis/etc/redis-default.conf /opt/bitnami/redis/etc/redis.conf
              fi
              pod_index=($(echo "$POD_NAME" | tr "-" "\n"))
              pod_index="${pod_index[-1]}"
              if [[ "$pod_index" == "0" ]]; then
                export REDIS_CLUSTER_CREATOR="yes"
                export REDIS_CLUSTER_REPLICAS="1"
              fi
              /opt/bitnami/scripts/redis-cluster/entrypoint.sh /opt/bitnami/scripts/redis-cluster/run.sh
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_NODES
              value: "temp-redis-cluster-0.temp-redis-cluster-headless temp-redis-cluster-1.temp-redis-cluster-headless temp-redis-cluster-2.temp-redis-cluster-headless temp-redis-cluster-3.temp-redis-cluster-headless temp-redis-cluster-4.temp-redis-cluster-headless temp-redis-cluster-5.temp-redis-cluster-headless "
            - name: REDISCLI_AUTH
              valueFrom:
                secretKeyRef:
                  name: temp-redis-cluster
                  key: redis-password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: temp-redis-cluster
                  key: redis-password
            - name: REDIS_AOF_ENABLED
              value: "yes"
            - name: REDIS_TLS_ENABLED
              value: "no"
            - name: REDIS_PORT
              value: "6379"
          ports:
            - name: tcp-redis
              containerPort: 6379
            - name: tcp-redis-bus
              containerPort: 16379
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            # One second longer than command timeout should prevent generation of zombie processes.
            timeoutSeconds: 6
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - /scripts/ping_liveness_local.sh 5
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            # One second longer than command timeout should prevent generation of zombie processes.
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - /scripts/ping_readiness_local.sh 1
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: redis-data
              mountPath: /bitnami/redis/data
              subPath: 
            - name: default-config
              mountPath: /opt/bitnami/redis/etc/redis-default.conf
              subPath: redis-default.conf
            - name: redis-tmp-conf
              mountPath: /opt/bitnami/redis/etc/
      volumes:
        - name: scripts
          configMap:
            name: temp-redis-cluster-scripts
            defaultMode: 0755
        - name: default-config
          configMap:
            name: temp-redis-cluster-default
        - name: redis-tmp-conf
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
        
  updateStrategy:
    type: RollingUpdate
```
I generated the template inside the bitnami/redis-cluster folder (inside the chart repository) with the default values. Did you change the values.yaml?

Thanks a lot

Álvaro
