### ISSUE TITLE
[bitnami/magento] Ingress using Fake Certificate instead of created certificate

### ISSUE THREAD

**Issue by mahgo** [bitnami/charts#6421]
**Which chart**:
Magento

**Describe the bug**
I have an ingress being made from the helm chart when installing it from using ingress.enabled, ingress.tls, ingress.hostname and ingress.annotations. However, the ingress is not using the certificate that was issued, and is instead using a Fake Certificate. I can confirm the status of the certificate that was issued is True.

I'm not really sure where to look with this problem. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"4d62230f10af41cec2851b5b113874f6d2098297", GitTreeState:"clean", BuildDate:"2021-03-22T23:01:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rafariossaa** [comment]
Hi,
  I am not very sure of what you mean by "ingress is not using the certificate that was issued", if you currently have a certificate you need to provide it by using the tls secret parameters. You can check them [here](https://github.com/bitnami/charts/tree/master/bitnami/magento#user-content-tls-secrets).

**Comment by mahgo** [comment]
Apologies for not being clear. I also forgot to mention that a ClusterIssuer was needed, but the Ingress itself automatically triggers the certificate being issued (in my case from Let's Encrypt). I use --set ingress.annotations."cert-manager\.io/issuer"=\"letsencrypt-prod\" when installing the magento chart, so that the ingress created by this chart knows which certificate to use.

When I say "ingress is not using the certificate that was issued", I mean the certificate this is being used is a Fake Certificate, and not the one issued by Let's Encrypt.

**Comment by juan131** [comment]
Hi @mahgo 

Could you give it a try by installing Magento using the `values.yaml` below?

```yaml
service:
  type: ClusterIP
ingress:
  enabled: true
  tls: true
  certManager: true
  hostname: foo.bar.baz
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
```

The resulting Ingress rule should look like this, and I think that's what you're looking for:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: magento
  namespace: default
  labels:
    app.kubernetes.io/name: magento
    helm.sh/chart: magento-18.0.2
    app.kubernetes.io/instance: magento
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: letsencrypt-prod
spec:
  rules:
    - host: "foo.bar.baz"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: magento
                port:
                  name: http
  tls:
    - hosts:
        - foo.bar.baz
      secretName: foo.bar.baz-tls
```

Cert Manager should issue the `foo.bar.baz-tls` secret using your ClusterIssuer.
