### ISSUE TITLE
Odoo Cannot find pid file '/opt/bitnami/odoo/tmp/pids/odoo.pid'

### ISSUE THREAD

**Issue by mrad-bilel** [bitnami/charts#6438]
**Which chart**:

odoo-18.2.7

**Describe the bug**
I'm working to deploy odoo on kubernetes using the helm chart and got 2 errors 

```
Error executing 'postInstallation': Unable to start com.bitnami.odoo: Cannot find pid file '/opt/bitnami/odoo/tmp/pids/odoo.pid'.: Cannot find pid file '/opt/bitnami/odoo/tmp/pids/odoo.pid'.

```

**To Reproduce**

 1st Error

Below my helm values 

 
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: odoo
  namespace: odoo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: odoo
  chart:
    git: git@github.com:bitnami/charts.git
    path: bitnami/odoo
    ref: master
  values:
    image:
      tag: 14.0.20210410-debian-10-r3
      pullPolicy: IfNotPresent

    odooUsername: xxxxxxx
    odooEmail: xxxxxx
    existingSecret: odoo-password

    postgresql:
      enabled: false  
    externalDatabase:
      host: xxxxxxxxxxxx.rds.amazonaws.com
      user: xxxxxx
      password: xxxxx 
      port: 5432

    ingress:
      enabled: true
      hostname: odoo.mydomain

    resources:
      requests:
        memory: 512Mi
        cpu: 300m
      limits:
        memory: 512Mi
        cpu: 600m 
```

This is the log from my pod 

```

2021-05-21T10:25:56.724465836Z
2021-05-21T10:25:56.724488539Z Welcome to the Bitnami odoo container
2021-05-21T10:25:56.724493499Z Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-odoo
2021-05-21T10:25:56.724497940Z Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-odoo/issues
2021-05-21T10:25:56.724501547Z
2021-05-21T10:26:02.828195885Z nami    INFO  Initializing odoo
2021-05-21T10:26:03.149777598Z odoo    INFO  Configuring Odoo database...
2021-05-21T10:26:03.152262605Z postgre INFO  Trying to connect to PostgreSQL server
2021-05-21T10:26:03.192023969Z postgre INFO  Found PostgreSQL server listening at xxxxxxx.rds.amazonaws.com:5432
2021-05-21T10:26:03.217803901Z postgre INFO  PostgreSQL server listening and working at xxxxxxxrds.amazonaws.com:5432
2021-05-21T10:26:03.217964827Z odoo    INFO  Preparing Odoo environment...
2021-05-21T10:26:59.178566434Z odoo    INFO  Starting Odoo...
2021-05-21T10:28:01.675316898Z Error executing 'postInstallation': Unable to start com.bitnami.odoo: Cannot find pid file '/opt/bitnami/odoo/tmp/pids/odoo.pid'.: Cannot find pid file '/opt/bitnami/odoo/tmp/pids/odoo.pid'.
```

2nd Error

When i restart my pod i got this error 

```
Welcome to the Bitnami odoo container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-odoo
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-odoo/issues

nami    INFO  Initializing odoo
odoo    INFO  Configuring Odoo database...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at xxxxxxx.rds.amazonaws.com:5432
postgre INFO  PostgreSQL server listening and working at xxxxxx.amazonaws.com:5432
odoo    INFO  Preparing Odoo environment...
Error executing 'postInstallation': User bn_odoo already exists
```
Why the startup script does not check for bn_odoo role in the DB ? 

**Additional context**
```
- kubernetes verion v.1.17
- DB version AWS RDS Postgres 12.4 
- Storage type EBS RWO
helm ls
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION  
odoo             odoo            1               2021-05-21 10:39:52.367690658 +0000 UTC deployed        odoo-18.2.7     14.0.2021041

``` 

Thanks in advance .

**Comment by javsalgar** [comment]
Hi,

It seems that there is an issue in the initialization script. We're working on a major change in the Odoo container that uses bash, I will forward this to the engineering team to take it into account when working on the new version. Does it work when not using the RDS database? This is to discard that the issue is in the volume provider.

**Comment by mrad-bilel** [comment]
Hey @javsalgar,

Thanks for your update .

I'm workig to setup a production deployment so i cannot setup a local DB (a statefulsets) , it should be an RDS . 

Does the entrepise version use the same container and helm chart version ? 
Can you provide me a stable version so i can perform the deployment ? 
Do wo have an idea when the new version will be released ?

**Comment by javsalgar** [comment]
Hi,

> Does the entrepise version use the same container and helm chart version ?

I'm afraid we're not packaging the Enterprise version, only the Open Source one

> Can you provide me a stable version so i can perform the deployment ?

We're testing the chart with all major Kubernetes distributions, that's we would like to know at which point the container initialization is failing. The idea of doing a quick  test it with a StatefulSet is just to ensure that the issue is when connecting to RDS, and then we can continue checking why it is failing to connect there. If it also fails with Statefulsets, then that means that the issue might be somewhere else.

> Do we have an idea when the new version will be released?

We don't have an ETA, but I know that we expect to start working on it during the next month

**Comment by mrad-bilel** [comment]
Hi,

I've deployed odoo with local postgres DB and it works fine and i can access it . 

```
kubectl get pods
NAME                          READY   STATUS    RESTARTS   AGE
odoo-86b6dbc47c-s9rlw          1/1   Running   0          17m
odoo-postgresql-0              1/1   Running   0          35m

helm ls
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION  
odoo             odoo            1               2021-05-25 08:11:28.488592027 +0000 UTC deployed        odoo-18.2.8     14.0.20210510

```

How to check the RDS connection issue ?

**Comment by javsalgar** [comment]
Does the RDS require TLS connection? That may partially explain the issue

**Comment by mrad-bilel** [comment]
Hi @javsalgar,

I've checked and found that rds.force_ssl is set to false so ssl/tls is not enforced .  
Additional info i've other applications using the same RDS instances and there is no issue .

**Comment by javsalgar** [comment]
Hi,

I would also try the following:

```
extraEnvVars:
  - name: NAMI_DEBUG
    value: true
  - name: NAMI_LOG_LEVEL
    value: trace8   
```

Let's see if this provides more logging. Make sure that you delete also any PVC from previous installations.
