### ISSUE TITLE
kibana savedObjects not processed when server.rewriteBasePath is used

### ISSUE THREAD

**Issue by jerryharrow** [bitnami/charts#6455]
**Which chart**:
kibana  chart 8.1.2

**Describe the bug**

When rewriteBasePath is used the basePath of the API changes.   The saved-objects-configmap.yaml doesn't consider this, so when rewriteBasePath is use, the curl call to load the savedObjects gets a 404 error and fails to load them.

**To Reproduce**

1. Create elastic/helm with rewriteBasePath  & savedObjects config map
```
elasticsearch:
  fullnameOverride: elasticsearch
  global:
    kibanaEnabled: true
    storageClass: "managed-nfs-storage-delete"
  kibana:
    ingress:
      enabled: true
      path: /kibana
      annotations:
        kubernetes.io/ingress.class: *ingressClass
    savedObjects:
      configmap: kibana-config
    configuration:
      server:
        basePath: /kibana
        rewriteBasePath: true
```

2. The kibana log shows a 404 failure loading the savedObjects.

**Expected behavior**

Saved object should be loaded even when rewriteBasePath is specified.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server 127.0.0.1:46716 was refused - did you specify the right host or port?
```

**Additional context**

Line 8 of the saved-objects-confimap.yaml template -- does not adjust the URL when rewriteBasePath  is in effect.

  {{- $savedObjectsUrl := printf "localhost:%d/api/saved_objects/_import" (int .Values.containerPort) }}

This is a follow-on to https://github.com/bitnami/bitnami-docker-kibana/pull/49  -- in which the kibana container has a similar defect.  Once fixing that, I then was able to hit the related behavior in this issue.
