### ISSUE TITLE
[external-dns] Ability to disable liveness check

### ISSUE THREAD

**Issue by psibi** [bitnami/charts#6471]
**Which chart**:

Chart name: external-dns
version: v4.9.1 (But even the latest one in master has the same issue)

**Is your feature request related to a problem? Please describe.**

Both the `readiness` and `liveness` probe are currently same:

```
          readinessProbe: 
            failureThreshold: 6
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe: 
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
```

Using a static tool like [kube-score](https://github.com/zegl/kube-score) throws this error:

```
apps/v1/Deployment external-dns in my-namespace                       💥
    [CRITICAL] Pod Probes
        · Container has the same readiness and liveness probe
            Using the same probe for liveness and readiness is very likely
            dangerous. Generally it's better to avoid the livenessProbe than
            re-using the readinessProbe.
            More information: https://github.com/zegl/kube-score/blob/master/README_PROBES.md
```

**Describe the solution you'd like**

The liveness probe it currently has isn't correct. Since currently the `external-dns` pod runs as PID 1, it would be best to leave the default behaviour of the k8s controller: If the PID 1 process exits, just restart the container.

With the current helm chart, there is no way to disable the liveness probe to fall back to the default behaviour of the k8s controller. One workaround is to use something like `exec: command` pattern inside the liveness probe to check if the application is alive. But I would like to avoid that and would like the ability in the chart to disable liveness check so that I can fallback to the kubernetes implementation behaviour.

**Describe alternatives you've considered**

There are various alternatives recommened by kube-score itself: https://github.com/zegl/kube-score/blob/master/README_PROBES.md#livenessprobe

**Additional context**

No additional context, but can provide if something is required.
