### ISSUE TITLE
[Bitnami/Wordpress] Apache crashes multiple times per day

### ISSUE THREAD

**Issue by corend** [bitnami/charts#6475]
**Which chart**:
Wordpress 5.7.2-debian-10-r10 and before.

**Describe the bug**
After few hours the Apache server is restarting without any reason. It happens several times per day. With a basic installation I have a 97.5% available time, this is the maximum I can reach.

**To Reproduce**

1. Install the Wordpress chart 5.7.2-debian-10-r10 or before, I did two installs one as simple basic install in RWO mode and another one the same but with RWX mode
2. Check how many restarts of your PODS you have after one day or two days
3. Most of the time you will see this error without any other errors before that: 
```LOG
[pid 67] AH00169: caught SIGTERM, shutting down
```
4. And sometimes you can get the following errors:
```LOG
[pid 67] AH00051: child pid 73 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[pid 67] AH00169: caught SIGTERM, shutting down
```
Is there any default Apache settings configured with Bitnami to force the Apache to restart?
This is not only a notice message as the Pods are really ending connections and restart. I've noticed that most of the time if you have multiple pods they all restart more or less at the same time (it is a question of seconds).

**Expected behavior**
Having not any restart without any reasons and fix Apache coredump issue. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v3.5.4
```

- Output of `kubectl version`:

```
v1.21.0
```

**Additional context**
I also tried with specific php.ini values in case of infinite loop somewhere but without success (Tried with lower values or higher values but the same issue happens):
```YAML
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-ini-v5
  labels:
    app.kubernetes.io/name: wordpress
data:
  php-custom.ini: |
    max_execution_time = 120
    max_input_time = 120
    memory_limit = 512M
    max_input_vars = 3000
```
Unfortunately, I have not any more information than that: WP Debug doesn't return anything, and in the logs linked to these pods I only have those errors reported in this ticket without more information than that.

We are getting this error since weeks/months, I was hopping to find it by myself but unfortunately I don't find any reason why this is restarting Apache. Any help would be appreciated.

I'm getting lost...

**Comment by marcosbc** [comment]
Hi @corend, unfortunately I'm not familiar with this issue, I've never seen it. I'm going to launch a deployment and leave it running for a day and see if I can reproduce the restarts.

Could you share more information about your Kubernetes cluster?

**Comment by corend** [comment]
Hi @marcosbc,
Yes for sure:
1 large cluster with:
- 2 VMs for storage (Longhorn v1.1.1) for the files : 2xVM of 4 X86 64 bit, 16 GB RAM, 150 Go NVMe
- 1 VM for the backend for the Apache/Wordpress (nodeSelector setup) : 1xVM of CPU 8 X86 64 bit, 32 GB RAM, 300 Go NVMe
- 1 nginx-controller
- 1 cert-manager
- 1 external HA Mysql (external but in the same data center)
On this cluster we have two WP Installs one running in RWO mode and another one running in RWX mode.

1 small cluster for dev tests without Longhorn pool:
- 1 VM for everything: 3 X86 64 bit, 4 GB RAM, 40 Go NVMe
With only one RWO WP install.

All cluster VMs are running on Ubuntu 20.04.1 LTS.
This morning I had one crash on the RWX setup but strangely not on the others... Nothing changed in between my post here and now.

If you need more info, please do not hesitate to ask me.

**Comment by marcosbc** [comment]
Thanks @corend. It could also be useful to know the version of your Kubernetes cluster (both client and server) and the version of Docker or containerd that your nodes are using. To get the containerd version, you can run the following commands:

```console
$ kubectl get nodes # extract NODE-NAME
# kubectl get node NODE-NAME -o jsonpath="{.status.nodeInfo.containerRuntimeVersion}"
```

As for this issue, unfortunately I've not been able to reproduce it yet:

```
NAME                              READY   STATUS    RESTARTS   AGE
mywp-mariadb-0                    1/1     Running   0          16h
mywp-wordpress-6d9498d585-qtz78   1/1     Running   0          16h
```

**Comment by corend** [comment]
Here we go:

(only the name for kubectl get nodes)
```
prod-node-prod-pool-fbeda1d87cb64fe7970
prod-node-prod-storage-xs-56b66570c5d34
prod-node-prod-storage-xs-df22e6f218854
```

```
containerd://1.4.4
```

Did you also try with a RWX mode?

Thx for your help, I feel less alone on this issue :)

**Comment by marcosbc** [comment]
Hi @corend, after some days it seems to continue working fine:

```
mbwp1-mariadb-0                    1/1     Running            0          3d18h
mbwp1-wordpress-6d9498d585-qtz78   1/1     Running            0          3d18h
```

> Did you also try with a RWX mode?

Could you specify the list of Helm deployment options that you specified? That way we may be able to reproduce your issue with the most similar list of options.

**Comment by corend** [comment]
Yes, please find it below:

PHP Configmap:
```YAML
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-ini-v1
  labels:
    app.kubernetes.io/name: wordpress
data:
  php-custom.ini: |
    upload_max_filesize = 300M
    post_max_size = 300M
    max_execution_time = 600
    max_input_time = 600
    memory_limit = 1024M
    max_input_vars = 10000
```

Helm for Wordpress:

```YAML
livenessProbe:
  enabled: true
  httpGet:
    httpHeaders:
      - name: X-Forwarded-Proto
        value: https
readinessProbe:
  enabled: true
  httpGet:
    path: /
    httpHeaders:
      - name: X-Forwarded-Proto
        value: https
wordpressBlogName: User's Blog!
wordpressEmail: WPEMAIL
wordpressExtraConfigContent: ""
wordpressFirstName: FirstName
wordpressLastName: LastName
wordpressTablePrefix: wp_shop
wordpressUsername: WPUSER
wordpressPassword: WPPWD
image:
  registry: docker.io
  repository: bitnami/wordpress
  tag: 5.7.2-debian-10-r10
allowOverrideNone: true
htaccessPersistenceEnabled: false
service:
  type: ClusterIP
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
    nginx.ingress.kubernetes.io/client-max-body-size: 200m
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
  certManager: true
  enabled: true
  #to be updated with the correct URL of the website
  hostname: domain.name
  secrets: []
  tls: true
mariadb:
  enabled: false
externalDatabase:
  host: DBIP
  port: DBPORT
  database: DBNAME
  user: DBUSER
  password: DBPWD
resources:
  requests:
    memory: 1024Mi
    cpu: 1000m
pdb:
  create: true
  minAvailable: 1
replicaCount: 1
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 80
  targetMemory: 80
persistence:
  enabled: true
  storageClass: longhorn-nfs
  #storageClass: nfs
  accessModes:
    - ReadWriteMany
  size: 10Gi
initContainers:
  - name: volume-permissions
    image: bitnami/minideb
    imagePullPolicy: Always
    command: ['sh', '-c', 'chown 1001:1001 /bitnami/wordpress']
    volumeMounts:
    - mountPath: /bitnami/wordpress
      name: wordpress-data
      subPath: wordpress
nodeSelector:
  k8s.scaleway.com/env: prod-fe
allowEmptyPassword: false
extraVolumeMounts:
  - name: php-ini
    mountPath: /opt/bitnami/php/etc/conf.d
extraVolumes:
  - name: php-ini
    configMap:
      name: php-ini-v1
customPostInitScripts:
  wp_memory_limit.sh: |
    sed -i "/.*That's all, stop editing! Happy publishing.*/i define('WP_MEMORY_LIMIT', '512M');" /opt/bitnami/wordpress/wp-config.php
wordpressConfigureCache: true
memcached:
  enabled: true
  service:
    port: 11211
```

I realized that I did different installs on an existing volume with already WP previously installed on it... Maybe this is linked to that. I will do some more tests in few weeks.
