### ISSUE TITLE
[postgresql-ha] Upgrade fails if postgresql.existingSecret is used

### ISSUE THREAD

**Issue by krichter722** [bitnami/charts#6510]
**Which chart**:
bitnami/postgresql-ha

**Describe the bug**
If PostgreSQL server and reprmgr credentials are managed in a secret with the expected keys outside of the chart and that secret is passed through the chart value `postgresql.existingSecret` a chart is supposed to be upgradable afaik. However, `helm upgrade` fails due to `'postgresql.password' must not be empty`.

I could not find reliable information in the documentation, especially not in [Credential errors while upgrading chart releases](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases) so I opened https://github.com/bitnami/charts-docs/issues/38 where I got the information that maintaining credentials in a secret not managed, but only used by the chart, is a valid upgrade path.

If I have to specify `postgresql.password` for the upgrade this contradicts the information I got from the linked issue comment. And it makes the chart unnecessarily hard to use with tools like Ansible. And it's simply inconvenient that one has to specify the password in both the secret and again as a chart value for upgrades.

The behavior seems to be the same for `bitnami/postgresql`.

**To Reproduce**
In form of a GitLab CI script which allows to reproduce on GKE easily:

```
variables:
  CLUSTER_NAME: "bitnami-psql-upgrade-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_IID"
  CLUSTER_VERSION: "1.19.9-gke.1900"
  CLUSTER_MASCHINE_TYPE: e2-standard-4
  CLUSTER_ZONE: us-central1-c
  HELM_VERSION: "3.5.4"

stages:
  - setup-cluster
  - setup-operations
  - tear-down-cluster

setup-cluster:
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:340.0.0
  stage: setup-cluster
  script:
    - gcloud config set project $PROJECT_ID
    - gcloud auth activate-service-account --key-file "$GOOGLE_KEY"
    - gcloud config set compute/zone $CLUSTER_ZONE
    - gcloud beta container clusters create $CLUSTER_NAME --machine-type=$CLUSTER_MASCHINE_TYPE --cluster-version=$CLUSTER_VERSION --no-enable-stackdriver-kubernetes --enable-autoupgrade

setup-cluster-operations:
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:340.0.0
  stage: setup-operations
  script:
    - gcloud config set project $PROJECT_ID
    - gcloud auth activate-service-account --key-file "$GOOGLE_KEY"
    - gcloud config set compute/zone $CLUSTER_ZONE
    - gcloud config set container/cluster $CLUSTER_NAME
    - gcloud container clusters get-credentials $CLUSTER_NAME
    - curl https://get.helm.sh/helm-v$HELM_VERSION-linux-amd64.tar.gz > helm-v$HELM_VERSION-linux-amd64.tar.gz && tar xf helm-v$HELM_VERSION-linux-amd64.tar.gz && rm helm-v$HELM_VERSION-linux-amd64.tar.gz && mkdir -p /usr/local/bin && mv linux-amd64/helm /usr/local/bin/
    - kubectl version
    - helm version
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo update
    - kubectl apply -f postgres-secret.yml
    - helm install postgresql-ha-release bitnami/postgresql-ha --version 7.5.1 --wait --set postgresql.existingSecret=postgres-secret
    - helm ls --all
    - kubectl get pods --all-namespaces
    - helm upgrade postgresql-ha-release bitnami/postgresql-ha --version 7.5.1 --wait --set postgresql.existingSecret=postgres-secret

tear-down-cluster:
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:340.0.0
  stage: tear-down-cluster
  when: always
  script:
    - gcloud config set project $PROJECT_ID
    - gcloud auth activate-service-account --key-file "$GOOGLE_KEY"
    - gcloud config set compute/zone $CLUSTER_ZONE
    - gcloud config set container/cluster $CLUSTER_NAME
    - gcloud container clusters get-credentials $CLUSTER_NAME
    - python3 k8s-ci-tools/find_disks.py
    - cat disk-name-suffixes
    - gcloud container clusters delete --quiet $CLUSTER_NAME
    - python3 k8s-ci-tools/delete_disks.py
```

**Expected behavior**
The `helm upgrade` command should return successfully using the credentials from `postgres-secret`. It should skip any changes to credentials because they're not change. And change is not supported afaik.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1900", GitCommit:"008fd38bf3dc201bebdd4fe26edf9bf87478309a", GitTreeState:"clean", BuildDate:"2021-04-14T09:22:08Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```

**Additional context**
./.
