### ISSUE TITLE
[Bitnami/cassandra] How to enable auditLogs in cassandra!

### ISSUE THREAD

**Issue by AkashRajvanshi** [bitnami/charts#6512]
**Which chart**:
The name (and version) of the affected chart.
Cassandra ( chart version 7.5.7 ) 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Hey, I want to enable the audit logs in Cassandra, but directly it is not supported in Cassandra >4. So, if anyone can help me out with this?

**Describe alternatives you've considered**

**Additional context**

**Comment by carrodher** [comment]
Hi, I'm sorry but it seems this feature is not available in the Helm Chart. At this moment the version used by the Helm Chart is Cassandra 3.11.10, which is the latest stable version; when Cassandra 4.x.x is released by the upstream maintainers, the Helm Chart will be updated to use the latest version.

Can you provide more info about how audit logging can be enabled in Cassandra itself (no in the Helm Chart but in Cassandra as an application)?

**Comment by AkashRajvanshi** [comment]
I found this to set up audit logs in Cassandra 3.11 or below. 

https://github.com/Ericsson/ecaudit
https://github.com/Ericsson/ecaudit/blob/master/doc/install.md

### Installation Guide of this ecaudit
---
Deploy Plug-In Jar File
Place the ecAudit jar file in your $CASSANDRA_HOME/lib/ directory. Get the official releases from Maven Central.

Enable Plug-In
The ecAudit plug-in is enabled by configuring a few different plug-in settings in Cassandra.

```bash
cassandra.yaml
Change the following settings in your cassandra.yaml.

authenticator: com.ericsson.bss.cassandra.ecaudit.auth.AuditAuthenticator
authorizer: com.ericsson.bss.cassandra.ecaudit.auth.AuditAuthorizer
role_manager: com.ericsson.bss.cassandra.ecaudit.auth.AuditRoleManager
```

By default the AuditAuthenticator, AuditAuthorizer and AuditRoleManager delegates operations to the standard PasswordAuthenticator, CassandraAuthorizer and CassandraRoleManager respectively. All configuration options and recommendations for the standard plug-ins applies for the Audit plug-ins as well. For instance, remember to increase the replication factor of the system_auth keyspace. Consult the Cassandra configuration documentation for details.

cassandra-env.sh
Add the following JVM option to your cassandra-env.sh or your cassandra.in.sh.

Note: If you configure these settings in your cassandra-env.sh, consider that the JVM_EXTRA_OPTS variable is consumed at the end of the file, so make sure to add the following lines before they are consumed.

```bash
JVM_EXTRA_OPTS="$JVM_EXTRA_OPTS -Dcassandra.custom_query_handler_class=com.ericsson.bss.cassandra.ecaudit.handler.AuditQueryHandler"
JVM_EXTRA_OPTS="$JVM_EXTRA_OPTS -da:net.openhft..."
```

can you please guide me on how I set this up with bitnami-cassandra?

I followed this steps:

```yaml
jvm:
  extraOpts: '-Dcassandra.custom_query_handler_class=com.ericsson.bss.cassandra.ecaudit.handler.AuditQueryHandler -da:net.openhft...'

extraEnvVars:
  - name: CASSANDRA_AUTHENTICATOR
    value: com.ericsson.bss.cassandra.ecaudit.auth.AuditAuthenticator
  - name: CASSANDRA_AUTHORIZER
    value: com.ericsson.bss.cassandra.ecaudit.auth.AuditAuthorizer
```
 
Is this right? and how should I use `role_manager`? is there is some env variable for this?
