### ISSUE TITLE
Feature request - prometheus metrics in tomcat chart.

### ISSUE THREAD

**Issue by cache-sk** [bitnami/charts#6517]
**Which chart**:
bitnami/tomcat

**Describe the solution you'd like**
Add prometheus metrics to tomcat chart, or add working example to README.md, how to use bitnami/jmx-exporter (or alternative) as sidecar.

**Describe alternatives you've considered**
Can't figure it out, how to get it work as sidecar defined in values so it can be deployed as one helm install.

Thanks.

**Comment by migruiz4** [comment]
Hi @cache-sk,

I have created an internal task to evaluate your feature request.

Meanwhile, the `jmx-exporter` can be configured using the following values.yaml:
```yaml
extraVolumes:
  - name: jmx-config
    configMap:
      name: jmx-configuration

sidecars:
  - name: jmx-exporter
    image: bitnami/jmx-exporter
    imagePullPolicy: IfNotPresent
    command:
      - java
      - -XX:+UnlockExperimentalVMOptions
      - -XX:+UseCGroupMemoryLimitForHeap
      - -XX:MaxRAMFraction=1
      - -XshowSettings:vm
      - -jar
      - jmx_prometheus_httpserver.jar
      - "5556"
      - /etc/jmx-tomcat/jmx-tomcat-prometheus.yml
    ports:
      - name: metrics
        containerPort: 5556
    volumeMounts:
      - name: jmx-config
        mountPath: /etc/jmx-tomcat

extraDeploy: |-
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: jmx-configuration
      labels: {{- include "common.labels.standard" . | nindent 2 }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
        {{- end }}
        app.kubernetes.io/component: metrics
    data:
      jmx-tomcat-prometheus.yml: |-
        lowercaseOutputLabelNames: true
        lowercaseOutputName: true
        rules:
        - pattern: 'Catalina<type=GlobalRequestProcessor, name=\"(\w+-\w+)-(\d+)\"><>(\w+):'
          name: tomcat_$3_total
          labels:
            port: "$2"
            protocol: "$1"
          help: Tomcat global $3
          type: COUNTER
        - pattern: 'Catalina<j2eeType=Servlet, WebModule=//([-a-zA-Z0-9+&@#/%?=~_|!:.,;]*[-a-zA-Z0-9+&@#/%=~_|]), name=([-a-zA-Z0-9+/$%~_-|!.]*), J2EEApplication=none, J2EEServer=none><>(requestCount|maxTime|processingTime|errorCount):'
          name: tomcat_servlet_$3_total
          labels:
            module: "$1"
            servlet: "$2"
          help: Tomcat servlet $3 total
          type: COUNTER
        - pattern: 'Catalina<type=ThreadPool, name="(\w+-\w+)-(\d+)"><>(currentThreadCount|currentThreadsBusy|keepAliveCount|pollerThreadCount|connectionCount):'
          name: tomcat_threadpool_$3
          labels:
            port: "$2"
            protocol: "$1"
          help: Tomcat threadpool $3
          type: GAUGE
        - pattern: 'Catalina<type=Manager, host=([-a-zA-Z0-9+&@#/%?=~_|!:.,;]*[-a-zA-Z0-9+&@#/%=~_|]), context=([-a-zA-Z0-9+/$%~_-|!.]*)><>(processingTime|sessionCounter|rejectedSessions|expiredSessions):'
          name: tomcat_session_$3_total
          labels:
            context: "$2"
            host: "$1"
          help: Tomcat session $3 total
          type: COUNTER
```

For the JMX Exporter configuration, I used this example: https://github.com/prometheus/jmx_exporter/blob/master/example_configs/tomcat.yml
But you can adapt it to your needs.

As you may have noticed, this requires the sidecar container feature to be fixed first.

**Comment by cache-sk** [comment]
Thanks for example @migruiz4 , will try that!

**Comment by juan131** [comment]
Please keep us updated and let us know if the JMX exporter worked for you @cache-sk

**Comment by cache-sk** [comment]
Sorry for late reply @juan131, but i didn't have time to test it yet. We are in evaluation pre-migration process and have too much to test/try. I hope i will find time next week and will update, if it works as expected.

**Comment by cache-sk** [comment]
Hello again. 

At first, I want to thank you all again for your effort.

We still don't have properly configured and working enviroment, but i had time to test-install @migruiz4 's example.

It will start, but it seems pretty empty:

```
# HELP jmx_exporter_build_info A metric with a constant '1' value labeled with the version of the JMX exporter.
# TYPE jmx_exporter_build_info gauge
jmx_exporter_build_info{version="0.15.0",name="jmx_prometheus_httpserver",} 1.0
# HELP jmx_config_reload_failure_total Number of times configuration have failed to be reloaded.
# TYPE jmx_config_reload_failure_total counter
jmx_config_reload_failure_total 0.0
# HELP jmx_scrape_duration_seconds Time this JMX scrape took, in seconds.
# TYPE jmx_scrape_duration_seconds gauge
jmx_scrape_duration_seconds 0.01714767
# HELP jmx_scrape_error Non-zero if this scrape failed.
# TYPE jmx_scrape_error gauge
jmx_scrape_error 0.0
# HELP jmx_scrape_cached_beans Number of beans with their matching rule cached
# TYPE jmx_scrape_cached_beans gauge
jmx_scrape_cached_beans 0.0
# HELP jmx_config_reload_success_total Number of times configuration have successfully been reloaded.
# TYPE jmx_config_reload_success_total counter
jmx_config_reload_success_total 0.0
# HELP jmx_config_reload_failure_created Number of times configuration have failed to be reloaded.
# TYPE jmx_config_reload_failure_created gauge
jmx_config_reload_failure_created 1.62317078765E9
# HELP jmx_config_reload_success_created Number of times configuration have successfully been reloaded.
# TYPE jmx_config_reload_success_created gauge
jmx_config_reload_success_created 1.623170787643E9
```

Doesn't seem like it will populate jmx exporter grafana dasboard..

Second problem is, if we want multiple replicas.. There are no agregated service (if I named it correctly, i am total beginner with this stuff), like in your memcached chart for example..

**Comment by migruiz4** [comment]
Hi @cache-sk,

Indeed, the previous configuration I provided was not enough to have Tomcat metrics exported.

I made some further testing using the following values.yaml:
```yaml
extraVolumes: |-
  - name: jmx-config
    configMap:
      name: {{ template "common.names.fullname" . }}-metrics
extraEnvVars:
  - name: CATALINA_OPTS
    value: "-Dcom.sun.management.jmxremote -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.rmi.port=9000 -Dcom.sun.management.jmxremote.port=9000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false"
sidecars:
  - name: jmx-exporter
    image: bitnami/jmx-exporter
    imagePullPolicy: IfNotPresent
    command:
      - java
      - -XX:+UnlockExperimentalVMOptions
      - -XX:+UseCGroupMemoryLimitForHeap
      - -XX:MaxRAMFraction=1
      - -XshowSettings:vm
      - -jar
      - jmx_prometheus_httpserver.jar
      - "5556"
      - /etc/jmx-tomcat/jmx-tomcat-prometheus.yml
    ports:
      - name: metrics
        containerPort: 5556
    volumeMounts:
      - name: jmx-config
        mountPath: /etc/jmx-tomcat

extraDeploy:
  - |
    apiVersion: v1
    kind: Service
    metadata:
      name: {{ template "common.names.fullname" . }}-metrics
      namespace: {{ .Release.Namespace }}
      labels: {{- include "common.labels.standard" . | nindent 4 }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 6 }}
        {{- end }}
        app.kubernetes.io/component: metrics
    spec:
      type: ClusterIP
      ports:
        - name: metrics
          port: 5556
          targetPort: metrics
      selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ template "common.names.fullname" . }}-metrics
      labels: {{- include "common.labels.standard" . | nindent 4 }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 6 }}
        {{- end }}
        app.kubernetes.io/component: metrics
    data:
      jmx-tomcat-prometheus.yml: |-
        jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:9000/jmxrmi
        ssl: false
        lowercaseOutputLabelNames: true
        lowercaseOutputName: true
        rules:
        - pattern: 'Catalina<type=GlobalRequestProcessor, name=\"(\w+-\w+)-(\d+)\"><>(\w+):'
          name: tomcat_$3_total
          labels:
            port: "$2"
            protocol: "$1"
          help: Tomcat global $3
          type: COUNTER
        - pattern: 'Catalina<j2eeType=Servlet, WebModule=//([-a-zA-Z0-9+&@#/%?=~_|!:.,;]*[-a-zA-Z0-9+&@#/%=~_|]), name=([-a-zA-Z0-9+/$%~_-|!.]*), J2EEApplication=none, J2EEServer=none><>(requestCount|maxTime|processingTime|errorCount):'
          name: tomcat_servlet_$3_total
          labels:
            module: "$1"
            servlet: "$2"
          help: Tomcat servlet $3 total
          type: COUNTER
        - pattern: 'Catalina<type=ThreadPool, name="(\w+-\w+)-(\d+)"><>(currentThreadCount|currentThreadsBusy|keepAliveCount|pollerThreadCount|connectionCount):'
          name: tomcat_threadpool_$3
          labels:
            port: "$2"
            protocol: "$1"
          help: Tomcat threadpool $3
          type: GAUGE
        - pattern: 'Catalina<type=Manager, host=([-a-zA-Z0-9+&@#/%?=~_|!:.,;]*[-a-zA-Z0-9+&@#/%=~_|]), context=([-a-zA-Z0-9+/$%~_-|!.]*)><>(processingTime|sessionCounter|rejectedSessions|expiredSessions):'
          name: tomcat_session_$3_total
          labels:
            context: "$2"
            host: "$1"
          help: Tomcat session $3 total
          type: COUNTER
```

Changes I made:
- Added CATALINA_OPTS adding the required settings to enable remote JMX metrics (https://github.com/bitnami/bitnami-docker-tomcat/issues/80).
- Modified `jmx-tomcat-prometheus.yml` adding `jmxUrl`.
- Added the `*-metrics` service to the `extraDeploy` list

The output now includes Tomcat metrics:
```
I have no name!@tomcat-575cd869-gpbbt:/$ curl tomcat-metrics:5556
# HELP jmx_exporter_build_info A metric with a constant '1' value labeled with the version of the JMX exporter.
# TYPE jmx_exporter_build_info gauge
jmx_exporter_build_info{version="0.15.0",name="jmx_prometheus_httpserver",} 1.0
# HELP jmx_config_reload_failure_total Number of times configuration have failed to be reloaded.
# TYPE jmx_config_reload_failure_total counter
jmx_config_reload_failure_total 0.0
# HELP jmx_config_reload_success_total Number of times configuration have successfully been reloaded.
# TYPE jmx_config_reload_success_total counter
jmx_config_reload_success_total 0.0
# HELP tomcat_bytesreceived_total Tomcat global bytesReceived
# TYPE tomcat_bytesreceived_total counter
tomcat_bytesreceived_total{port="8080",protocol="http-nio",} 0.0
# HELP tomcat_errorcount_total Tomcat global errorCount
# TYPE tomcat_errorcount_total counter
tomcat_errorcount_total{port="8080",protocol="http-nio",} 0.0
# HELP tomcat_requestcount_total Tomcat global requestCount
# TYPE tomcat_requestcount_total counter
tomcat_requestcount_total{port="8080",protocol="http-nio",} 62.0
# HELP tomcat_session_sessioncounter_total Tomcat session sessionCounter total
# TYPE tomcat_session_sessioncounter_total counter
tomcat_session_sessioncounter_total{context="/manager",host="localhost",} 0.0
tomcat_session_sessioncounter_total{context="/docs",host="localhost",} 0.0
tomcat_session_sessioncounter_total{context="/",host="localhost",} 0.0
tomcat_session_sessioncounter_total{context="/host-manager",host="localhost",} 0.0
tomcat_session_sessioncounter_total{context="/examples",host="localhost",} 0.0
# HELP tomcat_session_rejectedsessions_total Tomcat session rejectedSessions total
# TYPE tomcat_session_rejectedsessions_total counter
tomcat_session_rejectedsessions_total{context="/manager",host="localhost",} 0.0
tomcat_session_rejectedsessions_total{context="/docs",host="localhost",} 0.0
tomcat_session_rejectedsessions_total{context="/",host="localhost",} 0.0
tomcat_session_rejectedsessions_total{context="/host-manager",host="localhost",} 0.0
tomcat_session_rejectedsessions_total{context="/examples",host="localhost",} 0.0
# HELP tomcat_session_expiredsessions_total Tomcat session expiredSessions total
# TYPE tomcat_session_expiredsessions_total counter
tomcat_session_expiredsessions_total{context="/manager",host="localhost",} 0.0
tomcat_session_expiredsessions_total{context="/docs",host="localhost",} 0.0
tomcat_session_expiredsessions_total{context="/",host="localhost",} 0.0
tomcat_session_expiredsessions_total{context="/host-manager",host="localhost",} 0.0
tomcat_session_expiredsessions_total{context="/examples",host="localhost",} 0.0
# HELP tomcat_session_processingtime_total Tomcat session processingTime total
# TYPE tomcat_session_processingtime_total counter
tomcat_session_processingtime_total{context="/manager",host="localhost",} 0.0
tomcat_session_processingtime_total{context="/docs",host="localhost",} 0.0
tomcat_session_processingtime_total{context="/",host="localhost",} 0.0
tomcat_session_processingtime_total{context="/host-manager",host="localhost",} 0.0
tomcat_session_processingtime_total{context="/examples",host="localhost",} 0.0
# HELP tomcat_servlet_processingtime_total Tomcat servlet processingTime total
# TYPE tomcat_servlet_processingtime_total counter
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="stock",} 0.0
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="RequestHeaderExample",} 0.0
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="SessionExample",} 0.0
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="ServletToJsp",} 0.0
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="jsp",} 0.0
tomcat_servlet_processingtime_total{module="localhost/host-manager",servlet="HostManager",} 0.0
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="numberwriter",} 0.0
tomcat_servlet_processingtime_total{module="localhost/manager",servlet="default",} 0.0
tomcat_servlet_processingtime_total{module="localhost/",servlet="default",} 0.0
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="simpleimagepush",} 0.0
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="CompressionFilterTestServlet",} 0.0
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="async3",} 0.0
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="async2",} 0.0
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="async1",} 0.0
tomcat_servlet_processingtime_total{module="localhost/host-manager",servlet="default",} 0.0
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="async0",} 0.0
tomcat_servlet_processingtime_total{module="localhost/host-manager",servlet="HTMLHostManager",} 0.0
tomcat_servlet_processingtime_total{module="localhost/manager",servlet="Manager",} 0.0
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="RequestParamExample",} 0.0
tomcat_servlet_processingtime_total{module="localhost/docs",servlet="jsp",} 0.0
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="default",} 0.0
tomcat_servlet_processingtime_total{module="localhost/",servlet="jsp",} 1159.0
tomcat_servlet_processingtime_total{module="localhost/host-manager",servlet="jsp",} 0.0
tomcat_servlet_processingtime_total{module="localhost/manager",servlet="Status",} 0.0
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="responsetrailer",} 0.0
tomcat_servlet_processingtime_total{module="localhost/manager",servlet="JMXProxy",} 0.0
tomcat_servlet_processingtime_total{module="localhost/manager",servlet="HTMLManager",} 0.0
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="CookieExample",} 0.0
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="bytecounter",} 0.0
tomcat_servlet_processingtime_total{module="localhost/manager",servlet="jsp",} 0.0
tomcat_servlet_processingtime_total{module="localhost/docs",servlet="default",} 0.0
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="RequestInfoExample",} 0.0
tomcat_servlet_processingtime_total{module="localhost/examples",servlet="HelloWorldExample",} 0.0
# HELP tomcat_threadpool_connectioncount Tomcat threadpool connectionCount
# TYPE tomcat_threadpool_connectioncount gauge
tomcat_threadpool_connectioncount{port="8080",protocol="http-nio",} 1.0
# HELP tomcat_maxtime_total Tomcat global maxTime
# TYPE tomcat_maxtime_total counter
tomcat_maxtime_total{port="8080",protocol="http-nio",} 1139.0
# HELP tomcat_bytessent_total Tomcat global bytesSent
# TYPE tomcat_bytessent_total counter
tomcat_bytessent_total{port="8080",protocol="http-nio",} 690866.0
# HELP tomcat_servlet_errorcount_total Tomcat servlet errorCount total
# TYPE tomcat_servlet_errorcount_total counter
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="stock",} 0.0
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="RequestHeaderExample",} 0.0
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="SessionExample",} 0.0
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="ServletToJsp",} 0.0
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="jsp",} 0.0
tomcat_servlet_errorcount_total{module="localhost/host-manager",servlet="HostManager",} 0.0
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="numberwriter",} 0.0
tomcat_servlet_errorcount_total{module="localhost/manager",servlet="default",} 0.0
tomcat_servlet_errorcount_total{module="localhost/",servlet="default",} 0.0
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="simpleimagepush",} 0.0
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="CompressionFilterTestServlet",} 0.0
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="async3",} 0.0
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="async2",} 0.0
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="async1",} 0.0
tomcat_servlet_errorcount_total{module="localhost/host-manager",servlet="default",} 0.0
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="async0",} 0.0
tomcat_servlet_errorcount_total{module="localhost/host-manager",servlet="HTMLHostManager",} 0.0
tomcat_servlet_errorcount_total{module="localhost/manager",servlet="Manager",} 0.0
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="RequestParamExample",} 0.0
tomcat_servlet_errorcount_total{module="localhost/docs",servlet="jsp",} 0.0
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="default",} 0.0
tomcat_servlet_errorcount_total{module="localhost/",servlet="jsp",} 0.0
tomcat_servlet_errorcount_total{module="localhost/host-manager",servlet="jsp",} 0.0
tomcat_servlet_errorcount_total{module="localhost/manager",servlet="Status",} 0.0
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="responsetrailer",} 0.0
tomcat_servlet_errorcount_total{module="localhost/manager",servlet="JMXProxy",} 0.0
tomcat_servlet_errorcount_total{module="localhost/manager",servlet="HTMLManager",} 0.0
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="CookieExample",} 0.0
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="bytecounter",} 0.0
tomcat_servlet_errorcount_total{module="localhost/manager",servlet="jsp",} 0.0
tomcat_servlet_errorcount_total{module="localhost/docs",servlet="default",} 0.0
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="RequestInfoExample",} 0.0
tomcat_servlet_errorcount_total{module="localhost/examples",servlet="HelloWorldExample",} 0.0
# HELP tomcat_servlet_maxtime_total Tomcat servlet maxTime total
# TYPE tomcat_servlet_maxtime_total counter
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="stock",} 0.0
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="RequestHeaderExample",} 0.0
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="SessionExample",} 0.0
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="ServletToJsp",} 0.0
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="jsp",} 0.0
tomcat_servlet_maxtime_total{module="localhost/host-manager",servlet="HostManager",} 0.0
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="numberwriter",} 0.0
tomcat_servlet_maxtime_total{module="localhost/manager",servlet="default",} 0.0
tomcat_servlet_maxtime_total{module="localhost/",servlet="default",} 0.0
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="simpleimagepush",} 0.0
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="CompressionFilterTestServlet",} 0.0
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="async3",} 0.0
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="async2",} 0.0
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="async1",} 0.0
tomcat_servlet_maxtime_total{module="localhost/host-manager",servlet="default",} 0.0
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="async0",} 0.0
tomcat_servlet_maxtime_total{module="localhost/host-manager",servlet="HTMLHostManager",} 0.0
tomcat_servlet_maxtime_total{module="localhost/manager",servlet="Manager",} 0.0
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="RequestParamExample",} 0.0
tomcat_servlet_maxtime_total{module="localhost/docs",servlet="jsp",} 0.0
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="default",} 0.0
tomcat_servlet_maxtime_total{module="localhost/",servlet="jsp",} 1100.0
tomcat_servlet_maxtime_total{module="localhost/host-manager",servlet="jsp",} 0.0
tomcat_servlet_maxtime_total{module="localhost/manager",servlet="Status",} 0.0
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="responsetrailer",} 0.0
tomcat_servlet_maxtime_total{module="localhost/manager",servlet="JMXProxy",} 0.0
tomcat_servlet_maxtime_total{module="localhost/manager",servlet="HTMLManager",} 0.0
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="CookieExample",} 0.0
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="bytecounter",} 0.0
tomcat_servlet_maxtime_total{module="localhost/manager",servlet="jsp",} 0.0
tomcat_servlet_maxtime_total{module="localhost/docs",servlet="default",} 0.0
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="RequestInfoExample",} 0.0
tomcat_servlet_maxtime_total{module="localhost/examples",servlet="HelloWorldExample",} 0.0
# HELP tomcat_servlet_requestcount_total Tomcat servlet requestCount total
# TYPE tomcat_servlet_requestcount_total counter
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="stock",} 0.0
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="RequestHeaderExample",} 0.0
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="SessionExample",} 0.0
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="ServletToJsp",} 0.0
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="jsp",} 0.0
tomcat_servlet_requestcount_total{module="localhost/host-manager",servlet="HostManager",} 0.0
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="numberwriter",} 0.0
tomcat_servlet_requestcount_total{module="localhost/manager",servlet="default",} 0.0
tomcat_servlet_requestcount_total{module="localhost/",servlet="default",} 0.0
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="simpleimagepush",} 0.0
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="CompressionFilterTestServlet",} 0.0
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="async3",} 0.0
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="async2",} 0.0
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="async1",} 0.0
tomcat_servlet_requestcount_total{module="localhost/host-manager",servlet="default",} 0.0
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="async0",} 0.0
tomcat_servlet_requestcount_total{module="localhost/host-manager",servlet="HTMLHostManager",} 0.0
tomcat_servlet_requestcount_total{module="localhost/manager",servlet="Manager",} 0.0
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="RequestParamExample",} 0.0
tomcat_servlet_requestcount_total{module="localhost/docs",servlet="jsp",} 0.0
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="default",} 0.0
tomcat_servlet_requestcount_total{module="localhost/",servlet="jsp",} 62.0
tomcat_servlet_requestcount_total{module="localhost/host-manager",servlet="jsp",} 0.0
tomcat_servlet_requestcount_total{module="localhost/manager",servlet="Status",} 0.0
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="responsetrailer",} 0.0
tomcat_servlet_requestcount_total{module="localhost/manager",servlet="JMXProxy",} 0.0
tomcat_servlet_requestcount_total{module="localhost/manager",servlet="HTMLManager",} 0.0
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="CookieExample",} 0.0
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="bytecounter",} 0.0
tomcat_servlet_requestcount_total{module="localhost/manager",servlet="jsp",} 0.0
tomcat_servlet_requestcount_total{module="localhost/docs",servlet="default",} 0.0
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="RequestInfoExample",} 0.0
tomcat_servlet_requestcount_total{module="localhost/examples",servlet="HelloWorldExample",} 0.0
# HELP tomcat_threadpool_keepalivecount Tomcat threadpool keepAliveCount
# TYPE tomcat_threadpool_keepalivecount gauge
tomcat_threadpool_keepalivecount{port="8080",protocol="http-nio",} 1.0
# HELP tomcat_threadpool_currentthreadcount Tomcat threadpool currentThreadCount
# TYPE tomcat_threadpool_currentthreadcount gauge
tomcat_threadpool_currentthreadcount{port="8080",protocol="http-nio",} 10.0
# HELP tomcat_threadpool_currentthreadsbusy Tomcat threadpool currentThreadsBusy
# TYPE tomcat_threadpool_currentthreadsbusy gauge
tomcat_threadpool_currentthreadsbusy{port="8080",protocol="http-nio",} 0.0
# HELP tomcat_processingtime_total Tomcat global processingTime
# TYPE tomcat_processingtime_total counter
tomcat_processingtime_total{port="8080",protocol="http-nio",} 1271.0
# HELP jmx_scrape_duration_seconds Time this JMX scrape took, in seconds.
# TYPE jmx_scrape_duration_seconds gauge
jmx_scrape_duration_seconds 0.3606911
# HELP jmx_scrape_error Non-zero if this scrape failed.
# TYPE jmx_scrape_error gauge
jmx_scrape_error 0.0
# HELP jmx_scrape_cached_beans Number of beans with their matching rule cached
# TYPE jmx_scrape_cached_beans gauge
jmx_scrape_cached_beans 0.0
# HELP jmx_config_reload_failure_created Number of times configuration have failed to be reloaded.
# TYPE jmx_config_reload_failure_created gauge
jmx_config_reload_failure_created 1.623228562927E9
# HELP jmx_config_reload_success_created Number of times configuration have successfully been reloaded.
# TYPE jmx_config_reload_success_created gauge
jmx_config_reload_success_created 1.623228562925E9
```

**Comment by cache-sk** [comment]
Hi @migruiz4,

big thanks for your last post, this looks very promising - successfully deployed and metrics is served.

Can't wait to test it with prometheus (not ready so far at our enviroment).

**Comment by migruiz4** [comment]
You are welcome @cache-sk! I'm happy you found my comment helpful.

I would really really appreciate your feedback after testing it with Prometheus.

**Comment by cache-sk** [comment]
Hello @migruiz4, little update.

I now have little deeper knowledge, how it works and now i understand (again, thanks for your help), why there is no metrics in tomcat chart - there is no adhoc compatibile grafana dashboard. There are few, but without proper jmx exporter config, they are useless (and probably suited for older tomcat version)..

So, as proof of concept, i managed to partially work [this jmx dashboard](https://grafana.com/grafana/dashboards/3457) with this configuration:

```
extraVolumes: |-
  - name: jmx-config
    configMap:
      name: {{ template "common.names.fullname" . }}-metrics
extraEnvVars:
  - name: CATALINA_OPTS
    value: "-Dcom.sun.management.jmxremote -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.rmi.port=9000 -Dcom.sun.management.jmxremote.port=9000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false"
sidecars:
  - name: jmx-exporter
    image: bitnami/jmx-exporter
    imagePullPolicy: IfNotPresent
    command:
      - java
      - -XX:+UnlockExperimentalVMOptions
      - -XX:+UseCGroupMemoryLimitForHeap
      - -XX:MaxRAMFraction=1
      - -XshowSettings:vm
      - -jar
      - jmx_prometheus_httpserver.jar
      - "5556"
      - /etc/jmx-tomcat/jmx-tomcat-prometheus.yml
    ports:
      - name: metrics
        containerPort: 5556
    volumeMounts:
      - name: jmx-config
        mountPath: /etc/jmx-tomcat

extraDeploy:
  - |
    apiVersion: v1
    kind: Service
    metadata:
      name: {{ template "common.names.fullname" . }}-metrics
      namespace: {{ .Release.Namespace }}
      labels: {{- include "common.labels.standard" . | nindent 4 }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 6 }}
        {{- end }}
        app.kubernetes.io/component: metrics
    spec:
      type: ClusterIP
      ports:
        - name: metrics
          port: 5556
          targetPort: metrics
      selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ template "common.names.fullname" . }}-metrics
      labels: {{- include "common.labels.standard" . | nindent 4 }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 6 }}
        {{- end }}
        app.kubernetes.io/component: metrics
    data:
      jmx-tomcat-prometheus.yml: |-
        jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:9000/jmxrmi
        ssl: false
        lowercaseOutputLabelNames: true
        lowercaseOutputName: true
        whitelistObjectNames: ["*:*"]
        blacklistObjectNames: []
        rules:
          - pattern: 'java.lang<type=Runtime><>Uptime'
            name: up
            labels:
              job: jmx
          - pattern: '.*'
  - |
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: {{ template "common.names.fullname" . }}
      namespace: {{ .Release.Namespace }}
      labels: {{- include "common.labels.standard" . | nindent 4 }}
    spec:
      selector:
        matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}
          app.kubernetes.io/component: metrics
      endpoints:
        - port: metrics
          path: /
          honorLabels: true
      namespaceSelector:
        matchNames:
          - {{ .Release.Namespace }}
```

If you compare it with your previous configuration, there is added ServiceMonitor for prometheus k8s service discovery (with honorLabels to override job name in "up") and simplified jmx-tomcat-prometheus.yml to export everything with additional "up" for that dashboard instance selection.

So, i can confirm, that this and yours configuration is fully working and exporting and now is't about missing grafana dashboard.
