### ISSUE TITLE
mongodb: After cluster crash mongo has problem with node-affinity

### ISSUE THREAD

**Issue by rstoermer** [bitnami/charts#6525]
Hi,

my cluster had some problems, so alle nodes got recreated. It seems though, that the PV and PVC still exist from when i initially set everything up, which is good, as there is no data loss due to that. However when the pods of the statefulset are recreated, the first pod (master node) fails to claim the PVC, as this is bound to another node. 

I get the message:
` Warning  FailedAttachVolume  2m56s  attachdetach-controller  Multi-Attach error for volume "pvc-2e5a49c3-e1c1-4a08-beb2-34596721ce04" Volume is already exclusively attached to one node and can't be attached to another`

The pod is therefore stuck in the Pending state. It is running in: Node:           kube-dev-a1/10.0.0.3

When looking at the PVs `pvc-2e5a49c3-e1c1-4a08-beb2-34596721ce04` underlying PVC `datadir-main-mongo-0` I can see the following:

`               volume.kubernetes.io/selected-node: kube-dev-a2`

Why is this not changed automatically? It can always happen that a pod is recreated on another node, right?

My values.yaml

```
mongodb:
    enabled: true
    auth:
        enabled: false
    fullnameOverride: main-mongo
    image:
        tag: 4.4-debian-10
    architecture: replicaset
    tls:
        enabled: false
    replicaCount: 3
    replicaSetName: rs0
    persistence:
        storageClass: hcloud-volumes
        mountPath: /bitnami/mongodb
        size: 200Gi
        accessMode: ReadWriteOnce
    service:
        nameOverride: main-mongo-service-headless
```
