### ISSUE TITLE
Problem with dns thanos-query

### ISSUE THREAD

**Issue by neodani** [bitnami/charts#6539]
I'm installing thanos with helm chart to save data into GCS

````
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
prometheus      default         1               2021-06-02 12:20:33.0527409 +0200 CEST  deployed        prometheus-14.1.0       2.26.0
thanos          default         2               2021-06-02 12:40:23.7960313 +0200 CEST  deployed        thanos-3.17.3           0.20.2
````

```
helm upgrade --install --values thanos.yaml thanos bitnami/thanos
````

```
prometheus-alertmanager-54788dccb4-tdntm         2/2     Running   0          27m
prometheus-kube-state-metrics-5b8f9bdbbd-9nq4z   1/1     Running   0          27m
prometheus-node-exporter-fcqw2                   1/1     Running   0          27m
prometheus-node-exporter-xgs7r                   1/1     Running   0          27m
prometheus-pushgateway-785c66bccb-bv5p5          1/1     Running   0          27m
prometheus-server-0                              2/2     Running   0          27m
thanos-bucketweb-585b494df7-v9khj                1/1     Running   0          24m
thanos-compactor-68448f84bf-pqlwj                1/1     Running   0          24m
thanos-query-d75dd84b6-9pj9k                     1/1     Running   0          7m10s
thanos-query-frontend-9bc969845-snqmd            1/1     Running   0          24m
thanos-storegateway-0                            1/1     Running   0          24m
```

Configuration
```
objstoreConfig: |-
  type: GCS
  config:
    bucket: "thanos-prometheus-01"
    service_account: |-
     confidential....
      }
querier:
  dnsDiscovery:
    enabled: true
    #sidecarsService: prometheus-server
    sidecarsService: prometheus-server-headless
    sidecarsNamespace: default
compactor:
  enabled: true
  retentionResolutionRaw: 30d  # Full resolution
  retentionResolution5m: 60d   # 1 data point every 5m
  retentionResolution1h: 10y   # 1 data point per hour
storegateway:
  enabled: true
bucketweb:
  enabled: true
```

Container thanos-query

```
Containers:
  query:
    Container ID:  containerd://92a52229f24f6dff8b08759cc78b295462125b8d0c681cc0f0e82ad9cbad8061
    Image:         docker.io/bitnami/thanos:0.20.2-scratch-r0
    Image ID:      docker.io/bitnami/thanos@sha256:3e12968d2627ffb27dd9d02d6e877bc30962800087d65af516d594cb514de01f
    Ports:         10902/TCP, 10901/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      query
      --log.level=info
      --log.format=logfmt
      --grpc-address=0.0.0.0:10901
      --http-address=0.0.0.0:10902
      --query.replica-label=replica
      --store=dnssrv+_grpc._tcp.prometheus-server-headless.default.svc.cluster.local
      --store=dnssrv+_grpc._tcp.thanos-storegateway.default.svc.cluster.local
    State:          Running
      Started:      Wed, 02 Jun 2021 12:40:29 +0200
    Ready:          True
    Restart Count:  0
```

Error  Log
```
level=error ts=2021-06-02T10:44:59.706183048Z caller=resolver.go:99 msg="failed to lookup SRV records" host=_grpc._tcp.prometheus-server-headless.default.svc.cluster.local err="lookup _grpc._tcp.prometheus-server-headless.default.svc.cluster.local on 10.100.25.10:53: no such host"
```

Seems it should create automatically this endpoints
      --store=dnssrv+_grpc._tcp.prometheus-server-headless.default.svc.cluster.local
      --store=dnssrv+_grpc._tcp.thanos-storegateway.default.svc.cluster.local

When I try both, only ping the thanos-storegateway

```
[ root@curl:/ ]$ ping _grpc._tcp.prometheus-server-headless.default.svc.cluster.local
ping: bad address '_grpc._tcp.prometheus-server-headless.default.svc.cluster.local'
[ root@curl:/ ]$ ping _grpc._tcp.thanos-storegateway.default.svc.cluster.local
PING _grpc._tcp.thanos-storegateway.default.svc.cluster.local (10.100.25.249): 56 data bytes
^C
--- _grpc._tcp.thanos-storegateway.default.svc.cluster.local ping statistics ---
2 packets transmitted, 0 packets received, 100% packet loss
[ root@curl:/ ]$ ping prometheus-server-headless.default.svc.cluster.local
PING prometheus-server-headless.default.svc.cluster.local (10.75.0.57): 56 data bytes
64 bytes from 10.75.0.57: seq=0 ttl=63 time=0.089 ms
64 bytes from 10.75.0.57: seq=1 ttl=63 time=0.088 ms
^C
--- prometheus-server-headless.default.svc.cluster.local ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.088/0.088/0.089 ms
```

I do not know how to solve the problem, I do not understand why it does not create that dns record, I understand that without that record it is not able to reach the bucket and that is why I do not see content within GCS 

Do you know where is the problem?

Thank you very much
