### ISSUE TITLE
[bitnami/memcached] ClusterIP always set to None

### ISSUE THREAD

**Issue by smarsh-tim** [bitnami/charts#6542]
**Which chart**:
Memcached 5.12.2

**Describe the bug**
The documentation reflects that when using ClusterIP, the default is `nil`. As such, this should allow Kubernetes to assign the ClusterIP, and only be `None` when explicitly defined as so for a headless service.

| Parameter                                | Description                                                                               | Default                                                      |
|------------------------------------------|-------------------------------------------------------------------------------------------|--------------------------------------------------------------|
| `service.type`                           | Kubernetes service type for Memcached                                                     | `ClusterIP`                                                  |
| `service.clusterIP`                      | Specific cluster IP when service type is cluster IP. Use `None` for headless service      | `nil`                                                        |

Instead, the ClusterIP is hard-coded to `None` whenever the `type: ClusterIP`: https://github.com/bitnami/charts/blob/master/bitnami/memcached/templates/service.yaml#L20

**To Reproduce**

1. Create a HelmRelease resource for memcached
2. Under the `values` key, add the following:
   ```yaml
   service:
      type: ClusterIP
      port: 11211
   ```
3. Apply the HelmRelease to your cluster
4. Observe the ClusterIP is set to None

**Expected behavior**
The default value of ClusterIP is expected to be non-existent (`nil`), _not_ `None`. Further, when a static ClusterIP is defined, that static value should be used instead.

**Version of Helm and Kubernetes**:
Helm: v3.5.4
Kubernetes: 1.19.8

**Comment by carrodher** [comment]
It seems the README is not updated, there is not any `service.clusterIP` parameter defined in the values.yaml.
The service type by default is `ClusterIP`:
```yaml
## Service parameters
##
service:
  ## Service type
  ##
  type: ClusterIP
  ## Memcached port
  ##
  port: 11211
```
(same behavior is applied to the service for the metrics).

Then the _service.yaml_ is defined as follows:
```yaml
 apiVersion: v1
 kind: Service
...
 spec:
   type: {{ .Values.service.type }}
   {{- if and (eq .Values.architecture "high-availability") (eq .Values.service.type "ClusterIP") }}
   clusterIP: None
   {{- end }}
```
where the `spec.clusterIP` property is set to `None` when both conditions are true: architecture is "high-availability" and the service type is "ClusterIP". In any other case, this property is not going to be defined.
