### ISSUE TITLE
mariadb-galera crashloopbackoff caused by WSREP failing to load galera.dat and galera.cache

### ISSUE THREAD

**Issue by ahgraber** [bitnami/charts#6545]
Which chart:
bitnami/mariadb-galera

Describe the bug
I deployed the chart with the values (added below), and I cannot get the pods to initialize successfully.  In the logs, it appears the paths to `galera.dat` and `galera.cache` may be broken.

```
[Warning] WSREP: Could not open state file for reading: _**'/bitnami/mariadb/data//grastate.dat'**_
[Note] WSREP: Found saved state: 00000000-0000-0000-0000-000000000000:-1, safe_to_bootstrap: 1
[ERROR] WSREP: Failed to open file _**'/bitnami/mariadb/data//galera.cache'**_: 1 (Operation not permitted)
```

Ultimately, the deployment fails due to CrashLoopBackoff

Complete log:
```
mariadb 15:06:46.71 
6/2/2021 3:06:46 PM mariadb 15:06:46.72 Welcome to the Bitnami mariadb-galera container
6/2/2021 3:06:46 PM mariadb 15:06:46.73 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
6/2/2021 3:06:46 PM mariadb 15:06:46.74 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
6/2/2021 3:06:46 PM mariadb 15:06:46.74 
6/2/2021 3:06:46 PM mariadb 15:06:46.75 INFO  ==> ** Starting MariaDB setup **
6/2/2021 3:06:46 PM mariadb 15:06:46.86 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
6/2/2021 3:07:06 PM mariadb 15:07:06.62 DEBUG ==> Set Galera cluster address to gcomm://
6/2/2021 3:07:06 PM mariadb 15:07:06.98 INFO  ==> Initializing mariadb database
6/2/2021 3:07:06 PM mariadb 15:07:06.99 DEBUG ==> Ensuring expected directories/files exist
6/2/2021 3:07:07 PM mariadb 15:07:07.11 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable or does not exist. Configurations based on environment variables will not be applied for this file.
6/2/2021 3:07:19 PM mariadb 15:07:19.22 DEBUG ==> Cleaning data directory to ensure successfully initialization
6/2/2021 3:07:19 PM Installing MariaDB/MySQL system tables in '/bitnami/mariadb/data' ...
6/2/2021 3:07:28 PM OK
6/2/2021 3:07:28 PM 
6/2/2021 3:07:28 PM To start mysqld at boot time you have to copy
6/2/2021 3:07:28 PM support-files/mysql.server to the right place for your system
6/2/2021 3:07:28 PM 
6/2/2021 3:07:28 PM 
6/2/2021 3:07:28 PM PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
6/2/2021 3:07:28 PM To do so, start the server, then issue the following command:
6/2/2021 3:07:28 PM 
6/2/2021 3:07:28 PM '/opt/bitnami/mariadb/bin/mysql_secure_installation'
6/2/2021 3:07:28 PM 
6/2/2021 3:07:28 PM which will also give you the option of removing the test
6/2/2021 3:07:28 PM databases and anonymous user created by default.  This is
6/2/2021 3:07:28 PM strongly recommended for production servers.
6/2/2021 3:07:28 PM 
6/2/2021 3:07:28 PM See the MariaDB Knowledgebase at https://mariadb.com/kb or the
6/2/2021 3:07:28 PM MySQL manual for more instructions.
6/2/2021 3:07:28 PM 
6/2/2021 3:07:28 PM You can start the MariaDB daemon with:
6/2/2021 3:07:28 PM cd '/opt/bitnami/mariadb' ; /opt/bitnami/mariadb/bin/mysqld_safe --datadir='/bitnami/mariadb/data'
6/2/2021 3:07:28 PM 
6/2/2021 3:07:28 PM You can test the MariaDB daemon with mysql-test-run.pl
6/2/2021 3:07:28 PM cd '/opt/bitnami/mariadb/mysql-test' ; perl mysql-test-run.pl
6/2/2021 3:07:28 PM 
6/2/2021 3:07:28 PM Please report any problems at https://mariadb.org/jira
6/2/2021 3:07:28 PM 
6/2/2021 3:07:28 PM The latest information about MariaDB is available at https://mariadb.org/.
6/2/2021 3:07:28 PM You can find additional information about the MySQL part at:
6/2/2021 3:07:28 PM https://dev.mysql.com
6/2/2021 3:07:28 PM Consider joining MariaDB's strong and vibrant community:
6/2/2021 3:07:28 PM https://mariadb.org/get-involved/
6/2/2021 3:07:28 PM 
6/2/2021 3:07:40 PM mariadb 15:07:40.56 DEBUG ==> Set Galera cluster address to gcomm://
6/2/2021 3:07:40 PM mariadb 15:07:40.59 INFO  ==> Starting mariadb in background
6/2/2021 3:07:40 PM 2021-06-02 15:07:40 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.5.10-MariaDB-log) starting as process 205 ...
6/2/2021 3:07:40 PM 2021-06-02 15:07:40 0 [Note] WSREP: Loading provider /opt/bitnami/mariadb/lib/libgalera_smm.so initial position: 00000000-0000-0000-0000-000000000000:-1
6/2/2021 3:07:40 PM 2021-06-02 15:07:40 0 [Note] WSREP: wsrep_load(): loading provider library '/opt/bitnami/mariadb/lib/libgalera_smm.so'
6/2/2021 3:07:40 PM 2021-06-02 15:07:40 0 [Note] WSREP: wsrep_load(): Galera 4.8(rXXXX) by Codership Oy <info@codership.com> loaded successfully.
6/2/2021 3:07:40 PM 2021-06-02 15:07:40 0 [Note] WSREP: CRC-32C: using 64-bit x86 acceleration.
6/2/2021 3:07:40 PM 2021-06-02 15:07:40 0 [Warning] WSREP: Could not open state file for reading: '/bitnami/mariadb/data//grastate.dat'
6/2/2021 3:07:40 PM 2021-06-02 15:07:40 0 [Note] WSREP: Found saved state: 00000000-0000-0000-0000-000000000000:-1, safe_to_bootstrap: 1
6/2/2021 3:07:40 PM 2021-06-02 15:07:40 0 [ERROR] WSREP: Failed to open file '/bitnami/mariadb/data//galera.cache': 1 (Operation not permitted)
6/2/2021 3:07:40 PM 	 at /bitnami/blacksmith-sandox/libgalera-26.4.8/galerautils/src/gu_fdesc.cpp:constructor_common():141
6/2/2021 3:07:40 PM 2021-06-02 15:07:40 0 [ERROR] WSREP: Failed to create a new provider '/opt/bitnami/mariadb/lib/libgalera_smm.so' with options '': Failed to initialize wsrep provider
6/2/2021 3:07:40 PM 2021-06-02 15:07:40 0 [ERROR] WSREP: Failed to load provider
6/2/2021 3:07:40 PM 2021-06-02 15:07:40 0 [ERROR] Aborting
```

My `values.yaml`:

```yaml
## svc properties
service:
  ## Kubernetes service type and port number
  type: ClusterIP
  port: 3306

## An array to add extra environment variables
extraEnvVars:
 - name: TZ
   value: "America/New_York"
 - name: BITNAMI_DEBUG
   value: "true"

## Pod Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext:
  enabled: true
  fsGroup: 0  # 1001
  runAsUser: 0  # 1001

## Use existing secret (ignores rootUser.password, db.password, and galera.mariabackup.password)
existingSecret: 'mariadb-secret'

## Number of replicas (odd - 3 or 5 typical).  Do not exceed node count.
replicaCount: 3

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
persistence:
  ## If true, use a Persistent Volume Claim, If false, use emptyDir
  enabled: true
  ## mountPath is the internal directory to mount
  # mountPath: /bitnami/mariadb
  ## Persistent Volume Storage Class
  storageClass: nfs-client-db
  ## Persistent Volume size
  size: 8Gi
```

For reference, this exact storage class and PV/PVC setup works just fine on the standard MariaDB chart.
