### ISSUE TITLE
[bitnami/airflow] add ServiceMonitor if servicemonitor enabled true to automatically scrape exporter metrics

### ISSUE THREAD

**Issue by iamsudip** [bitnami/charts#6552]
**Which chart**:
airflow all versions

**Is your feature request related to a problem? Please describe.**
Metrics exporting

**Describe the solution you'd like**
add a flag in values.yaml metrics.serviceMonitor: true/false, if enabled we will create the following manifest
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: airflow-metrics
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      name: airflow-exporter
```

**Describe alternatives you've considered**
I created the above servicemonitor manually
