### ISSUE TITLE
[bitnami/wordpress] custom htaccess ignored

### ISSUE THREAD

**Issue by mh0rst** [bitnami/charts#6553]
**Which chart**:
wordpress-11.0.12

**Describe the bug**
When configuring a custom htaccess config map with `customHTAccessCM`, the htaccess file is ignored by apache. I could verify that the wordpress-htaccess.conf file is mounted in the pod and available at `/htaccess/wordpress-htaccess.conf`, but it has no effect. After I manually copied the file to the `/opt/bitnami/wordpress` directory using `cp htaccess/wordpress-htaccess.conf /opt/bitnami/wordpress/.htaccess`, the htaccess file works as expected.

Neither this chart repository nor the bitnami-docker-wordpress repository contains any reference to the mounted `/htaccess` directory, which might be the issue here.

I have not changed the values of `htaccessPersistenceEnabled`or `allowOverrideNone`.

**To Reproduce**

1. Create a configmap with a `wordpress-htaccess.conf` file containing commands with an easily verifiable effect on wordpress, e.g. `Deny from all`.
2. Use that configmap with the `customHTAccessCM` value in the wordpress chart.
3. Upgrade the helm application

**Expected behavior**
The configured htaccess data is considered by apache.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-13T02:40:46Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
The htaccess file was intended to introduce IP whitelisting to the admin pages. I also tried to use the `customPostInitScripts` to write a .htaccess file into the `/opt/bitnami/wordpress` directory, but those scripts run only on installation of course and the whitelisting wouldn't work after an update.

**Comment by mh0rst** [comment]
I was able to work around this issue using the following values instead of `custpmHTAccessCM`:
```
extraVolumes:
  - name: custom-htaccess
    configMap:
      name: wp-htaccess
      items:
        - key: wordpress-htaccess.conf
          path: wordpress-htaccess.conf
extraVolumeMounts:
  - mountPath: /opt/bitnami/apache/conf/vhosts/htaccess
    name: custom-htaccess
```
