### ISSUE TITLE
[bitnami/cert-manager] Wrong documentation / unused controller.serviceAccount.annotations?

### ISSUE THREAD

**Issue by alekc** [bitnami/charts#6565]
**Which chart**:
cert-manager

**Describe the bug**
The documentation states
```
controller.serviceAccount.annotations Additional custom annotations for the ServiceAccount
```

However, it doesn't look from either the code or deployment that that value is actually used at all 
```yaml
{{- if .Values.controller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  labels:
    app.kubernetes.io/component: controller
  {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ template "certmanager.controller.serviceAccountName" . }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
```

If that's indeed the case, we need either to drop the documentation or to implement the support for that property.
