### ISSUE TITLE
thanos rulers  unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by zerols** [bitnami/charts#6581]
**Which chart**:
bitnami/thanos   3.17.8

k8s:v1.2.0
helm:v3
storageclass: nfs-client
values.yaml:
```
global:
  storageClass: nfs-client
objstoreConfig: |-
  type: s3
  config:
    bucket: thanos
    endpoint: {{ include "thanos.minio.fullname" . }}.monitoring.svc.cluster.local:9000
    access_key: minio
    secret_key: minio123
    insecure: true
query:
  dnsDiscovery:
    sidecarsService: kube-prometheus-prometheus-thanos
    sidecarsNamespace: monitoring
bucketweb:
  enabled: true
compactor:
  enabled: true
  persistence:
    storageClass: nfs-client
storegateway:
  enabled: true
  persistence:
    storageClass: nfs-client
ruler:
  enabled: true
  persistence:
    storageClass: nfs-client
  alertmanagers:
    - http://kube-prometheus-alertmanager.monitoring.svc.cluster.local:9093
  config: |-
    groups:
      - name: "metamonitoring"
        rules:
          - alert: "PrometheusDown"
            expr: absent(up{prometheus="monitoring/kube-prometheus"})
receive:
  enabled: true
  persistence:
    storageClass: nfs-client
  
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
minio:
  enabled: true
  accessKey:
    password: "minio"
  secretKey:
    password: "minio123"
  defaultBuckets: "thanos"

```
thanos-ruler and thanos-storegateway show me 

0/6 nodes are available: 6 pod has unbound immediate PersistentVolumeClaims.

![image](https://user-images.githubusercontent.com/35661759/120951200-e3664500-c77a-11eb-9c70-4c324e027d67.png)
