### ISSUE TITLE
[bitnami/etcd]

### ISSUE THREAD

**Issue by antoineozenne** [bitnami/charts#6590]
**Which chart**: etcd 6.2.6

**Is your feature request related to a problem? Please describe.**
I provide a generated certificate for client connections.

```yaml
auth:
  client:
    secureTransport: true
    existingSecret: mytls
    certFilename: tls.crt
    certKeyFilename: tls.key
    caFilename: ca.crt
```

The probes use this client certificate to check the status, so the certificate must be valid for each etcd member `etcd-X.etcd-headless.etcd.svc.cluster.local`. It's not very scalable because if I want to scale from 1 to 2 replicas, I need to regenerate the certificate to add the additional SAN `etcd-1.etcd-headless.etcd.svc.cluster.local` in addition to `etcd-0.etcd-headless.etcd.svc.cluster.local`.

**Describe the solution you'd like**
Could probes use something else to get the status ?
