### ISSUE TITLE
How to custom  sub-chart config

### ISSUE THREAD

**Issue by simeon49** [bitnami/charts#6599]
Chart kong 2.4.1

I deploy kong with cmd "helm install dev-kong -f ./kong-values.yaml bitnami/kong" 
file ./kong-values.yaml look like blow:
```yaml
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName
#   storageClass: myStorageClass

## Bitnami kong image version
## ref: https://hub.docker.com/r/bitnami/kong/tags/
##
image:
  registry: docker.io
  repository: bitnami/kong
  tag: 2.4.1-debian-10-r9
  .....
  .....
migration:
  .....
  #  LOOK HERE !!!
  #  I want add "tolerations" for the "migration", but there is not field name "tolerations" here
  #  I add "tolerations" here but not work
  tolerations:
  - key: node-type
    operator: Equal
    value: development
    effect: NoSchedule
  .....
  
## PostgreSQL properties
##
postgresql:
  .....
  #  LOOK HERE !!!
  # There is very few config field here in "postgresql", I want set more field in "postgresql" that has defined in "https://artifacthub.io/packages/helm/bitnami/postgresql"  like below:
  persistence:
    enabled: true
    ## A manually managed Persistent Volume and Claim
    ## If defined, PVC must be created manually before volume will be bound
    ## The value is evaluated as a template, so, for example, the name can depend on .Release or .Chart
    ##
    existingClaim: development-postgresql
  .....
```
Anyone can help
