### ISSUE TITLE
[bitnami/redis] redis with 3 node cluster is not working with istio(1.9.5 and 1.10.0)

### ISSUE THREAD

**Issue by guru1306** [bitnami/charts#6618]
**Which chart**:
bitnami/redis - version 14.3.1

**Describe the bug**
The synchonization between redis master and worker nodes are not happening and hence the cluster is not in a writable state.

**To Reproduce**
Install Istio 1.9.5 or 1.10.0
Install redis chart with below values

```yaml
redis:  
nameOverride: redis      
auth: 
  enabled: false
  sentinel: false
commonConfiguration: |-
  maxmemory 2500mb
  maxmemory-policy volatile-lru
  maxmemory-samples 10
  min-replicas-max-lag 5
  min-replicas-to-write 0
  rdbchecksum yes
  rdbcompression yes
  repl-diskless-sync yes
  save 900 1    
replica:    
  replicaCount: 3      
sentinel: 
  enabled: true   
```

Error in logs

Node-0 redis logs:
```
1:S 09 Jun 2021 11:50:10.371 * Connecting to MASTER 10.42.1.196:6379
1:S 09 Jun 2021 11:50:10.371 * MASTER <-> REPLICA sync started
1:S 09 Jun 2021 11:50:10.371 * Non blocking connect for SYNC fired the event.
1:S 09 Jun 2021 11:50:10.371 * Master replied to PING, replication can continue...
1:S 09 Jun 2021 11:50:10.371 * Trying a partial resynchronization (request 38a0579220b925cc02199ef42dea63380d6f1099:2259).
1:S 09 Jun 2021 11:50:10.371 * Master is currently unable to PSYNC but should be in the future: -NOMASTERLINK Can't SYNC while not connected with my master
1:S 09 Jun 2021 11:50:11.375 * Connecting to MASTER 10.42.1.196:6379
1:S 09 Jun 2021 11:50:11.375 * MASTER <-> REPLICA sync started
1:S 09 Jun 2021 11:50:11.375 * Non blocking connect for SYNC fired the event.
1:S 09 Jun 2021 11:50:11.375 * Master replied to PING, replication can continue...
1:S 09 Jun 2021 11:50:11.375 * Trying a partial resynchronization (request 38a0579220b925cc02199ef42dea63380d6f1099:2259).
1:S 09 Jun 2021 11:50:11.375 * Master is currently unable to PSYNC but should be in the future: -NOMASTERLINK Can't SYNC while not connected with my master
1:S 09 Jun 2021 11:50:12.378 * Connecting to MASTER 10.42.1.196:6379
1:S 09 Jun 2021 11:50:12.378 * MASTER <-> REPLICA sync started
1:S 09 Jun 2021 11:50:12.378 * Non blocking connect for SYNC fired the event.
1:S 09 Jun 2021 11:50:12.378 * Master replied to PING, replication can continue...
1:S 09 Jun 2021 11:50:12.378 * Trying a partial resynchronization (request 38a0579220b925cc02199ef42dea63380d6f1099:2259).
1:S 09 Jun 2021 11:50:12.378 * Master is currently unable to PSYNC but should be in the future: -NOMASTERLINK Can't SYNC while not connected with my master
```

Node-1 redis logs:

```
1:S 09 Jun 2021 11:52:29.520 * Connecting to MASTER 10.42.1.196:6379
1:S 09 Jun 2021 11:52:29.520 * MASTER <-> REPLICA sync started
1:S 09 Jun 2021 11:52:29.520 * Non blocking connect for SYNC fired the event.
1:S 09 Jun 2021 11:52:29.522 * Master replied to PING, replication can continue...
1:S 09 Jun 2021 11:52:29.523 * Trying a partial resynchronization (request 393f40bc4c229e6fff971dc2808b4847055b1a78:8942).
1:S 09 Jun 2021 11:52:29.524 * Master is currently unable to PSYNC but should be in the future: -NOMASTERLINK Can't SYNC while not connected with my master
1:S 09 Jun 2021 11:52:30.530 * Connecting to MASTER 10.42.1.196:6379
1:S 09 Jun 2021 11:52:30.530 * MASTER <-> REPLICA sync started
1:S 09 Jun 2021 11:52:30.530 * Non blocking connect for SYNC fired the event.
1:S 09 Jun 2021 11:52:30.532 * Master replied to PING, replication can continue...
1:S 09 Jun 2021 11:52:30.533 * Trying a partial resynchronization (request 393f40bc4c229e6fff971dc2808b4847055b1a78:8942).
1:S 09 Jun 2021 11:52:30.533 * Master is currently unable to PSYNC but should be in the future: -NOMASTERLINK Can't SYNC while not connected with my master
```

Thanks
Guru

**Comment by pablogalegoc** [comment]
Hi @guru1306!

It does seem to be a specific issue with Istio. However, I've tried to reproduce it with your custom values in a three node cluster and didn't get those errors. What I do have seen is that it is messing with the IP's (but I don't think this is of any help for your issue):
```
1:X 10 Jun 2021 09:34:14.216 * +sentinel-address-switch master mymaster 10.244.1.5 6379 ip 127.0.0.1 port 26379 for e91755f8d8790ec9d5407b1f66ce0b12cc18fd83
```

Just letting you know that unfortunately our charts are not designed to work with Istio although they can be integrated with it since they can be extended adding custom sidecar containers, labels, annotations, etc. We don't test the integration with Istio in our pipeline and, therefore, we don't officially support it.

Have you been able to use this configuration with previous versions of Istio?

**Comment by guru1306** [comment]
@pablogalegoc 

Thanks. I am using this chart for the first time with istio.   It looks like at the startup it needs some other port other than 6379 and 26379 but it's not in the pod configuration.  

The ping works here but PSYNC is not working. Does it require any other port to do sync?

```
1:S 09 Jun 2021 11:50:11.375 * Master replied to PING, replication can continue...
1:S 09 Jun 2021 11:50:11.375 * Trying a partial resynchronization (request 38a0579220b925cc02199ef42dea63380d6f1099:2259).
1:S 09 Jun 2021 11:50:11.375 * Master is currently unable to PSYNC but should be in the future: -NOMASTERLINK Can't SYNC while not connected with my master
```

Thanks
Guru

**Comment by pablogalegoc** [comment]
Hi again @guru1306! Could you share the commands you used to install and set up Istio please?
I think I'm being able to reproduce your issue but I just want to be sure we are on the same environment.

**Comment by guru1306** [comment]
Thanks. Here are the steps used.

```
kubectl create namespace bitnami
kubectl label namespace bitnami istio.io/rev=1-9-5
kubectl config set-context --current --namespace=bitnami
```
Istio installation 

```curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.9.5 sh -
   istioctl install -f config.yaml
```

Contents of config.yaml
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  hub: gcr.io/istio-release
  tag: 1.9.5
  revision: 1-9-5
  profile: default
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
  meshConfig:
    defaultConfig:
      holdApplicationUntilProxyStarts: true
```
Then installed redis chart in bitnami namespace

**Comment by pablogalegoc** [comment]
Hi @guru1306! Here's what I'm seeing right at the startup of the redis container in `redis-node-0` with and without Istio:

```diff
- 1:M 14 Jun 2021 11:57:55.348 # Server initialized
- 1:M 14 Jun 2021 11:57:55.348 * Ready to accept connections
- 1:M 14 Jun 2021 11:58:26.146 * Replica 127.0.0.1:6379 asks for synchronization
- 1:M 14 Jun 2021 11:58:26.146 * Full resync requested by replica 127.0.0.1:6379
+ 1:M 14 Jun 2021 12:40:37.211 # Server initialized
+ 1:M 14 Jun 2021 12:40:37.212 * Ready to accept connections
+ 1:M 14 Jun 2021 12:40:54.413 * Replica 10.244.1.3:6379 asks for synchronization
+ 1:M 14 Jun 2021 12:40:54.413 * Full resync requested by replica 10.244.1.3:6379
```

Then the PSYNC problems start for the one configured with Istio. This is probably going to need some extra configuration, maybe something like [TPROXY](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig-InboundInterceptionMode)?

**Comment by KeithTt** [comment]
Same problem, any update?

**Comment by miguelaeh** [comment]
Hi @KeithTt ,
did you give a try to the @pablogalegoc suggestion?

**Comment by GabrielLasso** [comment]
Same problem here, the mesh config is:
```yaml
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      interceptionMode: TPROXY
      proxyMetadata: {}
    enablePrometheusMerge: true
    outboundTrafficPolicy:
      mode: ALLOW_ANY
```
