### ISSUE TITLE
[bitnami/solr] Support a way to add additional JARs in WEB-INF/lib

### ISSUE THREAD

**Issue by dalbani** [bitnami/charts#6635]
**Which chart**:
`solr:0.3.3`

**Is your feature request related to a problem? Please describe.**
In order to use JTS in Solr, it is apparently required to place the related JAR at a very specific location.
See <https://solr.apache.org/guide/8_8/spatial-search.html#jts-and-polygons-flat>.
What are the options to be able to do that with the Helm chart?

**Describe the solution you'd like**
A simple way to add arbitrary JAR to the Solr install, without having to build and maintain my own Docker image.

**Describe alternatives you've considered**
In the end, I came up with this solution:
```
        lifecycleHooks:
          postStart:
            exec:
              command:
                - curl
                - -o
                - /opt/bitnami/solr/server/solr-webapp/webapp/WEB-INF/lib/jts-core-1.8.1.jar 
                - https://repo1.maven.org/maven2/org/locationtech/jts/jts-core/1.8.1/jts-core-1.8.1.jar
```
But given no guarantee is made *when* exactly this command will run, I am not sure if it is reliable.
Oh, and I didn't want to override the default `command` as defined at <https://github.com/bitnami/charts/blob/master/bitnami/solr/templates/statefulset.yaml#L100>.

Has anyone a better idea?
