### ISSUE TITLE
how to change SMTP HOST parameter without breaking PV/PVC and database

### ISSUE THREAD

**Issue by enibache** [bitnami/charts#6649]
Dear bitnami,
I've been using the bitnami discourse helm chart to host a forum and it's been awesome so far.  Thanks for a wonderful piece of work here and for all your relentless efforts maintaining and keeping this repos up to date. Recently I updated/changed my smtp server name because of a necessity of concern. Now I need to change the SMTP HOST as well in my deployment.yaml via "lens" or "kubectl edit" which will eventually restart the pods. Do I have to be worried about ending up with a corrupt PV/PVC and database resulting in the pod not restarting eventually?
I'll really appreciate a confirmation or advice on how to go about this little change.

Thanks and cheers,
\enibache

**Comment by carrodher** [comment]
Hi! you can use some values from the Helm Chart that allow you to set some environment variables. you can use three different ways depending on your use case, check `discourse.extraEnvVars`, `discourse.extraEnvVarsCM` and `discourse.extraEnvVarsSecret` at https://github.com/bitnami/charts/tree/master/bitnami/discourse#discourse-parameters.

Those parameters are defined in the values.yaml:
```yaml
discourse:
  ...
  ## An array to add extra env vars
  ## For example:
  ## extraEnvVars:
  ##   discourse:
  ##   - name: DISCOURSE_ELASTICSEARCH_URL
  ##     value: test
  ##
  extraEnvVars: []

  ## Array to add extra configmaps:
  ##
  extraEnvVarsCM: []

  ## Array to add extra environment
  ## variables from a secret:
  ##
  # extraEnvVarsSecret: ""
```

And they are parsed in the deployment template to be taken into account by the container.
