### ISSUE TITLE
[bitnami/nginx] extraPaths not included in each extraHosts

### ISSUE THREAD

**Issue by DaviGia** [bitnami/charts#6656]
**Which chart**:
nginx 9.2.0

**Is your feature request related to a problem? Please describe.**
I cannot specify custom paths in extraHosts.

**Describe the solution you'd like**
I would like the chart to render `ingress.extraPaths` in all configured `ingress.extraHosts`, current only the main host (specified with value: `ingress.hostname`) renders _extraPaths_. **This may not be the best approach** (I'm opened to other approaches, see the last section), so it should be possible to disable it (and maybe disabled by default).

The snippet below 
``` yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
    helm.sh/chart: frontend-9.2.0
  annotations: {}
spec:
  rules:
    - host: domain0.local
      http:
        paths:
          - backend:
              service:
                name: gateway
                port:
                  name: http
            path: /gateway(/|$)(.*)
            pathType: Prefix
          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http
    - host: domain1.local
      http:
        paths: # extraPaths are not rendered (gateway is missing)
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  name: http
    - host: domain2.local
      http:
        paths: # extraPaths are not rendered (gateway is missing)
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  name: http
    - host: domain3.local
      http:
        paths: # extraPaths are not rendered (gateway is missing)
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  name: http
  tls:
    - hosts:
      - domain0.local
      secretName: domain0.local-tls-certificate
    - hosts:
      - domain1.local
      secretName: domain1.local-tls-certificate
    - hosts:
      - domain2.local
      secretName: domain2.local-tls-certificate
    - hosts:
      - domain3.local
      secretName: domain3.local-tls-certificate
```

**Describe alternatives you've considered**
I currently have no alternative. Is there other way with kubernetes to handle multiple domains with the same services? Should I deploy in the same helm release multiple nginx charts (each one will have its own ingress configured with a single domain)? My goal is to have multiple domains that uses the same backend gateway service (spring cloud gateway). I can duplicate frontend if needed but not the gateway.

What will be the best kubernetes configuration to handle this kind of architecture?

**Comment by alvneiayu** [comment]
hi @DaviGia 

Could you share with me the architecture that you want to deploy? Which products/pods/deployments you are deploying. To understand the problem.

Thanks a lot

Álvaro

**Comment by DaviGia** [comment]
Hi @alvneiayu,

The following image explains the architecture I want to deploy:
![architecture](https://user-images.githubusercontent.com/33369180/122252122-67cb6d00-cecb-11eb-83ae-6b8e181013bb.png)

Basically I have 3 tenants, with 3 different frontends (each one is slightly different from the other; so I have 3 different docker image tags) but a single backend that handles all tenants. The frontend pods use bitnami nginx chart. 

Currently this chart can create an ingress and can accept multiple hosts, but it's not capable of attaching the path I want in the extraHosts, so only the main tenant will be able to access the backend (the spring cloud gateway).

My first question is: 

Does this architecture make sense? How is the multi-tenancy handled normally in kubernetes? Other scenarios that come into my mind are:
- one ingress for each tenant (i.e. for each domain), each ingress exposes both frontend and backend
- one ingress for each frontend and an additional one that exposes the backend, all frontend contacts the same backend through a different domain (there is a CORS problem but I can solve it with k8s annotations)

My second and final question is:

Is there a way to handle multiple instances of the same chart with different values in Helm? 
Currently my main chart has a single bitnami nginx subchart as a dependency. This prevent me from deployment multiple frontends. I could solve it by declaring the same dependency multiple time in my main Helm chart and change alias so I can deploy N frontends with different values, but I don't particularly like this solution because it forces me to have a fixed number of frontends.

``` yaml
apiVersion: v2
name: example
type: application
version: 0.0.1
appVersion: 1.0.0
dependencies:
  - name: nginx
    version: ~9.2.0
    repository: https://charts.bitnami.com/bitnami
    alias: frontend0
    condition: frontend0.enabled
  - name: nginx
    version: ~9.2.0
    repository: https://charts.bitnami.com/bitnami
    alias: frontend1
    condition: frontend1.enabled
  - name: nginx
    version: ~9.2.0
    repository: https://charts.bitnami.com/bitnami
    alias: frontend2
    condition: frontend2.enabled
```

Thank you in advance
