### ISSUE TITLE
Thanos 3.18.0 breaks the use of existingSecret and keyMapping

### ISSUE THREAD

**Issue by mbrancato** [bitnami/charts#6666]
**Which chart**:
Thanos

**Describe the bug**
Release 3.18.0 with #6613 has broken the ability to use an existing secret with a key mapping. The key mapping appears to be ignored.

```
level=info ts=2021-06-15T01:07:09.527364527Z caller=client.go:55 msg="enabling client to server TLS"
level=error ts=2021-06-15T01:07:09.52775013Z caller=main.go:130 err="open /tls/client/ca-cert: no such file or directory\nreading client CA\ngithub.com/thanos-io/thanos/pkg/tls.NewClientConfig\n\t/app/pkg/tls/options.go:70\ngithub.com/thanos-io/thanos/pkg/extgrpc.StoreClientGRPCOpts\n\t/app/pkg/extgrpc/client.go:57\nmain.runQuery\n\t/app/cmd/thanos/query.go:333\nmain.registerQuery.func1\n\t/app/cmd/thanos/query.go:210\nmain.main\n\t/app/cmd/thanos/main.go:128\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nbuilding gRPC client\nmain.runQuery\n\t/app/cmd/thanos/query.go:335\nmain.registerQuery.func1\n\t/app/cmd/thanos/query.go:210\nmain.main\n\t/app/cmd/thanos/main.go:128\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\npreparing query command failed\nmain.main\n\t/app/cmd/thanos/main.go:130\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"
```

**To Reproduce**

configure the following values under `query.grpcTLS.client.existingSecret`:
```yaml
            name: thanos-tls
            keyMapping:
              ca-cert: ca.pem
              tls-cert: cert.pem
              tls-key: key.pem
```

From flux:
```
Status:
  Conditions:
    Last Transition Time:          2021-06-14T16:38:40Z
    Message:                       Helm upgrade failed: timed out waiting for the condition
    Reason:                        UpgradeFailed
    Status:                        False
    Type:                          Ready
    Last Transition Time:          2021-06-14T16:38:40Z
    Message:                       Helm upgrade failed: timed out waiting for the condition
    Reason:                        UpgradeFailed
    Status:                        False
    Type:                          Released
  Failures:                        46
  Helm Chart:                      flux-system/flux-system-thanos
  Last Applied Revision:           3.17.8
  Last Attempted Revision:         3.18.0
  Last Attempted Values Checksum:  d8d4d90160560fc473c4437d8f07f3e717f69cf5
  Last Release Revision:           19
  Observed Generation:             3
  Upgrade Failures:                1
```

**Expected behavior**
Thanos query should start, but instead goes into a crash loop.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```
But I'm actually using flux and a HelmRelease. 

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1400", GitCommit:"ec68c7064ea987ad0c7fb63930df96bdefeb93c4", GitTreeState:"clean", BuildDate:"2021-04-07T09:20:04Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by alvneiayu** [comment]
hi @mbrancato 

Working on it. Thanks for reporting the issue.

Thanks

Álvaro

**Comment by alvneiayu** [comment]
hi @mbrancato 

I think that the issue has been fixed. If you have any problem, let me know please.

Thanks a lot

Álvaro

**Comment by jppitout** [comment]
Hi @alvneiayu,

It seems we're having the same issue on version 3.18.2. 
Here are the values we're using for Thanos Query:
```
  grpcTLS:
    client:
      secure: true
      existingSecret:
        name: central-thanos-tls
        keyMapping:
          ca-cert: ca.pem
          tls-cert: cert.pem
          tls-key: key.pem
```
But the pod logs show:
```
level=error ts=2021-06-22T10:36:39.790907384Z caller=main.go:130 err="open /tls/client/ca.pem: no such file or directory
```
The key is correct in the secret:
```
$ kubectl describe secret central-thanos-tls | grep ca-cert
ca-cert:   1331 bytes
```
I can see the secret is getting mounted in the pod:
```
    volumeMounts:
    - mountPath: /tls/client
      name: tls-client

  volumes:
  - name: tls-client
    secret:
      defaultMode: 420
      secretName: central-thanos-tls
```

**Comment by alvneiayu** [comment]
hi @jppitout

I think that your secret is not properly created. Setting up the keyMapping, you are telling that the ca.pem in your secret, it will be the ca-cert. So you need to create your secret with a structure like this:
```
Name:         central-thanos-tls
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
ca.pem:    1359 bytes
cert.pem:  2945 bytes
key.pem:   1679 bytes
```
Try doing this and you will see your tls files inside your pod (in the folder /tls/client). Let me know if you still have problems.

Command:
```
kubectl create secret generic central-thanos-tls  --namespace default  --from-file=cert.pem=*PATH-CERT-PEM*  --from-file=ca.pem=*PATH-CA-PEM* --from-file=key.pem=*PATH-KEY-PEM*
```

Thanks a lot

Álvaro

**Comment by jppitout** [comment]
Thanks so much I realized we don't actually need `keyMapping`. Pod is running with:
```
  grpcTLS:
    client:
      secure: true
      existingSecret:
        name: central-thanos-tls
```
Thank you!
