### ISSUE TITLE
[bitnami/redis-cluster] Install chart with pre-defined IP Adresses for external access

### ISSUE THREAD

**Issue by cronventis** [bitnami/charts#6690]
**Which chart**:
redis-cluster 6.1.5

**Is your feature request related to a problem? Please describe.**
It seems like, if you want to have external access to redis, you always need to have two steps installing redis:
- helm install
- helm upgrad

**Describe the solution you'd like**
I would like to install redis on k8s by just adding one value file and running helm install.

**Additional context**
I have created a question in the community asking if this REALY is the path needed to deploy redis on k8s: [here](https://community.bitnami.com/t/install-redis-cluster-helm-chart-with-pre-defined-ip-adresses-for-external-access/96611)
I also found this issue: #5688 that seems to discuss the same issue...

**Comment by miguelaeh** [comment]
Hi @cronventis ,
If you set the loadbalancerIPs in the first step with `externalAccess.enabled=true` the statefulset will be created and you will not need to upgrade the cluster.
Could you give it a try and let us know?

**Comment by cronventis** [comment]
That is what I did:

`cluster:
    externalAccess:
      enabled: true
      loadBalancerIP:
      - 10.x.x.106
      - 10.x.x.107
      - 10.x.x.108
      - 10.x.x.109
      - 10.x.x.110
      - 10.x.x.111`

And the statefulset is not created..

**Comment by cronventis** [comment]
Ok, yes.. I'm blind:

```
cluster:
    externalAccess:
      enabled: true
      loadBalancerIP:
```
is not the same as

```
cluster:
    externalAccess:
      enabled: true
      service:
        loadBalancerIP:
```
