### ISSUE TITLE
[bitnami/mongodb] TLS with custom certificates fails PodInitializing

### ISSUE THREAD

**Issue by asenyaev** [bitnami/charts#6714]
I started minikube with the cluster version **v1.20.0**

Also added several lines for the `override.yaml` file: 
- defined an image tag
- enabled TLS
- added a certificate and a key

But mongo does not start. I see that all containers (mongodb and generate-tls-certs) were created and started, but pod is in an error status `Back-off restarting failed container`.

What I have added:
```
image:
  tag: 3.6.23

tls:
  enabled: true
  autoGenerated: false
  caCert: <my_certificate>
  caKey: <my_key>
```
The chart version: **10.19.0**

The image for mongodb: **3.6.23**
