### ISSUE TITLE
[bitnami/postgresql-ha] Client certificate check between pgpool and postgresql not working

### ISSUE THREAD

**Issue by lbrue** [bitnami/charts#6717]
**Which chart**:
postgresql-ha since Version 7.6.1

**Describe the bug**
Activating the client certificate check from pgpool (TLS Client) to postgresql (TLS Server) leads to a not startable postgresql container (not finding auto generated pg_hba.conf file) . The client certificate check is activated by setting the `postgresql.tls.certCAFilename` to any CA certificate. Specifying a custom `pg_hba.conf` file via `postgresql.pgHbaConfiguration` does not help. 

Log of the error:
```
postgresql-repmgr 13:12:59.54 
postgresql-repmgr 13:12:59.54 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 13:12:59.55 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 13:12:59.55 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 13:12:59.55 
postgresql-repmgr 13:12:59.55 DEBUG ==> Configuring libnss_wrapper...
postgresql-repmgr 13:12:59.56 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 13:12:59.59 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 13:12:59.60 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 13:12:59.60 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 13:12:59.61 DEBUG ==> Checking node 'postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local:5432'...
postgresql-repmgr 13:12:59.62 DEBUG ==> Executing SQL command:
SELECT conninfo FROM repmgr.show_nodes WHERE (upstream_node_name IS NULL OR upstream_node_name = '') AND active=true
psql: could not connect to server: Connection refused
	Is the server running on host "postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local" (172.17.0.4) and accepting
	TCP/IP connections on port 5432?
postgresql-repmgr 13:12:59.63 DEBUG ==> Skipping: failed to get primary from the node 'postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local:5432'!
postgresql-repmgr 13:12:59.64 DEBUG ==> Checking node 'postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.default.svc.cluster.local:5432'...
postgresql-repmgr 13:12:59.64 DEBUG ==> Executing SQL command:
SELECT conninfo FROM repmgr.show_nodes WHERE (upstream_node_name IS NULL OR upstream_node_name = '') AND active=true
psql: could not translate host name "postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.default.svc.cluster.local" to address: Name or service not known
postgresql-repmgr 13:12:59.71 DEBUG ==> Skipping: failed to get primary from the node 'postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.default.svc.cluster.local:5432'!
postgresql-repmgr 13:12:59.71 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 13:12:59.74 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 13:12:59.75 DEBUG ==> Injecting a new postgresql.conf file...
postgresql-repmgr 13:12:59.75 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 13:12:59.85 INFO  ==> Configuring TLS
postgresql-repmgr 13:12:59.87 INFO  ==> Enabling TLS Client authentication
cat: /opt/bitnami/postgresql/conf/pg_hba.conf: No such file or directory
```
**To Reproduce**

1. Generate two secrets for pgpool and postgresql (I did using cert-manager therefore I have a tls.key, tls.crt and ca.crt)
2. Make the secrets availiable in the namespace yopu want to install postgresql-ha in
3. Install postgresql-ha using the following settings file (called it `settings.yaml`):
```yaml
postgresql:
  tls:
    ## Enable TLS traffic
    ##
    enabled: true
    ##
    ## Whether to use the server's TLS cipher preferences rather than the client's.
    ##
    preferServerCiphers: true
    ##
    ## Name of the Secret that contains the certificates
    ##
    certificatesSecret: "postgresql-tls-secret"
    ##
    ## Certificate filename
    ##
    certFilename: "tls.crt"
    ##
    ## Certificate Key filename
    ##
    certKeyFilename: "tls.key"
    ##
    ## CA Certificate filename
    ## If provided, PgPool will authenticate TLS/SSL clients by requesting them a certificate
    ## ref: https://www.pgpool.net/docs/latest/en/html/runtime-ssl.html
    ##
    certCAFilename: "ca.crt"

postgresqlImage:
  debug: true

pgpoolImage:
  debug: true

pgpool:
  tls:
    ## Enable TLS traffic
    ##
    enabled: true
    ##
    ## Whether to use the server's TLS cipher preferences rather than the client's.
    ##
    preferServerCiphers: true
    ##
    ## Name of the Secret that contains the certificates
    ##
    certificatesSecret: "pgpool-tls-secret"
    ##
    ## Certificate filename
    ##
    certFilename: "tls.crt"
    ##
    ## Certificate Key filename
    ##
    certKeyFilename: "tls.key"
    ##
    ## CA Certificate filename
    ## If provided, PgPool will authenticate TLS/SSL clients by requesting them a certificate
    ## ref: https://www.pgpool.net/docs/latest/en/html/runtime-ssl.html
    ##
    ## Wenn nicht definiert, keine pg_hba.conf Datei erstellt
    certCAFilename: "ca.crt"

```
4. Install the bitnami chart Version 7.7.1 via `helm install postgresql-ha bitnami/postgresql-ha -f settings.yaml`

**Expected behavior**
Two postgresql instances booted.

When I uncomment the `postgresql.tls.certCAFilename` the pods are booting and are working but without client certificate check.

Also there seems to be a typo in the [postgresql statefulset](https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/templates/postgresql/statefulset.yaml#L250). Should not the postgresql CA certificate be used and not the pgpool one (should be postgresql instead of pgpool)?

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
using minikube
