### ISSUE TITLE
cors parameters provisioning

### ISSUE THREAD

**Issue by oktayalizada** [bitnami/charts#6718]
Hi,
Which option I should choose to provide cors parameters to bitnami/elasticsearch charts? 
I want to pass the following configs to elasticsearch 

http.cors.allow-origin: "*"
http.cors.enabled: true
http.cors.allow-credentials: true
http.cors.allow-methods : OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization, Access-Control-Allow-Headers, Accept
I have tried several options providing it as a config object, as environment variables. No success

Thank you

**Comment by Mauraza** [comment]
Hi @oktayalizada,

Could you check if this official documentation?
https://www.elastic.co/guide/en/elasticsearch/reference/7.13/modules-network.html

**Comment by oktayalizada** [comment]
Hi @Mauraza,
Thank you, yes, I read the docs, but how do I provide those settings to the helm chart I am not sure. To be able to provide them I need a variable(or parameter) where I can put them. Which variable should I use and what is the format?

**Comment by Mauraza** [comment]
Hi @oktayalizada,

You need to add that configuration to the elasticsearch.yml
```yaml
http.cors.enabled : true
http.cors.allow-origin: "*"
http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization, Access-Control-Allow-Headers, Accept
```
The chart has ⬇️ to provide the configuration you want
https://github.com/bitnami/charts/blob/62a0ebe745dfa326302aedb7cb5e3431e678fdf7/bitnami/elasticsearch/values.yaml#L127-L135

**Comment by oktayalizada** [comment]
hi @Mauraza  when I add custom configs, it replaces elasticsearch.yml it doesn't add my custom parameters,. Since it replaces elasticsearch.yml with only my custom configs, I have to either copy all default variables to my new config as well, but that wouldn't work because some of the parameters in elasticsearch.yml are generated on the fly. So I need a way to keep default elasticsearch,yml and add those parameters. What I have done I used initscript parameter and added those parameters wich echo command but that is obviously not how it should be

**Comment by Mauraza** [comment]
Hi  @oktayalizada,

You could follow these steps:
-  save the configuration you want to keep in a file 
-  add cors configuration
-  pass these values to the chart in the config

**Comment by Sam-Sundar-Apty** [comment]
> hi @Mauraza when I add custom configs, it replaces elasticsearch.yml it doesn't add my custom parameters,. Since it replaces elasticsearch.yml with only my custom configs, I have to either copy all default variables to my new config as well, but that wouldn't work because some of the parameters in elasticsearch.yml are generated on the fly. So I need a way to keep default elasticsearch,yml and add those parameters. What I have done I used initscript parameter and added those parameters with echo command but that is obviously not how it should be

Hi @oktayalizada ,

Can you please let us know how you solved it/ added cors parameter to `elasticsearch.yml` ?

**Comment by Mauraza** [comment]
Hi @Sam-Sundar-Apty,

you can use `extraConfig` to add the parameter of cors https://github.com/bitnami/charts/blob/c2de8c8b9a1e1bb4acd3217d200f78be1daf9f36/bitnami/elasticsearch/values.yaml#L168-L177

**Comment by Sam-Sundar-Apty** [comment]
Hi @Mauraza,

I tried add in extraConfig like below
```yaml
extraConfig: 
    http:
      cors.enabled : true
      cors.allow-origin: "*"
      cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
      cors.allow-headers: X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization, Access-Control-Allow-Headers, Accept
```
And it's getting created with a file `my_elasticsearch.yml` under `/opt/bitnami/elasticsearch/config/` but ES is not loading this config. 

I guess it needs the config in `/opt/bitnami/elasticsearch/config/elasticsearch.yml` file. 

![image](https://user-images.githubusercontent.com/83000807/150792652-619ba125-52b8-4199-9f5f-a9a0e611d236.png)
