### ISSUE TITLE
[bitnami/minio] WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.

### ISSUE THREAD

**Issue by viceice** [bitnami/charts#6726]
**Which chart**:
minio 7.1.0

**Describe the bug**
Getting a new warning:
```
WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
```

**To Reproduce**

1. create a `mode: distributed` cluster 
2. watch the pod logs

**Expected behavior**
I think the templates need a update. this is also related to #4422

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
doesn't matter
```

- Output of `kubectl version`:

```
doesn't matter
```

**Additional context**
nope

**Comment by marcosbc** [comment]
Thanks for reporting @viceice! It indeed seems like the `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY` flags have been deprecated into `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD`, respectively. I've created an internal task for performing the necessary changes in the [`bitnami-docker-minio`](https://github.com/bitnami/bitnami-docker-minio/) repository and in the Helm chart.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.

**Comment by viceice** [comment]
yes, seems to be fixed since some time 🥳

**Comment by ashkankzme** [comment]
I am still receiving this error even though I am using the latest version of MinIO:
`Version: RELEASE.2024-02-13T15-35-11Z (go1.21.7 linux/arm64)`


and I am unable to set `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY` and I see the following warning in the MinIO logs:
```
minio-1     | WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
minio-1     |          Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
```

It seems that MinIO ignores the environment variables set for the access keys.
I am able to create access keys through the MinIO console interface however.

here is the docker-compose file I use to build/run MinIO:

```
version: '3'
services:
  minio:
    image: 'minio/minio:latest'
    ports:
      - '${FORWARD_MINIO_PORT:-9000}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-9090}:9090'
    env_file:
      - 'environment_variables.env'
    volumes:
      - 'minio:/data/minio'
    command: minio server /data/minio --console-address ":9090"
volumes:
  minio:
    driver: local
```

And here is the `environment_variables.env` content:
```
MINIO_ROOT_USER="XXX"
MINIO_ROOT_PASSWORD="XXX"

MINIO_ACCESS_KEY="SOMETHING"
MINIO_SECRET_KEY="ANYTHING"

MINIO_NOTIFY_WEBHOOK_ENABLE_XXX="on"
MINIO_NOTIFY_WEBHOOK_ENDPOINT_XXX="XXX"

MINIO_URL="XXX"
```

Is there anything I'm doing wrong?

Thank you in advance
