### ISSUE TITLE
[bitnami/wordpress] Installation with external mariadb and existing claim fails

### ISSUE THREAD

**Issue by mh0rst** [bitnami/charts#6728]
**Which chart**:
wordpress-11.0.16

**Describe the bug**
When installing a new wordpress application using
1. an external, empty database
2. an existing persistent volume claim, also empty

the installation fails:

Pod log:
```
wordpress 14:39:32.77 
wordpress 14:39:32.77 Welcome to the Bitnami wordpress container
wordpress 14:39:32.77 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
wordpress 14:39:32.77 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
wordpress 14:39:32.78 
wordpress 14:39:32.78 INFO  ==> ** Starting WordPress setup **
wordpress 14:39:32.82 INFO  ==> Configuring PHP options
wordpress 14:39:32.83 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
wordpress 14:39:32.88 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
wordpress 14:39:33.00 INFO  ==> Ensuring WordPress directories exist
wordpress 14:39:33.01 INFO  ==> Trying to connect to the database server
wordpress 14:39:33.03 INFO  ==> Configuring WordPress with settings provided via environment variables
wordpress 14:39:35.18 INFO  ==> Installing WordPress
```

Events:
```
Events:
  Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
  Normal   Scheduled               11m                  default-scheduler        Successfully assigned web/wp-brinternal-wordpress-7c548c7b84-td2fh to XXX
  Normal   SuccessfulAttachVolume  11m                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-8fc56ac5-1330-4c5f-a94e-e61d9f83ef43"
  Normal   Pulled                  9m55s (x5 over 11m)  kubelet                  Container image "docker.io/bitnami/wordpress:5.7.2-debian-10-r25" already present on machine
  Normal   Created                 9m55s (x5 over 11m)  kubelet                  Created container wordpress
  Normal   Started                 9m55s (x5 over 11m)  kubelet                  Started container wordpress
  Warning  BackOff                 87s (x47 over 11m)   kubelet                  Back-off restarting failed container
```

MariaDB tables are also created successfully by the installation:
```
MariaDB [mydatabase]> show tables;
+------------------------+
| Tables_in_mydatabase   |
+------------------------+
| wp_commentmeta         |
| wp_comments            |
| wp_links               |
| wp_options             |
| wp_postmeta            |
| wp_posts               |
| wp_term_relationships  |
| wp_term_taxonomy       |
| wp_termmeta            |
| wp_terms               |
| wp_usermeta            |
| wp_users               |
+------------------------+
```

Is this even a supported use case? Or is wordpress installation only supported with the included mariadb and/or the automatically created PVC?

**To Reproduce**

1. Create a new database and a user with all privileges on that database on an external MariaDB instance
2. Create a new PVC
3. Install the wordpress chart using the config values listed below

PVC:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: externalpvc
  namespace: web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
```
Helm Values:
```
externalDatabase:
  host: mariadb.host.name
  database: mydatabase
  user: username
  password: password

podAffinityPreset: hard

service:
  type: ClusterIP

ingress:
  enabled: true
  certManager: true
  tls: true
  hostname: my.external.url
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"

persistence:
  existingClaim: externalpvc

mariadb:
  enabled: false
```

**Expected behavior**
The installation should succeed, the wordpress instance should become available after the installation.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-13T02:40:46Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```
