### ISSUE TITLE
[bitnami/minio] disk is not writable when persistence disabled

### ISSUE THREAD

**Issue by ben-wangz** [bitnami/charts#6736]
**Which chart**:
minio 7.1.0

**Describe the bug**
1. when you log into web ui, you'll find "Server not initialized, please try again"
2. kubectl get pod, it's running ok. but logs shows it is not.
```
Error: disk is not writable http://test-minio-0.test-minio-headless.default.svc.cluster.local:9000/data-1, Run the following command to add write permissions: `sudo chown -R <your-username> /data-1 && sudo chmod u+rxw /data-1` (*errors.errorString)
       2: cmd/storage-rest-server.go:1011:cmd.logFatalErrs()
       1: cmd/storage-rest-server.go:1056:cmd.registerStorageRESTHandlers.func1()

API: SYSTEM()
Time: 07:29:09 UTC 06/23/2021
Error: disk is not writable http://test-minio-0.test-minio-headless.default.svc.cluster.local:9000/data-0, Run the following command to add write permissions: `sudo chown -R <your-username> /data-0 && sudo chmod u+rxw /data-0` (*errors.errorString)
       2: cmd/storage-rest-server.go:1011:cmd.logFatalErrs()
       1: cmd/storage-rest-server.go:1056:cmd.registerStorageRESTHandlers.func1()
Unable to use the drive http://test-minio-0.test-minio-headless.default.svc.cluster.local:9000/data-0: file access denied
Unable to use the drive http://test-minio-0.test-minio-headless.default.svc.cluster.local:9000/data-1: file access denied
```

**To Reproduce**

1. test.yaml (values)
```yaml
mode: distributed
accessKey:
  password: null
secretKey:
  password: null
statefulset:
  # Number of replicas, it must even and greater than 4
  replicaCount: 4
  # Number of expanded MinIO(R) clusters
  zones: 1
  # Number of drives (PVC) attached to every node
  drivesPerNode: 2
service:
  type: NodePort
  nodePort: 32009
ingress:
  enabled: true
  certManager: false
  hostname: minio.test.local.some.domain
  path: /
volumePermissions:
  enabled: true
persistence:
  enabled: false
```
2. helm install test-minio minio --version 7.1.0 --values test.yaml --atomic --repo https://charts.bitnami.com/bitnami --create-namespace

**Expected behavior**
1. service start correctly even if i use emptyDir(disable persistence)
2. probes may have to be enhanced. helm install blocked/failed(with --atomic) if service is not available

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```
