### ISSUE TITLE
[bitnami/postgresql-ha] Possible typo in the postgresql statefulset of postgresql-ha chart

### ISSUE THREAD

**Issue by lbrue** [bitnami/charts#6743]
**Which chart**:
postgresql-ha, Version 7.7.1

**Describe the bug**
There seems to be a typo in the [postgresql statefulset](https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/templates/postgresql/statefulset.yaml#L250). Should not the postgresql CA certificate be used and not the pgpool one?

Current implementation:
```yaml
{{- if .Values.pgpool.tls.certCAFilename }}
            - name: POSTGRESQL_TLS_CA_FILE
              value: {{ template "postgresql-ha.postgresql.tlsCACert" . }}
```

Should change to 
```yaml
{{- if .Values.postgresql.tls.certCAFilename }}
            - name: POSTGRESQL_TLS_CA_FILE
              value: {{ template "postgresql-ha.postgresql.tlsCACert" . }}
```

due to the existing `postgresql.tls.certCAFilename` in the charts values.yaml and the fact that the postgresql CA certificate gets set to the `POSTGRESQL_TLS_CA_FILE` environment variable.

**To Reproduce**
Simple code review of the [postgresql statefulset file, line 250](https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/templates/postgresql/statefulset.yaml#L250)

**Expected behavior**
Due to the fact the postgresql CA certificate gets used for the 'value' key, it seems wrong that the if condition checks if the pgpool CA certificate is defined. A scenario where you do not want to have the client certificate checked in postgresql is not woking with the current implementation. The existence of the `postgresql.tls.certCAFilename` should be checked.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
