### ISSUE TITLE
Keycloak pod keeps restarting

### ISSUE THREAD

**Issue by MatteoInfi** [bitnami/charts#6774]
**Which chart**:
```
    name: keycloak
    version: 3.1.1
    repository: https://charts.bitnami.com/bitnami
```

**Describe the bug**
So I am using the keycloak chart as a dependency:

`Chart.lock`:

```
dependencies:
- name: keycloak
  repository: https://charts.bitnami.com/bitnami
  version: 3.1.1
digest: sha256:0845988827ef5c3528f3fb46730afb4af7b22a14e8f7605cef108c9f47f32068
generated: "2021-06-26T13:59:10.209970369+07:00"
```
In my `values.yaml` I have the following:

```
keycloak:
  replicaCount: 1
  auth:
    adminPassword: admin
    adminUser: admin
    createAdminUser: true
  service:
    type: ClusterIP
    port: 8080
```

So I want to use a `ClusterIP` service so I can connect it to my ingress instead of the `LoadBalancer` type

My Ingress configuration:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-keycloak-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /myapp/keycloak
            pathType: Prefix
            backend:
              service:
                name: myapp-keycloak
                port:
                  number: 8080

```

I have this intermittent random error in the events

```
Readiness probe failed: Get "http://10.244.0.13:8080/auth/realms/master": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Just to be clear I have also another ingress on my web page that will use keycloak:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rebugit-web-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/myapp/web)$ $1/ redirect;
spec:
  rules:
    - http:
        paths:
          - path: /myapp/web(.*)
            pathType: Prefix
            backend:
              service:
                name: {{.Values.dashboard.service.name }}
                port:
                  number: {{.Values.dashboard.service.port}}
```

**Expected behavior**
Should not restart randomly the pod

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

```

**I am using kind cluster**
```
kind v0.11.1 go1.16.5 linux/amd64
```
----

## UPDATE 1

So I have removed my ingress for now and just use the one you guys provide:

```
  ingress:
    hostname:
    enabled: true
    pathType: Prefix
    path: /myapp/keycloak
    servicePort: 8080
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite ^(/myapp/keycloak)$ $1/ redirect;
```

I have being also trying different configuration with the annotations and rewrite, however nothing has been working so far, the pod keep crashing without any reason with this error:

```
Readiness probe failed: Get "http://10.244.0.13:8080/auth/realms/master": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

and I cannot reach that url either I get 503 or 404

----

## UPDATE 2:

I have simplified by removing my other ingress, which rewrites might probably conflict, and refactor the configuration:

```
keycloak:
  replicaCount: 1
  auth:
    adminPassword: admin
    adminUser: admin
    createAdminUser: true
  service:
    type: ClusterIP
    port: 8080
  ingress:
    hostname:
    enabled: true
    pathType: Prefix
    path: /
    servicePort: 8080
```

So with the configuration above is now working correctly, however that is not what I want to achieve, my goal is to run keycloak on another path together with the other ingress for my web frontend

```
keycloak:
  replicaCount: 1
  auth:
    adminPassword: admin
    adminUser: admin
    createAdminUser: true
  service:
    type: ClusterIP
    port: 8080
  ingress:
    hostname:
    enabled: true
    pathType: Prefix
    path: /myapp/keycloak // <= This one
    servicePort: 8080
```

and then my web service

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rebugit-web-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/myapp/web)$ $1/ redirect;
spec:
  rules:
    - http:
        paths:
          - path: /myapp/web(.*)
            pathType: Prefix
            backend:
              service:
                name: {{.Values.dashboard.service.name }}
                port:
                  number: {{.Values.dashboard.service.port}}
```

**PS: one question that I have, why the keycloak pod gets restarted when I redeploy the chart? Even though I did not change anything regarding it, thanks**

----

## UPDATE 3

So I have found this Stackoverflow question, which seems to be very similar to my problem: https://stackoverflow.com/questions/44624844/configure-reverse-proxy-for-keycloak-docker-with-custom-base-url/54311713#54311713

So I have created a custom image 

```
FROM bitnami/keycloak:13.0.1

RUN sed -i -e 's/<web-context>auth<\/web-context>/<web-context>myapp\/keycloak\/auth<\/web-context>/' /opt/bitnami/keycloak/standalone/configuration/standalone-ha-default.xml
RUN sed -i -e 's/<web-context>auth<\/web-context>/<web-context>myapp\/keycloak\/auth<\/web-context>/' /opt/bitnami/keycloak/standalone/configuration/standalone.xml
```

Then add the additional env var `PROXY_ADDRESS_FORWARDING` and this is my final configuration

```
keycloak:
  replicaCount: 1
  image:
    registry: my-registry
    repository: myapp/keycloak
    tag: "123"
    pullPolicy: Always
  auth:
    adminPassword: admin
    adminUser: admin
    createAdminUser: true
  service:
    type: ClusterIP
    port: 8080
  extraEnvVars:
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
  ingress:
    hostname:
    enabled: true
    pathType: Prefix
    path: /rebugit/keycloak
    servicePort: 8080
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$1

```

So now this is accessible via service only inside the cluster `localhost:<placeholder_port>/myapp/keycloa/auth`
However this is still not accessible from my ingress I get a 503 and the probes give me this error:

```
Readiness probe failed: HTTP probe failed with statuscode: 404
Liveness probe failed: HTTP probe failed with statuscode: 404
```

So I have ended up changing both with the new url and now I kind working I can access the keycloak page at
`localhost/myapp/keycloak/auth**/**` with the trailing slash, however the pod keeps restarting randomly with the same error:

```
Readiness probe failed: HTTP probe failed with statuscode: 404
```
or

```
Readiness probe failed: Get "http://10.244.0.57:8080/myapp/keycloak/auth/realms/master": dial tcp 10.244.0.57:8080: connect: connection refused
```

This is my readiness probe

```
  readinessProbe:
    enabled: true
    httpGet:
      path: /myapp/keycloak/auth/realms/master
    initialDelaySeconds: 30
    timeoutSeconds: 30
```

**Comment by Mauraza** [comment]
Hi @MatteoInfi,

Can you access `http://10.244.0.57:8080/myapp/keycloak/auth/realms/master`?
Could you add to your values.yaml `image.debug: true` and share your logs?

**Comment by MatteoInfi** [comment]
Yes I can access, but the pod keep restarting randomly, and there is no error in the logs

**Comment by Mauraza** [comment]
Hi @MatteoInfi,

Could you try to change your `readinessProbe` for this 🔽 ?
```yaml
  readinessProbe:
    enabled: true
    httpGet:
      path: /myapp/keycloak/auth/realms/master
      port: http
    initialDelaySeconds: 30
    timeoutSeconds: 30
```
