### ISSUE TITLE
[bitnami/keycloak] Postgresql issues/questions

### ISSUE THREAD

**Issue by MatteoGioioso** [bitnami/charts#6794]
**Which chart**:
bitnami/keycloak:

**Describe the bug**
I have a couple of problems/questions maybe more questions than issues and I apologize in advance if this is not the appropriate channel. 

## Credentials not persisted
So I see that if I update credentials those are not set, I will explain with the reproduction steps:

**To Reproduce**

1. deploy the chart
2. deploy the chart with custom values
```
keycloak:
   postgresql:
    postgresqlDatabase: keycloak
    postgresqlPassword: postgres
    postgresqlUsername: postgres
```

3. The credentials are still the default one and the keycloak instance cannot connect and therefore crashes

**Expected behavior**
It should pick up the new credentials, however I am not sure this is an issue at all, so my question is: do credentials get set only at `install` time and cannot be upgraded? Or how does it work? And how can I proceed?

**Version of Helm and Kubernetes**:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0" , GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

```

## Init db

So I see that in your `bitnami/postgres` image I can mount or `COPY` my script in the docker container and run a `.sql` file to initialize my database, so for example in compose would be something like this:

```
  postgres:
    image: docker.io/bitnami/postgresql:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
    volumes:
      - ./db/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
```

Now I would like to do something similar using this chart, my goal is to share the same PostgreSQL instance with another application. So I am trying to mount the volume (but probably this is only for keycloak)

`values.yaml`:

```
database:
  user:
   password: p4zZwr0D
keycloak:
  extraVolumeMounts:
    - name: postgres-initdb
      mountPath: /docker-entrypoint-initdb.d
  extraVolumes:
    - name: postgres-initdb
      configMap:
        name: database-config
```

my config map:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: default
data:
  initDb: |-
    CREATE DATABASE myotherdb;
    CREATE DATABASE keycloak;

    CREATE USER app WITH LOGIN;
    ALTER USER app WITH PASSWORD '{{.Values.database.user.password}}';
```

But this does not seems to do anything, so how can I achieve this?

Thanks
