### ISSUE TITLE
[bitnam/postgresql] Metrics parameters for replica not full

### ISSUE THREAD

**Issue by serg-bs** [bitnami/charts#6800]
**Which chart**:
postgresql
version: 10.5.1

**Describe the bug**
Not show full Metrics parameters for replica

**To Reproduce**

1. Install helm chart with 
```yaml
  postgresqlDatabase: test
  postgresqlUsername: test
  postgresqlPassword: testpwd
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: monitoring
  replication:
    enabled: true
```
2. check metics endpont
There are only two parameters
pg_stat_replication_pg_wal_lsn_diff
pg_stat_replication_pg_current_wal_lsn_bytes

**Expected behavior**
I want to see all parameters 
https://github.com/prometheus-community/postgres_exporter/blob/master/cmd/postgres_exporter/postgres_exporter.go#L282

Additional: 
We try change user https://github.com/bitnami/charts/commit/9fb96201b974ab3247379654a6b7ee9fba2b3a93
But that not work.
