### ISSUE TITLE
[bitnami/mongodb-sharded] Sharded-data instances failing with incorrect shardsvr.service.name value

### ISSUE THREAD

**Issue by emmanuelm41** [bitnami/charts#6808]
**Which chart**:
mongodb-sharded v3.7.0

**Describe the bug**
When I deployed this chart in a Kubernetes cluster, mongos and configsrv were successfully initialized, but the shared-data-X were not. They fail with the legend "cannot resolve pre-prod-mongodb-service: no such host". The sharded-data look for mongos instance with the env variable [MONGODB_MONGOS_HOST](https://github.com/bitnami/bitnami-docker-mongodb-sharded/blob/e92e13de868856ce6d1251b309ec4cdc9c58f19d/4.4/debian-10/rootfs/opt/bitnami/scripts/libmongodb-sharded.sh#L82), but this variable is set to [common.names.fullname](https://github.com/bitnami/charts/blob/f208f66fbfe36a3aebb1a72bcd4c47c7ec67a991/bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml#L121) and not to [mongodb-sharded.serviceName](https://github.com/bitnami/charts/blob/f208f66fbfe36a3aebb1a72bcd4c47c7ec67a991/bitnami/mongodb-sharded/templates/mongos/mongos-service.yaml#L4). 

**To Reproduce**

1. Deploy the chart with the following values
```yaml
# This file and all contents in it are OPTIONAL.

# The namespace this chart will be installed to,
# if not specified the chart will be installed to "default"
# namespace: dev

# Custom helm options
helm:
  # The directory of the chart in the repo.  Also any valid go-getter supported
  # URL can be used there is specify where to download the chart from.
  # If repo below is set this value if the chart name in the repo
  chart: "mongodb-sharded"

  # An https to a valid Helm repository to download the chart from
  repo: "https://charts.bitnami.com/bitnami"

  # Used if repo is set to look up the version of the chart
  version: "3.7.0"

  # Force recreate resource that can not be updated
  force: false

  # How long for helm to wait for the release to be active. If the value
  # is less that or equal to zero, we will not wait in Helm
  timeoutSeconds: 600

  # Custom values that will be passed as values.yaml to the installation
  ## Global Docker image parameters
  ## Please, note that this will override the image parameters, including dependencies, configured to use the global value
  ## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
  ##
  # global:
  #   imageRegistry: myRegistryName
  #   imagePullSecrets:
  #     - myRegistryKeySecretName
  #   storageClass: myStorageClass

  ## Bitnami MongoDB(R) Sharded image version
  ## ref: https://hub.docker.com/r/bitnami/mongodb-sharded/tags/
  ##
  values:
    ## MongoDB(R) credentials
    ##

    ## Name of a secret containing all the credentials above
    ## ref:
    ##
    ## existingSecret: name-of-existing-secret
    ##
    existingSecret: pre-prod-mongodb-secret

    ## Mount credentials as files instead of using environment variables
    ##
    usePasswordFile: false

    ## Number of MongoDB(R) Shards
    ## ref: https://docs.mongodb.com/manual/core/sharded-cluster-shards/
    ##
    shards: 2

    ## Shard replica set properties
    ## ref: https://docs.mongodb.com/manual/replication/index.html
    ##
    shardsvr:
      ## Properties for data nodes (primary and secondary)
      ##
      dataNode:
        ## Number of replicas. A value of replicas=1 is simply a primary node
        ##
        replicas: 1
        ## Node labels for pod assignment
        ## ref: https://kubernetes.io/docs/user-guide/node-selection/
        ## You can set dataNodeLoopId (or any other parameter) by setting the below code block under this 'nodeSelector' section:
        ## nodeSelector: { shardId: "{{ .dataNodeLoopId }}" }
        ##
        nodeSelector:
          type: "dedicated"
        ## Tolerations for pod assignment
        ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
        ## You can set dataNodeLoopId (or any other parameter) by setting the below code block under this 'nodeSelector' section:
        ## tolerations:
        ## - key: "shardId"
        ##   operator: "Equal"
        ##   value: "{{ .dataNodeLoopId }}"
        ##   effect: "NoSchedule"
        ##
        tolerations:
          - key: "db"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"

      ## Enable persistence using Persistent Volume Claims
      ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
      ##
      persistence:
        enabled: true
        ## The path the volume will be mounted at, useful when using different
        ## MongoDB(R) images.
        ##
        mountPath: /bitnami/mongodb

        ## The subdirectory of the volume to mount to, useful in dev environments
        ## and one PV for multiple services.
        ##
        subPath: ""

        ## mongodb data Persistent Volume Storage Class
        ## If defined, storageClassName: <storageClass>
        ## If set to "-", storageClassName: "", which disables dynamic provisioning
        ## If undefined (the default) or set to null, no storageClassName spec is
        ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
        ##   GKE, AWS & OpenStack)
        ##
        storageClass: "local-path"
        accessModes:
          - ReadWriteOnce
        ## PersistentVolumeClaim size
        ##
        size: 4Ti
        ## Additional volume annotations
        ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
        ##
        annotations: { }

    ## Config Server replica set properties
    ## ref: https://docs.mongodb.com/manual/core/sharded-cluster-config-servers/
    ##
    configsvr:
      ## Number of replicas. A value of replicas=1 is simply a primary node
      ##
      replicas: 1
      ## Node labels for pod assignment
      ## ref: https://kubernetes.io/docs/user-guide/node-selection/
      ##
      nodeSelector:
        type: "dedicated"
      ## Tolerations for pod assignment
      ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
      ##
      tolerations:
        - key: "db"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      ## Enable persistence using Persistent Volume Claims
      ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
      ##
      persistence:
        enabled: true
        ## The path the volume will be mounted at, useful when using different
        ## MongoDB(R) images.
        ##
        mountPath: /bitnami/mongodb

        ## The subdirectory of the volume to mount to, useful in dev environments
        ## and one PV for multiple services.
        ##
        subPath: ""

        ## mongodb data Persistent Volume Storage Class
        ## If defined, storageClassName: <storageClass>
        ## If set to "-", storageClassName: "", which disables dynamic provisioning
        ## If undefined (the default) or set to null, no storageClassName spec is
        ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
        ##   GKE, AWS & OpenStack)
        ##
        storageClass: "local-path"
        accessModes:
          - ReadWriteOnce
        ## PersistentVolumeClaim size
        ##
        size: 1Ti
        ## Additional volume annotations
        ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
        ##
        annotations: { }

    ## Mongos properties
    ## ref: https://docs.mongodb.com/manual/reference/program/mongos/#bin.mongos
    ##
    mongos:
      ## Use StatefulSet instead of Deployment
      ##
      useStatefulSet: true
      ## Node labels for pod assignment
      ## ref: https://kubernetes.io/docs/user-guide/node-selection/
      ##
      nodeSelector:
        type: "dedicated"
      ## Tolerations for pod assignment
      ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
      ##
      tolerations:
        - key: "db"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

    ## Kubernetes service type
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/
    ##
    service:
      ## Specify an explicit service name
      ##
      name: pre-prod-mongodb-service
      ## Additional service annotations (evaluate as a template)
      ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
      ##
      annotations:
        load-balancer.hetzner.cloud/location: "nbg1"
      ## Service type
      ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
      ##
      type: LoadBalancer
      ## MongoDB(R) Service port and Container Port
      ##
      port: 27017
      ## Specify the nodePort value for the LoadBalancer and NodePort service types.
      ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
      ##
      nodePort: 31922

    ## Prometheus Exporter / Metrics
    ##
    metrics:
      enabled: true

      ## Metrics exporter resource requests and limits
      ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
      ##
      # resources: {}

      ## Metrics exporter liveness and readiness probes
      ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
      ##
      readinessProbe:
        enabled: true
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 1
        failureThreshold: 3
        successThreshold: 1


      ## Prometheus Service Monitor
      ## ref: https://github.com/coreos/prometheus-operator
      ##      https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
      ##
      podMonitor:
        ## If the operator is installed in your cluster, set to true to create a PodMonitor entry
        ##
        enabled: true
        ## Specify the namespace in which the podMonitor resource will be created
        ##
        namespace: default
```
2. You will see the sharded-data-x failing 

**Expected behavior**
It should not allow you to set the value to a different one if this will lead you to an error 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.3-rancher3", GitCommit:"657df59bbba1d9e175cf5080d4885bd57d037906", GitTreeState:"clean", GoVersion:"go1.13.15"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```
