### ISSUE TITLE
[bitnami/grafana] 6.0.0 Chart can't get a valid version for repositories grafana

### ISSUE THREAD

**Issue by alex1989hu** [bitnami/charts#6816]
**Which chart**:
bitnami/grafana 6.0.0

**Describe the bug**
Can not download `6.0.0` Chart with `helm`. Error message is:

Error: can't get a valid version for repositories grafana. Try changing the version constraint in Chart.yaml

**To Reproduce**

1. Create `Chart.yaml` with content:

```yaml
apiVersion: v2
appVersion: "1.0"
description: foo
name: monitoring-grafana
version: 0.0.1
dependencies:
- name: grafana
  version: 6.0.0
  repository: "@bitnami"
```

2. Execute `helm dep up`

**Expected behavior**
bitnami/grafana can be downloaded

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Before this commit you can download Helm Chart, after this (currently the latest) you face with error message shared above: https://github.com/bitnami/charts/commit/d0c3553812aed6429796490c81111cce10b96239
