### ISSUE TITLE
Elasticsearch extraVolumes and extraVolumeMounts - how to apply via cli at install?

### ISSUE THREAD

**Issue by financefeast** [bitnami/charts#6839]
**Which chart**:
elasticsearch

**Describe the bug**
How to supply extraVolumes and extraVolumeMounts for an NFS share for the snapshot repository. The documentation states 

```
extraVolumes:
  - name: snapshot-repository
    nfs:
      server: nfs.example.com # Please change this to your NFS server
      path: /share1
extraVolumeMounts:
  - name: snapshot-repository
    mountPath: /snapshots
snapshotRepoPath: "/snapshots"
```
Which is normally specified in the values.yaml file. How do you apply this via the cli during install?

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+k3s1", GitCommit:"5a67e8dc473f8945e8e181f6f0b0dbbc387f6fca", GitTreeState:"clean", BuildDate:"2021-06-21T20:52:44Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+k3s1", GitCommit:"5a67e8dc473f8945e8e181f6f0b0dbbc387f6fca", GitTreeState:"clean", BuildDate:"2021-06-21T20:52:44Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by pablogalegoc** [comment]
Hi @financefeast,

See if this is what you are looking for: [The Format and Limitations of --set](https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set). In particular:
The line `--set servers[0].port=80,servers[0].host=example` becomes:
```yaml
servers:
  - port: 80
    host: example
```

**Comment by financefeast** [comment]
So for the example above I would get :
```
helm install elastic --set ingress.enabled=true,global.storageClass=nfs-client,snapshotRepoPath="/snapshots",extraVolumes=extraVolumes[0].name=snapshot-repository,extraVolumes[0].nfs.server=nfs.example.com,extraVolumes[0].nfs.path="/share1",extraVolumeMounts=extraVolumeMounts[0].name=snapshot-repository,extraVolumeMounts[0].mountPath="/snapshots" bitnami/elasticsearch
```

Running that gives the following error:
```
Error: failed parsing --set data: unable to parse key: interface conversion: interface {} is string, not []interface {}
```

**Comment by financefeast** [comment]
So after messing with this for far too long I decided to do the following :

Export the values.yaml
```
helm show values bitnami/elasticsearch > values.yaml
```
Edit the values.yaml and entered the volume config
```
extraVolumes:
  - name: snapshot-repository
    nfs:
      server: nfs.example.com # Please change this to your NFS server
      path: /share1
extraVolumeMounts:
  - name: snapshot-repository
    mountPath: /snapshots
snapshotRepoPath: "/snapshots"
```
Then install using the values file
```
helm install elasticsearch --set ingress.enabled=true,global.storageClass=nfs-client,snapshotRepoPath="/snapshots" -f values.yaml bitnami/elasticsearch
```
This might save someone some time.
