### ISSUE TITLE
rabbitmq chart does not work in IPv6 environments

### ISSUE THREAD

**Issue by nicolaerosia** [bitnami/charts#6845]
The Bitnami rabbitmq chart does not work in IPv6 environments.

More info here:
https://www.rabbitmq.com/networking.html#distribution-ipv6

I'm not sure what would be the elegant solution here, in my chart I've added a flag ipv6_only and I'm adding the following environment values based on it:
```
          {{- if .Values.ipv6_only }}
          - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
            value: "-kernel inetrc '/etc/rabbitmq/erl_inetrc' -proto_dist inet6_tcp"
          - name: RABBITMQ_CTL_ERL_ARGS
            value: "-proto_dist inet6_tcp"
          {{- end }}
```

A file has to be created as well, `/etc/rabbitmq/erl_inetrc` with:
```
{inet6, true}.
```

LE:
First part can be done with
```
extraEnvVars:
  - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
    value: "-kernel inetrc '/etc/rabbitmq/erl_inetrc' -proto_dist inet6_tcp"
  - name: RABBITMQ_CTL_ERL_ARGS
    value: "-proto_dist inet6_tcp"
```

not sure about the file creation though

**Comment by carrodher** [comment]
You're right, at chart level, something like what you are proposing should work, users can customize the arguments.
Although if it is something we want to support in a permanent way maybe the best approach is to create some specific environment variables for IPv6.

Then, the container image (https://github.com/bitnami/bitnami-docker-rabbitmq) should be adapted to 1) use the new environment variables and 2) create/modify the _/etc/rabbitmq/erl_inetrc_ file.

The source code of the Helm Chart and container image is publicly available on GitHub, just in case you want to contribute with this feature, the team will be happy to review the PRs and provide feedback. Otherwise, I can create an internal task to evaluate the addition of IPv6, but it is going to depend on other priorities the team have and I can't provide an ETA

**Comment by nicolaerosia** [comment]
@carrodher thank you for the guidance. Please open an internal task, in the mean time, I will also try to take a look, the scripts in the container image are quite big and I need to figure out exactly where I need to add what I need.

Thanks!

**Comment by carrodher** [comment]
Sure, thank you. I just created the internal task; we will update this issue when we've any new about the topic

**Comment by nicolaerosia** [comment]
I'm using the following workaround which seems to be working fine:
```
    - initContainers:
      - name: ipv6-init
        image: "docker.io/busybox:1.33.1"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: ipv6-cfg
          mountPath: /ipv6
        command: ['sh', '-c', 'echo "{inet6, true}." > /ipv6/erl_inetrc']
    - extraVolumes:
      - name: ipv6-cfg
        emptyDir: {}
    - extraVolumeMounts:
      - name: ipv6-cfg
        mountPath: /ipv6
    - extraEnvVars:
      - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
        value: "-kernel inetrc '/ipv6/erl_inetrc' -proto_dist inet6_tcp"
      - name: RABBITMQ_CTL_ERL_ARGS
        value: "-proto_dist inet6_tcp"
```
