### ISSUE TITLE
[bitnami/mongodb] Unable to enable external access after commonLabels was added

### ISSUE THREAD

**Issue by pstetsuk** [bitnami/charts#6857]
**Which chart**:
mongodb

**Describe the bug**
If `externalAccess.enabled=true` chart failed to install  
This issues was introduced by [[bitnami/mongodb] commonLabels](https://github.com/bitnami/charts/pull/6815)

**To Reproduce**

1. Configuration file `params.yaml`
```
architecture: replicaset
replicaCount: 1
arbiter:
  enabled: false
externalAccess:
  enabled: true
  service:
    type: NodePort
    domain: localhost
    nodePorts: [30017]
```
2. Execute command
```
helm install test-mongo -f params.yaml bitnami/mongodb
```

**Expected behavior**
MongoDB should be installed and external access should be enabled

**Actual behavior**
```
Error: template: mongodb/templates/replicaset/external-access-svc.yaml:17:18: executing "mongodb/templates/replicaset/external-access-svc.yaml" at <.Values.commonLabels>: can't evaluate field Values in type int
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
