### ISSUE TITLE
[bitnami/cassandra]Memlock configured to unlimited for cassandra helm chart

### ISSUE THREAD

**Issue by yasha-dev1** [bitnami/charts#6859]
**Which chart**:
bitnami/cassandra:7.6.2

**Is your feature request related to a problem? Please describe.**
The memlock should be configured to be unlimited. this could fix some performance issues and the issue that I have currently with not enough memlock in cassandra: 
**`Unable to lock JVM memory (ENOMEM). This can result in part of the JVM being swapped out, especially with mmapped I/O enabled. Increase RLIMIT_MEMLOCK or run Cassandra as root.`**

as I have seen the following: 

> I have no name!@cassandra-0:/$ cat proc/1/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        unlimited            unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             unlimited            unlimited            processes 
Max open files            1048576              1048576              files     
**Max locked memory         65536                65536                bytes**     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       63977                63977                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us        

in the documentation it is also recommended to set the rlimit to unlimited: https://docs.datastax.com/en/dse/6.8/dse-admin/datastax_enterprise/config/configRecommendedSettings.html#Setuserresourcelimits

**Describe the solution you'd like**
This can be easily managed in the `entrypoint.sh` or more elegant way is to use  OCI hooks or custom runtime handlers.
The best way is to change the /etc/security/limits.conf accordingly.

**Additional context**
also take a look at the [opened issue](https://github.com/kubernetes/kubernetes/issues/3595) from K8s. at the end there is a short term solution for using OCI hooks or custom runtime handlers.

**Comment by juan131** [comment]
Hi @yasha-dev1 

We expose the `jvm.maxHeapSize` and `jvm.newHeapSize` parameters that allow you to configure the JVM settings at JAVA level. You can also play with the `resources.limits` and `resources.requests` values to tell K8s how much memory and CPU you want to run the Cassandra pods.

Shouldn't that be enough to avoid hitting the `ENOMEM` issue?

**Comment by yasha-dev1** [comment]
hi @juan131 
I am aware of those parameters. I have set them at max (see below). But it hitting `ENOMEM`.
as I see in Grafana, the memory is being consumed more than the limit. so probably, it needs more memory as you suggested. I'm closing the issue for now. thanks for the reply. 


```
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 2.5
      memory: 15Gi
    requests:
      cpu: 2.5
      memory: 15Gi
```
```
  jvm:
  jvm:
    ## Extra JVM options
    ##
    extraOpts:

    ## Memory settings: These are calculated automatically unless specified otherwise
    ## To run on environments with little resources (<= 8GB), tune your heap settings:
    ## maxHeapSize:
    ## - calculate 1/2 ram and cap to 1024MB
    ## - calculate 1/4 ram and cap to 8192MB
    ## - pick the max
    ## newHeapSize:
    ## A good guideline is 100 MB per CPU core.
    ## - min(100 * num_cores, 1/4 * heap size)
    ## ref: https://docs.datastax.com/en/archived/cassandra/2.0/cassandra/operations/ops_tune_jvm_c.html
    ##
    maxHeapSize: 10G
   ## tried with 8GB too.
    newHeapSize: 1G
```
