### ISSUE TITLE
springboot connect rabbitmq 5672 error 

### ISSUE THREAD

**Issue by zhangwei900808** [bitnami/charts#6862]
I was used helm to install rabbitmq ，the below is my values.yaml
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
  hostName: rabbitmq.testapi.seaurl.com
#  path: /rabbitmq
  tls: true
  tlsSecret: rabbitmq-tls
persistence:
  storageClass: "alicloud-disk-ssd"
  size: 20Gi
```

and it is work 
![image](https://user-images.githubusercontent.com/4385154/124590026-3ff97480-de8d-11eb-8e14-ff3ccddb571d.png)

and I used k8s dns rabbitmq address it is work

application.yml
```
spring:
  rabbitmq:
    host: test-rabbitmq-headless.rabbit.svc.cluster.local
    port: 5672
    username:
    password:
```

but when I used ```mvn spring-boot:run``` is not work 
application.yml
```
spring:
  rabbitmq:
    host: rabbitmq.testapi.seaurl.com
   # 5672 is not work yet
    port: 80
    username:
    password:
```
version:
helm: v3.6.0
chart：6.18.2，
APP：3.8.2

**Comment by rafariossaa** [comment]
Hi,
  By the screenshot you provided, I think the rabbitmq is served on a `https://....:433/` and by the spring-boot I would tell that you are using http on port 80.
  Could you check that ?

**Comment by zhangwei900808** [comment]
@rafariossaa I used 443 but it is not work
```
spring:
  rabbitmq:
    host: rabbitmq.testapi.seaurl.com
    port: 443
    username:
    password: 
```

**Comment by zhangwei900808** [comment]
![image](https://user-images.githubusercontent.com/4385154/124766626-abb10f80-df69-11eb-832d-4faec964f9c4.png)

**Comment by zhangwei900808** [comment]
@rafariossaa How can I fix it

**Comment by zhangwei900808** [comment]
when I used ```k port-forward -n rabbit svc/test-rabbitmq 5672:5672``` is work ,
```
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username:
    password:
```
but when I used hostname it is still not work
