### ISSUE TITLE
[bitnami/postgresql] No metric for replication from under default user

### ISSUE THREAD

**Issue by CarTerr** [bitnami/charts#6874]
**Which chart**:
postgresql 
Chart version: 10.5.2

**Describe the bug**
No metric for replication from under the user repl_user

**To Reproduce**

values.yaml
```
postgresql:
  postgresqlDatabase: test
  postgresqlUsername: test
  postgresqlPassword: test
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: monitoring
    customMetrics:
      pg_replication:
        query: "select state from pg_stat_replication AS state"
        master: true
        metrics:
          - state:
              usage: "GAUGE"
              description: "Replication state"

  replication:
    enabled: true
    user: repl_user
    password: repl_password
```
In postgres-master pod execute command
`curl http://172.17.0.12:9187/metrics | grep "pg_replication_state"`

I get
```
# TYPE pg_replication_state gauge
pg_replication_state{server="127.0.0.1:5432"} NaN
```

If execute query `select state from pg_stat_replication AS state` from under the user repl_user, I get
```
 state 
-------
 
(1 row)
```

If execute query `select state from pg_stat_replication AS state` from under the user posrtgres, I get
```
 state 
-------
streaming 
(1 row)
```

**Comment by marcosbc** [comment]
Hi @CarTerr, it looks like some sort of ACL limitation on the PostgreSQL side. You should be able to fix it like [this](https://www.postgresql.org/message-id/CANUg7LBdmn2RE%3DzwNCSG78obj0hPteADQZXsz%2B7BbfPapdzAdA%40mail.gmail.com):

```
GRANT SELECT ON public.pg_stat_repl TO repl_user;
```

You can include it as a [custom initdb script](https://github.com/bitnami/charts/tree/master/bitnami/postgresql#initialize-a-fresh-instance) to automate the deployment if you need.

**Comment by CarTerr** [comment]
why the correct grands are not being use in helm chart by default?

If I take another database (Mysql example), I get the correct replication metric, in contrast to postgres.
And maybe other people do not know about this problem and use the wrong metrics

**Comment by CarTerr** [comment]
Hi @marcosbc It didn't work for postgres_exporter
I get NaN in metrics
```
pg_replication_state{server="127.0.0.1:5432"} NaN
pg_stat_replication_pg_wal_lsn_diff{application_name="my_application",client_addr="",server="127.0.0.1:5432",slot_name="183",state=""} NaN
```

**Comment by marcosbc** [comment]
Hi @CarTerr, sorry to hear that. Did you try all the commands mentioned in the [guide](https://www.postgresql.org/message-id/CANUg7LBdmn2RE%3DzwNCSG78obj0hPteADQZXsz%2B7BbfPapdzAdA%40mail.gmail.com)? I just noticed that I had described that a simple grant was enough, but they were including more logic.

In any case, I just came across a page describing some [improvements in PostgreSQL 10](https://pganalyze.com/blog/whats-new-in-postgres-10-monitoring-improvements) that you may try to execute, and see if they solve this issue. Could you try this?

I would also recommend you to try and check if running the query as `repl_user` directly inside the psql console works, or if it shows a different value.

**Comment by CarTerr** [comment]
I find that sidecar container (postgres_exporter) connect to master postgres with user postgresqlUsername (my case -- test) , but not user in section replication: user: (my case -- repl_user)

**Comment by marcosbc** [comment]
Hi @CarTerr, did you check the post I shared in my previous comment? ([link](https://pganalyze.com/blog/whats-new-in-postgres-10-monitoring-improvements)) - It includes a specific command you can execute to grant such ownership to the PostgreSQL user.

**Comment by CarTerr** [comment]
Yes, I checked. It works.
Also found that the container postgres_exporter is connecting to the database with the wrong user. In my case, the user is test, but the correct user should be repl_user

**Comment by marcosbc** [comment]
Hi @CarTerr, nice to know it worked!

As for the user, actually my understanding is that the `postgresqlUsername` value should be the one used. That is because the replication user is only meant to serve as the user for PostgreSQL replica nodes to connect to the primary node. And the `postgresqlUsername` is the one you are supposed to be "exposing" as part of the deployment, i.e. to be used for any type of queries.

**Comment by CarTerr** [comment]
I solved this problem like this:

```
postgresql:
 initdbScripts:
  my_init_script.sh: |
  #!/bin/bash
  . /opt/bitnami/scripts/libpostgresql.sh
  echo "ALTER USER \"$POSTGRES_USER\" WITH SUPERUSER;" | postgresql_execute
```
 
and add the metric:

```
postgresql:
  metrics:
    enabled: true
    customMetrics:
      pg_replication:
        query: "select state from pg_stat_replication AS state"
        master: true
        metrics:
          - state:
              usage: "GAUGE"
              description: "Replication state"
```
