### ISSUE TITLE
Contour https port is not listened

### ISSUE THREAD

**Issue by VA-PLE** [bitnami/charts#6889]
**Which chart**:
contour

**Describe the bug**
The https port (443) is not listened to after installation. http works fine.

**My values**
```
contour:
  nodeSelector:
    contour: "yes"

replicaCount: 1

prometheus:
  serviceMonitor:
    enabled: true

envoy:
  nodeSelector:
    contour: "yes"

  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  terminationGracePeriodSeconds: 15

  service:
    type: NodePort
```
**netstat -nelp | grep envoy**
```
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      0          547149754  565780/envoy        
tcp        0      0 0.0.0.0:8002            0.0.0.0:*               LISTEN      0          547149759  565780/envoy        
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      0          547149738  565780/envoy 
```

**curl -i http://mytest.com**:
```
HTTP/1.1 204 No Content
ad-exchange-error-message: Internal Error
date: Thu, 08 Jul 2021 11:39:53 GMT
x-envoy-upstream-service-time: 7
server: envoy
```

**curl -i https://mytest.com**:
```
curl: (7) Failed to connect to mytest.com port 443: connection refused
```

Any ideas what the problem might be?
