### ISSUE TITLE
Airflow 404 = lots of circles

### ISSUE THREAD

**Issue by Nazar-Petsentii** [bitnami/charts#6890]
**Which chart**: bitnami/airflow current version (10.2.2)
The name (and version) of the affected chart

**Describe the bug** Providing internet access to airflow web via ingress settings set in values.yaml (they are almost default) raise Airflow 404 = lots of circles error with nothing else. However manually chaning airflow service type from clusterIp to loadbalancer (using oracle oke and ingress nginx controller default) - everything works.

**To Reproduce** 1.installed via "helm install bitnami/airflow" 
2. changed values in a values.file and applied them ( connected to postgres and redis running in a cluster)
3. Changed ingress values in a values.yaml file

**Expected behavior**

**Version of Helm and Kubernetes**: 3.3.4 1.19

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context** Here are ingress values 
```yaml
ingress:
  enabled: true
  apiVersion: networking.k8s.io/v1beta1
  pathType: ImplementationSpecific
  certManager: false  
```
  If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
   If certManager is set to true, annotation kubernetes.io/tls-acme: "true" will automatically be set
   Example:
 `kubernetes.io/ingress.class: nginx`

```yaml
  annotations:
    kubernetes.io/ingress.class: nginx
```
  Most likely this will be just one host, but in the event more hosts are needed, this is an array
``` yaml
  hosts:
    - name: ""
      path: /airflow
```
everything else is default.
