### ISSUE TITLE
[bitnami/minio] Ingress annotations not being applied

### ISSUE THREAD

**Issue by emmanuelm41** [bitnami/charts#6896]
**Which chart**:
MinIO chart, version 7.1.1

**Describe the bug**
I wanted to set some annotations for ingress, but they do not seem to be applied.

**To Reproduce**

1. Deploy the chart with the following values (change the ingress url!):
```
# This file and all contents in it are OPTIONAL.

# The namespace this chart will be installed to,
# if not specified the chart will be installed to "default"
namespace: dev

# Custom helm options
helm:
  # The release name to use. If empty a generated release name will be used
  releaseName: minio

  # The directory of the chart in the repo.  Also any valid go-getter supported
  # URL can be used there is specify where to download the chart from.
  # If repo below is set this value if the chart name in the repo
  chart: "minio"

  # An https to a valid Helm repository to download the chart from
  repo: "https://charts.bitnami.com/bitnami"

  # Used if repo is set to look up the version of the chart
  version: "7.1.1"

  # Force recreate resource that can not be updated
  force: false

  # How long for helm to wait for the release to be active. If the value
  # is less that or equal to zero, we will not wait in Helm
  timeoutSeconds: 600

  # Custom values that will be passed as values.yaml to the installation
  values:
    image:
      tag: 2021.6.17

    mode: standalone

    existingSecret: minio-storage

    podAnnotations:
      app: minio

    ingress:
      enabled: true
      hostname: minio.dev.ingress.net
      tls: true
      certManager: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        nginx.ingress.kubernetes.io/proxy-body-size: 0

    persistence:
      enabled: true
      mountPath: /data
      storageClass: local-path
      accessModes:
        - ReadWriteOnce
      size: 100Gi

    nodeSelector:
      type: dedicated

    networkPolicy:
      enabled: false
      allowExternal: true

    metrics:
      serviceMonitor:
        enabled: true

```
2. Check the annotations on the created ingress, and you will not see them there.

**Expected behavior**
The annotations should be there. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.3-rancher3", GitCommit:"657df59bbba1d9e175cf5080d4885bd57d037906", GitTreeState:"clean", GoVersion:"go1.13.15"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by marcosbc** [comment]
Hi @emmanuelm41, if I run the following command:

```
$ helm template my-minio --set mode=standalone --set existingSecret=minio-storage --set podAnnotations.app=minio --set ingress.enabled=true,'ingress.annotations.cert-manager\.io/cluster-issuer=letsencrypt-production','ingress.annotations.nginx\.ingress\.kubernetes\.io/proxy-body-size=0',ingress.certManager=true,ingress.tls=true,ingress.hostname=minio.dev.ingress.net .
```

Then I can see the following Ingress object:

```yaml
# Source: minio/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-minio
  namespace: default
  labels:
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-7.1.3
    app.kubernetes.io/instance: my-minio
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-body-size: 0
...
```

As you can see, the annotations are added properly. Could you check if I'm missing anything?
