### ISSUE TITLE
[bitnami/redis] PSP referenced by Role does not match created PSP

### ISSUE THREAD

**Issue by lingwooc** [bitnami/charts#6897]
**Which chart**:
redis:14.6.6

**Describe the bug**
Enable rbac, service account, pod security policy on a cluster with PSPs enabled and replica.replicaCount: 0. The master pod will fail to deploy due to the psp. This is because the PSP referenced by the role (xxxx-redis) does not exist. Its called xxxx-redis-master.

The role defined looks like this.
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xxx-redis
rules:
- apiGroups:
  - policy
  resourceNames:
  - xxx-redis
  resources:
  - podsecuritypolicies
  verbs:
  - use
```
But the psp is named xxx-redis-master so it can't work.
**To Reproduce**
Create a cluster with PSPs enabled.
Deploy redis (as a subchart) with the following options.
```
redis:
  replica:
    replicaCount: 0
  podSecurityPolicy:
    enabled: true
    create: true
  rbac:
    create: true
  serviceAccount:
    create: true
    name: redis
```
\+ other keys to make it work in your env if needed.

Judging by the chart I don't think the replica count is relevant but I've not tried it with replicas. It should work either way.
**Expected behavior**
Pod deploys.

**Additional context**
A simple work around is to add:
```
  rbac:
    rules:
      - apiGroups:
        - policy
        resourceNames:
        - xxxx-redis-master
        resources:
        - podsecuritypolicies
        verbs:
        - use
```
