### ISSUE TITLE
[bitnami/rabbitmq] Merging multiple definitions.json ?

### ISSUE THREAD

**Issue by olivierboudet** [bitnami/charts#6926]
**Which chart**:
Rabbitmq

**Is your feature request related to a problem? Please describe.**
I am using definitions import for queues, exchanges and some policies. So, I have a custom image with a raw definitions.json in there which includes all objects that must be presents in all our environments.
But some resources may be present only on some environment or may be a little different and must be configured for each (example: users, passwords, specific policies, etc).

**Describe the solution you'd like**
At the moment, i am using a forked version of the chart. There is an initContainer which merges some declarations in values with the definitions.json already existing in the image.

Example :
```
definitions:
  users: |-
   {
     "name": "user1",
     "password": "pwd1",
     "tags": ""
   },
   {
     "name": "user2",
     "password": "pwd2",
     "tags": ""
   }
```
```
      initContainers:
        - name: merge-definitions
          image: stedolan/jq
          command: ['sh', '-c', "jq -s '.[0] * .[1]' /image-definitions.json /k8s-definitions/definitions.json  > /etc/rabbitmq/definitions.json"]
          volumeMounts:
            - name: definitions
              mountPath: /k8s-definitions
```
Does a PR with this feature can be interesting ?
