### ISSUE TITLE
[bitnami/magento] Magento not accessible via Reverse Proxy - infinite redirects

### ISSUE THREAD

**Issue by hussam-qasem** [bitnami/charts#6928]
**Which chart**: `magento-18.1.5`

**Describe the bug**
I'm unable to access Magento frontend or admin URI when set up with a self-provisioned edge - an Apache Web Server, running as a reverse proxy. I get infinite redirects (Chrome: ERR_TOO_MANY_REDIRECTS)

This is a private Kubernetes cluster. None of the nodes have a public IP address. External clients do not access cluster nodes directly. Only the edge component has a public IP address, and it's setup to forward all HTTPS traffic to Kubernetes nodes port 30443 (HTTP to port 30080 for now).

My Apache `conf` attached at the bottom.

**To Reproduce**

1. Kubernetes on a Bare-metal server
2. Create a sample `values.yaml` file.
```YAML
image:
  debug: true
magentoHost: eshop.uat.internal-domain.com
magentoPassword: Bitnami1
magentoAdminUri: admin
# magentoUseHttps: true
# magentoUseSecureAdmin: true
persistence:
  enabled: false
containerPorts:
  http: 8080
  https: 8443
service:
  type: NodePort
  port: 80
  httpsPort: 443
  targetPorts:
    http: 8080
    https: 8443
  nodePorts:
    http: 30080
    https: 30443
  # externalTrafficPolicy: Local
extraEnvVars:
  - name: EXTERNAL_HTTP_PORT_NUMBER
    value: "80"
  - name: EXTERNAL_HTTP_PORT_NUMBER
    value: "443"
elasticsearch:
  master:
    persistence:
      enabled: false
  data:
    persistence:
      enabled: false
mariadb:
  auth:
    rootPassword: Covid-19
    password: Hello2021
  primary:
    persistence:
      enabled: false
```
3. Create a namespace (optional) and install via `helm`
```Shell
helm repo add bitnami https://charts.bitnami.com/bitnami

helm install demo bitnami/magento -n demo --create-namespace -f values.yaml
```

**Expected behavior**
Magento frontend loads normally.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
My `magento.conf` looks like:
```ApacheConf
<VirtualHost eshop.uat.internal-domain.com:80>
        ServerName eshop.uat.internal-domain.com
        Header add Set-Cookie: "ROUTEID=.%{BALANCER_WORKER_ROUTE}e; path=/" env=BALANCER_ROUTE_CHANGED
        <Proxy balancer://k8s>
                BalancerMember http://10.0.0.50:30080 route=route1 keepalive=On ping=1 ttl=60
                BalancerMember http://10.0.0.51:30080 route=route2 keepalive=On ping=1 ttl=60
                BalancerMember http://10.0.0.52:30080 route=route3 keepalive=On ping=1 ttl=60
                ProxySet lbmethod=bytraffic
                ProxySet stickysession=ROUTEID
        </Proxy>
        ProxyPass / balancer://k8s/ stickysession=ROUTEID
        ProxyPassReverse / balancer://k8s/
</VirtualHost>
```

![MagentoSetup](https://user-images.githubusercontent.com/68053227/125283600-3fdff580-e321-11eb-97d3-f727d810a154.png)
