### ISSUE TITLE
pull secrets don't get deduped

### ISSUE THREAD

**Issue by Morriz** [bitnami/charts#6929]
**Which chart**:
common@5.8.1 (same code as in master)

**Describe the bug**

When providing the same pull secret via multiple ways those don't get deduped:

```yaml
global:
  imagePullSecrets:
    - otomi-pullsecret-global
image:
  pullSecrets:
    - otomi-pullsecret-global
imagePullSecrets:
  - otomi-pullsecret-global
```

And this results in duplicate entries in the `spec.imagePullSecrets` array, which is supposed to hold unique values.
