### ISSUE TITLE
AWS RDS Postgres - failed to initialize database

### ISSUE THREAD

**Issue by harrishcris** [bitnami/charts#6935]
Hello,

I'm trying to get Harbor to use Postgres running in AWS RDS however the core pod keeps failing once I tell helm to use an external Postgres DB.

Error in core:
```
2021-07-13T10:57:12Z [INFO] [/common/dao/base.go:65]: Registering database: type-PostgreSQL host-REMOVED.REMOVED.eu-west-1.rds.amazonaws.com port-5432 database- sslmode-"disable"
[ORM]2021/07/13 10:57:12 register db Ping `default`, pq: database "sslmode=disable" does not exist
2021-07-13T10:57:12Z [FATAL] [/core/main.go:185]: failed to initialize database: register db Ping `default`, pq: database "sslmode=disable" does not exist
```

My values.yaml file:
```
postgresql:
  enabled: false
externalDatabase:
  host: REMOVED.REMOVED.eu-west-1.rds.amazonaws.com
  password: REMOVED
  user: REMOVED
```

Cloudformation template for RDS:
```
  PostgreRDSDatabase:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceClass: db.t3.micro
      Engine: postgres
      AllowMajorVersionUpgrade: false
      MasterUsername: REMOVED
      MasterUserPassword: REMOVED
      AllocatedStorage: 10
      DBSubnetGroupName: !Ref PostgreRDSDatabaseDBSubnetGroup
      VPCSecurityGroups:
        - !Ref PostgreRDSDatabaseSecurityGroup
```

I've manually run the following to create the required databases in Postgres:
```
CREATE DATABASE notaryserver;
CREATE USER server;
alter user server with encrypted password 'password';
GRANT ALL PRIVILEGES ON DATABASE notaryserver TO server;
CREATE DATABASE notarysigner;
CREATE USER signer;
alter user signer with encrypted password 'password';
GRANT ALL PRIVILEGES ON DATABASE notarysigner TO signer;
CREATE DATABASE registry ENCODING 'UTF8';
\c registry;
CREATE TABLE schema_migrations(version bigint not null primary key, dirty boolean not null);
```

I've tried changing the externalDatabase.host to something invalid and it's comes back with a `no such host` and if I enter an incorrect username or passsord I get an `authentication failed` so I know it's connecting into the database but there must be a configuration issue somewhere it doesn't like.

Any ideas?

**Comment by javsalgar** [comment]
Hi,

I see that you closed the issue. Could you confirm if it was fixed?

**Comment by harrishcris** [comment]
@javsalgar Thanks, yes this is now resolved, adding the following values resolved the issue:

```
externalDatabase:
  coreDatabase: registry
  notaryServerDatabase: notaryserver
  notarySignerDatabase: notarysigner
```
