### ISSUE TITLE
[bitnami/magento] occasionally Magento pod would fail upon inital install

### ISSUE THREAD

**Issue by hussam-qasem** [bitnami/charts#6949]
**Which chart**: magento-18.1.6

**Describe the bug**
Occasionally the Magento pod would crash upon initial install after `Catalog Search index process`. Sometimes it would restart and fix itself after one or two restarts and other times, it would fail with an Error.

**To Reproduce**

1. Create `values.yaml` file
```YAML
image:
  debug: true
magentoHost: eshop.uat.internal-domain.com
magentoPassword: Bitnami1
magentoAdminUri: admin
magentoUseHttps: true
magentoUseSecureAdmin: true
persistence:
  enabled: false
containerPorts:
  http: 8080
  https: 8443
service:
  type: NodePort
  port: 80
  httpsPort: 443
  targetPorts:
    http: 8080
    https: 8443
  nodePorts:
    http: 30080
    https: 30443
elasticsearch:
  master:
    persistence:
      enabled: false
  data:
    persistence:
      enabled: false
mariadb:
  auth:
    rootPassword: Covid-19
    password: Hello2021
  primary:
    persistence:
      enabled: false
```
2. Install with `helm`
```Shell
helm upgrade demo bitnami/magento --install -n demo --create-namespace -f values.yaml --wait
```
3. Inspect Pod logs, and you'll see:
```
magento 13:45:21.08 INFO  ==> Reindexing
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Product EAV index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Inventory index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:00
Catalog Search index process unknown error:
{"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [indices:admin/delete] would be [126642490/120.7mb], which is larger than the limit of [123273216/117.5mb], real usage: [126642360/120.7mb], new bytes reserved: [130/130b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=130/130b, model_inference=0/0b, accounting=0/0b]","bytes_wanted":126642490,"bytes_limit":123273216,"durability":"TRANSIENT"}],"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [indices:admin/delete] would be [126642490/120.7mb], which is larger than the limit of [123273216/117.5mb], real usage: [126642360/120.7mb], new bytes reserved: [130/130b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=130/130b, model_inference=0/0b, accounting=0/0b]","bytes_wanted":126642490,"bytes_limit":123273216,"durability":"TRANSIENT"},"status":429}
```
or
```
Catalog Search index process unknown error:
null
```

**Expected behavior**
`Catalog Search index has been rebuilt successfully`, and Pod would print the following log:
```
magento 10:14:05.39 INFO  ==> Reindexing
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Product EAV index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Inventory index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:00
magento 10:14:21.65 INFO  ==> Flushing cache
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
