### ISSUE TITLE
[Keycloak] Problem with Linkerd and external database

### ISSUE THREAD

**Issue by MatteoGioioso** [bitnami/charts#6953]
**Which chart**:
```
 name: keycloak
 version: 3.1.1
```

**Describe the bug**
I am using the Keycloak chart with an external database setup.
Everything works nicely, however when I try to use it with linkerd the keycloak pod crash and I suspect it is because mTLS, this is the error I get:

```
[org.jboss.jca.core.connectionmanager.pool.strategy.OnePool] (ServerService Thread Pool -- 63) IJ000604: Throwable while attempting to get a new connection: null: javax.resource.ResourceException: IJ031084: Unable to create connection
...
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
...
Caused by: java.net.SocketException: Connection reset
...
```

**To Reproduce**

Chart dependencies:

```
  - name: keycloak
    version: 3.1.1
    repository: https://charts.bitnami.com/keycloak
  - name: postgresql
    version: 10.5.1
    repository: https://charts.bitnami.com/bitnami
```

Values:

```
postgresql:
 postgresqlPassword: postgres
 primary:
    podAnnotations:
       linkerd.io/inject: enabled
keycloak:
   podAnnotations:
      linkerd.io/inject: enabled
   externalDatabase:
     port: 5432
     database: keycloak
     host: <chart name>-postgresql
     password: postgres
     user: postgres
```

And I am deploying everything to a namespace `helm upgrade -i  mynamespace . -f values.yaml`.
I suspect that the mTLS is the responsible for this and somehow the `externalDatabase.host` value provided by me is wrong. 
I have tried to put `https` in front, but it did not work.

Someone has encounter this before? Thanks!

**Expected behavior**
Should connect to the external database

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}   
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by rafariossaa** [comment]
Hi,
  I am not familiar with linkerd, but I think the issue here could be related to the use of it.
  Is linkerd a http/https proxy or does is also handle postgresql protocol ?
  I am asking because of this:
```
postgresql:
 postgresqlPassword: postgres
 primary:
    podAnnotations:
       linkerd.io/inject: enabled
```

**Comment by MatteoGioioso** [comment]
Hey,
according to this it should handle it: https://linkerd.io/2.10/features/protocol-detection/

**Comment by rafariossaa** [comment]
Hi,
 OK, 
 Please, don't hesitate to come back with your findings.

**Comment by MatteoGioioso** [comment]
Ok, seems like I have managed to solve it, I am still not sure 100% how it works though.

I think the _problem_ was related in how Keycloak discovers services, you can read more here: https://www.keycloak.org/2019/05/keycloak-cluster-setup.html

Apparently, in my case or in the case of this chart, it is using `TCPPING` which will use TCP protocol with **7800** port (7600 with old keycloak versions 12 <) to discover other instances.

So all I needed to do was to skip that port in outbound and inbound:

```
  postgresql:
    primary:
      podAnnotations:
        linkerd.io/inject: enabled
  keycloak:
    podAnnotations:
      linkerd.io/inject: enabled
      config.linkerd.io/skip-inbound-ports: "7800" # skip keycloak cluster discovery
      config.linkerd.io/skip-outbound-ports: "7800"
```
And with this now I can use linkerd mTLS without problem, at least for now =).

I will test a bit more and if everything works nicely I will close this issue.
Thanks
