### ISSUE TITLE
[bitnami/mongodb] mongodb fails to start in replicaset

### ISSUE THREAD

**Issue by Andrei-Stepanov** [bitnami/charts#6980]
**Which chart**:
```
NAME                   	CHART VERSION	APP VERSION   	DESCRIPTION                                       
bitnami/mongodb        	10.22.0      	4.4.6         	NoSQL document-oriented database that stores JS...
```

**Describe the bug**
Primary container says:

```
> rs.status()
{
	"ok" : 0,
	"errmsg" : "no replset config has been received",
	"code" : 94,
	"codeName" : "NotYetInitialized"
}

> db.stats()
{
	"topologyVersion" : {
		"processId" : ObjectId("60f14fcccb8523c605eec5d0"),
		"counter" : NumberLong(0)
	},
	"ok" : 0,
	"errmsg" : "node is not in primary or recovering state",
	"code" : 13436,
	"codeName" : "NotPrimaryOrSecondary"
}

> db.getReplicationInfo()
{ "errmsg" : "replication not detected" }

> db.hello()
{
	"topologyVersion" : {
		"processId" : ObjectId("60f14fcccb8523c605eec5d0"),
		"counter" : NumberLong(0)
	},
	"isWritablePrimary" : false,
	"secondary" : false,
	"info" : "Does not have a valid replica set config",
	"isreplicaset" : true,
	"maxBsonObjectSize" : 16777216,
	"maxMessageSizeBytes" : 48000000,
	"maxWriteBatchSize" : 100000,
	"localTime" : ISODate("2021-07-16T09:28:58.630Z"),
	"logicalSessionTimeoutMinutes" : 30,
	"connectionId" : 95,
	"minWireVersion" : 0,
	"maxWireVersion" : 9,
	"readOnly" : false,
	"ok" : 1
}
```

```
oc rsh  -c mongodb db-stage-mongodb-0 bash                             

1001087071@db-stage-mongodb-0:/$ env | grep -i MONGO
DB_STAGE_MONGODB_1_EXTERNAL_PORT=tcp://masked
DB_STAGE_MONGODB_METRICS_SERVICE_HOST=masked
DB_STAGE_MONGODB_0_EXTERNAL_PORT_27017_TCP_PROTO=tcp
DB_STAGE_MONGODB_0_EXTERNAL_PORT=masked
HOSTNAME=db-stage-mongodb-0
DB_STAGE_MONGODB_METRICS_PORT_9216_TCP_ADDR=masked
DB_STAGE_MONGODB_1_EXTERNAL_SERVICE_PORT=27017
DB_STAGE_MONGODB_METRICS_PORT_9216_TCP=tcp://masked:9216
DB_STAGE_MONGODB_0_EXTERNAL_SERVICE_PORT=27017
DB_STAGE_MONGODB_1_EXTERNAL_PORT_27017_TCP_PORT=27017
DB_STAGE_MONGODB_0_EXTERNAL_SERVICE_PORT_MONGODB=27017
MONGODB_DISABLE_SYSTEM_LOG=no
K8S_SERVICE_NAME=db-stage-mongodb-headless
DB_STAGE_MONGODB_1_EXTERNAL_PORT_27017_TCP_PROTO=tcp
DB_STAGE_MONGODB_0_EXTERNAL_PORT_27017_TCP=tcp://masked:27017
DB_STAGE_MONGODB_1_EXTERNAL_PORT_27017_TCP_ADDR=masked
DB_STAGE_MONGODB_METRICS_PORT_9216_TCP_PROTO=tcp
MONGODB_ENABLE_IPV6=no
DB_STAGE_MONGODB_METRICS_PORT=tcp://masked:9216
DB_STAGE_MONGODB_0_EXTERNAL_PORT_27017_TCP_ADDR=masked
DB_STAGE_MONGODB_1_EXTERNAL_PORT_27017_TCP=tcp://masked:27017
DB_STAGE_MONGODB_1_EXTERNAL_SERVICE_HOST=masked
DB_STAGE_MONGODB_1_EXTERNAL_SERVICE_PORT_MONGODB=27017
MONGODB_REPLICA_SET_NAME=rs-stage
MY_POD_NAME=db-stage-mongodb-0
DB_STAGE_MONGODB_0_EXTERNAL_SERVICE_HOST=masked
MONGODB_INITIAL_PRIMARY_HOST=db-stage-mongodb-0.db-stage-mongodb-headless.masked.svc.cluster.local
BITNAMI_APP_NAME=mongodb
DB_STAGE_MONGODB_METRICS_SERVICE_PORT=9216
DB_STAGE_MONGODB_0_EXTERNAL_PORT_27017_TCP_PORT=27017
MONGODB_ENABLE_JOURNAL=yes
MONGODB_ROOT_PASSWORD=masked
MONGODB_ENABLE_DIRECTORY_PER_DB=yes
DB_STAGE_MONGODB_METRICS_PORT_9216_TCP_PORT=9216
MONGODB_SYSTEM_LOG_VERBOSITY=0
MONGODB_DISABLE_JAVASCRIPT=no
MONGODB_REPLICA_SET_KEY=masked
DB_STAGE_MONGODB_METRICS_SERVICE_PORT_HTTP_METRICS=9216
PATH=/opt/bitnami/common/bin:/opt/bitnami/mongodb/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

```
cat values-db-cs-stage.yaml
---

# https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml

global:
  imageRegistry: quay.io

arbiter:
    containerSecurityContext:
        # must be in the ranges: [1001080000, 1001089999]
        runAsUser: 1001087071
    podSecurityContext:
        fsGroup: ~
podSecurityContext:
  fsGroup: ~
containerSecurityContext:
    # must be in the ranges: [1001080000, 1001089999]
    runAsUser: 1001087071
commonLabels:
    app.kubernetes.io/component: mongodb-stage
    app.kubernetes.io/instance: mongodb-stage
    app.kubernetes.io/name: mongodb-stage
architecture: replicaset
auth:
    enabled: true
    rootPassword: "masked"
    replicaSetKey: "masked"
replicaSetName: rs-stage
directoryPerDB: true
extraEnvVars:
    - name: ALLOW_EMPTY_PASSWORD
      value: "yes"
externalAccess:
    enabled: true
    port: 27017
    service:
        type: NodePort
        nodePorts:
            - 30991
            - 30992
        domain: masked
persistence:
    size: 5Gi
metrics:
    enabled: true
```

```
oc logs db-stage-mongodb-0 -c mongodb
Advertised Hostname: masked
Pod name matches initial primary pod name, configuring node as a primary
mongodb 09:22:20.43 
mongodb 09:22:20.43 Welcome to the Bitnami mongodb container
mongodb 09:22:20.44 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 09:22:20.44 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 09:22:20.44 
mongodb 09:22:20.44 INFO  ==> ** Starting MongoDB setup **
mongodb 09:22:20.46 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 09:22:20.46 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mongodb 09:22:20.47 INFO  ==> Initializing MongoDB...
mongodb 09:22:20.50 INFO  ==> Enabling authentication...
mongodb 09:22:20.51 INFO  ==> Deploying MongoDB with persisted data...
mongodb 09:22:20.51 INFO  ==> Writing keyfile for replica set authentication...
mongodb 09:22:20.54 INFO  ==> ** MongoDB setup finished! **

mongodb 09:22:20.56 INFO  ==> ** Starting MongoDB **

{"t":{"$date":"2021-07-16T09:22:20.593+00:00"},"s":"I",  "c":"CONTROL",  "id":20698,   "ctx":"main","msg":"***** SERVER RESTARTED *****"}
{"t":{"$date":"2021-07-16T09:22:20.594+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
{"t":{"$date":"2021-07-16T09:22:20.597+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2021-07-16T09:22:20.598+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
{"t":{"$date":"2021-07-16T09:22:20.598+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2021-07-16T09:22:20.639+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/bitnami/mongodb/data/db","architecture":"64-bit","host":"db-stage-mongodb-0"}}
```

```
ps ax
    PID TTY      STAT   TIME COMMAND
      1 ?        SLsl   0:07 /opt/bitnami/mongodb/bin/mongod --config=/opt/bitnami/mongodb/conf/mongodb.conf
```

```
cat /opt/bitnami/mongodb/conf/mongodb.conf
# mongod.conf
# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# where and how to store data.
storage:
  dbPath: /bitnami/mongodb/data/db
  journal:
    enabled: true
  directoryPerDB: true

# where to write logging data.
systemLog:
  destination: file
  quiet: false
  logAppend: true
  logRotate: reopen
  path: /opt/bitnami/mongodb/logs/mongodb.log
  verbosity: 0

# network interfaces
net:
  port: 27017
  unixDomainSocket:
    enabled: true
    pathPrefix: /opt/bitnami/mongodb/tmp
  ipv6: false
  bindIpAll: true
  #bindIp:

# replica set options
replication:
  replSetName: rs-stage
  enableMajorityReadConcern: true

# sharding options
#sharding:
  #clusterRole:

# process management options
processManagement:
   fork: false
   pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid

# set parameter options
setParameter:
   enableLocalhostAuthBypass: false

# security options
security:
  authorization: enabled
  keyFile: /opt/bitnami/mongodb/conf/keyfile
```
