### ISSUE TITLE
[bitnami/magento] Is there a way to persist Magnto Data under Docker Desktop for Mac?

### ISSUE THREAD

**Issue by hussam-qasem** [bitnami/charts#6989]
**Which chart**: magento-18.1.6

**Describe the bug**
I'm unable to persist data using Docker Desktop for Mac:
- Using `hostPath` to use local volume does not work for Magento. (mariadb & elasticsearch seem fine) [though I can't find the directory on the local filesystem, need to use [nsenter1](https://github.com/justincormack/nsenter1/blob/master/README.md) which is not ideal.]
- Using `PersistentVolume` Magento attempts to read from an empty directory and keeps failing. (see 'additional context' below)

**To Reproduce**

1. Create `values.yaml`:
```YAML
image:
  debug: true
magentoHost: magento.localtest.me
magentoPassword: Bitnami1
magentoAdminUri: admin
persistence:
  hostPath:
    path: /tmp/magento/magento
elasticsearch:
  master:
    persistence:
      hostPath:
        path: /tmp/magento/es-master
  data:
    persistence:
      hostPath:
        path: /tmp/magento/es-data
mariadb:
  auth:
    rootPassword: Covid-19
    password: Hello2021
  primary:
    persistence:
      hostPath:
        path: /tmp/magento/mariadb
```
2. Install the chart, e.g. in the `demo` namespace:
```SHELL
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install demo bitnami/magento -n demo --create-namespace -f ./values.yaml
```
3. Magento pod fails with a `CreateContainerError`
4. Describing the pod, shows the following:
```
Events:
  Type     Reason  Age   From     Message
  ----     ------  ----  ----     -------
  Warning  Failed  1s    kubelet  Error: Error response from daemon: invalid mode: /bitnami/magento
```

```Shell
% kubectl -n demo get pvc
NAME                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS
data-demo-elasticsearch-data-0     Bound    pvc-2957ad94-5d84-4ab2-98df-f9581d038ba1   8Gi        RWO            hostpath    
data-demo-elasticsearch-master-0   Bound    pvc-6e88da8d-7996-405a-95bf-95bc285c82ad   8Gi        RWO            hostpath    
data-demo-mariadb-0                Bound    pvc-4275bd13-106d-4a15-a32a-eb362365351c   8Gi        RWO            hostpath    
demo-magento-magento               Bound    demo-magento-magento                       8Gi        RWO                        
```

```Shell
% kubectl -n demo get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                   STORAGECLASS
demo-magento-magento                       8Gi        RWO            Retain           Bound    demo/demo-magento-magento                           
pvc-2957ad94-5d84-4ab2-98df-f9581d038ba1   8Gi        RWO            Delete           Bound    demo/data-demo-elasticsearch-data-0     hostpath    
pvc-4275bd13-106d-4a15-a32a-eb362365351c   8Gi        RWO            Delete           Bound    demo/data-demo-mariadb-0                hostpath    
pvc-6e88da8d-7996-405a-95bf-95bc285c82ad   8Gi        RWO            Delete           Bound    demo/data-demo-elasticsearch-master-0   hostpath    
```

**Expected behavior**
Magento Pod would start normally.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

Alternatively, attempt to create a `pv.yaml`:
```YAML
apiVersion: v1
kind: PersistentVolume
metadata:
  name: magento
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: magento
  local:
    path: /Users/hqasem/Public/magento
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mariadb
  local:
    path: /Users/hqasem/Public/mariadb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-master
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: es-master
  local:
    path: /Users/hqasem/Public/es-master
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: es-data
  local:
    path: /Users/hqasem/Public/es-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
```

Apply the PV configurations:
```Shell
kubectl apply -f ./pv.yaml
```

Use a modifed `values.yaml` file:
```YAML
image:
  debug: true
magentoHost: magento.localtest.me
magentoPassword: Bitnami1
magentoAdminUri: admin
persistence:
  storageClass: magento
elasticsearch:
  master:
    persistence:
      storageClass: es-master
  data:
    persistence:
      storageClass: es-data
mariadb:
  auth:
    rootPassword: Covid-19
    password: Hello2021
  primary:
    persistence:
      storageClass: mariadb
```

Install the chart.
```Shell
helm install demo bitnami/magento -n demo --create-namespace -f ./values.yaml
```

 Magento fails with the following errors in the logs:
```
magento 12:42:45.63 DEBUG ==> Getting configuration path '/db/connection/default/dbname' from Magento configuration
PHP Warning:  require(/opt/bitnami/magento/app/etc/env.php): failed to open stream: No such file or directory in Command line code on line 1
PHP Fatal error:  require(): Failed opening required '/opt/bitnami/magento/app/etc/env.php' (include_path='.:/opt/bitnami/php/lib/php') in Command line code on line 1
```
