### ISSUE TITLE
[bitnami/postgresql] postgresqlExtendedConf broken in 10.6.1

### ISSUE THREAD

**Issue by jhemmje** [bitnami/charts#7009]
**Which chart**:
bitnami/postgresql 10.6.1

**Describe the bug**
When the parameter `postgresqlExtendedConf` is used, then the following error messages appear during `helm upgrade`:

```
coalesce.go:163: warning: skipped value for postgresqlExtendedConf: Not a table.
coalesce.go:203: warning: destination for postgresqlExtendedConf is a table. Ignoring non-table value 
coalesce.go:163: warning: skipped value for postgresqlExtendedConf: Not a table.
```

Apparently [this commit](https://github.com/bitnami/charts/commit/d0957937c764187307b924f600247c2b7afaf536#diff-e054e4f4a1e43e6b2e37969dbb4571b4fa679cd678c1379bbaa38590a9cb0d09) by @carrodher introduced this bug. The default value for `postgresqlExtendedConf` was changed from `nil` to `""`.

Configuration snippet from my `values.yaml` file:
```
postgresql:
  [...]
  postgresqlExtendedConf:
    logStatement: mod
    sharedBuffers: 1024MB
    workMem: 32MB
    maintenanceWorkMem: 512MB
    maxWalSize: 1024MB
    walBuffers: 32MB
    walCompression: on
    walLevel: minimal
    maxWalSenders: 0
```

**To Reproduce**

1. Use the PostgreSQL Helm Chart version 10.6.1 in combination with the parameter `postgresqlExtendedConf`
2. Run `helm upgrade`
3. See error

**Expected behavior**
No error messages during `helm upgrade` like in 10.6.0.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-13T02:40:46Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+IKS", GitCommit:"16842bd5faea59e82ec5736a5c5ecb728fd46e07", GitTreeState:"clean", BuildDate:"2021-06-18T11:15:12Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
