### ISSUE TITLE
[bitnami/postgresql-ha] postgresql pods are not coming up after enabling persistence

### ISSUE THREAD

**Issue by abhaygupta81** [bitnami/charts#7017]
Hi, 
I am currently using the postgresql-ha-7.5.3 chart and after enabling the persistence storage the pods are not coming up.

Before enabling the persistence storage, we are using the below parameters and all the pods are coming up withour any issues.
```yaml
persistence:
  enabled: false
replication:
  enabled: true
postgresql:
  password: admin
  maxConnections: 500
pgpool:
  childLifeTime: 0
  replicaCount: 2
  numInitChildren: 250
```

After enabling the persistence storage, we are using the below parameters.

```yaml
volumePermissionsImage:
  pullPolicy: IfNotPresent
volumePermissions:
  enabled: true
postgresqlImage:
  debug: true
persistence:
  storageClass: kadalu.replica2
  enabled: true
  size: 1Gi
replication:
  enabled: true
postgresql:
  password: admin
  maxConnections: 500
  livenessProbe:
    initialDelaySeconds: 200
  readinessProbe:
    initialDelaySeconds: 200
pgpool:
  childLifeTime: 0
  replicaCount: 2
  numInitChildren: 250
  livenessProbe:
    initialDelaySeconds: 200
  readinessProbe:
    initialDelaySeconds: 200
```

Please help to get it resolved.
