### ISSUE TITLE
[bitnami/node] Node chart fails when extraEnvVars is supplied 

### ISSUE THREAD

**Issue by petilodie** [bitnami/charts#7027]
Below is the helm release definition in skaffol.yml:

```yml
  helm:
    releases:
      - name: my-api
        artifactOverrides:
          image: lodiee/my-api
        imageStrategy:
          helm: {}
        remoteChart: bitnami/node
        setValues:
          image.repository: lodiee/my-api
          service.type: LoadBalancer
          getAppFromExternalRepository: false
          mongodb.enabled: false
          extraEnvVars:
            - name: MONGODB_HOST
              value: 'mongo-host'
            - name: MONGODB_DATABASE
              value: 'mongo-database'
            - name: MONGODB_USERNAME
              value: 'mongo-username'
            - name: MONGODB_PASSWORD
              value: 'mongo-password'
            - name: MONGODB_PORT
              value: 27017
```

When deployed I get the error below:

`Error: YAML parse error on node/templates/deployment.yaml: error converting YAML to JSON: yaml: line 55: could not find expected ':'`

When I remove the `extraEnvVars` definition from the yaml, everything works perfect.

**Comment by pablogalegoc** [comment]
Hi @petilodie,

I can confirm it works setting your variables in the `values.yaml` like:
```yaml
extraEnvVars:
  - name: MONGODB_HOST
    value: 'mongo-host'
  - name: MONGODB_DATABASE
    value: 'mongo-database'
  - name: MONGODB_USERNAME
    value: 'mongo-username'
  - name: MONGODB_PASSWORD
    value: 'mongo-password'
  - name: MONGODB_PORT
    value: 27017
```
I'm not familiar with skaffold, it may be making transformations under the hood that break the Helm templates syntax. I see it has a `dry-run` option just like Helm, it can be useful rendering the manifests and see if there's something strange there. Let me know if you need further help here!
