### ISSUE TITLE
[ external-dns ] secretAnnotation chart value does not actually apply annotations to the external-dns secret

### ISSUE THREAD

**Issue by fvosburgh** [bitnami/charts#7047]
**Which chart**:
external-dns version 0.7.3

**Describe the bug**
The `secretAnnotations` chart value does not actually propagate the annotations to the external-dns secret.

**To Reproduce**

1. Deploy the external-dns:0.7.3 helm chart with any annotations set for `secretAnnotations`:

```
secretAnnotations:
  vault.security.banzaicloud.io/vault-addr: "https://vault.vault.svc.cluster.local:8200"
  vault.security.banzaicloud.io/vault-role: "default"
  vault.security.banzaicloud.io/vault-skip-verify: "false"
  vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
```

2. In the namespace you've deployed external-dns:0.7.3 to, run `kubectl describe secret external-dns`
3. Verify that you do not see the above annotations added to the secret

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:41:51Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
In [secret.yaml](https://github.com/bitnami/charts/blob/master/bitnami/external-dns/templates/secret.yaml#L8) the `common.tplvalues.render` helper function is being used, but it seems to ignore a value that has no templated strings in it. I see in the [source](https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_tplvalues.tpl#L8) for that function that it will try to template out any string given to it. However, `secretAnnotations` expects an object for the annotations. I tried passing the annotations via these methods with no luck:
```
secretAnnotations: |
   vault.security.banzaicloud.io/vault-addr: "https://vault.vault.svc.cluster.local:8200"
   vault.security.banzaicloud.io/vault-role: "default"
   vault.security.banzaicloud.io/vault-skip-verify: "false"
   vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
```
```
secretAnnotations: 
  test: |
     vault.security.banzaicloud.io/vault-addr: "https://vault.vault.svc.cluster.local:8200"
     vault.security.banzaicloud.io/vault-role: "default"
     vault.security.banzaicloud.io/vault-skip-verify: "false"
     vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
```
