### ISSUE TITLE
repo url for dependencies

### ISSUE THREAD

**Issue by MartinGolding515** [bitnami/charts#7054]
Hi, 

I am trying to use mongodb as a dependency but the home url is for the github code not the location of index.yaml.

Where are the releases hosted?

**Comment by migruiz4** [comment]
Hi @MartinGolding515,

You can add the MongoDB chart as a subchart by adding the following to your Chart.yaml:

```
dependencies:
  - condition: mongodb.enabled
    name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: 10.x.x
```

As an example, you can check the `bitnami/node` or `bitnami/parse` charts that also use MongoDB as a dependency:
- https://github.com/bitnami/charts/blob/master/bitnami/node/Chart.yaml
- https://github.com/bitnami/charts/blob/master/bitnami/parse/Chart.yaml
