### ISSUE TITLE
[bitnami/mariadb-galera] Add support for extraDeploy

### ISSUE THREAD

**Issue by RumRogerz** [bitnami/charts#7057]
Similar to bitmani/mariadb's helm chart, is it possible to also include this? Our deployments require use of Kubernetes External Secrets and would like the chart to also include an External Secrets object for deployments. For example:

```
[...]
existingSecret: "mariadb-galera-secret"
[...]
 extraDeploy:
    - apiVersion: 'kubernetes-client.io/v1'
      kind: ExternalSecret
      metadata:
        name: mariadb-galera-secret
        namespace: mariadb-galera
      spec:
        backendType: vault
        vaultMountPoint: some-super-cool-mountpoint
        vaultRole: read-secrets 
        data:
          - name: mariadb-galera-mariabackup-password
            key: secrets/data/mariadb
            property: mariadb-galera-mariabackup-password
          - name: mariadb-password
            key: secrets/data/mariadb
            property: mariadb-password
          - name: mariadb-root-password
            key: secrets/data/mariadb
            property: mariadb-root-password
```
 
works great with your other charts!
