### ISSUE TITLE
[bitnami/elasticsearch] Bundled Kibana can only be access via root path ("/") when apply ingress

### ISSUE THREAD

**Issue by QuanTran91** [bitnami/charts#7076]
Hi all,
When I try to install ELK on my local Kubernetes (Microk8s), and apply the ingress as below:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch-first-helm-app
  labels:
    helm.sh/chart: first-helm-app-0.1.0
    app.kubernetes.io/name: first-helm-app
    app.kubernetes.io/instance: elasticsearch
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host:
      http:
        paths:
          - path: /elasticsearch
            pathType: ImplementationSpecific
            backend:
              service:
                name: elasticsearch-master
                port:
                  number: 9200
          - path: /kibana
            pathType: Prefix
            backend:
              service:
                name: elasticsearch-kibana
                port:
                  number: 5601
```
I cannot access kibana via URL .../kibana, it return /space/enter and show 404
![image](https://user-images.githubusercontent.com/10222639/127303766-2ace8647-bd27-4f1e-8a07-3d5afed9ead8.png)

However, when I change the path of kibana from "path: /kibana" to "path: /".
I can access to it. 
Could anybody who experience the problem help?
Thanks.
