### ISSUE TITLE
[bitnami/mongodb-sharded] Disable transparent huge pages

### ISSUE THREAD

**Issue by F43RY** [bitnami/charts#7084]
**Which chart**:
bitnami/mongodb-sharded

**Is your feature request related to a problem? Please describe.**
MongoDB requires to disable THP (transparent huge pages) as described in [MongoDB - THP](https://docs.mongodb.com/manual/tutorial/transparent-huge-pages/)

**Describe the solution you'd like**
I think that THP could be set as done in [redis chart](https://github.com/helm/charts/tree/master/stable/redis/#host-kernel-settings)

**Describe alternatives you've considered**
I tried to add the following line to the entrypoint.sh script:
`echo never | tee /sys/kernel/mm/transparent_hugepage/enabled`
but it returned 
`tee: /sys/kernel/mm/transparent_hugepage/enabled: Read-only file system`

**Additional context**
The bitnami/Redis chart issue [#148](https://github.com/bitnami/bitnami-docker-redis/issues/148)

Thx

**Comment by alvneiayu** [comment]
hi @F43RY

I am going to open an internal task to include sysctlImage or to include securityContext.sysctls and added to backlog. This support is not already included and we need to port them. We are open to receive PRs and we will be really happy to review it. I am not able to give you an ETA. We will update this thread once we have news.

Thanks a lot

Álvaro

**Comment by F43RY** [comment]
Hi,
news about THP?

Thx

**Comment by alvneiayu** [comment]
hi @F43RY 

Given the small size of our team and the nature of the request, the issue is still in backlog and I can not provide you an ETA. We are open to receive PRs and I will be really happy to review it. We will update this thread once we have news.

Thanks a lot

Álvaro

**Comment by carrodher** [comment]
Unfortunately, after evaluating this new feature we didn't find the bandwidth to implement it nor there are plans to work on it in the short/mid term. If you want to contribute by creating a PR the team will be happy to review it

**Comment by F43RY** [comment]
Hi,
I could disable thp using init Containers. 
the following lines are added to my-custom-vlues.yaml in each server type:

```
  initContainers:
    - name: disable-thp
      image: busybox
      volumeMounts:
        - name: host-sys
          mountPath: /host-sys
      command: ["sh", "-c", "echo never >/host-sys/kernel/mm/transparent_hugepage/enabled"]
  extraVolumes:
    - name: host-sys
      hostPath:
        path: /sys
  extraVolumeMounts:
    - name: host-sys
      mountPath: /host-sys
```
