### ISSUE TITLE
[bitnami/thanos] - nil pointer error when installing or upgrading chart with bucketweb.ingress.enabled

### ISSUE THREAD

**Issue by evhiness** [bitnami/charts#7106]
**Which chart**:
Thanos:5.2.5

**Describe the bug**
The following error occurs when upgrading or installing Thanos version 5.2.5 with a specific configuration. 
```
template: thanos/templates/bucketweb/tls-secrets.yaml:9:18: executing "thanos/templates/bucketweb/tls-secrets.yaml" at <.Values.commonLabels>: nil pointer evaluating interface {}.commonLabels
```

**To Reproduce**
Use the following values.yaml file
```
bucketweb:
  enabled: true
  ingress:
    enabled: true
    secrets: 
    - name: thanos-bucketweb-tls
      key: tls.key
      certificate: tls.crt
```

```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-release bitnami/thanos --values values.yaml 
```

**Expected behavior**
The chart installs properly

**Version of Helm and Kubernetes**:
```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"4a4913e790a033f1101af2f0fb7be189b106e3ae", GitTreeState:"clean", BuildDate:"2021-05-25T17:37:03Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
A workaround is to add Values.commonLabels fields to each secret entry. If you actually use the common labels field, you will need to duplicate it for each secret so its not ideal.
```
bucketweb:
  enabled: true
  ingress:
    enabled: true
    secrets: 
    - name: thanos-bucketweb-tls
      key: tls.key
      certificate: tls.crt
      Values:
        commonLabels: {}
```
