### ISSUE TITLE
[bitnami/redis] No master is elected

### ISSUE THREAD

**Issue by panteparak** [bitnami/charts#7110]
**Which chart**:
bitnami/redis (version 14.8.7) - Redis (6.2.5)

**Describe the bug**
When attempt to connect, but unable to find master. and raised with `redis.sentinel.MasterNotFoundError: No master found`

**To Reproduce**

Deploy with the following `values.yaml`
```
replica:
  replicaCount: 3
sentinel: 
  enabled: true
  masterSet: mymaster
rbac:
  create: true
tls:
  enabled: true
  authClients: false
  autoGenerated: true
```

**Expected behavior**
The below python code snippet should be able to connect to an elected master node

```
from redis.sentinel import Sentinel
password = 'MY_PASSWORD'
sentinel = Sentinel([('localhost', 26379)], password=password, socket_timeout=100, sentinel_kwargs={'password': password} )
master = sentinel.master_for('mymaster', password=password)
master.incr('counter', 1)
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by panteparak** [comment]
Not sure if this is directly related to this issue? #7109

**Comment by panteparak** [comment]
@carrodher I'll give it a try and update on the issue. However, I've set `tls.authClients` to `false`. Would I still be required to specify the TLS certificate to the Client connector?

**Comment by carrodher** [comment]
I think it is not needed for the client, but it is needed for the server, for example, the exporter is not using the env. variable related to TLS client auth when `tls.authClients` is `false`, see [master/statefulset.yaml](https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/master/statefulset.yaml#L265)
```yaml
            {{- if .Values.tls.enabled }}
            - name: REDIS_ADDR
              value: rediss://{{ .Values.metrics.redisTargetHost }}:{{ .Values.master.containerPort }}
              {{- if .Values.tls.authClients }}
            - name: REDIS_EXPORTER_TLS_CLIENT_KEY_FILE
              value: {{ template "redis.tlsCertKey" . }}
            - name: REDIS_EXPORTER_TLS_CLIENT_CERT_FILE
              value: {{ template "redis.tlsCert" . }}
              {{- end }}
            - name: REDIS_EXPORTER_TLS_CA_CERT_FILE
              value: {{ template "redis.tlsCACert" . }}
            {{- end }}
```
