### ISSUE TITLE
[bitnami/wordpress] wordpressExtraConfigContent has no effect on the running POD.

### ISSUE THREAD

**Issue by dmitry-mightydevops** [bitnami/charts#7120]
I have wordpress pod running for a month when recently we needed to add debugging and I had to adjust HELM values.

I added the following instruction into the helm values. 

```yaml
wordpressExtraConfigContent: |
        define('WP_DEBUG', true );
        define('WP_DEBUG_LOG', true);
```
I saw the created ENV variables inside the POD:
```sh
WORDPRESS_EXTRA_WP_CONFIG_CONTENT=define('WP_DEBUG', true );
define('WP_DEBUG_LOG', true);
```

but this had no affect on anything, there were no changes in /bitnami/wordpress/wp-config.php.

### Full argo-cd app yaml manifest:

```yaml
project: project
source:
  repoURL: 'https://charts.bitnami.com/bitnami'
  targetRevision: 11.0.14
  helm:
    values: |
      wordpressSkipInstall: false

      image:
        repository: bitnami/wordpress
        tag: 5.7.2
        debug: true

      commonLabels: 
        tech_stack: php
        application: wordpress

      wordpressEmail: devops+project@org.com
      wordpressBlogName: project
      wordpressScheme: https
      allowEmptyPassword: false
      existingSecret: project-wordpress-dev


      wordpressExtraConfigContent: |
        define('WP_DEBUG', true );
        define('WP_DEBUG_LOG', true);

      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 0%
          maxUnavailable: 100%

      replicaCount: 1
        
      smtpHost: mailhog.mailhog.svc.cluster.local
      smtpPort: 1025
      smtpUser: project
      smtpPassword: anypassword
      smtpProtocol: ssl
       
      nodeSelector:
        tech_stack: php
       
      podSecurityContext:
        enabled: true
        fsGroup: 1000

      containerSecurityContext:
        enabled: true
        runAsUser: 1000

      livenessProbe:
        httpGet:
          path: /wp-admin/install.php
          port: 8080

      readinessProbe:
        enabled: true
        httpGet:
          path: /wp-admin/install.php
          port: 8080

      service:
        type: ClusterIP
        port: 8080

      ingress:
        enabled: true
        certManager: true
        hostname: project.org.com
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/proxy-body-size: 100m
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: project-wordpress-dev-basic-auth
          nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
          nginx.ingress.kubernetes.io/server-snippet: |-
             add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";

        tls: true

      persistence:
        enabled: true
        storageClass: gp2

      metrics:
        enabled: true

      mariadb:
        enabled: false

      externalDatabase:
        host: mysql.host.us-west-2.rds.amazonaws.com
        user: project-wordpress-user-dev
        existingSecret: project-wordpress-dev-externaldb
        database: project-wordpress-dev
        port: 3306
  chart: wordpress
destination:
  server: 'https://kubernetes.default.svc'
  namespace: project
syncPolicy:
  automated: {}
  syncOptions:
    - CreateNamespace=true
ignoreDifferences:
  - group: v1
    kind: secret
    jsonPointers:
      - /metadata/labels

```

What am I missing?
