### ISSUE TITLE
WordPress helm chart doesn't pass custom container port variables into container

### ISSUE THREAD

**Issue by mamiu** [bitnami/charts#7130]
**Which chart**:
[WordPress](https://github.com/bitnami/charts/tree/master/bitnami/wordpress) (latest / master)

**Describe the bug**
If the WordPress deployment parameters `containerPorts.http` and `containerPorts.https` are set to something else than the [default values](https://github.com/bitnami/charts/blob/68ee22f5749af0ba282f456d4bbc73660abe7cbf/bitnami/wordpress/values.yaml#L371) (`8080` and `8443`) these values are not getting passed into the [WordPress container](https://github.com/bitnami/bitnami-docker-wordpress).

**To Reproduce**
Change at least one of the container ports and deploy it. E.g.

```yaml
containerPorts:
    http: 9080
    https: 9443
```

This results in WordPress not being accessible.

**Expected behavior**
The `containerPorts` port settings should be passed to the WordPress container via the `APACHE_HTTP_PORT_NUMBER` and `APACHE_HTTPS_PORT_NUMBER` env variables in the [deployment template file](https://github.com/bitnami/charts/blob/68ee22f5749af0ba282f456d4bbc73660abe7cbf/bitnami/wordpress/templates/deployment.yaml#L117) like so:

```yaml
    - name: APACHE_HTTP_PORT_NUMBER
      value: {{ include "containerPorts.http" . | quote }}
    - name: APACHE_HTTPS_PORT_NUMBER
      value: {{ include "containerPorts.https" . | quote }}
```

**Temporary Workaround**
Set the env variables in the container via `extraEnvVars`:

```yaml
extraEnvVars:
  - name: APACHE_HTTP_PORT_NUMBER
    value: "9080"
  - name: APACHE_HTTPS_PORT_NUMBER
    value: "9443"
```
