### ISSUE TITLE
Active log4j in scala application

### ISSUE THREAD

**Issue by warichet** [bitnami/charts#7156]
Hello,
i try to add scala application trace on console worker.

In my Scala application i had some trace using log4j:
```
import org.apache.log4j.{ Level, Logger }

object EdgeStreamApp {
  def main(args: Array[String]) {

    val log = Logger.getLogger(this.getClass)
    log.setLevel(Level.INFO)
    log.info("SEB Start Edge stream")
```

My submit is done from a job launch using a yalm file:
```
apiVersion: batch/v1
kind: Job                    
metadata:
  name: apao-spark-edge-job
spec:                       
  template:
    metadata:
      name: apao-spark-edge-job
    spec:
      containers:
      - name: apao-spark
        image: apao_spark
        imagePullPolicy: IfNotPresent
        args: [ "spark-submit", "--class", "EdgeStreamApp", "--master", "spark://apao-service-spark-master-svc:7077", "--deploy-mode", "cluster", "--conf", "spark.cores.max=1", "--conf", "spark.executor.cores=1", "--conf", "spark.executor.memory=1g", "--conf", "spark.standalone.submit.waitAppCompletion=true", "/tmp/app/edge-stream-project_2.12-1.0.jar" ]
      restartPolicy: Never
```
I didn't change the /opt/bitnami/spark/conf/llog4j.properties.template filr.

> My worker is up

> I can see my running driver in Spark WebUI.

> But i don't see my info trace in Worker log

> Is there something to configure to have have application trace ?

Best regards
Sébastien
