### ISSUE TITLE
[RabbitMQ/8.19.3] Unable to login using password from existingPasswordSecret 

### ISSUE THREAD

**Issue by swade1987** [bitnami/charts#7176]
**Which chart**:
RabbitMQ - version 8.19.3

**Describe the bug**
Since using chart version 8.19.3 (default image tag) we have been unable to login. 

We pass the following values to the helm chart 

```
auth:
      existingErlangSecret: enquiry-engine-rabbitmq-credentials
      existingPasswordSecret: enquiry-engine-rabbitmq-credentials
      username: enquiry-engine-user
```

I can only login to the UI using the username of `enquiry-engine-user` and the password of `CHANGEME` 

When using chart version 8.9.1 this was not the case and I could login using the password in the secret.

**Expected behavior**
I would like to be able to login using the username and password provided in the `existingPasswordSecret` like previously.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
We deploy using GitOps leveraging the latest Flux and Helm Operator versions so the versions of Helm and Kubectl listed above are a little obsolete.

**Comment by EmmEff** [comment]
Hi @Mauraza, I am not the OP, though I am seeing the same issue after a `helm upgrade`

```sh
[emmeff@wedge ~]$ kubectl describe statefulset myrabbitmq | grep RABBITMQ_PASSWORD
      RABBITMQ_PASSWORD:        <set to the key 'rabbitmq-password' in secret 'myrabbitmq'>  Optional: false
[emmeff@wedge ~]$ printf "%s\n" $(kubectl get secret myrabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 -d)
changeme
[emmeff@wedge ~]$ kubectl run rabbitmq-mgmt --quiet --image rabbitmq:management --rm -ti --restart=Never -- rabbitmqadmin --host myrabbitmq --username rabbit --password changeme list exchanges
*** Access refused: /api/exchanges?columns=name,type

pod default/rabbitmq-mgmt terminated (Error)
[emmeff@wedge ~]$ kubectl run rabbitmq-mgmt --quiet --image rabbitmq:management --rm -ti --restart=Never -- rabbitmqadmin --host myrabbitmq --username rabbit --password CHANGEME list exchanges
+--------------------+---------+
|        name        |  type   |
+--------------------+---------+
|                    | direct  |
| amq.direct         | direct  |
| amq.fanout         | fanout  |
| amq.headers        | headers |
| amq.match          | headers |
| amq.rabbitmq.trace | topic   |
| amq.topic          | topic   |
+--------------------+---------+

```

In my case, I upgraded from the 6.x chart to 7.x using `helm upgrade myrabbitmq bitnami/rabbitmq --version "^7" --set auth.password="${RABBITMQ_PASSWORD}",auth.erlangCookie="${RABBITMQ_ERLANG_COOKIE}",auth.username=rabbit` where `RABBITMQ_PASSWORD` is set to `changeme` and `RABBITMQ_ERLANG_COOKIE` is set to match the value in the secret `rabbitmq`.

Any thoughts?

**Comment by pablogalegoc** [comment]
Hi @swade1987 @EmmEff I've not been able to reproduce the issue
Created both secrets :
```
❯ kubectl describe secret existing-password-secret
Name:         existing-password-secret
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
rabbitmq-password:  22 bytes

❯ kubectl describe secret existing-erlang-secret
Name:         existing-erlang-secret
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
rabbitmq-erlang-cookie:  27 bytes
```
Set the values on the `values.yaml` file and installed:
```yaml
auth:
  username: test-user
  existingPasswordSecret: "existing-password-secret"
  existingErlangSecret: "existing-erlang-secret"
```
And both in the UI and with the cli command I can login with the new credentials:
```
❯ kubectl run rabbitmq-mgmt --quiet --image rabbitmq:management --rm -ti --restart=Never -- rabbitmqadmin --host rabbitmq --username test-user --password test-rabbitmq-password list exchanges
+--------------------+---------+
|        name        |  type   |
+--------------------+---------+
|                    | direct  |
| amq.direct         | direct  |
| amq.fanout         | fanout  |
| amq.headers        | headers |
| amq.match          | headers |
| amq.rabbitmq.trace | topic   |
| amq.topic          | topic   |
+--------------------+---------+

❯ kubectl run rabbitmq-mgmt --quiet --image rabbitmq:management --rm -ti --restart=Never -- rabbitmqadmin --host rabbitmq --username rabbit --password CHANGEME list exchanges
*** Access refused: /api/exchanges?columns=name,type
```

**Comment by EmmEff** [comment]
@pablogalegoc That is not exactly the workflow that I described. I let the initial install create the secrets and added the `--set auth.password=xxxx` and `--set auth.erlangCookie=xxx` parameters to `helm upgrade`. It consistently does not work. My services that auth'd successfully prior to the upgrade now give auth errors when the new pod is running.

**Comment by swade1987** [comment]
Sorry all, had some higher priorities at work the last few weeks, aiming to revisit this next week so will report back.

**Comment by Mauraza** [comment]
Hi @EmmEff, 

Did you check this [part of the README.md](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#to-700)?

Your error seems different from what appears in the title of this issue, from what you describe it is even another version. For clear reasons and in order to keep the information accessible to the rest of the community, could you open a [new issue](https://github.com/bitnami/charts/issues/new/choose)?

**Comment by swade1987** [comment]
@Mauraza am I still correct that the data in the secret is still the same (see below)

```
rabbitmq-username: 
rabbitmq-password: 
rabbitmq-erlang-cookie:
```

**Comment by Mauraza** [comment]
Hi @swade1987,

The username does not appear in the secret, is a simple value: auth.username https://github.com/bitnami/charts/blob/b16c0372ca3899918172c33a006c968ea380e300/bitnami/rabbitmq/values.yaml#L99-L103

About `rabbitmq-password,rabbitmq-erlang-cookie `this is correct 
https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/templates/secrets.yaml

**Comment by swade1987** [comment]
I am still unable to login (see below)

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    fluxcd.io/automated: "false"
  name: rabbitmq-pe-sbx
  namespace: pe-sbx
spec:
  # Ref: https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq
  chart:
    name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: 8.19.3
  releaseName: rabbitmq-pe-sbx
  helmVersion: v3
  values:
    image:
      registry: docker.io
      repository: bitnami/rabbitmq

    auth:
      existingErlangSecret: enquiry-engine-rabbitmq-credentials
      existingPasswordSecret: enquiry-engine-rabbitmq-credentials
      username: enquiry-engine-user

    clustering:
      enabled: false
    extraEnvVars:
      - name: RABBITMQ_SECURE_PASSWORD
        value: "no"

    podAnnotations:
      sidecar.istio.io/inject: "true"

    persistence:
      enabled: false

    nodeSelector:
      node.kubernetes.io/role: enquiry-engine
    tolerations:
      - key: node.kubernetes.io/role
        value: enquiry-engine
        operator: Equal
        effect: NoSchedule

    resources:
      limits: {}
      requests: {}

    ingress:
      enabled: true
      tls: true
      certManager: true
      hostname: rabbitmq.example.co.uk
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-http"
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io: ""
    metrics:
      enabled: true
```

```
➜ k view-secret enquiry-engine-rabbitmq-credentials rabbitmq-username
enquiry-engine-user

➜ k view-secret enquiry-engine-rabbitmq-credentials rabbitmq-password
enquiryRabbit10{}
```

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    helm.fluxcd.io/antecedent: pe-sbx:helmrelease/rabbitmq-pe-sbx
    meta.helm.sh/release-name: rabbitmq-pe-sbx
    meta.helm.sh/release-namespace: pe-sbx
  labels:
    app.kubernetes.io/instance: rabbitmq-pe-sbx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-8.19.3
  name: rabbitmq-pe-sbx
  namespace: pe-sbx
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: rabbitmq-pe-sbx
      app.kubernetes.io/name: rabbitmq
  serviceName: rabbitmq-pe-sbx-headless
  template:
    metadata:
      annotations:
        checksum/config: 878eab131ae179929e385adfe549df7df450c946dc5207e36bd764ce343be39b
        prometheus.io/port: "9419"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rabbitmq-pe-sbx
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: rabbitmq
        helm.sh/chart: rabbitmq-8.19.3
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: rabbitmq-pe-sbx
                  app.kubernetes.io/name: rabbitmq
              namespaces:
              - pe-sbx
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: K8S_SERVICE_NAME
          value: rabbitmq-pe-sbx-headless
        - name: K8S_ADDRESS_TYPE
          value: hostname
        - name: RABBITMQ_FORCE_BOOT
          value: "no"
        - name: RABBITMQ_NODE_NAME
          value: rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.cluster.local
        - name: K8S_HOSTNAME_SUFFIX
          value: .$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.cluster.local
        - name: RABBITMQ_MNESIA_DIR
          value: /bitnami/rabbitmq/mnesia/$(RABBITMQ_NODE_NAME)
        - name: RABBITMQ_LDAP_ENABLE
          value: "no"
        - name: RABBITMQ_LOGS
          value: '-'
        - name: RABBITMQ_ULIMIT_NOFILES
          value: "65536"
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        - name: RABBITMQ_ERL_COOKIE
          valueFrom:
            secretKeyRef:
              key: rabbitmq-erlang-cookie
              name: enquiry-engine-rabbitmq-credentials
        - name: RABBITMQ_LOAD_DEFINITIONS
          value: "no"
        - name: RABBITMQ_SECURE_PASSWORD
          value: "yes"
        - name: RABBITMQ_USERNAME
          value: enquiry-engine-user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rabbitmq-password
              name: enquiry-engine-rabbitmq-credentials
        - name: RABBITMQ_PLUGINS
          value: rabbitmq_management, rabbitmq_peer_discovery_k8s, rabbitmq_auth_backend_ldap,
            rabbitmq_prometheus
        - name: RABBITMQ_SECURE_PASSWORD
          value: "no"
        image: docker.io/bitnami/rabbitmq:3.8.20-debian-10-r0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -ec
              - |
                if [[ -f /opt/bitnami/scripts/rabbitmq/nodeshutdown.sh ]]; then
                    /opt/bitnami/scripts/rabbitmq/nodeshutdown.sh -t "120" -d  "false"
                else
                    rabbitmqctl stop_app
                fi
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -ec
            - rabbitmq-diagnostics -q ping
          failureThreshold: 6
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 20
        name: rabbitmq
        ports:
        - containerPort: 5672
          name: amqp
          protocol: TCP
        - containerPort: 25672
          name: dist
          protocol: TCP
        - containerPort: 15672
          name: stats
          protocol: TCP
        - containerPort: 4369
          name: epmd
          protocol: TCP
        - containerPort: 9419
          name: metrics
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -ec
            - rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 20
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bitnami/rabbitmq/conf
          name: configuration
        - mountPath: /bitnami/rabbitmq/mnesia
          name: data
      dnsPolicy: ClusterFirst
      nodeSelector:
        node.kubernetes.io/role: enquiry-engine
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      serviceAccount: rabbitmq-pe-sbx
      serviceAccountName: rabbitmq-pe-sbx
      terminationGracePeriodSeconds: 120
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/role
        operator: Equal
        value: enquiry-engine
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: rabbitmq.conf
            path: rabbitmq.conf
          name: rabbitmq-pe-sbx-config
        name: configuration
      - name: data
  updateStrategy:
    type: RollingUpdate


```
