### ISSUE TITLE
CSRF Session token is missing in Airflow web UI

### ISSUE THREAD

**Issue by JagadeepK01** [bitnami/charts#7178]
**Which chart**:
Airflow / Chart version: 10.2.8

**Describe the bug**
CSRF Session token is missing

![csrf](https://user-images.githubusercontent.com/85338024/128878162-f569afcd-f554-4a7c-b32c-63d209b1c14c.png)

Below is my webserver_config.py file 

```
# Webserver ConfigMap
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: webserver-configmap
  data:
   webserver_config.py: |-
     import os

     #from flask_appbuilder.security.manager import AUTH_DB
     basedir = os.path.abspath(os.path.dirname(__file__))

     # Flask-WTF flag for CSRF
     WTF_CSRF_ENABLED = True
     #AUTH_TYPE = AUTH_DB
     AUTH_ROLE_PUBLIC = 'Admin'
```
I have also set `WTF_CSRF_ENABLED = True` , not sure if this really helps. 

**To Reproduce**
Run the airflow Helm chart with web server replicas set to more than 2 or 3.

**Expected behavior**
Web server should be visible even web server replicas set to 2 or 3

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v3.6.2
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+k3s1", GitCommit:"5a67e8dc473f8945e8e181f6f0b0dbbc387f6fca", GitTreeState:"clean", BuildDate:"2021-06-21T20:52:44Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+k3s1", GitCommit:"5a67e8dc473f8945e8e181f6f0b0dbbc387f6fca", GitTreeState:"clean", BuildDate:"2021-06-21T20:52:44Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
