### ISSUE TITLE
Issue with ClusterRole -kubernetes-event-exporter 

### ISSUE THREAD

**Issue by eldhodevops** [bitnami/charts#7179]
**Which chart**:
kubernetes-event-exporter 1.1.11

**Describe the bug**
The cluster role "view" which is getting assigned to the service account dosen't have much privilege to get the logs : 
https://github.com/bitnami/charts/blob/master/bitnami/kubernetes-event-exporter/templates/rbac.yaml#L16

**To Reproduce**

1. Follow the mentioned steps to deploy. [ https://artifacthub.io/packages/helm/bitnami/kubernetes-event-exporter ]
2. Once deployed see logs on the event exporter  pod
3. See error
 
```
{"level":"error","error":"nodes \"<REDACTED>\" is forbidden: User \"system:serviceaccount:monitoring:event-exporter\" cannot get resource \"nodes\" in API group \"\" at the cluster scope","time":"2021-01-04T14:18:54Z","caller":"/app/pkg/kube/watcher.go:80","message":"Cannot list annotations of the object"} 
```
**Expected behavior**

Added the below clusterrole and bind it to the serviceaccount as a post install for fixing: (this need's in the default installation instead of "view" role as in current release)

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-event-exporter-rbac
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - nodes
  - pods
  - events
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - namespaces
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-event-exporter-sa-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-event-exporter-rbac
subjects:
  - kind: ServiceAccount
    name: kubernetes-event-exporter
    namespace: {{.Release.Namespace}}
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
❯ helm version
version.BuildInfo{Version:"v3.6.2"
```

- Output of `kubectl version`:

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.12", GitCommit:"2cb4598553d0a2ca5f3eb7980c99cd8236cc5011", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:44Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
No stdout {} is added in config by default: 
https://github.com/bitnami/charts/blob/master/bitnami/kubernetes-event-exporter/values.yaml#L88
