### ISSUE TITLE
master node doesn't exist and all slave node is disappeared after master node restarted

### ISSUE THREAD

**Issue by congcongke** [bitnami/charts#7181]
**Which chart**:
bitnami/redis (14.8.8)

**Describe the bug**
The redis is not available after master pod restarted. Master is the older one and all slaves disappeared when digging on the other nodes.

**To Reproduce**

1. my config file is local.yaml, described as below:
```
auth:
  enabled: true
  sentinel: false
  password: "test"

master:
  podAntiAffinityPreset: soft
  persistence:
    enabled: false
replica:
  replicaCount: 3
  podAntiAffinityPreset: hard
  persistence:
    enabled: false

sentinel:
  enabled: true
```

2. `helm install -n xxx -f local.yaml redis .`
3. after all the node ready, delete node-0
4. wait the node-0 is ready,  exec to the node-1
5. `redis-cli -p 26379 -a test sentinel masters`
6. `redis-cli -p 26379 -a test sentinel slaves mymaster`

**Expected behavior**
There are one master and two slaves, and the ip of them is right.

**Version of Helm and Kubernetes**:
helm v3
kubernetes 1.18

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
