### ISSUE TITLE
[bitnami/spark] spark-submit with "--master k8s" generate an error in master 

### ISSUE THREAD

**Issue by warichet** [bitnami/charts#7188]
Hello,,
to have access to driver trace i have used **k8s** in master adresse, that should create a pod for driver and executor. 
```
spark-submit --master k8s://http://apao-service-spark-master-svc:7077
                      --deploy-mode cluster
                      --name edge-pod 
                      --class EdgeStreamApp
                      --conf spark.executor.instances=1 
                      --conf spark.kubernetes.container.image.pullPolicy=Never
                      --conf spark.kubernetes.container.image=apao_spark
                      --conf spark.cores.max=1
                      --conf spark.executor.cores=1
                      --conf spark.executor.memory=1g
                      local:///tmp/app/edge-stream-project_2.12-1.0.jar" 
```
With this command i have an error in the master.
21/08/10 07:57:59 WARN TransportChannelHandler: Exception in connection from /172.17.0.1:36206
java.lang.IllegalArgumentException: Too large frame: 5786935666976711016
If i submit the same jar file with this command
`spark-submit --class EdgeStreamApp --master spark://apao-service-spark-master-svc:7077
                       .....
i have no pb, except i can't retrieve driver trace.

- Have you already seen this error in master ?
- Is it possible to have driver trace  using  **spark** in  master address ?

Best regards
Sébastien

_Originally posted by @warichet in https://github.com/bitnami/charts/issues/7156#issuecomment-895879577_

**Comment by pablogalegoc** [comment]
Hi @warichet,

Not an expert on Spark here but I think I've found a (somewhat) similar issue: https://issues.apache.org/jira/browse/SPARK-35237
Could you check that you are hitting the right port on `k8s://http://apao-service-spark-master-svc`?

**Comment by warichet** [comment]
Hi thanks for your reply,
I have also seen the similar issue, but prometheus isn't configured on my minikube infra.
The port should be OK, because it is working if i use --master spark://apao-service-spark-master-svc:7077 address instead of k8s://http://apao-service-spark-master-svc:7077. Also the error is on master side.

Best regards
Sebastien

**Comment by pablogalegoc** [comment]
Could you share the parameters you are setting in the `values.yaml`? I'll try to setup your environment to reproduce the issue

**Comment by warichet** [comment]
No pb, thanks for your time

That the part of value concerning spark
```
spark:
  image:
    registry:
    repository: apao_spark
    tag: latest
    pullPolicy: IfNotPresent

  service:
    webPort: 8080

  worker:
    # Set Kafka broker address  kafka-rbx8-rdeu-preprod-1.rainbow.rdeu:9092
    kafkaBrokerAddr: "192.168.49.1:9091"
    # Set the number of workers
    replicaCount: 1
    memoryLimit: 3G
    coreLimit: 2
    # Specifies the extra volumes to be added to the Apache Spark worker deployment
    extraVolumes:
      - name: apao-spark-config
        configMap:
          name: "{{ .Release.Name }}-apao-spark-env"
          items:
            - key: config.json
              path: config.json
      - name: edge-data
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-spark-edge-vc-data"
      - name: vertex-data
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-spark-vertex-vc-data"
    # Specifies the mount points for the volumes in each worker node
    extraVolumeMounts:
      - name: apao-spark-config
        mountPath: /tmp/app/config.json
        subPath: config.json
        readOnly: true
      - mountPath: /tmp/edge/data
        name: edge-data
      - mountPath: /tmp/vertex/data
        name: vertex-data
  
  vertexDataVolumeSize: "500M"
  edgeDataVolumeSize: "500M"
```
That my docker file
```
ARG OPENJDK_TAG=8u292
FROM openjdk:${OPENJDK_TAG} as apao_sbt

ARG SBT_VERSION=1.5.5

# Install sbt
RUN \
  mkdir /working/ && \
  cd /working/ && \
  curl -L -o sbt-$SBT_VERSION.deb https://repo.scala-sbt.org/scalasbt/debian/sbt-$SBT_VERSION.deb && \
  dpkg -i sbt-$SBT_VERSION.deb && \
  rm sbt-$SBT_VERSION.deb && \
  apt-get install sbt && \
  cd .. && \
  rm -r /working/

FROM apao_sbt as builder

RUN mkdir /tmp/app
COPY ./app/scala/edge_stream/build.sbt /tmp/app/scala/edge_stream/build.sbt
COPY ./app/scala/edge_stream/src /tmp/app/scala/edge_stream/src
COPY ./app/scala/vertex_stream/build.sbt /tmp/app/scala/vertex_stream/build.sbt
COPY ./app/scala/vertex_stream/src /tmp/app/scala/vertex_stream/src

RUN cd /tmp/app/scala/edge_stream && sbt compile && sbt package
RUN cd /tmp/app/scala/vertex_stream && sbt compile && sbt package
RUN cd /tmp/app/scala/edge_stream && sbt sbtVersion > /tmp/app/sbt.version


FROM docker.io/bitnami/spark:3-debian-10

USER root
RUN pip install numpy

# Change file permission for the folders where we want to write
# chmod Recursive for all/user/group +read write 
ENV BITNAMI_PKG_CHMOD="-R g+rw"

USER 1001

RUN mkdir /tmp/vertex
RUN mkdir /tmp/vertex/data
RUN mkdir /tmp/vertex/check

RUN mkdir /tmp/edge
RUN mkdir /tmp/edge/data
RUN mkdir /tmp/edge/check

RUN mkdir /tmp/logging
RUN mkdir /tmp/spark-events

RUN curl https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.0.1/spark-sql-kafka-0-10_2.12-3.0.1.jar --output /opt/bitnami/spark/jars/spark-sql-kafka-0-10_2.12-3.0.1.jar
RUN curl https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.6.2/commons-pool2-2.6.2.jar --output /opt/bitnami/spark/jars/commons-pool2-2.6.2.jar
RUN curl https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.4.1/kafka-clients-2.4.1.jar --output /opt/bitnami/spark/jars/kafka-clients-2.4.1.jar
RUN curl https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.0.1/spark-token-provider-kafka-0-10_2.12-3.0.1.jar --output /opt/bitnami/spark/jars/spark-token-provider-kafka-0-10_2.12-3.0.1.jar
RUN curl https://repo1.maven.org/maven2/org/apache/spark/spark-tags_2.12/3.0.1/spark-tags_2.12-3.0.1.jar --output /opt/bitnami/spark/jars/spark-tags_2.12-3.0.1.jar
RUN curl https://repos.spark-packages.org/graphframes/graphframes/0.8.1-spark3.0-s_2.12/graphframes-0.8.1-spark3.0-s_2.12.jar --output /opt/bitnami/spark/jars/graphframes-0.8.1-spark3.0-s_2.12.jar
RUN curl https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.10/scala-library-2.12.10.jar --output /opt/bitnami/spark/jars/scala-library-2.12.10.jar
RUN curl https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.16/slf4j-api-1.7.16.jar --output /opt/bitnami/spark/jars/slf4j-api-1.7.16.jar

COPY ./app/properties.edge /tmp/app/properties.edge
COPY ./app/properties.vertex /tmp/app/properties.vertex

RUN mkdir /tmp/app
COPY --from=builder /tmp/app/sbt.version /tmp/app/sbt.version
COPY --from=builder /tmp/app/scala/vertex_stream/target/scala-2.12/vertex-stream-project_2.12-1.0.jar /tmp/app/vertex-stream-project_2.12-1.0.jar
COPY --from=builder /tmp/app/scala/edge_stream/target/scala-2.12/edge-stream-project_2.12-1.0.jar /tmp/app/edge-stream-project_2.12-1.0.jar


```
