### ISSUE TITLE
[kong] db-less deploys DB stuffs

### ISSUE THREAD

**Issue by Xat59** [bitnami/charts#7189]
**Which chart**:
kong 3.8.1

**Describe the bug**
Even by configuring DB-less Kong regarding the [DB-less configuration](https://artifacthub.io/packages/helm/bitnami/kong#db-less), the chart keeps deploying all the DB stuffs : `postgresql` and `migrate` pods.

**To Reproduce**
I use [helmfile](https://github.com/roboll/helmfile) to deploy charts.

Here is the `helmfile.yaml` file : 

```yaml
---
repositories:
  - name: kong
    url: https://charts.bitnami.com/bitnami
releases:
  - name: kong-ingress
    namespace: kong-ingress
    chart: bitnami/kong
    version: 3.8.1
    values:
      - values.yaml
    wait: false
    waitForJobs: false
```

Here is the `values.yaml` file : 

```yaml
kong:
  extraEnvVars:
    - name: KONG_DATABASE
      value: "off"

database: "off"

ingressController:
  enabled: true
  ingressClass: "kong-ingress"

service:
  type: LoadBalancer

ingress:
  enabled: true
```

**Expected behavior**
As you can see in the `values.yaml`, I have used both `KONG_DATABASE: off` and `database: off` to enable DB-less.
Despite this, `postgresql` and `migrate` pods keep deployed in the cluster.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

I am able to not deploy the `postgresql` pod by adding this configuration in the `values.yaml` : 

```yaml
postgresql:
  enabled: false
```

This code snippet is not documented in the [DB-less configuration](https://artifacthub.io/packages/helm/bitnami/kong#db-less) .
Even with this addition, note that the `migrate` pod is deployed and its logs says : `Waiting for database connection to succeed`, while we don't have any database. So... it keeps running.

Thanks a lot for your help.
