### ISSUE TITLE
Error executing 'postInstallation': EPERM: operation not permitted, utime '/bitnami/kibana/.restored'

### ISSUE THREAD

**Issue by sumit84mca** [bitnami/charts#7197]
**Description**

I am very very new to devops. Also I am coming from window background and have almost no knowledge of linux. I have to create a aks cluster for my applications. ElasticSearch is also required there. So I added bitnami/elasticsearch helm chart as dependency char to one of my chart. Everything was working fine with default implementation. Then I added a custom azure storage class and assigned this class to elasticsearch.global.storageClass. After that kibana pods started crashing with issue **Error executing 'postInstallation': EPERM: operation not permitted, utime '/bitnami/kibana/.restored'**.

**Steps to reproduce the issue:**

1. Create below storageClass
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: default-azure-storageclass
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS  
```
2. Assign this to elasticsearch.global.storageClass property in values.yaml
```
elasticsearch:
  global:
    kibanaEnabled: true
    storageClass: default-azure-storageclass
  image:
    tag: "7.9.3"
  master:
    replicas: 1
    persistence:
      size: 5Gi
    nodeSelector: { "kubernetes.io/os": linux }
  kibana:
    replicaCount: 2    
    image:
      tag: "7.9.3"
    nodeSelector: { "kubernetes.io/os": linux }
    persistence:
      size: 10Gi
      accessMode: ReadWriteMany
    resources:
      limits:
        cpu: 2
        memory: 2048M
      requests:
        cpu: 1
        memory: 1024M
  coordinating:
    nodeSelector: { "kubernetes.io/os": linux }
    replicas: 1
    resources:
      limits:
        cpu: 2
        memory: 2048M
      requests:
        cpu: 1
        memory: 1024M
  data:
    replicas: 1
    nodeSelector: { "kubernetes.io/os": linux }
    persistence:
      size: 5Gi
    resources:
      limits:
        cpu: 2
        memory: 2048M
      requests:
        cpu: 1
        memory: 1024M
```
3. Now deploy helm release. The pods crashing
![image](https://user-images.githubusercontent.com/18229166/129083690-da2cc096-7c52-4b80-ae99-7043d2e375c6.png)

4. I tried to override below combination but issue was not resolved
 ```
securityContext:
      runAsNonRoot: false
```
```
securityContext:
      enabled: false  
```    

```
securityContext:
      runAsUser: "root"
```

```
volumePermissions:
      enabled: true
```
 

**Describe the results you received:**

Kibana pods are crashing with **Back-off restarting failed container**. When I run kubectl logs <pod> I get below message 

**_Error executing 'postInstallation': EPERM: operation not permitted, utime '/bitnami/kibana/.restored'_**

**Describe the results you expected:**

Pod should be running with persistent volume as defined by StorageClass

**Additional information you deem important (e.g. issue happens only occasionally):**
**Version**
AKS Kubernetes Version (output of kubectl version)
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"e1d093448d0ed9b9b1a48f49833ff1ee64c05ba5", GitTreeState:"clean", BuildDate:"2021-06-03T00:20:57Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```
elasticsearch Chart Info
```
- name: elasticsearch
  version: "15.10.3"
  repository: "https://charts.bitnami.com/bitnami"
```
ElasticSearch and Kibana docker image Details

```
elasticsearch:
  image:
    registry: docker.io
    repository: bitnami/elasticsearch
    tag: "7.9.3"
  kibana:
     image:
       registry: docker.io
       repository: bitnami/kibana
       tag: "7.9.3"   
  
```
Please help on this.
