### ISSUE TITLE
Harbor with GCE controller pointnig to ClusterIP port service

### ISSUE THREAD

**Issue by robert-ingeniousio** [bitnami/charts#7203]
There is problem with harbor chart installation on GKE. I set up controller type for "gce" and all other options for ingresses. Everything is installing properly but ingress for "core" want to connect to portal service which is in type of "ClusterIP" instead of "NodePort". Here is ingress error:

```
Warning  Translate  4s                loadbalancer-controller  Translation failed: invalid ingress spec: service "harbor/harbor-portal" is type "ClusterIP", expected "NodePort" or "LoadBalancer"
```
And here is portal svc template:

```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.portal" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http
      port: {{ include "harbor.portal.servicePort" . }}
      targetPort: http
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: portal
```

I think there should be added such "if" like in other services or ingress should be pointing to core service which is using NodePort with "gce" controller:

```
  {{- if  (eq .Values.ingress.controller "gce") }}
  type: NodePort
  {{- end }}
  ```
  
EDIT:

I checked ingress template and it looks like ingress is pointing to both services so for "gce" portal service should have this "if" added too like in core and notary service:

![image](https://user-images.githubusercontent.com/85160621/129183755-329cb5ea-8f41-4a31-aadf-861f83f6eb8f.png)
