### ISSUE TITLE
[bitnami/kibana] Kibana fails on Pivotal PKS

### ISSUE THREAD

**Issue by mooncser** [bitnami/charts#7228]
**Which chart**:
kibana:7.13.4

**Describe the bug**
Pod crashes when grafana is launched on a PKS cluster (with no ipv6 support) 
```
kibana 04:05:47.98
kibana 04:05:47.99 Welcome to the Bitnami kibana container
kibana 04:05:47.99 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kibana
kibana 04:05:47.99 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kibana/issues
kibana 04:05:48.00
kibana 04:05:48.00 INFO ==> ** Starting Kibana setup **
kibana 04:05:48.03 INFO ==> Configuring/Initializing Kibana...
kibana 04:05:48.10 INFO ==> Found mounted configuration directory
kibana 04:05:48.14 INFO ==> ** Kibana setup finished! **

kibana 04:05:48.15 INFO ==> ** Starting Kibana **
{"type":"log","@timestamp":"2021-08-16T04:06:01+00:00","tags":["info","plugins-service"],"pid":53,"message":"Plugin \"timelines\" is disabled."}
{"type":"log","@timestamp":"2021-08-16T04:06:01+00:00","tags":["warning","config","deprecation"],"pid":53,"message":"plugins.scanDirs is deprecated and is no longer used"}
{"type":"log","@timestamp":"2021-08-16T04:06:01+00:00","tags":["warning","config","deprecation"],"pid":53,"message":"Config key [monitoring.cluster_alerts.email_notifications.email_address] will be required for email notifications to work in 8.0.\""}
{"type":"log","@timestamp":"2021-08-16T04:06:01+00:00","tags":["fatal","root"],"pid":53,"message":"Error: listen EAFNOSUPPORT: address family not supported :::5601\n at Server.setupListenHandle [as _listen2] (net.js:1303:21)\n at listenInCluster (net.js:1368:12)\n at doListen (net.js:1505:7)\n at processTicksAndRejections (internal/process/task_queues.js:83:21) {\n code: 'EAFNOSUPPORT',\n errno: -97,\n syscall: 'listen',\n address: '::',\n port: 5601\n}"}

FATAL Error: listen EAFNOSUPPORT: address family not supported :::5601
```

**To Reproduce**

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6+vmware.1", GitCommit:"088f01db2ffab397a290be443902918b59ee032c", GitTreeState:"clean", BuildDate:"2021-04-17T01:01:00Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by rafariossaa** [comment]
Hi,
  Could you double check you are not using IPv6 ? The error ` listen EAFNOSUPPORT: address family not supported :::5601` indicates that it is getting an IPV6.

**Comment by mooncser** [comment]
Hi Rafael:
@rafariossaa I am sure that our PKS cluster doesn't support IPV6 and it is managed by other teams. The default server  host value is "::" in [configmap](https://github.com/bitnami/charts/blob/master/bitnami/kibana/templates/configmap.yaml) which supports both IPV4 and IPV6. User could not configure the value in the values.yaml. I have replaced the confimap with parameter configurationCM. Kibana configmap values is as following:
```
apiVersion: v1
data:
  kibana.yml: |
    pid.file: /opt/bitnami/kibana/tmp/kibana.pid
    server.host: "0.0.0.0"
    server.port: 5601
    elasticsearch.hosts: ["https://elasticsearch-dev-master:9200"]
    server.basePath: "/kibana"
    server.rewriteBasePath: false
    elasticsearch.ssl.verificationMode: certificate
    elasticsearch.ssl.certificateAuthorities: /opt/bitnami/kibana/config/certs/elastic-certificate.pem
    elasticsearch.username: dummy
    elasticsearch.password: dummy
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: kibana
    meta.helm.sh/release-namespace: elk-system
  labels:
    app.kubernetes.io/instance: kibana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kibana
    helm.sh/chart: kibana-8.1.14
  name: kibana-configuration
  namespace: elk-system
```
Finally, the kibana is up. It is more convenient to change server.host value in values.yaml. 
So please define variable to replace the fixe value.
