### ISSUE TITLE
redmine - An error occurred while sending mail (503 AUTH command used when not advertised )

### ISSUE THREAD

**Issue by r10r** [bitnami/charts#7241]
**Which chart**:
redmine-17.0.2

**Describe the bug**

The charts SMTP configuration is not working properly without authentication.
The Redmine mailer configuration is invalid if `smtpPassword` and/or `smtpUser` are unset.

The mailer will then reject the connection with code 503 and redmine displays the following error message when sending a test mail:

```
An error occurred while sending mail (503 AUTH command used when not advertised )
```

This happens because:

1. The SMTP authentication method ( `REDMINE_SMTP_AUTH` ) can not be set and disabled in the chart.
2. The `smtpUser` and `smtpPassword` are set to blank values even if they are unset.

**configuration**

Chart mailer configuration in `values.yaml`

```yaml
## SMTP mail delivery configuration
## ref: https://github.com/bitnami/bitnami-docker-redmine/#smtp-configuration
## @param smtpHost SMTP server host
## @param smtpPort SMTP server port
## @param smtpUser SMTP username
## @param smtpPassword SMTP user password
## @param smtpProtocol SMTP protocol
smtpHost: "mx.company.de"
smtpPort: "25"
```

Generated Redmine mailer configuration `/bitnami/redmine/config/configuration.yml`

```yaml
default:
  # Outgoing emails configuration
  # See the examples below and the Rails guide for more configuration options:
  # http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: mx.company.de
      port: "25"
      authentication: login
      user_name: ""
      password: ""
      domain: ""
      enable_starttls_auto: "false"
```

### `smtpDomain` setting

This is a following issue if the `smtpUser` is unset. 

```
An error occurred while sending mail (501 Syntactically invalid HELO argument(s) )
```

The action mailer `domain` setting is derived from the value of the `smtpUser`:

- https://github.com/bitnami/bitnami-docker-redmine/blob/4011362166f035e91f7a73c4bd5306930a8d7331/4/debian-10/rootfs/opt/bitnami/scripts/libredmine.sh#L171

It's therefore not possible to set the helo domain without setting the `smtpUser`. I suggest to add an additional configuration setting `smtpDomain` to set the helo name.

## References

* https://github.com/bitnami/bitnami-docker-redmine/#smtp-configuration
* https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
