### ISSUE TITLE
[bitnami/elasticsearch] - Issue with multiple volume claims on AzureFiles persistent volume

### ISSUE THREAD

**Issue by andysousa** [bitnami/charts#7249]
**Which chart**:
ElasticSearch

**Describe the bug**
I have provisioned an AzureFile Share in storage and have the PV defined as below. 
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: elasticsearchstorage
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl

```
Which results in 
![image](https://user-images.githubusercontent.com/42151009/129743619-b0423f09-8399-428e-bfc2-e3ea82a3c801.png)

Now I am trying to create the elastic instance with 2 replicas and use this volume for the claims to be created.  The documentation in the yaml is a little rough, but from my understanding of how this is supposed to work, I should be able to just set the "existingvolume" property for the match.  This is in the data block of the Values.yaml (nothing else modified)

```
persistence:
    ## @param data.persistence.enabled Enable persistence using a `PersistentVolumeClaim`
    ##
    enabled: true
    ## @param data.persistence.storageClass Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    #storageClass: ""
    ## @param data.persistence.existingClaim Existing Persistent Volume Claim
    ## If persistence is enable, and this value is defined,
    ## then accept the value as an existing Persistent Volume Claim to which
    ## the container should be bound
    ##
    #existingClaim: ""
    ## @param data.persistence.existingVolume Existing Persistent Volume for use as volume match label selector to the `volumeClaimTemplate`. Ignored when `data.persistence.selector` ist set.
    ##
    existingVolume: "azurefile"
    ## @param data.persistence.selector Configure custom selector for existing Persistent Volume. Overwrites `data.persistence.existingVolume`
    ## selector:
    ##   matchLabels:
    ##     volume:
    #selector: {}
    ## @param data.persistence.annotations Persistent Volume Claim annotations
    ##
    annotations: {}
    ## @param data.persistence.accessModes Persistent Volume Access Modes
    ##
    accessModes:
      - ReadWriteOnce
    ## @param data.persistence.size Persistent Volume Size
    ##
    size: 5Gi
```

after install, the claims get created, but are stuck in pending with an error.  
![image](https://user-images.githubusercontent.com/42151009/129744262-dae3fede-f756-4185-9808-6f5f0659f1d0.png)
```
message: >-
  Failed to provision volume with StorageClass "default": azureDisk -
  claim.Spec.Selector is not supported for dynamic provisioning on Azure disk
source:
  component: persistentvolume-controller
```

If I investigate the yaml that gets created for the Data node in the stateful set, I see the volumeclaimtemplate set what I believe to be accurately..but as you can see, status is stuck in pending

```
volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: data
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteMany
        selector:
          matchLabels:
            volume: azurefile
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
      status:
        phase: Pending
```

What am I missing or is this scenerio not supported by the charts?  

Ultimately what I am trying to create is a persistent storage in azure so if my cluster gets taken down or rebuilt, elastic will just come back online using the same data that was their prior to a new deployment.  Am I approaching this correctly?

TIA

**Comment by andysousa** [comment]
I also want to add that I went down the path of using static azure files as I believed that better suited my needs.. I did seem to have better luck with that, but then I hit the issue with having 2 data nodes trying to use the same claim.  I read that this is being deprecated in elasticsearch 8, so I didn't want to go down this path.

Using the bitnami one, I didn't see a way to correctly use existing claims for more than one pod

**Comment by juan131** [comment]
Hi @andysousa 

Please note that "master" and "data" nodes use different statefulsets and different persistence parameters. You need to modify the `master.persistence.existingClaim` to choose an existing PVC for master nodes, while modifying the `data.persistence.existingClaim` to choose an existing PVC for data nodes.

- https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/templates/master-statefulset.yaml#L263
- https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/templates/data-statefulset.yaml#L260

That said, as you mentioned you'll be using a single PVC for every master node and another one for every data node. **This is simply not compatible**, every node should have its own volume. That's why we use volumeClaimTemplates.

So.. To solve your problem you should use [dynamic volume provisioning](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/). To use it with AzureFile shares, you simply need to use the appropriate storage class, see:

- https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv

Then, install the chart setting the storage class:

```yaml
master:
  persistence:
    storageClass: my-azurefile
    size: 30Gi
data:
  persistence:
    storageClass: my-azurefile
    size: 30Gi
```
