### ISSUE TITLE
[mongodb]: SSLHandshakeFailed: SSL peer certificate validation failed: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by mnyk** [bitnami/charts#7268]
Hi, 
I try to install MongoDB  with helm on kubernetes with `helm install mongodb bitnami/mongodb --set tls.enabled=true`, next I create a MongoDB client container and try to connect with `mongo admin --host "test-mongo-mongodb" -ssl` but there is an error:
![image](https://user-images.githubusercontent.com/6115766/130038868-549e9c22-4189-4248-a2fb-7ac1c4f42fe6.png)

in .yaml file for tls `enabled: true` and for `caCert:` and `caKey:` fields I pasted my cert and key from Let's Encrypt 
-my question is: isn't possible to run Standalone Bitnami MongoDB Instance by helm with custom CA certificate?

Thanks for your help.

**Comment by rafariossaa** [comment]
Hi,
  To connect to mongodb using the autogenerated certificate `tls.enabled=true`, you can use:
```
$ kubectl exec -it mongodb-69b9f77879-kq6dt -- bash

I have no name!@mongodb-69b9f77879-kq6dt:/$ mongo --tls --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert 
MongoDB shell version v4.4.8
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
{"t":{"$date":"2021-08-20T09:47:12.249Z"},"s":"W",  "c":"NETWORK",  "id":23237,   "ctx":"js","msg":"You have an IP Address in the DNS Name field on your certificate. This formulation is deprecated."}
Implicit session: session { "id" : UUID("1fcd756c-7f9d-4715-91c0-a0532767e2f8") }
MongoDB server version: 4.4.8
> 

```

**Comment by mnyk** [comment]
Hi, thanks for your answer.
I think, I am using wrong key and cert pair, because the error is:

generate-tls-certs Generating RSA private key, 2048 bit long modulus (2 primes)                                                                                                                          │
│ generate-tls-certs .+++++                                                                                                                                                                                │
│ generate-tls-certs .................................................+++++                                                                                                                                │
│ generate-tls-certs e is 65537 (0x010001)                                                                                                                                                                 │
│ generate-tls-certs Signature ok                                                                                                                                                                          │
│ generate-tls-certs subject=C = US, O = My Organisations, OU = IT, CN = xxx                                                                                         │
│ generate-tls-certs Getting CA Private Key                                                                                                                                                                │
│ generate-tls-certs CA certificate and CA private key do not match                                                                                                                                        │
│ generate-tls-certs error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:../crypto/x509/x509_cmp.c:296:                                                    │
│ generate-tls-certs stream closed


Can you help me to find where can I find a correct pair in kubernetes? I looked into azure cert. manager but it's empty!

**Comment by carrodher** [comment]
You can use `tls.existingSecret` or `tls.caCert` + `tls.caKey` to provide your own CA certificates, if those parameters are not specified, an auto-generated CA certificate will be used, see
```yaml
tls:
  ## @param tls.enabled Enable MongoDB&reg; TLS support between nodes in the cluster as well as between mongo clients and nodes
  ##
  enabled: false
  ## @param tls.autoGenerated Generate a custom CA and self-signed certificates
  ##
  autoGenerated: true
  ## @param tls.existingSecret Existing secret with TLS certificates (keys: `mongodb-ca-cert`, `mongodb-ca-key`, `client-pem`)
  ## NOTE: When it's set it will disable certificate creation
  ##
  existingSecret: ""
  ## Add Custom CA certificate
  ## @param tls.caCert Custom CA certificated (base64 encoded)
  ## @param tls.caKey CA certificate private key (base64 encoded)
  ##
  caCert: ""
  caKey: ""
```

According to your initial post, you are not setting `tls.existingSecret` nor `tls.caCert`/`tls.caKey`; in that case the auto-generated certificates are stored in a secret:
```console
$ kubectl describe secret mongodb-ca
Name:         mongodb-ca
Namespace:    default
Labels:       app.kubernetes.io/component=mongodb
              app.kubernetes.io/instance=mongodb
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=mongodb
              helm.sh/chart=mongodb-10.23.13
Annotations:  meta.helm.sh/release-name: mongodb
              meta.helm.sh/release-namespace: default

Type:  Opaque

Data
====
mongodb-ca-cert:  1131 bytes
mongodb-ca-key:   1675 bytes
client-pem:       2838 bytes
```

Inside the MongoDB container, you can find the certificates in the `/certs` dir:
```console
$ ls -la /certs
total 24
drwxrwsrwx 3 root 1001 4096 Aug 30 06:16 .
drwxr-xr-x 1 root root 4096 Aug 30 06:16 ..
drwxr-sr-x 2 root 1001 4096 Aug 30 06:16 CAs
-rw------- 1 1001 1001 1131 Aug 30 06:16 mongodb-ca-cert
-rw------- 1 1001 1001 3058 Aug 30 06:16 mongodb.pem
-rw-r--r-- 1 1001 1001  443 Aug 30 06:16 openssl.cnf
```

And then, as @rafariossaa said in the previous comment you can run the `mongo` CLI using the CA certs:
```console
$ mongo --tls --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert
MongoDB shell version v4.4.8
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
{"t":{"$date":"2021-08-30T06:19:26.561Z"},"s":"W",  "c":"NETWORK",  "id":23237,   "ctx":"js","msg":"You have an IP Address in the DNS Name field on your certificate. This formulation is deprecated."}
Implicit session: session { "id" : UUID("984f6f70-5c8a-48c3-9bcd-dc03982c77a3") }
MongoDB server version: 4.4.8
>
```
Take into account the above command should be executed in the same container where the certs are mount, not in an external container to be used as a client.
You can find more info at https://docs.bitnami.com/kubernetes/infrastructure/mongodb/administration/enable-tls/
