### ISSUE TITLE
[bitnami/spring-cloud-dataflow] - Add local/dev stream app to cluster?

### ISSUE THREAD

**Issue by msummers** [bitnami/charts#7284]
I've used the spring-cloud-dataflow chart to install SCDF into a k8s cluster generated by kOps in AWS.

I'm trying to add my development SCDF stream apps into the installation using a file URI and cannot figure-out where or how the shared Skipper & Server mount point is. exec'ing into either instance there is no `/home/cnb` and I'm not seeing anything common via `mount`. The best I can tell the installation is using the MariaDB instance for shared "storage".

Is there a recommended way of installing local/dev Stream apps into the cluster?

**Comment by carrodher** [comment]
There are a couple of parameters under the `deployer` section that allows you to mount volumes:
```yaml
deployer:
   ## @param deployer.volumeMounts Streaming applications extra volume mounts
   ##
   volumeMounts: {}
   ## @param deployer.volumes Streaming applications extra volumes
   ##
   volumes: {}
```
see https://github.com/bitnami/charts/tree/master/bitnami/spring-cloud-dataflow#deployer-parameters.

Then, the mounted volume is used in the ConfigMaps (both server and skipper):
- Server
https://github.com/bitnami/charts/blob/c351211a5501bb44b5e065a5e3a7d4b7414f84f3/bitnami/spring-cloud-dataflow/templates/server/configmap.yaml#L60
- Skipper
https://github.com/bitnami/charts/blob/c351211a5501bb44b5e065a5e3a7d4b7414f84f3/bitnami/spring-cloud-dataflow/templates/skipper/configmap.yaml#L72

Apart from that, there are also `server.extraVolumes` and `server.extraVolumeMounts` to be set on the Dataflow Server Pod, and `skipper.extraVolumes` and `skipper.extraVolumeMounts` to be set on the Skipper Pod just in case it's useful for your use case.
