### ISSUE TITLE
redis-ha not create pod

### ISSUE THREAD

**Issue by henjue** [bitnami/charts#7289]
When cluster.externalaccess.enabled: true, no pod will be created and there are no errors

values.yaml
```yaml
usePassword: false
#service:
#  type: LoadBalancer
cluster:
  init: true
  nodes: 3
  externalAccess:
    enabled: true
  loadBalancerIP:
    - 192.168.80.6
    - 192.168.80.7
    - 192.168.80.8
  update:
    addNodes: true
    currentNumberOfNodes: 3
```
```bash
helm install redis -f values.yaml bitnami/redis-cluster
```
![image](https://user-images.githubusercontent.com/1314740/130319278-fb448e2c-7b1f-43af-8542-e6ac4ff5b8cd.png)

**Comment by migruiz4** [comment]
Hi @henjue,

I've notice there is an issue with your `values.yaml`. You are setting `cluster.loadBalancerIP`, when it should be `cluster.externalAccess.service.loadBalancerIP`.

Because of that, the function 'redis-cluster.createStatefulSet' fails and statefulset won't be created.

Could you please try modifying your values.yaml as it follows?

```yaml
usePassword: false
#service:
#  type: LoadBalancer
cluster:
  init: true
  nodes: 3
  externalAccess:
    enabled: true
    service:
      loadBalancerIP:
        - 192.168.80.6
        - 192.168.80.7
        - 192.168.80.8
  update:
    addNodes: true
    currentNumberOfNodes: 3
```
