### ISSUE TITLE
[bitnami/postgresql] Config parameter persistence.accessMode is ignored in Helm chart

### ISSUE THREAD

**Issue by devops-42** [bitnami/charts#733]
Hi,

I tried to install `bitnami/postgresql` on Azure using the helm charts:

```
helm install --name bitnami-postgres \
  --set persistence.storageClass=azurefile,persistence.accessMode=ReadWriteMany \
    bitnami/postgresql
```

The PVC will be created with the correct storage class, but with `accessMode` `ReadWriteOnce`. Therefore the pods crashed with a permission error issue:

`EACCES permission denied, mkdir "/bitnami/postgresql/data"`

Is this parameter ignored?

Thanks for your help in advance!

Cheers

**Comment by carrodher** [comment]
Hi,
Instead of `install`, can you generate the template to check if the parameters are properly rendered? You can do it by running
```
helm template --name bitnami-postgres \
  --set persistence.storageClass=azurefile,persistence.accessMode=ReadWriteMany \
    bitnami/postgresql > template.yaml
```
Above command will generate a `template.yaml` file in your current directory. Can you check/copy the lines related to `accessModes`?

**Comment by devops-42** [comment]
Hi @carrodher ,

I generated the template using the command provided, here the according snippet:

```
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
        storageClassName: "azurefile"
```

Cheers

**Comment by carrodher** [comment]
Hi,
Thanks for running the command, you are right, it seems that the `persistence.accessMode=ReadWriteMany` is not taken into account because the template after render contains
```
accessModes:
- "ReadWriteOnce"
```
As you can see in the template, `storageClassName` works fine but it is a string while `accessModes` is an array, can you try using the array method?
```
helm install --name bitnami-postgres \
--set persistence.storageClass=azurefile,persistence.accessMode={ReadWriteMany} \
bitnami/postgresql
```
please, note the `{}`.

If the above command doesn't work, can you try the template command but using the curly braces method?
```
helm template --name bitnami-postgres \
--set persistence.storageClass=azurefile,persistence.accessMode={ReadWriteMany} \
bitnami/postgresql > template.yaml
```

**Comment by carrodher** [comment]
🤦‍♂️  We're using `accessMode` instead of `accessModes`, can you try using?
```
helm install --name bitnami-postgres --set persistence.storageClass=azurefile --set persistence.accessModes={ReadWriteMany} bitnami/postgresql
```

Take into account the plural and use the curly braces, it should work fine.

**Comment by devops-42** [comment]
Confirmed, template is now rendered correctly:

`helm template --name bitnami-postgres --set persistence.storageClass=azurefile --set persistence.accessModes={ReadWriteMany} bitnami/postgresql`

results in:

```
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
      spec:
        accessModes:
          - "ReadWriteMany"
```

Hopefully it'll resolve the permission errors I got, will check it later that day.

Thanks for your help!
