### ISSUE TITLE
Error: YAML parse error on keycloak/templates/secrets.yaml: error converting YAML to JSON:

### ISSUE THREAD

**Issue by vardangh** [bitnami/charts#7334]
**Which chart**:
keycloak (version: 5.0.4)

**Describe the bug**
After [this PR](https://github.com/bitnami/charts/pull/7319) providing password for external DB fails with this error message
```
Error: YAML parse error on keycloak/templates/secrets.yaml: error converting YAML to JSON: yaml: line 14: did not find expected key
```

**To Reproduce**

1. create values-keycloak-test.yml file with this content
```
externalDatabase:
  host: external_db_IP
  port: 5432
  user: keycloak
  password: anything
  database: keycloak
```
2. helm template keycloak bitnami/keycloak -f values-keycloak-test.yml --debug
the output of above command will be
```
---
# Source: keycloak/templates/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: ns-ist-pro
  labels:
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-5.0.4
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: keycloak
type: Opaque
data:
  admin-password: "xxxx"
  management-password: "xxxxx"postgresql-password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```
4. as you can see there is no new line after `management-password:`

I think **the issue is with chomping modifiers** 
https://github.com/bitnami/charts/blob/master/bitnami/keycloak/templates/secrets.yaml

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```
