### ISSUE TITLE
[bitnami/ghost] ingress.tls doesn't work

### ISSUE THREAD

**Issue by qdupuy** [bitnami/charts#7345]
Hello,

When activating the "ingress.tls" option it does not add the tls part of the ingress of my service.

On my ghost instance, I have forced https in the configuration file.

For regular checks, I put additional parameters :

```
## @param customLivenessProbe Custom livenessProbe that overrides the default one
##
customLivenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6
  successThreshold: 1
  tcpSocket:
    port: 2368

## @param customReadinessProbe Custom readinessProbe that overrides the default one
#
customReadinessProbe:
  initialDelaySeconds: 120
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6
  successThreshold: 1
  tcpSocket:
    port: 2368
```

For the moment, I have to add the tls section by hand on my ingress... It's quite a pain.

**Comment by pablogalegoc** [comment]
Hi @qdupuy!

Could you share the `ingress` parameters that you are setting?

Here's the part where they are used:
https://github.com/bitnami/charts/blob/bc571361bffe4706f9c7182446ceca3d667658e4/bitnami/ghost/templates/ingress.yaml#L49-L51

You'll need those configure extra ones also

**Comment by qdupuy** [comment]
Hello,

I put the option on but it doesn't do anything behind it.

Here is my ingress section :

```
ingress:
  ## @param ingress.enabled Enable ingress record generation for Ghost
  ##
  enabled: true
  ## @param ingress.pathType Ingress path type
  ##
  pathType: ImplementationSpecific
  ## @param ingress.apiVersion Force Ingress API version (automatically detected if not set)
  ##
  apiVersion:
  ## @param ingress.hostname Default host for the ingress record
  ##
  hostname: x.domain.com
  ## @param ingress.path Default path for the ingress record
  ## NOTE: You may need to set this to '/*' in order to use this with ALB ingress controllers
  ##
  path: /
  ## @param ingress.annotations Additional custom annotations for the ingress record
  ## NOTE: If `ingress.certManager=true`, annotation `kubernetes.io/tls-acme: "true"` will automatically be added
  ##
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/permanent-redirect-code: '301'

  ## @param ingress.tls Enable TLS configuration for the host defined at `ingress.hostname` parameter
  ## TLS certificates will be retrieved from a TLS secret with name: `{{- printf "%s-tls" .Values.ingress.hostname }}`
  ## You can:
  ##   - Use the `ingress.secrets` parameter to create this TLS secret
  ##   - Relay on cert-manager to create it by setting `ingress.certManager=true`
  ##   - Relay on Helm to create self-signed certificates by setting `ingress.selfSigned=true`
  ##
  tls: true
  ## @param ingress.certManager Add the corresponding annotations for cert-manager integration
  ##
  certManager: false
  ## @param ingress.selfSigned Create a TLS secret for this ingress record using self-signed certificates generated by Helm
  ##
  selfSigned: false
  ## @param ingress.extraHosts An array with additional hostname(s) to be covered with the ingress record
  ## e.g:
  ## extraHosts:
  ##   - name: ghost.local
  ##     path: /
  ##
  extraHosts: []
  ## @param ingress.extraPaths An array with additional arbitrary paths that may need to be added to the ingress under the main host
  ## e.g:
  ## extraPaths:
  ## - path: /*
  ##   backend:
  ##     serviceName: ssl-redirect
  ##     servicePort: use-annotation
  ##
  extraPaths: []
  ## @param ingress.extraTls TLS configuration for additional hostname(s) to be covered with this ingress record
  ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
  ## e.g:
  ## extraTls:
  ## - hosts:
  ##     - ghost.local
  ##   secretName: ghost.local-tls
  ##
  extraTls: []
  ## @param ingress.secrets Custom TLS certificates as secrets
  ## NOTE: 'key' and 'certificate' are expected in PEM format
  ## NOTE: 'name' should line up with a 'secretName' set further up
  ## If it is not set and you're using cert-manager, this is unneeded, as it will create a secret for you with valid certificates
  ## If it is not set and you're NOT using cert-manager either, self-signed certificates will be created valid for 365 days
  ## It is also possible to create and manage the certificates outside of this helm chart
  ## Please see README.md for more information
  ## e.g:
  ## secrets:
  ##   - name: ghost.local-tls
  ##     key: |-
  ##       -----BEGIN RSA PRIVATE KEY-----
  ##       ...
  ##       -----END RSA PRIVATE KEY-----
  ##     certificate: |-
  ##       -----BEGIN CERTIFICATE-----
  ##       ...
  ##       -----END CERTIFICATE-----
  ##
  secrets: []
  ```

**Comment by pablogalegoc** [comment]
I think you'll need to set also either `ingress. certManager: true` or `ingress.selfSigned: true`

**Comment by qdupuy** [comment]
I have already installed a certmanager. This will be a duplicate

**Comment by pablogalegoc** [comment]
In that case setting `ingress.certManager: true` will create the annotation in the service that should trigger the creation of the secret with the TLS certificates:
https://github.com/bitnami/charts/blob/c1c9ef7dd1067bbc322938e0414f9b4c5d3532b1/bitnami/ghost/templates/ingress.yaml#L14-L16
Am I missing something?

**Comment by qdupuy** [comment]
Still not.

I have to edit the ingress to change the port.name to HTTPS instead of HTTP.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    meta.helm.sh/release-name: x
    meta.helm.sh/release-namespace: x
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/permanent-redirect-code: "301"
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
  creationTimestamp: "2021-09-10T10:05:23Z"
  generation: 1
  labels:
    app.kubernetes.io/component: ghost
    app.kubernetes.io/instance: x
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ghost
    helm.sh/chart: ghost-14.0.13
  name: x-ghost
  namespace: x

spec:
  rules:
  - host: blog.x.fr
    http:
      paths:
      - backend:
          service:
            name: x-ghost
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - blog.x.fr
    secretName: blog.x.fr-tls
 ```
 
 Once I replace http with https, it works.
 
 https://github.com/bitnami/charts/blob/master/bitnami/ghost/templates/ingress.yaml --> There is a missing condition to replace http with https :(

**Comment by marcosbc** [comment]
Hi @qdupuy, are you referring to update `http` here?

```
    http:
      paths:
      - backend:
          service:
            name: x-ghost
            port:
              name: http
```

i.e. to this:

```
    https:
      paths:
      - backend:
          service:
            name: x-ghost
            port:
              name: https
```

If so, that doesn't make sense to me. That would cause the Ingress to try and use the HTTPS backend for the app, not expose the HTTPS backend. Note that you already configuring TLS properly here:

```
  tls:
  - hosts:
    - blog.x.fr
    secretName: blog.x.fr-tls
```
