### ISSUE TITLE
airflow: request for help to clone git dags repository using github ssh deploy key 

### ISSUE THREAD

**Issue by kad-bijste** [bitnami/charts#7358]
**Which chart**:
https://artifacthub.io/packages/helm/bitnami/airflow

**Describe the bug**
Is it possible to clone a git repo with dags using ssh git credentials (release 10.3.1)?
(using extra env vars, volumes and volume mounts? README.md or default values.yaml does not provide examples how to setup these properties in line with git.dags.repositories[0].repository).

It would otherwise be great to just have the possibility to specify specific properties e.g.  git.dags.ssh.enabled, git.dags.ssh.secret and specify the the repository as git@github...  

**Version of Helm and Kubernetes**:
Helm version v3.6.3, K8S Engine 20.10.6

**Comment by kad-bijste** [comment]
I checked out https://github.com/bitnami/charts/issues/2395 and https://github.com/bitnami/charts/pull/2595
Maybe someone has managed to do the ssh sync after the changes were merged.

**Comment by migruiz4** [comment]
Hi @kad-bijste,

The logic used by `git.dags` is quite simple:

https://github.com/bitnami/charts/blob/64d5d747b84299ca9f63ea8a586b13870abe31a6/bitnami/airflow/templates/_git_helpers.tpl#L88-L108

It uses the image bitnami/git (https://github.com/bitnami/bitnami-docker-git) to run the above commands.

In the `git.dags.repositories[0].repository` field, you could use either HTTPS or SSH.

For HTTPS you could provide your credentials as it follows:
```
git clone https://username:password@github.com/username/repository.git
```

For SSH, you will need to mount your SSH keys at `/root/.ssh/id_rsa` and `/root/.ssh/id_rsa.pub`. 

This can be done using `git.clone.extraVolumeMounts` and `git.sync.extraVolumeMounts` to mount your keys, along with `worker.extraVolumes`, `web.extraVolumes` and `scheduler.extraVolumes`.

For example:
```yaml
git:
  clone:
    extraVolumeMounts:
        - name: git-ssh-key
          mountPath: /root/.ssh
  sync:
    extraVolumeMounts:
        - name: git-ssh-key
          mountPath: /root/.ssh
web:
  extraVolumes:
    - name: git-ssh-key
       secret:
         secretName: git-ssh-key-secret
         defaultMode: 256
worker:
  extraVolumes:
    - name: git-ssh-key
       secret:
         secretName: git-ssh-key-secret
         defaultMode: 256
scheduler:
  extraVolumes:
    - name: git-ssh-key
       secret:
         secretName: git-ssh-key-secret
         defaultMode: 256
```

The secret can be easily created using kubectl:
```
 kubectl create secret generic git-ssh-key-secret --from-file=id_rsa=/path/to/.ssh/id_rsa --from-file=known_hosts=/path/to/.ssh/known_hosts --from-file=id_rsa.pub=/path/to/.ssh/id_rsa.pub
```

**Comment by kad-bijste** [comment]
Hi Miguel,

Thank you for helping out.
I tried to run my install with provided specs, but it fails in interpreting the extra Volumes for the three components web, worker and scheduler:

```
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /home/bijste/.cache/helm/repository/airflow-10.3.1.tgz
Error: failed to parse test3.yaml: error converting YAML to JSON: yaml: line 20: mapping values are not allowed in this context
```

**Comment by kad-bijste** [comment]
After searching on extraVolumes I found issue https://github.com/bitnami/charts/issues/6190.
It seems I also need the following values in my values.yaml and a configmap containing file requirements.txt

```
extraVolumeMounts:
  - name: requirements
mountPath: /bitnami/python/
extraVolumes:
  - name: requirements
configMap:
  - name: airflow-requirements
```

**Comment by kad-bijste** [comment]
Can you please provide the contents for the requirements file? 
I only found one example in a github repo from a helm chart from the competitors ;-)

**Comment by kad-bijste** [comment]
Using [**requirements.txt** from the kubernetes-client/python](https://github.com/kubernetes-client/python/blob/master/requirements.txt) all init containers were spinning up.
Alas cloning timed out, with following error message in the **clone-repositories** container:

```
Cloning into '/git_dags'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

As always indentation is key and led to prior _converting YAML to JSON_ error above.
All pods are up and running now, but advice is still needed on correct settings in requirements.txt and ways to debug the possible cause for the github.com connection issue.
This is the latest version of my values.yaml:

```
git:
  dags:
    enabled: true
    repositories:
      - repository: 'git@github.com:<org>/<repo>.git'
        name: git
        branch: master
  clone:
    extraVolumeMounts:
      - name: git-ssh-key
        mountPath: /root/.ssh
  sync:
    extraVolumeMounts:
      - name: git-ssh-key
        mountPath: /root/.ssh
      - name: requirements
        mountPath: /bitnami/python/
web:
  extraVolumes:
    - name: requirements
      configMap:
        name: airflow-requirements
    - name: git-ssh-key
      secret:
        secretName: git-ssh-key-secret
        defaultMode: 256
worker:
  extraVolumes:
    - name: requirements
      configMap:
        name: airflow-requirements
    - name: git-ssh-key
      secret:
        secretName: git-ssh-key-secret
        defaultMode: 256
scheduler:
  extraVolumes:
    - name: requirements
      configMap:
        name: airflow-requirements
    - name: git-ssh-key
      secret:
        secretName: git-ssh-key-secret
        defaultMode: 256
```

**Comment by migruiz4** [comment]
Hi @kad-bijste,

I think you are mixing some concepts, your goal is to configure the Git init containers to be able to clone private repositories via SSH.

While the requirements extra volume is used to mount a `requirements.txt` including a list of Python packages that would be installed using pip when the Airflow container initializes, which is unrelated to your goal.

This values.yaml should be enough to configure SSH:
```
git:
  dags:
    enabled: true
    repositories:
      - repository: 'git@github.com:<org>/<repo>.git'
        name: git
        branch: master
  clone:
    extraVolumeMounts:
      - name: git-ssh-key
        mountPath: /root/.ssh
  sync:
    extraVolumeMounts:
      - name: git-ssh-key
        mountPath: /root/.ssh
web:
  extraVolumes:
    - name: git-ssh-key
      secret:
        secretName: git-ssh-key-secret
        defaultMode: 256
worker:
  extraVolumes:
    - name: git-ssh-key
      secret:
        secretName: git-ssh-key-secret
        defaultMode: 256
scheduler:
  extraVolumes:
    - name: git-ssh-key
      secret:
        secretName: git-ssh-key-secret
        defaultMode: 256
```

But keep in mind that you'd need to create the keys and configure your Github user accordingly first:
1. Create the SSH keys: https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
2. Add the SSH keys to your github account: https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

The volumes are used to mount the SSH files into the SSH agent included in the Git container that clones your dag repository.
If the keys are not found, or they are not associated with your Github account (which should have access to the private repository), the following error will be displayed:
```
Cloning into '/git_dags'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

**Comment by MuriloSchaefer** [comment]
> Hi @kad-bijste,
> 
> I think you are mixing some concepts, your goal is to configure the Git init containers to be able to clone private repositories via SSH.
> 
> While the requirements extra volume is used to mount a `requirements.txt` including a list of Python packages that would be installed using pip when the Airflow container initializes, which is unrelated to your goal.
> 
> This values.yaml should be enough to configure SSH:
> 
> ```
> git:
>   dags:
>     enabled: true
>     repositories:
>       - repository: 'git@github.com:<org>/<repo>.git'
>         name: git
>         branch: master
>   clone:
>     extraVolumeMounts:
>       - name: git-ssh-key
>         mountPath: /root/.ssh
>   sync:
>     extraVolumeMounts:
>       - name: git-ssh-key
>         mountPath: /root/.ssh
> web:
>   extraVolumes:
>     - name: git-ssh-key
>       secret:
>         secretName: git-ssh-key-secret
>         defaultMode: 256
> worker:
>   extraVolumes:
>     - name: git-ssh-key
>       secret:
>         secretName: git-ssh-key-secret
>         defaultMode: 256
> scheduler:
>   extraVolumes:
>     - name: git-ssh-key
>       secret:
>         secretName: git-ssh-key-secret
>         defaultMode: 256
> ```
> 
> But keep in mind that you'd need to create the keys and configure your Github user accordingly first:
> 
> 1. Create the SSH keys: https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
> 2. Add the SSH keys to your github account: https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account
> 
> The volumes are used to mount the SSH files into the SSH agent included in the Git container that clones your dag repository.
> If the keys are not found, or they are not associated with your Github account (which should have access to the private repository), the following error will be displayed:
> 
> ```
> Cloning into '/git_dags'...
> ssh: connect to host github.com port 22: Connection timed out
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
> and the repository exists.
> ```

Hi there,

I'm trying to run the code above, but the files aren't mounted with proper permissions (0400 or 256). I set my values as following:

```yaml
airflow:
  git:
    clone:
      extraEnvVars:
        - name: GIT_SSH_COMMAND
          value: "ssh -vvv"
      extraVolumeMounts:
        - name: git-ssh-key
          mountPath: /root/.ssh
    sync:
      extraVolumeMounts:
        - name: git-ssh-key
          mountPath: /root/.ssh
    dags:
      enabled: true
      repositories:
      - branch: master
        name: github-dags
        path: ./dags
        repository: git@github.com:querylayer/dags.git
  scheduler:
    extraVolumes:
      - name: git-ssh-key
        secret:
          secretName: git-ssh-key-secret
          defaultMode: 256
  web:
    extraVolumes:
      - name: git-ssh-key
        secret:
          secretName: git-ssh-key-secret
          defaultMode: 256
  worker:
    extraVolumes:
      - name: git-ssh-key
        secret:
          secretName: git-ssh-key-secret
          defaultMode: 256
```

The `GIT_SSH_COMMAND` env variable set debug mode on Git SSH, the output of that is the following:
```bash
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0440 for '/root/.ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/root/.ssh/id_rsa": bad permissions
debug1: Trying private key: /root/.ssh/id_dsa
debug3: no such identity: /root/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_ecdsa
debug3: no such identity: /root/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_ed25519
debug3: no such identity: /root/.ssh/id_ed25519: No such file or directory
debug1: Trying private key: /root/.ssh/id_xmss
debug3: no such identity: /root/.ssh/id_xmss: No such file or directory
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I then connected to pod and confirmed that permissions are indeed off:
```bash
root@xxxxxx:~/.ssh/..2021_09_20_19_26_19.065376079# ls -lah
total 12K
drwxr-sr-x 2 root 1001  100 Sep 20 19:26 .
drwxrwsrwt 3 root 1001  140 Sep 20 19:26 ..
-r--r----- 1 root 1001 2.6K Sep 20 19:26 id_rsa
-r--r----- 1 root 1001  571 Sep 20 19:26 id_rsa.pub
-r--r----- 1 root 1001  442 Sep 20 19:26 known_hosts
```

I could not remove the permission for group tho, do you guys have any idea?
