### ISSUE TITLE
[bitnami/postgresql-ha] Helm won't grant the access for custom users to postgresql backends.

### ISSUE THREAD

**Issue by alff** [bitnami/charts#7378]
**Which chart**:
postgresql-ha-7.8.8

**Describe the bug**
When I want to specify additional users to postgresql - they won't authenticate through the pgpool.

My helm_values.yaml:
```
postgresql:
  database: "foobar_db"
  ## Affinity for PostgreSQL pods assignment
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/component"
                operator: In
                values:
                  - postgresql
          topologyKey: "kubernetes.io/hostname"
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: akk-persistence
#Create custom user for airflow
pgpool:
  customUsersSecret: test-postgresql-ha-pgpool-custom-users
```

**To Reproduce**

1. Create helm chart values from example above.
2. Create a kubernetes secret `test-postgresql-ha-pgpool-custom-users` with format `data.usernames` and `data.passwords` where specify credentials for user `foo`.
3. Install it `helm install myrdb -n akk-persistence -f postgresql_helm_values.yaml bitnami/postgresql-ha`
4. Go to pod `myrdb-postgresql-ha-pgpool-XXXXX-XXXX` and check `/opt/bitnami/pgpool/conf/pool_passwd`
5. `postgres` and `foo` users are there.
```
at /opt/bitnami/pgpool/conf/pool_passwd 
postgres:md5XXXXXXXXXXXXXX
foo:mdXXXXXXXXXXXXXX
```
6. Try to connect to database `foobar_db` as `foo` user over pgpool svc.

**Expected behavior**
Connection success!

**Actual behavior**
```
Password for user foo: 
psql: ERROR:  authentication failed
DETAIL:  password authentication failed for user "foo"
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:56:19Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}```
```

**Additional context**
When I connect to postgres as default `postgres` user and run `list users` I see default users only: `postgres` and `repmgr`. As far as I understood pgpool user credentials must be the same on pgpool and on the backends. But I don't see it there.

```
foobar_db=# \du
                                   List of roles
 Role name |                         Attributes                         | Member of 
-----------+------------------------------------------------------------+-----------
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 repmgr    | Superuser, Replication                                     | {}

```

Thanks.

**Comment by javsalgar** [comment]
Hi,

Thank you for using bitnami, could you provide an example secret file with some testing password that triggered the issue on your side?

**Comment by alff** [comment]
sure!
```
---
apiVersion: v1
kind: Secret
metadata:
  name: test-postgresql-ha-pgpool-custom-users
  namespace: akk-persistence
type: Opaque
data:
  usernames: Zm9v
  passwords: Zm9vdXNlcg==
```
