### ISSUE TITLE
[bitnami/postgresql] feature: override configmaps

### ISSUE THREAD

**Issue by soujiro32167** [bitnami/charts#738]
# Use case

There is a chart that requires bitnami/postgres as a dependency. I would like to pass in initialization scripts and override `postgresql.conf`. The directory structure is:
```
mychart
|- charts
|-- postgresql-2.1.0.tgz 
```

# Problem

The only way I found to do this was clone the chart into the `charts` folder and insert the files directly:

```
mychart
|- charts
|-- postgresql
|--- files
|---- postgresql.conf
|---- docker-entrypoint-initdb.d
|----- setup.sql
```

This, however, breaks the helm workflow for chart management

# Solution

A potential solution is to override the init configmaps with my own, which would include files/templates taken from the top level. Thoughts?

**Comment by tompizmor** [comment]
Hi @soujiro32167,

Agree! Your solution seems valid to me. We could add a parameter in the values.yaml so that if you provide a configmap name the chart will use that instead of creating a new one.

We will work on adding this feature to the chart but I cannot provide an ETA about when this will be done.

**Comment by soujiro32167** [comment]
Czech out the PR #739. Its working for us with the top chart as follows:

values.yaml
```yaml
postgresql:
  config:
    customInitConfig: true
```

templates/postgres-init-config.yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgresql-init-scripts # the name must match the original configmap
  labels:
    app: "postgresql" # I can't get the child chart properties, which makes me a sad panda
    chart: "postgresql-2.1.1"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  registry-init.sql: |-
    CREATE DATABASE registry;
# Or other things like globbing
```
