### ISSUE TITLE
[bitnami/keycloak] Not possible to set container's ports to 80/443

### ISSUE THREAD

**Issue by Igor-lkm** [bitnami/charts#7385]
**Which chart**:
bitnami/keycloak 15.0.2

**Describe the bug**

It is not possible to set `containerPorts.http` to `80` and `containerPorts.https` to `443`

The actual problems is:

I have **keycloak** behind **proxy** (kong). I can open home/welcome page at `https://auth.mydomain.com`, but when I click Administration Console I am redirected to `https://auth.mydomain.com:8443/admin/master/console/`. Port is `8443` and this port is not exposed as we expect to continue on port `443`

Related issue on [stackoverflow](https://stackoverflow.com/questions/55164687/keycloak-behind-kong-and-strange-redirect/58306107#58306107)

It is/was fixable by setting:

```
   - name: KEYCLOAK_HTTP_PORT
      value: "80"
    - name: KEYCLOAK_HTTPS_PORT
      value: "443"
    - name: KEYCLOAK_HOSTNAME
      value: auth.mydomain.com
```

However it is not possible to set them, the error: 
```
keycloak 12:25:24.05 ERROR ==> An invalid port was specified in the environment variable KEYCLOAK_HTTP_PORT: privileged port requested.
keycloak 12:25:24.05 ERROR ==> An invalid port was specified in the environment variable KEYCLOAK_HTTPS_PORT: privileged port requested.
```

my `values.yaml`:

```
replicaCount: 1
containerPorts:
   http: 80
   https: 443
auth:
  tls:
    enabled: true
    autoGenerated: true
service:
  type: ClusterIP
metrics:
  enabled: true
resources:
  limits:
    cpu: 1250m
    memory: 1024Mi
  requests:
    cpu: 150m
    memory: 768Mi
postgresql:
  enabled: false
externalDatabase:
  host: *
  port: *
  database: *
  user: *
  password: *
proxyAddressForwarding: true
```

**To Reproduce**

`values.yaml`:

```
containerPorts:
  http: 80
  https: 443
```

**Expected behavior**
Expecting to set port to `80` and `443` to make redirects work correctly. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.9-gke.2100", GitCommit:"b89829cd5757f7a861cde5b5a9a01387c78e8111", GitTreeState:"clean", BuildDate:"2021-08-11T09:19:21Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
```
