### ISSUE TITLE
[bitnami/jupyterhub] hub.configuration question

### ISSUE THREAD

**Issue by hydridity** [bitnami/charts#7404]
Chart:
> jupyterhub-0.1.18

Helm version:
> V3.6.1

I was looking into configuring different authenticators in jupyter hub, and following documentation at [https://docs.bitnami.com/kubernetes/infrastructure/jupyterhub/configuration/configure-authentication/](https://docs.bitnami.com/kubernetes/infrastructure/jupyterhub/configuration/configure-authentication/)
I've tried to put the example in the own Values.yaml file and deploy helm with those values, but I'm not sure if it's supposed to overwrite whole Chart.hub.configuration value, or just replace that specific part of hub.config.JupyterHub inside Chart.hub.configuration value.

Is it possible to somehow define own partial template of hub.config.JupyterHub and apply it without overwriting whole Chart.hub.configuration value, or do I have to copy entire Chart.hub.configuration from template and put it inside own Values.yaml file and replace the parts i need ?

With this Values.yaml configuration
```yaml
hub:
  configuration: |
    ...
    hub:
      config:
        JupyterHub:
          admin_access: true
          authenticator_class: nativeauthenticator.NativeAuthenticator
          Authenticator:
            admin_users:
              - test
    ...
```

The resulting secret does not contain any of the another definitions that are in template of that secret after rendering template or deploying the chart
```yaml
# Source: jupyterhub/templates/hub/secret.yaml
apiVersion: v1
kind: Secret
metadata: [REMOVED]
type: Opaque
data:
  values.yaml: "Li4uCmh1YjoKICBjb25maWc6CiAgICBKdXB5dGVySHViOgogICAgICBhZG1pbl9hY2Nlc3M6IHRydWUKICAgICAgYXV0aGVudGljYXRvcl9jbGFzczogbmF0aXZlYXV0aGVudGljYXRvci5OYXRpdmVBdXRoZW50aWNhdG9yCiAgICAgIEF1dGhlbnRpY2F0b3I6CiAgICAgICAgYWRtaW5fdXNlcnM6CiAgICAgICAgICAtIHRlc3QKLi4uCg=="
  proxy-token: "[REDACTED]"
```

Which after decoding data.values.yaml gives only data of overwritten value
```yaml
...
hub:
  config:
    JupyterHub:
      admin_access: true
      authenticator_class: nativeauthenticator.NativeAuthenticator
      Authenticator:
        admin_users:
          - test
...
```

**Comment by carrodher** [comment]
What you set on the `hub.configuration` parameter is going to be added to the secret, and the information set in that secret is going to be used by the _jupyterhub_config.py_ script.

In my case I did the same test by replacing the auth method, for that I modified the _values.yaml_ in the following way:
```diff
        JupyterHub:
          admin_access: true
-         authenticator_class: dummy
-         cookie_secret_file: /tmp/jupyterhub_cookie_secret
-         DummyAuthenticator:
-         {{- if .Values.hub.password }}
-           password: {{ .Values.hub.password | quote }}
-         {{- else }}
-           password: {{ randAlphaNum 10 | quote }}
-         {{- end }}
+         authenticator_class: nativeauthenticator.NativeAuthenticator
          Authenticator:
            admin_users:
-             - {{ .Values.hub.adminUser }}
+             - test
      cookieSecret:
      concurrentSpawnLimit: 64
      consecutiveFailureLimit: 5
```
Then I deployed the chart just by running `helm install jupyter . -f values.yaml` and I taking a look at the secret, everything that is set under the `hub.configuration` parameter appears:
```
$ kubectl get secret jupyter-jupyterhub-hub -o jsonpath="{.data['values\.yaml']}" | base64 --decode
```
```yaml
Chart:
  Name: jupyterhub
  Version: 0.1.18
Release:
  Name: jupyter
  Namespace: default
  Service: Helm
hub:
  config:
    JupyterHub:
      admin_access: true
      authenticator_class: nativeauthenticator.NativeAuthenticator
      Authenticator:
        admin_users:
          - test
  cookieSecret:
  concurrentSpawnLimit: 64
  consecutiveFailureLimit: 5
  activeServerLimit:
  db:
    type: postgres
    url: postgresql://bn_jupyterhub@jupyter-postgresql:5432/bitnami_jupyterhub
  services: {}
  allowNamedServers: false
  namedServerLimitPerUser:
  authenticatePrometheus:
  redirectToServer:
  shutdownOnLogout:
singleuser:
  podNameTemplate: jupyter-jupyterhub-jupyter-{username}
  networkTools:
    image:
      name: docker.io/bitnami/bitnami-shell
      tag: 10-debian-10-r173
      pullPolicy: Always
      pullSecrets:

  cloudMetadata:
    blockWithIptables: false
  events: true
  extraAnnotations:
  extraLabels:
    hub.jupyter.org/network-access-hub: "true"
    app.kubernetes.io/component: singleuser
    app.kubernetes.io/name: jupyterhub
    helm.sh/chart: jupyterhub-0.1.18
    app.kubernetes.io/instance: jupyter
    app.kubernetes.io/managed-by: Helm
  uid: 1001
  fsGid: 1001
  serviceAccountName: jupyter-jupyterhub-singleuser
  storage:
    type: dynamic
    extraLabels:
      app.kubernetes.io/component: singleuser
      app.kubernetes.io/name: jupyterhub
      helm.sh/chart: jupyterhub-0.1.18
      app.kubernetes.io/instance: jupyter
      app.kubernetes.io/managed-by: Helm
    capacity: 10Gi
    homeMountPath: /opt/bitnami/jupyterhub-singleuser
    dynamic:

      pvcNameTemplate: jupyter-jupyterhub-claim-{username}{servername}
      volumeNameTemplate: jupyter-jupyterhub-volume-{username}{servername}
      storageAccessModes:
        - ReadWriteOnce
  image:
    name: docker.io/bitnami/jupyter-base-notebook
    tag: 1.4.2-debian-10-r5
    pullPolicy: IfNotPresent
    pullSecrets:

  startTimeout: 300
  cpu:
    limit:
    guarantee:
  memory:
    limit:
    guarantee:
  cmd: jupyterhub-singleuser
  defaultUrl:
cull:
  enabled: true
  users: false
  removeNamedServers: false
  timeout: 3600
  every: 600
  concurrency: 10
  maxAge: 0
```

This secret includes the section I modified (`JupyterHub`) but also the default configuration that is present in the _values.yaml_ and I didn't change
