### ISSUE TITLE
Compatibility of kafka exporter and jmx exporter

### ISSUE THREAD

**Issue by srinivas-kandula** [bitnami/charts#7407]
Kindly let me know if we can use bitnami kafka exporter and jmx exporter to expose kafka metrics deployed by strimzi operator (https://strimzi.io/)?

**Comment by juan131** [comment]
Hi @srinivas-kandula 

I followed the steps described at https://strimzi.io/quickstarts to install the operator and provision an Apache Kafka cluster. After a while, these are the pods deployed by this solution:

```console
$ kubectl get pods -n kafka
NAME                                         READY   STATUS    RESTARTS   AGE
my-cluster-entity-operator-cb7668768-68q6k   3/3     Running   0          64s
my-cluster-kafka-0                           1/1     Running   0          109s
my-cluster-zookeeper-0                       1/1     Running   0          2m48s
strimzi-cluster-operator-687fdd6f77-ld86m    1/1     Running   0          3m16s
```

We can use the simple deployment and service like the ones below to run a Kafka exporter in the "default" namespace and expose the Kafka metrics retrieving them from the Strimzi solution:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: default
  labels:
    app.kubernetes.io/name: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-exporter
    spec:
      containers:
        - name: kafka-exporter
          image: docker.io/bitnami/kafka-exporter:1.3.1-debian-10-r88
          imagePullPolicy: "IfNotPresent"
          command:
            - /bin/bash
            - -ec
            - |
              kafka_exporter \
              --kafka.server=my-cluster-kafka-brokers.kafka.svc.cluster.local:9092 \
              --web.listen-address=:9308
          ports:
            - name: metrics
              containerPort: 9308
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  labels:
    app.kubernetes.io/name: kafka-exporter
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '9308'
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9308
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: kafka-exporter
```

Once deployed, you can obtain the metrics running:

```console
$ kubectl port-forward svc/kafka-exporter 9308:9308 &
$ curl 127.0.0.1:9308/metrics
```

---

Regarding the JMX exporter is more difficult since this container must be executed as a sidecar in the same pod used to run Kafka. Unless this Strimzi operator allows adding custom sidecars (I'm not aware of that), it won't be possible to use it.
