### ISSUE TITLE
Cassandra refuses connection from cassandra-client (and any other than own pods) after clear installation

### ISSUE THREAD

**Issue by airen29** [bitnami/charts#7411]
**Which chart**:
cassandra-8.0.3

**Describe the bug**

**To Reproduce**

1. Install `cassandra` with: `helm install cassandra bitnami/cassandra -n cassandra -f c-values.yaml`
2. Run a Cassandra pod that you can use as a client: 
```
kubectl run --namespace cassandra cassandra-client --rm --tty -i --restart='Never' \  
   --env CASSANDRA_PASSWORD=$CASSANDRA_PASSWORD \  
    \  
   --image docker.io/bitnami/cassandra:4.0.0-debian-10-r28 -- bash
```
3. Connect using the cqlsh client:
`cqlsh -u <USER_NAME> -p $CASSANDRA_PASSWORD cassandra`

4. Error message appears `Connection error: ('Unable to connect to any servers', {'127.0.0.1:9042': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})`

**Expected behavior**
To not refuse to connection, to be connected to cassandra at cassandra:9042 (from the cassandra-client pod)

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.12", GitCommit:"2cb4598553d0a2ca5f3eb7980c99cd8236cc5011", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:44Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Started with values.yaml file with content:
```yaml
image:
  registry: docker.io
  repository: bitnami/cassandra
  tag: 4.0.0-debian-10-r28
  pullPolicy: IfNotPresent
  debug: true
clusterDomain: cluster.local

persistence:
  enabled: true
cluster:
  name: cassandra
dbUser:
  user: <USER_NAME>
  forcePassword: true
  existingSecret:
    name: <SECRET_NAME>
    keyMapping:
      cassandra-password: password
podLabels:
  name: cassandra

networkPolicy:
  enabled: false
```
