### ISSUE TITLE
[bitnami/kong] do not expose HTTP port in Kong chart

### ISSUE THREAD

**Issue by latituder** [bitnami/charts#7418]
**Which chart**:
The name (and version) of the affected chart.
```
annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 2.5.0
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.x.x
- condition: cassandra.enabled
  name: cassandra
  repository: https://charts.bitnami.com/bitnami
  version: 8.x.x
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 1.x.x
description: Kong is a scalable, open source API layer (aka API gateway or API middleware)
  that runs in front of any RESTful API. Extra functionalities beyond the core platform
  are extended through plugins. Kong is built on top of reliable technologies like
  NGINX and provides an easy-to-use RESTful API to operate and configure the system.
home: https://github.com/bitnami/charts/tree/master/bitnami/kong
icon: https://bitnami.com/assets/stacks/kong/img/kong-stack-220x234.png
keywords:
- kong
- ingress
- openresty
- controller
- http
- web
- www
- reverse proxy
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: kong
sources:
- https://github.com/bitnami/bitnami-docker-kong
- https://konghq.com/
version: 4.0.4
```
**Is your feature request related to a problem? Please describe.**

The current chart must expose HTTP ports in `service.proxyHttpPort` and `service.adminHttpPort`;
seems there's no option to disable the HTTP port expose.

**Describe the solution you'd like**

would it possible to give a true/false option, that to disable HTTP port expose in LB mode svc?
