### ISSUE TITLE
Zombie process created after deploying the etcd chart

### ISSUE THREAD

**Issue by dyasny** [bitnami/charts#7437]
**Which chart**:
The name (and version) of the affected chart

helm.sh/chart: etcd-6.2.3

**Describe the bug**

After deploying the chart, I see a zombie process on all 3 nodes, tracking it's parent to etcd:

```
ubuntu@ip-10-0-1-94:~$ ps -aux |grep Z
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1001       15024  0.0  0.0      0     0 ?        Z    16:06   0:00 [setup.sh] <defunct>
ubuntu     20173  0.0  0.0   8168  2476 pts/0    S+   16:14   0:00 grep --color=auto Z

ubuntu@ip-10-0-1-94:~$ ps -ef|grep 15024
1001       15024   14948  0 16:06 ?        00:00:00 [setup.sh] <defunct>
ubuntu     20247   17669  0 16:14 pts/0    00:00:00 grep --color=auto 15024

ubuntu@ip-10-0-1-94:~$ ps -ef |grep 14948
1001       14948   14366  0 16:06 ?        00:00:03 /opt/bitnami/etcd/bin/etcd
1001       15024   14948  0 16:06 ?        00:00:00 [setup.sh] <defunct>
ubuntu     20251   17669  0 16:14 pts/0    00:00:00 grep --color=auto 14948

```

**To Reproduce**
Deploy the chart, watch for zombies

**Expected behavior**
No zombie processes should appear

**Version of Helm and Kubernetes**:
Tested on vanilla k8s 1.21.2 and 1.22.2 as well as k3s 1.21.2

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+k3s1", GitCommit:"5a67e8dc473f8945e8e181f6f0b0dbbc387f6fca", GitTreeState:"clean", BuildDate:"2021-06-21T20:52:44Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

this is the yaml file I use for etcd:

```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: x-etcd
  namespace: x
  labels:
    app.kubernetes.io/name: etcd
    helm.sh/chart: etcd-6.2.3
    app.kubernetes.io/instance: x
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: etcd
      app.kubernetes.io/instance: x
  serviceName: x-etcd-headless
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etcd
        helm.sh/chart: etcd-6.2.3
        app.kubernetes.io/instance: x
        app.kubernetes.io/managed-by: Helm
      annotations:
    spec:

      affinity:
        podAffinity:

        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: etcd
                  app.kubernetes.io/instance: x
              namespaces:
                - "x"
              topologyKey: kubernetes.io/hostname
        nodeAffinity:

      securityContext:
        fsGroup: 1001
      serviceAccountName: "default"
      containers:
        - name: etcd
          image: docker.io/bitnami/etcd:3.4.15-debian-10-r43
          imagePullPolicy: "IfNotPresent"
          lifecycle:
            preStop:
              exec:
                command:
                  - /opt/bitnami/scripts/etcd/prestop.sh
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETCDCTL_API
              value: "3"
            - name: ETCD_ON_K8S
              value: "yes"
            - name: ETCD_START_FROM_SNAPSHOT
              value: "no"
            - name: ETCD_DISASTER_RECOVERY
              value: "no"
            - name: ETCD_NAME
              value: "$(MY_POD_NAME)"
            - name: ETCD_DATA_DIR
              value: "/bitnami/etcd/data"
            - name: ETCD_LOG_LEVEL
              value: "info"
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "http://$(MY_POD_NAME).x-etcd-headless.x.svc.cluster.local:2379"
            - name: ETCD_LISTEN_CLIENT_URLS
              value: "http://0.0.0.0:2379"
            - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
              value: "http://$(MY_POD_NAME).x-etcd-headless.x.svc.cluster.local:2380"
            - name: ETCD_LISTEN_PEER_URLS
              value: "http://0.0.0.0:2380"
            - name: ETCD_INITIAL_CLUSTER_TOKEN
              value: "etcd-cluster-k8s"
            - name: ETCD_INITIAL_CLUSTER_STATE
              value: "new"
            - name: ETCD_INITIAL_CLUSTER
              value: "x-etcd-0=http://x-etcd-0.x-etcd-headless.x.svc.cluster.local:2380,x-etcd-1=http://x-etcd-1.x-etcd-headless.x.svc.cluster.local:2380,x-etcd-2=http://x-etcd-2.x-etcd-headless.x.svc.cluster.local:2380"
            - name: ETCD_CLUSTER_DOMAIN
              value: "x-etcd-headless.x.svc.cluster.local"
          envFrom:
          ports:
            - name: client
              containerPort: 2379
              protocol: TCP
            - name: peer
              containerPort: 2380
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /opt/bitnami/scripts/etcd/healthcheck.sh
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - /opt/bitnami/scripts/etcd/healthcheck.sh
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: data
              mountPath: /bitnami/etcd
      volumes:
        - name: data
          emptyDir: {}

```
