### ISSUE TITLE
AWS EKS and ALB not deployed when ghostEnableHttps: true and Ingress.enabled: true 

### ISSUE THREAD

**Issue by piiot** [bitnami/charts#7475]
**Which chart**:
Ghost 14.0.13 

**Describe the bug**
ALB resources not created when ghostEnableHttps: true, Ingress.enabled: true, and using ClusterIP serviceType.  Changing ports: name: from "https" to "http" corrects the issue.

**To Reproduce**
1. Deploy chart in AWS EKS using ALB Ingress annotations:

```
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: |
      [{"HTTPS": 80}, {"HTTPS": 443}]
```

2. Receive error from aws-load-balancer-controller:
```
{"level":"error","ts":1631518331.7244165,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ghost2","namespace":"ghost","error":"ingress: ghost/ghost: unable to find port http on service ghost/ghost"}
```

3. In charts/bitnami/ghost/templates/svc.yaml change:

```
  ports:
    {{- if .Values.ghostEnableHttps }}
    - name: https
      port: {{ .Values.service.httpsPort }}
      protocol: TCP
      targetPort: https
```
to:

```
  ports:
    {{- if .Values.ghostEnableHttps }}
    - name: http
      port: {{ .Values.service.httpsPort }}
      protocol: TCP
      targetPort: https
```

4. ALB Ingress created successfully and https:// version of site loads fine with image URL's generated correctly

*changing charts/bitnami/ghost/templates/ingress.yaml path service port from "http" to "https" in order to bypass the error and create the ALB resources results in HTTP 502 errors.
