### ISSUE TITLE
[bitnami/minio] Can't override `ingress.servicePort`

### ISSUE THREAD

**Issue by viceice** [bitnami/charts#7495]
**Which chart**:  bitnami/minio 8.0.0+
The name (and version) of the affected chart.

**Is your feature request related to a problem? Please describe.**
I like to use `ingress.extraHosts` to publish the minio api to be externally accessable.
But currently `servicePort` is fixed to `minio-console`.

**Describe the solution you'd like**
I'sd simply like to override `servicePort`

**Describe alternatives you've considered**
Manually add an extra ingress.

**Additional context**
Sample config which won't work yet

```yaml
ingress:
  enabled: true
  hostname: console.s3.domain.test
  extraHosts:
    - name: s3.domain.test
      servicePort: minio-api

extraEnv:
  - name: MINIO_BROWSER_REDIRECT_URL
    value: https://console.s3.domain.test
```

it's related to
- #7344
- #7480
