### ISSUE TITLE
Not able to add static IP in bitnami kafka helm charts

### ISSUE THREAD

**Issue by GaneshbabuRamamoorthy** [bitnami/charts#7501]
Hi All,

I have been trying to deploy bitnami kafka helm charts on robin platform with static IP’s and I have tried adding the annotations like this in helm charts under the commonAnnotations,

```
commonAnnotations:
     robin.io/networks: [{"ippool": "robin-default", "static_ips": ["fd74:ca9b:3a09:868c:172:18:0:48f5","fd74:ca9b:3a09:868c:172:18:0:42e4","fd74:ca9b:3a09:868c:172:18:0:4636"]}] 
```

When I gave like this, pod didn’t come up so for testing I have tried adding it in the templates/statefulsets.yaml file,

```
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "kafka.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: kafka
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  #{{- if .Values.commonAnnotations }}
  #annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  **annotations:
    robin.io/networks: '[{"ippool": "robin-default", "static_ips": ["fd74:ca9b:3a09:868c:172:18:0:48f5","fd74:ca9b:3a09:868c:172:18:0:42e4","fd74:ca9b:3a09:868c:172:18:0:4636"]}]'**
  #{{- end }}
```

After deploying the pod came up but when exec into the each pods and tried hostname -I
I can see two IP’s were assigned to pod but the third IP didn’t match from the static IP.

Also when I tried describe the pod,

kubectl describe pod kafka-0,
I am not able to see the robin network status like how we see it in scylladb pod,

![image](https://user-images.githubusercontent.com/20658619/133560255-aba6fdb3-d6ea-474b-9e91-41918491dfa4.png)

Can you please guide me how we can resolve this issue?
 

Thanks,
Ganeshbabu R
