### ISSUE TITLE
[bitnami/mongodb] use pdb of arbiter is not possible

### ISSUE THREAD

**Issue by rafernandez** [bitnami/charts#7545]
**Which chart**:
bitnami/mongodb

**Describe the bug**

How to use PDB feature with only 1 arbiter ? (replica number is not configurable)

**To Reproduce**
Deploy with one arbiter and PDB enable : 
```
arbiter:  
  pdb:
    create: true
```
Drain the node where arbiter is located.

Drain is blocked by PDB rule : 
```
evicting pod infra/mongodb-arbiter-0
error when evicting pods/"mongodb-arbiter-0" -n "infra" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"0b17c6315e806a66d507e77760a5d60ab5cccfd8", GitTreeState:"clean", BuildDate:"2021-08-30T01:42:22Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

To use arbiter's PDB, don't we need to be able to define the number of replicas?

**Comment by randradas** [comment]
Hello @rafernandez thank you for the issue, I need time to study it, I'll be back.

**Comment by rafariossaa** [comment]
I am leaving this issue closed.
Feel free to post a message to reopen it.

**Comment by rafernandez** [comment]
Hello @randradas @rafariossaa , sorry for the delay.

Command and values for deploy : 

* Helm command :
```
helm upgrade --install --history-max 5 \ 
      --create-namespace \
      -f helm/mongodb/values.yml \
      --set auth.rootPassword=XXXXXXXXX \
      --set auth.replicaSetKey=XXXXXXXX \
      --version 10.27.2 \
      mongodb bitnami/mongodb
```
* Values file : 
```
image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 4.4.6-debian-10-r8
architecture: replicaset
replicaCount: 2
resources:
  limits:
    cpu: 1000m
    memory: 10Gi
  requests:
    cpu: 500m
    memory: 8Gi
persistence:
  enabled: true
  storageClass: mongodb-data-standardhdd-lrs
  accessModes:
    - ReadWriteOnce
  size: 50Gi
extraFlags:
  - "--enableMajorityReadConcern=false"
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: mongodb
            app.kubernetes.io/name: mongodb
        namespaces:
        - "{{ .Release.Namespace }}"
        topologyKey: kubernetes.io/hostname
      weight: 1
pdb:
  create: true
arbiter:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: mongodb
              app.kubernetes.io/name: mongodb
          namespaces:
          - "{{ .Release.Namespace }}"
          topologyKey: kubernetes.io/hostname
        weight: 1
```

Thanks !

**Comment by rafariossaa** [comment]
Could you indicate how the mongodb pods are spread across the k8s nodes ? 
Maybe the PDB is not "compatible" with the AntiAffinity and your k8s size.

**Comment by rafernandez** [comment]
Hello @rafariossaa 

3 nodes with one mongodb instance (replica or arbiter) per node.
I customized AntiAffinity pod so that the arbiter not on the same node as the replicas.

Thanks !

**Comment by rafariossaa** [comment]
Could it be that when the node where the arbiter is running get drained kubernetes doesn't not have a node where to move the pod because the antiaffinity that is set ?.

**Comment by rafernandez** [comment]
Hello @rafariossaa 
I don't think it's an pod antiaffinity issue.
I started from a new fresh install to do some tests (without antiaffinity define) : 
* Values :
```
image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 4.4.6-debian-10-r8
architecture: replicaset
replicaCount: 2
persistence:
  enabled: true
  storageClass: mongodb-data-premiumsdd-lrs
  accessModes:
    - ReadWriteOnce
  size: 30Gi
pdb:
  create: true
arbiter:
  pdb:
    create: true
```
* This configuration created 2 pdb objects : 
```
NAME              MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
mongodb           1               N/A               1                     43h
mongodb-arbiter   1               N/A               0                     40m
```
* Review of the mongo arbiter pdb object : 
```
kubectl get pdb -n infra mongodb-arbiter -o yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    meta.helm.sh/release-name: mongodb
    meta.helm.sh/release-namespace: infra
  creationTimestamp: "2021-12-10T13:17:34Z"
  generation: 1
  labels:
    app.kubernetes.io/component: arbiter
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.27.2
  name: mongodb-arbiter
  namespace: infra
  resourceVersion: "605678"
  uid: 8a1c1fdd-31d6-49c0-aa6a-75be115fbf66
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: arbiter
      app.kubernetes.io/instance: mongodb
      app.kubernetes.io/name: mongodb
status:
  conditions:
  - lastTransitionTime: "2021-12-10T13:17:34Z"
    message: ""
    observedGeneration: 1
    reason: InsufficientPods
    status: "False"
    type: DisruptionAllowed
  currentHealthy: 1
  desiredHealthy: 1
  disruptionsAllowed: 0
  expectedPods: 1
  observedGeneration: 1
```
* Nodes topology : 
```
 kubectl get pods -A -o wide | grep  mongo
infra         mongodb-0                                               1/1     Running   0          4h18m   10.1.1.83    aks-pool00-76703125-vmss000007   <none>           <none>
infra         mongodb-1                                               1/1     Running   0          4h11m   10.1.0.158   aks-pool00-76703125-vmss000006   <none>           <none>
infra         mongodb-arbiter-0                                       1/1     Running   0          4h18m   10.1.0.103   aks-pool00-76703125-vmss000006   <none>           <none>
```
When i drain the node where mongo-arbiter pod is located : 
```
kubectl drain aks-pool00-76703125-vmss000006 --ignore-daemonsets --delete-emptydir-data
evicting pod infra/mongodb-1
error when evicting pods/"mongodb-arbiter-0" -n "infra" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
```
This is normal because the mongodb arbiter pdb rule tolerates 1 available pod.

Finally, shouldn't we define a pdb rule for all mondodb pods ? (replica and arbiter with the same match label selector for pdb object ?)

Thanks !
