### ISSUE TITLE
Clear documentation on values.yaml format

### ISSUE THREAD

**Issue by gmisura** [bitnami/charts#7550]
**Which chart**:
mongodb (but I'm guessing it impacts more)

**Describe the bug**
Documentation at
https://github.com/bitnami/charts/tree/master/bitnami/mongodb#mongodb-parameters
 says to override the image in values.yaml, use

```
image.registry: my-registry
image.repository: my/path/to/image
image.tag: mytag
```

**To Reproduce**

1. `helm install my-app my-chart -f values.yaml` with the values.yaml from above.
1. `oc describe deployment my-deployment | grep Image`
1. returns: Image: docker.io/bitnami/mongodb:4.4.9-debian-10-r0

**Expected behavior**
`oc describe deployment my-deployment | grep Image`
Should return
```
   Image: my-registry/my/path/to/image:mytag
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildINfo{Version:"v3.7.0", GitCommit: "eeac83883cb44014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8" 
```

- Output of `kubectl version`:

```
oc version
Client Version: 4.6.0-202103130248.p0-aaa9ca3
Kubernetes Version: v1.19.0+4c3480d
```

**Additional context**
I believe the "solution" is to improve the documentation so that it's clear the section must be a child of "mongodb"

```
mongodb:
  image.registry: my-registry
  image.repository: my/path/to/image
  image.tag: mytag
```

**Comment by miguelaeh** [comment]
Hi @gmisura ,
You are not using a valid `values.yaml`. You need to change it to:
```
image: 
  registry: my-registry
  repository: my/path/to/image
  tag: mytag
```
