### ISSUE TITLE
s3 gateway using aws role attached to the pod 

### ISSUE THREAD

**Issue by olektretiak** [bitnami/charts#7559]
**Is your feature request related to a problem? Please describe.**
According to the best practice, it's not a good idea to use was credentials for the infrastructure, it's a major recommendation from AWS.

**Describe the solution you'd like**
The idea is to attach annotation in the service account which will allow POD to use AWS services.

```
  serviceAccount:
    create: true
    # The name of the service account is autogenerated by default
    name:
    # annotations: {}
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::{accoiut_id}:role/s3-minio-role
```
