### ISSUE TITLE
mongodb fail to install as depency

### ISSUE THREAD

**Issue by ognif** [bitnami/charts#7589]
**Which chart**:
mongodb

**Describe the bug**
Try to install the mongodb with depencies function inside another chart.  
```
Error: template: sb-ep/charts/mongodb/templates/standalone/svc.yaml:5:11: executing "sb-ep/charts/mongodb/templates/standalone/svc.yaml" at <include "mongodb.fullname" .>: error calling include: template: sb-ep/charts/mongodb/templates/_helpers.tpl:15:4: executing "mongodb.fullname" at <include "common.names.fullname" .>: error calling include: template: no template "common.names.fullname" associated with template "gotpl"
```

Also get an error with replicaset
```
08:46:17  Error: UPGRADE FAILED: template: sb-ep/charts/mongodb/templates/replicaset/statefulset.yaml:5:15: executing "sb-ep/charts/mongodb/templates/replicaset/statefulset.yaml" at <include "common.capabilities.statefulset.apiVersion" .>: error calling include: template: no template "common.capabilities.statefulset.apiVersion" associated with template "gotpl"
```

**Chart.yaml**
My Chart.yaml
```
apiVersion: v2
name: sb-ep
description: Helm Chart for the My product
type: application
version: 0.1.0
appVersion: 0.6.0

dependencies:
- name: couchdb
  version: 3.3.3
  repository: https://apache.github.io/couchdb-helm
  condition: couchdb.enabled
  ###Ich mache mal einen Linie rein
- name: mongodb
  version: 9.2.5
  repository: https://charts.bitnami.com/bitnami/mongodb
```

**values.yaml**
```
mongodb:
  auth:
    rootPassword: password
    replicaSetKey: key1234567890
  #architecture: standalone
  architecture: replicaset 
  useStatefulSet: true
  arbiter:
    enabled: false 
  replicaCount: 1 
```

**charts folder**
mongodb-9.2.5.tgz
couchdb-3.3.3.tgz

**To Reproduce**
Install as depency

```
dependencies:
- name: couchdb
  version: 3.3.3
  repository: https://apache.github.io/couchdb-helm
  condition: couchdb.enabled
- name: mongodb
  version: 9.2.5
  repository: https://charts.bitnami.com/bitnami/mongodb
  architecture: standalone
  service.nameOverride: adt-mongodb
  useStatefulSet: true
```

**Expected behavior**
Successfull installation

**Version of Helm and Kubernetes**:
helm 3.6.2
Kubernetes 1.18

- Output of `helm version`: Standalone
```
Error: template: sb-ep/charts/mongodb/templates/standalone/svc.yaml:5:11: executing "sb-ep/charts/mongodb/templates/standalone/svc.yaml" at <include "mongodb.fullname" .>: error calling include: template: sb-ep/charts/mongodb/templates/_helpers.tpl:15:4: executing "mongodb.fullname" at <include "common.names.fullname" .>: error calling include: template: no template "common.names.fullname" associated with template "gotpl"
```
- Output of `helm version`: Replicaset
```
08:46:17  Error: UPGRADE FAILED: template: sb-ep/charts/mongodb/templates/replicaset/statefulset.yaml:5:15: executing "sb-ep/charts/mongodb/templates/replicaset/statefulset.yaml" at <include "common.capabilities.statefulset.apiVersion" .>: error calling include: template: no template "common.capabilities.statefulset.apiVersion" associated with template "gotpl"
```

**Comment by ognif** [comment]
The errors do not stop with this helm chart.

**Comment by miguelaeh** [comment]
Hi @ognif ,
It seems you are missing the common chart. All the bitnami charts use the `common` chart as a function library. Please execute `helm dependencies update` and try again.

Also, FYI your dependencies are wrong, you will need to apply this:
```diff
  version: 9.2.5
- repository: https://charts.bitnami.com/bitnami/mongodb
+ repository: https://charts.bitnami.com/bitnami/
```

**Comment by Hkyx** [comment]
In my case I needed to change bitnami-common to common

**Comment by ognif** [comment]
I have added bitnami "common" as depency and it works well. Userbug

**Comment by miguelaeh** [comment]
Thank you very much for the confirmation

**Comment by Hkyx** [comment]
> I have added bitnami "common" as depency and it works well. Userbug

something like that ? 

```
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
      - common
```

**Comment by miguelaeh** [comment]
This is how we add it to our charts:
```
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
```
