### ISSUE TITLE
[bitnami/minio] console does not bind to configured port

### ISSUE THREAD

**Issue by DaviGia** [bitnami/charts#7591]
**Which chart**:
minio:8.1.1

**Describe the bug**
Minio web console cannot be accessed because it appears that the `--console-address` argument is not passed to the server. Moreover I have the following message in the pod log: 

``` log
WARNING: Console endpoint is listening on a dynamic port (35734), please use --console-address ":PORT" to choose a static port.
```

**To Reproduce**
Deploy the chart using the following values:

``` yml
ingress:
  enabled: true
gateway:
  enabled: true
  replicaCount: 1
  autoscaling:
    minReplicas: 1
  auth:
    s3:
      accessKey: [REDACTED]
      secretKey: [REDACTED]
```

**Expected behavior**

The minio console should bind to the port specified in the value `service.ports.console` (i.e. 9001).

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
