### ISSUE TITLE
[kube-prometheus] No Custom Metrics in Prometheus

### ISSUE THREAD

**Issue by maxinfosoft** [bitnami/charts#7593]
I have installed:
`helm install kube-prometheus bitnami/kube-prometheus -f values.yaml`

Contents values.yaml:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myservice
  labels:
    app: myservice
    release: prometheus
spec:
  selector:
    matchLabels:
      app: myservice
  endpoints:
  - targetPort: 10100
  - interval: 5s
    path: /prometheus
  namespaceSelector:
    any: true
```

I launch prometheus dashboard through port-forward and see myservice in prometheus target & prometheus service discovery.
I also see all metrics of my application https://myservice/prometheus, which generates my application in prometheus-format.
**Problem:**
I do not see any metrics of my service in prometheus dashboard http://localhost/graph and therefore I can not use these metrics to build graphs or create a query.
