### ISSUE TITLE
[bitnami/mongodb] Unable to reference parent values in annotation template value

### ISSUE THREAD

**Issue by percenuage** [bitnami/charts#7594]
**Which chart**:
bitnami/mongodb@10.6.1

**Describe the bug**
I have a chart with a mongodb as subchart.
```yaml
# chart.yaml
apiVersion: v2
name: toto
type: application
version: 2.0.0
appVersion: v1

dependencies:
  - name: mongodb
    version: 10.6.1
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled

```
I would like to reference one annotation locate it in global values to mongodb annotation (and arbiter) to avoir duplication.

```yaml
# values.yaml
fullnameOverride: my-app
...
annotations:
  downscaler: always
...
mongodb:
  enabled: true
  fullnameOverride: my-db
  annotations:
    downscaler: "{{ .Values.annotations.downscaler }}"

```

In mongodb replicatset/deployment, the result is:
```yaml
...
annotations:
  downscaler: '' # Should be "always"
...
```

If you change  `.Values.annotations.downscaler` by  `.Values.fullnameOverride`, you will have:
```yaml
...
annotations:
  downscaler: my-db # Should be "my-app"
...
```

Question Bonus:
My real annotation is `downscaler/uptime` but I can't ref like `downscaler: "{{ .Values.annotations.downscaler/uptime }}"` because of "/". DO you know how to do it?

**To Reproduce**
See above :)

**Expected behavior**
```yaml
...
annotations:
  downscaler: always # or my-app
...
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.9-gke.701", GitCommit:"5f13de0910e4eb40c1c6b3b44704b25313a2c80c", GitTreeState:"clean", BuildDate:"2021-08-18T17:05:42Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I'm using inheritance of Helm values. So I don't want to use anchor because I have to repeat anchor in every helm values.

**Comment by percenuage** [comment]
For the bonus, I found at least this : `downscaler/uptime: '{{ index .Values "downscaler/uptime" }}'` 😄

**Comment by pablogalegoc** [comment]
Hi @percenuage!

AFAIK templating in the `values.yaml` is still not supported by Helm. You can find a good (old) explanation [here](https://github.com/helm/helm/issues/2492#issuecomment-413635332).

**Comment by percenuage** [comment]
> Hi @percenuage!
> 
> AFAIK templating in the `values.yaml` is still not supported by Helm. You can find a good (old) explanation [here](https://github.com/helm/helm/issues/2492#issuecomment-413635332).

Hi @pablogalegoc,

Ok so I have to write many times the same value? It's a not DRY. I would have avoided if I could but here it's a subchart so I can't edit bitnami template (I don't want also).

**Comment by pablogalegoc** [comment]
The only feature that I know that slightly resembles what you are looking for is imports/exports: [Importing Child Values via dependencies](https://helm.sh/docs/topics/charts/#importing-child-values-via-dependencies).

**Comment by percenuage** [comment]
@pablogalegoc, Thanks but its not really that it's more the opposite :)

On [Bitnami/mongodb chart](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/replicaset/statefulset.yaml), there is this template for annotations: 
```yaml
annotations:
    {{- if .Values.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.annotations "context" $) | nindent 4 }}
    {{- end }}
```
On the [Bitnami/common chart](https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_tplvalues.tpl) helpers there is this define:
```yaml
Renders a value that contains template.
Usage:
{{ include "common.tplvalues.render" ( dict "value" .Values.path.to.the.Value "context" $) }}
*/}}
{{- define "common.tplvalues.render" -}}
    {{- if typeIs "string" .value }}
        {{- tpl .value .context }}
    {{- else }}
        {{- tpl (.value | toYaml) .context }}
    {{- end }}
{{- end -}}
```
I don't really understand what "dict" does exactly.

I think I need on my side to add something so that Helm look on the parent values rather than on the current child values (mongodb). I tried this without success: `"{{ $.Values.annotations.downscaler }}"`

**Comment by percenuage** [comment]
I've found this on https://docs.helm.sh/docs/chart_template_guide/subcharts_and_globals/
```yaml
global:
  annotations:
    downscaler/uptime: always
```
That could be enough for me 😄
