### ISSUE TITLE
[bitnami/rabbitmq] Cluster partition immediately after app start

### ISSUE THREAD

**Issue by Schlurps** [bitnami/charts#7606]
**Which chart**:
bitnami/rabbitmq 8.0.0

**Describe the bug**
We are trying to run a rabbitmq cluster with 3 nodes, but sometimes, the nodes are unable to find each other and will then
create two distinct clusters.

As you can imagine, this makes the helm chart practically unusable for us, as it is complete luck whether the cluster is able to form correctly and there also seems to be no way to manually fix the partition.

**To Reproduce**

Simply install version 8.0.0 using the following values:

```yaml
persistence:
  enabled: true
replicaCount: 3
resources:
  requests:
    memory: 2Gi
    cpu: 100m
  limits:
    memory: 2Gi
    cpu: 200m
memoryHighWatermark:
  enabled: true
networkPolicy:
  enabled: true
  allowExternal: true
pdb:
  create: true
```

Note that the problem doesn't appear on every installation, so may have to try it a couple of times.

**Expected behavior**
All rabbitmq nodes should be part of the same cluster.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.19) exceeds the supported minor version skew of +/-1
```

**Additional context**

I attached the logs of the individual nodes after startup. Note that in this case, node 0 and node 2 formed a cluster,
while node 1 formed its own cluster.

[srsng-infra-rabbitmq-0.log](https://github.com/bitnami/charts/files/7218373/srsng-infra-rabbitmq-0.log)
[srsng-infra-rabbitmq-1.log](https://github.com/bitnami/charts/files/7218376/srsng-infra-rabbitmq-1.log)
[srsng-infra-rabbitmq-2.log](https://github.com/bitnami/charts/files/7218380/srsng-infra-rabbitmq-2.log)

**Comment by alemorcuq** [comment]
Hi, @Schlurps.

`8.0.0` is quite behind the latest version of the chart, `8.22.2`. Have you checked if this still happens in the latest one?

**Comment by Yamakaky** [comment]
Hello, I have the same issue. I'm using the operator 3.2.10 (docker image 2.2.0) with the default rabbitmq version 3.11.11 and a replica count of 3. Occasionally, two clusters are created, with one cluster of two nodes and another one with one node. This look like the same issue as https://github.com/rabbitmq/cluster-operator/issues/662, with some people mentioning it could be related to bitnami-specific configuration, not sure how to verify that claim. 

My cluster have limited resources (200m, 500Mi) so maybe this is a racing condition with some timeout expiring before two pods become ready, so they each think they are the only pod. This doesn't often happen so this is hard to test.

A debug/mitigation step I found are as follow:
1. Run `rabbitmq-diagnostics cluster_status` on the three pods and identify the cluster with only one peer
2. On this pod, run `rabbitmqctl stop_app && rabbitmqctl reset && rabbitmqctl start_app` to reset it and force it to connect to the main cluster.

This is obviously not ideal, since every cluster needs to be checked that way.

The cluster is deployed as a statefulset, so with fixed pod names. Would it be possible to add some check/condition so that only pod `xxxx-0` is allowed to create a new cluster, and not `xxxx-*`?

It may be the same problem as https://github.com/bitnami/charts/issues/7429.

**Comment by CeliaGMqrz** [comment]
Hi @Yamakaky,

Sorry for the delay. Thanks for reporting this issue!

Sorry, but I have not been able to reproduce the issue. I have reviewed the logic, it is possible that in some scenarios this is expected. 

>Edit: I managed to reproduce the issue with the following config, with 7 replicas (I assume this increases the chance the problem occurs) and the latest 3.4.2 oci release. It took a few tries to get a split cluster. I still have it available if you need additional information.

Could you provide the additional information you mention? Maybe we can reproduce it and review the logic in a more detailed environment. 

Thanks for your feedback!

**Comment by Yamakaky** [comment]
Hum, I don't have specific information in mind, do you have some you would like to have? One thing I didn't mention is that my cluster is on GCP over 3 availability zones, so maybe the network delays between nodes increase the problem?

**Comment by Yamakaky** [comment]
Please tell me if you need additional information like specific logs, manual tests to run, etc... I'm new to rabbitmq so I don't really know what would be useful to you.

**Comment by CeliaGMqrz** [comment]
Hi @Yamakaky,

Sorry, we are not able to reproduce the issue on our side. It seems it is not an issue related to the Bitnami RabbitMQ container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by fmulero** [comment]
Hi @Yamakaky 

NOTE: I am assuming you are using [bitnami/rabbitmq-cluster-operator](https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq-cluster-operator). I tested with version: 3.6.5

I tried to create a cluster with the configuration provided but the resources seems very low for rabbit and I can't get any pod ready. Leaving the default configuration and setting only the number of replicas and the log config:
```yaml
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: testrmq
spec:
  replicas: 7
  rabbitmq:
    additionalConfig: |
      # Print logs to stdout
      # https://www.rabbitmq.com/logging.html#logging-to-console
      log.console = true
```

After 10 minutes just only 1 pod gets ready... The situation doesn't look good. Could you share logs from your pods and could run `rabbitmqctl cluster_status` in each pod?

**Comment by Yamakaky** [comment]
My bad, with the vacations I forgot about this issue.

@fmulero do you still need the logs? Since it's the default configuration (ignoring `log.console`) I'm not sure what my logs would bring. Or do you mean give logs on a split brain cluster?

**Comment by fmulero** [comment]
Hi @Yamakaky, I was trying to reproduce again the case with latest version and I didn't have luck. I reduced the number of resources assigned with the values you shared but the cluster finally spin up (taking much longer than expected) successfully. Have you got a concrete steps to reproduce it? These is the `RabbitmqCluster` object  I used:
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: testrmq
spec:
  replicas: 3
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 512Mi
  persistence:
    storage: "10Gi"
  rabbitmq:
    additionalConfig: |
      # Print logs to stdout
      # https://www.rabbitmq.com/logging.html#logging-to-console
      log.console = true
```
