### ISSUE TITLE
Grafana HTTPS liveliness and readiness probes

### ISSUE THREAD

**Issue by Forbzy** [bitnami/charts#7611]
**Which chart**:
Grafana
Version: 6.1.15

**Is your feature request related to a problem? Please describe.**
I can configure grafana to use HTTPS instead of HTTP. However liveness and readiness probes will only check against HTTP which means pods won't get a ready state.

**Describe the solution you'd like**
Below are code snippets that might work if you put them in the deployment.yaml and make the relevant changes in the values.yaml. We just need to be able to set `scheme: HTTPS`. By default it can be `scheme: HTTP`. 

```
          readinessProbe:
            httpGet:
              path: /api/health
              port: dashboard
              scheme: {{ .Values.readinessProbe.scheme }}
```  
```
          livenessProbe:
            httpGet:
              path: /api/health
              port: dashboard
              scheme: {{ .Values.livenessProbe.scheme }}
```
