### ISSUE TITLE
Is it possible to add some dedicated users for ops usage ?

### ISSUE THREAD

**Issue by maulal** [bitnami/charts#7616]
**Which chart**: mongodb

**Is your feature request related to a problem? Please describe.**
Is it possible to add some dedicated users for ops usage as we do for the metrics user ? like:
- a **backup** user
- a **restore** user

And maybe consider refactor the auth values.

**Describe the solution you'd like**
Something like:
adding this to the `values.yaml` file
```yaml
auth:
  enabled: true
  root:
    username: root
    password: ""
  app:
    username: ""
    password: ""
    database: ""
  backup:
    username: ""
    password: ""
  restore:
    username: ""
    password: ""
  metrics:
    username: ""
    password: ""
```

- **backup** user creation to add during the initial sync
```
db.createUser({user: '{{ .Values.auth.backup.username }}', pwd: '{{ .Values.auth.backup.password }}', roles: [{ role: 'clusterMonitor', db: 'admin' }, { role: 'backup', db: 'admin' }] });
```
- **restore** user creation to add during the initial sync
```
db.createRole({role: 'restore-pitr', privileges: [{ resource: {anyResource: true}, actions: [ 'anyAction' ] }], roles: [] });
db.createUser({user: '{{ .Values.auth.restore.username }}', pwd: '{{ .Values.auth.restore.password }}', roles: [{ role: 'restore-pitr', db: 'admin' }, { role: 'restore', db: 'admin' }, { role: 'dbAdmin', db: 'admin' }, { role: 'dbAdminAnyDatabase', db: 'admin' }] });
```

**Additional context**
For the moment, i'm only writing an Issue, but i can work on the PR if the idea seems to look good for the maintainers team :)
Thanks all.
