### ISSUE TITLE
Setting db.host messes with Ingress-Certificate

### ISSUE THREAD

**Issue by boindil** [bitnami/charts#7638]
I'm extremely confused, but I narrowed the problem down to the following.

1. I am using a ClusterIssuer with letsencrypt utilizing a central cert-manager.
2. I try to set db.host for the helm chart
3. The previous steps result in a different (Self-Signed) Certificate being issued by "phpmyadmin-ca" which is actually really confusing to me. Leaving the db.host blank will result in the correct Letsencrypt certificate being issued and used in the ingress.

The helm chart looks like the following:
```
affinity: {}
args: []
clusterDomain: cluster.local
command: []
commonAnnotations: {}
commonLabels: {}
containerPorts:
  http: 8080
  https: 8443
containerSecurityContext:
  enabled: true
  runAsUser: 1001
customLivenessProbe: {}
customReadinessProbe: {}
db:
  allowArbitraryServer: true
  bundleTestDB: false
  chartName: ''
  enableSsl: false
  host: mariadb-galera.my-mariadb-galera-cluster
  port: 3306
  ssl:
    caCertificate: ''
    ciphers: []
    clientCertificate: ''
    clientKey: ''
    verify: true
extraDeploy: []
extraEnvVars: []
extraEnvVarsCM: ''
extraEnvVarsSecret: ''
extraVolumeMounts: []
extraVolumes: []
fullnameOverride: ''
global:
  imagePullSecrets: []
  imageRegistry: ''
hostAliases:
  - hostnames:
      - status.localhost
    ip: 127.0.0.1
image:
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: docker.io
  repository: bitnami/phpmyadmin
  tag: 5.1.1-debian-10-r98
ingress:
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    cert-manager.io/issuer-kind: ClusterIssuer
  certManager: false
  enabled: true
  extraHosts: []
  extraTls: []
  hostname: subdomain.my-domain.com
  pathType: ImplementationSpecific
  secrets: []
  tls: true
initContainers: []
kubeVersion: ''
livenessProbe:
  enabled: true
  failureThreshold: 6
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 30
mariadb: {}
metrics:
  enabled: false
  image:
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/apache-exporter
    tag: 0.10.1-debian-10-r3
  resources: {}
  service:
    annotations:
      prometheus.io/port: '{{ .Values.metrics.service.port }}'
      prometheus.io/scrape: 'true'
    loadBalancerIP: ''
    port: 9117
    type: ClusterIP
  serviceMonitor:
    additionalLabels: {}
    enabled: false
    honorLabels: false
    interval: 30s
    jobLabel: ''
    metricRelabelings: []
    namespace: ''
    relabellings: []
    scrapeTimeout: ''
nameOverride: ''
nodeAffinityPreset:
  key: ''
  type: ''
  values: []
nodeSelector: {}
podAffinityPreset: ''
podAnnotations: {}
podAntiAffinityPreset: soft
podLabels: {}
podSecurityContext:
  enabled: true
  fsGroup: 1001
readinessProbe:
  enabled: true
  failureThreshold: 6
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 30
resources:
  limits: {}
  requests: {}
service:
  annotations: {}
  clusterIP: ''
  externalTrafficPolicy: Cluster
  httpsPort: 443
  loadBalancerIP: ''
  loadBalancerSourceRanges: []
  nodePorts:
    http: ''
    https: ''
  port: 80
  type: ClusterIP
sidecars: []
tolerations: []
updateStrategy:
  type: RollingUpdate
```
