### ISSUE TITLE
[bitnami/rabbitmq] Clustering RabbitMQ

### ISSUE THREAD

**Issue by Scorito-Dev** [bitnami/charts#7641]
**Which chart**:
rabbimq 
https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq

version; 8.22.3

**Describe the bug**
We activated Clustering on our cluster, but I cannot see that is has been activated, when 1 node goes offline all producers and consumers are reporting that the queue is not available anymore.

These are the settings I am talking about (rebalance and forceboot are set to true)
![image](https://user-images.githubusercontent.com/83391962/135077539-88bd7132-4262-4eb5-ad45-029a63f21001.png)

When I look at the queue I see that is assigned to a specific node (in this case node 0) as soon as I delete this node the queue will become unavailable.
I assumed that this would mean that the queue will always be available.
![image](https://user-images.githubusercontent.com/83391962/135077995-17dfa22b-90a7-416e-bbb9-c6708d45501a.png)

**Comment by carrodher** [comment]
Can you share with us the custom values you are using? Take into account that, by default, `clustering.rebalance` and `clustering.forceBoot` are set to _false_, which means the logic or env. variables related to those features are not going to be taken into account during the deployment.
You need to manually set those parameters to _true_ in order to make it works.

**Comment by Scorito-Dev** [comment]
Thank you for your response! We have the following overwrite values when we apply the helm chart:
` --set clustering.rebalance=true --set clustering.forceBoot=true`

I might be misunderstanding the documentation but we have 3 nodes, 1 queue is only available on 1 node.
My understanding of clustering is that it can be available on the other's as well, it seems like 'quorum queue' is something I need to activate on the queue to have them sync to other nodes.
Is this correct?

 How can I verify if clustering is working as intended?

**Comment by carrodher** [comment]
By setting those values we modify the container behavior. When `clustering.forceBoot` is set to _true_ the RABBITMQ_FORCE_BOOT env. variable is set to _yes_. In the same way, when `clustering.rebalance` is set to _true_ the following postStart event is executed but **only if the number of replicas is greater than 1** (which is not the default value). 

We can see this by taking a look at the _stafulset.yaml_ file
```yaml
             - name: RABBITMQ_FORCE_BOOT
               value: {{ ternary "yes" "no" .Values.clustering.forceBoot | quote }}
...
           lifecycle:
           {{- if and .Values.clustering.rebalance (gt (.Values.replicaCount | int) 1) }}
             postStart:
               exec:
                 command:
                   - /bin/bash
                   - -ec
                   - |
                     until rabbitmqctl cluster_status >/dev/null; do
                         echo "Waiting for cluster readiness..."
                         sleep 5
                     done
                     rabbitmq-queues rebalance "all"
           {{- end }}
```

I just installed the chart and did some tests:
```console
$ helm install rabbit --set clustering.enabled=true --set clustering.rebalance=true --set clustering.forceBoot=true -n crhrabbit bitnami/rabbitmq

$ kubectl get pods -n crhrabbit
NAME                READY   STATUS    RESTARTS   AGE
rabbit-rabbitmq-0   1/1     Running   0          8m49s

$ kubectl exec -it rabbit-rabbitmq-0 -n crhrabbit -- env | grep RABBITMQ_FORCE_BOOT
RABBITMQ_FORCE_BOOT=yes
```

The `RABBITMQ_FORCE_BOOT` env. variable is properly set inside the rabbitmq container, but on the other hand, the `postStart` event was not defined because the number of replicas is one. Now, installing the chart with 3 replicas this is the result:
```console
$ helm install rabbit3 --set clustering.enabled=true --set clustering.rebalance=true --set clustering.forceBoot=true --set replicaCount=3 -n crhrabbit bitnami/rabbitmq

$ kubectl get pods -n crhrabbit

$ kubectl get pods -n crhrabbit
NAME                 READY   STATUS    RESTARTS   AGE
rabbit3-rabbitmq-0   1/1     Running   1          24m
rabbit3-rabbitmq-1   1/1     Running   1          16m
rabbit3-rabbitmq-2   0/1     Running   1          8m17s

$ kubectl exec -it rabbit3-rabbitmq-0 -n crhrabbit -- env | grep RABBITMQ_FORCE_BOOT
RABBITMQ_FORCE_BOOT=yes
$ kubectl exec -it rabbit3-rabbitmq-1 -n crhrabbit -- env | grep RABBITMQ_FORCE_BOOT
RABBITMQ_FORCE_BOOT=yes
$ kubectl exec -it rabbit3-rabbitmq-2 -n crhrabbit -- env | grep RABBITMQ_FORCE_BOOT
RABBITMQ_FORCE_BOOT=yes
```

In this case, Kubernetes should send the postStart event immediately after the container is created, if the pod is restarted and the container is recreated, the postStart event should be executed running the `rabbitmq-queues rebalance "all"` command.

[Here](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#recover-the-cluster-from-complete-shutdown) you can find more info about clustering, in the same way, the [official documentation](https://www.rabbitmq.com/clustering.html) can also provide more info.

Apart from that, there is another solution `bitnami/rabbitmq-cluster-operator` (more complex, see https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq-cluster-operator) that can fit better depending on your specific use case.
