### ISSUE TITLE
[bitnami/thanos] Enable editing "--min-time"

### ISSUE THREAD

**Issue by DuckInCyber** [bitnami/charts#7653]
Thanos-5.4.0

Hi, I can't view history older than 10 days and there is no where to edit this.
There is no way to change "--min-time".

This is what I get:

![image](https://user-images.githubusercontent.com/37802070/135295142-9810d1a1-740b-4911-8e73-e3afca6bb5af.png)

**Comment by marcosbc** [comment]
Hi @DuckInCyber, have you tried configuring the following values?

```
storegateway:
  sharded:
    enabled: false
    hashPartitioning:
      shards: ""
    timePartitioning:
      - min: ""
        max: ""
```

You can set them via CLI with `--set storegateway.sharded.enabled=true --set "storegateway.sharded.timePartitioning[0].min"=whatever`.
