### ISSUE TITLE
[bitnami/grafana] Add volumePermissions support

### ISSUE THREAD

**Issue by jack1902** [bitnami/charts#7662]
**Which chart**:
Chart: Grafana
Version: 

**Is your feature request related to a problem? Please describe.**
When I spin up the grafana chart, I get permission denied errors with no changes made to the values.yaml. I have encountered similar issues before and have fixed it by using `volumePermissions.enabled = true" for the elasticsearch chart. Upon looking at the grafana chart, I don't see a similar option.

https://github.com/bitnami/charts/blob/bbf403bae78be53430fbf13e462f9bd1eeb5bf04/bitnami/elasticsearch/values.yaml#L1642-L1645

**Describe the solution you'd like**
Be able to set `volumePermissions.enabled` to true similar to the elasticsearch chart link above to enable the pod to come up

**Describe alternatives you've considered**
I had a look https://github.com/bitnami/charts/issues/5568 but it wasn't very apparent what the solution is (unless it's setting the fsgroup to `0` but ideally id prefer to run my pod as non-root for everything

**Comment by jack1902** [comment]
For anyone who stumbles into this in the future, the original error was `mkdir: cannot create directory '/opt/bitnami/grafana/data/plugins': Permission denied`. To fix this, use `securityContext.fsGroup=0` and the pod will start up

**Comment by Mauraza** [comment]
Hi @jack1902,

Could you share the values are you using to deploy Grafana?

**Comment by jack1902** [comment]
@Mauraza Sure, on top of the default values file, i am passing the following in a separate file to helm `-f myvalues.yaml`

<details>
<summary><code>myvalues.yaml</code></summary>

```yaml
# I'm doing the below to force grafana onto the same node so i don't encounter the same issue over and over
nodeSelector:
  kubernetes.io/hostname=nodeo1
ingress:
  enabled: true
  hostname: grafana.local
metrics:
  enabled: true
serviceMonitor:
  enabled: true
  namespace: monitoring
securityContext:
  # i believed this would have solved it but i keep having to jump on to the node and chown -R 1001:1001
  fsGroup: 0
persistence:
  # This feels like a whitelie as the pod can be scheduled to any node unless i specify a specific node
  enabled: true
```

</details>

Out of interest, why is a deployment used and not a statefulset?
