### ISSUE TITLE
Thanos "To many redirects" using  --web.external-prefix

### ISSUE THREAD

**Issue by rodrigoscferraz** [bitnami/charts#7697]
**Which chart**:
Thanos 6.0.0

**Describe the bug**
Maybe this is not a bug, i think i missconfigure something ... I'm trying to expose bucketweb throught ISTIO but i'm receiving "TO MANY REDIORECTS" when i try to access.
An interesting point is that if i put /metrics at the end it works, but if try to access the root path i receive the redirect message.

**To Reproduce**
I have this config for my bucketweb
```
    bucketweb:
      service:
        http:
          port: 8080
      enabled: true
      extraFlags:
        - --web.external-prefix=tools/thanos-bucketweb
```

And for my virtual service i have this:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: thanos-bucketweb-monitoring-vsvc
  namespace: monitoring
spec:
  hosts:
  - internal.test.io
  gateways:
  - istio-system/private-gateway
  http:
  - match:
    - uri:
        exact: /tools/thanos-bucketweb
    - uri:
        prefix: /tools/thanos-bucketweb/
    rewrite:
      uri: /
    route:
    - destination:
        host: thanos-bucketweb
        port:
          number: 8080
```

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+k3s1", GitCommit:"5a67e8dc473f8945e8e181f6f0b0dbbc387f6fca", GitTreeState:"clean", BuildDate:"2021-06-21T20:52:44Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

```
