### ISSUE TITLE
harbor first time install, 5 pods not coming up, (permission denied errors? starting with redis ...)

### ISSUE THREAD

**Issue by karezza** [bitnami/charts#7727]
**Which chart**:
harbor

**Describe the bug**
5 pods not coming up with a clean first time helm installation

**To Reproduce**

1. add helm repo
2. install harbor via the bitnami repo

**Expected behavior**
harbor to be installed

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
```
[dev: harbor]
[~]
[travis@ansible]$ k logs -f harbor-postgresql-0 
postgresql 03:01:05.29 
postgresql 03:01:05.29 Welcome to the Bitnami postgresql container
postgresql 03:01:05.29 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 03:01:05.30 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 03:01:05.30 
postgresql 03:01:05.31 INFO  ==> ** Starting PostgreSQL setup **
postgresql 03:01:05.34 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 03:01:05.35 INFO  ==> Loading custom pre-init scripts...
postgresql 03:01:05.35 INFO  ==> Initializing PostgreSQL database...
mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied

[dev: harbor]
[~]
[travis@ansible]$ k logs -f harbor-trivy-0 
harbor-adapter-trivy 03:00:58.25 
harbor-adapter-trivy 03:00:58.25 Welcome to the Bitnami harbor-adapter-trivy container
harbor-adapter-trivy 03:00:58.25 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-harbor-adapter-trivy
harbor-adapter-trivy 03:00:58.25 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-harbor-adapter-trivy/issues
harbor-adapter-trivy 03:00:58.25 
harbor-adapter-trivy 03:00:58.26 INFO  ==> ** Starting Harbor Adapter Trivy setup **
mkdir: cannot create directory '/bitnami/harbor-adapter-trivy/.cache/trivy': Permission denied

[dev: harbor]
[~]
[travis@ansible]$ k logs -f harbor-redis-master-0 
1:C 07 Oct 2021 03:00:26.248 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 07 Oct 2021 03:00:26.248 # Redis version=6.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 07 Oct 2021 03:00:26.248 # Configuration loaded
1:M 07 Oct 2021 03:00:26.249 * monotonic clock: POSIX clock_gettime
1:M 07 Oct 2021 03:00:26.249 # Can't open the append-only file: Permission denied

[dev: harbor]
[~]
[travis@ansible]$ k get pvc
NAME                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS    AGE
data-harbor-postgresql-0           Bound    pvc-6cd72bef-f566-4f8a-a003-5037c7724831   8Gi        RWO            longhorn-slow   25m
data-harbor-trivy-0                Bound    pvc-a7ef65ef-bd50-4699-b5a5-8f9199cfe921   5Gi        RWO            longhorn-slow   25m
harbor-chartmuseum                 Bound    pvc-fa582ba3-a366-494f-8d76-e74f037c5bf5   5Gi        RWO            longhorn-slow   25m
harbor-jobservice                  Bound    pvc-4733886c-a708-4c37-a2d8-2a32337792db   1Gi        RWO            longhorn-slow   25m
harbor-registry                    Bound    pvc-3f23d859-baf7-4bf2-95c2-4fa80146e55f   5Gi        RWO            longhorn-slow   25m
redis-data-harbor-redis-master-0   Bound    pvc-16220af6-c5b7-49a6-83d5-16b4b812eb0d   8Gi        RWO            longhorn-slow   25m
```

**Comment by karezza** [comment]
Per your suggestion I have tried the following:
```
$ cat update-install 
#!/bin/bash

NAME=harbor
NS=$NAME
REPO=https://charts.bitnami.com/bitnami
REPO_ALIAS=bitnami
CHART=harbor

# prep
helm repo add $REPO_ALIAS $REPO
helm repo update
touch values.yaml

# if an upgrade
export HARBOR_ADMIN_PASSWORD=$(kubectl get secret --namespace "harbor" harbor-core-envvars -o jsonpath="{.data.HARBOR_ADMIN_PASSWORD}" | base64 --decode)

if [[ -z $HARBOR_ADMIN_PASSWORD ]]; then
  echo "*install*"

  # install
  helm upgrade \
          --install \
          --namespace $NS \
          --create-namespace \
          --set volumePermissions.enabled=true \
          --set persistence.resourcePolicy= \
          --set persistence.enabled=false \
          -f ./values.yaml \
          $NAME $REPO_ALIAS/$CHART
else
  echo "*update*"

  # upgrade
  helm upgrade \
          --install \
          --namespace $NS \
          --create-namespace \
          --set volumePermissions.enabled=true \
          --set persistence.resourcePolicy= \
          --set persistence.enabled=false \
          --set harborAdminPassword=$HARBOR_ADMIN_PASSWORD \
          -f ./values.yaml \
          $NAME $REPO_ALIAS/$CHART
fi
```

same result:
```
$ k get pods
NAME                                    READY   STATUS             RESTARTS      AGE
harbor-chartmuseum-9fd9d56d5-fmmzd      1/1     Running            0             2m16s
harbor-core-6544b59797-grgqv            0/1     Running            1 (59s ago)   2m16s
harbor-jobservice-859bfdb95c-hgm88      0/1     Running            2 (36s ago)   2m16s
harbor-nginx-84686dbff4-pq2xs           1/1     Running            0             2m16s
harbor-notary-server-5b8bb898cf-d4qwd   0/1     Running            1 (36s ago)   2m16s
harbor-notary-signer-9f7455d78-t4zsw    0/1     Running            1 (36s ago)   2m16s
harbor-portal-7bbc498446-8ll9s          1/1     Running            0             2m16s
harbor-postgresql-0                     0/1     CrashLoopBackOff   4 (30s ago)   2m16s
harbor-redis-master-0                   0/1     CrashLoopBackOff   4 (30s ago)   2m16s
harbor-registry-59d48444b7-x7nsw        2/2     Running            0             2m16s
harbor-trivy-0                          1/1     Running            0             2m16s
```

**Comment by lknite** [comment]
I was able to get this working by modifying two statefulsets:

harbor-redis-master
```
      initContainers:
      - command:
        - sh
        - -c
        - |
          mkdir -p "/data"
          chown -R "1001:1001" "/data"
        image: docker.io/bitnami/bitnami-shell:10-debian-10-r206
        imagePullPolicy: Always
        name: volume-permissions
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: redis-data

```

harbor-postgresql
```
      initContainers:
      - command:
        - sh
        - -c
        - |
          mkdir -p "/bitnami/postgresql"
          chown -R "1001:1001" "/bitnami/postgresql"
        image: docker.io/bitnami/bitnami-shell:10-debian-10-r206
        imagePullPolicy: Always
        name: volume-permissions
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bitnami/postgresql
          name: data
```
