### ISSUE TITLE
Init shell scripts don't execute, but 

### ISSUE THREAD

**Issue by hashibuto** [bitnami/charts#7755]
**Which chart**:
postgresql-ha 7.10.1

**Describe the bug**
Shell scripts provided via configmap, through variables/configmap described below do show up in `/docker-entrypoint-initdb.d`, however are not executed.

excerpt from `values.yaml`
```
postgresql-ha:
  postgresql:
    initdbScriptsCM: postgresql-init-script
```

excerpt from configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init-script
  labels:
    {{- include "test.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/docker-entrypoint-initdb.d/*.sh").AsConfig | indent 2 }}
```
View from exec into container:

```
I have no name!@test-postgresql-ha-postgresql-0:/docker-entrypoint-initdb.d$ ls -la
total 12
drwxrwsrwx 3 root 1001 4096 Oct  9 04:56 .
drwxr-xr-x 1 root root 4096 Oct  9 04:56 ..
drwxr-sr-x 2 root 1001 4096 Oct  9 04:56 ..2021_10_09_04_56_06.562180693
lrwxrwxrwx 1 root 1001   31 Oct  9 04:56 ..data -> ..2021_10_09_04_56_06.562180693
lrwxrwxrwx 1 root 1001   17 Oct  9 04:56 init-db.sh -> ..data/init-db.sh

I have no name!@sagani-postgresql-ha-postgresql-0:/docker-entrypoint-initdb.d$ pwd
/docker-entrypoint-initdb.d
```

The shell script:
```
#!/bin/sh

echo "CREATE DATABASE $DB_NAME" | psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER"
```
Above is just an example of a script that will not execute.  Environment variables have been verified from the command shell.

**To Reproduce**

Deploy the chart with a `.sh` init script.  `.sql` scripts DO however run properly when supplied in the exact same fashion.

**Expected behavior**
I would expect the shell script to execute

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s1", GitCommit:"acad8ef8402021d6a78405c0b4fe420982e5ad1e", GitTreeState:"clean", BuildDate:"2021-09-20T17:40:35Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
.sql files really do work fine.  it's not the contents of the shell script that matter in particular, they just aren't being executed.  i've tested with as basic as just creating a database, but the database will not be created.

Thanks!

**Comment by hashibuto** [comment]
@yilmi I've just tested your recommendation above, but am still unable to get the init script to execute.  Here are my `values.yaml`.  I appreciate all the help you've given so far, but this is seeming like a dead end.

```
global:
  pgpool:
    existingSecret: postgres-credentials
  postgresql:
    username: postgres
    existingSecret: postgres-credentials

postgresql-ha:
  postgresql:
    extraEnvVars:
    - name: DB_NAME
      valueFrom:
        configMapKeyRef:
          name: postgresql-config
          key: databaseName
    - name: POSTGRES_USER
      valueFrom:
        configMapKeyRef:
          name: postgresql-config
          key: username
    initdbScriptsCM: postgresql-init-script
```

The configmap (for env variables)
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  labels:
    {{- include "test.labels" . | nindent 4 }}
data:
  databaseName: test
  username: postgres
```

and finally the definition for the init:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init-script
  labels:
    {{- include "test.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/docker-entrypoint-initdb.d/*.sh").AsConfig | indent 2 }}
```

The secrets are populated via kubectl at deployment time.  Again, on each test I have fully deleted and recreated the cluster to ensure that no volumes remain.  I thank you for your help, but something is very wrong here.  If you see anything obvious in my values.yaml, perhaps let me know, but otherwise I think we will close this out pending a final look.

**Comment by yilmi** [comment]
Hi @hashibuto, sorry to hear that. I think there's something wrong with your values, the `postgresql-ha` key doesn't exist in the values file.

Could you try with the following structure:
```
postgresql:
    initdbScriptsCM: postgresql-init-script
```

Once using this key, could you confirm that even after adding logging to the script (like `echo "Creating database..." >> /bitnami/postgresql/custom_script.log`) you have nothing in the `/bitnami/postgresql/custom_script.log` file right?

**Comment by hashibuto** [comment]
@yilmi Finally I've had some success.  I stripped my chart down to the bare minimum.  Here is my values file:
```
global:
  pgpool:
    existingSecret: postgres-credentials
  postgresql:
    username: postgres
    existingSecret: postgres-credentials

postgresql-ha:
  postgresql:
    initdbScriptsCM: postgresql-init-script
```

The `postgresql-ha` is essential though, or the init script does not get picked up at all.  I think the problem could have been the init script itself though I'm unsure of why.  I used this basic script:

```
#!/bin/sh

echo "RUNNING THE INIT SCRIPT"
echo "------------------------"
echo "------------------------"
echo "------------------------"
echo "------------------------"
echo "------------------------"
echo "------------------------"
echo "------------------------"
echo "------------------------"
```

Then in the logs, we can see the following on first init:

```
postgresql-repmgr 19:06:23.91 
postgresql-repmgr 19:06:23.91 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 19:06:23.91 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 19:06:23.91 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 19:06:23.91 
postgresql-repmgr 19:06:23.92 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 19:06:23.95 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 19:06:23.95 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 19:06:23.95 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 19:06:23.98 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 19:06:23.99 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 19:06:23.99 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 19:06:24.07 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 19:06:24.08 INFO  ==> Initializing Repmgr...
postgresql-repmgr 19:06:24.08 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 19:06:24.09 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 19:06:24.09 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql-repmgr 19:06:24.80 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 19:06:24.92 INFO  ==> Changing password of postgres
postgresql-repmgr 19:06:24.93 INFO  ==> Creating replication user repmgr
postgresql-repmgr 19:06:24.96 INFO  ==> Configuring replication parameters
postgresql-repmgr 19:06:24.99 INFO  ==> Configuring fsync
postgresql-repmgr 19:06:25.00 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 19:06:25.00 INFO  ==> Creating repmgr user: repmgr
postgresql-repmgr 19:06:25.03 INFO  ==> Creating repmgr database: repmgr
postgresql-repmgr 19:06:25.29 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql-repmgr 19:06:25.39 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 19:06:25.52 INFO  ==> Registering Primary...
postgresql-repmgr 19:06:25.59 INFO  ==> Loading custom scripts...
postgresql-repmgr 19:06:25.60 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
postgresql-repmgr 19:06:25.60 INFO  ==> Starting PostgreSQL in background...
RUNNING THE INIT SCRIPT
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
postgresql-repmgr 19:06:25.61 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql-repmgr 19:06:25.72 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **

postgresql-repmgr 19:06:25.74 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2021-10-18 19:06:25.768 GMT [269] LOG:  pgaudit extension initialized
2021-10-18 19:06:25.768 GMT [269] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-10-18 19:06:25.768 GMT [269] LOG:  listening on IPv6 address "::", port 5432
2021-10-18 19:06:25.769 GMT [269] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-10-18 19:06:25.772 GMT [269] LOG:  redirecting log output to logging collector process
2021-10-18 19:06:25.772 GMT [269] HINT:  Future log output will appear in directory "/opt/bitnami/postgresql/logs".
2021-10-18 19:06:25.774 GMT [271] LOG:  database system was shut down at 2021-10-18 19:06:25 GMT
2021-10-18 19:06:25.777 GMT [269] LOG:  database system is ready to accept connections
 done
server started
postgresql-repmgr 19:06:25.86 INFO  ==> ** Starting repmgrd **
[2021-10-18 19:06:25] [NOTICE] repmgrd (repmgrd 5.2.1) starting up
INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
[2021-10-18 19:06:25] [NOTICE] starting monitoring of node "test-postgresql-ha-postgresql-0" (ID: 1000)
[2021-10-18 19:06:25] [NOTICE] monitoring cluster primary "test-postgresql-ha-postgresql-0" (ID: 1000)
[2021-10-18 19:06:37] [NOTICE] new standby "test-postgresql-ha-postgresql-1" (ID: 1001) has connected
```

At least this is a valid starting point now.  We know the init script executes and everything after that should fall into place.

Thank you so much for the time you spent helping me through this.  I'm going to close the issue now since we have resolution and we've verified that there is no bug in the chart.
