### ISSUE TITLE
[bitnami/discourse] Unable to start Nginx when running discourse in Minikube 

### ISSUE THREAD

**Issue by kguertin** [bitnami/charts#7783]
**Which chart**:
Discourse 2.7.8

**Describe the bug**
After installing discourse charts I get the following logs: 
```
discourse 16:17:59.89 Welcome to the Bitnami discourse container
discourse 16:17:59.91 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
discourse 16:17:59.93 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
discourse 16:17:59.94 
discourse 16:18:00.03 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse 16:18:00.08 INFO  ==> Trying to connect to the database server
discourse 16:18:00.21 INFO  ==> Creating database user postgres
discourse 16:18:00.37 INFO  ==> Creating database discourse
discourse 16:18:01.10 WARN  ==> The DISCOURSE_REDIS_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow a blank password. This is only recommended for development environments.
discourse 16:18:01.14 INFO  ==> Creating Discourse configuration file
discourse 16:18:01.66 INFO  ==> Restoring persisted Discourse installation
discourse 16:18:02.02 INFO  ==> Trying to connect to the database server
discourse 16:18:02.23 INFO  ==> Running database migrations
discourse 16:19:02.37 INFO  ==> Precompiling assets, this may take some time...
discourse 16:27:03.01 INFO  ==> ** Discourse setup finished! **

discourse 16:27:03.24 INFO  ==> ** Starting Discourse **
Could not start the Nginx engine:
nginx: [alert] Unable to start the Phusion Passenger(R) watchdog: it seems to have been killed with signal SIGABRT during startup (-1: Unknown error)
```

**To Reproduce**
1. Create a values.local.yaml file with the following content:
```
service:
  type: ClusterIP

discourse:
  host: "forum.test.local"
  siteName: "Local developer discourse instance"
  email: "email@test.com"
  username: "admin"
  password: "password"
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false

postgresql:
  enabled: false

externalDatabase:
  host: "postgres-postgresql.default.svc.cluster.local"
  port: 5432
  user: "postgres"
  password: "postgres"
  postgresqlPostgresUser: "postgres"
  postgresqlPostgresPassword: "postgres"
  database: "discourse"
```
2. run `helm install -f values.local.yaml discourse bitnami/discourse` (this assumes you have an existing postgres instance running in minikube).

**Expected behavior**
The discourse service should build.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/arm64"}
```
