### ISSUE TITLE
[bitnami/keycloak] Keycloak will not start if externalDatabase.existingSecret is set and internal postgres is disabled

### ISSUE THREAD

**Issue by mgorniew** [bitnami/charts#7794]
**Which chart**:
keycloak 5.1.2

**Describe the bug**
With following values:
```yaml
keycloak:
  postgresql:
    enabled: false
  externalDatabase:
    existingSecret: iam-keycloak-env
```

Both **env** and **envFrom** for PSQL password are generated in StatefulSet:
```yaml
    - name: KEYCLOAK_DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgresql-password
          name: iam-keycloak
    envFrom:
    - configMapRef:
        name: iam-keycloak-env-vars
    - secretRef:
        name: iam-keycloak-env
```

But **iam-keycloak** doesn't contain **postgresql-password** due to following check:
```gotpl
  {{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecret) }}
  postgresql-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
```

Because of this keycloak pods will never start.

**To Reproduce**

1. Install chart with values from bug description

**Expected behavior**
**KEYCLOAK_DATABASE_PASSWORD** should not be in StatefulSet if **externalDatabase.existingSecret** is set.
