### ISSUE TITLE
[bitnami/keycloak] Better documentation on how to add certificate for ldaps

### ISSUE THREAD

**Issue by StianHaugland1** [bitnami/charts#7796]
To configure ldaps im currently using JAVA_OPTS to add the cert. This works, because when no truststore is configured in the standalone.xml it falls back to javax.net.ssl.trustStore, but id like to configure it for "keycloak" istead, any tips? 

`keytool -import -alias somealias  -keystore keystore.jks -file somecer.cer`
`kubectl create secret generic ldap-keystore --from-file=truststore.jks`

values:
```extraVolumes: |
  - name: ldap-keystore
    secret:
      secretName: ldap-keystore

extraVolumeMounts: |
  - name: ldap-keystore
    mountPath: /bitnami/keycloak/keystore
    readOnly: true

extraEnvVars: |
  - name: JAVA_OPTS
    value: >-
      -Djavax.net.ssl.trustStore=/bitnami/keycloak/keystore/truststore.jks
      -Djavax.net.ssl.trustStorePassword=somepass```

**Comment by lknite** [comment]
Just to be more clear, here is the section from the values.yaml I was inviting you to try out:
```
    ## @param auth.tls.existingSecret Existing secret containing the TLS certificates per Keycloak replica
    ## Create this secret following the steps below:
    ## 1) Generate your trustore and keystore files (more info at https://www.keycloak.org/docs/latest/server_installation/#_setting_up_ssl)
    ## 2) Rename your truststore to `keycloak.truststore.jks`.
    ## 3) Rename your keystores to `keycloak-X.keystore.jks` where X is the ID of each Keycloak replica
    ## 4) Run the command below where SECRET_NAME is the name of the secret you want to create:
    ##       kubectl create secret generic SECRET_NAME --from-file=./keycloak.truststore.jks --from-file=./keycloak-0.keystore.jks --from-file=./keycloak-1.keystore.jks ...
    ##
    existingSecret: ""
```

**Comment by lknite** [comment]
@alvneiayu can you tell me what I can run within the keycloak-0 container to check for the existence of the truststore / keystore which I was attempting to set?

**Comment by lknite** [comment]
It occured to me that I might need to set a password for the truststore/keystore, even though I was using the default of 'changeit'.  I specified the password like so:
```
# required otherwise you get a blank page when visiting the admin console
proxyAddressForwarding: true

# to specify the ad ca public certificate in order to access ldaps
auth:
  tls:
    enabled: true
    existingSecret: keycloak-certs
    truststorePassword: changeit
```

I noticed this change was reflected in the secret 'keycloak' as:
```
Data
====
management-password:     10 bytes
tls-truestore-password:  8 bytes
admin-password:          10 bytes
```

There is a typo, 'tls-truestore-password', which probably should be 'tls-truststore-password'.  This typo also exists in the values.yaml file, perhaps this typo is the cause of this not working?

**Comment by lknite** [comment]
I checked inside the container and I can see the following environment variables being set, which look right:
```
KEYCLOAK_TLS_TRUSTSTORE_FILE=/opt/bitnami/keycloak/certs/keycloak.truststore.jks
KEYCLOAK_ENABLE_TLS=true
KEYCLOAK_TLS_TRUSTSTORE_PASSWORD=changeit
KEYCLOAK_TLS_CREATE_KEYSTORE=false
KEYCLOAK_TLS_KEYSTORE_FILE=/opt/bitnami/keycloak/certs/keycloak.keystore.jks
```

What to check next?

**Comment by lknite** [comment]
This worked after I also set the keystore password, so for ldaps it must use the keystore and not the truststore:
```
auth:
  tls:
    enabled: true
    existingSecret: keycloak-certs
    keystorePassword: changeit
    truststorePassword: changeit
```

**Comment by StianHaugland1** [comment]
I created a secret containing the truststore and keystore, but when i click test connection with ldaps:// in userfederation i get this error:
`[org.keycloak.truststore.SSLSocketFactory] (default task-1) No truststore provider found - using default SSLSocketFactory
14:20:28,875 ERROR [org.keycloak.services] (default task-1) KC-SERVICES0055: Error when connecting to LDAP`

Ive checked the env vars and they are the same as you posted above, except ive pass: 123456

Did i forget to do something @lknite ?

secret:
```
Data
====
keycloak-0.keystore.jks:  1314 bytes
keycloak.truststore.jks:  1314 bytes
```
values:
```
auth:
  tls:
    enabled: true
    existingSecret: keycloak-certs
    keystorePassword: "123456"
    truststorePassword: "123456"
```
