### ISSUE TITLE
The keycloak pod keeps exiting

### ISSUE THREAD

**Issue by krumka** [bitnami/charts#7830]
**Which chart**:
keycloak

**Describe the bug**
The pod containing the keycloak is exiting with exit code 1

**To Reproduce**

Install the chart with following values: 
``` yml
auth:
  adminUser: devops
  adminPassword: blabla
  managementUser: manage
  managementPassword: blabla

service:
  type: ClusterIP
```

**Expected behavior**

the pod not to exit
**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
3.7.1
```
through CI

- Output of `kubectl version`:

Through CI

**Additional context**

Part of the describe command:
```
State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
```
