### ISSUE TITLE
MARIADB: no persistent volumes available for this claim and no storage class is set

### ISSUE THREAD

**Issue by lapillaga** [bitnami/charts#7832]
Hello I'm trying to set up mariadb helm chart version 9.6.2 with ArgoCD. So I'm using this config files
`Chart.yaml`
```
appVersion: "1.0"
dependencies:
- name: mariadb
  version: 9.6.2
  repository: https://charts.bitnami.com/bitnami
```
`values.yaml` in global section
```
namespace: mariadb-gallon
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: "local-storage"
```
`values.yaml` in primary or secondary section
```
primary:
  persistence:
    storageClass: "local-storage"
```
For this example `local-storage` is my StorageClass which is using this declaration file:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```
This config create this objects:
![image](https://user-images.githubusercontent.com/42658241/137576832-ee529829-819e-4132-82fb-52f47a01ae20.png)
First pvc show these logs
![image](https://user-images.githubusercontent.com/42658241/137576850-c8a62eb8-f12f-4ab4-8301-019f4c7a3862.png)
![image](https://user-images.githubusercontent.com/42658241/137577002-d3aa3d13-a8f4-4269-b23f-ea40d0b9ac73.png)
This is expected behavior, but it's not working with other two pvcs. This is the log.
![image](https://user-images.githubusercontent.com/42658241/137576893-cac7651b-15f3-4cf6-8b52-ff7e00028f74.png)
And it's because the declaration manifest is not taking the 'local-storage' config from values
`pvc generated manifest`
![image](https://user-images.githubusercontent.com/42658241/137576973-bf0e3d74-cb38-4f5c-94b1-32dc878cf0df.png)
Any suggestions?
