### ISSUE TITLE
MySQL chart existing volume claim flag missing

### ISSUE THREAD

**Issue by pentago** [bitnami/charts#784]
Just noticed that even though at the end of the README it's said that existing volume claim can be used, I do not see **master.persistence.existingClaim** config existing there in a same way as in MariaDB chart. Is this the issue with chart description or this functionality hasn't been implemented yet?

**Comment by beltran-rubo** [comment]
Hi @pentago 

It seems the container functionality is there but we should add that parameter to the Chart files. We will look into it.

**Comment by pentago** [comment]
Thanks a ton @beltran-rubo !

**Comment by carrodher** [comment]
@pentago Thanks for letting us know!
I just implemented your suggestion (you can see the changes in the above PR).
If you find something weird do not hesitate to let us know.

**Comment by pentago** [comment]
Thanks a ton @carrodher. I'll upgrade later on and get back to you if anything weird occurs.

**Comment by pentago** [comment]
Just tried installing fresh chart and first installation works great, no problems whatsoever.
To test successfulness of the patch I performed ```helm del --purge mysql```  to delete deployment and tried installing it again to check if PVC is picked up. This time, chart installs but causes _CrashLoopBackOff_ with _exit code  1_.

Following is error log:

> mysqld_safe error: log-error set to '/opt/bitnami/mysql/logs/mysqld.log', however file don't exists. Create writable for user 'mysql'.

Same issue occurs even if I do not use existing PVC.

With stable/mariadb chart there's no such error and deployment works and mounts existing data with existing PVC I specify in custom values.yaml

values.yaml:
```
image:
  tag: 8.0.12-debian-9-r25

root:
  password: password

db:
  user: ''
  password: ''
  name: ''

replication:
  enabled: true
  user: replicator
  password: password

master:
  persistence:
    enabled: true
#    existingClaim: mysql-master-storage
#    mountPath: /bitnami
    storageClass: ssd
    accessModes:
    - ReadWriteOnce
    size: 100Gi
  resources:
    requests:
      cpu: 2
      memory: 3Gi
    limits:
      cpu: 2.5
      memory: 4Gi

slave:
  replicas: 2
  persistence:
    enabled: true
    storageClass: ssd
    accessModes:
    - ReadWriteOnce
    size: 100Gi
  resources:
    requests:
      cpu: 2
      memory: 3Gi
    limits:
      cpu: 2.5
      memory: 4Gi

metrics:
  enabled: true
  resources:
    requests:
      cpu: 0.3
      memory: 100Mi
    limits:
      cpu: 0.5
      memory: 300Mi
```

**Comment by carrodher** [comment]
Hi @pentago, thanks for the detailed explanation. We're aware of this issue, it was reported some days ago in the MySQL docker image repository, you can see the issue in the following link: https://github.com/bitnami/bitnami-docker-mysql/issues/47

My teammate @tompizmor is working to fix the issue and he is going to release a new MySQL version as soon as possible.

**Comment by pentago** [comment]
Great.

@carrodher one more thing, I'm using `mountPath: /bitnami` to mount my persistent volume to store my database files. Should I use that path or some other? 

I'm asking because chart uses `/bitnami/mysql/data` as mount point for PV it provisions dynamically.

Additionally, If I'm using my own PV(C) to mount to data dir, should chart obey that and not create and mount it's own PV to data dir?

**Comment by carrodher** [comment]
MySQL image stores the data at the `/bitnami/mysql` path. The chart mounts a PV at this location. The volume is created using dynamic volume provisioning by default but if you want, an existing PVC can be defined without problem, you should be able to use it as usual. For persistence, you should mount a directory at the `/bitnami` path. If the mounted directory is empty, it will be initialized on the first run.
```bash
$ docker run \
    -e ALLOW_EMPTY_PASSWORD=yes \
    -v /path/to/mysql-persistence:/bitnami \
    bitnami/mysql:latest
```
or using Docker Compose:
```yaml
version: '2'

services:
  mysql:
    image: 'bitnami/mysql:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    volumes:
      - /path/to/mysql-persistence:/bitnami
```

In order to have your custom files inside the docker image you can mount them as a volume. If you mount a volume at `/bitnami`, you could copy `my_custom.cnf` at `/path/to/mysql-persistence/mysql/conf/my_custom.cnf` or even edit the `/path/to/mysql-persistence/mysql/conf/my.cnf` file.
