### ISSUE TITLE
[KEYCLOAK] integrate keycloak plugins

### ISSUE THREAD

**Issue by qdupuy** [bitnami/charts#7865]
Hello,

Is it possible to modify your helm charts to integrate keycloak plugins?

Indeed, I will need to integrate some plugins on my keycloak instances

**Comment by Whazor** [comment]
These are the settings I am using to mount a plugin via a config map:
```
      extraVolumeMounts: |
        - name: keycloak-yourplugin-plugin
          mountPath: /opt/jboss/keycloak/standalone/deployments/yourplugin
      extraVolumes: |
        - name: keycloak-yourplugin-plugin
          configMap:
            name: keycloak-yourplugin-plugin
            items:
            - key: keycloak-extension-yourplugin-1.0.jar
              path: keycloak-extension-yourplugin-1.0.jar
```

You could also use a normal volume instead of a config map.

I upload the plugin via:
```bash
kubectl create configmap keycloak-yourplugin-plugin \
  --from-file=keycloak-extension-yourplugin-1.0.jar=target/keycloak-extension-yourplugin-1.0.2-15.0.2.jar --dry-run -o yaml | kubectl apply -f -
```
