### ISSUE TITLE
[bitnami/postgresql] Pods going in Crashloopbackoff

### ISSUE THREAD

**Issue by puneetmathur-87** [bitnami/charts#7871]
Hello Team, 

We are trying to use the bitnami postgresql chart for a simple postgres deployment on our on-prem kubernetes cluster but it seems it fails to initialize with the init container itself. The logs and the values file we use are below:

```yaml
volumePermissions:
  enabled: true
global:
  postgresql:
    postgresqlPassword: "password"
    postgresqlUsername: "postgres"
    postgresqlDatabase: "postgres"
#postgresqlPostgresPassword: "password"
#postgresqlUsername: "postgres"
#postgresqlDatabase: "postgres"
livenessProbe:
  initialDelaySeconds: 600
readinessProbe:
  initialDelaySeconds: 600
pgHbaConfiguration: |-
  host  all  all  0.0.0.0/0   md5
  host  all  all  ::/0  md5
  local all postgres trust
  host  all  all  127.0.0.1/32  md5
  host  all  all  ::1/128  md5
#  local    all             all                                     trust
#  host     all             all        127.0.0.1/32                 trust
#  host     all             all        ::1/128                      trust
tls:
  enabled: true
  autoGenerated: true
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 50Gi
securityContext:
  enabled: true
  fsGroup: 1001
containerSecurityContext:
  enabled: true
  runAsUser: 1001
```

```
**postgresql 14:04:53.37
postgresql 14:04:53.38 Welcome to the Bitnami postgresql container
postgresql 14:04:53.38 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 14:04:53.38 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 14:04:53.38
postgresql 14:04:53.40 INFO  ==> ** Starting PostgreSQL setup **
postgresql 14:04:53.42 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 14:04:53.43 WARN  ==> A CA X.509 certificate was not provided. Client verification will not be performed in TLS connections
postgresql 14:04:53.43 INFO  ==> Loading custom pre-init scripts...
postgresql 14:04:53.44 INFO  ==> Initializing PostgreSQL database...
postgresql 14:04:53.45 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected**
```

When I try the same on our cloud k8s services, it works fine but not on our on-prem.

Please suggest.

**Comment by migruiz4** [comment]
Hi @puneetmathur-87,

After enabling `image.debug`, does your container show the same output as this comment https://github.com/bitnami/charts/issues/7871#issuecomment-949921333?

I assumed that you were facing the same issue, but it could be different. 

Especially this section of the logs aimed us to the `huge_pages` issue as other postgres users are reporting the same problem (e.g. https://github.com/kubernetes/kubernetes/issues/71233):
```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /bitnami/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
Bus error (core dumped)  <--------
child process exited with exit code 135
initdb: removing contents of data directory "/bitnami/postgresql/data"
running bootstrap script ...
```

This comment also gathers other solutions to this problem: https://github.com/kubernetes/kubernetes/issues/71233#issuecomment-447472125

**Comment by unoexperto** [comment]
Hey folks. New to k8s and stumbled upon this issue. As many of you I had Exit Error 128 with an empty log. Turned out problem was caused by following part of stateful set:

```
resources:
  limits:
    cpu: "4"
    memory: 2048Mi
  requests:
    cpu: "1"
    memory: 2048Mi
```

Switching CPU limits to `4000m` and `1000m` correspondingly fixed the issue.
