### ISSUE TITLE
Mongodb chart does not support Replica Sets with  TLS + External Access

### ISSUE THREAD

**Issue by drawsmcgraw** [bitnami/charts#7886]
**Which chart**:
The name (and version) of the affected chart
`mongodb-10.27.2`
app version `4.4.9`

**Describe the bug**
When I attempt to deploy the Helm chart with `architecture: replicaset`,  `tls.enabled: true` and `externalAccess: true`, the first mongo pod never passes the liveness check and the chart fails.

**To Reproduce**

Deploy the Helm chart with the following `values.yml`:
```
architecture: replicaset
replicaCount: 3

externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true

tls:
  enabled: true
  autoGenerated: true

auth:
  enabled: true
  rootUser: root
  rootPassword: "redacted"
  replicaSetKey: "redacted"

rbac:
  create: true
```

Describe the first mongo pod:

```
$ kubectl describe pods mongo-mongodb-0
.
.
Normal   Started                 2m54s                 kubelet                  Started container mongodb
Warning  Unhealthy               43s (x13 over 2m43s)  kubelet                  Readiness probe failed:
```

Fetch logs from the first mongo pod:

```{"t":{"$date":"2021-10-21T12:20:25.731+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"100.96.1.1:57087","connectionId":119,"connectionCount":1}}
{"t":{"$date":"2021-10-21T12:20:25.731+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"100.96.2.1:41672","connectionId":120,"connectionCount":2}}
{"t":{"$date":"2021-10-21T12:20:25.731+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn119","msg":"Connection ended","attr":{"remote":"100.96.1.1:57087","connectionId":119,"connectionCount":1}}
{"t":{"$date":"2021-10-21T12:20:25.731+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn120","msg":"Connection ended","attr":{"remote":"100.96.2.1:41672","connectionId":120,"connectionCount":0}}
{"t":{"$date":"2021-10-21T12:20:27.051+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:48872","connectionId":121,"connectionCount":1}}
{"t":{"$date":"2021-10-21T12:20:27.054+00:00"},"s":"W",  "c":"NETWORK",  "id":23236,   "ctx":"conn121","msg":"Client connecting with server's own TLS certificate"}
{"t":{"$date":"2021-10-21T12:20:27.054+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn121","msg":"client metadata","attr":{"remote":"127.0.0.1:48872","client":"conn121","doc":{"application":{"name":"MongoDB Shell"},"driver":{"name":"MongoDB Internal Client","version":"4.4.9"},"os":{"type":"Linux","name":"PRETTY_NAME=\"Debian GNU/Linux 10 (buster)\"","architecture":"x86_64","version":"Kernel 5.8.0-1038-aws"}}}}
{"t":{"$date":"2021-10-21T12:20:27.057+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn121","msg":"Connection ended","attr":{"remote":"127.0.0.1:48872","connectionId":121,"connectionCount":0}}
{"t":{"$date":"2021-10-21T12:20:27.083+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:48876","connectionId":122,"connectionCount":1}}
{"t":{"$date":"2021-10-21T12:20:27.086+00:00"},"s":"W",  "c":"NETWORK",  "id":23236,   "ctx":"conn122","msg":"Client connecting with server's own TLS certificate"}
{"t":{"$date":"2021-10-21T12:20:27.086+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn122","msg":"client metadata","attr":{"remote":"127.0.0.1:48876","client":"conn122","doc":{"application":{"name":"MongoDB Shell"},"driver":{"name":"MongoDB Internal Client","version":"4.4.9"},"os":{"type":"Linux","name":"PRETTY_NAME=\"Debian GNU/Linux 10 (buster)\"","architecture":"x86_64","version":"Kernel 5.8.0-1038-aws"}}}}
{"t":{"$date":"2021-10-21T12:20:27.088+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn122","msg":"Connection ended","attr":{"remote":"127.0.0.1:48876","connectionId":122,"connectionCount":0}}
{"t":{"$date":"2021-10-21T12:20:30.113+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"100.96.2.16:56668","connectionId":123,"connectionCount":1}}
{"t":{"$date":"2021-10-21T12:20:30.117+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn123","msg":"client metadata","attr":{"remote":"100.96.2.16:56668","client":"conn123","doc":{"application":{"name":"MongoDB Shell"},"driver":{"name":"MongoDB Internal Client","version":"4.4.9"},"os":{"type":"Linux","name":"PRETTY_NAME=\"Debian GNU/Linux 10 (buster)\"","architecture":"x86_64","version":"Kernel 5.8.0-1038-aws"}}}}
{"t":{"$date":"2021-10-21T12:20:30.136+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn123","msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-256","speculative":true,"principalName":"root","authenticationDatabase":"admin","remote":"100.96.2.16:56668","extraInfo":{}}}
{"t":{"$date":"2021-10-21T12:20:30.142+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn123","msg":"Connection ended","attr":{"remote":"100.96.2.16:56668","connectionId":123,"connectionCount":0}}
{"t":{"$date":"2021-10-21T12:20:30.715+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"100.96.1.1:31699","connectionId":124,"connectionCount":1}}
{"t":{"$date":"2021-10-21T12:20:30.715+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn124","msg":"Connection ended","attr":{"remote":"100.96.1.1:31699","connectionId":124,"connectionCount":0}}
{"t":{"$date":"2021-10-21T12:20:30.715+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"100.96.2.1:40521","connectionId":125,"connectionCount":1}}
{"t":{"$date":"2021-10-21T12:20:30.715+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn125","msg":"Connection ended","attr":{"remote":"100.96.2.1:40521","connectionId":125,"connectionCount":0}}
{"t":{"$date":"2021-10-21T12:20:35.212+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"100.96.2.16:56700","connectionId":126,"connectionCount":1}}
{"t":{"$date":"2021-10-21T12:20:35.215+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn126","msg":"client metadata","attr":{"remote":"100.96.2.16:56700","client":"conn126","doc":{"application":{"name":"MongoDB Shell"},"driver":{"name":"MongoDB Internal Client","version":"4.4.9"},"os":{"type":"Linux","name":"PRETTY_NAME=\"Debian GNU/Linux 10 (buster)\"","architecture":"x86_64","version":"Kernel 5.8.0-1038-aws"}}}}
{"t":{"$date":"2021-10-21T12:20:35.235+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn126","msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-256","speculative":true,"principalName":"root","authenticationDatabase":"admin","remote":"100.96.2.16:56700","extraInfo":{}}}
```

**Expected behavior**
I expect all nodes in the replica set to finish creating, and to be able to access the replica set from outside the k8s cluster, secured with TLS.

**Version of Helm and Kubernetes**:
```
$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

Kubernetes version: v1.21.2+vmware.1
```

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+vmware.1", GitCommit:"54e7e68e30dd3f9f7bb4f814c9d112f54f0fb273", GitTreeState:"clean", BuildDate:"2021-06-28T22:12:04Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Ultimately, our desire is not to have Mongo manage a CA, but for us to provide our company's enterprise CA cert, plus a cert/key pair for the replica set nodes. This is how it's implemented with Mongodb on VMs today.

We've attempted to mimic this setup by putting our CA cert (NOTE: just the cert, not the key) in a secret, and putting the cert/key pair (wildcarded, since it's for multiple nodes) in a k8s secret. Then mounting those secrets as files via the Helm chart. Like so:

```
# Configure Mongo to use TLS, and provide the certs
extraEnvVars:
  - name: MONGODB_ADVERTISED_HOSTNAME
    value: '*.tanzu.tacticalprogramming.com'
  - name: MONGODB_EXTRA_FLAGS
    value: --tlsMode=requireTLS --tlsCertificateKeyFile=/opt/mongo-pem/mongo-cert-and-key.pem --tlsCAFile=/opt/mongo-ca/enterprise-ca.crt
  - name: MONGODB_CLIENT_EXTRA_FLAGS
    value: --tls --tlsCertificateKeyFile=/opt/mongo-pem/mongo-cert-and-key.pem --tlsCAFile=/opt/mongo-ca/enterprise-ca.crt

# Mount secrets as files to access the certs
extraVolumeMounts:
  - name: mongo-ca
    mountPath: /opt/mongo-ca
    readOnly: true
  - name: mongo-pem
    mountPath: /opt/mongo-pem
    readOnly: true

extraVolumes:
  - name: mongo-ca
    secret:
      secretName: mongo-ca
  - name: mongo-pem
    secret:
      secretName: mongo-pem
```

We're still testing this setup, though, so we're not even sure if this works or is the right way to do it.

**Comment by migruiz4** [comment]
Hi @drawsmcgraw,

I'm having some issues trying to reproduce the ExternalAccess + TLS behavior, but I think I know what could be the issue. Could you please try deploying with the following value and let me know if the problem still exists?

```yaml
extraEnvVars:
  - name: ELASTICSEARCH_ADVERTISED_HOSTNAME
    value: "$(MY_POD_NAME).{{ include \"mongodb.fullname\" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
```
