### ISSUE TITLE
TLS not being added on deployment for bitnami/consul chart

### ISSUE THREAD

**Issue by razahuss02** [bitnami/charts#7888]
**Which chart**:
bitnami/consul

**Describe the bug**
Chart does not install due to kubectl secret tls being created before hand and `existingSecret` parameter being used in chart. 

**To Reproduce**

1. kubectl create secret tls hostname-tls --key key.pem --cert cert.pem -n consul
2. helm install consul bitnami/consul -f values.yaml -n consul

```
image:
  registry: docker.io
  repository: bitnami/consul
  tag: 1.10.3-debian-10-r0
  pullPolicy: IfNotPresent
datacenterName: dc1
domain: consul
raftMultiplier: "1"
replicaCount: 3
service:
  enabled: true
  ports:
    https: 443
  type: LoadBalancer
ingress:
  enabled: true
  path: /
  hostname: hostname
  tls: true
  existingSecret: hostname-tls
```

**Expected behavior**
TLS certs should be attached to load balancer/hostname. Chart does not install due to secret being created beforehand. Expected behavior is TLS certs to be added to hostname upon deployment. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v3.7.0
```

- Output of `kubectl version`:

```
v1.22.2
```
