### ISSUE TITLE
security.enabled + security.tls.autoGenerated causes Kibana pod failure

### ISSUE THREAD

**Issue by brsolomon-deloitte** [bitnami/charts#7898]
**Which chart**:

elasticsearch chart 17.1.1 (deploying via ArgoCD)

**Describe the bug**

The combination of

- `security.enabled: true`
- `security.elasticPassword: <non-null value>`
- `security.tls.autoGenerated: true`
- `global.kibanaEnabled: true`

Causes the Kibana pod to fail to start while all other pods start successfully.

**To Reproduce**

Config:

```
project: default
source:
  repoURL: 'https://charts.bitnami.com/bitnami'
  targetRevision: 17.1.1
  helm:
    parameters:
      - name: security.elasticPassword
        value: changeme
      - name: security.enabled
        value: 'true'
      - name: coordinating.livenessProbe.initialDelaySeconds
        value: '180'
      - name: data.persistence.size
        value: 32Gi
      - name: global.kibanaEnabled
        value: 'true'
      - name: data.heapSize
        value: 2048m
      - name: security.tls.autoGenerated
        value: 'true'
  chart: elasticsearch
destination:
  server: 'https://kubernetes.default.svc'
  namespace: elasticsearch
syncPolicy:
  syncOptions:
    - CreateNamespace=true
 ```

Logs from Kibana pod:

```
[38;5;6mkibana [38;5;5m16:44:48.91 [0m
[38;5;6mkibana [38;5;5m16:44:48.91 [0m[1mWelcome to the Bitnami kibana container[0m
[38;5;6mkibana [38;5;5m16:44:48.91 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-kibana[0m
[38;5;6mkibana [38;5;5m16:44:48.91 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-kibana/issues[0m
[38;5;6mkibana [38;5;5m16:44:48.91 [0m
[38;5;6mkibana [38;5;5m16:44:48.91 [0m[38;5;2mINFO [0m ==> ** Starting Kibana setup **
[38;5;6mkibana [38;5;5m16:44:48.93 [0m[38;5;2mINFO [0m ==> Configuring/Initializing Kibana...
[38;5;6mkibana [38;5;5m16:44:48.94 [0m[38;5;2mINFO [0m ==> Found mounted configuration directory
[38;5;6mkibana [38;5;5m16:44:48.97 [0m[38;5;2mINFO [0m ==> ** Kibana setup finished! **

[38;5;6mkibana [38;5;5m16:44:48.98 [0m[38;5;2mINFO [0m ==> ** Starting Kibana **
{"type":"log","@timestamp":"2021-10-22T16:44:55+00:00","tags":["info","plugins-service"],"pid":69,"message":"Plugin \"metricsEntities\" is disabled."}
{"type":"log","@timestamp":"2021-10-22T16:44:55+00:00","tags":["warning","config","deprecation"],"pid":69,"message":"Setting [elasticsearch.username] to \"elastic\" is deprecated. You should use the \"kibana_system\" user instead."}
{"type":"log","@timestamp":"2021-10-22T16:44:55+00:00","tags":["warning","config","deprecation"],"pid":69,"message":"plugins.scanDirs is deprecated and is no longer used"}
{"type":"log","@timestamp":"2021-10-22T16:44:55+00:00","tags":["warning","config","deprecation"],"pid":69,"message":"Config key [monitoring.cluster_alerts.email_notifications.email_address] will be required for email notifications to work in 8.0.\""}
{"type":"log","@timestamp":"2021-10-22T16:44:55+00:00","tags":["warning","config","deprecation"],"pid":69,"message":"Setting [monitoring.username] to \"elastic\" is deprecated. You should use the \"kibana_system\" user instead."}
{"type":"log","@timestamp":"2021-10-22T16:44:55+00:00","tags":["warning","config","deprecation"],"pid":69,"message":"\"xpack.reporting.roles\" is deprecated. Granting reporting privilege through a \"reporting_user\" role will not be supported starting in 8.0. Please set \"xpack.reporting.roles.enabled\" to \"false\" and grant reporting privileges to users using Kibana application privileges **Management > Security > Roles**."}
{"type":"log","@timestamp":"2021-10-22T16:44:55+00:00","tags":["info","http","server","NotReady"],"pid":69,"message":"http server running at http://:::5601"}
{"type":"log","@timestamp":"2021-10-22T16:44:55+00:00","tags":["info","plugins-system"],"pid":69,"message":"Setting up [106] plugins: [translations,taskManager,licensing,globalSearch,globalSearchProviders,banners,licenseApiGuard,code,usageCollection,xpackLegacy,telemetryCollectionManager,telemetryCollectionXpack,kibanaUsageCollection,securityOss,share,screenshotMode,telemetry,newsfeed,mapsEms,mapsLegacy,legacyExport,kibanaLegacy,embeddable,uiActionsEnhanced,expressions,charts,esUiShared,bfetch,data,savedObjects,visualizations,visTypeXy,visTypeVislib,visTypeTimelion,features,visTypeTagcloud,visTypeTable,visTypePie,visTypeMetric,visTypeMarkdown,tileMap,regionMap,presentationUtil,timelion,home,searchprofiler,painlessLab,grokdebugger,graph,visTypeVega,management,watcher,licenseManagement,indexPatternManagement,advancedSettings,discover,discoverEnhanced,dashboard,dashboardEnhanced,visualize,visTypeTimeseries,savedObjectsManagement,spaces,security,transform,savedObjectsTagging,lens,reporting,canvas,lists,ingestPipelines,fileUpload,maps,dataVisualizer,encryptedSavedObjects,dataEnhanced,timelines,dashboardMode,cloud,upgradeAssistant,snapshotRestore,fleet,indexManagement,rollup,remoteClusters,crossClusterReplication,indexLifecycleManagement,enterpriseSearch,eventLog,actions,alerting,triggersActionsUi,stackAlerts,ruleRegistry,osquery,ml,cases,securitySolution,observability,uptime,infra,monitoring,logstash,console,apmOss,apm]"}
{"type":"log","@timestamp":"2021-10-22T16:44:55+00:00","tags":["info","plugins","taskManager"],"pid":69,"message":"TaskManager is identified by the Kibana UUID: 170a4bbf-d97f-40ff-9c55-a6fd7e100d8f"}
{"type":"log","@timestamp":"2021-10-22T16:44:55+00:00","tags":["warning","plugins","security","config"],"pid":69,"message":"Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
{"type":"log","@timestamp":"2021-10-22T16:44:55+00:00","tags":["warning","plugins","security","config"],"pid":69,"message":"Session cookies will be transmitted over insecure connections. This is not recommended."}
{"type":"log","@timestamp":"2021-10-22T16:44:55+00:00","tags":["warning","plugins","reporting","config"],"pid":69,"message":"Generating a random key for xpack.reporting.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.reporting.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
{"type":"log","@timestamp":"2021-10-22T16:44:55+00:00","tags":["warning","plugins","reporting","config"],"pid":69,"message":"Chromium sandbox provides an additional layer of protection, but is not supported for Linux Debian 10.10 OS. Automatically setting 'xpack.reporting.capture.browser.chromium.disableSandbox: true'."}
{"type":"log","@timestamp":"2021-10-22T16:44:55+00:00","tags":["warning","plugins","encryptedSavedObjects"],"pid":69,"message":"Saved objects encryption key is not set. This will severely limit Kibana functionality. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
{"type":"log","@timestamp":"2021-10-22T16:44:55+00:00","tags":["warning","plugins","actions","actions"],"pid":69,"message":"APIs are disabled because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
{"type":"log","@timestamp":"2021-10-22T16:44:55+00:00","tags":["warning","plugins","alerting","plugins","alerting"],"pid":69,"message":"APIs are disabled because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
{"type":"log","@timestamp":"2021-10-22T16:44:55+00:00","tags":["info","plugins","ruleRegistry"],"pid":69,"message":"Write is disabled, not installing assets"}
{"type":"log","@timestamp":"2021-10-22T16:44:56+00:00","tags":["info","savedobjects-service"],"pid":69,"message":"Waiting until all Elasticsearch nodes are compatible with Kibana before starting saved objects migrations..."}
{"type":"log","@timestamp":"2021-10-22T16:44:56+00:00","tags":["error","savedobjects-service"],"pid":69,"message":"Unable to retrieve version information from Elasticsearch nodes. socket hang up"}
```

**Expected behavior**

Kibana pod starts successfully.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

argocd: v2.1.3+d855831
  BuildDate: 2021-09-29T21:51:21Z
  GitCommit: d855831540e51d8a90b1006d2eb9f49ab1b088af
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

Maybe related: https://github.com/bitnami/charts/issues/5348

**Comment by tianjindaxue1202** [comment]
Recently, I installed elasticsearch&kibana(using Kibana as a subchart). This problem still exists. The following is my configuration. Is there a problem?
my elasticsearch and kibana version is 8.4.3

```
global:
  elasticsearch:
    service:
      name: elasticsearch
      ports:
        restAPI: 9200
  imagePullSecrets: []
  imageRegistry: ''
  kibanaEnabled: true
  storageClass: local-path
kibana:
  elasticsearch:
    hosts:
      - '{{ include "elasticsearch.service.name" . }}'
    port: '{{ include "elasticsearch.service.ports.restAPI" . }}'
    security:
      auth:
        createSystemUser: true
        elasticsearchPasswordSecret: elastic
        enable: true
        kibanaPassword: kibana
      tls:
        enable: true
        existingSecret: elkt-elasticsearch-coordinating-crt
        usePemCerts: true
security:
  elasticPassword: elastic
  enabled: true
  existingSecret: ''
  fipsMode: false
  tls:
    autoGenerated: true
    coordinating:
      existingSecret: ''
    data:
      existingSecret: ''
    ingest:
      existingSecret: ''
    keyPassword: ''
    keystoreFilename: elasticsearch.keystore.jks
    keystorePassword: ''
    master:
      existingSecret: ''
    passwordsSecret: ''
    restEncryption: true
    secretKey: ''
    secretKeystoreKey: ''
    secretTruststoreKey: ''
    truststoreFilename: elasticsearch.truststore.jks
    truststorePassword: ''
    usePemCerts: true
    verificationMode: full
```

after installed, the kinban.yaml is as following

```
server.host: "::"
server.port: 5601
elasticsearch.hosts: ['http://elasticsearch-coordinating-only:9200']  # < WRONG, should be https
server.rewriteBasePath: false
```
