### ISSUE TITLE
[postgresql] Huge pages in initdb

### ISSUE THREAD

**Issue by pbecotte** [bitnami/charts#7901]
My postgres DB couldn't start up, turned out I was hitting this issue. 

https://github.com/docker-library/postgres/issues/451#issuecomment-871109581

I tried setting

```
postgresqlConfiguration:
    huge_pages: "off"
```

The solution in that issue suggested modifying the file `postgresql.conf.sample`. I created a configmap

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-sample-config
data:
  postgresql.conf.sample: |-
    huge_pages = off
```

added these values-

```
extraVolumeMounts:
  - name: pg-sample-config
    mountPath: /opt/bitnami/postgresql/share/postgresql.conf.sample
    subPath: postgresql.conf.sample
extraVolumes:
  - configMap:
      name: pg-sample-config
    name:  pg-sample-config
```

Thing is, I don't see any mentions of `postgresql.conf.sample` in any of the docs, so don't understand why that file matters, but this did get the DB started.

**Comment by rafariossaa** [comment]
Hi @pbecotte ,
  Did you have the change to take a look to what @migruiz4 indicated ?

**Comment by pbecotte** [comment]
I replied in the other thread, but the short version is
setting the value in `postgresql.conf` does NOT solve the problem. It needs to be set in `postgresql.conf.sample` for some reason. 

You can feel free to close one ticket or the other- but unless the issue can be fixed in the upstream container, a way to add this setting to the sample file should be provided.

**Comment by migruiz4** [comment]
Hi,

I would like to share here my findings to clarify what could be causing the issue.

- The error is caused by the Postgresql setting `huge_pages`, which defaults to 'try'.
- The error is triggered during the execution of the command `initdb` ([code](https://github.com/bitnami/bitnami-docker-postgresql/blob/ac66d34257fdb3f09ed2472dba929fcf652d85ec/14/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L803-L832)).
- The Postgresql documentation is not clear about it, but `initdb` apparently uses `postgresql.conf.sample` and not `postgresq.conf`.

As a failed workaround, I tried to modify `postgresql.conf.sample` using an init script, but failed because of the file being owned by `root:postgres`.

So the workaround at the moment would be to mount `postgresql.conf.sample` with `huge_pages=off` as in the description of this issue.

In addition, I would suggest having a look at the other alternatives proposed here https://github.com/kubernetes/kubernetes/issues/71233#issuecomment-447472125

Unless other alternatives are proposed, to solve this issue without workarounds we would need to modify the PostgreSQL image changing the ownership of `postgresql.conf.sample` and adding an env variable that allowed users to easily set `huge_pages=off`.

**Comment by pkExec** [comment]
@pbecotte 
After following your workaround, I get 
`ERROR ==> include_dir line is not present in /opt/bitnami/postgresql/conf/postgresql.conf. This may be due to a changes in a new version of PostgreSQL.`
Any ideas on what I'm doing wrong?

**Comment by rafariossaa** [comment]
@pkExec thank you very much for providing a workaround example.
 
@pbecotte , Could you try what @pkExec indicated ?

**Comment by bewing** [comment]
The all-in-one values to resolve this (without adding a ConfigMap yourself):

```yaml
primary:
  configuration: |-
    huge_pages = 'off'
  extraVolumeMounts:
    - name: pg-sample-config
      mountPath: /opt/bitnami/postgresql/share/postgresql.conf.sample
      subPath: postgresql.conf.sample
  extraVolumes:
    - configMap:
        name: pg-sample-config
      name:  pg-sample-config
extraDeploy:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: pg-sample-config
    data:
      postgresql.conf.sample: |-
        huge_pages = off
```

This will have helm create/manage the lifecycle of the pg-sample-config ConfigMap, and disable hugepages in the init and main containers for a primary-only deployment.

**Comment by Langhalsdino** [comment]
I just want to add, that when using APPLICATION VERSION `15.1.0` and CHART VERSION `12.1.5` the values need to be adjusted like this, to solve the issue:

```
primary:
  extendedConfiguration: |-
    huge_pages = off
```

Otherwise the suggested solution will result in:
```
postgresql 13:36:12.51 INFO  ==> ** Starting PostgreSQL **
2022-12-16 13:36:12.524 GMT [1] LOG:  syntax error in file "/opt/bitnami/postgresql/conf/postgresql.conf" line 1, near token "="
2022-12-16 13:36:12.524 GMT [1] FATAL:  configuration file "/opt/bitnami/postgresql/conf/postgresql.conf" contains errors
```

Thank you @bewing to point me in a very helpful direction :)

**Comment by ogbennymic** [comment]
It's changed again. now:

`primary:
  extendedConfiguration: |-
    huge_pages = off`

**Comment by David-Angel** [comment]
I've submitted this as a PostgreSQL defect.
Looks like they may find a solution.  👍 
https://www.postgresql.org/message-id/17757-dbdfc1f1c954a6db%40postgresql.org

**Comment by herry-heni** [comment]
Thank you @pavelanni . You save my day since your config is working for me.

**Comment by focote** [comment]
As of postgres 16: There is a way to set huge_pages off for initdb: [See post](https://www.crunchydata.com/blog/huge-pages-and-postgres-in-containers)

```
primary:
  extendedConfiguration: |-
    huge_pages = off
  initdb:
    args: "--set huge_pages=off"

```
