### ISSUE TITLE
[bitnami/mongodb] Did not find replica set configuration document in local.system.replset

### ISSUE THREAD

**Issue by suppix** [bitnami/charts#7903]
Hello. 

I have a strange issue, for the first time everything was ok, then I need to redeploy from scratch mongodb helm chart. 
And now even the master don't want to start and initialize Replicaset. 

I have deleted everything: namespace with all STS, PVC, and so on. 
I have checked that none volumes left at the AWS. 
But still , mongodb-0 can't initialize Replicaset.

my values.yaml
```
        architecture: replicaset
        replicaCount: 3
        persistence:
          enabled: true
          size: 50Gi
        arbiter:
          enabled: false
        auth:
          enabled: true
          rootUser: ras-admin
          existingSecret: ras-mongodb-credentials
        tls:
          enabled: true
          autoGenerated: true
        metrics:
          enabled: false
```

helm chart version: 10.28.3
kubernetes: 1.21

Here is the log files:
https://www.dropbox.com/s/6fdgt1pgtuukguv/mongodb.log.txt?dl=0
