### ISSUE TITLE
Connect MongoDB with MongDB Compass

### ISSUE THREAD

**Issue by ognif** [bitnami/charts#7906]
**Which chart**:
bitnami/mongodb

**Describe the bug**
It is not possible to connect the installed mongodb from internal network with MongoDB Compass. The expected adress:
mongodb-srv-0.mongodb-svc.mongoiut.svc.cluster.local
is not reachable. (getaddrinfo ENOTFOUND)
Inside the Cluster MongoExpress can succesfful connect to MongoDB

mongodb.my-cluster.ad.local /admin (Ingress rule) works well.

**To Reproduce**
Installed with 

```yaml
ingress:
  host: mongodb.my-cluster.ad.local 

mongoexpress:
  enabled: true
  mongo_express_deployment_name: mongo-express
  mongo_express_label_name: mongo-express
  mongo_express_image: mongo-express:latest
  mongoexpress_replicas: 1
  mongoexpress_container_port: 8082
  mongoexpress_service_port: 8082
  mongoexpress_target_port: 8082
  nodeport: 30000
  protocol: TCP

mongodb:
  enabled: true
  fullnameOverride: mongodb-srv
  service:
    nameOverride: mongodb-svc
    port: 27017
  auth:
    rootUser: root
    rootPassword: example
    replicaSetKey: key1234567890
  architecture: replicaset
  useStatefulSet: true
  arbiter:
    enabled: false 
  replicaCount: 1   
  persistence:
    enabled: true
    storageClass: longhorn 
    mountPath: /opt/mongodb/data
    size: 10Gi    
  #externalAccess:
  #  enabled: true
  #  service:
  #    type: LoadBalancer    
  #    port: 27017      
  # autoDiscovery: 
  #    enabled: true
  #serviceAccount:
  #  create: true
  #rbac:
  #  create: true      
```
I tried with LoadBalancer and without. No access to the MongoDB. Iam totally confused because MongoExpress can successful connect to MongoDB but MongoDB Compass not. So there have to be an issue with external access. Internal seems to work ok.

With just the lines:
```yaml
  externalAccess:
    enabled: true
    service:
      type: LoadBalancer    
      port: 27017      
```
enabled, I get an message from Helm about Validation error and LoadBalancerIPs. But I do nto set LoadBalancerIP
If I enable the complete external access node, the pod will not get initialized. 

**Expected behavior**
A successfull connection with MongoDB Compass in my internal network. 

**Version of Helm and Kubernetes**:
Helm: v3.6.2
Kubernetes: 1.19
