### ISSUE TITLE
ODOO_DATABASE_PASSWORD environment variable is empty or not set

### ISSUE THREAD

**Issue by outbounder** [bitnami/charts#7910]
**Which chart**:

bitnami/odoo

**Describe the bug**

Installing latest helm chart with a copy of helm chart values.yaml fails with error

```
odoo 09:58:13.90 INFO ==> Validating settings in POSTGRESQL_CLIENT_* env vars
odoo 09:58:13.94 WARN ==> The WITHOUT_DEMO environment variable has been deprecated in favor of ODOO_LOAD_DEMO_DATA=yes. Support for it may be removed in a future release.
odoo 09:58:13.94 ERROR ==> The ODOO_DATABASE_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow a blank password. This is only recommended for development environment
```

**To Reproduce**

1. Download a copy of https://github.com/bitnami/charts/blob/master/bitnami/odoo/values.yaml
2. run `helm install odoo -f values.yaml bitnami/odoo`
3. see that odoo pod fails with error `The ODOO_DATABASE_PASSWORD environment variable is empty or not set.`

**Expected behavior**

The helm chart should complete and odoo pod should be running

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

* Without `values.yaml` the odoo pod fails to connect to postgres server with the following logs:

  ```
  postgre INFO Trying to connect to PostgreSQL server
  postgre INFO Found PostgreSQL server listening at odoo-postgresql:5432
  postgre ERROR [canConnect] Connection with 'postgres' user is unsuccessful
  postgre ERROR [canConnect] Connection with 'postgres' user is unsuccessful
  ....
  Error executing 'postInstallation': Cannot connect to PostgreSQL server:
  psql: FATAL: password authentication failed for user "postgres"
  ```

**Comment by outbounder** [comment]
Hey @Mauraza , sry for the delay 😊 Here is what I tried:

```
annotations:
  category: CRM
apiVersion: v2
appVersion: 14.0.20210310
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.x.x
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 1.x.x
description: A suite of web based open source business apps.
home: https://github.com/bitnami/charts/tree/master/bitnami/odoo
icon: https://bitnami.com/assets/stacks/odoo/img/odoo-stack-220x234.png
keywords:
- odoo
- crm
- www
- http
- web
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: odoo
sources:
- https://github.com/bitnami/bitnami-docker-odoo
- https://www.odoo.com/
version: 18.2.3
```

----

I'm closing this issue as I guess it is something in my workstation/approach broken. When I try the newer version will re-open the issue if it doesn't work as expected.
