### ISSUE TITLE
[chart/elasticsearch,kibana] tls autoGenerated not playing nicely

### ISSUE THREAD

**Issue by jack1902** [bitnami/charts#7928]
**Which chart**:
Elasticsearch (with kibana as a subchart) Version 17.1.0

**Describe the bug**
When using the elasticsearch chart, I am enabling authentication and tls (using self-signed certs via `autoGenerated`) but using the following options results in the an error message:

Error:
```
kibana: tls.enabled
    In order to enable HTTPS for Kibana, you also need to provide an existing secret
    containing the TLS certificates (--set tls.existingSecret="my-secret") or enable
    auto-generated certificates (--set elasticsearch.security.auth.existingSecret="true").
```

**To Reproduce**
Create a custom `myvalues.yaml` file from the below:

```yaml
global:
  kibanaEnabled: true

security:
  enabled: true
  elasticPassword: "<PASSWORD>"
  tls:
    # AutoGenerate TLS certs for elastic
    autoGenerated: true

kibana:
  elasticsearch:
    security:
      auth:
        enabled: true
        kibanaUsername: "<USERNAME>"
        kibanaPassword: "<PASSWORD>"
      tls:
        # Instruct kibana to connect to elastic over https
        enabled: true
        # This appears to remove the error but not what i want
        # verificationMode: "none"
  tls:
    enabled: true
    # AutoGenerate TLS certs for kibana
    autoGenerated: true
```

Run `helm upgrade -i elasticsearch elasticsearch -f myvalues.yaml` and observe the error

**Expected behavior**

I was expecting things to "just work" without much issues but the error keeps popping up. Prefixing the error values with `kibana.` as the warning is coming from the subchart of kibana and not elastic.

I also was wondering if there would be an easier way to pass the password once to the whole chart without having to manually pass the same value in twice but that isn't a blocker

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

Appears to be related to https://github.com/bitnami/charts/issues/7898 but i didn't want to hijack someone else's issue

**Comment by carrodher** [comment]
It can be different alternatives and maybe there is a way to simplify the current logic to work with secrets when using the chart and subcharts. Do you have something in mind? PRs are more than welcome, we will be happy to review any contribution regarding this topic.

**Comment by jack1902** [comment]
Another issue i just ran into, a bad combination of values (apologies if this is in the docs)

Both values must be the same, so either `true` or `false` but cannot be a mix otherwise kibana will fail (potentially a reason behind https://github.com/bitnami/charts/issues/7898 if you are still facing the same issue raised)

```yaml
security:
  tls:
    restEncryption: true
kibana:
  elasticsearch:
    security:
      tls:
        enabled: true
```
