### ISSUE TITLE
[bitnami/oauth2-proxy] support array hosts for ingress kind

### ISSUE THREAD

**Issue by arslanbekov** [bitnami/charts#7939]
**Which chart**:
[bitnami/oauth2-proxy]

**Is your feature request related to a problem? Please describe.**
For installation oauth2-proxy, you need to specify a large number of hosts, you need to go through them in a loop. In the case of using a single host, the whole point of using an oauth2-proxy disappears.

**Describe the solution you'd like**
Need to be able to specify an array of hosts here: https://github.com/bitnami/charts/blob/master/bitnami/oauth2-proxy/values.yaml#L121

Ultimately, you need to get something like this ingress format at the output:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
spec:
  rules:
    - host: admin.example.com
      http:
        paths:
          - backend:
              service:
                name: oauth2-proxy
                port:
                  number: 80
            pathType: Prefix
            path: /oauth2
    - host: private.example.com
      http:
        paths:
          - backend:
              service:
                name: oauth2-proxy
                port:
                  number: 80
            pathType: Prefix
            path: /oauth2
  tls:
    - hosts:
        - admin.example.com
        - private.example.com
      secretName: my-super-secret-name
```
