### ISSUE TITLE
[bitnami/keycloak] Helm-Chart value proxyAddressForwarding does not work as expected

### ISSUE THREAD

**Issue by sebschlue** [bitnami/charts#7941]
Setup is a typical Kubernetes setup with nginx as Ingress Controller and CertManager to manage SSL certificates via Let's Encrypt.

There is the usual k8s service and ingress objects to make Keycloak available via https while the backend connection (from nginx to keycloak) is done via http. All this is configured automatically by the Helm chart and I did not make any modifications there.

Problem is that I would like to be able to run Keycloak with setting KEYCLOAK_SSL_REQUIRED = external.

I believe this is where the Helm Chart value proxyAddressForwarding becomes important. I have set this to true.

I also verified that nginx ingress controller behaves in a way that should be compatible with Keycloak, i.e. it sets the correct http headers like

```
X-Forwarded-Port: 443
X-Forwarded-Proto: https

X-Real-Ip: XXX.XXX.XXX.XXX
X-Forwarded-For: XXX.XXX.XXX.XXX

X-Scheme: https
```

As far as I can see, this matches the requirements listed in https://www.keycloak.org/docs/latest/server_installation/index.html#_setting-up-a-load-balancer-or-proxy

But Keycloak is not satisfied and prints the error message

```
WARN 1 — [nio-8080-exec-1] o.k.adapters.RequestAuthenticator : SSL is required to authenticate. Remote address XXX.XXX.XXX.XXX is secure: false, SSL required for: EXTERNAL .
```

I don't know if anything else needs to be configured in addition to Helm Chart value proxyAddressForwarding to make this work as expected but as I did not find anything, I try to create this bug ticket.

**Comment by jack1902** [comment]
@sebschlue ensure you also set the following additional values:

```yaml
proxyAddressForwarding: true

# below ensures that keycloak frontend and backend requests work for the external / internal requests
extraEnvVars:
  - name: KEYCLOAK_EXTRA_ARGS
    value: "-Dkeycloak.frontendUrl=https://YOUR_URL/auth"
```

nginx-ingress was one of the other issues i originally ran into as the `x-forwarded-for` headers are set by a separate LB which forwards to nginx (which by default drops them and sets them from the request which is undesirable if you have LB -> nginx-ingress -> svc)
