### ISSUE TITLE
[Bitnami/Kube-prometheus] ServiceMonitor Controle Plane Component  Error Endpoint Metrics

### ISSUE THREAD

**Issue by fayssaldarif** [bitnami/charts#7963]
**Which chart**:
The name (and kube-prometheus-6.1.8 ) of the affected chart
APP VERSION 0.50.0

**Describe the bug**
All metrics endpoints for KubeController/KubePorxy/KueScheduler DOWN.
for kubecontroler I am using the below config
```
kubeControllerManager:
  enabled: true
  endpoints: []
  namespace: kube-system
  service:
    enabled: true
    port: 10257
    selector:
      component: kube-controller-manager
      tier: control-plane
    targetPort: 10257
```
But if I change the port from `10257` to `10252`, I can see the metrics endpoint UP. I have the same problem for kube proxy and kube scheduler.
Ports `10251` and `10252` have been replaced in veresion 1.17, 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
kubectl version --short && helm version --short
Client Version: v1.21.1
Server Version: v1.21.0
v3.6.2+gee407bd
```

values yaml file used
```
alertmanager:
  additionalPeers: []
  affinity: {}
  config:
    global:
      resolve_timeout: 5m
    receivers:
    - email_configs:
      - auth_identity: rxxxxx
        auth_password: rxxxxx
        auth_username: rxxxxx
        from: rxxxxx
        smarthost: rxxxxx
        to: rxxxxx
      name: rxxxxx
    route:
      group_by:
      - job
      group_interval: 5m
      group_wait: 30s
      receiver: rxxxxx
      repeat_interval: 12h
      routes:
      - match:
          alertname: Watchdog
        receiver: "null"
  configMaps: []
  configNamespaceSelector: {}
  configSelector: {}
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    enabled: true
    readOnlyRootFilesystem: false
    runAsNonRoot: true
  containers: []
  enabled: true
  externalConfig: false
  externalUrl: ""
  image:
    pullSecrets: []
    registry: docker.io
    repository: bitnami/alertmanager
    tag: 0.23.0-debian-10-r0
  ingress:
    annotations:
      cert-manager.io/acme-challenge-type: http01
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    apiVersion: ""
    certManager: false
    enabled: false
    extraHosts: []
    extraPaths: []
    extraTls: []
    hostname: xxxxxxxxxxxxxxxxx
    path: /
    pathType: ImplementationSpecific
    secrets: []
    tls: false
  listenLocal: false
  livenessProbe:
    enabled: true
    failureThreshold: 120
    initialDelaySeconds: 0
    path: /-/healthy
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3
  logFormat: logfmt
  logLevel: info
  nodeAffinityPreset:
    key: ""
    type: ""
    values: []
  nodeSelector:
     beta.kubernetes.io/arch: amd64
     beta.kubernetes.io/os: linux
     kubernetes.io/arch: amd64
     kubernetes.io/hostname: xxxxxxxxxxxxxxxxx
  paused: false
  persistence:
    accessModes:
    - ReadWriteOnce
    enabled: false
    size: 8Gi
    storageClass: ""
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  podDisruptionBudget:
    enabled: false
    maxUnavailable: ""
    minAvailable: 1
  podMetadata:
    annotations: {}
    labels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1002
    runAsUser: 1002
  portName: web
  priorityClassName: ""
  readinessProbe:
    enabled: true
    failureThreshold: 120
    initialDelaySeconds: 0
    path: /-/ready
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3
  replicaCount: 1
  resources: {}
  retention: 120h
  routePrefix: /
  secrets: []
  service:
    annotations: {}
    clusterIP: ""
    externalTrafficPolicy: Cluster
    healthCheckNodePort: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    nodePort: ""
    port: 9093
    stickySessions: ""
    type: ClusterIP
  serviceAccount:
    create: true
    name: "alertmanager-sa"
  serviceMonitor:
    enabled: true
    interval: ""
    metricRelabelings: []
    relabelings: []
  storageSpec: {}
  tolerations: []
  volumeMounts: []
  volumes: []
coreDns:
  enabled: true
  namespace: kube-system
  service:
    enabled: true
    port: 9153
    selector:
      k8s-app: kube-dns
    targetPort: 9153
  serviceMonitor:
    interval: ""
    metricRelabelings: []
    relabelings: []
exporters:
  kube-state-metrics:
    enabled: true
  node-exporter:
    enabled: true
fullnameOverride: ""
global:
  imagePullSecrets: []
  imageRegistry: ""
  labels: {}
  storageClass: ""
kube-state-metrics:
  serviceMonitor:
    enabled: true
kubeApiServer:
  enabled: true
  serviceMonitor:
    interval: ""
    metricRelabelings: []
    relabelings: []
kubeControllerManager:
  enabled: true
  endpoints: []
  namespace: kube-system
  service:
    enabled: true
    port: 10257
    selector:
      component: kube-controller-manager
      tier: control-plane
    targetPort: 10257
  serviceMonitor:
    https: false
    insecureSkipVerify: ""
    interval: ""
    metricRelabelings: []
    relabelings: []
    serverName: ""
kubeProxy:
  enabled: true
  endpoints: []
  namespace: kube-system
  service:
    enabled: true
    port: 10256
    selector:
      k8s-app: kube-proxy
    targetPort: 10256
  serviceMonitor:
    https: false
    interval: ""
    metricRelabelings: []
    relabelings: []
kubeScheduler:
  enabled: true
  endpoints: []
  namespace: kube-system
  service:
    enabled: true
    port: 10259
    selector:
      component: kube-scheduler
      tier: control-plane
    targetPort: 10259
  serviceMonitor:
    https: false
    insecureSkipVerify: ""
    interval: ""
    metricRelabelings: []
    relabelings: []
    serverName: ""

kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    cAdvisorMetricRelabelings: []
    cAdvisorRelabelings: []
    https: true
    interval: ""
    metricRelabelings: []
    relabelings: []
nameOverride: ""

node-exporter:
  extraArgs:
    collector.filesystem.ignored-fs-types: ^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
    collector.filesystem.ignored-mount-points: ^/(dev|proc|sys|var/lib/docker/.+)($|/)
  service:
    labels:
      jobLabel: node-exporter
    port: 9200
    targetPort: 9200
  serviceMonitor:
    enabled: true
    jobLabel: jobLabel

operator:
  affinity: {}
  configReloaderResources: {}
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    enabled: true
    readOnlyRootFilesystem: false
    runAsNonRoot: true
  enabled: true
  hostAliases: []
  image:
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/prometheus-operator
    tag: 0.50.0-debian-10-r8
  kubeletService:
    enabled: true
    namespace: kube-system
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 120
    path: /metrics
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  logFormat: logfmt
  logLevel: info
  nodeAffinityPreset:
    key: ""
    type: ""
    values: []
  nodeSelector: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  podSecurityContext:
    enabled: true
    fsGroup: 1002
    runAsUser: 1002
  priorityClassName: ""
  prometheusConfigReloader:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      enabled: true
      readOnlyRootFilesystem: false
      runAsNonRoot: true
    image: {}
    livenessProbe:
      enabled: true
      failureThreshold: 6
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      enabled: true
      failureThreshold: 6
      initialDelaySeconds: 15
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 5
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 30
    path: /metrics
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  resources: {}
  schedulerName: ""
  service:
    annotations: {}
    clusterIP: ""
    externalTrafficPolicy: Cluster
    healthCheckNodePort: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    nodePort: ""
    port: 8080
    type: ClusterIP
  serviceAccount:
    create: true
    name: ""
  serviceMonitor:
    enabled: true
    interval: ""
    metricRelabelings: []
    relabelings: []
  tolerations: []
prometheus:
  additionalAlertRelabelConfigsExternal:
    enabled: false
    key: ""
    name: ""
  additionalPrometheusRules: {}


  additionalScrapeConfigs:
    enabled: false
    external:
      key: ""
      name: ""
    internal:
      jobList: []
    type: external
  additionalScrapeConfigsExternal:
    enabled: false
    key: ""
    name: ""
  affinity: {}
  alertingEndpoints: []
  configMaps: []
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    enabled: true
    readOnlyRootFilesystem: false
    runAsNonRoot: true
  containers: []
  disableCompaction: false
  enableAdminAPI: false
  enabled: true
  evaluationInterval: ""
  externalLabels: {}
  externalUrl: ""
  image:
    pullSecrets: []
    registry: docker.io
    repository: bitnami/prometheus
    tag: 2.29.1-debian-10-r13
  ingress:
    annotations:
      cert-manager.io/acme-challenge-type: http01
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    apiVersion: ""
    certManager: false
    enabled: true
    extraHosts: []
    extraPaths: []
    extraTls: []
    hostname: xxxxxxxxxxxxx
    path: /
    pathType: ImplementationSpecific
    secrets: []
    tls: false
  listenLocal: false
  livenessProbe:
    enabled: true
    failureThreshold: 10
    initialDelaySeconds: 0
    path: /-/healthy
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 3
  logFormat: logfmt
  logLevel: info
  matchLabels: {}
  nodeAffinityPreset:
    key: ""
    type: ""
    values: []
  nodeSelector:
     beta.kubernetes.io/arch: amd64
     beta.kubernetes.io/os: linux
     kubernetes.io/arch: amd64
     kubernetes.io/hostname: xxxxxxxxxxxxxxxxx
  paused: false
  persistence:
    accessModes:
    - ReadWriteOnce
    enabled: false
    size: 8Gi
    storageClass: ""
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  podDisruptionBudget:
    enabled: false
    maxUnavailable: ""
    minAvailable: 1
  podMetadata:
    annotations: {}
    labels: {}
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1002
    runAsUser: 1002
  portName: web
  priorityClassName: ""
  probeNamespaceSelector: {}
  probeSelector: {}
  prometheusExternalLabelName: ""
  prometheusExternalLabelNameClear: false
  querySpec: {}
  readinessProbe:
    enabled: true
    failureThreshold: 10
    initialDelaySeconds: 0
    path: /-/ready
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 3
  remoteRead: []
  remoteWrite: []
  replicaCount: 1
  replicaExternalLabelName: ""
  replicaExternalLabelNameClear: false
  resources: {}
  retention: 10d
  retentionSize: ""
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector: {}
  scrapeInterval: ""
  secrets: []
  service:
    annotations: {}
    clusterIP: ""
    externalTrafficPolicy: Cluster
    healthCheckNodePort: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    nodePort: ""
    port: 9090
    stickySessions: ""
    type: ClusterIP
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  serviceMonitor:
    enabled: true
    interval: ""
    metricRelabelings: []
    relabelings: []
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  storageSpec: {}
  thanos:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      enabled: true
      readOnlyRootFilesystem: false
      runAsNonRoot: true
    create: false
    extraArgs: []
    image:
      pullPolicy: IfNotPresent
      pullSecrets: []
      registry: docker.io
      repository: bitnami/thanos
      tag: 0.22.0-scratch-r2
    ingress:
      annotations: {}
      certManager: false
      enabled: false
      hosts:
      - name: thanos.prometheus.local
        path: /
      tls: {}
    livenessProbe:
      enabled: true
      failureThreshold: 120
      initialDelaySeconds: 0
      path: /-/healthy
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    objectStorageConfig: {}
    prometheusUrl: ""
    readinessProbe:
      enabled: true
      failureThreshold: 120
      initialDelaySeconds: 0
      path: /-/ready
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      limits: {}
      requests: {}
    service:
      annotations: {}
      clusterIP: None
      extraPorts: []
      loadBalancerIP: ""
      loadBalancerSourceRanges: []
      nodePort: ""
      port: 10901
      type: ClusterIP
  tolerations: []
  volumeMounts: []
  volumes: []
  walCompression: false
rbac:
  apiVersion: v1beta1
  create: true
  pspEnabled: true

```
