### ISSUE TITLE
[kube-prometheus] readinessProbe.httpGet: Forbidden: may not specify more than 1 handler type

### ISSUE THREAD

**Issue by rodrigoscferraz** [bitnami/charts#7975]
**Which chart**:
kube-prometheus - 6.1.11

**Describe the bug**
After i set "true" to prometheus.listenLocal i'm receiving the following error:

`create Pod prometheus-kube-prometheus-prometheus-0 in StatefulSet prometheus-kube-prometheus-prometheus failed error: Pod "prometheus-kube-prometheus-prometheus-0" is invalid: spec.containers[0].readinessProbe.httpGet: Forbidden: may not specify more than 1 handler type `

Maybe i'm doing something wrong?

My values.yaml:
```

    kube-state-metrics:
      serviceMonitor:
        honorLabels: true

    prometheus:
      enabled: true
      listenLocal: true
      replicaCount: 2
      retention: 10d
      disableCompaction: true
      service:
        type: ClusterIP
        port: 9090
      persistence:
        enabled: true
        size: 10Gi
      externalLabels:
        cluster: "orion"
      thanos:
        create: true
        objectStorageConfig:
          secretKey: objstore.yml
          secretName: thanos-objstore-config
        resources:
          limits: {}
        requests: {}
        service:
          extraPorts:
          - name: "thanos-http"
            port: 10902
            targetPort: http
            protocol: TCP

      additionalScrapeConfigs:
        enabled: true
        type: external
        external: 
          name: "additional-scrape-configs"
          key: "prometheus-additional.yaml"

    operator:
      service:
        type: ClusterIP
        port: 8080

    alertmanager:
      enabled: true
      listenLocal: true
      service:
        type: ClusterIP
        port: 9093
      configSelector: 
        matchLabels:
          alertmanagerConfig: alertConfig
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```
