### ISSUE TITLE
[bitnami/kube-prometheus] values for thanos.ingress.tls gives a warning/error

### ISSUE THREAD

**Issue by ws-prive** [bitnami/charts#7978]
Helm chart: kube-prometheus 6.3.0
Helm version: 3.6.3
K8s version: 1.22.1

When installing the helm chart a warning is shown, this has to do with the prometheus-values.yaml file I am using. Without the -f prometheus-values.yaml the warnings are not shown. The error/warning is: 

```
coalesce.go:200: warning: cannot overwrite table with non table for tls (map[])
coalesce.go:200: warning: cannot overwrite table with non table for tls (map[])
```
Helm command:
```
helm upgrade prometheus bitnami/kube-prometheus -f prometheus-values.yaml \
  --install \
  --create-namespace \
  --namespace monitoring \
  --set prometheus.thanos.create=true \
  --set prometheus.thanos.objectStorageConfig.secretName=${THANOS_OBJSTORE_SECRET_NAME} \
  --set prometheus.thanos.objectStorageConfig.secretKey=objstore.yml \
  --set prometheus.thanos.ingress.enabled=true \
  --set prometheus.thanos.ingress.hosts[0].name="thanos-external2.test.com" \
  --set prometheus.thanos.ingress.annotations."kubernetes\.io/ingress\.class"=nginx \
  --set prometheus.thanos.ingress.annotations."nginx\.ingress\.kubernetes\.io/ssl-redirect"="true" \
  --set prometheus.thanos.ingress.annotations."nginx\.ingress\.kubernetes\.io/backend-protocol"="GRPC" \
  --set prometheus.thanos.ingress.annotations."nginx\.ingress\.kubernetes\.io/auth-tls-verify-client"="on" \
  --set prometheus.thanos.ingress.annotations."nginx\.ingress\.kubernetes\.io/auth-tls-secret"=${NAMESPACE}/thanos-ca-secret\
  --set prometheus.disableCompaction=true \
  --set prometheus.externalLabels.cluster=${CLUSTER_NAME} \
  --set prometheus.persistence.size=2Gi \
  --set prometheus.persistence.enabled=true \
  --set prometheus.retention=6h \
  --set prometheus.additionalScrapeConfigsExternal.enabled=false \
  --set prometheus.additionalScrapeConfigsExternal.name=additional-scrape-configs \
  --set prometheus.additionalScrapeConfigsExternal.key=prometheus-additional.yaml \
  --set kubeControllerManager.service.targetPort=10257 \
  --set kubeControllerManager.serviceMonitor.https=true \
  --set kubeControllerManager.serviceMonitor.insecureSkipVerify=true \
  --set kubeScheduler.service.targetPort=10259 \
  --set kubeScheduler.serviceMonitor.https=true \
  --set kubeScheduler.serviceMonitor.insecureSkipVerify=true
``` 

prometheus-values.yaml:
```
prometheus:
  thanos:
    ingress:
      tls:
      - hosts:
        - thanos-external2.test.com
      secretName: thanos-client-ingress-secret
```

Does anybody know how to fix this? Thanks!

**Comment by rafariossaa** [comment]
Hi,
  I think the issue here is that `prometheus.ingress.tls` is a boolean and you are providing an object. You can check the parameters [here](https://github.com/bitnami/charts/tree/master/bitnami/kube-prometheus#user-content-prometheus-parameters).

**Comment by ws-prive** [comment]
Hello @rafariossaa,

Thanks, but it is the ingress of thanos, not of prometheus and in the parameters {} is shown at prometheus.thanos.ingress.tls.

**Comment by rafariossaa** [comment]
Hi,
  Oh, I am sorry. My mistake.
  I think there is an indentation issue, or maybe it was an issue when pasted in  the issue description:
  The example in the values.yaml is:
```
       tls:
       - hosts:
           - thanos.prometheus.local
         secretName: thanos.prometheus.local-tls
```
but you have this:
```
prometheus:
  thanos:
    ingress:
      tls:
      - hosts:
        - thanos-external2.test.com
      secretName: thanos-client-ingress-secret
```
`secretName` should be in the `hosts` and not that the same level of `hosts`
