### ISSUE TITLE
[bitnami/minio] Adding LDAP support

### ISSUE THREAD

**Issue by eclipsetalk** [bitnami/charts#8000]
I'm trying to use LDAP with minio but it doesn't work. I don't even get any logs in the console.
This is my setting for my chart. What am I doing wrong:

```
extraEnv:
  - name: MINNIO_LOG_LEVEL
    value: DEBUG
  - name: MINIO_IDENTITY_LDAP_SERVER_ADDR
    value: "ldaps://xxxx.corp:636"
  - name: MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER
    value: "(&(objectCategory=user)(sAMAccountName=%s))"
  - name: MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN
    value: "DC=xxx,DC=CORP"
  - name: MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD
    value: 'xxxx'
  - name: MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN
    value: "CN=xxxxx,OU=Svcaccts,DC=xxx,DC=CORP"
  - name: MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER
    value: "(&(objectClass=group)(member=%d))"
```

**Comment by pablogalegoc** [comment]
Hi @eclipsetalk,

The parameter to add extra environment variables is `extraEnvVars` instead of `extraEnv`. Let me know if that was the issue.

**Comment by eclipsetalk** [comment]
I tried extraEnvVars also but no changes. Not sure how to unable LDAP with bitnami/minio

**Comment by pablogalegoc** [comment]
I've used the `extraEnvVars` parameter and I see the dummy variables are set in the pod:
```
❯ kubectl exec -it pod/minio-8489d4f795-k9gxt -- env | grep MINIO_IDENTITY_LDAP
MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN=CN=xxxxx,OU=Svcaccts,DC=xxx,DC=CORP
MINIO_IDENTITY_LDAP_SERVER_ADDR=ldaps://xxxx.corp:636
MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER=(&(objectClass=group)(member=%d))
MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD=xxxx
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN=DC=xxx,DC=CORP
```
Consider that these variables come from MinIO itself, they are not provided by us in the container image.

There's a documentation page that covers LDAP: [Configure MinIO for Authentication using Active Directory / LDAP](https://docs.min.io/minio/baremetal/security/ad-ldap-external-identity-management/configure-ad-ldap-external-identity-management.html#configure-minio-for-authentication-using-active-directory-ldap) and ultimately I'd recommend opening a discussion on the upstream project: https://github.com/minio/minio/discussions
I'm sure they'll know how to guide you better than us

**Comment by eclipsetalk** [comment]
I've made some progress, I can now see some error in the logs pertaining to LDAP. I see a x509 certificate issue.

`Error: Unable to parse LDAP configuration: Connection test for LDAP server failed: Error creating connection to LDAP server: LDAP Result Code 200 "Network Error": x509: certificate signed by unknown authority (*fmt.wrapError)
`
How can I set the certificate for minio? Which env variable should I set in the chart? 
Is it possible to set it via the bitnami helm chart? I have set up the CA cert as a trusted certificate via a kubernetes secret however how does one set it in the helm chart?

I tried the following but it doesn't work

```
tls:
  enabled: true
  existingSecret: "trusted-certs"
  mountPath: "/certs/CAs"
```
Thanks!

**Comment by eclipsetalk** [comment]
@pablogalegoc thank you. I can now set the certificate via the charts.

**Comment by eclipsetalk** [comment]
Any idea about this LDAP error? - I can access the LDAP server via the ldapsearch command line, so the LDAP setting is correct.

`Error: LDAP server error: Unable to find user DN: User DN for echaland not found (*fmt.wrapError)`

Thanks!

**Comment by eclipsetalk** [comment]
fyi - I've create a new issue in minio repo https://github.com/minio/minio/issues/13749

**Comment by javsalgar** [comment]
Thanks!

**Comment by nikhil-panchal** [comment]
hie @eclipsetalk can you share how you configure ldap config on chart now ??

**Comment by eclipsetalk** [comment]
Hi,
See below:
```
  ## @section Airflow ldap parameters
    ldap:
      enabled: true
      uri: "ldaps://xxxxx"
      base: "DC=xxxx,DC=CORP"
      uidField: "cn"
      binddn: "CN=xxxx,OU=xxxx,DC=xxx,DC=CORP"
      userRegistration: "True"
      userRegistrationRole: "Public"
      rolesMapping: "{'CN=....}"
      rolesSyncAtLogin: "True"

      tls:
        enabled: false
        allowSelfSigned: false
        CAcertificateSecret: "trusted-certs"
        CAcertificateFilename: "xxxx.pem"

```
