### ISSUE TITLE
bitnami/mongodb-sharded - External config server issue

### ISSUE THREAD

**Issue by sudheersagi** [bitnami/charts#8012]
_Originally posted by @sudheersagi in https://github.com/bitnami/charts/issues/7988#issuecomment-958685329_

Hi @yilmi 

I believe this is for sure not a problem from the MONGODB side but from the bitnami chart configuration itself because, when we tried to overwrite the /opt/bitnami/mongodb/conf/mongos.conf with the correct port configuration & fed it to the mongodb startup scripts, the MONGODB connection succeeded. 

We are looking forward for a couple of mins of your time (may be a quick zoom call) to talk about our suspicion on the  'PORT variables overwrite not happening'.

(https://github.com/bitnami/charts/tree/master/bitnami/mongodb-sharded#using-an-external-config-server)

#######################################

More details are described below:

I'm able to connect to Mongo configsvr from the POD without any issue if we run manually. What i was trying to tell you is after installed the chart, as soon the container is up and running it should create mongos process and and listen on port(here it is 27017) for any incoming requests, which is not happening because I dont see any pid inside _/opt/bitnami/mongodb/tmp/_. Correct me if this is not the expected behaviour of chart.

Just to make sure there are no existing PVCs
```sh
kubectl get pvc --namespace namespace1
No resources found in namespace1 namespace.
```

I followed the below steps to make sure there is not connectivity issue with MongoDB Config Server.

**Step1**: Installed the chart with above values.yaml file.
**Step2**: Exec to POD and verified conf files with custom changes
                 

>       - /bitnami/mongodb/conf/mongodb.conf  -- contains custom config as given in 'config' variable from yaml
> 		- /opt/bitnami/mongodb/conf/keyfile   -- Copied from 'replicasetKey' variable
> 		- /opt/bitnami/mongodb/conf/mongodb.conf -- same as in 'config' variable
> 		- /opt/bitnami/mongodb/conf/mongos.conf -- same as in 'config' variable
> 		- /opt/bitnami/mongodb/tmp/   -- process id is missing, assuming mongos not started

**Step3**: Perform command mongos -f <conf file>
                Terminal Output:

> mongos -f /opt/bitnami/mongodb/conf/mongos.conf 
			about to fork child process, waiting until server is ready for connections.
			forked process: 747
			child process started successfully, parent exiting

**Step4**: verify the process id, now i see pid is created which is supposed to be created during container startup itself.

> /opt/bitnami/mongodb/tmp# ls
				mongodb-27017.sock  mongodb.pid

**Step5**: Connect (external)configsvr/shrdsvr from mongos running pod.In step4 we see mongos process is started
        

>  $mongo --host 127.0.0.1  --port 27017 --authenticationDatabase "admin" -u "user" -p "passwd"
		MongoDB shell version v4.4.10
		connecting to: mongodb://127.0.0.1:27017/?authSource=admin&compressors=disabled&gssapiServiceName=mongodb
		Implicit session: session { "id" : UUID("066431fe-028a-453e-b689-f703a5fc781c") }
		MongoDB server version: 4.4.10
		mongos> 

FYI, **Step2** to **Step5** were performed within mongos pod.
**Step6**: Tried to connect from application and verify the data from MongoDB.
                   - We didn't observe any connection error (connection refused) and application is successfully opened connections.
        App Logs:
             

> logger:org.mongodb.driver.connection
message:Opened connection [connectionId{localValue:13, serverValue:85}] to mongodb.namespace1.svc.cluster.local:27017

From the above steps, i believe there is no connectivity issue with Mongo configsvr that is running externally and i think the mongos process should be created when the contianer up and running (if this is the expected behaiour of this chart).

I did grep on process that are running when POD is available

```sh
# ps -ef

root         1     0  0 17:57 ?        00:00:00 /bin/bash /opt/bitnami/scripts/mongodb-sharded/entrypoint.sh /opt/bitnami/scripts/mongodb-sharded/run.sh
root        13     1  0 17:57 ?        00:00:00 /bin/bash /opt/bitnami/scripts/mongodb-sharded/setup.sh

```

I also tried by launching separate instance(within network outside cluster) and manually installed mongodb binary with same mongos conf file and able to connect our centralised mongo configsvr without any issues.
We still see 
> "clientAddress":"(unknown)"

 in the log but able to connect mongo. So i guess this is not actual error and it is ignorable

_Originally posted by @sudheersagi in https://github.com/bitnami/charts/issues/7988#issuecomment-958685329_

**Comment by yilmi** [comment]
Hi @sudheersagi,

I'm a bit confused by your tests, you shouldn't start a process manually (Step 3), containers manage this for you.

When you deploy a chart and pass it a values.yaml file, you don't need to define all the values. The values that are not defined in your file are defaulted.

Instead of giving me the full values file for which I'd have to review individually every value to understand what you changed, could you please review what you changed, and only giving me a values file with values that are not the default ones? That would really save us some time and avoid confusion.

I don't know if you saw my last comment in the other issue:
> We are not MongoDB developers, and right now your problem seems more related to how MongoDB works than our chart itself. It seems that the Config Server also needs connectivity with the mongos - https://dba.stackexchange.com/a/201698

Can the config server reach your mongo pods? It seems to be a requirement.

Thanks

**Comment by sudheersagi** [comment]
Hi @yilmi 

Exactly we are trying to tell the same that mongos process not getting started after the chart is deployed and container status is Up and running with the below values.yaml changes. The reason we performed manual steps is to make sure the connections from PODS to Configsvr and ConfigSvr to PODS without any issues.

Yes, i saw your comment and it is confirmed that the config servers are reachable to mongos pods.

Config server is running on port **27019**, so we override MONGODB_CFG_PRIMARY_PORT_NUMBER in mongos deployment.Added pod logs below with and without override this variable
```yaml
- name: MONGODB_CFG_PRIMARY_PORT_NUMBER
   value: "27019"
```

_Below are the values that we changed in **values .yaml**_

#### Enabled the Debug logs

```yaml
## Set to true if you would like to see extra information on logs
##
  debug: true
```
#### Set shards to 0
```yaml
shards: 0
```

#### External config server values,
```yaml
configsvr:
     replicas: 0
  external:
    
     host: "configsvr1.example.com"
    
     rootPassword: rootpassword
    
     replicasetName: "cfgrs0"
    
     replicasetKey: |-
       YT9GpcsjddsjhdshhsjdahjssdflqzSyKK/lJs1Ly9jxFAjhdjjKjsjfhdkJFJBDCBXBCSjsh
       hQrnebqxrFSmHb+v2iKPs7D7mVDIrcPkyJYGxeDN8rEcxTmI7KOytmz3B6sASM7R
       VBH5K9SxA+fyZlGeK+WqlwpJppdJQ88jEo0QvSmOCHofgKK2Q4UeJmEfSXzaDmV8
       PJsU6TYSKUdc9a02nW47ki254HepYnMRfx9NQ3P/SPdI4IitdY7HQHkLC5WDR5+T
       Xa1fT/64s3FgI7Lub8mH6V1Oz16GXBLR0lyUGQJZbdO6fRpfm96MPhmTb9BDnRHW
       zFSIl/yuMwl8W+UBxX+EBWW8sajj8jhjhJJHJKUY89983QuWmGzsmD2wDcIEq92N
       PsdghjhsghsagfhUIYSAjhjHiuJBhjh7867687TEBeCkg2NYYQz2lwqGfzmiAX

```

#### Updated Mongos values

```yaml
mongos:
  
  replicas: 1

  config: |-
    net:
      #bindIp: 0.0.0.0,127.0.0.1,app1.host.com,mongos.namespace1.svc.cluster.local
      bindIpAll: true
      port: 27017
      unixDomainSocket:
        enabled: true
        pathPrefix: /opt/bitnami/mongodb/tmp
    processManagement:
      fork: true
      pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
    security:
      keyFile: /opt/bitnami/mongodb/conf/keyfile
      clusterAuthMode: keyFile
    sharding:
      configDB: cfgrs0/configsvr0.example.com:27019,configsvr1.example.com:27019,configsvr2.example.com:27019
    systemLog:
      destination: file 
      path: /opt/bitnami/mongodb/logs/mongodb.log
      logAppend: true

```

#### Commented the shard server replicas
```yaml
shardsvr:
    dataNode:
        replicas: 0
```

#### Pods logs with override of MONGODB_CFG_PRIMARY_PORT_NUMBER 

```
mongodb 17:55:04.77 Welcome to the Bitnami mongodb-sharded container
mongodb 17:55:04.77 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb-sharded
mongodb 17:55:04.77 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb-sharded/issues
mongodb 17:55:04.77 
mongodb 17:55:04.77 INFO  ==> ** Starting MongoDB Sharded setup **
mongodb 17:55:04.80 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 17:55:04.81 INFO  ==> Initializing Mongos...
mongodb 17:55:04.81 WARN  ==> Mounted mongos configuration file as mongodb.conf. Copying it to mongos.conf
mongodb 17:55:04.82 INFO  ==> Writing keyfile for replica set authentication...
mongodb 17:55:04.83 DEBUG ==> Waiting for primary node...
mongodb 17:55:04.83 DEBUG ==> Waiting for primary node...
mongodb 17:55:04.83 INFO  ==> Trying to connect to MongoDB server configsvr0.example.com...
mongodb 17:55:05.85 INFO  ==> Found MongoDB server listening at configsvr0.example.com:27019 !

```

#### Pod logs without overriding  MONGODB_CFG_PRIMARY_PORT_NUMBER

```
mongodb 18:11:58.11 INFO  ==> ** Starting MongoDB Sharded setup **
mongodb 18:11:58.14 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 18:11:58.15 INFO  ==> Initializing Mongos...
mongodb 18:11:58.15 INFO  ==> Writing keyfile for replica set authentication...
mongodb 18:11:58.17 DEBUG ==> Waiting for primary node...
mongodb 18:11:58.17 DEBUG ==> Waiting for primary node...
mongodb 18:11:58.17 INFO  ==> Trying to connect to MongoDB server configsvr0.example.com...
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"

```

**Comment by yilmi** [comment]
Hi @sudheersagi,

Thanks for your follow-up. My question was not only about `Mongos` --> `ConfigSrv:27019` but also `ConfigSrv` --> `Mongos:27017`. I assume this works right?

I'm trying to reproduce your issue with the values you provided, adjusting them to my environment.

**Comment by sudheersagi** [comment]
Thanks @yilmi , yes, it is working even with `ConfigSrv` --> `Mongos:27017`, verified from config server.

Correct i have checked configuration by running it manually and it is working.
Like i mentioned i'm stuck with mongos which is not starting automatically when the container is up with the above values yaml.

**Comment by yilmi** [comment]
@sudheersagi, have you tried adding the following to your values? 

```
mongos:
   extraEnvVars:
    - name: MONGODB_CFG_PRIMARY_PORT_NUMBER
      value: 27019
```

**Comment by sudheersagi** [comment]
Yes, i tried both by adding at mongos extraEnvVars and also as container env variable in mongos-dep-sts, don't see any difference in behaviour.

**Comment by yilmi** [comment]
@sudheersagi, I'm looking at this and will get back to you as soon as I have an update

**Comment by sudheersagi** [comment]
Thank you @yilmi. I'm at final phase of testing my application and i just blocked with this, please let me know once you have it.

**Comment by yilmi** [comment]
Hi @sudheersagi, I was able to reproduce the issue you initially reported, on my end I needed to define a service for the `configsvr`.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: configsvr
spec:
  selector:
    app.kubernetes.io/component: configsvr
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
```

With the following values for a config server:
```yaml
clusterDomain: cluster.local
image:
  debug: true
mongodbRootPassword: "rootpassword"
replicaSetKey: "testkey123"
shards: 0

service:
  name: "cfgrs0"
  port: 27017

configsvr:
  replicas: 1

mongos:
  replicas: 0
shardsvr:
  dataNode:
    replicas: 0
```

Values for the mongos:
```yaml

clusterDomain: cluster.local
image:
  debug: true
mongodbRootPassword: "rootpassword"
replicaSetKey: "testkey123"
shards: 2

service:
  name: "mongos"
  port: 27017

configsvr:
  replicas: 0
  external:
    host: "configsvr"
    rootPassword: rootpassword
    replicasetName: "mongos"
    replicasetKey: "testkey123"

mongos:
  replicas: 1

shardsvr:
  dataNode:
    replicas: 1
  persistence:
    enabled: true
  arbiter:
    replicas: 0
```

I can get the mongos to connect to the config server, so the external configsvr values work:
```bash
❯ kubectl logs mongos-mongodb-sharded-mongos-79b87dd6b8-55qfb --follow
mongodb 14:33:11.36 Welcome to the Bitnami mongodb-sharded container
<TRUNCATED>
mongodb 14:33:11.46 INFO  ==> Trying to connect to MongoDB server configsvr...
mongodb 14:33:11.47 INFO  ==> Found MongoDB server listening at configsvr:27017 !
mongodb 14:33:11.58 INFO  ==> MongoDB server listening and working at configsvr:27017 !
mongodb 14:33:11.58 DEBUG ==> Waiting for primary host configsvr to be ready...
mongodb 14:33:11.58 DEBUG ==> Validating configsvr as primary node...
mongodb 14:33:11.72 INFO  ==> Primary node ready.
mongodb 14:33:11.73 INFO  ==> ** MongoDB Sharded setup finished! **
<...>
{"t":{"$date":"2021-11-10T14:34:52.645+00:00"},"s":"I",  "c":"NETWORK",  "id":4333208, "ctx":"ReplicaSetMonitor-TaskExecutor","msg":"RSM host selection timeout","attr":{"replicaSet":"mongos","error":"FailedToSatisfyReadPreference: Could not find host matching read preference { mode: \"nearest\" } for set mongos"}}
{"t":{"$date":"2021-11-10T14:34:59.845+00:00"},"s":"I",  "c":"NETWORK",  "id":4333208, "ctx":"ReplicaSetMonitor-TaskExecutor","msg":"RSM host selection timeout","attr":{"replicaSet":"mongos","error":"FailedToSatisfyReadPreference: Could not find host matching read preference { mode: \"nearest\" } for set mongos"}}
{"t":{"$date":"2021-11-10T14:34:59.845+00:00"},"s":"W",  "c":"SHARDING", "id":23834,   "ctx":"mongosMain","msg":"Error initializing sharding state, sleeping for 2 seconds and retrying","attr":{"error":{"code":133,"codeName":"FailedToSatisfyReadPreference","errmsg":"Error loading clusterID :: caused by :: Could not find host matching read preference { mode: \"nearest\" } for set mongos"}}}
```

I'm still getting errors but they are related to the MongoDB configuration, as I'm not an expert I'll let you figure out what this may be.

**Comment by sudheersagi** [comment]
Thanks @yilmi for spending your time on this. I have couple of questions on your setup,
Is the `configsvr` running within the cluster? in our case the configsvr and shardsvr(shard nodes) are running outside the cluster(but in same network).
 As in your mongos values, do we need shardsvr and persistence enabled? Also i observed `shards: 2`, are these required to be running on same cluster where mongos exists or you just add them for your setup? In my case, all these were disabled only mongos service to be up and running.

```yaml
shardsvr:
  dataNode:
    **replicas: 1**
  persistence:
    **enabled: true**
  arbiter:
    replicas: 0
```

**Comment by yilmi** [comment]
Hi @sudheersagi, yes in my case the configsvr was running within the same cluster, but it shouldn't really matter as long as it can be reached and as long as it can reach the mongos. As you know, configuring it with port 27019 was causing some issues (as per https://github.com/bitnami/charts/issues/7850).

For the mongo values, the shards and persistence don't really impact this type of configuration I would say, the external configsvr is all we really need. I added them to have a realistic deployment type, so I didn't put much thoughts into it :-)

**Comment by sudheersagi** [comment]
@yilmi Thanks for the info, Yes, the issue is with port as our config server is running on port 27019 and chart takes only 27017, I don't think i have an option to change port to 27017 as this is common configsvr(centralized for multiple services). It would be great if we have provision to allow custom port for each component(mongos, configsvr and shardsvr). I see you have already updated ticket (#7981) . Any expected timeline for this changes.

**Comment by sudheersagi** [comment]
Is there a workaround to deploy only mongos in cluster connecting to external configsvr using custom config port and also to specify mutiple host names(configsvr replicaset) in configsvr primary host as mentioned in ticket (#7981 ).

Basically how do i make below custom mongos conf read by mongos and get it work with this chart.

```yaml
net:
      #bindIp: 0.0.0.0,127.0.0.1,app1.host.com,mongos.namespace1.svc.cluster.local
      bindIpAll: true
      port: 27017
      unixDomainSocket:
        enabled: true
        pathPrefix: /opt/bitnami/mongodb/tmp
    processManagement:
      fork: true
      pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
    security:
      keyFile: /opt/bitnami/mongodb/conf/keyfile
      clusterAuthMode: keyFile
    sharding:
      configDB: cfgrs0/configsvr0.example.com:27019,configsvr1.example.com:27019,configsvr2.example.com:27019
```
