### ISSUE TITLE
[bitnami/redis] Allow configuring the topology key for pod anti-affinity

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [bitnami/charts#8057]
**Which chart**:
bitnami/redis 15.4.1

**Is your feature request related to a problem? Please describe.**
The redis chart uses `common.affinities.pods.{soft,hard}` to manage anti-affinity, which specifies a fixed topologyKey ([source](https://github.com/bitnami/charts/blob/66edf04e3e244c343a845f9c684edf4c8ea04406/bitnami/common/templates/_affinities.tpl#L67)):

```
topologyKey: kubernetes.io/hostname
```

This makes it impossible to select other keys, e.g. `topology.kubernetes.io/zone` for zonal redundancy.

**Describe the solution you'd like**
A configurable `topologyKey` similar to how this was done for `bitnami/prometheus-operator`: https://github.com/bitnami/charts/pull/2998.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by juan131** [comment]
Hi @igorwwwwwwwwwwwwwwwwwwww 

Please note that we offer two kind of parameters to configure affinity/antiaffinity:

 - `xxx.podAffinityPreset` and `xxx.podAntiAffinityPreset` that can be set to `soft` or `hard` as you pointed out. These values are based on a predefined topology and they're intended to provide a quick way to setup affinity for beginners.
 - `xxx.affinity` that allows you overwrite the affinity with **any custom values you want to set**. This parameter is perfect for advanced use case such as yours since you have the freedom to customize the affinity as you want.

Everything's is detailed in the README.md, see https://github.com/bitnami/charts/tree/master/bitnami/redis#setting-pods-affinity

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
@juan131 Oh, I'd missed that capability! This answers my question.

For `soft` zonal affinity (if you want `hard` you can specify `requiredDuringSchedulingIgnoredDuringExecution` instead):

```
replica:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: node
              app.kubernetes.io/instance: my-release
              app.kubernetes.io/name: redis
          namespaces:
          - default
          topologyKey: topology.kubernetes.io/zone
        weight: 1
```
