### ISSUE TITLE
[bitnami/mongodb] Custom passwords users/dbs are only applied if auth.username and auth.database are used

### ISSUE THREAD

**Issue by mtimm** [bitnami/charts#8063]
**Which chart**:

bitnami/mongodb 10.29.0

**Describe the bug**

https://github.com/bitnami/charts/pull/7930 added the ability to configure multiple custom users and dbs with custom passwords however the custom passwords for said users is only applied if auth.username and auth.database is configured in the values.

Maybe this is working as designed but it seems very unexpected to me.  Values.auth.username and Values.auth.database are marked as deprecated and the documentation actually tells me to not use them: `DEPRECATED: use auth.usernames instead`  I do not see anything in the values documentation indicating the need to set them to get the custom passwords to carry over to the container.  Furthermore if the passwords are not set the container does not create the users or databases so it appears the feature just does not work at all unless the Values.auth.username and Values.auth.database parameters are set.

It isn't until I check the PR that added the feature that I find why the passwords are not being added:

https://github.com/bitnami/charts/pull/7930/files#diff-554225b236b642288f544d53cc31de044366922b8d9cbc10900bf19c8cf160aaL252
https://github.com/bitnami/charts/pull/7930/files#diff-15a560b024db8405938da8651ab677415b49eb54bc6c93b93361abc27ee18643L257
https://github.com/bitnami/charts/pull/7930/files#diff-53647e8938136505d791ce5b8487bc7aec81ac947f49f8b755b73afc63cb6df6L216

**To Reproduce**

1.  I used the same values from the original PR but removed the auth.username, auth.password and auth.database and I added a password just for testing, even if it's completely omitted, helm auto-generates one and the issue is still seen.

```
auth:
  usernames:
    - "juan"
  passwords:
    - "redactedpassword"
  databases:
    - "mydb"
```

2. I ran `helm install my-release bitnami/mongodb -f values.yaml`
3. Then grabbed the logs from the pod, the top of the logs before mongodb fully started had:

`mongodb 22:28:18.13 WARN  ==> Cannot create user 'juan', no password provided`

4. The containers env section of the replicaset spec did not contain the `MONGODB_EXTRA_PASSWORDS`

```
      containers:
      - env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: MONGODB_EXTRA_USERNAMES
          value: juan
        - name: MONGODB_EXTRA_DATABASES
          value: mydb
        - name: MONGODB_ROOT_USER
          value: root
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb-root-password
              name: my-release-mongodb
        - name: ALLOW_EMPTY_PASSWORD
          value: "no"
        - name: MONGODB_SYSTEM_LOG_VERBOSITY
          value: "0"
        - name: MONGODB_DISABLE_SYSTEM_LOG
          value: "no"
        - name: MONGODB_DISABLE_JAVASCRIPT
          value: "no"
        - name: MONGODB_ENABLE_JOURNAL
          value: "yes"
        - name: MONGODB_ENABLE_IPV6
          value: "no"
        - name: MONGODB_ENABLE_DIRECTORY_PER_DB
          value: "no"
```

**Expected behavior**

Custom users/dbs can be used without also having to set auth.username and auth.database which are now deprecated.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6+k3s1", GitCommit:"df033fa248bc2c9f636e4c0ff2b782cb8edbbf10", GitTreeState:"clean", BuildDate:"2021-11-04T00:25:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

N/A
