### ISSUE TITLE
Azure Disks are not deleted when PVC is deleted

### ISSUE THREAD

**Issue by mbendtsen** [bitnami/charts#8070]
**Which chart**:
rabbitmq

**Describe the bug**
Azure Disks is not deleted when PV and PVC is deleted. 
This seems to work when using rabbitmq-operator together with the RabbitMQCluster object.

**To Reproduce**

1. Install chart
   - `helm repo add bitnami-azure https://marketplace.azurecr.io/helm/v1/repo`
   - `helm install rabbitmq -f values.yml bitnami-azure/rabbitmq`  
2. Wait for the disks to be provisioned 
3. Uninstall release (`helm uninstall rabbitmq`)
4. Wait for pod to be terminated
5. Delete PVC and PV

**Expected behavior**
When reclaims policy is set to delete, I would expect it to delete the disk in Azure.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"881d4a5a3c0f4036c714cfb601b377c4c72de543", GitTreeState:"clean", BuildDate:"2021-10-21T05:13:01Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

### values.yml
``` yaml
## RabbitMQ Authentication parameters
##
auth:
  username: ****
  password: "*******************"

replicaCount: 1
podManagementPolicy: Parallel
resources:
  limits: {}
  requests: 
    cpu: 1000m
    memory: 4096Mi

tolerations:   
  - key: "products"
    operator: "Equal"
    value: "rabbitmq"
    effect: "NoSchedule"

persistence:
  enabled: true
  storageClass: "managed-csi"
  accessMode: ReadWriteOnce
  existingClaim: ""
  size: 20Gi
  volumes: []
  annotations: {}
```

### StorageClass
``` yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-csi
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: 'true'
provisioner: disk.csi.azure.com
parameters:
  skuname: StandardSSD_LRS
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
```
