### ISSUE TITLE
[bitnami/redmine] The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable.

### ISSUE THREAD

**Issue by ytianxia6** [bitnami/charts#8084]
**Which chart**:
The name (and version) of the affected chart
bitnami/redmine  17.0.7

**Describe the bug**
the mariadb pod cannot start!

**To Reproduce**

installed the helm with values:

``` yaml
affinity: {}
allowEmptyPassword: false
args: []
autoscaling:
  enabled: false
  maxReplicas: 11
  minReplicas: 1
  targetCPU: 50
  targetMemory: 50
certificates:
  customCA: []
  customCertificate:
    certificateLocation: /etc/ssl/certs/ssl-cert-snakeoil.pem
    certificateSecret: ''
    chainLocation: /etc/ssl/certs/mychain.pem
    chainSecret:
      key: ''
      name: ''
    keyLocation: /etc/ssl/private/ssl-cert-snakeoil.key
  extraEnvVars: []
  image:
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 10-debian-10-r203
command: []
commonAnnotations: {}
commonLabels: {}
containerPort: 3000
containerSecurityContext:
  enabled: false
  runAsUser: 1001
customLivenessProbe: {}
customPostInitScripts: {}
customReadinessProbe: {}
customStartupProbe: {}
databaseType: mariadb
existingSecret: ''
externalDatabase:
  database: redmine
  existingSecret: ''
  host: redmine-db-mysql.redmine.svc.cluster.local
  password: *****
  port: 3306
  user: root
extraDeploy: []
extraEnvVars: []
extraEnvVarsCM: ''
extraEnvVarsSecret: ''
extraVolumeMounts: []
extraVolumes: []
fullnameOverride: ''
global:
  imagePullSecrets: []
  imageRegistry: ''
  storageClass: ''
hostAliases: []
image:
  debug: false
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: docker.io
  repository: bitnami/redmine
  tag: 4.2.2-debian-10-r13
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  apiVersion: ''
  certManager: true
  enabled: true
  extraHosts: []
  extraPaths: []
  extraTls: []
  hostname: xxx
  path: /
  pathType: ImplementationSpecific
  secrets: []
  selfSigned: false
  tls: true
initContainers: []
kubeVersion: ''
livenessProbe:
  enabled: true
  failureThreshold: 6
  initialDelaySeconds: 300
  path: /
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
mailReceiver:
  affinity: {}
  allowOverride: ''
  args:
    - '-c'
    - /cj/receive.sh
  assignedTo: ''
  category: ''
  command:
    - bash
  containerSecurityContext:
    enabled: false
    runAsNonRoot: true
    runAsUser: 1001
  defaultGroup: ''
  enabled: false
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraVolumeMounts: []
  extraVolumes: []
  host: ''
  imapFolder: INBOX
  initContainers: []
  mailProtocol: IMAP
  moveOnFailure: ''
  moveOnSuccess: ''
  noAccountNotice: 1
  noPermissionCheck: 0
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  password: ''
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  port: 993
  priority: ''
  priorityClassName: ''
  project: ''
  projectFromSubaddress: ''
  schedule: '*/5 * * * *'
  sidecars: []
  ssl: true
  startTLS: false
  status: ''
  suspend: true
  tolerations: []
  tracker: ''
  unknownUserAction: ignore
  username: ''
mariadb:
  architecture: standalone
  auth:
    database: redmine
    existingSecret: ''
    password: ''
    rootPassword: ''
    username: bn_redmine
  enabled: true
  primary:
    persistence:
      accessModes:
        - ReadWriteOnce
      enabled: true
      existingClaim: ''
      hostPath: ''
      size: 8Gi
      storageClass: ''
nameOverride: ''
nodeAffinityPreset:
  key: ''
  type: ''
  values: []
nodeSelector: {}
persistence:
  accessModes:
    - ReadWriteOnce
  dataSource: {}
  enabled: true
  existingClaim: ''
  size: 80Gi
  storageClass: ''
podAffinityPreset: ''
podAnnotations: {}
podAntiAffinityPreset: soft
podDisruptionBudget:
  create: false
  maxUnavailable: ''
  minAvailable: ''
podLabels: {}
podSecurityContext:
  enabled: false
  fsGroup: 1001
postgresql:
  enabled: false
  existingSecret: ''
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    existingClaim: ''
    size: 8Gi
    storageClass: ''
  postgresqlDatabase: bitnami_redmine
  postgresqlPassword: ''
  postgresqlUsername: bn_redmine
readinessProbe:
  enabled: true
  failureThreshold: 6
  initialDelaySeconds: 5
  path: /
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
redmineEmail: xxx
redmineLanguage: cn
redminePassword: ********
redmineUsername: admin
replicaCount: 1
resources:
  limits: {}
  requests:
    cpu: 300m
    memory: 512Mi
schedulerName: ''
service:
  annotations: {}
  clusterIP: ''
  externalTrafficPolicy: Cluster
  extraPorts: []
  loadBalancerIP: ''
  loadBalancerSourceRanges: []
  nodePort: ''
  port: 80
  type: ClusterIP
serviceAccount:
  create: false
  name: ''
sidecars: []
smtpExistingSecret: ''
smtpHost: ''
smtpPassword: ''
smtpPort: ''
smtpProtocol: ''
smtpUser: ''
startupProbe:
  enabled: false
  failureThreshold: 6
  initialDelaySeconds: 300
  path: /
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
tolerations: []
updateStrategy:
  rollingUpdate: {}
  type: RollingUpdate
volumePermissions:
  enabled: false
  resources:
    limits: {}
    requests: {}
  securityContext:
    runAsUser: 0
```

the pod mariadb logs:

``` bash
mariadb 05:39:43.07 
mariadb 05:39:43.07 Welcome to the Bitnami mariadb container
mariadb 05:39:43.07 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 05:39:43.07 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 05:39:43.08 
mariadb 05:39:43.08 INFO  ==> ** Starting MariaDB setup **
mariadb 05:39:43.12 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 05:39:43.14 INFO  ==> Initializing mariadb database
mariadb 05:39:43.16 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mariadb 05:39:43.16 INFO  ==> Using persisted data
mariadb 05:39:43.21 INFO  ==> Running mysql_upgrade
mariadb 05:39:43.22 INFO  ==> Starting mariadb in background
```

**Expected behavior**
mariadb start normal.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}```

**Additional context**
Add any other context about the problem here.
