### ISSUE TITLE
Unable to upgrade version of mongo server

### ISSUE THREAD

**Issue by dannyharding10** [bitnami/charts#8087]
**Which chart**:
bitnami/mongodb

**Describe the bug**
When updating the image tag in order to upgrade the mongodb server version of a standalone mongo server, I am unable to upgrade the release. I run the command `helm upgrade mongodb bitnami/mongodb -f mongodb.yml` (with the new image tag in the values file), but the new pod goes into a CrashLoopBackoff state with the error `"DBPathInUse: Unable to lock the lock file: /bitnami/mongodb/data/db/mongod.lock (Resource temporarily unavailable). Another mongod instance is already running on the /bitnami/mongodb/data/db directory"`. I am trying to update the image tag from `4.2` to `4.4.10`. It seems to me that when trying to make this upgrade, the new mongo pod should be able to take over the lock file to avoid this error.

**To Reproduce**

1. `helm install mongodb bitnami/mongodb --set image.tag=4.2`
2. `helm upgrade mongodb bitnami/mongodb --set image.tag=4.2`
3. See error

**Expected behavior**
I would expect the new mongo pod to spin up seemlessly, and the old one to go away

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T09:58:13Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I am not experienced in this, but I believe this may not be a problem if the pod were to be scheduled on a different node, but I don't know what would happen to all of the data in the DB if that were to happen..

I also tried to shutdown the original mongo instance using `db.shutdownServer()`, but it would turn itself back on too quickly for me to launch the new pod 😆.

<details>
  <summary>Here are the contents of my values file in case it is relevant</summary>

```
image:
  tag: 4.4.10

auth:
  enabled: false

enableIPv6: false


service:
  annotations: {}
  type: ClusterIP

# port: 27017

tolerations:
  - key: dedicated
    value: db
    effect: NoSchedule

persistence:
  enabled: true
  size: 20Gi
  storageClass: expandable-gp2
  existingClaim: mongodb

# configuration: {}

resources:
  requests:
    cpu: 200m
    memory: 512Mi

nodeSelector:
  kops.k8s.io/instancegroup: db
```
</details>
