### ISSUE TITLE
Unable to add multiple replicas for odoo

### ISSUE THREAD

**Issue by ddevops** [bitnami/charts#8109]
**Which chart**:
bitnami/charts/odoo

**Describe the bug**
My requirement is to run odoo with a multiple replica counts, as per the chart I have also have to use access_mode: ReadWriteMany. The issue is when I change this access value from ReadWriteOnce to ReadWriteMany it gives me below error in events.

`Failed to provision volume with StorageClass "gp2": invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce] are supported`

Helm version: v3.7.0

EKS version: v1.21.2

Kubectl version: v1.22.2

**Comment by marcosbc** [comment]
Hi @ddevops, unfortunately that seems to be a limitation of your file system provider on EKS. In order to fix it, you have to change to a different one, like EFS (related to: https://stackoverflow.com/questions/51212904/kubernetes-pvc-with-readwritemany-on-aws)

**Comment by kartik-moolya** [comment]
I have added a EFS storage class and this is my values.yaml (part of it ofcourse)
```
persistence:
  enabled: true
  storageClass: aws-efs
  accessModes:
    - ReadWriteMany
  size: 10Gi
volumePermissions:
  enabled: true
```
However I get error from the init container saying 
```chown: changing ownership of '/bitnami/odoo': Operation not permitted```

Am I missing something?

I also tried setting
```
volumePermissions:
  enabled: false
```
But then to the error is same

**Comment by kartik-moolya** [comment]
@ddevops  did you get it to work somehow?

**Comment by ddevops** [comment]
@kartik-moolya my issue was related to the file storage as it didn’t support ReadWriteMany I had to change my fs

**Comment by dkaliberda** [comment]
EFS works with the following settings (ID: 999 is required):
```yaml
persistence:
  enabled: true
  storageClass: efs
  accessModes:
    - ReadWriteMany
  size: 4Gi

podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
  fsGroup: 999
containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  runAsUser: 999
  runAsGroup: 999
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
    add: ["CHOWN", "FOWNER", "SYS_CHROOT", "SETGID", "SETUID", "DAC_OVERRIDE"]
  seccompProfile:
    type: "RuntimeDefault"
 ```
 
 My storage class is:
 ```yaml
 apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs
provisioner: efs.csi.aws.com
parameters:
  directoryPerms: '700'
  ensureUniqueDirectory: 'true'
  fileSystemId: fs-0408057bcdad87879
  gidRangeEnd: '5000'
  gidRangeStart: '1000'
  provisioningMode: efs-ap
  reuseAccessPoint: 'false'
  subPathPattern: ${.PVC.namespace}/${.PVC.name}
reclaimPolicy: Delete
mountOptions:
  - iam
allowVolumeExpansion: true
volumeBindingMode: Immediate
```
