### ISSUE TITLE
[bitnami/spark] Cannot expose Spark workers, Spark Web UI uses inaccessible private IPs 

### ISSUE THREAD

**Issue by brsolomon-deloitte** [bitnami/charts#8121]
**Which chart**:

spark

**Describe the bug**

When `spark-master-svc` is exposed as LoadBalancer, the resulting UI still uses private IPv4 addresses for Spark workers, which are inaccessible and seemingly can't be changed.

**To Reproduce**

Deploy Spark chart 5.7.9.

Patch to LoadBalancer:

```
kubectl patch svc spark-master-svc \
    -p '{"spec": {"type": "LoadBalancer", "loadBalancerSourceRanges": ["xx.xx.xx.xx"]}}'
```

On the Spark UI, under "Completed Drivers", the worker link is `http://172.xx.xx.xx:8081/`.

**Expected behavior**

Allow the workers to be exposed through LB and/or use their service hostname rather than bare IP.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
In order to reproduce the issue, can you share the _values.yaml_ or helm command with the different `--set` flags you are using?

**Comment by brsolomon-deloitte** [comment]
I have not overridden any values in `values.yaml` - only called a single `kubectl patch` as shown above to expose the spark-master-svc as LoadBalancer. You can reproduce with the version 5.7.9 Spark chart as-is.

**Comment by carrodher** [comment]
I'm not sure if this approach will work, there are some parameters in the Helm chart to configure the service type:
```yaml
 ## Service parameters
 ##
 service:
   ## @param service.type Kubernetes Service type
   ##
   type: ClusterIP
   ## @param service.clusterPort Spark cluster port
   ##
   clusterPort: 7077
   ## @param service.webPort Spark client port
   ##
   webPort: 80
   ## Specify the nodePort(s) value(s) for the LoadBalancer and NodePort service types.
   ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
   ## @param service.nodePorts.cluster Kubernetes cluster node port
   ## @param service.nodePorts.web Kubernetes web node port
   ##
   nodePorts:
     cluster: ""
     web: ""
   ## @param service.loadBalancerIP Load balancer IP if spark service type is `LoadBalancer`
   ## Set the LoadBalancer service type to internal only
   ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
   ##
   loadBalancerIP: ""
```
Those are the default values (using `ClusterIP`), in order to use `LoadBalancer` you should edit the _values.yaml_ or provide the required parameters with `--set`

**Comment by brsolomon-deloitte** [comment]
> Those are the default values (using ClusterIP), in order to use LoadBalancer you should edit the values.yaml or provide the required parameters with --set

`kubectl patch svc spark-master-svc` provides the same behavior as setting the parameters at application deployment time.

This is clear since `svc-master.yaml` only applies to the Spark master:

https://github.com/bitnami/charts/blob/75700414c95177b44ab32a2eedb9d3571646360a/bitnami/spark/templates/svc-master.yaml#L40

This issue is concerning the fact that setting `service.type=LoadBalancer` will still result in a ton of dead hyperlinks in the Spark Master UI since those links still use the private IP addresses of the rest of the cluster (e.g. workers).

**Comment by carrodher** [comment]
The point of using the parameter during the initialization is that the installation notes are rendered based on the parameters provided, so you can see the access instructions based on the service type, but yes, in this case, it seems it doesn't matter at all.

I'm not sure about how the dead links issue can be solved in this kind of environment

**Comment by brsolomon-deloitte** [comment]
not stale

**Comment by brsolomon-deloitte** [comment]
Still investigating this one; one interesting thing i've run across (though old and written for Python2, quite possibly needs updating) is the use of a single proxy that hands off to the rest of the cluster for serving the different UIs: https://github.com/KienMN/Standalone-Spark-on-Kubernetes/tree/master/images/spark-ui-proxy

**Comment by brsolomon-deloitte** [comment]
Same concept here: https://github.com/kubernetes/examples/tree/master/staging/spark

**Comment by juan131** [comment]
Hi @brsolomon-deloitte 

It makes sense! You definitely need a Proxy to properly redirect the requests to the right worker since they'll be exposing the cluster internal IPs otherwise.

This chart currently lacks of this Proxy, you can workaround it by using the `extraDeploy` parameter to deploy a Proxy (using a Spark UI Proxy image) and its associated service when installing the chart:

- https://github.com/bitnami/charts/blob/master/bitnami/spark/values.yaml#L30

**Comment by brsolomon-deloitte** [comment]
@juan131 thanks, if I can get that working, would you welcome a docs PR illustrating the use of `extraDeploy` for a Spark proxy or do you think that is out of scope?

**Comment by carrodher** [comment]
Yes, sure. Feel free to create a PR, I think a subsection of "Configuration and installation details" would be fine, at the same level as "Define custom configuration" or "Submit an application". We will be happy to review it

**Comment by brsolomon-deloitte** [comment]
not stale

**Comment by brsolomon-deloitte** [comment]
Update: we have found a much easier way to fix this issue.

Spark natively supports `spark.ui.reverseProxy` and `spark.ui.reverseProxyUrl` config parameters. In the past, Spark seemed to be buggy with regards to these, but now they seem to be working fully and configurable through the Helm chart. Simply set:

```yaml
master:
  configOptions:
    -Dspark.ui.reverseProxy=true 
    -Dspark.ui.reverseProxyUrl=https://spark.<your-domain.com>
worker:
  configOptions:
    -Dspark.ui.reverseProxy=true 
    -Dspark.ui.reverseProxyUrl=https://spark.<your-domain.com>
```

in your custom values.yaml, with `reverseProxyUrl` pointing to where you ultimately have Spark accessible. (For instance, the `host` of an `Ingress` resource.)

This works like a charm in our cluster and wipes out the need for a separate custom proxy deployment.

the URLs will look like

```
https://spark.my-domain.com/proxy/worker-20220126204037-<private-ip>-34297
```

and in spark-master logs you should see

> 22/01/26 20:40:08 INFO Master: Spark Master is acting as a reverse proxy. Master, Workers and Applications UIs are available at https://spark.<my-domain.com>/
