### ISSUE TITLE
[memcached] SASL not working?

### ISSUE THREAD

**Issue by tebaly** [bitnami/charts#8129]
**Which chart**:
memcached 5.15.8

**Describe the bug**
## Without SASL (worked)
```
memcached:
  replicaCount: 1
  fullnameOverride: "memcached"
```
**memcstat** From another pod
```
# memcstat --servers="memcached"
Server: memcached (11211)
         pid: 1
         uptime: 87
         time: 1636885171
         version: 1.6.12
         libevent: 2.1.8-stable
         pointer_size: 64
         rusage_user: 0.079362
```
## With SASL (not)

```
memcached:
  replicaCount: 1
  memcachedUsername: "user"
  memcachedPassword: "strongpass"
  fullnameOverride: "memcached"
```
**memcstat** From another pod

```
# memcstat --servers="memcached" --username=user --password=strongpass      
# echo $?
1
```
