### ISSUE TITLE
[memcached] extraEnv documented format

### ISSUE THREAD

**Issue by tebaly** [bitnami/charts#8130]
https://github.com/bitnami/charts/blob/63a63c2cc227622d64cc450567448346600b613e/bitnami/memcached/values.yaml#L103

NOT
```
    environment:
      - MEMCACHED_CACHE_SIZE=128
```
BUT
```
  extraEnv:
    - name: MEMCACHED_CACHE_SIZE
      value: "128"
```
Not obvious

**Comment by juan131** [comment]
Hi @tebaly 

Thanks so much for reporting this! We're in the process of standardizing our charts and soon this (and other charts) should follow the format below for adding extra env. vars:

```yaml
## @param extraEnvVars Array with extra environment variables to add to Memcached nodes
## e.g:
## extraEnvVars:
##   - name: FOO
##     value: "bar"
##
extraEnvVars: []
## @param extraEnvVarsCM Name of existing ConfigMap containing extra env vars for Memcached nodes
##
extraEnvVarsCM: ""
## @param extraEnvVarsSecret Name of existing Secret containing extra env vars for Memcached nodes
##
extraEnvVarsSecret: ""
```

Indeed, some chats already follow it, for instance check:

- https://github.com/bitnami/charts/blob/master/bitnami/geode/values.yaml#L368
