### ISSUE TITLE
I need an example in which Thanos with s3 integration and compacter and store-gateway components work normally.

### ISSUE THREAD

**Issue by HanHoRang** [bitnami/charts#8134]
**Which chart**:
The name (and version) of the affected chart.
Thanos 

**Is your feature request related to a problem? Please describe.**

Thanos is not properly distributed. Below is the setting value entered as a value in the helm thanos installation. 
(The access key and secret key will be hidden and shown.)
```
objstoreConfig: |-
  type: s3
  config:
    bucket: eksworkshop-metrics-s3storage #S3 bucket name
    endpoint: s3.us-west-2.amazonaws.com #S3 Regional endpoint
    access_key: <mykey>
    secret_key: <my secret key>    
    encryptsse: true
query:
  dnsDiscovery:
    sidecarsService: kube-prometheus-prometheus-thanos
    sidecarsNamespace: monitoring
bucketweb:
  enabled: true
compactor:
  enabled: true
storegateway:
  enabled: true
ruler:
  enabled: true
  alertmanagers:
    - http://kube-prometheus-alertmanager.monitoring.svc.cluster.local:9093
  config: |-
    groups:
      - name: "metamonitoring"
        rules:
          - alert: "PrometheusDown"
            expr: absent(up{prometheus="monitoring/kube-prometheus"})
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

**Describe the solution you'd like**

Using the helm chart, I need an example yaml file in which Thanos components under s3 work normally.

**Describe alternatives you've considered**

I like the link above my wanting solution, but I looked for it, but couldn't find it

**Additional context**
