### ISSUE TITLE
[bitnami/contour]: Conflicting default configuration envoy.containerSecurityContext.runAsUser: 1001, containerPort 80/443 

### ISSUE THREAD

**Issue by tricky42** [bitnami/charts#8162]
**Which chart**:
Chart Name: `bitnami/contour`
Chart Version: `7.0.1`

**Describe the bug**
Deploying `contour` using the default configuration results in `envoy` not accepting any requests :( This is result of the following conflicting default config: 

```
envoy:
  containerSecurityContext:
    runAsUser: 1001

  containerPorts:
    http: 80
    http: 445
```
https://github.com/bitnami/charts/blob/ae6305bb1f6c802f38e01af64add155a26620126/bitnami/contour/values.yaml#L584
https://github.com/bitnami/charts/blob/ae6305bb1f6c802f38e01af64add155a26620126/bitnami/contour/values.yaml#L733

**To Reproduce**

1. Create k3d cluster:
```
❯ k3d cluster create contour -p "8080:80@loadbalancer" -p "8443:443@loadbalancer" --k3s-arg="--disable=traefik@server:*"
```

2. Deploy Contour:
```
❯ helm upgrade --install contour bitnami/contour
```

3. Deploy Sample Workload:
```
❯ cat values-podinfo.yaml 
ingress:
  enabled: true
  hosts:
    - paths:
       - path: /
         pathType: ImplementationSpecific%

❯ helm upgrade --install podinfo podinfo/podinfo -f values-podinfo.yaml
```

4. Try to access workload
```
❯ curl http://localhost:8080 -vvv
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.77.0
> Accept: */*
> 
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```

5. Check `k3d-contour-serverlb`:
```
2021/11/16 17:45:40 [error] 51#51: *1811 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: 0.0.0.0:80, upstream: "172.27.0.3:80", bytes from/to client:0/0, bytes from/to upstream:0/0
```

**Expected behavior**
I can curl the podinfo page exposed via Ingress

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Reconfiguring the containerPorts resolves the issue: 
**values-contour.yaml**
```
envoy:
  useHostPort: false
  containerPorts:
    http: 10080
    https: 10443
    
```

Curl works now:
```
❯ curl http://localhost:8080 -vvv
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.77.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/json; charset=utf-8
< x-content-type-options: nosniff
< date: Tue, 16 Nov 2021 19:28:14 GMT
< content-length: 352
< x-envoy-upstream-service-time: 0
< vary: Accept-Encoding
< server: envoy
< 
{
  "hostname": "podinfo-6f8f87b4c5-6bz2v",
  "version": "6.0.3",
  "revision": "",
  "color": "#34577c",
  "logo": "https://raw.githubusercontent.com/stefanprodan/podinfo/gh-pages/cuddle_clap.gif",
  "message": "greetings from podinfo v6.0.3",
  "goos": "linux",
  "goarch": "amd64",
  "runtime": "go1.16.9",
  "num_goroutine": "8",
  "num_cpu": "8"
* Connection #0 to host localhost left intact
}%                                                                                                                                                                                          

```
