### ISSUE TITLE
[bitnami/contour]: Using the default config Contour will only reconcile httpproxy instances which explicitly specify ingressClassName: contour

### ISSUE THREAD

**Issue by tricky42** [bitnami/charts#8174]
**Which chart**:
Chart name: `contour`
Chart version: `7.0.2`

**Describe the bug**
Right now the `Contour` Helm chart default configuration includes 

``` 
contour:
  ingressClass: 
    name: contour
```
By explicitly setting `ingressClassName` to `contour` the Contour controller will only reconcile httpproxy instances which explicitly specify `ingressClassName: contour` , e.g.:

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  namespace: default
  name: ratelimited-podinfo
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: httpproxy.podinfo.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: podinfo
          port: 9898
```

See https://kubernetes.slack.com/archives/C8XRH2R4J/p1637098585136400?thread_ts=1637094538.135400&cid=C8XRH2R4J
 for more background info. 

**To Reproduce**

1. Install Contour with no custom configuration. 
2. Deploy a custom workload which should be exposed and create a HttpProxy instance without specifying an `ingressClassName` , e.g.:
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  namespace: default
  name: ratelimited-podinfo
spec:
  virtualhost:
    fqdn: httpproxy.podinfo.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: podinfo
          port: 9898
```          
3. Check the status of the HttpProxy instance (`kubectl describe httpproxy <name>`) and see that doesnt get reconciled and remains in `Waiting for controller state`
```
➜ k describe httpproxy              
Name:         ratelimited-podinfo
Namespace:    default
API Version:  projectcontour.io/v1
Kind:         HTTPProxy
...
Spec:
  Routes:
    Conditions:
      Prefix:  /
    Services:
      Name:  podinfo
      Port:  9898
  Virtualhost:
    Fqdn:  httpproxy.podinfo.com
Status:
  Current Status:  NotReconciled
  Description:     Waiting for controller
Events:            <none>
```

**Expected behavior**
An installation of Contour which doesnt specify explicitly an `ingressClassName` reconciles all HttpProxy instances, even if not `ingressClassName` has been included in the manifest.
Therefore all examples from the Contour documentation will work out of the box and users are not surprised by differences in behaviour between Contour instances deployed using the Helm Chart or any other methods described in the Contour documentation. 

**Version of Helm and Kubernetes**:
- Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
