### ISSUE TITLE
Using an ingress with mediawiki

### ISSUE THREAD

**Issue by marghidanu** [bitnami/charts#8182]
**Which chart**:
MediaWiki 12.4.1

**Describe the bug**
Trying to use an ingress (ingress-nginx) with a ClusterIP service sets the APP_HOST to 127.0.0.1

**To Reproduce**
See above.

**Expected behavior**
To work. With an ingress, the APP_HOST is already known.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by alvneiayu** [comment]
hi @marghidanu 

I am a little bit lost, why are you using 127.0.0.1? Did you follow the steps defined [here](https://github.com/bitnami/charts/tree/master/bitnami/mediawiki#to-1200)?

Thanks a lot

Álvaro

**Comment by marghidanu** [comment]
I’m not using 127.0.0.1, this value is automatically inferred by the helm chart when using a ClusterIP service.

**Comment by marghidanu** [comment]
Also, this is not an upgrade, this is a first install.

**Comment by alvneiayu** [comment]
hi @marghidanu 

Could you share with me the values that you are using to install the chart, please?

Thanks

Álvaro

**Comment by marghidanu** [comment]
@alvneiayu 

Here are the values used for configuring the chart, no need for the actual domain for testing. You can `curl` on the ingress IP and set the `Host` header to the domain configured for your ingress.

```
mediawikiUser: admin
mediawikiPassword: xxxxxxxxxxxx
allowEmptyPassword: no

mariadb:
  enabled: true
  auth:
    rootPassword: xxxxxxxxxxx
    database: "mediawiki"
    username: "mediawiki"
    password: xxxxxxxxxxx

service:
  type: NodePort

ingress:
  enabled: true
  hostname: mydomain.com
  pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: nginx

```
