### ISSUE TITLE
[Keycloak] Ingress returns 502 after enabling auth.tls

### ISSUE THREAD

**Issue by ampc** [bitnami/charts#8198]
**Which chart**:
keycloak-5.1.5

**Describe the bug**
Ingress returns 502 Bad Gateway after enabling auth.enabled.

**To Reproduce**

1. Change **auth.tls.enabled** to **true**
2. Ingress returns 502

**Expected behavior**
I've enabled auth.tls because I think this is required in order to use keystores, and I'm using these jks to connect to LDAPS servers on user federation. Before enabling this option, the ingress was working fine.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

**Additional context**
values.yaml
```yaml
extraEnvVars:
  - name: KEYCLOAK_EXTRA_ARGS
    value: "-Dkeycloak.frontendUrl=https://keycloak.apps.example.com/auth/"
proxyAddressForwarding: true
ingress:
  ingressClassName: "private"
  enabled: true
  tls: true
  servicePort: "https"
  hostname: "keycloak.apps.example.com"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  existingSecret: "cert-tls"
service:
  type: ClusterIP
auth:
  tls:
    enabled: true
    existingSecret: keycloak-jks
    keystorePassword: changeit
    truststorePassword: changeit
```

**Comment by Mauraza** [comment]
Hi @ampc,

Could you share the logs of the error?

**Comment by ampc** [comment]
Hello @Mauraza 

nginx logs
```bash
ingress-nginx-controller-69tk9 controller 2021/11/22 14:05:17 [error] 2590#2590: *7955978 SSL_do_handshake() failed (SSL: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:SSL alert number 40) while SSL handshaking to upstream, client: 10.92.137.187, server: keycloak.apps.cnap-staging.eu-central-1.aws.cloud.acme123, request: "GET /auth/admin/master/console/ HTTP/1.1", upstream: "https://192.168.17.227:8443/auth/admin/master/console/", host: "keycloak.apps.cnap-staging.eu-central-1.aws.cloud.acme123"
ingress-nginx-controller-69tk9 controller 2021/11/22 14:05:17 [error] 2590#2590: *7955978 SSL_do_handshake() failed (SSL: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:SSL alert number 40) while SSL handshaking to upstream, client: 10.92.137.187, server: keycloak.apps.cnap-staging.eu-central-1.aws.cloud.acme123, request: "GET /auth/admin/master/console/ HTTP/1.1", upstream: "https://192.168.17.227:8443/auth/admin/master/console/", host: "keycloak.apps.cnap-staging.eu-central-1.aws.cloud.acme123"
ingress-nginx-controller-69tk9 controller 2021/11/22 14:05:17 [error] 2590#2590: *7955978 SSL_do_handshake() failed (SSL: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:SSL alert number 40) while SSL handshaking to upstream, client: 10.92.137.187, server: keycloak.apps.cnap-staging.eu-central-1.aws.cloud.acme123, request: "GET /auth/admin/master/console/ HTTP/1.1", upstream: "https://192.168.17.227:8443/auth/admin/master/console/", host: "keycloak.apps.cnap-staging.eu-central-1.aws.cloud.acme123"
ingress-nginx-controller-69tk9 controller 10.92.137.187 - - [22/Nov/2021:14:05:17 +0000] "GET /auth/admin/master/console/ HTTP/1.1" 502 552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36" 884 0.045 [antonio-keycloak-keycloak-https] [] 192.168.17.227:8443, 192.168.17.227:8443, 192.168.17.227:8443 0, 0, 0 0.008, 0.008, 0.032 502, 502, 502 2341c7b1a9c4c1c9d6540ec0ebfba0cd
```

**Comment by Mauraza** [comment]
Hi @ampc,

Could you try with these values 🔽 to check if the error is related to the certificate?
```yaml
extraEnvVars:
  - name: KEYCLOAK_EXTRA_ARGS
    value: "-Dkeycloak.frontendUrl=https://keycloak.apps.example.com/auth/"
proxyAddressForwarding: true
ingress:
  ingressClassName: "private"
  enabled: true
  tls: true
  servicePort: "https"
  hostname: "keycloak.apps.example.com"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
service:
  type: ClusterIP
auth:
  tls:
    enabled: true
    autoGenerated: true
```
