### ISSUE TITLE
Expose nats with ingress controller

### ISSUE THREAD

**Issue by giorgosnty** [bitnami/charts#8205]
**Which chart**:
bitnami/nats 6.6.1

**Describe the bug**
I'd like to deploy nats in my Kubernetes cluster and expose it using an ingress controller. 

**To Reproduce**
1. Install bitnami/nats using 
```helm install my-release bitnami/nats```
2. Create ingress using the following yaml file
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-controller
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
spec:
  tls: 
  - hosts: 
    - NATS_DOMAIN
    secretName: secret
  rules:
  - host: NATS_DOMAIN
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: nats-client
            port:
              number: 4222
```

**Expected behavior**
I expected for the nats to be reachable. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3-gke.2003", GitCommit:"b6a837065c60b193d0d31a818a0d52718b3bbcd1", GitTreeState:"clean", BuildDate:"2021-10-21T21:32:02Z", GoVersion:"go1.16.6b7", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
If I port forward, everything else is working and I can connect to NATS, so the only problem is the service being unreachable.
