### ISSUE TITLE
[bitnami/keycloak] upgrading to chart v5.0.4 breaks externalSecret name ref for postgresql password (using argocd)

### ISSUE THREAD

**Issue by Carus11** [bitnami/charts#8208]
**Which chart**:
bitnami/keycloak chart version 5.0.4

**Describe the bug**
I am deploying bitnami/keycloak using **ArgoCD**, In keycloak chart v 5.0.1 I have existingSecret configured and working:
```yaml
  auth:
    existingSecret:
      name: keycloak-secrets
      keyMapping:
        admin-password: ADMIN_PASSWORD
        management-password: MGMT_PASSWORD
        database-password: DB_PASSWORD
        tls-keystore-password: TLS_KEYSTORE_PASSWORD
        tls-truststore-password: TLS_TRUSTSTORE_PASSWORD
```

The secrets are correctly mapped to the pod (image from lens):
![image](https://user-images.githubusercontent.com/4925828/142857895-b461934a-e4a4-4b0d-a760-d296506d2f8b.png)

however during the upgrade to chart version 5.0.4 the logic that chooses the secret name for the database appears to have been altered, as it does not use the secret I have created with the correct value (image from lens):
![image](https://user-images.githubusercontent.com/4925828/142858054-47ad3a2b-2efd-4362-9e30-9704d065893f.png)

**To Reproduce**
Using ArgoCD:
1. Deploy chart 5.0.1 with externalSecrets configured
2. Update to chart 5.0.4 with externalSecrets configured

**Expected behavior**
Expect the external secret name to be the one defined in the values.yaml file

**Additional context**

**Comment by Carus11** [comment]
It looks like the functionality I expect was last visible in in this revision:
https://github.com/bitnami/charts/blob/f4ec593e3e37d0332aae3d14c928536926f96695/bitnami/keycloak/templates/statefulset.yaml#L215

But then was changed in this commit:
https://github.com/bitnami/charts/commit/3884536a4d28fae3682f56954958a0fbde5134ad

**Comment by migruiz4** [comment]
Hi @Carus11,

This issue is a duplicate of https://github.com/bitnami/charts/issues/7794, which has been resolved in version 5.1.5 of the Keycloak chart https://github.com/bitnami/charts/pull/7863.

Upgrading to version 5.1.5 or higher should fix the issue.

**Comment by Carus11** [comment]
Thanks for the reply @migruiz4 I actually first tried to upgrade to 5.2.0 and had the same issue, it is not picking up the secret. I only then tried to narrow it down to the release that broke.

In #7794 is it saying the key changed in the mapper? I am using the documentation as my guide on how to configure this: https://docs.bitnami.com/kubernetes/apps/keycloak/configuration/manage-passwords/

**Comment by Carus11** [comment]
I just updated to 5.1.5 and its still not pulling in the secret name and key from the mapper, its working for the other secrets but not the database-password.

A small difference from #7794 is this is for not an external postgresql. I just wanted to provide a password on initial installation that wasnt `some-password`

The vars and values from:
```yaml
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: ADMIN_PASSWORD
                  name: keycloak-secrets
            - name: KEYCLOAK_MANAGEMENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MGMT_PASSWORD
                  name: keycloak-secrets
            - name: KEYCLOAK_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresql-password
                  name: nonprod-blue-keycloak-postgresql
```

The mapper in values.yml
```yaml
  auth:
    existingSecret:
      name: keycloak-secrets
      keyMapping:
        admin-password: ADMIN_PASSWORD
        management-password: MGMT_PASSWORD
        database-password: DB_PASSWORD
        tls-keystore-password: TLS_KEYSTORE_PASSWORD
        tls-truststore-password: TLS_TRUSTSTORE_PASSWORD
```
