### ISSUE TITLE
ingress config multiline

### ISSUE THREAD

**Issue by fbacker** [bitnami/charts#8212]
**Which chart**:
bitnami/nginx-ingress-controller 9.0.7

**Describe the bug**

Using multiline in config will make it "single line with \n breaks"

**To Reproduce**

1. In values.yaml
```yaml
config:
  use-forwarded-headers: "true"
  http-snippet: |-
    server {
      listen 18080;

      set $proxy_upstream_name "internal";

      access_log off;

      opentracing off;

      location /nginx_status {
        allow all;
        stub_status on;
      }

      location / {
        return 404;
      }
    }      
```
2. Generate output ```helm template ingress bitnami/nginx-ingress-controller -n ingress-nginx -f ./values.yaml  > ./manifests.yaml```
3. Look at configmap ingress-nginx-ingress-controller
4. configmap
```yaml
data:
  http-snippet: "\nserver {\n  listen 18080;\n\n  set $proxy_upstream_name \"internal\";\n\n
    \ access_log off;\n\n  opentracing off;\n\n  location /nginx_status {\n    allow
    all;\n    stub_status on;\n  }\n\n  location / {\n    return 404;\n  }\n}      "
  use-forwarded-headers: "true"
```

**Expected behavior**

The http-snippet should keep the multiline format. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}```
```
