### ISSUE TITLE
ingress custom tcp ports, no access thru nodeport service

### ISSUE THREAD

**Issue by fbacker** [bitnami/charts#8232]
**Which chart**:
bitnami/nginx-ingress-controller: 9.0.8

**Describe the bug**
When adding custom tcp ports they wont work when using Service.

example the values
```yaml
tcp:
  18080: "datadog"
  10254: "metrics"

service:
  type: "NodePort"
  nodePorts:
    http: 30080
    https: 30443
    tcp:
      10254: 30254 # Expose metrics nodeport 30254
```

will create manifest
```yaml
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      nodePort: 30080
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      nodePort: 30443
    - name: 10254-tcp
      port: 10254
      protocol: TCP
      targetPort: 10254-tcp
      nodePort: 30254
    - name: 18080-tcp
      port: 18080
      protocol: TCP
      targetPort: 18080-tcp
```

When trying to access e.g. 10254-tcp and browse to /metrics it won't work.

If I change the name ```10254-tcp``` to ```10254tcp``` on ```Service``` and ```Deployment``` it works.

**Suggestion:*** change the generated name to not use the character -

**To Reproduce**

1. create values.yaml
```yaml
watchIngressWithoutClass: true

config:
  http-snippet: |-
    server {
      listen 18080;

      location /nginx_status {
        allow all;
        stub_status on;
      }

      location / {
        return 404;
      }
    }

tcp:
  18080: "datadog"
  10254: "metrics"

service:
  type: "NodePort"
  nodePorts:
    http: 30080
    https: 30443
    tcp:
      10254: 30254 # Expose metrics nodeport 30254

podAnnotations:
  ad.datadoghq.com/controller.logs: |
    [{"service": "ingress-controller-internal", "source": "nginx-ingress-controller", "env": "testing"}]
  ad.datadoghq.com/controller.check_names: |
    ["nginx","nginx_ingress_controller"]
  ad.datadoghq.com/controller.init_configs: |
    [{},{}]
  ad.datadoghq.com/controller.instances: |
    [{"nginx_status_url": "http://%%host%%:18080/nginx_status"},{"prometheus_url": "http://%%host%%:10254/metrics"}]
  
```
2. Generate manifest ```helm template ingress bitnami/nginx-ingress-controller -n ingress-nginx -f ./values.yaml  > ./manifests.yaml```
3. deploy to kubernetes
4. Access service nodeport 30254 with /metrics

**Expected behavior**
The ingress should allow me to use the extra tcp ports and show me the metrics data

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```
