### ISSUE TITLE
bitnami/kafka:2.8.1-debian-10-r31 Unable to create multiple replicas using multiple PVs

### ISSUE THREAD

**Issue by racheldaguenethahn** [bitnami/charts#8280]
Hi,

I'm trying to deploy Kafka with 3 replicas for Kafka and 3 replicas for zookeeper.
Each replica must be deployed on different nodes.
Each replica must use a different PV.

PVs are existing and have a label "kafka-pv" or "zookeeper-pv"
```
NAME                 CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                           STORAGECLASS   REASON   AGE
kafka-pv-01          100Gi      RWO            Retain           Available                         disk                    16h
kafka-pv-02          100Gi      RWO            Retain           Available                         disk                    16h
kafka-pv-03          100Gi      RWO            Retain           Available                         disk                    16h
zookeeper-pv-01      20Gi       RWO            Retain           Available                         disk                    16h
zookeeper-pv-02      20Gi       RWO            Retain           Available                         disk                    16h
zookeeper-pv-03      20Gi       RWO            Retain           Available                         disk                    16h
```

Kafka values:

```
replicaCount: 3
image:
  tag: 2.8.1-debian-10-r31
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      mev-pvname: kafka-pv
volumePermissions:
  enabled: true
  image:
    tag: 10-debian-10-r234

zookeeper:
  enabled: true
  image:
    tag: 3.7.0-debian-10-r188
  replicaCount: 3
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    selector:
      matchLabels:
        mev-pvname: zookeeper-pv
  volumePermissions:
    enabled: true
    image:
      tag: 10-debian-10-r234
```

When deploying the chart, the PVCs are created

```
NAME                     STATUS   VOLUME            CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-kafka-0             Bound    kafka-pv-02       100Gi      RWO            disk           23m
data-kafka-1             Bound    kafka-pv-01       100Gi      RWO            disk           23m
data-kafka-2             Bound    kafka-pv-03       100Gi      RWO            disk           23m
data-kafka-zookeeper-0   Bound    zookeeper-pv-01   20Gi       RWO            disk           23m
data-kafka-zookeeper-1   Bound    zookeeper-pv-02   20Gi       RWO            disk           23m
data-kafka-zookeeper-2   Bound    zookeeper-pv-03   20Gi       RWO            disk           23m
```

But the pods failed to initialize
```
NAME                READY   STATUS     RESTARTS   AGE
kafka-0             0/1     Init:0/1   0          46m
kafka-1             0/1     Init:0/1   0          46m
kafka-2             0/1     Init:0/1   0          46m
kafka-zookeeper-0   0/1     Init:0/1   0          46m
kafka-zookeeper-1   0/1     Init:0/1   0          46m
kafka-zookeeper-2   0/1     Init:0/1   0          46m
```

Output for kafka-0 pod
```
Events:
  Type     Reason            Age                  From                                                    Message
  ----     ------            ----                 ----                                                    -------
  Warning  FailedScheduling  47m (x2 over 47m)    default-scheduler                                       pod has unbound immediate PersistentVolumeClaims (repeated 7 times)
  Normal   Scheduled         46m                  default-scheduler                                       Successfully assigned kernel/kafka-0 to cn-hangzhou-zwynet-d01.i-i5c01jju8khobdm73gq0
  Warning  FailedMount       111s (x20 over 44m)  kubelet, cn-hangzhou-zwynet-d01.i-i5c01jju8khobdm73gq0  Unable to mount volumes for pod "kafka-0_kernel(9d731769-528d-11ec-bb86-00163e010382)": timeout expired waiting for volumes to attach or mount for pod "kernel"/"kafka-0". list of unmounted volumes=[data]. list of unattached volumes=[data scripts logs kafka-token-t8vkf]
```
