### ISSUE TITLE
[bitnami/argo-cd] Using customReadinessProbe in argo-cd chart renders invalid k8s yaml

### ISSUE THREAD

**Issue by cjoster** [bitnami/charts#8284]
**Which chart**: argo-cd (~~but apparently airflow is also affected~~)

**Describe the bug**
When overriding the builtin readinessProbe in dex using the customReadninessProbe, using the following values.yaml: 

```yaml
dex:
  enabled: true
  livenessProbe:
    enabled: false
  customLivenessProbe:
    exec:
      command:
      - /bin/true
  readinessProbe:
    enabled: false
  customReadinessProbe:
    exec:
      command:
      - /bin/true
```

the chart renders the following invalid yaml (note the lack of a handler for the readiness probe):

```yaml
          livenessProbe:
            exec:
              command:
              - /bin/true
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
```

And, as would be expected, k8s complains about it upon deployment:

```
Error: INSTALLATION FAILED: Deployment.apps "overridden-argocd-argo-cd-dex" is invalid: spec.template.spec.containers[0].readinessProbe: Required value: must specify a handler type
```

**To Reproduce**

1. Create a minimal values.yaml:

```bash
cat > values.yaml << EOF
dex:
  enabled: true
  livenessProbe:
    enabled: false
  customLivenessProbe:
    exec:
      command:
      - /bin/true
  readinessProbe:
    enabled: false
  customReadinessProbe:
    exec:
      command:
      - /bin/true
EOF
```

2. `helm template bitnami/argo-cd --version 2.0.12 -f values.yaml`
3. Scroll down to line 1115
4. Observe the lack of handler for the readinessProbe (note the livenessProbe overrides just fine)

**Expected behavior**
readinessProbe should render the same way the livenessProbe does.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
N/A
```
