### ISSUE TITLE
[bitnami/airflow] ElacticSearch write_stdout

### ISSUE THREAD

**Issue by eclipsetalk** [bitnami/charts#8293]
Hello,
I'm using airflow tag: 2.2.2-debian-10-r7 - I need to setup elasticsearch _write_stdout_ to true. When I set it in the chart as follow it has no effect:

```
elasticsearch:
  write_stdout: true
  json_format: true
  log_id_template: "{dag_id}_{task_id}_{execution_date}_{try_number}"
  json_fields: asctime, filename, lineno, levelname, message
```

I edited the airflow.cfg to set the values, I stopped and restarted airflow. The settings were updated until airflow restarted, then the settings reverted to defaults.
Can I use an env variables to set the write_stdout, and why isn't it working when set in the value.yaml file?

Thanks!

**Comment by rafariossaa** [comment]
Hi,
  I am not very sure if I am understanding you correctly. 
  Is your issue that you are trying to set your own `airflow.cfg` ? Not very sure of how you are setting it in the values.yaml

**Comment by eclipsetalk** [comment]
Hi @rafariossaa,
The airflow.cfg is configured when I install the helm chart but when I check the airflow.cfg after installing the helm chart the elasticsearch values are not set. Below is the elasticsearch section in the helm chart I have defined:

```
elasticsearch:
  write_stdout: true
  json_format: true
  log_id_template: "{dag_id}_{task_id}_{execution_date}_{try_number}"
  json_fields: asctime, filename, lineno, levelname, message
```

Then I tried to manually update the airflow.cfg values but it gets overwritten once the web server restarts. 
The issue is that I can't set the write_stdout to True via the helm chart
