### ISSUE TITLE
Need approaches to set multiple keys/values for nodeAffinityPreset.

### ISSUE THREAD

**Issue by huxuan** [bitnami/charts#8294]
**Which chart**:
The name (and version) of the affected chart

bitnami/airflow 11.1.9

**Describe the bug**

How to set multiple nodeAffinityPreset?

**To Reproduce**

Tried list of `nodeAffinityPreset` and list of values for `nodeAffinityPreset` but both failed.

For example,

```
nodeAffinityPreset:
  - key: key1
    type: hard
    values: [value1]
  - key: key2
    type: hard
    values: [value2]
```

**Expected behavior**

```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: key1
                operator: In
                values:
                - value1
              - key: key2
                operator: In
                values:
                - value2
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
