### ISSUE TITLE
"/bitnami/python" not a directory

### ISSUE THREAD

**Issue by zhemingdeng** [bitnami/charts#8308]
**Which chart**:
airflow

**Describe the bug**
When using configmap to mount a requirements.txt to path /bitnami/python/, the deploy failed and returns
Error: failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/var/lib/kubelet/pods/eca19057-559f-4cf8-bf97-7d28dc28b864/volume-subpaths/cm-requirements-file-volume/airflow-web/1" to rootfs at "/run/containerd/io.containerd.runtime.v1.linux/k8s.io/airflow-web/rootfs/bitnami/python" caused: not a directory: unknown 

**To Reproduce**

Using extravolumemount and configmap to mount a requirements.txt file to airflow's /bitnami/python directory

**Expected behavior**
the python package installed

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**
values.yaml (extraVolume and extraVolumemount)
```
  extraVolumeMounts:
    - name: cm-requirements-file-volume
      mountPath: /bitnami/python
      subPath: requirements.txt
  extraVolumes:
    - name: cm-requirements-file-volume
      configMap:
        name: cm-requirements-file
```

configmap
```
apiVersion: v1
kind: ConfigMap
metadata: 
  name: cm-requirements-file
data:
  requirements.txt: |-
    apache-airflow[google_auth]
    snowflake-connector-python

```
