### ISSUE TITLE
Thanos grpc.server.tls.autoGenerated doesn't work

### ISSUE THREAD

**Issue by Vladyslav-Miletskyi** [bitnami/charts#8322]
**Which chart**:
thanos
versions >8.0.0

**Describe the bug**
When setting `storegateway.grpc.server.tls.autoGenerated` component could not start

```yaml
component:
  grpc:
    server:
      tls:
        enabled: true
        autoGenerated: true
```

A component doesn't start.
Component log: `open /certs/ca-cert: no such file or directory`

Component deployment:

```yaml
...
- args:
    - store
    - --log.level=info
    - --log.format=logfmt
    - --grpc-address=0.0.0.0:10901
    - --http-address=0.0.0.0:10902
    - --data-dir=/data
    - --objstore.config-file=/conf/objstore.yml
    - --index-cache.config-file=/conf/index-cache.yml
    - --grpc-server-tls-cert=/certs/tls-cert
    - --grpc-server-tls-key=/certs/tls-key
    - --grpc-server-tls-client-ca=/certs/ca-cert
```

Secret content

```
data:
  ca.crt: ...
  tls.crt: ...
  tls.key: ...
```

**Expected behavior**
Component started with gRPC TLS enabled.
