### ISSUE TITLE
How to use redis-cluster configmap?

### ISSUE THREAD

**Issue by AsoTora** [bitnami/charts#8324]
**chart**:
Redis-cluster 

**Describe the bug**
Do not understand how to specify configmap properly.  Comment [here](https://github.com/bitnami/charts/blob/04a144858cd35140aeb75a715dc1281887819055/bitnami/redis-cluster/values.yaml#L159) doesn't really provide a valuable example.

I just want my config to have let's say `maxmemory-policy "allkeys-lru"`

**Version of Chart**:

```
CHART VERSION: 7.0.12
```

**Additional context**
Would be nice to have it in a README.

**Comment by AsoTora** [comment]
Figured it out eventually, here is the example:

```yaml
redis: 
  configmap: |
    maxmemory 4Gb
    maxmemory-policy allkeys-lru
```

Hence, this can be closed, i suppose.

**Comment by AsoTora** [comment]
Figured it out eventually, here is the example:

```yaml
redis: 
  configmap: |
    maxmemory 4Gb
    maxmemory-policy allkeys-lru
```

Hence, this can be closed, i suppose.
