### ISSUE TITLE
MongoDB install on Azure fail to mount PVC

### ISSUE THREAD

**Issue by ognif** [bitnami/charts#8343]
**Which chart**:
bitnami/MongoDB version 10.6.1

**Describe the bug**
I use in my helm chart the bitnami mongodb helm chart as subchart.
I use the following values:
````
mongodb:
  enabled: true
  global:
    storageClass: managed-premium
  auth:
    enabled: false
  architecture: replicaset 
  useStatefulSet: true 
  arbiter:
    enabled: false
  replicaCount: 1 
  persistence:
    enabled: true
    storageClass: managed-premium
    mountPath: /bitnami/mongodb
    size: 10Gi
  volumePermissions: 
    enabled: true 
  service:
    port: 27017
````

In our own cluster it works well (we use storageClass: longhorn there).
In Azure I got always the message:

````
Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[scripts myapp-mongodb-token-cmxln datadir]: timed out waiting for the condition
````

This comes right after:
````
AttachVolume.Attach succeeded for volume "pvc-8518ae55-7763-4d96-aa31-0c890bcb83e0"
````

**Expected behavior**
Work with the same settings inside the cluster and in Azure.

**Version of Helm and Kubernetes**:

version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

```
Release "myapp" has been upgraded. Happy Helming!
NAME: myapp
LAST DEPLOYED: Wed Dec  8 20:41:00 2021
NAMESPACE: myapp-demo
STATUS: deployed
REVISION: 21
TEST SUITE: None
```
