### ISSUE TITLE
[bitnami/airflow] LDAP error - group is not defined

### ISSUE THREAD

**Issue by chapai518** [bitnami/charts#8345]
**Which chart**:
[bitnami/airflow] 11.1.8

**Describe the bug**
When you enable LDAP, the Web container does not start.

**To Reproduce**
1. I make the settings in the variables:
```
...
ldap:
  enabled: true
  uri: 'ldap://dc.domain.com:389'
  base: 'dc=domain,dc=com'
  uidField: 'sAMAccountName'
  binddn: 'cn=LDAP_user,ou=Service Accounts,dc=domain,dc=com'
  bindpw: 'password'
  userRegistration: 'True'
  userRegistrationRole: 'Public'
  rolesMapping: '{ "cn=developers,ou=Groups,dc=domain,dc=com": ["User"], "cn=admins,ou=Groups,dc=domain,dc=com": ["Admin"], }'
  rolesSyncAtLogin: 'True'
  tls:
    enabled: false
    allowSelfSigned: true
...
```

2. I deploy to openshift (4.7.37)
3. Web container crashes with an error
```
AUTH_TYPE = AUTH_LDAP 
NameError: name 'AUTH_LDAP' is not defined
```

4. Googled, found it fixed in newer versions of the container. Fixed the name of the image  `2.2.2-debian-10-r0` to `2.2.2-debian-10-r8`
5.There were syntax errors after deployment

```
    AUTH_LDAP_SERVER = ldap://dc.domain.com:389
                          ^
SyntaxError: invalid syntax
```

```
    AUTH_LDAP_BIND_USER = cn=LDAP_user,ou=Service Accounts,dc=domain,dc=com
                                                 ^
SyntaxError: invalid syntax

```
6. Both errors are eliminated by enclosing the content in " quotes.
7. The next error appeared

```
    AUTH_USER_REGISTRATION_ROLE = Public
NameError: name 'Public' is not defined
```

8. Tried inserting groups Admin and User instead of Public, but the errors are similar. 

**Expected behavior**
Correct operation of LDAP authorization

**Version of Helm and Kubernetes**:
Helm v3.7.1
OpenShift 4.7.37 (Kubernetes v1.20.10)

**Additional context**
If I disable LDAP in variables and connect a third-party configmap with the webserver_config.py file in which the LDAP settings are made manually, then everything works correctly.

**Comment by juan131** [comment]
Hi @chapai518 

Thanks so much for reporting these issues with LDAP. I just created a PR that addresses several of them that are related to unquoted values.

Starting at this point, let's figure out how to address the rest of the issues.

**Comment by chapai518** [comment]
I tried to put the 2.2.2-debian-10-r9 web image, but it didn't help.
Experimentally I found how to start the web, for this, in the deployment by hand, you need to put double quotes for the fields:
AIRFLOW_LDAP_URI
AIRFLOW_LDAP_SEARCH
AIRFLOW_LDAP_UID_FIELD
AIRFLOW_LDAP_BIND_USER
And also the quotes in the body of the password are secret
airflow-ldap

![image](https://user-images.githubusercontent.com/63089139/145770041-9fc22b09-9f51-40ad-b4cc-faa72b43098a.png)


In this case, the pod is launched, without errors, but the authorization does not work, the variables in the pod show all the results with quotes, which apparently interferes with the normal operation of the LDAP.

That is, it does not start without quotes, and does not work with quotes.
Vicious circle :)

If I write the same variables to the webserver_config.py file
and I import it through the configmap, then LDAP authorization works.

**Comment by juan131** [comment]
Hi @chapai518 

Did you try using the Bitnami Airflow Chart version `11.1.11` and **without** including the single quotes in the `values.yaml`?

```yaml
...
ldap:
  enabled: true
  uri: ldap://dc.domain.com:389
  base: dc=domain,dc=com
  uidField: sAMAccountName
  binddn: cn=LDAP_user,ou=Service Accounts,dc=domain,dc=com
  bindpw: password
  userRegistration: True
  userRegistrationRole: Public
  rolesMapping: '{ "cn=developers,ou=Groups,dc=domain,dc=com": ["User"], "cn=admins,ou=Groups,dc=domain,dc=com": ["Admin"], }'
  rolesSyncAtLogin: True
  tls:
    enabled: false
    allowSelfSigned: true
...
```

**Comment by chapai518** [comment]
After your message, I have completely updated the chart.
I tried not to specify quotation marks according to your example, the errors are the same.
The only thing missing is the error with the AUTH_LDAP_SERVER field,
If I manually make quotes for this, then in the logs I swear at the syntax:
  File "/opt/bitnami/airflow/webserver_config.py", line 92
    AUTH_LDAP_SERVER = ''ldap: //dc.domain.com: 3268''  (2 single quotes)
                         ^
SyntaxError: invalid syntax

For other parameters, errors without quotation marks are the same as with single ones, for example:
  File "/opt/bitnami/airflow/webserver_config.py", line 133, in <module>
    AUTH_LDAP_BIND_PASSWORD = pass
NameError: name 'pass' is not defined

  File "/opt/bitnami/airflow/webserver_config.py", line 130, in <module>
    AUTH_LDAP_SEARCH = dc=ural,dc=evraz,dc=com
NameError: name 'com' is not defined

But everything works if I manually prescribe it in the ENV like this:
![image](https://user-images.githubusercontent.com/63089139/145793111-0e3102e7-8100-450d-b516-e574677073dd.png)
And I add single swings to the password body.

Or in the manifest
base: "'''dc=domain,dc=com'''"
  uidField: "'''sAMAccountName'''"
  binddn: "'''cn=LDAP_user,ou=Service Accounts,dc=domain,dc=com'''"
  bindpw: "'''pass'''"
  userRegistration: 'True'
  userRegistrationRole: 'Admin'
  rolesMapping: '{ "cn=developers,ou=Groups,dc=domain,dc=com": ["User"], "cn=admins,ou=Groups,dc=domain,dc=com": ["Admin"], }'
  rolesSyncAtLogin: 'True'

**Comment by juan131** [comment]
Hi @juan131 

I don't think that all these single/double quotes.. What version of the Bitnami Airflow chart are you using? Is it `11.1.11`?

**Comment by chapai518** [comment]
Yes
![image](https://user-images.githubusercontent.com/63089139/146176511-f2884c2b-73a4-4ca7-81fa-292b5139b2fa.png)

**Comment by juan131** [comment]
Hi @chapai518 

I've been checking it and the unique values that requires single quotes are `ldap.userRegistration` and `ldap.rolesSyncAtLogin` (so the values are evaluated as strings instead of booleans) and `ldap.rolesMapping` (so it's evaluated a string instead of a map`). For instance:

```yaml
ldap:
  enabled: true
  uri: ldap://dc.domain.com:389
  base: dc=domain,dc=com
  uidField: sAMAccountName
  binddn: cn=LDAP_user,ou=Service Accounts,dc=domain,dc=com
  bindpw: password
  userRegistration: 'True'
  userRegistrationRole: Public
  rolesMapping: '{ "cn=users,ou=readers,dc=example,dc=org": ["User"], "cn=admin,dc=example,dc=org": ["Admin"], }'
  rolesSyncAtLogin: 'True'
  tls:
    enabled: false
```
