### ISSUE TITLE
[bitnami/moodle] Ingress TLS Secretname parameter ignored

### ISSUE THREAD

**Issue by weiserhei** [bitnami/charts#8348]
Hello,
Im using the Moodle Chart and trying to set a custom Ingress TLS Secretname as shown in the readme Example:

```yaml
ingress:
  tls:
    secretName: <my-secretname>
```
https://github.com/bitnami/charts/blob/master/bitnami/moodle/README.md?plain=1#L348

But this name is ignored because secrets are created like

```yaml
secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
```
https://github.com/bitnami/charts/blob/master/bitnami/moodle/templates/ingress.yaml#L53

I work around by naming my secrets as they are expected to be named and ignoring the config parameter.

**Comment by juan131** [comment]
Hi @weiserhei 

What version of the chart are you using? Please ensure you update your chart repository:

```
helm repo update
```

Then try using the **values.yaml** below:

```yaml
ingress:
  tls: false 
  extraTls:
    - hosts:
        - minio.foo.bar
      secretName: minio-secret-name
```

Find more info in the link below:

- https://github.com/bitnami/charts/blob/master/bitnami/moodle/values.yaml#L435
