### ISSUE TITLE
bitnami/grafana

### ISSUE THREAD

**Issue by stephaneetje** [bitnami/charts#8359]
Grafana latest version chart:

The param `grafana.extraEnvVars` has no effect. Verified with helm template :

```yaml
grafana:
  extraEnvVars:
    - name: GF_SERVER_DOMAIN
      value: "test-kube.test.cc"
    - name: GF_SERVER_ROOT_URL
      value: "https://test-kube.test.cc"
```

According to the deployment template, it should load those var in it, but it is not. 

Here is the `helm template` with these values :

```yaml
# Source: grafana/charts/grafana/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    helm.sh/chart: grafana-7.2.9
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: RELEASE-NAME
      app.kubernetes.io/component: grafana
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        helm.sh/chart: grafana-7.2.9
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: grafana
      annotations:
        checksum/secret: 11772b98aefbfba843990c10b96d5d125aec8001f5701fd58cbd04a9b049e155
        checksum/config: 567f7a4b22b3b92338d254cdc0bd02265f52420aa591386c949fc159d3af6ab0
        checksum/dashboard-provider: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
    spec:

      serviceAccountName: RELEASE-NAME-grafana
      affinity:
        podAffinity:

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: grafana
                    app.kubernetes.io/instance: RELEASE-NAME
                    app.kubernetes.io/component: grafana
                namespaces:
                  - "monitoring"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:

      securityContext:
        runAsUser: 1001
        fsGroup: 1001
        runAsNonRoot: true
      initContainers:
      containers:
        - name: grafana
          image: docker.io/bitnami/grafana:8.3.1-debian-10-r0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1001
          envFrom:
            - configMapRef:
                name: RELEASE-NAME-grafana-envvars
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: RELEASE-NAME-grafana-admin
                  key: GF_SECURITY_ADMIN_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /opt/bitnami/grafana/data
          ports:
            - name: dashboard
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: dashboard
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /api/health
              port: dashboard
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          resources:
            limits: {}
            requests: {}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: RELEASE-NAME-grafana
```
