### ISSUE TITLE
[rabbitmq] Supports read-only file system

### ISSUE THREAD

**Issue by ruinshe** [bitnami/charts#8379]
**Which chart**:

rabbitmq, with chart version `8.24.11` and app version `3.9.11`

**Is your feature request related to a problem? Please describe.**

In order to make the Pods more safe, I'm working on setting some security rules (e.g. setup security context for the Pods), and I figure out that rabbitmq is not easy to support read only file system for containers.

**Describe the solution you'd like**

Providing a option in the `values.yaml` or a simple solution guide for how-to are both OK for me.

**Describe alternatives you've considered**

N/A

**Additional context**

I tried to add some folder modified by the `bitnami/rabbitmq` image using emptyDir to bypass the read only file system issue, but finally stuck at erlang cookie file modifying (the application will try to write erlang cookie file into a folder which is not empty so I can't mount the folder as emptyDir).

Currently I tried to add some basic configurations like:

```yaml
nodeSelector:
  # ...
persistence:
  existingClaim: the-claim-manually-created
containerSecurityContext:
  capabilities:
    drop:
      - ALL
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
extraVolumeMounts:
  - mountPath: /tmp
    name: tmp
  - mountPath: /opt/bitnami/rabbitmq/etc/rabbitmq
    name: rabbitmq-etc
  - mountPath: /opt/bitnami/rabbitmq/var/lib/rabbitmq/
    name: rabbitmq-var
extraVolumes:
  - name: tmp
    emptyDir: {}
  - name: rabbitmq-etc
    emptyDir: {}
  - name: rabbitmq-var
    emptyDir: {}
```

**Comment by alemorcuq** [comment]
> I tried to add some folder modified by the bitnami/rabbitmq image using emptyDir to bypass the read only file system issue, but finally stuck at erlang cookie file modifying (the application will try to write erlang cookie file into a folder which is not empty so I can't mount the folder as emptyDir).

Are you sure it's not empty? The cookie is created to `$RABBITMQ_HOME_DIR` which by default is `/opt/bitnami/rabbitmq/.rabbitmq` and is empty. Could you double check it?

**Comment by ruinshe** [comment]
> Are you sure it's not empty? The cookie is created to $RABBITMQ_HOME_DIR which by default is /opt/bitnami/rabbitmq/.rabbitmq and is empty. Could you double check it?

Hi @alemorcuq 

I checked the `.rabbitmq` folder it shows:

```sh
I have no name!@sc-commons-rabbitmq-0:/$ ls -al /opt/bitnami/rabbitmq/.rabbitmq/
total 8
drwxrwxr-x 1 root root   28 Dec 13 07:27 .
drwxr-xr-x 1 root root   45 Dec  2 16:26 ..
-r-------- 1 1001 root   33 Dec 13 07:27 .erlang.cookie
drwxr-xr-x 4 1001 1001 4096 Dec 13 07:27 mnesia
```

So in this case it's OK to mount it as emptyDir, right? (Just want to confirm that `mnesia` folder will be created every time so it's safe to mount it out)

**Comment by alemorcuq** [comment]
Yes

**Comment by ruinshe** [comment]
When I mount out the folder `/opt/bitnami/rabbitmq/.rabbitmq/`, and another error shows when startup:

```log
rabbitmq 09:36:32.17
rabbitmq 09:36:32.17 Welcome to the Bitnami rabbitmq container
rabbitmq 09:36:32.17 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
rabbitmq 09:36:32.17 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
rabbitmq 09:36:32.17
rabbitmq 09:36:32.17 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 09:36:32.19 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 09:36:32.27 INFO  ==> Initializing RabbitMQ...
mkdir: cannot create directory ‘/bitnami/rabbitmq/mnesia’: File exists
```

I found the file is created as soft link with link route below, but  folder `/opt/bitnami/rabbitmq/.rabbitmq/mnesia` is not created by default:
```
/bitnami/rabbitmq/mnesia -> /var/lib/rabbitmq/mnesia
/var/lib/rabbitmq -> /opt/bitnami/rabbitmq/.rabbitmq
```

I tried to create the folder `/opt/bitnami/rabbitmq/.rabbitmq/mnesia` manually using init container, the container starts but no files generated in the folder `/opt/bitnami/rabbitmq/.rabbitmq` (neither erlang cookie file, nor files in `mnesia` folder), any suggestions to figure it out why it doesn't work?

**Comment by alemorcuq** [comment]
You are right. I didn't notice that symlink. Main issue seems to be the erlang cookie generation, but maybe it makes sense to persist the cookie? We'll need to check that.

**Comment by ruinshe** [comment]
Hi, do you have plan to follow up this issue? Let me know if where is any question I may help.

**Comment by alemorcuq** [comment]
I created a task in the backlog, but due to other priorities I can't provide an ETA on it.

**Comment by kbraun-axio** [comment]
I had the same problem as @ruinshe. I encountered it while trying to deploy RabbitMq with the Bitnami Helm Chart in a K8s cluster that does not allow containers to create files in their own file system (files can only be created in mounted volumes). The error message that was initially displayed was the same as in https://github.com/bitnami/bitnami-docker-rabbitmq/issues/179.
While looking for a solution, I found this issue about the read-only file system.

I managed to start RabbitMq by mounting the whole `/opt/bitnami/rabbitmq` directory to an `emptyDir`. I used an initContainer with the same bitnami rabbitmq image that the statefulSet uses. This allowed me to copy the existing files into the emptyDir:

```
extraVolumeMounts:
  - name: tmp
    mountPath: /tmp
    readOnly: false
  - name: opt
    mountPath: /opt/bitnami/rabbitmq
    readOnly: false   

extraVolumes:
  - name: tmp
    emptyDir: {}
  - name: opt
    emptyDir: {}

initContainers:
   - name: data-copy
     image: bitnami/rabbitmq
     imagePullPolicy: IfNotPresent
     volumeMounts:
      - name: opt
        mountPath: "/mnt/opt/bitnami/rabbitmq"
     command:
      - /bin/bash
     args:
      - -ec
      - cp -r -v "/opt/bitnami/rabbitmq/." "/mnt/opt/bitnami/rabbitmq"
```

However, some experiments revealed that RabbitMq looses queued messages when it is restarted in this setup.
How did I find out?

First, I started a new minikube cluster with podSecurityPolicy enabled:
`minikube start --extra-config=apiserver.enable-admission-plugins=PodSecurityPolicy --addons=pod-security-policy`.
Second, I created a restricted podSecurityPolicy that sets `readOnlyRootFilesystem: true` (and a ClusterRole and ClusterRoleBinding like in the examples at https://kubernetes.io/docs/concepts/policy/pod-security-policy/).
Finally, I install the Bitnami RabbitMq Helm chart with the volumeMounts and InitContainers specified in the values.yaml file as shown above.

After the setup is done, I deploy two pods, one to send messages to RabbitMq and one to receive messages from it.
Before instructing the sender to start sending messages, I scale the deployment of the message receiver to 0 replicas. That is to let RabbitMQ queue the messages and not deliver them right away.

Afterwards, I make the sender send 500 messages. The RabbitMQ Management web interface shows 500 queued messages.
If I scale the deployment of the message receiver to 1 replica now, it receives the 500 messages.
However, if I scale the whole RabbitMq statefulSet to 0 replicas instead and wait until all pods are stopped, and then scale it back to 3 replicas (my initial replica count), all the 500 queued messages are lost. They neither get delivered to the message receiver pod, nor appear in the RabbitMQ Management web interface anymore.

The same experiment works if I do not set the podSecurityPolicy to `readOnlyRootFilesystem: true` but set it to `readOnlyRootFilesystem: false` instead. Then, my 500 queued messages survive restarts.

I guess it might have something to do with rabbitMq not being able to find the right persistence directory in the data PVC in case of a readOnly root container file system, though the data PVC is not read-only. But I couldn'v verify that yet. 

During startup of RabbitMq I saw some log messages like
```
Making sure data directory '/bitnami/rabbitmq/mnesia/rabbit@dev-rabbit-rabbitmq-0.dev-rabbit-rabbitmq-headless.default.svc.cluster.local/msg_stores/vhosts/628WB79CIFDYO9LJI6DKMI09L' for vhost '/' exists
2022-01-20 13:16:53.235774+00:00 [info] <0.544.0> Starting message stores for vhost '/'
2022-01-20 13:16:53.236039+00:00 [info] <0.548.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_transient": using rabbit_msg_store_ets_index to provide index
```

Maybe this directory `628WB79CIFDYO9LJI6DKMI09L` is not found after a restart with a read-only root file system?
