### ISSUE TITLE
Mongodb - config is not changed when siwtch from auth to no auth

### ISSUE THREAD

**Issue by ognif** [bitnami/charts#8394]
**Which chart**:
bitnami/mongodb

**Describe the bug**
After successfull install with rootUser access, the pod is running well.
After redeploy with `auth.enabled=fals`e and no rootUser Env, the pod is permanently crashing.

It seems that the pod is writing the config for mongodb to the PVC and never overwrite it with new ENV.

**To Reproduce**

1. Install with
```yaml
mongodb:
  enabled: true
  global:
    storageClass: longhorn
  auth:
    enabled: true
    rootUser: root
    adminPassword: example
  architecture: replicaset
  useStatefulSet: true
  arbiter:
    enabled: false
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: longhorn
    mountPath: /bitnami/mongodb
    size: 512Mi
  volumePermissions:
    enabled: true
  service:
    port: 27017
```
2.) Redeploy with
```yaml
mongodb:
  enabled: true
  global:
    storageClass: longhorn
  auth:
    enabled: false
  architecture: replicaset
  useStatefulSet: true
  arbiter:
    enabled: false
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: longhorn
    mountPath: /bitnami/mongodb
    size: 512Mi
  volumePermissions:
    enabled: true
  service:
    port: 27017
```

**Expected behavior**
I expect that ENV variables are written to the config file.
Or I have the possibility to force rewrite the config.
