### ISSUE TITLE
[bitnami/rabbitmq] Azure Kubernetes Service (AKS) persistence configuration with replicaCount > 1

### ISSUE THREAD

**Issue by christopheblin** [bitnami/charts#8415]
**Which chart**:

CHART rabbitmq-8.6.0

APP VERSION  3.8.9 

**Is your feature request related to a problem? Please describe.**

Not sure this is a feature request or a bug, so I'll try to explain what I did and what happened and what I'd like

I deployed a rabbitmq cluster with 2 replica and enabled the persistence

```yaml
persistence:
  enabled: true
  storageClass: "managed-premium" #same problem with "default"
  selector: {}
  accessMode: ReadWriteOnce
  size: 8Gi
```

So it correctly created 2 azure disks 

When I do a helm upgrade, it fails because there is more than one pod that tries to attach to the PVC

So I did set updateStrategyType: OnDelete so I can helm upgrade then kill the first pod (and after that k8s will recreate a pod that uses the same PVC) then kill the second pod

However, what happened is that it fails if k8s decide to schedule a pod on another node (because azure disks are not meant to be shared by 2 distinct virtual machines)

**Describe the solution you'd like**

I am not really sure if I made a mistake during persistence configuration (what should have used instead and why ?)

Otherwise, I'd like to be sure that each pod is recreated on the same node (and that both pods are created on different nodes for HA)

Any help appreciated !
