### ISSUE TITLE
PostgreSQL Helm Chart: SQL scripts from `initdbScripts` won't be executed

### ISSUE THREAD

**Issue by dominikbraun** [bitnami/charts#8427]
I found a couple of related issues, but none of them solved my problem, unfortunately.

**My `values.yaml`:**

```yaml
postgresqlUsername: dev
postgresqlPassword: dev
initdbScripts:
  init-mydb.sql: |
    CREATE USER abc WITH PASSWORD 'abc';
    CREATE DATABASE mydb;
    GRANT ALL PRIVILEGES ON DATABASE mydb TO abc;
```

**My problem:**

* After installing the Cart, there is a ConfigMap that contains all my init scripts.
* However, when connecting to PostgreSQL with the `dev` user and listing the databases using `\l`, the `mydb` database doesn't show up.
* It looks like the scripts from `initdbScripts` haven't been executed.

Any ideas? 🤔

**Comment by juan131** [comment]
Hi @dominikbraun 

Could you please share the following information?

- PostgreSQL container logs.
- Bitnami PostgreSQL chart version.

Thanks in advance!

**Comment by carrodher** [comment]
Adding debug to the container by appending the following code to the _values.yaml_
```yaml
image:
  debug: true
```
we can see the following error
```
postgresql 08:19:52.78 DEBUG ==> Executing /docker-entrypoint-initdb.d/..2021_12_17_08_19_32.787132921/init-mydb.sql
postgresql 08:19:52.78 DEBUG ==> Executing SQL command:
CREATE USER abc WITH PASSWORD 'abc';
CREATE DATABASE mydb;
GRANT ALL PRIVILEGES ON DATABASE mydb TO abc;
2021-12-17 08:19:52.796 GMT [160] ERROR:  permission denied to create role
2021-12-17 08:19:52.796 GMT [160] STATEMENT:  CREATE USER abc WITH PASSWORD 'abc';
ERROR:  permission denied to create role
CREATE DATABASE
2021-12-17 08:19:53.065 GMT [160] ERROR:  role "abc" does not exist
2021-12-17 08:19:53.065 GMT [160] STATEMENT:  GRANT ALL PRIVILEGES ON DATABASE mydb TO abc;
ERROR:  role "abc" does not exist
```

Per the above log, it seems your script is being executed but there is an error because of a lack of permissions.
Please, note that a `postgresqlUsername` different than _postgres_ is not admin user:
```
postgres=> \du
                                   List of roles
 Role name |                         Attributes                         | Member of
-----------+------------------------------------------------------------+-----------
 dev       | Create DB                                                  | {}
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
```

From the _values.yaml_:
```yaml
## @param postgresqlPostgresPassword PostgreSQL admin password (used when `postgresqlUsername` is not `postgres`, in which case`postgres` is the admin username)
## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#creating-a-database-user-on-first-run (see note!)
postgresqlPostgresPassword: ""
## @param postgresqlUsername PostgreSQL user (has superuser privileges if username is `postgres`)
## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#setting-the-root-password-on-first-run
##
postgresqlUsername: postgres
## @param postgresqlPassword PostgreSQL user password
## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#setting-the-root-password-on-first-run
##
postgresqlPassword: ""
```

In the same way, when installing the chart there are some notes to obtain the password for the admin user and the recently created one, as well as some instructions to connect to the database:

> To get the password for "postgres" run:
> 
>     export POSTGRES_ADMIN_PASSWORD=$(kubectl get secret postgres-postgresql -o jsonpath="{.data.postgresql-postgres-password}" | base64 --decode)
> 
> To get the password for "dev" run:
> 
>     export POSTGRES_PASSWORD=$(kubectl get secret postgres-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
> 
> To connect to your database run the following command:
> 
>     kubectl run postgres-postgresql-client --rm --tty -i --restart='Never' --image docker.io/bitnami/postgresql:11.14.0-debian-10-r17 --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql --host postgres-postgresql -U dev -d postgres -p 5432

You can obtain these notes at any time by running `helm get notes RELEASE_NAME`. Then you can access the database on this way and manually try to do your desired actions before moving them to the init script.
