### ISSUE TITLE
[elasticsearch] metrics don't work if security is enabled

### ISSUE THREAD

**Issue by ferama** [bitnami/charts#8444]
**Which chart**:
elastisearch 17.5.2

**Describe the bug**
if you enable security and metrics, metrics will not work. I think it is because no credentials are forwarded to the exporter deployment

**To Reproduce**

Install the chart using this overrides
```yaml
metrics:
    enabled: true
security:
    enabled: true
    elasticPassword: "thepassword"
    tls:
      restEncryption: false
      autoGenerated: true
```

**Expected behavior**
Credentials should be forwarded to the metrics service here https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/templates/metrics-deploy.yaml

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:08:39Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.4-3+adc4115d990346", GitCommit:"adc4115d990346b87714cc4f033d225711bf744d", GitTreeState:"clean", BuildDate:"2021-11-17T22:03:17Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by rafariossaa** [comment]
Hi, 
  Could you try if it works for you by passing them to `metrics.extraArgs` ?

**Comment by ferama** [comment]
forgot to mention but already did it without success. The elasticsesarch metrics exporter (https://github.com/prometheus-community/elasticsearch_exporter) assumes that you forward the credentials into the http uri using the `es.uri` parameter.
So:
```
http://admin:pass@localhost:9200
```
unfortunately trying to override the `es.uri` parameter using `metrics.extraArgs` doesn't work.
This is what I tryied
```
metrics:
    enabled: true
    extraArgs:
      - --es.uri=http://elastic:mypass@myrel-elasticsearch-coordinating-only:9200
```

the pod args become:
```
    Port:          9114/TCP
    Host Port:     0/TCP
    Args:
      --es.uri=http://myrel-elasticsearch-coordinating-only:9200
      --es.all
      --es.uri=http://elastic:myapss@myrel-elasticsearch-coordinating-only:9200
    State:          Waiting
      Reason:       CrashLoopBackOff
```

and the metrics pod will enter into `CrashLoopBackOff` state
