### ISSUE TITLE
[spark] security.ssl.enabled=true fails to open up Service port for HTTPS

### ISSUE THREAD

**Issue by brsolomon-deloitte** [bitnami/charts#8446]
**Which chart**:

spark

**Describe the bug**

When `security.ssl.enabled=true` and `security.ssl.autoGenerated=true`, the `spark-master-svc` created by spark/templates/svc-master.yaml fails to open up port 8480 for HTTPS, even though HTTP will auto-redirect there. This makes the Spark UI inaccessible.

**To Reproduce**

```bash
# wget -S spark-master-svc:80
Connecting to spark-master-svc:80 (10.100.93.188:80)
  HTTP/1.1 302 Found
  Connection: close
  Date: Fri, 17 Dec 2021 16:16:33 GMT
  Location: https://spark-master-svc:8480/
Connecting to spark-master-svc:8480 (10.100.93.188:8480)  # This will hang
```

Resulting manifest is missing a new port in `ports`:

```yaml
apiVersion: v1
kind: Service

...

spec:

  ...
  ports:
    - name: cluster
      port: 7077
      protocol: TCP
      targetPort: cluster
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: spark
    app.kubernetes.io/name: spark
  sessionAffinity: None
  type: ClusterIP
```

From Spark logs, these are the ports on container that need opened:

```
21/12/17 16:00:41 INFO Utils: Successfully started service 'MasterUI (HTTPS)' on port 8480.
21/12/17 16:00:41 INFO Utils: Successfully started service 'MasterUI' on port 8080.

21/12/17 16:03:07 INFO Utils: Successfully started service 'WorkerUI (HTTPS)' on port 8481.
21/12/17 16:03:07 INFO Utils: Successfully started service 'WorkerUI' on port 8081.
```
