### ISSUE TITLE
[bitnami/contour] cannot make ingress non-default

### ISSUE THREAD

**Issue by EugenMayer** [bitnami/charts#8450]
I'am deploy to contour instances (into different namespaces): `contour-internal` and `contour-external`

It works out pretty well. The only issue is with the ingressClasses - the internal I set to be the default

```yaml
contour:
  ingressClass:
    name: contour-internal
    create: true
    default: true
  manageCRDs: true
```

while the external I set to be not a default ingressClass

```yaml
contour:
  ingressClass:
    name: contour-internal
    create: true
    default: false
  manageCRDs: false
```

When deploying that and trying to create an ingress router without setting a specific ingressClassName I get the error:

```
Internal error occurred: 2 default IngressClasses were found, only 1 allowed
```

Am I using it the wrong way? Thanks
