### ISSUE TITLE
[bitnami/airflow] restarting the web/scheduler/worker in k8s helm

### ISSUE THREAD

**Issue by Kydybets** [bitnami/charts#8454]
**Which chart**:
  chart      = "airflow"
  version    = "8.0.7"

**Describe the bug**
facing the issue of crushing the pod with sync-repository with next logs
```
  | Dec 20, 2021 @ 06:35:57.872 | fatal: Could not read from remote repository.

  | Dec 20, 2021 @ 06:35:57.872 | and the repository exists.

  | Dec 20, 2021 @ 06:35:57.872 | Please make sure you have the correct access rights

  | Dec 20, 2021 @ 06:35:57.872 | ssh: Could not resolve hostname <DNS-NAME>: Temporary failure in name resolution

```

**Version of Helm and Kubernetes**:

```
$ helm version
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

Could you share the exact set of values that trigger the issue?

**Comment by Kydybets** [comment]
just to note, 
that this is happens randomly 

```
web:
  image:
    pullPolicy: Always
  extraVolumeMounts:
  - name: dind-storage
    mountPath: /var/lib/docker
  - name: git-clone-local-keys
    mountPath: /home/bitnami/.ssh
  - name: terraform-credentials
    mountPath: /.aws
  extraVolumes:
  - name: dind-storage
    emptyDir: {}
  - name: git-clone-local-keys
    emptyDir: {}
  - name: git-clone-secret
    secret:
      secretName: airflow-bitbucket-ssh-keys
      defaultMode: 256
  - name: terraform-credentials
    secret:
      secretName: airflow-terraform-aws-credentials
  nodeSelector:
    node_pool: management
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      memory: 1Gi
      cpu: 500m

scheduler:
  image:
    pullPolicy: Always
  extraVolumeMounts:
  - name: dind-storage
    mountPath: /var/lib/docker
  - name: git-clone-local-keys
    mountPath: /home/bitnami/.ssh
  - name: terraform-credentials
    mountPath: /.aws
  extraVolumes:
  - name: dind-storage
    emptyDir: {}
  - name: git-clone-local-keys
    emptyDir: {}
  - name: git-clone-secret
    secret:
      secretName: airflow-bitbucket-ssh-keys
      defaultMode: 256
  - name: terraform-credentials
    secret:
      secretName: airflow-terraform-aws-credentials
  nodeSelector:
    node_pool: management
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      memory: 1Gi
      cpu: 500m

worker:
  image:
    pullPolicy: Always
  extraVolumeMounts:
  - name: dind-storage
    mountPath: /var/lib/docker
  - name: git-clone-local-keys
    mountPath: /home/bitnami/.ssh
  - name: terraform-credentials
    mountPath: /.aws
  extraVolumes:
  - name: dind-storage
    emptyDir: {}
  - name: git-clone-local-keys
    emptyDir: {}
  - name: git-clone-secret
    secret:
      secretName: airflow-bitbucket-ssh-keys
      defaultMode: 256
  - name: terraform-credentials
    secret:
      secretName: airflow-terraform-aws-credentials
  nodeSelector:
    node_pool: management
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      memory: 1Gi
      cpu: 500m

git:
  dags:
    enabled: true
    repositories:
    #Actually not used anywhere and exists here to avoid errors for helm templating
    - repository: " "
      branch: " "
      name: "stealth"

  clone:
    extraVolumeMounts:
    - name: git-clone-secret
      mountPath: /keys
    - name: git-clone-local-keys
      mountPath: /root/.ssh

    #dags-stealth is created by parent chart (stealth is taken from repositories: section above)
    command: ["/bin/bash", "-ec"]
    # ~/.ssh/airflow this folder will be used by Airflow jobs (Git operations)
    # 1001 - is Airflow User
    args:
      - >-
        cp -rL /keys/* ~/.ssh/ &&
        chmod 600 ~/.ssh/* &&
        git clone ${DAGS_REPO} --branch ${DAGS_BRANCH} /dags-stealth
  sync:
    extraVolumeMounts:
    - name: git-clone-secret
      mountPath: /keys
    - name: git-clone-local-keys
      mountPath: /root/.ssh

    command: ["/bin/bash", "-ec"]
    args:
      - >-
        cp -rL /keys/* ~/.ssh/ &&
        chmod 600 ~/.ssh/* &&
        mkdir -p ~/.ssh/airflow &&
        cp -rL /keys/* ~/.ssh/airflow &&
        chown -R 1001:1001 ~/.ssh/airflow/ &&
        chmod 600 ~/.ssh/airflow/*  &&
        while true; do
            cd /dags-stealth && git pull origin ${DAGS_BRANCH}
            sleep 30
        done

externalDatabase:
  database: airflow
  port: 5432

postgresql:
  enabled: false

metrics:
  enabled: true
```
