### ISSUE TITLE
DNS record does not get created from VirtualService 

### ISSUE THREAD

**Issue by saikatharryc** [bitnami/charts#8489]
Virtual Service does not picked up and create the DNS record.
instead when i pass the target annotation , it gets created, although to make it dynamic, at times we cannot be sure what would the IP be.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-ingress
  namespace: test
  # annotations:
  #   external-dns.alpha.kubernetes.io/target: 10.14.64.1
spec:
  hosts:
    - t23.test-cluster-001.europe-west3-gcloud.internal.something.io
  gateways:
    - "cluster-services/istio-gateway-internal"
  http:
    - headers:
        response:
          set:
            Strict-Transport-Security: max-age=300; includeSubDomains
            X-Forwarded-Proto: https
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: hworld-svc
            port:
              number: 8080    
```
