### ISSUE TITLE
[Bitnami/Mongodb] Access Mongodb ReplicaSet From Client Mongo (Studio 3T, Robot 3T).

### ISSUE THREAD

**Issue by fayssaldarif** [bitnami/charts#8492]
**Which chart**:
mongodb-10.30.8  (and mongodb-10.30.8) of the affected chart

**Describe the bug**
I deployed mongodb replicaset with 3 mongodb instances (pods) + 1 mongodb arbiter (pod), and I have setup the TLS with self-signed cert for client-mongo and between members  communication.

I created three external access services NodePort to reach the mongo replicaset from outside the cluster.

Problem:
the Client mongo Studio 3T is trying to reach the mongodb primary node using the Pod's DNS name which will never get happen, because this DNS name only accessible from inside the cluster.

For that I switched to the second option, is to use the `extraDeploy `object with sidecar container  `mongo-labeler` deployed in each mongodb pod.

```yaml
- name: mongo-labeler
   image: korenlev/k8s-mongo-labeler-sidecar
   #image: combor/k8s-mongo-labeler-sidecar
   imagePullPolicy: Always
   env:
     - name: LABEL_SELECTOR
       value: "app.kubernetes.io/component=mongodb,app.kubernetes.io/instance=xx-mongodb,app.kubernetes.io/name=mongodb,app.kubernetes.io/managed-by=Helm"
     - name: NAMESPACE
       value: "demo"
     - name: DEBUG
       value: "true"
     - name: TZ
       value: "Europe/Paris"
   resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
```

extraDeploy object:

```yaml
apiVersion: v1
   kind: Service
   metadata:
     name: mongodb-primary
     namespace: demo
     labels:
       app.kubernetes.io/component: mongodb
       app.kubernetes.io/instance: xx-mongodb
       app.kubernetes.io/managed-by: Helm
       app.kubernetes.io/name: mongodb
   spec:
     type: NodePort
     externalTrafficPolicy: Cluster
     ports:
       - name: mongodb
         port: xxxxx
         nodePort: xxxxx
         protocol: TCP
         targetPort: mongodb
     selector:
       app.kubernetes.io/component: mongodb
       app.kubernetes.io/instance: xx-mongodb
       app.kubernetes.io/managed-by: Helm
       app.kubernetes.io/name: mongodb
       primary: "true"
```

Log error for sidecar container:

```console
$ kubectl logs -f xx-mongodb-0 -n demo -c mongo-labeler
time="2021-12-23T14:22:24Z" level=info msg="Setting logging level to debug"
time="2021-12-23T14:22:29Z" level=error msg="connection(localhost:27017[-1]) unable to decode message length: EOF"
time="2021-12-23T14:22:34Z" level=error msg="connection(localhost:27017[-2]) unable to decode message length: EOF"
time="2021-12-23T14:22:39Z" level=error msg="connection(localhost:27017[-3]) unable to decode message length: EOF"
time="2021-12-23T14:22:44Z" level=error msg="connection(localhost:27017[-4]) unable to decode message length: EOF"
time="2021-12-23T14:22:49Z" level=error msg="connection(localhost:27017[-5]) unable to decode message length: EOF"
time="2021-12-23T14:22:54Z" level=error msg="connection(localhost:27017[-6]) unable to decode message length: EOF"
time="2021-12-23T14:22:59Z" level=error msg="connection(localhost:27017[-7]) unable to decode message length: EOF"
time="2021-12-23T14:23:04Z" level=error msg="connection(localhost:27017[-8]) unable to decode message length: EOF"
time="2021-12-23T14:23:09Z" level=error msg="connection(localhost:27017[-9]) unable to decode message length: EOF"
time="2021-12-23T14:23:14Z" level=error msg="connection(localhost:27017[-10]) unable to decode message length: EOF"
time="2021-12-23T14:23:19Z" level=error msg="connection(localhost:27017[-11]) unable to decode message length: EOF"
time="2021-12-23T14:23:24Z" level=error msg="connection(localhost:27017[-12]) unable to decode message length: EOF"
time="2021-12-23T14:23:29Z" level=error msg="connection(localhost:27017[-13]) unable to decode message length: EOF"
time="2021-12-23T14:23:34Z" level=error msg="connection(localhost:27017[-14]) unable to decode message length: EOF"
time="2021-12-23T14:23:39Z" level=error msg="connection(localhost:27017[-15]) unable to decode message length: EOF"
time="2021-12-23T14:23:44Z" level=error msg="connection(localhost:27017[-16]) unable to decode message length: EOF"
time="2021-12-23T14:23:49Z" level=error msg="connection(localhost:27017[-17]) unable to decode message length: EOF"
time="2021-12-23T14:23:54Z" level=error msg="connection(localhost:27017[-18]) unable to decode message length: EOF"
time="2021-12-23T14:23:59Z" level=error msg="connection(localhost:27017[-19]) unable to decode message length: EOF"
time="2021-12-23T14:24:04Z" level=error msg="connection(localhost:27017[-20]) unable to decode message length: EOF"
time="2021-12-23T14:24:09Z" level=error msg="connection(localhost:27017[-21]) unable to decode message length: EOF"
time="2021-12-23T14:24:14Z" level=error msg="connection(localhost:27017[-22]) unable to decode message length: EOF"
```

**Version of Helm and Kubernetes**:

```
kube : Client Version: v1.21.1
         Server Version: v1.22.4
helm : v3.6.2+gee407bd
```

Values file:
```yaml
architecture: replicaset
containerSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1001
extraEnvVars:
- name: TZ
  value: Europe/Paris
persistence:
  accessModes:
  - ReadWriteOnce
  enabled: true
  size: 200Gi
  storageClass: local-storage
podSecurityContext:
  enabled: true
  fsGroup: 1001
replicaCount: 3
resources:
  limits:
    cpu: "1.5"
    memory: 2048Mi
  requests:
    cpu: 500m
    memory: 245Mi
serviceAccount:
  create: true
  name: mongodb-sa
tls:
  enabled: true
externalAccess:
  enabled: false
  service:
    type: NodePort
    nodePorts:
    - xxxxx
    - xxxxx
    - xxxxx
metrics:
    enabled: true
    resources:
     limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
    serviceMonitor:
      enabled: false
    readinessProbe:
      enabled: false
      initialDelaySeconds: 25
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 1
readinessProbe:
  enabled: false
  initialDelaySeconds: 25
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
podAnnotations:
  backup.velero.io/backup-volumes: datadir
existingSecret: xx-mongodb
sidecars:
 - name: mongo-labeler
   image: korenlev/k8s-mongo-labeler-sidecar
   #image: combor/k8s-mongo-labeler-sidecar
   imagePullPolicy: Always
   env:
     - name: LABEL_SELECTOR
       value: "app.kubernetes.io/component=mongodb,app.kubernetes.io/instance=xx-mongodb,app.kubernetes.io/name=mongodb,app.kubernetes.io/managed-by=Helm"
     - name: NAMESPACE
       value: "demo"
     - name: DEBUG
       value: "true"
     - name: TZ
       value: "Europe/Paris"
   resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
```
Addittional info:
The service account `mongodb-sa` used here has the right permssion to update pods. which means the sidecar container will be able to edit pods labels.

Thanks for your help
