### ISSUE TITLE
[bitnami/redis] Specify memory / cpu limit

### ISSUE THREAD

**Issue by Socolin** [bitnami/charts#8502]
**Which chart**:
redis: 15.6.8

Hello,

I would like to configure a limit cpu / memory for redis pods, is it possible ? if not it would be good to have this. Also it would be nice to be able to configure the max memory in the redis configuration `maxmemory 2mb` (maybe this is possible through ConfigMap but I don't know how to do this)

**Comment by carrodher** [comment]
Yes, it is possible, take a look at the `resources.limits` and/or `resources.requests` sections that are present for the different containers that are part of the Helm chart, for example in the case of the `master`:
```yaml
## @section Redis&trade; master configuration parameters
##
master:
...
  ## Redis&trade; master resource requests and limits
  ## ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ## @param master.resources.limits The resources limits for the Redis&trade; master containers
  ## @param master.resources.requests The requested resources for the Redis&trade; master containers
  ##
  resources:
    limits: {}
    requests: {}
```

In the [official k8s doc site](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) you can find info about how to configure those parameters.

Regarding configuration, the Helm chart (and Redis as application) can be configured in different ways (parameters, ConfigMap, Environment variables, etc); please take a look at the [_values.yaml_](https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml) descriptions to find the method that better fits in your use case, you can also find this kind of information in the [_README.md_](https://github.com/bitnami/charts/tree/master/bitnami/redis), there are some tables listing all the parameters that are available.

**Comment by Socolin** [comment]
Ok thanks, I was looking for `cpu` or `memory` on the README and it was not here, but now I understand how it works :) I'm not used yet to check the `values.yaml` to find what is available

I just have a question about `existingConfigmap` is it a replacement for the default ConfigMap from the chart or is it append to the default config ?

**Comment by carrodher** [comment]
If `existingConfigmap` is provided, this ConfigMap is going to be used instead of the predefined one. In fact, the default CM is not created, there is a function in the `_helpers.tpl` for that:
```
 {{/*
 Return true if a configmap object should be created
 */}}
 {{- define "redis.createConfigmap" -}}
 {{- if empty .Values.existingConfigmap }}
     {{- true -}}
 {{- end -}}
 {{- end -}}
```

If you want to customize the existing CM, you can use `commonConfiguration` which it's added into the ConfigMap:
```yaml
## @param commonConfiguration [string] Common configuration to be added into the ConfigMap
## ref: https://redis.io/topics/config
##
commonConfiguration: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""
```
and then it's used in the CM template:
```yaml
 {{- if (include "redis.createConfigmap" .) }}
 apiVersion: v1
 kind: ConfigMap
 metadata:
   name: {{ printf "%s-configuration" (include "common.names.fullname" .) }}
   namespace: {{ .Release.Namespace | quote }}
   labels: {{- include "common.labels.standard" . | nindent 4 }}
     {{- if .Values.commonLabels }}
     {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
     {{- end }}
   {{- if .Values.commonAnnotations }}
   annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
   {{- end }}
 data:
   redis.conf: |-
     # User-supplied common configuration:
     {{- if .Values.commonConfiguration }}
     {{- include "common.tplvalues.render" ( dict "value" .Values.commonConfiguration "context" $ ) | nindent 4 }}
     {{- end }}
     # End of common configuration
```
