### ISSUE TITLE
[Redis] failed on reinstall / upgrade chart: "upgrade failed: spec.clusterIP: Invalid value: "": field is immutable"

### ISSUE THREAD

**Issue by fabio-filho** [bitnami/charts#8508]
**Which chart**:
The chart redis used as a dependency:
```yaml
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 15.5.1
```

**Describe the bug**
After I reinstall / upgrade a **redis** helm chart I'm getting this message:
```
Warning  FailedReleaseSync  48s (x2 over 7d14h)       helm-operator  synchronization of release 'my-service' in namespace 'my-custom-namespace' failed: upgrade failed: failed to replace object: Service "my-service-redis-master" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```
I use the flux (legacy version) for CD/CI. Because of this, changes on the project repository or config map don't work, then the older status is always kept.

**To Reproduce**
1. Create a helm chart;
2. Use the redis as a dependency inside the main Chart;

The `values.yaml`
```yaml
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    existingSecret: my-service-redis
    existingSecretPasswordKey: PASSWORD
  resources:
    limits:
      memory: "128Mi"
      cpu: "0.05"
    requests:
      memory: "64Mi"
      cpu: "0.02"
```
The `Chart.yaml`
```yaml
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 15.5.1
    condition: redis.enabled
```
3. Execute `helm package --dependency-update .`;
4. Execute `helm install my-service my-service-0.0.1.tgz -n my-custom-namespace`;
5. Execute `kubectl describe helmrelease my-service -n my-custom-namespace `

**Expected behavior**
The re-install / upgrade must work without any error.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:51:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I found these related links:
- https://stackoverflow.com/questions/63704993/spec-clusterip-invalid-value-field-is-immutable
- https://github.com/kubernetes/kubectl/issues/798
