### ISSUE TITLE
Multiples configmap in extraEnvVarsCM

### ISSUE THREAD

**Issue by TinDang97** [bitnami/charts#8521]
https://github.com/bitnami/charts/blob/bd5647d778e26257907ba34fa3c4250830870c52/bitnami/airflow/values.yaml#L66

I have an issue when I split large configmap into small pies. I can't add multiple configmap in extraEnvVarsCM field like k8s YAML.

Example:
```yaml
      containers:
      - name: container_name
        envFrom:
          - configMapRef:
              name: common-configs
          - configMapRef:
              name: service_configs
```
Please, help me add multi env vars like above.
