### ISSUE TITLE
metrics-server cluster-role.yaml need add nodes/stats 

### ISSUE THREAD

**Issue by ygqygq2** [bitnami/charts#854]
Error log like that:
```
"403 Forbidden", response: "Forbidden (user=system:serviceaccount:kube-system:metrics-server-metrics-s, verb=get, resource=nodes, subresource=stats)"]
```

need add `nodes/stats` to fix it.

```
rules:
  - apiGroups:
    - ""
    resources:
      - pods
      - nodes
      - nodes/stats
      - namespaces
    verbs:
      - get
      - list
      - watch
```
