### ISSUE TITLE
Unable to set additional properties for kafka helm chart

### ISSUE THREAD

**Issue by selvakumaar5496** [bitnami/charts#8553]
**Which chart**:
bitnami/kafka

**Is your feature request related to a problem? Please describe.**
I am trying to set the following kafka properties but it does not get updated in server.properties
```
--set fileDeleteDelayMs=1 \
--set logFlushOffsetCheckpointIntervalMs=1
```

Tried the alternate way of setting using ENV as shown below:
```
extraEnvVars:
  - name: KAFKA_CFG_FILE_DELETE_DELAY_MS
    value: "1"
  - name: KAFKA_CFG_LOG_FLUSH_OFFSET_CHECKPOINT_INTERVAL_MS
    value: "1"
```

**Describe the solution you'd like**
I would like to set above properties inside server.properties file

**Describe alternatives you've considered**
NA
