### ISSUE TITLE
[bitnami/mariadb-galera] 3 replicas running, but wsrep_cluster_size=1

### ISSUE THREAD

**Issue by omegazeng** [bitnami/charts#8560]
**Which chart**:
helm.sh/chart: mariadb-galera-6.1.1

**Describe the bug**
a fresh install, 3 replicas, but every member wsrep_cluster_size=1
**To Reproduce**

* mariadb-galera.yaml
```yaml
rootUser:
  password: xxxxxxxxxxxxxxxxxxxx

db:
  user: maria
  password: xxxxxxxxxxxxxxxxxxx
  name: maria

galera:
  mariabackup:
    password: xxxxxxxxxxxxxxxxx

replicaCount: 3

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 1024Mi

persistence:
  size: 5Gi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```
```console
$ kubectl create ns mariadb
helm install mariadb bitnami/mariadb-galera -n mariadb -f mariadb-galera.yaml

$ kubectl get po -n mariadb
NAME                       READY   STATUS    RESTARTS   AGE
mariadb-mariadb-galera-0   2/2     Running   0          11h
mariadb-mariadb-galera-1   2/2     Running   0          11h
mariadb-mariadb-galera-2   2/2     Running   0          11h
```
```bash
show status like 'wsrep_cluster_size';
wsrep_cluster_size	1

show status like 'wsrep_incoming_addresses';
wsrep_incoming_addresses	AUTO
```
3 members are the same result
**Expected behavior**
wsrep_cluster_size should 3
**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
helm version
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

https://github.com/bitnami/charts/issues/7071#issuecomment-1003742015

enable TLS is failed, so disable TLS, delete PVC, redeploy Galera, failed.
