### ISSUE TITLE
extraDeploy after chart CRDs are deployed

### ISSUE THREAD

**Issue by suikast42** [bitnami/charts#8566]
I deploy the cer-manager chart with helm. 
So far so good everything is working perfect. 

But I see a little improvement potential with the extraDeploy feature.

I want to extra deploy a cluster issuer and a certificate for example. 

``` yaml
extraDeploy:
  - apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: root-issuer
      namespace: {{.Namespace}}
    spec:
      ca:
        secretName: root-ca

  - apiVersion: v1
    kind: Secret
    metadata:
      name: root-ca
      namespace: {{.Namespace}}
    data:
      tls.crt: <myCert>
      tls.key: <myKey>
```

But that's not working out of box. Beacause the CRD's of cert-manager are not deployed at the thime where helm try to deploy the ClusterIssuer. Is there a workaround ?
