### ISSUE TITLE
MongoDB replica node is not syncing with the primary node

### ISSUE THREAD

**Issue by sushil-clearsense** [bitnami/charts#8571]
**Which chart**:
MongoDB - 10.30.12

**Describe the bug**
Hi,  I am trying to deploy a mongo cluster in replicaset mode with replicacount = 2. My cluster is up, but the primary node is unable to connect to the secondary node. I repeatedly get the error message - "Host failed in replica set", "Couldn't get a connection within the time limit of 1000ms".

**To Reproduce**

1) Create PV's using the following chart: 

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-rs-pv0
  labels:
    app: mongodb-replicaset
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/mongodb_rs_0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-rs-pv1
  labels:
    app: mongodb-replicaset
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/mongodb_rs_1
```

2) Then i create the cluster using the following yaml

```yaml
architecture: replicaset
replicaCount: 2

resources:
  limits:
    memory: 2048M

auth:
  rootUser: mongoadmin
  rootPassword: mongoadmin
  replicaSetKey: keyfile

persistence:
  enabled: true
  accessModes: ["ReadWriteOnce"]
  mountPath: /test/mongodbrs
  size: 8Gi
  volumeClaimTemplates:
    selector:
      matchLabels:
          app: mongodb-replicaset
```

3) Then, i upgrade my cluster with the following settings: 

```yaml
architecture: replicaset
replicaCount: 2

resources:
  limits:
    memory: 2048M

auth:
  rootUser: mongoadmin
  rootPassword: mongoadmin
  replicaSetKey: keyfile

externalAccess:
  enabled: true
  service:
    type: NodePort
    port: 27017
    nodePorts:  
      - 31355
      - 31356

persistence:
  enabled: true
  accessModes: ["ReadWriteOnce"]
  mountPath: /test/mongodbrs
  size: 8Gi
  volumeClaimTemplates:
    selector:
      matchLabels:
          app: mongodb-replicaset
```

I follow the above approach as suggested in https://github.com/bitnami/charts/issues/5508 as otherwise I get the same error - 
```
"errmsg" : "No host described in new configuration with {version: 1, term: 0} for replica set rs0 maps to this node",
```

**Expected behavior**
I expect a fully working version of mongodb cluster is up and running, but in my case any changes which i make in the primary are not synced with the secondary node.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
 helm3 version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Another thing which i have noticed is that when I login to a pod and check the rs.status() command in the mongo, I see that the output for the secondary node is quite different than the primary one. For example: the name field is quite different between primary/secondary. Secondary just has the IP. Also the status shows - unreachable.

```
rs0:SECONDARY> rs.status()
{
        "set" : "rs0",
        "date" : ISODate("2022-01-04T22:43:00.438Z"),
        "myState" : 2,
        "term" : NumberLong(6),
        "syncSourceHost" : "my-mongodb-instance-0.my-mongodb-instance-headless.########.svc.cluster.local:27017",
        "syncSourceId" : 0,
        "heartbeatIntervalMillis" : NumberLong(2000),
        "majorityVoteCount" : 3,
        "writeMajorityCount" : 3,
        "votingMembersCount" : 4,
        "writableVotingMembersCount" : 3,
        "optimes" : {
                "lastCommittedOpTime" : {
                        "ts" : Timestamp(1641332483, 1),
                        "t" : NumberLong(5)
                },
                "lastCommittedWallTime" : ISODate("2022-01-04T21:41:23.680Z"),
                "appliedOpTime" : {
                        "ts" : Timestamp(1641336173, 1),
                        "t" : NumberLong(6)
                },
                "durableOpTime" : {
                        "ts" : Timestamp(1641336173, 1),
                        "t" : NumberLong(6)
                },
                "lastAppliedWallTime" : ISODate("2022-01-04T22:42:53.996Z"),
                "lastDurableWallTime" : ISODate("2022-01-04T22:42:53.996Z")
        },
        "lastStableRecoveryTimestamp" : Timestamp(1641332483, 1),
        "electionParticipantMetrics" : {
                "votedForCandidate" : true,
                "electionTerm" : NumberLong(6),
                "lastVoteDate" : ISODate("2022-01-04T21:42:40.444Z"),
                "electionCandidateMemberId" : 0,
                "voteReason" : "",
                "lastAppliedOpTimeAtElection" : {
                        "ts" : Timestamp(1641332523, 1),
                        "t" : NumberLong(5)
                },
                "maxAppliedOpTimeInSet" : {
                        "ts" : Timestamp(1641332523, 1),
                        "t" : NumberLong(5)
                },
                "priorityAtElection" : 1,
                "newTermStartDate" : ISODate("2022-01-04T21:42:43.896Z"),
                "newTermAppliedDate" : ISODate("2022-01-04T21:43:14.619Z")
        },
        "members" : [
                {
                        "_id" : 0,
                        "name" : "my-mongodb-instance-0.my-mongodb-instance-headless.#######.svc.cluster.local:27017",
                        "health" : 1,
                        "state" : 1,
                        "stateStr" : "PRIMARY",
                        "uptime" : 3629,
                        "optime" : {
                                "ts" : Timestamp(1641336173, 1),
                                "t" : NumberLong(6)
                        },
                        "optimeDurable" : {
                                "ts" : Timestamp(1641336173, 1),
                                "t" : NumberLong(6)
                        },
                        "optimeDate" : ISODate("2022-01-04T22:42:53Z"),
                        "optimeDurableDate" : ISODate("2022-01-04T22:42:53Z"),
                        "lastAppliedWallTime" : ISODate("2022-01-04T22:42:53.996Z"),
                        "lastDurableWallTime" : ISODate("2022-01-04T22:42:53.996Z"),
                        "lastHeartbeat" : ISODate("2022-01-04T22:42:58.994Z"),
                        "lastHeartbeatRecv" : ISODate("2022-01-04T22:42:59.981Z"),
                        "pingMs" : NumberLong(0),
                        "lastHeartbeatMessage" : "",
                        "syncSourceHost" : "",
                        "syncSourceId" : -1,
                        "infoMessage" : "",
                        "electionTime" : Timestamp(1641332560, 1),
                        "electionDate" : ISODate("2022-01-04T21:42:40Z"),
                        "configVersion" : 4,
                        "configTerm" : 6
                },
                {
                        "_id" : 1,
                        "name" : "my-mongodb-instance-1.my-mongodb-instance-headless.########.svc.cluster.local:27017",
                        "health" : 1,
                        "state" : 2,
                        "stateStr" : "SECONDARY",
                        "uptime" : 3661,
                        "optime" : {
                                "ts" : Timestamp(1641336173, 1),
                                "t" : NumberLong(6)
                        },
                        "optimeDate" : ISODate("2022-01-04T22:42:53Z"),
                        "lastAppliedWallTime" : ISODate("2022-01-04T22:42:53.996Z"),
                        "lastDurableWallTime" : ISODate("2022-01-04T22:42:53.996Z"),
                        "syncSourceHost" : "my-mongodb-instance-0.my-mongodb-instance-headless.#########.svc.cluster.local:27017",
                        "syncSourceId" : 0,
                        "infoMessage" : "",
                        "configVersion" : 4,
                        "configTerm" : 6,
                        "self" : true,
                        "lastHeartbeatMessage" : ""
                },
                {
                        "_id" : 2,
                        "name" : "my-mongodb-instance-arbiter-0.my-mongodb-instance-arbiter-headless.########.svc.cluster.local:27017",
                        "health" : 1,
                        "state" : 7,
                        "stateStr" : "ARBITER",
                        "uptime" : 3629,
                        "lastHeartbeat" : ISODate("2022-01-04T22:42:58.994Z"),
                        "lastHeartbeatRecv" : ISODate("2022-01-04T22:42:59.981Z"),
                        "pingMs" : NumberLong(0),
                        "lastHeartbeatMessage" : "",
                        "syncSourceHost" : "",
                        "syncSourceId" : -1,
                        "infoMessage" : "",
                        "configVersion" : 4,
                        "configTerm" : 6
                },
                {
                        "_id" : 3,
                        "name" : "72.24.346.51:27017",
                        "health" : 0,
                        "state" : 8,
                        "stateStr" : "(not reachable/healthy)",
                        "uptime" : 0,
                        "optime" : {
                                "ts" : Timestamp(0, 0),
                                "t" : NumberLong(-1)
                        },
                        "optimeDurable" : {
                                "ts" : Timestamp(0, 0),
                                "t" : NumberLong(-1)
                        },
                        "optimeDate" : ISODate("1970-01-01T00:00:00Z"),
                        "optimeDurableDate" : ISODate("1970-01-01T00:00:00Z"),
                        "lastAppliedWallTime" : ISODate("1970-01-01T00:00:00Z"),
                        "lastDurableWallTime" : ISODate("1970-01-01T00:00:00Z"),
                        "lastHeartbeat" : ISODate("2022-01-04T22:42:58.596Z"),
                        "lastHeartbeatRecv" : ISODate("1970-01-01T00:00:00Z"),
                        "pingMs" : NumberLong(0),
                        "lastHeartbeatMessage" : "Couldn't get a connection within the time limit of 1000ms",
                        "syncSourceHost" : "",
                        "syncSourceId" : -1,
                        "infoMessage" : "",
                        "configVersion" : -1,
                        "configTerm" : -1
                }
        ],
        "ok" : 1
}
```
