### ISSUE TITLE
[bitnami/thanos] existingConfigmap not working with annotations in rule 

### ISSUE THREAD

**Issue by davidy718** [bitnami/charts#8607]
**Which chart**:
[bitnami/thanos] v8.3.0

**Describe the bug**
when creating thanos rule with existingConfigmap you can not create a rule with annotations I think because of [this ](https://github.com/bitnami/charts/blob/5e2f9dc369dffe44e32bf5ddae835d0e93ad4549/bitnami/thanos/templates/ruler/configmap.yaml#L13)line

**To Reproduce**
create thanos rule with existingConfigmap and create a rule like this
```
          - alert: InstanceDown
              expr: up == 0
              for: 1m
              labels:
                severity: critical
              annotations:
                description: "{{ "{{" }} $labels.FQDN }} has been down for more than 1 minutes."
                summary: Endpoint {{ "{{" }} $labels.tag_FQDN }} down.
```

**Expected behavior**
that it will create the rules 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

- Output of `kubectl version`:

```
o1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @davidy718 

- Could you please provide the **values.yaml** you're using to deploy the Thanos chart?
- Do you obtain any error if you run the command below using your current **values.yaml**?

```bash
helm template thanos bitnami/thanos -f values.yaml -s templates/ruler/configmap.yaml
```

**Comment by davidy718** [comment]
values for rule
```
ruler:
  enabled: true
  alertmanagers:
    - http://alertmanager-service.monitoring.svc.cluster.local:9093
  existingConfigmap: rule-conf
```
and this is my config map
```
      groups:
        - name: node_alerts
          rules:
            - alert: InstanceDown
              expr: up == 0
              for: 1m
              labels:
                severity: critical
              annotations:
                description: "{{ "{{" }} $labels.FQDN }} has been down for more than 1 minutes."
                summary: Endpoint {{ "{{" }} $labels.tag_FQDN }} down.
```
