### ISSUE TITLE
REDIS SENTINEL - Stuck on 15.3.3; slave connections not working

### ISSUE THREAD

**Issue by aeimer** [bitnami/charts#8614]
**Which chart**:
The name (and version) of the affected chart

`bitnami/redis:15.4.0`

**Describe the bug**

After upgrading from `15.3.3` to `15.4.0` our java redis clients were not able to connect to the slaves anymore.

Its seem to be a problem with this PR: https://github.com/bitnami/charts/pull/7461

```
{"timestamp":"2021-12-07T13:51:37.729Z","level":"INFO","thread":"SimpleAsyncTaskExecutor-27","logger":"org.apache.catalina.core.StandardService","message":"Starting service [Tomcat[]"}
{"timestamp":"2021-12-07T13:51:37.730Z","level":"INFO","thread":"SimpleAsyncTaskExecutor-27","logger":"org.apache.catalina.core.StandardEngine","message":"Starting Servlet engine: [Apache Tomcat/9.0.55]"}
{"timestamp":"2021-12-07T13:51:37.738Z","level":"INFO","thread":"SimpleAsyncTaskExecutor-27","logger":"org.apache.catalina.core.ContainerBase.[Tomcat-1[].[localhost[].[/]","message":"Initializing Spring embedded WebApplicationContext"}
{"timestamp":"2021-12-07T13:51:37.738Z","level":"INFO","thread":"SimpleAsyncTaskExecutor-27","logger":"org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext","message":"Root WebApplicationContext: initialization completed in 1504 ms"}
{"timestamp":"2021-12-07T13:51:37.930Z","level":"INFO","thread":"SimpleAsyncTaskExecutor-27","logger":"org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver","message":"Exposing 3 endpoint(s) beneath base path '/actuator'"}
{"timestamp":"2021-12-07T13:51:38.430Z","level":"INFO","thread":"SimpleAsyncTaskExecutor-27","logger":"org.apache.coyote.http11.Http11NioProtocol","message":"Starting ProtocolHandler [\"http-nio-8081\"]"}
{"timestamp":"2021-12-07T13:51:38.433Z","level":"INFO","thread":"SimpleAsyncTaskExecutor-27","logger":"org.springframework.boot.web.embedded.tomcat.TomcatWebServer","message":"Tomcat started on port(s): 8081 (http) with context path ''"}
{"timestamp":"2021-12-07T13:51:44.132Z","level":"INFO","thread":"http-nio-8081-exec-1","logger":"org.apache.catalina.core.ContainerBase.[Tomcat-1[].[localhost[].[/]","message":"Initializing Spring DispatcherServlet 'dispatcherServlet'"}
{"timestamp":"2021-12-07T13:51:44.133Z","level":"INFO","thread":"http-nio-8081-exec-1","logger":"org.springframework.web.servlet.DispatcherServlet","message":"Initializing Servlet 'dispatcherServlet'"}
{"timestamp":"2021-12-07T13:51:44.134Z","level":"INFO","thread":"http-nio-8081-exec-1","logger":"org.springframework.web.servlet.DispatcherServlet","message":"Completed initialization in 1 ms"}
{"timestamp":"2021-12-07T13:52:02.258Z","level":"WARN","thread":"redisson-netty-2-13","logger":"org.redisson.connection.SentinelConnectionManager","message":"slave: redis://10.0.16.188:6379 is down"}
{"timestamp":"2021-12-07T13:52:04.637Z","level":"INFO","thread":"redisson-netty-2-20","logger":"org.redisson.connection.SentinelConnectionManager","message":"slave: redis://10.0.16.188:6379 is up"}
{"timestamp":"2021-12-07T13:52:04.638Z","level":"INFO","thread":"redisson-netty-2-15","logger":"org.redisson.connection.pool.PubSubConnectionPool","message":"1 connections initialized for 10.0.16.188/10.0.16.188:6379"}
{"timestamp":"2021-12-07T13:52:04.741Z","level":"INFO","thread":"redisson-netty-2-28","logger":"org.redisson.connection.pool.SlaveConnectionPool","message":"24 connections initialized for 10.0.16.188/10.0.16.188:6379"}
{"timestamp":"2021-12-07T13:52:12.666Z","level":"WARN","thread":"redisson-netty-2-12","logger":"org.redisson.connection.SentinelConnectionManager","message":"slave: redis://10.0.16.188:6379 is down"}
{"timestamp":"2021-12-07T13:52:13.668Z","level":"INFO","thread":"redisson-netty-2-32","logger":"org.redisson.connection.SentinelConnectionManager","message":"slave: redis://10.0.16.188:6379 is up"}
{"timestamp":"2021-12-07T13:52:13.673Z","level":"INFO","thread":"redisson-netty-2-26","logger":"org.redisson.connection.pool.PubSubConnectionPool","message":"1 connections initialized for 10.0.16.188/10.0.16.188:6379"}
{"timestamp":"2021-12-07T13:52:13.677Z","level":"INFO","thread":"redisson-netty-2-28","logger":"org.redisson.connection.pool.SlaveConnectionPool","message":"24 connections initialized for 10.0.16.188/10.0.16.188:6379"}
{"timestamp":"2021-12-07T13:52:26.896Z","level":"WARN","thread":"redisson-netty-2-14","logger":"org.redisson.connection.SentinelConnectionManager","message":"slave: redis://10.0.16.188:6379 is down"}
{"timestamp":"2021-12-07T13:52:27.897Z","level":"INFO","thread":"redisson-netty-2-20","logger":"org.redisson.connection.SentinelConnectionManager","message":"slave: redis://10.0.16.188:6379 is up"}
{"timestamp":"2021-12-07T13:52:27.902Z","level":"INFO","thread":"redisson-netty-2-3","logger":"org.redisson.connection.pool.PubSubConnectionPool","message":"1 connections initialized for 10.0.16.188/10.0.16.188:6379"}
{"timestamp":"2021-12-07T13:52:27.903Z","level":"INFO","thread":"redisson-netty-2-13","logger":"org.redisson.connection.pool.SlaveConnectionPool","message":"24 connections initialized for 10.0.16.188/10.0.16.188:6379"}
{"timestamp":"2021-12-07T13:52:54.965Z","level":"WARN","thread":"redisson-netty-2-9","logger":"org.redisson.connection.SentinelConnectionManager","message":"slave: redis://10.0.16.188:6379 is down"}
[...]
```

Config of redis:
```
---

# We don't want password protection for now
auth:
  enabled: false
  sentinel: false

architecture: replication

pdb:
  create: true
  minAvailable: 2

sentinel:
  enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
  quorum: 2
  downAfterMilliseconds: 10000
  failoverTimeout: 15000

serviceAccount:
  create: true

replica:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: redis
                app.kubernetes.io/instance: redis
            topologyKey: kubernetes.io/hostname
          weight: 100
  replicaCount: 3
  persistence:
    size: 8Gi
  resources:
    limits:
      cpu: 600m
      memory: 4Gi
    requests:
      cpu: 400m
  livenessProbe:
    initialDelaySeconds: 60
  readinessProbe:
    # This will give the existing pods enough time to find a new master on roll-over
    initialDelaySeconds: 20

configmap: |-
  # <<<BEGIN FROM default values.yaml
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""
  # >>>END FROM default values.yaml

  # Setup redis as cache
  # memory limit minus about 95% => 256mb
  maxmemory 3840mb
  # Evict using approximated LFU among the keys with an expire set
  maxmemory-policy volatile-lfu
```

**To Reproduce**

1. Setup redis sentinel
2. Try to use redis with redisson
3. See logs in java pods

**Expected behavior**

After the *non-breaking* update the setup should work as before.
Or there should be some kind of info on how to approach this new version.

We are now stuck on `15.3.3`, also the latest versions were tried, but the problem persists.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

Interactions till now:
- https://github.com/bitnami/charts/pull/7461#issuecomment-987985349
- https://github.com/bitnami/charts/issues/7283#issuecomment-990871975
