### ISSUE TITLE
Ingress TLS setting is ignored

### ISSUE THREAD

**Issue by foal** [bitnami/charts#8630]
**Which chart**:

bitnami/kibana

**Describe the bug**

set ingress.tls to `true` should generate the ingress with the `TLS` section, but doesn't do it 

**To Reproduce**

1. Rin `helm template --set ingress.enabled=true --set ingress.tls=true bitnami/kibana`
2. Check generated ingress
```yaml
# Source: kibana/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: RELEASE-NAME-kibana
  namespace: "web2-cp"
  labels:
    app.kubernetes.io/name: kibana
    helm.sh/chart: kibana-9.3.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: RELEASE-NAME-kibana
                port:
                  name: http
      host: kibana.local
```

**Expected behavior**

ingress with `TLS` section 
```yaml
  tls:
    - hosts:
        - kibana.local
      secretName: kibana.local-tls
```

**Comment by carrodher** [comment]
According to the conditions in the template
```yaml
   {{- if or (and .Values.ingress.tls (or .Values.ingress.certManager .Values.ingress.selfSigned)) .Values.ingress.extraTls }}
   tls:
     {{- if and .Values.ingress.tls (or .Values.ingress.certManager .Values.ingress.selfSigned) }}
     - hosts:
         - {{ .Values.ingress.hostname | quote }}
       secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
     {{- end }}
     {{- if .Values.ingress.extraTls }}
     {{- include "common.tplvalues.render" ( dict "value" .Values.ingress.extraTls "context" $ ) | nindent 4 }}
     {{- end }}
   {{- end }}
```
`ingress.selfSigned` is also needed apart from `ingress.tls` and `ingress.enabled`. `ingress.certManager` is present for backward compatibility, but it is already deprecated in favor of `ingress.annotations`

**Comment by foal** [comment]
The same issue is with `oauth2-proxy` chart after last update

**Comment by foal** [comment]
The same issue is with `keycloak` chart after the last update (Package Version: 6.1.1) 

Maybe you will stop copy/paste this issue?

**Comment by aleksandar-babic** [comment]
@foal Confirming the same issue as reported with `keycloack`.

**Comment by juan131** [comment]
Hi everyone, we should definitely reconsider this parameter's description or add new validations to ensure it's properly used because I agree it can be confusing.

This `ingress.tls` parameter just says "I want TLS termination" but it doesn't say HOW, that's why it requires setting other parameters. This is a summary of the supported scenarios:

- I want TLS wit self-signed certificates:

```yaml
ingress:
  tls: true
  selfSigned: true
```

- I want TLS with my own certificates:

```yaml
ingress:
  tls: true
  secrets:
    - name: my-tls-certs
      key: |-
        -----BEGIN RSA PRIVATE KEY-----
        ...
        -----END RSA PRIVATE KEY-----
     certificate: |-
        -----BEGIN CERTIFICATE-----
        ...
        -----END CERTIFICATE-----
```
      
- I want TLS with cert-manager generating the certs:

```yaml
ingress:
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: cluster-issuer-name
```

**Comment by foal** [comment]
For me is perfectly enough if it will work as before - just generate something like :
```
  tls:
    - hosts:
        - kibana.local
      secretName: kibana.local-tls
````
I use the annotations but slightly different than `cert-manager.io/cluster-issuer: cluster-issuer-name`

**Comment by juan131** [comment]
Hi @foal 

The function checks the presence of the `cert-manager.io/cluster-issuer` or `cert-manager.io/issuer` annotations, see:

- https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_ingress.tpl#L65

What other annotations are you using?

**Comment by foal** [comment]
Hmm. I have my own annotation to generate certificates for Istio. In Istio the certificate must be located in the namespace of Gateway, not in the namespace of the Ingress. Anyway, it is a particular case and it should not be a rule for the general HELM chart. 

I was sure that the following code is generated by default if `tls` is `true` without any additional conditions
```yaml
    tls:
    - hosts:
        - kibana..example.com
      secretName: kibana..example.com-tls
```
but looks like it is the wrong intention.

My current workaround is to use the `extraTls`
```yaml
 extraTls:
    [
      {
          hosts: [ kibana.example.com ],
          secretName: kibana..example.com
        }
    ]
```
It is working but I need always synchronize the `ingress.hostname` and the `ingress.extraTls`, and it is not so simple as just `ingress.tls: true`

**Comment by hazmat345** [comment]
This was confusing for me also. Specifically this comment in `values.yaml`:

```
  ## @param ingress.tls Enable TLS configuration for the host defined at `ingress.hostname` parameter
  ## TLS certificates will be retrieved from a TLS secret with name: `{{- printf "%s-tls" .Values.ingress.hostname }}`
  ## You can:
  ##   - Use the `ingress.secrets` parameter to create this TLS secret
  ##   - Relay on cert-manager to create it by setting the corresponding annotations
  ##   - Relay on Helm to create self-signed certificates by setting `ingress.selfSigned=true`
  ##
  tls: false
```

I don't use `cert-manager` and I also don't want helm making a secret for me - I already have a certificate signed by a private CA I'd like to use. This line makes it seem like if I set `ingress.tls=true` and name my secret correctly it should be picked up:

 > TLS certificates will be retrieved from a TLS secret with name: `{{- printf "%s-tls" .Values.ingress.hostname }}`

But because I'm not doing any of the three things listed in the comment the tls spec isn't generated.

@foal Thanks for pointing out the `extraTls` workaround, that's working for me.

**Comment by juan131** [comment]
Hi everyone! Thanks so much for your feedback!

Would a description like the one below be less confusing?

```yaml
  ## @param ingress.tls Enable TLS configuration for the host defined at `ingress.hostname` parameter
  ## TLS certificates can be retrieved from:
  ## a) A TLS secret with name: `{{- printf "%s-tls" .Values.ingress.hostname }}`. To generate this secret you can:
  ##   - Use the `ingress.secrets` parameter to create this TLS secret
  ##   - Relay on cert-manager to create it by setting the corresponding annotations
  ##   - Relay on Helm to create self-signed certificates by setting `ingress.selfSigned=true`
  ## b) Custom TLS secrets defined setting the `ingress.extraTls` parameter 
  ##
```

**Comment by foal** [comment]
1. Relay on cert-manager to create it by setting the cert-manager.io/cluster-issuer or cert-manager.io/issuer annotation
2. Custom TLS secrets defined setting the `ingress.extraTls` parameter 
May I use in the extraTls the helm variables? 
So instead of 
```yaml
 extraTls:
    [
      {
          hosts: [ kibana.example.com ],
          secretName: kibana..example.com
        }
    ]
```
use the 
```yaml
 extraTls:
    [
      {
        hosts: [ {{ .Values.ingress.hostname | quote }} ],
        secretName: {{ printf "%s-tls" .Values.ingress.hostname }}       
    ]
```

**Comment by hazmat345** [comment]
@juan131 yeah, that's great. Thanks!

**Comment by juan131** [comment]
@foal yes, you can do that since the  `extraTls` parameter is evaluated as a template. Try with:

```yaml
 extraTls
   - hosts:
        - "{{ .Values.ingress.hostname }}"
      secretName: "{{ printf \"%s-tls\" .Values.ingress.hostname }}"
```
