### ISSUE TITLE
[IMPROVEMENT] Support of replica.fetch.max.bytes configuration in parameters

### ISSUE THREAD

**Issue by jaudiger** [bitnami/charts#8637]
**Which chart**:

The Kafka chart on 14.9.0 version.

**Is your feature request related to a problem? Please describe.**

I would like to have a parameter to override the [replica.fetch.max.bytes](https://kafka.apache.org/documentation/#brokerconfigs_replica.fetch.max.bytes) configuration. Currently, the only way to do it is to have an extra environment variable to set it.

The environment variable fulfills my use case, I just wanted to have everything set with the chart's parameters. This is a minor improvement.

**Describe the solution you'd like**

```yml
replicaFetchMaxBytes: 10485760
```

**Describe alternatives you've considered**

```yml
extraEnvVars:
  - name: KAFKA_CFG_REPLICA_FETCH_MAX_BYTES
    value: "10485760"
```
