### ISSUE TITLE
"Password authentication failed for user postgres" when using custom pg_hba.conf

### ISSUE THREAD

**Issue by cornel-masson** [bitnami/charts#8650]
**Chart**: bitnami/postgresql
**Image tag**: 14.1.0-debian-10-r59
**Kubernetes:** Rancher Desktop on Windows 10/WSL

**Describe the bug**

Brand new installation. If I deploy with a custom config-map that specifies a custom **pg_hba.conf**, I get the error: _password authentication failed for user "postgres" (User "postgres" has no password assigned)_. This shows up in the pod log as soon as the live/ready probes start to fire, or I try to log in via psql. If I don't specify a custom pg_hba.conf, it works fine.

**To Reproduce**

Apply custom configmap with pg_hba.conf:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-custom-config
data:
  pg_hba.conf: |-
    # Unix sockets
    local  all  postgres  md5
    local  all  all            peer
    # IPv4 local connections:
    host  all  all  127.0.0.1/32            md5
    host  all  all  102.37.124.150/32  md5
    host  all  all  102.37.217.33/32    md5
    # IPv6 local connections:
    host  all  all   ::1/128   md5
```

My custom **values.yaml**, with test password ("1234") for postgres user, and tag for version 14:

```yaml
global:
  postgresql:
    postgresqlPassword: "1234"
image:
  tag: 14.1.0-debian-10-r59
```

Do helm install:
```
helm install release1 -f values.yaml \
	--set configurationConfigMap=postgres-custom-config \
	bitnami/postgresql
```

Verify that postgres user password is created as secret:
```
kubectl get secret --namespace ns1 s3pg-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode
```
yields correct value from custom configmap: **1234**

Create port-forward:
```
kubectl port-forward --namespace ns1 svc/s3pg-postgresql 5432:5432 &
```

Set PGPASSWORD and connect via psql:
```
export PGPASSWORD=1234
psql --host 127.0.0.1 -U postgres -d postgres -p 5432
```

...yields error:
```
psql: FATAL:  password authentication failed for user "postgres"
```

**Expected behavior**

Should log into postgres db as postgres user.

**Additional context**

Between test runs, I uninstall the helm release and also manually _delete all PVCs (and PVs)_, since I saw from some other logged issues that this could cause a problem. I also followed all advice in #2061, but nothing helps.

The error occurs even when using the auto-generated password, i.e. if I _don't_ set the parameter: `global.postgresql.postgresqlPassword`.

If I install without the custom config-map (i.e. no custom pg_hba.conf), everything works fine: I can login with psql, and no similar errors in pod log:
```
helm install release1 -f values.yaml bitnami/postgresql
```

**Comment by carrodher** [comment]
As you rightly said, usually this kind of issue appears because the password from a previous installation is present in the PVC, but you are handling this topic properly by removing the PVC.

Apart from that, in [this section](https://github.com/bitnami/charts/tree/master/bitnami/postgresql#postgresqlconf--pg_hbaconf-files-as-configmap) of the README, there is information about how to mount custom _pg_hba.conf_ files. Can you take a look at it?

**Comment by cornel-masson** [comment]
I have already read that section and I'm using the `--set configurationConfigMap` option, as described. It doesn't work.

**Comment by fmulero** [comment]
Hi @cornel-masson, thanks for the detailed description.

The container is not able to set the password for the postgresql user with your `pg_hba.conf` file. By default the database has no password and the container during initialization, log into the database and change this password. Your configuration file is enforcing a password and this initial process breaks (you could see at least one restart of the container in your postgresql pod).

As workaround I'd suggest changing your configmap (pay attention in the `trust` rule):
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-custom-config
data:
  pg_hba.conf: |-
    # Unix sockets
    local  all  postgres  trust
    local  all  all            peer
    # IPv4 local connections:
    host  all  all  127.0.0.1/32            md5
    host  all  all  102.37.124.150/32  md5
    host  all  all  102.37.217.33/32    md5
    # IPv6 local connections:
    host  all  all   ::1/128   md5
```

Once the database is initialized, you can change again the configmap with the original data and restart the postgresql statefulset to ensure that your configuration is applied.

I'll open an internal discussion about this topic
