### ISSUE TITLE
[bitnami/fluentd] Aggregator is missing a ClusterRoleBinding

### ISSUE THREAD

**Issue by nsurleraux-railnova** [bitnami/charts#8651]
**Which chart**:

`bitnami/fluentd`

**Describe the bug**

When starting, the aggregator tries to send a call to the pod and namespace APIs, but the created service account doesn't have the required ClusterRoleBinding.

**To Reproduce**

1. Deploy a release with the following config :
```
forwarder:
  rbac:
    create: true
  serviceAccount:
    create: true
aggregator:
  serviceAccount:
    create: true
  configMap: ${aggregatorConfigMap}
  extraEnv:
    - name: AWS_REGION
      value: eu-central-1
    - name: LOG_GROUP_NAME
      value: ${logGroupName}
```
2. See the aggregator restarting due to insufficient permissions to look up the namespace and pod API.

**Expected behavior**

The aggregator should not crash.

**Additional context**

* Terraform version 1.1.2
* Helm version `version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}`
* Chart version 4.5.2
