### ISSUE TITLE
[bitnami/mongodb] mongosh vs mongo: ENOTFOUND mongodb-1.mongodb-headless.salut.svc.cluster.local

### ISSUE THREAD

**Issue by jeusdi** [bitnami/charts#8665]
**Which chart**:

```
NAME                                            	CHART VERSION	APP VERSION
bitnami/mongodb                                 	10.31.3      	4.4.11
```

**Describe the bug**

I've deployed a mongodb replicat set with these helm values, setting `externalAccess` up with `LoadBalancer`s:

```yaml
architecture: replicaset
replicaCount: 2
arbiter:
  enabled: false
serviceAccount:
  create: true
rbac:
  create: true
externalAccess:
  enabled: true
  service:
    port: 27017
    type: LoadBalancer
    nodePorts:
      - 30017
      - 30018
  autoDiscovery:
    enabled: true
image:
  debug: true
```

Both `LoadBalancer` service are up and running:

```
NAME                 TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)           AGE
mongodb-headless     ClusterIP      None           <none>        27017/TCP         17m
mongodb-0-external   LoadBalancer   10.43.41.190   172.18.0.6    27017:30017/TCP   17m
mongodb-1-external   LoadBalancer   10.43.24.190   172.18.0.7    27017:30018/TCP   17m
```

As you can see, both `LoadBalancer` are allocated with an external IP: `172.18.0.6`, and `172.18.0.7`.

From my host, I'm trying to reach my exposed mongodb replicaset:

```
$ mongosh mongodb://172.18.0.6,172.18.0.7
Current Mongosh Log ID:	61e1409dd04ce546018998c7
Connecting to:		mongodb://172.18.0.6,172.18.0.7/
MongoNetworkError: getaddrinfo ENOTFOUND mongodb-1.mongodb-headless.salut.svc.cluster.local
```

I don't quite figure out why iIt's trying to resolve `mongodb-1.mongodb-headless.salut.svc.cluster.local` from my host.

I'm using `mongo` cli, everything seems work:

```
$ mongo mongodb://172.18.0.6,172.18.0.7
MongoDB shell version v5.0.5
connecting to: mongodb://172.18.0.6:27017,172.18.0.7:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("fa41ad0e-e2ca-4ffb-bfe8-66a1e733f0d0") }
MongoDB server version: 4.4.11
WARNING: shell and server versions do not match
================
Warning: the "mongo" shell has been superseded by "mongosh",
which delivers improved usability and compatibility.The "mongo" shell has been deprecated and will be removed in
an upcoming release.
For installation instructions, see
https://docs.mongodb.com/mongodb-shell/install/
================
rs0:PRIMARY>
```

However, when I'm trying to reach my exposed mongodb replicaset, using `mongosh`:

```
$ mongosh mongodb://172.18.0.6,172.18.0.7
Current Mongosh Log ID:	61e1409dd04ce546018998c7
Connecting to:		mongodb://172.18.0.6,172.18.0.7/
MongoNetworkError: getaddrinfo ENOTFOUND mongodb-1.mongodb-headless.salut.svc.cluster.local
```

I don't quite figure out why `mongosh` is trying to resolve `mongodb-1.mongodb-headless.salut.svc.cluster.local` from my host.

**Expected behavior**

mongodb replicaset is reached from external scope.
