### ISSUE TITLE
[bitnami/redis] Enabling sentinel causes "Can't open the append-only file: Permission denied"

### ISSUE THREAD

**Issue by MikeJohnsonDev** [bitnami/charts#8677]
**Which chart**:

bitnami/redis version 15.7.5

**Describe the bug**

When you install the bitnami/redis chart on a cluster with sentinel enabled, the master keeps crashing with the following log:

```
11:57:39.65 INFO  ==> about to run the command: REDISCLI_AUTH=$REDIS_PASSWORD timeout 5 redis-cli -h redis.ns.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster
11:57:39.65 INFO  ==> printing REDIS_SENTINEL_INFO=(redis-node-1.redis-headless.ns.svc.cluster.local,6379)
1:C 15 Jan 2022 11:57:39.662 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 15 Jan 2022 11:57:39.662 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 15 Jan 2022 11:57:39.662 # Configuration loaded
1:S 15 Jan 2022 11:57:39.662 * monotonic clock: POSIX clock_gettime
1:S 15 Jan 2022 11:57:39.662 # Can't open the append-only file: Permission denied
```

**To Reproduce**

1. Install the bitnami/redis chart with sentinel enabled
2. See log

**Expected behavior**

It should start all the Redis pods without any issues.

**Additional context**

I've tried the following using `values.yaml`, similar to issue #3110:

```yaml
master:
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

  containerSecurityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

replica:
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

  containerSecurityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

volumePermissions:
  enabled: true
```

**Comment by tbcashy** [comment]
Same issue here and I also tried to mess around with permissions without success! :(

**Comment by Mauraza** [comment]
Hi @MikeJohnsonDev,

I try with these values:

```yaml
master:
  podSecurityContext:
    enabled: true
    fsGroup: 1001

  containerSecurityContext:
    enabled: true
    runAsUser: 1001

replica:
  podSecurityContext:
    enabled: true
    fsGroup: 1001

  containerSecurityContext:
    enabled: true
    runAsUser: 1001

volumePermissions:
  enabled: true
  runAsUser: 1001

sentinel:
  enabled: true
  debug: true
```
and I wasn't able to reproduce. Could you share your values and the `kubectl describe of the pod

**Comment by jtslear** [comment]
This was recently seen in a CI run that is currently failing (though the failure might be something else, I'm not positive).  Reference a pull request test that is failing: https://github.com/bitnami/charts/runs/4842365585?check_suite_focus=true#step:6:1074

**Comment by Mauraza** [comment]
Hi @jtslear,

let's see how your PR ends.

**Comment by Mauraza** [comment]
Hi @tbcashy,

Do you use the same values as @MikeJohnsonDev shared?

**Comment by tbcashy** [comment]
Hi @Mauraza,

I dont have my initial values anymore. However using your values seemed to fix it. I probably used wrong values.

**Comment by Mauraza** [comment]
Hi @tbcashy,

I'm glad it is working.

**Comment by nicobao** [comment]
Hi,
I faced the same issue
@Mauraza, your suggested changes worked for me as well.
Priori to changing the values of the chart, I was using the following:

```yaml
# appendonly mode is set to 'true' by default
# @see https://github.com/helm/charts/blob/master/stable/redis/values.yaml for default values
global:
  # @see https://docs.ovh.com/gb/en/kubernetes/ovh-kubernetes-persistent-volumes/
  storageClass: csi-cinder-high-speed
auth:
  ## @param auth.enabled Enable password authentication
  ##
  enabled: false
  ## @param auth.sentinel Enable password authentication on sentinels too
  ##
  sentinel: false
 
# We use Redis Sentinel for HA purpose
sentinel:
  enabled: true
```

hence, simply default configuration regarding file access rights. I tried without `sentinel`, and experienced the exact same issue.
Is there a problem with the default configuration?
