### ISSUE TITLE
[bitnami/tomcat:10.1.2] extraVolumes: YAML parse error on tomcat/templates/deployment.yaml: error converting YAML to JSON: yaml: line 101: did not find expected key

### ISSUE THREAD

**Issue by visitingcat** [bitnami/charts#8681]
**Which chart**:

bitnami/tomcat:10.1.2 (suspect: all 10.x versions)

**Describe the bug**

Deploying chart with providing extraVolumes yields:

YAML parse error on tomcat/templates/deployment.yaml: error converting YAML to JSON: yaml: line 101: did not find expected key

**To Reproduce**

values.yaml

```
extraVolumes:
  - name: logs
    persistentVolumeClaim:
       claimName: logs
```

`helm install tomcat-test -f values.yaml bitnami/tomcat --version=10.1.2`

**Expected behavior**

I don't expect this error. It worked with version 9.6.1.

**Additional context**

None
