### ISSUE TITLE
[bitnami/minio] Can the Minio ingress configuration point to a subpath?

### ISSUE THREAD

**Issue by carolili** [bitnami/charts#8682]
**Which chart**: bitnami/minio

**Describe the bug**
Is it possible to use the ingress configuration to host Minio under a subpath such as https://myhostname.com/minio? The [configuration option seems to exist in the Helm chart](https://github.com/bitnami/charts/blob/master/bitnami/minio/values.yaml#L567) and the ingress is correctly created, however it only seems to lead to a "502 Bad Gateway" error.

I noticed an issue on GitHub mentioning that Minio doesn't support being hosted on a subpath: https://github.com/minio/minio/issues/10162 so I wanted to ask if you can confirm that it's possible to use the option in the Helm chart?

**To Reproduce**

I deploy minio with the TLS options below. I use the same options for minio-api but a different path:
```yaml
    ingress:
      enabled: true
      apiVersion: ""
      ingressClassName: "nginx"
      hostname: "myhostname.com"
      path: /minio(/|$)(.*)
      pathType: ImplementationSpecific
      servicePort: minio
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      tls: true
      selfSigned: false
      extraTls:
      - hosts:
          - myhostname.com
        secretName: myhostname.com
```
The ingress resources seem to be generated correctly (also for the minio-api with the different path):
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  annotations:
    meta.helm.sh/release-name: minio
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - myhostname.com
      secretName: myhostname.com
  rules:
    - host: myhostname.com
      http:
        paths:
          - path: /minio(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: minio
                port:
                  name: minio-console
```
The generated service and endpoints also look okay and seem to point to the correct target.

**Expected behavior**

I expect https://myhostname.com/minio to show the minio console instead of a "502 Bad Gateway".

**Additional context**

There is an issue on GitHub mentioning that minio doesn't support being hosted on a subpath: https://github.com/minio/minio/issues/10162

The Nginx rewrite configuration works with other applications ([see documentation](https://kubernetes.github.io/ingress-nginx/examples/rewrite/) for more info) so I was hoping it would also work with Minio.

Many thanks for any advice or pointers to the documentation regarding this matter. Please let me know if you spot any mistake in the configuration example.
