### ISSUE TITLE
[bitnami/galera] Fresh cluster fails (not safe to bootstrap)

### ISSUE THREAD

**Issue by Tricera-Hendrik-Weiss** [bitnami/charts#8685]
**Which chart**:

bitnami/galera chart version 6.5.0 app version 10.6.5

**Describe the bug**

I am using Kind (v0.11.1) to play arround with the galera chart. Setting up a new Kind Cluster with three untainted master nodes causes the galera cluster always to fail, whenever I provide a `wsrep_cluster_address=gcomm://galera-mariadb-galera-0,galera-mariadb-galera-1,galera-mariadb-galera-2` and a `rootUser` password. The error message is 

```
It is not safe to bootstrap form this node ('safe_to_bootstrap=0' is set in 'grastate.dat'). If you want to force bootstrap, set the environment variable MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes
```

Using 

```
galera:
  ## @param galera.name Galera cluster name
  ##
  name: galera
  ## Bootstraping options
  ## ref: https://github.com/bitnami/bitnami-docker-mariadb-galera#bootstraping
  ##
  bootstrap:
    ## @param galera.bootstrap.bootstrapFromNode Node to bootstrap from, you will need to change this parameter in case you want to bootstrap from other node
    ##
    bootstrapFromNode: "0"
    ## @param galera.bootstrap.forceSafeToBootstrap Force `safe_to_bootstrap: 1` in `grastate.date` file
    ## This will set safe_to_bootstrap=1 in the node indicated by bootstrapFromNode.
    ##
    forceSafeToBootstrap: true
  ## Credentials to perform backups
  ##
```

does not lead to any change at all. 

**To Reproduce**

1. Set up a new cluster
2. Deploy galera chart with wsrep_cluster_adress and rootUser password
3. See error

**Expected behavior**

Having a clustered galera with three instances
