### ISSUE TITLE
Documentation issue with postgresql-ha pgpool.customUsers

### ISSUE THREAD

**Issue by MrAmbiG** [bitnami/charts#8687]
**Which chart**:

postgresql-ha

**Describe the bug**

documentation:
The hierarchy mentioned for pgpool custom users seems to be conflicting with each other.
`pgpool.customUsers` is in conflict with `pgpool.username` and `pgpool.password` should it not be?

```yaml
pgpool:
    customUsers:
        usernames:
        passwords:
```

**Comment by carrodher** [comment]
The hierarchy is something like this:
```yaml
 ## Pgpool parameters
 ##
 pgpool:
   ## @param pgpool.customUsers Additional users that will be performing connections to the database using
   ## pgpool. Use this property in order to create new user/password entries that
   ## will be appended to the "pgpool_passwd" file
   ##
   customUsers: {}
   ## @param pgpool.usernames Comma or semicolon separated list of postgres usernames
   ## e.g:
   ## usernames: 'user01;user02'
   ##
   usernames: ""
   ## @param pgpool.passwords Comma or semicolon separated list of the associated passwords for the users above
   ## e.g:
   ## passwords: 'pass01;pass02'
   ##
   passwords: ""
```
being `customerUsers` and `usernames`/`passwords` at the same level since they have different purposes
