### ISSUE TITLE
Redis, Only one master, Limit size of AOF

### ISSUE THREAD

**Issue by OlivierMary** [bitnami/charts#8719]
**Which chart**: 

Redis

**Is your feature request related to a problem? Please describe.**

Yes, on NFS storage, Redis appendonly file grow a lot, ~100Go now with the default values.

When I see that:

```sh
127.0.0.1:6379>  config get auto-aof-rewrite-min-size
1) "auto-aof-rewrite-min-size"
2) "67108864"
127.0.0.1:6379>  config get auto-aof-rewrite-percentage
1) "auto-aof-rewrite-percentage"
2) "100"
127.0.0.1:6379>
```

For me the aof file will never grow over  ~67Mb, I seen in other issue, on master `BGREWRITEAOF` is never call. https://github.com/bitnami/charts/issues/8578#issuecomment-1005999074

But if I call it manually nothing append.... 

I have only one master. It's from the gitlab chart it's ask only one master and default's persistences options.

I thinks it's a NFS problem because on my NFS storage class the size of the pvc / pv is never check, so the volume is not bound to the default 8gi and see the full NFS space ~6Ti.......

How to limit this size?

Restart the container take a very long time..... loading 100go take ~30min, I can delete datas (it's only a session cache for gitlab), but I want to solve this for a long-term and not check this each time I need to move redis on another node....

**Describe the solution you'd like**

Limit the AOF size with only one master and on an unbound volume.

AOF limited :D

**Describe alternatives you've considered**

Delete datas each time the file is to large, but that mean users lost session,....

**Additional context**
 
N/A.

**Comment by juan131** [comment]
Hi @OlivierMary 

Could you please share the **values.yaml** you're using to install the chart and the Redis chart version you're using? Thanks in advance.

**Comment by OlivierMary** [comment]
Hi @juan131,

I use this https://gitlab.com/gitlab-org/charts/gitlab/-/blob/v5.5.2/values.yaml

It's the gitlab values so the sub values for redis of my values.yaml is: 

```yml
...
## Configuration of Redis
## https://docs.gitlab.com/charts/architecture/decisions#redis
## https://docs.gitlab.com/charts/installation/deployment.html#redis
redis:
  install: true
  existingSecret: gitlab-redis-secret
  existingSecretKey: redis-password
  usePasswordFile: true
  cluster:
    enabled: false
  metrics:
    enabled: false
...
```

So I just change the metrics to false, so 95% of the defaults values !

**Comment by OlivierMary** [comment]
@juan131 

I Forgot this information:

```yaml
- name: redis
  version: 11.3.4
  repository: https://charts.bitnami.com/bitnami
  condition: redis.install

```
