### ISSUE TITLE
etcd: peer and client auth settings

### ISSUE THREAD

**Issue by justinrush** [bitnami/charts#8729]
**Which chart**:

etcd 6.13.2

**Describe the bug**

I'm trying to deploy an ETCd cluster with peer and client TLS with certificate auth for clients. The client in this case will be Cortex. I can't seem to find the correct sets of values to set to make these things work together.

For the client cert, I'm using cert-manager with a clusterCA. I used this CRD to generate the client cert, key and CA secret:

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cortex-etcd-client
spec:
  secretName: cortex-etcd-client-tls
  issuerRef:
    name: clusterca
    kind: ClusterIssuer
  commonName: root
  subject:
    countries: ["US"]
    organizations: ["Acme"]
    organizationalUnits: ["Loony Toones"]
```

Then I deployed the chart using these values:
```yaml
auth:
  peer:
    secureTransport: true
    useAutoTLS: true
  client:
    secureTransport: true
    enableAuthentication: true
    useAutoTLS: false
    existingSecret: cortex-etcd-client-tls
    certFilename: tls.crt
    certKeyFilename: tls.key
    caFilename: ca.crt
replicaCount: 3
```

However, that resulted in these error messages on the server side:

```
{"level":"warn","ts":"2022-01-20T13:38:09.395Z","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"10.240.0.45:49006","server-name":"cortex-etcd-0.cortex-etcd-headless.cortex.svc.cluster.local","error":"remote error: tls: bad certificate"}
```

Using `openssl s_client` I found that the cert on the 2890 port was the self-signed etcd certs and the 2879 port had the expected client cert showing up.

I tried generating a certificate for the peers as well using this Certificate CRD (hoping that I could add all the peers as sans and use the same cert on all nodes):
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cortex-etcd-server
spec:
  secretName: cortex-etcd-server-tls
  issuerRef:
    name: clusterca
    kind: ClusterIssuer
  commonName: cortex-etcd.cortex.svc.cluster.local
  subject:
    countries: ["US"]
    organizations: ["Acme"]
    organizationalUnits: ["Looney Toones"]
  usages:
    - "signing"
    - "key encipherment"
    - "server auth"
    - "client auth"
  dnsNames:
    - cortex-etcd-0
    - cortex-etcd-1
    - cortex-etcd-2
    - cortex-etcd-0.cortex-etcd-headless.cortex.svc.cluster.local
    - cortex-etcd-1.cortex-etcd-headless.cortex.svc.cluster.local
    - cortex-etcd-2.cortex-etcd-headless.cortex.svc.cluster.local
    - cortex-etcd.cortex.svc.cluster.local
    - cortex-etcd
```

Then I deployed the chart using these values:
```yaml
auth:
  peer:
    secureTransport: true
    useAutoTLS: false
    existingSecret: cortex-etcd-server-tls
    certFilename: tls.crt
    certKeyFilename: tls.key
    enableAuthentication: false
    caFilename: ca.crt
  client:
    secureTransport: true
    enableAuthentication: true
    useAutoTLS: false
    existingSecret: cortex-etcd-client-tls
    certFilename: tls.crt
    certKeyFilename: tls.key
    caFilename: ca.crt
replicaCount: 3
```

The cluster nodes spewed the same error messages:
```
{"level":"warn","ts":"2022-01-20T13:28:54.290Z","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"10.240.0.191:37916","server-name":"cortex-etcd-0.cortex-etcd-headless.cortex.svc.cluster.local","error":"remote error: tls: bad certificate"}
```

The 2890 peer endpoint showed that it was using the cluster CA signed cert, but had this SSL error:
```
140165322630272:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../ssl/record/rec_layer_s3.c:1544:SSL alert number 42
```

Which I believe means that it required mTLS that I didn't provide. This is unexpected given that I set peer.enableAuthentication to false.

The only way I've been able to deply with both peer and client certs is by setting `useAutoTLS` to true for both:
```yaml
auth:
  peer:
    secureTransport: true
    useAutoTLS: true
  client:
    secureTransport: true
    useAutoTLS: true
replicaCount: 3
```

However, that doesn't enable client certificate based authentication.

**Comment by juan131** [comment]
Hi @justinrush 

Let's go back to your 1st scenario and keep the peer authentication using auto-generated TLS certificate. Could you please apply the changes below in your client auth settings and retry?

```diff
  client:
    secureTransport: true
-   enableAuthentication: true
+   enableAuthentication: false
    useAutoTLS: false
    existingSecret: cortex-etcd-client-tls
    certFilename: tls.crt
    certKeyFilename: tls.key
    caFilename: ca.crt
```

AFAIK the certificates you're auto-generating using CertManager don't include the etcd pods' hostname in the dnsNames field and that could be problematic.

I created a tutorial in the past for Kafka (it's not the same but it's similar) about how to enable mTLS and use certificates generated by CertManager, see: https://github.com/juan131/kafka-mtls-for-k8s
In this tutorial, there's a `resources/` folder with the Certificate manifests I used to generate the TLS certs for Kafka and, as you can see, I had to include in the `dnsNames` the pods' hostnames.

- https://github.com/juan131/kafka-mtls-for-k8s/blob/main/resources/certs.yaml

**Comment by justinrush** [comment]
That gives me the same bad certificate errors.

RE: cert-manager generated certs - the `cortex-etcd-server` Certificate has all the etcd pod names in their DNSNames... what names are you expecting to see that aren't there? FWIW the helm install command is:

`helm install cortex-etcd bitnami/etcd -n cortex -f values.yaml`

**Comment by levente-simon** [comment]
Hey @justinrush 

The undocumented behavior of setting the ca is to implicitly enable mTLS [(see here)](https://github.com/etcd-io/etcd/blob/main/client/pkg/transport/listener.go#L482)

```
 	if info.TrustedCAFile != "" || info.ClientCertAuth {
 		cfg.ClientAuth = tls.RequireAndVerifyClientCert
 	}
```
 

On the other hand, somehow you need to set the trusted ca for the clients to be able to verify the server cert, so if you don't want to authenticate the clients / peers, maybe the best is to mount the it from the secret as a systemwide ca. Something like this:

```
auth:
  peer:
    secureTransport: true
    useAutoTLS: false
    existingSecret: etcd-peer-tls
    certFilename: tls.crt
    certKeyFilename: tls.key
    enableAuthentication: false
  client:
    secureTransport: true
    useAutoTLS: false
    existingSecret: etcd-client-tls
    certFilename: tls.crt
    certKeyFilename: tls.key
    enableAuthentication: false
extraVolumes:
  - name: ca-volume
    secret:
      secretName: etcd-peer-tls
      items:
        - key: ca.crt
          path: corp-ca.pem
extraVolumeMounts:
  - name: ca-volume
    mountPath: /etc/ssl/certs/corp-ca.pem
    subPath: corp-ca.pem
```

It's working for me in a more or less same setup, with cert-manager and a vault pki as issuer.

**Comment by justinrush** [comment]
Odd, this also didn't work for me. What does your client and peer certificate request look like?

**Comment by levente-simon** [comment]
Sorry for the syntax if you are not into terraform, but I hope the point is there. 
The external FQDN in this case is `etcd.corp`, so for the client I ask for a cert with this in the SAN, plus the internal name (in my case it is lazily `*.etcd-headless.etcd.svc.cluster.local`) for both the client and the peer (frankly, I don't know why, but without having the internal name for the client it's still dropping bad certificate messages, but this way it works and I think it's not a big issue).

```
resource "kubernetes_manifest" "cert_etcd_client" {
  depends_on = [ rancher2_namespace.etcd ]

  manifest   = {
    "apiVersion" = "cert-manager.io/v1"
    "kind"       = "Certificate"
    "metadata"   = {
      "name"        = "etcd-client"
      "namespace"   = "etcd"
    }
    "spec"       = {  
      "secretName"  = "etcd-client-tls"
      "duration"    = "12h0m0s"
      "renewBefore" = "2h0m0s"
      "subject"     = {
        "organizations" = [ "Corp" ]
      }
      "privateKey"  = {
        "algorithm"     = "RSA"
        "encoding"      = "PKCS1"
        "size"          = "2048"
      }
      "usages"      = [ "server auth"  ]
      "dnsNames"    = [ "etcd.corp",
                        "*.etcd-headless.etcd.svc.cluster.local" ]
      "issuerRef"   = {
        "name"  = "vault-issuer"
        "kind"  = "ClusterIssuer"
      }
    }
  }
}

resource "kubernetes_manifest" "cert_etcd_peer" {
  depends_on = [ rancher2_namespace.etcd ]

  manifest   = {
    "apiVersion" = "cert-manager.io/v1"
    "kind"       = "Certificate"
    "metadata"   = {
      "name"        = "etcd-peer"
      "namespace"   = "etcd"
    } 
    "spec"       = {
      "secretName"  = "etcd-peer-tls"
      "duration"    = "12h0m0s"
      "renewBefore" = "2h0m0s"
      "subject"     = {
        "organizations" = [ "Corp" ]
      } 
      "privateKey"  = {
        "algorithm"     = "RSA"
        "encoding"      = "PKCS1"
        "size"          = "2048"
      } 
      "usages"      = [ "server auth", "client auth" ]
      "dnsNames"    = [ "*.etcd-headless.etcd.svc.cluster.local" ]
      "issuerRef"   = {
        "name"  = "vault-issuer"
        "kind"  = "ClusterIssuer"
      }
    }
  }
} 
```

**Comment by DenisMedeiros** [comment]
If this may help anyone, I was facing this issue when enabling TLS (certificates generated by cert-manager) for client and peer auth. I was able to fix it by defining environment variables with the certs for the `etcdctl` CLI (to force it to use cert-authentication). The variables were `ETCDCTL_CACERT`, `ETCDCTL_CERT`, and `ETCDCTL_KEY`.

Certificate (for peer and client are similar to the one below).

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-client
  namespace: apisix
spec:
  secretName: etcd-client-tls
  duration: 17520h # 730d
  renewBefore: 4320h # 180d
  issuerRef:
    name: apisix-issuer
    kind: Issuer
  usages:
    - server auth
    - client auth
  commonName: apisix-etcd
  dnsNames:
    - "*.apisix-etcd.apisix.svc.cluster.local"
    - "*.apisix-etcd-headless.apisix.svc.cluster.local"
```

Chart options:

```yaml
logLevel: debug
image:
  registry: docker.io
  repository: bitnami/etcd
  tag: 3.5.5
  debug: true
replicaCount: 3
auth:
  rbac:
    enabled: true
    create: true
    allowNoneAuthentication: false
    existingSecret: etcd-root-secret
  client:
    enableAuthentication: true
    useAutoTLS: false
    secureTransport: true
    existingSecret: etcd-client-tls
    certFilename: tls.crt
    certKeyFilename: tls.key
    caFilename: ca.crt
  peer:
    enableAuthentication: true
    useAutoTLS: true
    secureTransport: true
    existingSecret: etcd-peer-tls
    certFilename: tls.crt
    certKeyFilename: tls.key
    caFilename: ca.crt
extraEnvVars:
  - name: ETCDCTL_CACERT
    value: /opt/bitnami/etcd/certs/client/ca.crt
  - name: ETCDCTL_CERT
    value: /opt/bitnami/etcd/certs/client/tls.crt
  - name: ETCDCTL_KEY
    value: /opt/bitnami/etcd/certs/client/tls.key
```
