### ISSUE TITLE
KEYCLOAK_DATABASE_SCHEMA causes a crashloop if the schema doesn't already exist

### ISSUE THREAD

**Issue by doctorpangloss** [bitnami/charts#8738]
**Which chart**:

keycloak 6.0.0

**Describe the bug**

When specifying a Keycloak schema that isn't public using `

> KEYCLOAK_DATABASE_SCHEMA

`, if the schema doesn't pre-exist the creation of keycloak will fail.

**To Reproduce**

```
replicaCount: 1
nodeSelector:
  kubernetes.io/os: linux
  role: controller
postgresql:
  enabled: false
...
extraEnvVars:
  - name: KEYCLOAK_DATABASE_SCHEMA
    value: "keycloak"
  - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
    value: "true"
```

**Expected behavior**

It should probably `create schema if not exists %KEYCLOAK_DATABASE_SCHEMA%`.
