### ISSUE TITLE
Health ingress uses old beta network api version (`extensions/v1beta1`)

### ISSUE THREAD

**Issue by christianacca** [bitnami/charts#8739]
**Which chart**:

aspnetcore 3.0.3

**Describe the bug**

The health ingress is using an old beta version of the ingress object. This is failing when deploying to a k8 v1.19+ cluster

**Expected behavior**

The [health-ingress.yaml](https://github.com/bitnami/charts/blob/master/bitnami/aspnet-core/templates/health-ingress.yaml) needs updating to auto-detect the api version of the networking capability - just like the ingress.yaml template already does. EG:

```yaml
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
```

It would also make sense to replace the use of annotations to define the ingress class, to instead use the standards field `ingressClassName`. EG:

```yaml
spec:
  {{- if and .Values.healthIngress.ingressClassName (include "common.ingress.supportsIngressClassname" .) }}
  ingressClassName: {{ .Values.healthIngress.ingressClassName | quote }}
  {{- end }}
```
