### ISSUE TITLE
Elasticsearch CORS parameters - Config

### ISSUE THREAD

**Issue by Sam-Sundar-Apty** [bitnami/charts#8755]
**Which chart**:

elasticsearch:6.7.0
**Describe the bug**

We need to add below cors parameter to `elasticsearch.yml` 
```yaml
http.cors.enabled : true
http.cors.allow-origin: "*"
http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length
http.cors.allow-credentials: true
```

We tried to add under `config:` like below

```yaml
config: 
     http: 
       cors.allow-origin: "*"
       cors.enabled : true
       cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
       cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length
```           

While adding this to config, adds the data to `elasticsearch.yml` but we have some data in `elasticsearch.yml` which are generated automatically by the chart like below and these values are getting replaced by `config` values.
```yaml
http:
  port: 9200
path:
  data: /bitnami/elasticsearch/data
transport:
  tcp:
    port: 9300
network:
  host: 10.32.0.38
  publish_host: 10.32.0.38
  bind_host: 0.0.0.0
cluster:
  name: elastic
node:
  name: es-coordinating-only-0
  master: false
  data: false
  ingest: false
discovery:
  zen:
    ping:
      unicast:
        hosts:
        - es-elasticsearch-master.default.svc.cluster.local
        - es-coordinating-only.default.svc.cluster.local
        - es-elasticsearch-data.default.svc.cluster.local
    minimum_master_nodes: 2
  initial_state_timeout: 5m
gateway:
  recover_after_nodes: 3
```  

According to [this issue](https://github.com/bitnami/charts/issues/6718), he solved it by adding the same to `initscripts`, so i added the same like below and the same is getting mounted to my pod, but the script is not getting executed. 
```yaml
initScripts: 
      my_init_script.sh: |
        #!/bin/sh
        echo "http.cors.enabled : true
        http.cors.allow-origin: "*"
        http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
        http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length
        http.cors.allow-credentials: true" >> /opt/bitnami/elasticsearch/config/elasticsearch.yml
```

--------------------------------------------------------------------------------------------------------------------
Attaching my chart.yml below for reference.

```yaml
## Elasticsearch cluster name
## @param name Elasticsearch cluster name
##
name: elastic
## @param plugins Comma, semi-colon or space separated list of plugins to install at initialization
## ref: https://github.com/bitnami/bitnami-docker-elasticsearch#environment-variables
##
plugins: ""
## @param snapshotRepoPath File System snapshot repository path
## ref: https://github.com/bitnami/bitnami-docker-elasticsearch#environment-variables
##
snapshotRepoPath: ""
## @param config Override elasticsearch configuration
##
config: {}
  # extraConfig:
    # http: 
    #    cors.allow-origin: "*"
    #    cors.enabled : true
    #    cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
    #    cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length
  # extraConfig:
  #       http.cors.enabled : true
  #       http.cors.allow-origin: "*"
  #       http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
  #       http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length
  #       http.cors.allow-credentials: true
## @param extraConfig Append extra configuration to the elasticsearch node configuration
## Use this instead of `config` to add more configuration
## See below example:
## extraConfig:
##   node:
##     store:
##       allow_mmap: false
## ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html
##
extraConfig: {}
## @param extraVolumes A list of volumes to be added to the pod
## Example Use Case: mount ssl certificates when elasticsearch has tls enabled
## extraVolumes:
##   - name: es-certs
##     secret:
##       defaultMode: 420
##       secretName: es-certs
extraVolumes: []
## @param extraVolumeMounts A list of volume mounts to be added to the pod
## extraVolumeMounts:
##   - name: es-certs
##     mountPath: /certs
##     readOnly: true
extraVolumeMounts: []
## @param initScripts Dictionary of init scripts. Evaluated as a template.
## Specify dictionary of scripts to be run at first boot
## Alternatively, you can put your scripts under the files/docker-entrypoint-initdb.d directory
## For example:
## initScripts:
##   my_init_script.sh: |
##      #!/bin/sh
##      echo "Do something."
##
initScripts: 
      my_init_script.sh: |
        #!/bin/sh
        echo "http.cors.enabled : true
        http.cors.allow-origin: "*"
        http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
        http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length
        http.cors.allow-credentials: true" >> /opt/bitnami/elasticsearch/config/elasticsearch.yml
## @param initScriptsCM ConfigMap with the init scripts. Evaluated as a template.
## Note: This will override initScripts
##
initScriptsCM: ""
## @param initScriptsSecret Secret containing `/docker-entrypoint-initdb.d` scripts to be executed at initialization time that contain sensitive data. Evaluated as a template.
##
initScriptsSecret: ""
## @param extraEnvVars Array containing extra env vars to be added to all pods (evaluated as a template)
## For example:
## extraEnvVars:
##  - name: MY_ENV_VAR
##    value: env_var_value
##
```

**Comment by juan131** [comment]
Hi @Sam-Sundar-Apty 

You don't need to use the `config` parameter that overwrites the default configuration auto-generated, but `extraConfig` instead that appends your custom configuration. Find more info below:

- https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/values.yaml#L168

**Comment by Sam-Sundar-Apty** [comment]
Hey @juan131,

While we add extra params like below, ES is not able to pick those and is crashing
```yaml
config: 
  extraConfig:
    http: 
       cors.allow-origin: "*"
       cors.enabled : true
       cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
       cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length
```

----------------------------------------------------------


```bash
	Suppressed: java.lang.IllegalArgumentException: unknown setting [extraConfig.http.cors.enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:530) ~[elasticsearch-6.7.0.jar:6.7.0]
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:475) ~[elasticsearch-6.7.0.jar:6.7.0]
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:446) ~[elasticsearch-6.7.0.jar:6.7.0]
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:417) ~[elasticsearch-6.7.0.jar:6.7.0]
		at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:148) ~[elasticsearch-6.7.0.jar:6.7.0]
		at org.elasticsearch.node.Node.<init>(Node.java:374) ~[elasticsearch-6.7.0.jar:6.7.0]
		at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.7.0.jar:6.7.0]
		at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.7.0.jar:6.7.0]
		at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.7.0.jar:6.7.0]
		at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.7.0.jar:6.7.0]
		at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.7.0.jar:6.7.0]
		at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.7.0.jar:6.7.0]
		at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.7.0.jar:6.7.0]
		at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.7.0.jar:6.7.0]
		at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.7.0.jar:6.7.0]
		at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.7.0.jar:6.7.0]
		at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.7.0.jar:6.7.0]
```

Note: I'm using 6.7.0 version of ES. Image: docker.io/bitnami/elasticsearch:6.7.0

**Comment by juan131** [comment]
Hi @Sam-Sundar-Apty 

You're setting a non-existing `config.extraConfig` parameter. You need to use `extraConfig` instead:

```yaml
extraConfig:
  http: 
    cors.allow-origin: "*"
    cors.enabled : true
    cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
    cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length
```

**Comment by Sam-Sundar-Apty** [comment]
Hey @juan131,

I tried add in extraConfig like below
```yaml
extraConfig: 
    http:
      cors.enabled : true
      cors.allow-origin: "*"
      cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
      cors.allow-headers: X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization, Access-Control-Allow-Headers, Accept
```

And it's getting created with a file `my_elasticsearch.yml` under `/opt/bitnami/elasticsearch/config/` but ES is not loading this config.

I guess it needs the config in `/opt/bitnami/elasticsearch/config/elasticsearch.yml` file.

![Image](https://user-images.githubusercontent.com/83000807/150792652-619ba125-52b8-4199-9f5f-a9a0e611d236.png)

**Comment by juan131** [comment]
Hi @Sam-Sundar-Apty 

As you mentioned, the `extraConfig` parameter mounts a new configuration file at `/opt/bitnami/elasticsearch/config` with the name `my_elasticsearch.yml`. The Bitnami Elasticsearch container uses the logic below to detect the presence of this file, and it merges its content with the configuration available at `elasticsearch.yml`, see:

- https://github.com/bitnami/bitnami-docker-elasticsearch/blob/master/7/debian-10/rootfs/opt/bitnami/scripts/libelasticsearch.sh#L391

Therefore, this configuration is actually applied.

**Comment by Sam-Sundar-Apty** [comment]
Hey @juan131,

If it's getting applied, i shouldn't get CORS errors. But i'm getting the errors.

**Comment by juan131** [comment]
Yes, the same applies to the Bitnami ElasticSearch container `6.x.x`:

- https://github.com/bitnami/bitnami-docker-elasticsearch/blob/master/6/debian-10/rootfs/opt/bitnami/scripts/libelasticsearch.sh#L391

In any case, you can inspect if that specific function "elasticsearch_custom_configuration" is present in the image you're using by running it locally and inspecting the `/opt/bitnami/scripts/libelasticsearch.sh` library.

**Comment by Sam-Sundar-Apty** [comment]
Hey @juan131,


Just now checked and my image doesn't have `/opt/bitnami/scripts/libelasticsearch.sh`. 

Please find reference below 
![image](https://user-images.githubusercontent.com/83000807/150993685-78b654d2-f6b4-490d-ab96-36025bf77c83.png)
Is there any image with 6.7.0 version which will have the `/opt/bitnami/scripts/libelasticsearch.sh` scripts ?

**Comment by juan131** [comment]
Hi @Sam-Sundar-Apty 

Your image is quite old (`6.7.0` was published 2 years ago) and it doesn't include the initialization based on bash scripts (it uses a tool called "nami" that we already deprecated). As a consequence, I'm afraid that extending the configuration using `extendedConf` won't be a possibility for you and you'll have to use custom init scripts to achieve that.

**Comment by Sam-Sundar-Apty** [comment]
Hey @juan131,

I tried initscripts like below and it's getting mounted but not getting executed :(

```yaml
initScripts: 
      my_init_script.sh: |
        #!/bin/sh
        echo "http.cors.enabled : true
        http.cors.allow-origin: "*"
        http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
        http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length
        http.cors.allow-credentials: true" >> /opt/bitnami/elasticsearch/config/elasticsearch.yml
```
