### ISSUE TITLE
Redis Sentinel - Failover issue

### ISSUE THREAD

**Issue by donch** [bitnami/charts#8756]
**Which chart**:

redis-16.1.0

**Describe the bug**

I'm deploying a Redis Sentinel cluster (3 nodes) in Kubernetes 1.18.20 and the failover mechanism isn't functionnal when i delete the master pod.

**To Reproduce**

Deploy a Redis Sentinel cluster with helm : 

`helm upgrade --install  bitnami/redis -f values.yaml --version 16.1.0`

I'm using the following values.yaml : 

```yaml
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: "local-path"
  redis:
    password: ""

kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
commonLabels: {}
commonAnnotations: {}
clusterDomain: cluster.local
extraDeploy: []

diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity

image:
  registry: docker.io
  repository: bitnami/redis
  tag: 6.2.6-debian-10-r103
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false

architecture: replication
auth:
  enabled: false
  sentinel: false
  password: ""
  existingSecret: ""
  existingSecretPasswordKey: ""
  usePasswordFiles: false
commonConfiguration: |-
  appendonly yes
  save ""
existingConfigmap: ""

master:
  configuration: ""
  disableCommands:
    - FLUSHDB
    - FLUSHALL
  command: []
  args: []
  preExecCmds: []
  extraFlags: []
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  containerPorts:
    redis: 6379
  startupProbe:
    enabled: false
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
  customStartupProbe: {}
  customLivenessProbe: {}
  customReadinessProbe: {}
  resources:
    limits: {}
    requests: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
  schedulerName: ""
  updateStrategy:
    type: RollingUpdate
    rollingUpdate: {}
  priorityClassName: ""
  hostAliases: []
  podLabels: {}
  podAnnotations: {}
  shareProcessNamespace: false
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations:
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      operator: Equal
      value: "true"
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      operator: Equal
      value: "true"
  topologySpreadConstraints: {}
  lifecycleHooks: {}
  extraVolumes: []
  extraVolumeMounts: []
  sidecars: []
  initContainers: []
  persistence:
    enabled: true
    medium: ""
    path: /data
    subPath: ""
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: {}
    selector: {}
    dataSource: {}
    existingClaim: ""
  service:
    type: ClusterIP
    ports:
      redis: 6379
    nodePorts:
      redis: ""
    externalTrafficPolicy: Cluster
    extraPorts: []
    clusterIP: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    annotations: {}
  terminationGracePeriodSeconds: 30

replica:
  replicaCount: 3
  configuration: ""
  disableCommands:
    - FLUSHDB
    - FLUSHALL
  command: []
  args: []
  preExecCmds: []
  extraFlags: []
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  containerPorts:
    redis: 6379
  startupProbe:
    enabled: false
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
  customStartupProbe: {}
  customLivenessProbe: {}
  customReadinessProbe: {}
  resources:
    limits: {}
    requests: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
  schedulerName: ""
  updateStrategy:
    type: RollingUpdate
    rollingUpdate: {}
  priorityClassName: ""
  podManagementPolicy: ""
  hostAliases: []
  podLabels: {}
  podAnnotations: {}
  shareProcessNamespace: false
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations:
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      operator: Equal
      value: "true"
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      operator: Equal
      value: "true"
  topologySpreadConstraints: {}
  lifecycleHooks: {}
  extraVolumes: []
  extraVolumeMounts: []
  sidecars: []
  initContainers: []
  persistence:
    enabled: true
    medium: ""
    path: /data
    subPath: ""
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: {}
    selector: {}
    dataSource: {}
  service:
    type: ClusterIP
    ports:
      redis: 6379
    nodePorts:
      redis: ""
    externalTrafficPolicy: Cluster
    extraPorts: []
    clusterIP: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    annotations: {}
  terminationGracePeriodSeconds: 30
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 11
    targetCPU: ""
    targetMemory: ""

sentinel:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/redis-sentinel
    tag: 6.2.6-debian-10-r100
    pullPolicy: IfNotPresent
    pullSecrets: []
    debug: false
  masterSet: mymaster
  quorum: 2
  automateClusterRecovery: false
  downAfterMilliseconds: 8000
  failoverTimeout: 4000
  parallelSyncs: 1
  configuration: ""
  command: []
  args: []
  preExecCmds: []
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  containerPorts:
    sentinel: 26379
  startupProbe:
    enabled: false
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
  customStartupProbe: {}
  customLivenessProbe: {}
  customReadinessProbe: {}
  resources:
    limits: {}
    requests: {}
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
  lifecycleHooks: {}
  extraVolumes: []
  extraVolumeMounts: []
  service:
    type: ClusterIP
    ports:
      redis: 6379
      sentinel: 26379
    nodePorts:
      redis: ""
      sentinel: ""
    externalTrafficPolicy: Cluster
    extraPorts: []
    clusterIP: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    annotations: {}
  terminationGracePeriodSeconds: 30

networkPolicy:
  enabled: false
  allowExternal: true
  extraIngress: []
  extraEgress: []
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
podSecurityPolicy:
  create: false
  enabled: false
rbac:
  create: false
  rules: []
serviceAccount:
  create: true
  name: ""
  automountServiceAccountToken: true
  annotations: {}
pdb:
  create: false
  minAvailable: 1
  maxUnavailable: ""
tls:
  enabled: false
  authClients: true
  autoGenerated: false
  existingSecret: ""
  certificatesSecret: ""
  certFilename: ""
  certKeyFilename: ""
  certCAFilename: ""
  dhParamsFilename: ""

metrics:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/redis-exporter
    tag: 1.33.0-debian-10-r27
    pullPolicy: IfNotPresent
    pullSecrets: []
  redisTargetHost: "localhost"
  extraArgs: {}
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
  extraVolumes: []
  extraVolumeMounts: []
  resources:
    limits: {}
    requests: {}
  podLabels: {}
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
  service:
    type: ClusterIP
    port: 9121
    externalTrafficPolicy: Cluster
    extraPorts: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    annotations: {}
  serviceMonitor:
    enabled: false
    namespace: ""
    interval: 30s
    scrapeTimeout: ""
    relabellings: []
    metricRelabelings: []
    honorLabels: false
    additionalLabels: {}
  prometheusRule:
    enabled: false
    namespace: ""
    additionalLabels: {}
    rules: []

volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 10-debian-10-r312
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits: {}
    requests: {}
  containerSecurityContext:
    runAsUser: 0

sysctl:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 10-debian-10-r312
    pullPolicy: IfNotPresent
    pullSecrets: []
  command: []
  mountHostSys: false
  resources:
    limits: {}
    requests: {}

useExternalDNS:
  enabled: false
  suffix: ""
  annotationKey: external-dns.alpha.kubernetes.io/
  additionalAnnotations: {}
```

Once the cluster is UP, I'm able to get the master node : 

```
root@redis-cli:/data# redis-cli  -h redis -p 26379 sentinel get-master-addr-by-name mymaster
1) "redis-node-0.redis-headless.default.svc.cluster.local"
2) "6379"
```

I taint the node on which is scheduled `redis-node-0` to prevent any reschedule and then, I delete the pod `redis-node-0`

Even after a while, the master is still `redis-node-0` and no failover is triggered.

Here are the logs of the whole cluster (using Stern) since a delete the master.

```
- redis-node-0 › redis
- redis-node-0 › sentinel
redis-node-1 sentinel 1:X 24 Jan 2022 12:17:58.020 * +fix-slave-config slave redis-node-2.redis-headless.default.svc.cluster.local:6379 redis-node-2.redis-headless.default.svc.cluster.local 6379 @ mymaster redis-node-0.redis-headless.default.svc.cluster.local 6379
redis-node-2 redis 1:S 24 Jan 2022 12:17:58.027 * REPLICAOF would result into synchronization with the master we are already connected with. No operation performed.
redis-node-2 sentinel 1:X 24 Jan 2022 12:18:03.523 * +fix-slave-config slave redis-node-1.redis-headless.default.svc.cluster.local:6379 redis-node-1.redis-headless.default.svc.cluster.local 6379 @ mymaster redis-node-0.redis-headless.default.svc.cluster.local 6379
redis-node-1 redis 1:S 24 Jan 2022 12:18:03.518 * REPLICAOF would result into synchronization with the master we are already connected with. No operation performed.
redis-node-1 redis 1:S 24 Jan 2022 12:18:03.915 * REPLICAOF would result into synchronization with the master we are already connected with. No operation performed.
redis-node-1 sentinel 1:X 24 Jan 2022 12:18:03.914 * +fix-slave-config slave redis-node-1.redis-headless.default.svc.cluster.local:6379 redis-node-1.redis-headless.default.svc.cluster.local 6379 @ mymaster redis-node-0.redis-headless.default.svc.cluster.local 6379
redis-node-1 sentinel 1:X 24 Jan 2022 12:18:05.186 # +sdown sentinel 2a09ba7abbb41ee71e79087310d75f9809c3c815 redis-node-0.redis-headless.default.svc.cluster.local 26379 @ mymaster redis-node-0.redis-headless.default.svc.cluster.local 6379
redis-node-2 sentinel 1:X 24 Jan 2022 12:18:05.236 # +sdown sentinel 2a09ba7abbb41ee71e79087310d75f9809c3c815 redis-node-0.redis-headless.default.svc.cluster.local 26379 @ mymaster redis-node-0.redis-headless.default.svc.cluster.local 6379
redis-node-2 sentinel 1:X 24 Jan 2022 12:18:05.601 # +sdown master mymaster redis-node-0.redis-headless.default.svc.cluster.local 6379
redis-node-1 sentinel 1:X 24 Jan 2022 12:18:06.181 # +sdown master mymaster redis-node-0.redis-headless.default.svc.cluster.local 6379

redis-node-1 redis 1:S 24 Jan 2022 12:18:57.473 # MASTER timeout: no data nor PING received...
redis-node-1 redis 1:S 24 Jan 2022 12:18:57.473 # Connection with master lost.
redis-node-1 redis 1:S 24 Jan 2022 12:18:57.473 * Caching the disconnected master state.
redis-node-1 redis 1:S 24 Jan 2022 12:18:57.473 * Reconnecting to MASTER redis-node-0.redis-headless.default.svc.cluster.local:6379
redis-node-1 redis 1:S 24 Jan 2022 12:18:57.478 # Unable to connect to MASTER: Invalid argument
redis-node-1 redis 1:S 24 Jan 2022 12:18:57.478 * Connecting to MASTER redis-node-0.redis-headless.default.svc.cluster.local:6379
redis-node-1 redis 1:S 24 Jan 2022 12:18:57.481 # Unable to connect to MASTER: Invalid argument
redis-node-2 redis 1:S 24 Jan 2022 12:18:57.531 # MASTER timeout: no data nor PING received...
redis-node-2 redis 1:S 24 Jan 2022 12:18:57.531 # Connection with master lost.
redis-node-2 redis 1:S 24 Jan 2022 12:18:57.531 * Caching the disconnected master state.
redis-node-2 redis 1:S 24 Jan 2022 12:18:57.531 * Reconnecting to MASTER redis-node-0.redis-headless.default.svc.cluster.local:6379
redis-node-2 redis 1:S 24 Jan 2022 12:18:57.537 # Unable to connect to MASTER: Invalid argument
redis-node-2 redis 1:S 24 Jan 2022 12:18:57.537 * Connecting to MASTER redis-node-0.redis-headless.default.svc.cluster.local:6379
redis-node-2 redis 1:S 24 Jan 2022 12:18:57.542 # Unable to connect to MASTER: Invalid argument
redis-node-1 redis 1:S 24 Jan 2022 12:18:58.487 * Connecting to MASTER redis-node-0.redis-headless.default.svc.cluster.local:6379
redis-node-1 redis 1:S 24 Jan 2022 12:18:58.493 # Unable to connect to MASTER: Invalid argument
redis-node-2 redis 1:S 24 Jan 2022 12:18:58.546 * Connecting to MASTER redis-node-0.redis-headless.default.svc.cluster.local:6379
redis-node-2 redis 1:S 24 Jan 2022 12:18:58.553 # Unable to connect to MASTER: Invalid argument
redis-node-2 redis 1:S 24 Jan 2022 12:18:59.559 * Connecting to MASTER redis-node-0.redis-headless.default.svc.cluster.local:6379
redis-node-2 redis 1:S 24 Jan 2022 12:18:59.564 # Unable to connect to MASTER: Invalid argument
redis-node-1 redis 1:S 24 Jan 2022 12:18:59.500 * Connecting to MASTER redis-node-0.redis-headless.default.svc.cluster.local:6379
```

**Expected behavior**

As the quorum configuration is 2, failover should be triggered once the master is killed.

**Additional context**

When I remove the taint on my node, a Redis pod is rescheduled and failover happens, but in the meantime, the cluster isn't functionally until the pod comes up.

I think is more or less related to the use of FQDN in the configuration files. I'm able to reproduce this behavior with chart version 15.7.6.

I have tested with an older version of the chart (15.3.0) in which all configuration files use IP addresses instead of FQDN and the failover is working properly (e.g. a new master is elected as soon as I delete the master).

Is there any workaround? Or maybe I have missed something? 

Thanks
