### ISSUE TITLE
[bitnami/keycloak]  Self-signed certificate overriding cert-manager issued certificate

### ISSUE THREAD

**Issue by jordanbailes** [bitnami/charts#8763]
**Which chart**:
bitnami/keycloak

**Describe the bug**
We deploy keycloak with a cert-manager, which, when the certificate is provided by the cert-manager, works, but _sometimes_ end up with a self-signed certificate by the "keycloak-ca"  authority and cannot access the front end because of this. 

When the issue occurs the self-signed certificate replaces the one issued by the cert-manager inside of the certificate secret. 

When the keycloak chart is used with lets-encrypt as the cert-manager, this can lead to an additional difficult situation where a certificate can't be issued anymore by the cert-manager. This is because lets-encrypt has a rate-limit of 5 certificates per week for the same configuration.

`    message: 'The certificate request has failed to complete and will be retried:
      Failed to wait for order resource "keycloak.stage.company.dev-tls-342244232"
      to become ready: order is in "errored" state: Failed to create Order: 429 urn:ietf:params:acme:error:rateLimited:
      Error creating new order :: too many certificates (5) already issued for this
      exact set of domains in the last 168 hours: keycloak.stage.company.dev: see https://letsencrypt.org/docs/rate-limits/'
    observedGeneration: 1
    reason: Failed
    status: "False"
    type: Issuing`

**Expected behavior**
Keycloak does not override the certificate created by the nominated cert manager when a cert manager annotation is provided. 

**Additional context**
helm-values

```yaml
extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "-Dkeycloak.frontendUrl=https://keycloak.stage.company.url/auth"
    - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
      value: "true"

ingress:
  enabled: true
  tls: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

auth:
  tls:
    enabled: false
    autogenerated: false
```
