### ISSUE TITLE
[bitnami/solr] Allow custom secret key for auth password

### ISSUE THREAD

**Issue by tom-schoener** [bitnami/charts#8773]
**Which chart**:

bitnami/solr:3.0.2

**Is your feature request related to a problem? Please describe.**

Currently the solr Helm Chart allows to set an auth password via secret using the secret name provided with `auth.existingSecret`. This assumes the secret key to be `solr-password`.

**Describe the solution you'd like**

Introduce the values `auth.existingSecretPasswordKey`.

**Describe alternatives you've considered**

It is possible to work around this problem using `extraEnvVars` like so:

```yaml
extraEnvVars:
  - name: SOLR_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: solr-credentials
        key: password
        optional: false
```

It works, but this is not a very elegant solution, considering the other configuration. 

**Additional context**

In many charts this is already possible (See `auth.existingSecretPasswordKey` at https://github.com/bitnami/charts/tree/master/bitnami/redis#redis-common-configuration-parameters). 

Edit: Looking at other charts, it's not common to configure the username in secrets. Therefore, this is no longer a requirement.
