### ISSUE TITLE
[bitnami/postgresql-ha] Expose extra ports for the sidecar container of pgpool

### ISSUE THREAD

**Issue by daniel4wong** [bitnami/charts#8789]
I would like to add the pgadmin container as a sidecar container to pgpool.
So I would like to expose port 80 or 443.

Could values.yaml support to expose extra port as below: `service.extraPorts: []`?

Ref: [https://docs.bitnami.com/kubernetes/infrastructure/postgresql-ha/configuration/configure-sidecar-init-containers/](https://docs.bitnami.com/kubernetes/infrastructure/postgresql-ha/configuration/configure-sidecar-init-containers/)

Below is the values.yaml i have tried but the service "postgresql-ha-pgadmin" has not been created:
```yaml
pgpool:
  sidecars:
  - name: pgadmin
    image: docker.io/dpage/pgadmin4
    imagePullPolicy: Always
    ports:
    - name: pgadmin
      containerPort: 80
    env:
    - name: PGADMIN_DEFAULT_EMAIL
      value: "username@gmail.com"
    - name: PGADMIN_DEFAULT_PASSWORD
      value: "password"
  service:
    extraPorts:
    - name: postgresql-ha-pgadmin
      port: 80
      targetPort: 80
```
