### ISSUE TITLE
[bitnami/rabbitmq-operator] Pods failing at default-user-credential-updater (no such file or directory)

### ISSUE THREAD

**Issue by pitwegner** [bitnami/charts#8800]
**Which chart**:

bitnami/rabbitmq-operator version 2.2.2

**Describe the bug**

The Operator itself starts correctly. The instance does not. The Pods seem to start correctly, the liveness probe is successful and the management interface can be accessed. Also, the credentials from the vault secret work logging in. However, the default-user-credential-updater container crashes soon after the container start, letting the entire pod fail.

**To Reproduce**


1. Deploy Rabbitmq Operator using helm chart
2. Setup Vault authentication (not sure if necessary for reproducing the issue)
3. Create Rabbitmq Instance
4. Let Pods get created
5. Watch them fail in CrashLoop

**Expected behavior**

Successful deployment with running containers.

**Additional context**

Pod Logs:
```
...
rabbitmq 2022-01-26 14:34:00.902 [info] <0.632.0> Server startup complete; 6 plugins started.                                                                                                                                                              rabbitmq  * rabbitmq_prometheus                                                                                                                                                                                                                            rabbitmq  * rabbitmq_peer_discovery_k8s                                                                                                                                                                                                                    rabbitmq  * rabbitmq_peer_discovery_common                                                                                                                                                                                                                 rabbitmq  * rabbitmq_management                                                                                                                                                                                                                            rabbitmq  * rabbitmq_web_dispatch                                                                                                                                                                                                                          rabbitmq  * rabbitmq_management_agent                                                                                                                                                                                                                      rabbitmq  completed with 6 plugins.                                                                                                                                                                                                                        rabbitmq 2022-01-26 14:34:00.903 [info] <0.632.0> Resetting node maintenance status                                                                                                                                                                        rabbitmq 2022-01-26 14:34:10.661 [info] <0.803.0> Closing all channels from connection '172.16.0.152:45008 -> 10.233.109.71:5672' because it has been closed
rabbitmq 2022-01-26 14:34:20.661 [info] <0.812.0> Closing all channels from connection '172.16.0.152:45502 -> 10.233.109.71:5672' because it has been closed
rabbitmq 2022-01-26 14:34:30.661 [info] <0.821.0> Closing all channels from connection '172.16.0.152:46014 -> 10.233.109.71:5672' because it has been closed
rabbitmq 2022-01-26 14:34:40.661 [info] <0.853.0> Closing all channels from connection '172.16.0.152:46532 -> 10.233.109.71:5672' because it has been closed
rabbitmq 2022-01-26 14:34:50.661 [info] <0.899.0> Closing all channels from connection '172.16.0.152:47040 -> 10.233.109.71:5672' because it has been closed
default-user-credential-updater standard_init_linux.go:228: exec user process caused: no such file or directory
```

**Comment by pitwegner** [comment]
The same Rabbitmq instance is starting correctly and not failing using the operator components from https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml.

**Comment by javsalgar** [comment]
Hi,

This seems to be like an issue with the PATH variable. Could you show the kubectl describe pod of the default-user-credential updater? This may give us some clue

**Comment by pitwegner** [comment]
Well, it is one pod with rabbitmq and credential updater containers:
```yaml
Name:         dev-rmq-server-0
Namespace:    dev
Priority:     0
Node:         wkr-k8s-zto-ngf-003.ngf.zorc/172.16.0.153
Start Time:   Wed, 09 Feb 2022 09:34:10 +0100
Labels:       app.kubernetes.io/component=rabbitmq
              app.kubernetes.io/name=dev-rmq
              app.kubernetes.io/part-of=rabbitmq
              controller-revision-hash=dev-rmq-server-5cbddf8bf6
              statefulset.kubernetes.io/pod-name=dev-rmq-server-0
Annotations:  cni.projectcalico.org/containerID: 23fc5f8675ef744d0f4da7abcc79f345969f8bb81f72c719ae5865e94f4a93f0
              cni.projectcalico.org/podIP: 10.233.92.53/32
              cni.projectcalico.org/podIPs: 10.233.92.53/32
              prometheus.io/port: 15692
              prometheus.io/scrape: true
              vault.hashicorp.com/agent-init-first: true
              vault.hashicorp.com/agent-inject: true
              vault.hashicorp.com/agent-inject-perms-11-default_user.conf: 0640
              vault.hashicorp.com/agent-inject-secret-11-default_user.conf: k8s/data/dev/rabbitmq
              vault.hashicorp.com/agent-inject-status: injected
              vault.hashicorp.com/agent-inject-template-11-default_user.conf:
                
                {{- with secret "k8s/data/dev/rabbitmq" -}}
                default_user = {{ .Data.data.username }}
                default_pass = {{ .Data.data.password }}
                {{- end }}
              vault.hashicorp.com/role: kubernetes
              vault.hashicorp.com/secret-volume-path-11-default_user.conf: /etc/rabbitmq/conf.d
              vault.hashicorp.com/template-static-secret-render-interval: 15s
Status:       Running
IP:           10.233.92.53
IPs:
  IP:           10.233.92.53
Controlled By:  StatefulSet/dev-rmq-server
Init Containers:
  vault-agent-init:
    Container ID:  containerd://10b62774b4348c4356938883d4093c90c5d129230f205dd6bdd583f87ceccb04
    Image:         hashicorp/vault:1.9.2
    Image ID:      docker.io/hashicorp/vault@sha256:ff9b17b0cefe86ebdc2e1efed9a626cc464145062d6bcbc56da34f2ef7be8d86
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -ec
    Args:
      echo ${VAULT_CONFIG?} | base64 -d > /home/vault/config.json && vault agent -config=/home/vault/config.json
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 09 Feb 2022 09:34:41 +0100
      Finished:     Wed, 09 Feb 2022 09:34:42 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  128Mi
    Requests:
      cpu:     250m
      memory:  64Mi
    Environment:
      VAULT_LOG_LEVEL:   info
      VAULT_LOG_FORMAT:  standard
      VAULT_CONFIG:      eyJhdXRvX2F1dGgiOnsibWV0aG9kIjp7InR5cGUiOiJrdWJlcm5ldGVzIiwibW91bnRfcGF0aCI6ImF1dGgva3ViZXJuZXRlcyIsImNvbmZpZyI6eyJyb2xlIjoia3ViZXJuZXRlcyIsInRva2VuX3BhdGgiOiIvdmFyL3J1bi9zZWNyZXRzL2t1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvdG9rZW4ifX0sInNpbmsiOlt7InR5cGUiOiJmaWxlIiwiY29uZmlnIjp7InBhdGgiOiIvaG9tZS92YXVsdC8udmF1bHQtdG9rZW4ifX1dfSwiZXhpdF9hZnRlcl9hdXRoIjp0cnVlLCJwaWRfZmlsZSI6Ii9ob21lL3ZhdWx0Ly5waWQiLCJ2YXVsdCI6eyJhZGRyZXNzIjoiaHR0cDovL3ZhdWx0LmluZnJhLW1pc2Muc3ZjOjgyMDAifSwidGVtcGxhdGUiOlt7ImRlc3RpbmF0aW9uIjoiL2V0Yy9yYWJiaXRtcS9jb25mLmQvMTEtZGVmYXVsdF91c2VyLmNvbmYiLCJjb250ZW50cyI6Ilxue3stIHdpdGggc2VjcmV0IFwiazhzL2RhdGEvZm91bmRyeWNsb3VkLWRldi9yYWJiaXRtcVwiIC19fVxuZGVmYXVsdF91c2VyID0ge3sgLkRhdGEuZGF0YS51c2VybmFtZSB9fVxuZGVmYXVsdF9wYXNzID0ge3sgLkRhdGEuZGF0YS5wYXNzd29yZCB9fVxue3stIGVuZCB9fSIsImxlZnRfZGVsaW1pdGVyIjoie3siLCJyaWdodF9kZWxpbWl0ZXIiOiJ9fSIsInBlcm1zIjoiMDY0MCJ9XSwidGVtcGxhdGVfY29uZmlnIjp7ImV4aXRfb25fcmV0cnlfZmFpbHVyZSI6dHJ1ZSwic3RhdGljX3NlY3JldF9yZW5kZXJfaW50ZXJ2YWwiOiIxNXMifX0=
    Mounts:
      /etc/rabbitmq/conf.d from vault-secrets-custom-0 (rw)
      /home/vault from home-init (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-q2lqg (ro)
      /vault/secrets from vault-secrets (rw)
  setup-container:
    Container ID:  containerd://7d3a6db768a9543dfe64e2914b602cba81b951eaa59f26f0ba8b0039b5679960
    Image:         docker.io/bitnami/rabbitmq:3.8.27-debian-10-r6
    Image ID:      docker.io/bitnami/rabbitmq@sha256:a474caf429362f9effd9863519662b311ad1a9357192c43986777e16aac5f44c
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      cp /tmp/erlang-cookie-secret/.erlang.cookie /var/lib/rabbitmq/.erlang.cookie && chmod 600 /var/lib/rabbitmq/.erlang.cookie ; cp /tmp/rabbitmq-plugins/enabled_plugins /operator/enabled_plugins ; echo '[default[]' > /var/lib/rabbitmq/.rabbitmqadmin.conf && sed -e 's/default_user/username/' -e 's/default_pass/password/' /etc/rabbitmq/conf.d/11-default_user.conf >> /var/lib/rabbitmq/.rabbitmqadmin.conf && chmod 600 /var/lib/rabbitmq/.rabbitmqadmin.conf
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 09 Feb 2022 09:34:59 +0100
      Finished:     Wed, 09 Feb 2022 09:35:00 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  500Mi
    Requests:
      cpu:        100m
      memory:     500Mi
    Environment:  <none>
    Mounts:
      /etc/rabbitmq/conf.d from vault-secrets-custom-0 (rw)
      /operator from rabbitmq-plugins (rw)
      /tmp/erlang-cookie-secret/ from erlang-cookie-secret (rw)
      /tmp/rabbitmq-plugins/ from plugins-conf (rw)
      /var/lib/rabbitmq/ from rabbitmq-erlang-cookie (rw)
      /var/lib/rabbitmq/mnesia/ from persistence (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-q2lqg (ro)
      /vault/secrets from vault-secrets (rw)
Containers:
  rabbitmq:
    Container ID:   containerd://1e404dce16b2a5aa9372b82920d1939f6bfa790e05e87527210d9b0b94577735
    Image:          docker.io/bitnami/rabbitmq:3.8.27-debian-10-r6
    Image ID:       docker.io/bitnami/rabbitmq@sha256:a474caf429362f9effd9863519662b311ad1a9357192c43986777e16aac5f44c
    Ports:          4369/TCP, 5672/TCP, 15672/TCP, 15692/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Wed, 09 Feb 2022 09:35:01 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  4Gi
    Requests:
      cpu:      1
      memory:   1Gi
    Readiness:  tcp-socket :amqp delay=10s timeout=5s period=10s #success=1 #failure=3
    Environment:
      MY_POD_NAME:                    dev-rmq-server-0 (v1:metadata.name)
      MY_POD_NAMESPACE:               dev (v1:metadata.namespace)
      K8S_SERVICE_NAME:               dev-rmq-nodes
      RABBITMQ_ENABLED_PLUGINS_FILE:  /operator/enabled_plugins
      RABBITMQ_USE_LONGNAME:          true
      RABBITMQ_NODENAME:              rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE)
      K8S_HOSTNAME_SUFFIX:            .$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE)
    Mounts:
      /etc/pod-info/ from pod-info (rw)
      /etc/rabbitmq/conf.d from vault-secrets-custom-0 (rw)
      /etc/rabbitmq/conf.d/10-operatorDefaults.conf from rabbitmq-confd (rw,path="operatorDefaults.conf")
      /etc/rabbitmq/conf.d/90-userDefinedConfiguration.conf from rabbitmq-confd (rw,path="userDefinedConfiguration.conf")
      /operator from rabbitmq-plugins (rw)
      /var/lib/rabbitmq/ from rabbitmq-erlang-cookie (rw)
      /var/lib/rabbitmq/mnesia/ from persistence (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-q2lqg (ro)
      /vault/secrets from vault-secrets (rw)
  default-user-credential-updater:
    Container ID:  containerd://173ca32e3e12eeff6b55a2b85105f7ebdca283921fd54ff26e78d271ef337cd5
    Image:         docker.io/bitnami/rmq-default-credential-updater:1.0.1-scratch-r1
    Image ID:      docker.io/bitnami/rmq-default-credential-updater@sha256:a8d91b275d41035da01f3c9bc8cf84b9a2e95f5c137bf5cc9f2e3ca9a6d3eb2b
    Port:          <none>
    Host Port:     <none>
    Args:
      --management-uri
      http://127.0.0.1:15672
      -v
      4
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 09 Feb 2022 09:35:20 +0100
      Finished:     Wed, 09 Feb 2022 09:35:20 +0100
    Ready:          False
    Restart Count:  2
    Limits:
      cpu:     500m
      memory:  128Mi
    Requests:
      cpu:     10m
      memory:  512Ki
    Environment:
      MY_POD_NAME:       dev-rmq-server-0 (v1:metadata.name)
      MY_POD_NAMESPACE:  dev (v1:metadata.namespace)
      K8S_SERVICE_NAME:  dev-rmq-nodes
      HOSTNAME_DOMAIN:   $(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE)
    Mounts:
      /etc/rabbitmq/conf.d from vault-secrets-custom-0 (rw)
      /var/lib/rabbitmq/ from rabbitmq-erlang-cookie (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-q2lqg (ro)
      /vault/secrets from vault-secrets (rw)
  vault-agent:
    Container ID:  containerd://da3335c8f46bd2620536b4c7b3e59c4f060dbc0b4279f7d3087a06fa5e358237
    Image:         hashicorp/vault:1.9.2
    Image ID:      docker.io/hashicorp/vault@sha256:ff9b17b0cefe86ebdc2e1efed9a626cc464145062d6bcbc56da34f2ef7be8d86
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -ec
    Args:
      echo ${VAULT_CONFIG?} | base64 -d > /home/vault/config.json && vault agent -config=/home/vault/config.json
    State:          Running
      Started:      Wed, 09 Feb 2022 09:35:06 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  128Mi
    Requests:
      cpu:     250m
      memory:  64Mi
    Environment:
      VAULT_LOG_LEVEL:   info
      VAULT_LOG_FORMAT:  standard
      VAULT_CONFIG:      eyJhdXRvX2F1dGgiOnsibWV0aG9kIjp7InR5cGUiOiJrdWJlcm5ldGVzIiwibW91bnRfcGF0aCI6ImF1dGgva3ViZXJuZXRlcyIsImNvbmZpZyI6eyJyb2xlIjoia3ViZXJuZXRlcyIsInRva2VuX3BhdGgiOiIvdmFyL3J1bi9zZWNyZXRzL2t1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvdG9rZW4ifX0sInNpbmsiOlt7InR5cGUiOiJmaWxlIiwiY29uZmlnIjp7InBhdGgiOiIvaG9tZS92YXVsdC8udmF1bHQtdG9rZW4ifX1dfSwiZXhpdF9hZnRlcl9hdXRoIjpmYWxzZSwicGlkX2ZpbGUiOiIvaG9tZS92YXVsdC8ucGlkIiwidmF1bHQiOnsiYWRkcmVzcyI6Imh0dHA6Ly92YXVsdC5pbmZyYS1taXNjLnN2Yzo4MjAwIn0sInRlbXBsYXRlIjpbeyJkZXN0aW5hdGlvbiI6Ii9ldGMvcmFiYml0bXEvY29uZi5kLzExLWRlZmF1bHRfdXNlci5jb25mIiwiY29udGVudHMiOiJcbnt7LSB3aXRoIHNlY3JldCBcIms4cy9kYXRhL2ZvdW5kcnljbG91ZC1kZXYvcmFiYml0bXFcIiAtfX1cbmRlZmF1bHRfdXNlciA9IHt7IC5EYXRhLmRhdGEudXNlcm5hbWUgfX1cbmRlZmF1bHRfcGFzcyA9IHt7IC5EYXRhLmRhdGEucGFzc3dvcmQgfX1cbnt7LSBlbmQgfX0iLCJsZWZ0X2RlbGltaXRlciI6Int7IiwicmlnaHRfZGVsaW1pdGVyIjoifX0iLCJwZXJtcyI6IjA2NDAifV0sInRlbXBsYXRlX2NvbmZpZyI6eyJleGl0X29uX3JldHJ5X2ZhaWx1cmUiOnRydWUsInN0YXRpY19zZWNyZXRfcmVuZGVyX2ludGVydmFsIjoiMTVzIn19
    Mounts:
      /etc/rabbitmq/conf.d from vault-secrets-custom-0 (rw)
      /home/vault from home-sidecar (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-q2lqg (ro)
      /vault/secrets from vault-secrets (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  persistence:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  persistence-dev-rmq-server-0
    ReadOnly:   false
  plugins-conf:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:     dev-rmq-plugins-conf
    Optional:  false
  rabbitmq-confd:
    Type:               Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:     dev-rmq-server-conf
    ConfigMapOptional:  <nil>
  rabbitmq-erlang-cookie:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  erlang-cookie-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  dev-rmq-erlang-cookie
    Optional:    false
  rabbitmq-plugins:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  pod-info:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels['skipPreStopChecks'] -> skipPreStopChecks
  kube-api-access-q2lqg:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
  home-init:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  home-sidecar:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  vault-secrets:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  vault-secrets-custom-0:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      Memory
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                From                     Message
  ----     ------                  ----               ----                     -------
  Warning  FailedScheduling        95s (x3 over 99s)  default-scheduler        0/6 nodes are available: 6 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled               90s                default-scheduler        Successfully assigned dev/dev-rmq-server-0 to wkr-k8s-zto-ngf-003.ngf.zorc
  Normal   SuccessfulAttachVolume  79s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-459b60ca-4b9a-4527-876c-487cfef8a558"
  Normal   Pulling                 73s                kubelet                  Pulling image "hashicorp/vault:1.9.2"
  Normal   Pulled                  60s                kubelet                  Successfully pulled image "hashicorp/vault:1.9.2" in 12.775693944s
  Normal   Created                 59s                kubelet                  Created container vault-agent-init
  Normal   Started                 59s                kubelet                  Started container vault-agent-init
  Normal   Pulling                 58s                kubelet                  Pulling image "docker.io/bitnami/rabbitmq:3.8.27-debian-10-r6"
  Normal   Pulled                  44s                kubelet                  Successfully pulled image "docker.io/bitnami/rabbitmq:3.8.27-debian-10-r6" in 13.520819032s
  Normal   Created                 41s                kubelet                  Created container setup-container
  Normal   Started                 41s                kubelet                  Started container setup-container
  Normal   Pulled                  40s                kubelet                  Container image "docker.io/bitnami/rabbitmq:3.8.27-debian-10-r6" already present on machine
  Normal   Pulling                 39s                kubelet                  Pulling image "docker.io/bitnami/rmq-default-credential-updater:1.0.1-scratch-r1"
  Normal   Started                 39s                kubelet                  Started container rabbitmq
  Normal   Created                 39s                kubelet                  Created container rabbitmq
  Normal   Pulled                  35s                kubelet                  Successfully pulled image "docker.io/bitnami/rmq-default-credential-updater:1.0.1-scratch-r1" in 4.138094922s
  Normal   Pulled                  35s                kubelet                  Container image "hashicorp/vault:1.9.2" already present on machine
  Normal   Created                 34s                kubelet                  Created container vault-agent
  Normal   Started                 34s                kubelet                  Started container vault-agent
  Normal   Created                 33s (x2 over 35s)  kubelet                  Created container default-user-credential-updater
  Normal   Started                 33s (x2 over 35s)  kubelet                  Started container default-user-credential-updater
  Warning  BackOff                 32s (x2 over 33s)  kubelet                  Back-off restarting failed container
  Normal   Pulled                  21s (x2 over 34s)  kubelet                  Container image "docker.io/bitnami/rmq-default-credential-updater:1.0.1-scratch-r1" already present on machine
  Warning  Unhealthy               21s                kubelet                  Readiness probe failed: dial tcp 10.233.92.53:5672: connect: connection refused
```
