### ISSUE TITLE
Is there any way to expose each redis cluster node on different port?

### ISSUE THREAD

**Issue by jaggerwang** [bitnami/charts#8812]
**Which chart**:

Redis Cluster

**Is your feature request related to a problem? Please describe.**

I want to access redis cluster service, which running in an AWS EKS cluster, from my local computer, but don't want to create a loadbalancer for each node, as each loadbalancer will consume an scarce  internet ip.

**Describe the solution you'd like**

So I want to expose each node through nginx ingress controller's tcp proxy service, and I need to allocate different proxy port for each node, but I cannot config port in `cluster.externalAccess.service.loadBalancerIP`, as it only accept ip.

**Describe alternatives you've considered**

I tried to use redis cluster proxy, but my spring boot application does not support redis cluster proxy, the error message is "cannot execute hello command". 

**Additional context**

**Comment by alemorcuq** [comment]
Hi, @jaggerwang. 

I'm afraid there's no way to specify a different port for each node at the moment. Perhaps you could try to use a `NodePort` service instead of a `LoadBalancer` so that each node is exposed through a Node Port?

**Comment by jaggerwang** [comment]
> Hi, @jaggerwang.
> 
> I'm afraid there's no way to specify a different port for each node at the moment. Perhaps you could try to use a `NodePort` service instead of a `LoadBalancer` so that each node is exposed through a Node Port?

The result is the same, I still need to expose every node's port through load balancers.

**Comment by alemorcuq** [comment]
I'm going to leave this open in case someone wants to contribute to this.

**Comment by easayliu** [comment]
with this config
```yaml
  externalAccess:
    enabled: true
    service:
      ## Type of service for external access. At this moment only LoadBalancer is supported.
      ##
      type: ClusterIP
      ## Port used when service type is LoadBalancer
      ##
      port: 6379
      ## Array of load balancer IPs for each Redis(TM) node. Length must be the same as cluster.nodes
      ##
      loadBalancerIP: 
      # - 123.1231
      # - 123.32132.1231
      ## Service annotations done as key:value pairs
      ##
      annotations: {}
```
