### ISSUE TITLE
[external-dns] value `aws.preferCNAME` is not respected when rendering chart

### ISSUE THREAD

**Issue by timfallmk** [bitnami/charts#8832]
**Which chart**:

external-dns

**Describe the bug**

When using AWS GovCloud, where no `ALIAS` records are allowed, we attempt to set the `--aws-prefer-cname=true` flag so that external-dns creates CNAME records instead. We use the [associated value](https://github.com/bitnami/charts/blob/9c934eeb842b0c8a53a5cde1e349c8a3482301c2/bitnami/external-dns/templates/deployment.yaml#L185-L186) and set it to `true`. This value is not parsed into the deployment, and no error is seen.

**To Reproduce**

1. Create values file for `external-dns`
2. Add `aws.preferCNAME: true` to the file
3. Install chart
4. View deployment to verify flag missing

**Expected behavior**

We would expect this flag (without any values) to be set in the deployment manifest.

**Additional context**
I've also verified that this does not work when using the cli `--set` command to set the associated value. The only thing that works is passing a string to `extraArgs` that contains this flag (.i.e. `--set extraArgs='{--aws-prefer-cname}'`)

When using the normal value set process:

`helm install external-dns external-dns/external-dns -f values.external-dns.yaml --dry-run --debug --set aws.preferCNAME=true`

```yaml
spec:
      serviceAccountName: external-dns-route-53-access
      securityContext:
        fsGroup: 65534
      containers:
        - name: external-dns
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
          image: k8s.gcr.io/external-dns/external-dns:v0.10.2
          imagePullPolicy: IfNotPresent
          args:
            - --log-level=info
            - --log-format=text
            - --interval=1m
            - --source=service
            - --source=ingress
            - --policy=upsert-only
            - --registry=txt
            - --txt-owner-id=<snip>
            - --txt-prefix=<snip>
            - --provider=aws
```

When passing a parsed string via `--set`

`helm install external-dns external-dns/external-dns -f values.external-dns.yaml --dry-run --debug --set extraArgs={'--aws-prefer-cname'}`

```yaml
spec:
      serviceAccountName: external-dns-route-53-access
      securityContext:
        fsGroup: 65534
      containers:
        - name: external-dns
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
          image: k8s.gcr.io/external-dns/external-dns:v0.10.2
          imagePullPolicy: IfNotPresent
          args:
            - --log-level=info
            - --log-format=text
            - --interval=1m
            - --source=service
            - --source=ingress
            - --policy=upsert-only
            - --registry=txt
            - --txt-owner-id=<snip.
            - --txt-prefix=<snip>
            - --provider=aws
            - --aws-prefer-cname

```

**Comment by migruiz4** [comment]
Hi @timfallmk,

Could you please check that you are using the latest version of the `bitnami/external-dns` Helm chart?

In your `helm install`, I see you are using `external-dns/external-dns`, and the output looks different to what I get using the version 6.1.3 of the `bitnami/external-dns` chart:

```console
helm install external-dns bitnami/external-dns --dry-run --debug --set aws.preferCNAME=true
```

```yaml
    spec:
      
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: external-dns
                    app.kubernetes.io/instance: external-dns
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: "docker.io/bitnami/external-dns:0.10.2-debian-10-r27"
          imagePullPolicy: "IfNotPresent"
          args:
            # Generic arguments
            - --metrics-address=:7979
            - --log-level=info
            - --log-format=text
            - --policy=upsert-only
            - --provider=aws
            - --registry=txt
            - --interval=1m
            - --source=service
            - --source=ingress
            # AWS arguments
            - --aws-api-retries=3
            - --aws-zone-type=
            - --aws-batch-change-size=1000
            - --aws-prefer-cname
          env:
            # AWS environment variables
            - name: AWS_DEFAULT_REGION
              value: us-east-1
```
