### ISSUE TITLE
when externalaccess.service.type = clusterIP Readiness probe failed

### ISSUE THREAD

**Issue by floresfactor** [bitnami/charts#8848]
**Which chart**: bitnami/mongodb version 11.0.1

I want to expose in my AWS VPC each of the mongodb replicas, we use external dns tool in a private zone of route53 and everything is fine so far I can access it from my private VPC, these are my values
```yaml
architecture: replicaset
service:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mongo.mydns.com
    external-dns.alpha.kubernetes.io/ttl: "30"  
externalAccess: 
  enabled: true
  service:  
    type: ClusterIP
replicaCount: 3
podAntiAffinityPreset: soft
```
only that to test I wanted to restart a primary pod of the replica to see how it recovered and it never returns to being healthy it appears in the Readiness probe failed events and this only happens when I put `externalaccess.service.type=ClusterIP`

Is there something I have to do additional so that this does not happen?

**To Reproduce**
```
helm install mongo-cluster -n mongo bitnami/mongodb -f values-above.yaml
```
