### ISSUE TITLE
Seeing issue with ghost helm installation external database

### ISSUE THREAD

**Issue by pandeybk** [bitnami/charts#8852]
**Which chart**:

ghost chart 
version: 16.0.4

**Describe the bug**

I am using an external database. Looks like tables are created in database but failed with the following error log and pods are going into CrashLoopBackOff.

```
ghost 23:13:38.46 
ghost 23:13:38.47 Welcome to the Bitnami ghost container
ghost 23:13:38.47 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-ghost
ghost 23:13:38.47 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-ghost/issues
ghost 23:13:38.47 
ghost 23:13:38.47 INFO  ==> Configuring libnss_wrapper
ghost 23:13:38.50 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
ghost 23:13:38.56 DEBUG ==> Validating settings in GHOST_* environment variables...
ghost 23:13:38.57 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
ghost 23:13:38.57 INFO  ==> Ensuring Ghost directories exist
ghost 23:13:38.58 INFO  ==> Trying to connect to the database server
ghost 23:13:38.59 DEBUG ==> Executing SQL command:
SELECT 1
1
ghost 23:13:38.60 INFO  ==> Configuring database
ghost 23:13:38.61 INFO  ==> Setting up Ghost
- Inspecting operating system
- Checking for deprecations
[23:13:39] Checking for Ghost-CLI updates [started]
[23:13:39] Checking for Ghost-CLI updates [completed]
[23:13:39] Configuring Ghost [started]
[23:13:39] Configuring Ghost [completed]
[23:13:39] Setting up instance [started]
[23:13:39] Setting up instance [completed]

Ghost uses direct mail by default. To set up an alternative email method read our docs at https://ghost.org/docs/config/#mail

------------------------------------------------------------------------------

Ghost was installed successfully! To complete setup of your publication, visit: 

    http://stage.somedomain.com/blog/ghost/

ghost 23:13:40.00 INFO  ==> Configuring Ghost URL to http://stage.somedomain.com/blog
ghost 23:13:40.01 INFO  ==> Passing admin user creation wizard
ghost 23:13:40.02 INFO  ==> Starting Ghost in background
ghost 23:13:45.36 DEBUG ==> Checking that /opt/bitnami/ghost/content/logs/ghost.log log file contains entry "Your admin interface is located at"
ghost 23:13:45.36 DEBUG ==> Found entry "Your admin interface is located at" in /opt/bitnami/ghost/content/logs/ghost.log
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /ghost/api/v3/admin/authentication/setup/</pre>
</body>
</html>
ghost 23:13:50.40 ERROR ==> An error occurred while installing Ghost
```
**To Reproduce**

deploy chart with following values,

```yaml
        image:
          debug: true
        ghostHost: "https://stage.somedomain.com/"
        ghostPath: "/blog"
        mariadb:
          enabled: false
        externalDatabase:
          host: database.platform
          port: 6446
          database: stage_blog
          user: someuser
          existingSecret: ghost-database
        ingress:
          enabled: true
          hostname: "stage.somedomain.com"
          path: "/blog"
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            cert-manager.io/cluster-issuer: "letsencrypt-production"
            cert-manager.io/issue-temporary-certificate: "true"
          tls: true
        persistence:
          size: 8Gi
          storageClass: "local-path"
```
