### ISSUE TITLE
spark.executor.instances or --num-executors is not working 

### ISSUE THREAD

**Issue by sudhevan** [bitnami/charts#8867]
Hi,

I'm not able to control the no of executors. depending on the cores/memory setting no of executors are auto calculated based on the total resources available 

Ex: 

- No of spark-workers - 2
- coreLimit for each worker - 8 cores
- Total 16 cores available 

if i set --executor-cores=2 then i am getting 8 executors automatically
if i set --executor-cores=1 then i am getting 16 executors automatically

basically for a single spark-submit its trying to use all the resource available

`--num-executors` or `--conf spark.executor.instances` are NOT doing anything

- deploymode is client
- cannot use deploymode as cluster because its a python app
- spark-ver: 2.4.5

```bash
/opt/bitnami/spark/bin/spark-submit \
  --executor-memory 1G \
  --executor-cores 2  \
  --num-executors 2 \
  --conf spark.executor.instances=2 \
  /sparkapp/count.py
```

**Comment by juan131** [comment]
Hi @sudhevan 

Could you please share the **values.yaml** you're using to deploy the Spark chart? Specially interested if you modified `*.resource.[limits|requests]` or `worker.[daemonMemoryLimit|memoryLimit|coreLimit]` parameters.

**Comment by sudhevan** [comment]
Hi @juan131 
Yes, i do have limits set in helm
here is the preview and complete chart

```
worker:
  resources:
    limits:
      memory: 1Gi
  nodePorts:
    web: 32060
    #^web port refers to the spark app detail UI (eg: 32044)
  replicaCount: 2
  coreLimit: 8
  memoryLimit: 8G

```


```
#Spark for analytics
image:
  pullPolicy: Always
  registry: myregistry
  repository: spark-app
  tag: 2.4.5

# If ingresses are set simply comment out the below "type:NodePort" line; no need to comment out any of the port specifications
service:
  #type: NodePort
  nodePorts:
    cluster: 32412
    #^cluster port refers to the spark master service port to listen on (eg: 31493).
    #Set this to connect to spark from outside kubernetes cluster (additional security needed in this case)
    web: 32057
    #^web port refers to the spark app detail UI for the master (eg: 32043)

environment:
  PG_URL: "jdbc:postgresql://postgresql.postgresql:5432/metastore"
  S3_PROJ_BUCKET: "mybucket"
  S3_URL: http://minio.minio:9000

driver:
  resources:
    limits:
      memory: 1Gi
  nodePorts:
    web: 32015
    #^web port refers to the spark app detail UI (eg: 32002)

history:
  resources:
    limits:
      memory: 1Gi
  nodePorts:
    web: 32058
    #^web port refers to the spark app detail UI (eg: 32045)

thrift:
  resources:
    limits:
      memory: 1Gi
  nodePorts:
    web: 32013
    #^web port refers to the spark app detail UI (eg: 32001)
    cluster: 32059
    #^cluster port refers to the JDBC port for thriftserver (eg: 32046)

master:
  resources:
    limits:
      memory: 1Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/component"
                operator: In
                values:
                  - master
                  - worker
          topologyKey: "kubernetes.io/hostname"

worker:
  resources:
    limits:
      memory: 1Gi
  nodePorts:
    web: 32060
    #^web port refers to the spark app detail UI (eg: 32044)
  replicaCount: 2
  coreLimit: 8
  memoryLimit: 8G
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/component"
                operator: In
                values:
                  - worker
                  - master
          topologyKey: "kubernetes.io/hostname"

extraEnvVars:
  - name: PG_PWD
    valueFrom:
      secretKeyRef:
        name: postgresql-secret
        key: postgresql-password
  - name: S3_USR
    valueFrom:
      secretKeyRef:
        name: minio-secret
        key: accesskey
  - name: S3_PWD
    valueFrom:
      secretKeyRef:
        name: minio-secret
        key: secretkey

```
