### ISSUE TITLE
[bitnami/keycloak] - Too many redirects

### ISSUE THREAD

**Issue by Phoelsch** [bitnami/charts#8869]
**Which chart**:
 name: keycloak
 version: 6.1.1

**Describe the bug**
After upgrading from chart version 5.0.0 to 6.1.1 I'am not able to login into admin console. After passing the credentials Chrome tries to redirect but ends up with "Too many redirects". 

Log from the pod:
```
07:01:09,523 WARN  [org.keycloak.events] (default task-2) type=LOGIN_ERROR, realmId=master, clientId=null, userId=null, ipAddress=85.8.80.53, error=expired_code, restart_after_timeout=true, authSessionParentId=22b6a629-d1d3-4c74-97b6-75cdc104de84, authSessionTabId=hlTwuaHf2BM
```

**To Reproduce**

I'm running Keycloak with 3 replicas behind a NGNIX reverse proxy.

My config:
```
keycloak:
  enabled: true
  replicaCount: 3

  auth:
    tls:
      enabled: true
      autoGenerated: false
      type: jks
      existingSecret: dev-keycloak-certs
      keystorePassword: "empty"
      truststorePassword: "empty"
    adminUser: admin
    adminPassword: empty
    interBrokerProtocol: tls

  proxyAddressForwarding: true

  serviceDiscovery:
    enabled: true

  cache:
    ownersCount: 3
    authOwnersCount: 3

  rbac:
    create: true

  ingress:
    enabled: true
    tls: true
    servicePort: https
    hostname: not_important.io
    path: /auth/
    annotations:
      kubernetes.io/ingress.allow-http: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/affinity: "cookie"

  metrics:
    enabled: true

  readinessProbe:
    initialDelaySeconds: 60

  service:
    type: NodePort
    nodePorts:
      https: "32443"

  postgresql:
    enabled: true
    postgresqlUsername: example
    postgresqlPassword: example
    postgresqlDatabase: keycloak
    persistence:
      enabled: true
      size: 5Gi

  initdbScripts:
    my_init_script.sh: |
      debug_execute jboss-cli.sh <<EOF
      embed-server --server-config=${KEYCLOAK_CONF_FILE} --std-out=discard
      batch
      /subsystem=keycloak-server/spi=eventsListener:add
      /subsystem=keycloak-server/spi=eventsListener/provider=jboss-logging:add(enabled=true)
      /subsystem=keycloak-server/spi=eventsListener/provider=jboss-logging:write-attribute(name=properties.success-level,value=info)
      /subsystem=keycloak-server/spi=eventsListener/provider=jboss-logging:write-attribute(name=properties.error-level,value=warn)
      run-batch
      stop-embedded-server
      EOF

  extraVolumes: |
    - name: realm-secret
      secret:
        secretName: dev-realm-secret

  extraVolumeMounts: |
    - name: realm-secret
      mountPath: "/realm/"
      readOnly: true

  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "-Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.profile.feature.token_exchange=enabled -Dkeycloak.profile.feature.declarative_user_profile=enabled -Dkeycloak.import=/realm/example-realm.json"
```

**Expected behavior**

Login is successful and redirect to admin console.

**Additional context**

**Comment by juan131** [comment]
@Phoelsch 

Could you please check these other issues that report similar problems? Thanks in advance

- https://github.com/bitnami/charts/issues/8734
- https://github.com/bitnami/charts/issues/6940

**Comment by Phoelsch** [comment]
@juan131 

Thank for you're fast help. 

I checked both issues and tested the proposed solutions but non of them fixed the problem.

I also tested a setup where the NGINX sends plain Http requests to Keycloak with the same result as before.

Could it be that [Proxy environment variables](https://www.keycloak.org/2021/12/keycloak-1600-released) causes such problems? I found some similar hints but I'am not sure right now how this exactly could influence my deployment.

**Comment by miguelaeh** [comment]
Hi @Phoelsch ,
Could you share the rendered Ingress object, please?
Also, I remember here `path: /auth/` sometimes the last `/` can give issues. Give a try to remove it

**Comment by Phoelsch** [comment]
@miguelaeh 

I removed the trailing `/`.

Here is the Ingress object:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-keycloak
  namespace: kss-dev
  uid: 96c6ecaa-ad1d-493f-a3ae-f18005e9f626
  resourceVersion: '81874539'
  generation: 3
  creationTimestamp: '2022-02-01T13:00:49Z'
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-6.1.1
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["10.43.249.207"],"port":80,"protocol":"HTTP","serviceName":"kss-dev:dev-keycloak","ingressName":"kss-dev:dev-keycloak","hostname":"example-domain.io","path":"/auth/","allNodes":true}]
    kubernetes.io/ingress.allow-http: 'false'
    meta.helm.sh/release-name: dev
    meta.helm.sh/release-namespace: kss-dev
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-pass-headers: Authorization
  managedFields:
    - manager: rancher
      operation: Update
      apiVersion: extensions/v1beta1
      time: '2022-02-01T13:01:15Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:field.cattle.io/publicEndpoints': {}
    - manager: helm
      operation: Update
      apiVersion: networking.k8s.io/v1
      time: '2022-02-02T07:43:30Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubernetes.io/ingress.allow-http': {}
            'f:meta.helm.sh/release-name': {}
            'f:meta.helm.sh/release-namespace': {}
            'f:nginx.ingress.kubernetes.io/backend-protocol': {}
            'f:nginx.ingress.kubernetes.io/proxy-pass-headers': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/name': {}
            'f:helm.sh/chart': {}
        'f:spec':
          'f:rules': {}
    - manager: nginx-ingress-controller
      operation: Update
      apiVersion: networking.k8s.io/v1beta1
      time: '2022-02-02T15:32:27Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:loadBalancer':
            'f:ingress': {}
  selfLink: /apis/networking.k8s.io/v1/namespaces/kss-dev/ingresses/dev-keycloak
status:
  loadBalancer:
    ingress:
      - ip: 10.43.249.207
spec:
  rules:
    - host: example-domainx.io
      http:
        paths:
          - path: /auth/
            pathType: ImplementationSpecific
            backend:
              service:
                name: dev-keycloak
                port:
                  name: https

```

**Comment by miguelaeh** [comment]
mmmm looks correct except that I would try without the final `/` at the auth.

Can you share how are the redirections done? I mean, the source and destination of the redirections. You can see that information checking the network tab in the browser when reloading your page

**Comment by hjones2199** [comment]
Still not fixed

**Comment by benoitm76** [comment]
Check this:
```
serviceAccount:
  automountServiceAccountToken: true
```

Must be set to true to allow access to Kubernetes API from Keycloak when HA enabled.

**Comment by PePTojr** [comment]
Hi  my ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress-ssl
  namespace: default
  annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$1
#     nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
#     kubernetes.io/tls-acme: "true"
#     kubernetes.io/ingress.class: "nginx"
#     ingress.kubernetes.io/force-ssl-redirect: "true"
#     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
   - host: keycloak-test.kassanova.lcl
     http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 80
  tls:
  - hosts:
    - keycloak-test.kassanova.lcl
    secretName: key-cloak-tls-secret

After Im uncomment TLS  section   too  many redirects  if comment TLS  after  enter on Admin page I recived  empty  page
PROXY  forward true
 it is my deploy

   rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak
        envFrom:
            - configMapRef:
                name: keycloak-config
        env:
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin123
            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: DB_PASSWORD
            - name: JGROUPS_DISCOVERY_PROTOCOL
              value: kubernetes.KUBE_PING
            - name: JGROUPS_DISCOVERY_PROPERTIES
              value: dump_requests=true,port_range=0,namespace=default
              value: port_range=0,dump_requests=true
            - name: JGROUPS_DISCOVERY_PROTOCOL
              value: dns.DNS_PING
            - name: JGROUPS_DISCOVERY_PROPERTIES
              value: "dns_query=keycloak"
            - name: CACHE_OWNERS_COUNT
              value: '2'
            - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
              value: '2'
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
        ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
If   I use HTTP only all works  fine!

**Comment by javsalgar** [comment]
Hi @PePTojr could you share a values.yaml that triggers the issue? I would like to exactly reproduce the issue on my side.

**Comment by PePTojr** [comment]
> Hi @PePTojr could you share a values.yaml that triggers the issue? I would like to exactly reproduce the issue on my side.

sorry my English,   values.yaml ,  where I can get,   Im noob))  

extraEnv: |
  - name: KEYCLOAK_USER
    value: admin
  - name: KEYCLOAK_PASSWORD
    value: admin123
  - name: DB_ADDR
    value: "172.17.56.56"
  - name: DB_PORT
    value: "5432"
  - name: DB_DATABASE
    value: "keycloak"
  - name: DB_USER
    value: "keycloak"
  - name: DB_VENDOR
    value: "POSTGRES"
  - name: DB_SCHEMA
    value: "public"
  - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KEYCLOAK_FRONTEND_URL
    value: "https://keycloak-test.kassanova.lcl"
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: DB_PASSWORD
  - name: JGROUPS_DISCOVERY_PROTOCOL
    value: kubernetes.KUBE_PING
  - name: JGROUPS_DISCOVERY_PROPERTIES
    value: dump_requests=true,port_range=0,namespace=default
    value: port_range=0,dump_requests=true
  - name: CACHE_OWNERS_COUNT
    value: '2'
  - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
    value: '2'
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: DEPLOYPOSTGRES
    value: "false"

It s all what i  have but if   I use  KEYCLOAK_FRONTEND_URL    ---   recive  503 bad gateway

my schema   Nginx
 HTTPS(nginx)--> HTTP(ingress) --- > empty page((   now  empty page  with  stuck on keycloak.js
 if Im  use
If HTTP(nginx)----> HTTP(ingress) --- >> ALL FINE

sorry  I'm still not very good at all of this

**Comment by javsalgar** [comment]
Do the container logs show anything meaningful?

**Comment by PePTojr** [comment]
if Im use L4  loadbalance all ok, without Nginx,  Im  use IP node and port over 30000+
if  use Nginx before  cluster   stuck on  keycloak.js  without any log on container keyloak
in  log  Nginx ingress :
[11/Apr/2022:11:50:41 +0000] "GET /auth/resources/x3jze/common/keycloak/node_modules/angular-route/angular-route.min.js.map HTTP/1.0" 200 5916 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36" "-"
all fine  200 code

**Comment by javsalgar** [comment]
Do the chrome web inspector logs and the network inspector show anything that we can use to understand what the requested url is?

**Comment by PePTojr** [comment]
now   I have  this error after enter  login/password   
Your login attempt timed out. Login will start from the beginning.

**Comment by javsalgar** [comment]
Could you please share with us a values.yaml file and instructions to exactly reproduce the issue? If I need to change anything in my /etc/hosts file please let us know as well. I

**Comment by PePTojr** [comment]
> Could you please share with us a values.yaml file and instructions to exactly reproduce the issue? If I need to change anything in my /etc/hosts file please let us know as well.

I think I found the reason, everything works, the code deploys one pod, if I increase replicationset > 1 I get a redirect, the cluster from pod's is not collected if I use

JGROUPS_DISCOVERY_PROTOCOL = TCPPING
tried JDBC_PING ,
everything works as it should, I apologize for wasting time with my stupid questions

**Comment by javsalgar** [comment]
Hi,

Thank you so much for sharing the solution! I'm sure it will help other people in the community that come across the same issue :D

**Comment by serhiiromaniuk** [comment]
Hi folks!
Only with this config I was able to run clustered Keycloak's chart:

```yaml
serviceDiscovery:
  enabled: true
  protocol: JDBC_PING
  properties:
    - "datasource_jndi_name=java:jboss/datasources/KeycloakDS"
    - 'initialize_sql=>"CREATE TABLE IF NOT EXISTS JGROUPSPING ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created timestamp default current_timestamp, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))"'

cache:
  ownersCount: 3
  authOwnersCount: 3

replicaCount: 3
proxyAddressForwarding: true

extraEnvVars:
  - name: KEYCLOAK_FRONTEND_URL
    value: "https://< OUR HOSTNAME >/auth"
  - name: KUBERNETES_NAMESPACE
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.namespace

ingress:
  enabled: true
  # and other ingress conf

# and other related conf
```

When just add `serviceDiscovery.{protocol,properties}` I was able to avoid "too many redirects" error message behind balancer.

## Platform and specs:
- Chart version: `7.1.18`
- Platform: EKS `1.22` (latest for now)
- Balancer: Kubernetes Nginx Ingress Controller chart `4.1.0` + cert-manager `1.8.0`

**Comment by PePTojr** [comment]
Hi,  bro!
yes  me too))
only JDBC_PING
and I m use ext. DB Postgresq, before deploy script Im did
CREATE TABLE IF NOT EXISTS JGROUPSPING (own_addr varchar(200) NOT NULL,
cluster_name varchar(200) NOT NULL, ping_data BYTEA, constraint
PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name));

and then deploy

TY



ср, 11 мая 2022 г. в 23:01, Serhii Romaniuk ***@***.***>:

**Comment by serhiiromaniuk** [comment]
> Hi folks! Only with this config I was able to run clustered Keycloak's chart:
> 
> ```yaml
> serviceDiscovery:
>   enabled: true
>   protocol: JDBC_PING
>   properties:
>     - "datasource_jndi_name=java:jboss/datasources/KeycloakDS"
>     - 'initialize_sql=>"CREATE TABLE IF NOT EXISTS JGROUPSPING ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created timestamp default current_timestamp, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))"'
> 
> cache:
>   ownersCount: 3
>   authOwnersCount: 3
> 
> replicaCount: 3
> proxyAddressForwarding: true
> 
> extraEnvVars:
>   - name: KEYCLOAK_FRONTEND_URL
>     value: "https://< OUR HOSTNAME >/auth"
>   - name: KUBERNETES_NAMESPACE
>     valueFrom:
>       fieldRef:
>         apiVersion: v1
>         fieldPath: metadata.namespace
> 
> ingress:
>   enabled: true
>   # and other ingress conf
> 
> # and other related conf
> ```
> 
> When just add `serviceDiscovery.{protocol,properties}` I was able to avoid "too many redirects" error message behind balancer.
> 
> ## Platform and specs:
> * Chart version: `7.1.18`
> * Platform: EKS `1.22` (latest for now)
> * Balancer: Kubernetes Nginx Ingress Controller chart `4.1.0` + cert-manager `1.8.0`
> 
> [EDIT] PS: Also `initialize_sql=>` might not work, according to [this](https://github.com/keycloak/keycloak-containers/blob/main/server/README.md#clustering) documentation. But whatever sweat_smile


Broken, when get updated to `8.0.2` chart

**Comment by PePTojr** [comment]
TY,  Friend

вт, 17 мая 2022 г. в 14:12, Serhii Romaniuk ***@***.***>:

**Comment by amine7777** [comment]
I had the same issue and I solved it by enabling the cache

`    logging:
      output: default
      level: INFO
    cache:
      enabled: true`

**Comment by paltaa** [comment]
This config worked for me in `10.1.6`

```
cache:
  enabled: true
  ownersCount: 3
  authOwnersCount: 3

replicaCount: 3
proxyAddressForwarding: true
serviceDiscovery:
  enabled: true
  protocol: JDBC_PING
  properties:
    - "datasource_jndi_name=java:jboss/datasources/KeycloakDS"
    - 'initialize_sql=>"CREATE TABLE IF NOT EXISTS JGROUPSPING ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created timestamp default current_timestamp, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))"'
```
