### ISSUE TITLE
[bitnami/minio] minio mc: <ERROR> Invalid command usage, flag provided but not defined: -ignore-existing

### ISSUE THREAD

**Issue by Timvissers** [bitnami/charts#8873]
**Which chart**:

bitnami/minio

**Describe the bug**

Minio contains functionality to create buckets, they call it 'provisioning' in the charts.
When trying to provision, it fails on `minio mc: <ERROR> Invalid command usage, flag provided but not defined: -ignore-existing`

**To Reproduce**
Apply the chart with values
```
        provisioning:
          enabled: true
          buckets:
            - name: bucket1
              policy: none
            - name: bucket2
              policy: none
```

**Expected behavior**

The bucket should be created. 
The container that is responsible to create the bucket, should not go in error.
