### ISSUE TITLE
Kafka external access does not work with TLS enabled

### ISSUE THREAD

**Issue by mpmatti** [bitnami/charts#8875]
**Which chart**:

kafka-14.1.0

**Describe the bug**

We have configured external access to kafka (type loadBalancer) with client protocol SASL_TLS enabled. Access from clients does not work, it gives the following error:

```
ERROR [Consumer clientId=consumer-console-consumer-68764-1, groupId=console-consumer-68764] Connection to node 2147483647 (x.x.x.x/x.x.x.x:9094) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient)
ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$)
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative names matching IP address x.x.x.x found

```

**To Reproduce**

1. generate TLS cert for kafka server with three hostnames in SAN (DNS records already exist)
Add the key, cert and CA cert in a kubernetes secret object 'kafka-pem'. 

2. install kafka with the following values.yaml:

```yaml
kafka:
  replicaCount: 3 
  persistence: 
    enabled: true
  readinessProbe:
    initialDelaySeconds: 60
  livenessProbe:
    initialDelaySeconds: 60     
  externalAccess:
    enabled: true
    service:
      type: LoadBalancer
      port: 9094
      loadBalancerIPs: 
        - x.x.x.x
        - y.y.y.y
        - z.z.z.z
    
  auth:
    clientProtocol: sasl_tls
    interBrokerProtocol: plaintext

    tls:    
      type: pem
      existingSecret: kafka-pem
      
    sasl:
      jaas:
        existingSecret: kafka-secrets    
        interBrokerUser: brokeruser
        zookeeperUser: zookeeperuser
        clientUsers:
          - kafka-user

  allowPlaintextListener: true
  deleteTopicEnable: true
  autoCreateTopicsEnable: true 

  zookeeper:
    allowAnonymousLogin: false
    replicaCount: 3
    auth:
     enabled: true
     existingSecret: kafka-zookeeper-secrets
     clientUser: zookeeperuser
     serverUsers: zookeeperuser

```

3. set up a client using trusting the same CA cert

4. run kafka shell commands in client, e.g.
`kafka-console-producer.sh --producer.config /config/client-secret --bootstrap-server kafka-0.mydomain.com:9094 --topic test`

**Expected behavior**

The clients should be able to connect to the server, create topics, etc.

**Further investigations**

kafka server.properties file contains only the IP address of the kafka node in advertised listeners:
```
I have no name!@kafka-0:/$ cat /opt/bitnami/kafka/config/server.properties |grep -i advertised
advertised.listeners=INTERNAL://kafka-0.kafka-headless.kafka.svc.cluster.local:9093,CLIENT://kafka-0.kafka-headless.kafka.svc.cluster.local:9092,EXTERNAL://x.x.x.x:9094

```
Which causes the problem, as it advertises only the IP address to the client, and that does not match the SAN hostnames in the server certificate. It seems the chart does not have any configuration option to provide kafka with the correct hostnames used for external listener.

We also tested by adding the external host IPs to the certificate SAN list, and it worked fine. However, defining IP addresses in SAN is really not optimal, as in the end we'd like to use a wildcard certificate. Is there any way - using the chart parameters - to do this properly. Can we make kafka to advertise hostnames instead of IP addresses?
