### ISSUE TITLE
[bitnami/mariadb] Connection refused (HY000/2002) after upgrade v9.8.1 to v10.3.2

### ISSUE THREAD

**Issue by viceice** [bitnami/charts#8882]
**Which chart**: bitnami/mariadb 10.3.2

**Describe the bug**

After upgrade the chart and successful start of the pods, the container isn't accessible via network. 
Maybe the IPv6 change can be the issue ? I've a IPv4 only k3s cluster, but some nodes have a native IPv6.
I'll try to validate the broken commit later.

- ref #8393 

**To Reproduce**

1. deploy a v9.8.1 instance
2. upgrade to v10.3.2
3. try to connect via network

**Expected behavior**

The upgrade should work

**Additional context**

My *values.yaml*
```yml
image:
  registry: gcr.io
  repository: bitnami-containers/mariadb
  # do not upgrade major or minor until nextcloud is ready
  tag: 10.6.5-debian-10-r80

auth:
  forcePassword: true
  database: ''
  usePasswordFiles: true
  existingSecret: mariadb

primary:
  #  service:
  # type: LoadBalancer
  startupProbe:
    enabled: true
  livenessProbe:
    initialDelaySeconds: 0
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 1
  tolerations:
    - key: kriese.eu/hosted
      operator: Exists
      effect: NoSchedule
  nodeSelector:
    topology.kubernetes.io/region: xxx

  persistence:
    existingClaim: nc-db-data

  # required for nextcloud
  # https://help.nextcloud.com/t/update-to-22-failed-with-database-error-updated/120682/20
  extraFlags: '--transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed'
```
