### ISSUE TITLE
[bitnami/postgresql] postgres user password can not be set with helm values

### ISSUE THREAD

**Issue by PhilipMay** [bitnami/charts#8899]
### Name and Version

- bitnami/postgresql
- appVersion: 14.1.0
- version: 11.0.1

### What steps will reproduce the bug?

**PS: Yes. I am 100% sure that a new PV / PVC is created when I deploy this helm chart. It is NOT using an old PV.**

Create this very simple values.yaml file:

```yaml
persistence:
  storageClass: longhorn-crypto-global
  size: 200Mi

global:
  postgresql:
    auth:
      postgresPassword: "123456789"
```

Then deploy the helm chart: `helm upgrade --install postgresql-ssl bitnami/postgresql -n postgresql-ssl --create-namespace -f postgresql-ssl-helm-values.yaml`

Now I should be able to log in as postgres user with password "123456789". But that fails!

I have to do this to get the password: `kubectl get secret --namespace postgresql-ssl postgresql-ssl -o jsonpath="{.data.postgresql-password}" | base64 --decode`

That password looks like this: `hlJkEnbdeA`. With that password it works.

But the password should be `123456789` - as I did set it.

### Are you using any custom parameters or values?

yes - see above

### What is the expected behavior?

see above

### What do you see instead?

see above

### Additional information

```text
k get node -o wide
NAME     STATUS   ROLES                  AGE    VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION    CONTAINER-RUNTIME
eniak2   Ready    control-plane,master   5d2h   v1.23.3   49.12.225.94   <none>        Debian GNU/Linux 11 (bullseye)   5.10.0-11-amd64   containerd://1.4.12
```

**Comment by juan131** [comment]
Hi @PhilipMay 

Please check the upgrading notes that explain how to upgrade from `10.x` step by step:

- https://docs.bitnami.com/kubernetes/infrastructure/postgresql/administration/upgrade/#upgrading-instructions

**Comment by PhilipMay** [comment]
@juan131 this is not an update issue. This is happening with a **fresh install**.

I am always using the `upgrade --install` parameters with Helm because then the update and install commands are the same.

In this case it is a new install.

**Comment by juan131** [comment]
Hi @PhilipMay 

I'm not able to reproduce your issue, see:

```console
$ helm search repo bitnami/postgresql
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/postgresql   	11.0.1       	14.1.0     	PostgreSQL (Postgres) is an open source object-...
$ helm template test bitnami/postgresql --set global.postgresql.auth.postgresPassword=123456789 -s templates/secrets.yaml
---
# Source: postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-postgresql
  namespace: default
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-11.0.2
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "MTIzNDU2Nzg5"
$ echo "MTIzNDU2Nzg5" | base64 --decode
123456789
```

**Comment by PhilipMay** [comment]
@juan131I am an idiot and used an outdated chart. Sorry and thanks for your help.

Closing this.

**Comment by pavelzag** [comment]
I am experiencing the same issue with:
```
CHART NAME: postgresql                                                                                                                                                                                                                                                                                                     
CHART VERSION: 12.1.6                                                                                                                                                                                                                                                                                                       APP VERSION: 15.1.0
```

My values.yaml file looks like this:

```
global:
  postgresql:
    auth:
      postgresPassword: "somepassword"
      username: "myuser"
      password: "somepassword"
      database: "my-db"

# The postgres helm chart deployment will be using PVC postgresql-data-claim
primary:
  persistence:
    enabled: true
    existingClaim: "postgresql-data-claim-1234"
```

I fail to connect to this DB with anything but 
```
user: myuser 
password: mysecretpassword
```

I am not running an upgrade, a fresh install
