### ISSUE TITLE
[bitnami/postgresql] Containers resources missing in template  - Helm chart version 10.16.2 to 11.0.1

### ISSUE THREAD

**Issue by tudburley** [bitnami/charts#8906]
### Name and Version

bitnami/postgresql 11.0.1

### What steps will reproduce the bug?

I upgraded bitnami/postgresql Helm chart from version 10.16.2 to 11.0.1. Values contain the following resource limits (excerpt):

```
postgresql:
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
```

With 10.16.2, the stateful set was rendered with the resource limits configured above.
With 11.0.1, the stateful set will be rendered without any resource limits.

### What is the expected behavior?

Resource limits given in the values should be rendered in the stateful set.

### What do you see instead?

No resource limits rendered in the stateful set.

### Additional information

The template `statefulset.yaml` seemed to be refactored and it is now missing the node `resources`:

`statefulset.yaml` from Helm version 10.16.2
```
spec:
  template:
    spec:
      containers:
        resources: {{- toYaml .Values.resources | nindent 12 }}
```
`statefulset.yaml` from Helm version 11.0.1 does not have this entry.

**Comment by tudburley** [comment]
Can be closed, it's no bug. The configuration of the resource limits for the primary stateful set has been changed to
```
postgresql:
  primary:
    resources:
    ....
```

Though the [Upgrading Notes to 11.0](https://docs.bitnami.com/kubernetes/infrastructure/postgresql/administration/upgrade/) do not mention that change.
