### ISSUE TITLE
tls secretName not being generated

### ISSUE THREAD

**Issue by bchrao** [bitnami/charts#8912]
### Name and Version

bitnami/keycloak 6.1.4

### What steps will reproduce the bug?

When we run helm with the values.tpl.yaml we see that the secrets are created and created with the correct names (ex FirstSite-tls). The SecondSite url is created properly with https and a cert attached to the config in Kubernetes. The FirstSite url is created with http and no cert attached.
 

### Are you using any custom parameters or values?

[values.tpl.yml.txt](https://github.com/bitnami/charts/files/8005562/values.tpl.yml.txt)

### What is the expected behavior?

FirstSite would be created with certificate configured

### What do you see instead?

FirstSite is http with no cert attached.

**Comment by carrodher** [comment]
In order to reproduce the scenario as similar as possible, can you please share with us the `values.yaml` used once rendered the template you attached in the previous comment?
```yaml
ingress:
  enabled: true
  hostname: ${hostname}
  tls: true
  secrets:
    - name: ${hostname}-tls
      certificate: |
        ${indent(8, file(ssl_FirstSite_certificate_path))}
      key: |
        ${indent(8, file(ssl_FirstSite_key_path))}
    - name: ${extra_hostname}-tls
      certificate: |
        ${indent(8, file(ssl_SecondSite_certificate_path))}
      key: |
        ${indent(8, file(ssl_SecondSite_key_path))}
  extraHosts:
    - name: ${extra_hostname}
  extraTls:
    - hosts:
      - ${extra_hostname}
      secretName: ${extra_hostname}-tls
```
