### ISSUE TITLE
[bitnami/mongodb] Anti-affinity doesn't work for arbiter

### ISSUE THREAD

**Issue by philraj** [bitnami/charts#8914]
### Name and Version

bitnami/mongo 11.0.0

### What steps will reproduce the bug?

1. Deploy the chart with `architecture: replicaset` and `podAntiAffinityPreset: hard`.

### Are you using any custom parameters or values?

```yaml
mongodb:
  architecture: replicaset
  podAntiAffinityPreset: hard
  arbiter:
    podAntiAffinityPreset: hard
```

### What is the expected behavior?

Primary and secondary mongod pods **and** the arbiter pod should all be scheduled onto separate worker nodes, if there are enough available. If a worker node is running the primary mongod pod and the arbiter, and it goes down, there won't be enough voters left to promote the secondary to act as the new primary.

### What do you see instead?

Primary and secondary pods spread out properly, but arbiter pod can be scheduled onto the same worker node as a mongod pod, because the `matchLabels` section for the arbiter includes the label `app.kubernetes.io/component: arbiter`, which does not match the label of `app.kubernetes.io/component: mongodb` on the mongod pods.
