### ISSUE TITLE
Mounting PVC for Magento media under pub/media makes persisting application to break

### ISSUE THREAD

**Issue by atroxix** [bitnami/charts#8915]
### Name and Version

bitnami/magento 19.2.3

### What steps will reproduce the bug?

1. Create PVC for media and let it be mounted to `/bitnami/magento/pub/media` with `extraVolumes` and `extraVolumeMounts`
2. In order to have `pub` correct permissions, define another volume for under extraVolumes with `emptyDir: {}` and let it be mounted under `/bitnami/magento/pub/` with `extraVolumeMounts`
3. When you now let Magento be set up then at the "Persisting" step the following error is thrown: `setfacl: pub: Operation not permitted`

### Are you using any custom parameters or values?

```
extraVolumes:
  - name: magento-data-pub
    emptyDir: {}
  - name: magento-media
    persistentVolumeClaim:
      claimName: pvc-magento-media
extraVolumeMounts:
  - name: magento-data-pub
    mountPath: /bitnami/magento/pub
  - name: magento-media
    mountPath: /bitnami/magento/pub/media
```

### What is the expected behavior?

Persisting Magento deployment is successful

### What do you see instead?

```
magento 14:10:14.47 INFO  ==> Persisting Magento installation
setfacl: pub: Operation not permitted
```
