### ISSUE TITLE
[bitnami/kafka] Unable to deploy TLS with SAN cert

### ISSUE THREAD

**Issue by tbnguyen1407** [bitnami/charts#8918]
### Name and Version

bitnami/kafka 15.0.4

### What steps will reproduce the bug?

1. Deploy with SAN cert (single secret)
```
helm install kafka bitnami/kafka --version "15.0.4" -f values.override.yaml
```

### Are you using any custom parameters or values?

~  values.override.yaml ~

```yaml
auth:
  clientProtocol: tls
  tls:
    jksTruststoreSecret: kafka-tls-secret
    jksTruststore: truststore.jks
    jksKeystoreSAN: keystore.jks
    password: jkspass
```

~ kafka-tls-secret ~
```yaml
data:
  keystore.jks: ABC
  truststore.jks: DEF
```

### What is the expected behavior?

Successful deployment

### What do you see instead?

```
Error: execution error at (kafka/templates/NOTES.txt:252:4):
VALUES VALIDATION:

kafka: auth.tls.existingSecrets
    A secret containing the Kafka JKS keystores and truststore is required
    when TLS encryption in enabled and TLS format is "JKS"
```

### Additional information

If specifying `auth.tls.existingSecrets` with the same SAN cert multiple times, the chart will switch to normal TLS cert setup (1 per broker) instead of SAN cert. The setup script will then fail to find the keystores as they are are not correctly named (kafka-X.keystore.jks)

~ pod logs ~
```
init::checking service status
Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled.
```

Seems to me this is simply value validation problem. `auth.tls.existingSecrets` is not a required config when setting up SAN cert.

https://github.com/bitnami/charts/blob/6c49a9b1c186bdb976aad1fa93225a8a39208b67/bitnami/kafka/templates/scripts-configmap.yaml#L122-L128
