### ISSUE TITLE
[bitnami/mariadb-galera] resolveip IPv6

### ISSUE THREAD

**Issue by ioachim-hub** [bitnami/charts#8921]
### Name and Version

bitnami/mariadb-galera:7.0.0

### What steps will reproduce the bug?

1. create kind cluster
kind.yaml:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
  - role: control-plane
  - role: worker
    image: docker.io/kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
  - role: worker
    image: docker.io/kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
  - role: worker
    image: docker.io/kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
networking:
  ipFamily: ipv6
  apiServerAddress: "::"
  apiServerPort: 6443
```
2. deploy mariadb-galera chart on IPv6
helmfile.yaml:
```
# yaml-language-server: $schema=https://json.schemastore.org/helmfile.json

helmDefaults:
  timeout: 600
  skipDeps: true
  historyMax: 2

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

missingFileHandler: Error

releases:
  - name: mariadb-galera
    chart: mariadb-galera
    namespace: default
    version: 7.0.0
    values:
      - image:
          debug: true
      - rootUser:
          user: root
          password: "98cNUsR3gEyfYMrW"
          forcePassword: true
      - podAntiAffinityPreset: hard
      - podManagementPolicy: OrderedReady
      - replicaCount: 3
      - livenessProbe:
          enabled: true
          periodSeconds: 60
          timeoutSeconds: 10
      - readinessProbe:
          enabled: true
          periodSeconds: 60
          timeoutSeconds: 10
      - galera:
          mariabackup:
            user: mariabackup
            password: "qHmBRW7UfcVv27OD"
            forcePassword: true
```
3. read the logs of 'mariadb-galera-0' pod ('mariadb-galera' container)
```
WARNING: The host 'mariadb-galera-0' could not be looked up with /opt/bitnami/mariadb/bin/resolveip.
This probably means that your libc libraries are not 100 % compatible
with this binary MariaDB version. The MariaDB daemon, mysqld, should work
normally with the exception that host name resolving will not work.
This means that you should use IP addresses instead of hostnames
when specifying MariaDB privileges !
```

### Are you using any custom parameters or values?

The custom parameters are visible in `helmfile.yaml`.
The values are:
- rootUser credentials
- podAntiAffinityPresent enabled on `hard`
- replicaCount set to `3`
- galera.mariabackup credentials

### What is the expected behavior?

The nodes can rejoin the channel `galera` after crash.

### What do you see instead?

The nodes can not rejoin the channel `galera` after crash.
Logs:
```
2022-02-07  9:28:11 0 [Note] WSREP: gcomm: connecting to group 'galera', peer 'mariadb-galera-headless.default.svc.cluster.local:'
2022-02-07  9:28:14 0 [Note] WSREP: EVS version upgrade 0 -> 1
2022-02-07  9:28:14 0 [Note] WSREP: PC protocol upgrade 0 -> 1
2022-02-07  9:28:14 0 [Warning] WSREP: no nodes coming from prim view, prim not possible
```
