### ISSUE TITLE
minio: provisioning job will fail on rerun when policies are added to users

### ISSUE THREAD

**Issue by hojerst** [bitnami/charts#8928]
### Name and Version

bitnami/minio 10.1.6

### What steps will reproduce the bug?

1. install with user provisioning
2. upgrade chart in any way, so the provisioning pod is rerun

### Are you using any custom parameters or values?

```yaml
provisioning:
  enabled: true
  users:
    - username: testuser
      password: testpass
      disabled: false
      policies:
        - readwrite       # this fails on second run of provisioning container
```

### What is the expected behavior?

Upgrading the Chart should be possible with provisioning enabled.

### What do you see instead?

Chart upgrade fails because the provisioning Pod does fail with:

```
mc: <ERROR> Unable to update the policy: policy `readwrite` already exists.
```

### Additional information

The policies seem to be rendered out as `mc admin policy update provisioning readwrite user=testuser`. However this command is not idempotent and fails with `mc: <ERROR> Unable to update the policy: policy `readwrite` already exists.` when the policy is already assigned to the user.

Using `mc admin policy set provisioning readwrite,policy2,policy3 user=testuser` should work multiple times, but this will remove all other policies. (in my usecase this would be desirable, but might depend on expectations, though).
