### ISSUE TITLE
Airflow Redis password key value is not used

### ISSUE THREAD

**Issue by ameier38** [bitnami/charts#8984]
### Name and Version

bitnami/airflow 12.0.1

### What steps will reproduce the bug?

Set the value of `externalRedis.existingSecretPasswordKey` to anything other than `redis-password`

### Are you using any custom parameters or values?

`externalRedis.existingSecretPasswordKey=password`

### What is the expected behavior?

Airflow will use the specified redis password secret key

### What do you see instead?

Deployment fails because it is looking for hardcoded value `redis-password`

### Additional information

In [_helpers.tpl](https://github.com/bitnami/charts/blob/0dc3f89b08da451ab95bdf4f04125562c6c136d6/bitnami/airflow/templates/_helpers.tpl#L349) the defined redis key is not actually used.
Current:
```
- name: REDIS_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ include "airflow.redis.secretName" . }}
      key: redis-password
```
Should be
```
- name: REDIS_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ include "airflow.redis.secretName" . }}
      key: {{ include "airflow.redis.existingsecret.key" . }}
```
