### ISSUE TITLE
[bitnami/postgresql] Volume permission container should not be required to use TLS

### ISSUE THREAD

**Issue by OvervCW** [bitnami/charts#8990]
### Name and Version

bitnami/postgresql 11.0.2

### What is the problem this feature will solve?

It should be possible to enable TLS for PostgreSQL without having to enable the volume permission container, because I'd like to avoid containers that run as root.

### What is the feature you are proposing to solve the problem?

Rework the certificate file permission handling to not require the volume permission container.

### What alternatives have you considered?

I've temporarily removed `runAsNonRoot: true` from the pod security context to allow the volume permission container to run, but I'd much prefer disabling it.

**Comment by juan131** [comment]
Hi @OvervCW 

Could you please provide the values.yaml you're using to deploy the PostgreSQL chart? I'd like to reproduce the issue on my side. Thanks in advance.

**Comment by OvervCW** [comment]
@juan131 Sure, the values are:

```yaml
tls:
  enabled: true
  certificatesSecret: xxx
  certFilename: xxx
  certKeyFilename: xxx

volumePermissions:
  enabled: false
```

And they are rejected by this code:

https://github.com/bitnami/charts/blob/f1b572a51d4b539f9eb690437766cc6e6467a053/bitnami/postgresql/templates/_helpers.tpl#L261-L270
