### ISSUE TITLE
[bitnami/wordpress 11.1.5] Unable to deploy wordpress helm chart to OpenShift: Forbidden: not usable by user or serviceaccount

### ISSUE THREAD

**Issue by hectoralicea** [bitnami/charts#9010]
### Name and Version

`bitnami/wordpress` 11.1.5

### What steps will reproduce the bug?

 Step 1 - log into openshift cluster and update helm repo

```bash
oc login --token=sha256~TWI9D********C3e4mSkrNvrZvSwRo --server=https://api.oslab.duh.com:6443
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
```

Step 2 - add annotations to allow for user id / group id of 1001

```bash
oc annotate --overwrite namespace wp-template1 openshift.io/sa.scc.supplemental-groups=1000/1000
oc annotate --overwrite namespace wp-template1 openshift.io/sa.scc.uid-range=1000/1000
```

Step 3 - run helm install / update

```bash
helm upgrade template1 bitnami/wordpress  --version 11.1.5  --install  --namespace wp-template1  --debug  --wait  --timeout 20m  -f wordpress-values.yaml
```

### Are you using any custom parameters or values?

```yaml
## @param nameOverride String to partially override common.names.fullname
##
nameOverride: template1
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: template1
## @param commonLabels Labels to add to all deployed objects
##
#commonLabels: template1
## @param clusterDomain Kubernetes cluster domain name
##
clusterDomain: rke2-dev.duh.com

## @section WordPress Image parameters

## Bitnami WordPress image
## ref: https://hub.docker.com/r/bitnami/wordpress/tags/
## @param image.registry WordPress image registry
## @param image.repository WordPress image repository
## @param image.tag WordPress image tag (immutable tags are recommended)
## @param image.pullPolicy WordPress image pull policy
## @param image.pullSecrets WordPress image pull secrets
## @param image.debug Enable image debug mode
##
image:
  ## Enable debug mode
  ##
  debug: true
## @param wordpressUsername WordPress username
##
wordpressUsername: wpun
## @param wordpressPassword WordPress user password
## Defaults to a random 10-character alphanumeric string if not set
##
wordpressPassword: '1234'
## @param wordpressEmail WordPress user email
##
wordpressEmail: mini_me@duh.com
## @param wordpressFirstName WordPress user first name
##
wordpressFirstName: Mini
## @param wordpressLastName WordPress user last name
##
wordpressLastName: Me
## @param wordpressPlugins Array of plugins to install and activate. Can be specified as `all` or `none`.
## NOTE: If set to all, only plugins that are already installed will be activated, and if set to none, no plugins will be activated
##
wordpressPlugins: none
## @param customPostInitScripts Custom post-init.d user scripts
## ref: https://github.com/bitnami/bitnami-docker-wordpress/tree/master/5/debian-10/rootfs/post-init.d
## NOTE: supported formats are `.sh`, `.sql` or `.php`
## NOTE: scripts are exclusively executed during the 1st boot of the container
## e.g:
## customPostInitScripts:
##   enable-multisite.sh: |
##     #!/bin/bash
##     chmod +w /bitnami/wordpress/wp-config.php
##     wp core multisite-install --url=example.com --title="Welcome to the WordPress Multisite" --admin_user="doesntmatternotreallyused" --admin_password="doesntmatternotreallyused" --admin_email="user@example.com"
##     cat /docker-entrypoint-init.d/.htaccess > /bitnami/wordpress/.htaccess
##     chmod -w bitnami/wordpress/wp-config.php
##   .htaccess: |
##     RewriteEngine On
##     RewriteBase /
##     ...
##
customPostInitScripts:
  wp-migrate-import-db.sh: |
    #!/bin/bash
    wp --version

## @param allowEmptyPassword Allow the container to be started with blank passwords
##
allowEmptyPassword: false
## @param extraEnvVars Array with extra environment variables to add to the WordPress container
## e.g:
## extraEnvVars:
##   - name: FOO
##     value: "bar"
##
extraEnvVars:
  - name: GIT_REPO_CRED_USER
    valueFrom: 
      secretKeyRef:
        name: wp-template1-git-credential-secret
        key: username
  - name: GIT_REPO_CRED_USER_PASSWORD
    valueFrom: 
      secretKeyRef:
        name: wp-template1-git-credential-secret
        key: password
  - name: GIT_BRANCH_WORDPRESS_SITE
    value: "main"
  - name: GIT_BRANCH_WORDPRESS_PLUGINS
    value: "main"
  - name: GIT_DISCOVERY_ACROSS_FILESYSTEM
    value: "1"

## @section WordPress deployment parameters

## @param replicaCount Number of WordPress replicas to deploy
## NOTE: ReadWriteMany PVC(s) are required if replicaCount > 1
##
replicaCount: 1
## @param hostAliases [array] WordPress pod host aliases
## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
##
hostAliases:
  ## Required for apache-exporter, and other backup plugins to work
  - ip: "127.0.0.1"
    hostnames:
      - "template1.rke2-dev.duh.com"
## @param extraVolumes Optionally specify extra list of additional volumes for WordPress pods
##
extraVolumes:
  - name: wordpress-git
    persistentVolumeClaim:
      claimName: template1-git
  - name: init-mutex-fs
    persistentVolumeClaim:
      claimName: template1-mutex

## @param extraVolumeMounts Optionally specify extra list of additional volumeMounts for WordPress container(s)
##
extraVolumeMounts:
  - mountPath: /bitnami/wordpress-git
    name: wordpress-git
    subPath: wordpress-git
  - mountPath: /bitnami/init-mutex-fs
    name: init-mutex-fs
    subPath: init-mutex-fs         

## @param sidecars Add additional sidecar containers to the WordPress pod
## e.g:
## sidecars:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
sidecars:
  - name: git-sidecar
    image: aphex3k/curl-git-lfs:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
      runAsGroup: 1001
    env:
      - name: GIT_REPO_CRED_USER
        valueFrom: 
          secretKeyRef:
            name: wp-template1-git-credential-secret
            key: username
      - name: GIT_REPO_CRED_USER_PASSWORD
        valueFrom: 
          secretKeyRef:
            name: wp-template1-git-credential-secret
            key: password
      - name: GIT_BRANCH_WORDPRESS_SITE
        value: "main"
      - name: GIT_BRANCH_WORDPRESS_PLUGINS
        value: "main"
      - name: GIT_DISCOVERY_ACROSS_FILESYSTEM
        value: "1"
    command: 
      - '/bin/sh'
      - '-c'
      - |
        #!/bin/sh
        cd /bitnami/wordpress-git
        while true; do echo Keep running this sidecar ; git status || true ; sleep 5 ; done

    volumeMounts:
      - mountPath: /bitnami/wordpress
        name: wordpress-data
        subPath: wordpress    
      - mountPath: /bitnami/wordpress-git
        name: wordpress-git
        subPath: wordpress-git
      - mountPath: /bitnami/init-mutex-fs
        name: init-mutex-fs
        subPath: init-mutex-fs

## @param initContainers Add additional init containers to the WordPress pods
## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
## e.g:
initContainers:
  - name: init
    image: aphex3k/curl-git-lfs:latest    
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
      runAsGroup: 1001
    env:
      - name: GIT_REPO_CRED_USER
        valueFrom: 
          secretKeyRef:
            name: wp-template1-git-credential-secret
            key: username
      - name: GIT_REPO_CRED_USER_PASSWORD
        valueFrom: 
          secretKeyRef:
            name: wp-template1-git-credential-secret
            key: password
      - name: GIT_BRANCH_WORDPRESS_SITE
        value: "main"
      - name: GIT_BRANCH_WORDPRESS_PLUGINS
        value: "main"
      - name: GIT_DISCOVERY_ACROSS_FILESYSTEM
        value: "1"
    command: 
      - '/bin/sh'
      - '-c'
      - |
        #!/bin/sh
        # ls -alR /bitnami

    volumeMounts:
      - mountPath: /bitnami/wordpress
        name: wordpress-data
        subPath: wordpress    
      - mountPath: /bitnami/wordpress-git
        name: wordpress-git
        subPath: wordpress-git  
      - mountPath: /bitnami/init-mutex-fs
        name: init-mutex-fs
        subPath: init-mutex-fs         
##
## WordPress service parameters
##
service:
  ## @param service.type WordPress service type
  ##
  type: ClusterIP
  ## @param service.port WordPress service HTTP port
  ##
ingress:
  ## @param ingress.enabled Enable ingress record generation for WordPress
  ##
  enabled: true
  ## @param ingress.hostname Default host for the ingress record
  ##
  hostname: template1.rke2-dev.duh.com
## @section Persistence Parameters

## Persistence Parameters
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  ## @param persistence.accessModes [array] Persistent Volume access modes
  ##
  accessModes:
#   - ReadWriteOnce
    - ReadWriteMany
## 'volumePermissions' init container parameters
## Changes the owner and group of the persistent volume mount point to runAsUser:fsGroup values
##   based on the podSecurityContext/containerSecurityContext parameters
##
volumePermissions:
  ## @param volumePermissions.enabled Enable init container that changes the owner/group of the PV mount point to `runAsUser:fsGroup`
  ##
  enabled: false
  ## Init container Container Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ## @param volumePermissions.securityContext.runAsUser Set init container's Security Context runAsUser
  ## NOTE: when runAsUser is set to special value "auto", init container will try to chown the
  ##   data folder to auto-determined user&group, using commands: `id -u`:`id -G | cut -d" " -f2`
  ##   "auto" is especially useful for OpenShift which has scc with dynamic user ids (and 0 is not allowed)
  ##
#  securityContext:
#    runAsUser: 1001
## Wordpress Autoscaling configuration
## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
## @param autoscaling.enabled Enable Horizontal POD autoscaling for WordPress
## @param autoscaling.minReplicas Minimum number of WordPress replicas
## @param autoscaling.maxReplicas Maximum number of WordPress replicas
## @param autoscaling.targetCPU Target CPU utilization percentage
## @param autoscaling.targetMemory Target Memory utilization percentage
##
autoscaling:
  enabled: true
  # set min/max replicas to 1 to start until container initializes then playbook will increase after pods initialize and stablize
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 50
  targetMemory: 50
mariadb:
  enabled: false
    
externalDatabase:
  host: mysqld.duh.com
  port: 42158
  user: AnsibleSVC_template1
  password: randompw
  database: template1
```

### What is the expected behavior?

should deploy without error

### What do you see instead?

when I do a kubectl get events I get the following errors:
```
kc get events -n wp-template1
LAST SEEN   TYPE      REASON                         OBJECT                                  MESSAGE
2m2s        Warning   FailedCreate                   replicaset/template1-7f87fc6c4          Error creating: pods "template1-7f87fc6c4-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted: .spec.securityContext.fsGroup: Invalid value: []int64{1001}: 1001 is not an allowed group, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
23m         Normal    ExternalProvisioning           persistentvolumeclaim/template1-git     waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
23m         Normal    Provisioning                   persistentvolumeclaim/template1-git     External provisioner is provisioning volume for claim "wp-template1/template1-git"
23m         Normal    ProvisioningSucceeded          persistentvolumeclaim/template1-git     Successfully provisioned volume pvc-e609a6eb-7109-46f3-8c5f-f1ac926af987
23m         Normal    ExternalProvisioning           persistentvolumeclaim/template1-mutex   waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
23m         Normal    Provisioning                   persistentvolumeclaim/template1-mutex   External provisioner is provisioning volume for claim "wp-template1/template1-mutex"
23m         Normal    ProvisioningSucceeded          persistentvolumeclaim/template1-mutex   Successfully provisioned volume pvc-77ebd05f-e6bc-417e-a93d-a12c474e3878
23m         Normal    ExternalProvisioning           persistentvolumeclaim/template1         waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
23m         Normal    Provisioning                   persistentvolumeclaim/template1         External provisioner is provisioning volume for claim "wp-template1/template1"
23m         Normal    ScalingReplicaSet              deployment/template1                    Scaled up replica set template1-7f87fc6c4 to 1
23m         Normal    ProvisioningSucceeded          persistentvolumeclaim/template1         Successfully provisioned volume pvc-7a97f9d2-e167-4dc6-8cae-a90f17af0cc6
3m14s       Warning   FailedGetResourceMetric        horizontalpodautoscaler/template1       failed to get memory utilization: unable to get metrics for resource memory: no metrics returned from resource metrics API
21m         Warning   FailedGetResourceMetric        horizontalpodautoscaler/template1       failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
21m         Warning   FailedComputeMetricsReplicas   horizontalpodautoscaler/template1       invalid metrics (2 invalid out of 2), first error is: failed to get memory utilization: unable to get metrics for resource memory: no metrics returned from resource metrics API
23m         Normal    CreatedSCCRanges               namespace/wp-template1                  created SCC ranges
```

Note we do have longhorn installed in our OCP container to service as our default storage class.
