### ISSUE TITLE
[bitnami/logstash] No logstash.yml in configuration-cm.yaml template

### ISSUE THREAD

**Issue by andy812** [bitnami/charts#9017]
### Name and Version

bitnami/logstash 3.7.4

### What is the problem this feature will solve?

I want to add `pipeline.ecs_compability` option in `/opt/bitnami/logstash/config/logstash.yml`, but i have no way to do it.

### What is the feature you are proposing to solve the problem?

Please, add `logstash.yml` in `configuration-cm.yaml` template and mount it as the volume is `sts.yaml`.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. I will forward this to the engineering team. As this is not a critical feature, we cannot guarantee an ETA. However, if you want to speed up the process, feel free to submit a PR and we will review it

**Comment by NYARAS** [comment]
> 

How can someone do this? I'm currently facing the issues where I want to add some configurations like these

```yaml
    xpack.monitoring.elasticsearch.hosts:
    - http://elasticsearch:9200
    xpack.monitoring.enabled: false
    pipeline.batch.delay: 100
    pipeline.batch.size: 250
    pipeline.workers: 8
```

But I cannot do it.
