### ISSUE TITLE
[bitnami/mongodb] selector is not available for non-sts deployment (possible bug?)

### ISSUE THREAD

**Issue by ComradePashka** [bitnami/charts#9018]
### Name and Version

bitnami/mongodb:11.0.3

### What steps will reproduce the bug?

mongodb is setup as dependency (subchart) to my own chart:
```yaml
dependencies:
  - name: mongodb
    version: 11.0.3
    repository: https://charts.bitnami.com/bitnami
```

I want to use standalone mode with persistency and PVC with selectors so I passed values to subchart via main values.yaml:
```yaml
mongodb:
  auth:
    rootPassword: "somepassword"
    usernames: ["root"]
    passwords: ["somepassword"]
    databases: ["db"]
  persistence:
    enabled: true
    annotations:
      test-annotation: "test-annotation-value"
    size: "4Gi"
    volumeClaimTemplates:
      selector:
        matchLabels:
          app: "my-app"
```

so according to `mongodb\templates\standalone\dep-sts.yaml` if .Values.persistence.enabled and there's no .Values.persistence.existingClaim and .Values.useStatefulSet is not set then volume created with:
```yaml
        - name: datadir
          persistentVolumeClaim:
            claimName: {{ template "mongodb.fullname" . }}
```
and volumeClaimTemplates block which is added when .Values.useStatefulSet is enabled and contains selector will be never used in my case, while  `mongodb\templates\standalone\pvc.yaml` doesn't contain any selector tag. 

and volumeClaimTemplates section used when .Values.useStatefulSet is true contains following code:
```yaml
selector: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.volumeClaimTemplates.selector "context" $) | nindent 10 }}
```
so should it be added to mongodb\templates\standalone\pvc.yaml spec section?

I found in other issues not directly related to my case some people suggest to use .Values.persistence.existingClaim
it looks like sort of workaround, but I belive it should be way to setup selector just using existing helm charts.

### What is the expected behavior?

pvc with selectors that are possible to bind to manually created pv with specific labels.

### What do you see instead?

I am still not sure if it is really bug, so with my config I got PVC as follows:
```yaml
# Source: gigco-solana-gw/charts/mongodb/templates/standalone/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: solana-gw-dev-mongodb
  namespace: default
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-11.0.3
    app.kubernetes.io/instance: solana-gw-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
  annotations:
    a: b
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"
```

and I really need selectors, bc I have more than one mongodb services for dev/prod stages which definitely must use different pv and pvc

### Additional information

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

```console
$ docker version
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by ComradePashka** [comment]
UPD, so with .Values.persistence.existingClaim set upt to 'my-pvc' and following conf for pv/pvc pair everything is working, but I still interested in using selectors only with mongodb chart config:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace: default
  labels:
    app: my-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/db/mongodb/dev"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      app: "my-pv"
```
