### ISSUE TITLE
[bitnami/kong] Kong-ingress-controller deployment failure when configured as DB-less

### ISSUE THREAD

**Issue by superbobmtl** [bitnami/charts#9022]
### Name and Version

bitnami/kong 5.0.5

### What steps will reproduce the bug?

I pulled latest chart release 5.0.5 to my VM. I extracted it so I can change some parameters in values.yaml to deploy DB-less, and deploy using command:

helm install kong -f kong/values.yaml kong

I get same result if I run command:
```
helm install kong -f kong/values.yaml bitnami/kong
```

### Are you using any custom parameters or values?

I followed the instructions in the README.md for DB-less deployment plus disable postgresql:

1. database: "off"
2. kong.extraEnvVars: 
   - name: KONG_DATABASE
     value: "off"
3. postgresql.enabled: false

### What is the expected behavior?

Expected the kong pod to be up and running

### What do you see instead?

The kong-ingress-controller service failed after 5 minutes (9 restarts) with following error:
```
W0215 15:27:24.002922      16 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: failed to list *v1beta1.UDPIngress: udpingresses.configuration.konghq.com is forbidden: User "system:serviceaccount:default:kong" cannot list resource "udpingresses" in API group "configuration.konghq.com" at the cluster scope
E0215 15:27:24.002981      16 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.UDPIngress: failed to list *v1beta1.UDPIngress: udpingresses.configuration.konghq.com is forbidden: User "system:serviceaccount:default:kong" cannot list resource "udpingresses" in API group "configuration.konghq.com" at the cluster scope
time="2022-02-15T15:27:40Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for service caches to sync: timed out waiting for cache to be synced" logger=controller.service reconciler group= reconciler kind=Service
time="2022-02-15T15:27:40Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for secret caches to sync: timed out waiting for cache to be synced" logger=controller.secret reconciler group= reconciler kind=Secret
time="2022-02-15T15:27:40Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for tcpingress caches to sync: timed out waiting for cache to be synced" logger=controller.tcpingress reconciler group=configuration.konghq.com reconciler kind=TCPIngress
time="2022-02-15T15:27:40Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for ingress caches to sync: timed out waiting for cache to be synced" logger=controller.ingress reconciler group=networking.k8s.io reconciler kind=Ingress
time="2022-02-15T15:27:40Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for endpoints caches to sync: timed out waiting for cache to be synced" logger=controller.endpoints reconciler group= reconciler kind=Endpoints
time="2022-02-15T15:27:40Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for udpingress caches to sync: timed out waiting for cache to be synced" logger=controller.udpingress reconciler group=configuration.konghq.com reconciler kind=UDPIngress
time="2022-02-15T15:27:40Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for kongplugin caches to sync: timed out waiting for cache to be synced" logger=controller.kongplugin reconciler group=configuration.konghq.com reconciler kind=KongPlugin
time="2022-02-15T15:27:40Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for secret caches to sync: timed out waiting for cache to be synced"
time="2022-02-15T15:27:40Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for tcpingress caches to sync: timed out waiting for cache to be synced"
time="2022-02-15T15:27:40Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for ingress caches to sync: timed out waiting for cache to be synced"
time="2022-02-15T15:27:40Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for endpoints caches to sync: timed out waiting for cache to be synced"
time="2022-02-15T15:27:40Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for udpingress caches to sync: timed out waiting for cache to be synced"
time="2022-02-15T15:27:40Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for kongplugin caches to sync: timed out waiting for cache to be synced"
time="2022-02-15T15:27:40Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for kongconsumer caches to sync: timed out waiting for cache to be synced" logger=controller.kongconsumer reconciler group=configuration.konghq.com reconciler kind=KongConsumer
time="2022-02-15T15:27:40Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for kongingress caches to sync: timed out waiting for cache to be synced" logger=controller.kongingress reconciler group=configuration.konghq.com reconciler kind=KongIngress
time="2022-02-15T15:27:40Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for kongclusterplugin caches to sync: timed out waiting for cache to be synced" logger=controller.kongclusterplugin reconciler group=configuration.konghq.com reconciler kind=KongClusterPlugin
time="2022-02-15T15:27:40Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for kongconsumer caches to sync: timed out waiting for cache to be synced"
time="2022-02-15T15:27:40Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for kongingress caches to sync: timed out waiting for cache to be synced"
time="2022-02-15T15:27:40Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for kongclusterplugin caches to sync: timed out waiting for cache to be synced"
time="2022-02-15T15:27:40Z" level=info msg="Stopping and waiting for non leader election runnables"
time="2022-02-15T15:27:40Z" level=info msg="Stopping and waiting for leader election runnables"
time="2022-02-15T15:27:40Z" level=info msg="Stopping and waiting for caches"
time="2022-02-15T15:27:40Z" level=info msg="context done: shutting down the proxy update server" subsystem=proxy-cache-resolver
time="2022-02-15T15:27:40Z" level=error msg="context completed with error" error="context canceled" subsystem=proxy-cache-resolver
time="2022-02-15T15:27:40Z" level=info msg="Stopping and waiting for webhooks"
time="2022-02-15T15:27:40Z" level=info msg="stop status update channel."
time="2022-02-15T15:27:40Z" level=info msg="Wait completed, proceeding to shutdown the manager"
Error: failed to wait for service caches to sync: timed out waiting for cache to be synced
Error: failed to wait for service caches to sync: timed out waiting for cache to be synced
```

### Additional information

When I compare CRDs file custom-resource-definitions.yaml with the same file in kong.hq, it is missing the entire UDPIngress section. Is this a mistake? Or how to make the kong-ingress-controller starts correctly?

My environment:
  Kubernetes version 1.21.7
  Helm version 3.6.3

**Comment by marcosbc** [comment]
Hi @superbobmtl, unfortunately this is not a scenario that we are testing, so it is something we are officially able to support. However, we are open to any contributions for supporting such scenarios.

>When I compare CRDs file custom-resource-definitions.yaml with the same file in kong.hq, it is missing the entire UDPIngress section. Is this a mistake? Or how to make the kong-ingress-controller starts correctly?

That is probably a mistake. Would you be up for sending a PR to modify it?

**Comment by readverish** [comment]
The missing  UDPIngress  CRD problem, that impeded the kong-ingress-controller from starting is partially fixed. The CRD is now in the chart, except that the ClusterRole is missing the accesses to the udpingresses endpoints (see below excerpt of the ClusterRole included in the helm chart). 

```
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: server
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  name: {{ template "common.names.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - nodes
      - pods
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
      - "networking.internal.knative.dev"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
      - "networking.internal.knative.dev"
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - "configuration.konghq.com"
    resources:
      - tcpingresses/status
    verbs:
      - update
  - apiGroups:
      - "configuration.konghq.com"
    resources:
      - kongplugins
      - kongclusterplugins
      - kongcredentials
      - kongconsumers
      - kongingresses
      - tcpingresses
    verbs:
      - get
      - list
      - watch

```
