### ISSUE TITLE
Unterminated quoted string on prometheus rules with specific text lengths

### ISSUE THREAD

**Issue by maxnitze** [bitnami/charts#9028]
### Name and Version

bitnami/postgresql 14.1.0

### What steps will reproduce the bug?

Add one of the following rules in the `metrics.prometheusRule.rules` section of the chart:

```yaml
- alert: PostgresqlTableNotAnalyzed
  expr: time() - pg_stat_user_tables_last_autoanalyze{namespace="{{ .Release.Namespace }}", service="{{ printf "%s-metrics" (include "postgresql.primary.fullname" .) }}"} > 60 * 60 * 24
  for: 0m
  labels:
    severity: warning
  annotations:
    summary: Postgresql table not analyzed (instance {{ "{{ $labels.instance }}" }})
    description: Table has not been analyzed for 24 hours\n  VALUE = {{ "{{ $value }}" }}\n  LABELS = {{ "{{ $labels }}" }}
```

```yaml
- alert: PostgresqlHighRateStatementTimeout
  expr: rate(postgresql_errors_total{namespace="{{ .Release.Namespace }}", service="{{ printf "%s-metrics" (include "postgresql.primary.fullname" .) }}", type="statement_timeout"}[1m]) > 3
  for: 0m
  labels:
    severity: critical
  annotations:
    summary: Postgresql high rate statement timeout (instance {{ "{{ $labels.instance }}" }})
    description: Postgres transactions showing high rate of statement timeouts\n  VALUE = {{ "{{ $value }}" }}\n  LABELS = {{ "{{ $labels }}" }}
```

### What do you see instead?

```
parse error at (my-chart/charts/postgresql/templates/primary/prometheusrule.yaml:XXX): unterminated quoted string
```

### Additional information

Copied the rules from https://awesome-prometheus-alerts.grep.to/rules.html#postgresql

Could fix both rules by adding or removing characters from them. There are other rules with similar problems. I had a look at the template, but I could not really figure out where this issue comes from.

#### PostgresqlTableNotAnalyzed

Adding ten spaces between the "hours" and "\n" in the description will make the rule render successfully.

#### PostgresqlHighRateStatementTimeout

Removing the leading "Postgresql" in the summary will make the rule render successfully.

**Comment by maxnitze** [comment]
Could fix this issue by using multiline strings.

Still unsure why the former one failed though. Is Helm introducing line breaks in its values, which in my case ended up in between two quotes?

**Comment by fmulero** [comment]
Hi @maxnitze 

From your error it seems you are trying to work in your own chart. I tried to reproduce it using directly the 
latest `bitnami/postgresql` chart  (version 11.0.4) without success. This is the `values.yaml` that I used:
```
auth:
  database: test
metrics:
  enabled: true
  prometheusRule:
    enabled: true
    rules:
      - alert: PostgresqlTableNotAnalyzed
        expr: time() - pg_stat_user_tables_last_autoanalyze{namespace="{{ .Release.Namespace }}", service="{{ printf "%s-metrics" (include "postgresql.primary.fullname" .) }}"} > 60 * 60 * 24
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Postgresql table not analyzed (instance {{ "{{ $labels.instance }}" }})
```

Could you share more information? For example commands run and outputs

**Comment by maxnitze** [comment]
Hey,

I created a minimal setup that fails with the _unterminated quoted string_ error:

```bash
$ ls -a my-chart 
.  ..  Chart.lock  charts  Chart.yaml  values.yaml
```

```bash
$ cat my-chart/Chart.yaml
apiVersion: v2
name: my-app
version: 1.0.0
dependencies:
  - name: postgresql
    version: 11.0.4
    repository: https://charts.bitnami.com/bitnami
```

```bash
$ cat my-chart/values.yaml
postgresql:
  auth:
    database: postgres
  metrics:
    enabled: true
    prometheusRule:
      enabled: true
      rules:
        - alert: PostgresqlHighRateStatementTimeout
          expr: rate(postgresql_errors_total{namespace="{{ .Release.Namespace }}", service="{{ printf "%s-metrics" (include "postgresql.primary.fullname" .) }}", type="statement_timeout"}[1m]) > 3
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: Postgresql high rate statement timeout (instance {{ "{{ $labels.instance }}" }})
            description: Postgres transactions showing high rate of statement timeouts\n  VALUE = {{ "{{ $value }}" }}\n  LABELS = {{ "{{ $labels }}" }}
```

```bash
$ helm template my-app --namespace my-app ./my-chart                      
Error: template: my-chart/charts/postgresql/templates/primary/prometheusrule.yaml:21:17: executing "my-chart/charts/postgresql/templates/primary/prometheusrule.yaml" at <include "common.tplvalues.render" (dict "value" .Values.metrics.prometheusRule.rules "context" $)>: error calling include: template: my-chart/charts/postgresql/charts/common/templates/_tplvalues.tpl:11:12: executing "common.tplvalues.render" at <tpl (.value | toYaml) .context>: error calling tpl: error during tpl function execution for "- alert: PostgresqlHighRateStatementTimeout\n  annotations:\n    description: Postgres transactions showing high rate of statement timeouts\\n  VALUE\n      = {{ \"{{ $value }}\" }}\\n  LABELS = {{ \"{{ $labels }}\" }}\n    summary: Postgresql high rate statement timeout (instance {{ \"{{ $labels.instance\n      }}\" }})\n  expr: rate(postgresql_errors_total{namespace=\"{{ .Release.Namespace }}\", service=\"{{\n    printf \"%s-metrics\" (include \"postgresql.primary.fullname\" .) }}\", type=\"statement_timeout\"}[1m])\n    > 3\n  for: 0m\n  labels:\n    severity: critical": parse error at (my-chart/charts/postgresql/templates/primary/prometheusrule.yaml:5): unterminated quoted string

Use --debug flag to render out invalid YAML
```

What also fixed the issue is _escaping_ the parts, that should be _templated by Prometheus_ another way.

Instead of _escaping_ it as a whole like

```go
VALUE = {{ "{{ $value }}" }}\n  LABELS = {{ "{{ $labels }}" }}
```

_escaping_ the curly brackets alone

```go
VALUE = {{ "{{" }} $value {{ "}}" }}\n  LABELS = {{ "{{" }} $labels {{ "}}" }}
```

**Comment by fmulero** [comment]
Hi @maxnitze 

My fault, I didn't copy the description line what is causing the issue. I think this issue is in the `toYaml` function (so w can't do too much hereto be honest), this function automatically wraps the text to 80 characters (aprox) adding new lines if needed.

Thanks for sharing the solution you found. Other possible solution and clear way to avoid the auto-wrapping is setting the description directly in multiple lines:
```yaml
auth:
  database: test
metrics:
  enabled: true
  prometheusRule:
    enabled: true
    rules:
      - alert: PostgresqlTableNotAnalyzed
        expr: time() - pg_stat_user_tables_last_autoanalyze{namespace="{{ .Release.Namespace }}", service="{{ printf "%s-metrics" (include "postgresql.primary.fullname" .) }}"} > 60 * 60 * 24
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Postgresql table not analyzed (instance {{ "{{ $labels.instance }}" }})
          description: |
            Table has not been analyzed for 24 hours
            VALUE = {{ "{{ $value }}" }}
            LABELS = {{ "{{ $labels }}" }}
```
