### ISSUE TITLE
Metrics exporter not starting

### ISSUE THREAD

**Issue by sveba** [bitnami/charts#9041]
### Name and Version

bitnami/kafka 15.2.1

### What steps will reproduce the bug?

1. K8s-env
2. TLS configuration 
3. Metrics exporter deployment pods not starting properly 

### What do you see instead?

```
I0216 15:04:48.378433 1 kafka_exporter.go:769] Starting kafka_exporter (version=1.4.2, branch=non-git, revision=non-git)
F0216 15:04:48.378612 1 kafka_exporter.go:865] open "/opt/bitnami/kafka-exporter/cacert/tls.crt": no such file or directory
```

### Additional information

The problem is that attribute value quotes are not being removed, when not run in shell. eg:

```
/bin/bash -c kafka_exporter --tls.ca-file="/opt/bitnami/kafka-exporter/certs/{{ .Values.metrics.kafka.tlsCaCert }}"
```

most of the shells remove the quotes when passing the argumenst to the command 

BUT:

the deployment  is using `kafka_exporter --tls.ca-file="/opt/bitnami/kafka-exporter/certs/{{ .Values.metrics.kafka.tlsCaCert }}"` as command. So the `kafka_exporter` is trying to find the path **WITH** quotes

**Comment by juan131** [comment]
Thanks so much for reporting this issue @sveba ! I just approved/merged your PR

**Comment by GaneshbabuRamamoorthy** [comment]
@juan131 

I am facing this similar issue in my k8s environment

I have tried enabling kafka-exporter in the values.yaml and below is the config I have added,

```
## Prometheus Exporters / Metrics
##
metrics:
  ## Prometheus Kafka exporter: exposes complimentary metrics to JMX exporter
  ##
  kafka:
    enabled: true
    image:
      registry: artifactory.dev.com
      repository: dev/kafka-exporter
      tag: 1.4.2
      pullPolicy: IfNotPresent
      pullSecrets:
        - artifactory-registry
    certificatesSecret: "kafka-certs-0"
    tlsCert: kafka.truststore.jks
    tlsKey: kafka.keystore.jks
    tlsCaSecret: ""
    tlsCaCert:
    extraFlags:
      tls.insecure-skip-tls-verify: ""
```
      
Below is the kafka-exporter pod describe,

```
Containers:
  kafka-exporter:
    Container ID:  docker://944a7c097b8baae5e0f1b43665329cd4edb692d5ca5a24647a29f15532712632
    Image:         artifactory.dev.com/dev/kafka-exporter:1.4.2
    Image ID:      docker-pullable://artifactory.dev.com/dev/kafka-exporter@sha256:0c1187265da44b3faa971ed4c928cd4f8663d72248bca8cf0
    Port:          9308/TCP
    Host Port:     0/TCP
    Command:
      kafka_exporter
    Args:
      --kafka.server=kafka-0.kafka-headless.es.svc.cluster.local:9092
      --kafka.server=kafka-1.kafka-headless.es.svc.cluster.local:9092
      --tls.enabled
      --tls.key-file=/opt/bitnami/kafka-exporter/certs/kafka.keystore.jks
      --tls.cert-file=/opt/bitnami/kafka-exporter/certs/kafka.truststore.jks
      --tls.ca-file=/opt/bitnami/kafka-exporter/certs/
      --tls.insecure-skip-tls-verify
      --web.listen-address=:9308
```

```
[root@k8master1 bitnami]# kubectl logs kafka-exporter-7dd5d78887-8r22c -n es
I0329 11:51:01.670657       1 kafka_exporter.go:769] Starting kafka_exporter (version=1.4.2, branch=non-git, revision=non-git)
F0329 11:51:01.671177       1 kafka_exporter.go:865] read /opt/bitnami/kafka-exporter/certs/: is a directory
```
What is the value I should provide in **tls.ca-file** ?

When I tried giving **ca-file as kafka.truststore.jks** below is the error I am getting,

```
[root@k8master1 bitnami]# kubectl logs kafka-exporter-76b77df5f8-bvvkf -n es -f
I0329 12:08:19.600421       1 kafka_exporter.go:769] Starting kafka_exporter (version=1.4.2, branch=non-git, revision=non-git)
F0329 12:08:19.600936       1 kafka_exporter.go:865] tls: failed to find any PEM data in certificate input
```

kindly share your thoughts on the above setup and correct me If I am doing anything wrong.
