### ISSUE TITLE
initdb scripts are not running in Postgres container

### ISSUE THREAD

**Issue by JesalR** [bitnami/charts#9048]
### Name and Version

bitnami/postgres 11.0.4

### What steps will reproduce the bug?

Install the postgres chart with the following values
View DB or logs to see the script was not run

### Are you using any custom parameters or values?

values.yaml

```yaml
postgresql:
  nameOverride: db

  image:
    debug: true

  auth:
    postgresPassword: "docker"
    username: "docker"
    password: "docker"
    database: "gis"

  primary:
    extraVolumes:
      - name: postgres-seed
        persistentVolumeClaim:
          claimName: postgres-seed-pvc

    extraVolumeMounts:
      - mountPath: /docker-entrypoint-initdb.d
        name: postgres-seed

    initdb:
      user: "postgres"
      password: "docker"
      scripts:
        00_init_extensions.sql: |
          create extension if not exists postgis;
          create extension if not exists hstore;

    initContainers:
      - name: seed
        image: busybox
        command: ["sh"]
        args:
          - -c
          - >-
            get-seed-files-ready.sh
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d
            name: postgres-seed
```

alternative script
```yaml
        00_init_extensions.sh: |
          #!/bin/sh
          export PGPASSWORD=$POSTGRES_POSTGRES_PASSWORD
          psql -U postgres -d gis -c "create extension if not exists postgis; create extension if not exists hstore;"
```

template/pvc.yaml
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-seed-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gcp-ssd
```

### What is the expected behavior?

The script is run and the postgis extension is enabled

### What do you see instead?

Debug logs
```
postgresql 18:56:11.07
postgresql 18:56:11.07 Welcome to the Bitnami postgresql container
postgresql 18:56:11.07 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 18:56:11.08 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 18:56:11.08
postgresql 18:56:11.08 DEBUG ==> Configuring libnss_wrapper...
postgresql 18:56:11.10 INFO  ==> ** Starting PostgreSQL setup **
postgresql 18:56:11.13 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 18:56:11.14 INFO  ==> Loading custom pre-init scripts...
postgresql 18:56:11.15 INFO  ==> Initializing PostgreSQL database...
postgresql 18:56:11.15 DEBUG ==> Ensuring expected directories/files exist...
postgresql 18:56:11.18 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 18:56:11.18 INFO  ==> Generating local authentication configuration
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /bitnami/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
syncing data to disk ... ok


Success. You can now start the database server using:

    /opt/bitnami/postgresql/bin/pg_ctl -D /bitnami/postgresql/data -l logfile start

postgresql 18:56:12.74 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2022-02-16 18:56:12.783 GMT [66] LOG:  starting PostgreSQL 14.1 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2022-02-16 18:56:12.784 GMT [66] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-02-16 18:56:12.784 GMT [66] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
2022-02-16 18:56:12.789 GMT [66] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-02-16 18:56:12.795 GMT [67] LOG:  database system was shut down at 2022-02-16 18:56:12 GMT
2022-02-16 18:56:12.800 GMT [66] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE
postgresql 18:56:12.95 INFO  ==> Changing password of postgres
ALTER ROLE
postgresql 18:56:12.98 INFO  ==> Creating user docker
CREATE ROLE
postgresql 18:56:13.00 INFO  ==> Granting access to "docker" to the database "gis"
GRANT
ALTER DATABASE
postgresql 18:56:13.03 INFO  ==> Setting ownership for the 'public' schema database "gis" to "docker"
ALTER SCHEMA
postgresql 18:56:13.06 INFO  ==> Configuring replication parameters
postgresql 18:56:13.10 INFO  ==> Configuring synchronous_replication
postgresql 18:56:13.10 INFO  ==> Configuring fsync
postgresql 18:56:13.16 INFO  ==> Loading custom scripts...
postgresql 18:56:13.16 INFO  ==> Enabling remote connections
postgresql 18:56:13.18 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down....2022-02-16 18:56:13.190 GMT [66] LOG:  received fast shutdown request
2022-02-16 18:56:13.193 GMT [66] LOG:  aborting any active transactions
2022-02-16 18:56:13.195 GMT [66] LOG:  background worker "logical replication launcher" (PID 73) exited with exit code 1
2022-02-16 18:56:13.195 GMT [68] LOG:  shutting down
2022-02-16 18:56:13.213 GMT [66] LOG:  database system is shut down
 done
server stopped

postgresql 18:56:13.29 INFO  ==> ** PostgreSQL setup finished! **
postgresql 18:56:13.32 INFO  ==> ** Starting PostgreSQL **
2022-02-16 18:56:13.346 GMT [1] LOG:  pgaudit extension initialized
2022-02-16 18:56:13.354 GMT [1] LOG:  starting PostgreSQL 14.1 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2022-02-16 18:56:13.354 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-02-16 18:56:13.354 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2022-02-16 18:56:13.359 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-02-16 18:56:13.365 GMT [156] LOG:  database system was shut down at 2022-02-16 18:56:13 GMT
2022-02-16 18:56:13.373 GMT [1] LOG:  database system is ready to accept connections
```

**Comment by carrodher** [comment]
Unfortunately, I'm not able to reproduce the issue by using a custom sh script. I just added it by modifying the default `values.yaml` as follows:

```diff
-   scripts: {}
+   scripts:
+     00_init_extensions.sh: |
+       echo "Hi, I'm a testing script added by @carrodher"
```

Then, deployed the Helm chart with
```console
$ helm install postgresql bitnami/postgresql -f values.yaml
$ kubectl logs -f postgresql-0
...
postgresql 07:22:39.36 INFO  ==> Loading custom scripts...
postgresql 07:22:39.37 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
postgresql 07:22:39.37 INFO  ==> Starting PostgreSQL in background...
Hi, I'm a testing script added by @carrodher
postgresql 07:22:39.40 INFO  ==> Enabling remote connections
postgresql 07:22:39.42 INFO  ==> Stopping PostgreSQL...
```

As you can see the sentence added into the `echo` is present which means the script is being executed. Apart from that, the container logs are showing `Loading custom scripts...` and `Loading user's custom files from /docker-entrypoint-initdb.d ...` coming from the container logic at [_libpostgresql_](https://github.com/bitnami/bitnami-docker-postgresql/blob/80465109b41fbed3b7025f137460921fd62621ea/14/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L690).
In your case, the second sentence is not appearing, taking a look at the [container code](https://github.com/bitnami/bitnami-docker-postgresql/blob/80465109b41fbed3b7025f137460921fd62621ea/14/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L690) it seems the following condition is not meet:
```bash
if [[ -d "$POSTGRESQL_INITSCRIPTS_DIR" ]] && [[ -n $(find "$POSTGRESQL_INITSCRIPTS_DIR/" -type f -regex ".*\.\(sh\|sql\|sql.gz\)") ]] && [[ ! -f "$POSTGRESQL_VOLUME_DIR/.user_scripts_initialized" ]]; then
```

I did the same test using your `.sql` script and everything seems to be working fine:
```diff
image:
-  debug: false
+  debug: true
-   scripts: {}
+   scripts:
+     00_init_extensions.sql: |
+       create extension if not exists postgis;
+       create extension if not exists hstore;
```
```console
$ helm install postgresql3 bitnami/postgresql -f values.yaml
$ kubectl logs -f postgresql3-0
postgresql 07:52:56.64 INFO  ==> Loading custom scripts...
postgresql 07:52:56.65 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
postgresql 07:52:56.65 INFO  ==> Starting PostgreSQL in background...
postgresql 07:52:56.66 DEBUG ==> Executing /docker-entrypoint-initdb.d/..2022_03_07_07_52_44.172004481/00_init_extensions.sql
CREATE EXTENSION
CREATE EXTENSION
```

**Comment by djhoese** [comment]
Just another data point here from an outside observer, this worked for me using version 11.1.3 of the chart:

```yaml
  primary:
    initdb:
      scripts:
        00_init_extensions.sql: |
          CREATE EXTENSION IF NOT EXISTS postgis;
```

**Comment by dswiecki** [comment]
Few tips in case you encounter similar behaviour. 
1. Add configuration below to see debug logs
`
image:
  debug: true
`

2. Ensure that you do not have any previously existing pvc becouse initScripts are executed only during first deployment
3. Then you should see lines
```
postgresql 14:54:51.76 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
postgresql 14:54:51.78 INFO  ==> Starting PostgreSQL in background...
postgresql 14:54:51.87 DEBUG ==> Executing /docker-entrypoint-initdb.d/..2022_05_10_14_54_40.881018254/00_init_extensions.sql
```

4. Your script should be logged here `Executing /docker-entrypoint-initdb.d/..2022_05_10_14_54_40.881018254/00_init_extensions.sql`

**Comment by Deepanshu6dec** [comment]
I'm facing the similar type of issue in bitnami/Postgresql while deploying through helm
Steps Follow 
1. Creating Persistence Volume 
2. Creating Persistence Volume Claimed 
3. Created values.yaml file 
```   initdb:
      user: "CSMSC"
      passsword: "admin"
      scripts:
        init.sql: |
          create schema pub;
          create table pub.test( firstname CHAR(15), lastname CHAR(20));
          insert into pub.test values( 'Ops', 'Dev');
          select * from pub.test;  ```
# But this init.sql is not working at bootstrap 
# Helm Version :  3.9.0
# Helm Chart Version 11.6.15
#Here is my Logs of Postgresql 
```➜  yamls k logs postgresql1-0
postgresql 15:34:57.18 
postgresql 15:34:57.18 Welcome to the Bitnami postgresql container
postgresql 15:34:57.18 Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 15:34:57.18 Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql 15:34:57.19 
postgresql 15:34:57.19 DEBUG ==> Configuring libnss_wrapper...
postgresql 15:34:57.21 INFO  ==> ** Starting PostgreSQL setup **
postgresql 15:34:57.22 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 15:34:57.23 INFO  ==> Loading custom pre-init scripts...
postgresql 15:34:57.24 INFO  ==> Initializing PostgreSQL database...
postgresql 15:34:57.25 DEBUG ==> Ensuring expected directories/files exist...
postgresql 15:34:57.27 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 15:34:57.27 INFO  ==> Generating local authentication configuration
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /bitnami/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok


Success. You can now start the database server using:

    /opt/bitnami/postgresql/bin/pg_ctl -D /bitnami/postgresql/data -l logfile start

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
postgresql 15:34:58.12 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2022-07-12 15:34:58.158 GMT [68] LOG:  starting PostgreSQL 14.4 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-07-12 15:34:58.159 GMT [68] LOG:  listening on IPv6 address "::1", port 5432
2022-07-12 15:34:58.159 GMT [68] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-07-12 15:34:58.162 GMT [68] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-07-12 15:34:58.166 GMT [69] LOG:  database system was shut down at 2022-07-12 15:34:58 GMT
2022-07-12 15:34:58.170 GMT [68] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE
postgresql 15:34:58.31 INFO  ==> Changing password of postgres
ALTER ROLE
postgresql 15:34:58.33 INFO  ==> Creating user CSMSC
CREATE ROLE
postgresql 15:34:58.35 INFO  ==> Granting access to "CSMSC" to the database "CSMSC"
GRANT
ALTER DATABASE
postgresql 15:34:58.38 INFO  ==> Setting ownership for the 'public' schema database "CSMSC" to "CSMSC"
ALTER SCHEMA
postgresql 15:34:58.40 INFO  ==> Configuring replication parameters
postgresql 15:34:58.43 INFO  ==> Configuring synchronous_replication
postgresql 15:34:58.44 INFO  ==> Configuring fsync
postgresql 15:34:58.49 INFO  ==> Loading custom scripts...
postgresql 15:34:58.50 INFO  ==> Enabling remote connections
postgresql 15:34:58.51 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down....2022-07-12 15:34:58.516 GMT [68] LOG:  received fast shutdown request
2022-07-12 15:34:58.521 GMT [68] LOG:  aborting any active transactions
2022-07-12 15:34:58.523 GMT [68] LOG:  background worker "logical replication launcher" (PID 75) exited with exit code 1
2022-07-12 15:34:58.523 GMT [70] LOG:  shutting down
2022-07-12 15:34:58.546 GMT [68] LOG:  database system is shut down
 done
server stopped
postgresql 15:34:58.62 INFO  ==> ** PostgreSQL setup finished! **

postgresql 15:34:58.63 INFO  ==> ** Starting PostgreSQL **
2022-07-12 15:34:58.655 GMT [1] LOG:  pgaudit extension initialized
2022-07-12 15:34:58.662 GMT [1] LOG:  starting PostgreSQL 14.4 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-07-12 15:34:58.662 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-07-12 15:34:58.662 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2022-07-12 15:34:58.665 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-07-12 15:34:58.671 GMT [156] LOG:  database system was shut down at 2022-07-12 15:34:58 GMT
2022-07-12 15:34:58.678 GMT [1] LOG:  database system is ready to accept connections
```
Deploying Status 
```
NAME: postgresql1
LAST DEPLOYED: Tue Jul 12 15:34:55 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: postgresql
CHART VERSION: 11.6.15
APP VERSION: 14.4.0
```

**Comment by djhoese** [comment]
@Deepanshu6dec Can you do a `helm template -f your_custom_values.yaml test bitnami/postgresql` and look at the output for the ConfigMap generated? Specifically this one: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/templates/primary/initialization-configmap.yaml

I'm wondering if your init script isn't getting formatting properly. I suppose you could instead just do `kubectl get configmap/name-of-the-configmap -o yaml` on your system to see what the contents are.

Could you also reformat your comment so the triple backticks are on their own lines? The formatting got a bit messed up and parts are hard to read.

**Comment by NunoSav** [comment]
```yaml
primary:
  persistence:
    enabled: true
    size: 20Gi
  initdb:
    scripts:
      01-init.sql: |
        CREATE DATABASE IF NOT EXISTS "chirpstack-application-server" WITH OWNER postgres;
        CREATE DATABASE IF NOT EXISTS "chirpstack-network-server" WITH OWNER postgres;
        CREATE DATABASE IF NOT EXISTS "edc" WITH OWNER postgres;
        CREATE EXTENSION IF NOT EXISTS pg_trgm;
        CREATE EXTENSION IF NOT EXISTS hstore;
        CREATE IF NOT EXISTS ROLE chirpstack_as_events WITH LOGIN PASSWORD 'edc-chirpstack-telemetry-integration';
        CREATE DATABASE IF NOT EXISTS chirpstack_as_events WITH OWNER chirpstack_as_events;
image:
  repository: postgres
  tag: 14.5
auth:
  postgresPassword: EDC-filling-level-postgres-password
```

**Comment by djhoese** [comment]
In your log it shows:

```
CREATE EXTENSION
CREATE EXTENSION
CREATE DATABASE
CREATE DATABASE
CREATE DATABASE
CREATE ROLE
CREATE DATABASE
```

which besides being in a different order than your script, look like it is running the same commands. Which commands are not being run for you?

**Comment by NunoSav** [comment]
Sorry, i'm playing around to see if i get a clue and i showed you a different version of what was used, but basically i changed the order of the statements. 
For:
```
CREATE EXTENSION
CREATE EXTENSION
CREATE DATABASE
CREATE DATABASE
CREATE DATABASE
CREATE ROLE
CREATE DATABASE
```
The extensions were not created and only 3 out of 4 databases were created.

**Comment by djhoese** [comment]
:man_shrugging: What happens if you put the role creation as the first command?

**Comment by NunoSav** [comment]
I found a way to make it work:
```
  initdb:
    scripts:
      01-init.sql: |
        CREATE DATABASE "chirpstack-application-server" WITH OWNER postgres;
        CREATE DATABASE "chirpstack-network-server" WITH OWNER postgres;
        CREATE DATABASE "edc" WITH OWNER postgres;
        CREATE ROLE chirpstack_as_events WITH LOGIN PASSWORD 'edc-chirpstack-telemetry-integration';
        CREATE DATABASE chirpstack_as_events WITH OWNER chirpstack_as_events;
        CREATE EXTENSION pg_trgm;
        CREATE EXTENSION hstore;
      02_init_extensions.sh: |
        #!/bin/sh
        export PGPASSWORD=$POSTGRES_PASSWORD
        psql -U postgres -d chirpstack-application-server -c "create extension if not exists pg_trgm; create extension if not exists hstore;"
```

Thanks for your help @djhoese

**Comment by moreinhardt** [comment]
I ran into the same problem and enabling

```yaml
image:
  debug: true
```

showed me that these commands are actually run as the user specified with `auth.username` which doesn't have many rights and therefore my command failed.

In my case I wanted to give that user more role attributes.

The workaround from @NunoSav worked when I used the correct password env variable. :slightly_smiling_face: 

```yaml
  initdb:
    scripts:
      custom_user_setup.sh: |
        #!/bin/sh
        export PGPASSWORD=$POSTGRES_POSTGRES_PASSWORD
        psql -U postgres -d custom_db -c "ALTER ROLE custom_user WITH LOGIN REPLICATION;"
```
