### ISSUE TITLE
[Bug] init-chmod-data init container resources rendering

### ISSUE THREAD

**Issue by janlauber** [bitnami/charts#9052]
### Name and Version

bitnami/postgresql 11.0.5

### What steps will reproduce the bug?

1. Deploy the postgresql instance with primary resource requests/limits
2. `init-chmod-data` resource requests/limits won't get rendered correctly

### Are you using any custom parameters or values?

```yaml
primary:
  resources:
    limits:
      cpu: 125m
      memory: 256Mi
    requests:
      cpu: 125m
      memory: 256Mi
```

### What is the expected behavior?

```yaml
# [...]
initContainers:
  - command:
    - /bin/sh
    - -cx
    - |
      echo "current user id: `id`"
      mkdir -p /bitnami/postgresql/data
      chmod 700 /bitnami/postgresql/data
      find /bitnami/postgresql -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | \
        xargs chown -R 1001:1001
      chmod -R 777 /dev/shm
    image: docker.io/bitnami/minideb:buster
    imagePullPolicy: Always
    name: init-chmod-data
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi
    securityContext:
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /bitnami/postgresql
      name: data
    - mountPath: /dev/shm
      name: dshm
# [...]
```

### What do you see instead?

```yaml
# [...]
initContainers:
  - command:
    - /bin/sh
    - -cx
    - |
      echo "current user id: `id`"
      mkdir -p /bitnami/postgresql/data
      chmod 700 /bitnami/postgresql/data
      find /bitnami/postgresql -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | \
        xargs chown -R 1001:1001
      chmod -R 777 /dev/shm
    image: docker.io/bitnami/minideb:buster
    imagePullPolicy: Always
    name: init-chmod-data
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
    securityContext:
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /bitnami/postgresql
      name: data
    - mountPath: /dev/shm
      name: dshm
# [...]
```
