### ISSUE TITLE
Init-container wordpress terminates on chown

### ISSUE THREAD

**Issue by mchobbel** [bitnami/charts#9074]
### Name and Version

bitnami/wordpress-13.0.11

### What steps will reproduce the bug?

In OVH.com public cloud Kubernetes I 

created a pvc like this:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: michiel-wp-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cinder-classic
```
And then run the install with this:
```
 helm install wp-michiel5 bitnami/wordpress -f values.yaml 
```
with below values.yaml

### Are you using any custom parameters or values?

```yaml
persistence:
  existingClaim: michiel-wp-pvc
  
volumePermissions:
  enabled: true

ingress:
  enabled: false

service:
  type: NodePort

mariadb:
  enabled: false
  
wordpressScheme: https

externalDatabase:
  host: xx
  user: xx
  database: xx
  password: xx
  port: 3306
```

### What is the expected behavior?

The wordpress install would complete and a working wordpress pod becomes available.

### What do you see instead?

In the pod details, I see that the init-container has exited on `chown` with exit code 123. 

```yaml
Init Containers:
  volume-permissions:
    Container ID:  containerd://5832981fc897b4040e19ae4ae2a7859fcffb52334790fc5b04f843baa7b76001
    Image:         docker.io/bitnami/bitnami-shell:10-debian-10-r337
    Image ID:      docker.io/bitnami/bitnami-shell@sha256:3b73ef5913dc5a23a4dd2c60d004f656a7cacd257d5e2bd4a0a0c218d242439d
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
    Args:
      -ec
      mkdir -p /bitnami/wordpress
      find /bitnami/wordpress -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | xargs chown -R 1001:1001
      
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    123
      Started:      Fri, 18 Feb 2022 13:52:11 +0100
      Finished:     Fri, 18 Feb 2022 13:52:11 +0100
    Ready:          False
    Restart Count:  5
    Environment:    <none>
    Mounts:
      /bitnami/wordpress from wordpress-data (rw,path="wordpress")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2cf9l (ro)
```

### Additional information

When I start a bash container based on the  docker.io/bitnami/bitnami-shell:10-debian-10-r337 with the same volume mount, it strikes me that the volume-mount is completely empty (i'm not shure if that is expected at this point). 

Now I can replicate the 123 exit code by:
```
root@my-debug-helm:/# find /bitnami/wordpress  -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | xargs chown -R 1001:1001
chown: missing operand after '1001:1001'
Try 'chown --help' for more information.
root@my-debug-helm:/# echo $?
123
```
My analysis is that the find-xargs-chown sequence does not work on an empty dir! 
The error disappears after I put something there.
```
echo hello > /bitnami/wordpress/readme.txt
```
Now, repeating the find-xargs-chown there is no error. Also now I can do the helm install again and it doesn't crash on that thing anymore !
