### ISSUE TITLE
Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock

### ISSUE THREAD

**Issue by denniscallanan** [bitnami/charts#9083]
### Name and Version

bitnami/mysql 8.8.24

### Environment

Helm chart configuration in Devspace, using local K3D cluster

`auth.rootPassword` was only added because of previous error: `'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$MYSQL_ROOT_PASSWORD' to the command`

### Config

```
deployments:
  - name: database
    helm:
      chart:
        repo: https://charts.bitnami.com/bitnami
        name: mysql
      wait: true
      values:
        auth:
          username: root
          password: password
          rootPassword: password
          database: my_database
        volumePermissions:
          enabled: true
```

### Run

```
devspace dev
```

Underneath the Devspace hood:
```
helm upgrade database --namespace devspace --values /var/folders/p9/tcbw9s4s0rgg4fjj4sn5sx6h0000gn/T/944344650 --install mysql --repo https://charts.bitnami.com/bitnami --repository-config='' --wait --kube-context k3d-devspace
```
### Error

```
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  46s   default-scheduler  Successfully assigned devspace/database-mysql-0 to k3d-devspace-server-0
  Normal   Pulled     46s   kubelet            Container image "docker.io/bitnami/bitnami-shell:10-debian-10-r340" already present on machine
  Normal   Created    46s   kubelet            Created container volume-permissions
  Normal   Started    46s   kubelet            Started container volume-permissions
  Normal   Pulled     45s   kubelet            Container image "docker.io/bitnami/mysql:8.0.28-debian-10-r15" already present on machine
  Normal   Created    45s   kubelet            Created container mysql
  Normal   Started    44s   kubelet            Started container mysql
  Warning  Unhealthy  26s   kubelet            Startup probe failed: mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (2)'
Check that mysqld is running and that the socket: '/opt/bitnami/mysql/tmp/mysql.sock' exists!
  Warning  Unhealthy  6s (x2 over 16s)  kubelet  Startup probe failed: mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: YES)'
```

### Are you using any custom parameters or values?

```
auth:
  database: sinatra_ruby_sandbox
  password: password
  rootPassword: password
  username: root
volumePermissions:
  enabled: true
```

### What is the expected behavior?

MySQL is expected to run with near default configuration, as it would in docker-compose.

### What do you see instead?

Startup probe is failing. Can't connect to local MySQL server through socket.
