### ISSUE TITLE
Upgrade Postgresql 11 to 12

### ISSUE THREAD

**Issue by alekseytivonchik** [bitnami/charts#9085]
### Name and Version

bitnami/postgresql-10.12.0

### What steps will reproduce the bug?

Postresql ver - 11.13, bitnami helm chart ver - 10.12.0
Upgrade to version 12.8
Postgresql deployed on k3s with PVC

After all steps from [answer](https://github.com/bitnami/charts/issues/8025#issuecomment-964906018), i couldn't establish remote and local connect to postgresql with error
`postgres user has no password assigned`

Password should be assigne from kubernetes Secret.
Do you have any idia how to resolve this issue?

### Are you using any custom parameters or values?

Values.yaml
```
image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 12.8.0-debian-10-r91

diagnosticMode:
  enabled: true
  command:
    - sleep
  args:
    - infinity

auth:
  enablePostgresUser: true
  postgresPassword: "passwd"

persistence:
  enabled: true
  existingClaim: postgresql

service:
  type: NodePort
  nodePort: "31432"

metrics:
  enabled: true
  service:
    type: NodePort

pgHbaConfiguration: |-
  local   all             all                                     trust
  # IPv4 local connections:
  host    all             all             10.50.0.0/16            md5
```

### What is the expected behavior?

successfull remote and local connection to Postgresql 

### What do you see instead?

postgres user has no password assigned
