### ISSUE TITLE
[bitnami/rabbitmq] Force boot not working 

### ISSUE THREAD

**Issue by Becram** [bitnami/charts#9121]
### Name and Version

bitnami/rabbitmq 8.29.0

### What steps will reproduce the bug?

configured with values:

```yaml
image:
  debug: true
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi
service:
  type: NodePort
persistence:
  enabled: true
  size: 16G
memoryHighWatermark:
  enabled: true
  type: "relative"
  value: 0.7
clustering:
  enabled: true
  forceBoot: true
extraPlugins: ""
replicaCount: 3
```

### What is the expected behavior?

When the pods abruptly killed it should be started with force boot without checking other peers as force boot is enabled  but the force boot is  not happening when the pod starting up.
For the the directory mounted with symlink it fails to track files and cannot restore 

### What do you see instead?

no force booting/restoring of the pod  for directory with symlink
