### ISSUE TITLE
[bitnami/postgresql] Error on startup when running as non-root user.

### ISSUE THREAD

**Issue by hannesknutsson** [bitnami/charts#9127]
### Name and Version

bitnami/postgresql 11.0.6

### What steps will reproduce the bug?

We are deploying the chart as described below in a Minikube cluster (using ArgoCD), but trying to do so without ever using a root user. That meaning not even the init-container may be root. This is because when deploying in our dev/staging/prod environment, running as root is prohibited.

### Are you using any custom parameters or values?

Since we want to never run as root we set the permissions of the directories `/opt/bitnami` and `/bitnami/postgresql` by rebuilding the docker image like this:

Dockerfile:
```Dockerfile
FROM bitnami/postgresql:latest
USER 0
RUN chgrp -R daemon /opt/bitnami
RUN chgrp -R daemon /bitnami/postgresql
USER 1001
```

Here is a boiled down Chart.yaml (nesting bitnami/postgresql in order to store configs in Git in an ArgoCD friendly way):
```yaml
apiVersion: v2
name: vendor-services-postgresql
type: application
version: 11.0.6
appVersion: "14.1.0"

dependencies:
- name: postgresql
  version: "11.0.6"
  repository: "https://charts.bitnami.com/bitnami"
```

As we are using the postgresql as a subchart, everything is indented an extra level.

values.yaml:
```yaml
postgresql:
  global:
    imagePullSecrets:
      - regcred
    postgresql:
      postgresqlPassword: "<some password>"
  image:
    registry: <our private image repository/registry>
    repository: <our internal project name>/postgresql
    tag: latest
  persistence:
    enabled: true
    size: 5Gi
  volumePermissions:
    enabled: false

  securityContext: # These are default values, so should not be needed.
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
```

### What is the expected behavior?

We expect the postgresql server to start up successfully and be ready for clients.

### What do you see instead?

Instead, when starting, the pod dies with the following errors in the logs:

```
[38;5;6mpostgresql [38;5;5m14:43:50.30 [0m
[38;5;6mpostgresql [38;5;5m14:43:50.30 [0m[1mWelcome to the Bitnami postgresql container[0m
[38;5;6mpostgresql [38;5;5m14:43:50.30 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-postgresql[0m
[38;5;6mpostgresql [38;5;5m14:43:50.31 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-postgresql/issues[0m
[38;5;6mpostgresql [38;5;5m14:43:50.31 [0m
[38;5;6mpostgresql [38;5;5m14:43:50.32 [0m[38;5;2mINFO [0m ==> ** Starting PostgreSQL setup **
[38;5;6mpostgresql [38;5;5m14:43:50.34 [0m[38;5;2mINFO [0m ==> Validating settings in POSTGRESQL_* env vars..
[38;5;6mpostgresql [38;5;5m14:43:50.34 [0m[38;5;2mINFO [0m ==> Loading custom pre-init scripts...
[38;5;6mpostgresql [38;5;5m14:43:50.35 [0m[38;5;2mINFO [0m ==> Initializing PostgreSQL database...
[38;5;6mpostgresql [38;5;5m14:43:50.36 [0m[38;5;2mINFO [0m ==> pg_hba.conf file not detected. Generating it...
[38;5;6mpostgresql [38;5;5m14:43:50.36 [0m[38;5;2mINFO [0m ==> Generating local authentication configuration
/opt/bitnami/scripts/libpostgresql.sh: line 222: /opt/bitnami/postgresql/conf/pg_hba.conf: Permission denied
[38;5;6mpostgresql [38;5;5m14:43:50.37 [0m[38;5;2mINFO [0m ==> Deploying PostgreSQL with persisted data...
/opt/bitnami/scripts/libfile.sh: line 39: /opt/bitnami/postgresql/conf/pg_hba.conf: Permission denied
```
