### ISSUE TITLE
[bitnami/minio] Set MINIO_SERVER_URL based on ingress hostname

### ISSUE THREAD

**Issue by jacksgt** [bitnami/charts#9144]
### Name and Version

bitnami/minio 10.1.4

### What is the problem this feature will solve?

Minio has various "smart" redirect where it redirects the user from the API endpoint (e.g. `s3.example.com`) to the Console endpoint (`console.s3.example.com`).

At the moment, this is kind of broken with this chart because the Minio doesn't know about the "external" endpoints, i.e. it only knows it's own IP address and will redirect the user from `s3.example.com` to `192.x.x.x:9001` (the internal Console endpoint, likely not available outside the cluster).

### What is the feature you are proposing to solve the problem?

When the user specifies the Helm values `ingress.hostname` / `apiIngress.hostname`, the environment variables `MINIO_SERVER_URL` and `MINIO_BROWSER_REDIRECT_URL`:

> MINIO_SERVER_URL: The URL hostname the MinIO Console uses for connecting to the MinIO server. This variable is required if specifying TLS certificates which do not contain the IP address of the MinIO Server host as a [Subject Alternative Name](https://tools.ietf.org/html/rfc5280.html#section-4.2.1.6). Specify a hostname covered by one of the TLS certificate SAN entries.

https://docs.min.io/minio/baremetal/reference/minio-server/minio-server.html#envvar.MINIO_SERVER_URL

> MINIO_BROWSER_REDIRECT_URL: Specify the URL the MinIO Console provides as the redirect URL to the configured [external identity manager](https://docs.min.io/minio/baremetal/security/iam-overview.html#minio-authentication-and-identity-management). This variable may be necessary for MinIO deployments behind a reverse proxy, load balancer, or similar technology where the internal hostname or IP structure is not reachable from the external network.

https://docs.min.io/minio/baremetal/reference/minio-server/minio-server.html#envvar.MINIO_BROWSER_REDIRECT_URL

### What alternatives have you considered?

It is possible to set `minio.extraEnvVars` Helm values with the environment variables explained above.

```
minio:
  extraEnvVars:
  - name: MINIO_SERVER_URL
    value: s3.example.com

```
However, I think this should be set automatically for the user.

**Comment by jacksgt** [comment]
If there is consensus that this is the right thing to do, I'm happy to submit a PR for it.

**Comment by jacksgt** [comment]
Minio logs before:
```

API: http://10.42.0.57:9000  http://127.0.0.1:9000     

Console: http://10.42.0.57:9001 http://127.0.0.1:9001   
```

After setting the env vars discussed above:

```
 18:29:43.60 INFO  ==> ** Starting MinIO setup **
minio 18:29:43.64 INFO  ==> Starting MinIO in background...
minio 18:29:53.64 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 18:29:53.84 INFO  ==> Stopping MinIO...
 18:29:55.06 INFO  ==> ** MinIO setup finished! **

minio 18:29:55.09 INFO  ==> ** Starting MinIO **

 You are running an older version of MinIO released 2 months ago 
 Update: Run `mc admin update` 


API: https://s3.example.com

Console: https://console-s3.example.com
```

**Comment by jacksgt** [comment]
It appears that setting the env variable `MINIO_SERVER_URL` actually causes the login via the Minio Console to fail - even though it is not clear to me why this would happen: https://github.com/minio/minio/issues/13992#issuecomment-1001190835

Nevertheless, we could still set the `MINIO_BROWSER_REDIRECT_URL`.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for bringing this. 
  Yes, please sent the PR, we can discuss it there.

**Comment by Tony-The-Developer** [comment]
Hello I am having the same issue where when you go to the ingress site it is redirecting you to the ingress site :9001

**Comment by JonasGoetz01** [comment]
I do have the same problem. When I define the MINIO_SERVER_URL the login fails.

**Comment by WalissonPires** [comment]
I encountered the same problem. What worked for me was defining different subdomains for UI and API. The values I used were: (This configuration also solves other problems unrelated to this topic: written permission, forces generating cert using DNS-01 challenge instead of HTTP-01)

```yaml
volumePermissions:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

resources:
  requests:
    cpu: 100m
    memory: 100Mi

persistence:
  enabled: true
  storageClass: cloudstack-storage
  size: 1Gi

extraEnvVars:
  - name: MINIO_SERVER_URL
    value: https://storage.example.com.br
  - name: MINIO_BROWSER_REDIRECT_URL
    value: https://storage-ui.example.com.br

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: storage-ui.example.com.br
  path: /
  pathType: ImplementationSpecific
  servicePort: minio-console
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-regex: "true"
  tls: false
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraRules: []
  extraTls:
    - hosts: [ "*.example.com.br" ]
      secretName: storage.example.com.br-tls

apiIngress:
  enabled: true
  ingressClassName: "nginx"
  hostname: storage.example.com.br
  path: /
  pathType: ImplementationSpecific
  servicePort: minio-api
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-regex: "true"
  tls: false
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraRules: []
  extraTls:
    - hosts: [ "*.example.com.br" ]
      secretName: storage.example.com.br-tls
```
