### ISSUE TITLE
[bitnami/kafka] topologySpreadConstraints does not render

### ISSUE THREAD

**Issue by JMSwag** [bitnami/charts#9150]
### Name and Version

bitnami/kafka 12.0.0

### What steps will reproduce the bug?

Execute

```console
$ helm template kafka ./bitnami-charts/bitnami/kafka -f values-test.yaml > render.yaml
```

values-test.yaml
```yaml
topologySpreadConstraints:
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule
  labelSelector:
    matchLabels:
      app.kubernetes.io/name: kafka
      app.kubernetes.io/component: kafka
      app.kubernetes.io/managed-by: Helm
```

### Are you using any custom parameters or values?

`-f values-test.yaml`

### What is the expected behavior?

topologySpreadConstraints to be rendered

### What do you see instead?

topologySpreadConstraints is not rendered

### Additional information

Fixed in https://github.com/bitnami/charts/pull/9149, but can't sign off using my real name.
