### ISSUE TITLE
[bitnami/elasticsearch] Ingress is incorrectly rendered when Elasticsearch security (X-Pack) is enabled

### ISSUE THREAD

**Issue by itaytalmi** [bitnami/charts#9159]
### Name and Version

bitnami/elasticsearch 7.17.0

### What steps will reproduce the bug?

When deploying the chart with the below values.yaml file, ingress doesn't work because the ingress resource is rendered incorrectly and the resulting ingress spec points to an incorrect port.

### Are you using any custom parameters or values?

Values.yaml:

```yaml
master:
  ingress:
    enabled: true
    tls: true
    hostname: elasticsearch.example.domain
    extraTls:
      - hosts:
          - elasticsearch.example.domain
        secretName: my-elasticsearch-tls-cert

# X-Pack security parameters
security:
  enabled: true
  # Password for the 'elastic' user
  elasticPassword: "VMware1!"
  tls:
    restEncryption: false
    autoGenerated: true
```

### What is the expected behavior?

When security.enabled=true, ingress should use port name `https` rather than `http`. 

The resulting ingress spec should be:

```yaml
...
spec:
  rules:
  - host: elasticsearch.example.domain
    http:
      paths:
      - backend:
          service:
            name: elasticsearch-master
            port:
              name: https
        path: /
        pathType: ImplementationSpecific
...
```

### What do you see instead?

Currently, the resulting ingress spec is:

```yaml
...
spec:
  rules:
  - host: elasticsearch.example.domain
    http:
      paths:
      - backend:
          service:
            name: elasticsearch-master
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
...
```

### Additional information

The above occurs because when security.enabled=true, the service port name is `https`.

```yaml
apiVersion: v1
kind: Service
...
spec:
...
  ports:
  - name: https
    port: 9200
    protocol: TCP
    targetPort: https
  - name: tcp-transport
    port: 9300
    protocol: TCP
    targetPort: transport
...
```

Your service helm template uses the `elasticsearch.httpPortName` to set http or https for the Kubernetes service:
https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/templates/_helpers.tpl#L356#L362

However, for ingress, it is hard-coded:
https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/templates/ingress.yaml#L29

The same  `elasticsearch.httpPortName` function should be used by the ingress template as well, to prevent such inconsistencies.

As a workaround, I tried to use the `master.ingress.extraHosts` parameter, to point the ingress to the correct port, but apparently this parameter is not used anywhere in your helm templates... Which is a different/additional issue.

I ended up having to create the ingress resource separately for now.
