### ISSUE TITLE
Unable to update the policy: policy `consoleAdmin` already exists

### ISSUE THREAD

**Issue by devent** [bitnami/charts#9191]
### Name and Version

bitnamy/minio:10.1.11

### What steps will reproduce the bug?

1. deploy helm chart on K8s v1.22.5
2. Config:
```
mode: standalone

auth:
  rootUser: "owieru8baic5Ahli"
  rootPassword: "Raer1Oozecael5ee"

provisioning:
  enabled: true
  users:
    - username: erwin567
      password: xxx
      disabled: false
      policies:
        - consoleAdmin
        - diagnostics
  groups:
    - name: erwin
      disabled: false
      members:
        - erwin567
      policies:
        - readwrite
  buckets:
    - name: erwin
      region: eu-europe
      quota:
        type: hard
        size: 10GiB
  config:
    - name: region
      options:
        name: eu-europe
```
3. minio is deployed
4. provision pod is crash:
```
robobee@andrea-node-3:~$ kminio get pods
NAME                          READY   STATUS    RESTARTS     AGE
minio-57956bf5c7-rpdpc        1/1     Running   0            28s
minio-provisioning--1-fftq6   0/1     Error     1 (8s ago)   26s
robobee@andrea-node-3:~$ p=minio-provisioning--1-fftq6
robobee@andrea-node-3:~$ klog kminio $p
Start Minio provisioning
Added `provisioning` successfully.
Added user `erwin567` successfully.
mc: <ERROR> Unable to update the policy: policy `consoleAdmin` already exists.

```

### What do you see instead?

Minio is deployed and the users and groups are provisioned.

### Additional information

I'm new to Minio, so maybe I do something wrong in the config?
