### ISSUE TITLE
Help with node/pod affinity

### ISSUE THREAD

**Issue by andrewhadji-michael** [bitnami/charts#9194]
### Name and Version

bitnami/solr 0.3.3

### What steps will reproduce the bug?

Hi.

Hopefully someone can help me with my issue.

I am using an older version of the bitnami/solr helm chart 0.3.3.

I have been given this code to production so I would rather not upgrade the helm if I can avoid it so I don’t have to do extra work.

Everything is working just fine, however, I notice that when I spin up a cluster of 40 solr replicas around 7 of them complain of this issue: 
```
node(s) had volume node affinity conflict
```
From my googling, it seems that some of the ebs volumes might be in the wrong az to the pods.

What do I have to add to the helm to get the pods and nodes aligned?

I can see the nodes have a label: topology.kubernetes.io/zone=eu-west-2a

However, I have no idea how to label the pods to choose the correct nodes.

I know it is something to do with pods and node affinity but I am brand new to Kubernetes so this is a bit of a challenge.

Any help would be greatly appreciated.

Thanks

### Are you using any custom parameters or values?
```yaml
args: []
authentication:
  adminPassword: ~
  adminUsername: admin
  enabled: true
cloudBootstrap: true
cloudEnabled: true
clusterDomain: cluster.local
collection: my-collection
collectionReplicas: 2
collectionShards: 1
command: []
commonAnnotations: {}
commonLabels: {}
containerPort: 8983
containerSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1001
coreName: my-core
customLivenessProbe: {}
customReadinessProbe: {}
exporter:
  affinity: {}
  args: []
  command: []
  configFile: /opt/bitnami/solr/contrib/prometheus-exporter/conf/solr-exporter-config.xml
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
  customLivenessProbe: {}
  customReadinessProbe: {}
  enabled: false
  extraEnvVars: []
  extraEnvVarsCM: ~
  extraEnvVarsSecret: ~
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  image:
    pullPolicy: IfNotPresent
    registry: my-registery
    repository:solr #bitnami/solr
    tag: 8.11-s3
  initContainers: {}
  livenessProbe:
    enabled: true
    failureThreshold: 15
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 15
  nodeAffinityPreset:
    key: ""
    type: ""
    values: []
  nodeSelector: {}
  podAffinityPreset: hard
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  port: 9983
  readinessProbe:
    enabled: true
    failureThreshold: 15
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 15
    timeoutSeconds: 15
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 974m
      memory: 3Gi
  service:
    annotations: {}
    labels: {}
    loadBalancerSourceRanges: ~
    nodePorts:
      http: ""
      https: ""
    port: 9983
    type: ClusterIP
  sidecars: {}
  threads: 36
  tolerations: []
  updateStrategy:
    rollingUpdate: {}
    type: RollingUpdate
externalZookeeper:
  servers: []
extraDeploy: []
extraEnvVars: []
extraEnvVarsCM: ~
extraEnvVarsSecret: ~
extraVolumeMounts: []
extraVolumes: []
heap: ~
hostAliases: []
image:
  pullPolicy: IfNotPresent
  registry: my-registery
  repository: solr #bitnami/solr
  tag: 8.11-s3 #8.10.1-debian-10-r14
ingress:
  annotations: {}
  apiVersion: ~
  certManager: false
  enabled: false
  existingSecret: ~
  hostname: solr.local
  path: /
  pathType: ImplementationSpecific
  secrets: []
  tls: false
initContainers: []
javaMem: "-Xms8g -Xmx8g -DsocketTimeout=6000 -DconnTimeout=6000 -DdistribUpdateConnTimeout=90000 -DdistribUpdateSoTimeout=90000"
lifecycleHooks: {}
livenessProbe:
  enabled: true
  failureThreshold: 6
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
nodeAffinityPreset:
  key: ""
  type: ""
  values: []
nodeSelector: {}
persistence:
  accessModes:
    - ReadWriteOnce
  annotations: {}
  enabled: true
  mountPath: /bitnami/solr
  size: 20Gi
podAffinityPreset: ""
podAnnotations: {}
podAntiAffinityPreset: soft
podLabels: {}
podManagementPolicy: Parallel
podSecurityContext:
  enabled: true
  fsGroup: 1001
readinessProbe:
  enabled: true
  failureThreshold: 6
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
replicaCount: 40
resources:
  limits:
    cpu: 6
    memory: 16Gi
  requests:
    cpu: 2
    memory: 14Gi
serverDirectory: server
service:
  annotations: {
  }
  labels: {}
  nodePorts:
    http: ""
    https: ""
  port: 8983
  type: ClusterIP
serviceAccount:
  create: false
  name: ~
sidecars: {}
tls:
  autoGenerated: false
  enabled: false
  keystorePassword: ""
  resources:
    limits: {}
    requests: {}
  truststorePassword: ""
tolerations: []
updateStrategy:
  rollingUpdate: {}
  type: RollingUpdate
volumePermissions:
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
  enabled: false
  image:
    pullPolicy: Always
    pullSecrets: []
    registry: my-registery
    repository: shell
    tag: "10"
  resources:
    limits: {}
    requests: {}
zookeeper:
  image:
    pullPolicy: IfNotPresent
    registry: my-registery
    repository: zookeeper
    tag: 3.7.0-debian-10-r27
  enabled: true
  fourlwCommandsWhitelist: "srvr,mntr,conf,ruok"
  persistence:
    enabled: true
  port: 2181
  replicaCount: 7
  service:
    publishNotReadyAddresses: true
  resources:
    limits:
      cpu: 3
      memory: 4Gi
    requests:
      cpu: 1
      memory: 2Gi
```
### What is the expected behavior?

Pods get assigned to nodes with ebsvolumes in the correct availability zone.

### What do you see instead?

7 out of 40 pods complain of: node(s) had volume node affinity conflict
