### ISSUE TITLE
requestRedirectPolicy validation error

### ISSUE THREAD

**Issue by stumueller** [bitnami/charts#9217]
### Name and Version

bitnami\contour 7.3.9

### What steps will reproduce the bug?

We are using the latest bitnami chart for contour - 7.3.9

our httpproxy yaml's are as follows:
redirect.yaml
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: frontend-redirect
spec:
  virtualhost:
    fqdn: reporting.example.co.uk
    tls:
      secretName: frontend-proxy-redirect
  routes:
    - conditions:
        - prefix: /
      requestRedirectPolicy:
        hostname: www.reporting.example.co.uk
      services:
        - name: web
          port: 80
```
proxy.yaml
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: frontend
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: www.reporting.example.co.uk
    tls:
      secretName: frontend-proxy
  routes:
    - timeoutPolicy:
        response: "2m"
      conditions:
      - prefix: /
      services:
        - name: web
          port: 80
    - timeoutPolicy:
        response: "2m"
      conditions:
      - prefix: /matsweb
      services:
        - name: matsweb
          port: 80
```
after applying proxy.yaml when running `kubectl apply -f redirect.yaml`

We get the error:
```
error: error validating "redirect.yaml": error validating data: ValidationError(HTTPProxy.spec.routes[0]): unknown field "requestRedirectPolicy" in io.projectcontour.v1.HTTPProxy.spec.routes; if you choose to ignore these errors, turn validation off with --validate=false
```

### What do you see instead?
```
error: error validating "redirect.yaml": error validating data: ValidationError(HTTPProxy.spec.routes[0]): unknown field "requestRedirectPolicy" in io.projectcontour.v1.HTTPProxy.spec.routes; if you choose to ignore these errors, turn validation off with --validate=false
```
### Additional information

I initially raised this in the projectcontour repo and was advised the following:

> Looks like the helm chart does not have updated CRDs, no requestRedirectPolicy in https://github.com/bitnami/charts/blob/master/bitnami/contour/resources/httpproxies.yaml and last update was 4 months ago. Can you file an issue in that repo?
