### ISSUE TITLE
argocd install ca-bundle using postStart gets access denied

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#9218]
### Name and Version

bitnami/argocd : latest

### What steps will reproduce the bug?

helm install with postStart value

### Are you using any custom parameters or values?

```
controller:
  # lifecycle hoooks, allow a postStart script to update the certificates
  lifecycleHooks:
    postStart:
      exec:
        command: ["/bin/sh", "-c", "update-ca-certificates"]

  #
  extraVolumes:
  - name: certs
    configMap:
      name: ca-certs
      items:
      - key: "ca.crt"
        path: "onprem.crt"

  extraMounts:
  - mountPath: /usr/local/share/ca-certificates
    name: certs
```

### What is the expected behavior?

Working to install a ca-bundle.  My workplace rewrites https, this makes it appear that all certificates are invalid unless the onprem certificate authority is trusted.

I would expect update-ca-certificates to run and update ca-certificates.crt (including the ca-bundle I added as an extra volume).

### What do you see instead?

```
PostStartHookError: command '/bin/sh -c update-ca-certificates' exited with 1: rm: cannot remove 'ca-certificates.crt': Permission denied
```

### Additional information
I have tried to add the cert in the values, and though the cert is added, I'm still getting "x509: certificate signed by unknown authority"
```
config:
  tlsCerts:
    onprem-ca-bundle: |
        -----BEGIN CERTIFICATE-----
```
If permission denied is expected, then how am I to add to ca-certificates.crt ?

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. It seems that the steps you are doing are not compatible with how configmap and secrets work. Note that configmaps and secrets are read-only. Mounting the configmap inside a folder may cause permission issues because of that. You may need to use alternatives like PVCs instead.

**Comment by lknite** [comment]
I modified my strategy to copy the existing /etc/ssl/certs/ca-certificates.crt, add the certs which I wanted to the end of it then mount my ca-certificates.crt like so:
```
  extraVolumes:
  - name: certs
    configMap:
      name: ca-certs
      items:
      - key: "ca.crt"
        path: "ca-certificates.crt"

  extraVolumeMounts:
  - mountPath: /etc/ssl/certs
    name: certs
```
Still getting a "x509: certificate signed by unknown authority" error.

Which pod needs to have my additional certificates?  controller, repoServer, or server?

**Comment by lknite** [comment]
I modified my strategy to copy the existing /etc/ssl/certs/ca-certificates.crt, added the certs which I wanted to the end of it, then mounted my ca-certificates.crt like so:
```
  extraVolumes:
  - name: certs
    configMap:
      name: ca-certs
      items:
      - key: "ca.crt"
        path: "ca-certificates.crt"

  extraVolumeMounts:
  - mountPath: /etc/ssl/certs
    name: certs
```
This successfully replaces the /etc/ssl/certs/ca-certificates.crt with my ca-certificates.crt file.

This strategy has worked.
