### ISSUE TITLE
Odoo helm chart on Openshift

### ISSUE THREAD

**Issue by th3penguinwhisperer** [bitnami/charts#9223]
### Name and Version

bitnami/odoo 20.2.11

### What steps will reproduce the bug?

Deploying in an Openshift environment.

The database comes up properly and Odoo can connect to the database however I get this error:

`rm: cannot remove '/opt/bitnami/odoo/addons': Permission denied
`

This is in the Odoo container. Do I need the volumePermissions? But this should be handled by Openshift, right (why I had to disable the containerSecurityContext.enabled, ...)?
The default runAsUser is 0 in the values.yaml and it only allows integers so I doubt I have to change anything there.

To me the documentation is quite confusing on what to do when using Openshift.

### Are you using any custom parameters or values?

```yaml
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
commonLabels: {}
commonAnnotations: {}
extraDeploy: []

image:
  registry: docker.io
  repository: bitnami/odoo
  tag: 14
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false

odooEmail: user@example.com
odooPassword: ""
loadDemoData: false
customPostInitScripts: {}
smtpHost: ""
smtpPort: ""
smtpUser: ""
smtpPassword: ""
smtpProtocol: ""
existingSecret: ""
smtpExistingSecret: ""
allowEmptyPassword: false
command: []
args: []
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""

replicaCount: 1
updateStrategy:
  type: RollingUpdate
  rollingUpdate: {}
schedulerName: ""
serviceAccount:
  create: true
  name: ""
hostAliases: []
extraVolumes: []
extraVolumeMounts: []
sidecars: []
initContainers: []
podLabels: {}
podAnnotations: {}
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ""
  key: ""
  values: []
affinity: {}
nodeSelector: {}
tolerations: []
resources:
  limits: {}
  requests:
    memory: 512Mi
    cpu: 300m
containerPort: 8069
podSecurityContext:
  enabled: false
  fsGroup: 1001
containerSecurityContext:
  enabled: false
  runAsUser: 1001
livenessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 600
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 30
  periodSecSTER02hoponds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
startupProbe:
  enabled: false
  path: /
  initialDelaySeconds: 300
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
customLivenessProbe: {}
customReadinessProbe: {}
customStartupProbe: {}

service:
  type: LoadBalancer
  port: 80
  nodePort: ""
  clusterIP: ""
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster
  annotations: {}
  extraPorts: []

ingress:
  enabled: false

  selfSigned: false
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: odoo.local
  path: /
  annotations: {}
  tls: false
  extraHosts: []
  extraPaths: []
  extraTls: []
  secrets: []

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  accessMode: ReadWriteOnce
  size: 2Gi
  dataSource: {}
  existingClaim: ""

volumePermissions:
  enabled: false
  resources:
    limits: {}
    requests: {}
  securityContext:
    runAsUser: 0

pdb:
  create: false
  minAvailable: 1
  maxUnavailable: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 11
  targetCPU: 50
  targetMemory: 50

postgresql:
  enabled: true
  postgresqlUsername: "bn_odoo"
  postgresqlPassword: ""
  postgresqlDatabase: bitnami_odoo
  existingSecret: ""

  persistence:
    enabled: true
    existingClaim: ""

    storageClass: ""
    accessMode: ReadWriteOnce
    size: 2Gi

  volumePermissions:
    enabled: false
    securityContext:
      runAsUser: "auto"
  
  securityContext:
    enabled: false
  
  shmVolume:
    chmod:
      enabled: false
  
  containerSecurityContext:
    enabled: false


externalDatabase:
  host: ""
  port: 5432
  user: bn_odoo
  password: ""
  database: bitnami_odoo
  create: true
  postgresqlPostgresUser: "postgres"
  postgresqlPostgresPassword: ""
  existingSecret: ""

networkPolicy:
  enabled: false
  ingress:
    enabled: false
    podSelector: {}
    namespaceSelector: {}
  ingressRules:
    backendOnlyAccessibleByFrontend: false
    customBackendSelector: {}
    accessOnlyFrom:
      enabled: false
      namespaceSelector: {}
      podSelector: {}
    customRules: {}
  egressRules:
    denyConnectionsToExternal: false
    customRules: {}
```

### What is the expected behavior?

n/a

### What do you see instead?

Odoo pod starts but shows this error and is in crashloopbackoff.

`rm: cannot remove '/opt/bitnami/odoo/addons': Permission denied`
