### ISSUE TITLE
[bitnami/nats] Pod CrashLoopBackOff when defining NATS-server configuration

### ISSUE THREAD

**Issue by qtomato3** [bitnami/charts#9234]
### Name and Version

bitnami/nats 7.1.7

### What steps will reproduce the bug?

1. Define NATS-server configuration in values.yaml
```
maxPayload: "2097152" 
```
2. Install NATS helm chart
3. NATS Pod failed to run: "CrashLoopBackOff"
```
nats 20:24:31.19
nats 20:24:31.20 Welcome to the Bitnami nats container
nats 20:24:31.20 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nats
nats 20:24:31.22 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nats/issues
nats 20:24:31.27
nats 20:24:31.28 INFO  ==> ** Starting NATS setup **
nats 20:24:31.50 WARN  ==> A custom configuration file "nats-server.conf" was found or the file is not writable. Configurations based on environment variables will not be applied for this file.
nats 20:24:31.59 INFO  ==> Initializing NATS
nats 20:24:31.68 INFO  ==> Custom configuration files detected, using them
cp: cannot create regular file '/opt/bitnami/nats/conf/nats-server.conf': Permission denied
```

### Are you using any custom parameters or values?
```yaml
  enabled: true
  auth:
    enabled: false
  image:
    registry: [redacted]
    tag: 2.7.3-debian-10-r0
    pullPolicy: "IfNotPresent"
  maxPayload: "2097152" # increased from default 1Mb, https://docs.nats.io/nats-server/configuration
  service:
    annotations: [redacted]
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  podAnnotations: [redacted]
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
```

### What is the expected behavior?

Expected: NATS Pod is Running.

### What do you see instead?

NATS Pod: CrashLoopBackOff

### Additional information

Content of Secret:
```
listen: 0.0.0.0:4222
http: 0.0.0.0:8222

# Authorization for client connections

# Logging options
debug: false
trace: false
logtime: false
# Pid file
pid_file: "/opt/bitnami/nats/tmp/nats-server.pid"

# Some system overrides
max_payload: 2097152

# Clustering definition
cluster {
  listen: 0.0.0.0:6222
  # Authorization for cluster connections
  authorization {
    user: "nats_cluster"
    password: "d1pmZugBnc"
    timeout:  1
  }
  # Routes are actively solicited and connected to from this server.
  # Other servers can connect to us if they supply the correct credentials
  # in their routes definitions from above
  routes = [
    nats://nats_cluster:d1pmZugBnc@[app]-nats:6222
  ]
}
```

Older Helm chart version v6.2.1 runs fine with NATS v2.7.3.

**Comment by fmulero** [comment]
Hi @qtomato3 thanks for sharing the issue with such detailed level, that's great!

The problem is related to the assigned groups. The group 1001 doesn't have permissions over the nats config file. So you have 2 options to sort it out:
* Set `podSecurityContext.runAsGroup` and `podSecurityContext.fsGroup` as here:
```yaml
podSecurityContext:
    enabled: true
    fsGroup: 0
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
```
* Or directly don't set `podSecurityContext.runAsGroup` parameter:
```yaml
podSecurityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
    runAsNonRoot: true
```
