### ISSUE TITLE
Conflicting examples/docs around keycloak.existingSecret database password

### ISSUE THREAD

**Issue by brsolomon-deloitte** [bitnami/charts#9274]
### Name and Version

bitnami/keycloak 6.2.5

### What steps will reproduce the bug?

There seem to be some conflicting documentation / examples around `keycloak.auth. existingSecret` and specifically the use of a key named `password` versus `database-password`.

In https://docs.bitnami.com/kubernetes/apps/keycloak/configuration/manage-passwords/ and `keycloak/values.yaml`, an example is given using `database-password`:

```yaml
existingSecret:
  name: mySecret
  keyMapping:
    admin-password: myPasswordKey
    management-password: myManagementPasswordKey
    database-password: myDatabasePasswordKey
    tls-keystore-password: myTlsKeystorePasswordKey
    tls-truststore-password: myTlsTruststorePasswordKey
```

And yet in `keycloak/templates/secret.yaml`, the Secret key for `.Values.externalDatabase.password` is simply `password`:

https://github.com/bitnami/charts/blob/daeab7a63dae9b6754ad19864bf123a603ad85e5/bitnami/keycloak/templates/secrets.yaml#L28

I can't find any other actual _use_ of `database-password`, leading me to believe it is ignored.

```bash
$ helm pull --repo https://charts.bitnami.com/bitnami --version 6.2.5 --untar keycloak
$ cd keycloak
$ grep -nri 'database-password' .
./values.yaml:104:  ##     database-password: myDatabasePasswordKey
```

-----

Aside from the above, the documentation also does not mention which will take precedence if both `auth. existingSecret` is used (which contains a database password) as well as `postgresql.existingSecret`.

### What do you see instead?

See above
