### ISSUE TITLE
[bitnami/argo-cd] Missing default value with "repoServer:containerPorts:metrics" & Confused the metrics port number between server and repoServer

### ISSUE THREAD

**Issue by iwanchiyou** [bitnami/charts#9278]
### Name and Version

bitnami/argo-cd 3.0.11

### What steps will reproduce the bug?

```shell
helm pull bitnami/argo-cd --version 3.0.11
tar xf argo-cd-3.0.11.tgz
cd argo-cd
helm install  argocd . --set repoServer.metrics.enabled=true
```

### Are you using any custom parameters or values?

```
--set repoServer.metrics.enabled=true
```

### What is the expected behavior?

```yaml
containerPorts:
  repoServer: 8081
  metrics: ""
```
to
```yaml
containerPorts:
  repoServer: 8081
  metrics: 8084
```
&
```yaml
server:
  metrics:
    service:
      port: 8084
```
to
```yaml
server:
  metrics:
    service:
      port: 8083
```

### What do you see instead?

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].ports[1]): missing required field "containerPort" in io.k8s.api.core.v1.ContainerPort
```
