### ISSUE TITLE
[bitnami/discourse] 114 Killed

### ISSUE THREAD

**Issue by aakrem** [bitnami/charts#9281]
### Name and Version

[bitnami/argo-cd] 6.0.1

### What steps will reproduce the bug?

run the helm chart in eks 1.19

### Are you using any custom parameters or values?

```yaml
discourse:
  host: discourse.example.com

  postgresql:
    enabled: false

  externalDatabase:
    host: clustername.rds.amazonaws.com
    port: 5432
    database: databasename

  redis:
    enabled: false

  externalRedis:
    host: clustername.cache.amazonaws.com
    port: 6379

  ingress:
    hostname: discourse.example.com
    enabled: true
    tls: true

  discourse:
    extraEnvVars:
      - name: redis_use_ssl
        value: "true"
```

### What do you see instead?

```
discourse 14:44:47.76 
discourse 14:44:47.76 Welcome to the Bitnami discourse container
discourse 14:44:47.77 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
discourse 14:44:47.77 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
discourse 14:44:47.77 
discourse 14:44:47.77 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse 14:44:47.78 INFO  ==> Trying to connect to the database server
 ?column? 
----------
        1
(1 row)

discourse 14:44:47.80 INFO  ==> Creating database user discourse
DO
discourse 14:44:47.82 INFO  ==> Creating database discourse
discourse 14:44:47.84 DEBUG ==> Providing privileges to username discourse on database discourse
GRANT
ALTER DATABASE
NOTICE:  extension "hstore" already exists, skipping
CREATE EXTENSION
NOTICE:  extension "pg_trgm" already exists, skipping
CREATE EXTENSION
discourse 14:44:47.91 DEBUG ==> Validating settings in DISCOURSE_* environment variables...
discourse 14:44:47.93 INFO  ==> Creating Discourse configuration file
discourse 14:44:47.93 DEBUG ==> Setting hostname to 'removed' in Discourse configuration
discourse 14:44:47.93 DEBUG ==> Setting db_host to 'removed' in Discourse configuration
discourse 14:44:47.94 DEBUG ==> Setting db_port to 'removed' in Discourse configuration
discourse 14:44:47.94 DEBUG ==> Setting db_username to 'removed' in Discourse configuration
discourse 14:44:47.94 DEBUG ==> Setting db_password to 'removed' in Discourse configuration
discourse 14:44:47.94 DEBUG ==> Setting db_name to 'removed' in Discourse configuration
discourse 14:44:47.95 DEBUG ==> Setting redis_host to removed' in Discourse configuration
discourse 14:44:47.95 DEBUG ==> Setting redis_port to 'removed' in Discourse configuration
discourse 14:44:47.95 DEBUG ==> Setting redis_password to 'removed' in Discourse configuration
discourse 14:44:47.96 INFO  ==> Ensuring Discourse directories exist
discourse 14:44:47.96 INFO  ==> Trying to connect to the database server
 ?column? 
----------
        1
(1 row)

discourse 14:44:47.98 INFO  ==> Populating database
/opt/bitnami/scripts/libdiscourse.sh: line 331:   114 Killed                  "${cmd[@]}"
```

### Additional information

- I am using external postgres and external redis with tls
- All credentials are passed correctly
