### ISSUE TITLE
AWS ExternalSecret

### ISSUE THREAD

**Issue by camilo-alice** [bitnami/charts#9283]
### Name and Version

bitnani/wordpress 13.0.13

### What is the problem this feature will solve?

Hi folks! I have deployed the WordPress using bitnani helm chart. I intend to use external secrets from aws secretManager . I have tried to add this code block at the end of values.yaml, but it does not work:
```yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: wordpress-blog-db
spec:
  backendType: secretsManager
  region: us-east-1
  dataFrom:
    - staging/wordpress-blog/wordpress-blog
```

### What is the feature you are proposing to solve the problem?

Could you improve the helm chart to use external secrets?

### What alternatives have you considered?

Create a custom helm chart.

**Comment by carrodher** [comment]
Secrets are passed by using the `existingSecret` parameter see https://github.com/bitnami/charts/tree/master/bitnami/wordpress#wordpress-configuration-parameters. This is done by modifying the `values.yaml` or using `--set`, see the [values.yaml](https://github.com/bitnami/charts/blob/4961e12e11d29353595e908919f383d75b756714/bitnami/wordpress/values.yaml#L105) for more info:

```yaml
## @param existingSecret Name of existing secret containing WordPress credentials
## NOTE: Must contain key `wordpress-password`
## NOTE: When it's set, the `wordpressPassword` parameter is ignored
##
existingSecret: ""
```

The secret should exist previously in the cluster, in the above-mentioned parameter, you need to indicate the name. 

Please note this is not an issue related to the Bitnami WordPress Helm chart but about how the application or environment is being used/configured. For information regarding the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the technology, in this case about k8s or helm itself.

**Comment by camilo-alice** [comment]
Thanks @carrodher . What I was looking for is the parameter extraDeploy:

```
        extraDeploy:
          - apiVersion: kubernetes-client.io/v1
            kind: ExternalSecret
            metadata:
              name: wordpress-blog-db
            spec:
              backendType: secretsManager
              region: us-east-1
              dataFrom:
                - staging/wordpress-blog/wordpress-blog
```
With this code block the ArgoCD was able to retrieve the secrets from AWS.
