### ISSUE TITLE
[bitnami/keycloak] Upgrade from 6.2.5 to 7.0.0 leads to postgres crashloopBackoff

### ISSUE THREAD

**Issue by AlexisDucastel** [bitnami/charts#9288]
### Name and Version

bitnami/keycloak 7.0.0

### What steps will reproduce the bug?

We have a keycloak that was running with chart 6.2.5, we tried to upgrade to 7.0.0

By digging information on 7.0.0 commit diff and bitnami/postgres documentation, we achieved to proceed to upgrade on helm side. For this we deleted postgresql statefulset and postgresql secret according to Postgresql chart upgrade path from v10 to v11 (cf https://docs.bitnami.com/kubernetes/infrastructure/postgresql/administration/upgrade/#upgrading-instructions), and set values in keycloak release like following : 
```
...
postgresql:
  auth:
    password: <value_from_secret["keycloak-postgresql"].data.postgresql-password>
    postgresPassword: <value_from_secret["keycloak-postgresql"]:postgresql-postgres-password>
  # we have to also let old value as the chart will complain if we do remove it before upgrade
  postgresqlPassword: <value_from_secret["keycloak-postgresql"]:postgresql-password>
...
```

Right now Helm is not throwing errors anymore, but Postgresql statefulset is in crashloopbackoff.
Here is the log of the postgres container : 
```
postgresql 23:29:44.97 INFO ==> ** Starting PostgreSQL **
2022-03-03 23:29:44.982 GMT [1] FATAL: database files are incompatible with server
2022-03-03 23:29:44.982 GMT [1] DETAIL: The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 14.2.
```

### Are you using any custom parameters or values?

```
...
postgresql:
  auth:
    password: <value_from_secret["keycloak-postgresql"].data.postgresql-password>
    postgresPassword: <value_from_secret["keycloak-postgresql"]:postgresql-postgres-password>
  # we have to also let old value as the chart will complain if we do remove it before upgrade
  postgresqlPassword: <value_from_secret["keycloak-postgresql"]:postgresql-password>
...
```

### What is the expected behavior?

We would expect postgresql to upgrade from previous chart version to the new one successfully

### What do you see instead?

Postgresql subchart is deploying a postgresql version that seems to be not compatible with previous postgresql data files

### Additional information

Just for a bit of context : We are using keycloak on a Rancher RKE2 kubernetes cluster v1.22. Persistence is enabled and Postgres PVC storage backend is a Rook Ceph RBD.
