### ISSUE TITLE
[bitnami/argo-cd] dex livenessProbe & readinessProbe check failed caused by some TLS issues

### ISSUE THREAD

**Issue by iwanchiyou** [bitnami/charts#9291]
### Name and Version

bitnami/argo-cd 3.0.11

### What steps will reproduce the bug?

```shell
helm pull bitnami/argo-cd --version 3.0.11
tar xf argo-cd-3.0.11.tgz
cd argo-cd
helm install argocd . --set dex.enabled=true
````

### Are you using any custom parameters or values?

```shell
--set dex.enabled=true
```

### What is the expected behavior?

```yaml
dex:
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true
```
to

```yaml
dex:
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
```

or
add TLS support

### What do you see instead?

Liveiness probe failed: HTTP probe failed with statuscode: 404
Readiness probe failed: HTTP probe failed with statuscode: 404

### Additional information

https://github.com/dexidp/dex/pull/1653
