### ISSUE TITLE
[bitnami/argo-cd] argocd application controller dose not support HA

### ISSUE THREAD

**Issue by iwanchiyou** [bitnami/charts#9295]
### Name and Version

bitnami/argo-cd 3.0.11

### What is the problem this feature will solve?

Support HA variable "ARGOCD_CONTROLLER_REPLICAS"

### What is the feature you are proposing to solve the problem?

When setting to the config below, the controller will not be started. 
```yaml
controller:
  replicaCount: 2
  extraEnvVars:
    - name: "ARGOCD_CONTROLLER_REPLICAS"
      value: "2"
```
According to the [official doc](https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/), HA function should be configured as **StatefulSet** type.
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: argocd-application-controller
        env:
        - name: ARGOCD_CONTROLLER_REPLICAS
          value: "2"
```

### What alternatives have you considered?

Should we add a switch to select **Deployment** or **StatefulSet**. Or just add some notes or comments for this HA function not supported yet.
