### ISSUE TITLE
Instructions do not work to recover a galera cluster

### ISSUE THREAD

**Issue by withinboredom** [bitnami/charts#9307]
### Name and Version

bitnami/mariadb-galera 7.1.0

### What steps will reproduce the bug?

Create a new cluster using the following configuration:

```yaml
rootUser:
  password: password
db:
  user: user
  password: password
  name: db
galera:
  mariabackup:
    password: password
persistence:
  size: 25Gi
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: prometheus
```

Quickly delete all pods to simulate a power failure or other catastrophic failure.

Follow the instructions to force bootstrap the cluster after determining the highest `seqno`.

See the following error:

```
Error: UPGRADE FAILED: cannot patch "mysql-mariadb-galera" with kind StatefulSet: StatefulSet.apps "mysql-mariadb-galera" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy' and 'minReadySeconds' are forbidden
```

Possibly related to #8721 

### Are you using any custom parameters or values?

See above

### What is the expected behavior?

Cluster should be able to recover from failures

### What do you see instead?

A cluster that cannot recover from a failure.
