### ISSUE TITLE
Error syncing to GCP: error running backend syncing routine: error ensuring health check: googleapi: Error 400: Invalid value for field 'resource.timeoutSec': '3'. TimeoutSec should be less than checkIntervalSec., invalid

### ISSUE THREAD

**Issue by simplenotezy** [bitnami/charts#9313]
### Name and Version

bitnami/node 17.0.4

### What steps will reproduce the bug?

1. Installing the helm chart
2. Enabling ingress

### Are you using any custom parameters or values?

My values:

```
fullnameOverride: nestjs
replicaCount: 1
applicationPort: 3000
ingress:
  enabled: true
  hostname: k8s.domain.com
  path: / # or perhaps /*
  tls: true
  annotations:
    

livenessProbe:
  enabled: true
  path: '/health'
  initialDelaySeconds: 10
  periodSeconds: 2
readinessProbe:
  enabled: true
  path: '/health'
  initialDelaySeconds: 10
  periodSeconds: 2
mongodb:
  enabled: false
getAppFromExternalRepository: false
command: false
```

### What do you see instead?

`Error syncing to GCP: error running backend syncing routine: error ensuring health check: googleapi: Error 400: Invalid value for field 'resource.timeoutSec': '3'. TimeoutSec should be less than checkIntervalSec., invalid`
<img width="1688" alt="image" src="https://user-images.githubusercontent.com/3786627/157027371-b32d83c6-d2d5-4339-a6dc-e28944426503.png">

### Additional information

Not sure if this is related to GKE or this Chart, however, it is this chart that have created the ingress.

If I go to Network Services -> Load Balancing I don't see any load balancer. Not sure if this is related or not.

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/3786627/157027895-b27a35e7-64fc-42ea-9b79-d82864a6b8a3.png">
