### ISSUE TITLE
moodle database password not detected

### ISSUE THREAD

**Issue by fle108** [bitnami/charts#9324]
### Name and Version

bitnami/moodle

### What steps will reproduce the bug?

Environment: AKS
Kubernetes Version: 1.21.9
chart version: latest
mariadb enabled: false
externaldb: yes

when installing moodle with helm using env_secrets.yaml and values.yaml files, if the parameter `allowEmptyPassword` is set to false even if a password is set up , the container crash with error :
`The MOODLE_DATABASE_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow a blank password`

### Are you using any custom parameters or values?

i'm using values.yaml and env_secrets.yaml to parse secrets that i applied to my namespace as described in this article [ververica-zendesk](https://ververica.zendesk.com/hc/en-us/articles/360015021359-How-to-secure-passwords-secrets-in-values-yaml-with-Kubernetes-secrets)

```sh
helm install moodle -f values.yaml -f env_secrets.yaml bitnami/moodle
```

```yaml
# file: env_secret.yaml
# secrets environment file
env:
# moodle app user (admin)
- name: moodleUsername
  valueFrom:
    secretKeyRef:
      name: moodle-secret
      key: app_user
# moodle app user (admin) password
- name: moodlePassword
  valueFrom:
    secretKeyRef:
      name: moodle-secret
      key: app_password
# database user
- name: externalDatabase.user
  valueFrom:
    secretKeyRef:
      name: moodle-secret
      key: db_user
# database password
- name: externalDatabase.password
  valueFrom:
    secretKeyRef:
      name: moodle-secret
      key: db_password
# database name
- name: externalDatabase.database
  valueFrom:
    secretKeyRef:
      name: moodle-secret
      key: db_name
```

### What is the expected behavior?

every password or username values are injected where they are attended to be except for the moodle_database_password that returns the error when blank password are forbidden.
mariadb.enabled is at `false` so the template should detect it the externalDatabase.password.

### What do you see instead?

moodle 15:51:15.80 ERROR ==> The MOODLE_DATABASE_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow a blank password. This is only recommended for development environments.

### Additional information

another parameter is not accepted as well, it's  `moodle_database_type`.
when i set it up to `mysqli` in values.yaml 
```yaml
externalDatabase:
  ## @param externalDatabase.type Type of the existing database
  ##
  type: mysqli
  ## @param externalDatabase.host Host of the existing database
  ##
  host: "nameofmy.wonderfull.host.com"
  ## @param externalDatabase.port Port of the existing database
  ##
  port: 3306
  ## @param externalDatabase.user Existing username in the external db
  ##
  user:
  ## @param externalDatabase.password Password for the above username
  ##
  password:
  ## @param externalDatabase.database Name of the existing database
  ##
  database:
  ## @param externalDatabase.existingSecret Name of an existing secret resource containing the DB password
  ##
  existingSecret: ""
```
i get the error 
```log
moodle 15:51:15.80 ERROR ==> The allowed values for MOODLE_DATABASE_TYPE are: mysqli mariadb pgsql
```
actual workardound is to force this parameter in `extraEnvVars` like this in values.yaml:
```yaml
extraEnvVars:
  - name: MOODLE_DATABASE_TYPE
    value: mysqli
```
