### ISSUE TITLE
[Harbor] The trivy tag is not working

### ISSUE THREAD

**Issue by ajchiarello** [bitnami/charts#9325]
### Name and Version

bitnami/harbor 12.0.0

### What steps will reproduce the bug?

When setting the following values, the chart deploys trivy without any tag:
```yaml
trivy:
  image:
    registry: public.ecr.aws
    repository: aquasecurity/harbor-scanner-trivy
    tag: 0.25.0
```

### What is the expected behavior?

That you can set the trivy tag and it will be included in the statefulset

### What do you see instead?

No tag is included in the statefulset

**Comment by carrodher** [comment]
I'm not able to reproduce the issue, applying the following change into the default _values.yaml_
```diff
  image:
-   registry: docker.io
-   repository: bitnami/harbor-adapter-trivy
-   tag: 2.4.1-debian-10-r75
+   registry: public.ecr.aws
+   repository: aquasecurity/harbor-scanner-trivy
+   tag: 0.25.0
```
everything seems to be rendered properly:
`helm template hrb . -f values.yaml -s templates/trivy/trivy-sts.yaml`
```yaml
# Source: harbor/templates/trivy/trivy-sts.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hrb-harbor-trivy
  namespace: "default"
  labels:
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-12.0.0
    app.kubernetes.io/instance: hrb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: trivy
spec:
  replicas: 1
  serviceName: hrb-harbor-trivy
  updateStrategy:
    rollingUpdate: {}
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: harbor
      app.kubernetes.io/instance: hrb
      app.kubernetes.io/component: trivy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: harbor
        helm.sh/chart: harbor-12.0.0
        app.kubernetes.io/instance: hrb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: trivy
      annotations:
        checksum/configmap-env: 0e5041ef078a62e901fd132149ccfe8239b6de68d16f7e8998244462032def27
        checksum/secret-env: 20fc35d639a6910990950f0c267f3047678883c76fd635aef6a78c775a71143c
    spec:

      affinity:
        podAffinity:

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: harbor
                    app.kubernetes.io/instance: hrb
                    app.kubernetes.io/component: trivy
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:

      securityContext:
        fsGroup: 1001
      automountServiceAccountToken: false
      initContainers:
      containers:
        - name: trivy
          image: public.ecr.aws/aquasecurity/harbor-scanner-trivy:0.25.0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
          envFrom:
            - configMapRef:
                name: hrb-harbor-trivy-envvars
            - secretRef:
                name: hrb-harbor-trivy-envvars
          ports:
            - name: api-server
              containerPort: 8080
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              scheme: HTTP
              path: /probe/healthy
              port: api-server
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              scheme: HTTP
              path: /probe/ready
              port: api-server
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /bitnami/harbor-adapter-trivy/.cache
              readOnly: false
      volumes:
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/name: harbor
          app.kubernetes.io/instance: hrb
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
```
Paying attention to the trivy container section, we can see what is the image used: `image: public.ecr.aws/aquasecurity/harbor-scanner-trivy:0.25.0`
