### ISSUE TITLE
[bitnami/discourse] Redis :: TimeoutError : Connection timed out

### ISSUE THREAD

**Issue by aakrem** [bitnami/charts#9342]
### Name and Version

bitnami/discourse 2.7.13-debian-10-r26 

### What steps will reproduce the bug?

run the helm chart in eks 1.19

### Are you using any custom parameters or values?

```yaml
discourse:
  host: discourse.example.com

  postgresql:
    enabled: false

  externalDatabase:
    host: clustername.rds.amazonaws.com
    port: 5432
    database: databasename

  redis:
    enabled: false

  externalRedis:
    host: clustername.cache.amazonaws.com
    port: 6379

  ingress:
    hostname: discourse.example.com
    enabled: true
    tls: true

  discourse:
    extraEnvVars:
      - name: redis_use_ssl
        value: "true"
```
also tried the same values above with different discourse env vars definition like:
```yaml

  discourse:
    extraEnvVars:
      - name: DISCOURSE_REDIS_USE_SSL
        value: "true"
      - name: DISCOURSE_DB_TIMEOUT
        value: "200"

```

### What is the expected behavior?

no connection timeout with redis

### What do you see instead?

```log
NOTICE:  extension "pg_trgm" already exists, skipping
CREATE EXTENSION
discourse 14:44:47.91 DEBUG ==> Validating settings in DISCOURSE_* environment variables...
discourse 14:44:47.93 INFO  ==> Creating Discourse configuration file
discourse 14:44:47.93 DEBUG ==> Setting hostname to 'removed' in Discourse configuration
discourse 14:44:47.93 DEBUG ==> Setting db_host to 'removed' in Discourse configuration
discourse 14:44:47.94 DEBUG ==> Setting db_port to 'removed' in Discourse configuration
discourse 14:44:47.94 DEBUG ==> Setting db_username to 'removed' in Discourse configuration
discourse 14:44:47.94 DEBUG ==> Setting db_password to 'removed' in Discourse configuration
discourse 14:44:47.94 DEBUG ==> Setting db_name to 'removed' in Discourse configuration
discourse 14:44:47.95 DEBUG ==> Setting redis_host to removed' in Discourse configuration
discourse 14:44:47.95 DEBUG ==> Setting redis_port to 'removed' in Discourse configuration
discourse 14:44:47.95 DEBUG ==> Setting redis_password to 'removed' in Discourse configuration
discourse 14:44:47.96 INFO  ==> Ensuring Discourse directories exist
discourse 14:44:47.96 INFO  ==> Trying to connect to the database server
 ?column? 
----------
        1
(1 row)

discourse 16:12:11.96 INFO  ==> Populating database
rake aborted!
Redis::TimeoutError: Connection timed out
```

Additional information
I am using external postgres and external redis with tls
All credentials are passed correctly
