### ISSUE TITLE
[bitnami/mysql] global.storageClass, primary.persistence.storageClass and secondary.persistence.storageClass are ignored

### ISSUE THREAD

**Issue by protoman92** [bitnami/charts#9361]
### Name and Version

bitnami/mysql 8.8.26

### What steps will reproduce the bug?

1. Install MySQL with bitnami/mysql helm chart.
2. Set the values for `global.storageClass`, `primary.persistence.storageClass` and `secondary.persistence.storageClass` to any value.
3. The specified storage class values are ignored.

### Are you using any custom parameters or values?

- global.storageClass
- primary.persistence.storageClass
- secondary.persistence.storageClass

### What is the expected behavior?

The provided storage class should be used for the persistentvolumeclaims.

### What do you see instead?

The provided storage class is ignored for the persistentvolumeclaims.

### Additional information

I read the implementation of bitnami/mysql charts, and the storageClass values do not seem to be used anywhere. Perhaps this is a bug?

**Comment by migruiz4** [comment]
Hi @protoman92,

Could you please give more information about your issue? I haven't been able to reproduce it:

```
$ helm install test bitnami/mysql --set architecture=replication --set global.storageClass=my-class --dry-run
...
# Source: mysql/templates/primary/statefulset.yaml
...
  volumeClaimTemplates:
    - metadata:
        name: data
        labels: 
          app.kubernetes.io/name: mysql
          app.kubernetes.io/instance: test
          app.kubernetes.io/component: primary
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
        storageClassName: my-class
---
# Source: mysql/templates/secondary/statefulset.yaml
...
  volumeClaimTemplates:
    - metadata:
        name: data
        labels: 
          app.kubernetes.io/name: mysql
          app.kubernetes.io/instance: test
          app.kubernetes.io/component: secondary
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
        storageClassName: my-class

```
```yaml
$ helm ins tall test bitnami/mysql --set primary.persistence.storageClass=class1 --set secondary.persistence.storageClass=class2 --set architecture=replication --dry-run
...
# Source: mysql/templates/primary/statefulset.yaml
...
  volumeClaimTemplates:
    - metadata:
        name: data
        labels: 
          app.kubernetes.io/name: mysql
          app.kubernetes.io/instance: test
          app.kubernetes.io/component: primary
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
        storageClassName: class1
---
# Source: mysql/templates/secondary/statefulset.yaml
...
  volumeClaimTemplates:
    - metadata:
        name: data
        labels: 
          app.kubernetes.io/name: mysql
          app.kubernetes.io/instance: test
          app.kubernetes.io/component: secondary
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
        storageClassName: class2
```

 

> I read the implementation of bitnami/mysql charts, and the storageClass values do not seem to be used anywhere. Perhaps this is a bug?

The values are used by the common helper "common.storage.class". Check these references:
https://github.com/bitnami/charts/blob/c4beca4305ecc636cac2cae50441380cdf3afcf1/bitnami/mysql/templates/primary/statefulset.yaml#L364
https://github.com/bitnami/charts/blob/c4beca4305ecc636cac2cae50441380cdf3afcf1/bitnami/mysql/templates/secondary/statefulset.yaml#L333
