### ISSUE TITLE
[bitnami/zookeeper] init-certs fails in hardened environment (readOnlyRootFilesystem)

### ISSUE THREAD

**Issue by tbnguyen1407** [bitnami/charts#9367]
### Name and Version

bitnami/zookeeper 8.1.1

### What steps will reproduce the bug?

1. Deploy custom values.override.yaml

### Are you using any custom parameters or values?

```yaml
~ values.override.yaml ~
containerSecurityContext:
  readOnlyRootFilesystem: true

tls:
  client:
    enabled: true
    autoGenerated: true
    existingSecret: zookeeper-tls-secret
    passwordsSecretName: zookeeper-tls-password-secret
```

### What is the expected behavior?

Successful pod start

### What do you see instead?

Failure in init-certs initContainer:

```
pkcs12: Can't open "/tmp/keystore.p12" for writing, Read-only file system
```

### Additional information

Adding an emptyDir volume and mount it to init-certs at /tmp to ensure the folder is writable in hardened environment
