### ISSUE TITLE
[keycloak] included postgres does not respect postgresql.persistence.existingClaim

### ISSUE THREAD

**Issue by ahgraber** [bitnami/charts#9373]
### Name and Version

bitnami/keycloak 7.1.0

### What steps will reproduce the bug?

I have the following settings in my keycloak.values:

```yaml
    postgresql:
      enabled: true
      auth:
        databasae: <redacted>
        username: <redacted>
        password: <redacted>
      persistence:
        enabled: true
        existingClaim: keycloak-db
```

However, the chart does not seem to respect persistence.existingClaim; an additional PV `data-keycloak-postgresql-0` is created and mounted to the `keycloak-postgresql-0` pod instead of the intended `keycloak-db` claim specified.

### Are you using any custom parameters or values?

see above

### What is the expected behavior?

Keycloak/postgress will use the specified existing claim

### What do you see instead?

 an additional PV `data-keycloak-postgresql-0` is created and mounted to the `keycloak-postgresql-0` pod instead of the intended `keycloak-db` claim specified.
