### ISSUE TITLE
Enabling statsd metrics on Airflow Hem Chart

### ISSUE THREAD

**Issue by jayaswalayush** [bitnami/charts#9385]
### Name and Version

bitnami/airflow 12.0.10

### What steps will reproduce the bug?

Install Bitnami Airflow Helm Chart by enabling the metrics and service monitor

### Are you using any custom parameters or values?
```yaml
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  extraEnvVars:
  - name: AIRFLOW__METRICS__STATSD_ON
    value: "True"
  - name: AIRFLOW__METRICS__STATSD_ALLOW_LIST
    value: scheduler,executor,dagrun
```
### What is the expected behavior?

```
HELP airflow_collect_dags Metric autogenerated by statsd_exporter.
TYPE airflow_collect_dags gauge
HELP airflow_dag_loading_duration_example_bash_operator Metric autogenerated by statsd_exporter.
TYPE airflow_dag_loading_duration_example_bash_operator summary
```
### What do you see instead?

```
HELP airflow_dag_active Is the DAG active?
TYPE airflow_dag_active gauge
airflow_dag_active{dag="bash_example"} 1
airflow_dag_active{dag="create_database_1_10"} 1
airflow_dag_active{dag="create_database_parameterized"} 1
```
### Additional information

Ideally metrics should be seen on the Grafana dashboard as per the link : https://www.redhat.com/en/blog/monitoring-apache-airflow-using-prometheus

But for me there is no data in Grafana :

![image](https://user-images.githubusercontent.com/59866888/157866445-44c0c0dd-2832-4ecd-8b42-69f464c7bcec.png)
