### ISSUE TITLE
[bitnami/thanos] No service discovery  with Helm chart .. just ruler

### ISSUE THREAD

**Issue by linuxmail** [bitnami/charts#9388]
### Name and Version

bitnami/thanos 10.0.0 (0.25.0)

### What steps will reproduce the bug?

```
wget https://raw.githubusercontent.com/bitnami/charts/master/bitnami/thanos/values.yaml
< change stuff >
helm install -f values.yaml  --namespace monitoring thanos bitnami/thanos

$ kubectl get svc --namespace monitoring  
NAME                                 TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
alertmanager-operated                ClusterIP      None            <none>        9093/TCP,9094/TCP,9094/UDP   46h
kube-prometheus-alertmanager         ClusterIP      10.233.31.43    <none>        9093/TCP                     46h
kube-prometheus-kube-state-metrics   ClusterIP      10.233.36.177   <none>        8080/TCP                     46h
kube-prometheus-node-exporter        ClusterIP      10.233.23.140   <none>        9100/TCP                     46h
kube-prometheus-operator             ClusterIP      10.233.25.28    <none>        8080/TCP                     46h
kube-prometheus-prometheus           ClusterIP      10.233.56.104   <none>        9090/TCP                     46h
kube-prometheus-prometheus-thanos    ClusterIP      None            <none>        10901/TCP                    46h
prometheus-operated                  ClusterIP      None            <none>        9090/TCP                     46h
thanos-bucketweb                     ClusterIP      10.233.60.143   <none>        8080/TCP                     46h
thanos-compactor                     ClusterIP      10.233.42.128   <none>        9090/TCP                     46h
thanos-query                         ClusterIP      10.233.60.255   <none>        9090/TCP,10901/TCP           46h
thanos-query-frontend                ClusterIP      10.233.6.68     <none>        9090/TCP                     46h
thanos-ruler                         ClusterIP      10.233.52.220   <none>        9090/TCP,10901/TCP           46h
thanos-storegateway                  ClusterIP      10.233.53.117   <none>        9090/TCP,10901/TCP           46h

$ kubectl get pods --namespace monitoring  
NAME                                                  READY   STATUS    RESTARTS   AGE
alertmanager-kube-prometheus-alertmanager-0           2/2     Running   0          46h
grafana-7d47c99c7-n9l8g                               1/1     Running   0          27h
kube-prometheus-kube-state-metrics-59f658985b-fgndm   1/1     Running   0          46h
kube-prometheus-node-exporter-7rtp5                   1/1     Running   0          46h
kube-prometheus-node-exporter-g5fwq                   1/1     Running   0          46h
kube-prometheus-node-exporter-xc8k7                   1/1     Running   0          46h
kube-prometheus-operator-79786f5686-fbdxk             1/1     Running   0          46h
prometheus-kube-prometheus-prometheus-0               3/3     Running   0          24h
thanos-bucketweb-7977c587b6-jt9wm                     1/1     Running   0          125m
thanos-compactor-78b68f8dbc-pd66t                     1/1     Running   0          125m
thanos-query-849b455b99-dx8d9                         1/1     Running   0          68m
thanos-query-frontend-7cbd69f857-hh7bx                1/1     Running   0          125m
thanos-ruler-0                                        1/1     Running   0          125m
thanos-storegateway-0                                 1/1     Running   0          125m
```

### Are you using any custom parameters or values?

```yaml
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: "direct-csi-min-io"

kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
commonLabels: {}
commonAnnotations: {}
clusterDomain: cluster.local
extraDeploy: []


image:
  registry: docker.io
  repository: bitnami/thanos
  tag: 0.25.1-scratch-r0
  pullPolicy: IfNotPresent
  pullSecrets: []
objstoreConfig: |-
  type: s3
  config:
    bucket: prometheus-long-term
    endpoint: minio.minio.svc.cluster.local:9000
    access_key: thanos
    secret_key: s3cr3t
    insecure: true
indexCacheConfig: ""
bucketCacheConfig: ""
existingObjstoreSecret: ""
existingObjstoreSecretItems: []
existingServiceAccount: ""

query:
  enabled: true
  dnsDiscovery:
    sidecarsService: prometheus-operator-prometheus-thanos
    sidecarsNamespace: monitoring
    enabled: true
  logLevel: info
  logFormat: logfmt
  replicaLabel: [replica]
  dnsDiscovery:
    enabled: true
    sidecarsService: ""
    sidecarsNamespace: ""
  sdConfig: ""
  existingSDConfigmap: ""
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraFlags: []
  command: []
  args: []
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
  resources:
    limits: {}
    requests: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 30
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 30
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6
  startupProbe:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 15
    successThreshold: 1
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  initContainers: []
  sidecars: []
  extraVolumes: []
  extraVolumeMounts: []
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  podLabels: {}
  podAnnotations: {}
  hostAliases: []
  lifecycleHooks: {}
  priorityClassName: ""
  schedulerName: ""
  topologySpreadConstraints: []
  grpc:
    server:
      tls:
        enabled: false
        autoGenerated: false
        cert: ""
        key: ""
        ca: ""
        existingSecret: {}
    client:
      serverName: ""
      tls:
        enabled: false
        autoGenerated: false
        cert: ""
        key: ""
        ca: ""
        existingSecret: {}
  service:
    type: ClusterIP
    ports:
      http: 9090
      grpc: 10901
    nodePorts:
      http: ""
      grpc: ""
    clusterIP: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalTrafficPolicy: Cluster
    annotations: {}
    extraPorts: []
    labelSelectorsOverride: {}
    additionalHeadless: false
  serviceAccount:
    annotations: {}
    existingServiceAccount: ""
    automountServiceAccountToken: true
  rbac:
    create: false
    rules: []
  pspEnabled: false
  autoscaling:
    enabled: false
    minReplicas: ""
    maxReplicas: ""
    targetCPU: ""
    targetMemory: ""
  pdb:
    create: false
    minAvailable: 1
    maxUnavailable: ""
  ingress:
    enabled: false
    hostname: thanos.local
    ingressClassName: ""
    annotations: {}
    extraHosts: []
    extraTls: []
    secrets: []
    tls: false
    selfSigned: false
    apiVersion: ""
    path: /
    pathType: ImplementationSpecific
    grpc:
      enabled: false
      hostname: thanos-grpc.local
      ingressClassName: ""
      annotations: {}
      extraHosts: []
      extraTls: []
      secrets: []
      tls: false
      selfSigned: false
      apiVersion: ""
      path: /
      pathType: ImplementationSpecific


queryFrontend:
  enabled: true
  logLevel: info
  logFormat: logfmt
  config: ""
  existingConfigmap: ""
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraFlags: []
  command: []
  args: []
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
  resources:
    limits: {}
    requests: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 30
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 30
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6
  startupProbe:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 15
    successThreshold: 1
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  initContainers: []
  sidecars: []
  extraVolumes: []
  extraVolumeMounts: []
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  podLabels: {}
  podAnnotations: {}
  hostAliases: []
  lifecycleHooks: {}
  priorityClassName: ""
  schedulerName: ""
  topologySpreadConstraints: []
  service:
    type: ClusterIP
    ports:
      http: 9090
    nodePorts:
      http: ""
    clusterIP: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalTrafficPolicy: Cluster
    annotations: {}
    extraPorts: []
    labelSelectorsOverride: {}
  serviceAccount:
    annotations: {}
    existingServiceAccount: ""
    automountServiceAccountToken: true
  rbac:
    create: false
    rules: []
  pspEnabled: false
  autoscaling:
    enabled: false
    minReplicas: ""
    maxReplicas: ""
    targetCPU: ""
    targetMemory: ""
  pdb:
    create: false
    minAvailable: 1
    maxUnavailable: ""
  ingress:
    enabled: false
    hostname: thanos.local
    ingressClassName: ""
    annotations: {}
    extraHosts: []
    extraTls: []
    secrets: []
    tls: false
    selfSigned: false
    apiVersion: ""
    path: /
    pathType: ImplementationSpecific


bucketweb:
  enabled: true
  logLevel: info
  logFormat: logfmt
  refresh: 30m
  timeout: 5m
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraFlags: []
  command: []
  args: []
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
  resources:
    limits: {}
    requests: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 30
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 30
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6
  startupProbe:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 15
    successThreshold: 1
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  initContainers: []
  sidecars: []
  extraVolumes: []
  extraVolumeMounts: []
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  podLabels: {}
  podAnnotations: {}
  hostAliases: []
  lifecycleHooks: {}
  priorityClassName: ""
  schedulerName: ""
  topologySpreadConstraints: []
  service:
    type: ClusterIP
    ports:
      http: 8080
    nodePorts:
      http: ""
    clusterIP: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalTrafficPolicy: Cluster
    annotations: {}
    extraPorts: []
    labelSelectorsOverride: {}
  serviceAccount:
    annotations: {}
    existingServiceAccount: ""
    automountServiceAccountToken: true
  autoscaling:
    enabled: false
    minReplicas: ""
    maxReplicas: ""
    targetCPU: ""
    targetMemory: ""
  pdb:
    create: false
    minAvailable: 1
    maxUnavailable: ""
  ingress:
    enabled: false
    hostname: thanos-bucketweb.local
    ingressClassName: ""
    annotations: {}
    extraHosts: []
    extraTls: []
    secrets: []
    tls: false
    selfSigned: false
    apiVersion: ""
    path: /
    pathType: ImplementationSpecific


compactor:
  enabled: true
  logLevel: info
  logFormat: logfmt
  retentionResolutionRaw: 30d
  retentionResolution5m: 30d
  retentionResolution1h: 10y
  consistencyDelay: 30m
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraFlags: []
  command: []
  args: []
  updateStrategy:
    type: Recreate
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
  resources:
    limits: {}
    requests: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 30
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 30
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6
  startupProbe:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 15
    successThreshold: 1
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  initContainers: []
  sidecars: []
  extraVolumes: []
  extraVolumeMounts: []
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  podLabels: {}
  podAnnotations: {}
  hostAliases: []
  lifecycleHooks: {}
  priorityClassName: ""
  schedulerName: ""
  topologySpreadConstraints: []
  service:
    type: ClusterIP
    ports:
      http: 9090
    nodePorts:
      http: ""
    clusterIP: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalTrafficPolicy: Cluster
    annotations: {}
    extraPorts: []
    labelSelectorsOverride: {}
  serviceAccount:
    annotations: {}
    existingServiceAccount: ""
    automountServiceAccountToken: true
  ingress:
    enabled: false
    hostname: thanos-compactor.local
    ingressClassName: ""
    annotations: {}
    extraHosts: []
    extraTls: []
    secrets: []
    tls: false
    selfSigned: false
    apiVersion: ""
    path: /
    pathType: ImplementationSpecific
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: {}
    existingClaim: ""


storegateway:
  enabled: true
  logLevel: info
  logFormat: logfmt
  config: ""
  existingConfigmap: ""
  grpc:
    server:
      tls:
        enabled: false
        autoGenerated: false
        cert: ""
        key: ""
        ca: ""
        existingSecret: {}
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraFlags: []
  command: []
  args: []
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
  resources:
    limits: {}
    requests: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 30
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 30
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6
  startupProbe:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 15
    successThreshold: 1
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  initContainers: []
  sidecars: []
  extraVolumes: []
  extraVolumeMounts: []
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  podLabels: {}
  podAnnotations: {}
  hostAliases: []
  lifecycleHooks: {}
  priorityClassName: ""
  topologySpreadConstraints: []
  schedulerName: ""
  service:
    type: ClusterIP
    ports:
      http: 9090
      grpc: 10901
    nodePorts:
      http: ""
      grpc: ""
    clusterIP: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalTrafficPolicy: Cluster
    annotations: {}
    extraPorts: []
    labelSelectorsOverride: {}
    additionalHeadless: false
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: {}
    existingClaim: ""
  serviceAccount:
    annotations: {}
    existingServiceAccount: ""
    automountServiceAccountToken: true
  autoscaling:
    enabled: false
    minReplicas: ""
    maxReplicas: ""
    targetCPU: ""
    targetMemory: ""
  pdb:
    create: false
    minAvailable: 1
    maxUnavailable: ""
  ingress:
    enabled: false
    hostname: thanos-storegateway.local
    ingressClassName: ""
    annotations: {}
    extraHosts: []
    extraTls: []
    secrets: []
    tls: false
    selfSigned: false
    apiVersion: ""
    path: /
    pathType: ImplementationSpecific
    grpc:
      enabled: false
      hostname: thanos-grpc.local
      ingressClassName: ""
      annotations: {}
      extraHosts: []
      extraTls: []
      secrets: []
      tls: false
      selfSigned: false
      apiVersion: ""
      path: /
      pathType: ImplementationSpecific
  sharded:
    enabled: false
    hashPartitioning:
      shards: ""
    timePartitioning:
      - min: ""
        max: ""
    service:
      clusterIPs: []
      loadBalancerIPs: []
      http:
        nodePorts: []
      grpc:
        nodePorts: []
   
ruler:
  affinity: {}
  alertmanagers:
    - http://prometheus-operator-alertmanager.monitoring.svc.cluster.local:9093
  alertmanagersConfig: ''
  args: []
  autoscaling:
    enabled: false
    maxReplicas: ''
    minReplicas: ''
    targetCPU: ''
    targetMemory: ''
  clusterName: ''
  command: []
  config: |-
    groups:
      - name: "metamonitoring"
        rules:
          - alert: "PrometheusDown"
            expr: absent(up{prometheus="monitoring/prometheus-operator"})
  containerSecurityContext:
    allowPrivilegeEscalation: false
    enabled: true
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1001
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  dnsDiscovery:
    enabled: true
  enabled: true
  evalInterval: 1m
  existingConfigmap: ''
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraFlags: []
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  ingress:
    annotations: {}
    apiVersion: ''
    enabled: false
    extraHosts: []
    extraTls: []
    hostname: thanos-ruler.example.local
    ingressClassName: 'haproxy'
    path: /
    pathType: ImplementationSpecific
    secrets: []
  initContainers: []
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 30
  logFormat: logfmt
  logLevel: info
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  pdb:
    create: false
    maxUnavailable: ''
    minAvailable: 1
  persistence:
    accessModes:
      - ReadWriteOnce
    annotations: {}
    enabled: true
    existingClaim: ''
    size: 8Gi
    storageClass: ''
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podManagementPolicy: OrderedReady
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  priorityClassName: ''
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 30
  replicaCount: 1
  replicaLabel: replica
  resources:
    limits: {}
    requests: {}
  schedulerName: ''
  service:
    additionalHeadless: false
    annotations: {}
    clusterIP: ''
    externalTrafficPolicy: Cluster
    extraPorts: []
    labelSelectorsOverride: {}
    loadBalancerIP: ''
    loadBalancerSourceRanges: []
    nodePorts:
      grpc: ''
      http: ''
    ports:
      grpc: 10901
      http: 9090
    type: ClusterIP
  serviceAccount:
    annotations: {}
    automountServiceAccountToken: true
    existingServiceAccount: ''
  sidecars: []
  startupProbe:
    enabled: false
    failureThreshold: 15
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1
  tolerations: []
  topologySpreadConstraints: []
  updateStrategy:
    type: RollingUpdate

receive:
  enabled: false
  mode: standalone
  logLevel: info
  logFormat: logfmt
  tsdbRetention: 15d
  replicationFactor: 1
  config: []
  existingConfigmap: ""
  replicaLabel: replica
  grpc:
    server:
      tls:
        enabled: false
        autoGenerated: false
        cert: ""
        key: ""
        ca: ""
        existingSecret: {}
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraFlags: []
  command: []
  args: []
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
  resources:
    limits: {}
    requests: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 30
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 30
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6
  startupProbe:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 15
    successThreshold: 1
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  initContainers: []
  sidecars: []
  extraVolumes: []
  extraVolumeMounts: []
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  podLabels: {}
  podAnnotations: {}
  hostAliases: []
  lifecycleHooks: {}
  priorityClassName: ""
  schedulerName: ""
  topologySpreadConstraints: []
  service:
    type: ClusterIP
    ports:
      http: 10902
      grpc: 10901
      remote: 19291
    nodePorts:
      http: ""
      grpc: ""
      remote: ""
    clusterIP: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalTrafficPolicy: Cluster
    annotations: {}
    extraPorts: []
    labelSelectorsOverride: {}
    additionalHeadless: false
  serviceAccount:
    annotations: {}
    existingServiceAccount: ""
    automountServiceAccountToken: true
  autoscaling:
    enabled: false
    minReplicas: ""
    maxReplicas: ""
    targetCPU: ""
    targetMemory: ""
  pdb:
    create: false
    minAvailable: 1
    maxUnavailable: ""
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: {}
    existingClaim: ""
  ingress:
    enabled: false
    hostname: thanos-receive.local
    ingressClassName: ""
    annotations: {}
    extraHosts: []
    extraTls: []
    secrets: []
    tls: false
    selfSigned: false
    apiVersion: ""
    path: /
    pathType: ImplementationSpecific


receiveDistributor:
  enabled: false
  logLevel: info
  logFormat: logfmt
  replicaLabel: replica
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraFlags: []
  command: []
  args: []
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
  resources:
    limits: {}
    requests: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 30
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 30
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6
  startupProbe:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 15
    successThreshold: 1
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  initContainers: []
  sidecars: []
  extraVolumes: []
  extraVolumeMounts: []
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  podLabels: {}
  podAnnotations: {}
  hostAliases: []
  lifecycleHooks: {}
  priorityClassName: ""
  schedulerName: ""
  topologySpreadConstraints: []
  serviceAccount:
    annotations: {}
    existingServiceAccount: ""
    automountServiceAccountToken: true
  autoscaling:
    enabled: false
    minReplicas: ""
    maxReplicas: ""
    targetCPU: ""
    targetMemory: ""
  pdb:
    create: false
    minAvailable: 1
    maxUnavailable: ""


metrics:
  enabled: enable
  serviceMonitor:
    enabled: enable
    namespace: "monitoring"
    labels:
      serviceMonitorSelector: monitoring
    jobLabel: ""
    interval: ""
    scrapeTimeout: ""
    metricRelabelings: []
    relabelings: []
    selector: {}

  prometheusRule:
    enabled: false
    namespace: ""
    additionalLabels: {}
    rules: []


volumePermissions:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 10-debian-10-r361
    pullPolicy: IfNotPresent
    pullSecrets: []

networkPolicy:
  enabled: false
  allowExternal: true
  explicitNamespacesSelector: {}
```

### What is the expected behavior?

Scrape other services, like node-exporter

```
kubectl get servicemonitor --namespace monitoring 
NAME                                      AGE
kube-prometheus-alertmanager              47h
kube-prometheus-apiserver                 47h
kube-prometheus-coredns                   47h
kube-prometheus-kube-controller-manager   47h
kube-prometheus-kube-proxy                47h
kube-prometheus-kube-scheduler            47h
kube-prometheus-kube-state-metrics        47h
kube-prometheus-kubelet                   47h
kube-prometheus-node-exporter             47h
kube-prometheus-operator                  47h
kube-prometheus-prometheus                47h
minio                                     21h
thanos-bucketweb                          24h
thanos-compactor                          24h
thanos-query                              24h
thanos-query-frontend                     24h
thanos-ruler                              24h
thanos-storegateway                       24h
````

### What do you see instead?

```
level=info ts=2022-03-11T12:13:22.155140754Z caller=options.go:27 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2022-03-11T12:13:22.156195285Z caller=query.go:702 msg="starting query node"
level=info ts=2022-03-11T12:13:22.156393775Z caller=intrumentation.go:56 msg="changing probe status" status=ready
level=info ts=2022-03-11T12:13:22.156817132Z caller=intrumentation.go:75 msg="changing probe status" status=healthy
level=info ts=2022-03-11T12:13:22.156894823Z caller=http.go:73 service=http/server component=query msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2022-03-11T12:13:22.156971616Z caller=grpc.go:131 service=gRPC/server component=query msg="listening for serving gRPC" address=0.0.0.0:10901
level=info ts=2022-03-11T12:13:22.156978481Z caller=tls_config.go:195 service=http/server component=query msg="TLS is disabled." http2=false
level=info ts=2022-03-11T12:13:27.164517691Z caller=endpointset.go:349 component=endpointset msg="adding new rule with [storeAPI rulesAPI]" address=10.233.52.220:10901 extLset="{replica=\"thanos-ruler-0\", ruler_cluster=\"\"}"
level=info ts=2022-03-11T12:13:27.164603765Z caller=endpointset.go:349 component=endpointset msg="adding new store with [storeAPI]" address=10.233.53.117:10901 extLset="{replica=\"thanos-ruler-0\", ruler_cluster=\"\"}"
```

So I see only in querer frontend .. the ruler
![Bildschirmfoto von 2022-03-11 14-27-25](https://user-images.githubusercontent.com/1276233/157877055-78317b4e-c547-4934-adea-7bd0a41ee06d.png)

### Additional information

Either I did something wrong, or I miss something. I have no clue :-) 

It would be nice, if I get a hint .. what the root cause is.

Thanks (pretty big thanks for this Chart !)

**Comment by alemorcuq** [comment]
We'll look into it, thanks. Could you please provide only the values you are specifically setting instead of the whole list? It will be helpful for us to try to reproduce.

**Comment by linuxmail** [comment]
Hi @alemorcuq 

thanks for the reply .. I hope, that I do not forget something

```
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: "direct-csi-min-io"

objstoreConfig: |-
  type: s3
  config:
    bucket: prometheus-long-term
    endpoint: minio.minio.svc.cluster.local:9000
    access_key: thanos
    secret_key: s3cr3t
    insecure: true

query:
  enabled: true
  dnsDiscovery:
    sidecarsService: prometheus-operator-prometheus-thanos
    sidecarsNamespace: monitoring
    enabled: true
    stores: [] > removed

bucketweb:                                                                                                
  enabled: true
compactor:
  enabled: true
storegateway:
  enabled: true
ruler:
  affinity: {}
  alertmanagers:
    - http://prometheus-operator-alertmanager.monitoring.svc.cluster.local:9093
  alertmanagersConfig: ''
  args: []
  autoscaling:
    enabled: false
    maxReplicas: ''
    minReplicas: ''
    targetCPU: ''
    targetMemory: ''
  clusterName: ''
  command: []
  config: |-
    groups:
      - name: "metamonitoring"
        rules:
          - alert: "PrometheusDown"
            expr: absent(up{prometheus="monitoring/prometheus-operator"})
  containerSecurityContext:
    allowPrivilegeEscalation: false
    enabled: true
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1001
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  dnsDiscovery:
    enabled: true
  enabled: true
  ingress:
    annotations: {}
    apiVersion: ''
    enabled: false
    extraHosts: []
    extraTls: []
    hostname: thanos-ruler.example.com
    ingressClassName: 'haproxy'
    path: /
    pathType: ImplementationSpecific
    secrets: []
  initContainers: []
  lifecycleHooks: {}

metrics:
  enabled: enable
  serviceMonitor:
    enabled: enable
    namespace: "monitoring"
    labels:
      serviceMonitorSelector: monitoring
    jobLabel: ""
    interval: ""
    scrapeTimeout: ""
    metricRelabelings: []
    relabelings: []
    selector: {}
```

cu denny

**Comment by linuxmail** [comment]
Hello, 

I've found the "issue". Problem is / was .. that there was no Thanos sidecar, which uploads the Prometheus data to the S3 (minio). I compared my old Thanos K8s config with the Bitnami chart and missed the sidecar. I've found also related tickets like this [one](https://github.com/bitnami/charts/issues/3843) that pushes me in the right direction.

After adding 

```
        - name: thanos-sidecar
          image: docker.io/bitnami/thanos:0.25.0-scratch-r1
          args:
            - sidecar
            - '--prometheus.url=http://localhost:9090'
            - '--grpc-address=0.0.0.0:10901'
            - '--http-address=0.0.0.0:10902'
            - '--tsdb.path=/prometheus/'
            - '--objstore.config=$(OBJSTORE_CONFIG)'
```
to the kube-prometheus-prometheus .. Thanos starts with uploading the data to the S3 and is now available.
