### ISSUE TITLE
Requirements.txt file in Bitnami Airflow

### ISSUE THREAD

**Issue by gowthamprabhu** [bitnami/charts#9390]
### Name and Version

bitnami/airflow:2.2.4-debian-10-r1

### What steps will reproduce the bug?

I have installed Airflow in Kubernetes with the Helm Chart, however the requriements.txt file doesn't seem to be executed.

I have created a configmap in the namespace with the below command, 

kubectl create configmap requirements --from-file=requirements.txt -n airflow 

Now in the values file, I've used as below,
  extraVolumeMounts:
    - name: requirements
      mountPath: /bitnami/python/requirements.txt

  extraVolumes:
    - name: requirements

But the dependencies mentioned in the file doesn't seem to be installed. 

### Are you using any custom parameters or values?

kubectl create configmap requirements --from-file=requirements.txt -n airflow 

Now in the values file, I've used as below,
  extraVolumeMounts:
    - name: requirements
      mountPath: /bitnami/python/requirements.txt

  extraVolumes:
    - name: requirements

### What do you see instead?

Requirements dependencies not installed.

**Comment by fmulero** [comment]
Hi @gowthamprabhu 

I am not able to reproduce your issue. This is a `values.yaml` file with a similar configuration that you are trying:

```yaml
web: &requirements-volume-config
  extraVolumeMounts: 
    - name: requirements
      mountPath: /bitnami/python/requirements.txt
      subPath: requirements.txt
  extraVolumes:
    - name: requirements
      configMap:
        name: airflow-requirements
scheduler: *requirements-volume-config
worker: *requirements-volume-config
extraDeploy:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: airflow-requirements
    data:
      requirements.txt: |
        apache-airflow-providers-google
```

Please be aware of:
* Path to `extraVolumeMounts` and `extraVolumes` parameters. They are inside of `web`, `worker` or `scheduler` configuration
* `extraDeploy` parameter could help you to create additional resources like the requirements configmap.

I hope it helps
