### ISSUE TITLE
redis replicas restart when master restarts

### ISSUE THREAD

**Issue by edwardcookemacu** [bitnami/charts#9391]
### Name and Version

bitnami/redis

### What steps will reproduce the bug?

In docker-desktop

### Are you using any custom parameters or values?

```yaml
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: "nfs-client"
  redis:
    password: ""

kubeVersion: "1.22"
fullnameOverride: "redis"

auth:
  existingSecret: "redis-password"
  existingSecretPasswordKey: "password"

master:
  resources:
    limits: {}
    requests: {}
  ## Redis&trade; master service parameters
  ##
  service:
    type: NodePort
    nodePorts:
      redis: 30000

replica:
  resources:
    limits: {}
    requests: {}
  service:
    type: NodePort
    nodePorts:
      redis: 30001
```

### What is the expected behavior?

When the master pod is deleted (for whatever reason) the replicas don't restart.

### What do you see instead?

The replicas restart

### Additional information

I simulate a restart of the master node by calling `kubectl delete pod redis-master-0` or `kubectl rollout restart sts redis-master`. When the master node comes up the replicas restart.

The logs in the replica don't give much information. The empty lines is where I did the delete (just pressed enter to add some space)

```
1:S 12 Mar 2022 20:22:07.336 * Connecting to MASTER redis-master-0.redis-headless.redis.svc.cluster.local:6379
1:S 12 Mar 2022 20:22:07.337 * MASTER <-> REPLICA sync started


1:signal-handler (1647116549) Received SIGTERM scheduling shutdown...
1:S 12 Mar 2022 20:22:29.634 # User requested shutdown...
1:S 12 Mar 2022 20:22:29.634 * Calling fsync() on the AOF file.
1:S 12 Mar 2022 20:22:29.634 # Redis is now ready to exit, bye bye...
```
