### ISSUE TITLE
On Kafka Helm Chart installed on Docker Kubernetes On Mac Can't connect to external port  

### ISSUE THREAD

**Issue by pepgid** [bitnami/charts#9406]
### Name and Version

bitnami/kafka 14.0.2

### What steps will reproduce the bug?

1. On Mac, docker-desktop Kubernetes.
2. use zookeeper in indipindant chart 
`helm --kube-context docker-desktop upgrade zookeeper -n kafka bitnami/zookeeper -f values.yaml --version 7.3.0`
3. `helm --kube-context docker-desktop install kafka -n kafka bitnami/kafka -f values.yaml --version 14.0.2`
5. custom values as below
6. with externalAccess.service.useHostIPs: false or true
7. with externalAccess.service.domain: not set or 192.168.65.4 or 127.0.0.1 
8. 
```console
$ kubectl -n kafka get svc
NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
kafka                ClusterIP   10.109.195.102   <none>        9092/TCP                     4m42s
kafka-0-external     NodePort    10.102.145.16    <none>        9094:30000/TCP               4m42s
kafka-1-external     NodePort    10.111.253.191   <none>        9094:30001/TCP               4m42s
kafka-2-external     NodePort    10.104.59.173    <none>        9094:30002/TCP               4m42s
kafka-headless       ClusterIP   None             <none>        9092/TCP,9093/TCP            4m42s
kafka-jmx-metrics    ClusterIP   10.108.231.64    <none>        5556/TCP                     4m42s
kafka-metrics        ClusterIP   10.101.95.106    <none>        9308/TCP                     4m42s
zookeeper            ClusterIP   10.102.225.83    <none>        2181/TCP,2888/TCP,3888/TCP   6h36m
zookeeper-headless   ClusterIP   None             <none>        2181/TCP,2888/TCP,3888/TCP   6h36m
```

### Are you using any custom parameters or values?
```yaml
image: 
  registry: docker.io
  repository: bitnami/kafka
  tag: 2.8.0-debian-10-r61
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
hostAliases: []
podManagementPolicy: Parallel
clusterDomain: cluster.local
commonLabels: {}
commonAnnotations: {}
heapOpts: -Xmx6g -Xms6g
deleteTopicEnable: true
autoCreateTopicsEnable: true
logFlushIntervalMessages: _300000
logFlushIntervalMs: 999990
logRetentionBytes: _12073741824
logRetentionCheckIntervalMs: 300000
logRetentionHours: 168
logSegmentBytes: _1073741824
logsDirs: /bitnami/kafka/data
maxMessageBytes: _12000024
defaultReplicationFactor: 1
offsetsTopicReplicationFactor: 1
transactionStateLogReplicationFactor: 1
transactionStateLogMinIsr: 1
numIoThreads: 100
numNetworkThreads: 100
numPartitions: 1
numRecoveryThreadsPerDataDir: 1
socketReceiveBufferBytes: 102400
socketRequestMaxBytes: _104857600
socketSendBufferBytes: 102400
zookeeperConnectionTimeoutMs: 6000
command: 
  - /scripts/setup.sh
args: []
extraEnvVars: []
extraVolumes: []
extraVolumeMounts: []
extraDeploy: []
auth: 
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  sasl: 
    mechanisms: plain,scram-sha-256,scram-sha-512
    interBrokerMechanism: plain
    jaas: 
      clientUsers: 
        - user
      clientPasswords: []
      interBrokerUser: admin
      interBrokerPassword: ""
      zookeeperUser: ""
      zookeeperPassword: ""
      existingSecret: ""
  saslMechanisms: plain,scram-sha-256,scram-sha-512
  saslInterBrokerMechanism: plain
  jaas: 
    clientUsers: 
      - user
    clientPasswords: []
    interBrokerUser: admin
    interBrokerPassword: ""
    zookeeperUser: ""
    zookeeperPassword: ""
    existingSecret: ""
  tls: 
    type: jks
    existingSecret: ""
    autoGenerated: false
    password: ""
    jksTruststoreSecret: ""
    jksKeystoreSAN: ""
    jksTruststore: ""
    endpointIdentificationAlgorithm: https
  jksSecret: ""
  jksTruststoreSecret: ""
  jksKeystoreSAN: ""
  jksTruststore: ""
  jksPassword: ""
  tlsEndpointIdentificationAlgorithm: https
listeners: []
advertisedListeners: []
allowPlaintextListener: true
interBrokerListenerName: INTERNAL
replicaCount: 3
minBrokerId: 0
updateStrategy: RollingUpdate
podLabels: {}
podAnnotations: {}
priorityClassName: ""
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset: 
  type: ""
  key: ""
  values: []
affinity: {}
nodeSelector: {}
tolerations: []
podSecurityContext: 
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
containerSecurityContext: {}
resources: 
  requests: 
    cpu: 1
    memory: 2Gi
  limits: {}
livenessProbe: 
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 5
readinessProbe: 
  enabled: true
  initialDelaySeconds: 5
  failureThreshold: 6
  timeoutSeconds: 5
customLivenessProbe: {}
customReadinessProbe: {}
pdb: 
  create: false
  maxUnavailable: 1
sidecars: {}
service: 
  type: ClusterIP
  port: 9092
  internalPort: 9093
  externalPort: 9094
  nodePorts: 
    client: ""
    external: ""
  loadBalancerSourceRanges: []
  annotations: {}
externalAccess: 
  enabled: true
  autoDiscovery: 
    enabled: true
    image: 
      registry: docker.io
      repository: bitnami/kubectl
      tag: 1.19.13-debian-10-r15
      pullPolicy: IfNotPresent
      pullSecrets: []
    resources: 
      limits: {}
      requests: {}
  service: 
    type: NodePort
    port: 9094
    loadBalancerIPs: []
    loadBalancerSourceRanges: []
    nodePorts: 
      - 30000
      - 30001
      - 30002
    useHostIPs: true
    annotations: {}
persistence: 
  enabled: true
  accessModes: 
    - ReadWriteOnce
  size: 1Gi
  annotations: {}
  mountPath: /bitnami/kafka
logPersistence: 
  enabled: true
  accessModes: 
    - ReadWriteOnce
  size: 20Gi
  annotations: {}
  mountPath: /opt/bitnami/kafka/logs
volumePermissions: 
  enabled: false
  securityContext: 
    runAsUser: 0
  image: 
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 10-debian-10-r149
    pullPolicy: Always
    pullSecrets: []
  resources: 
    limits: {}
    requests: {}
serviceAccount: 
  create: true
  automountServiceAccountToken: true
rbac: 
  create: true
provisioning: 
  enabled: false
  image: 
    registry: docker.io
    repository: bitnami/kafka
    tag: 2.7.0-debian-10-r108
    pullPolicy: IfNotPresent
    pullSecrets: []
    debug: false
  numPartitions: 1
  replicationFactor: 1
  resources: 
    limits: {}
    requests: {}
  command: []
  args: []
  topics: []
metrics: 
  kafka: 
    enabled: true
    image: 
      registry: docker.io
      repository: bitnami/kafka-exporter
      tag: 1.3.1-debian-10-r64
      pullPolicy: IfNotPresent
      pullSecrets: []
    extraFlags: {}
    tlsCert: cert-file
    tlsKey: key-file
    tlsCaCert: ca-file
    resources: 
      limits: {}
      requests: {}
    affinity: {}
    nodeSelector: {}
    tolerations: []
    service: 
      type: ClusterIP
      port: 9308
      nodePort: ""
      loadBalancerSourceRanges: []
      annotations: 
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.metrics.kafka.service.port }}"
        prometheus.io/path: "/metrics"
  jmx: 
    enabled: true
    image: 
      registry: docker.io
      repository: bitnami/jmx-exporter
      tag: 0.16.1-debian-10-r17
      pullPolicy: IfNotPresent
      pullSecrets: []
    resources: 
      limits: {}
      requests: {}
    service: 
      type: ClusterIP
      port: 5556
      nodePort: ""
      loadBalancerSourceRanges: []
      annotations: 
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.metrics.jmx.service.port }}"
        prometheus.io/path: "/"
    whitelistObjectNames: 
      - kafka.controller:*
      - kafka.server:*
      - java.lang:*
      - kafka.network:*
      - kafka.log:*
    config: |
      jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:5555/jmxrmi
      lowercaseOutputName: true
      lowercaseOutputLabelNames: true
      ssl: false
      {{- if .Values.metrics.jmx.whitelistObjectNames }}
      whitelistObjectNames: ["{{ join "\",\"" .Values.metrics.jmx.whitelistObjectNames }}"]
      {{- end }}
  serviceMonitor: 
    enabled: true
    namespace: monitoring
zookeeper: 
  enabled: false
  auth: 
    enabled: false
externalZookeeper: 
  servers: 
    - zookeeper.kafka.svc.cluster.local
initContainers: []
```
### What is the expected behavior?

I expect to connect to Kafka from mac command line using external service
`kafkacat -b localhost:30000 -t test -C` 
should work

### What do you see instead?

both
`kafkacat -b localhost:30000 -t test -C` 
`kafkacat -b 127.0.0.1:30000 -t test -C` 
hang and don't receive messages 
no error

From a pod inside Kubernetes I can access brokers:
This command works from pod in Kubernetes:
`kafkacat -b kafka.kafka.svc.cluster.local:9092 -t test -C` 

I can't access Kafka brokers from mac 

`kafkacat -b localhost:9094 -t test -C` 

produces this error:

```
%3|1647288863.833|FAIL|rdkafka#consumer-1| [thrd:localhost:9094/bootstrap]: localhost:9094/bootstrap: Connect to ipv4#127.0.0.1:9094 failed: Connection refused (after 1ms in state CONNECT)
%3|1647288864.833|FAIL|rdkafka#consumer-1| [thrd:localhost:9094/bootstrap]: localhost:9094/bootstrap: Connect to ipv6#[::1]:9094 failed: Connection refused (after 0ms in state CONNECT)
%3|1647288865.834|FAIL|rdkafka#consumer-1| [thrd:localhost:9094/bootstrap]: localhost:9094/bootstrap: Connect to ipv6#[::1]:9094 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
%3|1647288866.834|FAIL|rdkafka#consumer-1| [thrd:localhost:9094/bootstrap]: localhost:9094/bootstrap: Connect to ipv4#127.0.0.1:9094 failed: Connection refused (after 0ms in state CONNECT)
```

`kafkacat -b localhost:9092 -t test -C` 

produces this error:

```
%3|1647288518.714|FAIL|rdkafka#consumer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv6#[::1]:9092 failed: Connection refused (after 1ms in state CONNECT)
%3|1647288519.717|FAIL|rdkafka#consumer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)
%3|1647288520.718|FAIL|rdkafka#consumer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
```

### Additional information

On AWS and on Ubuntu using Kind we access Kafka externally with no problem.
