### ISSUE TITLE
[bitnami/kube-prometheus] All tls-secret generated by ClusterIssuer are overwriten by the chart

### ISSUE THREAD

**Issue by DaedalusDev** [bitnami/charts#9430]
### Name and Version

bitnami/kube-prometheus 6.6.12

### What steps will reproduce the bug?

1. Deploy a kube-prometheus with the following values
  ```yaml
  prometheus:
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: <valid-hostname>
      tls: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: <valid-cluster-issuer>
  ```
2. A secret named `<valid-hostname>-tls` will be generate the cluster issuer
3. Deploy the chart again
4. A secret name `<valid-hostname>-tls` (sefl signed) will be generate the chart

### Are you using any custom parameters or values?

  ```yaml
  prometheus:
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: <valid-hostname>
      tls: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: <valid-cluster-issuer>
  ```

### What is the expected behavior?

ClusterIssuer's certificate must-not be overwritten.

### What do you see instead?

Secret is overwritten

### Additional information

A quick workarround is to toggle a deprecated value in values :
  ```yaml
  prometheus:
    ingress:
      enabled: true
      certManager: true # Won't overwrite certificate
      ingressClassName: nginx
      hostname: <valid-hostname>
      tls: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: <valid-cluster-issuer>
  ```

I'm gonna submit a merge request with a new parameter `ingress.selfSigned` to conform with most sibling charts
