### ISSUE TITLE
Grafana Helm Chart - alertmanager datasources not picking up "prometheus" implementation

### ISSUE THREAD

**Issue by DanPhonovation** [bitnami/charts#9443]
### Name and Version

bitnami/grafana 7.6.17

### What steps will reproduce the bug?

I am trying to deploy the alpha alert manager UI as per: https://grafana.com/docs/grafana/latest/datasources/alertmanager/

I have a secret enabling the alpha plugins and my datasource appears in the UI.

However, it is prometheus alert manager, so I specify the prometheus implementation but the UI still shows "Cortex" and I'm assuming thats why all the tabs for alert manager are failing.

### Are you using any custom parameters or values?

Secret containing alertmanager datasource but "prometheus" implementation type seems to be ignored.

```
apiVersion: v1
kind: Secret
metadata:
  name: grafana-alertmanager-datasource
  namespace: kannel-monitoring
type: Opaque
stringData:
  alertmanager_datasource.yaml: |-
    datasources:
      - name: Alertmanager
        type: alertmanager
        url: http://kannel-monitor-prometheus-alertmanager:9093
        access: proxy
        jsonData:
          implementation: prometheus
```

### What is the expected behavior?

THe UI shows "prometheus" implementation type

### What do you see instead?

UI shows Cortex implementation  type

### Additional information

![image](https://user-images.githubusercontent.com/33551214/158604429-45e4af33-c5a3-45cc-a626-d3ead7fcd7f2.png)

**Comment by DanPhonovation** [comment]
```
apiVersion: v1
kind: Secret
metadata:
  name: grafana-alertmanager-datasource
  namespace: kannel-monitoring
type: Opaque
stringData:
  alertmanager_datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Alertmanager
        type: alertmanager
        url: http://kannel-monitor-prometheus-alertmanager
        access: proxy
        jsonData:
          implementation: prometheus
```

Changing to this (add apiversion) seems to have resolved it.
