### ISSUE TITLE
Thanos-sidecar missing in release

### ISSUE THREAD

**Issue by brandshaide** [bitnami/charts#9444]
### Name and Version

bitnami/thanos

### What steps will reproduce the bug?

1. Runtime AKS k8s  with `kube-prometheus` and `prometheus-operator`
2. ``helm repo add bitnami https://charts.bitnami.com/bitnami`` ``helm install my-release bitnami/thanos``

### Are you using any custom parameters or values?

Using a `values.yaml` with `objectStorage` configured accordingly for Azure storage account: 

```
thanos:
  objstoreConfig: |
    type: AZURE
    config:
      storage_account: "thanossandbox"
      storage_account_key: "XXXXXXXXXXX"
      container: "thanoscontainer"
      endpoint: ""
      max_retries: 0

```

### What is the expected behavior?

Helm chart is ramping up all required components alongside Prometheus incl. thanos-sidecar

### What do you see instead?

Thanos-sidecar is missing and thus not ingesting any TSDB buckets to `objectStorage`

```
$ kubectl -n prometheus get po

core-prometheus-thanos-query-65cb9cfc9c-t875l            2/2     Running   0               30m
core-prometheus-thanos-query-frontend-7796f96bfb-6mqtb   2/2     Running   0               30m
prometheus-operator-857fc7fd78-xgcjk                     1/1     Running   0               6d5h
prometheus-prometheus-prometheus-0                       3/3     Running   0               5m41s
```

What am I missing? Thanks in advance
