### ISSUE TITLE
Can't use numeric password as initdb.password

### ISSUE THREAD

**Issue by EBCEEB** [bitnami/charts#9445]
### Name and Version

bitnami/postgresql 11.1.7

### What steps will reproduce the bug?

Try to deploy chart with initdb.password=12345678

### What do you see instead?

```
Error from server (BadRequest): error when creating "deploy.yaml": StatefulSet in version "v1" cannot be handled as a StatefulSet: json: cannot unmarshal number into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
```

### Additional information

The password value is not quoted in manifest:

```yaml
            {{- if .Values.primary.initdb.password }}
            - name: POSTGRESQL_INITSCRIPTS_PASSWORD
              value: {{ .Values.primary.initdb.password }}
            {{- end }}
```
