### ISSUE TITLE
argo-cd improved comment in values.yaml on helm chart for configuring oidc

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#9448]
### Name and Version

bitnami/argocd : latest

### What is the problem this feature will solve?

Attempting to configure oidc.  I know the values I need as I have configured things before using a configmap.

Configuring via the helm chart is proving a little difficult.

I have read about the technique I seem to need here:
https://docs.bitnami.com/tutorials/bitnami-best-practices-hardening-charts/

Not sure what to put in the values.yaml, here's what I think I need:
```
server:
  config:
    url: "https://<url>"

  config: |
    oidc.config:
      name = Azure
```

### What is the feature you are proposing to solve the problem?

There is a comment in values.yaml which is providing guidance on how to configure oidc:
```
  ## Argo CD server config. This object will be directly rendered
  ## @param server.config [object] Argo CD server configuration that will end on the argocd-cm Config Map
  ## Ref: https://argoproj.github.io/argo-cd/operator-manual/user-management/
```
However, for someone like myself working with common.tplvalues.render for the first time.  It is not immediately obvious how to get things working.

Please provide some additional comments.  Perhaps a comment to a url where using tplvalues.render is explained, and/or by adjusting the oidc example to use the formatting expected when using tplvalues.render .

**Comment by lknite** [comment]
Possibly related:  https://github.com/bitnami/charts/issues/9449

**Comment by marcosbc** [comment]
Hi @lknite, thanks for the feedback. I would like to understand further what is your concern with the current documentation.

Note that what [`common.tplvalues.render`](https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_tplvalues.tpl) will do is basically execute the [Helm `tpl` function](https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function) on a string, or on a YAML object, and render any LUA template strings, e.g.: `{{ .Value }}`.

But templating is not mandatory, which means that you could always include a raw YAML object like the one used in the example:

```
oidc.config:
  name: AzureAD
  issuer: https://login.microsoftonline.com/TENANT_ID/v2.0
  clientID: CLIENT_ID
  clientSecret: $oidc.azuread.clientSecret
  requestedIDTokenClaims:
    groups:
      essential: true
  requestedScopes:
    - openid
    - profile
    - email
```

But in this case, we also allow for the templates, which work exactly like they do throughout the Helm chart, where you could use Helm templating options like `{{ .Values.something }}`, loops, etc.

**Comment by lknite** [comment]
Like this?
```
server:
  oidc.config:
    name: Keycloak
    issuer: test
    clientID: test
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email"]
    logoutURL: test
```

Didn't work, tested with:
helm template argocd bitnami/argo-cd -f ./values.yaml -s templates/argocd-cm.yaml

Also tried with:
```
server:
  oidc:
    config:
      name: Keycloak ...
```

No errors, just lacks the oidc data:
```
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  dex.config: ""
  url: '...'
```

**Comment by lknite** [comment]
I eventually figured it out:
```
server:
  config:
    oidc.config:
       name: Keycloak
```

Maybe adjust the upper comment to something like:
```
  ## Argo CD server config. This object will be directly rendered
  ## @param server.config [object] Argo CD server configuration that will end on the argocd-cm Config Map
  ## Ref: https://argoproj.github.io/argo-cd/operator-manual/user-management/
  ## E.g:
  ## config:
  ##   repositories:
  ##     ...
  ##   oidc.config:
  ##     ...
  ##   dex.config:
  ##     ...
```

Or move the available sections underneath config:
```
server:
  config:
    ## Argo CD external base URL. Required when configuring SSO. Required when enabling dex.
    ## E.g:
    ## url: https://argocd.example.com
    ##
    url: "{{ .Values.server.url }}"
    ## Argo CD instance label key
    ##
    application.instanceLabelKey: argocd.argoproj.io/instance
    ## If Dex is enabled you need to add connectors here
    ## dex.config: |
    ##  connectors: []
    ##
    dex.config: ""
    ## dex.config:
    ##    connectors:
    ##      # GitHub example
    ##      - type: github
    ##        id: github
    ##        name: GitHub
    ##        config:
    ##          clientID: aabbccddeeff00112233
    ##          clientSecret: $dex.github.clientSecret
    ##          orgs:
    ##          - name: your-github-org
    ## repositories:
    ##   - url: git@github.com:group/repo.git
    ##     sshPrivateKeySecret:
    ##       name: secret-name
    ##       key: sshPrivateKey
    ##   - type: helm
    ##     url: https://charts.helm.sh/stable
    ##     name: stable
    ##   - type: helm
    ##     url: https://argoproj.github.io/argo-helm
    ##     name: argo
    ## oidc.config:
    ##   name: AzureAD
    ##   issuer: https://login.microsoftonline.com/TENANT_ID/v2.0
    ##   clientID: CLIENT_ID
    ##   clientSecret: $oidc.azuread.clientSecret
    ##   requestedIDTokenClaims:
    ##     groups:
    ##       essential: true
    ##   requestedScopes:
    ##     - openid
    ##     - profile
    ##     - email
```
