### ISSUE TITLE
argo-cd, common.tplvalues.render source server.config may conflict if used, should it be something other than server.config to avoid conflicting with other values such as: server.config.url?

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#9449]
### Name and Version

bitnami/argocd : latest

### What steps will reproduce the bug?

Add some additional values in values.yaml which you want to have end up underneath data in the argocd-cm:

values.yaml:
```yaml
server:
  config: |
    something = "asdf"
```

Now install helm argo-cd helm chart using the provided values.yaml.

### Are you using any custom parameters or values?

yes, see previous note, the idea is to add additional values to the argocd-cm

### What is the expected behavior?

The template for argocd-cm.yaml contains the following for adding customized values to the argocd-cm configmap:
```yaml
data:
  {{- include "common.tplvalues.render" ( dict "value" .Values.server.config "context" $ ) | nindent 2 }}
```

I would expect something like:
```yaml
server:
  config: |
    a = "one"
    b = "two"
```
to add the two specified values to the argocd-cm .

### What do you see instead?

I'm new to using common.tplvalues.render, but when I try to use it I get errors which make me think maybe server.config is invalid because it is being used in another way in the values.yaml:
```yaml
server:
  config:
    ## Argo CD external base URL. Required when configuring SSO. Required when enabling dex.
    ## E.g:
    ## url: https://argocd.example.com
    ##
    url: "{{ .Values.server.url }}"
    ## Argo CD instance label key
    ##
    application.instanceLabelKey: argocd.argoproj.io/instance
    ## If Dex is enabled you need to add connectors here
    ## dex.config: |
    ##  connectors: []
    ##
    dex.config: ""
```

errors:
```
Release "argocd-seed" does not exist. Installing it now.
coalesce.go:200: warning: cannot overwrite table with non table for config (map[application.instanceLabelKey:argocd.argoproj.io/instance dex.config: url:{{ .Values.server.url }}])
coalesce.go:200: warning: cannot overwrite table with non table for config (map[application.instanceLabelKey:argocd.argoproj.io/instance dex.config: url:{{ .Values.server.url }}])
coalesce.go:200: warning: cannot overwrite table with non table for config (map[application.instanceLabelKey:argocd.argoproj.io/instance dex.config: url:{{ .Values.server.url }}])
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ConfigMap.data): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "string", expected "map"
```

### Additional information

I wonder if this used to work:
```yaml
data:
  {{- include "common.tplvalues.render" ( dict "value" .Values.server.config "context" $ ) | nindent 2 }}
```

But, it no longer works because someone else started using additional values underneath server.config .

Is it possible we need to use a different value such as server.extraConfig instead of server.config?

**Comment by carrodher** [comment]
When running `helm template petete bitnami/argo-cd -f values.yaml -s templates/argocd-cm.yaml` using the following values
```yaml
server:
   config: |
     a = "one"
     b = "two"
```
the config map is rendered without any issue
```yaml
# Source: argo-cd/templates/argocd-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  # Mandatory hardcoded name.
  # Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  name: argocd-cm
  namespace: "default"
  labels:
    app.kubernetes.io/name: argo-cd
    helm.sh/chart: argo-cd-3.0.13
    app.kubernetes.io/instance: petete
    app.kubernetes.io/managed-by: Helm
    # Mandatory label
    # Ref: https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#atomic-configuration
    app.kubernetes.io/part-of: argocd
data:
  a = "one"
  b = "two"
```

**Comment by lknite** [comment]
@carrodher Running that command worked for me also.

I'm not sure what troubleshooting to perform.  If I remove the 'config: |' then my error goes away, demonstrating it is the source of the error.

# Some additional detail

Chart.yaml
```
$ cat Chart.yaml 
apiVersion: v2
name: argocd-seed
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: argo-cd
  repository: https://charts.bitnami.com/bitnami
  version: 3.1.0
```

So, it is a subchart meaning my values.yaml does have a top level argo-cd:
```
argo-cd:
  global:
    imageRegistry: "harbor.mydomain.com/dockerhub-proxy"
    storageClass: "medium"

  image:
    registry: "harbor.mydomain.com/dockerhub-proxy"

  # required to use ingress
  server:
    insecure: true
    url: "https://argocd-seed.mydomain.com"

#   config:
#     url: "https://argocd-seed.mydomain.com"

    config: |
      asdf = https://argocd-seed.prod.core.k.idaho.gov

    extraVolumes:
    - name: certs
      configMap:
        name: ca-certs
        items:
        - key: "ca.crt"
          path: "ca-certificates.crt"

    extraVolumeMounts:
    - mountPath: /etc/ssl/certs
      name: certs

  controller:
    extraVolumes:
    - name: certs
      configMap:
        name: ca-certs
        items:
        - key: "ca.crt"
          path: "ca-certificates.crt"

    extraVolumeMounts:
    - mountPath: /etc/ssl/certs
      name: certs

  repoServer:
    extraVolumes:
    - name: certs
      configMap:
        name: ca-certs
        items:
        - key: "ca.crt"
          path: "ca-certificates.crt"

    extraVolumeMounts:
    - mountPath: /etc/ssl/certs
      name: certs
```

**Comment by carrodher** [comment]
It seems using those parameters the ConfigMap is properly rendered as well:
```
helm template my-chart bitnami/argo-cd -f values.yaml -s templates/argocd-cm.yaml
```
```yaml
# Source: argo-cd/templates/argocd-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  # Mandatory hardcoded name.
  # Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  name: argocd-cm
  namespace: "default"
  labels:
    app.kubernetes.io/name: argo-cd
    helm.sh/chart: argo-cd-3.1.1
    app.kubernetes.io/instance: my-chart
    app.kubernetes.io/managed-by: Helm
    # Mandatory label
    # Ref: https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#atomic-configuration
    app.kubernetes.io/part-of: argocd
data:
  asdf = https://argocd-seed.mydomain.com
```

In your case, being used as a subchart shouldn't make any difference

**Comment by lknite** [comment]
I was using 1.18, just retested with 1.22.4.  Still seeing the same result.

Your command works:
```
helm template my-chart bitnami/argo-cd -f values.yaml -s templates/argocd-cm.yaml
```

The exact same 'config: |' configuration indented under the appropriate subchart name does not appear to work.

**Comment by lknite** [comment]
hmm, this also works:
```
helm template argocd ./base
```

troubleshooting ...

**Comment by lknite** [comment]
I guess this is a helm related issue.  I'll close and reopen over there.

**Comment by lknite** [comment]
For whatever reason, the pipe was required after oidc.config like so:
```
  server:

    config:
      oidc.config: |
        name: Keycloak
```
