### ISSUE TITLE
[bitnami/solr] tls.existingSecret 

### ISSUE THREAD

**Issue by DirkDittmarMonday** [bitnami/charts#9462]
### Name and Version

bitnami/solr

### What steps will reproduce the bug?

1. I tried to configure TLS (`values.yaml`):
```
tls:
  enabled: true
  certificatesSecretName: solr-tls-cert
  passwordsSecretName: solr-pkcs12-password-secret
```
2. `helm template . ` gives me the following error:
```
VALUES VALIDATION:

solr: tls.enabled
    In order to enable TLS, you also need to provide
    an existing secret containing the Keystore and Truststore or
    enable auto-generated certificates.
```

The Parameter `tls.existingSecret` is not documented (I think that's the only problem):
https://github.com/bitnami/charts/blob/4e3e2e24823338390171d533c49807788da881a2/bitnami/solr/templates/_helpers.tpl#L173

### What is the expected behavior?

I expect that my the provided certificates should be enough when I set `enabled: true` and `autoGenerated: false` (which is the default).
