### ISSUE TITLE
Cannot get magento to start in kubernetes environment

### ISSUE THREAD

**Issue by cmeyertons** [bitnami/charts#947]
**Description**

Cannot get magento to successfully initialize using helm in Azure Kubernetes Service connecting to Azure MySql database

**Steps to reproduce the issue:**
1. create mysql server `mydb` and db `magento` (name genericized) w/ server admin set to `admin`
1. Run `helm upgrade -i my-release .` with the following configuration

requirements.yaml
```yaml
dependencies:
  - name: magento
    version: 3.3.0
    repository: https://kubernetes-charts.storage.googleapis.com # stable
```

values.yaml
```yaml
magento:
  magentoHost: shop.mydomain.com
  magentoUsername: magentoadmin
  magentoPassword: hunter22 # 8 characters + no specials
  magentoEmail: cmeyertons@mydomain.com
  magentoFirstName: carl
  magentoLastName: meyertons
  magentoMode: developer
  externalDatabase:
    host: mydb.mysql.database.azure.com
    port: 3306
    user: admin@mydb
    password: Hunter22!
    name: magento

  serviceType: ClusterIP
  persistence:
    magento:
      storageClass: managed-premium
    apache:
      storageClass: managed-premium
  mariadb:
    enabled: false

# have to do this because helm doesn't exclude the subchart w/o it, smh
mariadb:
  enabled: false
```

**Describe the results you received:**

Output from pod:
```
Welcome to the Bitnami magento container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-magento
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-magento/issues

nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
apache  INFO  ==> Configuring dummy certificates...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing libphp
nami    INFO  libphp successfully initialized
nami    INFO  Initializing magento
magento INFO  Preparing PHP environment...
magento INFO  Preparing webserver environment...
magento INFO  Preparing Magento environment...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mydb.mysql.database.azure.com:3306
mysql-c INFO  MySQL server listening and working at mydb.mysql.database.azure.com:3306
magento INFO  Installing Magento...
Error executing 'postInstallation':

  [InvalidArgumentException]
  Parameter validation failed


Exception trace:
 () at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Console/Command/InstallCommand.php:189
 Magento\Setup\Console\Command\InstallCommand->initialize() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Command/Command.php:207
 Symfony\Component\Console\Command\Command->run() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /opt/bitnami/magento/htdocs/vendor/magento/framework/Console/Cli.php:104
 Magento\Framework\Console\Cli->doRun() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /opt/bitnami/magento/htdocs/bin/magento:23

setup:install [--backend-frontname BACKEND-FRONTNAME] [--key KEY] [--db-host DB-HOST] [--db-name DB-NAME] [--db-user DB-USER] [--db-engine DB-ENGINE] [--db-password DB-PASSWORD] [--db-prefix DB-PREFIX] [--db-model DB-MODEL] [--db-init-statements DB-INIT-STATEMENTS] [-s|--skip-db-validation] [--http-cache-hosts HTTP-CACHE-HOSTS] [--session-saveSESSION-SAVE] [--session-save-redis-host SESSION-SAVE-REDIS-HOST] [--session-save-redis-port SESSION-SAVE-REDIS-PORT] [--session-save-redis-password SESSION-SAVE-REDIS-PASSWORD] [--session-save-redis-timeout SESSION-SAVE-REDIS-TIMEOUT] [--session-save-redis-persistent-id SESSION-SAVE-REDIS-PERSISTENT-ID] [--session-save-redis-db SESSION-SAVE-REDIS-DB] [--session-save-redis-compression-threshold SESSION-SAVE-REDIS-COMPRESSION-THRESHOLD] [--session-save-redis-compression-lib SESSION-SAVE-REDIS-COMPRESSION-LIB] [--session-save-redis-log-level SESSION-SAVE-REDIS-LOG-LEVEL] [--session-save-redis-max-concurrency SESSION-SAVE-REDIS-MAX-CONCURRENCY] [--session-save-redis-break-after-frontend SESSION-SAVE-REDIS-BREAK-AFTER-FRONTEND] [--session-save-redis-break-after-adminhtml SESSION-SAVE-REDIS-BREAK-AFTER-ADMINHTML] [--session-save-redis-first-lifetime SESSION-SAVE-REDIS-FIRST-LIFETIME] [--session-save-redis-bot-first-lifetime SESSION-SAVE-REDIS-BOT-FIRST-LIFETIME] [--session-save-redis-bot-lifetime SESSION-SAVE-REDIS-BOT-LIFETIME] [--session-save-redis-disable-locking SESSION-SAVE-REDIS-DISABLE-LOCKING] [--session-save-redis-min-lifetime SESSION-SAVE-REDIS-MIN-LIFETIME] [--session-save-redis-max-lifetime SESSION-SAVE-REDIS-MAX-LIFETIME] [--cache-backend CACHE-BACKEND] [--cache-backend-redis-server CACHE-BACKEND-REDIS-SERVER] [--cache-backend-redis-db CACHE-BACKEND-REDIS-DB] [--cache-backend-redis-port CACHE-BACKEND-REDIS-PORT] [--page-cache PAGE-CACHE] [--page-cache-redis-server PAGE-CACHE-REDIS-SERVER] [--page-cache-redis-db PAGE-CACHE-REDIS-DB] [--page-cache-redis-port PAGE-CACHE-REDIS-PORT] [--page-cache-redis-compress-data PAGE-CACHE-REDIS-COMPRESS-DATA] [--base-url BASE-URL] [--language LANGUAGE] [--timezone TIMEZONE] [--currency CURRENCY] [--use-rewrites USE-REWRITES] [--use-secure USE-SECURE] [--base-url-secure BASE-URL-SECURE] [--use-secure-admin USE-SECURE-ADMIN] [--admin-use-security-key ADMIN-USE-SECURITY-KEY] [--admin-user ADMIN-USER] [--admin-password ADMIN-PASSWORD] [--admin-email ADMIN-EMAIL] [--admin-firstname ADMIN-FIRSTNAME] [--admin-lastname ADMIN-LASTNAME] [--cleanup-database] [--sales-order-increment-prefix SALES-ORDER-INCREMENT-PREFIX] [--use-sample-data] [-i|--interactive] [--magento-init-params MAGENTO-INIT-PARAMS]
```

**Describe the results you expected:**

I expected magento to start up successfully

**Version**
Azure Kubernetes Service

**Comment by carrodher** [comment]
Hi @cmeyertons,

I just moved the issue to the `bitnami/charts` repository, because `bitnami/bitnami-docker-magento` is oriented to issues related to the Docker image.

Regarding the issue, in the `values.yaml` provided above, the `externalDatabase` section contains a parameter that is not valid:
```yaml
  externalDatabase:
    host: mydb.mysql.database.azure.com
    port: 3306
    user: admin@mydb
    password: Hunter22!
    name: magento
```
`externalDatabase.name` is not an existing parameter, the correct value should be `externalDatabase.database`. You can take a look at it in the chart repository:
https://github.com/bitnami/charts/blob/master/upstreamed/magento/values.yaml#L79

Can you try if this change solve your issue?
