### ISSUE TITLE
[bitnami/postgresql] How to pass extendedConfiguration to replication ?

### ISSUE THREAD

**Issue by d3ployment** [bitnami/charts#9472]
### Name and Version

bitnami/postgresql 11.0.2

### What steps will reproduce the bug?

1. Add Chart as a dependency :
```yaml
dependencies:
  - name: postgresql
    version: 11.0.2
    repository: ${PROXY_REPO_URL}
```
2. Use `architecture: replication` and `primary.extendedConfiguration`
```yaml
architecture: replication

primary:
  extendedConfiguration: |
    listen_addresses='0.0.0.0'
    port=5432
    max_connections=400
    shared_buffers='400MB'
    ...
```

### What do you see instead?

Note that those settings are only applied on primary and that no replication.extendedConfiguration is available  

Is it a bug or this feature isn't implemented yet ?
