### ISSUE TITLE
Wordpress Helm with externalDatabase and extraEnvVarsSecret

### ISSUE THREAD

**Issue by camilo-alice** [bitnami/charts#9477]
### Name and Version

bitnami/wordpress 

### What steps will reproduce the bug?

1. Environment: EKS ArgoCD bitnami/wordpress 13.0.13

### What do you see instead?

Hi! I have tried to configure the argocd application to deploy WordPress in EKS production environment. Inside the argocd application manifest, I configured the bitnami helm chart values and worked fine without external secrets. I have configured AWS secrets manager to store the WordPress variables:
```
MARIADB_HOST
WORDPRESS_DATABASE_USER
WORDPRESS_DATABASE_PASSWORD
WORDPRESS_DATABASE_NAME
```
The extraEnvVarsSecret works fine. The helm is able to create de secret inside WordPress namespace. I don’t know how to configure the `externalDatabase` variables to receive the extraEnvVarsSecret values. I have tried this configuration:
```yaml
    extraEnvVarsSecret: "wordpress-blog-db"
    
    env:
      - name: "ALLOW_EMPTY_PASSWORD"
        value: "yes"
    
    externalDatabase:
      host: ${MARIADB_HOST}
      user: ${WORDPRESS_DATABASE_USER}
      password: ${WORDPRESS_DATABASE_PASSWORD}
      database: ${WORDPRESS_DATABASE_NAME}
      port: 3306
```
But this configuration does not work.
Could you help me to fix this issue?
