### ISSUE TITLE
KEYCLOAK_FRONTEND_URL in `extraEnvVars` takes no effect

### ISSUE THREAD

**Issue by manhhailua** [bitnami/charts#9486]
### Name and Version

bitnami/keycloak 7.1.3

### What steps will reproduce the bug?

1. Install chart bitnami/keycloak with below values
2. Ensure `KEYCLOAK_FRONTEND_URL` is specified in `extraEnvVars`

### Are you using any custom parameters or values?

My custom values file:

```yaml
extraEnvVars:
  - name: KEYCLOAK_LOG_LEVEL
    value: DEBUG
  - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KEYCLOAK_FRONTEND_URL
    value: https://domain.com/auth

service:
  type: ClusterIP
```

### What is the expected behavior?

The frontend url of master realm should be configured with value: `https://domain.com/auth`

### What do you see instead?

The frontend url of master realm is actually empty.

### Additional information

Posible cause: `KEYCLOAK_FRONTEND_URL` is missing fom this file. [https://github.com/bitnami/bitnami-docker-keycloak/blob/master/16/debian-10/rootfs/opt/bitnami/scripts/keycloak-env.sh#L23-L73](https://github.com/bitnami/bitnami-docker-keycloak/blob/master/16/debian-10/rootfs/opt/bitnami/scripts/keycloak-env.sh#L23-L73)
