### ISSUE TITLE
[bitnami/redis] Latest master changes is not being reflected in the zip file

### ISSUE THREAD

**Issue by Mihirkumarsingh** [bitnami/charts#9498]
### Name and Version

bitnami/redis 16.5.4

### What steps will reproduce the bug?

- Get the latest helm chart for redis
- It is not having the latest master changes which were pushed in this PR https://github.com/bitnami/charts/pull/9452

### What do you see instead?

It is still having the bug(syntax issue)  `{` ,which was fixed in the PR https://github.com/bitnami/charts/pull/9452
```yaml
          emptyDir: {
             medium: {{ .Values.master.persistence.medium | quote }}
             {{- if .Values.master.persistence.sizeLimit }}
             sizeLimit: {{ .Values.master.persistence.sizeLimit | quote }}
             {{- end }}
           }
 ```
