### ISSUE TITLE
setting configurationConfigMap for spark results in image not loading.

### ISSUE THREAD

**Issue by 0xc0deface** [bitnami/charts#9505]
### Name and Version

bitnami/spark 5.9.4

### What steps will reproduce the bug?

set `spark.master.configurationConfigMap` to a config map and try installing. master will fail to start.

### Are you using any custom parameters or values?

```yaml
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: spark-defaults-cfg
data:
  # https://spark.apache.org/docs/latest/configuration.html
  spark-defaults.conf: |-
```

```yaml
spark:
  master:
    configurationConfigMap: spark-defaults-cfg
```

### What is the expected behavior?

The expected behavior is that the container still starts up correctly when config is set.

### What do you see instead?
```
/opt/bitnami/scripts/spark/entrypoint.sh: line 22: /opt/bitnami/spark/conf/spark-env.sh: Read-only file system
```
### Additional information

setting configurationConfigMap results in the conf directory being mounted as read only with the ConfigMap files in it. then entrypoint.sh will try and write spark-env.sh into there resulting in the error above.
