### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] Misssing CRD after helm chart upgrade

### ISSUE THREAD

**Issue by carlosjgp** [bitnami/charts#9513]
### Name and Version

bitnami/rabbitmq-cluster-operator:2.4.0

### What steps will reproduce the bug?

1. Install bitnami/rabbitmq-cluster-operator:2.0.0
2. Upgrade to bitnami/rabbitmq-cluster-operator:2.4.0
3. See Topology operator failing due to missing CRD SuperStream

### Are you using any custom parameters or values?

```yaml
fullnameOverride: rabbitmq-operator
clusterOperator:
  replicaCount: 2
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"

  priorityClassName: "system-cluster-critical"
  metrics:
    enabled: true
    service:
      annotations:
        ad.datadoghq.com/endpoint.check_names: |-
          ["prometheus"]
        ad.datadoghq.com/endpoint.init_configs: |-
          [{}]
        ad.datadoghq.com/endpoint.instances: |-
          [{
            "prometheus_url": "http://%%host%%:80/metrics",
            "namespace": "rabbitmq-cluster-operator",
            "metrics": [
              "*"
            ]
          }]

msgTopologyOperator:
  replicaCount: 2
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  priorityClassName: "system-cluster-critical"
  metrics:
    enabled: false
    service:
      annotations:
        ad.datadoghq.com/endpoint.check_names: |-
          ["prometheus"]
        ad.datadoghq.com/endpoint.init_configs: |-
          [{}]
        ad.datadoghq.com/endpoint.instances: |-
          [{
            "prometheus_url": "http://%%host%%:80/metrics",
            "namespace": "rabbitmq-topology-operator",
            "metrics": [
              "*"
            ]
          }]
useCertManager: true
```

### What is the expected behavior?

New CRDs and updated versions are applied when Helm upgrades to a new chart version

Are these relevant?
- https://github.com/helm/helm/issues/7735
- https://github.com/bitnami/charts/issues/8945

### What do you see instead?

CrashLoop on topology operator PODs due to missing CRDs Superstream
