### ISSUE TITLE
Grafana Helm Chart not pulling in extraenvvars?

### ISSUE THREAD

**Issue by DanPhonovation** [bitnami/charts#9555]
### Name and Version

bitnami/grafana 7.6.19

### What steps will reproduce the bug?

In my helm chart I have:

`extraEnvVarsSecret: "grafana-extraenvvars"`

As a result, I see the K8 deployment and pod manifest show:

```
      envFrom:
        - configMapRef:
            name: kannel-monitoring-grafana-envvars
        - secretRef:
            name: grafana-extraenvvars
```

The manifest looks like this:

```
apiVersion: v1
kind: Secret
metadata:
  name: grafana-extraenvvars
  namespace: monitoring
type: Opaque
stringData:
  extraEnvVars.yaml: |-
    extraEnvVars:
      - name: GF_PLUGINS_ENABLE_ALPHA
        value: true
      - name: GF_SERVER_ROOT_URL
        value: "https://monitor.mydomain.com"
```

However, Grafana doesn't seem to be picking this up as seen from the pods shell:

```
1001@monitoring-grafana-5744bd4968-4vf4f:/opt/bitnami/grafana$ env | grep GF
GF_AUTH_LDAP_ENABLED=false
GF_PATHS_PROVISIONING=/opt/bitnami/grafana/conf/provisioning
GF_SECURITY_ADMIN_PASSWORD=*******
GF_SECURITY_ADMIN_USER=admin
GF_AUTH_LDAP_CONFIG_FILE=/opt/bitnami/grafana/conf/ldap.toml
GF_PATHS_DATA=/opt/bitnami/grafana/data
GF_INSTALL_PLUGINS=
GF_PATHS_LOGS=/opt/bitnami/grafana/logs
GF_AUTH_LDAP_ALLOW_SIGN_UP=false
GF_PATHS_PLUGINS=/opt/bitnami/grafana/data/plugins
GF_PATHS_CONFIG=/opt/bitnami/grafana/conf/grafana.ini
```

### What is the expected behavior?

ENV variables are pulled in

### What do you see instead?

ENV variables not pulled in
