### ISSUE TITLE
[contour] No option to have the envoy service point external https to internal http, which is required for NLB use case

### ISSUE THREAD

**Issue by paul-civitas** [bitnami/charts#9582]
### Name and Version

bitnami/contour 7.4.4

### What steps will reproduce the bug?

In this article: https://projectcontour.io/guides/deploy-aws-tls-nlb/

The project contour team instructs how to set up contour behind a SSL terminating AWS network load balancer.

However looking at the example it defines an envoy service like this:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: projectcontour
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-2:185309785115:certificate/7610ed7d-5a81-4ea2-a18a-7ba1606cca3e"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 443
    targetPort: 80
    name: http
    protocol: TCP
  selector:
    app: envoy
  type: LoadBalancer
```

You can see they have port 443 pointing to port 80. This is because the NLB is terminating the SSL in this example.

However in the helm chart, there's no option to support this use case. the HTTPS port always points to the HTTPS target port.

There should be an option to have the HTTPS port point to the HTTP target port, in order to support this use case.

### What is the expected behavior?

That there would be an option to support this common use case, and that it wouldn't be absolutely mandatory to have contour handle HTTPS decryption.

### What do you see instead?

There's no option for this. The code looks like this:

```yaml
    - name: https
      port: {{ .Values.envoy.service.ports.https }}
      protocol: TCP
      targetPort: {{ .Values.envoy.containerPorts.https }}
      {{- if and (or (eq .Values.envoy.service.type "NodePort") (eq .Values.envoy.service.type "LoadBalancer")) (not (empty .Values.envoy.service.nodePorts.https)) }}
      nodePort: {{ .Values.envoy.service.nodePorts.https }}
      {{- else if eq .Values.envoy.service.type "ClusterIP" }}
      nodePort: null
```

Which shows that this can't be configured in the way instructed in the article.
