### ISSUE TITLE
Unable to configure archive_command in postgres

### ISSUE THREAD

**Issue by tropicallydiv** [bitnami/charts#9604]
### Name and Version

Postgres 11.

### What steps will reproduce the bug?

Trying to configure the archive command using the postgres helm charts

```yaml
postgresqlExtendedConf: |-
archive_timeout: 300
archive_command: 'test ! -f /backup/postgres/dev/pgm/archivedir/%f && cp %p /backup/postgres/dev/pgm/archivedir/%f'

```

Version:
```yaml
annotations:
  category: Database
apiVersion: v2
appVersion: 11.13.0
dependencies:
name: postgresql
sources:
  - https://github.com/bitnami/bitnami-docker-postgresql
  - https://www.postgresql.org/
version: 10.10.2
```

### What is the expected behavior?

Either  the values get updated in the postgresql conf file or a new configmap should be created.
Neither happened.

### What do you see instead?

was expecting the values to appear somewhere in /opt/bitanami/postgressql/conf
```

I have no name!@pgm-postgresql-0:/opt/bitnami/postgresql/conf$ grep -i archive *

grep: conf.d: Is a directory
postgresql.conf:#archive_mode = off             # enables archiving; off, on, or always
postgresql.conf:#archive_command = ''           # command to use to archive a logfile segment
postgresql.conf:                                # placeholders: %p = path of file to archive
postgresql.conf:                                # e.g. 'test ! -f /mnt/server/archivedir/%f && cp %p /mnt/server/archivedir/%f'
postgresql.conf:#archive_timeout = 0            # force a logfile segment switch after this
postgresql.conf:#max_standby_archive_delay = 30s        # max delay before canceling queries
postgresql.conf:                                        # when reading WAL from archive

```
### Additional information

Thank you for your time.
