### ISSUE TITLE
Kafka helm chart is not working when deployed with "tls.existingSecrets" configuration

### ISSUE THREAD

**Issue by GaneshbabuRamamoorthy** [bitnami/charts#9607]
### Name and Version

bitnami/kafka-16.1.2 with kafka docker image 3.1.0

### What steps will reproduce the bug?

Hi All,

I am trying to deploy latest [kafka helm chart](https://github.com/bitnami/charts/tree/master/bitnami/kafka) in my k8s environment and when I tried deployed we are getting the below error in pod logs,

```
[root@k8master1 bitnami]# kubectl get pods -n es
NAME                READY   STATUS             RESTARTS   AGE
kafka-0             0/1     CrashLoopBackOff   7          12m
kafka-1             0/1     CrashLoopBackOff   7          12m
kafka-zookeeper-0   1/1     Running            0          12m
[root@k8master1 bitnami]#
[root@k8master1 bitnami]# kubectl logs kafka-0 -n es -f
Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled.
[root@k8master1 bitnami]#
[root@k8master1 bitnami]# kubectl logs kafka-1 -n es -f
Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled.
```

I have used this [script ](https://raw.githubusercontent.com/confluentinc/confluent-platform-security-tools/master/kafka-generate-ssl.sh) to generate the jks certificates.

after certificates generation we followed the documentation for creating secrets in k8s and below is the command we used,

```
kubectl create secret generic kafka-certs-0 --from-file=kafka.truststore.jks=./kafka.truststore.jks --from-file=kafka.keystore.jks=./kafka-0.keystore.jks -n es
kubectl create secret generic kafka-certs-1 --from-file=kafka.truststore.jks=./kafka.truststore.jks --from-file=kafka.keystore.jks=./kafka-1.keystore.jks -n es

```
Once the secrets were created we have added the secret name in values.yaml like this,

```
  ## TLS configuration
  ##  
  tls:
    type: jks
    pemChainIncluded: false
    existingSecrets: ["kafka-certs-0", "kafka-certs-1"]
    autoGenerated: false
    password: "changeme"
    existingSecret: ""
    jksTruststoreSecret: ""
    jksKeystoreSAN: ""
    jksTruststore: ""
    endpointIdentificationAlgorithm: https
```

### Are you using any custom parameters or values?

Attached the values.yaml I have used in my helm chart.
[values.txt](https://github.com/bitnami/charts/files/8368917/values.txt)

### What do you see instead?

I am getting the below error in pod logs,

```
[root@k8master1 bitnami]# kubectl get pods -n es
NAME                READY   STATUS             RESTARTS   AGE
kafka-0             0/1     CrashLoopBackOff   10         30m
kafka-1             0/1     CrashLoopBackOff   10         30m
kafka-zookeeper-0   1/1     Running            0          30m
[root@k8master1 bitnami]#
[root@k8master1 bitnami]#
[root@k8master1 bitnami]# kubectl logs kafka-0 -n es -f
Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled.
[root@k8master1 bitnami]#
[root@k8master1 bitnami]# kubectl logs kafka-1 -n es -f
Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled.
```

When I describe the pod I could see the secrets added in existingSecrets parameter were mounted in /certs-0 & /certs-1 path,

![image](https://user-images.githubusercontent.com/20658619/160555351-8ae1d5c0-4a8e-4b6a-be9d-2fd58138e5ba.png)

### Additional information

I also tried looking into the other similar issues but didnt help to resolve the above issue. Please correct me If I am doing anything wrong in my setup.

https://github.com/bitnami/charts/issues/8593
https://github.com/bitnami/charts/issues/8856

Thanks,
Ganeshbabu R

**Comment by rafariossaa** [comment]
Hi,
  I think you need to set one of `interBrokerProtocol`, `tlsEncryption` or `externalClient.tlsEncryption` to `tls`.
Could you take a look to [this section](https://github.com/bitnami/charts/tree/master/bitnami/kafka#enable-security-for-kafka-and-zookeeper) ?  Maybe that information helps you to solve this issue.

**Comment by GaneshbabuRamamoorthy** [comment]
Hi @rafariossaa 

Thanks for sharing your thoughts and I have redeployed with the same values.yaml pods were running fine and kafka nodes were created successfully.

I have tried enabling kafka-exporter in the same values.yaml and below is the config I have added,

```
## Prometheus Exporters / Metrics
##
metrics:
  ## Prometheus Kafka exporter: exposes complimentary metrics to JMX exporter
  ##
  kafka:
    enabled: true
    image:
      registry: artifactory.dev.com
      repository: dev/kafka-exporter
      tag: 1.4.2
      pullPolicy: IfNotPresent
      pullSecrets:
        - artifactory-registry
    certificatesSecret: "kafka-certs-0"
    tlsCert: kafka.truststore.jks
    tlsKey: kafka.keystore.jks
    tlsCaSecret: ""
    tlsCaCert:
    extraFlags:
      tls.insecure-skip-tls-verify: ""
```

Below is the kafka-exporter pod describe,
```
Containers:
  kafka-exporter:
    Container ID:  docker://944a7c097b8baae5e0f1b43665329cd4edb692d5ca5a24647a29f15532712632
    Image:         artifactory.dev.com/dev/kafka-exporter:1.4.2
    Image ID:      docker-pullable://artifactory.dev.com/dev/kafka-exporter@sha256:0c1187265da44b3faa971ed4c928cd4f8663d72248bca8cf0
    Port:          9308/TCP
    Host Port:     0/TCP
    Command:
      kafka_exporter
    Args:
      --kafka.server=kafka-0.kafka-headless.es.svc.cluster.local:9092
      --kafka.server=kafka-1.kafka-headless.es.svc.cluster.local:9092
      --tls.enabled
      --tls.key-file=/opt/bitnami/kafka-exporter/certs/kafka.keystore.jks
      --tls.cert-file=/opt/bitnami/kafka-exporter/certs/kafka.truststore.jks
      --tls.ca-file=/opt/bitnami/kafka-exporter/certs/
      --tls.insecure-skip-tls-verify
      --web.listen-address=:9308

```

```
[root@k8master1 bitnami]# kubectl logs kafka-exporter-7dd5d78887-8r22c -n es
I0329 11:51:01.670657       1 kafka_exporter.go:769] Starting kafka_exporter (version=1.4.2, branch=non-git, revision=non-git)
F0329 11:51:01.671177       1 kafka_exporter.go:865] read /opt/bitnami/kafka-exporter/certs/: is a directory
```

What is the value I should provide in tls.ca-file ?

When I tried giving **ca-file as kafka.truststore.jks** below is the error I am getting,

```
[root@k8master1 bitnami]# kubectl logs kafka-exporter-76b77df5f8-bvvkf -n es -f
I0329 12:08:19.600421       1 kafka_exporter.go:769] Starting kafka_exporter (version=1.4.2, branch=non-git, revision=non-git)
F0329 12:08:19.600936       1 kafka_exporter.go:865] tls: failed to find any PEM data in certificate input
```


kindly share your thoughts on the above setup and correct me If I am doing anything wrong.

Thanks,
Ganeshbabu R

**Comment by joancafom** [comment]
Hi! I am currently taking a look into the issue and will provide you with further comments soon.

**Comment by joancafom** [comment]
Hi @GaneshbabuRamamoorthy !

I will try to answer your question, but before let's start with the basics. As described in the [Enable security for Kafka and Zookeeper](https://github.com/bitnami/charts/tree/master/bitnami/kafka#enable-security-for-kafka-and-zookeeper) section from the README, the Bitnami Kafka Helm Chart can be configured with different encryption/authentication protocols. In particular, you can configure your deployment to use either `tls` or `mtls`, for communication **among brokers**, **clients** and/or **external clients**:

- **TLS** (encryption only): The Kafka server will encrypt its communications with TLS, using assymetric cryptography. Peers **can** validate the identity of the server, **if desired.**
- **mTLS** (a.k.a **Mutual TLS**; encryption & authentication): Not only will the Kafka server encrypt its communication using TLS, but will require peers to do it as well. Peers will have to provide proof of their identity, which Kafka will validate.

--- 

Having said that, let's focus on your setup.  You've configured your deployment to use `tls` for client communications, which of course includes `kafka-exporter`. 

By default, when TLS is enabled, `kafka-exporter` will attempt **to validate the Kafka server identity**, which requires to provide the CA certificate. Alternatively, you can skip this verification by setting the `tls.insecure-skip-tls-verify: ""` extraFlag in your deployment. For example, this is a totally valid set up which works as expected for me:

```yaml
replicaCount: 2
auth:
  interBrokerProtocol: tls
  clientProtocol: tls
  tls:
    type: jks
    existingSecrets:
      - "kafka-tls-0"
      - "kafka-tls-1"
    password: "changeme"
metrics:
  kafka:
    enabled: true
    extraFlags:
      tls.insecure-skip-tls-verify: "" 
```

On the other hand, if you'd like to keep the default behaviour and validate the Kafka's server identity, you will need to provide the CA certificate. However, as you are not using `mTLS`, there is no need to provide a client cerificate & key: the server will not attempt to verify the clients!

`kafka-exporter` expects certificates in PEM format. You can export the CA certificate from one of the created keystores using this command:

```bash
$ keytool -export -alias caroot -file ca-root.crt -keystore kafka-0.keystore.jks
```

Then create a secret based on it:

```
$ kubectl create secret generic exporter-tls --from-file=ca-file=ca-root.crt
```

Finally, another functional set up that works as expected:

```yaml
replicaCount: 2
auth:
  interBrokerProtocol: tls
  clientProtocol: tls
  tls:
    type: jks
    existingSecrets:
      - "kafka-tls-0"
      - "kafka-tls-1"
    password: "changeme"
metrics:
  kafka:
    enabled: true
    certificatesSecret: "exporter-tls"
```

I could not find any problems, except when neither of the CA certificate nor the `insecure-skip-tls-verify` flag is provided (which is not a valid a scenario).
