### ISSUE TITLE
Ruler config is trying to solve variables

### ISSUE THREAD

**Issue by TheMatrix97** [bitnami/charts#9621]
### Name and Version

bitnami/thanos 10.3.0

### What steps will reproduce the bug?

When defining a ruler configuration under ruler.config, it seems is trying to solve the variables inside, obviously, are prometheus and return an undefined variable error

### Are you using any custom parameters or values?

```yaml
  ...
  ruler:
    enabled: true
    logLevel: debug
    evalInterval: 30s
    clusterName: "testing"
    alertManagers:
      - http://prometheus-alertmanager:80
    config: |-
      groups:
      - name: metamonitoring
        rules:
        - alert: PrometheusReplicaDown
          annotations:
            message: Prometheus replica in cluster {{$labels.cluster}} has disappeared from Prometheus target discovery.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-prometheusdown
          expr: |
            label_replace(
              absent(sum(up{job="prometheus", cluster="testing", instance=~".*:9090"}) by (job, cluster) == 1),
              "cluster", "testing", "",""
            )
          for: 5m # for demo purposes, typically 5m is a fine number.
 ...
```

### What is the expected behavior?

I'm expecting to automatically create and populate a configmap without trying to solve the variables inside

### What do you see instead?

````
Error: INSTALLATION FAILED: template: thanos/charts/thanos/templates/ruler/statefulset.yaml:40:41: executing "thanos/charts/thanos/templates/ruler/statefulset.yaml" at <include (print $.Template.BasePath "/ruler/configmap.yaml") .>: error calling include: template: thanos/charts/thanos/templates/ruler/configmap.yaml:17:8: executing "thanos/charts/thanos/templates/ruler/configmap.yaml" at <include "common.tplvalues.render" (dict "value" .Values.ruler.config "context" $)>: error calling include: template: thanos/charts/thanos/charts/common/templates/_tplvalues.tpl:9:12: executing "common.tplvalues.render" at <tpl .value .context>: error calling tpl: error during tpl function execution for "groups:\n- name: metamonitoring\n  rules:\n  - alert: PrometheusReplicaDown\n    annotations:\n      message: Prometheus replica in cluster {{$labels.cluster}} has disappeared from Prometheus target discovery.\n      runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-prometheusdown\n    expr: |\n      label_replace(\n        absent(sum(up{job=\"prometheus\", cluster=\"testing\", instance=~\".*:9090\"}) by (job, cluster) == 1),\n        \"cluster\", \"testing\", \"\",\"\"\n      )\n    for: 5m # for demo 
purposes, typically 5m is a fine number.\n    ": parse error at (thanos/charts/thanos/templates/ruler/statefulset.yaml:6): undefined variable "$labels"
````

### Additional information

Actually, some other people solved this creating a configmap manually and then using the existingConfigMap. I don't like this solution, hence I would rather centralize all the configuration in a single Values file
https://github.com/thanos-io/thanos/issues/3386 

Thanks!
