### ISSUE TITLE
Error while trying to install prometheus

### ISSUE THREAD

**Issue by oktayalizada** [bitnami/charts#9624]
### Name and Version

bitnami/prometheus:2.33.5-debian-10-r19

### What steps will reproduce the bug?

When trying to install 
` helm install prom -f prometheus.yaml bitnami/kube-prometheus`

### Are you using any custom parameters or values?

```yaml
prometheus:
  enabled: true
  replicaCount: 3
  image:
      tag: 2.33.5-debian-10-r19
  service:
      nodePort: 32323
  persistance:
      enabled: true
      size: 50Gi
rbac:
  apiVersion: v1
```

### What is the expected behavior?

Helm installed successfully

### What do you see instead?

`Error:INSTALLATION FAILED: podsecuritypolicies.policy is forbidden: User "u-sss" cannot create resource "podsecuritypolicies" in API group "policy" at the cluster scope`
