### ISSUE TITLE
Rabbitmq: $NODE_PORT_AMQP points to epmd port

### ISSUE THREAD

**Issue by rjgildea** [bitnami/charts#9629]
### Name and Version

bitnami/rabbitmq 8.30.3

### What steps will reproduce the bug?

Chart installed with:
`helm install rabbits bitnami/rabbitmq -f values.yaml`

gives the following output:
```
To access for outside the cluster, perform the following steps:

Obtain the NodePort IP and ports:

    export NODE_IP=$(kubectl get nodes --namespace <NAMESPACE> -o jsonpath="{.items[0].status.addresses[0].address}")
    export NODE_PORT_AMQP=$(kubectl get --namespace <NAMESPACE> -o jsonpath="{.spec.ports[1].nodePort}" services rabbits-rabbitmq)
    export NODE_PORT_STATS=$(kubectl get --namespace <NAMESPACE> -o jsonpath="{.spec.ports[3].nodePort}" services rabbits-rabbitmq)

To Access the RabbitMQ AMQP port:

    echo "URL : amqp://$NODE_IP:$NODE_PORT_AMQP/"

To Access the RabbitMQ Management interface:

    echo "URL : http://$NODE_IP:$NODE_PORT_STATS/"

To access the RabbitMQ Prometheus metrics, get the RabbitMQ Prometheus URL by running:

    kubectl port-forward --namespace <NAMESPACE> svc/rabbits-rabbitmq 9419:9419 &
    echo "Prometheus Metrics URL: http://127.0.0.1:9419/metrics"

Then, open the obtained URL in a browser.
```
However, following the above instructions gives the incorrect port for `$NODE_PORT_AMQP`:
```
$ kubectl get -o jsonpath="{.spec.ports[1].nodePort}" services rabbits-rabbitmq
30044
```
As shown by the full list of `.spec.ports` it gives the `epmd` port (`.spec.ports[1]`) rather than the `amqp` port (`.spec.ports[0].`):
```
$ kubectl get -o jsonpath="{.spec.ports}" services rabbits-rabbitmq | jq
[
  {
    "name": "amqp",
    "nodePort": 32679,
    "port": 5672,
    "protocol": "TCP",
    "targetPort": "amqp"
  },
  {
    "name": "epmd",
    "nodePort": 30044,
    "port": 4369,
    "protocol": "TCP",
    "targetPort": "epmd"
  },
  {
    "name": "dist",
    "nodePort": 30284,
    "port": 25672,
    "protocol": "TCP",
    "targetPort": "dist"
  },
  {
    "name": "http-stats",
    "nodePort": 30773,
    "port": 15672,
    "protocol": "TCP",
    "targetPort": "stats"
  },
  {
    "name": "metrics",
    "nodePort": 31784,
    "port": 9419,
    "protocol": "TCP",
    "targetPort": "metrics"
  }
]
```

### Are you using any custom parameters or values?

values.yaml:
```yaml
persistence:
  enabled: true
metrics:
  enabled: true
plugins: rabbitmq_management
communityPlugins: "https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.9.0/rabbitmq_delayed_message_exchange-3.9.0.ez"
extraPlugins: rabbitmq_delayed_message_exchange
clustering:
  enabled: false
rbac:
  create: false
podSecurityContext:
  enabled: false
serviceAccount:
  create: false
service:
  type: NodePort
extraConfiguration: |-
  default_vhost = foo
  load_definitions = /app/load_definition.json
loadDefinition:
  enabled: true
  existingSecret: rabbitmq-load-definition
```

### What is the expected behavior?

Following the instructions to set the `$NODE_PORT_AMQP` variable should give the correct port.

### What do you see instead?

After following the instructions, `$NODE_PORT_AMQP` points to the `epmd` port, _not_ the `amqp` port.
