### ISSUE TITLE
Errors in Grafana Deployment pod

### ISSUE THREAD

**Issue by rodrigoscferraz** [bitnami/charts#9630]
### Name and Version

bitnami/grafana-operator 1.4.4

### What steps will reproduce the bug?

Just a fresh install of the Operator and a simple Grafana kind deployment

### Are you using any custom parameters or values?

```yaml
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
spec:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "efs"
  dashboardLabelSelector:
  - matchLabels:
      app: grafana
```

### What do you see instead?

```
t=2022-03-28T23:21:22+0000 lvl=eror msg="Failed to read plugin provisioning files from directory" logger=provisioning.plugins path=/opt/bitnami/grafana/conf/provisioning/plugins error="open /opt/bitnami/grafana/conf/provisioning/plugins: no such file or directory"
t=2022-03-28T23:21:22+0000 lvl=eror msg="Can't read alert notification provisioning files from directory" logger=provisioning.notifiers path=/opt/bitnami/grafana/conf/provisioning/notifiers error="open /opt/bitnami/grafana/conf/provisioning/notifiers: no such file or directory"
t=2022-03-28T23:21:22+0000 lvl=eror msg="can't read dashboard provisioning files from directory" logger=provisioning.dashboard path=/opt/bitnami/grafana/conf/provisioning/dashboards error="open /opt/bitnami/grafana/conf/provisioning/dashboards: no such file or directory"
```

### Additional information

I also have some Grafana Dashboards and Grafana Datasets CR... but what is strange is that everything is working, the dashboards, the datasets, but the grafana pod remains showing these error messages.
