### ISSUE TITLE
[bitnami/redis] <defunct> readiness and liveness probe processes

### ISSUE THREAD

**Issue by dominik-bln** [bitnami/charts#9654]
### Name and Version

bitnami/redis 16.7.0

### What steps will reproduce the bug?

I have no clear reproduction, but the problem we are seeing is likely to be explained in https://github.com/containerd/containerd/issues/4255#issuecomment-629108343

Currently the `timeoutSeconds` is passed [as-is to the `timeout` call](https://github.com/bitnami/charts/blob/9d8c4321830d01bbb2ffeef57054c1ff0e463d8a/bitnami/redis/templates/health-configmap.yaml#L20) in the `ping_readiness_*` probes. This means that Kubernetes will very likely kill the probe before the subprocess runs into the timeout.

I'd guess that the timeout passed to the probe scripts as done here https://github.com/bitnami/charts/blob/b87abf31902fd1d47fbfec8f529628c28f7a33ca/bitnami/redis/templates/master/application.yaml#L214 would need to be a little smaller than the setting of `timeoutSeconds`, e. g. something like:

`(max 1 (sub .Values.master.readinessProbe.timeoutSeconds 1))`

### Are you using any custom parameters or values?

```yaml
global:
  storageClass: rbd-csi
image:
  tag: 6.0.3-debian-10-r7
usePassword: true
password: 'redis'
persistence:
  enabled: true
  size: 1Gi
cluster:
  enabled: false
master:
  livenessProbe:
    periodSeconds: 30
  readinessProbe:
    periodSeconds: 15
resources:
  limits:
    cpu: "1000m"
    memory: "4Gi"
  requests:
    cpu: "100m"
    memory: "256Mi"
```

### What is the expected behavior?

Defunct processes should be reaped.

### What do you see instead?

```bash
1001      302743  0.0  0.0      0     0 ?        Z    02:10   0:00 [ping_readiness_] <defunct>
1001      430238  0.0  0.0      0     0 ?        Z    Mar31   0:00 [ping_readiness_] <defunct>
1001      569290  0.0  0.0      0     0 ?        Z    03:00   0:00 [ping_readiness_] <defunct>
1001     2690564  0.0  0.0      0     0 ?        Z    09:03   0:00 [ping_readiness_] <defunct>
1001     2691462  0.0  0.0      0     0 ?        Z    09:03   0:00 [ping_readiness_] <defunct>
1001     2691577  0.0  0.0      0     0 ?        Z    09:03   0:00 [ping_readiness_] <defunct>
1001     2692016  0.0  0.0      0     0 ?        Z    09:03   0:00 [ping_readiness_] <defunct>
```

### Additional information

We recently update our cluster to Kubernetes `v1.23` without dockershim and haven't seen this behaviour before this change.

**Comment by fmulero** [comment]
Thanks a lot @dominik-bln  for sharing this issue. Would you like to contribute by creating a PR with your proposal? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

Please note that you can test your solution setting a `customLivenessProbe`

**Comment by dominik-bln** [comment]
While trying to make the suggested change, I saw that someone else apparently already had the same idea with a slightly different fix using `add1`:

https://github.com/bitnami/charts/blob/2fff81ca29efc1ee0e3988998834541012a34b19/bitnami/redis/templates/master/application.yaml#L191-L192

I'm a bit confused now why we still saw this problem. The only idea I currently have is that we had a brief situation where the `1s` was not enough to guarantee this, but it's a bit odd. I'll try to see if I can find a better explanation, otherwise I think this issue can be closed since it might have been just a fluke with our cluster and not a general problem.

**Comment by fmulero** [comment]
Thanks @dominik-bln. Could you do a simple test? Please set the `master.readinessProbe.timeoutSeconds` and `master.livenessProbe.timeoutSeconds`. For example use this `values.yaml`:
```yaml
global:
  storageClass: rbd-csi
image:
  tag: 6.0.3-debian-10-r7
usePassword: true
password: 'redis'
persistence:
  enabled: true
  size: 1Gi
cluster:
  enabled: false
master:
  livenessProbe:
    periodSeconds: 30
    timeoutSeconds: 10
  readinessProbe:
    periodSeconds: 15
    timeoutSeconds: 10
resources:
  limits:
    cpu: "1000m"
    memory: "4Gi"
  requests:
    cpu: "100m"
    memory: "256Mi"
```
