### ISSUE TITLE
volumePermissions container not fixes permissions, still get Permission denied at startup

### ISSUE THREAD

**Issue by jnt2007** [bitnami/charts#9690]
### Name and Version

bitnami/kafka 16.2.2

### What steps will reproduce the bug?

1. Amazon EKS with EBS CSI driver
2. `helm install kafka bitnami/kafka -f kafka.yaml -n test --create-namespace`
3. Check Kafka pods logs

### Are you using any custom parameters or values?

kafka.yaml
```
logPersistence:
  enabled: true
  storageClass: ebs-sc-anton
persistence:
  enabled: true
  storageClass: ebs-sc-anton
volumePermissions:
  enabled: true
zookeeper:
  persistence:
    enabled: true
    storageClass: ebs-sc-anton
  volumePermissions:
    enabled: true
```

### What is the expected behavior?

Kafka and zookeeper pods are running with no errors

### What do you see instead?

```
$ kubectl -n test get po
NAME                READY   STATUS             RESTARTS   AGE
kafka-0             0/1     CrashLoopBackOff   6          10m
kafka-zookeeper-0   0/1     CrashLoopBackOff   6          10m
```

### Additional information

volume-permissions container has no log entries
```
$ kubectl -n test logs kafka-0 volume-permissions 
$
```

Kafka pod logs
```
kafka 17:01:25.55 
kafka 17:01:25.55 Welcome to the Bitnami kafka container
kafka 17:01:25.55 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
kafka 17:01:25.55 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
kafka 17:01:25.55 
kafka 17:01:25.55 INFO  ==> ** Starting Kafka setup **
kafka 17:01:25.61 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
mkdir: cannot create directory '/bitnami/kafka/config': Permission denied
```

Zookeeper pod logs
```
zookeeper 17:08:59.57 
zookeeper 17:08:59.57 Welcome to the Bitnami zookeeper container
zookeeper 17:08:59.57 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-zookeeper
zookeeper 17:08:59.57 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-zookeeper/issues
zookeeper 17:08:59.57 
zookeeper 17:08:59.58 INFO  ==> ** Starting ZooKeeper setup **
zookeeper 17:08:59.59 WARN  ==> You have set the environment variable ALLOW_ANONYMOUS_LOGIN=yes. For safety reasons, do not use this flag in a production environment.
mkdir: cannot create directory '/bitnami/zookeeper/data': Permission denied
```
