### ISSUE TITLE
[bitnami/prometheus] `tls-secrets.yaml` template is invalid due to indentation issues

### ISSUE THREAD

**Issue by itaytalmi** [bitnami/charts#9696]
### Name and Version

bitnami/prometheus 6.8.6

### What steps will reproduce the bug?

The `tls-secrets.yaml` template has indentation issues.
https://github.com/bitnami/charts/blob/master/bitnami/kube-prometheus/templates/prometheus/tls-secrets.yaml#L10#L11
`data` and `type` shouldn't be under `metadata`.

It should be:

```yaml
{{- if and .Values.prometheus.enabled .Values.prometheus.ingress.enabled }}
{{- if .Values.prometheus.ingress.secrets }}
{{- range .Values.prometheus.ingress.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "kube-prometheus.prometheus.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .certificate | b64enc }}
  tls.key: {{ .key | b64enc }}
```

### Are you using any custom parameters or values?

Irrelevant

### What is the expected behavior?

A secret should be created for ingress.

### What do you see instead?

```bash
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Secret.metadata): unknown field "data" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta, ValidationError(Secret.metadata): unknown field "type" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta]
```
