### ISSUE TITLE
[redis] PDB differenciate master/replica

### ISSUE THREAD

**Issue by stephaneetje** [bitnami/charts#9698]
### Name and Version

bitnami/redis

### What steps will reproduce the bug?

Actually, master and replicas are in the same pdb, thats problematic as it shouldn't be treated the same way.

I have 1 master and 2 replicas, as the pdb considers the 3 pods being in the same group, it kills the master (then i lose the connection on the replicas -> downtime on my app) as it considers i have 2 other pods running.
There should be 1 pdb for masters targeting only masters 
One pdb for replicas targeting only replicas.

That would give the possibility to get no downtime on masters when you only have one.

### Are you using any custom parameters or values?
```
redis:
    enabled: true
    commonConfiguration: maxmemory 2gb
    pdb:
        create: true
        maxUnavailable: 0
    auth:
        enabled: false
    replica:
        replicaCount: 2
    sentinel:
        enabled: false
```

<img width="716" alt="Capture d’écran 2022-04-06 à 11 16 17" src="https://user-images.githubusercontent.com/73826402/161941324-8c233d58-367d-4acc-b879-bb4b1b293dd7.png">
