### ISSUE TITLE
Replica can't connect to master, Unable to connect to MASTER: Invalid argument

### ISSUE THREAD

**Issue by thomastvedt** [bitnami/charts#9714]
### Name and Version

bitnami/redis 16.8.0

### What steps will reproduce the bug?

1. Install redis with no persistence, as Deployment and with values below
2. redis-master works
3. redis-replicas-0 can't contact redis-master

### Are you using any custom parameters or values?

values.yaml:

```yml
image:
  registry: docker.io
  repository: bitnami/redis
  tag: 6.2.6-debian-10-r169
  pullPolicy: IfNotPresent

architecture: replication
auth:
  enabled: true
  password: ""
  usePasswordFiles: false

master:
  disableCommands:
    - FLUSHDB
    - FLUSHALL
  containerPorts:
    redis: 6379
  startupProbe:
    enabled: true
    failureThreshold: 20 # Will give redis longer time to boot
  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 20
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: false
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
  kind: Deployment
  persistence:
    enabled: false
  service:
    type: LoadBalancer
    ports:
      redis: 6379
    externalTrafficPolicy: Cluster
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  terminationGracePeriodSeconds: 30

replica:
  replicaCount: 2
  disableCommands:
    - FLUSHDB
    - FLUSHALL
  startupProbe:
    enabled: true
    failureThreshold: 20 # Will give redis longer time to boot
  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 20
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: false
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
  persistence:
    enabled: false
  service:
    type: ClusterIP
    ports:
      redis: 6379
    externalTrafficPolicy: Cluster
  terminationGracePeriodSeconds: 30
  autoscaling:
    enabled: false

sentinel:
  enabled: false

tls:
  enabled: false

metrics:
  enabled: false

```

command:

```shell

$ helm upgrade redis bitnami/redis -f values.yml --install --debug --namespace redis --create-namespace --set auth.password=zzz
```

### What is the expected behavior?

Expected master and replica to work OOTB.

### What do you see instead?

log from redis-replicas-0:

```shell 
1:S 06 Apr 2022 20:20:09.541 * Connecting to MASTER redis-master-0.redis-headless.redis.svc.cluster.local:6379
1:S 06 Apr 2022 20:20:09.548 # Unable to connect to MASTER: Invalid argument
1:S 06 Apr 2022 20:20:10.550 * Connecting to MASTER redis-master-0.redis-headless.redis.svc.cluster.local:6379
1:S 06 Apr 2022 20:20:10.552 # Unable to connect to MASTER: Invalid argument
````

listing services:
```shell
$ k get svc --namespace redis
NAME                TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)          AGE
redis-headless      ClusterIP      None            <none>          6379/TCP         44m
redis-master        LoadBalancer   10.164.38.198   10.164.16.255   6379:30536/TCP   44m
redis-replicas      ClusterIP      10.164.38.54    <none>          6379/TCP         44m
```

The replica node can't contact `redis-master-0.redis-headless.redis.svc.cluster.local`, but this is the wrong service name?? See pings below from another node in the cluster:

```shell
~ $ ping redis-master-0.redis-headless.redis.svc.cluster.local
ping: bad address 'redis-master-0.redis-headless.redis.svc.cluster.local'
~ $ ping redis-master
PING redis-master (10.164.38.198): 56 data bytes
~ $ ping redis-master.redis.svc.cluster.local
PING redis-master.redis.svc.cluster.local (10.164.38.198): 56 data bytes
```

### Additional information

It worked when persistence was enabled, but we decided to disable persistence and change from StatefulSet to Deployment. The error occurred after this.
