### ISSUE TITLE
[bitnami/mariadb-galera] specifying metrics.servicemonitor.selector also adds default value

### ISSUE THREAD

**Issue by m-guest** [bitnami/charts#9740]
### Name and Version

bitnami/mariadb-galera 7.1.6

### What steps will reproduce the bug?

1. Deploy chart with custom values as below (`metrics.serviceMonitor.enabled` + `metrics.serviceMonitor.selector`)
2. Check k8s `ServiceMonitor` `galera-mariadb-galera`

### Are you using any custom parameters or values?

```yaml
metrics:
  serviceMonitor:
    enabled: true
    selector:
      app.kubernetes.io/part-of: "test_project"
```

### What is the expected behavior?

Deploy `ServiceMonitor` without adding the default value to `spec.selector.matchLabels`, as we set a custom value.

Note: adding of `common.labels.matchLabels` (instance+name) is OK as expected.

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
...
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: galera
      app.kubernetes.io/name: mariadb-galera
      app.kubernetes.io/part-of: test_project
```

### What do you see instead?

ServiceMonitor has `prometheus: kube-prometheus` added, even if we specified a custom value.

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
...
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: galera
      app.kubernetes.io/name: mariadb-galera
      app.kubernetes.io/part-of: test_project
      prometheus: kube-prometheus
```

### Additional information

This prevents correctly fetching the `Service` by `ServiceMonitor`, if `prometheus: kube-prometheus` tag is not used on `Service`.
