### ISSUE TITLE
wordpress: changing database host does not adopt wp-config

### ISSUE THREAD

**Issue by EugenMayer** [bitnami/charts#9765]
### Name and Version

bitname/wordpress-13.1.15

### What steps will reproduce the bug?

- deploy a wordpress chart with database host 1.2.3.4 and get it running
- change the database host in the helm chart to 4.3.2.1 and deploy
- the wordpress instance will never be able to connect to the database, since 1.2.3.4 is still used

### Are you using any custom parameters or values?

no

### What is the expected behavior?

update the database host

### What do you see instead?

old database host

### Additional information

- we are using an external databae (mariadb-galera cluster)

```yaml
global:
  storageClass: longhorn

image:
  debug: false

service:
  type: ClusterIP

replicaCount: 1
updateStrategy:
  type: Recreate
  rollingUpdate:

persistence:
  storageClass: longhorn
  size: 5Gi
  accessModes:
    - ReadWriteOnce

#volumePermissions:
#  enabled: true
mariadb:
  enabled: false

externalDatabase:
  existingSecret: ${external_db_secret}
  database: ${db_name}
  port: ${db_port}
  host: ${db_host}
  user: ${db_user}

resources:
  limits: {}
  requests:
    memory:
    cpu:

memcached:
  enabled: true

wordpressSkipInstall: true
wordpressScheme: https
wordpressAutoUpdateLevel: tue
wordpressUsername: <redacted>
wordpressEmail: <redacted>
wordpressPassword: "<redacted>"
allowEmptyPassword: false
wordpressConfigureCache: false
```
