### ISSUE TITLE
password authentication failed for user "bn_keycloak"

### ISSUE THREAD

**Issue by michas2** [bitnami/charts#9795]
### Name and Version

bitnami/keycloak 7.1.14

### What steps will reproduce the bug?

I install the chart without any special parameters.

### Are you using any custom parameters or values?

```yaml
proxyAddressForwarding: true
ingress:
  enabled: true
  hostname: keycloak.eks.my-domain.net
service:
  type: ClusterIP
```

### What is the expected behavior?

keycloak should be able to connect to the created database and startup.

### What do you see instead?

The `keycloak-0` pod crashes because it is not able to connect to the database.
The log of `keycloak-postgresql-0` shows:
```
2022-04-13 19:54:02.552 GMT [601] FATAL:  password authentication failed for user "bn_keycloak"
2022-04-13 19:54:02.552 GMT [601] DETAIL:  Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
```

**Comment by michas2** [comment]
The `keycloak-postgresql-0` pod contains:
```
    - name: POSTGRES_USER
      value: bn_keycloak
    - name: POSTGRES_POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgres-password
          name: keycloak-postgresql
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: keycloak-postgresql
```

For debugging I started a new postgresql pod:
```
$ kubectl get secret keycloak-postgresql -o json | jq '.data|map_values(@base64d)'
{
  "password": "jVf43g0jBw",
  "postgres-password": "iQlexIqGIV"
}
$ k run pg --image=postgres -it --rm -- bash
If you don't see a command prompt, try pressing enter.
root@pg:/# PGPASSWORD=jVf43g0jBw psql -h keycloak-postgresql -U bn_keycloak
psql: error: connection to server at "keycloak-postgresql" (172.20.22.125), port 5432 failed: FATAL:  password authentication failed for user "bn_keycloak"
```
