### ISSUE TITLE
Cannot setup postgresql in bitnami/odoo 21.2.7

### ISSUE THREAD

**Issue by ruddy32** [bitnami/charts#9796]
### Name and Version

bitnami/odoo 21.2.7

### What steps will reproduce the bug?

Deploy bitnami/odoo helm chart on kubernetes 1.18.20 using helm 3.8.1 and kubectl 1.23.5.

### Are you using any custom parameters or values?

I'm using specific container security context for postgresql subchart :
```
  postgresql:
    persistence:
      enabled: true
    volumePermissions:
      enabled: true
      containerSecurityContext:
        runAsGroup: 1001
        runAsUser: 0
...
    primary:
      containerSecurityContext:
        enabled: true
        runAsGroup: 1001
        runAsUser: 1001
...
```

### What is the expected behavior?

Create postgresql configuration file and start the database engine.

### What do you see instead?

ls command on /bitnami/pstgresql folder added at the end of the init-container command show following logs :
```
odoo-test-postgresql-0:init-chmod-data drwx--S--- 2 1001 1001 4.0K Apr 13 18:45 data
odoo-test-postgresql-0:init-chmod-data drwxrws--- 2 root 1001  16K Apr 13 18:45 lost+found
```
Then postgresql container show following logs :
```
odoo-test-postgresql-0:postgresql /opt/bitnami/scripts/libpostgresql.sh: line 222: /opt/bitnami/postgresql/conf/pg_hba.conf: Permission denied
odoo-test-postgresql-0:postgresql /opt/bitnami/scripts/libfile.sh: line 39: /opt/bitnami/postgresql/conf/postgresql.conf: Permission denied
```
