### ISSUE TITLE
[bitnami/redis] Replica.conf contains unaddressible URLs

### ISSUE THREAD

**Issue by colemanserious** [bitnami/charts#9798]
### Name and Version

bitnami/redis 16.8.5

### What steps will reproduce the bug?

1.  Deployed to k8s 1.21
2. Used values.yaml below, deployed with name as rules-cache
3. Interacted with Redis via Lettuce, and attempted to have it ReadFrom.REPLICA_PREFERRED

In investigating, discovered that ROLE was showing the replica addresses as: 
* rules-cache-redis-replicas-0.
* rules-cache-redis-replicas-1.

Those are unaddressable in k8s.  The pods created for the replicas have a subdomain of rules-cache-redis-headless, which means that the correct addresses would be rules-cache-redis-replicas-0.rules-cache-redis-headless and rules-cache-redis-replicas-1.rules-cache-redis-headless

This does NOT affect replication, since the replicas can still reach the master, but appears to impact the ability to identify nodes as replicas or masters.

### Are you using any custom parameters or values?

Very simple standalone replication.  
```yaml
global:
  redis:
    password: (redacted)

# Resource limits - per DevOps guidance 
#  intentionally not specifying limits at this time.  
master:
  resource:
    #limits:
    # cpu: 100m
    # memory: 128Mi
    requests:
     cpu: 500m
     memory: 2Gi

replica:
  # Default count would be 3.  To minimize spin-up time, at least temporarily setting to 2
  replicaCount: 2

  resource:
    #limits:
    # cpu: 100m
    # memory: 128Mi
    requests:
      cpu: 500m
      memory: 2Gi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  extraVolumes:

## First two lines are default configurations (appendonly, save)
## All other items below are customizations for this instantiation of redis
#   For redis.conf settings, see https://raw.githubusercontent.com/redis/redis/6.2/redis.conf
commonConfiguration: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled
  # AOF is better option for avoiding data loss and being able to start back
  #  up after a shutdown in a good state
  save ""
  # Update replication timeout (proof of ability to change setting)
  #repl-timeout 39
```                       

### What is the expected behavior?

ROLES, when executed on the master, should show either the host.subdomain pattern (e.g., rules-cache-redis-replicas-0.rules-cache-redis-headless) or the FQDN (host.subdomain.namespace.svc.cluster.local)

### What do you see instead?

ROLES reports as: 
`rules-cache-redis-replicas-1.`

replica.conf on replica pods contains (replica # varies depending upon which pod in the stateful set is logged into..)
```
replica-announce-port 6379
replica-announce-ip rules-cache-redis-replicas-1.
```

### Additional information

With some local experimentation, I was able to obtain the expected behavior of FQDN by adding the below line to the start-replica.sh script in scripts-configmap.yml.  Otherwise, the get_full_hostname method in that file does not have a populated HEADLESS_SERVICE variable, and the data are written to the replica.conf is effectively truncated.  

`HEADLESS_SERVICE="{{ template "common.names.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"`
