### ISSUE TITLE
[bitnami/kube-prometheus] prometheus-ca certificate instead of R3 letsencrypt certificate loaded. 

### ISSUE THREAD

**Issue by denys-haponov** [bitnami/charts#9802]
### Name and Version

6.5.1

### What steps will reproduce the bug?

not setting _**.Values.prometheus.ingress.certManager: true**_ value, results creation of cert, which will interfere with cert-manager+letsencrypt cluster issuer setup. 
 
```
prometheus:
  ingress:
    enabled: true
    hostname: "monitoring"
    tls: true
    certManager: true <===========//if ignored will create cert which mess up the letsencrypt cert process.
    annotations:
      appgw.ingress.kubernetes.io/cookie-based-affinity: true
      appgw.ingress.kubernetes.io/ssl-redirect: true
      cert-manager.io/cluster-issuer: letsencrypt-production
      kubernetes.io/ingress.class: azure/application-gateway
```

### Are you using any custom parameters or values?

workaround:
1. Deleting the certificate from secrets will trigger creation of new certificate which will go through the letsencrypt process as expected.

solution:
2. using the value .Values.prometheus.ingress.certManager , although it is mentioned as deprecated in : https://github.com/bitnami/charts/pull/7646

### What is the expected behavior?

certificate which is generated via cert-manager+clusterissuer+letsencrypt setup
of issuer R3

### What do you see instead?

certificate of issuer prometheus-ca which is created in 
https://github.com/bitnami/charts/blob/master/bitnami/kube-prometheus/templates/prometheus/tls-secrets.yaml

### Additional information

here PR of value deprecation:
https://github.com/bitnami/charts/pull/7646

to fix the issue rework of required:
https://github.com/bitnami/charts/blob/c82bdb06fc2f33ef9f30b532948d46e1fec38133/bitnami/kube-prometheus/templates/prometheus/tls-secrets.yaml#L17
