### ISSUE TITLE
Can't connect inside kubernetes cluster. 

### ISSUE THREAD

**Issue by rakibulalam** [bitnami/charts#9818]
### Name and Version

redis-16.8.5

### What steps will reproduce the bug?

```
query: SELECT * FROM current_schema()
--
Mon, Apr 18 2022 9:38:21 pm | [Nest] 1 - 04/18/2022, 3:38:21 PM ERROR [ExceptionHandler] connect ECONNREFUSED 127.0.0.1:6379
Mon, Apr 18 2022 9:38:21 pm | Error: connect ECONNREFUSED 127.0.0.1:6379
Mon, Apr 18 2022 9:38:21 pm | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)

```

### Are you using any custom parameters or values?

```
redis:
    ## @section Global parameters
  ## Global Docker image parameters
  ## Please, note that this will override the image parameters, including dependencies, configured to use the global value
  ## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
  ##

  ## @param global.imageRegistry Global Docker image registry
  ## @param global.imagePullSecrets Global Docker registry secret names as an array
  ## @param global.storageClass Global StorageClass for Persistent Volume(s)
  ## @param global.redis.password Global Redis&trade; password (overrides `auth.password`)
  ##
  global:
    imageRegistry: ""
    ## E.g.
    ## imagePullSecrets:
    ##   - myRegistryKeySecretName
    ##
    imagePullSecrets: []
    storageClass: "longhorn"
    redis:
      password: ""
  auth:
    enabled: false
  master: 
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values: ["storage-bbb", "storage-aaa","storage-test-001","storage-0001","node-e"]
  
  replica:
    replicaCount: 1
    externalMaster:
      enabled: true
    affinity: 
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values: ["storage-bbb", "storage-aaa","storage-test-001","storage-0001","node-e"]


 
```

### What do you see instead?

Looking solution
