### ISSUE TITLE
Discourse backup fails due to mismatch in pg_dump versions

### ISSUE THREAD

**Issue by manning-ncsa** [bitnami/charts#9830]
### Name and Version

bitnami/discourse 7.0.15

### What steps will reproduce the bug?

1. Backup Discourse using native admin tool
2. Upgrade discourse Helm chart version 5.2.3 to 7.0.15
3. Restore data using native admin tool.
4. Attempt to run a new backup.

### Are you using any custom parameters or values?

```yaml
diagnosticMode:
  enabled: false
host: "forum.example.com"
siteName: "My Forum"
auth:
  email: "admin@example.com"
  username: "admin"
  existingSecret: "discourse-admin"
smtp:
  enabled: true
  host: "smtp.example.com"
  port: "25"
replicaCount: 3

discourse:
  skipInstall: true
persistence:
  enabled: true
  storageClass: "-"
  accessModes:
    - ReadWriteMany
  accessMode: ReadWriteMany
  size: 15Gi
  existingClaim: "discourse-data-0-pvc"
ingress:
  enabled: false
postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: bitnami
    username: bn_discourse
    password: ""
    database: bitnami_application
    existingSecret: "discourse-db"
  architecture: standalone
  global:
    storageClass: "longhorn"
    postgresql:
      auth:
        existingSecret: "discourse-db"
  primary:
    persistence:
      existingClaim: "discourse-postgresql-pvc"
redis:
  enabled: true
  auth:
    enabled: true
    password: ""
    existingSecret: "discourse-redis"
    auth:
      existingSecret: "discourse-redis"
      existingSecretPasswordKey: "redis-password"
  architecture: standalone
  master:
    persistence:
      enabled: false
```

### What is the expected behavior?

The backup should execute properly.

### What do you see instead?

The backup fails with
```
...
[2022-04-19 16:40:13] Marking backup as running...
[2022-04-19 16:40:13] Making sure '/opt/bitnami/discourse/tmp/backups/default/2022-04-19-164012' exists...
[2022-04-19 16:40:13] Making sure '/opt/bitnami/discourse/public/backups/default' exists...
[2022-04-19 16:40:13] Updating metadata...
[2022-04-19 16:40:13] Dumping the public schema of the database...
[2022-04-19 16:40:13] pg_dump: error: server version: 14.2; pg_dump version: 13.6
[2022-04-19 16:40:13] pg_dump: error: aborting because of server version mismatch
[2022-04-19 16:40:13] EXCEPTION: pg_dump failed
...
```

### Additional information

The currently running images are:

* `docker.io/bitnami/discourse:2.8.3-debian-10-r0`
* `docker.io/bitnami/postgresql:14.2.0-debian-10-r58`
