### ISSUE TITLE
[bitnami/minio] Api ingress backend unhealthy state

### ISSUE THREAD

**Issue by Andrflor** [bitnami/charts#9857]
### Name and Version

bitnami/minio latest

### What steps will reproduce the bug?

I'm deploying to GCP using the parameters below
Everything works great except that api ingress won't access api backend service.

### Are you using any custom parameters or values?

Helm command
``` bash
helm install my-minio \
  --set 'defaultBuckets=bucket1:download\,bucket2:download' \
  --set auth.rootUser=$MINIO_USER \
  --set auth.rootPassword=$MINIO_PASS \
    bitnami/minio
```

Api ingress
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: image-mydomain-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: my-tls-secret

  rules:
  - host: image.mydomain.com

    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: my-minio
            port:
              name: minio-api
```
Console ingress
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-mydomain-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: my-tls-secret

  rules:
  - host: minio.mydomain.com

    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: my-minio
            port:
              name: minio-console
```

### What is the expected behavior?

Minio api should be found by the ingress and then accessible trough image.mydomain.com

### What do you see instead?

Service is in unhealthy state on the api ingress status
And code 502 on the image.mydomain.com url
serviceIp:9000 status unhealthy

### Additional information

Minio console is working flawlessly and is accessible trough minio.mydomain.com with all tls working
Minio api is accesible trough call from my rest-api server located in the same cluster
serviceIp:9001 status healthy
