### ISSUE TITLE
SSL Configuration Error: doesn't recognize spark-keystore.jks & spark-truststore.jks

### ISSUE THREAD

**Issue by porscheme** [bitnami/charts#9864]
### Name and Version

bitnami/spark:3

### What steps will reproduce the bug?

1. Create spark-truststore.jks using below steps
```
# Enter store password when prompted
keytool -keystore spark-truststore.jks -alias root -importcert -file rootCA.cert.pem -trustcacerts
keytool -keystore spark-truststore.jks -alias intermediate -importcert -file issuingCA.cert.pem -trustcacerts
```

2. Create spark-keystore.jks using below steps
```
# Make PKCS12 cert from crt and key pem files
openssl pkcs12 -export -in ssl.cert.pem -inkey ssl.key.pem -name spark -out spark-pkcs-12.p12
keytool -importkeystore -srckeystore spark-pkcs-12.p12 -srcstoretype PKCS12 -destkeystore spark-keystore.jks -deststoretype jks
```

3. Create K8S secret key
```
kubectl create secret generic sparksecret --from-literal=keystore_password=REDACTED --from-file=spark-keystore.jks=spark-keystore.jks --from-literal=truststore_password=REDACTED --from-file=spark-truststore.jks=spark-truststore.jks -n cohort-workbench
```

4. Deploy Sparck using helm charts

### What is the expected behavior?

SSL security enabled

### What do you see instead?

1. Below is the screen capture on master (initcontainer passed)
[Screenshot 2022-04-14 162133 PNG](https://user-images.githubusercontent.com/29828396/164157781-6492082a-105d-4081-8de8-774cde6d3a74.jpg)

2. Below is the screen capture on worker (stuck in initcontainer)
![Screenshot 2022-04-14 162133 PNG](https://user-images.githubusercontent.com/29828396/164158221-1da1d91f-8990-4a21-ae07-62628c40a0ab.jpg)

**Comment by dgomezleon** [comment]
Hi @porscheme ,

We have moved the issue to the charts repo.

Could you please let us know what parameters did you use to install the chart? Did you follow our documentation?

**Comment by porscheme** [comment]
> Hi @porscheme ,
> 
> We have moved the issue to the charts repo.
> 
> Could you please let us know what parameters did you use to install the chart? Did you follow our documentation? https://docs.bitnami.com/kubernetes/infrastructure/spark/administration/configure-security/

Thanks @dgomezleon quick reply. I'm happy to test any modifications you may suggest.

We are using official Bitnami Spark [Helm Charts](https://github.com/bitnami/charts/tree/master/bitnami/spark)
To be clear, to make it work below is what I did.
1. I made a custom image with both spark-keystore.jks & spark-truststore.jks files copied to the location /opt/bitnami/spark/conf/certs.
2. Removed below code block from initContainers in statefulset-master.yaml &  statefulset-worker.yaml files 
```
{{- else }}
if [[ -f "/certs/spark-truststore.jks" ]] && [[ -f "/certs/spark-keystore.jks" ]]; then
    cp "/certs/spark-truststore.jks" "/opt/bitnami/spark/conf/certs/spark-truststore.jks"
    cp "/certs/spark-keystore.jks" "/opt/bitnami/spark/conf/certs/spark-keystore.jks"
else
    echo "Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled."
    exit 1
fi
```

Below are my Helm values for security:
```
security:
  ## @param security.passwordsSecretName Name of the secret that contains all the passwords
  ## This is optional, by default random passwords are generated
  ##
  passwordsSecretName: ""
  ## RPC configuration
  ## @param security.rpc.authenticationEnabled Enable the RPC authentication
  ## @param security.rpc.encryptionEnabled Enable the encryption for RPC
  ##
  rpc:
    authenticationEnabled: false
    encryptionEnabled: false
  ## @param security.storageEncryptionEnabled Enables local storage encryption
  ##
  storageEncryptionEnabled: true
  ## @param security.certificatesSecretName Name of the secret that contains the certificates.
  ## It should contains two keys called "spark-keystore.jks" and "spark-truststore.jks" with the files in JKS format.
  ## DEPRECATED. Use `security.ssl.existingSecret` instead
  ##
  certificatesSecretName: ""
  ## SSL configuration
  ##
  ssl:
    ## @param security.ssl.enabled Enable the SSL configuration
    ##
    enabled: true
    ## @param security.ssl.needClientAuth Enable the client authentication
    ##
    needClientAuth: false
    ## @param security.ssl.protocol Set the SSL protocol
    ##
    protocol: TLSv1.2
    ## @param security.ssl.existingSecret Name of the existing secret containing the TLS certificates
    ## It should contains two keys called "spark-keystore.jks" and "spark-truststore.jks" with the files in JKS format.
    ##
    existingSecret: "sparksecret"
    ## @param security.ssl.autoGenerated Create self-signed TLS certificates. Currently only supports PEM certificates
    ## The Spark container will generate a JKS keystore and trustore using the PEM certificates.
    ##
    autoGenerated: false
    ## @param security.ssl.keystorePassword Set the password of the JKS Keystore
    ##
    keystorePassword: "REDACTED"
    ## @param security.ssl.truststorePassword Truststore password.
    ##
    truststorePassword: "REDACTED"
    ## Container resource requests and limits
    ## ref: https://kubernetes.io/docs/user-guide/compute-resources/
    ## We usually recommend not to specify default resources and to leave this as a conscious
    ## choice for the user. This also increases chances charts run on environments with little
    ## resources, such as Minikube. If you do want to specify resources, uncomment the following
    ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    ## @param security.ssl.resources.limits The resources limits for the container
    ## @param security.ssl.resources.requests The requested resources for the container
    ##
    resources:
      ## Example:
      ## limits:
      ##    cpu: 100m
      ##    memory: 128Mi
      limits: {}
      ## Examples:
      ## requests:
      ##    cpu: 100m
      ##    memory: 128Mi
      requests: {}
```

**Comment by dgomezleon** [comment]
Hi @porscheme, 

Sorry for the delay.

I want to understand the parameters you used with the default image since I could not reproduce the error.

Our documentation mentions the following one:

```
security.certificatesSecretName=my-secret
security.passwordsSecretName=my-passwords-secret
security.rpc.authenticationEnabled=true
security.rpc.encryptionEnabled=true
security.storageEncrytionEnabled=true
security.ssl.enabled=true
security.ssl.needClientAuth=true
```

Some of them differ from yours. Could you try the default image following this a let us know the result? Could you also use `image.debug=true` ?

**Comment by porscheme** [comment]
Thanks for the reply @dgomezleon. Thanks for taking security top priority.

I retried after setting image.debug=true but did not see any more logs than already reported.

I don't know which timezone you are located, I'm in Seattle, USA.
I'm happy to take a zoom call, if that helps.


First, I wanted to make sure SSL/TLS is working therefore I didn't enable below
```
security.ssl.needClientAuth=true
security.rpc.authenticationEnabled=true
security.rpc.encryptionEnabled=true
```
I didn't set this because doc says it's optional
```
passwordsSecretName: ""
```

I didn't set this because doc says its DEPRECATED, its was recommending security.ssl.existingSecret 
```
certificatesSecretName
```

**Comment by fmulero** [comment]
Hi @porscheme, sorry for the late response

In order to enable security using your own jks files you need to set the following values:
```yaml
security:
  passwordsSecretName: yourpasswordsecret
  ssl:
    enabled: true
    existingSecret:  yourjkssecret
```
The secret `yourpasswordsecret` should have the following structure:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: yoursecret
  namespace: yournamespace
data:
  ssl-keystore-password: REDACTED
  ssl-truststore-password: REDACTED
type: Opaque
```

If you want to use the same secret for both, jks and passwords, as you had at the beginning, you'll need to change a little the script to create the secret:
```
kubectl create secret generic sparksecret --from-literal=ssl-keystore-password=REDACTED --from-file=spark-keystore.jks=spark-keystore.jks --from-literal=ssl-truststore-password=REDACTED --from-file=spark-truststore.jks=spark-truststore.jks -n cohort-workbench

```

About the initial problem copying the jks files, Did you see any error like this at any point?

```console
 10:54:17.89 
 10:54:17.89 Welcome to the Bitnami spark container
 10:54:17.89 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-spark
 10:54:17.89 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-spark/issues
 10:54:17.89 
 10:54:17.90 INFO  ==> ** Starting Spark setup **
 10:54:17.92 ERROR ==> If you enable SSL configuration, you must mount your keystore file and specify the location in SPARK_SSL_KEYSTORE_FILE. Default value: /opt/bitnami/spark/conf/certs/spark-keystore.jks
 10:54:17.92 ERROR ==> If you enable SSL configuration, you must mount your trutstore file and specify the location in SPARK_SSL_TRUSTSTORE_FILE. Default value: /opt/bitnami/spark/conf/certs/spark-truststore.jks"
```
