### ISSUE TITLE
Bad member ID

### ISSUE THREAD

**Issue by ingvar-goryainov** [bitnami/charts#9865]
### Name and Version

bitnami/etcd 7.0.4

### What steps will reproduce the bug?
```
helm upgrade vault-etcd playtika-snapshot/etcd --install --namespace stage-sandbox-vault-etcd --version 0.1.0-CICD-34793-update-etcd-SNAPSHOT --values /home/jenkins/workspace/DeploymentPackage-1.0.134/deploymentPipelines/Helm/archive/helmValues.yml --timeout 600s --wait
```
### Are you using any custom parameters or values?
```yaml
auth:
  client:
    enableAuthentication: true
    secureTransport: true
  peer:
    enableAuthentication: true
    secureTransport: true
certManager:
  enabled: true
disasterRecovery:
  cronjob:
    enabled: true
  enabled: true
  pvc:
    storageClassName: thin-disk
image:
  debug: true
metrics:
  enabled: true
  podMonitor:
    additionalLabels:
      release: prometheus
    enabled: true
    scheme: https
persistence:
  accessModes:
    "0": ReadWriteMany
  enabled: true
  storageClass: thin-disk
replicaCount: 3
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi
startFromSnapshot:
  enabled: false
  existingClaim: ""
  snapshotFilename: ""

disasterRecovery:
  cronjob:
    enabled: true
    historyLimit: 1
    nodeSelector: {}
    podAnnotations: {}
    resources:
      limits: {}
      requests: {}
    schedule: '*/30 * * * *'
    snapshotHistoryLimit: 1
    tolerations: []
  enabled: true
  pvc:
    existingClaim: ""
    size: 2Gi
    storageClassName: thin-disk
image:
  debug: true
  pullPolicy: IfNotPresent
  registry: docker-hub.artifactory.playticorp.com
  repository: bitnami/etcd
  tag: 3.4.18-debian-10-r14
persistence:
  accessModes:
    - ReadWriteMany
  enabled: true
  size: 8Gi
  storageClass: thin-disk
podManagementPolicy: Parallel
```
### What is the expected behavior?

All etcd pods are in the "Running" state after the upgrade process.

### What do you see instead?

**Pod's logs**
```console
etcd 17:32:14.70 Welcome to the Bitnami etcd container
etcd 17:32:14.70 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-etcd
etcd 17:32:14.70 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-etcd/issues
etcd 17:32:14.70
etcd 17:32:14.71 INFO  ==> ** Starting etcd setup **
etcd 17:32:14.72 INFO  ==> Validating settings in ETCD_* env vars..
etcd 17:32:14.72 INFO  ==> Initializing etcd
etcd 17:32:14.72 INFO  ==> Generating etcd config file using env variables
etcd 17:32:14.74 INFO  ==> Detected data from previous deployments
etcd 17:32:14.90 DEBUG ==> etcd-0.etcd-headless.stage-sandbox-vault-etcd.svc.cluster.local:2379 endpoint is active
etcd 17:32:15.12 DEBUG ==> etcd-2.etcd-headless.stage-sandbox-vault-etcd.svc.cluster.local:2379 endpoint is active
etcd 17:32:15.12 INFO  ==> Updating member in existing cluster
Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex

$ kubectl -n stage-sandbox-vault-etcd describe po vault-etcd-2
etcd 12:13:33.03 ERROR ==> Unhealthy endpoint!
  Warning  Unhealthy  6s (x11 over 76s)  kubelet  (combined from similar events): Liveness probe failed: {"level":"warn","ts":"2022-04-21T12:14:53.074Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-f4ceb2c7-de11-4931-9174-d6f2fe8bea12/vault-etcd-2.vault-etcd-headless.stage-sandbox-vault-etcd.svc.cluster.local:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.108.77.22:2379: connect: connection refused\""}
vault-etcd-2.vault-etcd-headless.stage-sandbox-vault-etcd.svc.cluster.local:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Error: unhealthy cluster
etcd 12:14:53.07 ERROR ==> Unhealthy endpoint!
  Normal   Killing            6s  kubelet  Container etcd failed liveness probe, will be restarted
  Warning  FailedPreStopHook  6s  kubelet  Exec lifecycle hook ([/opt/bitnami/scripts/etcd/prestop.sh]) for Container "etcd" in Pod "vault-etcd-2_stage-sandbox-vault-etcd(ae9bb6b4-d75c-44d7-9f5a-5df1d3f107b0)" failed - error: command '/opt/bitnami/scripts/etcd/prestop.sh' exited with 128: Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex
, message: "Error: bad member ID arg (strconv.ParseUint: parsing \"\": invalid syntax), expecting ID in Hex\n"
```

**Comment by fmulero** [comment]
Hi @ingvar-goryainov 

I am trying to reproduce your issue without success. I'll share with you all the stepsI am following to try to find any clue:
```console
$ kubectl create ns monitoring
$ kubectl create namespace stage-sandbox-vault-etcd
$ helm install etcd bitnami/etcd --namespace stage-sandbox-vault-etcd --version 7.0.3 -f values.yaml --wait
$ export ETCD_ROOT_PASSWORD=$(kubectl get secret --namespace "stage-sandbox-vault-etcd" etcd -o jsonpath="{.data.etcd-root-password}" | base64 --decode)
$ helm upgrade etcd bitnami/etcd --namespace stage-sandbox-vault-etcd --version 7.0.4 -f values.yaml --set auth.rbac.rootPassword=$ETCD_ROOT_PASSWORD
```
And this is the content of my values.yaml file (I disabled authentication to simplify the scenario):
```yaml
auth:
  client:
    enableAuthentication: false
    secureTransport: false
  peer:
    enableAuthentication: false
    secureTransport: false
certManager:
  enabled: true
disasterRecovery:
  cronjob:
    enabled: true
  enabled: true
  pvc:
    storageClassName: hostpath
image:
  debug: true
metrics:
  enabled: true
  podMonitor:
    additionalLabels:
      release: prometheus
    enabled: true
    # scheme: https
persistence:
  accessModes:
    - ReadWriteMany
  enabled: true
  storageClass: hostpath
replicaCount: 3
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi
startFromSnapshot:
  enabled: false
  existingClaim: ""
  snapshotFilename: ""

disasterRecovery:
  cronjob:
    enabled: true
    historyLimit: 1
    nodeSelector: {}
    podAnnotations: {}
    resources:
      limits: {}
      requests: {}
    schedule: '*/30 * * * *'
    snapshotHistoryLimit: 1
    tolerations: []
  enabled: true
  pvc:
    existingClaim: ""
    size: 1Gi
    storageClassName: hostpath
image:
  debug: true
  # pullPolicy: IfNotPresent
  # registry: docker-hub.artifactory.playticorp.com
  # repository: bitnami/etcd
  # tag: 3.4.18-debian-10-r14
persistence:
  accessModes:
    - ReadWriteMany
  enabled: true
  size: 1Gi
  storageClass: hostpath
podManagementPolicy: Parallel
```

Could you also check the content and permissions of the following file '/bitnami/etcd/data/member_id'?
