### ISSUE TITLE
[bitnami/airflow] Git permission error

### ISSUE THREAD

**Issue by kodeine** [bitnami/charts#9879]
### Name and Version

bitnami/airflow 12.2.0

### What steps will reproduce the bug?

Use git repository for dags and plugins

### Are you using any custom parameters or values?

yes

### What do you see instead?

<img width="743" alt="image" src="https://user-images.githubusercontent.com/8620059/164611503-dda25145-c8c8-428f-adc7-65276d570a58.png">

**Comment by carrodher** [comment]
In order to reproduce the issue on our side, could you specify what parameters are you using?

**Comment by b97390022** [comment]
I have faced the same issue, and probably cause by a release of the git 2.35.2 security update which fixes vulnerabilities described here [https://github.blog/2022-04-12-git-security-vulnerability-announced/](url).
You can consider to try out this options
[https://stackoverflow.com/questions/71901632/fatal-unsafe-repository-home-repon-is-owned-by-someone-else](url)
and my choice is just simply change the image tag to 2.35.1
![image](https://user-images.githubusercontent.com/37010293/164624424-4937efff-e694-4c29-b8fd-e7fe371d7a88.png)

**Comment by addisonjones-gc** [comment]
After looking at this for a bit on Friday, it looks like the directory `"/dags_{{ include "airflow.git.repository.name" . }}"`  is owned by root, but in the 1001 user group. Would that cause any issues with permissions since the container is run as user 1001?

**Comment by javsalgar** [comment]
Hi,

Would it make sense to add these commands in the init container?

```
git config --global --add safe.directory "/dags_{{ include "airflow.git.repository.name" . }}"
```

**Comment by addisonjones-gc** [comment]
> Hi,
> 
> Would it make sense to add these commands in the init container?
> 
> ```
> git config --global --add safe.directory "/dags_{{ include "airflow.git.repository.name" . }}"
> ```
> 
> 

I think that makes great sense for the time being while they sort out the git Docker container repo

**Comment by javsalgar** [comment]
Hi,

Thanks! We will work on it. If you want to speed up the process, feel free to submit a PR and we will review it.

**Comment by addisonjones-gc** [comment]
So when trying to add the git config section into the `sync-repositories` container, I'm getting the following error: 
```error: could not lock config file //.gitconfig: Permission denied```

Below is what I'm trying in the `_git_helpers.tpl` file:
```yaml
  args:
    - -ec
    - |
      [[ -f "/opt/bitnami/scripts/git/entrypoint.sh" ]] && . /opt/bitnami/scripts/git/entrypoint.sh
    {{- if .context.Values.git.dags.enabled }}
      {{- range .context.Values.git.dags.repositories }}
      git config --global --add safe.directory "/dags_{{ include "airflow.git.repository.name" . }}"
      {{- end }}
    {{- end }}
    {{- if .context.Values.git.plugins.enabled }}
      {{- range .context.Values.git.plugins.repositories }}
      git config --global --add safe.directory "/plugins_{{ include "airflow.git.repository.name" . }}"
      {{- end }}
    {{- end }}
      while true; do
      {{- if .context.Values.git.dags.enabled }}
        {{- range .context.Values.git.dags.repositories }}
          cd /dags_{{ include "airflow.git.repository.name" . }} && git pull origin {{ .branch }} || true
        {{- end }}
      {{- end }}
      {{- if .context.Values.git.plugins.enabled }}
        {{- range .context.Values.git.plugins.repositories }}
          cd /plugins_{{ include "airflow.git.repository.name" . }} && git pull origin {{ .branch }} || true
        {{- end }}
      {{- end }}
          sleep {{ default "60" .context.Values.git.sync.interval }}
      done
```

And here's the compiled version in a sample template output: 
```yaml
        - name: sync-repositories
          image: "docker.io/bitnami/git:2.36.0-debian-10-r3"
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          command:
            - /bin/bash
          args:
            - -ec
            - |
              [[ -f "/opt/bitnami/scripts/git/entrypoint.sh" ]] && . /opt/bitnami/scripts/git/entrypoint.sh
              git config --global --add safe.directory "/dags_airflow-example-dags"
              while true; do
                  cd /dags_airflow-example-dags && git pull origin main || true
                  sleep 60
              done
```

Any thoughts? Seems a little weird that there's a double // in front of the `.gitignore` file name in the error, but unsure if that's expected.

**Comment by gcalmettes** [comment]
Hello,
Stumbled upon the same problem, and confirming that the workaround works.
Adding this in the values.yaml:

```
  git:
    dags:
      enabled: true
      repositories:
        - repository: https://myrepo.git
          name: some-dags
          branch: some_branch
    sync:
      args:
        - -ec
        - |
          [[ -f "/opt/bitnami/scripts/git/entrypoint.sh" ]] && . /opt/bitnami/scripts/git/entrypoint.sh
          while true; do
              cd /dags_some-dags && git config --global --add safe.directory $(pwd) && git pull origin some_branch || true
              sleep 60
          done
      extraEnvVars:
        - name: HOME
          value: "/tmp"
```
