### ISSUE TITLE
[bitnami/kube-prometheus] Rendering fails if global.labels is used

### ISSUE THREAD

**Issue by BernhardGruen** [bitnami/charts#9886]
### Name and Version

bitnami/kube-prometheus 6.9.5

### What steps will reproduce the bug?

1. Use this as `value.yaml`
```yaml
global:
  labels:
    some-label1: value
```
2. Render the chart
3. See followin error message that rendering fails
> Error: YAML parse error on kube-prometheus/templates/alertmanager/alertmanager.yaml: error converting YAML to JSON: yaml: line 10: mapping values are not allowed in this context

### Are you using any custom parameters or values?

```yaml
global:
  labels:
    some-label1: value
```

### What do you see instead?

Error: YAML parse error on kube-prometheus/templates/alertmanager/alertmanager.yaml: error converting YAML to JSON: yaml: line 10: mapping values are not allowed in this context

### Additional information

I already reduced this to the essential parts and I really hope it is easy to fix this bug.

If I disable alertmanager (enabled by default) the next error message that appears is for core-dns/service.yaml. Therefore I assume that this must be an error in the named template that generates those labels.

Versions since 6.9.0 are affected by this bug. 6.8.5 was and is working correctly.

**Comment by BernhardGruen** [comment]
I assume the error was introduced by this code change:
https://github.com/bitnami/charts/commit/d6588d0ca793f1ab6590b21b48f0bca8ab4965c9#diff-ee9478ae1fceeae3fa3a37f39a25ace3ac83abfe08bd46f56d7ff05fdc888d43R72-R75

**Comment by miguelaeh** [comment]
Could you please execute `helm template` and share the output of the failing file? It is possible that the `-` included in the change you mentioned breaks the YAML due to removing spaces.

**Comment by BernhardGruen** [comment]
This is the requested output:
```yaml
$ helm template bitnami/kube-prometheus -f values.yaml --debug --show-only templates/alertmanager/alertmanager.yaml
install.go:178: [debug] Original chart version: ""
install.go:199: [debug] CHART PATH: ~/.cache/helm/repository/kube-prometheus-6.9.5.tgz

---
# Source: kube-prometheus/templates/alertmanager/alertmanager.yaml

apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: RELEASE-NAME-kube-promethe-alertmanager
  namespace: default
  labels:
    app.kubernetes.io/name: kube-prometheus
    helm.sh/chart: kube-prometheus-6.9.5
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helmsome-label1: value
    app.kubernetes.io/component: alertmanager
spec:
  replicas: 1
  serviceAccountName: RELEASE-NAME-kube-promethe-alertmanager
  image: docker.io/bitnami/alertmanager:0.24.0-debian-10-r24
  listenLocal: false
  externalUrl: http://RELEASE-NAME-kube-promethe-alertmanager.default:9093/
  portName: "web"
```
And this is the line with the error (which contains `some-label1: value` at the end):
```
    app.kubernetes.io/managed-by: Helmsome-label1: value
```

I still assume that the lines I posted earlier are the problematic ones and there must be some `-` that eats too much white spaces.
