### ISSUE TITLE
[bitnami/mariadb-galera] Cannot start cluster when all pods of the stateful set have been down

### ISSUE THREAD

**Issue by EugenMayer** [bitnami/charts#9893]
### Name and Version

bitname/mariadb-galera 7.1.7

### What steps will reproduce the bug?

1. Deploy a mariadb-galera chart with 3 replicas on 3 workers
2. shutdown all 3 workers (and once or one after the other, but in the end, all should be down at the same time)
3. start all 3 workers again

MariaDB pod should fail to start since it cannot boostrap. One has to

- scale down the replicas to 1
- start use `forceSafeToBootstrap=true` to bootstrap
- remove force bootstrap and redeploy again (still 1 replica only)
- no scale up the replicas to 3

This is fairly complicated / involves more downtime then wanted. Are there any ways to do this any better?

### Are you using any custom parameters or values?

```
existingSecret: "mariadb-user-creds"

persistence:
  enabled: true
  storageClass: 'local-path'
  accessModes:
    - ReadWriteOnce
  size: 5Gi

galera:
  name: mariadb-cluster
  bootstrap:
    forceSafeToBootstrap: false
    forceBootstrap: false
    
replicaCount: 3
```

### What is the expected behavior?

be able to boostrap for the pod that is defined as boostrap node - let all other pods bootstrap from the bootstrap server

### What do you see instead?

replicas fail to boostrap since i suppose they do not understand who should be the lead-boostrap
