### ISSUE TITLE
[binami/nginx] nginx binary in nginx-ingress-controller does not support ngx_stream_realip_module

### ISSUE THREAD

**Issue by guoxiaod** [bitnami/charts#9908]
### Name and Version

bitnami/nginx-ingress-controller:1.1.3

### What steps will reproduce the bug?

1. install nginx-ingress-controller
    `helm install  --namespace ingress-nginx  -f ./values.yaml ingress-nginx nginx-ingress-controller/`
2. setup configmap like this:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-nginx-ingress-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  enable-real-ip: "true"
  proxy-real-ip-cidr: "172.20.0.0/16"
```
3. we will see errors in the k8s :
 "set_real_ip_from" directive is not allowed here in /tmp/nginx-cfg1243224824:7507 nginx: [emerg] "set_real_ip_from" directive is not allowed here in /tmp/nginx-cfg1243224824:7507 nginx: configuration file /tmp/nginx-cfg1243224824 test failed

4. in the stream config of nginx.tmpl, we can see,
```
    {{ if $cfg.EnableRealIp }}
    {{ range $trusted_ip := $cfg.ProxyRealIPCIDR }}
    set_real_ip_from    {{ $trusted_ip }};
    {{ end }}
    {{ end }}
```
5. but we can not find `--with-stream_realip_module` configuration parameter in the nginx configure arguments: 
```
/usr/local/nginx/sbin/nginx -V 2>&1 |sed -e 's/ /\n/g'|grep realip
--with-http_realip_module
--with-http_realip_module
```

### What is the expected behavior?

build nginx with `--with-stream_realip_module `

or

remove `set_real_ip_from` directive from `nginx.tmpl`

### What do you see instead?

nothing
