### ISSUE TITLE
failed to get memory utilization: missing request for memory

### ISSUE THREAD

**Issue by vanhonit** [bitnami/charts#9928]
### Name and Version

bitnami/redis

### What steps will reproduce the bug?

I am using the bitnami/redis repo when I try to enable the option autoscaling.enabled=true the HPA return error "failed to get memory utilization: missing request for memory" and "failed to get CPU utilization: missing request for CPU". I installed a metrics server on the Cluster and other HPA configurations are working well.
Here is my configuration:
```yaml
architecture: replication
  replica:
    replicaCount: 2
    autoscaling:
      enabled: true
      targetMemory: 80
      targetCPU: 80
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "125m"
        memory: "200Mi"
  sentinel:
    enabled: true
    masterSet: tabula-redis
  auth:
    enabled: false
  pdb:
    create: true
  metrics:
    enabled: true
    prometheusRule:
      enabled: true
    serviceMonitor:
      enabled: true
```

### What do you see instead?

<img width="362" alt="Screen Shot 2022-04-26 at 10 36 09" src="https://user-images.githubusercontent.com/1215676/165215496-87b8367a-9789-4d43-8de7-2dd79310d717.png">
