### ISSUE TITLE
Jmx serviceMonitor targets the wrong metrics service

### ISSUE THREAD

**Issue by nfeltrin-dkb** [bitnami/charts#9936]
### Name and Version

bitnami/kafka 16.2.8

### What steps will reproduce the bug?

Deploy the chart with `metrics.jmx.enabled=true` and `metrics.serviceMonitor.enabled=true`, without any `commonLabels`.

### Are you using any custom parameters or values?

```yaml
metrics:
  jmx:
    enabled: true
  serviceMonitor:
    enabled: true
commonLabels:
```

### What is the expected behavior?

The serviceMonitor matchLabel should match the labels in the service

### What do you see instead?

The serviceMonitor is looking for a hardcoded `app.kubernetes.io/component: kafka` label, while the service has a `app.kubernetes.io/component: metrics` hardcoded label. This is not the case for the exporter serviceMonitor/service which both have `app.kubernetes.io/component: metrics`.
