### ISSUE TITLE
[bitnami/postgresql-ha] postgresql-ha service monitor don't work

### ISSUE THREAD

**Issue by Joda89** [bitnami/charts#9937]
### Name and Version

bitnami/postgresql-ha 9.0.3

### What steps will reproduce the bug?

install postgresql-ha with this config:
```
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```
on serviceMonitor we have this :
```
spec:
...
  selector:
    matchLabels:
      app.kubernetes.io/component: postgresql
      app.kubernetes.io/instance: postgresql-ha
      app.kubernetes.io/name: postgresql-ha
      prometheus: kube-prometheus
```
but on the service metrics we don't have the label "prometheus: kube-prometheus" :
```
app.kubernetes.io/component: postgresql
app.kubernetes.io/instance: postgresql-ha
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: postgresql-ha
helm.sh/chart: postgresql-ha-8.6.13
```

### Are you using any custom parameters or values?

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

### What is the expected behavior?

we need to add the label "prometheus: kube-prometheus" on service metrics.

### What do you see instead?

the service monitor don't see any pod of portgresql

### Additional information
fix ==> https://github.com/bitnami/charts/pull/9938
_No response_
