### ISSUE TITLE
[bitnami/redis-cluster] Error introduced in svc-cluster-external-access.yaml with new loadBalancerSourceRanges 

### ISSUE THREAD

**Issue by kOstovic** [bitnami/charts#9943]
### Name and Version

bitnami/redis-cluster 7.5.0

### What steps will reproduce the bug?

Values yaml which works with 7.4.8 and does not work with new 7.5.0 chart altho nothing changed..bug has been introduced if new if statement for loadBalancerSourceRanges

because of an error:
Error: INSTALLATION FAILED: template: redis-cluster/templates/svc-cluster-external-access.yaml:33:24: executing "redis-cluster/templates/svc-cluster-external-access.yaml" at <.Values.externalAccess.service.type>: can't evaluate field Values in type int

```
cluster:
  externalAccess:
    enabled: true
    service:
      type: LoadBalancer
      annotations: {}
      loadBalancerIP: 
        - 10.0.3.21
        - 10.0.3.22
        - 10.0.3.23
        - 10.0.3.24
        - 10.0.3.25
        - 10.0.3.26
      loadBalancerSourceRanges: []
      port: 6379
```      
      

### What do you see instead?

Error: INSTALLATION FAILED: template: redis-cluster/templates/svc-cluster-external-access.yaml:33:24: executing "redis-cluster/templates/svc-cluster-external-access.yaml" at <.Values.externalAccess.service.type>: can't evaluate field Values in type int
