### ISSUE TITLE
[Bitnami Grafana] Support `ha_peers` configuration in Bitnami Grafana Helm? How to make sure nodeIp list dynamicly?

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [bitnami/charts#9960]
### Name and Version

grafana-7.6.24       AppVersion=8.4.5

### What steps will reproduce the bug?

nothing

### Are you using any custom parameters or values?
```yaml
global:
  storageClass: "csi-disk"

service:
  type: LoadBalancer
  annotations:
    kubernetes.io/elb.class: "union"
    kubernetes.io/elb.id: "eac9000e-2407-4d06-818b-c5be9ff7c063"
    kubernetes.io/elb.lb-algorithm: "ROUND_ROBIN"
    kubernetes.io/elb.health-check-flag: "on"
admin:
  user: admin
  password: admin#yB4qEJFx37

## Create datasources from a custom secret
## The secret must contain the files
## @param datasources.secretName Secret name containing custom datasource files
##
#datasources:
#  secretName: "grafana-alertmanager-datasource"

## Ldap configuration for Grafana
##
ldap:
  ## @param ldap.enabled Enable LDAP for Grafana
  ##
  enabled: false
  ## @param ldap.allowSignUp Allows LDAP sign up for Grafana
  ##
  allowSignUp: false
  ## @param ldap.configuration Specify content for ldap.toml configuration file
  ## e.g:
  ## configuration: |-
  ##   [[servers]]
  ##   host = "127.0.0.1"
  ##   port = 389
  ##   use_ssl = false
  ##   ...
  ##
  configuration: |-
    [[servers]]
    # Ldap server host (specify multiple hosts space separated)
    host = "uid.bestsign.tech"
    # Default port is 389 or 636 if use_ssl = true
    port = 636
    # Set to true if LDAP server should use an encrypted TLS connection (either with STARTTLS or LDAPS)
    use_ssl = true
    # If set to true, use LDAP with STARTTLS instead of LDAPS
    start_tls = false
    # set to true if you want to skip SSL cert validation
    ssl_skip_verify = true
    # set to the path to your root CA certificate or leave unset to use system defaults
    # root_ca_cert = "/path/to/certificate.crt"
    # Authentication against LDAP servers requiring client certificates
    # client_cert = "/path/to/client.crt"
    # client_key = "/path/to/client.key"

    # Search user bind dn
    bind_dn = "OU=BestSign,DC=bestsign,DC=com"
    # Search user bind password
    # If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
    bind_password = 'Secret20160304'

    # User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
    # Allow login from email or username, example "(|(sAMAccountName=%s)(userPrincipalName=%s))"
    search_filter = "(cn=%s)"

    # An array of base dns to search through
    search_base_dns = ["dc=bestsign,dc=com"]

    # group_search_filter = "(&(objectClass=posixGroup)(memberUid=%s))"
    # group_search_filter_user_attribute = "distinguishedName"
    # group_search_base_dns = ["ou=groups,dc=grafana,dc=org"]

persistence:
  enabled: false

## @section Grafana Image Renderer parameters
# The Grafana Image Renderer is a plugin for Grafana that uses headless Chrome to render panels and dashboards as PNG images.
imageRenderer:
  ## @param imageRenderer.enabled Enable using a remote rendering service to render PNG images
  ##
  enabled: true

grafana:
  replicaCount: 2
  extraEnvVars:
    - name: GF_PLUGINS_ENABLE_ALPHA
      value: "true"
    - name: GF_DATABASE_URL
      value: "mysql://grafana:XHnmElxpQq@grafana-mysql.thanos:3306/grafana"
    - name: GF_REMOTE_CACHE_CONNSTR
      # username:password@tcp(127.0.0.1:3306)/dbname
      value: "grafana:XHnmElxpQq@tcp(grafana-mysql.thanos:3306)/grafana"
```
### What is the expected behavior?

deduplicates alert notifications across Grafana instances

### What do you see instead?

alert duplication

### Additional information

When I use bitnami/grafana to deploy high-availability grafana, I don't know how to configurate `ha_peers` within [unified_alerting] section. It's hard to make sure nodeIp list when deploy.
https://grafana.com/docs/grafana/latest/alerting/unified-alerting/high-availability/
