### ISSUE TITLE
backing up influxdb to gcp bucket

### ISSUE THREAD

**Issue by yspassivelogic** [bitnami/charts#9975]
### Name and Version

influxdb 4.0.12 

### What steps will reproduce the bug?

I setup the values.yaml
```yaml
    google:
      enabled: enabled
      secret: "my-k8s-secret-name"
      secretKey: "key.json"
      existingSecret: ""
      bucketName: "gs://bucket/influxdb"
```
but I am not seeing any backups in my GCP bucket

I also cannot check inside the influxdb pod how this is setup

1. how do I check inside the influxdb pod if this is actually backing to GCP?
2. what is the difference between secret and existingSecret?

### Are you using any custom parameters or values?

I setup the values.yaml
```yaml
    google:
      enabled: enabled
      secret: "my-k8s-secret-name"
      secretKey: "key.json"
      existingSecret: ""
      bucketName: "gs://bucket/influxdb"
```
### What is the expected behavior?

influx backup to the GCP bucket

### What do you see instead?

nothing
