### ISSUE TITLE
RabbitMQ cannot start on Openshift without manipulating volumePermission initContainer runAsUser

### ISSUE THREAD

**Issue by mhhhkay** [bitnami/charts#9984]
### Name and Version

bitnami/rabbitmq

### What steps will reproduce the bug?

Helm install current RabbitMQ Chart below OCP at least 4.7+
with
 
```yaml
volumePermissions.enabled=true
podSecurityContext.enabled=true 
  runAsUser: 1000800000
  fsGroup: 1000800000
```

### What is the expected behavior?

The pod should be scheduled

### What do you see instead?

Pod cannot be scheduled even with `securityContext.enabled=true` as `fsGroup` is not being picked by the `initContainer` for `volumePermissions`

### Additional information

please refer https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/templates/statefulset.yaml#L98 

why do we not use `.Values.podSecurityContext.runAsUser` in that case aswell?

**Comment by mhhhkay** [comment]
Think i found a referrable Issue https://github.com/bitnami/charts/issues/8932 which has gone stale... any update on this?

**Comment by joancafom** [comment]
Hi @mhhhkay !

As mentioned in the issue you linked, it seems that the `runAsUser` param is not configurable for RabbitMQ. No one has contributed to this date, so unfortunately we don't have any updates on the matter. Would you like to send a PR implementing the changes? The team will be more than happy to review it :) 

You can take `bitnami/redis` as a good example: https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/master/application.yaml#L329

**Comment by DarkChaos** [comment]
Hi @mhhhkay,

I was going to implement the PR when I realized that you only need to disable the securityContexts.
```
containerSecurityContext:
  enabled: false
podSecurityContext:
  enabled: false
```

OpenShift takes care of setting the right SecurityContext with the right runAsUser
