### ISSUE TITLE
[bitnami/kafka] `zookeeperChrootPath` is ignored in when using `externalZookeeper.servers`.

### ISSUE THREAD

**Issue by geertp-ngdata** [bitnami/charts#9989]
### Name and Version

bitnami/kafka 3.1.0

### What steps will reproduce the bug?

1. Deploy bitnami/zookeeper as standalone chart with 3 replicas.
2. Deploy bitnami/kafka using the standalone zookeeper pods as externalZookeeper, and specify a zookeeperChrootPath
3. Result: the zookeeperChrootPath is ignored, and kafka creates nodes in the zookeeper root /

### Are you using any custom parameters or values?
```yaml
zookeeper:
  enabled: false
zookeeperChrootPath: "/kafka"
externalZookeeper:
  servers:
  - zookeeper-0.zookeeper-headless
  - zookeeper-1.zookeeper-headless
  - zookeeper-2.zookeeper-headless
```
### What is the expected behavior?

All kafka data for zookeeper should be written in the /kafka sub-folder

```
I have no name!@zookeeper-1:/$ zkCli.sh ls -R /kafka
/opt/bitnami/java/bin/java
Connecting to localhost:2181

WATCHER::

WatchedEvent state:SyncConnected type:None path:null
/kafka
/kafka/admin
/kafka/brokers
/kafka/cluster
/kafka/config
/kafka/consumers
/kafka/isr_change_notification
/kafka/latest_producer_id_block
/kafka/log_dir_event_notification
/kafka/admin/delete_topics
/kafka/brokers/ids
/kafka/brokers/seqid
/kafka/brokers/topics
/kafka/cluster/id
/kafka/config/brokers
/kafka/config/changes
/kafka/config/clients
/kafka/config/ips
/kafka/config/topics
/kafka/config/users

```

### What do you see instead?

```
I have no name!@zookeeper-1:/$ zkCli.sh ls -R /
/opt/bitnami/java/bin/java
Connecting to localhost:2181

WATCHER::

WatchedEvent state:SyncConnected type:None path:null
/admin
/brokers
/cluster
/config
/consumers
...
```

**Comment by geertp-ngdata** [comment]
There's a simple, but ugly workaround:

```yaml
zookeeper:
  enabled: false
externalZookeeper:
  servers:
  - zookeeper-0.zookeeper-headless
  - zookeeper-1.zookeeper-headless
  # appending /kafka to the last server to simulate zookeeperChrootPath
  - zookeeper-2.zookeeper-headless/kafka
```
